### ISSUE TITLE
[FEA] Return null for the row where null exists in `starts`, or `sizes`, or `steps`

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#10012]
https://github.com/rapidsai/cudf/pull/9839 has implemented the per-list sequence, but it will blow up when null exists in `starts`, or `sizes`, or `steps`.

Asking to return nulls silently instead (or can choose to return null) for this case is to align with the behavior of Spark. Spark will return nulls for rows that contain at least one `null`. For example, 

start | end | step | sequence(start, end, step)
-- | -- | -- | --
0 | 5 | 1 | [0, 1, 2, 3, 4, 5]
null | 2 | 2 | null
-3 | null | 1 | null
1 | 3 | null | null
null | 3 | null | null

**Comment by jrhemstad** [comment]
We specifically chose not to emulate this behavior. This behavior can be emulated in the plugin by stripping nulls in the inputs and then ANDing the output with the original input null mask.

**Comment by ttnghia** [comment]
Firstly, you do pre-processing, setting `start = end = step = DataType(0)` in the plugin for the row containing null. By doing so, the corresponding output list from cudf will be an empty list. Then, you do post-processing (also in the plugin), setting null for such list.

**Comment by firestarman** [comment]
Thanks for the info.
Is there any reason not to do this ? I think handling it in plugin is not as easy as in cudf.

**Comment by GregoryKimball** [comment]
Closing based on discussion in #9839
