### ISSUE TITLE
[FEA] Casting String to Decimal with built-in rounding

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#10023]
**Is your feature request related to a problem? Please describe.**
When casting a string value of say "29.895" to Decimal(scale:-3) = 29.895 which is correct. But what if we want to cast it to Decimal(scale:-2)? The correct answer could be 29.89 or 2.90 depending on whether the user wants the answer to be rounded up. 

**Describe the solution you'd like**
Cudf should give the user control if he wants to round the value according to a RoundingMode passed in to the `cast` method 

**Describe alternatives you've considered**
The only alternative is to cast the string value to a bigger scale and then round the result it. e.g. col{"29.895"}.cast(decimal(scale:-3) => col{29.895}.round(2) => col{29.90}. This works fine as long as the value can fit within 128-bit fixed point but fails to achieve the desired result otherwise. This is why we need to be able to cast a string to decimal with a built-in rounding which can be passed in.

**Additional context**
In Spark, when casting a string to a decimal, if the scale is larger than can fit in the desired type it will round the result. To match this behavior we will cast the string to a value with a larger scale and then round the result. This results in us only being able to support up to a Decimal(37, *) value. But if we have access to the raw string we should be able to look at the next digit when parsing and use that to decide if we need to round or not. This sounds like something that would be good to try and do in CUDF.

For more background: https://github.com/NVIDIA/spark-rapids/issues/4182

**Comment by davidwendt** [comment]
None of the `std::string` to number conversion functions `std:stol, std::stod, etc` perform rounding on the digit characters in the input string. I think the libcudf behavior should align with C++ standard library.
