### ISSUE TITLE
[FEA] Implement `DataFrame.select_dtypes`

### ISSUE THREAD

**Issue by wbadart** [rapidsai/cudf#1003]
The [`select_dtypes`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.select_dtypes.html) method on pandas DataFrames lets you directly examine the subset of a DataFrame with the types you're interested in. Adding this feature doesn't directly solve any major game-changing problems with the library, but it does bring us one step closer to feature parity with pandas.

Here's the most concise currently available alternative I could think of:

    subset = df.drop(df.columns[df.dtypes != int])

But this doesn't scale well if you're looking for multiple data types. With `select_dtypes` implemented, this:

    subset = df.drop(df.columns[(df.dtypes != int) & (df.dtypes != float) & (...)])

could be written as:

    subset = df.select_dtypes(int, float, ...)

`drop` forces you to invert the logic of selecting the data types. So, where the `select_dtypes` expression reads "select the columns of type int and type float from df," the `drop` expression reads "give me df but without columns that aren't int and aren't float." Definitely fewer logical steps in the former :)

---

Footnote:

I wanted to note that while it adds a couple characters, the `drop` expression reads a little nicer if you apply de morgan's law and give the mask a name:

    target_dtypes = (df.dtypes == int) | (df.dtypes == float) | (...)
    subset = df.drop(df.columns[~target_dtypes])

In case anyone else was looking for a workaround!

**Comment by AK-ayush** [comment]
PR #1066 added the this feature in branch-0.6. I believe this issue can be marked as done.

**Comment by wbadart** [comment]
Agreed! Would like to see the `exclude` keyword added at some point, but that can be a separate issue.
