### ISSUE TITLE
[BLOG] Blog post on improved UDF functionality

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#10051]
(experimenting with using GitHub issues to track blog posts)

Our [previous blog post](https://medium.com/rapids-ai/user-defined-functions-in-rapids-cudf-2d7c3fc2728d) on user-defined functions (UDFs) is dated. We should publish one that highlights improvements to UDFs since then.

**Comment by brandon-b-miller** [comment]
With https://developer.nvidia.com/blog/prototyping-faster-using-udfs-and-new-cudf-features/ I am closing this.
