### ISSUE TITLE
[FEA] Add File Statistic when writing the ORC file

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#10075]
Even with https://github.com/rapidsai/cudf/pull/10041 adding Statistic in RowIndex, CUDF still does not support writing the whole File Statistics into the ORC file.

## Why do we need this FEA?

Spark added a new FEA about aggregate pushdown for ORC/Parquet file format as of Spark 3.3.0, which pushes the aggregate to DataSource to calculate the aggregation.

Typically, for ORC, it will read File Statistics from the ORC file and get the column stats and finally do the aggregate(max/min/count) without reading any real data of the ORC file. which can remarkably improve the performance.

But if there is no File Statistic in the ORC file, Spark will throw an exception.

**Comment by amahussein** [comment]
There is a standing bug #5826 that points to missing statistics for chunk mode.

**Comment by vuule** [comment]
@wbo4958 I think the issue should be fixed by https://github.com/rapidsai/cudf/pull/10694
Is anything else pending here?
