### ISSUE TITLE
Improvements in `hash_functions.cuh`

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10081]
The file `hash_functions.cuh` has quite a bit of room for cleanup and improvement.

- Use `std::byte` more broadly.
- Reduce the use of magic values in hash functions.
- Separate translation units if possible -- to what extent can we avoid having a single large header?
- Make error messages more consistent.
- Use `compute_bytes` approach instead of re-implementing hash function in `string_view` template instantiation. (Make sure [un]aligned reads are handled correctly.)

See PRs for reference: comments in #9919, ongoing SHA work in #9215, refactors in #10379.

### Additional context

> What about `std::byte`, using `std::to_integer` to convert to the integer type needed at any point where we need computation other than the operators supported on `std::byte` (only supports bitwise operations)?

_Originally posted by @harrism in https://github.com/rapidsai/cudf/pull/9919#discussion_r781625077_

**Comment by bdice** [comment]
This is still relevant. I aim to work on a few more of these ideas after #11296, when I can also move `SparkMurmurHash3_32` out of `hash_functions.cuh`. See also: https://github.com/rapidsai/cudf/pull/11292#discussion_r925887225

**Comment by bdice** [comment]
We should also add documentation to detail methods in `hashing.hpp`.

**Comment by GregoryKimball** [comment]
@bdice We've made some improvements to `hash_functions.cuh`, should we close this?

**Comment by vyasr** [comment]
@bdice do you still want to do anything here?

**Comment by bdice** [comment]
We haven't adopted `std::byte` in some places where it might be relevant, but I also don't think this is important or urgent work. I'll close this.
