### ISSUE TITLE
[BUG] cudaMalloc and cudaFree are being called during aggregations

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#10080]
**Describe the bug**
While examining a recent trace I noticed that within the libcudf `aggregate` range there are calls to `cudaMalloc` and `cudaFree`, the latter which causes a synchronization on the default stream.  I attached gdb and put a breakpoint on `cudaMalloc` and found it was being triggered by `cudf::detail::is_relationally_comparable<cudf::table_device_view>` because it calls `thrust::all_of` without passing an execution policy.  Without using the RMM policy, it will use the default CUDA allocator.  Ideally it should be using `rmm::exec_policy(stream)` but the stream is not available to this method and would need to be passed.

**Steps/Code to reproduce bug**
Attach a debugger to a query using the RMM arena allocator and executes an aggregation.  Place a breakpoint on `cudaMalloc` and execute the query and observe the breakpoint is hit in a callstack that derives from `cudf::detail::is_relationally_comparable`.

**Expected behavior**
libcudf should not trigger calls to `cudaMalloc` or `cudaFree`.

**Comment by harrism** [comment]
Yowza. That function should take an explicit stream.

**Comment by jlowe** [comment]
Still relevant and would like to see this fixed.
