### ISSUE TITLE
[FEA] Support SUM aggregation (groupby and reduction at least) with upcasting the output.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10102]
**Is your feature request related to a problem? Please describe.**
This is a memory optimization.  In Spark if you ask to SUM ints, shorts or bytes the output is a long. In order for us to be able to do this in CUDF we first have to cast the input to a long and then ask CUDF to SUM the result. In the worst case, bytes, we need 9x the original input memory to do the operation. 

**Describe the solution you'd like**
Because group by and reduction aggregations tend to produce fewer output row than they got as input rows. It would really be nice if we could have a SUM aggregation that let us set the output type to be different from the input type.

**Describe alternatives you've considered**
We just keep doing what we do now.

**Additional context**
This is rare, but we are trying to guarantee as much as possible that the working memory needed to process a batch is at most 4x the input batch. This lets users reason about how much data they can process at once. 

SUM is also used in Spark for doing average aggregations, which between these two account for a very large percentage of all of the aggregations done

We also have seen that when doing decimal128 aggregations that sorting the data is one of the longest parts of the process. We have a crazy plan to split the decimal128 into 32-bit chunks and then sum each chunk separately so we can avoid the sorting. If we have to cast each of these 32-bit chunks to a 64-bit value before doing the SUM (so we can deal with overflow/etc) then we would need 3x the input memory. If we can keep them as 32-bit values we can cut that extra memory usage to just 2x, which is close to what we already use to be able to detect overflows in the SUMs.

**Comment by jrhemstad** [comment]
> It would really be nice if we could have a SUM aggregation that let us set the output type to be different from the input type.

For `groupby`, the accumulation and result will always be in the largest possible type. 

[`reduction`](https://github.com/rapidsai/cudf/blob/57ff6f55b9fd44e8a8e10282d3f95d5f38e299ef/cpp/include/cudf/reduction.hpp#L69) already allows specifying the output type.

**Comment by jlowe** [comment]
Thanks, @jrhemstad!  I double-checked how this was happening for a groupby with a sum aggregation, and input INT32 columns into the sum aggregation are indeed returned as INT64 output columns.  However UINT32 columns are also being returned as INT64 rather than UINT64.  Is that intentional?

**Comment by jrhemstad** [comment]
> However UINT32 columns are also being returned as INT64 rather than UINT64. Is that intentional?

Not really. I think the machinery in question was added before unsigned support and then was just never updated. It should be updated to use uint64 for unsigned integer types: https://github.com/rapidsai/cudf/blob/1246116c05abb6635624db25351f6596aa0abf2d/cpp/include/cudf/detail/aggregation/aggregation.hpp#L1140-L1147

**Comment by jlowe** [comment]
Thanks, @jrhemstad! I filed #10149 to track.

**Comment by revans2** [comment]
I am going to close this now because we have #10149 to track the bug and this feature has been implemented.
