### ISSUE TITLE
[BUG] Unexpected error when assigning a value to an empty series

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#10116]
**Describe the bug**
While porting some code from Pandas to cuDF, I have noticed a difference of behaviour between Pandas and cuDF.

When assigning a value to an empty series, Pandas does not produce any error, while cuDF does.

Hope it helps!
Miguel

**Steps/Code to reproduce bug**

> import pandas as pd
> import cudf
> 
> pdf = pd.DataFrame({"a": []})
> gdf = cudf.DataFrame({"a": []})
> 
> pdf.a = 0
> gdf.a = 0

**Expected behavior**
No error raised by cuDF.

**Environment overview (please complete the following information)**
cudf version: 21.12.02
DGX-1 Server

**Comment by shaswat-indian** [comment]
@galipremsagar Can I work on this in case you haven't started yet?

**Comment by galipremsagar** [comment]
> @galipremsagar Can I work on this in case you haven't started yet?

Sure, go ahead and take it up.
