### ISSUE TITLE
[QST] Does rapidsai's cudf helps in loading only DataFrame kind data or any kind of data?

### ISSUE THREAD

**Issue by asispatra** [rapidsai/cudf#1011]
Does rapidsai's cudf helps in loading only DataFrame kind data or any kind of data?

**Comment by kkraus14** [comment]
@asispatra currently the IO capabilities are for loading tabular data into a columnar data structure, but we have plans to separate this out into a separate cuIO library that will have more flexibility. Is there a specific data format or use case you have in mind?

**Comment by asispatra** [comment]
@kkraus14, Alexnet on Tensorflow usages TensorRecords for training and inference. In this kind of scenario I have seen that the data loading and pre-processing takes longer time than the GPU computation. 

Can I use CuDF to optimize the data loading and pre-processing time here?

Thanks.

**Comment by kkraus14** [comment]
We don't currently support TFRecords as an input format, but we'll add it to our list to explore, thanks!

**Comment by asispatra** [comment]
Thanks @kkraus14 for the quick reply.
