### ISSUE TITLE
[BUG] cudf 21.10.01: util.cpp: error: ‘<anonymous>’ may be used uninitialized in this function

### ISSUE THREAD

**Issue by robert-mijakovic** [rapidsai/cudf#10119]
**Describe the bug**
Build fails with the error message:
```
/home/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/src/binaryop/compiled/util.cpp: In function ‘constexpr decltype(auto) cudf::type_dispatcher(cudf::data_type, Functor, Ts&& ...) [with IdTypeMap = cudf::id_to_type_impl; Functor = cudf::detail::double_type_dispatcher_second_type<bool>; Ts = {cudf::binops::compiled::{anonymous}::common_type_functor, cudf::data_type&}]’:
/home/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/src/binaryop/compiled/util.cpp:48:15: error: ‘<anonymous>’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
   48 |       return {};
```

**Steps/Code to reproduce bug**
```
PACKAGE="cudf"
VERSION="21.10.01"

module purge
module load OpenSSL/1.1 CUDA/11.3.1 GCC/10.3.0 CMake/3.20.1-GCCcore-10.3.0 Clang/12.0.1-GCCcore-10.3.0 Python/3.9.5-GCCcore-10.3.0

...

CUDF_HOME=$(pwd)/${PACKAGE}-${VERSION}
cd ${CUDF_HOME}

./build.sh -v --cmake-args=\"-DCUDF_ENABLE_ARROW_S3=OFF -DOPENSSL_CRYPTO_LIBRARY=${EBROOTOPENSSL}/lib64/libcrypto.so -DOPENSSL_SSL_LIBRARY=${EBROOTOPENSSL}/lib64/libssl.so\" libcudf cudf dask_cudf tests
```

**Expected behavior**
That compilation finishes successfully.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: from source

**Comment by gfiameni** [comment]
Hi @robert-mijakovic, apparently this is an issue/bug correlated to GCC-10. Can you try again using GCC-11?

Giuseppe

**Comment by davidwendt** [comment]
There was code change made in this PR #10209 in `branch-22.04` just recently that may help.

**Comment by robert-mijakovic** [comment]
> Hi @robert-mijakovic, apparently this is an issue/bug correlated to GCC-10. Can you try again using GCC-11?
> 
> Giuseppe

Hi @gfiameni, I'm glad to see you here. Should I open another ticket with what GCC-11 reported?

**Comment by gfiameni** [comment]
> > Hi @robert-mijakovic, apparently this is an issue/bug correlated to GCC-10. Can you try again using GCC-11?
> > Giuseppe
> 
> Hi @gfiameni, I'm glad to see you here. Should I open another ticket with what GCC-11 reported?

Hi @robert-mijakovic, you can report the output using this issue. Have you checked this PR [#10209](https://github.com/rapidsai/cudf/pull/10209) too?

**Comment by robert-mijakovic** [comment]
I get:
```
error: namespace "std" has no member "optional"
```

I check and the standard used is gnu++17 standard.

I tried to override the standard and enforce the c++17 standard using:
1. CMAKE_CXX_STANDARD
2. CMAKE_CXX_FLAGS

None of the two worked as it wasn't enforced on all files but only some.

**Comment by robert-mijakovic** [comment]
> > > Hi @robert-mijakovic, apparently this is an issue/bug correlated to GCC-10. Can you try again using GCC-11?
> > > Giuseppe
> > 
> > 
> > Hi @gfiameni, I'm glad to see you here. Should I open another ticket with what GCC-11 reported?
> 
> Hi @robert-mijakovic, you can report the output using this issue. Have you checked this PR [#10209](https://github.com/rapidsai/cudf/pull/10209) too?

I will try the proposed change too with GCC10.
```
return std::nullopt;
```

**Comment by robert-mijakovic** [comment]
> > > > Hi @robert-mijakovic, apparently this is an issue/bug correlated to GCC-10. Can you try again using GCC-11?
> > > > Giuseppe
> > > 
> > > 
> > > Hi @gfiameni, I'm glad to see you here. Should I open another ticket with what GCC-11 reported?
> > 
> > 
> > Hi @robert-mijakovic, you can report the output using this issue. Have you checked this PR [#10209](https://github.com/rapidsai/cudf/pull/10209) too?
> 
> I will try the proposed change too with GCC10.
> 
> ```
> return std::nullopt;
> ```

It failed with:
```
/apps/USE/easybuild/release/2021.3/software/CUDA/11.3.1/bin/nvcc -forward-unknown-to-host-compiler -DCUDF_VERSION=21.10.01 -DJITIFY_PRINT_LOG=0 -DJITIFY_USE_CACHE -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -Dcudf_EXPORTS -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/dlpack-src/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/jitify-src -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/libcudacxx-src/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/src -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/arrow-src/cpp/src -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/arrow-src/cpp/src/generated -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/arrow-src/cpp/thirdparty/hadoop/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/arrow-src/cpp/thirdparty/flatbuffers/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/thrust-src -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/thrust-src/dependencies/cub -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/rmm-src/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/spdlog-src/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/cuco-src/include -I/mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/build/_deps/nvcomp-src/src/../include -isystem=/apps/USE/easybuild/release/2021.3/software/CUDA/11.3.1/include -O3 -DNDEBUG --generate-code=arch=compute_80,code=[sm_80] -Xcompiler=-fPIC --expt-extended-lambda --expt-relaxed-constexpr -Werror=cross-execution-space-call -Xcompiler=-Wall,-Werror,-Wno-error=deprecated-declarations -Xcompiler=-Wno-deprecated-declarations -Xfatbin=-compress-all -Xcompiler -pthread -std=c++17 -MD -MT CMakeFiles/cudf.dir/src/binaryop/compiled/binary_ops.cu.o -MF CMakeFiles/cudf.dir/src/binaryop/compiled/binary_ops.cu.o.d -x cu -c /mnt/tier2/users/apps/scratchpad/cudf/cudf-21.10.01/cpp/src/binaryop/compiled/binary_ops.cu -o CMakeFiles/cudf.dir/src/binaryop/compiled/binary_ops.cu.o
/mnt/tier2/apps/USE/easybuild/release/2021.3/software/GCCcore/10.3.0/include/c++/10.3.0/bits/stl_pair.h:230:2: error: ‘unnamed’ was not declared in this scope
  230 |                                    ::value, bool>::type = true>
      |  ^
```

**Comment by robert-mijakovic** [comment]
I also hit `error: ‘unnamed’ was not declared in this scope` with the release 21.08 of cudf.

**Comment by GregoryKimball** [comment]
Thank you @robert-mijakovic for sharing your findings. Please open an issue if you experience problems with our latest release.
