### ISSUE TITLE
[BUG] Type annotation for `Frame._columns` Mismatches with Actual Return Type

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#10130]
**Describe the bug**
The type annotation of `frame._columns` is `List[Any]`:
https://github.com/rapidsai/cudf/blob/22daaea61e60cc7c1d557e0ce47c65d49a82af53/python/cudf/cudf/core/frame.py#L107

The actual return type is a tuple:
https://github.com/rapidsai/cudf/blob/22daaea61e60cc7c1d557e0ce47c65d49a82af53/python/cudf/cudf/core/column_accessor.py#L213

**Steps/Code to reproduce bug**
N/A

**Expected behavior**
Type annotations should match. Better, figure out why mypy didn't catch this automatically.

**Comment by GregoryKimball** [comment]
Closed by [Replace custom `cached_property` implementation with functools (#10272)](https://github.com/rapidsai/cudf/commit/374b38745932616dbeca2e84e1e86d63c228a179)
