### ISSUE TITLE
[FEA] Add an optional max_file_size parameter to Chunked Parquet Writer

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#10144]
The chunked Parquet writer now supports partitioning. 

In ETL/Streaming, we can now append the partitioned Parquet output of every batch to a single file per partition inside the parquet directory instead of creating a separate small parquet file per partition per batch. 

However, with use cases like streaming, the appended parquet files can become arbitrarily large, which can become a problem in downstream processing.

Data Lake engines like Delta (features: Auto Optimize, Auto Compact) provide an option to specify a `max_file_size` parameter which means that after a certain size, the chunked writer will basically create another parquet file and append to it. This helps in efficient downstream processing and great to have in cuDF, too.

**Comment by chinmaychandak** [comment]
Hey @devavret, did we get a chance to scope the effort for this?

**Comment by devavret** [comment]
> Hey @devavret, did we get a chance to scope the effort for this?

Not yet. Is this critical for extracting performance gains from the previous partitioning work?

**Comment by chinmaychandak** [comment]
For streaming jobs, we need to cap the size of the files being generated so that we do not create really large arbitrary files which might impact downstream processing (which does not use GPUs as of now).

**Comment by devavret** [comment]
We just prioritized this and @galipremsagar is actively working on this.
