### ISSUE TITLE
libcudf deprecation policy

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#10159]
As discussed in https://github.com/rapidsai/cudf/pull/10152#issuecomment-1023862782, it would be good to introduce a formal deprecation policy to libcudf. Depending on what types of stability guarantees we provide, such a policy could cover:
- Whether code deprecation before removal is required or only done for critical APIs.
- How long before deprecated code should be removed.
- How we advertise deprecations to users (using the `[[deprecated]]` attribute, doxygen notices, etc).

**Comment by harrism** [comment]
I think deprecation should only be required for removals that cause API or ABI breaks, or that change behavior.

**Comment by vyasr** [comment]
I agree, definitely only for user-facing changes. At present, though, such changes often happen without any deprecation cycle at all. Do you think we should change that and always have some sort of deprecation cycle? Are we mature enough to stop allowing breaking change without warning? For reference, cuDF Python generally follows a deprecation cycle of one release (although sometimes it gets longer).

**Comment by harrism** [comment]
I do think a deprecation cycle is a good policy. We have used in RMM [[deprecated]] in the past. I think a single release cycle as a minimum is good.

**Comment by vyasr** [comment]
Doxygen also [supports deprecations in the documentation](https://www.doxygen.nl/manual/commands.html#cmddeprecated), should we make use of that as well?

**Comment by harrism** [comment]
Makes sense to me.

**Comment by karthikeyann** [comment]
`[[deprecated]]` attribute by doxygen, is in development https://github.com/doxygen/doxygen/pull/9064
