### ISSUE TITLE
[FEA] Use List of Columns instead of Frames in Cython API

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#10153]
Following the removal of `Table` class https://github.com/rapidsai/cudf/pull/9315, and a pilot study of changing several cython APIs into using list of columns https://github.com/rapidsai/cudf/pull/9558, we want to extend the previous effort and use lists of columns to replace usage of `Frame` with list of columns. The main arguments for this change are:
1. Libcudf's `table_view` is essentially a thin wrapper of `vector<column_view>`, this match with list of column concept.
2. In the vision by data consortium API, dataframes does not have a column name.
3. From developer's perspective, we want to rely on simpler data structure on cython layer for easy debugging.

This is a meta issue that tracks the list of candidate APIs that awaits to be changed and the refactor progress.

The following list is compiled by searching `\(\n?.*table_view.*(\n|\))` in the cpp code base and find their corresponding wrapper in cython. 

- [x] Copying.pyx:
    - [x] `Scatter`: should we expand the cython interface to support multi column scatter?
    - [x] `table_empty_like`
    - [x] `table_slice`
    - [x] `table_split`
    - [x] `boolean_mask_scatter_table`: see #8667.
    - [x] `sample`
- [x] filling.pyx:
    - [x] `repeat`
- [x] groupby.pyx:
    - [x] `groupby.__cinit__`
    - [x] `groupby.groups`
    - [x] `groupby.shift`
    - [x] `groupby.replace_nulls`
- [x] hash.pyx:
    - [x] `hash`
- [x] interop.pyx:
    - [x] `to_dlpack`
- [x] join.pyx:
    - [x] `join/semi_join`: lhs, rhs
- [x] merge.pyx:
    - [x] `merge_sorted`
- [x] partitioning.pyx:
    - [x] `partition`
- [x] quantile.pyx:
    - [x] `quantiles`
- [x] reshape.pyx:
    - [x] `interleave_columns`
    - [x] `tile`
- [x] search.pyx:
    - [x] `search_sorted`
- [x] sort.pyx:
    - [x] `is_sorted`
    - [x] `order_by`
    - [x] `digitize`
    - [x] `rank_columns`
- [x] transform.pyx:
    - [x] `table_encode`
- [x] transpose.pyx:
    - [x] `transpose`
- [ ] csv.pyx:
    - [ ] `write_csv`: note index argument
- [ ] orc.pyx:
    - [ ] `write_orc`
- [ ] parquet.pyx:
    - [ ] `write_parquet`
- [x] lists.pyx:
    - [x] `explode_outer`
    - [x] `concatenate_rows`
- [x] string/combine.pyx:
    - [x] `concatenate`

Second step from this is to remove `utils.table_view_from_table` completely.

**Comment by GregoryKimball** [comment]
@isVoid Should we close this, make a new issue for the IO files, and label it "good first issue"?

**Comment by isVoid** [comment]
I would still like to keep tracking in this issue. Especially the I/O files refactors are the hardest among the cohorts. I don't think moving it to a separate issue will help lowering the barrier.

**Comment by vyasr** [comment]
I'm going to close this issue. With pylibcudf coming we are going to have to rethink the internals of cudf further. Ultimately the list of columns approach we took here is certainly going to be closer to the final end state, but it is no longer directly applicable.
