### ISSUE TITLE
[DEPRECATION] Remove Series.merge

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#10166]
pandas only support merge operations on Series via the `pd.merge` or `DataFrame.merge` APIs.

**Comment by bdice** [comment]
Cross-referencing: #9316

**Comment by vyasr** [comment]
Thanks. Related, https://github.com/rapidsai/cudf/issues/9316#issuecomment-969341695 needs to be addressed before we remove this API.

**Comment by vyasr** [comment]
Resolved in #10450
