### ISSUE TITLE
[FEA] Standardize applymap support with pandas to enable Dask applymap

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#10169]
Today, we support the `applymap` interface on Series but not DataFrames. Pandas supports `applymap` on DataFrames but not Series. In pandas, the interface provides applies a scalar function/UDF to every element in the dataframe (elementwise UDF).

The reason for our Series.applymap implementation may be that, until recently, we did not support an elementwise `apply` interface directly. Now that we do, it's possible `Series.applymap` is redundant, as both interfaces explicitly provide users access to elementwise UDFs run via our udf pipeline. (Please feel free to correct me if I'm off base here).

For compatibility with Dask, we should explore aligning our interfaces with pandas. Right now, it's not possible to use `applymap` with Dask-cuDF, as the Dask.Series object does not have our Series interface and we don't implement the DataFrame interface.

We might consider:
- Deprecating (and eventually removing) Series.applymap
- Implementing DataFrame.applymap with our existing udf pipeline machinery (independently and sequentially processing each column)
- Adding unit tests for dask_cudf Dataframes
- Update the [Guide to UDFs](https://docs.rapids.ai/api/cudf/nightly/user_guide/guide-to-udfs.html) as appropriate

```python
import dask_cudf
import cudf
import pandas as pd
import dask.dataframe as dd

df = pd.DataFrame({"a":[0,1,2,3,4]})
gdf = cudf.from_pandas(df)

def func(x):
    return x + 10

# Dask CPU
ddf = dd.from_pandas(df, 2)
ddf.applymap(func).compute() # succeeds
# ddf.a.applymap(func).compute() # doesn't exist

# Dask GPU
ddf = dask_cudf.from_cudf(gdf, 2)
# ddf.applymap(func).compute() # fails
# ddf.a.applymap(func).compute() # fails
```

**Comment by brandon-b-miller** [comment]
I can look into this, @beckernick .

**Comment by brandon-b-miller** [comment]
This is in progress, applymap is deprecated and we're moving to supercede it with `apply`. In addition we now have `DataFrame.applymap` instead that truly mirrors pandas. This will be closed when `Series.applymap` is removed.

**Comment by brandon-b-miller** [comment]
with https://github.com/rapidsai/cudf/pull/11031 merged I think this is done :)
