### ISSUE TITLE
[BUG] Patch release process leaves branches not versioned properly

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#10162]
**Describe the bug**
When doing patch releases, there's a commit from @GPUtester against the `main` branch that bumps the version number in a few files. For example, https://github.com/rapidsai/cudf/commit/06540b9b3795931dccf0ba73b592af62c690086c.

If you look at the associated branch that also has the patches applied, it did not receive the version bump: https://github.com/rapidsai/cudf/blob/branch-21.12/cpp/doxygen/Doxyfile

Should the patch release process apply the release commit to the versioned branch and then merge that branch into `main`?

cc @raydouglass

**Comment by vyasr** [comment]
I'm going to close this since it's a process question for all of RAPIDS. I'll reopen in a more centralized location.
