### ISSUE TITLE
Error with "Expected 48 from C header, got 40 from PyObject"

### ISSUE THREAD

**Issue by hchen98** [rapidsai/cudf#10187]
When I try the Rapid GPU online colab demo, I have encountered the following issue:

![image](https://user-images.githubusercontent.com/12217705/152085085-e7184eed-77ae-42cf-be22-1dd531bf1a0f.png)

The error log:

```
/usr/local/lib/python3.7/site-packages/cudf/utils/gpu_utils.py:93: UserWarning: You will need a GPU with NVIDIA Pascal™ or newer architecture
Detected GPU 0: Tesla K80 
Detected Compute Capability: 3.7
  f"You will need a GPU with NVIDIA Pascal™ or "
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-a95ca25217db> in <module>()
----> 1 import cudf
      2 import io, requests
      3 
      4 # download CSV file from GitHub
      5 url="https://github.com/plotly/datasets/raw/master/tips.csv"

2 frames
/usr/local/lib/python3.7/site-packages/cudf/__init__.py in <module>()
     10 
     11 from cudf.api.types import dtype
---> 12 from cudf import api, core, datasets, testing
     13 from cudf._version import get_versions
     14 from cudf.api.extensions import (

/usr/local/lib/python3.7/site-packages/cudf/datasets.py in <module>()
      3 
      4 import cudf
----> 5 from cudf._lib.transform import bools_to_mask
      6 from cudf.core.column_accessor import ColumnAccessor
      7 

/usr/local/lib/python3.7/site-packages/cudf/_lib/__init__.py in <module>()
      2 import numpy as np
      3 
----> 4 from . import (
      5     avro,
      6     binaryop,

cudf/_lib/avro.pyx in init cudf._lib.avro()

cudf/_lib/column.pyx in init cudf._lib.column()

cudf/_lib/scalar.pyx in init cudf._lib.scalar()

cudf/_lib/interop.pyx in init cudf._lib.interop()

ValueError: pyarrow.lib.Codec size changed, may indicate binary incompatibility. Expected 48 from C header, got 40 from PyObject
```

Has anyone had the same issue? I even reinstall the different version of Numpy but still doesn't work.

**Comment by lixy3** [comment]
I've got the same error today on the PRO version of Google Colab. I've been using RAPIDS for a few months with no issues until now and always used the script from [https://rapids.ai/start.html](url) to install RAPIDS in Colab. @shwina I attached screenshots with the output you mentioned.

<img width="719" alt="Screenshot 2022-02-02 at 15 11 01" src="https://user-images.githubusercontent.com/45132236/152181504-eca2d836-ef1c-4ea0-9616-c3af7d07ce3c.png">
<img width="860" alt="Screenshot 2022-02-02 at 15 10 35" src="https://user-images.githubusercontent.com/45132236/152181638-53f59664-b598-4364-ab72-c5a5bbd0c62a.png">

**Comment by hchen98** [comment]
@shwina  here you go:

![image](https://user-images.githubusercontent.com/12217705/152206827-02f8ddc5-1ec6-4c60-92e5-2c641c38cb41.png)

**Comment by shwina** [comment]
Thanks!

The `dist-packages` in the path indicates that pyarrow was installed using the system package manager (eg., `apt`), and  that version is being preferred over the one installed by `conda`.

We're investigating what exactly is going wrong on Colab and will report back here with a solution.

**Comment by craigcitro** [comment]
Hi @shwina, colab-team member here; we got a similar report that I've duped into this issue. LMK if there are questions I can answer from our side.

There was one possibly-relevant change on our side: we just updated pandas from 1.1.5 to 1.3.5; IIUC you're installing your own copy of pandas from conda, but I thought I'd mention it in case it was helpful.

**Comment by praguna** [comment]
@shwina  any workaround for this ?

**Comment by prateek2512** [comment]
Hi i am also facing this issue in colab pro. i was using cudf in colab 3 days before normally. but from last 2 days above error is coming when importing cudf

**Comment by shwina** [comment]
Thanks @craigcitro, that is helpful! I believe the issue is on our end though. Ideally we should run in a totally separate environment from the built-in one on Colab, but we use `/usr/local` as our conda prefix which is messing things up. We are working to fix this and I'll report here with a solution or workaround as soon as I find one.

Apologies for the inconvenience.

**Comment by shwina** [comment]
Hi @craigcitro - upon some reflection, I realize that the reason we are installing conda packages into `/usr/local` is because that's where the `base` conda environment is installed when using `condacolab`: https://github.com/conda-incubator/condacolab#how-does-it-work

This sounds like it would result in conflicts with Python packages installed via the system package manager. For example, if you install Pandas via `conda`, you end up being two installs of Pandas, one in `/usr/local/lib/python3.7/dist-packages/pandas`, and one in `/usr/local/lib/python3.7/site-packages/pandas`. The latter is the one the user installed, but it never gets picked up, because the former is preferred.

Do you have any ideas on how this might be overcome? One suggestion I would have is that Colab could install its default Python packages via `pip`, rather than the system package manager `apt`, which would place them in `site-packages` instead. Then, if the user wants to install a newer or different version of any of those packages via `pip` or `conda`, that would work as expected.

**Comment by shwina** [comment]
To convince myself that this is the issue, I deleted `pandas` and `pyarrow` from the module cache before importing `cudf` and that seems to work:

```python
import sys

# clear Pandas and PyArrow from the module cache
# and force them to be reloaded on import.
# WARNING: I don't know what else this might break.

mods = [mod for mod in sys.modules if mod.startswith(("pandas", "pyarrow"))]
for mod in mods:
  del sys.modules[mod]
```

**Comment by hchen98** [comment]
Hey @shwina, I tried the solution you mentioned; however, I encountered the same issue as what @Halegua has faced.

**Comment by craigcitro** [comment]
@shwina following up with a few questions all at once:

1. We do all python installs via `pip`. However, we get our `python` installs from ubuntu via `apt`, which I suspect is the reason `dist-packages` gets preferred. We don't have any plans to start building our own python from source.
2. Yes, we import `pandas` at startup: it happens to be a dep of `google.colab`. Based on feedback, the majority of users end up doing an `import pandas` anyway, so having this happen before they connect saves them 1-2s on first import, too.
3. Any time a user installs a new version of a package already in `sys.modules`, confusion is likely to ensue. For `pip install`s in colab, we [try to detect](https://github.com/googlecolab/colabtools/blob/main/google/colab/_pip.py) this situation and warn the user to restart the runtime (with a button in the output).

I would say a good first fix would be to add a note to the rapidsai notebooks that recommends restarting the runtime (ctrl-m . or `Runtime` -> `Restart runtime`) after all the package installs are finished. 

A more complete fix might be to have the condacolab tell the user to restart their kernel; I see https://github.com/conda-incubator/condacolab/blob/c5e863ada01e5e2ac6971ffb958ea0116664bb79/condacolab.py#L145-L146, which should be doing the right thing here; IMO it's worth digging a little there to figure out why that isn't sufficient.

In addition, I'm updating the version of pyarrow in Colab, which will hopefully fix this issue; that should finish rolling out by tomorrow.

**Comment by hchen98** [comment]
Hey @craigcitro, I tried to restart (Factory reset runtime as well) the runtime after all necessary packages are installed. However, it did not work. I will try restarting the kernel.

For updating the version of pyarrow in Colab, I tried via `!conda install -c conda-forge pyarrow` on version 6.0.1, it causes inconsistent versioning with other packages.

**Comment by shwina** [comment]
Thanks, @craigcitro  -- that does help clear some things up for me.

> We do all python installs via pip. However, we get our python installs from ubuntu via apt, which I suspect is the reason dist-packages gets preferred. We don't have any plans to start building our own python from source.

That's fair. I'm still not sure what the root issue is but suspect it's some combination of:

- system,`pip`, and `conda` packages installed into the same environment
- pre-importing Pandas

Upgrading PyArrow in Colab will hopefully resolve this for now.

Thanks again!

**Comment by craigcitro** [comment]
`pyarrow` should be updated in Colab now, so hopefully this should be fixed.

**Comment by hchen98** [comment]
Hi @craigcitro, I just rerun the latest online demo on Colab, `pyarrow` still in version `5.0.0` (see detail below).

![image](https://user-images.githubusercontent.com/12217705/152626446-55dea4d2-478a-4857-ab29-c41c80352547.png)

Also, this time it gives a different error when importing the `cudf`. The error log is as follows:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-4-a95ca25217db>](https://localhost:8080/#) in <module>()
----> 1 import cudf
      2 import io, requests
      3 
      4 # download CSV file from GitHub
      5 url="https://github.com/plotly/datasets/raw/master/tips.csv"

2 frames
[/usr/local/lib/python3.7/site-packages/cudf/__init__.py](https://localhost:8080/#) in <module>()
     10 
     11 from cudf.api.types import dtype
---> 12 from cudf import api, core, datasets, testing
     13 from cudf._version import get_versions
     14 from cudf.api.extensions import (

[/usr/local/lib/python3.7/site-packages/cudf/datasets.py](https://localhost:8080/#) in <module>()
      3 
      4 import cudf
----> 5 from cudf._lib.transform import bools_to_mask
      6 from cudf.core.column_accessor import ColumnAccessor
      7 

[/usr/local/lib/python3.7/site-packages/cudf/_lib/__init__.py](https://localhost:8080/#) in <module>()
      2 import numpy as np
      3 
----> 4 from . import (
      5     avro,
      6     binaryop,

cudf/_lib/gpuarrow.pyx in init cudf._lib.gpuarrow()

ModuleNotFoundError: No module named 'pyarrow._cuda'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by Halegua** [comment]
@shwina @craigcitro @hchen98 Also receiving `ModuleNotFoundError: No module named 'pyarrow._cuda'` now. Any idea on how to fix it? I read some suggestions about downgrading pyarrow in this specific problem, but i guess that would be counter-productive since we probably would go back to the original problem.

**Comment by hchen98** [comment]
Hi @shwina, thanks for that! It works on my end!

I will close this issue :)

**Comment by shwina** [comment]
@craigcitro for whatever reason, even restarting the runtime doesn't change the location of Pandas/PyArrow already present in the module cache (`dist-packages`). Could you please point me to where the pre-importing of Pandas (and other libs?) is done within Colab ? Just curious to understand the root cause of the issue.

**Comment by sivaramakrishnareddyc** [comment]
I have this issue in my local environment too i.e on my workstation with RTX 5000 GPU and ubuntu 20.04, The error i am getting is ModuleNotFoundError: No module named 'pyarrow._cuda'
