### ISSUE TITLE
[FEA] group by aggregations that include a list of strings as the grouping type

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10181]
**Is your feature request related to a problem? Please describe.**
We have a customer that would like to perform group by aggregations in Spark on a column that contains a list of strings.

https://github.com/NVIDIA/spark-rapids/issues/4656

**Describe the solution you'd like**
To be specific we want to be able to create a [`cudf::group_by` ](https://github.com/rapidsai/cudf/blob/2c6b0dac61a6671642bb5b076e910e20e2bdd1b6/cpp/include/cudf/groupby.hpp#L125) where one of the columns in `keys` is a column of type `LIST` that holds a child data column of type `STRING`.

The only operation we need to perform on it is [`aggregate`](https://github.com/rapidsai/cudf/blob/2c6b0dac61a6671642bb5b076e910e20e2bdd1b6/cpp/include/cudf/groupby.hpp#L184).

For the grouping Spark defines equality recursively for its types. So `STRING` equality is the same as it is for `binary_op::NULL_EQUALS` or when doing a group by on another `STRING` column.  A `LIST` is equal to another `LIST` if and only if both are `NULL` or both have the same number of elements and all of the elements compare as equal to each other.

We would also **like** to be able to sort a table where one of the sort keys is the same data type, a `LIST` of `STRING`s. I have filed  #10184 for this as it is used in cases when the intermediate aggregation results have grown too large.

**Describe alternatives you've considered**
We could try to play games with deliminators and rewrite the list of strings into just a column of longer strings, but then we have issues with nulls, and all kinds of other things. It really gets to be hard to do.

**Comment by jrhemstad** [comment]
> We would also **like** to be able to sort a table where one of the sort keys is the same data type, a `LIST` of `STRING`s. This is not a hard requirement because we fall back to sorting the data if the intermediate results are so large that we cannot fit them all in GPU memory at once. If you want me to split this off into a separate request I am happy to do it.

Please do. Non-equality comparison is a different beast.

**Comment by devavret** [comment]
For groupby aggregate, we need a list hash and a list equality, neither of which is supported right now. But I think it's easier to do both of these rather than implement a list lexicographical comparator, which would be needed for sort based groupby. 

With the former, we can do a hash groupby where the output order of grouped keys is non deterministic. And you can't even sort **after** the groupby aggregate. It'll just have to be in arbitrary order.

I'm working on list equality right now and will probably use a similar technique to do a hash.

**Comment by revans2** [comment]
I filed #10184 for sorting lists of strings.  I will delete it from the description here.

**Comment by devavret** [comment]
Just realized, this looks like a special case of #8039.

**Comment by revans2** [comment]
Yes this very much is a special case of #8039. If you want to duplicate them, I am fine with it. I just wanted to be sure that the Spark requirements were properly captured.

**Comment by revans2** [comment]
This is still wanted @devavret should I close this as a dupe of #8039?
