### ISSUE TITLE
[FEA] Story - Supporting row operators on nested types

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#10186]
There have been several requests to enable row operators on nested types. This issue is to track all related issues as a story.

There are three types of row operators we need to support (equality comparison `==`, lexicographic comparison `<`, and hashing `#`) on two different nested types (`LIST` and `STRUCT`).

|Status|Issue|Type|Operation|Notes|
|-|-|-|-|-|
|✔️|#8683|STRUCT|`==`|Solved by flattening|
|In Progress|#8964|STRUCT|`==`, `<`|Proposed solution by flattening #9452|
|Partially complete, see issue|#8039|LIST|(`==` + `#`) / (`==` + `<`)|Requires `==` + `#` for hash groupby or `==` + `<` for sort groupby. Also a Spark req #10181|
||#8974|STRUCT|`<`|Individual action items being solved with flattening|
||#5890|LIST|`<`|Plain list sorting. Spark req #10184|
|will be closed by #11129|#6784|LIST|(`==` + `#`) / (`==` + `<`)|`drop_duplicates` uses (`==` + `<`) right now but will be optimized to use (`==` + `#`) in #10030|
||#9119|STRUCT|`#`|Needs a `struct_device_view`|
|✔️|#10378|LIST|`#`|We have list hashing, but need Spark-compatible Murmur3|
||#10408|LIST of STRUCT|`<`|Different from groupby on list because here the `list<struct>` column is values, not keys|

#### The plan
This will be supported using multiple PRs, first covering 1-table row comparators and hashing for nested types, then extending the row comparators with 2-table versions:

|Status|PR|Column Type|Operation|Number of tables|Dependencies|Notes|
|-|-|-|-|-|-|-|
||#10164|Struct|`<`|1||Refactor of existing functionality. Introduces new owning operator API|
||#10289|List + struct (arbitrary nesting)|`==`|1|#10164, #10291|Works only for "sanitized list" and structs with nulls pushed down|
||#10641|List + struct (arbitrary nesting)|`#`|1|#10289|Same requirements as #10289|
||#10883|List + struct (arbitrary nesting)|`==`|2|#10289, |Same requirements as #10289, also see #10508|
||#10730|Struct|`<`|2|#10164|#10508|
||#11129|List|`<`|1|#10164, #10291|Should work for struct of list but won't work for list of structs|
|||List of struct|`<`|1||Proposal in #11222|
||#11292|List of struct|Spark-`#`|1| ||

And then using the row comparators and hashing for nested types to implement algorithms.
|Status|PR|Algorithm|Requires|Notes|
|-|-|-|-|-|
|✔|#11129|Sort|`<`, 1 table|Requested by #5890, #10184|
||#10289|rank|`==`| rank assumes pre-sorted|
|✔|#10641|distinct| `==` + `#`, 1 table | Requested by #6784, e.g. `1,1,1,2,2,1,1 -> 1,2`|
|||distinct_count | `==` + `#`, 1 table | Requested by #6784, e.g. `1,1,1,2,2,1,1 -> 2`|
|||approx_distinct_count|`==` + `#`||
|||unique|`==`, 1 table | e.g. `1,1,1,2,2,1,1 -> 1,2,1` |
|||unique_count |`==`, 1 table | e.g. `1,1,1,2,2,1,1 -> 3` |
||#10770|Hash-based Groupby|`==` + `#`, 1 table|Requested by #8039, #10181|
|||Sort-based Groupby|`<`, 1 table|Requested by #8039, #10181|
|||scan (min/max)|`<`, 1 table|#10408|
|||search, replace|`==`, sort, 1 table, 2 table||
||#10656 tbd|contains|`==`, sort, 1 table||
|||equality join|`==` + `#`, 2 table||
|||quantiles|sort, 1 table||

**Comment by devavret** [comment]
> We would need to figure out how to pass column_device_view information as part of the object.

This may be achieved by specializing [`element_hasher`](https://github.com/rapidsai/cudf/blob/e4a16ae2550f5a7481887b28c7a60fc14fea2f5c/cpp/include/cudf/table/row_operators.cuh#L433-L440) for `list_view` and passing `list_device_view` to hash_function. Then instead of defining [`MurmurHash3_32<cudf::list_view>`](https://github.com/rapidsai/cudf/blob/276bcf4171c82101a12b3d2392802e4746d0d2e3/cpp/include/cudf/detail/utilities/hash_functions.cuh#L289) we can define `MurmurHash3_32<cudf::list_device_view>`

**Comment by sameerz** [comment]
Still needed

**Comment by GregoryKimball** [comment]
This story issue has served us well! I'm closing it in favor of #11844 where we will continue this work.
