### ISSUE TITLE
[FEA] Parquet reader optimization.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#10215]
Putting this up with a reference to:  https://github.com/NVIDIA/spark-rapids/issues/4687

Essentially, optimization work to the parquet reader to deal with a specific case:  files with large amount of rows encoded via dictionary as opposed to flat data.  Specifically addressing the data found in TPC-DS Q9.

The NVComp team put together a simple parquet reader for fixed-width types stored as flat data which is considerably faster than the cuIO reader.  It does not support many types or encodings though so the ongoing experiment is to add what's necessary to get the data from Q9 loading.

(Very) early results so far seem good:  seeing a ~25% speedup using this experimental reader and I suspect there is some room there to do better.  Note: this is just for the dictionary case.  The non-dictionary case runs 2-3x faster than cuIO even when in a low-number-of-pages case (kernel is parallelized by page).  It likely will do even better for very large files.

Once we generate enough results we can get together with the cuIO team and if/how it makes sense to integrate it  (the code right now is a completely separate one-off).

**Comment by nvdbaranec** [comment]
Still relevant.

**Comment by GregoryKimball** [comment]
To future engineers interested in this topic, there is an experimental branch available at https://github.com/nvdbaranec/cudf/tree/parquet_nvcomp_experiment
