### ISSUE TITLE
[BUG]  How to delete cuDF from GPU Memory

### ISSUE THREAD

**Issue by hakantekbas** [rapidsai/cudf#10228]
Hi;

I read a file from csv.

```
import cudf
data = cudf.read_csv("/data_ssd/userH/testFolder/tr/location/20220115/sample_4.csv.gz",has_header=False)
data.columns = ["n_{}".format(n) for n, name in enumerate(data.columns)]
```

This code allocated 2 gb memory in gpu.
![image](https://user-images.githubusercontent.com/19631334/152638900-c0ecabc6-e247-40a7-807d-d51a5e8f74e2.png)

Then I delete variable data.

`del data`

Usage does not change. I tested in 21.6 and 22.04. Same behaviour exist in both version. I saw a similar topic opened 1 year ago. Problem solved. 1 year ago. Is there any other way to delete variable from memory.

Thanks.

**Comment by hakantekbas** [comment]
I want to give more detail. If I set a breakpoint between creation and deletion of data, memory is growing and finally running out of memory. but if there is no breakpoint between creation and deletion of data, memory is remaining constant.

I'm connecting gpu server remotely with visual code.

Is this type of behaviour normal?

```
import cudf
import time

for i in range(10):
    data = cudf.read_csv("/data_ssd/hakan/start_io/tr/location/20220115/sample_4.csv.gz",has_header=False)
    data.columns = ["n_{}".format(n) for n, name in enumerate(data.columns)]
    data["n_0"].nunique()
    time.sleep(8)
    del data
    print(i)
```

**Comment by hakantekbas** [comment]
If code does not have any breakpoint  but it includes print statement, memory still grows.

```
import cudf
import time

for i in range(10):
    data = cudf.read_csv("/data_ssd/hakan/folder/tr/location/20220115/sample_4.csv.gz",has_header=False)
    data.columns = ["n_{}".format(n) for n, name in enumerate(data.columns)]
    data["n_0"].nunique()
    print(data.head(3))
    time.sleep(8)
    del data
    print(i)
```

I hope you can replicate same behaviour in your run. If not, let me know.

**Comment by casonk** [comment]
running gc.collect() solved the issue for me as well.
