### ISSUE TITLE
[QST] rmm feedstock

### ISSUE THREAD

**Issue by alhad-deshpande** [rapidsai/cudf#10243]
**What is your question?**
The conda yaml file (https://github.com/rapidsai/cudf/blob/v21.12.00/conda/environments/cudf_dev_cuda11.5.yml) has requirement of "rmm=21.12.*". When I am trying to create the cudf_dev conda enviroment on ppc64le arch, getting error that rmm package is not available. I tried searching rmm feedstock for the same but could only found feedstock for librmm (https://github.com/conda-forge/librmm-feedstock) which does not have rmm python package. Can you please let me know exactly to which feedstock rmm points to?

**Comment by beckernick** [comment]
Hi @alhad-deshpande . We provide conda packages in the rapidsai (stable) and rapidsai-nightly (nightly) channels (not conda-forge), but the packages do not support all systems.

From your question, it sounds like you're using a POWER system. We aren't set up create packages for POWER, but you may be able to build cuDF from source for such a system.

**Comment by beckernick** [comment]
I'm going to close this issue as answered, but please feel free to reopen.
