### ISSUE TITLE
[BUG] read_csv fails when not all columns specified in the `dtype` argument

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#10254]
```python
import cudf
import pandas as pd

# generate a CSV:
df = cudf.DataFrame(
    {
        "a": [1, 2, 3],
        "b": ["x", "y", "z"],
        "c": cudf.Series([1, 2, 3], dtype="datetime64[ns]"),
    }
)
df.to_csv("test.csv", index=False)

# this works:
pd.read_csv("test.csv", dtype={"a": "int"})

# this doesn't:
cudf.read_csv("test.csv", dtype={"a": "int"})
```

```python
...
RuntimeError: cuDF failure at: /home/ashwin/workspace/rapids/cudf/cpp/src/io/csv/reader_impl.cu:493: Must specify data types for all active columns
```

**Comment by galipremsagar** [comment]
This appears to be a validation check happening at `libcudf` layer. @vuule is it feasible to remove this check and auto-detect types like libcudf usually does for other columns not specified in `dtypes`?

**Comment by vuule** [comment]
> This appears to be a validation check happening at `libcudf` layer. @vuule is it feasible to remove this check and auto-detect types like libcudf usually does for other columns not specified in `dtypes`?

I think that's a feasible option. 
@shwina Is this a blocker for 22.04?

**Comment by vuule** [comment]
libcudf API also has an option to pass an array of types. Allowing this array to pass a subset of all required types seems ripe for user errors. @shwina is it sufficient to allow partial dtypes only when a dictionary is passed?
