### ISSUE TITLE
[FEA] Support string split with empty delimiter

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#10251]
Currently, when the input delimiter is an empty string, `strings::split` and `strings::split_record` perform splitting of strings on whitespaces. This produces inconsistent behavior with Java, which should produce an array of individual characters from the input string.

Although the default behavior of string split in Python Pandas is to split by whitespaces, that default behavior is only achieved when there is no delimiter specified. If we specified an empty delimiter, it will throw an exception instead.

Therefore, we can support splitting string with empty delimiter (i.e., the input string will be split into an array of characters) while still supporting splitting on whitespaces. Splitting by whitespace will be achieved by explicitly specifying the delimiter as an invalid string scalar delimiter.

**Comment by ttnghia** [comment]
Tag @davidwendt for relevant work.

**Comment by revans2** [comment]
I personally don't see this as a very high priority. Yes, someone can put in an empty string as the pattern for a split in Spark, but who actually wants that behavior? Unless this is very simple I would rather have us wait until we have a customer that actually wants this, or we run out of other things to do.

**Comment by ttnghia** [comment]
Agree. This is not a high priority.

**Comment by davidwendt** [comment]
You can call [`nvtext::character_tokenize()`](https://docs.rapids.ai/api/libcudf/stable/group__nvtext__tokenize.html#ga276c98f2ede96996eefa33be5473f8a4) in libcudf if you want to split on every character when you get an empty delimiter.

**Comment by davidwendt** [comment]
Since this function is already available, we can close this issue.

**Comment by ttnghia** [comment]
Sure. Close now.
