### ISSUE TITLE
[FEA]Read_parquet operator performance problem

### ISSUE THREAD

**Issue by lixiaolx** [rapidsai/cudf#10264]
**Is your feature request related to a problem? Please describe.**

When using the read_parquet operator to decompress and parse parquet data, a performance problem is encountered.
problem：
When the number of columns selected in the parquet file is large, make_string_column takes a lot of time and triggers multiple kernel-launches. At this time, gpu-util is low.

![image](https://user-images.githubusercontent.com/17673134/153353130-cc3635a9-4421-4750-94ed-7edf4bb63aec.png)

**Describe the solution you'd like**
What exactly is this part talking about? Is it necessary and can it be optimized to improve the GPU performance of the entire parquet

**Comment by devavret** [comment]
Are most of the columns selected in the file string columns? Conversion of each parquet string column to cudf string column might trigger a `make_string_column` call.

**Comment by lixiaolx** [comment]
> Are most of the columns selected in the file string columns?
There are 1300+ columns at most, and nsys-system finds that make_string_column is frequently triggered. Can this part be optimized?

**Comment by devavret** [comment]
> > Are most of the columns selected in the file string columns?
> There are 1300+ columns at most, and nsys-system finds that make_string_column is frequently triggered. Can this part be optimized?

This would require us to significantly rework creating string columns. i.e. we'd want to do them in a single kernel. I don't know how hard that would be but it doesn't look easy. @davidwendt can comment.

**Comment by GregoryKimball** [comment]
We expect poor GPU utilization for wide data sets with many columns and few rows.
