### ISSUE TITLE
[FEA] Refactor isclose tests.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10284]
**Is your feature request related to a problem? Please describe.**
In PR #10203, we discovered there is a pytest parametrization for `isclose` that is 6x6x6x6 = 1296 tests. https://github.com/rapidsai/cudf/pull/10203#discussion_r801107107

We can minimize the number of test cases dramatically while improving our test coverage.

**Describe the solution you'd like**
We want to cover all of the following cases for "low precision" (1e-5 or more, for unit scale data) and "high precision" (1e-8 or less, for unit-scale data):
- values are within rtol but not atol (tiny atol, but the scale of the values is large enough to catch it with rtol)
- values are within atol but not rtol (tiny rtol, scale of values is close to zero)
- values are outside of rtol and atol (easy case)
- values are inside of rtol and atol (easy case)
- different dtypes cast as expected (which requires the "high precision" case above for value scales on the order of 1)

We can parametrize these in a few (4-6) sets of parameters that provide both data and tolerances, instead of the full matrix of all data and tolerance combinations.

**Additional context**
- `isclose` is not commutative between `a` and `b`. The formula for `isclose(a, b, rtol, atol)` is `absolute(a - b) <= (atol + rtol * absolute(b))`.
- Real-world use cases of `isclose` often deal with comparing "small" differences, often at a precision greater than can be represented in a float32. That is, comparisons of `1.00000001` and `1`.
  - e.g. `np.float32(1.00000001) == 1` (indistinguishable float32 representations) but `not np.isclose(1.00000001, 1, rtol=1e-10, atol=1e-10)` (these values may be considered non-equal and not-close at some higher precision).
  - We can "defensively" choose our test data such that it would _fail_ if the data were cast as float32 instead of float64.

**Comment by vyasr** [comment]
I'm going to close this in favor of #13593
