### ISSUE TITLE
[BUG] series::to_array drops nan's

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#10304]
**Describe the bug**

`cudf.Series([0.0, None, 2.0]).to_array()` => `[0.0, 2.0]`

**Steps/Code to reproduce bug**

```python
import cudf
cudf.Series([1.0, 2.0, None, 4.0], dtype='float32').to_array()
```

**Expected behavior**

We expected the `NaN` value to not be dropped

**Environment overview (please complete the following information)**

`'22.02.00'` via conda stable inside Docker

**Extra context**

Not sure if this is new behavior or not, we just noticed it for the first time on some failing customer datasets. I did see `fillna` is a new param here...

**Comment by lmeyerov** [comment]
Looking further, explicitly setting `fillna=True` makes it work as we expected. Maybe the regression / desired behavior is to default it to `True`?

**Comment by lmeyerov** [comment]
Thanks!

And, yes - I appreciate that RAPIDS may want an internal method to reflect its internal data rep, but for an external interface, we expected a same-length buffer . Will check if the numpy method works as expected!

**Comment by lmeyerov** [comment]
I think we can close this -- at least for our case, confirmed `to_numpy()` is a predictable public interface, which makes sense. Something for getting the underlying buffers does make sense, but I'd hope `to_arrow()` would be better there.

**Comment by vyasr** [comment]
We actually `to_array` precisely because of this kind of surprising implicit behavior (among other reasons). I'll close this as you suggest, but feel free to open additional issues if you find that other methods have similar unpredictable behavior. That's definitely something that we'd like to root out.
