### ISSUE TITLE
[QST] Dockerfile example

### ISSUE THREAD

**Issue by albert17** [rapidsai/cudf#10301]
**What is your question?**
is there any dockerfile as example to build cudf as there was before: https://github.com/rapidsai/cudf/blob/branch-22.02/docker_build/Dockerfile ?

**Comment by galipremsagar** [comment]
Are you in need of `Docker` build [example](https://github.com/rapidsai/cudf/blob/branch-22.02/docker_build/Dockerfile)? We removed it recently assuming it was not being used, we could add it back if it is what you are looking for.

cc: @vyasr

**Comment by albert17** [comment]
I am building cudf from scratch  for Merlin Inference container: https://github.com/NVIDIA-Merlin/Merlin/blob/main/docker/dockerfile.tri#L81

So it is easy for me if I have an up-to-date reference about how to build it.

**Comment by vyasr** [comment]
The problem with having a file like that is that if we are not actively using it (and we weren't) it will inevitably go out of date and sprout errors. For instance, I'm not entirely certain that the example pointed to in the previous comments was actually an up-to-date reference, although it probably was at least a functional one. I think we would be better off pointing to examples of production containers built by the ops team that contain cudf, which do receive regular maintenance and stress testing. Even better would be if our production containers were built on top of multiple standalone containers for different tools that could easily be composed using multi-stage builds, but I am not sure how viable that is.

**Comment by GregoryKimball** [comment]
I'm reframing this as a proposal to add a link in our documentation to a production dockerfile.

**Comment by davidwendt** [comment]
I think the RAPIDS docker images call be accessed from here: https://hub.docker.com/r/rapidsai/rapidsai
The Dockerfiles are also available as well.
This link is at the bottom of the https://rapids.ai/start.html page which is included at top of the https://github.com/rapidsai/cudf README
Is this sufficient to close this?

**Comment by vyasr** [comment]
Maybe we should add links to https://github.com/rapidsai/docker as the source for the Dockerfiles as well (unless there's another set of Dockerfiles that you're thinking of?), but then yeah I think we ought to be set.

**Comment by GregoryKimball** [comment]
These links provide enough discoverability IMO
