### ISSUE TITLE
[FEA] Float32 and Int32 as default for variables.

### ISSUE THREAD

**Issue by titericz** [rapidsai/cudf#10318]
**Is your feature request related to a problem? Please describe.**
Creating a new DataFrame or a new variable always results in 64bit encoding column. A 32 bit variable is enough for 99% of the real life cases and consumes half GPU RAM than 64bit ones.

**Describe the solution you'd like**
Would be great to have 32bit by default variables(float32 and int32) and the possibility to select if the results of any operation would return in 32 or 64 bit mode.  A simple initial flag would be good to configure this mode. Eg: cudf.default_32bit() or cudf.default_64bit()

**Describe alternatives you've considered**

**Additional context**
Looks like that functionality is not available in Pandas as well.

**Comment by GregoryKimball** [comment]
Closed by #11272
