### ISSUE TITLE
[QST] - Performance with Spark3

### ISSUE THREAD

**Issue by eyalhir74** [rapidsai/cudf#10335]
Not sure this is the right group.
I'm trying to run some queries on big data. I've taken a portion of our data (only 43GB) and test some query with 15 fields in two scenarios:
1. 24 CPU cores with 200 files, up to 400MB per file
2. X CPU cores with one V100 GPU with 10 files, each about 4+GB as per the tuning guide suggestions.

The GPU is mostly idle and runs much slower than the CPU. Running the Spark on the GPU with the 400MBs files, runs slow as well.

I'm using the following command to run the GPU code:
`$SPARK_HOME/bin/spark-shell        --master "local[10]"  --driver-memory 50g        --conf spark.locality.wait=0s         --conf spark.rapids.memory.pinnedPool.size=30G        --conf spark.sql.files.maxPartitionBytes=256m   --conf spark.rapids.sql.concurrentGpuTasks=2        --conf spark.plugins=com.nvidia.spark.SQLPlugin        --jars ${SPARK_CUDF_JAR},${SPARK_RAPIDS_PLUGIN_JAR}  
`
Changing maxPartitionBytes or concurrentGpuTasks or any other parameter, doesn't seem to have any effect.
As far as I can see most of the time the network I/O is not working nor does the GPU.

Any idea would be highly appereciated.

**Comment by shwina** [comment]
Perhaps you could raise this issue in https://github.com/NVIDIA/spark-rapids/?

**Comment by eyalhir74** [comment]
Thank you @shwina , I'll post there and close this one.
