### ISSUE TITLE
[FEA]  Add support for CSV reading ANSI day-time interval

### ISSUE THREAD

**Issue by res-life** [rapidsai/cudf#10356]
**Is your feature request related to a problem? Please describe.**
CSV stores ANSI day-time interval as string, e.g: 
```
INTERVAL '100 10:30:40.999999' DAY TO SECOND
```
When reading CSV, there are need to parse interval string to long microseconds.

**Describe the solution you'd like**
- Cast ANSI day-time string to long microseconds
- Cast long microseconds to ANSI day-time string
- CSV support reading ANSI day-time interval, internally save as long microseconds column view.

Interval types can be found in https://spark.apache.org/docs/latest/sql-ref-datatypes.html.
Interval types includes YearMonthIntervalType and DayTimeIntervalType.
This feature only involves DayTimeIntervalType.
For DayTimeIntervalType, it has 10 types: 
INTERVAL DAY,  INTERVAL DAY TO HOUR, ... , INTERVAL SECOND

![选区_002](https://user-images.githubusercontent.com/8166419/155649086-d71123e3-ad6e-44ec-893d-77c05dcc9b74.png)

The function signature may be like:
```
column castIntervalStringToLong(
   column,   // string column contains interval strings
   YearMonthIntervalType(startField, endField)  // the format of interval strings
)

column castLongToIntervalString(
   column,   // string column contains interval strings
   YearMonthIntervalType(startField, endField),  // the format of interval strings
)
```

**Additional context**

hour range is [0, 23]  
minute range is [0, 59]  
second range is [0, 99]:  Note currently 99 is valid, I think it's a bug and I'll file a bug. The corrent ragne should be [0,59]  
micro seconds is 9 digits, but when convert to micro seconds, the NANOSECONDS is truncated.
e.g.: .111111999, the 999 NANOSECONDS is truncated.  

How to check the day-time interval is valid:
```
$SPARK_HOME/bin/pyspark
spark.sql("select INTERVAL '10 23:59:10.999999' DAY TO SECOND")
```
or use spark master code
```
IntervalUtils.castStringToDTInterval
```

Some examples of format for day to second interval
|type|example|valid|comment|
|:-|:-|:-|:-|
|INTERVAL DAY TO SECOND | INTERVAL '100 10:30:40.999999' DAY TO SECOND  |true    |    |
|INTERVAL DAY TO SECOND | INTERVAL '100 10:30:40. &nbsp;  &nbsp;999999' DAY TO SECOND  |false    | has extra spaces   |
|INTERVAL DAY TO SECOND | INTERVAL '100  &nbsp;  &nbsp; 10:30:40.999999' DAY TO SECOND  |false    |  has extra spaces     |
|INTERVAL DAY TO SECOND | INTERVAL '-100 10:30:40.999999' DAY TO SECOND  |true    |       |
|INTERVAL DAY TO SECOND | INTERVAL -'-100 10:30:40.999999' DAY TO SECOND  |true    |    two negative signs is positive  |
|INTERVAL DAY TO SECOND | INTERVAL '100 24:30:40.999999' DAY TO SECOND  |false    |    hour 24 outside range [0, 23] |
|INTERVAL DAY TO SECOND | INTERVAL '10 23:61:01.123456' DAY TO SECOND  |false    |    minute 61 outside range [0, 59] |
|INTERVAL DAY TO SECOND | INTERVAL '10 23:59:88.999999' DAY TO SECOND  |true    |88 second is valid!!!, will file a bug  |
|INTERVAL DAY TO SECOND | INTERVAL '100 26:30:40.111111999' DAY TO SECOND  |true    |999NS is truncated  |
|INTERVAL DAY TO SECOND | -100 10:30:40.999999  |true    |       |
|INTERVAL DAY TO SECOND | 100 10:30:40.999999  |true    |    |
|INTERVAL DAY TO SECOND | 100  &nbsp;  &nbsp;  10:30:40.999999  |false    | has extra spaces      |
|INTERVAL DAY TO SECOND | 100 10:30: &nbsp;  &nbsp; 40.999999  |false    | has extra spaces      |

This is an issue in Spark-Rapids plugin: https://github.com/NVIDIA/spark-rapids/issues/4146

**Comment by res-life** [comment]
Second rang is not [0, 59] bug:
https://issues.apache.org/jira/browse/SPARK-38324

**Comment by revans2** [comment]
To be clear this is a nice to have feature and it would be good to understand if pandas or others have something similar. If not we can look at supporting converting the strings ourselves.  We have an implementation right now that uses regular expressions, but that is expensive and we would like to avoid it. Even thought the interval types are ANSI SQL, I don't know if the format of the data is also standard.

**Comment by GregoryKimball** [comment]
If you would like cuDF-python to support CSV reading in ANSI day-time interval, please reopen this issue.
