### ISSUE TITLE
[FEA] Remove `copying::sample` from libcudf

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#10361]
**Is your feature request related to a problem? Please describe.**
In #10262 cuDF python moved away from depending on libcudf `sample` API. Instead, the gather map is generated depending on the random state provided by user. Current libcudf implementation of `sample` generates the gather map based on the provided seed and thrust random engine, the result is isn't an exact match with that from pandas. CuDF opted to transparently let the random state that user passes in to handle the gather map generation. This allows the flexibility for users to choose from either they want 1-1 result matches with that from pandas by supplying a numpy random state, or have device accelerated gather map generation that's on par with libcudf (~7% difference).

**Describe the solution you'd like**
If no other dependency is on `copying::sample`, it can be removed from libcudf.

**Describe alternatives you've considered**
N/A

**Comment by revans2** [comment]
Actually JAVA exports an API for this https://github.com/rapidsai/cudf/blob/4c9ef5161268e2486938546deef00f7fc84c9a95/java/src/main/native/src/TableJni.cpp#L3556-L3568 and it is used in the Spark plugin.  We have similar issues with producing the exact same results, so we don't use it by default, but the performance difference between generating random numbers on the CPU and pushing them down to the GPU vs doing it all on the GPU is large, so we have kept it as an option for users.

**Comment by vyasr** [comment]
I see. In Python users have the option of generating the random numbers on device using `cupy`, which as @isVoid points out results in only about a 7% perf hit relative to `libcudf::sample`. I guess there's no Java alternative for producing those random numbers? The only thing I could imagine is if there was a JNI for thrust, but of course that would blow up in size pretty fast with template instantiations.

**Comment by revans2** [comment]
We also have the problem that we are at a SQL layer, so you could do it with a special user defined function that does random number generation on the GPU, but then we are asking users to change their code for this.

**Comment by vyasr** [comment]
Fair enough. If this function continues to have value for the Java side it should be fine to leave it then. I suggested opening this issue to @isVoid since Python is removing its reliance on it and I didn't want to leave unnecessary cruft hanging around, but it sounds like this is useful to you.

**Comment by jrhemstad** [comment]
> This allows the flexibility for users to choose from either they want 1-1 result matches with that from pandas by supplying a numpy random state

How does this work? What is the performance of this code path?

Trying to guarantee identical results with serial vs random number generation is a bit scary.

**Comment by isVoid** [comment]
> > This allows the flexibility for users to choose from either they want 1-1 result matches with that from pandas by supplying a numpy random state
> 
> How does this work? What is the performance of this code path?

The gather map is created with numpy generator on host, passed to device and gathered on device. The performance is no doubt slower than today's code path, see benchmark (https://github.com/rapidsai/cudf/pull/10262#issue-1129241644). There's also an alternative if user does not wish to have 1-1 result with pandas but just matching shapes, a cupy generator can be used and gather map is created on device. See description in docstring: https://github.com/isVoid/cudf/blob/improvement/rewrite_sample/python/cudf/cudf/core/indexed_frame.py. My original thoughts are matching results with pandas is part of pandas API alignment roadmap, but I could be stretching the idea a bit, would like to weigh in more opinions before I proceed.

**Comment by vyasr** [comment]
@jrhemstad to be clear, we are not guaranteeing identical results between serial and parallel RNGs (which is basically impossible with the tools available to us, we would need to implement custom RNGs or at least find alternate implementations). We are allowing the user to specify that they want random numbers to be generated on the host if exact pandas equivalence is more important than performance to them. It's entirely opt-in, and the performance implications are documented. The default behavior is to generate random numbers on device using cupy and then pass that buffer to gather, which results in about a 7% perf degradation relative to the pure libcudf solution as @isVoid mentions in the PR description.
