### ISSUE TITLE
[FEA] dtype as argument parameter for Series/Dataframes

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1037]
I should be able to define the dtype of Series/Dataframe during construction:

```
cudf.DataFrame({}, dtype=np.int)
cudf.Series({}, dtype='int')
```

**Comment by beckernick** [comment]
This is now possible for Series, but still not for DataFrames.

**Comment by brandon-b-miller** [comment]
Picking this up.

**Comment by beckernick** [comment]
@brandon-b-miller , if you're updating the constructors, it might be convenient to explore https://github.com/rapidsai/cudf/issues/2715 , too.

**Comment by brandon-b-miller** [comment]
I think the simplest way to handle this is with something like 

`if dtype is not None: df._cols = df.astype(dtype)._cols` 

at the very end of construction, is anyone opposed to this approach? If not I'll work on getting [df.astype](https://github.com/rapidsai/cudf/issues/2195) done as an upstream blocker for this.
