### ISSUE TITLE
[FEA]  Support field id meta in Parquet writing

### ISSUE THREAD

**Issue by res-life** [rapidsai/cudf#10375]
**Is your feature request related to a problem? Please describe.**
[SPARK-38094](https://issues.apache.org/jira/browse/SPARK-38094) added the support to write field id in Parquet metadata.

// Sample Meta of CPU generated parquet file
message spark_schema {
  optional int32 c1 = 1;
}

// Sample Meta of GPU generated parquet file
message schema {
  optional int32 c1;
}

Description of [Spark PR](https://issues.apache.org/jira/browse/SPARK-38094) is

Field Id is a native field in the Parquet schema (https://github.com/apache/parquet-format/blob/master/src/main/thrift/parquet.thrift#L398)

After this PR, when the requested schema has field IDs, Parquet readers will first use the field ID to determine which Parquet columns to read, before falling back to using column names as before. It enables matching columns by field id for supported DWs like iceberg and Delta.

**Describe the solution you'd like**
Add the support of write field id in Parquet metadata.
Currently CompressionMetadataWriterOptions.withMetadata is used to store some metadata.
cuDF can use this to get the "parquet.field.id" information.
For example:
```
org.apache.spark.sql.parquet.row.metadata: {"type":"struct","fields":
[{"name":"c1","type":"integer","nullable":true,"metadata":{"parquet.field.id":1}}]}
```
Is this appropriate?  Or add a parameter in NestedBuilder.withColumns.

**Describe alternatives you've considered**
No need to support reading with the field id.

**Additional context**
Below is a simple example.
```
$SPARK_HOME/bin/spark-shell
import org.apache.spark.sql.execution.datasources.parquet._
import org.apache.spark.sql.types._
import org.apache.spark.sql._
def withId(id: Int) = new MetadataBuilder().putLong(ParquetUtils.FIELD_ID_METADATA_KEY, id).build()
val schema = new StructType().add("c1", IntegerType, nullable = true, withId(1))
val data = (1 to 10).map(i => Row(i))
val df = spark.createDataFrame(sc.parallelize(data), schema)
val path = "/tmp/my-parquet"
df.coalesce(1).write.mode("overwrite").parquet(path)

parquet-tool meta xxx.parquet
// Meta of CPU generated parquet file
message spark_schema {
  optional int32 c1 = 1;
}

// Meta of GPU generated parquet file
message schema {
  optional int32 c1;
}
```

**Comment by jlowe** [comment]
This issue is asking for the Java API to support field ID control.  I filed #10376 for libcudf/cuIO support, which would be required to implement the Java API.

**Comment by res-life** [comment]
still interested

**Comment by res-life** [comment]
I'm working on the Java API.
