### ISSUE TITLE
[BUG] JNI side is not setting the proper alignment for the `limiting_resource_adaptor` with ASYNC

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#10384]
In RmmJni, our use of `limiting_resource_adaptor` doesn't seem to be setting the proper alignment when wrapping the ASYNC allocator.

https://github.com/rapidsai/cudf/blob/branch-22.04/java/src/main/native/src/RmmJni.cpp#L360

There is an argument to the constructor of this adaptor to set the proper alignment, and it defaults to 256 bytes. From experiments, the ASYNC allocator looks to be aligning to 512 bytes, so we are going to be under counting if we are trying to track the amount of memory available in the pool.

**Comment by abellina** [comment]
Our tracking wrapper should also be updated to match 512 for ASYNC.

**Comment by rongou** [comment]
The CUDA programming guide only specifies
> Any address of a variable residing in global memory or returned by one of the memory
allocation routines from the driver or runtime API is always aligned to **at least** 256 bytes.

The actual alignment size seems to be an internal decision of the driver/runtime, not a public api.

**Comment by abellina** [comment]
> The actual alignment size seems to be an internal decision of the driver/runtime, not a public api.

Thanks @rongou. Then we shouldn't rely on the potential alignment we have seen in experiments. It seems we can't really limit the pool size then as it was intended with `limiting_resource_adaptor`, since the API doesn't make a guarantee.
