### ISSUE TITLE
[FEA] Implement DataFrame.info

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#1038]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to know which is the current memory usage of a DataFrame.

That info can be retrieved in Pandas with _pandas.DataFrame.info_ method.

**Describe the solution you'd like**
To be implemented something similar to https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html

**Describe alternatives you've considered**
None yet.

**Additional context**

**Comment by miguelangel** [comment]
Hi!

I was wondering if there is any ETA for this feature request.

Thanks!
Miguel
