### ISSUE TITLE
[DOC] set_index on series should has been removed from documentation

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#10390]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.Series.set_index.html?highlight=set_index

**Describe the problems or issues found in the documentation**
According to https://github.com/rapidsai/cudf/issues/9541 , the set_index() method for a Series is not available anymore.

Nevertheless, the method is still available in the documentation.

**Steps taken to verify documentation is incorrect**
Reading the PR and double-checking the documentation.

**Suggested fix for documentation**
Delete that entry in the documentation
---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by galipremsagar** [comment]
This is fixed as part of https://github.com/rapidsai/cudf/pull/9945/, but will only reflect once the release is complete.
