### ISSUE TITLE
[BUG] Use standard (lowercase) doxygen tags

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1039]
In Doxygen, the keyword used for parameters is `@param`. Note: Lower case. However, all of our Doxygen comments are laced with `@Param` . While doxygen itself may (or may not) overlook this, some IDEs do not, messing up syntax highlighting and pop-up explanations. The same goes for `@Returns`, etc.

So we should just lowecase the lot.

Also - we should use `@brief` instead of `@Synposis` (or `@synopsis`).

This issue is a bit related to PR #823 .

**Comment by eyalroz** [comment]
@kkraus14 : How about also doing @Synopsis -> @brief at the same time? `@Synopsis` (or `@synposis`) is also [non-standard](http://www.doxygen.nl/manual/commands.html).

**Comment by eyalroz** [comment]
@kkraus14 Actually, I just noticed I missed one or two functions which were added to branch-0.6 before I had forked it last... `gdf_replace_nulls` and `gdf_digitize`.

**Comment by kkraus14** [comment]
> @kkraus14 Actually, I just noticed I missed one or two functions which were added to branch-0.6 before I had forked it last... `gdf_replace_nulls` and `gdf_digitize`.

Feel free to open up a followup PR, no worries!

**Comment by harrism** [comment]
> In Doxygen, the keyword used for parameters is `@param`. Note: Lower case. However, all of our Doxygen comments are laced with @param .

I don't see the difference in the two versions of `@param` you wrote above. Can you clarify?

**Comment by eyalroz** [comment]
> I don't see the difference in the two versions of `@param` you wrote above. Can you clarify?

GitHub is doing something weird to the capitalization. Let me try to force it to do what I want...
