### ISSUE TITLE
[FEA] support min and max group by aggregations and reductions on lists of structs and strings

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10408]
**Is your feature request related to a problem? Please describe.**
This is specifically for https://github.com/NVIDIA/spark-rapids/issues/4929 for a customer query.

**Describe the solution you'd like**
Group by and reduction aggregations for min/max that support lists of structs and lists of strings. Ideally we could solve ordering in general like #5890 is trying to do. This would then be a follow on PR to reuse the row comparison code for min/max in this case. 

If more information is needed like null ordering etc I can provide it.

**Describe alternatives you've considered**
Just ugly hacks that we should not do.

**Comment by revans2** [comment]
It is the second one `1, b, 1, b` vs `1, a, 2, b`. But more generally sorting a list in Spark looks at each element in the list starting at the first and only if they are the same does it look at the next elements to break the tie.

null == null in sorting elements, but null < non-null

If one list is longer than another list, then it shorter list is less than the longer list if and only if all of the elements in the shorter list match those in the longer list up to the length of the shorter list. 

The code here is for sorting list/arrays in Spark

https://github.com/apache/spark/blob/a26c01d85035b487e2048f1c106b14b89455e2d9/sql/catalyst/src/main/scala/org/apache/spark/sql/types/ArrayType.scala#L116-L148

If you want some examples I can some up with a few.

**Comment by ttnghia** [comment]
@devavret I suppose to work on this, if nobody has been assigned.

**Comment by jrhemstad** [comment]
@ttnghia please hold off. This requires further discussion.

**Comment by sameerz** [comment]
Sill needed

**Comment by sameerz** [comment]
Still needed.

**Comment by ttnghia** [comment]
Depend on https://github.com/rapidsai/cudf/pull/10811.
