### ISSUE TITLE
Convert cuda array to cudf column in C++[QST]

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#10406]
**What is your question?**
Hello, I have a cuda implementation and prefer converting the kernel outputs into cudf:: column or  cudf:: table for processing and writing. How can I do that if I have a cuda array with `int` type for example? Appreciate it if someone has an idea about it. 

Here is the declaration of cuda array
```
cudaMalloc(&d_x, n*sizeof(int)); 
```

**Comment by davidwendt** [comment]
What kind of processing? 
A `cudf::column` is an owning class which manages its own data. 
Most libcudf APIs take a `cudf::column_view` as input.
You can wrap an existing array of ints with a `cudf::column_view` which is a read-only, non-owning view of column data: https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1column__view.html

For example
```
int* d_x;
cudaMalloc(&d_x, n*sizeof(int));
// ... put integer data into d_x ...
// wrap d_x with a column_view
cudf::column_view cv( cudf::data_type{cudf::type_id::INT32}, n, d_x );
// call libcudf API with cv
```

The same for `cudf::table` which owns its collection of `cudf::columns`. There is a `cudf::table_view` which is what most libcudf APIs accept. A [`cudf::table_view`](https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1table__view.html) can be created from a `std::vector` of `cudf::column_views` https://docs.rapids.ai/api/libcudf/stable/classcudf_1_1detail_1_1table__view__base.html#a1efbcc85f85d8e30b06e29633df0ca38

**Comment by MikeChenfu** [comment]
Many thanks @davidwendt. The example and doc are super helpful.
