### ISSUE TITLE
[FEA] Replace cudf's `concurrent_unordered_map` with `cuco::static_map`.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10401]
I noticed that `concurrent_unordered_map` and `concurrent_unordered_multimap` are not defined in the `cudf` namespace (they're in the global/root namespace). After discussion with @PointKernel, it seems we may be able to replace the existing uses of `concurrent_unordered_map` with `cuco::static_map` and delete these from libcudf. I plan to look at this after finishing another refactoring project #10081. Currently `cuco` only supports keys/values up to 8 bytes, but these use cases appear to be fine even with that limitation.

Current uses of `concurrent_unordered_map`:
- https://github.com/rapidsai/cudf/blob/b3dc9d6adf16635c94a1735ad9ca73c12494884e/cpp/src/io/json/json_gpu.h
- https://github.com/rapidsai/cudf/blob/b3dc9d6adf16635c94a1735ad9ca73c12494884e/cpp/src/groupby/hash/groupby.cu
- https://github.com/rapidsai/cudf/blob/b3dc9d6adf16635c94a1735ad9ca73c12494884e/cpp/src/io/json/reader_impl.cu (header included but not used)

~~Current uses of `concurrent_unordered_multimap`:~~
- ~~None. Only tests. https://github.com/rapidsai/cudf/blob/b3dc9d6adf16635c94a1735ad9ca73c12494884e/cpp/tests/hash_map/multimap_test.cu~~

**Comment by PointKernel** [comment]
@bdice Minor correction: `cuco` can handle key/value pairs larger than 8 bytes but does not support concurrent insert and find in that case (see https://github.com/NVIDIA/cuCollections/issues/137).

**Comment by GregoryKimball** [comment]
Closing this in favor of #12261
