### ISSUE TITLE
[FEA] Add date attribute to cudf.dataframe.series.Series.dt

### ISSUE THREAD

**Issue by paulhendricks** [rapidsai/cudf#1041]
**Is your feature request related to a problem? Please describe.**

Add date attribute to cudf.dataframe.series.Series.dt so one can access the date component of a `datetime64[ms]` column.

```python
print(gdf['datetime'].dt.date)  # AttributeError: 'DatetimeProperties' object has no attribute 'date'
```

The whole reproducible code is below:

```python
import cudf


# Create a test csv file
filename = 'foo.csv'
lines = [
  "num1,datetime,text",
  "123,2018-11-13T12:00:00,abc",
  "456,2018-11-14T12:35:01,def",
  "789,2018-11-15T18:02:59,ghi"
]
with open(filename, 'w') as fp:
    fp.write('\n'.join(lines)+'\n')

# Read the file with cudf using only certain columns (omitting strings)
names = ['num1', 'datetime', 'text']
dtypes = ['int', 'date', 'str']
gdf = cudf.io.csv.read_csv(filename, delimiter=',',
                        names=names, dtype=dtypes,
                        skiprows=1, usecols=['num1', 'datetime'])
print(gdf.head())
print(gdf.dtypes)

# Access time information
print(gdf['datetime'].dt.day)
print(gdf['datetime'].dt.month)
print(gdf['datetime'].dt.year)
print(gdf['datetime'].dt.hour)
print(gdf['datetime'].dt.minute)
print(gdf['datetime'].dt.second)

# Access date part i.e. "2018-11-13"
print(gdf['datetime'].dt.date)  # AttributeError: 'DatetimeProperties' object has no attribute 'date'

import pandas as pd

df = pd.read_csv('foo.csv')
df['datetime'] = pd.to_datetime(df['datetime'])
print(df)
print(df.dtypes)


# Access date 
df['datetime'].dt.date  # Works!
```

**Describe the solution you'd like**

```python
# Access date part
print(gdf['datetime'].dt.date)
```

**Describe alternatives you've considered**
Could use the `year`, `month`, `day` and concatenate a string. Implementing `date` would mirror the Pandas API.

**Additional context**

Pandas functionality here: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.date.html

**Comment by harrism** [comment]
@kkraus14 this is tagged with libcudf -- is there a feature needed? Is it covered by @trxcllnt 's work on timestamp types?

**Comment by JulianWgs** [comment]
What are the reasons for the postponings? Is there a release time frame?

**Comment by kkraus14** [comment]
@JulianWgs this just hasn't been prioritized thus far. That being said, it looks like this returns Python `datetime.date` objects which we can't mirror onto the GPU so we likely can't mirror Pandas behavior exactly here. We'll likely return a column of `date32` type in the future once we have the dtype plumbed into the Python.

**Comment by beckernick** [comment]
This was the original issue, but some details / complexity have been further fleshed out in https://github.com/rapidsai/cudf/issues/7880 . As a result, I'm going to close this in favor of 7880 to consolidate discussion.
