### ISSUE TITLE
[FEA] Add `.between()` to create easier range based mapping

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#10443]
**Is your feature request related to a problem? Please describe.**
 I was trying to create a set of age ranges for a classifier but couldn't use `.between` 

**Describe the solution you'd like**
```
import pandas as pd
import numpy as np

df = pd.DataFrame(data=np.random.randint(1,10,10), columns=['a'])

criteria = [df['a'].between(1, 3), df['a'].between(4, 7), df['a'].between(8, 10)]
values = [1, 2, 3]

df['b'] = np.select(criteria, values, 0)
print(df.head())
```

**Comment by beckernick** [comment]
Per the [pandas documentation](https://pandas.pydata.org/docs/reference/api/pandas.Series.between.html), this function is equivalent to `(left <= ser) & (ser <= right)` (with exclusivity/inclusivity determined by a parameter)
