### ISSUE TITLE
[FEA] customizable default for segmented_reduce value on empty segments

### ISSUE THREAD

**Issue by gerashegalov** [rapidsai/cudf#10455]
**Is your feature request related to a problem? Please describe.**
Currently segmented_reduce returns NULL for various inputs, including empty inputs. For empty inputs NULL is not always a natural choice. E.g. when implementing a Boolean aggregation `exists` https://github.com/NVIDIA/spark-rapids/pull/4973 for Spark SQL, empty input quite intuitively results in `false`

**Describe the solution you'd like**
The most generic solution is to simply to allow the user to pass the initial value for reduction similar to Scala [fold](https://www.scala-lang.org/api/2.12.15/scala/collection/immutable/Seq.html#fold[A1%3E:A](z:A1)(op:(A1,A1)=%3EA1):A1) 

**Describe alternatives you've considered**
As a workaround, we have to compute a Bool column for the post processing step of fixing up "wrong" results.

**Comment by jrhemstad** [comment]
Makes sense to me. No different than [cub's segmented reduce](https://nvlabs.github.io/cub/structcub_1_1_device_segmented_reduce.html#a6f89d5a541dfb20bd1ea4e990863ac66) taking an initial value.

**Comment by bdice** [comment]
Providing an initial value for the reduction is different than post-processing to replace null values. Which do you want? There's an implicit 'operator identity' right now as the default value, and its behavior wrt null inclusion/exclusion has the potential to change if a default value besides the identity is allowed.

For example, consider the operator `+`, initial value of 0 (the operator identity), and segment data `[null]`. Currently, the behavior is to return `null` for both `null_policy::INCLUDE` and `null_policy::EXCLUDE`. It seems that this proposed change could mean either of:
1. `reduce(+, 0, [null], include) == null`, `reduce(+, 0, [null], exclude) == 0`
    - Equivalent to left-fold with null semantics from the initial value
    - Note the behavior change from `null` to `0` for exclude!
2. `reduce(+, 0, [null], include) == 0`, `reduce(+, 0, [null], exclude) == 0`
    - Equivalent to trivial post-processing to replace `null` with 0

If it's (1) you're seeking, this could be in libcudf. If it's (2) you're seeking, I would recommend a trivial postprocessing.

Here's a larger matrix of examples:
<details>
<summary>Click to expand</summary>

| Initial value | Segment Data | Nulls   | Result of left fold (+) from initial value | Result of post-processed null replacement |
|---------------|--------------|---------|--------------------------------------------|-------------------------------------------|
| (identity)    | []           | Include | 0                                          | 0                                         |
| (identity)    | []           | Exclude | 0                                          | 0                                         |
| (identity)    | [1, 2]       | Include | 3                                          | 3                                         |
| (identity)    | [1, 2]       | Exclude | 3                                          | 3                                         |
| (identity)    | [null]       | Include | null                                       | 0                                         |
| (identity)    | [null]       | Exclude | 0 (currently gives null!)                  | 0                                         |
| (identity)    | [1, null]    | Include | null                                       | 0                                         |
| (identity)    | [1, null]    | Exclude | 1                                          | 1                                         |
| 42            | []           | Include | 42                                         | 42                                        |
| 42            | []           | Exclude | 42                                         | 42                                        |
| 42            | [1, 2]       | Include | 45                                         | 45                                        |
| 42            | [1, 2]       | Exclude | 45                                         | 45                                        |
| 42            | [null]       | Include | null                                       | 42                                        |
| 42            | [null]       | Exclude | 42                                         | 42                                        |
| 42            | [1, null]    | Include | null                                       | 42                                        |
| 42            | [1, null]    | Exclude | 43                                         | 1                                         |

</details>

**Comment by jrhemstad** [comment]
> Providing an initial value for the reduction is different than post-processing to replace null values.

Unless I'm misunderstanding, I don't think @gerashegalov is asking for post-processing to replace nulls.

He's saying that when there is an empty segment it currently returns `null`. It would be nice instead if an empty segment would just return the `init` value instead. 

This is a natural extension of how`std::reduce` on an empty input range will just return the initial value.

https://godbolt.org/z/e8TYo4Yd6

I was a little surprised that we don't have an `initial_value` argument in `cudf::reduce`.

**Comment by gerashegalov** [comment]
> Unless I'm misunderstanding, I don't think @gerashegalov is asking for post-processing to replace nulls.

Correct, we have already implemented postprocessing because there is no way to specify the initial value for aggregation https://github.com/NVIDIA/spark-rapids/blob/branch-22.06/sql-plugin/src/main/scala/com/nvidia/spark/rapids/higherOrderFunctions.scala#L398-L402

**Comment by davidwendt** [comment]
Both `cudf::reduce` and `cudf::segmented_reduce` accept an initial-value parameter now.
If you pass `false` as an initial value for the `ANY` aggregation type (`cudf::make_any_aggregation<cudf::segmented_reduce_aggregation>()`) then empty segments will return `false` and not null. Null rows are still controlled by the `null_policy` parameter.

```
input = [0,0], [1,1], [1,0], [0,1,1], [], [1,null], [0,null]
init_value = false
result = cudf::segmented_reduce(input, ANY, BOOL8, EXCLUDE, init_value)
result -> [false, true, true, true, false, true, false]

result = cudf::segmented_reduce(input, ANY, BOOL8, INCLUDE, init_value)
result -> [false, true, true, true, false, null, null]
```
Without the initial value, the empty segments will result in a null row.

**Comment by vyasr** [comment]
Can we close this now, then? Or is there an outstanding ask remaining?

**Comment by gerashegalov** [comment]
> Can we close this now, then? Or is there an outstanding ask remaining?

Thanks, I don't believe so. We'll open more issues if needed
