### ISSUE TITLE
[BUG] Left Semi Join much slower than Inner join

### ISSUE THREAD

**Issue by cheinger** [rapidsai/cudf#10464]
**Describe the bug**
I’ve noticed that Left Semi Join can be an order of magnitude slower than Inner Join. Below you can see the 10x slow down when we switch out Inner Join for Left Semi Join (same data & table sizes).

**Inner Join**
<img width="720" alt="Screen Shot 2022-03-18 at 6 06 11 PM" src="https://user-images.githubusercontent.com/12998801/159100763-56dfaad6-6a06-4fbf-9b0e-57fd2dddd6e9.png">

**Left Semi Join**
<img width="720" alt="Screen Shot 2022-03-18 at 6 06 06 PM" src="https://user-images.githubusercontent.com/12998801/159100761-55949ef4-6408-408a-aeb9-14c621f84cc6.png">

I did some further investigation and found that the cause for this slow down is the [thrust::copy_if](https://github.com/rapidsai/cudf/blob/21ed2519e20f95bad680bbd8d8fc6d379e320cee/cpp/src/join/semi_join.cu#L140) in `left_semi_anti_join` that copies the selected row indices that are found in the hash table. I switched this out for `cub::DeviceSelect::Flagged` and observed an 18x performance improvement as seen below:

**Before**
<img width="824" alt="Screen Shot 2022-03-18 at 5 11 11 PM" src="https://user-images.githubusercontent.com/12998801/159100792-ce919956-2f83-4cd7-b8d2-ad1ede3e35b8.png">

**After**
<img width="824" alt="Screen Shot 2022-03-18 at 5 11 41 PM" src="https://user-images.githubusercontent.com/12998801/159100794-1c7e0aaa-cec3-4735-9323-52803691234c.png">

**Expected behavior**
I would expect Left Semi Join and Inner Join to be somewhat comparable in performance, and if anything, Inner Join to be slower because we have to handle duplicate keys.

**Environment details**
[env_details.log](https://github.com/rapidsai/cudf/files/8308350/env_details.log)

**Comment by cheinger** [comment]
I have created a PR with a fix: https://github.com/rapidsai/cudf/pull/10511

**Comment by jrhemstad** [comment]
I'm more interested to know why `thrust::copy_if` is so much slower than `cub::DeviceSelect::flagged`. If they don't share the same implementation, then they should be made to.
