### ISSUE TITLE
[FEA] Refactor ORC's dictionary encoding using cuCo

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#10495]
ORC writer uses dictionary encoding on string columns and uses a custom hash map like structure. This is not needed anymore as we can use cuCo's hash maps.

Using #8476 as a template, we should be able to refactor and clean up the dictionary encoding code that currently resides in `src/io/orc/dict_enc.cu`

**Comment by PointKernel** [comment]
Still relevant

**Comment by GregoryKimball** [comment]
Closed by https://github.com/rapidsai/cudf/pull/13580
