### ISSUE TITLE
[BUG] read_csv is adding extra blank rows to data frame.

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#1050]
**Describe the bug**
When reading a csv file,` cudf.read_csv()` adds extra blank rows to the data frame. On a csv of ~ 18K rows, about 280 extra were added. In this reproduction of the issue, you will see 

**Steps/Code to reproduce bug**
This code, when used on the CSV file, reproduces the issue. 

```import os
import cudf
RAW_DATA = os.path.expanduser('small_hour_repo.csv')
gdf = cudf.read_csv(RAW_DATA)
len(gdf)
df = gdf.to_pandas()
df[df['temp'].isna()]
```

A 299 row subset of the original data is shared here: https://drive.google.com/open?id=12prslVeAlGqERB7DR5q_AVx4N5v9We50

**Expected behavior**
This creates a data frame with 4 extra rows added in, with all variables left as NaNs. 

**Environment details (please complete the following information):**
 - Environment location: Bare metal
 - Method of cuDF install: conda
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
**Additional context**
Code was executed in Jupyter Lab. 
[env.txt](https://github.com/rapidsai/cudf/files/2906498/env.txt)

**Comment by vuule** [comment]
I've made some changes recently that should also fix this issue.
@robocopnixon, can you please merge https://github.com/rapidsai/cudf/pull/1044 and check if the issue still reproes?

**Comment by vuule** [comment]
I cannot repro the issue with branch-0.6. 
@robocopnixon, which cuDF version are you using?

**Comment by j-ieong** [comment]
The env.txt shows `cudf 0.5.1`. @robocopnixon, can you try 0.6 if possible? Thanks!

**Comment by robocopnixon** [comment]
Okay, I did try this on 0.6 and it is no longer present. Thank you.
