### ISSUE TITLE
cudaErrorMemoryAllocation out of memory

### ISSUE THREAD

**Issue by faker2081** [rapidsai/cudf#10517]
**Describe the bug**
MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /usr/local/miniconda3/envs/rapids-22.02/include/rmm/mr/device/cuda_memory_resource.hpp

Even if it reads an empty file, it  will also report the error!

**Expected behavior**
```python 
df = cudf.Series([1,2,3,None,4])
```

**Environment overview **
 - Environment location: Cloud
 - Method of cuDF install: conda
   

**Environment details:**
- i use the flow command to create a conda virtual env:
```python 
conda create -n rapids-22.02 -c rapidsai -c nvidia -c conda-forge rapids=22.02 python=3.8 cudatoolkit=11.4 dask-sql
```

then i use the virtual env to make jupyter kernel

i hope someone can solve it.

**Comment by beckernick** [comment]
Hi @faker2081 , could you please provide more information about the system on which you are running? One option would be to clone this repository and run the `print_env.sh` script.
