### ISSUE TITLE
[BUG] read_csv includes return character in column name. 

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#1051]
**Describe the bug**
`read_csv()` writes the final variable name here as "cnt\r" rather than "cnt" like it does in pandas. 

**Steps/Code to reproduce bug**
```import os
import cudf
RAW_DATA = os.path.expanduser('small_hour_repo.csv')
gdf = cudf.read_csv(RAW_DATA)
print(gdf.columns)
```
The data file to reproduce the issue is available here: https://drive.google.com/open?id=12prslVeAlGqERB7DR5q_AVx4N5v9We50

**Expected behavior**
The return character should not be included in the column name. Pandas is able to do this. 

**Environment details (please complete the following information):**
 - Environment location: Bare Metal. 
[env.txt](https://github.com/rapidsai/cudf/files/2906540/env.txt)

**Additional context**
There doesn't seem to be anything exceptional about the underlying data. I looked at the file with all hidden characters

**Comment by vuule** [comment]
I should be able to look into this today. @mjsamoht, please assign to me.
