### ISSUE TITLE
[BUG] Parquet writes of a LIST of LISTS with a null validity crashes

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10536]
**Describe the bug**
If I try to write out an list of lists to parquet where all of the list values are null AND the validity buffers for the children are null, the parquet writing code throws an illegal memory access error. If those same validity buffers are allocated, but have a length of 0 everything is fine.

As a side note if you do a contiguous split on a table with 0 length child columns it will not bother to allocate validity buffers and make them null.

Here is some debugging output to print out the addressed of the data so you know what is there. DATA is the data buffer of the column and VAL is the validity buffer. 

The following data works... (it is what is returned by just reading in the file from parquet) 

GPU COLUMN 0 - NC: 3 DATA: null VAL: DeviceMemoryBufferView{address=0x302000e00, length=64, id=-1}
GPU COLUMN 0:DATA - NC: 0 DATA: null **VAL: DeviceMemoryBufferView{address=0x302001200, length=0, id=-1}**
GPU COLUMN 0:DATA:DATA - NC: 0 DATA: null VAL: null

But this one does not..
GPU COLUMN 0 - NC: 3 DATA: null VAL: DeviceMemoryBufferView{address=0x302000000, length=64, id=-1}
GPU COLUMN 0:DATA - NC: 0 DATA: null **VAL: null**
GPU COLUMN 0:DATA:DATA - NC: 0 DATA: null VAL: null

**Steps/Code to reproduce bug**

1) Unzip [data.zip](https://github.com/rapidsai/cudf/files/8375257/data.zip)
2) Read in the parquet file from the zip file
3) Do a contig split on the table that is returned.
4) try to write the result of the contig split table back out as parquet (using the chunked write API).

In java/scala we get an exception like...
```
ai.rapids.cudf.CudfException: CUDA error encountered at: ../include/cudf/detail/utilities/vector_factories.hpp:287: 700 cudaErrorIllegalAddress an illegal memory access was encountered
	at ai.rapids.cudf.Table.writeParquetChunk(Native Method)
```

If you need me to write a c++ test I can, but I really wanted to get this filed ASAP.

**Expected behavior**
No crash it works

**Comment by devavret** [comment]
I see it's not because of the presence of nullmask but the presence of offsets in the empty list level. It crashes when the data pointer of the second level list is null instead of a singular 0 value. I didn't know this was a valid, I thought a 0 sized list would have 0+1 sized offsets. I found now that it indeed is a [valid case](https://github.com/rapidsai/cudf/blob/ce385ce4244c19d37debdb51d9f5fe726d8665f3/cpp/src/lists/lists_column_factories.cu#L101-L103).

**Comment by revans2** [comment]
This is still needed and would really be great to get into the next release

**Comment by devavret** [comment]
@PointKernel Please hold off. I've been looking at this since before my leave. I didn't realise you just picked it.

**Comment by revans2** [comment]
I have a test for anyone who wants to use it.

```diff
diff --git a/cpp/tests/io/parquet_test.cpp b/cpp/tests/io/parquet_test.cpp
index 3905df2b27..1aeee53282 100644
--- a/cpp/tests/io/parquet_test.cpp
+++ b/cpp/tests/io/parquet_test.cpp
@@ -1506,6 +1506,34 @@ TEST_F(ParquetChunkedWriterTest, ListColumn)
   CUDF_TEST_EXPECT_TABLES_EQUAL(*result.tbl, *expected);
 }
 
+TEST_F(ParquetChunkedWriterTest, NullListOfList)
+{
+  auto all_null  = cudf::detail::make_counting_transform_iterator(0, [](auto i) { return true; });
+  auto level_0 = cudf::make_empty_column(cudf::data_type(cudf::type_id::INT32));
+
+  auto level_1_offsets = cudf::make_empty_column(cudf::data_type(cudf::type_id::INT32));
+  auto level_1 = cudf::make_lists_column(0, std::move(level_1_offsets), std::move(level_0), 0, rmm::device_buffer{});
+
+  cudf::test::fixed_width_column_wrapper<int32_t> level_2_offsets{0, 0, 0, 0};
+  rmm::device_buffer level_2_nullmask = cudf::test::detail::make_null_mask(all_null, all_null+3);
+  auto level_2 = cudf::make_lists_column(3, level_2_offsets.release(), std::move(level_1), 3, std::move(level_2_nullmask));
+
+  cudf::table_view tmp_table({level_2->view()});
+
+  cudf::test::print(level_2->view());
+
+  auto filepath = temp_env->get_temp_filepath("ChunkedNullListOfList.parquet");
+  cudf_io::chunked_parquet_writer_options args =
+    cudf_io::chunked_parquet_writer_options::builder(cudf_io::sink_info{filepath});
+  cudf_io::parquet_chunked_writer(args).write(tmp_table);
+
+  cudf_io::parquet_reader_options read_opts =
+    cudf_io::parquet_reader_options::builder(cudf_io::source_info{filepath});
+  auto result = cudf_io::read_parquet(read_opts);
+
+  CUDF_TEST_EXPECT_TABLES_EQUAL(*result.tbl, tmp_table);
+}
+
 TEST_F(ParquetChunkedWriterTest, ListOfStruct)
 {
   // Table 1
```
