### ISSUE TITLE
[FEA] Square Root via __array_ufunc__ protocol

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1055]
As a special case of https://github.com/rapidsai/cudf/issues/256 it would be useful to have a `sqrt` computation accessible from cudf on the Python side.  This would enable the computation of groupby-std (among other things).

Looking at instances of sqrt in the codebase today 

```
MROCKLIN-MLT:cudf mrocklin$ git grep sqrt
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_generic(gdf_column *input, gdf_column *output);
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output);
cpp/include/cudf/functions.h:gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output);
cpp/python/libgdf_cffi/tests/test_unaryops.py:def test_sqrt(dtype, ulp):
cpp/python/libgdf_cffi/tests/test_unaryops.py:    math_op_test(dtype, ulp, np.sqrt, libgdf.gdf_sqrt_generic,
cpp/src/unary/unary_ops.cu:        return std::sqrt(data);
cpp/src/unary/unary_ops.cu:DEF_UNARY_OP_REAL(gdf_sqrt)
cpp/src/unary/unary_ops.cu:gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output) {
cpp/src/unary/unary_ops.cu:gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output) {
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_generic(gdf_column *input, gdf_column *output)
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_f32(gdf_column *input, gdf_column *output)
python/cudf/bindings/cudf_cpp.pxd:    cdef gdf_error gdf_sqrt_f64(gdf_column *input, gdf_column *output)
python/cudf/dataframe/series.py:        return np.sqrt(self.var(ddof=ddof))
```

We see references to it in C++ side, a few references to bindings in the Cython side, but no use of it on the Python side as far as I can tell.  Oddly we *do* see `np.sqrt` used in the `Series.std` method, which I suspect converts to a numpy array?

**Comment by harrism** [comment]
This appears to be true of all unary ops. All the unary ops are implemented in C++ and have Cython bindings.  They are just not exposed via the Series interface in python.

**Comment by thomcom** [comment]
Is the syntax you require for this
```
import cudf as cd
gdf = cd.DataFrame({'x': [1, 2, 3]})
cd.sqrt(gdf)
```
?

**Comment by mrocklin** [comment]
Currently we use `np.sqrt(gdf)` or `np.sqrt(gdf.x)`

We could drop that down to `gdf ** 0.5` in dask-dataframe if desired.

Or, at some point, we should implement the `__array_ufunc__` protocol so that `np.sqrt(gdf)` calls `cudf.sqrt(gdf)` appropriately.  See https://github.com/rapidsai/cudf/issues/256

**Comment by thomcom** [comment]
For today, I can give you `gd.sqrt`

**Comment by mrocklin** [comment]
If it's ok, I'd like to leave this open until one of `np.sqrt(s)` or `s ** 0.5` work.  Those are what are necessary to get operations like groupby-std to work.

**Comment by thomcom** [comment]
Oh sorry, I thought `cudf.sqrt` would be adequate. I'll look at __array_ufunc__ now.
