### ISSUE TITLE
[FEA] Improvements to `cudf::cuda_error`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#10553]
**Is your feature request related to a problem? Please describe.**

Based on discussion in https://github.com/rapidsai/cudf/issues/10200#issuecomment-1081884311 there are a number of improvements we should make to the exceptions libcudf throws when a CUDA error occurs.

**Describe the solution you'd like**

1. Add a `cudaError_t` member to [`cudf::cuda_error`](https://github.com/rapidsai/cudf/blob/bc8f57843d2427ed07101faa86a40b162883d032/cpp/include/cudf/utilities/error.hpp#L32-L34) and corresponding `error_code()` function that returns the error code. 
2. Update `throw_cuda_error` to include the `cudaError_t` in the ctor of the `cudf::cuda_error`
3. Add a new `cudf::sticky_cuda_error` exception deriving from `cudf::cuda_error`
4. Update `throw_cuda_error` to detect and throw a sticky error, e.g.,
```
inline void throw_on_cuda_error(cudaError_t error, const char* file, unsigned int line)
   if(cudaSuccess != error){
       cudaGetLastError();                      // Clear any lingering cudart error
       auto const last = cudaGetLastError();    // Check if cudart error still exists (sticky)
       bool const is_sticky = (error == last) 
                              and (last == cudaDeviceSynchronize()); // Sync to ensure "last" wasnt an async error
       auto const msg = std::string{"CUDA error encountered at: " + std::string{file} + ":" +
                                     std::to_string(line) + ": " + std::to_string(error) + " " +
                                     cudaGetErrorName(error) + " " + cudaGetErrorString(error)};
       throw is_sticky ? sticky_cuda_error{"Sticky" + msg, error} : cudart_error{msg, error}; 
   }

#define CUDA_TRY(call)                                            \
  do {                                                            \
    cudaError_t const status = (call);                            \
    throw_on_cuda_error(status, __FILE__, __LINE__);
  } while (0)
```

**Comment by jrhemstad** [comment]
Despite the fact that "sticky error" is the term of art, perhaps `fatal_cuda_error` is a more intuitive/descriptive name than `sticky_cuda_error`.

**Comment by sperlingxx** [comment]
Hi @jrhemstad, is this feature under development ? Or, do we have a schedule on this issue ? Thanks.

**Comment by jrhemstad** [comment]
> Hi @jrhemstad, is this feature under development ? Or, do we have a schedule on this issue ? Thanks.

To the best of my knowledge, no one is planning to take this on yet, so feel free to do so!
