### ISSUE TITLE
[BUG] gdf_table gather_valid_mask and scatter_valid_mask assume destination is zeroed memory

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#1056]
**Describe the bug**
The gather_valid_mask and scatter_valid_mask kernels only copy the valid bit from the source if the bit is set.  This is only correct behavior if the destination memory is zeroed.  If the memory is not zeroed then the result of a valid mask scatter/gather could be a row entry being represented as valid when the original source row was not.

**Steps/Code to reproduce bug**
Gathering/scattering a valid mask with some nulls to a memory destination that is initialized to 0xFF for every byte should demonstrate the issue.  The resulting valid mask will have every bit set even though the original source mask did not.

**Expected behavior**
Valid vector bits being scattered or gathered should be copied to their respective destinations regardless of value.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of cuDF install: from source

**Comment by jrhemstad** [comment]
I believe this is fixed in https://github.com/rapidsai/cudf/pull/577
