### ISSUE TITLE
[DOC] Use of deprecated `as_gpu_matrix` and `fromDlpack` in 10min-cudf-cupy.ipynb

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/cudf#10582]
## Report incorrect documentation

**Location of incorrect documentation**
- https://github.com/rapidsai/cudf/blob/branch-22.06/docs/cudf/source/user_guide/10min-cudf-cupy.ipynb

**Describe the problems or issues found in the documentation**
We are still using deprecated CuPy function `fromDlpack` throughout this notebook, as well as `as_gpu_matrix` instead of `to_cupy`.

**Suggested fix for documentation**
Use the updated functions:

- `fromDlpack` -> `from_dlpack`
- `as_gpu_matrix` -> `to_cupy`

**Comment by galipremsagar** [comment]
Resolved by #10594
