### ISSUE TITLE
"count_digits" funtion performance optimization

### ISSUE THREAD

**Issue by lixiaolx** [rapidsai/cudf#10615]
**Is your feature request related to a problem? Please describe.**
When using count_digits to calculate the number of uint64, it is found that the performance of count_digits （https://github.com/rapidsai/cudf/blob/8d86ae88557053501535441518a17b4864cabcad/cpp/src/strings/convert/utilities.cuh#L98）is slow
**Describe the solution you'd like**
Use the following implementation to calculate the number of digits in uint64_t：
uint32_t ret = (uint32_t)__log10f(value) + 1;
In experiments called thousands of times，the overall kernel performance can be doubled (20ms down to 10ms)

**Comment by davidwendt** [comment]
Which API are you calling? I'm not seeing any improvement in our benchmarks for [`cudf::strings::to_integers()`](https://github.com/rapidsai/cudf/blob/branch-22.06/cpp/benchmarks/string/convert_numerics.cpp) when using `log10()`.

Can you provide some example code of what you are measuring including what data you are testing with?

**Comment by GregoryKimball** [comment]
Needs more information
