### ISSUE TITLE
[BUG] 10 minutes to cuDF and dask-cuDF notebook references missing data

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#10614]
**Describe the bug**
The `read_orc` section throw this error: ```FileNotFoundError: [Errno 2] No such file or directory: ['/rapids/cudf/python/cudf/cudf/tests/data/orc/TestOrcFile.test1.orc']```

**Steps/Code to reproduce bug**
Runt the notebook.

**Expected behavior**
Notebook should run.

**Comment by wence-** [comment]
This works when one has cloned the repository because in that case the file does exist (which is probably why we haven't noticed). I'll update the notebook to do the same as the other read/write options by writing first and then reading.
