### ISSUE TITLE
[BUG] 10 Minutes to cuDF and dask-cuDF uses deprecated Append method

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#10613]
**Describe the bug**
This notebook uses `append()` which is being deprecated and a warning is thrown. 

**Steps/Code to reproduce bug**
Run the notebook. 

**Expected behavior**
Code should be updated to change this section of the notebook to `concat`.

**Comment by galipremsagar** [comment]
This is being resolved in https://github.com/rapidsai/cudf/pull/10738
