### ISSUE TITLE
[BUG] Some cudf headers do not include `per_device_resource` when necessary.

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#10621]
Recently in Morpheus we encountered a bug where `get_current_device_resource` was undefined in a place we were not explicitly using it. Most public-facing libcudf APIs provide a `memory_resource*` as a default argument by calling `get_current_device_resource`, defined in `rmm/mr/per_device_resource.hpp`, however in some places this header is not included which requires the caller of libcudf APIs to include the header. If the header is not included by the caller, the symbol will remain undefined, leading to linker issues.

To fix the issue, public-facing libcudf APIs should IWYU, specifically `per_device_resource.hpp` in the case of calling `get_current_device_resource`. Likely this means adding an explicit `per_device_resource.hpp` import to all files matching the pattern `include/cudf/**/*.hpp`

**Comment by AtlantaPepsi** [comment]
Hi @cwharris , do you have any example where the linking breaks down because of this?
