### ISSUE TITLE
[FEA] Implement `cudf.get_dummies` utility function

### ISSUE THREAD

**Issue by paulhendricks** [rapidsai/cudf#1063]
**Is your feature request related to a problem? Please describe.**

Implement the `pd.get_dummies` utility function. Today, we have `cudf.dataframe.DataFrame.one_hot_encoding` which while similar provides lower level functionality.

The key difference between `cudf.dataframe.DataFrame.one_hot_encoding` and the proposed `cudf.get_dummies` is that the former is a method for `cudf.dataframe.DataFrame`; the latter is a module level utility function that takes as input a `cudf.dataframe.DataFrame` and a list of columns and returns a `cudf.dataframe.DataFrame` where all columns are one hot encoded.

**Describe the solution you'd like**

```python
def get_dummies(gdf, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None):
    output = cudf.dataframe.DataFrame()
    for column in columns:
        temp = gdf.one_hot_encoding(column)
        output = cudf.multi.concat([output, temp])
    return output
````

**Describe alternatives you've considered**

One can use a variation of the above Python solution. There may be more efficient implementations at the C/CUDA/Numba level that avoid needless memory copies.

**Additional context**

See here for cuDF API: https://rapidsai.github.io/projects/cudf/en/latest/api.html#cudf.dataframe.DataFrame.one_hot_encoding

See here for Pandas API: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.get_dummies.html

**Comment by beckernick** [comment]
This was not resolved by #1890 .

`get_dummies` is not yet a function accessible from the top-level module.
