### ISSUE TITLE
[BUG] libcudf should depend on Jitify2 branch, not custom fork

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#10654]
libcudf jitify2 source should be changed from our custom fork to a specific commit of the @NVIDIA/jitify jitify2 branch. Which commit should be used is in question.

https://github.com/rapidsai/cudf/blob/ce56bc3abad18943c972311305085843df7af36b/cpp/cmake/thirdparty/get_jitify.cmake#L21-L22

**Comment by cwharris** [comment]
This should wait until after jifity2 removes it's dependency on `libcuda.so`

**Comment by shwina** [comment]
We're currently blocked by the folllowing jitify2 issue: https://github.com/NVIDIA/jitify/issues/107

**Comment by shwina** [comment]
Closed in https://github.com/rapidsai/cudf/pull/11287
