### ISSUE TITLE
[DOC] gdf_filter requires better documentation

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#1067]
PR 541 is adding more Doxygen like documentation in the file functions.h
But more documentation is required for the function gdf_filter(). 
It should contain more detailed explanation of the functions semantics, expected use, etc.

Furthermore the comments above the function definition of gdf_filter in sqls_ops.cu is confusing.

**Comment by jrhemstad** [comment]
`gdf_filter` was removed by https://github.com/rapidsai/cudf/pull/1796
