### ISSUE TITLE
[FEA] Update Java bindings to handle separate nvcomp library

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#10681]
**Is your feature request related to a problem? Please describe.**
Currently the Java bindings statically link nvcomp into libcudf.so, but it is likely nvcomp will need to be a separate library (or possibly multiple libraries) with the nvcomp 2.3 release.  This will require updates to the Java bindings both in terms of what is packaged in the jar and what libraries are loaded by the NativeDepsLoader code.

**Describe the solution you'd like**
Ideally the build would support working with either the nvcomp 2.2 static-link-from-source-build or the prebuilt nvcomp 2.3 separate libraries.  NativeDepsLoader would need to check for optionally provided nvcomp libraries to load in order to support both the case where nvcomp libraries need to be loaded and when they do not.

**Comment by jbrennan333** [comment]
The changes in https://github.com/rapidsai/cudf/pull/10837 were pulled into https://github.com/rapidsai/cudf/pull/10851.
So this will be fixed by https://github.com/rapidsai/cudf/pull/10851.
