### ISSUE TITLE
[DOC] Conda package page for cudf has incorrect instructions

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#1069]
The rapidsai [anaconda page for cudf](https://anaconda.org/rapidsai/cudf) instructs users to ```conda install -c rapidsai cudf ```

This will fail with errors due to missing extra required channels.

The install command should be: ```conda install -c rapidsai -c conda-forge -c nvidia -c numba -c defaults cudf```

**Comment by kkraus14** [comment]
This is resolved.
