### ISSUE TITLE
[BUG] Series.apply does not retain the Series name

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#10715]
**Describe the bug**
Calling `cudf.Series.apply` should retain the Series name to align with `pandas.Series.apply` behavior. The previous behavior of `cudf.Series.applymap` (deprecated in favor of `cudf.Series.apply`) correctly retains the Series name.

**Steps/Code to reproduce bug**
```python
import pandas as pd
import cudf

ps = pd.Series(range(10), name="awesome_numbers")
result = ps.apply(lambda x: x + 42)
print(result.name)  # awesome_numbers

gs = cudf.from_pandas(ps)
result = gs.apply(lambda x: x + 42)
print(result.name)  # None

gs = cudf.from_pandas(ps)
result = gs.applymap(lambda x: x + 42)  # FutureWarning: Series.applymap is deprecated [...]
print(result.name)  # awesome_numbers
```

**Expected behavior**
`name` should be retained.

**Comment by vyasr** [comment]
When this issue is fixed I suppose we should also remove https://github.com/rapidsai/cudf/pull/10685/files#r856370814.

**Comment by bdice** [comment]
> When this issue is fixed I suppose we should also remove https://github.com/rapidsai/cudf/pull/10685/files#r856370814.

I have a follow-up PR planned once PRs #10716 and #10685 are merged.
