### ISSUE TITLE
[BUG] No-log script crash when running ./build.sh

### ISSUE THREAD

**Issue by thehemen** [rapidsai/cudf#10719]
**Describe the bug**
When running ./build.sh, script just exits (with GNOME terminal closed) with the last command:

> [ 83%] Building CUDA object CMakeFiles/cudf.dir/src/sort/stable_sort_column.cu.o.

**Steps to reproduce bug**
I run ./build.sh with S3 disabled and Thrust version 1.16.0 to prevent other errors. However, it just changes the actual progress to 83%.

**Expected behavior**
cuDF library should be built (libcudf, cudf and dask_cudf). 

**Environment overview**
 - Environment location: Bare-metal (Ubuntu 22.04).
 - Method of cuDF install: from source.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 5264f95bc12dc705635abcf479c6117eefec278c (HEAD -> branch-22.06, origin/branch-22.06, origin/HEAD)
     Author: David Wendt <45795991+davidwendt@users.noreply.github.com>
     Date:   Fri Apr 22 20:27:18 2022 -0400
     
     Fix rounding to zero error in stod on very small float numbers (#10672)
     
     Fixes a rounding error on extremely small floating-point numbers in the range `1E-287 - 1E-307`. These values were incorrectly being rounded to zero due to the fix in #10622. The extra float operation removed in #10622 is necessary for values in this range to keep them from being converted to zero.
     
     The fix adds a check so the extra floating point operation is only used when the overall exponent falls below `std::numeric_limits<double>::min_exponent10` (which is `-307`). The `ToFloat64` gtest was also updated to include value in this range to ensure this error does not occur again.
     
     Additionally, the conversion now supports subnormal numbers that are very very small in the range of E-307 and E-324.
     
     Authors:
     - David Wendt (https://github.com/davidwendt)
     
     Approvers:
     - Bradley Dice (https://github.com/bdice)
     - Yunsong Wang (https://github.com/PointKernel)
     - Mike Wilson (https://github.com/hyperbolic2346)
     
     URL: https://github.com/rapidsai/cudf/pull/10672
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=22.04
     DISTRIB_CODENAME=jammy
     DISTRIB_DESCRIPTION="Ubuntu 22.04 LTS"
     PRETTY_NAME="Ubuntu 22.04 LTS"
     NAME="Ubuntu"
     VERSION_ID="22.04"
     VERSION="22.04 (Jammy Jellyfish)"
     VERSION_CODENAME=jammy
     ID=ubuntu
     ID_LIKE=debian
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     UBUNTU_CODENAME=jammy
     Linux thehemen-H110M-H 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Sun Apr 24 00:32:43 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 510.60.02    Driver Version: 510.60.02    CUDA Version: 11.6     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
     |  0%   49C    P0    N/A /  72W |    265MiB /  4096MiB |      2%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A      1432      G   /usr/lib/xorg/Xorg                171MiB |
     |    0   N/A  N/A      1610      G   ...ome-remote-desktop-daemon        1MiB |
     |    0   N/A  N/A      1651      G   /usr/bin/gnome-shell               38MiB |
     |    0   N/A  N/A     68683      G   ...859041524729586485,131072       50MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Архитектура:                     x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Address sizes:                   39 bits physical, 48 bits virtual
     Порядок байт:                    Little Endian
     CPU(s):                          4
     On-line CPU(s) list:             0-3
     ID прроизводителя:               GenuineIntel
     Имя модели:                      Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
     Семейство ЦПУ:                   6
     Модель:                          158
     Потоков на ядро:                 1
     Ядер на сокет:                   4
     Сокетов:                         1
     Степпинг:                        9
     CPU max MHz:                     3500,0000
     CPU min MHz:                     800,0000
     BogoMIPS:                        6000.00
     Флаги:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
     Виртуализация:                   VT-x
     L1d cache:                       128 KiB (4 instances)
     L1i cache:                       128 KiB (4 instances)
     L2 cache:                        1 MiB (4 instances)
     L3 cache:                        6 MiB (1 instance)
     NUMA node(s):                    1
     NUMA node0 CPU(s):               0-3
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
     Vulnerability Srbds:             Mitigation; Microcode
     Vulnerability Tsx async abort:   Not affected
     
     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.23.1
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 11.2.0-19ubuntu1) 11.2.0
     Copyright (C) 2021 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-11.6/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2022 NVIDIA Corporation
     Built on Tue_Mar__8_18:18:20_PST_2022
     Cuda compilation tools, release 11.6, V11.6.124
     Build cuda_11.6.r11.6/compiler.31057947_0
     
     ***Python***
     
     ***Environment Variables***
     PATH                            : /usr/local/cuda-11.6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-11.6/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     conda not found
     ***pip packages***
     /usr/bin/pip
     Package                      Version
     ---------------------------- -------------------
     absl-py                      1.0.0
     apturl                       0.5.2
     astunparse                   1.6.3
     bcrypt                       3.2.0
     blinker                      1.4
     Brlapi                       0.8.3
     cachetools                   5.0.0
     certifi                      2020.6.20
     chardet                      4.0.0
     chrome-gnome-shell           0.0.0
     click                        8.0.3
     colorama                     0.4.4
     command-not-found            0.3
     cryptography                 3.4.8
     cupshelpers                  1.0
     cycler                       0.11.0
     dbus-python                  1.2.18
     defer                        1.0.6
     distro                       1.7.0
     distro-info                  1.1build1
     duplicity                    0.8.21
     fasteners                    0.14.1
     flatbuffers                  2.0
     fonttools                    4.33.1
     future                       0.18.2
     gast                         0.5.3
     google-auth                  2.6.6
     google-auth-oauthlib         0.4.6
     google-pasta                 0.2.0
     grpcio                       1.44.0
     h5py                         3.6.0
     httplib2                     0.20.2
     idna                         3.3
     importlib-metadata           4.6.4
     jeepney                      0.7.1
     joblib                       1.1.0
     keras                        2.8.0
     Keras-Preprocessing          1.1.2
     keyring                      23.5.0
     kiwisolver                   1.4.2
     language-selector            0.1
     launchpadlib                 1.10.16
     lazr.restfulclient           0.14.4
     lazr.uri                     1.0.6
     libclang                     13.0.0
     lockfile                     0.12.2
     louis                        3.20.0
     macaroonbakery               1.3.1
     Mako                         1.1.3
     Markdown                     3.3.6
     MarkupSafe                   2.0.1
     matplotlib                   3.5.1
     monotonic                    1.6
     more-itertools               8.10.0
     netifaces                    0.11.0
     numpy                        1.22.3
     oauthlib                     3.2.0
     olefile                      0.46
     opt-einsum                   3.3.0
     packaging                    21.3
     pandas                       1.4.2
     paramiko                     2.9.3
     pexpect                      4.8.0
     Pillow                       9.0.1
     pip                          22.0.2
     protobuf                     3.12.4
     ptyprocess                   0.7.0
     pyasn1                       0.4.8
     pyasn1-modules               0.2.8
     pycairo                      1.20.1
     pycups                       2.0.1
     PyGObject                    3.42.0
     PyJWT                        2.3.0
     pymacaroons                  0.13.0
     PyNaCl                       1.5.0
     pyparsing                    2.4.7
     pyRFC3339                    1.1
     python-apt                   2.3.0+ubuntu2
     python-dateutil              2.8.1
     python-debian                0.1.43ubuntu1
     pytz                         2022.1
     pyxdg                        0.27
     PyYAML                       5.4.1
     reportlab                    3.6.8
     requests                     2.25.1
     requests-oauthlib            1.3.1
     rsa                          4.8
     scikit-learn                 1.0.2
     scipy                        1.8.0
     screen-resolution-extra      0.0.0
     SecretStorage                3.3.1
     setuptools                   59.6.0
     six                          1.16.0
     systemd-python               234
     tensorboard                  2.8.0
     tensorboard-data-server      0.6.1
     tensorboard-plugin-wit       1.8.1
     tensorflow                   2.8.0
     tensorflow-io-gcs-filesystem 0.25.0
     termcolor                    1.1.0
     tf-estimator-nightly         2.8.0.dev2021122109
     threadpoolctl                3.1.0
     torch                        1.11.0+cu115
     torchaudio                   0.11.0+cu115
     torchvision                  0.12.0+cu115
     typing_extensions            4.2.0
     ubuntu-advantage-tools       27.7
     ubuntu-drivers-common        0.0.0
     ufw                          0.36.1
     unattended-upgrades          0.1
     urllib3                      1.26.5
     usb-creator                  0.3.7
     wadllib                      1.3.6
     Werkzeug                     2.1.1
     wheel                        0.37.1
     wrapt                        1.14.0
     xdg                          5
     xkit                         0.0.0
     zipp                         1.0.0
     
</pre></details>

**Additional context**

**Comment by vyasr** [comment]
@thehemen apologies for missing this earlier. Were you able to resolve the problem here?

**Comment by bdice** [comment]
@thehemen It is possible that this crashed because your system did not have enough RAM to compile libcudf -- I am guessing that from the GPU and CPU specs, you probably have less than 16 GB installed. Building libcudf from source is memory intensive. The minimum RAM requirements for compiling were substantially lessened after PR #10756, which might have fixed the underlying issue here. However, you may need to build in serial (`-j 1`) if your system is low on memory. If possible, try to use pre-built conda packages or Docker containers to avoid building libcudf from source.

**Comment by thehemen** [comment]
@vyasr As I remember, no.
Doing the same task now, I've replaced some pandas functions with its numpy alternatives to accelerate it a bit.

**Comment by vyasr** [comment]
I agree with @bdice, memory requirements are the most likely culprit. Is building from source a requirement for your use case, though, or could you use the pre-built packages instead? That would be the far simpler approach if nothing stops you.

**Comment by davidwendt** [comment]
What do mean when you say you build with _Thrust version 1.16.0_ ? Curious because you mentioned the build stopping in the middle of compiling `stable_sort_column.cu`. The libcudf build includes a patched thrust version specifically for sort. (Perhaps another reason not try to build libcudf from source).

**Comment by thehemen** [comment]
@bdice That's explains a lot. My system has just 8 GB RAM.
@vyasr Yes, most likely, using pre-built packages is the best option. Thanks!
davidwendt May be. There was another error with the original Thrust

**Comment by vyasr** [comment]
@thehemen did you intentionally close and reopen? I think we can probably leave this closed for now and reopen if and when you try to rebuild, unless you intend to try that soon in which case I'm interested to see what you find!
