### ISSUE TITLE
[FEA] Provide a generic "dictionary" column type 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1072]
**Is your feature request related to a problem? Please describe.**

Currently in libcudf we have the `GDF_CATEGORY` type, which is a column of `int32_t` elements that hold the mapping of some other column of elements into a 32-bit hash value representation. See Pandas Categorical type: https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html

However, a 32-bit representation may be unnecessary for many use-cases as the number of unique values may be much less than `2^31-1` and it would be more space efficient to store it in a smaller type.

Furthermore, https://github.com/rapidsai/cudf/pull/872 is adding support for Strings in libcudf via the `NVCategory` class. 

`NVCategory` is similar to a Categorical column that boils down to two things:

1. A "dictionary" of the unique strings in a column
2. A list of indices that index into the dictionary

For example:
```
strings : { "apple", "apple", "banana", "grape"}
dictionary : { "apple", "banana", "grape"}
indices : { 0, 0, 1, 2 }
```
(note that the dictionary is ordered. This is important such that the indices are order-preserving) 

In this way, we can do most (all?) operations in libcudf on columns of strings via operations on the `indices` of NVCategory, e.g., sort, join, groupby, etc.

**Problem** There should be a more generic concept of a "dictionary" column in libcudf that can satisfy the current requirements of `GDF_CATEGORY` and `NVCategory` and provide additional features. 

**Describe the solution you'd like**

We should design a better "dictionary" column abstraction that has two things:

1. A list of indices (these can be any type: `int8` through `int64` depending on what's needed)
2. The "thing" you're indexing into (call it a "dictionary" for simplicity)

**Additional context**

We could design features and algorithms in cuDF/libcudf around this generic "dictionary" column abstraction that can support the existing functionality of `NVCategory` and `GDF_CATEGORY`, but allow us to keep our algorithms generic _as well as_ provide entirely new functionality:

- Imagine you have a column of `int64` values a small number of unique values. You could get an 8x performance improvement by representing that column as a "dictionary" column with `int8` indices. 
- The "dictionary" could just be another column, and you could chain an arbitrary number of these "indices-into-another-column"-columns together to do things like delayed materialization of results from a sort or a join or a gather/scatter.

**Comment by felipeblazing** [comment]
A way of knowing if the indices are sorted or not. E.G, can they be used for inequality comparisions in addition to equality comparisons would be interesting.

**Comment by jrhemstad** [comment]
> A way of knowing if the indices are sorted or not. E.G, can they be used for inequality comparisions in addition to equality comparisons would be interesting.

I was thinking we'd make it a requirement that the dictionary/indices are _always_ order-preserving, but that may be too limiting.

**Comment by felipeblazing** [comment]
There are many situations where you moight not care. For example if you juse this for a hash based join you would not care since after you materialize you throw that crap away.

**Comment by kkraus14** [comment]
> I was thinking we'd make it a requirement that the dictionary/indices are _always_ order-preserving, but that may be too limiting.

On the Python side in our current categorical implementation we have a struct option to indicate whether the dictionary is ordered or not for this very reason.

**Comment by jrhemstad** [comment]
> On the Python side in our current categorical implementation we have a struct option to indicate whether the dictionary is ordered or not for this very reason.

Yeah, after a little more thought, it makes a lot more sense to allow it to be ordered/un-ordered depending on the need.

**Comment by felipeblazing** [comment]
In general Dictionaries would provide us with many optimization avenues when they exist. From filtering to allowing things like null substitution by just modifying the dictionary. The real magic starts happening when we leverage these dictionaries to make things more efficient.

**Comment by jrhemstad** [comment]
Closing this as it is superseded by https://github.com/rapidsai/cudf/issues/3535
