### ISSUE TITLE
[DOC] Provide API documentation for historical releases

### ISSUE THREAD

**Issue by csaimd** [rapidsai/cudf#10723]
how to find previous docs， the link below  only read the 22.04 version, i want to read the older version 0.14.0, 
What should I do？
https://docs.rapids.ai/api/cudf/stable/

**Comment by beckernick** [comment]
I believe we currently provide the prior release (legacy), current stable release, and nightly documentation on docs.rapids.ai. You may be able to clone the repository, checkout your desired branch, and build the documentation locally.

I'll convert this to a feature request for providing documentation of historical releases, [like PyTorch](https://pytorch.org/docs/versions.html)

**Comment by vyasr** [comment]
This is being worked on RAPIDS-wide in https://github.com/rapidsai/rapids.ai/pull/358. No ETA, but since this is a RAPIDS-wide docs effort let's track it there.
