### ISSUE TITLE
[FEA] Parquet support for reading binary and repeated binary

### ISSUE THREAD

**Issue by tgravescs** [rapidsai/cudf#10733]
**Is your feature request related to a problem? Please describe.**
We have a customer that is using parquet files written by a system other than Spark that is writing Strings to parquet files and using the schema type of binary and repeated binary.  In the past various other big data projects wrote strings this way as well.

Example of the parquet schema for a similar parquet file:
```
Schema:
message test {
  optional binary x;
  optional int32 y;
  optional int32 z;
  repeated binary net;
  optional binary locale;
}
```
Note that in some cases cudf seems to be able to read these but then in others it fails.  I'll attach 2 parquet files, goodbinary.parquet and badbinary.parquet where the only difference between good and bad is that the goodbinary.parquet drops the last column from schema above `optional binary locale` and the badbinary.parquet has all columns above.

binary is a list of bytes `[77 74 74]` when read as string `wtt`

**Describe the solution you'd like**
Regardless of it seems to sometimes work, we would like cudf to officially support reading these binary and repeated binary types.  Ideally we could support reading binary both as binary and as strings.  We could pass in a read schema so the reader would know what to read it is.

**Comment by tgravescs** [comment]
[binaryparquet.zip](https://github.com/rapidsai/cudf/files/8558278/binaryparquet.zip)

This zip file contains the 2 parquet files described above

**Comment by nvdbaranec** [comment]
This turns out to be a simple bug in the reader.  Working on it.

**Comment by nvdbaranec** [comment]
Closed with:  https://github.com/rapidsai/cudf/pull/10750
