### ISSUE TITLE
[FEA] cudf::lists::contains to support NaN == NaN

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10741]
**Is your feature request related to a problem? Please describe.**
In an attempt to make things simpler for users out of the box the Spark plugin would like to get rid of all of the NaN incompatibility so users don't have to opt into some operations when they know that there are no NaNs. list_contains is one place where we have problems with NaN. cudf does not believe that NaN == NaN, which if correct for C++, but not for Spark in this corner case.

**Describe the solution you'd like**
I would like to have lists::contains versions or a flag that lats us say if NaNs are equal or not.

**Describe alternatives you've considered**
In this specific case we could work around this by doing other operations like expanding the search column to match the data column of the list, and then doing our own equality checks followed by a segmented reduction. But there are other similar operators that we are asking for https://github.com/rapidsai/cudf/issues/10409 with no simple work around, so I would rather have us come to some understanding/president about how to make these types of operations work properly so we don't have to keep hacking around things.

**Comment by ttnghia** [comment]
This issue is not new. There are many places that we want to support comparison `NaN == NaN` or `NaN != NaN`. And all these cascade down to the row equality comparators.
Previously, in `lists::drop_list_duplicates`, NaN handling was supported locally. As more and more request for NaN handling like this, a more generic foundation should be implemented at the bottom level (row equality comparators) then the high level APIs can just pass down the NaN comparision parameter.

**Comment by ttnghia** [comment]
I filed a corresponding cudf issue for that dependency: https://github.com/rapidsai/cudf/issues/10781

**Comment by jrhemstad** [comment]
> This issue is not new.

I'd go so far as to say that this issue is [_old_ ](https://github.com/rapidsai/cudf/issues/4760) :)

**Comment by mythrocks** [comment]
> cudf does not believe that NaN == NaN, which if correct for C++, but not for Spark in this corner case.

Does [`cudf::detail::equality_compare()`](https://github.com/rapidsai/cudf/blob/branch-22.06/cpp/include/cudf/table/row_operators.cuh#L146) not currently do what Spark requires? 
```c++
template <typename Element, std::enable_if_t<std::is_floating_point_v<Element>>* = nullptr>
__device__ bool equality_compare(Element lhs, Element rhs)
{
  if (isnan(lhs) and isnan(rhs)) { return true; } // <------ NaN == NaN.
  return lhs == rhs;
}
```

Maybe I've not grokked what the issue for Spark might be here.

**Comment by ttnghia** [comment]
No. `equality_compare` produces `if (isnan(lhs) and isnan(rhs)) { return true; }`, which is the desired result, only if you explicitly call it. Otherwise, most APIs just call `lhs == rhs` internally.

**Comment by mythrocks** [comment]
> Not to mention that some other times the desired result would be NaN != NaN.

This isn't in dispute. I agree with the sentiment that this should be configurable.

> ...which is the desired result in this issue, only if you explicitly call it.

@revans2's report here refers to `lists::contains()` *not* doing `NaN == Nan` as Spark requires. But here's the [`lists::contains()` comparison code](https://github.com/rapidsai/cudf/blob/branch-22.06/cpp/src/lists/contains.cu#L112):
```c++
  auto const find_iter  = thrust::find_if(
      thrust::seq, list_begin, list_end, [search_key] __device__(auto element_and_validity) {
        auto [element, element_is_valid] = element_and_validity;
        return element_is_valid && cudf::equality_compare(element, search_key); // <-- Explicitly called!
      });
```
Given this implementation, I'm not sure how this isn't producing the result that Spark desires. :/

**Comment by revans2** [comment]
@mythrocks thanks for checking me. I thought I had tested this before filing it, but it sure looks like I was wrong.

```
+--------------+-----+----------------------+
|_1            |_2   |array_contains(_1, _2)|
+--------------+-----+----------------------+
|[100.0, NaN]  |100.0|true                  |
|[100.0, NaN]  |NaN  |true                  |
|[100.0, 200.0]|NaN  |false                 |
|[100.0, NaN]  |200.0|false                 |
+--------------+-----+----------------------+
```

This works.
