### ISSUE TITLE
Analyze performance of new row hasher

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#10743]
The new row hasher introduced in #10641 needs its performance analyzed further to identify if there is any low-hanging fruit available for further optimization. In particular, as requested in [this thread](https://github.com/rapidsai/cudf/pull/10641#discussion_r850773710) it may be possible to improve performance by considering how the compiler is treating the type dispatcher inside the hasher.

**Comment by devavret** [comment]
Actually Jake and I did spend some time exploring the code with the toolkit tools. We didn't get anything concrete but the hunch is that the amount of generated code is more when pulling out the type dispatcher.

**Comment by jrhemstad** [comment]
For reference, I recall that there was nearly 2x more SASS generated by pulling the type dispatch out of the loop. This was very surprising and Devavret and I tried many things like additional force includes and constifying things without much success.

**Comment by vyasr** [comment]
If there are no obvious actionables here perhaps we should just close this issue and reopen it in the future if someone is looking for avenues to optimize these algorithms?

**Comment by bdice** [comment]
I just asked a related question [here](https://github.com/rapidsai/cudf/pull/10641#discussion_r861267744) and was pointed to this issue. We'll need to do some profiling and optimization to avoid performance regressions, but we probably do not have anything specific to document as of yet.

**Comment by vyasr** [comment]
I'm not sure that regressions are a concern here, we already have benchmarks to check for that. This issue is basically about investigating potential future optimizations (and based on what Devavret and Jake found perhaps there aren't any, at least not related to type dispatch).

**Comment by GregoryKimball** [comment]
I'll close this for now. If we see performance issues when using the new row hasher, we will start a new investigation.
