### ISSUE TITLE
[QST] Is cudf installation available for CUDA 11.6?

### ISSUE THREAD

**Issue by josenafria** [rapidsai/cudf#10757]
HI!
I have been trying all the possible installation method for my AWS Machine with a Nvidia Tesla T4, nvidia driver 510.47.03 and CUDA version 11.6 and it is impossible.
Cuda 11.6 was released on January 2022, do you have any plans to make your package available for the last stable version of nvida CUDA?
Thank you in advance.

**Comment by quasiben** [comment]
The following worked for me:

> mamba create -n env11.6 rapids=22.04 cudatoolkit=11.6 -c rapidsai -c nvidia -c conda-forge

What issues are you seeing ?  
@bdice I recall you working in an 11.6 machine some time ago, correct ?

**Comment by bdice** [comment]
I am able to build and run with CUDA 11.6, yes. I am using a container based on `nvidia/cuda:11.6.0-devel-ubuntu20.04`.

**Comment by josenafria** [comment]
Thank you both for the quick answers! @bdice @quasiben 

About the container installation, I am not really familiar with docker but I will try and let you know which is the outcome. What I find weird is that on the official webpage there is no option for cuda 11.6 (cuda 11.5 looks like the latest version on the installation picker)

![image](https://user-images.githubusercontent.com/66060238/166419758-e1cc57b2-25a4-4014-9564-15c04e43801d.png)

**Comment by bdice** [comment]
@josenafria We don’t provide builds for 11.6 yet, but the Docker images and conda packages are forwards compatible with newer drivers and system toolkit versions. If your system has CUDA 11.6, I would recommend using the CUDA 11.5 containers or conda packages. If you have any issues, please copy the errors / traceback here and we’ll take a look!

Hope that helps! 😊

**Comment by bdice** [comment]
Closing as resolved.
