### ISSUE TITLE
[FEA] Add Thrust as sub-module

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1077]
**Is your feature request related to a problem? Please describe.**

Currently we rely on Thrust being installed in a user's CUDA tool-kit. Given our minimum supported version is CUDA 9.2, we cannot use the many new features from Thrust 10.1.

**Describe the solution you'd like**
Now that Thrust on GitHub is in-sync with what is released in the toolkit, we should add Thrust as a sub-module of cuDF such that we can use the latest version of Thrust from GitHub. 

https://github.com/thrust/thrust

**Comment by harrism** [comment]
Concern was that the latest Thrust is only tested with the latest CUDA toolkit, and we have to support older CUDA toolkits. However, @jrhemstad and I discussed and since libcudf CI tests our usage of Thrust with the CUDA Toolkits we support, the risk should be low. So we should go ahead with this in 0.11.

**Comment by devavret** [comment]
Given the discussion here https://github.com/rapidsai/cudf/issues/2631#issuecomment-616582519, it seems the plan is to add thrust to RMM. Should this issue then be moved to RMM?

**Comment by harrism** [comment]
We're going to wait on doing this until we really need it. @jrhemstad will be working on an uninitialized vector for RMM which should cover most uses of device_vector in cuDF, and may mean we don't need the latest Thrust as a submodule in cuDF or RMM.  Moving out of 0.14.

**Comment by harrism** [comment]
On second thought, I'm closing this. We can reopen it if we really need it.
