### ISSUE TITLE
The environment is inconsistent,

### ISSUE THREAD

**Issue by mathshangw** [rapidsai/cudf#10786]
i'm stuck on this problem while installing cudf 
```
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::glib-tools==2.68.3=h9c3ff4c_0
  - conda-forge/linux-64::lxml==4.6.3=py37h77fd288_0
  - conda-forge/linux-64::boost-cpp==1.74.0=hc6e9bd1_3
  - conda-forge/linux-64::pyqtchart==5.12=py37he336c9b_7
  - defaults/noarch::typing-extensions==3.10.0.0=hd3eb1b0_0
  - defaults/linux-64::jupyter==1.0.0=py37_7
  - conda-forge/linux-64::libglib==2.68.3=h3e27bee_0
  - conda-forge/linux-64::libxslt==1.1.33=h15afd5d_2
  - conda-forge/linux-64::pyqt-impl==5.12.3=py37he336c9b_7
  - conda-forge/linux-64::harfbuzz==2.8.1=h83ec7ef_0
  - defaults/noarch::jupyter_console==6.4.0=pyhd3eb1b0_0
  - defaults/noarch::pyls-spyder==0.3.2=pyhd3eb1b0_0
  - conda-forge/linux-64::pyqtwebengine==5.12.1=py37he336c9b_7
  - defaults/linux-64::pylint==2.9.1=py37h06a4308_1
  - defaults/linux-64::astroid==2.6.2=py37h06a4308_0
  - defaults/noarch::pyls-black==0.4.6=hd3eb1b0_0
  - defaults/linux-64::spyder==4.2.1=py37h06a4308_1
  - defaults/noarch::prompt_toolkit==3.0.17=hd3eb1b0_0
  - defaults/noarch::python-language-server==0.36.2=pyhd3eb1b0_0
  - defaults/linux-64::pango==1.45.3=hd140c19_0

```

the command i used is `
conda install -c rapidsai -c nvidia -c numba -c conda-forge     cudf=21.08 python=3.7 cudatoolkit=11.0`

**Comment by shwina** [comment]
Hi @mathshangw, are you attempting to install into an existing environment? It sounds like there may be package(s) in that environment that are incompatible with cuDF.

Can you perhaps run `conda list` and provide the output?

**Comment by galipremsagar** [comment]
> Hi @mathshangw, are you attempting to install into an existing environment? It sounds like there may be package(s) in that environment that are incompatible with cuDF.
> 
> Can you perhaps run `conda list` and provide the output?

In addition to this, can you also try using `mamba install` which will give us a clearer picture of the inconsistency:
```
mamba install -c rapidsai -c nvidia -c numba -c conda-forge cudf=21.08 python=3.7 cudatoolkit=11.0
```

**Comment by vyasr** [comment]
@mathshangw were you able to resolve this issue?

**Comment by vyasr** [comment]
I'm going to close this issue for now, but feel free to reopen if needed.
