### ISSUE TITLE
[BUG] `__eq__` and `__hash__` methods on many dtypes don't obey python data model requirements

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#10789]
When implementing dunder methods for equality and hash on objects, the Python language data model has [this to say](https://docs.python.org/3/reference/datamodel.html#object.__hash__):

> The `__hash__()` method should return an integer. _The only required property is that objects which compare equal have the same hash value;_ [...]

A number of the data types in cudf don't obey this prescription (since they allow some comparisons
```python
import cudf, numpy

dt1 = cudf.IntervalDtype(numpy.float32)
dt2 = cudf.IntervalDtype(numpy.float64)

print(dt1 == dt2) # => False
print(dt1 == "interval") # => True
print(dt2 == "interval") # => True (so equality is not transitive either since dt1 == A and dt2 == A !=> dt1 == dt2)
print(hash(dt1) == hash(dt2)) # => False
print(hash(dt1) == hash("interval")) # => False (doesn't match the required property above)
print(hash(dt2) == hash("interval")) # => False
```

It looks like cudf mimics pandas here, so arguably it's also a bug there, and perhaps this is just something to live with?

**Comment by shwina** [comment]
Yeah unfortunately, it's common to do checks like `s.dtype == "category"`. FWIW NumPy does this too with its dtypes:

```python
In [6]: np.dtype("int32") == "int32"
Out[6]: True
```
