### ISSUE TITLE
[FEA] Story - Supporting Approximate Count Distinct

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#10792]
This issue tracks the dependencies for supporting approximate count distinct using [HyperLogLog](https://www.wikiwand.com/en/HyperLogLog) algorithm.

 * Design doc (WIP): https://docs.google.com/document/d/1ezAXhH7GejuaNDvIyqMBYfmsSypcDWinl2_tmLJd-O4

**Comment by jrhemstad** [comment]
Given there was already sizable discussion in https://github.com/rapidsai/cudf/issues/10652, can we just use that issue? Or is there a different intent with this one?

**Comment by ttnghia** [comment]
That issue has been diluted.
Here I'm going to add checked list item for the necessary PRs/features we are going to add so people can keep track, like this: https://github.com/rapidsai/cudf/issues/10186.

**Comment by revans2** [comment]
This is still wanted

**Comment by GregoryKimball** [comment]
@etseidl FYI, our friends in Spark-RAPIDS are also interested in the HyperLogLog algorithm. 😄

**Comment by GregoryKimball** [comment]
Also see https://github.com/NVIDIA/cuCollections/pull/429

**Comment by vyasr** [comment]
Echoing Jake's question from two years ago: do we need this issue? Can we consolidate discussion in #10652? At this point it seems like we're just forced to post updates in two places. @ttnghia WDYT?

**Comment by res-life** [comment]
I'm working on this.

**Comment by vyasr** [comment]
To avoid fragmentation, I'm going to close this as a dup of #10652 so that we can focus discussion there.
