### ISSUE TITLE
[FEA] support lists::concatenate_rows for structs and lists

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10800]
**Is your feature request related to a problem? Please describe.**
We have a customer that really would like to be able to concatenate lists row by row, but the data types gets rather complicated. It includes lists and structs multiple levels deep.

```
val schema_a = StructType(Seq(
	StructField("a_d", DoubleType),
	StructField("a_s", StringType)))

val schema_b = ArrayType( StructType(Seq(
	StructField("b_a_1", ArrayType(schema_a)),
	StructField("b_a_2", ArrayType(schema_a)),
	StructField("b_l", LongType),
	StructField("b_s_1", StringType),
	StructField("b_s_2", StringType),
	StructField("b_s_3", StringType),
	StructField("b_a_s", ArrayType(StringType)))))
```

**Describe the solution you'd like**
I would love it if `lists::concatenate_rows` would work for me instead of throwing an exception saying that this is not going to work.

**Describe alternatives you've considered**
If it was just structs I might be able to hack something together myself, but I don't think this is really possible for me to do without some help.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by nvdbaranec** [comment]
Done.
