### ISSUE TITLE
[FEA] Host Doxygen HTML 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1081]
**Is your feature request related to a problem? Please describe.**
The libcudf Doxygen documentation HTML page should be accessible without requiring someone to clone the repo and build with `make doc`. 

**Describe the solution you'd like**
Doxygen HTML should be hosted and accessible via github or dev docs page.

Depends on https://github.com/rapidsai/cudf/pull/823

**Comment by harrism** [comment]
Doxygen HTML is here: https://docs.rapids.ai/api/libcudf/stable/
