### ISSUE TITLE
[FEA] Support `maps_column_view::contains()` with keys specified in a column

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#10819]
Currently, `maps_column_view::contains()` checks whether a specified key scalar value is present in each row of a "maps" column (i.e. `LIST<STRUCT<key, value>>`). This function does not currently support a key vector.

It would be good to add support to `contains()` for keys specified as a column. This will allow expression results to serve as map keys.

Additionally, a corresponding overload of `ColumnView::mapContains()` needs to be added in the JNI layer.

**Comment by revans2** [comment]
This is still wanted

**Comment by mythrocks** [comment]
This was resolved as part of #11128. The PR should really have linked this issue.

Closing this now.
