### ISSUE TITLE
[QST] pip build for cuda 10.1

### ISSUE THREAD

**Issue by svelts** [rapidsai/cudf#1082]
Just two questions:
1) is cuDF compatible with CUDA 10.1 already?
2) what are the plans to build and publish corresponding pip packages?
Just installed CUDA 10.1 and tried to use cudf-cuda100 and it does not work because of libcudart100.so is missing. 
It will be nice to know if it's better to build from source or  wait for a pip package. Thanks.

**Comment by kkraus14** [comment]
Hi @svelts, we are planning on testing and bug squashing CUDA 10.1 related issues over the next few days before releasing 0.6. If you could try to build from source and report any issues you run into that would be extremely helpful!

**Comment by kkraus14** [comment]
No longer supporting pip for the time being, closing this.
