### ISSUE TITLE
[BUG] Read_csv ignores last line if it does not include an endline

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1083]
**Describe the bug**

cudf.read_csv can ignore the last line if it does not include an endline.  My guess is that this comes from the byte range work.  My guess is that it should also consume the line if it encounters the end-of-file.

**Steps/Code to reproduce bug**

```python
In [1]: import cudf

In [2]: with open('foo.csv', 'w') as f:
   ...:     f.write('a,b\n1,2\n3,4')
   ...:

In [3]: cudf.read_csv('foo.csv').to_pandas()
Out[3]:
   a  b
0  1  2

In [4]: with open('foo.csv', 'w') as f:
   ...:     f.write('a,b\n1,2\n3,4\n')
   ...:
   ...:

In [5]: cudf.read_csv('foo.csv').to_pandas()
Out[5]:
   a  b
0  1  2
1  3  4
```

cc @vuule

**Comment by vuule** [comment]
This is not really a bug. The implementation has always assumed that the file ends with a newline.
@mjsamoht can you please help prioritize this issue?
