### ISSUE TITLE
[DOC] New parameter added to gdf_column_view_augmented (extra_info) is not documented.

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cudf#1084]
## Report incorrect documentation

https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/dataframe/column.cpp#L191
**Describe the problems or issues found in the documentation**

Parameter was added last week but there is no description of what the parameter is

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**

---

## Report needed documentation

**Report needed documentation**

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**

**Comment by kkraus14** [comment]
cc @felipeblazing since you touched this recently 😄

**Comment by felipeblazing** [comment]
https://github.com/rapidsai/cudf/pull/1090 look at these guys all over it!

**Comment by harrism** [comment]
@ChuckHastings the line you linked doesn't seem to match what you are talking about. Helps if you link to a specific commit hash. In any case, I believe the doxygen documentation is in types.h. 

Can you check to see if it is fixed by the PR @felipeblazing linked (#1090) and let us know? Thanks!

**Comment by ChuckHastings** [comment]
Yes, the PR #1090 corrects my documentation issue.
