### ISSUE TITLE
[FEA] Update to Thrust 1.16

### ISSUE THREAD

**Issue by robertmaynard** [rapidsai/cudf#10841]
We want to update the version of Thrust from 1.15 to 1.16 ([changelog](https://github.com/NVIDIA/thrust/blob/main/CHANGELOG.md#thrust-1160)). This update is needed to fix compilation with GCC 11, because of some warnings-as-errors present in Thrust 1.15 with GCC 11 (such as this one from Thrust's copy of cub: https://github.com/NVIDIA/cub/pull/418).

**Describe the solution you'd like**
As documented in https://github.com/rapidsai/cudf/pull/10586 the steps required are:

1. Try to work out whatever issues with CMake / include paths may exist.
2. Prepare all rapids-cmake repos for Thrust 1.16 compatibility. So far rmm (https://github.com/rapidsai/rmm/pull/1011) has been merged, and cuml is in progress ( https://github.com/rapidsai/cuml/pull/4675). Outstanding is cuCollections, raft, cuSpatial, and cuGraph.
3. Upgrade libcudf to Thrust 1.16 again (re-apply the updated patch in https://github.com/rapidsai/cudf/pull/10489, revert https://github.com/rapidsai/cudf/pull/10489 )
4. Upgrade rapids-cmake to Thrust 1.16.

**Comment by bdice** [comment]
Thanks for writing this up @robertmaynard! I can open the PRs for other repos soon - the time consuming part is self-review to make sure that the `#include`s are reasonably organized while keeping the diffs as minimal as possible.

**Comment by robertmaynard** [comment]
cugraph is now in progress https://github.com/rapidsai/cugraph/pull/2310

**Comment by bdice** [comment]
So are cuML (https://github.com/rapidsai/cuml/pull/4675), cuspatial (https://github.com/rapidsai/cuspatial/pull/539), cuco (https://github.com/NVIDIA/cuCollections/pull/161), raft (https://github.com/rapidsai/raft/pull/678). I am planning to commit a custom rapids-cmake `versions.json` and let CI test these packages with thrust 1.17-rc2, then revert those changes before merging.
