### ISSUE TITLE
[FEA] cudf::tdigest::percentile_approx() will return unsanitary lists for empty inputs.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#10856]
If all of the tdigest inputs to `percentile_approx` are empty, it will return a column containing null rows, as expected, but they will have unsanitary offsets.  

An example where 3 percentiles are requested (3 output values per row expected). 
```
List<double>:
Length : 3
Offsets : 0, 3, 6, 9
Null count: 3
000
   0, 0, 0, 0, 0, 0, 0, 0, 0
```

Ideally this would return

```
List<double>:
Length : 3
Offsets : 0, 0, 0, 0
Null count: 3
000
```

**Comment by GregoryKimball** [comment]
Could we just call the `purge_nonempty_nulls` from #10701?
