### ISSUE TITLE
[FEA] Series.median()

### ISSUE THREAD

**Issue by em-watkins** [rapidsai/cudf#1085]
I see that `Series.median()`, `Series.std()`, and other summary methods are supported today. It would be useful to have support for `Series.median()` like pandas does. 

current error: 'Series' object has no attribute 'median'
docker image: rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04
current-commit.hash: 
```
https://github.com/rapidsai/cudf.git
4a2f9c84dc97f7b77518f04babdf6de420ad48b6
```

**Comment by beckernick** [comment]
@kkraus14, this currently has the libcudf tag. Broadly speaking, the median is the 50th quantile estimated with linear interpolation. I would vote we implement  `median` in the Python bindings as just a wrapper around `quantile` at the series (as shown below) and dataframe level (iterating through the columns).

```
def median(self):
    return self.quantile(0.5, interpolation='linear') # enforce linear in case the default ever changes
```
