### ISSUE TITLE
[BUG] Writing parquet can take too much memory

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#10857]
**Describe the bug**
I have some proprietary data that when I try to write it out to parquet the amount of GPU memory that is being allocated becomes really huge. In this case over 200 times the size of the input data. I have been debugging this trying to understand why it is happening.  I have it traced down to the output compression buffer when doing snappy compression.

This data set has hundreds of columns in it and many of them are arrays and structs and arrays of structs/etc. Most of the columns have relatively small page sizes and also a relatively small number of pages, but one of them for some reason I do not understand has a page size that is 4 times the size of the next biggest page and thousands of times large than most pages. The current algorithm calculates the output size based off of the largest input page * the total number of pages. Because of this skew it means that we are asking for at least 26 times more data than we need. The 26 times is an estimate by writing each of the columns out individually and looking at the max page size there.

**Steps/Code to reproduce bug**
Just read in the file and try to write it out again. I am happy to hand over the file out of band. It is relatively small.

**Expected behavior**
I would love it if we could make it so that this would not crash. I don't know if there is something off with how page sizes are calculated and we are just getting too much skew there, or if it would be better to bucket the size of the pages, or even just call the nvcomp API for each of the different page sizes to get a truly accurate allocation.

**Comment by devavret** [comment]
> The current algorithm calculates the output size based off of the largest input page * the total number of pages.

> or even just call the nvcomp API for each of the different page sizes to get a truly accurate allocation.

This is due to a limitation in the nvcomp compressed size estimation API which doesn't guarantee that a kernel will NOT be called upon its invocation. If we could have this guarantee, then we could call it once per page.

Although, I'm curious why the page size is skewed given that we calculate it on our own and try to balance page sizes. I'm not very happy with the logic we currently have https://github.com/rapidsai/cudf/blob/280acdfd65b12b4ac953c193c7d7fd35809e41be/cpp/src/io/parquet/page_enc.cu#L336-L339

**Comment by revans2** [comment]
> This is due to a limitation in the nvcomp compressed size estimation API which doesn't guarantee that a kernel will NOT be called upon its invocation. If we could have this guarantee, then we could call it once per page.

Okay feels really odd that they would need a kernel if there is just an input data size and some options passed in.

https://github.com/rapidsai/cudf/blob/7f9d51ba91ea2c6503116d74c8d2787780eed4f0/cpp/src/io/parquet/writer_impl.cu#L1410-L1411

I think in this case there is guaranteed to be some skew in the page sizes. Some of the columns are string columns and, for this file at least, are all null values. Where as other columns have a lot of nearly random data. So even if you fix the page size issue there will likely be some skew in the results, unless you have lots and lots of really small pages.

I can think of a few ways to work around this. We could bucket the data based off of page size (small, medium and large).  Even if a kernel is called for each one of those three it should help reduce the total memory consumption and probably not introduce too much overhead. Or have a configurable maximum amount of memory that can be used for the compression output and split the single compression batch into smaller pieces if the compression output would go above that maximum. Or do a combination of the two and do the bucketing if the maximum memory usage would go over the limit, but before the data splitting in an attempt to save memory and keep performance unchanged in the common case.

**Comment by revans2** [comment]
> There's a problem here. Theoretically, a row could be arbitrarily large (string/list) and we cannot split the page in that case. I know it's rare and we don't even want to support a case where there's a megabyte sized string in a row.

I am not talking about splitting a page. I am talking about calling `nvcompBatchedSnappyCompressAsync` multiple times. The maximum would be a soft limit and if there is a single page that is too large to fit, then you just try and hope it works.

**Comment by revans2** [comment]
This is still relevant
