### ISSUE TITLE
[FEA] Rename `PER_THREAD_DEFAULT_STREAM` cmake option to be unique to cuDF 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#10862]
**Is your feature request related to a problem? Please describe.**

The `PER_THREAD_DEFAULT_STREAM` cmake option controls enabling `CUDA_API_PER_THREAD_DEFAULT_STREAM` to enable [per-thread default stream semantics](https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/) in CUDA. 

This name is not scoped to CUDF. This is not descriptive that it is a CUDF specific option and it could collide with other projects.

**Describe the solution you'd like**

Rename to `CUDF_USE_PER_THREAD_DEFAULT_STREAM`.

**Comment by jbrennan333** [comment]
I put up PR #10877 which fixes this, but does not remove PER_THREAD_DEFAULT_STREAM yet.
Will follow-up in 22.08 to remove PER_THREAD_DEFAULT_STREAM.

**Comment by jbrennan333** [comment]
This issue is still in progress.  I will be putting up a PR to remove PER_THREAD_DEFAULT_STREAM.
