### ISSUE TITLE
Bug in "shift" 

### ISSUE THREAD

**Issue by VitliKalesnik** [rapidsai/cudf#10875]
The following code shifts only the "b" column regardless of which column is being specified.

import pandas as pd
import dask.dataframe as dd
import cudf
pdf = pd.DataFrame({
    "a": [0,1,0,1,1,0],
    "b": range(6),
    "c": ["a","b","c","d","e","f"] })
gdf = cudf.from_pandas(pdf)
print (gdf)
print(pdf.groupby("a").b.shift(1))
gdf['n'] = gdf.groupby("a").a.shift(1)
gdf['nn'] = gdf.groupby("a").b.shift(1)
gdf['nnn'] = gdf.groupby("a").c.shift(1)
print (gdf)

**Comment by beckernick** [comment]
This was resolved in an earlier release and should no longer present. Closing, but feel free to reopen if you notice this is in the 22.06 nightly.

```python
import pandas as pd
import dask.dataframe as dd
import cudf

pdf = pd.DataFrame({
"a": [0,1,0,1,1,0],
"b": range(6),
"c": ["a","b","c","d","e","f"] })
gdf = cudf.from_pandas(pdf)
print (gdf)
print(pdf.groupby("a").b.shift(1))

gdf['n'] = gdf.groupby("a").a.shift(1)
gdf['nn'] = gdf.groupby("a").b.shift(1)
gdf['nnn'] = gdf.groupby("a").c.shift(1)
print (gdf)
   a  b  c
0  0  0  a
1  1  1  b
2  0  2  c
3  1  3  d
4  1  4  e
5  0  5  f
0    NaN
1    NaN
2    0.0
3    1.0
4    3.0
5    2.0
Name: b, dtype: float64
   a  b  c     n    nn   nnn
0  0  0  a  <NA>  <NA>  <NA>
1  1  1  b  <NA>  <NA>  <NA>
2  0  2  c     0     0     a
3  1  3  d     1     1     b
4  1  4  e     1     3     d
5  0  5  f     0     2     c

```
