### ISSUE TITLE
[FEA] Building and probing hash table libcudf APIs

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1087]
Had an offline discussion with @jrhemstad, but something that is needed to properly and performant support the `.loc` accessor (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) is the ability to build and keep around a hash table for a set of gdf_column(s) and be able to probe that hash table via an API.

For the `.loc` example, we'd want a hash table of values --> integer offsets so that we can collect a device array of integers to feed into a standard gather call.

This would also have other uses for other operations such as `value_counts` and other operations where we could be more efficient than the current sort based implementation.

**Comment by kkraus14** [comment]
Additionally, unless we want to constantly build hash tables on the fly, we should have the ability to reference the hash table from the Python side and pass that into the libcudf API calls via Cython.

**Comment by jrhemstad** [comment]
For more context, what this would look like is effectively exposing the functionality used in the hash-based join for building a hash table and then probing the hash table.

The build API could look something like this:

```
gdf_hash_table table = build_table( cudf::table keys, cudf::table payloads);
```

Where `keys` and `payloads` have the same number of rows. It will build a hash table mapping `keys[i]` to `payloads[i]` and return the hash table.


```
cudf::table payloads = probe_table (gdf_hash_table ht, cudf::table keys);
```

Given a hash table `ht` and a set of `keys`, probe `ht` and return the associated payload for each row in `keys`.

Design problem(s):

- The current hashmap classes require the number and types of columns to be known at compile time (it's template information). Can we somehow modify the design to use runtime information? i.e., the number and types of key and payload columns.

**Comment by nsakharnykh** [comment]
Another reason why we need this is to support more optimized distributed join algorithms for multi-GPU. Currently, cuDF provides a monolithic hash-join primitive that works great for single-GPU as well as certain multi-GPU join implementations such as shuffle (repartition) joins in Dask (https://blog.dask.org/2019/01/29/cudf-joins). However, there are other more efficient distributed join approaches available that highly utilize the hash table structure, e.g. broadcast hash joins (https://jaceklaskowski.gitbooks.io/mastering-spark-sql/spark-sql-joins-broadcast.html), that would require separate build and probe phases exposed in cuDF. + @muellren

**Comment by jrhemstad** [comment]
@nsakharnykh

**Comment by muellren** [comment]
One possibility is to templatize on the size of the keys and bit-compare keys.

**Comment by jrhemstad** [comment]
> One possibility is to templatize on the size of the keys and bit-compare keys.

That is a possibility, but could lead to a lot of template instantiations, and we'd have to hard-limit the size of the keys because we cannot generate an infinite number of template instantiations.

This also runs the risk of creating _very_ large hash-tables (as in memory consumption) if the size of the keys is large. This is why I went with a row-offset, indirection approach in join/groupby. 

To expand on the idea I mentioned above, here's what I'm thinking:

We instantiate only a single template instance of the `concurrent_unordered_multi/map` class, where `keyType=int32_t` and `valueType=int32_t`, such that the hash table will only store row offsets into a corresponding set of `key` and `value` columns.

As such, when you _build_ a hash table with `gdf_hash_table table = build_table( cudf::table keys, cudf::table payloads);` the returned `gdf_hash_table` object is really a combination of 3 things:
1. A pointer/copy of the input `keys` table
2. A pointer/copy of the input `payloads` table
3. A `concurrent_unordered_multi/map` whose key/values are row-offsets into the `keys` and `payloads` tables from 1. and 2., respectively.

**Comment by muellren** [comment]
`keyType=int32_t` because we currently store the `hash(key)` as the key in the map and, thus, pay the indirection on every probe? One typically stores at least a prefix (or better the most distinguishing part of the key) of the key in the HT.

**Comment by jrhemstad** [comment]
> `keyType=int32_t` because we currently store the `hash(key)` as the key in the map and, thus, pay the indirection on every probe? One typically stores at least a prefix (or better the most distinguishing part of the key) of the key in the HT.

That's a good point, the hash table `keyType` could be `pair<uint32_t, int32_t>` where `pair.first` is the hash value of the row and `pair.second` is the row index. This would reduce the amount of indirection required.

**Comment by jrhemstad** [comment]
After discussing with @kkraus14 and @shwina, I have a better idea of what's needed here. 

Today, libcudf's hash join has two phases:
1. Build a hash map from one of the input tables
2. Probe the hash map with the other table

Both of these phases are implementation details of the public facing `cudf::join` function. 

@kkraus14's request could be satisfied by providing public functions for each phase described above, e.g.,
```c++
class join_map; ///< Opaque type holding the hash map and other info

join_map build_join_map(table_view build_table);

table probe_join_map(table_view probe_table, join_map map);
```

`probe_join_map` could either return just the matching indices (i.e., the gather maps from `build_table`/`probe_table`), or the materialized join result from performing the requisite gathers.

This enables repeatedly probing a join hash map with different probe tables and saves the cost of having to build a new table every time. 

This would also enable @magnatelee's request to have an API to compute the output size of a join operation:

```
size_type get_join_output_size(table_view probe_table, join_map map);
...
auto map = build_join_map(t);

auto output_size = get_join_output_size(probe, map);

auto join_result = probe_join_map(probe, map);
```

Alternatively, we could make Join be an object oriented feature like groupby. We'd have a `join` object that hides the `map` internally and exposes member functions for building/probing/querying output size. Something like:
```
class hash_join{
   hash_join(table_view build_table); // Construct the `join` object from the table to build the map on
  
   size_type get_output_size(table_view probe_table); // Gets the output size

   table inner_join(table_view probe_table); // Materializes the inner join of build_table/probe_table

private:
  join_map map;
};
```

**Comment by zanmato1984** [comment]
This is a lovely proposal!

I'm looking forward to it as I'm planning to use the proposed new API to accelerate some of my own stuff.

@jrhemstad Is there an ETA for this feature? Thanks.

**Comment by jrhemstad** [comment]
> This is a lovely proposal!
> 
> I'm looking forward to it as I'm planning to use the proposed new API to accelerate some of my own stuff.
> 
> @jrhemstad Is there an ETA for this feature? Thanks.

This isn't an immediate high priority, so I'm guessing it won't make it until 0.16.

Are you planning to use this at the C++ level? I don't think it will be exposed in the Python API.

**Comment by zanmato1984** [comment]
> > This is a lovely proposal!
> > I'm looking forward to it as I'm planning to use the proposed new API to accelerate some of my own stuff.
> > @jrhemstad Is there an ETA for this feature? Thanks.
> 
> This isn't an immediate high priority, so I'm guessing it won't make it until 0.16.

OK. Any way 

> Are you planning to use this at the C++ level? I don't think it will be exposed in the Python API.

Yes, I'll be using the C++ API directly. 

> > This is a lovely proposal!
> > I'm looking forward to it as I'm planning to use the proposed new API to accelerate some of my own stuff.
> > @jrhemstad Is there an ETA for this feature? Thanks.
> 
> This isn't an immediate high priority, so I'm guessing it won't make it until 0.16.
> 
> Are you planning to use this at the C++ level? I don't think it will be exposed in the Python API.

Yes, I'm using the C++ API directly. 

I guess I'll just wait until it's ready. Thanks for replying :)

**Comment by zanmato1984** [comment]
> > This is a lovely proposal!
> > I'm looking forward to it as I'm planning to use the proposed new API to accelerate some of my own stuff.
> > @jrhemstad Is there an ETA for this feature? Thanks.
> 
> This isn't an immediate high priority, so I'm guessing it won't make it until 0.16.
> 
> Are you planning to use this at the C++ level? I don't think it will be exposed in the Python API.

Yes, I'm using the C++ API directly.

I guess I'll just wait until it's ready. Thanks for replying :)

**Comment by zanmato1984** [comment]
Hi @jrhemstad , I somehow managed to implement your proposal for this issue, and it worked just fine on my own stuff. I just opened a PR in https://github.com/rapidsai/cudf/pull/5648.

Could you please help to review? This is my first PR to this project and any comments are welcome.

Thanks in advance.
