### ISSUE TITLE
[FEA] Update read_csv to support using nvstrings

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#1088]
When #1032 closes, `cudf.read_csv_strings` can be deprecated, and `cudf.read_csv` should start actually returning an nvstring for string columns instead of hashed numeric columns.

**Comment by kkraus14** [comment]
Being tackled in #1032

**Comment by mjsamoht** [comment]
@kkraus14 a couple of questions:

1. I believe you meant to say "..., and **`cudf.read_csv`** should start actually returning an nvstring..." in the description.  Correct?
2. Other than deprecating `cudf.read_csv_strings` is there any other known work that will be required from cuIO team?  Just asking since we don't have much time left for 0.6.

**Comment by kkraus14** [comment]
> @kkraus14 a couple of questions:
> 
> 1. I believe you meant to say "..., and **`cudf.read_csv`** should start actually returning an nvstring..." in the description.  Correct?

Yes this is correct.

> 2. Other than deprecating `cudf.read_csv_strings` is there any other known work that will be required from cuIO team?  Just asking since we don't have much time left for 0.6.

I don't believe so. All of the work is on the Python side that I'll handle as part of my String integration work.

**Comment by vuule** [comment]
@kkraus14 
I think we also need to change the data type inference to detect string type instead of category. Is this correct?

Is it currently possible to use nvstring as a dataframe column?

**Comment by randerzander** [comment]
@vuule, yes type inference needs to be updated to default to string type instead of category.

When #1032 merges then it'll be possible for nvstrings to be cudf columns.

**Comment by mjsamoht** [comment]
I had a quick look at csv_reader.cu.  Unless I missed something this is just a one-line change:
`d_detectedTypes.push_back(GDF_CATEGORY); // For auto-detection, we are currently not supporting strings.`
needs to be changed to:
`d_detectedTypes.push_back(GDF_STRING);`

**Comment by mjsamoht** [comment]
Issue should be fixed with https://github.com/kkraus14/cudf/pull/3.

**Comment by kkraus14** [comment]
Fixed by #1032
