### ISSUE TITLE
[BUG] Error when reading jsonl file with Dask-cuDF

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#10898]
**Describe the bug**
Hi,

I am trying to read jsonl files with dask-cudf as follows on a DGX-1 with 8xv100 with 16GBs each.

> from dask.distributed import Client, wait
> from dask_cuda import LocalCUDACluster
> from dask.utils import parse_bytes
> import cudf
> import dask_cudf
> 
> cluster = LocalCUDACluster(
>     rmm_pool_size=parse_bytes("10GB") # Each GPU has 48GB of memory
> )
> client = Client(cluster)
> 
> ddf = dask_cudf.read_json("x00_004GB.jsonl", lines=True, chunksize="3 GB")

It produces the following error:

> 2022-05-19 12:11:24,886 - distributed.worker - WARNING - Compute Failed
> Key:       read_json_file-96198323-9136-47c3-ab62-7da49c4f709f
> Function:  execute_task
> args:      ((<function read_json_file at 0x7f388d946430>, <OpenFile '/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_004GB.jsonl'>, 'records', True, <function read_json at 0x7f35a94aae50>, False, '/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_004GB.jsonl', CategoricalDtype(categories=['/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_004GB.jsonl'], ordered=False), (<class 'dict'>, [['chunksize', '3 GB']])))
> kwargs:    {}
> Exception: "RuntimeError('cuDF failure at: /workspace/.conda-bld/work/cpp/include/cudf/strings/detail/strings_column_factories.cuh:79: total size of strings is too large for cudf column')"
> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_1393/2103654524.py in <module>
> ----> 1 ddf = dask_cudf.read_json("x00_004GB.jsonl", lines=True, chunksize="3 GB")
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/json.py in read_json(url_path, orient, lines, storage_options, blocksize, sample, encoding, errors, compression, meta, engine, include_path_column, path_converter, **kwargs)
>     284         ]
>     285 
> --> 286     return from_delayed(parts, meta=meta)
>     287 
>     288 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/io.py in from_delayed(dfs, meta, divisions, prefix, verify_meta)
>     623 
>     624     if meta is None:
> --> 625         meta = delayed(make_meta)(dfs[0]).compute()
>     626     else:
>     627         meta = make_meta(meta)
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
>     290         dask.base.compute
>     291         """
> --> 292         (result,) = compute(self, traverse=False, **kwargs)
>     293         return result
>     294 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
>     573         postcomputes.append(x.__dask_postcompute__())
>     574 
> --> 575     results = schedule(dsk, keys, **kwargs)
>     576     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
>     577 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
>    3013                     should_rejoin = False
>    3014             try:
> -> 3015                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
>    3016             finally:
>    3017                 for f in futures.values():
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
>    2165             else:
>    2166                 local_worker = None
> -> 2167             return self.sync(
>    2168                 self._gather,
>    2169                 futures,
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
>     307             return future
>     308         else:
> --> 309             return sync(
>     310                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
>     311             )
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
>     374     if error:
>     375         typ, exc, tb = error
> --> 376         raise exc.with_traceback(tb)
>     377     else:
>     378         return result
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in f()
>     347                 future = asyncio.wait_for(future, callback_timeout)
>     348             future = asyncio.ensure_future(future)
> --> 349             result = yield future
>     350         except Exception:
>     351             error = sys.exc_info()
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/tornado/gen.py in run(self)
>     760 
>     761                     try:
> --> 762                         value = future.result()
>     763                     except Exception:
>     764                         exc_info = sys.exc_info()
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
>    2028                             exc = CancelledError(key)
>    2029                         else:
> -> 2030                             raise exception.with_traceback(traceback)
>    2031                         raise exc
>    2032                     if errors == "skip":
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/json.py in read_json_file()
>     304 def read_json_file(f, orient, lines, engine, column_name, path, path_dtype, kwargs):
>     305     with f as open_file:
> --> 306         df = engine(open_file, orient=orient, lines=lines, **kwargs)
>     307     if column_name:
>     308         df = add_path_column(df, column_name, path, path_dtype)
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/io/json.py in read_json()
>      55 
>      56         return cudf.DataFrame._from_data(
> ---> 57             *libjson.read_json(
>      58                 filepaths_or_buffers, dtype, lines, compression, byte_range
>      59             )
> 
> cudf/_lib/json.pyx in cudf._lib.json.read_json()
> 
> cudf/_lib/json.pyx in cudf._lib.json.read_json()
> 
> RuntimeError: cuDF failure at: /workspace/.conda-bld/work/cpp/include/cudf/strings/detail/strings_column_factories.cuh:79: total size of strings is too large for cudf column

The `x00_004GB.jsonl` file is the output of the following command:

> $ cat x00_002GB.jsonl x00_002GB.jsonl > x00_004GB.jsonl

The `x00_002GB.jsonl` file can be read with the code above without issues.

In addition to the above, if I try to read a bigger and different file, `x00_005GB.jsonl`, I receive the following error:

> 2022-05-19 12:21:55,073 - distributed.worker - WARNING - Compute Failed
> Key:       read_json_file-d85b9bd0-499e-4bff-aecf-e4a4269cb82f
> Function:  execute_task
> args:      ((<function read_json_file at 0x7fc58d32a430>, <OpenFile '/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_005GB.jsonl'>, 'records', True, <function read_json at 0x7fc2a8efd5e0>, False, '/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_005GB.jsonl', CategoricalDtype(categories=['/rapids/notebooks/host/_rapids_bugs/20220514_error_when_reading_json_file_dask_cudf/x00_005GB.jsonl'], ordered=False), (<class 'dict'>, [['chunksize', '3 GB']])))
> kwargs:    {}
> Exception: "RuntimeError('CUDA error at: /opt/conda/envs/rapids/include/rmm/cuda_stream_view.hpp:81: cudaErrorIllegalAddress an illegal memory access was encountered')"
> 
> ---------------------------------------------------------------------------
> RuntimeError                              Traceback (most recent call last)
> /tmp/ipykernel_1675/3829119067.py in <module>
> ----> 1 ddf = dask_cudf.read_json("x00_005GB.jsonl", lines=True, chunksize="3 GB")
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/json.py in read_json(url_path, orient, lines, storage_options, blocksize, sample, encoding, errors, compression, meta, engine, include_path_column, path_converter, **kwargs)
>     284         ]
>     285 
> --> 286     return from_delayed(parts, meta=meta)
>     287 
>     288 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/io.py in from_delayed(dfs, meta, divisions, prefix, verify_meta)
>     623 
>     624     if meta is None:
> --> 625         meta = delayed(make_meta)(dfs[0]).compute()
>     626     else:
>     627         meta = make_meta(meta)
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(self, **kwargs)
>     290         dask.base.compute
>     291         """
> --> 292         (result,) = compute(self, traverse=False, **kwargs)
>     293         return result
>     294 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/base.py in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
>     573         postcomputes.append(x.__dask_postcompute__())
>     574 
> --> 575     results = schedule(dsk, keys, **kwargs)
>     576     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
>     577 
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in get(self, dsk, keys, workers, allow_other_workers, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
>    3013                     should_rejoin = False
>    3014             try:
> -> 3015                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
>    3016             finally:
>    3017                 for f in futures.values():
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
>    2165             else:
>    2166                 local_worker = None
> -> 2167             return self.sync(
>    2168                 self._gather,
>    2169                 futures,
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
>     307             return future
>     308         else:
> --> 309             return sync(
>     310                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
>     311             )
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
>     374     if error:
>     375         typ, exc, tb = error
> --> 376         raise exc.with_traceback(tb)
>     377     else:
>     378         return result
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in f()
>     347                 future = asyncio.wait_for(future, callback_timeout)
>     348             future = asyncio.ensure_future(future)
> --> 349             result = yield future
>     350         except Exception:
>     351             error = sys.exc_info()
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/tornado/gen.py in run(self)
>     760 
>     761                     try:
> --> 762                         value = future.result()
>     763                     except Exception:
>     764                         exc_info = sys.exc_info()
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
>    2028                             exc = CancelledError(key)
>    2029                         else:
> -> 2030                             raise exception.with_traceback(traceback)
>    2031                         raise exc
>    2032                     if errors == "skip":
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/dask/dataframe/io/json.py in read_json_file()
>     304 def read_json_file(f, orient, lines, engine, column_name, path, path_dtype, kwargs):
>     305     with f as open_file:
> --> 306         df = engine(open_file, orient=orient, lines=lines, **kwargs)
>     307     if column_name:
>     308         df = add_path_column(df, column_name, path, path_dtype)
> 
> /opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/io/json.py in read_json()
>      55 
>      56         return cudf.DataFrame._from_data(
> ---> 57             *libjson.read_json(
>      58                 filepaths_or_buffers, dtype, lines, compression, byte_range
>      59             )
> 
> cudf/_lib/json.pyx in cudf._lib.json.read_json()
> 
> cudf/_lib/json.pyx in cudf._lib.json.read_json()
> 
> RuntimeError: CUDA error at: /opt/conda/envs/rapids/include/rmm/cuda_stream_view.hpp:81: cudaErrorIllegalAddress an illegal memory access was encountered
> 

The three files mentioned above can be found [here](https://nvidia-my.sharepoint.com/:f:/p/miguelm/EqUY6w0jnX1LlH8Bk-nevzkBzl_XKcRK7gjMKaqTAjeHyg?e=Atyfrp) .

**Steps/Code to reproduce bug**
Running on RAPIDS container as follows:

> docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 -v /raid/miguelm/projects/:/rapids/notebooks/host rapidsai/rapidsai-core:22.04-cuda11.5-runtime-ubuntu20.04-py3.8

**Expected behavior**
No errors.

**Comment by beckernick** [comment]
> Exception: "RuntimeError('cuDF failure at: /workspace/.conda-bld/work/cpp/include/cudf/strings/detail/strings_column_factories.cuh:79: total size of strings is too large for cudf column')"

In this context, this error generally means that at least one of your partitions would have contained single column with too many characters. Does this still fail for the larger files if you use a smaller chunk size, such as 1 GB?

**Comment by miguelusque** [comment]
Hi @beckernick , but that is weird. The 4GBs files is just the concatenation of the 2GBs file, and the 2GBs file loads without issues.

**Comment by beckernick** [comment]
Discussed offline, but for clarity the limit noted in the column above applies to the total number of characters in a string column rather than a single row.

I suspect the issue is that the Dask JSON readers will read a single file into a single partition, regardless of the size. @rjzamora is that consistent with your understanding?

**Comment by ayushdg** [comment]
For the dask dataframe api, the argument for partition size is blocksize and not chunksize. 
According to their [docs](https://docs.dask.org/en/latest/generated/dask.dataframe.read_json.html) this only works for line delimited Json files (which should work here).

**Comment by miguelusque** [comment]
Hi! Amended as suggested, and it works like a charm now. Thanks!

(copying the code used below for future readers reference)

> from dask.distributed import Client, wait
> from dask_cuda import LocalCUDACluster
> from dask.utils import parse_bytes
> import cudf
> import dask_cudf
> 
> cluster = LocalCUDACluster(
>     rmm_pool_size=parse_bytes("15GB") # Each GPU has 16GB of memory
> )
> client = Client(cluster)
> 
> ddf = dask_cudf.read_json("x00_020GB.jsonl", lines=True, blocksize=parse_bytes("1 GB"))
> ddf["text"] = ddf["text"].str.replace(pat="\\n", repl=" ", regex=False)
> ddf["text"] = ddf["text"].str.replace(pat="\\r", repl=" ", regex=False)
> ddf["text"] = ddf["text"].str.replace(pat="\\t", repl=" ", regex=False)
> 
> ddf = ddf[ddf["text"].str.len() > 256].reset_index(drop=True)
> ddf.to_csv('result-*.csv', index=False, columns=["text"])
