### ISSUE TITLE
[BUG] regexp: `\d` and `[0-9]` produce different results for some unicode inputs

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#10894]
**Describe the bug**
I'm not sure if this is a documentation bug or implementation bug but the documentation states that "\d matches a character that is a digit" so my expectation was that this would be equivalent to `[0-9]` but this is not always the case.

**Steps/Code to reproduce bug**

``` python
>>> s = cudf.Series(['aa', 'aa1', '鈻', '鈻1', '䤫畍킱곂⬡❽ࢅ獰᳌蛫青'])
>>> s.str.contains('\d', regex=True)
0    False
1     True
2    False
3     True
4     True
dtype: bool
>>> s.str.contains('[0-9]', regex=True)
0    False
1     True
2    False
3     True
4    False
dtype: bool
```

**Expected behavior**
I would expect `\d` and `[0-9]` to produce the same results. If this is not the intent then it would be good to clarify in the documentation what `\d` means. In some other regexp engines (such as Java) it is explicit that `\d` is the same as `[0-9]`.

**Environment overview (please complete the following information)**
N/A

**Environment details**
N/A

**Additional context**
None

**Comment by davidwendt** [comment]
Reference also Python regex `re` library https://docs.python.org/3/library/re.html
It indicates that unicode characters identified as digits are to match `\d` but this does not seem to be the case:
```
>>> str.isdigit('❽')
True
>>> print(re.match(r'\d','❽',flags=re.UNICODE))
None
```
This is puzzling. I'll need to investigate further.

**Comment by davidwendt** [comment]
For reference it looks like Java only supports the ASCII characters for the builtin character classes `\d`, `\D`, `\s`, `\S`, `\w`, `\W`
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/regex/Pattern.html
(this does not appear to have changed much between versions 8 and 18).

**Comment by andygrove** [comment]
Thanks @davidwendt. We are now transpiling `\d` to `[0-9]` before passing to cuDF so that we can guarantee the same results as Java so we are not blocked on anything here but I think it would be good to update the documentation.

**Comment by davidwendt** [comment]
One partial solution for this is to support an `ASCII` regex flag like in python https://docs.python.org/3/library/re.html#re.ASCII
The page there also mentions how the `\d, \w, \b` specifiers' behavior with this flag.

So I think adding support for an `ASCII` flag here would match what Java/Spark expect:
https://github.com/rapidsai/cudf/blob/e0003a019797c482b1270427689b4b55766e936b/cpp/include/cudf/strings/regex/flags.hpp#L35-L39
