### ISSUE TITLE
[BUG] DataFrame.head method has slowed down

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1089]
**Describe the bug**
Hi,

I am just wondering if there has been any change to the DataFrame.head method. I am mentioning that because it used to run really fast before, and now it looks like it does not finish when performing the following command:

> h_df3b = h_df2.sort_values('attachments').head(h_df2['attachments'].count())

h_df2['attachments'].count() is 1466704

With that code, what I am trying to do is to create a new dataframe (h_df3b) where the column 'attachments' contains no nulls.

Regards,
Miguel
**Steps/Code to reproduce bug**
Described above.

**Expected behavior**
To run as fast as before (0.5.1 version of the code)

**Environment details (please complete the following information):**
DGX-1 with today's rapidsai-nightly container at DockerHub.

**Additional context**

**Comment by miguelangel** [comment]
Thank you @kkraus14 for a valid workaround:

> h_df3b = h_df2.sort_values('attachments').iloc[:h_df2['attachments'].count()]

**Comment by kkraus14** [comment]
Closing in favor of #1176
