### ISSUE TITLE
[FEA] Generate element labels from offsets

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#10905]
In some cases, for a list column, we want to generate labels for each element in the child column. 

For example, given a list column `[ [1, 2, 3], [4, 5], [6, 7, 8] ]`, we want to generate a label column like `[0, 0, 0, 1, 1, 2, 2, 2]`. 

Having such label column, we can combine the child column (i.e, `[1, 2, 3, 4, 5, 6, 7, 8]`) and the label column for further processing. Use case of such label column already exists in `drop_list_duplicates` ([link](https://github.com/rapidsai/cudf/blob/ca952f8355810c46bb132f0b50a67e4109108ccb/cpp/src/lists/drop_list_duplicates.cu#L175)).
The next use case would be for set-like operations (https://github.com/rapidsai/cudf/issues/10409), when we want to process all elements in the child column in parallel (i.e., one element per thread), instead of one list per thread.

**Comment by jrhemstad** [comment]
This sounds like something that could be an iterator instead of or in addition to needing to actually materializing the column of labels. I'd make the iterator and then if needed, use the iterator to implement materializing the labels.
