### ISSUE TITLE
Drop `thirdparty` directory in `custreamz`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#10918]
Appears there is a [`thirdparty` directory in `custreamz`]( https://github.com/rapidsai/cudf/tree/branch-22.06/python/custreamz/thirdparty ), but it is empty except for a license file. Guessing this was uses previously for something, but it appears to be no longer needed. If that's true, should we drop it?

**Comment by shwina** [comment]
Yup - we should drop it.

**Comment by vyasr** [comment]
Closed in #11343
