### ISSUE TITLE
 nan results in infinite values for rolling functions[BUG]

### ISSUE THREAD

**Issue by kunshouout** [rapidsai/cudf#10946]
**Describe the bug**
I have a cudf.Series looks like this:
s2.iloc[:201]
Out[60]: 
0      <NA>
1      <NA>
2      <NA>
3      <NA>
4      <NA>
       ... 
196    <NA>
197    <NA>
198    <NA>
199    <NA>
200     NaN

Note the last NaN values. If I do a rolling function, 

s2.iloc[:201].rolling(125,1).min()
Out[62]: 
0                  <NA>
1                  <NA>
2                  <NA>
3                  <NA>
4                  <NA>
             ...       
196                <NA>
197                <NA>
198                <NA>
199                <NA>
200    1.797693135e+308

However, if I convert s to nulls, it works fine

s2.nans_to_nulls().iloc[:201].rolling(125,1).min()
Out[63]: 
0      <NA>
1      <NA>
2      <NA>
3      <NA>
4      <NA>
       ... 
196    <NA>
197    <NA>
198    <NA>
199    <NA>
200    <NA>

I have read this missing-value doc(https://docs.rapids.ai/api/cudf/stable/user_guide/Working-with-missing-data.html). It does not mention anything about infinite results, so I assumed that both None and np.nan would work for rolling or groupby functions. For a  pandas user, this is quite counterintuitive.

So if I don't want to get into this infinite-value situation, should I always nans_to_nulls()? 

**Environment overview (please complete the following information)**
cudf 20.04
ubuntu 20

**Comment by ttnghia** [comment]
This is a bug. Currently rolling operations are implemented as
```
value = identity<OutputType>();

for(i in window) {
   value = op(value, input[i]);
}
```
For floating points number and `min` op, `identity() = inf`. And `std::min(inf, NaN) = inf`. This is why you get the wrong result.

**Comment by ttnghia** [comment]
Ref: https://github.com/rapidsai/cudf/blob/e8d189c8d3369c0a19217ac7c91f0285ab2b05ca/cpp/src/rolling/rolling_detail.cuh#L129

**Comment by jrhemstad** [comment]
@ttnghia This is not a bug, this is following typical IEEE754 NaN behavior. 

This is a difference in the semantics of NaN vs Null in Pandas vs cuDF.

I'll let @vyasr or @shwina explain as they'll do a better job than me.

**Comment by ttnghia** [comment]
Okay I was wrong. I remembered that any operation involving `NaN` will be `NaN`.

**Comment by GregoryKimball** [comment]
Thank you @kunshouout for raising this issue. The behavior in cuDF is expected and comes as a result of explicitly treating NaN and Null with difference conventions. I'm glad you were able to use `nans_to_nulls` to avoid adding a singularity to your data. By the way, the [Working with missing data](https://docs.rapids.ai/api/cudf/stable/user_guide/missing-data.html) doc has moved.
