### ISSUE TITLE
List operation in Cudf dataframe

### ISSUE THREAD

**Issue by arpan-das-astrophysics** [rapidsai/cudf#10967]
I have a cudf dataframe where the cell values of the columns are list (as the original data has N-D array as a cell value) and I am to do simple math operation like subtracting one column from another and it is giving me an error " Lists concatenation for this operation is not yetsupported". However, if I am converting the dataframe to Pandas it is working fine. Is there a simpler way to do math operation when the column dtypes are lists? I want to keep everything in GPU and hence switching back to Pandas is not helping much.

**Comment by shwina** [comment]
No, list operations are somewhat limited, and a column of lists can't be treated the same as a column of ndarrays in Pandas.

Are all your "lists" of the same length? If so, it might be simpler to store them as separate columns of a DataFrame.

**Comment by arpan-das-astrophysics** [comment]
> No, list operations are somewhat limited, and a column of lists can't be treated the same as a column of ndarrays in Pandas.
> 
> Are all your "lists" of the same length? If so, it might be simpler to store them as separate columns of a DataFrame.

Unfortunately no, different cell has different shaped arrays which actually represents observational data from telescopes. The main reason of using Cudf and Dask_cudf is to gain substantial speed with the gpus and hence I don't wanna switch back and forth between Pandas and Cudf. Is there a way to store the N-D array as something else and not as list to the cells?

**Comment by shwina** [comment]
Thanks! Could you also help with some additional information?

* How large are each of your lists (max?)
* How many lists do you have?
* What kind of operations do you need to do with these lists? (is it truly restricted to just binary and unary operations?)

If you're able to provide an example program that works in Pandas, that would be fantastic.

I'd like to understand if  there are ways to achieve what  you need in cuDF  today, and if not, what features we'd need to implement to enable that.

**Comment by arpan-das-astrophysics** [comment]
> Thanks! Could you also help with some additional information?
> 
> * How large are each of your lists (max?)
> * How many lists do you have?
> * What kind of operations do you need to do with these lists? (is it truly restricted to just binary and unary operations?)
> 
> If you're able to provide an example program that works in Pandas, that would be fantastic.
> 
> I'd like to understand if there are ways to achieve what you need in cuDF today, and if not, what features we'd need to implement to enable that.

My cudf data frame looks like the attached screenshot and I want to do a simple operation 

> df['baseline'] = df['POSITION_ANTENNA1']-df['POSITION_ANTENNA2'] 

which raises the above mentioned error. However if I do the following it works 

> df['baseline'] = df['POSITION_ANTENNA1'].to_pandas()-df['POSITION_ANTENNA2'].to_pandas()

Unfortunately the shape and dimension of the cell arrays are hard to comment on as it depends on what kind of observation and telescope used but I want to create generic tool which should not know what the shape of the data is. 

<img width="1016" alt="Screenshot 2022-05-26 at 01 33 12" src="https://user-images.githubusercontent.com/23120837/170386626-f3b58cf3-ebc9-4be5-8f21-aa2a0ad40f34.png">

**Comment by shwina** [comment]
Here's one way I think you could do this:

```python
df['baseline'] = (df['POSITION_ANTENNA1'].explode() - df['POSITION_ANTENNA2'].explode()).groupby(level=0).agg(list)
```

(explode each list column into a flat column, perform the binary operation, then construct a list column back from the result)

**Comment by arpan-das-astrophysics** [comment]
> Here's one way I think you could do this:
> 
> ```python
> df['baseline'] = (df['POSITION_ANTENNA1'].explode() - df['POSITION_ANTENNA2'].explode()).groupby(level=0).agg(list)
> ```
> 
> (explode each list column into a flat column, perform the binary operation, then construct a list column back from the result)

Thank you very much. This works perfectly. Now I have another question, is there a way to apply user-defined function to those columns containing list values? I am trying to avoid them to read them as numpy array first and do the calculation.

**Comment by arpan-das-astrophysics** [comment]
Hi @shwina , thank you for the reply. So here is the UDF: 

`baseline = df.baseline.explode().to_numpy().reshape((len(df_merged.baseline),3))*u.m
times = df.TIME.explode().to_numpy()
ref = df.REFERENCE_DIR.explode().to_numpy().reshape((len(df_merged.REFERENCE_DIR),2))

def compute_uvw(baseline, site, times, ref):
    baseline_ap = coord.EarthLocation(x=baseline[:,0], y=baseline[:,1], z=baseline[:,2])
    vla = coord.EarthLocation.of_site(site)
    t = astropy.time.Time(times, format='mjd', scale='utc')
    vla_p, vla_v = vla.get_gcrs_posvel(t)
    baseline_c_ap = coord.GCRS(baseline_ap.get_gcrs_posvel(t)[0], 
        obstime=t, obsgeoloc=vla_p, obsgeovel=vla_v)
    lon = ref[:,0]*u.rad
    lat = ref[:,1]*u.rad
    pnt = coord.SkyCoord(lon, lat, frame='icrs')
    frame_uvw = pnt.transform_to(baseline_c_ap).skyoffset_frame()
    baseline_uvw_ap = baseline_c_ap.transform_to(frame_uvw)
    baseline_uvw_ap = baseline_uvw_ap.cartesian
    baseline_uvw_ap = coord.CartesianRepresentation(
        x = baseline_uvw_ap.y,
        y = baseline_uvw_ap.z,
        z = baseline_uvw_ap.x)
    uvw = np.stack((baseline_uvw_ap.x.value, baseline_uvw_ap.y.value, baseline_uvw_ap.z.value),axis=1)
    
    return uvw

uvw = compute_uvw(baseline,'vla',times,ref)` 

where **baseline, time and ref** all are columns in the cudf dataframe. I am trying to execute that function which uses astropy for some conversions. I was wondering if there is a trick to do it faster without converting everything to numpy array.

**Comment by shwina** [comment]
> where baseline, time and ref all are columns in the cudf dataframe

It looks like these are the flat ("exploded") columns, and not the original list columns. If so, it _is_ possible to apply user-defined functions to them. We go over the technical details and limitations [here](https://docs.rapids.ai/api/cudf/nightly/user_guide/guide-to-udfs.html).

The difficulty with your UDF is that it seems to rely on a third-party library (`coord`), which we don't support on the GPU. If it's possible to replace the use of `coord` with some hand-spun functions that operate directly on numeric data, it could be possible to run on the GPU.

Sorry, that's probably not the answer you were hoping for... but we still have a ways to go before being able to support complex use-cases like this one.

**Comment by arpan-das-astrophysics** [comment]
@shwina Okay thank you. One last question for now. What is the best way to store the dataframe with list columns. Because in the original dataframe the dtype for the columns are list, for example: 

![Screen Shot 2022-05-31 at 3 25 50 PM](https://user-images.githubusercontent.com/23120837/171184494-bf84d58f-9465-41ad-a47c-b963e3271acf.png)

Now I have saved the dataframe by converting into pandas first: 
```python

df = df_merged.to_pandas()
df.to_csv('test.csv')
df1 = cudf.read_csv('test.csv')
``` 

Now when I read the same column the dtypes have changed to object and I can't use the .explode() method anymore 
![Screen Shot 2022-05-31 at 3 29 51 PM](https://user-images.githubusercontent.com/23120837/171185081-394359d4-a32e-4e5c-9d0a-986a098569d2.png)
 
Is it possible to implement more feautres for list columns!!!

**Comment by shwina** [comment]
The best (and fastest) way to write and read this type of data would be to use the [parquet](https://parquet.apache.org/) format, which _does_ support lists:

```
df.to_parquet('test.parquet')
df1 = cudf.read_parquet('test.parquet')
```

Note that you do not need to go through Pandas for writing Parquet files.

**Comment by arpan-das-astrophysics** [comment]
Okay thank you. I just checked with hdf5 as well and that supports it as well.

**Comment by GregoryKimball** [comment]
Closing in favor of #11130 which would enable easier list arithmetic.
