### ISSUE TITLE
[FEA] Limitation on amount of Strings that can be loaded into the memory

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#10976]
It seems like there is a limitation of around 2B total chars that can be present in a string column even though we don't max out on the GPU memory.

Here is a repro for it.
```
import cudf
import cupy as cp
df =cudf.DataFrame()
df['a'] = cp.random.randint(0,999,500_000_000)
df = df.to_pandas()
df['b'] = 'Hi'
df['c'] = df.b+df.a.astype('str')
df.to_parquet('test-str.pq')

import cudf
df = cudf.read_parquet('test-str.pq', columns=['a'])
```
Reading the int64 col with 0.5B rows works just fine. Memory print: (8bytes x 5,000,000,000)

But when i try to read the same number of columns with string of max 5 chars each (max of 2.5B chars) Memory print: (5 bytes x 5,000,000,000) which is less than above
```
import cudf
df = cudf.read_parquet('test-str.pq', columns=['c'])
df.dtypes, df.head()
```
cudf throws me an exception.
```RuntimeError: cuDF failure at: /workspace/.conda-bld/work/cpp/include/cudf/strings/detail/strings_column_factories.cuh:86: total size of strings is too large for cudf column```

**Comment by vyasr** [comment]
This is expected. A strings column cannot contain more than `INT_MAX=2^31` characters. See #3958 for a longer discussion. The usual solution for this problem in cudf is to use dask, which will handle chunking that column into multiple pieces for you.
