### ISSUE TITLE
[BUG] type dispatcher doesn't accept device-only functors 

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1098]
Sometimes you want to use the `type_dispatcher` to call some device code - just device code. Say, from within a function that is itself `__device__`. However, if you pass it a functor whose `operator()` instantiations are `__device__` rather than `__host__ __device__` - I get an error:
```
/path/to/cudf/cpp/src/utilities/type_dispatcher.hpp(100): error: calling a __device__ function("operator()") from a __host__ __device__ function("type_dispatcher") is not allowed
```
I'm not quite sure why this happens, since I can't reproduce the error  in [this simpler case](https://godbolt.org/z/zaa9Yz).

**Comment by jrhemstad** [comment]
That's strange, avoiding this error is explicitly why I added the `#pragma hd_warning_disable` to the type_dispatcher:

https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/utilities/type_dispatcher.hpp#L111

**Comment by harrism** [comment]
I haven't had this problem, I was able to type dispatch device-only functors. Closing until it comes up again.
