### ISSUE TITLE
[FEA] `orderby.cu` takes twice as long to build as any other file

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1099]
I was experimenting with the `ninja` build system, and it has a nice way to demonstrate how long each object file takes to compile.

I found that https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/orderby/orderby.cu takes 2-3x longer than any other file.

If we could reduce the compile time of that file, our overall build time could be improved by 2-3x.

I'm guessing that the `LesserRTTI` functor is to blame: https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/sqls/sqls_rtti_comp.h#L31

![cudf_build](https://user-images.githubusercontent.com/15221289/53830936-682cdd80-3f38-11e9-90c3-966e1f9e5b21.png)

**Comment by jrhemstad** [comment]
To reproduce the above graph:

Install `ninja-build`:
```
sudo apt-install ninja-build
```

Configure and build libcudf with ninja:
```
cd cudf/cpp/build
PARALLEL_LEVEL=N cmake .. -GNinja
ninja
```
Where `N` is the number of threads to use for the parallel build.

Get `ninjatracing`:
```
git clone https://github.com/nico/ninjatracing.git
```

Generate trace file:
```
./ninjatracing cudf/cpp/build/.ninja_log > trace.json
```

Open trace file:
- Open Google Chrome
- Enter `chrome://tracing` in the URL bar
- Hit the "Load" button and load the `trace.json` file you created in the above step

**Comment by harrism** [comment]
@jrhemstad should we update the performance plot in this issue now that #1538 is merged? Or should we just close this?

**Comment by jrhemstad** [comment]
@williamBlazing's brought down `orderby.cu` from ~480s to ~300s. I've attached updated graphs.

However, you can see that it's still ~2x the compile time of any other file. So our compile time will always be lower bounded by the compile time of `orderby.cu` at ~5 minutes. 

At this point, I don't know how much more we can do in libcudf. `orderby.cu` just calls a `thrust::sort` with a custom inequality operator. We may need to try and isolate it and show it to the Thrust team to see why it's taking so long to compile. 

As such, I think it's worth keeping the issue open until we find out why the `thrust::sort` call is taking so long. 

*branch-0.7*
![branch-0 7](https://user-images.githubusercontent.com/15221289/58062985-46072c80-7b31-11e9-8750-404319209833.png)

*branch-0.8*
![branch-0 8](https://user-images.githubusercontent.com/15221289/58062098-e52a2500-7b2d-11e9-848d-ccb4b36618aa.png)

**Comment by harrism** [comment]
Thanks for updating!

**Comment by harrism** [comment]
I think we should leave this open since orderby is still the long pole in compilation time. 

Is it possible to reduce the type combinations supported somehow? Presumably it is slow because there are a lot of type template combinations, but, for example, do some combinations not make sense to support?

**Comment by harrism** [comment]
Moving to 0.9.

**Comment by karthikeyann** [comment]
<img width="894" alt="compilation_profiling" src="https://user-images.githubusercontent.com/6488848/65555334-02db2100-df4a-11e9-9c85-f5644bca31a8.PNG">
ptxas takes most time when compiling with nvcc

**Comment by devavret** [comment]
`orderby.cu ` is legacy and will be removed. Should this issue be closed or renamed to the now longest to compile source file?
