### ISSUE TITLE
[DISCUSSION] Remove the Arrow CUDA IPC related code from libcudf/cuDF

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#10994]
libcudf provides a utility to read the Arrow IPC format composed of device (rather than host) buffers:

https://github.com/rapidsai/cudf/blob/branch-22.08/cpp/include/cudf/ipc.hpp

based on which, we have some Python utilities:

https://github.com/rapidsai/cudf/blob/branch-22.08/python/cudf/cudf/comm/gpuarrow.py

---

This feature was developed in the very early `pygdf` days, to enable some [early demos](https://github.com/Avkash/deeputil/blob/2667848a472002018541b7e029fc5b434e8924de/examples/notebooks/trials/mapd_to_pygdf_to_h2oaiglm.ipynb) showing data exchange between different GPU-enabled libraries.

Since then, other ways to exchange data, including `__cuda_array_interface__`,  `dlpack`, and file-based (`parquet`), have been added to cuDF. Searching on GitHub for users of `GpuArrowReader`, for example,  yields nothing recent.

This part of the codebase is totally independent of the rest of the project. Looking in `ipc.hpp` or `ipc.cpp`, we notice that they don't depend on any other parts of libcudf.

Additionally, it makes us dependent on Arrow CUDA, which in turn [requires linking to `libcuda.so`](https://github.com/rapidsai/cudf/issues/3661#issuecomment-1098381181). This precludes being able to, for example, build or import cudf on machines that do not have the CUDA driver installled.

---

I'd suggest that we simply go ahead and shed this bit of code from the project. Utilities like this may be much more at home in the Arrow project itself, and I've opened a [ticket](https://issues.apache.org/jira/browse/ARROW-16635) in the Arrow JIRA proposing exactly that.

**Comment by trivialfis** [comment]
Hi @shwina could you please take a look into https://github.com/NVIDIA/spark-rapids/issues/5561 ?

**Comment by shwina** [comment]
Hi @trivialfis - this issue is a bit orthogonal to that one as it doesn't look like Spark RAPIDS is utilizing the existing Arrow CUDA IPC code in cuDF. If they choose to do so at some point, the code can always be vendored.

**Comment by revans2** [comment]
I need to clarify a bit. There have been several people ask for this type of a feature with Spark so we can move data to a python process for ML. But with issues around cuda IPC and the async allocator we have not done much to really dig into it. We need to support going to/from CPU arrow formatted data, but we don't need the IPC use case directly right now. When we do get to the point where we could do CUDA IPC we can take a look at exactly what it would take at that point.
