### ISSUE TITLE
[QST]Failed to dlopen libcuda.so

### ISSUE THREAD

**Issue by lk137095576** [rapidsai/cudf#11028]
I installed cudf and cuml as instructed, but when import, I encountered this problem
I see the https://github.com/rapidsai/cudf/issues/10308, but it doesn't work for me.  my os is ubuntu18.04

Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so
Exception ignored in: 'cuda._lib.ccudart.utils.cudaPythonGlobal.lazyInitGlobal'
Traceback (most recent call last):
  File "cuda/_cuda/ccuda.pyx", line 3671, in cuda._cuda.ccuda._cuInit
  File "cuda/_cuda/ccuda.pyx", line 435, in cuda._cuda.ccuda.cuPythonInit
RuntimeError: Failed to dlopen libcuda.so

nvcc -V:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Oct_11_21:27:02_PDT_2021
Cuda compilation tools, release 11.4, V11.4.152
Build cuda_11.4.r11.4/compiler.30521435_0

locate libcuda.so  :
/home/hncg/nni/examples/trials/systems/opevo/tvm_patches/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.470.57.02
/usr/lib/stubs/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcuda.so.470.57.02
/usr/local/cuda-10.2/doc/man/man7/libcuda.so.7
/usr/local/cuda-10.2/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/local/cuda-11.4/targets/x86_64-linux/lib/stubs/libcuda.so
/usr/share/man/man7/libcuda.so.7

cat  ~/.bashrc :
# <<< conda initialize <<<
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64

**Comment by shwina** [comment]
Hi @lk137095576 -- just to confirm, what is the output of `nvidia-smi`?

**Comment by lk137095576** [comment]
> 

Thu Jun  2 21:53:15 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA TITAN Xp     Off  | 00000000:02:00.0 Off |                  N/A |
| 21%   38C    P0    61W / 250W |      0MiB / 12196MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA TITAN Xp     Off  | 00000000:04:00.0 Off |                  N/A |
| 19%   36C    P0    62W / 250W |      0MiB / 12196MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA TITAN Xp     Off  | 00000000:83:00.0 Off |                  N/A |
| 24%   40C    P0    62W / 250W |      0MiB / 12196MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA TITAN Xp     Off  | 00000000:84:00.0 Off |                  N/A |
| 19%   36C    P0    60W / 250W |      0MiB / 12196MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by shwina** [comment]
Thanks! And also could you provide the output of `echo $LD_LIBRARY_PATH` ? I wonder if, similar to the   linked issue, `libcuda.so` is getting picked up from somewhere other  than `/usr/lib/x86_64-linux-gnu/`.

What happens if you do:

```
export  LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/:$LD_LIBRARY_PATH
```

before running Python?

**Comment by shwina** [comment]
Thanks -- it means something in your `LD_LIBRARY_PATH` contains a broken `libcuda.so`. Before you run the `export` command above, can you show the output of:

```
echo $LD_LIBRARY_PATH
```

?

**Comment by lk137095576** [comment]
> Thanks -- it means something in your `LD_LIBRARY_PATH` contains a broken `libcuda.so`. Before you run the `export` command above, can you show the output of:
> 
> ```
> echo $LD_LIBRARY_PATH
> ```
> 
> ?

the out of echo $LD_LIBRARY_PATH
'/usr/lib/x86_64-linux-gnu/:/usr/lib/x86_64-linux-gnu/::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64'

**Comment by shwina** [comment]
Going to close this issue as resolved, as it looks like the solution provided works, and the problem seems something specific to your environment, @lk137095576. Please feel free to reopen if necessary.

**Comment by Skybluewater** [comment]
https://www.cnblogs.com/Skybluewater/articles/18778705 can check this pasage for sol

**Comment by vyasr** [comment]
Did you intend to post this here? If you have a bug with cudf, please open a new issue.

**Comment by Skybluewater** [comment]
> Did you intend to post this here? If you have a bug with cudf, please open a new issue.

I'm sorry, I find the link isn't supposed to be posed here, I'll remove it right away

**Comment by vyasr** [comment]
No problem.
