### ISSUE TITLE
[FEA] Expand OS and OS distribution support/testing

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1104]
At the moment, the RAPIDS page [says](https://rapids.ai/start.html):

> Prerequisites
>    ...
>    Ubuntu 16.04 or 18.04

And this repository's README.md says:
> These instructions are tested on Linux Ubuntu 16.04 & 18.04 ...  Other operatings systems may be compatible, but are not currently tested.

I don't think this is reasonable for a FOSS library. There should be testing (whether part of the Travis CI here or something occurring before a release etc.) on non-Ubuntu systems. At the very least Debian, Fedora and possibly Mint, Manjaro [etc.](https://distrowatch.com/dwres.php?resource=major). That's for the Linux side. Should we not also be aiming for MacOS compatibility? Windows? FreeBSD?

Due disclosure: I myself am using a Devuan ASCII machine for development.

**Comment by felipeblazing** [comment]
This decision was made about a year ago. The reasons are both the practical concerns of not having do devote more time to devops  with resource constraints and debugging/testing when things go nuts in a different environment.

**Comment by eyalroz** [comment]
@felipeblazing : A few more Travis CI VM's for Mac and other Linux distros don't sound like such a significant investment. Windows is a bit more of hassle, granted, but it shouldn't be _that_ bad... should it?

**Comment by kkraus14** [comment]
> > These instructions are tested on Linux Ubuntu 16.04 & 18.04 ... Other operatings systems may be compatible, but are not currently tested.

> I don't think this is reasonable for a FOSS library.

I don't think it's reasonable or helpful for you to make statements like this without trying to help improve the situation.

> A few more Travis CI VM's for Mac and other Linux distros don't sound like such a significant investment.

TravisCI unfortunately has no GPU support, outdated versions of OSes, and limited core counts and timeouts, which make it near impossible to use for this project. We originally used TravisCI, but we moved away from it to our own platform to provide a better developer experience.

> Should we not also be aiming for MacOS compatibility? Windows? FreeBSD?

It would be great if you explored, scoped, and documented the level of effort to resolve the current issues related to supporting these operating systems.

**Comment by datametrician** [comment]
Given MacOS has awful NVIDIA GPU support, I think we will skip that one

**Comment by eyalroz** [comment]
@kkraus14 : I think we have different views of what is appropriate for repository's issues page. Any Joe/Jane User can file an issue saying "I can't believe you're not doing XYZ, you're all lame!" because they thinks XYZ is critical. They may be wrong, or mis-assessing things; or they may be (partially) right, and its resource constraints that prevent XYZ from being realized. But usually this at least points out a valid desire or interest. 

Now, I'm in a different position than any user, doing part-time contractor work for BlazingDB, but I don't only file issues in that capacity. Also, I tend to bite more than I can chew in terms of changes I'd like to see in libcudf; and perhaps this is one of them.

But to your point about making practical suggestions:

* Let's separate the challenge of building from passing a battery of tests. I realize you can't _really_ separate the two, since you can obviously build something the wrong way and come up against runtime errors; but a well-though-out multi-distro/multi-platform build, even without multi-platform tests, is going more than half way towards support for those distros/platforms. A GPU is not (or should not) be necessary to build our code - just an installation of the CUDA toolkit. And it will not be susceptible to issues with the driver, or the kernel-driver interaction. 
* So, as far as building is concerned, GPU support, limited core count and even timeouts are things one can live with (I think). On the other hand, it does seem Travis CI only offers some Ubuntu distributions, and not even the latest one. I wonder if it can have CUDA installed on Windows and MacOS instances - it might at least help with noticing build issues there.
* We could try to rely on the user base. Of the 1,168 stars and probably thousands of users, I'm guessing mroe than a few build this on non-Ubuntu systems. We could think of ways to solicit bug reports from them - and here it can be both w.r.t. the build and w.r.t. passing the tests. Doing this too is not at all trivial, but we could at least have such a solicitation on the repository's README.md
