### ISSUE TITLE
[FEA] Parquet support for reading binary and repeated binary as binary not strings

### ISSUE THREAD

**Issue by tgravescs** [rapidsai/cudf#11044]
**Is your feature request related to a problem? Please describe.**
CUDF supports reading binary from parquet and it automatically reads it as Strings.  See https://github.com/rapidsai/cudf/issues/10733 which fixed this.

We would like to request being able to read binary as binary and not strings. 

**Describe the solution you'd like**
We would like cudf to officially support reading these binary and repeated binary types. Ideally we could support reading binary both as binary and as strings. We could pass in a read schema so the reader would know what to read it is.

**Comment by devavret** [comment]
What is the desired output column type? There isn't a binary type in libcudf right now. If you want it to be read as a `List<uint8>` then it's easy to convert the output string column into it because apart from the metadata, they're the same.

**Comment by tgravescs** [comment]
Sorry did not see your question, yes binary would just be an array of bytes in Spark so List<uint8> would make sense.

**Comment by sameerz** [comment]
Still needed.
