### ISSUE TITLE
[FEA]  Implement `lists::drop_list_duplicates` using `cudf::distinct`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11053]
I just realized that `lists::drop_list_duplicates` can be implemented using `cudf::distinct` by using the following approach:
 1. Peel out child column of the input lists column
 2. Generate labels for the child elements
 3. Add the labels column into the keys table that input into `cudf::distinct`
 4. The output labels of unique elements need to be grouped and maintain their group order, this can be achieved easily by changing `cudf::distinct` to use a gather map generated from a sequence of linear indices.
 5. The labels output from `cudf::distinct` are used to reconstruct the final lists column without duplicates.

Such approach can be implemented if we have `cudf::distinct` supports:
 * `duplicate_keep_option` parameter (https://github.com/rapidsai/cudf/issues/11050), and
 * `nan_equality` parameter, and
 * Step 4 above.

The only concern here is how to enforce step 4 above. Adding parameters is easy, even that is breaking change. Guarantee some internal implementation is more difficult, as devs may accidentally + silently change it. Maybe explicitly writing this into the public interface doxygen and adding unit tests can help.

**Comment by ttnghia** [comment]
Using this approach, my local implementation has only about 50 LOC, instead of >600 LOC as in the current implementation.

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/pull/11149
