### ISSUE TITLE
[BUG] GroupBy Transform return incorrect results

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#11067]
**Describe the bug**
cuDF's groupby transform returns incorrect results

**Steps/Code to reproduce bug**
I have noticed that when the index contains non-consecutive numbers, then cuDF groupby transform returns incorrect results.

**Expected behavior**
cuDF groupby transform should return correct results

**Environment overview (please complete the following information)**
Version cuDF is 22.04.00

**Additional context**
Here is a jupyter notebook to reproduce the error
https://github.com/cdeotte/RAPIDS-development/blob/master/bugs/bug005.ipynb

**Comment by bdice** [comment]
@shwina I think we may be susceptible to this class of error (dropping an input’s index or name when creating the output) in other places too. I caught a similar problem in #10715. If you can determine whether this is (1) not being tested or (2) not being caught by tests, that would be helpful.

**Comment by shwina** [comment]
I verified that #11068 fixes this issue.
