### ISSUE TITLE
[FEA] Use `cudf::distinct` in Python and Java when it has support for `duplicate_keep_option`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11089]
Now `cudf::distinct` is going to support `duplicate_keep_option` (https://github.com/rapidsai/cudf/pull/11052). When that PR is merged, we should update Python and Java sides to use it instead of `cudf::stable_sort_by_key` + `cudf::unique`. This will boost performance from `O(nlogn)` to `O(n)`.

**Comment by vyasr** [comment]
@ttnghia did you have any specific ideas of places where we could leverage this new feature, or do we just need to do a search for usage of `cudf::unique` calls to see where we are sorting first?

**Comment by ttnghia** [comment]
I have done the necessary work for the Java side. For Python, I've started https://github.com/rapidsai/cudf/pull/11230 but then @brandon-b-miller took over it by https://github.com/rapidsai/cudf/pull/11656 which should close this issue.

@brandon-b-miller do you have any update?

**Comment by brandon-b-miller** [comment]
got a little sidetracked but hoping to come back to this this week 👍

**Comment by bdice** [comment]
The Python side is using cudf::stable_distinct as of #11656, which closes half of this issue, but perhaps there is still work needed in Java? @ttnghia Can you offer an update here? Maybe we need to search the JNI or spark-rapids code for “cudf::unique”?

**Comment by ttnghia** [comment]
Thanks @bdice. Java doesn't need `unique` as I'm aware of.
`distinct` has been added to Java binding almost a year ago: https://github.com/rapidsai/cudf/pull/11232.

**Comment by ttnghia** [comment]
So both Java + Python binding have been addressed. I think we can close this.
