### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Mgalaz75** [rapidsai/cudf#11098]
`[]() 
![43337E63-0F80-4F44-9019-944F6F77890D](https://user-images.githubusercontent.com/106450535/173380379-c565f660-f4a2-4207-8223-67e1a8e345c7.jpeg)
**Describe` the bug**

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by vyasr** [comment]
@Mgalaz75 did you intend to report a specific bug with this issue?

**Comment by Mgalaz75** [comment]
Yes
