### ISSUE TITLE
[FEA] Fully support nested types in `lists::drop_list_duplicates`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11093]
Currently `lists::drop_lists_duplicates` can only handle input data of basic types and structs of basic types. As requested by customer(s) (https://github.com/NVIDIA/spark-rapids/issues/5508), we should add full support for nested types into it.

**Comment by sameerz** [comment]
Depends on https://github.com/rapidsai/cudf/issues/11053
