### ISSUE TITLE
[DOC] Add set_allocator to cuDF Python documentation (or deprecate in favor of rmm.reinitialize)

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#11097]
[set_allocator](https://github.com/rapidsai/cudf/blob/4e66281f48c55735edb4b610e0f859ee2de32a75/python/cudf/cudf/utils/utils.py#L193) enables users to set the GPU allocator and configure RMM. It's a wrapper around `rmm.reinitialize`.

We should either add this to the documentation or deprecate it in favor of users directly using `rmm.reinitialize`. [Searching for set_allocator](https://docs.rapids.ai/api/cudf/nightly/search.html?q=set_allocator) in the docs returns no results.

**Comment by shwina** [comment]
`cudf.set_allocator` is a wrapper around `rmm.reinitialize` and I think we should deprecate it in favor of the latter:

- It brings more visibility to RMM, which is good to know about if you are using RAPIDS and care about memory management/performance.
- In code that uses cuDF in combination with other RAPIDS libraries (e.g, cuml), using `cudf.set_allocator()` will implicitly configure memory management for other libraries as well, which feels smelly to me compared to using `rmm.reinitialize()` to configure memory management explicitly for all of RAPIDS.
