### ISSUE TITLE
[BUG] Lots of ops don't set output validity correctly

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1110]
**Describe the bug**
All the gpu binary ops support validity for the input, but never set validity for the output and don't set the null_count.

All the date/time ops assume that if validity is set for the input then validity must be there for the output and don't set the null_count

**Steps/Code to reproduce bug**
Do any binary or date time ops with nulls in the columns.

**Expected behavior**
The nulls are propagated properly and the null count is set properly.

I really would like to see something for unary ops like

```c
if (input->valid == null && input->null_count > 0) {
  return GDF_VALIDITY_MISSING;
}
if (input->null_count > 0 && output->validity == null) {
  return GDF_VALIDITY_MISSING;
} 
if (output->valid) {
  if (input->valid) {
       // Copy over valid mask
  } else {
       // mem set output->valid to all valid 
  }
}

output->null_count = input->null_count;
```

The binary operators are a bit more complex
```c
if (lhs->valid == null && lhs->null_count > 0) {
  return GDF_VALIDITY_MISSING;
}
if (rhs->valid == null && rhs->null_count > 0) {
  return GDF_VALIDITY_MISSING;
}
if ((rhs->null_count > 0 || lhs->null_count > 0) && output->validity == null) {
  return GDF_VALIDITY_MISSING;
}
if (output->valid) {
  if (lhs->valid && hrs->valid) {
       // output->valid = cuda kernel lhs->valid & rhs->valid
       // output->null_count = calculate null count or output->valid
  } else if (lhs->valid) {
      // copy lhs->valid to output->valid
      output->null_count = lhs->null_count;
  } else if (rhs->valid) {
      // copy rhs->valid to output->valid
      output->null_count = rhs->null_count; 
  } else {
       // mem set output->valid to all valid
       output->null_count = 0; 
  }
}
```

Is it expected that we need to do this all ourselves with `gdf_validity_and` and `gdf_count_nonzero_mask`?

**Comment by jrhemstad** [comment]
Yes, the unary ops definitely need to be refactored. (This is some of that embarrassing code I've been talking about when I've said there's a lot that needs to be refactored... :smile: ) 

Luckily, @devavret has already taken care of updating the binary ops and takes care of the null values for you: https://github.com/rapidsai/cudf/pull/892

**Comment by revans2** [comment]
@jrhemstad great to hear it, and I am excited to see some jitting coming in too.

**Comment by devavret** [comment]
I was also trying to refactor unary ops today so expect that soon.
