### ISSUE TITLE
[FEA] Split apart multi output conda recipe

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#11119]
**Is your feature request related to a problem? Please describe.**
As far as I can tell / dig up, there's no mechanism in conda-build to allow building only specific outputs of a recipe. With the changes introduced in #10326 I can no longer build just libcudf, but am forced to build the kafka integration library, tests, and example(s) unnecessarily. 

**Describe the solution you'd like**
I'd like to be able to build a libcudf conda package via the conda recipe without having to build a handful of additional unnecessary things.

**Describe alternatives you've considered**
I can hack the unneeded pieces out of the conda recipe myself, but that's brittle and gross.

**Comment by jakirkham** [comment]
Thanks for the feedback Keith 🙏 Agree this is an important use case

Yeah there are probably ways we can influence this like adding environment variables or variants to optionally build subsets of packages

**Comment by vyasr** [comment]
Migrated to rapidsai/build-planning#61
