### ISSUE TITLE
ppc64le - undefined symbol: _ZN4cudf2io6detail12cufile_input10read_asyncEmmPhN3rmm16cuda_stream_viewE

### ISSUE THREAD

**Issue by rnukala1** [rapidsai/cudf#11111]
I build cuda version of conda package for cuDF(21.10.00a cuda) and also dependent cuda version of conda packages of pyarrow and rmm on ppc64le (POWER) architecture. When I run a  sample with simple "import cudf"  I see the following error

(testcudfp39) [opence@waldevmlcerce04 cudf]$ python cudf_sample2.py
Traceback (most recent call last):
  File "/rcebuild/rajesh/sample_test_programs/rapids/cudf/cudf_sample2.py", line 1, in <module>
    import cudf
  File "/local/opence/anaconda3/envs/testcudfp39/lib/python3.9/site-packages/cudf/__init__.py", line 12, in <module>
    from cudf import api, core, datasets, testing
  File "/local/opence/anaconda3/envs/testcudfp39/lib/python3.9/site-packages/cudf/datasets.py", line 5, in <module>
    from cudf._lib.transform import bools_to_mask
  File "/local/opence/anaconda3/envs/testcudfp39/lib/python3.9/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
ImportError: /local/opence/anaconda3/envs/testcudfp39/lib/python3.9/site-packages/cudf/_lib/../../../../libcudf.so: undefined symbol: _ZN4cudf2io6detail12cufile_input10read_asyncEmmPhN3rmm16cuda_stream_viewE

Below is the package list installed in the conda environment
(testcudfp39) [opence@waldevmlcerce04 cudf]$ conda list
# packages in environment at /local/opence/anaconda3/envs/testcudfp39:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
abseil-cpp                20211102.0           h8ec6b75_0
arrow-cpp                 5.0.0           py39h926b4ae_34_cuda    local
arrow-cpp-proc            3.0.0                      cuda    local
aws-c-common              0.4.57               he6710b0_1
aws-c-event-stream        0.1.6                h29c3540_5
aws-checksums             0.1.9                he6710b0_0
aws-sdk-cpp               1.8.185              h6205695_0
bottleneck                1.3.4            py39hfc2be9b_0
brotli                    1.0.9                he6710b0_2
bzip2                     1.0.8                h7b6447c_0
c-ares                    1.18.1               h140841e_0
ca-certificates           2022.4.26            h6ffa863_0
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2022.5.18.1      py39h6ffa863_0
cudatoolkit               11.2.2               haa41c22_9    rocketce
cudf                      21.10.00a       cuda_11.2_py39_ge05bd4bf3c_345    local
cupy                      10.5.0           py39h0b15df5_0    local
dlpack                    0.5                  h3b9df90_0    conda-forge
fastavro                  1.4.7            py39h140841e_0
fastrlock                 0.6              py39h29c3540_0
fsspec                    2022.3.0         py39h6ffa863_0
gflags                    2.2.2                he6710b0_0
glog                      0.5.0                h29c3540_0
grpc-cpp                  1.36.4          h60f4467_pb3.14_2    rocketce
krb5                      1.19.2               h6205695_0
ld_impl_linux-ppc64le     2.38                 hec883e6_1
libblas                   3.9.0           11_linuxppc64le_openblas    conda-forge
libcblas                  3.9.0           11_linuxppc64le_openblas    conda-forge
libcudf                   21.10.00a       cuda11.2_ge05bd4bf3c_345    local
libcurl                   7.82.0               ha47bf17_0
libedit                   3.1.20210910         h140841e_0
libev                     4.33                 h140841e_1
libevent                  2.1.12               hb567c45_0
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
liblapack                 3.9.0           11_linuxppc64le_openblas    conda-forge
libllvm11                 11.1.0               h621ed2f_1
libnghttp2                1.46.0               hedb86c2_0
libopenblas               0.3.17                        1    rocketce
libprotobuf               3.14.0               h5f94dde_0
librmm                    21.10.00a       cuda11.2_gae27a572_42    local
libssh2                   1.10.0               hb567c45_0
libstdcxx-ng              11.2.0               h1234567_1
libthrift                 0.15.0               heb2aae8_0
libutf8proc               2.6.1                h140841e_0
llvmlite                  0.38.0           py39h5f94dde_0
lz4-c                     1.9.3                h29c3540_1
ncurses                   6.3                  h140841e_2
numba                     0.55.1           py39haab0e66_0
numexpr                   2.8.1            py39h6e379ce_0
numpy                     1.21.3           py39he089932_1    conda-forge
nvtx                      0.2.3            py39ha810350_1    conda-forge
openssl                   1.1.1o               h140841e_0
orc                       1.6.5                hb77ef19_2
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.3.5            py39h724cb3c_0
parquet-cpp               1.5.1                h34088ae_4
pip                       21.2.4           py39h6ffa863_0
protobuf                  3.14.0           py39h29c3540_1
pyarrow                   5.0.0           py39h926b4ae_34_cuda    local
pyparsing                 3.0.4              pyhd3eb1b0_0
python                    3.9.12               h836d2c2_1
python-dateutil           2.8.2              pyhd3eb1b0_0
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1           py39h6ffa863_0
re2                       2022.04.01           h29c3540_0
readline                  8.1.2                h140841e_1
rmm                       21.10.00a       cuda_11.2_py39_gae27a572_42    local
setuptools                61.2.0           py39h6ffa863_0
six                       1.16.0             pyhd3eb1b0_1
snappy                    1.1.9                h29c3540_0
spdlog                    1.10.0               h06f31f1_0    conda-forge
sqlite                    3.38.3               hd7247d8_0
tbb                       2021.5.0             h66086b3_0
tk                        8.6.12               h7e00dab_0
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022a                hda174b7_0
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h140841e_0
zlib                      1.2.12               h140841e_2
zstd                      1.4.9                hc52992f_0

From the documentation of cuda I understood that cuFile is not supported in ppc64le architecture. How can we build the conda package by removing the dependency of cuFile. Quick help on this is appreciated. Thank you.

**Comment by quasiben** [comment]
Can you try with `-DUSE_GDS=ON` (https://github.com/rapidsai/cudf/blob/branch-22.08/build.sh#L169) ?

**Comment by rnukala1** [comment]
Looks like for ppc64le architecture there is no support for cuFile. So, I am not able to install GDS in my power machine. I tried using the argument -DUSE_GDS=ON as well as -DUSE_GDS=OFF and I see the same error.

**Comment by GregoryKimball** [comment]
@rnukala1 is this issue still relevant?

**Comment by vyasr** [comment]
I'm going to close this issue for now, but please reopen it if the issues are still present.
