### ISSUE TITLE
ppc64le - Could NOT find cuFile (missing: cuFile_LIBRARY cuFileRDMA_LIBRARY cuFile_INCLUDE_DIR)

### ISSUE THREAD

**Issue by rnukala1** [rapidsai/cudf#11110]
I am building cudf 21.10 on ppc64le (POWER) architecture with cuda 11.2 enabled. While building libcudf tests using the command "./build.sh libcudf tests" I see the following errors. Can someone quickly help on this? 

/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o: in function `MultibyteSplitTest_LargeInput_Test::TestBody()':
multibyte_split_test.cpp:(.text+0x5138): undefined reference to `cudf::io::text::multibyte_split(cudf::io::text::data_chunk_source const&, std::string const&, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: multibyte_split_test.cpp:(.text+0x5174): undefined reference to `testing::ScopedTrace::PushTrace(char const*, int, std::string)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o: in function `MultibyteSplitTest_NondeterministicMatching_Test::TestBody()':
multibyte_split_test.cpp:(.text+0x56cc): undefined reference to `cudf::io::text::multibyte_split(cudf::io::text::data_chunk_source const&, std::string const&, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: multibyte_split_test.cpp:(.text+0x5704): undefined reference to `testing::ScopedTrace::PushTrace(char const*, int, std::string)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o: in function `MultibyteSplitTest_DelimiterAtEnd_Test::TestBody()':
multibyte_split_test.cpp:(.text+0x5b18): undefined reference to `cudf::io::text::multibyte_split(cudf::io::text::data_chunk_source const&, std::string const&, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: multibyte_split_test.cpp:(.text+0x5b54): undefined reference to `testing::ScopedTrace::PushTrace(char const*, int, std::string)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o: in function `MultibyteSplitTest_OverlappingMatchErasure_Test::TestBody()':
multibyte_split_test.cpp:(.text+0x5f70): undefined reference to `cudf::io::text::multibyte_split(cudf::io::text::data_chunk_source const&, std::string const&, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o: in function `MultibyteSplitTest_HandpickedInput_Test::TestBody()':
multibyte_split_test.cpp:(.text+0x6574): undefined reference to `cudf::io::text::multibyte_split(cudf::io::text::data_chunk_source const&, std::string const&, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: multibyte_split_test.cpp:(.text+0x65b8): undefined reference to `testing::ScopedTrace::PushTrace(char const*, int, std::string)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/io/text/multibyte_split_test.cpp.o:(.data.rel.ro._ZTIN4cudf4test11BaseFixtureE[_ZTIN4cudf4test11BaseFixtureE]+0x10): undefined reference to `typeinfo for testing::Test'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudftestutil.a(column_utilities.cu.o): in function `cudf::test::(anonymous namespace)::get_nested_type_str[abi:cxx11](cudf::column_view const&) [clone .localalias]':
tmpxft_002a5d19_00000000-6_column_utilities.cudafe1.cpp:(.text+0x343c): undefined reference to `cudf::jit::get_type_name[abi:cxx11](cudf::data_type)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: tmpxft_002a5d19_00000000-6_column_utilities.cudafe1.cpp:(.text+0x35b4): undefined reference to `cudf::jit::get_type_name[abi:cxx11](cudf::data_type)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: tmpxft_002a5d19_00000000-6_column_utilities.cudafe1.cpp:(.text+0x3974): undefined reference to `cudf::jit::get_type_name[abi:cxx11](cudf::data_type)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::create_directories(std::filesystem::path const&)@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::_M_split_cmpts()@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::io::detail::cufile_input::read_async(unsigned long, unsigned long, unsigned char*, rmm::cuda_stream_view)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::io::detail::parquet::writer::close(std::string const&)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::string_scalar::string_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, rmm::cuda_stream_view, rmm::mr::device_memory_resource*)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::io::table_input_metadata::table_input_metadata(cudf::table_view const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::jit::ptx_parser::ptx_parser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<int, std::less<int>, std::allocator<int> > const&)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::operator/=(std::filesystem::path const&)@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::_M_append(std::basic_string_view<char, std::char_traits<char> >)@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::io::build_timezone_transition_table(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, rmm::cuda_stream_view)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::jit::parse_single_function_cuda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::jit::ptx_parser::parse[abi:cxx11]()'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::_List::_List(std::filesystem::path::_List const&)@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::string_scalar::to_string[abi:cxx11](rmm::cuda_stream_view) const'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::_List::_Impl_deleter::operator()(std::filesystem::path::_List::_Impl*) const@GLIBCXX_3.4.26'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `cudf::io::convert_string_to_dtype(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/opt/rh/gcc-toolset-10/root/usr/bin/ld: ../libcudf.so: undefined reference to `std::filesystem::path::_List::_List()@GLIBCXX_3.4.26'
collect2: error: ld returned 1 exit status
gmake[2]: *** [tests/CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/build.make:107: gtests/MULTIBYTE_SPLIT_TEST] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:2245: tests/CMakeFiles/MULTIBYTE_SPLIT_TEST.dir/all] Error 2

**Comment by GregoryKimball** [comment]
After live debugging with @rnukala1 from Rocket Software, we resolved the build issue.

When building libcudf, CMake searches for a version of cuFile installed locally on the machine, and if found enables
the logic. The associated symbol `cudf::io::detail::cufile_input::read_async(unsigned long, unsigned long, unsigned char*, rmm::cuda_stream_view)` maps to a virtual function with no implementation no matter the state of GDS. The solution to the problem is to add an implementation for this virtual function to that the symbol can be resolved.

to the file `src/io/utilities/file_io_utilities.hpp`, around line 262. Add:
```
std::future<size_t> read_async(size_t offset,
                               size_t size,
                               uint8_t* dst,
                               rmm::cuda_stream_view stream) override
{
  CUDF_FAIL("Only used to compile without cufile library, should not be called");
}
```
