### ISSUE TITLE
[BUG] cuDF 22.04/build from source

### ISSUE THREAD

**Issue by MoamenMetwali** [rapidsai/cudf#11169]
**Describe the bug**
I am trying to install cuDF in my home directory from source but I am facing the following issue:
[ 98%] Linking CXX shared library libcudf.so
/binutils/2.35-GCCcore-10.2.0/bin/ld.gold: error: /cudf-22.04.00/cpp/build/fatbin.ld: SECTIONS seen after er input files; try -T/--script
/binutils/2.35-GCCcore-10.2.0/bin/ld.gold: internal error in write_sections, at reloc.cc:790

**Steps/Code to reproduce bug**
Loading the following modules:
CUDA 11.5
Python 3.8
spdlog
git
Cmake 3.20.1
using the following command to build from source
./build.sh --cmake-args=\"-DCUDF_ENABLE_ARROW_S3=OFF\" libcudf cudf

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Environment details**
***OS Information***
     Cluster Manager v9.0
     master
     NAME="Red Hat Enterprise Linux Server"
     VERSION="7.7 (Maipo)"
     ID="rhel"
     ID_LIKE="fedora"
     VARIANT="Server"
     VARIANT_ID="server"
     VERSION_ID="7.7"
     PRETTY_NAME="Red Hat Enterprise Linux"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
     HOME_URL="https://www.redhat.com/"
     BUG_REPORT_URL="https://bugzilla.redhat.com/"

     REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
     REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
     REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
     REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
     Red Hat Enterprise Linux Server release 7.7 (Maipo)
     Red Hat Enterprise Linux Server release 7.7 (Maipo)
     Linux mgmtnode 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
print_env.sh: line 25: nvidia-smi: command not found

***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                40
     On-line CPU(s) list:   0-39
     Thread(s) per core:    1
     Core(s) per socket:    20
     Socket(s):             2
     NUMA node(s):          4
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz
     Stepping:              7
     CPU MHz:               2100.000
     BogoMIPS:              4200.00
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              28160K
     NUMA node0 CPU(s):     0,4,8,12,16,20,24,28,32,36
     NUMA node1 CPU(s):     1,5,9,13,17,21,25,29,33,37
     NUMA node2 CPU(s):     2,6,10,14,18,22,26,30,34,38
     NUMA node3 CPU(s):     3,7,11,15,19,23,27,31,35,39

**Comment by quasiben** [comment]
> print_env.sh: line 25: nvidia-smi: command not found

This looks like the cuda driver and cudtoolkit aren't installed correctly on your machine.  Can you verify that they are ? Also, can you post the error during build ?

**Comment by MoamenMetwali** [comment]
> > print_env.sh: line 25: nvidia-smi: command not found
> 
> This looks like the cuda driver and cudtoolkit aren't installed correctly on your machine. Can you verify that they are ? Also, can you post the error during build ?

I've made sure the cuda module is loaded and it's detected during the building process:

> -- Found CUDA: /cm/shared/ebtree/software/CUDA/11.5.0 (found version "11.5")

and these are the error thrown during the building process:

> /binutils/2.35-GCCcore-10.2.0/bin/ld.gold: error: /cudf-22.04.00/cpp/build/fatbin.ld: SECTIONS seen after other input files; try -T/--script
> /binutils/2.35-GCCcore-10.2.0/bin/ld.gold: internal error in write_sections, at reloc.cc:790
> collect2: error: ld returned 1 exit status
> gmake[2]: *** [libcudf.so] Error 1
> gmake[1]: *** [CMakeFiles/cudf.dir/all] Error 2
> gmake: *** [all] Error 2

**Comment by vyasr** [comment]
I think this is an error with your linker. Can you try installing a standard version of binutils rather than the binutils-gold that you're currently using (as evidenced by the `ld.gold` in the command)?

**Comment by vyasr** [comment]
[Here's an example of the same error popping up in a similar context](https://forums.developer.nvidia.com/t/sections-seen-after-other-input-files/133441).

**Comment by MoamenMetwali** [comment]
> I think this is an error with your linker. Can you try installing a standard version of binutils rather than the binutils-gold that you're currently using (as evidenced by the `ld.gold` in the command)?

Thank you,
I've already tried multiple binutils release (2.32-2.35-2.36-2.38) and all of them lead to the same result.
All of them have gold linker in the bin dir "ld.gold".

**Comment by MoamenMetwali** [comment]
Any other ideas? the issue still exists.

**Comment by MoamenMetwali** [comment]
I used the linker in /usr/bin and unloaded 'binutils'
That was the output

> - Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /GCCcore/10.2.0/bin/cc
-- Check for working C compiler: /GCCcore/10.2.0/bin/cc - broken
CMake Error at /CMake/3.20.1-GCCcore-10.2.0/share/cmake-3.20/Modules/CMakeTestCCompiler.cmake:66 (message):
  The C compiler

    "/GCCcore/10.2.0/bin/cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /cudf/cpp/build/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_a76de/fast && gmake: Warning: File `Makefile' has modification time 1.3 s in the future
    /usr/bin/gmake  -f CMakeFiles/cmTC_a76de.dir/build.make CMakeFiles/cmTC_a76de.dir/build
    gmake[1]: Entering directory `/cpp/build/CMakeFiles/CMakeTmp'
    gmake[1]: Warning: File `CMakeFiles/cmTC_a76de.dir/flags.make' has modification time 1.3 s in the future
    Building C object CMakeFiles/cmTC_a76de.dir/testCCompiler.c.o
    /GCCcore/10.2.0/bin/cc    -o CMakeFiles/cmTC_a76de.dir/testCCompiler.c.o -c /cpp/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Linking C executable cmTC_a76de
    /CMake/3.20.1-GCCcore-10.2.0/bin/cmake -E cmake_link_script CMakeFiles/cmTC_a76de.dir/link.txt --verbose=1
    /GCCcore/10.2.0/bin/cc CMakeFiles/cmTC_a76de.dir/testCCompiler.c.o -o cmTC_a76de
    /usr/bin/ld.gold: --push-state: unknown option
    /usr/bin/ld.gold: use the --help option for usage information
    collect2: error: ld returned 1 exit status
    gmake[1]: *** [cmTC_a76de] Error 1
    gmake[1]: Leaving directory `/cpp/build/CMakeFiles/CMakeTmp'
    gmake: *** [cmTC_a76de/fast] Error 2

**Comment by vyasr** [comment]
Hmm I'm not quite sure what to recommend here. It seems like your compiler toolchain simply isn't working correctly. Can you successfully compile a simple C/C++ program? What about a CUDA program? For instance, does hello world compile for you with your `cc` compiler?
```
#include <stdio.h>
int main() {
    printf("Hello world\n");
}
```

If so, what about nvcc compiling a simple example like this:
```
#include <iostream>

__global__ void square(int* array, int n) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;
    if (tid < n) {
        array[tid] = array[tid] * array[tid];
    }
}

int main() {
    auto const N = 10;
    auto const N_bytes = 10 * sizeof(int);
    int h_x[N];
    int *d_x;
    cudaMalloc((void **)&d_x, N_bytes);

    for (int i = 0; i < 10; ++i) {
        h_x[i] = i;
    }

    cudaMemcpy(d_x, h_x, N_bytes, cudaMemcpyHostToDevice);

    square<<<1, 10>>>(d_x, 10);
    cudaDeviceSynchronize();

    cudaMemcpy(h_x, d_x, N_bytes, cudaMemcpyDeviceToHost);

    for (size_t i = 0; i < 10; ++i) {
        std::cout << h_x[i] << ", ";
    }
    std::cout << std::endl;
}
```

**Comment by MoamenMetwali** [comment]
> Hmm I'm not quite sure what to recommend here. It seems like your compiler toolchain simply isn't working correctly. Can you successfully compile a simple C/C++ program? What about a CUDA program? For instance, does hello world compile for you with your `cc` compiler?
> 
> ```
> #include <stdio.h>
> int main() {
>     printf("Hello world\n");
> }
> ```
> 
> If so, what about nvcc compiling a simple example like this:
> 
> ```
> #include <iostream>
> 
> __global__ void square(int* array, int n) {
>     int tid = blockDim.x * blockIdx.x + threadIdx.x;
>     if (tid < n) {
>         array[tid] = array[tid] * array[tid];
>     }
> }
> 
> int main() {
>     auto const N = 10;
>     auto const N_bytes = 10 * sizeof(int);
>     int h_x[N];
>     int *d_x;
>     cudaMalloc((void **)&d_x, N_bytes);
> 
>     for (int i = 0; i < 10; ++i) {
>         h_x[i] = i;
>     }
> 
>     cudaMemcpy(d_x, h_x, N_bytes, cudaMemcpyHostToDevice);
> 
>     square<<<1, 10>>>(d_x, 10);
>     cudaDeviceSynchronize();
> 
>     cudaMemcpy(h_x, d_x, N_bytes, cudaMemcpyDeviceToHost);
> 
>     for (size_t i = 0; i < 10; ++i) {
>         std::cout << h_x[i] << ", ";
>     }
>     std::cout << std::endl;
> }
> ```

I've compiled the first code using GCCcore10.2.0 and nothing went wrong.
The same for the second code using CUDA 11.5.0.
Both codes were compiled successfully.

**Comment by vyasr** [comment]
@robertmaynard do you have any other ideas what could cause this? I didn't have any further ideas here, but it seemed to me to be very likely due to some issue with the local build toolchain.

**Comment by robertmaynard** [comment]
CMake invokes the compiler ( `nvcc` or `g++` ) for the link step and not `ld` directly. I agree that explicitly requesting a non-gold linker should fix the issue. 

In this case we would be looking at something like ( after fully deleting the build directory at cpp/build )

```cmake
./build.sh ....... --cmake-args="-DCMAKE_CUDA_FLAGS=\"-fuse-ld=ld\""
```

**Comment by GregoryKimball** [comment]
Hello @MoamenMetwali, thank you for raising this issue. Please feel free to reopen if you are having trouble with our latest release. Also I recommend checking out our [devel docker](https://hub.docker.com/r/rapidsai/rapidsai-dev/tags) images, so that you can reference a working build environment.
