### ISSUE TITLE
[FEA] Add write_json method to cudf/io/json.hpp

### ISSUE THREAD

**Issue by dagardner-nv** [rapidsai/cudf#11165]
**Is your feature request related to a problem? Please describe.**
Currently the only method for serializing a cudf dataframe to json requires acquiring the Python GIL.

cudf/io/json.hpp contains a `read_json` method, and the corresponding `csv.hpp` header contains both  `read_csv` and `write_csv` methods.

**Describe the solution you'd like**
Add a `write_json` method which is callable from C++ and does not require the Python GIL.

**Describe alternatives you've considered**
Currently we have to use the Python API from C++:
https://github.com/nv-morpheus/Morpheus/blob/branch-22.08/morpheus/_lib/src/io/serializers.cpp#L109

**Additional context**
This would be a big performance win for us to not require the GIL in our serialize stage.

**Comment by GregoryKimball** [comment]
Thank you @dagardner-nv for sharing this request. Currently our main JSON focus is on reading arbitrarily-nested data types ([Nested JSON reader](https://github.com/rapidsai/cudf/milestone/13)). 

Writing JSON is complex because there are several common ways to represent tabular data in JSON. Would you please review the `orient` argument in `pandas.read_json` and share which convention would match your use case?

**Comment by dagardner-nv** [comment]
@GregoryKimball thanks, and yes for the purposes of Morpheus most of the time by the time we get around to writing it the data would be flat.

I wonder if it could be possible to do something like:
```
if is_simple(df):
    use_cpp_impl(df)
else:
    # Use current impl
```

**Comment by GregoryKimball** [comment]
Hello @chinmaychandak, would this `to_json` feature be useful for your work in Kratos?

**Comment by chinmaychandak** [comment]
Thanks for pointing me to this @GregoryKimball! 

Yes, `to_json` without acquiring the Python GIL would be super amazing for both overall performance like David mentioned as well as for streaming computations involving multiple layers of transformations and while writing serialized data back to sinks like Kafka/S3 from cuStreamz pipelines.

**Comment by jsmaupin** [comment]
Nothing to add from me.  I agree with @chinmaychandak 's comments.
