### ISSUE TITLE
"Relative/percentage" distance version of cudf.core.column.string.StringMethods.edit_distance[FEA]

### ISSUE THREAD

**Issue by lightsailpro** [rapidsai/cudf#11172]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]

Sometime we need to use the "relative" distance instead of current edit distance since s1 and s2 string length can be quite different. "edit distance" = 1 between two small strings and two large strings is not necessarily comparable.

**Describe the solution you'd like**

The following formula will calculate the relative distance
(max(len(s1), len(s2)) - edit_distance ) / max(len(s1), len(s2))

**Describe alternatives you've considered**

Calculating relative distance outside cudf can be very slow.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by beckernick** [comment]
Are you able to do this after the fact using the formula you've provided? You can use `Series.str.len()` to get the lengths of each string.

**Comment by lightsailpro** [comment]
@beckernick Thanks for the suggestion. I tried but could not do it efficiently as current function. I have more than 1 million strings to compare with each other on two v100 GPUs using dask_cudf. Could not use edit_distance_matrix because the result matrix is just too large, which generates error. With edit_distance by looping / comparing 1 string against 1 million each time, I feel that I will need to loop through the resulted series to calculate the relative distance of this string against the rest, which will be very slow, unless there is more efficient way. 

Also, for the edit_distance_matrix, if we have a "relative" distance version, and also allow filtering the returned result with the relative distance e.g. > 80% using some kind of sparse matrix format, then I will be able to use single call to finish the calculation.

**Comment by davidwendt** [comment]
Does this work?
```
>>> import cudf
>>> s1 = cudf.Series(["apple", "banana", "orange", "pear"])
>>> s2 = cudf.Series(["snapple", "minion", "black", "peach"])
>>> ed = s1.str.edit_distance(s2)
0    2
1    5
2    5
3    2
dtype: int32
>>> l1 = s1.str.len()
>>> l2 = s2.str.len()
>>> df = cudf.DataFrame({"l1":l1, "l2":l2})
   l1  l2
0   5   7
1   6   6
2   6   5
3   4   5
>>> mx = df.max(axis=1)
0    7
1    6
2    6
3    5
dtype: int32
>>> r = (mx - ed) / mx
0    0.714286
1    0.166667
2    0.166667
3    0.600000
dtype: float64
```
