### ISSUE TITLE
CUDF cannot import[BUG]

### ISSUE THREAD

**Issue by xiaogangzhu** [rapidsai/cudf#11185]
**Describe the bug**
cannot import cudf

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.
I install cudf on my local machine using conda, but when I try 
import cudf, it produce following error:
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tstone10/anaconda3/envs/rapids-22.06/lib/python3.8/site-packages/cudf/__init__.py", line 5, in <module>
    validate_setup()
  File "/home/tstone10/anaconda3/envs/rapids-22.06/lib/python3.8/site-packages/cudf/utils/gpu_utils.py", line 20, in validate_setup
    from rmm._cuda.gpu import (
  File "/home/tstone10/anaconda3/envs/rapids-22.06/lib/python3.8/site-packages/rmm/__init__.py", line 16, in <module>
    from rmm import mr
  File "/home/tstone10/anaconda3/envs/rapids-22.06/lib/python3.8/site-packages/rmm/mr.py", line 14, in <module>
    from rmm._lib.memory_resource import (
  File "/home/tstone10/anaconda3/envs/rapids-22.06/lib/python3.8/site-packages/rmm/_lib/__init__.py", line 15, in <module>
    from .device_buffer import DeviceBuffer
  File "device_buffer.pyx", line 1, in init rmm._lib.device_buffer
TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))

**Expected behavior**
import cudf successfully

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - local machine
 - 
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
conda install using following command 
conda create -n rapids-22.06 -c rapidsai -c nvidia -c conda-forge  \
    cudf=22.06 python=3.8 cudatoolkit=11.2 \
    jupyterlab
**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
My local machine has cuda 11.2 installed, and nvidia Quadro P4000.
Successfully run on tensorflow but cannot import cudf

**Comment by beckernick** [comment]
Could you run `conda list cuda-python` and share the output?

**Comment by alex-btc** [comment]
I have the exact same problem when installing a new RAPIDS env on Ubuntu 20.04, with the error `TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))` when importing `cudf`.

I suspect it has something to do with nvidia rotating GPG repo keys: https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/

But even though I followed all instructions above, I cannot import none of the rapids libraries.

Any help is appreciated!

**Comment by alex-btc** [comment]
> Could you run `conda list cuda-python` and share the output?

My `conda list cuda-python` output:

`Name                    Version                   Build  Channel`
`cuda-python               11.7.1           py39h3fd9d12_0    nvidia`

I last inslalled cuda 11.7, but I tryed installing all cuda versions since 11.0 and creating conda envs with apropriate cuda and python versions, and nothing worked, the above error persist.

**Comment by beckernick** [comment]
Some changes in CUDA-Python 11.7.1 are causing compatibility issues across RAPIDS libraries and we're working to resolve them.

In the meantime, if you downgrade cuda-python to 11.7.0 things should work. `conda install -c nvidia cuda-python=11.7.0`

**Comment by alex-btc** [comment]
> 

Wonderful, that worked flawlessly, thanks a lot!

**Comment by xiaogangzhu** [comment]
My `conda list cuda-python` output:
`# packages in environment at /home/tstone10/anaconda3/envs/rapids-22.06:
#
# Name                    Version                   Build  Channel
cuda-python               11.7.1           py38h3fd9d12_0    nvidia
`
I also install cuda 11.2 for tensorflow, and when I run `nvcc -V` the output is
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Feb_14_21:12:58_PST_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
`
So are we using the nvidia-smi version cuda or the cuda 11.2 version I installed? I only see cuda 11.7 on my machine when I type `nvidia-smi`

**Comment by beckernick** [comment]
This should be resolved with the release of [v22.06.01](https://anaconda.org/rapidsai/cudf), which is now automatically chosen when installing v22.06.
