### ISSUE TITLE
[QST] How to port this piece of code

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1121]
**What is your question?**
Hi,

I am porting a few notebooks to RAPIDS, and I have not been able to find a workaround for the following code templates.

Example 1:
```
file_agg = file_df_tmp.groupby(['user','timestep'])\
                        .agg(OrderedDict([\
                                         ('date',min),\
                                         ('activity','size'),\
                                         ('pc',lambda x:list(x)),\
                                         ('id',lambda x:list(x)),\
                                         ('content',lambda x: ' '.join(str(x)))\
                                         ]))\
                        .reset_index()
file_agg.columns = ['user','timestep','file_min_date','file_count','file_pcs','file_ids','file_content']

```
Example 2:
```
email_pagg = email_pdf.groupby('user')\
     .agg(OrderedDict([\
             ('pc',lambda x:list(x)),\
              ]))\
      .reset_index()
```

Thanks!
Miguel

**Comment by kkraus14** [comment]
@miguelangel Unfortunately it looks like this is using nested types which aren't supported yet. In particular these three aggregations are expecting to work on some form of iterable:
```
                                         ('pc',lambda x:list(x)),\
                                         ('id',lambda x:list(x)),\
                                         ('content',lambda x: ' '.join(str(x)))\
```

**Comment by randerzander** [comment]
@miguelangel were you able to come up with a suitable workaround using the upcoming string support, or other?

We don't plan to support nested types for awhile.

**Comment by miguelangel** [comment]
Hi @randerzander,

I managed to create a container based on 0.6 branch, and merged @kkraus14 `fea-ext-string-support` work.

It let me continue on those areas of the code where string support was needed. Unfortunately, I still need to find a workaround for that part of code.

I will keep you posted my the progress. 

Regards,
Miguel
