### ISSUE TITLE
[BUG] Move `_detail` in `rolling/` to `rolling/detail`

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#11211]
The contents of `cpp/src/rolling/` are a mix of `_detail` files that are private to implementation. This includes `rolling_detail.hpp`, `rolling_detail.cuh`, and an assortment of aggregation-specific files.
It would be best to follow the custom that other modules are using, and putting these under `cpp/src/rolling/detail`.

**Comment by mythrocks** [comment]
A reference implementation is available on the following branch:
https://github.com/mythrocks/cudf/tree/rolling-detail-move

**Comment by mythrocks** [comment]
@vyasr, sorry, mate. I've tagged you on the PR. :]

**Comment by vyasr** [comment]
How kind of you :slightly_smiling_face:
