### ISSUE TITLE
[FEA] Support compilation on Mac OSX

### ISSUE THREAD

**Issue by drbh** [rapidsai/cudf#1123]
**Describe the bug**
Cannot install on Mac OSX 10.14.3

```
Cuda compilation tools, release 10.1, V10.1.105
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
```

<img width="802" alt="screen shot 2019-03-06 at 1 05 49 pm" src="https://user-images.githubusercontent.com/9896130/53903118-da70f100-4010-11e9-8e1c-68601fa61270.png">

Why do I error out at 22% every-time I run `make -j`?

**Steps/Code to reproduce bug**
Following the install instructions on the README

**Comment by kkraus14** [comment]
@drbh We do not yet support Mac OSX or CUDA 10.1.

**Comment by drbh** [comment]
I was hoping to build it locally despite it not being supported yet. What are the blockers before it is ready for OSX distribution? I would love to help in any way possible - this is a great project!

**Comment by kkraus14** [comment]
> I was hoping to build it locally despite it not being supported yet. What are the blockers before it is ready for OSX distribution? I would love to help in any way possible - this is a great project!

I don't think anyone has a strong idea as no one has really investigated as of yet. If you could try with CUDA 10.0 and report back your issues that would be great.

**Comment by harrism** [comment]
I investigated a while back when I had a mac with a CUDA GPU. But now the fact that Apple doesn't make Macs with GPUs makes me hesitant to try again, unless I can get access to an eGPU.

**Comment by kkraus14** [comment]
https://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html#system-requirements

CUDA 10.2 is the last release to support Mac, so I don't think it makes sense for us to invest effort into supporting it.

**Comment by drbh** [comment]
guess I'll need to stick to a linux box for now. Thanks everyone for the feedback
