### ISSUE TITLE
[BUG] ContiguousSplitUntypedTest fails when run with the arena allocator

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#11249]
**Describe the bug**
ContiguousSplitUntypedTest fails when run with the arena allocator but passes when run with the pool or cuda allocators:
```
[ RUN      ] ContiguousSplitUntypedTest.CalculationOverflow
unknown file: Failure
C++ exception with description "std::bad_alloc: out_of_memory: RMM failure at:/home/jlowe/src/spark-rapids-jni/thirdparty/cudf/cpp/build/_deps/rmm-src/include/rmm/mr/device/arena_memory_resource.hpp:159: Maximum pool size exceeded" 
thrown in the test body.
[  FAILED  ] ContiguousSplitUntypedTest.CalculationOverflow (8 ms)
```

**Steps/Code to reproduce bug**
Run `cpp/build/gtests/COPYING_TEST --rmm_mode=arena`

**Expected behavior**
Tests should pass with any supported RMM memory resource.

**Comment by davidwendt** [comment]
This appears to be an out of memory error which is not a problem with the algorithm. The `COPYING_TEST` runs fine on my 48GB GPU with the arena allocator. The max memory required for `COPYING_TEST` appears to be about 25GB with the arena allocator.
Was is the GPU stats where this error occurs? Can you run this on a larger GPU?

**Comment by jlowe** [comment]
I ran this on a 16GB V100, so I guess if tests are expected to require more than that this is "working as designed."  However it seems a bit excessive to need that much memory for a test.

**Comment by davidwendt** [comment]
I agree. Actually, I don't think we should have this specific gtest. I'm inclined to disable it or remove it altogether.
