### ISSUE TITLE
[BUG?] `concat([<Series>], axis=1)` results in a series, not a dataframe

### ISSUE THREAD

**Issue by honno** [rapidsai/cudf#11244]
When using `cudf.concat(axis=1)` on a list containing just one series, a series is returned instead of a dataframe.

```python
>>> import cudf
>>> out1 = cudf.concat([cudf.Series([7, 42, 3])], axis=1)
>>> out1
0     7
1    42
2     3
dtype: int64
>>> type(out1)
cudf.core.series.Series
```

This is contrary to pandas behaviour

```python
>>> import pandas as pd
>>> out2 = pd.concat([pd.Series([7, 42, 3])], axis=1)
>>> out2
    0
0   7
1  42
2   3
>>> type(out2)
pandas.core.frame.DataFrame
```

I'm not even sure if this is a bug (or indeed on purpose), but thought I'd note this behaviour. My use case for this behaviour is just it's nice to write generalised logic for combining 0-to-many series into a dataframe, but definitely not a biggie.

Apologies if this is already known, did take a look at related issues but might of missed something :sweat_smile: 

**Environment overview**
 - Environment location: locally, Ubuntu 20.04.4
 - Method of cuDF install: conda via `rapidsai-nightly`
 - cudf version: `22.08.00a+213.g002cb1c45b`

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 8b3ae33c2874025c29c3747de1c3254eac516f9f (HEAD -> main, origin/main)
     Author: Matthew Barber <quitesimplymatt@gmail.com>
     Date:   Tue Jul 12 09:58:38 2022 +0100
     
     `--max-examples` flag, skip specific flaky cases on CI
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.4 LTS"
     NAME="Ubuntu"
     VERSION="20.04.4 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.4 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux honno-pc 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Jul 12 14:43:34 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 515.48.07    Driver Version: 515.48.07    CUDA Version: 11.7     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
     | 40%   54C    P8    20W / 170W |   1312MiB / 12288MiB |      2%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A      1180      G   /usr/lib/xorg/Xorg                 35MiB |
     |    0   N/A  N/A      1865      G   /usr/lib/xorg/Xorg                135MiB |
     |    0   N/A  N/A      2019      G   /usr/bin/gnome-shell               66MiB |
     |    0   N/A  N/A      2480      G   /usr/lib/firefox/firefox          130MiB |
     |    0   N/A  N/A     10214      G   ...veSuggestionsOnlyOnDemand       68MiB |
     |    0   N/A  N/A     62041      C   ...3/envs/cudf/bin/python3.9      431MiB |
     |    0   N/A  N/A     65091      C   ..._playground/bin/python3.9      431MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   39 bits physical, 48 bits virtual
     CPU(s):                          12
     On-line CPU(s) list:             0-11
     Thread(s) per core:              2
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           165
     Model name:                      Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
     Stepping:                        5
     CPU MHz:                         2900.000
     CPU max MHz:                     4300.0000
     CPU min MHz:                     800.0000
     BogoMIPS:                        5799.77
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        1.5 MiB
     L3 cache:                        12 MiB
     NUMA node0 CPU(s):               0-11
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
     Vulnerability L1tf:              Not affected
     Vulnerability Mds:               Not affected
     Vulnerability Meltdown:          Not affected
     Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
     Vulnerability Srbds:             Mitigation; Microcode
     Vulnerability Tsx async abort:   Not affected
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp pku ospke md_clear flush_l1d arch_capabilities
     
     ***CMake***
     /snap/bin/cmake
     cmake version 3.23.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-11.7/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2022 NVIDIA Corporation
     Built on Tue_May__3_18:49:52_PDT_2022
     Cuda compilation tools, release 11.7, V11.7.64
     Build cuda_11.7.r11.7/compiler.31294372_0
     
     ***Python***
     /home/honno/anaconda3/envs/cudf_playground/bin/python
     Python 3.9.13
     
     ***Environment Variables***
     PATH                            : /home/honno/anaconda3/envs/cudf_playground/bin:/home/honno/anaconda3/condabin:/usr/local/cuda-11.7/bin:/home/honno/.pyenv/shims:/home/honno/.pyenv/bin:/home/honno/go/bin:/usr/local/go/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/honno/.dotnet/tools
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/honno/anaconda3/envs/cudf_playground
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/honno/anaconda3/condabin/conda
     # packages in environment at /home/honno/anaconda3/envs/cudf_playground:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       2_gnu    conda-forge
     abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
     arrow-cpp                 8.0.0           py39h2f48f8a_4_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     asttokens                 2.0.5                    pypi_0    pypi
     aws-c-cal                 0.5.11               h95a6274_0    conda-forge
     aws-c-common              0.6.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
     aws-c-io                  0.10.5               hfb6a706_0    conda-forge
     aws-checksums             0.1.11               ha31a3da_7    conda-forge
     aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
     backcall                  0.2.0                    pypi_0    pypi
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.18.1               h7f98852_0    conda-forge
     ca-certificates           2022.6.15            ha878542_0    conda-forge
     cachetools                5.0.0              pyhd8ed1ab_0    conda-forge
     cuda-python               11.7.0           py39h5a03fae_0    conda-forge
     cudatoolkit               11.7.0              hd8887f6_10    conda-forge
     cudf                      22.08.00a220712 cuda_11_py39_g002cb1c45b_213    rapidsai-nightly
     cupy                      10.6.0           py39hc3c280e_0    conda-forge
     decorator                 5.1.1                    pypi_0    pypi
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     executing                 0.8.3                    pypi_0    pypi
     fastavro                  1.5.2            py39hb9d737c_0    conda-forge
     fastrlock                 0.8              py39h5a03fae_2    conda-forge
     fsspec                    2022.5.0           pyhd8ed1ab_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.6.0                h6f12383_0    conda-forge
     grpc-cpp                  1.45.2               h3b8df00_4    conda-forge
     ipython                   8.4.0                    pypi_0    pypi
     jedi                      0.18.1                   pypi_0    pypi
     keyutils                  1.6.1                h166bdaf_0    conda-forge
     krb5                      1.19.3               h3790be6_0    conda-forge
     ld_impl_linux-64          2.38                 h1181459_1
     libblas                   3.9.0           15_linux64_openblas    conda-forge
     libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
     libbrotlidec              1.0.9                h166bdaf_7    conda-forge
     libbrotlienc              1.0.9                h166bdaf_7    conda-forge
     libcblas                  3.9.0           15_linux64_openblas    conda-forge
     libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
     libcudf                   22.08.00a220712 cuda11_g002cb1c45b_213    rapidsai-nightly
     libcurl                   7.83.1               h7bff187_0    conda-forge
     libedit                   3.1.20210910         h7f8727e_0
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               h9b69904_4    conda-forge
     libffi                    3.4.2                h7f98852_5    conda-forge
     libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
     libgfortran-ng            12.1.0              h69a702a_16    conda-forge
     libgfortran5              12.1.0              hdcd56e2_16    conda-forge
     libgomp                   12.1.0              h8d9b700_16    conda-forge
     libgoogle-cloud           1.40.2               habd0e3a_0    conda-forge
     liblapack                 3.9.0           15_linux64_openblas    conda-forge
     libllvm11                 11.1.0               hf817b99_3    conda-forge
     libnghttp2                1.47.0               h727a467_0    conda-forge
     libnsl                    2.0.0                h7f98852_0    conda-forge
     libopenblas               0.3.20          pthreads_h78a6416_0    conda-forge
     libprotobuf               3.20.1               h6239696_0    conda-forge
     librmm                    22.08.00a220712 cuda11_g5ac89d17_57    rapidsai-nightly
     libssh2                   1.10.0               ha56f1ee_2    conda-forge
     libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
     libthrift                 0.16.0               h519c5ea_1    conda-forge
     libutf8proc               2.7.0                h7f98852_0    conda-forge
     libuuid                   2.32.1            h7f98852_1000    conda-forge
     libzlib                   1.2.12               h166bdaf_1    conda-forge
     llvmlite                  0.38.1           py39h7d9a04d_0    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
     matplotlib-inline         0.1.3                    pypi_0    pypi
     ncurses                   6.3                  h27087fc_1    conda-forge
     numba                     0.55.2           py39h66db6d7_0    conda-forge
     numpy                     1.22.4           py39hc58783e_0    conda-forge
     nvtx                      0.2.3            py39h3811e60_1    conda-forge
     openssl                   1.1.1q               h166bdaf_0    conda-forge
     orc                       1.7.5                h6c59b99_0    conda-forge
     packaging                 21.3               pyhd8ed1ab_0    conda-forge
     pandas                    1.4.3            py39h1832856_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.8.3                    pypi_0    pypi
     pexpect                   4.8.0                    pypi_0    pypi
     pickleshare               0.7.5                    pypi_0    pypi
     pip                       22.1.2             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.30                   pypi_0    pypi
     protobuf                  3.20.1           py39h5a03fae_0    conda-forge
     ptxcompiler               0.4.0            py39h1eff087_0    conda-forge
     ptyprocess                0.7.0                    pypi_0    pypi
     pure-eval                 0.2.2                    pypi_0    pypi
     pyarrow                   8.0.0           py39h1ed2e5d_4_cuda    conda-forge
     pyflakes                  2.4.0                    pypi_0    pypi
     pyflyby                   1.7.7                    pypi_0    pypi
     pygments                  2.12.0                   pypi_0    pypi
     pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
     python                    3.9.13          h9a8a25e_0_cpython    conda-forge
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python_abi                3.9                      2_cp39    conda-forge
     pytz                      2022.1             pyhd8ed1ab_0    conda-forge
     re2                       2022.06.01           h27087fc_0    conda-forge
     readline                  8.1.2                h0f457ee_0    conda-forge
     rmm                       22.08.00a220712 cuda11_py39_g5ac89d17_57    rapidsai-nightly
     s2n                       1.0.10               h9b69904_0    conda-forge
     setuptools                63.1.0           py39hf3d152e_0    conda-forge
     six                       1.16.0             pyh6c4a22f_0    conda-forge
     snappy                    1.1.9                hbd366e4_1    conda-forge
     spdlog                    1.8.5                h4bd325d_1    conda-forge
     sqlite                    3.39.0               h4ff8645_0    conda-forge
     stack-data                0.3.0                    pypi_0    pypi
     tk                        8.6.12               h27826a3_0    conda-forge
     traitlets                 5.3.0                    pypi_0    pypi
     typing_extensions         4.3.0              pyha770c72_0    conda-forge
     tzdata                    2022a                h191b570_0    conda-forge
     wcwidth                   0.2.5                    pypi_0    pypi
     wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     zlib                      1.2.12               h166bdaf_1    conda-forge
     zstd                      1.5.2                h8a70e8d_2    conda-forge
     
</pre></details>

**Comment by shwina** [comment]
Thanks for reporting! Definitely a bug :)
