### ISSUE TITLE
Add a pre-commit hook to verify that we don't introduce DeprecationWarning

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#11251]
We want to always use `FutureWarning` to broadcast deprecations, not `DeprecationWarning`. [@mroeschke suggested a pre-commit hook for this purpose](https://github.com/rapidsai/cudf/pull/11235#discussion_r919180337). It should be a straightforward bash command like 
```
if [[ `grep DeprecationWarning $FILE | wc -l` -gt 0 ]]; then
    exit 1
fi
exit 0
```
(not checked for syntactic correctness).

**Comment by wence-** [comment]
pre-commit has a `pygrep` hook builtin, so perhaps even simpler.
