### ISSUE TITLE
[BUG] Very slow join performance

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1127]
So I'm looking at the performance of indexed joins (cc @randerzander ) and I'm finding that these lines 

https://github.com/rapidsai/cudf/blob/214fba57307e9f4422556d1cb897bf3cf6454bad/python/cudf/dataframe/dataframe.py#L1438-L1439

Are calling this

https://github.com/rapidsai/cudf/blob/214fba57307e9f4422556d1cb897bf3cf6454bad/python/cudf/dataframe/index.py#L78-L80

Which if I'm not mistaken is iterating over every element in the index in Python, then creating a NumPy array, neither of which, I think, should be happening.  This is taking the vast majority of compute time, which is currently crippling.

Reproduced by 

```python
import cudf
df = cudf.DataFrame({'x': [1, 2, 3]})
df.merge(df, left_index=True, right_index=True)
```

**Comment by kkraus14** [comment]
I'll fast track a fix for this.
