### ISSUE TITLE
[BUG] Decompressing an orc file with ZSTD can fail due to an inaccurate uncompress block size

### ISSUE THREAD

**Issue by jbrennan333** [rapidsai/cudf#11280]
Decompressing an orc file can lead to a crash in the nvcomp-2.3.2 ZSTD decompression code.
The problem is that the nvcomp ZSTD decompressor requires an accurate calculation of the total decompress size, and this heuristic used in `gpuParseCompressedStripeData` can under-estimate the size for small blocks.

```
      // TBD: For some codecs like snappy, it wouldn't be too difficult to get the actual
      // uncompressed size and avoid waste due to block size alignment For now, rely on the max
      // compression ratio to limit waste for the most extreme cases (small single-block streams)
      uncompressed_size = (is_uncompressed)                         ? block_len
                          : (block_len < (block_size >> log2maxcr)) ? block_len << log2maxcr
                                                                    : block_size;
```

In the case of zstd, log2maxcr is set to 11, which corresponds to a max compression ratio of 2048:1

This was found while testing tpc-ds queries in spark using the spark-rapids plugin.  When run with Orc/ZSTD, 11 queries were producing incorrect output (it wasn't actually crashing).   While investigating one of them, I was able simplify the query to one that caused a crash and then I dumped the orc file that was passed to cudf (attached).   Here is part of the output log from spark-shell, while running under compute-sanitizer and reading the orc file:

```
22/07/15 22:04:18 INFO MultiFileOrcPartitionReader: Writing split data for path: file:///home/jimb/spark/dump-files-shell-orc-zstd-0714/2035750964.orc, range: 0-82178, partition values: [empty row] to /home/jimb/spark/dump-files-shell-orc-zstd/566502374.orc
ZSTD: compinfo[0]: num_compressed_blocks: 1, num_uncompressed_blocks: 0 compressed_data_size: 81973 max_uncompressed_size: 262144 max_uncompressed_block_size: 262144
ZSTD: compinfo[1]: num_compressed_blocks: 1, num_uncompressed_blocks: 0 compressed_data_size: 48 max_uncompressed_size: 92160 max_uncompressed_block_size: 92160
ZSTD: compinfo[2]: num_compressed_blocks: 0, num_uncompressed_blocks: 0 compressed_data_size: 6 max_uncompressed_size: 3 max_uncompressed_block_size: 3
ZSTD: compinfo[3]: num_compressed_blocks: 0, num_uncompressed_blocks: 0 compressed_data_size: 5 max_uncompressed_size: 2 max_uncompressed_block_size: 2
ZSTD: num_chunks: 2, max_uncomp_chunk_size: 262144 max_total_uncomp_size: 354309 temp_size: 716746
22/07/15 22:04:18 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
ai.rapids.cudf.CudaFatalException: transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
	at ai.rapids.cudf.Table.readORC(Native Method)
	at ai.rapids.cudf.Table.readORC(Table.java:1192)
```

Eric Schmidt, from the NVIDIA devtech team, was able to read the file and verify that it decompresses and matches the cpu.  He provided this info:

```
frame 0 size 167675
frame 1 size 247604
```

The interesting case is this one:
```
ZSTD: compinfo[1]: num_compressed_blocks: 1, num_uncompressed_blocks: 0 compressed_data_size: 48 max_uncompressed_size: 92160 max_uncompressed_block_size: 92160
```
This 48 byte compressed block uncompresses to 247604 bytes.   A compression ratio of 5158:1, which is well beyond the current value of 2048:1 that we use in the above heuristic.

I will attempt to attach the orc file that we used to reproduce this.

To fix this, I think in the short term we need to disable the heuristic for estimating the uncompressed block size for ZSTD.   I tested this theory by setting `m_log2MaxRatio = 18` for ZSTD.  With this change, I verified that all of the failing queries produce correct results (and my simpler test case no longer crashes).

[orc-crash-test-file.tgz](https://github.com/rapidsai/cudf/files/9124456/orc-crash-test-file.tgz)

**Comment by jbrennan333** [comment]
If possible, it would be great to have a workaround for this issue in 22.08 if a longer term fix is not possible in that time-frame.

**Comment by vyasr** [comment]
@jbrennan333 is there a longer term fix than what's done in #11288? Is there a more accurate estimate that we should be using?

**Comment by jbrennan333** [comment]
I think we do need a longer term fix, but I'm not certain what it should be.  nvcomp does have an API for calculating the needed decompress buffer sizes (`nvcompBatchedZstdGetDecompressSizeAsync`), but it is expensive to do this for all buffers.  Perhaps a pre-pass could identify the list of smaller compressed buffers and only call this API for them?  I think we really need cuIO team input on what the long term fix should be.

**Comment by jbrennan333** [comment]
@vuule is this on your radar for a future cuIO improvement, or are you happy with the workaround?

**Comment by vuule** [comment]
Should be fixed via https://github.com/rapidsai/cudf/pull/12338
