### ISSUE TITLE
[BUG] Loads a Hive Map columns as list when read with read_orc.

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#11293]
When the hive stores a columns as a map {key<str>:value<str>}. For example:
```
create table test
(id int, mapcol map<string,string>) 
ROW FORMAT SERDE 
  'org.apache.hadoop.hive.ql.io.orc.OrcSerde' 
STORED AS INPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcInputFormat' 
OUTPUTFORMAT 
  'org.apache.hadoop.hive.ql.io.orc.OrcOutputFormat'

insert into test
select 0 as id, map(cast('a' as String),cast('null' as String)) as mapcol

Select * from test

| bot_excl_test.id  | bot_excl_test.mapcol  |
+-------------------+-----------------------+
| 0                 | {"a":"null"}          |
```
Now loading the following file with cudf create a list dtype instead of a struct dtype.
```
In [1]: import cudf
In [2]: df = cudf.read_orc('000000_0')
In [10]: df.mapcol
Out[10]: 
0    [{'0': 'a', '1': 'null'}]
Name: mapcol, dtype: list
```

**Comment by mlahir1** [comment]
[000000_dummy_test.zip](https://github.com/rapidsai/cudf/files/9134577/000000_dummy_test.zip)

adding test data that causes the issue.

**Comment by vuule** [comment]
cuDF does not have a map type, so such columns are read as a list of structs of key-value pairs. AFAICT the behavior here is expected.

**Comment by mlahir1** [comment]
i understand cudf is trying to read a list of structs for map, but should they be formatted like this 
```
[{key1: value1}]
```

instead of
```
[{'0': 'key1', '1': 'value1'}]
```

**Comment by vuule** [comment]
That's how the structs are formatted; '0' and '1' are auto generated field names in the struct column.
CC @galipremsagar in case I'm missing something related to formatting.

**Comment by mlahir1** [comment]
@vuule , Also, i am writing the data from cudf, and i am creating an external table on this data with hive. One of my column that my external tables has is `map`, how is the cudf supposed to write it? if I am writing them this way `[{'0': 'key1', '1': 'value1'}]` hive throws an error while loading external table.

**Comment by galipremsagar** [comment]
> read a list of structs for map is good, but should they be formatted like this
> 
> ```
> [{key1: value1}]
> ```
> 
> instead of
> 
> ```
> [{'0': 'key1', '1': 'value1'}]
> ```

@mlahir1 Could you correct me if I didn't get it right? From what you are saying you expect the series to be of the following pattern?:

```
Out[10]: 
0    [{'a' : 'null'}]
1    [{'b' : '10'}] 
2    [{'c' : '50'}] 
Name: mapcol, dtype: list

**Comment by mlahir1** [comment]
yes, right.

**Comment by mlahir1** [comment]
i am look for a way, where an external table on hive with column dtype `mapcol` can read it.

**Comment by galipremsagar** [comment]
> Out[10]: 
> 0    [{'a' : 'null'}]
> 1    [{'b' : '10'}] 
> 2    [{'c' : '50'}] 
> Name: mapcol, dtype: list

Unfortunately, that's not possible with the `struct` type in `cudf`:

```python
In [4]: s = cudf.Series([{'a':1}, {'b':10}])

In [5]: s
Out[5]: 
0     {'a': 1, 'b': None}
1    {'a': None, 'b': 10}
dtype: struct

In [6]: s = cudf.Series([[{'a':1}, {'b':10}]])

In [7]: s
Out[7]: 
0    [{'a': 1.0, 'b': None}, {'a': None, 'b': 10.0}]
dtype: list
``` 

cc: @shwina for visibility.

**Comment by mlahir1** [comment]
so, there is no way i can create a `map` type col in hive, by writing a dataframe from cudf?

**Comment by galipremsagar** [comment]
> so, there is no way i can create a `map` type col in hive, by writing a dataframe from cudf?

As of now, we don't have a `1:1` corresponding `map` type in `cudf`.


But we would like to know more so that it will either help us in giving a workaround/support for what you are looking for:
1. What the dataset looks like, can you provide us with a dataset with more records? Does each row have multiple key-value pairs like for ex: 
```hive

| bot_excl_test.id  | bot_excl_test.mapcol              |
+-------------------+-----------------------------------+
| 0                 | {"a":"null"},  {"b": 10}          |
````

2. What is the size of the column in your real-world use case?
3. How many unique `key's`(i.e., `a`, `b`, `c`...) are going to be present in your column? We primarily are looking to learn the cardinality or how sparse the keys are.
4. After loading the orc file into `cudf`/`pandas` what are the operations you are planning on doing with the data frame?

Just as note, this is how pandas reads the provided orc file:
```python
In [7]: pd.read_orc('000000_0 (1)')
Out[7]:
   id       mapcol
0   0  [(a, null)]
```
