### ISSUE TITLE
[BUG] Exception thrown with dask_cudf.shuffle

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#11304]
the following exception is thrown with dask_cudf.shuffle.
```
TypeError: No dispatch for <class 'cudf.core.dataframe.DataFrame'>
```

Steps to repro the issue:
```
from dask.delayed import delayed
from dask.dataframe import from_delayed
import cudf, dask
from dask.distributed import Client, wait,  get_worker, progress
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster(threads_per_worker=8, rmm_managed_memory=True)
client = Client(cluster)

def create_df(i):
    df = cudf.DataFrame()
    df['a'] = range(1000000)
    df['b'] = 'test'
    return df

dfs =  from_delayed([delayed(create_df)(i) for i in range(100)])
dfs = dfs.repartition(npartitions=16).shuffle(['a']).to_delayed()

dfs, = dask.compute(dfs)
dfs
```

cudf version: 22.06
dask_cudf version: 22.06

**Comment by shwina** [comment]
Hmm - I was able to run this test fine locally. Does `cudf` work correctly for you outside of dask?

**Comment by mlahir1** [comment]
> cudf work correctly for you outside of dask?
yes, they work fine, outside dask_cudf.

**Comment by mlahir1** [comment]
may be trying increasing this number, `range(1000000)`. this works fine with `100000`

**Comment by quasiben** [comment]
I'm not able to reproduce either.  I'm going to close but feel free to reopen if you are still seeing the error @mlahir1 with latest cuDF/dask-cudf
