### ISSUE TITLE
[DOC] Unused import

### ISSUE THREAD

**Issue by Masynchin** [rapidsai/cudf#11316]
## Report incorrect documentation

**Location of incorrect documentation**
First line of

https://github.com/rapidsai/cudf/blob/edc5062bdcc3e12755603b0ad07a4d271fe95261/README.md?plain=1#L24-L34

**Describe the problems or issues found in the documentation**
Import of `io` is unused, since StringIO import directly.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

1) Look at example.
2) See unused import.
3) Verify with `cmd+f` with`io` and see no occurrences. 

**Suggested fix for documentation**
Remove `io` from module imports.

**Comment by vyasr** [comment]
Thanks for reporting this @Masynchin
