### ISSUE TITLE
aws/core/Aws.h - anyway of building without the dependency

### ISSUE THREAD

**Issue by sononix** [rapidsai/cudf#11333]
After looking through the documentation on building libcudf - I'm still hitting a block on 

<code>
/workspace/build/_deps/arrow-src/cpp/src/arrow/filesystem/s3fs.cc:42:10: fatal error: aws/core/Aws.h: No such file or directory
   42 | #include <aws/core/Aws.h>
      |          ^~~~~~~~~~~~~~~~
</code>

I have managed to build libcudf locally, yes after jumping through a number of hopes in particular the above error where I built the AWS sdk - https://docs.aws.amazon.com/sdk-for-cpp/v1/developer-guide/setup-linux.html from source code.

Im trying to stream line my build process by docker-ising the build procedure - Im using https://github.com/isVoid/linkto_libcudf,where I added some additional libraries and including the latest version of build tools 

The error is displaying again when I build within a docker container, so I was wondering is there anyway of installing a pre-built binary etc - I have tried using environment variable to skip an S3 build, but that doesnt work, building from AWS source was how I got past it locally but the build takes  a very long time !!!!!

From multiple treads that are here - Im wondering how everyone else is building from source as it doesnt appear to be straight forward, there are multiple dependencies on external modules, for example:

<code>
./build.sh cudf
</code>

building cudf you are required to have skbuild install to progress the build.

**Comment by upsj** [comment]
The S3 support can be disabled using the `CUDF_ENABLE_ARROW_S3` variable, IIRC. You can set it by passing `-DCUDF_ENABLE_ARROW_S3=OFF` to CMake during configuration.

**Comment by bdice** [comment]
Thanks @sononix for the question and @upsj for the answer. Setting the CMake variable `CUDF_ENABLE_ARROW_S3=OFF` should fix this. I have proposed a change in the default behavior in #11470 to prevent future issues like this one, so I'm going to close this. If you have any other questions, please let us know. Thank you!

**Comment by abnokubi** [comment]
Just FYI.
I had a similr issue, then finally I passed the building process.
The key is cmake version, fisrt I had used cmake 3.20.1 and got the error, then I upgraded cmake to 3.24.3, it work fine.
