### ISSUE TITLE
[BUG] SIGSEGV with sample iloc

### ISSUE THREAD

**Issue by pprados** [rapidsai/cudf#11349]
**Describe the bug**
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV) with a ilog and None value.

**Steps/Code to reproduce bug**
```python
$ conda create -n bug -y -c rapidsai -c nvidia -c conda-forge cudf==22.06 cudatoolkit=11.5
$ conda activate bug
$ python --version
Python 3.9.13
$ python
Python 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
import cudf
import pandas as pd
import numpy as np
pdf = pd.DataFrame({'a': [0, 1, 2, 3],'b': [0.1, 0.2, None, 0.4]})
df = cudf.from_pandas(pdf)
print(df)
df.iloc[0]  # Crash
```

**Expected behavior**
With None or np.NaN, the python process crash

**Environment overview (please complete the following information)**
- Python 3.9.13
- conda conda 4.12.0
- cudf-22.6.0-py3.9
 - Environment location: Bare-metal
- OS: Ubuntu 20.04.4 LTS
 - Method of cuDF install: `conda create -n bug -y -c rapidsai -c nvidia -c conda-forge cudf==22.06 cudatoolkit=11.5`

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details.
I not found the script `print_env.sh`

**Comment by shwina** [comment]
Thanks for reporting! This is a pretty serious  bug, and we'll get to the bottom of  it ASAP!
