### ISSUE TITLE
[BUG] Min and Max aggregations involving `infinity` produce incorrect results

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11352]
Currently, `min` and `max` aggregations for numeric types firstly initialize the results by an `identity` value then call a device operator. The `identity` is:
 * `cuda::std::numeric_limits<T>::max()`, if the aggregation is `min`, and
 * `cuda::std::numeric_limits<T>::lowest()`, if the aggregation is `max`.

When the input is floating-point data that has `infinity`, the `min` and `max` are computed incorrectly. That's because `min(max, infinity) == max` and `max(lowest, -infinity) == lowest`. In other words, for floating-point numbers the `lowest` value is still bigger than `-infinity` and `max` is still smaller than `infinity`.

We should specialize the `identity` value for floating-point numbers.

**Comment by bdice** [comment]
https://github.com/rapidsai/cudf/blob/8faf2b0446b978d2c72178ce786fa82cc5f52e27/cpp/include/cudf/detail/utilities/device_operators.cuh#L168-L177

This should probably read something like:

```cpp
  template <typename T,
            std::enable_if_t<!std::is_same_v<T, cudf::string_view> && !cudf::is_dictionary<T>() &&
                             !cudf::is_fixed_point<T>()>* = nullptr>
  static constexpr T identity()
  {
    // chrono types do not have std::numeric_limits specializations and should use T::min()
    // https://eel.is/c++draft/numeric.limits.general#6
    if constexpr (cudf::is_chrono<T>()) {
        return T::min();
    } else if constexpr (cuda::std::numeric_limits<T>::has_infinity) {
        return -cuda::std::numeric_limits<T>::infinity();
    }
    return cuda::std::numeric_limits<T>::lowest();
  }
```

and similarly for the min identity with +inf.
