### ISSUE TITLE
[BUG] Build configuration should check what _C_ compiler is being used

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1138]
I was just trying (by mistake) to build branch `branch-0.6` with `CC=/opt/gcc-8.2.0/bin/gcc` in my environment.

I actually got very far in the build - as far as the last few test binaries - then got an obscure linking error about an invalid relocation. Obviously, this doesn't happen with my distro's default compiler (GCC 6.3.0). I don't know exactly what the C compiler is used for - but it must be something.

Now, what _should_ happen is for the build to fail much earlier, at the configuration phase.

I would make a concrete suggestion if I knew how the C compiler is relevant to our build at all; but the "blunt approach" is to simply ensure, in our `CMakeLists.txt`, that the C compiler CMake has found  corresponds to an unsupported C++ compiler (e.g. when it's GCC, clang or MSVC).

**Comment by GregoryKimball** [comment]
Closing for now. @robertmaynard would you please re-open this if this is still relevant?
