### ISSUE TITLE
The example in the documentation for `get_dremel_data()` seems incorrect at line#1764

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#11396]
I know this isn't part of the review, but the example in the documentation for `get_dremel_data()` seems incorrect at line#1738 (now [#1764](https://github.com/rapidsai/cudf/pull/11328/files#diff-e3891cd717ca174e53dd11bbf812ad3f13034d4c1a4626ea751f05bbed8470d5R1764)):
```c++
 * Given a LIST column of type `List<List<int>>` like so:
 * ```
 * col = {
 *    [],
 *    [[], [1, 2, 3], [4, 5]],
 *    [[]]
 * }
 * ```
 * We can represent it in cudf format with two level of offsets like this:
 * ```
 * Level 0 offsets = {0, 0, 3, 5, 6}
 * Level 1 offsets = {0, 0, 3, 5, 5}
 * Values          = {1, 2, 3, 4, 5}
 * ```
```
The `Level 0` offset values can't exceed `4`, since `Level 1` has only 4 ranges (i.e. 5 offsets).
I'll try make sense of this at a later date, but I'm not sure I could follow along.

_Originally posted by @mythrocks in https://github.com/rapidsai/cudf/pull/11328#discussion_r932727013_

**Comment by vyasr** [comment]
@bdice noticed the same issues while reviewing #11129, which moves these dremel files around but also doesn't modify them. We'll want to do a thorough pass through both the docstring of `get_dremel_data` and the actual function implementation once both #11129 and of @hyperbolic2346's Parquet-related PRs are merged where we just focus on cleaning up that functionality and documentation.

**Comment by vyasr** [comment]
@bdice @hyperbolic2346 is this something you two want to take another look at? I think it got lost in the shuffle of the other PRs.
