### ISSUE TITLE
[BUG] module 'cudf' has no attribute 'DataFrame' in jupyter-lab

### ISSUE THREAD

**Issue by Laz4rz** [rapidsai/cudf#11427]
**Describe the bug**
In jupyter-lab after clean installation on new conda env
`
AttributeError: module 'cudf' has no attribute 'DataFrame'
` 
works when I call python in terminal and do the same 

**Steps/Code to reproduce bug**
After installation using 
`
conda install -c rapidsai -c nvidia -c numba -c conda-forge \
    cudf=22.06 python=3.9 cudatoolkit=11.6
`
and 

```
import cudf

cudf.DataFrame()

```
in jupyter-lab

**Expected behavior**

```
Empty DataFrame
Columns: []
Index: []
```

**Environment overview (please complete the following information)**
 - Environment location: Arch 5.17.7-arch1-1
 - Method of cuDF install: conda

**Environment details**

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit e7e5f456f4d7a47c76fb17cd20ca3ea037e15618 (HEAD -> branch-22.08, origin/branch-22.08, origin/HEAD)
     Author: H. Thomson Comer <thomcom@gmail.com>
     Date:   Tue Jul 26 16:53:36 2022 -0500
     
     Fix memory_usage() for `ListSeries` (#11355)
     
     This PR fixes the `memory_usage()` call for `ListSeries`. This is a bugfix. https://www.github.com/rapidsai/cuspatial/pull/585 depends on this. Perhaps it can get into `branch-22.08`?
     
     Fixes #11346.
     
     Authors:
     - H. Thomson Comer (https://github.com/thomcom)
     
     Approvers:
     - Ashwin Srinath (https://github.com/shwina)
     - GALI PREM SAGAR (https://github.com/galipremsagar)
     
     URL: https://github.com/rapidsai/cudf/pull/11355
     **git submodules***
     
     ***OS Information***
     NAME="Arch Linux"
     PRETTY_NAME="Arch Linux"
     ID=arch
     BUILD_ID=rolling
     ANSI_COLOR="38;2;23;147;209"
     HOME_URL="https://archlinux.org/"
     DOCUMENTATION_URL="https://wiki.archlinux.org/"
     SUPPORT_URL="https://bbs.archlinux.org/"
     BUG_REPORT_URL="https://bugs.archlinux.org/"
     LOGO=archlinux-logo
     Linux montec-c1 5.17.7-arch1-1 #1 SMP PREEMPT Thu, 12 May 2022 18:55:54 +0000 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Aug  2 13:32:28 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 515.43.04    Driver Version: 515.43.04    CUDA Version: 11.7     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
     | 37%   28C    P8    26W / 331W |      3MiB / 11264MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
     | 33%   23C    P8    15W / 250W |      2MiB / 11264MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Address sizes:                   39 bits physical, 48 bits virtual
     Byte Order:                      Little Endian
     CPU(s):                          12
     On-line CPU(s) list:             0-11
     Vendor ID:                       GenuineIntel
     Model name:                      Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
     CPU family:                      6
     Model:                           158
     Thread(s) per core:              2
     Core(s) per socket:              6
     Socket(s):                       1
     Stepping:                        10
     CPU(s) scaling MHz:              20%
     CPU max MHz:                     4700,0000
     CPU min MHz:                     800,0000
     BogoMIPS:                        7402.02
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
     Virtualization:                  VT-x
     L1d cache:                       192 KiB (6 instances)
     L1i cache:                       192 KiB (6 instances)
     L2 cache:                        1,5 MiB (6 instances)
     L3 cache:                        12 MiB (1 instance)
     NUMA node(s):                    1
     NUMA node0 CPU(s):               0-11
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Mitigation; Microcode
     Vulnerability Tsx async abort:   Mitigation; TSX disabled
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.23.1
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (GCC) 12.1.0
     Copyright (C) 2022 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /opt/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2022 NVIDIA Corporation
     Built on Tue_Mar__8_18:18:20_PST_2022
     Cuda compilation tools, release 11.6, V11.6.124
     Build cuda_11.6.r11.6/compiler.31057947_0
     
     ***Python***
     /home/mikolaj/anaconda3/envs/cudf_env/bin/python
     Python 3.9.13
     
     ***Environment Variables***
     PATH                            : /home/mikolaj/anaconda3/envs/cudf_env/bin:/home/mikolaj/anaconda3/bin:/home/mikolaj/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/mikolaj/anaconda3/envs/cudf_env
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/mikolaj/anaconda3/bin/conda
     # packages in environment at /home/mikolaj/anaconda3/envs/cudf_env:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       2_gnu    conda-forge
     abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
     absl-py                   1.2.0              pyhd8ed1ab_0    conda-forge
     aiohttp                   3.8.1            py39hb9d737c_1    conda-forge
     aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
     arrow-cpp                 8.0.1           py39h811ffd7_0_cpu    conda-forge
     astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
     async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
     attrs                     22.1.0             pyh71513ae_1    conda-forge
     aws-c-cal                 0.5.11               h95a6274_0    conda-forge
     aws-c-common              0.6.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
     aws-c-io                  0.10.5               hfb6a706_0    conda-forge
     aws-checksums             0.1.11               ha31a3da_7    conda-forge
     aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
     blinker                   1.4                        py_1    conda-forge
     brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.18.1               h7f98852_0    conda-forge
     ca-certificates           2022.6.15            ha878542_0    conda-forge
     cached-property           1.5.2                hd8ed1ab_1    conda-forge
     cached_property           1.5.2              pyha770c72_1    conda-forge
     cachetools                5.0.0              pyhd8ed1ab_0    conda-forge
     certifi                   2022.6.15        py39hf3d152e_0    conda-forge
     cffi                      1.15.1           py39he91dace_0    conda-forge
     charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
     click                     8.1.3            py39hf3d152e_0    conda-forge
     cryptography              37.0.4           py39hd97740a_0    conda-forge
     cuda-python               11.7.0           py39h3fd9d12_0    nvidia
     cudatoolkit               11.6.0               habf752d_9    nvidia
     cudf                      22.10.00a220802 cuda_11_py39_g797215b620_64    rapidsai-nightly
     cudnn                     8.4.1.50             hed8a83a_0    conda-forge
     cupy                      10.6.0           py39hc3c280e_0    conda-forge
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     fastavro                  1.5.4            py39hb9d737c_0    conda-forge
     fastrlock                 0.8              py39h5a03fae_2    conda-forge
     frozenlist                1.3.0            py39hb9d737c_1    conda-forge
     fsspec                    2022.7.1           pyhd8ed1ab_0    conda-forge
     gast                      0.5.3              pyhd8ed1ab_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.1                h36c2ea0_2    conda-forge
     glog                      0.6.0                h6f12383_0    conda-forge
     google-auth               2.9.1              pyh6c4a22f_0    conda-forge
     google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
     google-pasta              0.2.0              pyh8c360ce_0    conda-forge
     grpc-cpp                  1.45.2               h3b8df00_4    conda-forge
     grpcio                    1.45.0           py39h0f497a6_0    conda-forge
     h5py                      3.7.0           nompi_py39h63b1161_100    conda-forge
     hdf5                      1.12.1          nompi_h2386368_104    conda-forge
     icu                       70.1                 h27087fc_0    conda-forge
     idna                      3.3                pyhd8ed1ab_0    conda-forge
     importlib-metadata        4.11.4           py39hf3d152e_0    conda-forge
     jpeg                      9e                   h166bdaf_2    conda-forge
     keras                     2.8.0              pyhd8ed1ab_0    conda-forge
     keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
     keyutils                  1.6.1                h166bdaf_0    conda-forge
     krb5                      1.19.3               h3790be6_0    conda-forge
     ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
     libblas                   3.9.0           15_linux64_openblas    conda-forge
     libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
     libbrotlidec              1.0.9                h166bdaf_7    conda-forge
     libbrotlienc              1.0.9                h166bdaf_7    conda-forge
     libcblas                  3.9.0           15_linux64_openblas    conda-forge
     libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
     libcudf                   22.10.00a220802 cuda11_g797215b620_64    rapidsai-nightly
     libcurl                   7.83.1               h7bff187_0    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               h9b69904_4    conda-forge
     libffi                    3.4.2                h7f98852_5    conda-forge
     libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
     libgfortran-ng            12.1.0              h69a702a_16    conda-forge
     libgfortran5              12.1.0              hdcd56e2_16    conda-forge
     libgomp                   12.1.0              h8d9b700_16    conda-forge
     libgoogle-cloud           1.40.2               habd0e3a_0    conda-forge
     liblapack                 3.9.0           15_linux64_openblas    conda-forge
     libnghttp2                1.47.0               h727a467_0    conda-forge
     libnsl                    2.0.0                h7f98852_0    conda-forge
     libopenblas               0.3.20          pthreads_h78a6416_1    conda-forge
     libpng                    1.6.37               h753d276_3    conda-forge
     libprotobuf               3.20.1               h6239696_0    conda-forge
     librmm                    22.10.00a220802 cuda11_g721c50fa_0    rapidsai-nightly
     libssh2                   1.10.0               ha56f1ee_2    conda-forge
     libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
     libthrift                 0.16.0               h519c5ea_1    conda-forge
     libutf8proc               2.7.0                h7f98852_0    conda-forge
     libuuid                   2.32.1            h7f98852_1000    conda-forge
     libzlib                   1.2.12               h166bdaf_2    conda-forge
     llvmlite                  0.39.0           py39he1b5a44_0    numba
     lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
     markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
     markupsafe                2.1.1            py39hb9d737c_1    conda-forge
     multidict                 6.0.2            py39hb9d737c_1    conda-forge
     nccl                      2.12.12.1            h0800d71_0    conda-forge
     ncurses                   6.3                  h27087fc_1    conda-forge
     numba                     0.56.0          np1.16py3.9h59fbc97_gf75c45a8d_0    numba
     numpy                     1.22.4           py39hc58783e_0    conda-forge
     nvtx                      0.2.3            py39h3811e60_1    conda-forge
     oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
     openssl                   1.1.1q               h166bdaf_0    conda-forge
     opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
     orc                       1.7.5                h6c59b99_0    conda-forge
     packaging                 21.3               pyhd8ed1ab_0    conda-forge
     pandas                    1.4.3            py39h1832856_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       22.2.1             pyhd8ed1ab_0    conda-forge
     protobuf                  3.20.1           py39h5a03fae_0    conda-forge
     ptxcompiler               0.2.0            py39h107f55c_0    rapidsai-nightly
     pyarrow                   8.0.1           py39h42d110c_0_cpu    conda-forge
     pyasn1                    0.4.8                      py_0    conda-forge
     pyasn1-modules            0.2.7                      py_0    conda-forge
     pycparser                 2.21               pyhd8ed1ab_0    conda-forge
     pyjwt                     2.4.0              pyhd8ed1ab_0    conda-forge
     pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
     pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
     pysocks                   1.7.1            py39hf3d152e_5    conda-forge
     python                    3.9.13          h9a8a25e_0_cpython    conda-forge
     python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
     python-flatbuffers        2.0                pyhd8ed1ab_0    conda-forge
     python_abi                3.9                      2_cp39    conda-forge
     pytz                      2022.1             pyhd8ed1ab_0    conda-forge
     pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
     re2                       2022.06.01           h27087fc_0    conda-forge
     readline                  8.1.2                h0f457ee_0    conda-forge
     requests                  2.28.1             pyhd8ed1ab_0    conda-forge
     requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
     rmm                       22.10.00a220802 cuda11_py39_g721c50fa_0    rapidsai-nightly
     rsa                       4.9                pyhd8ed1ab_0    conda-forge
     s2n                       1.0.10               h9b69904_0    conda-forge
     scipy                     1.9.0            py39h8ba3f38_0    conda-forge
     setuptools                63.3.0           py39hf3d152e_0    conda-forge
     six                       1.16.0             pyh6c4a22f_0    conda-forge
     snappy                    1.1.9                hbd366e4_1    conda-forge
     spdlog                    1.8.5                h4bd325d_1    conda-forge
     sqlite                    3.39.2               h4ff8645_0    conda-forge
     tensorboard               2.8.0              pyhd8ed1ab_1    conda-forge
     tensorboard-data-server   0.6.0            py39hd97740a_2    conda-forge
     tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
     tensorflow                2.8.1           cuda112py39h01bd6f0_0    conda-forge
     tensorflow-base           2.8.1           cuda112py39he716a45_0    conda-forge
     tensorflow-estimator      2.8.1           cuda112py39hd320b7a_0    conda-forge
     termcolor                 1.1.0              pyhd8ed1ab_3    conda-forge
     tk                        8.6.12               h27826a3_0    conda-forge
     typing-extensions         4.3.0                hd8ed1ab_0    conda-forge
     typing_extensions         4.3.0              pyha770c72_0    conda-forge
     tzdata                    2022a                h191b570_0    conda-forge
     urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
     werkzeug                  2.2.1              pyhd8ed1ab_0    conda-forge
     wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
     wrapt                     1.14.1           py39hb9d737c_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yarl                      1.7.2            py39hb9d737c_2    conda-forge
     zipp                      3.8.1              pyhd8ed1ab_0    conda-forge
     zlib                      1.2.12               h166bdaf_2    conda-forge
     zstd                      1.5.2                h8a70e8d_2    conda-forge

**Additional context**
None

**Comment by shwina** [comment]
Could you also post the output of:

```python
>>> import cudf
>>> print(cudf.__file__)
>>> print(cudf.__version__)
```

Also, do you happen to run this code in a location that contains a directory called `cudf`?

**Comment by beckernick** [comment]
> In all of those cudf works in python commandline
>  Yes, notebook is in the same location as cudf directory, otherwise, it gives [module not found error]:

Your environment creation/install commands aren't installing Jupyterlab. Is it possible you're using actually using Jupyterlab from a base environment that is defaulting to a different Python kernel? That would explain what you're experiencing.

I'd recommend adding `jupyterlab` to your install command if you'd like to use it in your environment. https://rapids.ai/start.html#get-rapids has an environment selector widget that may be helpful.

**Comment by Laz4rz** [comment]
@beckernick I checked the env from notebook cell, but you might be actually right.

Going with this install now:
```
conda create -n rapids-22.08 -c rapidsai-nightly -c nvidia -c conda-forge  \
    cudf=22.08 cusignal=22.08 cucim=22.08 cuml=22.08 cugraph=22.08 cuxfilter=22.08 cuspatial=22.08 python=3.9 cudatoolkit=11.5 \
    jupyterlab dask/label/dev::dask-sql dash graphistry pycaret tensorflow
```

**Comment by beckernick** [comment]
Great. Closing this issue as resolved. Please feel free to re-open for further discussion, if relevant.
