### ISSUE TITLE
[QST] Is there a way to re-construct cudf DataFrame by __cuda_array_interface__

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#11462]
Hi there,

I'm asking if there is a way to re-construct cudf dataframe or Series according to __cuda_array_interface__?

the __cuda_array_interface__ is like 

``` json
{'shape': [5], 'data': ['xxxxxx', False], 'typestr': '<i4', 'version': 1}
```

**Comment by trivialfis** [comment]
Hi, to provide more context, @wbo4958 is currently working on https://github.com/NVIDIA/spark-rapids/issues/5561 for enabling sharing cuDF columns between jvm process and Python process via CUDA IPC.  @wbo4958 generated the cuda array interface from jvm side as a reference to the underlying data and passed it to the python process as a message. Other forms of references are also possible.  This feature request is more broadly about reconstructing a DataFrame from a set of pointers/IPC handles along with needed metadata.

I looked into the `from_dlpack` constructor, which should take ownership of the data and would be similar to what we need for constructing cudf dataframe from the handle. If this feature is desired I can help work on a PR.

**Comment by wence-** [comment]
> I looked into the `from_dlpack` constructor, which should take ownership of the data and is similar to what we need for constructing cudf dataframe from the handle. If this feature is desired I can help work on a PR.

Right now, `from_dlpack` copies the data, which is not what you want. It could be updated to share the pointer, but is a little fiddly.

**Comment by shwina** [comment]
Note that, while currently somewhat buggy, cuDF does support the [`__dataframe__` interchange protocol](https://data-apis.org/dataframe-protocol/latest/API.html) which is perhaps what you need here rather than `__cuda_array_interface__`. I aim to resolve many of the outstanding issues with our implementation of  the protocol during this release (22.10).

**Comment by trivialfis** [comment]
Thank you for the suggestions! The `__dataframe__` protocol seems to be a good starting point for us to hack into cuDF.
