### ISSUE TITLE
[FEA] Add `stream` parameter for groupby operations (aggregate, scan, shift, etc.)

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#11463]
Currently, groupby operations do not have a `stream` parameter. As such, we can't pass in the current `stream` value but the operations will use the default stream instead.

We should allow passing in `stream` parameter in groupby aggregation.

**Comment by davidwendt** [comment]
Closed by https://github.com/rapidsai/cudf/pull/17324
