### ISSUE TITLE
I beg you how to install cudf on windows 10 [QST]

### ISSUE THREAD

**Issue by Arsiprog** [rapidsai/cudf#11488]
**What is your question?**
C:\Windows\system32>python C:\cudf\setup.py
C:\cudf\setup.py:8: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
Traceback (most recent call last):
  File "C:\cudf\setup.py", line 11, in <module>
    from skbuild import setup
ModuleNotFoundError: No module named 'skbuild'

C:\Windows\system32>

**Comment by bdice** [comment]
Hi @Arsiprog, RAPIDS libraries are supported through the Windows Subsystem for Linux version 2 (WSL 2). Please see the link below for information on how to set up WSL2 with GPU support and install RAPIDS.

https://developer.nvidia.com/blog/run-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux/

Currently, Windows 11 and a GPU with the Turing microarchitecture or newer is required for running RAPIDS on WSL2. See #11382 and [this comment](https://github.com/rapidsai/cudf/issues/11382#issuecomment-1198389286) for additional details.

You may also find it helpful to get started with RAPIDS by using a cloud-based GPU if a local installation isn't supported on your hardware. See our [Getting Started](https://rapids.ai/start.html) page for more information.

I am going to close this issue for now, but feel free to re-open if you have additional questions or comments.
