### ISSUE TITLE
[QST]Failed to dlopen libcuda.so

### ISSUE THREAD

**Issue by pp850110** [rapidsai/cudf#11485]
Trying to import cuGraph but failed.

Error feedback is as follows:

------------------------------------------------
RuntimeError Traceback (most recent call last) 

File ~/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/cuda/_cuda/ccuda.pyx:3671, in cuda._cuda.ccuda._cuInit() 
File ~/miniconda3/envs/rapids-22.06/lib/python3.9/site-packages/cuda/_cuda/ccuda.pyx:435, in cuda._cuda.ccuda.cuPythonInit() 

RuntimeError: Failed to dlopen libcuda.so

Canceled future for execute_request message before replies were done

The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

----------------------------------------------------
NVIDIA-SMI is as follows:
<img width="571" alt="image" src="https://user-images.githubusercontent.com/34187179/183243722-11a8c3f8-a513-43b7-ab5d-5c26a6369465.png">

**Comment by galipremsagar** [comment]
@pp850110 Can you share the output of `conda list`?

**Comment by pp850110** [comment]
> @pp850110 Can you share the output of `conda list` in the environment you are seeing this error?

@galipremsagar Sure. It is as the .txt attachment


[Conda list.txt](https://github.com/rapidsai/cudf/files/9282799/Conda.list.txt)

**Comment by galipremsagar** [comment]
@pp850110 Could you share the output of `ldconfig -p | grep libcuda.so`

**Comment by pp850110** [comment]
@galipremsagar I got nothing from `ldconfig -p | grep libcuda.so`. Hereby sharing the output of `ldconfig -p`.
[ldconfig_p.txt](https://github.com/rapidsai/cudf/files/9303953/ldconfig_p.txt)

**Comment by galipremsagar** [comment]
Interesting, can you print your `$LD_LIBRARY_PATH`?

and also output of:
```
sudo find /usr/ -name 'libcuda.so.*'
```

**Comment by pp850110** [comment]
@galipremsagar Actually, I can get the output of `ldconfig -p | grep libcuda.so` once connecting to the remote GPU. BTW, it is not a local GPU in this case. However, I cannot print `$LD_LIBRARY_PATH` and also do not have the authority to `sudo`.
Please check the output of `ldconfig -p | grep libcuda.so` as follows:
[grep libcuda.so.txt](https://github.com/rapidsai/cudf/files/9307317/grep.libcuda.so.txt)

**Comment by galipremsagar** [comment]
What do the following environment variables have?:
```
CUDA_PATH
LD_LIBRARY_PATH
PATH
CUDA_HOME
```

**Comment by pp850110** [comment]
`$printenv`
`CUDA_PATH=/home/~/~/miniconda3/envs/rapids-22.06\`
`MODULES_RUN_QUARANTINE=LD_LIBRARY_PATH LD_PRELOAD\`
`PATH=/software/all/bin:/software/all/bin:/~/~/home/~/.vscode-server/bin/6d9b74a70ca9c7733b29f0456fd8195364076dda/bin/remote-cli:/home/~/~/miniconda3/envs/rapids-22.06/bin:/home/~/~/miniconda3/condabin:/home/~/.local/bin:/home/~/bin:/`
There is not any result of `CUDA_HOME`.

**Comment by galipremsagar** [comment]
Looks like your environment might be missing paths to libcuda.so, can you try setting these environment variables:
```bash
export CUDA_PATH=/usr/local/cuda
export LD_LIBRARY_PATH=$CUDA_PATH/lib64:$LD_LIBRARY_PATH
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
export PATH=$PATH:$CUDA_HOME/bin
```

All the above assumed you have a valid installation of `CUDA` at `/usr/local/cuda`, if you have it at any other location, you will need to tweak the paths accordingly.

**Comment by pp850110** [comment]
@galipremsagar 

Thanks for the suggestion. 
It did not work in the VS code studio via ssh.
However, after loading the CUDA module, it works on the Jupyter notebook web interface provided by the host.

**Comment by galipremsagar** [comment]
Thanks, @pp850110. Looks like an issue with vs code, closing this issue for now.
