### ISSUE TITLE
[FEA] Install `*.pyi` stub files

### ISSUE THREAD

**Issue by madsbk** [rapidsai/cudf#11496]
As far as I can see, we do not install the type stub files such as `column.pyi`. At least, building cudf and libcudf don't seem to install them?
```
./build.sh libcudf cudf 
```

Currently, I copy the `*.pyi` files manually to make the IntelliSense in Visual Studio Code work correctly.
```
cp python/cudf/cudf/_lib/*.pyi <CondaENV>/lib/python3.9/site-packages/cudf/_lib/
```

Am I missing something?

**Comment by shwina** [comment]
Likely they need to be included in the `package_data`?

**Comment by madsbk** [comment]
> Likely they need to be included in the `package_data`?

Yes, similar to how we handle `*.pxd`: https://github.com/rapidsai/cudf/blob/branch-22.10/python/cudf/setup.py#L149

**Comment by vyasr** [comment]
I'm going to close this. The Cython code in cuDF will be phased out at some point in the intermediate future. The long-term plan is for everything to be in pylibcudf, so #15190 is the spiritual successor to this issue.
