### ISSUE TITLE
[FEA] Create `make` target for building/installing libcudf into Python environment

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1152]
**Is your feature request related to a problem? Please describe.**

I wish that installing libcudf from source into the Python environment was easier.

Building and installing `libcudf` from source currently has a large number of manual steps that significantly slows down the process debugging C++ bugs in Python reproducers.

The currently required process:

```
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 
make -j                                                                 
make install                                                            
make python_cffi                                  
make install_python                              
cd $CUDF_HOME/python
python setup.py build_ext --inplace
python setup.py install   
```

**Describe the solution you'd like**

It would be significantly more convenient if a `make` target was created that would allow the steps described above to be simplified to the following:

```
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX 
make -j                                                                 
make install_python
```

**Comment by harrism** [comment]
How relevant is this if we eliminate CFFI?

**Comment by jrhemstad** [comment]
> How relevant is this if we eliminate CFFI?

What will the install process look like after removing CFFI?

Won't that just removed `make python_cffi`? In which case, I think it's still valuable to make a more streamlined target.

**Comment by vyasr** [comment]
This is no longer an issue with the switch to scikit-build. Using `python setup.py install` by itself is sufficient to build and install both the C++ and Python components. If necessary, the Python build can also be pointed to a preexisting libcudf build with `-DFIND_CUDF_CPP=ON -DCMAKE_PREFIX_PATH=/path/to/libcudf`.
