### ISSUE TITLE
cuDF not interpreting "-" within a regex set consistent with documentation and pandas.

### ISSUE THREAD

**Issue by brianklobucher** [rapidsai/cudf#11537]
cuDF regex interpretation of “-“ within a regex set does not conform to the documentation ([]https://docs.python.org/3/library/re.html), resulting in (at least) two unexpected and undesirable results:

1. cuDF throws an error:  cuDF failure at: /workspace/.conda-bld/work/cpp/src/strings/regex/regcomp.cpp:437: invalid regex pattern: nothing to repeat at position 17
2. cuDF results do not match those from pandas.

This issue is visible when using regex to identify email addresses.  The observed deviation from the documentation is that the “-“ needs to be either escaped (“\\-“) or not located at the beginning or end of the set (“[-“ and “-]”).

The below notebook includes multiple regex permutations (escaped “-“ in the set, etc.) to reproduce both of the above issues and to show regex where cuDF and pandas do match:  

[]https://github.com/brianklobucher/issue_analysis/blob/master/RAPIDS_regex/RAPIDS-regex-email-addresses.ipynb

Expected behavior:  cuDF and pandas regex produce identical results without needing to change the regex.

Environment:
* These issues were present for both RAPIDS 22.04 and 22.06.
* This was run on WSL Ubuntu 20.04.4 LTS.
* RAPIDS was installed via conda.

**Comment by shwina** [comment]
cc: @davidwendt

**Comment by davidwendt** [comment]
> Expected behavior: cuDF and pandas regex produce identical results without needing to change the regex.

In general, the cuDF regex will not match Pandas or Python regex in every condition.
Here is the documentation for what cuDF supports for regex: https://docs.rapids.ai/api/libcudf/stable/md_regex.html

That said, so far, this looks possible to support in libcudf.
