### ISSUE TITLE
[FEA] Remove usages of `pyorc` where not necessary

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#11540]
**Is your feature request related to a problem? Please describe.**
Writing a pandas dataframe to an orc file using `pyorc` is a bit of a complex operation. Until now we have been using `pyorc` as a reference writer because we had no other choice, with the introduction of `pyarrow`'s orc writer we should be making a switch from `pyorc` and this should remove a lot of complex handling that needs to be done for nested dtypes.

**Describe the solution you'd like**
Drop `pyorc` usages to almost none - Though we will keep it probably for a few basic dtype tests to validate compatibilty. But fuzz-testing and the rest of pytests should make the switch.

**Describe alternatives you've considered**
The FEA itself is a better alternative to `pyorc` 😉 

**Additional context**
https://arrow.apache.org/docs/python/generated/pyarrow.orc.write_table.html

https://github.com/rapidsai/cudf/issues/11540#tasklist-block-36d8af1d-36b8-447e-9227-e4ad3da9d7e1

**Comment by galipremsagar** [comment]
cc: @GregoryKimball @vuule

**Comment by vuule** [comment]
Is the main difference in the PyORC's requirement to pass in a schema?
Would it be possible to try this out in fuzz tests to verify that pyarrow is robust?

**Comment by galipremsagar** [comment]
> Is the main difference in the PyORC's requirement to pass in a schema?
That + while the writer was an internal only API it lacked the stripe_size support which was a limiting factor to use that internal version of pyarrow's orc writer. 

> Would it be possible to try this out in fuzz tests to verify that pyarrow is robust?

Yup

**Comment by vuule** [comment]
I definitely like the suggestion, pyarrow API looks very clean and... comprehensive (more so than ours 😬).

**Comment by galipremsagar** [comment]
https://github.com/rapidsai/cudf/pull/12103 solves part of the problem. However we will need to wait until pyarrow can write complex nested data-types to an orc file.

**Comment by vyasr** [comment]
This was completed in #14323
