### ISSUE TITLE
Should remove column count assertions in parquet tests

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#11541]
Vukasin pointed out that these asserts are testing `table`(previously)/`table_view`(now) constructor, rather then anything in Parquet. These should be removed.

__Originally posted by @vuule in https://github.com/rapidsai/cudf/pull/11524#discussion_r946237429__

**Comment by vuule** [comment]
Looked over other cuIO tests and could not find any other places where created tables are validated like this.
