### ISSUE TITLE
fail to install rapids/cudf

### ISSUE THREAD

**Issue by Wulin-Tan** [rapidsai/cudf#11542]
Hi, I tried cudf on my ubuntu20 PC and it can perfectly work.
but when I tried it on the linux server, it kept failing to be installed.

_**The error said:**_ 
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.27=0
  - python=3.8 -> libgcc-ng[version='>=7.5.0'] -> __glibc[version='>=2.17']
  - rapids -> cucim=22.06 -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.27

_**And my server's conda information as follows:**_ 
active environment : rapids
    active env location : /root/miniconda3/envs/rapids
            shell level : 2
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.25.1 CPython/3.8.10 Linux/5.4.0-96-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

**_Any suggestions?  Thank you._**

**Comment by Wulin-Tan** [comment]
Hi @shwina 

**_first, I established a virtual env_**
conda create -n my_env python=3.8
conda activate my_env

**_then I tried to install rapids/cudf_**
conda install -c rapidsai rapids 
**_or_**
conda install -c rapidsai cudf

**_both failed as mentioned above._**

**Comment by shwina** [comment]
Thanks, could you try using one of the commands generated using the release selector tool: https://rapids.ai/start.html#get-rapids?

**Comment by Wulin-Tan** [comment]
@shwina Hi, I figured it out by 2 solutions:
solution 1: following your suggestion, I installed it using release selector tool.
solution 2: Since it has been installed on my ubuntu20 PC, I just exported the env+packages by "conda pack" and then transferred to the server.
Both worked for me.
Thank you very much.

**Comment by shwina** [comment]
Glad to hear it! I'll close this issue out, then.
