### ISSUE TITLE
[BUG] read_csv method does not allow integer column names

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1156]
**Describe the bug**
In pandas, I can do the following when reading a csv file:

```
max_n = 8
pdf = pd.read_csv('test.txt', delim_whitespace=True, names=range(max_n))
```

but, if I try to do the same with cudf, the following error is displayed:

```
max_n = 8
gdf = cudf.read_csv('test.txt', delim_whitespace=True, names=range(max_n))
```

```
/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, comment, na_values, keep_default_na, na_filter, prefix, index_col)
    236         csv_reader.num_cols = len(names)
    237         for col_name in names:
--> 238             arr_names.append(_wrap_string(col_name))
    239             if dtype is not None:
    240                 if dtype_dict:

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/io/csv.py in _wrap_string(text)
     18         return ffi.NULL
     19     else:
---> 20         return ffi.new("char[]", text.encode())
     21 
     22 

AttributeError: 'int' object has no attribute 'encode'
```

**Steps/Code to reproduce bug**
Try the code above with any csv file.

**Expected behavior**
No error displayed.

**Environment details (please complete the following information):**
DGX-1, RAPIDS nightly build from 2019/03/08.
 
**Additional context**
The following workaround can be applied:

`gdf = cudf.read_csv('test.txt', delim_whitespace=True, names=[str(x) for x in range(max_n)])`

**Comment by j-ieong** [comment]
@miguelangel you can try the latest branch-0.7 code.

This should be fixed as a result of moving the CSV reader to Cython from CFFI; the column names are now converted to strings before encoding:

```python
    csv_reader.num_cols = len(names)
    for col_name in names:
        arr_names.append(str(col_name).encode())
```

**Comment by miguelangel** [comment]
Hi @j-ieong,

I have just tested with the latest cuDF nightly-built.

I can confirm that the runtime error does not happen anymore. Nevertheless, by converting the column number to string format, a difference between Pandas behaviour is added.

Please, find below how to reproduce it:

![image](https://user-images.githubusercontent.com/26169771/56986085-2ad87b00-6b8a-11e9-9996-e41bfa1ea680.png)

I am not sure if you would like me to close this issue. I would suggest keeping it opened until RAPIDS mimics Pandas behaviour.

Regards,
Miguel

**Comment by j-ieong** [comment]
Hrmm, I think technically it's a different bug now but we can re-use this bug rather than close and open a new one.

This should be a simple fix to keep column names as integral when assigning to the column/dataframe.

**Comment by miguelangel** [comment]
Hi @j-ieong,

Please, notice that in Pandas, when column names are integer values, then accessing by integer positions, i.e. pdf[1], will be restricted to the integer values assigned to the columns.

In my previous example, pdf[1] will fail when assigning column names [3, 4].

Hope it helps.

Regards,
Miguel

**Comment by j-ieong** [comment]
Yeah, that's what I would expect as well. It would only return columns that exist within the dataframe, regardless of the type.

The bug in cudf is that the column names are always a `string` type.
