### ISSUE TITLE
[FEA] Add method argument to DataFrame.quantile

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#11572]
**Is your feature request related to a problem? Please describe.**
@charlesbluca and @mroeschke did some nice work recently to add muli-column support to Pandas' quantile method (https://github.com/pandas-dev/pandas/pull/44301). The accepted solution there was to add a `method` argument (with the options being `"table"` and `"single"`) to `DataFrame.quantile`, rather than adding a `DataFrame.quantiles` method (like we have in cudf).

The new `quantile` change will be introduced to Pandas in the next release.  In order to simplify the development of library-agnostic multi-column sorting in `dask.dataframe`, I suggest that we align the cudf and pandas `quantile` arguments. 

**Describe the solution you'd like**
I would like for `cudf.DataFrame.quantile` to have the same `method` argument as `pd.DataFrame.quantile`.  In the future, it will probably make sense to deprecate  `cudf.DataFrame.quantiles` (note the plurality) altogether.

**Describe alternatives you've considered**
The alternative is to allow unnecessary API divergence between cudf and pandas, complicating both `dask.dataframe` and user code.

**Comment by skycj1** [comment]
#include

**Comment by vyasr** [comment]
Would love to see this make it in, `quantile` vs `quantiles` gives me a headache every time I see it in cudf.
