### ISSUE TITLE
[BUG] types.h refers to stdint.h types, doesn't include that file

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1160]
On branch-0.6, in [`cpp/include/cudf/types.h`](https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/include/cudf/types.h), we have the `gdf_data` union. Some of its members use types defined in `stdint.h`: `int8_t` and such. Yet - the file doesn't include any headers (which IIRC has to be the case due to Python CFFI restrictions?) - and thus fails to compile when included before rather than after other headers.

**Comment by jrhemstad** [comment]
Yes, this is due to CFFI restrictions.

See https://github.com/rapidsai/cudf/issues/599. CFFI will be removed in 0.7.
