### ISSUE TITLE
[DOC] Update data-types page for `cudf`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#11605]
**Describe the problems or issues found in the documentation**
We will need to expose some of the cudf specific data-type into the existing data-types page here: (https://docs.rapids.ai/api/cudf/nightly/user_guide/data-types.html)

**Suggested fix for documentation**
(https://pandas.pydata.org/docs/reference/api/pandas.CategoricalDtype.html#pandas.CategoricalDtype)

**Comment by shwina** [comment]
Do we just need to update/add to https://docs.rapids.ai/api/cudf/nightly/user_guide/data-types.html?

**Comment by galipremsagar** [comment]
> Do we just need to update/add to https://docs.rapids.ai/api/cudf/nightly/user_guide/data-types.html?

Yup

**Comment by vyasr** [comment]
@galipremsagar what data types are missing? It seems like all of our main extension types are there (list, struct) but perhaps I missed something?

**Comment by GregoryKimball** [comment]
Please feel free to re-open if #11604 did not solve this.

**Comment by galipremsagar** [comment]
We list all our extension types(as text) but their docstrings are not discoverable by any means(dtypes page/search). I intend to add that aspect.
