### ISSUE TITLE
[BUG] Regex negate classes in cudf work differently from re and pandas libraries with new-line characters

### ISSUE THREAD

**Issue by maxbalrog** [rapidsai/cudf#11643]
I noticed that some regular expressions behave differently in `re/pandas` and `cudf` libraries. Why it happens that way?

I could give the following example (but there are others) where tokens `\n` are not removed although they should be:
```python
import re
import pandas as pd
import cudf

print(f"re version:     {re.__version__}")
print(f"pandas version: {pd.__version__}")
print(f"cudf version:   {cudf.__version__}")

text = ["\nHello'\n!!!\n$$\n\n it is me"]
res = re.sub("[^A-Za-z0-9]+", " ", text[0])
print(res)

ser = pd.Series(text)
res = ser.str.replace("[^A-Za-z0-9]+", " ")
print(res)

ser = cudf.Series(text)
res = ser.str.replace("[^A-Za-z0-9]+", " ")
print(res)
```

Output:
```
re version:     2.2.1
pandas version: 1.3.1
cudf version:   21.10.01
 Hello it is me
0     Hello it is me
dtype: object
0    \nHello \n \n \n\n it is me
dtype: object
```

**Comment by davidwendt** [comment]
The `[^....]` negated classes pattern is specifically coded to not include the new-line (`\n`) character.
I honestly do not know why that is the case. I've found no documentation that supports this special case which is logic ported from the [plan9 regex source](https://9fans.github.io/usr/local/plan9/src/libregexp/regcomp.c) (lines 408-409).
This includes the libcudf regex documentation: https://docs.rapids.ai/api/libcudf/stable/md_regex.html
as well as here https://www.regular-expressions.info/refcharclass.html

I see no reason to keep this special case. I'll create a PR to remove it.
