### ISSUE TITLE
[BUG] Regex capturing group doesn't work properly in cudf

### ISSUE THREAD

**Issue by maxbalrog** [rapidsai/cudf#11650]
I tried to filter all numbers in a string (defined by `\s\d+\s`) with cudf but the function `Series.str.replace` does not work in my case while similar expressions in `re/pandas` libraries work properly. Is it a bug?

Here I attach my example:

```python
import re
import pandas as pd
import cudf

print(f"re version:     {re.__version__}")
print(f"pandas version: {pd.__version__}")
print(f"cudf version:   {cudf.__version__}")

text = ["16  6  brr  232323  1  hello  90"]
res = re.sub(r"(^|\s)\d+(\s|$)", " ", text[0])
print(res)

ser = pd.Series(text)
res = ser.str.replace(r"(^|\s)\d+(\s|$)", " ", regex=True)
print(res)

ser = cudf.Series(text)
res = ser.str.replace(r"(^|\s)\d+(\s|$)", " ", regex=True)
print(res)
```
Output:
```
re version:     2.2.1
pandas version: 1.3.1
cudf version:   21.10.01
   brr    hello  
0       brr    hello  
dtype: object
Traceback (most recent call last):
  File "check.py", line 111, in <module>
    res = ser.str.replace(r"(^|\s)\d+(\s|$)", " ", regex=True)
  File "/trinity/home/m.valialshchikov/.conda/envs/lama_venv/lib/python3.8/site-packages/cudf/core/column/string.py", line 907, in replace
    libstrings.replace_re(
  File "cudf/_lib/strings/replace_re.pyx", line 41, in cudf._lib.strings.replace_re.replace_re
RuntimeError: cuDF failure at: ../src/strings/regex/regcomp.cpp:397: invalid regex pattern: nothing to repeat at position 2
```

I believe there is a more elegant solution to my problem (e.g., adding whitespace characters to the beginning and to the end of the string so I don't have to use capturing groups `(^|\s)` and `(\s|$)`) but I wanted to do it that way and it's not clear why it doesn't work as expected.

**Comment by shwina** [comment]
cc: @davidwendt, perhaps you have the best insight into the issue here?

**Comment by davidwendt** [comment]
This looks to be a bug in the error check logic. I created a PR to fix it.
I did find a workaround in case it helps in the mean time. 
Just switch the order in the first alternation -- change `(^|\s)` to `(\s|^)` to get around the bug.
```
>>> ser = cudf.Series(text)
>>> res = ser.str.replace(r"(\s|^)\d+(\s|$)", " ", regex=True)
>>> print(res)
0       brr    hello  
dtype: object

```
