### ISSUE TITLE
[BUG] Reading `parquet` file written by `polars` gives wrong result

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#11686]
`cudf` is unable to correctly read a `parquet` file written by `polars`' [write_parquet](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.DataFrame.write_parquet.html#polars.DataFrame.write_parquet):

```python
>>> import cudf
>>> import polars as pl
>>> import pandas as pd
>>> df = pl.DataFrame({'a': [1, 2, 3]})
>>> df.write_parquet("test.pq", compression="uncompressed")  # compression="snappy" gives same result
>>> pd.read_parquet("test.pq")  # pandas can read the file:
   a
0  1
1  2
2  3
>>> cudf.read_parquet("test.pq")  # cudf does not
   a
0  0
1  0
2  0
```

**Comment by etseidl** [comment]
Looking through the polars code, it looks like they default to writing V2 data pages, which libcudf cannot read.  libcudf should throw an exception if V2 pages are detected.
