### ISSUE TITLE
[FEA] Add an option to spill to host memory and disk seamlessly

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#11688]
(initial work on this is well underway in #11553)

When working with large datasets, a common problem encountered is running out of device (GPU) memory.

It would be nice if cuDF could transparently spill (and "unspill") objects from device memory to host (CPU) memory or disk, which are typically much larger in size.

At a high level, it would work something like this:

```python
# assume df1 and df2 are very large,
# almost using up all available device memory:
df1 = cudf.read_csv("species.csv")
df2 = cudf.read_csv("countries.csv")

result1 = df1.groupby("name").max()  # if we run out of memory doing this, spill `df2` and try again
result2 = df2.max()  # at this point, unspill `df2`
```

A nice side effect of being able to do this is we effectively increase the granularity at which [Dask spilling](https://docs.rapids.ai/api/dask-cuda/stable/spilling.html) occurs (objects within tasks can now be spilled, rather than just objects that go in and out  of tasks).

**Comment by vyasr** [comment]
This was resolved in #12106 (with further enhancements pending).
