### ISSUE TITLE
[BUG] `repr` of `datetime` values that are not truly out of range wrapping around

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#11708]
**Describe the bug**
We perform a `to_pandas` call in our `datetime` related `repr` code, which results in displaying incorrect DateTime values for date values that are out of range in `ns` representation(`ns` because that is the only dtype pandas supports). But incase of `cudf` it wouldn't have overflowed. See example below.

**Steps/Code to reproduce bug**
```python
In [1]: import cudf

In [2]: import pyarrow as pa

In [3]: s = cudf.Series(pa.array(["1969-12-31 23:59:58.001001", "1839-12-24 03:58:56.000826", "1647-05-20 19:25:03.000638"]).cast(pa.timestamp('us')))

In [4]: s
Out[4]: 
0   1969-12-31 23:59:58.001001000
1   1839-12-24 03:58:56.000826000
2   2231-12-09 18:59:36.710189616
dtype: datetime64[us]

In [5]: s[2]
Out[5]: numpy.datetime64('1647-05-20T19:25:03.000638')
```

**Expected behavior**
```
In [4]: s
Out[4]: 
0   1969-12-31 23:59:58.001001
1   1839-12-24 03:58:56.000826
2   1647-05-20 19:25:03.000638
dtype: datetime64[us]
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Comment by galipremsagar** [comment]
cc: @vuule

**Comment by shwina** [comment]
Same as https://github.com/rapidsai/cudf/issues/11155?

**Comment by galipremsagar** [comment]
> Same as #11155?

Yup, closing in favor of #11155
