### ISSUE TITLE
[DOC] Docs say to build libcudf doxygen using `make docs_cudf`, which doesn't work.

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#11719]
## Report incorrect documentation

**Location of incorrect documentation**

cudf/cpp/doxygen/developer_guide/DOCUMENTATION.md

**Describe the problems or issues found in the documentation**

> The libcudf documentation can also be built using `make docs_cudf` from the cmake build directory (e.g. `cpp/build`).

The above suggestion does not work. 

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

* Also tried in `cpp/build/release`.
* Also tried `make docs_libcudf` and `make doc_cudf`.

**Suggested fix for documentation**

Remove this from the docs or make the command work.

**Comment by davidwendt** [comment]
The `make docs_cudf` works for me. What error are you seeing?
Also, if you are using `ninja` instead of `make` then it would be `ninja docs_cudf`.

**Comment by harrism** [comment]
Ahhhh. `ninja docs_cudf` works. Please update DOCUMENTATION.md to reflect this.

**Comment by harrism** [comment]
Here's how I did it in cuSpatial. https://github.com/rapidsai/cuspatial/pull/667/commits/17634db119b11918f66a4289606df7477a282bd1
