### ISSUE TITLE
Write csv without scientific notation[QST]

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#11722]
**What is your question?**
Hello, I met a problem to write data into csv file with a scientific notation. Do we have a workaround to remove the scientific notation?  Appreciate it if anyone has an idea about it.
```python
>>> import cudf
>>> df = cudf.DataFrame({'a':[0.0000009]})
>>> df.to_csv('test.csv', float_format='%.15f')

$ cat test.csv
		a
0	9.0e-07 

#expected behavior
$ cat test.csv
		a
0	0.0000009

```

**Comment by davidwendt** [comment]
Sorry, there is no workaround for this.
Scientific notation is used for numbers less then 0.0001 or greater than 1,000,000.

**Comment by MikeChenfu** [comment]
Thanks @davidwendt . It was working to convert it to decimal and write it as csv.

**Comment by davidwendt** [comment]
Ah. That is a good idea.
Can we close this then?

**Comment by MikeChenfu** [comment]
Yes, thanks again!
