### ISSUE TITLE
The segmented_sort.cu should align with sort_column.cu implementation

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#11729]
There are some inconsistencies in the sort logic used by `sort_column.cu` and `segmented_sort.cu` both use a radix-sort optimization but apply different logic for handling nulls and fixed-width types. Overall the logic should match to provide predictable results. One such occurrence appears in #11630 where NaNs are handled incorrectly. This logic was already correct in the `sort_column.cu` implementation.
Upon fixing #11630 in #11703 we found other discrepancies like handling of fixed-point types. It also appears that chrono-types are not handled in the same was as well.
Using the `is_relationally_comparable` trait should help align these two implementations after #11703 is merged.

Additional reference: https://github.com/rapidsai/cudf/pull/11703#issuecomment-1253674563

**Comment by davidwendt** [comment]
Looks like the `sort_column.cu`'s `is_radix_sort_supported()` should match the one in `segmented_sort.cu` (in PR #11703). The `sort_column.cu` logic uses `thrust::sort_by_key` to call the CUB radix-sort routines. But thrust catches the chrono types will not work and automatically funnels those types to thrust's internal merge-sort function instead.

**Comment by davidwendt** [comment]
Here is how the current sorting.hpp functions and are implemented for a single column.

| API | Implementation |
| ---- | ---- |
| [cudf::sorted_order](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga234cbe8106e60ecbbaf5704e1da0762c) |  copies input column, creates sequence column and calls `thrust::sort_by_key` (fast-sort) or `thrust::sort` (with comparator) |
| [cudf::stable_sorted_order](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga35d35d83d9966ee78b9e1a09c130c28a) | copies input column, creates sequence column and calls `thrust::stable_sort_by_key` (fast-sort) or `thrust::stable_sort` (with comparator) |
| [cudf::sort](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga63ae5bdac795a9829eda093339cf5a6d) | calls [cudf::detail::sorted_order](https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/sort/sort_column.cu#L124) and `cudf::detail::gather` |
| [cudf::sort_by_key](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga6db0403a43150b3bca0fbb9b2fbd68a3) | calls [cudf::detail::sorted_order](https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/sort/sort_column.cu#L124) and `cudf::detail::gather` |
| [cudf::stable_sort_by_key](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#gaea04f441fe246b5a7e4f6420864024d4) | calls `cudf::detail::stable_sorted_order` and `cudf::detail::gather` |
| [cudf::segmented_sorted_order](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga3d4c24b51165b9fd8c7eab606f3f63c8) | builds segmented-indices vector and calls `cudf::detail::sorted_order` |
| [cudf::stable_segmented_sorted_order](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#ga42b8777a373f5af6e35326a66bf43807) | builds segmented-indices vector and calls `cudf::detail::stable_sorted_order` |
| [cudf::segmented_sort_by_key](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#gad2a62f87331cba87994e9002a06f691d) | calls `cudf::detail::segmented_sorted_order` and `cudf::detail::gather` |
| [cudf::stable_segmented_sort_by_key](https://docs.rapids.ai/api/libcudf/stable/group__column__sort.html#gad43d4e87fbd37f9b60a132fc8e9cbf5d) | calls `cudf::detail::stable_segmented_sorted_order` and `cudf::detail::gather` |
| [cudf::lists::sort_lists](https://docs.rapids.ai/api/libcudf/stable/group__lists__sort.html#gaf8ff72fd3b5f48441e926e0d44d91ae4) | specialized logic to call `DeviceSegementedRadixSort::SortPairs` for integral types otherwise it calls `cudf::detail::segmented_sort_by_key` |
| [cudf::lists::stable_sort_lists](https://docs.rapids.ai/api/libcudf/stable/group__lists__sort.html#gaf6b57ec3845b3e25899a1c225fdd06f9) | calls `cudf::detail::stable_segmented_sort_by_key` |

thrust calls for reference
| API | Implementation |
| ---- | ---- |
| [thrust::sort](https://thrust.github.io/doc/group__sorting_ga3f47925d80f4970d5730051dba1c5603.html#ga3f47925d80f4970d5730051dba1c5603) | calls `cub::DeviceRadixSort::SortKeys` if possible otherwise calls `cub::DeviceMergeSort::SortKeys`  |
| [thrust::sort_by_key](https://thrust.github.io/doc/group__sorting_gabe038d6107f7c824cf74120500ef45ea.html#gabe038d6107f7c824cf74120500ef45ea) | calls `cub::DeviceRadixSort::SortPairs` if possible otherwise calls `cub::DeviceMergeSort::SortPairs` |
| [thrust::stable_sort_by_key](https://thrust.github.io/doc/group__sorting_gac6960b926c89bc29ffcfb4f451a4f2ef.html#gac6960b926c89bc29ffcfb4f451a4f2ef) | calls `cub::DeviceRadixSort::SortPairs` if possible otherwise calls `cub::DeviceMergeSort::StableSortPairs` |

**Comment by davidwendt** [comment]
Optimization for single-column sort reference issue #8634
The optimization work is to be separate from this work.

**Comment by GregoryKimball** [comment]
Nice work @davidwendt! Are there any outstanding tasks associated with this issue?

**Comment by davidwendt** [comment]
> Nice work @davidwendt! Are there any outstanding tasks associated with this issue?

Nothing outstanding currently. But I'll be working on fixing this. I just don't have any PRs open at the time.

**Comment by davidwendt** [comment]
The code has be aligned with the reference PRs.
The table above has also been updated to reflect the current implementation.
