### ISSUE TITLE
libcudf gtests unit tests should not be coded in namespace cudf or namespace cudf::*::test

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#11734]
Remove using `using namespace cudf;` and `using namespace cudf::test;` from gtests.
Likewise remove unit test source coded inside `namespace cudf {}` or `namespace cudf::test {}` 
The unit tests should not be considered part of `cudf` or the `cudf::test` infrastructure but rather consumers of them. This will help with maintenance (no confusion where functions are defined) and with verifying the libcudf APIs can be called outside of `cudf` namespace.

Reference discussion: https://github.com/rapidsai/cudf/pull/11703#discussion_r975884822

List of `cpp/tests/` that have `cudf` namespaces
- [x] `binaryop/*` (all 9 files)
- [x] `bitmask/is_element_valid_tests.cpp`
- [x] `copying/gather_struct_tests.cpp`
- [x] `copying/get_value_tests.cpp`
- [x] `copying/pack_tests.cpp`
- [x] `copying/purge_non_empty_nulls_test.cpp`
- [x] `copying/scatter_list_scalar_tests.cpp`
- [x] `copying/scatter_list_tests.cpp` (`using namespace cudf::test;`)
- [x] `copying/scatter_struct_scalar_tests.cpp`
- [x] `groupby/*` (about 33/37 of the files)
- [x] `hashing/hash_test.cpp` (`using namespace cudf::test;`)
- [x] `interop/dlpack_test.cpp` (`using namespace cudf::test;`)
- [x] `io/fst/common.hpp`
- [x] `io/fst/fst_test.cu`
- [x] `io/text/data_chunk_source_test.cpp` (`using namespace cudf::test;`)
- [x] `io/text/multibyte_split_test.cpp` (`using namespace cudf::test;`)
- [x] `io/json_tree.cpp`
~- [ ] `io/metadata_utilities.cpp`~
- [x] `lists/contains_tests.cpp`
- [x] `lists/explode_tests.cpp` (`using namespace cudf::test;`)
- [x] `quantiles/percentile_approx_test.cu` (`using namespace cudf;`)
- [x] `quantiles/quantile_test.cpp` (`using namespace cudf::test;`)
- [x] `quantiles/quantiles_test.cu` (`using namespace cudf::test;`)
- [x] `quantiles/tdigest_utilities.cu` (move to `tests/utilities`)
- [x] `reductions/collect_ops_tests.cpp`
- [x] `reductions/rank_tests.cpp`
- [x] `reductions/segmented_reduction_tests.cpp`
- [x] `reductions/tdigest_tests.cu`
- [x] `replace/replace_nans_test.cpp`
- [x] `reshape/byte_cast_tests.cpp`
- [x] `reshape/tile_tests.cpp` (`using namespace cudf::test;`)
- [x] `rolling/grouped_rolling_range_test.cpp`
- [x] `rolling/lead_lag_test.cpp` (`using namespace cudf::test;`)
- [x] `rolling/nth_element_test.cpp`
- [x] `rolling/range_rolling_window_test.cpp`
- [x] `rolling/range_window_bounds_test.cpp`
- [x] `sort/*` (all 5 files)
- [x] `strings/utilities.cpp` (remove or move to utilities/)
- [x] `strings/utilities.h` (remove or move to utilities/)
- [x] `structs/utilities_tests.cpp`
- [x] `table/experimental_row_operator_tests.cu` (`using namespace cudf::test;`)
- [x] `transform/integration/assert-unary.h`
- [x] `transform/integration/unary-transform-test.cpp`
- [x] `transform/one_hot_encode_tests.cpp`
- [x] `transform/row_bit_count_test.cu` (`using namespace cudf;`)

This is 89 files out of 293 total files.

**Comment by karthikeyann** [comment]
`io/metadata_utilities.cpp` is part of `cudftestutil` static library where all their utility functions are defined inside `cudf::test` namespace. So, this file should be skipped from this list.

**Comment by karthikeyann** [comment]
All usages in gtest and also benchmarks are addressed.
