### ISSUE TITLE
[BUG] Misleading error when casting huge arrays from long to string

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#11743]
**Describe the bug**

I have the following code to cast longs to string.

``` java
int n = 1_000_000_000;
try (ColumnVector cv = ColumnVector.fromScalar(Scalar.fromLong(Long.MAX_VALUE), n);
     ColumnVector cv2 = cv.castTo(DType.STRING)) {
  // success
}
```

When `n` is `900_000_000`, this fails, quite reasonably, with an `out_of_memory` error.

When `n` is `1_000_000_000`, then it fails with:

```
ai.rapids.cudf.CudaFatalException: for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Steps/Code to reproduce bug**
See code sample above.

**Expected behavior**
It would be nice to add appropriate checks so that this case also fails with `out_of_memory`.

**Environment overview (please complete the following information)**
Desktop

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 0ba4675056929b070082e4ac2aa8465da253469f (HEAD)
     Author: Elias Stehle <3958403+elstehle@users.noreply.github.com>
     Date:   Tue Sep 20 07:29:01 2022 +0200
     
     Adds type inference and type conversion for leaf-columns to the nested JSON parser (#11574)
     
     Adds type inference and type conversion for leaf-columns to the nested JSON parser
     
     **Note to the reviewers**:
     It's important to note that we're talking about two different stages of quote-stripping here.
     
     1. Including/excluding quotes in the tokenizer stage (currently always set to `true` using a `constexpr bool`)
     2. Including/excluding quotes in the type conversion stage
     
     Currently, we always include quotes in the tokenizer stage (1), such that the type casting stage (2) can differentiate between string values and literals (e.g. `[true, "true"]`) and, based on the user-provided choice in `json_reader_options::keep_quotes`, can strip off the quotes or keep them in the values returned to the user.
     
     **In addition to adding type inference and type casting:**
     - Switches logic for inferring nested columns. Inferring any column with at least one nested item (list or struct) as that respective nested column, making all other _non-nested_ items of that column invalid. E.g., `[null,{"a":1},"foo"] => List<Struct<a:int>> with struct col validity: 0, 1, 0`
     - Adds option for `keep_quotes` to differentiate between string values and numeric & literal values, like (`123.4`, `true`, `false`, `null`).
     - Migrated libcudf test to cudf test to avoid having large byte BLOBs in source file
     - Changing column order to match the behaviour of pandas and existing JSON lines reader. That is, column order corresponds to the order they were discovered in: `[{"b":1, "c":1}, {"a":1}] => order: <b, c, a>`
     - Support for escape sequences (see below)
     
     ## Performance comparison
     
     ### Tokenizer
     The following is a comparison of the **JSON tokenizer** stage before this PR and after:
     
     #### Before
     ```
     # Benchmark Results
     
     ## json_tokenizer
     
     ### [0] Tesla V100-SXM2-32GB
     
     |    string_size    | Samples | CPU Time  | Noise | GPU Time  | Noise |  Elem/s  |
     |-------------------|---------|-----------|-------|-----------|-------|----------|
     |    2^20 = 1048576 |   2176x |  2.489 ms | 9.62% |  2.480 ms | 9.61% | 422.729M |
     |    2^21 = 2097152 |   1936x |  2.501 ms | 7.14% |  2.492 ms | 7.12% | 841.482M |
     |    2^22 = 4194304 |   1152x |  2.612 ms | 5.43% |  2.604 ms | 5.42% |   1.611G |
     |    2^23 = 8388608 |   1456x |  2.855 ms | 4.26% |  2.847 ms | 4.23% |   2.947G |
     |   2^24 = 16777216 |   1104x |  3.395 ms | 5.34% |  3.387 ms | 5.33% |   4.954G |
     |   2^25 = 33554432 |    560x |  4.410 ms | 2.25% |  4.402 ms | 2.25% |   7.623G |
     |   2^26 = 67108864 |   1552x |  6.482 ms | 2.23% |  6.473 ms | 2.22% |  10.367G |
     |  2^27 = 134217728 |   1435x | 10.430 ms | 2.70% | 10.422 ms | 2.70% |  12.879G |
     |  2^28 = 268435456 |    815x | 18.396 ms | 1.95% | 18.387 ms | 1.95% |  14.599G |
     |  2^29 = 536870912 |     15x | 34.389 ms | 0.42% | 34.381 ms | 0.42% |  15.615G |
     | 2^30 = 1073741824 |     11x | 66.097 ms | 0.20% | 66.088 ms | 0.20% |  16.247G |
     ```
     
     
     #### After
     ```
     # Benchmark Results
     
     ## json_tokenizer
     
     ### [0] Tesla V100-SXM2-32GB
     
     |    string_size    | Samples |  CPU Time  | Noise  |  GPU Time  | Noise  |  Elem/s  |
     |-------------------|---------|------------|--------|------------|--------|----------|
     |    2^20 = 1048576 |   1408x |   2.600 ms | 11.28% |   2.592 ms | 11.26% | 404.547M |
     |    2^21 = 2097152 |    800x |   2.838 ms |  7.68% |   2.829 ms |  7.67% | 741.243M |
     |    2^22 = 4194304 |   2752x |   3.719 ms |  9.24% |   3.710 ms |  9.23% |   1.130G |
     |    2^23 = 8388608 |    128x |   4.855 ms |  3.38% |   4.846 ms |  3.37% |   1.731G |
     |   2^24 = 16777216 |    720x |   7.029 ms |  4.67% |   7.021 ms |  4.66% |   2.390G |
     |   2^25 = 33554432 |    832x |  10.760 ms |  3.83% |  10.751 ms |  3.83% |   3.121G |
     |   2^26 = 67108864 |    576x |  17.961 ms |  2.86% |  17.953 ms |  2.86% |   3.738G |
     |  2^27 = 134217728 |    461x |  32.550 ms |  2.13% |  32.542 ms |  2.13% |   4.124G |
     |  2^28 = 268435456 |    243x |  61.813 ms |  1.60% |  61.805 ms |  1.60% |   4.343G |
     |  2^29 = 536870912 |    125x | 120.445 ms |  1.21% | 120.437 ms |  1.21% |   4.458G |
     | 2^30 = 1073741824 |     66x | 228.833 ms |  0.75% | 228.825 ms |  0.75% |   4.692G |
     
     ```
     
     
     ### JSON Parser
     
     The overall parser performance is obviously impacted as we're now also doing type conversion instead of just returning string columns.
     
     #### Before
     ```
     # Benchmark Results
     
     ## nested_json_gpu_parser
     
     ### [0] Tesla V100-SXM2-32GB
     
     |    string_size    | Samples |  CPU Time  | Noise |  GPU Time  | Noise |  Elem/s  |
     |-------------------|---------|------------|-------|------------|-------|----------|
     |    2^20 = 1048576 |   1040x |   7.361 ms | 5.61% |   7.353 ms | 5.61% | 142.614M |
     |    2^21 = 2097152 |    832x |  11.549 ms | 3.63% |  11.541 ms | 3.63% | 181.708M |
     |    2^22 = 4194304 |    740x |  20.264 ms | 2.98% |  20.257 ms | 2.98% | 207.054M |
     |    2^23 = 8388608 |    407x |  36.844 ms | 2.26% |  36.837 ms | 2.26% | 227.724M |
     |   2^24 = 16777216 |     80x |  75.590 ms | 1.95% |  75.582 ms | 1.95% | 221.974M |
     |   2^25 = 33554432 |     80x | 179.442 ms | 4.40% | 179.434 ms | 4.40% | 187.001M |
     |   2^26 = 67108864 |     40x | 379.821 ms | 0.98% | 379.815 ms | 0.98% | 176.688M |
     |  2^27 = 134217728 |     20x | 777.351 ms | 1.72% | 777.347 ms | 1.72% | 172.661M |
     |  2^28 = 268435456 |     10x |    1.550 s | 0.99% |    1.550 s | 0.99% | 173.212M |
     |  2^29 = 536870912 |      5x |    3.055 s | 0.41% |    3.055 s | 0.41% | 175.749M |
     | 2^30 = 1073741824 |      3x |    6.315 s |  inf% |    6.315 s |  inf% | 170.018M |
     ```
     
     #### After
     ```
     |    string_size    | Samples |  CPU Time  | Noise |  GPU Time  | Noise |  Elem/s  |
     |-------------------|---------|------------|-------|------------|-------|----------|
     |    2^20 = 1048576 |   1568x |   7.908 ms | 5.24% |   7.900 ms | 5.24% | 132.730M |
     |    2^21 = 2097152 |    576x |  12.235 ms | 3.24% |  12.228 ms | 3.24% | 171.509M |
     |    2^22 = 4194304 |    192x |  21.171 ms | 2.09% |  21.164 ms | 2.09% | 198.182M |
     |    2^23 = 8388608 |     96x |  38.990 ms | 1.96% |  38.983 ms | 1.96% | 215.188M |
     |   2^24 = 16777216 |    192x |  78.414 ms | 2.21% |  78.407 ms | 2.21% | 213.977M |
     |   2^25 = 33554432 |     81x | 187.007 ms | 6.47% | 187.000 ms | 6.47% | 179.435M |
     |   2^26 = 67108864 |     38x | 400.007 ms | 1.59% | 400.000 ms | 1.59% | 167.772M |
     |  2^27 = 134217728 |     19x | 801.575 ms | 1.29% | 801.571 ms | 1.29% | 167.443M |
     |  2^28 = 268435456 |     10x |    1.590 s | 0.42% |    1.590 s | 0.42% | 168.799M |
     |  2^29 = 536870912 |      5x |    3.150 s | 0.40% |    3.150 s | 0.40% | 170.456M |
     | 2^30 = 1073741824 |      3x |    6.402 s |  inf% |    6.402 s |  inf% | 167.712M |
     ```
     
     
     ## Supported escape sequences:
     ```
     \" represents the quotation mark character (U+0022).
     \\ represents the reverse solidus character (U+005C).
     \/ represents the solidus character (U+002F).
     \b represents the backspace character (U+0008).
     \f represents the form feed character (U+000C).
     \n represents the line feed character (U+000A).
     \r represents the carriage return character (U+000D).
     \t represents the character tabulation character (U+0009).
     \uDDDD, where `D` is a hex digit 0-9, a-f, A-F, for code points on the MBP
     \uDDDD\uDDDD, where `D` is a hex digit 0-9, a-f, A-F, representing UTF-16 surrogate pairs for remaining unicode code points
     ```
     
     Authors:
     - Elias Stehle (https://github.com/elstehle)
     - Vukasin Milovanovic (https://github.com/vuule)
     - Yunsong Wang (https://github.com/PointKernel)
     - Karthikeyan (https://github.com/karthikeyann)
     
     Approvers:
     - Michael Wang (https://github.com/isVoid)
     - Karthikeyan (https://github.com/karthikeyann)
     - Vukasin Milovanovic (https://github.com/vuule)
     
     URL: https://github.com/rapidsai/cudf/pull/11574
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
     NAME="Ubuntu"
     VERSION="20.04.3 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.3 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux nvworkstation 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Sep 22 10:01:59 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 6000     On   | 00000000:17:00.0 Off |                  Off |
     | 44%   67C    P2   111W / 260W |    970MiB / 24220MiB |    100%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A      1411      G   /usr/lib/xorg/Xorg                  4MiB |
     |    0   N/A  N/A    193705      C   ...penjdk-amd64/jre/bin/java      481MiB |
     |    0   N/A  N/A    202213      C   ...penjdk-amd64/jre/bin/java      481MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          12
     On-line CPU(s) list:             0-11
     Thread(s) per core:              2
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           85
     Model name:                      Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
     Stepping:                        4
     CPU MHz:                         3500.000
     CPU max MHz:                     4000.0000
     CPU min MHz:                     1200.0000
     BogoMIPS:                        6999.82
     Virtualization:                  VT-x
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        6 MiB
     L3 cache:                        8.3 MiB
     NUMA node0 CPU(s):               0-11
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.16.3
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/andygrove/miniconda3/bin/python
     Python 3.9.1
     
     ***Environment Variables***
     PATH                            : /home/andygrove/.local/bin:/home/andygrove/miniconda3/bin:/home/andygrove/miniconda3/condabin:/home/andygrove/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin://opt/apache-maven-3.8.1/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/andygrove/miniconda3
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/andygrove/miniconda3/bin/conda
     # packages in environment at /home/andygrove/miniconda3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     attrs                     21.2.0                   pypi_0    pypi
     brotlipy                  0.7.0           py39h27cfd23_1003
     ca-certificates           2020.12.8            h06a4308_0
     certifi                   2020.12.5        py39h06a4308_0
     cffi                      1.14.4           py39h261ae71_0
     chardet                   3.0.4           py39h06a4308_1003
     conda                     4.9.2            py39h06a4308_0
     conda-package-handling    1.7.2            py39h27cfd23_1
     cryptography              3.3.1            py39h3c74f83_0
     idna                      2.10                       py_0
     iniconfig                 1.1.1                    pypi_0    pypi
     ld_impl_linux-64          2.33.1               h53a641e_7
     libedit                   3.1.20191231         h14c3975_1
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.1.0                hdf63c60_0
     libstdcxx-ng              9.1.0                hdf63c60_0
     ncurses                   6.2                  he6710b0_1
     numpy                     1.23.3                   pypi_0    pypi
     openssl                   1.1.1i               h27cfd23_0
     packaging                 21.0                     pypi_0    pypi
     pandas                    1.4.4                    pypi_0    pypi
     pip                       20.3.1           py39h06a4308_0
     pluggy                    0.13.1                   pypi_0    pypi
     py                        1.10.0                   pypi_0    pypi
     pyarrow                   9.0.0                    pypi_0    pypi
     pycosat                   0.6.3            py39h27cfd23_0
     pycparser                 2.20                       py_2
     pyopenssl                 20.0.0             pyhd3eb1b0_1
     pyparsing                 2.4.7                    pypi_0    pypi
     pysocks                   1.7.1            py39h06a4308_0
     pytest                    6.2.4                    pypi_0    pypi
     python                    3.9.1                hdb3f193_2
     python-dateutil           2.8.2                    pypi_0    pypi
     pytz                      2022.2.1                 pypi_0    pypi
     readline                  8.0                  h7b6447c_0
     requests                  2.25.0             pyhd3eb1b0_0
     ruamel_yaml               0.15.80          py39h27cfd23_0
     setuptools                51.0.0           py39h06a4308_2
     six                       1.15.0           py39h06a4308_0
     sqlite                    3.33.0               h62c20be_0
     sre-yield                 1.2                      pypi_0    pypi
     tk                        8.6.10               hbc83047_0
     toml                      0.10.2                   pypi_0    pypi
     tqdm                      4.54.1             pyhd3eb1b0_0
     tzdata                    2020d                h14c3975_0
     urllib3                   1.25.11                    py_0
     wheel                     0.36.1             pyhd3eb1b0_0
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h7b6447c_0
     zlib                      1.2.11               h7b6447c_3
     
</pre></details>

**Additional context**
None

**Comment by ttnghia** [comment]
As mentioned in https://github.com/NVIDIA/spark-rapids/issues/6598, this is because overflow of the output column size (https://github.com/rapidsai/cudf/blob/d2414582d853fa32960a59cb052aaaf814b1153e/cpp/src/strings/convert/convert_integers.cu#L381).

**Comment by davidwendt** [comment]
The output size of a strings column is limited to 2GB. In the worse case, a long can be 18 digits plus a sign character. So converting longs to strings would be limited to 127 million rows (2,415,919,103/19 = 127,153,637). Using this as an upper bound should prevent an overflow.

**Comment by andygrove** [comment]
Thank you for the info @davidwendt and @ttnghia

**Comment by davidwendt** [comment]
Can we close this isssue?

**Comment by andygrove** [comment]
Yes, I'll go ahead and close this.
