### ISSUE TITLE
[FEA] Improve/refactor the column wrapper (for testing)

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1178]
The column wrapper has several shortcomings in terms of its existing functionality, and some missing functionality.

Examples:

* Can't iterate through its elements, i.e. `for (auto x& : my_column_wrapper) { do_stuff(); }` (even not via a proxy.
* Can't use it with standard library algorithms: fill, copy, iota etc.
* Fixation with `std::vector`s (in its method's parameters; on the inside this is not a problem
* Can't read a single value
* Need to consider keeping both a host-side and a device-side aspect of the column at all times, so that each can be changed, and they can be synched when necessary

There are also some minor style issues like the use of the word `row` for indices when a column doesn't have any rows etc.

**Comment by harrism** [comment]
Please submit a PR for things like this if you feel strongly about them. I don't think we are running into actual usability issues with column_wrapper at this point. I consider all of the above "nice to have", although in practice if they aren't used, they are just adding complexity. I'm going to close this issue for now. Please reopen it if you run into actual problems in testing or if you contribute improvements.
