### ISSUE TITLE
[FEA] Implement overloads for CUDA atomic operations 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1179]
**Is your feature request related to a problem? Please describe.**
CUDA atomic functions are not natively supported for some types, like `int64_t` but we need this functionality for our algorithms. 

**Describe the solution you'd like**

Where possible, there should be overloads for all of the `atomic*` operations for all of the underlying types of the `gdf_dtype` enums, e.g., int8_t, int16_t, int64_t, and the `wrapper` types.

These should be of the form:

`atomicCAS(int8_t * address, int8_t compare, int8_t val)`

For types smaller than 4B, this will require careful bit-shiffting and masking. 

The desired atomic operations for now are:

`atomicMax`
`atomicMin`
`atomicCAS`
`atomicAdd`

**Comment by kovaltan** [comment]
The true generic atomicCAS for int8_t and int16_t like `int8_t atomicCAS(int8_t * address, int8_t compare, int8_t val)` is very hard without CUDA's official support for int8_t, int16_t `atomicCAS` while cuda `atomicCAS` supports uint32_t and uint64_t.

For example of problem at `int8_t atomicCAS(int8_t * address, int8_t compare, int8_t val)`:

do {
	assumed  = old;
	const int8_t val = op(update_value, old_value);
	old = atomicCAS(addr, assumed, val);
} while (assumed != old);


if `*addr = 0xaa 0xbb 0xcc 0xdd` and `assumed = 0xdd, val = 0xee` at the least byte.
Then other thread writes to *base_address_of32 as `0xee 0xbb 0xcc 0xdd`
`atomicCAS` failed and returns value `0xee 0xbb 0xcc 0xdd`. It is different from old value.
Though, the least byte value is still `0xdd` and it's same with assumed.
The return value of old would be `0xdd`, and it breaks the while loop without writing the val.

In PL #1005, I've wrote generic atomic operation for int8_t and int16_t.
  https://github.com/rapidsai/cudf/blob/8ddb744a716aa8fe736284272b065cf5b7085065/cpp/src/reductions/reduction_operators.cuh#L20-L43
It is possible if the updating binary operation is defined. But the true generic atomicCAS for int8_t and int16_t is not possible.

`atomicCAS` will be supported for 32bit or 64bit.
`atomicMax`, `atomicMin`, `atomicCAS`, `atomicAdd` under 64-bits are possible.
