### ISSUE TITLE
[BUG] Existing `int8_t` and `int16_t` overloads for atomicCAS are broken

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1180]
**Describe the bug**

There are overloads defined for `atomicCAS` on `int8_t` and `int16_t` types. However, they do not do what they should.

https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/hash/helper_functions.cuh#L34

For example:

If we have 4 `int8_t` as `int8_t[4] arr = {0xaa, 0xbb, 0xcc, 0xdd}` assume `&arr[0] == 0x0000`

We want to update `arr[0]` to `0xff`, then `int_val = 0x00 0x00 0x00 0xff`

and `int_comp = 0xaa 0xbb 0xcc 0xdd`

after the CAS, `arr = {0x00, 0x00, 0x00, 0xff}`

*NOTE: This means Join/Groupby are likely both broken for `int8_t` and `int16_t`.`

**Additional context**

It should be possible to create a correct overload of `int8_t` `atomicCAS` by constructing an `int32_t` `compare` value based on the specified `int8_t` compare value and the surrounding bytes, e.g.,

Assuming my above example:

`atomicCAS( &arr[0], (int8) 0xaa, (int8) 0xff)`

Then you can construct `int32_t int_compare = {0xaa, 0xbb, 0xcc, 0xdd}` by computing the base address of `&arr[0]` and combining `0xaa` with the surrounding bytes. 

Should be fixed by https://github.com/rapidsai/cudf/issues/1179

**Comment by harrism** [comment]
@kovaltan was this issue fixed by #1179?

**Comment by kovaltan** [comment]
No, atomicCAS for int8 and int16 is not supported at #1179 
As I mentioned at #1179 
int8 atomicCAS(int8*, int8, int8) is theoretically not possible. 
It's detailed at: https://github.com/rapidsai/cudf/issues/1179#issuecomment-472542570

Please use `atomicCAS(int32)` or `cudf::genericAtomicOperation` instead.

**Comment by harrism** [comment]
I don't see why `int16` is not supported since CUDA has atomicCAS for `unsigned short`: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomiccas

**Comment by harrism** [comment]
Also, Bob Crovella has a worked example of atomicCAS for 8-bit types here: https://stackoverflow.com/a/53380080/749748

**Comment by kovaltan** [comment]
> I don't see why `int16` is not supported since CUDA has atomicCAS for `unsigned short`: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#atomiccas

I guess it's documentation fault.
Indeed, there is no API declaration for `atomicCAS(int16)` at cuda's atomic header.
And I also verified `ATOM.CAS` only supports `.U32 .S32 .U64 `

> Also, Bob Crovella has a worked example of atomicCAS for 8-bit types here: https://stackoverflow.com/a/53380080/749748

If it is ensured that other thread never writes other byte in the 32bits,  Bob Crovella's suggestion will work. Otherwise, it will fail.

For example, this can be failed.
'''
int8 *arr;
atomicCAS(&arr[0], assume, new);
atomicCAS(&arr[1], assume, new);
atomicCAS(&arr[2], assume, new);
'''

**Comment by harrism** [comment]
The internal CAS loop ensures that only one thread updates the whole word (32 bits) at a time.  If thread A calls atomicCAS and gets out a value for "old" that is different than the value it thinks is there ("assumed"), then it tries again. 

The key is to look at the *whole* 32-bit value at the address, not just the byte the thread is interested in. The flaw in your counterexample on #1179 is that you are assuming the thread only compares the byte of interest in `old` and `assumed`. As long as it compares the whole word, it will see the difference and try again.

**Comment by kovaltan** [comment]
After the long discussion with Mark, it seems feasible to implement `atomicCAS` for int8/16_t.
Opened a PR for this.
