### ISSUE TITLE
[BUG] Allow string to numeric conversion with "dtype" argument in JSON reader

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#11817]
**Describe the bug**
The `cudf.read_json` does not correctly convert from strings to numeric type when `engine='cudf_experimental'` is set and the `dtype` argument specifies a numeric type. `engine='cudf'` and pandas both support strings to numeric casting.

**Steps/Code to reproduce bug**
```
>>> cudf.read_json(StringIO('{"k": "1"}'), engine='cudf_experimental', lines=True, dtype={'k': 'int'})
   k
0  0
>>> cudf.read_json(StringIO('{"k": "1"}'), engine='cudf', lines=True, dtype={'k': 'int'})
   k
0  1
>>> pd.read_json(StringIO('{"k": "1"}'), lines=True, dtype={'k': 'int'})
   k
0  1
```

**Expected behavior**
I expect the string data to be converted into the specified numeric dtype when possible, and to be null when it cannot be cast.

**Environment overview (please complete the following information)**
docker image "rapidsai/rapidsai-dev-nightly", "22.10-cuda11.5-devel-ubuntu18.04-py3.8", "418d71a6792c"
cudf built from source on commit `9e9ba6e8518cf36c42fdbdd60276bd414444827e`

**Additional context**
The behavior when some of the strings cannot be cast is currently not consistent. For now this issue addresses the case where all the strings cast as valid integers, but we may want to broaden the scope.
```
>>> pd.read_json(StringIO('{"k": "1"}\n{"k":"a"}'), lines=True, dtype={'k': 'int'})
   k
0  1
1  a
>>> cudf.read_json(StringIO('{"k": "1"}\n{"k":"a"}'), lines=True, dtype={'k': 'int'})
    k
0   1
1  10
>>> cudf.read_json(StringIO('{"k": "1"}\n{"k":"a"}'), lines=True, engine='cudf_experimental', dtype={'k': 'int'})
   k
0  0
1  0
```

**Comment by wence-** [comment]
```
>>> cudf.read_json(StringIO('{"k": "1"}\n{"k":"a"}'), lines=True, dtype={'k': 'int'})
    k
0   1
1  10
```

cudf default engine is reading in base-16:

```
Int[30]: cudf.read_json(StringIO('{"k": "1"}\n{"k":"g"}'), lines=True, dtype={'k': 'int'})
Out[30]: 
   k
0  1
1  0
```
