### ISSUE TITLE
[BUG] Resolve parquet writer issue with "timedelta64[s]" and "timedelta64[ms]"

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#11833]
**Describe the bug**
When we write a `cudf.DataFrame` containing columns with types `timedelta64[s]` or `timedelta64[ms]` to a parquet file, libcudf assigns that column `col_schema.type = Type::INT64` and `col_schema.converted_type = ConvertedType::TIME_MILLIS` ([libcudf code pointer](https://github.com/rapidsai/cudf/blob/920b58f9488802ad50258c858cef34a5fd162676/cpp/src/io/parquet/writer_impl.cu#L392)). However, these parquet files cannot be read by pandas or by cuDF because `TIME_MILLIS can only annotate INT32`. (See [logical types reference](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#deprecated-time-convertedtype) in parquet-format.) libcudf can still read the files, but cuDF fails because it uses pyarrow to extract data from the header before reading.

**Steps/Code to reproduce bug**
```
>>> df = cudf.DataFrame({'a':[1]}, dtype='timedelta64[ms]')
>>> df.to_parquet('ms.pq')
>>> cudf.read_parquet('ms.pq')
...
OSError: Error creating dataset. Could not read schema from '/nfs/repo/cudf-22.10/ms.pq': 
Could not open Parquet input source '/nfs/repo/cudf-22.10/ms.pq': TIME_MILLIS can only
 annotate INT32. Is this a 'parquet' file?

>>> df = cudf.DataFrame({'a':[1]}, dtype='timedelta64[s]')
>>> df.to_parquet('s.pq')
>>> cudf.read_parquet('s.pq')
...
OSError: Error creating dataset. Could not read schema from '/nfs/repo/cudf-22.10/s.pq': 
Could not open Parquet input source '/nfs/repo/cudf-22.10/s.pq': TIME_MILLIS can only 
annotate INT32. Is this a 'parquet' file?
```

**Expected behavior**
Write parquet files with timedelta[ms] columns that can be read by pandas and cuDF.

**Environment overview (please complete the following information)**
docker image "rapidsai/rapidsai-dev-nightly", "22.10-cuda11.5-devel-ubuntu18.04-py3.8", "418d71a6792c"
cudf built from source on commit "9e9ba6e8518cf36c42fdbdd60276bd414444827e"

**Environment details**
n/a

**Additional context**
We could address this issue in a few ways:
* use the `int32` physical type for `duration_s` and `duration_ms`
* use `TIME_MICROS` converted type with a scale factor
* implement the logical type `TIME` and use `TimeType (isAdjustedToUTC = true, unit = MILLIS)` 
Let's please discuss the pros and cons.

**Comment by vuule** [comment]
After a lot more digging:

1. IMO we should be using `int32` for `duration_d`, `duration_s` and `duration_ms` (Parquet type TIME_MILLIS);
2. cudf Parquet reader assumes `int64` timestamp and duration types in input files. This is incorrect and also needs to be fixed. The first part uncovers this.
3. cudf Parquet reader applies timestamp_type to diruation types as well. This seems incorrect, but also means that the kernel needs to know the cudf column type. If we disable this, we can avoid this new complexity.
4. Types `TIME_MILLIS` and `TIME_MICROS` are deprecated, so we probably want to invest in writing as `TIME` (+unit).

> use TIME_MICROS converted type with a scale factor
This is quick way to make the writer compliant, but does not help the reader inconsistencies.
