### ISSUE TITLE
[FEA] Byte-range support in "cudf_experimental" JSON reader

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#11843]
**Is your feature request related to a problem? Please describe.**
Similar to `read_csv`, `read_text` and `read_json(engine='cudf')`, I would like to add byte-range support to `read_json(engine='cudf_experimental')`. Byte-range support makes it possible to read files that are larger than GPU memory or contain columns larger than the libcudf column size limit.

**Describe the solution you'd like**
Add support for a naive byte-range reading in `read_json(engine='cudf_experimental')`. This byte-range implementation should not attempt to respect quoted delimiters, and should only be available when `lines=True`. The implementation searches for the first carriage return in the byte range to determine where to begin reading. If the byte range ends with a carriage return, then stop reading there, otherwise read past the byte range until the next carriage return.

**Describe alternatives you've considered**
For now we are using the read_text byte range, converting to a host buffer, and performing read_json on that buffer.

**Additional context**
@upsj has begun work on a parsing context-aware byte range support for `read_csv` in https://github.com/rapidsai/cudf/issues/11728. Ultimately we want all of the text readers to respect parsing context when finding record offsets in a byte range, but for now this issue only requests naive byte range support (assumes no quoted record delimiters).

**Comment by karthikeyann** [comment]
Naive byte range support is added in #12017

For missing fields, there are 2 problems. 
1. empty columns (list children) or all null columns should be created in chunks missing fields.
2. different type deducted in different chunks

problem 1) could be addressed at last stage by sharing column type, size, order information.
problem 2) can be addressed via different approaches,
- Similar to dask CSV reader, JSON dask reader also could parse only first few records of the first chunk, and use this type information for all other chunks. (The limitation is that first record should have all columns and necessary information to deduct right type for each column).
- column tree reduction - should also reduce the type information in each chunk, collate them together and broadcasted. But dask being out of core computing, dask workers cannot retain the data, or the further tasks cannot go to same worker. So, each chunk parsing has to be done again after type deduction-reduce-broadcast. (The limitation is that algorithm has to re-parse, tree traverse again after type decuction.)

**Comment by GregoryKimball** [comment]
Closed by #12017
