### ISSUE TITLE
[FEA] Groupby ngroup

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#11848]
I'd like to be able to call `df.groupby().ngroup()` like I can in pandas to get [the number of each group from 0 to the number of groups - 1](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.GroupBy.ngroup.html).

```python
import pandas as pd

df = pd.DataFrame({
    "a": [0,0,1,1,0],
    "b": range(5),
})

df.groupby("a").ngroup()
0    0
1    0
2    1
3    1
4    0
dtype: int64
```

This was originally requested in https://github.com/rapidsai/cudf/issues/1720 to enable some functionality in Dask, but we were able to get around this at the time.

**Comment by shwina** [comment]
It's just a little bit more involved than that -- it just so happened that you used `0` and `1` in your key column, and that you had only a single key column. It wouldn't work for example if you had:

```python
df = cudf.DataFrame({
    ...:     "a": [1, 1, 2, 2, 1],
    ...:     "b": [2, 2, 3, 2, 1],
    ...:     "c": range(5),
    ...: })
df.groupby(["a", "b"]).ngroup()
```

I think I have an idea for an implementation -- will open a PR in a bit.

**Comment by beckernick** [comment]
Ah, good point :smiley:
