### ISSUE TITLE
[BUG]libcudf example doesn't build because of hardcoded old googletest version

### ISSUE THREAD

**Issue by Char-Aznable** [rapidsai/cudf#11908]
**Describe the bug**

I am trying to build the libcudf example using cpp/examples/build.sh. It seems cudf hardcodes googletest version 1.10 into its config, which hits bugs https://github.com/google/googletest/issues/3219 and https://github.com/google/googletest/issues/4026 and therefore won't build. 

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

clone this repo and run cpp/examples/build.sh

**Expected behavior**

The examples should be built.

**Environment overview (please complete the following information)**
 - Environment location: ubuntu 22.04, gcc 11.2 nvcc 11.7
 - Method of cuDF install: source
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by Char-Aznable** [comment]
I'm not entirely sure whether this bug is due to libcudf's cmake config or rather it's due to rapids-cmake's https://github.com/rapidsai/rapids-cmake/blob/branch-22.12/rapids-cmake/cpm/versions.json file that hardcodes googletest version 1.10

**Comment by davidwendt** [comment]
I'm not able to reproduce this. Can you paste what error you are seeing? Can you try with gcc 9.5 ?

**Comment by Char-Aznable** [comment]
The error was exactly those in the OP of https://github.com/google/googletest/issues/3219. I don't have gcc 9.5 but gcc 9.4 can compile without error.

**Comment by davidwendt** [comment]
@robertmaynard

**Comment by vyasr** [comment]
RAPIDS is now on gtest 1.13 so this shouldn't be an issue any longer.
