### ISSUE TITLE
[FEA] Support "COLLECT" aggregation on struct columns in cuDF

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#11907]
**Is your feature request related to a problem? Please describe.**
I would like to perform `COLLECT` aggregations on `Struct` columns.  Based on initial triage by @shwina , adding `COLLECT` to `_STRUCT_AGGS` in [groupby.pyx](https://github.com/rapidsai/cudf/blob/branch-22.12/python/cudf/cudf/_lib/groupby.pyx#L61) would be the first step.

**Describe the solution you'd like**
I would like `groupby.agg(list)` to be supported for Struct columns.

**Describe alternatives you've considered**
I couldn't find a way to construct a nested `List<Struct>` without doing a device-host roundtrip and assembling a new `cudf.DataFrame`. If there are other tools we could use to pack a `Struct` column into a `List` column I would love to know. 

**Additional context**
Here is an example of packing a `Struct` column into a `List` column.
```
>>> df = cudf.DataFrame(index=[0,0,1], data={'a':[
...    {'k':'v1'}, {'k':'v2'}, {'k':'v3'}
... ]})
>>> df
             a
0  {'k': 'v1'}
0  {'k': 'v2'}
1  {'k': 'v3'}
>>> df.groupby(level=0).agg(list)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/groupby/groupby.py", line 458, in agg
    ) = self._groupby.aggregate(columns, normalized_aggs)
  File "groupby.pyx", line 295, in cudf._lib.groupby.GroupBy.aggregate
  File "groupby.pyx", line 185, in cudf._lib.groupby.GroupBy.aggregate_internal
pandas.core.base.DataError: All requested aggregations are unsupported.
>>> expected = cudf.DataFrame({'a':[
...    [{'k':'v1'}, {'k':'v2'}],[{'k':'v3'}]
... ]})
>>> expected
                            a
0  [{'k': 'v1'}, {'k': 'v2'}]
1               [{'k': 'v3'}]
```

**Comment by GregoryKimball** [comment]
Note, simply adding the `COLLECT` aggregation works to create a `List` column, but the full dtype is not preserved. 
```
>>> df = cudf.DataFrame(index=[0,0,1], data={'a':[
...    {'k':'v1'}, {'k':'v2'}, {'k':'v3'}
... ]})
>>> df.groupby(level=0).agg(list)
                            a
0  [{'0': 'v1'}, {'0': 'v2'}]
1               [{'0': 'v3'}]
```
See [11687](https://github.com/rapidsai/cudf/pull/11687), [11671](https://github.com/rapidsai/cudf/pull/11671).

**Comment by ttnghia** [comment]
Sorry is this FEA for Python or Java?
We have the `collect_list` aggregation and I'm still not clear on what is difference from `COLLECT` here?

**Comment by wence-** [comment]
Pretty sure this is for Python (have updated labels); as @GregoryKimball notes if you add `"COLLECT"` to the set of supported aggregations here

https://github.com/rapidsai/cudf/blob/387192c2b3659c872b27497aef033a5abcdb5444/python/cudf/cudf/_lib/groupby.pyx#L61

then libcudf will generate columns with the correct data. However, since struct dtype field names are managed in Python the field names are lost. Similar to #11687, I think this can be fixed by transferring relevant dtype information over post-hoc.
