### ISSUE TITLE
[BUG] Broken "rapids include" symlink reference when build.sh PREFIX is set

### ISSUE THREAD

**Issue by ochan1** [rapidsai/cudf#11913]
**Describe the bug**
Rapids from Version 21.12 to 22.02 (with libcudf 21.12.02 to 22.02.00) had some kind of setting change where when I set the PREFIX to consolidate the final build files into a folder called INSTALL (via `export PREFIX=INSTALL` ... as allowed in the [build.sh file](https://github.com/rapidsai/cudf/blob/v22.06.00/build.sh#L76)), the `include/rapids/libcxx/include` file (with the last `include` being a symlink file) has a broken symlink when exported since it does not do a deep copy anymore starting v22

Because now that the `include` file is symlinked in v22 rather than deep copied in v21, the export using the PREFIX will have that symlink reference not relative since the folder it is symlinked to is also not exported

Unsure if this is intended behavior, but the symlink is broken for sure compared to the past starting from v22 and up

The include folder in the original build has this symlink that is successful

Starting v22, that directory in the `cpp/build` build folder is symlinked

v21 does a deep copy even within the `cpp/build` build folder before the files are sent to PREFIX

This doesn't break any of libcudf's tests

For what I use libcudf for, it fails when I do a CMake `copy_directory` of the completed build into another folder since the symlink is not kept when consolidated to my defined `PREFIX` location

Rapids 21.12 to 22.02 comparison link: https://github.com/rapidsai/rapids-cmake/compare/branch-21.12..branch-22.02

**Steps/Code to reproduce bug**
1. set PREFIX to a destination folder: (Example: `export PREFIX=INSTALL`) ... also make the folder (`mkdir INSTALL`) on the root of the project
2. Build libcudf (`build.sh libcudf `, but I use: `build.sh libcudf tests --cmake-args=\"-DCUDF_ENABLE_ARROW_S3=OFF\"`)
3. Wait till completion
4. Navigate to `include/rapids/libcxx/include` file and the symlink is broken
5. Optionally, in a larger project, try to `copy_directory` that folder to a different one and the copy will break

**Expected behavior**
I assume that symlink should be linked to the original folder, either it should be deep copied or that `../include/cuda/std/detail/libcxx/include` folder should also be copied in the libcudf build scripts when exporting to PREFIX

**Environment overview (please complete the following information)**
 - Environment location: AWS Linux 20.02
 - Method of cuDF install: From Source

**Additional context**
![image](https://user-images.githubusercontent.com/29664484/195453040-507cd566-83b8-46f4-b2c1-d65b317875ac.png)

**Comment by GregoryKimball** [comment]
Thank you @ochan1 for sharing this issue. Are you interested in doing testing with a more recent version of libcudf - or is there some reason you must target 22.02?

**Comment by ochan1** [comment]
I am okay with doing testing with later versions of libcudf, unless there are major changes in the API

**Comment by ochan1** [comment]
This issue was fixed in v22.12.02 with whatever decision they made, so I will close the Issue
