### ISSUE TITLE
[BUG] multibyte_split implicitly synchronizes all streams

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#11929]
**Describe the bug**
Currently `multibyte_split` uses a stream pool to divide up work between multiple streams. However, `output_builder.inplace_resize` still resizes an `rmm::device_uvector` on [CUDA's default stream](https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/io/text/multibyte_split.cu#L528). This function is being called from `output_builder.advance_output`, which does not currently accept a stream. This is problematic since the default stream implicitly synchronizes with all streams. 

**Expected behavior**
From a quick analysis it is not clear to me whether `advance_output` or `inplace_resize` should be running on the `scan_stream` or the `read_stream` inside `multibyte_split`. [Based on where `advance_output` is called](https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/io/text/multibyte_split.cu#L553k), I suspect that it actually requires an explicit synchronization between these two streams, and perhaps the existing events are already intended to solve that need. Fixing this would require modifying this function to run on the appropriate stream, and perhaps introducing an explicit synchronization or some appropriate event waiting.

**Comment by vyasr** [comment]
Perhaps @upsj or @cwharris have some insight into the appropriate fix here.

**Comment by upsj** [comment]
Does this actually synchronize? [`device_uvector` doesn't](https://github.com/rapidsai/rmm/blob/5a6d7a6994889ba3b2ab8b3635f29642e322cc99/include/rmm/device_uvector.hpp#L387) and [`device_buffer` doesn't either](https://github.com/rapidsai/rmm/blob/branch-22.12/include/rmm/device_buffer.hpp#L294) in the shrinking case, as far as I can tell. It only modifies the `size` member appropriately.
I have a choice between two approaches: Use device_uvector as a fixed-sized buffer and store its actual size separately, or use size and capacity to keep track of how many elements inside the vector are already in use. What do you think - should this be marked/documented more explicitly or store the size separately?

**Comment by vyasr** [comment]
> Does this actually synchronize? [device_uvector doesn't](https://github.com/rapidsai/rmm/blob/5a6d7a6994889ba3b2ab8b3635f29642e322cc99/include/rmm/device_uvector.hpp#L387) and [device_buffer doesn't either](https://github.com/rapidsai/rmm/blob/branch-22.12/include/rmm/device_buffer.hpp#L294) in the shrinking case, as far as I can tell. It only modifies the size member appropriately.

You're right that neither of those synchronizes. However, [`device_buffer::resize` sets the stream used for deallocating the buffer](https://github.com/rapidsai/rmm/blob/branch-22.12/include/rmm/device_buffer.hpp#L296), which ends up triggering a sync on that stream when [the destructor of the uvector is called](https://github.com/rapidsai/rmm/blob/branch-22.12/include/rmm/device_buffer.hpp#L234). Both `char_storage` and `row_offset_storage` are function scoped, so they are only destroyed at the end of the function when this function's frame is popped off the stack. [`join_streams` is called well before that](https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/io/text/multibyte_split.cu#L745) and it looks like the input `stream` is set to wait on both the streams in the pool, so I think all that needs to happen is that the input stream needs to get passed through `advance_output` to `inplace_resize` so that the vectors in the two `output_builder`s (`char_storage` and `row_offset_storage`) are destroyed on the user-provided input stream, i.e. after all work in multibyte split is done but without using the default stream and triggering a sync _at the end of `multibyte_split`_, which will be undesirable once we expose a truly stream-ordered API that allows users to run multiple libcudf APIs (or other external functions) simultaneously on different streams.

**Comment by upsj** [comment]
Thanks for the details, I'll adopt your suggestions

**Comment by vyasr** [comment]
@upsj in the interest of making sure everything works together I saved you the time and have gone ahead and implemented my proposed solution in #11875. Tests still pass for me locally, so I think it should be OK, but I'll keep you apprised if something goes wrong!
