### ISSUE TITLE
[FEA] cudf.DataFrame.from_dict

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#11934]
**Is your feature request related to a problem? Please describe.**
rewriting code from pandas into cudf, trying to use `import cudf as pd`

**Describe the solution you'd like**
`cudf.DataFrame.from_dict` matching https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html

**Comment by rjzamora** [comment]
+1 to this feature (and to it's `dask_cudf` counterpart).

**Comment by quasiben** [comment]
From a call with @shwina.  We can already do something dict things like:


```python
In [4]: cudf.DataFrame({'a': cudf.Series([1,2,3]), 'b': cudf.Series([4,5,6], index=[9,10,11])})
Out[4]:
       a     b
0      1  <NA>
1      2  <NA>
2      3  <NA>
9   <NA>     4
10  <NA>     5
11  <NA>     6
```

Hmm, actually the DataFrame constructor is pretty robust:


```python
In [19]: cudf.DataFrame({'c': ['a', 'b', 'd'], 'b': cudf.Series([1, 2, 3]), 'd': pd.Series([10, 11, 12])})
Out[19]:
   c  b   d
0  a  1  10
1  b  2  11
2  d  3  12

In [23]: cudf.DataFrame({'a': cudf.Series([1,2,3]), 'b': cudf.Series([4,5,6], index=[9,10,11]),'c': pd.Series(['q', 'r', 's'])})
Out[23]:
       a     b     c
0      1  <NA>     q
1      2  <NA>     r
2      3  <NA>     s
9   <NA>     4  <NA>
10  <NA>     5  <NA>
11  <NA>     6  <NA>
```
@mattf can you, as a test, check if the standard constructor works for your usecase ?  If so, maybe this is as easy as redirecting `from_dict` to `DataFrame(...)`

**Comment by rjzamora** [comment]
@quasiben - I also suspect that `cudf.from_dict` can simply wrap `cudf.DataFrame` - Probably raising a `NotImplementedError` for `orient="index"` and `orient="tight"`.  In the long run, it may be nice to support the same `orient` options as `pandas`. However,  the most important thing is probably that the API *exists*. 

**More context**: The `dask.dataframe.DataFrame` constructor does not accept a `dict`-like argument, and so `dd.from_dict` is now the recommended way to create a Dask-DataFrame from `dict`-formatted data. Now that `dd.from_dict` is backend-dispatchable, it would be nice to be able to call into an explicit `cudf/dask_cudf.DataFrame` method for the "cudf" backend.

**Comment by mattf** [comment]
@quasiben the cudf.DataFrame constructor works for the specific case i have, but the most important thing is the API matches what pandas.DataFrame.from_dict provides

**Comment by GregoryKimball** [comment]
@mattf Would you please provide a specific case where `pandas` and cudf` diverge in `from_dict` behavior?

**Comment by rjzamora** [comment]
>Would you please provide a specific case where pandas and cudf diverge infrom_dict` behavior?

I think the problem is that there is no `cudf.DataFrame.from_dict` method at all.

**Comment by mattf** [comment]
@GregoryKimball `pandas.DataFrame.from_dict` exists and `cudf.DataFrame.from_dict` does not
