### ISSUE TITLE
[FEA] UDF support on string columns

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#1195]
**Is your feature request related to a problem? Please describe.**
Hi,

When trying to execute `applymap()` on a string column, it seems that it is not implemented yet.

**Describe the solution you'd like**
I think it would be very useful to be able to invoke `applymap()` on string columns.

**Describe alternatives you've considered** 
None yet.

**Additional context**
Thanks!

**Comment by miguelangel** [comment]
Hi,

I was wondering if there is any update on this issue.

Thanks!

Miguel

**Comment by beckernick** [comment]
As noted in https://github.com/rapidsai/cudf/issues/3646, this is a challenging problem due to dynamic memory allocation and branching behavior and being explored in the long term. I'm going to close this issue to consolidate further discussion in #3802
