### ISSUE TITLE
[BUG] Disable verbose output on merge

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1196]
On `merge` there is rather verobse output:

```
left dtype 0: 4
left mask_size: 0
left dtype 1: 3
left mask_size: 0
out dtype 0: 3
left dtype 2: 3
left mask_size: 0
out dtype 1: 3
left ....
```

Can this be removed or disabled ?

**Comment by kkraus14** [comment]
> On `merge` there is rather verobse output:
> 
> ```
> left dtype 0: 4
> left mask_size: 0
> left dtype 1: 3
> left mask_size: 0
> out dtype 0: 3
> left dtype 2: 3
> left mask_size: 0
> out dtype 1: 3
> left ....
> ```
> Can this be removed or disabled ?

This is removed in the latest string branch. Apologies.

**Comment by quasiben** [comment]
👍
