### ISSUE TITLE
[FEA] Make `experimental/read_json.hpp` the default JSON reading engine

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#11982]
**Is your feature request related to a problem? Please describe.**
Let's make `engine='cudf_experimental'` the default JSON reader. 

**Describe the solution you'd like**

1. refactor cuDF's `read_json` to use the nested JSON reader by default
2. refactor libcudf to promote the experimental JSON reader
3. refactor libcudf to begin deprecating the legacy JSON reader

**Describe alternatives you've considered**
n/a

**Additional context**
Please review the [nested JSON reader](https://github.com/rapidsai/cudf/milestone/13) milestone

**Comment by vuule** [comment]
What is left to do here? IIRC, just internal code reorg to match the new default (namespace shuffle). is that correct?

**Comment by karthikeyann** [comment]
Correct.
