### ISSUE TITLE
[FEA] CUDF cannot read binary encoded decimal values in parquet

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#11993]
**Describe the bug**
The parquet spec says that you should be able to encode any decimal type as a binary (like a string). When I try to do this CUDF throws an exception saying it is not supported.

[tmp.zip](https://github.com/rapidsai/cudf/files/9862988/tmp.zip)

```
cudf/cpp/src/io/parquet/reader_impl_helpers.cu:124: Invalid representation of decimal type
```

**Steps/Code to reproduce bug**
The attached zip file above has two parquet files in it. One has a single column and the other has 3 columns.

**Expected behavior**
Ideally we would like to have CUDF parse the values and return a DECIMAL column that is sized based off of the size of the precision.  Precision <= 9 is DECIMAL32
Precision <= 18 && > 9 is DECIMAL64
Precision <= 38 && > 18 is DECIMAL128
Precision > 38 is an error

Also when parsing the data it is possible to have binary data that is larger than the given type will hold. To be compatible with Spark ideally if the higher order bytes are zero, then they are ignored and the data is returned. If the resulting data is too large to fit then that should also throw an exception. But this should really be rare.

**Comment by revans2** [comment]
If you need another file https://github.com/daveoshinsky/drill/blob/d2372a892216269a71425175c2b2ad9b02941261/exec/java-exec/src/test/resources/parquet/varlenDecimal.parquet is a file created for the same kind of issue on a different project.

If you need me to include the data in these files I am happy to do it.

**Comment by GregoryKimball** [comment]
Thanks @revans2 for raising this issue. It looks like we added the `parquet::FIXED_LEN_BYTE_ARRAY` physical type for decimal during the `DECIMAL128` push.

For context, here is the description of [binary physical types for decimal](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#decimal) in the parquet spec. Where can we find out more about how this representation works? How many bits go to precision? 

I suppose we ought to change the [error](https://github.com/rapidsai/cudf/blob/b7d011528af766294e84e4dafd483c650fb5901b/cpp/src/io/parquet/reader_impl.cu#L145) from `"Invalid representation of decimal type"` to `Not implemented`...
