### ISSUE TITLE
[QST] Does cudf support cuda 10.1 ? 

### ISSUE THREAD

**Issue by mai1x9** [rapidsai/cudf#12028]
**Does cudf by any chance support cuda `10.1`, If so can anyone mention what is the version of cudf to be install to support cuda `10.1`. ?**

If it does not support cuda `10.1` any other alternatives. ?

**Comment by bdice** [comment]
Hi @mai1x9, the current 22.10 releases of RAPIDS packages (including cuDF) require CUDA 11.2 or newer. However, old versions of RAPIDS may support CUDA 10.1. Release v0.19 was the last version with support for CUDA 10.1: https://docs.rapids.ai/notices/rsn0006/

I'll close this for now. Feel free to re-open if you have any additional questions! 👍

**Comment by mai1x9** [comment]
How can I install `0.19` version. tried running 
```
pip3 install cudf==0.19
```
and resulted in below error.
```
ERROR: Could not find a version that satisfies the requirement cudf==0.19 (from versions: 0.6.1.post1)
ERROR: No matching distribution found for cudf==0.19
```
@bdice any suggestions for right way of installing.

**Comment by bdice** [comment]
Try installing with conda or use a Docker image. We did not support pip installation prior to the current 22.10 release. See https://rapids.ai for installation instructions. You will need to try to replace the current version number with 0.19.
