### ISSUE TITLE
Nightly build only using one gpu for E2E workflow

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#1203]
**Describe the bug**
In the nightly container build, Using the E2E scripted (no notebook) with 8 GPUs and 8 parts only uses one GPU for all 8 parts.  Works as expected in the NGC Rapids container for 0.5.1 cuda 9.2 with all 8 GPUs each reading a single part.

The CUDA_VISIBLE_DEVICES in each Dask Worker is shuffled correctly with each worker having a unique first gpu assignment.  All read_csv happen on GPU 0.

If I set the CUDA_VISIBLE_DEVICES in the environment before running the python script, all read_csv happen on the first GPU environment setting.
> export CUDA_VISIBLE_DEVICES=7,6,5,4,3,2,1,0
> run E2E.py
> All read_csv happen on GPU 7

**Steps/Code to reproduce bug**
Pull nightly build
Run E2E script with n gpus and n parts

**Expected behavior**
Watching nvidia-smi, all gpus should have utilization and data loaded

**Environment details (please complete the following information):**
Container: rapidsai/rapidsai-nightly
Server: I am on a DGX-1v, any multi-gpu system should work
Data: Mortgage data from Rapids.ai 
Script: E2E.py, run.sh
Execute: ./run.sh -g 8 -p 8

**Additional context**
Files available upon request if needed.

**Comment by randerzander** [comment]
Closing, as this is resolved in nightly containers per @kenhester 's offline comments.

Please re-open if this is actually still a problem.
