### ISSUE TITLE
[BUG] cudf.read_csv() fails with much smaller data than pandas.read_csv() followed by cudf.from_pandas()

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cudf#1204]
**Describe the bug**
It seems like cudf.read_csv() requires much more memory than pandas.read_csv() followed by cudf.from_pandas(). The latter combination can read nearly 2.5x larger data than cudf.read_csv().

**Steps/Code to reproduce bug**
The test graph data is located in /datasets/pagerank_demo/1/Input-gigantic/edges on DGX servers (e.g. dgx07 & dgx202). part-00000 file in this directory is approximately 19 GB (ascii) and contains two columns with little fewer than 1.2B rows. Each element is 32bit, so the final binary data size is less than 10 GB. On a V100 GPU with 32 GB memory, Code 1 (see below) successfully finishes while Code 2 (see below) crashes with the following error message. To successfully run Code 2, I need to reduce the data size by more than half while Code 1 can read data even (a bit) larger than the test data.

>>> cudf.read_csv(file_path, delimiter='\t',  names=['src', 'dst'], dtype=['int32', 'int32'])
terminate called after throwing an instance of 'cudf::cuda_error'
  what():  CUDA error encountered at: /home/seunghwak/RAPIDS/cudf/cpp/src/io/csv/csv_reader.cu:810: 77 cudaErrorIllegalAddress an illegal memory access was encountered
Aborted (core dumped)

Code 1
```python
import numpy as np
import pandas as pd

import cudf

file_path = r"/datasets/pagerank_demo/1/Input-gigantic/edges/part-00000"

df = pd.read_csv(file_path, delimiter='\t',  names=['src', 'dst'], dtype={'src': np.int32, 'dst': np.int32})
gdf = cudf.from_pandas(df)
```

Code2
```python
import cudf

file_path = r"/datasets/pagerank_demo/1/Input-gigantic/edges/part-00000"

cudf.read_csv(file_path, delimiter='\t',  names=['src', 'dst'], dtype=['int32', 'int32'])
```

**Expected behavior**
Ideally, Code 2 should be able to read data as long as the final binary data is smaller than GPU memory size (with some margin for temporary data, but this temporary data should not be huge). Also, a better error description (something indicative of memory allocation failure than illegal memory access) is desirable on actual memory allocation failure.

**Environment details (please complete the following information):**
Bare-metal, V100 GPU with 32 GB memory.

cuDF installed from source.

(base) seunghwak@seunghwak-linux:~/RAPIDS/cudf$ ./print_env.sh 
**git***
commit bc42147b672a40fb1a38079ea4aca3ea9dae1fdc (HEAD -> branch-0.7, origin/branch-0.7, origin/HEAD)
Merge: 39e2dcd0 19972f8f
Author: gpuCI <38199262+GPUtester@users.noreply.github.com>
Date:   Thu Mar 14 20:39:19 2019 -0400

    Merge pull request #1201 from rapidsai/branch-0.6
    
    [gpuCI] Auto-merge branch-0.6 to branch-0.7 [skip ci]

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux seunghwak-linux 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Fri Mar 15 08:03:48 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.39       Driver Version: 418.39       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro GV100        Off  | 00000000:15:00.0 Off |                  Off |
| 30%   43C    P2    38W / 250W |      0MiB / 32478MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Quadro GV100        Off  | 00000000:2D:00.0  On |                  Off |
| 36%   49C    P0    39W / 250W |    177MiB / 32470MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    1      1263      G   /usr/lib/xorg/Xorg                            72MiB |
|    1      1314      G   /usr/bin/gnome-shell                         103MiB |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              12
On-line CPU(s) list: 0-11
Thread(s) per core:  2
Core(s) per socket:  6
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
Stepping:            4
CPU MHz:             1200.122
CPU max MHz:         3700.0000
CPU min MHz:         1200.0000
BogoMIPS:            6800.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-11
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke flush_l1d

***CMake***
/usr/local/cmake/bin/cmake
cmake version 3.12.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***

***Python***
/home/seunghwak/Program/anaconda3/bin/python
Python 3.7.1

***Environment Variables***
PATH                            : /home/seunghwak/bin:/home/seunghwak/.local/bin:/usr/local/cmake/bin:/home/seunghwak/Program/anaconda3/bin:/home/seunghwak/Program/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH                 : 
NUMBAPRO_NVVM                   : 
NUMBAPRO_LIBDEVICE              : 
CONDA_PREFIX                    : /home/seunghwak/Program/anaconda3
PYTHON_PATH                     : 

***conda packages***
/home/seunghwak/Program/anaconda3/bin/conda
# packages in environment at /home/seunghwak/Program/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0  
alabaster                 0.7.12                   py37_0  
anaconda                  2018.12                  py37_0  
anaconda-client           1.7.2                    py37_0  
anaconda-navigator        1.9.6                    py37_0  
anaconda-project          0.8.2                    py37_0  
asn1crypto                0.24.0                   py37_0  
astroid                   2.1.0                    py37_0  
astropy                   3.1              py37h7b6447c_0  
atomicwrites              1.2.1                    py37_0  
attrs                     18.2.0           py37h28b3542_0  
babel                     2.6.0                    py37_0  
backcall                  0.1.0                    py37_0  
backports                 1.0                      py37_1  
backports.os              0.1.1                    py37_0  
backports.shutil_get_terminal_size 1.0.0                    py37_2  
beautifulsoup4            4.6.3                    py37_0  
bitarray                  0.8.3            py37h14c3975_0  
bkcharts                  0.2                      py37_0  
blas                      1.0                         mkl  
blaze                     0.11.3                   py37_0  
bleach                    3.0.2                    py37_0  
blosc                     1.14.4               hdbcaa40_0  
bokeh                     1.0.2                    py37_0  
boto                      2.49.0                   py37_0  
bottleneck                1.2.1            py37h035aef0_1  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2018.03.07                    0  
cairo                     1.14.12              h8948797_3  
certifi                   2018.11.29               py37_0  
cffi                      1.11.5           py37he75722e_1  
chardet                   3.0.4                    py37_1  
click                     7.0                      py37_0  
cloudpickle               0.6.1                    py37_0  
clyent                    1.2.2                    py37_1  
colorama                  0.4.1                    py37_0  
conda                     4.6.8                    py37_0  
conda-build               3.17.6                   py37_0  
conda-env                 2.6.0                         1  
conda-verify              3.1.1                    py37_0  
contextlib2               0.5.5                    py37_0  
cryptography              2.4.2            py37h1ba5d50_0  
curl                      7.63.0            hbc83047_1000  
cycler                    0.10.0                   py37_0  
cython                    0.29.2           py37he6710b0_0  
cytoolz                   0.9.0.1          py37h14c3975_1  
dask                      1.0.0                    py37_0  
dask-core                 1.0.0                    py37_0  
dask-mpi                  1.0.2                    pypi_0    pypi
datashape                 0.5.4                    py37_1  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py37_0  
defusedxml                0.5.0                    py37_1  
distributed               1.25.1                   py37_0  
docutils                  0.14                     py37_0  
entrypoints               0.2.3                    py37_2  
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.6                he6710b0_0  
fastcache                 1.0.2            py37h14c3975_2  
filelock                  3.0.10                   py37_0  
flask                     1.0.2                    py37_1  
flask-cors                3.0.7                    py37_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
future                    0.17.1                   py37_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.7            py37h7b6447c_1  
glib                      2.56.2               hd408876_0  
glob2                     0.6                      py37_1  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py37h10f8cd9_2  
graphite2                 1.3.12               h23475e2_2  
greenlet                  0.4.15           py37h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py37h989c5e5_3  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
heapdict                  1.0.0                    py37_2  
html5lib                  1.0.1                    py37_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0  
imageio                   2.4.1                    py37_0  
imagesize                 1.1.0                    py37_0  
importlib_metadata        0.6                      py37_0  
intel-openmp              2019.1                      144  
ipykernel                 5.1.0            py37h39e3cac_0  
ipython                   7.2.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.4.2                    py37_0  
isort                     4.3.4                    py37_0  
itsdangerous              1.1.0                    py37_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py37_0  
jedi                      0.13.2                   py37_0  
jeepney                   0.4                      py37_0  
jinja2                    2.10                     py37_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.2.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.4.0                    py37_0  
jupyterlab                0.35.3                   py37_0  
jupyterlab_server         0.2.0                    py37_0  
keyring                   17.0.0                   py37_0  
kiwisolver                1.0.1            py37hf484d3e_0  
krb5                      1.16.1               h173b8e3_7  
lazy-object-proxy         1.3.1            py37h14c3975_2  
libarchive                3.3.3                h5d8350f_5  
libcurl                   7.63.0            h20c2e04_1000  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
liblief                   0.9.0                h7725739_1  
libpng                    1.6.35               hbc83047_0  
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h1ba5d50_4  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.9                he85c1e1_2  
libtool                   2.4.6                h7b6447c_5  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.26.0           py37hd408876_0  
locket                    0.2.0                    py37_1  
lxml                      4.2.5            py37hefd8a0e_0  
lz4-c                     1.8.1.2              h14c3975_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.0            py37h7b6447c_0  
matplotlib                3.0.2            py37h5429711_0  
mccabe                    0.6.1                    py37_1  
mistune                   0.8.4            py37h7b6447c_0  
mkl                       2019.1                      144  
mkl-service               1.1.2            py37he904b0f_5  
mkl_fft                   1.0.6            py37hd81dba3_0  
mkl_random                1.0.2            py37hd81dba3_0  
more-itertools            4.3.0                    py37_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.1                hdf1c602_3  
mpmath                    1.1.0                    py37_0  
msgpack-python            0.5.6            py37h6bb024c_1  
multipledispatch          0.6.0                    py37_0  
navigator-updater         0.2.1                    py37_0  
nbconvert                 5.4.0                    py37_1  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  he6710b0_1  
networkx                  2.2                      py37_1  
nltk                      3.4                      py37_1  
nose                      1.3.7                    py37_2  
notebook                  5.7.4                    py37_0  
numba                     0.41.0           py37h962f231_0  
numexpr                   2.6.8            py37h9e4a6bb_0  
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
numpydoc                  0.8.0                    py37_0  
odo                       0.5.1                    py37_0  
olefile                   0.46                     py37_0  
openpyxl                  2.5.12                   py37_0  
openssl                   1.1.1a               h7b6447c_0  
packaging                 18.0                     py37_0  
pandas                    0.23.4           py37h04863e7_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2                    py37_1  
pango                     1.42.4               h049681c_0  
parso                     0.3.1                    py37_0  
partd                     0.3.9                    py37_0  
patchelf                  0.9                  he6710b0_3  
path.py                   11.5.0                   py37_0  
pathlib2                  2.3.3                    py37_0  
patsy                     0.5.1                    py37_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py37_0  
pexpect                   4.6.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    5.3.0            py37h34e0f95_0  
pip                       18.1                     py37_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py37_1  
pluggy                    0.8.0                    py37_0  
ply                       3.11                     py37_0  
prometheus_client         0.5.0                    py37_0  
prompt_toolkit            2.0.7                    py37_0  
psutil                    5.4.8            py37h7b6447c_0  
ptyprocess                0.6.0                    py37_0  
py                        1.7.0                    py37_0  
py-lief                   0.9.0            py37h7725739_1  
pycodestyle               2.4.0                    py37_0  
pycosat                   0.6.3            py37h14c3975_0  
pycparser                 2.19                     py37_0  
pycrypto                  2.6.1            py37h14c3975_9  
pycurl                    7.43.0.2         py37h1ba5d50_0  
pyflakes                  2.0.0                    py37_0  
pygments                  2.3.1                    py37_0  
pylint                    2.2.2                    py37_0  
pyodbc                    4.0.25           py37he6710b0_0  
pyopenssl                 18.0.0                   py37_0  
pyparsing                 2.3.0                    py37_0  
pyqt                      5.9.2            py37h05f1152_2  
pysocks                   1.6.8                    py37_0  
pytables                  3.4.4            py37ha205bf6_0  
pytest                    4.0.2                    py37_0  
pytest-arraydiff          0.3              py37h39e3cac_0  
pytest-astropy            0.5.0                    py37_0  
pytest-doctestplus        0.2.0                    py37_0  
pytest-openfiles          0.3.1                    py37_0  
pytest-remotedata         0.3.1                    py37_0  
python                    3.7.1                h0371630_7  
python-dateutil           2.7.5                    py37_0  
python-libarchive-c       2.8                      py37_6  
pytz                      2018.7                   py37_0  
pywavelets                1.0.1            py37hdd07704_0  
pyyaml                    3.13             py37h14c3975_0  
pyzmq                     17.1.2           py37h14c3975_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.5.3                    py37_0  
qtconsole                 4.4.3                    py37_0  
qtpy                      1.5.2                    py37_0  
readline                  7.0                  h7b6447c_5  
requests                  2.21.0                   py37_0  
rope                      0.11.0                   py37_0  
ruamel_yaml               0.15.46          py37h14c3975_0  
scikit-image              0.14.1           py37he6710b0_0  
scikit-learn              0.20.1           py37hd81dba3_0  
scipy                     1.1.0            py37h7c811a0_2  
seaborn                   0.9.0                    py37_0  
secretstorage             3.1.0                    py37_0  
send2trash                1.5.0                    py37_0  
setuptools                40.6.3                   py37_0  
simplegeneric             0.8.1                    py37_2  
singledispatch            3.4.0.3                  py37_0  
sip                       4.19.8           py37hf484d3e_0  
six                       1.12.0                   py37_0  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1                    py37_0  
sortedcollections         1.0.1                    py37_0  
sortedcontainers          2.1.0                    py37_0  
sphinx                    1.8.2                    py37_0  
sphinxcontrib             1.0                      py37_1  
sphinxcontrib-websupport  1.1.0                    py37_1  
spyder                    3.3.2                    py37_0  
spyder-kernels            0.3.0                    py37_0  
sqlalchemy                1.2.15           py37h7b6447c_0  
sqlite                    3.26.0               h7b6447c_0  
statsmodels               0.9.0            py37h035aef0_0  
sympy                     1.3                      py37_0  
tblib                     1.3.2                    py37_0  
terminado                 0.8.1                    py37_1  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py37_0  
tornado                   5.1.1            py37h7b6447c_0  
tqdm                      4.28.1           py37h28b3542_0  
traitlets                 4.3.2                    py37_0  
unicodecsv                0.14.1                   py37_0  
unixodbc                  2.3.7                h14c3975_0  
urllib3                   1.24.1                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.14.1                   py37_0  
wheel                     0.32.3                   py37_0  
widgetsnbextension        3.4.2                    py37_0  
wrapt                     1.10.11          py37h14c3975_2  
wurlitzer                 1.0.2                    py37_0  
xlrd                      1.2.0                    py37_0  
xlsxwriter                1.1.2                    py37_0  
xlwt                      1.3.0                    py37_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_1  
zict                      0.1.3                    py37_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0

**Comment by mjsamoht** [comment]
When parsing a file we store the beginning of every row or record with an 8-byte offset.  This file has 1.2B rows so that will require 9.6GB just to store all the record offsets.  If you add the 19GB file size we're already getting close to the 32GB of memory available.

The preferred way to handle such large files is to break them up using the `byte_range` option.  Then merge the results.

**Comment by randerzander** [comment]
Also please take a look at [dask-cudf](https://github.com/rapidsai/dask-cudf/), for handling larger than GPU memory datasets.

**Comment by afender** [comment]
Just noticed this has been closed. I'd like to re-open it as I haven't seen the solution for it yet. 
FYI there are good chances that we hit that problem again in the snmg PageRank pipeline @BradReesWork and @kkraus14

Can't we reduce memory requirements at all? The 2 columns in this file are about 10GB total, so it does fit in memory. If we have to go with a hack then :

> The preferred way to handle such large files is to break them up using the byte_range option. Then merge the results.

@mjsamoht, great! Did you implement a feature in the API that supports breaking the file and merging the results? If so, where can we find it? If not please point @seunghwak to the cuDF code that does that so that it can be replicated it in cuGraph. Also, what size should we expect to support with this hack?

>take a look at dask-cudf

@randerzander, that makes sense, do you have an example of a dask-cudf csv read followed by regular cudf/cuml calls? Would you say it is a better hack than what @mjsamoht suggested or should we have people looking at both in parallel?

**Comment by mjsamoht** [comment]
What I suggested is the proper way to process files that are too large to fit into GPU memory.  Let's say you have a 1 TB file, it surely won't fit in GPU memory and the only way to process is to break it up into chunks.  This is exactly what `dask-cudf` does. It uses the `byte_range` option of the CSV reader.
