### ISSUE TITLE
[FEA] Tokenized JSON for Spark

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#12051]
**Is your feature request related to a problem? Please describe.**
Provide public APIs to expose the tokenized JSON String for Spark and other users. 

> To me I want to see a few different public APIs.  One that tokenizes the raw inputs and lets the user decide how to handle the tokens. Just because there will be corner cases that everyone wants to handle differently. The other should be a reference/default implementation that does some form of error checking that matches what a general user would expect.

_Originally posted by @revans2 in https://github.com/rapidsai/cudf/issues/12022#issuecomment-1297304793_
      
**Describe the solution you'd like**
Confirm the  existing data structure and what output Spark expects these tokenized strings. Create a public API to deliver these internal tokens representation to Spark/user.

**Describe alternatives you've considered**
Export the JSON Column as string, But the tokens may not exactly end up in the same column and in same row after custom parsing. So, it's better to leave the token and hierarchy parsing to the user/spark.

**Additional context**
https://github.com/rapidsai/cudf/pull/12022#issuecomment-1297304793

**Comment by revans2** [comment]
I need to spend some more time to make sure I get the requirements properly. But really at a high level what we have today with [tokenization for nested JSON](https://github.com/rapidsai/cudf/blob/aaf251daa1fca7ce34b49d32a8e489ba19b621b7/cpp/src/io/json/nested_json.hpp) should give us what we need.  The main problem is that these are detail APIs in the source, instead of regular APIs we can include and use directly.  But I will try to go through the existing APIs and have something more concrete of a proposal.

**Comment by GregoryKimball** [comment]
Thank you @karthikeyann for opening this issue to track the discussion. 

Speaking of requirements, I understand that there is are "string to map" and "string to tuple" transformations of interest. Here is the example we've been working from as the desired "string to map" transformation:
```
# transform a strings column
s = cudf.Series([
    """{"A": "1", "B": 2}""", 
    """{"C": 100, "A": "TEST"}""", 
    """{"A.B": "SOMETHING"}""", 
    "{}", 
    """{"ONLY HERE": "SPARSE"}"""
])

# into a List<Struct<'key':string, 'value':string>> column
s_out = cudf.Series([
    [{'key': 'A', 'value':'1'}, {'key': 'B', 'value':'2'}],
    [{'key': 'C', 'value':'100'}, {'key': 'A', 'value':'TEST'}],
    [{'key': 'A.B', 'value': 'SOMETHING'}],
    [],
    [{'key': 'ONLY HERE', 'value': 'SPARSE'}],
])
```

**Comment by revans2** [comment]
Yes, Spark has the option of parsing a JSON dictionary as a MAP type. CUDF does not officially supports MAP as a type so we emulate it using a `LIST<STRUCT<key, value>>`. This appears to be very similar to how pandas handles nested JSON data by default converting it to a `dict` with a `dtype` of `object`. Spark also lets us parse it as a `STRUCT` with various children like happens with the nested parser today. I am not a pandas expert so I don't know if there is a way to parse it in a similar way or how CUDF wants to emulate that behavior behind the scenes.  Either way having the flexibility to handle the tokens ourselves lets us play games with how we parse the data to match as closely to spark as possible.  Including odd things like parsing values `"100"` differently from `100` when the output type is a string.

**Comment by GregoryKimball** [comment]
Also see https://github.com/rapidsai/cudf/issues/12476

**Comment by karthikeyann** [comment]
A part of this feature is completed in PR https://github.com/rapidsai/cudf/pull/12432

**Comment by vuule** [comment]
@ttnghia does [#12432](https://github.com/rapidsai/cudf/pull/12432) close this issue?

**Comment by ttnghia** [comment]
No. Actually close this by https://github.com/NVIDIA/spark-rapids-jni/pull/844.
