### ISSUE TITLE
[BUG] CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1205]
I'm having trouble producing a small example however, in working with the mortgage data from fannie mae after filter, merging, and doing a groupby I occasionally get an error like the following:
 
> ERROR:Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE

after getting the error the cudf dataframe is corrupted and I have to restart the notebook.  I'll work on getting a script together to reproduce the error -- for now I wanted to log the error I was seeing

**Comment by kkraus14** [comment]
@quasiben Were you able to reproduce this?

**Comment by harrism** [comment]
Ping @quasiben this is not a useful bug report. Please provide information on how to repro, or close the issue.

**Comment by harrism** [comment]
No answer, closing.

**Comment by quasiben** [comment]
apologies for not being responsive.  If I see the issue again i'll open with a reproducible example

**Comment by ksangeek** [comment]
I have put more detailed in here - https://github.com/rapidsai/notebooks/issues/107 on how I was able to recreate this consistently. Maybe I should have put the details in here as it looks more like a `cuDF` or `cuda` issue and not really a problem with the contents of the notebook!

**Comment by harrism** [comment]
This issue report was always too vague to start with. There are many ways you could get a CUDA error, so best to create a new issue with specific repro instructions.
