### ISSUE TITLE
Best way to know the original shape of a column whose cell values are list[QST]

### ISSUE THREAD

**Issue by arpan-das-astrophysics** [rapidsai/cudf#12053]
I have a data frame where one columns is an a multidimensional array. Since cudf doesn't support storing array, I used tolist() method to store it as a list . Now I want to read the dataframe and reconstruct the original array with it's original shape to do some operation. What is the best way to infer the original shape?? Here is how the dataframe looks like: 

![Screen Shot 2022-11-03 at 2 40 40 PM](https://user-images.githubusercontent.com/23120837/199736139-3f963513-7136-458d-b679-0f49cc18428f.png)

The original array has a shape of (6566400,1,4). But I want to do it in a generic way which will work for any shape and the user who is reading the dataframe should know the shape of the original array from the column only. @shwina tagging you as you have helped previously related to similar issue. 

To reconstruct I am using 
`'''
dftest.FLAG.explode().explode().to_numpy().reshape(len(dftest.FLAG),1,4)
'''` 
My question is how do I know that shape only from the dataframe and not from the original array

**Comment by wence-** [comment]
The dtype of the column is `ListDtype(ListDtype(bool))`, which doesn't constrain the shape of the entries (for example, one row could have `[[False, True], [False]]`, another could have `[[False, True, True, False]]`). But if you're happy that the input data are homogeneous, then you can deduce the shape of a row (and hence the original shape of the column) with:

```python
def shape_of(item):
    shape = []
    while isinstance(item, list):
        shape.append(len(item))
        item = item[0]
    return tuple(shape)

## Use like:
shape = shape_of(dftest.FLAG.iloc[0])

array = dftest.FLAG.explode().explode().to_numpy().reshape(len(dftest.FLAG), *shape)

## Aside, a simpler way of exploding to the flattened column is to use `.list.leaves` on the series
## This is then generic if your data in each row ever becomes 3-D
array = dftest.FLAG.list.leaves.to_numpy().reshape(len(dftest.FLAG), *shape)
## Depending on what you then need to do with the data, you may find you can do
## array processing with cupy (just use to_cupy() rather than to_numpy())
```

**Comment by shwina** [comment]
I'm going to close this question as answered, but please feel free to reopen if you have any follow-up questions, @arpan-das-astrophysics!
