### ISSUE TITLE
[BUG] Conda recipe improvements

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#1210]
Am documenting some observations and suggestions after working a little bit with the recipes in RAPIDS. There are some things that could be improved and simplified by leveraging features from conda-build 3. Also there are some build practices from `defaults` and `conda-forge` that would be good to adopt to avoid some common issues. My hope is this makes things easier to maintain in the long run. May update this list as things come up. Thoughts on this list would be welcome.

* [x] [`host`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#host ) for linked dependencies and `build` for CLI build tools (e.g. https://github.com/rapidsai/custrings/pull/155 )
* [ ] [Build variants]( https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#build-variants ) for `python` instead of `x.x`.
* [ ] Build matrices of different versions using build variants.
* [x] Require `pip` and `setuptools` to be explicitly included (set [`add_pip_as_python_dependency`]( https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#add-pip-as-python-dependency-add-pip-as-python-dependency ) to `False`)
* [x] Disable dependency downloads by `setuptools` or `pip` during build
* [x] Look into building with `pip` ( https://github.com/conda-forge/conda-forge.github.io/pull/518 )
* [x] Avoid requiring `setuptools` in `run` unless `pkg_resources` is used
* [x] Using the new compiler syntax (can be combined with [legacy compilers]( https://github.com/conda-forge/toolchain-feedstock ) in the near term)
* [x] Migrate to the new compilers in `defaults`
* [x] Add a compiler (wrapper?) package for `nvcc` ( https://github.com/conda-forge/staged-recipes/pull/8229 )
* [x] [Split packages]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#outputs-section ) for packages sharing content (e.g. `cudf`)
* [x] [`run_exports`]( https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#run-exports ) for libraries that need to be pinned (e.g. `libcudf`)
* [x] Spacing out version spec from package name ( https://github.com/conda/conda-build/issues/2828 )
* [x] Dynamically linking `cudatoolkit` libraries
* [ ] Preserve other build string content (like the package hash) when altering it (as an [example]( https://github.com/conda-forge/h5py-feedstock/blob/47d0478dad52966954d72bde068ba52b5963c4a4/recipe/meta.yaml#L37 )).

Note: I think these can be saved until things cool down a bit.

**Comment by kkraus14** [comment]
@jakirkham can a subpackage depend on another subpackage? I.E. can the `cudf` subpackage depend on the `libcudf` subpackage? From what I'm seeing it doesn't look possible yet.

**Comment by jakirkham** [comment]
Yes, this should be possible. Here's [an example]( https://github.com/conda-forge/apr-feedstock/tree/master/recipe ).

Were there specific issues that you encountered? Is there a recipe I can look at?

**Comment by jakirkham** [comment]
Have updated the `nvcc` compiler wrapper item (as there is a proposed solution) and added dynamically linking to `cudatoolkit`. Though am happy to discuss these further.

**Comment by jakirkham** [comment]
I'd be curious what the status is here. Also would be willing to help. In particular I think it would be interesting to try and get Conda compilers (and the NVCC wrapper compiler) working on one RAPIDS package (maybe cuDF?) and then see how things go.

**Comment by harrism** [comment]
Moving this old bug to 0.14 and assigning @jakirkham to decide if or how to proceed.

**Comment by jakirkham** [comment]
Sounds good. Thanks Mark! 😄

**Comment by vyasr** [comment]
@jakirkham any idea where we stand on this issue now? At least a few of the above issues no longer seem entirely relevant (e.g. using pip) while others have been addressed (the questions around compilers).

**Comment by jakirkham** [comment]
Certainly things have gotten better, but it looks like there is still more to do here. It will probably require someone to go through this in detail, which I have not yet done, but here are some cursory observations.

From a quick look, it doesn't look like adding `pip` to `requirements/host` is still needed. Setting `add_pip_as_python_dependency` to `False` would happen in either build scripts or Docker images as we decide (though am not seeing that from a quick search). It appears [`python x.x` is still used in `raft`]( https://github.com/rapidsai/raft/blob/fd170116acb7e23ca7dff609e8324ed42e1a6df9/conda/recipes/pylibraft/meta.yaml#L31 ) (cc @cjnolet), which we should drop. This [example is using `setuptools` in `run`]( https://github.com/rapidsai/rapids-examples/blob/0bd267feacdc5b5f7fc7954470d582956c8d69e1/dask-metrics/conda.recipe/meta.yaml#L18 ), but am unclear on whether it is needed. The disabling `pip`/`setuptools` downloads was mostly handled upstream (though there may be edge cases like split packages where we need to be mindful https://github.com/conda/conda-build/issues/3993 , which is easy to do). We are [still doing `python setup.py install`]( https://github.com/rapidsai/cudf/blob/002cb1c45bb04ab249765a307ecbe17569292b7b/build.sh#L334 ), which should be moved to `pip install`. The package [hash is still missing from the build string]( https://github.com/rapidsai/cudf/blob/002cb1c45bb04ab249765a307ecbe17569292b7b/conda/recipes/cudf/meta.yaml#L18 ). We may still want to consider using a split package to build `libcudf` & `cudf` and split the pieces out.

Investigating the usage of variants in a build matrix is still an interesting piece of work, but may involve other changes around handling global pinnings. This may require scoping.

So things have definitely improved (particularly on the compiler front), but there is still some room for improvement. Much of this is lower hanging fruit (especially given other changes that have occurred).

**Comment by vyasr** [comment]
Is the split not what was done in https://github.com/rapidsai/cudf/pull/10326?

I'm happy to help work through some of these, given all the ongoing build system work I think we'd benefit a lot from cleaning up some of these issues as we go.

**Comment by kkraus14** [comment]
FWIW, I raised an issue (https://github.com/rapidsai/cudf/issues/11119) about my struggles with using multi output recipes and folding cudf and libcudf into the same recipe will just further exacerbate that.

If the conda recipes are treated purely as an implementation detail and user consumption of them is explicitly out of scope, folding them all into a single recipe is somewhat reasonable, though it does limit the ability to parallelize the build process in building conda packages.

**Comment by jakirkham** [comment]
Thanks for surfacing that. Hadn't seen that issue. Agree that is something we want to take into account. Preferably before doing more splitting (since we will want to extend that to any added outputs)

**Comment by vyasr** [comment]
I just went through the above checklist and the bulk of the items that were previously unchecked were either completed or obsoleted by more recent changes (including the broad shift towards scikit-build/scikit-build-core, the requirement to invoke pip rather than setup.py, the various conda recipe improvements during the CUDA 12 work, etc). The remaining unchecked items are no longer clearly improvements for a variety of reasons. I think we can safely close this issue for now and consider any future improvements in light of the current state of the recipes. Also, we will want to coordinate such work across RAPIDS so that it's not specific to just cudf.
