### ISSUE TITLE
Complex number support[FEA]

### ISSUE THREAD

**Issue by arpan-das-astrophysics** [rapidsai/cudf#12104]
Hello, I am using cudf to reduce huge astronomical datasets. However one of the big drawback (compared to pandas) is not having the complex number support. For now, I am storing the real part and imaginary part separately, however it is not really feasible as we are reading that multiple times and every time we have to reconstruct the array of complex number from real and imag parts and it is very time consuming. Many of the radioastronomical datas are complex number and hence it will be amazing to have the ability to store the complex numbers directly.

**Comment by arpan-das-astrophysics** [comment]
> Same as #11983 ?

Yes same as the other issue. Currently we are doing lot of operations with complex numbers and it will be amazing to have that support otherwise it is a bit overwhelming to cast it to float all the time to store into the dataframe

**Comment by GregoryKimball** [comment]
Thank you @arpan-das-astrophysics for raising this topic. For now I'll close this in favor of #11983 and I would like to continue the discussion there.
