### ISSUE TITLE
[BUG] incorrect floor division in libcudf binarop (coming from CUDF cython)

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#12120]
**Describe the bug**

Floor division of large integers loses precision because it looks like it goes through floating point division somewhere.

**Steps/Code to reproduce bug**

```python
import cudf
import cupy
from cudf._lib.binaryop import binaryop
import numpy as np
s = cudf.Series([12], dtype="int64")
v = np.int64(1513393355500000000)
divided = cupy.asarray(binaryop(v, s._column, "__floordiv__", np.int64))
assert divided[0] == (v // 12) # => false
assert divided[0] == (v / 12).astype(np.int64) # => true, hmm suspicious
```

**Expected behavior**

Floor division should work with integers and not pass through a floating point representation.

**Comment by wence-** [comment]
`FLOOR_DIV` is noted as being implemented by conversion to float and truncation:

https://github.com/rapidsai/cudf/blob/b3429fb2322debf6306acbbbf3bf14b0692e932a/cpp/include/cudf/binaryop.hpp#L44-L45

This appeared in c8b897ccd1, do we recall why @devavret?

Plausible patch:

```patch
diff --git a/cpp/src/binaryop/compiled/operation.cuh b/cpp/src/binaryop/compiled/operation.cuh
index 68b750ca01..fd427d9b65 100644
--- a/cpp/src/binaryop/compiled/operation.cuh
+++ b/cpp/src/binaryop/compiled/operation.cuh
@@ -93,9 +93,9 @@ struct TrueDiv {
 struct FloorDiv {
   template <typename T1, typename T2>
   __device__ inline auto operator()(T1 const& lhs, T2 const& rhs)
-    -> decltype(floor(static_cast<double>(lhs) / static_cast<double>(rhs)))
+    -> decltype(lhs / rhs)
   {
-    return floor(static_cast<double>(lhs) / static_cast<double>(rhs));
+    return lhs / rhs;
   }
 };
 
```

**Comment by wence-** [comment]
This is insufficient because it doesn't give floored division of floating types, so we need SFINAE overloads for:

1. std::is_integral_v T0 and T1 (numpy promotion rules match C++ rules here: TODO CHECK!)
2. float, float (`floorf(lhs / rhs)`)
3. double, double (`floor(lhs / rhs)`)

And then it is cuDF's responsibility to do appropriate type promotion on the outside before calling into libcudf.

**Comment by bdice** [comment]
I did some research with @wence- and it seems that the conventions for floor division in libcudf can be improved.

The current implementation casts both inputs to `double` before flooring. https://github.com/rapidsai/cudf/blob/b3429fb2322debf6306acbbbf3bf14b0692e932a/cpp/include/cudf/binaryop.hpp#L44-L45

However, none of C++, Python, Java match this behavior of casting to `double` first. All of them do integral floor division for integral inputs.
Java: https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#floorDiv-long-long-

I think this is what we want:

```c++
struct FloorDiv {
  template <typename TypeLhs,
            typename TypeRhs,
            std::enable_if_t<(std::is_integral_v<std::common_type_t<TypeLhs, TypeRhs>> or
                              (cudf::is_fixed_point<TypeLhs>() and
                               std::is_same_v<TypeLhs, TypeRhs>) or
                              is_duration<TypeLhs>())>* = nullptr>
  __device__ inline auto operator()(TypeLhs x, TypeRhs y) -> decltype(x / y)
  {
    return x / y;
  }

  template <
    typename TypeLhs,
    typename TypeRhs,
    std::enable_if_t<(std::is_same_v<std::common_type_t<TypeLhs, TypeRhs>, float>)>* = nullptr>
  __device__ inline auto operator()(TypeLhs x, TypeRhs y) -> float
  {
    return floorf(x, y);
  }

  template <
    typename TypeLhs,
    typename TypeRhs,
    std::enable_if_t<(std::is_same_v<std::common_type_t<TypeLhs, TypeRhs>, double>)>* = nullptr>
  __device__ inline auto operator()(TypeLhs x, TypeRhs y) -> double
  {
    return floor(x, y);
  }
};
```
