### ISSUE TITLE
Loading bigger than memory dataframe using dask_cudf [QST]

### ISSUE THREAD

**Issue by arpan-das-astrophysics** [rapidsai/cudf#12134]
[](url)Hello, I am trying to load a file which is bigger than the available GPU memory using `daks_cudf(filename, chunksize = '100 MiB')` (just to test). 

The main dataframe is 780 Mib and I have defined chunksize to be 100 MiB. However, reading the chunk data is giving the full dataframe whereas I would expect a list of smaller chunk dataframes? 

[
![Screen Shot 2022-11-14 at 11 56 37 AM](https://user-images.githubusercontent.com/23120837/201643229-e0092cc0-df15-4c14-a357-d7b4d76a2a88.png)
](url) 

My main goal is to read the main dataframe into smaller chunks, do some operation on them and in the end concat all the chunks to get the bigger dataframe. The main reason is this filesize will likely to go bigger than 1 TB + and I am trying to find the most efficient way to do it. Also when I am trying to print the chunks all I am getting is the name of the columns of the main dataframe

![Screen Shot 2022-11-14 at 12 01 03 PM](https://user-images.githubusercontent.com/23120837/201644065-6a6eb4ff-c188-46a7-8814-c8b22a4bd9a8.png)

**Comment by beckernick** [comment]
Dask DataFrames organize the smaller partitions into a distributed dataframe for you. You can manipulate it like a single dataframe, but under the hood it's composed of multiple smaller dataframes. `for x in dataframe: ...` will loop over the column names like in pandas. When you read the file and call `len`, you're processing the distributed dataframe in chunks as you'd expect. You can access the partitions with `ddf.partitions`, but this would generally not be recommended outside of specific circumstances.

The [Dask DataFrame documentation](https://docs.dask.org/en/stable/dataframe.html) may be a good resource to learn more.

I'm going to close this issue, but please feel free to reopen it if things aren't working as expected.
