### ISSUE TITLE
[FEA] Add support for equivalent of Pandas `pivot_table`

### ISSUE THREAD

**Issue by niviksha** [rapidsai/cudf#1214]
**Is your feature request related to a problem? Please describe.**
I wish cudf would support the pandas pivot_table. A typical workflow i have is where i have a time series by entity (e.g. counts of connections by cell tower binned by a time interval) like so

```
	tower_id                   ct	dt_col
0	e8:1d:a8:33:cc:b0	50	2019_02_08
1	e8:1d:a8:30:81:c0	44	2019_02_28
2	38:ff:36:06:b9:d0	149	2019_03_07
3	e0:10:7f:15:9d:30	4	2019_03_07
4	e0:10:7f:12:3a:a0	74	2019_02_20

```
 I wish to turn this time series into a single row per cell_tower

```
    tower_id| 2019_02_01 | 2019_02_02 | 2019_02_03 | 2019_02_04 ...
0 | 0c:f4:d5:0c:83:40 | 9.0 | 20.0 | 4.0 | 6.0...
1| 0c:f4:d5:0c:85:b0 | 15.0 | 27.0 | 25.0 | 10.0

```
..etc

**Describe the solution you'd like**
support a pivot_table operation identical to pandas

**Describe alternatives you've considered**
Doing the pivot in pandas. This is suboptimal, since in omnisci, it's possible to create the cudf from a query directly - so doing this in pandas means leaving the gpu

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html

**Comment by bbooze1** [comment]
Has there been any progress made on this?

**Comment by shwina** [comment]
We're working on adding support for [`pivot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.pivot.html) which also does the reshaping operation described in the above example, but differs from `pivot_table` in that it doesn't support aggregations.

@bbooze1 would be curious to know if your use case requires aggregations, or if there are other features of `pivot_table` you need. Thanks!
