### ISSUE TITLE
[BUG] CUDF crashes when trying to read a valid ORC file with 100 null entries in it.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#12156]
**Describe the bug**
This is related to https://github.com/rapidsai/cudf/issues/12155.  I was trying to produce a synthetic file with the same error just so I could share it without getting permission.  Well I was able to make a crash happen, but it was not the same crash. I am not sure if this is a bug that will show up as a part of #12155 or not, but I wanted to document it.  Just so you know I wrote this file using CUDF.

**Steps/Code to reproduce bug**
Read the orc file inside of [other_error.zip](https://github.com/rapidsai/cudf/files/10016760/other_error.zip) using CUDF it will fail with an error something like 

```
cuDF failure at: cudf/cpp/src/io/orc/reader_impl.cu:333: No decompressible data found
```
Please ignore the line number I added in some debug print statements and so the lines are off a bit.

**Expected behavior**
It is read correctly like with Spark.
```
scala> spark.read.orc("part-00000-f7e595c6-ab11-46d0-9619-1f71cc41deac-c000.snappy.orc").show()
+----+
|   m|
+----+
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
|null|
+----+
only showing top 20 rows

```

or pandas

```
>>> pd.read_orc("part-00000-f7e595c6-ab11-46d0-9619-1f71cc41deac-c000.snappy.orc")
       m
0   None
1   None
2   None
3   None
4   None
..   ...
95  None
96  None
97  None
98  None
99  None

[100 rows x 1 columns]
```

**Comment by vuule** [comment]
Closed via #12160
