### ISSUE TITLE
GDFError: CUDA ERROR. cudaSuccess: no error 

### ISSUE THREAD

**Issue by VickiFu** [rapidsai/cudf#1221]
When I run the demo from the official site with NVIDIA GPU Cloud Image for Deep Learning and HPC@Azure with Feb 2019 update. https://rapidsai.github.io/demos/ 

On the code notebooks/cuml/dbscan_demo.ipynb
X = cudf.DataFrame.from_pandas(X)

---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<timed exec> in <module>

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/dataframe.py in from_pandas(cls, dataframe, nan_as_null)
   1654         # Set columns
   1655         for colk in dataframe.columns:
-> 1656             df[colk] = Series(dataframe[colk].values, nan_as_null=nan_as_null)
   1657         # Set index
   1658         return df.set_index(dataframe.index)

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/series.py in __init__(self, data, index, name, nan_as_null)
     75 
     76         if not isinstance(data, columnops.TypedColumnBase):
---> 77             data = columnops.as_column(data, nan_as_null=nan_as_null)
     78 
     79         if index is not None and not isinstance(index, Index):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null)
    208             raise NotImplementedError("Strings are not yet supported")
    209         else:
--> 210             data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
    211 
    212     elif isinstance(arbitrary, pa.Array):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null)
    200             if nan_as_null:
    201                 mask = cudautils.mask_from_devary(arbitrary)
--> 202                 data = data.set_mask(mask)
    203 
    204     elif isinstance(arbitrary, np.ndarray):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/column.py in set_mask(self, mask, null_count)
    212             msg = 'mask must be of byte; but got {}'.format(mask.dtype)
    213             raise ValueError(msg)
--> 214         return self.replace(mask=mask, null_count=null_count)
    215 
    216     def allocate_mask(self, all_valid=True):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/numerical.py in replace(self, **kwargs)
     72         if 'data' in kwargs and 'dtype' not in kwargs:
     73             kwargs['dtype'] = kwargs['data'].dtype
---> 74         return super(NumericalColumn, self).replace(**kwargs)
     75 
     76     def serialize(self, serialize):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/column.py in replace(self, **kwargs)
    328         if 'mask' in kwargs and 'null_count' not in kwargs:
    329             del params['null_count']
--> 330         return type(self)(**params)
    331 
    332     def view(self, newcls, **kwargs):

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/numerical.py in __init__(self, **kwargs)
     66             Data type
     67         """
---> 68         super(NumericalColumn, self).__init__(**kwargs)
     69         assert self._dtype == self._data.dtype
     70 

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/columnops.py in __init__(self, **kwargs)
     33     def __init__(self, **kwargs):
     34         dtype = kwargs.pop('dtype')
---> 35         super(TypedColumnBase, self).__init__(**kwargs)
     36         # Logical dtype
     37         self._dtype = pd.api.types.pandas_dtype(dtype)

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/column.py in __init__(self, data, mask, null_count)
    106             if self._mask is not None:
    107                 nnz = _gdf.count_nonzero_mask(self._mask.mem,
--> 108                                               size=len(self))
    109                 null_count = len(self) - nnz
    110                 if null_count == 0:

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/_gdf.py in count_nonzero_mask(mask, size)
    493 
    494     if addr != ffi.NULL:
--> 495         libgdf.gdf_count_nonzero_mask(mask_ptr, size, nnz)
    496 
    497     return nnz[0]

/conda/envs/rapids/lib/python3.6/site-packages/libgdf_cffi/wrapper.py in wrap(*args)
     25                     if errcode != self._api.GDF_SUCCESS:
     26                         errname, msg = self._get_error_msg(errcode)
---> 27                         raise GDFError(errname, msg)
     28 
     29                 wrap.__name__ = fn.__name__

GDFError: CUDA ERROR. cudaSuccess: no error

**Comment by kkraus14** [comment]
@VickiFu What CUDA version and GPU did you try this on?

**Comment by harrism** [comment]
@VickiFu Could you answer @kkraus14 's question?

**Comment by harrism** [comment]
No response, closing.
