### ISSUE TITLE
[BUG] Calling sum on a boolean column returns a boolean

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1224]
```python
import cudf
import numpy as np
s = cudf.Series(np.arange(100000))
(s > 1).sum()
```

```
True
```

I believe that this should return something lik 999999, and that we should have a method `all` and `any` which is closer to the current behavior.

**Comment by harrism** [comment]
@kkraus14 Please don't add the libcudf label without more information on triage. Seems this still needs the "needs triage" label, at least on the libcudf side...

**Comment by kkraus14** [comment]
@harrism The way we've been using the "? - Needs Triage" label is more of a "Needs Classification" to indicate that the team hasn't looked at and classified the issue yet.

**Comment by harrism** [comment]
That's fine, but if you have done enough to know that it's a bug in libcudf, please explain how you know that, so I know where to look. :)

**Comment by kkraus14** [comment]
> That's fine, but if you have done enough to know that it's a bug in libcudf, please explain how you know that, so I know where to look. :)

Fair point, we set the output dtype in Cython here and we incorrectly set it to the dtype of the input column 😅

**Comment by AK-ayush** [comment]
Even if we set the output dtype to any integer type(np.int8, np.int16, np.int32, np.int64) in Cython, maximum series size, is handled correctly in 127(range of int8). This is because of `type_dispachter.hpp`, this is returning the dtype is int8_t. 

One solution to this is, to change the dtype of intput col in cython to int64 before calling `sum` and `sum_of_squares` reductions. Not sure this is optimal.

**Comment by harrism** [comment]
@devavret is in the process of revamping how reductions work in #1005... @devavret can you look at this issue and see if it can be easily fixed as part of that PR?

**Comment by harrism** [comment]
@AK-ayush you certainly DO want to change the output column type if you want to sum a column of more than 128 True boolean values, otherwise you will just get overflow...  What does Pandas do? Unclear from docs. Numpy `sum` says: 

```
The type of the returned array and of the accumulator in which the elements are summed. The dtype of a is used by default unless a has an integer dtype of less precision than the default platform integer. In that case, if a is signed then the platform integer is used while if a is unsigned then an unsigned integer of the same precision as the platform integer is used.
```

Seems like sum reduction on a gdf_column of Booleans should choose a 32-bit integer output type by default (since the maximum column size is 32-bit and we are only adding 1s and zeros).

**Comment by kovaltan** [comment]
#1005 has output_dtype, it is possible for int8 to compute and calculate higher precision like int32 or int64 at C++ level.
Btw, I wonder what is the internal `gdf_dtype` for `(s > 1).sum()`?
`Boolean` is not defined in  `gdf_dtype`  yet.
Is it int8 internally?

**Comment by AK-ayush** [comment]
Yes @kovaltan `np.bool_` is being mapped to `GDF_INT8` in cudf_cpp.pyx . And then at C++ level it is handled as `int_8t`. 

@harrism  I am wondering why  this [test_sum(dtype, nelem) ](https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/python/libgdf_cffi/tests/test_reductions.py#L29) from `cpp/python/libgdf_cffi/tests/test_reductions.py` is not failing with `dtype=np.int8` and `nelem>=129`.

**Comment by harrism** [comment]
@AK-ayush not sure!

**Comment by kovaltan** [comment]
> @harrism I am wondering why this [test_sum(dtype, nelem) ](https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/python/libgdf_cffi/tests/test_reductions.py#L29) from `cpp/python/libgdf_cffi/tests/test_reductions.py` is not failing with `dtype=np.int8` and `nelem>=129`.

I think the implementation of `gen_rand` is limits the range in [-32, 32] for int8.
https://github.com/rapidsai/cudf/blob/c654c41e0d63e96c249a20c31ca32ef98a2ba93f/cpp/python/libgdf_cffi/tests/utils.py#L44-L47

**Comment by kovaltan** [comment]
@AK-ayush
PL #1005 (reduction, scan) is ready for review.
In the PL, I've add `test_sum_boolean` test case and verified it worked.
Is this enough for this issue?

def test_sum_boolean():
    s = Series(np.arange(100000))
    got = (s > 1).sum(dtype=np.int32)
    expect = 99998
    print('expect:', expect)
    print('got:', got)
    assert expect == got

https://github.com/rapidsai/cudf/blob/568cb94a299d39b60c3706e5e9316d9e625fa0c2/python/cudf/tests/test_reductions.py#L141-L149

**Comment by AK-ayush** [comment]
@kovaltan Yes, this will definitely fix this issue. I just want to add one thing, isn't it good if we fix the return type to `int32` when calling the `sum` and `sum_of_squares()` on `boolean series`? and similarly `float32` when calling the `mean()` on `boolean series`? It will be similar to pandas behaviour.

**Comment by kovaltan** [comment]
@AK-ayush

> I just want to add one thing, isn't it good if we fix the return type to int32 when calling the sum and sum_of_squares() on boolean series

It is feasible, but it seems that the behaviors of `sum` are different at pandas and numpy.
pandas does not mention the precision. I assume that int64_t is used for integers, and float664 is used for floats.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html

numpy mentions in the doc that same presicion is used for output and option dtype can change it.

"The type of the returned array and of the accumulator in which the elements are summed. The dtype of a is used by default unless a has an integer dtype of less precision than the default platform integer. In that case, if a is signed then the platform integer is used while if a is unsigned then an unsigned integer of the same precision as the platform integer is used."

https://docs.scipy.org/doc/numpy/reference/generated/numpy.sum.html

@kkraus14 @harrism , which is better for us?
For now, numpy models is applied to cudf::Series and NumericColumn.

**Comment by harrism** [comment]
I think that the numpy approach of scaling up to platform integer size will lead to the least amount of surprise (and overflow) among users. Do you agree @kkraus14 ?

**Comment by kovaltan** [comment]
PL #1005 (reduction, scan) is merged.
Can I close this bug?
It also has `test_sum_boolean` test case and verified it worked.
https://github.com/rapidsai/cudf/blob/568cb94a299d39b60c3706e5e9316d9e625fa0c2/python/cudf/tests/test_reductions.py#L141-L149
