### ISSUE TITLE
[FEA] Add `null_count_if_available` or `lazy_null_count` to `column` and `column_view`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12256]
The classes `column` and `column_view` have `null_count` functions that return the number of nulls in the given column. The column holds an internal null count value which is defaulted to `UNKNOW_NULL_COUNT`.

During various transformations, we need to copy that null count value around but may not really care about what that value is. However, if the function `null_count()` is called but the column's internal number of nulls has not been computed, a kernel will always be launched to compute the actual null count. That is a waste of time because we can just return `UNKNOW_NULL_COUNT` without compute anything.

I suggest adding a new function that allows returning the column's internal null count directly without computation. That function can be named `null_count_if_availabe` or `lazy_null_count` or anything else that is relevant.

**Comment by davidwendt** [comment]
The `UNKNOWN_NULL_COUNT` feature will be removed with https://github.com/rapidsai/cudf/issues/11968
So we will not be needing these extra functions.

**Comment by GregoryKimball** [comment]
I'll close this in favor of #11968 for now
