### ISSUE TITLE
Update PyTorch pinning

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#12273]
**Describe the bug**
Currently our CI tests are pinned to PyTorch <1.12.0.

https://github.com/rapidsai/cudf/blob/5f83a8491603eadc1de5cb174016801c1cca5824/conda/environments/all_cuda-115_arch-x86_64.yaml#L61

https://github.com/rapidsai/cudf/blob/5f83a8491603eadc1de5cb174016801c1cca5824/dependencies.yaml#L204

Two possible solutions to remove the pinning (maybe more?):
- Add ARM+CUDA to conda-forge, use conda-forge packages instead of pytorch packages: https://github.com/conda-forge/pytorch-cpu-feedstock/issues/149
- Wait until `cuda-toolkit` is used by both `pytorch/pytorch` and `conda-forge/pytorch` and RAPIDS packages (probably around CUDA 12, to be determined)

On the PyTorch channel, 1.11.0 builds against `cudatoolkit` and 1.12.0+ builds against `cuda-toolkit`. We can't use the builds that used `cuda-toolkit` because of issues with libcupti linkage and whether it's available in the relevant CTK package or not.

cc: @jakirkham @quasiben

**Comment by jakirkham** [comment]
As noted offline, we may want to add a comment next to those respective pins with a link to this issue. That would hopefully help anyone who wonders about them discover the additional context

**Comment by vyasr** [comment]
This particular issue has been resolved as we now use a much newer version of PyTorch. Further improvements will come as we improve alignment between the CUDA packages on different channels.
