### ISSUE TITLE
[BUG] Regression in regexp matching end-of-line

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#12278]
**Describe the bug**
PR https://github.com/rapidsai/cudf/pull/12181 changed the behavior of both `$` and `\Z` to the following:

```
Matches before the final line break in the string (if any) in addition to matching at the very end of the string.
```

This means we can no longer match the very end of the string. For example, `\A\d{4}-\d{2}-\d{2}\Z` will now match `1999-12-29\n`, where it previously did not. There seems to be no way in cuDF to match the end of the string now.

Python has different behavior between `$` and `\Z`, giving the user a choice about how to handle strings ending in newlines. Could we do the same in cuDF?

| Pattern | Meaning |
|--|--|
| `$` | Matches before the final line break in the string (if any) in addition to matching at the very end of the string.
| `\Z` | Matches at the end of the string the regex pattern is applied to.

**Steps/Code to reproduce bug**
See example above.

**Expected behavior**

**Environment overview (please complete the following information)**
N/A

**Environment details**
N/A

**Additional context**
None

**Comment by davidwendt** [comment]
@andygrove Could you test out the fix in https://github.com/rapidsai/cudf/pull/12282 ?

**Comment by andygrove** [comment]
Thanks @davidwendt. I tested the patch locally and confirmed that it fixes the regression.
