### ISSUE TITLE
[FEA] Improve CSV reader to reduce overhead of many small HtoD copies

### ISSUE THREAD

**Issue by j-ieong** [rapidsai/cudf#1227]
**Is your feature request related to a problem? Please describe.**
Compared to previous versions, the CSV reader splits the input into smaller chunks to better handle very large data files. Unfortunately, the chunks are a fixed size of 64MB and the copies may not be pipelined well, introducing some overhead compared to a single large copy + large kernel.

**Describe the solution you'd like**
- Use a larger chunk size or a dynamic chunk size, depending on data size, GPU, and features enabled (i.e. if data split/offsets are used)
- Use streams if possible to have concurrent kernels working on each chunk

**Comment by OlivierNV** [comment]
This is mostly resolved by #5024 (which eliminates most of the existing HtoD/DtoH transfers), though there should be some room for improvement, pipelining HtoD with kernel execution (not clear if the 64MB transfers of character data were a big problem).

**Comment by kkraus14** [comment]
Fixed by #5024
