### ISSUE TITLE
[FEA] Support multiple compressed inputs in `read_json`

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#12299]
JSON reader currently concatenates data from all input sources before (optional) decompression and parsing.
This is not correct for compressed input files, as each file is compressed separately.
https://github.com/rapidsai/cudf/pull/12285 disables multiple inputs for compressed data.
`read_json` should decompress each input file before concatenating the decompressed data.

**Comment by karthikeyann** [comment]
Note that Only a single source is currently supported in `read_csv`.
This work could help expand the same feature to csv reader.
