### ISSUE TITLE
[FEA] Improve CSV reader to speed-up ignoring line terminations within quotes

### ISSUE THREAD

**Issue by j-ieong** [rapidsai/cudf#1229]
**Is your feature request related to a problem? Please describe.**
Currently, the algorithm to exclude line terminations within quotes during row/record count is done on the CPU and serialized. For a large number of rows, it is a massive bottleneck.

**Describe the solution you'd like**
Use the GPU to implement the feature:
1. During the row count phase, store the row start character alongside the offset
2. Use a scan+reduction kernel to eliminate row entries that occur within unbalanced start/end quotes (i.e. row B starts with quotechar, skip skip skip, row X starts with quotechar)

**Describe alternatives you've considered**
A custom kernel or a thrust algo implementation. Trying to parallelize the current host code is also possible.

**Additional context**
N/A

**Comment by OlivierNV** [comment]
So, I've had time to think about this for a while now, and I think there are 3 things needed, all in the input stage of the CSV reader:
1. Move the header parsing out of the row counting stage: afaict, including the header as part of normal rows offset gathering stage only adds unnecessary complexity: the header rows should be immediately parsed by CPU (always starting from offset 0), and can be trimmed without ever needing to reach the GPU.
2. Row offset gathering should be implemented with a single custom kernel (2 launches for count and gather phases), matching pandas parsing rules (essentially moving the entire gather_row_offsets and select_rows functionality to GPU). This would eliminates the huge `select_rows` CPU bottleneck.
3. From what I can tell, byte_range functionality currently makes the assumption that the start of the byte range is not within a quote that would include the `\n` character. This should be improved by a backward scan to determine if the start of the byte range is within a special context like quote or comment (may need to rely on some heuristics for corner cases), this is also tied to the parallel-parsing in step 2.

**Comment by OlivierNV** [comment]
Estimated rough perf improvements for csv input stage (380MB csv, 256MB chunk size, TU102):
Old (~400ms total time):
```
56ms: HtoD (transfer character data)
14ms: Count newlines and quotes
18ms: Store newlines and quotes positions in non-deterministic random order
22ms: Sort positions (thrust::RadixSortXXX)
146ms: DtoH transfer positions
~120ms: select_row (parsing, filter positions on CPU, content-dependent)
32ms: HtoD transfer filtered row offsets
```

New (~70ms total time):
```
56ms: HtoD (transfer character data)
~4ms: parse, filter and count rows
~4ms: parse, filter and output row offsets in order
<1ms: Misc DtoH, HtoD
```
Not sure what the overall speedup would look like (depends on relative perf of input stage vs the subsequent conversion stage)

**Comment by OlivierNV** [comment]
Benchmarked the same file within cudf (2.3M rows) to get an idea of csv reader perf breakdown:
```
27% 52ms cudaMemcpyHtoD (copying input csv data, no surprises there)
24% 45.7ms csv::gpu::dataTypeDetection -> surprisingly slower than actual decoding, wtf (I guess it's important that caller specifies dtypes)
18% 34.5ms convertCsvToGdf -> actual conversion from csv to cudf data
13% 25.5ms thrust::counting_iterator(make_string_column) -> looks slow
 5% 9ms thrust::unary_transform<thrust::pair<char*,int>> (make_string_column)
 4% 7ms gather_row_offsets_gpu
 3% 6ms thrust::transform_iterator(strings::replace)
 3% 6ms thrust::for_each (strings::replace)
 1% 2ms thrust::for_each(make_string_column)
```
From the above, it looks like a 2x speedup would still be doable (beyond that is limited by disk/PCIE)
