### ISSUE TITLE
[FEA] Throw more descriptive error when file is not found in CUIO.

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#12311]
**Is your feature request related to a problem? Please describe.**
CUIO file utilities throw an unhelpful error when file is not found.
`Cannot query file size`
```
./build/morpheus/_lib/tests/test_libmorpheus.x --gtest_filter=TestMatxUtil.ReduceMax2dColMajor
Note: Google Test filter = TestMatxUtil.ReduceMax2dColMajor
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from TestMatxUtil
[ RUN      ] TestMatxUtil.ReduceMax2dColMajor
unknown file: Failure
C++ exception with description "cuDF failure at: /workspace/.conda-bld/work/cpp/src/io/utilities/file_io_utilities.cpp:34: Cannot query file size" thrown in the test body.
[  FAILED  ] TestMatxUtil.ReduceMax2dColMajor (13 ms)
[----------] 1 test from TestMatxUtil (13 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (13 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] TestMatxUtil.ReduceMax2dColMajor

 1 FAILED TEST
```

**Describe the solution you'd like**
Throw a more descriptive error when file is not found.

**Context**
This error was throw when attempting to open a csv file which did not exist.

**Comment by GregoryKimball** [comment]
What file format were you trying to read? For text files the errors can be a bit weird because they accept string data as well as string filenames.

**Comment by vuule** [comment]
This should happen with any reader, as long as they read from a file. The error is thrown from a utility class used in the file datasource.
I looked into this a bit, and it seems like we cannot be certain about the cause of the error, even with errno. If it helps, we can expand the error message to include something like "(possibly incorrect file name)".
