### ISSUE TITLE
[BUG] `cudf::strings::detail::stod` doesn't properly process some strings

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#12333]
**Describe the bug**
Due to the nature of how `cudf::stod` creates value, it is unable to produce certain values like `1.9002704020673403e214` when std::stod has no problem with it. The implementation in cudf first stores the digits as a integer and then converts them to a double, which produces `19002704020673404`. Then it is multiplied by `expten(exponent)`, which compounds the error and produces `1.9002704020673406e214`. Some initial investigation by Jake revealed that std::stod is building the float value with bit operations and not mathematically, probably to avoid this issue.

**Steps/Code to reproduce bug**
`cudf::strings::detail::stod("1.9002704020673403e214");`

**Expected behavior**
This value should be represented as 1.9002704020673403e214.

**Comment by davidwendt** [comment]
I would not consider accuracy to 15 decimal places a bug.

**Comment by hyperbolic2346** [comment]
> I would not consider accuracy to 15 decimal places a bug.

We don't match the output of `std::stod` and produce different results if run on CPU vs GPU. Would you consider this more of a feature request?

In my searching, it seems that the approach is to use a few fast and fine for most numbers algorithms that can return if they are unable to produce a valid value and then a [slower algorithm](https://nigeltao.github.io/blog/2020/parse-number-f64-simple.html) that can always produce the best value as a fallback. I'm not saying this is the best path for us, instead I am presenting my research into the issue.

**Comment by davidwendt** [comment]
Generally two floating points are equivalent (not equal to) if they differ within an [epsilon](https://en.cppreference.com/w/cpp/types/numeric_limits/epsilon) value. For `double` this is about 10 digits.
There was no attempt to match `std::stod()` bit for bit. 
It is certainly reasonable to request for more accuracy but generally floating point comparison is always expected to be within an error.

**Comment by revans2** [comment]
To be clear about the source of this.  Spark uses java to parse floating point values.  But Java in their infinite wisdom has defined their own standard on doing this.

https://docs.oracle.com/javase/8/docs/api/java/lang/Float.html#valueOf-java.lang.String-

https://docs.oracle.com/javase/8/docs/api/java/lang/Double.html#valueOf-java.lang.String-

When we do comparisons we verify that the value is within an epsilon with the value returned by Spark.

https://github.com/NVIDIA/spark-rapids/blob/6bc1c052d7b496d71c87f9273d71e79b97ff00bb/integration_tests/src/main/python/conftest.py#L32

This can be configured per test, but generally we go with the default values for pytest.approx when doing the comparisons.

https://docs.pytest.org/en/4.6.x/reference.html#pytest-approx

The issue that we run into is that when we use one API that uses `std::stod` on the GPU the test passes and when we use another API that uses `cudf::strings::detail::stod` it fails.

**Comment by davidwendt** [comment]
> The issue that we run into is that when we use one API that uses `std::stod` on the GPU the test passes and when we use another API that uses `cudf::strings::detail::stod` it fails.

I assume you meant CPU here since `std::stod` does not exist in device code.
Is there some reason you are not using the epsilon for verifying the `cudf::strings::detail::stod` result?
libcudf matches `cudf::strings::to_floats` results against `std::stod` in our gtests (with the appropriate epsilon).

**Comment by davidwendt** [comment]
Adding `"1.9002704020673403e214"` to the list of strings in https://github.com/rapidsai/cudf/blob/0c8eeb5a3caacf5881621f84da891a5d804d43d7/cpp/tests/strings/floats_tests.cpp#L125 passes this test.

**Comment by revans2** [comment]
@hyperbolic2346  I this we have something odd happening with the kernel, because my small scale tests show that things are working as expected and the tests should pass.

```
JAVA:
java.lang.Double.doubleToRawLongBits(java.lang.Double.valueOf("1.9002704020673403e214"))
7812682319334874594

C++
auto result = std::stod("1.9002704020673403e214");
uint64_t uint_result = *((uint64_t *)&result);
7812682319334874594

Spark:
val df = Seq("1.9002704020673403e214").toDF
java.lang.Double.doubleToRawLongBits(df.selectExpr("CAST(value as DOUBLE)").collect.head.getDouble(0))
CPU: 7812682319334874594
GPU: 7812682319334874595

CUDF:
val scv = ColumnVector.fromStrings("1.9002704020673403e214")
val dcv = scv.castTo(DType.FLOAT64)
val dhcv = dcv.copyToHost
java.lang.Double.doubleToRawLongBits(dhcv.getDouble(0))
7812682319334874595

New Kernel:
val scv = ColumnVector.fromStrings("1.9002704020673403e214")
val tmp = com.nvidia.spark.rapids.jni.CastStrings.toFloat(scv, false, DType.FLOAT64)
val hcv = tmp.copyToHost
java.lang.Double.doubleToRawLongBits(hcv.getDouble(0))
7812682319334874595

scala> java.lang.Double.longBitsToDouble(7812682319334874595L)
res0: Double = 1.9002704020673406E214

scala> java.lang.Double.longBitsToDouble(7812682319334874594L)
res1: Double = 1.9002704020673403E214
```

If I use pytest.approx on these different values it shows up as them being equal.

```
def test_odd_parse():
    first = struct.unpack('d', struct.pack('L', 7812682319334874595))[0]
    second = struct.unpack('d', struct.pack('L', 7812682319334874594))[0]
    pytest.approx(first, second)
```

So the only thing I can think of is that something else is off somewhere, possibly in the test itself.

**Comment by hyperbolic2346** [comment]
Correct, the tests will pass with this due to being within epsilon. This isn't causing any failed tests, it is just not matching `std::stod`. This may not be an issue or this may be considered a bug. This discussion is for that. We could match the `std::stod` bit for bit or we can leave it as is if the current implementation is faster on GPU or in some other way better.

**Comment by vyasr** [comment]
Unless we have a use case that demands bit for bit compatibility I'm inclined to leave this as is. I don't even think that the current implementation has to be faster or better in some way; it's advantage is simply that it already exists. Without a particular need for bitwise compatibility I just don't see the value in pursuing changes to floating point values that are smaller than machine epsilon.
