### ISSUE TITLE
[FEA] groupby(key)[col].apply(list)

### ISSUE THREAD

**Issue by KazukiOnodera** [rapidsai/cudf#12337]
I wish I could use cuDF to do groupby.apply(list)
I'm expecting this behavior like pandas

```
In [2]: 
   ...: df = pd.DataFrame(
   ...:     [
   ...:         ["A", 1],
   ...:         ["A", 2],
   ...:         ["A", 3],
   ...:         ["B", 4],
   ...:         ["B", 5],
   ...:         ["B", 6],
   ...:         ["B", 7],
   ...:         ["C", 8],
   ...: 
   ...:     ], columns=["x", "y"],)

In [3]: df.groupby("x")['y'].apply(list)
Out[3]: 
x
A       [1, 2, 3]
B    [4, 5, 6, 7]
C             [8]
```

In version 22.10.00, it causes
> TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values

**Comment by KazukiOnodera** [comment]
Yes. It's same as `df.groupby("x")['y'].collect()` and `df.groupby("x")['y'].agg(list)` in cudf.

**Comment by ttnghia** [comment]
So why do still need `groupby.apply(list)`? Why don't just use `groupby.agg(list)`?

**Comment by KazukiOnodera** [comment]
Because one of kaggler was trying to do that in cudf [here](https://twitter.com/colum2131/status/1600046674009001984?s=46&t=w6bgyaMsMjREVzQP7mCPWg).
I was also tried to do before, because I usually use that way in pandas. IMHO it would be preferable to be able to achieve this in more than one way.

**Comment by shwina** [comment]
For now, I'd say this is a `wontfix`.

In general, we don't support list types in groupby. Collecting group values into lists is one specific operation we _do_ support, and we recommend using `groupby().collect()` or equivalently `groupby().agg(list)`.

I'd prefer not to expose this functionality via `apply()`, as it gives the (false) impression that we can support an arbitrary operation like `.groupby().apply(lambda group: list(group) + [1, 2])`.
