### ISSUE TITLE
[FEA] Support `stream` and `mr` parameters for `structs::detail::flatten_nested_columns`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12349]
In `structs::detail::flatten_nested_columns`, the default stream and default device resource are always used for computing the internal data. This should be corrected to explicitly use the current `stream` and `mr` values passed in by the caller function.

**Comment by GregoryKimball** [comment]
I'm surprised that we didn't catch this in our stream sanitization tests. Do we have adequate unit tests for `structs::detail::flatten_nested_columns`?

**Comment by ttnghia** [comment]
Yes we have a lot of tests for that API. But as you know, most unit tests never specify the `stream` or `mr` parameters.
