### ISSUE TITLE
[FEA] Create a single RAPIDS library

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1234]
**Is your feature request related to a problem? Please describe.**
Hi all,

I would like to share with you the following idea:

So just as we have the following imports:

> import pandas as pd
> import tensorflow as tf
> import matplotlib as plt

why do not create a rapids library that could be imported as follows?

> import rapids as rs

or

> from rapids import cudf

I am aware that there are pros about having each library separate, but I think there are also pros about having a single library, such us

- easier for the data scientists to install: conda install rapids
- it creates a kind of identity around rapids (we do not think on cudf or cuml as independent identities, but as a whole).
- we might adopt 'rs' as a shortcut for rapids (currently, I have only found the following use of 'rs' import rhinoscriptsyntax as  rs)

Please, share your thoughts about the above.

Thanks!

P.S.: There are also cons about having a huge library, but I think the pros exceed the cons.

**Comment by kkraus14** [comment]
This is out of scope for now, possibly to be revisited in the future.
