### ISSUE TITLE
[QST] Ubuntu 22.04 support?

### ISSUE THREAD

**Issue by kuenzb** [rapidsai/cudf#12378]
Is there plans to add support for Ubuntu 22.04? Unable to install due to various incompatibilities

**Comment by beckernick** [comment]
Official support for Ubuntu 22.04 is [targeted for the RAPIDS 23.02 release](https://docs.rapids.ai/notices/rsn0025/).

While Ubuntu 22.04 is not officially supported in the 22.12 release, things may work currently. Could you share the commands you used to install, the output the commands generated, and your system information?

**Comment by GregoryKimball** [comment]
Thank you for alerting us about this issue. We've have Ubuntu 22.04 support since our 23.02 release. [Here are some docker images you can use](https://hub.docker.com/r/rapidsai/rapidsai/tags?page=1&name=ubuntu22.04).
