### ISSUE TITLE
[QST] Install cudf 22.04 via pip

### ISSUE THREAD

**Issue by fabiogeraci** [rapidsai/cudf#12379]
I am getting a conflict with protobuf, because I also install tensorflow-gpu 2.9.1. I use 
`pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com`
but this installs cudf-cu11-22.10 which upgrades protobuf to 3.20.1, and therefore creating the conflict because tensorflow requires protobuf = 3.19.6.

how can i install a version of cudf compatible with tensorflow, using pip?

**Comment by beckernick** [comment]
There is no way to match protobuf versions using the cuDF pip packages. To use cuDF with Tensorflow, we generally recommend using conda packages for cuDF and Tensorflow (which allows protobuf v3.20) or the [NVIDIA Tensorflow container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow) which also contains cuDF.

It's fine to use the protobuf v3.20.1 that cuDF requires with Tensorflow if you're using Linux. Despite the warning from pip, things will work as expected.
