### ISSUE TITLE
[BUG] Calling get_json_object on an empty string column throws an exception

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#12383]
**Describe the bug**
If I try to call `get_json_object` on an empty string column I get an exception.

```
CUDF failure at: /home/roberte/src/spark-rapids-jni/thirdparty/cudf/cpp/include/cudf/detail/utilities/cuda.cuh:66: num_blocks must be > 0
```

**Steps/Code to reproduce bug**
// This is in scala, but the C++ code is very simple to do the same kind of thing
```
val cv = ColumnVector.fromStrings()
val path = Scalar.fromString("$.foo")
cv.getJSONObject(path).close()
ai.rapids.cudf.CudfException: CUDF failure at: /home/roberte/src/spark-rapids-jni/thirdparty/cudf/cpp/include/cudf/detail/utilities/cuda.cuh:66: num_blocks must be > 0
  at ai.rapids.cudf.ColumnView.getJSONObject(Native Method)
  at ai.rapids.cudf.ColumnView.getJSONObject(ColumnView.java:2874)
  ... 49 elided
```

**Expected behavior**
I get back an empty string column with no rows, just like the input data.

**Comment by davidwendt** [comment]
So an empty column with an empty JSON path parameter will return an empty column.
The API generally returns a null entry when the path is not found.
Seems reasonable to return an empty column when given an empty input. 
This is consistent with most other libcudf APIs when given an empty input.
