### ISSUE TITLE
[BUG] No module named 'pandas.core.arrays._arrow_utils' when using dataporc rapids

### ISSUE THREAD

**Issue by blis-teng** [rapidsai/cudf#12386]
**Describe the bug**
I am trying to setup a dataproc cluster with GPU attached, to use cuml and cudf, I followed the instruction https://github.com/GoogleCloudDataproc/initialization-actions/blob/master/rapids/README.md
And able to setup the cluster, with nvidia driver successfully installed. But when I try
```
import cudf
```
It throws out the error

```
TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t)
```
I follow the instruction here: https://docs.rapids.ai/notices/rsn0020/
But after the downgraded version, another error show up when import cudf which is

```
No module named 'pandas.core.arrays._arrow_utils'
```

**Steps/Code to reproduce bug**
1. setup a GCP dataproc with the instruction.
2. import cudf

**Expected behavior**
cudf successfully imported.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by beckernick** [comment]
Thanks for filing this issue. Let's consolidate discussion in https://github.com/GoogleCloudDataproc/initialization-actions/issues/1039#issuecomment-1352504826

Closing in favor of the GCP Dataproc issue.
