### ISSUE TITLE
Converting cuDF dataframe to DMatrix on GPU directly

### ISSUE THREAD

**Issue by diefimov** [rapidsai/cudf#1239]
In order to train XGBoost model we should create DMatrix on CPU. This is a bottleneck of using cuDF together with XGBoost package. The current pipeline of preprocessing and training looks as follows:

**load data to GPU -> preprocess data using cuDF on GPU -> transfer data to CPU -> create DMatrix on CPU -> train XGBoost model on GPU**

Is it possible to skip transferring data to CPU for training XGBoost model on GPU?

**Comment by randerzander** [comment]
There's a [WIP PR](https://github.com/dmlc/xgboost/pull/3997) for supporting this directly in dmlc/xgboost.

In the meantime, you can do what you described by building the [cudf-interop branch of rapidsai/xgboost]https://github.com/rapidsai/xgboost).
