### ISSUE TITLE
[FEA] Decide what pandas versions to support in tests

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#12398]
**Is your feature request related to a problem? Please describe.**
cudf currently maintains [a set of pandas version flags](https://github.com/rapidsai/cudf/blob/main/python/cudf/cudf/core/_compat.py) that are used to branch behavior. To my knowledge, in practice these flags are used almost entirely within our testing code. In principle such branching could be useful. In practice, however, these flags are used so sparsely that it is a virtual guarantee that using any pandas version much older than the one currently being tested in CI will lead to cudf test failures due to changes that are not feature-flagged in this way.

**Describe the solution you'd like**
We should decide (and preferably document in the developer documentation) what pandas versions we want to support at this level of compatibility going forward. We should probably restrict ourselves to (at most) three total minor versions of pandas (e.g. 1.3-1.5) in order to limit the degree of special-casing needed. We should eliminate all of the current branches dealing with old pandas versions that our tests no longer need to support.

**Describe alternatives you've considered**
None

**Additional context**
pandas 2.0 is pretty close at this point. Depending on whether this signals an intent by pandas developers to be a bit more aggressive than they have been historically about releasing major versions, we may want to adjust our strategy going forward to minimize the overhead to cudf devs.

**Comment by bdice** [comment]
I opened https://github.com/rapidsai/cudf/issues/12785 suggesting a bump of cudf's minimum requirements to `pandas>=1.3.0` and `numpy>=1.21` to align with dask. That would let us delete some testing code for prior versions of pandas.

I'm also linking a few other prior conversations on this topic.
- https://github.com/rapidsai/cudf/pull/12150#discussion_r1023078133
- https://github.com/rapidsai/cudf/pull/12244#discussion_r1048930390

**Comment by vyasr** [comment]
This was addressed in https://github.com/rapidsai/cudf/pull/15145 and is now codified in [our testing developer docs](https://docs.rapids.ai/api/cudf/stable/developer_guide/testing/#version-testing).
