### ISSUE TITLE
[QST] cuDF to Snowflake connection

### ISSUE THREAD

**Issue by girishlc** [rapidsai/cudf#12400]
Hi Team,

I have the requirement where I need to get the data from Snowflake and process using CUDA and then load the result back into Snowflake.

1. Is there any way to connect to Snowflake from cuDF?
2. Does cuDF support probabilistic match packages? like fuzzy-wuzzy, rapidfuzz, etc from Python?
Thank you,
Girish.L.C

**Comment by galipremsagar** [comment]
cc: @ayushdg

**Comment by ayushdg** [comment]
For 1., yes It is possible to load data from snowflake into dask-cuDF or cuDF dataframes with the help of the [dask-snowflake](https://github.com/coiled/dask-snowflake) which uses the [snowflake-python-connector](https://docs.snowflake.com/en/user-guide/python-connector.html).
Here's a [blogpost](https://medium.com/snowflake/large-scale-machine-learning-with-snowflake-and-rapids-7796b5e979aa) with more information about moving data b/w Snowflake and Rapids and here's the example [notebook](https://gist.github.com/ayushdg/721d5eb9d52da7f63d291f80cb1fd114#file-snowflake-rapids-ipynb) highlighted in the blog.

Another option is to use the `snowflake-python-connector` directly to load the data from [snowflake to pandas](https://docs.snowflake.com/en/user-guide/python-connector-pandas.html) and then use the `cudf.from_pandas` api to create a cuDF dataframe. Though for larger datasets the dask-snowflake approach is more optimized and performant.

**Comment by beckernick** [comment]
> Does cuDF support probabilistic match packages? like fuzzy-wuzzy, rapidfuzz, etc from Python?

The libraries you've mentioned are designed to run on the CPU, so you'd to convert from cuDF to some kind of data structure they understand to use them (perhaps pandas).

cuDF [provides an edit distance function](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.core.column.string.stringmethods.edit_distance) that uses Levenshtein distance, with which you could do fuzzy string matching. You could also take a different approach and do string matching by using some combination of ngrams, TF-IDF, and Nearest Neighbors (exact or approximate), depending on the data. This is often considered to be more scalable.

**Comment by beckernick** [comment]
Closing as answered. Please feel free to reopen the discussion if anything else comes up.

**Comment by girishlc** [comment]
@ayushdg , @beckernick  thanks for the reply.

@ayushdg , you have mentioned about the dask-cuDF. I'm looking for CUDA dataframe example. Please let me know if any way to load it from snowflake to CUDA Dataframe.

**Comment by beckernick** [comment]
The suggestions above refer to dataframes GPU ("CUDA dataframes"). If you run into any issues, please feel free to comment.
