### ISSUE TITLE
[QST] apply_rows on string-based columns?

### ISSUE THREAD

**Issue by iwwwish** [rapidsai/cudf#12430]
**Does cudf support apply_rows on string-based columns ?**

I am trying to use cudf for faster processing of chemical structures to calculate some properties based on a toolkit called RDKit. For each row, which is a molecule denoted as SMILES string, the code converts SMILES into a molecule object and calculates some basic properties. Here's how my code looks:

```
import cudf
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors
import time

def calc_desc(smiles, desc_dict):
        m = Chem.MolFromSmiles(smiles)
        if m is not None:
                desc_dict['MOLWT'] = Descriptors.MolWt(m) # molecular weight
                desc_dict['TPSA'] = Descriptors.TPSA(m) # topological polar surface area
                desc_dict['LOGP'] = Descriptors.MolLogP(m) # octanol-water partition coefficient
        return desc_dict

start = time.time()

df = pd.read_csv('virtual_lib_100k.csv', names=['SMILES'])
# desc_list = ['MOLWT', 'TPSA', 'LOGP']
# df[desc_list] = df.SMILES.apply(lambda x: pd.Series(calc_desc(x)))
# df.to_csv('virtual_lib_100k_desc_pandas.csv', index=False)
cu_df = cudf.from_pandas(df)
cu_df = cu_df.apply_rows(calc_desc, incols=['SMILES'], outcols=dict(desc_dict=np.float64), kwargs=dict())
cu_df.to_csv('virtual_lib_100k_desc_rapids.csv', index=False)

end = time.time()
print(f"Time taken: {(end-start)} seconds")
```
I was hoping to process millions of rows to see if I can get this done faster than using Pandas, but I get the following error:

```
Traceback (most recent call last):
  File "rdkit_rapids.py", line 30, in <module>
    cu_df = cu_df.apply_rows(calc_desc, incols=['SMILES'], outcols=dict(desc_dict=np.float64), kwargs=dict())
  File "/home/ubuntu/anaconda3/envs/rdkit_2020_06/lib/python3.6/site-packages/cudf/core/dataframe.py", line 3578, in apply_rows
    cache_key=cache_key,
  File "/home/ubuntu/anaconda3/envs/rdkit_2020_06/lib/python3.6/site-packages/cudf/utils/applyutils.py", line 86, in apply_rows
    return applyrows.run(df)
  File "/home/ubuntu/anaconda3/envs/rdkit_2020_06/lib/python3.6/site-packages/cudf/utils/applyutils.py", line 158, in run
    inputs = {k: df[k]._column.data_array_view for k in self.incols}
  File "/home/ubuntu/anaconda3/envs/rdkit_2020_06/lib/python3.6/site-packages/cudf/utils/applyutils.py", line 158, in <dictcomp>
    inputs = {k: df[k]._column.data_array_view for k in self.incols}
  File "/home/ubuntu/anaconda3/envs/rdkit_2020_06/lib/python3.6/site-packages/cudf/core/column/column.py", line 84, in data_array_view
    raise ValueError("Cannot get an array view of a StringColumn")
ValueError: Cannot get an array view of a StringColumn
```

So, I am wondering if cudf supports operations on string based columns. I see some discussion in #5646 but was not sure if it was answered completely. The commented lines in above code is the pandas equivalent code that achieves what I want.

Thank you,
Vishal

**Comment by shwina** [comment]
Unfortunately, the `.apply()` function in cuDF is somewhat limited compared to Pandas. In particular, we don't support using "external" libraries (in this case, `rdkit`, inside UDFs). We simply have no way to generate CUDA kernels from totally arbitrary Python functions like these.

That being said, I'm curious if it isn't possible to leverage RAPIDS/cuDF to do this kind of operation on the GPU. Given a SMILES string, how trivial or non-trivial is it to write a function like `MolWt()` that will compute the molecular weight corresponding to that string? If that function is composed of relatively simple operations, it may be possible to parallelize on the GPU.

**Comment by iwwwish** [comment]
Hi Ashwin! Thanks for explaining the limitation. To answer your question on how trivial it is to write a function like MolWt(): it should be pretty straightforward if it is a simple property like Molecular Weight but I will have to compute a few complex descriptors that are already well defined in libraries like RDKit. So I am not sure if it is worth re-writing them. I'll explore further to see if I can find ways to parallelize my task using the RDkit library.

**Comment by shwina** [comment]
Yes, unfortunately it will need rewriting of the descriptor functions. 

I'm going to go ahead and close this issue as "answered", but if you're interested in exploring this further down the road, please feel free to reopen this issue!
