### ISSUE TITLE
[QST]When performing unique on a string column, the longer the string, the longer it takes?

### ISSUE THREAD

**Issue by infzo** [rapidsai/cudf#12438]
### Description 

Currently, there is a column of string data. When the unique command is executed, the larger the average length of the string in the column, the longer the time is consumed.

`unique` url: https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.core.column.lists.listmethods.unique

```
# Table (Actual number of rows: 30 million)
----------------------------------------------------------------
col_a              col_b
----------------------------------------------------------------
[aa, bb]           [uuuuuuuuuuuu, vvvvvvvvvvvvv]
[cc, dd, ee]       [wwwwwwwwww, xxxxxxxxxxxxx, yyyyyyyyyyyyy]
[ff]               [zzzzzzzzzzzzzz]
----------------------------------------------------------------

start_a = time.time()
df['col_a'].list.unique()
cost_a = time.time() - start_a

start_b = time.time()
df['col_b'].list.unique()
cost_b = time.time() - start_b

# Result:
cost_a < cost_b 
```

### Question
1. What is the cause of this?
2. How do I avoid time-consuming scaling up as the string length increases?

**Comment by davidwendt** [comment]
Yes, longer strings can take longer since most cudf function operate on a thread per row. So longer rows in lists may by slower. I expect this would occur with integers as well though I've not had a chance to test that.

```
col_a     col_b
[1,2,3]   [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3]
[2,3]     [3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
[4]       [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4]
```

**Comment by GregoryKimball** [comment]
Thank you @infzo for sharing this performance analysis. I believe that you're observing expected behavior. Please feel free to re-open if you'd like to have further discussion.
