### ISSUE TITLE
The edit_distance_matrix function return list in the value

### ISSUE THREAD

**Issue by Kafuuaki** [rapidsai/cudf#12433]
**Is your feature request related to a problem? Please describe.**
Hi team! I found that the edit_distance_matrix function return a list instead of a cupy array in the value, makes in not compatible with other function in the cupy library, for example, there is a "TypeError: *obj* doesn't implement the cuda array interface." if you call the values of the series.

**Describe the solution you'd like**
May be rewite it using cp.array instead of list

**Comment by bdice** [comment]
@Kafuuaki You can take the resulting lists column, access the resulting values, and convert to a CuPy array of the appropriate shape. Try this example (tested with cuDF 22.10):

```python
import cudf
import cupy
s = cudf.Series(["abc", "bc", "cba"])
edit_distances = s.str.edit_distance_matrix()
print("Edit distances:")
print(edit_distances)

array_shape = (len(s),) * 2
array = cupy.asarray(edit_distances.list.leaves).reshape(array_shape)
print("cupy array:")
print(array)
```

Result:
```
Edit distances:
0    [0, 1, 2]
1    [1, 0, 2]
2    [2, 2, 0]
dtype: list
cupy array:
[[0 1 2]
 [1 0 2]
 [2 2 0]]
```

**Comment by vyasr** [comment]
Closing since the above documents a seemingly appropriate workaround. Please reopen if necessary.
