### ISSUE TITLE
[BUG] cuDF build error

### ISSUE THREAD

**Issue by huangsongjue** [rapidsai/cudf#1243]
**cuDF (branch-0.7) build failed while `make -j`**

**Error Message:**

/root/cudf/cpp/src/string/nvcategory_util.cpp: In function 'NVCategory* {anonymous}::combine_column_categories(gdf_column**, int)':
/root/cudf/cpp/src/string/nvcategory_util.cpp:19:50: error: 'class NVCategory' has no member named 'merge_and_remap'
           combined_category = combined_category->merge_and_remap(
                                                  ^
/root/cudf/cpp/src/string/nvcategory_util.cpp:28:35: error: 'class NVCategory' has no member named 'copy'
         return combined_category->copy();
                                   ^
/root/cudf/cpp/src/string/nvcategory_util.cpp: In function 'gdf_error nvcategory_gather(gdf_column*, NVCategory*)':
/root/cudf/cpp/src/string/nvcategory_util.cpp:76:34: error: 'class NVCategory' has no member named 'add_keys_and_remap'
       nv_category = nv_category->add_keys_and_remap(*strs);
                                  ^
/root/cudf/cpp/src/string/nvcategory_util.cpp:109:44: error: 'class NVCategory' has no member named 'gather'
   NVCategory * new_category = nv_category->gather(static_cast<nv_category_index_type *>(column->data),
                                            ^
/root/cudf/cpp/src/string/nvcategory_util.cpp:117:44: error: invalid conversion from 'nv_category_index_type* {aka int*}' to 'unsigned int*' [-fpermissive]
                            DEVICE_ALLOCATED);
                                            ^
In file included from /root/cudf/cpp/src/string/nvcategory_util.cpp:5:0:
/root/cudf/cpp/build/include/nvstrings/NVCategory.h:94:9: note:   initializing argument 1 of 'int NVCategory::get_values(unsigned int*, bool)'
     int get_values( unsigned int* results, bool devmem=true );
         ^
/root/cudf/cpp/src/string/nvcategory_util.cpp: In function 'gdf_error concat_categories(gdf_column**, gdf_column*, int)':
/root/cudf/cpp/src/string/nvcategory_util.cpp:154:13: error: invalid conversion from 'nv_category_index_type* {aka int*}' to 'unsigned int*' [-fpermissive]
         true);
             ^
In file included from /root/cudf/cpp/src/string/nvcategory_util.cpp:5:0:
/root/cudf/cpp/build/include/nvstrings/NVCategory.h:94:9: note:   initializing argument 1 of 'int NVCategory::get_values(unsigned int*, bool)'
     int get_values( unsigned int* results, bool devmem=true );
         ^
In file included from /root/cudf/cpp/include/types.hpp:19:0,
                 from /root/cudf/cpp/src/string/nvcategory_util.hpp:6,
                 from /root/cudf/cpp/src/string/nvcategory_util.cpp:2:
/root/cudf/cpp/src/string/nvcategory_util.cpp: In function 'gdf_error sync_column_categories(gdf_column**, gdf_column**, int)':
/root/cudf/cpp/src/string/nvcategory_util.cpp:185:46: error: 'class NVCategory' has no member named 'values_cptr'
                           combined_category->values_cptr() + current_column_start_position,
                                              ^
/root/cudf/cpp/src/utilities/error_utils.hpp:120:33: note: in definition of macro 'CUDA_TRY'
     cudaError_t const status = (call);                            \
                                 ^
/root/cudf/cpp/src/string/nvcategory_util.cpp:191:76: error: 'class NVCategory' has no member named 'copy'
     output_columns[column_index]->dtype_info.category = combined_category->copy();
                                                                            ^
CMakeFiles/cudf.dir/build.make:101: recipe for target 'CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o' failed

**Steps/Code to reproduce bug**
Follow this guide https://github.com/rapidsai/cudf/blob/branch-0.7/CONTRIBUTING.md#setting-up-your-build-environment,  failed in the `make -j ` stage.

**Environment details (please complete the following information):**
**git***
commit abea67901cfcbc19c05101fad1abe35dce2532b2 (HEAD -> branch-0.7, origin/branch-0.7, origin/HEAD)
Merge: d5ca4b1 11dda6e
Author: gpuCI <38199262+GPUtester@users.noreply.github.com>
Date:   Mon Mar 18 16:39:33 2019 -0400

    Merge pull request #1225 from rapidsai/branch-0.6
    
    [gpuCI] Auto-merge branch-0.6 to branch-0.7 [skip ci]

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux 1edfd97799d5 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Wed Mar 20 02:49:58 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
| N/A   38C    P0    39W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                56
On-line CPU(s) list:   0-55
Thread(s) per core:    2
Core(s) per socket:    14
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz
Stepping:              4
CPU MHz:               1000.000
CPU max MHz:           2201.0000
CPU min MHz:           1000.0000
BogoMIPS:              4405.23
Virtualization:        VT-x
Hypervisor vendor:     vertical
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              19712K
NUMA node0 CPU(s):     0-13,28-41
NUMA node1 CPU(s):     14-27,42-55
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke spec_ctrl intel_stibp flush_l1d

***CMake***
/conda/envs/cudf_dev/bin/cmake
cmake version 3.14.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148

***Python***
/conda/envs/cudf_dev/bin/python
Python 3.7.2

***Environment Variables***
PATH                            : /conda/envs/cudf_dev/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64
NUMBAPRO_NVVM                   : /usr/local/cuda/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE              : /usr/local/cuda/nvvm/libdevice
CONDA_PREFIX                    : /conda/envs/cudf_dev
PYTHON_PATH                     : 

***conda packages***
/conda/bin/conda
# packages in environment at /conda/envs/cudf_dev:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boost                     1.68.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37hf0e25f4_1    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.8.0                      py_0    conda-forge
cmake                     3.14.0               hf94ab9c_0    conda-forge
commonmark                0.8.1                      py_0    conda-forge
cryptography              2.6.1            py37h9d9f1b6_0    conda-forge
curl                      7.64.0               h646f8bb_2    conda-forge
cython                    0.29.6           py37hf484d3e_0    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.1.4                      py_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.26.0                   py37_1    conda-forge
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
future                    0.17.1                py37_1000    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.3.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
libblas                   3.8.0                4_openblas    conda-forge
libcblas                  3.8.0                4_openblas    conda-forge
libcurl                   7.64.0               h541490c_2    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
liblapack                 3.8.0                4_openblas    conda-forge
libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.1                h22169c7_0    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libuv                     1.26.0               h14c3975_0    conda-forge
llvmlite                  0.28.0           py37hf484d3e_0    numba
Markdown                  2.6.11                    <pip>
markupsafe                1.1.1            py37h14c3975_0    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.4.1                      py_2    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbsphinx                  0.4.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  5.7.6                    py37_0    conda-forge
numba                     0.43.0          np116py37hf484d3e_0    numba
numpy                     1.16.2           py37h8b7e671_1    conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
nvstrings                 0.2.0            cuda9.2_py37_0    nvidia
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37hf484d3e_0    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         4    conda-forge
parso                     0.3.4                      py_0    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.0.3                   py37_0    conda-forge
pluggy                    0.9.0                      py_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.6.1            py37h14c3975_0    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.12.1           py37hbbcf98d_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyrsistent                0.14.11          py37h14c3975_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.3.1                    py37_0    conda-forge
python                    3.7.2                h381d211_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    5.1              py37h14c3975_0    conda-forge
pyzmq                     18.0.1           py37h0e1adb2_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
recommonmark              0.5.0                      py_0    conda-forge
requests                  2.21.0                py37_1000    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    1.8.5                    py37_0    conda-forge
sphinx-markdown-tables    0.0.9                     <pip>
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.26.0            h67949de_1001    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.1            py37h14c3975_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.1                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
 

**Additional context**

**Comment by harrism** [comment]
The problem is probably that you don't have the latest nvstrings installed. Can you please activate your conda environment and run `conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults nvstrings=0.3 python=3.7`?  

After that, remove your build directory and rebuild.

We are working on updating the documentation and conda environment configuration to make this smoother.

**Comment by eyalroz** [comment]
Also encountered this bug just now.

@harrism : I'm manually downloaded and installed the latest nvstrings available on anaconda.org - but it's not 0.3; there is no version 0.3 there. 0.2 is the latest.

**Comment by j-ieong** [comment]
@eyalroz It seems that nvstrings-0.3 is under the rapidsai channel, rather than nvidia channel. I don't know why.
Additionally, the default uses CUDA9.2 so I had to manually install the CUDA10 version. https://anaconda.org/rapidsai/nvstrings

**Comment by eyalroz** [comment]
@j-ieong : Thanks, will check. However, CMakeLists.txt must check for the appropriate minimum version, and the conda environment should take care of actually getting the appropriate version.

**Comment by eyalroz** [comment]
@j-ieong : The nvstrings package binaries are broken - at least for CUDA 9.2 and Python 3.6:
```
$ conda install -c rapidsai/label/cuda9.2 nvstrings
... etc. etc.. 

Downloading and Extracting Packages
nvstrings-0.3.0      | 14.8 MB   | ####################################################################################################################################### | 100% 
CondaFileIOError: '/home/eyalroz/miniconda2/pkgs/nvstrings-0.3.0-cuda9.2_py36_18.tar.bz2'. contains unsafe path: lib/libNVCategory.so
```

**Comment by eyalroz** [comment]
@huangsongjue : Would you mind editing your opening comment so as to properly format the quoted text? Put it within \``` \``` marks please.

**Comment by harrism** [comment]
@eyalroz cuDF requires Python 3.6 or later: https://github.com/rapidsai/cudf/tree/branch-0.6#customizing-the-build

**Comment by eyalroz** [comment]
> @eyalroz cuDF requires Python 3.6 or later: https://github.com/rapidsai/cudf/tree/branch-0.6#customizing-the-build

Then why isn't CMake not failing the build configuration when we only have Python 3.5.x?

**Comment by j-ieong** [comment]
@eyalroz Did you update conda recently? I had that message when I updated conda prior to installing. I rebooted my system, tried again and that went away.

If that doesn't work, @vuule had to modify conda itself to get past it.

**Comment by eyalroz** [comment]
@j-ieong : I don't reboot my system unless it hangs or I need to update the kernel. But I'm trying a further update which @harrism suggested to me in bug #1248 , and that might work.

**Comment by j-ieong** [comment]
@eyalroz Yeah, understandable. For me, that was the fastest way to get past it after trying several things.

**Comment by eyalroz** [comment]
Ok, this solved things for me:
```
conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults nvstrings=0.3 python=3.7
```
or replace 10.0 with 9.2 depending on your version of CUDA.

I still feel CMake should do more version checking.

**Comment by harrism** [comment]
Possibly. Maybe file an issue for that.

**Comment by huangsongjue** [comment]
> The problem is probably that you don't have the latest nvstrings installed. Can you please activate your conda environment and run `conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults nvstrings=0.3 python=3.7`?
> 
> After that, remove your build directory and rebuild.
> 
> We are working on updating the documentation and conda environment configuration to make this smoother.

@harrism thanks, it works, and I agreed with @eyalroz cmake should do the vesion check.

**Comment by harrism** [comment]
Note that PR #1252 should fix this, if you use the conda/envs/cudf_dev*.yml files to configure your environment.

**Comment by atlasgurus** [comment]
Thank you @harrism .  I see that #1252 is already fixed in branch-0.6, so I tried it as follows and still got similar build errors.  Is there a stable branch that I can use to build it?
git checkout branch-0.6
conda env create --name cudf_dev3 --file conda/environments/cudf_dev_cuda9.2.yml
source activate cudf_dev3
cd cpp/build
cmake .. -DCMAKE_INSTALL_PREFIX=/install/path -DCMAKE_BUILD_TYPE=Debug
make -j
......
/home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp: In function ‘gdf_error concat_categories(gdf_column**, gdf_column*, int)’:
/home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:153:9: error: invalid conversion from ‘nv_category_index_type* {aka int*}’ to ‘unsigned int*’ [-fpermissive]
         static_cast<nv_category_index_type *>(output_column->data),
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:5:0:
/home/ubuntu/projects/cudf/cpp/build/include/nvstrings/NVCategory.h:94:9: note:   initializing argument 1 of ‘int NVCategory::get_values(unsigned int*, bool)’
     int get_values( unsigned int* results, bool devmem=true );
.....

**Comment by atlasgurus** [comment]
I have run the command below too for goo measure

conda install -c nvidia/label/cuda9.2 -c rapidsai/label/cuda9.2 -c numba -c conda-forge -c defaults nvstrings=0.3 python=3.7

but still got the same errors as listed in this issue:
`/home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp: In function ‘NVCategory* {anonymous}::combine_column_categories(gdf_column**, int)’:
/home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:19:50: error: ‘class NVCategory’ has no member named ‘merge_and_remap’
           combined_category = combined_category->merge_and_remap(
                                                  ^~~~~~~~~~~~~~~
/home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:28:35: error: ‘class NVCategory’ has no member named ‘copy’
         return combined_category->copy();
`

**Comment by eyalroz** [comment]
@atlasgurus : Did you delete your build directory, recreate it and rebuilt?

**Comment by atlasgurus** [comment]
@eyalroz , thank you very much for the suggestion.  It did help.  I think I am almost there.  It now fails during link step:

`/usr/bin/x86_64-linux-gnu-ld: warning: libcudart.so.9.2, needed by /home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so, not found (try using -rpath or -rpath-link)
/home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so: undefined reference to `cudaLaunchKernel@libcudart.so.9.2'
/home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so: undefined reference to `cudaMemcpy@libcudart.so.9.2'
/home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so: undefined reference to `cudaFree@libcudart.so.9.2'
/home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so: undefined reference to `__cudaRegisterFatBinary@libcudart.so.9.2'
/home/ubuntu/projects/cudf/cpp/build/lib/libNVCategory.so: undefined reference to `__cudaRegisterVar@libcudart.so.9.2'
`

**Comment by eyalroz** [comment]
@atlasgurus : Something is messed up with the directories in which the linker is trying to find libraries. I suggest you open a separate issue, and that you provide a full command-line of a failing link command with the `-L` flags.

**Comment by harrism** [comment]
@atlasgurus Are you sure you have CUDA 9.2 installed and not CUDA 10?  It's possibly you have a version mismatch here.
