### ISSUE TITLE
[FEA] Implement `cudf::data_type::to_string()` for debugging purpose

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12440]
Many times, I got exception during cudf development like this:
```
ai.rapids.cudf.CudfException: CUDF failure at: ../src/column/column_factories.cpp:58: Invalid element type.
```

In order to debug the code, I typically add this line:
```
printf("type id: %d\n",(int) input->type().id());
```

The output value can be `type id: 23`. I need to further dig into the `cudf::type_id` enums to figure out what type the value `23` refers to.

It is much more convenient if we have `cudf::data_type::to_string()` so I just call:
```
printf("data type: %s\n",(int) input->type().to_string().c_str());
```
and can get a readable output:
```
data type: STRING
```

**Comment by ttnghia** [comment]
Since this is for debugging/testing purpose, adding a test utility `cudf::test::to_string(data_type)` should be a better option.

**Comment by vyasr** [comment]
Would the changes in https://github.com/rapidsai/cudf/pull/12158 solve your problem? It adds `type_to_name(data_type)`.

**Comment by ttnghia** [comment]
Oh yeah, I didn't realize that. Close the issue.
