### ISSUE TITLE
[QST] cudF/moderngpu build issue for cuda 10.1

### ISSUE THREAD

**Issue by pradghos** [rapidsai/cudf#1244]
**What is your question?**
`cuDF` is having submodule dependecy on `moderngpu`.
https://github.com/rapidsai/thirdparty-moderngpu/tree/c1fd31df008d79f727483e795b1ee1ce45b782ca.

However, `moderngpu` is having below deprecated symbols/PTX instruction which will eventually lead to build
failure for `cuda 10.1`.  

Location : `https://github.com/rapidsai/thirdparty-moderngpu/blob/c1fd31df008d79f727483e795b1ee1ce45b782ca/src/moderngpu/intrinsics.hxx`

``` 
__shfl_down , __shfl_up, 

 SHFL_OP_64b_MACRO - "shfl."#dir".b32 lo|p, lo, %2, %3;" 

 SHFL_OP_MACRO - "shfl."#dir".b32 r0|p, %1, %2, %3;"

 ``` 

 is it going to get fixed in the upcoming releases ? Thank you!

**Comment by harrism** [comment]
We aim to eliminate `moderngpu` ASAP. Thanks for the report.

**Comment by pradghos** [comment]
@harrism : Sure. Thanks for your response ! Once the PR is ready, we would like to give it a try building with `cuda 10.1`

**Comment by harrism** [comment]
ModernGPU is now removed from libcudf.
