### ISSUE TITLE
[BUG] `cudf_assert` does not have effect when `NDEBUG` is defined

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12459]
The documentation of `cudf_assert` states that:
```
...
 * This is effectively the same as the standard `assert` macro, except it will
 * not be compiled out in Release builds, i.e., this macro will be present
 * regardless of the state of `NDEBUG`.
```

However, it is implemented as:
```
#if !defined(NDEBUG) && 
...
#else
#define cudf_assert(e) (static_cast<void>(0))
#endif
```

As such, when `NDEBUG` is defined, this macro is just a no-op and is useless.

**Comment by davidwendt** [comment]
Looks like this was changed in https://github.com/rapidsai/cudf/pull/7583/files#diff-0f2a692a605528b72d11bd3a52ede606247602c5249dff63c8b003362f3d1d67
but the documentation was not updated.
@robertmaynard
