### ISSUE TITLE
【important】The cudf supports the Feather format.

### ISSUE THREAD

**Issue by mjshare** [rapidsai/cudf#12453]
Problem description:
When there are a large number of string columns, data in feather format is much smaller than that in arrow format. When data is transmitted to the GPU in feather format for decompression, the PICE bandwidth pressure is much lower. This requirement is valuable. Can the GPU support the feather format for decompression in GPU like parquet?

**Comment by davidwendt** [comment]
Is this different than #11407 ?

**Comment by mjshare** [comment]
> Is this different than #11407 ?

Similar requirements, Does the community have a solution plan? This reduces the bandwidth consumption of the GPU.

**Comment by davidwendt** [comment]
Any plans will likely be documented in #11407. Recommend closing this issue in favor of that one.

**Comment by beckernick** [comment]
Closing in favor of #11407 as suggested and copying the bandwidth comment
