### ISSUE TITLE
Does cudf support compression?

### ISSUE THREAD

**Issue by mjshare** [rapidsai/cudf#12450]
The arrow table contains multiple string columns. When cudf is used, transmission is affected due to the PICE bandwidth. Does cudf support compression to reduce transmission overhead? Or is there any other way to solve?

**Comment by mjshare** [comment]
> cuDF readers support a variety of compression formats. Could you provide a more concrete example of what you're trying to do? Are you trying to take an Arrow table in memory and convert to a cuDF DataFrame?



//Yes. Our scenario is as follows: Use the Arrow format, convert the arrow to cudf, and use the GPU for calculation. Currently, the arrow contains multiple columns of character strings, which causes the GPU transmission bottleneck. One solution is to compress the arrow, transmit it to the GPU, and then convert it to cudf. Do you have any other suggestions on this issue?
@beckernick

**Comment by GregoryKimball** [comment]
Thank you @mjshare for your comments. You might try writing a compressed parquet file to a host buffer and then reading that with `cudf.read_parquet`. Even an uncompressed parquet file dramatically reduces data size for some inputs with dictionary encoding. 
> causes the GPU transmission bottleneck
What is the throughput (GB/s) you are observing?

**Comment by GregoryKimball** [comment]
Thank you @mjshare for raising this use case. Please let us know if you would like to continue the discussion.
