### ISSUE TITLE
[BUG] Pip installed cuDF throws cudaErrorNotSupported error on Windows 10 WSL2

### ISSUE THREAD

**Issue by KevinOneSixDotNet** [rapidsai/cudf#12454]
**Describe the bug**
Hello,

I am running into an issue initializing a cudf series as per step 6 of the pip instructions on the WSL2 install documentation: https://rapids.ai/wsl2.html 

I am unsure if this is a legitimate issue with my environment or if there is an issue with cudf on pascal based cards

**Steps/Code to reproduce bug**
I run the following code in my environment

`import cudf`
`print(cudf.Series([1, 2, 3]))  #This line produces the error`

I receive the error:

`TypeError: memoryview: a bytes-like object is required, not 'list'`

During handling of the above exception, another exception occurred:

RuntimeError: Fatal CUDA error encountered at: /project/cpp/src/bitmask/null_mask.cu:94: 801 cudaErrorNotSupported operation not supported`

**Expected behavior**
Series would print out, similar to the behavior of pandas

**Environment overview (please complete the following information)**
 - Environment location: WSL2 (Ubuntu 20.04, Windows 10)
 - Method of cuDF install: Pip

**Environment details**
`
     ***git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
     NAME="Ubuntu"
     VERSION="20.04.3 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.3 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux DESKTOP-93TUHEB 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Dec 30 11:33:04 2022
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 525.65       Driver Version: 527.56       CUDA Version: 12.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
     | 37%   26C    P8     5W / 120W |   1101MiB /  3072MiB |     22%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   39 bits physical, 48 bits virtual
     CPU(s):                          4
     On-line CPU(s) list:             0-3
     Thread(s) per core:              1
     Core(s) per socket:              4
     Socket(s):                       1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           158
     Model name:                      Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
     Stepping:                        9
     CPU MHz:                         2999.997
     BogoMIPS:                        5999.99
     Hypervisor vendor:               Microsoft
     Virtualization type:             full
     L1d cache:                       128 KiB
     L1i cache:                       128 KiB
     L2 cache:                        1 MiB
     L3 cache:                        6 MiB
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
     Vulnerability L1tf:              Mitigation; PTE Inversion
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Mmio stale data:   Mitigation; Clear CPU buffers; SMT Host state unknown
     Vulnerability Retbleed:          Mitigation; IBRS
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS Not affected
     Vulnerability Srbds:             Unknown: Dependent on hypervisor status
     Vulnerability Tsx async abort:   Not affected
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb stibp fsgsbase bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves md_clear flush_l1d arch_capabilities
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     
     ***Environment Variables***
     PATH                            : /home/kevinmen171/.vscode-server/bin/e8a3071ea4344d9d48ef8a4df2c097372b0c5161/bin/remote-cli:/home/kevinmen171/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v11.5/bin:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v11.5/libnvvp:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v10.0/bin:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v10.0/libnvvp:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v10.1/bin:/mnt/c/Program
     Files/NVIDIA                    : GPU
     Computing                       : Toolkit/CUDA/v10.1/libnvvp:/mnt/c/Program
     Files/Microsoft                 : MPI/Bin/:/mnt/c/Program
     Files                           : (x86)/Intel/iCLS
     Client/:/mnt/c/Program          : Files/Intel/iCLS
     Client/:/mnt/c/windows/system32:/mnt/c/windows:/mnt/c/windows/System32/Wbem:/mnt/c/windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Program: Files
     (x86)/Intel/Intel(R)            : Management
     Engine                          : Components/DAL:/mnt/c/Program
     Files/Intel/Intel(R)            : Management
     Engine                          : Components/DAL:/mnt/c/Program
     Files                           : (x86)/Intel/Intel(R)
     Management                      : Engine
     Components/IPT:/mnt/c/Program   : Files/Intel/Intel(R)
     Management                      : Engine
     Components/IPT:/mnt/c/Program   : Files
     (x86)/NVIDIA                    : Corporation/PhysX/Common:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/Program
     Files/dotnet/:/mnt/c/Program    : Files/Microsoft
     SQL                             : Server/Client
     SDK/ODBC/130/Tools/Binn/:/mnt/c/Program: Files
     (x86)/Microsoft                 : SQL
     Server/140/Tools/Binn/:/mnt/c/Program: Files/Microsoft
     SQL                             : Server/140/Tools/Binn/:/mnt/c/Program
     Files/Microsoft                 : SQL
     Server/140/DTS/Binn/:/mnt/c/Program: Files/Microsoft
     SQL                             : Server/130/Tools/Binn/:/mnt/c/Program
     Files/Microsoft                 : SQL
     Server/Client                   : SDK/ODBC/170/Tools/Binn/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program
     Files                           : (x86)/Microsoft
     SQL                             : Server/150/DTS/Binn/:/mnt/c/Program
     Files/nodejs/:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program: Files
     (x86)/Google/Cloud              : SDK/google-cloud-sdk/bin:/mnt/c/Program
     Files/NVIDIA                    : Corporation/Nsight
     Compute                         : 2021.3.0/:/mnt/c/Program
     Files/CMake/bin:/mnt/c/Users/kevin/AppData/Local/Programs/Python/Python311/Scripts/:/mnt/c/Users/kevin/AppData/Local/Programs/Python/Python311/:/mnt/c/Users/kevin/AppData/Local/Programs/Python/Python37/Scripts/:/mnt/c/Users/kevin/AppData/Local/Programs/Python/Python37/:/mnt/c/Users/kevin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/kevin/AppData/Local/Programs/Azure: Data
     Studio/bin:/mnt/c/Users/kevin/.dotnet/tools:/mnt/c/Program: Files
     (x86)/Rico                      : Suter/NSwagStudio/:/mnt/c/Users/kevin/AppData/Roaming/npm:/mnt/c/Users/kevin/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/kevin/AppData/Local/Programs/Microsoft
     VS                              : Code/bin:/mnt/c/MinGW/bin:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     conda not found
     ***pip packages***
     /usr/bin/pip
     Package                Version
     ---------------------- --------------------
     attrs                  19.3.0
     Automat                0.8.0
     blinker                1.4
     cachetools             5.2.0
     certifi                2019.11.28
     chardet                3.0.4
     Click                  7.0
     cloud-init             21.4
     cloudpickle            2.2.0
     colorama               0.4.3
     command-not-found      0.3
     configobj              5.0.6
     constantly             15.1.0
     contourpy              1.0.6
     cryptography           2.8
     cubinlinker-cu11       0.3.0.post1
     cuda-python            11.8.1
     cudf-cu11              22.12.0
     cuml-cu11              22.12.0
     cupy-cuda11x           11.4.0
     cycler                 0.11.0
     Cython                 0.29.32
     dask                   2022.11.1
     dask-cuda              22.12.0
     dask-cudf-cu11         22.12.0.post1
     dbus-python            1.2.16
     distributed            2022.11.1
     distro                 1.4.0
     distro-info            0.23ubuntu1
     entrypoints            0.3
     fastrlock              0.8.1
     fonttools              4.38.0
     fsspec                 2022.11.0
     HeapDict               1.0.1
     httplib2               0.14.0
     hyperlink              19.0.0
     idna                   2.8
     importlib-metadata     1.5.0
     incremental            16.10.1
     Jinja2                 2.10.1
     joblib                 1.2.0
     jsonpatch              1.22
     jsonpointer            2.0
     jsonschema             3.2.0
     keyring                18.0.1
     kiwisolver             1.4.4
     language-selector      0.1
     launchpadlib           1.10.13
     lazr.restfulclient     0.14.2
     lazr.uri               1.0.3
     llvmlite               0.39.1
     locket                 1.0.0
     MarkupSafe             1.1.0
     matplotlib             3.6.2
     more-itertools         4.2.0
     msgpack                1.0.4
     netifaces              0.10.4
     numba                  0.56.4
     numpy                  1.23.5
     nvtx                   0.2.5
     oauthlib               3.1.0
     packaging              22.0
     pandas                 1.5.2
     partd                  1.3.0
     pexpect                4.6.0
     Pillow                 9.3.0
     pip                    20.0.2
     protobuf               3.20.3
     psutil                 5.9.4
     ptxcompiler-cu11       0.7.0.post1
     pyarrow                9.0.0
     pyasn1                 0.4.2
     pyasn1-modules         0.2.1
     PyGObject              3.36.0
     PyHamcrest             1.9.0
     PyJWT                  1.7.1
     pylibraft-cu11         22.12.0
     pymacaroons            0.13.0
     PyNaCl                 1.3.0
     pynvml                 11.4.1
     pyOpenSSL              19.0.0
     pyparsing              3.0.9
     pyrsistent             0.15.5
     pyserial               3.4
     python-apt             2.0.0+ubuntu0.20.4.7
     python-dateutil        2.8.2
     python-debian          0.1.36ubuntu1
     pytz                   2022.7
     PyYAML                 5.3.1
     raft-dask-cu11         22.12.0.post1
     requests               2.22.0
     requests-unixsocket    0.2.0
     rmm-cu11               22.12.0
     scipy                  1.9.3
     seaborn                0.12.1
     SecretStorage          2.3.1
     service-identity       18.1.0
     setuptools             45.2.0
     simplejson             3.16.0
     six                    1.14.0
     sortedcontainers       2.4.0
     sos                    4.2
     ssh-import-id          5.10
     systemd-python         234
     tblib                  1.7.0
     toolz                  0.12.0
     tornado                6.1
     treelite               3.0.1
     treelite-runtime       3.0.1
     Twisted                18.9.0
     typing-extensions      4.4.0
     ubuntu-advantage-tools 27.6
     ucx-py-cu11            0.29.0
     ufw                    0.36
     unattended-upgrades    0.1
     urllib3                1.25.8
     wadllib                1.3.3
     wheel                  0.34.2
     zict                   2.2.0
     zipp                   1.0.0
     zope.interface         4.7.1`

**Additional context**

**Comment by beckernick** [comment]
Thanks for filing an issue. It looks like you're using Windows 10. The linked instructions page indicates Window 11 as a prerequisite.

Would you be able to test this on Windows 11?

**Comment by KevinOneSixDotNet** [comment]
Unfortunately, the processor in my machine is not supported by Windows 11 as per their health check app.

I thought the only reason Windows 11 was specified in the instructions above was the previous limitation of Windows 10 not having WSL2 support (Which is no longer the case). But testing in Windows 11 is not an option at this time.

**Comment by vyasr** [comment]
I think this is the same issue as https://github.com/rapidsai/cudf/issues/11382. AFAIK Pascal-based cards haven't work with cudf on WSL2 since 21.08, and unfortunately since pip support was only added (experimentally) in 22.10 I don't think there's any way we're going to have working pip packages for Pascal cards unless someone is able to resolve the incompatibility (and I think various engineers have tried without success). @taureandyernv can probably say more.

**Comment by KevinOneSixDotNet** [comment]
Ah ok. I thought I saw that was resolved in another GitHub issue but if that is the case I will find a way to run 21.08. 

Thank you.
