### ISSUE TITLE
[BUG] libcudf::read_parquet performance worse than arrow::file_reader

### ISSUE THREAD

**Issue by JacoCheung** [rapidsai/cudf#12479]
**Describe the bug**
Hi teams. I'm from HugeCTR team. I know that`libcudf::read_parquet()` is gpu-accelerated and I'm using it to load data for my application. Recently, I found out `arrow` also has implemented a file_reader which is a cpu reader. I have some performance results for both readers, and the cudf performance seems not promising. I have tested on 3 datasets, and the row_group distributition is illustrated in the left table. For arrow reader, I was parallelizing the reading of each columnchunk. The result demonstrated that for all three files, the arrow was much faster than cudf, 6x for criteo  in particular. The criteo is a prevalent dataset used in recommendation system.

![image](https://user-images.githubusercontent.com/32166257/210726184-b360cdcb-bd2d-48a8-998f-6da32fd9cb20.png)

For both readers, I used c++ api to read data. 

**Steps/Code to reproduce bug**

Since I was using the C++ api, so one has to compile following two code snippets manually,
The files linked to are actually cpp source files (Sorry for the file suffix). The compiling command is prepended in the source files. 
[read_arrow.txt](https://github.com/rapidsai/cudf/files/10350353/read_arrow.txt)
[read_cudf.txt](https://github.com/rapidsai/cudf/files/10350354/read_cudf.txt)

After compilation, running the executables:
- Running arrow reader: `./arrow_parquet <filepath> false`
- Running cudf reader: `./cudf_parquet <filepath>`

**Expected behavior**
More performant data reading.

**Environment overview**
I was using Selene cluster (DGX-A100). Docker image [dockerfile](https://github.com/NVIDIA-Merlin/Merlin/blob/v22.12.00/docker/dockerfile.merlin)

**Comment by GregoryKimball** [comment]
Thanks @JacoCheung for sharing these results.

* Would you please explain the "features" and "row_group" information in the table you shared above? I'm not sure how to interpret this information. I would like to convert it to a list of the columns and their types to better evaluate your observations.
* Did you perform OS cache clearing before each read operation? Generally we recommend this to make sure the order of read operations does not impact the speed of each operation.
* Would you please share nsys profiles of the 'criteo' data set in particular? (If you like we can follow up on profile or dataset exchange on Slack?)
* It looks like you are using the RMM pool - that's great! How does the CUDA memory resource compare?

**Comment by zoltan** [comment]
Is this still true on the latest code?

**Comment by GregoryKimball** [comment]
I did a check of the cuDF python versus pandas-pyarrow performance reading a `criteo/day_0.parquet` file, and the performance of cuDF python was quite good ~35x faster on an A100 GPU and AMD EPYC 7642 CPU.

This script reads the first 10 row groups and then does a timing comparison:
```
import os
import cudf
import pandas 
import rmm
import time

mr = rmm.mr.CudaAsyncMemoryResource()
rmm.mr.set_current_device_resource(mr)
os.environ['KVIKIO_NTHREADS'] = '8'
os.environ['KVIKIO_COMPAT_MODE'] = 'on'

df = cudf.read_parquet('/datasets/criteo/crit_orig_pq/day_0.parquet', row_groups=[0,1,2,3,4,5,6,7,8,9])
print(df)
df.to_parquet('/raid/tmp.pq')


t0 = time.time()
df = cudf.read_parquet('/raid/tmp.pq')
t1 = time.time()
print('cudf.read_parquet', t1-t0)

t0 = time.time()
df = pandas.read_parquet('/raid/tmp.pq', engine='pyarrow')
t1 = time.time()
print('pandas.read_parquet', t1-t0)
```

with output
```
# CUDA_VISIBLE_DEVICES=4 python sc.py
         label    I1    I2    I3    I4    I5    I6 I7  I8  I9  ...       C17       C18       C19       C20       C21       C22       C23       C24       C25       C26
0            0    32     3     5  <NA>     1     0  0  61   5  ...  d20856aa  a1eb1511  9512c20b  febfd863  a3323ca1  c8e1ee56  1752e9e8  75350c8a  991321ea  b757e957
1            0  <NA>   233     1   146     1     0  0  99   7  ...  d20856aa  628f1b8d  9512c20b  c38e2f28  14f65a5d  25b1b089  d7c1fc0b  34a9b905  ff654802  ed10571d
2            0  <NA>    24  <NA>    11    24  <NA>  0  56   3  ...  1f7fc70b  a1eb1511  9512c20b      <NA>      <NA>      <NA>  dc209cd3  b8a81fb0  30436bfc  b757e957
3            0    60   223     6    15     5     0  0   1   8  ...  d20856aa  d9f758ff  9512c20b  c709ec07  2b07677e  a89a92a5  aa137169  e619743b  cdc3217e  ed10571d
4            1     7     1    10     2  <NA>     3  0   0  12  ...      <NA>  b8170bba  9512c20b  8024f45f  0683bc6f  fa7eca6c      <NA>  ecfbb046  ff654802  b757e957
...        ...   ...   ...   ...   ...   ...   ... ..  ..  ..  ...       ...       ...       ...       ...       ...       ...       ...       ...       ...       ...
3449995      0   305  <NA>    26  <NA>  <NA>     0  0   0  28  ...  d20856aa  b8170bba  55191c09  363b5931  e6b76e27  5e8abaf2  af0b7e1f  e1c7216e  ff654802  b757e957
3449996      0     2   339     1  <NA>  <NA>     0  0   6   1  ...      <NA>  b8170bba  108a0699  47849e55  73b3f46d  d994ba60      <NA>  215866f4  30436bfc  2ba8d787
3449997      0     3   200  <NA>  <NA>  <NA>     0  0   0   7  ...      <NA>  a1eb1511  9512c20b  47849e55  73b3f46d  d994ba60      <NA>  2ce085c8  ff654802  b757e957
3449998      0  <NA>   282  <NA>  <NA>  <NA>     0  0  14   0  ...      <NA>  628f1b8d  108a0699  3caa9e85  13ddfdce  592f3e64      <NA>  3a7d4eda  30436bfc  2ba8d787
3449999      0  <NA>   169  <NA>     5  <NA>  <NA>  1  -1   0  ...  d20856aa  b8170bba  9512c20b  febfd863  a3323ca1  c8e1ee56  90d3436e  317d843b  991321ea  b757e957

[3450000 rows x 40 columns]
cudf.read_parquet 0.12324333190917969
pandas.read_parquet 4.23388147354126
```
