### ISSUE TITLE
[FEA] padding operation for the list columns

### ISSUE THREAD

**Issue by bilzard** [rapidsai/cudf#12471]
**Is your feature request related to a problem? Please describe.**

I wish I had padding operation on the list columns.

**Describe the solution you'd like**
```python
df = cudf.DataFrame(
    {"g": [1, 1, 1, 2, 2, 3, 3, 3, 3], "a": [1, 2, 3, 1, 3, 1, 2, 3, 4]}
)
df.groupby("g")["a"].collect().list.pad(max_length=3, pad_left=True, drop="last", padding_value=-1)
```
```
g
1    [1, 2, 3]
2    [-1, 1, 3]
3    [1, 2, 3]
```

**Describe alternatives you've considered**

* implement to `collect` operator with padding option.

```python
df = cudf.DataFrame(
    {"g": [1, 1, 1, 2, 2, 3, 3, 3, 3], "a": [1, 2, 3, 1, 3, 1, 2, 3, 4]}
)
df.groupby("g")["a"].collect(pad=True, max_length=3, pad_left=True, drop="last", padding_value=-1)
```

**Additional context**

This feature will be useful when we want to make data-loader for sequential inputs (like NLP etc.).

**Comment by beckernick** [comment]
Are you familiar with https://github.com/NVIDIA-Merlin/NVTabular and https://github.com/NVIDIA-Merlin/dataloader? They're designed for scalable loading and preprocessing of tabular data for deep learning training workloads.

This kind of NLP / sequence model oriented padding functionality may be a better fit for these projects. I'm not sure if it would work for your use case, but [padding slices of lists columns is supported in NVTabular](https://nvidia-merlin.github.io/NVTabular/main/generated/nvtabular.ops.ListSlice.html?highlight=listslice#nvtabular.ops.ListSlice). 

cc @rjzamora @jperez999

**Comment by bilzard** [comment]
@beckernick In fact, I was trying to use NVTabular for my purpose. I agree with this kind of responsibility is more suitable for these projects. I will learn more about this. Thank you. Closing issue.
