### ISSUE TITLE
[FEA] Support JSON tokenizer from strings column

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12476]
We've filed an issue asking for support JSON reading in https://github.com/rapidsai/cudf/issues/10688. Now our actual use case has been changed. Instead of fully parsing JSON, we just need to tokenize the input given by a strings column. This request is also the building block to implement https://github.com/rapidsai/cudf/issues/10688 in case it is still needed.

In particular, we need a new overload for `cudf::io::json::detail::get_token_stream` API such that it takes a strings column as the input:
```
std::pair<rmm::device_uvector<PdaTokenT>, rmm::device_uvector<SymbolOffsetT>> get_token_stream(
  strings_column_view const& json_in,
  cudf::io::json_reader_options const& options,
  rmm::cuda_stream_view stream,
  rmm::mr::device_memory_resource* mr = rmm::mr::get_current_device_resource());
````

**Comment by GregoryKimball** [comment]
I believe this is also closed by https://github.com/NVIDIA/spark-rapids-jni/pull/844

**Comment by ttnghia** [comment]
No this is something else. We currently just don't support it yet. I'm fine with closing this until there is more use case that needs it.
