### ISSUE TITLE
[BUG] gdf_column comparison functions may produce false negatives

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1248]
Have a look at `gdf_equal_columns()` in `cpp/tests/utilities/cudf_test_utils.cuh` and `columns_are_equal()` in `cpp/tests/table/table_tests.cu` (in branch-0.6 as of right now.)

1. Both of these compare pairs of `gdf_column`s. However, they all expect the `data` pseudo-columns to be byte-for-byte identical. However, for null elements, the `data` pseudo-column can hold any value and still be equal to another column's NULL in the same position.
2. Both of these compare the "slack" bits of the last container of the valid pseudocolumn - although those do not have to be equal, and are unconstrained, if I recall correctly.

**Comment by harrism** [comment]
I believe 49a44f1c437dab88ca08a7b70d5a4c18d8dc4611 fixed this.
