### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_NATIVE'

### ISSUE THREAD

**Issue by newjavaer** [rapidsai/cudf#12500]
When I run ./build.sh with branch 22.12 ,the erro print log is nvcc fatal   : Unsupported gpu architecture 'compute_NATIVE' 
How can I deal the erro ,thank you.

**Comment by newjavaer** [comment]
Thank you for your reply.I confirm my CMake version is 25.1 again.But there still have this bug .I'm trying to figure out how nvcomp is used in the cudf library.It's important for me .It would be even better if you help me figure out which interfaces or functions of NVCOMP are used in CUDF。Thanks

**Comment by bdice** [comment]
If you could provide more information about your system, the commit of cudf you're trying to build, any options you're passing to the build script, and the full output/error traceback, that would be helpful for diagnosing the problem.

@vuule Would you be able to help with the questions about nvcomp?

**Comment by vuule** [comment]
All nvCOMP calls are made from https://github.com/rapidsai/cudf/blob/branch-22.12/cpp/src/io/comp/nvcomp_adapter.cpp
Please let me know if you have any further questions about the nvCOMP use.

**Comment by GregoryKimball** [comment]
Thank you @newjavaer for sharing your experience with libcudf and nvCOMP. Please let us know if you would like to discuss further.
