### ISSUE TITLE
[BUG] NVStrings doesn't install correctly in branch-0.6

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#1251]
The NVStrings dependency installation currently in branch-0.6 is insufficient. Either it installs version 0.2.0 by default, or it installs NVStrings for CUDA 9.2 by default (which is fine for people running CUDA 9.2, but bad for those on CUDA 10).

This is related to #1231

**Comment by kkraus14** [comment]
Fixed by #1252
