### ISSUE TITLE
[QST] Streaming dask-cudf

### ISSUE THREAD

**Issue by Manoj-red-hat** [rapidsai/cudf#12520]
**What is your question?**
Hi everyone, I am trying to create a architecture in which I am streaming arrow batch from flight C++ to flight Python RPC and trying to create a streaming dask-cudf.

Once streaming completed I am going to perform operation on that dask-cudf which underneath utilise mult gpu dask cluster 

Could any provide some guidance exactly how can I approach this?

Thanks

**Comment by Manoj-red-hat** [comment]
@davidwendt

**Comment by GregoryKimball** [comment]
@randerzander Do you have experience with streaming workflows in dask-cudf?

**Comment by randerzander** [comment]
Hi @Manoj-red-hat - you might want to take a look at [Streamz](https://streamz.readthedocs.io/en/latest/).

It allows you to consume streams of external data in batches and process them w/ Dask/Pandas/cuDF in streaming fashion, though you might need to write your own "source".

**Comment by GregoryKimball** [comment]
Hello @Manoj-red-hat, please let us know if you would like to discuss further your application

**Comment by vyasr** [comment]
Closing as stale. Feel free to open if there is more to discuss.
