### ISSUE TITLE
[FEA] Support dask.dataframe.utils.is_dataframe_like

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1253]
For dask-cudf we need cudf DataFrame/Series/Index objects to pass on Dask's `is_dataframe_like/is_series_like/is_index_like` functions to properly identify as partitions.

It would be useful to add tests for these in the cudf codebase.

Today, there is a slight issue in that `cudf.DataFrame.mean` doesn't exist.  It would be helpful on the dask side if this could exist.  Would a NotImplemented version of this function be accepted for 0.6?

cc @kkraus14

**Comment by mrocklin** [comment]
Pointer to dask functions for convenience

https://github.com/dask/dask/blob/24bbcdbbc10931e8accad749a57658e6bb593c40/dask/dataframe/utils.py#L513-L535

**Comment by mrocklin** [comment]
@kkraus14 I'm about to release Dask.  Just checking but will this break things, or did versions get pinned in conda recipes?

**Comment by kkraus14** [comment]
I don't believe so but given the current rate of change in `cudf` and `dask-cudf` I think breaking things is okay and we can guide users to proper versions if/when they run into issues or hotfix release if it becomes an issue.

**Comment by mrocklin** [comment]
OK.  I've just pushed out a release of Dask which breaks Dask-cudf.  This is now a decently high priority issue.

**Comment by mrocklin** [comment]
(at least for me)
