### ISSUE TITLE
Deprecate cudf::strings::repeat_strings_output_sizes in favor of cudf::repeat_strings throwing size limit error

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#12542]
The `cudf::strings::repeat_strings_output_sizes` was created so the output sizes of the `cudf::strings::repeat_strings` API could be pre-computed and checked for possible overflow. The `cudf::strings::repeat_strings` can now throw an exception if the output size will exceed the column limit size so this API is no longer needed.

The following API can be removed: https://docs.rapids.ai/api/libcudf/stable/group__strings__copy.html#gad137eea9f5189b3e8c6384c6ab8def40
The optional parameter for this API can be removed: https://docs.rapids.ai/api/libcudf/stable/group__strings__copy.html#ga89b08a3e8f941f7760087cb9e5bf9758

@revans2

**Comment by ttnghia** [comment]
I'll work on Spark plugin to adapt the changes addressed by this issue.
