### ISSUE TITLE
[BUG] cudf.DataFrame.rolling.std has a slower performance compared to its pandas counterpart

### ISSUE THREAD

**Issue by IMG-5** [rapidsai/cudf#12551]
I have a dataset of 10 million rows of which I am applying rolling standard deviation with a window of 400,000.

I calculated this rolling std using cudf and Pandas. cudf took around 2.5 minutes, as shown below:
df.rolling(400000).std().to_frame()
where df is a cudf DataFrame

If I convert the cudf df to pandas df and apply the rolling std on pandas and then convert it back to cudf DataFrame, it takes me 2 seconds, as show below:
cudf.DataFrame(df.to_pandas().rolling(400000).std())

When I calculate other statistical indicators (such as moving average), I don't face this problem, i.e., cudf is very fast. I think there is a bug in the rolling.std function in RAPIDS cudf. I think it calculates the whole window every time rather than just replacing the first and last elements of the moving window of 400000 elements, causing this delay whereas pandas does not do it that way. This is my thought but I could be wrong.

**Comment by quasiben** [comment]
Thanks @IMG-5 for the bug report .  Is it possible to generate a reproducer you can share publicly ?  For example, cudf has a random timeseries data generator which you might be able to use

```python
>>> import cudf
>>> cudf.datasets.timeseries().head()
                       id    name         x         y
timestamp
2000-01-01 00:00:00  1014  Ingrid -0.474264 -0.260488
2000-01-01 00:00:01   996  Hannah -0.524467 -0.804983
2000-01-01 00:00:02  1002   Kevin -0.926233  0.211606
2000-01-01 00:00:03  1023     Tim -0.723334  0.860013
2000-01-01 00:00:04   988   Edith  0.801960 -0.940885
```

**Comment by bdice** [comment]
There is a reproducer in related issue #12774.

**Comment by GregoryKimball** [comment]
Closing in favor of #12774
