### ISSUE TITLE
[BUG] `null_order::BEFORE/AFTER` is a misnomer for sorting lists

### ISSUE THREAD

**Issue by divyegala** [rapidsai/cudf#12558]
**Describe the bug**
As noted in https://github.com/rapidsai/cudf/pull/12538 

1. [reverse](https://github.com/rapidsai/cudf/blob/36b07f13480d8f7ba18274cb3a63f06855d848ff/cpp/include/cudf/table/experimental/row_operators.cuh#L558) the output of `ASCENDING` for `DESCENDING`
2. [null_compare](https://github.com/rapidsai/cudf/blob/172696297fac609e3541e9d61a977ad2555224f8/cpp/include/cudf/table/row_operators.cuh#L104) NULLs are a lexicographical insert in comparison orders

We are sorting NULLs lexicographically for lists, and not just pushing them to `BEFORE/AFTER`.

Hence, `DESCENDING` with `null_order::AFTER` ends up being 
```
NULL > [NULL] > [[NULL]] > [[int]] > [[]] > []
```
because `ASCENDING` with `null_order::AFTER` is
```
[] < [[]] < [[int]] < [[NULL]] < [NULL] < NULL
```

**Expected behavior**
Either rename `null_order::BEFORE/AFTER` to `null_order::LESS/GREATER`, or rework the functionality for sorting lists

cc @bdice

**Comment by davidwendt** [comment]
This has already been discussed here: https://github.com/rapidsai/cudf/issues/8269

**Comment by bdice** [comment]
Thanks for the cross-reference. Continuing there and closing this issue.
