### ISSUE TITLE
Replace pointers with std::optional in ORC, Parquet writer options

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#12552]
> Keeping pointers is very risky because of life time issues. I'd like to move away from this approach in the existing code as well.

_Originally posted by @vuule in https://github.com/rapidsai/cudf/pull/12474#discussion_r1070202706_
            

Replace usage of optional pointers with std::optional in ORC, Parquet writer options, and its builder.

https://github.com/rapidsai/cudf/blob/36b07f13480d8f7ba18274cb3a63f06855d848ff/cpp/include/cudf/io/orc.hpp#L811
https://github.com/rapidsai/cudf/blob/36b07f13480d8f7ba18274cb3a63f06855d848ff/cpp/include/cudf/io/parquet.hpp#L474

Use `std::optional` at all places

**Comment by MostlyGenius** [comment]
can you assign this issue to me? @karthikeyann

**Comment by GregoryKimball** [comment]
Hello @MostlyGenius thanks for requesting assignment 😄 - please let us know if you have any questions. 🙏

**Comment by GregoryKimball** [comment]
Hello @MostlyGenius we're thinking about working on this issue. Do you still want the assignment?
