### ISSUE TITLE
[BUG] cudf does not recover properly after out-of-memory in read_csv

### ISSUE THREAD

**Issue by flx42** [rapidsai/cudf#1256]
**Steps/Code to reproduce bug**
```
$ ls -lh /tmp/Performance*
[...] 1.6G Mar 20 16:52 /tmp/Performance_2001Q1.txt
[...] 191G Mar 20 16:15 /tmp/Performance.txt
```
`Performance.txt` is the concatenation of all `Performance` files from the full Mortgage dataset. I'm not expecting the 191GB file to be parsed successfully, but on error I expect all resources to be released:
```
>>> import cudf
>>> cudf.read_csv("/tmp/Performance.txt", delimiter='|')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.6/site-packages/cudf-0.6.0.dev0+1721.g04fac703.dirty-py3.6-linux-x86_64.egg/cudf/io/csv.py", line 337, in read_csv
    libgdf.read_csv(csv_reader)
  File "/conda/envs/rapids/lib/python3.6/site-packages/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: GDF_MEMORYMANAGER_ERROR
>>> cudf.read_csv("/tmp/Performance_2001Q1.txt", delimiter='|')
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: out of memory
Aborted (core dumped)
```
Whereas if I just load the smaller file, it works fine:
```
>>> import cudf
>>> print(cudf.read_csv("/tmp/Performance_2001Q1.txt", delimiter='|'))
    100005072756              02/01/2001                NULL  8.0          Unnamed: 4   2.0  358.0 ...  NULL.3
```

**Environment details (please complete the following information):**
Docker container `rapidsai/rapidsai-nightly@sha256:6ac57168a4cbcf6d3ff7fb3d0aec94a831ae5cac107d1a6cf5a1c166523cc9c3`
with cudf rebuilt manually from commit 04fac703a4e654e20bc02fa524bb03bbb42f5cac
```
# conda list | grep -E 'cudf|rmm'
cudf                      0.6.0.dev0+1721.g04fac703.dirty          pypi_0    pypi
dask-cudf                 0.0.0.dev0               pypi_0    pypi
librmm-cffi               0.6.0                    pypi_0    pypi
```

**Comment by harrism** [comment]
I'm going to hazard a guess that the leak is somewhere in `read_csv`. Assign to @mjsamoht to triage.

**Comment by mjsamoht** [comment]
@flx42 just curious how did you determine that there is a memory leak?

Just by code inspection I can definitely tell that in some error cases we don't free all the memory.  So we will address this.

**Comment by flx42** [comment]
> @flx42 just curious how did you determine that there is a memory leak?

Because it fails in this sequence:
* large file -> OOM error
* small file -> abort

Whereas this works fine:
* small file -> success
