### ISSUE TITLE
[FEA] Absolute value of a series

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1257]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to calculate the absolute value of a series. Currently, I can only do this with a workaround using a Boolean comparison to 0, multiplying separately, concatenating the result back into the dataframe (since we don't have setitem for conditionals). I could also do this with a UDF.

**Describe the solution you'd like**
`gdf['col'].abs()`, similar to [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.abs.html)

**Describe alternatives you've considered**
The alternative is to either use one of the above workaround or convert to Pandas

**Additional context**
Will provide an example shortly.

**Comment by AK-ayush** [comment]
@beckernick  I can take up the implementation of this feature.

**Comment by devavret** [comment]
@AK-ayush It's a part of #1163. Implementation is [here](https://github.com/rapidsai/cudf/pull/1163/commits/9a22ba752424c8e48d8c8e3be62c4574494a0248)

**Comment by devavret** [comment]
@AK-ayush I added the `Series.abs` member function and its pytest from your PR.
