### ISSUE TITLE
[FEA] Support reading FIXED_LEN_BYTE_ARRAY as binary in read_parquet

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#12590]
**Is your feature request related to a problem? Please describe.**
Currently, the libcudf parquet reader can only interpret FIXED_LEN_BYTE_ARRAY physical types as decimal. Spark3.4 includes a ([feature](https://issues.apache.org/jira/browse/SPARK-41096)) to read parquet FIXED_LEN_BYTE_ARRAY as binary type (i.e. list of int8 in libcudf). I would like to support reading FIXED_LEN_BYTE_ARRAY as binary in read_parquet

**Describe the solution you'd like**
Add FIXED_LEN_BYTE_ARRAY to list of types that can be read binary (list of int8) in libcudf read_parquet.

**Describe alternatives you've considered**
n/a

**Additional context**
Spark3.4 includes a ([feature](https://issues.apache.org/jira/browse/SPARK-41096)) to read parquet FIXED_LEN_BYTE_ARRAY as binary type (i.e. list of int8 in libcudf). The Spark-RAPIDS team has also opened an [issue](https://github.com/NVIDIA/spark-rapids/issues/7449), to provide a little more context. It seems like [11160](https://github.com/rapidsai/cudf/pull/11160) added support for reading variable-length BYTE_ARRAY, so adding FIXED_LEN_BYTE_ARRAY may not be too complex.

**Comment by GregoryKimball** [comment]
@revans2 Do you have any sample files that would be useful for developing this feature?

**Comment by revans2** [comment]
Sure. Here is what I have for a simple file. I can generate more if you want/need me to.

[FIXED_BIN_TEST.parquet.zip](https://github.com/rapidsai/cudf/files/11019725/FIXED_BIN_TEST.parquet.zip)

```
scala> spark.read.parquet("/data/tmp/FIXED_BIN_TEST.parquet").show()
+--------+                                                                      
|bin_test|
+--------+
| [41 42]|
| [31 32]|
+--------+
```

Python/pandas

```
>>> pd.read_parquet("/data/tmp/FIXED_BIN_TEST.parquet")
  bin_test
0    b'AB'
1    b'12'
```
