### ISSUE TITLE
[BUG] Series.fillna changes dtype in 0.6

### ISSUE THREAD

**Issue by cmgreen210** [rapidsai/cudf#1261]
After building `branch-0.6` (3a8dc23) locally I'm seeing the following behavior when using `Series.fillna`:
```python
In [1]: import cudf
In [2]: import numpy as np
In [3]: df = cudf.DataFrame()
In [4]: df['a'] = [1, 2, 3]
In [5]: df.a.astype(np.int16).fillna(1).dtype
Out[5]: dtype('int64')
```
When running same code in latest rapids container (`cudf==0.5`) `Out[5]` above is `dtype('int16')` as expected.

**Comment by cmgreen210** [comment]
Also all tests pass locally. This one fails when I added it to `test_dataframe.py`:

```python
def test_series_fillna_dtype():
    df = gd.DataFrame()
    df['a'] = [1, 2, 3]
    df['a'] = df['a'].astype(np.int16)
    df['a'] = df['a'].fillna(1)
    assert df['a'].dtype == np.int16
```

**Comment by kkraus14** [comment]
@cmgreen210 We'll be resolving this, but if you do `.fillna(np.dtype(np.int16).type(YOUR_SCALAR))` it should work.

**Comment by shwina** [comment]
I'll look into this

**Comment by cmgreen210** [comment]
cc @EvenOldridge
