### ISSUE TITLE
[FEA] support DataFrame.duplicated

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12628]
**Is your feature request related to a problem? Please describe.**
working with `import cudf as pd`

**Describe the solution you'd like**
implementation of https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.duplicated.html

![image](https://user-images.githubusercontent.com/112653/215008739-ca5447bf-1b47-40a2-9015-f2bc84236d64.png)

**Comment by galipremsagar** [comment]
@mattf We do have support for `DataFrame.duplicated`, which was very recently added in `23.02`(https://github.com/rapidsai/cudf/pull/12246): https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.dataframe.duplicated

**Comment by mattf** [comment]
@galipremsagar wonderful. i guess i should move to trying nightly.

**Comment by galipremsagar** [comment]
> @galipremsagar wonderful. i guess i should move to trying nightly.

Yup, would highly recommend using nightly builds to check if something is broken or missing.
