### ISSUE TITLE
[BUG] CMake build config should check for versions of dependency libs (nvstrings etc.)

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1262]
At the moment, branch-0.6 requires NVStrings >= 0.3.0, and possibly other non-Python-related requirements; this is spelled out in the two `conda/environments/cudf_dev_cudaXX.X.yml` .

However, the build configuration (with CMake) does not fail due to these requirements not being met. It really should have a check for the required versions of Python and NVStrings, at least (possibly also additional libraries). We shouldn't just rely on Conda being installed and the appropriate environment activated.

**Comment by harrism** [comment]
CMake is for building libcudf, which does not require Python 3.6... cuDF Python API requires it.  I'm told the main reason we moved to Python 3.6 and higher is because most of the ecosystem (e.g. Conda) is dropping Python 3.5.  In any case, I wonder if there's a better place to check the Python version than CMake. @kkraus14 any thoughts?

**Comment by eyalroz** [comment]
@harrism : Well, that's not 100% true, since _our_ `CMakeLists.txt` does use python for the installation. Now, I guess that part doesn't need Python >= 3.6, but we would still need to check for Python. If there's another opportunity to do so, great, but otherwise we could, say, prevent `install_python` from running if Python is under 3.6.

**Comment by kkraus14** [comment]
> @harrism : Well, that's not 100% true, since _our_ `CMakeLists.txt` does use python for the installation. Now, I guess that part doesn't need Python >= 3.6, but we would still need to check for Python. If there's another opportunity to do so, great, but otherwise we could, say, prevent `install_python` from running if Python is under 3.6.

We are working on ripping out CFFI which will move all Python dependency out of CMake.

**Comment by eyalroz** [comment]
@kkraus14 : Ok, so I'm back to making this issue about the C++ dependencies.

**Comment by atlasgurus** [comment]
Is it why the current build fails with the errors below?  Is there a workaround?

> /home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:19:50: error: ‘class NVCategory’ has no member named ‘merge_and_remap’
>            combined_category = combined_category->merge_and_remap(
>                                                   ^~~~~~~~~~~~~~~
> /home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:28:35: error: ‘class NVCategory’ has no member named ‘copy’
>          return combined_category->copy();
>                                    ^~~~
> /home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp: In function ‘gdf_error nvcategory_gather(gdf_column*, NVCategory*)’:
> /home/ubuntu/projects/cudf/cpp/src/string/nvcategory_util.cpp:76:34: error: ‘class NVCategory’ has no member named ‘add_keys_and_remap’
>        nv_category = nv_category->add_keys_and_remap(*strs);

**Comment by eyalroz** [comment]
@atlasgurus : Yes, but what you're is seeing bug #1243 . If you follow the link you'll find how to overcome it.

If this bug were resolved, you would fail at the build configuration stage, and CMake would tell you that your version of NVStrings is too low.

**Comment by davidwendt** [comment]
Can this be closed? 
The `CMakeLists.txt` file have been reworked in #6134

**Comment by kkraus14** [comment]
Yes, this is stale.
