### ISSUE TITLE
[BUG] Variables not reallocating memory when cell is re-run. Explodes memory across all cudf operations. 

### ISSUE THREAD

**Issue by MarkMoTrin** [rapidsai/cudf#12662]
**Describe the bug**
When a variable is re-allocated using cudf, the old memory is not released. 

The notebook shows the memory doubling each time the same csv file is read in. This has downstream effects for other pandas operators that are supposed to overwrite the dataframe. 

This means that memory is doubled unnecessarily during different operations on the GPU. 

**Steps/Code to reproduce bug**
Steps

**Pull relevant container** 
- rapidsai/rapidsai-core-nightly:cuda11.5-runtime-ubuntu20.04-py3.8
- nvcr.io/nvidia/rapidsai/rapidsai:22.12-cuda11.2-runtime-ubuntu20.04-py3.9
- nvcr.io/nvidia/merlin/merlin-pytorch:22.12 (edited) 

**Download dataset** 
- [Link](https://www.kaggle.com/datasets/mkechinov/ecommerce-behavior-data-from-multi-category-store?select=2019-Oct.csv)

**Run container** - note start container in the same folder (or close) to where you data is located. Change path to data in notebook as needed.
- docker run --gpus all --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host --cap-add SYS_NICE -v $PWD/:/rapids/notebooks/host rapidsai/rapidsai-core-nightly:cuda11.5-runtime-ubuntu20.04-py3.8

**Run the notebook**
[cudf-memory-doubling-reproducer-statistics.zip](https://github.com/rapidsai/cudf/files/10549932/cudf-memory-doubling-reproducer-statistics.zip)

See attached notebook for screenshots and code 

**Expected behavior**
When a variable is overwritten the original memory allocated to the variable should be rewritten and deallocated. No doubling of memory should be observed if a variable is being re-written. 

**Environment overview (please complete the following information)**
Using docker containers from dockerhub and NGC. Initially discovered in Merlin-pytorch container. 

 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]

**Environment details**
Run notebook attached

**Additional context**
Notebook shared internally.

**Comment by MarkMoTrin** [comment]
See screenshots of memory doubling each time code is executed

[screenshots-cudf-error.zip](https://github.com/rapidsai/cudf/files/10549950/screenshots-cudf-error.zip)

**Comment by shwina** [comment]
We determined offline that adding a call to `gc.collect()` ensures freeing of device memory. Closing as resolved, but please feel free to reopen if the issue persists.
