### ISSUE TITLE
[DOC] Build (and expand) dask-cudf API docs

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#12679]
Many of the  functions in dask-cudf have docstrings, but anyone browsing the rapids doc site would not know, because currently nothing is built into a sphinx page.

At present the only documentation for dask-cudf is part of the "10 minutes to" notebook.

- [ ] Build sphinx docs
- [ ] Add overview page
- [ ] Add repo README
- [ ] Summary page describing differences from standard dask dataframe
- [ ] cross-linking to other relevant bits and pieces

**Comment by vyasr** [comment]
@wence- @quasiben is there more that we want to do for this issue after https://github.com/rapidsai/cudf/pull/12982 and https://github.com/rapidsai/cudf/pull/12725?

**Comment by wence-** [comment]
I think this is mostly done.
