### ISSUE TITLE
[BUG] Some groupby.apply UDFs compute `mean` incorrectly

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#12686]
**Describe the bug**
Some combinations of `if/else` conditions and `mean` aggregations result in incorrect results with `groupby.apply` UDFs.

**Steps/Code to reproduce bug**
Here is a snippet that reproduces the behavior:
```
import cudf
df = cudf.DataFrame({
    'a':[0,0,0,1,1,1],
    'b':[1,1,1,2,3,4],    
})

def udf(x):
    if x['a'].mean() > 0:
        return x['b'].mean()
    return 0

g = df.groupby('a').apply(udf, engine='jit')
```
which returns:
```
   a      None
0  0  0.000000
1  1  0.666667
```
This is some strange case because changing the conditional or return statements can cause this kind of UDF to return the correct answer. In this case, the computation appears to be dividing the first value by the length rather than the sum by the length.

**Expected behavior**
I expect this result:
```
   a      None
0  0  0.0
1  1  3.0
```

**Environment overview (please complete the following information)**
Docker image from [rapidsai-dev-nightly](https://hub.docker.com/r/rapidsai/rapidsai-dev-nightly/tags?page=1&name=23.02) with id `0022659d9d65`. Built from source commit `3c39be5a9d7d69adaad47121359e0c084b76decf`

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 3c39be5a9d7d69adaad47121359e0c084b76decf (HEAD -> branch-23.02, origin/branch-23.02)
     Author: AJ Schmidt <ajschmidt8@users.noreply.github.com>
     Date:   Wed Feb 1 15:44:09 2023 -0500
     
     Don't upload `libcudf-example` to Anaconda.org (#12671)
     
     When initially created, the GitHub Actions scripts that upload conda packages would upload all packages that were built indiscriminately.
     
     As a result, the `libcudf-example` package has been uploading to Anaconda.org. It was not previously uploaded to Anaconda.org prior to migrating to GitHub Actions.
     
     While this isn't a huge deal, I recently added some functionality ([here](https://github.com/rapidsai/shared-action-workflows/pull/33)) that allows us to specify package names that shouldn't be uploaded to Anaconda.org in our workflows.
     
     This PR adds the `libcudf-example` package to the list of packages that should not be uploaded to Anaconda.org
     
     Authors:
     - AJ Schmidt (https://github.com/ajschmidt8)
     
     Approvers:
     - Ray Douglass (https://github.com/raydouglass)
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
     NAME="Ubuntu"
     VERSION="20.04.5 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.5 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux 988ea4b69385 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Feb  3 00:05:20 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA A100 80G...  On   | 00000000:01:00.0 Off |                    0 |
     | N/A   41C    P0    53W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   1  NVIDIA A100 80G...  On   | 00000000:23:00.0 Off |                    0 |
     | N/A   41C    P0    56W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   2  NVIDIA A100 80G...  On   | 00000000:41:00.0 Off |                    0 |
     | N/A   41C    P0    54W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   3  NVIDIA A100 80G...  On   | 00000000:61:00.0 Off |                    0 |
     | N/A   41C    P0    55W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   4  NVIDIA A100 80G...  On   | 00000000:81:00.0 Off |                    0 |
     | N/A   42C    P0    56W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   5  NVIDIA A100 80G...  On   | 00000000:A1:00.0 Off |                    0 |
     | N/A   45C    P0    59W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   6  NVIDIA A100 80G...  On   | 00000000:C1:00.0 Off |                    0 |
     | N/A   43C    P0    56W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     |   7  NVIDIA A100 80G...  On   | 00000000:E1:00.0 Off |                    0 |
     | N/A   39C    P0    54W / 300W |      0MiB / 81920MiB |      0%      Default |
     |                               |                      |             Disabled |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   43 bits physical, 48 bits virtual
     CPU(s):                          96
     On-line CPU(s) list:             0-95
     Thread(s) per core:              1
     Core(s) per socket:              48
     Socket(s):                       2
     NUMA node(s):                    2
     Vendor ID:                       AuthenticAMD
     CPU family:                      23
     Model:                           49
     Model name:                      AMD EPYC 7642 48-Core Processor
     Stepping:                        0
     Frequency boost:                 enabled
     CPU MHz:                         1498.751
     CPU max MHz:                     2300.0000
     CPU min MHz:                     1500.0000
     BogoMIPS:                        4599.94
     Virtualization:                  AMD-V
     L1d cache:                       3 MiB
     L1i cache:                       3 MiB
     L2 cache:                        48 MiB
     L3 cache:                        512 MiB
     NUMA node0 CPU(s):               0-47
     NUMA node1 CPU(s):               48-95
     Vulnerability Itlb multihit:     Not affected
     Vulnerability L1tf:              Not affected
     Vulnerability Mds:               Not affected
     Vulnerability Meltdown:          Not affected
     Vulnerability Mmio stale data:   Not affected
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling, PBRSB-eIBRS Not affected
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Not affected
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate sme ssbd mba sev ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip rdpid overflow_recov succor smca
     
     ***CMake***
     /opt/conda/envs/rapids/bin/cmake
     cmake version 3.25.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /opt/conda/envs/rapids/bin/g++
     g++ (conda-forge gcc 9.5.0-19) 9.5.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2021 NVIDIA Corporation
     Built on Thu_Nov_18_09:45:30_PST_2021
     Cuda compilation tools, release 11.5, V11.5.119
     Build cuda_11.5.r11.5/compiler.30672275_0
     
     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.9.15
     
     ***Environment Variables***
     PATH                            : /root/.cargo/bin:/opt/conda/envs/rapids/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib:/opt/conda/envs/rapids/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/envs/rapids/bin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       2_gnu    conda-forge
     _sysroot_linux-64_curr_repodata_hack 3                   h5bd9786_13    conda-forge
     aiobotocore               2.4.2              pyhd8ed1ab_0    conda-forge
     aiohttp                   3.8.3            py39hb9d737c_1    conda-forge
     aioitertools              0.11.0             pyhd8ed1ab_0    conda-forge
     aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
     alabaster                 0.7.13             pyhd8ed1ab_0    conda-forge
     anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
     aom                       3.5.0                h27087fc_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
     argon2-cffi-bindings      21.2.0           py39hb9d737c_3    conda-forge
     arrow-cpp                 10.0.1           ha770c72_5_cpu    conda-forge
     asvdb                     0.4.2               g90e8f2c_40    rapidsai
     async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
     atk-1.0                   2.38.0               hd4edc92_1    conda-forge
     attrs                     22.2.0             pyh71513ae_0    conda-forge
     autoconf                  2.69            pl5321hd708f79_11    conda-forge
     automake                  1.16.5          pl5321ha770c72_0    conda-forge
     aws-c-auth                0.6.21               hd93a3ba_3    conda-forge
     aws-c-cal                 0.5.20               hff2c3d7_3    conda-forge
     aws-c-common              0.8.5                h166bdaf_0    conda-forge
     aws-c-compression         0.2.16               hf5f93bc_0    conda-forge
     aws-c-event-stream        0.2.18               h57874a7_0    conda-forge
     aws-c-http                0.7.0                h96ef541_0    conda-forge
     aws-c-io                  0.13.12              h57ca295_1    conda-forge
     aws-c-mqtt                0.7.13              h0b5698f_12    conda-forge
     aws-c-s3                  0.2.3                h82cbbf9_0    conda-forge
     aws-c-sdkutils            0.1.7                hf5f93bc_0    conda-forge
     aws-checksums             0.1.14               h6027aba_0    conda-forge
     aws-crt-cpp               0.18.16             hf80f573_10    conda-forge
     aws-sam-translator        1.58.1             pyhd8ed1ab_0    conda-forge
     aws-sdk-cpp               1.10.57              ha834a50_1    conda-forge
     aws-xray-sdk              2.11.0             pyhd8ed1ab_0    conda-forge
     babel                     2.11.0             pyhd8ed1ab_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                pyhd8ed1ab_3    conda-forge
     backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
     backports.zoneinfo        0.2.1            py39hf3d152e_7    conda-forge
     bcrypt                    3.2.2            py39hb9d737c_1    conda-forge
     beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
     benchmark                 1.5.1                he1b5a44_2    conda-forge
     binutils                  2.39                 hdd6e379_1    conda-forge
     binutils_impl_linux-64    2.39                 he00db2b_1    conda-forge
     binutils_linux-64         2.39                h5fc0e48_11    conda-forge
     black                     22.3.0             pyhd8ed1ab_0    conda-forge
     blas                      1.1                    openblas    conda-forge
     bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
     blinker                   1.5                pyhd8ed1ab_0    conda-forge
     blosc                     1.21.3               hafa529b_0    conda-forge
     bokeh                     2.4.3            py39hf3d152e_0    conda-forge
     boost                     1.74.0           py39h5472131_5    conda-forge
     boost-cpp                 1.74.0               h75c5d50_8    conda-forge
     boto3                     1.24.59            pyhd8ed1ab_0    conda-forge
     botocore                  1.27.59            pyhd8ed1ab_0    conda-forge
     branca                    0.6.0              pyhd8ed1ab_0    conda-forge
     breathe                   4.34.0             pyhd8ed1ab_0    conda-forge
     brotli                    1.0.9                h166bdaf_8    conda-forge
     brotli-bin                1.0.9                h166bdaf_8    conda-forge
     brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
     brunsli                   0.1                  h9c3ff4c_0    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.18.1               h7f98852_0    conda-forge
     c-blosc2                  2.6.1                hf91038e_0    conda-forge
     c-compiler                1.3.0                h7f98852_0    conda-forge
     ca-certificates           2022.12.7            ha878542_0    conda-forge
     cached-property           1.5.2                hd8ed1ab_1    conda-forge
     cached_property           1.5.2              pyha770c72_1    conda-forge
     cachetools                5.3.0              pyhd8ed1ab_0    conda-forge
     cairo                     1.16.0            ha61ee94_1014    conda-forge
     certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
     cffi                      1.15.1           py39he91dace_3    conda-forge
     cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
     cfitsio                   4.1.0                hd9d235c_0    conda-forge
     cfn-lint                  0.23.2                     py_0    conda-forge
     chardet                   5.1.0            py39hf3d152e_0    conda-forge
     charls                    2.3.4                h9c3ff4c_0    conda-forge
     charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
     clang                     11.1.0               ha770c72_1    conda-forge
     clang-11                  11.1.0          default_ha53f305_1    conda-forge
     clang-tools               11.1.0          default_ha53f305_1    conda-forge
     clangxx                   11.1.0          default_ha53f305_1    conda-forge
     click                     8.1.3            py39hf3d152e_1    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
     cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
     cmake                     3.25.2               h077f3f9_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     cmakelang                 0.6.13             pyhd8ed1ab_0    conda-forge
     cmarkgfm                  0.8.0            py39hb9d737c_2    conda-forge
     colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
     colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
     comm                      0.1.2              pyhd8ed1ab_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     conda                     4.12.0           py39hf3d152e_0    conda-forge
     conda-build               3.22.0           py39hf3d152e_3    conda-forge
     conda-package-handling    2.0.2              pyh38be061_0    conda-forge
     conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
     conda-verify              3.1.1           py39hf3d152e_1006    conda-forge
     contourpy                 1.0.7            py39h4b4f3f3_0    conda-forge
     coverage                  7.1.0            py39h72bdee0_0    conda-forge
     cryptography              39.0.0           py39h079d5ae_0    conda-forge
     cubinlinker               0.2.0            py39h11215e4_1    rapidsai-nightly
     cuda-profiler-api         11.8.86                       0    nvidia
     cuda-python               11.8.1           py39h2405124_2    conda-forge
     cudatoolkit               11.5.1              h59c8dcf_11    conda-forge
     cudf                      23.2.0a0+g78cc98a          pypi_0    pypi
     cudf-kafka                23.2.0a0+g78cc98a          pypi_0    pypi
     cugraph                   23.2.0a0+g9754157          pypi_0    pypi
     cugraph-dgl               23.2.0a0+g9754157          pypi_0    pypi
     cugraph-pyg               23.2.0a0+g9754157          pypi_0    pypi
     cugraph-service-client    23.2.0a0+g9754157          pypi_0    pypi
     cugraph-service-server    23.2.0a0+g9754157          pypi_0    pypi
     cuml                      23.2.0a0+g56d767c          pypi_0    pypi
     cupy                      11.5.0           py39hc3c280e_0    conda-forge
     curl                      7.87.0               hdc1c0ab_0    conda-forge
     cusignal                  23.2.0a0+g883a037          pypi_0    pypi
     cuspatial                 23.2.0a0+gf967893          pypi_0    pypi
     cuxfilter                 23.2.0a0+g3ee4186          pypi_0    pypi
     cxx-compiler              1.3.0                h4bd325d_0    conda-forge
     cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
     cyrus-sasl                2.1.27               h9033bb2_6    conda-forge
     cython                    0.29.33          py39h227be39_0    conda-forge
     cytoolz                   0.12.0           py39hb9d737c_1    conda-forge
     dask                      2022.11.1a221118  py_g7887430c_9    dask/label/dev
     dask-core                 2022.11.1a221118 py_g5a52c83ff_5    dask/label/dev
     dask-cudf                 23.2.0a0+g78cc98a          pypi_0    pypi
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         6.0.0              pyhd8ed1ab_0    conda-forge
     dask-ml                   2022.5.27          pyhd8ed1ab_0    conda-forge
     dask-sql                  2022.12.0                pypi_0    pypi
     dataclasses               0.8                pyhc8e2a94_3    conda-forge
     datashader                0.13.1a                    py_0    rapidsai
     datashape                 0.5.4                      py_1    conda-forge
     dav1d                     1.0.0                h166bdaf_1    conda-forge
     dbus                      1.13.6               h5008d03_3    conda-forge
     debugpy                   1.6.6            py39h227be39_0    conda-forge
     decopatch                 1.4.10             pyhd8ed1ab_0    conda-forge
     decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
     distributed               2022.11.1a221118  py_g7887430c_9    dask/label/dev
     distro                    1.6.0              pyhd8ed1ab_0    conda-forge
     dlpack                    0.5                  h9c3ff4c_0    conda-forge
     docker-py                 6.0.0              pyhd8ed1ab_0    conda-forge
     docutils                  0.17.1           py39hf3d152e_3    conda-forge
     double-conversion         3.1.5                h9c3ff4c_2    conda-forge
     doxygen                   1.8.20               had0d8f1_0    conda-forge
     ecdsa                     0.18.0             pyhd8ed1ab_1    conda-forge
     entrypoints               0.4                pyhd8ed1ab_0    conda-forge
     exceptiongroup            1.1.0              pyhd8ed1ab_0    conda-forge
     execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
     expat                     2.5.0                h27087fc_0    conda-forge
     faiss-proc                1.0.0                      cuda    rapidsai
     fastapi                   0.89.1             pyhd8ed1ab_0    conda-forge
     fastavro                  1.7.1            py39h72bdee0_0    conda-forge
     fastrlock                 0.8              py39h5a03fae_3    conda-forge
     feather-format            0.4.1              pyh9f0ad1d_0    conda-forge
     filelock                  3.9.0              pyhd8ed1ab_0    conda-forge
     filterpy                  1.4.5                      py_1    conda-forge
     fiona                     1.8.22           py39h80939cc_0    conda-forge
     flake8                    3.8.4                      py_0    conda-forge  
     ucx-py                    0.30.00a230131  py39_ga21f62a_17    rapidsai-nightly
     zstandard                 0.19.0           py39h29414ee_1    conda-forge
     zstd                      1.5.2                h3eb15da_6    conda-forge
     
</pre></details>

**Additional context**
These UDFs don't have the same issue:
```
def udf(x):
    if x['a'].mean() > 0:
        return x['b'].mean()
    return x['b'].mean()
```

```
def udf(x):
    if x['a'].mean() == 0:
        return x['b'].mean()
    return 0
```

**Comment by brandon-b-miller** [comment]
After some debugging I think I've some idea of what's going on here. Fix to follow hopefully soon.
