### ISSUE TITLE
[BUG] Write JSON misses a comma every 8 records with `lines=False`

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#12687]
**Describe the bug**
When using the new JSON writer in cuDF-python with `lines=False`, the output skips the necessary comma periodically. This appears to happen every 8 records from my testing.

**Steps/Code to reproduce bug**
Here is a repro for the issue:
```
df = cudf.DataFrame({'a':range(18)})
df.to_json('j.json', engine='cudf', lines=False)
```
Here is the file:
`[{"a":0},{"a":1},{"a":2},{"a":3},{"a":4},{"a":5},{"a":6},{"a":7}{"a":8},{"a":9},{"a":10},{"a":11},{"a":12},{"a":13},{"a":14},{"a":15}{"a":16},{"a":17}]`
Note the missing comma between `{"a":7}` and `{"a":8}`.

and here is the error:
```
df = cudf.read_json('j.json', engine='cudf', lines=False)
RuntimeError: CUDF failure at:/nfs/repo/cudf-23.02/cpp/src/io/json/json_tree.cu:264: JSON Parser encountered an invalid format at location 64
```

**Expected behavior**
I expect to write valid JSON, where each record is separated by a comma.

**Environment overview (please complete the following information)**
Docker image from [rapidsai-dev-nightly](https://hub.docker.com/r/rapidsai/rapidsai-dev-nightly/tags?page=1&name=23.02) with id `0022659d9d65`. Built from source commit `3c39be5a9d7d69adaad47121359e0c084b76decf`

**Environment details**
skipped

**Additional context**
I have not seen a similar issue with `lines=True`

**Comment by GregoryKimball** [comment]
Maybe this is related to a `row_per_chunk` option set to 8 for some reason.

**Comment by karthikeyann** [comment]
The bug is in the avoiding trailing comma for records format (lines=False).
Though cudf json reader reads it right, trailing commas are not supported by pandas.

Created a fix https://github.com/rapidsai/cudf/pull/12688
