### ISSUE TITLE
[FEA] libcuDF covariance for Series and Groupby

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1268]
**Is your feature request related to a problem? Please describe.**
As a cuDF user, I want to calculate the covariance matrix of my dataset. While I am interested in the covariance between two series, for many downstream uses I often actually need the entire covariance matrix rather than just the covariance of two columns. Implementing covariance in libcudf at the gdf_column level will let us create the dataframe level API in the python bindings.

The pandas API docs are [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.cov.html).

**Describe the solution you'd like**
I'd like to be able to call `df.cov()` and get a pairwise covariance matrix of my dataset. To do this, we'll need a method that can compute the covariance of two gdf columns.

**Describe alternatives you've considered**
The alternative is to manually calculate the covariance, most easily in a double for loop.

**Additional context**

**Comment by beckernick** [comment]
#2719 provided a temporary, Python-based implementation for this. Updating this issue to refer to a libcuDF implementation.

**Comment by vyasr** [comment]
This was closed in #9889
