### ISSUE TITLE
[FEA] Series level cumulative sum

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1269]
**Is your feature request related to a problem? Please describe.**
As a user, I want to calculate the cumulative sum of a series. I'd like it to behave like the pandas `cumsum` method, which can be found [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.cumsum.html#pandas.Series.cumsum).

**Describe the solution you'd like**
I'd like to be able to call `series.cumsum()` and return results consistent with what I would get from calling this on a pandas series.

**Describe alternatives you've considered**
The alternative is to iterate through each cell in the column, keep a running tally of the sum of values seen so far, and then store that value in a new array.

**Additional context**
I would think that column-level cumulative sums are more common than row-level cumulative sums, which would make supporting the row-level pattern (axis=1) less important.

**Comment by jrhemstad** [comment]
Necessary C++ functionality added in https://github.com/rapidsai/cudf/pull/1005
