### ISSUE TITLE
[BUG] "Fatal Python error init_import_size" when trying to build cudf from source

### ISSUE THREAD

**Issue by kunshouout** [rapidsai/cudf#12703]
Following the instructions, I built and installed libcudf successfully. When try to build cudf with the following command:

`python setup.py build_ext --inplace`

I got the errors:
pc:~/setup/cudf/python/cudf$ /usr/bin/python setup.py build_ext --inplace
/usr/lib/python3/dist-packages/setuptools/dist.py:473: UserWarning: Normalizing '23.02.00a+307.g78cc98a288.dirty' to '23.2.0a0+307.g78cc98a288.dirty'
  warnings.warn(
[3/15] Generating CXX source cudf/_lib/utils.cxx
FAILED: cudf/_lib/utils.cxx /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib/utils.cxx 
cd /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib && /home/ken/.local/bin/cython --cplus --include-dir /usr/include/python3.8 -3 --directive binding=True,embedsignature=True,always_allow_keywords=True /home/ken/setup/cudf/python/cudf/cudf/_lib/utils.pyx --output-file /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib/utils.cxx
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Error processing line 1 of /home/ken/.local/lib/python3.8/site-packages/matplotlib-3.3.0-py3.8-nspkg.pth:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 175, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "types.pyx", line 3, in init cudf._lib.types
  File "/usr/lib/python3.8/enum.py", line 2, in <module>
    from types import MappingProxyType, DynamicClassAttribute
ImportError: cannot import name 'MappingProxyType' from partially initialized module 'types' (most likely due to a circular import) (/home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib/types.cpython-38-x86_64-linux-gnu.so)

It seems cudf/python/cudf/cudf/_lib/types.pxd conficts with the default python types package. How do I fix this? Please Help!

**Environment overview**
python 3.10.8
ubuntu 20.04
cudf 23.02.00a+307.g78cc98a288.dirty
cuda 12.0.0

**Comment by kunshouout** [comment]
Finally figured it out. The real issue is circular import of the modules where cudf and python-builtin have the same name(eg datetime). Note 'cd /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib' before cython is applied to compile. It's where the cudf pyx files lie, and this conflicts the python builtin module. Don't know why this happens. I modified the build.ninja manually,
'cd /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/cudf/_lib' 
->
'cd /home/ken/setup/cudf/python/cudf/_skbuild/linux-x86_64-3.8/cmake-build/'
ie. don't go to the _lib directory.

and the errors disapeared

**Comment by vyasr** [comment]
That is an odd issue to run into with cythonizing specifically. I have never run into it before. However, your explanation certainly makes sense. It looks like you're using Python 3.8. What version of Cython are you using? I cannot reproduce your issue locally, but the build.ninja file that scikit-build generated for me has the same types of commands as yours so the Cython executable behaving differently would be the next culprit.

**Comment by GregoryKimball** [comment]
Thank you @kunshouout for sharing this issue and your solution. Please feel free to reach out if you encounter any other issues.
