### ISSUE TITLE
[FEA][BACKLOG] Difference functionality

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1271]
**Is your feature request related to a problem? Please describe.**
As a cuDF user, I want to calculate the difference between rows in a column (most commonly with the previous row). The equivalent in the pandas API docs is [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.diff.html#pandas.Series.diff) for Series and [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.diff.html) for Groupbys.

**Describe the solution you'd like**
I'd like to be able to call `.diff(n)` on:
- Series (Python/Numba version implemented in #1456)
- DataFrames
- Groupbys

And return the appropriate object with the difference between each value and the value `n` rows "above" it.

**Describe alternatives you've considered**
I could do this by going to the CPU or with a kernel by iterating through the column and populating a new device array of the same size.

**Comment by beckernick** [comment]
Stopgap Python layer functionality for this feature has been merged with #1456. Explicitly backlogging this and defer to @harrism prioritization on the libcudf side.

**Comment by harrism** [comment]
@beckernick how is this different from a binary subtract operation ?

**Comment by beckernick** [comment]
Closing the loop on this issue, this functionality can be expressed as a call to shift followed by a binary subtract op with the operands being the original column and the shifted column.

Column and Groupby shift have now been implemented in libcudf and the only remaining piece in Python is `DataFrame.diff`, which is specifically requested in https://github.com/rapidsai/cudf/issues/9604 and has a PR in review at https://github.com/rapidsai/cudf/pull/9817

As a result, I believe this can be closed alongside #9604 when #9817 lands, and I'll update the PR description to reflect it.
