### ISSUE TITLE
[FEA] Series level cumulative max

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1273]
**Is your feature request related to a problem? Please describe.**
As a cuDF user, I want to calculate the cumulative max over a column. The equivalent in the pandas API docs is [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.cummax.html#pandas.Series.cummax).

**Describe the solution you'd like**
I'd like to call `series.cummax()` and return a series of the same size in which each value is the maximum value seen so far in the series.

**Describe alternatives you've considered**
I could do this manually by iterating over the column, storing the running max, and populating another array with the result.

**Additional context**

**Comment by jrhemstad** [comment]
Note that on the C++ side, this will be possible with https://github.com/rapidsai/cudf/pull/1005

**Comment by beckernick** [comment]
Closed by #1441
