### ISSUE TITLE
[FEA] Ability to track `CopyOnWriteBuffer` by sharing references

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#12734]
**Is your feature request related to a problem? Please describe.**
With `CopyOnWriteBuffer` we should explore if we can just pass on the `CopyOnWriteBuffer` reference to another column and still create a weak reference.
for example:
```
y = CopyOnWriteBuffer(..)
x = y # Should establish a weak reference or something of that sort
x2 = y.copy(deep=True)  # currently only this achieves establishing a weak-reference.
```

**Comment by vyasr** [comment]
@galipremsagar @madsbk do you think that the unification of COW and spilling changed how this should work?

**Comment by madsbk** [comment]
I don't it is possible to overload assignment of a variable in Python. That is, we cannot do anything here:
```python
x = y # Should establish a weak reference or something of that sort
```

Or maybe I am misunderstanding the idea?

**Comment by vyasr** [comment]
You're right that we can't override the behavior of the assignment operator, I guess I was wondering exactly what @galipremsagar was hoping to accomplish here and if there's another way to do it and if anything has changed. If it really is just about the assignment operator then yeah we just have to close this.

**Comment by galipremsagar** [comment]
Yes, this is about trying to keep track of references somewhere whenever there is an assignment operator. Unfortunately, I didn't find a solution to this problem. So, I will close this issue for now.
