### ISSUE TITLE
[QST] Got an error when installing cudf from pip

### ISSUE THREAD

**Issue by naruwy** [rapidsai/cudf#12762]
When I ran this code, I got the following error This worked until the day before yesterday, but it stopped working yesterday. The environment is google colab. What should I do?

```
!pip install cudf-cu11 --extra-index-url=https://pypi.ngc.nvidia.com/
!rm -rf /usr/local/lib/python3.8/dist-packages/cupy*
!pip install cupy-cuda11x
import cudf
```

```
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://pypi.ngc.nvidia.com/
Collecting cudf-cu11
  Using cached cudf_cu11-23.2.0.tar.gz (6.5 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting cupy-cuda11x
  Using cached cupy_cuda11x-11.5.0-cp38-cp38-manylinux1_x86_64.whl (93.7 MB)
Requirement already satisfied: numpy<1.26,>=1.20 in /usr/local/lib/python3.8/dist-packages (from cupy-cuda11x) (1.21.6)
Requirement already satisfied: fastrlock>=0.5 in /usr/local/lib/python3.8/dist-packages (from cupy-cuda11x) (0.8.1)
Installing collected packages: cupy-cuda11x
Successfully installed cupy-cuda11x-11.5.0
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-7-96106a163e3c>](https://localhost:8080/#) in <module>
      3 get_ipython().system('rm -rf /usr/local/lib/python3.8/dist-packages/cupy*')
      4 get_ipython().system('pip install cupy-cuda11x')
----> 5 import cudf, cuml

ModuleNotFoundError: No module named 'cudf'
```

**Comment by beckernick** [comment]
Thanks for the report. We'll investigate what's going on with our 23.02 packages.

In the meantime, you should be able to use the 22.12 packages. In a fresh notebook (with a GPU runtime), try running `!pip install cudf-cu11==22.12 rmm-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/`.

**Comment by naruwy** [comment]
Thank you for your reply and investigation

**Comment by beckernick** [comment]
We've switched to a new index for 23.02 but haven't finished updating our documentation.

You can install cuDF 23.02 on Colab with `!pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com/` (rather than `pypi.ngc.nvidia.com`.

Closing as answered, but please feel free to reopen if you have any issues.

**Comment by sajjadGG** [comment]
I tested the proposed approach to install `!pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com/` and it still fails with the same error

**Comment by sparta0000** [comment]
!pip install cudf-cu11 --extra-index-url=https://pypi.nvidia.com/

ERROR:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/, https://pypi.nvidia.com/
Collecting cudf-cu11
  Using cached cudf_cu11-23.2.0.tar.gz (6.5 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by gattaloukik123** [comment]
I was struggling with getting the cudf packages to work with pip and I think I finally figured a version that works and a way to install cuml, cudf, cugraph. Also I tried this on google colab notebook and it worked well for me. 

`pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 cudf-cu11==22.10 rmm-cu11==22.10 dask-cudf-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cuml-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cudf-cu11==22.10 cugraph-cu11==22.10 --extra-index-url=https://pypi.nvidia.com

pip uninstall cupy-cuda115 -y
pip uninstall cupy-cuda11x -y
pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64
pip install nvidia-ml-py3`

**Comment by sparta0000** [comment]
> I was struggling with getting the cudf packages to work with pip and I think I finally figured a version that works and a way to install cuml, cudf, cugraph. Also I tried this on google colab notebook and it worked well for me.
> 
> ```
> pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 cudf-cu11==22.10 rmm-cu11==22.10 dask-cudf-cu11==22.10 --extra-index-url=https://pypi.nvidia.com
> 
> pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cuml-cu11==22.10 --extra-index-url=https://pypi.nvidia.com
> 
> pip install dask==2022.9.2 distributed==2022.9.2 ucx-py-cu11==0.29.0 raft-dask-cu11==22.10 pylibcugraph-cu11==22.10 pylibraft-cu11==22.10 cudf-cu11==22.10 cugraph-cu11==22.10 --extra-index-url=https://pypi.nvidia.com
> 
> pip uninstall cupy-cuda115 -y
> pip uninstall cupy-cuda11x -y
> pip install cupy-cuda11x -f https://pip.cupy.dev/aarch64
> pip install nvidia-ml-py3
> ```

Thank you , itried something similar, one liner  and it worked 

`!pip install cudf-cu11==22.12 rmm-cu11==22.12 dask-cudf-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/ `

**Comment by pROGRAMMERDATASCIENCE22** [comment]
ERROR: Ignored the following yanked versions: 0.0.1
ERROR: Could not find a version that satisfies the requirement cudf-cu11==22.12 (from versions: 23.2.0, 23.4.0, 23.4.0.1681363056, 23.4.1, 23.6.0, 23.6.1, 23.8.0, 23.10.0, 23.10.1, 23.10.2, 23.12.0, 23.12.1, 24.2.0, 24.2.1, 24.2.2, 24.4.0, 24.4.1, 24.6.0, 24.6.1, 24.8.1, 24.8.2, 24.8.3, 24.10.1)
ERROR: No matching distribution found for cudf-cu11==22.12

**Comment by vyasr** [comment]
You are trying to install a version for which our pip packages were still experimental and are apparently no longer available on our indexes. Please try specifying a newer version (ideally our latest, 24.08 or 24.10).

**Comment by loretoparisi** [comment]
@sparta0000 
> pip install cudf-cu11==22.12 rmm-cu11==22.12 dask-cudf-cu11==22.12 --extra-index-url=https://pypi.ngc.nvidia.com/

is causing an error on Python3.10


```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com/
Collecting cudf-cu11==22.12
  Using cached cudf_cu11-22.12.0.tar.gz (973 bytes)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl against tag cp38-cp38-manylinux2014_x86_64
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl against tag cp38-cp38-manylinux_2_17_x86_64
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp38-cp38-manylinux_2_31_aarch64.whl against tag cp38-cp38-manylinux_2_31_aarch64
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl against tag cp39-cp39-manylinux_2_17_x86_64
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl against tag cp39-cp39-manylinux2014_x86_64
      INFO:wheel-stub:Testing wheel cudf_cu11-22.12.0-cp39-cp39-manylinux_2_31_aarch64.whl against tag cp39-cp39-manylinux_2_31_aarch64
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/wheel.py", line 235, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/wheel.py", line 173, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/wheel.py", line 235, in download_wheel
          return download_manual(wheel_directory, distribution, version, config)
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/wheel.py", line 173, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cudf-cu11 22.12.0
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/buildapi.py", line 29, in build_wheel
          return download_wheel(pathlib.Path(wheel_directory), config_settings)
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/wheel.py", line 237, in download_wheel
          report_install_failure(distribution, version, config, exception_context)
        File "/tmp/pip-build-env-yhrd_wwc/overlay/local/lib/python3.10/dist-packages/wheel_stub/error.py", line 67, in report_install_failure
          raise InstallFailedError(
      wheel_stub.error.InstallFailedError:
      *******************************************************************************
      
      The installation of cudf-cu11 for version 22.12.0 failed.
      
      This is a special placeholder package which downloads a real wheel package
      from https://pypi.nvidia.com/. If https://pypi.nvidia.com/ is not reachable, we
      cannot download the real wheel file to install.
      
      You might try installing this package via
      ```
      $ pip install --extra-index-url https://pypi.nvidia.com/ cudf-cu11
      ```
      
      Here is some debug information about your platform to include in any bug
      report:
      
      Python Version: CPython 3.10.12
      Operating System: Linux 5.10.228-219.884.amzn2.x86_64
      CPU Architecture: x86_64
      Driver Version: 550.127
      CUDA Version: 12.4
      
      *******************************************************************************
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
````

**Comment by vyasr** [comment]
Could you please try installing a newer version of our packages? 22.12 is almost 2 years old now and a lot has changed, including our support matrix.

**Comment by loretoparisi** [comment]
> Could you please try installing a newer version of our packages? 22.12 is almost 2 years old now and a lot has changed, including our support matrix. If you still run into problems, please open a new issue.

@vyasr thanks which version shall I use with CUDA 12 I have tried

```
pip install cudf-cu12==24.12 rmm-cu12==24.12 dask-cudf-cu12==24.12 --extra-index-url=https://pypi.ngc.nvidia.com/ 
```

but did not find it.
I'm running
```
NVIDIA-SMI 550.127.08             Driver Version: 550.127.08     CUDA Version: 12.4  
```

Thanks a lot!

**Comment by loretoparisi** [comment]
@vyasr I finally made it working using

```
pip install dask-cudf-cu12
pip install rmm-cu12
```

but I have some execution error on the dask-cudf side, opened an [issue](https://github.com/rapidsai/dask-cuda/issues/1415) for that

Thanks!

**Comment by beckernick** [comment]
Thanks for updating this issue.

Could you share what happens if you use the installation command on rapids.ai in a totally fresh environment?

```
pip install \
  --extra-index-url=https://pypi.nvidia.com \
  cudf-cu12==24.10.* \
  dask-cudf-cu12==24.10.*
```
