### ISSUE TITLE
[QST]When would cuda12 be supported by cudf?

### ISSUE THREAD

**Issue by kunshouout** [rapidsai/cudf#12763]
I tried to build cudf 22.12 from source with cuda12, ubuntu 20.04, python 3.8, but with no luck. I get "segment fault" error. Is there a plan to  support cuda12?

**Comment by bdice** [comment]
@kunshouout Currently cuDF is supported on CUDA 12 through the Deep Learning Frameworks images. You can use DLFW containers (e.g. [PyTorch 23.01](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-01.html#rel-23-01)) that have CUDA 12 and RAPIDS 22.12.

RAPIDS will be shipping CUDA 12 conda packages and Docker containers in the future, once conda-forge has CUDA 12 packages. We estimate that this will come in the RAPIDS 23.04 release if possible, but may slip to 23.06 depending on how long it takes conda-forge to get CUDA 12 packages. See this issue for tracking conda-forge CUDA 12 support: https://github.com/conda-forge/staged-recipes/issues/21382

As for building from source - I believe the core support for CUDA 12 already exists in the public development branch of RAPIDS projects (rmm, cuDF, ...) and the package should build properly, but there are Python package dependencies like CuPy and Numba which may not yet have official CUDA 12 support except in DLFW containers that have been patched.

**Comment by vyasr** [comment]
RAPIDS added support for CUDA 12 in pip wheels in 24.06 and in conda packages in 24.08.
