### ISSUE TITLE
[BUG] `cudf::strings::replace_re` can be 20X slower than a single thread on the CPU for some cases

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12778]
Similar to https://github.com/rapidsai/cudf/issues/12694, we discovered a similar issue with `cudf::strings::replace_re` for some input data.

In particular, using the same data file as in https://github.com/rapidsai/cudf/issues/12694, Spark CPU (`regexp_replace`) can complete its job in around 600ms while the GPU version (which calls to `cudf::strings::replace_re`) on the same input takes around 11 seconds.

**Comment by ttnghia** [comment]
Example of reproducible code:
```
    auto const pattern    = std::string("\\[\\{|\\}\\]");
    auto const regex_prog = cudf::strings::regex_program::create(
      pattern, cudf::strings::regex_flags::DEFAULT, cudf::strings::capture_groups::NON_CAPTURE);
    auto const replace = cudf::string_scalar("");
    cudf::strings::replace_re(strs_input, *regex_prog, replace);
```

**Comment by davidwendt** [comment]
Yes, long strings for regex are a known issue. This is likely not going to be fixed.

**Comment by GregoryKimball** [comment]
I'll close this in favor of #13048, where we can track progress on long string performance.
