### ISSUE TITLE
[BUG] can't merge dask-cudf dataframes when index is non-numeric?

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#12773]
**Describe the bug**

Consider
```python
import cudf
import dask_cudf as dd

df1 = cudf.DataFrame({"a": ["a", "b"], "b": [1, 2]})
df2 = cudf.DataFrame({"a": ["a", "c"], "b": [2, 3]})

ddf1 = dd.from_cudf(df1, npartitions=2).set_index("a")
ddf2 = dd.from_cudf(df2, npartitions=2).set_index("a")

union = ddf1.merge(ddf2, left_index=True, right_index=True, how="left").compute()
```

This produces

```pytb
File ~/cudf/python/cudf/cudf/core/column/string.py:5475, in StringColumn.as_numerical_column(self, dtype, **kwargs)
   5473 elif out_dtype.kind == "f":
   5474     if not libstrings.is_float(string_col).all():
-> 5475         raise ValueError(
   5476             "Could not convert strings to float "
   5477             "type due to presence of non-floating values."
   5478         )
   5480 result_col = _str_to_numeric_typecast_functions[out_dtype](string_col)
   5481 return result_col

ValueError: Could not convert strings to float type due to presence of
non-floating values.
```

This should work. I think something strange is going on, effectively
the error occurs because dask is trying to do

```python
df3 = df1.set_index("a")

df4 = df3.assign(foo=cudf.Series([1, 2]))
```

And this fails because the assignment column doesn't have the same
index as the dataframe.

Whose bug is this? Everything "works" with pandas-backed dataframes.

**Comment by daxiongshu** [comment]
I'm curious about this bug. Thank you for raising the issue.

**Comment by wence-** [comment]
Looks like at least one problem is that `.set_index()` with a column of `str` dtype, divisions are not computed.

**Comment by rjzamora** [comment]
It isn't too difficult to get `set_index` to update the divisions correctly in `dask_cudf`.  However, I'm still running into a separate issue where `cudf` doesn't support `loc` indexing of a range where one end of the range is not physicaly present in the index. For example:

```python
import pandas as pd, cudf

pdf = pd.DataFrame({"a": ["a", "b", "c"], "b": range(3)}).set_index("a")
gdf = cudf.from_pandas(pdf)

pdf.loc["a":"d"]  # Works fine
gdf.loc["a":"d"]  # Fails
```

**Comment by rjzamora** [comment]
@wence- do you happen to know off-hand if [this issue](https://github.com/rapidsai/cudf/issues/12773#issuecomment-1431964533) is already covered by something in https://github.com/rapidsai/cudf/issues/12793? If not, I can submit a new issue and link it.

**Comment by wence-** [comment]
I think it is not, please add to the list!

**Comment by wence-** [comment]
> However, I'm still running into a separate issue where `cudf` doesn't support `loc` indexing of a range where one end of the range is not physicaly present in the index.

This is #12833.

**Comment by wence-** [comment]
> It isn't too difficult to get `set_index` to update the divisions correctly in `dask_cudf`. However, I'm still running into a separate issue where `cudf` doesn't support `loc` indexing of a range where one end of the range is not physicaly present in the index. For example:
> 
> ```python
> import pandas as pd, cudf
> 
> pdf = pd.DataFrame({"a": ["a", "b", "c"], "b": range(3)}).set_index("a")
> gdf = cudf.from_pandas(pdf)
> 
> pdf.loc["a":"d"]  # Works fine
> gdf.loc["a":"d"]  # Fails
> ```

This aspect should now be fixed. Can we revisit the original issue?

**Comment by wence-** [comment]
This looks like it is now fixed, we should probably add a test...
