### ISSUE TITLE
[FEA] Support group by data type larger than int64

### ISSUE THREAD

**Issue by JinHai-CN** [rapidsai/cudf#1277]
Currently, I found cudf group by data type only support which width is not larger than 64bit. Can cudf add support to float128/int128 group by feature?

**Comment by harrism** [comment]
Since these are not built-in types in C++ and not natively supported on GPUs, this would be a major undertaking. Moreover, even though GCC provides an `__int128` type, it is not supported on machines with `long long` size less than 128 bits wide. AFAIK all platforms we support have 64-bit `long long` size...

**Comment by jrhemstad** [comment]
This isn't currently even possible on a GPU as it would require atomic support larger than 8B.

**Comment by harrism** [comment]
Technically wouldn't it be possible to do sort-based groupby without atomics larger than 8B?

**Comment by JinHai-CN** [comment]
Is it possible to use CAS op to construct a mutex to synchronize the agg op between threads?

**Comment by harrism** [comment]
Yes, I think that is possible as well. I believe that is exactly what is happening when one uses CAS to implement, for example, atomicAdd for a datatype that isn't natively supported -- shouldn't matter if the data type is smaller or larger. 

Priority is a different question.

**Comment by jrhemstad** [comment]
> Technically wouldn't it be possible to do sort-based groupby without atomics larger than 8B?

Yes, that's true. 

> I believe that is exactly what is happening when one uses CAS to implement, for example, atomicAdd for a datatype that isn't natively supported -- shouldn't matter if the data type is smaller or larger.

Not quite. @JinHai-CN is suggesting creating an additional mutex object for each entry in the hash table. You'd lock the mutex when updating the >8B value in the payload. 

That is very different from how we emulate `atomicAdd` for types like `int8_t`. We perform the operation as an `int8_t` on the old value, and then update the entire 4B word that contains the 1B `int8_t` with a 4B `atomicCAS`. This only works if you have an `atomicCAS` that is at least as large as the type for which you are emulating the atomic. 

A mutex approach would be possible. I did consider it when originally implementing the hash-based groupby, but it would be a significant amount of work---not the least of which is implementing a performant and safe device mutex. Perhaps once `std::mutex` is supported in device code we can revisit. 

So I was too hasty to say it's impossible. Rather, it's infeasible any time in the foreseeable future.

**Comment by harrism** [comment]
Of course there's also the important fact that we don't actually support any data types larger than 64 bits today. Even strings are dictionary encoded before we act on them.

**Comment by kkraus14** [comment]
Closing in favor of discussion in #3958
