### ISSUE TITLE
[FEA] CEC for CUDA 12: using nvjitlink (instead of ptxcompiler / cubinlinker)

### ISSUE THREAD

**Issue by sevagh** [rapidsai/cudf#12822]
cuDF uses ptxcompiler and cubinlinker for CEC. Will this be changing for CUDA 12? We should discuss.

@bdice @gmarkall @vyasr

**Comment by bdice** [comment]
In my understanding, we have (at least) two options:

1. Create ptxcompiler/cubinlinker packages for CUDA 12 that do "nothing" (or at least less work than the current packages by leveraging nvJitLink?) -- then we don't have to make CUDA-version-dependent lists of dependencies for cuDF.
2. Alter cuDF in a way that doesn't depend on ptxcompiler/cubinlinker packages when building for CUDA 12 (but this may require some kind of nvJitLink support built into cuDF?). This requires CUDA version knowledge when determining cuDF dependencies.

Happy to be corrected if anything above is inaccurate.

**Comment by vyasr** [comment]
My understanding was that this wouldn't be a build-time issue at all, but that numba would "just work" when using CUDA 12 JITted kernels across different minor CUDA versions (probably by using nvJitLink under the hood). I thought that all cudf would need to do is to make the cubinlinker and ptxcompiler requirements conditional on the CUDA version.

**Comment by sevagh** [comment]
The only issue I encountered when test-driving CUDA 12 pip wheel builds for cuDF (i.e. cudf-cu12, dask-cudf-cu12) was in the test step, where the install of cudf-cu12 couldn't find ptxcompiler-cu12, cubinlinker-cu12 to install from its requirements.

So, if the only change for CUDA 12 is to delete those lines (perhaps using `ci/release/apply_wheel_modifications.sh`, Vyas' new mechanism for modifying setuptools/python package files), that's fine too.

**Comment by vyasr** [comment]
If simply removing the requirements makes everything work then yeah we could use that script (although it wouldn't be enough by itself, we would also need to do something for conda packages.

**Comment by bdice** [comment]
Conda packages are easier because we can template the `meta.yaml` on the `RAPIDS_CUDA_VERSION` environment variable. That will already be necessary to make CUDA 11/12 compatible sets of CUDA dependencies.

**Comment by vyasr** [comment]
Yup I agree, it's not hard. Just one more thing to do in addition to what we'd do for wheels.

**Comment by jakirkham** [comment]
cc @gmarkall

**Comment by jakirkham** [comment]
(bump)

**Comment by vyasr** [comment]
Short term solution: https://github.com/rapidsai/cudf/issues/13339

**Comment by jakirkham** [comment]
Have tried to retitle this issue to make it clearer to others. Please feel free to revise if there is a better way to capture the intent here
