### ISSUE TITLE
Conda install erro

### ISSUE THREAD

**Issue by jIskCoder** [rapidsai/cudf#12821]
When I run 

`conda install -c rapidsai -c conda-forge -c nvidia cudf=23.04 python=3.10 cudatoolkit=11.8
`
I get the following error

```
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=11.8
  - cudf=23.04

Current channels:

  - https://conda.anaconda.org/rapidsai/linux-64
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/nvidia/linux-64
  - https://conda.anaconda.org/nvidia/noarch
  - https://levinthal:paradox@conda.graylab.jhu.edu/linux-64
  - https://levinthal:paradox@conda.graylab.jhu.edu/noarch
  - https://conda.anaconda.org/biobakery/linux-64
  - https://conda.anaconda.org/biobakery/noarch
  - https://conda.anaconda.org/bioconda/linux-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

```

**Comment by bdice** [comment]
Hi @jIskCoder, can you try adding `-c rapidsai-nightly` to the list of channels? If you want to install 23.04, it is still a nightly and not yet a final release. Our current release is 23.02, and you can change your installation command to `cudf=23.02` if you prefer to install a stable release.

Example of 23.04 nightly installation:
```bash
conda create -n rapids-23.04 -c rapidsai-nightly -c conda-forge -c nvidia  \
    cudf=23.04 python=3.10 cudatoolkit=11.8
```

Example of 23.02 stable installation:
```bash
conda create -n rapids-23.02 -c rapidsai -c conda-forge -c nvidia  \
    cudf=23.02 python=3.10 cudatoolkit=11.8
```

I’ll close this for now, but please feel free to reopen if anything else comes up! Thanks for using cuDF! 😊

**Comment by zachary62** [comment]
This is very helpful. 
Could you fix the instruction in the readme?
If 23.04 is not available, why does it appear on the front page? I've spent hours struggling with that.

**Comment by bdice** [comment]
@zachary62 The repository’s default branch determines the README that is shown. That points to our developer branch, which is currently for the 23.04 release. We try to avoid confusion by including a note at the top of the README:

> NOTE: For the latest stable [README.md](https://github.com/rapidsai/cudf/blob/main/README.md) ensure you are on the main branch.

The best place to get installation instructions is the main website, https://rapids.ai. The release selector includes information on several installation methods including Docker, conda, and pip, for nightly/stable versions and various other options. Hope that helps!
