### ISSUE TITLE
[BUG] cannot load library 'librmm.so'

### ISSUE THREAD

**Issue by manojkumardas7** [rapidsai/cudf#1283]
**Describe the bug**
unable to use cudf

**Steps/Code to reproduce bug**

here are my environment entries
export PATH=/usr/local/cuda-10.0/bin${PATH:+:$PATH}}
export PATH=/usr/local/MATLAB/bin${PATH:+:$PATH}}
export CUDADIR=/usr/local/cuda-10.0
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export LD_LIBRARY_PATH=/usr/local/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export NUMBAPRO_NVVM=/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so
export NUMBAPRO_LIBDEVICE=/usr/local/cuda-10.0/nvvm/libdevice

for cudf-cuda100==0.6, I get the following error on import
OSError: cannot load library 'librmm.so': librmm.so: cannot open shared object file: No such file or directory

for cudf-cuda100==0.5, import is succesful but on creating a dataframe:
cudf.DataFrame({'x': np.random.rand(100)})
below is returned
GDFError: CUDA ERROR. cudaSuccess: no error

**Expected behavior**
should had imported/ created a cuda dataframe

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [pip]
environment details
I have cuda toolkit 10.
nvcc -V works
deviceQuery from cuda examples test has PASSED
Python version is 3.7
OS is Ubuntu 18.04.2 LTS 

**Additional context**

**Comment by harrism** [comment]
Please run the print_env.sh from the cudf root directory and include the results here.

**Comment by kkraus14** [comment]
@manojkumardas7 is there any update from your side on this issue? Dumping the environment would greatly help us to solve this issue.

**Comment by manojkumardas7** [comment]
@harrism and @kkraus14, sorry guys, been really caught up with my daily job. I have installed cudf using the pypi repository, if that is something that also helps. Below is the run of the print_env.sh, I shall try to be prompt from now, possible delay due to difference in time zone.

**git***
commit c7ad586cc2ccbb219e0e0c1672c698f43d691325 (HEAD -> branch-0.7, origin/branch-0.7, origin/HEAD)
Merge: dc7a86a1 94e9f2e7
Author: Keith Kraus <keith.j.kraus@gmail.com>
Date:   Mon Apr 8 14:51:39 2019 -0500

    Merge pull request #1363 from kkraus14/fea-ext-dataframe-mean-notimplemented
    
    [REVIEW] Add DataFrame.mean that raises NotImplementedError

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux mansLap 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Tue Apr  9 05:18:06 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GT 650M     Off  | 00000000:01:00.0 N/A |                  N/A |
| N/A   78C    P0    N/A /  N/A |    157MiB /   981MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               58
Model name:          Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz
Stepping:            9
CPU MHz:             1826.080
CPU max MHz:         3400.0000
CPU min MHz:         1200.0000
BogoMIPS:            4788.86
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            6144K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts flush_l1d

***CMake***
/usr/bin/cmake
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


***nvcc***
/usr/local/cuda-10.0/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

***Python***
/usr/bin/python
Python 2.7.15rc1

***Environment Variables***
PATH                            : /usr/local/spark/bin:/snap/bin:/opt/mssql-tools/bin:/usr/local/MATLAB/bin:/usr/local/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin}}}}
LD_LIBRARY_PATH                 : /usr/local/lib:/usr/local/cuda-10.0/lib64
NUMBAPRO_NVVM                   : /usr/local/cuda-10.0/nvvm/lib64/libnvvm.so
NUMBAPRO_LIBDEVICE              : /usr/local/cuda-10.0/nvvm/libdevice
CONDA_PREFIX                    : 
PYTHON_PATH                     : 

conda not found
***pip packages***
/usr/local/bin/pip
Package                  Version            
------------------------ -------------------
-upy                     5.2.0              
alabaster                0.7.12             
apt-clone                0.2.1              
apt-xapian-index         0.47               
apturl                   0.5.2              
asn1crypto               0.24.0             
Babel                    2.6.0              
backcall                 0.1.0              
bleach                   3.1.0              
Brlapi                   0.6.6              
certifi                  2018.1.18          
cffi                     1.11.5             
chardet                  3.0.4              
click                    6.7                
cloudpickle              0.7.0              
colorama                 0.4.1              
command-not-found        0.3                
configparser             3.7.1              
cryptography             2.1.4              
cudf-cuda100             0.6.0.post1        
cupshelpers              1.0                
cupy                     5.3.0              
cycler                   0.10.0             
Cython                   0.29.4             
dask                     1.1.0              
decorator                4.3.0              
defer                    1.0.6              
defusedxml               0.5.0              
distro-info              0.18ubuntu0.18.04.1
docutils                 0.14               
entrypoints              0.3                
fastrlock                0.4                
gstreamer-player         1.1.2              
Guake                    3.0.5              
httplib2                 0.9.2              
ibm-db                   2.0.9              
idna                     2.6                
imagesize                1.1.0              
ipykernel                5.1.0              
ipyparallel              6.2.3              
ipython                  7.2.0              
ipython-genutils         0.2.0              
ipywidgets               7.4.2              
Jasper                   0.1                
jedi                     0.13.2             
Jinja2                   2.10               
jsonschema               2.6.0              
jupyter                  1.0.0              
jupyter-client           5.2.4              
jupyter-console          6.0.0              
jupyter-core             4.4.0              
keyring                  10.6.0             
keyrings.alt             3.0                
kiwisolver               1.0.1              
language-selector        0.1                
launchpadlib             1.10.6             
lazr.restfulclient       0.13.5             
lazr.uri                 1.0.3              
llvmlite                 0.28.0             
louis                    3.5.0              
macaroonbakery           1.1.3              
Mako                     1.0.7              
MarkupSafe               1.0                
matplotlib               3.0.2              
mistune                  0.8.4              
mutagen                  1.42.0             
nbconvert                5.4.0              
nbformat                 4.4.0              
netifaces                0.10.4             
networkx                 2.2                
nose                     1.3.7              
notebook                 5.7.4              
numba                    0.41.0             
numpy                    1.16.2             
nvstrings-cuda100        0.2.0.post2        
oauth                    1.0.1              
olefile                  0.45.1             
packaging                19.0               
PAM                      0.4.2              
pandas                   0.24.0             
pandocfilters            1.4.2              
parso                    0.3.2              
pbr                      3.1.1              
pexpect                  4.2.1              
pickleshare              0.7.5              
Pillow                   5.1.0              
pip                      19.0.3             
pipenv                   2018.11.26         
prometheus-client        0.5.0              
prompt-toolkit           2.0.7              
protobuf                 3.0.0              
psycopg2                 2.7.7              
ptyprocess               0.6.0              
py4j                     0.10.7             
pyarrow                  0.13.0             
pycairo                  1.16.2             
pycparser                2.19               
pycrypto                 2.6.1              
pycryptodome             3.7.3              
pycups                   1.9.73             
Pygments                 2.3.1              
pygobject                3.26.1             
PyICU                    1.9.8              
pymacaroons              0.13.0             
pymssql                  2.1.4              
PyMySQL                  0.9.3              
PyNaCl                   1.1.2              
pyocr                    0.5.3              
pyodbc                   4.0.25             
pyparsing                2.3.1              
pyRFC3339                1.0                
pyspark                  2.4.0              
python-apt               1.6.3+ubuntu1      
python-dateutil          2.7.5              
python-debian            0.1.32             
pytz                     2018.3             
PyWavelets               1.0.1              
pyxdg                    0.25               
PyYAML                   3.12               
pyzmq                    17.1.2             
qtconsole                4.4.3              
redis                    3.0.1              
reportlab                3.4.0              
requests                 2.18.4             
requests-unixsocket      0.1.5              
scikit-image             0.14.2             
scikit-learn             0.20.2             
scipy                    1.2.0              
screen-resolution-extra  0.0.0              
SecretStorage            2.3.1              
Send2Trash               1.5.0              
setuptools               40.6.3             
simplejson               3.13.2             
six                      1.12.0             
sklearn                  0.0                
snowballstemmer          1.2.1              
Sphinx                   1.8.3              
sphinxcontrib-websupport 1.1.0              
SQLAlchemy               1.2.17             
system-service           0.3                
systemd-python           234                
teradatasql              16.20.0.39         
teradatasqlalchemy       16.20.0.5          
termcolor                1.1.0              
terminado                0.8.1              
tesseract                0.1.3              
testpath                 0.4.2              
testresources            2.0.1              
toolz                    0.9.0              
tornado                  5.1.1              
tqdm                     4.11.2             
traitlets                4.3.2              
ubuntu-drivers-common    0.0.0              
ufw                      0.35               
unattended-upgrades      0.1                
urllib3                  1.22               
usb-creator              0.3.3              
virtualenv               16.2.0             
virtualenv-clone         0.5.1              
wadllib                  1.3.2              
wcwidth                  0.1.7              
webencodings             0.5.1              
wheel                    0.32.3             
widgetsnbextension       3.4.2              
xkit                     0.0.0              
zope.interface           4.3.2

**Comment by harrism** [comment]
What was your `git clone` command? Did you use the `-recurse-submodules` option? I'm wondering if you have the RMM submodule and if it is building properly.

Can you do a clean clone and build and paste the entire output?

**Comment by manojkumardas7** [comment]
@harrism, I have used the pypi repository for the cudf installation. Which means I have not done the build from the repository. I have tried doing the build in the past and it has not gone so well, but I am happy to try again. Can you also let me know which branch would you want me  to try out.

**Comment by kkraus14** [comment]
@manojkumardas7 It looks like you're trying to run this on a `Kepler` architecture card as well as Python 2.7. We dropped support for Python 2.7 a few months back, so I'd recommend upgrading to Python 3, and as far as I'm aware we don't support the Kepler architecture.

@harrism anything to add about the architecture?

**Comment by harrism** [comment]
Ah, sorry I thought this was a build-from-source issue. @kkraus14 you are correct, we can't support Kepler: no unified memory and insufficient atomics.

**Comment by manojkumardas7** [comment]
@kkraus14 - Using Python 3.7, although the print_env script my display python2.7, I have used python 3.7, using pip3.7

@harrism 
Also my GPU is not the Kepler architecture. I am just using CUDA 10, as I have moved to CUDA 10 for my developments.
