### ISSUE TITLE
Parquet read pipeline decode step

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#12845]
This portion of the work for pipelining the parquet reader will focus on the decode step of the read. This occurs after the data is read and decompressed and involved converting to the cudf format. Pipelining of this step would result in reading group N, decompressing group N-1, and decoding group N-2 all at the same time.

Measuring of success will depend on the performance results of this conversion. Care must be taking to measure many variables such as:

- row group size
- compression type
- overall file size
- cardinality

**Comment by GregoryKimball** [comment]
Closing in favor of #11951
