### ISSUE TITLE
Pipeline Parquet file reads and decompress

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#12844]
As part of the larger pipeline work, we need to pipeline the parquet read and decompress steps. This work will break the read into groups and read group N while decompressing group N-1. The group size is yet to be determined and may be user controlled depending on performance wins.

Measuring of success will depend on the performance results of this conversion. Care must be taking to measure many variables such as:

- row group size
- compression type
- overall file size
- cardinality

**Comment by GregoryKimball** [comment]
Closing in favor of #11951
