### ISSUE TITLE
[FEA] Is semi-join supported?

### ISSUE THREAD

**Issue by zachary62** [rapidsai/cudf#12880]
**Is your feature request related to a problem? Please describe.**
There was an old issue about supporting semi join https://github.com/rapidsai/cudf/issues/3903
Not sure if it is supported or not. If it is, can you refer me to the doc?

I basically want something like this: df1[df1.x.isin(df2.x)], df1[~df1.x.isin(df2.x)]

So I can efficiently select df1 based on whether x is in df2.x or not. I want to update part of df1 based on if df1.x.isin(df2.x).
The problem with merge is that it creates a new dataframe, which consumes GPU memory and can't update in-place.

However, currently, isin is even slower than merge, even if merge creates a new table! I suspect due to inefficient implementation, as isin is not expecting a large list.

**Comment by shwina** [comment]
Yes -- semi joins are supported. As described in the `merge` docs, you can use `how='lefsemi'` or `how='leftanti`' to do semi joins:

https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.dataframe.merge#cudf.DataFrame.merge

Please let us know if that works for you and answers your question!

**Comment by zachary62** [comment]
Hi @shwina , my understanding is that the leftsemi still creates a new dataframe right?
Is it possible to return an array of T/F to select the original dataframe?
Something like df1[df1.x.isin(df2.x)], but isin is even slower than creating a new dataframe,

**Comment by shwina** [comment]
Correct -- it returns a new dataframe. 

It would be helpful if you could provide a reproducible example of when `isin()` is slow (it sounds like that is the root issue here).

That being said, perhaps this trick will allow you to make some progress:

```
# Say you start with these two dataframes:

>>> df1
Out[11]: 
   x  y
0  1  a
1  2  b
2  3  c
3  4  d

>>> df2
Out[12]: 
   x  y
0  2  c
1  3  d
2  4  b
3  5  g

# first, add a "sequence" column to df1
>>> df1['index'] = range(len(df1))

# next, do a left semi join, but only include the columns
# that will participate in the join. This makes the output
# as small as possible:
>>> df1[['x', 'index']].merge(df2[['x']], how='leftsemi')
   x  index
0  2      1
1  3      2
2  4      3

# The `index` column in the result gives you the integer indexes into `df1`
# where `df1.x.isin(df2.x)`. You can use it with e.g., `iloc`.
```

**Comment by zachary62** [comment]
My experiments:

`
import cudf
import pandas as pd
import numpy as np

df1 = pd.DataFrame()
dim = 1000000
df1["A"] = np.random.randint(0, dim, 20000000)
df1["B"] = np.random.randint(0, 10000, 20000000)

df2 = pd.DataFrame()
df2["A"] = np.arange(0, dim, 1)
df2["C"] = np.random.randint(0, 200, dim)

df1 = cudf.from_pandas(df1)
df2 = cudf.from_pandas(df2)

%%time
df2_selected = df2[df2["C"]<10]
3.9ms

%%time
df3 = df1.merge(df2_selected, on='A', how='leftsemi')
del df3
8.33ms

%%time
df1[df1.A.isin(df2_selected.A)]
54ms

%%time
df1['index'] = range(len(df1))
idx = df1[['A', 'index']].merge(df2_selected[['A']], how='leftsemi')
9.43ms

%%time
df1.loc[idx["index"], 'A'] = 1
27.9ms
`
This trick looks great!

**Comment by shwina** [comment]
Note that you should use `.iloc[]` rather than `loc[]`. It's also much faster:

Replace:

```
df1.loc[idx["index"], 'A'] = 1
```

With:

```
%%time
df1['A'].iloc[idx["index"]] = 1

CPU times: user 4.98 ms, sys: 0 ns, total: 4.98 ms
Wall time: 4.45 ms
```

**Comment by zachary62** [comment]
Thank you so much!

**Comment by zachary62** [comment]
Just to fix another inefficiency. df1['index'] = range(len(df1)) so use reset_index instead
