### ISSUE TITLE
[BUG] API mismatch - DataFrame.to_csv line_terminator vs pandas' lineterminator

### ISSUE THREAD

**Issue by mattf** [rapidsai/cudf#12894]
**Describe the bug**
writing code with `import cudf as pd`

**Steps/Code to reproduce bug**

[pandas to_csv uses `lineterminator`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv)

[cudf to_csv uses `line_terminator`](https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.dataframe.to_csv#cudf.DataFrame.to_csv)

**Expected behavior**
`cudf to_csv` to accept `lineterminator`

https://github.com/rapidsai/cudf/blob/branch-23.02/python/cudf/cudf/io/csv.py#L158

**Comment by wence-** [comment]
Note that pandas < 1.5 used `line_terminator` (see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_csv.html#pandas.DataFrame.to_csv). Pandas 1.5 will accept `line_terminator` and produce a deprecation warning, pandas 2 removes `line_terminator`.

So we should deprecate `line_terminator` in 23.04, accept `lineterminator` and drop `line_terminator` in 23.06.

**Comment by galipremsagar** [comment]
> So we should deprecate `line_terminator` in 23.04, accept `lineterminator` and drop `line_terminator` in 23.06.

+1
