### ISSUE TITLE
[BUG] cudf import is not successful after installing it with pip on Databricks cluster

### ISSUE THREAD

**Issue by tdembelova** [rapidsai/cudf#12893]
**Describe the bug**
After installing `cudf` with `%pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.nvidia.com` in Databricks notebook, I try to do `import cudf`, which throws the exception below.

This issue is similar: https://github.com/rapidsai/cudf/issues/12772.
```
FileNotFoundError                         Traceback (most recent call last)
<command-323111309219749> in <module>
----> 1 import cudf
      2 print(cudf.Series([1, 2, 3]))

/databricks/python_shell/dbruntime/PythonPackageImportsInstrumentation/__init__.py in import_patch(name, globals, locals, fromlist, level)
    165             # Import the desired module. If you’re seeing this while debugging a failed import,
    166             # look at preceding stack frames for relevant error information.
--> 167             original_result = python_builtin_import(name, globals, locals, fromlist, level)
    168 
    169             is_root_import = thread_local._nest_level == 1

/databricks/python/lib/python3.8/site-packages/cudf/__init__.py in <module>
      3 from cudf.utils.gpu_utils import validate_setup
      4 
----> 5 validate_setup()
      6 
      7 import cupy

/databricks/python/lib/python3.8/site-packages/cudf/utils/gpu_utils.py in validate_setup()
     93             )
     94 
---> 95         cuda_runtime_version = runtimeGetVersion()
     96 
     97         if cuda_runtime_version < 11000:

/databricks/python/lib/python3.8/site-packages/rmm/_cuda/gpu.py in runtimeGetVersion()
     85     # TODO: Replace this with `cuda.cudart.cudaRuntimeGetVersion()` when the
     86     # limitation is fixed.
---> 87     major, minor = numba.cuda.runtime.get_version()
     88     return major * 1000 + minor * 10
     89 

/databricks/python/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py in get_version(self)
    109         """
    110         rtver = ctypes.c_int()
--> 111         self.cudaRuntimeGetVersion(ctypes.byref(rtver))
    112         # The version is encoded as (1000 * major) + (10 * minor)
    113         major = rtver.value // 1000

/databricks/python/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py in __getattr__(self, fname)
     63 
     64         if not self.is_initialized:
---> 65             self._initialize()
     66 
     67         # Find function in runtime library

/databricks/python/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py in _initialize(self)
     49                    "32-bit systems.")
     50             raise CudaSupportError(msg)
---> 51         self.lib = open_cudalib('cudart')
     52 
     53         self.is_initialized = True

/databricks/python/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py in open_cudalib(lib)
     57 
     58 def open_cudalib(lib):
---> 59     path = get_cudalib(lib)
     60     return ctypes.CDLL(path)
     61 

/databricks/python/lib/python3.8/site-packages/numba/cuda/cudadrv/libs.py in get_cudalib(lib, platform, static)
     49         return get_cuda_paths()['nvvm'].info or _dllnamepattern % 'nvvm'
     50     else:
---> 51         libdir = get_cuda_paths()['cudalib_dir'].info
     52 
     53     candidates = find_lib(lib, libdir, platform=platform, static=static)

/databricks/python/lib/python3.8/site-packages/numba/cuda/cuda_paths.py in get_cuda_paths()
    147         d = {
    148             'nvvm': _get_nvvm_path(),
--> 149             'libdevice': _get_libdevice_paths(),
    150             'cudalib_dir': _get_cudalib_dir(),
    151         }

/databricks/python/lib/python3.8/site-packages/numba/cuda/cuda_paths.py in _get_libdevice_paths()
     55     # Search for pattern
     56     pat = r'libdevice(\.\d+)*\.bc$'
---> 57     candidates = find_file(re.compile(pat), libdir)
     58     # Keep only the max (most recent version) of the bitcode files.
     59     out = max(candidates, default=None)

/databricks/python/lib/python3.8/site-packages/numba/misc/findlib.py in find_file(pat, libdir)
     54     files = []
     55     for ldir in libdirs:
---> 56         entries = os.listdir(ldir)
     57         candidates = [os.path.join(ldir, ent)
     58                       for ent in entries if pat.match(ent)]

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/cuda/nvvm/libdevice'
```

**Steps/Code to reproduce bug**
1. Create a compute using Databricks UI (single node, Databricks Runtime: 10.4 LTS ML, node type is g5.xlarge)
2. Create a Databricks Notebook with this compute.
3. Run cell command `!pip install cudf-cu11 dask-cudf-cu11 --extra-index-url=https://pypi.nvidia.com`
4. Run cell command `import cudf` -> Exception from above

**Expected behavior**
The import command shoud successfully finish.

**Environment overview (please complete the following information)**
 - Environment location: Databricks
 - Method of cuDF install: pip

**Environment details**
***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.5 LTS"
     NAME="Ubuntu"
     VERSION="20.04.5 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.5 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux 0131-140614-jhowe4lp-10-45-199-90 5.4.0-1096-aws #104~18.04.1-Ubuntu SMP Wed Jan 25 19:58:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Mar  7 15:03:43 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  NVIDIA A10G         Off  | 00000000:00:1E.0 Off |                    0 |
     |  0%   26C    P8     9W / 300W |      2MiB / 22731MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   48 bits physical, 48 bits virtual
     CPU(s):                          4
     On-line CPU(s) list:             0-3
     Thread(s) per core:              2
     Core(s) per socket:              2
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       AuthenticAMD
     CPU family:                      23
     Model:                           49
     Model name:                      AMD EPYC 7R32
     Stepping:                        0
     CPU MHz:                         3205.910
     BogoMIPS:                        5599.66
     Hypervisor vendor:               KVM
     Virtualization type:             full
     L1d cache:                       64 KiB
     L1i cache:                       64 KiB
     L2 cache:                        1 MiB
     L3 cache:                        8 MiB
     NUMA node0 CPU(s):               0-3
     Vulnerability Itlb multihit:     Not affected
     Vulnerability L1tf:              Not affected
     Vulnerability Mds:               Not affected
     Vulnerability Meltdown:          Not affected
     Vulnerability Mmio stale data:   Not affected
     Vulnerability Retbleed:          Vulnerable
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Not affected
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext ssbd ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr wbnoinvd arat npt nrip_save rdpid
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.16.3
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /databricks/python3/bin/python
     Python 3.8.10
     
     ***Environment Variables***
     PATH                            : /databricks/python3/bin:/usr/local/nvidia/bin:/databricks/python3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     ***conda packages***
     conda: not found

**Additional context**
Installing using conda works, however then I can not access cudf from Databricks notebook, only from the terminal...

**Comment by vyasr** [comment]
Since there's already discussion on #12772 I'm going to close this issue to consolidate discussion.
