### ISSUE TITLE
[QST]When I add printf in cpp/src/binaryop/binaryop.cpp,there isn't print 

### ISSUE THREAD

**Issue by newjavaer** [rapidsai/cudf#12913]
When I add printf in cpp/src/binaryop/binaryop.cpp,there isn't print  in python code.

**Comment by bdice** [comment]
@newjavaer What data types and operators are you using?

**Comment by newjavaer** [comment]
Hi, @bdice .I use python demo in  https://github.com/rapidsai/cudf/tree/branch-22.12.I compile licudf and cudf manually.Then I add print log in cpp/src/binaryop/binaryop.cpp,but there isn't print.I think it maybe use cudf ,because it use gpu memory when the code running.

**Comment by GregoryKimball** [comment]
> I think cudf might be calling cupy instead of libcudf's binary ops for some paths

@newjavaer At which lines did you insert the `printf` statements?

> I think it maybe use cudf ,because it use gpu memory when the code running

@bdice mentioned that perhaps the cuDF-python code path would be using `cupy`, which is another GPU-accelerated library and would also be expected to use GPU memory as you observed. 

Would you also please share a python code where you expect to trigger the `printf` statements?

**Comment by vyasr** [comment]
Closing as stale. Please reopen if needed.
