### ISSUE TITLE
[BUG] Issues while loading TimeStamp columns

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#12926]
```
In [2]: import cudf

In [3]: cudf.read_orc('tsrepro.orc')
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[3], line 1
----> 1 cudf.read_orc('tsrepro.orc')

File /conda/envs/rapids-23.02/lib/python3.10/site-packages/cudf/io/orc.py:370, in read_orc(filepath_or_buffer, engine, columns, filters, stripes, skiprows, num_rows, use_index, timestamp_type, use_python_file_object, storage_options, bytes_per_thread)
    366         stripes = selected_stripes
    368 if engine == "cudf":
    369     return DataFrame._from_data(
--> 370         *liborc.read_orc(
    371             filepaths_or_buffers,
    372             columns,
    373             stripes,
    374             skiprows,
    375             num_rows,
    376             use_index,
    377             timestamp_type,
    378         )
    379     )
    380 else:
    382     def read_orc_stripe(orc_file, stripe, columns):

File orc.pyx:84, in cudf._lib.orc.read_orc()

File orc.pyx:121, in cudf._lib.orc.read_orc()

RuntimeError: CUDF failure at: /opt/conda/conda-bld/work/cpp/src/io/orc/timezone.cpp:138: Failed to open the timezone file.
```

[tsrepro.orc.zip](https://github.com/rapidsai/cudf/files/10946593/tsrepro.orc.zip)

**Comment by karthikeyann** [comment]
Please share the environment details.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Comment by mlahir1** [comment]
Environment location: Docker.
Method of cuDF install: conda

output of  print_env.sh is attached. 
[env.txt](https://github.com/rapidsai/cudf/files/10959041/env.txt)

Same issue happens with 23.04 nightly too.

**Comment by karthikeyann** [comment]
is it your own dockerfile?

Try installing `tzdata` in your dockerfile
`apt-get install --reinstall tzdata`

**Comment by mlahir1** [comment]
reinstall tzdata fixed it, i will add that to the docker file.

**Comment by karthikeyann** [comment]
Keeping this open to provide a method to use `tzdata` package installed via conda, in orc reader.

@vuule Right now, tzif_system_directory is hardcoded to `"/usr/share/zoneinfo/"` https://github.com/rapidsai/cudf/blob/276bcf4171c82101a12b3d2392802e4746d0d2e3/cpp/src/io/orc/timezone.cpp#L27  
 when cudf installed conda, `tzdata` package is installed but orc reader cannot access it now. Alternate path in conda is `$CONDA_PREFIX/share/zoneinfo`, it should be accessible by orc reader.

**Comment by vuule** [comment]
Understood.
Should we default to `/usr/share/zoneinfo/`, but fall back to `$CONDA_PREFIX/share/zoneinfo` if the default dir fails?

**Comment by vyasr** [comment]
I'm guessing we'd want the reverse? We generally prefer conda files (libraries/headers/whatever) inside a conda environment to system files.

**Comment by vuule** [comment]
Sounds good. I'll make the change after the refactor PR is merged.

**Comment by vyasr** [comment]
See https://github.com/rapidsai/cudf/pull/15214#issuecomment-2378094929
