### ISSUE TITLE
[FEA] Throw `std::overflow` exception when an output column size exceeds cudf limit

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#12925]
In Spark, we want to handle the cases when the libcudf APIs throw exception due to their output column having sizes exceeding cudf limit. We want to differentiate if the thrown exception was really due to such reason (so we can split the input by half and try again), or due to something else (such as invalid input type or inconsistent data type etc). Unfortunately, currently only one type of exception (`cudf::logic_error`) is being thrown.

We want to have a new specific exception type with a name like `cudf::output_size_exceed_limit`. This exception type will be used to throw in the case mentioned above. Adding this new exception type is similar to https://github.com/rapidsai/cudf/pull/12426 which introduced a new exception type to throw when the input data type is invalid.

**Comment by vyasr** [comment]
Please raise this issue for discussion on Slack or in the next team meeting. It would be great to consider whether there should be different exceptions for compound (strings) columns than for other columns too. I am not necessarily advocating this, but it's something to consider in case there are different ways that a caller could attempt to mitigate one scenario than the other (CC @davidwendt).

Depending on what decision is made, please update #12885 accordingly.

**Comment by ttnghia** [comment]
I think it is relevant not just for strings column. For example, we have the `concatenate` and `interleave` APIs that append columns one after another. If the total size of the input exceeds cudf limit, we can also throw the proposed exception above, indicating the exact failure reason (the `interleave` API can still split retry again with half size input).

**Comment by ttnghia** [comment]
That can be fine, only still a minor issue if `std::overflow_error` is thrown by other code rather than our check for column size. But I assume that such issue will now show up very soon so let's use that std exception.
