### ISSUE TITLE
[BUG] reading ORC file fails

### ISSUE THREAD

**Issue by rgoel1122** [rapidsai/cudf#12920]
**Describe the bug**
When reading an ORC file, cudf reports error
```
$ python readorc_cudf.py 
customer.0000.orc
Traceback (most recent call last):
  File "/home/rohit/test/readorc_cudf.py", line 12, in <module>
    df = cudf.read_orc(f)
  File "/home/rohit/envs/theseus_dev/lib/python3.10/site-packages/cudf/io/orc.py", line 370, in read_orc
    *liborc.read_orc(
  File "orc.pyx", line 84, in cudf._lib.orc.read_orc
  File "orc.pyx", line 121, in cudf._lib.orc.read_orc
RuntimeError: CUDF failure at: /opt/mambaforge/conda-bld/libcudf-ext_1676569522224/work/cpp/src/io/orc/reader_impl.cu:656: ORC data decode failed
```

reading file with pandas or pyarrow succeeds.

**Steps/Code to reproduce bug**
following python code was used to read the orc file

```
import cudf
files = [ 'customer.0000.orc' ]                
for f in files:
    print(f)
    df = cudf.read_orc(f)
    print(df)
```

[customer.0000.orc.zip](https://github.com/rapidsai/cudf/files/10937356/customer.0000.orc.zip)

**Comment by GregoryKimball** [comment]
Thank you for posting this IO failure. Looking at the data I see only simple types, so your observation is surprising! Would you please let me know if you've seen any small files or snippets showing decode failures?

**Comment by rgoel1122** [comment]
Gegory, I was able to read a smaller file (attached).  
[customer.0000.small.zip](https://github.com/rapidsai/cudf/files/10991503/customer.0000.small.zip)

**Comment by GregoryKimball** [comment]
Thanks @rgoel1122 I did a bit more testing here and the failure seems to come from ORC files with >10000 rows in a string column, when written by pandas. Here's an example:

```
    for rows in [10000,10001]:
        df = pd.DataFrame({'a':['b'] * rows})
        df.to_orc(f'pd_write_{rows}')
        try:
            d = cudf.read_orc(f'pd_write_{rows}')
            print(f'ok with pd_write_{rows}')
        except:
            print(f'failed with pd_write_{rows}')

        gdf = cudf.DataFrame(df)
        gdf.to_orc(f'cudf_test{rows}')
        try:
            d = cudf.read_orc(f'cudf_test{rows}')
            print(f'ok with cudf_write_{rows}')
        except:
            print(f'failed with cudf_write_{rows}')
```
output:
```
ok with pd_write_10000
ok with cudf_write_10000
failed with pd_write_10001
ok with cudf_write_10001
```
[orc_error.zip](https://github.com/rapidsai/cudf/files/10994842/orc_error.zip)

@vuule The pandas file (10 kB) is bigger than the cudf file (0.7 kB) for some reason. Would you please take a look?

**Comment by GregoryKimball** [comment]
Looks like this is actually a repeat of #11890. Closing in favor of #11890.
