### ISSUE TITLE
[FEA] Series.rank

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1294]
**Is your feature request related to a problem? Please describe.**
As a cuDF user, I want to compute the rank of values in a column (i.e., I want to know that the value in cell X is the 5th largest/smallest and the value in cell Y is the Nth largest/smallest). The equivalent in the pandas API doc is [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.rank.html#pandas-series-rank).

Support for axis='columns' is likely less important than standard rank functionality.

**Describe the solution you'd like**
I'd like to be able to call `series.rank()` and return a new series containing the ranks.

**Describe alternatives you've considered**
One alternative is to sort the series, store the results in a new series, bring the index into a column, and then merge the results.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by harrism** [comment]
We can't do the libcudf implementation of this in 0.7. Suggest moving it to "next release" in feature planning.

**Comment by harrism** [comment]
In libcudf++, `cudf::sortedOrder()` returns the indices that would be used to materialize a sorted version of the input. I believe that is the same as the rank.  Just needs a Python interface.

**Comment by harrism** [comment]
I was wrong, because Pandas has multiple ways to treat equal values. So I think after sorting, you have to run another pass that compares consecutive values (in the sorted order) and combines the ones that are equal with the appropriate operator (min, max, average, first, etc.).  That makes this effectively a groupby. :(

**Comment by karthikeyann** [comment]
`numeric_only` arg implementation only is pending.

**Comment by beckernick** [comment]
I believe this was resolved by #4294 . Closing
