### ISSUE TITLE
[QST]Package not available when installing with Conda 

### ISSUE THREAD

**Issue by XiaomingY** [rapidsai/cudf#1295]
I am trying to install cupy in a new python 3.6 conda environment. Running
_conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf=0.6 python=3.6_
and there is packages NotFoundError.

With  
_conda install --channel "rapidsai" cudf_
The same packages NotFoundError and the current channel are listed:
 - https://conda.anaconda.org/rapidsai/win-64
 - https://conda.anaconda.org/rapidsai/noarch

Am I missing something for installing the package?

**Comment by XiaomingY** [comment]
Just realised there is no build for windows :(

**Comment by kkraus14** [comment]
@XiaomingY I would suggest you +1 #28 but Windows support is not on the short-term roadmap. Closing this as duplicate.
