### ISSUE TITLE
[BUG] Indexing a non-RangeIndex with a numpy integer returns a slice, not an entry

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#12954]
**Describe the bug**

```python
import cudf
import numpy as np

index = cudf.Index([1, 2], dtype="int64")
value = index[np.int32(0)]
print(type(value)) # => cudf.core.index.Int64Index
value = index[0]
print(type(value)) # => np.int64
```

Contrast, pandas, where indexing with a single value gives us a scalar in both cases.

**Expected behavior**

This should work, I think.

**Comment by vyasr** [comment]
Does this belong with #12793 or is this more of a one-off?

**Comment by wence-** [comment]
This is a one-off, I think. I guess I could add it to the long list of "give me tagged unions" bugs in dynamic dispatch.
