### ISSUE TITLE
[FEA] Groupby cumulative count

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1296]
**Is your feature request related to a problem? Please describe.**
As a cuDF user, I want to assign numbers to each observation of a group reflecting its order of occurrence in the group.

The equivalent in the pandas API doc is [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.cumcount.html#pandas-core-groupby-groupby-cumcount).

**Describe the solution you'd like**
I'd like to be able to call `df.groupby(col).cumcount()` and return a column of the same size containing the numberings described above.

**Comment by harrism** [comment]
Implementation is basically the same as groupby.cumsum. Will move to 0.8 along with #1298

**Comment by daxiongshu** [comment]
Is this the same function as the following code?
```
def get_order_in_group(y, order):
    for i in range(cuda.threadIdx.x, len(y), cuda.blockDim.x):
        order[i] = i

got = df.groupby(['y']).apply_grouped(get_order_in_group,incols=['y'],
                                  outcols={'order': 'int32'},
                                  tpb=self.tpb)
```
The full notebook [link](https://www.kaggle.com/jiweiliu/moa-all-rapids), `cell 15`.

**Comment by karthikeyann** [comment]
This operation requires output to be in same order as input. Is that right?

**Comment by kkraus14** [comment]
> This operation requires output to be in same order as input at column level. is that right?
> because order only within group is simply sequence from 0 to size(group).

It only requires the output order within groups to be stable. The ordering of the grouping keys is not required.

**Comment by harrism** [comment]
@karthikeyann is this implemented as part of 7387?

**Comment by karthikeyann** [comment]
Cython, Python code is not done yet.

**Comment by kkraus14** [comment]
@karthikeyann unassigned you since I figured someone else would do the Cython / Python code, but if you're tackling it please reassign yourself.

**Comment by karthikeyann** [comment]
I am already working on it.
