### ISSUE TITLE
[BUG] csv_reader setts the col_name member of gdf_column, but never frees it

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1297]
**Describe the bug**
I noticed that the csv reader will set the `col_name` of a `gdf_column`, but there is no code anywhere in cudf that either reads that field, or more importantly frees that field.  This is a minor memory leak, but more importantly `col_name` is really unnecessary and should probably just be removed.

**Steps/Code to reproduce bug**
Just run anything with the CSV reader and you will leak a string per column.

**Expected behavior**
No leaks happen.

**Environment details (please complete the following information):**
Nothing special just enough to run.
 

**Additional context**
None

**Comment by revans2** [comment]
FYI, if it is ok to just remove it, I am happy to put up a pull request for it.

**Comment by kkraus14** [comment]
@revans2 We actually use the names from the Python side to get the column names in the dataframe, but agreed we don't have any mechanism to free the names currently.

**Comment by revans2** [comment]
@kkraus14 thanks I missed the python code

**Comment by j-ieong** [comment]
@kkraus14  @revans2 We now free the column names in the Cython `csv.pyx` code.

**Comment by mjsamoht** [comment]
@revans2 let us know if you're still observing a memory leak.  As @j-ieong pointed out we are now freeing col names.  In the meantime, I'm closing this issue.
