### ISSUE TITLE
[DOC] Groupby apply JIT engine documentation example rendering incorrectly

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#12986]
The groupby.apply(..., engine="jit") [docs example](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.core.groupby.groupby.groupby.apply) is not rendering correctly as code.

Perhaps due to the [docstring not using a codeblock](https://github.com/rapidsai/cudf/blob/branch-23.04/python/cudf/cudf/core/groupby/groupby.py#L1148-L1160) literal?

**Comment by brandon-b-miller** [comment]
Taking a look at this - thanks!
