### ISSUE TITLE
[FEA] Ensure that we can get a columns libgdf dtype from python

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#1299]
**Is your feature request related to a problem? Please describe.**
I wish the python side of CUDF had a representation of libcudf dtype before it gets sent over to  libcudf. If you are someone like us where you provide users interaction from the python side but may send over a message to cudf not through cython but rather over the network. So we generate ipc handles for gpu data, put the handles and the rest of the column metadata into flatbuffers and ship that around. Right now the dtype is a pandas dtype before it goes to libcudf and gets converted to libcudf dtype when its going in.

**Describe the solution you'd like**
I want to know the libgdf dtype of a column at all points in its lifecycle regardless of wheter we are looking at it in python or in c++. Because we need to keep compatibility with pandas I would recommend having a panda_dtype and libgdf_dtype so people can appropriately choose the one they are using.

**Describe alternatives you've considered**
We are currently adding hacky logic that basically checks to see if something is a string column and if so setting its type to GDF_STRING on serialization.

**Comment by kkraus14** [comment]
@felipeblazing there's a dictionary in `cudf.bindings.cudf_cpp.dtypes` that you can use to convert from the Pandas dtype to a libcudf dtype. If we exposed a convenience function to handle that dictionary lookup for you and return the proper enum would that suffice for your needs?

**Comment by kkraus14** [comment]
Not an issue.
