### ISSUE TITLE
[FEA] Support binops between different size decimal types

### ISSUE THREAD

**Issue by ChrisJar** [rapidsai/cudf#13008]
**Is your feature request related to a problem? Please describe.**
I would like it if cudf supported binary operations between decimal types (columns or scalars) with different sizes (ex: Decimal32Dtype and DecimalDtype64)

```python
import cudf

s = cudf.Series([1,2,3], dtype=cudf.Decimal32Dtype(3,0))

s < cudf.Scalar(2,dtype=cudf.Decimal64Dtype(3,0))
```
throws:
```
ValueError: CUDF failure at:/opt/conda/conda-bld/work/cpp/src/binaryop/binaryop.cpp:206: Unsupported operator for these types
```
whereas:
```python
import cudf

s = cudf.Series([1,2,3], dtype=cudf.Decimal32Dtype(3,0))

s < cudf.Scalar(2,dtype=cudf.Decimal32Dtype(3,0))
```
returns:
```
0     True
1    False
2    False
dtype: bool
```

**Comment by shwina** [comment]
I think it's reasonable to upcast the input `Series` here before doing the operation. @ChrisJar do you need similarly to be able to do arithmetic ops like `+` or `*`? 

@mroeschke do you have any insights perhaps?

**Comment by mroeschke** [comment]
That sounds reasonable.

In pandas the story is a bit different because the "decimal" support is only through 1 pyarrow size, `decimal128` or through `object` type which doesn't have this size constraint.

**Comment by charlesbluca** [comment]
> @ChrisJar do you need similarly to be able to do arithmetic ops like + or *?

For context, this issue is coming up as part of adding support for decimal columns in https://github.com/dask-contrib/dask-sql/pull/1073, so ideally would want this to work for the following binary ops:

https://github.com/dask-contrib/dask-sql/blob/0f2062ff9c589b2f868c8acff10a40c681fd1bba/dask_sql/physical/rex/core/call.py#L983-L993

**Comment by vyasr** [comment]
This seems to work fine now
```
In [119]: s = cudf.Series([1,2,3], dtype=cudf.Decimal32Dtype(3,0))
     ...:
     ...: s < cudf.Scalar(2,dtype=cudf.Decimal64Dtype(3,0))
Out[123]:
0     True
1    False
2    False
dtype: bool
```
