### ISSUE TITLE
[BUG] Numba 0.57 will break row UDFs

### ISSUE THREAD

**Issue by gmarkall** [rapidsai/cudf#13002]
**Describe the bug**

Identified by @brandon-b-miller:

https://github.com/numba/numba/pull/8120 added a `bitwidth` attribute to the `Record` type, which is computed by converting the fields to their NumPy dtype and getting the item size. However, cuDF uses `Record` instances that have non-NumPy members - I believe we generate these types here: https://github.com/rapidsai/cudf/blob/branch-23.04/python/cudf/cudf/core/udf/row_function.py#L30

The consequence is that Numba raises when attempting to convert these members to NumPy dtypes.

**Steps/Code to reproduce bug**

Running the `test_string_udf_strip` test should reproduce the issue when Numba built from its `main` branch is in the environment should cause this: i.e. `pytest test_udf_masked_ops.py -k test_string_udf_strip`

**Expected behavior**

Successful execution of the test.

**Environment overview (please complete the following information)**

Any environment in which Numba built from current `main` is present (or the 0.57 RC / release when it's out).

**Environment details**

Not supplied.

**Additional context**

None.

**Comment by vyasr** [comment]
Resolved in #13271
