### ISSUE TITLE
[BUG] iloc indexing with a Categorical not possible

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#13013]
**Describe the bug**

```python
import cudf
import pandas as pd

f = pd.Series([0, 1, 2])
index1 = pd.Categorical([1])
f.iloc[index1] # => Length 1 series with the second row
index2 = pd.Categorical([0, 2])
f.iloc[index2] # => Length 2 series with first and third rows

cf = cudf.from_pandas(f)
cf.iloc[index1] # => TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Categorical'
cf.iloc[index2] # => NotImplementedError: Unknown indexer <class 'cudf.core.column.categorical.CategoricalColumn'>
```

The former error is because `_is_scalar_or_zero_d_array` treats categoricals of length one as scalars (prior to https://github.com/vyasr/cudf/commit/62511222d4dd72fa078c47b5c283c185111b79f9 _all_ categoricals were treated as scalars). Which, as observed above, is in conflict with pandas.

The latter is an error because casting into a an integer array doesn't work, and so the indexer ends up not knowing what to do.

**Expected behavior**

I'm not sure, the implicit casting to integers for iloc-based indexing of an object that might well _not_ contain integers feels like an accident of pandas history. The pandas documentation [says (of `iloc` indexing)](https://pandas.pydata.org/docs/dev/user_guide/indexing.html):

> The .iloc attribute is the primary access method. The following are valid inputs:
> [...]
> -    A list or array of integers [4, 3, 0].

I think a categorical is _not_ a list of integers, so this should be a `TypeError`, but it just happens to work because `np.asarray(whatever).astype(int)` works as long as `whatever` is coercible to int (this is _broad_ e.g. `f.iloc[[1.5]]` works!?).

@mroeschke do you happen to know if `iloc`-based indexing with categoricals is "definitely supported" or "accident of history"?

**Comment by mroeschke** [comment]
> do you happen to know if iloc-based indexing with categoricals is "definitely supported" or "accident of history"?

`pd.Categorical` is "array-like" so I would expect a `pd.Categorical` of integers to work in `iloc` in pandas

**Comment by wence-** [comment]
Thanks!

**Comment by wence-** [comment]
> `pd.Categorical` is "array-like" so I would expect a `pd.Categorical` of integers to work in `iloc` in pandas

What about a categorical of floats?

```
import pandas as pd
s = pd.Series([0, 1, 2])
s.iloc[pd.Categorical([1.5])]
# => 1 1
```
