### ISSUE TITLE
[BUG] estimated result size is not correct.

### ISSUE THREAD

**Issue by JinHai-CN** [rapidsai/cudf#1302]
When I checked the join function code, I found following facts. I don't if it is a fault.
Code logic is as following:
Assume probe_to_build_ratio == 4, which is not large than MAX_RATIO(5)

probe_table_num_rows will be used as the sample_probe_num_rows.

But after calling compute_join_output_size function, d_size_estimate is calculated. h_size_estimate still equals *d_size_estimate * probe_to_build_ratio. In current situation, d_size_estimate already represent the real result size which shouldn't multiply probe_to_build_ratio any more.

**Comment by harrism** [comment]
@nsakharnykh can you take a look? @JinHai-CN it would help to include links to the code you are referring to.

Thanks!

**Comment by jrhemstad** [comment]
Aha, good find @JinHai-CN!

You are correct, the current `estimate_join_output_size` function will return an output size much larger than necessary for some cases.

The offending line is here: https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/join/join_compute_api.h#L149

If the `probe_to_build_ratio <= MAX_RATIO`, then we should not be multiplying `*d_size_estimate`  by `probe_to_build_ratio`.

**Comment by JinHai-CN** [comment]
@jrhemstad I would like to work on this issue. Is this OK for you?

**Comment by jrhemstad** [comment]
> @jrhemstad I would like to work on this issue. Is this OK for you?

Absolutely! I'll never turn down an offer for help.

**Comment by JinHai-CN** [comment]
#1451
