### ISSUE TITLE
[FEA] Performance issue with the Parquet reader for very large schemas (especially when containing strings)

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#13024]
For parquet files that contain very large schemas with strings (either large numbers of columns, or large numbers of nested columns) we pay a very heavy price postprocessing the string data after the core decode kernels runs.  

Essentially, the "decode" process for strings is just emitting a large array of pointer/size pairs that are then passed to other cudf functions to reconstruct actual columns.    The problem is that we are doing this with no batching - each output string column results in an entire cudf function call (`make_strings_column`) with multiple internal kernel calls each.  In situations with thousands of columns, this gets very expensive.

![image](https://user-images.githubusercontent.com/56695930/228312025-67ea3177-9d67-4e84-84e5-cb317c895001.png)

In the image above, the green span represents the time spent in the decode kernel and the time spent in all of the `make_strings_column` calls afterwards.  The time is totally dominated by the many many calls to `make_strings_column` (the red span).  

Ideally, we would have some kind of batched interface to `make_strings_column`  (`make_strings_columns` ?) that can do the work for the thousands of output columns coalesced into fewer kernels.  

On a related note, the area under the blue line represents a similar problem involving preprocessing the file (thousands of calls to `thrust::reduce` and `thrust::exclusive_scan_by_key`).   This has been largely addressed by this PR  https://github.com/rapidsai/cudf/pull/12931

**Comment by etseidl** [comment]
@nvdbaranec I'm curious if #13302 had any impact on the file used to generate the profile above.

**Comment by GregoryKimball** [comment]
@vuule recently conducted some experiments using an internal stream pool to hide latencies during column buffer allocation. Perhaps evaluating string types with larger column counts would show a bigger signal.

**Comment by mhaseeb123** [comment]
Investigated this issue by profiling the overhead of many `make_strings_columns` on `read_parquet` using a custom NVTX range. Observed that 1024 calls of `make_strings_column`s take roughly ~1.5ms to complete in the current state which seems negligible compared to the decode time (roughly 4ms for table size of 64MB across 1024 cols, 17ms for table size of 1GB across 1024 string cols and 178ms for table size of 12GB across 1024 string cols).

![Image](https://github.com/user-attachments/assets/600498d4-1c6c-400e-b57f-95a6ca2b4161)

In fact, using a stream pool of as less as 2 or 4 streams does not make any substantial improvement on `make_strings_column` time. Using a larger stream pool (1024 streams, 1 stream per col) adds significant overheads as shown below:

  ![Image](https://github.com/user-attachments/assets/3304a0a0-327c-400f-aa49-1a471e8543a6)

From the investigation and @etseidl's PR it seems like large number of `make_strings_column` calls is not a significant performance issue in `read_parquet` anymore. @GregoryKimball @nvdbaranec @vuule

**Comment by mhaseeb123** [comment]
Closing the issue based on above comment.
