### ISSUE TITLE
[BUG] GroupBy.apply() that involve reductions return index with wrong values

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#13037]
When the UDF passed to `groupby.apply()` involves a reduction, we return an incorrect index:

```python
In [16]: df = cudf.DataFrame({'a': [1, 1, 2, 2], 'b': [1, 2, 3, 4]})

In [17]: df.groupby('a').apply(lambda group: group.sum())
Out[17]: 
   a  b
a      
0  2  3
1  4  7
```

Pandas behavior:

```python
In [18]: df.to_pandas().groupby('a').apply(lambda group: group.sum())
Out[18]: 
   a  b
a      
1  2  3
2  4  7
```

**Comment by shwina** [comment]
As a note, just changing the data here:

https://github.com/rapidsai/cudf/blob/173fde9d9ae335014a1aa6de60b417f6f245dcf2/python/cudf/cudf/tests/test_groupby.py#L1958

to:

```python
{"key": [3, 3, 1, 1, 2, 2, 2], "val": [0, 1, 2, 3, 4, 5, 6]} 
```

will fail the unit test.

**Comment by shwina** [comment]
@brandon-b-miller do you think this is a safe assumption (at least given the current state and features we support in groupby-apply):

> if the size of the result is the same as the number of unique keys, we can return the unique keys in sorted order as the index

**Comment by brandon-b-miller** [comment]
I'd say that if the result of applying the function to a single group is a scalar, then we can take the unique keys to be the index, but I don't think we make any guarantees that the ordering of those keys matches pandas - just that they're the same set of values overall. 

I can look into addressing this as part of my fix for https://github.com/rapidsai/cudf/issues/12987 as there seem to be several issues with the same section of code that all have to do with inspecting the output of our iterative groupby process to determine what kind of output object to assemble and what to do with it's index.

**Comment by shwina** [comment]
Okay -- thank you! I reassigned to you if that's ok
