### ISSUE TITLE
[DISCUSSION] Better column abstraction in libcudf

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1304]
Creating an issue to make sure there's visibility, @jrhemstad has created a gist capturing some of his initial thoughts: https://gist.github.com/jrhemstad/581eb1a7b56673bad7da64dab7b5a724

**Comment by eyalroz** [comment]
An initial rejoinder to the linked-to gist: [here](https://gist.github.com/eyalroz/5bec0f4de53781c7599ad61e0c0e0d60).

It is half-finished. That is, the rejoinder-y part of it is done, but I intend to complete it with a sketch of proposal of my own regarding what `cudf::column` should be.

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/rapidsai/cudf/issues/1443
