### ISSUE TITLE
[BUG] Constructing from an unbound sequence doesn't raise/hangs

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#13049]
The following snippet never completes:

```python
In [1]: import cudf
In [2]: class A:
   ...:     def __getitem__(self, key):
   ...:         return 3
   ...: 
In [3] cudf.Series(A())
```

In Pandas, a Series of object data type is returned:

```python
In [4]: pd.Series(A())
Out[4]: 
0    <__main__.A object at 0x7f0a946afd90>
dtype: object
```

At the very least, I think cuDF should be able to detect and raise (`ValueError`) in this pathological case.

**Comment by bdice** [comment]
Is the title of this issue accurate? Unbound sequences also cause pandas to fail:

```python
import pandas as pd

def count_forever():
    i = 1
    while True:
        yield i
        i +=1

pd.Series(count_forever())  # Does not return.
```

I believe this is actually a special case where `__getitem__` is being called by cudf but not pandas, which simply uses the object value as a singleton item in the same way as `pd.Series(3)` returns the same as `pd.Series([3])`.

**Comment by shwina** [comment]
Thanks, @bdice. Happy to chnage the title to something else. I used "unbound sequence" loosely here to refer to an object that is effectively a `Sequence` minus `__len__`.

**Comment by bdice** [comment]
I think the issue is a bit similar to #13056. I think this should be treated as an issue with constructing a Series from a scalar (here, the scalar is an instance of an object that defines getitem!) and not an issue with unbound data. Here, the getitem method should never be called and we should error at the point that instances of A have no supported GPU dtype.

**Comment by shwina** [comment]
> I don’t think we must be any smarter than pandas at this task.

This is the problem :( Pandas _does_ return here. And since we cannot, we should probably raise.

**Comment by bdice** [comment]
Yes. And it’s an “incompatible type” error, not an “unbound sequence” error.

**Comment by bdice** [comment]
I discussed offline with @shwina. We concluded we should check that the input passes `isinstance(x, Iterable) or isinstance(x, Sequence)` before passing to pyarrow. We also found a bug in PyArrow which I reported upstream: https://github.com/apache/arrow/issues/34944
