### ISSUE TITLE
CuDF does not compile on gcc-11 (calling a __host__ function from a __host__ __device__ function is not allowed)

### ISSUE THREAD

**Issue by izoiluzja** [rapidsai/cudf#13051]
We are trying to compile cuDF with gcc-11 on GNU/Linux using a fresh checkout of CuDF from github and the provided build script.

Build command:
`./build.sh libcudf`

Compiler,
```
$gcc --version
gcc-11 (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
with
```
$ ./build.sh libcudf                                                                                                                                                                          
Building for the architecture of the GPU in the system...                                                                                                                                                          
-- The C compiler identification is GNU 11.1.0                                                                                                                                                                     
-- The CXX compiler identification is GNU 11.1.0                                                                                                                                                                   
-- The CUDA compiler identification is NVIDIA 11.5.119  

```
The build fails with the following  repeated error (see also title of issue),
```
[ 57%] Building CUDA object CMakeFiles/cudf.dir/src/io/orc/stripe_data.cu.o cudf/cpp/src/io/utilities/parsing_utils.cuh(240): error #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed 
```
We noted, that CuDF compiles in the same environment with gcc-9.

The complete build error is below.

`[ 57%] Building CUDA object CMakeFiles/cudf.dir/src/io/orc/stripe_data.cu.o /home/albert/cudf/cpp/src/io/utilities/parsing_utils.cuh(240): error #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed detected during: instantiation of "std::optional<T> cudf::io::parse_numeric<T,base>(const char *, const char *, const cudf::io::parse_options_view &) [with T=int8_t, base=16]" (579): here instantiation of "__nv_bool cudf::io::ConvertFunctor::operator()<T,<unnamed>>(const char *, const char *, void *, size_t, cudf::data_type, const cudf::io::parse_options_view &, __nv_bool) [with T=int 8_t, <unnamed>=(void *)nullptr]" /home/albert/cudf/cpp/include/cudf/utilities/type_dispatcher.hpp(446): here 1 error detected in the compilation of "/home/albert/cudf/cpp/src/io/csv/csv_gpu.cu". make[2]: *** [CMakeFiles/cudf.dir/build.make:1840: CMakeFiles/cudf.dir/src/io/csv/csv_gpu.cu.o] Error 1 make[2]: *** Waiting for unfinished jobs.... /home/albert/cudf/cpp/src/io/utilities/parsing_utils.cuh(240): error #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed detected during: instantiation of "std::optional<T> cudf::io::parse_numeric<T,base>(const char *, const char *, const cudf::io::parse_options_view &) [with T=int8_t, base=16]" (579): here instantiation of "__nv_bool cudf::io::ConvertFunctor::operator()<T,<unnamed>>(const char *, const char *, void *, size_t, cudf::data_type, const cudf::io::parse_options_view &, __nv_bool) [with T=int 8_t, <unnamed>=(void *)nullptr]" /home/albert/cudf/cpp/include/cudf/io/detail/data_casting.cuh(405): here instantiation of "std::unique_ptr<cudf::column, std::default_delete<cudf::column>> cudf::io::json::experimental::detail::parse_data(str_tuple_it, cudf::size_type, cudf::data_type, B &&, const cudf::i o::parse_options_view &, rmm::cuda_stream_view, rmm::mr::device_memory_resource *) [with str_tuple_it=thrust::pair<const char *, cudf::size_type> *, B=rmm::device_buffer]" /home/albert/cudf/cpp/src/io/json/json_column.cu(349): here 1 error detected in the compilation of "/home/albert/cudf/cpp/src/io/json/json_column.cu". make[2]: *** [CMakeFiles/cudf.dir/build.make:1910: CMakeFiles/cudf.dir/src/io/json/json_column.cu.o] Error 1 /home/albert/cudf/cpp/src/io/utilities/parsing_utils.cuh(240): error #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed detected during: instantiation of "std::optional<T> cudf::io::parse_numeric<T,base>(const char *, const char *, const cudf::io::parse_options_view &) [with T=int8_t, base=16]" (579): here instantiation of "__nv_bool cudf::io::ConvertFunctor::operator()<T,<unnamed>>(const char *, const char *, void *, size_t, cudf::data_type, const cudf::io::parse_options_view &, __nv_bool) [with T=int 8_t, <unnamed>=(void *)nullptr]" /home/albert/cudf/cpp/include/cudf/utilities/type_dispatcher.hpp(446): here 1 error detected in the compilation of "/home/albert/cudf/cpp/src/io/json/json_gpu.cu". make[2]: *** [CMakeFiles/cudf.dir/build.make:1924: CMakeFiles/cudf.dir/src/io/json/json_gpu.cu.o] Error 1 /home/albert/cudf/cpp/src/io/utilities/parsing_utils.cuh(240): error #20014-D: calling a __host__ function from a __host__ __device__ function is not allowed detected during: instantiation of "std::optional<T> cudf::io::parse_numeric<T,base>(const char *, const char *, const cudf::io::parse_options_view &) [with T=int8_t, base=16]" (579): here instantiation of "__nv_bool cudf::io::ConvertFunctor::operator()<T,<unnamed>>(const char *, const char *, void *, size_t, cudf::data_type, const cudf::io::parse_options_view &, __nv_bool) [with T=int 8_t, <unnamed>=(void *)nullptr]" /home/albert/cudf/cpp/include/cudf/io/detail/data_casting.cuh(405): here instantiation of "std::unique_ptr<cudf::column, std::default_delete<cudf::column>> cudf::io::json::experimental::detail::parse_data(str_tuple_it, cudf::size_type, cudf::data_type, B &&, const cudf::i o::parse_options_view &, rmm::cuda_stream_view, rmm::mr::device_memory_resource *) [with str_tuple_it=thrust::transform_iterator<lambda [](auto)->auto, thrust::zip_iterator<thrust::tuple<cudf::io::json::NodeInde xT *, cudf::io::json::NodeIndexT *, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type, thrust::null_type>>, thrust::use_default, thrust::use_default>, B=rmm::device_buffer]" /home/albert/cudf/cpp/src/io/json/nested_json_gpu.cu(1639): here 1 error detected in the compilation of "/home/albert/cudf/cpp/src/io/json/nested_json_gpu.cu". make[2]: *** [CMakeFiles/cudf.dir/build.make:1952: CMakeFiles/cudf.dir/src/io/json/nested_json_gpu.cu.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:643: CMakeFiles/cudf.dir/all] Error 2 make: *** [Makefile:156: all] Error 2`

**Comment by davidwendt** [comment]
I think there are issues with gcc-11 and CUDA 11.5.
Would you be willing to retry with CUDA 11.8?

**Comment by izoiluzja** [comment]
That may be the case. I can confirm that CuDF compiles with gcc-11 and CUDA 11.8. Thank you for the hint.

**Comment by davidwendt** [comment]
Closing as answered, but please feel free to reopen to continue the discussion.
