### ISSUE TITLE
[DOC] gdf_column doxygen should specify alignment constraints

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1305]
The doxygen comments on the fields: `size`, `data`, `valid` of `gdf_column` should specify their alignment behavior (not guaranteed to be aligned, 2-byte aligned, 4-byte aligned, whatever). The functions `gdf_column_view()`, `gdf_column_view_augmented()` should similarly specify alignment constraints on the arguments they combine into a column, in the doxygen comment.

**Comment by harrism** [comment]
Feel free to jump in and fix, @eyalroz

**Comment by eyalroz** [comment]
@harrism : This seems like a policy decision rather than just checking the state of the code at a given time. In fact, perhaps we have some code which makes assumptions it's not allowed to. I don't mind helping to check the code for compliance with the minimum acceptable allocation.
