### ISSUE TITLE
[BUG] Jetson Build

### ISSUE THREAD

**Issue by JasonAtNvidia** [rapidsai/cudf#1306]
**Describe the bug**
cuDF fails to build all on Jetson AGX

**Steps/Code to reproduce bug**
I have put the contents of the make command into bugfile.txt
error occured just by running make after successful cmake
[bugfile.txt](https://github.com/rapidsai/cudf/files/3015420/bugfile.txt)

**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of cuDF install:  from source
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
[environment.txt](https://github.com/rapidsai/cudf/files/3015429/environment.txt)

**Additional context**
Attempting to build RAPIDS for AGX product line

**Comment by andrewssobral** [comment]
I tried to compile cuDF (before compiling cuML) on my NVIDIA Jetson TX2, but it crashes.
I followed https://github.com/rapidsai/cudf/tree/master#development-setup
and tested with CXX11_ABI=ON and CXX11_ABI=OFF, but the errors are still the same.

```
andrews@jetsontx2:~/Projects/cudf/cpp/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX11_ABI=OFF
-- CUDF: Disabling the GLIBCXX11 ABI
-- ARROW: Disabling the GLIBCXX11 ABI
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrews/Projects/cudf/cpp/build/arrow
-- ARROW BUILD: Enabling Parallel CMake build with all threads
[ 12%] Performing update step for 'Arrow'
[ 25%] Performing configure step for 'Arrow'
-- Building using CMake version: 3.14.1
-- Arrow version: 0.12.1 (full: '0.12.1')
clang-tidy not found
clang-format not found
infer not found
-- Found cpplint executable at /home/andrews/Projects/cudf/cpp/build/arrow/arrow/cpp/build-support/cpplint.py
-- Compiler command: env LANG=C /usr/bin/c++ -v
-- Compiler version: Using built-in specs.
COLLECT_GCC=/usr/bin/c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib--enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)

-- Compiler id: GNU
Selected compiler gcc 7.3.0
Using optional gold linker (version 1.15)
Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
-- Build Type: DEBUG
-- BOOST_VERSION: 1.67.0
-- BROTLI_VERSION: v0.6.0
-- DOUBLE_CONVERSION_VERSION: v3.1.1
-- FLATBUFFERS_VERSION: 02a7807dd8d26f5668ffbbec0360dc107bbfabd5
-- GBENCHMARK_VERSION: v1.4.1
-- GFLAGS_VERSION: v2.2.0
-- GLOG_VERSION: v0.3.5
-- GRPC_VERSION: v1.14.1
-- GTEST_VERSION: 1.8.0
-- JEMALLOC_VERSION: 17c897976c60b0e6e4f4a365c751027244dada7a
-- LZ4_VERSION: v1.7.5
-- ORC_VERSION: 1.5.1
-- PROTOBUF_VERSION: v3.6.1
-- RAPIDJSON_VERSION: v1.1.0
-- RE2_VERSION: 2018-10-01
-- SNAPPY_VERSION: 1.1.3
-- THRIFT_VERSION: 0.11.0
-- ZLIB_VERSION: 1.2.8
-- ZSTD_VERSION: v1.3.7
-- Found pthread: /usr/lib/aarch64-linux-gnu/libpthread.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   regex
--   system
--   filesystem
-- Boost include dir: /usr/include
-- Boost libraries: /usr/lib/aarch64-linux-gnu/libboost_regex.so/usr/lib/aarch64-linux-gnu/libboost_system.so/usr/lib/aarch64-linux-gnu/libboost_filesystem.so
Added shared library dependency boost_system_shared: /usr/lib/aarch64-linux-gnu/libboost_system.so
Added shared library dependency boost_filesystem_shared: /usr/lib/aarch64-linux-gnu/libboost_filesystem.so
Added shared library dependency boost_regex_shared: /usr/lib/aarch64-linux-gnu/libboost_regex.so
Added static library dependency double-conversion_static: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/lib/libdouble-conversion.a
-- double-conversion include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/include
-- double-conversion static library: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/lib/libdouble-conversion.a
-- RapidJSON include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep/include
-- Flatbuffers include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/include
-- Flatbuffers compiler: /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/bin/flatc
-- Found hdfs.h at: /home/andrews/Projects/cudf/cpp/build/arrow/arrow/cpp/thirdparty/hadoop/include/hdfs.h
-- CMAKE_C_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -fuse-ld=gold -ggdb -O0   -Wall -march=armv8-a+crc
-- CMAKE_CXX_FLAGS:  -Wno-noexcept-type  -D_GLIBCXX_USE_CXX11_ABI=0 -fuse-ld=gold -ggdb -O0  -Wall -march=armv8-a+crc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/andrews/Projects/cudf/cpp/build/arrow/build
[ 37%] Performing build step for 'Arrow'
[  1%] Performing download step (download, verify and extract) for 'rapidjson_ep'
[  2%] Performing download step (download, verify and extract) for 'flatbuffers_ep'
[  3%] Performing download step (download, verify and extract) for 'double-conversion_ep'
CMake Error at double-conversion_ep-stamp/double-conversion_ep-download-DEBUG.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download-DEBUG-impl.cmake'

  See also

    /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download-*.log


CMakeFiles/double-conversion_ep.dir/build.make:93: recipe for target 'double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download' failed
make[5]: *** [double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download] Error 1
CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/double-conversion_ep.dir/all' failed
make[4]: *** [CMakeFiles/double-conversion_ep.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
CMake Error at flatbuffers_ep-stamp/flatbuffers_ep-download-DEBUG.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download-DEBUG-impl.cmake'

  See also

    /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download-*.log


CMake Error at rapidjson_ep-stamp/rapidjson_ep-download-DEBUG.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep-stamp/rapidjson_ep-download-DEBUG-impl.cmake'

  See also

    /home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep-stamp/rapidjson_ep-download-*.log


CMakeFiles/flatbuffers_ep.dir/build.make:93: recipe for target 'flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download' failed
CMakeFiles/rapidjson_ep.dir/build.make:93: recipe for target 'src/rapidjson_ep-stamp/rapidjson_ep-download' failed
make[5]: *** [src/rapidjson_ep-stamp/rapidjson_ep-download] Error 1
make[5]: *** [flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download] Error 1
CMakeFiles/Makefile2:279: recipe for target 'CMakeFiles/flatbuffers_ep.dir/all' failed
make[4]: *** [CMakeFiles/flatbuffers_ep.dir/all] Error 2
CMakeFiles/Makefile2:112: recipe for target 'CMakeFiles/rapidjson_ep.dir/all' failed
make[4]: *** [CMakeFiles/rapidjson_ep.dir/all] Error 2
Makefile:143: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/Arrow.dir/build.make:111: recipe for target 'Arrow-prefix/src/Arrow-stamp/Arrow-build' failed
make[2]: *** [Arrow-prefix/src/Arrow-stamp/Arrow-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Arrow.dir/all' failed
make[1]: *** [CMakeFiles/Arrow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
CMake Error at cmake/Modules/ConfigureArrow.cmake:69 (message):
  Building Arrow failed: 2
Call Stack (most recent call first):
  CMakeLists.txt:92 (include)


-- Configuring incomplete, errors occurred!
See also "/home/andrews/Projects/cudf/cpp/build/CMakeFiles/CMakeOutput.log".
andrews@jetsontx2:~/Projects/cudf/cpp/build$
```

**Comment by JasonAtNvidia** [comment]
> I tried to compile cuDF (before compiling cuML) on my NVIDIA Jetson TX2, but it crashes.
> I followed https://github.com/rapidsai/cudf/tree/master#development-setup
> and tested with CXX11_ABI=ON and CXX11_ABI=OFF, but the errors are still the same.
> 
> ```
> andrews@jetsontx2:~/Projects/cudf/cpp/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_CXX11_ABI=OFF
> -- CUDF: Disabling the GLIBCXX11 ABI
> -- ARROW: Disabling the GLIBCXX11 ABI
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/andrews/Projects/cudf/cpp/build/arrow
> -- ARROW BUILD: Enabling Parallel CMake build with all threads
> [ 12%] Performing update step for 'Arrow'
> [ 25%] Performing configure step for 'Arrow'
> -- Building using CMake version: 3.14.1
> -- Arrow version: 0.12.1 (full: '0.12.1')
> clang-tidy not found
> clang-format not found
> infer not found
> -- Found cpplint executable at /home/andrews/Projects/cudf/cpp/build/arrow/arrow/cpp/build-support/cpplint.py
> -- Compiler command: env LANG=C /usr/bin/c++ -v
> -- Compiler version: Using built-in specs.
> COLLECT_GCC=/usr/bin/c++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/7/lto-wrapper
> Target: aarch64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib--enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
> Thread model: posix
> gcc version 7.3.0 (Ubuntu/Linaro 7.3.0-27ubuntu1~18.04)
> 
> -- Compiler id: GNU
> Selected compiler gcc 7.3.0
> Using optional gold linker (version 1.15)
> Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
> -- Build Type: DEBUG
> -- BOOST_VERSION: 1.67.0
> -- BROTLI_VERSION: v0.6.0
> -- DOUBLE_CONVERSION_VERSION: v3.1.1
> -- FLATBUFFERS_VERSION: 02a7807dd8d26f5668ffbbec0360dc107bbfabd5
> -- GBENCHMARK_VERSION: v1.4.1
> -- GFLAGS_VERSION: v2.2.0
> -- GLOG_VERSION: v0.3.5
> -- GRPC_VERSION: v1.14.1
> -- GTEST_VERSION: 1.8.0
> -- JEMALLOC_VERSION: 17c897976c60b0e6e4f4a365c751027244dada7a
> -- LZ4_VERSION: v1.7.5
> -- ORC_VERSION: 1.5.1
> -- PROTOBUF_VERSION: v3.6.1
> -- RAPIDJSON_VERSION: v1.1.0
> -- RE2_VERSION: 2018-10-01
> -- SNAPPY_VERSION: 1.1.3
> -- THRIFT_VERSION: 0.11.0
> -- ZLIB_VERSION: 1.2.8
> -- ZSTD_VERSION: v1.3.7
> -- Found pthread: /usr/lib/aarch64-linux-gnu/libpthread.so
> -- Boost version: 1.65.1
> -- Found the following Boost libraries:
> --   regex
> --   system
> --   filesystem
> -- Boost include dir: /usr/include
> -- Boost libraries: /usr/lib/aarch64-linux-gnu/libboost_regex.so/usr/lib/aarch64-linux-gnu/libboost_system.so/usr/lib/aarch64-linux-gnu/libboost_filesystem.so
> Added shared library dependency boost_system_shared: /usr/lib/aarch64-linux-gnu/libboost_system.so
> Added shared library dependency boost_filesystem_shared: /usr/lib/aarch64-linux-gnu/libboost_filesystem.so
> Added shared library dependency boost_regex_shared: /usr/lib/aarch64-linux-gnu/libboost_regex.so
> Added static library dependency double-conversion_static: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/lib/libdouble-conversion.a
> -- double-conversion include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/include
> -- double-conversion static library: /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep/src/double-conversion_ep/lib/libdouble-conversion.a
> -- RapidJSON include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep/include
> -- Flatbuffers include dir: /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/include
> -- Flatbuffers compiler: /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/bin/flatc
> -- Found hdfs.h at: /home/andrews/Projects/cudf/cpp/build/arrow/arrow/cpp/thirdparty/hadoop/include/hdfs.h
> -- CMAKE_C_FLAGS:  -D_GLIBCXX_USE_CXX11_ABI=0 -fuse-ld=gold -ggdb -O0   -Wall -march=armv8-a+crc
> -- CMAKE_CXX_FLAGS:  -Wno-noexcept-type  -D_GLIBCXX_USE_CXX11_ABI=0 -fuse-ld=gold -ggdb -O0  -Wall -march=armv8-a+crc
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/andrews/Projects/cudf/cpp/build/arrow/build
> [ 37%] Performing build step for 'Arrow'
> [  1%] Performing download step (download, verify and extract) for 'rapidjson_ep'
> [  2%] Performing download step (download, verify and extract) for 'flatbuffers_ep'
> [  3%] Performing download step (download, verify and extract) for 'double-conversion_ep'
> CMake Error at double-conversion_ep-stamp/double-conversion_ep-download-DEBUG.cmake:49 (message):
>   Command failed: 1
> 
>    '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download-DEBUG-impl.cmake'
> 
>   See also
> 
>     /home/andrews/Projects/cudf/cpp/build/arrow/build/double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download-*.log
> 
> 
> CMakeFiles/double-conversion_ep.dir/build.make:93: recipe for target 'double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download' failed
> make[5]: *** [double-conversion_ep-prefix/src/double-conversion_ep-stamp/double-conversion_ep-download] Error 1
> CMakeFiles/Makefile2:75: recipe for target 'CMakeFiles/double-conversion_ep.dir/all' failed
> make[4]: *** [CMakeFiles/double-conversion_ep.dir/all] Error 2
> make[4]: *** Waiting for unfinished jobs....
> CMake Error at flatbuffers_ep-stamp/flatbuffers_ep-download-DEBUG.cmake:49 (message):
>   Command failed: 1
> 
>    '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download-DEBUG-impl.cmake'
> 
>   See also
> 
>     /home/andrews/Projects/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download-*.log
> 
> 
> CMake Error at rapidjson_ep-stamp/rapidjson_ep-download-DEBUG.cmake:49 (message):
>   Command failed: 1
> 
>    '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep-stamp/rapidjson_ep-download-DEBUG-impl.cmake'
> 
>   See also
> 
>     /home/andrews/Projects/cudf/cpp/build/arrow/build/src/rapidjson_ep-stamp/rapidjson_ep-download-*.log
> 
> 
> CMakeFiles/flatbuffers_ep.dir/build.make:93: recipe for target 'flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download' failed
> CMakeFiles/rapidjson_ep.dir/build.make:93: recipe for target 'src/rapidjson_ep-stamp/rapidjson_ep-download' failed
> make[5]: *** [src/rapidjson_ep-stamp/rapidjson_ep-download] Error 1
> make[5]: *** [flatbuffers_ep-prefix/src/flatbuffers_ep-stamp/flatbuffers_ep-download] Error 1
> CMakeFiles/Makefile2:279: recipe for target 'CMakeFiles/flatbuffers_ep.dir/all' failed
> make[4]: *** [CMakeFiles/flatbuffers_ep.dir/all] Error 2
> CMakeFiles/Makefile2:112: recipe for target 'CMakeFiles/rapidjson_ep.dir/all' failed
> make[4]: *** [CMakeFiles/rapidjson_ep.dir/all] Error 2
> Makefile:143: recipe for target 'all' failed
> make[3]: *** [all] Error 2
> CMakeFiles/Arrow.dir/build.make:111: recipe for target 'Arrow-prefix/src/Arrow-stamp/Arrow-build' failed
> make[2]: *** [Arrow-prefix/src/Arrow-stamp/Arrow-build] Error 2
> CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/Arrow.dir/all' failed
> make[1]: *** [CMakeFiles/Arrow.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2
> CMake Error at cmake/Modules/ConfigureArrow.cmake:69 (message):
>   Building Arrow failed: 2
> Call Stack (most recent call first):
>   CMakeLists.txt:92 (include)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/andrews/Projects/cudf/cpp/build/CMakeFiles/CMakeOutput.log".
> andrews@jetsontx2:~/Projects/cudf/cpp/build$
> ```

Your issue is not with cudf itself, your issue is you need to apt-get install libcurl4-openssl-dev before building CMake, then use the command ```./bootstrap --system-curl``` to allow CMake to use the system curl.

**Comment by andrewssobral** [comment]
Hi @JasonAtNvidia ,
Thanks a lot for your remark, now I am getting the following error:
```
andrews@jetsontx2:~/Projects/cudf/cpp/build$ make -j5
Scanning dependencies of target stringify
Scanning dependencies of target rmm
[  0%] Building CXX object CMakeFiles/stringify.dir/thirdparty/jitify/stringify.cpp.o
[  1%] Building CXX object rmm/CMakeFiles/rmm.dir/thirdparty/cnmem/src/cnmem.cpp.o
[  1%] Building CXX object rmm/CMakeFiles/rmm.dir/src/memory_manager.cpp.o
[  1%] Building CXX object rmm/CMakeFiles/rmm.dir/src/rmm.cpp.o
[  2%] Linking CXX executable stringify
[  2%] Built target stringify
Scanning dependencies of target stringify_run
[  3%] Run stringify on header types.h to convert it to c-str for use in JIT compiled code
[  3%] Built target stringify_run
[  4%] Linking CXX shared library librmm.so
[  4%] Built target rmm
Scanning dependencies of target random_allocate
Scanning dependencies of target cudf
Scanning dependencies of target RMM_TEST
[  4%] Building CXX object rmm/tests/CMakeFiles/random_allocate.dir/performance/random_allocate.cpp.o
[  4%] Building CXX object rmm/tests/CMakeFiles/RMM_TEST.dir/memory_tests.cpp.o
[  5%] Building CUDA object CMakeFiles/cudf.dir/src/comms/ipc/ipc.cu.o
[  6%] Building CXX object CMakeFiles/cudf.dir/src/dataframe/column.cpp.o
[  6%] Building CXX object CMakeFiles/cudf.dir/src/dataframe/context.cpp.o
[  7%] Building CXX object CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o
In file included from /home/andrews/Projects/cudf/cpp/src/dataframe/column.cpp:26:0:
/home/andrews/Projects/cudf/cpp/src/utilities/type_dispatcher.hpp:24:10: fatal error: nvstrings/NVStrings.h: No such file or directory
 #include <nvstrings/NVStrings.h>
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cudf.dir/build.make:75: recipe for target 'CMakeFiles/cudf.dir/src/dataframe/column.cpp.o' failed
make[2]: *** [CMakeFiles/cudf.dir/src/dataframe/column.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/andrews/Projects/cudf/cpp/src/string/nvcategory_util.cpp:5:10: fatal error: nvstrings/NVCategory.h: No such file or directory
 #include <nvstrings/NVCategory.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/cudf.dir/build.make:101: recipe for target 'CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o' failed
make[2]: *** [CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o] Error 1
[  8%] Linking CXX executable ../../bench/random_allocate
[  8%] Built target random_allocate
[  9%] Linking CXX executable ../../gtests/RMM_TEST
[  9%] Built target RMM_TEST
CMakeFiles/Makefile2:1002: recipe for target 'CMakeFiles/cudf.dir/all' failed
make[1]: *** [CMakeFiles/cudf.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
andrews@jetsontx2:~/Projects/cudf/cpp/build$
```
you know how to fix it?
you can find here (https://pastebin.com/raw/w542FNFy) the output of my Cmake.

**Comment by JasonAtNvidia** [comment]
> Hi @JasonAtNvidia ,
> Thanks a lot for your remark, now I am getting the following error:
> 
> ```
> andrews@jetsontx2:~/Projects/cudf/cpp/build$ make -j5
> Scanning dependencies of target stringify
> Scanning dependencies of target rmm
> [  0%] Building CXX object CMakeFiles/stringify.dir/thirdparty/jitify/stringify.cpp.o
> [  1%] Building CXX object rmm/CMakeFiles/rmm.dir/thirdparty/cnmem/src/cnmem.cpp.o
> [  1%] Building CXX object rmm/CMakeFiles/rmm.dir/src/memory_manager.cpp.o
> [  1%] Building CXX object rmm/CMakeFiles/rmm.dir/src/rmm.cpp.o
> [  2%] Linking CXX executable stringify
> [  2%] Built target stringify
> Scanning dependencies of target stringify_run
> [  3%] Run stringify on header types.h to convert it to c-str for use in JIT compiled code
> [  3%] Built target stringify_run
> [  4%] Linking CXX shared library librmm.so
> [  4%] Built target rmm
> Scanning dependencies of target random_allocate
> Scanning dependencies of target cudf
> Scanning dependencies of target RMM_TEST
> [  4%] Building CXX object rmm/tests/CMakeFiles/random_allocate.dir/performance/random_allocate.cpp.o
> [  4%] Building CXX object rmm/tests/CMakeFiles/RMM_TEST.dir/memory_tests.cpp.o
> [  5%] Building CUDA object CMakeFiles/cudf.dir/src/comms/ipc/ipc.cu.o
> [  6%] Building CXX object CMakeFiles/cudf.dir/src/dataframe/column.cpp.o
> [  6%] Building CXX object CMakeFiles/cudf.dir/src/dataframe/context.cpp.o
> [  7%] Building CXX object CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o
> In file included from /home/andrews/Projects/cudf/cpp/src/dataframe/column.cpp:26:0:
> /home/andrews/Projects/cudf/cpp/src/utilities/type_dispatcher.hpp:24:10: fatal error: nvstrings/NVStrings.h: No such file or directory
>  #include <nvstrings/NVStrings.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/cudf.dir/build.make:75: recipe for target 'CMakeFiles/cudf.dir/src/dataframe/column.cpp.o' failed
> make[2]: *** [CMakeFiles/cudf.dir/src/dataframe/column.cpp.o] Error 1
> make[2]: *** Waiting for unfinished jobs....
> /home/andrews/Projects/cudf/cpp/src/string/nvcategory_util.cpp:5:10: fatal error: nvstrings/NVCategory.h: No such file or directory
>  #include <nvstrings/NVCategory.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> CMakeFiles/cudf.dir/build.make:101: recipe for target 'CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o' failed
> make[2]: *** [CMakeFiles/cudf.dir/src/string/nvcategory_util.cpp.o] Error 1
> [  8%] Linking CXX executable ../../bench/random_allocate
> [  8%] Built target random_allocate
> [  9%] Linking CXX executable ../../gtests/RMM_TEST
> [  9%] Built target RMM_TEST
> CMakeFiles/Makefile2:1002: recipe for target 'CMakeFiles/cudf.dir/all' failed
> make[1]: *** [CMakeFiles/cudf.dir/all] Error 2
> Makefile:140: recipe for target 'all' failed
> make: *** [all] Error 2
> andrews@jetsontx2:~/Projects/cudf/cpp/build$
> ```
> you know how to fix it?
> you can find here (https://pastebin.com/raw/w542FNFy) the output of my Cmake.

You didn't build and install custrings (https://github.com/rapidsai/custrings) before building cudf.  You will also need to build Arrow from source, I'm still in the middle of trying to get that done correctly.

**Comment by kkraus14** [comment]
@JasonAtNvidia @andrewssobral is there any updates regarding this?

**Comment by victoraranda** [comment]
@JasonAtNvidia  @andrewsobral @kkraus14 ditto

**Comment by andrewssobral** [comment]
Hi @kkraus14 @victoraranda , from my side I paused my work on it, i will focus on this later. Maybe @JasonAtNvidia has some update?

**Comment by harrism** [comment]
I'm going to close this issue now since it is kind of a broad issue and out of date. @JasonAtNvidia please reopen any more specific issues as you find them.
