### ISSUE TITLE
[FEA] retrieve cudf::Table from a PyObject for pybind11 code

### ISSUE THREAD

**Issue by nwstephens** [rapidsai/cudf#13074]
Software integrator is looking for a method to retrieve cudf::Table from a PyObject, such that we can use it in our pybind11 code. These are similar to the two functions that pyarrow support, namely:

1. Unwrap and return the Arrow C++ [Table](https://arrow.apache.org/docs/cpp/api/table.html#_CPPv4N5arrow5TableE) pointer from obj: https://arrow.apache.org/docs/python/integration/extending.html#_CPPv4N5arrow5arrow2py12unwrap_tableEP8PyObject

2. Wrap the Arrow C++ table in a [pyarrow.Table](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table) instance: https://arrow.apache.org/docs/python/integration/extending.html#_CPPv4N5arrow5arrow2py10wrap_tableERKNSt10shared_ptrI5TableEE

**Comment by bdice** [comment]
Unfortunately this is pretty tricky. The Python `cudf.DataFrame` class doesn't _hold_ a `cudf::table_view`. There's not a clear "has-a" relationship, the columns of the DataFrame are independently managed The inheritance and memory management are structured a bit differently. You can learn more at the [Library Design page](https://docs.rapids.ai/api/cudf/nightly/developer_guide/library_design.html).

What is the Python object you're starting from? What exactly do you want to do with it? You could use cudf's Cython APIs directly, perhaps, though I don't think we guarantee any API stability at the Cython layer (only the Python APIs have stability and go through deprecation cycles). Also, interoperability between pybind11 and Cython is not straightforward ([reference](https://github.com/pybind/pybind11/issues/522)). You might be able to use pybind11 to wrap libcudf at the C++ level if you want to develop your own pybind11 bindings, but that could be a lot of work depending on how much API coverage you need.

**Comment by vyasr** [comment]
I believe that this is also something that the Morpheus team had some interest in, I believe @cwharris looked into it.

**Comment by shwina** [comment]
While it's true that there's no `table_view` sitting underneath a DataFrame, you could _construct_ a `table_view` from the PyObject by grabbing the data pointers from underneath it. I don't think it makes sense to create a `cudf::table` from a DataFrame though, as a `table` expects to own its memory while a DataFrame could consist of externally (e.g.., CuPy) allocated memory.

 cuDF supports the dataframe interchange protocol, an API that lets you get the data pointers out from underneath a DataFrame:

https://data-apis.org/dataframe-protocol/latest/API.html

**Comment by cwharris** [comment]
Morpheus uses pybind11 for most of our python bindings, but we make a special exception for interfacing with CUDF, where we use Cython to extract the underlying data from a DataDrame using CUDF's own utilities. It's not an elegant solution, but it works for our case so far.

https://github.com/nv-morpheus/Morpheus/blob/3fc48c09bb1382d2b958e619e2b6827a528635eb/morpheus/_lib/cudf_helpers.pyx

**Comment by nwstephens** [comment]
Thanks, @cwharris. This Cython solution unblocked this particular integration. I am curious to know if you have any thoughts on what a more `elegant solution` would look like should others encounter this issue.

**Comment by cwharris** [comment]
@nwstephens The relevant portions of CUDF are written in Cython, and so the only way to access the C++ objects utilized by Python are through Cython. If CUDF provided a way to share or release the underlying tables and column names from C++ this could lead to a more elegant solution, but libcudf has no concept of column names today, and that's not on the road map afaik.
