### ISSUE TITLE
[BUG] Constructing a DataFrame from numpy changes the locales' preferred encoding

### ISSUE THREAD

**Issue by dagardner-nv** [rapidsai/cudf#13085]
**Describe the bug**
Constructing a DataFrame from a multidimensional numpy (or cupy) array changes the locale's preferred encoding. Observed in versions 22.10 & 23.02 installed via conda.

**Steps/Code to reproduce bug**
```
import locale

import cudf
import numpy as np

data = np.array([[1, 0], [0, 1]])

print(locale.getpreferredencoding())
cdf = cudf.DataFrame(data)
print(locale.getpreferredencoding())
```

Output:
```
UTF-8
ANSI_X3.4-1968
```

**Expected behavior**
Don't change the locale

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
```
mamba create -n cudf_latest -c conda-forge -c rapidsai python=3.8 cudf=23.02
```

**Additional context**
n/a

**Comment by dagardner-nv** [comment]
New wrinkle to this bug, is that calling `cudf.DataFrame.to_cupy` or `cudf.Series.to_cupy` sometimes also changes the encoding (depending on the type) as does printing a cupy array:

```
import locale

import cudf

s = cudf.Series(range(10), dtype=cudf.dtype('int64'), name='a')

print(locale.getpreferredencoding()) # UTF-8

a = s.to_cupy()
print(locale.getpreferredencoding()) # ANSI_X3.4-1968
```


printing a cupy array
```
import locale

import cudf
import cupy as cp

cdf = cudf.DataFrame([[1, 0, 0, 0, 0],[0, 0, 0, 1, 0]])

print(locale.getpreferredencoding()) # UTF-8

cpa = cdf.to_cupy()

print(locale.getpreferredencoding()) # UTF-8

print(cpa)

print(locale.getpreferredencoding()) # ANSI_X3.4-1968
```

**Comment by bdice** [comment]
Closing this in favor of the cupy issue https://github.com/cupy/cupy/issues/7514 as this does not appear to be a bug in cudf. Please feel free to re-open if there is additional context. I don't think cudf can include any locale resetting logic without wrapping every cupy call which would have hefty costs in maintenance and performance.

**Comment by leofang** [comment]
This is not a CuPy bug, but an NVRTC one: nvbugs 3833924
