### ISSUE TITLE
[FEA] Attempt to JIT `GroupBy.apply` functions by default and fall back to iterative algorithm

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#13103]
With https://github.com/rapidsai/cudf/pull/11452 we introduced a framework for JIT compiling groupby UDFs with numba, along with the `GroupBy.apply` `engine='jit'` kwarg. This is an o.k. approach since generally we are alright with introducing things that are a superset of the Pandas API. 

Recently we've discussed changing things so that when a user uses `GroupBy.apply` we try and JIT the UDF first and if it doesn't work, then fall back to the iterative method. This would provide a unified API with less to learn for users and no wondering if the UDF conforms to the restrictions on JIT apply. It also provides an easier internal interface for features that build on top of `GroupBy.apply`, such as `filter`. However it introduces JIT overhead to workflows that ultimately won't even use it. This is not ideal, but iterative groupby apply is pretty slow already.

**Comment by vyasr** [comment]
I'm fine with introducing the extra overhead in the cases that won't JIT to help the cases that do JIT. We could mitigate the issue by introducing a new `engine='auto'` mode that does this, allowing users to opt into `engine='cudf'` if they know that they don't have a UDF that will compile successfully and want to avoid the overhead.

**Comment by brandon-b-miller** [comment]
So would `engine='auto'` be the default?

**Comment by vyasr** [comment]
I think so. If we wanted to err on the side of performance we could default to `jit`, but that seems likely to break many workflows.
