### ISSUE TITLE
[FEA] Do not depend on the internal implementation of `cuco::` maps for argument order

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#13116]
Look at this code, which is ugly IMO and is highly volatile:
 * https://github.com/rapidsai/cudf/blob/73c8d161718bf6d5aab0eb5fffb2958ae2997c2b/cpp/src/join/join_common_utils.cuh#L119-L125

In particular, it switches the order of the parameter `lhs` and `rhs` before passing them into `_check_row_equality`. This is because the comparator was constructed with `left_table` and `right_table` in the opposite order. Switching these table order may break code in some other places thus we have to rely on the code above to switch index order (`lhs` and `rhs`) instead. By doing so, we hope that the order of parameters (`lhs` and `rhs` indices) will match with the order of the comparing tables. There is not an easy way to verify if the index order matches with the table order with the current implementation.

However, such hack is not guaranteed to be working in the future. In fact, when the comparator is passed into `cuco::` map (and upcoming set) classes, we have to pray that `cuco::` will not switch the order of parameter it passes into row equality comparator. For example, this is one of those places that we wish that it will not be changed: https://github.com/NVIDIA/cuCollections/blob/dev/include/cuco/detail/static_map.inl#L537

In particular, the current code is `key_equal(existing_key, insert_pair.first)` which is not guaranteed to never be changed in the future. If it is changed to `key_equal(insert_pair.first, existing_key)` then we will have to fix all our code.

We should not rely on such code from an external dependency. There is a very simple way to enforce index order to be matched with table order: using strong index types. Although simple, it is not trivial since strong index types cannot be used for row hasher. However, workaround has already been implemented in https://github.com/rapidsai/cudf/pull/11330, using some additional strong index type adapters.

We should adopt such strong index type approach to enforce index order matching with table order, instead of rely on the order of comparator used in `cuco::` code.

**Comment by vyasr** [comment]
@PointKernel are we still doing this, or have the new cuco data structures insulated us from the ordering issues to any degree?

**Comment by PointKernel** [comment]
Great timing. The related cuco issue was just closed last week https://github.com/NVIDIA/cuCollections/issues/474.

We could close the current issue and use https://github.com/rapidsai/cudf/issues/12261 to track the whole hash join refactoring. The whole join code base will be rewritten so it will implicitly solve the problem.
