### ISSUE TITLE
Cython 3.0 update tasks

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#13114]
This issue tracks issues/work related to upgrading to Cython 3.0.

```[tasklist]
### Tasks
- [ ] Replace the use of custom `optional` bindings with upstream bindings (see https://github.com/cython/cython/issues/3293)
- [ ] Make use of first-class support for `enum class`
```

**Comment by vyasr** [comment]
Closing as stale. We've updated to Cython 3.0 and continue to make incremental changes to leverage more of its features (migrating C-style enums to C++ scoped enums is an ongoing task that we have been performing as different parts of cudf are migrated to pylibcudf).
