### ISSUE TITLE
[FEA] GPU enabled Folds (Fold-L and Fold-R)

### ISSUE THREAD

**Issue by joehoeller** [rapidsai/cudf#1315]
Fold-L/Fold-R (high order function): GPU enabled .map(), .reduce(), and .filter() functions avail to the Python API; must be composable [ f(g(x)) ] so it's underlying C++ code needs to be a functor.

FoldR Wiki:
https://en.wikipedia.org/wiki/Fold_(higher-order_function)

**Comment by harrism** [comment]
This is a very unclear feature request. What specifically are you asking for? Fold is a very broad concept. Please provide specific details and examples of what you would like to accomplish with cuDF that you can't today.

**Comment by joehoeller** [comment]
Something like this, but GPU enabled, with added folding types like map and filter:
https://pytorch.org/docs/stable/nn.html#torch.nn.Fold

**Comment by harrism** [comment]
Why not just use pytorch for this? Seems to be more of a tensor operation than a dataframe operation.

**Comment by harrism** [comment]
BTW, to the extent that a fold is a reduction, cuDF *does* support them.
