### ISSUE TITLE
[FEA] Use numba 0.57+ for CEC

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#13215]
When enabling CEC we should use the numba config option `CUDA_ENABLE_MINOR_VERSION_COMPATIBILITY` instead of patching the linker manually during cuDF import. This should allow us to set up the cuDF internals in such a way that they enable CEC when necessary for cuda <12.0, but still provide CEC for 12+.

**Comment by bdice** [comment]
@brandon-b-miller If you are able to attempt this with a pre-release of Numba 0.57 and draft a PR (even if only partially working), that'd be fantastic. Ideally we hope to move quickly on this once Numba 0.57 / CUDA 12 is available, so it does not push back CUDA 12 support for 23.06. Thanks so much.

**Comment by brandon-b-miller** [comment]
Roger that, I can aim to have cuDF building and passing tests with numba 0.57 before it's released.

**Comment by jakirkham** [comment]
FWIW Numba 0.57.0rc1 packages are available:

* [`numba` channel on Anaconda.org]( https://anaconda.org/numba/numba/files?version=0.57.0rc1 )
* [On PyPI (using `--pre`)]( https://pypi.org/project/numba/0.57.0rc1/ )

Other relevant information may be found in the 0.57.0rc1 issue ( https://github.com/numba/numba/issues/8841 )

**Comment by jakirkham** [comment]
Is there anything else needed here or is this good to close?

**Comment by brandon-b-miller** [comment]
Nope this should be all done!

**Comment by jakirkham** [comment]
Thanks Brandon! 🙏
