### ISSUE TITLE
[DOC] missing dropdown element with 0.6 version

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1323]
## Report incorrect documentation
Hi, 

I have reached to this page: https://docs.rapids.ai/api/cudf/stable/

Then, I use the dropdown on the top right side of the page to read the 0.5 API. After that,  I cannot return to the current version (0.6) without leaving that page.

I think it is missing an element in the dropdown, which links to the latest version.

![image](https://user-images.githubusercontent.com/26169771/55361887-c073e280-54d8-11e9-8281-b346bc5bc66a.png)

Finally, there is also a link to nvStrings v0.2 element in the dropdown, which I am not sure if it should be there.

**Location of incorrect documentation**
Provide links and line numbers if applicable.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by harrism** [comment]
This issue belongs on a different repo: https://github.com/rapidsai/docs

**Comment by miguelangel** [comment]
Hi @harrism,

My bad. Closing now.

For reference, I have just opened this same issue in the repository you mention above.

https://github.com/rapidsai/docs/issues/6
