### ISSUE TITLE
[FEA] Return compression statistics from ORC and Parquet writers

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#13252]
In ORC and Parquet writers, compression is performed separately on many data blocks. If compression fails for some of these blocks, writers output such blocks as uncompressed data, instead of throwing an exception (ORC does throw in some cases).
This may lead to unexpectedly large files. Currently there is no transparency into this process so it's hard for users to understand the resulting file size.

The proposal is to add 
```
struct writer_compression_statistics{
  size_t compressed_num_bytes;
  size_t failed_num_bytes;
  size_t skipped_num_bytes;
  double effective_compression_ratio;
};
```
Users can pass a shared pointer to a `writer_compression_statistics` object as an option to a writer. Once writing is complete, this object will the populated by the writer.

Benefits of this approach over returning `writer_compression_statistics` object directly from `write_xyz`: no API break, and no overhead in the writer when the feature is not used.
```[tasklist]
### Tasks
- [x] Main PR: https://github.com/rapidsai/cudf/pull/13294
- [ ] JNI work
```

**Comment by jlowe** [comment]
This looks good to me, although it would be nice to further specify when these are updated in a chunked writing scenario.  Are they updated after every chunked write operation, or only when the writer is closed?  In light of retry scenarios (see #13042), if updated on every chunked write it should only be done after all GPU memory operations have completed to avoid double-counting on retries.

**Comment by vuule** [comment]
@jlowe That's a good point. Would updating after each chunked write be useful? I don't think it would complicate the implementation significantly.

**Comment by jlowe** [comment]
> Would updating after each chunked write be useful?

I don't think we would take advantage of that and would only be looking at these stats at the end of the write. It would be good to document whichever way it works so callers know when it's safe to examine them.

**Comment by vuule** [comment]
In the current implementation, a single statistics object can be reused in multiple write calls, but the updates are not thread-safe, so it should not be used concurrently.
@jlowe is this limitation relevant? If we made `writer_compression_statistics` thread-safe it could be safely used to gather statistics for the entire workflow.

**Comment by jlowe** [comment]
> In the current implementation, a single statistics object can be reused in multiple write calls, but the updates are not thread-safe, so it should not be used concurrently.

For our planned use-case, I don't think we're expecting to examine the statistics object until after the write completes successfully.  Even if we do examine it before the chunked write is fully complete, we would not examine the statistics in a separate thread from the one invoking the chunked write interface.  Assuming libcudf is not updating these stats in a separate CPU thread from the one invoking the chunked writer, the lack of thread safety seems like a non-issue for us at least.
