### ISSUE TITLE
[BUG] DataFrame iloc indexing is incorrect for repeated index entries in the "columns" part of the key

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#13266]
**Describe the bug**
```python
import cudf
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(4).reshape(2, 2))
cdf = cudf.from_pandas(df)

df.iloc[:, [0, 1, 0]]
#    0  1  0
# 0  0  1  0
# 1  2  3  2

cdf.iloc[:, [0, 1, 0]]
#    0  1
# 0  0  1
# 1  2  3
```

This is because `ColumnAccessor.select_by_index` uniquifies input index arguments.

**Expected behavior**

This should match pandas.

**Comment by wence-** [comment]
This is probably a consequence of cudf not supporting duplicate column names:
```
pd.DataFrame(np.arange(4).reshape(2,2), columns=["a", "a"])
#    a  a
# 0  0  1
# 1  2  3
cudf.DataFrame(np.arange(4).reshape(2,2), columns=["a", "a"])
#    a
# 0  1
# 1  3
```

**Comment by mroeschke** [comment]
Looks you had "fixed" this in commit https://github.com/rapidsai/cudf/commit/e0ffbd72e92 by raising a ValueError. (I'll open a separate issue for cudf to support duplicate labels) so closing this out
