### ISSUE TITLE
[BUG] DataFrame `loc` indexing is incorrect with repeated column labels.

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#13269]
**Describe the bug**

This is basically #13266 but for `loc`, I will fix it separately due to different code paths.

```python
import cudf
import pandas as pd
import numpy as np
df = pd.DataFrame(np.arange(4).reshape(2, 2))
cdf = cudf.from_pandas(df)

df.loc[:, [0, 1, 0]]
#    0  1  0
# 0  0  1  0
# 1  2  3  2

cdf.loc[:, [0, 1, 0]]
#    0  1
# 0  0  1
# 1  2  3
```

This is because `ColumnAccessor.select_by_label` uniquifies input label arguments.

**Expected behavior**

This should match pandas.

**Comment by wence-** [comment]
This is a consequence of #13273, and how it will be fixed depends on what we do there.

**Comment by mroeschke** [comment]
This was fixed by https://github.com/rapidsai/cudf/pull/16514 so closing
