### ISSUE TITLE
[BUG] dataframe construction silently drops data with duplicate column names

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#13273]
**Describe the bug**

In pandas, it is allowable to construct a dataframe where the same name is used for more than one of the columns (seems unlikely you would _want_ to do this, but OK).

In cudf, in contrast, duplicate column names are _not_ allowed. However, this restriction is only checked in a few APIs (`from_pandas` complains, for example, but `DataFrame.__init__` doesn't).

This is rather nefarious because operations succeed but silently drop data.

Example:
```python
import pandas as pd
import numpy as np
import cudf

df = pd.DataFrame(np.arange(4).reshape(2, 2), columns=["A", "A"])
assert df.sum().sum() == 6 # succeeds
cdf = cudf.DataFrame(np.arange(4).reshape(2, 2), columns=["A", "A"]) # succeeds, but throws away first column

assert cdf.sum().sum() == 6 # fails
cdf2 = cudf.from_pandas(df) # raises ValueError
```

**Expected behavior**

Either

1. Support this use case (probably a big job)
2. Raise `ValueError` in all cases (easier, minimal sufficient requirement for xdf).

**Comment by mroeschke** [comment]
Looks like option 2 was selected with commit https://github.com/rapidsai/cudf/commit/501736c0ae7 so closing
