### ISSUE TITLE
[BUG] Cannot read non-annotated fixed_len_byte_array data from Parquet as binary (string)

### ISSUE THREAD

**Issue by NVnavkumar** [rapidsai/cudf#13304]
**Describe the bug**
Parquet supports the `FIXED_LEN_BYTE_ARRAY` physical type in addition to the `BINARY` physical type (which is basically a variable length byte array). cuDF can currently read Decimals and other types which are stored as `FIXED_LEN_BYTE_ARRAY`, but can't read the FIXED_LEN_BYTE_ARRAY data as binary data (or string).  It should behave the same as `BINARY`.

Basically, this schema:

```
message table {
| required FIXED_LEN_BYTE_ARRAY(10) bin_test;
|}
```

should be handled the same as:

```
message table {
|    required BINARY bin_test;
|}
```

This is required for https://github.com/NVIDIA/spark-rapids/issues/7449

**Steps/Code to reproduce bug**
[flba_binary_parquet.zip](https://github.com/rapidsai/cudf/files/11409735/flba_binary_parquet.zip)

The attached parquet file has one row with the following schema:

```
message spark {
            |  required fixed_len_byte_array(5) a;
            |  required fixed_len_byte_array(5) b;
            |}
```

In cuDF Python:

```
>>> df = cudf.read_parquet("/tmp/flba_binary.parquet")
>>> df
  a b
0
```

**Expected behavior**

The output should be:

```
>>> df
       a      b
0  hello  there
```

**Environment overview (please complete the following information)**
 - Docker commands:
```
docker pull rapidsai/rapidsai-core-nightly:23.06-cuda11.8-runtime-ubuntu22.04-py3.10
docker run --gpus all --rm -it \
        --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 \
        -p 8888:8888 -p 8787:8787 -p 8786:8786 \
        rapidsai/rapidsai-core-nightly:23.06-cuda11.8-runtime-ubuntu22.04-py3.10
```
Ran `ipython` inside Docker container

**Comment by revans2** [comment]
I think this is a duplicate of https://github.com/rapidsai/cudf/issues/12590

**Comment by NVnavkumar** [comment]
Closing this as duplicate of #12590
