### ISSUE TITLE
[DOC] dask-cudf starter example on docs page fails

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#13309]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.

https://docs.rapids.ai/api/dask-cudf/nightly/

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

`ValueError` is thrown when running the starter script on dask_cudf docs page.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

Following this block:
```python
import dask
import dask.dataframe as dd

dask.config.set({"dataframe.backend": "cudf"})
# This gives us a cuDF-backed dataframe
df = dd.read_parquet("coords.parquet", ...)
```

Gives error
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 df = dd.read_parquet("coords.parquet")

File ~/compose/etc/conda/cuda_11.8.0/envs/rapids/lib/python3.10/site-packages/dask/backends.py:133, in CreationDispatch.register_inplace.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    131 @wraps(fn)
    132 def wrapper(*args, **kwargs):
--> 133     func = getattr(self, dispatch_name)
    134     try:
    135         return func(*args, **kwargs)

File ~/compose/etc/conda/cuda_11.8.0/envs/rapids/lib/python3.10/site-packages/dask/backends.py:152, in CreationDispatch.__getattr__(self, item)
    148 def __getattr__(self, item: str):
    149     """
    150     Return the appropriate attribute for the current backend
    151     """
--> 152     backend = self.dispatch(self.backend)
    153     return getattr(backend, item)

File ~/compose/etc/conda/cuda_11.8.0/envs/rapids/lib/python3.10/site-packages/dask/backends.py:101, in CreationDispatch.dispatch(self, backend)
     99 else:
    100     return impl
--> 101 raise ValueError(f"No backend dispatch registered for {backend}")

ValueError: No backend dispatch registered for cudf
```

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

I'm not an expert on this, but perhaps using `import dask_cudf; dask_cudf.read_parquet` should work?

**Comment by quasiben** [comment]
Can you report the versions of Dask, cuDF, and Dask-cuDF  you have installed ?

**Comment by isVoid** [comment]
Hmm, actually this error went away after I have purged an old version of `dask_cudf` on my machine. False alarm.
