### ISSUE TITLE
RAPIDS AI INSTALLATION FOR UBUNTU 22.04.2 LTS

### ISSUE THREAD

**Issue by Sudharshan96** [rapidsai/cudf#13356]
Greetings guys,

I have recently migrated to Ubuntu 22.04.2 LTS, I have doubt regarding installation of RAPIDS.

Currently in the RAPIDS documentation installation procedure is given only for Ubuntu 22.04 LTS, will the same installation procedure work for Ubuntu 22.04.2 LTS version as well.

Kindly assist me on this, your replies will be much obliged.

Regards,
Sudharshan.G

**Comment by Sudharshan96** [comment]
Greetings @shwina may I know if this installation command will work for CUDA 11.8

conda create -n rapids-23.04 -c rapidsai -c conda-forge -c nvidia  \
    cudf=23.04 cuml=23.04 cugraph=23.04 python=3.10 cudatoolkit=11.8
    dask-sql tensorflow pycaret dash

I have changed cudatoolkit with 11.8 version, I want to know if all the libraries cudf,cuml will work with cuda 11.8 version as well

**Comment by vyasr** [comment]
I'm very sorry that your last question here never received a response. Yes, that command above ought to work. If you want the most updated commands, please use our [install selector](https://docs.rapids.ai/install), which should generate them for you. I'm going to close this issue as it is now very stale, but feel free to reopen if you still have questions.
