### ISSUE TITLE
[BUG]filter test perfroms wrong when GDF_LESS_THAN

### ISSUE THREAD

**Issue by StevenJoker** [rapidsai/cudf#1336]
**filter_ops.cu**
The comparison operations have bugs in the LESS_THAN condition, which makes it perform as same as the GREATER_THAN condition.

**Code to reproduce bug**
rapidsai/cudf/cpp/src/filter/filter_ops.cu: Line 62 &Line 72.
Both ">" should be "<".

**Expected behavior**
No mix between greater than and less than

**Comment by harrism** [comment]
@StevenJoker can you please use a GitHub link to the exact lines? Or provide a commit hash. Without a link or hash, we might not get the right version of the file. This code is undergoing change.

**Comment by StevenJoker** [comment]
https://github.com/rapidsai/cudf/blob/a369752366f0fd8bf73e5518bb00ec7bec2bc8bb/cpp/src/filter/filter_ops.cu#L62
and
https://github.com/rapidsai/cudf/blob/a369752366f0fd8bf73e5518bb00ec7bec2bc8bb/cpp/src/filter/filter_ops.cu#L72

**Comment by harrism** [comment]
Thanks @StevenJoker . filter_ops.cu is deleted by PR #1076 which is about to be merged. The functionality is replaced by binary operations. #892 has already been merged which implements that change. CC @devavret
