### ISSUE TITLE
[BUG] Remove `row_conversion.cu` from CUDF JNI

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#13374]
Depends on https://github.com/NVIDIA/spark-rapids-jni/issues/1149.

CUDF JNI has a `row_conversion.cu` that is likely cruft, and not used anywhere else. This was used at one point from [`spark-rapids`](https://github.com/NVIDIA/spark-rapids), but it has been replaced by the version of `row_conversion.cu` available in [`spark-rapids-jni`](https://github.com/NVIDIA/spark-rapids-jni/).

Once the differences between these have been [reviewed](https://github.com/NVIDIA/spark-rapids-jni/issues/1149), it should be safe to remove this from CUDF JNI.

**Comment by mythrocks** [comment]
(This should probably be left till the 23.08 release.)

**Comment by GregoryKimball** [comment]
Hey @mythrocks now that the cudf repo is in 23.08, is this worth revisiting?

**Comment by ttnghia** [comment]
Code was removed in https://github.com/rapidsai/cudf/pull/14664. Close this.
