### ISSUE TITLE
CUDA 11.8 and UBUNTU 23.04

### ISSUE THREAD

**Issue by Sudharshan96** [rapidsai/cudf#13377]
Greetings @shwina may I know if this installation command will work for CUDA 11.8 and Ubuntu 23.04

conda create -n rapids-23.04 -c rapidsai -c conda-forge -c nvidia
cudf=23.04 cuml=23.04 cugraph=23.04 python=3.10 cudatoolkit=11.8
dask-sql tensorflow pycaret dash

I have changed cudatoolkit with 11.8 version, I want to know if all the libraries cudf,cuml will work with cuda 11.8 version as well

**Comment by shwina** [comment]
Hi @Sudharshan96 - did you try it? If so, what results did you see?

**Comment by Sudharshan96** [comment]
Hi @shwina I will give a try in Ubuntu 23.04 OS with CUDA 11.8 and get back to you.

Is it possible for you to share any linkedin ID or instagram so that I can reach out to you, if you are ok.

**Comment by shwina** [comment]
You can reach out on our community slack: https://rapids-goai.slack.com/join/shared_invite/zt-trnsul8g-Sblci8dk6dIoEeGpoFcFOQ

**Comment by GregoryKimball** [comment]
Thank you @Sudharshan96 for sharing this issue. Please feel free to message our RAPIDS-GoAI slack as you test new installation commands.
