### ISSUE TITLE
[FEA] Support equality comparison on Strings

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#1337]
**Is your feature request related to a problem? Please describe.**
String binary/unary ops don't appear to be supported yet. Basic ones like `__eq__` are important for implementing string indexes, among other things.

In order to define a string index, I need a working equality operator. After implementing an equality operator for a basic unit test, I get GDF_UNSUPPORTED_DTYPE back from libgdf:

```
[Tue Apr  2 08:06:16 2019] Running: pytest -x cudf/tests/test_multiindex.py
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.3.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/nfs/tcomer/NVIDIA/cudf/python, inifile:
collected 11 items

cudf/tests/test_multiindex.py .....F

=================================== FAILURES ===================================
______________________________ test_string_index _______________________________

    def test_string_index():
        pdf = pd.DataFrame(np.random.rand(5, 5))
        gdf = cudf.from_pandas(pdf)
        stringIndex = ['a', 'b', 'c', 'd', 'e']
        pdf.index = stringIndex
>       gdf.index = stringIndex

cudf/tests/test_multiindex.py:93:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
cudf/dataframe/dataframe.py:660: in index
    self[k] = self[k].set_index(idx)
cudf/dataframe/dataframe.py:269: in __setitem__
    self._cols[name] = self._prepare_series_for_add(col)
cudf/dataframe/dataframe.py:798: in _prepare_series_for_add
    if forceindex or empty_index or self._index.equals(series.index):
cudf/dataframe/index.py:199: in equals
    return (self == other)._values.all()
cudf/dataframe/index.py:179: in __eq__
    return self._apply_op('__eq__', other)
cudf/dataframe/index.py:133: in _apply_op
    return as_index(op(other))
cudf/dataframe/series.py:518: in __eq__
    return self._unordered_compare(other, 'eq')
cudf/dataframe/series.py:502: in _unordered_compare
    outcol = self._column.unordered_compare(cmpops, other._column)
cudf/dataframe/string.py:549: in unordered_compare
    return string_column_binop(self, rhs, op=cmpop)
cudf/dataframe/string.py:567: in string_column_binop
    null_count = _gdf.apply_binaryop(_binary_impl[op], lhs, rhs, out)
cudf/_gdf.py:107: in apply_binaryop
    binop(*args)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<cdata 'struct gdf_column_ *' owning 56 bytes>, <cdata 'struct gdf_column_ *' owning 56 bytes>, <cdata 'struct gdf_column_ *' owning 56 bytes>)
errcode = 2, errname = 'GDF_UNSUPPORTED_DTYPE', msg = 'GDF_UNSUPPORTED_DTYPE'

    def wrap(*args):
        # covert errcode to exception
        errcode = fn(*args)
        if errcode != self._api.GDF_SUCCESS:
            errname, msg = self._get_error_msg(errcode)
>           raise GDFError(errname, msg)
E           libgdf_cffi.wrapper.GDFError: GDF_UNSUPPORTED_DTYPE

../cpp/build/python/libgdf_cffi/wrapper.py:27: GDFError
```

This error is much more easily reproduced with the following minimal reproducer:
``` python
import cudf
x = cudf.Series(['a', 'b', 'c'])
y = cudf.Series(['a', 'c', 'c'])
x == y
```
```output
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/dataframe.py", line 525, in __eq__
    return self._unordered_compare(other, 'eq')
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/dataframe.py", line 519, in _unordered_compare
    return self._call_op(other, '_unordered_compare', cmpops)
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/dataframe.py", line 443, in _call_op
    fn,
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/series.py", line 502, in _unordered_compare
    outcol = self._column.unordered_compare(cmpops, other._column)
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/string.py", line 549, in unordered_compare
    return string_column_binop(self, rhs, op=cmpop)
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/dataframe/string.py", line 567, in string_column_binop
    null_count = _gdf.apply_binaryop(_binary_impl[op], lhs, rhs, out)
  File "/home/nfs/tcomer/NVIDIA/cudf/python/cudf/_gdf.py", line 107, in apply_binaryop
    binop(*args)
  File "/home/nfs/tcomer/NVIDIA/cudf/cpp/build/python/libgdf_cffi/wrapper.py", line 27, in wrap
    raise GDFError(errname, msg)
libgdf_cffi.wrapper.GDFError: GDF_UNSUPPORTED_DTYPE

GDF_UNSUPPORTED_DTYPE
```

**Describe the solution you'd like**
This particular comparison should return a Series containing the comparison result of each pairwise string in the Series:

```
>>> x == y
0    True
1    False
2    True
dtype: bool
```

**Comment by felipeblazing** [comment]
https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/binary/binary_ops.cu#L256

This is the issue I am pretty certain. We need to add it to this macro. I don't know if other changes have to be made as well. It is just an int32 as far as logical ops are concerned.

**Comment by felipeblazing** [comment]
so
`#define DEF_LOGICAL_OP_NUM(F)                                                 \
gdf_error F##_generic(gdf_column *lhs, gdf_column *rhs, gdf_column *output) { \
    switch ( lhs->dtype ) {                                                   \
    case GDF_INT8:      return F##_i8(lhs, rhs, output);                      \
    case GDF_INT32:     return F##_i32(lhs, rhs, output);                     \
    case GDF_INT64:     return F##_i64(lhs, rhs, output);                     \
    case GDF_FLOAT32:   return F##_f32(lhs, rhs, output);                     \
    case GDF_FLOAT64:   return F##_f64(lhs, rhs, output);                     \
    case GDF_DATE32:    return F##_i32(lhs, rhs, output);                     \
    case GDF_DATE64:    return F##_i64(lhs, rhs, output);                     \
    case GDF_TIMESTAMP: return F##_i64(lhs, rhs, output);                     \
    default: return GDF_UNSUPPORTED_DTYPE;                                    \
    }                                                                         \
}
`
should be something like
`#define DEF_LOGICAL_OP_NUM(F)                                                 \
gdf_error F##_generic(gdf_column *lhs, gdf_column *rhs, gdf_column *output) { \
    switch ( lhs->dtype ) {                                                   \
    case GDF_INT8:      return F##_i8(lhs, rhs, output);                      \
    case GDF_STRING_CATEGORY:
    case GDF_INT32:     return F##_i32(lhs, rhs, output);                     \
    case GDF_INT64:     return F##_i64(lhs, rhs, output);                     \
    case GDF_FLOAT32:   return F##_f32(lhs, rhs, output);                     \
    case GDF_FLOAT64:   return F##_f64(lhs, rhs, output);                     \
    case GDF_DATE32:    return F##_i32(lhs, rhs, output);                     \
    case GDF_DATE64:    return F##_i64(lhs, rhs, output);                     \
    case GDF_TIMESTAMP: return F##_i64(lhs, rhs, output);                     \
    default: return GDF_UNSUPPORTED_DTYPE;                                    \
    }                                                                         \
}
`

**Comment by thomcom** [comment]
I will try to implement what you're proposing here into `binary_ops.cu` and `unary_ops.cu`

**Comment by thomcom** [comment]
No luck - I made the appropriate changes in `binary_ops.cu` and still get back `GDF_UNSUPPORTED_DTYPE`. In order to verify that the error was coming from a different place, I also modified each of those clauses (there were three, one for logical, one for bitwise, and one for arithmetic) to return `GDF_C_ERROR` instead of the original error, but that didn't work either. I'll leave it to the experts for now. :)

**Comment by thomcom** [comment]
@felipeblazing your first impression was the right one - I'm calling the `F##_generic` function now with GDF_STRING_CATEGORY. My above issue had to do with allocating an output buffer that wasn't `bool` dtype. Will update when that's resolved anyway. We need to have a conversation about how much to put into this for strings. I may create another issue for "support all ops on Strings" and mark this one resolved when I can simply for equality.

**Comment by harrism** [comment]
I would like @devavret involved in this issue and fix. He implemented the new binary ops functionality which I *thought* eliminated all that `F##_generic` stuff. (And if not, why not?) 

I want to make sure the fix is correct.
