### ISSUE TITLE
[QST] Error while performing factorize operation on cudf

### ISSUE THREAD

**Issue by ashish-kumar-hpe** [rapidsai/cudf#13400]
**What is your question?**

gdf = cudf.read_csv('./data/pop_2-02.csv', usecols=['easting', 'northing', 'county'])
print(gdf.dtypes)
gdf.shape

gdf.head()

gdf['county'], county_names = gdf['county'].factorize()
gdf.head()

county_map = dict(zip(list(county_names.index.to_arrow()), county_names.to_arrow()))
county_map[37]

At the last step i am getting error as below
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_452/3154154574.py in <module>
----> 7 county_map = dict(zip(list(county_names.index.to_arrow()), county_names.to_arrow()))
      8 county_map[37]

AttributeError: 'StringIndex' object has no attribute 'index'

**Comment by galipremsagar** [comment]
@ashish-kumar-hpe `factorize` returns an `Index` object at the second position, so you will need to change the following statement:
```
county_map = dict(zip(list(county_names.index.to_arrow()), county_names.to_arrow()))
```
to:
```
county_map = dict(zip(list(county_names.to_arrow()), county_names.to_arrow()))
```

Let me know if that resolves your issue.

**Comment by galipremsagar** [comment]
Given a sample series like the following:

```
In [2]: s = cudf.Series(['county1', 'county2', 'county3', 'county2', 'county1'])

In [9]: s
Out[9]: 
0    county1
1    county2
2    county3
3    county2
4    county1
dtype: object

In [11]: ids, names = s.factorize()

In [12]: ids
Out[12]: array([0, 1, 2, 1, 0], dtype=int8)

In [13]: names
Out[13]: StringIndex(['county1' 'county2' 'county3'], dtype='object')
```

Do you want to construct a dict of names to id's location mapping like:
```
{'county1': [0, 4], 'county2':[1, 3], ....}
```
or
id's to names like: 
```
{0:'county1', 1: 'county2', ...}
```
?

**Comment by ashish-kumar-hpe** [comment]
I want to construct the dictionary of ids-to-names mapping like ...
{0:'county1', 1: 'county2', ...}

**Comment by galipremsagar** [comment]
You could do:
```python
In [22]: dict(zip(range(len(names)), names.to_arrow().tolist()))
Out[22]: {0: 'county1', 1: 'county2', 2: 'county3'}
```

**Comment by bdice** [comment]
Looks like this is solved, so I will close it. Thanks @ashish-kumar-hpe and @galipremsagar!
