### ISSUE TITLE
[QST] regarding usage of libgdf_cffi, libgdf 

### ISSUE THREAD

**Issue by pradghos** [rapidsai/cudf#1341]
**What is your question?**

Latest `cuDF` version is having dependent packages which are renamed to `libcudf` and `libcudf_cffi`. However, `import  libgdf_cffi` , `from libgdf_cffi import libgdf` are still being used. 
is there any plan to change `import  libgdf_cffi` to `import  libcudf_cffi` and same for `from libgdf_cffi import libgdf` to `from libcudf_cffi import libcudf` ? Thank you ! 

`Location referred : https://github.com/rapidsai/cudf/tree/branch-0.7/conda/recipes`

**Comment by jrhemstad** [comment]
I think this will be irrelevant after https://github.com/rapidsai/cudf/issues/599 is completed for 0.7 as CFFI will be completely removed.

**Comment by pradghos** [comment]
@jrhemstad Okay ! Thanks for the information !

**Comment by pradghos** [comment]
@jrhemstad There are useful changes coming in `v0.7.0` . is there any tentative release date for `cudF v0.7.0` ? not sure if this is the correct forum to ask.

**Comment by harrism** [comment]
Mid-may.

**Comment by pradghos** [comment]
@harrism Thanks for the information !
