### ISSUE TITLE
cudf and numba prblem initialization of _internal failed without raising an exception [BUG]

### ISSUE THREAD

**Issue by GBZH** [rapidsai/cudf#13413]
**Describe the bug**
On Ubuntu 22.04, I have just installed  Rapids AI using the latest anaconda version.
Everything looked successful, but when trying to import cudf in an ipython notebook (in vscode), I get an error message  related to numba: SystemError: initialization of _internal failed without raising an exception

**Full error message**
SystemError                               Traceback (most recent call last)
Cell In[1], line 41
     38 from scipy.special import iv
     40 import cupy as cp
---> 41 import cudf
     42 from cusignal import chirp, spectrogram
     43 import cusignal as csg

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/cudf/__init__.py:5](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/cudf/__init__.py:5)
      1 # Copyright (c) 2018-2023, NVIDIA CORPORATION.
      3 from cudf.utils.gpu_utils import validate_setup
----> 5 validate_setup()
      7 import cupy
      8 from numba import config as numba_config, cuda

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:95](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/cudf/utils/gpu_utils.py:95), in validate_setup()
     85     minor_version = getDeviceAttribute(
     86         cudaDeviceAttr.cudaDevAttrComputeCapabilityMinor, 0
     87     )
     88     warnings.warn(
     89         "A GPU with NVIDIA Pascal™ (Compute Capability 6.0) "
     90         "or newer architecture is required.\n"
     91         f"Detected GPU 0: {device_name}\n"
     92         f"Detected Compute Capability: {major_version}.{minor_version}"
     93     )
---> 95 cuda_runtime_version = runtimeGetVersion()
     97 if cuda_runtime_version < 11000:
     98     # Require CUDA Runtime version 11.0 or greater.
     99     major_version = cuda_runtime_version [/](https://file+.vscode-resource.vscode-cdn.net/)[/](https://file+.vscode-resource.vscode-cdn.net/) 1000

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/rmm/_cuda/gpu.py:86](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/rmm/_cuda/gpu.py:86), in runtimeGetVersion()
     76 """
     77 Returns the version number of the current CUDA Runtime instance.
     78 The version is returned as (1000 major + 10 minor). For example,
   (...)
     82 current limitations in cuda-python.
     83 """
     84 # TODO: Replace this with `cuda.cudart.cudaRuntimeGetVersion()` when the
     85 # limitation is fixed.
---> 86 import numba.cuda
     88 major, minor = numba.cuda.runtime.get_version()
     89 return major * 1000 + minor * 10

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/__init__.py:42](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/__init__.py:42)
     38 from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
     39                                    jit_module)
     41 # Re-export vectorize decorators and the thread layer querying function
---> 42 from numba.np.ufunc import (vectorize, guvectorize, threading_layer,
     43                             get_num_threads, set_num_threads,
     44                             set_parallel_chunksize, get_parallel_chunksize,
     45                             get_thread_id)
     47 # Re-export Numpy helpers
     48 from numba.np.numpy_support import carray, farray, from_dtype

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/np/ufunc/__init__.py:3](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/np/ufunc/__init__.py:3)
      1 # -*- coding: utf-8 -*-
----> 3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize
      4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One
      5 from numba.np.ufunc import _internal, array_exprs

File [/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/np/ufunc/decorators.py:3](https://file+.vscode-resource.vscode-cdn.net/data4/anaconda3/envs/rapids-23.06/lib/python3.10/site-packages/numba/np/ufunc/decorators.py:3)
      1 import inspect
----> 3 from numba.np.ufunc import _internal
      4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder
      6 from numba.core.registry import DelayedRegistry

SystemError: initialization of _internal failed without raising an exception

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: Ubuntu 22.04 LTS, 4 x nVidia V100 32 GB
 - Method of cuDF install: command generated and copied from https://docs.rapids.ai/install
 - conda create -n rapids-23.06 -c rapidsai-nightly -c conda-forge -c nvidia  \
    cusignal=23.06 cudf=23.06 cuspatial=23.06 cuxfilter=23.06 cucim=23.06 cugraph=23.06 cuml=23.06 python=3.10 cudatoolkit=11.8 \
    dask/label/dev::dask-sql jupyterlab dash graphistry
  

**Environment details**
numba version from conda list command is:
numba              conda-forge/linux-64::numba-0.56.4-py310h0e39c9b_1 
CUDA 11.8:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
Driver  Version: 530.30.02 
**Additional context**

**Comment by brandon-b-miller** [comment]
Hi @GBZH , what version of `numpy` are you using in the environment that reports this error?

**Comment by GBZH** [comment]
Hi, 

Currently, in the env using command mamba list, I get: 
numpy 1.23.5 py310h53a5b5f_0 conda-forge 

In fact I have tested many combinations for the installation: with anaconda, with libmamba in anaconda and then directly with mamba which is my last install with numpy 1.23.5, but I allways have the same behaviour with an error message related to numba when using anaconda and the following one related to pandas with freshh install of mamba after deleting anaconda: 

AttributeError Traceback (most recent call last) 
Cell In[1], line 41 
38 from scipy . special import iv 
40 import cupy as cp 
---> 41 import cudf 
42 from cusignal import chirp, spectrogram 
43 import cusignal as csg File [ https://file+.vscode-resource.vscode-cdn.net/data4/quemener/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/__init__.py:19 | /data4/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/__init__.py:19 ] 
16 from rmm . allocators . cupy import rmm_cupy_allocator 
17 from rmm . allocators . numba import RMMNumbaManager 
---> 19 from cudf import api, core, datasets, testing 
20 from cudf . api . extensions import ( 
21 register_dataframe_accessor, 
22 register_index_accessor, 
23 register_series_accessor, 
24 ) 
25 from cudf . api . types import dtype File [ https://file+.vscode-resource.vscode-cdn.net/data4/quemener/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/api/__init__.py:3 | /data4/ ] [ https://file+.vscode-resource.vscode-cdn.net/data4/quemener/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/api/__init__.py:3 | mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/api/__init__.py:3 ] 
1 # Copyright (c) 2021, NVIDIA CORPORATION. 
----> 3 from cudf . api import extensions, types 
5 __all__ = [ " extensions " , " types " ] File [ https://file+.vscode-resource.vscode-cdn.net/data4/quemener/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/api/types.py:464 | /data4/mambaforge/envs/rapids-23.06/lib/python3.10/site-packages/cudf/api/types.py:464 ] 
462 is_datetime64_ns_dtype = pd_types . is_datetime64_ns_dtype 
463 is_datetime64tz_dtype = pd_types . is_datetime64tz_dtype 
--> 464 is_extension_type = pd_types . is_extension_type 
465 is_extension_array_dtype = pd_types . is_extension_array_dtype 
466 is_int64_dtype = pd_types . is_int64_dtype 
AttributeError : module 'pandas.api.types' has no attribute 'is_extension_type' 

Please note that I am running my .ipynb in (vs)code, I have also reinitialized all the extensions several times just in case. 

Thanks a lot for your help.

**Comment by vyasr** [comment]
I'm very sorry that we never followed up here. I'm going to close this issue as stale, but if it is still reproducible in any environment feel free to reopen and ping us again.
