### ISSUE TITLE
[FEA] Sort-based group by with NULL support

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#1342]
NOTE: the solution to this issue is already being implemented. The PR will be submitted soon

**Is your feature request related to a problem? Please describe.**
I wish cudf would have a sort based group by. Sort based group by would allow for easier implementation of specific types of aggregations (such as count distinct) and should perform faster on data that is already sorted and produce groups that are already sorted.

**Describe the solution you'd like**
 This function should have NULL support and also support choosing to follow  Pandas like or SQL like group by conventions.

**Describe alternatives you've considered**
Right now the hash based group by does not provide NULL support and does not have support for COUNT DISTINCT

**Additional context**

**Comment by harrism** [comment]
We are in burn down so can't accept new PRs for 0.7. Moving to 0.8.
