### ISSUE TITLE
[FEA] Move `cudf::test::print` out of test into a public API

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#13450]
With the growth of libcudf development, there is also an increasing number of debugging tasks. Printing a column content is one of the useful debugging approaches. In cudf, we can easily call `cudf::test::print` for that purpose, but the downstream applications don't have access to such functionality in the C++ test module.

I propose to change the function `cudf::test::print` into a public API `cudf::print(column_view const&)` or `cudf::to_string(column_view const&)`.

**Comment by davidwendt** [comment]
I would rather consider a cmake compile option that links the `libcudftestutil.a` with `libcudf.so` such that you can use `cudf::test::print` within libcudf functions temporarily for development.
There is a bunch of code in `cudf::test::print` and I fear moving it to `cudf::print` would generate too many distracting requirements including scalability and performance. I feel it is a perfectly suited for debugging small test cases and would prefer it be maintained in `cudf::test`.

Another option is to use the CSV writer with a [`data_sink` that takes a `std::vector<char>`](https://github.com/rapidsai/cudf/blob/e01e497fe0d1f884ad2966497d1c5f3d6b5fc90b/cpp/include/cudf/io/types.hpp#L508). The CSV writer contains alot of specialized code to convert columns to strings and I would not want to duplicate it unnecessarily.

**Comment by ttnghia** [comment]
I have another idea: continue to keep `cudf::test::print` in the test framework but make that utility function independently compilable in a separate TU. When somebody needs to use it, they can manually change the cmake file to include such TU directly into libcudf.
