### ISSUE TITLE
thrust_create_target dependency

### ISSUE THREAD

**Issue by sononix** [rapidsai/cudf#13468]
I'm trying to build the basic example on ubuntu 20.04 > cuda 11.8 and having trouble in getting the example to compile, I had it working on an older install be for some reason Im getting the following error 

<code>
CMake Error at /usr/lib/cmake/cudf/cudf-config.cmake:178 (thrust_create_target):
  Unknown CMake command "thrust_create_target".
Call Stack (most recent call first):
  build/cmake/CPM_0.35.3.cmake:216 (find_package)
  build/cmake/CPM_0.35.3.cmake:273 (cpm_find_package)
  CMakeLists.txt:23 (CPMFindPackage)
</code>

Ive tried adding the library in the command line using 

<code>
cmake -S . -DThrust_DIR=/home/..../thrust/thrust/cmake -B build
</code>

and setting the dependence in the cmakefile but neither approaches seem to work 
<code>
set(Thrust_DIR /home/..../thrust/thrust/cmake) 
</code>

the full output to screen is 

<code>
sudo cmake -S . -B build
-- The CXX compiler identification is GNU 9.4.0
-- The CUDA compiler identification is NVIDIA 11.8.89
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Downloading CPM.cmake to /home/ms/CODE/NVIDIA/cudf/cpp/examples/basic/build/cmake/CPM_0.35.3.cmake
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.8.89") 
</code>

Ive managed to build cudf from source and thrust library from source on the box, but the thrust_create_target error has me stumped 
Anyone any idea to what might be causing the error

tks

**Comment by robertmaynard** [comment]
We don't support an external Thrust due to the patches we apply.

**Comment by sononix** [comment]
My bad I was missing an argument in the build.sh file for the CMAKE_CUDA_COMPILER - though I getting blocked on the linking not locating nvToolsExt - it appears it is needed in the strings example and is blocking the build process 

<code>
/usr/bin/ld: cannot find -lnvToolsExt
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/libcudf_apis.dir/build.make:100: libcudf_apis] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:89: CMakeFiles/libcudf_apis.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
</code>

should it not be installed along with cuda?

**Comment by vyasr** [comment]
Closing as stale. Feel free to reopen if needed.
