### ISSUE TITLE
[BUG] `single_lane_block_sum_reduce` is not data-race safe if called in a loop

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#13485]
**Describe the bug**

Determined as part of investigation in #13479.

`single_lane_block_sum_reduce` is as below:

https://github.com/rapidsai/cudf/blob/ebc68df255b9f304ee19b969645a10d5ab9f8bea/cpp/include/cudf/detail/utilities/cuda.cuh#L87-L109

The `__syncthreads` call on line 99 ensures that the write on line 98 happens-before the read on line 106.

However, if called more than once (for example in a loop), as occurs in `valid_if_n_kernel`:

https://github.com/rapidsai/cudf/blob/ebc68df255b9f304ee19b969645a10d5ab9f8bea/cpp/include/cudf/detail/valid_if.cuh#L154-L188

additional synchronisation is required to ensure the read on line 106 in iteration `i` happens-before the write in line 98 on iteration `i+1`. `valid_if_n_kernel` `__ballot_sync`s on every iteration, but I think this is only warp-level, rather than block-level synchronisation.

One fix would be to add an additional `__syncthreads` call to `single_lane_block_sum_reduce`. 
```diff
diff --git a/cpp/include/cudf/detail/utilities/cuda.cuh b/cpp/include/cudf/detail/utilities/cuda.cuh
index cdbc26701d..9085c97a46 100644
--- a/cpp/include/cudf/detail/utilities/cuda.cuh
+++ b/cpp/include/cudf/detail/utilities/cuda.cuh
@@ -94,6 +94,7 @@ __device__ T single_lane_block_sum_reduce(T lane_value)
   auto const warp_id{threadIdx.x / warp_size};
   __shared__ T lane_values[warp_size];
 
+  __syncthreads();
   // Load each lane's value into a shared memory array
   if (lane_id == leader_lane) { lane_values[warp_id] = lane_value; }
   __syncthreads();
```

But this may be overkill for the cases where it is not called repeatedly within the same kernel (at present, the only caller that does this is `valid_if_n_kernel`). So perhaps another approach is to `__syncthreads` there and add documentation that states the synchronisation conditions of `single_lane_block_some_reduce`.

Which do we prefer? Is this analysis correct?

**Comment by bdice** [comment]
I agree with this analysis. I think adding the `__syncthreads` as proposed above, while stricter than absolutely necessary, is the best way to go here. I don't want to add new requirements on the caller for the function to be safe, I'd rather fix the safety of the existing function.
