### ISSUE TITLE
[FEA] Slice and Split (Copying) 

### ISSUE THREAD

**Issue by ironbit** [rapidsai/cudf#1353]
**Is your feature request related to a problem? Please describe.**
For distribution requirements, it is needed to divide a whole column into multiple parts (split) and also it is needed to copy some ranges from a column (slice) into multiple output columns.

The problem arises in the copy process for the 'valid' field in the gdf_column structure. As an example, copy from the 5 index means that it is required to divide the first char of the valid field.

**Description Slice**
Slices a column (including null values) into a set of columns according to a set of indices.

The "slice" function divides part of the input column into multiple intervals of rows using the indices values and it stores the intervals into the output columns. Regarding the interval of indices, every two values are taken from the indices array. The pair of indices are left-closed and right-open.

Example

```
input: {10, 12, 14, 16, 18, 20, 22, 24, 26, 28}
indexes: {1, 3, 5, 9}
output: {{12, 14}, {20, 22, 24, 26}}
```

**Description Split**
Splits all the column (including null values) into a set of columns according to a set of indices.

The "split" function divides all the input column into multiple intervals of rows using the indices values and it stores the intervals into the output columns. Regarding the interval of indices, a pair of values are taken from the indices array in a consecutive manner. The pair of indices are left-closed and right-open. For the first pair, the function will take the value 0 and the first element of the indices array. For the last pair, the function will take the last element of the indices array and the size of the input column.

Example

```
input: {10, 12, 14, 16, 18, 20, 22, 24, 26, 28}
indexes: {2, 5, 9}
output: {{10, 12}, {14, 16, 18}, {20, 22, 24, 26}, {28}}
```

**Additional context**
The PR #1310  has been created with the implementation of those functionalities.

**Comment by harrism** [comment]
Fixed by #1310
