### ISSUE TITLE
[BUG] High memory usage with cudf::strings::contains_re

### ISSUE THREAD

**Issue by jihoonson** [rapidsai/cudf#13546]
**Describe the bug**

Hi all :wave: First of all, please correct me if I am using a wrong issue template. I was not 100% sure whether this is a question or a bug report. 

I was testing memory usage of `cudf::strings::contains_re` in libcudf, and noticed that its peak memory usage is much bigger than its input size. In my testing, its peak memory usage was 10 times bigger (2.1 GB) than its input (230 MB). Note that the input was a 25-byte long fixed-size string column. I understand that the regex processing may consume a large amount of memory, but was wondering whether this high memory consumption is expected. For comparison, I tested `cudf::strings::like` as well, which consumed only 330 MB for the same data.

**Steps/Code to reproduce bug**

A simple code to reproduce it.

```cpp
  std::vector<std::string> strings;
  for (size_t i = 0; i < num_rows; ++i) {
    strings.emplace_back("AAAAAAAAAAAAAAAAAAAABRASS");
  }

  cudf::strings_column_wrapper cudf_str(strings.begin(), strings.end());

  std::unique_ptr<cudf::strings::regex_program> regex_program = 
            cudf::strings::regex_program::create(regex);

  auto contains = cudf::strings::contains_re(cudf_str, *regex_program);
```

**Expected behavior**

I do not have any expectation, but was rather curious whether this much of memory consumption is expected.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda,

**Environment details**

I don't think that there is anything special with my environment setting. But please let me know if this can be useful.

**Comment by davidwendt** [comment]
Although the amount of memory needed to execute `contains_re` or any regex libcudf function is dependent on the number of strings it is also depends on the size of the regex pattern used for matching.  The regex state engine requires a certain amount of memory per regex _instruction_ which comes from processing the regex pattern. There really is no way around this. The implementation does attempt to throttle the working memory size if it gets too high by executing over batches of strings but there is no way to control this externally at this time since it would potentially degrade performance. So the large memory footprint is indeed expected.
Also, the working memory has no dependency on the size of each string.

**Comment by jihoonson** [comment]
@davidwendt thanks for your explanation. The regex pattern I used for my testing was `.*BRASS$`. So, if I correctly understand your explanation, the memory consumption would depend on the number of input strings, the number of regex instructions, and the size of the pattern, which are 10000000 rows, 1 instruction and a 8-bytes long pattern in this case, respectively. Is this correct? I'm still quite surprised that cudf would use that much amount of memory for this simple pattern. It is good to know that this is expected :slightly_smiling_face:

**Comment by jihoonson** [comment]
@davidwendt this is a great explanation. I appreciate it! I think now understand why it needs so much memory. The high memory consumption itself is not a problem for me. My question was more about whether this is expected, or some sort of bug caused by sub-optimal memory management. As long as it is expected, I could use this as a factor for rough memory consumption of my operator, so that I could do something to avoid OOM errors, such as splitting the input as you described or scheduling `condains_re` for later when there is enough room in the memory.

Thanks again for the explanation! I'm closing this issue now.

**Comment by davidwendt** [comment]
I would also like to point out that your pattern `.*BRASS$` is checking for the `BRASS` to appear at the end of the string. If would be more efficient and performant to use [`cudf::strings::ends_with`](https://docs.rapids.ai/api/libcudf/stable/group__strings__find.html#ga2f970e44f0f6cc7ff749d88aa81e6b44) instead for this.

There are many [`cudf::strings` APIs](https://docs.rapids.ai/api/libcudf/stable/group__strings__apis.html) and sometimes using multiple APIs could be more efficient than using the regex ones.

**Comment by jihoonson** [comment]
You are right. I don't have full context as I didn't write this code using `contains_re` in our code base, but was told that this code is a legacy code which was written a long time ago even before other cudf string matching APIs existed. `std::strings::like` perfectly fits for our case, so I fixed our code to use that API instead.
