### ISSUE TITLE
[BUG] Unexpected malformed parquet page data error when reading multiple parquet files using libcudf

### ISSUE THREAD

**Issue by jihoonson** [rapidsai/cudf#13559]
**Describe the bug**

I have two parquet files. These files can be read successfully with no issue when I read them one at a time. However, when I read them together using `cudf::io::read_parquet`, it fails with an error below.

```
CUDF failure at: /path/to/libcudf/cpp/src/io/parquet/reader_impl_preprocess.cu:1391: Encountered malformed parquet page data (row count mismatch in page data)
```

IIUC, this error means that some column has a different number of rows than other columns in the given files. However, I don't think that is the case because each file can be read individually with no issue.

This error occurs very rarely. I can reproduce it only when certain conditions are met:

- When you read certain files together
- When you read certain columns in a certain order. The column order should be different than the column definition order in the parquet file schema.

**Steps/Code to reproduce bug**

This error can be reproduced only with certain input files. Please find the files I've been using in https://drive.google.com/file/d/16VWhJu8q6eoUAM1h20eSqDkK4MZDJ_wP/view?usp=sharing (it's about 50 MB). In the data set shared, there are two parquet files of the TPC-H customer table. Once you download them, you can reproduce the error using the code below. You can copy-paste this test into `cudf/cpp/tests/io/parquet_test.cpp`.

Note that the column order matters to reproduce the error. The same files can be read successfully if you reverse the order to `{"c_phone", "c_acctbal"}`.

```cpp
#include <arrow/io/api.h>
#include <arrow/filesystem/localfs.h>

TEST_F(ParquetReaderTest, MalformedParquetPageDataError)
{
  std::vector<std::string> files = {"/path/to/customer/customer.8619.parquet", "/path/to/customer/customer.8881.parquet"};
  std::vector<std::string> cols = {"c_acctbal", "c_phone"};

  auto fs = std::make_shared<arrow::fs::LocalFileSystem>();
  std::vector<std::shared_ptr<arrow::io::RandomAccessFile>> arrow_files;
  for (const auto& f : files) {
    arrow_files.emplace_back(fs->OpenInputFile(f).ValueOrDie());
  }

  std::vector<cudf::io::arrow_io_source> arrow_sources;
  std::vector<cudf::io::datasource*> datasources;
  for (auto& file : arrow_files) {
    arrow_sources.emplace_back(cudf::io::arrow_io_source{std::move(file)});
  }
  for (auto& arrow_source : arrow_sources) {
    datasources.emplace_back(&arrow_source);
  }
  cudf::io::source_info source{datasources};

  cudf::io::parquet_reader_options read_opts =
      cudf::io::parquet_reader_options::builder(source)
        .use_pandas_metadata(false)
        .convert_strings_to_categories(false)
        .columns(cols);
  auto result = cudf::io::read_parquet(read_opts);
  fprintf(stderr, "%d\n", result.tbl->num_rows());
}
```

**Expected behavior**

Since those files are not malformed, `cudf::io::read_parquet` should not fail with this malformed page data error.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda and from source

**Libcudf version tested**

Only 23.04.0 is tested.

**Comment by etseidl** [comment]
Part of the problem seems to be [here](https://github.com/rapidsai/cudf/blob/c929a84719baf169d05e4d0ee87a0df6e77f5b45/cpp/src/io/parquet/reader_impl_preprocess.cu#L247), where the reader is trying to coalesce reads. The issue arises when the next chunk will come from a different file...the coalesced read will bring in garbage for the next chunk.  This test should include `chunk_source_map[chunk] != chunk_source_map[next_chunk]` to prevent this.
