### ISSUE TITLE
[BUG] The libcudf device atomic operations cause memcheck errors on types smaller than 4 bytes

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#13575]
The [`device_atomics`](https://github.com/rapidsai/cudf/blob/branch-23.08/cpp/include/cudf/detail/utilities/device_atomics.cuh) implementation in libcudf are failing memchecks when used on types smaller than 4 bytes.

https://github.com/rapidsai/cudf/blob/c929a84719baf169d05e4d0ee87a0df6e77f5b45/cpp/include/cudf/detail/utilities/device_atomics.cuh#L65-L69

This was found while investigating some memcheck errors that occurred on `cudf::reduce` where the aggregation return type is `bool` (1 byte) and an `atomicOr` was used to produce the output. Reference: https://github.com/rapidsai/cudf/pull/13574

The solution is to use the libcudaxx `cuda::atomic` and `cuda::atomic_ref` in place of these implementations and potentially remove the `device_atomics.cuh` altogether.

**Comment by PointKernel** [comment]
Depends on https://github.com/NVIDIA/libcudacxx/issues/496

**Comment by PointKernel** [comment]
Update: `atomic_ref` is limited to hardware-supported types, so it doesn't work properly with types like booleans, timestamps, and durations. As a result, we can't fully eliminate `device_atomics.cuh`. This issue should be addressed alternatively.

**Comment by davidwendt** [comment]
Closed by https://github.com/rapidsai/cudf/pull/13583 and https://github.com/NVIDIA/cccl/issues/1024
