### ISSUE TITLE
[BUG] Device atomics missing atomicOr and atomicAnd

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1357]
**Describe the bug**
Recently merged PR #1194 added overloads for most CUDA device atomics for cuDF data types. But atomicOr and atomicAnd were missed -- these are important for valid bit mask manipulation in kernels.

We should add these. 

Also, I believe most of the atomics added missed unsigned data types. E.g. `uint8_t` (the underlying type of `gdf_valid_type`), `uint16_t`, etc.

Note that I don't think it's appropriate to add overloads for atomicOr and atomicAnd for non-integral types. I think we should just have int and uint 8, 16, 32, and 64.

**Comment by kovaltan** [comment]
Shall I also add `atomicXor` ?
