### ISSUE TITLE
[BUG] cudaErrorIllegalAddress on distinct_count and nunique for reduce

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#13576]
**Describe the bug**
I recently needed to get an approximate distinct count for a dynamic optimization I was doing in Spark.  As a part of this I tried to use nunique as a reduce aggregation and ran into cudaErrorIllegalAddress on anything more complicated than some very basic types. I then tried to use distinct_count for the same thing, because I wanted the result on the CPU and this made it very simple to do, but I hit the same problem.
 
**Steps/Code to reproduce bug**
I was doing a test with TPCDS data and the keys to various hash aggregates, but I also saw it in a few unit tests.  Generally the rule that I found, but don't really trust is that anything with more than one column in it or any value that is larger than 64-bits. So strings cause this, structs cause this, tables with more than one column has this show up.  Decimal_128 causes this.  Lots of things, but here is one example test that I wrote that also causes it to crash.

```
TEST_F(DistinctCount, SimpleStruct)
{
//            .column(5, 3, 3, 1, 1)
//            .column(5, 3, null, null, 5)
//            .column(1, 3, 5, 7, 9)

    auto a  = cudf::test::fixed_width_column_wrapper<int32_t>{5, 3, 3, 1, 1};
    auto b  = cudf::test::fixed_width_column_wrapper<int32_t>({5, 3, XXX, XXX, 5}, nulls_at({2, 3}));
    auto c  = cudf::test::fixed_width_column_wrapper<int32_t>{1, 3, 5, 7, 9};

    cudf::table_view input_table({a, b, c});
    cudf::distinct_count(input_table);
}
```

I am happy to provide more data that causes crashes if people want me to. In the short term I have worked around the issue by hashing the row before sending it to distinct_count, because all I really care about is an approximate count, not an exact one. But I don't want to put anything into production until this gets fixed.

I did run compute sanitizer on the failing test and got back a lot of issues, but this is the first one

```
========= Invalid __global__ read of size 4 bytes
=========     at 0x170 in void cuco::experimental::detail::insert_if_n<(int)1, (int)128, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, cudf::detail::row_validity, cuda::__4::atomic<unsigned long, (cuda::std::__4::__detail::thread_scope)1>, cuco::experimental::static_set_ref<int, (cuda::std::__4::__detail::thread_scope)1, cudf::experimental::row::equality::device_row_comparator<(bool)0, cudf::nullate::DYNAMIC, cudf::experimental::row::equality::nan_equal_physical_equality_comparator>, cuco::experimental::linear_probing<(int)1, const cudf::detail::experimental::compaction_hash<cudf::experimental::row::hash::device_row_hasher<cudf::detail::default_hash, cudf::nullate::DYNAMIC>>>, cuco::experimental::detail::aow_storage_ref<(int)1, int, cuco::experimental::extent<unsigned long, (unsigned long)18446744073709551615>>, cuco::experimental::op::insert_tag>>(T3, long, T4, T5, T6 *, T7)
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x0 is out of bounds
=========     and is 140591841148928 bytes before the nearest allocation at 0x7fde16c00000 of size 20 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x23adbc]
=========                in /usr/lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:__cudart1071 [0x85215b]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:cudaLaunchKernel_ptsz [0x891da8]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:unsigned long cuco::experimental::static_set<int, cuco::experimental::extent<unsigned long, 18446744073709551615ul>, (cuda::std::__4::__detail::thread_scope)1, cudf::experimental::row::equality::device_row_comparator<false, cudf::nullate::DYNAMIC, cudf::experimental::row::equality::nan_equal_physical_equality_comparator>, cuco::experimental::linear_probing<1, cudf::detail::experimental::compaction_hash<cudf::experimental::row::hash::device_row_hasher<cudf::detail::MurmurHash3_32, cudf::nullate::DYNAMIC> > const>, rmm::mr::stream_allocator_adaptor<default_allocator<char> >, cuco::experimental::aow_storage<1> >::insert_if<thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, cudf::detail::row_validity>(thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, cudf::detail::row_validity, cuco::experimental::cuda_stream_ref) [0x40476a]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:cudf::detail::distinct_count(cudf::table_view const&, cudf::null_equality, rmm::cuda_stream_view) [0x400cf6]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:cudf::distinct_count(cudf::table_view const&, cudf::null_equality) [0x400de5]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:DistinctCount_SimpleStruct_Test::TestBody() [0x20b045]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) [0x84c8ed]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:testing::Test::Run() [clone .part.0] [0x83bd76]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:testing::TestInfo::Run() [0x83c4aa]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:testing::TestSuite::Run() [clone .part.0] [0x83ccbb]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:testing::internal::UnitTestImpl::RunAllTests() [0x842e7a]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:testing::UnitTest::Run() [0x83c641]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:main [0x1de237]
=========                in gtests/DISTINCT_COUNT
=========     Host Frame:__libc_start_main [0x240b3]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0x20636e]
=========                in gtests/DISTINCT_COUNT
```

This was on the latest 23.08 code.

**Expected behavior**
No crashes.

**Comment by ttnghia** [comment]
```
Address 0x0 is out of bounds
=========     and is 140591841148928 bytes before the nearest allocation
```
This looks like an overflow in a kernel with zero-size input.

**Comment by wence-** [comment]
> So, if only some of the input columns are nullable (as is the case here), this returns a null pointer and a null count of zero (everything is valid).

Actually, this is a misreading of the documentation. I think the documentation intends that the implementation of `bitmask_or` should just `or` together those columns with non-empty bitmasks. but, the implementation does this:

```c++
  rmm::device_buffer null_mask{0, stream, mr};
  if (view.num_rows() == 0 or view.num_columns() == 0) {
    return std::pair(std::move(null_mask), 0);
  }

  std::vector<bitmask_type const*> masks;
  std::vector<size_type> offsets;
  for (auto&& col : view) {
    if (col.nullable()) {
      masks.push_back(col.null_mask());
      offsets.push_back(col.offset());
    }
  }

  if (static_cast<size_type>(masks.size()) == view.num_columns()) {
    return cudf::detail::bitmask_binop(
      [] __device__(bitmask_type left, bitmask_type right) { return left | right; },
      masks,
      offsets,
      view.num_rows(),
      stream,
      mr);
  }

  return std::pair(std::move(null_mask), 0);
```

So if not all columns are nullable, then we get an empty (all-valid) bitmask back.

So perhaps instead we want this patch to make the implementation agree with the documentation.

```diff
diff --git a/cpp/src/bitmask/null_mask.cu b/cpp/src/bitmask/null_mask.cu
index bbe603dfdb..7d61c0b533 100644
--- a/cpp/src/bitmask/null_mask.cu
+++ b/cpp/src/bitmask/null_mask.cu
@@ -488,7 +488,7 @@ std::pair<rmm::device_buffer, size_type> bitmask_or(table_view const& view,
     }
   }
 
-  if (static_cast<size_type>(masks.size()) == view.num_columns()) {
+  if (masks.size() > 0) {
     return cudf::detail::bitmask_binop(
       [] __device__(bitmask_type left, bitmask_type right) { return left | right; },
       masks,
```

**Comment by wence-** [comment]
Ah, no, this is deliberate (as per https://github.com/rapidsai/cudf/pull/7406#discussion_r581276636). If any masks are null then the validity of their `or` is null (i.e. everything is valid). So I think the first patch is correct.

**Comment by ttnghia** [comment]
I think the logic here was wrong from the beginning. We want to avoid `insert` if there is any null in the row. So we should check `"null_or"` instead of `bitmask_or` (which is equivalent to `"valid_or"`). In other word, the correct logic should be using `bitmask_and`.

**Comment by ttnghia** [comment]
@wence- While finding similar code, I only see one more instance of `bitmask_or` in Python: https://github.com/rapidsai/cudf/blob/67efaf62c7314fbda56d39ea5f60bb893c406084/python/cudf/cudf/core/groupby/groupby.py#L869.

I'm not familiar with Python code here so can you have a look and check if it is also correct, please?

**Comment by wence-** [comment]
> I think the logic here was wrong from the beginning. We want to avoid `insert` if there is any null in the row. So we should check `"null_or"` instead of `bitmask_or` (which is equivalent to `"valid_or"`). In other word, the correct logic should be using `bitmask_and`: only insert a row if that row doesn't contain any nulls, so the bitmask to check should be resulted from `bitmask_and`.

I think I disagree. We want to count distinct rows, if nulls should compare equal, then we still need to hash the row if it only contains some nulls.

That is, the table:

```
 0   1
NA   2
 1   0
 2  NA
```

with `null_equality::EQUAL` should have a `distinct_count` of 4. If we were only to insert rows when the row has no nulls, then we would end up with a `distinct_count` of 3 (`2 + (int)(null_count > 0)`).

Do you agree?

**Comment by wence-** [comment]
> @wence- While looking for similar code, I only see one more instance of `bitmask_or` in Python:
> 
> https://github.com/rapidsai/cudf/blob/67efaf62c7314fbda56d39ea5f60bb893c406084/python/cudf/cudf/core/groupby/groupby.py#L869
> .
> 
> I'm not familiar with Python code here so can you have a look and check if it is also correct, please?

This is safe afaict.

1. It ignores the null mask itself anyway (it's only checking if the null count of the OR of the columns)
2. The cython wrapper wraps up an `rmm::device_buffer` for the null mask, but does this appropriately even for an empty buffer.

**Comment by ttnghia** [comment]
> We want to count distinct rows, if nulls should compare equal, then we still need to hash the row if it only contains some nulls.

Yes. And `bitmask_and` will tell you what rows contain at least a null. If the output bitmask is `1` then that rows doesn't have any nulls, and vice versa.

Note that the other callers to `insert_if` such as https://github.com/rapidsai/cudf/blob/67efaf62c7314fbda56d39ea5f60bb893c406084/cpp/src/search/contains_table.cu#L127 and `mixed_join_semi` correctly use `bitmask_and`.

**Comment by ttnghia** [comment]
Humnn, sorry it seems that I was wrong. So we want to insert a row if it still contains at least one non-null element. So `bitmask_or` is correct.

**Comment by wence-** [comment]
> Yes. And bitmask_and will tell you what rows contain at least a null. If the output bitmask is 1 then that rows doesn't have any nulls, and vice versa.

Ah thanks, I got myself confused. OK, so with `bitmask_and` we will have a validity mask that only skips those rows for which every column is NULL.

**Comment by wence-** [comment]
> So I thought that we are inserting rows without any nulls. It should state this:

Yeah, I continue to be confused all the time by the interpretation of the null mask as "bit set => no null at this position".

So the way we detect that a row is fully null is to OR the bitmasks together (because setness [validity] in any column means that the row is _not_ fully null).

**Comment by ttnghia** [comment]
In term of efficiency, I think using `bitmask_or` in case of nulls compared equal is not really efficient. If we have millions of rows in the table, all of them are repeated (so we have only 1 unique row), but not any row is all-nulls. In such case, we will insert all rows.

**Comment by wence-** [comment]
I think this patch is a correctness fix, and only does `insert_if` if it is necessary:
```diff
diff --git a/cpp/src/stream_compaction/distinct_count.cu b/cpp/src/stream_compaction/distinct_count.cu
index 7185dae77b..341648d548 100644
--- a/cpp/src/stream_compaction/distinct_count.cu
+++ b/cpp/src/stream_compaction/distinct_count.cu
@@ -150,15 +150,21 @@ cudf::size_type distinct_count(table_view const& keys,
       stream.value()};
 
     auto const iter = thrust::counting_iterator<cudf::size_type>(0);
-    // when nulls are equal, insert non-null rows only to improve efficiency
+    // when nulls are equal, only insert those rows that are not all null to improve efficiency
     if (nulls_equal == null_equality::EQUAL and has_nulls) {
       thrust::counting_iterator<size_type> stencil(0);
       auto const [row_bitmask, null_count] =
         cudf::detail::bitmask_or(keys, stream, rmm::mr::get_current_device_resource());
       row_validity pred{static_cast<bitmask_type const*>(row_bitmask.data())};
 
-      return key_set.insert_if(iter, iter + num_rows, stencil, pred, stream.value()) +
-             static_cast<cudf::size_type>(null_count > 0);
+      // Unless all columns have a null mask, row_bitmask will be
+      // null, and null_count will be zero. Equally, unless there is
+      // some row which is null in all columns, null_count will be
+      // zero. So, it is only when null_count is not zero that we need
+      // to do a filtered insertion.
+      if (null_count > 0) {
+        return key_set.insert_if(iter, iter + num_rows, stencil, pred, stream.value()) + 1;
+      }
     }
     // otherwise, insert all
     return key_set.insert(iter, iter + num_rows, stream.value());
```

**Comment by wence-** [comment]
> In term of efficiency, I think using `bitmask_or` in case of nulls compared equal is not really efficient. If we have millions of rows in the table, all of them are repeated (so we have only 1 unique row), but not any row is all-nulls. In such case, we will insert all rows.

But this is no worse than the case _without_ any nulls (which is presumably the more common one).

Do we have any benchmarks here?

**Comment by ttnghia** [comment]
I don't think we have any benchmark for such extreme cases, because such benchmarks will never be able to complete.

**Comment by wence-** [comment]
https://github.com/rapidsai/cudf/pull/13590 fixes the distinct count issue (with the most recent patch from this issue). @revans2 can you check if this also fixes the original (non-narrowed-down) problem?
