### ISSUE TITLE
[BUG]pyarrow question by building on conda

### ISSUE THREAD

**Issue by newjavaer** [rapidsai/cudf#13596]
When I use this command build cudf environment.
conda create -n rapids-22.12 -c rapidsai -c conda-forge -c nvidia  \
    cudf=22.12 python=3.10 cudatoolkit=11.5
I install pyarrow==11.0.0，there will appear a error
![image](https://github.com/rapidsai/cudf/assets/49930795/f7e7faa1-1577-437e-b5f4-dc6d1b177d42)
when I change pyarrow to 9.0.0 ,there also appear this a error
![image](https://github.com/rapidsai/cudf/assets/49930795/7c880bb2-62c8-4005-9fac-d10dffb60081)
hope for your reply!

**Comment by beckernick** [comment]
Unfortunately, you can't mix Arrow packages across conda and pip. The conda built arrow binaries are not ABI compatible with the pip wheels. You can solve this issue by installing everything from conda or everything from pip.

**Comment by newjavaer** [comment]
> Hi @newjavaer - thanks for reporting!
> 
> What is the output of:
> 
> ```python
> import pyarrow as pa
> print(pa.__version__)
> ```

There is 9.0.0

**Comment by newjavaer** [comment]
> Unfortunately, you can't mix Arrow packages across conda and pip. The conda built arrow binaries are not ABI compatible with the pip wheels. Once you've settled on the right version, you can solve the symbol clash issue by installing everything from conda or everything from pip.

Thank you !
