### ISSUE TITLE
Invalid Device Ordinal on Jetson

### ISSUE THREAD

**Issue by JasonAtNvidia** [rapidsai/cudf#1360]
**Describe the bug**
specific error returned from specific function that is blocking the success of `make test` after building on AGX.

Error output from ./HASH_MAP_TEST 
'''
ERROR: CUDA RT call "cudaMemPrefetchAsync(m_hashtbl_values, m_hashtbl_size*sizeof(value_type), dev_id, 0)" in line 88 of file /home/nvidia/Documents/cudf/cpp/src/hash/concurrent_unordered_map.cuh failed with invalid device ordinal (10).
'''

Error output from ./JOIN_TEST
'''
C++ exception with description "CUDA error encountered at: /home/nvidia/Documents/cudf/cpp/src/hash/concurrent_unordered_multimap.cuh:467: 10 cudaErrorInvalidDevice invalid device ordinal" thrown in the test body.
'''
The line 467 of multimap is also a call to cudaMemPrefetchAsync that is failing.

./NVCATEGORY_TEST.... same error
'''
C++ exception with description "CUDA error encountered at: /home/nvidia/Documents/cudf/cpp/src/hash/concurrent_unordered_multimap.cuh:467: 10 cudaErrorInvalidDevice invalid device ordinal" thrown in the test body.
'''

**Steps/Code to reproduce bug**
You have to build cudf on a Jetson Xavier.  This is a huge headache but if you need to reproduce it I can get you there.

**Expected behavior**
Test should pass

**Environment details (please complete the following information):**
 - Environment location: Bare-metal, Jetson Xavier
 - Method of cuDF install:from source

 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 [print_env_jetson.txt](https://github.com/rapidsai/cudf/files/3048341/print_env_jetson.txt)

**Additional context**

**Comment by harrism** [comment]
Apparently this is because Jetson (even Xavier) doesn't support Unified Memory. From the docs:

> Unified Memory has two basic requirements:
>  - a GPU with SM architecture 3.0 or higher (Kepler class or newer)
>  - a 64-bit host application and *non-embedded* operating system (Linux, Windows, macOS)

I guess JetPack Linux qualified as an embedded operating system. 

In order to support this, we would need to modify the concurrent_map and multi map to not use Unified Memory by default. There are also other locations in cuDF that use Unified Memory...

**Comment by harrism** [comment]
Rather than just closing this issue, I'm going to convert it into a feature request for Jetson / UVM-less support in libcudf.

**Comment by JasonAtNvidia** [comment]
Unified memory works on Tegra, it is just the Prefetch we need a workaround for.

See this documentation. https://docs.nvidia.com/cuda/cuda-for-tegra-appnote/index.html#effective-usage-unified-memory

**Comment by nsakharnykh** [comment]
@JasonAtNvidia can you just comment out all `cudaMemPrefetchAsync` calls and test it? (there shouldn't be many, just in the hash map class I believe)

**Comment by JasonAtNvidia** [comment]
Commenting out cudaMemPrefetchAsync works great. Builds and tests run great.  Do you think there is any performance to be gained by swapping in cudaStreamAttachMemAsync()?

**Comment by harrism** [comment]
@JasonAtNvidia I believe we removed the managed memory usage from libcudf quite a while ago now, and that seemed to fix this, so closing.
