### ISSUE TITLE
[FEA] Add forward and backward fill options to DataFrame.fillna

### ISSUE THREAD

**Issue by pboynton** [rapidsai/cudf#1361]
It would be nice to have forward fill and backward fill options within the DataFrame.fillna method to use in time series applications. The "method" argument is already implemented in the API currently.

```python
import cudf
df = cudf.DataFrame({'x': [1, 2, None, 4]})
df.fillna(method='ffill') # returns df with None filled as 2
df.fillna(method='bfill') # returns df with None filled as 4
```

This issue is somewhat of a continuation of #1106 .

**Comment by kkraus14** [comment]
@harrism added the libcudf label because I'll imagine we want to implement this functionality / have an API for accomplishing this from libcudf as well.

**Comment by harrism** [comment]
@kkraus14 Perhaps this should be in 0.8 along with dropna #911 ?

**Comment by shwina** [comment]
I'm looking into this - PR incoming!

**Comment by miroenev** [comment]
Bump!

**Comment by chinmaychandak** [comment]
Can someone please look into `fillna` methods like `ffill`, `bfill` for groupby objects?

**Comment by chinmaychandak** [comment]
Also, will this work for string columns, once implemented?

**Comment by shwina** [comment]
I'm unassigning myself from this as I never got around to it - apologies :-( Defer to @harrism and @kkraus14 to prioritize/assign.

**Comment by harrism** [comment]
We're generally only doing bug fixes / tech debt / documentation in 0.14 (and a few urgent performance things). New features are mostly reprioritized until 0.15.

**Comment by rnyak** [comment]
@harrism any plan to include ffill() and bfill() methods in 0.16 nightlies? Thanks.

**Comment by pretzelpy** [comment]
bump

**Comment by rspadim** [comment]
Hi guys, any improvement here? there's a real use that needs this: https://stackoverflow.com/questions/64197834/fill-forward-cupy-cudf/64217244

**Comment by kkraus14** [comment]
> Hi guys, any improvement here? there's a real use that needs this: https://stackoverflow.com/questions/64197834/fill-forward-cupy-cudf/64217244

We have just started scoping this where we're hoping to be able to tackle this in 0.18.

**Comment by rspadim** [comment]
Thanks @kkraus14 !

**Comment by yidong72** [comment]
For anyone who needs a quick implementation of `fillna` with`method` and `limit` support. Here is a Numba implementation. 
[fillna.zip](https://github.com/rapidsai/cudf/files/5569767/fillna.zip)
