### ISSUE TITLE
[QST] cufio-drv:705 running in compatible mode

### ISSUE THREAD

**Issue by qzc438** [rapidsai/cudf#13651]
When reading a large file, the cufile.log will show "cufio-drv:705 running in compatible mode".

**Comment by GregoryKimball** [comment]
Hello @qzc438, thank you for trying out GDS support in cudf. Would you please clarify - are you interested in what "compatible mode" means in this case? Is GDS working well for your use case?

**Comment by qzc438** [comment]
Hi Gregory, this is my question. I did not know why cufio went into a compatible mode. Could you please indicate the potential reasons for this?

**Comment by GregoryKimball** [comment]
Please excuse the delay. It sounds like the cudf build you are using was not built with cuFile. Comparing with my workstation, I see `cufio-drv:705 running in compatible mode` in `cufile.log` when I'm running on a build that has not been setup with cuFile. Do you see an error when you set the environment variable `LIBCUDF_CUFILE_POLICY=ALWAYS`?

**Comment by vyasr** [comment]
Closing as stale. Feel free to reopen if needed.
