### ISSUE TITLE
[FEA] support min/max for LIST group by aggregations.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#13667]
**Is your feature request related to a problem? Please describe.**
This is specifically related to https://github.com/NVIDIA/spark-rapids/issues/8668

It looks like we got CUDF support for most types, but LIST at the top level still appears to return an error.

```
ai.rapids.cudf.CudfException: CUDF failure at:/home/jenkins/agent/workspace/jenkins-spark-rapids-jni_nightly-dev-476-cuda11/thirdparty/cudf/cpp/src/groupby/sort/group_single_pass_reduction_util.cuh:108: Unsupported groupby reduction type-agg combination.
	at ai.rapids.cudf.Table.groupByAggregate(Native Method)
```

Oddly if I wrap the LIST in a struct and do the aggregation it all works correctly.

**Describe the solution you'd like**
LISTs work for the value in a min or max of a group by aggregation.

**Describe alternatives you've considered**
Do something really ugly, like wrap the LIST in a struct.

**Comment by GregoryKimball** [comment]
Thank you @revans2 for noticing this. @divyegala would you please check out this scenario with LIST value types in aggregations? I believe @PointKernel tackled most of the refactoring in aggregations for experimental comparators. Hopefully this will be as simple as adjusting the overloads in `group_single_pass_reduction_util.cuh`. Thank you for your help!

**Comment by GregoryKimball** [comment]
@divyegala did a quick evaluation here. To add LIST value support for min/max aggregations, we'll need to introduce a new utility module (e.g. `list_minmax_util.cuh`) to complement the existing `struct_minmax_util.cuh`. 

From where we are today, I sadly must encourage you to `Do something really ugly, like wrap the LIST in a struct.`, until we invest in a better solution here.

**Comment by ttnghia** [comment]
I suspect that `struct_minmax_util` can be used for lists as well. Previously I implemented it to support structs while couldn't support lists but now we have the experimental comparator working for any type. 

I'm testing that idea and will confirm.

**Comment by ttnghia** [comment]
Confirm that my idea work. Need more tests and cleanup. A PR should be up by next week.
