### ISSUE TITLE
[FEA] Need a general, testing-framework-aware column comparison for testing

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1367]
Most libcudf tests need to compare columns: Expected vs Actual. Some do this using the `gdf_equal_columns` template in `cpp/tests/utilities/cudf_test_utils.cuh`. Some tests have idiosyncratic functions which copy data from the device and make it accessible for comparison in std::vector's; and some, especially more recently, use the `cudf::test::column_wrapper` abstraction, with its `operator==`. While column_wrapper is far from perfect (see #1178 ), it is at least taking many steps in the direction of a uniform facility for handling columns in tests and should be in general use in relevant tests.

Now, the two factored-out and general-case comparators - `gdf_equal_columns` and `column_wrapper::operator==`, are oblivious to gtest, our testing framework. They merely return a boolean value. On the other hand, the custom comparator code in various tests _is_ mostly testing-framework-aware, and uses `EXPECT_` and/or `ASSERT_` macros to provide more specific indications of errors or mismatches. Of course, not all tests using custom comparison code give indication of all possible cases of mismatch, and may ignore or bunch together some of them.

There should be a common facility for comparing columns - preferably both `cudf::test::column_wrapper<E>`'s and `gdf_column`'s - which all tests can use and which will be as specific as is reasonable in reporting errors.

**Comment by jrhemstad** [comment]
Seeing as though `column_wrapper` is only for use in GTest code anyways, I'd support adding `EXPECT_*` GTest macros inside of the `operator==` function.

**Comment by eyalroz** [comment]
@jrhemstad : I would be against that, for the following reasons:

1. Inconsistent with the behavior of things which aren't columns (including, say, gdf_scalar)
2. Inconsistent with the behavior of `gdf_column` (for which, in some cases, comparison is also relevant)
3. Breaks the element of least surprise. It's surprising for `cola == colb` to print things. 
4. Inconsistent with the pattern of using gtest; we are used to saying `EXPECT_...` or `ASSERT_` rather than have that just sort of happen. <- TBH, my function is a bit inconsistent with that as well, but I tried to minimize this.
5. Classes should. in genera, have the minimum functionality they need; and column_wrapper is already packed with functionality I'm not sure it should have
