### ISSUE TITLE
[QST] Why does pandas use less memory for deeply nested types?

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#13671]
**What is your question?**
Why does pandas use less memory for deeply nested types? Here's an example:

```
>>> import pandas as pd
>>> import pyarrow as pa
>>> obj = [[[[[[[[[[1]]]]]]]]]]
>>> df = cudf.DataFrame({'a':obj*10_000})
>>> df.memory_usage().sum()
440036
>>> df = pd.DataFrame({'a':obj*10_000})
>>> df.memory_usage().sum()
80128
>>> table = pa.Table.from_pandas(df)
>>> table.get_total_buffer_size()
440036
>>> df = pd.DataFrame({'a':[1]*10_000})
>>> df.memory_usage().sum()
80128
```

In this example, `obj` is a nested list with depth of 10. I understand that with an Arrow representation, this requires 10 offset child columns. `pyarrow` and `cudf` both use Arrow representation and so have the same memory size. However, the pandas memory size being the same between `1` and `[[[[[[[[[[1]]]]]]]]]]` was very surprising to me. Why does pandas use less memory for deeply nested types?

**Comment by shwina** [comment]
I think perhaps you want the `deep=True` argument to `memory_usage`:

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.memory_usage.html

**Comment by shwina** [comment]
Also note that Pandas has no equivalent for "list" and "struct" types, it just uses Python `list`s and `dict`s as the underlying storage. So the memory layout and consumption is going to be very different from cuDF or Arrow.

**Comment by GregoryKimball** [comment]
Thank you @shwina that solves the mystery for me!

```
>>> obj = [[[[[[[[[[1]]]]]]]]]]
>>> df = pd.DataFrame({'a':obj*10_000})
>>> df.memory_usage().sum()
>>> df.memory_usage(deep=True).sum()
560128
```

Arrow representation is actually about 20% smaller than pandas. Thank you!!
