### ISSUE TITLE
[BUG] set_null_count() doesn't check for nullptr's enough

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1368]
In `utilities/cudf_utilities.h` we have the `set_null_count()`. It:

1. Doesn't make sure the `col` pointer is non-null before dereferencing it.
2. Calls `gdf_count_nonzero_mask()` even if `col->valid` is `nullptr`

As for (1.) - we should at least add an `assert()` there.
As for (2.) - **edit:** this is fine, but as @jrhemstad suggests, the Doxygen for gdf_count_nonzero_mask() should be fixed to indicate it's ok to call it with a null pointer like this.

**Comment by jrhemstad** [comment]
> As for (2.) - while `gdf_count_nonzero_mask()` _does_ check for a nullptr argument, it considers that to be an error. So, instead, we need to check for `col->valid` being `nullptr` and handle that case.

This isn't correct. However, I do see that the Doxygen between what is in `functions.h` and `valid_ops.cu` is out of sync. What is is `valid_ops.cu` is more up to date and notes that if the input mask is `nullptr`, that it just returns a count equal `num_rows`.  

https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/bitmask/valid_ops.cu#L119

**Comment by eyalroz** [comment]
Ok, and will change my PR accordingly.

**Comment by jrhemstad** [comment]
> Hmmm... wait, this is not right. I looked at `gdf_count_nonzero_masks()` again, and it has:
> 
> ```
>  if(0 == num_rows) {return GDF_SUCCESS;}
> ```
> without initializing `*count` to 0. Is that supposed to be the case?

That's separate from the original point you made, but it is a very good point. It definitely should initialize `*count` to 0.

**Comment by jrhemstad** [comment]
Makes sense to me. I'd welcome a PR that updates the documentation and provides additional error checking.
