### ISSUE TITLE
[FEA] Support for murmur hash for List[Structs]

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#13689]
**Is your feature request related to a problem? Please describe.**
I wish cudf could support murmur hash for a columnview of List of Structs

**Describe the solution you'd like**
The following test should pass in Java
```
  @Test
  public void testSpark32BitMurmurHash() {
      StructData structData = new StructData(1, 2.0f);
      HostColumnVector.DataType dt = new HostColumnVector.ListType(true,
              new HostColumnVector.StructType(true,
                      new HostColumnVector.BasicType(true, DType.INT32),
                      new HostColumnVector.BasicType(true, DType.FLOAT32)));
    try(ColumnVector vector = ColumnVector.fromLists(dt, Arrays.asList(structData, structData));
        ColumnVector res = ColumnVector.spark32BitMurmurHash3(new ColumnView[]{vector})) {
        assert res != null;
    }
  }
```

**Describe alternatives you've considered**
None

**Additional context**
This is needed by spark-rapids

**Comment by GregoryKimball** [comment]
Hello @razajafri, with the recent work by @nvdbaranec on Spark-compatible XXHash64, do you think this request should be solved in the JNI layer instead?

**Comment by razajafri** [comment]
Closed in lieu of https://github.com/NVIDIA/spark-rapids-jni/issues/1280
