### ISSUE TITLE
[FEA] Missing error-handling/execution-control macros for gdf_error values

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1369]
In our `cpp/src/utilities/error_utils.hpp` we have two kinds of macros:

* `GDF_REQUIRE()` - which expects a boolean `true` value
* `RMM_TRY` and `CUDA_TRY` - which expect success values returned by various calls

both return some error if the condition was not met. But - what about libcudf functions? Why can't we `_TRY` them? We should have a `GDF_TRY()` macro which does that. * **edit**: Following a discussion with @jrhemstad , let's also add `CUDF_TRY()` which throws an exception instead of returning a `gdf_error` further back up.

The same thing goes for the `ASSERT_` macros in `cpp/tests/utilities/cudf_test_fixtures.h`: We have `ASSERT_CUDA_SUCCEEDED` and `ASSERT_RMM_SUCCEEDED` but no `ASSERT_CUDF_SUCCEEDED`.

So let's add these three macros.

**Comment by jrhemstad** [comment]
With the introduction of `CUDF_EXPECTS`, the `gdf_error` codes are effectively deprecated and will be removed from functions as they are updated to a C++ API.

In time, I believe the `gdf_error` codes and `GDF_REQUIRE` macro will be removed entirely.

**Comment by eyalroz** [comment]
Well, there's still code that gets written that uses `GDF_REQUIRE` and deals with other code that returns gdf_error. So, the first convenience macro still makes sense for now - and will go away along with `GDF_REQUIRE`. I only suggested this since I found myself using it...

But the second part makes sense both now and later on, since it has nothing to do with the transition to exceptions.
