### ISSUE TITLE
[BUG] libcudf misreads deeply nested ORC column

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#13709]
**Describe the bug**
libcudf misreads an ORC file consisting of a single struct<struct<int>> column relative to Apache Spark.

**Steps/Code to reproduce bug**
Execute the following C++ program on the file and compare the output to the associated Spark output attachment showing what is expected for the file's contents.
```c++
#include <iostream>

#include <cudf/io/orc.hpp>
#include <cudf_test/column_utilities.hpp>

int main(int argc, char** argv) {
  auto twm =  cudf::io::read_orc( 
    cudf::io::orc_reader_options::builder(cudf::io::source_info(argv[1])));
  std::cout << "Num columns: " << twm.tbl->num_columns() << std::endl;
  auto col = twm.tbl->get_column(0);
  cudf::test::print(col);
  return 0;
}
```

Running this on the test orc file results in this output:
```
Num columns: 1
cudf::struct_view<cudf::struct_view<int32_t,>,>:
Length : 42:
Null count: 3
111111111111111111111110111111100111111111
   cudf::struct_view<int32_t,>:
   Length : 42:
   Null count: 3
   111111111111111111111110111111100111111111
      000111111111111111111110111101100111111111
      -1285054300, 2073013853, -1536043331, -1951095677, -823325295, 1847137302, -116758710, -1022864982, -20361476, NULL, NULL, -2091669542, -92717762, NULL, -997298912, 512188123, -1945512229, -1120352167, NULL, -1249034686, 921385857, -1021479014, -1984694792, 804506720, -1118499454, -2060407069, -2147009342, -1248600986, -780086624, 38076635, 1660839633, 1838787742, 1408957971, -1308193965, 1788821176, 696257041, -269646613, -573160045, 373586948, NULL, NULL, NULL
```

Apache Spark thinks the values in the file are:
```
scala> spark.read.orc("orcdbg1111771617.orc").show(100000)
+---------------+
|            a.b|
+---------------+
|{{-1285054300}}|
| {{2073013853}}|
|{{-1536043331}}|
|{{-1951095677}}|
| {{-823325295}}|
| {{1847137302}}|
| {{-116758710}}|
|{{-1022864982}}|
|  {{-20361476}}|
|           null|
|           null|
| {{-221772138}}|
|  {{346222857}}|
|{{-2091669542}}|
|  {{-92717762}}|
|       {{null}}|
| {{-997298912}}|
|  {{512188123}}|
|           null|
|{{-1945512229}}|
|{{-1120352167}}|
|{{-1752389781}}|
|{{-1249034686}}|
|  {{921385857}}|
|{{-1021479014}}|
|{{-1984694792}}|
|  {{804506720}}|
|{{-1118499454}}|
|{{-2060407069}}|
|{{-2147009342}}|
|{{-1248600986}}|
| {{-780086624}}|
|   {{38076635}}|
| {{1660839633}}|
| {{1838787742}}|
| {{1408957971}}|
|{{-1308193965}}|
| {{1788821176}}|
|  {{696257041}}|
| {{-269646613}}|
| {{-573160045}}|
|  {{373586948}}|
+---------------+
```

Note how the values are initially in agreement until the 12th row where libcudf loads -2091669542 but Spark loads -221772138.  Values then appear to be shifted by a few rows relative to Spark, and there are three null rows at the end that Spark does not have.

[orcdbg1111771617.orc.gz](https://github.com/rapidsai/cudf/files/12073385/orcdbg1111771617.orc.gz)

**Expected behavior**
libcudf should load the file with the same values as Apache Spark.

**Comment by vuule** [comment]
ORC reader skips data decode when a hierarchy level contains no data. This is the case for the nested struct column, as it does not even contain a validity mask.
The data decode also includes the update of null masks for the children columns, so skipping this step for the level 1 struct causes incorrect null mask for the level 2 int column.

Looking into how to properly select work that needs to be done even with empty data on a given level
