### ISSUE TITLE
[BUG] allocation size calculations etc. may overflow

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1371]
In several places in our code, and perhaps most importantly in the functions we use to calculate sizes for allocations, we do something like the following:
```
z = (x+y-1)/y;
```
or
```
z = ((x+y-1)/y)*y;
```
the former is supposed to a division of x by y, rounding up, and the latter - just rounding up to a multiple of y. These calculations run the risk of **overflow** - and this is especially a problem considering the small type we use for allocation sizes - `gdf_size_type` is effectively a 32-bit integer. It is not inconceivable that someone will try to use an `x` value that's close to 2^31, and this value will just overflow.

We need safe versions of integer round-up and division-rounding-up - and to have allocation functions use them (e.g. in `cpp/src/bitmask/legacy_bitmask.cpp`). They should also be used when forming CUDA kernel launch grids; perhaps a bit of code facilitating that, at least in simple cases, could be added.

**Comment by jrhemstad** [comment]
Makes sense to me. I'd support helper functions for doing these computations in a safer way.

**Comment by harrism** [comment]
I believe this is finished, not sure why it's still open.
