### ISSUE TITLE
[FEA] Use a RAII wrapper for streams in outer API function implementations

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1372]
Quite a few implementations of our cuDF API functions have the following pattern in their code:
```
gdf_error gdf_foo(args...) 
{
    // some setup
    cudaStream_t stream;
    cudaStreamCreate(&stream);
    // do stuff with the stream
    if (error) {
        // some teardown
        cudaStreamSynchronize(stream);
        cudaStreamDestroy(stream);
        return GDF_SOME_ERROR;
    }          
    // do more stuff
    cudaStreamSynchronize(stream);
    cudaStreamDestroy(stream);
}
```
... and that's assuming errors are actually checked and the stream properly destroyed...

instead, we should have a RAII gadget that will simplify this to merely:
```
gdf_error gdf_foo(args...) 
{
    // some setup
    cudf::util::scoped_stream stream; // will throw on failure to create
    // do stuff with the stream
    if (error) {
        // some teardown
        return GDF_SOME_ERROR;
    }          
    // do more stuff
}
```
3 less lines - but absolutely no stream handle leaks!

**Comment by jrhemstad** [comment]
Makes sense to me. Ultimately we'll want to move away from functions creating/destroying their own streams and instead providing a pool of available streams. But this is a good intermediary.
