### ISSUE TITLE
[BUG] Tidy up bit_util.cuh,  `bit_mask.h` and `bit_mask.cuh`

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1373]
`cpp/src/utilities/bit_util.cuh` is kind of messy right now:

* It has types and constants we don't use (`ValidType`, `ValidSize`) - and they don't even correspond to what we're actually doing
* It has code we don't use, like `gdf_valid_to_str()`. Not that that's unusable - but that's test-related code (which, in fact, exists under `cpp/tests`)
* It uses a lot of magic numbers with inherent assumptions about the size of the "bit container" and the number of bits in a byte - which may be valid but should not be made separately everywhere, just centrally, with the code drawing upon definitions elsewhere.
* It uses lookup tables for some bit operations, which are both unseemly and unuseful.

Let' remove what we don't need, and rewrite what we do need (or expect to need) to make less assumptions and be more generic.

Also, the is some redundancy between `bit_util.cuh` and `bit_mask.cuh` + `bit_mask.h` in `cpp/src/bitmask/`. Those headers also have methods for setting and clearing bits etc. Let's ensure the code in `bit_util.cuh` can be, and is, used in `bit_mask.cuh`/`bit_mask_h`. as appropriate.

Finally, it doesn't make much sense to have two headers with the same name, at the same location, with different extensions; plus, `bit_mask.h` has all the code under a class named `BitMask`. - while a lot of the code doesn't really involve instances of that class, at all; so let's move the `BitMask`-class-specific code into its own file, and keep just one header with non-`BitMask`-related code.

PS - I'm not sure if even that one header is necessary, or whether it should be merged into `bit_util.cuh`, but let's leave it in existence for now.

**Comment by jrhemstad** [comment]
Agreed. `bit_util.cuh` is problematic and any needed functionality should be move elsewhere.

**Comment by harrism** [comment]
Reopening.. Apparently this was close-referenced by the wrong PR...
