### ISSUE TITLE
[BUG] Decimal128 uses a fixed precision of 18 when converting to an arrow array

### ISSUE THREAD

**Issue by jihoonson** [rapidsai/cudf#13749]
**Describe the bug**
Hi all. When a decimal128 column is converted to an arrow array, the precision is set to 18 in [this line](https://github.com/rapidsai/cudf/blob/branch-23.08/cpp/src/interop/to_arrow.cu#L203), even though the max precision decimal128 supports is 38. This seems like a bug rather than intentional behavior.

**Comment by codereport** [comment]
So I'm not 💯 percent confident this is the story but I am pretty certain is is the case. TLDR: It was a bug when it was introduced in https://github.com/rapidsai/cudf/pull/9986. 

___

Timeline:

* https://github.com/rapidsai/cudf/pull/5704 was merged Jul 2020
* https://github.com/rapidsai/cudf/pull/7609 was merged Apr 2021 ⬅️ introduced the 18 for decimal64 
* https://github.com/rapidsai/cudf/pull/9483 was merged Nov 2021
* https://github.com/rapidsai/cudf/pull/9986 was merged Apr 2022 ⬅️ introduced the 18 for decimal6128

My guess is this was just a copy and paste issue. Note though that `libcudf` doesn't actually have the concept of precision, but `Python CUDF` does seem to set it to 38 in the case of 128. 

```py
class Decimal32Dtype(DecimalDtype):
    name = "decimal32"
    MAX_PRECISION = np.floor(np.log10(np.iinfo("int32").max))
    ITEMSIZE = 4


@doc_apply(
    decimal_dtype_template.format(
        size="64",
    )
)
class Decimal64Dtype(DecimalDtype):
    name = "decimal64"
    MAX_PRECISION = np.floor(np.log10(np.iinfo("int64").max))
    ITEMSIZE = 8


@doc_apply(
    decimal_dtype_template.format(
        size="128",
    )
)
class Decimal128Dtype(DecimalDtype):
    name = "decimal128"
    MAX_PRECISION = 38
    ITEMSIZE = 16
```

My suggestion is to "fix" it, and then write a few tests to see if it works when roundtripping. IIRC, we had planned to test most of the overflow  / close to overflow use cases from the Python side of things cause it was much easier that way. Probably why it wasn't caught immediately in the C++ test cases (as they are quite bare bones)

**Comment by jihoonson** [comment]
Thanks @codereport. I created https://github.com/rapidsai/cudf/pull/14230 to fix this issue.
