### ISSUE TITLE
[BUG] Int8 not supported in GPUArrowReader

### ISSUE THREAD

**Issue by randyzwitch** [rapidsai/cudf#1380]
**Describe the bug**
For the OmniSci `select_ipc_gpu` method in pymapd, we use Arrow to return a buffer and use `GpuArrowReader` from cudf to build a GPU dataframe. Currently, having an `int8` column returns a `NotImplemented` error when trying to convert the Arrow buffer to a cudf.

I'm fairly certain the issue is here, and that adding `'INT8'` to the tuple on line 46 will fix the problem:
https://github.com/rapidsai/cudf/blob/a65a474d25c0c70e43fcc8d166264ff329243dcd/python/cudf/comm/gpuarrow.py#L43-L53

**Steps/Code to reproduce bug**
Need to be running an OmniSci server with GPU capabilities:

```python
import numpy as np
import pandas as pd
import pymapd

int8arr = np.array([1,2,3,4,5], dtype='int8')
int8df = pd.DataFrame(int8arr, columns=['int8col'])

con = pymapd.connect(host="localhost", port=6274, dbname="mapd", user="mapd", password="HyperInteractive")
con.load_table("int_table_bug", int8df, method="arrow")

gdf = con.select_ipc_gpu("select * from int_table_bug")

In [4]: gdf = con.select_ipc_gpu("select * from int_table_bug")
Traceback (most recent call last):

  File "<ipython-input-4-29f7c516646a>", line 1, in <module>
    gdf = con.select_ipc_gpu("select * from int_table_bug")

  File "/home/rzwitch/pymapd/pymapd/connection.py", line 278, in select_ipc_gpu
    df = _parse_tdf_gpu(tdf)

  File "/home/rzwitch/pymapd/pymapd/_parsers.py", line 206, in _parse_tdf_gpu
    reader = GpuArrowReader(schema_buffer, darr)

  File "/home/rzwitch/miniconda3/envs/cudf06/lib/python3.6/site-packages/cudf/comm/gpuarrow.py", line 175, in __init__
    self._open()

  File "/home/rzwitch/miniconda3/envs/cudf06/lib/python3.6/site-packages/cudf/comm/gpuarrow.py", line 209, in _open
    dtype=_schema_to_dtype(**layout['dtype']),

  File "/home/rzwitch/miniconda3/envs/cudf06/lib/python3.6/site-packages/cudf/comm/gpuarrow.py", line 52, in _schema_to_dtype
    raise NotImplementedError(fmt.format(name, bitwidth))

NotImplementedError: unsupported type INT8 8-bits

```

**Expected behavior**
The expectation is that a cudf can be created from an Arrow buffer with an `int8` column, just like it can when using `cudf.DataFrame.from_pandas()` where the pandas dataframe has an `int8` column.

**Environment details (please complete the following information):**
cudf 0.6, bare metal (home workstation) on Ubuntu 16.04 LTS

**Comment by randyzwitch** [comment]
I have confirmed that adding `INT8` to the tuple on line 46 fixes the issue. I'm willing to submit a PR, but need some guidance how to test this, since setting up OmniSci to do the test doesn't make sense.

**Comment by kkraus14** [comment]
@randyzwitch The curent tests are in `python/cudf/tests/test_gpu_arrow_parser.py` which should serve as a guide as to how to extend to test for `int8`.
