### ISSUE TITLE
[BUG] undefined reference to `TestParameters<std::tuple<std::vector<int, std::allocator<int>

### ISSUE THREAD

**Issue by nasica88** [rapidsai/cudf#1384]
**Describe the bug**
When building from source, 'make' produces "undefined reference to `TestParameters<std::tuple..." error after completing 92% as below.

[ 92%] Linking CUDA executable ../gtests/HASHING_TEST

**Steps/Code to reproduce bug**

After completing cmake successfully in build directory, running 'make' produces "nvcc fatal : A single input file is required..." error as below.

u0017649@sys-97701:~/files/cudf/cpp/build$ cmake .. -DCMAKE_INSTALL_PREFIX=~/anaconda3

u0017649@sys-97701:~/files/cudf/cpp/build$ make -j2 VERBOSE=1
...
[ 92%] Linking CUDA executable ../gtests/HASHING_TEST
cd /home/u0017649/files/cudf/cpp/build/tests && /home/u0017649/anaconda3/bin/cmake -E cmake_link_script CMakeFiles/HASHING_TEST.dir/link.txt --verbose=1
/usr/bin/g++  CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o CMakeFiles/HASHING_TEST.dir/hashing/hash_test.cu.o CMakeFiles/HASHING_TEST.dir/utilities/cudf_test_utils.cu.o CMakeFiles/HASHING_TEST.dir/cmake_device_link.o -o ../gtests/HASHING_TEST  -L/home/u0017649/files/cudf/cpp/build/lib  -L/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/lib  -L/home/u0017649/files/cudf/cpp/build/googletest/install/lib -Wl,-rpath,/home/u0017649/files/cudf/cpp/build/lib:/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/lib:/home/u0017649/files/cudf/cpp/build/googletest/install/lib:/home/u0017649/files/cudf/cpp/build:/home/u0017649/files/cudf/cpp/build/rmm -lgmock -lgtest -lgmock_main -lgtest_main -lpthread ../libcudf.so ../rmm/librmm.so /usr/local/cuda/targets/ppc64le-linux/lib/libnvToolsExt.so -lcudart -lcuda ../arrow/install/lib/libarrow.a /usr/lib/powerpc64le-linux-gnu/libz.so -lNVCategory -lNVStrings -lnvrtc  -L"/usr/local/cuda/targets/ppc64le-linux/lib/stubs" -L"/usr/local/cuda/targets/ppc64le-linux/lib" -lcudadevrt -lcudart_static -lrt -lpthread -ldl
/usr/bin/ld: CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o:(.toc+0x0): undefined reference to `TestParameters<std::tuple<std::vector<int, std::allocator<int> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> >, std::vector<double, std::allocator<double> > >, (gdf_hash_func)0, 0, 2, 3>::cols_to_hash'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/HASHING_TEST.dir/build.make:147: gtests/HASHING_TEST] Error 1
make[2]: Leaving directory '/home/u0017649/files/cudf/cpp/build'
make[1]: *** [CMakeFiles/Makefile2:2079: tests/CMakeFiles/HASHING_TEST.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Expected behavior**

'make' should be completed without error.

**Environment details (please complete the following information):**

Environment location: IBM POWER8 cloud
Method of cuDF install: from source

u0017649@sys-97701:~/files/cudf$ ./print_env.sh
**git***
commit b63e971f9c2348db6c12882c882139b2e0988d1e (HEAD -> branch-0.7, origin/branch-0.7, origin/HEAD)
Merge: bff6849c 3d473a37
Author: Keith Kraus <keith.j.kraus@gmail.com>
Date:   Tue Apr 9 18:57:45 2019 -0400

    Merge pull request #1381 from mrocklin/get-numeric-data

    Implement DataFrame._get_numeric_data

***OS Information***
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"
NAME="Ubuntu"
VERSION="18.10 (Cosmic Cuttlefish)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.10"
VERSION_ID="18.10"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
Linux sys-97701 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:20:58 UTC 2018 ppc64le ppc64le ppc64le GNU/Linux

***GPU Information***
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

***CPU***
Architecture:        ppc64le
Byte Order:          Little Endian
CPU(s):              2
On-line CPU(s) list: 0,1
Thread(s) per core:  2
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Model:               2.1 (pvr 004b 0201)
Model name:          POWER8E (raw), altivec supported
Hypervisor vendor:   KVM
Virtualization type: para
L1d cache:           64K
L1i cache:           32K
NUMA node0 CPU(s):   0,1

***CMake***
/home/u0017649/anaconda3/bin/cmake
cmake version 3.12.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***
/usr/bin/g++
g++ (Ubuntu 7.3.0-29ubuntu1) 7.3.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

***nvcc***
/usr/local/cuda/bin/nvcc
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:10:00_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

***Python***
/home/u0017649/anaconda3/bin/python
Python 3.7.0

***Environment Variables***
PATH                            : /home/u0017649/anaconda3/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH                 : /home/u0017649/anaconda3/lib:/usr/local/cuda/lib64:/usr/local/lib64:/usr/local/lib:/usr/lib64:/usr/lib:/lib64:/lib
NUMBAPRO_NVVM                   :
NUMBAPRO_LIBDEVICE              :
CONDA_PREFIX                    :
PYTHON_PATH                     :

***conda packages***
/home/u0017649/anaconda3/bin/conda
# packages in environment at /home/u0017649/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.11                   py37_0
anaconda                  5.3.0                    py37_0
anaconda-client           1.7.2                    py37_0
anaconda-project          0.8.2                    py37_0
appdirs                   1.4.3            py37h28b3542_0
arrow                     0.10.0                     py_1    conda-forge
asn1crypto                0.24.0                   py37_0
astroid                   2.0.4                    py37_0
astropy                   3.0.4            py37h14c3975_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
automat                   0.7.0                    py37_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.shutil_get_terminal_size 1.0.0                    py37_2
beautifulsoup4            4.6.3                    py37_0
bitarray                  0.8.3            py37h14c3975_0
bkcharts                  0.2                      py37_0
blas                      1.0                    openblas
bleach                    2.1.4                    py37_0
blosc                     1.14.4               hdbcaa40_0
bokeh                     0.13.0                   py37_0
boost                     1.67.0                   py37_4
boost-cpp                 1.67.0               h14c3975_4
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h035aef0_1
brotli                    1.0.7                he6710b0_0
bzip2                     1.0.6                h14c3975_5
ca-certificates           2018.03.07           hf82bc7d_0
cairo                     1.14.12              h8948797_3
certifi                   2018.8.24                py37_1
cffi                      1.11.5           py37h9745a5d_0
chardet                   3.0.4                    py37_1
click                     6.7                      py37_0
cloudpickle               0.5.5                    py37_0
clyent                    1.2.2                    py37_1
cmake                     3.12.2               h52cb24c_0
colorama                  0.3.9                    py37_0
conda                     4.5.11                   py37_0
conda-build               3.15.1                   py37_0
conda-env                 2.6.0                         1
constantly                15.1.0           py37h28b3542_0
contextlib2               0.5.5                    py37_0
cryptography              2.3.1            py37hc365091_0
curl                      7.61.0               h84994c4_0
cycler                    0.10.0                   py37_0
cython                    0.28.5           py37hf484d3e_0
Cython                    0.29                      <pip>
cytoolz                   0.9.0.1          py37h14c3975_1
dask                      0.19.1                   py37_0
dask-core                 0.19.1                   py37_0
datashape                 0.5.4                    py37_1
decorator                 4.3.0                    py37_0
distributed               1.23.1                   py37_0
docutils                  0.14                     py37_0
entrypoints               0.2.3                    py37_2
et_xmlfile                1.0.1                    py37_0
expat                     2.2.6                he6710b0_0
fastcache                 1.0.2            py37h14c3975_2
filelock                  3.0.8                    py37_0
flask                     1.0.2                    py37_1
flask-cors                3.0.6                    py37_0
flatbuffers               1.10.0               he6710b0_0
fontconfig                2.13.0               h9420a91_0
freetype                  2.9.1                h8a8886c_0
get_terminal_size         1.0.0                         0
gevent                    1.3.6            py37h7b6447c_0
gflags                    2.1.2                         0
glib                      2.56.2               hd408876_0
glob2                     0.6                      py37_0
gmp                       6.1.2                h7f7056e_2
gmpy2                     2.0.8            py37h10f8cd9_2
greenlet                  0.4.15           py37h7b6447c_0
h5py                      2.8.0            py37h8d01980_0
hdf5                      1.10.2               hba1933b_1
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
hyperlink                 18.0.0                   py37_0
icu                       58.2                 h64fc554_1
idna                      2.7                      py37_0
imageio                   2.4.1                    py37_0
imagesize                 1.1.0                    py37_0
incremental               17.5.0                   py37_0
ipykernel                 4.9.0                    py37_1
ipython                   6.5.0                    py37_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.1                    py37_0
isort                     4.3.4                    py37_0
itsdangerous              0.24                     py37_1
jbig                      2.1                  h14c3975_0
jdcal                     1.4                      py37_0
jedi                      0.12.1                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hcb7ba68_2
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.3                    py37_0
jupyter_console           5.2.0                    py37_1
jupyter_core              4.4.0                    py37_0
jupyterlab                0.34.9                   py37_0
jupyterlab_launcher       0.13.1                   py37_0
kiwisolver                1.0.1            py37hf484d3e_0
lazy-object-proxy         1.3.1            py37h14c3975_2
libboost                  1.67.0               h46d08c1_4
libcurl                   7.61.0               h1ad7b7a_0
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hf62a594_5
libgcc-ng                 8.2.0                h822a55f_1
libgfortran-ng            7.3.0                h822a55f_1
libopenblas               0.2.20               h9ac9557_7
libpng                    1.6.32               h288d48a_4
libsodium                 1.0.16               h1bed415_0
libstdcxx-ng              8.2.0                h822a55f_1
libtiff                   4.0.9                he85c1e1_1
libuuid                   1.0.3                h1bed415_2
libxcb                    1.13                 h1bed415_0
libxml2                   2.9.8                h26e45fe_1
libxslt                   1.1.32               h1312cb7_0
locket                    0.2.0                    py37_1
lxml                      4.2.5            py37hefd8a0e_0
lz4-c                     1.8.3             hf484d3e_1001    conda-forge
lzo                       2.10                 h0dabc4d_2
markupsafe                1.0              py37h14c3975_1
matplotlib                2.2.3            py37hb69df0a_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.3            py37h14c3975_1
more-itertools            4.3.0                    py37_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
mpmath                    1.0.0                    py37_2
msgpack-python            0.5.6            py37h6bb024c_1
multipledispatch          0.6.0                    py37_0
nbconvert                 5.3.1                    py37_0
nbformat                  4.4.0                    py37_0
ncurses                   6.1                  hf484d3e_0
networkx                  2.1                      py37_0
nltk                      3.3.0                    py37_0
nose                      1.3.7                    py37_2
notebook                  5.6.0                    py37_0
numexpr                   2.6.7            py37h98f89e9_0
numpy                     1.14.5           py37h2aefc1b_4
numpy-base                1.14.5           py37h2b20989_4
numpydoc                  0.8.0                    py37_0
odo                       0.5.1                    py37_0
olefile                   0.46                     py37_0
openblas                  0.2.20                        7
openblas-devel            0.2.20                        7
openpyxl                  2.5.6                    py37_0
openssl                   1.0.2p               h14c3975_0
packaging                 17.1                     py37_0
pandas                    0.23.4           py37h04863e7_0
pandoc                    2.0.0.1                       1
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
partd                     0.3.8                    py37_0
patchelf                  0.9                  hf484d3e_2
path.py                   11.1.0                   py37_0
pathlib2                  2.3.2                    py37_0
patsy                     0.5.0                    py37_0
pcre                      8.42                 hf484d3e_0
pep8                      1.7.1                    py37_0
pexpect                   4.6.0                    py37_0
pickleshare               0.7.4                    py37_0
pillow                    5.2.0            py37h2879dc4_0
pip                       10.0.1                   py37_0
pixman                    0.34.0               h1f8d8dc_3
pkginfo                   1.4.2                    py37_1
pluggy                    0.7.1                    py37_0
ply                       3.11                     py37_0
prometheus_client         0.3.1                    py37_0
prompt_toolkit            1.0.15                   py37_0
psutil                    5.4.7            py37h14c3975_0
ptyprocess                0.6.0                    py37_0
py                        1.6.0                    py37_0
py-boost                  1.67.0           py37h04863e7_4
pyarrow                   0.13.1.dev51+g2a4e48e3.d20190410           <pip>
pyasn1                    0.4.4                    py37_0
pyasn1-modules            0.2.2                    py37_0
pycodestyle               2.4.0                    py37_0
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.18                     py37_1
pycrypto                  2.6.1            py37h14c3975_9
pycurl                    7.43.0.2         py37hb7f436b_0
pyflakes                  2.0.0                    py37_0
pygments                  2.2.0                    py37_0
pylint                    2.1.1                    py37_0
pyodbc                    4.0.24           py37he6710b0_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.2.0                    py37_1
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37ha205bf6_0
pytest                    3.8.0                    py37_0
pytest-arraydiff          0.2              py37h39e3cac_0
pytest-astropy            0.4.0                    py37_0
pytest-doctestplus        0.1.3                    py37_0
pytest-openfiles          0.3.0                    py37_0
pytest-remotedata         0.3.0                    py37_0
python                    3.7.0                h78a52d1_0
python-dateutil           2.7.3                    py37_0
pytz                      2018.5                   py37_0
pywavelets                1.0.0            py37hdd07704_0
pyyaml                    3.13             py37h14c3975_0
pyzmq                     17.1.2           py37h14c3975_0
rapidjson                 1.1.0                h6bb024c_0
readline                  7.0                  h7b6447c_5
requests                  2.19.1                   py37_0
rhash                     1.3.6             h14c3975_1001    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
scikit-image              0.14.0           py37hf484d3e_1
scikit-learn              0.19.1           py37h6cfcb94_0
scipy                     1.1.0            py37h9c1e066_0
seaborn                   0.9.0                    py37_0
send2trash                1.5.0                    py37_0
service_identity          17.0.0           py37h28b3542_0
setuptools                40.2.0                   py37_0
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
six                       1.11.0                   py37_1
snappy                    1.1.7                h1532aa0_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.0.1                    py37_0
sortedcontainers          2.0.5                    py37_0
sphinx                    1.7.9                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
sqlalchemy                1.2.11           py37h7b6447c_0
sqlite                    3.24.0               h84994c4_0
statsmodels               0.9.0            py37h035aef0_0
sympy                     1.2                      py37_0
tblib                     1.3.2                    py37_0
terminado                 0.8.1                    py37_1
testpath                  0.3.1                    py37_0
thrift                    0.11.0           py37hf484d3e_0
tk                        8.6.8                hbc83047_0
toolz                     0.9.0                    py37_0
tornado                   5.1              py37h14c3975_0
tqdm                      4.26.0           py37h28b3542_0
traitlets                 4.3.2                    py37_0
twisted                   18.4.0           py37h14c3975_0
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h2c717c6_0
urllib3                   1.23                     py37_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.31.1                   py37_0
widgetsnbextension        3.4.1                    py37_0
wrapt                     1.10.11          py37h14c3975_2
xlrd                      1.1.0                    py37_1
xlsxwriter                1.1.0                    py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                h1bed415_2
zeromq                    4.2.5                hf484d3e_0
zict                      0.1.3                    py37_0
zlib                      1.2.11               hb9fc6fc_2
zope                      1.0                      py37_1
zope.interface            4.5.0            py37h14c3975_0
zstd                      1.3.8             h4a5956a_1002    conda-forge

**Comment by j-ieong** [comment]
Hi @nasica88, could you paste the verbose command of nvcc when it's compiling the cuda .cu files?

**Comment by nasica88** [comment]
@j-ieong  Here it is.

cd /home/u0017649/files/cudf/cpp/build/tests && /usr/local/cuda/bin/nvcc  -DARROW_METADATA_V4 -DARROW_VERSION=1210 -I/home/u0017649/files/cudf/cpp/build/googletest/install/include -I/home/u0017649/files/cudf/cpp/build/arrow/install/include -I/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/include -I/usr/local/cuda/targets/ppc64le-linux/include -I/home/u0017649/files/cudf/cpp/build/include -I/home/u0017649/files/cudf/cpp/include -I/home/u0017649/files/cudf/cpp -I/home/u0017649/files/cudf/cpp/src -I/home/u0017649/files/cudf/cpp/thirdparty/cub -I/home/u0017649/files/cudf/cpp/thirdparty/moderngpu/src -I/home/u0017649/files/cudf/cpp/thirdparty/rmm/include -I/home/u0017649/files/cudf/cpp/tests/, -I/home/u0017649/files/cudf/cpp/thirdparty/dlpack/include  -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 --expt-extended-lambda --expt-relaxed-constexpr -Werror cross-execution-space-call -Xcompiler -Wall,-Werror -O3 -DNDEBUG -Xcompiler=-fPIE   -std=c++14 -x cu -c /home/u0017649/files/cudf/cpp/tests/hash_map/multimap_test.cu -o CMakeFiles/HASH_MAP_TEST.dir/hash_map/multimap_test.cu.o
[ 85%] Linking CUDA device code CMakeFiles/HASHING_TEST.dir/cmake_device_link.o
cd /home/u0017649/files/cudf/cpp/build/tests && /home/u0017649/anaconda3/bin/cmake -E cmake_link_script CMakeFiles/HASHING_TEST.dir/dlink.txt --verbose=1
/usr/local/cuda/bin/nvcc   -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_70,code=compute_70 --expt-extended-lambda --expt-relaxed-constexpr -Werror cross-execution-space-call -Xcompiler -Wall,-Werror -O3 -DNDEBUG -Xcompiler=-fPIC -Wno-deprecated-gpu-targets -shared -dlink CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o CMakeFiles/HASHING_TEST.dir/hashing/hash_test.cu.o CMakeFiles/HASHING_TEST.dir/utilities/cudf_test_utils.cu.o -o CMakeFiles/HASHING_TEST.dir/cmake_device_link.o  -L/home/u0017649/files/cudf/cpp/build/lib  -L/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/lib  -L/home/u0017649/files/cudf/cpp/build/googletest/install/lib -lgmock -lgtest -lgmock_main -lgtest_main -lpthread -Xnvlink ../libcudf.so -Xnvlink ../rmm/librmm.so -Xnvlink /usr/local/cuda/targets/ppc64le-linux/lib/libnvToolsExt.so -lcudart -lcuda ../arrow/install/lib/libarrow.a -Xnvlink /usr/lib/powerpc64le-linux-gnu/libz.so -lNVCategory -lNVStrings -lnvrtc
[ 86%] Linking CUDA executable ../gtests/HASHING_TEST
cd /home/u0017649/files/cudf/cpp/build/tests && /home/u0017649/anaconda3/bin/cmake -E cmake_link_script CMakeFiles/HASHING_TEST.dir/link.txt --verbose=1
/usr/bin/g++  CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o CMakeFiles/HASHING_TEST.dir/hashing/hash_test.cu.o CMakeFiles/HASHING_TEST.dir/utilities/cudf_test_utils.cu.o CMakeFiles/HASHING_TEST.dir/cmake_device_link.o -o ../gtests/HASHING_TEST  -L/home/u0017649/files/cudf/cpp/build/lib  -L/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/lib  -L/home/u0017649/files/cudf/cpp/build/googletest/install/lib -Wl,-rpath,/home/u0017649/files/cudf/cpp/build/lib:/home/u0017649/files/cudf/cpp/build/arrow/build/flatbuffers_ep-prefix/src/flatbuffers_ep-install/lib:/home/u0017649/files/cudf/cpp/build/googletest/install/lib:/home/u0017649/files/cudf/cpp/build:/home/u0017649/files/cudf/cpp/build/rmm -lgmock -lgtest -lgmock_main -lgtest_main -lpthread ../libcudf.so ../rmm/librmm.so /usr/local/cuda/targets/ppc64le-linux/lib/libnvToolsExt.so -lcudart -lcuda ../arrow/install/lib/libarrow.a /usr/lib/powerpc64le-linux-gnu/libz.so -lNVCategory -lNVStrings -lnvrtc  -L"/usr/local/cuda/targets/ppc64le-linux/lib/stubs" -L"/usr/local/cuda/targets/ppc64le-linux/lib" -lcudadevrt -lcudart_static -lrt -lpthread -ldl
/usr/bin/ld: CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o:(.toc+0x0): undefined reference to `TestParameters<std::tuple<std::vector<int, std::allocator<int> >, std::vector<double, std::allocator<double> >, std::vector<int, std::allocator<int> >, std::vector<double, std::allocator<double> > >, (gdf_hash_func)0, 0, 2, 3>::cols_to_hash'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/CMakeFiles/HASHING_TEST.dir/build.make:147: gtests/HASHING_TEST] Error 1
make[2]: Leaving directory '/home/u0017649/files/cudf/cpp/build'
make[1]: *** [CMakeFiles/Makefile2:1963: tests/CMakeFiles/HASHING_TEST.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by harrism** [comment]
@nasica88 Can you try this? In the file cpp/tests/hashing/hash_partition_test.cu, comment out the lines I have commented out here:
```typedef ::testing::Types< TestParameters< VTuple<int32_t>, GDF_HASH_IDENTITY, 0 >,
                          TestParameters< VTuple<int32_t, int32_t>, GDF_HASH_MURMUR3, 0, 1>,
                          TestParameters< VTuple<float, double>, GDF_HASH_MURMUR3, 1>,
                          TestParameters< VTuple<int64_t, int32_t>, GDF_HASH_MURMUR3, 1>,
                          TestParameters< VTuple<int64_t, int64_t>, GDF_HASH_MURMUR3, 0, 1>,
                          TestParameters< VTuple<int64_t, int64_t, float, double>, GDF_HASH_IDENTITY, 2, 3>,
//                          TestParameters< VTuple<int32_t, double, int32_t, double>, GDF_HASH_MURMUR3, 0, 2, 3>,
//                          TestParameters< VTuple<int64_t, int64_t, float, double>, GDF_HASH_MURMUR3, 1, 3>,
//                          TestParameters< VTuple<int64_t, int64_t>, GDF_HASH_MURMUR3, 0, 1>,
//                          TestParameters< VTuple<float, int32_t>, GDF_HASH_MURMUR3, 0>
                         >Implementations;```

I've seen this before on another system... I think it might be a compiler template argument limit somewhere...

**Comment by j-ieong** [comment]
@nasica88 Sorry for the late reply. Hrmm, the nvcc output doesn't have anything that seems out of place to me; similar to mine.

You can try @harrism's suggestion to comment out those lines.
Only other thing from the link error I can speculate is that you need to define `cols_to_hash` outside the class as well. You can try adding these `+` lines into `hash_partition_test.cu`:

```cpp
template< typename tuple_of_vectors, 
          gdf_hash_func hash,
          int... cols>
struct TestParameters
{
  static_assert((std::tuple_size<tuple_of_vectors>::value >= sizeof...(cols)), 
      "The number of columns to hash must be less than or equal to the total number of columns.");

  // The tuple of vectors that determines the number and types of the columns 
  using multi_column_t = tuple_of_vectors;

  // The hash function to use
  constexpr static const gdf_hash_func gdf_hash_function = hash;

  // The number of columns to hash
  constexpr static const int num_cols_to_hash{sizeof...(cols)};

  // The indices of the columns that will be hashed to determine the partitions
  constexpr static const std::array<int, sizeof...(cols)> cols_to_hash{{cols...}};
};
+template< typename tuple_of_vectors, 
+          gdf_hash_func hash,
+          int... cols>
+constexpr const std::array<int, sizeof...(cols)> TestParameters<tuple_of_vectors, hash, cols...>::cols_to_hash;
```

**Comment by nasica88** [comment]
@harrism  Sorry for my late response.  I lost my environment, and had to build a new one... and YES !  Your suggestion worked !  Thanks a lot !

...
[ 84%] Built target HASH_MAP_TEST
[ 86%] Built target UNARY_TEST
[ 89%] Built target ORDERBY_TEST
[ 91%] Built target BIT_MASK_TEST
[ 92%] Building CUDA object tests/CMakeFiles/HASHING_TEST.dir/hashing/hash_partition_test.cu.o
[ 94%] Built target REPLACE_NULLS_TEST
[ 97%] Built target BINARY_TEST
[ 97%] Linking CUDA device code CMakeFiles/HASHING_TEST.dir/cmake_device_link.o
[ 98%] Linking CUDA executable ../gtests/HASHING_TEST
[100%] Built target HASHING_TEST

**Comment by harrism** [comment]
@nasica88 sorry for delay. Did you try *my* suggestion (commenting out some of the test parameters, thus reducing test coverage), or did you try @j-ieong 's suggestion of adding 

```
template< typename tuple_of_vectors, 
           gdf_hash_func hash,
           int... cols>
 constexpr const std::array<int, sizeof...(cols)> TestParameters<tuple_of_vectors, hash, cols...>::cols_to_hash;```

(see https://github.com/rapidsai/cudf/issues/1384#issuecomment-483936604)

If the former, can you try @j-ieong 's suggestion too? If it works, that could be the fix...

**Comment by nasica88** [comment]
@harrism  The former - I applied your suggestion of commenting out some of the test parameters.  I'll try @j-ieong 's suggestion, and let you know the result.

**Comment by nasica88** [comment]
@harrism , @j-ieong , Good news.  @j-ieong 's suggestion of adding those lines works just fine.   

...
[ 95%] Linking CUDA executable ../gtests/GROUPBY_TEST
[ 95%] Built target GROUPBY_TEST
[ 96%] Linking CUDA device code CMakeFiles/COPYING_TEST.dir/cmake_device_link.o
[ 97%] Linking CUDA executable ../gtests/COPYING_TEST
[ 97%] Built target COPYING_TEST
[ 97%] Linking CUDA device code CMakeFiles/JOIN_TEST.dir/cmake_device_link.o
[ 98%] Linking CXX executable ../gtests/JOIN_TEST
[ 98%] Built target JOIN_TEST
[100%] Linking CUDA device code CMakeFiles/UTILITIES_TEST.dir/cmake_device_link.o
[100%] Linking CUDA executable ../gtests/UTILITIES_TEST
[100%] Built target UTILITIES_TEST

**Comment by harrism** [comment]
@jrhemstad since you wrote these tests, what do you think of this solution?
