### ISSUE TITLE
[FEA] Clearer error for bad filename for jsonlines reader

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#13845]
If I give a bad path/filename when trying to read_json w/ lines=True, I get a confusing error, which might send me down a path debugging the JSON format instead of realizing I was giving a bad path:
```
import cudf

cudf.read_json("nonexistent_filename.jsonl", lines=True)
```

Trace:
```
RuntimeError: CUDF failure at: /opt/conda/conda-bld/work/cpp/src/io/json/json_column.cu:967: Input needs to be an array of arrays or an array of (nested) objects
```

For example, read_csv handles this nicely:
```
cudf.read_csv("non_existent_file.csv")
```
```
FileNotFoundError: non_existent_file.csv could not be resolved to any files
```

**Comment by davidwendt** [comment]
Looks like the behavior has changed a bit from #13026
We probably should combine these issues.

**Comment by GregoryKimball** [comment]
Closing in favor of #13026
