### ISSUE TITLE
[BUG] Some libcudf gtests failing in with a Debug build and identify-stream-usage enabled

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#13859]
The following gtests fail in a Debug build of libcudf when using `ninja test` or `ctest`
```
	  3 - TIMESTAMPS_TEST (Failed)
	  4 - ERROR_TEST (Failed)
	 11 - HASH_MAP_TEST (Failed)
	 33 - JSON_TYPE_CAST_TEST (Failed)
	 38 - LOGICAL_STACK_TEST (Failed)
	 39 - FST_TEST (Failed)
	 40 - TYPE_INFERENCE_TEST (Failed)
	 44 - SPAN_TEST (Failed)
	 47 - DEVICE_ATOMICS_TEST (Failed)
	 58 - DISPATCHER_TEST (Failed)
```
None of these fail when run individually, only when run with `ninja test`
To recreate the failures individually requires enabling the identify-stream-usage feature by setting the following 2 env vars:
```
$ export GTEST_CUDF_STREAM_MODE=new_cudf_default
$ export LD_PRELOAD=/cudf/cpp/build/libcudf_identify_stream_usage_mode_cudf.so
```

Most of these fail right away with an error like the following:
```
$ gtests/TIMESTAMPS_TEST
[==========] Running 40 tests from 10 test suites.
[----------] Global test environment set-up.
[----------] 4 tests from ChronoColumnTest/0, where TypeParam = cuda::std::__4::chrono::time_point<cuda::std::__4::chrono::system_clock, cuda::std::__4::chrono::duration<int, cuda::std::__4::ratio<86400l, 1l> > >
[ RUN      ] ChronoColumnTest/0.ChronoDurationsMatchPrimitiveRepresentation
pure virtual method called
terminate called without an active exception
Aborted (core dumped)

```

The `gtests/ERROR_TEST` fails with a couple `"cudf_identify_stream_usage found unexpected stream!"` messages which I believe are incorrect.

The `SPAN_TEST` error can be recreated by using
```
gtests/SPAN_TEST --gtest_filter=-SpanTest.CanConstructFromDeviceContainers
```

I think this error needs to be addressed as a possible problem with how the identify-stream-usage feature is implemented.
I've not been able to determine who the error occurs though it may be at odds with how gtest is implemented.

**Comment by GregoryKimball** [comment]
@vyasr When you get a chance, would you please share your thoughts about these observations?

**Comment by vyasr** [comment]
I don't really have an idea of what's going on here. I'll investigate when I can, but will probably be a bit.
