### ISSUE TITLE
[FEA] Some (trivial) utility functions for gdf_column's

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1387]
There are some routine, mostly-trivial tasks we occasionally, or often, need to perform on `gdf_column`'s, the code for which is currently at best repeated and at worst partially-repeated in different places in libcudf. Also, when we use this code, we don't quite say what it is that we're doing:

* Ensuring a column is valid (e.g. not having more nulls than elements and a bunch of other checks)
* Determining whether two columns have matching types (which includes the nullability check) 
* Checking whether a column is nullable or not not. Right now we use the "implementation" of this check, i.e. check whether `some_column->valid == nullptr`, when we could say `is_nullable(some_column)`
* Determining whether two columns have compatible extra_type_info (which sometimes means doing nothing, depending on the dtype)

Let's have these utility functions implemented.

**Comment by harrism** [comment]
Fixed by #1390
