### ISSUE TITLE
[BUG] reindexing a DataFrame with a CategoricalIndex incorrectly matches label and drops Index name

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#13900]
**Describe the bug**
reindexing a DataFrame with a CategoricalIndex incorrectly matches label and drops Index name

**Steps/Code to reproduce bug**
```
In [53]: import cudf; import numpy as np

In [54]: cudf.__version__
Out[54]: '23.10.00'

In [55]: df3 = cudf.DataFrame(
    ...: 
    ...:     {"A": np.arange(3), "B": cudf.Series(list("abc")).astype("category")}
    ...: 
    ...: )
    ...: 
    ...: 
    ...: 
    ...: df3 = df3.set_index("B")
    ...: 
    ...: df3
Out[55]: 
   A
B   
a  0
b  1
c  2

In [56]: df3.reindex(["a", "e"])
Out[56]: 
      A
a  <NA>
e  <NA>

In [57]: df3.to_pandas().reindex(["a", "e"])
Out[57]: 
     A
B     
a  0.0
e  NaN
```

**Expected behavior**
1. Reindexing by an existing category with CategoricalIndex should not return NA
2. The existing CategoricalIndex name should be maintained 

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by galipremsagar** [comment]
This also happens for any Index object.
