### ISSUE TITLE
[BUG] Groupby object returns erroneous results for subsequent nth calls

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#13923]
**Describe the bug**
Groupby object returns erroneous results for subsequent nth calls

**Steps/Code to reproduce bug**
```
In [63]: import cudf; import numpy as np

In [64]: df = cudf.DataFrame([[1, np.nan], [1, 4], [5, 6]], columns=["A", "B"])

In [65]: g = df.groupby("A")

In [66]: g.nth(-1)
Out[66]: 
   B
A   
1  4
5  6

In [67]: g.nth(0)  # same result for any n
Out[67]: 
   None
A      
1     0
5     0

In [68]: pdf = df.to_pandas()

In [69]: g = pdf.groupby("A")

In [70]: g.nth(-1)
Out[70]: 
     B
A     
1  4.0
5  6.0

In [71]: g.nth(0)
Out[71]: 
     B
A     
1  NaN
5  6.0
```

**Expected behavior**
Looks like there's some errant state held in the groupby object that makes subsequent groupby.nth calls incorrect. Should match the pandas result

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by wence-** [comment]
see also https://github.com/rapidsai/cudf/issues/13390

**Comment by mroeschke** [comment]
> see also #13390

Ah! So this is a problem generally with most/(any?) subsequent use of a groupby object
