### ISSUE TITLE
[FEA] Introduce the pylibcudf API and subpackage

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#13921]
### Background

cuDF-python is the common way for Python users to interact with libcudf, the CUDA/C++ computational core for RAPIDS dataframe and database operations. However, cuDF-python is designed to closely correspond with the pandas API, and in the process incurs some semantic overhead to libcudf algorithms. For python applications looking for accelerated dataframe operations and where API matching is not useful, "pylibcudf" provides a direct way for python ecosystem to use libcudf. Pylibcudf also makes libcudf APIs available to the python ecosystem even if they are not supported in pandas ([e.g. TEXT](https://github.com/rapidsai/cudf/issues/9555)).

In addition, we can improve the performance and design of cuDF-python by building on a "pylibcudf" foundation and refactoring extra complexity in cuDF-python's Cython layer.

### Example performance
Here is an example of the API design we have in mind for pylibcudf. 
```
    # cv1, cv2 and cv3 are ColumnView objects
    tv = pylibcudf.TableView([cv1, cv2])
    gb = pylibcudf.GroupBy(tv)

    req = pylibcudf.AggregationRequest(cv3, [pylibcudf.GroupbyAggregation.sum()])
    keys, results = gb.aggregate([req])
```

Here are some draft performance results from our prototype, showing good throughput and low overhead.
![image](https://github.com/rapidsai/cudf/assets/12725111/b9612e5b-65d5-4a22-b850-07fc7486a60e)

**Comment by vyasr** [comment]
Before we can close this issue we will also need to add comprehensive testing. For now, every pylibcudf API is being developed as a back-end for a cuDF Python API, so the existing Python test suite gives us sufficient coverage. We will want to come back and remedy this gap before actually extracting pylibcudf as a separate package.

**Comment by vyasr** [comment]
pylibcudf development is now under way. I have create [a project board for tracking](https://github.com/orgs/rapidsai/projects/121) as well as a number of issues to discuss more specific topics. I am therefore now closing this issue in favor of tracking using those.

**Comment by GregoryKimball** [comment]
FYI https://github.com/rapidsai/cudf/issues/15162 is the spiritual successor to this issue
