### ISSUE TITLE
[QST] Internal Error while loading CuDF - Cuda 12.2

### ISSUE THREAD

**Issue by nnagarajan** [rapidsai/cudf#13949]
Internal Error while loading CuDF. Is Nvidia Rapids compatible with Cuda 12.2 ?  Any known resolution for the RuntimeError ? 

Environment
Rocky Linux 8.8
Cuda 12.2

>>> default_df_orig = pd.read_csv('data/default1.csv',index_col='ID')                                                                      
warn: error opening log file: Permission denied, logging will be disabled
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nnagarajan/anaconda3/envs/py3.9/lib/python3.9/site-packages/nvtx/nvtx.py", line 101, in inner
    result = func(*args, **kwargs)
  File "/home/nnagarajan/anaconda3/envs/py3.9/lib/python3.9/site-packages/cudf/io/csv.py", line 88, in read_csv
    df = libcudf.csv.read_csv(
  File "csv.pyx", line 426, in cudf._lib.csv.read_csv
RuntimeError: cuFile error at: /__w/cudf/cudf/python/cudf/_skbuild/linux-x86_64-3.9/cmake-build/_deps/kvikio-src/cpp/include/kvikio/file_handle.hpp:176: internal error

**Comment by madsbk** [comment]
I thought so but maybe not?

@nnagarajan can you try setting the environment variable `KVIKIO_COMPAT_MODE=1`, which will make KvikIO not use cuFile?

**Comment by nnagarajan** [comment]
Thank you @madsbk  for the solution, this works and I able to display the contents of the data frame on console.  

API Docs (https://docs.rapids.ai/api/libkvikio/nightly/classkvikio_1_1defaults.html) suggests that this should be enabled by default, any reason why need to set compatibility mode when on CUDA 12.2 ? 

Any timeline on when RAPIDS will make its API fully compatibility with CUDA 12.2 ?

**Comment by madsbk** [comment]
> API Docs (https://docs.rapids.ai/api/libkvikio/nightly/classkvikio_1_1defaults.html) suggests that this should be enabled by default, any reason why need to set compatibility mode when on CUDA 12.2 ?

No,  compatibility mode is only enabled if cufile wasn't found (or if running in WSL or ` /run/udev` isn't readable). 

On my local workstation KvikIO works fine with CUDA 12.2 in a new Conda environment.
```
mamba create -n kvikio-cuda12.2 -c rapidsai -c conda-forge cuda-version=12.2 kvikio
```

**Comment by bdice** [comment]
@madsbk `cuda-version=12.2` won't work yet -- only `cuda-version=12.0` has packages. Right now, `cuda-version=12.1` and `cuda-version=12.2` are placeholders. As a result, `kvikio` is probably falling back to CUDA 12.0 packages. We'd need to try building this from source to test it accurately.

**Comment by GregoryKimball** [comment]
@nnagarajan Please let us know if you would like to discuss further. In the meantime I would encourage you to try out our conda packages or Docker images.

**Comment by vyasr** [comment]
Now that newer CUDA versions are fully available on conda-forge the above should all be resolved.
