### ISSUE TITLE
[FEA] Overflow-safe facility for obtaining simple 1-D grid configurations

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1394]
Related to #1371.

Many of the kernels we launch directory have simple 1-dimensional grids, whose number of blocks should be the division-rounding-up of the number of elements by a block size (determined one way or another). Now, the calculation of this division may overflow, and the cases in which it overflows - input lengths very close to 2^31 - are not esoteric.

It would be nice if we had a facility which generates a CUDA launch configuration, for this case at least, and ensures the calculation is correct - so that we won't have to remember to do this every time. Also, it will save a few lines of code here and there.

**Comment by jrhemstad** [comment]
Agreed, this would be a useful utility.

**Comment by harrism** [comment]
Fixed by #1397
