### ISSUE TITLE
[FEA]  Get rid of gdf_column_sizeof()

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1400]
The cuDF API currently has the function
```
gdf_size_type gdf_column_sizeof();
```
which returns `sizeof(gdf_column)`. I believe this is completely redundant, both within libcudf itself and outside of it, as - if we expose gdf_columns, other parties also surely know what its size in bytes is.

**Comment by jrhemstad** [comment]
I agree, it's only usage is here https://github.com/rapidsai/cudf/blob/7d5e909bc8697919f4a21060feea266967ea4cef/cpp/src/io/utilities/wrapper_utils.hpp#L38 which was written by @j-ieong.

I believe this would be better replaced by making `col` a `gdf_column` member of the class instead of a `gdf_column*`, which avoids the need for heap allocation.

**Comment by j-ieong** [comment]
I was originally using `sizeof(gdf_column)` until I saw that there was an API for it and switched to that... :slightly_smiling_face: 

The IO readers need to eventually return the malloc'ed columns to the Python layer. This wrapper is simply for RAII lifetime management so stuff gets released in case of exceptions...

When we change to Cython and C++, then we can change how the columns are returned, but this is for maintaining the original CFFI behavior.

**Comment by eyalroz** [comment]
@j-ieong : So, I assume we can switch back to `sizeof(gdf_column)`, right? ... if so, let's do that.

When we change to Cython and C++ all sorts of things will happen; let's not pile on yet another thing that needs to be handled then.

**Comment by j-ieong** [comment]
@eyalroz Yup, there's no problem changing it and removing this API.

Yeah, I was just explaining why we have that wrapper as it is. Part of the reason is _because_ I didn't want to pile lots of changes for unrelated IO stuff... it's a rabbit hole of future improvements.

**Comment by harrism** [comment]
This is done, though we need an equivalent back in the public API. But closing this one.
