### ISSUE TITLE
[BUG] Conda environment has pip-installed dependencies, but doesn't depend on pip

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1401]
I'm using:

* branch-0.7 of cudf
* Devaun 2.0 ASCII 
* conda 4.6.11
* CUDA 9.2
* `conda/environments/cudf_dev_cuda9.2.yml`

When I
```
conda update -f conda/environments/cudf_dev_cuda9.2.yml
```

My conda tells me:
```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
```

**Comment by jrhemstad** [comment]
That's the same command I use to update my conda environments and I've never seen this error. 

Perhaps you have something in your environment that was previously pip installed?

**Comment by eyalroz** [comment]
@jrhemstad : Not that I know of, but the YAML file has:
```
 pip:
  - sphinx-markdown-tables
```
in it.

**Comment by kkraus14** [comment]
I think this was a recent change in conda to push towards explicitly adding `pip` as a dependency.

**Comment by kkraus14** [comment]
This is resolved, pip is now included in the environment files.

**Comment by yasirniazi** [comment]
The same issue is facing. Kindly guide. 
**yasirniazi@yasirniazi:~/2020plus-1.2.3$ conda env create -f environment_python.yml**
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.

**Comment by yasirniazi** [comment]
> This is resolved, pip is now included in the environment files.

how did you resolve?

**Comment by kkraus14** [comment]
pip is now included in the environment files: https://github.com/rapidsai/cudf/blob/branch-0.15/conda/environments/cudf_dev_cuda10.0.yml#L34
