### ISSUE TITLE
[BUG] Cannot assign DataFrame.column.name

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#14012]
**Describe the bug**
DataFrame.pop removes column name

**Steps/Code to reproduce bug**
```python
In [1]: import cudf

In [2]: df = cudf.DataFrame({"a": [1., 2.]})

In [3]: df.index.name = "baz"

In [4]: df
Out[4]: 
       a
baz     
0    1.0
1    2.0

In [5]: df["foo"] = "bar"

In [6]: df
Out[6]: 
       a  foo
baz          
0    1.0  bar
1    2.0  bar

In [7]: df.pop("foo")
Out[7]: 
baz
0    bar
1    bar
Name: foo, dtype: object

In [8]: df.columns.name # should be "baz"

In [9]: df.columns
Out[9]: Index(['a'], dtype='object')
```

**Expected behavior**
```python
In [8]: df.columns.name
"baz"
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by galipremsagar** [comment]
@mroeschke Is the example you provided for a different issue? Or were you referring to this:
```python
In [37]: df = cudf.DataFrame({"a": [1., 2.]})

In [38]: df
Out[38]: 
     a
0  1.0
1  2.0

In [39]: df.columns.name = "baz"

In [40]: df
Out[40]: 
     a
0  1.0
1  2.0

In [41]: df.columns
Out[41]: Index(['a'], dtype='object')
```

**Comment by mroeschke** [comment]
@galipremsagar is there a reason why `cudf.DataFrame`'s return pandas objects for `df.columns`? I think this might be the limitation why the name cannot be set

```
In [1]: import cudf

In [2]: df = cudf.DataFrame({"a": [1., 2.]})

In [8]: type(df.columns)
Out[8]: pandas.core.indexes.base.Index

In [9]: type(df.index)
Out[9]: cudf.core.index.RangeIndex
```

**Comment by vyasr** [comment]
I believe it is because most operations involving column names occur on the host, not on device. Storing the column names in a cudf Index would require constant H2D copies. @shwina may be able to provide more of the history here, but I do agree that this choice can sometimes cause confusion and make certain aspects of implementation harder.

**Comment by galipremsagar** [comment]
resolved in https://github.com/rapidsai/cudf/pull/17597
