### ISSUE TITLE
[FEA] Allow DataFrame.sort_index(level=n) to tiebreak on lexsortedness in mode.pandas_compatable

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#14011]
**Is your feature request related to a problem? Please describe.**
```python
In [1]: import cudf

In [2]:         df = cudf.DataFrame(
   ...:             {
   ...:                 "col1": ["b", "d", "b", "a"],
   ...:                 "col2": [3, 1, 1, 2],
   ...:                 "data": ["one", "two", "three", "four"],
   ...:             }
   ...:         )
   ...: 
   ...:         df2 = df.set_index(["col1", "col2"])

In [3]: df2
Out[3]: 
            data
col1 col2       
b    3       one
d    1       two
b    1     three
a    2      four

In [4]: df2.sort_index(level=0, key=None)
Out[4]: 
            data
col1 col2       
a    2      four
b    3       one
     1     three
d    1       two

In [7]: df2.to_pandas().sort_index(level=0, key=None)
Out[7]: 
            data
col1 col2       
a    2      four
b    1     three
     3       one
d    1       two
```

**Describe the solution you'd like**
The current behavior is still technically correct, but it appears that pandas tiebreaks on lexsortedness. It would be nice to mirror this behavior in pandas compatible mode

**Describe alternatives you've considered**
Manually lexsort after `sort_index`

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by wence-** [comment]
This is due to cudf not (yet) implementing behaviour for the `sort_remaining` keyword argument to `sort_index`.
