### ISSUE TITLE
[BUG] libcudf CI builds failing due to lack of `zlib` package

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#14021]
**Describe the bug**

[Recently](https://github.com/conda-forge/cmake-feedstock/pull/191/files), the conda feedstock for `cmake` updated its run exports to remove dependency on (amongst other things) the `zlib` conda package.

It seems like we were relying on this transitively being pulled in for our builds. See for example a recent failure: https://github.com/rapidsai/cudf/actions/runs/6033351272/job/16385609807#step:7:635

We should therefore probably make this dependency explicit in `dependencies.yaml` and the conda recipe `meta.yaml` for libcudf.

**Comment by bdice** [comment]
This is where we actually use zlib in libcudf. This is the part I was missing:

https://github.com/rapidsai/cudf/blob/c73ff70dc5ad85d71a0719606c688c2447d55d85/cpp/CMakeLists.txt#L170
https://github.com/rapidsai/cudf/blob/c73ff70dc5ad85d71a0719606c688c2447d55d85/cpp/src/io/text/bgzip_utils.cpp#L17
