### ISSUE TITLE
[BUG] Need to protect against NVstrings.h lack of include guards

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1402]
[NVstrings.h](https://github.com/NVIDIA/nvstrings/blob/master/NVStrings.h) version 0.3 does [not have include guards](https://github.com/NVIDIA/nvstrings/issues/9).

While we might be requiring a later version of it at some point in the future, that point is not now, and - we are including `NVStrings.h` in a bunch of places; which means we need to guard against double-including it.

**Comment by kkraus14** [comment]
This was resolved in NVStrings.
