### ISSUE TITLE
[QST] Regarding the usage of CMAKE_CXX11_ABI flag in cudf/cpp/CMakeLists.txt 

### ISSUE THREAD

**Issue by pradghos** [rapidsai/cudf#1406]
**What is your question?**
1. I can see that  `CMAKE_CXX11_ABI` flag  set by default without explicitly setting it up for `GNU compiler`. 
[ without setting `-DCMAKE_CXX11_ABI` in `CMAKE_COMMON_VARIABLES` ] 
 
``` 
if(CMAKE_COMPILER_IS_GNUCXX)
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")

    option(CMAKE_CXX11_ABI "Enable the GLIBCXX11 ABI" ON)
    if(CMAKE_CXX11_ABI)
        message(STATUS "CUDF: Enabling the GLIBCXX11 ABI")
```
Build log snippet: 
``` 
-- CUDF: Enabling the GLIBCXX11 ABI
   
-std=c++14 -x cu -c $SRC_DIR/cpp/src/comms/ipc/ipc.cu -o CMakeFiles/cudf.dir/src/comms/ipc/ipc.cu.o
```
Does that mean for a default case of `GNU compiler` cuDF supports `CXX11_ABI`  and `CMAKE_CXX_STANDARD` and `CMAKE_CUDA_STANDARD` are set to `14` ? 

2.  `set(CMAKE_CXX_STANDARD 14) set(CMAKE_CUDA_STANDARD 14)` are these the mandatory requirement for latest `cuDF` version to build. ? 

Thanks in advance for your response !

**Comment by kkraus14** [comment]
@pradghos Yes, the default case for `GNU compiler` is to use the new ABI, denoted by `CXX11_ABI`. The library uses a bunch of C++14 features, so `STANDARD 14` is required and is not an option.

**Comment by pradghos** [comment]
@kkraus14 Thanks for your response !
