### ISSUE TITLE
[FEA][JNI] Add JNI bindings for cudf::strings::integers_to_hex()

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#14081]
**Is your feature request related to a problem? Please describe.**
We need a way to convert a string col to a hex string col

**Describe the solution you'd like**
libcudf already supports this in convert_integers::integers_to_hex(). We should expose this method to Java

**Describe alternatives you've considered**
None

**Comment by gerashegalov** [comment]
you can reuse

https://github.com/NVIDIA/spark-rapids-jni/blob/ba6eefaf040a7eae1a4322d9ee5cff27a6fe65da/src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java#L112

https://github.com/NVIDIA/spark-rapids-jni/blob/ba6eefaf040a7eae1a4322d9ee5cff27a6fe65da/src/main/cpp/src/CastStringJni.cpp#L211-L215

**Comment by razajafri** [comment]
Thanks, let me confirm if that is what we want before closing this issue

**Comment by razajafri** [comment]
I have confirmed, this works thanks @gerashegalov

**Comment by razajafri** [comment]
Upon further investigation, the existing [feature](https://github.com/NVIDIA/spark-rapids-jni/blob/ba6eefaf040a7eae1a4322d9ee5cff27a6fe65da/src/main/java/com/nvidia/spark/rapids/jni/CastStrings.java#L112) can't be used as is because it drops the leading zeros which are needed when converting binary data to string to be printed to the screen
