### ISSUE TITLE
[BUG] Default type of empty list for `Index` should be `object` dtype

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#14091]
**Describe the bug**
When an empty list is passed to `Index` constructor `cudf` defaults to `float64`, whereas pandas defaults to `object`. We should match the same.

**Steps/Code to reproduce bug**
```python
In [1]: import cudf

In [2]: cudf.Index([])
Out[2]: Float64Index([], dtype='float64')

In [3]: import pandas as pd

In [4]: pd.Index([])
Out[4]: Index([], dtype='object')
```

**Expected behavior**
```
In [4]: cudf.Index([])
Out[4]: StringIndex([], dtype='object')
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Comment by mroeschke** [comment]
Note that in 2.0, an empty `pandas.Series` also defaulted to `object`
