### ISSUE TITLE
[QST] How to use cudf.Series() and get_json_object()

### ISSUE THREAD

**Issue by zlwu92** [rapidsai/cudf#14102]
Does the API get_json_object() described in https://docs.rapids.ai/api/cudf/legacy/api_docs/api/cudf.core.column.string.stringmethods.get_json_object/
supports the json query?

I installed rapids cudf libraries via conda following the instructions in rapids site.

Follow the example in the above link, I write python code like below 

![image](https://github.com/rapidsai/cudf/assets/104770161/8ee3bc33-1b22-4ca1-a26c-11ca97420c25)

But it gives an error like this? What is the problem?
![image](https://github.com/rapidsai/cudf/assets/104770161/42488127-33bb-4938-83e9-1b6089dc0e59)

**Comment by davidwendt** [comment]
The `str.get_json_object()` only works on strings column data. The `s` object in your example is created as a `struct` type.
```
>>> s = cudf.Series({"employee": {"name": "sonoo", "salary": 56000, "married": "true"}})
>>> print(s)
employee    {'married': 'true', 'name': 'sonoo', 'salary':...
dtype: struct
```

You can use the `struct.field()` function to access the name as follows:
```
>>> s.struct.field('name')
employee    sonoo
dtype: object
```
Reference: https://docs.rapids.ai/api/cudf/legacy/api_docs/api/cudf.core.column.struct.structmethods.field/#cudf.core.column.struct.StructMethods.field

Hopefully that helps.

**Comment by zlwu92** [comment]
> The `str.get_json_object()` only works on strings column data. The `s` object in your example is created as a `struct` type.
> 
> ```
> >>> s = cudf.Series({"employee": {"name": "sonoo", "salary": 56000, "married": "true"}})
> >>> print(s)
> employee    {'married': 'true', 'name': 'sonoo', 'salary':...
> dtype: struct
> ```
> 
> You can use the `struct.field()` function to access the name as follows:
> 
> ```
> >>> s.struct.field('name')
> employee    sonoo
> dtype: object
> ```
> 
> Reference: https://docs.rapids.ai/api/cudf/legacy/api_docs/api/cudf.core.column.struct.structmethods.field/#cudf.core.column.struct.StructMethods.field
> 
> Hopefully that helps.

**Comment by zlwu92** [comment]
Ok. Thank you. Can you share me a simple example created as a strings column data object?
Actually I got error in the example provided in https://docs.rapids.ai/api/cudf/legacy/api_docs/api/cudf.core.column.string.stringmethods.get_json_object/

**Comment by davidwendt** [comment]
The doc is a bit confusing since the formatter would have issues with the three double-quotes `"""`.
Here is the example perhaps in a better format:
```
>>> s = cudf.Series([ """ {
... "store":{ "book":[
...   { "category":"reference",
...     "author":"Nigel Rees",
...     "title":"Sayings of the Century",
...     "price":8.95 },
...   { "category":"fiction",
...     "author":"Evelyn Waugh",
...     "title":"Sword of Honour",
...     "price":12.99 }
... ] } } """ ])
>>> s
0     {\n"store":{ "book":[\n  { "category":"refere...
dtype: object
>>> s.str.get_json_object("$.store.book")
0    [\n  { "category":"reference",\n    "author":"...
dtype: object
>>> s.str.get_json_object("$.store.book[0].author")
0    Nigel Rees
dtype: object

```
