### ISSUE TITLE
[BUG] Iteration on `StringMethods` is resulting in infinite loop & hangs

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#14153]
**Describe the bug**
`StringMethods` in pandas supports iteration and performing the same in `cudf` is resulting in infinite loops or hangs. 

**Steps/Code to reproduce bug**
```python
In [46]: import pandas as pd

In [47]: import cudf

In [48]: s = pd.Series(['a', 'b'])

In [49]: gs = cudf.from_pandas(s)

In [50]: for i in s.str:
    ...:     print(i)
    ...: 
<ipython-input-50-d888a34388a8>:1: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  for i in s.str:
0    a
1    b
dtype: object

In [51]: for i in gs.str:
    ...:     print(i)
    ...: 
.
.
.
.
Infinite loop
```

**Expected behavior**
Iteration should be disabled for all `ColumnMethods` since it is very inefficient.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Comment by mroeschke** [comment]
Just a reminder to raise an exception in `__iter__` specifically since I'm assuming `__getitem__` is defined https://github.com/pandas-dev/pandas/pull/54174

**Comment by galipremsagar** [comment]
> Just a reminder to raise an exception in `__iter__` specifically since I'm assuming `__getitem__` is defined [pandas-dev/pandas#54174](https://github.com/pandas-dev/pandas/pull/54174)

+1, yup that's the source of the issue.
