### ISSUE TITLE
[FEA] Parquet Statistics 

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1415]
For Dask (or probably any distributed computing framework) we will want to read parquet datasets in two stages.  First we will want to gather statistical metadata on a central node, and then we will want to read individual row groups of the data on other nodes, based on that metadata.

1.  **Gather statistical metadata:** Locally, we will want to query the .metadata file (if it exists) or the files themselves in order to extract statistics metadata.  In particular we care about column names, dtypes, and minimum/maximum values, but presumably it would be good to expose all statistics.

    This allows us to be clever about removing reads early, finding sorted columns, doing joins efficiently and so on.  

    Concretely we need three things:

    1.  column names and data types
    2.  minimum/maximum values of each column, if present in metadata
    3.  tokens pointing to each row group, that we'll read in the next section

2.  *Read individual row groups:** We'll then use those statistics to filter out the row groups that we want.  Then we'll send some reference to each row group to one of our workers to read into a cudf dataframe.  

It may be that we would rely on some other package, like Arrow, to gather the metadata (although that package currently has some flaws in this regard, which would be good to fix at some point) and that the only ask here is to be able to specify a particular row group within a particular file and pull out only that data (or a subset of columns of that data).

@williamBlazing @kkraus14

**Comment by kkraus14** [comment]
@mjsamoht do you have an idea of what level of effort this would be?

**Comment by mrocklin** [comment]
To be clear, there are two possible things that we might do here:

1.  Important and hopefully easy: read a single row group rather than a whole file/dataset
2.  Not so important if we're ok also using `pyarrow.parquet`: gather statistics information

**Comment by j-ieong** [comment]
The option to reading individual row groups is easy to add. We could also add filtering values on min/max as well during reading if required and that shouldn't be difficult either.

For returning metadata, the GPU Parquet reader uses the CPU to perform that parsing and schema build-up, so there isn't any advantage with us versus PyArrow, especially since the `read_parquet` is just a C-like interface rather than a C++ class right now.

**Comment by mrocklin** [comment]
I don't need the filtering (Dask is already having that) though I can imagine that cudf might want it when it uses this functionality raw.

> The option to read an individual row group is easy to add

I'll also need a listing of all row groups.  So something like the following should work (though probably better names exist)

```python
>>> dtypes, references_to_row_groups, statistics = cudf._read_parquet_metadata(filename)
>>> all_row_groups = [cudf._read_parquet_row_group(ref, columns=[...]) 
                      for ref in references_to_row_groups]
```

**Comment by j-ieong** [comment]
Okay, that looks like something we can work on and have something for you next week.

**Comment by OlivierNV** [comment]
Note that we should also be able to have skip_rows/num_rows functionality (supported by low-level parquet/orc kernels) if that matters (though row group granularity is better since row-based splitting still requires reading entire row groups)

**Comment by mrocklin** [comment]
Thanks all.  FWIW, I don't think that we will need to have skip_rows/num_rows for read_parquet.  Being able to read individual row groups should be enough.

**Comment by mjsamoht** [comment]
Moving out for remaining part.

**Comment by kkraus14** [comment]
I believe this is solved, if not feel free to reopen.
