### ISSUE TITLE
[BUG] quantile() underflow if input integer value is more than 2^52

### ISSUE THREAD

**Issue by kovaltan** [rapidsai/cudf#1417]
Though PR #1416  correct the return values from quntiles, there are still potential issues.
The goal of this issue is to fix below issues.

1.  if column size is more than 2^52, the index computation will point incorrect index due to underflow
2. At interpolation = linear or midpoint, the computation may also overflow|underflow if input dtype is int64_t

Those 2 issues is caused by  overflow|underflow  at the conversion of between signed/unsigned int64_t and double since double's fraction part is limited in 52bits.

**Comment by harrism** [comment]
Since `gdf_size_type` is `int`, the column_size can't be more than `2^31 - 1`.

**Comment by kovaltan** [comment]
> Since gdf_size_type is int, the column size can't be more than 2^31 - 1.

That's great!
Then, the rest issue is overflow|underflow at nterpolation = linear or midpoint.

**Comment by jrhemstad** [comment]
Yeah 1. won't be an issue with `gdf_size_type` being `int`.

Can you give an example of what you mean in 2.?

**Comment by kovaltan** [comment]
For example of 2.

At this part: https://github.com/rapidsai/cudf/blob/07c20fadb12675d4b138ef7b827093b21c81ae96/cpp/src/quantiles/quantiles.cu#L93-L94
When RetT = double and T = int64_t for hv, any of hv[0] and hv[1] are greater than 2^52
or 
When RetT = double and T = int64_t, (hv[1] - hv[0] ) is greater than 2^52

**Comment by jrhemstad** [comment]
> When RetT = double and T = int64_t for hv, any of hv[0] and hv[1] are greater than 2^52
> or
> When RetT = double and T = int64_t, (hv[1] - hv[0] ) is greater than 2^52

I believe the maximum possible integer thtat can be represented _exactl_y by a double is `2^53`.

However, integers larger than `2^53` can still be represented as a `double`, just not exactly. So you lose some precision, but I don't believe that you'll overflow.

See: https://wandbox.org/permlink/oxrIQ4EGUaetqAFP

**Comment by harrism** [comment]
Since the gdf_scalar return value is type erased, can't you just adapt the return type to suit the input type?

**Comment by kovaltan** [comment]
> Since the gdf_scalar return value is type erased, can't you just adapt the return type to suit the input type?

Sorry, what do you mean?

For cudf::interpolate::midpoint(), I've already cared of underflow and overflow.
https://github.com/rapidsai/cudf/blob/c8e08560d9f475753b6607025d24907e51df779e/cpp/src/quantiles/quantiles.hpp#L45-L80

But the specialization cases of cudf::interpolate::linear() is not implemented yet since it is more difficult than midpoint().

**Comment by harrism** [comment]
@kovaltan can you comment on whether this is still an issue?

**Comment by kovaltan** [comment]
Yes, this is still an issue.
Example:

```
template<typename T_out, typename T_in>
void linear_test(T_out exact, T_in lhs, T_in rhs, double frac=0.5)
{
    T_out result;
    cudf::interpolate::linear(result, lhs, rhs, frac);

    EXPECT_EQ(exact, result) << "linear( " << lhs << ", " << rhs << ")";
}

TEST(InterpolateTest, LinearTest)
{
  using T = long;
  T t_max = std::numeric_limits<T>::max();
  T t_min = std::numeric_limits<T>::lowest();

  double mid_of_mimax = ( std::is_integral<T>::value == true ) ? -0.5 : 0.0;

  linear_test(mid_of_mimax, t_max, t_min);
  linear_test(T(t_min+100), t_min, T(t_min+T(200)));
}
```
The result:
```
[ RUN      ] InterpolateTest.LinearTest
/home/kova/rapids/cudf/cpp/tests/quantiles/quantiles_test.cu:199: Failure
      Expected: exact
      Which is: -0.5
To be equal to: result
      Which is: 0
linear( 9223372036854775807, -9223372036854775808)
/home/kova/rapids/cudf/cpp/tests/quantiles/quantiles_test.cu:199: Failure
      Expected: exact
      Which is: -9223372036854775708
To be equal to: result
      Which is: -9223372036854775808
linear( -9223372036854775808, -9223372036854775608)
[  FAILED  ] InterpolateTest.LinearTest (0 ms)
```

**Comment by harrism** [comment]
Moving to 0.9.

**Comment by kkraus14** [comment]
@harrism should this be reassigned?

**Comment by harrism** [comment]
It's not P0, right? So just de-assigning it.

**Comment by karthikeyann** [comment]
```cpp
template <typename T_out, typename T_in,
typename upcast_T = typename 
std::conditional_t< (sizeof(T_in) < sizeof(double)) , double, long double>
>
std::enable_if_t< (sizeof(long double)>sizeof(double)), void> 
linear(T_out& result, T_in lhs, T_in rhs, double frac)
{
    upcast_T dlhs = static_cast<upcast_T>(lhs);
    upcast_T drhs = static_cast<upcast_T>(rhs);
    double one_minus_frac = 1.0 - frac;

    result = static_cast<T_out>(one_minus_frac * dlhs + frac * drhs);
}
```

This code will work in CPU. It will not work in GPU (not supported `long double` in device code).
Note: Our code uses linear interpolation for quantiles in CPU.

**Comment by jrhemstad** [comment]
I think this should be a `wontfix`. There are plenty of places in libcudf that can result in silent overflow, e.g., a sum reduction of `int64_t` could easily overflow an `int64_t` accumulator without any notification given to the user. I don't think this overflow in quantiles is any different.

**Comment by karthikeyann** [comment]
I considered this different case because even before the operation is performed, it limits the input range to be 52 bits only. 
The above codefix is enough for removing this issue.

**Comment by devavret** [comment]
> Our code uses linear interpolation for quantiles in CPU.

Group quantiles are interpolated on the GPU so this fix applies only to Series. Not saying that should prevent this fix but don't close this issue if we go with this.

**Comment by cwharris** [comment]
The changes in #4292 can interpolation the midpoint between `numeric_limits<int64>::max()` and `numeric_limits<int64>::max() - 2` correctly as `numeric_limits<int64>::max() - 1`

**Comment by cwharris** [comment]
We've decided to postpone integer support indefinitely. See conversation in #4292.

**Comment by harrism** [comment]
Is that really what was decided?

**Comment by jrhemstad** [comment]
> Is that really what was decided?

https://github.com/rapidsai/cudf/pull/4292#issuecomment-603473333

**Comment by harrism** [comment]
Please be explicit, guys. Are you saying this issue should be closed? If so, close it.
