### ISSUE TITLE
[BUG] More gracefully handle overflows in reductions

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1418]
By default reductions will use the same dtype as the input and will silently overflow. We should have a way to more gracefully handle overflows and magically upcast so that end users of cuDF aren't surprised. This could live at the Python layer as I'm not sure libcudf would want / expect the same behavior.

**Comment by jrhemstad** [comment]
Also see: https://github.com/rapidsai/cudf/issues/609

I'm not a big fan of trying to detect overflows at the C++ layer. 

I'd think at the Python level you'd want to just always request the highest precision type for the reduction result.

**Comment by kkraus14** [comment]
> I'd think at the Python level you'd want to just always request the highest precision type for the reduction result.

For many reductions we can also do some basic envelope math with `np.iinfo(dtype).{min, max}` and the column size to determine what size we can fit it into.

**Comment by kkraus14** [comment]
Also it looks like Pandas / Numpy just return `int64`for all integer precision reductions, but for floating point reductions keep the precision the same as the input.

**Comment by kkraus14** [comment]
Duplicate of #609
