### ISSUE TITLE
[FEA] Add JSON reader option to ignore all characters after a valid JSON record

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#14226]
**Is your feature request related to a problem? Please describe.**

When reading a newline-delimited JSON file in Spark (using default settings), all characters after a valid JSON record are ignored. For example, all of the following inputs equate to the same value `{ "number": 1 }`:

```
{ "number": 1 }
{ "number": 1 } xyz
{ "number": 1 } {}
{ "number": 1 } { "number": 4 }
```

However, when reading this data in cuDF (and when specifying the `recover_with_nulls` option), the lines with additional characters are rejected as invalid, and NULL values are returned.

**Describe the solution you'd like**

To support Spark compatibility, I would like a new JSON reader option that specifies to ignore all input after a valid JSON record and before the line delimiter.

**Describe alternatives you've considered**
It is perhaps possible that in Spark RAPIDS we could pre-process the input for some of these cases, but I am not sure that it is feasible to efficiently use regular expressions to completely validate JSON.

**Additional context**

**Comment by elstehle** [comment]
Thanks for the example, @andygrove. My understanding of Spark JSON parser's behaviour is still a bit fuzzy here. Would it be correct to assume that it fails for any line whose _first_ record (including first record's decendants) does not conform to the JSON grammar and that Spark parser simply ignores anything that comes after the first record?

**Comment by andygrove** [comment]
> Thanks for the example, @andygrove. My understanding of Spark JSON parser's behaviour is still a bit fuzzy here. Would it be correct to assume that it fails for any line whose _first_ record (including first record's decendants) does not conform to the JSON grammar and that Spark parser simply ignores anything that comes after the first record?

Yes, that is my understanding.

**Comment by elstehle** [comment]
Thank you for confirming, @andygrove. I'm working on a PR that will change the behaviour to ignore any data that comes after the first JSON value on a JSON line and the next newline.

**Comment by elstehle** [comment]
Just to follow up, I've opened https://github.com/rapidsai/cudf/pull/14279 to address this issue.

Now, when `recover_with_nulls` is `true`, it will _always_ ignore any excess data that comes after the first record on each JSON line. Is that sufficient, or do we need the behaviour to be toggleable via an extra option?

**Comment by andygrove** [comment]
> Just to follow up, I've opened #14279 to address this issue.
> 
> Now, when `recover_with_nulls` is `true`, it will _always_ ignore any excess data that comes after the first record on each JSON line. Is that sufficient, or do we need the behaviour to be toggleable via an extra option?

@elstehle That is sufficient for our use case, based on the testing I have performed so far. Thank you.
