### ISSUE TITLE
[FEA] Implement Pandas Dataframe.pop()

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1423]
**Is your feature request related to a problem? Please describe.**
I am porting existing Pandas code to cuDF, and I have noticed that the pandas Dataframe.pop() method is not available in cuDF.

**Describe the solution you'd like**
To have it available in cuDF.

**Describe alternatives you've considered**
Making a copy of the column content, and then use cudf.Dataframe.drop_column()

**Additional context**
Happy to be a RAPIDS user.

**Comment by beckernick** [comment]
Hey @miguelangel. This feature recently merged into branch 0.7 with PR #1412. If you have any issues with it after updating your branch, let us know! Closing this issue.

**Comment by miguelangel** [comment]
Hi,

Today, I docker pulled the latest nightly container. It failed.

Is it not there?

Regards,
Miguel

**Comment by miguelangel** [comment]
Hi @beckernick,

I tested with the latest RAPIDS nightly-built available when I opened this issue.

https://hub.docker.com/r/rapidsai/rapidsai-nightly/tags

I have noticed that 6 hours ago, the nightly builds have been updated.

I have just tested again, with the latest container from the nightly builds (I just docker pulled it). It is still failing:

![image](https://user-images.githubusercontent.com/26169771/56082396-aca17800-5e18-11e9-8d13-135d8ac98a23.png)

Could you please double check?

Thanks!

Regards,
Miguel

**Comment by beckernick** [comment]
@miguelangel , it looks like the latest nightly container is installing cudf 0.6. I'm going to close this issue and open a new one to reflect that. Thanks for asking me to double check!

If you run into any issues with `pop` in cudf version 0.7, please update this issue.

**Comment by datametrician** [comment]
Nick also please notify the ops team

**Comment by beckernick** [comment]
Will do. Opened an ops issue and will ping Slack
