### ISSUE TITLE
[DOC] Incorrect value for integers_to_hex reported in the function docs

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#14232]
## Report incorrect documentation
The value 123 should map to '7B' not '4D2' in the function docs for integers_to_hex. 

**Location of incorrect documentation**
https://github.com/rapidsai/cudf/blob/23d24d43fac8615166c38231f13fe8751a8aec42/cpp/include/cudf/strings/convert/convert_integers.hpp#L204

**Describe the problems or issues found in the documentation**
It should be fixed to the correct hex value

**Steps taken to verify documentation is incorrect**
Ran the method `integers_to_hex`

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by davidwendt** [comment]
I can fix this in #14208
