### ISSUE TITLE
[BUG] read_json fails when reading multiple files but works with the individual files

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#14268]
**Describe the bug**
For certain datasets, `cudf.read_json(lines=True, engine="cudf")` fails when combining multiple files, while reading them individually works as expected.

**Steps/Code to reproduce bug**
```
df = cudf.read_json(files, engine="cudf_legacy", lines=True)
```

**Expected behavior**
No error.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - 22.10 nightly from oct 05

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by karthikeyann** [comment]
@ayushdg what is the failure error?
Please share the files to reproduce this error.

**Comment by ayushdg** [comment]
Thanks for following up. On further inspection it looks like it was happening because some of the jsonl files were empty which ended up tripping/confusing the parser when reading multiple files simultaneously. 

For the time being we explicitly check for empty files in the curator codebase, but I wonder if there's scope for better error messages here instead of the json parser error at location xyz.

**Comment by wence-** [comment]
FWIW, I can't reproduce a failure with a minimal set of files with two non-empty and one empty one.

**Comment by karthikeyann** [comment]
Is this still an issue?

**Comment by ayushdg** [comment]
I don't believe so. Thanks for the ping closing as resolved.
