### ISSUE TITLE
[FEA] Add index support to cuDF Dataframe.drop() method

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#1427]
**Is your feature request related to a problem? Please describe.**
While porting some pandas to cudf code, it looks like indexes are not supported in cuDF Dataframe.drop() method.

It is useful when performing some actions as follows:

```
train_dataset = dataset.sample(frac=0.8,random_state=0)
test_dataset = dataset.drop(train_dataset.index)
```

**Describe the solution you'd like**
To have that functionality available in cuDF.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by miguelangel** [comment]
Hi!

Is there any update on this feature request?

Thanks!

Miguel

**Comment by beckernick** [comment]
Closing as this has been implemented.

```python
import cudf
​
df = cudf.DataFrame({"a":range(5)})
train = df.sample(frac=0.6)
print(df.drop(train.index))
   a
3  3
4  4
```
