### ISSUE TITLE
[QST]How to display more rows by setting?

### ISSUE THREAD

**Issue by yoyitowang** [rapidsai/cudf#1429]
**What is your question?**
I tried set_options as pandas to show more rows?
But it's not working. Then searching some setting function to do it.
`from cudf import settings
settings.set_options(nrows=50)`
How should set it?

**Comment by j-ieong** [comment]
cuDF accesses the print options under a `formatting` dict.

In the call to `set_options`, pass a `formatting` dict with the desired key-value pairs. Additionally, that call returns the settings object in the local context so your print should be within its scope. Ex:

```python
from cudf.settings import set_options

def test_print():
    df = ...
    with set_options(formatting={'nrows': 50}):
        print(df)
```
