### ISSUE TITLE
[BUG] OOM with isin when lhs/rhs contain repeats / spill fails

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#14298]
**Describe the bug**
When using `.isin` on a comparatively small set of `cudf.Series`, OOM occurs. This is because the `cudf.Series` contain repeats, which explodes memory in `.isin`.

**Steps/Code to reproduce bug**
The minimal reproducer is contained in https://gitlab-master.nvidia.com/tcomer/isin_bug so that you can download the .csv files containing the relatively small serieses with numerous repeats.

**Expected behavior**
`.isin` should not OOM when comparing a 2.2m column with a 275k column.

**Environment overview (please complete the following information)**
Cudf installed via conda:

`micromamba install -c rapidsai -c conda-forge -c nvidia cudf`

```
(ins)(sisclip-viz) tcomer@tcomer-NVIDIA:~/miniconda3/envs/sisclip-viz/lib/python3.10/site-packages/cudf$ micromamba list | grep cudf
  cudf                           23.08.00      cuda11_py310_230809_g8150d38e08_0  rapidsai   
  dask-cudf                      23.08.00      cuda11_py310_230809_g8150d38e08_0  rapidsai   
  libcudf                        23.08.00      cuda11_230809_g8150d38e08_0        rapidsai  
```

**Comment by wence-** [comment]
`isin` does a merge of the two columns. So can blow up the size if the number of repeats is high. It should probably be reworked to do the merge on unique values and the expand out afterwards.
