### ISSUE TITLE
[DOC] Dask_cudf docs have a FIXME and orange warning section in legacy, stable, and nightly.

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#14299]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/dask-cudf/stable/api/#dask_cudf.concat

**Describe the problems or issues found in the documentation**
Our dask_cudf docs have a big orange warning section with a `FIXME: where should the following live?` in stable, legacy, and nightly

**Suggested fix for documentation**
May I suggest that `dask_cudf.concat()` go under `DataFrames and Series`, and `dask_cudf.from_delayed()` stay in `Creating and storing DataFrames`?

**Comment by GregoryKimball** [comment]
@rjzamora Would you please check if this issue is still needed? Thank you for your help!

**Comment by rjzamora** [comment]
>May I suggest that dask_cudf.concat() go under DataFrames and Series, and dask_cudf.from_delayed() stay in Creating and storing DataFrames?

Thanks for raising @taureandyernv ! I think your suggested solution would be fine. Are you interested in contributing that change?

Note that it may also be fine to remove `concat` and `from_delayed` from the documentation altogether given that the `dask_cudf` version is just calling the `dask.dataframe` version directly (as is). In fact, I should probably take some time to deprecate the redundant definitions in the `dask_cudf` namespace, and revise the documentation to better clarify that `dask_cudf.DataFrame/Series` **is** a `dask.dataframe.DataFrame/Series`, and that users should rarely need to import `dask_dataframe` directly.

**Comment by wence-** [comment]
I merged this to 24.02 (so it wasn't auto-closed) since it wasn't critical for 23.12. But this should be fixed in nightlies.
