### ISSUE TITLE
[FEA] Add ability to return similar return types for `value_count` when pandas compatibility mode is turned on

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#14353]
**Is your feature request related to a problem? Please describe.**
`value_counts` in `cudf` returns a lower dtype for performance reasons, 
```python
In [1]: import cudf

In [5]: s = cudf.Series([1, 2, 1, 2, 1, 4])

In [6]: s
Out[6]: 
0    1
1    2
2    1
3    2
4    1
5    4
dtype: int64

In [7]: s.value_counts()
Out[7]: 
1    3
2    2
4    1
dtype: int32

In [8]: s.to_pandas().value_counts()
Out[8]: 
1    3
2    2
4    1
dtype: int64
```
**Describe the solution you'd like**

It would be nice to have it return a type similar to what pandas returns when pandas compatibility mode is enabled.

**Comment by bdice** [comment]
I think it would be reasonable to cast to `int64` always. The performance penalty is probably small enough that it is not worth having two code paths here.

**Comment by mroeschke** [comment]
Curious why does cudf return int32 in this case? Was it just the chosen return type in libcudf?
