### ISSUE TITLE
JSON reader provides a full null mask for a column with no NULLs

### ISSUE THREAD

**Issue by divyegala** [rapidsai/cudf#14366]
While writing https://github.com/rapidsai/cudf/pull/13795, we discovered that the JSON reader attaches a fully allocated null mask for a column that does not have NULLs. This can cause severe performance degradation in some algorithms for the deeply nested type case.

A solution here is for the JSON reader to post-process columns and ensure that a column with `has_nulls() == 0` also has `nullable() == false`.

cc @bdice

**Comment by GregoryKimball** [comment]
Thank you @divyegala and @bdice for revisiting this issue.

The performance data in the upcoming blog will be impacted if we don't address the excess nulls sanitization in `cudf::detail::gather`. Of course, if `cudf::detail::gather` is not preserving the nullability of its input then that is also not acceptable. I would prefer to update gather without bringing in a JSON dependency to 23.12 burndown.

Would it be feasible to add a condition to populate an all-true nullmask for the returned column/table if `nullable==true` and `null_count==0`?

**Comment by bdice** [comment]
Yes, I discussed that idea here https://github.com/rapidsai/cudf/pull/14363#issuecomment-1795907900. I think both changes (a shortcut for `detail::gather` to avoid gathering all-valid null masks AND not populating all-valid null masks in the JSON reader) are sensible performance optimizations for the library.

**Comment by GregoryKimball** [comment]
Thank you @bdice. @divyegala would you please reopen #14363 and add the extra step of returning an all-valid null mask with `null_count==0` and `nullable==true`?

**Comment by divyegala** [comment]
@bdice @GregoryKimball I reopened https://github.com/rapidsai/cudf/pull/14363 to satisfy `nullable() and not has_nulls()` condition but I'm seeing some failures locally in gtests. Could either of you verify if I did anything wrong?

**Comment by bdice** [comment]
> @bdice @GregoryKimball I reopened #14363 to satisfy `nullable() and not has_nulls()` condition but I'm seeing some failures locally in gtests. Could either of you verify if I did anything wrong?

I'll check CI logs after it runs. I did a quick pass of review and nothing seems obviously wrong to me.

**Comment by GregoryKimball** [comment]
Circling back to the topic of dropping the null mask for columns where the null count is zero, @karthikeyann do you think this would be a good optimization? or are there good reasons (such as the not-yet-implemented chunked JSON reader) why we should prefer returning null masks for all columns?

**Comment by karthikeyann** [comment]
JSON reader will always compute null mask. so computation wise it's not an optimization. but it reduces memory usage slightly. Right now, the nulls are kept in nested json reader because legacy JSON reader kept it always. There are few tests which compare legacy with nested reader. So, these tests should be updated when making this change.

Since it impacts performance on other parts of library, definitely this change would be a good optimization.

**Comment by karthikeyann** [comment]
Should the null mask be removed in legacy JSON reader as well?

**Comment by bdice** [comment]
I'm not sure how long we intend to keep the legacy JSON reader. If we can't remove the legacy reader in the short term, I would consider doing whichever is easier: (1) removing null masks in the legacy reader or (2) altering the tests that compare legacy/new behavior to disregard all-null masks when comparing to no null mask.

**Comment by karthikeyann** [comment]
null mask removal in legacy reader (1) is easier. PR #14451 will address this issue.
