### ISSUE TITLE
[BUG] cudf::util::round_up_safe is incorrectly marked constexpr

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1438]
This was a gaffe on my part which unfortunately slipped past review:

In `integer_utils.hpp`, I've written the function:
```
constexpr inline S round_up_safe(S number_to_round, S modulus)
```
but it's not actually `constexpr`, since it can throw. It is not really possible to safely round up, because the rounding up can fail; and either we throw an exception or report an error some other way. We've been going down the exception road.

Solution: Just need to remove the constexpr from there.

**Comment by harrism** [comment]
Fixed by #2833
