### ISSUE TITLE
[DOC] Higher contrast fonts in dark mode

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#14463]
Currently when I navigate to cudf docs I find that it defaults to dark mode (my OS system defaults) and text is hard to read:

<img width="754" alt="Screenshot 2023-11-21 at 2 11 23 PM" src="https://github.com/rapidsai/cudf/assets/306380/b21a6efe-fd3c-4621-b220-5b923351a4ec">

Light mode is great

<img width="763" alt="Screenshot 2023-11-21 at 2 11 36 PM" src="https://github.com/rapidsai/cudf/assets/306380/b404549c-7ac2-499c-9efb-ff42b5d06a2c">

An easy solution to this would be to just turn off dark mode.  This can be acheived with a setting in conf.py .  I think the setting itself is documented in the pydata sphinx theme y'all are using.

**Comment by bdice** [comment]
Thanks for filing this. It's been on my to-do list for a while to fix! PR #14466 disables dark mode since our custom theme is not legible with it enabled.

**Comment by bdice** [comment]
@galipremsagar came up with a better approach to fix the dark theme. See here: https://github.com/rapidsai/docs/pull/456

This should be live on the website in ~2 hours.
