### ISSUE TITLE
[BUG] `Index.difference` does not uniquify output for duplicate indexes

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#14489]
**Describe the bug**

cudf computes `Index.difference` with a `leftanti` join. This preserves duplicates in the left index. In contrast, pandas always produces an index with uniquified values.

**Steps/Code to reproduce bug**

```
import cudf
import pandas as pd

left = pd.Index([1, 1, 2, 2])
right = pd.Index([2])

print(left.difference(right))
cleft = cudf.from_pandas(left)
cright = cudf.from_pandas(cright)
print(cleft.difference(cright))
```

**Expected behavior**

Match pandas, either by calling `drop_duplicates` or using `libcudf.search.contains` (see also #14487).

**Notes**

Doesn't apply to `MultiIndex` right now, because that goes through pandas (although that's a perf bug that should be fixed).

**Comment by amiralimi** [comment]
hi. can i try to fix this?

**Comment by amiralimi** [comment]
Hi @wence- . Can I fix this issue?

**Comment by wence-** [comment]
> Hi @wence- . Can I fix this issue?

Please go ahead! When you open a PR please tag me so I don't miss it, thanks!
