### ISSUE TITLE
[DOC] How to install cudf offline on Linux ?

### ISSUE THREAD

**Issue by tx2002** [rapidsai/cudf#14490]

**Comment by wence-** [comment]
Can you provide a bit more information by what you mean by "offline"? Do you want to install on a system that is gated behind a firewall so doesn't have any internet access? Or do you want to build on such a system? Or something else?

**Comment by tx2002** [comment]
Due to some security reasons, my Linux system cannot access the Internet. So I cannot use the command generated by the selector tool provided by rapids official website to install cudf.
I have tried downloading the compressed file of the package from Anaconda or pipy website and transferring it to Linux for offline installation. But this doesn't seem to work.
In this case, is there any good way for me to install cudf? For example, is there a .whl file provided for offline installation?
Thank you very much.

**Comment by wence-** [comment]
> I have tried downloading the compressed file of the package from Anaconda [...] and transferring it to Linux for offline installation. But this doesn't seem to work.

For conda packages, this is the correct approach. However, there are a number of difficulties associated with this. It is possible to overcome them but won't be completely straightforward sadly :(.

It is possible to install downloaded conda packages from local files, see https://docs.anaconda.com/free/anaconda/packages/install-packages/#installing-packages-on-a-non-networked-air-gapped-computer.

However, as noted there, if you just download a single package and then try and install it, it won't fetch any dependencies.

If you have a setup where there is a filesystem that is shared between the air-gapped system (where you want the install to take place) and a login node (which does have internet access), you can drive the `conda` (or `mamba`) installer in "offline" mode.

You will need to have installed conda on both the air-gapped system and the login node.

On the login node, run

```
mamba install --download-only PACKAGES_TO_DOWNLOAD
```

Where `PACKAGES_TO_DOWNLOAD` is as given by the selector tool on the rapids website.

When that completes you will have "pre-populated" the cache of downloaded files, but not tried to install anything.

Then, on the air-gapped system run:
```
mamba install --offline PACKAGES_TO_DOWNLOAD
```
This should run locally and install things if it can see the same mamba installation.

You can see the location conda writes its downloaded packages with `conda config --show pkgs_dir`. If those aren't the same on both systems you'll need to copy the contents from the system which downloads everything to the air-gapped system.
I assume that you have a setup where you have a filesystem that is shared between the air-gapped system that cannot access the internet

**Comment by vyasr** [comment]
It's probably a bit easier to do this with pip. A `pip download $pkg` will download the necessary wheel as well as all of its dependencies. Then you can copy those over and do a `pip install --no-deps /path/to/package/directory`. I specify `--no-deps` so that you don't have to worry about the order those dependencies get installed on the final system.

**Comment by davidwendt** [comment]
I'm wondering if this could also be done using the RAPIDS docker images. 
First pull the appropriate image using https://docs.rapids.ai/install using a machine that has access to the internet.
Then create a .tar file of the image using `docker save -o rapids.tar <image-name>`.
Copy the .tar file to the isolated machine and untar it there using `docker load -i rapids.tar`

Reference to RAPIDS docker hub page: https://hub.docker.com/r/rapidsai/rapidsai-core

**Comment by tx2002** [comment]
Thank you very much for your help. I have successfully installed cudf offline using pip just as @vyasr  said. Proceed as follows.
With:
 - node A : have access to the Internet, don't have gpu and cuda
 - node B : no access the Internet, have gpu and cuda
 - they can transfer files through local network

### pip
First, using pip to download all the wheel on node A

```python
 pip download --extra-index-url=https://pypi.nvidia.com
```

then, transfer to the node B, install all of this.  Pay attention to your python version and cuda version.

```python
pip install --no-deps /path/*.whl
```

---

What follows are some of my trial and error experiences

### conda

when I run this on node A:

```python
conda install --download-only PACKAGES_TO_DOWNLOAD
```

Error : There is no corresponding cuda version
So I can't download the packages.

Also, I can't create a conda environment on node A because it don't have cuda. So I can't use the conda-pack.

### Docker

I can easily download the docker image from the docker hub, but it only have the standard version ( size 10G ). I can't only install the cudf.

In addition, if I want to use gpu in docker, I must install the nvidia-container-toolkit on node B. This raises a new question: how to install nvidia-container-toolkit offline?  Since I have installed cudf with pip at that time, I did not continue to study it.

At last, Thank you again for helping me !!!
