### ISSUE TITLE
[BUG] Unexpected result from `MEAN()` aggregation on `DECIMAL` input

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#14507]
**Describe the bug**
`MEAN` aggregation seems to produce incorrect results when run on `DECIMAL` input. Looks like a rounding error. (This issue first manifested as a test failure in Spark RAPIDS: https://github.com/NVIDIA/spark-rapids/issues/9682.)

**Steps/Code to reproduce bug**
```c++
TEST_F(ScratchTest, DecimalAgg)
{
    auto const filename = "/tmp/decimal_12_7.parquet";
    auto reader_opts =
            cudf::io::parquet_reader_options::builder(cudf::io::source_info{filename});
    auto const result = cudf::io::read_parquet(reader_opts);
    auto const decimal_agg_col = result.tbl->get_column(0);

    // Workaround: DECIMAL columns aren't supported in cudf::reduce. Use dummy groupby column.
    using gby_column_t = cudf::test::fixed_width_column_wrapper<int32_t>;
    auto const gby_iter = thrust::constant_iterator<int32_t>(0);
    auto const gby_col = gby_column_t( gby_iter, gby_iter + decimal_agg_col.size() ).release();

    auto agg_requests = std::vector<cudf::groupby::aggregation_request>{};
    agg_requests.emplace_back(cudf::groupby::aggregation_request());
    agg_requests[0].values = decimal_agg_col;
    agg_requests[0].aggregations.push_back(cudf::make_sum_aggregation<cudf::groupby_aggregation>());
    agg_requests[0].aggregations.push_back(cudf::make_count_aggregation<cudf::groupby_aggregation>());
    agg_requests[0].aggregations.push_back(cudf::make_mean_aggregation<cudf::groupby_aggregation>());

    auto gby = cudf::groupby::groupby{cudf::table_view{{*gby_col}},
                                      cudf::null_policy::INCLUDE,
                                      cudf::sorted::YES};
    auto gby_agg_result = gby.aggregate(agg_requests);
    std::cout << "SUM agg results: " << std::endl;
    cudf::test::print(*gby_agg_result.second.front().results[0]);
    std::cout << "COUNT agg results: " << std::endl;
    cudf::test::print(*gby_agg_result.second.front().results[1]);
    std::cout << "MEAN agg results: " << std::endl;
    cudf::test::print(*gby_agg_result.second.front().results[2]);
}
```
This produces the following output:
```
SUM agg results: 
338651.4750000
COUNT agg results: 
96
MEAN agg results: 
3527.6195312
```

**Expected behavior**
`338651.4750000 / 96` would yield `3527.61953125`, which should round to `3527.6195313`, when cast to `DECIMAL(12,7)`.

**Environment overview**
 - CUDF 23.12
 - Spark-RAPIDS Plugin 23.12 SNAPSHOT

The (Parquet) data used to repro this failure is attached as a zipped file herewith: 
[decimal_12_7.parquet.zip](https://github.com/rapidsai/cudf/files/13481507/decimal_12_7.parquet.zip)

**Comment by ttnghia** [comment]
Cudf decimal rounding is always a round down, not round-to-near-value. So probably we should upcast the sum to `DECIMAL(12+1,7+1)`, do the rounding then down cast back.

**Comment by bdice** [comment]
Decimals always truncate (round to the floor) as far as I am aware -- like dealing with integers, but with a shifted decimal place. A smaller reproducer would be `3 + 4` averaging to `3.5` which floors to `3` when there are no digits kept after the decimal place (zero scale, if I recall the terminology...).

As @ttnghia proposes, it may be necessary to use a higher precision/scale -- but be aware that this can also cause overflow.

**Comment by ttnghia** [comment]
This is what I found before:
> Assume that we have a float number `x = 0.299999`. We construct a decimal with `scale = -1` from it. In cudf, `fixed_point` constructed from it will be `0.2` instead of `0.3`.

**Comment by mythrocks** [comment]
On examining the way Spark RAPIDS calls into CUDF, I'm no longer convinced the problem is in CUDF. I'll accept that the behavior described above is the desired one. 

I'm closing this bug, to focus on investigating the plugin.
