### ISSUE TITLE
[FEA] redesign quantile 

### ISSUE THREAD

**Issue by kovaltan** [rapidsai/cudf#1450]
Merge quanatile_approx and quanatile_exact into a single API, and apply cudf c++ design like cudf::quantile() + throws exceptions.
And also discuss how to handle array of quantilies.

Why redesign is needed?

1. Pandas quantile does not have exact option

2. Instead, Pandas has numeric_only option
Pandas quantile supports Timestamp if numeric_only=False
It can compute quantiles as same input type, and can be interpolated as linear.
quantile_approx can return same input type at timestamp, but cannot be interpolated as linear.
See detail: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.quantile.html

3. Pandas quantile often gives array of quantilies while gdf_quantiles only returns scalar value.

For 2,
I think it's better to merge quanatile_approx and quanatile_exact into a single API, then add `numeric_only` flag which determine the data type of result as double or same of input type.

For 3, there are 2 options.

3.1. implement at python side
If apply_quntile in python clones the input column and sorts the column at first gdf_quanatile call, it it not necessary to sort the colum at subsequenct calls.

3.2. implement at c++ side 
Technically it is possible, but there is API design issue.
For now, we use `gdf_scalar`, it has type infomation and placed at host memory.
We can use `gdf_column` instead, it also has type infomation, but it is placed at device memory.
The memory location will be changed if we use `gdf_column` as output.
Of course, we can pass raw memory storage, it does not have any type infomation, but it is possible for any of host, device memory.

Related issue, PR #1416 #1417

**Comment by cwharris** [comment]
`quantiles_approx` and `quantiles_exact` have been merged in #3402. Legacy implementation has not yet been updated/removed.

**Comment by kkraus14** [comment]
Fixed by #3402
