### ISSUE TITLE
[FEA] Proxy ndarrays don't pass an `instancecheck()` for `np.ndarray`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#14537]
There's a lot of code out there that does something like:

```python
if not isinstance(x, np.ndarray):
    raise TypeError("Not a numpy array")
```

This is a problem for `cudf.pandas`, because proxy ndarray types, such as those returned by `pd.Series.values` do not pass the `isinstance()` check.

Ideally, more projects would avoid doing a hard `isinstance()` check and instead use something like EAFP:

```python
np.asarray(x)
```

..but that is not the world we live in today. Too many third-party libraries that people want to use with `cudf.pandas` use the pattern above, so it's on us to solve the problem right now.

**Comment by Matt711** [comment]
As far as I can see there isn't a fix for this because we cannot modify `np.ndarray`'s `__instancecheck__` which is called when you call `isinstance(c, np.ndarray)`. For example, 

```python
import cudf.pandas
cudf.pandas.install()
import pandas as pd
import numpy as np

x = pd.Series([1,2]).to_numpy() # proxy for numpy.ndarray

isinstance(x, np.ndarray) # calls np.ndarray.__instancecheck__(x) which returns false
```

I thought you might be able to modify `np.ndarray.__instancecheck__` but you get an error
```python
TypeError: cannot set '__instancecheck__' attribute of immutable type 'numpy.ndarray'
```

**Comment by shwina** [comment]
That's correct. I don't think there's a very good solution here, short of proxying `numpy` in the same way we proxy `pandas`. But that comes with its own set of challenges.
