### ISSUE TITLE
[QST] Does cuDF only work with pandas==1.5

### ISSUE THREAD

**Issue by qsimeon** [rapidsai/cudf#14546]
I recall it threw an error when I tried to use with Pandas 2.1.3 (which I wrote my code originally using). I downgraded to 1.5 in order to get the promised speedups from cuDF (which were not significant) but obtained more headaches from Pandas 1.5 (like not being able to save a list as an entry properly, etc). The documentation also does not make it clear anywhere that cuDF won't work with Pandas > 1.5 so this is also a question and a documentation request.

**Comment by shwina** [comment]
Thanks for reporting! We do document the Pandas requirement in the known limitations section of our docs:

https://docs.rapids.ai/api/cudf/stable/cudf_pandas/faq/#are-there-any-known-limitations

As for speedup, it's difficult to make recommendations without knowing what code you're trying to run. It's likely that a significant portion of your code is falling back to CPU and it may be possible to write in a more GPU friendly way.

Have you tried running the profiler to see what ran on CPU versus GPU?

**Comment by qsimeon** [comment]
When do you expect cudf.pandas will work will the latest version of Pandas? Could you also fix this issue https://github.com/rapidsai/cudf/issues/14547#issue-2022778661 ?

**Comment by shwina** [comment]
> When do you expect cudf.pandas will work will the latest version of Pandas? 

cuDF 24.04 will be the first version of cuDF with support for pandas 2.x. The stable release will be in April, but nightly packages should start being published in early to mid February with support for pandas 2.x.

> Could you also fix this issue https://github.com/rapidsai/cudf/issues/14547#issue-2022778661 ?

Absolutely. We're triaging it right now!
