### ISSUE TITLE
[QST] How to improve performance of cudf.pandas `df1.add(df2)`

### ISSUE THREAD

**Issue by dask-user** [rapidsai/cudf#14548]
In my example below, I'm seeing the cudf.pandas extension does have an impact, but it's a <2x speedup. I would have expected for something as basic as adding 2 like-shaped frames together, this would have had a significantly more profound impact. Is this expected? if not is there some other way I can realize a better performance improvement?

Thank you.

Environment configuration (using colab linked in cudf.pandas docs):
```
>>> import cudf
>>> cudf.__version__
'23.10.02'
>>> import pandas
>>> pandas.__version__
'1.5.3'
>>> !nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Running the following script

```
%load_ext cudf.pandas

import pandas as pd
import numpy as np

df1 = pd.DataFrame(np.random.randn(250000, 1000))
df2 = pd.DataFrame(np.random.randn(250000, 1000))

x = df1.add(df2)  # timing this call below tag=(1)
y = df1.add(df2).add(df1).add(df2)  # timing this call below tag=(2)
```

%%timeit Timings

```
CPU Timings (no cudf extension)
tag=(1)
708 ms ± 118 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

tag=(2)
2.24 s ± 382 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

GPU Timings (with cudf extension) - confirmed using GPU with %%cudf.pandas.profile
tag=(1)
392 ms ± 49 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

tag=(2)
1.26 s ± 161 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

**Comment by dask-user** [comment]
Thanks for the insight. Reshaping to 10,000,000 x 25 did indeed result in a 20x speedup. That is rather unfortunate though, as many time series analysis based use cases naturally fit this kind of shape. E.g. weather, oil/gas well drilling, power generation, etc.
Is this an inherent limitation of working on GPUs, or just due to implementation details of cudf? I'm assuming the latter, because the original shaped dataset on cupy provides a similar ~20x speedup over NumPy. Assuming that assumption is correct, is this on the cudf roadmap to address? Thanks.

**Comment by shwina** [comment]
I'll add that when data is stored in this way, it becomes natural and easy to do "database-like" operations like groupbys:

```python
# get the mean power generating per unit:
df.groupby("power_generating_unit_id").mean()
                             value
power_generating_unit_id
0                         0.497459
1                         0.510917
2                         0.511179
3                         0.504013
4                         0.513688
...                            ...
4995                      0.502024
4996                      0.496629
4997                      0.494932
4998                      0.509441
4999                      0.504814
```

And operations like that are blazing fast with cuDF.

**Comment by dask-user** [comment]
HI @vyasr and @shwina thanks for the info. The above suggestions do explain the issue, thank you. However, I do find this unfortunate, as one of the main strengths of pandas is its ability to switch between long relational format and wide ndarray format, and it seems like cudf.pandas is aiming to support only the long format style. I think with the emergence of duckdb and polars, etc. these technologies will significantly diminish the market share of pandas for these purely long relational style workflows. Not to mention, that these two new solutions are offering speeds faster than the gpu accelerated benchmark that @shwina provided above, on traditional CPU hardware (see below for a recreation of the benchmark). Where pandas still holds an unchallenged advantage is in numerical computing workflows where data frames are regularly switching between relational and ndarray style, and many operations are done in the latter style. A lot of numerical modeling work is still and will continue to be done this way, essentially using pandas as numpy with labels (similar to xarray), and pivoting to/from long format where needed. This hybrid workflow is becoming an increasingly large market share of pandas use cases, as users migrate to better technologies for purely relational workflows. cudf.pandas in it's current form might be able to stem the tide of users moving away from pandas for these relational use cases, but I think it would be good to address the hybrid use cases where pandas has significant edge.

```
# on colab notebook linked in cudf.pandas docs

df = pd.DataFrame(np.random.rand(1000, 50000), index=pd.date_range("2001-01-01", periods=1000, name="date"))
df = df.reset_index()
df = df.melt("date", var_name="power_generating_unit_id")
df["power_generating_unit_id"] = df["power_generating_unit_id"].astype("int32")

%timeit (df['value'] + df['value']).sum()  # timed with pure pandas and cudf.pandas
%timeit duckdb.sql('select sum(value + value) from df')  # time this without cudf.pandas extension loaded
# pandas          200 ms
# cudf.pandas 12.7 ms
# duckdb          1.12 ms

%timeit df.groupby("power_generating_unit_id")['value'].mean()
%timeit duckdb.sql('select power_generating_unit_id, mean(value) from df group by power_generating_unit_id')
# pandas          943 ms
# cudf.pandas 37.6 ms
# duckdb          0.982 ms



```

**Comment by shwina** [comment]
In your duckdb timings, what you're measuring is simply the time it takes to create the relation object - not actually the time it takes to execute the query. IPython/Jupyter has some tricky behaviour here that might be throwing you off, where the call to `%timeit` returns before the object is printed, and the printing of the duckdb object is what executes the query.

I believe the right way to measure execution time here for duckdb is to invoke `show()` or `execute()` on the result. Here's what I see when I do that:

```python
%timeit (df['value'] + df['value']).sum()  # timed with pure pandas and cudf.pandas
%timeit duckdb.sql('select sum(value + value) from df').execute()  # time this without cudf.pandas extension loaded

# pandas          200 ms
# duckdb          167 ms
# cudf.pandas     12.8 ms
```

```python
%timeit df.groupby("power_generating_unit_id")['value'].mean().mean()  # timed with pure pandas and cudf.pandas
%timeit duckdb.sql('select mean(value) from (select power_generating_unit_id, mean(value) as value from df group by   power_generating_unit_id)').execute()  # time this without cudf.pandas extension loaded

# pandas          1.03 s
# duckdb          724 ms
# cudf.pandas     46 ms
```

Keep in mind though, that the Colab instance has just a single hyperthreaded core - so you may be able to get better performance using DuckDB on a machine with more CPU cores.

**Comment by shwina** [comment]
As for the question of supporting wide DataFrames like in your example, unfortunately that's not on the roadmap for cuDF. It would mean choosing a completely different memory layout, and sacrificing performance significantly for "classical" operations. 

Apologies if that's not the answer you were looking for! I'd definitely look into whether CuPy would be a good fit for you if you're interested in leveraging GPUs for these kinds of operations.

**Comment by dask-user** [comment]
Understood makes sense thank you. 
And yes I see what you're referring to wrt duckdb timing. The post timeit printing executing the query was indeed throwing me off.
