### ISSUE TITLE
[FEA] Remove the directory `python/cudf/cudf/benchmarks` and its contents

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#14573]
**Is your feature request related to a problem? Please describe.**
We have legacy benchmarking code from cuDF-python that was designed to test JSON and Avro reading throughput. These benchmarks are not regularly run and should be removed from the repository.

One drawback of removing this code is that we will not have a tool for Avro reader benchmarks. However, we aren't using or running these benchmarks today and don't plan to add them to our benchmark automation. See #14574 for tracking the request to add Avro reader benchmarks to libcudf benchmarks.

**Describe the solution you'd like**
Remove the directory `python/cudf/cudf/benchmarks` and its contents

**Describe alternatives you've considered**
Keep `python/cudf/cudf/benchmarks` as unused legacy code

**Additional context**
We have automated benchmarks based on the following submodules, and we should expand these if needed rather than supporting the legacy benchmarks.
* https://github.com/rapidsai/cudf/tree/branch-24.02/python/cudf/benchmarks
* https://github.com/rapidsai/cudf/tree/branch-24.02/cpp/benchmarks

**Comment by osidekyle** [comment]
Hi @GregoryKimball, I am a first time contributor. May I take up this issue?

**Comment by shwina** [comment]
Hi @osidekyle - yes, please feel free to do that. Thanks!
