### ISSUE TITLE
[BUG] Devcontainers failing to compile simple program

### ISSUE THREAD

**Issue by ZelboK** [rapidsai/cudf#14606]
**Describe the bug**
The dev containers do not work for people outside of NVIDIA likely. sccache is complaining and getting in the way of building libcudf. This is likely the same(if not, similar) error that CCCL was experiencing. URL to said issue at bottom. 

```
(rapids) coder ➜ ~/cudf $ ./build.sh libcudf benchmarks
Building for the architecture of the GPU in the system...
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- The CUDA compiler identification is NVIDIA 12.0.76
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc
-- Check for working C compiler: /home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc - broken
CMake Error at /home/coder/.conda/envs/rapids/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:67 (message):
  The C compiler

    "/home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/home/coder/cudf/cpp/build/CMakeFiles/CMakeScratch/TryCompile-ZVxIG6'
    
    Run Build Command(s): /home/coder/.conda/envs/rapids/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_94ec7/fast
    /usr/bin/gmake  -f CMakeFiles/cmTC_94ec7.dir/build.make CMakeFiles/cmTC_94ec7.dir/build
    gmake[1]: Entering directory '/home/coder/cudf/cpp/build/CMakeFiles/CMakeScratch/TryCompile-ZVxIG6'
    Building C object CMakeFiles/cmTC_94ec7.dir/testCCompiler.c.o
    /usr/bin/sccache /home/coder/.conda/envs/rapids/bin/x86_64-conda-linux-gnu-cc   -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/coder/.conda/envs/rapids/include  -I/home/coder/.conda/envs/rapids/targets/x86_64-linux/include  -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib -L/home/coder/.conda/envs/rapids/targets/x86_64-linux/lib/stubs  -o CMakeFiles/cmTC_94ec7.dir/testCCompiler.c.o -c /home/coder/cudf/cpp/build/CMakeFiles/CMakeScratch/TryCompile-ZVxIG6/testCCompiler.c
    sccache: error: Timed out waiting for server startup. Maybe the remote service is unreachable?
    Run with SCCACHE_LOG=debug SCCACHE_NO_DAEMON=1 to get more information
    gmake[1]: *** [CMakeFiles/cmTC_94ec7.dir/build.make:78: CMakeFiles/cmTC_94ec7.dir/testCCompiler.c.o] Error 2
    gmake[1]: Leaving directory '/home/coder/cudf/cpp/build/CMakeFiles/CMakeScratch/TryCompile-ZVxIG6'
    gmake: *** [Makefile:127: cmTC_94ec7/fast] Error 2
   
  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:26 (project)
```

**Steps/Code to reproduce bug**
1. Reopen cudf in dev container as someone outside of NVIDIA
2. Try to compile simple program

**Expected behavior**
Using the build script

**Environment details**
cuda 12.0 with conda devcontainer

**Additional context**
https://github.com/NVIDIA/cccl/issues/593

**Comment by cwharris** [comment]
This error should have been fixed with https://github.com/rapidsai/devcontainers/pull/169/files. Is it possible you are running an older container? Can you tell me what the following environment variables are set to?
```
SCCACHE_BUCKET
SCCACHE_REGION
```

**Comment by ZelboK** [comment]
I imagine if I was using the old dev container, both of those would return values correct? They both returned values, one was us-east iirc(lost the terminal i did this in, i apologize lol)

I went through with the authentication process this time, where as when I made this issue I skipped it, and it now works. Both variables return nothing.

Thanks!

**Comment by esoha-nvidia** [comment]
I suffer from this issue, too.

**Comment by ZelboK** [comment]
> I suffer from this issue, too.

Are you skipping the authentication/login on to github? If you are, that might be why. I noticed this problem went away after I went through with that. Unless I fixed it somehow a different way without realizing it.

**Comment by cwharris** [comment]
@esoha-nvidia 's issue was something else, and we were able to get it resolved. thanks, @ZelboK .

**Comment by ZelboK** [comment]
> unset SCCACHE_BUCKE

BTW to clarify my 

> @esoha-nvidia 's issue was something else, and we were able to get it resolved. thanks, @ZelboK .
> 
> Essentially we needed to `unset SCCACHE_BUCKET` from the environment we were in.

Glad it was resolved! I should add that this environment variable was also unset for me when it resolved, so I'm pretty sure that it is the same problem, it's just that the environment variable unset right coincidentally after I authenticated with github. I didn't touch the environment variables at all so I assumed that this was the fix.

**Comment by vyasr** [comment]
I'm going to close this issue as resolved for now since it seems like both issues were resolved in unrelated ways, but feel free to continue the discussion and reopen if further help is needed.

**Comment by esoha-nvidia** [comment]
I got help and found this:

```
docker run -it rapidsai/ci-conda:cuda12.2.2-ubuntu22.04-py3.10-amd64
git clone https://github.com/rapidsai/cudf
cd cudf
mamba env create -f conda/environments/all_cuda-120_arch-x86_64.yaml
conda activate all_cuda-120_arch-x86_64
mamba install cuda-nvtx-dev
unset SCCACHE_BUCKET
./build.sh
```

**Comment by vyasr** [comment]
That works, but that's not using devcontainers. That's using a separate container that happens to be a valid container in which to build RAPIDS. It should work fine for you though aside from the inability to access the cache.
