### ISSUE TITLE
[BUG] COMMAND NOT WORKING: pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11 

### ISSUE THREAD

**Issue by dking21st** [rapidsai/cudf#14645]
**Describe the bug**
I'm trying to build a docker image and install cuDF as I would like to use Nvidia Merlin with GPU.
However, `pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11` command is returning an error. 
Even I copy and paste the suggestion install command, it fails. 

**Steps/Code to reproduce bug**
```
=> ERROR [13/22] RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11                4.9s 
------                                                                                                                   
 > [13/22] RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11:                           
1.543 Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com                                               
2.726 Collecting cudf-cu11                                                                                               
3.017   Downloading cudf-cu11-23.12.1.tar.gz (6.8 kB)                                                                    
3.046   Preparing metadata (setup.py): started                                                                           
3.578   Preparing metadata (setup.py): finished with status 'error'
3.602   error: subprocess-exited-with-error
3.602   
3.602   × python setup.py egg_info did not run successfully.
3.602   │ exit code: 1
3.602   ╰─> [16 lines of output]
3.602       Traceback (most recent call last):
3.602         File "<string>", line 2, in <module>
3.602         File "<pip-setuptools-caller>", line 34, in <module>
3.602         File "/tmp/pip-install-50dn1tgn/cudf-cu11_12d5907ae07f4ca8a449949af8f6f303/setup.py", line 137, in <module>
3.602           raise RuntimeError(open("ERROR.txt", "r").read())
3.602       RuntimeError:
3.602       ###########################################################################################
3.602       The package you are trying to install is only a placeholder project on PyPI.org repository.
3.602       This package is hosted on NVIDIA Python Package Index.
3.602       
3.602       This package can be installed as:
3.602       ```
3.602       $ pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11
3.602       ```
3.602       ###########################################################################################
3.602       
3.602       [end of output]
3.602   
3.602   note: This error originates from a subprocess, and is likely not a problem with pip.
3.610 error: metadata-generation-failed
3.610 
3.610 × Encountered error while generating package metadata.
3.610 ╰─> See above for output.
3.610 
3.610 note: This is an issue with the package mentioned above, not pip.
3.610 hint: See above for details.
------
```

**Expected behavior**
I want cuDF to be installed properly, so I can use nvtabular / merlin.models (tensorflow) with GPU configuration. 

**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda, Docker, or from source]

Here is my dockerfile that I use to build docker image

```
FROM --platform=linux/amd64 tensorflow/tensorflow:2.12.0-gpu as prod

WORKDIR /content

COPY ./airflow . 
COPY ./images/requirements.txt .

RUN apt-get update && yes|apt-get upgrade

# Adding wget and bzip2
RUN apt-get install -y wget bzip2

# Add sudo
RUN apt-get -y install sudo

RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev libffi-dev gcc-x86-64-linux-gnu

WORKDIR /root

# Set requirements
RUN pip install --upgrade pip
RUN apt-get install -y git

#RAPIDs
RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11 
```

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

* I'm trying to build a docker image that will be used with Airflow & KubernetPodOperator
* I initially tried with the command from here (https://docs.rapids.ai/install#pip) but error suggested to run with `RUN pip install --no-cache-dir --extra-index-url https://pypi.nvidia.com cudf-cu11`  command. However, it is failing again.
* the main reason why I think I need to install cudf is because I'm seeing this error message when I try to run my code on airflow with current image (image without cudf)

```
[2023-12-16, 08:32:38 KST] {pod_manager.py:203} INFO -   File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 251, in __init__
[2023-12-16, 08:32:38 KST] {pod_manager.py:203} INFO -     raise RuntimeError(
[2023-12-16, 08:32:38 KST] {pod_manager.py:203} INFO - RuntimeError: Cannot initialize Dataset on GPU. cudf package not found. Check that cudf is installed in this environment and can be imported.
```

**Comment by bdice** [comment]
```
File "/usr/local/lib/python3.8/dist-packages/merlin/io/dataset.py", line 251, in __init__
```
From that line, it looks like you're using Python 3.8. Currently cuDF produces conda packages and wheels for Python 3.9 and 3.10. Python 3.8 support was dropped in 23.06 (https://docs.rapids.ai/notices/rsn0029/). NEP 29 also dropped Python 3.8 around that time (April 2023, per https://numpy.org/neps/nep-0029-deprecation_policy.html), making it hard for RAPIDS to support anything below 3.9.

You can check the RAPIDS Installation Guide (https://docs.rapids.ai/install) for more information about supported platforms and versions.

**Comment by dking21st** [comment]
@bdice Thank you for your comment. 
Do you know how should I update docker file to run with Python 3.9+ then? should I just do pip install?

**Comment by bdice** [comment]
I'm not familiar with the `tensorflow/tensorflow:2.12.0-gpu` Docker image, but from reading https://hub.docker.com/r/tensorflow/tensorflow/ it seems that Python 3.8 is the newest version available. Those images won't be compatible with RAPIDS, which requires Python 3.9 or 3.10. You might be able to use the NVIDIA Deep Learning Framework containers, which include TensorFlow (or PyTorch) and RAPIDS pre-installed. https://catalog.ngc.nvidia.com/orgs/nvidia/collections/nvidia_dlfw

**Comment by bdice** [comment]
I'll close this for now -- feel free to follow up if upgrading Python did not solve the issue.
