### ISSUE TITLE
Remove arrow dependency in cuIO by implementing a `host_buffer_source`

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#14661]
Currently we use `arrow::io::BufferReader` to implement a zero-copy datasource for host buffers. This is a feature we could implement ourselves and remove the last of arrow dependency in cuIO.

A requirement for this source type would be to avoid copying the data when calling `std::unique_ptr<datasource::buffer> host_read(size_t offset, size_t size)`. This is what `device_buffer_source` alrady does in its d`evice_read` implementation.

**Comment by ZelboK** [comment]
Can I take this

**Comment by vyasr** [comment]
Related to #15193

**Comment by ZelboK** [comment]
I believe this should be closed per https://github.com/rapidsai/cudf/pull/15189

**Comment by jakirkham** [comment]
Should we close this or is there more to do here?

**Comment by vyasr** [comment]
Thanks for the ping @ZelboK! Yes, this was resolved by #15189.
