### ISSUE TITLE
[BUG] The read_json() method of cudf can't parse the string like "5-0"

### ISSUE THREAD

**Issue by tx2002** [rapidsai/cudf#14670]
**Describe the bug**
The read_json() method of cudf can't parse the string like "5-0".
It seems that the number in front cannot be larger than the number in the back.

**Steps/Code to reproduce bug**
run code
```
import cudf as pd

data = '''[{"id":"1","Col_01":"test","Col_02":"77"},

{"id":"2","Col_01":"test","Col_02":"1355-0652142"}]
'''

df = pd.read_json(data, orient = "records")

df
```
get error
![image](https://github.com/rapidsai/cudf/assets/76741680/b8998b5d-a4e6-4ea3-83d0-4474dccfc39b)

If I use the normal pandas, it can get the correct answer.
```
import pandas as pd

data = '''[{"id":"1","Col_01":"test","Col_02":"77"},

{"id":"2","Col_01":"test","Col_02":"1355-0652142"}]
'''

df = pd.read_json(data, orient = "records")

df
```
If I change the `5-0` to `5-5` and still use cudf, it also right.
```
import cudf as pd

data = '''[{"id":"1","Col_01":"test","Col_02":"77"},

{"id":"2","Col_01":"test","Col_02":"1355-5652142"}]
'''

df = pd.read_json(data, orient = "records")

df
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: pip

**Comment by karthikeyann** [comment]
Thank you for reporting the issue.
Which cudf version has this issue?

I tried locally, but I could not replicate the issue.
Just `orient = "records"` with `lines=False` (default) will invoke pandas.read_json internally. It should show a warning
`UserWarning: Using CPU via Pandas to read JSON dataset, this may be GPU accelerated in the future`

With cudf GPU engine too, `df3 = cudf.read_json(data, orient = "records", engine="cudf")`, it works.

**Comment by karthikeyann** [comment]
Closing the issue.

In [3]: df3 = cudf.read_json(data, orient = "records", engine="cudf")
In [8]: df3["Col_02"][1]
Out[8]: '1355-0652142'
