### ISSUE TITLE
[FEA] cudf.pandas details on CPU fall backs

### ISSUE THREAD

**Issue by yz342** [rapidsai/cudf#14709]
My code runs 3 times slower with cudf.pandas instead of pandas. I would like to understand what part of the code is executed on the GPU and which part of the code is executed on the CPU so as to better understand what's causing the slowdown. It is often possible to rewrite pandas functions. Would love to see a feature that enables this.

Also, there is no documentation on CUDF_PANDAS_FALLBACK_MODE.

**Comment by bdice** [comment]
Please try the cudf.pandas profiler and let us know what seems to be slowing down the code: https://docs.rapids.ai/api/cudf/nightly/cudf_pandas/usage/#understanding-performance-the-cudf-pandas-profiler

The docs on CUDF_PANDAS_FALLBACK_MODE are here: https://docs.rapids.ai/api/cudf/nightly/cudf_pandas/faq/#can-i-force-running-on-the-cpu
