### ISSUE TITLE
[BUG] Tests fail to build - undefined references to NVcategory functions

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1470]
I've pulled branch-0.7 and recreated my conda environment. I deleted and recreated my build directory, ran `cmake ../cpp` and built. The compilation went fine, but when linking the test binaries, I get link errors regarding NVCategory symbols:
```
[ 34%] Linking CUDA executable ../gtests/UTILITIES_TEST
[ 34%] Linking CUDA executable ../gtests/TRANSPOSE_TEST
[ 35%] Linking CUDA executable ../gtests/COPYING_TEST
[ 36%] Linking CUDA executable ../gtests/DLPACK_TEST
../libcudf.so: undefined reference to `NVCategory::get_values(int*, bool)'
../libcudf.so: undefined reference to `NVCategory::gather(int const*, unsigned int, bool)'
../libcudf.so: undefined reference to `NVCategory::values_cptr()'
../libcudf.so: undefined reference to `NVCategory::merge_and_remap(NVCategory&)'
../libcudf.so: undefined reference to `NVCategory::add_keys_and_remap(NVStrings&)'
../libcudf.so: undefined reference to `NVCategory::copy()'
collect2: error: ld returned 1 exit status
tests/CMakeFiles/TRANSPOSE_TEST.dir/build.make:133: recipe for target 'gtests/TRANSPOSE_TEST' failed
make[2]: *** [gtests/TRANSPOSE_TEST] Error 1
CMakeFiles/Makefile2:1238: recipe for target 'tests/CMakeFiles/TRANSPOSE_TEST.dir/all' failed
make[1]: *** [tests/CMakeFiles/TRANSPOSE_TEST.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../libcudf.so: undefined reference to `NVCategory::get_values(int*, bool)'
../libcudf.so: undefined reference to `NVCategory::gather(int const*, unsigned int, bool)'
../libcudf.so: undefined reference to `NVCategory::values_cptr()'
../libcudf.so: undefined reference to `NVCategory::merge_and_remap(NVCategory&)'
../libcudf.so: undefined reference to `NVCategory::add_keys_and_remap(NVStrings&)'
../libcudf.so: undefined reference to `NVCategory::copy()'
collect2: error: ld returned 1 exit status
```
and so on.

My guess is that this has something to do with PR #1435, but I'm not sure.

PS:
1. I use Devuan ASCII (~= Debian Stretch) with CUDA 9.2 installed manually.
2. Probably not related to #1469 but I'll mention it anyway.

**Comment by kkraus14** [comment]
@eyalroz can you run `conda list | grep -i nvstrings` and post the output here? This looks like you're getting an old / wrong version.

**Comment by eyalroz** [comment]
```
$ conda list | grep -i nvstrings
libnvstrings              0.7.0.dev0           cuda9.2_95    rapidsai-nightly/label/cuda9.2
nvstrings                 0.2.0            cuda9.2_py37_0    nvidia/label/cuda9.2
```
Maybe I need to remove the old version somehow?

**Comment by kkraus14** [comment]
@eyalroz you should be grabbing `nvstrings` from the `rapidsai-nightly/label/cuda9.2` and getting version `0.7.0.dev0`. Likely what's happening in your above environment is that the `0.2.0` package which has the old shared libraries was installed after `libnvstrings` and overwrote the libs.

**Comment by eyalroz** [comment]
@kkraus14 : Perhaps, but - CMake should still notice that it's missing what it needs, and not proceed to Makefile generation. In my `CMakeCache.txt`, I see:
```
//Path to a library.
NVCATEGORY_LIBRARY:FILEPATH=NVCATEGORY_LIBRARY-NOTFOUND
// etc. etc.
//Path to a library.
NVSTRINGS_LIBRARY:FILEPATH=NVSTRINGS_LIBRARY-NOTFOUND
```
That should not be acceptable.

**Comment by eyalroz** [comment]
I've worked around this by manually copying the `.so`  files from the `pkgs/libnvstrings-0.7.0.dev0-cuda9.2_95/lib/` subdirectory into `envs/cudf/lib`.
