### ISSUE TITLE
[FEA] Resolve degenerate performance in `create_structs_data`

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#14716]
**Is your feature request related to a problem? Please describe.**
While writing the blog post "Streamline ETL Workflows with Nested Data Types in RAPIDS libcudf" [link](https://developer.nvidia.com/blog/streamline-etl-workflows-with-nested-data-types-in-rapids-libcudf/), we noticed degenerate behavior during copying of deeply nested struct columns. One way to observe a similar phenomenon is to profile a libcudf benchmark that generates struct data. 

Using this command you can generate a representative profile, with the region of interest being the call to `create_structs_data` for 1M rows and depth 16. (Note: would someone please add NVTX regions to `create_structs_data` and other data generators? 😄)
```
nsys profile -t nvtx,cuda,osrt -f true --cuda-memory-usage=true --gpu-metrics-device=0 ./SORT_NVBENCH --profile --device 0 --benchmark 1 --axis T=AVERAGE --axis NumRows=1000000 --axis Nulls=0 --axis Depth=16
```

Please note that the `rank_struct` timing (~11 ms on A100) is not the focus of this issue. Rather the degenerate performance is in the 7.4 s spent in chained calls to `mutable_view`.
![image](https://github.com/rapidsai/cudf/assets/12725111/5f5cdfbf-b22c-4ab3-8fab-3608bb175379)
[prof2.zip](https://github.com/rapidsai/cudf/files/13856463/prof2.zip)

**Describe the solution you'd like**
First, we should implement nvbench benchmarks that monitor the runtime of copying and/or creating columns. We could create benchmarks for the generator functions `create_structs_data` and `create_lists_data` with an nvbench "axis" to control nesting depth. Presumably this benchmark would show unusually poor scaling with depth for struct types.

Second, we should investigate and resolve the degenerate performance in creating deeply nested struct columns. We should expect struct column creation runtime to not be a strong function of depth, especially when each struct level is not nullable.

**Describe alternatives you've considered**
Accept unusually slow performance when working with deeply nested structs.

**Comment by SurajAralihalli** [comment]
Hello, I'd like to try doing this task, thanks!

**Comment by GregoryKimball** [comment]
Solved by #14761

**Comment by SurajAralihalli** [comment]
Hey @GregoryKimball, you are right. I benchmarked `n_rows : 2**26` again and here is my analysis. 

<img width="1216" alt="Screenshot 2024-01-22 at 4 44 38 PM" src="https://github.com/rapidsai/cudf/assets/24796335/de8c1035-93b3-4029-8a5b-3d6a806ef0ae">


Most of the time is spent in generating the `n_rows` validity vector (`libcudf: Validity vector creation`) not in the nested struct creation (`libcudf: Struct structs_column_wrapper creation`). I believe struct copying step is close to SOL.

**Comment by karthikeyann** [comment]
would preallocating `struct_validity` make it faster?

**Comment by SurajAralihalli** [comment]
> would preallocating ([vector::reserve](https://en.cppreference.com/w/cpp/container/vector/reserve)) `struct_validity` make it faster?

Thank you @karthikeyann for the suggestion, but it did not result in any noticeable speedup.

https://github.com/SurajAralihalli/cudf/blob/c2dceea07f150e19c1dd66a610ead5f05fbf4c8a/cpp/benchmarks/common/generate_nested_types.hpp#L108

**Comment by GregoryKimball** [comment]
Thank you @SurajAralihalli for taking a closer look. I think we are good to close this at completed!
