### ISSUE TITLE
[BUG] gdf_hash_partition can incorrectly partition string category columns

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#1473]
**Describe the bug**
gdf_hash_partition on a string category column hashes the category index rather than the underlying string.  This can cause a string represented by a category index to be incorrectly partitioned between two tasks that build different category indices for the same string.

**Steps/Code to reproduce bug**
Task 1 receives a string column of three strings, "A", "B", and "C".  Task 2 receives a string column of "A", "C", and "D".  Task 1 builds a string category column which results in index mappings of A=0, B=1, and C=2.  Task 2's mappings will be A=0, C=1, and D=2.  When both tasks hash partition their respective string category columns, the "C" string will likely be hashed to different partitions because the tasks are hashing the category index numbers 1 and 2 rather than the same underlying string, "C".

**Expected behavior**
String category columns should partition in the same manner as the underlying strings the category indices represent.  Without this behavior hash partitioning of strings is difficult to achieve in practice.  Either a global string category table would be required to be used by all tasks when partitioning or libcudf would need to support string column partitioning.

**Comment by jrhemstad** [comment]
This is definitely an issue, and requires additional functionality be provided by an NVCategory column.

See https://github.com/rapidsai/custrings/issues/250

**Comment by jlowe** [comment]
This bug is problematic for a distributed setup for any partitioning is done on string category columns (e.g.: distributed join).  Is there a rough estimate for when this could be addressed?

It's possible to fix this without modifying custrings by having the cudf table build a string view for the category using`NVCategory::create_index`.  That can allow `hash_row` to hash the string data instead of the category index.  Alternatively a column of hashes could be built based on the string data accessible from the string view and then table hashing could substitute the hash column for the string category column.  However I could see it being much faster if implemented in custrings since the string view creation could be avoided.

**Comment by jrhemstad** [comment]
This is fixed in the libucdf++ hash partition.
