### ISSUE TITLE
[BUG] gdf_hash_partition does not gather string category columns

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#1474]
**Describe the bug**
When gdf_hash_partition is called on a string category column the output category column has no NVCategory pointer that represents the order of partitioned strings.  This is inconsistent with string category column handling from other libcudf functions that can output new string category columns like the groupby and join operations.  It is up to the caller to gather the original NVCategory based on the output category indices from gdf_hash_partition.

**Steps/Code to reproduce bug**
Call `gdf_hash_partition` on a string category column and note the null value in the `dtype_info.category` field of the resulting output gdf_column structure.

**Expected behavior**
When libcudf creates a new string category column there should be a valid NVCategory pointer associated with it.  If there's reasons to avoid doing this then the behavior should be clearly documented.

**Comment by sameerz** [comment]
Superseded by #2811 and #2861.
