### ISSUE TITLE
Revisit conditional dependency handling in wheels

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#14773]
Currently we have a bunch of logic that uses `sed` to change out bits of `pyproject.toml`. Wonder if there is a better option for handling this in `pyproject.toml` without needing `sed`

https://github.com/rapidsai/cudf/blob/42e946f4056bed7942d7a355aeb23317506305e5/ci/build_wheel.sh#L37-L53

**Comment by bdice** [comment]
@jakirkham This is largely overlapping with https://github.com/rapidsai/dependency-file-generator/issues/46. There's an open PR for resolving that but it has been stalled. That would solve some of these pieces, specifically the conditionals like `[[ $PACKAGE_CUDA_SUFFIX == "-cu12" ]]`.

However, the `alpha_spec` piece would not be possible to implement with `rapids-dependency-file-generator`. Do you have thoughts on how to accomplish that without `sed`?

**Comment by vyasr** [comment]
This is being solved with a combination of https://github.com/rapidsai/rapids-build-backend/ and https://github.com/rapidsai/pre-commit-hooks/pull/28.
