### ISSUE TITLE
[FEA] Allow grouping on arbitrary arrays passed in at runtime

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1477]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to be able to pass in an arbitrary array/series to `groupby(...)` and have my groupby create groups based on this array/series.

**Describe the solution you'd like**
I'd like to be able to do the cudf equivalent of the following:

```
import pandas as pd
import numpy as np

ser1 = [1,1,2,2,33,33]
ser2 = [1,1,2,19,4,None,]
pdf = pd.DataFrame({'a':ser1, 'b':ser2})
print(pdf)

group_dummy = [1,4,1,1,1,4]
print(pdf.groupby(group_dummy).sum())
    a     b
0   1   1.0
1   1   1.0
2   2   2.0
3   2  19.0
4  33   4.0
5  33   NaN
    a     b
1  38  26.0
4  34   1.0
```

**Describe alternatives you've considered**
The alternative is to create a new dataframe column containing the new array/series, and then use that as the groupby column. One potential solution is to simply wrap this functionality into the groupby process.

**Additional context**
This will help downstream with dask-cudf.

**Comment by shwina** [comment]
@beckernick Can this be closed? It's possible to group by an arbitrary `Series` (but of same length as the DF) right now

**Comment by beckernick** [comment]
@shwina let's leave this open until I confirm that Dask internally can do what it needs with a Series based approach. With that said, if it requires a list, perhaps the right solution is to update the Dask function to expect a Series. Looks like I didn't link this issue to a specific Dask issue, so it will take a bit to dig it up.

**Comment by shwina** [comment]
Great. Unfortunately a list doesn't work right now although if it's absolutely required I can try to make that work.

**Comment by kkraus14** [comment]
Closing as this was resolved by the groupby refactor. Please reopen if there's still an issue.
