### ISSUE TITLE
[BUG] test_dask.py should skip unless minimum version 1.1.0 is installed 

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1488]
**Describe the bug**
python/cudf/tests/test_dask.py runs a `testorskip` on the dask module. If the dask module is installed, but has too early a version, the tests may fail due to missing features in dask.

**Steps/Code to reproduce bug**
Install an old version of desk-core, and run pytests.

**Expected behavior**
Make the test skip if the version is insufficient (1.1.0 I believe). Also make it display a warning explaining why the test is skipped if it does skip.

**Comment by jakirkham** [comment]
Thanks for filing this issue. Have submitted PR ( https://github.com/rapidsai/cudf/pull/1490 ), which hopefully addresses it.
