### ISSUE TITLE
[QST] Is there any plan to support insert unused_key in concurrent_unordered_map?

### ISSUE THREAD

**Issue by OliverLPH** [rapidsai/cudf#14896]
**What is your question?**
[concurrent_unordered_map](https://github.com/rapidsai/cudf/blob/branch-24.02/cpp/src/hash/concurrent_unordered_map.cuh#) need set [unused_key](https://github.com/rapidsai/cudf/blob/branch-24.02/cpp/src/hash/concurrent_unordered_map.cuh#L165)
 when construct it. And unused_key was set to `std::numeric_limits<key_type>::max()` by default. However, there is a possibility that the inserted key may be equal to the unused_key in my scenarios, which might potentially cause the program crash.

I just wondering is there any plans to support unused_key insert and find? Thanks for your valuable work.

**Comment by bdice** [comment]
Hi @OliverLPH, thanks for the question. We are phasing out these classes from cudf in favor of https://github.com/NVIDIA/cuCollections/. @PointKernel may be able to answer your question, if it is relevant to cuCollections.

**Comment by PointKernel** [comment]
> there is a possibility that the inserted key may be equal to the unused_key in my scenarios

@OliverLPH The best solution is to choose a value that will be never used in your case as the unused key (or "sentinel"). Would `std::numeric_limits<key_type>::min()` or simply `-1` work for you?

Another option is to remap sentinel to a different value to avoid conflicts, e.g. https://github.com/rapidsai/cudf/blob/821f4dea107db6a51fcbffff997fa6844ab5565f/cpp/src/join/join_common_utils.cuh#L34-L45

Just FYI, `concurrent_unordered_map` will be deprecated and removed from the repo soon and as @bdice mentioned, https://github.com/NVIDIA/cuCollections/ is the place where we actively develop/maintain GPU hash tables.

**Comment by OliverLPH** [comment]
@PointKernel Thanks for your prompt reply. 
In my particular case, controlling the input key may be difficult, so I will consider your second suggestion of doing remaps for the unused key.
I also have a question: why this corner case still not been implemented in the latest version of cuco's [concurrent_unordered_map.cuh](https://github.com/rapidsai/cudf/blob/branch-24.04/cpp/src/hash/concurrent_unordered_map.cuh#L142)?

Thank you.

**Comment by PointKernel** [comment]
> why this corner case still not been implemented in the latest version of cuco's [static_map](https://github.com/NVIDIA/cuCollections/blob/dev/include/cuco/static_map.cuh#L168)?

It's not a corner case but more of an implementation choice. We chose to use a sentinel value instead of an additional bitmask to denote empty slots since the latter requires extra memory space. Then the downside or "inconvenience" is that any insertions against sentinel value are undefined behavior. If it's impossible to find a sentinel in your case, using the remapping functor is the best way out.
