### ISSUE TITLE
[DOC] Link to libcudf developer_guide is broken in cuDF developer_guide

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#14991]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/stable/developer_guide/

**Describe the problems or issues found in the documentation**

The Python cuDF [developer guide](https://docs.rapids.ai/api/cudf/stable/developer_guide/) includes a link to the libcudf developer guide that results in 404 not found. The broken URL is  https://github.com/rapidsai/cudf/blob/main/cpp/docs/DEVELOPER_GUIDE.md

**Suggested fix for documentation**
Replace with link https://docs.rapids.ai/api/libcudf/stable/developer_guide

**Comment by sanjana098** [comment]
I'd love to pick this up.
