### ISSUE TITLE
[BUG]cudf version 23.10: Import issue, getting an Error saying kernel launch configuration was not specified

### ISSUE THREAD

**Issue by Rajrupa1998** [rapidsai/cudf#14994]
**cudf version 23.10: Import issue, getting an Error saying kernel launch configuration was not specified**
Installed cudf from Rapids, my cuda-python version is 12.3.0. I am able to see cudf installed with numba -s command, but not able to import or use the extension.

**Steps/Code to reproduce bug**
Install with
conda create --solver=libmamba -n faster_pandas -c rapidsai -c conda-forge -c nvidia  \
    rapids=23.12 python=3.10 cuda-version=12.0
conda activate faster_pandas
while I am trying to import, the error is kernel launch configuration was not specified, screenshot is attached.

Cuda Device Initialized: True
cuda driver version: 12.1
![WhatsApp Image 2024-02-07 at 5 51 34 PM](https://github.com/rapidsai/cudf/assets/122585536/27c5244d-582a-427d-b79a-aef39e9666c0)

**Comment by shwina** [comment]
@brandon-b-miller does this look familiar to you?

**Comment by brandon-b-miller** [comment]
`numba.cuda` is the module within numba that provides CUDA support. It looks like in this environment, there's a python file located at `~/cs22s505/cuda.py` that's shadowing the real `numba.cuda` module. So the `cudf` internals are getting confused. 

@Rajrupa1998 can you move this `cuda.py` file somewhere else or change its name? One final suggestion, in the `cuda.py` file that is being invoked, the syntax is not quite correct - try using square brackets to specify the launch configuration, like `f[3,5](args)`.

**Comment by bdice** [comment]
Agreed. `import cuda` needs to find the cuda-python package (https://nvidia.github.io/cuda-python/) but instead it's finding a local module named `cuda.py`. Try renaming that file.

**Comment by shwina** [comment]
@Rajrupa1998 I'm going to go ahead and close this issue as it's been answered. But, if the suggestions above don't work for you or if you have other problems, please feel free to reopen. Thanks!
