### ISSUE TITLE
A don't install in google colab[BUG]

### ISSUE THREAD

**Issue by joker2017** [rapidsai/cudf#1500]
**Describe the bug**
I can not install google colab(https://colab.research.google.com). Writes OSError: cannot load library 'librmm.so': librmm.so: cannot be shared file or directory.

GPU Tesla T4
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
Cuda compilation tools, release 10.0, V10.0.130

**Comment by kkraus14** [comment]
@joker2017 see our blog on supporting colab: https://medium.com/rapids-ai/run-rapids-on-google-colab-for-free-1617ac6323a8
