### ISSUE TITLE
[FEA] Apply functions to columns independently in parallel.

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/cudf#1501]
**Is your feature request related to a problem? Please describe.**
For the dataset with many uncorrelated columns, we want to transform each column independently in parallel. An example is as follows:
```
# needs better way to replace the for loop.
# number of columns could be large.
for col in df.columns:
    df[col] = some_cudf_transform_function(df[col])
```
**Describe the solution you'd like**
Apply the same transform function to a group of columns in parallel, ideally through an API call directly supported by cudf.

**Additional context**
An example of such property is [Santander dataset](https://www.kaggle.com/c/santander-customer-transaction-prediction) and the corresponding ETL can be found at cell 5 of the [notebook](https://github.com/daxiongshu/notebooks-extended/blob/kaggle/tutorials/advanced/kaggle/santander/cudf_tf_demo.ipynb). Independent columns might be resulted from [anonymization](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3046817/).

**Comment by jrhemstad** [comment]
Once libcudf APIs are updated to expose streams via external APIs, I'd hope this should be straightforward from the Python side to identify that these column-wise operations can be done independently and execute them on separate streams. 

See https://github.com/rapidsai/cudf/issues/925

**Comment by vyasr** [comment]
More recent efforts have focused on aligning cudf more closely with pandas, not less. This functionality is therefore unlikely to be directly supported in cudf. However, it should be quite easy to enable something like this in pylibcudf (especially using multiple streams), which is probably the way that we will want to go.
