### ISSUE TITLE
[BUG] Read parquet reads strings as ints

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1502]
**Describe the bug**
cudf `read_parquet` method reads strings in as integers

**Steps/Code to reproduce bug**
```
>>> import pandas as pd
>>> import cudf

>>> pdf = pd.DataFrame()
>>> pdf['a'] = ['testString']*100
>>> pdf.to_parquet('temp.snappy.parquet')

>>> gdf = cudf.io.read_parquet('temp.snappy.parquet')

>>> gdf.head().to_pandas()


   | a
-- | --
1267071231
1267071231
1267071231
1267071231
1267071231

>>> gdf.dtypes

a    int32
dtype: object
```

**Expected behavior**

```
>>> pdf.head()

	a
0	testString
1	testString
2	testString
3	testString
4	testString

>>> pdf.dtypes

a    object
dtype: object
```

**Environment details (please complete the following information):**
 - From source

**Comment by ayushdg** [comment]
To add to the example above, bools get read as int8. Which is not as big an issue as we can easily go back from int to bool.
```
import pandas as pd
import cudf

df = pd.DataFrame()
df['a'] = ['testString']*100
df['b'] = [True,False]*50
df.to_parquet('temp.snappy.parquet')
df2 = cudf.io.read_parquet('temp.snappy.parquet')

df2.head().to_pandas()
```
```

  | a | b
-- | -- | --
1267071231 | 1
1267071231 | 0
1267071231 | 1
1267071231 | 0
1267071231 | 1
```

**Comment by j-ieong** [comment]
We currently map byte arrays (like char* strings) to GDF_CATEGORY, by default like CSV Reader. GDF_CATEGORY is basically a 32-bit hash of the string so that's why you see it as an int. We can add an option to map them to GDF_STRING columns instead.

As for the booleans, cuDF doesn't currently have a native bool type so it's currently GDF_INT8. Once PR #1142 gets merged, then we can map to the new type.

**Comment by ayushdg** [comment]
@j-ieong Thanks for the update! I don't know when the csv reader things might have gotten updated but I think they support strings now. 

```
import pandas as pd
import cudf

pdf = pd.DataFrame()
pdf['a'] = ['testString']*100
pdf['b'] = [True,False]*50

pdf.to_csv('temp.csv',index = False)
gdf = cudf.io.read_csv('temp.csv')

gdf.head().to_pandas()
```
```
  | a | b
-- | -- | --
testString | True
testString | False
testString | True
testString | False
testString | True
```
```
>>> gdf.dtypes

a    object
b    object
dtype: object
```

Yeah once #1142 gets merged all the readers can handle booleans using this type :)

**Comment by randerzander** [comment]
> We can add an option to map them to GDF_STRING columns instead.

Now that strings are supported in cuDF, we should read them as GDF_STRING by default.

cudf.read_csv already does this, and now only hashes if you specify 'category' as a column's dtype.

**Comment by j-ieong** [comment]
> > We can add an option to map them to GDF_STRING columns instead.
> 
> Now that strings are supported in cuDF, we should read them as GDF_STRING by default.
> 
> cudf.read_csv already does this, and now only hashes if you specify 'category' as a column's dtype.

Ah yes, I forgot we changed the default a while back. PR #1507 is simple enough that hopefully it'll merge soon.
