### ISSUE TITLE
[FEA] Automate include grouping order in .clang-format

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#15024]
**Is your feature request related to a problem? Please describe.**
Use the IncludeCategories settings in .clang-format to automatically enforce our documented #include order in libcudf. See https://docs.rapids.ai/api/libcudf/stable/developer_guide

Fixed by #14993

**Comment by bdice** [comment]
Closed by https://github.com/rapidsai/cudf/pull/15063.
