### ISSUE TITLE
[FEA] Integrate ZLUDA for AMD CUDA

### ISSUE THREAD

**Issue by GermanAizek** [rapidsai/cudf#15035]
**Describe the feature**
@davidwendt,
https://github.com/vosen/ZLUDA
it can give feature run CUDA program on amd video cards if cuda code is optimized, and speed up work on amd.

**Comment by GregoryKimball** [comment]
Hello @GermanAizek, thank you for mentioning the ZLUDA project. This looks like a promising direction, and currently it has some [important limitations](https://github.com/vosen/ZLUDA?tab=readme-ov-file#known-issues) in support for CUDA 12 and the latest CCCL. We don't currently plan to support ZLUDA, but please let us know if are able to build and run libcudf for AMD hardware using ZLUDA.
