### ISSUE TITLE
[BUG] gdf.loc[:, col_name] returns a key error with the first char of col_name

### ISSUE THREAD

**Issue by EvenOldridge** [rapidsai/cudf#1505]
I'm trying to slice a  cuDF dataframe to pull out a single column from the mortgage dataset.  Data has been loaded into the dataframe via from_parquet.

path contains a single parquet from the intermediate output of: https://github.com/rapidsai/notebooks/blob/b2ff2b82af22b66ff9f90351bef8aa4560e57ac0/mortgage/E2E_Deep_Learning.ipynb

**Steps/Code to reproduce bug**
gdf = cudf.read_parquet(path) 
col_name = 'delinquency_12'
if target_name in gdf.columns: # establish the column exists
    target = gdf.loc[:,col_name]

This returns: KeyError: 'd'
Manually changing col_name within the check to 'thiscoldoesnotexist' returns KeyError: 't'
Also tried variables and double quotes with same behaviour.

It looks as if the column name in slicing is being truncated to the first character.  

**Expected behavior**
Return the sliced column
In the case of 'thiscoldoesnotexist' the error should be: KeyError: 'thiscoldoesnotexist' 

**Environment details (please complete the following information):**
 - Environment location: rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04
 - Method of cuDF install: rapids container
 cudf.__version__ = '0.6.1+1.g9ca9325'

**Additional context**

**Comment by beckernick** [comment]
[This](https://github.com/rapidsai/cudf/blob/branch-0.7/python/cudf/dataframe/dataframe.py#L2782) is the line that causes this bug. It implicitly assumes col_slice is a list, when it can be a string. Looping over a string causes the character behavior. This is also a partial blocker for cumulative aggregations in dask-cudf

**Comment by rjzamora** [comment]
I get the same error for this simple example:
```p
import cudf
import pandas as pd
import pyarrow as pa
df = pd.DataFrame({'one': [-1, 0, 2.5],
                   'two': [45, 3, 17]})
table = pa.Table.from_pandas(df)
pa.parquet.write_table(table, 'example.parquet')
gdf = cudf.read_parquet('example.parquet')
col_name = 'two'
if col_name in gdf.columns:
    target = gdf.loc[:,col_name]
```

The error is resolved by adding the following to the end of the `elif isinstance(arg, tuple):` block in the `Loc` class definition (`python/cudf/dataframe/dataframe.py`):
```p
if isinstance(arg_2, str):
    col_slice = [arg_2]
```

I'll open up a PR with the change.
