### ISSUE TITLE
[FEA] Make `Groupby.shift` work for MultiIndex

### ISSUE THREAD

**Issue by amanlai** [rapidsai/cudf#15087]
Say I have a MultiIndex Series as follows:
```python
s = cudf.Series(range(4), index=cudf.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)], names=['f', 's']))
```
which looks like:
```none
f   s
a  1    0
    2    1
b  1    2
    2    3
dtype: int64
```
I want to shift this Series down by the first index level:
```python
s.groupby(level=0).shift(1)
```
but I get an error:
```none
AttributeError: 'RangeIndex' object has no attribute '_names'
```
This should produce either
```none
f   s
a  1    NaN
    2    0.0
b  1    NaN
    2    2.0
dtype: float64
```
or 
```none
f   s
a  2    0.0
b  2    2.0
dtype: float64
```
Right now, I can get my desired output by unstacking the Series, shifting it and then stacking it back:
```python
s.to_frame().unstack('f').shift().rename(columns=lambda x: x[1]).stack()
```

which is very ugly. I would like cudf to extend `groupby.shift` to MultiIndex.

**Comment by shwina** [comment]
Thanks - this seems a bug with our implementation of `.shift`. Should be a relatively easy fix - we'll try to get to it ASAP!
