### ISSUE TITLE
[BUG] GPU buffer overrun in zstd::init_huff_tables

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#15096]
**Describe the bug**
Encountered a GPU illegal address crash while trying to load a ZSTD-compressed Parquet file in Spark using the RAPIDS Accelerator.  compute-sanitizer shows the crash originating in zstd::init_huff_tables.

**Steps/Code to reproduce bug**
The following C++ program will recreate the issue when run under compute-sanitizer with the attached Parquet data file as an argument (e.g..: `compute-sanitizer ./repro pqdbg1637506717.parquet`):
```c++
#include <cudf/io/parquet.hpp>
#include <iostream>

int main(int argc, char** argv) {
  if (argc != 2) {
    std::cerr << "Usage: " << argv[0] << " <parquet_file>" << std::endl;
    return 1;
  }
  cudf::io::parquet_reader_options read_opts =
    cudf::io::parquet_reader_options::builder(cudf::io::source_info{argv[1]});
  auto result = cudf::io::read_parquet(read_opts);
  return 0;
}
```
[pqdbg1637506717.parquet.gz](https://github.com/rapidsai/cudf/files/14351766/pqdbg1637506717.parquet.gz)

**Expected behavior**
Parquet file should load without crashing.

**Comment by bdice** [comment]
Closed by https://github.com/rapidsai/cudf/pull/15128.
