### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by amanlai** [rapidsai/cudf#15104]
**Describe the bug**

A call to `.stack()` on a DataFrame with MultiIndex columns by some level results in a DataFrame whose columns are sorted lexicographically (does not preserve the original order).

The following constructor:
```python
df = cudf.DataFrame({('b', 3): [1, 2], ('a', 2): [3, 4]})
```
creates a DataFrame that looks like
```none
   b  a
   3  2
0  1  3
1  2  4
```
Stacking it using `df.stack()` produces
```none
       a    b
0 2  NaN  3.0
  3  1.0  NaN
1 2  NaN  4.0
  3  2.0  NaN
```

Since the original column order was `'b'` and `'a'`, the expected output is
```none
       b    a
0 2  NaN  3.0
  3  1.0  NaN
1 2  NaN  4.0
  3  2.0  NaN
```

This is reproducible on Google Colab using the Rapids installer.

On a related note, I believe `stack()` in pandas behave like this in older versions (e.g. 1.5) but it preserves the original order in newer versions (e.g. 2.2).

**Comment by shwina** [comment]
Thanks for reporting, @amanlai! cc: @galipremsagar any chance this is fixed in the upcoming 2.2 compatibility changes?
