### ISSUE TITLE
got an error when install cudf with pypi[QST]

### ISSUE THREAD

**Issue by fusying-hwang** [rapidsai/cudf#15105]
Hi,
I have installed nividia dirver and cuda toolkit
I used "pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12" to install cudf but get this error prompts

![image](https://github.com/rapidsai/cudf/assets/101255426/047b4676-1225-4cf3-97af-47a08ae52c62)

**Comment by fusying-hwang** [comment]
anyone has any insight on this error, thanks in advance!

**Comment by shwina** [comment]
Thanks for reporting - we're investigating!

**Comment by fusying-hwang** [comment]
after downgrading to python 3.10, it works as a charm. Thanks for the help!
