### ISSUE TITLE
[PERF] `interpolate` in cudf is much slower than `interpolate` in pandas

### ISSUE THREAD

**Issue by amanlai** [rapidsai/cudf#15107]
Let's take an example with 10k rows with 10 missing values:

```python
pdf = pd.Series(np.random.default_rng(0).random(10000))
pdf.iloc[np.random.default_rng(0).choice(len(pdf), size=10, replace=False)] = np.nan

cdf = cudf.from_pandas(pdf)
```
`interpolate` seems to cache values, so to make sure I get an accurate benchmark, I ran it first on the cudf Series before the actual benchmark:
```python
cdf.interpolate(method='linear')
```
Note that this run takes almost 10 seconds while the equivalent call in pandas computes instantly.

Afterwards, I ran the following timeit test using `%timeit` magic in Colab:
```python
%timeit -n 100 pdf.interpolate(method='linear')
# 482 µs ± 18.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit -n 100 cdf.interpolate(method='linear')
# 3.8 ms ± 618 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
As you can see from above, interpolation on the cudf Series is about 8 times slower even after making the test run beforehand.

I expected cudf to perform at least as well as pandas but it was not the case. For a larger frames (with 10 million rows etc.), it takes minutes to compute something that can be done under a second in pandas. Also, not included in the benchmark here but `cudf.pandas` was also much slower than pandas.

---

**Environment details**
- Used pandas==1.5.3, cudf==24.02.01, numpy==1.25.2 on Google Colab. 
- cudf was installed using rapidsai-csp-utils.

Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Comment by bdice** [comment]
Thanks @amanlai for this issue. For anyone who works on this, I wanted to note that there is a performance-related TODO here: https://github.com/rapidsai/cudf/blob/4ce99af7438d38e91ee2540336a278ade2fffd79/python/cudf/cudf/core/indexed_frame.py#L2044

**Comment by shwina** [comment]
Thanks @amanlai - while it definitely looks like we can improve here, I did notice that at a size of 1 million elements, cuDF seems significantly faster:

```python
In [47]: %timeit -n 100 pdf.interpolate(method='linear')
47.9 ms ± 57 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [48]: %timeit -n 100 cdf.interpolate(method='linear')
4.93 ms ± 596 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Generally speaking, cuDF shines at the 1-10 million (and if you have a large enough GPU, 100 million) data size.

**Comment by shwina** [comment]
> interpolate seems to cache values, so to make sure I get an accurate benchmark, I ran it first on the cudf Series before the actual benchmark:

Ah good observation. Rather than cache, this seems to be a one-time JIT overhead - somewhere in the CuPy code base? The first time I run it, here's what I see:

```
cub/detail/detect_cuda_runtime.cuh(39): warning: cuda_runtime_api.h: [jitify] File not found

../util_type.cuh(42): warning: cuda.h: [jitify] File not found

cupy_jitify_exercise(10): warning: cooperative_groups.h: [jitify] File not found
cupy_jitify_exercise(11): warning: cooperative_groups/memcpy_async.h: [jitify] File not found

```

**Comment by amanlai** [comment]
@shwina I did suspect it was a JIT-compiling related issue because the second run was much faster than the first run. I didn't benchmark it against pandas using my real data; didn't realize subsequent runs were much faster than pandas, so thanks for the benchmark on larger data.

Maybe could the documentation be updated to make it clear that to see actual speed up in performance, it has to be run twice (I believe text of that effect are in the numba docs)?

**Comment by amanlai** [comment]
It turns out if you make a call to `interpolate()` on a randomly small cudf object beforehand, the actual interpolation is much faster. So instead of running `cdf.interpolate(method='linear')` twice, it's much better if we do the following:
```python
x = cudf.Series([1]).interpolate()

cdf.interpolate()
```
On a frame with 10mil rows, the first run of the former took 1min 30s while the first run of the second took 2.48s. The second runs of both took 25ms.
