### ISSUE TITLE
`cudf.merge` doesn't guarantee key order

### ISSUE THREAD

**Issue by amanlai** [rapidsai/cudf#15117]
This is especially relevant for left-merge or inner-merge.

Consider the following scenario:
```python
df1 = cudf.DataFrame({'a': list('aedbc'), 'b': range(5)})
df2 = cudf.DataFrame({'a': list('eba'), 'c': range(3)})
df1.merge(df2, how='left', on='a')
```
which produced, for me:
```none
	a	b	c
0	a	0	2
1	e	1	0
2	b	3	1
3	d	2	<NA>
4	c	4	<NA>
```
However, I wanted (note that the values in column `'a'` are ordered as in the original left dataframe `df1`):
```none
	a	b	c
0	a	0	2
1	e	1	0
2	d	2	<NA>
3	b	3	1
4	c	4	<NA>
```
which is guaranteed in pandas.

Sorting is very cheap in cudf, so if the values were originally already sorted, then it's very easy to fix that but if the values have a specific order as in the above example, it's a little more difficult to get back to original ordering.

**Comment by shwina** [comment]
Thanks, @amanlai - cuDF has a [pandas compatibility mode](https://docs.rapids.ai/api/cudf/stable/user_guide/pandas-comparison/#result-ordering), which you can enable to get better alignment with pandas:

```python
In [3]: cudf.options.set_option("mode.pandas_compatible", True)

In [4]: df1 = cudf.DataFrame({'a': list('aedbc'), 'b': range(5)})
   ...: df2 = cudf.DataFrame({'a': list('eba'), 'c': range(3)})
   ...: df1.merge(df2, how='left', on='a')
Out[4]:
   a  b     c
0  a  0     2
1  e  1     0
2  d  2  <NA>
3  b  3     1
4  c  4  <NA>
```

Could you please try that out and let us know if it works?

**Comment by wence-** [comment]
Just to add to @shwina's comment, this is a deliberate choice in the API. Especially when joining on many columns, the argsort that is required to match the input order is a significant additional cost to the runtime.

Perhaps you can explain why you need the output to match the input order for your downstream processing, it might be that we can suggest ways around that need.
