### ISSUE TITLE
Explore writing pylibcudf pyx files using Cython's pure Python mode

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#15135]
Cython offers a [pure Python syntax](https://cython.readthedocs.io/en/latest/src/tutorial/pure.html) that can still be compiled using Cython as long as the underlying constructs can be expressed using Python syntax. While code written in this way cannot yet handle the entire Cython API, in recent versions of Cython it has become far more capable and it supports a wide range of standard Cython use cases. Support for better typing etc are only expected to grow over time (for instance, see https://cython.readthedocs.io/en/latest/src/tutorial/pure.html#reference-table).

We should test out whether pylibcudf Cython modules will support being written using this syntax. While it is probably not worth a large investment of time, it is worth some quick exploration because if it works we would immediately be able to take full advantage of Python tooling that does not currently work (sometimes at all, sometimes not well) for Cython. For example, we could start applying all Python linters/etc to Cython files. Right now our linting of Cython is largely restricted to what cython-lint provides. Moreover, we'd get improved IDE and LSP support out of the box.

Known potential issues and blockers:
- The biggest blocker I foresee is if critical Cython/C++ syntax like the construction of templated containers like vectors is not supported in Python mode, i.e. if pure Python mode cannot handle the use of square brackets as a template specializer even when compiled. If that is a problem then this proposal is probably dead in the water, at least until Cython adds some support for that syntax. It would be useful to establish if that is the case and open Cython feature requests if so.
- [pure Python mode does not yet support enums](https://github.com/cython/cython/issues/4252). This issue may not be a problem for us, though. Essentially all enums that we expose come from libcudf, which means they must be exposed from the C++ pxd files anyway and the corresponding pyx files (in the current tree) exist only to force compilation of the corresponding Python enums. IOW we may never need to declare enums in pyx files.
- pxd files will continue to exist. However, they are much lighter-weight and easier to handle, so being able to convert pyx to py files would still be a win. We will also still need to keep pxd files for declaring the C++ APIs that we are exposing to Python.

**Comment by wence-** [comment]
Just to note, right now, I think the python mode doesn't support really any C++ Cython interfacing features at all (note how https://cython.readthedocs.io/en/latest/src/userguide/wrapping_CPlusPlus.html#wrapping-cplusplus doesn't offer a "pure python" version of any of its examples)

**Comment by vyasr** [comment]
Yup that's my expectation as well from having looked at that page.

**Comment by vyasr** [comment]
I think this is probably not going to be possible anytime soon. While writing "pure Cython" code using the pure Python mode seems like it is feasible, handling the C++ interfaces is (I suspect) out of scope for Cython's pure Python mode for the foreseeable future.
