### ISSUE TITLE
[FEA] Implement Series.where

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1514]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to use `Series.where(...)` in the same way I would do in pandas. This partially blocks dask `cummin` and `cummax` operations (but not sum and product). The API docs are [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.where.html). `where` is essentially an API for replacing values based on a supplied condition that evaluates to a Boolean array.

We can include an assert that requires the `axis` argument to be zero, as we will need that keyword argument downstream regardless of whether it's implemented. `Where` has a lot of complex functionality that may not be necessary to implement all at once. For dask cummin/cummax, minimally sufficient functionality would include the ability to replace all values with a scalar `other` where `cond` evaluates to False.

```python
s = pd.Series(range(5))
s.where(s > 1, 10)
0    10
1    10
2    2
3    3
4    4
dtype: int64
```

**Comment by beckernick** [comment]
This could largely be done in the Python layer, but will at least depend on libcuDF for fixes to using Boolean indexing / replace with null values in columns. Something like this would be sufficient for `cummin`/`cummax` if we can close #1560 (though that issue may be dependent on the broader null handling improvement).

```python
def where(ser, cond, other=None, inplace=False, axis=None,
          level=None, errors='raise', try_cast=False,
          raise_on_error=None):
    
    x = ser.notna()
    idx = x[x == True].index    
    replacement_arr = s.fillna(-9999).iloc[idx].unique().to_array() # cant Boolean index with nulls  
    
    return ser.replace(replacement_arr, other)


s = cudf.Series(list(range(3)) + [None] + list(range(5)))
print(s)
print(where(s, s > 1, 100))
```

**Comment by AK-ayush** [comment]
I am working on and will submit a  PR asap. 
I want to know one thing, are we replacing `nulls` also if `other` is scalar?

**Comment by beckernick** [comment]
@AK-ayush if I understand your question correctly, then the answer is yes. In pandas.where, null values in a column are replaced by a scalar `other` as the boolean condition `cond` will always evaluate to False for that cell. I believe this is the example in my comment above. Let me know if I'm misunderstanding and that's not the case.

**Comment by asmeurer** [comment]
Support for bitwise operations on booleans would be great. Was an issue opened for that? Right now I have to use * for AND and + for OR, which isn't great from a code readability point of view.

**Comment by asmeurer** [comment]
Also:

```py
>>> np.bool_(True) + cudf.Series([True])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'add'>, '__call__', True, <cudf.Series nrows=1 >): 'bool_', 'Series'
```

which makes it annoying (also annoying is that the workaround for `~x`, `True - x`, is deprecated for numpy.bool_ and gives an error).
