### ISSUE TITLE
[FEA] Implement all libcudf modules required by cuDF Python in pylibcudf

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#15162]
**Is your feature request related to a problem? Please describe.**
pylibcudf is intended to provide a low-level Python interface to the libcudf C++ API. cuDF's internals will ultimately be refactored to depend on pylibcudf. As a first step, we need to expose all libcudf algorithms used by cuDF Cython in pylibcudf.

**Describe the solution you'd like**
This is a tracking issue for APIs to expose in Cython. The APIs are grouped based on the pxd file exposing libcudf APIs in Cython, which roughly corresponds to namespaces in libcudf.

| Module | PRs (or assignees) | Notes |
|---|---|---|
| aggregation.pxd | #14945, #14970  | |
| binaryop.pxd | #14821 | |
| column/column.pxd | #13562 | pylibcudf Columns share ownership |
| column/column_factories.pxd | #15257 | |
| column/column_view.pxd | #13562 | pylibcudf Columns share ownership |
| concatenate.pxd | #15011 | |
| contiguous_split.pxd | #16953  | |
| copying.pxd | #13562, #14508, #14640| |
| datetime.pxd | #15916, #16776, #17143 | |
| expressions.pxd | #16056 | |
| filling.pxd | #15225 | |
| groupby.pxd | #14945 | |
| hash.pxd | #15418  | |
| interop.pxd | https://github.com/rapidsai/cudf/pull/17055 | |
| io/arrow_io_source.pxd | #16050 | |
| io/avro.pxd | #15899 | |
| io/csv.pxd | #16011 #17163 | |
| io/data_sink.pxd | | I think this is finished once we're porting the remaining IO writers. We should also delete helper utility functions in `cudf._lib` if possible (eg. `make_sink_info`) |
| io/datasource.pxd | #16050 | |
| io/json.pxd | #15952 #15966 | |
| io/orc.pxd | #16042 #17310 | |
| io/orc_metadata.pxd | #16042 | |
| io/parquet.pxd | #16078  #17245 https://github.com/rapidsai/cudf/pull/17491 https://github.com/rapidsai/cudf/pull/17506| |
| io/text.pxd | #17232 | |
| io/timezone.pxd | #16771 | |
| io/types.pxd | | |
| join.pxd | #14972 | |
| labeling.pxd | #16761 | |
| lists/combine.pxd | #15928 | |
| lists/contains.pxd | #15981 | |
| lists/count_elements.pxd | #16072 | |
| lists/explode.pxd | #15011 | |
| lists/extract.pxd | #16071  | |
| lists/gather.pxd | #16170 | |
| lists/lists_column_view.pxd | #16175 | |
| lists/sorting.pxd | #16179 | |
| lists/stream_compaction.pxd | #16184 | |
| lists/reverse.pxd | #16185 | |
| merge.pxd | #15011 | |
| null_mask.pxd | #15908 | |
| nvtext/byte_pair_encode.pxd | #17101 | |
| nvtext/edit_distance.pxd | #16957 | |
| nvtext/generate_ngrams.pxd | #17006 | |
| nvtext/jaccard.pxd | #17007 | |
| nvtext/minhash.pxd | #17021 | |
| nvtext/ngrams_tokenize.pxd | #17070 | |
| nvtext/normalize.pxd | #17072 | |
| nvtext/replace.pxd | #17084 | |
| nvtext/stemmer.pxd | #17085 | |
| nvtext/subword_tokenize.pxd | #17096 | |
| nvtext/tokenize.pxd | #17100 | |
| partitioning.pxd | #16781 | |
| quantiles.pxd | #15874 | |
| reduce.pxd | #14970 | |
| replace.pxd | #15005 | |
| reshape.pxd | #15827| sans byte_cast which is only used by cpp/java |
| rolling.pxd | #14982 | |
| round.pxd | #15863 | |
| scalar/scalar.pxd | #14133 | |
| search.pxd | #15166 #17271 | |
| sorting.pxd | #15011 | |
| stream_compaction.pxd | #15011 | |
| strings/convert/convert_booleans.pxd | #16971 | |
| strings/convert/convert_datetime.pxd | #16971 | |
| strings/convert/convert_durations.pxd | https://github.com/rapidsai/cudf/pull/16982 | |
| strings/convert/convert_fixed_point.pxd | https://github.com/rapidsai/cudf/pull/16984 | |
| strings/convert/convert_floats.pxd | https://github.com/rapidsai/cudf/pull/16990 | |
| strings/convert/convert_integers.pxd | https://github.com/rapidsai/cudf/pull/16991 #17270 | |
| strings/convert/convert_ipv4.pxd | https://github.com/rapidsai/cudf/pull/16994 | |
| strings/convert/convert_lists.pxd | https://github.com/rapidsai/cudf/pull/16997 | |
| strings/convert/convert_urls.pxd | https://github.com/rapidsai/cudf/pull/17003 | |
| strings/split/partition.pxd | https://github.com/rapidsai/cudf/pull/16940 | |
| strings/split/split.pxd | https://github.com/rapidsai/cudf/pull/16940 | |
| strings/attributes.pxd | https://github.com/rapidsai/cudf/pull/16785 | |
| strings/capitalize.pxd | https://github.com/rapidsai/cudf/pull/15503 | |
| strings/case.pxd |https://github.com/rapidsai/cudf/pull/15489 | |
| strings/char_types.pxd | https://github.com/rapidsai/cudf/pull/16788 | |
| strings/combine.pxd | https://github.com/rapidsai/cudf/pull/16790 | |
| strings/contains.pxd | https://github.com/rapidsai/cudf/pull/16814 | |
| strings/extract.pxd | https://github.com/rapidsai/cudf/pull/16823 | |
| strings/find.pxd | https://github.com/rapidsai/cudf/pull/15604 | |
| strings/find_multiple.pxd | https://github.com/rapidsai/cudf/pull/16920 | |
| strings/findall.pxd | https://github.com/rapidsai/cudf/pull/16825 | |
| strings/json.pxd | https://github.com/rapidsai/cudf/pull/17025 | |
| strings/padding.pxd | https://github.com/rapidsai/cudf/pull/16833 | |
| strings/regex_flags.pxd | https://github.com/rapidsai/cudf/pull/15880 | |
| strings/regex_program.pxd | https://github.com/rapidsai/cudf/pull/15880 | |
| strings/repeat.pxd | https://github.com/rapidsai/cudf/pull/16834 | |
| strings/replace.pxd | #15839 | |
| strings/replace_re.pxd | https://github.com/rapidsai/cudf/pull/17023 | |
| strings/side_type.pxd | https://github.com/rapidsai/cudf/pull/16833 | |
| strings/strip.pxd | https://github.com/rapidsai/cudf/pull/16833 | |
| strings/substring.pxd | https://github.com/rapidsai/cudf/pull/15988 | |
| strings/translate.pxd | https://github.com/rapidsai/cudf/pull/16934 | |
| strings/wrap.pxd | https://github.com/rapidsai/cudf/pull/16935 | |
| strings_udf.pxd | https://github.com/rapidsai/cudf/pull/17107 | We decided not to include `strings_udf` in pylibcudf because (if we did) the C++ we'd be creating bindings for in https://github.com/rapidsai/cudf/tree/branch-24.12/python/cudf/udf_cpp  is not a part of the libcudf API. |
| table/table.pxd | #13562 | Tables share column ownership in pylibcudf |
| table/table_view.pxd | #13562 | Tables share column ownership in pylibcudf |
| transform.pxd | #16760 | |
| transpose.pxd | #16749| |
| types.pxd | #13562 | More types added as needed in other PRs |
| unary.pxd | #14850 | |
| utilities/span.pxd | #17021 | |
| wrappers/decimals.pxd | https://github.com/rapidsai/cudf/pull/17048 | |
| wrappers/durations.pxd | https://github.com/rapidsai/cudf/pull/17010 | |
| wrappers/timestamps.pxd | https://github.com/rapidsai/cudf/pull/17010 | |

**Comment by lithomas1** [comment]
I'm planning on doing the string modify stuff
https://docs.rapids.ai/api/cudf/nightly/libcudf_docs/api_docs/strings_modify/

starting with padding.

**Comment by vyasr** [comment]
Closing as complete. pylibcudf has basically all of the algorithms that cudf, cudf-polars, and cudf.pandas need now. The remaining work will be at a higher level of pylibcudf to ensure it can be used directly.
