### ISSUE TITLE
[FEA] Allow column indexing by `cudf.Index`

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#15179]
It would be nice if cudf did not raise an `"Index object is not iterable"` error when a `cudf.Index` object was used to perform column projection. I certainly understand the motivation for warning the user when they try to iterate over a device buffer. However, for the case of column projection, we are not really "helping" to user avoid inefficient code. The column index is not likely to be large, and there is little-to-no harm in automatically converting to host memory under the hood (without raising).

Example of logic used in dask-expr that works for pandas, but not cudf:

```python
import cudf

df = cudf.DataFrame({"a": [1, 2], "b": ["dog", "cat"]})

# Use cudf or pandas to compute an Index of relevant columns
# for a larger (parallel) `var` operation
relevent_columns = df.var(numeric_only=True).index

# Perform a column projection using that index
df[relevent_columns]
```

**Additional context**
This is not a high priority, but does require a workaround in dask-cudf at the moment.

**Comment by wence-** [comment]
TBH, despite the possible performance pitfalls, I think we should just enable this via an all-at-once device-to-host transfer and then iteration over the pandas object:
```
def __iter__(self):
    return iter(self.to_pandas())
```

This style of row-wise iteration is an anti-pattern for dataframes with many rows in pandas _anyway_, so the places where it likely shows up are probably not problematic in practice.

**Comment by vyasr** [comment]
I'm going to close this in favor of tracking in #14935.
