### ISSUE TITLE
[BUG] GDF_BOOL8 is not tested for all algorithms

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1518]
**Describe the bug**
The new GDF_BOOL8 data type was added to libcudf in PR #1142, but adding gtests (and pytests) and fixing failures for all algorithms using that type has not been finished.

The following do not test  `GDF_BOOL8` / `cudf::bool8`:

- [x] Device Atomics
- [x] unary operations
- [x] binary operations, 
- [x] ~order_by~ sorted_order/is_sorted/sort_by_key
- [x] group_by
- [ ] join
- [x] hashing
- [x] replace
- [x] quantiles
- [ ] CSV, Parquet, and any other file loaders
- [x] other

Note that testing GDF_BOOL8 may not make sense for all of these. But it should at least be considered. Pytests for these should also be considered, though may not be necessary since Python bool was already supported -- it was implemented using int8.

**Comment by harrism** [comment]
While #3581 will remove the bool8 type, I believe we still need to add testing for `bool` type columns to the algorithms listed above (and probably others that didn't exist a year ago when I filed this). @codereport FYI.

**Comment by harrism** [comment]
After the libcudf++ port, join tests and binops tests are the only two (other than file readers) that do not use  type_lists.hpp to define the sets of types to test.  I'm not sure why this is.

**Comment by harrism** [comment]
@devavret can you comment on the binops tests? Do they sufficiently test all types?
@jrhemstad who knows the join tests best and answer the same question for those?

I would like to close this issue out if possible.

For cuIO, I think the majority of testing is done with pytests, currently.

**Comment by devavret** [comment]
Binary ops don't test bool as input types. They do test it for output types of logical and comparison operations.

**Comment by harrism** [comment]
Is not testing bool inputs sufficient? :)

**Comment by devavret** [comment]
It's not. But as with other binop tests, we shouldn't add a blanket test for all combinations involving a bool or else we'll take a long time to compile tests. Need to figure out what combinations need to be tested.

**Comment by harrism** [comment]
I would think the operators which return a Boolean and those which make sense to apply to Boolean inputs. 

```
   EQUAL,                 ///< operator ==
   NOT_EQUAL,             ///< operator !=
   LESS,                  ///< operator <
   GREATER,               ///< operator >
   LESS_EQUAL,            ///< operator <=
   GREATER_EQUAL,         ///< operator >=
   LOGICAL_AND,           ///< operator &&
   LOGICAL_OR,            ///< operator ||
```

**Comment by jrhemstad** [comment]
> join tests and binops tests are the only two (other than file readers) that do not use type_lists.hpp to define the sets of types to test. I'm not sure why this is.

Join should use the type lists and include testing for `bool`s. There's nothing special about join that would preclude testing with bool.

**Comment by harrism** [comment]
Join appears to only test ints.

**Comment by harrism** [comment]
@karthikeyann please make sure binops is sufficiently covered for GDF_BOOL8 tests under your refactor.

**Comment by GregoryKimball** [comment]
For file loaders we have coverage for bool in [fuzz testing](https://github.com/rapidsai/cudf/tree/branch-22.08/python/cudf/cudf/_fuzz_testing). For join we have coverage for bool in [cross_join_tests](https://github.com/rapidsai/cudf/blob/ff63c0a745382d79eaf0ae45931e7167d9763b88/cpp/tests/join/cross_join_tests.cpp#L36) from #5327
