### ISSUE TITLE
[FEA] Provide type stubs for pylibcudf package

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#15190]
**Is your feature request related to a problem? Please describe.**

As we build out the pylibcudf API, having type stubs for lsp and type-checking integration becomes increasingly useful.

**Describe the solution you'd like**

Provide type stubs (with docstrings) so that lsp/type-checker integration works.

We don't want to replicate docstrings in more than one place, I don't know if the right place for them is the type stub file.

**Describe alternatives you've considered**

Having the relevant pyx file open in an editor at the same time.

**Additional context**

There are a number of half-working auto-generation engines for stubs, but none of them seem to work that well, so we should probably just do this by hand.

**Comment by vyasr** [comment]
We may want to look into https://github.com/cython/cython/pull/3818. As @wence- mentioned, many of the existing autogenerators ([listed in the linked Cython issue](https://github.com/cython/cython/pull/3818#issuecomment-1666687625)) aren't great, but getting something baked directly into Cython with all of the information Cython already has could in principle work much better.
