### ISSUE TITLE
[BUG] TableTest.testChunkedPackTwoPasses is breaking CI

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#15209]
We have gotten reports of `TableTest.testChunkedPackTwoPasses` breaking CI and we need to investigate what exactly is going on. @nvdbaranec did work to isolate the issue and has gotten it down to this test by itself breaking, if it's changed slightly to initialize part of the column that is getting chunked packed.

Our plan is to disable it for now and work on a permanent fix. The test has been running for a while and it is unclear why it's failing now.

**Comment by davidwendt** [comment]
Should you mark #15210 as do-not-merge then? Or maybe just close it.

**Comment by abellina** [comment]
> Should you mark #15210 as do-not-merge then? Or maybe just close it.

I didn’t want to have everyone wait for CI, so I was going to let that merge and post a fix Monday. Sorry that my comment wasn’t clear.

**Comment by ttnghia** [comment]
The PR #15210 couldn't be merged anyway, before Monday. So I think it is no longer needed, you should better close it and post your fix instead.

**Comment by abellina** [comment]
This was finally fixed by: https://github.com/rapidsai/cudf/pull/15220.
