### ISSUE TITLE
[BUG] Prescribed Databricks init script is failing as of 20240306

### ISSUE THREAD

**Issue by joe-altana** [rapidsai/cudf#15249]
**Describe the bug**
The Databricks init script prescribed [here](https://docs.rapids.ai/deployment/stable/platforms/databricks/) was working for me for some time, and suddenly started failing yesterday.

**Steps/Code to reproduce bug**
Follow the directions in that linked [page](https://docs.rapids.ai/deployment/stable/platforms/databricks/), see init script failure when you try to start the cluster (details below).

**Expected behavior**
Init script finishes successfully, as it did before yesterday.

**Environment overview (please complete the following information)**
Databricks 13.3ML on a single g5.xlarge node.

**Environment details**
*Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details*

Not sure how I'd do that from Databricks, and in any event I can't start the cluster.

**Additional context**
Here is the actual error:

```
Failed to run via FUSE mount, retrying with pre-signed URLs
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sl3eiz50/ptxcompiler-cu11_3a492d72a338405d91fd68ee51d48067/setup.py", line 90, in <module>
          raise RuntimeError("Bad params")
      RuntimeError: Bad params
      [end of output]
```

I suspect it is not a coincidence that ptxcompiler-cu11 dropped a new version yesterday (20240306). Perhaps its version is not pinned in whatever library depends on it.

**Comment by joe-altana** [comment]
I note that the dependency on ptxcompiler-cu11 is not version pinned. https://github.com/rapidsai/cudf/blob/753bf3e525e15c970fc7dc7ce333d96035c4cc55/dependencies.yaml#L557

**Comment by joe-altana** [comment]
Workaround: add `pip install --extra-index-url=https://pypi.nvidia.com ptxcompiler-cu11==0.7.0.post1` to the init script before the main `pip install` there, and that main pip install will respect that version and not try to upgrade it.

**Comment by wence-** [comment]
Hmm, the provided init.sh script:

```
#!/bin/bash
set -e

# Install RAPIDS libraries
pip install --extra-index-url=https://pypi.nvidia.com \
    "cudf-cu11" \
    "cuml-cu11" \
    "dask-cudf-cu11" \
    "dask-cuda==24.02"
```

Specifies `--extra-index-url`, so any ptxcompiler-cu11 package on pypi.nvidia.com _should_ take precedence. Unless, I suppose the version on pypi.org is newer. It may be that you were just unlucky with the timing, if I try creating this environment today, it completes successfully (although I am doing so locally rather than on databricks). So perhaps in the intervening few days the pypi.nvidia.com ptxcompiler packages were _also_ updated, and you just unluckily tried installing in a window in which they were not.

Could you please try installing again to see if the problem persists?

**Comment by jacobtomlinson** [comment]
Could you also share your Python version?

**Comment by joe-altana** [comment]
Confirmed that it now works without explicitly installing the previous version of ptxcompiler first.

Bad luck timing on my part, I guess.
