### ISSUE TITLE
[FEA] White space normalization in JSON arrays

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#15251]
**Is your feature request related to a problem? Please describe.**
I am putting this down as a new feature because I think it is a missed requirement as a part of https://github.com/rapidsai/cudf/pull/15033

I really would love it if we also could normalize the whitespace within arrays, not just objects.

```
{"data": [0,5,6,7 ,8 , 9 ]}
```

should become
```
{"data":[0,5,6,7,8,9]}
```

Similarly we should be able to deal with strings and we remove all of the white space around quoted strings, but not in them.

```
{"data": ["0"," 5","6 ","7" ,"8" , "9" ]}
```

should become
```
{"data":["0"," 5","6 ","7","8","9"]}
```
And ideally this should nest

```
{"data": [{"a": "A"}, {"b": "B"}]}
```
would become

```
{"data":[{"a":"A"},{"b":"B"}]}
```

**Comment by shrshi** [comment]
Thank you for the explanation and the examples, @revans2 
All of the cases mentioned are already being parsed correctly with the current whitespace normalizer i.e. it can handle whitespace in nested lists and around quoted strings.

**Comment by revans2** [comment]
Okay then I will do some more debugging and see why I am not seeing the results coming back properly.

**Comment by revans2** [comment]
You are correct it was a bug in my test
