### ISSUE TITLE
[QST] Cannot import `cudf`

### ISSUE THREAD

**Issue by blue-cat-whale** [rapidsai/cudf#15268]
I've downloaded `cudf==24.4.0a` on my RHEL 8.9, but when I tried `import cudf` like [this tutorial](https://docs.rapids.ai/api/cudf/stable/user_guide/10min/), the python console just crushed.
How can I fix it?
![fig](https://github.com/rapidsai/cudf/assets/162076794/248986fc-b396-429c-adef-372ad15985d8)

**Comment by wence-** [comment]
Hmm, can you show the output of `nvidia-smi` on this system please?

**Comment by blue-cat-whale** [comment]
I installed CUDA12.4 locally
```
[root@localhost code]# whereis nvcc
nvcc: /usr/local/cuda-12.4/bin/nvcc /usr/local/cuda-12.4/bin/nvcc.profile
```
But that cloud GPU has multiple CUDA installed, I'm not sure which one is active.
```
[root@localhost code]# ls /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda* -d
/opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.0  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.3  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.6  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-12.0
/opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.1  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.4  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.7  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-12.1
/opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.2  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.5  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-11.8  /opt/orion/orion_runtime/gpu/cuda/current/orion-cuda-12.2
```

![fig1](https://github.com/rapidsai/cudf/assets/162076794/985fdb4d-1f0f-4dd3-8fd5-11f06d833389)
![fig2](https://github.com/rapidsai/cudf/assets/162076794/4a4a0500-c233-49f6-915d-8295b2fd4007)


I'm an end-user and I don't know how this cloud GPU is set up on the server side. This is how I set up it as an end user.
```
wget http://<private_url>/dev/rpm/orionx-cuda-4.2.0-1.all.rpm
wget http://<private_url>/dev/rpm/orionx-engine-4.2.0- 1.all.rpm
wget http://<private_url>/dev/rpm/orionx-runtime-4.2.0- 1.all.rpm


rpm -i ./orionx-engine-4.2.0-1.all.rpm
rpm -i ./orionx-cuda-4.2.0-1.all.rpm
rpm -i ./orionx-runtime-4.2.0-1.all.rpm


systemctl start oriond


export ORION_CLIENT_ID=client-id
export ORION_VGPU=1
export ORION_GMEM=10000
export ORION_RATIO=100
export ORION_DEVICE_ENABLE=1
export ORION_RESERVED=0
export LD_LIBRARY_PATH=/opt/orion/orion_runtime/gpu/cuda/current   
```

**Comment by bdice** [comment]
If you are seeing `nvidia-smi` produce `CUDA Version: N/A`, that's not a good sign. I'm not sure what that means, but it could be an issue with your drivers? I would first try compiling and a running a basic CUDA program. Something like [this hello world example](https://cuda-tutorial.readthedocs.io/en/latest/tutorials/tutorial01/). I also recommmend reaching out to your cloud provider for support.

**Comment by vyasr** [comment]
Closing as stale. Please reopen if needed.
