### ISSUE TITLE
[FEA] Support casting of LIST type to STRING in JSON

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#15278]
**Is your feature request related to a problem? Please describe.**

This is a follow on issue for https://github.com/rapidsai/cudf/pull/14936#discussion_r1516854731

Really we just want to be able to request that a column or child column, be returned as a string and it works, even if the data is a nested type.

**Comment by GregoryKimball** [comment]
Hello @revans2, would you please share a bit about the case where a list type is coerced to string? I understand the map type case, but why would you want this for the top-level list rather than only for its child values?

**Comment by revans2** [comment]
@GregoryKimball Spark allows anything to be coerced into a string, if the user asks for it.  Also Spark has requirements to treat quoted and unquoted strings differently for essentially all data types, so the schema we pass to the JSON parser has all strings at the leaf nodes. So this can end up being a very common problem, and we have no way to detect it and fall back to the CPU because the issue is in the data, not in anything we have access to at planning time.
