### ISSUE TITLE
OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/librmm.so': libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nagamanikandank** [rapidsai/cudf#1528]
I am getting an error `OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/librmm.so': libcuda.so.1: cannot open shared object file: No such file or directory` when I `import cudf` in my code.

These are the steps I followed

1. Create a container using `nvidia/cuda:10.0-cudnn7-devel` 

2. Installed `Python 3.6` and `pip` in that container.

3. Installed cudf using following two commands
`python3.6 -m pip install cudf-cuda92==0.6`
`python3.6 -m pip install cudf-cuda100`

4. Set the following environment variables
`export PATH=$PATH:/usr/local/cuda-10.0/bin`
`export PATH=$PATH:/usr/local/cuda-10.0/lib64`
`export PATH=$PATH:/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so`
`export PATH=$PATH:/usr/local/cuda-10.0/nvvm/libdevice`
`export PATH=$PATH:/usr/local/lib/python3.6/dist-packages`
`export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:/usr/local/lib/python3.6/dist-packages`
`export NUMBAPRO_NVVM=/usr/local/cuda-10.0/nvvm/lib64/libnvvm.so`
`export NUMBAPRO_LIBDEVICE=/usr/local/cuda-10.0/nvvm/libdevice`
`export CUDADIR=/usr/local/cuda-10.0`

##### NVIDIA GPU Details
Tesla V100-SXM2

I don't have `conda` on the container, so I have to use `pip`. `conda tool kit` comes with the `nvidia/cuda:10.0-cudnn7-devel` image . I am not sure what I am missing.

Attaching the full error below

`Python 3.6.7 (default, Oct 22 2018, 11:32:17)`
`[GCC 8.2.0] on linux`
`Type "help", "copyright", "credits" or "license" for more information.`
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/cudf/__init__.py", line 3, in <module>
    from cudf import dataframe
  File "/usr/local/lib/python3.6/dist-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/usr/local/lib/python3.6/dist-packages/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
  File "/usr/local/lib/python3.6/dist-packages/librmm_cffi/__init__.py", line 50, in <module>
    librmm_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library '/usr/local/lib/python3.6/dist-packages/librmm.so': libcuda.so.1: cannot open shared object file: No such file or directory

**Comment by ayushdg** [comment]
@nagamanikandank Could you share the command you use to start the docker container?

**Comment by nagamanikandank** [comment]
@ayushdg . This is the command I used to start the container
`nvidia-docker run -i -t --name TestRapids nvidia/cuda:10.0-cudnn7-devel`

**Comment by kkraus14** [comment]
Closing as this was related to pip which is no longer supported.
