### ISSUE TITLE
Cannot import cudf

### ISSUE THREAD

**Issue by sshah1502** [rapidsai/cudf#15292]
**Describe the bug**
ImportError: cannot import name 'no_default' from 'cudf.api.extensions'

while import cudf

**Comment by bdice** [comment]
@sshah1502 Hi, can you share what version of cuDF you are using and the installation methods you used? This is directly imported from `pandas`, so it's possible you have an incompatible pandas version installed. https://github.com/rapidsai/cudf/blob/33a201d08f518831b612aced8f4be1054a6df2fb/python/cudf/cudf/api/extensions/__init__.py#L3

**Comment by vyasr** [comment]
Closing as stale. Please reopen if needed.
