### ISSUE TITLE
[FEA] Report the number of rows read per file in libcudf's Parquet reader 

### ISSUE THREAD

**Issue by gaohao95** [rapidsai/cudf#15389]
**Is your feature request related to a problem? Please describe.**
I wish libcudf's parquet reader reports the number of rows read per file.

Consider the following example, 
```c++
  std::vector<std::string> file_paths;  // defined elsewhere
  std::vector<std::string> column_names;  // defined elsewhere

  auto source  = cudf::io::source_info(file_paths);
  auto options = cudf::io::parquet_reader_options::builder(source);
  options.columns(column_names);
  auto result = cudf::io::read_parquet(options);
```

Here, `result` is of type [`table_with_metadata`](https://github.com/rapidsai/cudf/blob/branch-24.02/cpp/include/cudf/io/types.hpp#L249), but the metadata doesn't contain the number of rows read from each file. I wish libcudf can add this functionality.

**Describe the solution you'd like**
Report the number of rows read from each file in `table_with_metadata`.

**Describe alternatives you've considered**
I have tried `cudf::io::read_parquet_metadata` out-of-band, like the following snippet.

```c++
  std::vector<cudf::size_type> rows_per_file;
  rows_per_file.reserve(file_paths.size());

  for (auto const& file_path : file_paths) {
    auto file_source = cudf::io::source_info(file_path);
    auto metadata    = cudf::io::read_parquet_metadata(file_source);
    rows_per_file.push_back(metadata.num_rows());
  }
  result.rows_per_file = std::move(rows_per_file);
```

But this has nontrivial overhead in my use case. I believe we can get it for free as part of the Parquet reading process, since the Parquet reader needs to decode the file footers anyway.

**Comment by mhaseeb123** [comment]
Hi @gaohao95, thank you for reporting this issue. I will be looking into it promptly. To get started, can you please provide some more information on the use case / application of the `num_rows_per_file` information. Second, would you like the number of rows per file reported with or without AST filter (row selection) considered?

In the former case, we can also return a vector containing the number of rows per file (along with other metadata like the sum of rows from all files, number of cols etc.) from `cudf::io::read_parquet_metadata` API.

**Comment by gaohao95** [comment]
The use case is to load [Hive-partitioned dataset](https://duckdb.org/docs/data/partitioning/hive_partitioning) efficiently. To reconstruct the partition key columns, we need to know how many rows are loaded from each file.

I currently don't use the AST filter. If I were, I wish the reported number of rows per file is the actual number of rows in the result table, so it should be after the filter.

> In the former case, we can also return a vector containing the number of rows per file (along with other metadata like the sum of rows from all files, number of cols etc.) from cudf::io::read_parquet_metadata API.

I'm hoping to avoid this, because it requires us to open/close the file descriptors and decode the Parquet header twice.

**Comment by mhaseeb123** [comment]
Hi @gaohao95, I did some investigation on the issue and I think we can report the number of rows read per file when AST filter (row selection) is not being used for both normal and chunked parquet reader. Would this work for you?

The reason to not report the number of rows per file when row selection is being used is that the filters are applied at the very end after reading the table from parquet file and doing so at this stage will introduce significant processing overheads.

**Comment by gaohao95** [comment]
> I think we can report the number of rows read per file when AST filter (row selection) is not being used. Would this work for you?

Works for my use case. Thank you!
