### ISSUE TITLE
[BUG] json_column.cu (possibly others) appears to have a lot of async synchronization issues

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#15390]
**Describe the bug**
I have been trying to debug an issue that shows up when trying to use the JSON parser through java.

https://github.com/NVIDIA/spark-rapids/issues/10633

I am still debugging exactly what is happening there, but when looking through the code it is clear that there are a lot of synchronization issues when copying data from the GPU to the host. I am not 100% sure if any of these are actually the cause of the problem. I think they are probably not an issue most of the time as the memory being copied to is pageable memory. This is not guaranteed to make the async copies synchronous, but a lot of the time it is.

Here are a few examples of places that I have seen problems.

https://github.com/rapidsai/cudf/blob/933e32ab9ad8e5057282c48129ddbd745c538967/cpp/src/io/json/json_column.cu#L79

In this we make a std::vector using a async memory copy, and then instantly call `print_vec` on it with no synchronization on the stream to be sure that the copy completed.

That happens effectively 5 times in this one debug function, not to mention that in many cases `input` to this function was also copied async to the host with no synchronization before this was called.

https://github.com/rapidsai/cudf/blob/933e32ab9ad8e5057282c48129ddbd745c538967/cpp/src/io/json/json_column.cu#L523
https://github.com/rapidsai/cudf/blob/933e32ab9ad8e5057282c48129ddbd745c538967/cpp/src/io/json/json_column.cu#L540

This is almost an issue, except we are saved (at least most of the time by 

https://github.com/rapidsai/cudf/blob/933e32ab9ad8e5057282c48129ddbd745c538967/cpp/src/io/json/json_column.cu#L336

Which does a sync copy to the host in between `unique_col_ids` being copied async to the host and `std::transform` reading from it. If the order of this changes at all, we could run into problems.

But that does not make this std::transform safe as 
https://github.com/rapidsai/cudf/blob/933e32ab9ad8e5057282c48129ddbd745c538967/cpp/src/io/json/json_column.cu#L538
is right above it and has not synchronization before being read by std::transform.

**Comment by karthikeyann** [comment]
Thank you @revans2 . That's a detailed analysis of all async issues in that file! I provided a fix in https://github.com/rapidsai/cudf/pull/15497
