### ISSUE TITLE
[FEA] Allow cython bindings create column view with type GDF_STRING

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1541]
**Is your feature request related to a problem? Please describe.**
Cython bindings always interpret strings as `GDF_STRING_CATEGORY` when creating column view. 

**Describe the solution you'd like**
Allow Cython bindings to create a column view for dtype `GDF_STRING`

**Additional context**
https://github.com/rapidsai/cudf/blob/branch-0.7/python/cudf/bindings/cudf_cpp.pyx#L34

**Comment by kkraus14** [comment]
Closing as this is invalidated by the libcudf++ refactor.
