### ISSUE TITLE
[BUG] Enable running `tests/series/test_arithmetic.py ` in `cudf.pandas`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#15430]
**Describe the bug**
Investigate hangs in `tests/series/test_arithmetic.py` and enable running it in `cudf.pandas` tests.

This set of tests is being ignored here: https://github.com/rapidsai/cudf/blob/aab6137c80c50eccc5007120f7140cfe6646b5e0/python/cudf/cudf/pandas/scripts/run-pandas-tests.sh#L34C10-L34C42

**Comment by mroeschke** [comment]
Closed by https://github.com/rapidsai/cudf/pull/15486/files
