### ISSUE TITLE
[FEA] Use nested type-checking in dictionary concatenate

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#15491]
Filing this issue as a piece of follow-up work on #14531. There is a piece of code where we are checking types directly against a key type. I want to refactor this so that the columns can be correctly compared to the key type if either is a nested type. This requires using `cudf::types_equal` as implemented in #14531, but the refactoring needed was too large and thus I left it out of scope for that PR.

https://github.com/rapidsai/cudf/blob/c91df106f55b68068e9f1b4cf977fbe5257ea9b3/cpp/src/dictionary/detail/concatenate.cu#L223-L224

https://github.com/rapidsai/cudf/pull/14531/files#diff-e57bb56f60427be2c2bab0e098d9c965996d0516867693372f72982ecb319cfeR223

**Comment by davidwendt** [comment]
Closed by https://github.com/rapidsai/cudf/pull/14531
