### ISSUE TITLE
[BUG] String to Double return 0.0 for very large number and vice versa

### ISSUE THREAD

**Issue by thirtiseven** [rapidsai/cudf#15508]
**Describe the bug**

`cudf::strings::detail::stod` returns `inf` for a number very close to zero, like `9.299999257686047e-0005603333574677677`, and returns `0.0` for a very large number, like `9.299999257686047e0005603333574677677`.

**Steps/Code to reproduce bug**

`cudf::strings::detail::stod` ([link](https://github.com/rapidsai/cudf/blob/888e9d5c38cb27402313681744b87462846bc405/cpp/include/cudf/strings/detail/convert/string_to_float.cuh#L36)) uses `int` to save exponent value, so it will overflow to a negative sign if input exponent is larger than INT_MAX.
For the above 1st double string, it will overflow from negative value to positive value.
For the above 2nd double string, it will overflow from positive value to negative value.
So it gets wrong results.

```cpp
  // check for exponent char
  int exp_ten  = 0;
  int exp_sign = 1;
  if (in_ptr < end) {
    char ch = *in_ptr++;
    if (ch == 'e' || ch == 'E') {
      if (in_ptr < end) {
        ch = *in_ptr;
        if (ch == '-' || ch == '+') {
          exp_sign = (ch == '-' ? -1 : 1);
          ++in_ptr;
        }
        while (in_ptr < end) {
          ch = *in_ptr++;
          if (ch < '0' || ch > '9') break;
          exp_ten = (exp_ten * 10) + (int)(ch - '0');  // Overflow here!
        }
      }
    }
  }
```

Not sure if this is intentional and matches some behavior.

`getJsonObject` in spark-rapids-jni needs this function to perform floating point number normalization, so we copied this function to spark-rapids-jni and [fixed it](https://github.com/NVIDIA/spark-rapids-jni/pull/1944). But we would like to call it from cuDF in a long term.

**Comment by res-life** [comment]
Spark test case:
```
Seq("9.299999257686047e-0005603333574677677", "1.0").toDF("s").repartition(1).selectExpr("CAST(s as double)").collect.foreach(println)
```

on CPU we get back 0.0 and 1.0
on the GPU we get back null and 1.0

For more details, refer to [link](https://github.com/NVIDIA/spark-rapids-jni/issues/1923#issuecomment-2049746861)
