### ISSUE TITLE
[FEA] Support groupby aggregations when grouped on string columns

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1552]
```
import cudf

df = cudf.DataFrame()
df['a'] = ['a']*100
df['b'] = [i for i in range(100)]

df2 = df.groupby(by=['a']).min()
```

Output
```
/cudf/dataframe/index.py", line 599, in as_index
    "Strings are not yet supported in the index"
NotImplementedError: Strings are not yet supported in the index
```

**Comment by kkraus14** [comment]
> ```
> import cudf
> 
> df = cudf.DataFrame()
> df['a'] = ['a']*100
> df['b'] = [i for i in range(100)]
> 
> df2 = df.groupby(by=['a']).min()
> ```
> 
> Output
> 
> ```
> /cudf/dataframe/index.py", line 599, in as_index
>     "Strings are not yet supported in the index"
> NotImplementedError: Strings are not yet supported in the index
> ```

If you pass `as_index=False` this will work as expected, albeit without the index. String indexing is coming as part of #827.

**Comment by ayushdg** [comment]
Thanks! @kkraus14

**Comment by ayushdg** [comment]
> ```
> import cudf
> 
> df = cudf.DataFrame()
> df['a'] = ['a']*100
> df['b'] = [i for i in range(100)]
> 
> df2 = df.groupby(by=['a']).min()
> ```
> 
> 
> Output
> 
> 
> ```
> /cudf/dataframe/index.py", line 599, in as_index
>     "Strings are not yet supported in the index"
> NotImplementedError: Strings are not yet supported in the index
> ```

Can confirm that this now works with the merging of #1301
