### ISSUE TITLE
[FEA] Remove legacy JSON reader

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#15537]
The legacy JSON reader has been replaced by an "experimental" JSON reader. The experimental reader has been in production use for over a year, so we'd like to remove the legacy code.

Python's options for using the legacy reader in `cudf.read_json` [have been deprecated since 23.02](https://github.com/rapidsai/cudf/blob/74b39e213a4e6a6a1cf9f0e8d19a112fc6639214/python/cudf/cudf/io/json.py#L52-L56) and we use the "experimental" (non-legacy) reader by default in C++ (#11982). I'll file an issue describing how we can remove this in parts:

- [x] Remove legacy reader support from Python in 24.06: https://github.com/rapidsai/cudf/pull/15538
- [x] Deprecate C++ code used to enable the legacy reader in 24.06 https://github.com/rapidsai/cudf/pull/15558
- [x] Fix deprecation warnings (oops, forgot this step): https://github.com/rapidsai/cudf/pull/15563
- [x] Remove the name "experimental" from JSON test files:
  - https://github.com/rapidsai/cudf/pull/15563/files#r1570973860
  - https://github.com/rapidsai/cudf/pull/15568
- [x] Remove `host_parse_nested_json`:
  - https://github.com/rapidsai/cudf/pull/15568#issuecomment-2065369856
  - https://github.com/rapidsai/cudf/pull/15674
- [x] Remove legacy reader from C++ code in 24.08 https://github.com/rapidsai/cudf/pull/15813
- [x] Attempt to remove `concurrent_unordered_map`. libcudf's copy of this code is used in legacy JSON reader, which might be the last remaining usage. All others have been migrated to use cuCollections. See https://github.com/rapidsai/cudf/issues/12261
  - Part of https://github.com/rapidsai/cudf/pull/15813

**Comment by bdice** [comment]
I feel confident about (1) and will open a PR. @vuule -- can you weigh in on the rest of the plan here?

**Comment by vuule** [comment]
sounds good. Only one thing - we can move the new reader out of experimental earlier. IIRC this is something we missed when we switched the default reader.

**Comment by bdice** [comment]
Great. I edited the task list to move out of the `experimental` namespace in 24.06.
