### ISSUE TITLE
[BUG] cuDF JNI should use the same .clang-format as the rest of cuDF

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#15546]
**Describe the bug**
libcudf JNI has its own .clang-format file with different rules. It should not.  For example, headers are ordered in the OPPOSITE order in JNI files from the order in the rest of libcudf.

**Comment by bdice** [comment]
I opened #15557 to address this.

**Comment by ttnghia** [comment]
I indeed wanted to address this for a long time. Thanks for raising it up.
