### ISSUE TITLE
[FEA] Expose json_recovery_mode in cudf.read_json Python API, and add a column with filenames index

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#15559]
**Is your feature request related to a problem? Please describe.**
Hi!

When passing a list of files to cudf.read_json, it might fail because any of the json objects cannot be parsed because of any reason.

With the current Python API, we cannot distinguish which file failed, so it makes hard to debug those failures when dealing with thousands of jsonl files (for instance, when curating a corpus for LLM training).

Therefore, if the following functionalities would be available:
- Create a row with nulls when one of the json objects of a file canot be read, and
- Optionally, adding a column containing the index to the files passed to cudf.read_json method that indicates to which file corresponds each row in the dataset.

With those two functionalities, reading thousands of jsonl files in parallel while managing exceptions while reading them would be much efficient (reading files in a list is several times faster than reading them one after the other).

Already discussed with @vuule.

Thanks!

P.S.: NeMo Curator may benefit of this FR when performing _Exact Deduplication_, _Fuzzy Deduplication_ and _Download and Extract_ corpus features.

**Comment by GregoryKimball** [comment]
Hello @shrshi, would you please add python bindings for the JSON reader option `json_recovery_mode`?

**Comment by galipremsagar** [comment]
Sure, I'll take care of it.

**Comment by shrshi** [comment]
Thank you @galipremsagar

**Comment by miguelusque** [comment]
Thank you all! Much appreciated!
