### ISSUE TITLE
[BUG] Poor performance scaling of `str.count` with long strings

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#15567]
**Describe the bug**
During large string testing, I noticed that we have poor performance scaling of the `str.count` API with string length. 

**Steps/Code to reproduce bug**
```
df = cudf.DataFrame({'a':['abc','cdf']})
for n in [1,10,100,1000, 10000]:
    df['b'] = df['a'].str.repeat(n)
    t0 = time.time()
    _ = df['b'].str.count('a')
    t1 = time.time()
    string_length = int(df['b'].str.len().mean())
    print(f'count on string len {string_length}, took {t1-t0} seconds')
```

```
count on string len 3, took 0.0012462139129638672 seconds
count on string len 30, took 0.00027561187744140625 seconds
count on string len 300, took 0.0019071102142333984 seconds
count on string len 3000, took 0.12342023849487305 seconds
count on string len 30000, took 11.811477422714233 seconds
```

**Expected behavior**
The observed scaling is something like `O(n^2)`, but I would expect scaling more like `O(n)`. 

**Additional context**
This issue is one component of improving performance with long strings in #13048

**Comment by davidwendt** [comment]
This is a character count and not the number of bytes so resolving multi-byte characters requires some computation.
Regardless, it should be possible to compute the character count in a more parallel way for long strings.
