### ISSUE TITLE
[BUG] Unable to convert a pyarrow.Table to a cudf.pandas DataFrame

### ISSUE THREAD

**Issue by kolfild26** [rapidsai/cudf#15577]
Hi,
I'm trying to convert a pyarrow.Table to a cudf.pandas DataFrame. First, I load a cudf.pandas extension and then import pandas. Next, a pyarrow.Table has a [to_pandas()](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.to_pandas) method. What I expect is a cudf.pandas dataframe with the GPU support in result.
But It seems like a simple pandas dataframe's created instead. Here is a code.

```
%load_ext cudf.pandas
import pandas as pd
import pyarrow as pa

# assume here is a pyarrow table called pa_table

pd_table = pa_table.to_pandas(types_mapper=pd.ArrowDtype)
```
pd_table's been created successfully but when trying to run some GPU supported functions on that table it doesn't work on the GPU.  

```
%%cudf.pandas.profile                                                                                              
                                                Stats                                         
                                Total time elapsed: 35.442 seconds                           
                                0 GPU function calls in 0.000 seconds                         
                                0 CPU function calls in 0.000 seconds                          
┏━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃ Function ┃ GPU ncalls ┃ GPU cumtime ┃ GPU percall ┃ CPU ncalls ┃ CPU cumtime ┃ CPU percall ┃
┡━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
└──────────┴────────────┴──────────────┴─────────────┴──────────┴──────────────┴─────────────┘

```
Actually the profile doesn't even show where the calculations are made. Probably it is still the CPU, I'm making this assumption based on the resulting time I get when using a pure cuDF table, with no a cudf.pandas proxy.
```
...
import cudf
cudf_table = cudf.DataFrame.from_arrow(pa_table)
```
1) the convertion was very fast
2) any further calculations were very fast and the profile show it's all on the GPU.

So, I might do something wrong above. If so, please advise me how to correctly create a cudf.pandas table from a pyarrow table.
If the way I do all above is correct, this might be a problem with that pyarrow method. I totally realise that in this case it's a pyarrow team who is responsible for this functionality. But, you know, here is two roads crossing and I just started from asking here first.

**Comment by mroeschke** [comment]
Thanks for the report. This is a known issue described in https://github.com/rapidsai/cudf/issues/14521 so closing as a duplicate issue. If you have any additional feedback happy to have your thoughts there!
