### ISSUE TITLE
[BUG] Calls to ArrowArrayFinishBuilding in gtests FromArrowDeviceTest DateTimeTable/DurationsTest fail validation

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#15597]
The call to `ArrowArrayFinishBuilding` with `NANOARROW_VALIDATION_LEVEL_MINIMAL` reports a validation error 
```
Expected int64 array buffer 1 to have size >= 48 bytes but found buffer with 0 bytes
```
This occurs in the `FromArrowDeviceTest.DateTimeTable` and `FromArrowDeviceTestDurationsTest.DurationTable` gtests in `from_arrow_device_test.cpp`

Found while working on #15596 

Workaround is to change to `NANOARROW_VALIDATION_LEVEL_NONE` for now.

**Comment by davidwendt** [comment]
@zeroshade I'm not sure if this a problem with the test or something deeper.

**Comment by zeroshade** [comment]
It likely means I forgot to set the buffer.size on something in the test, i'll double check it

**Comment by zeroshade** [comment]
@davidwendt The solution is to add the following lines:

at line 118 of `from_arrow_device_test.cpp` insert the line:

`ArrowArrayBuffer(input_array->children[0], 1)->size_bytes = sizeof(int64_t) * data->size();`

At line 174 insert:

`ArrowArrayBuffer(input_array->children[0], 1)->size_bytes = sizeof(T) * data.size();`

that should fix the validation issues
