### ISSUE TITLE
[FEA] Evaluate and add support for `Frame.flags`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#15607]
**Is your feature request related to a problem? Please describe.**
We should evaluate if adding flags support in `cudf` will have a utility. From the initial pass, I don't think so, in which case we need to at least raise an error that this feature is not supported and properly have the fall-back mechanism implemented in `cudf.pandas`.

**Comment by mroeschke** [comment]
Is this similar to https://github.com/rapidsai/cudf/issues/15400?

**Comment by galipremsagar** [comment]
Yes, it is. Closing.
