### ISSUE TITLE
[QST] Recusively Generating AST Expressions (C++ libcudf)

### ISSUE THREAD

**Issue by shriramch** [rapidsai/cudf#15653]
I would like to implement a function that can generate AST expressions, for example, by recursively converting a different expression class, such as an Apache Arrow `arrow::compute::expression` [object](https://github.com/apache/arrow/blob/main/cpp/src/arrow/compute/expression.h), to a `cudf::ast::expression` [object](https://github.com/rapidsai/cudf/blob/branch-24.06/cpp/include/cudf/ast/expressions.hpp). 

Is this even possible? libcudf's AST expression classes only accept references that are owned by the caller function; this is a problem since we can not recurse anymore. Is there any way to do this, to implement functions that can generate AST expressions instead of hardcoding expressions in a caller?

**Comment by bdice** [comment]
For an example of constructing an expression tree, see this benchmark: https://github.com/rapidsai/cudf/blob/23bb2ed156d164b59e608e7e791c74db5cb4bce8/cpp/benchmarks/ast/transform.cpp#L65-L87

**Comment by vyasr** [comment]
FWIW we'd also be OK with changing the current model, see #10744. If you would like to make that change, a PR is welcome!

**Comment by shriramch** [comment]
@bdice Thank you, this approach worked.

**Comment by shriramch** [comment]
@vyasr Sure, I'd like to try this.

**Comment by vyasr** [comment]
@shriramch OK great! Feel free to post here if you need help in getting a development environment set up for cudf!

**Comment by shriramch** [comment]
@vyasr Is it possible to get a remote development environment? Unfortunately I can't do this on my current PC.

**Comment by vyasr** [comment]
Would you be able to spin up an EC2 or GCP instance for this? I think getting access on one of the cloud services would be the easiest. [Paperspace](https://www.paperspace.com/) is another good option.

**Comment by bdice** [comment]
Closing as the original question about managing AST expressions was answered.
