### ISSUE TITLE
[DOC] Clarification on exceptions, return codes, and recoverability

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1566]
Not sure if this is a doc issue, a design bug, or what exactly.  I am trying to add java bindings to cudf and part of this is to translate the various errors/exceptions that can be returned or thrown into corresponding java exceptions.

I started out with exceptions that follow the various error codes that can be returned. 
`cudaError_t` for cuda errors, `rmmError_t` for rmm errors, and `gdf_error` for cudf specific issues.  Even when we got back a `RMM_ERROR_CUDA_ERROR` or a `GDF_CUDA_ERROR` it is simple enough to call `cudaGetLastError` to get/clear the cuda error, then create the proper java exception and throw it.

With the new C++ code, which I know is still a work in process, there does not appear to be as much consistency on the exceptions being thrown, and harder it is even harder to recover consistently from these errors.

`joining.h` can throw a `cuda_exception_t` sometimes peeking at the last error and some times not.
`ipc.cu` can throw a `ParseError` but I think that is just internal and never gets out to the end user.
`managed.cuh` and `managed_allocator.cuh` will throw `std::bad_alloc` when RMM is not able to allocate memory, except in one case where it throws an `std::runtime_error`.
`type_dispatcher.hpp` will throw a `std::runtime_error` when a string vector was passed to operations that do not support it.
all the rest of the code appears to be using `error_utils.hpp` which will throw a `cudf::logic_error` when an expectation is not met, a `cudf::cuda_error` if there are errors on a particular stream and `NDEBUG` is enabled, as the result of calling a cuda call, or whenever someone wants to call `CUDA_CHECK_LAST`, which is a lot of places.

Is the long term plan to have `std::runtime_error` and `cudf::logic_error` replace most of  `gdf_error`, and to have `cudf::cuda_error` handle returning cuda errors seen by cudf, while `std::bad_alloc` would be for rmm errors seen by cudf?  If so what is the right way to clear/recover from a `cudf::cuda_error`?  should I always call `cudaGetLastError` and throw it away just to be sure I removed it so it does not cause more exceptions in the future, or should I be more worried about other errors showing up because it is not consistent when an exception was thrown before clearing the error or not?

**Comment by kkraus14** [comment]
@harrism assigned you as this is surrounding libcudf design, feel free to deassign / reassign as you see fit.

**Comment by harrism** [comment]
I don't know that we have a long-term plan for what exceptions we will  throw. I don't see why we wouldn't want to reserve the option to throw any appropriate `std::exception`. https://en.cppreference.com/w/cpp/error/exception

As for always calling cudaGetLastError(), I think it would be OK for you to check it, but in the case of some errors you might need to take an action other than throwing it away.

**Comment by harrism** [comment]
I think we should probably clear CUDA errors when we throw a cudf::cuda_error, but we don't today. The .what() in the exception should tell you as much information as `cudaGetLastError()` will, so no need to call that.

**Comment by jrhemstad** [comment]
libcudf++ uses exceptions instead of return codes and will clear any non-sticky CUDA errors before throwing the exception.
