### ISSUE TITLE
[BUG] cudf.pandas dataframe.__repr__ slow in jupyterlab for large datasets

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cudf#15747]
**Describe the bug**
Calling a dataframe.__repr__ in a notebook cell either takes very long or results in a kernel failure for large datasets. 
**Steps/Code to reproduce bug**
In a jupyterlab environment, run this in a cell:

```python

# [cell 1]
%load_ext cudf.pandas

# [cell 2]
import pandas as pd
import numpy as np

# Define the number of rows and columns
num_rows = 25_000_000
num_columns = 12

# Create a DataFrame with random data
df = pd.DataFrame(np.random.randint(0, 100, size=(num_rows, num_columns)),
                  columns=[f'Column_{i}' for i in range(1, num_columns + 1)])


# [cell 3]
df
```
![image](https://github.com/rapidsai/cudf/assets/20476096/f496473d-369a-4fe4-a91c-950944b44c05)

**Expected behavior**
dataframe should render quickly, as is the case when working directly with cudf, or pandas

**Note**
This works as expected in a python interactive shell, or when calling `print(df)` in a notebook.

**Comment by vyasr** [comment]
cf #13297
