### ISSUE TITLE
[BUG] Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies. 

### ISSUE THREAD

**Issue by junuk861** [rapidsai/cudf#1576]
**Describe the bug**
Error message
"Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies."

could you help me figure out this issue?

**Comment by kkraus14** [comment]
If you're using the yml files that we provide for the environment you need to add `pip` as an entry. Conda made a change somewhat recently where it no longer automatically ships `pip` and you need to explicitly include it now.
