### ISSUE TITLE
[BUG] dask-cudf isin errors when passing in a list of values

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#15768]
**Describe the bug**
When calling the `isin` method on a series with the list of values results in an error. 
This used to work in 24.04 and seems to be a regression in the nightlies.

**Steps/Code to reproduce bug**
```python
ser = cudf.Series([1,2,3])
ddf = dask_cudf.from_cudf(ser,1)
ddf.isin([1,5]).head() # ERROR, TypeError: Cannot convert a integer of object type


ser.isin([1,5]) # works
```

**Expected behavior**
Returns the result
```
0     True
1    False
2    False
dtype: bool
```

**Environment overview (please complete the following information)**
 - nightly package in a docker container

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by rjzamora** [comment]
Here is a reproducer for the problematic `cudf` code that `dask.dataframe` is attempting to execute:

```python
import cudf
import numpy as np

ser = cudf.Series([1,2,3])
values = [1, 5]
values = np.fromiter(values, dtype=object)
ser.isin(values)
```

cc @galipremsagar @mroeschke - In case you know of some recent cudf changes that would make this a problem.
