### ISSUE TITLE
[FEA] Potential optimization:  Batched memset.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#15773]
Under some situations in the Parquet reader (particularly the case with tables containing many columns or deeply nested column) we burn a decent amount of time doing `cudaMemset()` operations on output buffers. A good amount of this overhead seems to stem from the fact that we're simply launching many tiny kernels.  It might be useful to have a batched/multi memset kernel that takes a list of address/sizes/values as a single input and does all the work under a single kernel launch.  Similar to the Cub multi-buffer memcpy or `contiguous_split`.

**Comment by davidwendt** [comment]
Closed by https://github.com/rapidsai/cudf/pull/16281
