### ISSUE TITLE
[FEA] implement astype on Index objects

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#1580]
There is a new failure in the dask-cudf where we're calling something like the following on a cudf dataframe and it is breaking because `RangeIndex` has no attribute, `astype`:

```python
df.index = df.index.astype(...)
```

Is this easy to add?  In this particular case the type doesn't even change, so it should be a no-op.

**Comment by mrocklin** [comment]
Not sure if it's appropriate to put this into the 0.7 release or not.  Will leave that to maintainers if possible.

**Comment by kkraus14** [comment]
> Not sure if it's appropriate to put this into the 0.7 release or not. Will leave that to maintainers if possible.

This will not make the 0.7 release unfortunately, but we can likely implement it in early 0.8.
