### ISSUE TITLE
[BUG] OOM in `has_next` and `read_chunk` of chunked parquet reader

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#15812]
**Describe the bug**
While reading a dataframe of size ~8GB  on T4(16GB), there seems to be an OOM exception when `has_next` is called.

**Steps/Code to reproduce bug**

```python
# The dataframe can be fit into memory easily:

In [1]: import pyarrow as pa

In [2]: import pandas as pd

In [3]: import cudf

In [4]: table = pa.Table.from_pandas(pd.read_parquet("lineitem.parquet"))

In [5]: gdf = cudf.DataFrame.from_arrow(table)

In [6]: gdf
Out[6]: 
          l_orderkey  l_partkey  ...  l_shipmode                                  comments
0                  1    1551894  ...       TRUCK                   egular courts above the
1                  1     673091  ...        MAIL        ly final dependencies: slyly bold 
2                  1     636998  ...     REG AIR             riously. regular, express dep
3                  1      21315  ...         AIR                   lites. fluffily even de
4                  1     240267  ...         FOB                   pending foxes. slyly re
...              ...        ...  ...         ...                                       ...
59986047    60000000     698651  ...       TRUCK                                ons. accou
59986048    60000000     224200  ...     REG AIR                     the final requests. f
59986049    60000000     118838  ...        SHIP  odolites grow quickly. slyly even waters
59986050    60000000    1294851  ...        MAIL                    ests wake blithely fur
59986051    60000000     558286  ...     REG AIR           round the regular, special theo

[59986052 rows x 16 columns]


```

nvidia-smi:

```bash
Every 0.5s: nvidia-smi                                       dt07: Wed May 22 00:19:27 2024

Wed May 22 00:19:27 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:3B:00.0 Off |                    0 |
| N/A   44C    P0              27W /  70W |   8865MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       On  | 00000000:5E:00.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      5MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla T4                       On  | 00000000:AF:00.0 Off |                    0 |
| N/A   32C    P8               9W /  70W |      5MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla T4                       On  | 00000000:D8:00.0 Off |                    0 |
| N/A   30C    P8               9W /  70W |      5MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A   1816858      C   ...0/pgali/envs/cudfdev/bin/python3.11     8860MiB |
+---------------------------------------------------------------------------------------+
```

Bug:
```python
In [1]: import cudf

In [2]: from cudf._lib.parquet import ParquetReader

In [3]: reader = ParquetReader(["lineitem.parquet"], chunk_rea
   ...: d_limit=24000000)

In [4]: reader._has_next()
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
Cell In[4], line 1
----> 1 reader._has_next()

File parquet.pyx:844, in cudf._lib.parquet.ParquetReader._has_next()

MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /nvme/0/pgali/envs/cudfdev/include/rmm/mr/device/cuda_memory_resource.hpp:60: cudaErrorMemoryAllocation out of memory


```

**Expected behavior**
We should be able to read using chunked parquet reader.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

This issue will need changes from : https://github.com/rapidsai/cudf/pull/15728

**Comment by mhaseeb123** [comment]
Looked into this but unable to reproduce the issue on my machine. The reader seems to be working fine as seen in the screenshot below.
 
<img width="1386" alt="image" src="https://github.com/rapidsai/cudf/assets/14217455/155b67b6-ead1-46a4-a506-0e134a918eb5">

**Comment by mhaseeb123** [comment]
Here is my test code. I did notice in `nvidia-smi` that we see a transient GPU memory spike of `21GiB` and it quickly goes down and saturates at around `10GiB`. I am assuming that this `21GiB` transient might be the culprit behind the OOM. It doesn't fail on my machine as my GPUs are free otherwise and can handle the transient.

```python
def test_parquet_chunked_reader_oom():
    reader = ParquetReader(["/home/coder/datasets/lineitem.parquet"], chunk_read_limit=24000000)
    while (reader._has_next()):
        chunk = reader._read_chunk()
```

**Comment by galipremsagar** [comment]
@mhaseeb123 maybe this is a GPU specific issue? Can you try on a T4?

**Comment by galipremsagar** [comment]
>  I did notice in `nvidia-smi` that we see a transient GPU memory spike of `21.4GiB` and it quickly goes down and saturates at around `10GiB`. I am assuming that this `21.4GiB` transient might be the culprit behind the OOM. 


Exactly, I did notice this too on T4 and since T4's can't handle that much amount of memory we end up with an OOM there too.

**Comment by GregoryKimball** [comment]
Thank you @mhaseeb123 and @galipremsagar for testing this. I don't believe the C++ API encounters this memory spike. @mhaseeb123 would you please check? @nvdbaranec would you please share your thoughts?

**Comment by nvdbaranec** [comment]
First question, the code I'm seeing is just read_parquet(), not the chunked reader

`In [4]: table = pa.Table.from_pandas(pd.read_parquet("lineitem.parquet"))`

The regular reader is implemented in terms of the chunked reader, but with no limits set.  Ie, infinite sizes.  So if you're just using that, OOMs are absolutely possible.

If this code is somehow using the chunked reader, note that there are two parameters:
- the output chunk limit, which limits the total size in bytes of the output file, but does nothing to control the memory usage of the decode process.
- the input chunk limit, which limits how much (temporary) memory will be used during the decoding process. 

They can be set independently, but only the input chunk limit will work to keep OOMs down.

**Comment by GregoryKimball** [comment]
Thank you @nvdbaranec, yes we are trying to use the chunked reader here in python. It looks like we might not be setting the "input chunk limit"

**Comment by nvdbaranec** [comment]
Sorry, I misread.  I thought the first block of code was where the bug was.  It is odd that the one that uses the chunked reader directly would fail. There should be no difference between the two in overall memory usage, but maybe that small chunk value specfied (24 MB) is throwing something for a loop.

**Comment by galipremsagar** [comment]
The issue has been resolved by using `pass_read_limit`, Thanks @mhaseeb123 & @nvdbaranec !
