### ISSUE TITLE
Build Error a pointer to a bound function may only be used to call the function

### ISSUE THREAD

**Issue by Msabih** [rapidsai/cudf#1584]
I am attempting to build cudf with anaconda, gcc 7, cuda 10.1, cmake 3.12. I cant install through conda as cuda 10.1 is not supported through conda packages.

 The librmm and custrings was compiled successfully however the make of cudf gives an error while building 

> Built target ERROR_TEST
> scalar_wrapper.cuh(123): error: a pointer to a bound function may only be used to call the function

Is there a way to bypass this error or solve it ?

**Comment by jrhemstad** [comment]
Aha, I see the issue. I'm struggling to understand how the code in question _ever_ worked.

```  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
    return (the_scalar.data == rhs.data &&
            the_scalar.dtype == rhs.dtype &&
            the_scalar.is_valid == rhs.is_valid);
  }```

This is comparing if two `scalar_wrapper` objects are equal. Each `scalar_wrapper` has a `gdf_scalar` member.

In the above code, `rhs` is a `scalar_wrapper` object. Yet, it's trying to reference members of the `gdf_scalar`.

The above code should be changed to:

```  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
    return (the_scalar.data == rhs.the_scalar.data &&
            the_scalar.dtype == rhs.the_scalar.dtype &&
            the_scalar.is_valid == rhs.the_scalar.is_valid);
  }```

**Comment by jrhemstad** [comment]
I'll have a PR with the fix momentarily.

**Comment by Msabih** [comment]
> Aha, I see the issue. I'm struggling to understand how the code in question _ever_ worked.
> 
> ```
>  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
>     return (the_scalar.data == rhs.data &&
>             the_scalar.dtype == rhs.dtype &&
>             the_scalar.is_valid == rhs.is_valid);
>   }
> ```
> 
> This is comparing if two `scalar_wrapper` objects are equal. Each `scalar_wrapper` has a `gdf_scalar` member.
> 
> In the above code, `rhs` is a `scalar_wrapper` object. Yet, it's trying to reference members of the `gdf_scalar`.
> 
> The above code should be changed to:
> 
> ```
>  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
>     return (the_scalar.data == rhs.the_scalar.data &&
>             the_scalar.dtype == rhs.the_scalar.dtype &&
>             the_scalar.is_valid == rhs.the_scalar.is_valid);
>   }
> ```

I tried the fix, it gave another error

error: no match for 'operator==' (operand types are 'const gdf_data' and 'const gdf_data')
     return (the_scalar.data == rhs.the_scalar.data &&

Anyways, its good that you noticed something wrong so when there is a proper fix, I will apply it asap and try to build.

**Comment by Msabih** [comment]
> Aha, I see the issue. I'm struggling to understand how the code in question _ever_ worked.
> 
> ```
>  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
>     return (the_scalar.data == rhs.data &&
>             the_scalar.dtype == rhs.dtype &&
>             the_scalar.is_valid == rhs.is_valid);
>   }
> ```
> 
> This is comparing if two `scalar_wrapper` objects are equal. Each `scalar_wrapper` has a `gdf_scalar` member.
> 
> In the above code, `rhs` is a `scalar_wrapper` object. Yet, it's trying to reference members of the `gdf_scalar`.
> 
> The above code should be changed to:
> 
> ```
>  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {
>     return (the_scalar.data == rhs.the_scalar.data &&
>             the_scalar.dtype == rhs.the_scalar.dtype &&
>             the_scalar.is_valid == rhs.the_scalar.is_valid);
>   }
> ```


This works

 bool operator==(scalar_wrapper<ScalarType> const& rhs) const {                                                                                                                                                                                                           
121     return (the_scalar.data == rhs.data &&                                                                                                                                                                                                                                 
122             the_scalar.dtype == rhs.the_scaler.dtype &&                                                                                                                                                                                                                    
123             the_scalar.is_valid == rhs.the_scalar.is_valid);                                                                                                                                                                                                               
124   }

**Comment by jrhemstad** [comment]
> ```
>  bool operator==(scalar_wrapper<ScalarType> const& rhs) const {                                                                                                                                                                                                           
>      return (the_scalar.data == rhs.data &&                                                                                                                                                                                                                                 
>              the_scalar.dtype == rhs.the_scaler.dtype &&                                                                                                                                                                                                                    
>              the_scalar.is_valid == rhs.the_scalar.is_valid);                                                                                                                                                                                                               
>    } 
> ```

This doesn't really make sense either. `rhs` doesn't have a member called `data`. Very confusing.

**Comment by jrhemstad** [comment]
@Msabih could you try https://github.com/rapidsai/cudf/pull/1586 and make sure that fixes your problem?

For whatever reason, my build won't reproduce the error you're seeing, even though it most certainly is an error.

**Comment by Msabih** [comment]
> @Msabih could you try #1586 and make sure that fixes your problem?
> 
> For whatever reason, my build won't reproduce the error you're seeing, even though it most certainly is an error.

The fix works.
