### ISSUE TITLE
[MNT] add tests for ListMethods?

### ISSUE THREAD

**Issue by raybellwaves** [rapidsai/cudf#15858]
**Is your feature request related to a problem? Please describe.**

I was working on https://github.com/rapidsai/cudf/pull/15846 and I noticed there is no equivalent pandas method for `s.list.sort_values` (https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/core/column/lists.py#L622). In the pandas compat box I would like to make a note of how to do this in pandas similar to the note that exists for `df.interleave_columns()` (https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/core/dataframe.py#L7593)

**Describe the solution you'd like**

When I added the pandas code for `interleave_columns` I grabbed it from a test file (https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/tests/test_reshape.py#L316). I was hoping to do the same for `list.sort_values` but I couldn't find a test for it. Are there tests for the ListMethods? https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/core/column/lists.py#L316 I apologize if I am looking in the wrong place. In pandas there is https://github.com/pandas-dev/pandas/blob/main/pandas/tests/series/accessors/test_list_accessor.py and I see https://github.com/rapidsai/cudf/blob/branch-24.06/python/cudf/cudf/tests/series/test_accessors.py is a place holder. 

**Describe alternatives you've considered**

I see `list.sort_values` calls `sort_lists` and that is well tested e.g. https://github.com/rapidsai/cudf/blob/branch-24.06/cpp/tests/lists/sort_lists_tests.cpp. There might be a reason if the tests for ListMethods is missing such as duplication of tests.

**Additional context**

Apologies again if I am looking in the wrong place in the repo.

**Comment by mroeschke** [comment]
Yeah the Python test organization is generally pretty monolithic right now. There are a few placeholder files that aspirationally these monolithic tests will be split into.

For list accessor tests I see some in `python/cudf/cudf/tests/test_list.py` and `python/cudf/cudf/tests/test_contains.py`

**Comment by raybellwaves** [comment]
Thanks. I found what I was looking for https://github.com/rapidsai/cudf/blob/branch-24.08/python/cudf/cudf/tests/test_list.py#L289

Closing
