### ISSUE TITLE
[FEA] Add developer/private cudf.pandas API to check for proxy objects 

### ISSUE THREAD

**Issue by mroeschke** [rapidsai/cudf#15864]
**Is your feature request related to a problem? Please describe.**
We've encountered a few scenarios where we need to know whether an object is an cudf.pandas proxy object vs an actual cudf or pandas object e.g. https://github.com/rapidsai/cuml/pull/5861#discussion_r1584001820

The classic `isinstance` does not work since proxy objects ensures this always returns `True` for the case above. Like the solution above, we're relied on checking attributes but this is not a sustainable long term solution as private attributes should be subject to change.

**Describe the solution you'd like**
Exposing the proxy type in `cudf.pandas._types.`(?) that allows developers to explicitly check if they have a proxy object

**Describe alternatives you've considered**
Checking if proxy object attributes exist

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by vyasr** [comment]
When evaluating use cases for this feature we should also be thinking about if they would be better served by improving how well the proxy object masquerades for the original. We can't make `isinstance` usable for the differentiation, but ideally calling codes wouldn't have to differentiate, so any time that they do probably indicates an area where the proxy isn't a drop-in replacement to the extent that we'd like it to be.

**Comment by Matt711** [comment]
I'm not sure if we want to go this route, but every proxy type is an instance of the same metaclass. So we could check for that.
```python
s = pd.Series([1])
assert type(type(s)) == cudf.pandas.fast_slow_proxy._FastSlowProxyMeta
```

**Comment by mroeschke** [comment]
I think a developer API that checks for `_FastSlowProxyMeta` would be good initial check.

I'm not sure if it's worth differentiating specific object types, i.e. pandas proxy objects vs numpy proxy objects, or make it fully generic by checking that metaclass. My initial feeling is checking `_FastSlowProxyMeta` would be preferable

**Comment by vyasr** [comment]
@Matt711's check should be sufficient. By definition every scenario that we're thinking of is one where the caller knows the wrapped type (either slow or fast) that they expected to get.

**Comment by Matt711** [comment]
I'll add the change for it
