### ISSUE TITLE
[DOC] add cudf to database-like ops benchmark?

### ISSUE THREAD

**Issue by raybellwaves** [rapidsai/cudf#15909]
## Report needed documentation

**Report needed documentation**

I wonder if it's worth adding cudf to the Database-like ops benchmark? https://docs.rapids.ai/api/cudf/stable/cudf_pandas/benchmarks/

Currently the benchmark just includes cudf.pandas which is a minor modification of the pandas code.

I'm curious what is the performance of pure cudf in the benchmark. It would be more of an indicator of the upper-limit of cudf.pandas performance.

**Describe the documentation you'd like**

Update the chart in https://docs.rapids.ai/api/cudf/stable/cudf_pandas/benchmarks/ to include a pure cudf solution.

**Comment by brandon-b-miller** [comment]
Hi @raybellwaves, so far we haven't done a cuDF only benchmark run to use as a direct comparison. However, we do provide some tools for determining how close to speed of light your particular workflow is. The [cudf.pandas profiler](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/usage/#understanding-performance-the-cudf-pandas-profiler) in particular can highlight areas of a workflow that are hitting a CPU side bottleneck which can negatively impact your performance. Assuming the entire query is able to execute GPU side, the `cudf.pandas` python layer itself is quite lightweight, and I wouldn't expect it to have a significant effect on performance at scale. We'd probably consider such a slowdown to be somewhat buggy behavior so if you encounter that, I'd encourage reporting it as a bug. Sorry I can't offer a better comparison!

**Comment by vyasr** [comment]
We discussed this a bit offline and came to the conclusion that there isn't much to be gained by running this with pure cudf vs cudf.pandas for the reason Brandon mentioned above: either cudf.pandas successfully executes on the GPU, in which case the overhead is minimal, or it fails, in which case we wouldn't be able to run that benchmark with cudf without modification anyway.
