### ISSUE TITLE
[BUG] Loc and iloc do not consistently match pandas

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1592]
Behavior of `iloc` and `loc` do not match pandas in a number of situations that limits users and downstream development.

Given the number of relevant issues and the likelihood that many (or all) of them will be tackled at once due to the nature of the code (though perhaps separately for iloc and loc), I'm creating this issue just to track them in a single place:

iloc
- https://github.com/rapidsai/cudf/issues/1494 (also for loc)
- https://github.com/rapidsai/cudf/issues/1459
- https://github.com/rapidsai/cudf/issues/1444

loc
- https://github.com/rapidsai/cudf/issues/1513
~- https://github.com/rapidsai/cudf/issues/1505~ (closed by #1660)
- https://github.com/rapidsai/cudf/issues/1494 (also for iloc)

**Comment by shwina** [comment]
Thanks for summarizing! Currently looking into some of this and your comments on the respective issues are very useful!

**Comment by beckernick** [comment]
The underlying issues have been resolved by #1622 . Closing.
