### ISSUE TITLE
[FEA] Support named aggregations in `df.groupby().agg()`

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#15967]
**Is your feature request related to a problem? Please describe.**
I wish cudf python supported column name keywords in `df.groupby().agg()`

[See pandas docs here](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.aggregate.html)
> Here the output has one column for each element in **kwargs. The name of the column is keyword, whereas the value determines the aggregation used to compute the values in the column.

**Describe the solution you'd like**
Let's add support for column name keywords in `df.groupby().agg()`. This should be a python-only change for API convenience. It will prevent host fallback in `cudf.pandas`

**Describe alternatives you've considered**
Instead of:
`df.groupby('a').agg(mycol=('b','sum'))`
we can say
`df.groupby('a').agg({'b': 'sum'}).rename(columns={'b': 'named_agg'})`
and renaming columns doesn't work with a list of aggregations on the same column
`df.groupby('a').agg({'b': ['sum', 'mean']}).rename(columns={???: 'sum'})`

It seems like we could write a convenience API here to capture any `kwargs` and their tuples to make new columns.

**Additional context**
Many nice pandas queries for TPC-H were published in the [fireducks-dev](https://github.com/fireducks-dev/polars-tpch/tree/fireducks/queries/pandas) repo, and the `agg` column name keywords style is common.

**Comment by NeilGeorge1** [comment]
Hi! First timer here.

I'm eager to contribute and would like to take on this issue. Could you please assign it to me?

Thanks!

**Comment by wence-** [comment]
Related request: https://github.com/rapidsai/cudf/issues/15118

**Comment by Matt711** [comment]
Hi @NeilGeorge1, thanks for your interest in this issue! I'll assign it to you now. Also, take a look at our contributing [guidelines here](https://github.com/rapidsai/cudf/blob/branch-24.08/CONTRIBUTING.md).

**Comment by NeilGeorge1** [comment]
Hi @Matt711 
Thank you for assigning me this issue. I shall look into the contributing guidelines as well

**Comment by NeilGeorge1** [comment]
Hi,

I've successfully implemented the feature as described above. However, while running pytest to verify the functionality across the project, I encountered an issue: 'module cudf is missing' , which is necessary for the tests to run properly.

Could you please provide guidance on how to resolve this? It seems that cudf should have been included or configured differently in the environment setup.

Should i manually install cudf?

Thank you for your assistance.

**Comment by wence-** [comment]
> Hi,
> 
> I've successfully implemented the feature as described above. However, while running pytest to verify the functionality across the project, I encountered an issue: 'module cudf is missing' , which is necessary for the tests to run properly.
> 
> Could you please provide guidance on how to resolve this? It seems that cudf should have been included or configured differently in the environment setup.
> 
> Should i manually install cudf?
> 
> Thank you for your assistance.

Having cloned the repo, have you built cudf? If not, that is probably your issue. The simplest (IMO) way to do this is to use the devcontainer setup in the repository and then (inside the devcontainer) run `build-cudf`.

**Comment by NeilGeorge1** [comment]
> > Hi,
> > I've successfully implemented the feature as described above. However, while running pytest to verify the functionality across the project, I encountered an issue: 'module cudf is missing' , which is necessary for the tests to run properly.
> > Could you please provide guidance on how to resolve this? It seems that cudf should have been included or configured differently in the environment setup.
> > Should i manually install cudf?
> > Thank you for your assistance.
> 
> Having cloned the repo, have you built cudf? If not, that is probably your issue. The simplest (IMO) way to do this is to use the devcontainer setup in the repository and then (inside the devcontainer) run `build-cudf`.

Oh yes I did figure that out eventually. However, I'm facing errors after running pytest related to cuDF, likely because the installed NVIDIA drivers are not able to function properly.  Since I'm using a pc **without a gpu**  is this the root of the issue?

**Comment by wence-** [comment]
> Since I'm using a pc without a gpu is this the root of the issue?

Yes, you can build cudf without a gpu, but you won't be able to run it.

Best thing to do is to push a branch and open a PR, we can then review and run things through CI.

**Comment by NeilGeorge1** [comment]
Ok thank you, I'll push the branch soon and open a PR. Looking forward to your review and CI validation.
