### ISSUE TITLE
[FEA] Add an ORC reader benchmark that uses multiple CUDA streams

### ISSUE THREAD

**Issue by zpuller** [rapidsai/cudf#15973]
**Is your feature request related to a problem? Please describe.**
This is an extension of https://github.com/rapidsai/cudf/issues/12700 to provide a benchmark for multi-stream ORC reads, which is also common in Spark-RAPIDS, similar to parquet.

**Describe the solution you'd like**
Again, similar to https://github.com/rapidsai/cudf/issues/12700, a libcudf microbenchmark that creates several host threads, each with it's own non-default CUDA stream, and then reads a large ORC dataset from host memory into a libcudf table, using the [read_orc](https://github.com/rapidsai/cudf/blob/97a746f4195b65366865a6763ce0446c30279ecf/cpp/include/cudf/io/detail/orc.hpp#L59) detail api.

**Describe alternatives you've considered**
The alternative would be to continue using Spark-RAPIDS NDS runs to track performance of libcudf's parquet reader in a multi-threaded, multi-stream use case.

**Comment by GregoryKimball** [comment]
Thank you @zpuller. This sounds like a good first issue and straightforward extension of https://github.com/rapidsai/cudf/pull/15585

**Comment by zpuller** [comment]
I'm planning to work on this btw.
