### ISSUE TITLE
[BUG]cudf get different dtype for same column in two files(files generated by machine so have same column type), which make cudf fail to concat two dataframes.

### ISSUE THREAD

**Issue by lucyzhang0106** [rapidsai/cudf#1597]
**Describe the bug**
I have hundrands of csv files generated from same program. 
When cudf read_csv, it parses one same column to different type in two files. 
which makes it fail to concatenate these two  dataframes finally. 

**Steps/Code to reproduce bug**

Example code: 
test1=cudf.read_csv('ww39.csv')
test2=cudf.read_csv('ww41.csv')
cudf.concat([test1,test2])

It returns error :    **ValueError: All series must be of same type**

When I compare two dataframe, I noticed one column in test1 and test2, cudf parses it different data types. see below:
test1[test1.columns[38:40]].dtypes
Isat_P3    P/.154/016_SITE_VALUE    float64
Isat_P3L   P/.154/016_SITE_VALUE    float64
dtype: object

test2[test2.columns[38:40]].dtypes
Isat_P3    P/.154/016_SITE_VALUE    datetime64[ms]
Isat_P3L   P/.154/016_SITE_VALUE    datetime64[ms]
dtype: object

Below is sample of data. Obviously the data type should be float.
test1 

Isat_P3    P/.154/016_SITE_VALUE
--
-1.17
-1.372
-1.273
-1.25
-1.176

test2: 

Isat_P3    P/.154/016_SITE_VALUE
--
-1.116
-1.166
-1.343
-1.365

**Expected behavior**

Same code works successfully in pandas. 
See below:

p_test1=pd.read_csv('ww39.csv')
p_test2=pd.read_csv('ww41.csv')

p_test1[p_test1.columns[38:40]].dtypes
Isat_P3    P/.154/016_SITE_VALUE    float64
Isat_P3L   P/.154/016_SITE_VALUE    float64
dtype: object

p_test2[p_test2.columns[38:40]].dtypes
Isat_P3    P/.154/016_SITE_VALUE    float64
Isat_P3L   P/.154/016_SITE_VALUE    float64
dtype: object

pd.concat([p_test1,p_test2])
it returns data
.......
2043 rows × 95 columns

**Environment details (please complete the following information):**
 - Environment location: [Docker]
 - Method of cuDF install: [ Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

docker pull rapidsai/rapidsai:cuda9.2-runtime-centos7

sudo docker run --runtime=nvidia --rm -it --privileged=true  -v /project.xxx174:/project.xxx174   -p 9000:8888 -p 8787:8787 -p 8786:8786     rapidsai/rapidsai:cuda9.2-runtime-centos7

 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**

**Comment by beckernick** [comment]
@lucyzhang0106 when I create a text file of:

```
Isat_P3    P/.154/016_SITE_VALUE
-1.116
-1.166
-1.343
-1.365
```
I see the following:
```python
df = cudf.read_csv('untitled.txt')
print(df)
print(df.dtypes)
   Isat_P3    P/.154/016_SITE_VALUE
0                            -1.116
1               -1.1660000000000001
2                            -1.343
3                            -1.365
Isat_P3    P/.154/016_SITE_VALUE    float64
dtype: object
```

Are you able to reproduce your issue (reading the data as a datetime64[ms] dtype) from just the small snippet you've shared?

**Comment by lucyzhang0106** [comment]
cat test.csv 
Isat_P3    P/.154/016_SITE_VALUE
-1.116
-1.166
-1.343
-1.365

test=cudf.read_csv('/rapids/data/test.csv')
test.dtypes
Isat_P3    P/.154/016_SITE_VALUE    float64
dtype: object

**Comment by j-ieong** [comment]
My feeling is that one of the values is giving a false positive for `datetime` during dtype detection. In the dtype code, we're checking each bucket in sequence and the `datetime` bucket is checked before `float`.

The code should be taking the majority vote of the buckets and using that as the dtype.

**Comment by mjsamoht** [comment]
It looks like with 'ww39.csv' we correctly detect that col as float, but with 'ww41.csv' the col is incorrectly detected as timestamp. 

@lucyzhang0106 can you share the two input files you used?

**Comment by mjsamoht** [comment]
I believe I figured out the problem.  The file `ww39.csv` contains numbers `1.00E+15` that we incorrectly interpret as strings.  The reason is that the function `isLikeFloat` doesn't expect `+`.

We need to allow for a `+` in the exponent, and perhaps should also allow it as first character like we do for `-`.  E.g. `+3.42` should be interpreted as a float and not a string.

**Comment by lucyzhang0106** [comment]
Hmm, I think we can change our upstream to remove those format like 1.00E+15 to bypass this problem.

**Comment by mjsamoht** [comment]
This also explains why importing into Excel or LibreOffice Calc and then saving again resolves the problem.  The number gets written back without the `+`.

But I would argue this is a valid number representation that we should handle.

**Comment by lucyzhang0106** [comment]
It will be good if Cudf can read the data correctly for sure.

From: Lucy Zhang <luzhang@nvidia.com>
Date: Thursday, May 9, 2019 at 2:11 PM
To: rapidsai/cudf <reply@reply.github.com>, rapidsai/cudf <cudf@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [rapidsai/cudf] [BUG]cudf get different dtype for same column in two files(files generated by machine so have same column type), which make cudf fail to concat two dataframes. (#1597)

Hmm, I think we can change our upstream to remove those format like 1.00E+15 to bypass this problem.

**Comment by lucyzhang0106** [comment]
But I think it’s a valid format for float expression.  It’s used very popular.

-1.97E-08

-2.12E-08

-1.50E-08

-1.88E-08

-1.08E-08
