### ISSUE TITLE
[BUG] cudf reports error when csv file is empty

### ISSUE THREAD

**Issue by lucyzhang0106** [rapidsai/cudf#1598]
**Describe the bug**
I have many files generated by program.
Few of them are empty file. File exists in the disk but the size is 5 bytes. 
When I do pandas.read_csv, the dataframe will show "empty".
But in cudf, when read_csv, it will reports error "GDFError: GDF_INVALID_API_CALL".

Although I can work around this issue by checking file size first, I think this should be fixed. 

**Steps/Code to reproduce bug**
 
testdf=cudf.read_csv('2019-ww13.csv')

---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<ipython-input-271-ef7270dc4198> in <module>
----> 1 cudf=cudf.read_csv('ww13.csv')

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0.6.1+1.g9ca9325-py3.6-linux-x86_64.egg/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, comment, na_values, keep_default_na, na_filter, prefix, index_col)
    335 
    336     # Call read_csv
--> 337     libgdf.read_csv(csv_reader)
    338 
    339     out = csv_reader.data

/conda/envs/rapids/lib/python3.6/site-packages/libgdf_cffi/wrapper.py in wrap(*args)
     25                     if errcode != self._api.GDF_SUCCESS:
     26                         errname, msg = self._get_error_msg(errcode)
---> 27                         raise GDFError(errname, msg)
     28 
     29                 wrap.__name__ = fn.__name__

GDFError: GDF_INVALID_API_CALL

**Expected behavior**

In pandas, it will read in one empty dataframe. which makes more sense and won't block normal program.  see below:

p_df=pd.read_csv('2019-ww13.csv')
p_df.head()
Empty

**Environment details (please complete the following information):**
 - Environment location: [ Docker]
 - Method of cuDF install: [Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

docker pull rapidsai/rapidsai:cuda9.2-runtime-centos7

sudo docker run --runtime=nvidia --rm -it --privileged=true  -v /project.xxx174:/project.xxx174   -p 9000:8888 -p 8787:8787 -p 8786:8786     rapidsai/rapidsai:cuda9.2-runtime-centos7

 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**

**Comment by j-ieong** [comment]
Yeah, I think we raise an exception on empty file on the latest code. It should be easier to change it to return an empty dataframe to match behavior now that we've moved to Cython and CSV reader uses RAII.

**Comment by mjsamoht** [comment]
Yes, an empty file will fail the following check.

We will need to define what an empty dataframe is.  E.g. if a file contains the header (col names) but no data, would we also return an empty dataframe?  Or only for empty files?

```
if (args->byte_range_offset >= (size_t)file_size) { 
   close(fd); 
   checkError(GDF_INVALID_API_CALL, "The byte_range offset is larger than the file size");
}

```

**Comment by vuule** [comment]
I'm not seeing the same behavior with Pandas as what you describe.
~~~~
fname = tmpdir.mkdir("gdf_csv").join("tmp_file.csv")
open(fname, 'a').close()
pd_df = pd.read_csv(fname)
~~~~
Results in the following error:
pandas.errors.EmptyDataError: No columns to parse from file

@lucyzhang0106 can you please share an example "empty" file with me? It is not clear why the behavior would be different.

**Comment by vuule** [comment]
Got a PR that modifies the reader behavior to the following:
* Output dataframe has no columns if the user does not pass both names and dtype arguments;
* Output dataframe contains empty columns with correct names and types if user passes names and dtype;
Please review and let me know if is the desired behavior.

**Comment by lucyzhang0106** [comment]
@vuule  sorry for the late response, attached is the file which we read empty in Pandas but failed in cudf.  Github doesn't support uploading of csv file. Our original file is csv file, I changed it to xlsx and uploaded. You can simply rename it to .csv after you download it. Thanks

[2019-ww13.xlsx](https://github.com/rapidsai/cudf/files/3163593/2019-ww13.xlsx)

**Comment by vuule** [comment]
Thank you for sharing the file. It is not what I expected from the description. Namely, the file contains the word 'Empty', instead of really being empty.
Because of this, Pandas parses it as having a single column named 'Empty', of type object, and no data.
With cuIO we get the following error:
"No data available for data type inference"
which is correct, as you did not pass the dtype parameter and there is no data to infer the type from (and we don't have a default column type).

The behavior is expected, and the only way to match the expectations would be to **assume a default data type when inference cannot be done** (presumably string). I don't think this is a good idea. Pandas has a good default as Object could be anything, AFAIK. String is a much worse default and I think it would lead to more surprises that improvements. 
@mjsamoht What are your thoughts on the desired behavior here?

@lucyzhang0106 Is there a reason why you can't catch the exception and continue with the execution?

**Comment by mjsamoht** [comment]
@vuule I assume we're interpreting `Empty` as the column name, correct?

It's kind of odd and somewhat arbitrary to expect the reader to interpret the single word `Empty` as an empty dataframe.  Unless this is common practice I would rather not add logic to handle this.  But I think it's good to interpret an empty file as empty dataframe.

@randerzander do you have any thoughts?

**Comment by vuule** [comment]
@mjsamoht Yes, Empty is the column name. This is the case with both cuIO and Pandas. The only difference is that Pandas has a default column type and we don't.

**Comment by mjsamoht** [comment]
Okay, I see.  I think this is a slightly different issue then.  The questions here are really:
1. If a CSV file contains only one row, should we interpret that row as the header of an otherwise empty dataframe with some default data type?
2. What should be this default data type?  String?

The returned dataframe will then not be truly empty.  It will contain `n` columns with headers plus zero data rows.

**Comment by kkraus14** [comment]
@mjsamoht @vuule was this resolved by #1169, or does that not add a default dtype when there's no data for dtype inference?

**Comment by mjsamoht** [comment]
We're now returning an empty dataframe when the input file is empty.

But we're not yet handling the case described above where the file contains only one row, which would be interpreted as header row which each column using default data type.  Do we believe this is a practical use case?

**Comment by kkraus14** [comment]
> We're now returning an empty dataframe when the input file is empty.
> 
> But we're not yet handling the case described above where the file contains only one row, which would be interpreted as header row which each column using default data type. Do we believe this is a practical use case?

Yes, there's often cases where a user has an automated workflow that writes / reads empty dataframes so we should handle that situation. I believe Pandas by default returns an `object` column, which it essentially treats as strings, if there's no data available for inference.

**Comment by mjsamoht** [comment]
> Yes, there's often cases where a user has an automated workflow that writes / reads empty dataframes so we should handle that situation. I believe Pandas by default returns an `object` column, which it essentially treats as strings, if there's no data available for inference.

Let's say we have two CSV files as follows:
**File 1:**
```
a b c d
5 4 3 2
1 2 3 4
```

**File 2:**
```
a b c d
```

For `File 1` we return a dataframe with 4 columns and 2 rows, each column of integer type.  But for 'File 2` we return an "empty" dataframe with 4 columns and 0 rows, each column of string type.

How would the user be able to combine/process these dataframes when they now have different data types?
