### ISSUE TITLE
Merge shouldn't use "type" as a keyword parameter 

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#160]
Given "type" is a builtin Python function we should move away from using it as a parameter both on the external API and internal. I'd propose we use the keyword "method" instead but opening this issue to kick off discussion.

**Comment by scopatz** [comment]
I am +1 on moving away from built-in names.  As a point of reference, [pandas uses `how`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.merge.html)

**Comment by kkraus14** [comment]
@scopatz we already use the `how` parameter for specifying column names similar to Pandas, this parameter is to say whether to use the sort based method or hash based method underneath. There isn't an equivalent in Pandas as far as I know.

**Comment by scopatz** [comment]
Ahh OK, thanks for explaining the discintion.

**Comment by mike-wendt** [comment]
@kkraus14 is this fixed with the #153 merge?

**Comment by kkraus14** [comment]
@mike-wendt no, that was for a different function, this is referencing the merge function here: https://github.com/gpuopenanalytics/pygdf/blob/master/pygdf/dataframe.py#L638.

**Comment by kkraus14** [comment]
Resolved.
