### ISSUE TITLE
[BUG] Performance degradation on certain apis

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#1602]
**Describe the bug**

cudautils.py:122(copy_array)
column.py:480(to_dense_buffer)
column.py:279(to_gpu_array)

These three functions are all operating between 3-6x slower than they were in the previous table release. This is on small dataframes. Have not tested on larger data frames yet.

**Steps/Code to reproduce bug**
Run any operation that uses those apis and compare performance to previous builds.

**Expected behavior**
I did not expect to see such a significant slow down of code that is used so frequently.

**Environment details (please complete the following information):**
 - Environment location: bare metal
 - Method of cuDF install: conda

**Additional context**
@trxcllnt can add some more details about the specific versions that were compared

**Comment by lmeyerov** [comment]
https://colab.research.google.com/drive/1S5UhplicI4gpEIJz0jQdhGd3gyBAYbee

We've seen a few plummet (^^^). Less obvious, if we have a bunch of code and want to hit subsecond, the 5-10ms per-expression overhead of what should be < 1ms calls adds up  real quick. Ex: 50-200 lines of code => 300 expressions => 1-2s. Some commands really stand out: .count(), sort_values(), merge(). Overhead there may be multiplying as well...

**Comment by kkraus14** [comment]
@felipeblazing @lmeyerov The reason the performance as degraded is that the function was inconsistent and erroneous in that it sometimes returned by reference and sometimes returned by copy. It was fixed to always return by copy, but it has illuminated that the function was being used erroneously to access the underlying memory of columns. We'll have to take a sweep through and fix this behavior.
