### ISSUE TITLE
[FEA] Drop gdf_transpose()

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1603]
We currently have a `gdf_transpose()` function. This is not a good idea

Letting n be the length of the input column,

1. It replaces O(1) host-side data with O(n) host-side data.
2. It process the O(n) columns serially on the host side (there may be a bit of auto-vectorization, but not much).
3. It creates the false impression that libcudf meaningfully supports two-dimension data structures - which it doesn't.

So, I suggest we drop the pretense that transposing with cudf is really a thing.

**Comment by harrism** [comment]
This function was requested by an important user. It's clear that it has potentially very large performance issues if misused; nevertheless, it is useful for some.  

We will be looking at optimization options in the future.
