### ISSUE TITLE
Cannot import cuDF CUDA Runtime Error

### ISSUE THREAD

**Issue by weidinger-c** [rapidsai/cudf#16031]
When importing cuDF inside a docker container I get the following error:

![image](https://github.com/rapidsai/cudf/assets/126055535/5bac0e63-2b7a-4bf3-b6e1-c9fc8493af8c)

Seems there is an issue with the cuda runtime?

Outside the docker it works, the nvidia-container-runtime is installed and I can call nvidia-smi successfully inside the container. Is there something additional to install?

**Comment by Matt711** [comment]
Hi @weidinger-c, can you tell us more about how you installed cuDF?

**Comment by weidinger-c** [comment]
Like in the readem:
pip install --extra-index-url=https://pypi.nvidia.com cudf-cu11

**Comment by Matt711** [comment]
Do you have the [cuda toolkit installed](https://developer.nvidia.com/cuda-toolkit) installed?

For example, can you execute an example [Numba CUDA kernel from here](https://numba.readthedocs.io/en/stable/cuda/kernels.html)?

**Comment by vyasr** [comment]
Note that the error shown is coming from numba already. The bytecode is showing calls from `numba.cuda`, such as `numba.cuda.cudadrv.driver.driver` and `numba.cuda.runtime`. `numba` requires that you have the CUDA runtime library available somewhere.

**Comment by weidinger-c** [comment]
Thanks, I got it working by installing all CUDA deps in the container itself.
