### ISSUE TITLE
[QST] How to debug a user defined function ? Break points just won't stop.

### ISSUE THREAD

**Issue by langslike** [rapidsai/cudf#16096]
I want to try debug and run into the function "count_if_gt_3", and I set break points in the function, however the program wont stop and finish running, how to debug it? I know how to run file in debug mode, but with cudf, it just wont work. I will be glad if anyone can show me how.

```
import cudf
def count_if_gt_3(window):
    count = 0
    for i in window:
            if i > 3:
                    count += 1
    return count

s = cudf.Series([0, 1.1, 5.8, 3.1, 6.2, 2.0, 1.5])
s.rolling(3, min_periods=1).apply(count_if_gt_3)
```

[rolling.apply](https://docs.rapids.ai/api/cudf/stable/user_guide/api_docs/api/cudf.core.window.rolling.rolling.apply/#cudf.core.window.rolling.Rolling.apply)

**Comment by brandon-b-miller** [comment]
Hi @langslike ,
`rolling.apply` doesn't actually run the real python function, it uses [numba cuda](https://numba.pydata.org/numba-doc/latest/cuda/index.html) to analyze the function you pass and create a GPU equivalent that works on your data instead. However, the GPU version should match the python logic exactly, so if you want to debug, I'd recommend converting the series to pandas and passing the same function:

```python
s.to_pandas().rolling(3, min_periods=1).apply(count_if_gt_3))
```

After you have confirmed the function does what you want, you can remove the breakpoints and pass it to the `cudf` series again, I'd expect it to produce the same result.

**Comment by langslike** [comment]
@brandon-b-miller Thanks for your very quick reply, I have some knowledge on pandas and I know what pandas will do with the "count_if_gt_3" function,  I just wonder if cudf will behave like pandas. Do you mean that I actually cannot probe in what's going on under the hood with cudf? Should I just compare the cudf version code's output and pandas version code's output to confirm that I write the correct UDF?

**Comment by brandon-b-miller** [comment]
Yes, the intention is that cudf will produce the same result as pandas for any function that we accept through the API. If a function was found that broke this rule somehow, it would be considered a bug in cuDF. For simple functions, this should allow debugging using pandas with the expectation things will work on the GPU as well.

**Comment by brandon-b-miller** [comment]
Unfortunately, user defined functions (for rolling) support a limited subset of python. Generally, [these](https://numba.readthedocs.io/en/stable/cuda/cudapysupported.html) are the supported features, which as of today do not include array methods/numpy array APIs within UDFs. This means to compute the `mean`, you would have to do it using a scalar implementation that sums up the array elements and than divides by the length.

**Comment by vyasr** [comment]
Going to close as answered, but please feel free to reopen as needed. The UX here will continue to improve over time, but there are some things (like breakpoints) that will not be possible with cudf for the foreseeable future.
