### ISSUE TITLE
[QST] Question about the cuDF.pandas interception

### ISSUE THREAD

**Issue by shou123** [rapidsai/cudf#16119]
**
Hi there, 

I am working on understanding the cuDF.pandas source code and have a few questions:

1. When does cuDF.pandas enable interception to run fast_lib on the GPU? Is this logic defined in module_accelerator.py or fast_slow_proxy.py?
2. Is there a call stack map available for cuDF.pandas?
**

**Comment by Matt711** [comment]
Hi @shou123 , thanks for question!

> 1. When does cuDF.pandas enable interception to run fast_lib on the GPU? Is this logic defined in module_accelerator.py or fast_slow_proxy.py?

`cudf.pandas` works via a fast-slow proxy mechanism. It wraps Pandas types and functions into proxy types and functions that include their fast (cuDF) and slow (Pandas) versions. The proxy objects are executed on the GPU and fallback to the CPU when needed. You can find more information in the documentation [here](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/how-it-works/). The functionality you're referring to is in [`_fast_slow_function_call`](https://github.com/rapidsai/cudf/blob/c847b98291bd41f98ac417becf0c53293a392ce3/python/cudf/cudf/pandas/fast_slow_proxy.py#L873).
> 2. Is there a call stack map available for cuDF.pandas?

There is a [profiler](https://docs.rapids.ai/api/cudf/stable/cudf_pandas/usage/#) which can show which functions executed where (GPU or CPU). And we're working on more ways to better track proxied function calls.
