### ISSUE TITLE
[FEA] Add `min_by` aggregate support

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#16139]
**Is your feature request related to a problem? Please describe.**
Spark supports an aggregate called `min_by`, which is used to return the value of one column associated with the minimum value of another column. 

```
> SELECT min_by(x, y) FROM VALUES ('a', 10), ('b', 50), ('c', 20) AS tab(x, y);
 a
``` 

It would be great that cuDF can support this `min_by`, then we can use it mixed with other common aggregates (e.g. max, min) in a single groupby-aggregation execution.

**Describe the solution you'd like**
We can leverage the `argmin` to get the indices for the minimum values used for ordering, then gather the relevant values from the value column.

**Describe alternatives you've considered**
`argmin` is already exposed to users, and we can implement `min_by` outside of cuDF.
But it likely to make the users code more complicated, because when `min_by` runs with other common aggregates (count, max, min), we can not have all the aggregates done in a single pass.
It may also lead to higher memory pressure and worse performance, because the original device memory can not be released until the following gather operation is done after all the aggregates complete.

**Comment by davidwendt** [comment]
Seems like this aggregation can be performed using libcudf APIs: `groupby(argmin)`, `replace_nulls`, and `gather`.
I'm not convinced this needs to be implemented by libcudf or is providing any specific value.
The caller can just make these 3 calls. I would recommend closing this issue.

**Comment by vyasr** [comment]
That sounds similar to what @bdice proposed on the associated PR #16163. Perhaps he can comment further.

**Comment by ttnghia** [comment]
If the alternative solution can be implemented as simple as suggested above, it can be added in spark-rapids-jni under a new module like `aggregation_utils.*`.

**Comment by bdice** [comment]
I don't have anything further than what I already said on the PR. This does seem like it's already solved, and if there are unsupported semantics (e.g. for NaN handling, etc.) then we need to expand the existing functions in libcudf. https://github.com/rapidsai/cudf/pull/16163#issuecomment-2213745818

**Comment by bdice** [comment]
There may be some pieces of the work in #16163 that we want to accept as improvements to our existing code (I noticed a bug report #16542) but I have not had time to look at this further.

**Comment by thirtiseven** [comment]
> Seems like this aggregation can be performed using libcudf APIs: `groupby(argmin)`, `replace_nulls`, and `gather`. I'm not convinced this needs to be implemented by libcudf or is providing any specific value. The caller can just make these 3 calls. I would recommend closing this issue.

Yes, technically we can do that, but it will bring in another pass over the data to gather the values after the aggregation. Especially if there are multiple aggregations, we may have to keep the original data, extract the argmin results, gather to get the values, and then concatenate the results back. This would be painful to do in an upper layer, but efficient to do in cuDF's aggregation framework.

> If the alternative solution can be implemented as simple as suggested above, it can be added in spark-rapids-jni under a new module like aggregation_utils.*.

Not sure if I got the idea. I think currently we collect all aggs to a request list in spark-rapids and make cuDF to handle them and get the results back. Does it means we need to port a part of the cuDF aggregation framework if we want to add some spark specific aggregate functions in spark-rapids-jni?

**Comment by ttnghia** [comment]
> Does it means we need to port a part of the cuDF aggregation framework if we want to add some spark specific aggregate functions in spark-rapids-jni?

This is a good idea that I wanted to do for a while. I'm thinking of changing the cudf groupby/reduction framework such that we can implement our custom aggregations in spark-rapids-jni and just plug into it. Doing so, we can maximize our ability of customization. For example, for `M2`/`MERGE_M2` aggregation we want to output more than just one columns for reuse in other aggregation computation.

But that should be a future work. In the meantime, it is better to either implement the new aggregation in cudf or spark-rapids-jni like we are doing/discussing above.

**Comment by davidwendt** [comment]
> Yes, technically we can do that, but it will bring in another pass over the data to gather the values after the aggregation. Especially if there are multiple aggregations, we may have to keep the original data, extract the argmin results, gather to get the values, and then concatenate the results back. This would be painful to do in an upper layer, but efficient to do in cuDF's aggregation framework.

But the implementation you added to libcudf in PR #16163 is literally calling `groupby(argmin/argmax)`, `replace_nulls`, and `gather`:
https://github.com/rapidsai/cudf/blob/b98dfbaa8794c8235498a40f2f5d63b1b18f38ac/cpp/src/groupby/sort/aggregate.cpp#L203-L227
I'm not sure how the upper layer would be inconvenienced by calling this same patten with the public APIs.

> Not sure if I got the idea. I think currently we collect all aggs to a request list in spark-rapids and make cuDF to handle them and get the results back. Does it means we need to port a part of the cuDF aggregation framework if we want to add some spark specific aggregate functions in spark-rapids-jni?

Yes, I think spark-specific aggregate functions should not be implemented in libcudf.

**Comment by ttnghia** [comment]
I've filed an issue for my idea: https://github.com/rapidsai/cudf/issues/16633
