### ISSUE TITLE
[BUG] ORC incorrect schema ingestion

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1615]
With the following [ORC file](https://www.googleapis.com/download/storage/v1/b/anaconda-public-data/o/orc%2FTestOrcFile.testDate1900.orc?generation=1522611448751555&alt=media), cudf incorrect assign datetimes a dtype of `datetime64[ms]` when the schema defines the dtype as `datetime64[ns]`

```python
In [1]: import pyarrow.orc as orc

In [2]: path = 'sample.orc'

In [3]: o = orc.ORCFile(path)

In [4]: o.schema
Out[5]:
time: timestamp[ns]
date: date32[day]

In [5]: import cudf

In [6]: cdf = cudf.read_orc(path)

In [7]: cdf.dtypes
Out[7]:
time    datetime64[ms]
date    datetime64[ms]
dtype: object
```

**Comment by j-ieong** [comment]
When we looked at it, `cudf` has many places still hard-coded to use milliseconds. This comment [comment](https://github.com/rapidsai/cudf/blob/61bc74fb4e237675e19a80c9f8446d24b7cf587e/python/cudf/dataframe/datetime.py#L22) implies only millisecond is supported.

**Comment by quasiben** [comment]
@j-ieong thanks!  I vaguely recall knowing this at one point?  Do you know if this is also documented elsewhere ?  If not, @kkraus14 @thomcom do you have thoughts here ?  Should this be documented ?  Are there plans to move to support dt64[ns] after 0.7 release ?  Can I help ?

**Comment by kkraus14** [comment]
> @j-ieong thanks! I vaguely recall knowing this at one point? Do you know if this is also documented elsewhere ? If not, @kkraus14 @thomcom do you have thoughts here ? Should this be documented ? Are there plans to move to support dt64[ns] after 0.7 release ? Can I help ?

There are plans to support arbitrary resolution timestamp types in the future, but for the 0.7 release we currently only support millisecond resolution. Changes will be needed at both the Python and libcudf levels and would gladly accept help towards making that a reality.

**Comment by quasiben** [comment]
thanks @kkraus14 !  closing this issue
