### ISSUE TITLE
[QST] Is CUDF_USE_PER_THREAD_DEFAULT_STREAM enabled by default for the published Java artifacts?

### ISSUE THREAD

**Issue by billu94** [rapidsai/cudf#16208]
**What is your question?**
Is CUDF_USE_PER_THREAD_DEFAULT_STREAM enabled by default for the published Java artifacts to maven central? https://repo1.maven.org/maven2/ai/rapids/cudf/24.06.0/ 

Is there a way to check this?

**Comment by jlowe** [comment]
Yes, it is enabled by default for the Java bindings.  You can examine the setting at runtime via Cuda.isPtdsEnabled(), for example, I used jshell to verify:
```
$ jshell -class-path cudf-24.06.0.jar:/home/jlowe/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar
|  Welcome to JShell -- Version 11.0.23
|  For an introduction type: /help intro

jshell> ai.rapids.cudf.Cuda.isPtdsEnabled()
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
$1 ==> true
```

**Comment by jlowe** [comment]
The script used to build the artifact is located under java/ci/build-in-docker.sh which defaults per-thread default stream to ON.
