### ISSUE TITLE
[FEA] Support parquet read from multiple source with mismatched schema if set of projected columns have matching schemas

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#16269]
**Is your feature request related to a problem? Please describe.**

Suppose I have two parquet files, both with two columns. 

The first (`f1`) with schema:
```
a: int32
b: string
```
The second (`f2`) with schema
```
a: float32
b: string
```

Clearly, `read_parquet([f1, f2])` should fail, since we can't unify (without casting, which the reader should not do) the schema of `a`, and `b`.

However, arguably `read_parquet([f1, f2], projected_columns=["b"])` could succeed since `b` has the same schema in both `f1` and `f2`, and we never look at `a`.

It would be nice if this latter use case were possible.

It becomes slightly more complicated if there are filters since one must also have matching schemas for the columns that are referenced in the filters.

**Describe the solution you'd like**

It would be nice if the parquet reader only worried about matching the schema of those columns that are actually read.

**Describe alternatives you've considered**

This behaviour comes up via the cudf-polars works, where polars supports the reading of sets of parquet files as long as the _projected_ schemas match.

Alternatively I could read each parquet file individual with column projections and then concatenate the results, but this serialises the reads and is likely not as performant.

If I only want to do this for files where libcudf will complain I would need to first inspect the metadata which could also be costly (since that information will be thrown away and reconstituted by libcudf when we actually read the files).

**Comment by GregoryKimball** [comment]
Thank you @wence-, this seems like something we could support. Types must only match in projected columns plus the columns used for filtering.

**Comment by mhaseeb123** [comment]
Working on this!

**Comment by wence-** [comment]
> Can be supported with a limitation that the column(s) in question in all data sources must have an identical `SchemaElement`. i.e. either the cols must be nullable in all sources or none. Mix and match won't work. (This needs to be tracked and fixed in a separate issue).

This is presumably the case even if both files had the _same_ schema (up to nullability)?

**Comment by mhaseeb123** [comment]
> > Can be supported with a limitation that the column(s) in question in all data sources must have an identical `SchemaElement`. i.e. either the cols must be nullable in all sources or none. Mix and match won't work. (This needs to be tracked and fixed in a separate issue).
> 
> This is presumably the case even if both files had the _same_ schema (up to nullability)?

Yes, we enforce the schemas across files to be identical (up to nullability). Bypassing this check currently leads to `page_decode()` failure when reading. For the current issue, we will need this constraint for the columns of interest only.

```python
def test_nullability():
    df = cudf.DataFrame({"a": [1, 2, 3]})
    nonulls = BytesIO()
    df.to_parquet(nonulls)
    df = cudf.DataFrame({"a": [4, None, 6]})
    nulls = BytesIO()
    df.to_parquet(nulls)
    # this is CUDF_FAIL.
    read = cudf.read_parquet([nonulls, nulls])
```

**Comment by mhaseeb123** [comment]
Hi @wence-, I looked into a solution for this a bit deeper and here are a few thoughts. Unless the column(s) of interest in multiple sources have an _identical schema and are located at the same indices in the schema tree_, we would need to add a lot of book-keeping to track where to collect pages from for the columns in question.

For example, the following case can be easily supported.

Consider ``f1`:
```
... 
i: int64
j: list[int32]
...
k: float64
...
l: string
m: float64
... (don't care)
```
and `f2`
```
... 
i: float32
j: list[int32]
... 
k: float64
...
l: bool
m: float64
... (don't care)
```
then say: `read_parquet([f1, f2], projected_columns=["j, k, m"])` would work and can be easily supported since these columns are located at the same schema_idx in both files

**Comment by mhaseeb123** [comment]
On the other hand, supporting the following case would require quite a bit of extra effort.

Consider ``f1`:
```
... 10 cols 
i: int64
j: list[int32]
... 2 cols
k: float64
... 4 cols
l: string
m: float64
... (don't care how many cols after this)
```
and `f2`
```
... 9 cols -> difference
i: float32
j: list[int32]
... 2 cols
k: float64
... 4 cols
l: bool
m: float64
... (don't care how many cols after this)
```

**Comment by mhaseeb123** [comment]
Another solution that I am thinking of would involve transplanting all schema trees to a common structure (given the cols are present in all of them and have an identical `SchemaElement` to the nullability) and use the existing parquet reader as is. Looking into the feasibility of this solution still.

**Comment by mhaseeb123** [comment]
Hi @wence-, please let us know if solution 1 (requiring )

> Hi @wence-, I looked into a solution for this a bit deeper and here are a few thoughts. Unless the column(s) of interest in multiple sources have an _identical schema and are located at the same indices in the schema tree_, we would need to add and handle a quite a bit of book-keeping to track where to collect pages from for the columns in question.
> 
> For example, the following case can be easily supported.
> 
> Consider `f1`:
> 
> ```
> ... 10 cols
> i: int64
> j: list[int32]
> ... 5 cols 
> k: float64
> ... 4 cols
> l: string
> m: float64
> ... (don't care how many cols after this)
> ```
> 
> and `f2`
> 
> ```
> ... 10 cols
> i: float32
> j: list[int32]
> ... 5 cols
> k: float64
> ... 4 cols
> l: bool
> m: float64
> ... (don't care how many cols after this)
> ```
> 
> then say: `read_parquet([f1, f2], projected_columns=["j, k, m"])` would work and can be easily supported since these columns are located at the same schema_idx in both files. Do you think this case would work for your application?

Hi @wence- , please let us know if this above solution would work for your case or if the latter solution with tranplanting trees would be the way to go. Thanks!

**Comment by wence-** [comment]
> Hi @wence-, please let us know if solution 1 (requiring )
> 
> > Hi @wence-, I looked into a solution for this a bit deeper and here are a few thoughts. Unless the column(s) of interest in multiple sources have an _identical schema and are located at the same indices in the schema tree_, we would need to add and handle a quite a bit of book-keeping to track where to collect pages from for the columns in question.
> > For example, the following case can be easily supported.
> > Consider `f1`:
> > ```
> > ... 10 cols
> > i: int64
> > j: list[int32]
> > ... 5 cols 
> > k: float64
> > ... 4 cols
> > l: string
> > m: float64
> > ... (don't care how many cols after this)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and `f2`
> > ```
> > ... 10 cols
> > i: float32
> > j: list[int32]
> > ... 5 cols
> > k: float64
> > ... 4 cols
> > l: bool
> > m: float64
> > ... (don't care how many cols after this)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then say: `read_parquet([f1, f2], projected_columns=["j, k, m"])` would work and can be easily supported since these columns are located at the same schema_idx in both files. Do you think this case would work for your application?
> 
> Hi @wence- , please let us know if this above solution would work for your case or if the latter solution with tranplanting trees would be the way to go. Thanks!

I will check on monday, thanks
