### ISSUE TITLE
[BUG] `cudf::strings_column_view::chars_size` returns incorrect value for sliced input

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#16298]
The implementation of `strings_column_view::chars_size` does not consider the `offset` value of the input column. As such, it always returns the total chars size of the column, not the size of the current sliced view.
For example:
```
// Input contains 2600 rows.
auto char_s  = input.chars_size(stream);
auto sl      = cudf::slice(input.parent(), {input.size() / 2, input.size() / 2 + 1})[0];
auto char_s2 = cudf::strings_column_view{sl}.chars_size(stream);
printf("char size: %d - %d\n", (int)char_s, (int)char_s2);

Output: char size: 21967941 - 21967941
```

We should take the column `offset` into account for this function.

**Comment by davidwendt** [comment]
This is on purpose. This was decided when it was designed/implemented.
This is even documented in the doxygen for this method
https://github.com/rapidsai/cudf/blob/8b767e5c237840e0a35848bff7ed479ec5c56bb1/cpp/include/cudf/strings/strings_column_view.hpp#L88-L97
