### ISSUE TITLE
[FEA] Explore performance and optimizations for rolling windows

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1635]
#1356 was merged but there are some opportunities for optimization. The main one would be eliminating duplicate loads in overlapping windows by cooperatively loading into shared memory and then aggregating from there: the classic way "stencils" are implemented, since rolling is just a stencil.

Should create a benchmark for rolling windows and use it for investigation.

See the TODO here: https://github.com/rapidsai/cudf/blob/b936b52767b161522894634ed09ff583f48a38ac/cpp/src/rolling/rolling.cu#L138-L147

CC @nsakharnykh

**Comment by GregoryKimball** [comment]
`rolling.cu` has been through a lot of changes since May 2019. It appears this was resolved in #3305 and #3601.
