### ISSUE TITLE
[BUG] cudf.Series.unique() and pandas.Series.unique() return different type of objects

### ISSUE THREAD

**Issue by dantegd** [rapidsai/cudf#16417]
There is a small discrepancy between cuDF and pandas when using the `unique` function of a `Series`, which seems unintentional to me: 

Code to repro:
```python
import cudf
import cupy as cp
import pandas as pd
import numpy as np

df = pd.DataFrame(np.random.rand(100,10))

print(type(df[df.columns[0]].unique())) # this is a numpy array

df2 = cudf.DataFrame(cp.random.rand(100,10))

print(type(df2[df2.columns[0]].unique())) # this is a cuDF Series
```

Output:
```python
(rapids) coder ➜ ~/cuml $ python repro.py
<class 'numpy.ndarray'>
<class 'cudf.core.series.Series'>
```

**Comment by bdice** [comment]
@dantegd Last time I noticed this, I didn't think there was any way to improve it. Returning a NumPy array isn't good because it would copy data to the host. Returning a CuPy array isn't an option because CuPy can't represent all the types that cuDF can represent. Thus returning a cuDF Series is the only logical choice imo. What would you propose to do here?

**Comment by dantegd** [comment]
> @dantegd Last time I noticed this, I didn't think there was any way to improve it. Returning a NumPy array isn't good because it would copy data to the host. Returning a CuPy array isn't an option because CuPy can't represent all the types that cuDF can represent. Thus returning a cuDF Series is the only logical choice I can see. What would you propose to do here?

Makes sense why a copy array wouldn't suffice then, is this documented somewhere? Main issue is the surprise element really. This also is a difference that crops up when turning on cudf.pandas for some codes, which can be surprising if one relies on the cudf to series behavior (cuML did in a couple of places). Probably doesn't warranty a warning, but an info level logging maybe?

**Comment by bdice** [comment]
@dantegd Please try running the pandas snippet with cudf.pandas enabled. The behavior changes between cudf and cudf.pandas: https://github.com/rapidsai/cudf/blob/58f47242fe04b1e25fd42e1e45e8c15417140777/python/cudf/cudf/core/series.py#L3045-L3046

```
<class 'cudf.pandas._wrappers.numpy.ndarray'>
```
