### ISSUE TITLE
[BUG] list.sort_values returning incorrect results in some cases.

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#16455]
**Describe the bug**
Ran into a bug where sorting list values in a series led to a few rows producing incorrectly sorted results.

**Steps/Code to reproduce bug**
```python
import cudf

df = cudf.read_parquet("listtype.parquet")
sorted_df = df.a.list.sort_values()
sorted_df.to_pandas().apply(lambda x: sorted(x) != x).sum()
3
```
Effectively 3 rows returned incorrect results.

More specifically these 3 indices: [79888, 122495, 163667] have incorrectly sorted results.

Repro Data: [data.tgz](https://github.com/user-attachments/files/16447883/data.tgz)

**Expected behavior**
Correctly sorted values

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: pip release 24.06
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by Matt711** [comment]
I was able to reproduce in 24.10. And I get a lot more incorrect results when `ascending=False`

```python
import cudf

df = cudf.read_parquet("listtype.parquet")
sorted_df = df.a.list.sort_values(ascending=False)
sorted_df.to_pandas().apply(lambda x: sorted(x) != x).sum()
206721
```
