### ISSUE TITLE
[FEA] Add support for `cudf.unique`

### ISSUE THREAD

**Issue by Matt711** [rapidsai/cudf#16460]
**Is your feature request related to a problem? Please describe.**
I'd like cuDF to support `cudf.unique` like pandas
```python
>>> cudf.unique(cudf.Series([2, 1, 3, 3]))
array([2, 1, 3])
```

**Describe the solution you'd like**
There's already `cudf.Series.unique` which works. I'm primarily interested in this feature in the context of `cudf.pandas` which currently falls back on this operation. I think we can just follow the approach used by `cudf.Series.unique` to support `cudf.unique`.

```python
>>> cudf.Series([2, 1, 3, 3]).unique()
0    2
1    1
2    3
dtype: int64
```

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by mroeschke** [comment]
You'll just need to be mindful of the return types of `pandas.unique` which depends on the input: https://pandas.pydata.org/docs/reference/api/pandas.unique.html
