### ISSUE TITLE
[FEA] Support order-preserving groupby option in cudf-polars

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#16477]
In polars, a groupby operation by default is not order-preserving. However, one can optionally ask for order-preservation.

Right now, cudf-polars does not support the order-preserving groupby and therefore falls back to the CPU engine.

Since groupby-aggregations are one place where the GPU acceleration really shines, it would be good to support this mode of operation.

This should be possible, once the exact ordering requirements are determined, by a mode that is similar to the way we do order-preservation in the cudf-classic groupby code.

**Comment by lithomas1** [comment]
Done
