### ISSUE TITLE
[FEA] Support scan-based aggregations in cudf-polars

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#16478]
We currently support reduction-based aggregations in both whole-frame and groupby contexts. However, we have not yet implemented scan-based aggregations.

We should implement these. The whole-frame case is probably quite straightforward. For the grouped context, we probably need some libcudf work (see https://github.com/rapidsai/cudf/issues/15541)

**Comment by beckernick** [comment]
This was implemented for the beta release (except cumulative count, which we can track independently)
