### ISSUE TITLE
ValueError: cannot determine Numba type of <class 'datetime.datetime'>, while using datetime value in query 

### ISSUE THREAD

**Issue by Salonijain27** [rapidsai/cudf#165]
I ran the following lines of code, to filter out rows in a dataframe based on a datetime dtype value :
```
import numpy
from pygdf import DataFrame
from pygdf import Series
import pandas as pd
from datetime import *
df_pandas = pd.DataFrame()
start_date = datetime.strptime("2000-10-21", '%Y-%m-%d')
data = [(start_date + timedelta(days=x)) for x in range(6)]
df_pandas["dates"] = data
df_pandas["num"] = [1,2,3,4,5,6]
df_pygdf = DataFrame.from_pandas(df_pandas)
df_pygdf = df_pygdf.query("dates==@start_date")
```
the error I get is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf/dataframe.py", line 877, in query
    boolmask = queryutils.query_execute(self, expr, callenv)
  File "/conda/envs/gdf/lib/python3.6/site-packages/pygdf/queryutils.py", line 217, in query_execute
    kernel.forall(nrows)(*args)
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/cuda/compiler.py", line 251, in __call__
    kernel = self.kernel.specialize(*args)
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/cuda/compiler.py", line 746, in specialize
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/cuda/compiler.py", line 746, in <listcomp>
    [self.typingctx.resolve_argument_type(a) for a in args])
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/typing/context.py", line 292, in resolve_argument_type
    return typeof(val, Purpose.argument)
  File "/conda/envs/gdf/lib/python3.6/site-packages/numba/typing/typeof.py", line 35, in typeof
    raise ValueError(msg)
ValueError: cannot determine Numba type of <class 'datetime.datetime'>
```

**Comment by Salonijain27** [comment]
workaround this problem is converting the datetime format to unixtime :
```
import numpy
from pygdf import DataFrame
from pygdf import Series
import pandas as pd
from datetime import *
import time
df_pandas = pd.DataFrame()
start_date = datetime.strptime("2000-10-21", '%Y-%m-%d')
data = [time.mktime((start_date + timedelta(days=x)).timetuple()) for x in range(6)]
df_pandas["dates"] = data
df_pandas["num"] = [1,2,3,4,5,6]
df_pygdf = DataFrame.from_pandas(df_pandas)
start_date = time.mktime(start_date.timetuple())
df_pygdf = df_pygdf.query("dates==@start_date")
```

**Comment by scopatz** [comment]
@hhuuggoo - would you mind taking a look at this, please?

**Comment by hhuuggoo** [comment]
Will have a look today

**Comment by hhuuggoo** [comment]
ok so I think a few things need to happen for this to work properly

1.  we need to detect python datetime objects in 

https://github.com/gpuopenanalytics/pygdf/blob/master/pygdf/queryutils.py#L202

and coerce them into ints so that numba is happy

2.  we need to extend the DatetimeColumn to pull in some of the binary op capabilities that the numeric column has ( I thought we could inherit, but that seems like a bad idea )

3.  we need to extend libgdf gdf_eq_generic to handle date32/64/timestamp

I'm planning on doing 3, then 2 then 1.

**Comment by mike-wendt** [comment]
@hhuuggoo can you link the relevant PR(s) here?

**Comment by hhuuggoo** [comment]
extend libgdf logical ops to date32/64/timestamp

libgdf/83 https://github.com/gpuopenanalytics/libgdf/pull/83

I also had to modify datetime ops to support null masks

libgdf/84 - https://github.com/gpuopenanalytics/libgdf/pull/84

and then the pygdf changes, #186 

ligdf/83 is independent
libgdf/84 was built on top of libgdf/83 but does not depend on it, so I could rebase it onto master if nececssary
#186  depends on libgdf/83 and libgdf/84

**Comment by hhuuggoo** [comment]
I need to take a second look at the WIP PRs this afternoon, but I'm pretty sure they are ready or just a touc missing

**Comment by kkraus14** [comment]
This is resolved now.
