### ISSUE TITLE
[BUG]cannot pip install on linux (Ubuntu)

### ISSUE THREAD

**Issue by SHIMURA0** [rapidsai/cudf#16557]
**Describe the bug**
I am trying to install cuff on linux (Ubuntu) server using the command 
pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12
but at the very end of the installing I have the following error:
![221723625460_ pic](https://github.com/user-attachments/assets/a74a393f-3729-4175-9a88-f184a9a86dae)
I will be grateful if someone can help me to resolve this issue.

Linux server: Ubuntu 20.04
Python conda environment: python=3.10
Nvidia GPU = V100 
CUDA 12.1

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by bdice** [comment]
It looks like this is trying to install 23.12, an old release. Can you try to install the latest release? We have improved the error reporting and it should give us more debugging info even if it fails to install.

`pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12==24.8.*`

**Comment by SHIMURA0** [comment]
I am so grateful! It works! 



> It looks like this is trying to install 23.12, an old release. Can you try to install the latest release? We have improved the error reporting and it should give us more debugging info even if it fails to install.
> 
> `pip install --extra-index-url=https://pypi.nvidia.com cudf-cu12==24.8.*`

**Comment by SHIMURA0** [comment]
Another question, I wonder how to install and use desk_cudf, I find that repository has been moved to CUDF.

**Comment by bdice** [comment]
The installation guide shows how to get all of RAPIDS. Try this: https://docs.rapids.ai/install

This command installs all RAPIDS packages.

```bash
pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu12==24.8.* dask-cudf-cu12==24.8.* cuml-cu12==24.8.* \
    cugraph-cu12==24.8.* cuspatial-cu12==24.8.* cuproj-cu12==24.8.* \
    cuxfilter-cu12==24.8.* cucim-cu12==24.8.* pylibraft-cu12==24.8.* \
    raft-dask-cu12==24.8.* cuvs-cu12==24.8.*
```

**Comment by vyasr** [comment]
Closing as resolved. Please feel free to reopen if needed.
