### ISSUE TITLE
[BUG] Illegal Memory Access w/ New cuDF Polars backend

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#16582]
@lithomas1 first identified an illegal memory error when running cudf_Polars on an H100 using the TPC-H benchmark at Scale Factor (SF) 100GB:

> RUN_POLARS_GPU_DEVICE=1 RUN_POLARS_GPU=1 SCALE_FACTOR=100 python -m queries.polars.q1

And the above results in the following errors

```
bzaitlen@XYZ:/tpch$ RUN_POLARS_GPU_DEVICE=1 RUN_POLARS_GPU=1 SCALE_FACTOR=100 python -m queries.polars.q1
warn: error opening log file: Permission denied, logging will be disabled
Code block 'Run polars-gpu-cuda query 1' took: 3.79167 s
q1 FAILED
MemoryError: std::bad_alloc: CUDA error at: /tmp/pip-build-env-a9j9c7q6/normal/lib/python3.10/site-packages/librmm/include/rmm/mr/device/cuda_memory_resource.hpp:60: cudaErrorIllegalAddress an illegal memory       access was encountered
CUDA error at: /__w/cudf/cudf/python/cudf/build/cp310-cp310-linux_x86_64/_deps/kvikio-src/cpp/include/kvikio/posix_io.hpp:53: CUDA_ERROR_ILLEGAL_ADDRESS(an illegal memory access was encountered)
```

Thus far we have not been able to build a smaller reproducer. Both in terms of scale or different hardware.  When running at 120GB we correctly get an OOM:

> $ RUN_POLARS_GPU_DEVICE=1 RUN_POLARS_GPU=1 SCALE_FACTOR=120 python -m queries.polars.q1
warn: error opening log file: Permission denied, logging will be disabled
Code block 'Run polars-gpu-cuda query 1' took: 4.18674 s
q1 FAILED
MemoryError: std::bad_alloc: out_of_memory: CUDA error at: /tmp/pip-build-env-a9j9c7q6/normal/lib/python3.10/site-packages/librmm/include/rmm/mr/device/cuda_memory_resource.hpp:60: cudaErrorMemoryAllocation out of memory

We've both used compute-sanitizer to help diagnose though we've seen varying reports.  For example when I run with:

> compute-sanitizer --tool memcheck --print-limit 0
I see errors like:

> ========= Leaked 16777216 bytes at 0x7f833e000000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2da4ea]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x143a3ff]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x14537c8]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
===

Full details below:
<details>
========= Program hit CUDA_ERROR_INVALID_CONTEXT (error 201) due to "invalid device context" on CUDA API call to cuCtxGetDevice.
=========     Saved host backtrace up to driver entry point at error
=========     Host Frame: [0x2cb03c]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame:__pyx_f_4cuda_5_cuda_5ccuda__cuCtxGetDevice(int*) in cuda/_cuda/ccuda.cpp:23194 [0x51828]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cuda/_cuda/ccuda.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:__pyx_f_4cuda_4_lib_7ccudart_7ccudart__cudaGetDevice(int*) in cuda/_lib/ccudart/ccudart.cpp:16071 [0x9ff8]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cuda/_lib/ccudart/ccudart.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:__pyx_f_4cuda_7ccudart_cudaGetDevice(int*) in cuda/ccudart.cpp:10901 [0x10ca9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cuda/ccudart.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:__pyx_pw_4cuda_6cudart_71cudaGetDevice(_object*, _object*) in cuda/cudart.cpp:260990 [0x35ebb1]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cuda/cudart.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4181 [0x139141]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame: [0x64dab]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/rmm/_lib/memory_resource.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4181 [0x139141]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4181 [0x139141]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4213 [0x13484f]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_Vector in /usr/local/src/conda/python-3.10.14/Python/ceval.c:5067 [0x1d7c5f]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:PyEval_EvalCode in /usr/local/src/conda/python-3.10.14/Python/ceval.c:1134 [0x1d7ba6]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:builtin_exec in /usr/local/src/conda/python-3.10.14/Python/clinic/bltinmodule.c.h:371 [0x1deda9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:cfunction_vectorcall_FASTCALL in /usr/local/src/conda/python-3.10.14/Objects/methodobject.c:430 [0x144bf2]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4213 [0x13484f]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4213 [0x13484f]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:pymain_run_module in /usr/local/src/conda/python-3.10.14/Modules/main.c:297 [0x1fab77]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:Py_RunMain in /usr/local/src/conda/python-3.10.14/Modules/main.c:670 [0x1fa4be]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:Py_BytesMain in /usr/local/src/conda/python-3.10.14/Modules/main.c:1090 [0x1cb1f6]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:__libc_start_call_main in ../sysdeps/nptl/libc_start_call_main.h:58 [0x29d8f]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:__libc_start_main in ../csu/libc-start.c:392 [0x29e3f]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0x1cb0f0]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========
warn: error opening log file: Permission denied, logging will be disabled
Code block 'Run polars-gpu-cuda query 1' took: 51.60195 s
========= Leaked 16777216 bytes at 0x7f833e000000
=========     Saved host backtrace up to driver entry point at allocation time
=========     Host Frame: [0x2da4ea]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x143a3ff]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x14537c8]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, std::thread::_In
voker<std::tuple<kvikio::FileHandle::pread(void*, unsigned long, unsigned long, unsigned long, unsigned long)::{lambda()#2}> >, unsigned long> >::_M_invoke(std::_Any_data const&) [0x14552b2]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) [0x12fb70a]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:__pthread_once_slow in ./nptl/pthread_once.c:116 [0x99ee7]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame:std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<kvikio::FileHandle::pread(void*, unsigned long, unsigned long, unsigned long, unsigned long)::{lambda()#2}> >, unsigned long>::_M_complete_async() [0x1450464]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x13a3085]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) [0x12fb70a]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:__pthread_once_slow in ./nptl/pthread_once.c:116 [0x99ee7]
=========                in /lib/x86_64-linux-gnu/libc.so.6
=========     Host Frame: [0x139dc51]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::parquet::detail::reader::impl::read_compressed_data() [0x13c7146]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::parquet::detail::reader::impl::setup_next_pass(cudf::io::parquet::detail::reader::impl::read_mode) [0x137bdbb]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::parquet::detail::reader::impl::handle_chunking(cudf::io::parquet::detail::reader::impl::read_mode) [0x13811b4]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::parquet::detail::reader::impl::read() [0x134ea14]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::parquet::detail::reader::read() [0x134714d]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::io::read_parquet(cudf::io::parquet_reader_options const&, rmm::cuda_stream_view, cuda::mr::__4::basic_resource_ref<(cuda::mr::__4::_AllocType)1, cuda::mr::__4::device_accessible>) [0x11b05ad]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x36d76]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/pylibcudf/io/parquet.cpython-310-x86_64-linux-gnu.so
=========     Host Frame: [0x379b4]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/lib/python3.10/site-packages/cudf/_lib/pylibcudf/io/parquet.cpython-310-x86_64-linux-gnu.so
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:method_vectorcall in /usr/local/src/conda/python-3.10.14/Objects/classobject.c:53 [0x150581]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:method_vectorcall in /usr/local/src/conda/python-3.10.14/Objects/classobject.c:53 [0x150581]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:method_vectorcall in /usr/local/src/conda/python-3.10.14/Objects/classobject.c:53 [0x150581]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:method_vectorcall in /usr/local/src/conda/python-3.10.14/Objects/classobject.c:53 [0x150581]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4231 [0x1358f9]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyFunction_Vectorcall in /usr/local/src/conda/python-3.10.14/Objects/call.c:342 [0x144a2b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:PyObject_Call in /usr/local/src/conda/python-3.10.14/Objects/call.c:317 [0x150f1b]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:partial_call in /usr/local/src/conda/python-3.10.14/Modules/_functoolsmodule.c:323 [0x20a9ad]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyObject_MakeTpCall in /usr/local/src/conda/python-3.10.14/Objects/call.c:215 [0x13da6a]
=========                in /datasets/bzaitlen/miniconda3/envs/polars-pip-test-2024-07-29/bin/python
=========     Host Frame:_PyEval_EvalFrameDefault in /usr/local/src/conda/python-3.10.14/Python/ceval.c:4277 [0x1372b2]
</details>

Where as Thomas has observed:

> ========= Invalid __global__ read of size 4 bytes
=========     at void cudf::strings::detail::gather_chars_fn_char_parallel<(int)32, thrust::transform_iterator<cudf::detail::value_accessor<cudf::string_view>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::use_default, thrust::use_default>, cudf::detail::input_indexalator>(T2, char *, cudf::detail::input_offsetalator, T3, int)+0x10f0
=========     by thread (2,0,0) in block (17179560,0,0)
=========     Address 0x7ef4f511d408 is out of bounds
=========     and is 358441 bytes after the nearest allocation at 0x7ef468000000 of size 2366397408 bytes

<details>
========= Invalid __global__ read of size 4 bytes
=========     at void cudf::strings::detail::gather_chars_fn_char_parallel<(int)32, thrust::transform_iterator<cudf::detail::value_accessor<cudf::string_view>, thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::use_default, thrust::use_default>, cudf::detail::input_indexalator>(T2, char *, cudf::detail::input_offsetalator, T3, int)+0x10f0
=========     by thread (2,0,0) in block (17179560,0,0)
=========     Address 0x7ef4f511d408 is out of bounds
=========     and is 358441 bytes after the nearest allocation at 0x7ef468000000 of size 2366397408 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame: [0x33255f]
=========                in /lib/x86_64-linux-gnu/libcuda.so.1
=========     Host Frame: [0x2d5155d]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x2db4fcd]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x7c5f83]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x7d8da2]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x84a3fd]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::detail::gather(cudf::table_view const&, cudf::column_view const&, cudf::out_of_bounds_policy, cudf::detail::negative_index_policy, rmm::cuda_stream_view, cuda::mr::__4::basic_resource_ref<(cuda::mr::__4::_AllocType)1, cuda::mr::__4::device_accessible>) [0x7e01c7]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::detail::gather(cudf::table_view const&, cudf::device_span<int const, 18446744073709551615ul>, cudf::out_of_bounds_policy, cudf::detail::negative_index_policy, rmm::cuda_stream_view, cuda::mr::__4::basic_resource_ref<(cuda::mr::__4::_AllocType)1, cuda::mr::__4::device_accessible>) [0x7e02cd]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x280ad25]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame: [0x280bb4f]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::detail::apply_boolean_mask(cudf::table_view const&, cudf::column_view const&, rmm::cuda_stream_view, cuda::mr::__4::basic_resource_ref<(cuda::mr::__4::_AllocType)1, cuda::mr::__4::device_accessible>) [0x27ef338]
=========                in /raid/tholi/miniconda3/lib/python3.11/site-packages/cudf/_lib/../libcudf.so
=========     Host Frame:cudf::apply_boolean_mask(cudf::table_view const&, cudf::column_view const&, cuda::mr::__4::basic_resource_ref<(cuda::mr::__4::_AllocType)1, cuda::mr::__4::device_accessible>) [0x27ef3e1]
</details>

I have the slightest suspicion that something is going awry with the fallback here. When I slightly amend [TPCH Q1](https://github.com/pola-rs/tpch/blob/27215e614ab3b4d3be502dc5aa7e96207241a82b/queries/polars/q1.py#L25-L27)
to not include the binary operations I don't observe the illegal memory access error

**Comment by wence-** [comment]
Fixed by #16643 (which is in 24.10 and has been backported to feature/cudf/polars)
