### ISSUE TITLE
[FEA] Accelerate CI/CD by building and testing only the changed modules

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#16606]
The CI/CD time now is several hours, which is enormous. Sometimes, there are only very few changes in the code but they trigger the entire CI/CD pipeline to build and test for all unrelated modules. We can do much better by only building and testing the related ones for each PR.

For example, changes in the `java` folder would never affect the `libcudf` and `cudf` python modules thus we would never need to build and test them. Similarly, changes only in the python module should never trigger rebuilding and testing the `libcudf` as well as `java` module.

**Comment by vyasr** [comment]
Yes, this is a good idea. We're discussing this kind of change RAPIDS-wide in https://github.com/rapidsai/build-planning/issues/5, so closing in favor that issue.
