### ISSUE TITLE
[BUG] cudaErrorIllegalAddress while copying values to nullable string series

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#16618]
**Describe the bug**
`cudaErrorIllegalAddress` while copying values to nullable string series. This is a regression from the behavior in `24.02`.

**Steps/Code to reproduce bug**
```
cudf.Series(['a', None])[1:2] = ['b'] # cudaErrorIllegalAddress
```
However, the following _does_ work:
```
cudf.Series(['a', 'b'])[1:2] = ['c'] # works
```
as does:
```
cudf.Series([0, 1])[1:2] = [2] # works
```

**Expected behavior**
expected the value to be copied to the specified range without causing `cudaErrorIllegalAddress`

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: conda

**Additional context**
Morpheus depends heavily on this behavior.

**Comment by davidwendt** [comment]
Also this works
```
cudf.Series(['a', None])[1:2] = 'b'
```
Broken down just to make sure:
```
>>> import cudf
>>> s = cudf.Series(['a', None])
>>> s[1:2] = 'b'
>>> s
0    a
1    b
dtype: object
```
