### ISSUE TITLE
[BUG] Series.duplicated doesn't preserve name

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#16654]
**Describe the bug**
Series.duplicated doesn't preserve name

**Steps/Code to reproduce bug**

```
cudf.Series([1,2,3], name='a').duplicated().name
```

**Expected behavior**
Output should be `'a'`, like it is in pandas

**Environment overview (please complete the following information)**

Kaggle notebook, cudf version 24.08.02

Noticed this in [Narwhals](https://github.com/narwhals-dev) tests

**Comment by bdice** [comment]
Thanks for the bug report! I'm working on this in #16655.
