### ISSUE TITLE
[BUG] Error with batched multi-source JSON read with >1 MB per row

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#16664]
**Describe the bug**
When reading JSONL files in a >2 GB list of sources, and when the files contain very large lines (>5MB), we observe a crash in the reader throwing `CUDA_ERROR_INVALID_VALUE`. This error is due to an issue in the multi-source batch processing algorithm that does not correctly process large lines.

**Steps/Code to reproduce bug**

This kind of multi-source read can fail. The issue was observed with average characters per line is 500K and the maximum characters per line of >10 MB.
```
import cudf
import os
data_path = **redacted**
files = sorted(list(map(lambda x: os.path.join(data_path,x),os.listdir(data_path)))) 
df = cudf.read_json(files, lines=True, engine="cudf") 
# fails with CUDA_ERROR_INVALID_VALUE(invalid argument)')
```
Please note: We will replace this with a public repro as time permits.

**Comment by shrshi** [comment]
Closing with the merge of #16687
