### ISSUE TITLE
[FEA] Add libcudf cudf::get_current_device_resource() wrapper for rmm::get_current_device_resource()

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#16676]
**Is your feature request related to a problem? Please describe.**
I'm about to undertake yet another change to every function in libcudf that takes an MR parameter. To prevent doing this too many times in the future, I would like to provide a wrapper in libcudf to centralize calls to `rmm::get_current_device_resource[_ref]()` and an alias for RMM `resource_ref` type. hopefully this can reduce the number of files that need to change in the future when this functionality changes (e.g. if it moves out of RMM to CCCL).

**Describe the solution you'd like**
A header, say `cpp/include/cudf/utilities/memory_resource.hpp`. Please provide suggestions on the best place for this. Contents something like this:

```
namespace cudf {

using device_async_resource_ref = rmm::device_async_resource_ref;

inline device_async_resource_ref get_current_device_resource_ref() {
  return rmm::get_current_device_resource_ref();
}

inline device_async_resource_ref set_current_device_resource_ref(device_async_resource_ref mr) {
  return rmm::set_current_device_resource_ref(mr);
}

inline device_async_resource_ref reset_current_device_resource_ref() {
  return rmm::reset_current_device_resource_ref();
}
```

**Describe alternatives you've considered**

**Additional context**
https://github.com/rapidsai/rmm/pull/1598

**Comment by vyasr** [comment]
I would be in favor of this as being something analogous to our wrappers for default stream handling.
