### ISSUE TITLE
[FEA] Support JNI build in rapids dev container

### ISSUE THREAD

**Issue by pxLi** [rapidsai/cudf#16686]
**Is your feature request related to a problem? Please describe.**
Request from @harrism to support cudf JNI with in rapids dev container
https://github.com/rapidsai/cudf/tree/branch-24.10/.devcontainer

**Describe the solution you'd like**
not sure since I have no experience for it. Could try port existing build environment https://github.com/rapidsai/cudf/tree/branch-24.10/java
to dev container and provide a step by step instructions.

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by vyasr** [comment]
@harrism made the same request in https://github.com/rapidsai/devcontainers/issues/268. I'll close this request in favor of that one since the changes need to happen in the devcontainer repo, not here.

**Comment by harrism** [comment]
I forgot about that!
