### ISSUE TITLE
[FEA] Increase the default thread count for kvikIO file reads

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#16718]
**Is your feature request related to a problem? Please describe.**
For hot-cache files, we can increase the IO throughput with a multi-threaded kvikIO read.

**Describe the solution you'd like**

We should increase the number of threads in kvikIO file reads in libcudf. You can see this effect when using kvikIO on a hot cache file data source (which is a pageable host buffer pretending to be a file), where with 8 threads we get to utilization of 80-90% and throughput of 50 GB/s. I suggest trying a behavior where we use up to 8 threads depending on the size of the file and the default task size. For example, with a task size of 4 MiB, we might use 1 thread for 0-8MiB, two threads for 8-16 MiB, etc up to 8 threads. 

We may need to add new plumbing to let us change the kvikIO threadcount per read operation.

![Image](https://github.com/user-attachments/assets/f0948a90-4669-4d10-9f46-5c08f529a02d)

**Additional context**
A multi-threaded copy would be great for single-threaded tools like `cudf.pandas` and could give 3-4x faster IO operations.

**Comment by abellina** [comment]
I believe that a staged copy strategy with a pinned bounce buffer will be helpful, from the standpoint of pinned memory management. We can see a similar pattern D2H for shuffle, where we have to (today) hold on to pinned memory while we write to the file system, which often is CPU bound due to compression. 

I would hope a MT copy strategy could be general and we can use it H2D and D2H.

**Comment by GregoryKimball** [comment]
Thank you @abellina for this feedback. @kingcrimsontianyu and I did some benchmarking and found good results from increasing the thread count.

```
./PARQUET_READER_NVBENCH  -d 0 -b 1 --profile -a cardinality=0 -a run_length=1
KVIKIO_NTHREADS=8 ./PARQUET_READER_NVBENCH  -d 0 -b 1 --profile -a cardinality=0 -a run_length=1
```

For this benchmark and the `FILEPATH` datasource, going from 1->8 threads on x86-H100 yielded 141 ms to 74 ms. On GH200 the difference was 100 ms to 67 ms.

[I am opening an issue in kvikIO about MT memcpy and will update here]

**Comment by GregoryKimball** [comment]
I would like to rescope this issue to focus on increasing the number of threads in kvikIO file reads in libcudf. I suggest trying a behavior where we use up to 8 threads depending on the size of the file and the default task size. For example, with a task size of 4 MiB, we might use 1 thread for 0-8MiB, two threads for 8-16 MiB, etc up to 8 threads.

**Comment by GregoryKimball** [comment]
@ayushdg noted that `KVIKIO_NTHREADS` could also impact performance on other file-like data sources like network-attached, Lustre, slurm and others.

**Comment by ayushdg** [comment]
Following up on this, looks like setting `KVIKIO_NTHREADS=8` impacts performance negatively on data high performance network filesystem like `lustre` based on internal testing.
