### ISSUE TITLE
[FEA] Consider supporting `extract_datetime_component` in libcudf

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#16735]
I would like to use [this datetime component enum](https://github.com/rapidsai/cudf/blob/fa1486e1d1d09116d2b5f57dfef7d9307ebc76c6/cpp/src/datetime/datetime_ops.cu#L47) in some kind of function with a signature like the following:

```c++
std::unique_ptr<column> extract_datetime_component(column_view const &column, datetime_component component) { }
```

This would help push a little messy logic in the [cudf cython code](https://github.com/rapidsai/cudf/blob/fa1486e1d1d09116d2b5f57dfef7d9307ebc76c6/python/cudf/cudf/_lib/datetime.pyx#L40) down into libcudf and hopefully fits the pattern of the rest of libcudf. I am happy to take this on if this seems like an agreeable change 👍

**Comment by davidwendt** [comment]
This sounds good to me. I would also like to consider removing the individual APIs in favor of this one if that make sense.

**Comment by bdice** [comment]
Should `extract`-with-enum accept multiple enum values (in a `cudf::host_span`), thereby allowing the extraction of multiple components into a `cudf::table` with a single kernel call?

That might help with some performance concerns we discussed in https://github.com/rapidsai/cudf/pull/16500#discussion_r1707922347.
