### ISSUE TITLE
[BUG] JSON string with certain UTF-8 data fails to tokenize fully

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#16741]
**Describe the bug**
JSON tokenizer does not output after UTF-8 character upto  `u000F`. 

**Steps/Code to reproduce bug**
Repro code:
```cpp
TEST_F(JsonReaderTest, ValidationTestda)
{
  std::string data = 
    "{\"a\": 3.4}\n {\"a\": \"A\u0000B\"}\n {\"a\": \"A\\u0000B\"}\n";

  cudf::io::json_reader_options in_options =
    cudf::io::json_reader_options::builder(cudf::io::source_info{data.data(), data.size()})
      //  .recovery_mode(cudf::io::json_recovery_mode_t::RECOVER_WITH_NULL)
      .lines(true);
  cudf::io::table_with_metadata result = cudf::io::read_json(in_options);

  cudf::test::print(result.tbl->get_column(0));
  // num_rows
  std::cout<<  result.tbl->num_rows() <<"," <<result.tbl->get_column(0).null_count() << std::endl;

}
```

` {  < FB FE VB VE  >  }  {  < FB FE SB `
has only 2 rows.

**Expected behavior**
Expected tokens:
` {  < FB FE VB VE  >  }  {  < FB FE SB SE  >  }  {  < FB FE SB SE  >  } `
Expected 3 rows.

< is StructMemberBegin, SB is StringBegin.

**Additional context**
Issue found in one of java unit tests in PR https://github.com/rapidsai/cudf/pull/15968

**Comment by elstehle** [comment]
I think the issue here is that your example string contains a `null` character that simply terminates the string after `14` characters: `[...]\u0000B[...]` is `\u0000`, which is `\0`, followed by the character `B`. I assume you actually wanted to have `\u000B`?
> `std::string data = 
    "{\"a\": 3.4}\n {\"a\": \"A\u0000B\"}\n {\"a\": \"A\\u0000B\"}\n";`

Let me know if you still encounter issues with the tokenizer, otherwise feel free to close the issue.

**Comment by karthikeyann** [comment]
Not a bug. No issue after replacing C Str string with string literal that can hold `\0`.  
closing the issue.
