### ISSUE TITLE
[BUG] cudf.pandas fallback fails with read_csv due to columns being strings

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#16766]
**Describe the bug**
Reading a CSV file with `header=None` produces integer column names in pandas, so you can access the columns like `df[0]`. However, cudf only supports string column names, so `read_csv` gives different types for the columns (`str` rather than `int`). Thus, accessing the data like `df[0]` breaks in both cudf and pandas fallback. It fails during fall back to pandas because the original cudf object had string column names.

**Steps/Code to reproduce bug**

```bash
#!/bin/bash

cat << EOF > test.csv
1
2
3
EOF

cat << EOF > test.py
import pandas as pd
df = pd.read_csv("test.csv", header=None)
print(df)
df[0]  # Fails because cudf reads with string keys like df["0"] but pandas uses integers
EOF

python -m cudf.pandas test.py
```

**Expected behavior**
pandas code works without changes in cudf.pandas.

**Additional context**
A workaround is to use `df.iloc[:, 0]` or `df[df.columns[0]]` instead of `df[0]`. This gets "the first column" rather than indexing by a column name.

Discussed with @Matt711 and @puririshi98. This causes failures in code paths like this one in OGB: https://github.com/snap-stanford/ogb/blob/f631af76359c9687b2fe60905557bbb241916258/ogb/io/read_graph_raw.py#L34-L35

**Comment by bdice** [comment]
xref: https://github.com/snap-stanford/ogb/pull/489

**Comment by mroeschke** [comment]
Looks like we do some post-processing from the CSV reader when `names` is passed

```python
    if names is not None and len(names) and isinstance(names[0], (int)):
        df.columns = [int(x) for x in df._data]
```

So I suppose we can do the same when `header=None` and in `mode.pandas_compatable`
