### ISSUE TITLE
[FEA] `drop_first` in `to_dummies`

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#16791]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to pass `drop_first` to `to_dummies`

**Describe the solution you'd like**
```
cudf.get_dummies(cudf.Series(list('abcaa')), drop_first=True)
```

**Describe alternatives you've considered**

**Additional context**

For usage in Narwhals (we're currently having to xfail a cuDF test for this https://github.com/narwhals-dev/narwhals/pull/945/files)

**Comment by mroeschke** [comment]
Thanks for the request! Opened up https://github.com/rapidsai/cudf/pull/16795 to support this keyword.
