### ISSUE TITLE
[BUG] Requested types ignored if prune_schema is enabled for JSON reading

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#16797]
**Describe the bug**
I noticed this in some unit tests for the java APIs when I tried to enable schema pruning in CUDF by default for java JSON read APIs that explicitly do column pruning. 

   * https://github.com/rapidsai/cudf/blob/0b32f55b1ed38507437770d21da1e4e1a1c4a17d/java/src/test/java/ai/rapids/cudf/TableTest.java#L664-L714 which fails because column `d` is being returned as a `LIST<INT8>` instead of a `LIST<INT64>` which is what it was requested to be, and which is what is returned for column `d` if pruning is disabled.
   * https://github.com/rapidsai/cudf/blob/0b32f55b1ed38507437770d21da1e4e1a1c4a17d/java/src/test/java/ai/rapids/cudf/TableTest.java#L743-L790 is failing for the same reason as the above one. column `d` is the wrong type.
   * https://github.com/rapidsai/cudf/blob/0b32f55b1ed38507437770d21da1e4e1a1c4a17d/java/src/test/java/ai/rapids/cudf/TableTest.java#L716-L741 is failing because column `e` was requested to be a `LIST<STRUCT>`, but it was returned as a `LIST<INT8>` column. 

**Steps/Code to reproduce bug**
If you want to reproduce this you can take https://github.com/rapidsai/cudf/pull/16796 and enable column pruning for the tests that are listed as failing. The third test is the scariest one, and it appears to return totally invalid results where the data column is empty despite the there being offsets pointing into it. 

If I need to create a C++ repro case I am happy to do it

**Expected behavior**
I would expect the types in the schema to be honored at least in the same way that it is for the non pruning use case.

**Comment by revans2** [comment]
I think this is fixed if the experimental feature is enabled.

**Comment by ttnghia** [comment]
Recent changes in JNI always enable prune column by default if there is a schema given. Thus, this is already fixed.
