### ISSUE TITLE
[FEA] Support datetime64[D]

### ISSUE THREAD

**Issue by nghiadt22** [rapidsai/cudf#16803]
**Describe the solution you'd like**
please let cudf to support datetime64[D].

**Describe alternatives you've considered**
I had to convert my datetime to integer for filter and etc.

**Comment by mroeschke** [comment]
Thanks for the request. Just to understand your use case, do you regularly work with dates before 2.9e11 BC or after 2.9e11 AD? 

For reference, pandas 2.0 also does not support `datetime64[D]`. The largest precision cudf supports is `datetime64[s]` which matches pandas and allows dates representable between `[2.9e11 BC, 2.9e11 AD]`

**Comment by nghiadt22** [comment]
Thanks @mroeschke. I got around my problem pretty easily by converting my string dates formatted as "yyyymmdd" into numbers for comparison. 

That's all I wanted: to compare my dates. 

I just thought that it'd enable more options for the user since cudf's supported data format becomes more granular.
However, I understand that cudf is intertwined with pandas so this feature is only valuable when both libs work.
So, from your POV, is it worth it? Please let me know what you think.

**Comment by mroeschke** [comment]
>  However, I understand that cudf is intertwined with pandas so this feature is only valuable when both libs work.

Not necessarily; one could use cudf independently of pandas and cudf _could_ support day resolution datetime type. But a day resolution type is functionally equivalent to other resolutions (i.e. "compare your dates" will work with any resolution); the only difference is that day resolution can represent a wider range of dates.

So for the team to consider implementing this feature, there needs to be a demand/use case to store dates beyond `[2.9e11 BC, 2.9e11 AD]`

**Comment by nghiadt22** [comment]
> >  However, I understand that cudf is intertwined with pandas so this feature is only valuable when both libs work.
> 
> Not necessarily; one could use cudf independently of pandas and cudf _could_ support day resolution datetime type. But a day resolution type is functionally equivalent to other resolutions (i.e. "compare your dates" will work with any resolution); the only difference is that day resolution can represent a wider range of dates.
> 
> So for the team to consider implementing this feature, there needs to be a demand/use case to store dates beyond `[2.9e11 BC, 2.9e11 AD]`

I see. Thank you for your effort and promptly feedback. I'll close this request.
