### ISSUE TITLE
[BUG] Could not find wheels

### ISSUE THREAD

**Issue by Rishit-dagli** [rapidsai/cudf#16804]
**Describe the bug**

I thought there were wheels for this configuration but for some reason I still see that wheels are not compatible.

**Expected behavior**

I would expect the wheels for this configuration to work well.

```
Looking in indexes: https://pypi.org/simple, https://pypi.nvidia.com
Collecting cudf-cu11==24.8.*
  Using cached cudf_cu11-24.8.2.tar.gz (2.6 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [57 lines of output]
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp310-cp310-manylinux_2_28_aarch64.whl against tag cp310-cp310-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp310-cp310-manylinux_2_28_x86_64.whl against tag cp310-cp310-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp311-cp311-manylinux_2_28_aarch64.whl against tag cp311-cp311-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp311-cp311-manylinux_2_28_x86_64.whl against tag cp311-cp311-manylinux_2_28_x86_64
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp39-cp39-manylinux_2_28_aarch64.whl against tag cp39-cp39-manylinux_2_28_aarch64
      INFO:nvidia-stub:Testing wheel cudf_cu11-24.8.2-cp39-cp39-manylinux_2_28_x86_64.whl against tag cp39-cp39-manylinux_2_28_x86_64
        File "/tmp/pip-build-env-hmfak5ri/overlay/lib/python3.10/site-packages/nvidia_stub/wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/tmp/pip-build-env-hmfak5ri/overlay/lib/python3.10/site-packages/nvidia_stub/wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      Traceback (most recent call last):
        File "/tmp/pip-build-env-hmfak5ri/overlay/lib/python3.10/site-packages/nvidia_stub/wheel.py", line 177, in download_wheel
          return download_manual(wheel_directory, distribution, version)
        File "/tmp/pip-build-env-hmfak5ri/overlay/lib/python3.10/site-packages/nvidia_stub/wheel.py", line 144, in download_manual
          raise RuntimeError(f"Didn't find wheel for {distribution} {version}")
      RuntimeError: Didn't find wheel for cudf-cu11 24.8.2
```

**Environment overview (please complete the following information)**

Python Version: CPython 3.10.12
Operating System: Linux 5.4.0-150-generic
CPU Architecture: x86_64
Driver Version: 525.105
CUDA Version: 12.0

**Additional context**

**Comment by bdice** [comment]
I was unable to reproduce this with `pip install --extra-index-url=https://pypi.nvidia.com cudf-cu11==24.8.*`. It seems like your system is falling back to the `nvidia-stub` package because it can't find a matching wheel, so there may be something about your system that is unsupported. Can you do a few things to help us diagnose this?

- What install command did you run? Did you get it from https://docs.rapids.ai/install?
- What Linux OS are you using (looking for something like Ubuntu 22.04, not just the kernel version)?
- Can you also share the output of `ldd --version`?
- Double-check the Python version, CPU arch, and CUDA version are correct in your issue above.

**Comment by Rishit-dagli** [comment]
- yes, the pip command from this page

```
pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu11==24.8.* dask-cudf-cu11==24.8.* cuml-cu11==24.8.* \
    cugraph-cu11==24.8.* cuspatial-cu11==24.8.* cuproj-cu11==24.8.* \
    cuxfilter-cu11==24.8.* cucim-cu11==24.8.* pylibraft-cu11==24.8.* \
    raft-dask-cu11==24.8.* cuvs-cu11==24.8.*
```

- ah, yes: `Ubuntu 18.04.6 LTS`
- i think i understand what you are getting at: my glibc is `ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27`, and i assume the wheels require 2.28?
- yes, so these were taken from the error trace, the correct ones should be (i think the installation got it wrong since it's an hpc system with all versions of cuda installed, i was able to set the correct `CUDA_HOME` which identifies the correct cuda version):

```
Python Version: CPython 3.10.12
Operating System: Linux 5.4.0-150-generic
CPU Architecture: x86_64
Driver Version: 525.105
CUDA Version: 11.8
```

**Comment by bdice** [comment]
Thanks. Yes, RAPIDS wheels require glibc 2.28 or higher, which is not met by your system. We deprecated support for Ubuntu 18.04 several releases ago (see [RAPIDS Support Notice 24](https://docs.rapids.ai/notices/rsn0024/)) and now require Ubuntu 20.04 or higher.

You may be able to install RAPIDS 24.04, which still supported glibc 2.17 (old enough to include support for Ubuntu 18.04).

**Comment by Rishit-dagli** [comment]
thanks i saw the wheel metadata and i did not realise the `2_28` was the `glibc` version.

if it helps someone else, i ended up running (which worked):

```sh
pip install \
    --extra-index-url=https://pypi.nvidia.com \
    cudf-cu11==24.04 dask-cudf-cu11==24.04 cuml-cu11==24.04 \
    cugraph-cu11==24.04 cuspatial-cu11==24.04 cuproj-cu11==24.04 \
    cuxfilter-cu11 cucim-cu11==24.04 pylibraft-cu11==24.04 \
    raft-dask-cu11==24.04 cuvs-cu11==24.04
```
