### ISSUE TITLE
[FEA] Expand CUDF_EXPECTS to allow an optional exception type.

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1682]
Currently, `CUDF_EXPECTS` can only throw a `cudf::logic_error`. IMHO, it should be able to throw other errors, like `invalid_argument` for example. So, I propose the `CUDF_EXPECTS` macro be changed from
```
#define CUDF_EXPECTS(cond, reason)
```
to
```
#define CUDF_EXPECTS(cond, exception_type, reason)
```
and perhaps we add something like
```
#define CUDF_LOGIC_EXPECTS(cond, reason)
```
which throws a `logic_error`.

**Comment by harrism** [comment]
CUDF_EXPECTS is already used heavily, so your suggested change would be a big effort. I think instead we should modify it to use VA_ARGS and make the exception type an optional third parameter.

**Comment by eyalroz** [comment]
@harrism :
Ah, a macro-writing challenge. Ok, apparently one _can_ sort-of overload on the number of macro arguments. How about this? :
```
+#define CUDF_EXPECTS(...) GET_CUDF_EXPECTS_MACRO(__VA_ARGS__, CUDF_EXPECTS_3, CUDF_EXPECTS_2)(__VA_ARGS__)
#define GET_CUDF_EXPECTS_MACRO(_1,_2,_3,NAME,...) NAME
#define CUDF_EXPECTS_3(_condition, _exception_type, _what) \
 (!!(_condition))                                          \
       ? static_cast<void>(0)                              \
      : throw _exception_type("At " __FILE__ ":" CUDF_STRINGIFY(__LINE__) ": " _what)
#define CUDF_EXPECTS_2(_condition, _reason) CUDF_EXPECTS_3(_condition, cudf::logic_error, _reason)
#define CUDF_LOGIC_EXPECTS(_condition, _reason) CUDF_EXPECTS_2(_condition, _reason)
```

**Comment by harrism** [comment]
That does the opposite of what I suggested. I asked that the interface for CUDF_EXPECTS not change, since that would affect a lot of existing code.  I honestly don't think there's a big issue with CUDF_EXPECTS today, and this issue just feels like make-work.

**Comment by eyalroz** [comment]
@harrism : It's not a big issue, it's a minor issue. But - what I suggested means all existing calls remain valid.
