### ISSUE TITLE
[FEA] Unified memory for Polars GPU Engine

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#16850]
We now use [unified memory + prefetching](https://developer.nvidia.com/blog/rapids-cudf-unified-memory-accelerates-pandas-up-to-30x-on-large-datasets/) by default for cuDF Pandas, which has materially improved the user experience while still providing large speedups to workflows -- particularly on the lower-memory GPUs where users are frequently trying to process e.g., 5-20GB datasets.

In contrast, users of the Polars GPU engine are currently at high risk of experiencing out-of-memory errors when processing the medium-sized datasets for which they're hoping accelerated computing can help them handle.

A brief series of ad-hoc investigations exploring UVM for Polars on [PDS-H](https://github.com/pola-rs/polars-benchmark) on 100-200GB datasets on higher-memory GPUs like the A100 and H100 have showed promise but run into some performance challenges in selected scenarios. We should formalize this investigation to target enabling UVM for the Polars GPU engine.

**Comment by wence-** [comment]
This is now on by default in 24.12, so I think we can close?

**Comment by vyasr** [comment]
Yes, this was resolved by #17375
