### ISSUE TITLE
[FEA] Support reading multi-file Parquet (was: Reader throws Error "No such file or directory")

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#1688]
**Procedure:**
1. read a csv with dask as dask dataframe.
2. use to parquet to write the dataframe as parquet files.
3. now read the parquet file parquet reader.

**Code**
import dask.dataframe as dd
df = dd.read_csv('df-0.csv')
df.repartition(npartitions=1)
df.to_parquet('df-0.parquet')
import cudf
df = cudf.read_parquet('df-0.parquet')
[df-0.csv.zip](https://github.com/rapidsai/cudf/files/3159384/df-0.csv.zip)

I am able to read this file using dask. but reading with cudf throws this error.

**Branch Info**
Issue detected in cudf/branch-0.7

**Comment by ayushdg** [comment]
Hi @mlahir1. At this step `df.to_parquet('df-0.parquet')` dask creates a folder with two files. One containing metadata info and the other containing the actual parquet file. For your particular example changing this path to `df = cudf.read_parquet('df-0.parquet/part.0.parquet')` should not show you the error. 
For now cudf needs the path to the actual parquet file and cannot read from a folder. You could do something like this if you don't want to specify the filename:
```
import os
files = [fn for fn in os.listdir('df-0.parquet') if  fn.endswith('.parquet')]
```
This will give you the list of parquet files that you can read from the directory.

**Comment by OlivierNV** [comment]
We should keep track of this as a new feature for future releases. Parquet allows independent files per column chunk, but we currently do not support that (might be able to make it for 0.8)

**Comment by mlahir1** [comment]
Thanks @ayushdg This means If I have multiple parts in parquet file, I have to read all the parts separately and merge them together into a single DF.

**Comment by ayushdg** [comment]
@mlahir1 As of now that is what you can do with cudf. 
As @OlivierNV suggested it would be a good enhancement to the parquet reader if we can read multipart parquet files from a directory.

**Comment by OlivierNV** [comment]
@ayushdg Could you attach the zip file with the df-0.parquet directory that contains the multipart parquet files ?

**Comment by ayushdg** [comment]
@OlivierNV I have attached 3 zip files. One with a single partition Dask Dataframe writing to parquet. One with multiple partitions writing to parquet and one where a spark Dataframe writes to parquet. 
[dask_df_singlePartition.parquet.zip](https://github.com/rapidsai/cudf/files/3168377/dask_df_singlePartition.parquet.zip)
[spark_df.parquet.zip](https://github.com/rapidsai/cudf/files/3168378/spark_df.parquet.zip)
[dask_df_multiPartition.parquet.zip](https://github.com/rapidsai/cudf/files/3168379/dask_df_multiPartition.parquet.zip)

Snippet for dask if you want to change anything around:
```
import dask.dataframe
import dask
import pandas as pd
import numpy as np

df = pd.DataFrame()
n_elem = 10000
nparts = 10
df['a'] = np.arange(n_elem)
df['b'] = np.random.random(n_elem)
df['c'] = ['str1', 'str2']*(int)(n_elem/2)
df['d'] = [True,False]*(int)(n_elem/2)
df['e'] = [np.datetime64('2019-03-28 18:00:00')]*n_elem
ddf = dask.dataframe.from_pandas(df,npartitions=nparts)
ddf.to_parquet('df.parquet')
```

**Comment by OlivierNV** [comment]
Hmm. It looks like none of these files are using the multi-file capability of parquet: just storing individual parquet files for pieces of a dataframe with an arbitrary "part-NNNN*" file naming convention. Handling this would be easier in the python layer (just multiple calls to read_parquet), but it would be more efficient built into the parquet reader if we want all fragments in a single dataframe on a single gpu.

**Comment by harrism** [comment]
I'm going to change this to a feature request.

**Comment by weiji14** [comment]
Using `engine="pyarrow"` instead of the default `engine="cudf"` seems to work, but it involves reading into the CPU first:

```python
df = cudf.read_parquet(path="df.parquet", engine="pyarrow")
```

This is the traceback warning on cudf 0.15.0a+4631.g68af93d98 nightly build.

```python-traceback
/home/user/miniconda3/envs/cudf/lib/python3.8/site-packages/cudf/io/parquet.py:217: UserWarning: Using CPU via PyArrow to read Parquet dataset.
  warnings.warn("Using CPU via PyArrow to read Parquet dataset.")
```

**Comment by vuule** [comment]
This should now be addressed by https://github.com/rapidsai/cudf/pull/6815.
`df = cudf.read_parquet(path="dir/*.parquet", engine="cudf")` should work as expected.
Please reopen if the feature is not sufficient as currently implemented
