### ISSUE TITLE
[FEA] Add JSON reader column projection example

### ISSUE THREAD

**Issue by GregoryKimball** [rapidsai/cudf#16959]
**Is your feature request related to a problem? Please describe.**
Using the libcudf reader with large JSON lines records, and only extracting a few fields, is a common use case.

Let's add a libcudf example to make it easier to profile this kind of work.

**Describe the solution you'd like**

The example could:
* accept a JSON lines filename as a CLI parameter
* read the JSON lines file
* accept a number of "fields requested" as a CLI parameter
* randomly select a subset of fields, create a new reader options and read the JSON lines file again
* accept a "repetitions" CLI parameter and repeat the field selection and file read as requested

**Additional context**
We might want to randomly choose between all parent and child columns... is this hard to do?

**Comment by GregoryKimball** [comment]
We are going to close this for now in favor of adhoc python scripts

**Comment by karthikeyann** [comment]
Path of the python script 
https://github.com/karthikeyann/cudf/blob/enh-profile_memusage_json/wm_benchmark.py
Optional arguments:
-n num_columns (number of columns to prune 0-57, default -1 is all 57)
-p data_path (path to parquet files)
