### ISSUE TITLE
[BUG] some pytest configurations not used

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#16974]
**Describe the bug**
Since #16851, all python packages have a `pytest.ini` in `package/tests/`. However, some of the packages previously had pytest-specific configuration in the `pytest.tool.ini-options` section of `pyproject.toml`. These settings are now ignored (as per https://docs.pytest.org/en/8.2.x/reference/customize.html#finding-the-rootdir).

We should pick a single configuration file that is used (and recommended in the dev guide).

FWIW, my preference is for pyproject.toml, since that's where all the other tool-specific config is going.

**Comment by vyasr** [comment]
The general consensus when discussing this was that we all prefer pyproject.toml here.
