### ISSUE TITLE
[DOC] Elaborate dataset size vs hardware requirements

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#17095]
## Report needed documentation

**Report needed documentation**
Hardware requirements for cuDF Pandas could be more explicit. Developers should expect to have 3x the size of their dataset in GPU VRAM to take advantage of the accelerated processing. Hardware requirements are currently not elaborated on in the documentation.

**Comment by bdice** [comment]
@galipremsagar Please see #16693 and #16869 for related discussions. It is important for users to know that the choices of algorithms, data types, file formats, and more can affect the hardware requirements. Requiring VRAM that is 3x the data size is a very rough rule of thumb, but that multiple can vary a lot (some algorithms require 5x or more) and is also impacted by cudf.pandas' use of unified memory and prefetching to expand the upper bounds of acceleration.

**Comment by vyasr** [comment]
I'm going to close this as addressed by the PRs mentioned above.
