### ISSUE TITLE
[FEA] dt.date (mirror pyarrow-backed pandas behaviour)

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#17174]
**Is your feature request related to a problem? Please describe.**

pandas with pyarrow-backed dtypes supports this - would you consider adding this to cudf now?
```python
>>> pd.Series([datetime(2020,1,1)]).convert_dtypes(dtype_backend='pyarrow').dt.date
0    2020-01-01
dtype: date32[day][pyarrow]
```

**Describe the solution you'd like**
`.dt.date()` to return a Series of dtype `'Date'`

**Describe alternatives you've considered**

This was discussed and rejected in https://github.com/rapidsai/cudf/issues/7880, but now with it being supported properly in pandas (i.e. not returning a numpy array), maybe you can reconsider?

use-case: we're x-failing some tests for cudf in Narwhals because of this

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by mroeschke** [comment]
Like what was recently stated on the issue you linked https://github.com/rapidsai/cudf/issues/7880#issuecomment-2448721567 I would also support adding a date type eventually. Since that issue was reopened let's consolidate discussion to that issue.

**Comment by vyasr** [comment]
Whoops I apologize for not realizing there were duplicates coming up here, thanks for consolidating Matt.
