### ISSUE TITLE
[BUG] DataFrame.from_records is reporting 'numpy.float64' has no len()

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1722]
**Describe the bug**
Hi,

I think I have found a bug when running the following code:

```
import numpy as np
import cudf
a = np.random.uniform(-10,10,size=100000)

print(a)
print(type(a))
print(a.size)

b = cudf.DataFrame.from_records(a)
```

![image](https://user-images.githubusercontent.com/26169771/57650980-71879580-75cc-11e9-924a-c13c16fdfd46.png)

**Steps/Code to reproduce bug**
Run the code above using the latest RAPIDS container (v0.7).

**Expected behavior**
A dataframe is created from the numpy.ndarray.

**Environment details (please complete the following information):**
DGX-1
Latest RAPIDS v0.7 container.
 

**Additional context**

**Comment by kkraus14** [comment]
`cudf.DataFrame.from_records` expects a numpy recaarray: https://docs.scipy.org/doc/numpy/reference/generated/numpy.recarray.html, not a numpy ndarray.

**Comment by miguelangel** [comment]
Hi @kkraus14,

Ups! My bad!

Nevertheless, I have tried to convert the numpy ndarray to recarray, and it seems to be failing yet. Am I missing something?

```
import numpy as np
import cudf
a = np.random.uniform(-10,10,size=100000)

print(a)
print(type(a))
print(a.size)

b = a.view(np.recarray)
print(type(b))

c = cudf.DataFrame.from_records(b)
```

![image](https://user-images.githubusercontent.com/26169771/57680512-16868a80-762e-11e9-99bf-ee09f8a4d503.png)

Regards,
Miguel

**Comment by kkraus14** [comment]
@miguelangel thanks for the troubleshooting, redefined as a bug, thanks!

**Comment by kkraus14** [comment]
Seems like Pandas can't handle this object either:
```
In [30]: pd.DataFrame.from_records(b)                                                                                                      
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-b11b4310d5c8> in <module>
----> 1 pd.DataFrame.from_records(b)

~/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/pandas/core/frame.py in from_records(cls, data, index, exclude, columns, coerce_float, nrows)
   1504 
   1505         elif isinstance(data, (np.ndarray, DataFrame)):
-> 1506             arrays, columns = to_arrays(data, columns)
   1507             if columns is not None:
   1508                 columns = ensure_index(columns)

~/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/pandas/core/internals/construction.py in to_arrays(data, columns, coerce_float, dtype)
    422     else:
    423         # last ditch effort
--> 424         data = lmap(tuple, data)
    425         return _list_to_arrays(data, columns, coerce_float=coerce_float,
    426                                dtype=dtype)

~/miniconda3/envs/cudf_dev/lib/python3.6/site-packages/pandas/compat/__init__.py in lmap(*args, **kwargs)
    130 
    131     def lmap(*args, **kwargs):
--> 132         return list(map(*args, **kwargs))
    133 
    134     def lfilter(*args, **kwargs):

TypeError: 'numpy.float64' object is not iterable
```

It looks like you're generating a 1d array and when viewing it as a record array it still stays as a 1d array instead of a 2d array. Given it doesn't work in Pandas either and it's a very extreme edge case I'm going to say this is a wontfix situation and that raising an exception is the right behavior.
