### ISSUE TITLE
[FEA] Implementing `__array_wrap__`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#1724]
**Is your feature request related to a problem? Please describe.**

NumPy `ufunc`-like functions leverage `__array_wrap__` instead of `__array_ufunc__`. It would be nice to be able to use these functions out-of-the-box on `DataFrame` and `Series` classes.

Note: This is something that [Pandas implements currently]( https://github.com/pandas-dev/pandas/search?q=__array_wrap__&unscoped_q=__array_wrap__ ).

**Describe the solution you'd like**

To support use of them with cuDF, it would help to have an `__array_wrap__` method for `DataFrame` and `Series` classes.

**Describe alternatives you've considered**

We might be able to bypass this completely by implementing `__array_function__`, but that may take more work than adding `__array_wrap__` (even if that is our end solution).

Alternatively we could try to convince NumPy to convert `ufunc`-likes to actual `ufunc`s. Though their (reasonable) response has been to implement `__array_function__` instead.

**Comment by jakirkham** [comment]
Have also opened issue ( https://github.com/rapidsai/cudf/issues/1728 ) on the `__array_function__` protocol. This is a newer protocol that NumPy provides and a few libraries support, but Pandas does not yet support. There is probably value to both approaches, but it is likely `__array_function__` will overtake `__array_wrap__` in the long run.

**Comment by kkraus14** [comment]
We have implemented `__array_function__` so going to close this.

**Comment by jakirkham** [comment]
Thanks Keith! 😄
