### ISSUE TITLE
[BUG] JSON parser still returns outdated schema structure for strings column

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#17240]
Previously, strings columns have two children: `offsets` and `chars`. As such, JSON parsers return this schema:
```
      // For string columns return ["offsets", "char"] schema
      if (target_type.id() == type_id::STRING) {
        return {std::move(col), std::vector<column_name_info>{{"offsets"}, {"chars"}}};
      }
```

However, recent changes in cudf have removed the `chars` child column, leaving only the `offsets` child remaining. We should update JSON parser to return the proper schema.

**Comment by karthikeyann** [comment]
@mhaseeb123 is already looking into this for all io formats. (especially parquet format and arrow).

**Comment by mhaseeb123** [comment]
Notes from investigating Parquet and Arrow formats for strings columns.

- Looks like Parquet format expects zero children for strings columns. [Ref](https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/schema.cc#L344)
- It also looks like `arrow::Schema` also expects zero children for String columns [Ref](https://github.com/apache/arrow/blob/main/cpp/src/parquet/arrow/schema.cc#L792). That being said, Arrow does implement string columns as `StringArray` and use separate `Buffer`s for `offsets, data, and (opt) validity bitmap`.
