### ISSUE TITLE
[FEA] Implement `Series.searchsorted`

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1727]
See: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.searchsorted.html

This the only known major building block needed for dask-cudf sorting.

@harrism Would love your feedback as to if https://github.com/rapidsai/cudf/pull/1428 suffices for this.

**Comment by harrism** [comment]
Not going to make it for 0.8, sorry.
