### ISSUE TITLE
[FEA] Add Google Bench for libcudf microbenchmarks

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1729]
**Is your feature request related to a problem? Please describe.**
libcudf currently lacks any facility for doing micro-benchmark testing of key performance metrics. 

**Describe the solution you'd like**
Add [Google Bench](https://github.com/google/benchmark) for adding micro-benchmarks of libcudf code. 

**Additional context**
Ideally, Google Bench benchmarks can then be tied into ASV.

**Comment by devavret** [comment]
Is this fixed by #1998?

**Comment by jrhemstad** [comment]
> Is this fixed by #1998?

Yep!
