### ISSUE TITLE
[BUG] Transpose should support StringIndex

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1731]
**Describe the bug**
Now that we have a string index, we should update `transpose` to support this to be consistent with pandas.

```
import pandas as pd
import cudf
sample = cudf.DataFrame({'a':[1,2,3], 'b':[4,5,6]})
psample = sample.to_pandas()

print(sample)
print(sample.T)
print(psample.T)
   a  b
0  1  4
1  2  5
2  3  6
   0  1  2
0  1  2  3
1  4  5  6
   0  1  2
a  1  2  3
b  4  5  6
```

**Comment by shwina** [comment]
This is addressed as part of #1622

**Comment by beckernick** [comment]
Thanks @shwina . Can you update that PR description to reflect that it will close #1731 ?

**Comment by beckernick** [comment]
Resolved by #1622.

**Comment by shwina** [comment]
Not resolved

**Comment by shwina** [comment]
Appears to be resolved after all
