### ISSUE TITLE
[BUG] MultiIndex does not support as_column

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1738]
**Describe the bug**
As noted in rapidsai/dask-cudf#125, MultiIndex's lack of `as_column` is causing multi-column groupbys in dask-cudf to fail when `npartitions > 1`. @thomcom has identified that this occurs only in the case where there are multiple partitions that need to be combined.

Please see rapidsai/dask-cudf#125 for more discussion and a reproducible example.

**Comment by thomcom** [comment]
This should be fixed in 0.7.0 and 0.8.0 from https://github.com/rapidsai/cudf/pull/1741, can you confirm or deny?

**Comment by beckernick** [comment]
This is resolved. Oversight not closing this when I closed the dask-cudf issue. Thanks.
