### ISSUE TITLE
[FEA] Update `gdf_*` type aliases to use fixed-width types

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1751]
**Is your feature request related to a problem? Please describe.**

libcudf currently uses machine dependent types for it's type aliases in `types.h`. See https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/include/cudf/types.h#L4

For example: `typedef char          gdf_bool8;`

This is problematic as we are relying on the width of these types to be a specific size throughout the source code, but the size of these types is not guaranteed by the standard. 

**Describe the solution you'd like**
Now that CFFI is gone, we should be using the standard, fixed-width types whose sizes are guaranteed, e.g., `int64_t` instead of `long long int`. 

Likewise, these type definitions should be moved from `types.h` to `types.hpp` and renamed from `gdf_*` to `cudf::*`.

**Comment by pradghos** [comment]
Observed `warning: invalid narrowing conversion` even though, its not build failure - 
```
cpp/src/utilities/device_atomics.cuh(955): warning: invalid narrowing conversion from "signed char" to "char"
```

**Comment by jrhemstad** [comment]
> Observed `warning: invalid narrowing conversion` even though, its not build failure -
> 
> ```
> cpp/src/utilities/device_atomics.cuh(955): warning: invalid narrowing conversion from "signed char" to "char"
> ```

Yeah, that looks like the same issue about the difference in `char` behavior on `x86` vs `POWER`. Using unambiguous, fixed-width types should resolve any warnings like these.

**Comment by harrism** [comment]
Moving to 0.9

**Comment by trevorsm7** [comment]
Submitted PR here https://github.com/rapidsai/cudf/pull/3029/

I left the old gdf_ types in place where they are used in the gdf_ structs/unions, but moved to the cudf:: types everywhere else. In both case, the numeric types now use stdint definitions.

**Comment by trevorsm7** [comment]
PR #3029 merged
