### ISSUE TITLE
[DOC] clarify safety of integer utils

### ISSUE THREAD

**Issue by wence-** [rapidsai/cudf#17539]
**Describe the bug**

Noticed while implementing saturating addition for rolling window work.

This is a minor thing, and I think all the usages in libcudf are safe anyway, but...

In `integer_utils.hpp` we have (for signed integers).

```c++
template <typename I>
constexpr I div_rounding_up_safe(std::integral_constant<bool, true>, I dividend, I divisor) noexcept
{
  auto quotient  = dividend / divisor;
  auto remainder = dividend % divisor;
  return quotient + (remainder != 0);
}
```

This doesn't work for `divisor == 0` (OK, fine). It also overflows for `divisor == -1` since `INT_MIN / -1` is undefined.

I think all the usages in libcudf are for dividing two positive integers, in which case it's probably fine.

**Comment by davidwendt** [comment]
This is an internal function so there is no binding contract here and 'safe' is a relative term.
Do you have a problem with the name? I don't think it is worth renaming perhaps.
Do you wish for a safer version that checks the conditions you mentioned?
How would you like to see this issue closed?

**Comment by wence-** [comment]
> How would you like to see this issue closed?

Probably just to document these edge cases.
