### ISSUE TITLE
[FEA] Python-level support for writing compressed JSON format

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#17564]
In order to save more memory, many customers want to output the jsonl.gz format after processed data. And the c++/cuda level feature https://github.com/rapidsai/cudf/pull/17323 is finished, so we need to implement a python-level interface.

**Comment by mroeschke** [comment]
Thanks for the report.

We're currently working though refactoring how options are passed though between libcudf and cudf Python (https://github.com/rapidsai/cudf/issues/17565 cc @Matt711 ), but after that that this shouldn't be too hard to pass though to `DataFrame/Series.to_json`
