### ISSUE TITLE
[FEA] Series.std(), Series.var() and similar in libcudf

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1762]
We should implement standard deviation, variance, and similar operations on series on the libcudf side with Python bindings. 

Consider Implementing for gdf_column as well as cudf::table, in case some operations can be reused across columns (e.g. the count() needed for mean(), std(),. etc.).

In addition to these two, we should look at what other similar aggregations can be handled in the same way. E.g. covariance?

This will also serve as an exploration of what common functionality of aggregations can be shared between column aggregations and groupby/rolling aggregations.

Pandas reference: 
Std() on series: http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.std.html?highlight=std#pandas.Series.std
std() on dataframe: http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.std.html?highlight=std#pandas.DataFrame.std
var() on series: http://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.var.html?highlight=var#pandas.Series.var

**Comment by kovaltan** [comment]
`Series.std()`, `Series.var()` call `NumericalColumn.mean_var()` and it is already computed by combination of `cudf::reduction(‘sum’)` and `cudf::reduction(sum_of_squares)`.

https://github.com/rapidsai/cudf/blob/d049217803caaa3346eae8f16200432b54e3a592/python/cudf/dataframe/numerical.py#L251-L258

Do we need this as a single function call?
Of course, it is possible to add new  reduction enum into `cudf::reduction`.

**Comment by harrism** [comment]
This is a question of how feature-complete we want libcudf to be... We have users of the C++ API who don't use the Python API. Hence this request.

**Comment by kovaltan** [comment]
> This is a question of how feature-complete we want libcudf to be... We have users of the C++ API who don't use the Python API. Hence this request.

Okay, understand.

**Comment by kovaltan** [comment]
Hi @harrism ,

What are the required combination of input and output dtypes for `mean`, `var`, `std`?
I assume: 

Required input dtypes : arithmetic types + cudf:bool8
Required output dtypes: arithmetic types 

Do we need cudf:bool8 and integer types for output dtypes?

**Comment by harrism** [comment]
Seems like output should only be floating point types? I can't see any way to get an integer result from `mean()` in pandas, for example, even with integer inputs.

@kkraus14 @randerzander do you have any requirements for data type support for `mean`, `var`, `std`?

**Comment by kkraus14** [comment]
> Seems like output should only be floating point types? I can't see any way to get an integer result from `mean()` in pandas, for example, even with integer inputs.
> 
> @kkraus14 @randerzander do you have any requirements for data type support for `mean`, `var`, `std`?

Float64 is the expected dtype of the output

**Comment by kovaltan** [comment]
@harrism 
Kraus pointed float64 is enough for python.
How about C++ interface? 
I'm implementing like this: `cudf::reduction(col, op=GDF_REDUCTION_STD, dtype=GDF_FLOAT64)`
Do we force `dtype=GDF_FLOAT64` for `STD`, `MEAN`, `VAR`? then throw exception if `dtype != GDF_FLOAT64`
Or accepts any dtype, but treat it as GDF_FLOAT64 in the function?

**Comment by harrism** [comment]
I think in C++ we should accept any convertible floating point type for the output of std, mean, or var.  E.g. if the input columns are float32, then it should be legal to request the result is float32.

If they request an int or non-arithmetic type, throw an exception with helpful `what()` string (e.g. "Unsupported output data type" or something).

**Comment by kovaltan** [comment]
Okay, I will use `std::is_floating_point`
Thanks,

**Comment by karthikeyann** [comment]
@harrism @kkraus14 
Pandas `Series` or `DataFrame` does not have _**dtype**_ kwarg in their interfaces of `min`, `max`, `sum`, `mean`, `var`, `std`. but these methods of `cudf.DataFrame` and `cudf.Series` has  _**dtype**_ kwarg.
Is this **_dtype_**  argument necessary for `cudf.DataFrame` and `cudf.Series` ?
