### ISSUE TITLE
[BUG] groupby.get_group raises KeyError

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#17650]
**Describe the bug**

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

```python
df = cudf.DataFrame({'b': [4,5], 'a': [1,2], 'c': [4,3]})
df.groupby(['b', 'c']).get_group((4, 4))

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[13], line 2
      1 df = cudf.DataFrame({'b': [4,5], 'a': [1,2], 'c': [4,3]})
----> 2 df.groupby(['b', 'c']).get_group((4, 4))

File /opt/conda/lib/python3.10/site-packages/cudf/utils/performance_tracking.py:51, in _performance_tracking.<locals>.wrapper(*args, **kwargs)
     43 if nvtx.enabled():
     44     stack.enter_context(
     45         nvtx.annotate(
     46             message=func.__qualname__,
   (...)
     49         )
     50     )
---> 51 return func(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/cudf/core/groupby/groupby.py:487, in GroupBy.get_group(self, name, obj)
    485         name = name[0]
    486     else:
--> 487         raise KeyError(name)
    488 return obj.iloc[self.indices[name]]

KeyError: (4, 4)
```

**Expected behavior**

pandas:
```
import pandas as pd
df = pd.DataFrame({'b': [4,5], 'a': [1,2], 'c': [4,3]})
df.groupby(['b', 'c']).get_group((4, 4))
```
```
 	b 	a 	c
0 	4 	1 	4
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

cudf 24.12.00

spotted in [Narwhals](https://github.com/narwhals-dev/narwhals)

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

Looks like this is due to https://github.com/rapidsai/cudf/pull/17216

**Comment by DasIstSpark** [comment]
on 25.08, the get_group() is still broken,

please check the following test case.


```
df = cudf.DataFrame({"a": ['string'], "b": [4], "c": [3]})
expected = df.to_pandas().groupby(["a"]).get_group('string')
result = df.groupby(["a"]).get_group('string')
```

**edit**

instead of using

`expected = df.to_pandas().groupby(["a"]).get_group('string')`

using 

`expected = df.to_pandas().groupby(["a"]).get_group(('string',))`

resolved the issue.
