### ISSUE TITLE
[FEA] add dtype.pyarrow_dtype

### ISSUE THREAD

**Issue by MarcoGorelli** [rapidsai/cudf#17663]
**Is your feature request related to a problem? Please describe.**

in pandas I can do
```
pd.Series([[1,2,3], [4, 5]], dtype=pd.ArrowDtype(pa.list_(pa.int64()))).dtype.pyarrow_dtype
```

in cuDF, it's
```
cudf.Series([[1,2,3], [4, 5]]).dtype.to_arrow()
```

Why not introduce a `pyarrow_dtype` property (instead of, or alongside, `to_arrow()`) so it mirrors pandas?

(this came up testing Narwhals)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by mroeschke** [comment]
Thanks for the suggestion.

The current complication is that for numeric and datelike types, cudf just uses the numpy dtype objects.

Some cudf Python types do expose a `to_arrow` method e.g `ListDtype`, `StructDtype`, the decimal types

Does polars have/plan to have an API to convert their types to (py)arrow types as well? Is that the iterop bridge you're typing to build in Narwhals?

**Comment by MarcoGorelli** [comment]
I just noticed this in internal code, where if we have a list data type then `.pyarrow_dtype` worked for pandas but raised for cuDF

Not an issue though, it's easy to work around:

https://github.com/narwhals-dev/narwhals/blob/7c8c6fa1d3e7a4c31b8bf7577ca80ab9322a1c95/narwhals/_pandas_like/utils.py#L449-L451

happy to close then
