### ISSUE TITLE
[BUG] GpuArrowReader behavior changed between 0.6 and 0.7 (ValueError: buffer source array is read-only)

### ISSUE THREAD

**Issue by randyzwitch** [rapidsai/cudf#1766]
**Describe the bug**
In pymapd, we are seeing a bug when using cudf 0.7.1 with GpuArrowReader. Our code passes the following to GpuArrowReader:

```python
    schema_buffer = np.frombuffer(schema_buffer[0].to_pybytes(),
                                  dtype=np.uint8)

    dtype = np.dtype(np.byte)
    darr = cuda.devicearray.DeviceNDArray(shape=dptr.size,
                                          strides=dtype.itemsize,
                                          dtype=dtype,
                                          gpu_data=dptr)
    reader = GpuArrowReader(schema_buffer, darr)
```

This code works in cudf 0.6 to create a cudf dataframe.

**Steps/Code to reproduce bug**
```python
In [6]: df = con.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")
Traceback (most recent call last):

  File "<ipython-input-6-c183a84f9277>", line 1, in <module>
    df = con.select_ipc_gpu("select start_station_latitude from fordgobike_tripdata")

  File "/home/rzwitch/github_work/pymapd/pymapd/connection.py", line 306, in select_ipc_gpu
    df = _parse_tdf_gpu(tdf)

  File "/home/rzwitch/github_work/pymapd/pymapd/_parsers.py", line 203, in _parse_tdf_gpu
    reader = GpuArrowReader(schema_buffer, darr)

  File "cudf/bindings/gpuarrow.pyx", line 203, in cudf.bindings.gpuarrow.GpuArrowReader.__init__

  File "cudf/bindings/gpuarrow.pyx", line 228, in cudf.bindings.gpuarrow.GpuArrowReader._open

  File "cudf/bindings/gpuarrow.pyx", line 248, in cudf.bindings.gpuarrow.GpuArrowReader._parse_metdata

  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper

  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__

ValueError: buffer source array is read-only

```

**Expected behavior**
The expected behavior would be to return a cudf in the same way it is returned in cudf 0.6.

**Environment details (please complete the following information):**
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 
Environment: Ubuntu 18.04 LTS, conda environment install

**Comment by randyzwitch** [comment]
From digging through the commits, it appears that one of these two might have introduced this issue:

https://github.com/rapidsai/cudf/commit/8505bc803e63dc30b0e1f34fa4e0987e73384de6
https://github.com/rapidsai/cudf/commit/94ae25b08203ad94b53675230889b4a8d031fea5

**Comment by kkraus14** [comment]
@randyzwitch looks like the offending line is https://github.com/rapidsai/cudf/blob/branch-0.8/python/cudf/bindings/gpuarrow.pyx#L248, @jakirkham looks like the Cython memoryview isn't happy with the input buffer being read-only, any ideas?

**Comment by kkraus14** [comment]
@randyzwitch short term while we work this out, if instead of using `np.frombuffer(...)` you created the numpy array by copy `np.array(...)` I think it will remove the read only flag and workaround this issue.

**Comment by kkraus14** [comment]
Fixed by #1768

**Comment by jakirkham** [comment]
> @jakirkham looks like the Cython memoryview isn't happy with the input buffer being read-only, any ideas?

Sorry for missing this @kkraus14. I have seen some issues where Cython doesn't like read-only memoryviews. Though they have also been actively improving this over time (e.g. https://github.com/cython/cython/issues/1605 ).

**Comment by jakirkham** [comment]
If you'd like me to dig into this further Keith, I'd be happy to do that. Though am also happy with your solution as is.
