### ISSUE TITLE
[BUG] cudf.bindings.GDFError.GDFError: b'GDF_UNSUPPORTED_DTYPE'

### ISSUE THREAD

**Issue by seraphzl** [rapidsai/cudf#1774]
**Describe the bug**
Hi,
When reading csv file with cudf.read_csv, an error was reported:

Traceback (most recent call last):
  File "./datapre_gpu.py", line 286, in <module>
    dw_event = get_event_record(dw)
  File "./datapre_gpu.py", line 58, in get_event_record
    gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)
  File "/home/abc/app/miniconda3/lib/python3.7/site-packages/cudf/io/csv.py", line 164, in read_csv
    index_col=index_col
  File "cudf/bindings/csv.pyx", line 44, in cudf.bindings.csv.cpp_read_csv
  File "cudf/bindings/csv.pyx", line 266, in cudf.bindings.csv.cpp_read_csv
  File "cudf/bindings/cudf_cpp.pyx", line 365, in cudf.bindings.cudf_cpp.check_gdf_error
cudf.bindings.GDFError.GDFError: b'GDF_UNSUPPORTED_DTYPE'

**Steps/Code to reproduce bug**

import cudf
headers = ['STATION', 'SW', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']
dtypes = ['int32', 'int16', 'int16', 'int8', 'int8', 'int8', 'int8']
gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)

**Expected behavior**
The csv file was read with no error.

**Environment details (please complete the following information):**
 - Environment location: CentOS 7.6.1810 Linux host
 - Method of cuDF install: conda
 - Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3

**Comment by j-ieong** [comment]
This is because `int16` is missing from our `convertStringToDtype` function, as it currently only maps `short`.

**Comment by seraphzl** [comment]
import cudf
headers = ['STATION', 'SW', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']
dtypes = ['int32'] * 7
gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)

When using the code above to read the csv file of 750M, another error was reported:
Segmentation fault (core dumped)

- Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3
- Hardware: 2 Tesla V100 (32G Memory), Host memory 128G

**Comment by j-ieong** [comment]
> import cudf
> headers = ['STATION', 'SW', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']
> dtypes = ['int32'] * 7
> gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)
> 
> When using the code above to read the csv file of 750M, another error was reported:
> Segmentation fault (core dumped)
> 
>     * Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3
> 
>     * Hardware: 2 Tesla V100 (32G Memory), Host memory 128G

@seraphzl That seems like a different issue. Does it work if you reduce the CSV file to a few lines? Can attach a reduction of the CSV file that repros if possible? Thanks!

**Comment by seraphzl** [comment]
> > import cudf
> > headers = ['STATION', 'SW', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']
> > dtypes = ['int32'] * 7
> > gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)
> > When using the code above to read the csv file of 750M, another error was reported:
> > Segmentation fault (core dumped)
> > ```
> > * Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3
> > 
> > * Hardware: 2 Tesla V100 (32G Memory), Host memory 128G
> > ```
> 
> @seraphzl That seems like a different issue. Does it work if you reduce the CSV file to a few lines? Can attach a reduction of the CSV file that repros if possible? Thanks!

@j-ieong ok, I will move it to a new issue. Thanks!

**Comment by mjsamoht** [comment]
Re-opening.  We still want to add the missing 'int8' and 'int16' support.

**Comment by seraphzl** [comment]
'uint16' and 'uint8' support are also needed. :-)
