### ISSUE TITLE
[DOC] Monitoring and debugging tool for rapids.io 

### ISSUE THREAD

**Issue by vnkesarwani** [rapidsai/cudf#1775]
## Report needed documentation

**Monitoring and debugging tool for rapids.io**
How do you monitor and debug cudf? 

1- What function call is executing @present in GPU.
2- Time taken for data load, execution time, memory allocated/used, time cudf library loading in GPU or context creation.
3- Is there any gpu job monitoring tool which can provide this kind of details?
4- Which tool is suited for running cudf ETL in distributed mode.
5- How do we Accumulate resultant data in distributed mode and return.
6- is there any tool which can convert sql to cudf dataframe directly?

I am exploring these options to create an end to end flow. Let me know if any of you can give a pointer here.

**Comment by vnkesarwani** [comment]
Any Comment on that.

**Comment by kkraus14** [comment]
Responded on the google group request so closing this and will continue discussion there.
