### ISSUE TITLE
[BUG] Merges (SQL style joins) don't maintain original row ordering when key columns are different

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1776]
**Describe the bug**
Left join merges don't maintain the ordering of the original dataframe if the values in one join key are not identical to the other join key. This is occurring with both string and numeric column keys. So far, I've only been able to reproduce this for `left joins` (`inner joins` don't seem to have the same issue).

```
# Superset of key values

df_a = cudf.DataFrame()
df_a['key'] = [10, 12, 13, 14, 15]
df_a['vals_a'] = [float(i + 10) for i in range(5)]

df_b = cudf.DataFrame()
df_b['key'] = [10, 12, 13, 13, 14, 15, 15]
df_b['vals_b'] = [float(i+100) for i in range(7)]

merged = df_a.merge(df_b, on=['key'], how='left')
print(df_a)
print(merged)

pdf_a = df_a.to_pandas()
pdf_b = df_b.to_pandas()
merged = pdf_a.merge(pdf_b, on=['key'], how='left')
print(merged)
   key  vals_a
0   10    10.0
1   12    11.0
2   13    12.0
3   14    13.0
4   15    14.0
   key  vals_a  vals_b
0   10    10.0   100.0
1   12    11.0   101.0
2   13    12.0   102.0
3   14    13.0   104.0
4   15    14.0   105.0
5   13    12.0   103.0
6   15    14.0   106.0
   key  vals_a  vals_b
0   10    10.0   100.0
1   12    11.0   101.0
2   13    12.0   102.0
3   13    12.0   103.0
4   14    13.0   104.0
5   15    14.0   105.0
6   15    14.0   106.0
```

```
# Subset of key values
df_a = cudf.DataFrame()
df_a['key'] = [10, 12, 13, 14, 15]
df_a['vals_a'] = [float(i + 10) for i in range(5)]

df_b = cudf.DataFrame()
df_b['key'] = [10, 13, 15]
df_b['vals_b'] = [float(i+100) for i in range(3)]

merged = df_a.merge(df_b, on=['key'], how='left')
print(df_a)
print(merged)

pdf_a = df_a.to_pandas()
pdf_b = df_b.to_pandas()
merged = pdf_a.merge(pdf_b, on=['key'], how='left')
print(merged)
   key  vals_a
0   10    10.0
1   12    11.0
2   13    12.0
3   14    13.0
4   15    14.0
   key  vals_a  vals_b
0   10    10.0   100.0
1   13    12.0   101.0
2   15    14.0   102.0
3   12    11.0        
4   14    13.0        
   key  vals_a  vals_b
0   10    10.0   100.0
1   12    11.0     NaN
2   13    12.0   101.0
3   14    13.0     NaN
4   15    14.0   102.0
```

```
# Identical key values - order is maintained

df_a = cudf.DataFrame()
df_a['key'] = [10, 12, 13, 14, 15]
df_a['vals_a'] = [float(i + 10) for i in range(5)]

df_b = cudf.DataFrame()
df_b['key'] = [10, 12, 13, 14, 15]
df_b['vals_b'] = [float(i+100) for i in range(5)]

merged = df_a.merge(df_b, on=['key'], how='left')
print(df_a)
print(merged)

pdf_a = df_a.to_pandas()
pdf_b = df_b.to_pandas()
merged = pdf_a.merge(pdf_b, on=['key'], how='left')
print(merged)
   key  vals_a
0   10    10.0
1   12    11.0
2   13    12.0
3   14    13.0
4   15    14.0
   key  vals_a  vals_b
0   10    10.0   100.0
1   12    11.0   101.0
2   13    12.0   102.0
3   14    13.0   103.0
4   15    14.0   104.0
   key  vals_a  vals_b
0   10    10.0   100.0
1   12    11.0   101.0
2   13    12.0   102.0
3   14    13.0   103.0
4   15    14.0   104.0

```

**Comment by jrhemstad** [comment]
Pandas is an inherently sequential library, so the order of its outputs will always be the same. That won't be true of cuDF unless we do additional work (make performance worse).

It is the nature of most parallel algorithms that the order of the outputs will not be deterministic unless you pay some cost to make them deterministic (e.g., sorting the outputs). 

This has come up a few times, so I think it points to something we'll want to make sure we add to the documentation of cuDF as a whole that by default you shouldn't rely on any particular output order. If you need a particular order, then the onus is on the user to sort the data.

**Comment by beckernick** [comment]
@randerzander, let's make sure we think this through carefully and document it for users. As @jrhemstad is right it will likely keep coming up.

Suggesting a user sort afterward based on the original order is messy because we may not have the same number of records depending on the nature of the merge. If the data is originally sorted by a column, we can of course just sort by that column (assuming we aren't concerned with maintaining the order of merged values for that key).

But if the merge is on "unsorted" data with ordering that we want to preserve, it's less clear. We don't have `df.reindex` functionality (though perhaps we should, I'll make a feature request for that), but even if we did we'd end up passing too few or too many indices to `reindex` for the ordering if the merged dataframe has more or fewer rows. Is the best solution simply to document for users that we can't preserve order and that sorting afterwards won't solve the problem unless the data was pre sorted by a specific column?

Interested to hear both of your thoughts on what makes sense here.

**Comment by jrhemstad** [comment]
> @randerzander, let's make sure we think this through carefully and document it for users. As @jrhemstad is right it will likely keep coming up.
> 
> Suggesting a user sort afterward based on the original order is messy because we may not have the same number of records depending on the nature of the merge. If the data is originally sorted by a column, we can of course just sort by that column (assuming we aren't concerned with maintaining the order of merged values for that key).
> 
> But if the merge is on "unsorted" data with ordering that we want to preserve, it's less clear. We don't have `df.reindex` functionality (though perhaps we should, I'll make a feature request for that), but even if we did we'd end up passing too few or too many indices to `reindex` for the ordering if the merged dataframe has more or fewer rows. Is the best solution simply to document for users that we can't preserve order and that sorting afterwards won't solve the problem unless the data was pre sorted by a specific column?
> 
> Interested to hear both of your thoughts on what makes sense here.

Would you mind making a separate issue to discuss order preserving behavior of cuDF vs Pandas?

**Comment by beckernick** [comment]
Will open up a new issue and reference this issue.

**Comment by kkraus14** [comment]
Closing this as a non-issue and will continue discussion in #1781
