### ISSUE TITLE
[BUG] Version number for branch-0.8 is 0.7.1+*

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1777]
**Describe the bug**
With 0.8 built from source, my cudf version number is listed as: `'0.7.1+500.g24ab9736.dirty'`

```
root@eda6446ca8a0:/cudf# conda list | grep cudf
cudf                      0.7.1+500.g24ab9736.dirty          pypi_0    pypi
dask-cudf                 0.0.0.dev0               pypi_0    pypi
root@eda6446ca8a0:/cudf#
```

**Comment by kkraus14** [comment]
@raydouglass @mike-wendt This version is pulled from the git tag, is there any way for us to be able to tag dev branches without being disruptive?

**Comment by raydouglass** [comment]
@beckernick Are you up to date on `branch-0.8`? You may also need to pull the tags: `git fetch origin --tags`.

The latest v0.8 tag is `v0.8.0a1`.
