### ISSUE TITLE
[BUG] Datetime read by parquet reader incorrect for parquet file written by Dask

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1784]
**Describe the bug**
I have a parquet file that was originally created as follows: 
Pandas df (with datetime col) -> Dask Dataframe (from pandas) -> to_parquet (dask)

When reading this parquet file using cudf.read_parquet() the results are incorrect and might have something to do with how dask writes the datetime objects to the file which cudf does not handle well.

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
import pandas as pd
import dask.dataframe

pdf = pd.DataFrame()
pdf['a'] = pd.Series([np.datetime64('2019-03-28 00:15:00.023'),np.datetime64('2019-03-29 00:59:59.997')]*5)
ddf = dask.dataframe.from_pandas(pdf,1)
ddf.to_parquet('datetime.parquet')

df = cudf.read_parquet('datetime.parquet/part.0.parquet')
print(df)
```
Output:
```
a    datetime64[ns]
dtype: object
                         a
__index_level_0__
0 51205-10-23T10:00:23.000
1 51208-08-19T15:59:57.000
2 51205-10-23T10:00:23.000
3 51208-08-19T15:59:57.000
4 51205-10-23T10:00:23.000
5 51208-08-19T15:59:57.000
6 51205-10-23T10:00:23.000
7 51208-08-19T15:59:57.000
8 51205-10-23T10:00:23.000
9 51208-08-19T15:59:57.000
```

**Expected behavior**
Datetime values should match the inputs provided initially

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: from source
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**
Have also attached the parquet file being written by dask for reference
[datetime.parquet.zip](https://github.com/rapidsai/cudf/files/3192951/datetime.parquet.zip)

**Comment by kkraus14** [comment]
@ayushdg if you write the file using Pandas and then read from cuDF does that work as expected? That will be easier to triage and resolve if possible.

**Comment by ayushdg** [comment]
Yes, writing the same file from pandas and reading into cudf works as expected with correct results.

**Comment by kkraus14** [comment]
Will leave it to the IO experts from here then 😄

**Comment by OlivierNV** [comment]
I think this is another side effect of cudf only supporting millisecond timestamps -> the datetime file saved by dask has timestamp in microsecond units. Parquet currently doesn't do any conversion, though we could force a conversion to milliseconds until cudf properly supports other units.

**Comment by ayushdg** [comment]
Great. I'll also upload the file written by pandas because when the data is written to a parquet file by pandas, cudf has no problem reading it. Maybe pandas does not write it in microseconds but you can verify to make sure that is the issue.

Code to reproduce: 
```
import cudf
import numpy as np
import pandas as pd

pdf = pd.DataFrame()
pdf['a'] = pd.Series([np.datetime64('2019-03-28 00:15:00.023'),np.datetime64('2019-03-29 00:59:59.997')]*5)
pdf.to_parquet('datetime_pd.parquet')

df = cudf.read_parquet('datetime_pd.parquet')
print(df)
```
```
                        a
__index_level_0__
0 2019-03-28T00:15:00.023
1 2019-03-29T00:59:59.997
2 2019-03-28T00:15:00.023
3 2019-03-29T00:59:59.997
4 2019-03-28T00:15:00.023
5 2019-03-29T00:59:59.997
6 2019-03-28T00:15:00.023
7 2019-03-29T00:59:59.997
8 2019-03-28T00:15:00.023
9 2019-03-29T00:59:59.997
```
[datetime_pd.parquet.zip](https://github.com/rapidsai/cudf/files/3203926/datetime_pd.parquet.zip)

**Comment by OlivierNV** [comment]
@ayushdg : thanks, I can confirm that the pandas version indeed stores the timestamps in milliseconds (parquet::TIMESTAMP_MILLIS=9), whereas dask stores the timestamps in microseconds (parquet::TIMESTAMP_MICROS=10), this seems to be the only difference between the two files.

**Comment by OlivierNV** [comment]
If we want this handled in 0.8, a short-term fix would be to just convert microsecond timestamps to milliseconds in the parquet reader, so that the output is always in milliseconds.

**Comment by ayushdg** [comment]
@OlivierNV This isn't a blocker for me right now but if the short-term fix does not require a big change it would be good to have for 0.8.

**Comment by OlivierNV** [comment]
@ayushdg : Can we use this test file for automated testing ?

**Comment by ayushdg** [comment]
@OlivierNV Sure :D
