### ISSUE TITLE
[FEA] Reducing memory overhead for `concat` via shallow copy

### ISSUE THREAD

**Issue by mt-jones** [rapidsai/cudf#1787]
Currently, column concatenation requires that the [output column's total size matches the aggregate size of the columns](https://github.com/rapidsai/cudf/blob/20c87a94dddee6c2d8b2730818c9bbcdc14f339a/cpp/src/column/column.cpp#L75) to be concatenated. [It then performs a deep copy](https://github.com/rapidsai/cudf/blob/20c87a94dddee6c2d8b2730818c9bbcdc14f339a/cpp/src/column/column.cpp#L102).

There is nothing wrong with this, but it does incur a 2X memory overhead. Meaning, if the columns you want to concatenate exceed (in memory) 50% of your available memory, you will OOM.

Memory spill-over will certainly help to mitigate this limitation, but _at the cost of multiple copies between device and host_.

I'm wondering if we can design a method which simply copies the metadata associated with the constituent columns instead of copying the physical data. (e.g.) instead of copying the data itself, copy its location and size in memory to a new column structure. This would probably require the column structure we have to be reworked slightly to accommodate this pattern.

This would translate to lower memory overheads, and faster concatenation time (actually, not really faster, we'd be deferring the memory access to the kernel that needs to access the data later, maybe even fragmenting the data, memory not coalesced, etc.).

My question is what other issues are there associated with such a solution?

**Comment by jrhemstad** [comment]
Two large design issues stand in the way:
 1. Unofficially, columns are generally immutable. 
   - Shallow copying from one column to another would have two columns pointing to the same data.
2. Support for chunked columns. 
   - What you're suggesting is essentially shallow copying `n` columns into 1 chunked column. Makes sense, but we're a long ways off from being able to support this in any of libcudf's algorithms.

**Comment by mt-jones** [comment]
>What you're suggesting is essentially shallow copying n columns into 1 chunked column. Makes sense, but we're a long ways off from being able to support this in any of libcudf's algorithms.

Perhaps a broader question would be whether or not we want to make it an official specification that columns remain immutable. Has this been discussed?

**Comment by jrhemstad** [comment]
> > What you're suggesting is essentially shallow copying n columns into 1 chunked column. Makes sense, but we're a long ways off from being able to support this in any of libcudf's algorithms.
> 
> Perhaps a broader question would be whether or not we want to make it an official specification that columns remain immutable. Has this been discussed?

I'm keeping it in mind as part of https://github.com/rapidsai/cudf/issues/1443

**Comment by kkraus14** [comment]
Closing this as it breaks a lot of design of the current column implementation. We should continue discussion in #1443.
