### ISSUE TITLE
[FEA] Function to convert column of floating points with NaNs into bitmask 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1788]
It is necessary to be able to take a column of floating point values, potentially containing NaNs, and generate a bitmask where every NaN is indicated as null by the bitmask.

The function would look something like:
```
bit_mask_t * nans_to_nulls(gdf_column const * col);
```

`col` may be nullable and must be either `GDF_FLOAT32` or `GDF_FLOAT64`. The returned bitmask will be copied from `col` and updated to have a 0 at bit `i` if `col->data[i]` is `NaN`.

This should be very easy and efficient to implement in a kernel that uses [`isnan`](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html) and [`__ballot_sync` ](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#warp-vote-functions).

This would be used to replace an inefficient Numba function that is currently doing the same thing: https://github.com/rapidsai/cudf/blob/branch-0.8/python/cudf/utils/cudautils.py#L362. Once the libcudf primitive is created, usage of `mask_from_devary` should be replaced with `nans_to_nulls`.

**Comment by jrhemstad** [comment]
@hummingtree in order to implement this function, I'd like you to create a more generic function that we can reuse internally in libcudf.

The function would look something like this:

```
/**---------------------------------------------------------------------------*
 * @brief Creates a bitmask by applying a predicate to the elements of a column.
 *
 * Bit `i` in the output bitmask will be set if `p(input[i])` returns true,
 * else, the bit will be unset.
 *
 * @param input The column to apply the predicate on
 * @param p The predicate to apply
 * @return bit_mask_t* A bitmask whose bits are set iff the predicate returned
 * true on the corresponding elements of `input`.
 *---------------------------------------------------------------------------**/
template <typename Predicate>
bit_mask_t* null_if(gdf_column const& input, Predicate p);
```
And then to implement `nans_to_nulls()` the `Predicate` would just be something like:
```
struct is_nan{
    template <typename T>
    bool operator()(gdf_size_type index){
        return is_nan(static_cast<T*>(input.data)[index]);
    }
    gdf_column input;
}
```

**Comment by jrhemstad** [comment]
@kkraus14 what (if any) is the expected behavior for handling `inf` values in this function?

**Comment by kkraus14** [comment]
@jrhemstad return `inf` values as normal, don't need any special handling.
