### ISSUE TITLE
[BUG] GDF_COALESCE is not implemented

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1797]
**Describe the bug**
`GDF_COALESCE` is not implemented.  You try to use it with `gdf_binary_operation_*` your code complies but the JITed code fails to compile.  There is no implementation of it on the back-end.

**Steps/Code to reproduce bug**
Take any existing test for bianry ops and switch it to use GDF_COALESCE instead.
```
--- a/cpp/tests/binary/integration/binary-operation-integration-test.cpp
+++ b/cpp/tests/binary/integration/binary-operation-integration-test.cpp
@@ -79,7 +79,7 @@ TEST_F(BinaryOperationIntegrationTest, Add_Vector_Scalar_SI08_SI16_SI32) {
     auto rhs = cudf::test::scalar_wrapper<int32_t>{100};
     auto out = cudf::test::column_wrapper<int8_t>{lhs.get()->size, true};
 
-    auto result = gdf_binary_operation_v_s(out.get(), lhs.get(), rhs.get(), GDF_ADD);
+    auto result = gdf_binary_operation_v_s(out.get(), lhs.get(), rhs.get(), GDF_COALESCE);
     ASSERT_TRUE(result == GDF_SUCCESS);
 
     ASSERT_BINOP(out, lhs, rhs, ADD());
```

Try to run the test and instead of failing with bad data, it fails with not able to compile.

```
---------------------------------------------------
--- JIT compile log for  ---
---------------------------------------------------
__nv_name_map(2): error: identifier "None" is undefined

__nv_name_map(2): error: Error in parsing name expression for lowered name lookup. Input name expression 
was: " kernel_v_s < signed char, short int, int, None >"

2 errors detected in this compilation.


---------------------------------------------------
unknown file: Failure
C++ exception with description "NVRTC error: NVRTC_ERROR_COMPILATION" thrown in the test body.

```

**Expected behavior**
Either `GDF_COALESCE` does not exist so we know it does not work, or it actually produces some kind of result.

**Comment by jrhemstad** [comment]
This looks like it was added by @felipeblazing here https://github.com/rapidsai/cudf/commit/fd0ecd893350fe5fb6a8f186c91afc12b9b2f117 but never implemented in libcudf. 

I suspect it was added for internal use by Blazing.

This should be rectified and either removed or implemented in libcudf.

**Comment by harrism** [comment]
Presumably "coalesce" was removed during the libcudf++ refactor. @revans2 is coalesce basically `copy_if_else`? Is this issue still needed?

**Comment by devavret** [comment]
@harrism , I think the answer to your question is in Alternatives Considered in #3754 . Also they are duplicate issues. Closing this one.
