### ISSUE TITLE
[FEA] Change default output dtype of `DataFrame.one_hot_encoding` from `float64` to `int32`

### ISSUE THREAD

**Issue by RFinkelberg** [rapidsai/cudf#1800]
**Is your feature request related to a problem? Please describe.**
Under the current implementation of `one_hot_encoding`, the default dtype of the returned dummy columns is `float64`. This can cause a slowdown of up to 3x on tall dataframes when compared to `int32`.

**Describe the solution you'd like**
Change the default output dtype to `int32`, or some other similar type with less overhead.

**Additional context**
By the nature of one hot encoding, output vectors don't need to be floating point. [Pandas one hot encoder](https://github.com/pandas-dev/pandas/blob/v0.24.2/pandas/core/reshape/reshape.py#L701) similarly uses `uint8`s.

**Comment by beckernick** [comment]
Closing, as this is now resolved:
- We just deprecated `one_hot_encoding` in https://github.com/rapidsai/cudf/pull/9977
- get_dummies currently uses integers

```python
import cudf
​
df = cudf.DataFrame({
    "a":["a","b","c"]
})
print(cudf.get_dummies(df))
   a_a  a_b  a_c
0    1    0    0
1    0    1    0
2    0    0    1
```
