### ISSUE TITLE
[BUG] Segmentation fault (core dumped) when loading 750M csv file

### ISSUE THREAD

**Issue by seraphzl** [rapidsai/cudf#1815]
**Describe the bug**
Hi,
When reading a 750M csv file with cudf.read_csv, an error was reported:
Segmentation fault (core dumped)

**Steps/Code to reproduce bug**
import cudf
headers = ['STATION', 'SW', 'YEAR', 'MONTH', 'DAY', 'HOUR', 'MINUTE']
dtypes = ['int32'] * 7
gdf = cudf.read_csv(dr_path+dr_file, usecols=headers, dtype=dtypes)

**Expected behavior**
The csv file was loaded with no error.

**Environment details (please complete the following information):**
 - Environment location: CentOS 7.6.1810 Linux host
 - Method of cuDF install: conda
 - Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3
 - Hardware: 2 Tesla V100 (32G Memory), Host memory 128G

**Additional context**
When using this code: gdf = cudf.read_csv(dr_path+dr_file, usecols=headers), the csv file was loaded with no error.

**Comment by kkraus14** [comment]
@seraphzl would you be able to upload a data sample or a script to generate data that reproduces this issue?

**Comment by mjsamoht** [comment]
@seraphzl this sounds very similar to #1625, which was fixed in branch-0.8 about 8 days ago.  Can you verify with 0.8 top of tree whether the problem still persists?

**Comment by mjsamoht** [comment]
@seraphzl can you please comment whether this is still an open issue with 0.8 top of tree?

**Comment by mjsamoht** [comment]
No response in 10 days so I'm going to close this.  Feel free to reopen if the problem still reproduces with 0.8 top of tree.
