### ISSUE TITLE
[FEA] Add support for equivalence of Pandas 'stack'

### ISSUE THREAD

**Issue by bellershaw1** [rapidsai/cudf#1820]
**Is your feature request related to a problem? Please describe.**
I wish cuDF supported Pandas stack.

**Describe the solution you'd like**
Support a stack operation identical to Pandas stack.

**Describe alternatives you've considered**
Right now I have to go back to Pandas in order to use stack, which is unwanted because I lose the optimization that cuDF gives me.

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.stack.html

**Comment by thomcom** [comment]
Fixed by #2956
