### ISSUE TITLE
[FEA] Add support for equivalence of Pandas 'unstack' 

### ISSUE THREAD

**Issue by bellershaw1** [rapidsai/cudf#1821]
**Is your feature request related to a problem? Please describe.**
I wish cuDF supported Pandas unstack.

**Describe the solution you'd like**
Support an unstack operation identical to Pandas unstack.

**Describe alternatives you've considered**
Right now I have to go back to Pandas in order to use unstack, which is unwanted because I lose the optimization that cuDF gives me.

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unstack.html

**Comment by thomcom** [comment]
Thanks for the request @bellershaw1 - I just added MultiIndex into cuDF. I'll get to work with stack and unstack as well, since it is clearly needed.

**Comment by okdimok** [comment]
Hi! Are there any news or workarounds available?
