### ISSUE TITLE
[BUG] Boolean series with null values `to_pandas()` throws error

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1829]
**Describe the bug**
If I have a boolean column in cudf with null values converting to pandas raises an error

**Steps/Code to reproduce bug**
```
import cudf

a = [True,None,False]
gs = cudf.Series(a)
gs.to_pandas()
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/adattagupta/conda/envs/test/lib/python3.7/site-packages/cudf/dataframe/series.py", line 763, in to_pandas
    s = self._column.to_pandas(index=index)
  File "/home/nfs/adattagupta/conda/envs/test/lib/python3.7/site-packages/cudf/dataframe/numerical.py", line 169, in to_pandas
    return pd.Series(self.to_array(fillna='pandas'), index=index)
  File "/home/nfs/adattagupta/conda/envs/test/lib/python3.7/site-packages/cudf/dataframe/column.py", line 307, in to_array
    return self.to_dense_buffer(fillna=fillna).to_array()
  File "/home/nfs/adattagupta/conda/envs/test/lib/python3.7/site-packages/cudf/dataframe/column.py", line 498, in to_dense_buffer
    na_value = self.default_na_value()
  File "/home/nfs/adattagupta/conda/envs/test/lib/python3.7/site-packages/cudf/dataframe/numerical.py", line 304, in default_na_value
    "numeric column of {} has no NaN value".format(self.dtype))
TypeError: numeric column of bool has no NaN value

```

**Expected behavior**
The conversion takes place without any errors. 

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of cuDF install: Conda nightly as of (05/21) 

**Additional context**
The issue stems from this method here: https://github.com/rapidsai/cudf/blob/branch-0.8/python/cudf/dataframe/numerical.py#L291-L301

Which does not specify any default null value for bools. If there is a specific default null value we want to specify for bools like (`None`) and this seems to be the preferred method of handling the issue, I'd be happy to make a small pr to fix the issue.

**Comment by ayushdg** [comment]
I was looking at the pandas behavior a bit more and we might need to discuss the approach cudf takes. A boolean column with nulls is treated as dtype(`np.object_`) and not boolean. If you force pandas to read the column as a boolean type it converts all nulls to `False`.

**Comment by kkraus14** [comment]
> I was looking at the pandas behavior a bit more and we might need to discuss the approach cudf takes. A boolean column with nulls is treated as dtype(`np.object_`) and not boolean. If you force pandas to read the column as a boolean type it converts all nulls to `False`.

We can look at pyarrow's behavior here for reference:

```
In [53]: import pyarrow as pa                                                                                                      

In [54]: pa.array([True, None, False])                                                                                             
Out[54]: 
<pyarrow.lib.BooleanArray object at 0x7ff981513778>
[
  true,
  null,
  false
]

In [55]: pa.array([True, None, False]).to_pandas()                                                                                 
Out[55]: array([True, None, False], dtype=object)

In [56]: pa.array([True, False]).to_pandas()                                                                                       
Out[56]: array([ True, False])
```
