### ISSUE TITLE
[BUG] Build script use of PYTHON

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cudf#1830]
CI is failing on GPU matrix builds: https://gpuci.gpuopenanalytics.com/job/gpuCI/job/cudf/job/branches/job/cudf-gpu-matrix-branch-0.8/CC_VERSION=5,CUDA=10.0,LINUX_VERSION=ubuntu16.04,PYTHON=3.6/2/console

CI uses the `PYTHON` environment variables for the version of python (`3.6` in the above example). The script use `PYTHON` as the python executable, so there is a conflict.

This has to be fixed in cuDF because many scripts in cuDF and other projects use `PYTHON` to check the version.

**Comment by rlratzel** [comment]
Fixed with PR #1831
