### ISSUE TITLE
Error while trying to find the linear regression for a given data set

### ISSUE THREAD

**Issue by vp2527** [rapidsai/cudf#1832]
I am pretty new to using the RAPIDS library. I am trying to find the class of breast cancer(malignant or benign) using linear regression for a dataset that I got from the internet. 

dfcu = cudf.read_csv('breast-cancer-wisconsin.data.txt', delimiter=',',names = ['id', 'clump_thickness' , 'unif_cell_size' , 'unif_cell_shape' , 'marg_adhesion', 'single_eputh_cell_size' , 'bare_nuclei', 'bland_chrom', 'norm_nucleoli', 'mitoses', 'class'])

Xcu = dfcu.drop(['class'],1)
ycu = dfcu['class']

Xcu_train, Xcu_test, ycu_train, ycu_test = sklearn.model_selection.train_test_split(Xcu,ycu,test_size=0.2)

cuols = cuLinearRegression(fit_intercept=True,
                  normalize=True,
                  algorithm='eig')

_cuols.fit(Xcu_train, ycu_train)_

**THE ERROR I GET WHILE TRYING TO RUN THE ABOVE LINE:**

AttributeError                            Traceback (most recent call last)
<ipython-input-108-469c8d9812ee> in <module>()
----> 1 cuols.fit(Xcu_train, ycu_train)

cuml/linear_model/linear_regression.pyx in cuml.linear_model.linear_regression.LinearRegression.fit()

2 frames
/usr/local/lib/python3.6/site-packages/cudf/dataframe/column.py in to_gpu_array(self, fillna)
    288         output size could be smaller.
    289         """
--> 290         return self.to_dense_buffer(fillna=fillna).to_gpu_array()
    291 
    292     def to_array(self, fillna=None):

AttributeError: 'nvstrings' object has no attribute 'to_gpu_array'

Any idea on where I might be going wrong?

**Comment by thomcom** [comment]
It looks like you need to convert the string columns in your dataset to numerical or categorical columns - I suspect the issue here is that `nvstrings` can't have a linear regression computed on it. That doesn't make sense. :)

**Comment by thomcom** [comment]
This is a great question to post to StackOverflow, try there?

**Comment by vp2527** [comment]
Thanks for your input. I'll try it out :)
