### ISSUE TITLE
[BUG] inconsistent results of dataframe.iloc from cudf and pandas

### ISSUE THREAD

**Issue by seraphzl** [rapidsai/cudf#1834]
**Describe the bug**
Hi,
The dataframe.iloc from cudf give inconsistent results with pandas: pdf.iloc[:, :2] get all rows and first 2 columns, while gdf.iloc[:, :2] get 2 rows and all columns.
pdf:
    a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
gdf:
    a  b  c
0  1  1  1
1  2  2  2

**Steps/Code to reproduce bug**
import pandas as pd
import cudf
pdf = pd.DataFrame({'a': [1,2,3,4,5], 'b': [1,2,3,4,5], 'c': [1,2,3,4,5]})
gdf = cudf.DataFrame([('a', [1,2,3,4,5]), ('b', [1,2,3,4,5]), ('c', [1,2,3,4,5])])
a = pdf.iloc[:, :2]
b = gdf.iloc[:, :2]
print('pdf:\n', a)
print('gdf:\n', b)

**Expected behavior**
iloc should give the consistent results.

**Environment details (please complete the following information):**
 - Environment location: CentOS 7.6.1810 Linux host
 - Method of cuDF install: conda
 - Software version: cudf 0.7.2+0.g3ebd286.dirty, cuda 10.0, python 3.7.3
 

**Additional context**

**Comment by beckernick** [comment]
Thanks for the bug report @seraphzl !

We recently improved our indexing to resolve several issues, including this one. Let us know if you still run into this issue with a fresh installation of cuDF 0.8. Closing for now, but please feel free to reopen it if the bug persists.
