### ISSUE TITLE
Error while converting panda data frame into cudf data frame

### ISSUE THREAD

**Issue by vp2527** [rapidsai/cudf#1835]
Every time I try to convert a panda df to a cudf df I get the following error. What could've gone wrong?
<img width="909" alt="Screenshot 2019-05-23 at 4 30 57 PM" src="https://user-images.githubusercontent.com/35620007/58247996-a0de9500-7d78-11e9-9617-007658bd0a91.png">
<img width="388" alt="Screenshot 2019-05-23 at 4 31 02 PM" src="https://user-images.githubusercontent.com/35620007/58248009-a76d0c80-7d78-11e9-8114-f27d2aaa5cfc.png">

**Comment by thomcom** [comment]
Thanks @vp2527 this definitely looks like a series issue. What dtypes are in your original pandas dataframe? Can you give me a minimal reproducer code that allows me to reproduce the error without having your source data?

What's the output of
`X.dtypes`
?

Please review the set of questions that are asked when you file an issue and include as much information as you can with this one.

**Comment by vp2527** [comment]
Initially I had the output of X.dtypes all as objects. Conversion to the cudf data frame was giving me an error then. Then I converted the entire type to int64 and the conversion to the cudf data frame did not give me an error. I could run the code successfully. I am not sure if its supposed to work this way.


<img width="435" alt="Screenshot 2019-05-27 at 12 39 04 PM" src="https://user-images.githubusercontent.com/35620007/58401884-97a53f00-807c-11e9-9964-58ae03875f49.png">
<img width="593" alt="Screenshot 2019-05-27 at 12 39 43 PM" src="https://user-images.githubusercontent.com/35620007/58401893-9a079900-807c-11e9-912a-96a2f6973f14.png">

**Comment by thomcom** [comment]
Were you able to resolve your issue, then? cuDF is very specific about types, so that it can take advantage of GPU acceleration, whereas Pandas allows almost anything to go into the dataframe. :)

Is this issue closed?

**Comment by kkraus14** [comment]
> Initially I had the output of X.dtypes all as objects. Conversion to the cudf data frame was giving me an error then. Then I converted the entire type to int64 and the conversion to the cudf data frame did not give me an error. I could run the code successfully. I am not sure if its supposed to work this way.
> 
> <img alt="Screenshot 2019-05-27 at 12 39 04 PM" width="435" src="https://user-images.githubusercontent.com/35620007/58401884-97a53f00-807c-11e9-9964-58ae03875f49.png">
> 
> <img alt="Screenshot 2019-05-27 at 12 39 43 PM" width="593" src="https://user-images.githubusercontent.com/35620007/58401893-9a079900-807c-11e9-912a-96a2f6973f14.png">

This is expected, we currently only support `object` dtypes for strings.
