### ISSUE TITLE
[QST] Does the Parquet_reader support List columns

### ISSUE THREAD

**Issue by darylparker** [rapidsai/cudf#1836]
I'm trying to use the cuDF project to decode parquet files. I've been testing with various simple files to see the capabilities of the library. It seems to me that there are issues with decoding Parquet files that have LIST columns. E.g a simple file with 5 rows of 4 columns one of which is a list/array column should look something like (Apache Spark or PyArrow output):
```
+-------+------+--------------------+---------+
|byteCol|intCol|primArray           |longCol  |
+-------+------+--------------------+---------+
|8      |320   |[10, 11, 12]        |73763636 |
|12     |640   |[13, 14, 15, 16]    |173763636|
|16     |1280  |[17, 18]            |273763636|
|18     |2560  |[19, 20, 21, 22, 23]|373763636|
|20     |5120  |[24, 25]            |473763636|
+-------+------+--------------------+---------+
```
however the output from libcudf (using cudf python wrapper in the Docker image) looks like below 
```
   byteCol  intCol  primArray.list.element    longCol
0        8     320                      10   73763636
1       12     640                          173763636
2       16    1280                      11  273763636
3       18    2560                          373763636
4       20    5120                          473763636
```
Running my own C++ code example with the debug turned on in parquet_reader.cu gives the following output. 
```
[+] Metadata:
 version = 1
 created_by = "parquet-mr version 1.10.1 (build a89df8f9932b6ef6633d06069e50c9b7970bebd1)"
 schema (7 entries):
  [0] type=0, name="spark_schema", num_children=4, rep_type=0, max_def_lvl=0, max_rep_lvl=0
  [1] type=1, name="byteCol", num_children=0, rep_type=0, max_def_lvl=0, max_rep_lvl=0
  [2] type=1, name="intCol", num_children=0, rep_type=0, max_def_lvl=0, max_rep_lvl=0
  [3] type=0, name="primArray", num_children=1, rep_type=1, max_def_lvl=1, max_rep_lvl=0
  [4] type=0, name="list", num_children=1, rep_type=2, max_def_lvl=2, max_rep_lvl=1
  [5] type=1, name="element", num_children=0, rep_type=0, max_def_lvl=2, max_rep_lvl=1
  [6] type=2, name="longCol", num_children=0, rep_type=0, max_def_lvl=0, max_rep_lvl=0
 num rows = 5
 num row groups = 1
 num columns = 4
[+] Selected row groups: 1
[+] Selected columns: 1
[+] Selected skip_rows: 0 num_rows: 5
  0: name=primArray.list.element size=5 type=3 data=0 valid=0
[+] Column Chunk Description
  2: primArray.list.element start_row=0, num_rows=5, codec=1, num_values=16
     total_compressed_size=127 total_uncompressed_size=124
     schema_idx=5, type=1, type_width=0, max_def_level=2, max_rep_level=1
     data_page_offset=138, index_page_offset=0, dict_page_offset=0
[+] Chunk Information
  0: comp_data=140096592413184, comp_size=127, num_values=16
     start_row=0 num_rows=5 max_def_level=2 max_rep_level=1
     data_type=1 def_level_bits=2 rep_level_bits=1
     num_data_pages=1 num_dict_pages=0 max_num_pages=0
[+] Page Header Information
  0: comp_size=80, uncomp_size=77, num_values=16, chunk_row=0, num_rows=16
     chunk_idx=0, flags=0, encoding=0, def_level=3 rep_level=3, valid_count=0
[+] Compression
 Total compressed size: 77
 Number of compressed pages: 1
  gzip:    0 
  snappy: 1
[+] Page Data Information
  0: valid_count=2/5
Value : 10 , valid: true
Value : 27268353 , valid: false
Value : 11 , valid: true
Value : 352720128 , valid: false
Value : 68688902 , valid: false
``` 
Looking at the code it seems the metadata for the column is decoded correctly (sees there should be 16 values) but the data gets decoded as just 5 values.  Am I missing something here or is this a bug??

**Comment by ayushdg** [comment]
The io team might be able to comment on whether the metadata decoding logic is a bug or not. 
But as of now my understanding is that cudf does not support nested columns and does not support the type of a column to be a list. Supported types currently include numeric types, strings, bools, datetime and categorical.

**Comment by OlivierNV** [comment]
@ayushdg is correct: lists, maps (any type with multiple values per record) are not currently supported (this is visible in the metadata dump as max_rep_lvl != 0).

**Comment by darylparker** [comment]
Thanks for the clarification. Are there any plans for adding support for these types of repeated columns? I didn't find anything specific in the issues/features. Has anyone already started looking at this?

**Comment by randerzander** [comment]
Hi @darylparker can you provide some more details about what you want to do with nested columns?

We're discussing how to approach this problem, but it wont be for a few releases.

Do you need to operate on individual values in the nested list, or just be able to read them from files generated by an upstream process?

Supposing you were able to read them into a delimited string, would that be a useful stopgap for you? If so, and you needed to access individual elements, you could use string split functions to do so.
