### ISSUE TITLE
[QST] Integrating in C/C++ project

### ISSUE THREAD

**Issue by Tongdongq** [rapidsai/cudf#1837]
All examples and tutorials I found were focussed on usage in a Python environment. I have an existing C++ project (and a C project) that I would like to use with RAPIDS. Is this possible and does this make sense?

**Comment by jrhemstad** [comment]
Yes! This is absolutely possible and encouraged.

I gave a talk giving an overview of the C++ side of RAPIDS cuDF (libcudf) that should help you get started. You can watch a recording or get the slides here: https://on-demand-gtc.gputechconf.com/gtcnew/sessionview.php?sessionName=s91043-rapids+cuda+dataframe+internals+for+c%2b%2b+developers

Note that we are in the middle of a pretty large overhaul of our C++ interface and internals. So expect these things to change (and become more pleasant) over the next few months. 

See: 
https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/docs/TRANSITIONGUIDE.md
https://github.com/rapidsai/cudf/issues/1443

**Comment by jrhemstad** [comment]
I'll leave this issue open if you have any other questions. If you come across particular issues/questions, feel free to open another issue.

If you'd find something you'd like to change/improve, we welcome PRs. You can check out our backlog of C++ issues [here](https://github.com/rapidsai/cudf/issues?q=is%3Aopen+is%3Aissue+label%3A%22libcudf+%28C%2B%2B%2FCUDA%29%22)

**Comment by rjammala** [comment]
@jrhemstad : I realize this is a closed question but commenting here because of the relevance. Do you have concrete C++ example of how to parse json using cudf? The conda commands are taking forever to run so I don't think the Python version is usable. Thanks for all the effort.

**Comment by kkraus14** [comment]
@rjammala what is in your conda environment that you're running the install on? We recently resolved some conda issues and have tested that installs should work as expected.

**Comment by rjammala** [comment]
this is what it looks like:
$ conda env list
# conda environments:
#
base                     /home/ubuntu/anaconda3
aws_neuron_mxnet_p36     /home/ubuntu/anaconda3/envs/aws_neuron_mxnet_p36
aws_neuron_tensorflow_p36     /home/ubuntu/anaconda3/envs/aws_neuron_tensorflow_p36
chainer_p27              /home/ubuntu/anaconda3/envs/chainer_p27
chainer_p36              /home/ubuntu/anaconda3/envs/chainer_p36
mxnet_p27                /home/ubuntu/anaconda3/envs/mxnet_p27
mxnet_p36                /home/ubuntu/anaconda3/envs/mxnet_p36
python2                  /home/ubuntu/anaconda3/envs/python2
python3               *  /home/ubuntu/anaconda3/envs/python3
pytorch_p27              /home/ubuntu/anaconda3/envs/pytorch_p27
pytorch_p36              /home/ubuntu/anaconda3/envs/pytorch_p36
tensorflow2_p27          /home/ubuntu/anaconda3/envs/tensorflow2_p27
tensorflow2_p36          /home/ubuntu/anaconda3/envs/tensorflow2_p36
tensorflow_p27           /home/ubuntu/anaconda3/envs/tensorflow_p27
tensorflow_p36           /home/ubuntu/anaconda3/envs/tensorflow_p36

$ nvidia-smi
Mon Feb 10 17:59:05 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   30C    P0    24W / 300W |      0MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+


Please let me know if you need any other info.

**Comment by kkraus14** [comment]
@rjammala could you run `conda list` in the environment you're trying to install into?

**Comment by rjammala** [comment]
`$ conda list
# packages in environment at /home/ubuntu/anaconda3/envs/python3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.10           py36h306e16b_0  
anaconda-client           1.6.14                   py36_0  
anaconda-project          0.8.2            py36h44fb852_0  
argparse                  1.4.0                     <pip>
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.3                    py36_0  
astropy                   3.0.2            py36h3010b51_1  
attrs                     18.1.0                   py36_0  
Automat                   0.3.0                     <pip>
autovizwidget             0.13.1                    <pip>
babel                     2.5.3                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0              py36hfa02d7e_1  
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2  
bcrypt                    3.1.7                     <pip>
beautifulsoup4            4.6.0            py36h49b8c8c_1  
bitarray                  0.8.1            py36h14c3975_1  
bkcharts                  0.2              py36h735825a_0  
blas                      1.0                         mkl  
blaze                     0.11.3           py36h4e06776_0  
bleach                    2.1.3                    py36_0  
blosc                     1.14.3               hdbcaa40_0  
bokeh                     1.0.4                    py36_0  
boto                      2.48.0           py36h6e4cd66_1  
boto3                     1.10.23                   <pip>
boto3                     1.10.19                    py_0  
botocore                  1.13.23                   <pip>
botocore                  1.13.19                    py_0  
bottleneck                1.2.1            py36haac1ea0_0  
bzip2                     1.0.6                h14c3975_5  
ca-certificates           2019.10.16                    0  
cached-property           1.5.1                     <pip>
cairo                     1.14.12              h8948797_3  
certifi                   2019.9.11                py36_0  
cffi                      1.11.5           py36h9745a5d_0  
characteristic            14.3.0                    <pip>
chardet                   3.0.4            py36h0f667ec_1  
click                     6.7              py36h5253387_0  
cloudpickle               0.5.3                    py36_0  
clyent                    1.2.2            py36h7e57e65_1  
colorama                  0.3.9            py36h489cec4_0  
contextlib2               0.5.5            py36h6c84a62_0  
cryptography              2.2.2            py36h14c3975_0  
cryptography              2.8                       <pip>
curl                      7.60.0               h84994c4_0  
cycler                    0.10.0           py36h93f1223_0  
cython                    0.28.2           py36h14c3975_0  
Cython                    0.28.4                    <pip>
cytoolz                   0.9.0.1          py36h14c3975_0  
dask                      0.17.5                   py36_0  
dask-core                 0.17.5                   py36_0  
datashape                 0.5.4            py36h3ad6b5c_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
defusedxml                0.6.0                      py_0  
distributed               1.21.8                   py36_0  
docker                    4.1.0                     <pip>
docker-compose            1.25.0                    <pip>
dockerpty                 0.4.1                     <pip>
docopt                    0.6.2                     <pip>
docutils                  0.14             py36hb0f60f5_0  
entrypoints               0.2.3            py36h1aec115_2  
environment-kernels       1.1.1                     <pip>
et_xmlfile                1.0.1            py36hd6bccc3_0  
expat                     2.2.5                he0dffb1_0  
fastcache                 1.0.2            py36h14c3975_2  
ffmpeg                    4.0.2                ha0c5888_2    conda-forge
filelock                  3.0.4                    py36_0  
flask                     1.0.2                    py36_1  
flask-cors                3.0.4                    py36_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0             hf484d3e_1005    conda-forge
freetype                  2.9.1                h8a8886c_1  
fribidi                   1.0.5                h7b6447c_0  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    1.3.0            py36h14c3975_0  
glib                      2.56.1               h000015b_0  
glob2                     0.6              py36he249c77_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36hc8893dd_2  
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
graphite2                 1.3.11               h16798f4_2  
graphviz                  2.40.1               h21bd128_2  
greenlet                  0.4.13           py36h14c3975_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py36h989c5e5_3  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.2               hba1933b_1  
hdijupyterutils           0.13.1                    <pip>
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h9c2bf20_1  
idna                      2.6              py36h82fb2a8_1  
imageio                   2.3.0                    py36_0  
imagesize                 1.0.0                    py36_0  
intel-openmp              2018.0.0                      8  
ipykernel                 4.8.2                    py36_0  
ipyparallel               6.2.2                     <pip>
ipython                   6.4.0                    py36_0  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.2.1                    py36_0  
ipywidgets                7.4.0                     <pip>
isort                     4.3.4                    py36_0  
itsdangerous              0.24             py36h93cc618_1  
jasper                    2.0.14               h07fcdf6_1  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4                      py36_0  
jedi                      0.12.0                   py36_1  
jinja2                    2.10             py36ha16c418_0  
jmespath                  0.9.4                      py_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.4.0            py36h7c827e3_0  
jupyterlab                0.32.1                   py36_0  
jupyterlab_launcher       0.10.5                   py36_0  
kiwisolver                1.0.1            py36h764f252_0  
krb5                      1.14.2               hcdc1b81_6  
lazy-object-proxy         1.3.1            py36h10fcdad_0  
libcurl                   7.60.0               h1ad7b7a_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3  
libglu                    9.0.0             hf484d3e_1000    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libopencv                 3.4.2                hb342d67_1  
libpng                    1.6.34               hb9fc6fc_0  
libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
libsodium                 1.0.16               h1bed415_0  
libssh2                   1.8.0                h9cfc8f7_4  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.9                he85c1e1_1  
libtool                   2.4.6                h544aabb_3  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
libxslt                   1.1.32               h1312cb7_0  
llvmlite                  0.23.1           py36hdbcaa40_0  
locket                    0.2.0            py36h787c0ad_1  
lxml                      4.2.1            py36h23eabaa_0  
lzo                       2.10                 h49e0be7_2  
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.2.3            py36hb69df0a_0  
matplotlib                3.0.3                     <pip>
mccabe                    0.6.1            py36h5ad9710_1  
mistune                   0.8.3            py36h14c3975_1  
mkl                       2018.0.2                      1  
mkl-service               1.1.2            py36h17a0993_4  
mkl_fft                   1.0.1            py36h3010b51_0  
mkl_random                1.0.1            py36h629b387_0  
mock                      3.0.5                     <pip>
more-itertools            4.1.0                    py36_0  
mpc                       1.0.3                hec55b23_5  
mpfr                      3.1.5                h11a74b3_2  
mpi                       1.0                     openmpi    conda-forge
mpmath                    1.0.0            py36hfeacd6b_2  
msgpack                   0.6.0                     <pip>
msgpack-python            0.5.6            py36h6bb024c_0  
multipledispatch          0.5.0                    py36_0  
nb_conda                  2.2.1                    py36_2    conda-forge
nb_conda_kernels          2.2.2                    py36_0    conda-forge
nbconvert                 5.4.1                    py36_3  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.1                  hf484d3e_0  
nettle                    3.3                           0    conda-forge
networkx                  2.1                      py36_0  
nltk                      3.3.0                    py36_0  
nose                      1.3.7            py36hcdf7029_2  
notebook                  5.5.0                    py36_0  
numba                     0.38.0           py36h637b7d7_0  
numexpr                   2.6.5            py36h7bf3b9c_0  
numpy                     1.14.3           py36hcd700cb_1  
numpy-base                1.14.3           py36h9be14a7_1  
numpydoc                  0.8.0                    py36_0  
odo                       0.5.1            py36h90ed295_0  
olefile                   0.45.1                   py36_0  
opencv                    3.4.2            py36h6fd60c2_1  
openh264                  1.8.0             hdbcaa40_1000    conda-forge
openmpi                   3.1.0                h26a2512_3    conda-forge
openpyxl                  2.5.3                    py36_0  
openssl                   1.0.2t               h7b6447c_1  
packaging                 17.1                     py36_0  
pandas                    0.24.2           py36he6710b0_0  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
pango                     1.42.3               h8589676_0  
paramiko                  2.6.0                     <pip>
parso                     0.2.0                    py36_0  
partd                     0.3.8            py36h36fd896_0  
patchelf                  0.9                  hf79760b_2  
path.py                   11.0.1                   py36_0  
pathlib2                  2.3.2                    py36_0  
patsy                     0.5.0                    py36_0  
pcre                      8.42                 h439df22_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.5.0                    py36_0  
pickleshare               0.7.4            py36h63277f8_0  
pillow                    5.2.0            py36heded4f4_0  
pip                       10.0.1                   py36_0  
pixman                    0.34.0               hceecf20_3  
pkginfo                   1.4.2                    py36_1  
plotly                    4.3.0                     <pip>
pluggy                    0.6.0            py36hb689045_0  
ply                       3.11                     py36_0  
prompt_toolkit            1.0.15           py36h17d85b1_0  
protobuf                  3.6.1           py36hf484d3e_1001    conda-forge
protobuf3-to-dict         0.1.5                     <pip>
psutil                    5.4.5            py36h14c3975_0  
psycopg2                  2.7.5                     <pip>
ptyprocess                0.5.2            py36h69acd42_0  
py                        1.5.3                    py36_0  
py-opencv                 3.4.2            py36hb342d67_1  
py4j                      0.10.7                    <pip>
pycodestyle               2.4.0                    py36_0  
pycosat                   0.6.3            py36h0a5515d_0  
pycparser                 2.18             py36hf9f622e_1  
pycrypto                  2.6.1            py36h14c3975_8  
pycurl                    7.43.0.1         py36hb7f436b_0  
pyflakes                  1.6.0            py36h7bd6a15_0  
pygal                     2.4.0                     <pip>
pygments                  2.2.0            py36h0d3125c_0  
pykerberos                1.2.1            py36h14c3975_0  
pylint                    1.8.4                    py36_0  
PyNaCl                    1.3.0                     <pip>
pyodbc                    4.0.23           py36hf484d3e_0  
pyopenssl                 18.0.0                   py36_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.9.2            py36h751905a_0  
pysocks                   1.6.8                    py36_0  
pyspark                   2.3.2                     <pip>
pytables                  3.4.3            py36h02b9ad4_2  
pytest                    3.5.1                    py36_0  
pytest-arraydiff          0.2                      py36_0  
pytest-astropy            0.3.0                    py36_0  
pytest-doctestplus        0.1.3                    py36_0  
pytest-openfiles          0.3.0                    py36_0  
pytest-remotedata         0.2.1                    py36_0  
python                    3.6.5                hc3d631a_2  
python-dateutil           2.7.3                    py36_0  
pytz                      2018.4                   py36_0  
pywavelets                0.5.2            py36he602eb0_0  
pyyaml                    3.12             py36h14c3975_1  
pyzmq                     17.0.0           py36h14c3975_0  
qt                        5.9.6                h52aff34_0  
qtawesome                 0.4.4            py36h609ed8c_0  
qtconsole                 4.3.1            py36h8f73b5b_0  
qtpy                      1.4.1                    py36_0  
readline                  7.0                  ha6073c6_4  
requests                  2.20.0                py36_1000    conda-forge
requests-kerberos         0.12.0                    <pip>
retrying                  1.3.3                     <pip>
rope                      0.10.7           py36h147e2ec_0  
ruamel_yaml               0.15.35          py36h14c3975_1  
s3fs                      0.1.5                    py36_0  
s3transfer                0.2.1                    py36_0  
sagemaker                 1.44.0                    <pip>
sagemaker-pyspark         1.2.6                     <pip>
scikit-image              0.13.1           py36h14c3975_1  
scikit-learn              0.20.3                    <pip>
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     1.1.0            py36hfc37229_0  
seaborn                   0.8.1            py36hfad7ec4_0  
send2trash                1.5.0                    py36_0  
setuptools                39.1.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36h7a266c3_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0           py36h372c433_1  
snappy                    1.1.7                hbae5bb6_3  
snowballstemmer           1.2.1            py36h6febd40_0  
sortedcollections         0.6.1                    py36_0  
sortedcontainers          1.5.10                   py36_0  
sparkmagic                0.12.5                    <pip>
sphinx                    1.7.4                    py36_0  
sphinxcontrib             1.0              py36h6d0f590_1  
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1  
spyder                    3.2.8                    py36_0  
sqlalchemy                1.2.7            py36h6b74fdf_0  
SQLAlchemy                1.2.11                    <pip>
sqlite                    3.23.1               he433501_0  
statsmodels               0.9.0            py36h3010b51_0  
sympy                     1.1.1            py36hc6d1c1c_0  
tbb                       2018.0.4             h6bb024c_1  
tbb4py                    2018.0.4         py36h6bb024c_1  
tblib                     1.3.2            py36h34cf8b6_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h8cadb63_0  
texttable                 1.6.2                     <pip>
tk                        8.6.7                hc745277_3  
toolz                     0.9.0                    py36_0  
tornado                   5.0.2                    py36_0  
traitlets                 4.3.2            py36h674d592_0  
typing                    3.6.4                    py36_0  
unicodecsv                0.14.1           py36ha668878_0  
unixodbc                  2.3.6                h1bed415_0  
urllib3                   1.23                     py36_0  
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
websocket-client          0.56.0                    <pip>
werkzeug                  0.14.1                   py36_0  
wheel                     0.31.1                   py36_0  
widgetsnbextension        3.2.1                    py36_0  
widgetsnbextension        3.4.2                     <pip>
wrapt                     1.10.11          py36h28b7045_0  
x264                      1!152.20180806       h14c3975_0    conda-forge
xlrd                      1.1.0            py36h1db9f0c_1  
xlsxwriter                1.0.4                    py36_0  
xlwt                      1.3.0            py36h7b00a1f_0  
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                h439df22_0  
zict                      0.1.3            py36h3a3bf81_0  
zlib                      1.2.11               ha838bed_2  `

**Comment by kkraus14** [comment]
Some things that stick out from a quick glance:
```
numba 0.38.0 --> we require "numba>=0.46.0"

dask 0.17.5 py36_0
dask-core 0.17.5 py36_0 --> this is an extremely old version at this point, we require a relatively new version where the newer the better, would suggest "dask>=2.8.0"

pandas 0.24.2 py36he6710b0_0 --> we require "pandas>=0.25"
```
