### ISSUE TITLE
[FEA]Support for Binary Operator functions like add/sub

### ISSUE THREAD

**Issue by skmatti** [rapidsai/cudf#1851]
Pandas allows binary operations using both operator as well using an operator function as shown below:
```
import pandas as pd

df = pd.DataFrame({'x':[1, 2], 'y':[3,4]})
df1 = df + df  # using operator
df2 = df.add(df) # using a function

df3 = df + 1
df4 = df.add(1)
```

Currently `cudf` has support only for operator based binary operations. It would be nice to have function based support as well.

**Comment by devavret** [comment]
@randerzander do you need all the other argument support as well? There's axis, level, fill_value. If so, this might not be that trivial.

**Comment by randerzander** [comment]
@skmatti can you confirm whether the basic example you gave is what you need, or if you require the additional params devavret listed?

**Comment by skmatti** [comment]
We need only `fill_value` argument support for our use-case.
