### ISSUE TITLE
[FEA] 'columns' parameter for DataFrame's drop method

### ISSUE THREAD

**Issue by floscha** [rapidsai/cudf#1860]
While it is certainly a matter of taste, I find df.drop(columns=['y', 'z']) more intuitive than df.drop(['y', 'z'], axis=1) and would appreciate compatible APIs between pandas and cuDF.

If approved, I can happily create a PR to implement this feature.

**Comment by randerzander** [comment]
That would be a welcome contribution, @floscha !

**Comment by kkraus14** [comment]
Fixed in 0.10.
