### ISSUE TITLE
[FEA] The conda environment should automatically set NUMBAPRO_NVVM, NUMBAPRO_LIBDEVICE

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1862]
At the moment, it is not enough to merely `conda activate cudf` in order to perform various cudf-related actions - in particular, running the Python tests (`py.test`): One needs [to set the environment variables `NUMBAPRO_NVVM` and `NUMBAPRO_LIBDEVICE`](https://github.com/rapidsai/cudf/blob/feec0c5e21fef4a416c77656d1d3f43205aeddc1/CONTRIBUTING.md#build-from-source).

But - it is possible to have these variables set by `conda activate`, using files under the environment prefix: See [this StackOverflow post](https://stackoverflow.com/a/31615307/1593077). Essentially, this is done via `$CONDA_PREFIX/etc/conda/activate.d`.

**Comment by harrism** [comment]
I wrote this a while back, which discusses using `etc/conda/activate.d` for all env variables when building from source. https://docs.google.com/document/d/1JcZcrQ156zk7TK1Wnad_Nz715SNyyeNlySismr64Djk/edit#heading=h.tjxhz15codzy

Hope it helps.

But I don't think we can make `activate.d` part of the conda env description, so I'm not sure this can be added to source control.

**Comment by eyalroz** [comment]
@harrism : Why not create that `activate.d` script as part of the cudf installation process? Either done during `make install`, or the `python setup.py`?

**Comment by harrism** [comment]
1. If you read my document, some of us eschew `make install`, for good reasons.
2. `python setup.py` depends on the LD_LIBRARY_PATH and PYTHONPATH environment variables that are needed because of 1.

**Comment by eyalroz** [comment]
1. Ok, but `make install` is the default thing people would do unless they know better. So why not improve it somewhat?
2. How is this dependence prevent `python setup.py` from setting these environment variables?

**Comment by harrism** [comment]
I was merely providing assistance, not closing your issue.

**Comment by kkraus14** [comment]
This is now deprecated and instead uses the `cudatoolkit` conda package, `CUDA_HOME` environment variable, or typical CUDA install locations. Closing this.
