### ISSUE TITLE
[FEA] Support quantiles as a groupby aggregation

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#1866]
**Is your feature request related to a problem? Please describe.**
I have a use case where I need to calculate percentiles on the groups after performing a groupby operation. Cudf currently supports quantiles on whole columns but not on the grouped column

**Describe the solution you'd like**
Support a groupby quantile aggregation somewhat similar to [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.quantile.html) 

**Describe alternatives you've considered**
One workaround is to use the legacy groupby and write a custom method to perform the operation.

**Comment by kkraus14** [comment]
Duplicate of #619
