### ISSUE TITLE
[FEA] Add libcudf any() and all() reductions

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#1874]
**Is your feature request related to a problem? Please describe.**

Currently cuDF Python implements any() and all() for a column by calling libcudf's min() and max() (see #1863). libcudf should provide any() and all() instead. They can be made faster and also give us better control over semantics.

**Describe the solution you'd like**
It would be faster to provide an optimized any() and all() that first check that the values are non-zero to get a boolean per element and then use bitwise reductions in CUDA for a faster reduction.

**Describe alternatives you've considered**
It currently works, so this is just a potential optimization.

**Comment by harrism** [comment]
@kovaltan FYI in case you have thoughts on this.

**Comment by kovaltan** [comment]
I agree to have `any` and `all` function in cudf for better control over semantics.
But I suspect about the potential optimization.

> It would be faster to provide an optimized any() and all() that first check that the values are non-zero to get a boolean per element and then use bitwise reductions in CUDA for a faster reduction.

The current implementation of reduction has already output dtype option.
For non boolean column, if we set output_dtype = bool8 and do reduction `min` (for all), or `max` (for any), 
the reducntion kernel cast a element into cudf::bool and then do reduction for rows.
The current implementation uses 1 byte `atomicMin` for cudf::bool reduction, there would be a room for optimization.
But in future, I'm thinking to re-implement reduction using null supported iterator given by PR #1833, then the implementation will use cub and it would be well optimised.

Btw, I've found a bug about `all` and `any` of integer column, and fixed it, I will file it later.

**Comment by harrism** [comment]
In my experience even CUB doesn't have an optimized 1-bit-per-boolean reduction (i.e. using `__popc() or `__syncthreads_and()` or `__syncthreads_or()`.

**Comment by rgsl888prabhu** [comment]
> In my experience even CUB doesn't have an optimized 1-bit-per-boolean reduction (i.e. using `__popc()` or `__syncthreads_and()`/`__syncthreads_or()`.

Why not use thrust::all_of and thrust::any_of ?

**Comment by jrhemstad** [comment]
> > In my experience even CUB doesn't have an optimized 1-bit-per-boolean reduction (i.e. using `__popc()` or `__syncthreads_and()`/`__syncthreads_or()`.
> 
> @harrism Why not use thrust::all_of and thrust::any_of ?

`thrust::all_of/any_of` are slow and should not be used. See: https://github.com/thrust/thrust/issues/1016

**Comment by karthikeyann** [comment]
faster early out for `any_of` and `all_of`
https://github.com/thrust/thrust/issues/1016#issuecomment-542867313

**Comment by jrhemstad** [comment]
> faster early out for `any_of` and `all_of`
> [thrust/thrust#1016 (comment)](https://github.com/thrust/thrust/issues/1016#issuecomment-542867313)

@karthikeyann Your results in that issue are fishy/impossible.

**Comment by karthikeyann** [comment]
Yes. looked into it. it had a bug. updating it now.
