### ISSUE TITLE
[BUG] Multiindex groupby aggregation functions called on columns directly returns empty dataframes

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1889]
As discussed in https://github.com/rapidsai/cudf/pull/1882, the following groupby usage pattern (as opposed to the agg API) produces an empty dataframe

```python
import cudf
df = cudf.DataFrame()
df['key'] = [0, 0, 1, 1, 2, 2, 2]
df['val'] = [0, 1, 2, 3, 4, 5, 6]
df['val1'] = [0, 1, 2, 3, 4, 5, 6]
df['mult'] = df['key'] * df['val']

df.groupby(['key', 'val']).mult.mean()
```

**Comment by thomcom** [comment]
Nick when it is convenient can you validate that this is fixed and close it?

**Comment by kkraus14** [comment]
Confirmed this works now. Closing.
