### ISSUE TITLE
[BUG] core dumped when the column of dataset is large

### ISSUE THREAD

**Issue by pengsnv** [rapidsai/cudf#1893]
```python
import xgboost as xgb
import numpy as np
from sklearn.model_selection import train_test_split
import time
X=np.random.randint(100,size=(2048,331072),dtype=np.int32)
y=np.random.randint(2,size=2048,dtype=np.int32)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.75, train_size=0.25,
                                                    random_state=42)
num_round = 10
param = {'objective': 'multi:softmax', 
         'num_class': 8, 
         'tree_method': 'gpu_hist', 
         'n_gpus': -1,
         }
dtrain = xgb.DMatrix(X_train, label=y_train)
dtest = xgb.DMatrix(X_test, label=y_test)
gpu_res = {} 
tmp = time.time()
xgb.train(param, dtrain, num_round, evals=[(dtest, 'test')], evals_result=gpu_res)
print("GPU Training Time: %s seconds" % (str(time.time() - tmp)))
```

I run the above script within container rapidsai/rapidsai:0.7-cuda10.0-runtime-ubuntu18.04-gcc7-py3.7, on DGX-1.
The script will crash when the column of X is up to 331072, although the X is just about 3GB.
The track trace is:
`terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: invalid configuration argument
Aborted (core dumped)`
 Matthew Jones <majones@nvidia.com> suggests posting an issue here. 
Can this bug be fixed?

**Comment by kkraus14** [comment]
There's no cuDF related code in here as far as I can see. This is pure XGBoost code, so I believe this issue should be moved elsewhere, possibly to the XGBoost repo?

**Comment by datametrician** [comment]
Agreed/closing. @mt-jones asked @pengsnv to test on the latest xgb version and then file an issue on their GitHub.

**Comment by tqslj2** [comment]
hi, i've just have the same isue with a 4G csv using cudf, but everything is ok with a csv file which is smaller than 3G, so have you solve this problem?  tks.

**Comment by harrism** [comment]
The above issue was unrelated to cuDF. I suggest if you have an issue that involves cuDF, file a new issue with complete description, system details, and reproduction instructions (follow the instructions displayed when you open the issue).  Thanks!
