### ISSUE TITLE
[FEA] libcudf scatter scalar

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1894]
There's currently an implementation of scatter in libcudf that expects a scatter map and a dense buffer of the same length of the scatter map to use for the values to scatter. Many situations in Python the user wants to provide a scatter map and a scalar value to use for all associated locations in the scatter map. Instead of filling a dense buffer with the scalar, we should provide a scatter scalar implementation as it would be faster and have less memory pressure.

**Comment by jrhemstad** [comment]
@kkraus14 is there any desire to have this work on a DataFrame/table?

For example:

```
void scalar_scatter(gdf_scalar value, gdf_column * destination, gdf_column scatter_map); // single column
```
vs.
```
void scalar_scatter(std::vector<gdf_scalar> values, cudf::table * destination, gdf_column scatter_map); // table
```

where `values[i]` will be scattered to column `i` in the `destination` table.
