### ISSUE TITLE
[FEA] libcudf functions to convert table to/from 2d dense arrays

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#1898]
Ideally with parameters to specify properties like strides, C vs Fortran ordering, etc.

**Comment by vyasr** [comment]
Based on timing, I'm going to guess that this request was related to #1790. I'll keep that open as the core feature request, and if and when we decide to tackle enabling sparse data storage in cudf we can revisit how exactly that ought to be implemented across the different layers (Python/C++, etc).
