### ISSUE TITLE
[BUG] __version__ from conda package is dirty

### ISSUE THREAD

**Issue by asmeurer** [rapidsai/cudf#1900]
**Describe the bug**

I have the cudf 0.7.2 py37_0 Linux 64-bit conda package installed from the rapidsai conda channel. 

The version is

```
>>> cudf.__version__
'0.7.2+0.g3ebd286.dirty'
```

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

The version number for the released package should be just `'0.7.2'`.

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
 

**Additional context**

**Comment by kkraus14** [comment]
Stale and resolved as of recent releases.
