### ISSUE TITLE
[FEA] Adding string column to dataframe is slow

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#1907]
**Describe the bug**
Adding a string column directly is ~ 2x slower that first creating a nvstring and then allocating it to the column.  

**Steps/Code to reproduce bug**
```python
import cudf
import time
import nvstrings
input_lines = ['Test--String']*50_000_000

## Load strs to cudf directly
df = cudf.DataFrame()
st = time.time()
df['text']= input_lines
et = time.time()
print("Time taken to read directly = {}".format(et-st))
del df

## Load strs to nvstrings and then to divice
st = time.time()
df = cudf.DataFrame()
df['text'] = nvstrings.to_device(input_lines)
et = time.time()
print("Time taken to read via nvstrings = {}".format(et-st))
del df

```
Output:
```python
Time taken to read directly = 5.8345630168914795
Time taken to read via nvstrings = 3.1215779781341553
```

**Expected behavior**
I would hope for a similar performence
**Environment details (please complete the following information):**
 - Environment location Docker
 - Method of cuDF install: From source
 

**Additional context**
This perofrmence drop was greatly improved by a fixing a previous pr https://github.com/rapidsai/cudf/issues/1348 but still not as fast as it should be.

**Comment by kkraus14** [comment]
@VibhuJawa any chance you can run this through snakeviz and see where the time is going? Snakeviz: https://jiffyclub.github.io/snakeviz/

**Comment by shwina** [comment]
In #1915, we remove an expensive call `self._index.equals(series.index)`. Just curious if that helps performance

**Comment by kkraus14** [comment]
I'm guessing this has to do with the codepath for handling Python lists specifically in that it will first create a PyArrow array and then create the nvstrings instance from that PyArrow array. Is handing large Python lists efficiently really important?

**Comment by VibhuJawa** [comment]
@kkraus14 , I think you are right, From `snake-viz` it looks like that too. 

Snake-viz for casting using lists. 
`%snakeviz df['text']= input_lines`

![image](https://user-images.githubusercontent.com/4837571/59050868-519c6800-8840-11e9-9f8d-3f4659d20ca3.png)


Snake viz for creating series via nvstrings. 
`%snakeviz df['text']= nvstrings.to_device(input_lines)`

![image](https://user-images.githubusercontent.com/4837571/59050922-7db7e900-8840-11e9-9b57-5a1f27c416e7.png)


Sorry, for the delay in getting these.

**Comment by VibhuJawa** [comment]
> Is handing large Python lists more efficiently important? I would strongly prefer to avoid writing dtype inference code for host Python objects and rely on libraries like PyArrow, Pandas, and Numpy to handle that for us.

Yup, @kkraus14  is right,  exploring the code path and snake-viz tells us that:

We have two major areas where we spend time:

* `list` to `pyarrow.StringArray` conversion happening at:

https://github.com/rapidsai/cudf/blob/7312d4aa413eafdad28b67efccbc3dc15d9b5e27/python/cudf/dataframe/columnops.py#L461-L464

* `pyarrow.StringArray` to `nvstrings` conversion happening at:

https://github.com/rapidsai/cudf/blob/7312d4aa413eafdad28b67efccbc3dc15d9b5e27/python/cudf/dataframe/columnops.py#L297-L317

Will wait for further comments before adding any dtype inference code.

**Comment by kkraus14** [comment]
I would argue that handling large Python lists / tuples of strings isn't a case that we should spend effort optimizing. @randerzander any objections from your end?

If possible in your data source avoid creating Python lists and use a more efficient type like a PyArrow array if possible.

**Comment by randerzander** [comment]
@kkraus14 I think loading strings from memory will be somewhat common in streaming workloads.

What better approach would you suggest to someone pulling from some queue into host-memory before loading to cuDF?

**Comment by VibhuJawa** [comment]
So seems like `nvstrings` just casts  `numericals` as `nones` while `pandas`/`StringArrow` way casts the `numerical dtypes` into `strings` . 


```python
import cudf
import pandas
import nvstrings

ls = ['a',1e8,'b',100]
print('direct_cast/pyarrow: \n{}'.format(cudf.Series(ls).to_pandas()))
print('\n')
print('via nvstrings: \n{}'.format(cudf.Series(nvstrings.to_device(ls)).to_pandas()))
print("\n")
print("pandas cast : \n{}".format(pandas.Series(ls)))
```
Ouput:
```python
direct_cast/pyarrow: 
0              a
1    100000000.0
2              b
3            100
dtype: object


via nvstrings: 
0       a
1    None
2       b
3    None
dtype: object


pandas cast : 
0        a
1    1e+08
2        b
3      100
dtype: object
```

**Comment by kkraus14** [comment]
> @kkraus14 I think loading strings from memory will be common in streaming workloads.
> 
> What better approach would you suggest to someone pulling from some queue into host-memory before loading to cuDF?

When you say pulling from some queue into host memory, what type of Python object are you creating in host memory? My thought is that it's typically not a Python list as that would be relatively inefficient to create from any kind of in-memory representation. If we have to handle Python lists more efficiently then we can try to do so, but it will be a non-trivial task.

**Comment by kkraus14** [comment]
Resolved by libcudf++ refactor.
