### ISSUE TITLE
[BUG] cudf::apply_boolean_mask return value (gdf_column) has an invalid col_name pointer

### ISSUE THREAD

**Issue by jeanp413** [rapidsai/cudf#1913]
**Describe the bug**
cudf::apply_boolean_mask return value (gdf_column) has an invalid col_name pointer (garbage value).

**Steps/Code to reproduce bug**

- Call cudf::apply_boolean_mask.
- Check that the col_name attribute of the returned gdf_column has a garbage value.

**Expected behavior**
cudf::apply_boolean_mask return value (gdf_column) col_name attribute should be a null pointer.

**Comment by harrism** [comment]
See also #1904
