### ISSUE TITLE
[BUG] multiple aggregations hangs

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#1920]
When aggregating with a list of `agg` cudf hangs.

```python
import pandas as pd
import numpy as np
import cudf

df = pd.DataFrame({"x": np.random.randint(0, 5, size=10000), "y":
    np.random.normal(size=10000)})

cdf = cudf.from_pandas(df)

df.groupby("x").y.agg(["sum", "max"])

cdf.groupby("x").y.agg(["sum", 'max'])  # <-- hangs
```

I believe the issue is happening in `agg()` here:
https://github.com/rapidsai/cudf/blob/6d4f71b510053c638a179f1a083592c00e969cf8/python/cudf/groupby/groupby.py#L74

**Comment by kkraus14** [comment]
cc @thomcom

**Comment by thomcom** [comment]
Wrote a fix for this one @quasiben, coming up soon.

**Comment by quasiben** [comment]
Thanks!!!!
