### ISSUE TITLE
[DOC] Groupby.std() is a currently non existent function that needs to be removed from Docs

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#1928]
verified by Dante, Paul and others, Groupby.std() does not exist.  We should remove that from our official docs to avoid confusion and distrust of our docs

Location: https://rapidsai.github.io/projects/cudf/en/0.6.0/api.html#cudf.groupby.legacy_groupby.Groupby.std

**Comment by mike-wendt** [comment]
This should be updated and fixed for next release if it has not been done already, thanks!

**Comment by harrism** [comment]
Groupby.std() will exist after #2791

**Comment by harrism** [comment]
Groupby.std() now exists but I believe it needs Python bindings.

**Comment by harrism** [comment]
@shwina is this fixed by #4346 ?

**Comment by shwina** [comment]
Yes
