### ISSUE TITLE
[BUG] read_csv() misinterprets string with format XYZW-XY as Datetime

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#1929]
Here is an example where `read_csv` misinterprets the value `ABCE-01` as a datetime:

```
In [1]: import cudf                                                                                                                                                                                             

In [2]: cat test.csv                                                                                                                                                                                            
col1,col2
ABCE-01,PB01

In [3]: print(cudf.read_csv('test.csv'))                                                                                                                                                                        
                     col1  col2
0 1905-06-06T11:52:32.000  PB01
```

but it has no problems with `ABCDE-01`:

```
In [1]: import cudf                                                                                                                                                                                             

In [2]: cat test.csv                                                                                                                                                                                            
col1,col2
ABCDE-01,PB01

In [3]: print(cudf.read_csv('test.csv'))                                                                                                                                                                        
       col1  col2
0  ABCDE-01  PB01
```

**Comment by shwina** [comment]
This seems to be the underlying cause of #1918

**Comment by faywang123** [comment]
My work is  blocked. Please let me know when this problem can be fixed.

**Comment by beckernick** [comment]
@faywang123 are you able to temporarily work around this issue by explicitly passing dtypes to the `dtype` argument when reading the file?

```python
# using Ashwin's example from this issue

dtype_dict = {'col1':'str', 'col2':'str'}
df = cudf.read_csv('untitled.txt', dtype=dtype_dict)
print(df)
      col1  col2
0  ABCE-01  PB01
```

**Comment by faywang123** [comment]
ok.
Also, I attached a second zip file in issue #1918 to indicate that this type issue does not always happen. Please also take a look.

**Comment by faywang123** [comment]
Hit another roadblock:

  File "cudf_test_v5.py", line 15, in test_concat
    dfs = [cudf.read_csv(f,dtype_dict) for f in files]
  File "cudf_test_v5.py", line 15, in <listcomp>
    dfs = [cudf.read_csv(f,dtype_dict) for f in files]
  File "/home/fayw/conda/lib/python3.6/site-packages/cudf/io/csv.py", line 164, in read_csv
    index_col=index_col
  File "cudf/bindings/csv.pyx", line 44, in cudf.bindings.csv.cpp_read_csv
  File "cudf/bindings/csv.pyx", line 234, in cudf.bindings.csv.cpp_read_csv
AttributeError: 'dict' object has no attribute 'encode'

**Comment by mjsamoht** [comment]
I can confirm that `dataTypeDetection()` incorrectly infers `ABCE-01` as date-time  We need to check how to improve the data type detection without significantly increase complexity (and lower performance).

**Comment by faywang123** [comment]
@beckernick, How to resolve the encode issue?

**Comment by faywang123** [comment]
any update?

**Comment by j-ieong** [comment]
The way to go about this issue is probably to align our behavior with PANDAS. That is, default return the dates as strings unless `parse_dates` is set.

When the current behavior was implemented, strings were not supported yet so we always inferred and parsed datetime data. Now, we can optionally parse and possibly also support `keep_date_col`.
