### ISSUE TITLE
[BUG] str.cat should allow multiple inputs

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#1939]
**Describe the bug**
Pandas's `Series.str.cat` allows for list-like inputs for `others`. cuDF's implementation does not. 

As discussed in rapidsai/dask-cudf#272, this is blocking string concatenation in dask-cudf. A potential solution is also mentioned.

```python
import cudf
x = cudf.DataFrame({"b":["prefix"]*5,"c":["suffix"]*5})
​
print(x.b.str.cat(x.c))
​
tup = (x.c, x.b)
print(x.b.str.cat(tup))
0    prefixsuffix
1    prefixsuffix
2    prefixsuffix
3    prefixsuffix
4    prefixsuffix
dtype: object
<empty Series of dtype=float64>
```

**Comment by beckernick** [comment]
@galipremsagar can't assign you on the issue (not in the github group yet) but consider it assigned for all intents and purposes

**Comment by galipremsagar** [comment]
> @galipremsagar can't assign you on the issue (you're not in the github group yet) but consider it assigned for all intents and purposes

Sure, taken. Working on it.
