### ISSUE TITLE
[BUG] Hash functions need to be specialized for `cudf::bool8`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1942]
**Describe the bug**

`cudf::bool8` is defined such that `0 == false` and  `>0` is `true`. As such, hashing any two `cudf::bool8` values `a` and `b` should return identical hash values for `a,b ∈ [1, 255]`. However, the existing hash functions will return different hash values if `a` and `b` are two different values greater than zero. 

**Expected behavior**

The libcudf hash functions should be specialized for `cudf::bool8` such that they will match expected behavior above. 

https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/hash/hash_functions.cuh

**Comment by trxcllnt** [comment]
Closed by https://github.com/rapidsai/cudf/pull/3087
