### ISSUE TITLE
[BUG] JitCache suffers from "static initialization order fiasco" 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1950]
**Describe the bug**

There is a static, global `jitify::JitCache` object in `launcher.cpp`.
https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/binary/jit/core/launcher.cpp#L36

This is problematic for at least two reasons:
1. https://isocpp.org/wiki/faq/ctors#static-init-order
2. Is more subtle:
   - Constructing an instance of `jitify::JitCache` ultimately calls to `cudaFree(0)` to force initialization of the CUDA context.
   - Having a global, static `jitify::JitCache` means that ultimately we'll be calling into the CUDA runtime during library load, which is erroneous. 

**Expected behavior**

The static, global should be replaced with a function local static:
```
jitify::JitCache& get_jit_cache(){
   static jitify::JitCache JitCache;
   return JitCache
}
```

Despite [the ISOCPP's suggestion against doing so](https://isocpp.org/wiki/faq/ctors#construct-on-first-use-v2),  I believe we should use a function local static object vs. a function local static pointer to ensure that the `JitCache` destructor is called.

**Comment by devavret** [comment]
This was fixed in #1245 https://github.com/rapidsai/cudf/pull/1245/commits/538ebe3ac51d52c260e3ecd2d388f6fecbba76b7#diff-c9a49624f72ccf3e05fbc58ec2920c5aR30
