### ISSUE TITLE
[ENH] iterator driven reductions

### ISSUE THREAD

**Issue by kovaltan** [rapidsai/cudf#1953]
At study of benchmarking iterator at PR #1833 (null supported iterator), `cub::DeviceReduce` using iterator may be 3x faster than current `cudf::reduction` which is implemented by custome kernel using `cub::BlockReduce` + `atomics`.

And also the when dtype of the column is GDF_INT8 or GDF_INT16, `cudf::reduction` can be 1500x slower than `cub::DeviceReduce` using iterator, it is due to there is massive `atomicAdd`, and it is emulated by using `atomicCAS`.

The goal of this issue is to implement iterator driven reductions using single `cub::DeviceReduce` call after PR #1833 gets merged.

Below is the case which GDF_INT8 shows 1500x slower at iterator benchmark.
```
$ ./ITERATOR_BENCH 5000000 1000 a
Iterator performance test:
  column_size = 5000000
  num iterates = 1000

GDF_INT8
new allocation: 0
raw stream cub: 		1.27071e-05
iterator cub <false>: 	1.36032e-05
iterator cub <true>: 	2.43299e-05
new allocation: 1
raw stream cub: 		1.34921e-05
iterator cub <false>: 	1.21835e-05
iterator cub <true>: 	2.53243e-05
raw stream thust: 		0.000213109
iterator thust <false>: 	0.000209712
iterator thust <true>: 	0.000213171
raw stream cub::BlockReduce<false>: 	0.0200344
raw stream cub::BlockReduce<true>: 	0.0198559
```

**Comment by harrism** [comment]
Exciting!
