### ISSUE TITLE
[BUG] apply_boolean_mask filters for bool8 == 1 rather than != 0

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#1955]
**Describe the bug**
`boolean_mask_filter` masks on the bool8 value having the exact value of `1` rather than checking if it is a non-zero value.

**Expected behavior**
`apply_boolean_mask` would filter based on the mask values being any non-zero value rather than only the value of `1`.

**Comment by jrhemstad** [comment]
Are you actually seeing errors from this?

While you're correct that it checks `data[i] == cudf::true_v`:
https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/stream_compaction/stream_compaction.cu#L39

`operator==(bool8,bool8)` is specialized to cast both arguments to a `bool`:
https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/utilities/wrapper_types.hpp#L377

So this should be providing the desired behavior.

**Comment by jlowe** [comment]
> Are you actually seeing errors from this?

No, I just ran across the stream_compaction.cu#L39 when looking into something else and it looked backwards to me.

> operator==(bool8,bool8) is specialized to cast both arguments to a bool:

Ah, I missed the operator overrides for bool8!  Thanks, sorry for the noise.
