### ISSUE TITLE
add_column followed by @cuda.jit function passes reference causing changes to propagate 

### ISSUE THREAD

**Issue by egoolish** [rapidsai/cudf#196]
```
from pygdf import DataFrame as gdf
import pandas as pd
from numba import cuda

@cuda.jit
def mask_func(io_array):
    pos = cuda.grid(1)
    if pos < io_array.size:
        io_array[pos] = io_array[pos] - 10

df = pd.DataFrame()
for i in range(0, 4):
    df[str(i)] = [i, i+1, i+2, i+3, i+4, i+5, i+6]
my_gdf = gdf.from_pandas(df)
my_gdf.add_column('new_column', my_gdf['3'])
print(my_gdf)
mask_func[1, 512](my_gdf['new_column'].to_gpu_array())
print(my_gdf)
```
```
     0    1    2    3 new_column
0    0    1    2    3          3
1    1    2    3    4          4
2    2    3    4    5          5
3    3    4    5    6          6
4    4    5    6    7          7
5    5    6    7    8          8
6    6    7    8    9          9
     0    1    2    3 new_column
0    0    1    2   -7         -7
1    1    2    3   -6         -6
2    2    3    4   -5         -5
3    3    4    5   -4         -4
4    4    5    6   -3         -3
5    5    6    7   -2         -2
6    6    7    8   -1         -1
```

You can see that in the example, mask_func is called only on new_column, but the modifications to new_column are seen in column 3 as well. This behavior is not the case for non JIT operations, and such operations stop the pass by reference as seen here:

```
from pygdf import DataFrame as gdf
import pandas as pd
from numba import cuda

@cuda.jit
def mask_func(io_array):
    pos = cuda.grid(1)
    if pos < io_array.size:
        io_array[pos] = io_array[pos] - 10

df = pd.DataFrame()
for i in range(0, 4):
    df[str(i)] = [i, i+1, i+2, i+3, i+4, i+5, i+6]
my_gdf = gdf.from_pandas(df)
my_gdf.add_column('new_column', my_gdf['3'])
print(my_gdf)
my_gdf['new_column'] = my_gdf['new_column']+1
print(my_gdf)
mask_func[1, 512](my_gdf['new_column'].to_gpu_array())
print(my_gdf)
```
```
     0    1    2    3 new_column
0    0    1    2    3          3
1    1    2    3    4          4
2    2    3    4    5          5
3    3    4    5    6          6
4    4    5    6    7          7
5    5    6    7    8          8
6    6    7    8    9          9
     0    1    2    3 new_column
0    0    1    2    3          4
1    1    2    3    4          5
2    2    3    4    5          6
3    3    4    5    6          7
4    4    5    6    7          8
5    5    6    7    8          9
6    6    7    8    9         10
     0    1    2    3 new_column
0    0    1    2    3         -6
1    1    2    3    4         -5
2    2    3    4    5         -4
3    3    4    5    6         -3
4    4    5    6    7         -2
5    5    6    7    8         -1
6    6    7    8    9          0
```

**Comment by VibhuJawa** [comment]
To reproduce in 0.6 + cudf:
change the below line to
```
# mask_func[1, 512](my_gdf['new_column'].to_gpu_array()
mask_func[1, 512](my_gdf['new_column'].data.to_gpu_array())
```
The cause of the issue seems to be shallow copy of the [series].data being done here. 
Currently when we add a column, we create a shallow copy of the data, for which  we call the _copy_construct: 
https://github.com/rapidsai/cudf/blob/5b90ecd45c9302375a19bd1113f41c6b336274fd/python/cudf/dataframe/series.py#L140-L146

Which i am guessing calls the constructor :
https://github.com/rapidsai/cudf/blob/5b90ecd45c9302375a19bd1113f41c6b336274fd/python/cudf/dataframe/series.py#L72-L75

When we do  ```  my_gdf['new_column']+1 ```, we create a new series for which new memory is allocated and so we don't see this behavior. 


### Reproduction Code to see how .data is kept and how it changes with operations:

```python
import cudf
from cudf import DataFrame as gdf
print("cudf v {}".format(cudf.__version__))
import pandas as pd
from numba import cuda

@cuda.jit
def mask_func(io_array):
    pos = cuda.grid(1)
    if pos < io_array.size:
        io_array[pos] = io_array[pos] - 10

df = pd.DataFrame({"a":[1,2,3,4],"b":[1,2,3,4]})
    
my_gdf = gdf.from_pandas(df)
print("Inital DF \n")
print(my_gdf)
my_gdf.add_column('a_copy', my_gdf['a'])
my_gdf.add_column('b_copy', my_gdf['b'])
print("a_copy data_object {}\na data_object {}".format(my_gdf['a_copy'].data,my_gdf['a'].data))
print("b_copy data_object {}\nb data_object {}".format(my_gdf['b_copy'].data,my_gdf['b'].data))
print("---"*10)

#Operation done with jit 
mask_func[1, len(my_gdf['a_copy'])](my_gdf['a_copy'].data.to_gpu_array())

# #Operation done without jit
my_gdf['b_copy'] = my_gdf['b_copy']-10
print("After Operations DF \n")
print(my_gdf)
print("a_copy data_object {}\na data_object {}".format(my_gdf['a_copy'].data,my_gdf['a'].data))
print("b_copy data_object {}\nb data_object {}".format(my_gdf['b_copy'].data,my_gdf['b'].data))
```

### Output:
We can see that the .data reference is same for (a_copy and a)  and (b_copy and b) which is the cause of the issue. 
```

cudf v 0.7.0.dev0+307.gdf92f43e.dirty
Inital DF 

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
a_copy data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de06cda0>
a data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de06cda0>
b_copy data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de54c278>
b data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de54c278>
------------------------------
After Operations DF 

   a  b  a_copy  b_copy
0 -9  1      -9      -9
1 -8  2      -8      -8
2 -7  3      -7      -7
3 -6  4      -6      -6
a_copy data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de06cda0>
a data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de06cda0>
b_copy data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de35ebe0>
b data_object <cudf.dataframe.buffer.Buffer object at 0x7fa8de54c278>
``` 

## Approach to take:
We can change this behavior but it will make add column slow as we will have to create a copy of the data object.  I am not sure what is recommended here.  Thoughts @kkraus14  , @randerzander ?

**Comment by randerzander** [comment]
I couldn't find a reference to `add_column` in Pandas's docs at all. I might have missed it?

I propose two things:

1. Deprecate `add_column`. We already have the `copy` method which seems most like cuDF's add_column.
2. Add a `deep_copy` (or similarly named) kwarg to `to_gpu_array` 

I can see users sometimes wanting to modify the column in place, and sometimes wanting to create a copy that numba or other libraries are free to modify without modifying the original DataFrame.

Thoughts @kkraus14 ?

**Comment by VibhuJawa** [comment]
Regarding point 2, i believe that :

If call ```to_gpu_array()``` directly on the series/column object the default behavior is creating a deep copy.

Currently, If we do : 
```python
ar = my_gdf['a'].to_gpu_array() # This create a deep copy
ar = my_gdf['a'].data.to_gpu_array() # This refers to the original object
```
This is because when we call ```series.to_gpu_array()``` , it calls ```to_dense_buffer(fillna=fillna).to_gpu_array()``` and in  ```to_dense_buffer()``` we create a copy of the ```cudf.dataframe.buffer.Buffer``` object which holds the data.

 #### column.to_gpu_array() snippet.
https://github.com/rapidsai/cudf/blob/39a599b9e26224ddcefbf7aef3dd3dac93ce81b3/python/cudf/dataframe/column.py#L279-L293

 #### column.to_dense_buffer() snippet
https://github.com/rapidsai/cudf/blob/39a599b9e26224ddcefbf7aef3dd3dac93ce81b3/python/cudf/dataframe/column.py#L508-L509

**Comment by VibhuJawa** [comment]
## Pandas behavior
Pandas default behavior seems to be creating a copy while adding a column .

## Code to check pandas behavior
```python
import pandas as pd
import numpy as np


def mask_func(ar):
    for index in range(len(ar)):
        ar[index]-=10
        
df = pd.DataFrame({'a':[0,1,2,3,4]})
print("\ndf before changes")
print(df)
df['a_copy']=df['a']
print("\na_copy data_object {}\na data_object {}".format(df['a_copy'].data,df['a'].data))

ar = np.asarray(df['a_copy'].data)

mask_func(ar) #mask function

print("\ndf after changes")
print(df)
```
### Output
```
df before changes
   a
0  0
1  1
2  2
3  3
4  4

a_copy data_object <memory at 0x7f5fbc7bee88>
a data_object <memory at 0x7f5fbc7bedc8>

df after changes
   a  a_copy
0  0     -10
1  1      -9
2  2      -8
3  3      -7
4  4      -6

```

**Comment by VibhuJawa** [comment]
The default behavior currently for creating column seems to be creating shallow copies. 
```
my_gdf['a_copy'] = my_gdf['a']  ## Creates a shallow copy
my_gdf['a_copy'] = my_gdf['a].copy() ## Creates a deep copy

## assigning a column to a diffrent dataframe
my_gdf_2['a_copy'] = my_gdf['a] ## Creates a shallow copy too

```

Me and @ayushdg are thinking that we should stick to shallow copy as default behavior .  

We can mention this behavior in docs and may be throw a warning if a user tries to access the ```series.data``` object directly . Always creating deep copies may increase the gpu  memory usage too much.

**Comment by kkraus14** [comment]
This is stale and intended behavior, closing.
