### ISSUE TITLE
[BUG] Parquet reader returns extra pandas index column if index column requested explicitly

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#1960]
**Describe the bug**
If the caller specifies the name of the pandas index column in the list of columns to load then the Parquet reader will end up returning the pandas index column twice.  The first instance appears in the position it was requested in the caller's selection list.  The second instance appears as an extra column at the end.

**Steps/Code to reproduce bug**
Load a Parquet file that has a pandas index column and specify all of the column names to the Parquet loader.  The pandas index column will appear twice in the output.

**Expected behavior**
Columns will not appear redundantly in the Parquet load result.

**Comment by j-ieong** [comment]
Hrmm... I actually get an indexing error in this case, rather than a duplicate column.

@jlowe Can you post the `cudf.read_parquet` line with its arguments, along with all the column names in the data? Thanks!

**Comment by jlowe** [comment]
This is actually at the C++ layer. This is a non-Python use-case where the schema was auto-detected outside of cud’s and all of the columns were requested. I was surprised when more than all the columns came back.

**Comment by j-ieong** [comment]
Ah okay, that makes sense that I have different result using the Python interface. We'll see about deduplicating it.
