### ISSUE TITLE
[BUG] gdf_unary_math does not check output type

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#1962]
**Describe the bug**
`gdf_unary_math` blindly assumes that the output type and the input type are identical.  This is a requirement but there are no errors if you get it wrong, just possible memory corruption, and there is no documentation on it either.

This is especially confusing because the binary operations `gdf_binary_operation_*` have no such requirement.

**Steps/Code to reproduce bug**
Call `gdf_unary_math` with a different output type than the input type.  If the output type is smaller than the input type congratulations you have memory corruption.

**Expected behavior**
I get an error if it is not supported or it just works and the output is cast to the appropriate type.

Please note that even though the documentation for `gdf_unary_math` says
>  All operations only supported on floating point types

Many of the operations (like abs) work perfectly fine on other types.  The only reason I mention this is that if you are going to add in extra checks I don't really want to lose the ability to operate on non-floating point types.  I am fine with the limitation that the input and output must match.  I would just like it at a minimum to be documented and checked.

**Comment by devavret** [comment]
The reason you don't see this for binary ops is because they were transitioned to JIT compilation while the unary ops stayed precompiled. But the check for dtype matching can be easily added, no problem.

**Comment by devavret** [comment]
This is obsolete after the libcudf++ port as unary math operations (now simply unary operations; cast is now separate) don't take output dtype anymore.
