### ISSUE TITLE
[FEA]  Index initialization with null values

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#1968]
**Is your feature request related to a problem? Please describe.**
Currently, cuDF dataframes and/or series cannot be initialized with an `index=` list containing null values ( e.g. `s = cudf.Series([1, 2, 3], index=[4, 5, None])`).  

**Describe the solution you'd like**
The solution may just be to remove `assert values.null_count == 0` from the `GenericIndex` constructor [here](https://github.com/rapidsai/cudf/blob/f47a088eacd9b85131235a25f75c252eece3225a/python/cudf/dataframe/index.py#L463).  However, there may be good reason(s) for this assert statement that I am not aware of.  If so, please share them :)

**Describe alternatives you've considered**
Cudf dataframes can be created with `DataFrame.from_pandas` after initializing in pandas. Dataframes can also be initialize with the index as a column, and then `set_index` can be used to override the default index.  If these approaches are "appropriate," then removing the `assert values.null_count == 0` should also be fine.  Otherwise, the user should probably get a warning explaining the lack of support for null values in the index (in the short term, at least).

**Comment by kkraus14** [comment]
We could likely remove the assert, but we'd have to make sure that all of the functions that we are utilizing account for the null mask. You could try it and see if the unit tests pass?

**Comment by rjzamora** [comment]
Right - All existing unit tests pass, because none of them itialize dataframes/series with null index values.

**Comment by kkraus14** [comment]
My concern is functions like `.loc` and joining against indexes likely don't handle null values right now.

**Comment by rjzamora** [comment]
Just a note -  This issue should be addressed by [PR#1947](https://github.com/rapidsai/cudf/pull/1947)

**Comment by kkraus14** [comment]
Fixed by #1947
