### ISSUE TITLE
[BUG] Update C++ guide to avoid suggestion of using `std::tuple` for multiple return values

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1970]
**Describe the bug**
The [C++ transition guide ](https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/docs/TRANSITIONGUIDE.md#multiple-return-values) suggests using `std::tuple` to return multiple values from a libcudf API. However, Cython apparently doesn't support `std::tuple`.

**Expected behavior**
Update documentation to suggest using `std::pair` and note that functions will be limited to returning only two objects of different types (multiple objects of the same type can be returned via a `std::vector`.

**Comment by devavret** [comment]
I feel we should just enforce return structs. Makes for a much clearer intent, can hold anything, usage already demonstrated in CSV reader, not too difficult to write, won't clutter up `types.h` now that there's separate `hpp` headers for each functionality.

**Comment by devavret** [comment]
In fact, structs should even be used as input parameters to get around the C++ limitation of not being able to choose which optional parameters to pass. Kind of like kwargs of python land.

**Comment by jrhemstad** [comment]
> I feel we should just enforce return structs. Makes for a much clearer intent, can hold anything, usage already demonstrated in CSV reader, not too difficult to write, won't clutter up `types.h` now that there's separate `hpp` headers for each functionality.

I definitely don't want to require all APIs that wish to return multiple things to return a `struct`. Certainly there are times where it may be appropriate, and I do offer that as an option in the guide. However, a `struct` is far more heavy handed than what is usually necessary. Furthermore, it can encourage people to stuff way too much stuff inside of a `struct`.
