### ISSUE TITLE
dask_cudf.read_csv memory usage in AWS Sagemaker

### ISSUE THREAD

**Issue by ivenzor** [rapidsai/cudf#1972]
Are there any plans to work with AWS to enable RAPIDS to be available out of the box within Sagemaker?

It would be useful to be able to start a Sagemaker instance with GPUs and then use RAPIDS the same way you can already use Dask for example.

**Comment by quasiben** [comment]
I believe when you launch sagemaker it comes with Anaconda installed so you should be able to install the rapids packages through conda:

```
conda install -c defaults -c nvidia -c rapidsai -c pytorch -c numba -c conda-forge \
cudf=0.7 cuml=0.7 python=3.6 cudatoolkit=9.2
```

**Comment by nicolasburtey** [comment]
Just tried it. I can confirm this works.

**Comment by ivenzor** [comment]
Many thanks for your quick reply.  I will test this myself today.

**Comment by nicolasburtey** [comment]
Actually, that doesn't work. I have cudaErrorNoKernelImageForDevice error.
I guess this is because the driver is set at Driver Version: 418.40.04
Not sure if there is an easy way to update the driver on Sagemaker.

**Comment by ivenzor** [comment]
As far as I know the driver version requirement for Cuda 10 is 418.40.04, so it should work with the driver version you mentioned.

I did some testing and it's working for me after conda install.

_import cudf
df = cudf.DataFrame()
df['key'] = [0, 1, 2, 3, 4]
df['val'] = [float(i + 10) for i in range(5)]  # insert column
print(df)

   key   val
0    0  10.0
1    1  11.0
2    2  12.0
3    3  13.0
4    4  14.0_

I have some issues to read csv files from s3 and also the pandas encoding parameter is missing. But I will do more testing tomorrow to try to solve this issues.

**Comment by ivenzor** [comment]
Something is wrong with cuml:

terminate called after throwing an instance of 'MLCommon::Exception'
  what():  Exception occured! file=/conda/envs/gdf/conda-bld/libcuml_1557509586353/work/cuML/external/ml-prims/src/linalg/cutlass_wrappers.h line=380: FAIL: call='cudaPeekAtLastError()'. Reason:no kernel image is available for execution on the device

**Comment by ivenzor** [comment]
Perhaps this issue is due to Cuda 10.1 being used by Sagemaker instead Cuda 10.0?

**Comment by jrhemstad** [comment]
> Perhaps this issue is due to Cuda 10.1 being used by Sagemaker instead Cuda 10.0?

What GPU are you running on? 

```
 Reason:no kernel image is available for execution on the device
```

This error means you're trying to run on a GPU that doesn't support the architecture the binary was compiled for.

**Comment by ivenzor** [comment]
K80

**Comment by ivenzor** [comment]
I tested again with a V100 and it seems it's working now.

_import cuml
df_float = cudf.DataFrame()
df_float['0'] = [1.0, 2.0, 5.0]
df_float['1'] = [4.0, 2.0, 1.0]
df_float['2'] = [4.0, 2.0, 1.0]
dbscan_float = cuml.DBSCAN(eps=1.0, min_samples=1)
dbscan_float.fit(df_float)
print(dbscan_float.labels_)

0    0
1    1
2    2
dtype: int32_

**Comment by jrhemstad** [comment]
A K80 is a Kepler GPU. The oldest architecture RAPIDS supports is Pascal.

**Comment by ivenzor** [comment]
Altough the "no kernel image is available for execution on the device" error is solved, I still can't read a csv file on s3. It works when using pandas read_csv, but cudf.read_csv fails with the following exeption:
FileNotFoundError

Is there any special procedure to read csv files on s3?

**Comment by ivenzor** [comment]
I will try with dask_cudf.read_csv

**Comment by ivenzor** [comment]
Currently I can use dask_cudf.read_csv to read s3 files.

However if I specify the dtypes parameter no matter what type I specify for the columns I always got:
GDFError: b'GDF_UNSUPPORTED_DTYPE'

**Comment by ivenzor** [comment]
I'm currently using dask_cudf to read some gzip files using something similar to this:

data=dask_cudf.read_csv(list_of_files, compression='gzip',header=None, sep='~', names=[...], dtype=[...])

The gzip files are about 150MB each, and about 2.5GB each in non-compressed form. 
However, if I read more than 2 files I got a memory error while using a 16GB Tesla V100 GPU.

Maybe I'm missing something, but even in raw format, the files are way less than 16GB. And it's my understanding that inside the GPU they are in a columnar apache arrow format and in that case the data should be way smaller.

It's not clear to me why I'm facing a memory issue in this scenario.
