### ISSUE TITLE
[FEA] Add `nunique` aggregation to Groupby.agg

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#1974]
**Is your feature request related to a problem? Please describe.**
I wish to use cuDF to count unique visits partitioned over a particular grouping.

**Describe the solution you'd like**
```
import cudf as cu
df = cu.DataFrame(...)
df.groupby(['key']).agg({'val': 'nunique'})
```

**Describe alternatives you've considered**
```
import pandas as pd
df = pd.DataFrame(...)
df.groupby(['key']).agg({'val': 'nunique'})
```

**Additional context**
See [pandas.GroupBy.agg](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.agg.html#pandas.core.groupby.GroupBy.agg)

**Comment by randerzander** [comment]
@trstovall another workaround that doesn't involve going back to Pandas (minus the pretty printing) would be:
```
>>> import pandas as pd
d>>> pdf = pd.DataFrame()
>>> pdf['id'] = [0, 1, 2]
>>> pdf['val'] = [0, 1, 2]
>>> 
>>> import cudf
>>> gdf = cudf.from_pandas(df)

>>> pdf.groupby(['id']).agg({'val': 'nunique'})
    val
id     
0     1
1     1
2     1
>>> gdf.groupby(['id']).count().to_pandas()
    val
id     
0     1
1     1
2     1
```

This requires doing only a single aggregation at a time, as opposed to supporting single-pass multi-aggregations as you typically can with the `.agg` groupby approach.

**Comment by harrism** [comment]
Moving to 0.11

**Comment by beckernick** [comment]
This has popped up again, and the suggested workaround above is incomplete as it doesn't handle keys more than one of the same value. To work around this, you'd need to also drop duplicates on the combination of [key_col, val_col].

@JohnZed ran into this and worked around it like so: `df.drop_duplicates([group_key, counted_key]).groupby(group_key)[counted_key].count()`.

**Comment by randerzander** [comment]
This will depend on [sort based groupby](https://github.com/rapidsai/cudf/pull/3597)

**Comment by karthikeyann** [comment]
C++ part is completed. 
Cython and Python part is pending.

**Comment by devavret** [comment]
Closed by #4107

**Comment by harrism** [comment]
@kkraus14 assigning you to prioritize and assign Python exposure of this feature.

**Comment by kkraus14** [comment]
cc @shwina who's going to be working on the Cython / Python groupby refactoring
