### ISSUE TITLE
[BUG] Missing checks for (validly) empty include directories 

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#1975]
CMake does not like being given empty arguments for `include_directories` - even if other arguments are non-empty. It tells you (for example):
```
CMake Error at tests/CMakeLists.txt:52 (include_directories):
  include_directories given empty-string as include directory.
```
Now, in our `CMakeLists.txt`, it can happen that one (or more?) of the include directory variables is empty. Specifically if CUDA is installed under `/usr` (which it very well might be), we get an empty `CMAKE_CUDA_TOOLKIT_INCLUDE_DIRECTORIES`. 

So, before passing arguments to the `include_directories()` command, we need to be 100% certain they cannot be empty. The simple fix would be to just to check each such argument about which we're not sure and issue `include_directories()` with just that argument if it checks out. That should not be too much trouble (there are only 3 `include_directories()` commands in our `CMakeLists.txt` files overall).

**Comment by kkraus14** [comment]
Fixed by #1977
