### ISSUE TITLE
[FEA] Add a `cudf::transform` function

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1980]
**Is your feature request related to a problem? Please describe.**

It would be nice if libcudf provided a feature that allowed applying a Python user-defined `__device__` unary function against every element of a column. 

**Describe the solution you'd like**

The UDF unary `__device__` function would be JIT compiled w/ Numba in Python, and then it's PTX will be passed into libcudf to be applied to every element of a column. 

Proposed API:
```
namespace cudf{
/**---------------------------------------------------------------------------*
 * @brief Creates a new column by applying a unary function against every
 * element of an input column.
 *
 * Computes:
 * `out[i] = F(in[i])`
 *
 * @param input The input column to transform
 * @param ptx_unary_function The PTX of the unary function to apply
 * @return gdf_column The column resulting from applying the unary function to
 * every element of the input
 *---------------------------------------------------------------------------**/
gdf_column transform(gdf_column const& input,
                     std::string const& ptx_unary_function);
}
```

**Comment by devavret** [comment]
It'd be great if those PTX can be cached using JitCache. But that would mean JitCache would have to allow caching pre-compiled PTX.
