### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by efghnouz** [rapidsai/cudf#1988]
I followed rapids.ai/start.html tried cuDF and try import cudf but shows "illegal instruction (core dumped). I have GT 1030 on board.

**Comment by devavret** [comment]
Can you please paste every command you ran, including the terminal output. Can you also paste the output of `print_env.sh`. You can find it in the root of the repository.

**Comment by efghnouz** [comment]
I am frustrated with ubuntu. I am trying centos now but the installation is slow.

**Comment by efghnouz** [comment]
![page1](https://user-images.githubusercontent.com/51100800/59440178-866e6900-8dc4-11e9-9f0e-dff3452cb111.png)

**Comment by efghnouz** [comment]
![page2](https://user-images.githubusercontent.com/51100800/59440223-98500c00-8dc4-11e9-976d-1dd7a279935a.png)

**Comment by efghnouz** [comment]
![page3](https://user-images.githubusercontent.com/51100800/59440240-9e45ed00-8dc4-11e9-90ff-4673ad340c8c.png)

**Comment by efghnouz** [comment]
![page4](https://user-images.githubusercontent.com/51100800/59440248-a30aa100-8dc4-11e9-9bb1-d5176a62a7f0.png)

**Comment by efghnouz** [comment]
I just tried docker from RAPIDS Release Selector. I try to run DBSCAN_Demo_full.ipynb under tutorial. No luck.

The problem is at cuda or driver install. I guess.

But demo show cuda 10.1 driver 418.67 which is no difference.

**Comment by kkraus14** [comment]
@efghnouz Looks like you have CUDA 10.1 installed in your host machine which we don't support yet (reported by nvcc). 

The driver you have should be sufficient and with the docker container it should use either CUDA 10.0 or CUDA 9.2 which should work.

@harrism Do you know of any CUDA limitations with the GT 1030 that could potentially cause issues?

**Comment by harrism** [comment]
Not that I know of.

(BTW, in the future, please paste the text output of `print_env.sh`, not screenshots. :)

**Comment by efghnouz** [comment]
If you can not identify problem, shut up. Copy and paste may not be appropriate especially for nvidia-smi result.

I guess nvidia invest resource to rapids ai though it is open source project.
But the technical document really sucks. Nvidia/nvidia-docker instructions apparently does not work but no update.
Nvidia should hire somebody fix these things.

**Comment by muellren** [comment]
Going out on a limb here but I think the problem is not the GPU but rather your CPU. 
libcudf.so from the container image requires SSE4.1 and it appears from your second screenshot that your AMD Phenom does not support that.

**Comment by efghnouz** [comment]
Thank you.
