### ISSUE TITLE
[BUG] Rendering for Groupby.apply_grouped example broken

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#1989]
**Describe the bug**
https://rapidsai.github.io/projects/cudf/en/0.8.0/api.html#cudf.groupby.legacy_groupby.Groupby.apply_grouped

The example appears here as a string of unformatted text, as oppposed to the normal syntax highlighted in other examples.

**Comment by kkraus14** [comment]
Fixed by #1990
