### ISSUE TITLE
[BUG] `lhs` and `rhs` for `cudf::binary_operation` should be `const&`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#1997]
The `lhs` and `rhs` input arguments for `cudf::binary_operation` should be made `gdf_column const&` instead of `gdf_column*`. 

Looks like when the APIs were updated, this change slipped by.

See https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/docs/TRANSITIONGUIDE.md

**Comment by devavret** [comment]
This was fixed in the libcudf++ port.
