### ISSUE TITLE
[BUG] `cudf::scatter` does not correctly preserve bitmask of destination

### ISSUE THREAD

**Issue by RFinkelberg** [rapidsai/cudf#2007]
**Describe the bug**
When using the `cudf::scatter` python bindings to scatter an input column containing null values, the null mask is not properly transferred to the output column.

**Steps/Code to reproduce bug**
```python
In [1]: import cudf

In [2]: s = cudf.Series([1, 2, None, 4])
```
We want to change the first two values to `10` and `None`, giving us `[10, None, None, 4]`
```python
In [3]: in_col = cudf.Series([10, None])._column

In [4]: mask = cudf.Series([0, 1])._column.data.mem

In [5]: print(s)
0    1
1    2
2
3    4
dtype: int64

In [6]: cudf.bindings.copying.apply_scatter_column(in_col, mask, s._column)
Out[6]: <cudf.dataframe.numerical.NumericalColumn at 0x7fbdf7980160>

In [7]: print(s)
0    10
1
2
3
dtype: int64
```
Instead of only replacing the first two values, the entire remainder of the series is nulled. If we try this with a larger series we see the same behavior
```python
In [8]: s = cudf.Series([1, 2, None, 4, 5, 6, 7])

In [9]: cudf.bindings.copying.apply_scatter_column(in_col, mask, s._column)
Out[9]: <cudf.dataframe.numerical.NumericalColumn at 0x7fbdcd2396a0>

In [10]: print(s)
0    10
1
2
3
4
5
6
dtype: int64
```

**Environment details:**
Run on the latest `rapidsai/rapidsai-nightly` 18.04 development container, building dff2b20 from source
 

**Additional context**
This is relevant to #1979 which contributes a higher level wrapper for `Column` (around `apply_scatter_column`) and `Series.__setitem__` bindings using that wrapper. Currently a workaround is to [pass in a nullmask and manually set each value](https://github.com/rapidsai/cudf/blob/1439328c578e08efcd2f43cf2e95b02b1a55b917/python/cudf/dataframe/column.py#L504)

**Comment by jrhemstad** [comment]
Okay, so we've got:
```
source = [10, null]
scatter_mask = [0, 1]
destination = [1, 2, null, 4]
```

I'll see if I can reproduce in C++.

**Comment by RFinkelberg** [comment]
Thanks, let me know if you need any more information. For the record, everything works if source doesn't contain any nulls

**Comment by jrhemstad** [comment]
Confirmed that this happens purely in C++ as well. To reproduce: 
```
  cudf::test::column_wrapper<int64_t> source(
      {10, -1}, [](auto index) { return index != 1; });

  cudf::test::column_wrapper<int64_t> destination(
      {1, 2, -1, 4}, [](auto index) { return index != 2; });

  std::vector<int> scatter_map({0, 1});
  rmm::device_vector<int> d_scatter_map = scatter_map;

  cudf::table source_table({source.get()});
  cudf::table destination_table({destination.get()});

  cudf::scatter(&source_table, d_scatter_map.data().get(), &destination_table);

  EXPECT_EQ(cudaSuccess, cudaDeviceSynchronize());

  destination.print();
```

**Comment by jrhemstad** [comment]
Well, found the problem:

https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/copying/scatter.cu#L98

We're zeroing out the destination's bitmask. I'm sure I had a good reason to do that, there's even a comment telling me to make sure to do it... just can't remember why :D

**Comment by jrhemstad** [comment]
@hummingtree will fix this as he tackles https://github.com/rapidsai/cudf/issues/1677, but it won't be done until next release.
