### ISSUE TITLE
[BUG]   binaryops.cpp should call gdf_column_free to free temporary columns

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2013]
This TODO can be resolved by calling `gdf_column_free`, which would replace all of the lines in the following excerpt: 
https://github.com/rapidsai/cudf/blob/6e272375d474daad49d6b5507225ec54b89e1bc2/cpp/src/binaryop/binaryop.cpp#L260-L270

Assigning @devavret

**Comment by jrhemstad** [comment]
No longer relevant in libucdf++.
