### ISSUE TITLE
[FEA] Add support for clipping values in a Series

### ISSUE THREAD

**Issue by RFinkelberg** [rapidsai/cudf#2014]
**Is your feature request related to a problem? Please describe.**
It would be nice to have built in functionality to clip values in a dataframe to some min/max

**Describe the solution you'd like**
A pandas-like `Series.clip`, such that if
```python
s = cudf.Series([-1, 0, 2, 3, 4, 20, 30])
s = s.clip(min=0, max=10)
```
then `s` now contains `[0, 0, 2, 3, 4, 10, 10]`

**Describe alternatives you've considered**
A current workaround is to use `Series.applymap`, i.e 
```python
s = s.applymap(lambda i: max(i, 10))
```
to upper bound the values of the series at 10.

**Additional context**
[Link to pandas `DataFrame.clip`](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.clip.html)

**Comment by jrhemstad** [comment]
This could be a great candidate for @hummingtree working on https://github.com/rapidsai/cudf/issues/1980

**Comment by harrism** [comment]
I think the libcudf side of this should be called `cudf::clamp` to match (C++17) [`std::clamp`](https://en.cppreference.com/w/cpp/algorithm/clamp). e.g. 

`cudf::column clamp(cudf::column const& in, cudf::scalar const& lo, cudf::scalar const& hi);`

Python API can use `clip` to match pandas.

**Comment by rgsl888prabhu** [comment]
Needs to add cython and python support.

**Comment by rgsl888prabhu** [comment]
#5222 and #3594 have been merged.
