### ISSUE TITLE
[BUG] RuntimeError in cuio_common.cpp while reading a non ".csv" extension file

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2023]
I'm on the latest nightly of cudf. I'm getting below RuntimeError when I try reading a csv.

My code:
```python

import cudf
base_path = "temp.csv"

master_df = cudf.read_csv(base_path,sep='|')

```

Output:
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-10-a114fd3fb696> in <module>
      2 
      3 ftype = 'tlproject2'
----> 4 master_df = cudf.read_csv(base_path,sep='|')

/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/csv.py in read_csv(filepath_or_buffer, lineterminator, quotechar, quoting, doublequote, header, mangle_dupe_cols, usecols, sep, delimiter, delim_whitespace, skipinitialspace, names, dtype, skipfooter, skiprows, dayfirst, compression, thousands, decimal, true_values, false_values, nrows, byte_range, skip_blank_lines, comment, na_values, keep_default_na, na_filter, prefix, index_col)
     49         na_filter=na_filter,
     50         prefix=prefix,
---> 51         index_col=index_col
     52     )
     53 

cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_read_csv()

cudf/bindings/csv.pyx in cudf.bindings.csv.cpp_read_csv()

RuntimeError: cuDF failure at: /conda/envs/gdf/conda-bld/libcudf_1560801312446/work/cpp/src/io/cuio_common.cpp:90: Invalid compression argument
```

The same code ran correctly until I deleted my container and installed a new one along with all nightly packages.

For reference, the below is the discussion on this bug in a previous dask thread #281(https://github.com/rapidsai/dask-cudf/issues/281)
**Comment 1:**
> Hmm. Yeah, looking at the code, it looks like it will fail if the file extension isn't .csv -> was it the case here ?

Yep the extension of the file isn't a .csv
> (It should instead infer uncompressed imo) -> @galipremsagar : you can check if adding compression=None in the read_csv parameters resolves the issue.

Tried it, but no luck. Still the same exception.

_Originally posted by @galipremsagar in https://github.com/rapidsai/dask-cudf/issues/281#issuecomment-502900957_

**Comment 2:**

Yeah, it's a bug in the `inferCompressionType()`... well, actually maybe two bugs.

First is that `infer` should internally default to `none` if it doesn't match any known compression extensions per PANDAS. Second is that `None` should set the args field to `none`...

_Originally posted by @j-ieong in https://github.com/rapidsai/dask-cudf/issues/281#issuecomment-502903569_

**Comment by j-ieong** [comment]
Assign myself, as some IO team members are away.
