### ISSUE TITLE
[BUG] nvcategory_util sync_column_categories doesn't respect valid mask

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2024]
**Describe the bug**
sync_column_categories does not copy the valid mask from the input to the output columns. This means that correct usage requires manual copying of the valid mask and null_count, as in this lovely sequence: 

https://github.com/rapidsai/cudf/blob/1ebf10fb9fac6b1f9efe05a31c2d1f220d77cefa/cpp/src/join/joining.cu#L510-L520

**Expected behavior**
The entire columns should be synchronized, not just the data and category, to make this function easier and less error-prone to use.

**Comment by jrhemstad** [comment]
No longer relevant in libcudf++.
