### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by slfs007** [rapidsai/cudf#2025]
**Describe the bug**
 cudaErrorNoKernelImageForDevice no kernel image is available for execution on the device

**Steps/Code to reproduce bug**

`import numpy as np
import cudf

# Both import methods supported
from cuml import LinearRegression
from cuml.linear_model import LinearRegression

lr = LinearRegression(fit_intercept = True, normalize = False, algorithm = "eig")

X = cudf.DataFrame()
X['col1'] = np.array([1,1,2,2], dtype = np.float32)
X['col2'] = np.array([1,2,2,3], dtype = np.float32)

y = cudf.Series( np.array([6.0, 8.0, 9.0, 11.0], dtype = np.float32) )

reg = lr.fit(X,y)
print("Coefficients:")
print(reg.coef_)
print("intercept:")
print(reg.intercept_)

X_new = cudf.DataFrame()
X_new['col1'] = np.array([3,2], dtype = np.float32)
X_new['col2'] = np.array([5,5], dtype = np.float32)
preds = lr.predict(X_new)

print(preds)`
**Expected behavior**

**Environment details (please complete the following information):**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
    Docker
 - Method of cuDF install: [conda, Docker, or from source]
  docker pull rapidsai/rapidsai:cuda10.0-runtime-centos7
docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
rapidsai/rapidsai:cuda10.0-runtime-centos7
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant 

[env_log.txt](https://github.com/rapidsai/cudf/files/3300776/env_log.txt)

**Additional context**

**Comment by slfs007** [comment]
> **Describe the bug**
> cudaErrorNoKernelImageForDevice no kernel image is available for execution on the device
> 
> **Steps/Code to reproduce bug**
> 
> `import numpy as np
> import cudf
> 
> # Both import methods supported
> from cuml import LinearRegression
> from cuml.linear_model import LinearRegression
> 
> lr = LinearRegression(fit_intercept = True, normalize = False, algorithm = "eig")
> 
> X = cudf.DataFrame()
> X['col1'] = np.array([1,1,2,2], dtype = np.float32)
> X['col2'] = np.array([1,2,2,3], dtype = np.float32)
> 
> y = cudf.Series( np.array([6.0, 8.0, 9.0, 11.0], dtype = np.float32) )
> 
> reg = lr.fit(X,y)
> print("Coefficients:")
> print(reg.coef_)
> print("intercept:")
> print(reg.intercept_)
> 
> X_new = cudf.DataFrame()
> X_new['col1'] = np.array([3,2], dtype = np.float32)
> X_new['col2'] = np.array([5,5], dtype = np.float32)
> preds = lr.predict(X_new)
> 
> print(preds)`
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Environment details (please complete the following information):**
> 
> * Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
>   Docker
> * Method of cuDF install: [conda, Docker, or from source]
>   docker pull rapidsai/rapidsai:cuda10.0-runtime-centos7
>   docker run --runtime=nvidia --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 
>   rapidsai/rapidsai:cuda10.0-runtime-centos7
> * Please run and attach the output of the `cudf/print_env.sh` script to gather relevant
> 
> [env_log.txt](https://github.com/rapidsai/cudf/files/3300776/env_log.txt)
> 
> **Additional context**
> Add any other context about the problem here.

detail err log:
[details_log.txt](https://github.com/rapidsai/cudf/files/3300791/details_log.txt)

**Comment by jrhemstad** [comment]
You're running on a Tesla K40, which is the Kepler line of architecture. The oldest GPU architecture we support is Pascal.

**Comment by ja3067** [comment]
Is RAPIDS incompatible with earlier generations, or do the prebuilt versions simply not support it? Can I build it from scratch for a Maxwell or Kepler GPU? Requiring a Pascal GPU seems pretty restrictive when it rules out some of the most popular GPUs, like the 970 and 980 series, as well as "Deep Learning Accelerators" like the M40 or K40.
