### ISSUE TITLE
[BUG] performance overhead of converting NVStrings to NVCategory before passing to libcudf

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2029]
**Describe the bug**
I currently have operations such as string replace / assign / concat in my dask-cudf code and looking at the task-graphs I find that there is significant amount of time being spent while allocating mask & `cpp_apply_boolean_mask`. This attributes to roughly 4 mins of my entire run. The entire run takes about 9 minutes. 

**Steps/Code to reproduce bug**
Here are the snaps of the task-graphs:
![image](https://user-images.githubusercontent.com/11664259/59704604-26abff80-91c2-11e9-8298-072d825e4dd0.png)

![image](https://user-images.githubusercontent.com/11664259/59708858-3c71f280-91cb-11e9-9ce9-fe7a0cbd624f.png)

![image](https://user-images.githubusercontent.com/11664259/59704609-2ad81d00-91c2-11e9-9438-c55bb678f381.png)

Is there any way to reduce the time being spent in applying boolean masks?

**Environment details (please complete the following information):**
 - Environment location:  Docker
 - Method of cuDF install:  Conda-nightly
 -  `cudf/print_env.sh`: [log_env.txt](https://github.com/rapidsai/cudf/files/3302652/log_env.txt)

 

**Additional context**
I'm running this on a multi-node setup. Dataset size is 1Billion records. Entire run takes about 9minutes. This is for an internal workflow which I can share/walk-through if required. Please feel free to ping me on slack for that.

cc: @beckernick @randerzander

**Comment by galipremsagar** [comment]
Updating with `nvcategory.from_strings` call which takes considerable amount of time::
![image](https://user-images.githubusercontent.com/11664259/59708975-6f1beb00-91cb-11e9-8d44-a60b3a35a5ff.png)

**Comment by kkraus14** [comment]
@galipremsagar can you share the profile html here for us to investigate? Is the code sensitive where it can't be shared publicly?

**Comment by galipremsagar** [comment]
@kkraus14, Yes, code and data are sensitive and can't be shared publicly. Shared the profile html with you over slack because of a possible doubt of call stack too getting exported as part of a json in the html file.

**Comment by harrism** [comment]
This should be fixed by libcudf++ port. Please file new performance issues if you find them.
