### ISSUE TITLE
[FEA] Add memory buffer input support to ORC/Parquet readers

### ISSUE THREAD

**Issue by mjsamoht** [rapidsai/cudf#2043]
ORC/Parquet readers currently only accept file names as input.  We need support for memory buffer input where the bytes of a complete ORC/Parquet file are passed in as buffer. 

Note:  There is no need to support processing of byte ranges.

**Comment by OlivierNV** [comment]
Looks like the cpp end already supports it, but it needs to be added to the python/cython layer.
