### ISSUE TITLE
[FEA] Add timedelta dtype

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2052]
I want to compute elapsed time between two datetime columns. In Pandas I would do:
```
df['delta'] = df['dt2'] - df['dt1']
``` 
and the result would be a timedelta dtype.

In cudf you can't subtract one datetime column from another due to lack of binary operator support for datetimes.

Workaround, but leaves the user to write the basic calculations for converting delta units to seconds, minutes, hours, etc:
```
df['delta'] = df['dt2'].astype('int') - df['dt1'].astype('int')
```

The workaround for _adding_ a time to a cudf DateTime column is similar.

**Comment by karthikeyann** [comment]
Datetime difference yields timedelta.
```python
import cudf
import pandas as pd
pdf=pd.DataFrame({'dt1': pd.Series(pd.date_range('2000', freq='s', periods=6)),'dt2': pd.Series(pd.date_range('2000', freq='D', periods=6)) })
df=cudf.from_pandas(pdf)
df['delta'] = df['dt2'] - df['dt1']
df['delta'].dtype
```

**Comment by karthikeyann** [comment]
completed with all PRs in #5272
