### ISSUE TITLE
[FEA] cudf.read_csv and other readers should support reading from a URL

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2062]
With pandas, I can read a CSV (or other filetypes) directly from a URL as opposed to a file on disk.

```
import pandas as pd

url="https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
c=pd.read_csv(url)
```

It would be nice to be able to do the same thing in cudf instead of having to first download the file or read it into a StringIO object.

**Comment by ivenzor** [comment]
Currently I can use dask_cudf.read_csv to read 'remote' files, but it seems there are some errors while handling string data from dask_cudf into the cudf data frame.

**Comment by randerzander** [comment]
@ivenzor can you open another issue, and include sample data that reproduces the issue?

**Comment by ivenzor** [comment]
Sorry for the delay, the GDFError: b'GDF_UNSUPPORTED_DTYPE' error was due a mistake if mine.

However I got a memory while reading more than 3 files and I created another issue:
#1972 

Best regards.
