### ISSUE TITLE
[BUG] rapidsai-nightly/label/cuda10.0  cudf.fillna(0) fail

### ISSUE THREAD

**Issue by Polarbeargo** [rapidsai/cudf#2064]
**Describe the bug**
I use cudf 0.8 rapidsai-nightly/label/cuda10.0 as i implement
`df.fillna(0)` encouter 
`/databricks/python/lib/python3.6/site-packages/numba/cuda/compiler.py:234: UserWarning: Could not autotune, using default tpb of 128
  warnings.warn('Could not autotune, using default tpb of 128')
TypeError: fill_value must be a string or a string series`

**Steps/Code to reproduce bug**
![88](https://user-images.githubusercontent.com/8589224/59894109-e5aa2a00-9411-11e9-98c0-156b8f5a7811.png)
**Expected behavior**
Implement `df.fillna(0)` without error.
**Environment details (please complete the following information):**

![2](https://user-images.githubusercontent.com/8589224/59894086-d925d180-9411-11e9-8bf9-fe042970eed4.png)

**Comment by kkraus14** [comment]
It looks like you have some string dtype columns which can't just be filled with `0` naively. Pandas uses Python objects under the hood whereas we use an actual UTF8 string type.

**Comment by kkraus14** [comment]
@randerzander @beckernick any views on how this should best be handled from your perspective? Would you expect it to fill with `"0"` or throw an error as it currently does?

**Comment by randerzander** [comment]
IMO it's best to keep it an error as is.

This feels like one of those places where automatic type conversion (0 -> "0") is highly likely to induce confusion downstream.

Consider the scenario where CSV dtype inference reads a string when the user expected numerics. Prior to running some algorithm, they do:
```for col in df.columns: df[col] = df[col].fillna(0)```

At best, simple numeric operators surface the problem early.

At worst, a numba kernel or call to `fit` gives an inscrutable error, and significant time gets wasted trying to figure out what's going wrong.

**Comment by Polarbeargo** [comment]
If I write `df.fillna("0")`  will bumped into following error message:
![33](https://user-images.githubusercontent.com/8589224/59986823-fbfef280-966a-11e9-9f5a-35a4b03b43c4.png)

**Comment by kkraus14** [comment]
@polarbeargo trying to run fillna on the full dataframe object is going to be problematic for you since you have mixed dtypes. Here you're trying to fill numeric columns with a string which isn't allowed and we don't want to automatically typecast all of your numeric columns to strings.

**Comment by Polarbeargo** [comment]
Thank you @kkraus14 very appreciate your guidance:)!
