### ISSUE TITLE
[BUG] unary operations don't seem to handle empty series

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2077]
**Describe the bug**
There is an issue when we perform unary operations like `abs`, `min`, `max`... on an empty series.

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.DataFrame({'x':[]}
print(df.x.abs())

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-188-257386167fa5> in <module>
----> 1 df.x.abs()

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/series.py in abs(self)
   1713         Returns a new Series.
   1714         """
-> 1715         return self._unaryop('abs')
   1716 
   1717     def __abs__(self):

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/series.py in _unaryop(self, fn)
    454         operand.
    455         """
--> 456         outcol = self._column.unary_operator(fn)
    457         return self._copy_construct(data=outcol)
    458 

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/numerical.py in unary_operator(self, unaryop)
     79     def unary_operator(self, unaryop):
     80         return numeric_column_unaryop(self, op=unaryop,
---> 81                                       out_dtype=self.dtype)
     82 
     83     def unary_logic_op(self, unaryop):

/conda/envs/rapids/lib/python3.7/site-packages/cudf/dataframe/numerical.py in numeric_column_unaryop(operand, op, out_dtype)
    406 def numeric_column_unaryop(operand, op, out_dtype):
    407     out = columnops.column_empty_like_same_mask(operand, dtype=out_dtype)
--> 408     cpp_unaryops.apply_math_op(operand, out, op)
    409     return out.view(NumericalColumn, dtype=out_dtype)
    410 

cudf/bindings/unaryops.pyx in cudf.bindings.unaryops.apply_math_op()

RuntimeError: cuDF failure at: /conda/envs/gdf/conda-bld/libcudf_1561082418487/work/cpp/src/unary/unary_ops.cuh:92: Pointer to data in input column is null
```
**Expected behavior**
We should be returning an empty series like pandas does:
```python
import pandas as pd
df = pd.DataFrame({'x':[]})
print(df.x.abs())
Series([], Name: x, dtype: float64)
```

**Environment details (please complete the following information):**
 - Environment location: Docker
 - Method of cuDF install: conda-nightly
 

**Additional context**
Found this issue when there is a dask partition with empty dataframe in it

Potential resolutions to this issue would be:
1. To handle it on python side in `numeric_column_unaryop` function guarding with a size check. 
2. Or handle it on the cpp side when the input is empty, but we seem to have an explicit null pointer check and raising exception in this line: https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/unary/unary_ops.cuh#L91 , if that's the case should the ideal approach be to fix it on python side?

cc: @kkraus14 @beckernick @randerzander

**Comment by kkraus14** [comment]
Should handle it in libcudf.

**Comment by harrism** [comment]
@devavret can you take this? We should probably update all the unary ops public APIs to the new C++ standard (create the result internally and return it), and then `return cudf::empty_like(input)` when input is zero-length or has a null data pointer.
