### ISSUE TITLE
[FEA] Use an inplace replace_nulls in nvcategory_gather

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#2080]
The function `nvcategory_gather` in https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/string/nvcategory_util.cpp uses an out-of-place `replace_nulls`, which could be done inplace. This will make `gather` faster on columns of dtype `GDF_STRING_GATEGORY`.

So really this is two feature requests:

1. Add an inplace version of `replace_nulls`
2. Update `nvcategory_gather` to use it

Perhaps could be part of #1677 ?

**Comment by kkraus14** [comment]
NVCategory is deprecated as of 0.14 so closing this.
