### ISSUE TITLE
[FEA] Add GDF_STRING_CATEGORY support to cudf::fill

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2085]
**Is your feature request related to a problem? Please describe.**
cudf::fill() currently does not support filling a string literal value because `gdf_scalar` cannot hold string data.

**Describe the solution you'd like**
Add support for filling a literal string value.

**Describe alternatives you've considered**
This could be done by adding dtype_extra_info to gdf_scalar #1449 and then using a GDF_STRING_CATEGORY gdf_scalar as the input. It might be a bit inefficient if it requires building a string_category of a single string first...

**Comment by jrhemstad** [comment]
No longer relevant in libcudf++.
