### ISSUE TITLE
[FEA] Add string support to gdf_scalar

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2087]
**Is your feature request related to a problem? Please describe.**
To enable operations such as comparing a string column to a single string literal (#1808 ) and assigning a string literal to a range of elements in a column (#2085), `gdf_scalar` should be augmented to support storing a single string value. 

**Describe the solution you'd like**
We need to discuss the proper solution. As @devavret points out (https://github.com/rapidsai/cudf/issues/1808#issuecomment-500871234), 

> Do we also add `dtype_info` to `gdf_scalar`? And do we store an `NVCategory` object in it? Or do we store just a char* in the data union or as a separate member of `gdf_scalar`?

Adding `dtype_extra_info` to `gdf_scalar` is #1449.

**Comment by karthikeyann** [comment]
depends on whichever is easier (and faster),
adding `char*` to exisiting column's `NVCategory`  or `NVCategory` to `NVCategory`?
