### ISSUE TITLE
[DOC] typo in to_csv

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2099]
## Report incorrect documentation

**Location of incorrect documentation**
https://rapidsai.github.io/projects/cudf/en/0.8.0/api.html#cudf.dataframe.DataFrame.to_csv

**Describe the problems or issues found in the documentation**
There is a typo in last line of sample code:
`cudf.to_csv(filename)`

**Steps taken to verify documentation is incorrect**
Verified with source.

**Suggested fix for documentation**
It has to be:
`df.to_csv(filename)`

**Comment by kkraus14** [comment]
Fixed by #2113
