### ISSUE TITLE
[BUG] Groupby has a large memory leak

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2101]
**Describe the bug**
The `sparse_output_values` table is never freed in groupby, causing a large memory leak.

https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/groupby/hash/groupby.cu#L381

**Comment by ayushdg** [comment]
@jrhemstad Good to close?

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/cudf/pull/2102
