### ISSUE TITLE
[QST] Can RAPIDS run on Power 8 + P100?

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#2121]
**What is your question?**
Hi,

We are presenting RAPIDS right now to some colleagues, and we are wondering if RAPIDS can be run on Power 8 + P100 GPUs?

Thanks!

Regards,
Miguel

**Comment by kkraus14** [comment]
@miguelangel yes it can, you can even conda install power builds for RAPIDS libraries via the IBM PowerAI conda channel: https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/.

@pradghos Anything that you can add here? Thanks!

**Comment by miguelangel** [comment]
Thank you @kkraus14!

I appreciate your quick response!

Closing this issue now.

**Comment by pradghos** [comment]
> 
> 
> @miguelangel yes it can, you can even conda install power builds for RAPIDS libraries via the IBM PowerAI conda channel: https://public.dhe.ibm.com/ibmdl/export/pub/software/server/ibm-ai/conda/.
> 
> @pradghos Anything that you can add here? Thanks!

Thanks @kkraus14 for quick response ! just to add here - all the RAPIDS packages in `PowerAI conda channel`  has been built and dependent on `cudatoolkit 10.1`.
