### ISSUE TITLE
[BUG] Boolean column being treated as String column when reading CSV

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2122]
**Describe the bug**
When we read a csv, we seem to be treating a column with Boolean records of dtype string(`object`) which is why Boolean comparisons seem to be failing. 

**Steps/Code to reproduce bug**
Sample csv in zip: [sample.zip](https://github.com/rapidsai/cudf/files/3330460/sample.zip)

```python
import cudf
df = cudf.read_csv('sample.csv')
print(df.x)
print(df[df.x==True])
0     True
1    False
Name: x, dtype: object
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-c87eeab785d7> in <module>
      2 df = cudf.read_csv('sample.csv')
      3 print(df.x)
----> 4 print(df[df.x==True])

/conda/envs/cudf/lib/python3.7/site-packages/cudf/dataframe/series.py in __eq__(self, other)
    811 
    812     def __eq__(self, other):
--> 813         return self._unordered_compare(other, 'eq')
    814 
    815     def equals(self, other):

/conda/envs/cudf/lib/python3.7/site-packages/cudf/dataframe/series.py in _unordered_compare(self, other, cmpops)
    781     def _unordered_compare(self, other, cmpops):
    782         nvtx_range_push("CUDF_UNORDERED_COMP", "orange")
--> 783         other = self._normalize_binop_value(other)
    784         outcol = self._column.unordered_compare(cmpops, other)
    785         result = self._copy_construct(data=outcol)

/conda/envs/cudf/lib/python3.7/site-packages/cudf/dataframe/series.py in _normalize_binop_value(self, other)
    777             return Series(other)._column
    778         else:
--> 779             return self._column.normalize_binop_value(other)
    780 
    781     def _unordered_compare(self, other, cmpops):

/conda/envs/cudf/lib/python3.7/site-packages/cudf/dataframe/string.py in normalize_binop_value(self, other)
    703             return self.replace(data=col.data)
    704         else:
--> 705             raise TypeError('cannot broadcast {}'.format(type(other)))
    706 
    707     def default_na_value(self):

TypeError: cannot broadcast <class 'bool'>
```

But then we seem to be detecting the types of y column correctly:
```python
print(df.y)
0    1
1    2
Name: y, dtype: int64
```
Pandas:

```python
import pandas as pd
df = pd.read_csv('sample.csv')
print(df.x)
print("************")
print(df[df.x==True])
print("************")
print(df.y)
0     True
1    False
Name: x, dtype: bool
************
   Unnamed: 0     x  y
0           0  True  1
************
0    1
1    2
Name: y, dtype: int64
```

**Expected behavior**
As a workaround we just need to typecast the column to bool and things will work fine. But when we read from csv, we should be treating the column with boolean values as bool type column, verified this issue doesn't exist when I convert a pandas dataframe into cudf dataframe (`cudf.from_pandas(pandas_df)`)

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source(branch-0.8 & branch-0.9)

**Environment details**
print_env.sh output : [env.txt](https://github.com/rapidsai/cudf/files/3330513/env.txt)

**Comment by mjsamoht** [comment]
The problem is in the function `dataTypeDetection()`.  We call `serializedTrieContains(opts.trueValuesTrie, raw_csv + start, field_len)` only when `if(countNumber==int_req_number_cnt)`.

If the value is `True` or `False` there are no digits and `countNumber=0` so the `if` statement will always evaluate to false.

**Comment by mjsamoht** [comment]
Fix should be simple.  I believe all we have to do is move the check for Boolean values before the check for numbers:

```
const size_t field_len = tempPos - start + 1;
if (strLen==0) {  ...
}
else if (serializedTrieContains(opts.trueValuesTrie, raw_csv + start, field_len) ||
           serializedTrieContains(opts.falseValuesTrie, raw_csv + start, field_len)) {
   atomicAdd(& d_columnData[actual_col].countBool, 1);
}
else if (countNumber==int_req_number_cnt) {  ...
}
```...

**Comment by j-ieong** [comment]
> Fix should be simple. I believe all we have to do is move the check for Boolean values before the check for numbers:
> 
> ```
> const size_t field_len = tempPos - start + 1;
> if (strLen==0) {  ...
> }
> else if (serializedTrieContains(opts.trueValuesTrie, raw_csv + start, field_len) ||
>            serializedTrieContains(opts.falseValuesTrie, raw_csv + start, field_len)) {
>    atomicAdd(& d_columnData[actual_col].countBool, 1);
> }
> else if (countNumber==int_req_number_cnt) {  ...
> }
> ```...
> ```

Yup. It should be moved to the same place where we check for NA values.
