### ISSUE TITLE
[QST] How do you handle out of memory error in cudf or dask-cudf

### ISSUE THREAD

**Issue by vnkesarwani** [rapidsai/cudf#2133]
**What is your question?**
I was trying to load data larger than GPU memory. and i am getting following error.

Function:  load_data
args:      (125000000)
kwargs:    {}
Exception: CudaAPIError(1, 'Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE')

ERROR: RMM call in line 68of file /conda/envs/gdf/conda-bld/libcudf_1558047478243/work/cpp/src/hash/managed_allocator.cuh failed with result RMM_ERROR_OUT_OF_MEMORY (4)  Attempted to allocate: 4000000000 bytes.
distributed.worker - WARNING -  Compute Failed
Function:  groupby
args:      (<cudf.DataFrame ncols=2 nrows=125000000 >)
kwargs:    {}
Exception: MemoryError('std::bad_alloc')

ERROR: RMM call in line 68of file /conda/envs/gdf/conda-bld/libcudf_1558047478243/work/cpp/src/hash/managed_allocator.cuh failed with result RMM_ERROR_OUT_OF_MEMORY (4)  Attempted to allocate: 4000000000 bytes.
distributed.worker - WARNING -  Compute Failed
Function:  groupby

----------------------------------------------------------------------------

Is it possible to avoid this error by any intelligence or any tool/framework?

i.e. Intelligently load data in chunks/spill over to CPU RAM/Disk; reduce it in GPU or CPU?? as Spark does.

I tried it with dask-cudf and it doesn't seem to be equipped yet to handle this scenario.

Any suggestions.

**Comment by kkraus14** [comment]
@vnkesarwani in using dask-cudf inputs are typically chunked into more consumable pieces of work. These pieces can they be shuffled into and out of GPU memory as necessary to try to prevent OOM issues. This is still ongoing work and is definitely very rough around the edges currently.

In your above example it looks like you tried to run a very large groupby and by default groupby will try to condense the result down to a single partition. There are parameters for `split_out` and `split_every` to help control this behavior.

**Comment by vnkesarwani** [comment]
> @vnkesarwani in using dask-cudf inputs are typically chunked into more consumable pieces of work. These pieces can they be shuffled into and out of GPU memory as necessary to try to prevent OOM issues. This is still ongoing work and is definitely very rough around the edges currently.
> 
> In your above example it looks like you tried to run a very large groupby and by default groupby will try to condense the result down to a single partition. There are parameters for `split_out` and `split_every` to help control this behavior.

dasd

**Comment by kkraus14** [comment]
@vnkesarwani We are essentially following the existing memory management model of Dask but adding an additional tier of GPU memory above host memory. You can read about that here: https://distributed.dask.org/en/latest/worker.html#memory-management.
