### ISSUE TITLE
[BUG] describe not in-line with pandas describe behavior

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2134]
**Describe the bug**
1. We don't seem to be setting index of the data frame being returned in `describe` api call.
2. Irrespective of whether a Series or Dataframe is calling `describe` we seem to construct a DataFrame with a dedicated column `**stats**` and then populate results. 
3. If we fix 1, maybe we can drop `stats` column?

**Steps/Code to reproduce bug**
cudf:
```python
import cudf
df = cudf.Series([1,2,4])
print(df.describe().index)
RangeIndex(start=0, stop=8)
print(df.describe())
   stats    values
0  count       3.0
1   mean  2.333333
2    std  1.527525
3    min       1.0
4    25%       1.5
5    50%       2.0
6    75%       3.0
7    max       4.0
```

pandas:
```python
import pandas as pd
df = pd.Series([1,2,4])
print(df.describe().index)
Index(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'], dtype='object')

print(df.describe())
count    3.000000
mean     2.333333
std      1.527525
min      1.000000
25%      1.500000
50%      2.000000
75%      3.000000
max      4.000000
dtype: float64
```

**Expected behavior**
1. We will need to set index as similar to that of pandas.
2. Return types of a Series.describe should be Series, DataFrame.describe should be DataFrame.
3. If we fix the index issue, looks like we might not need `stats` column anymore, lets remove it?

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source

**Environment details**
`cudf/print_env.sh` : 
[env.txt](https://github.com/rapidsai/cudf/files/3335567/env.txt)

**Comment by karthikeyann** [comment]
Yes. both Series and DataFrame describe() returns DataFrame with a column 'stats'
I have the fix as well. Here is complete bug test code.
```
import cudf
s1 = cudf.Series([1,2,4])
s2 = cudf.Series([5,6,7])
df = cudf.DataFrame({'s1': s1, 's2': s2})
print(s1.describe())
print(df.describe())
print(s1.describe().index)
type(s1.describe())
type(df.describe())
````
