### ISSUE TITLE
[BUG] Selecting columns as attributes of rolling objects.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2136]
As of now, we cannot select columns after rolling window operations. An example of this is below:

```
import cudf
df = cudf.DataFrame({'x': np.arange(10)})
print(df.rolling(2).x.mean())
```

**Comment by chinmaychandak** [comment]
Still getting an issue when I do rolling over time and then select a column. Something missing?

```
import cudf
import pandas as pd
import numpy as np
index = pd.DatetimeIndex(start='2000-01-01', end='2000-01-03', freq='1h')
df = cudf.DataFrame({'x': np.arange(len(index))}, index=index)
print(df.rolling('2h').x.mean())
```

**Comment by kkraus14** [comment]
@chinmaychandak This is a different issue with regards to handling timedeltas, could you open a new issue?

**Comment by chinmaychandak** [comment]
Sure, will do. Thanks @kkraus14
