### ISSUE TITLE
[BUG] loc fails with DatetimeIndex

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2138]
loc throws "ValueError: value not found" when the query DatetimeIndex value is not present in the dataframe. 

An example of this is shown below:
```
import cudf
import pandas as pd
import numpy as np

index = pd.date_range(start='2017-01-01', periods=4, freq='0h15min')
gdf = cudf.DataFrame({'x': np.arange(len(index))}, index=index)
gdf.loc[pd.Timestamp(2017,1,1,0,20):]
```

With pandas, the output is:
![Screen Shot 2019-06-27 at 10 40 05 AM](https://user-images.githubusercontent.com/47901991/60287976-0ff36000-98c8-11e9-972c-60436495777e.png)

This is a major blocker in performing rolling window operations over time.

**Comment by ayushdg** [comment]
**Additional info**: It seems like with datetime indices pandas handles loc slices even if that exact timestamp mentioned in the slice does not exist. 
The same example above with `gdf.loc[pd.Timestamp(2017,1,1,0,15):]` would work as cudf can identify this value in the index and give all elements after it.

**Comment by shwina** [comment]
Thanks @chinmaychandak for reporting. Could you please provide a snippet showing how you would like to use this with rolling windows?

**Comment by chinmaychandak** [comment]
@shwina, the rolling window operations I'm targeting are a little complex. They involve streaming dataframes. All in all, it throws the error because of the issue posted above. Here's the example snippet, though:

```
import cudf
import pandas as pd
import numpy as np
from streamz import Stream
from streamz.dataframe import DataFrame

index = pd.date_range(start='2017-01-01', periods=10, freq='0h15min')
df = cudf.DataFrame({'x': np.arange(len(index))}, index=index)

stream=Stream()
sdf = DataFrame(stream=stream, example=df)
L = sdf.x.rolling(pd.Timedelta("20 minutes")).mean().stream.gather().sink_to_list()
assert len(L) == 0

for i in range(0, len(df), 3):
    sdf.emit(df.iloc[i:i+3])
    
print(cudf.concat(L))
```

**Comment by shwina** [comment]
This should have been fixed by https://github.com/rapidsai/cudf/pull/2162 

Could you please confirm @chinmaychandak so we can close out this issue?

**Comment by chinmaychandak** [comment]
Yes, fixed! Thanks @shwina

**Comment by shwina** [comment]
Thanks to @rjzamora!

Closing this
