### ISSUE TITLE
[QST] What if I need Python 3 to integrate with PySyft

### ISSUE THREAD

**Issue by Polarbeargo** [rapidsai/cudf#2153]
**What is your question?**
Dear all,
I currently use cudf 0.8 rapidsai-nightly/label/cuda10.0. If I need python 3 to integrate with PySyft which version of cudf should I use? I truly appreciate your guidance and help.
![33](https://user-images.githubusercontent.com/8589224/60419373-b4063f80-9c17-11e9-82d4-ba3f3f55f3ca.png)

## Environment: Azure Databricks
![cluster conffig](https://user-images.githubusercontent.com/8589224/60419641-5cb49f00-9c18-11e9-842b-5b04364dd63a.png)
![cluster config](https://user-images.githubusercontent.com/8589224/60419645-5e7e6280-9c18-11e9-85d3-00b106aeb302.png)

**Comment by galipremsagar** [comment]
Looks like you are on an older version of 0.8 nightly. 0.8 stable is released, it comes with python 3.7 and you can install by copy pasting following command:
![image](https://user-images.githubusercontent.com/11664259/60457889-cb86fd80-9c02-11e9-9466-d31b4ededf43.png)

`conda install -c nvidia -c rapidsai -c numba -c conda-forge -c pytorch -c defaults \
    cudf=0.8 cuml=0.8 cugraph=0.8 python=3.7 cudatoolkit=10.0`

The above command can be found at this page: https://rapids.ai/start.html

**Comment by Polarbeargo** [comment]
Thank you for your guidance @galipremsagar! I'll work on it:)!

**Comment by kkraus14** [comment]
@Polarbeargo I'm going to close this as it's been answered, but feel free to open up another issue if you hit another problem.
