### ISSUE TITLE
[FEA] Autogenerate conda existence tests for libcudf headers

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2167]
**Is your feature request related to a problem? Please describe.**

Currently the libcudf conda `meta.yml` runs tests for all the libcudf public headers to make sure they are installed correctly for packaging.

When adding a new header, it's easy to forget to add it to the conda recipe. 

**Describe the solution you'd like**
Autogenerate the list of tests based on the contents of `cpp/include`. e.g. if there's a header `cpp/include/cudf/foo/bar.hpp`, then `meta.yml` should have a test line for it:

```
- test -f $PREFIX/include/cudf/foo/bar.hpp
```

**Comment by harrism** [comment]
libcudf headers are changing a lot, and it's hard to keep on top of this manually. @kkraus14 @mike-wendt it would be nice to automate it.

**Comment by karthikeyann** [comment]
> Currently the libcudf conda `meta.yml` runs tests for all the libcudf public headers to make sure they are installed correctly for packaging.

what qualifies a header (.h, .hpp) to be _a public header_?

**Comment by harrism** [comment]
> what qualifies a header (.h, .hpp) to be a public header?

It's in cpp/include
