### ISSUE TITLE
[FEA] Remove old C++ groupby implementation 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2174]
**Is your feature request related to a problem? Please describe.**

After the merging of https://github.com/rapidsai/cudf/pull/1478 and https://github.com/rapidsai/cudf/pull/2018 the previous libcudf groupby implementation is defunct.

**Describe the solution you'd like**
Remove the old libcudf groupby implementation.

**Comment by beckernick** [comment]
@kkraus14 would removing this implementation kill the legacy_groupby API?
