### ISSUE TITLE
[FEA] Implement pandas idxmax and idxmin method

### ISSUE THREAD

**Issue by asmeurer** [rapidsai/cudf#2188]
**Is your feature request related to a problem? Please describe.**

The `idxmax` function from pandas doesn't appear to be implemented on cudf. For my code, I particularly need this implemented on groupby objects, but it exists on pandas dataframe and series objects as well.

**Comment by kkraus14** [comment]
For reference: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.idxmax.html

**Comment by beckernick** [comment]
For additional reference on the groupby.idxmax/min:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.idxmax.html

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.idxmin.html

**Comment by hopeful-coder** [comment]
What was your workaround for this?

**Comment by kkraus14** [comment]
> What was your workaround for this?

I don't believe we have a current workaround for this. Looks like `ARGMIN` / `ARGMAX` landed on the libcudf side where we should explore plumbing this into the Python layer.

**Comment by asmeurer** [comment]
I did something like

```py
from numba import cuda

df['ix'] = range(df.shape[0])

def idxmax(col, ix, maxout):
    maxidx = cuda.threadIdx.x
    for i in range(cuda.threadIdx.x, len(col), cuda.blockDim.x):
        maxout[i] = -1
        if col[i] > col[maxidx]:
            maxidx = i
    maxout[0] = ix[maxidx]

g = df.groupby(...)
res = g.apply_grouped(idxmax, incols=['col', 'idx'], outcols={"maxout": int})
# the idxmax is in res['maxout'][0]
```

I think a similar thing should work for non-groupby idxmax with apply_rows. I haven't tested this in a while though so it may not work (or I may have a bug in the above snippet), and there may be better ways.

**Comment by harrism** [comment]
argmin and argmax were implemented in libcudf groupby way back in #3616. Just needs Cython. CC @karthikeyann

**Comment by karthikeyann** [comment]
cudf groupby needs additional gather from results of libcudf.groupby aggregation (idxmax, idxmin).
@shwina could help on where this gather should go.

**Comment by shwina** [comment]
The argmin and argmax aggregations return the positions of the min/max value per group, whereas Pandas `idxmin` and `idxmax` return the values of the Index at those positions. So, in Python, we need to use the libcudf result as a gathermap into the index.

The groupby Python code currently doesn't easily support this kind of post-processing. I'll follow up with an issue/PR to address that shortly, but until then, the `idxmin` and `idxmax` aggregations won't work as expected in Python.

**Comment by beckernick** [comment]
This appears to have been implemented, so I'll close this. @shwina or @asmeurer please feel free to reopen if things don't work as expected.

```python
import cudf
from cudf.tests.utils import assert_eq
​
df = cudf.datasets.randomdata(nrows=10000)
pdf = df.to_pandas()
​
assert_eq(
    df.groupby("id").idxmax().sort_index().astype("int64"), # we return int32s by default
    pdf.groupby("id").idxmax().sort_index()
)
​
assert_eq(
    df.groupby("id").idxmin().sort_index().astype("int64"),
    pdf.groupby("id").idxmin().sort_index()
)
True
```
