### ISSUE TITLE
[FEA] `to_arrow` should clear the padding bits in the bitmask

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2210]
**Is your feature request related to a problem? Please describe.**
According to the Arrow spec:
> Bitmaps are to be initialized to be all unset at allocation time (this includes padding).

This would imply that bits outside the range `[0, size)` should always be zero. However, in cuDF/libcudf, we take a more conservative approach and say that bits outside `[0,size)` are undefined in order to avoid any potential issues.

The only potential issue I see is if an output from libcudf is consumed by some other library that supports Arrow, and that library makes assumptions about the state of the padding bits. In which case, we can guard against that in our `to_arrow` calls to zero out the padding bits.

**Describe the solution you'd like**
In `cuDF` and `libcudf` (which doesn't exist yet) `to_arrow` calls, the bits outside `[0, size)` should be cleared in accordance with Arrow spec.

**Comment by kkraus14** [comment]
Marking as a good first issue on the cuDF side as it's a great place to see how we're currently using Numba with bitmasks.
