### ISSUE TITLE
[FEA] Add `split` and `slice` functions that return zero-copy, non-owning views of columns

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#2211]
In Spark when we shuffle data between machines we will partition the data and then serialize out each partition separately, because each partition is likely to go to a different machine.   As a part of the serialization we would like to capture the null count for each partition, but there is no way to currently do that efficiently.

We could do it on the receiving end where we take all of the data and concatenate it back together, and then call gdf_count_nonzero_mask on it, but that is a legacy operation that I would rather not rely on.  Also if I can get the null count early I can potentially avoid sending unnecessary validity buffers across the wire.

**Comment by jrhemstad** [comment]
With the latest `bitmask` and `bitmask_view` design, you can create a zero-copy "slice" of a `column` or `bitmask` and then read the `null_count` from that slice. 

I haven't figured out all the details yet, but you can see what the `slice` API would look like for `bitmask` here: https://github.com/rapidsai/cudf/blob/c7df113f2f302ca1fbe09f1a52c92a43b1e75a03/cpp/include/cudf/bitmask/bitmask.hpp#L212 

I haven't extended this to `column` yet as I'm working on finishing all the bitmask stuff first. But the basic idea is that a `column` or `column_view` will have a `null_count()` member function that upon first invocation will launch a kernel to count the number of null bits, and then store (memoize) that information. Assuming that null count is invalidated, later calls will simply return the stored value. At a later point, that null count may be invalidated, after which a future call to `null_count()` would require recomputing it. I just haven't figured out all the events will require invalidating the stored null counts.

**Comment by revans2** [comment]
I'm not sure that really fits.  It would work but not be that efficient. I would end up calling it for each partition * each column.  The default partitioning for spark is 200, which is horrible, but also not that unreasonable if we have to make sure each partition can fit in GPU memory for processing.  The ideal would be to have something that can do it all at once, so it is only on the order of the number of columns.  I don't really want it to be a part of calling partition because there are other ways we want to partition the data besides hash partitioning that might not involve calling a kernel at all.

**Comment by jrhemstad** [comment]
Sounds like you want something like `cudf::split` or `cudf::slice` APIs that return a set of zero-copy views instead of  deep copied columns: https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/copying.hpp#L231

**Comment by revans2** [comment]
yes that looks like it would work.

**Comment by kkraus14** [comment]
@jrhemstad we could really benefit from zero-copy views instead of deep copied columns from the Python side as well.

**Comment by jrhemstad** [comment]
> @jrhemstad we could really benefit from zero-copy views instead of deep copied columns from the Python side as well.

Yeah, it's in the works.

**Comment by jrhemstad** [comment]
I updated the title of the issue to better reflect the work that's required.
