### ISSUE TITLE
[BUG] Use dictionary values during  categorical type conversion

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#2222]
I expected `Series.astype(x)`, for categoricals, to act on dictionary values, but it may be working on dictionary keys.

Repro:

```
df = pd.DataFrame( {'c': pd.Series([20, 10, 20], dtype="category")} )
gdf = cudf.DataFrame.from_pandas(df)
```

Pandas (Expected):
```
df['c'].astype('int32')
=> 
0    20
1    10
2    20
Name: c, dtype: int32
```

Cudf (Buggy):
```
gdf['c'].astype('int32').to_pandas()
=>
0    1
1    0
2    1
Name: c, dtype: int32
```

This was in 0.7, worth first reproducing in head.

Current workaround is round trip through pandas:

```
gdf['c'].to_pandas().astype('int32')
=>
0    20
1    10
2    20
Name: c, dtype: int32
```

**Comment by kkraus14** [comment]
Currently typecasting to/from categoricals isn't implemented yet and it erroneously operates against the codes instead of the full column. We should throw an exception loudly here instead of what we're currently doing.

**Comment by lmeyerov** [comment]
Yes, that would have saved an afternoon :)

**Comment by kkraus14** [comment]
This now works as expected, closing.
