### ISSUE TITLE
[FEA] support unstack function with multi-index dataframe

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/cudf#2227]
**Is your feature request related to a problem? Please describe.**
Time series data are usually given in a dataframe as follows:
```
import pandas as pd
df = pd.DataFrame({'sequence_id':[1,1,1,2,2,3,3,3,3],
                   'time':[1,2,3,1,2,1,2,3,4],
                   'value':[0.2,0.2,0.3,0.3,0.4,0.5,0.6,0.7,0.8]})
```
It is slow to sample sequences from such a dataframe since each sequence has different length and span multiple rows. The unstack function can transform such dataframe so that each sequence is in a separate row. 
```
df = df.set_index(['sequence_id','time']).unstack(-1)
df
            value               
time            1    2    3    4
sequence_id                     
1             0.2  0.2  0.3  NaN
2             0.3  0.4  NaN  NaN
3             0.5  0.6  0.7  0.8
```

**Describe the solution you'd like**
Support the unstack [function](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.unstack.html) of pandas.

**Comment by ayushdg** [comment]
Similar to #1821

**Comment by beckernick** [comment]
This is now resolved, likely by https://github.com/rapidsai/cudf/pull/5779
