### ISSUE TITLE
[FEA] `is_monotonic_increasing` and `is_monotonic_decreasing` functions

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#2240]
Pandas APIs:
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.is_monotonic_increasing.html
- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Index.is_monotonic_decreasing.html

Above functions should operate against a single column. And are essentially is this column sorted ascending / descending.

Additionally, should be able to run the same functions against a cudf::table.

**Comment by jrhemstad** [comment]
We should just have APIs that work on a `cudf::table`. 

The implementation should be a pretty straightforward application of `thrust::all_of` using `row_inequality_comparator` https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/table/device_table_row_operators.cuh#L97

**Comment by kkraus14** [comment]
Operating only on a `cudf::table` is perfectly fine from the Python perspective.

**Comment by jrhemstad** [comment]
Actually, I think this should just be a single function, `is_sorted` and should follow the same scheme of `order_by` and `upper/lower_bound` where you can specify the ascending/descending nature of each column:

Something like this:
```
bool is_sorted(table const& t,
                       std::vector<bool> const& ascending,
                       bool nulls_as_largest = true);
```

**Comment by rgsl888prabhu** [comment]
@jrhemstad 
Are we checking only one column in the table or all ?
If it's all, will we be returning vector which will represent all the column ?

I just wanted to clarify because the the "is_sorted" function return type is just bool.

**Comment by jrhemstad** [comment]
> Are we checking only one column in the table or all ?
> If it's all, will we be returning vector which will represent all the column ?

We're verifying that the _rows_ of the table are sorted. Therefore there is only a single `bool` returned.

**Comment by rgsl888prabhu** [comment]
> > Are we checking only one column in the table or all ?
> > If it's all, will we be returning vector which will represent all the column ?
> 
> We're verifying that the _rows_ of the table are sorted. Therefore there is only a single `bool` returned.

Are we checking whether all the columns in the table are sorted and will return true only if all the columns are sorted ?

I was just comparing with usual sorting where a column is sorted and all other associated columns are sorted according to it. And normally other columns might not preserve their orders. So, are we checking whether this sorting actually arranges all other columns in order ?

**Comment by jrhemstad** [comment]
> > > Are we checking only one column in the table or all ?
> > > If it's all, will we be returning vector which will represent all the column ?
> > 
> > 
> > We're verifying that the _rows_ of the table are sorted. Therefore there is only a single `bool` returned.
> 
> Are we checking whether all the columns in the table are sorted and will return true only if all the columns are sorted ?
> 


No, you're checking if the _rows_ are lexicographically sorted. It's like alphabetically sorting a list of words:

```
aaaa
aabb
abbc
```

**Comment by rgsl888prabhu** [comment]
> > > > Are we checking only one column in the table or all ?
> > > > If it's all, will we be returning vector which will represent all the column ?
> > > 
> > > 
> > > We're verifying that the _rows_ of the table are sorted. Therefore there is only a single `bool` returned.
> > 
> > 
> > Are we checking whether all the columns in the table are sorted and will return true only if all the columns are sorted ?
> 
> No, you're checking if the _rows_ are lexicographically sorted. It's like alphabetically sorting a list of words:
> 
> ```
> aaaa
> aabb
> abbc
> ```

So, in this case the gdf_columns would be

gdf_column1 a a a
gdf_column2 a a b
gdf_column3 a b b
gdf_column4 a b c

Am I correct ?

**Comment by jrhemstad** [comment]
> > > > > Are we checking only one column in the table or all ?
> > > > > If it's all, will we be returning vector which will represent all the column ?
> > > > 
> > > > 
> > > > We're verifying that the _rows_ of the table are sorted. Therefore there is only a single `bool` returned.
> > > 
> > > 
> > > Are we checking whether all the columns in the table are sorted and will return true only if all the columns are sorted ?
> > 
> > 
> > No, you're checking if the _rows_ are lexicographically sorted. It's like alphabetically sorting a list of words:
> > ```
> > aaaa
> > aabb
> > abbc
> > ```
> 
> So, in this case the gdf_columns would be
> 
> gdf_column1 a a a
> gdf_column2 a a b
> gdf_column3 a b b
> gdf_column4 a b c
> 
> Am I correct ?

Yes, exactly. And there's already machinery that compares inequality between two rows: https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/table/device_table_row_operators.cuh#L198

Your implementation should basically just be a call to `thrust::all_of` where you check that row `i` is less than row `i+1`, using the `row_inequality_comparator`.

**Comment by rgsl888prabhu** [comment]
> Actually, I think this should just be a single function, `is_sorted` and should follow the same scheme of `order_by` and `upper/lower_bound` where you can specify the ascending/descending nature of each column:
> 
> Something like this:
> 
> ```
> bool is_sorted(table const& t,
>                        std::vector<bool> const& ascending,
>                        bool nulls_as_largest = true);
> ```

In that case, why do we need a vector of bool values which represent ascending or descending, we just need a single bool.

**Comment by jrhemstad** [comment]
Because you want to be able to control how each column is compared. Look at the `asc_desc_flags` in `row_inequality_comparator` : https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/table/device_table_row_operators.cuh#L206

**Comment by rgsl888prabhu** [comment]
That clarifies all my doubts, thank you.
