### ISSUE TITLE
[FEA] Create `__contains__` functions for Index / Series / Column objects

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#2243]
This would allow us to do things like:
```python
test = cudf.Series([1,2,3])
print(3 in test)
# True
```

Though Pandas has some weird behavior here where it looks like it always operates against the index as opposed to the values in the Series.

**Comment by harrism** [comment]
@kkraus14 @rgsl888prabhu it would be fairly straightforward to add this to libcudf. We can just `thrust::find_if` with a lambda that respects nulls. Please file a FEA bug against libcudf if you think it's needed.

For already sorted columns, you can use `cudf::lower_bound` today.
