### ISSUE TITLE
AUC not consistent after xgboost training on same server and data

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#2248]
The AUC results (pdf attached) between xgboost training using cudf are not consistent.  There can be as much as a 12 point change between training on the same data on the same server.  The Jupyter notebook (attached) runs multiple dask xgboost training using cudf on the same data to illustrate the variance in AUC.

The weighted average of each run:
```
-- AUC: 78.06105606919284
-- AUC: 90.93877137252815
-- AUC: 89.72277069191611
-- AUC: 83.03834637659703
```

[mortgage_dask_auc_results.pdf](https://github.com/rapidsai/dask-cudf/files/2705505/mortgage_dask_auc_results.pdf)

[small_dask_mortgage.zip](https://github.com/rapidsai/dask-cudf/files/2705507/small_dask_mortgage.zip)

**Comment by kkraus14** [comment]
Closing as not cudf.
