### ISSUE TITLE
README.md outdated

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cudf#2249]
**I.**
**Following the instruction**

1. Install dependencies into a new conda environment

conda create -n dask-cudf \
   -c rapidsai -c numba -c conda-forge -c defaults \
   cudf dask cudatoolkit

**produces the following error.**

Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cudf -> libcudf=0.5.1 -> nvstrings
  - cudf -> libcudf_cffi=0.5.1

**adding -c nvidia fixes this problem.**

**II.**
**And the above instruction assumes CUDA 9.2. To use CUDA10**

**One needs to replace -c nvidia -c rapidsai with -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0** (based on https://github.com/rapidsai/cudf/blob/branch-0.6/README.md). Adding this instruction will be helpful to users who want to use CUDA 10.

**Comment by quasiben** [comment]
This issues was brought over from the now archived dask-cudf repo.  It is no longer relevant as the cudf readme is up to date
