### ISSUE TITLE
Use mainline Dask DataFrame Join implementation

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2250]
We should replace the join/merge implementation in dask-cudf with the upstream implementation in dask.dataframe.

The Dask dataframe join implementation is a bit more fully featured than the implementation here in dask-cudf.  In particular it includes solutions for things like joins-on-sorted-indexes (see #76), joins other than "left", joins against single-partition dataframes, and other common cases.  It would be useful at some point to remove the join implementation within this dask-cudf codebase, and rely on the upstream implemenatation.

We did exactly this recently with groupby-aggregations in https://github.com/rapidsai/dask-cudf/pull/69 .  This approach tends to require two sets of work:

1.  Make the Dask Dataframe implementation more flexible to Pandas-*like* objects
2.  Make cuDF more Pandas-like in a few ways to fit into Dask's expectations

Our experience with groupby-aggregations is that this resulted in something like 10 small issues upstream to cuDF, which maintainers there seem to be able to handle within about half a day each.  I don't have a strong expectation on how expensive this would be (though I'll take a look shortly)

cc @randerzander @quasiben @kkraus14 @thomcom

**Comment by quasiben** [comment]
closed by: https://github.com/rapidsai/cudf/pull/3243
