### ISSUE TITLE
[feature request] Specification of "pandas-like dataframe" needed

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#2251]
As implied by issue #79, dataframe objects managed by dask.dataframe need to be "pandas-like".  Would it be possible to provide a specification that dataframe libraries like pandas, cudf, and others can implement to ensure compatibility with dask.dataframe?  (This is a request for such a specification.)

**Comment by kkraus14** [comment]
There are ongoing community efforts in defining DataFrame specifications that we are engaged in. Most notably: https://github.com/wesm/dataframe-protocol

Going to close this issue in favor of community efforts.
