### ISSUE TITLE
Solutions for creating random datasets

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2252]
For examples and testing it would be useful to have functions to generate random dataframes.

### Use dask.datasets.timeseries

For Pandas-backed Dask Dataframe we have the `dask.datasets.timeseries` function

```python
>>> import dask
>>> df = dask.datasets.timeseries()
>>> df.head()
                       id     name         x         y
timestamp
2000-01-01 00:00:00  1031   Yvonne -0.925042 -0.236635
2000-01-01 00:00:01   980    Edith -0.994766  0.698225
2000-01-01 00:00:02  1012   Ingrid  0.851759  0.631721
2000-01-01 00:00:03   973  Norbert -0.584185  0.256136
2000-01-01 00:00:04   974   Oliver -0.153558 -0.840026

>>> df
Dask DataFrame Structure:
                   id    name        x        y
npartitions=30
2000-01-01      int64  object  float64  float64
2000-01-02        ...     ...      ...      ...
...               ...     ...      ...      ...
2000-01-30        ...     ...      ...      ...
2000-01-31        ...     ...      ...      ...
Dask Name: make-timeseries, 30 tasks
```

In theory we could do something like ...

```python
>>> df = dask.datasets.timeseries().map_partitions(cudf.from_pandas)
```

except ...

1.   We'll have to use the `dtypes=` keyword to avoid string types (until string support arrives)
2.  We might have to use `reset_index()` to avoid a timeseries index (which I think isn't currently supported?)
3.  We'll be generating data on the CPU and then moving it to the GPU

Those might all be totally acceptable costs.

### Generate our own data with cupy

This blogpost shows how to use cupy and dask array to generate random dask arrays on the device: http://blog.dask.org/2019/01/03/dask-array-gpus-first-steps

We could then map `cudf.Series` across those blocks and that would hopefully produce a `dask_cudf.Series` object.  We would then concatenate a bunch of those together with `axis=1` to form columns of a `dask_cudf.DataFrame`.

**Comment by quasiben** [comment]
This has been implemented:

```python
import cudf
cdf = cudf.datasets.timeseries()
```
