### ISSUE TITLE
[FEA] Support Parquet, ORC, JSON readers & writers

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2254]
cuDF recently merged support for more file formats, including Parquet, ORC, JSON, Feather, and HDF5.

Today we can work with those file formats by using dask.read_parquet, etc, but that'll convert them to Pandas DataFrames, and requires the user to then do a .map_partitions to turn pd.DataFrames into cudf.DataFrames. That is slow and a painful user experience.

dask-cudf should be extended to handle reading and Parquet, ORC, and JSON file formats directly into cudf.DataFrames. It should also support writing into Parquet, and JSON file formats (ORC has no cudf writer at this time).

**Comment by kkraus14** [comment]
Closing as we support all of the above readers and writers as of current release.
