### ISSUE TITLE
[FEA] dask-cudf should expose cudf functions that don't have dask equivalents

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2264]
cudf has functions which don't have dask analogues.

For example:
```
import cudf, dask_cudf

df = cudf.DataFrame()
df['ones'] = [1, 1, 1]

ddf = dask_cudf.from_cudf(df, npartitions=1)
ddf['ones'].to_gpu_array()
```

Result:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-912c9fd2ec6f> in <module>
      8 ddf = dask_cudf.from_cudf(df, npartitions=1)
      9 
---> 10 ddf['ones'].to_gpu_array()

AttributeError: 'Series' object has no attribute 'to_gpu_array'
```

For a cudf user, this error is confusing. I went to look at cudf's API to see if cudf dropped this function before realizing it just doesn't exist in dask-cudf.

Other similar functions include `to_gpu_matrix`, `as_gpu_matrix`, `from_gpu_matrix`.

Instead of adding such methods to dask-cudf, would it make sense to catch this type of `Series` or `DataFrame` `has no attribute` error and attempt to have each partition call the given cudf function?

If so, it would help avoid the user pain of needing to fall back to `dask.delayed` workarounds.

**Comment by kkraus14** [comment]
Closing as we've pushed in general to mirror the Pandas API which makes this a moot point, but will continue to reserve the right to expose additional APIs as desired.
