### ISSUE TITLE
Profile indexed joins

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2265]
Here is a notebook which does indexed joins.  The data prep is a bit messy (I'll look at cleaning this up soonish) but the actual dask-cudf joins are pretty slick.  Here is the resulting profile output:

https://gist.github.com/mrocklin/ab10c61a17391e8dbc7577f83fc4d25d

**Comment by kkraus14** [comment]
Closing as we've spent quite a bit of time profiling and optimizing joins.
