### ISSUE TITLE
TypeError: can't pickle CompiledFFI objects

### ISSUE THREAD

**Issue by AK-ayush** [rapidsai/cudf#2267]
I am trying to run [this notebook](https://gist.github.com/AK-ayush/c004868c6cdee15698d2582b13a671e7) using dask. 

When I run each cell as in sequential manner, it is running perfectly 
but when I create a dask dag and then it is giving this error: `TypeError: can't pickle CompiledFFI objects`

**Comment by kkraus14** [comment]
CFFI is gone so this is no longer an issue, closing.
