### ISSUE TITLE
Development process

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2273]
In this repository we've been using master and squashed commits somewhat uniformly over the past few months.  During the release process it looks like some automated processes have moved to branch-0.6 and branch-0.7 and merge commits.  What is our plan going forward?

cc @kkraus14 @mike-wendt @raydouglass @quasiben

**Comment by quasiben** [comment]
dask-cudf has now been merged into the cudf repository and we are now following cudf development processes
