### ISSUE TITLE
Rename CHANGELOG.rst to CHANGELOG.md

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#2274]
Hi,

It looks like the CHANGELOG file extension is not consistent with the other RAPIDS packages. 

For dask-cudf, we have CHANGELOG.**rst**. For cuDF, cuML, and cuGraph, we have CHANGELOG.**md**.

Hope it helps.

Regards,
Miguel

**Comment by quasiben** [comment]
I think we can close this as dask-cudf is now in the cudf repository:
https://github.com/rapidsai/cudf/tree/branch-0.12/python/dask_cudf

**Comment by miguelangel** [comment]
Sure! Thanks!
