### ISSUE TITLE
What does the DataFrame.join method do?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2275]
I'm confused about the `DataFrame.join` method.  It appears to be different from the join implementation in the `join_impl` module but looking briefly at the code I'm not sure what it's supposed to actually do.  Unfortunately it has a lot of non-trivial logic and not a ton of documentation.

cc @sklam , do you recall what the intent was behind this method, and how it related to the code in join_impl?

**Comment by quasiben** [comment]
closing as dask-cudf now uses mainline dask for joins
