### ISSUE TITLE
dask_cudf.read_csv has no docstring

### ISSUE THREAD

**Issue by gravitino** [rapidsai/cudf#2277]
dask_cudf.read_csv has no docstring. At least one should state that you forward the arguments to cudf.read_csv.

**Comment by jangorecki** [comment]
It would be very useful to include in documentation a complete working example of using managed memory. In plain cudf: `cudf.set_allocator("managed")`. That would cover #2288 too. If possible also using dask in a non-cluster setup, current comment in #2288 mentions only `client = Client(cluster)` way. AFAIU it is not really needed when parallelizing computation over multiple GPUs on the same machine, and not a cluster.

**Comment by jangorecki** [comment]
is it possible to assign this issue to a milestone?
