### ISSUE TITLE
[Discussion] Dask groupby compatibility with cudf groupby methods (hash, sort)

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2278]
Cudf's groupby slightly deviates from pandas in that it provides a `method` argument allowing us to provide method=hash, sort etc. 

I have workflows with aggregations such as `first` and `last` which are currently not supported by cudf but my understanding is that even if it does get implemented, it would be a part of the sort based groupby as ordering in the hash based one is non-deterministic and therefore doing `first` `last` does not make much sense. 

Since I cannot provide any method argument to Dask's native groupby and cudf by default uses `hash`, I would not be able to use some of the aggregations provided by cud's groupby (or use sort based methods if needed) with dask. 

Is there some way of working around this issue without having to change anything from the cudf or dask end?

One approach of using `map_partitions` or `dask_delayed` function to call cudf's groupby doesn't really help too much as it performs the operation on each partition and therefore my aggregations results belong to each partition and not the overall Dataframe.

Open to suggestions and ideas which would also help workflows that extensively use groupby's and need to scale using dask.

**Comment by kkraus14** [comment]
We've removed the `method` keyword where it auto selects which to use based on the passed in aggregations in libcudf. Closing this.
