### ISSUE TITLE
[Performance] Directly accessing date-time (.dt) is slower than using .map_partitions() and an accessor

### ISSUE THREAD

**Issue by deltadu** [rapidsai/cudf#2282]
It is slower to directly access date-time (.dt) info

```
gdf['hour'] = gdf['pickup_datetime'].dt.hour
gdf['year'] = gdf['pickup_datetime'].dt.year
gdf['month'] = gdf['pickup_datetime'].dt.month
gdf['day'] = gdf['pickup_datetime'].dt.day
gdf['diff'] = gdf['dropoff_datetime'].astype('int32') - gdf['pickup_datetime'].astype('int32')
```

While using .map_partitions() and an 'accessor' function runs faster: 

```
def add_features(df):
    df['hour'] = df['pickup_datetime'].dt.hour
    df['year'] = df['pickup_datetime'].dt.year
    df['month'] = df['pickup_datetime'].dt.month
    df['day'] = df['pickup_datetime'].dt.day
    df['diff'] = df['dropoff_datetime'].astype('int32') - df['pickup_datetime'].astype('int32')

gdf.map_partitions(add_features)
```

The data was partitioned to 8 workers before we tried to access it.
I run 5 iterations with both methods, and the time cost is:
**direct accessing:**
[0.441, 0.460, 0.467, 0.454, 0.466] seconds

**map_partitions:**
[0.219, 0.042, 0.043, 0.041, 0.040] seconds

**Comment by kkraus14** [comment]
Closing as this is stale. If this is still an issue feel free to reopen.
