### ISSUE TITLE
[FEA] Support for accessing keys and values of groupby objects

### ISSUE THREAD

**Issue by neileshc** [rapidsai/cudf#2289]
**Is your feature request related to a problem? Please describe.**
I wish I could groupby cudf dataframes by multiple columns.

**Describe the solution you'd like**
I want to have groupby objects based on multiple columns. I also would like to be able to loop over the key/value pairs.

**Describe alternatives you've considered**
I used Pandas for this step outside and then passed sorted frames but this slows down my code

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

Code snippet:
test = pd.DataFrame({'key1': ['A', 'B', 'B', 'D'],
                     'key2': ['E', 'B', 'B', 'H'],
                     'key3': [ 1, 2, 3, 4],
                     'key4': [0.1, 0.2, 0.3, 0.4]})
test
>>
               key1       key2       key3       key4
0             A             E             1             0.1
1             B             B             2             0.2
2             B             B             3             0.3
3             D            H            4             0.4

g = (test.groupby(['key1','key2']))
print('keys','     size')
for k,v in g:
    print(k,len(v))
>>
keys      size
('A', 'E') 1
('B', 'B') 2
('D', 'H') 1

**Comment by jrhemstad** [comment]
Superseded by #3082
