### ISSUE TITLE
[FEA] Support for `groupby.apply`

### ISSUE THREAD

**Issue by neileshc** [rapidsai/cudf#2290]
**Is your feature request related to a problem? Please describe.**
I wish I could apply custom functions on cudf series.

**Describe the solution you'd like**
 I want to have cudf series on which I can apply my own functions.

**Describe alternatives you've considered**
I do this in Pandas for now as additional step which slows down the functionality

**Additional context**
code snippet:

def step1(data):
    tmp = [data[col].tolist() for col in ['key3','key4']]
    return tmp

test = pd.DataFrame({'key1': ['A', 'B', 'B', 'D'],
                     'key2': ['E', 'B', 'B', 'H'],
                     'key3': [ 1, 2, 3, 4],
                     'key4': [0.1, 0.2, 0.3, 0.4]})
test
>>
               key1       key2       key3       key4
0             A             E             1             0.1
1             B             B             2             0.2
2             B             B             3             0.3
3             D            H            4             0.4

g = (test.groupby(['key1','key2']))
s1 = g.apply(step1)
s1
>>
key1  key2
A     E               [[1], [0.1]]
B     B       [[2, 3], [0.2, 0.3]]
D     H               [[4], [0.4]]
dtype: object

**Comment by beckernick** [comment]
@neileshc you can execute UDFs on grouped dataframes using the `apply_grouped` API method. Currently, it only supports numeric data. You may find the [docs](https://rapidsai.github.io/projects/cudf/en/0.8.0/api.html#cudf.groupby.legacy_groupby.Groupby.apply_grouped) useful, as well as [this](https://github.com/Quansight/scipy-2019-rapids-tutorial/blob/master/cudf/Intro%20to%20cuDF%20UDFs.ipynb) UDFs notebook.

Is your goal to execute groupby UDFs on string columns, as in your example?

**Comment by vyasr** [comment]
We now support `groupby.apply`. While our functionality is not (and will never be) quite as general as pandas', we are working to improve on both performance and coverage. We can open more targeted issues to discuss those more specific thrusts.
