### ISSUE TITLE
[FEA] Support for operations on dataframe with list, dicts, numbers, and strings as datatype

### ISSUE THREAD

**Issue by neileshc** [rapidsai/cudf#2291]
**Is your feature request related to a problem? Please describe.**
I wish I could have lists, arrays, dicts, ... in my cudf dataframe.

**Describe the solution you'd like**
I want cudf let me have lists and arrays and also strings in my cudf and also let me apply functions (apply_row for example) on them. currently apply_row only works with numerical values.

**Describe alternatives you've considered**
I had to create a much bigger cudf dataframe that contains the flattened version of arrays, tuples, and lists. This is done in Pandas and could be time consuming.

**Additional context**
code snippet in pandas

test = pd.DataFrame({'key1': ['A', 'B', 'B', 'D'],
                     'key2': [['E'], ('B'), {'B':0}, 0.123]})
test
>>
               key1       key2
0             A             [E]
1             B             B
2             B             {'B': 0}
3             D            0.123

**Comment by kkraus14** [comment]
@neileshc Strings and Numbers are supported today. We are working on supporting nested columns (think list) in the future and it is dependent on #2207. Supporting dicts via something dictionary like is something that will be very far down the line if ever supported.

Pandas allows you to use arbitrary Python objects in your DataFrame, but it does this at the cost of a LOT of performance and we will not support arbitrary Python objects at any point in the future.
