### ISSUE TITLE
[BUG] Deep copying a column should just copy the mask instead of allocating and filling it

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#2294]
Deep copying a column should use libcudf `cudf::copy` instead of the current Numba implementation which copies the buffers one by one.

**Comment by jrhemstad** [comment]
Can this just use `cudf::copy` instead? https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/copying.hpp#L54

**Comment by kkraus14** [comment]
Didn't know that existed, yes!
