### ISSUE TITLE
[BUG] Python typecasting should use libcudf `gdf_cast` instead of numba

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#2295]
Basically replace `cudautils.astype` with using the function provided in `typecast.pyx` which are Cython bindings to the libcudf `gdf_cast` function.

**Comment by jrhemstad** [comment]
This should wait until https://github.com/rapidsai/cudf/pull/2202 is complete.

**Comment by galipremsagar** [comment]
> This should wait until #2202 is complete.

Have made the changes based on #2202 changes. But yes will refactor once the changes are finalized too.

**Comment by jrhemstad** [comment]
> > This should wait until #2202 is complete.
> 
> Have made the changes based on #2202 changes. But yes will refactor once the changes are finalized too.

As long as you're based off of #2202, then you're golden.
