### ISSUE TITLE
[BUG] Merge fills in values in the other key that should be NaN/null when left_on and right_on differ

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2299]
Calling merge on columns with partial overlap does not produce NaNs/nulls in the resultant dataframe. Instead, the "missing values" from the key column are filled with the key value from the other key column.

cuDF:
```python
import cudf
import pandas as pd
​
df1 = cudf.DataFrame({'a':[0,1,2.0,3,4,5, 9]})
df2 = cudf.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
​
res = df1.merge(df2, how='left', left_on=['a'], right_on=['b'])
print(res)
     a    b  c
0  3.0  3.0  2
1  5.0  5.0  1
2  9.0  9.0  3
3  0.0  0.0   
4  1.0  1.0   
5  2.0  2.0   
6  4.0  4.0   
7  5.0  5.0  4
```

pandas:
```python
import cudf
import pandas as pd
​
df1 = pd.DataFrame({'a':[0,1,2.0,3,4,5, 9]})
df2 = pd.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
​
res = df1.merge(df2, how='left', left_on=['a'], right_on=['b'])
print(res)
     a    b    c
0  0.0  NaN  NaN
1  1.0  NaN  NaN
2  2.0  NaN  NaN
3  3.0  3.0  2.0
4  4.0  NaN  NaN
5  5.0  5.0  1.0
6  5.0  5.0  4.0
7  9.0  9.0  3.0
```

```
commit 28492c82d39aca7f9ee64c7d74138158914965bb
Merge: 78116de 6eb5861
Author: Keith Kraus <kkraus@nvidia.com>
Date:   Mon Jul 15 11:14:58 2019 -0400
```

**Comment by jrhemstad** [comment]
I wonder if this is an issue with how the `left_on`, `right_on` arguments are being handled?

@beckernick can you try it where the 'on' columns have the same name and don't need to be explicitly specified? Otherwise this is a pretty trivial left join and I would think we would have uncovered an issue like this a long time ago.

**Comment by kkraus14** [comment]
This may be a Python / Cython issue in what returned column we're using for the output. cc @shwina @thomcom

**Comment by beckernick** [comment]
@jrhemstad you're correct. When the key names are the same, this doesn't occur.

```python
import cudf
import pandas as pd
​
df1 = cudf.DataFrame({'a':[0,1,2.0,3,4,5, 9]})
df2 = cudf.DataFrame({'a':[12,5.0,3,9,5], 'c':range(5)})
​
res = df1.merge(df2, how='left', left_on=['a'], right_on=['a'])
print(res)
     a  c
0  3.0  2
1  5.0  1
2  9.0  3
3  0.0   
4  1.0   
5  2.0   
6  4.0   
7  5.0  4
```

**Comment by kkraus14** [comment]
@jrhemstad I think the issue is libcudf only returns one column per pair of key columns, whereas Pandas only has that behavior if the columns are named the same. We worked around this by copying the key column(s) we return into two columns as needed, but this doesn't account for the bitmask properly on `left` and `outer` joins.

**Comment by kkraus14** [comment]
Another problematic case:
```
In [64]: import cudf
    ...: import pandas as pd
    ...:
    ...: df_lib = pd
    ...:
    ...: df1 = df_lib.DataFrame({'a':[0,1,2.0,3,4,5,9]})
    ...: df2 = df_lib.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
    ...:
    ...: res = df1.merge(df2, how='outer', left_on=['a'], right_on=['b'])
    ...: print(res)
     a     b    c
0  0.0   NaN  NaN
1  1.0   NaN  NaN
2  2.0   NaN  NaN
3  3.0   3.0  2.0
4  4.0   NaN  NaN
5  5.0   5.0  1.0
6  5.0   5.0  4.0
7  9.0   9.0  3.0
8  NaN  12.0  0.0

In [65]: import cudf
    ...: import pandas as pd
    ...:
    ...: df_lib = cudf
    ...:
    ...: df1 = df_lib.DataFrame({'a':[0,1,2.0,3,4,5,9]})
    ...: df2 = df_lib.DataFrame({'b':[12,5.0,3,9,5], 'c':range(5)})
    ...:
    ...: res = df1.merge(df2, how='outer', left_on=['a'], right_on=['b'])
    ...: print(res)
      a     b  c
0   3.0   3.0  2
1   5.0   5.0  1
2   9.0   9.0  3
3   0.0   0.0
4   1.0   1.0
5   2.0   2.0
6   4.0   4.0
7   5.0   5.0  4
8  12.0  12.0  0
```

**Comment by jrhemstad** [comment]
When `left_on` and `right_on` are different, I think this can be handled by passing an extra `gdf_column` that points to the same data as the left/right `key` column.

```
                         gdf_column **left_cols, 
                         int num_left_cols,
                         int left_join_cols[],
                         gdf_column **right_cols,
                         int num_right_cols,
                         int right_join_cols[],
                         int num_cols_to_join,
```

So with the above example:

```
left_cols: [[0,1,2.0,3,4,5,9]]
right_cols:[ [12,5.0,3,9,5], [12,5.0,3,9,5], [0, 1, 2, 3, 4] ] // note the shallow copy duplicate of the key column
left_join_cols: [0]
right_join_cols: [0] 
```

**Comment by kkraus14** [comment]
In the above example both columns `a` and `b` are incorrect, so I guess pass an extra shallow copied columns into both left and right?

**Comment by jrhemstad** [comment]
> In the above example both columns `a` and `b` are incorrect, so I guess pass an extra shallow copied columns into both left and right?

Yeah, for an outer join I suppose that would work. The column returned for the "keys" would just be discarded then I guess.  

This `left_on` and `right_on` stuff wasn't part of the requirements when the Join API was being designed, so we don't really handle it well. Join is overdue for an update and refactoring anyways, so we can revisit then.

**Comment by kkraus14** [comment]
@jrhemstad do you have a sense for the level of effort to fix this in the libcudf side? Should we just handle in Python for now or would you rather fix it in libcudf?

**Comment by jrhemstad** [comment]
> @jrhemstad do you have a sense for the level of effort to fix this in the libcudf side? Should we just handle in Python for now or would you rather fix it in libcudf?

Shouldn't be too hard. Updating this should happen concurrent with updating the API to use `cudf::table`. 

We'll have to find a clean way to specify the behavior of the returned `key` column, i.e., should we return a single key column vs. separate instances of the `key` columns from both the left and right tables.

**Comment by kkraus14** [comment]
@revans2 Does this behavior align with Spark?
