### ISSUE TITLE
[BUG] `category.set_keys` giving incorrect results

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2306]
**Describe the bug**

`category.set_keys` is giving incorrect results

**Steps/Code to reproduce bug**
```python
import  cudf
import pandas as pd

pd_sr = pd.Series([1,0,0,0,0,0,0,0,0,0,2]).astype('category')
cudf_sr = cudf.Series(pd_sr)
key_sr = cudf.Series([1,2])

cudf_sr.cat.set_categories(key_sr).to_pandas()
```

Current Output:
```python
0       1
1     NaN
2     NaN
3     NaN
4     NaN
5       2
6     NaN
7     NaN
8     NaN
9     NaN
10    NaN
dtype: category
Categories (2, int64): [1, 2]

```

**Expected behavior**
Expected output is :

```python
0       1
1     NaN
2     NaN
3     NaN
4     NaN
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
10      2
dtype: category
Categories (2, int64): [1, 2]
```
**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda] :

```
cudf                      0.9.0a                py37_1312    rapidsai-nightly
libcudf                   0.9.0a            cuda10.0_1312    rapidsai-nightly
```
Edit:

Updating with new example as somehow the previous example is fixed in the latest `libcudf` version.  (There was previously inconsistency in  my  `libcudf` and `cudf` version)

**Comment by kkraus14** [comment]
@trxcllnt Looks like somewhere that we're using a join where we aren't keeping track of the order along the way to resort.
