### ISSUE TITLE
[BUG] Unable To create a dask_cudf from gdfs in dask workers

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#2308]
**Describe the bug**
I try to run the following code and it fails
    
    import dask
    print(dask.__version__)
    def make_dask_df():
        df = cudf.DataFrame()
        df['key'] = [0, 1, 2, 3, 4]
        df['val'] = [float(i + 10) for i in range(5)]
        return df

    delayed_object = dask.delayed(make_dask_df)()
    dask_df = dd.from_delayed([delayed_object])`

My intention is to be able to make a dataframe in a dask worker and add it to a dask_df
**Steps/Code to reproduce bug**
run the code above in python with a dask-scheduler and worker running. 

**Expected behavior**
I expect to be able to generate a dask_cudf from this.

**Environment overview (please complete the following information)**
 - Environment location: google kubernetes engine
 - Method of cuDF install: from source
cuda branch-0.8, dask_cudf branch-0.8,

**Additional context**

**Comment by kkraus14** [comment]
This code works as expected for me on cudf 0.9 latest nightly, dask 2.1.0, and distributed 2.1.0. @felipeblazing if upgrading doesn't resolve feel free to reopen.
