### ISSUE TITLE
[BUG] Ascending flags in sorting APIs should be `bool`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2312]
**Describe the bug**

Several APIs that provide multi-column sorting functionality allow specifying if column `i` should be sorted in ascending or descending order. In several places, the types of these flags is `int8_t`. The type of these flags should instead be `bool` and changed throughout the codebase. 

**Expected behavior**

Change all occurrences of `int8_t` ascending flags to be `bool`. This includes:

- [`gdf_order_by`](https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/functions.h#L765)
- [`row_inequality_comparator` ](https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/table/device_table_row_operators.cuh#L284)

**Comment by harrism** [comment]
I think it might be more literate to use an enum?

```
enum sort_order {
    ORDER_ASCENDING,
    ORDER_DESCENDING
}
```
