### ISSUE TITLE
[FEA] astype Category

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#2315]
Currently cudf does not support astype('category') for converting a column (str, int, etc) to a category type.  As best as I can tell, cudf support for categoricals only works when building a cudf Series/Dataframe from a pandas series/dataframe which is type category

**Comment by kkraus14** [comment]
Duplicate of #1664

**Comment by quasiben** [comment]
Thanks @kkraus14

**Comment by shwina** [comment]
Fixed in #2318
