### ISSUE TITLE
[BUG] cuDF and PyArrow reads from ORC file does not match

### ISSUE THREAD

**Issue by Nanthini10** [rapidsai/cudf#2322]
**Describe the bug**
Data read from ORC file with cuDF and PyArrow do not match

**Steps/Code to reproduce bug**
```
# For all the orc files in a path
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".orc"):
            file_name = os.path.join(root, file)
            df_1 = cudf.read_orc(file_name)
            df_1 = df_1.to_arrow(preserve_index = False)
            print(df_1.schema)
            
            with open(file_name, 'rb') as f:
                df_2 = orc.ORCFile(f)
                df_2 = df_2.read()
                print(df_2.schema)
                print("\n****\n****\nComparing the two", df_1.equals(df_2))
```

**Expected behavior**
The two tables do not match in values.

**Environment overview (please complete the following information)**
 - Environment location: conda jupyter notebook
 - Method of cuDF install: conda 

**Environment details**
cudf version: "0.9.0a+1285.gf2e95bc.dirty"

**Comment by OlivierNV** [comment]
Bug in RLEv2 patched base mode, which previously had no coverage, will have a fix shortly.
