### ISSUE TITLE
[BUG] gdf_group_by_without_aggregations return incorrect value when input_table num_rows is zero

### ISSUE THREAD

**Issue by jeanp413** [rapidsai/cudf#2335]
**Describe the bug**
When the number of rows from input_table is zero in `gdf_group_by_without_aggregations` the return value contains a table with no columns.

**Expected behavior**
gdf_group_by_without_aggregations should return a table of empty columns with the same types as the inputs

**Comment by jrhemstad** [comment]
closed by https://github.com/rapidsai/cudf/pull/2304
