### ISSUE TITLE
[BUG] Filtering followed by column-creation based on np.where() fails

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2341]
I am filtering a dataframe based on a column value, and then creating a new column based on a condition specified in `np.where`. The below code fails with `AttributeError: 'str' object has no attribute 'data'`. 

```
import cudf
import numpy as np
df = cudf.DataFrame({"a":["abc","xyz"],"b":["x","y"],"time":["t1","t2"]})
df = df[df['time']=="t2"]
df['new'] = np.where((df['a'] == 'abc') | (df['a'] == 'xyz'), 1, 0)
```

However, if I remove ```df = df[df['time']=="t2"]``` and just perform the ```np.where()``` operation, everything works fine.

Anything I'm missing out?

**Comment by ayushdg** [comment]
For this particular case one workaround I can think of is using `masked_assign`
```
df['new'] = 0
mask = (df['a'] == 'abc') | (df['a'] == 'xyz')
df['new'] = df['new'].masked_assign(1, mask)
```

**Comment by chinmaychandak** [comment]
Thanks @ayushdg

**Comment by kkraus14** [comment]
This now works without issue, closing.
