### ISSUE TITLE
[BUG] cudf.read_orc asserts with no columns on Snappy ORC file

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2343]
cudf.read_orc will fail with "No columns found" when reading an ORC file using snappy compression.

```
>>> df = cudf.read_orc('data/000000_0.snappy')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/cudf-0.9.0a0+1364.g8088e6a-py3.7-linux-x86_64.egg/cudf/io/orc.py", line 45, in read_orc
    filepath_or_buffer, columns, stripe, skip_rows, num_rows, use_index
  File "cudf/bindings/orc.pyx", line 25, in cudf.bindings.orc.cpp_read_orc
  File "cudf/bindings/orc.pyx", line 59, in cudf.bindings.orc.cpp_read_orc
RuntimeError: cuDF failure at: /cudf/cpp/src/io/orc/orc_reader_impl.cu:150: No columns found
```

**Comment by randerzander** [comment]
@mjsamoht looking [here](https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/io/orc/orc_common.h#L24) we have enumerated various compression types. Can you comment which ones are actually implemented currently?

This is something we should document in the Python API docs.

**Comment by OlivierNV** [comment]
Snappy compression should be supported within read_orc (one of the compression method that we support). Is this by any chance a file that has been subsequently compressed ? (the .snappy extension would suggest that someone just compressed the file afterwards, so it's now a snappy archive that contains an ORC file, not an ORC file).

**Comment by OlivierNV** [comment]
For ORC, snappy and zlib are the two compression methods that are currently supported.
Failure at line 150 means that it got path the decompression stage, but failed to find any columns (or perhaps decompression failed ?) -> @randerzander can you attach the file 00000_0,snappy ?

**Comment by mjsamoht** [comment]
@randerzander can you attach the file `00000_0.snappy`?

**Comment by randerzander** [comment]
It turns out the file was not actually ORC encoded.
