### ISSUE TITLE
[FEA] Supported nested data with "cudf.io.json.read_json"

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#2362]
**Describe the bug**

I want to read json files and import them into data frames. Each json file includes multiple json objects. “pandas.read_json” reads the files correctly. The shape of each dataframe should be (XXX, 19), and that’s what I get from pandas.read_json. But when I use cudf.io.json.read_json, it creates cuDFs with size (XXX, 20) or (XXX, 36) or different. It is not consistent.

**Steps/Code to reproduce bug**
```
import cudf 
import pandas as pd
import json
```
```
%%time
file = '/rapids/semantic_scholar/test.json'
df1 = cudf.io.json.read_json(file, lines =True, orient='columns')
```
```
df1.shape
(1, 36)
```

With pandas:
```
%%time
file = '/rapids/semantic_scholar/test.json'
data1 = pd.read_json(file, lines=True, orient='columns
```
```
data1.shape
(1, 19)
```
**Expected behavior**

Expected number of columns and names:
```
data1.columns
Index(['authors', 'doi', 'doiUrl', 'entities', 'id', 'inCitations',
       'journalName', 'journalPages', 'journalVolume', 'outCitations',
       'paperAbstract', 'pdfUrls', 'pmid', 's2PdfUrl', 's2Url', 'sources',
       'title', 'venue', 'year'],
      dtype='object')
```

What I get from cuDF:

```
df1.columns

Index(['entities', 'symptom', 'another symptom', 'disease rate',
       'Neuroscience', 'Neural networks', 'Patients', 'healthcare',
       'journalVolume', 'journalPages', 'pmid', 'year', 'outCitations',
       'f0223f8d1920009d1afccffe2d4129f2211711cf',
       'aaee9e127e63a4ee8baae2bc8a960f4a42afce78',
       '03029e4427cfe66c3da6257979dc2d5b6eb3a0e4',
       'd14434966fd87e94c97ed88938ea3dd5282d7652',
       'd6fa05d67f9a6fc3256d05c81a4c55c472e78b0c',
       'b653b7a6bd4680ff536d91a7a174088cd2f43976', 's2Url', 's2PdfUrl', 'id',
       'authors', 'ids', 'name', 'journalName', 'paperAbstract', 'inCitations',
       '786f4f5b397a0d8aedbe348cc1d3365a3a63b121',
       '9324bd563c8fdaa0d8d49b6120519ef346a90c9a', 'pdfUrls', 'title', 'doi',
       'sources', 'doiUrl', 'venue'],
      dtype='object')
```

**Environment overview (please complete the following information)**
 - Environment location: Rapids-docker & Jupyter notebook
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
```
docker pull rapidsai/rapidsai:latest

nvidia-docker run -it -p 8888:8888 -v /home/mydirectory/:/rapids/semantic/ -v /data_directory/:/rapids/semantic_scholar rapidsai/rapidsai:latest
```

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

Getting the following:

"bash: cd: cu: No such file or directory"

**Additional context**

The test.json files is attached as test.txt 
[test.txt](https://github.com/rapidsai/cudf/files/3418001/test.txt)

**Comment by datametrician** [comment]
@kkraus14 or @mjsamoht could one of you triage this?

**Comment by mjsamoht** [comment]
We'll take a look.

**Comment by mjsamoht** [comment]
The JSON file contains nested data that we currently don't support in cuDF.  Some fields contain arrays of strings or arrays of structures.  There is no way to map this to the cuDF dataframe.

**Comment by mjsamoht** [comment]
I'm changing this to `feature request` and put it to the backlog.  We can revisit once we have a path to output nested data.

**Comment by kkraus14** [comment]
@mjsamoht how hard would it be to detect the nested data and throw an exception accordingly for the time being? Failing loudly would be much better than silently giving garbage data.

**Comment by mjsamoht** [comment]
Based on code inspection it doesn't look like the JSON Lines reader is keeping track of the nested level by counting the square brackets.  Instead, it seems to make the assumption there is no nesting and then uses a simplified and faster parsing.
I was going to confirm this by running the code but was having problems building TOT.  Will try again later.

**Comment by mjsamoht** [comment]
I can confirm that we currently don't parse square brackets ('[', ']').  We would have to parse those and keep track of nesting level to detect nested data, which unfortunately is non-trivial to add.

**Comment by GregoryKimball** [comment]
Closing in favor of #8827
