### ISSUE TITLE
[FEA] Add a dask-cudf README

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2365]
Now that dask-cudf merged into cudf, cudf should have a README page explaining what the module's purpose is, how to install it, etc.

This will be useful on its own, but also for blogs, gists, notebooks etc to link to.

**Comment by randerzander** [comment]
@rajkaramchedu-nvidia can you tackle this?

**Comment by rajkaramchedu-nvidia** [comment]
> 
> 
> @rajkaramchedu-nvidia can you tackle this?

Yes, will get to it sometime today.

**Comment by vyasr** [comment]
@randerzander could you give a little more information on what exactly you'd want to see here? A README specific to `dask_cudf`? We do have build instructions now in https://github.com/rapidsai/cudf/blob/branch-22.08/CONTRIBUTING.md#setting-up-your-build-environment, perhaps those need to be somewhere more public? For most users, who are more interested in installation via conda, what info exactly would you want to see?

**Comment by randerzander** [comment]
Originally this was about cudf users asking how to scale beyond single GPU but not knowing what Dask is, and use "dask-cudf" as an answer being confusing.

I think we've addressed that in several ways now.
