### ISSUE TITLE
[BUG] binops comparisons incorrectly handle nulls as 0

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#2366]
**Describe the bug**
cuDF incorrectly treats `None` as `0`, causing binary op comparisons to return incorrect results.

**Steps/Code to reproduce bug**
```
import pandas as pd
import cudf

from cudf.tests.utils import assert_eq

def append_binops(n, df):
    df['< {}'.format(n)] = df['value'] < n
    df['> {}'.format(n)] = df['value'] > n
    df['<= {}'.format(n)] = df['value'] <= n
    df['>= {}'.format(n)] = df['value'] >= n
    df['== {}'.format(n)] = df['value'] == n
    df['!= {}'.format(n)] = df['value'] != n


src = {'value': [None, -1., 0, 1.]}

df_pandas = pd.DataFrame(src)
df_cudf = cudf.DataFrame(src)

n = 0 # any number will cause assert_eq to fail, `np.nan` will pass.
append_binops(n, df_pandas)
append_binops(n, df_cudf)

print('Comparing None with {}:'.format(n))
print("Pandas")
print(df_pandas)
print()
print("cuDF")
print(df_cudf)
print()

assert_eq(df_pandas, df_cudf)
```

**Expected behavior**
`cuDF` binary op comparisons involving a `None` always result in `False`, with the exception of `!=`, which should return `True`.

**Comment by jrhemstad** [comment]
Can you include the output from your reproducer?

**Comment by cwharris** [comment]
@jrhemstad there's multiple outputs depending on `n`, but here's the one for `0`:

```
Comparing None with 0.0:
Pandas
   value  < 0.0  > 0.0  <= 0.0  >= 0.0  == 0.0  != 0.0
0    NaN  False  False   False   False   False    True
1   -1.0   True  False    True   False   False    True
2    0.0  False  False    True    True    True   False
3    1.0  False   True   False    True   False    True

cuDF
   value  < 0.0  > 0.0  <= 0.0  >= 0.0  == 0.0  != 0.0
0         False  False    True    True    True   False
1   -1.0   True  False    True   False   False    True
2    0.0  False  False    True    True    True   False
3    1.0  False   True   False    True   False    True
```

**Comment by cwharris** [comment]
Wanting to test a theory, I adjusted the input/output of cpp binops for cudf.Column, and ended up with correct results:

```
   ...
    # new code
    is_op_comparison = op in ['lt', 'gt', 'le', 'ge', 'eq', 'ne']
    if is_op_comparison:
        lhs = lhs.fillna(np.nan)
        rhs = rhs.fillna(np.nan)

    # unaltered code
    out = columnops.column_empty(row_count, dtype=out_dtype, masked=masked)
    # Call and fix null_count
    null_count = cpp_binops.apply_op(lhs, rhs, out, op)

    # new code
    if is_op_comparison:1
        out = out.replace(mask=None)
    ...
```

I was also able to remove some erroneous code from a couple of tests
 - `test_operator_func_between_series`
 - `test_operator_func_series_and_scalar`

code I was able to remove:
```
    # if got.dtype == np.bool:
    #     got = got.fillna(True) if func == "ne" else got.fillna(False)
```

I'm going to make `cpp_binops.apply` treat nulls similarly to `nan` in the case of comparison operators.

**Comment by jrhemstad** [comment]
I do not think that the binary operations C++ code should be modified to try and satisfy Pandas' behavior here, because I strongly suspect that SQL/Spark are different. I believe the issue is in the Cython plumbing.

As it is, in the C++ implementation, if you do a comparison with a NULL value, your result will be NULL, not `True` or `False`. 

As such, in the Cython bindings, you should do a `fillna` with the expected result for comparison with a null value.

**Comment by cwharris** [comment]
Just to be clear, _*I am not attempting to introduce Pandas-isms in to the core comparison operators*_ as that would be naive and incorrect. Traditionally, comparisons between unknown / null values will always result in unknown / null / false (except for !=, which will result in unknown / null / true). I believe it is worth implementing at the core operator level because that logic _*is consistent across many data-centric languages*_ including SQL and Spark, but I am happy to discuss the potentially of that not being the case.

I believe you make a valid point, though, that the validity bit _output_ should be included in the comparison operations, because some languages do need to indicate the validity of the result,. whereas Pandas will consider comparison results always valid (afaik).

**Comment by jrhemstad** [comment]
I'd need to be convinced that we need to include the any of the validity bitmasks in the kernels/operators themselves. 

Currently, all of the binary operations simply compute the output bitmask by ANDing the `lhs` and `rhs` bitmask. 

I'm having trouble wrapping my head around why this is insufficient.

**Comment by cwharris** [comment]
@jrhemstad I came to a similar conclusion here: https://github.com/rapidsai/cudf/pull/2391#issuecomment-515156160. You're right that the output bitmask can be determined solely by ANDing the `lhs` and `rhs` bitmasks, which is exactly how it's being done now.

The problem I'm having, though, is the data, not the bitmask. For floating point types, I can `fillna` the `lhs` and `rhs` data with `nan`s, and get the results I need (assuming I remove the output bitmask) because the cpp operators return the correct comparison results for `nan`s. However, non- floating-point types don't have a `nan` equivalent, so I can't `fillna` before the comparisons, as I need `fill == fill` as `false` and `fill != fill` as true (as it is with `nan`s). If I try to `fillna` after the comparisons, I'll get the wrong values, since the result is dependent on the validity of the inputs.

I believe there is a way to handle this without changing cuda code, but I don't think it will be pretty. I will try to do that and post here. Do you have any suggestions on how to handle this scenario?
