### ISSUE TITLE
[DOC] cuDF DataFrame API documentation has gaps for code snippet examples.

### ISSUE THREAD

**Issue by rajkaramchedu-nvidia** [rapidsai/cudf#2371]
For the cuDF DataFrame API reference here: https://rapidsai.github.io/projects/cudf/en/0.8.0/api.html#cudf.dataframe.DataFrame even though there are good code examples showing how to use the API, we can enhance the docs by adding similar code snippets for each method of this API.

**Comment by kkraus14** [comment]
Fixed by #5213
