### ISSUE TITLE
[QST]dataframe rolling regression

### ISSUE THREAD

**Issue by richwu** [rapidsai/cudf#2375]
**What is your question?**
I'm thinking if there is a good way to replace my existing CPU-based DF rolling regression code by cudf.
My code is as below. I'm trying to think the apply_* methods as the possible replacement. However, seems those methods are targeting to the way that each GPU thread handle each row. My goal is how to let the GPU thread handle a frame. Can anyone candle a light of this?

# function def
``` python
def best_fit2(dfr):
    y = dfr.Px.values
    x = dfr.time_tick.values.reshape(-1,1)
    last_seq = dfr.seq.tail(1).values[0]
    linear = sklearn.LinearRegression()
    linear.fit(x,y)
    p_slope, p_intercept = linear.coef_[0], linear.intercept_
    p_angle = np.rad2deg(np.arctan2(price_slope, 1))    
    yy = dfr.o_delta.values
    linear.fit(x,yy)
    o_slope, oi_intercept = linear.coef_[0], linear.intercept_
    o_angle = np.rad2deg(np.arctan2(oi_slope, 1))
    return(last_seq, p_slope, p_angle, p_intercept, o_slope, o_angle, o_intercept)

# code
def RegressionRoll(df, win):
    end = df.shape[0]+1
    win = win
    rng = np.arange(start = win, stop = end, step = 1)
    
    // Subset and store dataframes
    frames = {}
    n = 1

    //Rolling slice the dataframe, and keep them each in a dict
    for i in rng:
        df_temp = df.iloc[:i].tail(win)
        newname = 'df' + str(n)
        frames.update({newname: df_temp})
        n += 1
    print(f'n: {n}')
    
    // distribute the invidual slice to cpu-core for furher processing
    num_cores = multiprocessing.cpu_count() - 5
    inputs = tqdm(list(frames.values()))
    processed_list = Parallel(n_jobs=num_cores)(delayed(best_fit2)(i) for i in inputs)
    
   return processed_list
```
# This is the caller
``` python
rtn = RegressionRoll(df=df_obs, win=120);
df_res = pd.DataFrame(rtn, columns =['seq', 'price_slope', 'price_angle', 'price_intercept','oi_slope', 'oi_angle', 'oi_intercept'])
df_res.head(30)
````
# result
seq     |      p_slope | p_angle     | p_intercept     | o_slope     | o_angle       | o_intercept
15119 | 0.0065768 | 0.3768201 | 2139.0836777 | 0.2529342 | 14.1943636 | -32461.5495868
15120 | 0.0059744 | 0.3423023 | 2139.1153581 | 0.2799500 | 15.6395897 | -32462.9903581
15121 | 0.0053754 | 0.3079832 | 2139.1468320 | 0.3068269 | 17.0574202 | -32464.4228650
15122 | 0.0049865 | 0.2857006 | 2139.1699725 | 0.3343913 | 18.4894856 | -32465.8796143
15123 | 0.0045975 | 0.2634179 | 2139.1931129 | 0.3626293 | 19.9321308 | -32467.3597796
15124 | 0.0040020 | 0.2292973 | 2139.2243802 | 0.3907007 | 21.3406244 | -32468.8300275
15125 | 0.0034100 | 0.1953755 | 2139.2554408 | 0.4194319 | 22.7547314 | -32470.3228650
15126 | 0.0028214 | 0.1616525 | 2139.2862948 | 0.4479825 | 24.1315445 | -32471.8049587
15127 | 0.0022363 | 0.1281284 | 2139.3169421 | 0.4654282 | 24.9585945 | -32472.4096419
15128 | 0.0016546 | 0.0948032 | 2139.3473829 | 0.4825127 | 25.7578983 | -32472.9928375
15129 | 0.0010765 | 0.0616768 | 2139.3776171 | 0.4992361 | 26.5300240 | -32473.5545455
15130 | 0.0002917 | 0.0167124 | 2139.4243113 | 0.5155983 | 27.2755551 | -32474.0947658
15131 | 0.0001302 | 0.0074609 | 2139.4380854 | 0.5332523 | 28.0688725 | -32474.678512

**Comment by kkraus14** [comment]
Stale closing.
