### ISSUE TITLE
[FEA] DataFrame `shift()`

### ISSUE THREAD

**Issue by darogross** [rapidsai/cudf#2390]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]

shift() and dropna() for dataframes

These functions are required for most time series analytics since the basic element is the row vector. It represents a state in time. Dropna() allows for real world dirty data.

**Describe the solution you'd like**
like pandas

**Describe alternatives you've considered**
alternatives: add, remove, update rows by index

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by taureandyernv** [comment]
Being this to your attention as i know you and @darogross discussed this, @kkraus14 , He wants a pandas-like way to shift() for dataframes- not just series.

**Comment by kkraus14** [comment]
dropna was implemented in #2196

**Comment by cwharris** [comment]
Consolidating to #2434
