### ISSUE TITLE
How about cudf running on ray?  

### ISSUE THREAD

**Issue by backyes** [rapidsai/cudf#2393]
Check ray: 
https://www.usenix.org/system/files/osdi18-moritz.pdf
https://pdfs.semanticscholar.org/0e8f/5cd8d8dbbe4a55427e90ed35977e238b1eed.pdf
https://github.com/modin-project/modin 

https://github.com/ray-project/ray

**Comment by tgaddair** [comment]
+1, combining [Dask on Ray](https://docs.ray.io/en/master/dask-on-ray.html) with dask_cudf would be amazing.

cc @clarkzinzow

**Comment by clarkzinzow** [comment]
Does this not currently work out-of-the-box?

**Comment by vyasr** [comment]
cudf + Ray works already. However, the limitation mentioned above is still present: Ray's object store does not support GPU buffers. There is at present no impetus to work on this, so I'm closing this as a wontfix. If there is future interest we can reopen the issue.
