### ISSUE TITLE
[BUG] [Dask-cudf] Tracking issues while using mainline Dask `set_index`

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2395]
I modified the code (removed dask-cudf set_index) to use the mainline dask `set_index` method. 

**Describe the bug**
Dask seems to use the `values` property of a Series. Something that cudf lacks. Not sure whether the right approach is to modify dask to use another property (to_gpu_array maybe? Not sure) or modify cudf to add a `values` property.

**Steps/Code to reproduce bug**
```
df = cudf.DataFrame({'a':[1,2,3],'b':[4,5,6]})
ddf = dask_cudf.from_cudf(df,1)
ddf.set_index('a') # Using dask set_index

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/dataframe/core.py", line 3457, in set_index
    **kwargs
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/dataframe/shuffle.py", line 74, in set_index
    divisions, sizes, mins, maxes, optimize_graph=False
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/threaded.py", line 82, in get
    **kwargs
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/local.py", line 491, in get_async
    raise_exception(exc, tb)
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/compatibility.py", line 130, in reraise
    raise exc
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/local.py", line 233, in execute_task
    result = _execute_task(task, data)
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/home/nfs/adattagupta/conda/envs/cudf_dev1/lib/python3.7/site-packages/dask/dataframe/partitionquantiles.py", line 413, in percentiles_summary
    data = df.values
AttributeError: 'Series' object has no attribute 'values'
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: From source built off of https://github.com/rapidsai/cudf/pull/2156 and with dask_cudf `set_index` removed.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
print_env.sh: 10: [: true: unexpected operator
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux dt03 4.4.0-154-generic #181-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Jul 25 10:31:35 2019       
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
     | N/A   46C    P0    28W /  70W |    225MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla T4            Off  | 00000000:5E:00.0 Off |                    0 |
     | N/A   32C    P8     9W /  70W |     10MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
     | N/A   31C    P8    10W /  70W |     10MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla T4            Off  | 00000000:D8:00.0 Off |                    0 |
     | N/A   32C    P8     9W /  70W |     10MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0    190509      C   /opt/conda/envs/rapids/bin/python            215MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                64
     On-line CPU(s) list:   0-63
     Thread(s) per core:    2
     Core(s) per socket:    16
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
     Stepping:              4
     CPU MHz:               2095.076
     BogoMIPS:              4191.35
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              22528K
     NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
     NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku md_clear flush_l1d
     
     ***CMake***
     /home/nfs/adattagupta/conda/envs/cudf_dev1/bin/cmake
     cmake version 3.14.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-10.0/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /home/nfs/adattagupta/conda/envs/cudf_dev1/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/nfs/adattagupta/conda/envs/cudf_dev1/bin:/home/nfs/adattagupta/conda/condabin:/usr/local/cuda-10.0/bin:/home/nfs/adattagupta/conda/bin:/home/nfs/adattagupta/bin:/home/nfs/adattagupta/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.0/lib64:
     NUMBAPRO_NVVM                   : 
     NUMBAPRO_LIBDEVICE              : 
     CONDA_PREFIX                    : /home/nfs/adattagupta/conda/envs/cudf_dev1
     PYTHON_PATH                     : 
     
     ***conda packages***
     conda is /home/nfs/adattagupta/conda/condabin/conda
     /home/nfs/adattagupta/conda/condabin/conda
     # packages in environment at /home/nfs/adattagupta/conda/envs/cudf_dev1:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main  
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
     asn1crypto                0.24.0                py37_1003    conda-forge
     aspy.yaml                 1.3.0                      py_0    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     aws-sam-translator        1.11.0                     py_1    conda-forge
     aws-xray-sdk              0.95                       py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.tempfile        1.0                        py_0    conda-forge
     backports.weakref         1.0.post1             py37_1000    conda-forge
     black                     19.3b0                     py_0    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.2.0                    py37_0    conda-forge
     boost                     1.68.0          py37h8619c78_1001    conda-forge
     boost-cpp                 1.68.0            h11c811c_1000    conda-forge
     boto                      2.49.0                     py_0    conda-forge
     boto3                     1.9.193                    py_0    conda-forge
     botocore                  1.12.193                   py_0    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     ca-certificates           2019.5.15                     0  
     cached-property           1.5.1                      py_0    conda-forge
     certifi                   2019.6.16                py37_0  
     cffi                      1.12.3           py37h8022711_0    conda-forge
     cfgv                      2.0.1                      py_0    conda-forge
     cfn-lint                  0.21.2                     py_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                      pypi_0    pypi
     cloudpickle               1.2.1                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     commonmark                0.9.0                      py_0    conda-forge
     cookies                   2.2.1                      py_0    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               10.0.130                      0  
     cudf                      0.8.0a1+2237.g703a0b0.dirty          pypi_0    pypi
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cython                    0.29.12          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.1.0+15.gd0ee320          pypi_0    pypi
     dask-core                 2.1.0                      py_0    conda-forge
     dask-cudf                 0.8.0a1+2407.g95ca969.dirty          pypi_0    pypi
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     distributed               2.1.0+16.g586ead9          pypi_0    pypi
     docker-py                 4.0.2                    py37_0    conda-forge
     docker-pycreds            0.4.0                      py_0    conda-forge
     docutils                  0.14                  py37_1001    conda-forge
     ecdsa                     0.13                       py_0    conda-forge
     editdistance              0.5.3            py37hf484d3e_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     flake8                    3.7.7                    py37_0    conda-forge
     flask                     1.1.1                      py_0    conda-forge
     freetype                  2.10.0               he983fc9_0    conda-forge
     fsspec                    0.3.4                      py_0    conda-forge
     future                    0.17.1                py37_1000    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     httpretty                 0.9.6                      py_0    conda-forge
     icu                       58.2              hf484d3e_1000    conda-forge
     identify                  1.4.5                      py_0    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        0.18                     py37_0    conda-forge
     ipykernel                 5.1.1            py37h5ca1d4c_0    conda-forge
     ipython                   7.6.1            py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     4.3.21                   py37_0    conda-forge
     itsdangerous              1.1.0                      py_0    conda-forge
     jedi                      0.14.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     jmespath                  0.9.4                      py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     jsondiff                  1.1.2                      py_0    conda-forge
     jsonpatch                 1.23                       py_0    conda-forge
     jsonpickle                1.2                        py_0    conda-forge
     jsonpointer               2.0                        py_0    conda-forge
     jsonschema                3.0.0a3               py37_1000    conda-forge
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libblas                   3.8.0               10_openblas    conda-forge
     libcblas                  3.8.0               10_openblas    conda-forge
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20181209         hc058e9b_0  
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0  
     libgfortran-ng            7.3.0                hdf63c60_0  
     liblapack                 3.8.0               10_openblas    conda-forge
     libnvstrings              0.9.0a1             cuda10.0_37    rapidsai-nightly
     libopenblas               0.3.6                h6e990d7_4    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
     librmm                    0.9.0a1              cuda10.0_2    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0  
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuv                     1.30.1               h516909a_0    conda-forge
     llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  2.6.11                   pypi_0    pypi
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     mock                      3.0.5                    py37_0    conda-forge
     more-itertools            7.1.0                      py_0    conda-forge
     moto                      1.3.8                      py_1    conda-forge
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     nbconvert                 5.5.0                      py_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.4.2                      py_0    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nodeenv                   1.3.3                      py_0    conda-forge
     notebook                  6.0.0                    py37_0    conda-forge
     numba                     0.44.1           py37hb3f55d8_0    conda-forge
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     nvstrings                 0.9.0a1                 py37_37    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.6                h6e990d7_4    conda-forge
     openssl                   1.1.1c               h7b6447c_1  
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.24.2           py37he6710b0_0  
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         4    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.1.0            py37he7afcd5_0    conda-forge
     pip                       19.1.1                   py37_0    conda-forge
     pluggy                    0.12.0                     py_0    conda-forge
     pre_commit                1.17.0                   py37_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.12.1           py37hbbcf98d_0    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pycryptodome              3.8.2            py37he80fd80_0    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.1                      py_0    conda-forge
     pyrsistent                0.15.3           py37h516909a_0    conda-forge
     pysocks                   1.7.0                    py37_0    conda-forge
     pytest                    5.0.1                    py37_1    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     python-jose               2.0.2                      py_0    conda-forge
     pytz                      2019.1                     py_0    conda-forge
     pyyaml                    5.1.1            py37h516909a_0    conda-forge
     pyzmq                     18.0.2           py37h1768529_2    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.5.0                      py_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     responses                 0.9.0                      py_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.9.0a1                  py37_2    rapidsai-nightly
     s3fs                      0.3.0                      py_0    conda-forge
     s3transfer                0.2.1                    py37_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.0.1                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snowballstemmer           1.9.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.1.2                      py_0    conda-forge
     sphinx-markdown-tables    0.0.9                    pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.29.0               hcee41ef_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
     tk                        8.6.9             hed695b0_1002    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.2                 py37_1000    conda-forge
     urllib3                   1.25.3                   py37_0    conda-forge
     virtualenv                16.6.2                   py37_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websocket-client          0.56.0                   py37_0    conda-forge
     werkzeug                  0.15.5                     py_0    conda-forge
     wheel                     0.33.4                   py37_0    conda-forge
     wrapt                     1.11.2           py37h516909a_0    conda-forge
     xmltodict                 0.12.0                     py_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                    pypi_0    pypi
     zipp                      0.5.1                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1005    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

**Comment by ayushdg** [comment]
Just came across #2272. Which has discussions about a plan for sort_values/set_index

**Comment by rjzamora** [comment]
Looks like we are running into similar questions :)

**Comment by ayushdg** [comment]
Closing. @rjzamora prs enables this to work with the mainline dask methods.
