### ISSUE TITLE
[FEA] Create RAII object for NVTX ranges

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2397]
**Is your feature request related to a problem? Please describe.**

Currently, in order to add NVTX ranges to code in libcudf requires using the `PUSH_RANGE`/`POP_RANGE` APIs: https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/src/utilities/nvtx/nvtx_utils.h#L25

**Describe the solution you'd like**
It would be far more convenient to have a RAII wrapper that calls `PUSH_RANGE` in the constructor and `POP_RANGE` in the destructor. This will also guarantee that a matching `POP_RANGE` will always be called, even in the event of an early return.

**Comment by harrism** [comment]
Will this make it trickier to end a range before it goes out of scope?  I guess you can always put in an artificial scope (`{}`), but could also give this RAII object a `.pop()` method?

**Comment by jrhemstad** [comment]
An artificial scope is a common practice when using something like [`std::lock_guard`](https://en.cppreference.com/w/cpp/thread/lock_guard)

You could also explicitly invoke the destructor:
```
nvtx_range r;
...
r.~nvtx_range();
```

But I'm not opposed to an explicit function to end the range.
