### ISSUE TITLE
Request: iloc() for dataframes

### ISSUE THREAD

**Issue by darogross** [rapidsai/cudf#2409]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by kkraus14** [comment]
@darogross DataFrame `.iloc()` is supported today. Do you have a code snippet that reproduces the issue you're seeing?

**Comment by darogross** [comment]
*I will have to update my software. *

*Daro Gross*

*Mobile: 408.348.9110*
*Skype: ncfproject*
