### ISSUE TITLE
[BUG] to_csv fails silently when no filename is provided

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2410]
**Describe the bug**
Calling `dataframe.to_csv()` with no filename runs successfully but saves/returns nothing.
 
**Steps/Code to reproduce bug**
```
import cudf
df = cudf.DataFrame({'a':[1,2,3]})
df.to_csv()
```

**Expected behavior**
In these situations pandas returns the csv as a string.
Until #2408 is implemented `to_csv` should throw an error along the lines of " filename not provided"

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   Latest nightly

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by harrism** [comment]
Simple bug fix, prioritizing for 0.14.

**Comment by kkraus14** [comment]
@rgsl888prabhu can you tackle this when you get a chance?

Thanks @harrism :)
