### ISSUE TITLE
[FEA] extra features to match spark's rolling winodw support

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#2414]
I am not totally sure exactly what will be needed in the end, but I am hoping to start a discussion on what is the right way to get the same functionality that Spark offers.  I am hoping that most of what we need is already in place in rolling.hpp, but some things I don't know off the top of my head how to make it work.  For the others I think we may be missing some functionality to be able to setup window_col, min_periods_col, and forward_window_col.

Spark offers a windowing API where you get three options. Partition by, Order by, and range.

Range specifies how many entries before and how many after will be in the window. I believe that this is the same as window/window_col and forward_window/forward_window_col receptively.

Order by gives a set of columns to sort the data by.  I think we can ignore this because the sorting will happen outside of the operation.

Partition by is the interesting one.  This one essentially does the equivalent of a group_by, and wants to do the rolling operation within each group.

I think I can make this work by calculating the proper window_col and forward_window_col, but I am not sure of the best way to do that.

When using an order by or a partition by the data will have been sorted before hand, at least by the partition keys, so I need the ability to find inside a table where the group boundaries are.  I don't think there is anything to do that right now.

I then need to be able to take those boundaries and for each entry in the range put in something where the window_col value never goes below the start of the group, and the forward_window_col never goes beyond the end of the group.  I can picture in my head how to write a simple kernel to do this, but I don't know of any existing cudf functions to do it.

Any help is appreciated.

**Comment by jrhemstad** [comment]
If "partition by" is just a groupby, how about just call a groupby?

**Comment by jrhemstad** [comment]
> so I need the ability to find inside a table where the group boundaries are

Something like this:
https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/groupby.hpp#L173

or this:
https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/groupby.hpp#L198
?

**Comment by revans2** [comment]
@jrhemstad thanks those APIs look exactly like what I need.

The only remaining question is how to get the result of gdf_unique_indices exploded into window_col and forward_window_col.

Like I said I can see kind of how I could write a custom cuda kernel to do it, and I am not expert in this.  Is doing this kernel something that should be a part of CUDF proper, or is it something that I should look at doing in the spark plugin?

**Comment by jrhemstad** [comment]
I'm a bit unclear on what the ultimate goal you're trying to accomplish. 

So you mentioned 3 things:
1. orderby (which we can ignore?)
2. range (which is already supported by the existing rolling API?)
3. partitionby (effectively does a groupby?)

So it sounds like 3 is the only thing that is unresolved. 

However, could 3 not be accomplished by calling libcudf's existing groupby API?

**Comment by revans2** [comment]
OK so let me give you a quick example.

There is an example at https://xinhstechblog.blogspot.com/2016/04/spark-window-functions-for-dataframes.html that is fairly good.

The data is

```
("Alice", "2016-05-01", 50.00),
("Alice", "2016-05-03", 45.00),
("Alice", "2016-05-04", 55.00),
("Bob", "2016-05-01", 25.00),
("Bob", "2016-05-04", 29.00),
("Bob", "2016-05-06", 27.00)
```
They are doing a moving average partitioned by name and ordered by date, with a range that is one on either side of the row we are looking at.  The exact details of the aggregate don't really matter though.

The order by would run on name and date (No change to the data shown).

We would then run the `gdf_unique_indices` to get back the indices. (I am guessing at the output form the docs, but it looks like it would be).

```
0
3
```

I now need to translate this into something for `window_col` and `window_col_froward` that gives me at most 1 on either side, for each row, but also respects the groups.

window_col
```
0,
1,
1,
0,
1,
1,
```

window_col_forward
```
1,
1,
0,
1,
1,
0
```

This is more difficult if instead of using a range of -1 to 1, it was the entire group, in that case I would need something like.
window_col
```
0,
1,
2,
0,
1,
2
```

window_col_forward
```
2,
1,
0,
2,
1,
0
```

This is the part I am stuck on.

**Comment by jrhemstad** [comment]
I see, so it's not just simply a groupby. It's a stencil that respects group boundaries?

**Comment by revans2** [comment]
Yes, sorry about the delay I was out on vacation.

**Comment by abellina** [comment]
In addition to the case outlined above, here are some more examples on the types of ranges that Spark supports. The main question is what functions in cudf we can use to achieve the partitioned nature of the rolling function, and if you have ideas on the date interval part.

## Different types of ranges

### Date interval ranges

Used to gate what rows are part of the window aggregate, based on some interval (days, months, years, etc).

```
sum(count) over (
  partition by partitionId order by cast(date as timestamp) asc 
  range between interval 3 days preceding and interval 1 days preceding
)
```
### Bounded row ranges

Used for the case where we want to say `ROW BETWEEN 5 PRECEDING AND 2 FOLLOWING`, this is analogous to `window_col` and `window_col_forward` columns. 
```
sum(count) over (
  partition by partitionId order by cast(date as timestamp) asc 
  rows between 1 preceding and 1 following
)
```
### Unbounded ranges
When we want all rows in the partition to be candidates, so the window is infinite in one direction (`PRECEDING` in this case, but could be `FOLLOWING` as well).
```  
lag(date) over (
  partition by partitionId order by cast(date as timestamp) asc
)
```
```
row_number() over (
  partition by partitionId order by cast(date as timestamp) asc
)
```

### Example

```
select *
from (
    select partitionId,  date, count, 
    lag(date) over (
        partition by partitionId order by cast(date as timestamp) asc
    ) as prev_date, 
    row_number() over (
        partition by partitionId order by cast(date as timestamp) asc 
    ) as part_row_number,
    sum(count) over (
        partition by partitionId order by cast(date as timestamp) asc 
        rows between 1 preceding and 1 following
    ) as rolling_count,
    sum(count) over (
        partition by partitionId order by cast(date as timestamp) asc 
        range between interval 1 days preceding and interval 1 days preceding) as sum_1_days, 
    sum(count) over (
        partition by partitionId order by cast(date as timestamp) asc 
        range between interval 2 days preceding and interval 1 days preceding) as sum_2_days, 
    sum(count) over (
        partition by partitionId order by cast(date as timestamp) asc 
        range between interval 3 days preceding and interval 1 days preceding) as sum_3_days
    from window_test order by partitionId, date, part_row_number
)
```

Output:

```
|partitionId|      date|count| prev_date|part_row_number|rolling_count|sum_1_days|sum_2_days|sum_3_days|
+-----------+----------+-----+----------+---------------+-------------+----------+----------+----------+
|          1|2019-10-01|    1|      null|              1|            2|      null|      null|      null|
|          1|2019-10-02|    1|2019-10-01|              2|            3|         1|         1|         1|
|          1|2019-10-03|    1|2019-10-02|              3|            3|         1|         2|         2|
|          1|2019-10-04|    1|2019-10-03|              4|            2|         1|         2|         3|
|          2|2019-10-01|    1|      null|              1|            2|      null|      null|      null|
|          2|2019-10-01|    1|2019-10-01|              2|            3|      null|      null|      null|
|          2|2019-10-04|    1|2019-10-01|              3|            2|      null|      null|         2|
|          3|2019-10-01|    1|      null|              1|            1|      null|      null|      null|
+-----------+----------+-----+----------+---------------+-------------+----------+----------+----------+
```

**Comment by revans2** [comment]
This looks like it was mostly finished by #4363
