### ISSUE TITLE
[FEA] Change default for read_csv to read through host memory

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2421]
Currently there are two paths for `dask_cudf.read_csv`

1.  Read directly from device memory using code in the dask_cudf package.  This is fast.
2.  Read from host memory and then call the `cudf.read_csv` function on those host-side bytes as appropriate.  We use this path if the user specifies any protocol like `s3://` or `file://`. This is pretty fast, but is bound by disk->host->device transfer speeds, which are about the same speed as parsing.

Today both systems seem to work pretty well.  Most users are happy.  However, of the issues that we do receive (about one every week or two) almost all are from users using path one, and their issues are resolved by moving to path two when we tell them to prepend `"file://"` to their path.  These tend to show up when users are using a variety of complex keyword arguments that interact oddly with slicing up bytes (skiprows, header, ...).  

Some possible solutions:

1.   Reimplement all of the logic in dask.dataframe in dask-cudf (I personally would like to shoot this down)
2.  Implement a GPU [file system](https://filesystem-spec.readthedocs.io) so that we can use the mainline dask.dataframe algorithms with GPU data (cc @martindurant).  This would be a moderately large endeavor, but might be useful in other efforts too.
3.  Change the default from using device memory (path one) to using host memory (path two).  This is simple and should solve most problems at the cost of slower performance (but still quite fast)
4.  Change the default from using device memory to host memory *if* the user strays out of a whitelisted set of known safe keywords

**Comment by martindurant** [comment]
> Implement a GPU file system so that we can use the mainline dask.dataframe algorithms with GPU data

This does certainly have a good dose of "be explicit" about it. Writing such classes is pretty easy, you don't need to implement all the methods.

**Comment by kkraus14** [comment]
For clarification:

1) Does not read directly from device memory, it typically memmaps the file at the C++ level and then processes the data from there. It bypasses Python memory management almost entirely though which is likely where the perf improvements come from. I believe we're mostly using Arrow C++ here at this point to accomplish this.

**Comment by mjsamoht** [comment]
For most cuIO readers we support two types of input at C++ layer:
1. file name
2. host memory pointer

In case of file name we will open the file and then use `mmap()` to memory map the file.

For Parquet reader we also support a third input type, which is `arrow::io::randomaccessfile`.

**Comment by martindurant** [comment]
It seems to me that the simplest CU local file system implementation (within the fspec structure) might subclass from [`LocalFileSystem`](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.local.LocalFileSystem) , but override the `open` method to provide exactly what you need - maybe just pass on the filename. 

(as an aside, most implementations of files and indeed the OpenFile class, which is a lazy opener, support `os.fspath`, which means you could not override anything at all, just extract the path from the object that gets passed)

Any file systems reading from remote can be used to provide `bytes`, which is what Dask normally does now.

**Comment by beckernick** [comment]
@ayushdg @rjzamora given IO changes in the past two years, is this issue still relevant?

**Comment by rjzamora** [comment]
>given IO changes in the past two years, is this issue still relevant?

The feature request is still somewhat relevant (there are still two distinct code paths, depending on the data source). With that said, my impression is that the local-FS code path is significantly more stable now, so there is less of a motivation to move entirely to `dask.dataframe`.

I am always happy to leverage upstream code. So I will support anyone who wants to take the time to work out a way to push the necessary functionailty into dask. However, I also think it's safe to close this issue for now (since it is both old and low-priority). If anyone does decide to re-prioritize a unified code path, feel free to re-open :)
