### ISSUE TITLE
[PROPOSAL] Combine "dask" and "dask-cudf" issue labels

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2427]
When looking for previously filed issues related to dask and dask_cudf, it took time to realize that some were labeled "dask" and some were labeled "dask-cudf".

In the interest of simplifying bug reporting and increasing visibility of related issues, can we eliminate the "dask-cudf" label and just use "dask"?

Edit:
I realize the "dask-cudf" label is for issues migrated from the now archived rapidsai/dask-cudf repo, but users (at least me) are still able to tag issues as "dask-cudf" manually.

**Comment by kkraus14** [comment]
Took a pass through and effectively did this, so closing.
