### ISSUE TITLE
[FEA] Add an `n-ary` transform 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2428]
**Is your feature request related to a problem? Please describe.**

Building off of https://github.com/rapidsai/cudf/issues/1980 which defines a _unary_ transform (i.e., operates only on single elements), it would be nice to have an _n-ary_ transform that can operate on the rows of `n` columns. 

This has multiple uses, including supporting row-level operations like what was discussed here:  https://github.com/rapidsai/cudf/pull/2416

**Describe the solution you'd like**

Implement a `cudf::transform` that operates on a `cudf::table` of `n` columns and accepts a PTX string containing a UDF with `n` inputs, then applies that function to each row of the table. 

I think there's probably two versions of the function, which vary in the outputs:
1. Output is a single column
2. Output is n-columns

**Comment by beckernick** [comment]
@harrism , would be interested in your thoughts on this. A potential goal would be to leverage something like this to support row-wise reduction/scan operations.

**Comment by harrism** [comment]
My thought is that as long as we constrain what the UDF can do, e.g. similar to what it can do for `transform`, then it's very doable.

**Comment by vyasr** [comment]
This is now possible using numba kernels at the cuDF Python level. There is at present no specific need for this in libcudf (e.g. using jitify). If that changes, we can reopen this in the future.
