### ISSUE TITLE
[FEA] Export the __cuda_array_interface__ attribute

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2433]
It looks like currently cudf.Series objects don't implement the `__cuda_array_interface__` protocol.  

```python
In [1]: import cudf

In [2]: cudf.Series([1, 2, 3]).__cuda_array_interface__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-ed3281dc52bd> in <module>
----> 1 cudf.Series([1, 2, 3]).__cuda_array_interface__

AttributeError: 'Series' object has no attribute '__cuda_array_interface__'
```

This makes it quite slow to convert cudf objects into other array libraries.  I suspect that this is going through some very slow path currently.

```python
In [1]: import cudf, cupy, numpy

In [2]: s = cudf.Series(numpy.arange(10000))

In [3]: %time cupy.asarray(s)
CPU times: user 2.79 s, sys: 28 ms, total: 2.82 s
Wall time: 2.82 s
Out[3]: array([   0,    1,    2, ..., 9997, 9998, 9999])
```

I suspect that this is currently due to a lack of missing value support in the `__cuda_array_interface__`.  If so, is there anything that we can do in the meantime?  Perhaps we might optionally provide `__cuda_array_interface__` attribute *if* the missing values mask is empty?

**Comment by kkraus14** [comment]
@mrocklin As of Numba 0.45 there's actually a mask attribute in `__cuda_array_interface__` (https://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html) so we can nicely expose this including masks but Numba will throw an exception if given a mask, CuPy will likely do the same.

**Comment by mrocklin** [comment]
When we don't have a mask we should be ok though?
