### ISSUE TITLE
[FEA] libcuDF Shift for Series and DataFrames

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2434]
As a user of cuDF through any language bindings, I'd like to be able to shift Series and DataFrames `n` periods forward or backward, while effectively handling null values. 

`shift` exists in cuDF Python currently, but there are real limitations. Implementing this in libcuDF may improve performance, improve null handling, and eliminate the time spent JIT compiling. A libcuDF implementation will also provide this functionality to Python, Java, and any other language bindings.

See discussion in #1285 for more information.

**Comment by harrism** [comment]
C++ implemented by #3662 but I believe Cython needs to be written. @cwharris are you able to do this?

**Comment by harrism** [comment]
Also note that strings support is not implemented yet. That is tracked by https://github.com/rapidsai/cudf/issues/3915
