### ISSUE TITLE
[FEA] dayoftheweek function in datetime 

### ISSUE THREAD

**Issue by Nanthini10** [rapidsai/cudf#2435]
**Is your feature request related to a problem? Please describe.**
It would be useful to have a function to find the day of the week instead of writing a udf to do the same.

**Describe the solution you'd like**
The function performs the calculations to find the day of the week and returns a number indicating the day of the week. 

**Describe alternatives you've considered**
We could write an udf for solving this problem and use applyrows, but it is quite slow.

**Additional context**
Here's the pandas version: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DatetimeIndex.dayofweek.html

**Comment by randerzander** [comment]
@kkraus14 not sure if this needs libcudf or not.

This would let us do feature engineering much faster vs the apply_rows kernel that we use today.

**Comment by brandon-b-miller** [comment]
closed in https://github.com/rapidsai/cudf/pull/2814.
