### ISSUE TITLE
[FEA] is_monotonic properties should use libcudf `is_sorted` functions

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#2436]
See #2380 for implementation

**Comment by rgsl888prabhu** [comment]
@kkraus14 
If there is `None` in series in pandas, it always returns `False` for both  `is_monotonic_increasing` and `is_monotonic_decreasing` for all types. Should we follow same ?

**Comment by cwharris** [comment]
@rgsl888prabhu Pandas supports nulls/None only via NaN/NaT, which is not exactly the same. We support both nulls and NaNs simultaneously. I think it makes sense for Pandas to return False for both `is_monotonic_increasing` and `is_monotonic_decreasing`. I can see why we'd want to follow suit, but I wonder how often consumers want to simply _ignore_ nulls/nans/nats.
