### ISSUE TITLE
[FEA] Consider using nullable integer types for Pandas

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2439]
From latest rapidsai-nightly cudf conda package:
```
import cudf
cudf.Series([0, 1, None]).to_pandas()
```
```
0    0
1    1
2   -1
dtype: int64
```

```
import pandas as pd
pd.Series([0, 1, None])
```
```
0    0.0
1    1.0
2    NaN
dtype: float64
```

For what it's worth, I stumbled over this while inspecting output from cudf.DataFrame.merge with how='left'. So if you have a DataFrame will null values, and you pass results back to a downstream system via Pandas, you may get surprising results.

**Comment by ayushdg** [comment]
I guess the fundamental issue is pandas does not allow nulls in their `int32` and `int64` types. Creating a df with nulls automatically typecasts to float with `np.nan` as the nulls.
Cudf has the capability to handle nulls with int dtypes. 
The `to_pandas` method just fills the nulls with `-1` for an int column (which probably can be misleading when going back to pandas).
Modying `to_pandas` to upcast to float and fill with np.nan should be possible if that needed.

**Comment by shwina** [comment]
What about Pandas' nullable int type (now that we use a new enough version of Pandas):

https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html

**Comment by shwina** [comment]
Would it be more useful to return a Pandas object with a nullable int type, @randerzander, or upcast?

**Comment by ayushdg** [comment]
@shwina I didn't realize that pandas added this 😀  (I was still stuck in 0.23.4 land) This might be a better approach to handle null int columns while doing `to_pandas`.

**Comment by randerzander** [comment]
nullable int seems like an improvement (slightly safer for identifiers) over a forced cast to float. Until filing this issue, I wasn't aware pandas even had the cast behavior, so I doubt it many users rely on it.

If we go with nullable int, does that mean ``` cudf.from_pandas(df.to_pandas())``` would preserve the int type? If so, that's nice, and would benefit users who go to and from Pandas as a workaround.

However, most comments I hear about to_pandas are related to slowness. If returning a nullable int is significantly slower than upcasting, I think we should default to upcasting.

**Comment by shwina** [comment]
Upsides:
* The round trip you mentioned would preserve the `int` type
* We can test more directly with Pandas and reduce the uncertainty of null behaviour for users

Downsides:
* I don't know if Pandas supports all the same operations on nullable ints as with plain ints
* Might surprise some users who haven't used them before

I'm not sure if it would be any faster or slower but worth exploring

**Comment by kkraus14** [comment]
> Upsides:
> 
> * The round trip you mentioned would preserve the `int` type
> * We can test more directly with Pandas and reduce the uncertainty of null behaviour for users
> 
> Downsides:
> 
> * I don't know if Pandas supports all the same operations on nullable ints as with plain ints
> * Might surprise some users who haven't used them before
> 
> I'm not sure if it would be any faster or slower but worth exploring

It is definitely slower because you have an additional boolean array alongside the data array. Additionally, from some testing I've done nullable integers are still very young in Pandas where they're not fully usable yet.

I'd suggest we keep the current behavior and re-evaluate once Pandas releases 1.0.

**Comment by davidwendt** [comment]
I tried this today on branch-21.12 with Pandas 1.2.5.

```
>>> import cudf
>>> import pandas as pd
>>> cudf.Series([0, 1, None]).to_pandas()
0    0.0
1    1.0
2    NaN
dtype: float64
>>> pd.Series([0, 1, None])
0    0.0
1    1.0
2    NaN
dtype: float64
```

Perhaps this issue can be closed?

**Comment by thomcom** [comment]
Those are float types, not int. I am not sure if int64 has NaN yet.

**Comment by davidwendt** [comment]
How about this?
```
>>> cudf.Series([0, 1, None], dtype=np.int64).to_pandas(nullable=True)
0       0
1       1
2    <NA>
dtype: Int64
>>> 

```

I'm probably out of my depth here.

**Comment by shwina** [comment]
> Would it be more useful to return a Pandas object with a nullable int type, @randerzander, or upcast?

Looks like we went with the upcasting route here. We previously experimented briefly with returning nullable types instead, but that led to some user frustration.

I also feel that this can be closed out for now if  @randerzander agrees.

**Comment by beckernick** [comment]
> > Would it be more useful to return a Pandas object with a nullable int type, @randerzander, or upcast?
> 
> Looks like we went with the upcasting route here. We previously experimented briefly with returning nullable types instead, but that led to some user frustration.
> 
> I also feel that this can be closed out for now if @randerzander agrees.

Agreed. Going to close this issue, but please feel free to reopen it @randerzander
