### ISSUE TITLE
[BUG] fillna behavior is functioning incorrectly

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#2440]
**Describe the bug**
`fillna` seems to be filling the values in Series incorrectly. Please see the below simplified example:

**Steps/Code to reproduce bug**
```python
import cudf
print(cudf.Series([1,2,None]*32).fillna(-1))
0     1
1     2
2    -1
3     1
4     2
5    -1
6     1
7     2
8     0
9     1
[86 more rows]
dtype: int64
```
If you see the 8th record, it shouldn't ideally be a 0..Expected behavior is that 8th record should have been filled with -1 instead of 0. Not just at this index there seems to be other indices filled with 0's too if you see the `value_counts`:
```
print(cudf.Series([1,2,None]*32).fillna(-1).value_counts())
-1    32
1    24
2    24
0    16
dtype: int32
```
Ideally we should be having the count of -1,1,2 as 32 as below.

**Expected behavior**
```python
import pandas as pd
print(pd.Series([1,2,None]*32).fillna(-1).value_counts())
-1.0    32
 2.0    32
 1.0    32
dtype: int64
```

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source

**Comment by kkraus14** [comment]
I can't reproduce this

**Comment by galipremsagar** [comment]
This seems to be an issue with changing mask dtype. Had a discussion offline with @kkraus14 and closing this issue for now.
