### ISSUE TITLE
[FEA] Dot Product

### ISSUE THREAD

**Issue by ritchieng** [rapidsai/cudf#2448]
Seems like there's no easy way for dot product can this be implemented?

Pandas equivalent: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dot.html

**Comment by jrhemstad** [comment]
We should ultimately have this natively implemented in libcudf, but in the short term, this would be trivial to provide with a binary op + reduction.

**Comment by cwharris** [comment]
In the mean time, something along these lines would work (though clearly not very reusable).

```
import cudf
import numpy

def kernel(a, b, c, out):
     for i, (x, y, z) in enumerate(zip(a, b, c)):
         out[i] = x * y * z

num_rows = 20000000

df = cudf.DataFrame([
    ('a', list(range(num_rows))),
    ('b', list(reversed(range(num_rows)))),
    ('c', list(range(num_rows)))
])

df = df.apply_rows(
    kernel,
    incols=['a', 'b', 'c'],
    outcols=dict(out=numpy.float64),
    kwargs=dict()
)

dot_product = df['out'].sum()
```

**Comment by ritchieng** [comment]
Thanks!

**Comment by karthikeyann** [comment]
[`pandas.DataFrame.dot`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dot.html) is matrix multiplication. It is not dot product which is the requested feature in this issue.

**Comment by beckernick** [comment]
Are we sure we need this in libcudf, as opposed to relying on cuDF <-> CuPy for matrix manipulation?

**Comment by jrhemstad** [comment]
> Are we sure we need this in libcudf, as opposed to relying on cuDF <-> CuPy for matrix manipulation?

Yeah, this doesn't need to be in libcudf.
