### ISSUE TITLE
[FEA] Add `cudf::partition`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2452]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to partition a `table` into `m` new `table`s by using a column with the same number of values as rows in the `table` that maps each row to a particular partition. 

This is useful for doing distributed sorting in Dask: https://github.com/rapidsai/cudf/issues/2272 

**Describe the solution you'd like**

I'm envisioning an algorithm that does the following:

Inputs:

- A `table` with N rows
- A `partition_map` of N values `[0, m)`
- `m` the number of partitions

Outputs:
`m` `table`s where `table` `i` contains all of the rows `j` from the input `table` where `partition_map[j] == i`

**Describe alternatives you've considered**

This could also be accomplished by first sorting the `partition_map`, getting the first index of each unique value (`gdf_unique_indices`), and then using `cudf::slice/split`. However, I think that would be much less efficient than the algorithm I described above. 

**Additional context**

[`gdf_hash_partition`](https://github.com/rapidsai/cudf/blob/branch-0.9/cpp/include/cudf/functions.h#L359) is a very similar existing feature to the one I am requesting, albeit more specialized. 

`gdf_hash_partition` accepts a `table` and a desired number of partitions `m`. It hashes each row, and then maps the hash value to a partition. This effectively creates the `partition_map` described above. 

By fusing the generation of the `partition_map` with the actual partitioning allows this operation to be more efficient. However, in the spirit of generality, the partitioning phase of the `gdf_hash_partition` algorithm could be split off into it's own feature that would satisfy the desired new feature.

**Comment by harrism** [comment]
As a short-term solution, could we just providing python bindings that build partition using cudf::slice? The cython code would need to compute the slice indices, rather than a number of slices.

**Comment by jrhemstad** [comment]
> As a short-term solution, could we just provide python bindings that build partition using cudf::slice? The cython code would need to compute the slice indices, rather than a number of slices. This may be lower effort since we wouldn't need new gtests.

That would work, but `cudf::slice` would probably need to be optimized then because it currently invokes a separate kernel per slice.

**Comment by felipeblazing** [comment]
We have a function that handles this right now and would be happy to move it into cudf.

**Comment by harrism** [comment]
@felipeblazing how soon can you do it?

**Comment by rjzamora** [comment]
> We have a function that handles this right now and would be happy to move it into cudf.

@felipeblazing Just curious if you have any update on this?

**Comment by jrhemstad** [comment]
Suggested naming instead of `cudf::partition` is `cudf::shuffle`.

**Comment by karthikeyann** [comment]
is deep copy required for new `table`s?

**Comment by harrism** [comment]
I think this is the wrong issue for discussion. Please discuss on #2677.

**Comment by harrism** [comment]
I'm going to close this issue.
