### ISSUE TITLE
[FEA] Add gdf_to_np_dtype to cudf_cpp.pxd

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cudf#2457]
**Is your feature request related to a problem? Please describe.**

Could you add the 
gdf_to_np_dtype function (defined in python/cudf/cudf/bindings/cudf_cpp.pyx)
to the python/cudf/cudf/bindings/cudf_cpp.pxd file?

get_dtype (numpy types to gdf_dtype) is exposed in cudf_cpp.pxd file for external users but gdf_to_np_dtype (gdf_dtype to numpy types) is not. cuGraph needs both.

**Comment by kkraus14** [comment]
@seunghwak `gdf_to_np_dtype` is a Python defintion as opposed to a cdef, so you should be able to just import it as opposed to cimport and it should work without issue. I.E. `from cudf.bindings.cudf_cpp import gdf_to_np_dtype`
