### ISSUE TITLE
Alternative to iloc() = .at()

### ISSUE THREAD

**Issue by darogross** [rapidsai/cudf#2465]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]
.iloc() or .at() are necessary to load real time data into a dataframe. Why not use .at() instead of .iloc() to start. It's faster and easier.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by shwina** [comment]
@darogross Thanks for reporting. Could you please provide a code snipped (using Pandas maybe?) that shows what you need to achieve?

**Comment by darogross** [comment]
Just need to load data into row 0 of a pandas dataframe, e.g., df.at[0,
"column"] = 1

*Daro Gross*

*Mobile: 408.348.9110*
*Skype: ncfproject*

**Comment by darogross** [comment]
Also need to access values with x = df.at[row, column]

*Daro Gross*

*Mobile: 408.348.9110*
*Skype: ncfproject*

**Comment by shwina** [comment]
Thanks! This will be added in #2442

**Comment by darogross** [comment]
When might that be?

*Daro Gross*

*Mobile: 408.348.9110*
*Skype: ncfproject*

**Comment by shwina** [comment]
That PR is actively being worked on. It should be available in the coming release, which is scheduled for Aug 21st. If it's merged into the current `branch-0.9` branch earlier than that, you could use it via a nightly build of cudf.

**Comment by darogross** [comment]
Keep me abreast of progress. I am just waiting for Nvidia so I can test.

*Daro Gross*

*Mobile: 408.348.9110*
*Skype: ncfproject*

**Comment by kkraus14** [comment]
Resolved by #2442
