### ISSUE TITLE
[BUG] nvstrings ipc-transfer methods incorrect when using rmm memory pool

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#2469]
**Describe the bug**
The NVStrings `ipc_transfer.h` interfaces need to account for rmm memory pool.

**Steps/Code to reproduce bug**
Server code -- creates nvstrings instance and ipc-data
```
from librmm_cffi import librmm as rmm
from librmm_cffi import librmm_config as rmm_cfg
rmm_cfg.use_pool_allocator = True
rmm_cfg.initial_pool_size = 2 << 30
rmm.initialize()
import nvstrings
strs = nvstrings.to_device(["abc", "defghi", None, "jkl", "mno", "pqr", "stu", "dog and cat"])
ipc_data = strs.get_ipc_data()
import sys, pickle
with open("/tmp/ipctest", 'wb') as filehandler:
            pickle.dump(ipc_data, filehandler)
input('server ready')  # process waits for the client
```
Client code that reads the ipc-data to create the nvstrings instance:
```
from librmm_cffi import librmm as rmm
from librmm_cffi import librmm_config as rmm_cfg
rmm_cfg.use_pool_allocator = True
rmm_cfg.initial_pool_size = 2 << 30
rmm.initialize()
import nvstrings, sys, pickle
filehandler = open("/tmp/ipctest", 'rb')
ipc_data = pickle.load(filehandler)
new_strs = nvstrings.create_from_ipc(ipc_data)
```
Error occurs because the pointer used is inside the pool:
```
nvs-create-ipc: cudaErrorInvalidValue(1):invalid argument
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorInvalidValue: invalid argument
208 nvs-getStringsPtrAborted
```
The above works correctly when the rmm memory pool is not used.

The NVStrings `ipc_transfer.h` data needs to include the pool pointer offset available from the rmm api `rmmGetAllocationOffset()` and then apply it appropriately when creating the new instance on the client context.

**Comment by harrism** [comment]
I think it's worth looking at how cuDF handles (or handled) cudaIpcHandle lifetime. CC @kkraus14 .  A quick search of this repo only turned up code in nvstrings. But I swear we used to have to handle cudaIpc -- that's why I added the offset to RMM.

**Comment by harrism** [comment]
Perhaps another option would be to build opening / closing the IpcMemHandle into RMM itself.

**Comment by harrism** [comment]
Moving to 0.11.

**Comment by kkraus14** [comment]
Closing as this is no longer necessary with native string integration.
