### ISSUE TITLE
[BUG] DataFrame concatenation fails on large inputs

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cudf#2474]
**Describe the bug**
cudf.concat gives a cudaErrorInvalidValue error

**Steps/Code to reproduce bug**
     
     import cudf
     import numpy as np
     df1 = cudf.DataFrame()
     df1['src']=np.ones(500000000, dtype=np.int32)*244
     df1['dst']=np.ones(500000000, dtype=np.int32)*111
     df2 = cudf.DataFrame()
     df2['src']=np.ones(500000000, dtype=np.int32)*826
     df2['dst']=np.ones(500000000, dtype=np.int32)*507
     df = cudf.concat([df1,df2])
     Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "/home/nfs/iroy/anaconda3/envs/cugraph_env_10/lib/python3.7/site-packages      /cudf/multi.py", line 52, in concat
     return DataFrame._concat(objs, axis=axis, ignore_index=ignore_index)
     File "/home/nfs/iroy/anaconda3/envs/cugraph_env_10/lib/python3.7/site-packages /cudf/dataframe/dataframe.py", line 1279, in _concat
     index = Index._concat([o.index for o in objs])
     File "/home/nfs/iroy/anaconda3/envs/cugraph_env_10/lib/python3.7/site-packages/cudf/dataframe/index.py", line 132, in _concat
     data = Column._concat([o.as_column() for o in objs])
     File "/home/nfs/iroy/anaconda3/envs/cugraph_env_10/lib/python3.7/site-packages/cudf/dataframe/column.py", line 116, in _concat
     col = _column_concat(objs, col)
     File "cudf/bindings/concat.pyx", line 23, in cudf.bindings.concat._column_concat
     RuntimeError: CUDA error encountered at: /conda/envs/gdf/conda- bld/libcudf_1561648877394/work/cpp/src/column/column.cpp:101: 11 cudaErrorInvalidValue  invalid argument

**Environment details**
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2018-09-25"
     DGX_SWBUILD_VERSION="4.0.2"
     DGX_COMMIT_ID="6acd9cb"
     DGX_PLATFORM="DGX Server for DGX-2"
     DGX_SERIAL_NUMBER=0574318000281
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
     NAME="Ubuntu"
     VERSION="18.04.1 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.1 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux exp01 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Aug  6 10:52:27 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM3...  On   | 00000000:34:00.0 Off |                    0 |
     | N/A   35C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM3...  On   | 00000000:36:00.0 Off |                    0 |
     | N/A   32C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM3...  On   | 00000000:39:00.0 Off |                    0 |
     | N/A   38C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM3...  On   | 00000000:3B:00.0 Off |                    0 |
     | N/A   38C    P0    53W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM3...  On   | 00000000:57:00.0 Off |                    0 |
     | N/A   33C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM3...  On   | 00000000:59:00.0 Off |                    0 |
     | N/A   38C    P0    53W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM3...  On   | 00000000:5C:00.0 Off |                    0 |
     | N/A   34C    P0    52W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM3...  On   | 00000000:5E:00.0 Off |                    0 |
     | N/A   38C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   8  Tesla V100-SXM3...  On   | 00000000:B7:00.0 Off |                    0 |
     | N/A   33C    P0    52W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   9  Tesla V100-SXM3...  On   | 00000000:B9:00.0 Off |                    0 |
     | N/A   35C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  10  Tesla V100-SXM3...  On   | 00000000:BC:00.0 Off |                    0 |
     | N/A   36C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  11  Tesla V100-SXM3...  On   | 00000000:BE:00.0 Off |                    0 |
     | N/A   38C    P0    51W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  12  Tesla V100-SXM3...  On   | 00000000:E0:00.0 Off |                    0 |
     | N/A   33C    P0    50W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  13  Tesla V100-SXM3...  On   | 00000000:E2:00.0 Off |                    0 |
     | N/A   35C    P0    49W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  14  Tesla V100-SXM3...  On   | 00000000:E5:00.0 Off |                    0 |
     | N/A   38C    P0    54W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |  15  Tesla V100-SXM3...  On   | 00000000:E7:00.0 Off |                    0 |
     | N/A   37C    P0    49W / 350W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              96
     On-line CPU(s) list: 0-95
     Thread(s) per core:  2
     Core(s) per socket:  24
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Platinum 8168 CPU @ 2.70GHz
     Stepping:            4
     CPU MHz:             2911.355
     CPU max MHz:         3700.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            5400.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            33792K
     NUMA node0 CPU(s):   0-23,48-71
     NUMA node1 CPU(s):   24-47,72-95
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke
     
     ***CMake***
     /home/nfs/iroy/anaconda3/envs/cugraph_env_10/bin/cmake
     cmake version 3.14.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /home/nfs/iroy/anaconda3/envs/cugraph_env_10/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /usr/local/cuda/bin:/home/nfs/iroy/anaconda3/envs/cugraph_env_10/bin:/home/nfs/iroy/bin:/home/nfs/iroy/.local/bin:/home/nfs/iroy/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/nfs/iroy/anaconda3/envs/cugraph_env_10
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/nfs/iroy/anaconda3/bin/conda
     # packages in environment at /home/nfs/iroy/anaconda3/envs/cugraph_env_10:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     alabaster                 0.7.12                     py_0    conda-forge
     arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
     asn1crypto                0.24.0                py37_1003    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     boost                     1.68.0          py37h8619c78_1001    conda-forge
     boost-cpp                 1.68.0            h11c811c_1000    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py37_1    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     Click                     7.0                       <pip>
     cloudpickle               1.2.1                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     commonmark                0.9.0                      py_0    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               10.0.130                      0
     cudf                      0.8.0                    py37_0    rapidsai/label/cuda10.0
     cugraph                   0+untagged.1196.g64fcb88           <pip>
     cugraph                   0+untagged.1153.g05c7b4c.dirty           <pip>
     cugraph                   0.9.0a0+229.ge72952b.dirty           <pip>
     cugraph                   0.9.0a1+171.gdd3e17d.dirty           <pip>
     cugraph                   0+untagged.1196.g64fcb88.dirty           <pip>
     cugraph                   0+untagged.1197.g7a96bd6.dirty           <pip>
     cugraph                   0.9.0a1+172.gb306fb5.dirty           <pip>
     cugraph                   0.9.0a0+229.ge72952b           <pip>
     cugraph                   0+untagged.1201.g756d0ae.dirty           <pip>
     cugraph                   0.9.0a1+171.gdd3e17d           <pip>
     cugraph                   0.9.0a1+213.g9038cf1.dirty           <pip>
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cython                    0.29.12          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask-core                 2.1.0                      py_0    conda-forge
     dask-cuda                 0.8.0                    py37_0    rapidsai/label/cuda10.0
     dask-cuda                 0.6.0                     <pip>
     dask-cudf                 0.0.0.dev0                <pip>
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     distributed               2.1.0                      py_0    conda-forge
     docutils                  0.15.1                   py37_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     future                    0.17.1                py37_1000    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     icu                       58.2              hf484d3e_1000    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        0.18                     py37_0    conda-forge
     ipykernel                 5.1.1            py37h5ca1d4c_0    conda-forge
     ipython                   7.6.1            py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.14.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     jsonschema                3.0.1                    py37_0    conda-forge
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libblas                   3.8.0               10_openblas    conda-forge
     libcblas                  3.8.0               10_openblas    conda-forge
     libcudf                   0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     liblapack                 3.8.0               10_openblas    conda-forge
     libnvstrings              0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libopenblas               0.3.6                h6e990d7_5    conda-forge
     libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
     librmm                    0.8.0                cuda10.0_0    rapidsai/label/cuda10.0
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libuv                     1.30.1               h516909a_0    conda-forge
     llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
     Markdown                  2.6.11                    <pip>
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     more-itertools            7.1.0                      py_0    conda-forge
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     nbconvert                 5.5.0                      py_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.4.2                      py_0    conda-forge
     nccl                      1.3.5                cuda10.0_0
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.3                        py_0    conda-forge
     notebook                  6.0.0                    py37_0    conda-forge
     numba                     0.45.0           py37hb3f55d8_0    conda-forge
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     nvstrings                 0.8.0                    py37_0    rapidsai/label/cuda10.0
     openblas                  0.3.6                h6e990d7_5    conda-forge
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.25.0           py37hb3f55d8_0    conda-forge
     pandoc                    2.7.3                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         4    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pip                       19.2.1                   py37_0    conda-forge
     pluggy                    0.12.0                     py_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.12.1           py37hbbcf98d_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.1                      py_0    conda-forge
     pyrsistent                0.15.3           py37h516909a_0    conda-forge
     pysocks                   1.7.0                    py37_0    conda-forge
     pytest                    5.0.1                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     python-louvain            0.13                       py_0    conda-forge
     pytz                      2019.1                     py_0    conda-forge
     pyyaml                    5.1.1            py37h516909a_0    conda-forge
     pyzmq                     18.0.2           py37h1768529_2    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.5.0                      py_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.8.0                    py37_0    rapidsai/label/cuda10.0
     scipy                     1.3.0            py37h921218d_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.0.1                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snowballstemmer           1.9.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.1.2                      py_0    conda-forge
     sphinx-markdown-tables    0.0.9                     <pip>
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.29.0               hcee41ef_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
     tk                        8.6.9             hed695b0_1002    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.2                 py37_1000    conda-forge
     urllib3                   1.25.3                   py37_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.4                   py37_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                     <pip>
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.5.1                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1005    conda-forge

**Comment by Iroy30** [comment]
I believe what is happening is during Index._concat (which happens before actual data/column concatenation) the index dtype is default to int64, so byte width is 8, which results in an overflow in calculated bytes (which is a 32 bit integer) at the following line: https://github.com/rapidsai/cudf/blob/bc1bb7b5e5df0fe8cf083ec96d6ccc11b289b91b/cpp/src/column/legacy/column.cpp#L100 

Forcing index dtype to int32 fixes the issue:
>>> import cudf
>>> import numpy as np
>>> df1 = cudf.DataFrame()
>>> df1['src']=np.ones(500000000, dtype=np.int32)*244
>>> df1['dst']=np.ones(500000000, dtype=np.int32)*111
>>> df1.index = df1.index.astype(np.int32)
>>> df2 = cudf.DataFrame()
>>> df2['src']=np.ones(500000000, dtype=np.int32)*826
>>> df2['dst']=np.ones(500000000, dtype=np.int32)*507
>>> df2.index = df2.index.astype(np.int32)
>>> df = cudf.concat([df1,df2])

However, cudf should have an inbuilt process to handle the same for large concats.

**Comment by jrhemstad** [comment]
Aha! Good catch, that `bytes` calculation should definitely use `size_t`. I'll open a PR with that change right away.
