### ISSUE TITLE
[QST] Memory Reporting

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#2478]
I am seeing strange behavior with cudf memory reporting. 

If I create a dataframe with 2**26 ints I should expect ~.5GB to be allocated on the GPU + some amount for cuda context.  Instead, I see 1.8GB:

```python
In [1]: import cudf

In [2]: from numba import cuda

In [3]: free_before = cuda.current_context().get_memory_info()[0]

In [4]: cdf = cudf.DataFrame({'a': range(2**26)})

In [5]: free_after = cuda.current_context().get_memory_info()[0]

In [6]: free_before - free_after
Out[6]: 1541406720

In [7]: cdf.__sizeof__()
Out[7]: 536870944
```

However, on subsequent constructions the "appropriate" amount of memory is allocated:

```python
In [17]: free_before = cuda.current_context().get_memory_info()[0]

In [18]: cdf3 = cudf.DataFrame({'a': range(2**26)})
free_after =
In [19]: free_after = cuda.current_context().get_memory_info()[0]

In [20]: free_before - free_after
Out[20]: 536870912
```

Is rmm building a larger cuda context than expected ?  Would this at all impact serialization in that the full context is not being serialized ?  I am looking at this through a UCX debugging lens as well (grasping at straws for why things aren't working)

cc @kkraus14 @pentschev

**Comment by kkraus14** [comment]
@quasiben there's a few things happening here:
First, the CUDA context is created on the dataframe call as opposed to on import (will change in the future) and takes ~500MB. We use numba to create this and you can recreate the behavior using the following:
```python
from numba import cuda
ctx = cuda.current_context()
free, total = ctx..get_memory_info()
print(total - free)
# 332005376 for me
```

Then you can run your cudf operation afterwards and you should see the roughly ~500MB consumed:
```
import cudf
cdf = cudf.DataFrame({'a': range(2**26)})
free, total = ctx..get_memory_info()
print(total - free)
# 1005191168 for me
```

If there's additional processes running on the same GPU it would affect the results as numba will be creating the driver API as opposed to the runtime API in this situation as far as I know.

**Comment by kkraus14** [comment]
Additionally, I've seen the CUDA context vary in size but I'm not sure exactly what the semantics related to it are.

**Comment by kkraus14** [comment]
Closing as this isn't an issue.
