### ISSUE TITLE
[FEA] Add DataFrame.memory_usage support

### ISSUE THREAD

**Issue by qinxuye** [rapidsai/cudf#2488]
**Is your feature request related to a problem? Please describe.**

I use `df.memory_usage(index=False, deep=True)` to obtain the usage of memory of each column, but it's absent in cudf.

The method can be added to cudf.Series as well.

**Comment by jrhemstad** [comment]
Thanks for filing an issue for a feature enhancement. I believe this one has already been requested here:  https://github.com/rapidsai/cudf/issues/1937. As such, closing this issue. Feel free to comment on the existing issue.
