### ISSUE TITLE
Dataframe groupby -> apply_grouped inplace?

### ISSUE THREAD

**Issue by Denisevi4** [rapidsai/cudf#249]
Is it possible to make an inplace dataframe groupby apply_grouped operation?

I see that after I do groupby and then apply_grouped method, I get a completely new dataframe and the old one is still in memory.

`
    new_df = df_old.groupby("GroupColumn", method= "pygdf).apply_grouped(
        transform_kernel,
            incols=['c1'],
            outcols={'c2': np.float64}
    )
`

if I print both dataframes, they'd have different c2 columns, so they are different dataframes.

I have two questions:
1. How do I release memory from the old dataframe, the one prior to apply_grouped ? if I do 
`
    del old_df
`
does it release it from GPU memory? Or should I do some additional cleanup?

2. Is it possible just to update the columns in the old dataframe assuming that the dataframe is already sorted so that the groups come contiguously?

**Comment by kkraus14** [comment]
1. Deleting the `old_df` releases the reference to the dataframe and associated columns which then defers them to Numba for garbage collection. Numba's CUDA garbage collection policy can be seen here: https://numba.pydata.org/numba-doc/dev/cuda/memory.html#deallocation-behavior

2. In general we try to avoid inplace operations right now and we have hash based methods in addition to sort based methods for joins and groupbys.

**Comment by Denisevi4** [comment]
Thanks!

**Comment by Denisevi4** [comment]
Oh, and by the way, thank you for this awesome package. I'm enjoying it so far. It's a good start.
