### ISSUE TITLE
groupby rounding error cause different answer from same query

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#2494]
Running same query twice produce slightly different result. Seems to be related to floating point rounding error.
Is there any documentation about the magnitude of rounding error? so I can use appropriate tolerance when testing for equality.
```py
import os
import gc
import cudf as cu
ver = cu.__version__
print(ver)
#0.8.0+0.g8fa7bd3.dirty
src_grp = "G1_1e7_1e2_0_0.csv"
x = cu.read_csv(src_grp, skiprows=1,
                names=['id1','id2','id3','id4','id5','id6','v1','v2','v3'],
                dtype=['str','str','str','int','int','int','int','int','float'])
print(len(x.index), flush=True)
# 10000000
ans = x.groupby(['id6'],as_index=False).agg({'v1':'sum', 'v2':'sum', 'v3':'sum'}).reset_index(drop=True)
chk = [ans['sum_v1'].sum(), ans['sum_v2'].sum(), ans['sum_v3'].sum()]
print(chk)
#[30001016, 29998058, 506569984.0]
del ans
gc.collect()
#5563
ans = x.groupby(['id6'],as_index=False).agg({'v1':'sum', 'v2':'sum', 'v3':'sum'}).reset_index(drop=True)
chk = [ans['sum_v1'].sum(), ans['sum_v2'].sum(), ans['sum_v3'].sum()]
print(chk)
#[30001016, 29998058, 506570048.0]
```
to produce data use this python script https://github.com/dask/dask/issues/4372#issuecomment-453899270 and save file as `G1_1e7_1e2_0_0.csv`.

**Comment by jrhemstad** [comment]
This isn't a bug.

The result from summing a set of `n` floating point numbers depends on the order in which they are summed together. As we are doing the groupby computation in parallel, there is no guarantee on the order in which they are summed, and as such, cannot guarantee bitwise equality from run to run. 

As for your question about tolerances, there is no quick and easy answer. This is a good resource that should help you determine how to best test for equality: https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/
