### ISSUE TITLE
[FEA] Loading timestamps with microsecond precision when supported by format

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#2497]
**Is your feature request related to a problem? Please describe.**
When loading timestamps from a file format parsed by the GPU, timestamps are returned in units of milliseconds.  This loses precision when the original data format (e.g.: Parquet, ORC, etc.) provided a more precise value.

For a concrete example, Apache Spark tracks timestamps internally in microseconds.  When loading timestamp data from a Parquet or ORC file that contains microsecond resolution or higher, the data loaded by the GPU does not match the same data that was loaded by the CPU.  Ideally using GPU-accelerated Spark should not cause a loss of timestamp precision when compared to the non-GPU version.
 
**Describe the solution you'd like**
cudf loader parameters could support an optional timestamp unit.  When specified, timestamp data would be automatically cast to a GDF_TIMESTAMP column in the specified time unit precision.  Spark could then request timestamps be parsed with microsecond precision to match the CPU version.

**Describe alternatives you've considered**
Another approach is to have a flag that informs the cudf data loaders to load timestamp data in the highest resolution supported by the file.  This is not as convenient for the Spark use case, since it will always end up casting back to Spark's internal format of microseconds.  However there may be other, non-Spark use-cases where it could be useful to always load the data in the most precise format available.

**Comment by OlivierNV** [comment]
I'm assuming this feature would be C++ API only ?
Right now, date64 and timestamp columns are converted to milliseconds due to cudf limitations on the python side. I think the optional gdf time unit for the readers makes sense, with TIME_UNIT_NONE meaning keep the native time unit of the file (microseconds for parquet and nanoseconds for ORC IIRC)

**Comment by jlowe** [comment]
Yes, this would be for the C++ API only.

**Comment by trxcllnt** [comment]
The limitations on the python side are resolved now, so we should be able to expose this there too.
