### ISSUE TITLE
[BUG] joins can return success without initializing dtypes

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#2504]
**Describe the bug**
If you do a join that is going to return an empty table GDF_SUCCESS is returned before the output dtypes are initialized. Which means the caller has to initialize the dtypes themselves before passing in the output which is not needed in any other case.
```
  GDF_REQUIRE(0 != num_cols_to_join, GDF_SUCCESS);
...

  // If the inputs are empty, immediately return
  if ((0 == left_col_size) && (0 == right_col_size)) {
    return GDF_SUCCESS;
  }

  // If left join and the left table is empty, return immediately
  if ((JoinType::LEFT_JOIN == join_type) && (0 == left_col_size)) {
    return GDF_SUCCESS;
  }

  // If Inner Join and either table is empty, return immediately
  if ((JoinType::INNER_JOIN == join_type) &&
      ((0 == left_col_size) || (0 == right_col_size))) {
    return GDF_SUCCESS;
  }
```

**Steps/Code to reproduce bug**
Inner join where either table is empty.

**Expected behavior**
Get a valid set of empty columns back.

**Comment by jrhemstad** [comment]
@rgsl888prabhu can you fix this as part of https://github.com/rapidsai/cudf/pull/2496?

Since you're updating to use `table`, it should just be as easy as returning a `empty_like(...)`.

**Comment by jrhemstad** [comment]
@revans2 also note that in #2496, join is being updated to _return_ outputs rather than having them be passed as output parameters.

**Comment by rgsl888prabhu** [comment]
I have already taken care of that issue, once the PR gets approved, it should be working.

**Comment by revans2** [comment]
@jrhemstad @rgsl888prabhu sounds great. Do you want me to close this now as a dupe of #2496 or should I wait?

**Comment by rgsl888prabhu** [comment]
I have mentioned this bug in my PR, so once its merged, it should automatically close the bug as well.
