### ISSUE TITLE
[FEA] Add _constructor_sliced property

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#2506]
**Is your feature request related to a problem? Please describe.**
In pandas, the [`_constructor_sliced` property](https://github.com/pandas-dev/pandas/blob/d44fb07063e9a8bd8a209ddce35b40d8a56c8d02/pandas/core/frame.py#L380) of a dataframe will return a pandas-`Series` constructor.  I would like the same property to exist for a cudf dataframe.  This would allow cudf series objects to be generated from cudf dataframes within dask (without requiring dask to explicitly check if the dataframe is pandas or cudf-based).

**Describe the solution you'd like**
I would like the addition of a very simple property, returning the `Series` constructor for a cudf DataFrame (and raising an error for a cudf Series). 

**Describe alternatives you've considered**
In dask, we are currently resorting to things like `type(dask.dataframe.DataFrame._meta.iloc[:, 0])` to get a Series constructor in a way that works for both pandas and cudf. Unfortunately, this approach breaks is some cases (like a dataframe without columns).

**Additional context**
Although `_constructor_sliced` is not currently documented as a *public* property, [pandas-dev/pandas issue#27824](https://github.com/pandas-dev/pandas/issues/27824) is suggesting such documentation.

This change will simplify [efforts to support `set_index`-based shuffling in dask](https://github.com/dask/dask/pull/5205)

**Comment by beckernick** [comment]
I believe this was resolved by #2536. Closing.
