### ISSUE TITLE
[BUG] ImportError: /home/USERNAME/anaconda3/lib/python3.6/site-packages/cudf/bindings/replace.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gdf_find_and_replace_all

### ISSUE THREAD

**Issue by gfelitti** [rapidsai/cudf#2520]
As I try to import cudf,  my system (Pyhton 3.6 / Ubuntu 19 - cuDF installed using Conda)  throws me a ImportError:

ImportError: /home/USERNAME/anaconda3/lib/python3.6/site-packages/cudf/bindings/replace.cpython-36m-x86_64-linux-gnu.so: undefined symbol: gdf_find_and_replace_all

When I installed on Sunday, it worked just fine, what confuses me.

**Comment by nvrajana** [comment]
Please try updating to latest cudf version 0.8

**Comment by kkraus14** [comment]
Stale, closing.
