### ISSUE TITLE
[FEA] Create collection of dataframes for testing

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#2530]
When testing cudf with new systems it is often useful to have a somewhat comprehensive collection of dataframes that cudf might create.  This would be useful for testing systems like serialization, writing to various formats, and so on.  Ideally, I would test my system with with cudf by doing something like the following:

```python
# cudf/python/cudf/utils.py

dataframes = {
    "series": lambda: cudf.Series([1, 2, 3]),
    "series-strings": lambda: cudf.Series(["a", "b", "c"]),
    "dataframe": lambda: cudf.DataFrame({"x": [1, 2, 3], "y": [1., 2., 3.]}),
    "empty-series": lambda: cudf.Series([], name="foo"),
    ...
    "large-series": lambda: cudf.Series(np.arange(100000000)),
    ...
}
```

```python
# my-external-code.py
from cudf.utils import dataframes

for name, df_func in dataframes.items():
    df = df_func()
    try:
        myfunction(df)
    except Exception as e:
        print(name, "failed with exception", e)
```

This collection might include things like ...

1.  dataframes of different types
2.  series
3.  empty dataframes/series
4.  strings
5.  categoricals
6.  dataframes with a non-trivial index
7.  Big dataframes/series
8.  Datetimes

and so on.

I think that @quasiben could use this for UCX testing (we keep running into situations where our serialization can't handle things correctly) and I suspect that it would also be helpful for I/O work (cc @mjsamoht )

I made the actual values callables above so that we wouldn't need to actually allocate these at startup.

**Comment by GregoryKimball** [comment]
The python benchmarks introduced by #11125 provide an excellent collection of dataframes and operations for testing.

**Comment by vyasr** [comment]
I think I accidentally reopened this.
