### ISSUE TITLE
[FEA] Add `as_map` Python utility function to create a gathermap from arbitrary inputs

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#2537]
Gathermaps are used in a few different places, especially in the Cython bindings and it will be useful to create a utility function to create them from arbitrary inputs (e.g., integers, negative integers, booleans, masks, etc.,)

**Comment by kkraus14** [comment]
@shwina with the gather changes is this still needed?

**Comment by shwina** [comment]
Nope. Since libcudf now works with a column, we can just use `as_column()` instead.
