### ISSUE TITLE
[FEA] Parquet reader should be able to specify row groups to read

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#2539]
The parquet reader used to be able to specify which row groups were to be read. This capacity has been removed in the new api and it is necessary if people want to reap the benefits of data skipping by reading meta data.

I would expect one of the parquet reader options to be able to specify which rowgroups we want to load into the dataframe.

There aren't really any alternatives since this is perfomring the i/o.

**Comment by j-ieong** [comment]
If you use the Python interface, it should have a row_group parameter. Ex:
https://github.com/rapidsai/cudf/blob/79850a478e6e208f5d2a6dff840327a7c4e547a1/python/cudf/cudf/tests/test_parquet.py#L232

If you use `cudf::read_parquet`, the `parquet_read_arg` struct should have row group option:
https://github.com/rapidsai/cudf/blob/79850a478e6e208f5d2a6dff840327a7c4e547a1/cpp/include/cudf/io_types.hpp#L201-L216

Both the above wrap the lower-level `cudf::io::parquet::reader`, which has a `read_row_group()` method:
https://github.com/rapidsai/cudf/blob/79850a478e6e208f5d2a6dff840327a7c4e547a1/cpp/include/cudf/io_readers.hpp#L424-L431

**Comment by kkraus14** [comment]
@felipeblazing does this suffice for you?

**Comment by j-ieong** [comment]
We already have the ability to read an individual row group in both the Python and C++; it was never removed in the new interface. Closing...
