### ISSUE TITLE
[FEA][DOC] Need examples folder for cudf cpp

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#2547]
Often times when I tell my friends about rapidsai they find that they can't get started on libcudf (C++) without an initial learning curve. I have been told that if we had an examples folder with clear and concise examples of usages of our API that would be a great help. The tests folder is doing a semi decent job at it but because we use internal APIs that are only available in test context they aren't a 100% transferable to an application outside of the project.

**Comment by harrism** [comment]
@razajafri can you please clarify whether this is referring to the cuDF API (Python) or libcudf API (C++). Thanks!

**Comment by razajafri** [comment]
This refers to libcudf (C++). I have also updated the description
