### ISSUE TITLE
[FEA] Keep the order of rows in tables returned by `groupby` the same with that in table of keys

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#2549]
I wish i could use cuDF to calculate the group information( and weight inforamtion) for learning to rank in XGBoost-Spark by a single call to `groupby` on group column with the aggregation `count`. But the output tables break the order of rows in the input table. 

Suppose having a keys table as below, the aggregation value table has only the second column,
     1   1
     1   3
     1   3
     1   5
     1   5
     1   0

Call `groupby` on column 0 and 1 with aggregation `count`, then actual output tables are 
    1    1       
    1    5              
    1    0         
    1    3         
and 
    1
    2
    1
    2

But what i want are
    1    1           
    1    3                   
    1    5                    
    1    0                    
and
   1
   2
   2
   1

Which keep the order unchanged and the second table is exactly the group information for learning to rank.

One possible solution for CUDF comes to my mind is to record the indices of the rows in keys table internally, and do a `orderby` on the indices column just after `groupby`, then run the aggerations on each group. So the output tables will keep the order the same with the intput keys table.

Of course there is an alternative solution, copying data into cpu memory and calculating the group information by iterating all the rows, but it is not CUDF things and really takes time.
The CPU version implementation in row way is here: https://github.com/dmlc/xgboost/blob/master/jvm-packages/xgboost4j-spark/src/main/scala/ml/dmlc/xgboost4j/scala/spark/XGBoost.scala#L706

**Comment by kkraus14** [comment]
Not even Pandas has this behavior.

```
In [2]: pdf = pd.DataFrame({'a': [1, 5, 5, 3, 3, 0]})

In [3]: pdf.groupby('a').agg({'a': 'count'})
Out[3]:
   a
a
0  1
1  1
3  2
5  2
```

If you want to maintain ordering that either means doing an extra n log n operation at the end to sort it which shouldn't be done implicitly for every operation. If you need a specific output ordering I'd suggest you call a sort after your groupby. I'm going to close this issue.
