### ISSUE TITLE
[BUG] fill tests crash when using different column sizes

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#2556]
**Describe the bug**
I ran into some code that tried filling a 7000-row column with a scalar null value which resulted in an CUDA memory error and crash.  Upon further investigation, I discovered I could reproduce this by simply varying the number of rows in the libcudf FILLING_TEST.  Setting `column_size` in filling_tests.cu to 1100 causes 14 of the 18 tests to fail with unexpected output.  Setting it to 3000 causes the `SetAll` test to crash:
```
Expected: cudf::fill(source.get(), *val.get(), begin, end) doesn't throw an exception.
  Actual: it throws.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted (core dumped)
```

**Steps/Code to reproduce bug**
Apply this patch, rebuild, and run gtests/FILLING_TEST
```patch
diff --git a/cpp/tests/filling/filling_tests.cu b/cpp/tests/filling/filling_tests.cu
index 01e7f1ea9..0a2c9bfe5 100644
--- a/cpp/tests/filling/filling_tests.cu
+++ b/cpp/tests/filling/filling_tests.cu
@@ -33,7 +33,7 @@ using test_types =
                    cudf::bool8>;
 TYPED_TEST_CASE(FillingTest, test_types);
 
-constexpr gdf_size_type column_size{1000};
+constexpr gdf_size_type column_size{3000};
 
 auto all_valid = [](gdf_index_type row) { return true; };
 ```

**Comment by devavret** [comment]
I'm unable to reproduce this in Release or Debug build. I've also tried using `cuda-memcheck` which returned no errors. Considering this is also a legacy test, I think this issue can be closed if you're unable to reproduce it in the modern `fill_tests` @jlowe .

**Comment by jlowe** [comment]
> Considering this is also a legacy test, I think this issue can be closed if you're unable to reproduce it

+1, closing.
