### ISSUE TITLE
Implement comprehensive set of ufuncs

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#256]
There are a variety of ufuncs that are not yet implemented on pygdf.  Operations like exp or round don't seem to be available.  Some of these come through Numpy:

    np.exp(df.x)

And some of them are methods:

    df.round(...)

**Comment by mrocklin** [comment]
One approach to this would be to combine the `__array_ufunc__` protocol with Numba's ability to compile Numpy functions.  I imagine that a solution might look something like the following:

```python
    def __array_ufunc__(self, ufunc, method, *inputs, **kwargs):
        if method == '__call__':
            numba_gpu_ufunc = numba.gpu_vectorize(ufunc)
            input_arrays = [input.to_gpu_array() if isinstance(pygdf.Series) else input for input in inputs]
            data  = numba_gpu_ufunc(*input_arrays, **kwargs)
            return pygdf.Series(data, index=...)
        else:
            return NotImplemented
```

Where I'm hoping that a function like `numba.gpu_vectorize` exists and works as I've expressed above.

cc @sklam is something like this possible?

**Comment by kkraus14** [comment]
Even if possible, things like `round`, `exp`, and other typical functions are things we will want implementations that don't depend on JIT compilation for as the time to compile the functions is non-trivial in many cases and we can often create more optimized implementations.

**Comment by kkraus14** [comment]
That being said, if we could do this for functionality first and optimize later that would be amazing.

**Comment by mrocklin** [comment]
@sklam @seibert any thoughts on this?  My guess is that this is easy-ish to do with numba, and possibly a nice win.

**Comment by seibert** [comment]
Roughly, this requires generating the scalar body of the ufunc (string templating is usually what we have to do) from the ufunc name and then wrapping with `@vectorize(target='gpu')`.  Not all these operations have Numba-known equivalents on the GPU, so you would need to implement them.

Another way to bootstrap could be with CuPy, which has implemented most of these functions with exact NumPy-like names and signatures.

**Comment by mrocklin** [comment]
It looks like we could use this for `np.sqrt` at least for groupby std.  cc @quasiben

**Comment by kkraus14** [comment]
Considering most of these are now implemented going to close this issue and encourage users to raise an issue for an individual function if it's not implemented already.
