### ISSUE TITLE
[BUG][Java] ColumnVector.fromScalar null issues

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#2564]
**Describe the bug**

1. On a failure from C++ cudf, `ColumnVector.fromScalar` is double closing a buffer, causing the original issue to be hidden.
2. With a null scalar, `ColumnVector.fromScalar` is calling `cudf::fill`, and in addition to the call being unnecessary, it can cause the following blocking issue for Spark (https://github.com/rapidsai/cudf/issues/2556). We should not call `cudf::fill` for a null scalar.

**Comment by abellina** [comment]
A PR to do this for the Java API is in the works.

**Comment by kkraus14** [comment]
Fixed by #2567
