### ISSUE TITLE
[BUG] Core dump while reading multiline Json Object File(cudf.read_json())

### ISSUE THREAD

**Issue by sandeepsingh** [rapidsai/cudf#2572]
**Describe the bug**
Core dump issue while creating dataframe from nested json file.

**Steps/Code to reproduce bug**
import cudf as cd
gdf = cd.read_json('test_multi_nested.json',lines=True)
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted (core dumped)

**Expected behavior**
It should have created a nested dataframe of shape (2,10). Able to get it from pandas df. 

**Environment overview (please complete the following information)**
 Rapids Docker nvcr.io/nvidia/rapidsai/rapidsai:cuda9.2-runtime-ubuntu16.04

**Environment details**
DGX-1 

**Additional context**
Json file is like this.

{"name":"ran","roll":123,"affiliation":{"college":"MJHS","company":["LLLP","KJP"]},"Keywords":["abc","def"],"activities":[{"facebook":123,"twitter":"handles"},{"facebook":345,"twitter":"no handles"}]}
{"name":"man","roll":321,"affiliation":{"college":"KKHS","company":["Rext","Mults"]},"Keywords":["zyx","mno"]}

**Comment by kkraus14** [comment]
@sandeepsingh Is this JSON lines with nested fields within each line or one big JSON object? Regardless, nested fields are not yet supported in cuDF.

**Comment by harrism** [comment]
Closing as no response and marked invalid.
