### ISSUE TITLE
[FEA] `Series.str.func` goes via host when return type is not a nvstrings instance

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2589]
**Describe the bug**
The stringMethods interface allows users to invoke nvstrings methods by doing the following on a string series. `StrSeries.str.stringmethod()`.

Some methods in nvstrings return data on the host (When the return type is not an nvstrings ir nvcategory instance. Eg: int, bools etc ). These methods always have an optional `devptr` argument to provide a gpu ptr to return directly to the device.

Calling such methods on a cudf string series goes via the host, reducing efficiency.

Exception to these are methods are those explicitly defined in the `stringMethods` class. eg:   [contains](https://docs.rapids.ai/api/nvstrings/nightly/) method which returns a cudf series of booleans.

**Steps/Code to reproduce bug**
```
import cudf
df = cudf.DataFrame()
n_elem = 10
df['a'] = ['127.0.0.1'] * n_elem
res = df['a'].str.ip2int()
type(res)
```
`list`

**Expected behavior**
Do not go via the host
- Some sort of generalized mechanism if possible to return a cudf series instead of host side pylist if `devptr` argument exists in the parent class method. (Possible issue is identifying the return dtype of the method. 
- Default nvstrings methods to return device array. Drawback is nvstrings is now responsible for creating a device array of specific types. 

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
`docker pull rapidsai/rapidsai-nightly:0.9-cuda10.0-devel-ubuntu16.04-gcc5-py3.7`

**Comment by kkraus14** [comment]
@ayushdg that was meant purely to be a workaround in the short term. I would suggest adding functions where appropriate to `string.py` as we'll eventually be plumbing them to Cython to connect to libcudf as custrings get merged into libcudf.

**Comment by kkraus14** [comment]
the nvstrings wrapper has been removed as of 0.14 so closing this.
