### ISSUE TITLE
[BUG] dataframe labels after merge

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cudf#2594]
**Describe the bug**
When the same column names are used but in a different order, the merge function doesn't label the output as expected.  I would expect either the columns to be labeled as the left data frame or expect both columns (as pandas).  See the example below.

**Steps/Code to reproduce bug**
The following code demonstrates the behavior:
```
a = cudf.DataFrame()
b = cudf.DataFrame()

a['src'] = [ 0, 0 ]
a['dst'] = [ 1, 2 ]
a['name'] = 'a'

b['src'] = [ 1, 2 ]
b['dst'] = [ 0, 0 ]
b['name'] = 'b'

print('a')
print(a.to_pandas())
print('a merge b')
print(a.merge(b, left_on=['src', 'dst'], right_on=['dst', 'src']).to_pandas())
```

**Expected behavior**
The current code provides the following result:
```
a
   src  dst name
0    0    1    a
1    0    2    a
a merge b
   src  dst name_x name_y
0    1    0      a      b
1    2    0      a      b
```
Note that the src and dest columns are labeled as in data frame b even though we started from a and did a left inner join.  I would expect - if we only keep one set of src/dst columns that it would be the columns from a, since that is both the object of the operation and the fact that we are doing a left join and a is on the left.  It might be better, in this case, to use the suffix method as pandas does.

Pandas (with the same code) provides the following output:
```
a
   src  dst name
0    0    1    a
1    0    2    a
a merge b
   src_x  dst_x name_x  src_y  dst_y name_y
0      0      1      a      1      0      b
1      0      2      a      2      0      b
```
Which preserves both values for src/dst by adding the suffixes to the key columns when their names match.  A little experimenting with different variations of selecting columns whose names match in same and different orderings suggest that the criteria for using the suffix is something like:
 - if we're comparing a key column from both data frames and the names match use this name in the output
 - if we're comparing a key column from both data frames and the names don't match then append the suffix if that column name appears as a column in the other data frame
 - Already have rules in place for handling if a non-key column name is duplicated, leave those in place.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
[cudf-environment.txt](https://github.com/rapidsai/cudf/files/3506146/cudf-environment.txt)

**Additional context**

**Comment by jrhemstad** [comment]
@rgsl888prabhu will https://github.com/rapidsai/cudf/pull/2496 fix this?

**Comment by rgsl888prabhu** [comment]
Yes, 2496 will fix this issue.
