### ISSUE TITLE
[FEA] as_type() for Dataframes

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2600]
I am trying to cast values in a dataframe to another datatype, and get the error `AttributeError: 'DataFrame' object has no attribute 'astype'`. 

I think as_type() is available for Series, but it would be good to have it for DataFrames (like Pandas) as well.

Example snippet: 

```
import cudf
import numpy as np
df = cudf.DataFrame({"x": (np.arange(4) // 2).astype(float)})
df.astype(int)
```

**Comment by ayushdg** [comment]
Duplicate of #2195
