### ISSUE TITLE
[FEA] Use multi-column apply_boolean_mask in cudf

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#2613]
libcudf provides a multi-column `apply_boolean_mask` which is currently not taken advantage of in cudf. As an optimization we should the multi-column version when masking a DataFrame with multiple columns, i.e., in `df.loc[mask]`.

**Comment by harrism** [comment]
I thought I did this in 0.9...

**Comment by shwina** [comment]
Yup - that's what I'm referring to. We just need the Python plumbing that utilizes the libcudf functions you wrote.

**Comment by harrism** [comment]
Yeah I meant I thought I did that when I made the existing pytests pass with the new API, which is table-only.  I guess there must be a single-columnification happening on the python side.

**Comment by shwina** [comment]
Yes, there is. Specifically here:

```

**Comment by kkraus14** [comment]
This is fixed as of 0.13.
