### ISSUE TITLE
What to use place of masked_assign? [QST]

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/cudf#2624]
**What is your question?**
- `masked_assign` was taken out of `series.py` a few days ago in [branch-0.9 merge](https://github.com/rapidsai/cudf/commit/3e40dd821af132ee05955004cabd02bd644362b4#diff-501a702b0087ece1365c3a792ab95570)
  - what should be used in its place? 

Thanks

**Comment by shwina** [comment]
Thanks for reporting. Setting values by mask can now be done with `loc` (same as Pandas'):

```
sr.loc[mask] = value
```

**Comment by gumdropsteve** [comment]
This works, thank you.
