### ISSUE TITLE
[BUG] Gather gives wrong result when gathering in-place

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#2630]
**Describe the bug**
`cudf::gather` gives a zeroed result when specifying the same source and destination table. 

**Steps/Code to reproduce bug**
Call `cudf::gather` on the same source and destination table

The bug is in these lines: https://github.com/rapidsai/cudf/blob/ea55d97b138bb43944b537156cdd561c5d557032/cpp/src/copying/gather.cu#L188-L192
because the allocation is happening in the default stream while the computation is happening in the stream passed to the enclosing function.

An easy fix is to replace `rmm::device_vector` with `RMM_ALLOC` because the latter can take a stream.

**Comment by jrhemstad** [comment]
I agree that this code is broken if pool mode is used (see https://github.com/rapidsai/cudf/issues/2631). However, in non-pool mode, then `cudaMalloc` is used, which is synchronous wrt to the host and it is guaranteed that `in_place_buffer` will be allocated before the following `thrust::gather` call.

**Comment by harrism** [comment]
This is a bug in legacy code. Closing.
