### ISSUE TITLE
[BUG] array calculation while doing MSE creates Nulls

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#2634]
References a NEW issue on this notebook: https://github.com/rapidsai/notebooks-contrib/blob/master/intermediate_notebooks/E2E/census/census_education2income_demo.ipynb

During the MSE calculation, the portion `y_test - y_pred` returns null values for the entire column.  This is a new error within the last 10 days.  Output is correct if data converted into a numpy array.  i'm at a loss why.  @cjnolet investigated with me, and we ended on this error:
```
RuntimeError: cuDF failure at: /conda/conda-bld/libcudf_1566114320500/work/cpp/src/binaryop/binaryop.cpp:285: Column data pointers are null
```

My attempt to make a reproducible works as it should...
```
import numpy as np
import cudf
yp= 10*np.random.rand(10000000)
yt = np.around(yp, 0)
#print(yp)
#print (yt)
y_pred = cudf.Series(yp)
y_test = cudf.Series(yt)
print(y_test - y_pred)
print("type of y_pred %s" % type(y_pred))
print("type of y_test %s" % type(y_test))
```
...but if i pickle the dataframe and run ridge on it, returns nulls despite having a similar formats and less data(< 30 seconds to complete)

```
import pandas as pd
import numpy as np
import cuml
import cudf
import dask_cudf
#import dask_cuml
import sys
import os
import gzip
from pprint import pprint
import warnings
warnings.filterwarnings('ignore')
###----------------------------
# MSE, CoD, and Ridge training helper function

def mse(y_test, y_pred):
    
    print("type of y_pred %s" % type(y_pred))
    print("type of y_test %s" % type(y_test))
    a = np.isnan(y_pred.to_array())
    b = np.isnan(y_test.to_array())
    print(str(len(a[a==True])))
    print(str(len(b[b==True])))
    print(y_pred.head())
    print (y_test.head())
    print(str((y_test - y_pred)))
    
    return ((y_test - y_pred) ** 2).mean()

def cod(y_test, y_pred):
    y_bar = y_test.mean()
    total = ((y_test - y_bar) ** 2).sum()
    residuals = ((y_test - y_pred) ** 2).sum()
    return 1 - (residuals / total)

from cuml.preprocessing.model_selection import train_test_split
trainsize = .9
yCol = "EDUC"
from cuml.preprocessing.model_selection import train_test_split
from cuml.linear_model.ridge import Ridge

def train_and_score(data, clf, train_frac=0.8, n_runs=20):
    mse_scores, cod_scores = [], []
    for _ in range(n_runs):
        X_train, X_test, y_train, y_test = cuml.preprocessing.model_selection.train_test_split(df, yCol, train_size=.9)
        #print(X_train.head())
        #print (X_test.head())
        y_pred = clf.fit(X_train, y_train).predict(X_test)
        #print(y_pred.head())
        #print (y_test.head())
        mse_scores.append(mse(y_test, y_pred))
        #print(mse_scores)
        cod_scores.append(cod(y_test, y_pred))
    return mse_scores, cod_scores

###-----------------------------
# ETL
df=cudf.read_csv("df.csv")
df.dtypes
df["Unnamed: 0"]= df["Unnamed: 0"].astype('float64')
df.dtypes

###-------------------------
# Training
n_runs = 1
clf = Ridge()
mse_scores, cod_scores = train_and_score(df, clf, n_runs=n_runs)
print(f"median MSE ({n_runs} runs): {np.median(mse_scores)}")
print(f"median COD ({n_runs} runs): {np.median(cod_scores)}")
```

I'll edit this with a google drive link to the `df..csv`

LINK TO `df.csv` for troubleshooting (2GB): https://drive.google.com/file/d/1NqvF5o8DowlfbvUxFHbN2MM9VXA9zaLS/view?usp=sharing

**Comment by taureandyernv** [comment]
@robocopnixon also had this issue in the MSE calc if his GTC notebook.  He discovered that it is an API behavior change.  You now have to reset the column indexes.  This was the additional code that he used to solve it: `.reset_index(drop=True)`

```
return ((y_test - y_pred) ** 2).mean() #old code
return ((y_test.reset_index(drop=True) - y_pred.reset_index(drop=True)) ** 2).mean() # new required patch code
```
Currently, we don't have a mean_squared_error function like skl, so someone has to write theirs form scratch as above.  *My new question: is this the expected behavior that we want, as it is different from last release?*  If yes, we can close the issue.

For reference, this is how sklearn does the output error in their function from https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/metrics/regression.py
```
output_errors = np.average((y_true - y_pred) ** 2, axis=0,
                               weights=sample_weight)
```

**Comment by kkraus14** [comment]
> During the MSE calculation, the portion `y_test - y_pred` returns null values for the entire column.

Is there any way to reduce the example above to just constructing input and running this function to show where it goes from not null to null erroneously?

**Comment by robocopnixon** [comment]
@kkraus14 this is the result of doing arithmetic on series with non-matching indexes. Do we think this is an error? It changed how some early code worked, but people should be mindful that they're comparing series along equal indexes.

**Comment by kkraus14** [comment]
@robocopnixon Was about to say the same. This is the correct behavior, `cuml.preprocessing.model_selection.train_test_split` should likely reset the index and then all will be well.

**Comment by robocopnixon** [comment]
@kkraus14 @taureandyernv IMHO we should just document how our basic functions require equality of index, including in my revamp of the cheat sheet this week.

**Comment by kkraus14** [comment]
> @kkraus14 @taureandyernv IMHO we should just document how our basic functions require equality of index, including in my revamp of the cheat sheet this week.

In the cuML side? In cuDF they do not require equality of index because we align them, which is the whole point of this functionality.

**Comment by kkraus14** [comment]
Since this isn't a cuDF issue I'm going to close this.
