### ISSUE TITLE
[BUG] RMM segv on drop_duplicates

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cudf#2636]
**Describe the bug**
Repeated calls to read_csv followed by drop_duplicates cause a core dump.  Seems to only occur with the pool allocator.

**Steps/Code to reproduce bug**
[demonstrate_error.tar.gz](https://github.com/rapidsai/cudf/files/3520961/demonstrate_error.tar.gz)

The attached sample code demonstrates the issue.  If you extract the tarball and run the python script it fails with a segv.  It fails at different times during the execution.  Occasionally the python script will run to completion without a failure.  The python code is duplicated here (the tarball also contains the test data):

```
import gc
import cudf
from librmm_cffi import librmm as rmm
from librmm_cffi import librmm_config as rmm_cfg

def test_symmetrize(graph_file):
    gc.collect()

    rmm.finalize()
    rmm_cfg.use_managed_memory = True
    rmm_cfg.use_pool_allocator = True
    rmm.initialize()

    assert(rmm.is_initialized())

    cu_M = cudf.read_csv(graph_file, delimiter=' ',
                         dtype=['int32', 'int32', 'float32'], header=None)

    dd_gdf = cu_M.drop_duplicates()
    print("orig = ", len(cu_M), ", dd = ", len(dd_gdf))


#
# Run test
#
file = 'email-Eu-core.csv'

for i in range(400):
    print(i)
    test_symmetrize(file)

print('success')
```

**Expected behavior**
NOTE: There are no duplicates in this particular data set.  Expectation is that this will read a csv into a data frame and that both data frames will be equal.  This is a simplified example from a more complex python code, but it demonstrates the segv.  The code should run to completion without failures every time it executes.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda and from source (branch-0.10) both fail

**Environment details**
[demonstrate_error-env.txt](https://github.com/rapidsai/cudf/files/3520960/demonstrate_error-env.txt)

**Additional context**

**Comment by harrism** [comment]
Can you put the code directly in the issue so it's easy to inspect?

**Comment by jrhemstad** [comment]
99% certain that this was caused by the issues I fixed here: https://github.com/rapidsai/cudf/pull/3295
