### ISSUE TITLE
[BUG] groupby returns wrong results with >2^17 rows

### ISSUE THREAD

**Issue by takeshi-yoshimura** [rapidsai/cudf#2646]
**Describe the bug**
I am testing upstream cudf, and an example notebook ([https://github.com/rapidsai/notebooks-contrib/blob/master/intermediate_notebooks/E2E/mortgage/mortgage_e2e.ipynb](https://github.com/rapidsai/notebooks-contrib/blob/master/intermediate_notebooks/E2E/mortgage/mortgage_e2e.ipynb)) went into an infinite loop at merge operations.
I found groupby in the upstream cudf returns different results from cudf 0.7.2.
I observed this problem in both x86 and ppc64le Ubuntu 18.04.

**Steps/Code to reproduce bug**
```python
>>> import cudf
>>> print(cudf.__version__)
0.9.0a+2638.gd45a14503
>>> df = cudf.DataFrame([('a', list(range(2**17))), ('b', list(range(2**17)))])
>>> df.groupby('a').max()
             b
a             
0            0
121773  121773
1            1
121773  121773
2            2
...        ...
121773  121773
65534    65534
121773  121773
65535    65535
121773  121773

[131072 rows x 1 columns]
>>> 

```
**Expected behavior**
groupby should return unique values for column 'a'.
I observed this when we use larger than 2**17 rows. integer overflows?

**Environment overview (please complete the following information)**
 - Environment location: [Docker (x86_64, ppc64le)]
 - Method of cuDF install: [from source]

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit d45a145031dcac7bdc5ac16f1dda47018283ab15 (HEAD, origin/branch-0.9, origin/HEAD)
     Merge: 7c94748a9 ec2e75b45
     Author: Mark Harris <mharris@nvidia.com>
     Date:   Tue Aug 13 17:49:12 2019 +1000
     
     Merge pull request #2431 from mluukkainen/fix_root_owned_directories
     
     Fix local build creating directories owned by root
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     97e046f4f4883dc5612dd14bc063e53dd623a6cf thirdparty/jitify (remotes/origin/feature/api_v2)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
     NAME="Ubuntu"
     VERSION="18.04.2 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.2 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux s7fx1tyos 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Aug 21 08:23:50 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-PCIE...  On   | 00000000:AF:00.0 Off |                    0 |
     | N/A   32C    P0    24W / 250W |      0MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              72
     On-line CPU(s) list: 0-71
     Thread(s) per core:  2
     Core(s) per socket:  18
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
     Stepping:            4
     CPU MHz:             1000.233
     CPU max MHz:         3700.0000
     CPU min MHz:         1000.0000
     BogoMIPS:            4600.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            25344K
     NUMA node0 CPU(s):   0-17,36-53
     NUMA node1 CPU(s):   18-35,54-71
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/tyos/anaconda3/envs/p9cudf/bin/cmake
     cmake version 3.14.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/tyos/anaconda3/envs/p9cudf/bin/python
     Python 3.6.9
     
     ***Environment Variables***
     PATH                            : /home/tyos/anaconda3/envs/p9cudf/bin:/home/tyos/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/tyos/anaconda3/envs/p9cudf
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/tyos/anaconda3/condabin/conda
     # packages in environment at /home/tyos/anaconda3/envs/p9cudf:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     attrs                     19.1.0                   py36_1
     backcall                  0.1.0                    py36_0
     blas                      1.0                         mkl
     bleach                    3.1.0                    py36_0
     bokeh                     1.3.4                    py36_0
     boost                     1.67.0                   py36_4
     boost-cpp                 1.67.0               h14c3975_4
     brotli                    1.0.7                he6710b0_0
     bzip2                     1.0.8                h7b6447c_0
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py36_1    conda-forge
     cffi                      1.12.3           py36h2e261b9_0
     click                     7.0                      py36_0
     cloudpickle               1.2.1                      py_0
     cmake                     3.14.0               h52cb24c_0
     cmake-setuptools          0.1.3                    pypi_0    pypi
     cudatoolkit               10.1.168                      0
     cudf                      0.9.0a0+2103.g260c249bb          pypi_0    pypi
     cython                    0.29.12          py36he6710b0_0
     cytoolz                   0.10.0           py36h7b6447c_0
     dask-core                 2.2.0                      py_0
     dbus                      1.13.6               h746ee38_0
     decorator                 4.4.0                    py36_1
     defusedxml                0.6.0                      py_0
     distributed               2.2.0                      py_1
     dlpack                    0.2                  he1b5a44_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     entrypoints               0.3                      py36_0
     expat                     2.2.6                he6710b0_0
     flatbuffers               1.11.0               he6710b0_0
     fontconfig                2.13.0               h9420a91_0
     freetype                  2.9.1                h8a8886c_1
     gflags                    2.2.2                he6710b0_0
     glib                      2.56.2               hd408876_0
     glog                      0.3.5                hf484d3e_1
     gmp                       6.1.2                h6c8ec71_1
     gst-plugins-base          1.14.0               hbbd80ab_1
     gstreamer                 1.14.0               hb453b48_1
     heapdict                  1.0.0                    py36_2
     icu                       58.2                 h9c2bf20_1
     intel-openmp              2019.4                      243
     ipykernel                 5.1.1            py36h39e3cac_0
     ipython                   7.7.0            py36h39e3cac_0
     ipython_genutils          0.2.0                    py36_0
     ipywidgets                7.5.1                      py_0
     jedi                      0.13.3                   py36_0
     jinja2                    2.10.1                   py36_0
     jpeg                      9b                   h024ee3a_2
     jsonschema                3.0.1                    py36_0
     jupyter                   1.0.0                    py36_7
     jupyter_client            5.3.1                      py_0
     jupyter_console           6.0.0                    py36_0
     jupyter_core              4.5.0                      py_0
     krb5                      1.16.1               h173b8e3_7
     libboost                  1.67.0               h46d08c1_4
     libcurl                   7.65.2               h20c2e04_0
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.8                h1ba5d50_0
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     libopenblas               0.3.6                h5a2b251_1
     libpng                    1.6.37               hbc83047_0
     libprotobuf               3.5.2                h6f1eeef_0
     libprotobuf-static        3.7.1                hd408876_0
     librmm-cffi               0.9.0                    pypi_0    pypi
     libsodium                 1.0.16               h1bed415_0
     libssh2                   1.8.2                h1ba5d50_0
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.10               h2733197_2
     libuuid                   1.0.3                h1bed415_2
     libxcb                    1.13                 h1bed415_1
     libxml2                   2.9.9                hea5a465_1
     line_profiler             2.1.2            py36h14c3975_0
     llvmlite                  0.29.0           py36hd408876_0
     locket                    0.2.0                    py36_1
     lz4-c                     1.8.1.2              h14c3975_0
     markupsafe                1.1.1            py36h7b6447c_0
     mistune                   0.8.4            py36h7b6447c_0
     mkl                       2019.4                      243
     mkl_fft                   1.0.12           py36ha843d7b_0
     mkl_random                1.0.2            py36hd81dba3_0
     msgpack-python            0.6.1            py36hfd86e86_1
     nbconvert                 5.5.0                      py_0
     nbformat                  4.4.0                    py36_0
     ncurses                   6.1                  he6710b0_1
     notebook                  6.0.0                    py36_0
     numba                     0.45.1           py36h962f231_0
     numpy                     1.16.4           py36h7e9f1db_0
     numpy-base                1.16.4           py36hde5b4d6_0
     nvstrings-cudaunknown     0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                     py36_0
     openssl                   1.1.1c               h516909a_0    conda-forge
     orc                       1.5.1                hdbcaa40_0
     packaging                 19.0                     py36_0
     pandas                    0.25.0           py36he6710b0_0
     pandoc                    2.2.3.2                       0
     pandocfilters             1.4.2                    py36_1
     parso                     0.5.0                      py_0
     partd                     1.0.0                      py_0
     pcre                      8.43                 he6710b0_0
     pexpect                   4.7.0                    py36_0
     pickleshare               0.7.5                    py36_0
     pillow                    6.1.0            py36h34e0f95_0
     pip                       19.1.1                   py36_0
     prometheus_client         0.7.1                      py_0
     prompt_toolkit            2.0.9                    py36_0
     protobuf                  3.5.2            py36hf484d3e_1
     psutil                    5.6.3            py36h7b6447c_0
     ptyprocess                0.6.0                    py36_0
     py-boost                  1.67.0           py36h04863e7_4
     pyarrow                   0.14.1                   pypi_0    pypi
     pycparser                 2.19                     py36_0
     pygments                  2.4.2                      py_0
     pyparsing                 2.4.0                      py_0
     pyqt                      5.9.2            py36h05f1152_2
     pyrsistent                0.14.11          py36h7b6447c_0
     python                    3.6.9                h265db76_0
     python-dateutil           2.8.0                    py36_0
     pytz                      2019.1                     py_0
     pyyaml                    5.1.1            py36h7b6447c_0
     pyzmq                     18.0.0           py36he6710b0_0
     qt                        5.9.7                h5867ecd_1
     qtconsole                 4.5.2                      py_0
     rapidjson                 1.1.0                h6bb024c_0
     readline                  7.0                  h7b6447c_5
     rhash                     1.3.8                h1ba5d50_0
     send2trash                1.5.0                    py36_0
     setuptools                41.0.1                   py36_0
     sip                       4.19.8           py36hf484d3e_0
     six                       1.12.0                   py36_0
     snappy                    1.1.7                hbae5bb6_3
     sortedcontainers          2.1.0                    py36_0
     sqlite                    3.29.0               h7b6447c_0
     tbb                       2019.7               hc9558a2_0    conda-forge
     tblib                     1.4.0                      py_0
     terminado                 0.8.2                    py36_0
     testpath                  0.4.2                    py36_0
     thrift-cpp                0.11.0               h02b749d_3
     tk                        8.6.8                hbc83047_0
     toolz                     0.10.0                     py_0
     tornado                   6.0.3            py36h7b6447c_0
     traitlets                 4.3.2                    py36_0
     wcwidth                   0.1.7                    py36_0
     webencodings              0.5.1                    py36_1
     wheel                     0.33.4                   py36_0
     widgetsnbextension        3.5.0                    py36_0
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7                had09818_2
     zeromq                    4.3.1                he6710b0_3
     zict                      1.0.0                      py_0
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.3.7                h0b5b093_0
     
</pre></details>

**Additional context**

**Comment by shwina** [comment]
Could you please try with the latest nightly? This should have been fixed recently:

https://github.com/rapidsai/cudf/pull/2604

**Comment by takeshi-yoshimura** [comment]
Oh, I didn't realize the fix. I confirmed the problem was resolved. Thank you!
