### ISSUE TITLE
[BUG] Unable to read CSV from remote url

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/cudf#2650]
**Describe the bug**
I am unable to load a csv file from a remote HTTPS url. When attempting it seems to download the file but then give a `FileNotFoundError` error.

The file definitely exists as I can download it myself and load it from a local path.

**Steps/Code to reproduce bug**

```console
$ conda create -n dask-cudf-remote -c nvidia -c rapidsai -c conda-forge python=3.7 ipython dask cudf dask-cudf distributed   
$ conda activate dask-cudf-remote
$ pip install git+https://github.com/rapidsai/dask-cuda requests --upgrade
```

```python
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()

import distributed
client = distributed.Client(cluster)

import dask_cudf
gdf = dask_cudf.read_csv('https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-01.csv')
```

```python-traceback
FileNotFoundError: https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-01.csv
```

**Expected behavior**
I would expect the dataframe to be loaded successfully.

**Additional information**
I also tried a different protocol and get the same issue.

```console
$ pip install awscli
$ aws configure  # Set up credentials here
$ conda install -c conda-forge -y s3fs
```

```python
# Create cluster as above

gdf = dask_cudf.read_csv('s3://nyc-tlc/trip+data/yellow_tripdata_2019-01.csv') 
```

```python-traceback
FileNotFoundError: nyc-tlc/trip+data/yellow_tripdata_2019-01.csv
```

**Comment by ayushdg** [comment]
I can also reproduce with Dask (Not dask-cudf): 
```
>>> from dask import dataframe as dd
>>> df = dd.read_csv('https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2019-01.csv')
>>> df = dd.read_csv("s3://nyc-tlc/trip+data/yellow_tripdata_2019-01.csv",storage_options={'anon':True})
```
with `FileNotFoundError`

**Comment by jacobtomlinson** [comment]
Oh interesting I hadn't considered that! I'll raise another issue on Dask.

Thanks for catching my bug in the S3 example. Sneaky space.

**Comment by jacobtomlinson** [comment]
Related to dask/dask#5310

**Comment by kkraus14** [comment]
Fixed in https://github.com/dask/dask/issues/5310

**Comment by Anagha2299** [comment]
import wmi
import os
import subprocess
import re
import socket, sys
import pexpect

def main():
    host="Acer-PC"
    username="NIVI"
    password="NIVI123"
    server =connects(host, username, password)
    s = socket.socket()
    s.settimeout(5)
    print(server.run_remote('hostname'))

class connects:

    def __init__(self, host, username, password, s = socket.socket()):
        self.host=host
        self.username=username
        self.password=password
        self.s=s

        try:
            self.connection= wmi.WMI(self.host, user=self.username, password=self.password)
            self.s.connect(('10.61.0.50', 25))
            print ("Connection established")
        except:
            print ("Could not connect to machine")

    def run_remote(self, cmd, minimized=True):
        call=subprocess.check_output(cmd, shell=True,stderr=subprocess.STDOUT )
        print ("call")

main() 



Error:
Could not connect to machine
call
None


Can you please help me to solve this errors I am beginner in python.
