### ISSUE TITLE
[BUG] Running `dir` on a cuDF DataFrame errors out

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#2656]
**Describe the bug**

Running `dir` on a `cudf.DataFrame` throws an exception.

**Steps/Code to reproduce bug**

```python
import pandas as pd
import cudf

df = pd.DataFrame({"a": range(10)})
cdf = cudf.from_pandas(df)

dir(cdf)
```

This results in the following exception.

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-241127bd7e45> in <module>
      5 cdf = cudf.from_pandas(df)
      6 
----> 7 dir(cdf)

~/miniconda/envs/cumldev/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in __dir__(self)
    212         o = set(dir(type(self)))
    213         o.update(self.__dict__)
--> 214         o.update(c for c in self.columns if
    215                  (isinstance(c, pd.compat.string_types) and
    216                   pd.compat.isidentifier(c)))

~/miniconda/envs/cumldev/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in <genexpr>(.0)
    213         o.update(self.__dict__)
    214         o.update(c for c in self.columns if
--> 215                  (isinstance(c, pd.compat.string_types) and
    216                   pd.compat.isidentifier(c)))
    217         return list(o)

AttributeError: module 'pandas.compat' has no attribute 'string_types'
```

**Expected behavior**

A list of all attributes on the object would be returned

**Environment overview (please complete the following information)**
 - Environment location: DGX
 - Method of cuDF install: conda

**Environment details**

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2018-03-20"
     DGX_SWBUILD_VERSION="3.1.6"
     DGX_COMMIT_ID="1b0f58ecbf989820ce745a9e4836e1de5eea6cfd"
     DGX_SERIAL_NUMBER=QTFCOU822000C
     
     DGX_OTA_VERSION="3.1.7"
     DGX_OTA_DATE="Mon Jul  2 18:36:07 PDT 2018"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
     NAME="Ubuntu"
     VERSION="16.04.5 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.5 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux dgx15 4.4.0-135-generic #161-Ubuntu SMP Mon Aug 27 10:45:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Aug 21 14:41:02 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 396.44                 Driver Version: 396.44                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   35C    P0    55W / 300W |   1869MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   34C    P0    43W / 300W |     11MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   37C    P0    55W / 300W |   9293MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   34C    P0    55W / 300W |   9793MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   32C    P0    42W / 300W |     11MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   34C    P0    44W / 300W |     11MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   35C    P0    43W / 300W |     11MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   31C    P0    42W / 300W |     11MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0       772      C   ...rkham/miniconda/envs/cumldev/bin/python   496MiB |
     |    0     67182      C   ...len/miniconda3/envs/cudf-dev/bin/python  1360MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                80
     On-line CPU(s) list:   0-79
     Thread(s) per core:    2
     Core(s) per socket:    20
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 79
     Model name:            Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:              1
     CPU MHz:               3034.281
     CPU max MHz:           3600.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              4391.63
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              51200K
     NUMA node0 CPU(s):     0-19,40-59
     NUMA node1 CPU(s):     20-39,60-79
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.12.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/nfs/jkirkham/miniconda/envs/cumldev/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/nfs/jkirkham/miniconda/envs/cumldev/bin:/home/nfs/jkirkham/miniconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   : /usr/local/cuda-9.2//nvvm/lib64/libnvvm.so
     NUMBAPRO_LIBDEVICE              : /usr/local/cuda-9.2//nvvm/libdevice
     CONDA_PREFIX                    : /home/nfs/jkirkham/miniconda/envs/cumldev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/nfs/jkirkham/miniconda/condabin/conda
     # packages in environment at /home/nfs/jkirkham/miniconda/envs/cumldev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    defaults
     aiohttp                   3.5.4            py37h14c3975_0    conda-forge
     alembic                   1.0.11                     py_0    conda-forge
     arrow-cpp                 0.12.1           py37h0e61e49_0    conda-forge
     asn1crypto                0.24.0                py37_1003    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     blas                      2.12                   openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     blinker                   1.4                        py_1    conda-forge
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.68.0            h11c811c_1000    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py37_1    conda-forge
     certipy                   0.1.3                      py_0    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.1                      py_0    conda-forge
     configurable-http-proxy   4.1.0                  node11_1    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               9.2                           0    defaults
     cudf                      0.8.0                    py37_0    rapidsai
     cudnn                     7.6.0                 cuda9.2_0    defaults
     cuml                      0.8.0            cuda9.2_py37_0    rapidsai
     cupy                      6.2.0            py37h6adefed_0    jakirkham/label/cupy
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.2.0                      py_0    conda-forge
     dask-core                 2.2.0                      py_0    conda-forge
     dask-cuda                 0.8.0                    py37_0    rapidsai
     dask-cudf                 0.8.0                    py37_0    rapidsai
     dask-cuml                 0.8.0                    py37_0    rapidsai
     dask-glm                  0.1.0                         0    conda-forge
     dask-labextension         1.0.3                      py_0    conda-forge
     dask-ml                   0.13.0                     py_0    conda-forge
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     distributed               2.2.0                      py_1    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastrlock                 0.4             py37hf484d3e_1000    conda-forge
     fontconfig                2.13.1            he4413a7_1000    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.4.1                      py_0    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     glib                      2.58.3            h6f030ca_1002    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     icu                       58.2              hf484d3e_1000    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
     ipython                   7.7.0            py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1                      py_0    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.0.2                    py37_0    conda-forge
     jupyter                   1.0.0                      py_2    conda-forge
     jupyter-server-proxy      1.1.0                      py_0    conda-forge
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_console           6.0.0                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     jupyterhub                1.0.0                    py37_0    conda-forge
     jupyterlab                1.0.5                    py37_0    conda-forge
     jupyterlab_server         1.0.0                      py_1    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libcudf                   0.8.0                 cuda9.2_0    rapidsai
     libcuml                   0.8.0                 cuda9.2_0    rapidsai
     libcumlmg                 0.0.0.dev0         cuda10.0_374    nvidia
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0    defaults
     libgfortran-ng            7.3.0                hdf63c60_0    defaults
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               12_openblas    conda-forge
     liblapacke                3.8.0               12_openblas    conda-forge
     libnvstrings              0.8.0                 cuda9.2_0    rapidsai
     libopenblas               0.3.7                h6e990d7_0    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.6.1             hdbcaa40_1001    conda-forge
     librmm                    0.8.0                 cuda9.2_0    rapidsai
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0    defaults
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.9                h13577e0_2    conda-forge
     llvmlite                  0.29.0           py37hf484d3e_0    numba
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     mako                      1.1.0                      py_0    conda-forge
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     multidict                 4.5.2           py37h14c3975_1000    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nbconvert                 5.6.0                      py_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1               cuda9.2_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nodejs                    11.14.0              he1b5a44_1    conda-forge
     notebook                  6.0.0                    py37_0    conda-forge
     numba                     0.45.1           py37h962f231_0    defaults
     numpy                     1.17.0           py37h95a1406_0    conda-forge
     nvstrings                 0.8.0                    py37_0    rapidsai
     oauthlib                  3.0.1                      py_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.0                       py_0    conda-forge
     pamela                    1.0.0                      py_0    conda-forge
     pandas                    0.25.0           py37hb3f55d8_0    conda-forge
     pandoc                    2.7.3                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         4    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pcre                      8.41              hf484d3e_1003    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.1.0            py37h6b7be26_1    conda-forge
     pip                       19.2.2                   py37_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     pyarrow                   0.12.1           py37hbbcf98d_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pycurl                    7.43.0.2         py37h16ce93b_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyjwt                     1.7.1                      py_0    conda-forge
     pynvml                    8.0.1                      py_0    conda-forge
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     pyqt                      5.9.2            py37hcca6a23_2    conda-forge
     pyrsistent                0.15.4           py37h516909a_0    conda-forge
     pysocks                   1.7.0                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     python-editor             1.0.4                      py_0    conda-forge
     pytz                      2019.2                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.0.2           py37h1768529_2    conda-forge
     qt                        5.9.7                h52cfd70_2    conda-forge
     qtconsole                 4.5.2                      py_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rmm                       0.8.0                    py37_0    rapidsai
     scikit-learn              0.21.3           py37hcdab131_0    conda-forge
     scipy                     1.3.1            py37h921218d_1    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.0.1                   py37_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     sip                       4.19.8          py37hf484d3e_1000    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlalchemy                1.3.6            py37h516909a_0    conda-forge
     sqlite                    3.29.0               hcee41ef_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            h0a07b25_1002    conda-forge
     tk                        8.6.9             hed695b0_1002    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.2                 py37_1000    conda-forge
     urllib3                   1.25.3                   py37_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.4                   py37_0    conda-forge
     widgetsnbextension        3.5.1                    py37_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     yarl                      1.3.0           py37h14c3975_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1005    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**
NA

**Comment by ayushdg** [comment]
@jakirkham What version of pandas are you running?

**Comment by kkraus14** [comment]
Anything less than 0.25 should resolve the problem and we've labelled the dependency as such. Closing the issue.
