### ISSUE TITLE
[BUG] ReadCSV for Timestamp columns returns an unexpected value

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#2657]
**Describe the bug**
A CSV file with columns of type = timestamp does not return epoch timestamps back. 

**Steps/Code to reproduce bug**
Input CSV : 
1,08/09/2016T01:02:03.04
2,08/09/2017T01:02:03.04

OR
1,08-09-2016T01:02:03.04
2,08-09-2017T01:02:03.04
 
OR
1,08-09-2016 01:02:03.04
2,08-09-2017 01:02:03.04
```
//add imports as needed
> val csvSchemaBuilder = ai.rapids.cudf.Schema.builder
> val b = csvSchemaBuilder.column(DType.INT32, "int").column(DType.TIMESTAMP, "ts").build
> val builder = CSVOptions.builder().hasHeader(false).build
> val table = Table.readCSV(b, builder, new File("/tmp/ts.csv"))

table: ai.rapids.cudf.Table = Table{columns=[ColumnVector{rows=2, type=TIMESTAMP, hostData=null, deviceData=BufferEncapsulator{type= DeviceMemoryBuffer, data= MemoryBuffer{address=0x7fa7a6c02c00, length=16}, valid= MemoryBuffer{address=0x7fa7a6c02e00, length=1}, offsets= null}, nullCount=0, cudfColumn=140357982820480}, ColumnVector{rows=2, type=TIMESTAMP, hostData=null, deviceData=BufferEncapsulator{type= DeviceMemoryBuffer, data= MemoryBuffer{address=0x7fa7a6c03000, length=16}, valid= MemoryBuffer{address=0x7fa7a6c03200, length=1}, offsets= null}, nullCount=0, cudfColumn=140357981275136}, ColumnVector{rows=2, type=TIMESTAMP, hostData=null, deviceData=BufferEncapsulator{type= DeviceMemoryBuffer, data= MemoryBuffer{address=0x7fa7a6c03400, length=16}, valid= Memo...

> table.getColumn(1)
ai.rapids.cudf.ColumnVector = ColumnVector{rows=2, type=TIMESTAMP, hostData=BufferEncapsulator{type= HostMemoryBuffer, data= MemoryBuffer{address=0x7fa7a39c0d00, length=16}, valid= MemoryBuffer{address=0x7fa7a39c17d0, length=1}, offsets= null}, deviceData=BufferEncapsulator{type= DeviceMemoryBuffer, data= MemoryBuffer{address=0x7fa7a6c03000, length=16}, valid= MemoryBuffer{address=0x7fa7a6c03200, length=1}, offsets= null}, nullCount=0, cudfColumn=140357981275136}

> table.getColumn(1).getLong(0)
 Long = 800902016001002003
```
which seems like a decimal encoded value. 

**Expected behavior**
It should return some sort of epoch timestamp that can be used to convert it back to any other timestamp formats applications might expect.

**Environment overview (please complete the following information)**
 - Environment location: Bare Metal
 - Method of cuDF install: conda
 
**Environment details**
N/A

**Additional context**
N/A

**Comment by mjsamoht** [comment]
Closing since #2697 is merged.

**Comment by abellina** [comment]
@mjsamoht This issue is not addressed by #2697, and so I am reopening. #2697 makes sure that the time unit is associated with the column, but doesn't address the bug reported here.

The issue, as @kuhushukla described, is that a timestamp column with values like: 
`2018-11-01T10:04:56.000`,

Is getting turned into a form of a numeric representation, which mostly follows the original string:
`2018011001010004056`

We expect instead a `date64` that was initialized with a millisecond epoch (as defined by that type):
`1572602696000`

**Comment by harrism** [comment]
@abellina can you test with the latest and see if this is still an issue? We need to verify if this is just a legacy code issue or if it still exists in 0.13/0.14.

**Comment by vuule** [comment]
I tested all three formats listed here: 
- 08/09/2016T01:02:03.04
- 08-09-2016T01:02:03.04
- 08-09-2016 01:02:03.04

The non-legacy CSV reader returns the correct value for all formats. Pretty sure this has been resolved, we can close this issue soon if there is no followup.

**Comment by harrism** [comment]
Closing. Please comment/ reopen if there is still an issue.
