### ISSUE TITLE
[BUG] cudf.Series.replace overrides input dtype to int64

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#2662]
cudf.Series.replace should preserve the input column's dtype.

Repro:
```
s = cudf.Series(np.zeros(5, dtype='int8'), dtype='int8')
s.dtype
```
This is as expected
```
dtype('int8')
```
Now actually calling replace..
```
s.replace(0, None).dtype
```
Unexpected result:
```
dtype: int64
```

**Comment by ayushdg** [comment]
The current approach upcasts everything to the type highest type of the series, `to_replace` and `replacement`. When the two arguments are scalars or python lists of ints/float. The column created from it will by default have a dtype of `np.int64` or `np.float64`.
eg:
```
a = cudf.Series(1)
a.dtype
dtype("int64")
```

Current pandas behavior is to retain the original series dtype even if the replacement is too big to fit in the dtype.
eg:
```
a = pd.Series(1,dtype="int8")
a.replace(1,129)
0   -127
dtype: int8
```

IMO we should not follow this. Ideal case would be checking/upcasting if replacement dtype elements would exceed the original series dtype, else retain.

**Comment by kkraus14** [comment]
Pushing to 0.11.
