### ISSUE TITLE
Blank Methods cuDF/stable [DOC]

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/cudf#2681]
## Report incorrect documentation

**Location of incorrect documentation**
cuDF stable API docs ([link](https://docs.rapids.ai/api/cudf/stable/))
[Screenshot](https://drive.google.com/file/d/0ByYiTnJ6uYaxMTVHTzRKVUE0ajhIQWJJbmVMUnhFaGZvODlR/view?usp=sharing) of main issue

**Describe the problems or issues found in the documentation**
- Extra/future methods left in blank table below main methods table
- `count(self, \*\*kwargs)` un-clickable & with blank description in main table

**Steps taken to verify documentation is incorrect**
Visited page multiple times over a number of days

**Suggested fix for documentation**
Fill in right column & merge to main table, or remove blank methods

**Comment by kkraus14** [comment]
@mike-wendt @dillon-cullinan I think the issue is just the lack of docstrings for these methods so no need for ops involvement at this point, thanks!
