### ISSUE TITLE
[BUG] df.index.min()/max() return type not in-line with Pandas 

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#2688]
cudf Dataframes with a DatetimeIndex return a `<class 'numpy.datetime64'>` on methods like `df.index.min()` or `df.index.max()`. 

Pandas returns a `<class 'pandas._libs.tslibs.timestamps.Timestamp'>` instead, compatible with Pandas Timedelta, which may be required to fallback onto in streaming operations, until cudf has a Timedelta of its own.

Code to reproduce this:
```
import cudf
import pandas as pd
import numpy as np

index = pd.DatetimeIndex(start='2000-01-01', end='2000-01-03', freq='1h')
df = cudf.DataFrame({'x': np.arange(len(index), dtype=float),
                     'y': np.arange(len(index), dtype=float) % 2},
                    index=index)
print(type(df.index.min()))
```

**Comment by kkraus14** [comment]
@chinmaychandak Our DatetimeIndex can be an arbitrary resolution whereas Pandas Timestamp types are always nanosecond resolution. If we had the `min` and `max` operations return Pandas Timestamp objects then we're doing typecasting, and if a user wants to chain that into another call then we'd have to do more typecasting unnecessarily. I'm going to mark this as `wontfix` and think it should be handled in the Streamz library instead if possible.
