### ISSUE TITLE
[BUG] Numeric Series replace returns incorrect result

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2695]
**Describe the bug**
Really weird bug with replace on numeric columns
**Steps/Code to reproduce bug**
```
import cudf
ser = cudf.Series([1,2,None,3])

for i in range(10):
    c = ser.replace([1,2,3],None)
    print(c)
```
```
0    null
1    null
2    null
3    null
dtype: int64
0    null
1    null
2    null
3    null
dtype: int64
0              0
1              0
2    17179869188
3              0
dtype: int64
0    null
1    null
2    null
3    null
dtype: int64
0              0
1              0
2    17179869188
3              0
dtype: int64
0    null
1    null
2    null
3    null
dtype: int64
0              0
1              0
2    17179869188
3              0
dtype: int64
0    null
1    null
2    null
3    null
dtype: int64
```
Note: I restarted and ran this snippet multiple times and the order of incorrect output seems to be same every time. First two runs are fine and then incorrect and correct output alternate.

---

Now making things weirder
```
import cudf
ser = cudf.Series([1,2,None,3])

for i in range(10):
    a = ser.replace([1],None)
    c = ser.replace([1,2,3],None)
    print(c)
```
Adding another unrelated replace before the buggy one
```
0    null
1    null
2    null
3    null
dtype: int64
0    null
1       0
2    null
3       0
dtype: int64
0    null
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0    null
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0    null
1       0
2    null
3       0
dtype: int64
0       0
1    null
2    null
3    null
dtype: int64
```
--- 
Another variation
```
for i in range(10):
    b = ser.replace([1,2],None)
    c = ser.replace([1,2,3],None)
    print(c)
```
```
0    null
1    null
2    null
3    null
dtype: int64
0    null
1    null
2    null
3       0
dtype: int64
0    null
1    null
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0    null
1    null
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0       0
1       0
2    null
3       0
dtype: int64
0    null
1    null
2    null
3       0
dtype: int64
0       0
1    null
2    null
3    null
dtype: int64
```
**Expected behavior**
Same output every time. All nulls

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
0.10 nightly dev docker

**Comment by kkraus14** [comment]
@shwina any ideas here?

**Comment by shwina** [comment]
No clue but can investigate. I do remember that I didn't give enough love to `replace` with nulls when I wrote the bindings. Assigning self.

**Comment by rgsl888prabhu** [comment]
@ayushdg Can you try removing the print and use something like following and let me know whether you come across same issue or not.

```
import cudf
import numpy as np
from cudf.tests.utils import assert_eq

ser = cudf.Series([1,2,3, None])
exp = cudf.Series([None, None, None, None], dtype=np.int64)
for i in range(3):
    c = ser.replace([1,2,3],None)
    assert_eq(exp, c)
```

**Comment by kkraus14** [comment]
@rgsl888prabhu confirmed that works without issue, increased the range to 1000 as well.

**Comment by rgsl888prabhu** [comment]
> @rgsl888prabhu confirmed that works without issue, increased the range to 1000 as well.

When there is no `print`, while creating `gdf_column`, the valid bits are always set to `0`, but when we use `print`, some time the valid bit contains garbage. which kind of leads to the issue.

Currently I am resolving the issue in libcudf which will take care of this issue in both cases, but I still wonder what `print` is triggering to cause issue.
