### ISSUE TITLE
[BUG] Dask_cudf agg on datetime column incorrectly updates granularity in dtype

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2705]
**Describe the bug**
Performing a aggregation (groupby or otherwise) incorrectly changes the dtype of the dataframe which does not match the dtype of the underlying data in terms of datetime granularity (ms, ms etc.)

**Steps/Code to reproduce bug**
```
import cudf
import dask_cudf
import numpy as np
df = cudf.DataFrame()
df['a'] = [1,2,3,4,5]
df['d'] = np.datetime64("2000-01-01")
ddf = dask_cudf.from_cudf(df,1)

print(ddf.dtypes)
print(ddf.head().dtypes)

a             int64
d    datetime64[ms]
dtype: object
a             int64
d    datetime64[ms]
dtype: object
```
Right now the dtype of both the dask dataframe and the underlying data is the same `datetime64[ms]`

```
ddf3 = ddf.groupby("a").d.min().to_frame()
print(ddf3.dtypes)
print(ddf3.head().dtypes)

d    datetime64[ns]
dtype: object
d    datetime64[ms]
dtype: object
``` 

The underlying data even after the aggregation has dtype `datetime64[ms]`. However the dtype of the Dask Dataframe has been updated to `datetime64[ns]` which does not represent the actual dtype of the data underneath.

Additionally 
`ddf3['d'] = ddf3['d'].astype("datetime64[ms]")` 
does not update the dtype of ddf3 which is still `datetime64[ns]`

__Why is this important__: In certain downstream tasks it causes the code to break with errors like for certain cases of the mortgage data.
```
ValueError: Metadata mismatch found in `from_delayed`.

Partition type: `cudf.dataframe.dataframe.DataFrame`
+-----------------+----------------+----------------+
| Column          | Found          | Expected       |
+-----------------+----------------+----------------+
| delinquency_180 | datetime64[ms] | datetime64[ns] |
| delinquency_30  | datetime64[ms] | datetime64[ns] |
| delinquency_90  | datetime64[ms] | datetime64[ns] |
| timestamp       | datetime64[ms] | datetime64[ns] |
+-----------------+----------------+----------------+
```

**Expected behavior**
Handle the dtypes properly

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
Dev container at adad23251cc70cf958948f

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit adad23251cc70cf958948f7a84ea11cbc68879d5 (HEAD -> branch-0.10, origin/branch-0.10, origin/HEAD)
     Merge: 8acb5eb 927d21c
     Author: Robert (Bobby) Evans <bobby@apache.org>
     Date:   Tue Aug 20 16:10:52 2019 -0500
     
     Merge pull request #2641 from revans2/fix-concat
     
     Make concat not lose time units and work with string categories
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     97e046f4f4883dc5612dd14bc063e53dd623a6cf thirdparty/jitify (remotes/origin/feature/api_v2)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux dt03 4.4.0-159-generic #187-Ubuntu SMP Thu Aug 1 16:28:06 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Aug 29 06:20:22 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla T4            Off  | 00000000:3B:00.0 Off |                    0 |
     | N/A   46C    P0    28W /  70W |  14013MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla T4            Off  | 00000000:5E:00.0 Off |                    0 |
     | N/A   46C    P0    27W /  70W |  13573MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla T4            Off  | 00000000:AF:00.0 Off |                    0 |
     | N/A   44C    P0    28W /  70W |  13573MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla T4            Off  | 00000000:D8:00.0 Off |                    0 |
     | N/A   44C    P0    28W /  70W |  13573MiB / 15079MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                64
     On-line CPU(s) list:   0-63
     Thread(s) per core:    2
     Core(s) per socket:    16
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
     Stepping:              4
     CPU MHz:               2095.103
     BogoMIPS:              4191.33
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              22528K
     NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
     NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp pti tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku md_clear flush_l1d
     
     ***CMake***
     /opt/conda/envs/rapids/bin/cmake
     cmake version 3.14.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin:/conda/bin:/conda/bin
     LD_LIBRARY_PATH                 : /opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     absl-py                   0.7.1                    py37_0    conda-forge
     aiohttp                   3.5.4            py37h14c3975_0    conda-forge
     arrow-cpp                 0.14.1           py37h6b969ab_0    conda-forge
     astor                     0.7.1                      py_0    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.1.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     blas                      1.1                    openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py37_1    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                      pypi_0    pypi
     cloudpickle               1.2.1                      py_0    conda-forge
     cmake                     3.14.5               hf94ab9c_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     cudatoolkit               10.0.130                      0    anaconda
     cudf                      0.10.0a0+706.gadad232          pypi_0    pypi
     cugraph                   0.10.0a0+72.g656a382          pypi_0    pypi
     cuml                      0.10.0a0+302.ge6f9780.dirty          pypi_0    pypi
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cycler                    0.10.0                     py_1    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.3.0                      py_0    conda-forge
     dask-core                 2.3.0                      py_0    conda-forge
     dask-cudf                 0.10.0a0+706.gadad232          pypi_0    pypi
     dask-glm                  0.1.0                         0    conda-forge
     dask-labextension         1.0.3                      py_0    conda-forge
     dask-ml                   1.0.0                      py_0    conda-forge
     dask-xgboost              0.1.5                    pypi_0    pypi
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     distributed               2.3.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastavro                  0.22.3           py37h516909a_0    conda-forge
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.4.1                      py_0    conda-forge
     gast                      0.2.2                      py_0    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glib                      2.58.3            h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.22.0           py37he9ae1f9_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     h5py                      2.9.0           nompi_py37h513d04c_1104    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1102    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     hypothesis                4.33.0                   py37_0    conda-forge
     icu                       64.2                 he1b5a44_0    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     importlib_metadata        0.18                     py37_0    conda-forge
     ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
     ipython                   7.3.0            py37h24bf2e0_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.0.2                    py37_0    conda-forge
     jupyter-server-proxy      1.1.0                      py_0    conda-forge
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     jupyterlab                1.0.7                    py37_0    conda-forge
     jupyterlab-nvdashboard    0.1.9                    pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     keras-applications        1.0.7                      py_1    conda-forge
     keras-preprocessing       1.0.9                      py_1    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     lapack                    3.6.1                ha44fe06_2    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libclang                  8.0.0                h6bb024c_0    rapidsai
     libcumlprims              0.9.0                cuda10.0_0    nvidia
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 7.3.0                hdf63c60_0    anaconda
     libgfortran               3.0.0                         1    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_0    anaconda
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               12_openblas    conda-forge
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm-cffi               0.10.0                   pypi_0    pypi
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              7.3.0                hdf63c60_0    anaconda
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.30.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.9                hee79883_2    conda-forge
     llvmlite                  0.29.0           py37hf484d3e_0    numba
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     make                      4.2.1             h14c3975_2004    conda-forge
     markdown                  3.1.1                      py_0    conda-forge
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     matplotlib                3.1.1                    py37_1    conda-forge
     matplotlib-base           3.1.1            py37he7580a8_1    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     mock                      3.0.5                    py37_0    conda-forge
     more-itertools            7.2.0                      py_0    conda-forge
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     multidict                 4.5.2           py37h14c3975_1000    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nbconvert                 5.6.0                      py_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.3                        py_0    conda-forge
     nodejs                    12.8.1               h10a4023_0    conda-forge
     nomkl                     2.0                           0    anaconda
     notebook                  6.0.0                    py37_0    conda-forge
     numba                     0.45.1          np116py37hf484d3e_0    numba
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     nvstrings-cuda100         0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.7                h6e990d7_1    conda-forge
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     pandoc                    2.7.3                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.41              hf484d3e_1003    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.1.0            py37h6b7be26_1    conda-forge
     pip                       19.2.2                   py37_0    conda-forge
     pluggy                    0.12.0                     py_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     protobuf                  3.8.0            py37he1b5a44_1    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.14.1           py37h8b68381_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     pyqt                      5.9.2            py37hcca6a23_2    conda-forge
     pyrsistent                0.15.4           py37h516909a_0    conda-forge
     pytest                    5.1.0                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     pytz                      2019.2                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.0.2           py37h1768529_2    conda-forge
     qt                        5.9.7                h0c104cb_3    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2019.08.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     scikit-learn              0.21.3           py37hcdab131_0    conda-forge
     scipy                     1.3.1            py37h921218d_2    conda-forge
     seaborn                   0.9.0                      py_1    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.0.1                   py37_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     sip                       4.19.8          py37hf484d3e_1000    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.29.0               hcee41ef_0    conda-forge
     statsmodels               0.10.1           py37hc1659b7_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     tensorboard               1.13.1                   py37_0    conda-forge
     tensorflow                1.13.1           py37h90a7d86_1    conda-forge
     tensorflow-estimator      1.13.0                     py_0    anaconda
     termcolor                 1.1.0                      py_2    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1002    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.2                 py37_1000    conda-forge
     umap-learn                0.3.10                   py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     werkzeug                  0.15.5                     py_0    conda-forge
     wheel                     0.33.4                   py37_0    conda-forge
     xgboost                   1.0.0rapidsdev0-SNAPSHOT          pypi_0    pypi
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     yarl                      1.3.0           py37h14c3975_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                    pypi_0    pypi
     zipp                      0.5.2                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1005    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

**Comment by rgsl888prabhu** [comment]
This issue has been resolved with the refactor 
```
>>> import cudf
>>> import dask_cudf
>>> import numpy as np
>>> df = cudf.DataFrame()
>>> df['a'] = [1,2,3,4,5]
>>> df['d'] = [np.datetime64("2000-01-01")]*5
>>> ddf = dask_cudf.from_cudf(df,1)
>>> 
>>> print(ddf.dtypes)
a            int64
d    datetime64[s]
dtype: object
>>> print(ddf.head().dtypes)
a            int64
d    datetime64[s]
dtype: object
>>> ddf3 = ddf.groupby("a").d.min().to_frame()
>>> print(ddf3.dtypes)
d    datetime64[s]
dtype: object
>>> print(ddf3.head().dtypes)
d    datetime64[s]
dtype: object

```
@ayushdg  please confirm

**Comment by ayushdg** [comment]
Confirmed this is resolved. Thanks for the ping @rgsl888prabhu 😄
