### ISSUE TITLE
[BUG] Cumsum on bool columns coerces all values to True after a True

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2708]
We should instead create an appropriately typed integer column, treating True as 1 and False as 0.

```python
import cudf
​
s = cudf.Series([False, True,False,True])
s.cumsum()
0    False
1     True
2     True
3     True
dtype: bool
```

```python
import pandas as pd
​
s = pd.Series([False, True,False,True])
s.cumsum()
0    0
1    1
2    1
3    2
dtype: int64
```

**Comment by beckernick** [comment]
This is a both a cuDF (Python) and libcuDF issue.

For libcuDF, it results from the `CUDF_EXPECTS`:

https://github.com/rapidsai/cudf/blob/6afa4e7f357203dffa52df076567ae1761ae05ac/cpp/src/reductions/scan.cu#L149-L151

From Python, we'll also need to relax the requirement that scan ops have identical input and output dtypes:

https://github.com/rapidsai/cudf/blob/6afa4e7f357203dffa52df076567ae1761ae05ac/python/cudf/cudf/core/column/numerical.py#L114-L117

**Comment by AK-ayush** [comment]
Hi @beckernick,
Since the expected datatype for resultant series is `int64`, this can be fixed by just adding one more condition in `series.cumsum()`.
change this line: 
https://github.com/rapidsai/cudf/blob/branch-0.10/python/cudf/cudf/core/series.py#L1787

to:
```python
if np.issubdtype(self.dtype, np.integer) or \
           np.issubdtype(self.dtype, np.bool):
```

**Comment by beckernick** [comment]
Thanks @AK-ayush ! You're right. This would solve the issue by abstracting away from it without adding too much complexity, which is probably a good short term approach. Would you like to submit a PR that also slightly updates the comment to explain why it's also including a bool dtype?

**Comment by AK-ayush** [comment]
Sure, I'll submit the fix for it.
