### ISSUE TITLE
[BUG] Value access of MultiIndex produces incorrect results

### ISSUE THREAD

**Issue by WhistleWhileYouWork** [rapidsai/cudf#2711]
**Describe the bug**
Basic value access of a two-level MultiIndex produces jumbled results, returning rows from other first level categories. This occurs whether you create the cudf dataframe from a pandas dataframe or create it via cudf.DataFrame(). Tested on cudf 0.9 and 0.10a, cudatoolkit 9.2 and 10.0, python 3.6.7 and 3.7.3. This is a regression from cudf 0.8.

**Steps/Code to reproduce bug**
```python
import numpy as np
import pandas as pd
import cudf
periods = [5, 4, 3]
first_level = ['a'] * periods[0] + ['b'] * periods[1] + ['c'] * periods[2]
second_level = list(range(1, periods[0] + 1)) + \
               list(range(1, periods[1] + 1)) + \
               list(range(1, periods[2] + 1))
tuples = list(zip(first_level, second_level))
index = pd.MultiIndex.from_tuples(tuples)
df = pd.DataFrame({'A': second_level, 'B': np.random.rand(sum(periods))}, index=index)
gdf = cudf.from_pandas(df)
# Uncomment these lines to initialize the dataframe in cudf directly
# the incorrect results will still be the same.
# index = cudf.MultiIndex.from_tuples(tuples)
# gdf = cudf.DataFrame({'A': second_level, 'B': np.random.rand(sum(periods))}, index=index)
print(gdf)
# Access of first level, no tuple
print(gdf.loc['a'].to_pandas())
print(gdf.loc['b'].to_pandas())
print(gdf.loc['c'].to_pandas())
# Access of first level only, using tuple
print(gdf.loc[('a', )].to_pandas())
# Access of first and second level, using tuple
print(gdf.loc[('a', 5)].to_pandas())
print(gdf.loc[('b', 1)].to_pandas())
```

Results:
```python
In [26]: print(gdf)
     A         B
a 1  1  0.479177
  2  2  0.984660
  3  3  0.878674
  4  4  0.573545
  5  5  0.256685
b 1  1  0.893322
  2  2  0.579766
  3  3  0.573205
  4  4  0.227897
c 1  1  0.282509
  2  2  0.928581
  3  3  0.432880

In [27]: # Access of first level, no tuple

In [28]: print(gdf.loc['a'].to_pandas())
     A         B
a 1  1  0.479177
b 4  4  0.227897
a 3  3  0.878674
  5  5  0.256685
b 2  2  0.579766

In [29]: print(gdf.loc['b'].to_pandas())
     A         B
a 2  2  0.984660
c 1  1  0.282509
  2  2  0.928581
  3  3  0.432880

In [30]: print(gdf.loc['c'].to_pandas())
     A         B
a 4  4  0.573545
b 1  1  0.893322
  3  3  0.573205

In [31]: # Access of first level only, using tuple

In [32]: print(gdf.loc[('a', )].to_pandas())
   A         B
1  1  0.479177
5  4  0.227897
2  3  0.878674
3  5  0.256685
4  2  0.579766

In [33]: # Access of first and second level, using tuple

In [34]: print(gdf.loc[('a', 5)].to_pandas())
     A         B
b 4  4  0.227897

In [35]: print(gdf.loc[('b', 1)].to_pandas())
     A         B
c 1  1  0.282509
```

**Expected behavior**
```python
gdf.loc['a']
# Should return
#    A         B
# 1  1  0.479177
# 2  2  0.984660
# 3  3  0.878674
# 4  4  0.573545
# 5  5  0.256685
gdf.loc[('a', 5)]
# Should return
# A         B
# 5  0.256685
```
**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux OZHOMEU 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Aug 29 23:23:06 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce GTX 1080    Off  | 00000000:01:00.0 Off |                  N/A |
     | 25%   30C    P8    16W / 240W |    174MiB /  8119MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      1324      G   /usr/lib/xorg/Xorg                           118MiB |
     |    0      1512      G   /usr/bin/gnome-shell                          53MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              8
     On-line CPU(s) list: 0-7
     Thread(s) per core:  2
     Core(s) per socket:  4
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               94
     Model name:          Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
     Stepping:            3
     CPU MHz:             4200.035
     CPU max MHz:         4200.0000
     CPU min MHz:         800.0000
     BogoMIPS:            8016.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            8192K
     NUMA node0 CPU(s):   0-7
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/s/miniconda3/envs/cudf_test/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/s/miniconda3/envs/cudf_test/bin:/home/s/miniconda3/condabin:/usr/local/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.0/lib64:/usr/local/cuda/extras/CUPTI/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/s/miniconda3/envs/cudf_test
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/s/miniconda3/condabin/conda
     # packages in environment at /home/s/miniconda3/envs/cudf_test:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     arrow-cpp                 0.14.1           py37h6b969ab_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_0    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.6.16            hecc5488_0    conda-forge
     certifi                   2019.6.16                py37_1    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     cudatoolkit               10.0.130                      0    anaconda
     cudf                      0.9.0                    py37_0    rapidsai
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     dlpack                    0.2                  he1b5a44_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     fastavro                  0.22.4           py37h516909a_0    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libcudf                   0.9.0                cuda10.0_0    rapidsai
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0    anaconda
     liblapack                 3.8.0               12_openblas    conda-forge
     libnvstrings              0.9.0                cuda10.0_0    rapidsai
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.9.0                cuda10.0_0    rapidsai
     libstdcxx-ng              9.1.0                hdf63c60_0
     llvmlite                  0.29.0           py37hf484d3e_0    numba
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     numba                     0.45.1          np116py37hf484d3e_0    numba
     numpy                     1.16.4           py37h95a1406_0    conda-forge
     nvstrings                 0.9.0                    py37_0    rapidsai
     openssl                   1.1.1c               h516909a_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pyarrow                   0.14.1           py37h8b68381_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     pytz                      2019.2                     py_0    conda-forge
     re2                       2019.08.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rmm                       0.9.0                    py37_0    rapidsai
     setuptools                41.2.0                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sqlite                    3.29.0               hcee41ef_1    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1002    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     zlib                      1.2.11            h516909a_1005    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**
**General observations:**
The length of the results are correct: `gdf.loc['a']` returns 5 results, `gdf.loc['b']` returns 4 results and so on.

**Observations of results for non-tuple access:**
First level index is returned with the results (this is inconsistent with pandas).
Column `A` values correspond with the second level index so only the overall order is jumbled.
Each time this example is run in-full, the order of the incorrect results are always the same.

**Observations of results for first level tuple access:**
Only the second level index is returned with the results (this is consistent with pandas).
The second level index is even more incorrect compared to not using a tuple.
The order of the _values_ however are the same as without using a tuple.

**Observations of results for first and second level tuple access:**
Results are incorrect.

**Comment by thomcom** [comment]
Thanks @WhistleWhileYouWork. I have one other incorrect case where we return an incorrectly shaped MultiIndex access result, which I'm documenting here.

```
    gdf = cudf.DataFrame(
        {"x": np.arange(10), "y": np.arange(10), "z": np.arange(10)}
    )
    gdg = gdf.groupby(["x", "y"]).min()
    gdgT = gdg.T
    pdgT = gdgT.to_pandas()
    # gdgT[(0, 0)] returns a DataFrame
    # pdgT[(0, 0)] returns a Series
    assert_eq(gdgT[(0, 0)], pdgT[(0, 0)])
```

**Comment by rgsl888prabhu** [comment]
Don't see this issue anymore in 0.14, this issue can be closed.
