### ISSUE TITLE
[FEA] Pandas feature parity: support itertuples attribute for cudf Dataframe

### ISSUE THREAD

**Issue by animohan** [rapidsai/cudf#2723]
**Is your feature request related to a problem? Please describe.**
Request to support  itertuples attribute for a cudf DataFrame similar to a pandas DataFrame. 

Some libraries,  like jupyter-gmaps<https://jupyter-gmaps.readthedocs.io/en/v0.3.3/gmaps.html> use itertuples; Hence it is not easy to swap pandas dataframe with cudf dataframe to get accelerated mapping.

**Additional context**
Pandas details: 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html

**Comment by kkraus14** [comment]
@animohan `DataFrame.itertuples` returns an iterator of Python namedtuple objects where you're leaving the ability to accelerate things using GPUs. We could add the function purely for compatibility reasons, but anything done with the tuples will not be accelerated in any way.

**Comment by animohan** [comment]
@kkraus14 : Appreciate the feedback. 
It might be still useful for parity with pandas. For e.g in the jupyter-maps example mentioned above, read_csv would be gpu accelerated if we replaced pandas with cudf.

**Comment by kkraus14** [comment]
I don't think it makes sense for us to implement this as we can't give any GPU acceleration and will encourage inefficient code paths, but we should "poison" the method to raise a clearer error.
