### ISSUE TITLE
[DOC] Documentation request: cuDF + AWS SageMaker

### ISSUE THREAD

**Issue by mstewart141** [rapidsai/cudf#2726]
## cuDF + AWS SageMaker
First off, thanks for the great project. 

SageMaker is a common tool for prototyping GPU oriented logic on aws. I tried to set up cuDF in a SageMaker (jupyter) notebook but did not have much like tweaking all the knobs to align. I was not able to get an install working. I believe it would be valuable to have a tutorial/docs on how to get cuDF working in SageMaker, as it is the entrypoint for a lot of GPU work.

There are good docs for installation in general (thank you!) but a more tailored blurb would still be greatly appreciated. The generic install docs did not get me very close to success, though certainly there is a way to do it, no doubt.

This PR seems to be related, in part: https://github.com/rapidsai/cudf/issues/1972

**Steps taken to search for needed documentation**
Reviewed rapids website and cudf github.

**Comment by ivenzor** [comment]
@mstewart141 I haven't been able to dedicate much time to this but I'm able to install rapids on sagemaker and do some stuff:

df = cudf.DataFrame()
df['key'] = [0, 1, 2, 3, 4]
df['val'] = [float(i + 10) for i in range(5)]  # insert column
print(df)

   _key   val
0    0  10.0
1    1  11.0
2    2  12.0
3    3  13.0
4    4  14.0_

**Comment by mstewart141** [comment]
@ivenzor no worries, thank you for taking the time to look. would you be able to post the steps you took to get there?

**Comment by ivenzor** [comment]
@mstewart141 it's not very good, but I hope it's somewhat useful:
https://github.com/ivenzor/Sagemaker-Rapids/blob/master/README.md

**Comment by mstewart141** [comment]
thanks, super useful! much appreciated

**Comment by kkraus14** [comment]
cc @randerzander

**Comment by ivenzor** [comment]
It's now published:
https://towardsdatascience.com/quick-install-guide-nvidia-rapids-blazingsql-on-aws-sagemaker-cb4ddd809bf5
