### ISSUE TITLE
CSV reader test not checking categorical column

### ISSUE THREAD

**Issue by sklam** [rapidsai/cudf#274]
This test
https://github.com/gpuopenanalytics/pygdf/blob/f80748da0495e5b1080628e9831157835d3f9ebd/pygdf/tests/test_csvreader.py#L96-L110

is missing `pd.util.testing.assert_frame_equal(df, out.to_pandas())`.

But when added, it reveals that the category column from pygdf has int32 type.  How do you read categories from libgdf.read_csv?

**Comment by kkraus14** [comment]
@sklam Currently the CSV reader hashes string columns you mark as "category" and returns an int32. As we introduce additional String support into libgdf and pygdf this will be updated to better support reversing the hash to a String, and importing/exporting to normal Arrow/Pandas enumeration based Categoricals/Dictionaries.

**Comment by kkraus14** [comment]
Closing this as question was answered.
