### ISSUE TITLE
[BUG] NVCategory get_value and get_value_bounds have race conditions

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#2755]
**Describe the bug**
`NVCategory::get_value` and `NVCategory::get_value_bounds` both have code that copies a value from the device to the host asynchronously and then reads the value before synchronizing with the device.  In `get_value`:
```
    int rtn = -1;
    if( d_map )
        CUDA_TRY(cudaMemcpyAsync(&rtn,d_map+index,sizeof(int),cudaMemcpyDeviceToHost))
    return rtn;
```

and in `get_value_bounds`:
```
    int first = 0; // get the position back into host memory
    CUDA_TRY(cudaMemcpyAsync(&first,keys.data().get(),sizeof(int),cudaMemcpyDeviceToHost))
    rtn.first = first-1; // range is always
```

**Expected behavior**
I would expect these to be synchronous `cudaMemcpy` calls since the host memory is being accessed immediately afterwards.

**Comment by davidwendt** [comment]
Using `cudaMemcpy` contains a `cudaDeviceSynchronize` which waits on all streams across the whole device.
The correct solution looks to be to add a call to `cudaStreamSynchronize(0)` after the async call.

**Comment by jlowe** [comment]
Looking for other instances where a device-to-host async transfer is used in NVCategory, there are other places where a parameter passed by the caller is asynchronously being updated when the method returns.  As long as the caller understands they need to synchronize the device (or know what stream to synchronize?) before examining the data it's fine.  I wasn't sure if it was intentional that `create_index`, `get_values`, and others can return while device-to-host transfers to results could still be pending.
