### ISSUE TITLE
[FEA/Discussion] Refactor writers to use fsspec 

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2760]
**Is your feature request related to a problem? Please describe.**
The refactor in #2635 plans on using fsspec to handle remote filesystems and consequently returning a filepath or buffer. Current implementation [here](https://github.com/rapidsai/cudf/blob/17f0a22fd19f118780b5c9658919857f6a725a26/python/cudf/cudf/utils/ioutils.py#L824).

The idea is to refactor the writers `to_csv` and `to_orc` for now and others in the future to be able to use the helper method mentioned above to possibly write to remote filesystems etc.

**Describe the solution you'd like**

- `get_filepath_or_buffer utility` gets a `mode` argument to pass the mode `read/write`.
- All readers/writers go through the `get_filepath_or_buf` utility with readers using modes like `rb` and writers using modes like `wb`.
- The utility returns the filepath if it is a local file, allowing the readers/writers to perform any optimizations at the libcudf level for local files (like mmapping)
  - Option 1: The utility returns the open file handle in the case of all remote filesystems. Readers additionally call another method (either in python or Cython) to read the buffer into a `BytesIO` object that is later passed down to libcudf.
  - Option 2: The utility itself reads the buffer from the open file handle if the input mode is a `read` mode, and returns the `BytesIO` object.
- In the case of writers the utility returns the open file handle. Cython can have an argument passed down to libcudf indicating if the method should try to open the file and write (for local files) or return a host buffer with the data to be written (remote).
- If the data returned is a host buffer, the writers (at cython/python level) use the open file handle returned by the utility method, write the data to those files and close the file handle.

**Things to consider**
- Personally haven't looked into how a host buffer can be passed from libcudf to Cython and later used to write to an open file.
- How do we handle chunked writing approaches for the remote fs case? Eg: `to_csv` with chunksize, keeps processing a chunk and writes to the host buffer chunk by chunk. This will be tricky with the proposed approach. (Not sure, but if Cython could pass the open file handle or some attribute down to libcudf where libcudf itself handles writing to that file, it would simplify this case)
- How things integrate and work with dask_cudf dataframes.

Would love feedback and suggestions.
cc: @kkraus14, @j-ieong, @davidwendt

**Comment by davidwendt** [comment]
Also need to consider GPU Direct Storage (GDS) which can be used to read/write files to/from GPU memory directly. GDS has its own set of API calls and file-handle types. Perhaps cudf needs a more general file class (rather than helpers) to abstract the open/close and read/write methods and specific implementations for file, buffer, GDS.

**Comment by ayushdg** [comment]
Am I right in assuming that GDS would be applicable for localfilesystems only? If that is true then the behavior need not be redefined at the python/cython level as we pass down the filepath to libcudf directly without any changes or instantiation of file objects, buffers etc. Libcudf can then be responsible for checking if GDS is an option and decide the corresponding codepath. The python layer would not need to handle anything (fs related) in this case.

**Comment by j-ieong** [comment]
The `libcudf` readers already abstract out open()/close() and read() to a `datasource` class. The plan is for GDS to be integrated at this level as the GDS API takes in file handles and operate like mmapping (which is the fallback if GDS is unsupported).
The `libcudf` writers (such as the ORC writer) will either extend/rename `datasource` or have a separate `datasink` class.

There shouldn't be anything required of the Python or Cython layer for GDS.

**Comment by ayushdg** [comment]
Another idea/possibility that comes to mind, not sure about the feasibility. (This is not really related to the title of the pr but a general idea w.r.t IO)
Since the bottleneck for non local files is the Python memory allocation, I was thinking if this could be bypassed by somehow being able to map python open file objects via Cython to C file objects (or something like that). If that is possible we could theoretically release the GIL and do the following at the libcudf level 
- If it a read operation, datasource can handle some C file object (that Cython passed down) and do the equivalent of `BytesIO(file.read())` in cpp
- If it is a write operation. do something equivalent to  `file.write(BytesIO(buffer))` in cpp.

If this is feasible it should in theory speed up `read/writes` for other types of filesystems as well.

I apologize in advance if this is not feasible and I missed something obvious.

cc: @kkraus14 who might have some thoughts/ideas?

**Comment by kkraus14** [comment]
> Am I right in assuming that GDS would be applicable for localfilesystems only?

No, it will work over fabrics as well so you can't assume it's only local filesystems.

> Since the bottleneck for non local files is the Python memory allocation, I was thinking if this could be bypassed by somehow being able to map python open file objects via Cython to C file objects (or something like that).

This is apparently not easy in Python 3+ as file opens use the `io` module which handles the buffer management and doesn't actually rely on creating C file handles anymore. There may be Arrow utilities that we could rely on to handle these types of things for us though as I know there's ongoing work on an Arrow Filesystem abstraction API at the C++ level.

**Comment by ayushdg** [comment]
> No, it will work over fabrics as well so you can't assume it's only local filesystems.

- What kind of fabrics?
- At the python level do we plan on adding a check for deciding if GDS is possible or not?

**Comment by kkraus14** [comment]
> * What kind of fabrics?

Going to defer to the announcement blog: https://devblogs.nvidia.com/gpudirect-storage/

> At the python level do we plan on adding a check for deciding if GDS is possible or not?

That will be handled at the C++ level but we haven't done much exploration / discussion as to what it will look like for the Python level. We could probably add parameters to explicitly control behavior of "use GDS or fail" but likely the user is going to want a behavior of "use the fastest path available to me".

**Comment by jlowe** [comment]
The RAPIDS Spark plugin needs this feature to support the distributed filesystems used in Spark.  The option to output to a host buffer would be useful.

Another Spark use-case is writing a file whose input is larger than GPU memory.  Filed #3004 to track that separately.

**Comment by kkraus14** [comment]
@jlowe I think there may be a disconnect here. `fsspec` is a Python library and won't affect the C++ code. If you're referring to the chunked writing approaches then I think the discussion was mainly surrounding CSV / JSON / other text formats at least for now, but if we need the ability to chunk ORC / Parquet for Spark then that makes sense.

**Comment by kkraus14** [comment]
> Oh, sorry. I thought this could be useful for Spark as well since the labels called out cuIO and the description mentioned libcudf returning a host buffer from the write call. That's the part we would like to see for Spark to support writing distributed filesystems like S3 and HDFS. If that's not happening as part of this, I'll file a separate feature request to track that.

I think we're aligned where we'd love to see this functionality pushed down to the C++ level and everyone can depend on the same implementation, there just isn't anything out there yet. I believe Arrow has just started going down this route: https://github.com/apache/arrow/pull/5167 but there isn't a URI based implementation quite yet.

**Comment by ayushdg** [comment]
I think @j-ieong had also mentioned something about a `datasink` class that can write the data to a host buffer and return the buffer object instead of writing directly to a file.

Python / Spark would still have to be responsible for the host buffer and would have to implement logic/use libraries to write this buffer to remote/distributed file systems.

In the short/medium term this might be useful to write to different filesystems. 

In the long term it would be beneficial if the libcudf layer itself could understand and write directly to different filesystems so that everyone depends on the same implementation.

**Comment by kkraus14** [comment]
@ayushdg is this still a to-do?

**Comment by ayushdg** [comment]
@kkraus14 Yes. The original approach described https://github.com/rapidsai/cudf/issues/2760#issue-491239086 here is stale, but given the updates made in #5250, #5061 and general improvements in handling of host buffers while writing, makes plumbing this to write to remote filesystems much easier. Happy to take this on for 0.15 😄
