### ISSUE TITLE
[FEA] adding `to_datetime()` feature for time dependent data sets

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#2761]
**Is your feature request related to a problem? Please describe.**
We need a built in way to extract and manipulate time information from our notebook's columns.  As we get into more time series and forecasting, some public datasets require extracting and altering the date/time information.  

**Describe the solution you'd like**
See `pandas.to_datetime()`: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html

**Describe alternatives you've considered**
Currently, i use pandas.to_datetime().  On a 1 gb file, it takes 15-20 minutes.  I have also tried string manipulation using `datetime` and `timedelta` from some examples:
```
from datetime import datetime, timedelta
b = datetime.strptime(dfrt["Time Stamp"][70], '%m/%d/%Y %H:%M:%S')
df.year = b[0]
df.month = b[1]
df.hour=b[2]
df.minute=b[3]
df.second=b[4]
```
this does work faster than pandas, and i can do groupbys, but the output isn't something i can convert easily into a date number as if i had a `datetime`, although i probably could with more tinkering.
gdf["Datenum"] = gdf['Date'].astype(np.int64)// 10**9

**Additional context**
This is our closest example: 
https://rapidsai.github.io/projects/cudf/en/0.9.0/api.html?highlight=time

**Comment by beckernick** [comment]
@taureandyernv , what are you trying to do here? I don't think it's quite clear as that pandas method does a variety of things.

Based on your example, it looks like you're trying trying to convert a string column with values like `2019-09-11 00:00:00` into a datetime column, and then access the year/month/day/etc. Have you tried calling `astype('datetime64[ms]])` on your column?

**Comment by beckernick** [comment]
Connected offline. The desired functionality is implemented via the `Series.dt` accessor. We may want to better document this functionality. Closing this issue and will open a docs issue as appropriate.
