### ISSUE TITLE
[FEA] Add a nan_as_null attribute to Series

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2764]
Right now, there is no way to know whether a Series is treating NaNs as nulls (the default) or not. 
Implementations of various mathematical/statistical operations (variance, covariance, correlation, kurtosis, etc.) _generally_ need to treat NaNs as nulls, otherwise we would end up with incorrect results (primarily due to dividing by the wrong length of an array) or simply need to return NaN (see #2763 also).

We can always call `series.nans_to_nulls()` in the statistical operations, but this forces a copy every time, which isn't ideal since the `nan_as_null=False` scenario is likely an edge case.

If we add something like the following to the `Series` class constructor, we could use a single branching statement to avoid the copies in our method implementations. 

```python
class Series(object):
    ...
    def __init__(
        self, data=None, index=None, name=None, nan_as_null=True, dtype=None
    ):
        ...
        self._nan_as_null = nan_as_null
```

Alternatively, we could perhaps enhance `nans_to_nulls()` to optionally not make a copy.

**Comment by karthikeyann** [comment]
binary ops can generate nans. ` Series._nan_as_null` won't capture this. 

There is a way to create a temporary mask to convert all nans to nulls (including existing nulls also) before processing. It could avoid data copy. mask will still be copied.

**Comment by kkraus14** [comment]
I'm a strong -1 on this. It's impossible for us to track whether there's NaN values in a Series purely at construction time so we'd need to do this when a function is called.

In general either libcudf needs to handle NaN values in its functions, or in cuDF Python we need to convert `NaN` to `null` before the function is called, but this will either always invoke a copy, or do an expensive search for `NaN` values.
