### ISSUE TITLE
[DOC]Nvstrings nighly docs are not being rendered

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2767]
**Describe the bug**

Nvstrings nightly doc ( https://docs.rapids.ai/api/nvstrings/nightly/ ) are not beign rendered. 

![image](https://user-images.githubusercontent.com/4837571/64579024-2e4cf180-d336-11e9-8d2f-099798d89a6f.png)

**Comment by ayushdg** [comment]
Should be resolved by #2785
