### ISSUE TITLE
[FEA] left semi join and left anti join

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#2774]
**Is your feature request related to a problem? Please describe.**
Spark has support for a left semi join which is used to optimize `WHERE EXISTS` clauses in SQL.  Similarly Spark supports a left anti join which optimizes `WHERE NOT EXISTS` clauses. These joins are different than the standard join types in that they act like a filter on the left table with a join condition predicate.  Each row in the left table will only be emitted at most once regardless of the number of matches (or anti-matches) with that row in the right table, so there is no potential for the join exploding.

**Describe the solution you'd like**
libcudf provides a method to implement left semi join with arguments to specify the left table, the right table, the join columns, and the left table columns to return.  A table containing the join result would be returned.  Implementing left anti join could be done as a separate method or a flag to the left semi method.

**Describe alternatives you've considered**
Ways to implement these joins in terms of existing joins were considered.  If the right table has no more than one match per row in the left table then an inner join could be used.  Similarly an inner join could be performed followed by a groupby pass on the matching columns if the left table started with no rows containing duplicate values in the matching columns.  Unfortunately both of these require prior knowledge of the input table data which is expensive to discover on-the-fly and limits applicability of the accelerated join when those conditions are not met.

**Comment by jrhemstad** [comment]
So correct me if I'm wrong, but a "semi join" is basically just a set intersection, and "anti join" is set subtraction?

**Comment by jrhemstad** [comment]
An (inefficient) workaround would be to call `unique` on the `right` table, and then do a regular left join.

**Comment by jlowe** [comment]
> a "semi join" is basically just a set intersection, and "anti join" is set subtraction?

As I understand it, yes.

The distinct pass on the right table does look like a viable (if not performant) workaround for left semi.

**Comment by jrhemstad** [comment]
This wouldn't be too much effort to implement---it's easier than a regular join. I'm envisioning a hash-based implementation that uses the `concurrent_unordered_map` (instead of `multimap`) to build a hash table on the smaller table, then probe with the other table (basically the current hash-based join implementation, but uses a map instead of a multimap.)

**Comment by jlowe** [comment]
For the Spark use-case we only need left semi and left anti as those are the only semi/anti join types supported.

I haven't heard of an inner or outer semi join.  What would be their semantics if implemented?

**Comment by jrhemstad** [comment]
> For the Spark use-case we only need left semi and left anti as those are the only semi/anti join types supported.

Sounds great.

> What would be their semantics if implemented?

I have no idea :smile:
