### ISSUE TITLE
[BUG] nvstrings.slice_from gives incorrect result if start and stop are both zero

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2782]
**Describe the bug**
[BUG] nvstrings.slice_from gives incorrect result if start and stop are both zero .

**Steps/Code to reproduce bug**
```python
import nvstrings
import numpy as np
from numba import cuda
s = nvstrings.to_device(["hello","there"])
start_array = cuda.to_device(np.asarray([0,0],dtype=np.int32))
end_array = cuda.to_device(np.asarray([0,0],dtype=np.int32))

print(s.slice_from(starts=darr.device_ctypes_pointer.value,stops = end_array.device_ctypes_pointer.value))
```
```
['hello', 'there']
```

**Expected behavior**
I would expect that the result is as given below
```
['', '']
```
**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [source]

**Additional context**

This  causes some errors in the porter stemmer  implementation.

**Comment by davidwendt** [comment]
You are correct. 
The nvstrings regular `slice()` method also has this incorrect behavior.
Verified this with Pandas `slice()` method as well.
