### ISSUE TITLE
[FEA] Compile/Run All Benchmarks

### ISSUE THREAD

**Issue by dillon-cullinan** [rapidsai/cudf#2784]
**Is your feature request related to a problem? Please describe.**
Currently all benchmarks must be manually ran after compilation by doing `./<benchmark> --benchmark_out=<benchmark>.json --benchmark_out_format=json` after passing `-DBUILD_BENCHMARKS=ON` to cmake which isn't too friendly for job automation in Jenkins. Source building has to be edited manually on the job currently since I cannot use the root build script.

**Describe the solution you'd like**
1. A flag/option in root `build.sh` to build the benchmarks via this script. All this flag needs to do is pass `-DBUILD_BENCHMARKS=ON` to libcudf cmake.
2. A make target for benchmarks that builds/runs all the benchmarks given options described above (output dirname and file type (csv, json, console)). A single output file would be ideal, but outputting several files similar to GTest is fine as well.

- [x] 1. https://github.com/rapidsai/cudf/pull/2786
- [ ] 2.  https://github.com/rapidsai/cudf/pull/9879

**Comment by karthikeyann** [comment]
@robertmaynard is it possible to run benchmarks with `make benchmarks` or `ninja benchmarks` ? (or `ninja run_benchmarks`)
AFAIK, we don't have any such rule now in cmake.

**Comment by robertmaynard** [comment]
We could write such a rule via a `add_custom_target` where we have multiple `COMMAND` inputs which map to each benchmark we have generated

**Comment by karthikeyann** [comment]
Is there a way to all benchmarks like we run `ninja test` ?
Perhaps using Ctest scripting https://gitlab.kitware.com/cmake/community/-/wikis/doc/ctest/Scripting-Of-CTest ?
