### ISSUE TITLE
[FEA] Rolling window operations over grouped objects

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#2789]
**Is your feature request related to a problem? Please describe.**

While working with time series data there might be a need to perform rolling window operations on groups within a dataset. 
Eg: The fannie-mae mortgage performance data has multiple rows for a single `loan_id` added over time with the updated status of that loan. One kind of analysis could be to roll over a time window of a few months for each loan and compute some features like the minimum unpaid principal amount etc.

This would require being able to do something like: df.groupby("loan_id").rolling("365d").min() allowed by pandas.

Worth noting that the way to accomplish this in Dask is by using `groupby.apply` as mentioned here https://stackoverflow.com/questions/42172130/dask-rolling-function-by-group-syntax

**Describe alternatives you've considered**
Alternatives might be to manually implement the `rolling` functionality with legacy groupby as a custom method

**Comment by shwina** [comment]
In the short term, `groupby.rolling` can be provided with legacy groupby. In the medium term it can be replaced with a libcudf implementation. I'm going to be working on unifying the legacy and hash-based groupby on the Python side and will tackle this there.

**Comment by harrism** [comment]
CC @devavret for visibility

**Comment by shwina** [comment]
Now that libcudf offers groupby rolling, we should plumb it through to Python

**Comment by harrism** [comment]
Should we prioritize for 0.15?
