### ISSUE TITLE
[BUG] upper_bound and lower_bound functions incorrect results when searching GDF_STRING_CATEGORY values

### ISSUE THREAD

**Issue by jeanp413** [rapidsai/cudf#2790]
**Describe the bug**
`upper_bound` and `lower_bound` functions give incorrect results when searching GDF_STRING_CATEGORY values

This is caused because the column's categories are not synced before doing the search

**Steps/Code to reproduce bug**
Call `upper_bound` / `lower_bound` with the `cudf::table table` and `cudf::table values` parameters containing a columns whose types are GDF_STRING_CATEGORY

**Expected behavior**
`upper_bound` and `lower_bound` should give correct results when searching GDF_STRING_CATEGORY values

**Comment by kuhushukla** [comment]
Based on some java side tests GDF_STRING also seems to be broken for lower/upper bound.

**Comment by harrism** [comment]
This is fixed in the libcudf++ API by #3229 

@kuhushukla @jeanp413 please reopen if you find this is not the case.
