### ISSUE TITLE
[FEA] Add support for cudf Series.apply and Series.map

### ISSUE THREAD

**Issue by hokiegeek2** [rapidsai/cudf#2793]
Requesting support for the apply and map methods for cudf Series objects in analogy to Pandas Series.apply and Series.map

**Comment by beckernick** [comment]
Series.map has been implemented:

```python
import cudf
s = cudf.Series(["a","b","c"])
print(s)
s.map({"a":"hello", "b":"world"})
0    a
1    b
2    c
dtype: object
0    hello
1    world
2     <NA>
dtype: object
```

**Comment by hokiegeek2** [comment]
@beckernick NICE!

**Comment by beckernick** [comment]
We've now also implemented `Series.apply` and `DataFrame.apply` for scalar functions. Please feel free to visit the [Series.apply documentation](https://docs.rapids.ai/api/cudf/nightly/api_docs/api/cudf.Series.apply.html) or our 21.12 [release blog](https://medium.com/rapids-ai/rapids-release-21-12-fc5cfcfc1cb8).

```python
import cudf
​
sr = cudf.Series([1,cudf.NA,3])
​
def f(x):
    if x is cudf.NA:
        return 42
    else:
        return x - 1
​
sr.apply(f)
0     0
1    42
2     2
dtype: int64
```

Closing as resolved, but please feel free to reopen.

**Comment by hokiegeek2** [comment]
Thank you!!
