### ISSUE TITLE
[BUG] dask_cudf.read_csv 8x slower than pandas.read_csv

### ISSUE THREAD

**Issue by ivenzor** [rapidsai/cudf#2798]
I'm using rapids 0.9 to read 3 columns from a csv.gzip file with 219 columns and 629,470 rows:
_2	18	56
0	2016-01-01 00:00:00.000000	133449.950	120
1	2016-01-01 00:00:00.000000	0.000	120
2	2016-01-01 00:00:00.000000	862685.583	120
3	2016-01-01 00:00:00.000000	NaN	199
4	2016-01-01 00:00:00.000000	NaN	199_

Pandas read:
_df=pd.read_csv('s3://XXX.csv.gz', compression='gzip', sep='~', header=None, encoding='cp1252', low_memory=False, usecols=[2,18, 56])_

Dask-Cudf read:
_df=dask_cudf.read_csv('s3://XXX.csv.gz', compression='gzip', sep='~', header=None, usecols=[2,18, 56])_

With pandas.read_csv it took **7.5** minutes and with dask_cudf.read_csv it took **61** minutes. GPU (v100) Memory usage is 553MB.

Am I doing something wrong?

**Comment by quasiben** [comment]
Thanks for the report @ivenzor .  I don't think you are doing anything wrong but can we get some more information ?

- what version of dask ?
- what version of distributed ?
- are you using rapids inside docker or using conda packages ?
- is it possible to make the file publicly consumable so we can test?

**Comment by ivenzor** [comment]
As I'm not able to reproduce this on rapids 0.10 I will close this issue.
