### ISSUE TITLE
[BUG] dask_cudf meet errors when using large datasets on distributed servers. 

### ISSUE THREAD

**Issue by pengsnv** [rapidsai/cudf#2808]
Environment & datasets
Two servers connected with ethernet. Each equipment with 4 PCIE-16GB-V100
Use nvcr.io/nvidia/rapidsai/rapidsai:0.8-cuda9.2-runtime-centos7-gcc7-py3.7 container
3 datasets:
2.8GB csv datasets  149000000row *5column( 4 features+1 class) (for test)
5.6GB csv datasets  298000000row *5column( 4 features+1 class) (for test)
112GB csv datasets  5960000000row *5column( 4 features+1 class) (their real datasets)
 
How we start the test
On Server1 (IP, for example, 192.168.1.1)
Start the container: 
```
$nvidia-docker run it --rm --net=host -v path_to_data_sets:/datasets nvcr.io/nvidia/rapidsai/rapidsai:0.8-cuda9.2-runtime-centos7-gcc7-py3.7
```
In the container, start dask scheduler: 
```
$dask-scheduler >/tmp/scheduler.log 2>&1 &
```
In the container, start dask worker: 
```
$dask-cuda-worker 192.168.1.1:8786 --memory-limit=200GB >/tmp/worker.log 2>&1 &
```
 
On server2(IP ,for example, 192.168.1.2)
Start the container: 
```
$nvidia-docker run it --rm --net=host -v path_to_data_sets:/datasets nvcr.io/nvidia/rapidsai/rapidsai:0.8-cuda9.2-runtime-centos7-gcc7-py3.7
```
In the container, start dask worker: 
```
$dask-cuda-worker 192.168.1.1:8786 --memory-limit=200GB >/tmp/worker.log 2>&1 &
```
 
Then run the script similar to this( on server 1):
```
  import cudf
  import dask
  import dask_cudf
  import dask_xgboost
  import pandas as pd
  import numpy as np
  from dask.distributed import Client,wait
  import subprocess
  cmd="hostname --all-ip-addresses"
  process=subprocess.Popen(cmd.split(),stdout=subprocess.PIPE)
  output,error=process.communicate()
  IPADDR=str(output.decode()).split()[0]

  _client=IPADDR+str(":8786")#replace IPADDR to your dask server IP.
  client=Client(_client)
  print(client)
  size = 3000
  npartitions = 8
  #############   method split datafile   ###############
  ############### used when csv is too large#############
 #dask.dataframe.read_csv("large1.csv").repartition(npartitions=10).to_csv("./many/*.csv",index=False)
#exit()

 ##########random dataset###############################
  pdf = pd.DataFrame({'x': np.random.randint(0, npartitions, size=size), 'y': 
  np.random.normal(size=size)})

#############   method 1  pandas-dask.dataframe-dask_cudf   ###############
  pdf = pd.read_csv("large1.csv")
  pdf = dask.dataframe.from_pandas(pdf, npartitions=npartitions)
  ddf = dask_cudf.from_dask_dataframe(pdf)

#############   method 2 dask_cudf   #############################
  #ddf=dask_cudf.read_csv("large1.csv",header=0)

#############   method 3 dask.dataframe-dask_cudf   #############################
  #pdf=dask.dataframe.read_csv("large1.csv")
  #ddf = dask_cudf.from_dask_dataframe(pdf)

#############   method 4 dask.dataframe-map-function  ######################
  #pdf=dask.dataframe.read_csv("large1.csv")
  #ddf=pdf.map_partitions(cudf.from_pandas)



  x_train = ddf.query('y < 0.5')
  y_train = x_train[['x']]
  x_train = x_train[x_train.columns.difference(['x'])]

  x_test = ddf.query('y > 0.5')
  y_test = x_test[['x']]
  x_test = x_test[x_test.columns.difference(['x'])]
  #print(x_test.compute())
  #print(y_test.compute())


  params = {
    'num_rounds':   100,
    'max_depth':    8,
    'max_leaves':   2**8,
    'n_gpus':       1,
    'tree_method':  'gpu_hist',
    'objective':    'reg:squarederror',
    'grow_policy':  'lossguide'
  }


  x_train = x_train.persist()
  y_train = y_train.persist()

  bst = dask_xgboost.train(client, params, x_train, y_train, 
  num_boost_round=params['num_rounds'])

  pred = dask_xgboost.predict(client, bst, x_test)
  test = dask.dataframe.multi.concat([pred], axis=1)
  test['squared_error']=(test[0]-y_test['x'])**2

  rmse = np.sqrt(test.squared_error.mean().compute())
  #big_future = client.scatter(test.squared_error.mean().compute())     # good
  #rmse=client.submit(np.sqrt, big_future)
  print('rmse value:', rmse)
```
 
What we have test
Method 1: pandas+dask.dataframe+dask.cudf
```
pdf = pd.read_csv("large1.csv")
pdf = dask.dataframe.from_pandas(pdf, npartitions=npartitions)
ddf = dask_cudf.from_dask_dataframe(pdf)
 ```

2.8GB datasets: pass      
5.6GB datasets: sometimes pass; sometimes block, need to restart cuda-dask-worker
112GB datasets: lack of memory to load datasets in pandas dataframe on on machine.
 
Method 2: dask_cudf
```
ddf=dask_cudf.read_csv("large1.csv",header=0)
```
 
2.8GB datasets: pass
5.6 GB datasets: failed
Then we tried to split the 5.6GB datasets into 16 part.
```
dask.dataframe.read_csv("large1.csv").repartition(npartitions=16).to_csv("./split/*.csv",index=False)
exit()
```
And load the small part 
```
ddf=dask_cudf.read_csv("./split/*.csv",header=0)
```
also failed.

Log in schedule.log
```
Distributed.worker -INFO- Run out-of-band function ‘start_tracker’
```

Log in worker.log
```
Distributed.core -INFO- Event loop was unresponsive in Worker for 21.62s. This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.
…
… (repeats of the same info)
Distributed.utils_perf -INFO- full garbage collection released 102.40MB from 106 reference cycles (threshold: 10MB)
```
 
Method 3:dask.dataframe+dask.cudf
```
pdf=dask.dataframe.read_csv("large1.csv")
ddf = dask_cudf.from_dask_dataframe(pdf)
```
 
2.8GB datasets: pass
5.6GB datasets: failed
Log in worker.log
```
Terminate called after throwing an instance of “thrust::system::systetem_error”
    What(): parallel_for failed: out of memory
Terminate called after throwing an instance of “thrust::system::systetem_error”
    What(): parallel_for failed: out of memory
```

**Comment by randerzander** [comment]
@pengsnv several things:

1. Can you also try the 0.9 container images? Quite a few bugs and improvements have been made since then.

2. Make sure to start your dask-cuda-workers with `--memory-limit 0`, and set some client configurations:
```
# this will limit work-stealing as much as possible
dask.config.set({'distributed.scheduler.work-stealing': False})
dask.config.get('distributed.scheduler.work-stealing')
dask.config.set({'distributed.scheduler.bandwidth': 1})
dask.config.get('distributed.scheduler.bandwidth')
```

3. please try calling `.persist()` on the dask_cudf DataFrame before your calls to train. This helps avoid Dask having workers shuffle partitions over the network.

**Comment by pentschev** [comment]
I think this is because some cuDF calls are requiring too much memory, I had success using CUDA managed memory cases similar to this one.

@pengsnv could you try adding the following immediately after the `client=Client(_client)` line?

```python
def initialize_rmm():
    from librmm_cffi import librmm_config as rmm_cfg
    import cudf
    cudf.rmm.finalize()
    rmm_cfg.use_managed_memory = True
    return cudf.rmm.initialize()

client.run(initialize_rmm)
```

I'm fairly confident this will suffice, and would also recommend 0.9 (I haven't tested that on 0.8).

**Comment by pengsnv** [comment]
@randerzander 5.6GB datasets run successful with the dask.config.set, in 0.8 container. Thanks very much. And the configuration seems about the network, will infiniband network improve the performance and cover the issue?

@pentschev  I also try managed_memory method in 0.8 container, it can work well with 5.6GB datasets, although the worker still report 
`Distributed.core -INFO- Event loop was unresponsive in Worker for 26.03s. This is often caused by long-running GIL-holding functions or moving large chunks of data. This can cause timeouts and instability.`  
So maybe more work-stealing( I think this meanings moving chunks of data) will lead to more GPU memory usage building cudf dataframe and case OOM, right?
And as it uses managed_memory, this method will be a bit slower then the method above.

Many thanks and We will try 112GB datasets later.

**Comment by pentschev** [comment]
@pengsnv sorry, I forgot to say that the solution I proposed was meant specifically for method 3, where you got an out-of-memory error. This will likely not play a role in the work-stealing business.

**Comment by pengsnv** [comment]
Hi @randerzander  & @pentschev :
I have tested 28GB/56GB/84GB datasets on DGX-2, and met OOM with 84GB datasets.

Environment & datasets
Two servers connected with ethernet. Each equipment with 4 PCIE-16GB-V100
Use nvcr.io/nvidia/rapidsai/rapidsai:0.9-cuda10.0-runtime-ubuntu18.04 container
3 datasets:
28GB csv datasets 1490000000row *5column( 4 features+1 class) (for test)
56GB csv datasets 2980000000row *5column( 4 features+1 class) (for test)
86GB csv datasets 4470000000row *5column( 4 features+1 class) (for test)
datasets looks like:
`
Col_A,Col_B,Col_C,Col_D,class
4.9,3.0,1.4,0.2,0.0
4.7,3.2,1.3,0.2,0.0
…
`
I started dask environment and used script with dask_cudf method mentioned above.
I have also split the datasets into multi 2.8GB files and added dask.config.set.

1. 28GB  **PASS**
2. 56GB **PASS after adding initialize_rmm**
3. 87GB **FAIL**
    Through monitoring  GPU memory utilization and dask dashboard, I found:
     a. At "read-csv" and "getitem" (present on dashboard) stage, comsumes about 8GB per GPU.
     b. At "tuple" stage, GPU memory utilization expanding and almost all the GPU memory is utilized.
     c. At "train_part" preparing stage, some GPUs/dask-workers will restart.

Please find the attachment for the script, output, worker.log, GPU memory utilization and dashboard result. 

Please advice me how to modify the script to run 87GB/112GB datasets on DGX2?
Thanks in advance.
[log.zip](https://github.com/rapidsai/cudf/files/3781856/log.zip)

**Comment by pentschev** [comment]
The failure doesn't seem to be an OOM one, from the `dask_work.log`:

```
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:45:35] /conda/envs/gdf/conda-bld/xgboost_1561069550363/work/include/xgboost/../../src/common/span.h:404: Check failed: _ptr || _count == 0:
Stack trace:
  [bt] (0) /opt/conda/envs/rapids/lib/libxgboost.so(+0xb7e74) [0x7f33c8c90e74]
  [bt] (1) /opt/conda/envs/rapids/lib/libxgboost.so(xgboost::common::Span<xgboost::detail::GradientPairInternal<float>, -1l>::Span(xgboost::detail::GradientPairInternal<float>*, long)+0x69) [0x7f33c8eb17c9]
  [bt] (2) /opt/conda/envs/rapids/lib/libxgboost.so(xgboost::tree::DeviceShard<xgboost::detail::GradientPairInternal<double> >::InitCompressedData(xgboost::common::HistCutMatrix const&, xgboost::SparsePage const&, bool)+0x270) [0x7f33c8ed7ab0]
  [bt] (3) /opt/conda/envs/rapids/lib/libxgboost.so(+0x2ffd6a) [0x7f33c8ed8d6a]
  [bt] (4) /opt/conda/envs/rapids/lib/./libgomp.so.1(GOMP_parallel+0x3f) [0x7f3534c1e027]
  [bt] (5) /opt/conda/envs/rapids/lib/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::InitDataOnce(xgboost::DMatrix*)+0x6c9) [0x7f33c8ecd6e9]
  [bt] (6) /opt/conda/envs/rapids/lib/libxgboost.so(xgboost::tree::GPUHistMakerSpecialised<xgboost::detail::GradientPairInternal<double> >::Update(xgboost::HostDeviceVector<xgboost::detail::GradientPairInternal<float> >*, xgboost::DMatrix*, std::vector<xgboost::RegTree*, std::allocator<xgboost::RegTree*> > const&)+0x14ef) [0x7f33c8ecee6f]
  [bt] (7) /opt/conda/envs/rapids/lib/libxgboost.so(+0x13d903) [0x7f33c8d16903]
  [bt] (8) /opt/conda/envs/rapids/lib/libxgboost.so(+0x13e2e8) [0x7f33c8d172e8]
```

I also don't see any other errors anywhere that point to an obvious OOM error, but I'm not familiar with xgboost.

@randerzander any ideas here? Perhaps it would be useful to engage someone working with xgboost to take a look?

**Comment by kkraus14** [comment]
Stale, closing.
