### ISSUE TITLE
read_parquet: Reading num_rows with an offset of skip_rows causes cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by jperez999** [rapidsai/cudf#2812]
**Describe the bug**
Trying to create a cudf dataset iterator using skip_rows and num_rows. So it can support multiple file types. Currently causes a cudaErrorIllegalAddress, whenever skip_rows > 0.

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
import os

processed = 10000
batch = 10000
n = 100000
out_df = cudf.DataFrame({'y': np.random.choice(range(1000000, 2000000), n, replace=False),
                   'z': np.random.choice(range(1000000, 2000000), n, replace=False),
                   's': np.random.choice(range(20), n, replace=True),
                   'a': np.round(np.random.uniform(1, 5000, n), 2)})
print(out_df.head())
out_df.to_parquet('temp')
r_fi = ['temp/' + x for x in os.listdir('temp/') if x.endswith(".parquet")]

for i in range(20):
    if processed > len(out_df): break
    chunk = cudf.read_parquet(r_fi[0], skip_rows=processed, num_rows=batch)
    print(chunk.head())
    processed += batch
    del chunk
```
**Expected behavior**
Expect to iterate over the file pulling out each chunk of data frame. Works with csv:
```
import cudf
import numpy as np
import os

processed = 10000
batch = 10000
n = 1000000
out_df = cudf.DataFrame({'y': np.random.choice(range(1000000, 2000000), n, replace=False),
                   'z': np.random.choice(range(1000000, 2000000), n, replace=False),
                   's': np.random.choice(range(20), n, replace=True),
                   'a': np.round(np.random.uniform(1, 5000, n), 2)})
print(out_df.head())
out_df.to_csv('temp.csv')
# r_fi = ['temp/' + x for x in os.listdir('temp/') if x.endswith(".csv")]
for i in range(20):
    if processed > len(out_df): break
    chunk = cudf.read_csv('temp.csv', skiprows=processed, nrows=batch)
    print(chunk.head())
    processed += batch
    del chunk
```

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install: [conda]

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux 99c2508ab077 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Sep 16 19:48:00 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla P100-DGXS...  On   | 00000000:07:00.0  On |                    0 |
     | N/A   37C    P0    43W / 300W |   9858MiB / 16275MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla P100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
     | N/A   37C    P0    34W / 300W |     12MiB / 16278MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla P100-DGXS...  On   | 00000000:0E:00.0 Off |                    0 |
     | N/A   39C    P0    31W / 300W |     12MiB / 16278MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla P100-DGXS...  On   | 00000000:0F:00.0 Off |                    0 |
     | N/A   36C    P0    32W / 300W |     12MiB / 16278MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              16
     On-line CPU(s) list: 0-15
     Thread(s) per core:  2
     Core(s) per socket:  8
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-1660 v4 @ 3.20GHz
     Stepping:            1
     CPU MHz:             1199.427
     CPU max MHz:         3800.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6395.89
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            20480K
     NUMA node0 CPU(s):   0-15
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     
     ***g++***
     
     ***nvcc***
     
     ***Python***
     /conda/envs/rapids/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /conda/envs/rapids/bin:/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /conda/envs/rapids/bin/conda
     # packages in environment at /conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     aiohttp                   3.6.0                    pypi_0    pypi
     arrow-cpp                 0.14.1           py37h6b969ab_1    conda-forge
     asn1crypto                0.24.0                py37_1003    conda-forge
     async-timeout             3.0.1                    pypi_0    pypi
     attrs                     19.1.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     beautifulsoup4            4.8.0                    py37_0
     blas                      1.0                    openblas
     bleach                    3.1.0                      py_0    conda-forge
     blinker                   1.4                        py_1    conda-forge
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     boto3                     1.9.227                    py_0    conda-forge
     botocore                  1.12.227                   py_0    conda-forge
     bottleneck                1.2.1            py37h035aef0_1
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_1    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.5.15                     1
     cachetools                2.1.0                      py_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.6.16                py37_1
     cffi                      1.12.3           py37h8022711_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_0    conda-forge
     conda                     4.7.12                   py37_0    conda-forge
     conda-package-handling    1.4.1                    py37_0    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               10.0.130                      0
     cudf                      0.10.0a               py37_1297    rapidsai-nightly
     cudnn                     7.6.0                cuda10.0_0
     cugraph                   0.10.0a                py37_104    rapidsai-nightly
     cuml                      0.10.0a         cuda10.0_py37_539    rapidsai-nightly
     cupy                      6.2.0            py37h88562e5_0    rapidsai
     cuspatial                 0.10.0a                py37_111    rapidsai-nightly
     custreamz                 0.10.0a               py37_1297    rapidsai-nightly
     cycler                    0.10.0                     py_1    conda-forge
     cymem                     2.0.2            py37hfd86e86_0
     cyrus-sasl                2.1.27               he38ecfd_0    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.9.0.1          py37h14c3975_1
     dask                      2.3.0                      py_0    conda-forge
     dask-core                 2.3.0                      py_0    conda-forge
     dask-cuda                 0.10.0a0+13.g39eac02          pypi_0    pypi
     dask-cudf                 0.10.0a               py37_1297    rapidsai-nightly
     dataclasses               0.6                        py_0    fastai
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.5.0                      py_1    conda-forge
     dill                      0.2.9                    py37_0
     distributed               2.3.2                      py_1    conda-forge
     dlpack                    0.2                  he1b5a44_0    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     dragonfly-opt             0.1.4                    pypi_0    pypi
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastai                    1.0.57                        1    fastai
     fastavro                  0.22.4           py37h516909a_0    conda-forge
     fastprogress              0.1.21                     py_0    fastai
     fastrlock                 0.4             py37hf484d3e_1000    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fribidi                   1.0.5             h516909a_1002    conda-forge
     fsspec                    0.4.4                      py_0    conda-forge
     future                    0.17.1                   pypi_0    pypi
     gcsfs                     0.3.0                      py_1    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glib                      2.58.3            h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     google-auth               1.6.3                      py_0    conda-forge
     google-auth-oauthlib      0.4.0                      py_0    conda-forge
     graphite2                 1.3.13            hf484d3e_1000    conda-forge
     graphviz                  2.40.1               h0f2764d_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     harfbuzz                  2.4.0                h9f30f68_3    conda-forge
     heapdict                  1.0.0                 py37_1000    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     ignite                    0.2.0                    py37_0    pytorch
     intel-openmp              2019.4                      243
     ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
     ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.1                     py_0    conda-forge
     jmespath                  0.9.4                      py_0    conda-forge
     joblib                    0.13.2                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.0.2                    py37_0    conda-forge
     jupyter-server-proxy      1.1.0                    pypi_0    pypi
     jupyter_client            5.3.1                      py_0    conda-forge
     jupyter_core              4.4.0                      py_0    conda-forge
     jupyterlab                1.1.3                      py_0    conda-forge
     jupyterlab-nvdashboard    0.1.9                    pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libarchive                3.3.3             hb44662c_1005    conda-forge
     libblas                   3.8.0               12_openblas    conda-forge
     libcblas                  3.8.0               12_openblas    conda-forge
     libcudf                   0.10.0a           cuda10.0_1297    rapidsai-nightly
     libcugraph                0.10.0a            cuda10.0_104    rapidsai-nightly
     libcuml                   0.10.0a            cuda10.0_539    rapidsai-nightly
     libcumlprims              0.9.0                cuda10.0_0    nvidia
     libcuspatial              0.10.0a            cuda10.0_111    rapidsai-nightly
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_0
     libgpg-error              1.36                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0             h19a2143_1004    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     liblapack                 3.8.0               12_openblas    conda-forge
     libntlm                   1.4               h14c3975_1002    conda-forge
     libnvstrings              0.10.0a           cuda10.0_1297    rapidsai-nightly
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librdkafka                1.1.0                hb2b7465_0    conda-forge
     librmm                    0.10.0a             cuda10.0_19    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libsolv                   0.7.5                h8b12597_0    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libtool                   2.4.6             h14c3975_1002    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.30.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.9                hee79883_5    conda-forge
     lightgbm                  2.2.1            py37he6710b0_0
     llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     lzo                       2.10              h14c3975_1000    conda-forge
     mamba                     0.0.8            py37hc9558a2_1    conda-forge
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     matplotlib                3.1.1                    py37_1    conda-forge
     matplotlib-base           3.1.1            py37he7580a8_1    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     mkl                       2019.4                      243
     msgpack-numpy             0.4.3.2                  py37_0
     msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
     multidict                 4.5.2                    pypi_0    pypi
     murmurhash                1.0.2            py37he6710b0_0
     nbconvert                 5.6.0                    py37_1    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     ninja                     1.9.0            py37hfd86e86_0
     nodejs                    12.8.1               h10a4023_0    conda-forge
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.45.1           py37hb3f55d8_0    conda-forge
     numexpr                   2.7.0            py37h2ffa06c_0
     numpy                     1.17.2           py37h95a1406_0    conda-forge
     nvidia-ml-py3             7.352.0                    py_0    fastai
     nvstrings                 0.10.0a               py37_1297    rapidsai-nightly
     oauthlib                  3.0.1                      py_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1d               h7b6447c_1
     packaging                 19.0                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     pandas-profiling          1.4.1                    py37_0
     pandoc                    2.7.3                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     pango                     1.42.4               ha030887_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pcre                      8.41              hf484d3e_1003    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.1.0            py37h6b7be26_1    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     plac                      0.9.6                    py37_0
     preshed                   2.0.1            py37he6710b0_0
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.9                      py_0    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py4j                      0.10.7                     py_1    conda-forge
     pyarrow                   0.14.1           py37h8b68381_0    conda-forge
     pyasn1                    0.4.6                      py_0    conda-forge
     pyasn1-modules            0.2.6                      py_0    conda-forge
     pycosat                   0.6.3           py37h14c3975_1001    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyjwt                     1.7.1                      py_0    conda-forge
     pynvml                    8.0.3                    pypi_0    pypi
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     pyqt                      5.9.2            py37hcca6a23_4    conda-forge
     pyrsistent                0.15.4           py37h516909a_0    conda-forge
     pysocks                   1.7.0                    py37_0    conda-forge
     pyspark                   2.4.4                      py_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-confluent-kafka    1.1.0            py37h516909a_0    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     python-graphviz           0.13                       py_0    conda-forge
     python-libarchive-c       2.8                   py37_1004    conda-forge
     pytorch                   1.3.0.dev20190912 py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch-nightly
     pytz                      2019.2                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.1.0           py37h1768529_0    conda-forge
     qt                        5.9.7                h0c104cb_3    conda-forge
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     regex                     2018.01.10      py37h14c3975_1000    fastai
     requests                  2.22.0                   py37_1    conda-forge
     requests-oauthlib         1.2.0                      py_0    conda-forge
     rmm                       0.10.0a                 py37_19    rapidsai-nightly
     rsa                       3.4.2                      py_1    conda-forge
     ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
     s3fs                      0.3.4                      py_0    conda-forge
     s3transfer                0.2.1                    py37_0    conda-forge
     scikit-learn              0.21.3           py37hcdab131_0    conda-forge
     scipy                     1.3.1            py37h921218d_2    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.2.0                   py37_0    conda-forge
     simpervisor               0.3                      pypi_0    pypi
     sip                       4.19.8          py37hf484d3e_1000    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snakeviz                  2.0.1                    py37_0
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     soupsieve                 1.9.2                    py37_0
     spacy                     2.0.18          py37hf484d3e_1000    fastai
     sqlite                    3.29.0               hcee41ef_1    conda-forge
     streamz                   0.5.2                      py_0    conda-forge
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thinc                     6.12.1          py37h637b7d7_1000    fastai
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     torchvision               0.3.0           py37_cu10.0.130_1    pytorch
     tornado                   6.0.3            py37h516909a_0    conda-forge
     tqdm                      4.35.0                     py_0    conda-forge
     traitlets                 4.3.2                 py37_1000    conda-forge
     typing                    3.6.4                    py37_0
     ujson                     1.35             py37h14c3975_0
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.3                   py37_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     wrapt                     1.10.11          py37h14c3975_2
     xgboost                   1.0.0-SNAPSHOT           pypi_0    pypi
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.8                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxpm               3.5.12            h516909a_1002    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-libxt                1.1.5             h516909a_1003    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     yarl                      1.3.0                    pypi_0    pypi
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Comment by rjzamora** [comment]
Thanks for raising this @jperez999 -  I can confirm that iterating through a file using `skip_rows`/`num_rows` does not behave correctly **unless** you are reading in batches that are aligned with parquet row-groups.  I can get parquet to behave the way you **do** want by specifying a `row_group_size` that is a multiple of `batch` within `out_df.to_parquet`:

```python
import cudf
import numpy as np
import shutil
import os

batch = 10000
n = 100000
out_df = cudf.DataFrame(
    {'i0': np.arange(n), 'i1': np.arange(n)}
)

filepath = 'temp'
if os.path.isdir(filepath):
    shutil.rmtree(filepath)
    
print("\nHead of Written DataFrame:")
print(out_df.head())
out_df.to_parquet('temp', row_group_size=batch)
r_fi = ['temp/' + x for x in os.listdir('temp/') if x.endswith(".parquet")]

print("\nDataFrame Metadata (rows, row-groups, columns):")
print(cudf.io.read_parquet_metadata(r_fi[0])); 
filepath = r_fi[0]
    
with open(filepath, "rb") as f:
    for i in range(0, n//batch):
        f.seek(0)
        chunk = cudf.read_parquet(f, skip_rows=batch*i, num_rows=batch)
        # OR: chunk = cudf.read_parquet(f, row_group=i)
        print("\nHead of Chunk %d:" % i)
        print(chunk.head())
        del chunk
```
<details>
<summary>Click to show output...</summary>
<br>
```
Head of Written DataFrame:
   i0  i1
0   0   0
1   1   1
2   2   2
3   3   3
4   4   4

DataFrame Metadata (rows, row-groups, columns):
(100000, 10, ['i0', 'i1'])

Head of Chunk 0:
   i0  i1
0   0   0
1   1   1
2   2   2
3   3   3
4   4   4

Head of Chunk 1:
      i0     i1
0  10000  10000
1  10001  10001
2  10002  10002
3  10003  10003
4  10004  10004

...

Head of Chunk 9:
      i0     i1
0  90000  90000
1  90001  90001
2  90002  90002
3  90003  90003
4  90004  90004
```
</details>

Note that this solution also requires `f.seek(0)` before each chunk is read in (I'm not exactly sure why the file pointer needs to be reset before each read -- perhaps this is a bug?).

If I remove `row_group_size=batch` from `out_df.to_parquet` in the above example, the data is **not** read in correctly.  For chunk 1 (the second chunk to be read in), I get the following output:

```
Head of Chunk 1:
      i0     i1
0  10000  20048
1  10001  20049
2  10002  20050
3  10003  20051
4  10004  20052
```

Since `"i0"` and `"i1"` should match, this makes me think that the parquet reader is incorrectly expecting the data for this chunk of `"i1"` to be stored adjacent to this chunk of `"i0"`.  This, however, is only true if the chunk is aligned with the current row-group.

**Comment by OlivierNV** [comment]
For the initial issue, it seems that we fault when skip_rows becomes larger than the number of rows in the file (iteration i=9 correctly returns an empty dataframe with skip_rows=100000, but iteration i=10 faults with skip_rows=110000).
Actually, with 0.10, I'm getting an error "cuDF failure at parquet_reader_impl.cu:228: Invalid row start"
@jperez999 : is the expected behavior to return an empty dataframe ?

**Comment by jperez999** [comment]
@OlivierNV Oh sorry no... the index out of bounds is not part of the problem I am trying to fix. The problem I was trying to highlight was that trying to grab batches not aligned with the row_groups fails. I can add escape to loop (i.e. when processed > file_size: break) to safely traverse the file.

**Comment by OlivierNV** [comment]
Haven't dug into it yet, but I suspect it may be similar to a bug that was fixed for ORC, where the number of rows to skip was not adjusted correctly if it did not fall within the first row_group/stripe.

**Comment by OlivierNV** [comment]
Update: the kernel-level handling of skip_rows, when it does not align with a page boundary is definitely broken... Working on a fix.
