### ISSUE TITLE
[Bug] nvstrings.hash gives incorrect result with np.int64 device array

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2815]
**Describe the bug**
 `nvstrings.hash` gives incorrect result with `np.int64` device array . 

In our current implementation we seem to only give correct output when the dtype of the device array is `np.uint32` , In the docs we say that it should alteast be able to hold `np.uint32` so we should  support `np.int64` .  

https://github.com/rapidsai/cudf/blob/a80e9a1e173abf60f5703486933e80d87982212a/python/nvstrings/nvstrings.py#L681-L683

**Steps/Code to reproduce bug**

```python
token_ser = cudf.Series(['this','this','is','is','a','a','check','check'])

str_hash_ser = cudf.Series(librmm.device_array(len(token_ser), dtype=np.int64))
token_ser.str.hash(devptr=str_hash_ser.data.mem.device_ctypes_pointer.value)
str_hash_ser
```

Output:
```python
0    7301601398839607241
1    -309387569807436380
2   -3896403093571685881
3    5022561781046032724
4        140731450674752
5        140731450674768
6        140731450674784
7        140731450674800
dtype: int64
```

As we can see hash of the same string is giving different values. 

**Expected behavior**
The expected behaviour will be what we get with `uint32`:

```python
token_ser = cudf.Series(['this','this','is','is','a','a','check','check'])
str_hash_ser = cudf.Series(librmm.device_array(len(token_ser), dtype=np.uint32))
token_ser.str.hash(devptr=str_hash_ser.data.mem.device_ctypes_pointer.value)
str_hash_ser
```

```python
0    1700036553
1    1700036553
2    4222932388
3    4222932388
4    3387765255
5    3387765255
6    1169406292
7    1169406292
dtype: uint32
```
**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: source

**Additional context**
Currently we dont support `np.uint32` in gdf columns so i cant really use the result in a `cudf.Series` . I get below when i try to cast it to `int64`

`str_hash_ser.astype(np.int64)`
```python
----------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-86-525a02221c35> in <module>
      3 str_hash_ser = cudf.Series(librmm.device_array(len(token_ser), dtype=np.uint32))
      4 token_ser.str.hash(devptr=str_hash_ser.data.mem.device_ctypes_pointer.value)
----> 5 str_hash_ser.astype(np.int64)

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/series.py in astype(self, dtype, **kwargs)
   1412             return self
   1413 
-> 1414         return self._copy_construct(data=self._column.astype(dtype, **kwargs))
   1415 
   1416     def argsort(self, ascending=True, na_position="last"):

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/column.py in astype(self, dtype, **kwargs)
    923 
    924         else:
--> 925             return self.as_numerical_column(dtype, **kwargs)
    926 
    927     def as_categorical_column(self, dtype, **kwargs):

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/numerical.py in as_numerical_column(self, dtype, **kwargs)
    170     def as_numerical_column(self, dtype, **kwargs):
    171         return self.replace(
--> 172             data=libcudf.typecast.cast(self, dtype).data, dtype=np.dtype(dtype)
    173         )
    174 

cudf/_lib/typecast.pyx in cudf._lib.typecast.cast()

cudf/_lib/cudf.pyx in cudf._lib.cudf.check_gdf_compatibility()

TypeError: column type `uint32` not supported in gdf
```

**Work Around**

The current work around i am using is to use cupy arrays for casting as we don't support casting `uint32` . 

```python
token_ser = cudf.Series(['this','this','is','is','a','a','check','check'])

str_hash_array = librmm.device_array(len(token_ser), dtype=np.uint32)
token_ser.str.hash(devptr=str_hash_array.device_ctypes_pointer.value)
str_hash_array = cp.asarray(str_hash_array).astype(np.int64)
str_hash_ser = cudf.Series(str_hash_array)
str_hash_ser
```

**Comment by davidwendt** [comment]
`Must be able to hold at least size() of uint32 values. `
This means you can have size() or more of `uint32` values not.
The `least` part of the documentation was meant for the `size()` part and not the type.
We can change the documentation but I do not recommend a code change for this.
Providing the wrong type is not recommended for any API.

**Comment by VibhuJawa** [comment]
> `Must be able to hold at least size() of uint32 values. `
> This means you can have size() or more of `uint32` values.
> The `least` part of the documentation was meant for the `size()` part and not the type.
> We can change the documentation but I do not recommend a code change for this.
> Providing the wrong type is not recommended for any API.

Apologies, i read the documentation incorrectly.  Thanks for the clarifying. 

I am gonna change this from bug to a feature request to allow hashing to allow casting to `int64` because we don't have support for `uint32` in cudf columns which means we cant use the hashed values without going through another library for casting .

**Comment by davidwendt** [comment]
If it helps, you can use `np.int32` type here as well. It is harmless for the hash() function. It just means you get some values as negative which is still valid.
```
 import nvstrings
 from librmm_cffi import librmm as rmm
 import numpy as np
 s = nvstrings.to_device(['this','this','is','is','a','a','check','check'])

 hash1 = rmm.device_array(s.size(), dtype=np.uint32)
 s.hash(devptr=hash1.device_ctypes_pointer.value)
 print(hash1.copy_to_host())
```
```
 [1700036553 1700036553 4222932388 4222932388 3387765255 3387765255
 1169406292 1169406292]
```
```
 hash2 = rmm.device_array(s.size(), dtype=np.int32)
 s.hash(devptr=hash2.device_ctypes_pointer.value)
 print(hash2.copy_to_host())
```
```
[1700036553 1700036553  -72034908  -72034908 -907202041 -907202041
 1169406292 1169406292]
```
Then you can cast these to `int64` or whatever you need.

**Comment by VibhuJawa** [comment]
Got it.  Thanks for help . 

For context : Why, i wanted positive values is because I am trying to use these hashes as feature_ids which are supposed to be positive for following convention of https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.csr_matrix.html . 

I think you we can work around these via casting for now. 

I have added a feature request https://github.com/rapidsai/cudf/issues/2819 for uint32s so i am closing this for now .
