### ISSUE TITLE
[FEA] Support unsigned integer types

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2819]
**Is your feature request related to a problem? Please describe.**

I would like `cudf` to support for uint32 dtype .  Currently `rmm` supports  allocating `uint32` but we dont support it in  `cudf` columns. 

`uint32` is especially useful when we are dealing with `hashes` and will help some memory pressure for some work-flows where we have to cast/use them as `int64` instead.

**Additional context**

```python
cudf_col = cudf.Series(np.asarray([1,2,3],dtype=np.uint32))
# below throws an error
cudf_col+cudf_col
```
Stack Trace
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-d1865cad0700> in <module>
      1 cudf_col = cudf.Series(np.asarray([1,2,3],dtype=np.uint32))
----> 2 cudf_col+cudf_col

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/series.py in __add__(self, other)
    628 
    629     def __add__(self, other):
--> 630         return self._binaryop(other, "add")
    631 
    632     def radd(self, other, fill_value=None):

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/series.py in _binaryop(self, other, fn, reflect)
    567         lhs, rhs = _align_indices(self, other)
    568         rhs = self._normalize_binop_value(rhs)
--> 569         outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
    570         result = lhs._copy_construct(data=outcol, name=result_name)
    571         libcudf.nvtx.nvtx_range_pop()

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/numerical.py in binary_operator(self, binop, rhs, reflect)
     99                 op=binop,
    100                 out_dtype=out_dtype,
--> 101                 reflect=reflect,
    102             )
    103         else:

/data/vjawa/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/numerical.py in _numeric_column_binop(lhs, rhs, op, out_dtype, reflect)
    429     out = column.column_empty(row_count, dtype=out_dtype, masked=masked)
    430     # Call and fix null_count
--> 431     null_count = libcudf.binops.apply_op(lhs, rhs, out, op)
    432 
    433     if is_op_comparison:

cudf/_lib/binops.pyx in cudf._lib.binops.apply_op()

cudf/_lib/cudf.pyx in cudf._lib.cudf.check_gdf_compatibility()

TypeError: column type `uint32` not supported in gdf

```

**Comment by jrhemstad** [comment]
We can use this issue for tracking the addition of all unsigned integer types to libcudf. This is something we can tackle as https://github.com/rapidsai/cudf/pull/2207 is completed. 

For the short-term, why can't hash values be stored in int32? That's currently how they are returned in [`gdf_hash`](https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/include/cudf/functions.h#L202)

**Comment by VibhuJawa** [comment]
> We can use this issue for tracking the addition of all unsigned integer types to libcudf. This is something we can tackle as #2207 is completed.
> 
> For the short-term, why can't hash values be stored in int32? That's currently how they are returned in [`gdf_hash`](https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/include/cudf/functions.h#L202)

So, there are 2 parts to this: 

1. I am working with some data sets that directly provides us with uint32 hashed values  so we cant really work around that i think.  

2. Currently `nvstrings.hash` gives `uint32` as outputs which we can work around for some cases as you suggest.

**Comment by lmeyerov** [comment]
From #4243 : The current behavior from a ~primitive type is surprising -- creating uint's and converting them throws fairly gnarly-looking exceptions, making it unclear that this is not supported vs a bug, and is a landmine.

I recommend:
* Docs should clarify NotImplemented('uint')
* DF/Series  throw NotImplemented('uint')
* from_pandas etc. throw NotImplemented('uint')

**Comment by kkraus14** [comment]
Fixed by #5292 and #5431

**Comment by lmeyerov** [comment]
@kkraus14  Anywhere to understand the scope of new uint support? I'm trying to understand implications for end-to-end life cycle: readers -> compute -> writers, and in 0.15 vs later.

**Comment by kkraus14** [comment]
DLPack isn't quite supported yet: https://github.com/rapidsai/cudf/issues/5353
Parquet reading/writing isn't supported yet (will typecast to signed type): https://github.com/rapidsai/cudf/issues/5352
ORC reading/writing isn't supported yet (will typecast to signed type): https://github.com/rapidsai/cudf/issues/5351
