### ISSUE TITLE
[BUG] Slow Speed Running XGBoost from Rapids

### ISSUE THREAD

**Issue by FCheda** [rapidsai/cudf#2835]
Hi, I’m doing performance analysis over RAPIDS and I got to some kind of problem where using XGBoost from a dask-cudf dataframe is slower than working directly from pandas, I looked at it with RAPIDS.AI team in Slack but we weren’t able to find the bug.

Starting times where 25 minutes for RAPIDS vs 10 seconds to Pandas, we found that we needed to pass the Y parameter as dataframe instead of series to XGBoost from RAPIDs, and time dropped to 30 seconds, but still way over Pandas times.

I can’t upload the dataset used but you can download it if you accept the conditions, I’m using this Kaggle training set, more specifically a subset with the first 1 million rows. 
Reference, dataset. https://www.kaggle.com/c/LANL-Earthquake-Prediction
The subset used contain 2 columns, we operate it with rolling windows generating multiple statistics, I’ll paste the code afterwards, if you want to test generating a random set 2 columns x 1million rows in float 32 should work.

**Steps/Code to reproduce bug**

Code Jupyter/Python3:
•	First we load the dataframe, 1 million rows. 
•	Then we run the next function to generate the final dataset
•	Last we run both versions of code, pandas/scikit-learn  - rapids
•	We compare the times 
Its quite a long post so I hope it helps, but please contact me if I can add anything else.

### code etl
```Python


def rolling(df):
    #mean
    df['mean_5'] = df['acoustic_data'].rolling(5).mean().astype("float32")
    df['mean_10'] = df['acoustic_data'].rolling(10).mean().astype("float32")
    df['mean_100'] = df['acoustic_data'].rolling(100).mean().astype("float32")
    df['mean_1000'] = df['acoustic_data'].rolling(1000).mean().astype("float32")
    df['mean_10000'] = df['acoustic_data'].rolling(10000).mean().astype("float32")
    #std
    df['std_5'] = df['acoustic_data'].rolling(5).std().astype("float32")
    df['std_10'] = df['acoustic_data'].rolling(10).std().astype("float32")
    df['std_100'] = df['acoustic_data'].rolling(100).std().astype("float32")
    df['std_1000'] = df['acoustic_data'].rolling(1000).std().astype("float32")
    df['std_10000'] = df['acoustic_data'].rolling(10000).std().astype("float32")
    #var
    df['var_5'] = df['acoustic_data'].rolling(5).var().astype("float32")
    df['var_10'] = df['acoustic_data'].rolling(10).var().astype("float32")
    df['var_100'] = df['acoustic_data'].rolling(100).var().astype("float32")
    df['var_1000'] = df['acoustic_data'].rolling(1000).var().astype("float32")
    df['var_10000'] = df['acoustic_data'].rolling(10000).var().astype("float32")
    #median ->
    df['median_5'] = df['acoustic_data'].rolling(5).median().astype("float32")
    df['median_10'] = df['acoustic_data'].rolling(10).median().astype("float32")
    df['median_100'] = df['acoustic_data'].rolling(100).median().astype("float32")
    df['median_1000'] = df['acoustic_data'].rolling(1000).median().astype("float32")
    df['median_10000'] = df['acoustic_data'].rolling(10000).median().astype("float32")
    #quantiles -> not implemented in cuda
    df['quantile_025_5'] = df['acoustic_data'].rolling(5).quantile(0.25).astype("float32")
    df['quantile_025_10'] = df['acoustic_data'].rolling(10).quantile(0.25).astype("float32")
    df['quantile_025_100'] = df['acoustic_data'].rolling(100).quantile(0.25).astype("float32")
    df['quantile_025_1000'] = df['acoustic_data'].rolling(1000).quantile(0.25).astype("float32")
    df['quantile_025_10000'] = df['acoustic_data'].rolling(10000).quantile(0.25).astype("float32")
    
    df['quantile_075_5'] = df['acoustic_data'].rolling(5).quantile(0.75).astype("float32")
    df['quantile_075_10'] = df['acoustic_data'].rolling(10).quantile(0.75).astype("float32")
    df['quantile_075_100'] = df['acoustic_data'].rolling(100).quantile(0.75).astype("float32")
    df['quantile_075_1000'] = df['acoustic_data'].rolling(1000).quantile(0.75).astype("float32")
    df['quantile_075_10000'] = df['acoustic_data'].rolling(10000).quantile(0.75).astype("float32")
    #skew
    df['skew_5'] = df['acoustic_data'].rolling(5).skew().astype("float32")
    df['skew_10'] = df['acoustic_data'].rolling(10).skew().astype("float32")
    df['skew_100'] = df['acoustic_data'].rolling(100).skew().astype("float32")
    df['skew_1000'] = df['acoustic_data'].rolling(1000).skew().astype("float32")
    df['skew_10000'] = df['acoustic_data'].rolling(10000).skew().astype("float32")
    #kurt
    df['kurt_5'] = df['acoustic_data'].rolling(5).kurt().astype("float32")
    df['kurt_10'] = df['acoustic_data'].rolling(10).kurt().astype("float32")
    df['kurt_100'] = df['acoustic_data'].rolling(100).kurt().astype("float32")
    df['kurt_1000'] = df['acoustic_data'].rolling(1000).kurt().astype("float32")
    df['kurt_10000'] = df['acoustic_data'].rolling(10000).kurt().astype("float32")
    #min and max
    df['min_5'] = df['acoustic_data'].rolling(5).min().astype("float32")
    df['min_10'] = df['acoustic_data'].rolling(10).min().astype("float32")
    df['min_100'] = df['acoustic_data'].rolling(100).min().astype("float32")
    df['min_1000'] = df['acoustic_data'].rolling(1000).min().astype("float32")
    df['min_10000'] = df['acoustic_data'].rolling(10000).min().astype("float32")
    
    df['max_5'] = df['acoustic_data'].rolling(5).max().astype("float32")
    df['max_10'] = df['acoustic_data'].rolling(10).max().astype("float32")
    df['max_100'] = df['acoustic_data'].rolling(100).max().astype("float32")
    df['max_1000'] = df['acoustic_data'].rolling(1000).max().astype("float32")
    df['max_10000'] = df['acoustic_data'].rolling(10000).max().astype("float32")
    
%time rolling(df)
df.head()
```

### code ,  pandas and so on …
```Python
import os
import numpy as np
import pandas as pd
import zipfile
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
import xgboost as xgb

%time df = pd.read_csv(datafolder+"train_1M_0.csv").set_index("Unnamed: 0")
%time rolling(df)
df=df.dropna()
df=(df-df.mean())/df.std()
df2=df.dropna()
#df2=(df2-df2.mean())/df2.std()
#X=df2.iloc[:,2:]
#X["acoustic_data"]=df2["acoustic_data"]
X=df2.drop(columns=["time_to_failure"])
y=df2.loc[:,"time_to_failure"]
%time X_train, X_test, y_train, y_test=sklearn.model_selection.train_test_split(X,y)

params = {
  'num_rounds':   100,
  'max_depth':    12,
  'max_leaves':   2**10,
  'n_gpus':       1,
  'tree_method':  'gpu_hist',
  'objective':    'reg:squarederror',
  'grow_policy':  'lossguide'
}

%time xgtrain = xgb.DMatrix(X_train.values, y_train.values)
%time xgtest = xgb.DMatrix(X_test.values)

%time bst = xgb.train(params, xgtrain,num_boost_round=100)
%time preds=bst.predict(xgtest)

pr=pd.DataFrame(preds)
pr["truth"]=y_test.reset_index()["time_to_failure"]
rmse=((pr[0] - pr["truth"]) ** 2).mean() ** .5
print("rmse ",rmse)
```
### code rapids

```Python
# dask client
import os
import numpy as np
import pandas as pd
import zipfile
import dask
import dask_cudf
import dask.dataframe as dd
from dask.distributed import Client, wait,LocalCluster
from dask_cuda import LocalCUDACluster
from dask_ml.model_selection import train_test_split
import subprocess

#%env NCCL_P2P_DISABLE=1
cmd = "hostname --all-ip-addresses"
process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
output, error = process.communicate()
IPADDR = str(output.decode()).split()[0]
dask.config.set(temporary_directory='/media/fcheda/My Passport/tmp')
dask.config.set(local_dir='/media/fcheda/My Passport/dask')
#dask.config.set(temporary_directory='/tmp')
cluster = LocalCUDACluster(ip=IPADDR,local_dir='/media/fcheda/My Passport/dask')
client = Client(cluster)#this limits it to just 1 gpu cluster

#client=Client()
client
#code
import cudf
import cuml
import dask_cudf


df = dd.read_csv(datafolder+"train_1M_0.csv",blocksize=150000).set_index("Unnamed: 0")#.loc[0:10000000]#.sample(frac=0.01)#lets change and read only 10 million rows with nrows 
#df=dd.DataFrame(df,name=",meta=,divisions=)
df=df.repartition(npartitions=10)#reduce partitions when reduce size
df.npartitions
%time rolling(df)
df=df.dropna()
df=(df-df.mean())/df.std()
ddf=dask_cudf.from_dask_dataframe(df)
ddf["acoustic_data"]=ddf["acoustic_data"].astype("float32")

X=ddf.iloc[:,2:]
X["acoustic_data"]=ddf["acoustic_data"]
y=ddf[["time_to_failure"]] #changing this from series to datagrame changed from 35 min to 35 seconds
%time X_train, X_test, y_train, y_test=train_test_split(X,y)#default test size 0.25
%time X_train.compute()
%time y_train.compute()
print("y type ",type(y_train))
%time bst = dask_xgboost.train(client, params, X_train,y_train, num_boost_round=params['num_rounds'])

```

**Expected behavior**

Rapids version of the code should be faster than pandas version. Or in the worst case have the same speed but not lower. 

**Environment Details**
System and environment:
•	I’m working with v0.9 version of RAPIDS
•	Ubuntu 18.04
•	64 GB ram
•	CPU Intel i7-7820X 3.6GHZ
•	GPU NVIDIA Titan Xp Collectors Edition

**Aditional context**

This problem was found during a performance analysis of pandas and scikit-learn vs rapids, this was the last test. In most other cases rapids was faster when implemented with accelerations from 0,6 in linear reggresion, 2,6 in ridge or 287 in logistic regression ( git does not like me trying to copy the full tables XD)

**Update**
I updated the post to clean it a little and mark areas as code
Update 2, changed pandas code as i uploaded a wrong one

**Comment by JohnZed** [comment]
Hi, @FCheda - when you mention the very long times, are you timing the whole workflow, or just xgboost.train at the end?

**Comment by FCheda** [comment]
Just xgboost.train

**Comment by JohnZed** [comment]
Sorry for the extra work, @FCheda - but would you be able to post or upload the original notebook or code file at least for the "dask client" section? github has mangled the code a bit, and I want to make sure we repro it exactly.

**Comment by trivialfis** [comment]
@FCheda 

The command used to extract 1M rows:
``` bash
head -n 1000000 ./train.csv > train_1M_0.csv
```

I modified your script a little bit to simplify things, attached below.  And here is the console output:
```
npartitions: 10
persist: 0.08715581893920898
y type  <class 'dask_cudf.core.DataFrame'>
[01:00:06] Initialized DMatrix from CUDF with 900231 rows and 1 cols.
Training: 4.325560808181763
Totaling: 6.42704439163208

```

### Code
``` python
import dask_cudf
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster, Future
from dask_cuda import LocalCUDACluster
from dask_ml.model_selection import train_test_split
import dask_xgboost
from time import time

import cudf
import dask_cudf


def train():
    cluster = LocalCUDACluster(n_workers=1)
    client = Client(cluster)  # this limits it to just 1 gpu cluster

    df = dd.read_csv("train_1M_0.csv", blocksize=150000)
    df = df.repartition(npartitions=10)  # reduce partitions when reduce size
    print('npartitions:', df.npartitions)

    df = df.dropna()
    df = (df - df.mean()) / df.std()
    ddf = dask_cudf.from_dask_dataframe(df)
    # ddf["acoustic_data"] = ddf["acoustic_data"].astype("float32")

    X = ddf.iloc[:, 2:]
    X["acoustic_data"] = ddf["acoustic_data"]
    y = ddf[[
        "time_to_failure"
    ]]
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    start = time()
    X_train = X_train.persist()
    y_train = y_train.persist()
    print('persist:', time() - start)

    print("y type ", type(y_train))
    params = {
        'num_rounds': 100,
        'max_depth': 12,
        'max_leaves': 2**10,
        'tree_method': 'gpu_hist',
        'objective': 'reg:squarederror',
        'grow_policy': 'lossguide',
        'verbosity': 2
    }
    start = time()
    bst = dask_xgboost.train(client,
                             params,
                             X_train,
                             y_train,
                             num_boost_round=params['num_rounds'])
    assert bst is not Future
    print('Training:', time() - start)


if __name__ == '__main__':
    start = time()
    train()
    print('Totaling:', time() - start)

```

**Comment by trivialfis** [comment]
@FCheda 

Here is the command line used to extract 1M rows:
``` bash
head -n 1000000 ./train.csv > train_1M_0.csv
```

I modified your script a little bit to simplify things and it's attached below.  Here is the console output:
```
npartitions: 10
persist: 0.08715581893920898
y type  <class 'dask_cudf.core.DataFrame'>
[01:00:06] Initialized DMatrix from CUDF with 900231 rows and 1 cols.
Training: 4.325560808181763
Totaling: 6.42704439163208
```

### code
``` python
import dask_cudf
import dask.dataframe as dd
from dask.distributed import Client, LocalCluster
from dask_cuda import LocalCUDACluster
from dask_ml.model_selection import train_test_split
import dask_xgboost
from time import time

import cudf
import dask_cudf


def train():
    cluster = LocalCUDACluster(n_workers=1)
    client = Client(cluster)  # this limits it to just 1 gpu cluster

    df = dd.read_csv("train_1M_0.csv", blocksize=150000)
    df = df.repartition(npartitions=10)  # reduce partitions when reduce size
    print('npartitions:', df.npartitions)

    df = df.dropna()
    df = (df - df.mean()) / df.std()
    ddf = dask_cudf.from_dask_dataframe(df)
    # ddf["acoustic_data"] = ddf["acoustic_data"].astype("float32")

    X = ddf.iloc[:, 2:]
    X["acoustic_data"] = ddf["acoustic_data"]
    y = ddf[[
        "time_to_failure"
    ]]
    X_train, X_test, y_train, y_test = train_test_split(X, y)

    start = time()
    X_train = X_train.persist()
    y_train = y_train.persist()
    print('persist:', time() - start)

    print("y type ", type(y_train))
    params = {
        'num_rounds': 100,
        'max_depth': 12,
        'max_leaves': 2**10,
        'tree_method': 'gpu_hist',
        'objective': 'reg:squarederror',
        'grow_policy': 'lossguide',
        'verbosity': 2
    }
    start = time()
    bst = dask_xgboost.train(client,
                             params,
                             X_train,
                             y_train,
                             num_boost_round=params['num_rounds'])
    print('Training:', time() - start)


if __name__ == '__main__':
    start = time()
    train()
    print('Totaling:', time() - start)

```

**Comment by FCheda** [comment]
Hi

I'll check this afternoon and upload a clean full ipython notebook. 

@trivialfis :, 

- if im not missing anything you are getting 4 seconds training over a dataset of 1 million rows with 2 columns.
- for what i see you are not calling df=rolling(df) witch uses rolling windows to generate way more columns (50 extra)
- if thats correct you are getting 4 seconds with 2 columns, i got 4 seconds on pandas with the 52 columns and 30+ seconds from rapids on train.

Please tell me if i messed anything, as i said after work i will upload a cleaned notebook so you can run it.

 (You will still need to download the original data if you want to use that, accepting the competition rules, or generate a random dataset but i can add that too to the notebook)

**Comment by trivialfis** [comment]
@Fcheda Thanks!  I can reproduce it now. It got stuck somewhere in between dask and XGBoost.

**Comment by trivialfis** [comment]
@kkraus14 I tried to look into this a bit more.  So if I use cudf to load the data directly (removing dask from the middle), `df['std_5'].rolling(5).astype('float32')` results in a `NotImplementedError: <class 'cudf.dataframe.string.StringColumn'>`.  Is it possible that the slowness is due to dask_cudf doing these thing on CPU instead of GPU?

**Comment by FCheda** [comment]
You have to load with pandas . Then run the rolling windows function and
afterward moving it to cudf. Those statistics are not implemented yet on
cudf for rolling windows.

Sorry for the short answer but im in the phone now xd

**Comment by trivialfis** [comment]
Okay.  Now we know why the slowness.  :-)
________________________________

**Comment by kkraus14** [comment]
> Okay. Now we know why the slowness. :-)

Yea this all makes sense now. We aren't forcing evaluation of the dask task graph anywhere so when the DMatrix is trying to be constructed it forces evaluation and the Pandas operations make things seem slow.

**Comment by FCheda** [comment]
Sorry for asking but shouldnt persist and compute commands force the computation to be done so the time does not affect the xgboost training time. ?

Did you test forcing the computation and got better times? I just did a test even calling 2 times the train function one after another and times were the same in both cases.

I'm not sure if i'm missing something

**Comment by kkraus14** [comment]
> Sorry for asking but shouldnt persist and compute commands force the computation to be done so the time does not affect the xgboost training time. ?
> 
> Did you test forcing the computation and got better times? I just did a test even calling 2 times the train function one after another and times were the same in both cases.
> 
> I'm not sure if i'm missing something

Calling `.persist()` returns a Future immediately and forces the computation to run in the background and for the task graph to stay computed up to that point. Calling `.compute()` forces computation and a transfer of the result to the client process, but doesn't keep computations around, so if you call `.compute()` again it will recompute the task graph.

This is exacerbated that your LocalCUDACluster will only create 1 worker (1 GPU), and you're using 10 partitions, so no matter what before actually creating the DMatrix, it will shuffle the data to a single partition and that shuffling is expensive both for memory and time.

Given you only have a single GPU and XGBoost doesn't yet support larger than GPU memory workloads, you'd be better off just using cuDF directly here as opposed to using it with Dask. It will greatly simplify your workflow and give you the best performance.

**Comment by FCheda** [comment]
@kkraus

Se after your last post i wanted to do some more test to try to understand the problem better.

As you said, calling directly XGBoost from the Dmatrix has no diference works the same either using rapids or not before, as my preprocessing cant be done in the current version of rapids that would not let me compare anything in this specific test (as i said is just one of the tests i did)

Still i wanted to check a little bit more the dask-cudf-> xgboost option.

I changed the repartition to 1 partition, as you said i have only one gpu so if i have more partitions will mean extra suffle of data.

Then i looked to the dashboard, and even after i had called persist, each time i called xgbost-train all the dask operations were executed again (i thought it will be only done the first time but i seams i was wrong)

This code runs all dask graph for both calls of xgboost.train.

```Python
f1=client.persist(X_train)
f2=client.persist(y_train)
print("y type ",type(y_train))
%time bst = dask_xgboost.train(client, params, X_train,y_train, num_boost_round=params['num_rounds'])
%time bst = dask_xgboost.train(client, params, X_train,y_train, num_boost_round=params['num_rounds'])
```

If i add the wait function

```Python
wait(f1)
wait(f2)
```

I in both calls it takes 10 seconds. knowing that from dmatrix took 8,5 seconds + about half second to generate the dmatrix times are about the same, with a little overhead from dask for what it seams.

#from dask-cudf (train from dask-cudf dataframe)
CPU times: user 1.23 s, sys: 86.4 ms, total: 1.32 s
Wall time: 9.74 s

#from pandas/ dmatrix (dmatrix + train)
CPU times: user 1.7 s, sys: 268 ms, total: 1.97 s
Wall time: 568 ms
CPU times: user 1.44 s, sys: 130 ms, total: 1.57 s
Wall time: 197 ms
CPU times: user 10.2 s, sys: 1.28 s, total: 11.4 s
Wall time: 8.35 s

Not sure if you want to close the issue or there is something else that you think we should check.
