### ISSUE TITLE
[FEA] Support copy parameter in astype

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2839]
For dask-related API compatibility (see #2719 ), we should include a `copy` argument in `astype`, like pandas. It seems `copy` is used to return a view in some cases (perhaps when possible), such as when the dtype does not change. We may need to actually implement the view behavior to move forward, so we need to be able to set `copy=True | copy=False`.

```python
s1 = pd.Series([1,2], dtype='int64')
s2 = s1.astype('int64', copy=False)
s2[0] = 10
print(s1)
print(s2)
0    10
1     2
dtype: int64
0    10
1     2
dtype: int64
```

```python
s1 = pd.Series([1,2], dtype='int64')
s2 = s1.astype('int32', copy=False)
s2[0] = 10
print(s1)
print(s2)
0    1
1    2
dtype: int64
0    10
1     2
dtype: int32
```

**Comment by UmashankarTriforce** [comment]
I would like to work on this issue. May I know the specifics and details?

**Comment by AK-ayush** [comment]
@beckernick I have opened a PR #3692 addressing this feature. Please let me know whether this is desired behaviour?
```python
# with copy=False
s1 = cudf.Series([1,2], dtype='int64')
s2 = s1.astype('int64', copy=False)
s2[0] = 10
print(s1)
print(s2)
0    10
1     2
dtype: int64
0    10
1     2
dtype: int64

s3 = s1.astype('int32', copy=False)
s3[0] = 1
print(s1)
print(s3)
0    1
1    2
dtype: int32
0    1
1    2
dtype: int32


# with copy=True 
s1 = cudf.Series([1,2], dtype='int64')
s2 = s1.astype('int64', copy=True)
s2[0] = 11
print(s1)
print(s2)
0    1
1    2
dtype: int64
0    11
1     2
dtype: int64

s3 = s1.astype('int32', copy=True)
s3[0] = 11
print(s1)
print(s3)
0    1
1    2
dtype: int64
0    11
1     2
dtype: int32

```


post that i will update/add the unit tests.

**Comment by galipremsagar** [comment]
This is resolved as part of : https://github.com/rapidsai/cudf/pull/5162
