### ISSUE TITLE
[DISCUSSION] Toward using cuDF methods inside efficient Python UDFs

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2846]
When writing UDFs that operate independently on rows, groups, or windows, I currently have to choose between:
- Using cuDF methods inside my function and processing my data sequentially
- Leveraging Numba.cuda for significant parallelism

I'd like to use cuDF methods inside UDFs that run quickly either across rows (`apply_rows/chunks`) or across groups (`apply_grouped`). A desired end result might look something like the code below but run on the entire data in parallel, rather than on each group sequentially as currently happens in [this codepath](https://github.com/rapidsai/cudf/blob/68a7513d9026074bc42992549efee1741a702541/python/cudf/cudf/core/groupby/legacy_groupby.py#L392).

```python
import cudf
from cudf.datasets import randomdata
​
df = randomdata(nrows=20,
                dtypes={'a':int, 'b':str, 'c':str, 'd':int},
                seed=12)

grouped = df.groupby(['a'], method="cudf")
​
def name_filter(data):
    group_specific_names = data[data.b == 'Victor']['d'].unique()
    return data[data.d.isin(group_specific_names)]
​
res = grouped.apply(name_filter)
print(df.head())
print(res.head())
      a       b       c     d
0   963   Frank   Quinn   936
1   977     Tim   Frank  1005
2  1048  Victor  Ursula  1025
3  1078   Laura   Quinn  1004
4   979   Alice     Dan   959
       a       b       c     d
10   997  Victor   Kevin   994
18  1048  Victor  Ursula  1025
```

One way to do this might be to allow Numba to understand cuDF types, such as through expanding [jitclass](https://numba.pydata.org/numba-doc/dev/user/jitclass.html) to support GPUs and then creating one for cuDF, though I'm clear on if this would be successful. There are perhaps several other ways we could work towards this future state. I'm creating this issue to have a central location to discuss this.

**Comment by harrism** [comment]
We discussed this in a meeting and one outcome is that we really should profile the existing implementation before we decide how to proceed, because there may be low-hanging fruit. Can we get a benchmark with realistic data sizes to profile?

**Comment by beckernick** [comment]
@harrism We'll provide a benchmark on various data sizes to help evaluate.

With that said, from the codepath we can know in advance that any UDF applied to a legacy groupby will scale linearly in the number of groups, with real-world variations due to the differences in group sizes.

**Comment by harrism** [comment]
Scaling with the number of groups is as it should be when iterating over groups sequentially.  But still worth profiling.

**Comment by beckernick** [comment]
@harrism I agree --this is behaving as expected. The issue is that as we scale to more groups and non-trivial operations, the time cost can become significant.

The following benchmarks exhibit what I mean (I'll add a profile as soon as I can as well):

The columns `group_ratio` and `time_ratio` indicate the scaling ratio of num_groups and time_seconds (previous value divided by the next value, thus the NaN in the first row). As expected they scale consistently.

```python
import time

import pandas as pd
import cudf
from cudf.datasets import randomdata

def udf_filter(data):
    return data['b'] * data['c']

timetable = []
nrows = [10, 100, 500, 1000, 2000]

for rows in nrows:
    df = randomdata(nrows=rows,
                dtypes={'a':int, 'b':int, 'c':int, 'd':int},
                seed=12)
    
    unique_group_count = df.a.unique().shape[0]
    
    grouped = df.groupby(['a'], method="cudf")
    t0 = time.time()
    res = grouped.apply(udf_filter)
    t1 = time.time()
    timetable.append((rows, unique_group_count, t1-t0))

result_df = pd.DataFrame(timetable, columns=['nrows', 'num_groups', 'time_seconds'])
result_df['group_ratio'] = result_df.num_groups / result_df.num_groups.shift(1)
result_df['time_ratio'] = result_df.time_seconds / result_df.time_seconds.shift(1)
result_df
   nrows  num_groups  time_seconds  group_ratio  time_ratio
0     10           9      0.043333          NaN         NaN
1    100          67      0.276602     7.444444    6.383224
2    500         135      0.560102     2.014925    2.024943
3   1000         151      0.625394     1.118519    1.116570
4   2000         167      0.869246     1.105960    1.389918
```

```python
import time

import pandas as pd
import cudf
from cudf.datasets import randomdata

def udf_filter(data):
    group_specific_d = data[data.b == 'Victor']['d'].unique()
    return data[data.d.isin(group_specific_d)]

timetable = []
nrows = [10, 100, 500, 1000, 2000]

for rows in nrows:
    df = randomdata(nrows=rows,
                dtypes={'a':int, 'b':str, 'c':str, 'd':int},
                seed=12)
    
    unique_group_count = df.a.unique().shape[0]
    
    grouped = df.groupby(['a'], method="cudf")
    t0 = time.time()
    res = grouped.apply(udf_filter)
    t1 = time.time()
    timetable.append((rows, unique_group_count, t1-t0))

result_df = pd.DataFrame(timetable, columns=['nrows', 'num_groups', 'time_seconds'])
result_df['group_ratio'] = result_df.num_groups / result_df.num_groups.shift(1)
result_df['time_ratio'] = result_df.time_seconds / result_df.time_seconds.shift(1)
print(result_df)
   nrows  num_groups  time_seconds  group_ratio  time_ratio
0     10           9      0.728335          NaN         NaN
1    100          67      4.140603     7.444444    5.685028
2    500         135      8.271440     2.014925    1.997641
3   1000         151      9.438513     1.118519    1.141097
4   2000         167     10.619956     1.105960    1.125173
```

If methods like `unique`, `isin`, and others take between one and 50 milliseconds per call, the time cost adds up quickly. A complex UDF will likely chain multiple methods together.

**Comment by harrism** [comment]
This request is very difficult in the general case. This is why I want to eliminate all low hanging fruit possible first. And we are likely to need to constrain what you can do in a udf. We are nowhere near the point where we can enable users to call arbitrary cudf functions inside a UD and JIT that to GPU code...

**Comment by beckernick** [comment]
Within `groupby.apply` (key Python lines copied below), the overwhelming majority of the time is spent executing the cuDF operations in the `name_filter` UDF.

https://github.com/rapidsai/cudf/blob/af4ef6de8cb09d45f1810eb0962c1b0c04b8b56c/python/cudf/cudf/core/groupby/legacy_groupby.py#L392-L399

90-95% of the time is spent executing the UDF in the list comprehension:

https://github.com/rapidsai/cudf/blob/af4ef6de8cb09d45f1810eb0962c1b0c04b8b56c/python/cudf/cudf/core/groupby/legacy_groupby.py#L399

About 3-5% is spent creating the chunks:

https://github.com/rapidsai/cudf/blob/af4ef6de8cb09d45f1810eb0962c1b0c04b8b56c/python/cudf/cudf/core/groupby/legacy_groupby.py#L398

The remainder of the time is spent in `concat` step of line 398 (shown above), with a miniscule amount coming from calling `as_df()`, here:

https://github.com/rapidsai/cudf/blob/af4ef6de8cb09d45f1810eb0962c1b0c04b8b56c/python/cudf/cudf/core/groupby/legacy_groupby.py#L396

With 90-95% of the "udf execution", I believe we'd be rate limited to about 5-11% speedups if we functionally eliminated the time spent in the other segments (outside of optimizing the operations themselves).

![Screen Shot 2019-10-02 at 2 03 32 PM](https://user-images.githubusercontent.com/8457388/66070975-4a504700-e520-11e9-9246-a6c54902dce2.png)

![Screen Shot 2019-10-02 at 2 21 05 PM](https://user-images.githubusercontent.com/8457388/66071005-5805cc80-e520-11e9-87ee-cfa272f25368.png)


cc @randerzander

**Comment by kkraus14** [comment]
Stale, closing.
