### ISSUE TITLE
[BUG] CSV parser inits row offsets vector on CPU before GPU copy clobbers it

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#2849]
**Describe the bug**
`csv::reader::Impl::select_rows` constructs a vector of row offsets, `h_row_offsets`.  This can be a non-trivial size if a large amount of CSV data is being parsed with relatively few bytes per row.  The CPU zero-initializes this vector before it is clobbered by a GPU memcpy, and the CPU can spend many milliseconds performing this unnecessary initialization.

**Steps/Code to reproduce bug**
Take an nsight trace of `read_csv` on 2GB+ of CSV input and notice the gap of idle GPU time after the GPU counting kernels complete but before the `cudaMemcpyAsync` from device to host is issued.  This time gap is largely due to the CPU zero-initializing `h_row_offsets` which will ultimately be overwritten by the `cudaMemcpyAsync` call.

**Comment by j-ieong** [comment]
This is still a remnant of the old design. Ultimately, we would either implicitly have the `select_row()` step part of `gather_row()` kernel operation or do it similarly as ORC and Parquet readers and use pinned memory rather than `std::vector` if still requiring host access.
