### ISSUE TITLE
Support pip install

### ISSUE THREAD

**Issue by impredicative** [rapidsai/cudf#285]
Please support pip installation using PyPI.

**Comment by feluelle** [comment]
+

**Comment by yutiansut** [comment]
+1

**Comment by wbadart** [comment]
Until full support is added, you can pull straight from github with `pip install git+https://github.com/rapidsai/pygdf`. HOWEVER you'll need to have pandas, pyarrow (both available from pip) and [libgdf](https://github.com/rapidsai/libgdf) already installed. Maybe pandas and pyarrow should be added to `install_requires` in setup.py?

**Comment by jangorecki** [comment]
@wbadart 7 days ago libgdf you linked has been archived, do we still need it for installation using pip?

**Comment by wbadart** [comment]
Yup, still going to need it no matter how you install the python library. It seems that nvidia's reorganized the code, so now libgdf lives here in this repository (unsurprisingly, in the [libgdf](https://github.com/rapidsai/cudf/tree/master/libgdf) directory).

Someone from nvidia, please correct me if I'm wrong, but my understanding of this cuDF package is that libgdf is the "core" implementation; the code that actually runs on your GPU(s), and cuDF is a python library that hooks into this implementation through a foreign function interface (FFI, a more general computing pattern for coding in multiple languages, in this case python and cuda). You can read the configuration of this FFI [here](https://github.com/rapidsai/cudf/tree/master/libgdf/python).

**Comment by jangorecki** [comment]
Is this issue solved already? PR for that has been merged.
When attempting to install from pip I am getting the following:
```sh
python -m pip install cudf-cuda100
Collecting cudf-cuda100
  Could not find a version that satisfies the requirement cudf-cuda100 (from versions: )
No matching distribution found for cudf-cuda100
```
Looks like that there is a part of error message after `from versions: `
```
nvcc --version
#nvcc: NVIDIA (R) Cuda compiler driver
#Copyright (c) 2005-2018 NVIDIA Corporation
#Built on Sat_Aug_25_21:08:01_CDT_2018
#Cuda compilation tools, release 10.0, V10.0.130
```

**Comment by raydouglass** [comment]
The pip packages have not been published yet. They will be published when v0.5 is released.

**Comment by kkraus14** [comment]
> When will v0.5 be released? (Strange that the instructions are published before the version is why I ask)

We're working on releasing right now, so hopefully by the end of the week.

**Comment by blackrim** [comment]
Great!

sent while on the move. please forgive any errors

**Comment by datametrician** [comment]
@blackrim that was merged into the 0.5 branch.  once it's merged to master, pip will be released. Sorry for the confusion.

**Comment by impredicative** [comment]
There is at this time no package on PyPI named [cudf-cuda92](https://pypi.org/project/cudf-cuda92) or [cudf-cuda100](https://pypi.org/project/cudf-cuda100) as are noted in the readme. Am I missing something here? Why is this issue closed prematurely without an actual release?

**Comment by mike-wendt** [comment]
@impredicative this [README.md](https://github.com/rapidsai/cudf/blob/master/README.md) is the **current stable release** and it has no mention of pip installs. What you see by default is `branch-0.6` and it is a WIP. To prevent confusion this [commit](https://github.com/rapidsai/cudf/commit/f4dd5ac0e625d769bde2f21146d53dd307b07a67) was added to have a link to the `README.md` on the master branch at the top.

pip installs are coming in v0.5 and we are working through issues that are blocking the release. Please track #786 for when they are available.

**Comment by jangorecki** [comment]
What is the status the issue?
I cannot see any pip installation instruction in `master` branch and 0.9 and 0.8 branches.
What is the most recent release available in pip?

**Comment by kkraus14** [comment]
@jangorecki We are no longer supporting pip installs as the wheel packaging situation is unsustainable. We are continuing to support conda and docker moving forward.

For more information you can read about what lead to this decision here: https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472
