### ISSUE TITLE
[BUG] Missing arch flag in CMakelists for T4

### ISSUE THREAD

**Issue by kaatish** [rapidsai/cudf#2853]
Cmake needs to be updated with the correct arch for T4 (compute capability 7.5) [here](https://github.com/rapidsai/cudf/blob/8e5c1f28ee82fb5f078388e8a15f298b1eea201b/cpp/CMakeLists.txt#L66).

As of now `__CUDA_ARCH__` does not correctly identify the compute capability of T4 in kernel code.

**Comment by kkraus14** [comment]
Resolved in 0.11.
