### ISSUE TITLE
[BUG] Discrepancy in behavior for Categorical series dtype

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#2864]
**Describe the bug**

Currently, when we create a `cudf.Series` from a pandas categorical series we dont set the categories in the `CategoricalDtype` of the column while pandas sets those categories in the `CategoricalDtype` . (See below example) 

Thi discrepancy in  behavior is causing issues downstream in dask related issues (#2862 and #2269) as dask has a  function [equal_dtypes](https://github.com/dask/dask/blob/0922a872e34445970c65d2275ed56a920f7d826d/dask/dataframe/utils.py#L593-L600) which it uses for inferring if dtypes are equal. 
 

**Steps/Code to reproduce bug**
#### Cudf Series

```python 
cudf_ser = cudf.Series(pd.Categorical.from_codes([0,0], ['a','b']))
cudf_ser.dtype
```
output
```
CategoricalDtype(categories=None, ordered=False)
```

#### Pandas Series
```
pd_ser = pd.Series(pd.Categorical.from_codes([0,0], ['a','b']))
pd_ser.dtype
```
output
```
CategoricalDtype(categories=['a', 'b'], ordered=False)
```

**Expected behavior**

I would expect the behavior to be same as pandas.

### Additional Context

We need a way to set the categories at these lines (and other lines where we use `CategoricalDtype`) but as this is a `pandas dtype ` and these codes are stored on device (and can be a `nvstrings` object) we may want to implement our own wrapper of the said `CategoricalDtype` . 

https://github.com/rapidsai/cudf/blob/86760c316f98cf46ea3b7bdbe51cfdab75366f9d/python/cudf/cudf/core/column/categorical.py#L235

https://github.com/rapidsai/cudf/blob/86760c316f98cf46ea3b7bdbe51cfdab75366f9d/python/cudf/cudf/core/column/categorical.py#L115

CC: @shwina , @trxcllnt

**Comment by shwina** [comment]
Thanks for reporting! Assigning to self after discussion with @trxcllnt
