### ISSUE TITLE
[FEA] Please fully implement Pandas DataFrame.filna

### ISSUE THREAD

**Issue by hokiegeek2** [rapidsai/cudf#2866]
**Is your feature request related to a problem? Please describe.**
Would like cudf DataFrame to fully implement Pandas DataFrame.fillna.  In particular, would like the ability to pass dict of column -> value mappings

**Comment by ayushdg** [comment]
Cudf supports the following:
```
import numpy as np
import cudf

df = cudf.DataFrame()
df['a'] = [1,2,None,3]
df['b'] = [1.2,np.nan,None,3]
df['c'] = ['a',None,None,None]
print(df)
```
```
      a     b     c
0     1   1.2     a
1     2  null  None
2  null  null  None
3     3   3.0  None
```
```
print( df.fillna( { 'a':12, 'b': 1.5, 'c': 'ABC' } ) )
```
```
    a    b    c
0   1  1.2    a
1   2  1.5  ABC
2  12  1.5  ABC
3   3  3.0  ABC
```
Is this what you are looking for?


Note: Tested on the latest nightly (v0.10) but should work for stable (v0.9) as well.

**Comment by kkraus14** [comment]
Closing due to lack of response.
