### ISSUE TITLE
[QST] Out of Memory when counting number of rows using multiple parquet fles

### ISSUE THREAD

**Issue by chochim** [rapidsai/cudf#2871]
I have 500 parquet files. Each parquet file is SNAPPY compressed and is around 200MB of size. Parquet consists of three columns. Each column is a string.

I am trying to find the number of rows using the following code:

```python
cluster = LocalCUDACluster(ip=sched_ip, n_workers=num_of_gpus)
client = Client(cluster)
df = dask_cudf.read_parquet(path_to_local, columns=['col1','col2'])
rows, cols = df.shape
num_rows = rows.compute()
```

It throws a Runtime Exception: ```Exception: RuntimeError('parallel_for failed: out of memory')```

I am using an EC2 instance (p3.8xlarge) with following configuration:
1) **RAM**: 244GB
2) **vCPU**: 32
3) **GPU RAM**: 64GB
4) **GPUs**: 4 Tesla V100

Is this expected behaviour? Or are there any workarounds?

**Comment by OlivierNV** [comment]
read_parquet_metadata() is probably what you want (no need to actually read column data)

**Comment by chochim** [comment]
That makes sense. Thanks
