### ISSUE TITLE
[BUG] Reading huge csv by chunks is too slow

### ISSUE THREAD

**Issue by gcca** [rapidsai/cudf#2876]
**Bug description**
I want to read an 8.4G CSV file with 100 millions lines. To do that, I'm reading a million lines by step using the _nrows_ and _skiprows_ argument of _cudf.read_csv_. But, each iteration take at least 42 seconds.

I'm doing a batching process:
* read a chunk of the csv file and create a dataframe with _cudf.read_csv_,
* execute some operations over the dataframe, and
* write the result dataframe to a file.

I do that because the whole file can't be read with my nVidia card (4G).

**To reproduce bug**
Basically, I execute the following code:
```python
start = 0
step = 10**6

while True:
    df = cudf.read_csv('file.csv',
                       delimiter='|',
                       names=names,
                       dtype=dtype,
                       usecols=usecols,
                       nrows=step,
                       skiprows=start)
    start += step
```
where _file.csv_ is a csv file with 16 columns (6 str, 4 int64, and 6 int8).

**Expected behavior**
I expect to wait less time by iteration.

**Environment overview (please complete the following information)**
 - Environment location: bare-metal
 - nVidia driver version: 396.37
 - nVidia gpu: GeForce GTX 1050 Ti with 4G 
 - Method for cuDF installation: conda

**Comment by OlivierNV** [comment]
Did you try byte_range instead ? (To know where a specific row is located in the file, the parser has to do quite a bit of redundant parsing, which isn't necessary with byte_range)

**Comment by VibhuJawa** [comment]
@gcca , You can also explore `dask-cudf` to do the chunked processing you want to do.

`dask-cudf` internally uses the byte-range parameter to split the file into required chunks and also will allow you to use other reduction like operations out of the box without keeping the whole data-frame in memory. 

See: https://rapidsai.github.io/projects/cudf/en/0.9.0/dask-cudf.html#

**Comment by harrism** [comment]
No response from the original requester. Closing. 

@gcca if the responses did not solve your problem, please feel free to comment and/or reopen.
