### ISSUE TITLE
[BUG] Scatter Benchmark OOM Error

### ISSUE THREAD

**Issue by dillon-cullinan** [rapidsai/cudf#2879]
**Describe the bug**
This bug is very odd. It seems to point to a memory leak in the `SCATTER_BENCH` benchmark. However, it only happens when executed in a certain manner from the command line.

**Steps/Code to reproduce bug**

**Breaks:**
1. Build libcudf from source with `-DBUILD_BENCHMARKS=ON` cmake option.
2. After installing libcudf, navigate to the `cpp/build/gbenchmarks` folder
3. Run the `SCATTER_BENCH` executable with `./SCATTER_BENCH`

Output:

```
$ ./SCATTER_BENCH 
2019-09-26 17:00:36
Running ./SCATTER_BENCH
Run on (80 X 3600 MHz CPU s)
CPU Caches:
  L1 Data 32K (x40)
  L1 Instruction 32K (x40)
  L2 Unified 256K (x40)
  L3 Unified 51200K (x2)
Load Average: 0.56, 1.62, 1.72
-------------------------------------------------------------------------------------------------------------
Benchmark                                                   Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------------------
benchmark/double_coalesce_x/1024/1/manual_time          79539 ns       107596 ns         8656 bytes_per_second=196.444M/s
benchmark/double_coalesce_x/2048/1/manual_time          75918 ns       103526 ns         8089 bytes_per_second=411.631M/s
benchmark/double_coalesce_x/4096/1/manual_time          76928 ns       104653 ns         8007 bytes_per_second=812.447M/s
benchmark/double_coalesce_x/8192/1/manual_time          77096 ns       104621 ns         7850 bytes_per_second=1.58335G/s
benchmark/double_coalesce_x/16384/1/manual_time         77543 ns       104970 ns         8356 bytes_per_second=3.14845G/s
benchmark/double_coalesce_x/32768/1/manual_time         77907 ns       105252 ns         8087 bytes_per_second=6.26745G/s
benchmark/double_coalesce_x/65536/1/manual_time         79294 ns       106140 ns         7526 bytes_per_second=12.3157G/s
benchmark/double_coalesce_x/131072/1/manual_time        86035 ns       112834 ns         7841 bytes_per_second=22.7014G/s
benchmark/double_coalesce_x/262144/1/manual_time       102416 ns       211901 ns         6585 bytes_per_second=38.1411G/s
terminate called after throwing an instance of 'cudf::logic_error'
  what():  RMM error encountered at: /home/nfs/dcullinan/rapids/cudf/cpp/benchmarks/synchronization/synchronization.cpp:34: 4 RMM_ERROR_OUT_OF_MEMORY
Aborted
```

Oddly enough, when running the executable with `cuda-memcheck`, there are no errors.

**Works:**
1. Steps 1 and 2 from above
2. Run the `SCATTER_BENCH` with `cuda-memcheck SCATTER_BENCH`

**Expected behavior**
For the benchmark to run to completion when running the executable without cuda-memcheck.

**Environment overview (please complete the following information)**
 - Environment location: This happens on both bare-metal and docker
 - Method of cuDF install: Source
 - GPU: Single V100-32GB

**Environment details**
The conda environment given via https://github.com/rapidsai/cudf/blob/branch-0.10/conda/environments/cudf_dev_cuda10.0.yml

**Comment by harrism** [comment]
Closing. New issue to port gather/scatter benchmarks to libcudf++ being filed.
