### ISSUE TITLE
[BUG] cudf.read_csv and dask_cudf: 'utf-8' codec can't decode byte 0xcd

### ISSUE THREAD

**Issue by ivenzor** [rapidsai/cudf#2893]
I'm using cudf 0.10 to read a csv file (200 columns and 600K rows) with both numeric and string data.

When using pandas I have no error:
```
df=pd.read_csv('s3://XXX.csv.gz', compression='gzip', sep='~', header=None, encoding='cp1252', low_memory=False)
df.head()
```

When using cudf.read_csv or das_cudf.read_csv I got an utf-8 codec error:

```
df=cudf.read_csv('s3://XXX.csv.gz', compression='gzip', sep='~', header=None, encoding='cp1252', low_memory=False)
df=dask_cudf.read_csv('s3://XXX.csv.gz', compression='gzip', sep='~', header=None,encoding='cp1252', low_memory=False, assume_missing=True)
```

**UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 14: invalid continuation byte**

Any suggestion to track the issue? If I change the encoding to utf-8 I got the same error.

**Comment by kkraus14** [comment]
@ivenzor you're trying to use `cp1252` encoding which isn't supported via cudf at this time.

**Comment by ivenzor** [comment]
@kkraus14  Many thanks for your quick reply.

Quick recap:
With encoding cp1252 in pandas it works. In cudf I got error.
With encoding 'ISO-8859-1' in pandas it works. In cudf I got error.
With encoding 'utf8' I got error in both pandas and cudf.

Which encodings are supported in cudf at this time?

**Comment by ayushdg** [comment]
cudf only supports `utf8` at the moment. If pandas/cudf (encoding="utf8") encounters any character in the input data that does not belong to the `utf8` charset it will throw an error.

**Comment by ivenzor** [comment]
Thanks for your reply.  I will close this issue.

**Comment by kkraus14** [comment]
@ivenzor if `cp1252` or `ISO-8859-1` encodings are important to you could you raise a feature request issue to support those encodings?
