### ISSUE TITLE
[FEA] Design and implement cudf::scalar

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2914]
**Is your feature request related to a problem? Please describe.**

With the first phase of the libcudf core data structure redesign in place (#2207), we need to add a scalar type, `cudf::scalar` to replace the legacy `gdf_scalar` struct.

**Describe the solution you'd like**

`cudf::scalar` needs to support all the types `gdf_scalar` supports, as well as string and category scalar values. I think a good test of `gdf_scalar` is whether it can be used to `cudf::fill()` a column of any type.

I'm sure @jrhemstad has thoughts on design to share.

**Comment by jrhemstad** [comment]
Unlike with `column_view`s, for `cudf::scalar`, I'd like to use a derived class pattern to implement `cudf::scalar`. We will pass `cudf::scalar` into libcudf APIs via a base class `const&`, and then cast to the appropriate derived class via the type dispatcher.

**Comment by jrhemstad** [comment]
I'd like to effectively emulate [Arrow Scalar](https://github.com/apache/arrow/blob/master/cpp/src/arrow/scalar.h#L41) for this.
