### ISSUE TITLE
[DOC] Nightly API docs not incorporating recent changes

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2920]
Nightly docs don't seem to be updating based on recent changes. DataFrame/Series API methods that have been added in the past few weeks are missing (such as Series.kurtosis, for example), as well as changes to parameters of existing methods (such as DataFrame.apply_rows).

**Comment by kkraus14** [comment]
@beckernick @dillon-cullinan is this resolved?

**Comment by beckernick** [comment]
Yes, but we have a markdown formatting issue. Will address it ASAP

**Comment by kkraus14** [comment]
Resolved.
