### ISSUE TITLE
CUDA 10 with Turing Architecture support

### ISSUE THREAD

**Issue by joehoeller** [rapidsai/cudf#293]
Does this support the current Turing Arch with ability to pipe data to Tensor Cores on RTX 2080 Ti via some tensor_matrix_to_tpu() function?

**Comment by joehoeller** [comment]
Also, do you need help with a readthdocs manual? Documenting the API would be useful.

**Comment by joehoeller** [comment]
IBM - Python has no way of accessing tensor cores at this time:
https://developer.ibm.com/articles/ba-accelerate-python/


How to use Tensor Cores in CUDA9:
https://devblogs.nvidia.com/programming-tensor-cores-cuda-9/

**Comment by joehoeller** [comment]
Also - do you have docs on the API?

**Comment by kkraus14** [comment]
Those are the old API docs from before the refactor started. The API docs are here: https://rapidsai.github.io/docs/cuDF/

**Comment by mike-wendt** [comment]
Updated ones are now in the correct and final place here: https://cudf.readthedocs.io/en/latest/

**Comment by joehoeller** [comment]
Do you know when a CentOS/RHEL container will be avail?
See here ~
https://hub.docker.com/r/rapidsai/rapidsai/

**Comment by wuxianliang** [comment]
Does the claim " you will use 16-bit you virtually have 16 GB of memory on an RTX 2070" make sense in a gpu datafame? If so, it would be a great advantage. 

http://timdettmers.com/2018/11/05/which-gpu-for-deep-learning/

**Comment by harrism** [comment]
> Does this support the current Turing Arch with ability to pipe data to Tensor Cores on RTX 2080 Ti via some tensor_matrix_to_tpu() function?

We do not currently support piping data to tensor cores. If you have a specific use case for this it would be very helpful to know more.  Please file a new feature request issue describing the use case.
