### ISSUE TITLE
[FEA] Port groupby to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2938]
Is your feature request related to a problem? Please describe.

Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/groupby.hpp.

Describe the solution you'd like

Update the API functions definitions in cudf/groupby.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by harrism** [comment]
We will split this into two separate efforts: hash-based and sort-based. Assigning @jrhemstad to hash-based and @devavret to sort-based.

**Comment by harrism** [comment]
@jrhemstad @devavret can you update this issue with links to the PRs that close it?

**Comment by kkraus14** [comment]
Moving to 0.13 as hash groupby will not land for 0.12.

**Comment by devavret** [comment]
Sort groupby merged in #3597.
Hash groupby PR not opened yet.

**Comment by harrism** [comment]
@devavret can you file issues for any remaining hash groupby features that are in progress? Then we can close this.

**Comment by harrism** [comment]
Ping @devavret. ⬆️

**Comment by devavret** [comment]
> Ping @devavret. ⬆️

Already did #4400 #4401.
