### ISSUE TITLE
[FEA] Port join to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2939]
Is your feature request related to a problem? Please describe.

Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/join.hpp.

Describe the solution you'd like

Update the API functions definitions in cudf/join.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by jrhemstad** [comment]
Since @kaatish already has worked extensively on the join implementation in the past, I think it makes the most sense to assign this to him.

**Comment by jrhemstad** [comment]
Also, @kaatish I think we can drop the sort-based implementation. It's currently unused as it is only single column and doesn't support nulls. This will also reduce the amount of porting effort required.
