### ISSUE TITLE
[FEA] Port predicates.hpp to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2941]
Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/predicates.hpp (`is_sorted`).

Update the API functions definitions in cudf/predicates.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by harrism** [comment]
Reassigning to @cwharris since he has spare cycles. @jwyles please let us know ASAP if you have already started on this.

**Comment by cwharris** [comment]
@harrism Looks like we first need a separate pr for porting `table/legacy/device_table_row_operators.cuh`, since it's used more places than `predicates.hpp`.

**Comment by cwharris** [comment]
`table/legacy/device_table_row_operators.cuh` has already been ported to `table/row_operators.cuh`.
