### ISSUE TITLE
[FEA] Port reductions to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2943]
Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/reductions.hpp.

Update the API functions definitions in cudf/reductions.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by jrhemstad** [comment]
Note that this should also port and revamp the iterator in [`iterator.cuh`](https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/src/iterator/iterator.cuh)

**Comment by karthikeyann** [comment]
@jrhemstad  for iterator revamp, do you have anything particular in mind? (besides porting to cudf::column)
