### ISSUE TITLE
[FEA] Port rolling windows to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2945]
Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/rolling.hpp.

Update the API functions definitions in cudf/rolling.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by harrism** [comment]
#3305 fixes this for fixed-width types but does not support strings or UDFs, so moving this to 0.12.

**Comment by rgsl888prabhu** [comment]
@harrism should I close this, or we still have something with UDFs.
