### ISSUE TITLE
[FEA] Port search.hpp to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#2946]
Now that #2207 is merged we need to start porting functionality to use it. This issue covers functionality defined in cudf/search.hpp.

Update the API functions definitions in cudf/search.hpp and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by ChuckHastings** [comment]
A few questions/observations, love some feedback @harrism and/or @jrhemstad 

I assume this story also covers updating the python bindings so that the python tests work correctly as well.

The search methods use both column and table.  It appears that cudf::table has also been migrated to C++.  Should I be updating search to use both cudf::table and cudf::column?

Is there a time frame on cudf::scalar?  The search code uses this as well.

**Comment by jrhemstad** [comment]
> I assume this story also covers updating the python bindings so that the python tests work correctly as well.

This is only for the C++ effort. The Python side is still in the process of updating their data structures to accomodate libcudf++ APIs. (see https://github.com/rapidsai/cudf/pull/2927)

> The search methods use both column and table. It appears that cudf::table has also been migrated to C++. Should I be updating search to use both cudf::table and cudf::column?

So there's two `table` data structures now. `cudf::table` is the _old_ one. [`cudf::exp::table`](https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/include/cudf/table/table.hpp) is the new one that should be used.

**Comment by ChuckHastings** [comment]
Regarding legacy support... should I move the existing code into the legacy directory as is and put the new code in the cudf::exp namespace?  Or is there some other preferred mechanism for this?

**Comment by harrism** [comment]
Regarding `cudf::scalar` timeframe: @devavret was just assigned today.

**Comment by ChuckHastings** [comment]
The current search functions use comparison functions from device_table_row_operators which are written against the legacy table interface.  They appear to be contributions from BlazingDB.  Are they working on equivalent operations against the new table interface, or do I need to explore a different way of solving the problem?

**Comment by jrhemstad** [comment]
> The current search functions use comparison functions from device_table_row_operators which are written against the legacy table interface. They appear to be contributions from BlazingDB. Are they working on equivalent operations against the new table interface, or do I need to explore a different way of solving the problem?

New versions exist here: https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/include/cudf/table/row_operators.cuh

**Comment by harrism** [comment]
Fixed by #3229
