### ISSUE TITLE
[FEA] Support exploding nested type columns

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#2975]
When processing a nested type column, I'd like to be able to `explode` the column into a non-nested type column, like in Spark-sql or pandas. [Spark API doc](https://spark.apache.org/docs/1.6.0/api/java/org/apache/spark/sql/functions.html#explode(org.apache.spark.sql.Column)).

Pyspark:

```
import pandas as pd

from pyspark import SparkContext
from pyspark.sql import SQLContext
from pyspark.sql import functions as F

sc = SparkContext()
sqlContext = SQLContext(sc)

df = pd.DataFrame()
df['col1'] = [0, 1]
df['col2'] = [[12,12,38], [42,93]]

sdf = sqlContext.createDataFrame(df)
sdf.withColumn("exploded", F.explode("col2")).select("exploded").show()
+--------+
|exploded|
+--------+
|      12|
|      12|
|      38|
|      42|
|      93|
+--------+
```

Pandas:

```python
import pandas as pd

df = pd.DataFrame()
df['col1'] = [0, 1]
df['col2'] = [[12,12,38], [42,93]]

df.col2.explode()
0    12
0    12
0    38
1    42
1    93
Name: col2, dtype: object
```

**Comment by kkraus14** [comment]
Relevant Pandas API: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.explode.html

**Comment by kkraus14** [comment]
Relevant libcudf PR that implemented the functionality: https://github.com/rapidsai/cudf/pull/7140/files

**Comment by skirui-source** [comment]
Looks like Marlene is already working on this issue:
 https://github.com/rapidsai/cudf/pull/7227
