### ISSUE TITLE
[DOC] Create libcudf++ transition guide 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#2990]
## Report needed documentation

**Report needed documentation**
We need a guide that describes how to transition libcudf APIs from their current state to make use of `cudf::column` and associated types. 

This will replace the old transition guide here: https://github.com/rapidsai/cudf/blob/branch-0.10/cpp/docs/TRANSITIONGUIDE.md

**Comment by shwina** [comment]
There will need to be minimal changes to the Cython with each transition. Specifically if libcudf functions are moved to a `legacy` namespace, that namespace change will need to be reflected in the Cython bindings. Perhaps the transition guide could include a small blurb about this

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/cudf/pull/3011
