### ISSUE TITLE
[BUG] `cudf.set_allocator(pool=True)` causes RMM error at exit

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#2993]
```python

In [1]: import cudf

In [2]: cudf.set_allocator(pool=True)

In [3]: a = cudf.Series([1, 2, 3, 4, 5])                                                                                                                                                      

In [4]: exit                                                                                                                                                                                  
Traceback (most recent call last):
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 745, in _exitfunc
    f()
  File "/home/ashwint/miniconda3/envs/cudf_dev/lib/python3.7/site-packages/numba/utils.py", line 669, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/ashwint/workspace/github/shwina/rmm/python/rmm/rmm.py", line 219, in finalizer
    return librmm.rmm_free(handle, stream)
  File "rmm/_lib/lib.pyx", line 272, in rmm._lib.lib.rmm_free
  File "rmm/_lib/lib.pyx", line 261, in rmm._lib.lib.c_free
  File "rmm/_lib/lib.pyx", line 49, in rmm._lib.lib.check_error
rmm.rmm.RMMError: RMM_ERROR_NOT_INITIALIZED

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True



```

**Comment by jrhemstad** [comment]
Was cuDF Python updated to use RMM's new Cython bindings instead of the old CFFI ones?

**Comment by shwina** [comment]
Yes - might be related

**Comment by ayushdg** [comment]
I cannot reproduce with Cuda 10.0, latest nightly installed from Conda.

Environment details:

<details>
<pre>

arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cudatoolkit               10.0.130                      0    anaconda
cudf                      0.10.0a191007         py37_2427    rapidsai-nightly
cython                    0.29.13          py37he1b5a44_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_1    conda-forge
fastavro                  0.22.5           py37h516909a_0    conda-forge
fsspec                    0.5.2                      py_0    conda-forge
gflags                    2.2.2             he1b5a44_1001    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
libblas                   3.8.0               13_openblas    conda-forge
libcblas                  3.8.0               13_openblas    conda-forge
libcudf                   0.10.0a191007     cuda10.0_2427    rapidsai-nightly
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
liblapack                 3.8.0               13_openblas    conda-forge
libnvstrings              0.10.0a191007     cuda10.0_2427    rapidsai-nightly
libopenblas               0.3.7                h6e990d7_1    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.10.0a191007      cuda10.0_136    rapidsai-nightly
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
llvmlite                  0.30.0rc1        py37hf484d3e_0    numba
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numba                     0.46.0rc1       np116py37hf484d3e_0    numba
numpy                     1.16.4           py37h95a1406_0    conda-forge
nvstrings                 0.10.0a191007         py37_2427    rapidsai-nightly
openssl                   1.1.1c               h516909a_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
pip                       19.2.3                   py37_0    conda-forge
pyarrow                   0.14.1           py37h8b68381_2    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
re2                       2019.09.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rmm                       0.10.0a191007          py37_136    rapidsai-nightly
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sqlite                    3.30.0               hcee41ef_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

</pre>
</details>

**Comment by shwina** [comment]
Yes, I think it's because the RMM error above is silently passed in the Cython, which is addressed in https://github.com/rapidsai/rmm/pull/142

**Comment by shwina** [comment]
Closing at it looks like I can't reproduce after pulling latest RMM in locally. Apologies for the false alarm.
