### ISSUE TITLE
Unable to open 'csv.pyx': Unable to read file (Error: File not found cudf/_lib/csv.pyx)).

### ISSUE THREAD

**Issue by Bandit253** [rapidsai/cudf#3003]
Tried to run the Haversine_distance_test.py on smaller than the NY taxi file ~74,000

**Steps/Code to reproduce bug**
https://github.com/rapidsai/cuspatial/blob/branch-0.10/python/cuspatial/demos/haversine_distance_test_nyctaxi.py

 File "/home/rob/PythonDEV/haversine_dist_test.py", line 9, in <module>
    df = read_csv("/home/rob/PythonDEV/Lin_Crashash.csv")
  File "/home/rob/anaconda3/envs/geo/lib/python3.7/site-packages/cudf/io/csv.py", line 82, in read_csv
    index_col=index_col,
  File "cudf/_lib/csv.pyx", line 41, in cudf._lib.csv.read_csv
  File "cudf/_lib/csv.pyx", line 205, in cudf._lib.csv.read_csv
RuntimeError: rmm_allocator::allocate(): RMM_ALLOC: __global__ function call is not configured

**Expected behavior**
tested the file against pandas reads fine

Ubuntu 18.04 HyperV 
Conda install

**Additional context**
Noobie

**Comment by kkraus14** [comment]
@Bandit253 what hardware did you run this on? What was the size of the CSV you tried to read? That error message typically comes from trying to allocate more memory than available (WIP to improve this error message drastically).

**Comment by Bandit253** [comment]
@kkraus14 thanks for getting back to me.
My graphics card is a GeForce GTX 670 and the csv is only 4.3mb, rather than the multi G sample file.
Interestingly or sadly, I only went for the Unbuntu VM path because I was not able to get the docker image to work either :(  #838 docker: Error response from daemon: Unknown runtime specified nvidia

I am starting to feel defeated, I oh so want to get cuSpatial,  it sounds amazing, going but I am starting the think I need native linux or compile from code

**Comment by kkraus14** [comment]
@Bandit253 Unfortunately a GTX 670 won't work with RAPIDS as we only support Pascal or newer architecture (GTX 670 is Kepler) as there's some hardware features critical for performance for us. I'm guessing this is a case of RMM not erroring nicely that the GPU is unsupported.

**Comment by Bandit253** [comment]
@kkraus14 Thanks for the rapid (pardon the pun) response and to be honest that is also what I suspected.  I will get it working, just might take a little longer.  Keep up the great work!
