### ISSUE TITLE
[FEA] Option for ORC writer to generate statistics

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3018]
**Is your feature request related to a problem? Please describe.**
The ORC format has the ability to provide statistics at the file, stripe, and row group level.  These statistics are needed for predicate pushdown filtering.

**Describe the solution you'd like**
The ORC writer should have an option to generate statistics at the row group, stripe, and file levels.  File and stripe levels would be particularly useful for trimming out an entire stripe, avoiding sending any of the stripe's data to the GPU.  Row group level statistics are less useful for cudf until the readers support predicate pushdown directly.  However it would be nice for generating an ORC file that is useful to other data processing frameworks that can perform predicate pushdown at the row group level.

**Comment by OlivierNV** [comment]
Starting to look at this: will most likely drop the rowgroup-level stats (rowgroups in ORC are at most 10K rows), and collect stats for both stripe and file levels.
