### ISSUE TITLE
[FEA] Gather multiple definitions of CUDA_DEVICE_CALLABLE into single place

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3034]
**Is your feature request related to a problem? Please describe.**

CUDA_DEVICE_CALLABLE and CUDA_HOST_DEVICE_CALLABLE are each defined in 3 places: cpp/include/cudf/utilities/cuda.cuh, cpp/src/utilities/bit_util.cuh, cpp/src/utilities/cudf_utils.h (and I'm also adding the definition directly to types.hpp in PR 3029 so that Jitify doesn't need any additional headers stringified). Having the same macros defined in multiple places is unexpected and error prone.

**Describe the solution you'd like**

Pick a suitable header in which to define these macros and remove the redundant definitions. Jitify may need to have this header stringified to that it can find the defintions.

**Comment by harrism** [comment]
utilities/cuda.cuh makes sense. Putting it in types.hpp is not ideal since this is an external header and these macros are only needed internally.

**Comment by harrism** [comment]
@trevorsm7 assigning you and marking P0 for 0.12. (I missed this issue until now)
