### ISSUE TITLE
[FEA] CMake does not display output of failing tests by default

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3036]
**Is your feature request related to a problem? Please describe.**

When running tests by `make test`, information about failing tests is not displayed by default. The errors can be displayed by running `make CTEST_OUTPUT_ON_FAILURE=1 test` instead.

**Describe the solution you'd like**

Change the CMake configuration to display errors by default.

**Describe alternatives you've considered**

Change the documentation to suggest running `ctest --output-on-failure` instead of `make test`.

**Comment by harrism** [comment]
What I usually do is see which test failed. Let's say it's HASH_TEST. Then I run `gtests/HASH_TEST` to see the output.

**Comment by trevorsm7** [comment]
Running the gtests directly worked for me as well. Maybe it would be better to update the documentation with a note about how to run failing tests manually this way?

**Comment by kkraus14** [comment]
I think it's reasonable to default to this behavior when someone runs `make test`
