### ISSUE TITLE
[BUG] Remove all `cudaDeviceSynchronize` from libcudf features

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3045]
**Is your feature request related to a problem? Please describe.**

`cudaDeviceSynchronize()`s are littered throughout libcudf code. These are a heavy hammer that obliterate any opportunity for multi-threaded/multi-stream use of libcudf.

**Describe the solution you'd like**
Any `cudaDeviceSynrhonize()` should be removed in favor of a more appropriate synchronization, e.g., `cudaStreamSynchronize()`.

**Comment by trevorsm7** [comment]
I browsed through the code and only found `cudaDeviceSynchronize()` remaining in tests, legacy, and custrings so it seems this could be closed, maybe pending on https://github.com/rapidsai/cudf/issues/4050

**Comment by jrhemstad** [comment]
> I browsed through the code and only found `cudaDeviceSynchronize()` remaining in tests, legacy, and custrings so it seems this could be closed, maybe pending on #4050

Let's just close it when legacy is removed.
