### ISSUE TITLE
[BUG] Groupby performance regression

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3057]
**Describe the bug**
Groupby performance has degraded and memory usage has increased in 0.10

**Steps/Code to reproduce bug**
```
# imports
import cudf
import numpy as np

# setup
df = cudf.DataFrame()
n_elem = 20_000_000
n_groups = n_elem // 100

for i in range(5):
    df[str(i)] = np.random.randint(0,n_groups,n_elem)
for i in range(5,7):
    df[str(i)] = np.random.random(n_elem)

# groupby
%%time
res = df.groupby([str(i) for i in range(5)], sort = True)['5','6'].sum()

Old Time: ~1.3s      Old peak memory: ~3GB
New Time: ~3.5s.   New Peak memory: ~4.5GB
```

With sort=False
```
%%time
res = df.groupby([str(i) for i in range(5)], sort = False)['5','6'].sum()

Old Time: ~250 ms
New Time: ~2s
```

Similar pattern for other aggs like `min/max` and grouping by fewer columns.

**Expected behavior**
Similar performance with the newer version. 

The git bisect path led me to 74b562c06751de441d4ee30460528c9fa6f7221d being the faulty commit which is a part of #2870 

**Environment overview (please complete the following information)**
Build from source dec6423a06ed25f6411236a5b3e6cf725434a800

**Comment by randerzander** [comment]
Closed by #3064
