### ISSUE TITLE
[FEA] Abstract output sink for ORC/Parquet writers

### ISSUE THREAD

**Issue by mjsamoht** [rapidsai/cudf#3063]
Will add more details later.

Requirements:
- [x] Write to file.
- [x] Write to host memory buffer.

**Comment by vuule** [comment]
@mjsamoht added support for local files and host buffers, is anything else pending before this issue can be closed?

**Comment by mjsamoht** [comment]
I think that's all.  @OlivierNV do you agree?

**Comment by OlivierNV** [comment]
Yup, I think that's it [Closing].
