### ISSUE TITLE
[BUG] matplotlib plot function not working

### ISSUE THREAD

**Issue by Sterls** [rapidsai/cudf#3072]
**Describe the bug**
When trying to use the plot function from matplotlib, I get the following error:

TypeError: memoryview: a bytes-like object is required, not 'tuple'
During handling of the above exception, another exception occurred:
ArrowInvalid: Could not convert slice(None, None, None) with type slice: did not recognize Python value type when inferring an Arrow data type

**Steps/Code to reproduce bug**
test = cudf.DataFrame()
#test = pd.DataFrame()
test['a'] = np.arange(10, dtype=np.float64)
test['b'] = np.arange(10, dtype=np.float64)

fig,ax=plt.subplots(figsize=(20,10))
plt.plot(test['a'],test['b'])
plt.show()

**Comment by kkraus14** [comment]
Duplicate of #4948
