### ISSUE TITLE
[DOC] Series.str.rstrip and Series.str.lstrip documentation is not in cuDF but in nvstrings package

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#3075]
## Report incorrect documentation

**Location of incorrect documentation**
I cannot find the `Series.str.rstrip` or `Series.str.lstrip` documentation in cuDF documentation (https://docs.rapids.ai/api/cudf/stable/). It is available in nvStrings docs (https://docs.rapids.ai/api/nvstrings/stable/).

**Describe the problems or issues found in the documentation**
It is not intuitive to search into nvStrings documentation to find API details for those methods.

As a user, I have imported cuDF, not nvStrings.

**Steps taken to verify documentation is incorrect**
Use search boxes in https://docs.rapids.ai/api/cudf/stable/ and https://docs.rapids.ai/api/nvstrings/stable/

**Suggested fix for documentation**
Put nvstrings documentation also available from here: (https://docs.rapids.ai/api/cudf/stable/)

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by kkraus14** [comment]
Will be fixed when cuDF hits libcudf++ string functions.

**Comment by miguelusque** [comment]
Hi @galipremsagar ,

I am trying to find that documentation in the 0.14 nightly build of the documentation, but somehow I cannot find it.

I am performing the following searches:

[https://docs.rapids.ai/api/cudf/nightly/search.html?q=lstrip&check_keywords=yes&area=default#
](https://docs.rapids.ai/api/cudf/nightly/search.html?q=lstrip&check_keywords=yes&area=default#
)
[https://docs.rapids.ai/api/cudf/nightly/search.html?q=rstrip&check_keywords=yes&area=default#](https://docs.rapids.ai/api/cudf/nightly/search.html?q=rstrip&check_keywords=yes&area=default#)

Could you please point me to the right location?

Thanks!

Miguel

**Comment by galipremsagar** [comment]
@miguelusque Due to some issues with internal containers, docs will be built today. So you might want to give it another day for the changes to reflect.
