### ISSUE TITLE
[BUG] Series.str.startswith returns a list and not a Series

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#3076]
**Describe the bug**
Hi,

When trying to move some code from Numpy to Cupy, I have noticed that there is an unexpected behaviour in _Series.str.startswith_ method.

According to Pandas, it should return a Series (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.startswith.html), while in cuDF it returns a `list`

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
import cupy as cp

gdf = cudf.DataFrame({
    'a': [0.0, 0.0, 0.0, 0.0, 0.0],
    'b': ['m', 'm', 'm', 'm', 'm'],
    'c': [54.426256, 54.501872, 54.483065, 54.640205, 54.575450],
    'e': [-1.465314, -1.667874, -1.501312, -1.558986, -1.600592],
    'f': ['Edward', 'Eamonn', 'Ethan', 'Elvin', 'Edward']})

ed_names_np = gdf.loc[np.logical_and(gdf['f'].str.startswith('E'),
                                     gdf['f'].str.endswith('d'))]
print("Logical and with Numpy")
print(ed_names_np)

# It returns a list, not a Series
print(type(gdf['f'].str.startswith('E'))) 

ed_name_cp = gdf.loc[cp.logical_and(gdf['f'].str.startswith('E'),
                                     gdf['f'].str.endswith('d'))]
print("Logical and with Cupy")
print(ed_names_cp)
```

**Expected behavior**
cuDF to return a Series

**Environment overview (please complete the following information)**
RAPIDS 0.9

**Environment details**
DLI environment

**Additional context**
Thanks @kkraus14 for noticing where the issue is likely to be.

**Comment by ayushdg** [comment]
Related to #2589

**Comment by miguelangel** [comment]
Hi,

Is there any ETA for this issue?

Thanks!

**Comment by kkraus14** [comment]
This will be fixed when cuDF is updated to use the new libcudf++ string functions.

**Comment by galipremsagar** [comment]
Closing this as this was fixed/covered in recent changes to `.str.startswith`.
