### ISSUE TITLE
[FEA] Multiple value search

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3077]
**Is your feature request related to a problem? Please describe.**
SQL has an `IN` operator that returns a boolean result that is true if the value appears in a list of values to test against and false otherwise.  Implementing this in a columnar fashion would allow accelerating this SQL operator on the GPU.

**Describe the solution you'd like**
libcudf provides a method that is similar to the following:
```c++
column multisearch(column_view const& haystack, column_view const& needles);
```
The returned column would be a `bool8` column that has the same size as the `haystack` input column.  Each row in the result column would be non-zero if the value of the corresponding row in `haystack` appeared anywhere in the `needles` column.  If the value does not appear anywhere in `needles` then the corresponding row in the result column is zero.

**Describe alternatives you've considered**
This can be implemented today by performing separate equality comparisons on each value of `needles` to generate a `bool8` column, and then the boolean columns can be combined with logical AND operations to form the final result column.  However this leads to many separate comparison and combine operations as the number of values to test increases.

If the `IN` is used directly in a filter operation then it can be implemented as a left join against the values to test against.  However `IN` may be just one small part of a complicated expression that may or may not be used as a filter predicate.

**Comment by jrhemstad** [comment]
Implementation idea:

Assuming `needles.size()` is relatively "small", (probably less than 32 elements?)
- Sort `needles`
- `thrust::transform` over the output `bool8` column where for each element do a `thrust::binary_search(seq,...)` into sorted `needles`. If the element is found, return true.

**Comment by jlowe** [comment]
> Assuming needles.size() is relatively "small"

For all of the examples I've seen, the list has been small.

> Sort needles

Often the needles are literal values, and it would not be difficult for the caller to ensure the list is sorted before sending the data to the GPU and calling the search function.  The overhead of sorting on the GPU may be slower than sorting on the CPU.  Therefore it may be worthwhile to require the caller to pass a sorted `needles` column or expose a second API where the sort can be avoided.

An alternative approach is to build a hash table, but I don't know offhand the relative GPU costs of that approach vs. sort and binary search when the list is likely to be small.

**Comment by jrhemstad** [comment]
> An alternative approach is to build a hash table, but I don't know offhand the relative GPU costs of that approach vs. sort and binary search when the list is likely to be small.

Hash table is an interesting idea.

@nsakharnykh this could be a good place to experiment with very small hash tables, probably small enough to replicate across all blocks and fit in L1$/shared memory. 

Thinking out loud... how/when should the hash table be built?
- Build it on the CPU, put it in constant memory? Then launch the search kernel.
- Or, In search kernel, each block first builds the hash table in shared memory

**Comment by nsakharnykh** [comment]
Hash tables will be faster than binary search - O(1) access to something like constant memory cache/L1/SMEM vs O(log N) accesses. If we don’t care much about the build cost, i.e. it’s done once in the preprocessing phase, then building on the CPU and putting in constant memory is likely the best option. We can write some microbenchmark to test throughput for this solution.

**Comment by harrism** [comment]
@jlowe Do you prefer a bool result column or do you prefer an int result column where the value at each row `i` is the index of `haystack[i]` in `needles[i]`?

@davidwendt recently started porting a function that does exactly this for strings columns: https://github.com/rapidsai/cudf/pull/3421/

**Comment by beckernick** [comment]
This could likely be plumbed to the Python to replace the current `isin` method (https://github.com/rapidsai/cudf/issues/1577)

**Comment by jlowe** [comment]
> Do you prefer a bool result column or do you prefer an int result column where the value at each row i is the index of haystack[i] in needles[i]?

For implementing SQL IN it should be a bool result column.  If there's only a method that produces an index then we can follow it up with a cast to bool as a workaround.

**Comment by harrism** [comment]
Is there any reason to get the index of the needle as in #3421? CC @davidwendt

**Comment by jlowe** [comment]
I'm sure having indices would be useful somewhere.  Off the top of my head I'm not seeing a scenario where Spark SQL ops would want needle indices, but maybe I haven't seen the relevant SQL op yet. :smile:

I should clarify the cast workaround I mentioned above.  We'd have to do a little math before the cast, e.g.: compute result+1 and cast that as a bool8 column.  So there would be a couple of extra kernel invocations before getting the desired output.  Would be nice to avoid that overhead, but I expect it to be relatively small.

**Comment by kkraus14** [comment]
> Is there any reason to get the index of the needle as in #3421? CC @davidwendt

Pandas has `idxmin` and `idxmax` functions which are to return the index of the first occurrence of the min or max value respectively, so we could have a valid use for this.

**Comment by harrism** [comment]
`idxmax` is something different -- it's the [argmin](https://en.wikipedia.org/wiki/Arg_max) of a column / data frame.  It doesn't involve a search of values from one array into another, which is what is being discussed here.

**Comment by harrism** [comment]
We'll go ahead and return bools. However unless @davidwendt provides a strings function that returns bools, there will be extra kernel overhead for the strings column case.

**Comment by davidwendt** [comment]
> We'll go ahead and return bools. However unless @davidwendt provides a strings function that returns bools, there will be extra kernel overhead for the strings column case.
Sorry if I'm not understanding this correctly but I don't see a need for strings specialization here. If you are just comparing rows of strings you should be able to use generic `column_view` since the `string_view` primitive has comparison operators (`<`,`>`,`==`).
Also #3421 is not the same as this function since it is searching for substrings inside each string and returning the character position and not booleans.

**Comment by harrism** [comment]
Maybe I misunderstood due to the timing of your PR and @ChuckHastings ' PRs being opened so close together. I thought you opened #3421 *because* of this request, to provide a way for Chuck to implement his function on strings columns.

From reviewing #3427, it appears it uses hashing, not comparison. As long as hashing works on strings, I guess it just works.

**Comment by ChuckHastings** [comment]
I think it's probably just a timing issue.  I'm not sure that #3421 would be of much help to solve this problem.  #3421 is a much more expensive operation I would imagine (computes an n x m output column).  Any result that was not 0 would indicate that the values don't match, but any result that was zero could be a false positive and you would have to do a string comparison of those elements to validate.  Then you'd have to do a reduction to get the n x m column down to the desired column of length n.

I believe the hashing I put into #3427 works on strings.  There are several unit tests for them that work successfully.

**Comment by harrism** [comment]
Thanks for clarifying, sorry or my confusion!
