### ISSUE TITLE
[BUG] Inconsistent null handling in cudf binary operations

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#3078]
One of these things is not like the other.
```
cudf.Series([None]) == cudf.Series([None])
0    False
dtype: bool
```
```
>>> cudf.Series([None]).eq(cudf.Series([None]))
0    False
dtype: bool
```
```
>>> cudf.Series([None]).eq(cudf.Series([None]), fill_value=None)
0    False
dtype: bool
```
```
>>> cudf.Series([None]).eq(cudf.Series([None]), fill_value=5.0)
0    null
dtype: bool
```

When using a `fill_value`, the result is null. Which is the opposite of what you might expect, especially considering that in other cases, null comparisons are just `False` (which, ironically, feels like it should be None`).

`False` is consistent with Pandas if we consider `np.nan` as `null`, but inconsistent if we consider `np.nan` as an existent, but "invalid", value.

The question is, which one is the bug?

In my opinion, we should give null comparisons null results.

**Comment by rgsl888prabhu** [comment]
when comparing `cudf.Series([None]).eq(cudf.Series([None]), fill_value=5.0)`
cudf.Series([None]) is of type object and other series would be of type `Float`.

With following change it gives false as expected,
```
>>> cudf.Series([None], dtype='float').eq(cudf.Series([5.0]))
0    False
dtype: bool

```

**Comment by rgsl888prabhu** [comment]
For 
```
>>> pd.Series([np.nan]).eq(pd.Series([np.nan]), fill_value=5.0)
0    False
dtype: bool
```
As per the pandas [doc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.eq.html) it should be returning `missing/none` but the actual behavior is different. I have created a [bug](https://github.com/pandas-dev/pandas/issues/33380) in pandas to check what should be the expected behavior.

**Comment by cwharris** [comment]
Looks like that pandas bug is closed with a documentation updated. Do we still need to address changing cudf?

**Comment by rgsl888prabhu** [comment]
Think we don't need any changes, and current behavior looks good
```
>>> cudf.Series([None]) == cudf.Series([None])
0    <NA>
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([None]))
0    <NA>
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([None]), fill_value=None)
0    <NA>
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([None]), fill_value=5.0)
0    <NA>
dtype: bool
>>> 

```

**Comment by cwharris** [comment]
Awesome. I went ahead and checked some other combos just so we have a record of these too:
```
>>> cudf.Series([5.0]).eq(cudf.Series([None]), fill_value=5.0)
0    True
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([5.0]), fill_value=5.0)
0    True
dtype: bool
>>> cudf.Series([5.1]).eq(cudf.Series([None]), fill_value=5.0)
0    False
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([5.1]), fill_value=5.0)
0    False
dtype: bool
>>> cudf.Series([5.1]).eq(cudf.Series([None]), fill_value=None)
0    <NA>
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([5.1]), fill_value=None)
0    <NA>
dtype: bool
>>> cudf.Series([5.1]).eq(cudf.Series([5.1]), fill_value=None)
0    True
dtype: bool
>>> cudf.Series([None]).eq(cudf.Series([None]), fill_value=None)
0    <NA>
dtype: bool
>>>
```
Looks fine to me.
