### ISSUE TITLE
[BUG] read_parquet(...) non-deterministic results

### ISSUE THREAD

**Issue by jdye64** [rapidsai/cudf#3081]
I'm experiencing non-deterministic results when running 

```
import cudf

# Paths to the data files
click_file = "/part-00000-ab0d89e1-fc52-4c0b-a18a-9dca176cedbf-c000.snappy.parquet"
other_file = "/part-00000-40e6a9ba-5706-4e3f-aad5-8292e5c57a15-c000.snappy.parquet"

click_df = cudf.read_parquet(click_file, row_group=1)
print(len(click_df))
other_df = cudf.read_parquet(other_file)

# Perform inner join
result_df = click_df.join(other_df.set_index('click_sk'), how="inner", on="other_click_sk")
result_df
```

The datasets on disk are not changing however I am seeing dramatically different results in the number of rows as the result of the "result_df". I am running a fresh python environment for each run and still seeing the non-deterministic results.

I'm not sure if the BUG is in the reading, joining, or filtering of the dataframe?

The input parquet file for clicks is large and hence why I'm on retrieving the first "row_group".

The "len" of click_df is always consistent so I don't think that is the problem in the reading.

Run #1 
![image](https://user-images.githubusercontent.com/2127235/66776075-904bca00-ee93-11e9-93d0-a267e2742538.png)

Run # 2
![image](https://user-images.githubusercontent.com/2127235/66776096-9f327c80-ee93-11e9-9ba2-35bdf05bc830.png)

**Comment by OlivierNV** [comment]
Not sure if this could be related, but I am seeing some intermittent failures of test_parquet_reader_filepath_or_buffer in test_parquet.py that seem related to the null_count generated being incorrect (might be related to valid allocation padding ?)

**Comment by OlivierNV** [comment]
One thing about parquet/orc readers is that values that are null are not initialized (with the exception of strings), so if there is some improper null handling, it could lead to non-deterministic output, but we'd have to trace the output to see at which stage the results differ.

**Comment by kkraus14** [comment]
@jdye64 Is this still an issue? If so we should try to iron it down to removing the join and other operations so it’s just a parquet read and that’s all. It’s possible we have a bug in join or not null that’s corrupting the results.

**Comment by jdye64** [comment]
@kkraus14 ok. I removed everything but the read_parquet(). That is giving me deterministic results. Therefore the issue must be in the joining I'm guessing?

**Comment by kkraus14** [comment]
Closing as read_parquet is deterministic. Suggest opening a follow up issue if this is still a problem.
