### ISSUE TITLE
Add back the single GPU examples notebooks

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#309]
## Reporting a bug

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The ask is to include the single GPU and multi-gpu example notebooks in the rapids container.  Please add back the Pandas (CPU) and non-dask GPU xgboost, dbscan, knn, pca, others example notebooks.

**Comment by mike-wendt** [comment]
@kenhester they are included in the latest release on docker hub and are published here: https://github.com/rapidsai/notebooks

Does this solve the issue?

**Comment by harrism** [comment]
No response, so closing. I believe the notebooks repo solves this problem. If not, please open an issue on https://github.com/rapidsai/notebooks
