### ISSUE TITLE
[FEA] Suggestion to improve DataFrame display time in Jupyter notebooks

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#3090]
**Is your feature request related to a problem? Please describe.**
Hi, I have noticed that, when trying to display a DataFrame in Jupyter lab, it takes much longer to use the following code:

`print(gdf)`

than using the following approach
```
#30 is the number of rows displayed in my Jupyter notebook when using the code above.
print(gdf.head(30))
print(gdf.tail(30))
```

In my testing, the first code takes 3 seconds to display the DataFrame, where the second takes 0.05.

**Describe the solution you'd like**
Maybe, there is some room of improvement here when using the first approach: print(gdf)

**Describe alternatives you've considered**
Second approach detailed above.

**Additional context**
Adding an screenshot of my testing results.

Running on AWS instance, with 4 V100 16GBs, RAPIDS 0.9.

Hope it helps!

![screencapture-ec2-3-15-226-107-us-east-2-compute-amazonaws-lab-lab-2019-10-15-13_05_57](https://user-images.githubusercontent.com/26169771/66826529-edf01d00-ef4c-11e9-8c92-9d97865b763a.png)

**Comment by kkraus14** [comment]
@thomcom sounds like we're copying / converting way more data than we should be, no? Handling ~100 rows should be sub 100ms, no?

**Comment by thomcom** [comment]
Indeed, the only time cost should have to do with slicing up the big original dataframe. It needs to be profiled, but I suspect that calling `.iloc` is taking longer than expected.
