### ISSUE TITLE
Coupling of Dictionary with Data causes issues for usage

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#3097]
In many cases users are going to things like sort, filter group on indices from NVCategory  without wanting to modify the dictionary itself. Because NVCategory contains both then it makes it difficult to do something like reordering a column without having to reconstitute a new NVCategory. Is there a way that we can separate the two? This way you could filter a column and you only have to generate new indices and know that the use the same dictionary. We could do this by  modifying the current PR for NVCategory support to store an NVCategory::Dictionary or something of that nature instead of teh NVCategory itself. This woudl also probably require a utility function that could create an NVCategory from this data and this dictionary without requiring copies if we wanted to access its apis to do things like merge them.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/rapidsai/cudf/issues/3535
