### ISSUE TITLE
[BUG] NVCategory and NVStrings needs a validity bitmask

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3098]
Based on https://github.com/rapidsai/nvstrings/issues/22 it seems that `NVCategory` uses a sentinel value of `-1` to represent null values. This is incompatible with `libcudf`.

All of the logic in `libcudf` is built such that null values in a column are represented via an associated `valid` bitmask where bit `i` indicates the validity of element `i` in the column. 

If bit `i` is 0, the value is null, if bit `i` is 1, then the value is not null. If the `nullptr == valid`, it is assumed that all of the values are not null.

See https://arrow.apache.org/docs/memory_layout.html for more detail on bitmasks and bit ordering assumed in libcudf.

**Comment by kkraus14** [comment]
Closing as we have a clear path forward here in libcudf++.
