### ISSUE TITLE
Insertion of null lines in pygdf.read_csv when reading csv files generated by Windows systems.

### ISSUE THREAD

**Issue by dantegd** [rapidsai/cudf#310]
_From @MurrayData on October 27, 2018 9:21_

I found a bug in pygdf.read_csv where it inserted null rows consisting of all None types. I checked the input CSV file, and it was fine. Further investigation showed this bug relates to files generated by Windows systems with CR/LF (x'0d0a') line endings, rather than Uniix/Linux LF (x'0a') only. A workaround, on Linux systems, is to use the dos2unix command to convert the file beforehand, then it loads correctly.

Code:
![rapids_csv_bug_1](https://user-images.githubusercontent.com/8914493/47602052-12b45300-d9d1-11e8-8f5d-0139224b7ed8.jpg)
Source file:
![rapids_csv_bug_2](https://user-images.githubusercontent.com/8914493/47602054-15af4380-d9d1-11e8-8391-1eb72fcfff1c.jpg)
Another example:
![rapids_csv_bug_3](https://user-images.githubusercontent.com/8914493/47602057-18aa3400-d9d1-11e8-9fe8-2f6d430b0515.jpg)

_Copied from original issue: rapidsai/cudf-alpha#2_

**Comment by dantegd** [comment]
_From @BradReesWork on October 27, 2018 23:50_

We have a patch that addresses this issue and adds a new argument for windows csv fils (CR/LF)

Send from my mobile device
________________________________

**Comment by harrism** [comment]
I thought I merged the PR that fixes windows line endings last week.

**Comment by kkraus14** [comment]
This is resolved, open a new issue if you're seeing similar behavior, thanks!
