### ISSUE TITLE
[QST] Should nvstrings.free delete Python reference to object freed from GPU memory

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3104]
Currently, `nvstrings.free` will free memory for the nvstrings instance passed to it, but it won't delete the reference to that object in Python. Accessing that reference currently causes a segfault. Should `nvstrings.free` in the Python bindings also delete the Python reference? The reference count in Python is probably not being decremented so garbage collection won't occur.

```python
import nvstrings
data = nvstrings.to_device(['a', 'b', 'c', 'd'])
nvstrings.free(data)
print(data) # causes a segfault
```

**Comment by kkraus14** [comment]
nvstrings is deprecated as of 0.14, closing.
