### ISSUE TITLE
[FEA] Support specifying category values at nvcategory creation time

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3106]
If you want to manually specify the list of values for an nvcategory, today the only way I could find is to first create a category from an nvstrings, then call .set_keys.

That works, but it would be nice if I could pass the list of valid keys at initial category creation time, which should be faster and a more straightforward API.

Today's API:
```
keys = nvstrings.to_device(uniques)
cat = nvcategory.from_strings(df[col].data)
cat = cat.set_keys(keys)
```

Proposed API:
```
keys = nvstrings.to_device(uniques)
cat = nvcategory.from_strings(df[col].data, keys=keys)
```

**Comment by kkraus14** [comment]
Closing as NVCategory is deprecated as of 0.14
