### ISSUE TITLE
[FEA] Support passing a column of strings to `Series.str.contains()`

### ISSUE THREAD

**Issue by AK-ayush** [rapidsai/cudf#3107]
`data.csv`
```CSV
col1, col2
abc, abcde
efg, eft
```
And, I want to apply `contains()` operation on each row but I don't want to copy argument string to host.
Is there any way, we can pass the custring argument  to `contains()` method??
```python
df_str = cudf.read_csv("data.csv")

print(df_str.dtypes)
col1     object
col2     object
dtype: object

s1 = df_str.col1.str
s2 = df_str.col2.str



s1.gather([0]).contains(s2.gather([0]))

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: bad argument type for built-in operation

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-36-1c87cb59d2aa> in <module>()
      1 ced.gather([0]).contains(cfn.gather([0]))

~/libraries/nb_env/lib64/python3.6/site-packages/nvstrings.py in contains(self, pat, regex, devptr)
   2128 
   2129         """
-> 2130         rtn = pyniNVStrings.n_contains(self.m_cptr, pat, regex, devptr)
   2131         return rtn
   2132 

SystemError: <built-in function n_contains> returned a result with an error set
```
but this if copy the argument string to host, then last line works:
```python
s1.gather([0]).contains(s2.gather([0]).to_host())

[True]
```

**Comment by AllDuffy** [comment]
Has this functionality been added yet?

**Comment by davidwendt** [comment]
No, not yet.
Just another clarification. This is the desired behavior?
```
import cudf
s1 = cudf.Series(['bcd','efg'])
s2 = cudf.Series(['abcde','eft'])

s2.str.contains(s1)
0    True
1    False
dtype: bool
```

This would not be difficult to add with the following restrictions for this new feature:
- no regex: target strings `s1` are purely substrings of the source strings `s2`
- search is case-sensitive: 'Bcd' is not contained in 'abcde'

I can create a PR for this today.

**Comment by AllDuffy** [comment]
> No, not yet.
> Just another clarification. This is the desired behavior?
> 
> ```
> import cudf
> s1 = cudf.Series(['bcd','efg'])
> s2 = cudf.Series(['abcde','eft'])
> 
> s2.str.contains(s1)
> 0    True
> 1    False
> dtype: bool
> ```
> 
> This would not be difficult to add with the following restrictions for this new feature:
> 
> * no regex: target strings `s1` are purely substrings of the source strings `s2`
> * search is case-sensitive: 'Bcd' is not contained in 'abcde'
> 
> I can create a PR for this today.

Yes that would be the desired functionality. Reg-ex would be helpful but would much rather quick addition of the simple functionality. Thank you!
