### ISSUE TITLE
Date/time format specifiers

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#3109]
Documenting the current and missing specifiers in this issue for `long2timestamp` and `timestamp2long`. Specifiers are documented here: https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior

**Currently supported specifiers are as follows:**

- `%d` - day of month
- `%m` - month
- `%y,%Y` - year
- `%H,%I` - hour
- `%M` - minute
- `%S` - seconds
- `%f` - microseconds
- `%z` - UTC offset
- `%j` - day of year

Also, the `%p` format is supported but only `AM/PM` or `am/pm` is recognized.

**Not supported are locale-specific specifiers and some less common numeric-only specifiers.**
The numeric specifiers are as follows:

- `%U,%W` - week number of the year (00-53)
- `%w` - week day of the week (0-6)

The common locale-specific specifiers are as follows:

- `%a,%A` - name of the weekday
- `%b,%B` - name of the month
- `%p` - the am or pm string
- `%Z` - timezone name (e.g. EST, CST, UTC, etc)

The following less common specifiers rely on the locale's general date/time format:

- `%c` - date and time representation (e.g. Tue Aug 16 21:30:00 1988)
- `%x` - date representation (e.g. 16.08.1988)
- `%X` - time representation (e.g. 21:30:00)

Also the literal `%` character does not usually appear in date/time formats but can be specified using the `%%` specifier. This is also not currently supported/expected.

**Comment by kkraus14** [comment]
@davidwendt did this ever land in published documentation anywhere?

**Comment by davidwendt** [comment]
Yes, I ended up just adding the docs directly into the doxygen: 
https://docs.rapids.ai/api/libcudf/nightly/group__strings__convert.html#gacaf50d3b6d14ece094b9fc16b3d35c76
https://docs.rapids.ai/api/libcudf/nightly/group__strings__convert.html#ga192bce8f917991cf0475089f9865b50f

**Comment by Gabriel-Kissin** [comment]
Just to point out that these currently all fail silently - just spent a while tracing some unexpected behaviour back to this. While these specifiers are still unsupported, ideally there would be a warning the first time any of them are used

**Comment by davidwendt** [comment]
> Just to point out that these currently all fail silently - just spent a while tracing some unexpected behaviour back to this. While these specifiers are still unsupported, ideally there would be a warning the first time any of them are used

I believe unsupported specifiers should throw an error. 
Can you provide an example along with the function you are calling?
@Gabriel-Kissin

**Comment by Gabriel-Kissin** [comment]
Sure, here is an MRE:
```python
import pandas as pd
import cudf
print(pd.__version__, cudf.__version__)
dates = pd.date_range("01-01-2000", "01-01-2001", 13)
print(pd.Series(dates).dt.strftime("%u_%A_%B"))
print(cudf.Series(dates).dt.strftime("%m_%A_%B"))
```
Output I get:
```
2.2.3 25.04.00
0       6_Saturday_January
1         1_Monday_January
2         4_Thursday_March
3         6_Saturday_April
4            2_Tuesday_May
5          4_Thursday_June
6            7_Sunday_July
7         2_Tuesday_August
8       5_Friday_September
9         7_Sunday_October
10    3_Wednesday_November
11       5_Friday_December
12        1_Monday_January
dtype: object
0     01__
1     01__
2     03__
3     04__
4     05__
5     06__
6     07__
7     08__
8     09__
9     10__
10    11__
11    12__
12    01__
dtype: object
```

**Comment by Gabriel-Kissin** [comment]
After testing a bit more it appears that many of the specifiers actually are (now) supported. However this is only when they are by themselves. It is when they are included as part of a string that they aren't included - it is the addition of the `_` which causes the issue above.

```python
import pandas as pd
import cudf
print(pd.__version__, cudf.__version__)
dates = pd.date_range("01-01-2000", "01-01-2001", 13, tz="utc")
unsupported_specifiers = ["%U","%W","%w","%a","%A","%b","%B","%p","%Z","%c","%x","%X"]
print(unsupported_specifiers)

def make_series(specifier):
    try:
        return cudf.Series(dates).dt.strftime(specifier)
    except:
        return cudf.Series(["error"] * len(dates))

cudf.DataFrame({
    specifier: make_series(specifier)
    for specifier in unsupported_specifiers
})
```
shows which raise errors (%c, %x, %X - the "less common specifiers which rely on the locale's general date/time format"), and which work when by themselves (%U, %W, %w, %a, %A, %b, %B, %p, %Z).

```python
cudf.DataFrame({
    specifier+"_": make_series(specifier+"_")
    for specifier in unsupported_specifiers
})
```
shows which specifiers fail when included in a string (%a, %A, %b, %B).

If `cudf.Series` is replaced by `pd.Series`, all work fine as expected.

Apologies, I guess I should have opened a separate issue regarding this

**Comment by davidwendt** [comment]
Yes, I'd recommend opening a new issue with this new information since this issue if quite out of date now.
