### ISSUE TITLE
[Bug] NVCategory  set_keys does not mention sorted keys 

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3110]
Currently  we seem to `sort` numeric keys  when we `set_keys`. 

This makes it inconsistent with the documentation as the expected behavior is to map values to the new key indexes (unsorted). 

Example:
```python
import nvcategory
import numpy as np
c = nvcategory.from_numbers(np.array([4, 1, 2, 3, 2, 1, 4]))
print('initial keys', c.keys(),c.values())
nc = c.set_keys(np.array([4,2]))
print('final keys',nc.keys(),nc.values())
```

Output:
```python
initial keys [1, 2, 3, 4] [3, 0, 1, 2, 1, 0, 3]
final keys [2, 4] [1, -1, 0, -1, 0, -1, 1]
```

Expected Output:
```python
final keys [4, 2] [0, -1, 1, -1, 1, -1, 0]
```

### Edit:

Added that the bug is in documentation.

**Comment by kkraus14** [comment]
@VibhuJawa are you unblocked by using a CategoricalColumn with a StringColumn dictionary since the refactor?

**Comment by VibhuJawa** [comment]
So the previous bug was in `nvcategory` where we used to sort categories by default which made it inconsinstent with `pandas`.  

Our new behavior is consitent with pandas. 

```python
>>> pd.Series(["a", "b", "c", "a"], dtype="category").cat.set_categories(['b','a'])
0      a
1      b
2    NaN
3      a
dtype: category
Categories (2, object): [b, a]
```

```python
>>> cudf.Series(["a", "b", "c", "a"], dtype="category").cat.set_categories(['b','a'])
0      a
1      b
2   null
3      a
dtype: category
Categories (2, object): [b, a]
```


Env:
```
cudf                      0.14.0a200401         py37_2278    rapidsai-nightly
```

Closing the issue. Thanks for the ping here.
