### ISSUE TITLE
[DOCS] nvcategory.from_strings not showing in API docs

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3111]
https://github.com/rapidsai/custrings/blob/954f50335a0e1ff7f4da04f54baa108c3e7b32b5/python/nvcategory.py#L78

@rajkaramchedu can you tackle this? It should be similar to work you're doing in cudf. The [docs](https://docs.rapids.ai/api/nvstrings/stable/) are generated by Sphinx, which reads the Python comment-strings and produces HTML pages.

It _looks_ like some whitespace formatting may be busted such that `from_strings` isn't being rendered into html.

**Comment by kkraus14** [comment]
Closing as nvcategory is deprecated as of 0.14
