### ISSUE TITLE
[FEA] Bag of words functionality

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3112]
A very common task in NLP workflows is to create, for a given document, a vector comprising the frequency counts of each unique token in a defined vocabulary. For example, given the following:
```
vocabulary = [a, b, c, random_word]
document_tokenized = [a, a, b, b]
```
We'd have the following bag of words (BoW) vector for this document:

```
bow_vector = [2, 2, 0, 0],
```

where index 0 corresponds to `a`, index 1 to `b`, and index 2 to `c`, and so on.

Each unique token in the vocabulary is mapped to an index position in the vector. The value in that position of the vector is the frequency count of that vocabulary token in this document.

Additionally, it's common to configure which words are included in the vocabulary used to define the vector. Above, we had a vocabulary of size four, so we had a vector of size four. But, we might want to do things like:

- Set a minimum number of occurrences of a word in our corpus (collection of documents) to be considered part of the vocabulary
- Set a maximum number of tokens from the vocabulary to consider in creating the vectors, based on their word frequency (high to low)
- Pass an array of stopwords that will be removed from the vocabulary (set difference)

### Canonical API

In NLP workflows, it's very common to have have many documents. A goal state end-user API might be one in which a user could:

1) Define an array of length N in which each element is a document in the corpus (N documents)
2) Apply to or call a single bag-of-words-like function on that array to generate the word vector for each document (N word vectors)

[Scikit-learn's CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) has such an API currently.

This is their example:

```python
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']

print(X.toarray())  
[[0 1 1 1 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]
````

The `feature_names` are the unique tokens in the corpus, and `X` is the generated array of word vectors.

**Comment by VibhuJawa** [comment]
Will likely be closed by : https://github.com/rapidsai/cuml/pull/2267

**Comment by beckernick** [comment]
Closing, as per the above comment. This is available in cuML.
