### ISSUE TITLE
[FEA] Allow user to specify "removed key" value for nvcategory.set_keys

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3113]
Users sometimes want control over the sentinel value used to replace a value outside the list of "allowed" categorization keys.

`nvcategory.set_keys` should include an int param `na_rep` to be used instead of -1. The implication being that encoded values in the "allowed" key list must never be encoded as `na_rep`.

Example:
```
strs = nvstrings.to_device([''dog', 'fish', 'cat'])
cat = nvcategory.from_strings(strs)
print("Original encoding:")
print(cat.values())

print("Re-encoded:")
cat = cat.set_keys(['dog', 'fish'], na_rep=0)
print(cat.values())
```
Result:
```
Original encoding:
0, 1, 2

Re-encoded:
1, 2, 0
```

**Comment by kkraus14** [comment]
Closing as nvcategory is deprecated as of 0.14
