### ISSUE TITLE
[QST] cuStrings with NVS810+Python3.7.4+Cuda10.1

### ISSUE THREAD

**Issue by penalvch** [rapidsai/cudf#3114]
I'd like to try out using cuStrings with the following environment (no alternatives are possible for me presently):

- NVS 810
- Python 3.7.4
- Cuda 10.1
- Windows 10 x64

One may install the above via PowerShell:
choco install python3
choco install miniconda3
choco install cuda
conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults nvstrings=0.8 python=3.7.4 cudatoolkit=10.1

Is there anything known not to work with:
1) python3.7.4 versus the explicitly mentioned python3.6 as per https://github.com/rapidsai/custrings/tree/master ?
2) CUDA 10.1 versus the explicitly mentioned 10.0 as per https://github.com/rapidsai/custrings/tree/master ?
3) Using devices with 'compute capability' 5 (NVS 810 is 5)?
4) Using Windows? It is understood Windows is not officially supported, but is there anything technically stopping one from actually installing cuString as per above, and it working just fine anyways?

Thanks!

**Comment by kkraus14** [comment]
Closing as nvstrings is deprecated as of 0.14
