### ISSUE TITLE
[BUG] timestamp2long fractional second parsing

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#3118]
Error when the timestamp2long conversion fails to parse %f in a timestamp inside the timestamp string, causing values to default to 0 with no error message. This bug is consistently reproduce-able when not padding the sub-second digit to match the granularity. Erroneous behavior is confirmed in the C++ version too.

s granularity --> requires 3 digits
ms granularity --> requires 3 digits
us granularity --> requires 6 digits
ns granularity --> requires 9 digits

timestamp2long should be able to parse into any granularity regardless of the number of digits in the sub-second.

```
>>> nvstrings.to_device(["1945-03-08 09:58:48", "1945-03-08 09:58:48.1", "1945-03-08 09:58:48.0", "1945-03-08 09:58:48.2380000", '1947-10-26 14:01:12.12354346', '1945-10-26 14:01:12.762', '1965-10-26 14:01:12.762000000']).timestamp2int("%Y-%m-%d %H:%M:%S.%f", "ns")
[-783180072000000000, 0, 0, 0, 0, 0, -131968727238000000]
```

**Comment by sameerz** [comment]
Spark team waiting for this to appear in string columns before retesting.

**Comment by rwlee** [comment]
https://github.com/rapidsai/custrings/pull/418 -- this was open when the old repo was archived. This issue is resolved by a documentation fix, even though it does not resolve the correctness issue we are still worried about. There are other issues opened that have similar correctness issues, hopefully a cleaner solution to these problems can be incorporated into those reengineering efforts.

**Comment by davidwendt** [comment]
Documentation is now available here:
https://docs.rapids.ai/api/libcudf/stable/group__strings__convert.html#gacaf50d3b6d14ece094b9fc16b3d35c76
https://docs.rapids.ai/api/libcudf/stable/group__strings__convert.html#ga192bce8f917991cf0475089f9865b50f

This plus the flexibility of allowing the caller to specify the number of digits for `%f` hopefully addresses this specific issue.
If not, we can reopen this or create a new, more specific issue as well.
