### ISSUE TITLE
[DOC] Minor python doc issues

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3121]
`capitalize`, `swap case`, `upper` example incorrect (uses `lower`)
`rindex` example does not show up properly (some minor formatting issue)
`rjust` example uses `ljust`

**Comment by datametrician** [comment]
I wish I'd have seen this PR... I would have fixed them all at one time. Maybe tomorrow I'll do another PR with [noci] for the rest of these... sorry team

**Comment by randerzander** [comment]
Re-opening as #3491 only fixed `capitalize`.

**Comment by kkraus14** [comment]
Closing as nvstrings is deprecated as of 0.14 and docs for string functionality were fixed in #5213
