### ISSUE TITLE
[BUG] RMM deallocation errors on exit -- __global__ function call is not configured

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3127]
As requested, see: https://github.com/rapidsai/rmm/issues/55#issuecomment-542453923

Not a blocker, but worth noting.

**Comment by harrism** [comment]
Can you please follow the issue instructions and provide complete info here so it can be reproduced?

**Comment by lmeyerov** [comment]
The linked comment has the precise environment and source code. Unfortunately, I cannot share the triggering dataset.  As noted in the linked issue, I don't think this is a priority as it not incurring in the nightlies.

**Comment by shwina** [comment]
We iterated through a few different strategies for finalizing RMM correctly in the last few days. @lmeyerov could you please confirm if you're seeing the same behavior with the latest nightlies?

cc: @kkraus14

**Comment by shwina** [comment]
Ah I see from your comment above that this is _not_ occurring with latest nightlies.
