### ISSUE TITLE
[FEA] group by count without skipping nulls

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#3131]
**Is your feature request related to a problem? Please describe.**
We would like a `count` aggregate for the hash and sort aggregate, where we don't skip nulls. This is the equivalent to the spark function `count(*)`. 

Example:
```
scala> spark.sql("select count(arr), count(*) from (select explode(array(null, 1,2,3,4, null, 6)) as arr)").show
+----------+--------+
|count(arr)|count(1)|
+----------+--------+
|         5|       7|
+----------+--------+
```

Note also, that the same is needed for a group by aggregate:

Given a table that looks like this:
```
scala> spark.sql("select coalesce(arr % 2, 2) as key, arr  from (select explode(array(null, 1,2,3,4, null, 6)) as arr)").show
+---+----+
|key| arr|
+---+----+
|  2|null|
|  1|   1|
|  0|   2|
|  1|   3|
|  0|   4|
|  2|null|
|  0|   6|
+---+----+
```

If grouped by `key`, you'd get the following results for `coun(col)` vs `count(*)`:
```
scala> spark.sql("select key, count(arr), count(*) from (select arr, coalesce(arr % 2, 2) as key  from (select explode(array(null, 1,2,3,4, null, 6)) as arr)) group by key").show
+---+----------+--------+
|key|count(arr)|count(1)|
+---+----------+--------+
|  0|         3|       3|
|  2|         0|       2|
|  1|         2|       2|
+---+----------+--------+
```

**Describe the solution you'd like**
A group by `count` with the option of not skipping nulls.

**Describe alternatives you've considered**
Currently we implement this by materializing a new column which has no nulls, and counting that as we group.

**Comment by abellina** [comment]
Note that normally `count(*)` doesn't have a column associated with it, we are counting the things that would group within a grouping key.

**Comment by jrhemstad** [comment]
So really you just want to be able to get the size of each group? 

Functionally that may be equivalent to what you're asking for, but in terms of implementation it is quite a bit different. It would be no small undertaking to add counting nulls to the count aggregation.

**Comment by abellina** [comment]
> So really you just want to be able to get the size of each group?
Yes exactly.

This is definitely lower priority, since we can work around it, and especially if it's going to require a huge amount of work. I don't know what the interface _would_ be either, since there is no index really for this new column of counts. 

The only place that looks similar is `gdf_group_by_without_aggregations`, where it also returns a column of the first index of every grouping range. Would it make sense to have a `gdf_group_by_without_aggregations` that returned the table grouped but instead of returning just a column as the second item in the pair, it could return a table? Columns of this table would be various kinds of metadata about the groups: first index of every grouping range, number of nulls, number of items, number of NaN, etc? I am just thinking out loud.

**Comment by jrhemstad** [comment]
What I'm thinking is that we're going to overhaul libcudf's `groupby` such that it returns a `groupby` object (similar to Pandas) on which you could invoke something like `group_sizes()` which will tell you the size of each group.

**Comment by abellina** [comment]
That should work too, can't comment on the effort side of things, but something like would be easy to talk to from java.

**Comment by jrhemstad** [comment]
Superseded by https://github.com/rapidsai/cudf/issues/3708
