### ISSUE TITLE
[BUG] cudf.transpose fails with ValueError: all columns must have the same dtype

### ISSUE THREAD

**Issue by ericdill** [rapidsai/cudf#3151]
**Describe the bug**
When I have a wide dataframe and want to look at a few rows, i'll usually do this with `df.head().T` in pandas or dask. When I try to do this with a cudf dataframe I get a ValueError: all columns must have the same dtype.

**Steps/Code to reproduce bug**
```
import cudf
import pandas as pd
df = cudf.DataFrame({'a': 1, 'b': 'cat'}, index=[pd.datetime(2019, 9, 1)])
print(df)
```
produces:
```
            0    1
2019-09-01  1  cat
```
Then try to view the transpose: `df.T`, which produces:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-7fdade2a6a38> in <module>
----> 1 df.T

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/cudf/core/dataframe.py in T(self)
   2058     @property
   2059     def T(self):
-> 2060         return self.transpose()
   2061 
   2062     def melt(self, **kwargs):

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/cudf/core/dataframe.py in transpose(self)
   2048         temp_columns = self.columns.copy(deep=False)
   2049         self.columns = pd.Index(range(len(self.columns)))
-> 2050         result = libcudf.transpose.transpose(self)
   2051         self.columns = temp_columns
   2052         result = result.rename(dict(zip(result.columns, self.index)))

cudf/_lib/transpose.pyx in cudf._lib.transpose.transpose()

ValueError: all columns must have the same dtype
```

**Expected behavior**
df.T should work

**Environment overview (please complete the following information)**
 - Environment location: bare-metal
 - Method of cuDF install: conda

**Environment details**
Conda env and output of print_env.sh can be found at [this gist](https://gist.github.com/ericdill/e37176b4c3620d0c9a475b7fe9630b24)

**Comment by ericdill** [comment]
I suppose the workaround here is `df.head().to_pandas().T` which isn't really that burdensome, now that I have thought through it a bit. But for someone new to cudf that is generally familiar with pandas and dask, df.head().T not working was a bit of a surprise

**Comment by kkraus14** [comment]
Triaging old issues. This will not be addressed in the near future. In Pandas, transpose is heavily dependent on using `object` dtypes in order to have mixed dtype columns and cuDF will never support `object` dtypes fully.

In the future we could support union types to enable handling mixed dtype columns.
