### ISSUE TITLE
[BUG] ValueError: Metadata inference failed in `total_mem_usage`.

### ISSUE THREAD

**Issue by ericdill** [rapidsai/cudf#3152]
**Describe the bug**
Trying to repartition a dask_cudf dataframe fails with the `partition_size` keyword. Works just fine with the `npartitions` keyword though.

**Steps/Code to reproduce bug**
1. Read in data file
2. try and repartition with `df.repartition(partition_size=<some number>)`
3. Get the following stack trace:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    167     try:
--> 168         yield
    169     except Exception as e:

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4724     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4725         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4726 

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in total_mem_usage(df)
   5477 def total_mem_usage(df):
-> 5478     mem_usage = df.memory_usage(deep=True)
   5479     if is_series_like(mem_usage):

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/cudf/core/dataframe.py in __getattr__(self, key)
    277 
--> 278         raise AttributeError("'DataFrame' object has no attribute %r" % key)
    279 

AttributeError: 'DataFrame' object has no attribute 'memory_usage'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-21-266f82402cc4> in <module>
----> 1 df = df.repartition(partition_size=250000)

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in repartition(self, divisions, npartitions, partition_size, freq, force)
   1114 
   1115         if partition_size is not None:
-> 1116             return repartition_size(self, partition_size)
   1117         elif npartitions is not None:
   1118             return repartition_npartitions(self, npartitions)

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in repartition_size(df, size)
   5454     size = int(size)
   5455 
-> 5456     mem_usages = df.map_partitions(total_mem_usage).compute()
   5457 
   5458     # 1. split each partition that is larger than partition_size

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(self, func, *args, **kwargs)
    609         >>> ddf.map_partitions(func).clear_divisions()  # doctest: +SKIP
    610         """
--> 611         return map_partitions(func, self, *args, **kwargs)
    612 
    613     @insert_meta_param_description(pad=12)

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in map_partitions(func, *args, **kwargs)
   4764         # Use non-normalized kwargs here, as we want the real values (not
   4765         # delayed values)
-> 4766         meta = _emulate(func, *args, udf=True, **kwargs)
   4767     else:
   4768         meta = make_meta(meta, index=meta_index)

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   4723     """
   4724     with raise_on_meta_error(funcname(func), udf=kwargs.pop("udf", False)):
-> 4725         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   4726 
   4727 

~/miniconda/envs/rapids-nightly/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    187         )
    188         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 189         raise ValueError(msg)
    190 
    191 

ValueError: Metadata inference failed in `total_mem_usage`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
AttributeError("'DataFrame' object has no attribute 'memory_usage'")

Traceback:
---------
  File "/home/ericdill/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/utils.py", line 168, in raise_on_meta_error
    yield
  File "/home/ericdill/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py", line 4725, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/home/ericdill/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/dask/dataframe/core.py", line 5478, in total_mem_usage
    mem_usage = df.memory_usage(deep=True)
  File "/home/ericdill/miniconda/envs/rapids-nightly/lib/python3.7/site-packages/cudf/core/dataframe.py", line 278, in __getattr__
    raise AttributeError("'DataFrame' object has no attribute %r" % key)
```
**Expected behavior**
all keywords shown in the function signature and docstring should be functional.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit cebbec2c4df9f4aa824aa6473e7db8547b99582f (HEAD, origin/master, origin/HEAD, master)
     Author: Eric Dill <thedizzle@gmail.com>
     Date:   Fri Oct 18 07:32:24 2019 -0400
     
     Better definition of rapids env
     **git submodules***
     
     ***OS Information***
     CentOS Linux release 7.6.1810 (Core)
     NAME="CentOS Linux"
     VERSION="7 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="7"
     PRETTY_NAME="CentOS Linux 7 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:7"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"
     
     CENTOS_MANTISBT_PROJECT="CentOS-7"
     CENTOS_MANTISBT_PROJECT_VERSION="7"
     REDHAT_SUPPORT_PRODUCT="centos"
     REDHAT_SUPPORT_PRODUCT_VERSION="7"
     
     CentOS Linux release 7.6.1810 (Core)
     CentOS Linux release 7.6.1810 (Core)
     Linux desktop-qepl07h.lan 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Oct 18 12:16:32 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce RTX 2070    On   | 00000000:1F:00.0  On |                  N/A |
     |  0%   31C    P8    13W / 175W |   3904MiB /  7949MiB |     13%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      2980      G   /usr/bin/X                                   225MiB |
     |    0      7194      G   ...uest-channel-token=10447837260775572939    77MiB |
     |    0     16765      G   ...quest-channel-token=2750878945691515965   599MiB |
     |    0     17525      C   ...iniconda/envs/rapids-nightly/bin/python   235MiB |
     |    0     20556      C   ...iniconda/envs/rapids-nightly/bin/python   233MiB |
     |    0     22546      C   ...iniconda/envs/rapids-nightly/bin/python  2299MiB |
     |    0     22584      C   ...iniconda/envs/rapids-nightly/bin/python   231MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                12
     On-line CPU(s) list:   0-11
     Thread(s) per core:    2
     Core(s) per socket:    6
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             AuthenticAMD
     CPU family:            23
     Model:                 8
     Model name:            AMD Ryzen 5 2600 Six-Core Processor
     Stepping:              2
     CPU MHz:               1550.000
     CPU max MHz:           3400.0000
     CPU min MHz:           1550.0000
     BogoMIPS:              6799.09
     Virtualization:        AMD-V
which: no cmake in (/home/ericdill/miniconda/bin:/home/ericdill/miniconda/condabin:/home/ericdill/miniconda/bin:/home/ericdill/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ericdill/bin:/var/lib/snapd/snap/bin:/home/ericdill/autobin:/home/ericdill/.screenlayout)
     L1d cache:             32K
     L1i cache:             64K
     L2 cache:              512K
     L3 cache:              8192K
     NUMA node0 CPU(s):     0-11
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb hw_pstate sme retpoline_amd ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39)
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2015 NVIDIA Corporation
     Built on Tue_Aug_11_14:27:32_CDT_2015
     Cuda compilation tools, release 7.5, V7.5.17
     
     ***Python***
     /home/ericdill/miniconda/bin/python
     Python 3.6.3
     
     ***Environment Variables***
     PATH                            : /home/ericdill/miniconda/bin:/home/ericdill/miniconda/condabin:/home/ericdill/miniconda/bin:/home/ericdill/bin:/usr/local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/ericdill/bin:/var/lib/snapd/snap/bin:/home/ericdill/autobin:/home/ericdill/.screenlayout
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/ericdill/miniconda
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/ericdill/miniconda/bin/conda
     # packages in environment at /home/ericdill/miniconda:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     aiohttp                   3.6.2                    pypi_0    pypi
     asn1crypto                0.23.0           py36h4639342_0
     async-timeout             3.0.1                    pypi_0    pypi
     attrs                     19.3.0                   pypi_0    pypi
     backcall                  0.1.0                    pypi_0    pypi
     bleach                    3.1.0                    pypi_0    pypi
     bokeh                     1.3.4                    pypi_0    pypi
     bzip2                     1.0.8                h7b6447c_0
     ca-certificates           2017.08.26           h1d4fec5_0
     certifi                   2017.11.5        py36hf29ccca_0
     cffi                      1.11.2           py36h2825082_0
     chardet                   3.0.4            py36h0f667ec_1
     click                     7.0                      pypi_0    pypi
     cloudpickle               1.2.2                    pypi_0    pypi
     conda                     4.7.11                   py36_0
     conda-env                 2.6.0                h36134e3_1
     conda-package-handling    1.3.11                   py36_0
     cryptography              2.1.4            py36hd09be54_0
     dask                      2.6.0                    pypi_0    pypi
     dask-labextension         1.0.3                    pypi_0    pypi
     decorator                 4.4.0                    pypi_0    pypi
     defusedxml                0.6.0                    pypi_0    pypi
     distributed               2.6.0                    pypi_0    pypi
     entrypoints               0.3                      pypi_0    pypi
     heapdict                  1.0.1                    pypi_0    pypi
     idna                      2.6              py36h82fb2a8_1
     idna-ssl                  1.1.0                    pypi_0    pypi
     importlib-metadata        0.23                     pypi_0    pypi
     ipykernel                 5.1.2                    pypi_0    pypi
     ipython                   7.8.0                    pypi_0    pypi
     ipython-genutils          0.2.0                    pypi_0    pypi
     jedi                      0.15.1                   pypi_0    pypi
     jinja2                    2.10.3                   pypi_0    pypi
     jsonschema                3.1.1                    pypi_0    pypi
     jupyter-client            5.3.4                    pypi_0    pypi
     jupyter-core              4.6.0                    pypi_0    pypi
     jupyter-server-proxy      1.1.0                    pypi_0    pypi
     libarchive                3.3.3                h7d0bbab_1
     libedit                   3.1                  heed3624_0
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libstdcxx-ng              7.2.0                h7a57d05_2
     libxml2                   2.9.9                hea5a465_1
     lz4-c                     1.8.1.2              h14c3975_0
     lzo                       2.10                 h49e0be7_2
     markupsafe                1.1.1                    pypi_0    pypi
     mistune                   0.8.4                    pypi_0    pypi
     more-itertools            7.2.0                    pypi_0    pypi
     msgpack                   0.6.2                    pypi_0    pypi
     multidict                 4.5.2                    pypi_0    pypi
     nbconvert                 5.6.0                    pypi_0    pypi
     nbformat                  4.4.0                    pypi_0    pypi
     ncurses                   6.0                  h9df7e31_2
     notebook                  6.0.1                    pypi_0    pypi
     numpy                     1.17.3                   pypi_0    pypi
     openssl                   1.0.2s               h7b6447c_0
     packaging                 19.2                     pypi_0    pypi
     pandocfilters             1.4.2                    pypi_0    pypi
     parso                     0.5.1                    pypi_0    pypi
     pexpect                   4.7.0                    pypi_0    pypi
     pickleshare               0.7.5                    pypi_0    pypi
     pillow                    6.2.0                    pypi_0    pypi
     pip                       9.0.1            py36h6c6f9ce_4
     prometheus-client         0.7.1                    pypi_0    pypi
     prompt-toolkit            2.0.10                   pypi_0    pypi
     psutil                    5.6.3                    pypi_0    pypi
     ptyprocess                0.6.0                    pypi_0    pypi
     pycosat                   0.6.3            py36h0a5515d_0
     pycparser                 2.18             py36hf9f622e_1
     pygments                  2.4.2                    pypi_0    pypi
     pyopenssl                 17.5.0           py36h20ba746_0
     pyparsing                 2.4.2                    pypi_0    pypi
     pyrsistent                0.15.4                   pypi_0    pypi
     pysocks                   1.6.7            py36hd97a5b1_1
     python                    3.6.3                h6c0c0dc_5
     python-dateutil           2.8.0                    pypi_0    pypi
     python-libarchive-c       2.8                     py36_13
     pyyaml                    5.1.2                    pypi_0    pypi
     pyzmq                     18.1.0                   pypi_0    pypi
     readline                  7.0                  ha6073c6_4
     requests                  2.18.4           py36he2e5f8d_1
     ruamel_yaml               0.11.14          py36ha2fb22d_2
     send2trash                1.5.0                    pypi_0    pypi
     setuptools                36.5.0           py36he42e2e1_0
     simpervisor               0.3                      pypi_0    pypi
     six                       1.11.0           py36h372c433_1
     sortedcontainers          2.1.0                    pypi_0    pypi
     sqlite                    3.20.1               hb898158_2
     tblib                     1.4.0                    pypi_0    pypi
     terminado                 0.8.2                    pypi_0    pypi
     testpath                  0.4.2                    pypi_0    pypi
     tk                        8.6.7                hc745277_3
     toolz                     0.10.0                   pypi_0    pypi
     tornado                   6.0.3                    pypi_0    pypi
     tqdm                      4.32.1                     py_0
     traitlets                 4.3.3                    pypi_0    pypi
     typing-extensions         3.7.4                    pypi_0    pypi
     urllib3                   1.22             py36hbe7ace6_0
     wcwidth                   0.1.7                    pypi_0    pypi
     webencodings              0.5.1                    pypi_0    pypi
     wheel                     0.30.0           py36hfd4bba0_1
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7                had09818_2
     yarl                      1.3.0                    pypi_0    pypi
     zict                      1.0.0                    pypi_0    pypi
     zipp                      0.6.0                    pypi_0    pypi
     zlib                      1.2.11               ha838bed_2
     zstd                      1.3.3                h84994c4_0
     
</pre></details>

**Comment by kkraus14** [comment]
We don't have a `memory_usage` function for cuDF quite yet so this is expected for the time being.

**Comment by galipremsagar** [comment]
Closing this issue as this seems to be resolved with addition of `memory_usage` function in cuDF.
```python
>>> df = cudf.DataFrame({'a':[1,2,3,4,5,6,6], 'b':[0,0,0,0,1,1,1]})
>>> df
   a  b
0  1  0
1  2  0
2  3  0
3  4  0
4  5  1
5  6  1
6  6  1

>>> df.memory_usage()
a        56
b        56
Index     0
dtype: int64
>>> import dask_cudf
>>> s = dask_cudf.from_cudf(df, npartitions=4)
>>> from dask.dataframe.core import total_mem_usage
>>> s
<dask_cudf.DataFrame | 3 tasks | 3 npartitions>
>>> s.map_partitions(total_mem_usage)
Dask Series Structure:
npartitions=3
0    int64
2      ...
4      ...
6      ...
dtype: int64
Dask Name: total_mem_usage, 6 tasks
>>> s.map_partitions(total_mem_usage).compute()
0    32
1    32
2    48
dtype: int64
>>> 
```
