### ISSUE TITLE
[QST] Stable cuDF 10.0 and rapidsai/xgboost

### ISSUE THREAD

**Issue by ivenzor** [rapidsai/cudf#3153]
I just want to be sure.

For stable cuDF 10.0, rapidsai/xgboost shouldn't be used and instead I should pip install xgboost https://xgboost-ci.net/job/xgboost/job/master/lastSuccessfulBuild/artifact/python-package/dist/xgboost-1.0.0_SNAPSHOT-py2.py3-none-any.whl

Am I correct?

**Comment by kkraus14** [comment]
cc @JohnZed

**Comment by JohnZed** [comment]
If you are installing packages, we recommend the rapids-xgboost conda package that has been posted in the rapidsai conda repo. You can install like:

```
conda install -c rapidsai -c nvidia -c conda-forge \
        rapids-xgboost cudatoolkit=10.0
```

You can also use the recent XGBoost pip packages from XGBoost directly (like the one you have listed). Those will be more up-to-date with master in the XGBoost repo but will be updated nightly, whereas the rapids-xgboost package will remain stable.

If you want to install from source, you can use recent master builds from XGBoost or the rapids-0.10-release branch from github.com/rapidsai/xgboost.

**Comment by ivenzor** [comment]
@JohnZed thanks for the answer. Some weeks ago I got the idea that rapidsai/xgboost was not compatible with cuDF 10.0, but I can see it was recently updated.
