### ISSUE TITLE
[FEA] CUDF_VERSION in cudf.h ?

### ISSUE THREAD

**Issue by OlivierNV** [rapidsai/cudf#3155]
**Is your feature request related to a problem? Please describe.**
Changes to cudf functionality may break existing code that relies on cudf. The lack of versioning makes it difficult to have a code base that could support multiple cudf versions. 

**Describe the solution you'd like**
Seems like a CUDF_VERSION, perhaps along with CUDF_VERSION_{MAJOR|MINOR} definitions would be useful. Would also be useful for cudf-io writers for putting cudf version in parquet/orc files.

**Comment by GregoryKimball** [comment]
I believe this is resolved, including `CUDF_VERSION`, `CUDF_VERSION_MAJOR` and `CUDF_VERSION_MINOR`

**Comment by vyasr** [comment]
I don't believe that this exists yet.

**Comment by vyasr** [comment]
@robertmaynard isn't this trivially solvable now with https://docs.rapids.ai/api/rapids-cmake/stable/command/rapids_cmake_write_version_file/?

**Comment by robertmaynard** [comment]
Rapids-cmake would provide the major, minor, and patch defines. That should be sufficient for consuming projects
