### ISSUE TITLE
[BUG] read_csv byte_range mishandling resumption on lines with quotes

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3156]
**Describe the bug**

When writing an iterator via bytes_read to read a csv in chunks and print them back out, lines with quotes seem to be confusing the parser on where the line starts:

```
5:11.683,2018-01-18 18:12:11.111,abc\/index2.php,,                <div id=\"abc\" class=\"sbbtext normaltext\">
```

=>

```
5:11.683,2018-01-18 18:12:11.111,abc\/index2.php,,                <div id=\""abc\"" class=\""sbbtext normaltext\"">
"sbbtext normaltext\"">
```

Note that `"sbbtext normaltext\"">` is duplicated in the output 2x.

**Steps/Code to reproduce bug**

```
df = None
offset =0
step=1000
while not done:
        print("Step", str(offset))
        try:
            df = cudf.io.read_csv(infile,
                                  byte_range=[offset,step], 
                                  names=names_long,
                                  dtype=dtype_long)
             df.to_pandas().to_csv('out.csv', mode='a')
        except Exception as e:
            print('Done?', e)
            done = True
            break
        if len(df) < 1:
            print('0 rows, stop')
            break
        else:
            offset = offset + step
            row_count = row_count + len(df)
```

**Expected behavior**

I'd expect either the second occurence to be the full line or not exist, but not to get a partial & duplicated result

**Environment overview (please complete the following information)**

`rapidsai/rapidsai-nightly:cuda10.0-runtime-ubuntu18.04`

**Comment by lmeyerov** [comment]
Maybe the meta thing:

0. The goal is use the GPU for faster csv parsing + very light processing
1. The reason I'm using bytes is b/c we're blowing out of GPU mem so need to iterate
2. ... because skiprows/nrows seems to be much slower (full parse?) and docs point towards bytes instead
3. ... and it's unclear how to do bytes-based iteration

Part of the answer may be " use cudfdask.read_csv" and improve docks

**Comment by ayushdg** [comment]
May not apply to your case but #2398 and #873 might be interesting reads.

**Comment by lmeyerov** [comment]
Yeah, doing `quoting=3` to ignore quotations seems to work in this case, but not reliable, e.g., as we go from the 1k test set to 100GB :)

**Comment by harrism** [comment]
@vuule Can you do a little triage on this to determine next steps / estimate work involved?

**Comment by vuule** [comment]
@lmeyerov can you please share the input file that you read with the attached snippet?

**Comment by vuule** [comment]
Turns out we have very limited `byte_range` test coverage - there are no `byte_range` tests that include strings.
Looking at the parsing code, there's one potential issue when strings are parsed with `byte_range` - if the byte range starts within a string, the parser would get confused and filter out the line ends as being parts of strings (closing quotations become opening, and vice versa). This would take less than a day to fix.
I'm not sure if this is the same bug as the issue reported here. I would need to repro the reported issue locally to make sure it's actually addressed with the fix.

**Comment by lmeyerov** [comment]
Hi @vuule  not sure what you're asking , input is copied above.

Maybe more meta: we were working through a threat feed (I cannot share unfortunately) with all sorts of weird characters, and I was having difficulty pushing it through neo4j + rapids. That's a classic adverserial scenario where folks put weird characters in to trick tools. Maybe use a guided fuzzer or something to generate more? I can ask PL twitter if there's a favorite tool here..

**Comment by vuule** [comment]
I guess I don't understand the repro steps as described. The only input copied above is the line
`5:11.683,2018-01-18 18:12:11.111,abc\/index2.php,,                <div id=\"abc\" class=\"sbbtext normaltext\">`
And based on the step size in the posted script, it looks like this is not the entire input file (it's smaller than a single step).

**Comment by lmeyerov** [comment]
Yes that is the line that tripped it up, found via delta debugging

I can't share uninvolved lines as this is customer data

**Comment by vuule** [comment]
> I can't share uninvolved lines as this is customer data

Not a problem, I think I found the root cause (got a similar local repro).
