### ISSUE TITLE
[DOC] update CONTRIBUTING.MD to better capture dependencies.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#3160]
RMM (and possibly DLPACK?) used to be submodules but are now seperate packages. 

Setting up using conda  (/cudf/conda/environments/cudf_dev_cuda10.0.yml) makes this process significantly easier.

Additional:   If you have been trying to build and getting failures, activating the conda environment after the fact may appear to not work because of cmake caching issues.  Deleting the build folder (cpp/build) appears to remedy this.

**Comment by beckernick** [comment]
@nvdbaranec do you feel like this is still relevant?

**Comment by nvdbaranec** [comment]
No, probably not.

**Comment by beckernick** [comment]
Thanks! Closing. If that changes, we can reopen.
