### ISSUE TITLE
[FEA] Series and DataFrame size attr

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3164]
**Is your feature request related to a problem? Please describe.**

When setting up large data pipelines, e.g., manually shuffling out-of-memory bits in-and-out, it'd be quite helpful to know how many bytes a `Series` and `DataFrame` are, esp. when created from a method such as `load_csv`. 

The current inference work around is a longer version of:

```
my_sizeof(df):
  sum = 0
  for c in df:
    if primitive(c): 
       sum += sizeof(type(df(c)) * len(c)
    if c is string:
       sum+= df[c].str.len().sum()
  return sum
```

**Describe the solution you'd like**

`Series` and `DataFrame` should have a low-cost (e.g., CPU-only and no traversal required) getter such as `.num_bytes`

**Describe alternatives you've considered**

* Manual workaround: What we're doing
* Cleaner version: I'm unfamiliar with pandas idioms here (maybe none, as less ability to do big data there?) and Python/numpy ones, so I'd check if there is a naming convention here.
* More broadly, cudf / dask-cudf should support out-of-memory use (and tutorials for that), if it doesn't already. 
* Some way for DF's at IO boundaries to report size statistics, and/or have as part of `.describe()`

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

See discussion here: https://rapids-goai.slack.com/archives/C5E06F4DC/p1571617513016200

**Comment by lmeyerov** [comment]
For now:

```
def series_size(s):
    if pd.api.types.is_string_dtype(s.dtype):
        print('str => %s', s.str.devic`e_memory())
        return s.str.device_memory()
    else:
        print('fixed => %s', s.dtype.itemsize * len(s))
        return s.dtype.itemsize * len(s)

def df_size(gdf):
    return sum([series_size(gdf[c]) for c in gdf.columns])
``

**Comment by quasiben** [comment]
I think this is now covered by `memory_usage`:
https://github.com/rapidsai/cudf/pull/3610

```python
In [46]: cdf = cudf.DataFrame({'a': np.arange(3), 'b': [1, 0, 1]})

In [47]: cdf.memory_usage()
Out[47]:
a        24
b        24
Index     0
dtype: int64

In [48]: cdf.a.memory_usage()
Out[48]: 24

In [49]: cdf.memory_usage(deep=True)
Out[49]:
a        24
b        24
Index     0
dtype: int64
```
