### ISSUE TITLE
[BUG] ORC reader reading date as timestamp

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#3174]
**Describe the bug**
The ORC writer is reading a date field as timestamp 

**Steps/Code to reproduce bug**
Convert a file from parquet which has a date field to ORC (file0.orc) 
Read file0.orc and write it again as file1.orc

Comparing the schema of the two files will show file0.orc has date while file1.orc has timestamp

file converted from parquet to orc using cudf: 
struct<loan_id:bigint,orig_channel:int,orig_interest_rate:double,orig_upb:int,orig_loan_term:int,orig_date:date,first_pay_date:date,orig_ltv:double,orig_cltv:double,num_borrowers:double,dti:double,borrower_credit_score:double,first_home_buyer:int,loan_purpose:int,property_type:int,num_units:int,occupancy_status:int,property_state:int,zip:int,mortgage_insurance_percent:double,product_type:int,coborrow_credit_score:double,mortgage_insurance_type:double,relocation_mortgage_indicator:int,quarter:int,seller_id:int>
orc file rewritten after being read by cudf ORC reader: 
struct<loan_id:bigint,orig_channel:int,orig_interest_rate:double,orig_upb:int,orig_loan_term:int,orig_date:timestamp,first_pay_date:timestamp,orig_ltv:double,orig_cltv:double,num_borrowers:double,dti:double,borrower_credit_score:double,first_home_buyer:int,loan_purpose:int,property_type:int,num_units:int,occupancy_status:int,property_state:int,zip:int,mortgage_insurance_percent:double,product_type:int,coborrow_credit_score:double,mortgage_insurance_type:double,relocation_mortgage_indicator:int,quarter:int,seller_id:int>

**Expected behavior**
The date field should remain as date type

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
 rjafri   ORC  ~  nvcudf  1  ./print_env.sh 
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 27878a8e106aa63d103f9dfea12afbd9f94d3347 (HEAD -> ORC, github/ORCWriter)
     Author: Raza Jafri <rjafri@nvidia.com>
     Date:   Fri Oct 18 18:46:45 2019 -0700
     
     get absolutefilepath
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     63f644be44201467e3938d59ed9d89cc8725c35d thirdparty/jitify (remotes/origin/feature/api_v2_v0.10)
     5654f2bcc8972d513cf9cedf28510c1b6613aeeb thirdparty/libcudacxx (0.8.1-82-g5654f2b)
     34dfe2830dbd7322d00fe5b9c85d1832b8b955ca thirdparty/libcudacxx/libcxx (34dfe28)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"
     NAME="Ubuntu"
     VERSION="16.04.6 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.6 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux raza-linux-2 4.15.0-65-generic #74~16.04.1-Ubuntu SMP Wed Sep 18 09:51:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Oct 21 17:19:50 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.78       Driver Version: 410.78       CUDA Version: 10.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  TITAN X (Pascal)    Off  | 00000000:0A:00.0  On |                  N/A |
     | 23%   38C    P8    18W / 250W |   1011MiB / 12187MiB |     13%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      7258      G   /usr/lib/xorg/Xorg                           607MiB |
     |    0      8694      G   compiz                                       320MiB |
     |    0     10176      G   ...uest-channel-token=13731392033325103117    57MiB |
     |    0     12465      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     12525      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     12542      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     12562      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     12732      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     21485      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     30225      G   /usr/lib/firefox/firefox                       2MiB |
     |    0     31373      G   /usr/lib/firefox/firefox                       2MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                12
     On-line CPU(s) list:   0-11
     Thread(s) per core:    2
     Core(s) per socket:    6
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 63
     Model name:            Intel(R) Core(TM) i7-5820K CPU @ 3.30GHz
     Stepping:              2
     CPU MHz:               1515.111
     CPU max MHz:           3600.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              6598.03
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              15360K
     NUMA node0 CPU(s):     0-11
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm cpuid_fault epb invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /home/rjafri/miniconda2/envs/cudf_dev/bin/cmake
     cmake version 3.15.4
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /home/rjafri/miniconda2/envs/cudf_dev/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/rjafri/miniconda2/envs/cudf_dev/bin:/home/rjafri/miniconda2/bin:/home/rjafri/miniconda2/condabin:/home/rjafri/bin:/usr/local/cuda/bin:Android/Sdk/platform-tools:/usr/local/go/bin:/home/rjafri/bin:/home/rjafri/.local/bin:/opt/maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64:/usr/local/cuda-8.0/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/rjafri/miniconda2/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/rjafri/miniconda2/bin/conda
     # packages in environment at /home/rjafri/miniconda2/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
     asn1crypto                1.0.1                    py37_0    conda-forge
     aspy.yaml                 1.3.0                      py_0    conda-forge
     atomicwrites              1.3.0                      py_0    conda-forge
     attrs                     19.2.0                     py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     black                     19.3b0                     py_0    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.3.4                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_1    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.9.11            hecc5488_0    conda-forge
     cached-property           1.5.1                      py_0    conda-forge
     certifi                   2019.9.11                py37_0    conda-forge
     cffi                      1.12.3           py37h8022711_0    conda-forge
     cfgv                      2.0.1                      py_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_0    conda-forge
     cmake                     3.15.4               hf94ab9c_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              2.7              py37h72c5cf5_0    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cython                    0.29.13          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.0           py37h516909a_0    conda-forge
     dask                      2.5.2+14.g0b2b15b          pypi_0    pypi
     decorator                 4.4.0                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.5.2+8.g00d7f7d          pypi_0    pypi
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     editdistance              0.5.3            py37hf484d3e_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1003    conda-forge
     fastavro                  0.22.5           py37h516909a_0    conda-forge
     flake8                    3.7.8                    py37_1    conda-forge
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.5.2                      py_0    conda-forge
     future                    0.18.0                   py37_0    conda-forge
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                4.40.0                   py37_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     identify                  1.4.7                      py_0    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        0.23                     py37_0    conda-forge
     ipykernel                 5.1.2            py37h5ca1d4c_0    conda-forge
     ipython                   7.8.0            py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     4.3.21                   py37_0    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     jsonschema                3.1.1                    py37_0    conda-forge
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.5.0                      py_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     libblas                   3.8.0               13_openblas    conda-forge
     libcblas                  3.8.0               13_openblas    conda-forge
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     liblapack                 3.8.0               13_openblas    conda-forge
     libopenblas               0.3.7                h6e990d7_1    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.10.0a191014      cuda10.0_169    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.10            h57b8799_1003    conda-forge
     libuv                     1.32.0               h516909a_0    conda-forge
     llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  2.6.11                   pypi_0    pypi
     markupsafe                1.1.1            py37h14c3975_0    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mistune                   0.8.4           py37h14c3975_1000    conda-forge
     more-itertools            7.2.0                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     nbconvert                 5.6.0                    py37_1    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.4.3                      py_0    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nodeenv                   1.3.3                      py_0    conda-forge
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.45.1           py37hb3f55d8_0    conda-forge
     numpy                     1.17.2           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.2.0            py37h6b7be26_0    conda-forge
     pip                       19.2.3                   py37_0    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     pre_commit                1.18.1                   py37_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.10                     py_0    conda-forge
     psutil                    5.6.3            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.14.1           py37h8b68381_2    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.4.2                      py_0    conda-forge
     pyopenssl                 19.0.0                   py37_0    conda-forge
     pyparsing                 2.4.2                      py_0    conda-forge
     pyrsistent                0.15.4           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.2.1                    py37_0    conda-forge
     python                    3.7.3                h33d41f4_1    conda-forge
     python-dateutil           2.8.0                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.1.0           py37h1768529_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.10.0a191014          py37_169    rapidsai-nightly
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                41.4.0                   py37_0    conda-forge
     six                       1.12.0                py37_1000    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.2.0                      py_0    conda-forge
     sphinx-markdown-tables    0.0.9                    pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     streamz                   0.5.2                    pypi_0    pypi
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.2                    py37_0    conda-forge
     testpath                  0.4.2                   py_1001    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.6                   py37_0    conda-forge
     virtualenv                16.7.5                     py_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7             h14c3975_1001    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.0                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

test code used to analyze 

  private static void testcudfORCvsApache() throws IOException {
    File parquetFile = new File("/home/rjafri/nvcudf/java/src/test/resources/acq.parquet");
    File parquetToORC = File.createTempFile("parquet-orc", ".orc");
    File orcRewritten = File.createTempFile("orc-rewritten", ".orc");
    try (Table t0 = Table.readParquet(parquetFile)) {
      t0.writeORC(parquetToORC);
    }
    Reader reader = OrcFile.createReader(new Path(parquetToORC.getAbsolutePath()),
        OrcFile.readerOptions(new Configuration()));
    TypeDescription typeDescription = reader.getSchema();
    System.out.println("file converted from parquet to orc using cudf: "+typeDescription.toString());
    try (Table t0 = Table.readORC(parquetToORC)) {
      t0.writeORC(orcRewritten);
    }
    reader = OrcFile.createReader(new Path(orcRewritten.getAbsolutePath()),
        OrcFile.readerOptions(new Configuration()));
    typeDescription = reader.getSchema();
    System.out.println("orc file rewritten after being read by cudf ORC reader: "+typeDescription.toString());
  }

**Comment by OlivierNV** [comment]
I think this is mostly a duplicate of #2384 , though I think the 'use_np_dtypes' flag may not be exposed on the python side, so we'll probably need to add it there if not present.

**Comment by razajafri** [comment]
We are using cpp directly. I can add that flag and see if it changes

**Comment by razajafri** [comment]
Confirmed, the issue is fixed by setting the flag to false
