### ISSUE TITLE
[DOC] Dask + Pandas --> Dask + cuDF Conversion

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/cudf#3176]
## Reporting confusing documentation

I'm looking at the "Multi-GPU with Dask-cuDF" documentation at https://rapidsai.github.io/projects/cudf/en/0.10.0/dask-cudf.html
Specifically, the section "Converting to and from other forms"

There are four types of conversions discussed:
1.     Dask + Pandas to Dask + cuDF df.map_partitions(cudf.from_pandas)
2.     Dask + cuDF to Dask + Pandas df.map_partitions(lambda df: df.to_pandas())
3.     cuDF to Dask + cuDF: dask.dataframe.from_pandas(df, npartitions=20)
4.      Dask + cuDF to cuDF: df.compute()

Three of these work (2, 3, 4).
However, the first item "Dask + Pandas to Dask + cuDF" does not work.
The documented call "df.map_partitions(cudf.from_pandas)" does not seem right -- what is from_pandas (a function? an attribute?) What is being called? Where does the input pandas df go? I tried numerous variations of this call, all resulting in low-level errors. 

I tried this with v0.9 and v0.10 via the container.

I can certainly go pandas --> cudf --> dask-cudf -- is that the recommended pathway? If so, what does conversion #1 from the docs refer to?

Could the best practice for pandas --> dask-cudf be shared?

```
# we start with a regular cudf
# works fine:
df = cudf.DataFrame([('a', list(range(20))),
('b', list(reversed(range(20)))),
('c', list(range(20))),
('x','172.2.3.6')])
print(df.head())

# then we go to dask_cudf
# also works fine:
ddf = dask_cudf.from_cudf(df, npartitions=1)
ddf.head()

# we grab a select field for computation w/ pandas (for string col not supported on cudf)
# also works fine: 
x_pd = ddf.map_partitions(lambda dfx: dfx.to_pandas()).compute()
print(type(x_pd))
ipdf = x_pd.x.str.split(".", n = 3, expand = True) 
x_pd['ip1']=ipdf[0]
x_pd['ip2']=ipdf[1]
```

**Comment by ayushdg** [comment]
Thank you for raising this issue! The docs do need some updates w.r.t the the cases mentioned. 

For the specific case `Dask + Pandas to Dask + cuDF df.map_partitions(cudf.from_pandas)` which does not work. It should be updated to something like this:
`Dask + Pandas to Dask + cuDF df.map_partitions(cudf.DataFrame.from_pandas)`

Here `cudf.DataFrame.from_pandas` is a function and partitions of the `df` calling `map_partitions` will be the first argument passed to the method. More information about `map_partitions` can be found in the [dask docs](https://docs.dask.org/en/stable/dataframe-api.html#dask.dataframe.DataFrame.map_partitions).

Conversion from dask+pandas -> dask+cudf refers to the case where you have a Dask Dataframe where the underlying data is a pandas dataframe and you want to move to a Dask Dataframe where the underlying dataframe is a cudf GPU DataFrame. This is useful when you *have* to perform some pandas operation in parallel taking advantage of the multiple cpu cores and then move to cudf to perform super fast operations on the GPU.

Based on the example you shared above, I'd also love to point out that our string support and integrations is being completely refactored and should be even better in the future. However, for now cudf does support string operations like `split` on the GPU and might work as an alternative to using pandas for this operation.
