### ISSUE TITLE
[DOC] Best Practice on String Operations on cuDF / dask-cudf Series/DF

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/cudf#3177]
We're trying to understand the best practice on string manipulation (e.g., for feature engineering pre model training.)

We've read through the documentation at https://rapidsai.github.io/projects/cudf/en/0.10.0/dask-cudf.html and reviewed the string-related Github Issues on this repo. Until applying function maps for string ops is enabled, is the best practice to:
- Bring select columns from dask/cudf_dask into pandas 
- Apply the changes
- Bring the changed columns back from pandas into dask/cudf-dask 

It would be good to understand the recommended approach while awaiting full string support.

Thanks

**Comment by jpjenk** [comment]
I also would like to understand the best-practices in this case

**Comment by kkraus14** [comment]
@saifrahmed @jpjenk We’re in the middle of a large refactor that completely reworks how strings are handled that will allow us to do more and better optimize things. That being said, UDFs (apply functions) will continue to not be supported for strings for the foreseeable future.

In this case if you need a UDF the best practice is as you said to move the column(s) back to Pandas / Dask DataFrame, run the UDF, then move back to cuDF / Dask-cuDF.
