### ISSUE TITLE
[DOC] Conversion Dask + cuDF to Dask + Pandas: Is there such a thing as Dask+Pandas?

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/cudf#3178]
## Reporting confusing documentation

I'm looking at the "Multi-GPU with Dask-cuDF" documentation at https://rapidsai.github.io/projects/cudf/en/0.10.0/dask-cudf.html
Specifically, the section "Converting to and from other forms"

There are four types of conversions discussed, but this clarification / documentation request is around the second item: "Dask + cuDF to Dask + Pandas", which is shown as:
`df.map_partitions(lambda df: df.to_pandas())`

I ran the below code and the "Dask + cuDF to Dask + Pandas" operation seems to produce just a regular Pandas dataframe. The type comes out as <class 'pandas.core.frame.DataFrame'>

We would appreciate clarification on several items:
1. Is there such a thing as a conversion to "Dask + Pandas" or is it just a conversion to Pandas?
2. Does this force the column[s] to be materialized locally on the client machine, or is it somehow distributed? If it is somehow distributed, why is the datatype suggesting otherwise?

Thanks

```
# we start with a regular cudf
# works fine:
df = cudf.DataFrame([('a', list(range(20))),
('b', list(reversed(range(20)))),
('c', list(range(20))),
('x','172.2.3.6')])
print(df.head())

# then we go to dask_cudf
# also works fine:
ddf = dask_cudf.from_cudf(df, npartitions=1)
ddf.head()

# we grab a select field for computation w/ pandas (for string col not supported on cudf)
# also works fine: 
x_pd = ddf.map_partitions(lambda dfx: dfx.to_pandas()).compute()
print(type(x_pd))
```

**Comment by jpjenk** [comment]
Understanding this would also be very helpful. I've been struggling with this. Looking forward to the responses.

**Comment by VibhuJawa** [comment]
Sorry for the delayed response. 

> 1. Is there such a thing as a conversion to "Dask + Pandas" or is it just a conversion to Pandas?

Yup, so i think what you are looking for is called [dask.DataFrame](https://docs.dask.org/en/latest/dataframe.html)

> 2. Does this force the column[s] to be materialized locally on the client machine, or is it somehow distributed? If it is somehow distributed, why is the datatype suggesting otherwise?

It should be  distributed.  The `data-type`  is  suggesting otherwise because of the `.compute` call which force the dataframe to be materialized locally on the client machine and converted to pandas.

See [api.] docs. (https://docs.dask.org/en/latest/dataframe-api.html?highlight=dask%20compute#dask.dataframe.compute) 


 ```
> x_pd = ddf.map_partitions(lambda dfx: dfx.to_pandas())
> print(type(x_pd))
<class 'dask.dataframe.core.DataFrame'>
```

```
> x_pd = ddf.map_partitions(lambda dfx: dfx.to_pandas()).compute()
> print(type(x_pd))
<class 'pandas.core.frame.DataFrame'>
```
