### ISSUE TITLE
[FEA] nvstrings functions Spark uses, that should be ported to string columns

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#3179]
Here are the operations that we know we use from NVStrings, that we would like to get with the string column redesign.

Casting:
- [x] string <-> date
- [x] long/integer <-> string
- [x] string <-> timestamp

String operations:
Higher priority
- [x] **contains:** return true if string contains a substring.
- [x] **ends with**: `endswith(string, substr)` return true if string ends with substr.
- [x] **starts with:** `startswith(string, substr)` return true if string starts with substr.
- [x] **substring:** `substring(string, pos, len)`. Note that pos can be negative.
- [ ] **regex:** initially to produce a boolean column with true for a match, and false otherwise, but other regex expressions allow capturing groups in Spark (not as high a priority).

Others:
- [x] **concatenation:** `strcat(col1, sep, col2)` produces a new string column with: col1 + sep + col2
- [x] **locate(string search):** return position of first occurrence of string, with an optional starting position.
- [x] **lower:** return lowercase of column.
- [x] **upper:** return uppercase of column.

**Comment by abellina** [comment]
This is a good starting point, but I expect this list to grow. The issue is not meant to mean 1 PR to port all of these, but just to get it in the radar of those doing the nvstring -> string column refactor.

**Comment by harrism** [comment]
@davidwendt can you update the description above with links to any PR #s that are already open for this list?

**Comment by davidwendt** [comment]
| function | PR | Notes |
| --- | --- | --- |
| `contains` | #3189 | non-regex implementation |
| `ends_with` and `starts_with` | #3189 |  |
| `slice_strings` | #3170  | does not accept negative character position |
| `contains_re`  |  #3292 | regex implementation |
| `concatenate` | #2991 | supports separator and narep |
| `find` and `rfind` | #3189 | accepts starting and ending character positions |
| `to_lower` and `to_upper` | #3217 | includes same limitations as `NVStrings` right now |
| `to_integers` and `from_integers` | #3191 | supports all cudf integer types |
| `to_timestamps` and `from_timestamps` | #3232 | supports all cudf timestamp types |

**Comment by harrism** [comment]
Thanks @davidwendt. For the four remaining, should we request individual issues to be filed with details?

**Comment by davidwendt** [comment]
> Thanks @davidwendt. For the four remaining, should we request individual issues to be filed with details?

I believe these to be covered with the above. If not, yes, let's open issues.
- string/date should be covered with `to_timestamps/from_timestamps`
- substring should be covered with `slice_strings` -- separate issue needed to support negative pos
- regex description is vague but expect to be covered by the `contains_re` and the other existing regex PRs
- locate should be covered with `find`

**Comment by harrism** [comment]
So basically regex is the only piece that isn't done in this issue. @abellina suggest filing individual issues for each further strings feature request. Catch-all issues tend to leave loose ends that languish, in my opinion.

**Comment by abellina** [comment]
@harrism @davidwendt thanks for the work to implement these. Sorry for the catch-all issue. I'll split the regex one into a new issue to track it that way, so we can close this one then.
