### ISSUE TITLE
[BUG] `to_arrow` is 2x slower in with Numpy < 1.17

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3185]
**Describe the bug**
The `to_arrow` method is 2x slower in the docker images and some Conda environments when compared to a Conda environment / custom environment which seems to install the same rapids libraries. 

**Steps/Code to reproduce bug**
```
import cudf
import time


nrows = 10_000_000
df = cudf.datasets.randomdata(nrows = nrows, dtypes = {'a':int,'b':int, 'c':float,'d':float}, seed = 1)

for i in range(10):
    t1 = time.time()
    a = df.to_arrow(preserve_index = False)
    print(time.time()-t1)
```

In the slow environment: ~ 0.2 seconds for all runs
In the fast environment: ~0.1 seconds for all runs

**Expected behavior**
Similar timing. Maybe some other library is the reason for the speed difference between the two environments

**Environment overview (please complete the following information)**

**Slow envs:**
Stable docker releases and 
Slow_environment.yml
```
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - python=3.7
  - cudatoolkit=10.0
  - rapids=0.10
```

**Fast environment:**
```
channels:
  - rapidsai
  - nvidia
  - conda-forge
dependencies:
  - cudatoolkit=10.0
  - cudf=0.10
  - cugraph=0.10
  - dask-cuda=0.10
  - dask-cudf=0.10
  - xgboost
  - dask-xgboost
```

**Environment details**
<details>
<summary> Slow Environment packages </summary>
<pre>
_libgcc_mutex             0.1                        main  
arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.10.16                    0    anaconda
certifi                   2019.9.11                py37_0    anaconda
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
cudatoolkit               10.0.130                      0    nvidia
cudf                      0.10.0                   py37_0    rapidsai
cugraph                   0.10.0                   py37_0    rapidsai
cuml                      0.10.0          cuda10.0_py37_0    rapidsai
cuspatial                 0.10.0                   py37_0    rapidsai
cython                    0.29.13          py37he1b5a44_0    conda-forge
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask                      2.6.0                      py_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
dask-cuda                 0.10.0                   py37_0    rapidsai
dask-cudf                 0.10.0                   py37_0    rapidsai
dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai
distributed               2.6.0                      py_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_1    conda-forge
fastavro                  0.22.5           py37h516909a_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.5.2                      py_0    conda-forge
gflags                    2.2.2             he1b5a44_1001    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcudf                   0.10.0               cuda10.0_0    rapidsai
libcugraph                0.10.0               cuda10.0_0    rapidsai
libcuml                   0.10.0               cuda10.0_0    rapidsai
libcumlprims              0.10.0               cuda10.0_0    nvidia
libcuspatial              0.10.0               cuda10.0_0    rapidsai
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnvstrings              0.10.0               cuda10.0_0    rapidsai
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.10.0               cuda10.0_0    rapidsai
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libxgboost                1.0.0.SNAPSHOT       cuda10.0_1    rapidsai
llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nccl                      2.4.6.1              cuda10.0_0    nvidia
ncurses                   6.1               hf484d3e_1002    conda-forge
numba                     0.45.1           py37hb3f55d8_0    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
nvstrings                 0.10.0                   py37_0    rapidsai
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1                h7b6447c_0    anaconda
packaging                 19.2                       py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.0.0                      py_0    conda-forge
pillow                    6.2.1            py37h6b7be26_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
py-xgboost                1.0.0.SNAPSHOT   cuda10.0py37_1    rapidsai
pyarrow                   0.14.1           py37h8b68381_2    conda-forge
pynvml                    8.0.3                      py_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
rapids                    0.10.0          cuda10.0_py37_1    rapidsai
rapids-xgboost            0.10.0          cuda10.0_py37_0    rapidsai
re2                       2019.09.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rmm                       0.10.0                   py37_0    rapidsai
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xgboost                   1.0.0.SNAPSHOT   cuda10.0py37_1    rapidsai
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
</pre>
</details>

<details>
<summary> Fast environment packages </summary>
<pre>
_libgcc_mutex             0.1                        main  
arrow-cpp                 0.14.1           py37h5ac5442_4    conda-forge
bokeh                     1.3.4                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_1    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_0    conda-forge
cudatoolkit               10.0.130                      0    nvidia
cudf                      0.10.0                   py37_0    rapidsai
cugraph                   0.10.0                   py37_0    rapidsai
cython                    0.29.13          py37he1b5a44_0    conda-forge
cytoolz                   0.10.0           py37h516909a_0    conda-forge
dask                      2.6.0                      py_0    conda-forge
dask-core                 2.6.0                      py_0    conda-forge
dask-cuda                 0.10.0                   py37_0    rapidsai
dask-cudf                 0.10.0                   py37_0    rapidsai
dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai
distributed               2.6.0                      py_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_1    conda-forge
fastavro                  0.22.5           py37h516909a_0    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.5.2                      py_0    conda-forge
gflags                    2.2.2             he1b5a44_1001    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.0                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcudf                   0.10.0               cuda10.0_0    rapidsai
libcugraph                0.10.0               cuda10.0_0    rapidsai
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnvstrings              0.10.0               cuda10.0_0    rapidsai
libopenblas               0.3.7                h6e990d7_2    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.10.0               cuda10.0_0    rapidsai
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.0.10            h57b8799_1003    conda-forge
libxgboost                1.0.0.SNAPSHOT       cuda10.0_1    rapidsai
llvmlite                  0.29.0           py37hfd453ef_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nccl                      2.4.6.1              cuda10.0_0    nvidia
ncurses                   6.1               hf484d3e_1002    conda-forge
numba                     0.45.1           py37hb3f55d8_0    conda-forge
numpy                     1.17.2           py37h95a1406_0    conda-forge
nvstrings                 0.10.0                   py37_0    rapidsai
olefile                   0.46                       py_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.0.0                      py_0    conda-forge
pillow                    6.2.1            py37h6b7be26_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
psutil                    5.6.3            py37h516909a_0    conda-forge
py-xgboost                1.0.0.SNAPSHOT   cuda10.0py37_1    rapidsai
pyarrow                   0.14.1           py37h8b68381_2    conda-forge
pynvml                    8.0.3                      py_0    conda-forge
pyparsing                 2.4.2                      py_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.1.2            py37h516909a_0    conda-forge
re2                       2019.09.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
rmm                       0.10.0                   py37_0    rapidsai
scikit-learn              0.21.3           py37hcdab131_0    conda-forge
scipy                     1.3.1            py37h921218d_2    conda-forge
setuptools                41.4.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snappy                    1.1.7             he1b5a44_1002    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_0    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xgboost                   1.0.0.SNAPSHOT   cuda10.0py37_1    rapidsai
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zict                      1.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge
</pre>
</details>

**Additional context**

One visible difference between the slow and fast environments is the Numpy version. Maybe that is the root cause?

**Comment by ayushdg** [comment]
Edit: Updating the Numpy version in the rapids docker packages seemed to improve the performance. 1.16.4 vs 1.17.2. Though I'm unsure how Numpy dependency impacts performance. (Maybe some copy to host step that uses numpy?)

**Comment by kkraus14** [comment]
@ayushdg Numpy 1.17 introduced an optimization for copying large chunks of memory from host to device and I believe we use Numpy to manage buffers coming from PyArrow.

**Comment by ayushdg** [comment]
Awesome! Thanks @kkraus14. Would it be worthwhile to bump the minimum Numpy dependency or do you think its a better idea to figure out why the docker environments don't pick up the latest Numpy updates

**Comment by mike-wendt** [comment]
> Awesome! Thanks @kkraus14. Would it be worthwhile to bump the minimum Numpy dependency or do you think its a better idea to figure out why the docker environments don't pick up the latest Numpy versions

The docker containers are locked to 1.16.4 for notebook issues, and the fact that cuml blessed 1.16.4 for the release not 1.17

**Comment by ayushdg** [comment]
Thanks @mike-wendt. I'll close this issue out since cudf doesn't seem to be the relevant repo for this issue anymore. We can slowly start transitioning notebooks to be more 1.17 compliant so that future releases/nightlies can use the updated Numpy
