### ISSUE TITLE
[FEA] Move error_utils.hpp to public include directory

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3190]
**Is your feature request related to a problem? Please describe.**
https://github.com/rapidsai/cudf/pull/3171 moves the old error utilities to `src/utilities/legacy`.

The remaining contents of `error_utilities.hpp` should be moved to `cpp/include/cudf/utilities/error.hpp`.

**Comment by harrism** [comment]
@trevorsm7 only PRs go in the PR columns of the project tables, not issues. This is an issue.
