### ISSUE TITLE
[FEA] Port stack and tile to cudf::column types

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#3196]
**Is your feature request related to a problem? Please describe.**
Now that #2207 is merged we need to start porting functionality to use it. This issue covers tile and stack implemented in #2956. 

Update these API function definitions and their implementations to use the new cudf::column and associated classes.

Note that until string columns and other wrapper types are supported, operations will only be able to be implemented for numerical columns. Initially the "legacy" APIs should be kept in place but moved to the cudf/legacy folder and if necessary a legacy namespace.

**Comment by cwharris** [comment]
@devavret Let me know if you want to keep this one for yourself.

**Comment by harrism** [comment]
I think @devavret will be busy with groupby for a while.
