### ISSUE TITLE
[FEA] Implement `table_wrapper`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3203]
**Is your feature request related to a problem? Please describe.**
https://github.com/rapidsai/cudf/pull/3130 added the `column_wrapper` classes for more convenient construction of `cudf::column`s for writing tests. 

However, it is still a bit inconvenient to create a `table`. Making a `table` from a set of `column_wrapper`s would look something like this:
```
fixed_width_column_wrapper<int8_t> col0(b,e);
fixed_width_column_wrapper<int16_t> col1(b1,e1);
fixed_width_column_wrapper<int8_t> col2(b2,e2,v);
fixed_width_column_wrapper<float> col3(b3,e3);
strings_column_wrapper strings{"hello", "world"};
table t{col0,col1,col2,col3,strings};
```

**Describe the solution you'd like**
It would be nice to be able to instead just do something like this:
```
table_wrapper<int8_t, int16_t, int8_t, float, string> t{b, e, v, b2, b3, b4, v, b5};
```

A rough idea of the implementation would be something like this:
```
template <typename... Ts>
class table_wrapper{
   template <typename Input1, typename ValidityIterator, typename... Iterators>
   table_wrapper(Input1 begin, Input1 end, ValidityIterator v, Iterators... begins){
   }
   private:
   std::unique_ptr<table> wrapped;
};
```

Where the first column is constructed from the iterators `[begin,end)` and the (optional) validity iterator `v`, and then the remaining columns are constructed from the remaining iterators in `begins`.

The really tricky part of this is that we'd like to be able construct a set of columns where each column has the option of being nullable or not. E.g., with the pseudo-code example above:
```
// size = distance(b0,e0);
// column 0 is nullable [b0,e0) and v
// column 1 is non-nullable [b1, b1 + size)
// column 2 is non-nullable [b2, b2 + size)
// column 3 is nullable [b3, b3 + size) and v3
table_wrapper<int8_t, int16_t, int8_t, float> t{b0, e0, v, b1, b2, b3, v3};
```
This is tricky as-is because the parameter pack of iterators in `begins` would contain a set of iterators where some of the iterators and the beginning of element ranges, some of them are beginning of validity ranges and there's no easy way to differentiate between them.

I suspect what we'll need to do is make the parameter pack in `begins` to be a "zip" like a tuple or pair or something such that it would look like this:
```
table_wrapper<int8_t, int16_t, int8_t, float> t{b0, e0, v, {b1}, {b2}, {b3, v3}};
```
That way we can differentiate what the various iterators are.

**Comment by harrism** [comment]
@jrhemstad do you think we are suffering without this, or are we doing fine? :)

**Comment by jrhemstad** [comment]
> @jrhemstad do you think we are suffering without this, or are we doing fine? :)

Personally, I haven't experienced any suffering because it's been a while since I've written any tests. If people are happy without a `table_wrapper` then I have no problem closing the issue.

**Comment by vyasr** [comment]
Given that nobody has felt the need to push on this for over two years, I'm going to close this as not a true cause of suffering :)
