### ISSUE TITLE
[FEA] Compressing/decompressing `__cuda_array_interface__` objects

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#3230]
**Is your feature request related to a problem? Please describe.**

It would be useful to feed the compression algorithms that cuIO supplies with any `__cuda_array_interface__` object. This would allow users to supply any GPU array object and have it be compressed. This can be useful in a number of applications like storage, fast network transfers, and efficient memory usage.

**Describe the solution you'd like**

In Python many of the compression algorithms are exposed so that users can call `compress` and `decompress` with anything that supports the Python Buffer Protocol. It would be useful to have a similar interface to the cuIO compression algorithms that use `__cuda_array_interface__` instead.

**Describe alternatives you've considered**

Not aware of any, but please feel free to propose if you have ideas.

**Additional context**

This could be a useful combination with GPUDirect Storage. Namely users could compress data on the GPU and write it out or read in compressed data from disk and decompress it.

**Comment by jrhemstad** [comment]
CC @nsakharnykh who is working on a generic compress/decompress C++ APIs for libcudf and/or nvcomp.

**Comment by nsakharnykh** [comment]
What does ‘__cuda_array_interface__’ map to in the C++ backend? Is it a pointer + size, or something more sophisticated?

**Comment by jakirkham** [comment]
Sure, here's [the spec]( http://numba.pydata.org/numba-doc/latest/cuda/cuda_array_interface.html ). So pointer and some metadata like shape, type, strides, etc. Though it could make sense to reject anything but the simplest cases (like 1-D, C-contiguous array) initially.

**Comment by jakirkham** [comment]
FWIW we should be able to coerce everything into a 1-D C-contiguous `uint8` array (see code below). This for the most part uses a view unless the array data is not C or Fortran contiguous.

```python
import cupy as cp

def asgpubyteslike(data):
    return cp.asarray(data).ravel("A").view("u1")
```

Then a compression function could look like this.

```cython
def compress(data):
    data1d = cp.asarray(data).ravel("A").view("u1")

    cdef void* data1d_ptr = data1d.__cuda_array_interface__["data"][0]
    cdef size_t data_len = data.__cuda_array_interface__["shape"][0]

    ...
```

**Comment by nsakharnykh** [comment]
Thanks @jakirkham. Contiguous arrays can be easily supported by the API that I'm designing. I'll share more details once we stabilize the interface for the compression library, but I'll definitely keep your use case in mind.

**Comment by jakirkham** [comment]
cc @OlivierNV (who may be interested in this)

**Comment by OlivierNV** [comment]
Keep in mind that this would almost certainly have to imply a custom gpu-specific compression codec (data would have to be chunked in fixed size chunks for standard compressors to be efficient on gpu, though the chunking is independent from the compression codec),

**Comment by vyasr** [comment]
@jakirkham would it be sufficient to simply convert said object to a `cudf.Series` (which supports the 0-copy `__cuda_array_interface__`) and then run the compression on that? The resulting `Series` also supports the `__cuda_array_interface__`, so converting back to the original type would again be 0-copy. While the C++ code may support arbitrary contiguous buffers, exposing that generically in Python would involve exposing a lower-level (non-pandas-like) Python API, which is probably out of scope at present (unless I'm misunderstanding the request).

**Comment by vyasr** [comment]
IMO cudf is no longer the correct home for this, [kvikio](https://github.com/rapidsai/kvikio/) is (especially since it has some Python bindings for nvcomp). @jakirkham would you agree?

I'll plan to transfer this issue in the next couple of days unless I hear any objections.

**Comment by jakirkham** [comment]
The original goal of compress objects that support `__cuda_array_interface__` is already completed in KvikIO via pynvcomp. So if that is the only goal at this point, would close

The use cases enumerated above would be solved in different places:
1. Faster network transmission: UCXX
2. Faster storage IO: KvikIO
3. Compact memory usage: cuDF spilling

Think tackling those would be best discussed in new issues focused on those use cases instead of this one

So would propose we close this out

**Comment by vyasr** [comment]
Sounds right to me, thanks John!
