### ISSUE TITLE
[FEA] Specialize hash functions for floating point

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3233]
**Is your feature request related to a problem? Please describe.**

For the existing libcudf hash functions, `hash(-0.0f) != hash(0.0f)` and `hash(NaN) != hash(NaN)` for all NaNs.

**Describe the solution you'd like**

[libcudf hash functions](https://github.com/rapidsai/cudf/blob/branch-0.8/cpp/src/hash/hash_functions.cuh#L33) should be specialized for floating points such that `hash(-0.0f) == hash(0.0f)` and `hash(NaN) == hash(NaN)` for all NaNs.

Note, this is how [libstd++ specializes for `std::hash<float>` ](https://github.com/gcc-mirror/gcc/blob/41d6b10e96a1de98e90a7c0378437c3255814b16/libstdc%2B%2B-v3/include/bits/functional_hash.h#L226)to ensure `hash(-0.0f) == hash(0.0f)`. We can do something similar to also include NaNs using [`isnan`](https://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html).

**Comment by harrism** [comment]
@trevorsm7 can you take this since you most recently worked on the hashing code? It's P0 for spark in 0.12.

**Comment by trevorsm7** [comment]
Sure, will do
