### ISSUE TITLE
[FEA] Support date_range

### ISSUE THREAD

**Issue by xiaonans** [rapidsai/cudf#3234]
**Is your feature request related to a problem? Please describe.**
I wish I could use cuDF to do date operation like pandas.date_range (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.date_range.html) and pandas.tseries.offsets.DateOffset (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.tseries.offsets.DateOffset.html).

**Comment by beckernick** [comment]
DateOffset has been implemented. Updating this issue to request date_range.

```python
import cudf
import pandas as pd
​
d = cudf.from_pandas(pd.date_range(start="1/1/2021", periods=2))
print(d)
print(d + cudf.DateOffset(years=1))
DatetimeIndex(['2021-01-01', '2021-01-02'], dtype='datetime64[ns]')
DatetimeIndex(['2022-01-01', '2022-01-02'], dtype='datetime64[ns]')
```
