### ISSUE TITLE
[FEA] Character Level Parsing/Tokenization for smaller string batches

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3240]
#### [FEA] Character Level Parsing/Tokenization for smaller string batches

 We wish to use `nvstrings`  to perform `bert-tokenization`, we wish to the following tasks:
* `Lower Case`
* `Tokenize`  // spaces tokenization
* `Replace` / `Translate`:

Currently when we replace we can have a case where we replace a single character with multiple characters so translate cant be used. If we extend translate to this use case that can also be a work around. 

####  Problem at hand:
* For this use case the number of strings is less and number of characters to replace with (15,000) is a lot so the performance is less that ideal. 

#### Solution required: 

We would ideally like a way for `nvstrings` to provide parallelism at character level such that we can get the best performance possible. 

**Additional context**

The repo for experimentation with this is shared in our internal strings channel. 

The performance comparison is as follows:
```python
### Batch size 1
custom cuda imp. 0.056919 ms
custrings time 188.923931 ms

###  Batch size  4
custom cuda imp. 0.073376 ms.
custrings time 266.158020 ms.

##  Batch size  8
custom cuda imp. 0.093352 ms
custrings time 365.152490 ms

###  Batch size  16
custom cuda imp. 0.127261 ms
custrings time 304.191357 ms

###  Batch size  64
custom cuda imp. 0.272587 ms
custrings time 414.762339 ms

###   Batch size  128
custom cuda imp. 0.768313 ms
custrings time 385.038867 ms

###   Batch size  256
custom cuda imp.1.379156 ms
custrings time 462.306200 ms
```

CC: @davidwendt 
CC: @randerzander

**Comment by kkraus14** [comment]
Closing as the bert tokenizer is now open source in https://github.com/rapidsai/clx.
