### ISSUE TITLE
[BUG] Get "RMM initialization error" using cpp binding "cudf:read_csv"

### ISSUE THREAD

**Issue by da0412** [rapidsai/cudf#3244]
**Describe the bug**
Got "rmm initialization error" when using cpp binding "cudf:read_csv" on version 0.10.
The message is:
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::allocate(): RMM_ALLOC: cudaErrorInitializationError: initialization error

The test cods is:

    {
        const std::string fname	= "data.csv";
        // types are  { "int", "float64", "int" };
        std::ofstream outfile(fname, std::ofstream::out);
        outfile << " 20, 1, 100\n"\
               "-21, 2, 101\n"\
               " 22, 3, 102\n"\
               "-23, 4, 103\n";
        outfile.close();

        cudf::csv_read_arg args(cudf::source_info{fname});
        args.names = { "A", "B", "C" };
        args.header = -1;
        args.use_cols_names = { "A", "C" };
        const auto df = cudf::read_csv(args);
    }

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

data frame return

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.10 python=3.6 cudatoolkit=10.1

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
    
     **git***
     commit 511b75c7c926c1c6cf427e442aa532f2bc9d825a (HEAD, origin/branch-0.9, origin/HEAD, branch-0.9)
     Merge: a9cbeb1 fd09572
     Author: Keith Kraus <kkraus@nvidia.com>
     Date:   Sun Aug 4 09:46:13 2019 -0800
     
     Merge pull request #2368 from rjzamora/cudf-engine
     
     [Review] Updating dask_cudf.read_parquet() to leverage new Dask API
     **git submodules***
     -b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub
     -97e046f4f4883dc5612dd14bc063e53dd623a6cf thirdparty/jitify
     
     ***OS Information***
     CentOS Linux release 7.6.1810 (Core)
     NAME="CentOS Linux"
     VERSION="7 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="7"
     PRETTY_NAME="CentOS Linux 7 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:7"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"
     
     CENTOS_MANTISBT_PROJECT="CentOS-7"
     CENTOS_MANTISBT_PROJECT_VERSION="7"
     REDHAT_SUPPORT_PRODUCT="centos"
     REDHAT_SUPPORT_PRODUCT_VERSION="7"
     
     CentOS Linux release 7.6.1810 (Core)
     CentOS Linux release 7.6.1810 (Core)
     
     ***GPU Information***
     Wed Oct 30 14:12:14 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla P40           Off  | 00000000:04:00.0 Off |                  Off |
     | N/A   22C    P8    13W / 250W |     10MiB / 24451MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                56
     On-line CPU(s) list:   0-55
     Thread(s) per core:    2
     Core(s) per socket:    14
     Socket(s):             2
     NUMA node(s):          2
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 79
     Model name:            Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
     Stepping:              1
     CPU MHz:               1200.500
     CPU max MHz:           3500.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              5200.47
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              35840K
     NUMA node0 CPU(s):     0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54
     NUMA node1 CPU(s):     1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts spec_ctrl intel_stibp
     
     ***CMake***
     /bin/cmake
     cmake version 2.8.12.2
     
     ***g++***
     /bin/g++
     g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-10.1/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Apr_24_19:10:27_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.168
     
     ***Python***
     /home/test/users/anaconda3/bin/python
     Python 3.6.7
     
     ***Environment Variables***
     PATH                            : /usr/local/cuda-10.1/bin:/home/test/users/anaconda3/bin:/usr/local/cuda-10.1/bin:/sbin:/bin:/usr/sbin:/usr/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.1/lib64:/usr/local/cuda-10.1/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/test/users/anaconda3/bin/conda
     # packages in environment at /home/test/users/anaconda3:
     #
     # Name                    Version                   Build  Channel
     _ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0
     _libgcc_mutex             0.1                        main
     alabaster                 0.7.10           py36h306e16b_0
     anaconda                  5.0.1            py36hd30a520_1
     anaconda-client           1.6.5            py36h19c0dcd_0
     anaconda-navigator        1.6.9            py36h11ddaaa_0
     anaconda-project          0.8.0            py36h29abdf5_0
     arrow-cpp                 0.14.1           py36hb2cae1d_3    conda-forge
     asn1crypto                0.22.0           py36h265ca7c_1
     astroid                   1.5.3            py36hbdb9df2_0
     astropy                   2.0.2            py36ha51211e_4
     babel                     2.5.0            py36h7d14adf_0
     backports                 1.0              py36hfa02d7e_1
     backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2
     beautifulsoup4            4.6.0            py36h49b8c8c_1
     bitarray                  0.8.1            py36h5834eb8_0
     bkcharts                  0.2              py36h735825a_0
     blas                      1.0                         mkl
     blaze                     0.11.3           py36h4e06776_0
     bleach                    2.0.0            py36h688b259_0
     bokeh                     0.12.10          py36hbb0e44a_0
     boost-cpp                 1.70.0               ha2d47e9_0    conda-forge
     boto                      2.48.0           py36h6e4cd66_1
     bottleneck                1.2.1            py36haac1ea0_0
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.6                h0376d23_1
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2017.08.26           h1d4fec5_0
     cairo                     1.14.10              haa5651f_5
     certifi                   2017.7.27.1      py36h8b7b77e_0
     cffi                      1.10.0           py36had8d393_1
     chardet                   3.0.4            py36h0f667ec_1
     click                     6.7              py36h5253387_0
     cloudpickle               0.4.0            py36h30f8c20_0
     clyent                    1.2.2            py36h7e57e65_1
     colorama                  0.3.9            py36h489cec4_0
     conda                     4.7.12                   py36_0    conda-forge
     conda-build               3.0.27           py36h940a66d_0
     conda-env                 2.6.0                         1    conda-forge
     conda-package-handling    1.6.0            py36h516909a_0    conda-forge
     conda-verify              2.0.0            py36h98955d8_0
     contextlib2               0.5.5            py36h6c84a62_0
     cryptography              2.7              py36h72c5cf5_0    conda-forge
     cudatoolkit               10.1.168                      0    nvidia
     cudf                      0.10.0                   py36_0    rapidsai
     curl                      7.55.1               hcb0b314_2
     cycler                    0.10.0           py36h93f1223_0
     cython                    0.29.13          py36he1b5a44_0    conda-forge
     cytoolz                   0.8.2            py36h708bfd4_0
     dask                      0.15.3           py36hdc2c8aa_0
     dask-core                 0.15.3           py36h10e6167_0
     datashape                 0.5.4            py36h3ad6b5c_0
     dbus                      1.10.22              h3b5a359_0
     decorator                 4.1.2            py36hd076ac8_0
     distributed               1.19.1           py36h25f3894_0
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.14             py36hb0f60f5_0
     double-conversion         3.1.5                he1b5a44_1    conda-forge
     entrypoints               0.2.3            py36h1aec115_2
     et_xmlfile                1.0.1            py36hd6bccc3_0
     expat                     2.2.4                hc00ebd1_1
     fastavro                  0.22.5           py36h516909a_0    conda-forge
     fastcache                 1.0.2            py36h5b0c431_0
     filelock                  2.0.12           py36hacfa1f5_0
     flask                     0.12.2           py36hb24657c_0
     flask-cors                3.0.3            py36h2d857d3_0
     fontconfig                2.12.4               h88586e7_1
     freetype                  2.8                  h52ed37b_0
     fsspec                    0.5.2                      py_0    conda-forge
     get_terminal_size         1.0.0                haa9412d_0
     gevent                    1.2.2            py36h2fe25dc_0
     gflags                    2.2.2             he1b5a44_1001    conda-forge
     glib                      2.53.6               hc861d11_1
     glob2                     0.5              py36h2c1b292_1
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2                hb3b607b_0
     gmpy2                     2.0.8            py36h55090d7_1
     graphite2                 1.3.10               hc526e54_0
     greenlet                  0.4.12           py36h2d503a6_0
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     gst-plugins-base          1.12.2               he3457e5_0
     gstreamer                 1.12.2               h4f93127_0
     h5py                      2.7.0            py36he81ebca_1
     harfbuzz                  1.5.0                h2545bd6_0
     hdf5                      1.10.1               hb0523eb_0
     heapdict                  1.0.0            py36h79797d7_0
     html5lib                  0.999999999      py36h2cfc398_0
     icu                       58.2                 h211956c_0
     idna                      2.6              py36h82fb2a8_1
     imageio                   2.2.0            py36he555465_0
     imagesize                 0.7.1            py36h52d8127_0
     intel-openmp              2018.0.0             h15fc484_7
     ipykernel                 4.6.1            py36hbf841aa_0
     ipython                   6.1.0            py36hc72a948_1
     ipython_genutils          0.2.0            py36hb52b0d5_0
     ipywidgets                7.0.0            py36h7b55c3a_0
     isort                     4.2.15           py36had401c0_0
     itsdangerous              0.24             py36h93cc618_1
     jbig                      2.1                  hdba287a_0
     jdcal                     1.3              py36h4c697fb_0
     jedi                      0.10.2           py36h552def0_0
     jinja2                    2.9.6            py36h489bce4_1
     jpeg                      9b                   habf39ab_1
     jsonschema                2.6.0            py36h006f8b5_0
     jupyter                   1.0.0            py36h9896ce5_0
     jupyter_client            5.1.0            py36h614e9ea_0
     jupyter_console           5.2.0            py36he59e554_1
     jupyter_core              4.3.0            py36h357a921_0
     jupyterlab                0.27.0           py36h86377d0_2
     jupyterlab_launcher       0.4.0            py36h4d8058d_0
     lazy-object-proxy         1.3.1            py36h10fcdad_0
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.10.0               cuda10.1_0    rapidsai
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1                h4deb6c0_3
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.2.0                h9f7466a_2
     liblapack                 3.8.0               14_openblas    conda-forge
     libnvstrings              0.10.0               cuda10.1_0    rapidsai
     libopenblas               0.3.7                h6e990d7_2    conda-forge
     libpng                    1.6.32               hda9c8bc_2
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.10.0               cuda10.1_0    rapidsai
     libsodium                 1.0.13               h31c71d8_2
     libssh2                   1.8.0                h8c220ad_2
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.0.8                h90200ff_9
     libtool                   2.4.6                hd50d1a6_0
     libxcb                    1.12                 h84ff03f_3
     libxml2                   2.9.4                h6b072ca_5
     libxslt                   1.1.29               hcf9102b_5
     llvmlite                  0.30.0           py36hf484d3e_0    numba
     locket                    0.2.0            py36h787c0ad_1
     lxml                      4.1.0            py36h5b66e50_0
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     lzo                       2.10                 h1bfc0ba_1
     markupsafe                1.0              py36hd9260cd_1
     matplotlib                2.1.0            py36hba5de38_0
     mccabe                    0.6.1            py36h5ad9710_1
     mistune                   0.7.4            py36hbab8784_0
     mkl                       2018.0.0             hb491cac_4
     mkl-service               1.1.2            py36h17a0993_4
     mpc                       1.0.3                hf803216_4
     mpfr                      3.1.5                h12ff648_1
     mpmath                    0.19             py36h8cc018b_2
     msgpack-python            0.4.8            py36hec4c5d1_0
     multipledispatch          0.4.9            py36h41da3fb_0
     navigator-updater         0.1.0            py36h14770f7_0
     nbconvert                 5.3.1            py36hb41ffb7_0
     nbformat                  4.4.0            py36h31c9010_0
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.0              py36h7e96fb8_0
     nltk                      3.2.4            py36h1a0979f_0
     nose                      1.3.7            py36hcdf7029_2
     notebook                  5.0.0            py36h0b20546_2
     numba                     0.46.0          np116py36hf484d3e_0    numba
     numexpr                   2.6.2            py36hdd3393f_1
     numpy                     1.16.4           py36h95a1406_0    conda-forge
     numpydoc                  0.7.0            py36h18f165f_0
     nvstrings                 0.10.0                   py36_0    rapidsai
     odo                       0.5.1            py36h90ed295_0
     olefile                   0.44             py36h79f9f78_0
     openpyxl                  2.4.8            py36h41dd2a8_1
     openssl                   1.1.1c               h516909a_0    conda-forge
     packaging                 16.8             py36ha668100_1
     pandas                    0.24.2           py36hb3f55d8_0    conda-forge
     pandoc                    1.19.2.1             hea2e7c5_1
     pandocfilters             1.4.2            py36ha6701b7_1
     pango                     1.40.11              h8191d47_0
     parquet-cpp               1.5.1                         2    conda-forge
     partd                     0.3.8            py36h36fd896_0
     patchelf                  0.9                  hf79760b_2
     path.py                   10.3.1           py36he0c6f6d_0
     pathlib2                  2.3.0            py36h49efa8e_0
     patsy                     0.4.1            py36ha3be15e_0
     pcre                      8.41                 hc71a17e_0
     pep8                      1.7.0            py36h26ade29_0
     pexpect                   4.2.1            py36h3b9d41b_0
     pickleshare               0.7.4            py36h63277f8_0
     pillow                    4.2.1            py36h9119f52_0
     pip                       9.0.1            py36h8ec8b28_3
     pixman                    0.34.0               h83dc358_2
     pkginfo                   1.4.1            py36h215d178_1
     ply                       3.10             py36hed35086_0
     prompt_toolkit            1.0.15           py36h17d85b1_0
     psutil                    5.4.0            py36h84c53db_0
     ptyprocess                0.5.2            py36h69acd42_0
     py                        1.4.34           py36h0712aa3_1
     pyarrow                   0.14.1           py36h8b68381_2    conda-forge
     pycodestyle               2.3.1            py36hf609f19_0
     pycosat                   0.6.3           py36h14c3975_1001    conda-forge
     pycparser                 2.18             py36hf9f622e_1
     pycrypto                  2.6.1            py36h6998063_1
     pycurl                    7.43.0           py36h5e72054_3
     pyflakes                  1.6.0            py36h7bd6a15_0
     pygments                  2.2.0            py36h0d3125c_0
     pylint                    1.7.4            py36hb9d4533_0
     pyodbc                    4.0.17           py36h999153c_0
     pyopenssl                 17.2.0           py36h5cc804b_0
     pyparsing                 2.2.0            py36hee85983_1
     pyqt                      5.6.0            py36h0386399_5
     pysocks                   1.6.7            py36hd97a5b1_1
     pytables                  3.4.2            py36h3b5282a_2
     pytest                    3.2.1            py36h11ad3bb_1
     python                    3.6.7             h357f687_1005    conda-forge
     python-dateutil           2.6.1            py36h88d3b88_1
     pytz                      2017.2           py36hc2ccc2a_1
     pywavelets                0.5.2            py36he602eb0_0
     pyyaml                    3.12             py36hafb9ca4_1
     pyzmq                     16.0.2           py36h3b0cf96_2
     qt                        5.6.2               h974d657_12
     qtawesome                 0.4.4            py36h609ed8c_0
     qtconsole                 4.3.1            py36h8f73b5b_0
     qtpy                      1.3.1            py36h3691cc8_0
     re2                       2019.09.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     requests                  2.18.4           py36he2e5f8d_1
     rmm                       0.10.0                   py36_0    rapidsai
     rope                      0.10.5           py36h1f8c17e_0
     ruamel_yaml               0.11.14          py36ha2fb22d_2
     scikit-image              0.13.0           py36had3c07a_1
     scikit-learn              0.19.1           py36h7aa7ec6_0
     scipy                     0.19.1           py36h9976243_3
     seaborn                   0.8.0            py36h197244f_0
     setuptools                36.5.0           py36he42e2e1_0
     simplegeneric             0.8.1            py36h2cb9092_0
     singledispatch            3.4.0.3          py36h7a266c3_0
     sip                       4.18.1           py36h51ed4ed_2
     six                       1.11.0           py36h372c433_1
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     snowballstemmer           1.2.1            py36h6febd40_0
     sortedcollections         0.5.3            py36h3c761f9_0
     sortedcontainers          1.5.7            py36hdf89491_0
     sphinx                    1.6.3            py36he5f0bdb_0
     sphinxcontrib             1.0              py36h6d0f590_1
     sphinxcontrib-websupport  1.0.1            py36hb5cb234_1
     spyder                    3.2.4            py36hbe6152b_0
     sqlalchemy                1.1.13           py36hfb5efd7_0
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     statsmodels               0.8.0            py36h8533d0b_0
     sympy                     1.1.1            py36hc6d1c1c_0
     tblib                     1.3.2            py36h34cf8b6_0
     terminado                 0.6              py36ha25a19f_0
     testpath                  0.3.1            py36h8cadb63_0
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.9             hed695b0_1003    conda-forge
     toolz                     0.8.2            py36h81f2dff_0
     tornado                   4.5.2            py36h1283b2a_0
     tqdm                      4.36.1                     py_0    conda-forge
     traitlets                 4.3.2            py36h674d592_0
     typing                    3.6.2            py36h7da032a_0
     unicodecsv                0.14.1           py36ha668878_0
     unixodbc                  2.3.4                hc36303a_1
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.22             py36hbe7ace6_0
     wcwidth                   0.1.7            py36hdf4376a_0
     webencodings              0.5.1            py36h800622e_1
     werkzeug                  0.12.2           py36hc703753_0
     wheel                     0.29.0           py36he7f4e38_1
     widgetsnbextension        3.0.2            py36hd01bb71_1
     wrapt                     1.10.11          py36h28b7045_0
     xlrd                      1.1.0            py36h1db9f0c_1
     xlsxwriter                1.0.2            py36h3de1aca_0
     xlwt                      1.3.0            py36h7b00a1f_0
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.1.7                h96e3832_1
     zeromq                    4.2.2                hb0b69da_1
     zict                      0.1.3            py36h3a3bf81_0
     zlib                      1.2.11               hfbfcf68_1
     zstd                      1.4.0                h3b9ef0a_0    conda-forge

**Additional context**

**Comment by jrhemstad** [comment]
A recent change to RMM requires you to initialize it first before it can be used. 

https://github.com/rapidsai/rmm/blob/2b3bd9ad2e132643e71e30b77a62091c842e1d06/include/rmm/rmm_api.h#L90

**Comment by da0412** [comment]
Thank you. I confirmed the normal operation with the following code.
{
    rmmOptions_t options{PoolAllocation, 0, false};
    rmm::Manager::getInstance().initialize(&options);

    const std::string fname	= "data.csv";
    // types are  { "int", "float64", "int" };
    std::ofstream outfile(fname, std::ofstream::out);
    outfile << " 20, 1, 100\n"\
           "-21, 2, 101\n"\
           " 22, 3, 102\n"\
           "-23, 4, 103\n";
    outfile.close();

    cudf::csv_read_arg args(cudf::source_info{fname});
    args.names = { "A", "B", "C" };
    args.header = -1;
    args.use_cols_names = { "A", "C" };
    const auto df = cudf::read_csv(args);

    rmm::Manager::getInstance().finalize();
}
