### ISSUE TITLE
[BUG] Series.replace on string columns replaces substrings

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3246]
Calling `replace` on a string series also replaces substrings (which is inconsistent with pandas), because it's leveraging the underlying nvstrings replace method. nvstrings.replace is doing substring pattern matching, rather than finding the exact string and replacing it. This can result in the following potentially unexpected behavior.

Replace is using `regex=True` by default, so we could enforce the correct behavior as a stopgap by inserting start/end anchors in Python (looks like Java doesn't yet support replace on string columns).

Eventually, we'd want to support this in libcuDF like we do for numeric columns (so adding a libcuDF label).

```python
import pandas as pd
s = pd.Series(['a','ab','c','d'])
print(s)
print(s.replace('a', 'new'))
0     a
1    ab
2     c
3     d
dtype: object
0    new
1     ab
2      c
3      d
dtype: object
```

```python

)
import cudf
s = cudf.Series(['a','ab','c','d'])
print(s)
print(s.replace('a', 'new'))
0     a
1    ab
2     c
3     d
dtype: object
0     new
1    newb
2       c
3       d
dtype: object
```

**Comment by galipremsagar** [comment]
@beckernick This seems to be fixed in recent libcudf implementations on `branch-0.13`
```python
>>> import cudf
>>> s = cudf.Series(['a','ab','c','d'])
>>> print(s)
0     a
1    ab
2     c
3     d
dtype: object
>>> print(s.replace('a', 'new'))
0    new
1     ab
2      c
3      d
dtype: object
>>> print(s.to_pandas().replace('a', 'new'))
0    new
1     ab
2      c
3      d
dtype: object
```
