### ISSUE TITLE
[FEA] Add left and right index iterators for row_operators

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3257]
**Is your feature request related to a problem? Please describe.**
Issue https://github.com/rapidsai/cudf/issues/3207 fixed row_lexicographic_comparator when the left and right are not views into the same table. However, there is still an issue with disambiguation between indices into the left table and indices into the right table. For example, rator with the ordered sequence on the left and the values sequence on the right, but `thrust::upper_bound` uses the operator with the values sequence on the left and the ordered sequence on the right. It is very easy to initialize the comparator with the table views in the wrong order and there is no feedback at compile time if it is wrong.

**Describe the solution you'd like**
Add counting iterators with a strong typedef index type (similar to those in wrapper_types.hpp), such that the comparator operator() can be overloaded to disambiguate between (left_index, right_index) and (right_index, left_index). A same_index type could also be added to support cases where left and right are the same table and there is a single iterator, such as `thrust::sort`. Additionally, it might make sense to rename left/right or lhs/rhs to first/second to make it more clear that first may not always be left.

**Comment by trevorsm7** [comment]
See example here: https://github.com/trevorsm7/cudf/blob/e2f5183b565cb1c74b6a12e226fd01805928c745/cpp/include/cudf/table/row_operators.cuh#L207-L276

**Comment by trevorsm7** [comment]
An alternative approach is the `tagged_element_relational_comparator` from PR https://github.com/rapidsai/cudf/pull/3250

**Comment by harrism** [comment]
@trevorsm7 can you comment on whether this is still a problem and important to fix?

**Comment by trevorsm7** [comment]
I think this is still an issue that should be fixed. It's easy for `row_lexicographic_comparator` to mix up the lhs and rhs indices when the left and right tables are different, because some thrust algorithms use `operator(rhs, lhs)` to check if lhs > rhs instead of lhs < rhs. The strong typedef solution proposed above should only take a few days to implement.

The `row_lexicographic_tagged_comparator` functor was also added to serve a similar purpose for thrust::merge (which has a special requirement that the lhs and rhs indices be the same type, so enum tags had to be used rather than strong typedefs). This currently lives in `merge.cuh`, but it might be a good idea to move this to `row_operators.cuh` so it's grouped with related functions.
