### ISSUE TITLE
[FEA] Modify Python digitize functions to use upper_bound and lower_bound

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3258]
**Is your feature request related to a problem? Please describe.**
`gdf_digitize` is being removed from the C++ API as it duplicates the functionality of `cudf::upper_bound` and `cudf::lower_bound` defined in https://github.com/rapidsai/cudf/pull/3229. There are Python bindings/wrapper around this function that need to be updated.

**Describe the solution you'd like**
The Python wrapper can call `cudf::upper_bound` and `cudf::lower_bound` instead.

**Comment by harrism** [comment]
@kkraus14 should this be covered by the Cython libcudf++ port?

**Comment by kkraus14** [comment]
No, likely will be done in a follow up.

**Comment by rgsl888prabhu** [comment]
@kkraus14 @harrism  #4191 has already incorporated lower_bound and upper_bound in digitize, I think this can be closed.
