### ISSUE TITLE
[BUG] Memory leak on drop_duplicates

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3269]
**Describe the bug**

Statement `df4 = df3.drop_duplicates([col])` leaks memory, which is problematic for large files that are bigger than GPU RAM. In our case, ~30% of the memory is leaking, so capping us < 50GB files.

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

Cannot share underlying data, but overall loop looks like:

1. Compute:
```
def handle_chunk(df, projections, col):
    early_exit = False
    df2 = df[projections]
    stripped = cudf.Series(df[col].str.strip('  	"'))
    replaced = stripped.str.replace('\r','', regex=True)
    df3 = df2.assign(**{col: replaced})
    if early_exit:
        return df3
    df4 = df3.drop_duplicates([col])
    return df4
```

2. Loop:
```
offset = 0
step = 100000
while not done:  
    df = cudf.read_csv(infile, byte_range=[offset,step], names=cols, usecols=cols,
                           dtype=[...])
    df2 = handle_chunk(df, ['some','cols'], 'my_primary_key')
    offset = offset = step
```
    

**Expected behavior**

The value of `early_exit` should not impact termination. This loop should run indefinitely. If an allocation ever fails, gc should free the stale allocations, and ideally, it should happen before then.

Instead, GPU memory steadily increases until explosion. Early existing before the `drop` statement keeps the memory running in a steady state, which is expected.

**Environment overview (please complete the following information)**

Encountered in both of

```
rapidsai/rapidsai-nightly   0.11-cuda10.0-base-ubuntu18.04   ceeab396ef08        14 hours ago        4.02GB
rapidsai/rapidsai           0.10-cuda10.0-base-ubuntu18.04   75ab236316f8        2 weeks ago         3.83GB
```

**Environment details**
Azure nvc6_v2's / ubuntu / nvidia docker

```
Thu Oct 31 21:26:23 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.50       Driver Version: 430.50       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00008110:00:00.0 Off |                  Off |
| N/A   26C    P0    32W / 250W |   4982MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
```

**Additional context**

https://rapids-goai.slack.com/archives/C5E06F4DC/p1572548162002100

**Comment by lmeyerov** [comment]
@kkraus14  Any word here? This one seems like a core critical bug

**Comment by lmeyerov** [comment]
@kkraus14  Hi Keith, checking in again. This is a fairly core primitive and harms use with large datasets .

**Comment by rgsl888prabhu** [comment]
Code to reproduce and test 
```
import cudf
import numpy as np
import pandas as pd
import string
import random
def id_generator(size=3, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))
def handle_chunk(df):
    df2 = df.drop_duplicates(['key']);
    return df2
step = 0
col_size = 5000000
#key =  np.random.randint(col_size, size=col_size)
key  = np.array([id_generator() for i in range(col_size)]);
col =  np.random.randint(col_size, size=col_size)
df = cudf.DataFrame({'key':key, 'col':col});
done = False;
while not done:
    print ("Step : ", step);
    step = step+1
    df2 = handle_chunk(df);
```
