### ISSUE TITLE
[FEA] Utility for converting from bools to null mask 

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#3275]
It would be nice to have a libcudf utility for generating null masks from bools. `column_wrapper` does this already but something in the public API to achieve this would be useful too.

**Comment by jrhemstad** [comment]
This could be a thin wrapper around [`valid_if`](https://github.com/rapidsai/cudf/pull/3263) that looks something like this:
```
std::unique_ptr<rmm::device_buffer> bools_to_mask(column_view const& bools);
```
