### ISSUE TITLE
[FEA] Add support for `ascending` parameter in dask-cudf

### ISSUE THREAD

**Issue by robocopnixon** [rapidsai/cudf#3290]
cuDF now supports support `ascending` in the `dataframe.sort_values()` function, but this does not exist in dask-cudf. 

I would like to have the functionality follow the same API as cuDF. This will be important to certain benchmarks and workflows. 

See also https://github.com/rapidsai/cudf/issues/2255

**Comment by beckernick** [comment]
Duplicate of #2255 . closing.
