### ISSUE TITLE
installation with conda to new env fails

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#330]
Looks like readme file should be update.
Suggested command to create new environment gives following erro
```
conda env create --name cudf --file conda_environments/testing_py35.yml

SpecNotFound: Invalid name, try the format: user/package
```

**Comment by pearu** [comment]
The diagnosis of this issue is wrong: there is a typo in the given command (or perhaps was in some earlier version of `README.md`).

The correct command to create a new environment is
```
conda env create --name cudf --file conda/environments/testing_py35.yml
#                                        ^___ notice the slash `/` instead of underscore `_`
```

Suggest closing the issue.

**Comment by harrism** [comment]
The path did indeed used to be `conda_environments`. Perhaps this is because of `conda env create` instead of `conda create`? 

@kkraus14 can you weigh in on closing this issue?
