### ISSUE TITLE
[FEA] Allow user to specify whether `Decimal` types in ORC and Parquet files are read as `float64` or `int64` types

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3306]
Currently we support reading ORC and Parquet files containing Hive & Spark's `Decimal` type into `float64` types cuDF columns. In some cases, users prefer to read into an `int64` column to avoid precision problems with floating point types.

Until cudf supports a true fixed point `Decimal` type, `read_orc` and `read_parquet` should support an optional param that specifies how `Decimal` types in respective data files are loaded into cudf columns.

**Comment by mjsamoht** [comment]
Assigning @OlivierNV to take a look after #2463 is done

**Comment by OlivierNV** [comment]
@randerzander : I moved the target branch for this to 0.12, since it's too late to make it into 0.11.
Will try to have a PR ready this week for ORC support with a decimal as int64.
Btw, would it make sense to use the native column scale or do we want the ability to specify a global decimal->int64 scale, say 2-digits of fractional precision for all columns ? (or both ?)

**Comment by randerzander** [comment]
When you say native column scale, do you mean read the scale from the ORC file itself? If so, that makes sense to be the default behavior.

However, it also makes sense to support a specified override precision given that ORC files are often produced by upstream systems where arbitrary precision is supported but where the cudf user may want to read just X digits.

**Comment by OlivierNV** [comment]
Yes, I meant the scale from the ORC file itself. In this mode, reading decimals as int64 is essentially identical to reading true DECIMAL64 support (except that the app is responsible for keeping track of the column scale). In the mode where the app overrides the scale, it is a global override for all decimal columns (as you said, presumably to just truncate digits).
On the CPP side, this is done by 2 parameters: a decimals_as_float boolean and an forced_decimals_scale integer, where a negative value means automatic (no forced scale).

**Comment by mjsamoht** [comment]
@randerzander so this is needed for both ORC and Parquet?  Olivier's current PR (which should be ready shortly) only supports ORC.  Would have to add Parquet support as well.

**Comment by randerzander** [comment]
Unless someone else needs this workaround for Parquet files, I think we should wait for #3556 instead.
