### ISSUE TITLE
[FEA] Port device_atomics.hpp to support new libcudf++ types (bool8 and timestamp)

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#3311]
This file is a dependency for porting several modules (groupby/join/rolling/reductions) to libcudf++. We need to update it to work with new libcudf++ wrapper types, specifically bool8 and timestamps.

https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/src/utilities/device_atomics.cuh

**Comment by jrhemstad** [comment]
The implementation could also just use some general cleanup and improvement, which could be tackled as part of this effort.

**Comment by harrism** [comment]
Sure. But time is of the essence.

**Comment by trxcllnt** [comment]
Resolved by https://github.com/rapidsai/cudf/pull/3396
