### ISSUE TITLE
[BUG] Unable to instantiate templated device functions with wrapped types

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#3316]
**Describe the bug**
Instantiating a templated device function compiles but throws an error at runtime `cudaErrorInvalidDeviceFunction`.

**Steps/Code to reproduce bug**
It is most reliably reproducible in typed google tests. Although @karthikeyann has been able to reproduce in simple fixture based tests.

```c++
template <typename T>
__global__ void test_kernel() {}

template <typename T>
struct IssueRepo : public cudf::test::BaseFixture {};

TYPED_TEST_CASE(IssueRepo, cudf::test::Types<cudf::experimental::bool8>);

TYPED_TEST(IssueRepo, Test) {
  test_kernel<TypeParam><<<1, 1>>>();
  CUDA_CHECK_LAST();
}
```
Note that this works: (Always for me, although @karthikeyann would differ)
```c++
TYPED_TEST(IssueRepo, Test) {
  test_kernel<cudf::experimental::bool8><<<1, 1>>>();
  CUDA_CHECK_LAST();
}
```

**Additional context**
Another way it works is when the non-problematic instantiation is done first.
```c++
TYPED_TEST(IssueRepo, Test) {
  test_kernel<cudf::experimental::bool8><<<1, 1>>>();
  CUDA_CHECK_LAST();

  test_kernel<TypeParam><<<1, 1>>>(); // Now this works
  CUDA_CHECK_LAST();
}
```
IIUC, the compiler doesn't consider `test_kernel<cudf::experimental::bool8><<<1, 1>>>()` to be a different instantiation than `test_kernel<TypeParam><<<1, 1>>>()`.

**Comment by harrism** [comment]
@trxcllnt can you take a look?

**Comment by rgsl888prabhu** [comment]
It can be reproduced just with bool and I don't think it is not an issue with `cudf::experimental::bool8`.
The following reproducible shows same issue,
```
template <typename T>
__global__ void test_kernel() {}

template <typename T>
struct IssueRepo : public testing::Test{};

using TestTypes = ::testing::Types<bool>;

TYPED_TEST_CASE(IssueRepo, TestTypes);
TYPED_TEST(IssueRepo, Test) {

  test_kernel<TypeParam><<<1, 1>>>();
  CUDA_CHECK_LAST();
  //auto status = cudaGetLastError ();
  //auto status = cudaDeviceSynchronize();
  //std::cout << cudaGetErrorString(status) << std::endl;
}

```

**Comment by rgsl888prabhu** [comment]
I verified gtest with this kind of test case independently and it still fails.
[sample.txt](https://github.com/rapidsai/cudf/files/3860719/sample.txt)

**Comment by trxcllnt** [comment]
@devavret @harrism It looks like this is happening only for namespaced types. Possible nvcc bug? Here's a standalone repro:
```cuda
// tests/tmp.cu

#include <tests/utilities/base_fixture.hpp>
#include <tests/utilities/type_list_utilities.hpp>

struct foo {};
namespace bar { struct baz {}; };

template <typename T>
__global__ void test_kernel() {}

template <typename T>
struct IssueRepo : public cudf::test::BaseFixture {};

using DummyTypes = cudf::test::Types<foo, bar::baz>;

TYPED_TEST_CASE(IssueRepo, DummyTypes);

TYPED_TEST(IssueRepo, Test) {
  test_kernel<TypeParam><<<1, 1>>>();
  CUDA_CHECK_LAST();
}
```

```txt
[==========] Running 2 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 1 test from IssueRepo/0, where TypeParam = foo
[ RUN      ] IssueRepo/0.Test
[       OK ] IssueRepo/0.Test (152 ms)
[----------] 1 test from IssueRepo/0 (152 ms total)

[----------] 1 test from IssueRepo/1, where TypeParam = bar::baz
[ RUN      ] IssueRepo/1.Test
unknown file: Failure
C++ exception with description "CUDA error encountered at: ../../../tests/tmp.cu:19: 98 cudaErrorInvalidDeviceFunction invalid device function" thrown in the test body.
[  FAILED  ] IssueRepo/1.Test, where TypeParam = bar::baz (0 ms)
[----------] 1 test from IssueRepo/1 (0 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 2 test cases ran. (153 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] IssueRepo/1.Test, where TypeParam = bar::baz

 1 FAILED TEST
```

**Comment by harrism** [comment]
@rgsl888prabhu can you please provide the nvcc line you use to build this? I can't get it to build.

**Comment by rgsl888prabhu** [comment]
Just a makeshift line to get it to work,
`nvcc -I ~/Projects/cuml/cuml/thirdparty/cutlass/tools/external/googletest/googletest/include/ sample.cu ~/Projects/cuml/cpp/build/test/googletest/lib/libgtest.a ~/./Projects/cuml/cpp/build/test/googletest/lib/libgtest_main.a  -o sample`

**Comment by harrism** [comment]
OK, so I think this is documented CUDA behavior rather than a bug. See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#templates

Inside the gtest macros, `TypeParam` is a private typedef, and the docs say "A type or template cannot be used in the type, non-type or template template argument of a __global__ function template instantiation or a __device__/__constant__ variable instantiation if ... The type or template is a class member with private or protected access and its parent class is not defined within a __device__ or __global__ function."

But here's a workaround. Just use `gtest_TypeParam_` instead of `TypeParam` in the test.  Here's a modified version of @rgsl888prabhu 's sample that works:

```
#include <gtest/gtest.h>

template <typename T>
__global__ void test_kernel() {}

template <typename T>
struct IssueRepo : public testing::Test{};

using TestTypes = ::testing::Types<bool>;

TYPED_TEST_CASE(IssueRepo, TestTypes);
TYPED_TEST(IssueRepo, Test) {
  using T = gtest_TypeParam_;
  test_kernel<T><<<1, 1>>>();
  auto status = cudaGetLastError ();
  std::cout << cudaGetErrorString(status) << std::endl;
}
```

This works because TypeParam is just a private typedef of the public template parameter `gtest_TypeParam_`.
