### ISSUE TITLE
[FEA] Coalesce single_lane_block_*_reduce functions

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3324]
**Is your feature request related to a problem? Please describe.**
https://github.com/rapidsai/cudf/pull/3313 added `single_lane_block_popc_reduce`, but this functionality is redundant with `single_lane_block_sum_reduce`. This was done because `gather` dynamically computes the block size while `single_lane_block_sum_reduce` uses a fixed block size as a template parameter. Note that the functionality is not exactly the same: the popc variant additionally calls popc, but this can be done separately before calling block sum reduce as in valid_if, making the sum variant more generic.

**Describe the solution you'd like**
Two possible solutions:
- remove the block_size template parameter from `single_lane_block_sum_reduce` and use blockDim.x instead
- hard-code the `gather` block size to 256 and use `single_lane_block_sum_reduce` as-is

The two solutions should be profiled on V100 to observe how performance is affected.

**Additional context**
@jrhemstad 
>The popc version is unnecessarily specialized to call "popc" in the kernel. The user can just call that before calling the block sum reduce, like I do in valid_if.

**Comment by devavret** [comment]
Solution number 2 seems to be already implemented. https://github.com/rapidsai/cudf/blob/d3ddd851e2dbea8650cb45eaf783ddba870dfa0b/cpp/include/cudf/detail/gather.cuh#L330

I searched but couldn't find a usage of `single_lane_block_popc_reduce`. Should this issue be used to track its removal?

**Comment by harrism** [comment]
Why not!

**Comment by trevorsm7** [comment]
I'll take a look at this today. Hopefully this just got taken care of during `gather` refactoring

**Comment by trevorsm7** [comment]
Looks like @cwharris took care of solution 2 back in PR https://github.com/rapidsai/cudf/pull/3653

We can go ahead and remove `single_lane_block_popc_reduce` and close this issue. @devavret if you'd like to remove it since you were looking into this you can go ahead, otherwise I can take care of it.
