### ISSUE TITLE
[BUG] RMM initialization failing in benchmarks

### ISSUE THREAD

**Issue by dillon-cullinan** [rapidsai/cudf#3327]
**Describe the bug**
```
00:34:54 terminate called after throwing an instance of 'thrust::system::system_error'
00:34:55   what():  rmm_allocator::allocate(): RMM_ALLOC: initialization error
```
@harrism suggested that the benchmarks weren't properly tested after the RMM initialization change. 

Some of them still work.

Working (ran to completion in the job):
`APPLY_BOOLEAN_MASK_BENCH`
`GATHER_BENCH`

Failed:

`JOIN_BENCH`

The rest of the benchmarks are unknown if they work or not.

**Steps/Code to reproduce bug**
1. Build benchmarks for libcudf
2. Run `JOIN_BENCH` executable

**Environment overview (please complete the following information)**
 - Environment location: Bare metal and Docker
 - Method of cuDF install: Source

**Environment details**
Conda environment given in repo

**Comment by harrism** [comment]
It's not RMM initialization failing, it's that some benchmarks are not initializing RMM (because they don't use the right fixture). Fix in the works.
