### ISSUE TITLE
[BUG] Support host-side splitting of compressed CSV files with dask_cudf

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3342]
Original Issue: https://github.com/rapidsai/dask-cudf/issues/211

User reports indicate problems reading heavily compressed CSV files with `dask_cudf`. Typically Dask splits large files into multiple partitions at read time. However, if they are compressed, Dask doesn't support splitting them, leading to OOM scenarios for cudf.

As a workaround, users can use another tool to repartition input files before processing with `dask_cudf`, or they can use Dask's `repartition` method, this (currently) incurs significant networking overhead.

Ideally Dask would support splitting compressed files into more manageable chunks. If not, `dask_cudf` would benefit from a hook which does it.

**Comment by rjzamora** [comment]
Just to clarify - It seems that the goal here is to add a dask_cudf feature that will take in a list of csv files, decompress the file(s) in host memory (resulting in new decompressed files on the file system), and then read the decompressed data into gpu memory.  The end result is a dask_cudf dataframe with the number of partitions being  **larger** than the number of files.

I understand that this feature would be a nice simplification for the user, but I am skeptical that the performance will be better than the "workarounds" you mention.  For example, if someone doesn't want to explicitley split the files with main-line dask beforehand (i.e. using `dask.read_csv` -> `dask.repartition` -> `dask.to_csv`), then I wonder if it is fastest just to perform the IO in host memory and then explicitly move the data in to gpu memory (i.e. `dask.read_csv` -> `dask.repartition` -> `dask_cudf.from_dask_dataframe`).  In other words, I worry that the extra step of writing the decompressed files to disk will make it impractical to repartition the data more than once.

Note that I am still trying to understand exactly what is needed here, and I am probably misunderstanding something :)

**Comment by kkraus14** [comment]
Closing as this was answered.
