### ISSUE TITLE
[QST] Appending Dataframe Rows

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/cudf#3343]
I'm using cuDF v0.10.0 and trying to append two dataframes (adding rows, not joining columns.) In pandas, I might do something like this:

df1 = df = pd.DataFrame({"a":[1, 2, 3, 4], "b":[5, 6, 7, 8]}) 
df2 = pd.DataFrame({"a":[1, 2, 3], "b":[5, 6, 7]}) 
df.append(df2, ignore_index = True) 

I'm trying to find similar functionality with cuDF. I looked on the docs and the "concat" function seems to offer this:
https://rapidsai.github.io/projects/cudf/en/0.10.0/api.html#cudf.core.reshape.concat

However, I cannot find the concat function. Is there a sample invocation to demonstrate this?

**Comment by jpjenk** [comment]
I am also struggling to use concat on rapids data frames.

**Comment by beckernick** [comment]
We expose concat as a module-level function like pandas.

```python
import pandas as pd

df = pd.DataFrame({"a":[1, 2, 3, 4], "b":[5, 6, 7, 8]})
df2 = pd.DataFrame({"a":[1, 2, 3], "b":[5, 6, 7]})
pd.concat([df, df2], ignore_index = True)
```

```python
import cudf

df = cudf.DataFrame({"a":[1, 2, 3, 4], "b":[5, 6, 7, 8]})
df2 = cudf.DataFrame({"a":[1, 2, 3], "b":[5, 6, 7]})
cudf.concat([df, df2], ignore_index = True)
  | a | b
-- | -- | --
1 | 5
2 | 6
3 | 7
4 | 8
1 | 5
2 | 6
3 | 7
```

Please feel free to file a feature request for `.append`, or comment on an `append` issue if one exists!

You both may also be interested in [10 Minutes to cuDF](https://rapidsai.github.io/projects/cudf/en/0.11.0/10min.html#10-Minutes-to-cuDF-and-Dask-cuDF) from our API docs page, which covers some useful functionality like this.

**Comment by beckernick** [comment]
Closing this issue as resolved.
