### ISSUE TITLE
[FEA] Remove concept of a null "string_view"

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3346]
**Is your feature request related to a problem? Please describe.**

Currently, [`cudf::string_view`](https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/include/cudf/strings/string_view.cuh#L86) has a representation for a null element that is separate from the null indicator bitmask. 

This is problematic because it is potentially confusing to users for a few reasons:

1.) Even though it is clearly documented that this is _not_ the case, some users might think that the `column_device_view::element<string_view>(i)` will return a `string_view s` where `s.is_null() == true`. However, this is not the case.

2.) No other element type has a null element representation other than the bitmask (or an appropriate `cudf::scalar` type). We should seek to make the `string_view` element as similar to other types as we can (obviously there will always be unavoidable differences, but I don't think this needs to be one of them). 

**Describe the solution you'd like**

Remove the `string_view::is_null` function and remove the concept of a null `string_view` entirely. Any place that relied on a null `string_view` should be able to be replaced by a `string_scalar`.

**Comment by davidwendt** [comment]
Fixed in #4548
