### ISSUE TITLE
[FEA] Primitive and aggregation operators for time data

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3358]
**Is your feature request related to a problem? Please describe.**

When working with time data, we would like to perform scalar operations, which comes up in tasks such as bucketing and windowing, both for pre/during/post processing. However, tasks such as subtracting and dividing by scalars & same-type time values throw exceptions.

Lowish priority as workaroundable, but annoying in practice.

**Describe the solution you'd like**

1. Binary operators over scalar values should work natively, with an interpretation relative to the base. E.g., `Series<datetime[ms]> + int64 => Series<datetime[ms]>` should time shift by ms. Priority on `+,-,*,/,%`. Questionable on the expectation on units for result of `*,/`: I advocate treating the same as +/- as they're likely part of a same-unit transform.

2. Binary operators over same-type time values should work (`Series<datetime[ms]> - Series<datetime[ms]> => Series<datetime[ms]>`). Priority on `+,-`. 

3. Binary operators over different-type time series values should work with a deterministic coercion ("lhs", "most precise", ...), e.g., `Series<datetime[a]> * Series<datetime[b]> -> Series<datetime[a]>`.

**Describe alternatives you've considered**

We currently do a ton of boilerplate that looks something like:

```
def my_generic_time_f(s):
  s_normalized = s.astype('datetime[ms]').astype('int64')
  out_normalized = my_time_f_ms_int64(s_normalized)
  out = s2_normalized.astype(s.dtype)
  return out
```

**Additional context**

```
import cudf

df = cudf.DataFrame({
    'int': cudf.Series([1000,200,3000]),
    'ms': cudf.Series([1000,200,3000]).astype('datetime64[ms]'),
    'ns': cudf.Series([1000,200,3000]).astype('datetime64[ns]')
})

for colname in df:
    try:
        print('divide', colname, '->', (df[colname] / 1000).tolist())
    except Exception as e:
        print('divide', colname, '!!', str(e))
    try:
        print('shift ', colname, '->', (df[colname] - df[colname]).tolist())
    except Exception as e:
        print('shift ', colname, '!!', str(e))
            
```
=>
```
divide int -> [1.0, 0.2, 3.0]
shift  int -> [0, 0, 0]
divide ms !! cannot broadcast <class 'int'>
shift  ms !! 'DatetimeColumn' object has no attribute 'binary_operator'
divide ns !! cannot broadcast <class 'int'>
shift  ns !! 'DatetimeColumn' object has no attribute 'binary_operator'
```

**Comment by beckernick** [comment]
> Binary operators over scalar values should work natively, with an interpretation relative to the base. E.g., Series<datetime[ms]> + int64 => Series<datetime[ms]> should time shift by ms. Priority on +,-,*,/,%. Questionable on the expectation on units for result of *,/: I advocate treating the same as +/- as they're likely part of a same-unit transform.

I believe this kind of type coercion is no longer possible today in Pandas. Instead, the ask is that the user creates type manually.

```python
pd.Series(["2021-01-03"], dtype="datetime64[ns]") - 1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
...
TypeError: Addition/subtraction of integers and integer-arrays with DatetimeArray is no longer supported.  Instead of adding/subtracting `n`, use `n * obj.freq`
```



> Binary operators over same-type time values should work (Series<datetime[ms]> - Series<datetime[ms]> => Series<datetime[ms]>). Priority on +,-.

This has been implemented for subtraction, returning a timedelta dtype Series (similar to pandas). I'm not sure what the other binary operators would look like here, and I believe they aren't supported in pandas.

> Binary operators over different-type time series values should work with a deterministic coercion ("lhs", "most precise", ...), e.g., Series<datetime[a]> * Series<datetime[b]> -> Series<datetime[a]>.

The broader ask of type coercion to the higher precision has been implemented for the subtraction binary op.

@lmeyerov does the above functionally resolve this issue for you?

**Comment by beckernick** [comment]
@lmeyerov is this still relevant?

**Comment by lmeyerov** [comment]
Hmm not sure, I can check this weekend. We're running 2021.10 I think, doing 11/12 upgrade in a couple weeks, if relevant.

**Comment by vyasr** [comment]
@lmeyerov did you ever get a chance to check on this? Thanks!

**Comment by vyasr** [comment]
I'm going to close this issue as no longer relevant, but feel free to reopen if needed.

**Comment by lmeyerov** [comment]
Sorry this is like 2 years later , hard to revisit that particular code right now

**Comment by vyasr** [comment]
No problem. Based on Nick's comment I'm guessing that the original request is no longer quite relevant, but if you discover otherwise in the future please feel free to reopen. I'm just doing some housekeeping.
