### ISSUE TITLE
[DOC] Add Supported Datatypes documentation

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3360]
## Report needed documentation

**Report needed documentation**
We need documentation on what datatypes we support reading, like `Decimal` types, and which readers support it, like `Parquet` or `CSV`, and what format we convert them to after being ingested.  Some users have reported challenges around the lack of clarity on what to expect

**Steps taken to search for needed documentation**
Searched for different data types in cudf and cuml docs.  Also looked up "datatypes".  There is no section analogous to https://spark.apache.org/docs/latest/sql-reference.html where the user can be certain their datatype will work from the PyData ecosystem formats

**Comment by taureandyernv** [comment]
cc @randerzander

**Comment by drabastomek** [comment]
+10 on this one. Seems like a straightforward thing to add in the docs.

**Comment by beckernick** [comment]
@taureandyernv this is now available at https://docs.rapids.ai/api/cudf/nightly/basics.html , but it looks like it could use an update for the addition of list and struct types. Would you be interested in enhancing it?

**Comment by taureandyernv** [comment]
Awesome.  I'll work with @Nicholas-7 to see about getting that done.

**Comment by vyasr** [comment]
The desired table is now at https://docs.rapids.ai/api/cudf/stable/user_guide/data-types.html.
