### ISSUE TITLE
[BUG]cudf-0.10 parse csv file error

### ISSUE THREAD

**Issue by guoxiangzhou** [rapidsai/cudf#3367]
I use cudf-0.10 to parse the CSV file. 
code ：
auto &&df = cudf::read_csv(args);

but not use：
rmmInitialize();   rmmFinalize();

Occasionally, the following errors are thrown，and it's hard to reproduce：
terminate called after throwing an instance of 'thrust::system::system_error'
what(): parallel_for failed: invalid argument

How to solve it?

**Comment by guoxiangzhou** [comment]
now，I  modify code as follow，not ok：
------------------------
rmmInitialize(nullptr);

auto &&df = cudf::read_csv(args);
.......
df.destroy();

rmmFinalize();
---------------------------

**Comment by guoxiangzhou** [comment]
now，I modify code as follow，not ok：

```
rmmInitialize(nullptr);

auto &&df = cudf::read_csv(args);
.......
df.destroy();

rmmFinalize();
```

**Comment by guoxiangzhou** [comment]
anybody here?

**Comment by guoxiangzhou** [comment]
i mistake，don't use &&df

**Comment by guoxiangzhou** [comment]
The problem remains

**Comment by kkraus14** [comment]
Closing as this is stale. If this is still an issue with the latest 0.14 please open a new issue.
