### ISSUE TITLE
[FEA] Concatenate strings columns

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#3373]
**Is your feature request related to a problem? Please describe.**
We'd like to enable implementing `cudf::concatenate(columns)` with strings columns.

**Describe the solution you'd like**
`std::unique_ptr<cudf::column> concatenate(std::vector<strings_column_view> const& columns)`

This function takes a vector of `strings_column_view`s and concatenates them end-to-end so that their internal representation is contiguous in a single column (the output).

Internally, also, a `detail` namespace version that takes a second parameter, a pre-concatenated validity bitmask for the input columns. This should then be stored as the bitmask of the output column.  This is to enable strings-column concatenation to use existing null-mask concatenation functionality.

**Comment by harrism** [comment]
In fact, do we only need the detail namespace version?

**Comment by jrhemstad** [comment]
> In fact, do we only need the detail namespace version?

Yes, this should only be an internal API. The only public functions for strings should be those unique to strings.

**Comment by jrhemstad** [comment]
> takes a second parameter, a pre-concatenated validity bitmask for the input columns. 

This feels a little clunky to me. I'd opt to just have the strings concatenate return a column with only the data concatenated and an allocated (uninitialized) null mask, with the expectation that a following kernel will fill the null mask. 

That would fit with a pattern like what is seen in gather: https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/include/cudf/detail/gather.cuh#L240

**Comment by harrism** [comment]
Good idea, I like that better.

**Comment by davidwendt** [comment]
Referencing this comment in PR #3356: https://github.com/rapidsai/cudf/pull/3356#discussion_r345437333
This appears to be `concatenate_vertically` or maybe I have it backward.
Also, should it accept a `table_view` here instead of vector of `strings_column_view`?
This was suggested in previous PR somewhat related.
https://github.com/rapidsai/cudf/pull/2991#discussion_r342206609

Perhaps this API should line up with whatever is decided in #3356 :
```
std::unique_ptr<cudf::column> concatenate_vertically(table_view const& table)
```

**Comment by davidwendt** [comment]
Just realized that a `table` requires each of the columns have the same size. So accepting a vector of `strings_column_view` objects may be more useful after all.

**Comment by harrism** [comment]
Table concatenation means concatenate corresponding rows of multiple tables together. Not concatenate multiple rows of the same table together.
