### ISSUE TITLE
[QST] multiple GPUs support in cudf

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#3374]
Are there any plans to support multiple GPUs on a **single machine** within cudf module?
As of now one needs to use dask-cudf, but I would like to know if it is to-be state, or support multiple GPUs on the single machine is on the cudf roadmap.

**Comment by harrism** [comment]
Hi @jangorecki, thanks for your question.

No, this is not currently on the cudf roadmap. As you mention, with Dask and cuDF scaling out to multiple GPUs can be done in the same way as scaling out to multiple nodes. Therefore, we have so far chosen to parallelize in this way to multiple GPUs in a node.

**Comment by jangorecki** [comment]
@harrism Thanks for clarying my initial question. I wanted to setup dask and cudf now but found it difficuilt due to lack of documentation.

- [dask-cudf](https://github.com/rapidsai/dask-cudf) project seems to be archived, is there any up-to-date documentation available on setting up dask and cudf together? Official docs 
at https://rapidsai.github.io/projects/cudf/en/0.11.0/dask-cudf.html still refers to `dask-cudf` package.
Trying 10 mins to dask-cudf instructions at https://rapidsai.github.io/projects/cudf/en/0.11.0/10min.html on recent stable version leads to:
```py
>>> import dask_cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dask_cudf'
```
Attempts to install `dask_cudf`, `dask-cudf` or `daskcudf` fails. cudf has been installed with the command from getting started
```sh
conda install --name cudf -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.11 python=3.6 cudatoolkit=10.0
```

- are there any specific github issues that could allow me to track progress on features that are currently missing in dask-cudf? for example "grouping on multiple columns" which is currently strikeout in documentation. I checked `dask-cudf` labelled issues but don't see any, should I create one for each feature I am interested about?

**Comment by kkraus14** [comment]
@jangorecki `dask-cudf` has been merged into the cudf repo. The relevant source code is here: https://github.com/rapidsai/cudf/tree/branch-0.12/python/dask_cudf.

You should be able to install `dask-cudf` from conda via `conda install --name cudf -c rapidsai -c nvidia -c conda-forge -c defaults dask-cudf=0.11`.

If you don't find an issue for a feature that isn't currently working in `dask-cudf` please raise an issue. The biggest gap right now is unit tests as most of the functionality in `dask-cudf` relies on the upstream `dask.dataframe` code and utilizing the fact that `cudf` follows the pandas API so it "just works".

**Comment by jangorecki** [comment]
Thanks @kkraus14

**Comment by khawar512** [comment]
@jangorecki I tried very hard to convert pandas code into cudf but still facing problem please help me Code link
https://stackoverflow.com/questions/66073491/typeerror-data-must-be-list-or-dict-like-in-cudf/66074951#66074951
