### ISSUE TITLE
[FEA] Add parameter to specify number of row groups per partition for parquets with dask-cudf

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3394]
**Is your feature request related to a problem? Please describe.**

I would like to have a parameter to allow reading n rows groups per partition for parquets.  We can currently read only `1 row  group` per partition with the  `split_row_groups = True` behavior.  1 partition may or may not be more performant so having this flexibility will go a long way. 

**Describe the solution you'd like**

I would like to have the api another parameter `rows_groups_per_part`  parameter which will allow us to control partition sizes as `chunk-size` allows us to do with `csvs` . 

```python
dask_cudf.read_parquet( 'path*', split_row_groups=True, gather_statistics=True, rows_groups_per_part = x) 
```

I would also like for this to work even if we have to read multiple files (compressed / non-compressed) .  

#### Edge Cases to discuss

I think we may also need to cover below in the future but as a initial implementation we can may be assume below wont be problems. 

* How to handle cases where each files (compressed + non compressed)  have different number of row groups 
 
**Additional context**

Relevant issue +discussion about reading single large parquet files at https://github.com/rapidsai/cudf/issues/3142

**Comment by rjzamora** [comment]
It certainly makes sense that you may want your divisions to be larger than the row-group size in some cases.  The feature would most-likely need to go in the upstream-Dask `read_parquet` code (to avoid copying most of the `read_metadata` implementation in dask_cudf).

Side Note:  I don't expect it to be difficult to aggregate multiple row-groups into a single read task.  However,  the `read_parquet` backends (cudf and pyarrow) only allow you to specify a single row group.  In other words, the worker will *probably* be reading each row-group seperately in a loop.

**Comment by VibhuJawa** [comment]
> Side Note: I don't expect it to be difficult to aggregate multiple row-groups into a single read task. However, the `read_parquet` backends (cudf and pyarrow) only allow you to specify a single row group. In other words, the worker will _probably_ be reading each row-group seperately in a loop.

Okay, so its essentially gonna be a `read_parquet_row_group` + `concat` call ?  

If i interpret that correctly , I should expect the overhead associated with that plus this wont give me any `io` benefits as the io is still limited to 1 row group.

**Comment by VibhuJawa** [comment]
> It certainly makes sense that you may want your divisions to be larger than the row-group size in some cases. The feature would most-likely need to go in the upstream-Dask `read_parquet` code (to avoid copying most of the `read_metadata` implementation in dask_cudf).
> 
> Side Note: I don't expect it to be difficult to aggregate multiple row-groups into a single read task. However, the `read_parquet` backends (cudf and pyarrow) only allow you to specify a single row group. In other words, the worker will _probably_ be reading each row-group seperately in a loop.

Also, FWIW,  i think that this is a completely reasonable initial implementation , If io/concat does become a bottle-neck we can revisit it at `cudf` level.

**Comment by rjzamora** [comment]
> If i interpret that correctly , I should expect the overhead associated with that plus this wont give me any io benefits as the io is still limited to 1 row group ?

Right - I'm saying that the io benefit alone *might* not be much,  but there could be other benefits for aggregating row-groups for each partition.

**Comment by VibhuJawa** [comment]
> > If i interpret that correctly , I should expect the overhead associated with that plus this wont give me any io benefits as the io is still limited to 1 row group ?
> 
> Right - I'm saying that the io benefit alone _might_ not be much, but there could be other benefits for aggregating row-groups for each partition.

Yup, completely agree.

**Comment by mrocklin** [comment]
@VibhuJawa can you say more about why you want to collect many row groups into a single partition?  Are you seeing negative performance due to too many partitions, or it is something else?

**Comment by mrocklin** [comment]
@rjzamora from the statistics do we have a decent estimate of the size of each row group?  I wonder if we might identify and possibly handle this situation automatically, or at least warn the user.

**Comment by VibhuJawa** [comment]
> @VibhuJawa can you say more about why you want to collect many row groups into a single partition? Are you seeing negative performance due to too many partitions, or it is something else?

Yup, So in the current use case i have a lot of partitions and it has non trivial performance implications.  

Currently with `read_parquet` I only have 2 options to decide the chunksize either `1 partition/n_row group parts per file`.  This will really help a long way in giving us control for experimenting with finer partition sizes.  

Also, I understand that modifying the input data is an option but i have to use this data across a bunch of workflows so i would really like to have control on a case by case basis and modifying for each case is not an option. 

Also, when trying to tweak workflows based on underlying hardware (16 G cards vs 32 G cards) this will also go a long way. 

CC: @randerzander  @beckernick @ayushdg .

**Comment by mrocklin** [comment]
I'm curious, how large are your row groups?  I would hope that there would
be a large range where things would be best l near optimal.
