### ISSUE TITLE
[BUG] CUDA_ERROR_INVALID_PTX when multiplying Series of float64 on Pascal

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#3410]
**Describe the bug**
Trying to multiply a Series of `float64` on Pascal (P40) throws a CUDA_ERROR_INVALID_PTX.

**Steps/Code to reproduce bug**
```
import cudf

df = cudf.DataFrame({'a': [0.85, 0.233, 0.883], 'b': [992.11, 98.0912, 89.9832]})
df['a'] * 10
```

The `//` operator throws the same error. However, dividing by .1 works fine. 

**Expected behavior**
Proper multiplication values.

**Environment overview (please complete the following information)**
 - Environment location: Azure-ML but running Rapids docker, v.10, Ubuntu 18.04, Cuda 10.1
 - Method of cuDF install: Docker
   
**Environment details**
No access..

**Additional context**

**Comment by drabastomek** [comment]
@johnzed suggested this might be a `float32` thing but tested and the issue is still there on P40.

**Comment by harrism** [comment]
@drabastomek can you try with a more recent cuDF (e.g. 0.13) and reply here if this is still an issue?

**Comment by devavret** [comment]
Tried to reproduce it on a Pascal (P100), worked fine for me.
@drabastomek In case you're using nightlies, try clearing `/tmp/cudf*`

**Comment by drabastomek** [comment]
I tried to reproduce this but no longer have access to P40s to test... I'll
see if I can get something and will circle back. Thank you for looking into
it!

**Comment by harrism** [comment]
Thanks @devavret and @drabastomek. I'm going to close for now, but if you find you can repro on a P40 please reopen!
