### ISSUE TITLE
[BUG] apply_rows throws exception on type-correct empty dataframes

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3418]
**Describe the bug**

When apply_rows runs on a type-correct yet empty dataframes, it throws an exception instead of returning a dataframe.

**Steps/Code to reproduce bug**

```
import cudf
import numpy as np

df1 = cudf.DataFrame({'a': cudf.Series([1], dtype=np.int64), 'b': cudf.Series([2], dtype=np.int64)})
df2 = cudf.DataFrame({'a': cudf.Series([], dtype=np.int64), 'b': cudf.Series([], dtype=np.int64)})

def some_fun(a, b, out):
    for i, (x, y) in enumerate(zip(a, b)):
        out[i] = x + y

## works as expected
df1.apply_rows(some_fun, incols=['a', 'b'], outcols={'out': np.int64}, kwargs={})

## surprise: throws exn
df2.apply_rows(some_fun, incols=['a', 'b'], outcols={'out': np.int64}, kwargs={})

```

**Expected behavior**

As `df2` in above has empty well-typed cols `a: np.int64` and `b: np.int64`, I expected an empty df with `out: np.int64`. Instead, I got exception `ValueError: cannot determine Numba type of <class 'cudf.core.column.numerical.NumericalColumn'>`.

Having to add boilerplate guards everywhere around well-typed code is doable but needlessly annoying :)

**Environment overview (please complete the following information)**

cudf 0.10 / py3.7 / docker

**Comment by lmeyerov** [comment]
Heh been hitting this elsewhere as we're upgrading stuff

**Comment by lmeyerov** [comment]
FYI, hit this again (`0.11`), and took googling and re-landing on this GH issue to realize it was a zero-length cudf bug. So a better error message or just doing the right thing (create empty cols) in `apply_row` / `apply_chunks` would help.

**Comment by rgsl888prabhu** [comment]
This also handled in refactoring and can be closed

**Comment by galipremsagar** [comment]
Closing this as it seems to be fixed, feel free to reopen if it persists. Verified on `branch-0.14`.
