### ISSUE TITLE
[QST] Choose specific GPU to use with cuDF

### ISSUE THREAD

**Issue by bpleao** [rapidsai/cudf#3428]
In a machine with multiple GPUs is it possible to select which GPU to use for cuDF? In this case is it possible to start separate processes using different GPUs? Thanks

**Comment by kkraus14** [comment]
@bpleao cuDF will always target GPU 0. You can use the `CUDA_VISIBLE_DEVICES` environment variable to change what GPU cuDF thinks is GPU 0. You can learn more here: https://devblogs.nvidia.com/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/

**Comment by bpleao** [comment]
It works! Thank you!

**Comment by pseudotensor** [comment]
This is a poor way to resolve.  Need to be able to specify in environment where accessing multiple GPUs one GPU at a time.  E.g. for xgboost one can set gpu_id in multi-GPU case, but cudf always would be on 0, so there is inconsistency.

**Comment by kkraus14** [comment]
There's nothing stopping you from using the CUDA APIs in Numba or CuPy to set the device and cuDF will happily use it, but we've historically ran into issues with this approach because of libraries using `cudaSetDevice(0)` to initialize, so we've guided users to use `CUDA_VISIBLE_DEVICES`.

I.E.
```
import cupy
import cudf

cupy.cuda.Device(1).use()
df = cudf.DataFrame({'a': [1, 2, 3]})
```

**Comment by pseudotensor** [comment]
@kkraus14 Thanks for the quick response and resolution!

**Comment by ajalberd** [comment]
I'm getting "Invalid device ordinal" when initiating that way, and setting the CUDA_VISIBLE_DEVICES. 

Is there a better way, now?

**Comment by Yikai-coder** [comment]
Thanks for you guys' help. 

But in my case when I use Jupyter notebook, setting `cupy.cuda.Device(1).use()` didn't work for me, and cuDF would still use all devices. The correct way to set device for me is `os.environ["CUDA_VISIBLE_DEVICES"]="0"`. Hope that can help those who are facing the same problem.😊

**Comment by will-hill** [comment]
Can we add programmatic device selection instead of environment variables?
