### ISSUE TITLE
[FEA] Scalar/column implementation of copy_if_else

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#3446]
We'd like to implement versions of copy_if_else that allow arbitary combinations of scalars and columns as inputs.  Conceptually, exposure in copying.hpp would look like:

```
// what already exists
copy_if_else(column_view lhs, column_view rhs, column_view boolean_mask);
// what we'd like to add
copy_if_else(scalar lhs, column_view rhs, column_view boolean_mask);
copy_if_else(column_view lhs, scalar rhs, column_view boolean_mask);
// in this case, size of the output column would be the size of the boolean_mask
copy_if_else(scalar lhs, scalar rhs, column_view boolean_mask);
```
The interfaces of column_view and scalar are different enough that there doesn't appear to be a way to express all 4 top level interfaces in one generic way.  Ie, 

```
copy_if_else(column_or_scalar lhs, column_or_scalar rhs);
```

Internally, this is mostly just a refactor of the copy_if_else_kernel from
```
void copy_if_else_kernel(column_device_view const lhs, column_device_view const rhs, ...)
```
to
```
void copy_if_else_kernel(LeftIter lhs, RightIter rhs, ...)
```
In all cases, lhs and rhs would be thrust zip_iterators wrapping element value and element validity iterators. Element value iterators would be implemented as:

```
// column_view
thrust::device_ptr<T> value_iter((T*)in.begin<T>());
// scalar
auto lhs_iter = thrust::make_constant_iterator(static_cast<cudf::experimental::scalar_type_t<T>const*>(&in)->value());
```
Element validity iterators would be implemented as either a constant iterator (true) for scalars, or a transform iterator for columns with the lambda
```
return null_mask == nullptr ? true : null_mask[word_index(i)] & (1<<intra_word_index(i));
```

I am intentionally ignoring make_pair_iterator here because that particular iterator requires the has_validity bool as part of it's template.  This would cause a bit of an ugly explosion because of the possibility of mixed has-validity in the two column case, ala:

```
if(output_has_valids){
   if(lhs.nullable() && rhs.nullable()){
      l = make_pair_iterator<true>(lhs.data, lhs.validity);
      r = make_pair_iterator<true>(rhs.data, rhs.validity);
      kernel<output_has_valids = true>(l, r);
   } else if(lhs.nullable() && !rhs.nullable()){
      l = make_pair_iterator<true>(lhs.data, lhs.validity);
      r = make_pair_iterator<false>(rhs.data, nullptr);
      kernel<output_has_valids = true>(l, r);
  }
  etc.
}
```
It's cleaner to have a do-all transform iterator that handles both possibilities for both inputs.

This change would also involve handling string scalars as well.

**Comment by nvdbaranec** [comment]
Actually, now that I think of it:  Jason how important is it to have both scalar/column and column/scalar versions?  Is it a big deal if the spark layer has to live with a specific ordering ahead of time (scalar/column for example) and arrange it's boolean_mask accordingly?

**Comment by harrism** [comment]
@jlowe see above.

>  Is it a big deal if the spark layer has to live with a specific ordering ahead of time (scalar/column for example) and arrange it's boolean_mask accordingly?

You could always provide a bool parameter to invert the mask (default it to false).

**Comment by jlowe** [comment]
>  Is it a big deal if the spark layer has to live with a specific ordering ahead of time (scalar/column for example) and arrange it's boolean_mask accordingly?

It would be less than ideal.  Spark would need to invoke a separate kernel to invert the mask.  

Agree with @harrism that inverting the sense of the mask on-the-fly in the kernel would be better than requiring a separate kernel pass to invert it.  I would also advocate for hiding this boolean parameter in the implementation detail so users still call it naturally, i.e.: copy_if_else(scalar, column, mask) and copy_if_else(column_val, scalar_val, mask) are supported, and they both can call something like detail::copy_if_else(scalar_val, column, mask, is_mask_inverted).

**Comment by harrism** [comment]
Sounds good.

**Comment by jrhemstad** [comment]
@nvdbaranec can you close this if this has been addressed?

**Comment by nvdbaranec** [comment]
Done.
