### ISSUE TITLE
[BUG] String to datetime typecasting loses sub-second granularity

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3450]
As noted in https://github.com/rapidsai/cudf/issues/3375#issuecomment-556312618 , we currently lose granularity when typecasting strings to nanosecond resolution. A bit of triage suggests this is specific to typecasting from strings to datetime, rather than int64 to datetime.

Pandas:
```python
import pandas as pd
s = pd.Series('2016-01-01 00:00:03.333')
s1 = s.astype('datetime64[ns]')
print(s1)
print(s1.iloc[0])
0   2016-01-01 00:00:03.333
dtype: datetime64[ns]
2016-01-01 00:00:03.333000
```

cuDF
```python
import cudf
s = cudf.Series('2016-01-01 00:00:03.333')
s1 = s.astype('datetime64[ns]')
print(s1)
print(s1.iloc[0])
0   2016-01-01 00:00:03
dtype: datetime64[ns]
2016-01-01T00:00:03.000000000
```

We succeed when explicitly using the integer.

```python
val = 1451606403333000000
cudf.Series(val).astype('datetime64[ns]').iloc[0]
numpy.datetime64('2016-01-01T00:00:03.333000000')
```

**Comment by rgsl888prabhu** [comment]
Currently we can cast timestamp to similar in date-time or down cast it, like from `ns -> us or ms`, but up casting is buggy for which a new issue has been created #4784.

Alternate path to upcast is to cast it to same type in datetime and then up casting it.
```
import cudf
s = cudf.Series('2016-01-01 00:00:03.333')
s1 = s.astype('datetime64[ms]')
s1 = s1.astype('datetime64[ns]')
```
