### ISSUE TITLE
[BUG] `set-item` with cudf.series with bool-mask  gives inconsistent results compared to pandas

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3455]
**Describe the bug**
`set-item` with `series` with `bool-mask`  gives inconsistent results compared to `pandas`

**Steps/Code to reproduce bug**

```python
df = cudf.DataFrame({'a':[1,2,3]})
df['a'][[True,False,True]] = cudf.Series([-1,-1])
df['a']

0   -1
1    2
2   -1
Name: a, dtype: int64
```
**Expected behavior**

```python
df = pd.DataFrame({'a':[1,2,3]})
df['a'][[True,False,True]] = pd.Series([-1,-1])
df['a']

0   -1.0
1    2.0
2    NaN
Name: a, dtype: float64
```

**Environment overview (please complete the following information)**
 - Method of cuDF install: [conda]

**Additional context**
This behavior will also be present when setting item with cudf-dataframe.
Relevant PR : #3442

**Comment by kkraus14** [comment]
Fixed by #3442
