### ISSUE TITLE
[BUG] 0 length string columns fail to deserialize

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#3481]
When using an `rmm.DeviceBuffer` (as dask does):

https://github.com/dask/distributed/blob/master/distributed/comm/ucx.py#L50

deserialization fails when the buffer is a string of size 0:

<details>
<summary> Bug Report </summary>

```
distributed.utils - ERROR - 'rmm._lib.device_buffer.DeviceBuffer' object has no attribute 'device_ctypes_pointer'
Traceback (most recent call last):
  File "/datasets/bzaitlen/GitRepos/distributed/distributed/utils.py", line 663, in log_errors
    yield
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/comm/serialize.py", line 38, in deserialize_cudf_dataframe
    cudf_obj = cudf_typ.deserialize(header, frames)
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/dataframe.py", line 274, in deserialize
    columns = column.deserialize_columns(header["columns"], column_frames)
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/column/column.py", line 1553, in deserialize_columns
    colobj = col_typ.deserialize(meta, frames[:col_frame_count])
  File "/datasets/bzaitlen/GitRepos/cudf/python/cudf/cudf/core/column/string.py", line 661, in deserialize
    arrays.append(libcudf.cudf.get_ctype_ptr(frame))
  File "cudf/_lib/cudf.pyx", line 104, in cudf._lib.cudf.get_ctype_ptr
  File "cudf/_lib/cudf.pyx", line 105, in cudf._lib.cudf.get_ctype_ptr
AttributeError: 'rmm._lib.device_buffer.DeviceBuffer' object has no attribute 'device_ctypes_pointer'
```

</details>

Probably all is needed is a check on length in the deserialization scheme:
https://github.com/rapidsai/cudf/blob/d206d35f6e097f4913f8eb659b583414d428eb52/python/cudf/cudf/core/column/string.py#L650-L661

**Comment by quasiben** [comment]
Actually, i think this happens with populated buffers as well.  `rmm.DeviceBuffer` doesn't expose a `device_ctypes_pointer`.  

> *** AttributeError: 'rmm._lib.device_buffer.DeviceBuffer' object has no attribute 'device_ctypes_pointer'

@kkraus14 can we add this to rmm ?

**Comment by jakirkham** [comment]
AIUI cuDF doesn't currently use `DeviceBuffer`, but this should be handled by PR ( https://github.com/rapidsai/cudf/pull/3254 ).

**Comment by jakirkham** [comment]
What if we special cased `__cuda_array_interface__` like is done with `memoryview` here?

**Comment by jakirkham** [comment]
> What if we special cased `__cuda_array_interface__` like is done with `memoryview` here?

FWIW I put together a quick pass of this in PR ( https://github.com/rapidsai/cudf/issues/3481 ).

**Comment by jakirkham** [comment]
Came up with the following in an attempt to create a simpler reproducer.

```python
In [1]: import rmm                                                              

In [2]: import cudf                                                             

In [3]: s = cudf.DataFrame(data=[], columns=["a", "b", "c"], dtype=str)         

In [4]: header, frames = s.serialize()                                          

In [5]: frames2 = [rmm.DeviceBuffer(size=f.nbytes) for f in frames]             

In [6]: s2 = cudf.DataFrame.deserialize(header, frames2) 
```

**Comment by jakirkham** [comment]
Using the reproducer above, it appears PR ( https://github.com/rapidsai/cudf/pull/3563 ) solves this issue (as `s2` is now created as opposed to raising an exception).
