### ISSUE TITLE
[DOC] Changelog include migration guidance for breaking changes

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3482]
## Report incorrect documentation

**Location of incorrect documentation**

* https://docs.rapids.ai/api/cudf/stable/
* https://github.com/rapidsai/cudf/blob/master/CHANGELOG.md

**Describe the problems or issues found in the documentation**

Docs do not include breaking changes, which makes migrations difficult

**Steps taken to verify documentation is incorrect**

Checked above and Slack discussion: https://rapids-goai.slack.com/archives/C5E06F4DC/p1574881014184100

**Suggested fix for documentation**

* Changelog has an explicit callout for breaking changes / migrations, vs. interleaved
* Change guidance should be clear for both detection + resolution, e.g., "replace all calls to X with calls to Y")
* Perform as part of the dev process, not just during final release, so nightly users can watch/participate less painfully, less chance of missing something, and later-adopters have an easy time

**Comment by GregoryKimball** [comment]
We call out "breaking changes" in the release [changelog](https://github.com/rapidsai/cudf/blob/branch-22.08/CHANGELOG.md) much more clearly now.
![Uploading image.png…]()
