### ISSUE TITLE
[BUG] df tuple constructor regression

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3483]
**Describe the bug**

`cudf.DataFrame([('a', [1,2,3])])` works in `0.10` but throws an exn `0.11`

**Steps/Code to reproduce bug**

Run `cudf.DataFrame([('a', [1,2,3])])`

**Environment overview (please complete the following information)**

conda cuda10 py3.7 nightly

**Environment details**

`cudf` nightly (0.11): `0.11.0a+3390.g7f5e054`

**Comment by cwharris** [comment]
The behavior of `cudf.DataFrame([('a', [1,2,3])])` in `0.10` was reported to not match Pandas' behavior (#1705).

The behavior was updated to match Pandas' behavior (#3147).

Pandas' behavior for `pd.DataFrame([('a', [1,2,3])])` nests series inside of cells, which cudf does not yet support.

To get back to the previous behavior, you can use `cudf.DataFrame({ 'a': [1,2,3]})` which should also be consistent with Pandas.

To match the previous behavior you could do this instead:
```
data = [('a', [1,2,3])]
cudf.DataFrame({ key: value for key, value in data })
```

**Comment by lmeyerov** [comment]
Yes, this was a fairly trivial yet breaking signature change to a public API, so I was requested to file the real (meta) issue of https://github.com/rapidsai/cudf/issues/3482
