### ISSUE TITLE
[QST] deepcopy in cudf.drop

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#3493]
**What is your question?**

In UCX performance profiling, we noticed that there was a [deepcopy happening in `cudf.drop`]( https://github.com/rapidsai/cudf/blob/c021a74ca84a6157ea2b6b920ee9692676809ebc/python/cudf/cudf/core/dataframe.py#L1645 ). Am curious, is this needed or is this something we might be able to avoid?

Here is the [profile.zip]( https://github.com/rapidsai/dask-cuda/files/3903002/profile.zip ). Copied from @madsbk's [comment]( https://github.com/rapidsai/dask-cuda/pull/183#issuecomment-559600162 ).

cc @kkraus14 @mrocklin @quasiben

**Comment by madsbk** [comment]
With https://github.com/rapidsai/cudf/pull/3497 and https://github.com/dask/dask/pull/5657, Dask uses in-place `cudf.drop()`, which doubles the performance of merge on two GPUs!

**Comment by mrocklin** [comment]
As mentioned in that PR, it may not be trivial for us to use the inplace operation.  If there is a way to accelerate this within cudf itself that might be nicer.

**Comment by kkraus14** [comment]
> As mentioned in that PR, it may not be trivial for us to use the inplace operation. If there is a way to accelerate this within cudf itself that might be nicer.

Could we use a shallow copy? That should be equally as cheap without mutating input objects, though at the risk of mutating memory down the line.

**Comment by mrocklin** [comment]
Ah, I see.  Yes, I can see how a shallow copy would also cause some correctness concerns on your end as well.

**Comment by mrocklin** [comment]
In the dask-cudf case this is still a live issue.  We probably can't merge the proposed solution as-is.  We're working on an alternative with dataframe optimizations.

**Comment by kkraus14** [comment]
> In the dask-cudf case this is still a live issue. We probably can't merge the proposed solution as-is. We're working on an alternative with dataframe optimizations.

Would suggest you open a dask issue to track it as now the fix will hopefully be Pandas/cudf agnostic :)

**Comment by jakirkham** [comment]
Well let's go ahead and reopen so we are at least tracking this somewhere (at least until we know where it belongs 😉). Thanks for the work on this so far. 🙂

**Comment by madsbk** [comment]
Created an issue to track this issue: https://github.com/dask/dask/issues/5664
