### ISSUE TITLE
[QST] Improving performance in Dataframe.merge

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#3494]
**What is your question?**

In a recent UCX benchmark ( https://github.com/rapidsai/dask-cuda/pull/183 ), we are noticing that it is taking a bit to call `Dataframe.merge`. Interestingly this is taking nearly 2x longer (in the communication profile) than a deepcopy of the data ( https://github.com/rapidsai/cudf/issues/3493 ). Am curious, are there ways we can speed this function up?

Here is the [profile.zip]( https://github.com/rapidsai/dask-cuda/files/3903002/profile.zip ). Copied from @madsbk's [comment]( https://github.com/rapidsai/dask-cuda/pull/183#issuecomment-559600162 ).

cc @kkraus14 @mrocklin @quasiben

**Comment by mrocklin** [comment]
I'm not sure I follow this.  The merge call in the profile is fairly cheap,
around 10% of total

https://gist.githack.com/mrocklin/a2fee3d50707ca08540f6baf16472ce7/raw/6481b4bd4a52cf9121ff059750138ed3ddc089af/dask-cudf-ucx-profile.html

**Comment by jakirkham** [comment]
I added this in the edit. Not sure if you saw.

> in the communication profile

**Comment by kkraus14** [comment]
We've spent a lot of time optimizing joins at the C++ level and the Python overhead should be vastly reduced as part of the Python refactor based on libcudf++.

**Comment by madsbk** [comment]
> We've spent a lot of time optimizing joins at the C++ level and the Python overhead should be vastly reduced as part of the Python refactor based on libcudf++.

Great, combined with https://github.com/rapidsai/dask-cuda/pull/226, we should see a significant overall performance boost!

**Comment by kkraus14** [comment]
Closing as this was addressed.
