### ISSUE TITLE
[BUG] CUDA_TRY leaves CUDA error pending

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3510]
As discussed in #3158, the `CUDA_TRY` macro can leave the CUDA error pending.  Its argument is often obtained via `cudaPeekLastError` and the macro does not clear it when the exception is thrown.  Leaving the CUDA error pending will likely trigger another subsequent error if the throw exception is caught in a way that allows execution to continue.

**Comment by jrhemstad** [comment]
Simple solution is to just add `cudaGetLastError()` to `CUDA_TRY` to clear the error state.

Note that some CUDA errors are "sticky" and cannot be cleared by `cudaGetLastError()` and can only be cleared by resetting the CUDA context.

**Comment by jrhemstad** [comment]
Closed by https://github.com/rapidsai/cudf/pull/3587
