### ISSUE TITLE
[FEA] table level split API with the output laid out contiguously in device memory

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3515]
We are in the process of trying to optimize shuffle for spark.  We are running into some performance issues with memory transfers and also RMM_FREE.

As the size of a job increases spark has to split the data into smaller and smaller pieces to redistribute the data for downstream processing a.k.a shuffle the data. This process usually involves taking a table, partitioning it either with hash partitioning or with lower/upper bounds.  Followed by calling split on the table to create N smaller tables one for each partition.  These smaller tables are distributed to other nodes/GPUs for processing.

The issue is that when we call split the number of resulting memory buffers is `O(num_splits * num_columns)`  This is bad because to transfer the data with cudaMemcpy or UCX I have to issues at least `num_splits * num_columns` calls. It does not scale very cleanly.  What is more cnmem, which RMM is wrapping uses a linear algorithm to free a buffer, so the more allocations done the longer RMM takes to free it, and in our tests RMM free is starting to show up taking a significant amount of time for large queries.

I would like to propose an alternative version of split that will take a table_view as input instead of a column_view and each output table_view would be backed by a single contiguous rmm allocation.  With that we would now have `O(num_splits)` allocations `O(num_splits)` calls to move the data and the size of the buffers being transferred would likely be larger so it would be more efficient to send them.

We had a few discussions about the APIs and I think I would like to see something like

```
class contiguous_split_result {
  cudf::experimental::table_view table;
  unique_ptr<rmm:device_buffer> buffer;
};

std::vector<contiguous_split_result> contiguous_split(cudf::experimental::table_view const& input, std::vector<size_type> const& splits);
```

In this case each contiguous_split_result would have a table_view, because it does not own the device memory it is pointing to, and a device_buffer that would own that memory.

I really do want a table_view because in some cases we will not end up transferring the table_view to a new GPU and would like to be able to process it in place.

I am also okay with doing a single allocation for the entire split output, but the return type gets to be a lot more complicated because you need to know the location and size for each table_view, and if we need to drop some of the data, but not all of it we would need to make copies of it first.

**Comment by jrhemstad** [comment]
From what I saw, it looked like the bottleneck was really from the poor scaling of RMM free. So `contiguous_split` may actually be a larger hammer than what is needed here. 

You identified that with the existing split you send each partition over the wire in multiple messages (~`2m` messages, where m is the number of columns).

On the receiving end, you allocate ~2m buffers to receive the partition. You identified that the bottleneck was having to free the 2m buffers on the receiving end with RMM_FREE, yes?

So in reality, the bottleneck is not the 2m messages, but the 2m buffers (specifically, freeing them).
The proposed solution in contiguous_split is to enable 1 message and 1 buffer (per partition).

But why not do 2m messages and 1 receive buffer? I.e., just allocate a single buffer on the receiving end to hold the entire partition and send the 2m messages into that single buffer.

This wouldn't require any new libcudf functionality, and it could be higher performance because:
- There's extra work to perform the contiguous_split step
- Unless the messages are really tiny, you likely get better network utilization by using multiple messages instead of a single giant one

**Comment by revans2** [comment]
@jrhemstad The issue is multi-fold, and what you are proposing covers some of it. Sorry if the following is long but I want you to understand the full problem and what we are trying to fix.

Currently in Spark as a part of shuffle after partitioning the data Spark will write the data to disk. Originally we would call split after hash_partition but when the number of partitions became large we found that transferring the data to the host was extremely slow.  This had nothing to do with RMM, it was just the fact that we had to call cudaMemcpy so many times on relatively small buffers that we could not keep the PCIe bus fully utilized. The optimization we came up with was to transfer the data back to the host without splitting it.  Then we would split it on the CPU as we wrote it out to disk.  This had the added benefit of doing more or less what you are suggesting in that when we pulled the data back from disk we would have a single buffer.  But it also had the advantage that we could do a single transfer of the data.

We are now in the process of trying to use UCX to transfer the data instead of using the built in spark shuffle.  Because we are not pulling the data back to the CPU fist we had go back to splitting the data on the GPU again.  The issues we saw after that are RMM frees taking forever, like you said, both on the sending side because of the large number of buffers created there, but also on the receiving side.  Your proposal helps to mitigate the receiving side.  The other issue I am really concerned about is the number of transfer calls that will happen.  We have not gotten past the RMM issues yet, but from our previous experience the overhead of a cudaMemcpy to the host is not trivial.  I imagine that UCX calls are similarly expensive, and I want to reduce the number of transfers that we do.  This is why I want contiguous_split.  In the short term it helps with RMM, at least until we can fix RMM issues properly.  In the long term it should help us to optimize the transfer speed between tasks.

So the overall plan is to have contiguous_split output something that we can either process on the GPU as it, if the receiver happens to be running on the same GPU and the producer, or send to a separate GPU with at most two transfers.  One transfer to send the metadata for the table (probably a host to host transfer) and a second to send the actual data.  On the receiving side we could try to play some games with what you are suggesting and allocate a single large buffer to handle receiving all of the remote data at once.  My hope is that we would not need to do that if we can keep the number of partitions to a reasonable level.

**Comment by revans2** [comment]
Sorry.  In practice working with UCX we have found that you don't get better performance with smaller transfers. With very small transfers the bottleneck quickly becomes the CPU.  The UCX API requires you to call a progress function repeatedly to make progress. If we dedicate an entire core to calling the progress function we can get OK performance at 200KB message sizes.  As the sizes get larger the amount of CPU used goes down significantly, which means we can use less CPU to transfer the same amount of data at the same throughput.  This might change if we have bonded nics or other things that we have not tested yet.  But it is a lot simpler to break a transfer up into smaller ones if needed than the opposite.

**Comment by harrism** [comment]
I don't see why you have to allocate 2m buffers on the sending side -- the split is a zero-copy split, right? So there should be no new allocations on the sending side in Jake's suggested approach. There are only 2 allocations on the receiving side, rather than 2m.

**Comment by revans2** [comment]
The issue is also with the number of send operations that need to happen.  Not just the number of allocations done.

**Comment by jrhemstad** [comment]
> The issue is also with the number of send operations that need to happen

This is no small amount of work, but a common technique to alleviate the overhead of small messages is to allocate a medium-sized staging buffer. When you "send" a small message, it is just appended to the staging buffer. When the staging buffer reaches a certain size, the whole buffer is then sent over the wire.

This is in effect a more general way of doing what `contiguous_split` is doing (aggregating all of a table into a single buffer to be sent). I don't know how feasible this is in the Spark framework.

**Comment by nvdbaranec** [comment]
Done.
