### ISSUE TITLE
[FEA] `unordered_multimap` improvements

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3518]
**Is your feature request related to a problem? Please describe.**
The CUDF `unordered_multimap` could use some improvements.

**Describe the solution you'd like**

1. Update `insert`/`find`
   
   - Remove the[ Frakenstein `insert`](https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/src/hash/concurrent_unordered_multimap.cuh#L224) function that requires a bool to indicate if the hash value is pre-computed. Furthermore, remove the `keys_are_equal` parameter as it is redundant with the member `keys_equal()`. 

   - Instead, it should be two overloads:
```c++
  insert(const value_type& x, hash_value_type precomputed_hash_value){
   ...
  }

  insert(const value_type& x){
     auto hash_value = m_hf(x);
     insert(x, hash_value);
   }
```

   - Do the same thing for [Frakenstein `find`](https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/src/hash/concurrent_unordered_multimap.cuh#L364). 

2. Add `unordered_multimap::count` to count the number of keys that match the queried key:

```c++
size_type count(key_type k){...}
```

This would simplify the computation of estimating the join output size. 

3. More TBD

**Comment by kaatish** [comment]
>  2. Add `unordered_multimap::count` to count the number of keys that match the queried key:
> 
> 
> ```c++
> size_type count(key_type k){...}
> ```
> 
> This would simplify the computation of estimating the join output size.

If you want to encapsulate the while loop [here](https://github.com/rapidsai/cudf/blob/072785e24fd59b6f4eeaad3b54592a8c803ee96b/cpp/src/join/join_kernels.cuh#L150), the signature of the count function will have to be

`size_type count(key_type k, row_equality eq, bool is_left_join)`.

**Comment by jrhemstad** [comment]
> If you want to encapsulate the while loop [here](https://github.com/rapidsai/cudf/blob/072785e24fd59b6f4eeaad3b54592a8c803ee96b/cpp/src/join/join_kernels.cuh#L150), the signature of the count function will have to be
> 
> `size_type count(key_type k, row_equality eq, bool is_left_join)`.

The hash map shouldn't need to know anything about `is_left_join`. That logic should be handled outside the hash map.

I understand the need for the `row_equality` parameter and that makes sense to add.

**Comment by harrism** [comment]
@jrhemstad is this issue still relevant?
