### ISSUE TITLE
[FEA] Port cuIO JSON reader to `cudf::column` types

### ISSUE THREAD

**Issue by mjsamoht** [rapidsai/cudf#3521]
**Is your feature request related to a problem? Please describe.**
This issue tracks the effort for moving the cuIO JSON reader to using the new column design and associated infrastructure.  It is a continuation of #2954 where all other cuIO readers and writers were moved in release 0.11.

**Describe the solution you'd like**
Currently, cuIO JSON reader uses wrappers around the C-style `gdf_column` to aid in storing/accessing column metadata and allocating/deallocating memory. We should be able to get rid of the custom C++ wrappers and directly use the `cudf::column` and `cudf::table`.

**Describe alternatives you've considered**
We may or may not need some sort of temporary wrapper or custom column class still within cuIO to temporary hold column metadata that's format-specific, for delayed column creation to save memory or other usage. The returned columns will be `cudf::column` and `cudf::table` though.

**Additional context**
See other porting efforts for `libcudf`.

**Comment by mjsamoht** [comment]
@nvdbaranec are you still working on this?

**Comment by nvdbaranec** [comment]
Yes. Hoping to put up a PR today.
