### ISSUE TITLE
read_csv "sep" not implemented, but exposed to end users. Causing parsing errors

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#353]
The `read_csv` API exposes the `sep=None` argument, but doesn't actually use it. Users coming from pandas are used to putting their delimiter in the `sep` argument, and may not realize they need to use the `delimiter=` argument instead of `sep`.

We should consider either implementing or removing this to avoid confusion. Will add example later today (@zronaghi can add as she experienced this issue).

**Comment by harrism** [comment]
@BradReesWork is this on the CSV reader roadmap?

**Comment by kkraus14** [comment]
This is resolved and `sep` is exposed now.
