### ISSUE TITLE
[FEA] Blazing wishlist Variable width data

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#3536]
Variable Width Data:

Kernels should to have row level accessors that allow you to get a ptr to the underlying data and the length of that data from that point.
Kernels should have batch accessor methods that allow a kernel to do something like
```
  //inside a kernel
  int offsets[BATCH_SIZE+1];
  byte * dataStart;
   column.getColumnDataBatch(offsets,BATCH_SIZE,dataStart);

   for(0 to BATCH_SIZE){
      i = 0
      for(i to BATCH_SIZE){
       processBytes(dataStart + offsets[i],dataStart + offsets[i+1])
      }
   }
```
Kernels could have a method for accessing portions of bytes from the buffer of variable width data. This could allow something like more performant searches for rare occurrences of sequences of characters without the thread divergence that both the above methods would display. I am sure that would be useful to someone doing something like searching for nucleotides or something.
There should be a limited number of buffers and allocations to manage a variable width data. For example we hope there will be a single buffer for all of the variable width data and another for offsets. Not a buffer per row. This is important for transporting over things like UCX / TCP. As well as interoperability.
should have same basic string functionality at the row level of a kernel like concat, like, regex compare, cast , inequality comparisons, equality comparisons, in a header only implementation so that we can include and use these from kernels
something like
```
  //inside a kernel
  int offset = 5;
  int size;
  byte * dataStart;
   column.getColumnData(offset,dataStart,size);
   result = likeOper(dataStart,size,"some_regex")
```
General Requirements:
1. * This should be able to be combined together with https://github.com/rapidsai/cudf/issues/3535 in order to form dictionary encoded columns where the dictionaries are variable width data.

**Comment by jrhemstad** [comment]
We've already got a representation for variable width elements that is already in heavy use throughout libcudf. 

The thing for you to do is to evaluate the representation we use for strings columns and if you require changes, then those need to be opened as concrete, separate issues. 

For the strings representation, see: https://github.com/rapidsai/cudf/blob/branch-0.11/cpp/docs/TRANSITIONGUIDE.md#strings-support

**Comment by jrhemstad** [comment]
Looking through your requirements, I think the strings column representation already ticks all your boxes, but you'll have to verify.

**Comment by felipeblazing** [comment]
```   if( d_strings.is_valid(row_index) ) {
      string_view d_str = d_strings.element<string_view>(row_index);
      ...
   }```

That this is a requirement seems a bit onerous. If its invalid there is still a space in the allocation is there not? requiring this can cause significant slow downs because it is doing an extra global memory look up, causes thread divergence when nulls occur which can duplicate execution time of the code within the if.

**Comment by felipeblazing** [comment]
> ```
> if( d_strings.is_valid(row_index) ) {
>       string_view d_str = d_strings.element<string_view>(row_index);
>       ...
>    }
> ```
> 
> That this is a requirement seems a bit onerous. If its invalid there is still a space in the allocation is there not? requiring this can cause significant slow downs because it is doing an extra global memory look up, causes thread divergence when nulls occur which can duplicate execution time of the code within the if.

The more I think about this I can't envision many scenarios where immediately afterwards there is not thread divergence since element in this case would return something like nullptr and size 0.

**Comment by jrhemstad** [comment]
> If its invalid there is still a space in the allocation is there not?

No.

If element at `row_index` is null, you can do:
```c++
 string_view d_str = d_strings.element<string_view>(row_index);
```
It's just undefined behavior to do anything with `d_str`. 

That's no different than with a fixed-width type like an `int`. It's undefined behavior to use the value of a null element.

**Comment by felipeblazing** [comment]
ok awsome! ty!

**Comment by jrhemstad** [comment]
@felipeblazing can we close this issue? Or are there requirements that are not met by the string column representation?
