### ISSUE TITLE
[DISCUSSION] Bitmask operations via Thrust

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#3565]
Problem
-
Nulls are supported via bitmask, and useful libraries like Thrust don't support bit specific operations. To compensate, we complement Thrust with a custom bitmask kernels. These kernels re-use a lot of the same code, can be confusing, and implementing them correctly takes significantly longer than their Thrust counter-parts.

Proposed Solution
-
Firstly, I am unsure if this is feasible without modifying Thrust's source code (which I have no desire to do), hence the discussion.

1) Create a Thrust execution policy specifically for "bit-specific" operations (which doesn't do anything more than our current execution policy).
2) Use SFINAE to "override" `parallel_for` and use a custom `AgentLauncher`.
 - 1) For each element, make a _copy_ of each element.
 - 2) Execute the unary operation for each copy of the element.
 - 3) Unary operation has the opportunity to modify the copy via reference.
 - 4) Merge the appropriate bits from each copy based on the thread or element id (more on this later).
 - 5) Assign the merged bits to the original element via reference.

A Little More Detail
-
_How does the unary function know which bit to operate?_
The `AgentLauncher` needs to indicate the appropriate bit to the unary function. To support this, we would only allow operations against elements which "extend" a _special tuple type_. That tuple contains whatever data the user wants to operate on _as well as_ the index of the bit on which to operate (bit offset per element can be found via modulus).

_What about operations which iterate over subsets of the data?_
Since we're "processing individual bits", we already know the value of the element to which the bit belongs. In this case, we would only invoke the unary operator for the appropriate subset of bits. The other bits would be set to their original value before the result is assigned to the original element's memory (via reference).

_Custom bitmask kernals are fast, is this going to be faster?_
I don't know. That is a major topic of discussion. The kernels Thrust produces are (read: should be) efficient. It's possible thrust can produce faster kernels than we are able to implement manually, and can offset the overhead of the proposed bit-specific operation abstraction. It's also possible the new kernels will be slower. We won't know until we benchmark and compare against existing implementations.

Feedback
-
As mentioned previously, I don't know if this is feasible. I'm hoping for feedback such as...
- "This definitely won't work, here's why....",
- "You forgot to address this issue...",
- "This will definitely be slower, because..."
- "I disagree that custom kernels are a problem worth solving, because..."

Thanks :pray:

**Comment by jrhemstad** [comment]
The proposed solution is too far into the realm of theoretical and too deep into the internals of Thrust for me to really reason about how it would work or how efficient it is going to be. I'm not familiar with specifying custom execution policies. 

I'd need to see a more concrete example to better understand what is being proposed. 

In general, I think the performance hurdle to overcome is that the custom kernels are _very_ efficient. `__ballot_sync` computes a single output element in a single intrinsic. Likewise, we can compute the resulting null count in the same kernel, at the same time using another very efficient primitive `__popc`. I'm not sure how the equivalent could be done in a single Thrust aglorithm, which would mean doing _two_ kernel invocations. The amount of work in a bitmask operation is usually quite small, which means the launch latency will be large relative to the kernel execution time, so using two kernels in place of one could mean significant slow down.

**Comment by harrism** [comment]
On a different note, I prefer that we provide general tools for operating on bit masks that can be used in custom CUDA kernels *as well as* Thrust kernels (if that is possible). Because even if we enable operating on bit masks in Thrust, there will always be cases where we need to write kernels directly. So the place to start is to look at our custom bitmask kernels and look at common patterns that can be abstracted out to make them easier to write and less bug prone.

**Comment by harrism** [comment]
I'm going to close this discussion. Please reopen if needed.
