### ISSUE TITLE
[FEA] libcudf++ hash_partition is not ideal for large number of partitions

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3566]
When I filed #3515 I expected the new libcudf++ `hash_partition` to behave like `gdf_hash_partition` did where it would return a reorder table and offsets into the table that can be passed into split.  The new implementation does not do that.  It splits the tables up itself.  This is problematic for the reasons described in #3515.

As such I am requesting that we either have an API for hash_partition that is like the split command requested in #3515 and implemented in #3557 or if we could just do the same thing as `gdf_hash_partition` did and users can split it up ourselves using whichever API they want.

**Comment by jrhemstad** [comment]
I suggest the new API should be the following:
```
std::pair< unique_ptr<table>, std::vector<size_type> > hash_partition(...);
...
auto [table, offsets] = hash_parititon(...);
```

i.e., returns a single table and a set of offsets into that table, where `offsets[i]` is the row index into `table` of the start of partition `i`. 

This can then be passed into the `contiguous_split` function in order to get the desired "one allocation per table" layout.

**Comment by trevorsm7** [comment]
Should I keep the existing API as-is and add a separate implementation for this, or should I just modify the existing API since nobody is using it yet? I took the latter approach in the PR, but it would be easy to do the former.

**Comment by jrhemstad** [comment]
> Should I keep the existing API as-is and add a separate implementation for this, or should I just modify the existing API since nobody is using it yet? I took the latter approach in the PR, but it would be easy to do the former.

The latter is good.
