### ISSUE TITLE
[QST] Usage of `np.frombuffer`

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#3568]
**What is your question?**

Currently there are several calls to `np.frombuffer`. Is there a reason for this?

This is somewhat interesting (to me) as `np.frombuffer` is less friendly to use compared to alternatives like `np.asarray`. The former (`np.frombuffer`) loses information about the data (like type, shape, striding, and so on). As a result users need to feed this information back in (like setting type in the call to `np.frombuffer` or calling `.reshape(...)`). On the other hand the latter (`np.asarray`) preserves all this information. It also works nicely with `memoryview`s. So a typical thing one might do is call `np.asarray(memoryview(...))` on some object to get a NumPy view onto the underlying data. Given this, would it make sense to switch to `np.asarray` or are there other reasons not to?

**Comment by kkraus14** [comment]
This is currently only used in tests after recent refactoring. Closing this.
