### ISSUE TITLE
[FEA] Update cudf.to_parquet to use new GPU accelerated Parquet writer

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3574]
Now that #3284 merged, [`cudf.to_parquet` needs to be updated](https://github.com/rapidsai/cudf/blob/branch-0.12/python/cudf/cudf/io/parquet.py#L73) to use it, instead of PyArrow's Parquet writer.

**Comment by chinmaychandak** [comment]
This would be awesome!

**Comment by jdye64** [comment]
I started working on this. After taking a look and talking with @kkraus14 I'm going to hold off on starting this until PR https://github.com/rapidsai/cudf/pull/3254 is merged.

**Comment by jdye64** [comment]
Just an update here. Still waiting on https://github.com/rapidsai/cudf/pull/3254 to merge but looks like its getting close. I will start on this once its merged.
