### ISSUE TITLE
[FEA] Implement DataFrameGroupBy.idxmin and DataFrameGroupBy.idxmax

### ISSUE THREAD

**Issue by Nanthini10** [rapidsai/cudf#3585]
**Is your feature request related to a problem? Please describe.**
Would be useful to have an implementation for finding the maximum and minimum index on grouped data with `idxmax` and `idxmin` 

**Describe the solution you'd like**
Return the occurrence of the maximum and minimum index value on groupby

**Describe alternatives you've considered**
`reset_index` before `groupby` and then sorting based on that to return first and last values

**Additional context**
Pandas implementations
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.DataFrameGroupBy.idxmax.html

https://pandas.pydata.org/pandas-docs/version/0.17.0/generated/pandas.core.groupby.DataFrameGroupBy.idxmin.html

**Comment by jrhemstad** [comment]
Lol, this is extremely coincidental. I was _just_ looking at adding `argmax/argmin` (equivalent of `idxmax/idxmin`) this morning.

**Comment by harrism** [comment]
There is an existing request: #2188

**Comment by harrism** [comment]
Closing in favor of the older one.

**Comment by jrhemstad** [comment]
From @2188:

>  I particularly need this implemented on groupby objects

So I agree this is a duplicate.

**Comment by beckernick** [comment]
Agreed. Closing this again as a duplicate, and adding the link to the groupby.idxmax/min pandas docs to the original issue #2188
