### ISSUE TITLE
[BUG] Failed to set CMAKE_CUDA_HOST_COMPILER when compiling

### ISSUE THREAD

**Issue by zingdle** [rapidsai/cudf#3589]
**Describe the bug**
Failed to set `CMAKE_CUDA_HOST_COMPILER` when compiling

**Steps/Code to reproduce bug**
Follow [build instruction](https://github.com/rapidsai/cudf/blob/branch-0.12/CONTRIBUTING.md#setting-up-your-build-environment), when cmake:

```
cmake .. -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX -DCMAKE_CXX11_ABI=ON -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-7
```

But ` -ccbin=/usr/bin/g++-7` is not used when compiling objects.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 6e6e00197abec292a75114bdc8d0cba37c1bec5e (HEAD -> branch-0.12, origin/branch-0.12, origin/HEAD)
     Merge: 2f745efa0 9378733bc
     Author: OlivierNV <45697062+OlivierNV@users.noreply.github.com>
     Date:   Tue Dec 10 22:22:53 2019 -0800
     
     Merge pull request #3502 from OlivierNV/enh-orc-reader-decimals-as-int
     
     [REVIEW] ORC reader: add option to read DECIMALs as INT64
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     63f644be44201467e3938d59ed9d89cc8725c35d thirdparty/jitify (remotes/origin/feature/api_v2_v0.10)
     39125e0e476b960c2001f1ec76a3441335ff91b2 thirdparty/libcudacxx (0.8.1-94-g39125e0)
     08bc464bd8f4d779e4294305aa7dadebcebcc507 thirdparty/libcudacxx/libcxx (heads/rapidsai-interop)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=19.10
     DISTRIB_CODENAME=eoan
     DISTRIB_DESCRIPTION="Ubuntu 19.10"
     NAME="Ubuntu"
     VERSION="19.10 (Eoan Ermine)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 19.10"
     VERSION_ID="19.10"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=eoan
     UBUNTU_CODENAME=eoan
     Linux PC 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Dec 12 14:29:15 2019
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce GTX 1660    Off  | 00000000:01:00.0  On |                  N/A |
     |  0%   50C    P8    11W / 135W |   2031MiB /  5944MiB |      6%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  GeForce GT 640      Off  | 00000000:03:00.0 N/A |                  N/A |
     | 60%   41C    P8    N/A /  N/A |      1MiB /   981MiB |     N/A      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      1123      G   /usr/lib/xorg/Xorg                            26MiB |
     |    0      1619      G   /usr/lib/xorg/Xorg                           546MiB |
     |    0     19303      G   /usr/bin/gnome-shell                         330MiB |
     |    0     20426      G   ...quest-channel-token=9101046147469587991   351MiB |
     |    0     21110      G   ...quest-channel-token=4549011318992961533   726MiB |
     |    1                    Not Supported                                       |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   39 bits physical, 48 bits virtual
     CPU(s):                          6
     On-line CPU(s) list:             0-5
     Thread(s) per core:              1
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           158
     Model name:                      Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
     Stepping:                        13
     CPU MHz:                         3300.137
     CPU max MHz:                     4600.0000
     CPU min MHz:                     800.0000
     BogoMIPS:                        7399.70
     Virtualization:                  VT-x
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        1.5 MiB
     L3 cache:                        9 MiB
     NUMA node0 CPU(s):               0-5
     Vulnerability Itlb multihit:     KVM: Mitigation: Split huge pages
     Vulnerability L1tf:              Not affected
     Vulnerability Mds:               Not affected
     Vulnerability Meltdown:          Not affected
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling
     Vulnerability Tsx async abort:   Mitigation; TSX disabled
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d arch_capabilities
     
     ***CMake***
     /home/user/.miniconda3/envs/cudf_dev/bin/cmake
     cmake version 3.16.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /home/user/.local/bin/g++
     g++ (Ubuntu 8.3.0-23ubuntu2) 8.3.0
     Copyright (C) 2018 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243
     
     ***Python***
     /home/user/.miniconda3/envs/cudf_dev/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/user/.miniconda3/envs/cudf_dev/bin:/home/user/.miniconda3/condabin:/usr/local/cuda/bin:/home/user/.local/bin:/usr/local/cuda/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/linuxbrew/.linuxbrew/opt/fzf/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64:/usr/local/cuda/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/user/.miniconda3/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/user/.miniconda3/condabin/conda
     # packages in environment at /home/user/.miniconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     aspy.yaml                 1.3.0                      py_0    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     black                     19.10b0                  py37_0    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cached-property           1.5.1                      py_0    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cffi                      1.13.2           py37h8022711_0    conda-forge
     cfgv                      2.0.1                      py_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     cmake                     3.16.0               h28c56e5_2    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              2.8              py37h72c5cf5_1    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cupy                      6.3.0            py37hf7e11e9_0    rapidsai
     cython                    0.29.14          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.9.0+7.g1c39d48b          pypi_0    pypi
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.9.0+9.g74b6e1aa          pypi_0    pypi
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37he1b5a44_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.7           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     flake8                    3.7.9                    py37_0    conda-forge
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.6.1                      py_0    conda-forge
     future                    0.18.2                   py37_0    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                4.53.1                   py37_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     identify                  1.4.8                      py_0    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        1.2.0                    py37_0    conda-forge
     ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
     ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     4.3.21                   py37_0    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.6.1                    py37_0    conda-forge
     krb5                      1.16.3            h05b26f9_1001    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libopenblas               0.3.7                h5ec1e0e_5    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.11.0               cuda10.1_0    rapidsai
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuv                     1.34.0               h516909a_0    conda-forge
     llvmlite                  0.30.0           py37h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.0.1                    pypi_0    pypi
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     mypy_extensions           0.4.3                    py37_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.5.0                      py_0    conda-forge
     nccl                      2.4.6.1              cuda10.1_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nodeenv                   1.3.3                      py_0    conda-forge
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.46.0           py37hb3f55d8_1    conda-forge
     numpy                     1.17.3           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_1    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.1                      py_0    conda-forge
     partd                     1.0.0                      py_0    conda-forge
     pathspec                  0.6.0                      py_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.2.1            py37hd70f55b_1    conda-forge
     pip                       19.3.1                   py37_0    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     pre_commit                1.18.1                   py37_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            3.0.2                      py_0    conda-forge
     psutil                    5.6.7            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.5                      py_0    conda-forge
     pyrsistent                0.15.6           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.3.1                    py37_0    conda-forge
     python                    3.7.3                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.2              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2019.12.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2019.12.9        py37h516909a_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.11.0                   py37_0    rapidsai
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                42.0.2                   py37_0    conda-forge
     six                       1.13.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.2.2                      py_0    conda-forge
     sphinx-markdown-tables    0.0.10                   pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     streamz                   0.5.2                    pypi_0    pypi
     tblib                     1.4.0                      py_0    conda-forge
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     typed-ast                 1.4.0            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.1                  py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.7                   py37_0    conda-forge
     virtualenv                16.7.5                     py_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Comment by GregoryKimball** [comment]
Please try again to follow our [CONTRIBUTING](https://github.com/rapidsai/cudf/blob/branch-22.08/CONTRIBUTING.md) guide to build from source.
