### ISSUE TITLE
[FEA] Add support for "rank" to cudf.groupby

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3591]
With Pandas I can call DataFrame and Series level [`rank`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rank.html) function. We have [a related open feature request](https://github.com/rapidsai/cudf/issues/1294).

Since groupby operators are implemented separately, I'm raising this additional feature request for [grouped `rank`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.rank.html#pandas.core.groupby.GroupBy.rank) support.

**Comment by beckernick** [comment]
Will https://github.com/rapidsai/cudf/pull/8652 provide what's needed in libcudf for this feature?

**Comment by harrism** [comment]
Not sure. @rwlee ?

**Comment by rwlee** [comment]
This covers the basic functionality of the grouped `rank` requested, with a few missing pieces.
1. Current implementation expects keys (and as a result inputs) to be sorted before calling the groupby `rank` scan.
2. The linked function seems to have a lot of sub features (`average`, `min`, `max`, `first`, and `dense` rank methods + configurations for `axis`, `percent`, and `na_option`, `numeric_only`)

In terms of configurations:
* `axis` is reasonable to implement, but looks very different from the current rank code.
* `percent` should be reasonable to implement as an additional transformation layer on top of the aggregate result.
* `na_option` or null handling has 3 different configurations `keep`, `top`, and `bottom`. Support `keep` is difficult given the current requirement for pre-sorting. With the new approach that has the order by column(s) being supplied as structs, it could be possible but requires sorting struct columns. I think we can support `top` and `bottom` based off sorting's handling of nulls, but I'd need to double check.

In terms of rank methods:
* Our `RANK` aggregation in #8652 corresponds to the pandas `min` functionality.
* Our `DENSE_RANK` aggregation in #8652 corresponds to the pandas `dense` functionality.
* `max` and `average` should be easy to implement based off the what we already have, but are not in #8652
* I'm not quite sure what `first` is, if it's a grouped row number we can probably shoehorn the existing row functionality to work with it. I couldn't find a simple example of this one working.

**Comment by beckernick** [comment]
Bringing this comment to the primary issue, rather than a commit: https://github.com/rapidsai/cudf/commit/b803c4ef48824238935f4972e472367d13ec34e7#commitcomment-65914602

cc @chil-trek thanks for commentnig. Could you share any additional information about how you'd like to use groupby.rank?

**Comment by chil-trek** [comment]
@beckernick - I am looking for the following

Taking the example that I have come across in libcudf documentation, say I have the below dataframe
df = cudf.DataFrame()
df['driver_name'] = ["bottas", "bottas", "bottas", "bottas", "bottas", "hamilton", "hamilton", "hamilton", "hamilton"]
df['num_overtakes'] = [2, 2, 2, 1, 1, 4, 4, 3, 2]
df['lap_number'] = [3, 7, 7, 1, 2, 1, 1, 4, 4]

I want to compute dense_rank within each 'driver_name', ordered by 'num_overtakes' and 'lap_number'

Expected syntax (doesn't have to exactly be this way)

df.groupby(['driver_name']).dense_rank(orderby=['num_overtakes', 'lap_number'], ascending=[True, True])

Just to make sure it is clear, the SQL equivalent is
"select driver_name, num_overtakes, lap_number, dense_rank() over(partition by driver_name order by num_overtakes, lap_number) from df"

By the way, I checked BlazingSQL documentation and that too doesn't support rank in window. I gathered that this is supported only in libcudf and cudf-java.

Hope that clarifies the ask

**Comment by karthikeyann** [comment]
All features are implemented for groupby rank (https://github.com/rapidsai/cudf/pull/9569)
Also, unified the ranks together to single aggregation.
