### ISSUE TITLE
[BUG] CUDA_TRY guard missing in multiple places

### ISSUE THREAD

**Issue by seunghwak** [rapidsai/cudf#3595]
**Describe the bug**
CUDA_TRY guard missing in multiple places.

under cudf/cpp
grep -rHn cudaStreamCreate
grep -rHn cudaStreamSynchronize
grep -rHn cudaStreamDestroy

I can see multiple unguarded calls.

This might be a case for other CUDA calls as well.

One tricky case is CUDA calls inside destructors (as throwing inside destructors is undesirable).

https://github.com/rapidsai/cudf/blob/6a26d6500da047b811f1c2e944cb525d1375af72/cpp/src/utilities/legacy/cuda_utils.hpp#L83

Does cuDF has a policy to handle this case?

**Comment by jrhemstad** [comment]
For destructors I generally use an `assert` or check the result and print to `stderr` in a non-release build.

**Comment by karthikeyann** [comment]
Following cuda functions returning `cudaError_t` are missing `CUDA_TRY` guard.
- cudaDeviceGetAttribute
- cudaGetDevice
- cudaGetDeviceCount
- cudaGetDeviceProperties

- cudaMalloc
- cudaMallocHost
- cudaMallocManaged
- cudaMemcpy
- cudaMemcpyAsync
- cudaMemset
- cudaMemsetAsync
- cudaFree
- cudaFreeHost
- cudaGetSymbolAddress

- cudaStreamDestroy
- cudaStreamSynchronize
- cudaDeviceSynchronize
- cudaThreadSynchronize [DEPRECATED]

- cudaPointerGetAttributes
- cudaOccupancyMaxPotentialBlockSize
- cudaProfilerStart
- cudaProfilerStop

- cudaIpcCloseMemHandle
- cudaIpcGetMemHandle
- cudaIpcOpenMemHandle

is `CUDA_TRY` really not necessary for any of these above cuda calls?
