### ISSUE TITLE
[FEA] Update `strings::copy_if_else` to accept pair iterators for inputs

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3598]
**Is your feature request related to a problem? Please describe.**

The existing `strings::copy_if_else` expects the `lhs/rhs` to be `strings_column_view`s. This is problematic because the calling code is attempting to use iterators for the inputs, which requires additional special casing of the string code path. 

**Describe the solution you'd like**

It would be nice if `strings::copy_if_else` could be updated to accept a pair iterator for the `lhs` and `rhs`. This pair iterator would be the result from `make_pair_iterator` that returns a `thrust::pair<string_view, bool>` for each element that contains the element and whether or not it is valid. 

This would look something like:
```c++
template<typename StringPairIterator, typename Filter>
std::unique_ptr<cudf::column> copy_if_else( StringPairIterator lhs,
                                            StringPairIterator rhs,
                                            Filter filter_fn,
                                            rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource(),
                                            cudaStream_t stream=0 )
```

**Comment by jrhemstad** [comment]
This is also necessary because otherwise overloads would have to be provided where the `lhs/rhs` could both/either be a ` cudf::string_scalar`. By using iterators it eliminates the need for maintaining 4 different overloads.

**Comment by davidwendt** [comment]
There seems to be something missing here. 
Can you point me to the code referred to by _the calling code is attempting to use iterators for the inputs_ ?
The code [here](https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/detail/copy_if_else.cuh) appears to use `column_view` for even the kernel parameters.
https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/detail/copy_if_else.cuh

Does the `filter_fn()` still accept an index parameter?
The index would be based on counting from 0 starting with `lhs` and `rhs`? 
Also, I assume there is supposed to be a `StringPairIterator end` parameter so we know when to stop iterating.

**Comment by jrhemstad** [comment]
The new version of `copy_if_else` that requires the iterator based API is under development here: https://github.com/rapidsai/cudf/pull/3471 from @nvdbaranec.

And yes, I forgot to include an `end` iterator, so should probably be something like this:
```c++
template<typename StringPairIterator, typename Filter>
std::unique_ptr<cudf::column> copy_if_else( StringPairIterator lhs_begin, StringPairIterator lhs_end
                                            StringPairIterator rhs_begin,
                                            Filter filter_fn,
                                            rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource(),
                                            cudaStream_t stream=0 )
```

But I'll let you and @nvdbaranec work out the exact requirements.
