### ISSUE TITLE
[BUG] to_host uses column_view::head without asserting that offset is zero

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#3599]
**Describe the bug**
If the `column_view` passed to `to_host` has a non-zero offset, the resulting host vector will contain the wrong data because the `head()` method does not apply the offset.
https://github.com/rapidsai/cudf/blob/6a26d6500da047b811f1c2e944cb525d1375af72/cpp/tests/utilities/column_utilities.hpp#L99-L104

**Expected behavior**
Either assert that offset is zero or take the offset into account. Replacing `c.head<T>` with `c.data<T>` should accomplish the latter.

**Comment by harrism** [comment]
Fixed by #3672
