### ISSUE TITLE
[BUG] Can't operate on nvstrings objects within map_partitions

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3606]
We can't currently use nvstrings objects in `map_partitions` calls using the distributed scheduler.

However, if we pass a cuDF.Series and then access the underlying nvstrings object, we can use it. In the following example, workers simply die left and right when using the distributed scheduler since we directly pass the nvstrings instance.

It works with the single scheduler, so it seems likely to be serialization related. (This may be a better fit for the dask/distributed issue tracker.)

```python
import cudf
import dask_cudf
import nvstrings
from dask_cuda import LocalCUDACluster
from dask.distributed import Client


cluster = LocalCUDACluster(
    n_workers=4,
    CUDA_VISIBLE_DEVICES="0,2,3,4",
)
client = Client(cluster)


ddf = dask_cudf.from_cudf(
    cudf.datasets.randomdata(50, dtypes={'a':str, 'b':str}),
    5
)

def f(df, nvs):
#     return cudf.Series(len(df))
    return cudf.Series(len(nvs))

s = nvstrings.to_device(['a', 'b', 'c'])

ddf.map_partitions(f, nvs=s).compute()
```

**Comment by beckernick** [comment]
cc @ayushdg @randerzander

**Comment by kkraus14** [comment]
@beckernick closing this as serialization is handled with new cudf StringColumns
