### ISSUE TITLE
[BUG] make_empty_column does not work with strings

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3607]
**Describe the bug**

This is not super critical because I can work around it fairly simply for what I am doing. I just don't know if it is going to bite us in the future so I thought I should at least document it.

```
#include <cudf/column/column_factories.hpp>
#include <cudf/strings/strings_column_view.hpp>
...
std::unique_ptr<cudf::column> column = cudf::make_empty_column(cudf::data_type(cudf::STRING));
cudf::strings_column_view view(*column);
```

fails with an exception of 
"../src/strings/strings_column_view.cu:44: strings column has no children"

Sadly this is also true for
```
#include <cudf/strings/detail/utilities.hpp>
#include <cudf/strings/strings_column_view.hpp>
...
std::unique_ptr<cudf::column> column = cudf::strings::detail::make_empty_strings_column();
cudf::strings_column_view view(*column);
```

**Steps/Code to reproduce bug**
see above

**Expected behavior**
The view does not blow up.  An empty column is still a valid column.

**Comment by jrhemstad** [comment]
@davidwendt could you check it out? I'm guessing a `CUDF_EXPECTS` just needs to be updated to check for `size == 0` first.

**Comment by davidwendt** [comment]
Sorry, but I'm not able to recreate this error. Neither of the code snippets in the description execute line 44 as described:
https://github.com/rapidsai/cudf/blob/995c5100423f2d3e2c5b61114800c93ea3cd4069/cpp/src/strings/strings_column_view.cu#L44
This exception (line 44) is in the `strings_column_view` `offsets()` function. The offsets column will not exist if there are no children.

**Comment by revans2** [comment]
@davidwendt sorry it looks like I misunderstood where the exception was coming from.  Sorry I should have dug deeper to see what the error was that I was actually getting.
