### ISSUE TITLE
[BUG] __sizeof__ does not track nvstring device memory

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#3611]
**Describe the bug**

Current `__sizeof__` does not track memory allocated by strings and i would like it to support that. 

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.DataFrame({'a':['1']*1_000_000})
print(df.__sizeof__())
```

```python
64
```
**Expected behavior**
`nvstrings` has `device_memory` which tracks correct memory i believe. 

```python
import cudf
df = cudf.DataFrame({'a':['1']*1_000_000})
print(df['a'].str.device_memory())
```
```python
24000000
```
**Environment overview (please complete the following information)**
 - Environment location: 
 - Method of cuDF install: [conda]

**Environment details**
```python
cudf                      0.12.0b191213           py37_61    rapidsai-nightly
libcudf                   0.12.0b191213       cuda10.0_61    rapidsai-nightly
```

**Additional context**
The problem is stemming from  below function and i think `nvstrings` `sizeof` operation which gives incorrect memory .

For example : 
```python
a = nvstrings.to_device(['a']*500_000)
print(a.__sizeof__())
```
```
32
```
 https://github.com/rapidsai/cudf/blob/6f81a5ccd21abb245fba869045cd63a4cd6250cc/python/cudf/cudf/core/column/column.py#L300-L304

CC: @rjzamora @pentschev 
Regarding:  https://github.com/rapidsai/cudf/issues/1937

**Comment by VibhuJawa** [comment]
Sorry missed that @rjzamora  you all ready are tracking the issue. Closing it. Oops.

**Comment by rjzamora** [comment]
@VibhuJawa - #3610 is in.  Feel free to re-open here if there are problems with the `__sizeof__` fix, etc
