### ISSUE TITLE
[DOC] requirement.txt missing?

### ISSUE THREAD

**Issue by zingdle** [rapidsai/cudf#3624]
## Report incorrect documentation

**Location of incorrect documentation**

https://github.com/rapidsai/cudf/blob/branch-0.12/docs/cudf/README.md

**Describe the problems or issues found in the documentation**

`A basic python environment with packages listed in ./requirement.txt is enough to build the docs.`

But I cannot find `requirement.txt` anywhere in the repo.

**Comment by galipremsagar** [comment]
Closing this issue as the current docs building instructions are different and updated.
