### ISSUE TITLE
[BUG] nvtext.scatter_count doesn't utilize input GPU memory pointer

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3626]
@davidwendt and I discussed offline. Currently, a GPU memory pointer passed in Python to the counts arugment of `nvtext.scatter_count` doesn't get used.

```python
import nvstrings
import nvtext
import rmm
import numpy as np

strs = nvstrings.to_device(['this is mine', 'this', 'yet ano th er'])
arr = np.array([1,2,3], dtype='int32')
dev_arr = rmm.to_device(arr)
ptr = dev_arr.device_ctypes_pointer.value
print(nvtext.scatter_count(strs, ptr))
None
```
The expectation is that this would return an nvstring instance with each string scattered the appropriate number of times based on `arr`.

**Comment by davidwendt** [comment]
Found the error in the python-to-C++ interface code for nvstrings. 
The device pointer is not being passed down to the C++ NVText function.
Should be a simple fix.
