### ISSUE TITLE
[QST]Why cuDF is not able to run 

### ISSUE THREAD

**Issue by vrushang25** [rapidsai/cudf#3631]
I installed cuDF with anaconda during cugraph installation but my kernel is not able to produce any output. 

My code is below.

import cugraph
import cudf
import pandas as pd
print("hi")
M = cudf.read_csv('karate.csv', delimiter=' ', dtype=['int32', 'int32', 'float32'], header=None)
sources = cudf.Series(M['0'])
destinations = cudf.Series(M['1'])
G = cugraph.Graph()
G.add_edge_list(sources, destinations, None)
parts, modularity_score = cugraph.louvain(G)
print(modularity_score)

but i am not getting output for the cudf.read_csv. i tried in jupyter notebook and it is not working. so now what should i do?

when i tried to execute some functions like 

s = cudf.Series([1,2,3,None,4])
print(s)
 but i got the error like below

ERROR:Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

please help me out from this situation.
Thank you so muich.

**Comment by kkraus14** [comment]
@vrushang25 what do you mean you're not getting output for the `cudf.read_csv`? Is `M` not a `cudf.DataFrame` after the call in your example above?

**Comment by vrushang25** [comment]
I am not getting why kernel is not executing. when i tried to execute some functions like

s = cudf.Series([1,2,3,None,4])
print(s)
but i got the error like below

ERROR:Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null, dtype)
    410         try:
--> 411             data = as_column(memoryview(arbitrary))
    412         except TypeError:

TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

CudaAPIError                              Traceback (most recent call last)
<ipython-input-6-d9ded96cafd5> in <module>
      1 df = cudf.DataFrame([('a', list(range(20))),
      2 ('b', list(reversed(range(20)))),
----> 3 ('c', list(range(20)))])
      4 print(df)

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in __init__(self, name_series, index)
    108                 name_series = name_series.items()
    109             for k, series in name_series:
--> 110                 self.add_column(k, series, forceindex=index is not None)
    111 
    112     def serialize(self, serialize):

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in add_column(self, name, data, forceindex)
    810         if isinstance(data, GeneratorType):
    811             data = Series(data)
--> 812         series = self._prepare_series_for_add(data, forceindex=forceindex)
    813         series.name = name
    814         self._cols[name] = series

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in _prepare_series_for_add(self, col, forceindex)
    781         The prepared Series object.
    782         """
--> 783         self._sanitize_columns(col)
    784         col = self._sanitize_values(col)
    785 

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/dataframe.py in _sanitize_columns(self, col)
    734            col values
    735         """
--> 736         series = Series(col)
    737         if len(self) == 0 and len(self.columns) > 0 and len(series) > 0:
    738             ind = series.index

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/series.py in __init__(self, data, index, name, nan_as_null, dtype)
     79         if not isinstance(data, columnops.TypedColumnBase):
     80             data = columnops.as_column(data, nan_as_null=nan_as_null,
---> 81                                        dtype=dtype)
     82 
     83         if index is not None and not isinstance(index, Index):

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null, dtype)
    424                 data = as_column(
    425                     pa.array(arbitrary, type=pa_type, from_pandas=nan_as_null),
--> 426                     nan_as_null=nan_as_null
    427                 )
    428             except (pa.ArrowInvalid, pa.ArrowTypeError, TypeError):

~/anaconda3/lib/python3.7/site-packages/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null, dtype)
    355             )
    356         else:
--> 357             pamask, padata = buffers_from_pyarrow(arbitrary)
    358             data = numerical.NumericalColumn(
    359                 data=padata,

~/anaconda3/lib/python3.7/site-packages/cudf/utils/utils.py in buffers_from_pyarrow(pa_arr, dtype)
    152     if buffers[0]:
    153         mask_dev_array = make_mask(len(pa_arr))
--> 154         arrow_dev_array = rmm.to_device(np.array(buffers[0]).view('int8'))
    155         copy_array(arrow_dev_array, mask_dev_array)
    156         pamask = Buffer(

~/anaconda3/lib/python3.7/site-packages/librmm_cffi/wrapper.py in to_device(self, ary, stream, copy, to)
    239         if to is None:
    240             to = self.device_array_like(ary, stream=stream)
--> 241             to.copy_to_device(ary, stream=stream)
    242             return to
    243         if copy:

~/anaconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    223     def _require_cuda_context(*args, **kws):
    224         with _runtime.ensure_context():
--> 225             return fn(*args, **kws)
    226 
    227     return _require_cuda_context

~/anaconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py in copy_to_device(self, ary, stream)
    196                 copy=not ary_core.flags['WRITEABLE'])
    197             check_array_compatibility(self_core, ary_core)
--> 198             _driver.host_to_device(self, ary_core, self.alloc_size, stream=stream)
    199 
    200     @devices.require_context

~/anaconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in host_to_device(dst, src, size, stream)
   1894         fn = driver.cuMemcpyHtoD
   1895 
-> 1896     fn(device_pointer(dst), host_pointer(src, readonly=True), size, *varargs)
   1897 
   1898 

~/anaconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    292             _logger.debug('call driver api: %s', libfn.__name__)
    293             retcode = libfn(*args)
--> 294             self._check_error(fname, retcode)
    295         return safe_cuda_api_call
    296 

~/anaconda3/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    327                     _logger.critical(msg, _getpid(), self.pid)
    328                     raise CudaDriverError("CUDA initialized before forking")
--> 329             raise CudaAPIError(retcode, msg)
    330 
    331     def get_device(self, devnum=0):

CudaAPIError: [1] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

**Comment by vrushang25** [comment]
> @vrushang25 what do you mean you're not getting output for the `cudf.read_csv`? Is `M` not a `cudf.DataFrame` after the call in your example above?

Can you please help me ? is it reason due to the improper installation in anaconda? my versino is 0.6.1+0.gbeb4ef3.dirty

Thank you.

**Comment by vrushang25** [comment]
I solved this problem by just updating my nvidia drivers now it's working very well. 

Thank you so much for the support
