### ISSUE TITLE
[FEA] libcudf binary operations should use `thrust::transform`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3633]
**Is your feature request related to a problem? Please describe.**

Currently, libcudf binary operations (including the [libcudf++ implementation](https://github.com/rapidsai/cudf/pull/3507/files#diff-8e311b70b900e85bad5f9e753321885bR38)) make use of a custom kernel to perform the operation.

These should really instead make use of a [`thrust::transform`](https://thrust.github.io/doc/group__transformations_gacca2dd17ae9de2f7bcbb8da6d6f6fce4.html#gacca2dd17ae9de2f7bcbb8da6d6f6fce4) (variant with 2 inputs).

The reason is so that we can take advantage of any optimizations that the Thrust kernels may have (such as vectorized load/stores).

**Describe the solution you'd like**

Update the binary ops implementation to use `thrust::transform`. 

**Additional context**
This will require Jitifying Thrust code, which may be tricky.

**Comment by harrism** [comment]
From talking to @trxcllnt his Jitify experiments with Thrust and column_device_view/string view haven't panned out. So we think it's best to do non-JIT implementations of string comparison operators, since it's a small set.  So I don't want to make this issue a requirement for 0.12

**Comment by jrhemstad** [comment]
> So we think it's best to do non-JIT implementations of string comparison operators to resolve #3651 , since it's a small set. So I don't want to make this issue a requirement for 0.12

Since that is going to require a custom code path, and it's not going to be JIT'd, then why not use the `thrust::transform` approach? Otherwise you're going to have to write 4 new kernels for the combination of lhs/rhs being a string column/scalar. In contrast to a single `thrust::transform` that uses iterators for the lhs/rhs.

**Comment by trxcllnt** [comment]
@jrhemstad that's the approach I've taken in https://github.com/rapidsai/cudf/pull/3657 (except restricted to `string_view` types so it doesn't explode compile times).

**Comment by harrism** [comment]
Fixed by #3657. @jrhemstad if there is work remaining / unfixed, please comment and reopen.
