### ISSUE TITLE
[BUG] dask_cudf cannot set_index with sorted=True

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#3634]
I'm trying to make use of pre-sorted data to avoid a slow distributed sort. Unfortunately trying to set_index on a pre-sorted column fails with dask_cudf.

From tip of branch-0.12, and master of both dask and distributed:
```
import dask_cudf, cudf

df = cudf.DataFrame({'val': [4, 3, 2, 1, 0], 'id': [0, 1, 2, 3, 4]})
ddf = dask_cudf.from_cudf(df, npartitions=2)

ddf.set_index('id', sorted=True)
```
Trace:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-19-743f0f77571b> in <module>
      4 ddf = dask_cudf.from_cudf(df, npartitions=2)
      5 
----> 6 ddf.set_index('id', sorted=True)
      7 #ddf.set_index('id')

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf/core.py in set_index(self, other, **kwargs)
    174                 % kwargs["shuffle"]
    175             )
--> 176         return super().set_index(other, shuffle="tasks", **kwargs)
    177 
    178     def reset_index(self, force=False, drop=False):

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in set_index(***failed resolving arguments***)
   3519 
   3520             return set_sorted_index(
-> 3521                 self, other, drop=drop, divisions=divisions, **kwargs
   3522             )
   3523         else:

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/shuffle.py in set_sorted_index(df, index, drop, divisions, **kwargs)
    649 
    650     if not divisions:
--> 651         divisions = compute_divisions(result, **kwargs)
    652     elif len(divisions) != len(df.divisions):
    653         msg = (

/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/shuffle.py in compute_divisions(df, **kwargs)
    669     mins = df.index.map_partitions(M.min, meta=df.index)
    670     maxes = df.index.map_partitions(M.max, meta=df.index)
--> 671     mins, maxes = compute(mins, maxes, **kwargs)
    672 
    673     if (

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
    436     results = schedule(dsk, keys, **kwargs)
--> 437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 
    439 

/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py in <listcomp>(.0)
    435     postcomputes = [x.__dask_postcompute__() for x in collections]
    436     results = schedule(dsk, keys, **kwargs)
--> 437     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    438 
    439 

/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf/core.py in finalize(results)
     46 
     47 def finalize(results):
---> 48     return cudf.concat(results)
     49 
     50 

/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/reshape.py in concat(objs, axis, ignore_index, sort)
     84         return Index._concat(objs)
     85     else:
---> 86         raise ValueError("Unknown type %r" % typ)
     87 
     88 

ValueError: Unknown type <class 'int'>
```

**Comment by kkraus14** [comment]
Looks like this is because it expects to use `cudf.concat` to handle an integer returned from a min and max call on each partition. @mrocklin @rjzamora any thoughts on how we should handle this situation? Copying these to the GPU doesn't sound like the right behavior here nor does even using `pd.concat` as we want it as a tuple afterwards: https://github.com/dask/dask/blob/master/dask/dataframe/shuffle.py#L664

**Comment by rjzamora** [comment]
Thanks @kkraus14 - I'm loooking into this.  

My intuition is to convert the tuple of scalars into a pandas series within the `finalize` function if the results do not contain Series of Dataframe objects.  Dask is expecting a pandas series here to calculate the divisions. I agree that we probably dont want to copy the mins/maxes back to the GPU -- I'll update here if I run into issues

**Comment by kkraus14** [comment]
> Thanks @kkraus14 - I'm loooking into this.
> 
> My intuition is to convert the tuple of scalars into a pandas series within the `finalize` function if the results do not contain Series of Dataframe objects. Dask is expecting a pandas series here to calculate the divisions. I agree that we probably dont want to copy the mins/maxes back to the GPU -- I'll update here if I run into issues

My understanding is at this point it converts the list to a Pandas Series then immediately converts that Pandas Series to a tuple. This is really expensive in the GPU programming world and would be better if we could avoid round tripping through a Pandas Series, but I'd defer to your judgement.

**Comment by rjzamora** [comment]
> This is really expensive in the GPU programming world and would be better if we could avoid round tripping through a Pandas Series, but I'd defer to your judgement.

Right - There is no need to convert to a pandas Series - The divisions logic can handle the tuple as is.  I just meant to say that we don't need to (and shouldn't) be converting the mins/maxes into a cudf Series/DataFrame (which was probably obvious to you :) - sorry).
