### ISSUE TITLE
[DOC] error in example code in cuDF Docs, Dataframes section

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3638]
## Report incorrect documentation

**Location of incorrect documentation**
Example code on https://rapidsai.github.io/projects/cudf/en/0.11.0/api.html#cudf.core.dataframe.DataFrame is incorrect and throws an error.

```
>>> t0 = datetime.strptime('2018-10-07 12:00:00', '%Y-%m-%d %H:%M:%S')
>>> n = 5
>>> df = cudf.DataFrame({
>>>   'id': np.arange(n),
>>>   datetimes', np.array([(t0+ timedelta(seconds=x)) for x in range(n)])
>>> })
>>> df
```

needs to change the "," to a ":" for the statement to work
**'datetimes', np.array**([(t0+ timedelta(seconds=x)) for x in range(n)])
to
**'datetimes': np.array**([(t0+ timedelta(seconds=x)) for x in range(n)])

I'll create a commit for it and merge it in with my existing PR https://github.com/rapidsai/cudf/pull/3618

**Comment by kkraus14** [comment]
Fixed in #3618
