### ISSUE TITLE
[QST] Does dask and rapids a competitor of Apache Spark?

### ISSUE THREAD

**Issue by cfangplus** [rapidsai/cudf#3643]
Hi,
I am an Apache Spark developer and these days I was told tools called NV Rapids cudf, cuml and cuGraph.
I know that dask overcomes the disadvantage of Pandas/Scikit-Learn and extends python developer to develop their project in distributed mode. Now I have a questions as follow,
Combined with dask and rapids modules like cuDF, cuML, cuGraph, does it mean that Python ecosystem own its solution that is comparable with Apache Spark? 
Or does it means that developer with GPU could develop bigdata application(including data proessing and machine learning) without Apache Spark? Also, are there any features NV Rapids need to be added?

**Comment by datametrician** [comment]
@cfangplus, just my opinions here, but we never want to "replace" Apache Spark (in fact, we have a team working on adding GPU support to Spark as well).  It does give yet another option. For people who prefer the PyData APIs, and want to use GPUs end to end for ETL, ML, Graph, Streaming, Signal Processing, Array Processing, or Geospatial Applications... we want to make that really easy. For people who prefer Java/Scala, we want them to continue to do that with GPU support in the future.  Both Spark and Dask run on Yarn/K8s/Slurm/etc... and the goal is to build more bridges and fewer walls.

We're far from feature complete. Please check https://docs.rapids.ai/overview for where we are today, and we will have new updates for 0.11 there soon.

Also please try RAPIDS, many large companies are using it and helping us make it better.  Our RAPIDS Medium, https://medium.com/rapids-ai, has many blogs from people around the world.

**Comment by datametrician** [comment]
I'm going to close this issue, but feel free to ask any other questions here or elsewhere, and welcome!

**Comment by cfangplus** [comment]
Great thanks @datametrician
