### ISSUE TITLE
[BUG] cudf::strings::create_offsets() does not work correctly for columns with a non-zero offset.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#3644]
For input columns that have a non-zero offset (a typical example being something that has come from slice() or split()), the returned device_vectors end up representing a double offset. Specifically, for column A with internal offset X, the offsets device vector will return the offsets column starting at offset[X], but the chars device vector will also start offset an equivalent # of chars Y into the char data.  So when a user uses the two together, they end up doubling their offset.

```
// what you would expect
ptr = &chars[0] + offsets[X]

// what you get
ptr = &chars[Y] + offsets[X];

// values from repro code below
chars.offset() -> 6
offsets.offset() -> 2
offsets[2] -> 6
```

I believe the issue here is this line of code

```
auto d_chars = strings.chars().data<char>();
```
One possible fix would be to just use `head` instead of `data`. 

**Steps/Code to reproduce bug**
Easiest way to reproduce is to do a split() on a string column and then cudf::test::print().  The following code will do it

```
  std::vector<std::string> strings = {"this", "is", "a", "column", "of", "strings"};
  cudf::test::strings_column_wrapper sw = { strings.begin(), strings.end() };                                                
  auto col = sw.release();
  std::vector<cudf::size_type> splits{ 2 };
  auto result = cudf::experimental::split(*col, splits);
  for(size_t idx=0; idx<result.size(); idx++){     
     cudf::test::print(result[idx]);
     printf("\n");
  }
```

Expected
```
this,is
a,column,of,strings
```

Actual
```
this,is
n,ofstri,ng,s
```

**Comment by rgsl888prabhu** [comment]
There are two issues

1.  byte size being calculated in `cudf::strings::create_offsets` in [line](https://github.com/rapidsai/cudf/blob/e8992c789d1a5f5a16e2337e7506afb4d4d45c6a/cpp/src/strings/strings_column_view.cu#L160) takes last offset value, which is actually size of the main string_column and not of the slice, so it would require some change as below
```
size_type bytes = thrust::device_pointer_cast(d_offsets)[count]-thrust::device_pointer_cast(d_offsets)[0];
``` 
but if #3652 gets added then we can replace this with directly the host value.

2.  In `cudf::test::to_host` while creating the host data, the first offsets gets added to already offset char array, which results in wrong output. The issue in [line](https://github.com/rapidsai/cudf/blob/e8992c789d1a5f5a16e2337e7506afb4d4d45c6a/cpp/tests/utilities/column_utilities.hpp#L132).

Fix for this issue
```
auto initial_offset = h_offsets[0];
    for( size_type idx=0; idx < c.size(); ++idx )
    {
        auto offset = h_offsets[idx];
        auto length = h_offsets[idx+1] - offset;
        host_data.push_back(std::string( h_chars.data()+offset-initial_offset, length));
    }

```
