### ISSUE TITLE
[BUG] cudf::strings::print() does not work correctly for columns with a non-zero offset.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#3645]
Bug is identical to https://github.com/rapidsai/cudf/issues/3644 except it manifests directly in cudf::strings::print() via a similar mechanism as the one in cudf::strings::create_offsets()

Repro steps are similar

```
  std::vector<std::string> strings = {"this", "is", "a", "column", "of", "strings"};
  cudf::test::strings_column_wrapper sw = { strings.begin(), strings.end() };                                                
  auto col = sw.release();
  std::vector<cudf::size_type> splits{ 2 };
  auto result = cudf::experimental::split(*col, splits);
  for(size_t idx=0; idx<result.size(); idx++){     
     cudf::strings::print(result[idx]);

     // this function uses cudf::strings::create_offsets() which has a similar issue
     // cudf::test::print(result[idx]);

     printf("\n");
  }
```

Fix appears to be similar

```
auto d_strings = strings.chars().data<char>();
```

Should probably just be `head`.   Although it probably makes sense to refactor so that both cudf::test::print() an cudf::strings::print() are going through the same common code.

**Comment by jrhemstad** [comment]
I don't think `cudf::strings::print` needs to exist. There should only be `cudf::test::print`.
