### ISSUE TITLE
Linear Algebra Support (BLAS etc) in Rapids

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cudf#365]
## Feature request / Question

I'd like to be able to perform some linear algebra on data. This is what I'm trying to do. I am passing a 2x2 convolution filter across LiDAR data in strides of 1 to calculate angles and direction. A 2nd wrapping convolution is run against this to find all triangles by wrapping all combinations of 3 adjacent point around the perimeter..

The aim is to estimate the angle and main direction of slope in a grid square. It's not only for ground but also measuring roof angle of slope.

So what I come up with, for an insurance company, is a profile of the shape of a building.

![figure_2](https://user-images.githubusercontent.com/8914493/48303031-17165b00-e4fd-11e8-974d-b9405296f50c.png)

![figure_2-1](https://user-images.githubusercontent.com/8914493/48303073-999f1a80-e4fd-11e8-86d2-f36377f274af.png)

I  am presently using Numpy, but it is very slow. The present code is shown below.

This is the first convolution function which acts on the grid square :

```
def max_slope(p):
    if np.any(np.isnan(p)):
        return np.nan
    s = nd.generic_filter(p, slope, size=3,mode='wrap')
    if np.all(np.isnan(s)):
        return np.nan
    return np.nanmax(s)
```

This is the 2nd convolution function which normalises the plane vectors and calculates the angle by taking arc cosine of the 3rd moment.

```
import numpy as np
import scipy.ndimage as nd

def slope(p):
    p1 = np.array([0,0,p[0]])
    p2 = np.array([0,1,p[1]])
    p3 = np.array([1,1,p[2]])
    v1 = p2 - p1
    v2 = p2 - p3
    cp = np.cross(v1,v2)
    return (180.0*np.arccos(abs((cp / np.linalg.norm(cp))[2]))/np.pi)
```

np.nan is used as no data value in the grid after the building outline polygon is applied as a path to exclude points outside.

One problem is that Rapids kernel, and Numba JIT functions don't allow numpy arrays to be created inside the function which are essential for the linear.

I think it would be useful, for many applications, to be able to perform linear algebra in Rapids. Could it be linked to CuBLAS possibly? I can see the tools I need in Pyculib https://pyculib.readthedocs.io/en/latest/cublas.html but I can't see a way of implementing them within a kernel function due to the array constraint.

**Comment by harrism** [comment]
I provide the following in the hopes of keeping you making progress on your problems, since your request is likely a longer-term feature request. 

I understand that your request is likely more general, but in the example you give the linear algebra is really simple since it's just 3D vectors -- cuBLAS is likely overkill. (Note that Numba does expose cuBLAS interfaces) 

With some back of the envelope jotting you can easily simplify `slope(p)` to a function without any Numpy arrays, and you can reduce the arithmetic by several operations by working out the cross product and noting that the third component of the cross product is 1.

```
def slope(p):
    x = p[1] - p[2]
    y = p[0] - p[2]
    length = np.sqrt(x*x + y*y + 1)
    return (180.0 * np.arccos(abs(1.0 / length)) / np.pi)
```

This is untested, I may have made a mistake. But you should be able to correct it.

**Comment by harrism** [comment]
@MurrayData was this at all helpful? Are you unblocked?

**Comment by MurrayData** [comment]
Thank you @harrism. My GitHub account was locked out due to a hacking attempt. Yes, I'll give that a try. I'm a bit rusty on the pure maths these days (digs out University Linear Algebra text book)

**Comment by kkraus14** [comment]
Going to close this as the question was answered.
