### ISSUE TITLE
[FEA] negative windows in rolling

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3650]
**Is your feature request related to a problem? Please describe.**
In Spark it is possible to request a window that does not include the current row.  So for example I may want the MAX of the 5 entries just before the current one.  In that case I could set the preceding window to 5 and the following window to -1. Currently in cudf this fails with an std::logic_error. But if I explode them out into columns it works. It also looks like if I just apply the following patch I get what I want.

```diff
diff --git a/cpp/src/rolling/rolling.cu b/cpp/src/rolling/rolling.cu
index e991abf46..34d7f31fb 100644
--- a/cpp/src/rolling/rolling.cu
+++ b/cpp/src/rolling/rolling.cu
@@ -292,8 +292,8 @@ std::unique_ptr<column> rolling_window(column_view const& input,
                                        rolling_operator op,
                                        rmm::mr::device_memory_resource* mr)
 {
-  CUDF_EXPECTS((preceding_window >= 0) && (following_window >= 0) && (min_periods >= 0),
-               "Window sizes and min periods must be non-negative");
+  CUDF_EXPECTS(min_periods >= 0,
+               "Min periods must be non-negative");
 
   auto preceding_window_begin = thrust::make_constant_iterator(preceding_window);
   auto following_window_begin = thrust::make_constant_iterator(following_window);

```

We are likely going to use a different API for most rolling windows operations, but there are some cases where we might want to fall back to using this one, and it would be helpful to have this supported. 

**Describe the solution you'd like**
I would love to have a patch that lets me use a negative value for window ranges

**Describe alternatives you've considered**
We could just use fill to explode it out to a column and use that instead, but it feels like a bit of a waste.

**Comment by harrism** [comment]
I think we should just generalize to accept negative windows but it requires more changes. We have to ensure that we swap the start and end index of the window if they are out of order to make sure the window iteration works correctly.  So in addition to removing the CUDF_EXPECTS, this code:

https://github.com/rapidsai/cudf/blob/a75e9df3d8dcb9a4d827bd011b4e0796c9415daf/cpp/src/rolling/rolling.cu#L86-L88

Would change to:

```
// compute bounds
size_type start = max(0, i - preceding_window);
size_type end = min(input.size(), i + following_window + 1); 
// swap if start > end
size_type start_index = min(start, end);
size_type end_index = max(start, end);
```

Tests would need to be updated.

**Comment by harrism** [comment]
I'm going to make this change as part of my already open (and waiting on dependencies) PR #3601 since I'm about to leave for a month vacation.
