### ISSUE TITLE
[FEA] Support string comparisons in binary ops

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#3651]
**Is your feature request related to a problem? Please describe.**
Binary ops were ported to libcudf++ APIs but without support for string column-column and column-scalar comparisons (<, >, <=, >=, ==, !=). This should be added.

**Comment by jrhemstad** [comment]
This could/should be done at the same time as https://github.com/rapidsai/cudf/issues/3633 using iterators for the columns that call the `element` method.

**Comment by harrism** [comment]
Fixed by #3657. @trxcllnt if I am incorrect in closing this, please reopen or comment.
