### ISSUE TITLE
[FEA] Compute size of chars child column in a strings_column_view() when performing a slice.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#3652]
Related to null_count() computation work being done in https://github.com/rapidsai/cudf/issues/3600

Currently, when a string column is sliced, the size of the chars child column is not updated on the CPU. This makes sense because you have to reach into gpu memory to check the offsets column to get the info and slice is a cheap cpu-side operation.

The strings implementation of contiguous_split() needs to be able to compute a buffer size that includes the chars child subcolumn in a fast way, at scale. Currently, you can get this info on the cpu by calling strings_column_view.chars() - however that function ends up reading device memory directly to get the info. This will not be fast enough for the scale that contiguous_split() wants to run at (potentially hundreds of thousands of columns).

If we change slice() to compute null counts in a kernel (https://github.com/rapidsai/cudf/issues/3600) it  might also make sense to add code that computes the overall size of the chars child column in the case of a strings_column_view.

This would also allow strings_column_view.chars() to become "free" instead of having a silent performance hit synchronizing with the GPU.

**Comment by davidwendt** [comment]
`strings_column_view.chars()` not longer reads device memory
