### ISSUE TITLE
[BUG] libcudf++ ORC reader incorrectly casts timestamps

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3658]
**Describe the bug**
The ORC reader based on libcudf++ does not read timestamps correctly when asking to convert timestamps to either `TIMESTAMP_MILLISECONDS` or `TIMESTAMP_MICROSECONDS`.

**Steps/Code to reproduce bug**
Read an ORC file with a timestamp column, specifying either `TIMESTAMP_MILLISECONDS` or `TIMESTAMP_MICROSECONDS` for the `timestamp_type` field in `read_orc_args`.  The values are not scaled as expected when compared to loading the data with `TIMESTAMP_NANOSECONDS` or `TIMESTAMP_SECONDS`.

**Expected behavior**
Reading timestamps with `timestamp_type` = `TIMESTAMP_MICROSECONDS` should return  values that are 1/1000 the value returned by reading with `TIMESTAMP_NANOSECONDS`. 
Reading with `timestamp_type` = `TIMESTAMP_MILLISECONDS` should return values that are 1/1000 the value returned by reading with `TIMESTAMP_MICROSECONDS`.

**Comment by jlowe** [comment]
This appears to have been broken in commit 80c285bca960fcf957431fa6c8ad6e732384788e where for some reason the scaling of `TIMESTAMP_MILLISECONDS` and `TIMESTAMP_MICROSECONDS` were flipped in the `to_clockrate` method.
```patch
diff --git a/cpp/src/io/orc/reader_impl.cu b/cpp/src/io/orc/reader_impl.cu
index 45b67e4b1..2a6ab940b 100644
--- a/cpp/src/io/orc/reader_impl.cu
+++ b/cpp/src/io/orc/reader_impl.cu
@@ -99,9 +99,9 @@ constexpr int32_t to_clockrate(type_id timestamp_type_id) {
   switch (timestamp_type_id) {
     case type_id::TIMESTAMP_SECONDS:
       return 1;
-    case type_id::TIMESTAMP_MILLISECONDS:
-      return 1000;
     case type_id::TIMESTAMP_MICROSECONDS:
+      return 1000;
+    case type_id::TIMESTAMP_MILLISECONDS:
       return 1000000;
     case type_id::TIMESTAMP_NANOSECONDS:
       return 1000000000;
```
This change deviated the `to_clockrate` behavior from the correctly functioning version in the legacy implementation at cpp/src/io/orc/legacy/orc_reader_impl.cu.

**Comment by OlivierNV** [comment]
Yup, looks like an unintended typo/copy-paste issue - this should match between legacy and libcudf++ path. No vpn, so can't start a PR from here, but the fix is basically in the above comment (just swapping the milliseconds/microseconds switch statements)
