### ISSUE TITLE
[FEA] With CuDF, how do you read parquet partitions?

### ISSUE THREAD

**Issue by RXY3832** [rapidsai/cudf#3660]
**What is your question?**
I have partitioned parquet files and while I'm able to read them in, I don't get the column by which the partitions were done. So, for example, restid is the name of the column used to create the partitions. But after reading in the files, restid is not in the finale dataframe. How do I keep it in there? 

Thanks,
Rocky

**Comment by RXY3832** [comment]
Need to include a way to load parquet files from partitions.

**Comment by kkraus14** [comment]
@RXY3832 You can read specific row groups using the API: https://rapidsai.github.io/projects/cudf/en/0.11.0/api.html#cudf.io.parquet.read_parquet, otherwise if you wanted to read a specific partition from a parquet directory, you can read the specific file in the directory.
