### ISSUE TITLE
[BUG] replace_multi slower than chained calls to replace when regex=True

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3665]
Calling `multi_replace` is significantly slower than the chaining "equivalent" replace calls (the behavior isn't exactly the same due to what happens if multiple replace patterns would match a given character, but they are quite similar).

The discrepancy gets **significantly** larger as the length of the strings increases.

Length 50 strings

```python
import string
import numpy as np
import nvstrings
​
allchars = string.ascii_letters
​
def genstring(n=5):
    return ''.join(np.random.choice(list(allchars), n))
​
def gensent(nsent=5, token_per_sent=5):
    return nvstrings.to_device([genstring(token_per_sent) for x in np.arange(nsent)])
​
s = gensent(nsent=100000, token_per_sent=50)
for x in s[:3].to_host():
    print(x, '\n')
TEyiozlzDAOQwaMnCPDnXHztuNvaQcNyJnLSPUYkXkwVBhqYhw 

mYpACkGqwmbxbPongkwhpuYIHtHFgEpHypCOZjHWARPzZVFMNQ 

jzybxswQiwBXoHXduLBqdOsAwvdCrngRQTfufiYgpnxoSLRNdP 
```

```python
%%time
srm = s.replace_multi(
        ["a", "b"],
        ["q", "r",],
    )
CPU times: user 13.6 ms, sys: 13.1 ms, total: 26.6 ms
Wall time: 25.7 ms

%%time
sr = (s
    .replace('a', 'b')
    .replace('q', 'r')
           )
CPU times: user 506 µs, sys: 8.63 ms, total: 9.13 ms
Wall time: 22.2 ms
```

Length 500 strings.

```python
s = gensent(nsent=100000, token_per_sent=500)
for x in s[:3].to_host():
    print(x, '\n')
VPprUVvQhfYJTvTWCuOhohlDskGYrnsnwqLAEvBYgyHiHugeORjWBJkuXxopVKLxMegHktkWsCjDahpxiBqMHUeyoLNbGgwouNxtuDepBcwktAwnknDYUDqiaPShvNngoTRmwWggRDPGEzPfWjeqFnMnkJAtLZmijkcQxKvAupcRUtrbpSzuIPMQeXnnzeGDDodvznMFvrpfTBnadJovwrbsyMdQoFqadFgevAhCYrcLXUyuUhQmdsxyiIRVXspsQRIqPpBJiWRUCKRpanIYtkHSSyFTvjDjemVmCZphkiIGfDaDyuMPKaPftdWszxXfkGFVrdtgookIwPpkebwMquwllrLSCDnxJSXphXwnNTfNABxnKwzwPbeSNCNbnGFQBxIeAHHxQmHPNllAgxhXTkFjgTkXUKUftHVGjQIXdtAeYFTwcpAoIkwWCGuThjHWUOVOmIhAsBRyQzjyWOnMiAaJVEoeQNlVJOCajcaHrWvrvifvLvcc 

oOMclyBDpPWgzYojmXiddgVthZVQtBNjqjkihhKnJfWIeSZPtZihkXRCmAKcqKnlegtyZfqZyOZoNNqtloekovZFfAUaMmkcpueeanIpyiVGcEstRDoWsUGdKkCcYarlJuRNftUtZUBpPFncdWJKmjOCfpZsyPnRoSeRFKJqfjplFpumIgOtrSyWWjAFbYaLDQtcRwdNuvcTlUokuYRoWzBzEuyCjuxysjcAcBMxwqECnHxczMEHURJkGIKUafpCrwIHVJBJsgotYOMrYRALHtclDFMiNOUuxSVkXWOIPvfHfwZhuxkTTskMoIgNICRFYNvZekgudllxZapnCryfnYTIiJSMlDTXHWvMKHhJgVJtqAQaGbeWLXMhEkAbDBNjjQgkuoxopKSqaFDuVZxJdKQaYxPWSuOePAKymuUtOGEKoqQUwXYFeaAQKXyVVlNPEIJGqJOIEHeScnkoVnPJduVJfYmEptntOOOwumiMItEPpfoYHwIj 

tvwEuNsIuOSPOtspNtvmHNcUBXhNFjZPJsYbnMOJIHtTCCVFPgrZFyQaFuVvOzSVfrxPcNVDqqMzipxerHpFrxyKLKEFYNmcWKIYfXpKPhkPthfguzGTadIIRkvZGEUrJaZbBvfIANeUXSAMgBcKreAHAViKyMuDzKfkzBFFplTeqtcarxNDKGwQEWpzHIxSZXafAAKezemwLQxTbyQkUNkgDVtVkegwwvNhsCpmYaVItZIFhITZECxIUKtdhskUMQOPbjDyXBrVWNVvdkaXKCObUlzslzdJXENSnrlLZymkjbgPBYIgGwFUPXpVDmdmUGrYLNFbuVRfQXbBWdVFRYYAyAIrdwyxRcpJfFVXYbsLAEOZoPGJsghRzwHAoLHwAohDcXDVMLekbVrbHVwhyfDdmdjGzkechxgnQPHnOCKZrevgHvRhINmMhDaETTCqxVOtlNELudeQZmkRQYsLkBrXNfGmzMFtMymgbdeQiYljBAriVPxr 
```

```python
%%time
srm = s.replace_multi(
        ["a", "b"],
        ["q", "r",],
    )
CPU times: user 4.49 s, sys: 3.43 s, total: 7.92 s
Wall time: 8.04 s

%%time
sr = (s
    .replace('a', 'b')
    .replace('q', 'r')
           )
CPU times: user 26 ms, sys: 12.6 ms, total: 38.6 ms
Wall time: 37.8 ms
```

**Comment by davidwendt** [comment]
Not that it matters for this issue but the following two lines are **_not_** equivalent.
```
srm = s.replace_multi( ["a", "b"], ["q", "r",]  )
sr = (s.replace('a', 'b').replace('q', 'r'))
```
The first one (`srm`) replaces `a` with `q` and `b` with `r` while the second one (`sr`) replaces `a` with `b` and `q` with `r`. The first parameter for `replace_multi` is the list of strings to search for replacing. If a string is found, the corresponding string from the second parameter is used for the replacement. To make it equivalent to the chained version it should be called as follows:
```
srm = s.replace_multi( ["a", "q"], ["b", "r",]  )
```

The default for both `replace` and `replace_multi` is `regex=True`. If you pass `regex=False` then both the chained `replace` and `replace_multi` here would be faster (around 22ms for both on my machine).

For the case of `replace_multi` with `regex=True` the list of strings in the first parameter are treated as regex patterns and compiled individually before launching the kernel.

But given that `regex=True` is also the default for `replace` then it is still curious why chaining the calls would be significantly faster. Looks like the regex version of replace-multi needs some work.

**Comment by beckernick** [comment]
Yep, that's a typo. Thanks @davidwendt . Sloppiness on my part while making this toy example. Thanks for verifying that the `regex=False` scenario is behaving as expected (just reconfirmed on my machine as well). Good to see that.

Investigating the regex version of multi-replace sounds like the next step, so I'll update the title of this issue to reflect that.
