### ISSUE TITLE
[FEA] Alias kurtosis as kurt

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3674]
For pandas API compatibility, we should add an alias `kurt` for our `kurtosis` method. Until we have a libcuDF implementation, we can do it just like the following:

https://github.com/rapidsai/cudf/blob/633e9325f7ffdd21826f4e7f6e33e9abaa25279d/python/cudf/cudf/core/series.py#L1297-L1300

**Comment by galipremsagar** [comment]
Fixed by #4645
