### ISSUE TITLE
[FEA] Series and DataFrame mode

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3677]
Following up on the `median` implementation, it would be nice to also have `mode` to help round out our distributional descriptive statistics (like [pandas](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.mode.html)). The [mode](https://en.wikipedia.org/wiki/Mode_(statistics)) is the most common value in the data.

**Comment by argenisleon** [comment]
Hi @beckernick,

Any plan to add this?
