### ISSUE TITLE
make pytest fails - "ImportError: cannot import name 'ffi'

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#368]
Hardware: amd64 CPU, ~ 16 GB RAM, EVGA GTX 1050 Ti 4 GB device mem. 
Software: Devuan ASCII (~= Debian Stretch), Linux kernel 4.9.0-8; CUDA 9.2; driver version 410.73; cudf master branch, commit cf87857a38a4e8ef71549d118bf3c18695b73877

When I build `libgdf` and run `make pytest` (from the `libgdf/build` directory), I get:
```
Traceback (most recent call last):
  File "/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/_pytest/config/__init__.py", line 381, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/mnt/sdb3/home-eyalroz/src/blazing/cudf/libgdf/python/tests')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/_pytest/config/__init__.py", line 412, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/mnt/sdb3/home-eyalroz/src/blazing/cudf/libgdf/python/tests/conftest.py')

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/_pytest/config/__init__.py", line 418, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 290, in load_module
    six.exec_(co, mod.__dict__)
  File "/mnt/sdb3/home-eyalroz/src/blazing/cudf/libgdf/python/tests/conftest.py", line 6, in <module>
    from . import utils
  File "/mnt/sdb3/home-eyalroz/src/blazing/cudf/libgdf/python/tests/utils.py", line 4, in <module>
    from libgdf_cffi import ffi, libgdf
ImportError: cannot import name 'ffi'
ERROR: could not load /mnt/sdb3/home-eyalroz/src/blazing/cudf/libgdf/python/tests/conftest.py

CMakeFiles/pytest.dir/build.make:61: recipe for target 'pytest' failed
```

- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the version or commit hash I am using for reference.
- [x] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by dantegd** [comment]
It seems that the `cffi` files are not in their proper location, did you run `make pytest` after the cffi generation steps? i.e. in the build directory, before `make pytest` you need to do all the steps: 

```cmake .. -DHASH_JOIN=ON -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
make -j install
make copy_python
python setup.py install```

**Comment by eyalroz** [comment]
@dantegd :Ah. Indeed, I haven't. But - typically (I mean, typically in other FOSS projects) - installation is not required to run tests.

Perhaps this could be checked - either within CMake or within the python script - with a more informative error message?

**Comment by harrism** [comment]
@dantegd you don't need to run make install or python setup.py install in order to run tests from the build directory, since the modules are copied into the build directory by `make pytest` (which depends on `make copy_python`). 
For me this works:

```
make -j
make pytest
```

**Comment by eyalroz** [comment]
@harrism : This is what didn't work for me (well, without the `-`j, I use the `MAKEFLAGS` environment variable).

And while I don't mind making those additions to `PYTHONPATH` and `LD_LIBRARYPATH` - I really shouldn't need to - `CMakeLists.txt` should take care of things for me.  At the very least it should tell me something like "XYZ not found in PYTHONPATH, please add it."

I should also mention I ran this from within the cudf conda environment, which is another point at which this stuff could be taken care of (maybe).

**Comment by eyalroz** [comment]
@harrism : "make test works fine" - Do you mean `make pytest`?

Now, indeed it could very well be something different on my setup. But "it works on the developer's favorite setup" is not really an answer... a setup is either good enough for building and testing, or CMake needs to complain about something in the configuration phase.

**Comment by harrism** [comment]
Yes, `make pytest`. My setup is achieved by following the readme (and I recently rebuilt my conda environment). My point is that I'm unable to reproduce the issue, and until we have a repro it's harder to take action.

Can you list all the commands you ran after creating the `libgdf/build` directory? Also please provide the complete output from `make pytest` and the path you ran it from.

BTW, we welcome pull requests for improvements such as the one you are suggesting.

**Comment by kkraus14** [comment]
@eyalroz is this resolved? There hasn't been activity on this in a while.

**Comment by eyalroz** [comment]
@kkraus14 : I don't know. `pytest` is no longer a Make target, and I don't quite see where these tests have gone.

**Comment by harrism** [comment]
@eyalroz the new process (without installing) would be:

```
make -j                                       # build libcudf
make python_cffi                      # build CFFI bindings for librmm.so, libcudf.so
$ cd python && py.test -v
```

Can you try that?

**Comment by eyalroz** [comment]
@harrism 
Running the second command, I get:
```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
CMakeFiles/python_cffi.dir/build.make:61: recipe for target 'PYTHON_CFFI' failed
```

**Comment by eyalroz** [comment]
@harrism 
This fails at the _second_ command (`make python_cffi`) with:
```
creating build/temp.linux-x86_64-3.5/cudf/bindings
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -m64 -fPIC -fPIC -I/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/numpy/core/include -I../cpp/include/ -I/home/eyalroz/miniconda2/envs/cudf/include/python3.5m -c cudf/bindings/cudf_cpp.cpp -o build/temp.linux-x86_64-3.5/cudf/bindings/cudf_cpp.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/numpy/core/include/numpy/ndarraytypes.h:1821:0,
                 from /home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                 from /home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from cudf/bindings/cudf_cpp.cpp:657:
/home/eyalroz/miniconda2/envs/cudf/lib/python3.5/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
cudf/bindings/cudf_cpp.cpp:659:18: fatal error: cudf.h: No such file or directory
 #include "cudf.h"
```

**Comment by eyalroz** [comment]
But to be honest - this is another bug already. @harrism : should we close this one and have me open another one for this new error message?

**Comment by mike-wendt** [comment]
@eyalroz I'd support a new bug and link it to this one if they are related.

**Comment by crmchan** [comment]
Dear @eyalroz @mike-wendt  
Is it resolved? any solution for it?
Thanks!

**Comment by crmchan** [comment]
Below is what I encountered with.

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_win32comgenpy.py", line
 47, in <module>
  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32com\__init__.py", line 5, in <module>
  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32ctypes\win32api.py", line 9, in <module>
  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32ctypes\pywin32\__init__.py", line 11, in <module>

  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32ctypes\pywin32\win32api.py", line 12, in <module>

  File "Lib\site-packages\win32ctypes\core\__init__.py", line 36, in load_module

  File "importlib\__init__.py", line 126, in import_module
  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32ctypes\core\cffi\_common.py", line 12, in <module
>
  File "D:\lib\site-packages\PyInstaller\loader\pyimod03_
importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\win32ctypes\core\cffi\_util.py", line 14, in <module>
ImportError: cannot import name 'FFI'
[7328] Failed to execute script pyi_rth_win32comgenpy
