### ISSUE TITLE
[BUG] Dask DataFrames groupby...apply

### ISSUE THREAD

**Issue by xiaonans** [rapidsai/cudf#3682]
**Describe the bug**
AttributeError occurs when I use groupby...apply to dask dataframe.

> AttributeError: 'SeriesGroupBy' object has no attribute 'apply'

**Steps/Code to reproduce bug**
`from dask.distributed import Client, wait`
`from dask_cuda import LocalCUDACluster`
`import dask_cudf`
`from cudf.datasets import timeseries, randomdata`
`cluster = LocalCUDACluster()`
`client = Client(cluster)`
`df = randomdata(nrows=1000, dtypes={'id':int, 'longitude':float})`
`ddf = dask_cudf.from_cudf(df, npartitions=5)`
`ddf.groupby(['id']).longitude.apply(lambda x: x+1, meta=float).compute()`

**Expected behavior**
Expected output is to be similar to the output of 
`df.groupby(['id'], method='cudf').apply(lambda x: x['longitude']+1)`

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - docker pull rapidsai/rapidsai-nightly:cuda10.0-runtime-centos7
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-nightly:cuda10.0-runtime-centos7

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     CentOS Linux release 7.7.1908 (Core)
     NAME="CentOS Linux"
     VERSION="7 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="7"
     PRETTY_NAME="CentOS Linux 7 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:7"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"
     
     CENTOS_MANTISBT_PROJECT="CentOS-7"
     CENTOS_MANTISBT_PROJECT_VERSION="7"
     REDHAT_SUPPORT_PRODUCT="centos"
     REDHAT_SUPPORT_PRODUCT_VERSION="7"
     
     CentOS Linux release 7.7.1908 (Core)
     CentOS Linux release 7.7.1908 (Core)
     Linux peDGX 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Jan  2 09:18:20 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: N/A      |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-DGXS...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   39C    P0    53W / 300W |   1910MiB / 32478MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
     | N/A   39C    P0    52W / 300W |   1058MiB / 32478MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                40
     On-line CPU(s) list:   0-39
     Thread(s) per core:    2
     Core(s) per socket:    20
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 79
     Model name:            Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:              1
     CPU MHz:               1204.547
     CPU max MHz:           3600.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              4397.53
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              256K
     L3 cache:              51200K
     NUMA node0 CPU(s):     0-39
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     
     ***g++***
     
     ***nvcc***
     
     ***Python***
     /opt/conda/envs/rapids/bin/python
     Python 3.6.7
     
     ***Environment Variables***
     PATH                            : /opt/conda/envs/rapids/bin:/opt/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin:/conda/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    conda-forge
     _tflow_select             2.1.0                       gpu
     absl-py                   0.9.0                    py36_0    conda-forge
     aiohttp                   3.6.2            py36h516909a_0    conda-forge
     arrow-cpp                 0.15.0           py36h090bef1_2    conda-forge
     astor                     0.7.1                      py_0    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     blas                      2.14                   openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py36_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.11.28               py36_0    conda-forge
     cfitsio                   3.470                hb60a0a2_2    conda-forge
     chardet                   3.0.4                 py36_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.12.0b191224          py36_510    rapidsai-nightly
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cugraph                   0.12.0a191223          py36_147    rapidsai-nightly
     cuml                      0.12.0a191223   cuda10.0_py36_328    rapidsai-nightly
     cupti                     10.0.130                      0
     cupy                      6.6.0            py36h809cb0f_1    conda-forge
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuspatial                 0.12.0a191223            py36_8    rapidsai-nightly
     cycler                    0.10.0                     py_2    conda-forge
     cython                    0.29.14          py36he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py36h516909a_0    conda-forge
     dask                      2.9.0                      py_0    conda-forge
     dask-core                 2.9.0                      py_0    conda-forge
     dask-cuda                 0.12.0a191223           py36_40    rapidsai-nightly
     dask-cudf                 0.12.0b191224          py36_510    rapidsai-nightly
     dask-glm                  0.2.0                      py_1    conda-forge
     dask-labextension         1.0.3                      py_0    conda-forge
     dask-ml                   1.1.1                      py_0    conda-forge
     dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.9.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     entrypoints               0.3                   py36_1000    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.8           py36h516909a_0    conda-forge
     fastrlock                 0.4             py36he1b5a44_1000    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     freexl                    1.0.5             h14c3975_1002    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     gast                      0.2.2                      py_0    conda-forge
     gdal                      2.4.3            py36h5f563d9_9    conda-forge
     geos                      3.7.2                he1b5a44_2    conda-forge
     geotiff                   1.5.1                hbd99317_7    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.58.3          py36h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     google-pasta              0.1.8                      py_0    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.23.0           py36he9ae1f9_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
     gstreamer                 1.14.5               h36ae1b5_0    conda-forge
     h5py                      2.10.0          nompi_py36h513d04c_101    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py36_1000    conda-forge
     idna_ssl                  1.1.0                 py36_1000    conda-forge
     importlib_metadata        1.3.0                    py36_0    conda-forge
     ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
     ipython                   7.3.0            py36h24bf2e0_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     jedi                      0.15.1                   py36_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     joblib                    0.14.1                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1            h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.2.0                    py36_0    conda-forge
     jupyter-server-proxy      1.2.0                      py_0    conda-forge
     jupyter_client            5.3.3                    py36_1    conda-forge
     jupyter_core              4.6.1                    py36_0    conda-forge
     jupyterlab                1.2.4                      py_0    conda-forge
     jupyterlab-nvdashboard    0.1.11                   pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kealib                    1.4.10            h58c409b_1005    conda-forge
     keras-applications        1.0.8                      py_1    conda-forge
     keras-preprocessing       1.1.0                      py_0    conda-forge
     kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
     krb5                      1.16.4               h2fd8d38_0    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libclang                  9.0.0           default_hde54327_4    conda-forge
     libcudf                   0.12.0b191224      cuda10.0_510    rapidsai-nightly
     libcugraph                0.12.0a191223      cuda10.0_147    rapidsai-nightly
     libcuml                   0.12.0a191223      cuda10.0_328    rapidsai-nightly
     libcumlprims              0.12.0a191223        cuda10.0_0    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libcuspatial              0.12.0a191223        cuda10.0_8    rapidsai-nightly
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 7.3.0                hdf63c60_2    conda-forge
     libgdal                   2.4.3                h2f07a13_9    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     liblapacke                3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libllvm9                  9.0.0                hc9558a2_3    conda-forge
     libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
     libnvstrings              0.12.0b191224      cuda10.0_510    rapidsai-nightly
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libpq                     11.5                 hd9ab2ff_2    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.12.0a191223       cuda10.0_80    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libspatialite             4.3.0a            h4f6d029_1032    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              7.3.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.33.1               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxgboost                1.0.0.SNAPSHOT       cuda10.0_1    rapidsai
     libxkbcommon              0.9.1                hebb1f50_0    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py36h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.1.1                      py_0    conda-forge
     markupsafe                1.1.1            py36h516909a_0    conda-forge
     matplotlib                3.1.2                    py36_1    conda-forge
     matplotlib-base           3.1.2            py36h250f245_1    conda-forge
     mistune                   0.8.4           py36h516909a_1000    conda-forge
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.2            py36hc9558a2_0    conda-forge
     multidict                 4.6.1            py36h516909a_0    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     nbconvert                 5.6.1                    py36_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.4                        py_0    conda-forge
     nodejs                    13.0.0               h10a4023_1    conda-forge
     nomkl                     2.0                           0
     notebook                  6.0.1                    py36_0    conda-forge
     nspr                      4.24                 he1b5a44_0    conda-forge
     nss                       3.47                 he751ad9_0    conda-forge
     numba                     0.46.0           py36hb3f55d8_1    conda-forge
     numpy                     1.17.3           py36h95a1406_0    conda-forge
     nvstrings                 0.12.0b191224          py36_510    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openblas                  0.3.7                he1df0ab_6    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     opt_einsum                3.1.0                      py_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py36hb3f55d8_1    conda-forge
     pandoc                    2.9.1                         0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.2                      py_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     patsy                     0.5.1                      py_0    conda-forge
     pcre                      8.43                 he1b5a44_0    conda-forge
     pexpect                   4.7.0                    py36_0    conda-forge
     pickleshare               0.7.5                 py36_1000    conda-forge
     pillow                    6.2.1            py36hd70f55b_1    conda-forge
     pip                       19.3.1                   py36_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pluggy                    0.12.0                     py_0    conda-forge
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                11.5                 hc63931a_2    conda-forge
     proj                      6.2.1                hc80f0dc_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt-toolkit            2.0.10                   pypi_0    pypi
     protobuf                  3.8.0            py36he1b5a44_2    conda-forge
     psutil                    5.6.7            py36h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     py-xgboost                1.0.0.SNAPSHOT   cuda10.0py36_1    rapidsai
     pyarrow                   0.15.0           py36h8b68381_1    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pynvml                    8.0.3                      py_0    conda-forge
     pyparsing                 2.4.5                      py_0    conda-forge
     pyqt                      5.12.3           py36hcca6a23_1    conda-forge
     pyqt5-sip                 4.19.18                  pypi_0    pypi
     pyqtwebengine             5.12.1                   pypi_0    pypi
     pyrsistent                0.15.6           py36h516909a_0    conda-forge
     pytest                    5.3.2                    py36_0    conda-forge
     python                    3.6.7             h357f687_1006    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.2              py36h516909a_0    conda-forge
     pyzmq                     18.1.1           py36h1768529_0    conda-forge
     qt                        5.12.5               hd8c4c69_1    conda-forge
     rapids                    0.12.0          cuda10.0_py36_11    rapidsai-nightly
     rapids-xgboost            0.12.0          cuda10.0_py36_1    rapidsai-nightly
     re2                       2019.12.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rmm                       0.12.0a191223           py36_80    rapidsai-nightly
     scikit-learn              0.22             py36hcdab131_1    conda-forge
     scipy                     1.4.1            py36h921218d_0    conda-forge
     seaborn                   0.9.0                      py_2    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                42.0.2                   py36_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     six                       1.13.0                   py36_0    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     statsmodels               0.10.2           py36hc1659b7_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     tensorboard               2.0.0              pyhb38c66f_1
     tensorflow                2.0.0           gpu_py36h6b29c10_0
     tensorflow-base           2.0.0           gpu_py36h0ec5d1f_0
     tensorflow-estimator      2.0.0              pyh2649769_0
     termcolor                 1.1.0                      py_2    conda-forge
     terminado                 0.8.3                    py36_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py36h516909a_0    conda-forge
     traitlets                 4.3.3                    py36_0    conda-forge
     typing_extensions         3.7.4.1                  py36_0    conda-forge
     tzcode                    2019a             h516909a_1002    conda-forge
     umap-learn                0.3.10                   py36_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     werkzeug                  0.16.0                     py_0    conda-forge
     wheel                     0.33.6                   py36_0    conda-forge
     wrapt                     1.11.2           py36h516909a_0    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.0.0.SNAPSHOT   cuda10.0py36_1    rapidsai
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.3.0           py36h516909a_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

**Comment by kkraus14** [comment]
cc @rjzamora Is this something that isn't implemented in Dask that would need to be implemented upstream?

**Comment by kkraus14** [comment]
cc @shwina this is also likely dependent on a big groupby refactor.

**Comment by thomcom** [comment]
It's implemented in `dask`, the issue is `cudf`s `SeriesGroupBy` class lacking the `.apply` fn. In order to use `apply` with `cudf` you have to create the groupby with `df.groupby(key, method="cudf")`, which isn't supported as a pass-through argument in dask.

I'm still investigating a workaround.

**Comment by ayushdg** [comment]
W.r.t the example provided above it would seem that the addition operation (without groupby) should work in this case. For this particular example of `groupby.apply`, this is the behavior shown by pandas:
```
df = cudf.DataFrame()
df['id'] = [1,2,3,1,1,2,3]
df['longitude'] = [0.5,0.6,0.7,0.8,0.9,1.0,1.1]
df.to_pandas().groupby(['id']).longitude.apply(lambda x: x+1)
```
```
0    1.5
1    1.6
2    1.7
3    1.8
4    1.9
5    2.0
6    2.1
Name: longitude, dtype: float64
```
`df['longitude_new'] = df['longitude'] + 1` should also produce the desired output:
```
>>> df['longitude_new']

0    1.5
1    1.6
2    1.7
3    1.8
4    1.9
5    2.0
6    2.1
Name: longitude_new, dtype: float64
```
---
*Other experiments:*

- Pandas Dataframe level apply:
```
>>> df.to_pandas().groupby(['id']).apply(lambda x: x['longitude']+1)
id   
1   0    1.5
    3    1.8
    4    1.9
2   1    1.6
    5    2.0
3   2    1.7
    6    2.1
Name: longitude, dtype: float64
```
Cudf/dask-cudf workaround:
```
df['longitude'] = df['longitude'] + 1
df['index'] = df.index
df.groupby(by=['id,'index']).longitude.min() #Can also be max/sum since only one element per group
```
```
id  index
1   0        1.5
    3        1.8
    4        1.9
2   1        1.6
    5        2.0
3   2        1.7
    6        2.1
Name: longitude, dtype: float64
```

- `method='cudf'` groupby apply
```
>>> df.groupby(by=['id'], method='cudf').apply(lambda x: x['longitude']+1)

0    1.5
1    1.8
2    1.9
3    1.6
4    2.0
5    1.7
6    2.1
Name: longitude, dtype: float64
```
This is inherently sorting by `id` but loses all index information in the result.

**Comment by xiaonans** [comment]
@ayushdg The 'code to reproduce bug' I attached is only a simplified demo of the real application. The actual code I am writing is 
`def sort(inp):`
    `    outp = inp.sort_values('longitude', ascending=True)` 

`ddf.groupby(['id']).apply(lambda x: x.sort_values('longitude', ascending=True))`

So I really need to use something like 'groupby...sort'. `df['longitude_new'] = df['longitude'] + 1` doesn't work for me.

**Comment by thomcom** [comment]
Hi @xiaonans ! Hopefully with the following line and @ayushdg's excelllent workaround, this suits your needs? Simply replace the last line in your above example with this:

`ddf.to_frame().reset_index().sort_values(by='id').head().to_pandas()`

The result of GPU groupby results will generally not be sorted. At the level of `cudf`, we provide a `sort` argument which allows you to get the result you're looking for. Unfortunately, just like `method`, this argument is not passed through `dask_cudf`. The line above implements your ask, I hope. :)

**Comment by ayushdg** [comment]
Hi @xiaonans, thanks for the additional context. In addition to what @thomcom mentioned as a solution another possibility that should work is changing the groupby call to something like: `ddf=ddf.groupby(by=['id','index']).agg({'longitude':'min'})`.

The difference in sorting behavior with dask-cudf groupby and the way the aggregation is called is outlined in #3319.

**Comment by xiaonans** [comment]
Thank @ayushdg and @thomcom for your greate support! That workaround solves the problem. :)

**Comment by xiaonans** [comment]
Hi @kkraus14 , the workaround provided by @ayushdg and @thomcom works fine with 10M samples on a dgx station. But when the dataset contains 7800M samples, sorting on the whole dataset instead of within a group is very time consuming. Is it possible to use daskcudf to sortvalues within a group?

**Comment by kkraus14** [comment]
@xiaonans It's not currently possible to sort values within a group as far as I'm aware. We're in progress of refactoring the Python groupby and adding additional aggregations at the C++ level so we'll see what we can do.

**Comment by vyasr** [comment]
The original example in this issue no longer throws an error on the current 22.08 branch now that the `apply` method exists:
```
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
import dask_cudf
from cudf.datasets import timeseries, randomdata

if __name__ == "__main__":
    cluster = LocalCUDACluster()
    client = Client(cluster)
    df = randomdata(nrows=1000, dtypes={'id':int, 'longitude':float})
    ddf = dask_cudf.from_cudf(df, npartitions=5)
    print(ddf.groupby(['id']).longitude.apply(lambda x: x+1, meta=float).compute())
```

Output:
```
$ python test.py  
2022-07-20 16:29:01,597 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-07-20 16:29:01,597 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
/home/vyasr/local/rapids/compose/etc/conda/cuda_11.5/envs/rapids/lib/python3.8/site-packages/dask/dataframe/core.py:6604: FutureWarning: Meta is not valid, `map_partitions` and `map_overlap` expects output to be a pandas object. Try passing a pandas object as meta or a dict or tuple representing the (name, dtype) of the columns. In the future the meta you passed will not work.
  warnings.warn(
705    0.911643
823    0.176986
606    0.098324
951    0.501098
395    0.339375
         ...   
273    0.360622
453    0.954584
880    0.354728
642    1.721207
961    1.135527
Name: longitude, Length: 1000, dtype: float64
```
