### ISSUE TITLE
libgdf join_test fails on MaxJoinTest - tries to allocate more than my GPU's global memory size

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#369]
Hardware: amd64 CPU, ~ 16 GB RAM, EVGA GTX 1050 Ti 4 GB device memory. 
Software: Devuan ASCII (~= Debian Stretch), Linux kernel 4.9.0-8; CUDA 9.2; driver version 410.73; cudf master branch, commit cf87857a38a4e8ef71549d118bf3c18695b73877

When I build `libgdf` and run `make test` (from the `libgdf/build` directory), the 4th test, `join_test`, fails. Full failure log is attached below, but the point is - the test attempts to allocate more memory than the GPU has free, or has at all - 8 GiB. It probably just doesn't check for the global memory size. This is particularly weird because a subsequent  test, which runs and succeeds, is named `InputTooLarge`. Perhaps the global memory size was hardcoded somehow?

I should also mention the test took ~1,400 seconds (!) on my machine before failing.
```
[----------] 2 tests from MaxJoinTest/1, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, s
td::allocator<int> > >, false>
[ RUN      ] MaxJoinTest/1.HugeJoinSize
ERROR: RMM call in line 67of file /home/eyalroz/src/blazing/cudf/libgdf/src/join/hash/../../hashmap/managed_allocator.cuh failed w
ith result RMM_ERROR_OUT_OF_MEMORY (4)  Attempted to allocate: 8589934592 bytes.
unknown file: Failure
C++ exception with description "std::bad_alloc" thrown in the test body.
[  FAILED  ] MaxJoinTest/1.HugeJoinSize, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, s
td::allocator<int> > >, false> (21656 ms)
[ RUN      ] MaxJoinTest/1.InputTooLarge
[       OK ] MaxJoinTest/1.InputTooLarge (596815 ms)
[----------] 2 tests from MaxJoinTest/1 (618528 ms total)

[----------] Global test environment tear-down
[==========] 312 tests from 46 test cases ran. (1344119 ms total)
[  PASSED  ] 311 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] MaxJoinTest/1.HugeJoinSize, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, s
td::allocator<int> > >, false>

 1 FAILED TEST
```

- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the version or commit hash I am using for reference.
- [x] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [x] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by jrhemstad** [comment]
Yeah, the `MaxJoinTest` isn't particularly intelligent. It was added when there was an integer overflow bug, and I believe I sized the input assuming at least a 16GB GPU. I'll look into making it more intelligent by checking the available GPU memory or something similar.

The `InputTooLarge` doesn't fail because it doesn't actually allocate a buffer. It simply passes in a `gdf_column` whose size is set to be larger than the maximum supported size.
