### ISSUE TITLE
[BUG] apply_rows string AttributeError

### ISSUE THREAD

**Issue by antw-cg** [rapidsai/cudf#3700]
**Describe the bug**
`AttributeError: 'nvstrings' object has no attribute 'mem'` when attempting to use apply_rows on str data.

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
# import nvstrings

dts = np.array([20170101, 20170102], dtype='int32')
headlines = ['FB buys Instagram', 'Trump says something']
gdf = cudf.DataFrame()
gdf['headline_text'] = headlines
gdf['dt'] = dts

# TICKERS = nvstrings.to_device(['fb', 'amzn'])
# CO_NAMES = nvstrings.to_device(['facebook', 'amazon'])
TICKERS = ['fb', 'amzn']
CO_NAMES = ['facebook', 'amazon']

def lf_about_public_company(headline_text, lf_about_public_company):
    for i, val in enumerate(headline_text):
        no_company_tickers = not any([word in headline_text[i].str.lower() for word in TICKERS]) 
        no_company_names = not any([word in headline_text[i].str.lower() for word in CO_NAMES])
        lf_about_public_company[i] = 0 if no_company_tickers or no_company_names else 1

outdf = gdf.apply_rows(lf_about_public_company,
                       incols=['headline_text'],
                       outcols=dict(lf_about_public_company=np.int32),
                       kwargs=dict())
```

**Expected behavior**
an additional column in outdf
`>> outdf.head()`
| headline_text | dt | lf_about_public_company |
| FB buys Instagram | 20170101 | 1 |
| Trump says something | 20170102 | 0 |

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: conda

**Environment details**
**git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
     NAME="Ubuntu"
     VERSION="18.04.2 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.2 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux a157821 4.4.0-165-generic #193-Ubuntu SMP Tue Sep 17 17:42:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Jan  6 21:28:16 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 384.183      Driver Version: 384.183      CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-DGXS...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   42C    P0    52W / 300W |  14317MiB / 32497MiB |      1%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
     | N/A   41C    P0    54W / 300W |   2609MiB / 32499MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-DGXS...  On   | 00000000:0E:00.0 Off |                    0 |
     | N/A   41C    P0    54W / 300W |   2609MiB / 32499MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-DGXS...  On   | 00000000:0F:00.0 Off |                    0 |
     | N/A   42C    P0    53W / 300W |   2609MiB / 32499MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              40
     On-line CPU(s) list: 0-39
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             1199.945
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4397.49
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-39
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /opt/conda/bin/cmake
     cmake version 3.14.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243
     
     ***Python***
     /opt/conda/envs/test_env/bin/python
     Python 3.6.7
     
     ***Environment Variables***
     PATH                            : /opt/conda/envs/test_env/bin:/opt/conda/condabin:/usr/local/nvm/versions/node/v12.9.0/bin:/opt/conda/bin:/usr/local/mpi/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /opt/conda/envs/test_env
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /opt/conda/envs/test_env:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     absl-py                   0.9.0                    pypi_0    pypi
     alabaster                 0.7.12                   pypi_0    pypi
     apex                      0.1                      pypi_0    pypi
     arrow-cpp                 0.15.0           py36h090bef1_2    conda-forge
     astor                     0.8.1                    pypi_0    pypi
     attrs                     19.3.0                     py_0    conda-forge
     babel                     2.7.0                    pypi_0    pypi
     backcall                  0.1.0                    py36_0
     blas                      1.0                         mkl
     blis                      0.4.1                    pypi_0    pypi
     bokeh                     1.4.0                    py36_0
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     boto3                     1.10.43                  pypi_0    pypi
     botocore                  1.13.43                  pypi_0    pypi
     brotli                    1.0.7                he6710b0_0
     bzip2                     1.0.8                h7b6447c_0
     c-ares                    1.15.0            h7b6447c_1001
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cachetools                4.0.0                    pypi_0    pypi
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     catalogue                 0.0.8                      py_0    conda-forge
     certifi                   2019.11.28               py36_0
     cffi                      1.13.2           py36h8022711_0    conda-forge
     cfitsio                   3.470                hb7c8383_2
     chardet                   3.0.4                 py36_1003    conda-forge
     click                     7.0                      py36_0
     cloudpickle               1.2.2                      py_0
     conllu                    1.3.1                    pypi_0    pypi
     cryptography              2.8              py36h72c5cf5_1    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.11.0                   py36_0    rapidsai
     cudnn                     7.6.5                cuda10.1_0
     cugraph                   0.11.0                   py36_0    rapidsai
     cuml                      0.11.0          cuda10.1_py36_0    rapidsai
     cupy                      6.6.0            py36ha7c4746_1    conda-forge
     curl                      7.67.0               hbc83047_0
     cuspatial                 0.11.0                   py36_0    rapidsai
     cycler                    0.10.0                   pypi_0    pypi
     cymem                     2.0.3            py36he1b5a44_0    conda-forge
     cython                    0.29.14          py36he6710b0_0
     cytoolz                   0.10.1           py36h7b6447c_0
     dask                      2.9.0                      py_0
     dask-core                 2.9.0                      py_0
     dask-cuda                 0.11.0                   py36_0    rapidsai
     dask-cudf                 0.11.0                   py36_0    rapidsai
     dask-xgboost              0.2.0.dev28      cuda10.1py36_0    rapidsai
     datasketch                1.5.0                    pypi_0    pypi
     decorator                 4.4.1                      py_0
     distributed               2.9.0                      py_0
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   pypi_0    pypi
     double-conversion         3.1.5                he6710b0_1
     editdistance              0.5.3                    pypi_0    pypi
     en-core-web-lg            2.2.5                    pypi_0    pypi
     expat                     2.2.6                he6710b0_0
     fast-bert                 1.5.3                    pypi_0    pypi
     fastavro                  0.22.7           py36h7b6447c_0
     fastprogress              0.1.22                   pypi_0    pypi
     fastrlock                 0.4              py36he6710b0_0
     flaky                     3.6.1                    pypi_0    pypi
     flask                     1.1.1                    pypi_0    pypi
     flask-cors                3.0.8                    pypi_0    pypi
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.9.1                h8a8886c_1
     freexl                    1.0.5                h14c3975_0
     fsspec                    0.6.2                      py_0
     ftfy                      5.6                      pypi_0    pypi
     gast                      0.2.2                    pypi_0    pypi
     gdal                      2.4.3            py36h5f563d9_9    conda-forge
     geos                      3.7.2                he1b5a44_2    conda-forge
     geotiff                   1.5.1                h21e8280_0
     gevent                    1.4.0                    pypi_0    pypi
     gflags                    2.2.2                he6710b0_0
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.63.1               h5a9c865_0
     glog                      0.4.0                he6710b0_0
     google-auth               1.10.0                   pypi_0    pypi
     google-auth-oauthlib      0.4.1                    pypi_0    pypi
     google-pasta              0.1.8                    pypi_0    pypi
     greenlet                  0.4.15                   pypi_0    pypi
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     grpcio                    1.26.0                   pypi_0    pypi
     h5py                      2.10.0                   pypi_0    pypi
     hdf4                      4.2.13               h3ca952b_2
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py36_1000    conda-forge
     imagesize                 1.1.0                    pypi_0    pypi
     importlib_metadata        1.3.0                    py36_0    conda-forge
     intel-openmp              2019.4                      243
     ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
     ipython                   7.10.2           py36h39e3cac_0
     ipython_genutils          0.2.0                    py36_0
     itsdangerous              1.1.0                    pypi_0    pypi
     jedi                      0.15.1                   py36_0
     jinja2                    2.10.3                     py_0
     jmespath                  0.9.4                    pypi_0    pypi
     joblib                    0.14.1                     py_0
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1               h1bed415_0
     jsonnet                   0.14.0                   pypi_0    pypi
     jsonpickle                1.2                      pypi_0    pypi
     jsonschema                3.2.0                    py36_0    conda-forge
     jupyter_client            5.3.4                    py36_0
     jupyter_core              4.6.1                    py36_0
     kealib                    1.4.10            h58c409b_1005    conda-forge
     keras                     2.3.1                    pypi_0    pypi
     keras-applications        1.0.8                    pypi_0    pypi
     keras-preprocessing       1.1.0                    pypi_0    pypi
     kiwisolver                1.1.0                    pypi_0    pypi
     krb5                      1.16.4               h173b8e3_0
     libcudf                   0.11.0               cuda10.1_0    rapidsai
     libcugraph                0.11.0               cuda10.1_0    rapidsai
     libcuml                   0.11.0               cuda10.1_0    rapidsai
     libcumlprims              0.11.0               cuda10.1_0    nvidia
     libcurl                   7.67.0               h20c2e04_0
     libcuspatial              0.11.0               cuda10.1_0    rapidsai
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgdal                   2.4.3                h2f07a13_9    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_0
     libiconv                  1.15                 h63c8f33_5
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
     libnvstrings              0.11.0               cuda10.1_0    rapidsai
     libpng                    1.6.37               hbc83047_0
     libpq                     11.5                 hd9ab2ff_2    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.11.0               cuda10.1_0    rapidsai
     libsodium                 1.0.16               h1bed415_0
     libspatialite             4.3.0a            h4f6d029_1032    conda-forge
     libssh2                   1.8.2                h1ba5d50_0
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libxcb                    1.13                 h1bed415_1
     libxgboost                1.0.0dev.rapidsai0.11      cuda10.1_1    rapidsai
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py36hd408876_0
     locket                    0.2.0                    py36_1
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.1.1                    pypi_0    pypi
     markupsafe                1.1.1            py36h7b6447c_0
     matplotlib                3.1.2                    pypi_0    pypi
     mkl                       2019.4                      243
     mkl-service               2.3.0            py36he904b0f_0
     mkl_fft                   1.0.15           py36ha843d7b_0
     mkl_random                1.1.0            py36hd6b4f25_0
     mock                      3.0.5                    pypi_0    pypi
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.1            py36hfd86e86_1
     murmurhash                1.0.0            py36he1b5a44_0    conda-forge
     nccl                      2.4.6.1              cuda10.1_0    nvidia
     ncurses                   6.1                  he6710b0_1
     ninja                     1.9.0            py36hfd86e86_0
     nltk                      3.4.5                    pypi_0    pypi
     numba                     0.46.0           py36h962f231_0
     numpy                     1.17.4           py36hc1035e2_0
     numpy-base                1.17.4           py36hde5b4d6_0
     numpydoc                  0.9.1                    pypi_0    pypi
     nvstrings                 0.11.0                   py36_0    rapidsai
     oauthlib                  3.1.0                    pypi_0    pypi
     olefile                   0.46                     py36_0
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h7b6447c_3
     opt-einsum                3.1.0                    pypi_0    pypi
     overrides                 2.6                      pypi_0    pypi
     packaging                 19.2                       py_0
     pandas                    0.24.2           py36he6710b0_0
     parquet-cpp               1.5.1                         2    conda-forge
     parsimonious              0.8.1                    pypi_0    pypi
     parso                     0.5.2                      py_0
     partd                     1.1.0                      py_0
     patsy                     0.5.1                    pypi_0    pypi
     pcre                      8.43                 he6710b0_0
     pexpect                   4.7.0                    py36_0
     pickleshare               0.7.5                    py36_0
     pillow                    6.2.1            py36h34e0f95_0
     pip                       19.3.1                   py36_0
     pixman                    0.38.0               h7b6447c_0
     plac                      0.9.6                    py36_0    conda-forge
     plotly                    4.4.1                    pypi_0    pypi
     pluggy                    0.13.1                   pypi_0    pypi
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         0
     postgresql                11.5                 hc63931a_2    conda-forge
     pprint                    0.1                      pypi_0    pypi
     preshed                   3.0.2            py36he1b5a44_1    conda-forge
     proj                      6.2.1                haa6030c_0
     prompt_toolkit            3.0.2                      py_0
     protobuf                  3.11.1                   pypi_0    pypi
     psutil                    5.6.7            py36h7b6447c_0
     ptyprocess                0.6.0                    py36_0
     py                        1.8.0                    pypi_0    pypi
     py-xgboost                1.0.0dev.rapidsai0.11  cuda10.1py36_1    rapidsai
     pyarrow                   0.15.0           py36h8b68381_1    conda-forge
     pyasn1                    0.4.8                    pypi_0    pypi
     pyasn1-modules            0.2.7                    pypi_0    pypi
     pycparser                 2.19                     py36_1    conda-forge
     pyculib                   1.0.1                    pypi_0    pypi
     pygments                  2.5.2                      py_0
     pynvml                    8.0.3                      py_0    conda-forge
     pyopenssl                 19.1.0                   py36_0    conda-forge
     pyparsing                 2.4.5                      py_0
     pyrsistent                0.15.6           py36h516909a_0    conda-forge
     pysocks                   1.7.1                    py36_0    conda-forge
     pytest                    5.3.2                    pypi_0    pypi
     python                    3.6.7             h357f687_1006    conda-forge
     python-dateutil           2.8.0                    pypi_0    pypi
     pytorch                   1.3.1           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
     pytorch-lamb              1.0.0                    pypi_0    pypi
     pytorch-nlp               0.5.0                    pypi_0    pypi
     pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
     pytorch-transformers      1.1.0                    pypi_0    pypi
     pytz                      2019.3                     py_0
     pyyaml                    5.2              py36h7b6447c_0
     pyzmq                     18.1.0           py36he6710b0_0
     rapids                    0.11.0          cuda10.1_py36_10    rapidsai
     rapids-xgboost            0.11.0          cuda10.1_py36_10    rapidsai
     re2                       2019.08.01           he6710b0_0
     readline                  8.0                  hf8c457e_0    conda-forge
     regex                     2019.12.19               pypi_0    pypi
     requests                  2.22.0                   py36_1    conda-forge
     requests-oauthlib         1.3.0                    pypi_0    pypi
     responses                 0.10.9                   pypi_0    pypi
     retrying                  1.3.3                    pypi_0    pypi
     rmm                       0.11.0                   py36_0    rapidsai
     rsa                       4.0                      pypi_0    pypi
     s3transfer                0.2.1                    pypi_0    pypi
     sacremoses                0.0.35                   pypi_0    pypi
     scattertext               0.0.2.56                 pypi_0    pypi
     scikit-learn              0.22             py36hd81dba3_0
     scipy                     1.3.2            py36h7c811a0_0
     sentencepiece             0.1.85                   pypi_0    pypi
     seqeval                   0.0.12                   pypi_0    pypi
     setuptools                42.0.2                   py36_0
     simpletransformers        0.13.2                   pypi_0    pypi
     six                       1.13.0                   py36_0
     sklearn                   0.0                      pypi_0    pypi
     snappy                    1.1.7                hbae5bb6_3
     snorkel                   0.7.0                      py_1    conda-forge
     snowballstemmer           2.0.0                    pypi_0    pypi
     sortedcontainers          2.1.0                    py36_0
     spacy                     2.2.3            py36hc9558a2_0    conda-forge
     sphinx                    2.3.0                    pypi_0    pypi
     sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
     sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
     sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
     sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
     sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
     sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
     sqlalchemy                1.3.11           py36h7b6447c_0
     sqlite                    3.30.1               h7b6447c_0
     sqlparse                  0.3.0                    pypi_0    pypi
     srsly                     0.2.0            py36he1b5a44_0    conda-forge
     statsmodels               0.10.2                   pypi_0    pypi
     tbb                       2019.8               hfd86e86_0
     tblib                     1.6.0                      py_0
     tensorboard               2.0.2                    pypi_0    pypi
     tensorboardx              1.9                      pypi_0    pypi
     tensorflow                2.0.0                    pypi_0    pypi
     tensorflow-estimator      2.0.1                    pypi_0    pypi
     termcolor                 1.1.0                    pypi_0    pypi
     textblob                  0.15.3                   pypi_0    pypi
     thinc                     7.3.1                    pypi_0    pypi
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toolz                     0.10.0                     py_0
     torch                     1.3.1                    pypi_0    pypi
     torchvision               0.4.2                    pypi_0    pypi
     tornado                   6.0.3            py36h7b6447c_0
     tqdm                      4.40.2                     py_0    conda-forge
     traitlets                 4.3.3                    py36_0
     transformers              2.2.2                    pypi_0    pypi
     tzcode                    2019a             h516909a_1002    conda-forge
     unidecode                 1.1.1                    pypi_0    pypi
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.7                   py36_0    conda-forge
     wasabi                    0.4.0                      py_0    conda-forge
     wcwidth                   0.1.7                    py36_0
     werkzeug                  0.16.0                   pypi_0    pypi
     wheel                     0.33.6                   py36_0
     word2number               1.1                      pypi_0    pypi
     wrapt                     1.11.2                   pypi_0    pypi
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.0.0dev.rapidsai0.11  cuda10.1py36_1    rapidsai
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7                had09818_2
     zeromq                    4.3.1                he6710b0_3
     zict                      1.0.0                      py_0
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.3                h3b9ef0a_0    conda-forge

**Additional context**
Full error output:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-36-08328c754ee3> in <module>
      2                        incols=['headline_text'],
      3                        outcols=dict(lf_about_public_company=str),
----> 4                        kwargs=dict())
      5 outdf.tail()
      6 #

/opt/conda/envs/test_env/lib/python3.6/site-packages/cudf/core/dataframe.py in apply_rows(self, func, incols, outcols, kwargs, pessimistic_nulls, cache_key)
   2970             kwargs,
   2971             pessimistic_nulls,
-> 2972             cache_key=cache_key,
   2973         )
   2974 

/opt/conda/envs/test_env/lib/python3.6/site-packages/cudf/utils/applyutils.py in apply_rows(df, func, incols, outcols, kwargs, pessimistic_nulls, cache_key)
     75         func, incols, outcols, kwargs, pessimistic_nulls, cache_key=cache_key
     76     )
---> 77     return applyrows.run(df)
     78 
     79 

/opt/conda/envs/test_env/lib/python3.6/site-packages/cudf/utils/applyutils.py in run(self, df, **launch_params)
    142             inputs = {v: df[k].data.mem for (k, v) in self.incols.items()}
    143         else:
--> 144             inputs = {k: df[k].data.mem for k in self.incols}
    145         # Allocate output columns
    146         outputs = {}

/opt/conda/envs/test_env/lib/python3.6/site-packages/cudf/utils/applyutils.py in <dictcomp>(.0)
    142             inputs = {v: df[k].data.mem for (k, v) in self.incols.items()}
    143         else:
--> 144             inputs = {k: df[k].data.mem for k in self.incols}
    145         # Allocate output columns
    146         outputs = {}

AttributeError: 'nvstrings' object has no attribute 'mem'
```

**Comment by taureandyernv** [comment]
@antw-cg , here is an alternative solution using string accessors.  Not the most optimum code.  I also added a little more data.

```
import cudf
import numpy as np

dts = np.array([20170101, 20170102, 20170103], dtype='int32')
headlines = ['FB buys Instagram', 'Trump says something', "Amazon makes Bezos richer"]
gdf = cudf.DataFrame()
gdf['headline_text'] = headlines
gdf['dt'] = dts

TICKERS = ['fb', 'amzn']
CO_NAMES = ['facebook', 'amazon']

a = gdf['headline_text'].str.lower()
tickers = 0
conames = 0
for i in range(0, len(TICKERS)):
    tickers+= a.str.contains(TICKERS[i]).astype("int32")
for i in range(0, len(CO_NAMES)):
    conames+= a.str.contains(CO_NAMES[i]).astype("int32")
gdf["lf_about_public_company"] = tickers+conames
```
Output:
```
	headline_text	dt	lf_about_public_company
0	FB buys Instagram	20170101	1
1	Trump says something	20170102	0
2	Amazon makes Bezos richer	20170103	1
```

If this solves your issue, let us know!

**Comment by antw-cg** [comment]
@taureandyernv Your solution works for the example dataset. Thank you.

However, I tried optimizing the implementation myself using the nvtext.contains_strings method which, works on an example dataset, but for a dataset of 1.6M headlines and 9000 company names and tickers, the kernel crashes. I was monitoring GPU usage using nvtop, and the kernel crashes when GPU compute spikes up to 75%, GPU memory stayed below 10% of the 32 GB. For comparison, the implementation you gave maxed out GPU compute and GPU memory sometimes spiked up to 30% of the 32GB:
```
headlines_nvs = nvstrings.to_device(list(gdf['headline_text'].astype('str').to_array()))
TICKERS_N_COS = TICKERS + CO_NAMES
tickers_n_cos_nvs = nvstrings.to_device(TICKERS_N_COS)
bool_matrix_labels = nvtext.contains_strings(headlines_nvs, tickers_n_cos_nvs)
labels_df = pd.DataFrame(bool_mtrx_lbls, columns=TICKERS_N_COS)
labels_df.head()
```

I tried again to optimize the implementation using applymap, but got the same error (AttributeError: 'StringColumn' object has no attribute 'unary_operator') as https://github.com/rapidsai/cudf/issues/3646:
```
def apply_map_kernel(headline_text):
    company_count = 0
    for i in range(0, len(TICKERS)):
        company_count += headline_text.str.contains(TICKERS[i]).astype("int32")
    if company_count == 0:
        for i in range(0, len(CO_NAMES)):
            company_count += headline_text.str.contains(CO_NAMES[i]).astype("int32")
    return int(company_count > 0)

gdf1 = gdf
gdf1['headline_text'].applymap(
    udf = apply_map_kernel,
    out_dtype = np.int32
)
gdf1.head()
```

Could you point me in the right direction as to how this implementation could be optimized, especially for larger datasets?


As a sidenote, the syntax in the implementation you provided works, and is correct for the example (doesn't appear to be working on my larger dataset, but that's not necessarily caused by RAPIDS), but is somewhat confusing:
```
a = gdf['headline_text'].str.lower()
tickers = 0
conames = 0
for i in range(0, len(TICKERS)):
    tickers+= a.str.contains(TICKERS[i]).astype("int32")
for i in range(0, len(CO_NAMES)):
    conames+= a.str.contains(CO_NAMES[i]).astype("int32")
gdf["lf_about_public_company"] = tickers+conames
```
1. It is unclear that when iterating over TICKERS and CO_NAMES that you're also iterating over  `gdf['headline_text'].str.lower()`. 
2. tickers and conames vars are both initialized as single value ints. It seems like despite that, they take on a different value for each row in the matrix. Not sure whether something related to this is what's causing errors in my implementation on a larger dataset...

**Comment by taureandyernv** [comment]
I wrote a long response with a few questions of my own, but i may need to chat with you and then submit the optimized solution for the large dataset here.  Can you find me on the [RAPIDS-GoAI slack](https://join.slack.com/t/rapids-goai/shared_invite/enQtMjE0Njg5NDQ1MDQxLTJiN2FkNTFkYmQ2YjY1OGI4NTc5Y2NlODQ3ZDdiODEwYmRiNTFhMzNlNTU5ZWJhZjA3NTg4NDZkMThkNTkxMGQ)? 

I did expect the GPU to get pegged.  A 3x memory increase was not expected and i'd like to explore that a bit more with.  

Side Notes Replies:
1) `a = gdf['headline_text'].str.lower()` creates a pointer to the dataframe column to work on.  .  `tickers= a.str.contains(TICKERS[i]).astype("int32")` , tickers points to the output of the string operations that you did on `a`.  The string accessor abstracts the parallelized operations for working on the rows.  The FOR loop is serial.  `tickers+= a.str.contains(TICKERS[i]).astype("int32")` should have been far more memory friendly....

2) While I don't believe that it should crash anything, i did shortcut there for the toy example.  However, by the first iteration, it should be in the cudf scalar size you wanted.  You could instantiate something at the size of `headline_text`. 

I look forward to chatting with you on slack

**Comment by antw-cg** [comment]
I'll be satisfied with the first implementation you gave me. Thanks.
