### ISSUE TITLE
[DOC] Clearer documentation of edge cases that throw runtime exceptions, e.g., scale

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#3703]
## Report incorrect documentation

**Location of incorrect documentation**

`series.scale`: 
https://github.com/rapidsai/cudf/blob/branch-0.12/python/cudf/cudf/core/series.py#L2110

**Describe the problems or issues found in the documentation**

While readers `series::scale()` source code know that providing a masked series will throw a runtime exception, users of the docs do not. We have found similar issues elsewhere, which adds to the difficulty of writing cudf-based software that does not crash unpredictably.

**Steps taken to verify documentation is incorrect**

Read source code of `0.10` and `0.12`.

**Suggested fix for documentation**

Possible solutions are to document the exceptions thrown in API docs and include them in IDE-readable annotations.

**Comment by GregoryKimball** [comment]
Closing because the `series.scale` function has been rewritten. Please raise a new issue for examples of exceptions that need documentation.
