### ISSUE TITLE
[FEA] `string` dtype doesn't support `to_gpu_array()`

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#3707]
**Is your feature request related to a problem? Please describe.**

Columns with `string` dtype can't be passed to numba because `to_gpu_array()` is not supported.

**Describe the solution you'd like**

The `to_gpu_array()` method could be supported simply by converting the string column into a `category` before calling `to_gpu_array()`. Callers will need to get access to the map from categories back to string values.

I'm not sure if we want to add this feature but there is a stackoverflow question relating to it.

https://stackoverflow.com/questions/56386314/nvstrings-object-has-no-attribute-to-gpu-array

**Comment by kkraus14** [comment]
A string is not representable in a single contiguous array so this is impossible. If an array library starts supporting strings that aren't like numpy where it's an array of pointers to Python objects, we'll investigate supporting it, but until then closing this as out of scope.
