### ISSUE TITLE
[FEA] Add COUNT aggregation that includes null values

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3708]
**Is your feature request related to a problem? Please describe.**

Currently, the [COUNT](https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/aggregation.hpp#L51) aggregation will only count _valid_ values. 

As requested in https://github.com/rapidsai/cudf/issues/3131, there is need for the ability to perform a COUNT aggregation that includes null values.

**Describe the solution you'd like**

Update the COUNT aggregation factory to accept a boolean that specifies whether or not NULL values are included. 

```
std::unique_ptr<aggregation> make_count_aggregation(bool skip_nulls);
```

Internally, the existing `COUNT` enum value should be renamed to `COUNT_VALID`, and a new enum value `COUNT_ALL` should be added. Depending on the value of `skip_nulls`, the `make_count_aggregation` will return an aggregation whose `kind` is either `COUNT_VALID` or `COUNT_ALL`.

**Comment by karthikeyann** [comment]
which is preferred? 
`std::unique_ptr<aggregation> make_count_aggregation(bool skip_nulls);`
or existing enum class `include_nulls::YES` `NO`?

**Comment by jrhemstad** [comment]
> which is preferred?
> `std::unique_ptr<aggregation> make_count_aggregation(bool skip_nulls);`
> or existing enum class `include_nulls::YES`,`NO`?

Use the `include_nulls` enum.
