### ISSUE TITLE
Mis-construction of modulus_bit_width functor in libgdf - constructor parameter not used.

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#371]
Have a look at [this](https://github.com/rapidsai/cudf/blob/master/libgdf/src/streamcompactionops.cu#L94):
```
struct modulus_bit_width : public thrust::unary_function<gdf_size_type,gdf_size_type>
{
        /* snipped */

	modulus_bit_width (gdf_size_type b_nytes, gdf_size_type column_size) {
		this->n_bytes = n_bytes;
		this->column_size = column_size;
	}
```
That's rot night. I mean, not right. If you catch my drift.

Also, this functor needs a bit of tender love and care (e.g. an initializer list, doxygenation, clearer variable names).

Looking at cudf master branch, commit f1dd5e03d1feb306aba4114507cb5f4db83b59e3 .

**Comment by harrism** [comment]
That's kind of funny. How does this even compile? 

The commit you list doesn't seem to be the commit that made this code...

**Comment by eyalroz** [comment]
> That's kind of funny. How does this even compile?

It compiles because `b_nytes` is never used... :-P

> The commit you list doesn't seem to be the commit that made this code...

That's true. This was introduced... a long time ago. However, @williamBlazing has shown me commits in the binary-operator-draft branch which fix this, and in fact, the rather broken semantics of this functor. I'm working on porting those commits, or at least one of them, to apply directly to cudf's master branch.

**Comment by harrism** [comment]
But `n_bytes` *is* used so must be defined elsewhere. Either that or this is not compiled.

**Comment by eyalroz** [comment]
> But `n_bytes` _is_ used so must be defined elsewhere. Either that or this is not compiled.

It's a self-assignment. Devilishly clever!

**Comment by eyalroz** [comment]
So, apparently this was resolved on the `binary_operators_draft` branch, because the semantics of the functor which changed completely.

**Comment by Shakeebbk** [comment]
Will work on this.

**Comment by harrism** [comment]
This code doesn't exist anymore.
