### ISSUE TITLE
[unrecognized error code] Read CSV

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/cudf#3711]
Create a CSV file:
for example I am making a file called `test.csv` with content below:
```
1,1,2.00,AR,Ben
1,45,-16.00,AR,Ric
2,3,48.01,MD,PP
```

load the csv file using cudf.
```
>>> import cudf
>>> df = cudf.read_csv('test.csv')
```

Error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf/io/csv.py", line 82, in read_csv
    index_col=index_col,
  File "cudf/_lib/csv.pyx", line 41, in cudf._lib.csv.read_csv
  File "cudf/_lib/csv.pyx", line 233, in cudf._lib.csv.read_csv
RuntimeError: after reduction step 1: unrecognized error code
```

**Comment by taureandyernv** [comment]
hey @mlahir1 , i just tested this and it works...  although, with your code as is, it uses the first row as the header.  

What is your RAPIDS version, env, and set up?

Input (as `errortest.csv`)
```
1,1,2.00,AR,Ben
1,45,-16.00,AR,Ric
2,3,48.01,MD,PP
```
Code:
```
import cudf
df = cudf.read_csv('errortest.csv')
df.head()
```
Output:
```
  | 1 | 1.1 | 2.00 | AR | Ben
-- | -- | -- | -- | -- | --
1 | 45 | -16.00 | AR | Ric
2 | 3 | 48.01 | MD | PP
```

**Comment by mlahir1** [comment]
@taureandyernv 

I am using cudf branch-0.12, built from source today's latest nightly.
CUDA_VERSION=10.0
LINUX_VERSION=ubuntu16.04

**Comment by mlahir1** [comment]
Hello @taureandyernv 

I tried again with the latest nightly built from source today morning. still the same issue.
`cudf: 0.12.0b0+839.g0d5caee`

**Comment by randerzander** [comment]
@mlahir1 the following works for me in both 0.11 release conda packages and 0.12 nightly conda packages:
```
import cudf

fn = 'test.csv'
lines = """1,1,2.00,AR,Ben
1,45,-16.00,AR,Ric
2,3,48.01,MD,PP
"""
with open(fn, 'w') as fp:
    fp.write(lines)
    
cudf.read_csv(fn)
```

Could there be either some environment issue, or perhaps the CSV file is encoded differently from how I created it in my test snippet?

**Comment by randerzander** [comment]
Closing, I believe this is an issue with build environment. Please re-open if you find otherwise.
