### ISSUE TITLE
[BUG] mean() fails on groupby

### ISSUE THREAD

**Issue by AjayThorve** [rapidsai/cudf#3712]
**Describe the bug**
When trying to use the mean() function on a cudf.core.groupby.groupby.DataFrameGroupBy object, a 'RuntimeError: Failed to deserialize program' is thrown

**Steps/Code to reproduce bug**
```python
df = cudf.DataFrame(
    {"key": [0, 1, 2, 3, 4], "val": [float(i + 10) for i in range(5)], "val2": [float(i + 15) for i in range(5)]}
)

g = df.groupby('key')
g.mean()
```
Stack Trace

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-53-c79523bc0c66> in <module>
----> 1 g.mean()

~/anaconda3/envs/rapids_dev_0.12/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in mean(self)
     38 
     39     def mean(self):
---> 40         return self._apply_aggregation("mean")
     41 
     42     def count(self):

~/anaconda3/envs/rapids_dev_0.12/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in _apply_aggregation(self, agg)
    130         Applies the aggregation function(s) ``agg`` on all columns
    131         """
--> 132         result = self._groupby.compute_result(agg)
    133         libcudf.nvtx.nvtx_range_pop()
    134         return result

~/anaconda3/envs/rapids_dev_0.12/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in compute_result(self, agg)
    368             aggs_as_list,
    369             self.sort,
--> 370             self.dropna,
    371         )
    372 

~/anaconda3/envs/rapids_dev_0.12/lib/python3.7/site-packages/cudf/core/groupby/groupby.py in _groupby_engine(key_columns, value_columns, aggs, sort, dropna)
    549     """
    550     out_key_columns, out_value_columns = libcudf.groupby.groupby(
--> 551         key_columns, value_columns, aggs, dropna=dropna
    552     )
    553 

cudf/_lib/groupby.pyx in cudf._lib.groupby.groupby()

RuntimeError: Failed to deserialize program

```
**Expected behavior**
As of the nightly build 0.12.0a200105, the output was as expected ->
```python
   key   val  val2
0    0  10.0  15.0
1    1  11.0  16.0
2    2  12.0  17.0
3    3  13.0  18.0
4    4  14.0  19.0

```
**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
Output of the `cudf/print_env.sh` 

<details><summary>Click here to see environment details</summary><pre>
     **git***
     Not inside a git repository
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux aiinfra-rapids-ajay 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Jan  7 13:20:25 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  TITAN RTX           On   | 00000000:02:00.0  On |                  N/A |
     | 41%   42C    P2    59W / 280W |   2364MiB / 24219MiB |      2%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      2279      G   /usr/lib/xorg/Xorg                            28MiB |
     |    0      2336      G   /usr/bin/gnome-shell                          50MiB |
     |    0      3310      G   /usr/lib/xorg/Xorg                           336MiB |
     |    0      3471      G   /usr/bin/gnome-shell                         315MiB |
     |    0      7074      G   ...uest-channel-token=--------------------   321MiB |
     |    0      9881      C   python                                       355MiB |
     |    0     12736      C   ...aconda3/envs/rapids_dev_0.12/bin/python   355MiB |
     |    0     29082      G   ...uest-channel-token=--------------------   514MiB |
     |    0     31504      G   ...uest-channel-token=--------------------   71MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz
     Stepping:            1
     CPU MHz:             1357.616
     CPU max MHz:         3800.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6796.14
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            15360K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.16.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89
     
     ***Python***
     /home/$USER/anaconda3/envs/rapids_dev_0.12/bin/python
     Python 3.7.3
     
     ***Environment Variables***
     PATH                            : /home/$USER/anaconda3/envs/rapids_dev_0.12/bin:/home/$USER/anaconda3/condabin:/home/$USER/anaconda3/bin:/home/$USER/bin:/home/$USER/.local/bin:/home/$USER/.nvm/versions/node/v13.5.0/bin:/home/$USER/anaconda3/bin:/home/$USER/bin:/home/$USER/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/$USER/anaconda3/envs/rapids_dev_0.12
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/$USER/anaconda3/condabin/conda
     # packages in environment at /home/$USER/anaconda3/envs/rapids_dev_0.12:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main    conda-forge
     aiohttp                   3.6.2                    pypi_0    pypi
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     async-timeout             3.0.1                    pypi_0    pypi
     attrs                     19.3.0                     py_0    conda-forge
     babel                     2.7.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     black                     19.10b0                  py37_0    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cffi                      1.13.2           py37h8022711_0    conda-forge
     cfitsio                   3.470                hb60a0a2_2    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.5.0                      py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     colorcet                  2.0.1                      py_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              2.8              py37h72c5cf5_1    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.12.0b200107          py37_606    rapidsai-nightly
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cupy                      6.6.0            py37ha7c4746_1    conda-forge
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuxfilter                 0.12.0a0+39.g9ba5616.dirty           dev_0    <develop>
     cycler                    0.10.0                     py_2    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.9.0                      py_0    conda-forge
     dask-core                 2.9.0                      py_0    conda-forge
     datashader                0.9.0                      py_0    conda-forge
     datashape                 0.5.4                      py_1    conda-forge
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.9.0                      py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.15.2                   py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.5             he1b5a44_1004    conda-forge
     fastavro                  0.22.8           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fiona                     1.8.9.post2      py37hdff7cfa_0    conda-forge
     flake8                    3.7.9                    py37_0    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     freexl                    1.0.5             h14c3975_1002    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     future                    0.18.2                   py37_0    conda-forge
     gdal                      2.4.3            py37h5f563d9_9    conda-forge
     geopandas                 0.6.2                      py_0    conda-forge
     geos                      3.7.2                he1b5a44_2    conda-forge
     geotiff                   1.5.1                hbd99317_7    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.58.3          py37h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.1.2             hf484d3e_1000    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     imageio                   2.6.1                    py37_0    conda-forge
     imagesize                 1.1.0                      py_0    conda-forge
     importlib_metadata        1.3.0                    py37_0    conda-forge
     ipykernel                 5.1.3            py37h5ca1d4c_0    conda-forge
     ipython                   7.10.1           py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1                      py_0    conda-forge
     jedi                      0.15.1                   py37_0    conda-forge
     jinja2                    2.10.3                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1            h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter-server-proxy      1.2.0                    pypi_0    pypi
     jupyter_client            5.3.3                    py37_1    conda-forge
     jupyter_core              4.6.1                    py37_0    conda-forge
     jupyter_sphinx            0.2.3                    py37_0    conda-forge
     jupyterlab                1.2.4                      py_0    conda-forge
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kealib                    1.4.10            h58c409b_1005    conda-forge
     kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
     krb5                      1.16.4               h2fd8d38_0    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.12.0b200107      cuda10.1_606    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.2.0                hdf63c60_0    conda-forge
     libgdal                   2.4.3                h2f07a13_9    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_2    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnetcdf                 4.7.1           nompi_h94020b1_102    conda-forge
     libnvstrings              0.12.0b200107      cuda10.1_606    rapidsai-nightly
     libopenblas               0.3.7                h5ec1e0e_5    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libpq                     11.5                 hd9ab2ff_2    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.12.0a200107      cuda10.1_113    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libspatialindex           1.9.3                he1b5a44_1    conda-forge
     libspatialite             4.3.0a            h4f6d029_1032    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.2.0                hdf63c60_0    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py37h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.0.1                    pypi_0    pypi
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     matplotlib-base           3.1.2            py37h250f245_1    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     more-itertools            8.0.2                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     multidict                 4.7.2                    pypi_0    pypi
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     mypy_extensions           0.4.3                    py37_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  4.4.0                      py_1    conda-forge
     nbsphinx                  0.5.0                      py_0    conda-forge
     nccl                      2.4.6.1              cuda10.1_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.4                        py_0    conda-forge
     notebook                  6.0.1                    py37_0    conda-forge
     numba                     0.46.0           py37hb3f55d8_1    conda-forge
     numpy                     1.17.3           py37h95a1406_0    conda-forge
     numpydoc                  0.9.1                      py_0    conda-forge
     nvstrings                 0.12.0b200107          py37_606    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     packaging                 19.2                       py_0    conda-forge
     pandas                    0.24.2           py37hb3f55d8_1    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     panel                     0.6.4                         0    conda-forge
     param                     1.9.2                      py_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.5.2                      py_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.6.0                      py_0    conda-forge
     pcre                      8.43                 he1b5a44_0    conda-forge
     pexpect                   4.7.0                    py37_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    6.2.1            py37hd70f55b_1    conda-forge
     pip                       19.3.1                   py37_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                11.5                 hc63931a_2    conda-forge
     proj                      6.2.1                hc80f0dc_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            3.0.2                      py_0    conda-forge
     psutil                    5.6.7            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.0                      py_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                     py37_1    conda-forge
     pyct                      0.4.6                      py_0    conda-forge
     pyct-core                 0.4.6                      py_0    conda-forge
     pydeck                    0.1.dev5                 pypi_0    pypi
     pyee                      6.0.0                      py_0    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.5                      py_0    conda-forge
     pyppeteer                 0.0.25                     py_1    conda-forge
     pyproj                    2.4.2.post1      py37h12732c1_0    conda-forge
     pyrsistent                0.15.6           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.3.2                    py37_0    conda-forge
     python                    3.7.3                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyviz_comms               0.7.2                      py_0    conda-forge
     pywavelets                1.1.1            py37hc1659b7_0    conda-forge
     pyyaml                    5.2              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     re2                       2019.12.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2019.12.19       py37h516909a_0    conda-forge
     requests                  2.22.0                   py37_1    conda-forge
     rmm                       0.12.0a200107          py37_113    rapidsai-nightly
     rtree                     0.9.3            py37h7b0cdae_0    conda-forge
     scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
     scipy                     1.4.0            py37h921218d_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                42.0.2                   py37_0    conda-forge
     shapely                   1.6.4           py37hec07ddf_1006    conda-forge
     simpervisor               0.3                      pypi_0    pypi
     six                       1.13.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1002    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sphinx                    2.3.0                      py_0    conda-forge
     sphinx-markdown-tables    0.0.10                   pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     tqdm                      4.40.2                     py_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     typed-ast                 1.4.0            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.1                  py37_0    conda-forge
     tzcode                    2019a             h516909a_1002    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.25.7                   py37_0    conda-forge
     wcwidth                   0.1.7                      py_1    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websockets                8.1              py37h516909a_0    conda-forge
     wheel                     0.33.6                   py37_0    conda-forge
     widgetsnbextension        3.5.1                    py37_0    conda-forge
     xarray                    0.14.1                     py_1    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.4.2                    pypi_0    pypi
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      0.6.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
</pre></details>

**Additional context**
This was not an issue in the nightly build 0.12.0a200105, but is in the build 0.12.0b200107

**Comment by jrhemstad** [comment]
@devavret @trxcllnt This looks like a Jitify issue when the `mean` aggregation calls the `div` binary operation. Were the jitify changes that would have broken the old binops?

**Comment by devavret** [comment]
@AjayThorve, Try cleaning out `/tmp/cudf*`

**Comment by AjayThorve** [comment]
yes, cleaning `/tmp/cudf*` resolved it. Thanks @devavret!
