### ISSUE TITLE
[BUG] I/O readers/writers mistakenly use the CATEGORY type

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#3721]
**Describe the bug**

The `CATEGORY` type for libcudf++ was not meant to be used and was simply a placeholder for a `DICTIONARY` column type (my fault for not being explicit about this or documenting it).

@davidwendt reported that the following files are using the `CATEGORY` type:
- io/csv/csv_gpu.cu
- io/csv/reader_impl.cu
- io/orc/writer_impl.cu
- io/parquet/reader_impl.cu
- io/parquet/writer_impl.cu

It's not quite clear how this type is being used, but it should be removed and the `CATEGORY` type should be removed all together. 

**Additional context**
A true dictionary column type is being added in https://github.com/rapidsai/cudf/pull/3577 which will add the type `DICTIONARY`.

**Comment by vuule** [comment]
@jrhemstad what is the expectation here? Are we supposed to directly use int32 type as CATEGORY backend until DICTIONARY becomes available?

**Comment by jrhemstad** [comment]
> @jrhemstad what is the expectation here? Are we supposed to directly use int32 type as CATEGORY backend until DICTIONARY becomes available?

How is the CATEGORY type currently being used?

**Comment by vuule** [comment]
> How is the CATEGORY type currently being used?
It's used to support categorical data type. In the legacy implementation, CATEGORY field values are computed as hash values of the string data in the input field. So the underlying data type is int32.
I took another look to answer your question and I don't see the equivalent code in the new implementations, except some bits and pieces, most notably in Parquet. No C++ tests test this feature so I can't tell if any references to CATEGORY in non-legacy code are in dead code.

@mjsamoht, what is the current state for categorical data support?

**Comment by mjsamoht** [comment]
I thought CATEGORY was only used for hash values before we had string support.  It shouldn't be required anymore.  But @OlivierNV would be the better person to comment.

**Comment by vuule** [comment]
Regardless of whether the categorical type support is functional ATM, I think it would be beneficial to keep the current logic with a placeholder type until the DICTIONARY support is in. @jrhemstad Thoughts?

**Comment by OlivierNV** [comment]
categorical is pretty much a hack, should be safe to remove it entirely from the libcudf++ paths: the readers will return strings as a 32-bit hash if the python use_categorical (iirc) parameter is true. For the writers, there is no such thing as categorical type in parquet/orc so it just treats the cudf category type as int32 if we ever see a column with this type, but it's not very useful since it would load back as int32, so we can just remove this type from the switch statements IMO (libcudf++ paths, legacy can remain as is).
Once we have generic string dictionary support, we could automatically convert strings to dictionaries, which require some non-trivial work, mainly to merge the existing parquet/orc rowgroup/stripe dictionaries to dictionary columns to minimize memory utilization.

**Comment by vuule** [comment]
@OlivierNV I don't see how hashing can work if we don't have a separate category type. If we directly use int32 for categorical data, such data it will be parsed as integers instead. What am I missing?

**Comment by OlivierNV** [comment]
@vuule With dictionary support, the dictionary index is the hash. No need for hashing strings into int32 (that was always a hack due to lack of proper dictionary support afaik).

**Comment by vuule** [comment]
> @vuule With dictionary support, the dictionary index is the hash. No need for hashing strings into int32 (that was always a hack due to lack of proper dictionary support afaik).

My question is about the current state - dictionary support is not in yet so I'm not sure what behavior we are supposed to implement until then.
I made a PR to remove the references, as requested by Jake:
https://github.com/rapidsai/cudf/pull/3766
@OlivierNV are these changes in line with what you expect?

**Comment by OlivierNV** [comment]
Yes, the changes seem reasonable to me.
