### ISSUE TITLE
[FEA] null aware equals binary op

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3749]
**Is your feature request related to a problem? Please describe.**
For spark support we need a SQL op '<=>' which 

> Returns same result as the EQUAL(=) operator for non-null operands, but returns true if both are null, false if one of the them is null.

This is **NOT** the same as the c++ <=> operator.

**Describe the solution you'd like**
I would love to see a new binary op that does what we want.

**Describe alternatives you've considered**
We can probably make this work with a combination of isNull, and copyIf, but that feels overly complicated and would result in a lot more columns being materialized.

**Comment by jrhemstad** [comment]
Sounds good, but we should definitely name it something different because this conflicts with C++'s spaceship operator that has much different behavior: https://en.cppreference.com/w/cpp/language/default_comparisons

**Comment by devavret** [comment]
Closed by #5004
