### ISSUE TITLE
[FEA] add months binary op

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3750]
**Is your feature request related to a problem? Please describe.**
We need to support the `add_months` SQL operator in Spark.  It takes a timestamp and will add the given number of months to it.

**Describe the solution you'd like**
A binary op that will add the given number of months to date/timestamp.

**Describe alternatives you've considered**
There is no real alternative because date/time operations are rather difficult to get right and us trying to do it with existing operators is likely to result in errors.

**Comment by devavret** [comment]
I'm tempted to say you can do this with UDFs https://github.com/rapidsai/cudf/issues/3791#issuecomment-578332645. But I think your concern here is that you'd like someone with experience in cudf timestamps (and `std::chrono`) to write that UDF?

**Comment by devavret** [comment]
Do you want the months to be chronological or calendrical? Meaning, should months just be considered as 30 days or should the actual name of the month be considered while adding days. With the latter, Feb 25 + 1 month would be March 25. https://stackoverflow.com/a/43018120/3325146

**Comment by jlowe** [comment]
> should months just be considered as 30 days or should the actual name of the month be considered

It's the latter.  This is implemented in terms of Java's [LocalDate#plusMonths method](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html#plusMonths-long-).  It treats the date as YY/MM/DD, adds the specified number of months to the months field, carrying over into the years field as necessary.  Then it checks the resulting date to see if it is an invalid calendar date.  If invalid, it walks back to the last valid date of that month.  Leap years are considered, so Feb 29th _might_ be a valid calendar date depending upon the year.

**Comment by beckernick** [comment]
Is this now covered by the recent implementation of `add_calendrical_months`?

https://github.com/rapidsai/cudf/blob/32f46f0e5dc3c1a0ee48799927878c88c333eb88/cpp/include/cudf/datetime.hpp#L160-L191

**Comment by revans2** [comment]
It looks like it should work for us. It is not a super high priority right now so it might be a while before I have time to test it and be sure it will work for everything we need.
