### ISSUE TITLE
[FEA] atan2 binary op

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3751]
**Is your feature request related to a problem? Please describe.**
For Spark we need to support the SQL function `atan2` which is described as 

>Returns the angle in radians between the positive x-axis of a plane and the point given by the coordinates (exprX, exprY), as if computed by java.lang.Math.atan2

**Describe the solution you'd like**
It looks like it would work well as a binary op that produces a double.

**Describe alternatives you've considered**
The algorithm takes several steps to get the answer and materializing all of the intermediate steps is too much.

**Comment by devavret** [comment]
https://github.com/rapidsai/cudf/issues/3791#issuecomment-578332645

**Comment by razajafri** [comment]
Wanted to know where we stand on this

**Comment by harrism** [comment]
Happy to review implementation PRs. libcudf team is focused on bugs/docs/tech debt for the 0.14 release.

**Comment by sriramch** [comment]
@razajafri i'm looking into this.
