### ISSUE TITLE
[BUG] dask_cudf.read_orc fails with OOM error

### ISSUE THREAD

**Issue by jcuda000001** [rapidsai/cudf#3752]
**Describe the bug**
dask_cudf reader fails when the dataset is one large orc file. Though it's a large dataset, the orc file contains around 200 stripes. cudf.read_orc() of individual stripes consumes around 1.4GB of GPU memory on average. None of the stripe consumes more than 1.5GB memory.  

Although, it seems, the dask orc reader code in the following link constructs the dask dataframe by  iterating through list of orc stripes, it is not able to avoid OOM error by creating a partitioned dataframe. 
https://github.com/rapidsai/cudf/blob/branch-0.12/python/dask_cudf/dask_cudf/io/orc.py

**Expected behavior**
dask_cudf.read_orc should create a DataFrame with multiple partitions.

**Environment overview (please complete the following information)**
 - Environment location: Docker (containerized environment)
 - Method of cuDF install: conda (rapids packages are installed using conda package manager)
 - GPUs - Tesla V100 (32GB mem)

**Comment by kkraus14** [comment]
cc @rjzamora @pentschev any ideas why Dask wouldn't start spilling here? @jcuda000001 how did you start your dask cluster?

**Comment by jcuda000001** [comment]
@kkraus14 
```
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
client = Client(cluster)

dask_cudf.read_orc('hdfs://.../../')
```

**Comment by jcuda000001** [comment]
On a different note, for dask_cudf to work on a single device, do we need to initiate a dask cluster (LocalCUDACluster)?

In both approaches (read_orc with and without LocalCUDACluster), I could see one of the devices getting filled to 32GB and fails.

**Comment by kkraus14** [comment]
> On a different note, for dask_cudf to work on a single device, do we need to initiate a dask cluster (LocalCUDACluster)?

Yes you still want that as it starts a `dask-cuda` worker which is what handles spilling the memory from GPU --> host memory --> disk.

Can you dump the output of `conda list` here? Specifically I want to see the versions of cudf, dask-cudf, dask, distributed, and dask-cuda that you have.

**Comment by jcuda000001** [comment]
```
cudf                      0.10.0                   py37_0    rapidsai
dask                      2.9.0                      py_0    conda-forge
dask-core                 2.9.0                      py_0    conda-forge
dask-cuda                 0.10.0                   py37_0    rapidsai
dask-cudf                 0.10.0                   py37_0    rapidsai
dask-labextension         1.1.0                    pypi_0    pypi
dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai
distributed               2.9.0                      py_0    conda-forge
```

**Comment by jcuda000001** [comment]
Seems like the code to handle stripes appeared from branch 0.11. Do I need an upgrade ?

**Comment by rjzamora** [comment]
> Seems like the code to handle stripes appeared from branch 0.11. Do I need an upgrade ?

That is correct - We added stripe-based partitioning more recently than 0.10

**Comment by kkraus14** [comment]
@jcuda000001 going to close this as this is resolved as of 0.11. If you still see this issue after upgrading feel free to reopen.

**Comment by jcuda000001** [comment]
@kkraus14, @rjzamora - upgrading to v0.11 fixed the issue. I could see that the number of partitions in the resultant DataFrame is equal to the number of stripes in the orc file. 

Thanks for the quick responses.

**Comment by jcuda000001** [comment]
@kkraus14, @rjzamora - Is there a way to control the number of partitions in the dask-cudf dataframe created from dask_cudf.read_orc(list_of_orc_files) operation?
It's good that read_orc from v0.11 actually does the read operation at stripe level, so there is no OOM error while reading large ORC files. But, in general (even for smaller datasets), this seems to be creating too many small partitions in the DataFrame (npartitions == n_stripes_per_file*number_of_files) and increasing the overall computation time of dask-cudf dataframe operations.

**Comment by jcuda000001** [comment]
In v0.10, reading same dataset with smaller ORC files created dask-cudf DataFrame with npartitions==number_of_files. This DataFrame computes faster than the v0.11 dataframe.

**Comment by rjzamora** [comment]
Hey @jcuda000001 - You are correct that the current implementation will always map each stripe in the dataset onto a distinct partition. This is also what the [upstream dask.dataframe implementation does](https://github.com/dask/dask/blob/3b31ab57d60c0729ffc224786ac69456ea8e6435/dask/dataframe/io/orc.py#L12). It may be reasonable to optionally partition by file instaed (as was done before 0.11).  It may also make sense to add an option to do something in-between (i.e aggregate multiple stripes per partition).

I suggest that you open a separtate issue for us to discuss the appropriate path forward.  To better motivate the addition of a new featutre, I suggest you explain the situation in which you see better performance for file partitioning. For example:  How much slower is stripe-based partitioning? Are the stripes all 250MB (the default)?  How many files and stripes are in the dataset?  Are you running with a distributed scheduler (using multiple GPUs)?
