### ISSUE TITLE
[FEA] date diff

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3757]
**Is your feature request related to a problem? Please describe.**
We would like to implement the spark sql datediff function.  It returned the number of days between two dates.

**Describe the solution you'd like**
This feels like it would make for a good binary op.

**Describe alternatives you've considered**
cast timestamps to days and subtract them, but with libcudf++ the subtraction binary op does not work for dates.

**Comment by jrhemstad** [comment]
Alternatively, once we add a time duration type, the subtration binary op will support timestamps and will return time deltas.

**Comment by revans2** [comment]
So is https://github.com/rapidsai/cudf/issues/2052 the issue I should dupe my date/time math issues against?  Or is there a different/newer issue I should look at?

**Comment by jrhemstad** [comment]
> So is #2052 the issue I should dupe my date/time math issues against? Or is there a different/newer issue I should look at?

Sure, #2052 can be the tracking issue for adding time-delta type, which I think will cover some of your datetime related requests.
