### ISSUE TITLE
[FEA] isnan

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3763]
**Is your feature request related to a problem? Please describe.**
Python has isna but there is no equivalent in c++.  For Spark we need this functionality.

**Describe the solution you'd like**
I would like a function that takes a float/double column and returns a column of Bool8s saying if the value is NaN (true) or not (false).

**Describe alternatives you've considered**
No other easy way to do this.

**Comment by beckernick** [comment]
I believe we wrap libcuDF for this in Python:

https://github.com/rapidsai/cudf/blob/e7886b2cb3c3af3fe4cf1832c31d948513e779ee/cpp/src/unary/null_ops.cu#L28

**Comment by revans2** [comment]
For spark, and optionally the internal cudf implementation, null and nan are separate values.  We already have is_null.  We want is_nan

**Comment by beckernick** [comment]
👍 we actually don't currently make that distinction specifically with our isna/isnull ops in Python-land, but it's a very good point
```python
import cudf
import numpy as np
s = cudf.Series([0, None, np.nan], nan_as_null=False)
s.isna()
s
0     0.0
1    null
2     NaN
dtype: float64
```
