### ISSUE TITLE
[FEA] logarithm with variable base, log base 10 and log base 2

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3765]
**Is your feature request related to a problem? Please describe.**
For Spark we would like a log function that takes a variable base to implement the sql log, log10 and log2 functions.  

**Describe the solution you'd like**
This feels like a binary operator that could do it for us.

**Describe alternatives you've considered**
We could do it with the existing unary log and divide.

**Comment by harrism** [comment]
Fixed by #4626
