### ISSUE TITLE
[BUG]Possible memory leak in cuDF read operation

### ISSUE THREAD

**Issue by jcuda000001** [rapidsai/cudf#3767]
**Describe the bug**
Querying a cuDF DataFrame increases the "used memory" of a GPU device. Below df operation increases the device usage in every such query operation and eventually fails with OOM error by filling the device memory:
`df.groupby(['col1']).agg({'measure': 'sum'}).head()`

version: 0.11

**Expected behavior**
System should automatically free up memory

**Environment location: Docker (containerized environment)**
Method of cuDF install: conda (rapids packages are installed using conda package manager)
GPUs - Tesla V100 (32GB mem)

**Comment by kkraus14** [comment]
@jcuda000001 do you happen to have a reproducing dataset or at least dtypes so that we can try to replicate?

**Comment by jcuda000001** [comment]
@kkraus14 
Please find the test dataset on which I could reproduce the issue on v.10 and v.11:
```
import cudf
import numpy as np
import pandas as pd
from sklearn.datasets import make_classification

n_samples = 2**20
n_features = 399
n_info = 300
data_type = np.float32

x, y = make_classification(n_samples=n_samples,
                          n_features=n_features,
                          n_informative=n_info,
                          random_state=123, n_classes=2)

x = pd.DataFrame(x.astype(data_type))

x_cudf = cudf.DataFrame.from_pandas(x)
```
Repeated execution of the following line of querying the cuDF dataframe results in OOM error and the device doesn't seem to release the used GPU mem.
`x_cudf.groupby([0]).count().head()
`
Device: Tesla V100
RAPIDS version: v0.10 and v0.11

Let me know if you need further information.

**Comment by brandon-b-miller** [comment]
This appears to be related to the way that IPython caches python objects referenced from previously executed cells, see [here](https://ipython.org/ipython-doc/3/interactive/reference.html#output-caching-system) for some background information. This appears to occur for other types of objects, not just `cuDF` objects, and manifests most evidently in situations such as these where we have a particularly constrained resource such as GPU memory. It seems as though a [related issue in ipython](https://github.com/ipython/ipython/issues/3452) was closed at some point, however the problem persists. While following up with the IPython community might be useful, I'm not sure we can make any changes in cuDF to alleviate this issue. 

Thankfully we shouldn't see the behavior except for the specific situation where `head()` is called repeatedly inside a notebook. If you save the output in a variable for instance with `y = x_cudf.groupby([0]).agg({1: 'sum'})` and then call `y.head()`, there won't be any memory errors.

**Comment by harrism** [comment]
So @brandon-b-miller @kkraus14 is this not a cuDF bug? Should it be closed?
