### ISSUE TITLE
[FEA]Data load from Hive tables

### ISSUE THREAD

**Issue by jcuda000001** [rapidsai/cudf#3768]
This issue is partly a question as well. 
- What are the best possible options to read data from Hive tables? 
- Can we develop an API that reads the data from Hive tables and loads to a cudf dataframe or dask-cudf dataframe (if it's a large dataset)? 
- Is it wise to involve traditional tools such Hive or Spark to read data from hdfs and then convert to cudf/dask-cudf? OR is it better to use Dask reader(with pyarrow underneath it) to read directly from hdfs files of a hive table ?

I developed something which uses thrift to connect to Hive metastore to collect the metadata  information about hive table being queried (hdfs filename list of table, column list, dtypes etc) and dask-cudf  to read the hdfs file list.  This returns back a dask-cudf dataframe as the following:
`df(cudf or dask-cudf) = table_reader('hive_db_name', 'hive_table_name')`
This retains the speed of dask-cudf/pyarrow file read operation and still gives the simplicity of giving hive table names directly instead of hdfs files to the dask_cudf.read_orc() or dask_cudf.read_parquet(). Is there a better/faster way to read data from Hive tables or is dask-cudf/pyarrow the fastest?

**Describe the solution you'd like**
df(cudf or dask-cudf) = table_reader('hive_db_name', 'hive_table_name')

**Comment by williamBlazing** [comment]
Not cudf exactly, but you can do this with BlazingSQL https://docs.blazingdb.com/docs/apache-hive

**Comment by GregoryKimball** [comment]
We recommend using [dask-sql](https://github.com/dask-contrib/dask-sql) with its experimental support for running SQL queries on CUDA-enabled GPUs.
