### ISSUE TITLE
[FEA] Reductions over string columns

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#3771]
**Is your feature request related to a problem? Please describe.**
Pandas allows for certain types of reductions over string based series objects. In particular one can sum a `string` series and obtain an ordered concatenation of all the elements:

```
>>> pd.Series(['a','b','c']).sum()
'abc'
```

As well as perform `min` and `max` operations that seem to return alphabetical results:

```
>>> pd.Series(['a','b','c']).min()
'a'
```

It would be useful for matching pandas behavior around global reduction operations in cuDF such as `DataFrame.min()`, currently we have to drop some non-numeric columns to proceed in these cases. 

**Describe the solution you'd like**
Match pandas reductions over strings

**Describe alternatives you've considered**
I think a workaround might be possible by reusing some of the categorical machinery we have already. But ultimately native support would be optimal. 

**Additional context**
useful for https://github.com/rapidsai/cudf/issues/2067

**Comment by jrhemstad** [comment]
libcudf support for min/max on strings is already merged as of https://github.com/rapidsai/cudf/pull/3273

The string sum behavior resulting in concatenation was determined to be non-standard for C++ behavior and therefore was not added in libcudf's sum reduction. The python layer will need to be special cased to call the appropriate strings function for concatenating all of the strings in a column into a single string.

**Comment by cwharris** [comment]
Do we have a python equivalent of `scalar`? The string `sum` method has the potential to return a very large string. Perhaps there is a use case where we want to keep that memory on device?

**Comment by AK-ayush** [comment]
> `sum` method has the potential to return a very large string.

@cwharris this is quite possible and which is why even I'd be inclined to get the result as a `nvstrings object`. 
And then I can further use the nvstrings APIs if required without any unnecessary data transfer between host and device.

**Comment by jrhemstad** [comment]
> > `sum` method has the potential to return a very large string.
> 
> @cwharris this is quite possible and which is why even I'd be inclined to get the result as a `nvstrings object`.
> And then I can further use the nvstrings APIs if required without any unnecessary data transfer between host and device.

NVStrings will no longer exist.

**Comment by kkraus14** [comment]
> cudf/3861 implements sum using .join().to_host()[0], but I'm wondering if a python string is what we want back from sum(). Do we have a python equivalent of scalar?

We likely want a Python string back in this case. If there was some GPU library that dealt with a single large string that would be ideal, but as far as I'm aware nothing of that nature exists currently.

**Comment by brandon-b-miller** [comment]
Reductions over numeric columns return a host side scalar IIRC so it makes sense to me to do the same for strings. As a side note it seems like dataframe level reductions copy all the scalar results from all the columns to host, and then back down the the device as a series - maybe we can figure out a way to keep everything on the device in the future.
