### ISSUE TITLE
[FEA] Implement sort-merge join

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cudf#3773]
**Is your feature request related to a problem? Please describe.**
Exploration of #2792 has identified a need to have alternative join algorithms implemented within cudf.

**Describe the solution you'd like**
Implement a sort-merge join for equijoin (equality comparisons). A sort-merge join of two tables will sort the rows of the two tables and use merge logic to identify the results that match the join criteria.

**Describe alternatives you've considered**
We currently have a hash join implementation. We will also need to create a nested loop join implementation (#3772).

**Additional context**

**Comment by harrism** [comment]
After discussion it was determined sort-merge join is not needed currently.
