### ISSUE TITLE
Different behavior for .replace as compared to Pandas

### ISSUE THREAD

**Issue by tunguz** [rapidsai/cudf#3787]
In Pandas I can just pass a dictionary to `.replace,` while in `cudf` it seems that I need to explicitly pass `to_replace` and `replacement`.

**Comment by kkraus14** [comment]
@tunguz Can you give a reproducer here of what your expected behavior is and the stacktrace from cudf?

**Comment by tunguz** [comment]
@kkraus14 The code that works in Pandas is the following one for instance:

`X[mapped_var + '_num'] = X[mapped_var].replace(mapped_values)`

where `mapped_values` is a dictionary.

However, in `cudf` it throws the following error message:

`TypeError: replace() missing 1 required positional argument: 'replacement'`

The following workaround works:

`X[mapped_var + '_num'] = X[mapped_var].replace(to_replace=list(mapped_values.keys()), replacement=list(mapped_values.values()))`

However, there could be issues with the ordering of keys and values in Python 3.6. I understand with Python 3.7 it would not be an issue.

**Comment by galipremsagar** [comment]
Fixed by: #4543
