### ISSUE TITLE
[FEA] Support HALF_UP and HALF_EVEN rounding to a set number of decimal places

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3790]
**Is your feature request related to a problem? Please describe.**
This might need to wait for #3556 to work.  There is also a lot of overlap with #1270.

We want to implement the spark functions round and bround.  Each of them round a number to a set number of decimal places.  One uses HALF_EVEN rounding the other uses HALF_UP rounding.

https://en.wikipedia.org/wiki/Rounding#Rounding_to_the_nearest_integer

We would like APIs to support both, for all numeric types (Floating point, Integer, and fixed point decimal when that is ready)

**Describe the solution you'd like**
I just want something that can do this. Not sure if a Binary op is the right way for this because it does not fit with the rest of the binary ops.

**Describe alternatives you've considered**
I'm not sure there is a good alternative.

**Comment by razajafri** [comment]
What's the status of this feature?

**Comment by harrism** [comment]
https://github.com/rapidsai/cudf/issues/3751#issuecomment-619878870

Like any feature request, needs motivation to prioritize it relative to everything else.
