### ISSUE TITLE
[FEA] bit shift operators

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3791]
**Is your feature request related to a problem? Please describe.**
We would like to be able to support the Spark bit shift operators shiftleft (<<), shiftright (>>), and shiftrightunsigned (>>>). For doing a left bit shift, a right bit shirt and an unsigned right bit shift.

These would only need to be supported for 64 and 32 bit Integer types. But more are not a problem.

**Describe the solution you'd like**
I think this would fit with a binary op.  We want to be able to support shifting A Scalar value by a Column of shift values, a Column of inputs by a Column of shifts values and a Column of inputs by a Scalar shift value.

In all cases a null on either side would result in a null value.

**Describe alternatives you've considered**
I'm not sure if there is a good way to do it otherwise.

**Comment by devavret** [comment]
This seems like it should be done with a UDF. Currently binaryops does not have an option to take a CUDA UDF, only PTX. But if we add that, it should take care of all your binaryops requirements for now and future.

You can then pass a string like this:
```c++
__device__ inline int64_t udfOp(int32_t lhs, int8_t rhs) {
  return lhs << rhs;
}
```
to the binaryops API.

**Comment by kkraus14** [comment]
@devavret that is super unfriendly from a downstream language binding perspective. It would be much easier / cleaner / consistent to define the op once in the C++ and then have everyone else bind to that implementation.

**Comment by devavret** [comment]
@kkraus14, okay maybe bit shift is quite a general operation and deserves to be in libcudf proper
 but I was looking at the general trend of feature requests e.g. https://github.com/rapidsai/cudf/issues/3751 and it seemed worthwhile to allow binary ops to accept CUDA UDFs.

**Comment by kkraus14** [comment]
Even then, there's no easy way for these languages to generate a UDF short of manually defining the string to feed you. We should define these functions at the C++ so all downstream languages can bind to the same implementation.
