### ISSUE TITLE
[FEA] get the sign of a float

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#3794]
**Is your feature request related to a problem? Please describe.**
As a part of Spark we would like to implement the sign/signum functions.  These look at a floating point number and return -1.0 for anything < 0, 0.0 for == 0, 1.0 for > 0.0, NaN for NaN, and null for null.

**Describe the solution you'd like**
This feels like it would work well as a Unary op.

**Describe alternatives you've considered**
We could do this by calling the Binary comparison operators for < equal to, >, isNull and the one we filed for isNaN to then put in in the correct values using copy if else, but that feels really complicated and we would end up materializing a lot of unneeded intermediate results.

**Comment by jrhemstad** [comment]
I think this could just be a `clamp`: 

https://github.com/rapidsai/cudf/pull/3594

**Comment by rgsl888prabhu** [comment]
But, I am not sure whether NAN will be left unmodified. May be I have to to take care of it.

**Comment by rgsl888prabhu** [comment]
@revans2 @jrhemstad I just verified and it work for NAN as well. So clamp will resolve this issue.

**Comment by jrhemstad** [comment]
Actually, I don't think clamp will work as it is now.

From @revans2 description, the only possible values in the output are `-1.0, 0.0, 1.0`.

If you were to call `cudf::clamp` with `lo==-1.0` and `hi=1.0`, then any values between `-1.0` and `1.0` would be unmodified.

**Comment by rgsl888prabhu** [comment]
Ahh, missed that. I can start working on this.

**Comment by rgsl888prabhu** [comment]
@revans2 Me and Jake were discussing to update the clamp/clip to accept two sets of scalars for lo and hi, one to compare and other to replace`[lo = 0, lo_replace = -1.0, hi = 0, hi_replace=1.0]`. Do you have any requirement where you can use such an API apart from this `sign of float`. And if you have, what are the possibilities that the replacement scalars would be null values?

**Comment by revans2** [comment]
I have been thinking about it and I don't see any other use in spark right now for clamp/clip.  So you should be okay with not supporting null values as the replacement.

**Comment by rgsl888prabhu** [comment]
#3594 supports this functionality. I have also added a particular test as per this requirement.
