### ISSUE TITLE
[FEA] Add value_counts method to StringColumn 

### ISSUE THREAD

**Issue by tgrel** [rapidsai/cudf#3801]
**Is your feature request related to a problem? Please describe.**
Currently this code results in an exception:
```import cudf
data = 'a b c d e f g'.split()
s = cudf.Series(data)
s.value_counts()
```
Here's the complete traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-aac58d122c78> in <module>
      4 s = cudf.Series(data)
      5 
----> 6 s.value_counts()

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/series.py in value_counts(self, method, sort)
   1689         if self.null_count == len(self):
   1690             return Series(np.array([], dtype=np.int64))
-> 1691         vals, cnts = self._column.value_counts(method=method)
   1692         res = Series(cnts, index=as_index(vals))
   1693         if sort:

AttributeError: 'StringColumn' object has no attribute 'value_counts'
```

For reference I'm using rapids in a docker image: `nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-base-ubuntu16.04`

`print(cudf.__version__)` results in `0.8.0+0.g8fa7bd3.dirty`

**Describe the solution you'd like**
I'd like to be able to compute value_counts() for a string column as in pandas.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VibhuJawa** [comment]
This seems to be allready present in `0.11` release, fixed by pr: https://github.com/rapidsai/cudf/pull/2415
