### ISSUE TITLE
[FEA] Implement applymap method for StringColumn

### ISSUE THREAD

**Issue by tgrel** [rapidsai/cudf#3802]
**Is your feature request related to a problem? Please describe.**
Currently issuing the following code results in an exception:
```
import cudf
data = 'a b c d e f g'.split()
s = cudf.Series(data)
s.applymap(lambda x : x)
```
The complete traceback:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-8dbb669ac599> in <module>
      4 s = cudf.Series(data)
      5 
----> 6 s.applymap(lambda x : x)

/conda/envs/rapids/lib/python3.6/site-packages/cudf/dataframe/series.py in applymap(self, udf, out_dtype)
   1532             The mask and index are preserved.
   1533         """
-> 1534         res_col = self._column.applymap(udf, out_dtype=out_dtype)
   1535         return self._copy_construct(data=res_col)
   1536 

AttributeError: 'StringColumn' object has no attribute 'applymap'
```

For reference I'm using rapids in a docker image: `nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-base-ubuntu16.04`

`print(cudf.__version__)` results in `0.8.0+0.g8fa7bd3.dirty`

**Describe the solution you'd like**
I'd like to be able to compute `apply_map()` for a string column similarly to `apply` in pandas.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by GregoryKimball** [comment]
Let's close this in favor of #9639
