### ISSUE TITLE
[FEA] Performance - search contains using slow approach

### ISSUE THREAD

**Issue by ChuckHastings** [rapidsai/cudf#3806]
**Is your feature request related to a problem? Please describe.**
The contains (scalar) implementation uses a known inefficient thrust call (find).

**Describe the solution you'd like**
Instead of doing a find and comparing the result to end(), we should do a count_if and return true if count_if > 0.

**Describe alternatives you've considered**

**Additional context**

**Comment by GregoryKimball** [comment]
Thanks @ttnghia for taking a look. For context to this issue here is a [very useful discussion in thrust](https://github.com/NVIDIA/thrust/issues/1016)
