### ISSUE TITLE
[BUG] Possible Memory Leak with Nulls in String Columns

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#3813]
**Describe the bug**
I think there is a possible memory leak when selecting from string columns which contain `Null` values.   Originally I ran nvprof over [test_string](https://github.com/rapidsai/cudf/blob/branch-0.12/python/cudf/cudf/tests/test_string.py) and note unequal cudaMalloc/cudaFree calls.  Below is a minimal reproducible example of the bug

**Steps/Code to reproduce bug**
```python
import cudf
cdf = cudf.Series([None, None, None], index=[11,13,17], dtype=str)

cdf[[True, False, True]]

```

when executing the above with `nvprof` I see more cudaMalloc calls compared with cudaFree

```
(rapids12) bzaitlen@dgx14:~/foobar$ /usr/local/cuda-10.1/bin/nvprof python test_getitem.py 2> >(grep 'cudaMalloc\|cudaFree')
      API calls:   98.41%  1.71107s        57  30.019ms     291ns  1.71042s  cudaMalloc
                    0.03%  538.71us        55  9.7940us     455ns  30.280us  cudaFree
```

Additional call which also demonstrate possible leaks;

- cdf.isnull()
- cdf.notnull()
- cdf.iloc[[1,2]]

**Expected behavior**
I would expect equal number of cudaMalloc and cudaFree calls

**Environment overview (please complete the following information)**
```
# Name                    Version                   Build  Channel
cudf                      0.12.0b200116         py37_1422    rapidsai-nightly
dask-cudf                 0.12.0b200116         py37_1422    rapidsai-nightly
libcudf                   0.12.0b200116     cuda10.1_1422    rapidsai-nightly
```

cc @pentschev @kkraus14

**Comment by ayushdg** [comment]
Here are some numbers for peak memory usage based on experiments:

```python
import cudf
import numpy as np

n_elem = 100_000_000

%%time
cdf = cudf.Series(['ABC', 'DEF']*n_elem)
```

With 0.11 release container:
Time: ~23s
Peak Memory usage: 7927MB

With 0.12 built from source at c4c2d9b04321f2a6acbdde5e6a4fde646fe08edf
Time: ~18s
Peak memory usage: 9343MB

**Comment by kkraus14** [comment]
> Here are some numbers for peak memory usage based on experiments:
> 
> ```python
> import cudf
> import numpy as np
> 
> n_elem = 100_000_000
> 
> %%time
> cdf = cudf.Series(['ABC', 'DEF']*n_elem)
> ```
> 
> With 0.11 release container:
> Time: ~23s
> Peak Memory usage: 7927MB
> 
> With 0.12 built from source at [c4c2d9b](https://github.com/rapidsai/cudf/commit/c4c2d9b04321f2a6acbdde5e6a4fde646fe08edf)
> Time: ~18s
> Peak memory usage: 9343MB

String memory usage is expected to be temporarily increased in 0.12 at the moment. We currently always have the character bytes and offsets buffers in GPU memory, and then if we call an `nvstrings` API we calculate and memoize the `nvstrings` object, and then if we call a libcudf legacy API we calculate and memoize an `nvcategory` object as well.

This will all go away other than the two buffers as we move to using the new libcudf++ APIs.

**Comment by quasiben** [comment]
It's worth noting that this seems to be specific to Strings.  If you change the dtype to int I see no leak.

**Comment by ayushdg** [comment]
> > Here are some numbers for peak memory usage based on experiments:
> > ```python
> > import cudf
> > import numpy as np
> > 
> > n_elem = 100_000_000
> > 
> > %%time
> > cdf = cudf.Series(['ABC', 'DEF']*n_elem)
> > ```
> > 
> > 
> > With 0.11 release container:
> > Time: ~23s
> > Peak Memory usage: 7927MB
> > With 0.12 built from source at [c4c2d9b](https://github.com/rapidsai/cudf/commit/c4c2d9b04321f2a6acbdde5e6a4fde646fe08edf)
> > Time: ~18s
> > Peak memory usage: 9343MB
> 
> String memory usage is expected to be temporarily increased in 0.12 at the moment. We currently always have the character bytes and offsets buffers in GPU memory, and then if we call an `nvstrings` API we calculate and memoize the `nvstrings` object, and then if we call a libcudf legacy API we calculate and memoize an `nvcategory` object as well.
> 
> This will all go away other than the two buffers as we move to using the new libcudf++ APIs.

Thanks @kkraus14  for the context. Am I correct in understanding that the nvstrings and nvcategory objects will be kept in memory only if/when I try calling nvstrings API and/or legacy libcudf API. So during `cudf.Series` creation should the memory usage only include the character and offsets buffer? (Maybe a temporary nvstrings object creation during series creation can explain the higher peak?)
