### ISSUE TITLE
[BUG] Build System Bug for Python nvstrings

### ISSUE THREAD

**Issue by vmjersey** [rapidsai/cudf#3824]
**Describe the bug**
If you have Anaconda installed in non-standard location, Cmake won't find it when you try to install the nvstrings module.

**Steps/Code to reproduce bug**
After you have built Cudf from source.

cd $CUDF/python/nvstrings
python setup.py install

**Expected behavior**

It should build successfully, however on my system it finds the system version of Python which is 2.7.5 and fails several warnings about 'error: PyUnicode_AsUTF8 was not declared in this scope.'  As I understand it.  This is because Cmake is finding the Python 2 version in /usr/lib and not my Anaconda Python 3 version which is installed in /usr/local/Anaconda3/$version.  

**Environment details**
OS: RHEL 7.7
Cmake: 3.15.2
GCC: 6.3
Anaconda: 19.07

**Additional context**
The fix is fairly easy.  On line 153 in python/nvstrings/cpp/CMakeLists.txt, add the following line:
`find_package(PythonInterp)`
This seemed to solve the problem for me.  I don't know if this is the best thing to do for the whole build but it help for this one module.  I also tried setting both PYTHON_LIBRARY and PYTHON_INCLUDE_DIR  environment variables, but this did not seem to do anything.

**Comment by kkraus14** [comment]
nvstrings is going away as part of the libcudf refactor, so likely won't fix this as it will be gone in the very near future.

**Comment by davidwendt** [comment]
nvstrings has been removed from cudf
