### ISSUE TITLE
[FEA] Port NVStrings extract_record to libcudf++

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#3826]
`NVStrings` `extract_record` documentation is here: https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#a38ca4fa55925f7bd107b0c5c9011b034

The NVStrings source file for `extract_record` is here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/custrings/strings/extract_record.cu

This is the `_record` version of the `extract()` API that is defined here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/strings/extract.hpp and implemented here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/src/strings/extract.cu

Suggested API signature:
```
std::unique_ptr<experimental::table> extract_record( strings_column_view const& strings,
                                     std::string const& pattern,
                                     rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```
The size of the output columns should be the number groups defined in the regex `pattern` parameter.

The output will be a new strings column containing the extracted parts of each input column string. If there are 1000 strings in the input column, there will be a 1000 columns in the output. Therefore, I recommend looking at `contiguous_split` to see how they create a single allocate for multiple columns.

**Comment by aschaffer** [comment]
Two questions, off the bat:
1. as far as regexp groups, is the functionality supposed to mirror the paranthesized expressions in Python? And if so, will it follow Python's `re.search(pattern, string)` functionality or `re.findall(pattern, string)`. Example:

>>> str_digits = "([1-9]+)"
>>> str_letters = "([a-zA-Z]+)"

####### serach:
##
>>> xm = re.search(str_digits+str_letters,"123abc")
>>> xm.groups()
('123', 'abc')

>>> xm = re.search(str_digits+str_letters,"abc")
>>> xm.groups()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'groups'

>>> xm = re.search(str_digits+str_letters,"1a2b3c")
>>> xm.groups()
('1', 'a')
>>> xm.group(3)

###### findall:
##
>>> xm = re.findall(str_digits+str_letters,"1a2b3c")
>>> xm
[('1', 'a'), ('2', 'b'), ('3', 'c')]
>>> xm = re.findall(str_digits+str_letters,"1a2b3")
>>> xm
[('1', 'a'), ('2', 'b')]

2. I am to assume the groups are always in sync; i.e., for a given string _every_ group either returns something (not-null), or nothing. IOW, there should _not_ be a situation where, for a given string, some groups return something and other return nothing. Correct?

**Comment by davidwendt** [comment]
I believe the answer is yes to both questions if I understand them correctly.
If it helps you can try out `nvstrings` `extract_record` in Python as part of a `cudf` install.
Here is the Python documentation for it: https://rapidsai.github.io/projects/nvstrings/en/0.11.0/api.html#nvstrings.nvstrings.extract_record
which includes an example:
```
>>> import nvstrings
>>> s = nvstrings.to_device(["a1","b2","c3"])
>>> for result in s.extract_record('([ab])(\d)'):
...     print(result)
["a","1"]
["b","2"]
[None,None]
```

There is also example code in the gtests for the NVStrings C++ code here:
https://github.com/rapidsai/cudf/blob/1ead2d55562b9cd1b80568b86b8b51ab616f3cb8/cpp/custrings/tests/test_extract.cpp#L30

**Comment by aschaffer** [comment]
@davidwendt, thanks for the info. Okay, so simply port existent functionality. No _new_ functionality, then, correct?

**Comment by davidwendt** [comment]
> @davidwendt, thanks for the info. Okay, so simply port existent functionality. No _new_ functionality, then, correct?

Yes, this is a just port to libcudf++.

**Comment by aschaffer** [comment]
@davidwendt, since there is already a _ported_ implementation of `extract_record()` in `cpp/include/cudf/strings/extract.hpp` and `cpp/src/strings/extract.cu`, what is it that's missing? Is this implementation incomplete (or buggy)? Even ported tests exists for this.

It's not clear from the initial comment above what exactly is the scope of the required work for this feature. Could you please elaborate?

**Comment by davidwendt** [comment]
So `extract_record` is different than `extract()`. The latter already exists.
Here is some additional documentation for the Python interface to the C++ APIs  that may help show the distinction. The results are loosely transposes of each other.

The implementation should be in a separate .cu file. They can share a .hpp file for declaration.
You do not need to move custrings to legacy since custrings is already considered 'legacy'.
You should not be updating files/folders in the custrings and nvstrings directories for this task.

**Comment by aschaffer** [comment]
Has `custrings/regex/regex.cuh` been ported, or do I use it as is?

**Comment by aschaffer** [comment]
@davidwendt, about `contiguous_split()`: 

`contiguous_split()` splits **vertically (row-wise)** a table (view) into a collection of table(view)s;

While `extract_record()` must split one column into multiple columns (and collects them into a table). Hence the split here is **horizontal (column-wise)**, _not_ vertical (row-wise).

IOW, `contiguous_split()` returns a collection of tables with _different number of rows_ (summing up to the original number of rows) _but same number of columns_. 

While  `extract_record()` returns a table with _same number of rows_ (as original column) but _different number of columns_ (as many as there are groups instead of the one given column);

Unless I'm missing something I don't see how `contiguous_split()` can help `extract_record()`;

**Comment by aschaffer** [comment]
And in fact I doubt you can use `horizontal_split()` similar to `contiguous_split()` (vertical) because the horizontal split in `extract_record` cannot rely on indexing because same group would have different sizes in different rows, etc.

**Comment by davidwendt** [comment]
The `extract_record` indeed takes a single column and makes multiple columns from it. The number of output columns is actually the number of rows in the input columns. So you can see this would be a scaling problem when you have a column with many strings. Creating many columns using a purely `column` approach would require individual memory allocates per column.

The `contiguous_split()` suggestion is basically about how it is able to build multiple `column_views` pointing to a single memory allocate. There is no reason to return multiple `column`s but rather if we could return multiple `column_view`s with a single allocate. You don't have to use `contiguous_split` but I thought it would be at least a good model for this.

**Comment by aschaffer** [comment]
> The number of output columns is actually the number of rows in the input columns.

I don't understand: you're saying you have as many columns in the output as there are **rows in the input** ?! And the number of output rows is the number of groups, then?

Also, `contiguous_split` relies on chunks of memory of size that is known in advance. `extract_record` would return columns of variable size for each row (or rows of variable size for each column if the claim above is true) of sizes that are _not_ known in advance. 

What seems to be needed here  is a specialized device pool allocator, which might be a separate task in itself.

**Comment by davidwendt** [comment]
Yes, the number of rows for each of the output columns would be the number of groups.

I guess I'm not communicating this very well. You don't have to use `contiguous_split` if it is not convenient. But you should be able to create a vector of `column_view`s that all point to different pieces of a single chunk of device memory. 

You would need to calculate the size of this giant chunk first by running the extract regex fn without doing any real work other than adding up the sizes. This is what the `extract_fn` functor does inside of the `extract.cu` does right now so it should be a good example of on how to do this.

**Comment by aschaffer** [comment]
> So, if you have 1e+9 rows and two groups the output will be a table with 2 rows and 1e+9 columns?

Sorry, I need to iterate on this as it doesn't make sense to me to have a situation like the one above. Why not having an output with 2 columns and 1e+9 rows?

**Comment by davidwendt** [comment]
The output of `extract_record()` for 2 groups would be 1e+9 columns each with 2 rows.
The output of `extract()` for 2 groups is 2 columns each with 1e+9 rows.

The `extract_record()` is generally only useful on a _smallish_ set of rows.

**Comment by aschaffer** [comment]
Okay, so `extract_record` is essentially the transpose of `extract` (if you look at a table as a matrix). Correct?

**Comment by davidwendt** [comment]
> Okay, so `extract_record` is essentially the transpose of `extract` (if you look at a table as a matrix). Correct?

Yes.

**Comment by harrism** [comment]
Deprioritizing for 0.13 as discussed. This function is inefficient and not currently used.

**Comment by kkraus14** [comment]
Closing as it's a year later and this hasn't come up or been needed.
