### ISSUE TITLE
[FEA] Port NVStrings findall_record to libcudf++

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#3827]
`NVStrings` `findall_record` documentation is here: https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#ac3f7e8b012dc69785e61417c4cfcd915

The NVStrings source file for `findall_record` is here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/custrings/strings/findall_record.cu

This is the `_record` version of the `findall_re()` API that is defined here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/include/cudf/strings/findall.hpp and implemented here: https://github.com/rapidsai/cudf/blob/branch-0.12/cpp/src/strings/findall.cu

Suggested API signature:
```
std::vector<std::unique_ptr<column>> findall_re_record( strings_column_view const& strings,
                                     std::string const& pattern,
                                     rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```

The size of each output column will depend on the number of strings located within each input string.

The output will be a new strings column containing the found strings of each input column string. If there are 1000 strings in the input column, there will be a 1000 columns in the output. Therefore, I recommend looking at `contiguous_split` to see how they create a single allocate for multiple columns.

**Comment by kkraus14** [comment]
@davidwendt is this relevant anymore? Should we close this?

**Comment by davidwendt** [comment]
No one has asked for this since porting nvstrings. 
We can close it until someone says they need it.
