### ISSUE TITLE
Some libcudf API functions are prefixed with gdf_, some with gpu_. Unify!

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#383]
The API in `libgdf/include/gdf/cffi/functions.h` has some functions prefixed with `gdf_`, such as:
```gdf_error gdf_radixsort_i8(
    gdf_radixsort_plan_type *hdl,
    gdf_column *keycol,
    gdf_column *valcol);
```
while others are prefixed with `gpu_`:
```
gdf_error gpu_comparison_static_i8(
    gdf_column *lhs, 
    int8_t value, 
    gdf_column *output,
    gdf_comparison_operator operation);
```
I asked around, and it seems this is an afterthought, not the result of any conscious decision. So, I suggest a rename of all `gpu_`-prefixed functions in that file to start with `gdf_` instead, for consistency.

**Comment by jrhemstad** [comment]
Absolutely. I wasn't even aware there were functions that were prefixed with `gpu`.

**Comment by harrism** [comment]
`gdf` will soon be replaced with `cudf`, won't it?

**Comment by eyalroz** [comment]
> `gdf` will soon be replaced with `cudf`, won't it?

Will it? Nobody tells us these things...

**Comment by harrism** [comment]
To my comment a month ago, I *thought* the refactor PR would rename all these things. But I'm glad it didn't -- there was too much in that PR already which made it a difficult one. We won't be doing huge PRs like that again. 

I do think we should unify / update naming to the `cudf` prefix, but it's not super high priority right now. This would be a good issue for someone who wants to gain more familiarity with the libcudf C++/CUDA code base.

**Comment by eyalroz** [comment]
Agree, except for the target developer for this issue. It is, after all, basically a find-replace; you wouldn't have to know the codebase to get it to work. 

But this is a good first issue to teach someone about how the development process on cuDF works: Where to branch from, how to create a PR, updating the changelog, waiting for the CI etc.
