### ISSUE TITLE
[BUG] Running cell 4 of 10 Minutes of cuDF guide gives `ndim mismatch`

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3832]
**Describe the bug**
In our [10 minutes to cuDF guide](https://rapidsai.github.io/projects/cudf/en/0.11.0/10min.html), the way we show how to create a dataframe using lists yields an error `ndim mismatch`.  Suspect an API change.

**Steps/Code to reproduce bug**
```
import cudf
#code from docs
df = cudf.DataFrame([('a', list(range(20))),
('b', list(reversed(range(20)))),
('c', list(range(20)))])
df
```
**Expected behavior**
an output of: 
a | b | c
-- | -- | --
0 | 19 | 0
1 | 18 | 1
2 | 17 | 2
3 | 16 | 3
4 | 15 | 4
5 | 14 | 5
6 | 13 | 6
7 | 12 | 7
8 | 11 | 8
9 | 10 | 9
10 | 9 | 10
11 | 8 | 11
12 | 7 | 12
13 | 6 | 13
14 | 5 | 14
15 | 4 | 15
16 | 3 | 16
17 | 2 | 17
18 | 1 | 18
19 | 0 | 19

**Additional Info**
The code in the docs should probably be changed to this:
```
df = cudf.DataFrame({'a': list(range(20)),
'b': list(reversed(range(20))),
'c': list(range(20))})
df
```

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install:[Docker, with same docker pull from our getting started page]

**Comment by taureandyernv** [comment]
@harrism, @rnyak is working on this through in her doc work.  Can you reassign it to her?  tagging her for awareness

**Comment by rnyak** [comment]
will do the update asap.

**Comment by kkraus14** [comment]
Is this still an issue or has this been resolved?

**Comment by taureandyernv** [comment]
Seems to be resolved.  Closing!  Thanks @kkraus14
