### ISSUE TITLE
pygdf Dataframes throws errors when checked with np.isnan()

### ISSUE THREAD

**Issue by knithinreddy3** [rapidsai/cudf#384]

**Comment by harrism** [comment]
Can you work through the checklist and provide the info it requires? If anything is not applicable, delete that line. Also choose either feature request or bug and delete the other one.

**Comment by knithinreddy3** [comment]
I have made the changes. Thank you!

**Comment by kkraus14** [comment]
You can't run arbitrary numpy / pandas functions against cuDF objects. Even if they do work it will trigger copying the data off the GPU or something worse which is definitely undesired behavior.

We should implement an elementwise `isnan` function though. As a workaround you can do the following for now:
```
import cudf

test = cudf.Series([1,2,3,None,5])
print(test.null_count) # Should return 1

test_nan = cudf.cudautils.expand_mask_bits(len(test), test.nullmask.mem) # Expands bitmask into gpu array of int32s with 1 being valid, 0 being null
test_nan = (cudf.Series(test_nan) == 0) # Flips the 1s and 0s and returns a boolean type
```
