### ISSUE TITLE
[DOC] How to cite?

### ISSUE THREAD

**Issue by ChasNelson1990** [rapidsai/cudf#3849]
## Report needed documentation

**Report needed documentation**
Please add information about how to cite this package (and your other packages) for scientific papers and published reports.
Ideally this would be both on the Git readme and in the documentation of all packages.

**Steps taken to search for needed documentation**
I have looked on the GitHub pages and documentation (stable) as well as checking out the Get Started pages.

Thanks.

**Comment by rnyak** [comment]
@ChasNelson1990 please visit this link: https://rapids.ai/branding.html

You can find RAPIDS CITATION GUIDE here.

**Comment by ChasNelson1990** [comment]
Thanks. As I say, this should really be somewhere more conventional like the git repos and/or docs. I would never think of looking at a companies branding page to find a reference (I would only go there if I worked with the company).
