### ISSUE TITLE
[FEA] null boolean handling for copy_if_else

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#3856]
**Is your feature request related to a problem? Please describe.**
Currently `copy_if_else` throws a logic error if the boolean predicate vector contains any nulls.  When using `copy_if_else` to implement Spark SQL's `IF` or `CASE WHEN` statements, the boolean mask vector is typically the result of a comparison operation which can contain nulls.  It would be great if `copy_if_else` could handle the nulls.

**Describe the solution you'd like**
Spark SQL's `IF` and `CASE WHEN` are implemented like this pseudo-code:
```c++
  if (boolean_result == true) {
    return true_value;
  } else {
    return false_value;
  }
```
As a result, anything that is _not_ true is false, which means null entries are considered false.  Therefore I would either like `copy_if_else` to handle null boolean entries as if they were false or take an optional parameter to include that behavior.

**Describe alternatives you've considered**
This can be worked around by replacing the null entries in the boolean mask with `false` before calling `copy_if_else`, but it requires manifesting an intermediate boolean vector.  It would be more efficient if `copy_if_else` handled null booleans directly.

**Comment by jrhemstad** [comment]
This should be pretty straightforward by using `make_null_replacement_iterator` to replace nulls with `false`.
