### ISSUE TITLE
[FEA] Increasing our test coverage of dask-cudf functionality like groupby-aggregations

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3863]
It may be worthwhile to add (EDIT: more) explicit dask-cudf tests for functionality such as groupby-aggregations (multiple columns, split_out, etc.) and others. As discussed in #1903 , we can still make changes in cuDF that have unanticipated affects in dask-cudf. 

While some issues only surface on the distributed scheduler, most are pervasive. As a result, this could include non-distributed scheduler tests as a starting point, and perhaps eventually include distributed scheduler tests.

EDIT:
Using this as a tracker, too. We should also add unit tests to cover:
- https://github.com/rapidsai/cudf/issues/3954

**Comment by quasiben** [comment]
Hmm, when I looked at the test infrastructure I see multi-column and split_out tests:

https://github.com/rapidsai/cudf/blob/branch-0.12/python/dask_cudf/dask_cudf/tests/test_groupby.py#L168

Is there something else you had in mind ?

**Comment by beckernick** [comment]
Thanks for linking directly to a test @quasiben . An example of where we lack coverage would be testing multiple-aggregations and aggregations on multiple columns with the agg API.

For example, the following slightly adapted examples from the test will fail with #3784:

```python
column = ['b', 'c']
split_out = 2

gddf_result = (
    gddf.groupby(column)
    .mean(split_out=split_out)
    .compute()
    .sort_values()
)
```

```python
gddf_result = (
    gddf.groupby(column)
    .agg({'a':'mean'}, split_out=split_out)
    .compute()
    .sort_values()
)
```

**Comment by beckernick** [comment]
Picking this up. cc @kkraus14 @shwina

**Comment by beckernick** [comment]
This is no longer relevant (has occurred over time). Closing.
