### ISSUE TITLE
[BUG] column length mismatch error in setitem when replacing column

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cudf#3865]
**Describe the bug**
"ValueError: Cannot insert Column of different length into OrderedColumnDict" when trying to replace column in a DataFrame with renumbered values even though column lengths are same.

**Steps/Code to reproduce bug**
>>> import cudf
>>> df= cudf.DataFrame()
>>> df['src']=[0,1,1,2,3]
>>> renumber_map=cudf.Series([10,11,12,13])
>>> df['src']=renumber_map[df['src']]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iroy/.conda/envs/unrenumbering/lib/python3.7/site-packages/cudf/core/dataframe.py", line 528, in __setitem__
    self._data[arg] = column.as_column(value)
  File "cudf/_libxx/table.pyx", line 23, in cudf._libxx.table.OrderedColumnDict.__setitem__
ValueError: Cannot insert Column of different length into OrderedColumnDict

**Expected behavior**
>>> df['src']=renumber_map[df['src']]
>>> df['src']
0    10
1    11
2    11
3    12
4    13
Name: src, dtype: int64

**Comment by Iroy30** [comment]
The error occurs after changes in PR #3799. 
When df['src'] = renumber_map[df['src']] is executed, renumber_map[df['src']] gives:
0    10
1    11
1    11
2    12
3    13
dtype: int64
Length is 5 but the index values are repeated. Hence when setitem is called, line 525 https://github.com/rapidsai/cudf/blob/162097cc9d8687890e0198d49b64e498df0e6903/python/cudf/cudf/core/dataframe.py#L525 gives:
0      10
1      11
1      11
2      12
3      13
4    null
Name: 0, dtype: int64
Length is 6, resulting in the column length mismatch error in as_column()

**Comment by kkraus14** [comment]
@Iroy30 This errors in Pandas as well. The issue is that `renumber_map[df['src']]` results in a duplicate index which Pandas and cuDF don't allow trying to align to the DataFrame. You'd have to call `.reset_index(drop=True)` for example to prevent index alignment.
