### ISSUE TITLE
[FEA] Exposing utilities for use by other projects

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#3872]
**Is your feature request related to a problem? Please describe.**
In BlazingSQL we want to be able to use cudf test utility code or other internal utility code inside of the BlazingSQL codebase. For example we are currently using stuff from the following files 

src/io/csv/legacy/datetime_parser.hpp
src/utilities/legacy/error_utils.hpp
src/utilities/legacy/cudf_utils.h
src/bitmask/legacy/legacy_bitmask.hpp
tests/utilities/column_utilities.cu
tests/utilities/table_utilities.cu
src/utilities/legacy/bit_util.cuh"
tests/utilities/base_fixture.hpp
tests/utilities/column_utilities.hpp
tests/utilities/type_lists.hpp

Note, we are currently still transitioning to libcudf++, so once that migration is complete we may no longer need some of the legacy utilities.

Right now, to cope, we are having to copy over the code we need into our project. This is a temporary solution.

**Describe the solution you'd like**
Would like to see test utilities added to the include folder.

**Describe alternatives you've considered**
We have considered using git submodules or cmake external projects, but these solutions would require a fair amount of work and can be quite problematic.

**Additional context**

**Comment by harrism** [comment]
@williamBlazing could you update the original description above to replace the list of legacy code you need with the non-legacy utility code that you need exposed? We will be removing the legacy folders in a near future release (hopefully 0.14).

**Comment by jrhemstad** [comment]
closed by https://github.com/rapidsai/cudf/pull/6201
