### ISSUE TITLE
cudf not a drop-in replacement for pygdf in OmniSci

### ISSUE THREAD

**Issue by randyzwitch** [rapidsai/cudf#389]
I'm trying to migrate pymapd from pygdf over to cudf, but it doesn't appear to be a drop-in replacement. Here are the relevant lines from pymapd:

https://github.com/omnisci/pymapd/blob/master/pymapd/_parsers.py#L156-#L199

These are my versions:
```python
libgdf                    0.1.0a3            cuda_9.0_452    gpuopenanalytics/label/dev
libgdf_cffi               0.1.0a3                py35_452    gpuopenanalytics/label/dev
arrow-cpp                 0.10.0           py35h70250a7_0    conda-forge
pyarrow                   0.10.0           py35hfc679d8_0    conda-forge
pygdf                     0.1.0a3                py35_266    gpuopenanalytics/label/dev
```

When I run an example with `0.1.0a3`, the result works as expected.

Then I remove pygdf/libgdf and install cudf as `conda install -c numba -c conda-forge -c rapidsai -c defaults cudf=0.2.0`

When I do a simple swap of `cudf` for `pygdf` in the code and run a previously working example, I get the following:

```python
In [1]: import pymapd
   ...: 
   ...: conn = pymapd.connect(user="mapd", host="localhost", password="HyperInteractive", port=9091, dbname="mapd")
   ...: 
   ...: df = conn.select_ipc_gpu("select bike_id from fordgobike_tripdata limit 100")
IPCParser failed: ParseError: cannot read value
Traceback (most recent call last):

  File "<ipython-input-1-c97ba8ef3ee9>", line 5, in <module>
    df = conn.select_ipc_gpu("select bike_id from fordgobike_tripdata limit 100")

  File "/home/rzwitch/pymapd/pymapd/connection.py", line 272, in select_ipc_gpu
    return _parse_tdf_gpu(tdf)

  File "/home/rzwitch/pymapd/pymapd/_parsers.py", line 190, in _parse_tdf_gpu
    reader = GpuArrowReader(schema_buffer, darr)

  File "/home/rzwitch/miniconda3/envs/pymapdfix/lib/python3.5/site-packages/cudf/gpuarrow.py", line 174, in __init__
    self._open()

  File "/home/rzwitch/miniconda3/envs/pymapdfix/lib/python3.5/site-packages/cudf/gpuarrow.py", line 199, in _open
    schema, layoutinfo, dataptr = self._parse_metdata()

  File "/home/rzwitch/miniconda3/envs/pymapdfix/lib/python3.5/site-packages/cudf/gpuarrow.py", line 253, in _parse_metdata
    check_error(ipcparser)

  File "/home/rzwitch/miniconda3/envs/pymapdfix/lib/python3.5/site-packages/cudf/gpuarrow.py", line 234, in check_error
    raise MetadataParsingError(error)

MetadataParsingError: ParseError: cannot read value
```

The error happens here:
https://github.com/omnisci/pymapd/blob/master/pymapd/_parsers.py#L190

Is there any insight you might have around how cudf has changed, especially with respect to how we're trying to pass the buffers into `GpuArrowReader`? I'm not confident at all about how we're trying to do IPC, so if there's an example you can provide to do this more efficiently, I'd love to hear.

**Comment by randyzwitch** [comment]
All of the sizes seem to match (`self._gpu_data_size` = `darr.size` = `dptr.size` = `tdf.df_size`), so I'm inclined to believe that the pointer is wrong. Not sure how to troubleshoot that, but that would indicate the error is somewhere here (I think):

https://github.com/omnisci/pymapd/blob/master/pymapd/_parsers.py#L173-L176

**Comment by kkraus14** [comment]
@randyzwitch What version of Arrow and the Arrow messaging format is MapD + PyMapD using?

**Comment by randyzwitch** [comment]
We're using Arrow 0.10.

**Comment by kkraus14** [comment]
Okay, next suggestion would be to leverage our tests which are passing to compare outputs: https://github.com/rapidsai/cudf/blob/master/python/cudf/tests/test_gpu_arrow_parser.py

You should be able to craft the same output from a test function and a query via pymapd to compare the returned objects and see where they differ.

**Comment by randyzwitch** [comment]
Not sure I follow...how can I compare the results of an OmniSci query if I can't read the data into a cudf? One thing I know is that the schema part works, because we use the same code for our CPU-based queries. It's the GPU portion starting at the pointer I'm having issues with.

**Comment by kkraus14** [comment]
If you interact directly with thrift you can make the call of `sql_execute_gdf` which should return you the `TDataFrame` object that has the associated pointers and metadata used to construct the GPU DataFrame. From there you can basically run through the `_parse_tdf_gpu` function line by line comparing results to known good results to see where you're getting inconsistencies.

**Comment by kkraus14** [comment]
@randyzwitch @andrewseidl Is this resolved or is there still issues in using the `select_ipc_gpu` method?

**Comment by randyzwitch** [comment]
When I am back in the office, I will validate the proposed fix by @andrewseidl

**Comment by randyzwitch** [comment]
It appears that we've resolved this on our side.
