### ISSUE TITLE
[FEA] Optimize `cudf::scatter_to_tables`

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3890]
[`cudf::scatter_to_tables`](https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/copying.hpp#L165-L167)

Original PR / discussion: https://github.com/rapidsai/cudf/pull/2685

It is currently implemented using an N pass algorithm, where `N` is the number of output tables and can be optimized. This algorithm is used in distributed sorting implementations and has been shown to be a potential bottleneck.

**Comment by vuule** [comment]
Added a benchmark to analyze the effect of the number of the output tables on performance:
![image](https://user-images.githubusercontent.com/16005690/73315316-9c5e5c00-41e4-11ea-8af9-2d9eb44b99c1.png)
As expected, the performance becomes worse as the number grows. In addition, the rate at which it degrades becomes larger the more output tables there are.

**Comment by harrism** [comment]
Clearly the scaling curve could be better. However this was deprioritized in favor of #4040 . This could be revisited later.

**Comment by jrhemstad** [comment]
Scatter to tables no longer exists in favor of `cudf::partition`.
