### ISSUE TITLE
[BUG] IndexError: out-of-bound

### ISSUE THREAD

**Issue by RedTailedHawk** [rapidsai/cudf#3912]
Getting an error (`IndexError: out-of-bound`) on `df.tail()` when there's only one row in the data frame.

Works for Pandas, but not for cudf.
![image](https://user-images.githubusercontent.com/8505928/73108959-cdcae500-3ecf-11ea-8a26-693c51c4e8ff.png)

**Comment by kkraus14** [comment]
@RedTailedHawk what version of cuDF are you using? I believe this is fixed in 0.12.

**Comment by RedTailedHawk** [comment]
@kkraus14 we're running 0.11.  Do you have a sense for when 0.12 will be released?

**Comment by kkraus14** [comment]
@RedTailedHawk We went into code freeze at the end of last week, so we're working on release now. Hopefully in the next few days 😄. If you're interested we do publish nightly builds on conda as well: https://anaconda.org/rapidsai-nightly/cudf.

**Comment by kkraus14** [comment]
This is resolved as of 0.13.
