### ISSUE TITLE
[BUG] Dask-cudf loses series name on groupby with protocol=ucx

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#3913]
**Describe the bug**
Dask-cudf loses series name on groupby with `protocol=ucx`. This causes issues downstream when trying to rename/reset_index and the metadata is not in sync with the underlying dataframe.

**Steps/Code to reproduce bug**

```
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import dask_cudf
import cudf
cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1", protocol="ucx",enable_nvlink=True)
client = Client(cluster)
```

```
df = cudf.DataFrame({'a':[1,2,3,4],'b':[5,1,2,5]})
dask_df = dask_cudf.from_cudf(df,npartitions=2)
dask_df_g = dask_df.groupby(['a']).b.sum().compute()
assert(dask_df_g.name == 'b')
```
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-0d1ff1d440f5> in <module>
----> 1 assert(dask_df_g.name == 'b')

AssertionError: 
```

If the same cluster is started up with TCP there is no assertion error and the column name `b` is retained.

**Expected behavior**
The column name is retained downstream

**Environment overview (please complete the following information)**
- Conda: `conda create -n ucx -c rapidsai-nightly -c nvidia -c conda-forge -c defaults cudatoolkit=10.0 rapids=0.12 ucx-py=0.12 python=3.7`

**Environment details**
```
cudf                      0.12.0b200124         py37_2007    rapidsai-nightly
dask-cudf                 0.12.0b200124         py37_2007    rapidsai-nightly
libcudf                   0.12.0b200124     cuda10.0_2002    rapidsai-nightly
dask                      2.9.2                      py_0    conda-forge
dask-core                 2.9.2                      py_0    conda-forge
dask-cuda                 0.12.0a200124           py37_48    rapidsai-nightly
dask-xgboost              0.2.0.dev28      cuda10.0py37_0    rapidsai-nightly
```

**Additional context**

Some additional discussion that might be relevant: #3798 and #3803. 

Unlike TCP since UCX doesn't go via pickle could it be that the issue seems to have popped up again. 

cc: @VibhuJawa

**Comment by beckernick** [comment]
Thanks for the clean reproducible example of this behavior

**Comment by kkraus14** [comment]
Looks like we don't special case the `SeriesGroupBy` serialization code which loses the name. Should be an easy fix.
