### ISSUE TITLE
[FEA] Port parquet.pyx to use non-legacy libcudf APIs

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3924]

**Comment by jdye64** [comment]
@kkraus14 I'm going to tackle this after port json.pyx since there are some tricky moving files around and partial lingering dependencies.

Feel free to assign this to me. Shouldn't take long once I get to it.

**Comment by trxcllnt** [comment]
@jdye64 heads up, there's probably a few changes in https://github.com/rapidsai/cudf/pull/4276 necessary for porting parquet.pyx.
