### ISSUE TITLE
Update operators to use the `type_dispatcher`

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#393]
Soon, PR #379 will be merged (one way or another), and we will be able to use templates instead of switch statements to implement operators taking type-erased `gdf_column`'s.

I suggest we use this issue to 'hang' commits which make this transition for different operators, and close it when they're all done.

I'll begin with what the locations where I see such a transition being appropriate:

* ~~`src/reductions.cu`:~~ fixed by https://github.com/rapidsai/cudf/pull/445
 *  ~~All operators defined using the switch-based `DEF_REDUCE_OP_NUM()` macro (and the macro itself).~~
  * ~~All operators defined using the switch-based `DEF_REDUCE_OP_REAL()` macro (and the macro itself).~~
* `src/io/convert/gdf_to_csr.cu`:
  * `gdf_to_csr()`
  * the, `convertDataElement()` <- Try to get rid of this at some point.
* `src/sqlsops.cu`:
  * ~~The various `gdf_group_by_` operators.~~ obviated by https://github.com/rapidsai/cudf/pull/426

https://github.com/rapidsai/cudf/blob/master/cpp/src/io/csv/csv_reader.cu#L164

https://github.com/rapidsai/cudf/blob/master/cpp/src/io/csv/csv_reader.cu#L764

https://github.com/rapidsai/cudf/blob/master/cpp/src/io/csv/csv_reader.cu#L1056

https://github.com/rapidsai/cudf/blob/c9fbc8b275315d173e4345e10283b6c697fa7556/cpp/src/quantiles/quantiles.cu#L156

https://github.com/rapidsai/cudf/blob/c9fbc8b275315d173e4345e10283b6c697fa7556/cpp/src/sort/segmented_sorting.cu#L241

https://github.com/rapidsai/cudf/blob/c9fbc8b275315d173e4345e10283b6c697fa7556/cpp/src/join/joining.cu#L147

https://github.com/rapidsai/cudf/blob/c9fbc8b275315d173e4345e10283b6c697fa7556/cpp/src/unary/unary_ops.cu#L94 & below 

https://github.com/rapidsai/cudf/blob/c9fbc8b275315d173e4345e10283b6c697fa7556/cpp/tests/utilities/cudf_test_utils.cuh#L78

https://github.com/rapidsai/cudf/blob/branch-0.5/cpp/tests/filter/helper/utils.cuh#L19

https://github.com/rapidsai/cudf/blob/b7356d9204acc5922a54fd7814c105390aaaafa5/cpp/src/filter/filter_ops.cu#L258

  * TO BE CONTINUED

**Comment by eyalroz** [comment]
@harrism : I still see switches over the dtype in  `quantiles.cu`, `sorting.cu`, `segmented_sorting.cu` (there's also `binary_ops.cu` but there it's understandable, perhaps). Consider reopening?

**Comment by devavret** [comment]
@eyalroz where? Are you sure you’re looking at branch 0.7? E.g. I don’t see it in [`quantiles.cu`](https://github.com/rapidsai/cudf/blob/branch-0.7/cpp/src/quantiles/quantiles.cu)

**Comment by eyalroz** [comment]
`quantiles.cu`: You're right, I was looking at the wrong commit.
`sorting.cu`: `gdf_radixsort_generic()`. Note that I'm planning to add support for type-dispatching with implementations for only some of the gdf_dtype values; but you can still pull it off by defaulting to returning `GDF_UNSUPPORTED_TYPE` in the non-specialized templated code.
`segmented_sorting.cu`: `gdf_segmented_radixsort_generic()`

**Comment by devavret** [comment]
@eyalroz can you please provide the GitHub link to those files, for some reason I cannot find it.

**Comment by eyalroz** [comment]
@devavret : Oh, no, I got my branch origins mixed up. I take it back... this was correctly closed. Sorry for wasting your time.
