### ISSUE TITLE
[FEA] Port unaryops.pyx to use non-legacy libcudf APIs

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3949]

**Comment by cwharris** [comment]
libcudf++ offers `is_nan` support for floating point types. Should we use this for `column.isna`? If so, should we fail for non- floating point types, or fall back to `column.isnull`?

**Comment by cwharris** [comment]
Suggest we keep it as-is for now, so we don't have to write new tests during this port.
