### ISSUE TITLE
[BUG] cuDF Series pickling broken in 0.13 

### ISSUE THREAD

**Issue by dantegd** [rapidsai/cudf#3955]
**Describe the bug**
Pickling cuDF Series seems broken, and seems to be what is blocking cuML's CI in the corresponding branch-0.13. DataFrame pickling seems to work fine though. 

**Steps/Code to reproduce bug**
See example: 

```python
>>> import cudf
>>> import pickle

>>> cudf.__version__
'0.13.0a+644.gc404768'

>>> a = cudf.Series([1,2,3,4])
>>> with open('a.pickle', 'wb') as pf:
...     pickle.dump(a, pf)
...
>>> with open('a.pickle', 'rb') as pf:
...     b = pickle.load(pf)
...
>>> b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/cudf/core/series.py", line 560, in __repr__
    preprocess.astype("O").fillna("null").to_pandas().__repr__()
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/cudf/core/series.py", line 1426, in to_pandas
    s = self._column.to_pandas(index=index)
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/cudf/core/column/string.py", line 629, in to_pandas
    pd_series.index = index
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/pandas/core/generic.py", line 5192, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/pandas/core/series.py", line 444, in _set_axis
    self._data.set_axis(axis, labels)
  File "/home/dante/miniconda3/envs/cudf13-0127/lib/python3.7/site-packages/pandas/core/internals/managers.py", line 183, in set_axis
    "values have {new} elements".format(old=old_len, new=new_len)
ValueError: Length mismatch: Expected axis has 1 elements, new values have 4 elements

>>> c = cudf.DataFrame()
>>> c['1'] = [1,2,3,4]
>>> c['2'] = [2,3,4,5]

>>> with open('c.pickle', 'wb') as pf:
...     pickle.dump(c, pf)
...
>>> with open('c.pickle', 'rb') as pf:
...     d = pickle.load(pf)
...
>>> d
   1  2
0  1  2
1  2  3
2  3  4
3  4  5
```

**Expected behavior**
Pickling working 

**Environment overview (please complete the following information)**
 - Environment location: Bare metal (and GPUCI container)
 - Method of cuDF install: conda, nightly: 
```
cudf                      0.13.0a200127          py37_644    rapidsai-nightly
libcudf                   0.13.0a200127      cuda10.1_644    rapidsai-nightly
```

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit f44a91f90257e7fb9cedabd13e2a147f1f7e8223 (HEAD -> branch-0.13, origin/branch-0.13)
     Merge: c4047687e c9b85f45f
     Author: OlivierNV <45697062+OlivierNV@users.noreply.github.com>
     Date:   Mon Jan 27 18:23:07 2020 -0800

     Merge pull request #3953 from jlowe/fix-buffer-size-overflow

     Fix overflow in column_buffer when computing the device buffer size
     **git submodules***
     -b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub
     -bcd545071c7a5ddb28cb6576afc6399eb1286c43 thirdparty/jitify
     -cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux gv100-1804 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Mon Jan 27 20:30:55 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 430.40       Driver Version: 430.40       CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Quadro GV100        Off  | 00000000:17:00.0 Off |                  Off |
     | 31%   43C    P2    26W / 250W |    746MiB / 32508MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro GV100        Off  | 00000000:65:00.0  On |                  Off |
     | 31%   43C    P0    28W / 250W |    688MiB / 32505MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0     18379      C   python                                       735MiB |
     |    1      1505      G   /usr/lib/xorg/Xorg                            71MiB |
     |    1      1580      G   /usr/bin/gnome-shell                          62MiB |
     |    1      2216      G   /usr/lib/xorg/Xorg                           249MiB |
     |    1      2370      G   /usr/bin/gnome-shell                         227MiB |
     |    1      3325      G   ...quest-channel-token=4714508060444853452    58MiB |
     |    1      3583      G   /usr/lib/firefox/firefox                       6MiB |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
     Stepping:            4
     CPU MHz:             1200.078
     CPU max MHz:         4000.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6999.82
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            8448K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d

     ***CMake***

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda-10.1u2/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243

     ***Python***
     /home/dante/miniconda3/envs/cudf13-0127/bin/python
     Python 3.7.6

     ***Environment Variables***
     PATH                            : /usr/local/cuda-10.1u2/bin:/home/dante/miniconda3/envs/cudf13-0127/bin:/home/dante/miniconda3/condabin:/usr/local/cuda-10.1u2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/dante/miniconda3/envs/cudf13-0127
     PYTHON_PATH                     :

     ***conda packages***
     /home/dante/miniconda3/condabin/conda
     # packages in environment at /home/dante/miniconda3/envs/cudf13-0127:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.13.0a200127          py37_644    rapidsai-nightly
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cupy                      7.1.1            py37h0c141eb_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.13.0a200127      cuda10.1_644    rapidsai-nightly
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnvstrings              0.13.0a200127      cuda10.1_644    rapidsai-nightly
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.13.0a200127       cuda10.1_98    rapidsai-nightly
     libstdcxx-ng              9.1.0                hdf63c60_0
     llvmlite                  0.31.0           py37h8b12597_0    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     nccl                      2.4.6.1              cuda10.1_0    nvidia
     ncurses                   6.1                  he6710b0_1
     numba                     0.48.0           py37hb3f55d8_0    conda-forge
     numpy                     1.17.5           py37h95a1406_0    conda-forge
     nvstrings                 0.13.0a200127          py37_644    rapidsai-nightly
     openssl                   1.1.1d               h516909a_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       20.0.2                   py37_0
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     python                    3.7.6                h0371630_2
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  7.0                  h7b6447c_5
     rmm                       0.13.0a200127           py37_98    rapidsai-nightly
     setuptools                45.1.0                   py37_0
     six                       1.14.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1003    conda-forge
     sqlite                    3.30.1               h7b6447c_0
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.8                hbc83047_0
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wheel                     0.33.6                   py37_0
     xz                        5.2.4                h14c3975_4
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.3                h3b9ef0a_0    conda-forge

</pre></details>

**Additional context**
As mentioned in the beginning of the issue, this is currently a blocker for CI for cuML for branch-0.13. 

Edit: had pasted the wrong output of print_env

**Comment by jakirkham** [comment]
For a reproduce that doesn't involve writing to disk...

```python
In [1]: import pickle                                                           

In [2]: import cudf                                                             

In [3]: a = cudf.Series([1,2,3,4])                                              

In [4]: p = pickle.dumps(a)                                                     

In [5]: pickle.loads(p)
```

**Comment by jakirkham** [comment]
Was wondering if this might be related to pickling changes made to `rmm.DeviceBuffer` recently ( https://github.com/rapidsai/rmm/pull/258 ) (though I guess this would have surfaced much sooner), but that doesn't appear to be the case as this can be reproduced using a CuPy array instead.

```python
In [1]: import pickle

In [2]: import cupy

In [3]: import cudf

In [4]: a = cudf.Series(cupy.asarray([1,2,3,4]))

In [5]: p = pickle.dumps(a)

In [6]: pickle.loads(p)
```

**Comment by jakirkham** [comment]
After playing with [the `__reduce__` implementation]( https://github.com/rapidsai/cudf/blob/f44a91f90257e7fb9cedabd13e2a147f1f7e8223/python/cudf/cudf/core/series.py#L151-L152 ) more directly it appears this can be reproduced without pickling.

```python
In [1]: import cudf

In [2]: a = cudf.Series([1,2,3,4])

In [3]: cudf.Series(a._data, a.index)
```

**Comment by jakirkham** [comment]
Addressed with PR ( https://github.com/rapidsai/cudf/pull/3970 ).
