### ISSUE TITLE
[BUG] OSError vs ImportError

### ISSUE THREAD

**Issue by xmnlab** [rapidsai/cudf#3956]
**Describe the bug**
In some cases import cudf is rasing `OSError` eg: #3529

**Expected behavior**
Normally when the import doesn't work we expect `ImportError`

Is it possible to force/ensure an `ImportError` instead of `OSError`?

thanks a lot for the attention!

**Comment by kkraus14** [comment]
#3529 is from 0.6 which is an extremely old version at this point. In general if there's a missing library we throw an `ImportError`, but if Cython fails to load a shared library that it needs I'm not sure exactly what error will be thrown, but it's likely out of our control. Are you seeing an `OSError` in practice somewhere? Could you give us a stacktrace?

**Comment by xmnlab** [comment]
@mikehinchey could you share your case here? thanks!

**Comment by kkraus14** [comment]
No reproducer, so closing. Feel free to reopen if you have a stacktrace / reproducer.
