### ISSUE TITLE
[DOC]Need Docs for Categorical Accessor

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#3962]
## Report needed documentation

**Report needed documentation**
There is no documentation of the Categorical Accessor found here: https://github.com/rapidsai/cudf/blob/branch-0.13/python/cudf/cudf/core/column/categorical.py.  if you don't dig through the repo, you won't know it exists.

**Describe the documentation you'd like**
Something similar to this: https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html, where available commands and usage can be found

**Steps taken to search for needed documentation**
Searched the docs site, https://docs.rapids.ai/api/cudf/nightly/, and looked in the cudf repo and found no doc strings.

**Comment by galipremsagar** [comment]
Closing as this is resolved by https://github.com/rapidsai/cudf/issues/3121
