### ISSUE TITLE
[FEA] Porting nvtext to libcudf++

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#3965]
NVText is a set higher-level natural language processing functionality that is built on cuStrings primitives. With native string support in cudf::column, nvstrings data structures will eventually disappear. But as these disappear, there is no longer a bridge to NVText.

To remedy this, I propose the following in the short-term:

- Port an initial set of NVText functions to use libcuDF APIs, including:
    - tokenize
    - normalize_spaces
    - ngrams_tokenize
    - token_count

Eventually, I think we should both fully port NVText to libcuDF++ and also find a home for much of the functionality in either the cuML preprocessing namespace or maintain a separate NLP library.

Interested to hear from others. @kkraus14 @davidwendt @harrism @randerzander

**Comment by kkraus14** [comment]
From the C++ side, the ask is to initially port the following into libcudf++ APIs:

- `NVText::tokenize`
- `NVText::normalize_spaces`
- `NVText::ngrams_tokenize`
- `NVText::token_count`

These are the high priority functions that are used in workflows today that we need to port ASAP.

We'll follow up with an issue to build a Cython / Python interface to the libcudf++ APIs.

**Comment by davidwendt** [comment]
So porting these to C++ means making these strings API functions?
For example, `tokenize` becomes a strings defined in a `cudf/strings` header like:
```
std::unique_ptr<column> tokenize(strings_column_view const& strs, std::string const& delimiter);
```
And there will be nvtext class in C++ or in Python?
I suppose we could put these functions in a 'nvtext' namespace.

**Comment by kkraus14** [comment]
I'm fine with an `nvtext` namespace both for the C++ and for the Python. Eventually we'll likely want to roll these out into a cuML preprocessing library or a separate library entirely, but we can start with them in libcudf for now and adjust later.

**Comment by davidwendt** [comment]
Closing this. The python interface is covered in #4371
