### ISSUE TITLE
[FEA] Integrate string typecasting APIs underneath unary `cast` API

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3966]
Currently there's a bunch of different string typecasting functions in the `cudf::strings` namespace for converting various types to strings, i.e. https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/strings/convert/convert_integers.hpp#L69

These should be integrated into the unary cast implementation (https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/unary.hpp#L93).

For booleans, lets just default to `True` and `False` for the relevant strings via the cast API.

**Comment by kkraus14** [comment]
For handling timestamps, Python ideally wants a default format based on the units:
```
nanoseconds: %Y-%m-%dT%H:%M:%S.(%ns) (9 decimal places)
microseconds: %Y-%m-%dT%H:%M:%S.%f (6 decimal places)
milliseconds: %Y-%m-%dT%H:%M:%S.(%f[:-3]) (only 3 decimal places)
seconds: %Y-%m-%dT%H:%M:%S
days: %Y-%m-%d
```

Note that nanoseconds and milliseconds don't have a format string that can properly represent them, but that's the format that we'd expect / want.

**Comment by rgsl888prabhu** [comment]
Closing this as string type casting to other types such as float, integers and vice-versa doesn't agree with C/C++ realm.
