### ISSUE TITLE
[BUG] cuDF factorize() produces wrong size output

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#3973]
**Describe the bug**
When you factorize the cuDF Series of length 10 below, it returns a cuDF Series of length 20. Without setting the DataFrame index, it works correctly. Somehow by setting the index the bug is generated.

**Steps/Code to reproduce bug**
    `x = gd.DataFrame()`
    `x['col1'] = ['C','H','C','W','W','W','W','W','C','W']`
    `x['col2'] = [2992443., 2992447., 2992466., 2992440., 2992441., 2992442.,
       2992444., 2992445., 2992446., 2992448.]`
    `x = x.set_index('col2')`
    `y,_ = x.col1.factorize()`
    `y.shape`
    `#OUTPUTS (20,)`

**Expected behavior**
We expect that the length of `y` above should be `(10,)` equal to length of `x`.

**Environment overview (please complete the following information)**
Conda install on Jan 28, 2020 using nightly build. The cuDF version is '0.12.0b+2007.g03d22b3'

**Comment by kkraus14** [comment]
Likely just an index alignment issue where we're using Series internally instead of columns.

**Comment by galipremsagar** [comment]
Fixed by #4609
