### ISSUE TITLE
[FEA] Move the `take()` method to `Frame`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#3981]
Since `take()` is common to `Series`, `DataFrame` and `Index`, a common implementation can be provided in the `Frame` base class.

**Comment by beckernick** [comment]
Is this still relevant @shwina @vyasr ? I see that Frame.take exists and it looks like Series.take, DataFrame.take, and implicitly Index.take use it.

**Comment by vyasr** [comment]
Good find, looks like this was resolved by #9464.
