### ISSUE TITLE
[FEA] Port nvstrings Case Handling functions to cuDF Python/Cython

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3987]
- [ ] `nvstrings.nvstrings.capitalize` --> `Series.str.capitalize` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.capitalize.html)
- [ ] `nvstrings.nvstrings.islower` --> `Series.str.islower` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.islower.html)
- [ ] `nvstrings.nvstrings.isupper` --> `Series.str.isupper` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.isupper.html)
- [ ] `nvstrings.nvstrings.lower` --> `Series.str.lower` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.lower.html)
- [ ] `nvstrings.nvstrings.swapcase` --> `Series.str.swapcase` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.swapcase.html)
- [ ] `nvstrings.nvstrings.title` --> `Series.str.title` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.title.html)
- [ ] `nvstrings.nvstrings.upper` --> `Series.str.upper` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.upper.html)

**Comment by cwharris** [comment]
May break this in to multiple PRs.

**Comment by cwharris** [comment]
It looks like `isupper` and `islower` hasn't been ported / declared in `cudf::strings` yet. Those methods exist in `nvstrings`'s `attrs.cu`.

**Comment by kkraus14** [comment]
@davidwendt do you know where these functions landed?

**Comment by kkraus14** [comment]
@cwharris looks like the signature changed per this PR: https://github.com/rapidsai/cudf/pull/3159

**Comment by davidwendt** [comment]
> @davidwendt do you know where these functions landed?

I made these into a single method called `cudf::strings::all_characters_of_type()`
https://github.com/rapidsai/cudf/blob/60daf4b8c112d9b6a6d0d7dd4701881f76b406c4/cpp/include/cudf/strings/char_types/char_types.hpp#L56
You pass in any combination of flags from this enum:
https://github.com/rapidsai/cudf/blob/60daf4b8c112d9b6a6d0d7dd4701881f76b406c4/cpp/include/cudf/strings/char_types/char_types.hpp#L30

**Comment by cwharris** [comment]
Thank you! :D

**Comment by cwharris** [comment]
It would appear we have some discrepancies between pandas and the c++ implementations.

```
=============================================== FAILURES ================================================
_________________________________ test_string_char_types_isupper[data5] _________________________________

data = ['A B', '1.5', '3,000']

    @pytest.mark.parametrize("data", _string_types_check_data)
    def test_string_char_types_isupper(data):
        gs = Series(data)
        ps = pd.Series(data)
    
        assert_eq(gs.str.isdecimal(), ps.str.isdecimal())
        assert_eq(gs.str.isalnum(), ps.str.isalnum())
        assert_eq(gs.str.isalpha(), ps.str.isalpha())
        assert_eq(gs.str.isdigit(), ps.str.isdigit())
>       assert_eq(gs.str.isupper(), ps.str.isupper())

cudf/tests/test_string.py:1165: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/_libs/testing.pyx:65: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: Series are different
E   
E   Series values are different (33.33333 %)
E   [left]:  [False, False, False]
E   [right]: [True, False, False]

pandas/_libs/testing.pyx:178: AssertionError
_________________________________ test_string_char_types_islower[data3] _________________________________

data = ['1234567890', 'de', '1.75', '-34', '+9.8', '7¼', ...]

    @pytest.mark.parametrize("data", _string_types_check_data)
    def test_string_char_types_islower(data):
        gs = Series(data)
        ps = pd.Series(data)
    
>       assert_eq(gs.str.islower(), ps.str.islower())

cudf/tests/test_string.py:1173: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/_libs/testing.pyx:65: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: Series are different
E   
E   Series values are different (9.09091 %)
E   [left]:  [False, True, False, False, False, False, False, False, False, False, False]
E   [right]: [False, True, False, False, False, False, True, False, False, False, False]

pandas/_libs/testing.pyx:178: AssertionError
_________________________________ test_string_char_types_islower[data4] _________________________________

data = ['one', 'one1', '1', '']

    @pytest.mark.parametrize("data", _string_types_check_data)
    def test_string_char_types_islower(data):
        gs = Series(data)
        ps = pd.Series(data)
    
>       assert_eq(gs.str.islower(), ps.str.islower())

cudf/tests/test_string.py:1173: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/_libs/testing.pyx:65: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: Series are different
E   
E   Series values are different (25.0 %)
E   [left]:  [True, False, False, False]
E   [right]: [True, True, False, False]

pandas/_libs/testing.pyx:178: AssertionError
============================= 3 failed, 60 passed, 3491 deselected in 3.26s =============================
```

**Comment by cwharris** [comment]
It may boil down to these:
```
_________________________________ test_string_char_types_islower[data9] _________________________________

data = ['a1', 'A1', 'a!', 'A!', '!1', 'aA']

    @pytest.mark.parametrize("data", _string_types_check_data)
    def test_string_char_types_islower(data):
        gs = Series(data)
        ps = pd.Series(data)
    
>       assert_eq(gs.str.islower(), ps.str.islower())

cudf/tests/test_string.py:1174: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pandas/_libs/testing.pyx:65: in pandas._libs.testing.assert_almost_equal
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   AssertionError: Series are different
E   
E   Series values are different (33.33333 %)
E   [left]:  [False, False, False, False, False, False]
E   [right]: [True, False, True, False, False, False]

pandas/_libs/testing.pyx:178: AssertionError
```

**Comment by kkraus14** [comment]
Pandas follows general Python string logic: https://docs.python.org/3/library/stdtypes.html#str.isupper

Seems like we're handling non-case characters differently here.

**Comment by cwharris** [comment]
It would appear that Pandas ignores non-alpha char types.
```
                'a1',  'A1',  'a!',  'A!',  '!1',  'aA'
pandas isupper  False, True,  False, True,  False, False 
  cudf isupper  False, False, False, False, False, False

pandas islower  True,  False, True,  False, False, False
  cudf islower  False, False, False, False, False, False
```

**Comment by cwharris** [comment]
Should we spend time addressing this?

I'm thinking maybe not for this PR.

**Comment by kkraus14** [comment]
We should address it but not necessarily in this PR. Maybe just add a warning and xfail the relevant tests for now?

**Comment by davidwendt** [comment]
> It would appear that Pandas ignores non-alpha char types.
> 
> ```
>                 'a1',  'A1',  'a!',  'A!',  '!1',  'aA'
> pandas isupper  False, True,  False, True,  False, False 
>   cudf isupper  False, False, False, False, False, False
> 
> pandas islower  True,  False, True,  False, False, False
>   cudf islower  False, False, False, False, False, False
> ```

Was there an issue created for this?
