### ISSUE TITLE
CMake Error : NVSTRINGS

### ISSUE THREAD

**Issue by nasica88** [rapidsai/cudf#399]
I am trying to build cudf on Redhat 7.5 ppc64le.   I have CUDA 9.2 installed on it.

On running the following as instructed, I get the following error messages concerning to NVSTRINGS.

$ MAKEFLAGS=-j16 cmake .. -DHASH_JOIN=ON -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX
...
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
NVSTRINGS_INCLUDE_DIR
NVSTRINGS_LIBRARY

I checked the following and confirmed that fixes #362 and #363 are already applied, but still I get the error.

https://github.com/rapidsai/cudf/pull/364

I find nothing similar to nvstrings.h or libnvstring.so on my CUDA installation.   Did I miss something ?

**Comment by kkraus14** [comment]
@nasica88 if you're not using conda there isn't an easy way to install nvstrings yet. I'd recommend using conda and then you can install `nvstrings` with:
```bash
conda install -c rapidsai -c nvidia -c numba -c conda-forge -c defaults nvstrings
```

If you're not using conda you'd have to download the package from https://anaconda.org/nvidia/nvstrings/files and move the `.so` and `.h` files into the appropriate directories for cmake to find them.

**Comment by nasica88** [comment]
@kkraus14  So nvstrings is not open source ?  Since I am using Redhat ppc64le, which is not binary-compatible with x86, I cannot use the .so files directly.  I need to have the source codes, if available.

**Comment by adamjm** [comment]
@kkraus14 Has there been any progress on this issue? I am really keen to test this on a ppc64le based machine. I would also be happy to test any code on this ppc64le machine.

**Comment by datametrician** [comment]
@adamjm no progress yet, I apologize, but it's on our radar

**Comment by thomcom** [comment]
You can install nvstrings via https://github.com/rapidsai/custrings, now.

**Comment by thomcom** [comment]
Were you able to make progress on your issue @nasica88 ? Can we close this one?

**Comment by nasica88** [comment]
@thomcom  Yes, I had an error but it was addressed in [1384](https://github.com/rapidsai/cudf/issues/1384)
