### ISSUE TITLE
[FEA] Port NVStrings capitalize to libcudf++

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3995]
This is to cover porting of the `capitalize` function in NVStrings to libcudf++.

NVStrings documentation for `capitalize`: https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#a2c71da05b27c0df1488a55ca5985f266

**Comment by aschaffer** [comment]
I assume the API should look like this:
```
std::unique_ptr<experimental::table> capitalize( strings_column_view const& strings,
                                         rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```

@davidwendt, please advise.

**Comment by aschaffer** [comment]
An example of how I understand this should work:
```string_tbl = ["tesT1", "a Test", "Another Test"];
capt_string_tbl = ["Test1", "A test", "Another test"]
```
IOW, in the result, the 1st character always is always upper-case; and **all** remaining characters are lower-case.  Correct?

**Comment by kkraus14** [comment]
@aschaffer correct, this follows the behavior of: https://docs.python.org/3/library/stdtypes.html#str.capitalize

**Comment by davidwendt** [comment]
Another set of documentation in case it helps:
https://rapidsai.github.io/projects/nvstrings/en/0.11.0/api.html#nvstrings.nvstrings.capitalize

**Comment by aschaffer** [comment]
OK, how about the C++ API suggested above? Do we have agreement on that?

Once we agree on it, I'll adopt similar APIs for `title` and `wrap` (https://github.com/rapidsai/cudf/issues/3996 and https://github.com/rapidsai/cudf/issues/3997). The plan is to implement them one at a time but I think there is a good chance for factoring out a common part of the functionality: essentially a generic transform on the string rows, where only the transforming functor should be different between these 3 tasks (`capitalize`, `title`, `wrap`).

**Comment by davidwendt** [comment]
I would've expected a column of strings to produce another column of strings per captilize, etc. and not a table of columns.
```
std::unique_ptr<column> capitalize( strings_column_view const& strings,
                                         rmm::mr::device_memory_resource* mr = rmm::mr::get_default_resource());
```
Also, you should look at the current `to_upper()` and `to_lower()` functions for details on how properly convert case on UTF-8 characters.
https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/src/strings/case.cu
