### ISSUE TITLE
[FEA] Port NVStrings title to libcudf++

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3996]
This is to cover porting of the `title` function in NVStrings to libcudf++.

NVStrings documentation for `title`: https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#a0c802b3e2fbd2710490ab19dbd988756

**Comment by harrism** [comment]
@aschaffer I believe this should be closed now too? Implemented by #4063?

**Comment by aschaffer** [comment]
> 
> 
> @aschaffer I believe this should be closed now too? Implemented by #4063?

@harrism, yes! it went into #4063.
