### ISSUE TITLE
[FEA] Port NVStrings wrap to libcudf++

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#3997]
This is to cover porting of the `wrap` function in NVStrings to libcudf++.

NVStrings documentation for `wrap`: https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#ac7b63041edf7e30cdbe8676c75f38635

**Comment by aschaffer** [comment]
The documentation on wrap (https://rapidsai.github.io/projects/libnvstrings/0.11.0/classNVStrings.html#ac7b63041edf7e30cdbe8676c75f38635) is a bit unclear on `width`.
It says:
"Attempts to make each line less than or equal to width characters"
which means `width` is the _maximum_ size of a line.
but then:
```
width The minimum number of characters for a line in each string.
```
Is it the `minimum` or the `maximum` number of a characters for a line?

**Comment by aschaffer** [comment]
Another point to clarify the API: the newly created _lines_ should go on separate rows in the return, or they should stay in same row, just with newlines between them?

IOW, is the number of _rows_ in the return the same as the input?

**Comment by aschaffer** [comment]
Also:

1. What happens with groups of spaces? I assume the whole group gets replaced by just one newline, correct? i.e., `"test     something"` becomes  `"test\nsomething"`, right?
2. What happens with the spaces at the end of a string? I assume they are ignored, correct? Example:  `"more tests    "` becomes `"more\ntests"`, right?
