### ISSUE TITLE
[BUG] cannot run docker from Centos 7

### ISSUE THREAD

**Issue by faywang123** [rapidsai/cudf#4004]
**Describe the bug**
The API read_csv failed with unspecified launch failure: 

Python 3.6.7 | packaged by conda-forge | (default, Nov  6 2019, 16:19:42)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>> df = cudf.read_csv("abc.tsv", sep='\t')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gfn/anaconda3/lib/python3.6/site-packages/cudf/io/csv.py", line 82, in read_csv
    index_col=index_col,
  File "cudf/_lib/csv.pyx", line 41, in cudf._lib.csv.read_csv
  File "cudf/_lib/csv.pyx", line 205, in cudf._lib.csv.read_csv
RuntimeError: rmm_allocator::allocate(): RMM_ALLOC: unspecified launch failure

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]: Bare-metal
 - Method of cuDF install: [conda, Docker, or from source]: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

The command to install cudf:
conda install -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.11 python=3.6

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

Cannot locate print_env.sh. Please provide absolute path. 

**Additional context**

**Comment by kkraus14** [comment]
Hi @faywang123 what's the size of the CSV you're reading? Data types? What type of GPU are you calling this from?

**Comment by faywang123** [comment]
hi Kraus,
   I switched to use rapids docker on my centos env instead of installing rapids directly into my anaconda environment

My Centos version: CentOS Linux release 7.6.1810 (Core)
My docker version: Docker version 18.09.3, build 774a1f
 
(1) I am able to pull the image:
docker pull rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04

docker images:
rapidsai/rapidsai   cuda10.0-runtime-ubuntu16.04   23341e245c4d        7 weeks ago         8.25GB

(2) but the docker run command failed with
 unknown flag: --gpus
See 'docker run --help'.

docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04

Please advise!

**Comment by faywang123** [comment]
I upgraded my docker to version 19
Docker version 19.03.5, build 633a0ea

The docker run command still failed:
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by harrism** [comment]
Closing due to no response. Please reopen if needed
