### ISSUE TITLE
dockerfile error

### ISSUE THREAD

**Issue by lyl472324464** [rapidsai/cudf#401]
nvstrings can not be installed correctly if you don't add "-c nvidia" at step 20.

## Reporting a bug

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by harrism** [comment]
PR #354 fixes this. Please reopen if not.
