### ISSUE TITLE
[FEA] Implement Is Not Distinct From comparator in Joins

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#4010]
**Is your feature request related to a problem? Please describe.**
When joining it would be very useful to have a flag that allows you to use the operator "IS NOT DISTINCT FROM". This operator has the same truth table as = with the condition that null joins to null.

**Describe the solution you'd like**
Add to both python and libcudf++ join api a flag parameter that the user can use to indicate if null = null can be results in those rows being part of the join output.

**Describe alternatives you've considered**
Preprocessing the inputs to the join in order to change nulls to a value outside the range of values in the columns. Sometimes this will not be possible with high cardinality data on low cardinality types (thing randomly distributed int8).
**Additional context**
This will allow us to implement count distinct without having to perform an extra pre processing step and allow us to return distinct null count for null groups. e.g. when a user does something like 

```
select count(distinct(a)) from table_1 group by b
```
when can include the distinct count of the group where b = null.

**Comment by felipeblazing** [comment]
To give somemore context. A query like  the following on TPC-H lineitem table 

```
select count(l_discount), sum(l_tax), sum(l_orderkey),  count(distinct(l_orderkey)), count(distinct(l_suppkey)) from lineitem where l_shipdate < Date '1994-01-01' group by l_shipdate limit 10
```

translates to 

```
LogicalSort(fetch=[10])
  LogicalProject(EXPR$0=[$1], EXPR$1=[$2], EXPR$2=[$3], EXPR$3=[$4], EXPR$4=[$6])
    LogicalJoin(condition=[IS NOT DISTINCT FROM($0, $5)], joinType=[inner])
      LogicalProject(l_shipdate=[$0], EXPR$0=[$1], EXPR$1=[$2], EXPR$2=[$3], EXPR$3=[$5])
        LogicalJoin(condition=[IS NOT DISTINCT FROM($0, $4)], joinType=[inner])
          LogicalAggregate(group=[{0}], EXPR$0=[COUNT($1)], EXPR$1=[SUM($2)], EXPR$2=[SUM($3)])
            LogicalProject(l_shipdate=[$4], l_discount=[$2], l_tax=[$3], l_orderkey=[$0], l_suppkey=[$1])
              BindableTableScan(table=[[main, lineitem]], filters=[[<($4, 1994-01-01)]], projects=[[0, 2, 6, 7, 10]], aliases=[[l_orderkey, l_suppkey, l_discount, l_tax, l_shipdate]])
          LogicalAggregate(group=[{0}], EXPR$3=[COUNT($1)])
            LogicalAggregate(group=[{0, 1}])
              LogicalProject(l_shipdate=[$4], l_orderkey=[$0])
                BindableTableScan(table=[[main, lineitem]], filters=[[<($4, 1994-01-01)]], projects=[[0, 2, 6, 7, 10]], aliases=[[l_orderkey, l_suppkey, l_discount, l_tax, l_shipdate]])
      LogicalAggregate(group=[{0}], EXPR$4=[COUNT($1)])
        LogicalAggregate(group=[{0, 1}])
          LogicalProject(l_shipdate=[$4], l_suppkey=[$1])
            BindableTableScan(table=[[main, lineitem]], filters=[[<($4, 1994-01-01)]], projects=[[0, 2, 6, 7, 10]], aliases=[[l_orderkey, l_suppkey, l_discount, l_tax, l_shipdate]])
```

**Comment by jrhemstad** [comment]
This would be pretty straightforward to add. The `row_equality_comparator` used by Joins already exposes a `nulls_are_equal` parameter: https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/table/row_operators.cuh#L199

It would just be a matter of adding a `nulls_are_equal` parameter to the top-level join APIs and plumbing it down to the comparator ctor.

**Comment by harrism** [comment]
@felipe the simpler example you gave is a groupby (if I'm wrong, blame my limited knowledge of SQL):

```
select count(distinct(a)) from table_1 group by b
```

We have an open request to implement groupby.nunique -- would that satisfy the simpler query above?

**Comment by beckernick** [comment]
@felipeblazing is this still relevant?

**Comment by vyasr** [comment]
As far as I can tell this request was addressed a long time ago at the libcudf level: all join functions accept a `null_equality` parameter that is being used by Spark at this stage. The Python request is no longer relevant. We can reopen this request if a Python use case arises in the future.
