### ISSUE TITLE
Feature request, usecols parameter on read_csv

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cudf#402]
Feature request.

Please could we have a Pandas style usecols parameter to select only certain columns from a CSV file to go into the dataframe?

I have some large CSV files where I am only interested in a handful of columns. As a workaround, I'm using Pandas as an intermediary stage.

Thanks.

**Comment by harrism** [comment]
@BradReesWork can you evaluate?

**Comment by BradReesWork** [comment]
The CUDA portion of the request has been merged into the master branch.  The Python bindings are being worked now.  
From the C/CUDA side, the user specifies a list of column names or numbers that they would like returned.  All other columns are discarded - the code does not create a column or convert from string to data types.

**Comment by kkraus14** [comment]
Resolved by #478
