### ISSUE TITLE
[BUG] Cython warnings during cuDF build

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#4024]
**Describe the bug**

Am seeing some Cython warnings when building the code locally.

<details>

```
[ 1/34] Cythonizing cudf/_lib/arrow/_cuda.pyx
[ 2/34] Cythonizing cudf/_lib/avro.pyx
warning: cudf/_lib/avro.pyx:59:47: Use boundscheck(False) for faster access
[ 3/34] Cythonizing cudf/_lib/binops.pyx
[ 4/34] Cythonizing cudf/_lib/concat.pyx
[ 5/34] Cythonizing cudf/_lib/copying.pyx
[ 6/34] Cythonizing cudf/_lib/csv.pyx
warning: cudf/_lib/csv.pyx:96:53: Not all members given for struct 'reader_options'
warning: cudf/_lib/csv.pyx:96:53: Not all members given for struct 'reader_options'
warning: cudf/_lib/csv.pyx:273:65: Not all members given for struct 'csv_write_arg'
warning: cudf/_lib/csv.pyx:273:65: Not all members given for struct 'csv_write_arg'
warning: cudf/_lib/csv.pyx:209:46: Use boundscheck(False) for faster access
[ 7/34] Cythonizing cudf/_lib/cudf.pyx
[ 8/34] Cythonizing cudf/_lib/dlpack.pyx
[ 9/34] Cythonizing cudf/_lib/filling.pyx
[10/34] Cythonizing cudf/_lib/gpuarrow.pyx
[11/34] Cythonizing cudf/_lib/groupby.pyx
[12/34] Cythonizing cudf/_lib/hash.pyx
[13/34] Cythonizing cudf/_lib/issorted.pyx
[14/34] Cythonizing cudf/_lib/join.pyx
[15/34] Cythonizing cudf/_lib/json.pyx
warning: cudf/_lib/json.pyx:77:47: Use boundscheck(False) for faster access
[16/34] Cythonizing cudf/_lib/nvtx.pyx
[17/34] Cythonizing cudf/_lib/orc.pyx
warning: cudf/_lib/orc.pyx:86:46: Use boundscheck(False) for faster access
[18/34] Cythonizing cudf/_lib/parquet.pyx
warning: cudf/_lib/parquet.pyx:61:49: Use boundscheck(False) for faster access
[19/34] Cythonizing cudf/_lib/quantile.pyx
[20/34] Cythonizing cudf/_lib/reduce.pyx
[21/34] Cythonizing cudf/_lib/replace.pyx
[22/34] Cythonizing cudf/_lib/reshape.pyx
[23/34] Cythonizing cudf/_lib/rolling.pyx
[24/34] Cythonizing cudf/_lib/search.pyx
[25/34] Cythonizing cudf/_lib/sort.pyx
[26/34] Cythonizing cudf/_lib/stream_compaction.pyx
[27/34] Cythonizing cudf/_lib/table.pyx
/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/nfs/jkirkham/cudf/python/cudf/cudf/_lib/table.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[28/34] Cythonizing cudf/_lib/transpose.pyx
[29/34] Cythonizing cudf/_lib/typecast.pyx
warning: cudf/_lib/typecast.pyx:33:24: local variable 'c_category' referenced before assignment
[30/34] Cythonizing cudf/_lib/unaryops.pyx
[31/34] Cythonizing cudf/_lib/utils.pyx
[32/34] Cythonizing cudf/_libxx/column.pyx
/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/nfs/jkirkham/cudf/python/cudf/cudf/_libxx/column.pxd
  tree = Parsing.p_module(s, pxd, full_module_name)
[33/34] Cythonizing cudf/_libxx/copying.pyx
/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/nfs/jkirkham/cudf/python/cudf/cudf/_libxx/copying.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
[34/34] Cythonizing cudf/_libxx/table.pyx
/datasets/jkirkham/miniconda/envs/rapids13dev/lib/python3.7/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/nfs/jkirkham/cudf/python/cudf/cudf/_libxx/table.pxd
```

</details>

**Steps/Code to reproduce bug**

`python setup.py build_ext --inplace`

**Expected behavior**

No warnings.

**Environment overview (please complete the following information)**
 - Environment location: DGX-1
 - Method of cuDF install: Conda / source for cuDF
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit aeb3978f1f8016bd8017bcb382039ef08ea3a24a (HEAD -> add_buf_cai, jakirkham/add_buf_cai)
     Author: John Kirkham <jakirkham@gmail.com>
     Date:   Thu Jan 30 23:40:27 2020 -0800
     
     Note addition in changelog
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     bcd545071c7a5ddb28cb6576afc6399eb1286c43 thirdparty/jitify (remotes/origin/HEAD)
     cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx (0.8.1-99-gcdcda48)
     -a97a7380c76346c22bb67b93695bed19592afad2 thirdparty/libcudacxx/libcxx
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2019-04-24"
     DGX_SWBUILD_VERSION="4.1.0"
     DGX_COMMIT_ID="2c52306"
     DGX_PLATFORM="DGX Server for DGX-1"
     DGX_SERIAL_NUMBER="QTFCOU822000C"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
     NAME="Ubuntu"
     VERSION="18.04.2 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.2 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx15 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Jan 31 02:58:30 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   32C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   32C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   33C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   31C    P0    41W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   32C    P0    41W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   33C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   34C    P0    42W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   31C    P0    41W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             3410.732
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.12
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     /datasets/jkirkham/miniconda/envs/rapids13dev/bin/cmake
     cmake version 3.16.3
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /datasets/jkirkham/miniconda/envs/rapids13dev/bin/g++
     g++ (crosstool-NG 1.23.0.450-d54ae) 7.3.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /datasets/jkirkham/miniconda/envs/rapids13dev/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243
     
     ***Python***
     /datasets/jkirkham/miniconda/envs/rapids13dev/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /datasets/jkirkham/miniconda/envs/rapids13dev/bin:/datasets/jkirkham/miniconda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /datasets/jkirkham/miniconda/envs/rapids13dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /datasets/jkirkham/miniconda/condabin/conda
     # packages in environment at /datasets/jkirkham/miniconda/envs/rapids13dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       0_gnu    conda-forge
     aiohttp                   3.6.2            py37h516909a_0    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     attrs                     19.3.0                     py_0    conda-forge
     autoconf                  2.69            pl526h14c3975_9    conda-forge
     automake                  1.16.1               pl526_1003    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     binutils-meta             1.0.4                         0    conda-forge
     binutils_impl_linux-64    2.33.1               h53a641e_8    conda-forge
     binutils_linux-64         2.33.1              h9595d00_16    conda-forge
     blas                      2.14                   openblas    conda-forge
     bleach                    3.1.0                      py_0    conda-forge
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     c-compiler                1.0.4                h516909a_0    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     cairo                     1.16.0            hfb77d84_1002    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cfitsio                   3.470                hb60a0a2_2    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                        py_0    conda-forge
     cloudpickle               1.2.2                      py_1    conda-forge
     cmake                     3.16.3               h28c56e5_0    conda-forge
     compilers                 1.0.4                         0    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    defaults
     cudf                      0.13.0a200129          py37_685    rapidsai-nightly
     cudnn                     7.6.5                cuda10.1_0    defaults
     cugraph                   0.13.0a200128           py37_84    rapidsai-nightly
     cuml                      0.13.0a200128   cuda10.1_py37_84    rapidsai-nightly
     cupy                      7.1.1            py37h0c141eb_0    conda-forge
     curl                      7.65.3               hf8cf82a_0    conda-forge
     cuspatial                 0.13.0a200128            py37_2    rapidsai-nightly
     cxx-compiler              1.0.4                hc9558a2_0    conda-forge
     cython                    0.29.14          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.10.0                     py_0    conda-forge
     dask-core                 2.10.0                     py_0    conda-forge
     dask-cuda                 0.13.0a200128            py37_2    rapidsai-nightly
     dask-cudf                 0.13.0a200129          py37_685    rapidsai-nightly
     dask-xgboost              0.2.0.dev28      cuda10.1py37_0    rapidsai-nightly
     dbus                      1.13.6               he372182_0    conda-forge
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.10.0                     py_0    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.9                he1b5a44_1    conda-forge
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     fortran-compiler          1.0.4                he991be0_0    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     freexl                    1.0.5             h14c3975_1002    conda-forge
     fribidi                   1.0.5             h516909a_1002    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     gcc_impl_linux-64         7.3.0                hd420e75_4    conda-forge
     gcc_linux-64              7.3.0               h553295d_16    conda-forge
     gdal                      2.4.4            py37h5f563d9_0    conda-forge
     geos                      3.8.0                he1b5a44_0    conda-forge
     geotiff                   1.5.1                h38872f0_8    conda-forge
     gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     gfortran_impl_linux-64    7.3.0                hdf63c60_4    conda-forge
     gfortran_linux-64         7.3.0               h553295d_16    conda-forge
     giflib                    5.1.7                h516909a_1    conda-forge
     glib                      2.58.3          py37h6f030ca_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     graphite2                 1.3.13            hf484d3e_1000    conda-forge
     graphviz                  2.42.3               h0511662_0    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     gst-plugins-base          1.14.5               h0935bb2_1    conda-forge
     gstreamer                 1.14.5               h36ae1b5_1    conda-forge
     gxx_impl_linux-64         7.3.0                hdf63c60_4    conda-forge
     gxx_linux-64              7.3.0               h553295d_16    conda-forge
     harfbuzz                  2.4.0                h9f30f68_3    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.8                   py37_1000    conda-forge
     importlib_metadata        1.4.0                    py37_0    conda-forge
     inflect                   4.0.0                    py37_1    conda-forge
     ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
     ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1                      py_0    conda-forge
     jaraco.itertools          5.0.0                      py_0    conda-forge
     jedi                      0.16.0                   py37_0    conda-forge
     jinja2                    2.11.0                     py_0    conda-forge
     joblib                    0.14.1                     py_0    conda-forge
     jpeg                      9c                h14c3975_1001    conda-forge
     json-c                    0.13.1            h14c3975_1001    conda-forge
     json5                     0.8.5                      py_0    conda-forge
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter                   1.0.0                      py_2    conda-forge
     jupyter-server-proxy      1.2.0                      py_0    conda-forge
     jupyter_client            5.3.4                    py37_1    conda-forge
     jupyter_console           6.0.0                      py_0    conda-forge
     jupyter_core              4.6.1                    py37_0    conda-forge
     jupyterlab                1.2.6                      py_0    conda-forge
     jupyterlab-nvdashboard    0.1.11200116              py_12    rapidsai-nightly
     jupyterlab_server         1.0.6                      py_0    conda-forge
     kealib                    1.4.10            h58c409b_1005    conda-forge
     krb5                      1.16.4               h2fd8d38_0    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libclang                  9.0.1           default_hde54327_0    conda-forge
     libcudf                   0.13.0a200129      cuda10.1_685    rapidsai-nightly
     libcugraph                0.13.0a200128       cuda10.1_84    rapidsai-nightly
     libcuml                   0.13.0a200128       cuda10.1_84    rapidsai-nightly
     libcumlprims              0.13.0a200128        cuda10.1_0    rapidsai-nightly
     libcurl                   7.65.3               hda55be3_0    conda-forge
     libcuspatial              0.13.0a200128        cuda10.1_2    rapidsai-nightly
     libdap4                   3.20.4               hd3bb157_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
     libgdal                   2.4.4                h2b6fda6_0    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_4    conda-forge
     libgomp                   9.2.0                h24d8f2e_2    conda-forge
     libhwloc                  2.1.0                h3c4fd83_0    conda-forge
     libiconv                  1.15              h516909a_1005    conda-forge
     libkml                    1.3.0             h4fcabce_1010    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     liblapacke                3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libllvm9                  9.0.1                hc9558a2_0    conda-forge
     libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
     libnvstrings              0.13.0a200129      cuda10.1_685    rapidsai-nightly
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libpq                     12.1                 hd9ab2ff_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     libsodium                 1.0.17               h516909a_0    conda-forge
     libspatialite             4.3.0a            ha48a99a_1034    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libtool                   2.4.6             h14c3975_1002    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.34.0               h516909a_0    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxgboost                1.0.0dev.rapidsai0.12      cuda10.1_1    rapidsai-nightly
     libxkbcommon              0.9.1                hebb1f50_0    conda-forge
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.30.0           py37h8b12597_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     m4                        1.4.18            h14c3975_1001    conda-forge
     make                      4.2.1             h14c3975_2004    conda-forge
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     more-itertools            8.1.0                      py_0    conda-forge
     msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
     multidict                 4.7.4            py37h516909a_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  5.0.4                      py_0    conda-forge
     nccl                      2.4.8.1              h51cf6c1_1    conda-forge
     ncurses                   6.1               hf484d3e_1002    conda-forge
     nodejs                    13.7.0               h10a4023_0    conda-forge
     notebook                  6.0.3                    py37_0    conda-forge
     nspr                      4.24                 he1b5a44_0    conda-forge
     nss                       3.47                 he751ad9_0    conda-forge
     numba                     0.46.0           py37hb3f55d8_1    conda-forge
     numpy                     1.17.5           py37h95a1406_0    conda-forge
     nvcc_linux-64             10.1                 h51cf6c1_6    conda-forge
     nvstrings                 0.13.0a200129          py37_685    rapidsai-nightly
     olefile                   0.46                       py_0    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1d               h516909a_0    conda-forge
     packaging                 20.1                       py_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     pandoc                    2.9.1.1                       0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     pango                     1.42.4               ha030887_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.6.0                      py_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pcre                      8.43                 he1b5a44_0    conda-forge
     perl                      5.26.2            h516909a_1006    conda-forge
     pexpect                   4.8.0                    py37_0    conda-forge
     pickle5                   0.0.9            py37h516909a_0    conda-forge
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    7.0.0            py37hefe7db6_0    conda-forge
     pip                       20.0.2                   py37_0    conda-forge
     pixman                    0.38.0            h516909a_1003    conda-forge
     pkg-config                0.29.2            h516909a_1006    conda-forge
     pluggy                    0.13.0                   py37_0    conda-forge
     poppler                   0.67.0               h14e79db_8    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                12.1                 hc63931a_0    conda-forge
     proj                      6.3.0                hc80f0dc_0    conda-forge
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            2.0.10                     py_0    conda-forge
     psutil                    5.6.7            py37h516909a_0    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.1                      py_0    conda-forge
     py-xgboost                1.0.0dev.rapidsai0.12  cuda10.1py37_1    rapidsai-nightly
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pynvml                    8.0.4                      py_0    conda-forge
     pyparsing                 2.4.6                      py_0    conda-forge
     pyqt                      5.12.3           py37hcca6a23_1    conda-forge
     pyqt5-sip                 4.19.18                  pypi_0    pypi
     pyqtwebengine             5.12.1                   pypi_0    pypi
     pyrsistent                0.15.7           py37h516909a_0    conda-forge
     pytest                    5.3.4                    py37_0    conda-forge
     pytest-asyncio            0.10.0                py37_1000    conda-forge
     python                    3.7.6                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python-graphviz           0.13.2                     py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.3              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     qt                        5.12.5               hd8c4c69_1    conda-forge
     qtconsole                 4.6.0                      py_0    conda-forge
     rapids                    0.13.0          cuda10.1_py37_0    rapidsai-nightly
     rapids-xgboost            0.13.0          cuda10.1_py37_0    rapidsai-nightly
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rhash                     1.3.6             h14c3975_1001    conda-forge
     scikit-learn              0.22.1           py37hcdab131_1    conda-forge
     scipy                     1.4.1            py37h921218d_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                45.1.0                   py37_0    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     six                       1.14.0                   py37_0    conda-forge
     snappy                    1.1.7             he1b5a44_1003    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     tornado                   6.0.3            py37h516909a_0    conda-forge
     traitlets                 4.3.3                    py37_0    conda-forge
     tzcode                    2019a             h516909a_1002    conda-forge
     ucx                       1.7.0dev+g9d06c3a    cuda10.1_129    rapidsai-nightly
     ucx-py                    0.13.0a200123+g896e60b         py37_12    rapidsai-nightly
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     valgrind                  3.15.0               he513fc3_0    conda-forge
     wcwidth                   0.1.8                      py_0    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.34.1                   py37_0    conda-forge
     widgetsnbextension        3.5.1                    py37_0    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.0.0dev.rapidsai0.12  cuda10.1py37_1    rapidsai-nightly
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.9                h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxpm               3.5.13               h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-libxt                1.1.5             h516909a_1003    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.3.0           py37h516909a_1000    conda-forge
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                      py_0    conda-forge
     zipp                      2.1.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Additional context**

NA

**Comment by kkraus14** [comment]
Fixed by #4223

**Comment by jakirkham** [comment]
Thanks Keith! 😄

I think there are still a few of these lingering like `boundscheck` warnings and missing declarations. Otherwise it does appear the `language_level` warnings should be fixed. Do we want to track these remaining warnings in a new issue or is here ok? 🙂

**Comment by jakirkham** [comment]
Reopening for now to track those remaining warnings. Though happy to move to a new issue if that's preferred 🙂

**Comment by jakirkham** [comment]
Looks like we are down to just these...

```cython
warning: cudf/_lib/csv.pyx:93:53: Not all members given for struct 'reader_options'
warning: cudf/_lib/csv.pyx:93:53: Not all members given for struct 'reader_options'
warning: cudf/_lib/csv.pyx:270:65: Not all members given for struct 'csv_write_arg'
warning: cudf/_lib/csv.pyx:270:65: Not all members given for struct 'csv_write_arg'
```

**Comment by kkraus14** [comment]
> Looks like we are down to just these...
> 
> ```cython
> warning: cudf/_lib/csv.pyx:93:53: Not all members given for struct 'reader_options'
> warning: cudf/_lib/csv.pyx:93:53: Not all members given for struct 'reader_options'
> warning: cudf/_lib/csv.pyx:270:65: Not all members given for struct 'csv_write_arg'
> warning: cudf/_lib/csv.pyx:270:65: Not all members given for struct 'csv_write_arg'
> ```

Those will all go away when we rip out the legacy code 😄

**Comment by jakirkham** [comment]
Figured as much 😉

**Comment by kkraus14** [comment]
No more warnings as of removal from legacy, closing this out! 🎉
