### ISSUE TITLE
[BUG] np.where not supported? 

### ISSUE THREAD

**Issue by RedTailedHawk** [rapidsai/cudf#4032]
This works with normal Pandas, but I get an error with cudf.  Is there another way to do it?

![image](https://user-images.githubusercontent.com/8505928/73571252-28b68c00-443c-11ea-9a54-5ff109fa0f69.png)

**Comment by RedTailedHawk** [comment]
Looks like it works with cupy.

![image](https://user-images.githubusercontent.com/8505928/73681930-4cbcdc00-468d-11ea-9d29-7684955317d8.png)

**Comment by jrhemstad** [comment]
It looks like in your original example you were using strings, whereas the cupy example does not. I believe the cuDF `where` functionality relies on a Numba JITed kernel which currently doesn't support strings.

**Comment by RedTailedHawk** [comment]
OK thanks.  Numbers are the main thing I need for this, so that should be fine.  But it looks like None is not supported here, which I kind of need.

```
data = {"age": [20, 21, 19, 18]}
df = cudf.DataFrame(data)
df["x"] = cupy.where(df["age"] == 21, 1, None)
display(df)
```

`ValueError: Must provide both 'x' and 'y' or neither.`

It works for normal Pandas.
```
data = {"age": [20, 21, 19, 18]}
df = pd.DataFrame(data)
df["x"] = np.where(df["age"] == 21, 1, None)
display(df)
```

![image](https://user-images.githubusercontent.com/8505928/73686720-8a723280-4696-11ea-9fcd-51c7db393495.png)

Any idea if this will be supported in the future?  Is this a cudf feature, or should I post on the cupy board?

**Comment by beckernick** [comment]
CuPy doesn't understand the `None`, so it's throwing a ValueError. You may want to raise a request on the CuPy issue tracker for this.

If you don't need to make the distinction between `None` and `NaN`, you could do `df["x"] = np.where(df["age"] == 21, 1, np.nan)`.

To coerce these NaNs to nulls, you could do:
```
df['x'] = cp.where(arr == 21, 1, np.nan)
df['x'] = df.x.nans_to_nulls()

**Comment by RedTailedHawk** [comment]
OK, that's a decent workaround, but is there a way to convert NaN to None instead of null?

**Comment by beckernick** [comment]
Pandas is allowing you to replace a Python `None` into your column, which changes your data type from integer to object.

cuDF doesn't support the Python None, but does support both `NaN` and `null`, which should hopefully give you the null handling support you need. If it doesn't, it would be great to learn about more about your downstream operations before continuing the discussion.

**Comment by RedTailedHawk** [comment]
I think that gives me enough to go on.

Thanks all for your help!!
