### ISSUE TITLE
Dockerfile Error 

### ISSUE THREAD

**Issue by a-agrz** [rapidsai/cudf#404]
## Reporting a bug

There is a mistake in Dockerfile line 55 and 56 :
  mkdir -p /cudf/libgdf/build && \
cd /cudf/libgdf/build && \
As described in README.md you should put 
 mkdir -p /cudf/cpp/build && \
cd /cudf/cpp/build && \

Best regards

**Comment by a-agrz** [comment]
After correcting all this errors I was able to build and run the cuDF docker image, but I found myself face to another problem while importing cudf library that I couldn't resolve : 
root@1640567a24f8:/# source activate cudf
(cudf) root@1640567a24f8:/# python -c "import cudf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.3.0+3.gccc6883-py3.6-linux-x86_64.egg/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe             # noqa: F401
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.3.0+3.gccc6883-py3.6-linux-x86_64.egg/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,  # noqa: F401
  File "/conda/envs/cudf/lib/python3.6/site-packages/cudf-0.3.0+3.gccc6883-py3.6-linux-x86_64.egg/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
ImportError: cannot import name 'librmm'
Best regards
aguerzaa

**Comment by DC-Shi** [comment]
Additional notes:
I followed the instruction above to add cython & change wrong folder name, encountered cannot import librmm problem.

I searched for others that dependent on librmm_cffi, and found the function used are in this file: [cpp/python/librmm_cffi/wrapper.py](https://github.com/rapidsai/cudf/blob/master/cpp/python/librmm_cffi/wrapper.py)


But this wrapper only contains `_RMMWrapper`, this should be `librmm` I think.

**Comment by kkraus14** [comment]
This was resolved by #408. Please open a new issue if you're still encountering issues in using the Dockerfile.
