### ISSUE TITLE
[BUG] split should always return N + 1 vectors where N is the split indexes

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#4056]
**Describe the bug**
The split function should always return N + 1 vectors where N is the split indexes. The function will return N tables, instead of N + 1 tables, if the last index sent to it is of the same size as number of rows in the input table. If the last index sent is of the same size as the number of rows in the input table, the last table should be empty, but instead its simply omitted. This behavior is confusing since the function does not exclude any empty table that could be generated by it, only if its the last table. It is apparent in the code where this happens. In split.cpp is the following:
```
template<typename T>
    std::vector<T> split(T const& input, size_type column_size, std::vector<size_type> const& splits) {
        std::vector<T> result{};

        if(splits.size() == 0 or column_size == 0) {
            return result;
        }
        CUDF_EXPECTS(splits.back() <= column_size, "splits can't exceed size of input columns");

        // If the size is not zero, the split will always start at `0`
        std::vector<size_type> indices{0};
        std::for_each(splits.begin(), splits.end(), 
                [&indices](auto split) {
                    indices.push_back(split); // This for end
                    indices.push_back(split); // This for the start
                });
        
        if (splits.back() != column_size) {
            indices.push_back(column_size); // This to include rest of the elements
        } else {
            indices.pop_back(); // Not required as it is extra  ----->  WHY IS THIS HERE??
        }

        return cudf::experimental::slice(input, indices);
    }   
```

**Steps/Code to reproduce bug**
Code like this should reproduce the bug:
```
fixed_width_column_wrapper<T> col1{{5, 4, 3, 5, 8, 5, 6}};
fixed_width_column_wrapper<T> col2{{15, 14, 13, 15, 18, 15, 16}};
table_view table_view_in {{col1, col2}};

std::vector<size_type> split_indexes{3, 3, 5, 7};

std::vector<table> partitioned = split(table_view_in, split_indexes);

EXPECT_EQ(partitioned.size(), 5);
EXPECT_EQ(partitioned[1]->num_rows(), 0);
EXPECT_EQ(partitioned[4]->num_rows(), 0);
```

**Expected behavior**
split should always return N + 1 vectors where N is the split indexes

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by harrism** [comment]
Appears to duplicate #4027
