### ISSUE TITLE
Utility function should be created for category synchronization

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#409]
Given the need to synchronize categories for any function that takes in multiple `category` dtype series, we should create a single function that takes in a collection of `category` series and/or `category` columns and returns a collection of the objects with the categories set to the superset, and the data recoded based on the new category set.

**Comment by trxcllnt** [comment]
Like this? https://github.com/rapidsai/cudf/blob/dc3fef60eb83f19d5a31597a290df224234091c7/python/cudf/cudf/dataframe/column.py#L83-L87

**Comment by trxcllnt** [comment]
@kkraus14 what are some examples of methods that take in multiple series and need to combine the categories? I'd be happy to normalize the logic for all those methods into a utility function and submit a PR!

**Comment by kkraus14** [comment]
Superseded by libcudf implementation of categorical column.
