### ISSUE TITLE
[BUG] Groupby+reset_index with dask_cudf upcasts the key column dtype

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#4090]
**Describe the bug**
Calling dask_cudf groupby agg + reset index in the .agg{'col':[agg]} form upcasts the key column dtype to `float64`

**Steps/Code to reproduce bug**
```
import cudf
import dask_cudf
import numpy as np

df = cudf.DataFrame()
df["a"] = np.arange(10, dtype="int8")
df["b"] = np.arange(10, dtype="int8")
df = dask_cudf.from_cudf(df,1)

a = df.groupby("a").agg({'b':["count"]})
print("Index dtype before reset_index(key col a):", a.index.dtype)
print("Dtype of columns after reset_index:\n", a.reset_index().dtypes)
```

```
Index dtype before reset_index(key col a): int8
Dtype of columns after reset_index:
 0    float64
1    float64
```
**Expected behavior**
Dtype for the key column should be retained

**Environment overview (please complete the following information)**
 - 0.12 release docker

**Additional context** 
Workaround is to cast back after groupby operation

**Comment by kkraus14** [comment]
@ayushdg calling `reset_index` resets the index to a `RangeIndex` which is an unmaterialized `int64` dtype.  If you want that as a smaller type you should be able to typecast it without issue.

**Comment by ayushdg** [comment]
Apologizes for not including the output earlier. The issue isn't the new index becoming `int64` but the original dtype for key column: `a` becoming a `float64`. Also this behavior only occurs when calling the aggregate in the dict+(list of values) form.

**Comment by kkraus14** [comment]
Looks like it's specifically something in how Dask does `reset_index()`. Any insights here @rjzamora?

**Comment by kkraus14** [comment]
Hmm, something in the `_meta_nonempty` calculation is causing an upcast to `int64` but I'm still not clear how it's getting to `float64`.

**Comment by rjzamora** [comment]
> Hmm, something in the _meta_nonempty calculation is causing an upcast to int64 but I'm still not clear how it's getting to float64.

Yeah - Looks like soemthing goes wrong during the cudf-pandas roundtrip within our meta_nonempty dispatch definition.  I can check it out.

**Comment by rjzamora** [comment]
Some notes on the behavior I have discovered (so far):

```python
import cudf as df_backend
import numpy as np

df = df_backend.DataFrame()
df["a"] = np.arange(10, dtype="int8")
df["b"] = np.arange(10, dtype="int8")
a = df.groupby("a").agg({'b':["count"]})
```

**`a.index`** ->
```
GenericIndex([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int8, name='a')
```

**`a.dtypes`** -> 
```
0    int32
dtype: object
```

**`a.iloc[:0].dtypes`** -> 
```
0    int32
dtype: object
```

**`a.iloc[:0].iloc[:0].dtypes`**  [Cause of the `float64` type - This is effectively what dask_cudf does when creating `self._meta`] -> 
```
0    float64
dtype: object
```

**`a.index.to_pandas()`** [Initial type conversion of index - Created when dask_cudf lets dask use pandas to prepare "nonempty" metadata] -> 
```
0    int32
dtype: object
```

**Note-1**:  Much of the above behavior is specific to dataframes where `self.columns` is a   `MultiIndex`.

**Note-2**: Pandas also has strange (but different) behavior for the above example. More specifically, the index becomes `int64` after the groupby aggregation (no follow-up operations like iloc are needed to "mess things up").
