### ISSUE TITLE
[FEA] Implement python API for libcudf++ n-way merge

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#4094]
Now that #4040 is merged, we can add a python API to "merge" a list of sorted tables into a larger sorted table.  Note that this functionality is not really really covered by the current pandas API (please correct me if I am wrong).

**Comment by rjzamora** [comment]
@kkraus14 - Happy to work on this today, but understand if you want to get a cython expert to knock it out :)

**Comment by kkraus14** [comment]
> @kkraus14 - Happy to work on this today, but understand if you want to get a cython expert to knock it out :)

It should be pretty straight forward where if you've got the cycles it would be great if you could tackle it. I'll be more than happy to lend you eyes where you need them 😄.
