### ISSUE TITLE
[BUG] hash_partition can produce nulls when input has no nulls

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#4103]
**Describe the bug**
Calling `hash_partition` will sometimes produce a table with columns that can contain null values despite the input having no null values.  Typically an entire column becomes null values.

**Steps/Code to reproduce bug**
Partition a table into less than 512 partitions, triggering the optimized code path, and use string columns that have validity masks but no nulls set in those masks.

**Expected behavior**
Null values should not be created by a table partition operation.

**Comment by jlowe** [comment]
cc: @trevorsm7

**Comment by jlowe** [comment]
I believe the problem occurs because of a disconnect between the expectations of `hash_partition` when it gathers a string known to contain no nulls and what `string::detail::gather` does. Gathering a string does not handle the null mask.  It will allocate a null mask if the input is `nullable()` but it will leave the null count as UNKNOWN_NULL_COUNT.  The `hash_partition` code is checking if the table has any nulls to decide if it should handle null masks, so that leads to the disconnect.  The caller doesn't think nulls have to be handled, but the callee returned an uninitialized null mask expecting the caller to fill it in.

I don't know the story behind why gathering a string will gather the data but not the null mask.  One way to fix it would be to have `string::detail::gather` check for `has_nulls` rather than `nullable`.

**Comment by harrism** [comment]
@jlowe you don't happen to have C++ code that repros, do you?

**Comment by jlowe** [comment]
> you don't happen to have C++ code that repros, do you?

Unfortunately no.  I have debugged it to the point where I'm confident in my analysis above.  If I disable the optimized code path in `hash_partition` then it produces correct results.  Setting up a hash partition of a string column that has a validity mask but all entries are valid should trigger the issue.  The string gather code will see the input is nullable and allocate an uninitialized validity mask expecting the caller to initialize it, but the hash partition optimized code path will see there are no nulls and skip handling any null masks.

**Comment by trevorsm7** [comment]
I filed a separate issue https://github.com/rapidsai/cudf/issues/4120 for the surprising behavior of `column_gatherer` allocating null masks but returning them uninitialized. We can resolve the `hash_partition` issue either by fixing `column_gatherer` or by adding a simple workaround in `hash_partition`. In the meantime, I'm working on adding a unit test to repro this bug.
