### ISSUE TITLE
[FEA] `Buffer` constructor checks for array interface objects

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#4104]
**Is your feature request related to a problem? Please describe.**

When constructing a `Buffer` from an object supporting either `__array_interface__` or `__cuda_array_interface__`, it would be good to check that it meets certain requirements (like being contiguous). Additionally it may make sense to require that the data provided is 1-D and/or of `uint8` type as neither shape nor type are preserved by `Buffer`s.

**Describe the solution you'd like**

As `Buffer` has an internal method, [`_init_from_array_like`]( https://github.com/rapidsai/cudf/blob/8bd6c817c71d0e6824a4a1aa84e105e643bb7c2f/python/cudf/cudf/core/buffer.py#L68 ), for creating a `Buffer` from something supporting either `__array_interface__` or `__cuda_array_interface__`, this seems like a natural place for these checks. Can simply error if one of the requirements is not met.

**Describe alternatives you've considered**

There might be other reasonable places for these checks like the constructor. Perhaps only some of these checks are needed.

**Additional context**

As other objects that use the `Buffer` assume these requirements are met, it would make sense to ensure they are met when creating the `Buffer`.

**Comment by brandon-b-miller** [comment]
@jakirkham a clarifying question, why would we need to require `uint8`? Unless I am misunderstanding something, we regularly construct buffers from data that isn't `uint8`. 

```
>>> data = cupy.arange(10)
>>> buf = Buffer(data, size=data.size)
>>> cudf.Series(NumericalColumn(buf, dtype=data.dtype))
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
```

**Comment by jakirkham** [comment]
Well really `Buffer`s are in some sense untyped blobs of data. Typically that is typed as `uint8` in Python. So this would be consistent with that. Of course people can interpret this blob of data as having an externally supplied type.

```python
In [1]: import numpy as np                                                      

In [2]: b = b"abcd"                                                             

In [3]: np.asarray(memoryview(b))                                               
Out[3]: array([ 97,  98,  99, 100], dtype=uint8)

In [4]: np.asarray(memoryview(b)).view("i2")                                    
Out[4]: array([25185, 25699], dtype=int16)
```

**Comment by brandon-b-miller** [comment]
That makes sense - at the buffer level it's just a blob of bytes and it's up to some higher level object to view it was something else. So is there any reason to specifically disallow any incoming blob based on a datatype that may or may not be attached to the owner of that blob?

**Comment by jakirkham** [comment]
I suppose it could be allowed. However we are not preserving that type information. So we should somehow indicate that to the user and possibly suggest they use something else (like making a `Series`?).

**Comment by brandon-b-miller** [comment]
Now that I think about it, it might actually make sense to disable it. My original concern was that we'd break the codepath that was used to construct columns from cupy or numba arrays that have numpy types. In those cases I think the column constructors perform some arithmetic with the datatype to build a buffer that has the right size, etc, but still passes the original data to the buffer as `owner`. I was thinking we'd then hit an error there if we required the incoming data to be `uint8`, but I suppose we could just convert to a `uint8` view at the last moment.
