### ISSUE TITLE
[BUG] RMM initialization error when read csv using libcudf

### ISSUE THREAD

**Issue by xiaonans** [rapidsai/cudf#4106]
**Describe the bug**
I use cpp APIs in libcudf to read csv files. I can succeed in compiling the .cu file. But when I run the executable file, error occured as 

> terminate called after throwing an instance of 'thrust::system::system_error'

>   what():  rmm_allocator::allocate(): RMM_ALLOC: initialization error

> Aborted` (core dumped)" 

**Steps/Code to reproduce bug**
**My codes in the test.cu:**
#include "cudf/io/functions.hpp"
#include <cudf/table/table.hpp>
#include <cudf/table/table_view.hpp>
#include "fstream"

namespace cudf_io = cudf::experimental::io;
int main(){
 auto filepath = "Booleans.csv";
  {
    std::ofstream outfile(filepath, std::ofstream::out);
    outfile << "YES,1,bar,true\nno,2,FOO,true\nBar,3,yes,false\nNo,4,NO,"
               "true\nYes,5,foo,false\n";
  }
  cudf_io::read_csv_args in_args{cudf_io::source_info{filepath}};
  in_args.names = {"A", "B", "C", "D"};
  in_args.dtype = {"int32", "int32", "short", "bool"};
  in_args.true_values = {"yes", "Yes", "YES", "foo", "FOO"};
  in_args.false_values = {"no", "No", "NO", "Bar", "bar"};
  in_args.header = -1;
  auto result = cudf_io::read_csv(in_args);
  return 0;
}
**How I compile the above test.cu:**
nvcc -g -std=c++14 -arch=sm_75 -I/home/xiaonans/anaconda3/envs/rapids-stable/include -L/home/xiaonans/anaconda3/envs/rapids-stable/lib -lcudf -lrmm -o test test.cu

**Expected behavior**
It is expected to run the compiled test without error.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
print_env.sh: 10: [: true: unexpected operator
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
     NAME="Ubuntu"
     VERSION="18.04.1 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.1 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux xiaonans-System-Product-Name 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Mon Feb 10 12:17:19 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 6000     Off  | 00000000:01:00.0 Off |                  Off |
     | 35%   36C    P8    28W / 260W |    652MiB / 24190MiB |      2%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro RTX 6000     Off  | 00000000:02:00.0 Off |                  Off |
     | 33%   30C    P8    14W / 260W |      0MiB / 24190MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      3413      G   /usr/lib/xorg/Xorg                           274MiB |
     |    0      3605      G   /usr/bin/gnome-shell                         227MiB |
     |    0      4080      G   ...-token=DD056A7BBC15DD5C0D3BEC7E1309A0FD    68MiB |
     |    0      5757      G   ...uest-channel-token=11927131796726150364    79MiB |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               158
     Model name:          Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
     Stepping:            10
     CPU MHz:             4703.219
     CPU max MHz:         4700.0000
     CPU min MHz:         800.0000
     BogoMIPS:            7392.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            12288K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp md_clear flush_l1d

     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.16.2

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda-10.0/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130

     ***Python***
     /home/xiaonans/anaconda3/envs/rapids-stable/bin/python
     Python 3.7.6

     ***Environment Variables***
     PATH                            : /home/xiaonans/anaconda3/envs/rapids-stable/bin:/home/xiaonans/anaconda3/condabin:/home/xiaonans/softwares/apache-maven-3.0.5/bin:/usr/local/cuda-10.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/xiaonans/softwares
     LD_LIBRARY_PATH                 : /home/xiaonans/anaconda3/envs/rapids-stable/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/xiaonans/anaconda3/envs/rapids-stable
     PYTHON_PATH                     :

     ***conda packages***
     conda is /home/xiaonans/anaconda3/condabin/conda
     /home/xiaonans/anaconda3/condabin/conda
     # packages in environment at /home/xiaonans/anaconda3/envs/rapids-stable:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       0_gnu    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2019.11.28           hecc5488_0    conda-forge
     certifi                   2019.11.28               py37_0    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.12.0                   py37_0    rapidsai
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cupy                      7.1.1            py37he57b8b9_1    conda-forge
     dlpack                    0.2                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcudf                   0.12.0               cuda10.0_0    rapidsai
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
     libgomp                   9.2.0                h24d8f2e_2    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnvstrings              0.12.0               cuda10.0_0    rapidsai
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.12.0               cuda10.0_0    rapidsai
     libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
     llvmlite                  0.31.0           py37h8b12597_0    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     numba                     0.48.0           py37hb3f55d8_0    conda-forge
     numpy                     1.18.1           py37h95a1406_0    conda-forge
     nvstrings                 0.12.0                   py37_0    rapidsai
     openssl                   1.1.1d               h516909a_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       20.0.2                     py_2    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     python                    3.7.6                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     pytz                      2019.3                     py_0    conda-forge
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     rmm                       0.12.0                   py37_0    rapidsai
     setuptools                45.1.0                   py37_0    conda-forge
     six                       1.14.0                   py37_0    conda-forge
     snappy                    1.1.8                he1b5a44_1    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     wheel                     0.34.2                     py_1    conda-forge
     xz                        5.2.4             h14c3975_1001    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge

</pre></details>

**Comment by harrism** [comment]
You need to initialize RMM. 

```
    rmmOptions_t options{PoolAllocation, 0, false};
    rmmInitialize(&options); 
```

If you do not wish to use Pool Allocation, replace `PoolAllocation` with `CudaDefaultAllocation`.

**Comment by harrism** [comment]
Agree we need some standalone libcudf usage examples, but that's not going to happen soon.

**Comment by xiaonans** [comment]
That solves this issue.
