### ISSUE TITLE
[BUG] contiguous_split can corrupt string columns

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#4114]
**Describe the bug**
`contiguous_split` can produce garbage data for string columns in the resulting table views after splitting.

**Steps/Code to reproduce bug**
I have a sample Parquet file based on the mortgage dataset containing 32 columns and 10,000 rows.  The last column is a string indicating the quarter, e.g.: `2007Q3`, and all values in that column are the same value.  After loading the Parquet file and calling `contiguous_split(t, { 4985 })` the values for the last column in the two table views contain strings with garbage data.

**Expected behavior**
Each row should contain data that can be tracked back to a row in the original table being split.

**Comment by jlowe** [comment]
cc: @nvdbaranec

**Comment by nvdbaranec** [comment]
Fix incoming.  It's an issue related to tables of mixed string/non-string columns.  Verified with Jason's test.
