### ISSUE TITLE
[BUG] unknown type in template argument, when building cudf python bindings on ARM

### ISSUE THREAD

**Issue by heavyinfo** [rapidsai/cudf#4121]
After a long struggle I have managed to install successfully libcudf, nvstrings and dependencies such as dlpack, rmm on Jetson Nano (ARM - AArch64).

I had completely functional libarrow and Pyarrow already in my machine - [Pyarrow on ARM](https://gist.github.com/heavyinfo/04e1326bb9bed9cecb19c2d603c8d521).

But, I've reached a dead end when building cudf python bindings due to a error wehn compiling cython arrow files.

**Describe the bug**
```
sudo -E python3 setup.py build_ext --inplace

Compiling cudf/_lib/arrow/_cuda.pyx because it changed.
Compiling cudf/_lib/avro.pyx because it changed.
Compiling cudf/_lib/binops.pyx because it changed.
Compiling cudf/_lib/concat.pyx because it changed.
Compiling cudf/_lib/copying.pyx because it changed.
Compiling cudf/_lib/csv.pyx because it changed.
Compiling cudf/_lib/cudf.pyx because it changed.
Compiling cudf/_lib/dlpack.pyx because it changed.
Compiling cudf/_lib/filling.pyx because it changed.
Compiling cudf/_lib/gpuarrow.pyx because it changed.
Compiling cudf/_lib/groupby.pyx because it changed.
Compiling cudf/_lib/hash.pyx because it changed.
Compiling cudf/_lib/issorted.pyx because it changed.
Compiling cudf/_lib/join.pyx because it changed.
Compiling cudf/_lib/json.pyx because it changed.
Compiling cudf/_lib/nvtx.pyx because it changed.
Compiling cudf/_lib/orc.pyx because it changed.
Compiling cudf/_lib/parquet.pyx because it changed.
Compiling cudf/_lib/quantile.pyx because it changed.
Compiling cudf/_lib/reduce.pyx because it changed.
Compiling cudf/_lib/replace.pyx because it changed.
Compiling cudf/_lib/reshape.pyx because it changed.
Compiling cudf/_lib/rolling.pyx because it changed.
Compiling cudf/_lib/search.pyx because it changed.
Compiling cudf/_lib/sort.pyx because it changed.
Compiling cudf/_lib/stream_compaction.pyx because it changed.
Compiling cudf/_lib/table.pyx because it changed.
Compiling cudf/_lib/transpose.pyx because it changed.
Compiling cudf/_lib/typecast.pyx because it changed.
Compiling cudf/_lib/unaryops.pyx because it changed.
Compiling cudf/_lib/utils.pyx because it changed.
Compiling cudf/_libxx/column.pyx because it changed.
Compiling cudf/_libxx/copying.pyx because it changed.
Compiling cudf/_libxx/stream_compaction.pyx because it changed.
Compiling cudf/_libxx/table.pyx because it changed.
[ 1/35] Cythonizing cudf/_lib/arrow/_cuda.pyx

Error compiling Cython file:
------------------------------------------------------------
...
    """
    def __cinit__(self, CudaBuffer obj):
        self.buffer = obj
        self.reader = new CCudaBufferReader(self.buffer.buffer)
        self.set_random_access_file(
            shared_ptr[RandomAccessFile](self.reader))
                      ^
------------------------------------------------------------

cudf/_lib/arrow/_cuda.pyx:740:23: unknown type in template argument

Error compiling Cython file:
------------------------------------------------------------
...
    buffering.
    """
    def __cinit__(self, CudaBuffer buffer):
        self.buffer = buffer
        self.writer = new CCudaBufferWriter(self.buffer.cuda_buffer)
        self.set_output_stream(shared_ptr[OutputStream](self.writer))
                                         ^
------------------------------------------------------------

cudf/_lib/arrow/_cuda.pyx:787:42: unknown type in template argument
Traceback (most recent call last):
  File "setup.py", line 76, in <module>
    ext_modules=cythonize(extensions),
  File "/home/abishek/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/home/abishek/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cudf/_lib/arrow/_cuda.pyx
```

**Steps/Code to reproduce bug**
Build cudf python bindings on ARM after building and installing libcudf.

**Expected behavior**
Successful compilation of cudf python bindings.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal.
 - Method of cuDF install: from source.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit d6b4794b4a3ed7e6577042596a32732bd62fd074 (HEAD -> branch-0.13, origin/branch-0.13, origin/HEAD)
     Merge: ecfd1307a a0c64d997
     Author: Raza Jafri <razajafri@users.noreply.github.com>
     Date:   Sat Feb 8 21:39:01 2020 -0800

     Merge pull request #4069 from razajafri/stringcast

     Added cast of numeric columns to/from string
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     bcd545071c7a5ddb28cb6576afc6399eb1286c43 thirdparty/jitify (heads/cudf)
     cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx (0.8.1-99-gcdcda48)
     a97a7380c76346c22bb67b93695bed19592afad2 thirdparty/libcudacxx/libcxx (heads/rapidsai-interop)

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux Titan 4.9.140-tegra #1 SMP PREEMPT Sat Oct 19 15:54:06 PDT 2019 aarch64 aarch64 aarch64 GNU/Linux

     ***GPU Information***
./print_env.sh: line 25: nvidia-smi: command not found

     ***CPU***
     Architecture:        aarch64
     Byte Order:          Little Endian
     CPU(s):              4
     On-line CPU(s) list: 0-3
     Thread(s) per core:  1
     Core(s) per socket:  4
     Socket(s):           1
     Vendor ID:           ARM
     Model:               1
     Model name:          Cortex-A57
     Stepping:            r1p1
     CPU max MHz:         1428.0000
     CPU min MHz:         102.0000
     BogoMIPS:            38.40
     L1d cache:           32K
     L1i cache:           48K
     L2 cache:            2048K
     Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.16.4

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Mon_Mar_11_22:13:24_CDT_2019
     Cuda compilation tools, release 10.0, V10.0.326

     ***Python***
     /usr/bin/python
     Python 2.7.15

     ***Environment Variables***
     PATH                            : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/abishek/.local/bin:/usr/local/cuda/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 : /usr/local/lib::/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     pip not found
</pre></details>

**Additional context**
Although env reports default Python as 2.7.15, I've used Python3 throughout my build.
If this bug is resolved, I expect a successful cudf installation on ARM.

**Comment by kkraus14** [comment]
@heavyinfo It looks like it's not finding the Arrow Cython headers properly. How did you install arrow-cpp / pyarrow?

**Comment by kkraus14** [comment]
Also, FYI: Jetson Nano has a Maxwell architecture GPU on it which doesn't support certain atomics that we use in libcudf (specifically for certain reductions I believe),

**Comment by heavyinfo** [comment]
@kkraus14 , thank you for the quick response.

As for arrow modules in my system,
version : 0.15.1
arrow cpp was built with following modules -
```
cmake -DCMAKE_INSTALL_PREFIX=$ARROW_HOME \       
      -DCMAKE_INSTALL_LIBDIR=lib  \
      -DARROW_FLIGHT=ON \
      -DARROW_GANDIVA=ON  \
      -DARROW_ORC=ON  \
      -DARROW_WITH_BZ2=ON \       
      -DARROW_WITH_ZLIB=ON  \
      -DARROW_WITH_ZSTD=ON  \
      -DARROW_WITH_LZ4=ON \       
      -DARROW_WITH_SNAPPY=ON  \      
      -DARROW_WITH_BROTLI=ON  \       
      -DARROW_PARQUET=ON  \
      -DARROW_PYTHON=ON \
      -DARROW_PLASMA=ON \
      -DARROW_CUDA=ON \
      -DARROW_BUILD_TESTS=ON  \
      -DPYTHON_EXECUTABLE=/usr/bin/python3  \
      ..
```
Pyarrow was built with following options -
```
export PYARROW_WITH_FLIGHT=1
export PYARROW_WITH_GANDIVA=1
export PYARROW_WITH_ORC=1
export PYARROW_WITH_PARQUET=1
export PYARROW_WITH_CUDA=1
export PYARROW_WITH_PLASMA=1
```
Both, libarrow and Pyarrow was built and installed successfully. It is being used to store pandas DataFrame in feather format.

Although, when I built libcudf it didn't seem to make use of libarrow* existing in my system but downloaded it new.

Thanks for letting me know about Maxwell limitation on Jetson Nano, new Volta based Jetson Xavier NX SOM is coming next month which can be used with the Jetson Nano board and so if we can get the ARM build, installations issues sorted out cudf can be a great asset to the performance of these little machines.

**Comment by kkraus14** [comment]
@heavyinfo we actually need an installed libarrow for dynamic linking and we compile the static lib ourself to static link some symbols (IO related and all of the CUDA related symbols). Where is `$ARROW_HOME` above, where does pyarrow get installed and can you confirm the `.pxd` files from their Cython are installed there as well?

**Comment by heavyinfo** [comment]
@kkraus14 My `$ARROW_HOME` is at `/usr/local/lib`

```
cd /usr/local/lib
ls | grep arrow

libarrow.a
libarrow.so
libarrow.so.100
libarrow.so.100.0.0
libarrow_cuda.a
libarrow_cuda.so
libarrow_cuda.so.100
libarrow_cuda.so.100.0.0
libarrow_dataset.a
libarrow_dataset.so
libarrow_dataset.so.100
libarrow_dataset.so.100.0.0
libarrow_flight.a
libarrow_flight.so
libarrow_flight.so.100
libarrow_flight.so.100.0.0
libarrow_flight_testing.a
libarrow_flight_testing.so
libarrow_flight_testing.so.100
libarrow_flight_testing.so.100.0.0
libarrow_python.a
libarrow_python.so
libarrow_python.so.100
libarrow_python.so.100.0.0
libarrow_python_flight.a
libarrow_python_flight.so
libarrow_python_flight.so.100
libarrow_python_flight.so.100.0.0
libarrow_testing.a
libarrow_testing.so
libarrow_testing.so.100
libarrow_testing.so.100.0.0
```

> can you confirm the .pxd files from their Cython are installed there as well?
Their .pxd files are located in this path,

```
cd /usr/local/lib/python3.6/dist-packages/pyarrow-0.15.1.dev356+gbe6fad5f4.d20191218-py3.6-linux-aarch64.egg/pyarrow

ls *.pxd
__init__.pxd  _cuda.pxd  _fs.pxd  _orc.pxd  _parquet.pxd  lib.pxd

```
`_cuda.pyx ` is also present but as the error log in the first post shows, only the arrow files inside the cudf are being used during the error.

**Comment by kkraus14** [comment]
We vendored over the cuda Cython bits, but they call into the general pyarrow Cython headers: https://github.com/rapidsai/cudf/blob/branch-0.13/python/cudf/cudf/_lib/arrow/_cuda.pxd#L27-L29

Specifically the `RandomAccessFile` and `OutputStream` should come from here: https://github.com/apache/arrow/blob/apache-arrow-0.15.1/python/pyarrow/includes/libarrow.pxd#L770-L783

It looks like those headers aren't being found for some reason. Can you confirm you're running python3.6 that's installed out of `/usr/local/lib/python3.6`?. The environment dump is showing Python 2.7.

**Comment by heavyinfo** [comment]
Those imports makes sense on how system pyarrow is being used.

But I'm 100% sure that python 3.6 is being used as I explicitly invoke that during build and also the errors show that it's being used.

Also, even if I try to explicitly run using python2; it throws `CUDA_HOME` doesn't exist error even before starting the build process. So, we can definitely conclude that only python3.6.9 being used.

Even the specific files used in the import are available in the path,

```
/usr/local/lib/python3.6/dist-packages/pyarrow-0.15.1.dev356+gbe6fad5f4.d20191218-py3.6-linux-aarch64.egg/pyarrow/includes$ ls -a
.   __init__.pxd  libarrow.pxd       libarrow_flight.pxd  libgandiva.pxd
..  common.pxd    libarrow_cuda.pxd  libarrow_s3fs.pxd    libplasma.pxd
```
If the import failed, wouldn't it throw error right at the beginning during execution of the import statements in cython?

**Comment by kkraus14** [comment]
> If the import failed, wouldn't it throw error right at the beginning during execution of the import statements in cython?

Possibly. Cython is a bit finicky in this regard. You don't happen to have a newer version of arrow installed as well, right? These names changed in 0.16.0 I believe where if its picking up a 0.16.0 install it won't be able to find them.

**Comment by heavyinfo** [comment]
> Possibly. Cython is a bit finicky in this regard.

In the issue #3656, the import statements throw error where expected when that user didn't have PyArrow installed. 

> You don't happen to have a newer version of arrow installed as well, right? 
No, I have only 0.15.1 installed.
```
pip3 freeze | grep pyarrow
pyarrow==0.15.1.dev356+gbe6fad5f4.d20191218
```
Also, I've been using pyarrow regularly to save pandas data frame in feather format.

Should I ask about this at the arrow JIRA?

**Comment by kkraus14** [comment]
I really don't know from here. We technically use Arrow 0.15.0 in our builds currently whereas you have 0.15.1 installed but I don't think that should cause an issue, especially after confirming the type names haven't changed.

Could you dump the output of `pip3 list` as well as `python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`?

**Comment by heavyinfo** [comment]
```
python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"
/usr/lib/python3/dist-packages
```
Where as the pyarrow path is /`usr/local/lib/python3.6/dist-packages/` as it was built from source.

**Comment by kkraus14** [comment]
Aha, our Python setup.py will not search in `/usr/local/lib/python3.6/dist-packages` and will only search in `/usr/lib/python3/dist-packages` due to this line: https://github.com/rapidsai/cudf/blob/branch-0.13/python/cudf/setup.py#L51

Could you try replacing `get_python_lib()` with os.sys.path but making it the second item in the list instead of the first? I believe that should allow it to find your PyArrow Cython headers.

**Comment by heavyinfo** [comment]
Unfortunately, that didn't resolve the issue. Same error after changing the setup.py and executing it.

Executing the suggested change on terminal, does show all paths.

```
python3 -c "from distutils.sysconfig import get_python_lib; import os; print([os.path.join(os.sys.prefix, 'lib')] + os.sys.path)"

['/usr/lib', '', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/abishek/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/local/lib/python3.6/dist-packages/pyarrow-0.15.1.dev356+gbe6fad5f4.d20191218-py3.6-linux-aarch64.egg', '/usr/local/lib/python3.6/dist-packages/torchvision-0.5.0a0+85b8fbf-py3.6-linux-aarch64.egg', '/usr/local/lib/python3.6/dist-packages/sentencepiece-0.1.85-py3.6-linux-aarch64.egg', '/usr/local/lib/python3.6/dist-packages/nvstrings_cudaunknown-0.0.0.dev0-py3.6-linux-aarch64.egg', '/usr/local/lib/python3.6/dist-packages/spacy-2.2.3-py3.6-linux-aarch64.egg', '/usr/local/lib/python3.6/dist-packages/torchtext-0.5.1-py3.6.egg', '/usr/lib/python3/dist-packages', '/usr/lib/python3.6/dist-packages']
```

**Comment by kkraus14** [comment]
Can you similarly try adding the path to the `include_dirs`? https://github.com/rapidsai/cudf/blob/branch-0.13/python/cudf/setup.py#L41-L50

In hindsight it looks like that controls where Cython will search for things to cimport where `library_dirs` just controls where shared objects are found for dynamic linking.

**Comment by heavyinfo** [comment]
I added all the paths shown in the earlier output manually to the include_dirs, unfortunately there was no difference.

Should I try building with `-DCMAKE_CXX11_ABI=OFF` ? But it takes two days to compile though as only single job can be executed due to limited memory. (But, memory is not an issue for current issue as I've been monitoring when trying to build this).

**Comment by heavyinfo** [comment]
@kkraus14 I changed the parameter name from `OutputStream` to `COutputStream` and `RandomAccessFile` to `CRandomAccessFile` as in https://github.com/apache/arrow/blob/412145b8a736a5dce4f17b03d7f72efb45053176/python/pyarrow/_cuda.pyx

And the _cuda.pyx has now successfully Cythonized! But, the error now is at second file - 

```
[ 2/35] Cythonizing cudf/_lib/avro.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int32_t, uint32_t
from libcpp cimport bool
from libcpp.vector cimport vector
from libcpp.memory cimport unique_ptr

from rmm._lib.device_buffer cimport device_buffer, DeviceBuffer, move
^
------------------------------------------------------------

cudf/_libxx/lib.pxd:6:0: 'rmm/_lib/device_buffer.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int32_t, uint32_t
from libcpp cimport bool
from libcpp.vector cimport vector
from libcpp.memory cimport unique_ptr

from rmm._lib.device_buffer cimport device_buffer, DeviceBuffer, move
^
------------------------------------------------------------

cudf/_libxx/lib.pxd:6:0: 'rmm/_lib/device_buffer/device_buffer.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int32_t, uint32_t
from libcpp cimport bool
from libcpp.vector cimport vector
from libcpp.memory cimport unique_ptr

from rmm._lib.device_buffer cimport device_buffer, DeviceBuffer, move
^
------------------------------------------------------------

cudf/_libxx/lib.pxd:6:0: 'rmm/_lib/device_buffer/DeviceBuffer.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
from libc.stdint cimport int32_t, uint32_t
from libcpp cimport bool
from libcpp.vector cimport vector
from libcpp.memory cimport unique_ptr

from rmm._lib.device_buffer cimport device_buffer, DeviceBuffer, move
^
------------------------------------------------------------

cudf/_libxx/lib.pxd:6:0: 'rmm/_lib/device_buffer/move.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
        data_type(type_id id)
        type_id id()

cdef extern from "cudf/column/column.hpp" namespace "cudf" nogil:
    cdef cppclass column_contents "cudf::column::contents":
        unique_ptr[device_buffer] data
                               ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:40:32: unknown type in template argument

Error compiling Cython file:
------------------------------------------------------------
...
        type_id id()

cdef extern from "cudf/column/column.hpp" namespace "cudf" nogil:
    cdef cppclass column_contents "cudf::column::contents":
        unique_ptr[device_buffer] data
        unique_ptr[device_buffer] null_mask
                               ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:41:32: unknown type in template argument

Error compiling Cython file:
------------------------------------------------------------
...
        vector[unique_ptr[column]] children

    cdef cppclass column:
        column()
        column(const column& other)
        column(data_type dtype, size_type size, device_buffer&& data)
                                               ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:47:48: 'device_buffer' is not a type identifier
warning: cudf/_libxx/lib.pxd:146:32: Function 'move' previously declared as 'private', now as 'extern'

Error compiling Cython file:
------------------------------------------------------------
...
        table_view source_table,
        column_view gather_map
    )

cdef extern from "<utility>" namespace "std" nogil:
    cdef unique_ptr[column] move(unique_ptr[column])
                               ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:146:32: Function signature does not match previous declaration
warning: cudf/_libxx/lib.pxd:147:31: Function 'move' previously declared as 'private', now as 'extern'

Error compiling Cython file:
------------------------------------------------------------
...
        column_view gather_map
    )

cdef extern from "<utility>" namespace "std" nogil:
    cdef unique_ptr[column] move(unique_ptr[column])
    cdef unique_ptr[table] move(unique_ptr[table])
                              ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:147:31: Function signature does not match previous declaration
warning: cudf/_libxx/lib.pxd:148:40: Function 'move' previously declared as 'private', now as 'extern'

Error compiling Cython file:
------------------------------------------------------------
...
    )

cdef extern from "<utility>" namespace "std" nogil:
    cdef unique_ptr[column] move(unique_ptr[column])
    cdef unique_ptr[table] move(unique_ptr[table])
    cdef vector[unique_ptr[column]] move(vector[unique_ptr[column]])
                                       ^
------------------------------------------------------------

cudf/_libxx/lib.pxd:148:40: Function signature does not match previous declaration
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    ext_modules=cythonize(extensions),
  File "/home/abishek/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1096, in cythonize
    cythonize_one(*args)
  File "/home/abishek/.local/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1219, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: cudf/_lib/avro.pyx
```

**Comment by kkraus14** [comment]
> @kkraus14 I changed the parameter name from `OutputStream` to `COutputStream` and `RandomAccessFile` to `CRandomAccessFile` as in https://github.com/apache/arrow/blob/412145b8a736a5dce4f17b03d7f72efb45053176/python/pyarrow/_cuda.pyx
> 
> And the _cuda.pyx has now successfully Cythonized!

That sounds like it's finding a pyarrow 0.16.0 install then, because those were renamed in 0.16.0.

> But, the error now is at second file

It looks like it's not finding the rmm Cython headers now.

**Comment by heavyinfo** [comment]
> That sounds like it's finding a pyarrow 0.16.0 install then, because those were renamed in 0.16.0.

Not sure why, PyArrow version reports as 0.15.1 and when I downloaded, built it only that version was available.

I checked the `_cuda.pyx` file at `/usr/local/lib/python3.6/dist-packages/pyarrow-0.15.1.dev356+gbe6fad5f4.d20191218-py3.6-linux-aarch64.egg/pyarrow the name of those attributes were as in the arrow master.

So maybe they were changed in 0.15.1 itself?

> It looks like it's not finding the rmm Cython headers now.

Okay, I didn't install python module of rmm.  So, I built and installed it.

While doing so, it couldn't find rmm installed earlier in `/usr/local/lib/rmm/ `and set in `RMM_ROOT` .

`/usr/bin/ld: cannot find -lrmm
`
So created a soft link for `librmm.so` at `/usr/local/lib/` and I was able to build, install rmm==0.13.0 successfully.

Now, cudf completes all initial checks for build successfully and fails at 

```
cudf/_lib/arrow/_cuda.cpp:692:10: fatal error: arrow/python/platform.h: No such file or directory
 #include "arrow/python/platform.h"
```

That file was available in this path - `/usr/local/lib/include/arrow/python/`

So, I went ahead and changed `setup.py` once again and then I received -

`/usr/bin/ld: cannot find -lcudf
`
So created another symlink for `libcudf.so` at `/usr/local/lib/`

Then I received,

```
cudf/_lib/avro.cpp:696:10: fatal error: rmm/rmm.h: No such file or directory
 #include "rmm/rmm.h"
```
Edited setup.py again to include `/usr/local/lib/rmm/include/`

Then as expected,
```
cudf/_lib/dlpack.cpp:713:10: fatal error: dlpack/dlpack.h: No such file or directory
 #include "dlpack/dlpack.h"
```
Edited setup.py again to include `/usr/local/lib/dlpack/include/`

**Then cudf build and install was successful!**

To test,
```
python3 -v
import cudf
....
OSError: Could not load shared object file: libllvmlite.so
```

So, I guess now I'm onto llvmlite build now. I will update tomorrow.

**Comment by kkraus14** [comment]
@heavyinfo thanks for the update! Would you mind submitting a PR to update our `setup.py` to resolve these issues?

**Comment by heavyinfo** [comment]
> I guess now I'm onto llvmlite build now


I reinstalled `llvmlite` via pip3 and that error is gone.

Had some errors with cudf libs such as `libNV*.so` which I symlinked to /usr/local/lib.

had to install `fsspec`, `cupy` via  pip3 ( `cupy` further installed its dependency `fastrlock`).

It seems to import cudf fine after that.

I'm going to perform some real world tests for cudf, just to be sure. 

@kkraus14 , can you tell me where I'm likely to face issues due to **maxwell GPU** architecture and how it would look like? I intended to perform simple data frame operations like reading csv of different data types, describing data etc.

> Would you mind submitting a PR to update our setup.py to resolve these issues?

I would love to submit a PR. I appreciate your patience in answering my questions.

But, shouldn't we confirm about whether `0.15.1` is compatible and why even if `/usr/local/lib` is in path it doesn't look inside `/usr/local/lib/arrow` or `/usr/local/lib/rmm` or `/usr/local/lib/dlpack` or `/usr/local/lib/cudf` and so I had to soft link the *.so files (or) I should have installed them directly in `/usr/local/lib` and not in a separate folder.

**Comment by kkraus14** [comment]
> @kkraus14 , can you tell me where I'm likely to face issues due to maxwell GPU architecture and how it would look like? I intended to perform simple data frame operations like reading csv of different data types, describing data etc.

I believe we use certain atomics in reductions that were implemented in the pascal architecture. I'm not sure if they'll crash and burn or just use something like a CAS underneath and run slower. I'll ping some people to see if someone can answer 😄.

> I would love to submit a PR. I appreciate your patience in answering my questions.

> But, shouldn't we confirm about whether 0.15.1 is compatible and why even if /usr/local/lib is in path it doesn't look inside /usr/local/lib/arrow or /usr/local/lib/rmm or /usr/local/lib/dlpack or /usr/local/lib/cudf and so I had to soft link the *.so files (or) I should have installed them directly in /usr/local/lib and not in a separate folder.

Yes, we should figure out how we can correctly get the python setup process to find the relevant library extensions without having to symlink them all over.

**Comment by heavyinfo** [comment]
Unfortunately, it didn't work.

```
import cudf
gdf = cudf.read_csv('path/to/file.csv')
for column in gdf.columns:
    print(gdf[column].mean())
```
resulted in,

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: no kernel image is available for execution on the device
```
It's likely due to the GPU architecture being Maxwell with 5.3 compute capability and cudf requires at-least 6.0+ as per [prerequisites](https://rapids.ai/start.html). You did try to warn me!

Anyways, I'm glad that we were able to get cudf built, installed successfully on ARM (which may be the first time, judging from the open issues).

I will write a gist and also submit a PR for path fixes once we conclude best strategy to parse the include_dirs.

**Comment by kkraus14** [comment]
@heavyinfo You could try passing an empty string to the `GPU_ARCHS` cmake variable when building libcudf: https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/CMakeLists.txt#L83

That should try to build it for compute 5.3 but unsure how compilation / execution will go.

**Comment by heavyinfo** [comment]
Using GPU_ARCHS="" showed correct GPU compute architecture number during the preparation of make files.

Proceeding with make now. I'll update tomorrow.

**Comment by heavyinfo** [comment]
It worked! Was able to execute cudf operations, had some learning curve regard supported data types and to change workflow from pandas for testing.

As for performance improvements, as long as data set is small there are definitely improvements; but since all cores, CUs are used the memory runs out and ends up crashing.

reg https://github.com/rapidsai/cudf/issues/4121#issuecomment-585864035

> I changed the parameter name from OutputStream to COutputStream and RandomAccessFile to CRandomAccessFile as in https://github.com/apache/arrow/blob/412145b8a736a5dce4f17b03d7f72efb45053176/python/pyarrow/_cuda.pyx

I think that may be because, I cloned from arrow git and didn't use proper 0.15.1 source from their releases.

reg https://github.com/rapidsai/cudf/issues/4121#issuecomment-585938993

> /usr/bin/ld: cannot find -lrmm
> So created a soft link for librmm.so at /usr/local/lib/ and I was able to build, install rmm==0.13.0 successfully.

> /usr/bin/ld: cannot find -lcudf
> So created another symlink for libcudf.so at /usr/local/lib/

I think that could be resolved with proper LD_LIBRARY_PATH,
```
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/lib/cudf/lib:/usr/local/lib/rmm/lib:$LD_LIBRARY_PATH
```

So, only issue which may need your attention is finding python headers of installed arrow, rmm, dlpack in setup.py(https://github.com/rapidsai/cudf/blob/master/python/cudf/setup.py#L41) as mentioned in https://github.com/rapidsai/cudf/issues/4121#issuecomment-585938993.

But the user can install them in any location, so need to think of the best strategy to implement them.

**Comment by heavyinfo** [comment]
I have written the build procedure for cudf on ARM (Jetson) here - https://gist.github.com/heavyinfo/da3de9b188d41570f4e988ceb5d81abc.

**Comment by kkraus14** [comment]
Closing as this is resolved.
