### ISSUE TITLE
[FEA] Change returned size of offsets from `sort_groupby_helper::group_offsets`

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#4135]
As per https://github.com/rapidsai/cudf/pull/4039#discussion_r374227055, `sort_groupby_helper::group_offsets()` should return `num_groups + 1` values with the last one being simply the size of the values. This is required for some use cases like:

1. The aforementioned groupby rolling https://github.com/rapidsai/cudf/pull/4039 where the current method would incur an extra device vector operation.
2. `groupby.nth()` needs to be able to include/exclude nulls to calculate nth. For this it needs to calculate group sizes with and without nulls. Calculating without nulls is taken care of using `detail::group_count` but for with nulls it should be able to use `group_offsets[i+1] - group_offsets[i]`

**Comment by devavret** [comment]
A simple way to do this could be:
https://github.com/rapidsai/cudf/blob/c190442ca216085cec47913de9bb7a08f3b01d2b/cpp/src/groupby/sort/sort_helper.cu#L178
be replaced with
```c++
_group_offsets[num_groups] = num_keys();
_group_offsets->resize(num_groups + 1);
```
and https://github.com/rapidsai/cudf/blob/c190442ca216085cec47913de9bb7a08f3b01d2b/cpp/include/cudf/detail/groupby/sort_helper.hpp#L129
with 
```c++
size_type num_groups() { return group_offsets().size() - 1; } 
```
But obviously open to suggestions.

**Comment by karthikeyann** [comment]
The last element of group_offsets will not be num_groups.
unique_copy won't copy after last unique element.

https://github.com/rapidsai/cudf/blob/c190442ca216085cec47913de9bb7a08f3b01d2b/cpp/src/groupby/sort/sort_helper.cu#L164

so resizing may not work.

**Comment by jrhemstad** [comment]
Does the helper have a function to return the size of each group? The standard way of computing an `n+1` vector of offsets is to get the size of each group and do an inclusive scan starting at the second element.

**Comment by devavret** [comment]
@jrhemstad This one does it differently. It directly calculates the offset based on the indices that are different from their subsequent. Reduces compute complexity.

**Comment by jrhemstad** [comment]
In that case, the solution you proposed makes sense.
