### ISSUE TITLE
[FEA] libcuDF function to convert a validity bitmask to a column of bools

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#4142]
**Is your feature request related to a problem? Please describe.**
Effectively want the reverse of this function: https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/transform.hpp#L68-L85

**Describe the solution you'd like**
It would be extra great if the mask wasn't required to be 64 byte padded or even 4 byte padded, but beggers can't be choosers :).

**Describe alternatives you've considered**
We currently have a numba function in cuDF for this but would like to defer down to libcuDF functionality.

**Comment by jrhemstad** [comment]
> It would be extra great if the mask wasn't required to be 64 byte padded or even 4 byte padded, but beggers can't be choosers :).

Strictly speaking, none of our functionality relies on the 64B padding. We _definitely_ rely on 4B padding.

**Comment by kkraus14** [comment]
> `bitmask_type` is a 4B type. It would be illegal to pass in any allocation that can't be reference via a `bitmask_type*` (i.e., an allocation whose size is not a multiple of 4B).

Yea, unfortunately some of the situations where I'd like to use this we could have a user pass a non-cudf controlled object into it which doesn't guarantee 4B alignment, i.e. having a column of 5 values and they construct a 1 element int8 array to pass for a mask. We can allocate a properly padded mask and copy into the mask, but that's unfortunately expensive.

**Comment by jrhemstad** [comment]
This should be a trivial wrapper around `true_if`:

https://github.com/rapidsai/cudf/blob/1ead2d55562b9cd1b80568b86b8b51ab616f3cb8/cpp/include/cudf/detail/unary.hpp#L42

**Comment by jrhemstad** [comment]
> Yea, unfortunately some of the situations where I'd like to use this we could have a user pass a non-cudf controlled object into it which doesn't guarantee 4B alignment, i.e. having a column of 5 values and they construct a 1 element int8 array to pass for a mask. We can allocate a properly padded mask and copy into the mask, but that's unfortunately expensive.

A library allocating such objects should be beaten with sticks for violating the Arrow spec.

**Comment by kkraus14** [comment]
It's not necessarily related to Arrow, for example someone could have used PyTorch or CuPy which are more traditional array libraries similar to a `thrust::device_vector`

**Comment by jrhemstad** [comment]
> It's not necessarily related to Arrow, for example someone could have used PyTorch or CuPy which are more traditional array libraries similar to a `thrust::device_vector`

Then if they care about performance, they should be _strongly_ encouraged to use a 4B padded allocation. Reading a bitmask 1B at a time gives garbage performance.

**Comment by kkraus14** [comment]
> > It's not necessarily related to Arrow, for example someone could have used PyTorch or CuPy which are more traditional array libraries similar to a `thrust::device_vector`
> 
> Then if they care about performance, they should be _strongly_ encouraged to use a 4B padded allocation. Reading a bitmask 1B at a time gives garbage performance.

We can absolutely throw a warning in that situation if desired, but sounds like in the meantime we should probably just allocate a properly sized / padded Buffer and DtoD copy into it if their allocation isn't 4 byte aligned.

**Comment by jrhemstad** [comment]
> We can absolutely throw a warning in that situation if desired, but sounds like in the meantime we should probably just allocate a properly sized / padded Buffer and DtoD copy into it if their allocation isn't 4 byte aligned.

I was thinking something more along the lines of filing issues against these libraries to do something more sane.

**Comment by kkraus14** [comment]
If the library is just an NDArray library and you ask for int8 elements that's all they should give you, no? For example if we have an int8 column, we don't do the underlying math using `int32_t` I would assume?

**Comment by jrhemstad** [comment]
> If the library is just an NDArray library and you ask for int8 elements that's all they should give you, no?

Perhaps, so just don't use `int8` for bitmasks. Use a 4B type. 

> For example if we have an int8 column, we don't do the underlying math using int32_t I would assume?

Technically it will always be 8B padded if it's allocated with RMM.

**Comment by jrhemstad** [comment]
This function exists: https://github.com/rapidsai/cudf/blob/7b9ea2b480ba723e5fc70e17c42a0a93123fef80/cpp/include/cudf/transform.hpp#L175-L200
