### ISSUE TITLE
[FEA] Add expect_tables_equivalent

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#4150]
**Is your feature request related to a problem? Please describe.**
PR https://github.com/rapidsai/cudf/pull/3776 added `expect_columns_equivalent`, which is more permissive than `expect_columns_equal`. In particular, non-nullable columns and nullable columns with all valids are considered equivalent but not equal. This functionality should be extended to tables.

**Describe the solution you'd like**
Add an `expect_tables_equivalent` to extend the `expect_columns_equivalent` functionality to tables.

**Comment by davidwendt** [comment]
Looks like `cudf::test::expect_tables_equivalent` was added in #4147

**Comment by trevorsm7** [comment]
I took a look through the code to see if there were any places where loops with `expect_columns_equivalent` that could be replaced with `expect_tables_equivalent` and didn't find any, so I'll go ahead and close this.
