### ISSUE TITLE
[BUG] from_timestamp handles some literals incorrectly

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4160]
**Describe the bug**
%z doesn't reporting anything back in the time zones
%p reports 12pm as AM
%I reports back 00 as the hour for 12pm 
%j reports wrong values 

 //'2018-07-04 12:00:00' 
from_timestamps(1530705600L,  "%p::%I") ----> AM::00

- Test from_unixtime with day of the year *** FAILED ***
  Running on the GPU and on the CPU did not match 

Day of the year is also reported wrong when the following dates were used 

      118800L, //1970-01-02 09:00:00
      1293901860L, //2011-01-01 17:11:00
      318402000L, //1980-02-03 05:00:00
      604996200L, //1989-03-04 06:30:00
      1270413572L, //2010-04-04 20:39:32
      1588734621L, //2020-05-06 03:10:21
      2550814152L, //2050-10-31 07:29:12
      4102518778L, //2100-01-01 20:32:58
      702696234, //1992-04-08 01:23:54
      6516816203L, //2176-07-05 02:43:23
      26472091292L, //2808-11-12 22:41:32
      4133857172L, //2100-12-30 01:39:32
      1560948892, //2019-06-19 12:54:52
      4115217600L //2100-05-28 20:00:00

The last 3 digits are reported by the method as day-of-the-year which is wrong as its reporting the day of the month instead  
format = %d/%m/%Y %j
[02/01/1970 002], 
[01/01/2011 001], 
[03/02/1980 003], 
[04/03/1989 004], 
[04/04/2010 004], 
[06/05/2020 006], 
[31/10/2050 031], 
[01/01/2100 001], 
[08/04/1992 008], 
[05/07/2176 005], 
[12/11/2808 012], 
[30/12/2100 030], 
[19/06/2019 019], 
[28/05/2100 028]

**Expected behavior**

PM::12

for %z may be we should just output +0000 since the times are all in UTC

Last 3 digits are the day of the year
format = %d/%m/%Y %j
[02/01/1970 002], 
[01/01/2011 001], 
[03/02/1980 034], 
[04/03/1989 063],
[04/04/2010 094], 
[06/05/2020 127], 
[31/10/2050 304], 
[01/01/2100 001], 
[08/04/1992 099],
[05/07/2176 187], 
[12/11/2808 317], 
[30/12/2100 364], 
[19/06/2019 170], 
[28/05/2100 148])

**Comment by razajafri** [comment]
@davidwendt

**Comment by davidwendt** [comment]
The '%j' specifier is not officially supported.
https://github.com/rapidsai/cudf/blob/4da06c6eaf6018bb63edf1883e95d64888f0318a/cpp/include/cudf/strings/convert/convert_datetime.hpp#L59
The `nvstrings` code is being deprecated so the https://rapidsai.github.io/projects/nvstrings/en/0.12.0/datetime.html# page will need to be moved/updated.
