### ISSUE TITLE
[BUG] New GPU-accelerated parquet_writer error

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4161]
```
import cudf
df = cudf.DataFrame({'x':[1,2,3], 'y':["a","b","c"]})
df.to_parquet("parquet_files")
```
gives me the following error:
 
`TypeError: descriptor 'encode' requires a 'str' object but received a 'NoneType'`

Am I doing something wrong?

**Comment by kkraus14** [comment]
@jdye64 can you take a look?

**Comment by jdye64** [comment]
Yep looking now
