### ISSUE TITLE
[QST] Large Parquet Query Setup

### ISSUE THREAD

**Issue by sshakeri** [rapidsai/cudf#4169]
What is the recommended hardware/ implementation of Dask-cudf to handle querying and joining various parquet files amounting to 2 TBs? 

I have tried out BlazingDB and it works for reading a subset of rowgroups. But for large files that don't fit into the GPU memory, what is the best approach? 

Thanks

**Comment by kkraus14** [comment]
Apologies that this was never answered.

It's very data dependent, but in general the more GPU memory you have and better networking interconnect you have the better. With more GPU memory we can keep more of the data in GPU memory for processing and avoid spilling.

For things like distributed joins, it causes an all-to-all communication pattern where having infiniband and RDMA can give massive speedups.

The TPCx-BB blog in handling SF10k is likely a good resource for some lessons learned from our side in handling large datasets: https://medium.com/rapids-ai/no-more-waiting-interactive-big-data-now-32f7b903cf41
