### ISSUE TITLE
[FEA] Add missing aggregations between sort and hash groupby

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#4179]
**Is your feature request related to a problem? Please describe.**
`groupby::aggregate()` uses a dispatcher internally to select whether the sort or the hash implementation of groupby will be used for all aggregations. If all the aggregations can be satisfied by hash implementation then it uses it, otherwise uses sort implementation for all aggregations. This assumes that the set of supported aggregations by sort impl is a superset of that of hash impl. In the future, if we have an aggregation that is possible (and likely faster) by hash impl, we'd have to implement a sort impl as well. Otherwise, the API will be buggy. Passing aggregation requests that contain both a hash-only and a sort-only aggregation will throw an exception. This will be a case once #4174 is merged as it adds `ARGMIN` and `ARGMAX` as well as string support for `MIN` and `MAX`.
Furthermore, maintaining two different implementations of the same aggregation is not ideal and contributes to code smell.

EDIT: Also to add, hash groupby will make use of multi-agg optimization to compute single-pass aggregations. This wouldn't be used when any of the requested aggs is sort-only and we have to use sort impl even for these single pass aggs.

**Describe the solution you'd like**
~The dispatcher logic needs to change~ https://github.com/rapidsai/cudf/blob/22fa178ba9240de5427802f8744d158b0cf7660e/cpp/src/groupby/groupby.cu#L58-L65
~It should make use of the hash impl for all hash based aggregations and sort impl for all the sort based aggs. In case there are both types then the hash aggregation results should be gathered using `helper.unsorted_labels` to match the order of sort groupby results.~

For the time being, it should suffice to add `ARGMIN`, `ARGMAX`, and `MIN` and `MAX` on strings in sort impl.

**Comment by jrhemstad** [comment]
> It should make use of the hash impl for all hash based aggregations and sort impl for all the sort based aggs.

I don't think it's that simple. The reason for the current heuristic is that if you need to perform a sort for any aggregation, it's probably faster to just use a sort-based implementation for the remaining aggregations. Otherwise you have to incur the cost of both sorting _and_ building the hash map.

**Comment by devavret** [comment]
>it's probably faster to just use a sort-based implementation for the remaining aggregations

Let me get back to you with a profile to see the extent of performance hit. Building a hash map might indeed not be such a fast task due to the use of `atomicCAS`

Notice that:
>if we have an aggregation that is possible (and likely faster) by hash impl, we'd have to implement a sort impl as well. Otherwise, the API will be buggy

Correctness is a necessity. We don't have `ARGMIN` until sort impl also has `ARGMIN`. Same for `MIN` and `MAX` on strings.

**Comment by GregoryKimball** [comment]
Closed by #4456
