### ISSUE TITLE
[BUG] Binary op when one of the operands is a scalar on a TIMESTAMP_DAYS 

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4180]
**Describe the bug**
When doing a binop on a TIMESTAMP_DAYS vector with a scalar (TIMESTAMP_DAYS or INT32) operand or viceversa throws an NVRTC_ERROR_COMPILATION

**Steps/Code to reproduce bug**
call the binaryOp function with one of the operands 

**Expected behavior**
It should return a ColumnVector with the scalar value subtracted. As it does when called on two columnvectors of TIMESTAMP_DAYS type (haven't tested others) 

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by trxcllnt** [comment]
Per: https://github.com/rapidsai/cudf/pull/4256#issuecomment-591205249
The current guidance is to case the timestamp column to the corresponding numeric type, do the binop, and cast the result back to the timestamp dtype.

**Comment by harrism** [comment]
Binops with timestamps will require a duration type. Even when we have that type, the operation described here will be illegal. For now, @trxcllnt 's comment above provides a workaround.
