### ISSUE TITLE
[BUG] BinaryOp on two TIMESTAMP_DAYS columns and casting the result to INT32 throws exception

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4181]
**Describe the bug**
when doing a binary op on two TIMESTAMP_DAYS columns with the result being casted to an INT32 throws an NVRTC_COMPILATION_ERROR. It works when giving the output type as TIMESTAMP_DAYS 

**Steps/Code to reproduce bug**
Call the binaryop with two columns of TIMESTAMP_DAYS type without giving a result type or giving a result type of INT32 (haven't tested other types) 

**Expected behavior**
It should do the operation and return the result with the desired type

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by trxcllnt** [comment]
Per: https://github.com/rapidsai/cudf/pull/4256#issuecomment-591205249
The current guidance is to case the timestamp column to the corresponding numeric type, do the binop, and cast the result back to the timestamp dtype.

**Comment by jrhemstad** [comment]
> Per: [#4256 (comment)](https://github.com/rapidsai/cudf/pull/4256#issuecomment-591205249)
> The current guidance is to case the timestamp column to the corresponding numeric type, do the binop, and cast the result back to the timestamp dtype.

With the note that this is only temporary until we add a duration type.
