### ISSUE TITLE
very slow conversion from cuDF series to numpy array 

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cudf#4188]
**Describe the bug**
a customer reports an issue of converting from cuDF series to numpy array being very, very slow. 

**Steps/Code to reproduce bug**
```
import cugraph
import cudf
import os
import numpy as np

def create_component_fromDF(_df):

    nn = np.array(_df['org_vertices'])
    return nn

len = 768061
wcc = cudf.DataFrame({'org_vertices': np.arange(len),
                     'vertices': np.arange(len)})    // mimic cuGraph output 

tempdf = cudf.DataFrame()
id=1
tempdf['WCC'+str(id)] = [str(create_component_fromDF(wcc))] # this takes 5 minutes. works fine if len is small  
#tempdf['WCC'+str(id)] = [wcc['org_vertices'].to_string()]  # runs but does not write all the information I want 
#tempdf.to_csv('../../xx.csv', index=False)
```
what I need is to create the tempdf to be something like this:
WCC1
"[0,1,2,3,...768061]"

**Expected behavior**
conversion from cudf to numpy array done in a reasonable amount of time.  Actually it does not need to convert to a numpy array, all we want is to transpose a column cudf series to a row, and then convert the row to a long string. there is a transpose API for cudf dataframe, but not for Series. 

Tried conversion from cudf series to Python list -- same slowness. 

The profiling shows all the time is spent on memcpy D2H. 

**Environment overview (please complete the following information)**
 - Method of cuDF install: Docker

On PSGcluster, 
docker pull rapidsai/rapidsai-dev:0.12-cuda10.0-devel-centos7-py3.7

**Comment by kkraus14** [comment]
@dorisnvidia instead of doing `np.array(_df['org_vertices'])` you should do `_df['org_vertices'].to_array()` which should be much faster.

We should support `__array__` protocol though to prevent this slow path.

**Comment by dorisnvidia** [comment]
Thank you Keith for the suggestion! Then the file written is a truncated version, i.e., 

$ more xx.csv
"WCC1"
"[     0      1      2 ... 768058 768059 768060]"

but i need a full list of node indices. See the def function below:
```
def create_component_fromDF(_df):

    #nn = _df['org_vertices'].to_array()
    #nn=np.array(_df['org_vertices'])
    nn=[]
    for i in range(len):
        nn.append(i)
    return nn
```
You can set the len to be say 2000 (otherwise it takes forever to run). Use the Python list append function, it then writes a full list of array elements, which is what I am aiming for.

**Comment by kkraus14** [comment]
Superceded by #4552
