### ISSUE TITLE
Sum_of_squares Series method does not support integer types.

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#419]
Series `sum_of_squares` method is now broken. We also need a unit test for this method, which I'll open a separate issue for.

Example below:

```
import cudf
s = cudf.Series([1,2,3])
s.sum_of_squares()
```
Traceback:

```
---------------------------------------------------------------------------
GDFError                                  Traceback (most recent call last)
<ipython-input-3-f3374dd5b420> in <module>()
----> 1 s.sum_of_squares()

/conda/envs/cudf/lib/python3.5/site-packages/cudf/dataframe/series.py in sum_of_squares(self)
    788 
    789     def sum_of_squares(self):
--> 790         return self._column.sum_of_squares()
    791 
    792     def unique_k(self, k):

/conda/envs/cudf/lib/python3.5/site-packages/cudf/dataframe/numerical.py in sum_of_squares(self)
    229 
    230     def sum_of_squares(self):
--> 231         return cpp_reduce.apply_reduce('sum_squared', self)
    232 
    233     def applymap(self, udf, out_dtype=None):

cudf/bindings/reduce.pyx in cudf.bindings.reduce.apply_reduce()

cudf/bindings/cudf_cpp.pyx in cudf.bindings.cudf_cpp.check_gdf_error()

GDFError: b'GDF_UNSUPPORTED_DTYPE'
```

CUDA 9.2, 410.48, V100, Ubuntu 16.04

**Comment by harrism** [comment]
On the C++ side, this is in reductions.cu, and it returns `GDF_UNSUPPORTED_TYPE` if the type of the column is not one of: `GDF_FLOAT64`, `GDF_FLOAT32`, `GDF_INT64`, `GDF_INT32`, or `GDF_INT8`.

From the sample code, it looks like these should be `GDF_INT32`, but we should check the Series constructor in Python to make sure, I guess?

**Comment by kkraus14** [comment]
It would default to `GDF_INT64` actually, would that be a reason to throw this error?

**Comment by kkraus14** [comment]
Ah in looking in `functions.h` it seems we only have templates for `FLOAT64` and `FLOAT32`.

**Comment by kkraus14** [comment]
@beckernick as a workaround for now you can typecast to `float32` or `float64` then typecast back.

**Comment by beckernick** [comment]
Thanks @kkraus14!

**Comment by harrism** [comment]
`gdf_sum_squared_generic` should switch on the datatype of the column and dispatch the code for GDF_INT64. So that shouldn't be it...

BTW, the gdf functions are poorly named. In my book, `sum_squared` means something mathematically different from `sum_of_squares`!

**Comment by harrism** [comment]
Oh, I see. `gdf_sum_squared_generic` calls `gdf_sum_squared_<type>`, and those other types don't exist. Nice...

**Comment by harrism** [comment]
This is a libcudf bug.

**Comment by jrhemstad** [comment]
@harrism this sounds like a good candidate to be updated with the `type_dispatcher` and `gdf_sum_square_<type>` can all be removed in place of just `gdf_sum_squared`.

**Comment by harrism** [comment]
It sure does! But he's busy with other stuff right now so this is likely to happen a week or more from now.

**Comment by harrism** [comment]
I believe the reason this wasn't implemented before is that for large integer arrays, it's much more likely that you will overflow when summing squares than with floating point arrays. Regardless, that is up to the user to worry about, we should add support. I have a fix in progress using `type_dispatcher`.

**Comment by eyalroz** [comment]
@harrism : Note I've implemented a fix, or the infrastructure for one, with [this commit](https://github.com/eyalroz/cudf/commit/1fa362234745528b77544b5405344b377fd1be73), which separates the return type from the input type. It's not against the type-dispatcher-merged main branch though.

**Comment by harrism** [comment]
I have a PR with a basic fix for functionality (but not accuracy). Accuracy is TODO. As is getting rid of two-level reductions in favor of atomics.
