### ISSUE TITLE
[BUG] Performance regression in d516611507

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#4202]
**Describe the bug**
I have a script that I have been testing using CUDF.  On Commit acab67b91ab7bdc0b11df698e5e8cd7fef4774ae it can run in 3 min and 30 seconds. On commit 
```
commit d516611507cbf0435fa4a0559390e85029c17d98
Author: David Wendt <dwendt@nvidia.com>
Date:   Wed Feb 12 13:46:17 2020 -0500
    Really fix the bug in strings concatenate with offsets
```

The script now takes about 11 mins to complete.  Most of that time appears to be in parsing CSV, which is a requirement for this operation.  I can do some more profiling to be sure exactly what kernel etc is taking all of the slowness. 

**Steps/Code to reproduce bug**
Sadly the script itself is proprietary, but parsing any sufficiently large CSV file with strings in it should show the same issue.

**Expected behavior**
I want string processing to be correct, and I am willing to take a performance hit for that, but with this change it makes it so running on the GPU is no longer cost effective for this one use case.

**Comment by davidwendt** [comment]
I took a look at the commit
https://github.com/rapidsai/cudf/commit/d516611507cbf0435fa4a0559390e85029c17d98
And the only function changed there is the `cudf::strings::detail::concatenate()` function.
As far as I can tell, this function is not called during any `read_csv()` path that I can find.

The old code for this function is here:
https://github.com/rapidsai/cudf/blob/acab67b91ab7bdc0b11df698e5e8cd7fef4774ae/cpp/src/strings/copying/concatenate.cu
It's standalone enough that if you want to compile this one file into your code and see if it resolves the issue.
Otherwise, we will need more information on what your script is doing.

**Comment by revans2** [comment]
I have tested with reverting just d516611 and I see the performance go back to normal.  I'll try to get some performance traces before and after so you can compare.

**Comment by revans2** [comment]
These are the nvprof results for running based off of f950eb0ce28ac89bfec6c05d95e11dae350e2e27

I'll revert the patch and rerun so you can see the difference.  I'll also try and send over the full logs offline if there is more you want/need to see.
```
==32570== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   71.39%  380.118s       403  943.22ms  3.6480us  3.45968s  void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__parallel_for::ParallelForAgent<thrust::cuda_cub::for_each_f<thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::detail::wrapped_function<cudf::strings::detail::_GLOBAL__N__46_tmpxft_00007e25_00000000_6_concatenate_cpp1_ii_80eaa229::concatenate_fn, void>>, unsigned long>, thrust::cuda_cub::for_each_f<thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>, thrust::detail::wrapped_function<cudf::strings::detail::_GLOBAL__N__46_tmpxft_00007e25_00000000_6_concatenate_cpp1_ii_80eaa229::concatenate_fn, void>>, unsigned long>(thrust::use_default, thrust::use_default)
                    6.73%  35.8433s       399  89.833ms  406.27us  654.92ms  void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__merge_sort::BlockSortAgent<int*, int*, long, cudf::experimental::row_lexicographic_comparator<bool=0>, thrust::detail::integral_constant<bool, bool=0>, thrust::detail::integral_constant<bool, bool=0>>, bool, int*, int*, long, int*, int*, cudf::experimental::row_lexicographic_comparator<bool=0>>(int*, long, bool=0, cudf::experimental::row_lexicographic_comparator<bool=0>, bool, bool=0, thrust::detail::integral_constant<bool, bool=0>)
                    6.64%  35.3376s      3907  9.0447ms  43.424us  83.256ms  void thrust::cuda_cub::core::_kernel_agent<thrust::cuda_cub::__merge_sort::MergeAgent<int*, int*, long, cudf::experimental::row_lexicographic_comparator<bool=0>, thrust::detail::integral_constant<bool, bool=0>>, bool, int*, int*, long, int*, int*, cudf::experimental::row_lexicographic_comparator<bool=0>, long*, long>(int*, long, bool=0, cudf::experimental::row_lexicographic_comparator<bool=0>, bool, bool=0, thrust::detail::integral_constant<bool, bool=0>, thrust::cuda_cub::__merge_sort::MergeAgent<int*, int*, long, cudf::experimental::row_lexicographic_comparator<bool=0>, thrust::detail::integral_constant<bool, bool=0>>, bool)

```

**Comment by davidwendt** [comment]
I guess I need to see a test script more than I need to see the numbers here.
I'm unable to see the `read_csv()` API call the `concatenate()` function.

**Comment by revans2** [comment]
Sorry I was wrong.  When I look at the profiling data I see that  it is not in CSV.  It looks like some of the metrics we were collecting at the application level pointed me int he wrong direction.  These are all places where we truly are calling `concatenate()` on string columns.

**Comment by revans2** [comment]
Also so you know none of these columns have an offset.  Not sure if it makes it simpler to just special case it or not.

**Comment by davidwendt** [comment]
Argh, I see it now.
I can change the code back and fix the offsets logic.
I should have a PR today if you want to try it out.
