### ISSUE TITLE
[FEA] Datetime inference

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4205]
**Is your feature request related to a problem? Please describe.**

I wish cudf had configurable datetime inference, as discussed in https://nvcollab.slack.com/archives/GB27DMPK7/p1582154392055700 , because it is awkward to implement with nvstrings, slow to do in pandas, and tricky overall to roll-our-own. 

**Describe the solution you'd like**

A couple locations:

* CSV parsing  (`infer_timestamps=True`, `infer_timestamps={"col1": True}`)
* Series transforms: `series.to_datetime(infer=True)`

It would operate over `string` and `numeric`

It would return:

* Tightest possible datetimes or the original
* A format string

At a minimum, it would recognize:

* Epoch time at typical ns/ms/s resolutions (numeric inputs)
* A few common standard time formats (UTC, UTC+Z, and native formats of top used DBs)

As a reach goal, it'd use a BERT model ;-)

**Describe alternatives you've considered**

We currently do horrible heuristics in the CPU (try pandas, datetime, and manual parsers): slow, brittle, terrible

**Comment by beckernick** [comment]
@lmeyerov is this issue still relevant with the `parse_dates` parameter to `read_csv` and the ability to `infer_datetime_format` in `to_datetime`?

**Comment by beckernick** [comment]
With the capabilities mentioned above, I'm going to close this issue as resolved. Please feel free to reopen if appropriate.
