### ISSUE TITLE
[BUG] Port legacy benchmarks to libcudf++

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#4209]
**Describe the bug**
Some legacy benchmarks are still in `cpp/benchmarks/*` directory. As part of libcudf++ port, this should be moved to `cpp/benchmarks/*/legacy/` and rename those benchmarks to `LEGACY_*` 

- **List of files to be moved**
`cpp/benchmarks/copying/scatter_benchmark.cu`
`cpp/benchmarks/copying/gather_benchmark.cu`
`cpp/benchmarks/stream_compaction/apply_boolean_mask_benchmark.cu`
`cpp/benchmarks/search/search_benchmark.cu`
`cpp/benchmarks/type_dispatcher/type_dispatcher_benchmark.cu`

**Suggested steps**
```
git mv cpp/benchmarks/copying/scatter_benchmark.cu cpp/benchmarks/copying/legacy/scatter_benchmark.cu
git mv cpp/benchmarks/copying/gather_benchmark.cu cpp/benchmarks/copying/legacy/gather_benchmark.cu
git mv cpp/benchmarks/stream_compaction/apply_boolean_mask_benchmark.cu cpp/benchmarks/stream_compaction/legacy/apply_boolean_mask_benchmark.cu
git mv cpp/benchmarks/search/search_benchmark.cu cpp/benchmarks/search/legacy/search_benchmark.cu
git mv cpp/benchmarks/type_dispatcher/type_dispatcher_benchmark.cu cpp/benchmarks/type_dispatcher/legacy/type_dispatcher_benchmark.cu
```
and
rename these benchmarks to `LEGACY_` respectively in `cpp/benchmarks/CMakeLists.txt`

**Comment by harrism** [comment]
Let's repurpose this issue to *port* the legacy benchmarks and then remove them, rather than just moving them.
