### ISSUE TITLE
[BUG] Confusing dtype with mixed types

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#4210]
**Describe the bug**
I was about write up an issue asking for `to_numeric` support but in doing so I may have inadvertently stepped on a bug? If the users hands a cudf Series with a mix of strings/int/floats the dtype, I would have assumed should be 'O'. In cudf, however, the dtype is float and the input data is cast accordingly

For example:

```python
In [6]: cdf = cudf.Series(['1.0', '2', -3])

In [7]: cdf
Out[7]:
0    1.0
1    2.0
2   -3.0
dtype: float64

In [8]: cdf.iloc[0]
Out[8]: 1.0

In [9]: cdf.iloc[0].dtype
Out[9]: dtype('float64')
```

For reference pandas does cast everything as an Object

```python
In [12]: import pandas as pd

In [13]: df = pd.Series(['1.0', '2', -3])

In [14]: df
Out[14]:
0    1.0
1      2
2     -3
dtype: object

In [15]: df.dtype
Out[15]: dtype('O')
```

I suspect this is a low priority issue, and, may in fact not be an issue and we should not expect the same behavior as pandas

**Comment by kkraus14** [comment]
We're likely hitting this case:
```
In [15]: np.asarray(['1.0', '2', -3], dtype=np.dtype(None))
Out[15]: array([ 1.,  2., -3.])
```
