### ISSUE TITLE
[FEA] Remove direct use of `RMM_ALLOC`/rmm::alloc

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4212]
**Is your feature request related to a problem? Please describe.**

RMM is likely to deprecate and remove the `RMM_ALLOC/rmm::alloc` and corresponding `RMM_FREE/rmm::free` APIs https://github.com/rapidsai/rmm/issues/302

**Describe the solution you'd like**
 Remove direct use of these APIs in favor of RAII constructs like `rmm::device_buffer` or `rmm::device_vector`. Alternatively, using the `device_memory_resource` directly from `get_default_resource()` and calling `allocate/deallocate`. 

It looks like current usage is in old legacy code, so this should happen automatically after https://github.com/rapidsai/cudf/issues/4050 is complete.

**Comment by davidwendt** [comment]
There is an important one here for managing the children member in the `column_device_view`
https://github.com/rapidsai/cudf/blob/ad36bdd18ea1d5e1db366b40761a86a4ea526e8c/cpp/src/column/column_device_view.cu#L35

**Comment by jrhemstad** [comment]
> There is an important one here for managing the children member in the `column_device_view`
> https://github.com/rapidsai/cudf/blob/ad36bdd18ea1d5e1db366b40761a86a4ea526e8c/cpp/src/column/column_device_view.cu#L35

Ah yeah, we can replace that with using the memory resource directly or just coming up with another solution all together.

**Comment by vuule** [comment]
@jrhemstad, is `custrings` in the scope of this change?

**Comment by davidwendt** [comment]
> @jrhemstad, is `custrings` in the scope of this change?

You can consider anything `custrings` or `nvstrings` as legacy.
