### ISSUE TITLE
[BUG] Parquet writer crashes kernel on write

### ISSUE THREAD

**Issue by jperez999** [rapidsai/cudf#4213]
**Describe the bug**
When using the cudf parquet writer the kernel restarts without throwing any errors. 

**Steps/Code to reproduce bug**
```
import cudf
import numpy as np
import os

GPU_id = 0
os.environ['CUDA_VISIBLE_DEVICES'] = str(GPU_id)


df = cudf.datasets.timeseries(
    start="2000-01-01",
    end="2000-01-04",
    freq="60s",
    dtypes={
        "name-cat": "category",
        "name-string": "category",
        "id": int,
        "label": int,
        "x": float,
        "y": float,
        "z": float,
    },
).reset_index()

df.to_parquet('.')
```

**Expected behavior**
Expect to write the parquet file out to target with kernel restart. Works in current release (0.12)

**Environment overview (please complete the following information)**
 - Environment location: Docker container
 - Method of cuDF install: from source
   - 
```
docker run --rm -it -p 9888:8888 -p 9787:8787 -p 9786:8786 -p 3000:3000 --ipc=host --name dev_tip -v /home/nfs/srabhi/:/rapids/notebooks/srabhi/ -v /datasets/:/datasets/ -v /home/nfs/eoldridge/:/rapids/notebooks/eoldridge/ -v /home/nfs/jperez/:/rapids/notebooks/jperez/  --gpus '"device=all"' gitlab-master.nvidia.com:5005/rapidsdl/docker/rapidsdl_nite:latest /bin/bash
```

**Environment details**

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit a831f11bdeb2cb8dfcc2f47ef69b596a2334c3d2 (HEAD -> branch-0.13, origin/branch-0.13, origin/HEAD)
     Merge: 52c383d1a 7b9d25ede
     Author: OlivierNV <45697062+OlivierNV@users.noreply.github.com>
     Date:   Wed Feb 19 17:17:16 2020 -0800
     
     Merge pull request #4199 from rapidsai/OlivierNV-fix-memcpy-race
     
     [REVIEW] Fix potential race condition in memcpy_block
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     e3f867027c1d9603b5a677795900465b9fac9cb8 thirdparty/jitify (heads/cudf)
     cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx (0.8.1-99-gcdcda48)
     a97a7380c76346c22bb67b93695bed19592afad2 thirdparty/libcudacxx/libcxx (heads/rapidsai-interop)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux 9d19b70e9277 4.4.0-134-generic #160-Ubuntu SMP Wed Aug 15 14:58:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Thu Feb 20 19:08:29 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   31C    P0    42W / 300W |     11MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   40C    P0    68W / 300W |  11928MiB / 32480MiB |      2%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   32C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   31C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   35C    P0    57W / 300W |  14330MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   33C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   34C    P0    44W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   31C    P0    43W / 300W |      0MiB / 32480MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             3220.679
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.15
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdseed adx smap xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts flush_l1d
     
     ***CMake***
     /conda/envs/rapids/bin/cmake
     cmake version 3.16.4
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /conda/envs/rapids/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /conda/envs/rapids/bin:/conda/condabin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/conda/bin
     LD_LIBRARY_PATH                 : /usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   : /usr/local/cuda/nvvm/lib64/libnvvm.so
     NUMBAPRO_LIBDEVICE              : /usr/local/cuda/nvvm/libdevice/
     CONDA_PREFIX                    : /conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /conda/condabin/conda
     # packages in environment at /conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       0_gnu    conda-forge
     aiohttp                   3.6.2                    pypi_0    pypi
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
     aspy.yaml                 1.3.0                      py_0    conda-forge
     astroid                   2.3.3                    pypi_0    pypi
     astropy                   4.0                      pypi_0    pypi
     async-timeout             3.0.1                    pypi_0    pypi
     attr                      0.3.1                    pypi_0    pypi
     attrs                     19.3.0                     py_0    conda-forge
     babel                     2.8.0                      py_0    conda-forge
     backcall                  0.1.0                      py_0    conda-forge
     beautifulsoup4            4.8.2                    pypi_0    pypi
     black                     19.10b0                  py37_0    conda-forge
     blas                      1.0                    openblas
     bleach                    3.1.1                      py_0    conda-forge
     blis                      0.4.1                    pypi_0    pypi
     bokeh                     1.4.0                    py37_0    conda-forge
     boost-cpp                 1.70.0               h8e57a91_2    conda-forge
     bottleneck                1.3.1                    pypi_0    pypi
     brotli                    1.0.7             he1b5a44_1000    conda-forge
     bzip2                     1.0.8                h516909a_2    conda-forge
     c-ares                    1.15.0            h516909a_1001    conda-forge
     ca-certificates           2020.1.1                      0
     cached-property           1.5.1                      py_0    conda-forge
     catalogue                 1.0.0                    pypi_0    pypi
     certifi                   2019.11.28               py37_0
     cffi                      1.13.2           py37h8022711_0    conda-forge
     cfgv                      3.0.0                      py_0    conda-forge
     chardet                   3.0.4                 py37_1003    conda-forge
     click                     7.0                      pypi_0    pypi
     cloudpickle               1.3.0                      py_0    conda-forge
     cmake                     3.16.4               h28c56e5_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
     commonmark                0.9.1                      py_0    conda-forge
     confuse                   1.0.0                    pypi_0    pypi
     coverage                  5.0.3                    pypi_0    pypi
     cryptography              2.8              py37h72c5cf5_1    conda-forge
     cudatoolkit               10.0.130                      0    nvidia
     cudf                      0.13.0a0+2103.ga831f11bd          pypi_0    pypi
     cudnn                     7.6.0                cuda10.0_0    nvidia
     cupy                      7.2.0            py37he57b8b9_0    conda-forge
     cycler                    0.10.0                   pypi_0    pypi
     cymem                     2.0.3                    pypi_0    pypi
     cython                    0.29.15          py37he1b5a44_0    conda-forge
     cytoolz                   0.10.1           py37h516909a_0    conda-forge
     dask                      2.11.0+4.g54deb7fa          pypi_0    pypi
     dask-cudf                 0.13.0a0+2103.ga831f11bd          pypi_0    pypi
     decorator                 4.4.1                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.11.0+1.g83f8febd          pypi_0    pypi
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.16                     py37_0    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37he1b5a44_0    conda-forge
     entrypoints               0.3                   py37_1000    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastai                    1.0.60                   pypi_0    pypi
     fastavro                  0.22.9           py37h516909a_0    conda-forge
     fastprogress              0.2.2                    pypi_0    pypi
     fastrlock                 0.4             py37he1b5a44_1000    conda-forge
     flake8                    3.7.9                    py37_0    conda-forge
     flatbuffers               1.11.0               he1b5a44_0    conda-forge
     freetype                  2.10.0               he983fc9_1    conda-forge
     fsspec                    0.6.2                      py_0    conda-forge
     future                    0.18.2                   py37_0    conda-forge
     gflags                    2.2.2             he1b5a44_1002    conda-forge
     glog                      0.4.0                he1b5a44_1    conda-forge
     gmp                       6.2.0                he1b5a44_2    conda-forge
     grpc-cpp                  1.23.0               h18db393_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     htmlmin                   0.1.12                   pypi_0    pypi
     hypothesis                5.5.4                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     identify                  1.4.11                     py_0    conda-forge
     idna                      2.8                      pypi_0    pypi
     ignite                    0.3.0                    py37_0    pytorch
     imagesize                 1.2.0                      py_0    conda-forge
     importlib_metadata        1.5.0                    py37_0    conda-forge
     intel-openmp              2020.0                      166
     ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
     ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1                    pypi_0    pypi
     isort                     4.3.21                   py37_0    conda-forge
     jedi                      0.16.0                   py37_0    conda-forge
     jinja2                    2.11.1                     py_0    conda-forge
     joblib                    0.14.1                     py_0
     jpeg                      9c                h14c3975_1001    conda-forge
     json5                     0.9.1                      py_0
     jsonschema                3.2.0                    py37_0    conda-forge
     jupyter-server-proxy      1.2.0                    pypi_0    pypi
     jupyter_client            5.3.4                    py37_1    conda-forge
     jupyter_core              4.6.3                    py37_0    conda-forge
     jupyterlab                1.2.6              pyhf63ae98_0
     jupyterlab-nvdashboard    0.2.0                    pypi_0    pypi
     jupyterlab_server         1.0.6                      py_0
     kaggle                    1.5.6                    pypi_0    pypi
     kiwisolver                1.1.0                    pypi_0    pypi
     krb5                      1.16.4               h2fd8d38_0    conda-forge
     lazy-object-proxy         1.4.3                    pypi_0    pypi
     ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcurl                   7.68.0               hda55be3_0    conda-forge
     libedit                   3.1.20170329      hf8c457e_1001    conda-forge
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             he1b5a44_1006    conda-forge
     libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
     libgomp                   9.2.0                h24d8f2e_2    conda-forge
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hed695b0_0    conda-forge
     libprotobuf               3.8.0                h8b12597_0    conda-forge
     librmm                    0.13.0a200220      cuda10.0_278    rapidsai-nightly
     libsodium                 1.0.17               h516909a_0    conda-forge
     libssh2                   1.8.2                h22169c7_2    conda-forge
     libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
     libtiff                   4.1.0                hfc65ed5_0    conda-forge
     libuv                     1.34.0               h516909a_0    conda-forge
     lightgbm                  2.3.0            py37he6710b0_0
     llvmlite                  0.31.0           py37h8b12597_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.8.3             he1b5a44_1001    conda-forge
     markdown                  3.0.1                    pypi_0    pypi
     markupsafe                1.1.1            py37h516909a_0    conda-forge
     matplotlib                3.1.3                    pypi_0    pypi
     mccabe                    0.6.1                      py_1    conda-forge
     missingno                 0.4.2                    pypi_0    pypi
     mistune                   0.8.4           py37h516909a_1000    conda-forge
     mkl                       2020.0                      166
     more-itertools            8.2.0                      py_0    conda-forge
     msgpack-python            1.0.0            py37hc9558a2_0    conda-forge
     multidict                 4.7.4                    pypi_0    pypi
     murmurhash                1.0.2                    pypi_0    pypi
     mypy_extensions           0.4.3                    py37_0    conda-forge
     nbconvert                 5.6.1                    py37_0    conda-forge
     nbformat                  5.0.4                      py_0    conda-forge
     nbsphinx                  0.5.1                      py_0    conda-forge
     nccl                      2.4.6.1              cuda10.0_0    nvidia
     ncurses                   6.1               hf484d3e_1002    conda-forge
     networkx                  2.4                      pypi_0    pypi
     ninja                     1.9.0            py37hfd86e86_0
     nodeenv                   1.3.5                      py_0    conda-forge
     nodejs                    10.13.0              he6710b0_0
     notebook                  6.0.3                    py37_0    conda-forge
     numba                     0.48.0           py37hb3f55d8_0    conda-forge
     numexpr                   2.7.1                    pypi_0    pypi
     numpy                     1.18.1           py37h95a1406_0    conda-forge
     numpydoc                  0.9.2                      py_0    conda-forge
     nvidia-ml-py3             7.352.0                  pypi_0    pypi
     nvstrings-cuda100         0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                       py_0    conda-forge
     openssl                   1.1.1d               h7b6447c_4
     packaging                 20.1                       py_0    conda-forge
     pandas                    0.25.3           py37hb3f55d8_0    conda-forge
     pandas-profiling          2.5.0                    pypi_0    pypi
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.6.1                      py_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.7.0                      py_0    conda-forge
     pexpect                   4.8.0                    py37_0    conda-forge
     phik                      0.9.9                    pypi_0    pypi
     pickleshare               0.7.5                 py37_1000    conda-forge
     pillow                    7.0.0            py37hefe7db6_0    conda-forge
     pip                       20.0.2                     py_2    conda-forge
     plac                      1.1.3                    pypi_0    pypi
     pluggy                    0.13.0                   py37_0    conda-forge
     pre_commit                1.18.1                   py37_0    conda-forge
     preshed                   3.0.2                    pypi_0    pypi
     prometheus_client         0.7.1                      py_0    conda-forge
     prompt_toolkit            3.0.3                      py_0    conda-forge
     protobuf                  3.11.3                   pypi_0    pypi
     psutil                    5.7.0            py37h516909a_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.8.1                      py_0    conda-forge
     pyarrow                   0.15.0           py37h8b68381_1    conda-forge
     pycodestyle               2.5.0                      py_0    conda-forge
     pycparser                 2.19                       py_2    conda-forge
     pyflakes                  2.1.1                      py_0    conda-forge
     pygments                  2.5.2                      py_0    conda-forge
     pylint                    2.4.4                    pypi_0    pypi
     pynvml                    8.0.4                    pypi_0    pypi
     pyopenssl                 19.1.0                   py37_0    conda-forge
     pyparsing                 2.4.6                      py_0    conda-forge
     pyrsistent                0.15.7           py37h516909a_0    conda-forge
     pysocks                   1.7.1                    py37_0    conda-forge
     pytest                    5.3.5                    py37_1    conda-forge
     pytest-cov                2.8.1                    pypi_0    pypi
     pytest-pylint             0.15.0                   pypi_0    pypi
     python                    3.7.6                h357f687_2    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python-slugify            4.0.0                    pypi_0    pypi
     pytorch                   1.5.0.dev20200219 py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch-nightly
     pytz                      2019.3                     py_0    conda-forge
     pyyaml                    5.3              py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37h1768529_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.01.01           he1b5a44_0    conda-forge
     readline                  8.0                  hf8c457e_0    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2020.2.18        py37h516909a_0    conda-forge
     requests                  2.22.0                   pypi_0    pypi
     rhash                     1.3.6             h14c3975_1001    conda-forge
     rmm                       0.13.0a200220          py37_278    rapidsai-nightly
     scikit-learn              0.22.1           py37h22eb022_0
     scipy                     1.4.1            py37habc2bb6_0
     seaborn                   0.10.0                   pypi_0    pypi
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                45.2.0                   py37_0    conda-forge
     simpervisor               0.3                      pypi_0    pypi
     six                       1.14.0                   py37_0    conda-forge
     snakeviz                  2.0.1                    py37_0
     snappy                    1.1.8                he1b5a44_1    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.1.0                      py_0    conda-forge
     soupsieve                 1.9.5                    pypi_0    pypi
     spacy                     2.2.3                    pypi_0    pypi
     sphinx                    2.4.2                      py_0    conda-forge
     sphinx-markdown-tables    0.0.12                   pypi_0    pypi
     sphinx_rtd_theme          0.4.3                      py_0    conda-forge
     sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
     sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
     sqlite                    3.30.1               hcee41ef_0    conda-forge
     srsly                     1.0.1                    pypi_0    pypi
     streamz                   0.5.2                    pypi_0    pypi
     tangled-up-in-unicode     0.0.3                    pypi_0    pypi
     tblib                     1.6.0                      py_0    conda-forge
     tensorboardx              2.0                      pypi_0    pypi
     terminado                 0.8.3                    py37_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     text-unidecode            1.3                      pypi_0    pypi
     thinc                     7.3.1                    pypi_0    pypi
     thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
     tk                        8.6.10               hed695b0_0    conda-forge
     toml                      0.10.0                     py_0    conda-forge
     toolz                     0.10.0                     py_0    conda-forge
     torchvision               0.5.0                    pypi_0    pypi
     tornado                   6.0.3            py37h516909a_4    conda-forge
     tqdm                      4.42.0                   pypi_0    pypi
     traitlets                 4.3.3                    py37_0    conda-forge
     typed-ast                 1.4.1            py37h516909a_0    conda-forge
     typing_extensions         3.7.4.1                  py37_0    conda-forge
     uriparser                 0.9.3                he1b5a44_1    conda-forge
     urllib3                   1.24.3                   pypi_0    pypi
     virtualenv                16.7.5                     py_0    conda-forge
     visions                   0.2.2                    pypi_0    pypi
     wasabi                    0.6.0                    pypi_0    pypi
     wcwidth                   0.1.8                      py_0    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.34.2                     py_1    conda-forge
     widgetsnbextension        3.5.1                    pypi_0    pypi
     wrapt                     1.11.2                   pypi_0    pypi
     xz                        5.2.4             h14c3975_1001    conda-forge
     yaml                      0.2.2                h516909a_1    conda-forge
     yarl                      1.4.2                    pypi_0    pypi
     zeromq                    4.3.2                he1b5a44_2    conda-forge
     zict                      1.0.0                    pypi_0    pypi
     zipp                      2.2.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1006    conda-forge
     zstd                      1.4.3                h3b9ef0a_0    conda-forge
     
</pre></details>

**Comment by kkraus14** [comment]
@jdye64 this feels like an uncaught Python exception in the Cython where we throw if there's "category" dtype

**Comment by jdye64** [comment]
I'm looking into this. Think I found the problem. Waiting on the build and will test and report back.

**Comment by jdye64** [comment]
![image](https://user-images.githubusercontent.com/2127235/74972824-6f225980-53f0-11ea-86c7-0a5c65d4b6e2.png)

With the fix above Python will now properly report that Categorical columns are not currently supported by the GPU accelerated parquet writer.

**Comment by OlivierNV** [comment]
Are categoricals now the new DICTIONARY32 type, or the legacy CATEGORY dtype ?

**Comment by kkraus14** [comment]
> Are categoricals now the new DICTIONARY32 type, or the legacy CATEGORY dtype ?

@OlivierNV They're currently neither, they're purely on the Python side and we manually handle the categories there and hand libcudf integer types. We'll move to the DICTIONARY32 type in the near future most likely.
