### ISSUE TITLE
[FEA] Speeding up cudf import time

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#4227]
**Is your feature request related to a problem? Please describe.**

It would be nice if we could speed up `cudf` import time.

```python
In [1]: %time import cudf                                                       
CPU times: user 2.51 s, sys: 6.2 s, total: 8.71 s
Wall time: 3.26 s
```

**Describe the solution you'd like**

(as stated)

**Describe alternatives you've considered**

Leave the import time as-is. cuDF is probably doing reasonable things here. Alternatively maybe something else cuDF is using is slow so we could speed it up.

**Additional context**

This comes up at the beginning of a user's program. So would be nice to make pretty fast to keep things responsive.

**Comment by kkraus14** [comment]
duplicate of #627

**Comment by jakirkham** [comment]
Oops 😬 Sorry Keith. Searched and somehow missed that one
