### ISSUE TITLE
DataFrame.quantile() should return a Dataframe but it prints and returns None 

### ISSUE THREAD

**Issue by chychen** [rapidsai/cudf#423]
https://github.com/rapidsai/cudf/blob/08860df5f72a15117a147adc00b95de806d4f8d2/python/cudf/dataframe/dataframe.py#L1678

The docstring of function mentioned that **quantile** will return **Dataframe** value, but it return **None** and print out the non necessary output.

**Comment by harrism** [comment]
He's right, see the linked line. Also, the docstring mentions a `columns` parameter that does not actually exist. This function needs attention. Assign to @kkraus14  to delegate.

**Comment by kkraus14** [comment]
Going to kick this over to @thomcom to fix when he gets some spare cycles.

**Comment by thomcom** [comment]
I addressed the listed issues, but I'm worried that the main functionality doesn't work. Did I use it incorrectly? See #644.

**Comment by thomcom** [comment]
Created a new issue for `.quantile()` on integer Series: #647. This is complete.

**Comment by kkraus14** [comment]
Fixed by #644.
