### ISSUE TITLE
[DOC] Clarify non-determinism

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4237]
## Report incorrect documentation

**Location of incorrect documentation**

In 0.12, common functions such as `drop_duplicates` and `merge` are unclear on whether they are order-preserving, and how. This is a gotcha for developers and a tough burden for non-developers (e.g., data scientists).

**Steps taken to verify documentation is incorrect**

Encountered when our tests failed during a 0.11->0.12 upgrade, and we were unsure if that was expected.

**Suggested fix for documentation**

1. Audit of most popular methods for order-preserving: filter, apply, merge, drop duplicates, groupby?

2. In most cases, 

* Explicitly document whether order preserving
* When possible, be order preserving
* Whenever not, provide a parameter to preserve/guide sort order, and print a warning if the option is not explicitly set

**Comment by GregoryKimball** [comment]
cuDF docs show that DataFrame [merge]https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.DataFrame.merge.html) in cuDF results in non-deterministic row ordering..
