### ISSUE TITLE
[BUG] Cudf io tests currently write to /tmp. 

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#4247]
This is apparently no good for the CI machines.   Suggestion is to change it to write to $WORKSPACE or $WORKSPACE/tmp

**Comment by devavret** [comment]
@karthikeyann, I suppose this is familiar territory for you?

**Comment by karthikeyann** [comment]
@nvdbaranec why no good?

**Comment by karthikeyann** [comment]
Following code should be able to change temporary directory to any location. (and still cleanup works).

```
class new_temp : public cudf::test::TempDirTestEnvironment {
  public:
  void SetUp() override {
    char tmp_format[] = "./gtest.XXXXXX";
    tmpdir = mkdtemp(tmp_format);
    tmpdir += "/";
  }
};

// Global environment for temporary files
auto const temp_env = static_cast<cudf::test::TempDirTestEnvironment*>(
    ::testing::AddGlobalTestEnvironment( new new_temp));
        //new cudf::test::TempDirTestEnvironment));
```

So, it is possible to configure it per test file.
specific cudf io tests can use this snippet.
