### ISSUE TITLE
[BUG] Series.isin() incorrect results 

### ISSUE THREAD

**Issue by dmitra79** [rapidsai/cudf#4249]
**Describe the bug**
Series.isin() seems to return incorrect results in some cases

**Steps/Code to reproduce bug**

`
 print(data_df[sensor_cols[1]].head())
 print(data_df[sensor_cols[1]].isin(range(0,10**6)).head())
 print(data_df[sensor_cols[1]].applymap(lambda x: x>=0 and x<=10**6).head())
`

Produces:

2017-09-21 12:14:33.566       null
2017-09-21 12:14:33.567    992.823
2017-09-21 12:14:33.583       null
2017-09-21 12:14:33.600       null
2017-09-21 12:14:33.617    993.105
Name: B992__ip_m, dtype: float64
0    False
1    False
2    False
3    False
4    False
Name: B992__ip_m, dtype: bool
2017-09-21 12:14:33.566    null
2017-09-21 12:14:33.567    True
2017-09-21 12:14:33.583    null
2017-09-21 12:14:33.600    null
2017-09-21 12:14:33.617    True
Name: B992__ip_m, dtype: bool

**Expected behavior**

The above result is clearly incorrect - expected result of isin(range(0,10**6)) to match what is obtained using applymap function.

On a different column, results match:
`print(data_df[sensor_cols[0]].head())
print(data_df[sensor_cols[0]].isin(range(0,10**6)).head())
print(data_df[sensor_cols[0]].applymap(lambda x: x>=0 and x<=10**6).head())`

2017-09-21 12:14:33.566        null
2017-09-21 12:14:33.567    541652.0
2017-09-21 12:14:33.583        null
2017-09-21 12:14:33.600        null
2017-09-21 12:14:33.617    541672.0
Name: B992__vp_m, dtype: float64
0    False
1     True
2    False
3    False
4     True
Name: B992__vp_m, dtype: bool
2017-09-21 12:14:33.566    null
2017-09-21 12:14:33.567    True
2017-09-21 12:14:33.583    null
2017-09-21 12:14:33.600    null
2017-09-21 12:14:33.617    True
Name: B992__vp_m, dtype: bool

**Environment overview (please complete the following information)**
I am on  Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)
cudf was installed with conda, version:

cudatoolkit               10.0.130                      0    nvidia
cudf                      0.10.0                   py37_0    rapidsai
cugraph                   0.10.0                   py37_0    rapidsai
cuml                      0.10.0          cuda10.0_py37_0    rapidsai
cuspatial                 0.10.0                   py37_0    rapidsai
dask                      2.8.0                      py_1    conda-forge
dask-core                 2.8.0                      py_0    conda-forge
dask-cuda                 0.10.0                   py37_0    rapidsai
dask-cudf                 0.10.0                   py37_0    rapidsai
dask-xgboost              0.2.0.dev28      cuda10.0py36_0    rapidsai

**Comment by kkraus14** [comment]
Looks like an issue of treating `range` as an array-like of integer values instead of a start / stop. Thanks for the bug report!

**Comment by galipremsagar** [comment]
I think both `isin` and `applymap` are functioning correctly. Here's why:

```python
>>> s = cudf.Series([None, 992.823, None, None, 993.105], nan_as_null=True)
>>> s
0       null
1    992.823
2       null
3       null
4    993.105
dtype: float64
>>> s.isin(range(0,10**6))
0    False
1    False
2    False
3    False
4    False
dtype: bool
>>> s.to_pandas().isin(range(0,10**6))
0    False
1    False
2    False
3    False
4    False
dtype: bool
```
In `isin` all we are essentially do is to check is if any of the values (`[0, 1, 2, 3, .......  999992, 999993, 999994, 999995, 999996, 999997, 999998, 999999]`) exists at any index in the series, if yes we return `True` at that index. Since the `values` you are passing are integers they obviously don't match with any of the floating values you have in the series, hence they return all as False which is correct.

```python
>>> s = cudf.Series([None, 992.823, None, None, 993.105], nan_as_null=True)
>>> s
0       null
1    992.823
2       null
3       null
4    993.105
dtype: float64
>>> s.applymap(lambda x: x>=0 and x<=10**6)
0    null
1    True
2    null
3    null
4    True
dtype: bool
>>> s.to_pandas().apply(lambda x: x>=0 and x<=10**6)
0    False
1     True
2    False
3    False
4     True
dtype: bool
```

In case of `applymap` we are checking for each value in the Series if they satisfy this condition : `x>=0 and x<=10**6`. Since 992.823 & 993.105 lie inbetween 0 and 10**6, they return `True`. 

To simplify, In your case for `isin` you are actually doing an equality check against integer values which will return `False`, incase of `applymap` you are doing a `0<= x <=10**6` condition check which will return `True`.

**Comment by dmitra79** [comment]
I see what you mean. 
The problem then is that there is no nice way to test for a range of values in a cudf. I've actually resorted to doing: 
'''
cudf.logical_and(data_df[current_col]>t1, data_df[current_col]<t2)
'''
 which is also not pretty, but faster than applymaps.
 Also, lack of documentation makes figuring these things out quite painful.

**Comment by galipremsagar** [comment]
You could as well do:
```python
>>> import cudf
>>> s = cudf.Series([1,2,3,4,5])
>>> (0<s) & (s<4)
0     True
1     True
2     True
3    False
4    False
dtype: bool
>>> s
0    1
1    2
2    3
3    4
4    5
dtype: int64
```

I have raised a doc request stating your case: #4723, hence closing this issue.
