### ISSUE TITLE
[BUG] Problem using lists with Series.applymap

### ISSUE THREAD

**Issue by dmitra79** [rapidsai/cudf#4250]
**Describe the bug**
When I try to use variables in applymap,  I get an error. Consider the following lines:

```
valid_status_list = [0, 40, 2052]
status_ok = data_df[status_col].isin(valid_status_list)
status_ok = data_df[status_col].applymap(lambda x: x in [0, 40, 2052])
status_ok = data_df[status_col].applymap(lambda x: x in valid_status_list)
```

The last line results in an error:

> TypingError: Failed in nopython mode pipeline (step: ensure IR is legal prior to lowering)
> The use of a reflected list(int64) type, assigned to variable 'valid_status_list' in globals, is not 
> supported as globals are considered compile-time constants and there is no known way to >compile a reflected list(int64) type as a constant.
>
> File "<ipython-input-104-092e90c9671a>", line 4:
> status_ok = data_df[status_col].applymap(lambda x: x in [0, 40, 2052])
> status_ok = data_df[status_col].applymap(lambda x: x in valid_status_list)

Using a set instead of a list lead to same error. 
Using a tuple actually worked, as long as it was done outside the call, ie.

'''
status_ok = data_df[status_col].applymap(lambda x: x in tuple(valid_status_list))
'''
still throws an error.

It seems that applymap can only work with constants. If this is the case, perhaps there can be a clear example in the documentation

**Environment overview (please complete the following information)**
I am on Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-45-generic x86_64)
cudf was installed with conda, version:

cudatoolkit 10.0.130 0 nvidia
cudf 0.10.0 py37_0 rapidsai
cugraph 0.10.0 py37_0 rapidsai
cuml 0.10.0 cuda10.0_py37_0 rapidsai
cuspatial 0.10.0 py37_0 rapidsai
dask 2.8.0 py_1 conda-forge
dask-core 2.8.0 py_0 conda-forge
dask-cuda 0.10.0 py37_0 rapidsai
dask-cudf 0.10.0 py37_0 rapidsai
dask-xgboost 0.2.0.dev28 cuda10.0py36_0 rapidsai

**Comment by rnyak** [comment]
@dmitra79 can you please add `data_df` to your example? without  `data_df[status_col]`, I cannot reproduce the issue.

**Comment by dmitra79** [comment]
That status column is just integer values and null values. Example:
``
data_df[status_col].head()
``
>2016-07-09 11:46:10.367       0
>2016-07-09 11:46:10.383    null
>2016-07-09 11:46:10.400       0
>2016-07-09 11:46:10.417    null
>2016-07-09 11:46:10.433    null
>Name: status, dtype: int32

Also, to avoid 'applymap' overwriting the column, the example lines should include 'copy':
``
valid_status_list = [0, 40, 2052]
status_ok = data_df[status_col].isin(valid_status_list)
status_ok = data_df[status_col].copy().applymap(lambda x: x in [0, 40, 2052])
status_ok = data_df[status_col].copy().applymap(lambda x: x in valid_status_list)
``

**Comment by galipremsagar** [comment]
> It seems that applymap can only work with constants. If this is the case, perhaps there can be a clear example in the documentation

This is correct. Numba doesn't have access to constants that are globally defined, instead we'd recommend you to use `lambda x: x in [0, 40, 2052]`. We have added more clear examples & notes as part of #4865
