### ISSUE TITLE
[BUG] nvstrings libcudf slice api doesn't support negative parameters/indexing

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#4255]
**Describe the bug**
Pandas string slice API supports negative values for `start`, `stop` & `step`:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.slice.html#pandas.Series.str.slice

**Steps/Code to reproduce bug**
This can be tested after this PR is merged : #4244
Python Behavior:

```python
>>> import pandas as pd
>>> s = pd.Series(["koala", "fox", "chameleon"])
>>> s.str.slice(start=-1)
0           a
1           x
2           n
dtype: object
```
cudf:

```python
>>> import cudf
>>> s = cudf.Series(["koala", "fox", "chameleon"])
>>> s.str.slice(start=-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/string.py", line 461, in slice
    cpp_slice_strings(self._parent, start, stop, step), **kwargs
  File "cudf/_libxx/strings/slice.pyx", line 32, in cudf._libxx.strings.slice.slice_strings
RuntimeError: cuDF failure at: /cudf/cpp/src/strings/substring.cu:105: Parameter start must be zero or positive integer.
```

**Expected behavior**
Ideal expectation is strings libcudf api's support negative values like pandas does.

**Environment overview (please complete the following information)**
 - Environment location:  Docker
 - Method of cuDF install:  from source

**Environment details**
 output of the `cudf/print_env.sh` script here: [env.txt](https://github.com/rapidsai/cudf/files/4252807/env.txt)

**Comment by kkraus14** [comment]
cc @shwina @jrhemstad how did we handle this for gather?

**Comment by davidwendt** [comment]
The libcudf gather code includes a special index iterator for handling negative row indices.
This is not row slicing but rather _string slicing_ which is character position based within each string.

The original nvstrings code did not support negative indexes for this function so this will require some new code logic.
https://rapidsai.github.io/projects/nvstrings/en/0.12.0/api.html#nvstrings.nvstrings.slice
```
>>> import nvstrings
>>> s = nvstrings.to_device(["hello","goodbye"])
>>> print(s.slice(2,5))
['llo', 'odb']
```
For reference, here is the Pandas equivalent which includes negative position value examples
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.slice.html

**Comment by kkraus14** [comment]
@davidwendt yes I understand this is string slicing as opposed to row based indices, but I was wondering if the solution to handling negatives there could be generalized in some way for here. Seems like it may not be able to.

**Comment by shwina** [comment]
It should be possible to convert negative slice indexes to the appropriate positive values via `slice.indices(length)`, unless I'm missing something.

**Comment by davidwendt** [comment]
@shwina I'm not sure what `slice.indices(length)` means. There is no vector of position/indices values here just a single parameter. And each individual string can be a different length.
```
s = cudf.Series(["koala", "fox", "chameleon"])
s.str.slice(start=-1)
0           a
1           x
2           n
```
So the start position would technically be different for each string/row.
This should not be difficult but I don't think the index iterator in gather will help here.

**Comment by shwina** [comment]
Gotcha - I misunderstood completely :-)
