### ISSUE TITLE
[BUG] using apply_row() on cudf

### ISSUE THREAD

**Issue by raviy0807** [rapidsai/cudf#4257]
**Describe the bug**

I have cudf dataframe that has float64 values in all columns.

Idea is to add a column based on the existing column. Based on the float value of a column the new column should store string value.

BUG:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f355c079f90>) with argument(s) of type(s): 
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(int64, 1d, A), int64, Literal[str](ds))

This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f355c079f90>)
[2] During: typing of call at <string> (8)


File "<string>", line 8:
<source missing, REPL/exec in use?>
```
**Steps/Code to reproduce bug**
```
data = {'Name':['rk','pm','ty'], 'Age':[20, 21, 19]} 
df = cudf.DataFrame(data)

def compute_result(Name, Age, Result, m):
    for i, (x, y) in enumerate(zip(Name, Age)):
        ans = foo(x,y) # foo function returns value in string 
        Result[i] = ans # also tried converting ans in integer and use, but same error


df.apply_rows(compute_result,
             incols=['Name','Age'],
             outcols=dict(Result=np.int64),
             kwargs=dict(m=10))

```
**Expected behavior**
It should add 'Result' column

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install: [conda]
   - Stable version

**Comment by jrhemstad** [comment]
I believe this issue is a result of the fact that Numba does not support String operations in device code. If you can frame your algorithm in a way that avoids needing strings you should be set.

**Comment by raviy0807** [comment]
@jrhemstad , is there any work around to add columns in cudf dataframe that i can execute parallely.

Main focus is on getting string value what is generated from a library's function.
Perform this operation in each row

**Comment by kkraus14** [comment]
@raviy0807 it looks like your UDF is trying to use the dictionary as a lookup table to convert a float --> string. In this case You could try using `DataFrame.replace(...)` with a dictionary or create a DataFrame from your dictionary (`lookup_df = cudf.DataFrame(my_dict)`) and then run a join to do the lookups: `df.merge(lookup_df)`

**Comment by raviy0807** [comment]
@kkraus14 ,

Could you explain by modifying this example?
```
from xyz import foo

data = {'salary':[112,334,556], 'Age':[20, 21, 19]} 
df = cudf.DataFrame(data)

def compute_result(salary, Age, Result, m):
    for i, (x, y) in enumerate(zip(salary, Age)):
        Result[i]= foo(x,y) # foo function takes value in int and returns value in string 

df.apply_rows( compute_result,
             incols=['salary','Age'],
             outcols=dict(Result=np.int64),
             kwargs=dict(m=10) )
```

**Comment by kkraus14** [comment]
```
lookup_data = {'int':[1, 2, 3], 'str':['a', 'b', 'c']} 
lookup_df = cudf.DataFrame(lookup_data)

my_df = cudf.DataFrame({'int': [2, 3, 1, 3, 2, 1], 'other_col': [1.0, 2.0, 3.0, 4.0, 5.0, 6.0]})
result_df = my_df.merge(lookup_df, on=['int'])
result_df = result_df[['str', 'other_col']]

# If you want to rename the `str` column
result_df = result_df.rename({'str': 'new_name'}, copy=False)
```

**Comment by raviy0807** [comment]
@kkraus14 

```
lookup_data = {'int': [1, 2, 3], 'str': ['a', 'b', 'c']} 
lookup_df = cudf.DataFrame(lookup_data)
```

lookup_data should be produced by library function that generates the 'str' column.

Lets say we have 2 columns : 'age' and 'tax' . we provide this to a library function which returns the alphanumb value in string. 

So, i want to add this new value to column in cudf. Basically, generating new column based on the value of existing columns with the help of a library function that returns string.

Please let me know, if use-case is not clear.

**Comment by raviy0807** [comment]
As, @jrhemstad  said, that it is not possible. What will be most efficient way of doing it if that size of dataframe is in many millions rows. I tried with pandas and dask, but it take lots of time.

I would like to perform this task in 'Rapids' ecosystem.

**Comment by kkraus14** [comment]
@raviy0807 You would need to reimplement the library function as a function that you can pass to `apply_rows`. This would mean either unrolling the function into your `compute_result` function, or defining a new `foo` function that's a numba cuda device function (https://numba.pydata.org/numba-doc/dev/cuda/device-functions.html) and using that within your `compute_result` function.

**Comment by beckernick** [comment]
This might also be a great question for Stackoverflow and the `cudf` or `rapids` tag, if you're interested in creating a minimal example that shows:

- A small amount of input data that is representative of your real data
- Your current code, with explicitly defined functions
- The desired output data after processing

**Comment by beckernick** [comment]
This might also be a great question for Stackoverflow and the `cudf` or `rapids` tag, if you're interested in creating a minimal example that shows:

- A small amount of input data that is representative of your real data
- Your current code, with explicitly defined functions
- The desired output data after processing

**Comment by raviy0807** [comment]
```
from geohash import encode

location_df = cudf.DataFrame( {
'latitude':[23.23,12.43,67.44],
'longitude':[45.234,34.12,44.23]
})

def compute_result(salary, Age, geohash, m):
    for i, (x, y) in enumerate(zip(salary, Age)):
        geohash[i]= encode(x,y) # function takes value in float and returns value in string 

location_df .apply_rows( compute_result,
             incols=['latitude','longitude'],
             outcols=dict(geohash=str),
             kwargs=dict(m=10) 
)
```


Output:
```
latitude | longitude | geohash
-- | -- | --
23.23 | 45.234 | gfr241
12.43 | 34.120 | gkr231
67.44 | 44.230 | gfb231

```


@beckernick and @kkraus14  , this is the task which i am trying to do. I may not be always reimplement the library functions.

It would be great to see any way how we can use the gpu for creating new column based on library function. What will be best way to do it?

**Comment by kkraus14** [comment]
@raviy0807 Unfortunately we can't just take an arbitrary library and accelerate it with the GPU. In your case above there isn't an easy workaround currently as we don't yet support range based or inequality joins.

In the future, you could possibly get the geoencoding table and create a cuDF DataFrame from it, then to get the `geohash` you would do a join based on the latitude and longitude. I believe there's also talk about doing spatial joins in https://github.com/rapidsai/cuspatial in the future as well.

**Comment by kkraus14** [comment]
Closing as this is answered.
