### ISSUE TITLE
[BUG] Using df.loc[idx] returns rows out of order.

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#4265]
**Describe the bug**
Sometimes when you use loc to select specific rows (i.e. df.loc[idx]), the rows are returned out of order with relation to the ordering of idx.

**Steps/Code to reproduce bug**
df = cudf.DataFrame()
df['a'] = np.array([2987000., 2987001., 2987002., 2987003., 2987004., 2987005.,
       2987006., 2987007., 2987008., 2987009., 2987010., 2987011.,
       2987012., 2987013., 2987014., 2987015., 2987016., 2987017.,
       2987018., 2987019., 2987020., 2987021., 2987022., 2987023.,
       2987024., 2987025., 2987026., 2987027., 2987028., 2987029.,
       2987030., 2987031., 2987032., 2987033., 2987034., 2987035.,
       2987036., 2987037., 2987038., 2987039., 2987040., 2987041.,
       2987042., 2987043., 2987044., 2987045., 2987046., 2987047.,
       2987048., 2987049., 2987050., 2987051., 2987052., 2987053.,
       2987054., 2987055., 2987056., 2987057., 2987058., 2987059.,
       2987060., 2987061., 2987062., 2987063., 2987064., 2987065.,
       2987066., 2987067., 2987068., 2987069., 2987070., 2987071.,
       2987072., 2987073., 2987074., 2987075., 2987076., 2987077.,
       2987078., 2987079., 2987080., 2987081., 2987082., 2987083.,
       2987084., 2987085., 2987086., 2987087., 2987088., 2987089.,
       2987090., 2987091., 2987092., 2987093., 2987094., 2987095.,
       2987096., 2987097., 2987098., 2987099.], dtype='float32')
df['b'] = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype='int8')
df = df.set_index('a')
split = 3*len(df)//4
idxA = df.index[:split]
idxB = df.index[split:]
print( df.loc[idxA] )

**Expected behavior**
The first row printed should be row with index 2987000. but it is not. In the Jupyter notebook here:
https://github.com/cdeotte/RAPIDS-development/blob/master/bugs/bug002.ipynb
we see that the first row printed has index 2987064.0

**Environment overview (please complete the following information)**
The stable 0.12.0 install of RAPIDS

**Comment by rgsl888prabhu** [comment]
This issue already been resolved with a less efficient option, waiting on feature request #4574 for better solution.

**Comment by kkraus14** [comment]
Resolved by #4570
