### ISSUE TITLE
[BUG] dask-cudf column renaming 

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#4296]
**Describe the bug**

I would like to do column renaming for a dask-cudf. The following code does not do column renaming in-place.

**Steps/Code to reproduce bug**
The original dask-cudf  and its columns:

```
dff = dask_cudf.read_csv('test.csv')
dff.head(5).to_pandas()
 VendorID  trip_distance	  RateCodeID	      fare_amount
0	2	          1.59	            1	                 12.0
1	1	          3.30	            1	                 14.5
2	1	          1.80	            1	                  9.5
3	1	          0.50	            1	                  3.5
4	1	          3.00	            1	                 15.0
```

The code for column renaming:
```
# some col-names include pre-pended spaces remove & lowercase column names
tmp = {col:col.strip().lower() for col in list(dff.columns)}
print(tmp)
dff.rename(columns=tmp)

dff.columns
Index(['VendorID', 'trip_distance', 'RateCodeID', 'fare_amount'], dtype='object')
```

**Expected behavior**
```
dff.columns
Index(['vendorid', 'trip_distance', 'ratecodeid', 'fare_amount'], dtype='object')
```
One work around could be the following:

```
# some col-names include pre-pended spaces remove & lowercase column names
tmp = {col:col.strip().lower() for col in list(dff.columns)}
print(tmp)
dff=dff.rename(columns=tmp)
```
But not sure that's the right way to do.

**Environment overview (please complete the following information)**
 - Environment location: [ Docker 0.13 relase]
 - Method of cuDF install: [Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
[test.txt](https://github.com/rapidsai/cudf/files/4277624/test.txt)

**Additional context**
the test.txt file is attached to reproduce the issue.

**Comment by kkraus14** [comment]
Work around is the correct way, closing.
