### ISSUE TITLE
[FEA] Remove legacy C++ and Cython files to reduce build times

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/cudf#4300]
Now that the libcudf++ and Cython porting efforts are drawing to a close, we should start removing the legacy C++/Cython `gdf_column` and related APIs. This will greatly reduce build times, lower CI loads, and eliminate the linker errors we're currently seeing in C++ debug builds.

**Comment by jrhemstad** [comment]
Beat you to the punch :) https://github.com/rapidsai/cudf/issues/4050
