### ISSUE TITLE
[FEA] Add NVTX ranges to most libcudf APIs

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4312]
**Is your feature request related to a problem? Please describe.**

It would be nice when profiling with Nsight Systems to automatically see when a libcudf function is called and how long it takes. This is a perfect use case for NVTX ranges. 

https://github.com/rapidsai/cudf/pull/4304 adds new infrastructure to make it very easy to add ranges to functions. The simplest method is to use the `CUDF_FUNC_RANGE` macro which automatically constructs an `nvtx::domain_thread_range` in the `libcudf` domain using the name of the enclosing function as the message of the range. E.g.,
```
void some_function(){
   // Range begins on entry to `some_function` and ends when the function returns
   // Gets the name of the enclosing function via __func__
   CUDF_FUNC_RANGE(); 
}
```

**Describe the solution you'd like**

Add `CUDF_FUNC_RANGE()` to most/all libcudf top-level compute APIs. 

Since most libcudf top-level libcudf APIs immediately call a detail function, the perfect place to put `CUDF_FUNC_RANGE()` is immediately before the call to the `detail` API. See https://github.com/rapidsai/cudf/pull/4304/files#diff-f5207068230a0e7c9c37ea39c3acee39R113

**Comment by millerhooks** [comment]
I can get this. I'm just wrapping up the new `NVTX` stuff with #4235 and replaced the instances of the usage of old `NVTX`.

**Comment by jrhemstad** [comment]
This is actually already closed by https://github.com/rapidsai/cudf/pull/4304
