### ISSUE TITLE
[DOC] Improve internal documentation of cuIO compression / decompression kernels

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#4320]
## Report needed documentation

To facilitate knowledge transfer, maintenance and possible future factoring-out of compression and decompression from libcudf/cuIO, we should improve the documentation of the algorithms and kernels used for compression and decompression in cuIO.

For example, this kernel function is 250 lines of code with little explanation of what it does or how it works. https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/src/io/parquet/page_enc.cu#L863-L1115

There are several kernels like this in cuIO. Long functions like this could also be broken into shorter functions with clear names.

**Comment by nsakharnykh** [comment]
I found some time to look into https://github.com/rapidsai/cudf/pull/4903 today. I noticed it's already merged? Anyways, I think I'd like more documentation for the main function in debrotli https://github.com/rapidsai/cudf/blob/99a6c347a9ab25ee079a821d6662301fd0fa191f/cpp/src/io/comp/debrotli.cu#L1989 - it's lacking any documentation regarding the high-level flow (what warps/blocks are assigned to), and no comments in the function body. Are we planning to add more for this one? Same for the main inflate kernel https://github.com/rapidsai/cudf/blob/99a6c347a9ab25ee079a821d6662301fd0fa191f/cpp/src/io/comp/gpuinflate.cu#L1169
