### ISSUE TITLE
[FEA] Remove `cudf::transpose`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4322]
**Is your feature request related to a problem? Please describe.**

`cudf::transpose` is inherently slow because of having to allocate a potentially large number of output columns. In reality, transpose only makes sense when all of the input columns are the same type and the output should just be a 2D NDarray in Python. 

**Describe the solution you'd like**
Remove `cudf::transpose` as Python has other alternatives. Unless Spark or Blazing needs it.

**Comment by kkraus14** [comment]
From the Python side we already have fast paths to go from DataFrame --> CuPy column major array, which we can then run a transpose which likely just calls into cuBLAS. This returns us a row major NDArray which is likely what we'd want anyway.

**Comment by jrhemstad** [comment]
@jlowe @felipeblazing do you guys need/use this API? It's very slow and there isn't much we can do about it.

**Comment by jlowe** [comment]
The Spark plugin is not currently using it, nor am I aware of plans to do so.  cc: @revans2

**Comment by jrhemstad** [comment]
Closing. https://github.com/rapidsai/cudf/pull/4802 has shown with the libcudf++ lifetime semantics, we are able to return a single allocation for all transposed columns which dramatically improves performance.
