### ISSUE TITLE
[FEA] Add NVTX ranges for strings/text/dictionary APIs

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4323]
**Is your feature request related to a problem? Please describe.**

Same as https://github.com/rapidsai/cudf/issues/4312 but for the strings/dictionary/text APIs that I didn't get.

**Comment by millerhooks** [comment]
#4235 

Can do.

**Comment by jrhemstad** [comment]
@davidwendt is this done? Are NVText and Dictionary APIs annotated?

**Comment by davidwendt** [comment]
Somehow I missed the dictionary ones. I will push a PR tomorrow.
