### ISSUE TITLE
[FEA] Remove old NVTX functionality

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4326]
**Is your feature request related to a problem? Please describe.**

Once https://github.com/rapidsai/cudf/issues/4312 is merged, the old NVTX functionality should be removed. Specifically, the contents of https://github.com/rapidsai/cudf/tree/branch-0.13/cpp/src/utilities/nvtx

Users that depended on this functionality are free to either use the new stuff added in https://github.com/rapidsai/cudf/issues/4312 or make native language NVTX bindings (recommended).

**Comment by millerhooks** [comment]
I got this. #4235

**Comment by jrhemstad** [comment]
@millerhooks, to be clear, I'm referring to removing all of the code here: https://github.com/rapidsai/cudf/tree/branch-0.13/cpp/src/utilities/nvtx

**Comment by harrism** [comment]
@jrhemstad should this have been closed?

**Comment by jrhemstad** [comment]
We definitely still want to remove the old NVTX C++ stuff. Whether that's in this PR or part of removing legacy doesn't really matter.

**Comment by harrism** [comment]
There is no PR, but I think legacy will handle it (since it is in a legacy folder). Reopening.

**Comment by jrhemstad** [comment]
fyi, this is still here and should be removed: https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/include/cudf/utilities/nvtx_utils.hpp
