### ISSUE TITLE
[BUG] Change make_scalar_iterator() and make_pair_iterator(scalar) to return iterators that don't memcpy the values up to the host.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#4330]
Currently, make_scalar_iterator returns a thrust constant iterator, but to do this it retrieves the scalar value off the device by hand with a cudaMemcpy() (via scalar::value()).   Similarly, make_pair_iterator(scalar) does the same for both the the value and validity.

It would make a lot more sense to have an iterator that just keeps the pointer to the value and dereferences as needed on the gpu.   Possibly with an optimization to cache the value on the first read to potentially get some memory locality wins.

**Comment by nvdbaranec** [comment]
@trevorsm7  Has a clean solution for this which could be slotted in here pretty easily.

https://github.com/rapidsai/cudf/blob/60daf4b8c112d9b6a6d0d7dd4701881f76b406c4/cpp/src/copying/scatter.cu#L129-L132

**Comment by karthikeyann** [comment]
@nvdbaranec still `make_scalar_iterator()` will makes memcpy to host for checking validity. is that fine?

**Comment by nvdbaranec** [comment]
This is_valid() check?  Without overhauling scalar entirely I don't think there's any other way to do it besides removing that check entirely.   So leaving it as is is ok I guess.  @jrhemstad ?

**Comment by jrhemstad** [comment]
The `is_valid` check should really be solved by memoizing the contents of the validity in host memory as well. I don't think that's a task to solve in the `make_scalar_iterator`.
