### ISSUE TITLE
[FEA] Include cpp test utility code in build products

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#4332]
**Is your feature request related to a problem? Please describe.**
I'm writing `cuspatial` C++ code, which depends on cudf. There are many great cudf test utilities and fixtures in `cpp/tests/utilities/` that I can't utilize since they aren't shipped with the build.

**Describe the solution you'd like**
Please add a directory such as `include/testing` that contains headers for the test utilities, and the utility source to be built into `libcudf.so`

**Describe alternatives you've considered**
I could add additional include and build path dependencies to `cuspatial`s CMakeLists.txt. This seems unoptimal since we'd like for any downstream user of `libcudf.so` to be able to take advantage of our testing frameworks.

**Comment by jrhemstad** [comment]
I'm fine with making these externally available, but I'm unsure about putting it in `libcudf.so` and inflating the size of the library. If anything, it should probably be header only or a separate DLL.

**Comment by thomcom** [comment]
`libcudf` and `libcudf-dev` :)

**Comment by jrhemstad** [comment]
The other thing that makes me uncomfortable about this is that by making it publicly consumable, it creates an implicit assumption of stability of testing utility APIs. The testing utilities are basically like stuff in a `detail` namespace. It's liable to change completely at a moment's notice without warning.

**Comment by thomcom** [comment]
I think there's less expectation of API stability in a `-dev` package. It has seemed to me like we are starting to need one -like with the work in `cuspatial`, many who are actively using `libcudf` might want access to things like the `detail` namespace.

**Comment by jrhemstad** [comment]
> many who are actively using libcudf might want access to things like the detail namespace.

That's explicitly what the `detail` namespace should _not_ be used for :)

**Comment by jrhemstad** [comment]
But to your point, @williamBlazing opened pretty much the same issue in the past: https://github.com/rapidsai/cudf/issues/3872

**Comment by jrhemstad** [comment]
Also `-dev` packages don't mean they include `detail` or internal interfaces. `-dev` just means instead of shipping only the `.so`, it also ships the headers so you can actually compile against it. At least that's the standard in Linux packages.

**Comment by harrism** [comment]
The test utilities are not compiled into libcudf.so. They are compiled into cudftestutil, a static library. See `cpp/tests/CMakeLists.txt`.

**Comment by jrhemstad** [comment]
> And a lot of it is in namespace cudf::test, not detail at all.

Like I said, `cudf::test` is _like_ being in detail. It shouldn't be relied on by public users to not change dramatically at any point without warning.

**Comment by harrism** [comment]
Hmmm, that sounds like an opinion that could be swayed. There is a demonstrated need here.

**Comment by harrism** [comment]
So while @thomcom is a public user, cuSpatial is a part of RAPIDS.  So I think it's OK. And cudftestutil doesn't increase the  size of libcudf.so (your other concern). So I think it's OK to go  ahead with this... I'm just not sure when we'll have time.

**Comment by jrhemstad** [comment]
> So while @thomcom is a public user, cuSpatial is a part of RAPIDS.

Yeah, but then when we break or change a test utility, it will break cuSpatial. Likewise, if Blazing starts using them, it will break them as well. 

Exposing our testing utilities puts us on the hook for maintaining that code, increasing the surface area of the library by quite a bit. In contrast, if other people depend on that code, then we can't just change it on a whim.

**Comment by harrism** [comment]
I think that's the price of doing business with data structures that we want other RAPIDS libraries to use.  We want them to use cudf::column and cudf::table. We don't want them to write ugly tests and reinvent the test utility wheel.

**Comment by jrhemstad** [comment]
closed by https://github.com/rapidsai/cudf/pull/6201
