### ISSUE TITLE
[FEA] Remove all unneeded usage of nvstrings and nvcategory from cuDF codebase

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#4334]
Currently nvstrings is used throughout the cuDF Python codebase and we should move those usages to just use columns directly to prevent unnecessary expensive conversions.

**Comment by harrism** [comment]
Why is this moved back into 0.13?

**Comment by kkraus14** [comment]
> Why is this moved back into 0.13?

Because the work is basically already done where @galipremsagar is just doing a final pass for any stragglers before we close this.
