### ISSUE TITLE
[DOC] Aggregation support matrix

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#4341]
Unified aggregations are supported at column level, in rolling windows, and in groupby. But not all functionalities support all aggregations. We need to document the subset of aggregations that each functionality supports.

**Comment by harrism** [comment]
Let's roll this into #6977

**Comment by harrism** [comment]
On second thought, maybe this is more of a user docs thing than a developer docs thing...

**Comment by codereport** [comment]
I have started on this here: https://gist.github.com/codereport/b747c8cad4026fa1defc422411afbcbc

Will finish and rolling into docs or developer guide.

**Comment by harrism** [comment]
Could add it as a doxygen page in the aggregations section...

**Comment by harrism** [comment]
@codereport you still planning this?

**Comment by codereport** [comment]
mmm, yes. This definitely should still get done.

**Comment by GregoryKimball** [comment]
Now this is fairly well documented in [aggegations.hpp](https://github.com/rapidsai/cudf/blob/f6e9666412715927798baaff41996dbaac20dc43/cpp/include/cudf/aggregation.hpp).
