### ISSUE TITLE
[DOC] replace np.arange with cupy.arange in tutorials

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4350]
## Report incorrect documentation

**Location of incorrect documentation**

In '10 Minutes to cuDF', all uses of `arange` are via `np.arange` instead of `cupy.range`

**Describe the problems or issues found in the documentation**

This suggests there is not yet a rapids-friendly way to do `araange`. See: https://github.com/rapidsai/cudf/issues/4325 

**Suggested fix for documentation**

* Update the primary examples to `cudf.Series(cupy.arange(...))` (or equiv)
* That's janky, so even better would be `cudf.arange` / `cudf.Series.arange`.

**Comment by lmeyerov** [comment]
Looking further, I saw elsewhere in our code we have `from cudf.utils.cudautils import arange` ... but that doesn't show up in the docs.

**Comment by kkraus14** [comment]
> Looking further, I saw elsewhere in our code we have `from cudf.utils.cudautils import arange` ... but that doesn't show up in the docs.

That's an internal numba function that accomplishes similar but has more non-trivial jit compilation time and is more limited in functionality. Actually working on ripping it out right now 😄.

**Comment by lmeyerov** [comment]
Thanks! For those following along:

```
import cudf
import cupy as cp
from cudf.utils.cudautils import arange
```

1. Raw calls:

(highly variable)
```
>>> t0 = time.time(); car = arange(1000); time.time() - t0
0.0020761489868164062
```
vs
```
>>> t0 = time.time(); scp = cp.arange(0, 1000); time.time() - t0
0.0003485679626464844
```

2. cudf-wrapped:

```
>>> t0 = time.time(); scp = cudf.Series(arange(0, 1000)); time.time() - t0
0.0034999847412109375
```
vs
```
>>> t0 = time.time(); scp = cudf.Series(cp.arange(0, 1000)); time.time() - t0
0.0007555484771728516
```
