### ISSUE TITLE
[FEA] strings libcudf zfill api needs to align with pandas behavior for specific case

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#4355]
**Describe the bug**
Our `zfill` api seems to be adding `0`s differently when there is a sign. Maybe we are performing special handling to do so. But from pandas doc: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.zfill.html , it seems like `+100`/`-90` are treated as characters and hence they pad it with 0's before the sign(`+/-`). The difference can be seen in the example below.

**Steps/Code to reproduce bug**

```python
>>> import cudf
>>> s = cudf.Series(["hello", "there", "world", "+1234", "-1234", None, "accént", ""])
>>> s.str.zfill(19)
0    00000000000000hello
1    00000000000000there
2    00000000000000world
3    +000000000000001234
4    -000000000000001234
5                   None
6    0000000000000accént
7    0000000000000000000
dtype: object
>>> s.to_pandas().str.zfill(19)
0    00000000000000hello
1    00000000000000there
2    00000000000000world
3    00000000000000+1234
4    00000000000000-1234
5                   None
6    0000000000000accént
7    0000000000000000000
dtype: object

```
**Expected behavior**
We should be aligning with pandas behavior as they seem to treat `-`/`+` as a regular char.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source

**Environment details**
Output of the `cudf/print_env.sh` script here: [env.txt](https://github.com/rapidsai/cudf/files/4298969/env.txt)

**Additional context**
This can be tested using PR: #4311

**Comment by davidwendt** [comment]
Argh. Looks like Pandas changed. Old spec:
https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.Series.str.zfill.html#pandas.Series.str.zfill
This certainly looks easier to code.
Is there any significance to the red highlights in the description?

**Comment by galipremsagar** [comment]
> Is there any significance to the red highlights in the description?

No, seems like github is doing weird red highlighting for 0's if I select python code block.

**Comment by davidwendt** [comment]
Maybe just a sanity check but how is `zfill(width)` different from than just `pad(width,'left','0')`?

**Comment by galipremsagar** [comment]
They both are identical. `pad(width,'left','0')` == zfill(width)

Infact pandas listed it in their docs too: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.pad.html#pandas.Series.str.pad

**Comment by davidwendt** [comment]
Should I just remove libcudf `zfill()` and python/cython just call `pad()` then?

**Comment by galipremsagar** [comment]
We can absolutely do that, I was wondering why we had two API's. But then thought `zfill` would have some optimized logic to do it. If you feel both calls are same you can remove zfill and I'll be able to use just `pad`

**Comment by davidwendt** [comment]
Ok. You are right, it is a little more optimized. I will keep it in and add some comments.
