### ISSUE TITLE
[FEA] schema.metadata get/set without CPU round trip

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4370]
**Is your feature request related to a problem? Please describe.**

Arrow has `arrow.schema.metadata` set & get, but when using with `cudf`, getting or extending the metadata requires a CPU round trip:

```
arr = gdf.to_arrow()
arr2 = arr.replace_schema_metadata( f(arr.schema.metadata) )
gdf2 = cudf.DataFrame.from_arrow(arr2)
```

Big data file formats provide portable schema metadata so application-specific summary logic can be attached, so support this in a non-prohibitive way would help!

**Describe the solution you'd like**

Getter/setter methods `get_schema_metadata` and `replace_schema_metadata` that conform to Arrow's portable `Table::replace_schema_metadata(dict<str,str>)` and `Schema::metadata() :: dict<str,str>`.

Arrow-mirroring:
```
metadata2 = f(gdf.get_schema_metadata())
gdf2 = gdf.replace_schema_metadata_with(metadata2)
```

Or something more consistent like `DataFrame::get::metadata` and `DataFrame::assign/replace_metadata(dict<str,str>))`:

```
metadata2 = f(gdf.metadata)
gdf2 = gdf.assign_metadata(metadata2)
```

**Describe alternatives you've considered**

* CPU round trip <- slow workaround
* Manually wrapping df's <- global code rewrite to wrap all df's :( We actually currently have this and are systematically removing
* Explicit cudf.DataFrame::schema attribute support <- Long-term solution, but easier to start with just get/set metadata and not tackle the surrounding schema baggage until more understood

Less obvious to me is if/when to expose the data to GPU kernels. In our case, we do not need to notify the GPU kernels, so can skip the write, but I can imagine kernels wanting that as part of their kernel args.

**Comment by kkraus14** [comment]
@lmeyerov This is out of scope for cuDF as of now and we have no plans to mirror the Arrow APIs moving forward. We consume / produce the schema metadata so we can roundtrip index columns and the like without issue, but we have no intention of managing user defined metadata ourselves.

**Comment by lmeyerov** [comment]
Got it - @kkraus14 should I file a feature issue for user-provided metadata as part of getting cudf useful for more than individual data scientists?

**Comment by lmeyerov** [comment]
Ah realized that it is this one :)

Before you close, I should explain the use case a bit more in this case:

Scenario: An application is using cudf as the primary data type for passing data between code and say serialization/deserialization (parquet, ...). As soon as code gets to any interesting size, it is likely that application-specific annotations beyond just dtypes will be useful for intepretation at the table and column level. ("IP", "InternalIP", "Dirty", "Prefiltered", "Provenance", ...). 

I expect this not to happen to individual data scientists writing tiny individual code, but to start happening as they work in teams, and especially if software is to build on top of cudf.

Today:
* Parquet, Arrow, Pandas, Spark, etc. allow adding ~json at the table or column level, but cudf does not (officially)
* Software writers should not pass around cudf objects, and instead manually pass around `(cudf, schema)` pairs, or more finnicky, subclass `MyFinnickyClass(cudf.DataFrame)`, and during I/O points, manually shuffle the schema around
* This is a far-reaching global rewrite if they started writing their app without it, or want to switch from one to another. As such, production use of cudf requires subtle prescience or painful refactorings. 

Request:
* A user-defined schema slot. Ex: Table-level. Ex: Column level
* Make it serializable. Ex: JSON. Ex: Arrow's byte dictionary.

**Comment by kkraus14** [comment]
> Got it - @kkraus14 should I file a feature issue for user-provided metadata as part of getting cudf useful for more than individual data scientists?

If this is a critical feature for your use case I would suggest that you open a pull request and contribute it. This is just not a priority for us or on our roadmap at this time. I'm happy to leave this issue open as a standing feature request.

**Comment by lmeyerov** [comment]
Thanks! Not too big of an issue vs say broken sorting or high overheads ;-) I was filing b/c it seems lightweight yet important to not miss.

The report comes form us starting with the fragile class extension approach, and because that being fragile for ~obvious reasons, been rewriting to pass around a tagged pair. (Global metadata store has its own issues of a central service or tricky GC.) So we've been leaving with this gap for over a year and can keep trucking. It just popped up again as we're working through some bugs due to manual metadata management here, so I thought it'd be an important design point to put in here.

**Comment by GregoryKimball** [comment]
Closing for now, please comment if table/column tagging is important to you.

**Comment by lmeyerov** [comment]
it's still of interest, we pay repeat hits on wrangling flows: data ingest, potentially during etl pipeline, and then again on the way out
