### ISSUE TITLE
[BUG] Append CUDF dataframe to join all files

### ISSUE THREAD

**Issue by raviy0807** [rapidsai/cudf#4372]
**Describe the bug**
Program crash while combining all dataframes.

**Steps/Code to reproduce bug**
main_df = cudf.DataFrame()
for file in file_list:
     df = cudf.io.parquet.read_parquet(file)
     main_df = cudf.concat([main_df,df])

**Expected behavior**
A single dataframe of 20GB.

**Environment overview (please complete the following information)**
Stable CUDF in docker 

What would be best approach to combine all parquet file in a folder? 
I tried to use panda's 'append' function and it works. But with cudf, the program crahes.

**Comment by kkraus14** [comment]
@raviy0807 Do you have a stacktrace from your crash? In general if your final DataFrame is 20GB, then to run the concat you're also going to need 20GB which is likely larger than your GPU memory.

Could you try using `dask-cudf` or try using `cudf.set_allocator(allocator="managed")`

**Comment by kkraus14** [comment]
Closing as no response. Feel free to reopen if you have a stacktrace / reproducer.
