### ISSUE TITLE
[question] - Graph acceleration

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cudf#438]
I am preparing some bench-marking for graph processing, I am aware of GraphX exisitng (CPU only) spark subproject. I also have collection of CUDA accelerated common graph algorithms (C only). On top of that I created JNI bridge (will commit into JavaCPP presets  https://github.com/bytedeco/javacpp-presets soon..) for CUDA accelerated comprehensive library for general graph algo processing. Guys support at moment single node multi-gpu setup: https://gunrock.github.io/docs/

Now the idea is to integrate GraphX (VertexRDD, EdgeRDD) with Gunrock via RAPIDS layer... :-) not sure if all my assumptions leading me to this idea are correct, but it should lead to Spark GPU accelerated graph processing.

What is your opinion on this? I think Graphs will become more and more popular in AI workloads as well.

Thank you for any kind of response on this.

**Comment by MurrayData** [comment]
This is very interesting. I've implemented a simple GPU based graph structure, using NUMBA, with the A* algorithm compiled as CUDA JIT function to add road distances and drive times to retail datasets in Rapids. I think graph acceleration would a very useful addition to Rapids.

**Comment by datametrician** [comment]
I'm going to close this out @archenroot and @MurrayData but please check out NVGraph https://developer.nvidia.com/nvgraph. All of this will be added to cuGraph, and we will start work on multi-GPU graph algorithms in the coming months.

**Comment by archenroot** [comment]
@datametrician - I got under impression that you are going to integrate with Gunrock (they support already multigpu graph algo, etc.)
