### ISSUE TITLE
Comparing floats with a fixed episilon is bad. Instead, use units in the last place. 

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4383]
Comparing floats with a fixed episilon is bad. Instead, use units in the last place. See https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

_Originally posted by @jrhemstad in https://github.com/rapidsai/cudf/pull/4331#issuecomment-595489519_

**Comment by GregoryKimball** [comment]
Closing for now
