### ISSUE TITLE
CSV_TEST fails with CUDA launch failure

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#440]
- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the following environment details:
      Linux Ununtu 18.04, Tesla V100

CSV_TEST fails with the error: `ERROR: CUDA Runtime call cudaGetLastError() in line 833 of file /home/mharris/src/cudf/cpp/src/io/csv/csv_reader.cu failed with too many resources requested for launch (7).`

We believe the error is caused by a block size set to 1024 threads which causing too many registers to be needed to launch the `countRecords` kernel.

**Comment by harrism** [comment]
I'm working on a fix.

**Comment by harrism** [comment]
ACtually, I thought the fix would be to use smaller block size, but it turns out that doesn't fix it. There's something else wrong. If you run *just* the QuotedStrings test by itself, like this: `CUDA_TRY(cudaDeviceSynchronize());` you get the following output:

```
Running main() from gmock_main.cc
Note: Google Test filter = gdf_csv_test.QuotedStrings
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from gdf_csv_test
[ RUN      ] gdf_csv_test.QuotedStrings
/home/mharris/src/cudf/cpp/tests/io/csv/csv_test.cu:314: Failure
Expected: (stringLengths[i]) > (0), actual: -1 vs 0
[  FAILED  ] gdf_csv_test.QuotedStrings (1659 ms)
[----------] 1 test from gdf_csv_test (1659 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1659 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] gdf_csv_test.QuotedStrings
```

Note there is no CUDA error. Instead, the assert on line 377 in this code is failing due to `StringLengths[0]` equaling `-1`.
https://github.com/rapidsai/cudf/blob/dae6026475aa19947fcf46c792cd11a18a32c43b/cpp/tests/io/csv/csv_test.cu#L375-L379

@j-ieong since you wrote this code, can you fix? I think this is a high priority bug to fix.

Assigning to @BradReesWork since for some reason github won't let me assign to @j-ieong (?)

**Comment by j-ieong** [comment]
I'll try to repro and debug. I haven't been able to repro it on my Ubuntu 18.04 with RTX 2080 yet.

@harrism Does it happen with the regular string test as well?

**Comment by harrism** [comment]
What is the regular string test?

**Comment by j-ieong** [comment]
That should be the first test in csv_test.cu. There should be three gtests:
gdf_csv_test.Strings (does not test quotechar)
gdf_csv_test.QuotedStrings (tests 'quotechar')
gdf_csv_test.KeepFullQuotedStrings (tests 'quotechar' and 'quoting')

Trying to isolate whether it's due to the quoting, since we didn't have a gtest for non quoting strings until now...

**Comment by harrism** [comment]
It happens for all tests. Try `gtests/CSV_TEST --gtest_filter=gdf_csv_test.Strings`.

**Comment by j-ieong** [comment]
Okay, now I see the "too many resources requested" if I rebuild the whole thing using -DCMAKE_BUILD_TYPE=Debug. Seems like the extra debug info are causing the kernels to be overloaded but release doesn't, on my system.

I tried reducing the threads for every csv_reader kernel (countRecords, storeRecordStart, dataTypedetect, convertCsvToGdf) from 1024 to 512, and all the gests passes for me now.

**Comment by harrism** [comment]
@j-ieong that's not what I see. As I explained above, if I run a single test, I get the GTest assert failure caused by the length of the first string being `-1`. Did you run the single gtest command line I sent?

**Comment by j-ieong** [comment]
@harrism Okay I did a fresh setup, now I do see the -1 failure, when running that single test.  However, changing threads to 256 still fixes the issue for me. Hrmmm...

**Comment by harrism** [comment]
If you submit your PR to GitHub I can test on my machine.

**Comment by Msabih** [comment]
CSV TEST fails on my machine as well.
