### ISSUE TITLE
[QST]how to use libcudf directly？

### ISSUE THREAD

**Issue by scirocc** [rapidsai/cudf#4426]
hi everybody.I am just new to here.Can I ask you a simple question?I wanna use libcudf directly,how should I do that?Now I download cuda10.2 and libcudf-0.13.0a200216-cuda10.2_1863.tar.bz2.In cmakelist I wrote something like this:
`include_directories(../libcudf/include)
target_link_libraries(helloworld libcudf.so)
target_link_libraries(helloworld libcudftestutil.a)`

Is that correct?

**Comment by kkraus14** [comment]
@scirocc you shouldn't need to link against `libcudftestutil.a` unless you're looking for our testing utilities. Just linking against `libcudf.so` should get you all of the functionality you're looking for.
