### ISSUE TITLE
[FEA] add cuda 10.2 environment

### ISSUE THREAD

**Issue by rongou** [rapidsai/cudf#4437]
**Is your feature request related to a problem? Please describe.**
Build cuDF with CUDA 10.2.

**Describe the solution you'd like**
Add an environment file for cuda 10.2.

**Describe alternatives you've considered**
Duplicate the cuda 10.1 file locally and change it to 10.2.

**Additional context**
CUDA download page defaults to 10.2.

**Comment by datametrician** [comment]
This is coming in 0.13 and has been announced and planned. I feel this is tracked somewhere else so going to close if that's ok. Thanks @rongou

**Comment by rongou** [comment]
@datametrician This turns out to be non-trivial, at least copying `conda/environments/cudf_dev_cuda10.1.yml` and changing the cuda version there didn't work. Is there a tracking issue for this somewhere?

**Comment by datametrician** [comment]
@mike-wendt @kkraus14

**Comment by rongou** [comment]
Fixed by #4479

**Comment by datametrician** [comment]
Thanks @rongou
