### ISSUE TITLE
[BUG] Kafka external datasource bugs

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4442]
Creating this on @jdye64's request.

Using this as reference: [https://github.com/jdye64/cudf/blob/kratos/python/custreamz/custreamz/kafka.py](https://github.com/jdye64/cudf/blob/kratos/python/custreamz/custreamz/kafka.py
)

If another consumer just commits or gets committed offsets, but doesn’t 'consume' from the same topic partition, the notebook kernel dies. Is this expected?

**Comment by jdye64** [comment]
@chinmaychandak can you attach a ipynb or python snippet where where that is occurring here?

**Comment by chinmaychandak** [comment]
Can't seem to find it rn, but you can easily reproduce it. Create a consumer, consume some data,  and then use another consumer to say retrieve watermarks or committed offsets for the same TopicPartition.
