### ISSUE TITLE
Initialize RMM once per test program instead of once per test suite

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#4448]
RMM is currently initialized and finalized in every test case. Enabling pool mode prohibitively increases the test execution time in this setup.
Proposal: move the RMM initialization to a test environment object and instantiate it in every test program. With this, RMM pool mode can be expected to improve execution time.

**Comment by jrhemstad** [comment]
Related, see https://github.com/rapidsai/cudf/issues/797#issuecomment-528980321

**Comment by vuule** [comment]
Fixed in #4616
