### ISSUE TITLE
[BUG] dask version mismatch

### ISSUE THREAD

**Issue by afender** [rapidsai/cudf#4452]
**Describe the bug**
After https://github.com/rapidsai/cudf/pull/4412 `dask` and `distributed` versions mismatch between `ci` and `conda` folders

**Steps/Code to reproduce bug**

https://github.com/rapidsai/cudf/blob/8de02da243a042b571e50b2620785d9a505f2b13/ci/gpu/build.sh#L61

https://github.com/rapidsai/cudf/blob/8de02da243a042b571e50b2620785d9a505f2b13/conda/environments/cudf_dev_cuda10.1.yml#L37

**Expected behavior**
I assume it should be 2.12.0 there: https://github.com/rapidsai/cudf/blob/8de02da243a042b571e50b2620785d9a505f2b13/ci/gpu/build.sh#L61

**Comment by kkraus14** [comment]
@afender right below the lines in `gpu/build.sh` we install from master so we always test with the latest versions of Dask and Distributed.
