### ISSUE TITLE
[BUG] dask_cudf: cannot rename index

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#4475]
**Describe the bug**
Issuing a `.rename({'index':'foo'})` after `.reset_index()` leads to error: `cannot rename index`. The same behavior in `cudf` works fine.

**Steps/Code to reproduce bug**
`df = dask_cudf.from_cudf(cudf.DataFrame({'a': [0,1,2,2,3,4]}), npartitions=2)['a'].reset_index().rename({'index': 'foo'})`

**Expected behavior**
The column named `index` to be renamed to `foo`.

**Environment overview (please complete the following information)**
 - Environment location: Docker on AzureML, nightly 0.13
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

```
docker pull rapidsai/rapidsai-nightly:cuda10.1-runtime-ubuntu18.04-py3.7
docker run --gpus all --rm -it -p 8888:8888 -p 8787:8787 -p 8786:8786 \
    rapidsai/rapidsai-nightly:cuda10.1-runtime-ubuntu18.04-py3.7
```

**Comment by kkraus14** [comment]
@drabastomek Can you dump the output of just:
```
test = dask_cudf.from_cudf(cudf.DataFrame({'a': [0,1,2,2,3,4]}), npartitions=2)['a'].reset_index()
print(test.columns)
print(test._meta.columns
```
Curious what columns it thinks

**Comment by drabastomek** [comment]
@kkraus14 

The output is as expected:

```
Index(['index', 'a'], dtype='object')
Index(['index', 'a'], dtype='object')
```

Here's the actual error I get:

```
/opt/conda/envs/rapids/lib/python3.7/site-packages/dask/dataframe/core.py in rename(self, index, columns)
   3655     def rename(self, index=None, columns=None):
   3656         if index is not None:
-> 3657             raise ValueError("Cannot rename index.")
   3658 
   3659         # *args here is index, columns but columns arg is already used
```

**Comment by kkraus14** [comment]
@drabastomek can you try with:
```
df = dask_cudf.from_cudf(cudf.DataFrame({'a': [0,1,2,2,3,4]}), npartitions=2)['a'].reset_index().rename(columns={'index': 'foo'})
```

This looks to be an upstream Dask issue in not supporting the `mapper` arg.

**Comment by drabastomek** [comment]
Thanks @kkraus. This worked! Still, I think this might need to get address as it's inconsistent between `cudf` and `dask_cudf`. I'll let you decided if you want to close this for now :)

**Comment by kkraus14** [comment]
Will close when we raise an upstream issue against Dask, thanks!

**Comment by kkraus14** [comment]
This is actually not a Dask issue. cuDF has erroneous behavior here where `rename` technically should default to doing index row renaming instead of column name renaming.
