### ISSUE TITLE
[FEA] `detail::scatter` has several issues

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4485]
**Is your feature request related to a problem? Please describe.**

The [`detail::scatter` ](https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/include/cudf/detail/scatter.cuh#L180)API is deficient in several ways:

1. It inexplicably requires an explicit template parameter `T` which is undocumented what this type is used for, and so attempting to call `detail::scatter` will leave you very confused with compiler errors like: 
```
error: no instance of function template "cudf::experimental::detail::scatter" matches the argument list
```

Because you need to invoke it like:
```
detail::scatter<T>(...)
```

This is not usable as-is. 

2. There is no way for the caller to opt out of having negative scatter map indices wrapped back around. Like `detail::gather`, the caller should be able to opt out of this unnecessary step.

**Comment by davidwendt** [comment]
Looks like #4486 should've closed this issue.
