### ISSUE TITLE
[QST] Loading dataset of images with dask_cudf for ML with dask_cuml

### ISSUE THREAD

**Issue by Cipcu** [rapidsai/cudf#4512]
**What is your question?**
Hey,

i want to evaluate _dask_cudf_ and _dask_cuml_ in terms of efficiency. For that, i have a kubernetes cluster on gcloud with a few Nvidia Tesla T4 GPUs and a jupyterlab with _dask_, _dask_cudf_ & _dask_cuml_ installed. 

For now, i have a ~400MB _Intel Image Classification_ dataset consiting of 150x150 images of different landscapes. I would like to load the images with GPUs and than use _dask_cuml_ on them.  I have a little problem with loading the images though so that I can use them as input (_train, test, predict_ etc.) for _cuml_ functions.
Since I haven't found any direct method to load images with _cudf_, i decided to convert them into csv files. For the training, it results in 6 csv files, each with about 22500 rows and 2100 columns. Using dask_cudf.read_csv on even one of these files is really slow, and alone computing _head_ takes about 1 minute (pandas takes about 2-5 seconds).  

My question is, what would be the general steps to load a dataset consiting of images, possibly efficent and with using multiple workers (i am planning on using a larger dataset later) and then apply _dask_cuml_ functions on it.  I know that so many columns may be the reason for _cudf_ to be slow, but what are the other options, if I want to use GPUs for reading. Or maybe it would be better to read the files with CPUs and then convert them into _cudf_ dataframes? 

Version of rapids=0.12, dask_cudf=0.9 dask_cuml=0.8, dask=2.10.1

Thanks a lot !
Cipcu

**Comment by OlivierNV** [comment]
How about representing the images as 150 columns of 150-characters strings in parquet or ORC format (at least it would avoid storing it as text)

**Comment by Cipcu** [comment]
Hey,
thanks for the response. You mean a parquet file, in which one cell represents the 150 pixel values from the y-axis of the image ? I will try this and let know, if it improves the timing.  

Thanks!

**Comment by Cipcu** [comment]
Hey,
so, it improves the timing massively for CSV and even more for parquet. Now, however, the question is, how can I feed this kind of cudf dataframe into cuml-fit functions? Every elemnt of the dataframe consists now of a string with 150 numbers. I guess I need to convert it into list of ints. Will try.

**Comment by OlivierNV** [comment]
Not familiar with cuml, but IIRC, it should be possible to map individual columns to numpy arrays. It might not be too difficult to implement a slightly different frontend to the io readers to return numpy arrays instead of cudf dataframes, probably something we should consider if there are benefits (may also allow loading multiple columns as contiguous 2D arrays, something not possible with dataframes where each column is its own allocation)

**Comment by Cipcu** [comment]
Hey thank you for help. I gave up on trying to load images with cudf for cuml. Decided to use a dataset with a few features and many rows. I'm closing.

**Comment by harrism** [comment]
BTW, NVIDIA has a library for optimized handling of image datasets intended for deep learning. Perhaps it can be used to load and create a dataset for RAPIDS as well? https://github.com/NVIDIA/DALI

**Comment by Cipcu** [comment]
Hey, thanks for DALI suggestion. From quick research it seem possible to combine those two libraries, which would allow keeping everything on GPU. Will give it a closer look.
