### ISSUE TITLE
[FEA] Support `__array__` and `__arrow_array__` protocols

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#4552]
Would allow for much more performant and safer implicit conversions of things like Series / Index to some host array-like objects.

**Comment by jakirkham** [comment]
On the one hand, I agree this can be quite useful as things like `np.asarray(...)` would just work. On the other hand, this could hide device-to-host transfers in complex pipelines by accident.

FWIW CuPy has had similar conversations over time ( https://github.com/cupy/cupy/issues/589 ) and decided not to support, but instead raise an informative error about what to do. For contrast, Numba does support this behavior ( https://github.com/numba/numba/pull/2667 ).

**Comment by kkraus14** [comment]
@jakirkham one problem is `np.asarray(...)` still just works via iteration of `__getitem__` calls which is infinitely worse. One on hand they basically stall the program to the point it becomes easy to diagnose what's happening, on the other hand it stalls the program...

**Comment by jakirkham** [comment]
Right. I'm not saying we shouldn't implement `__array__`. Am saying we have a choice of how we do that:

1. CuPy approach of erroring
2. Numba approach of performing device-to-host transfer
3. Some hybrid approach (flag to enable/disable device-to-host transfer)
4. ?

**Comment by jakirkham** [comment]
`__array__` was implemented in PR ( https://github.com/rapidsai/cudf/pull/4864 ).

Does `__arrow_array__` need to be implemented separately or does it fallback to `__array__`?

**Comment by kkraus14** [comment]
> Does `__arrow_array__` need to be implemented separately or does it fallback to `__array__`?

I believe separately. Not sure if we'd want to similarly raise as in `__array__` or have it gracefully return a pyarrow array.

**Comment by galipremsagar** [comment]
> I believe separately. Not sure if we'd want to similarly raise as in `__array__` or have it gracefully return a pyarrow array.

@kkraus14, Should we let `__arrow_array__` to raise error(a similar error like we do in `__array__` ), but specify in that error for the user to explicitly use `.to_arrow`

**Comment by kkraus14** [comment]
> @kkraus14, Should we let `__arrow_array__` to raise error(a similar error like we do in `__array__` ), but specify in that error for the user to explicitly use `.to_arrow`

Yes this sounds like a good plan to me. This maintains the pattern of device --> host needs to be done explicitly by the user / library instead of hitting it implicitly.
