### ISSUE TITLE
[FEA] Implement `gather_by_key` 

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#4574]
**Is your feature request related to a problem? Please describe.**
Considering two columns, one is subset of other, need a gather map. In case of multi-columns, it would set of columns.
Example:
sub_col = {2, 4, 1, 5, 6}
col = {1, 2, 3, 4, 5, 6, 7}

expected_col = {1, 3, 0, 4, 5}

Multi-Column Example:
sub_cols={{ 3,    1,   2}, 
                 {"a", "b", "a"}}
cols={{  1,    2,    3,   1,    2,  3},
          {"a", "a", "a", "b", "b", "b"}}

expected_col={2, 3, 1}
**Describe the solution you'd like**
A libcudf API that can accept two table_views and return gather map for the sub table_view.

**Comment by jrhemstad** [comment]
Can you give more explanation? I don't understand the example.

**Comment by rgsl888prabhu** [comment]
As libcudf doesn't actually work on the index that normally we have in python, we need a mapping between that index to generic indexing which we normally use in libcudf.

So, considering an index=[10, 20, 30, 40, 50, 60, 70], and if we want fetch values for [30, 40], we need to map [30, 40] to [2, 3] to use it in libcudf.

**Comment by kkraus14** [comment]
## Logical Explanation
Imagine wanting to treat a set of columns as "row-labels", and then run a gather on the Table based on those "row-labels".

## Example
Say I have a table `source_table`:
| a | b | c | d |
|---|---|---|---|
| 10 | 20 | 30 | 40 |
| 11 | 21 | 31 | 41 |
| 12 | 22 | 32 | 42|
| 13 | 23 | 33 | 43 | 
| 14 | 24 | 34 | 44 |

And I want to gather some rows based on the values of columns `a` and `c`, where I pass something that looks like a vector of column_views:
```
[[14, 12, 14, 10], [34, 32, 34, 30]]
```
The expected output would either be a gather map (as a Column):
```
[4, 2, 4, 0]
```
or you could materialize the end result Table for us:
| a | b | c | d |
| - | - | - | - |
| 14 | 24 | 34 | 44 |
| 12 | 22 | 32 | 42 |
| 14 | 24 | 34 | 44 |
| 10 | 20 | 30 | 40 |

**Comment by jrhemstad** [comment]
So a more generic way of describing it is to return the index of an element from a needle table in a haystack table.

So:
```
unique_ptr<column> index_of(table_view haystack, table_view needles);
```

**Comment by rgsl888prabhu** [comment]
Yes

**Comment by jrhemstad** [comment]
And since you plan to just use this for gathering anyways, how about fuse it into a single operation:
```
unique_ptr<table> gather_by_key(table_view source, vector<size_type> key_columns, table_view keys);
```

Where `key_columns` indicates which columns will act as the keys into `source`, and `keys` indicates the values to gather from `source`. `key_columns.size() == keys.num_columns`.

**Comment by rgsl888prabhu** [comment]
Can we have both APIs, I feel other API would also be useful in some other scenarios

**Comment by jrhemstad** [comment]
> Can we have both APIs, I feel other API would also be useful in some other scenarios

Let's not add features without concrete needs.

**Comment by jrhemstad** [comment]
What is the behavior if there are multiple matches in the key rows of `source` for a given row in `keys`?

**Comment by rgsl888prabhu** [comment]
The pandas provides both index values that matches, but I would leave decision to @kkraus14.

**Comment by kkraus14** [comment]
> What is the behavior if there are multiple matches in the key rows of `source` for a given row in `keys`?

It gives an output for each match. I believe Pandas will likely do it in the order of input table but I don't think we need to / should constrain ourselves to that behavior.

**Comment by jrhemstad** [comment]
Are you positive we need match the behavior of returning an output for all matches in `source`? 

That's a significantly harder problem because now the output size is indeterminate. 

Furthermore, the original `index_of` feature request would not have worked for this behavior. 

I thought index columns in Pandas are supposed to be all unique values?

**Comment by kkraus14** [comment]
> Are you positive we need match the behavior of returning an output for all matches in `source` for each row in `keys`?
> 
> That's a significantly harder problem because now the output size is indeterminate.
> 
> Furthermore, the original `index_of` feature request would not have worked for this behavior.
> 
> I thought index columns in Pandas are supposed to be all unique values?

Yes I'm positive. No there's certain places that guarantee uniqueness and others that do not, and this is unfortunately one of those places that non-uniqueness is gracefully handled as expected.

**Comment by cwharris** [comment]
I assume this will require two passes, one to determine the size of the output, and another to perform the gather. Perhaps the first pass should generate a boolean mask which can be summed to produce the result size and used to retrieve the already-matched elements.

Another thought: since `gather` already exists, is it prudent to have this function return an index only, rather than the gather results? The consumer could compose `index_of` and `gather`. That's at the expense of an intermediary column.

Now that I'm thinking about, could `index_of` (or rename it) return a boolean mask? If we have a gather function that accepts a boolean mask, the consumer can use that. If not, maybe it's best to make one, since something needs to do that work anyway?

I'm sure there are many ways to go about this. Those are just my initial thoughts.

**Comment by kkraus14** [comment]
> Now that I'm thinking about, could `index_of` (or rename it) return a boolean mask?

It would need to be a gathermap since the order of the output needs to match the order of the input keymap.

**Comment by harrism** [comment]
Basically, you want "find all rows that match the specified keys in the specified key columns".

This is basically a fancy `copy_if`, where the predicate is just to check if the element from the table matches the keys at the corresponding columns. 

But if you want the output in the order given by the keys, it gets harder (it's not just a copy_if). Do you require the output to be in that order, as in @kkraus14 's example?

**Comment by kkraus14** [comment]
@harrism yes the output needs to match the order given by the keys, plus we need to be able to handle duplicate keys which would return duplicate values in the order specified as well.

**Comment by harrism** [comment]
OK, so it requires a sort of the key columns in order to do a vectorized lower_bound on the key columns

`source_table`:
a | b | c | d
-- | -- | -- | --
10 | 20 | 30 | 40
12 | 22 | 32 | 42
14 | 24 | 34 | 44
13 | 23 | 33 | 43
11 | 21 | 31 | 41

(reordered some rows to make it more interesting)

`key_columns`: a and c:

`needles`: `[[14, 12, 14, 10], [34, 32, 34, 30]]`

1. Create a table `key_table` made of the key columns of `source_table` and an index column (just 0 to numrows in the input table):

idx | a | c
-- | -- | --
0 | 10 | 30
1 | 12 | 32
2 | 14 | 34
3 | 13 | 33
4 | 11 | 31

2. Sort `key_table` in lexicographic order (by the key columns only)

idx | a | c
-- | -- | --
0 | 10 | 30
4 | 11 | 31
1 | 12 | 32
3 | 13 | 33
2 | 14 | 34

3. lower_bound of the needles in the non-index columns of this table

`auto lb = lower_bound(sorted_key_table, needles);`

`lb = [4, 1, 4, 0]`

4. indirect into the sorted index column to get a gather map. This doesn't need to be materialized if it can be put into a transform_iterator used by gather?

`gather_map[i] = idx[lb]`

5. gather from the input table using the gather map

`ret = gather(source_table, gather_map)`

Cost is sort [O(n log n)] + lower_bound [O(k log n)] + gather [O(k)] == O((n + k) log n), where n is the size of `source_table` and k is the size of `needles`.

It would be nice to flip the problem and sort the needles and search for the rows of the source_table key columns in the sorted needles (this would be O((n + k) log k)), but that wouldn't support duplicates and wouldn't output in the order of the needles.

**Comment by kkraus14** [comment]
I believe your example assumes both `a` and `c` are similarly sorted which they aren't in practice. We could have it sorted by `a`, but `c` would likely not be sorted afterwards.

**Comment by harrism** [comment]
I don't understand, please provide an example.  I think we have to assume that since a and c are columns of the same input table, their ordering at the time of input is linked / the same.

**Comment by kkraus14** [comment]
Derived from your above example but tweaked to make sorting not align and adding duplicates:

`source_table`:

| a | b | c | d |
| - | - | - | - |
| 10 | 22 | 33 | 40
| 12 | 21 | 30 | 41
| 11 | 20 | 33 | 42
| 10 | 23 | 31 | 43
| 10 | 22 | 33 | 44


`key_columns`: a and c

`needles`: `[[12, 10, 10, 10], [30, 33, 31, 33]]`

1. Create a table `key_table` made of the key columns of `source_table` and an index column (just 0 to numrows in the input table):

| idx | a | c |
| - | - | - |
| 0 | 10 | 33 |
| 1 | 12 | 30 |
| 2 | 11 | 33 |
| 3 | 10 | 31 |
| 4 | 10 | 33 |

2. Sort `key_table` in lexicographic order (by the key columns only). **This is where I believe we run into problems in sorting by `a` leaves `c` unsorted which makes us unable to run a `lower_bound` against it.**

| idx | a | c |
| - | - | - |
| 0 | 10 | 33 |
| 3 | 10 | 31 |
| 4 | 10 | 33 |
| 2 | 11 | 33 |
| 1 | 12 | 30 |

**Skipping to final output, note that each needle can generate multiple output rows. Including a *needle* column just for reference, number in parenthesis is the index of the input needle corresponding to the output row**:
| a | b | c | d | *needle* |
| - | - | - | - | - |
| 12 | 21 | 30 | 41 | [12, 30] (0) |
| 10 | 22 | 33 | 40 | [10, 33] (1) |
| 10 | 22 | 33 | 44 | [10, 33] (1) |
| 10 | 23 | 31 | 43 | [10, 31] (2) |
| 10 | 22 | 33 | 40 | [10, 33] (3) |
| 10 | 22 | 33 | 44 | [10, 33] (3) |

**Comment by harrism** [comment]
Your sort is not lexicographical by a, then c, which is what my algorithm suggested. You only sorted by a.

But indeed my algorithm can't generate multiple outputs per needle. 

I think what we need is to run a lower_bound AND an upper_bound. This would result in a range of outputs per input. Then we would need to do a scan on the distances between the lower and upper bounds to get the total size of the output and the starting offset for each needle's output. Then we would need to generate the gather map into this, and use it. 

So a few extra steps. It's complicated, but doable.

**Comment by kkraus14** [comment]
If we sort lexicographically by `a`, then `c` the output would be:

| idx | a | c |
| - | - | - |
| 3 | 10 | 31 |
| 0 | 10 | 33 |
| 4 | 10 | 33 |
| 2 | 11 | 33 |
| 1 | 12 | 30 |

Which still doesn't leave `c` in a state you can run a lower/upper bound against, no? Unless you're talking about sorting `a` and `c` individually, but then you're breaking the rows.

**Comment by harrism** [comment]
The lower_bound is lexicographical too. The values of a are sorted, and the values of c within each value of a are sorted. So lower_bound would work.

**Comment by kkraus14** [comment]
Apologies I may have misunderstood. We have table level `lower_bound` and `upper_bound` as opposed to just column level?

**Comment by harrism** [comment]
I assume so, but could be wrong.

**Comment by kkraus14** [comment]
FWIW the way we currently have this implemented on the Python side:

`source_table`:

| a | b | c | d |
| - | - | - | - |
| 10 | 22 | 33 | 40 |
| 12 | 21 | 30 | 41 |
| 11 | 20 | 33 | 42 |
| 10 | 23 | 31 | 43 |
| 10 | 22 | 33 | 44 |

Build table of `needles` along with `idx` column of 0 --> N:

| idx | a | c |
| - | - | - |
| 0 | 12 | 30 |
| 1 | 10 | 33 |
| 2 | 10 | 31 |
| 3 | 10 | 33 |

Run a join on the two tables against `a` and `c` (giving random output order):

| idx | a | b | c | d |
| - | - | - | - | - |
| 1 | 10 | 22 | 33 | 40 |
| 0 | 12 | 21 | 30 | 41 |
| 3 | 10 | 22 | 33 | 40 |
| 2 | 10 | 23 | 31 | 43 |
| 1 | 10 | 22 | 33 | 44 |
| 3 | 10 | 22 | 33 | 44 |

Sort by `idx`:

| idx | a | b | c | d |
| - | - | - | - | - |
| 0 | 12 | 21 | 30 | 41 |
| 1 | 10 | 22 | 33 | 40 |
| 1 | 10 | 22 | 33 | 44 |
| 2 | 10 | 23 | 31 | 43 |
| 3 | 10 | 22 | 33 | 40 |
| 3 | 10 | 22 | 33 | 44 |

Then drop `idx` column for final output:

| a | b | c | d |
| - | - | - | - |
| 12 | 21 | 30 | 41 |
| 10 | 22 | 33 | 40 |
| 10 | 22 | 33 | 44 |
| 10 | 23 | 31 | 43 |
| 10 | 22 | 33 | 40 |
| 10 | 22 | 33 | 44 |

**Comment by harrism** [comment]
Yeah I was wondering if a join might be faster or simpler.

**Comment by shwina** [comment]
@harrism @jrhemstad Happy to take this on if it isn't being worked on already -- need it for #5448.

**Comment by harrism** [comment]
That's fine. We can discuss the right name in your PR.

**Comment by shwina** [comment]
Just extending the above examples to use the algorithm @harrism outlines [here](https://github.com/rapidsai/cudf/issues/4574#issuecomment-625021146) to facilitate discussion:

`source_table`:
a | b | c | d
-- | -- | -- | --
10 | 20 | 30 | 40
12 | 22 | 32 | 42
14 | 24 | 34 | 44
13 | 23 | 33 | 43
11 | 21 | 31 | 41
10 | 30 | 30 | 45

(reordered some rows to make it more interesting)

`key_columns`: a and c:

`needles`: `[[14, 12, 14, 10], [34, 32, 34, 30]]`

1. Create a table `key_table` made of the key columns of `source_table` and an index column (just 0 to numrows in the input table):

idx | a | c
-- | -- | --
0 | 10 | 30
1 | 12 | 32
2 | 14 | 34
3 | 13 | 33
4 | 11 | 31
5 | 10 | 30

2. Sort `key_table` in lexicographic order (by the key columns only)

`sorted_key_table`
idx | a | c
-- | -- | --
0 | 10 | 30
5 | 10 | 30
4 | 11 | 31
1 | 12 | 32
3 | 13 | 33
2 | 14 | 34

3. lower_bound **and upper_bound** of `needles` in `sorted_key_table`, using a lexicographical comparator that compares only key columns.

`needles`: `[[14, 12, 14, 10], [34, 32, 34, 30]]`

`auto lb = lower_bound(sorted_key_table, needles);`

`lb = [5, 3, 5, 0]`
`ub = [6, 4, 6, 2]`

4. Do a scan on the distances between the lower and upper bounds to get the total size of the output and the starting offset for each needle's output. 

`offsets = [0, 1, 2, 3, 5]`

5. Generate the gather map:

`gather_map[offsets[i]:offsets[i+1]] = idx[lb[i]:ub[i]] // == [2, 1, 2, 0, 5]`

6. gather from the input table using the gather map

`ret = gather(source_table, gather_map)`

`ret`:
a | b | c | d
-- | -- | -- | --
14 | 24 | 34 | 44
12 | 22 | 32 | 42
14 | 24 | 34 | 44
10 | 20 | 30 | 40
10 | 30 | 30 | 45

**Comment by jrhemstad** [comment]
@shwina now that you've laid it all out, I realized that you literally just described the sort-based join algorithm.

**Comment by shwina** [comment]
So to clarify: would a hash join with a sort as a pre-processing step be more efficient than the algorithm above? The hash join approach is what we currently do in Python.

**Comment by jrhemstad** [comment]
> So to clarify: would a hash join with a sort as a **post**-processing step be more efficient than the algorithm above? The hash join approach is what we currently do in Python.

`gather_by_key` is just a join.

If you want `index_of`, then a join + a sort is needed, and should definitely be faster because it's a single column integer sort vs. a multi-col sort.

Question is, do you really need `index_of`? Or can you just use the indices of the join result to implement the functionality you're ultimately after?

**Comment by shwina** [comment]
For `unstack`, I specifically need to be able to get the `index_of` to generate a scattermap to pass to `scatter_to_table`

**Comment by GregoryKimball** [comment]
We ended up implementing `loc` with join functions rather than `gather_by_key`
