### ISSUE TITLE
[BUG] Kafka external data source — get_watermark_offsets(timeout=.., cached=False) throws errors

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4581]
@jdye64 

Reproduce using:

```
from time import sleep
import confluent_kafka as ck
from custreamz import kafka


def main():
    params = {
        "metadata.broker.list": "localhost:9092",
        "enable.partition.eof": "true",
        "group.id": "custreamz",
        "auto.offset.reset": "earliest",
        "enable.auto.commit": "false",
        "session.timeout.ms": "60000"
     }

    c = kafka.Consumer(params)
    
    while True:
        tp = ck.TopicPartition('test-topic', 0)
        try:
            print(c.get_watermark_offsets(tp, timeout=1, cached=False))
        except:
            pass
        print('tick')
        sleep(1)


if __name__ == '__main__':
    main()
```

It should return (0,0) when there's no messages.

In fact, it throws errors even when there's messages in the topic.

**Comment by jsmaupin** [comment]
Can we share an example of the error message?

**Comment by chinmaychandak** [comment]
There's a minor fix needed in the error message, too. Have already pinged Jeremy about it and he's working on it.

**Comment by jdye64** [comment]
This is now resolved and (0, 0) will be returned instead of -1001

https://github.com/jdye64/cudf/blob/kratos/python/custreamz/custreamz/kafka.py#L91

**Comment by chinmaychandak** [comment]
Even then, `cached=False` throws errors, could you verify before you build?

**Comment by jdye64** [comment]
I haven't built and pushed yet after the fix. How did you see the error?

**Comment by chinmaychandak** [comment]
Well, it wasn't returning the correct output at the time. The fixes you made are for the error statement and the high offset to be returned as 0, so I thought it might be an unrelated bug.

**Comment by chinmaychandak** [comment]
Yes, just tried the new build. 

When `cached=False` (just running the example above), it throws:

`
ValueError: Multiple watermark offsets encountered. Only 2 were expected and 0 encountered
`

**Comment by jdye64** [comment]
Ok perfect 👌

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by chinmaychandak** [comment]
Hmm, when I remove `timeout` altogether, `cached=False` seems to work. But then obviously timeout isn't respected when say the Kafka broker/s are down.

Not sure why this is happening. 

@jdye64 Any ideas?

**Comment by chinmaychandak** [comment]
Okay, I think it was just the first couple of calls with `cached=False` that threw an error. Now that I have a try-catch in the script, everything seems to work fine.

Although, it seems to pose the same problem as CK — the timeout is not respected when the Kafka brokers are down; instead it just gets stuck indefinitely. As we discussed, an error should be thrown in this case.

**Comment by jdye64** [comment]
@chinmaychandak the default value of `session.timeout.ms` is 60s or 1 minute. After that an exception should be thrown. Are you seeing it sitting there longer than that?

IF you are this is a librdkafka bug that would need resolved on their end and not ours.

**Comment by chinmaychandak** [comment]
> Are you seeing it sitting there longer than that?

Yes, can you give it a try and confirm it?

> IF you are this is a librdkafka bug that would need resolved on their end and not ours.

Yup, can we point it out to them, then? And hope someone resolves this. 

CK has this: https://github.com/confluentinc/confluent-kafka-python/issues/413

**Comment by jdye64** [comment]
![image](https://user-images.githubusercontent.com/2127235/77108274-46de4880-69f8-11ea-846d-cda3e5110061.png)

Ok I *think* I hacked something together that will work. I'm going to commit this and make another build for you to give it a shot.
