### ISSUE TITLE
[BUG] libcudf tests failing under `cuda-memcheck`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4583]
**Describe the bug**

Several libcudf tests are failing when run under `cuda-memcheck`. These may be serious or they may be spurious. We should diagnose.

- COLUMN_TEST
- COPYING_TEST
- DEVICE_ATOMICS_TEST
- DICTIONARY_TEST
- ERROR_TEST (I believe this one is expected.)
- ORC_TEST

**Expected behavior**

These tests shouldn't fail when run under `cuda-memcheck`. 

This reminds me that we should revisit: https://github.com/rapidsai/cudf/issues/904

**Comment by davidwendt** [comment]
Created PR #4612 to fix cuda-memcheck error for DICTIONARY_TEST

**Comment by davidwendt** [comment]
Created PR #4614 to fix COLUMN_TEST and COPYING_TEST

**Comment by OlivierNV** [comment]
ORC_TEST is a real bug (potential 3-byte OOB write in compression of random data ~ trivial fix, but probably would be good to have in 0.13). PR coming up.

**Comment by davidwendt** [comment]
@jrhemstad 
All of these have been fixed except for the ERROR_TEST one. 
That one purposely produces a kernel launch error which I don't think cuda-memcheck likes very much.

**Comment by jrhemstad** [comment]
> @jrhemstad
> All of these have been fixed except for the ERROR_TEST one.
> That one purposely produces a kernel launch error which I don't think cuda-memcheck likes very much.

Awesome. Thanks @davidwendt and @OlivierNV for jumping on these.
