### ISSUE TITLE
[BUG] to_parquet(index=...) throws an exception

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4597]
**Describe the bug**

Specifying `gdf.to_parquet(path, index=False)` throws exception:

```
>   ???
E   TypeError: __cinit__() got an unexpected keyword argument 'index'

pyarrow/_parquet.pyx:1220: TypeError
```

**Steps /Code to reproduce bug**

```
async def test_parquet_write():
    cudf.DataFrame({'x': [0, 1, 2]}).to_parquet('/opt/graphistry/.tmp/file2.parquet', index=False, compression='snappy')
```

**Expected behavior**

File saves with no exception

**Environment overview (please complete the following information)**

cudf 0.12 (conda) in docker

**Additional context**

The motivating use case is ensuring `index=False`, which the 0.12 docs report as engine-determined with the default of `index=None`.

**Comment by kkraus14** [comment]
This is fixed as of 0.13: https://github.com/rapidsai/cudf/blob/branch-0.13/python/cudf/cudf/io/parquet.py#L165-L209
