### ISSUE TITLE
[FEA] read_parquet() to be able to read specific row groups 

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#4604]
**Is your feature request related to a problem? Please describe.**
I want to be able to read specific row groups from a parquet file. Right now the current API allows for reading specific row groups but only if they are consecutive. 

**Describe the solution you'd like**
It would be a better more universal API if you could pass it a vector of row groups indexes that do not have to be consecutive

**Describe alternatives you've considered**
Right now I have to see for a set of row groups indexes, which are consecutive and then concatenate the resulting dataframes, which is not very performant and adds unnecessary complexity

**Additional context**

**Comment by OlivierNV** [comment]
Would this be for the pandas API, or just C++ ?
