### ISSUE TITLE
Added support for compression="gzip" on read_csv

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#462]
## Feature request
Need support on cudf read_csv  for compression argument

## Reporting a bug
Need support on cudf read_csv for the compression argument like pandas read_csv.
Looking for support for gzip compression type.

Use cases:
1. Decompress the entire gzip file into GPU memory through the read_csv API
2. Decompress only a partition / portion of the gzip between the skip_rows and nrows arguments.  This is necessary when the file decompressed is larger then the GPU memory.  The file will be read into GPU memory in partitions.  Expecting that the rows before skip_rows and after nrows should not occupy GPU memory.

```
import pandas as pd
pd.read_csv("sample.gz",compression='gzip')
```
```
import cudf
cudf.read_csv("sample.gz",compression='gzip')
```
```
import cudf
import pandas as pd
df1 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=0, nrows=400000)
df2 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=400001, nrows=400000)
df3 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=800001, nrows=400000)
df = pd.concat([df1,df2,df3])

```

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by kkraus14** [comment]
@BradReesWork assigned to you to coordinate the libcudf side and once that's done I can coordinate the Python changes.

**Comment by kenhester** [comment]
Issue #462 has much more detail about not decompressing the entire file into memory to allow for a partition or windowed read.

Please confirm this detail made it into issue 474 PR.

Ken Hester | NVIDIA Solutions Architect
c: 832-216-8736
khester@nvidia.com<mailto:khester@nvidia.com>

**Comment by kenhester** [comment]
Please re-open and update the original issue #462 and add Windowing comments as this was the intent of the original issue.

Even if gzip (deflate) is inherently serial, could you not deflate in chunks and throw away the data decompressed as you count rowlines until the start_row to nrows is  request is in gpu memory?



Ken Hester | NVIDIA Solutions Architect
c: 832-216-8736
khester@nvidia.com<mailto:khester@nvidia.com>
