### ISSUE TITLE
[DOC] Replace OutOfMemory exception with UnsupportedGPU exception

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4620]
**Describe the bug**

We end up getting deployed in scenarios where cudf, on initialization, throws an RMM exception for out of memory during load, when in reality it is rejecting the available hardware. 

This typically impacts our new-to-GPU users and even advanced ones during a config mistakes. E.g., on Azure, the default-available GPUs are K80s (until users jump quota hoops), so the typical Azure first-use experience is to spin up and get this misleading error.  It's quite a tough and misleading experience for most people until they've been burnt enough. 

We end up doing all sorts of things to try to get users to pick the right env etc. beforehand, but invariably, mistakes will happen, even by advanced users (misconfig, ...). 

Not sure if this is better in `cudf` or `rmm`.

**Steps/Code to reproduce bug**

`import cudf ; cudf.DataFrame({'x': [1]})` on an old popular GPU like the k80

And/or on common other init next steps like `set_alloc`

**Expected behavior**

Fail with `UnsupportedDeviceError` or something similarly indicative

**Environment overview (please complete the following information)**

Everywhere. We happen to hit it in Docker.

**Comment by kkraus14** [comment]
We have similarly poor error messages for old CUDA versions, old driver versions, etc. that we should handle in one swoop.

We should also strive to maintain allowing `cudf` to be imported on a machine with no GPU for things like API enumeration and whatnot.

**Comment by harrism** [comment]
@lmeyerov what version are you on?

**Comment by lmeyerov** [comment]
We were getting reports from 0.7 -- 0.11. We're shipping 0.12 next week and then switch internal to 0.13 

(0.13/0.14 should be faster b/c the 0.11 & 0.12 upgrades involved 100-200 unit tests & further automation around how we use it)

**Comment by lmeyerov** [comment]
Also, we always ship as docker, and in cloud cases but not on-prem, get to control the  host as ubuntu 18 + whatever the aws+azure nvidia drivers are at that time

**Comment by lmeyerov** [comment]
If overhead on the check is a concern,  another option that is fine for us as sw devs is explicit opt-in call. 

Ex: something like a `healthcheck()` or `validity()` . in opencl, you get back a set of valid devices & their specs, and can even pick which you're using (==> cooperatively schedulable.)

That wouldn't help direct cudf users like data scientists tho.

**Comment by jrhemstad** [comment]
This is pretty straightforward.

At `import cudf`:

-  GPU compute capability:  [`cudaDeviceGetAttribute`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__DEVICE.html#group__CUDART__DEVICE_1gb22e8256592b836df9a9cc36c9db7151) and check for `cudaDevAttrComputeCapabilityMajor > 7000`.
- CUDA Runtime: [cudaRuntimeGetVersion ](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html#group__CUDART____VERSION_1g0e3952c7802fd730432180f1f4a6cdc6)
- Driver version: check that the result of [`cudaDriverVersion`](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART____VERSION.html#group__CUDART____VERSION_1g8a06ee14a0551606b7c780084d5564ab) is >= to the result from `cudaRuntimeGetVersion`. 

Does numba or cupy already wrap the appropriate APIs? Or would we need to do so in cuDF cython?

**Comment by kkraus14** [comment]
Overhead on the check should be pretty low so I'm not too concerned.

> We were getting reports from 0.7 -- 0.11. We're shipping 0.12 next week and then switch internal to 0.13
Note 0.12 has a bunch of non-trivial memory overhead for Strings where you may just want to go from 0.11 --> 0.13 which has the overhead completely removed and additional memory usage improvements.

**Comment by lmeyerov** [comment]
We're stuck on `0.12` b/c blazing isn't blessed for `0.13` afaict: https://anaconda.org/blazingsql/blazingsql

**Comment by lmeyerov** [comment]
@jrhemstad  Sanity check re:not importing, will doing submodule imports (`from cudf.io.parquet...`) still trigger running `cudf/__init__.py`? I'm not up on python module semantics, so not sure if putting the check at module import time will still allow GPU-less module reflection.

**Comment by kkraus14** [comment]
> @jrhemstad Sanity check re:not importing, will doing submodule imports (`from cudf.io.parquet...`) still trigger running `cudf/__init__.py`? I'm not up on python module semantics, so not sure if putting the check at module import time will still allow GPU-less module reflection.

Yes it still will: https://docs.python.org/3/reference/import.html#regular-packages
