### ISSUE TITLE
[FEA] String support for `interleave_columns`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#4624]
`interleave_columns` currently supports only fixed-width types:

https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/src/reshape/interleave_columns.cu#L34

It would be great to have support for non fixed-width types as well, specifically strings.

**Comment by kkraus14** [comment]
@shwina the results for this were likely wrong for Strings before the port as I'm pretty sure we didn't synchronize the categories of the NVCategory objects before interleaving. We should be able to just throw if there's string columns for now on the Python side.

**Comment by nvdbaranec** [comment]
I believe this is done now:
https://github.com/rapidsai/cudf/pull/5248
