### ISSUE TITLE
[BUG] ngrams_tokenize default delimiter inconsistent with behavior

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#4634]
Post refactor, the default delimiter of `ngrams_tokenize` is listed as an empty string but appears to be whitespace. See https://github.com/rapidsai/cudf/blob/7bb1cae8b10ade881d8c8a903b7adca6b4ab6feb/python/cudf/cudf/core/column/string.py#L1835-L1842

The empty string scenario is handled differently (as shown below). We should probably update the default to be whitespace, and consider whether an empty string delimiter should be treated as whitespace. I suspect it should not.

```python
import nvtext
import cudf
​
s = cudf.Series(["this .   fs,.ds,.fefem", "hello", ""])


old =cudf.Series(
    nvtext.ngrams_tokenize(
        s._column.nvstrings, delimiter=''
    )
)
new = s.str.ngrams_tokenize(delimiter='')
print(old)
print(new)
Series([], dtype: object)
0             this_.
1    ._fs,.ds,.fefem
dtype: object
```
```python
import nvtext
import cudf
​
s = cudf.Series(["this .   fs,.ds,.fefem", "hello", ""])

old =cudf.Series(
    nvtext.ngrams_tokenize(
        s._column.nvstrings
    )
)
new = s.str.ngrams_tokenize()
print(old)
print(new)
0             this_.
1    ._fs,.ds,.fefem
dtype: object
0             this_.
1    ._fs,.ds,.fefem
dtype: object
```

**Comment by davidwendt** [comment]
I think this is a bug in the original nvtext version of `ngrams_tokenize()` and `tokenize()` for that matter. The empty string delimiter was intended to tokenize on whitespace for all the tokenize methods (as well as split/rsplit, etc) as implemented in cudf now.
@beckernick  Do you think there is value in supporting the original nvtext version which just returns an empty column?

**Comment by kkraus14** [comment]
cc @beckernick for the question

**Comment by harrism** [comment]
@beckernick ping?

**Comment by beckernick** [comment]
I think we probably don't need to return an empty column, so it sounds like there is no action needed here given the empty string delimiter is intended to split on whitespace.
