### ISSUE TITLE
[QST] How to handle partition table on AWS (s3) 

### ISSUE THREAD

**Issue by jeanmidevacc** [rapidsai/cudf#4637]
**What is your question?**

Hello Rapidsai , 

Thanks for the great library that you have built. I am contacting you because I have a question on the management of partition table that can be stored on S3.

Currently cudf can handle multiple files from a specific location on s3
![image](https://user-images.githubusercontent.com/23313992/77205966-5d55d400-6acc-11ea-9227-b296623a8440.png)

But in the case, if I have a table partitioned by a specific column and for each partition, I have a "folder" that is containing parquet files like in the previous statement
![image](https://user-images.githubusercontent.com/23313992/77206069-870efb00-6acc-11ea-9121-5635672b6dbc.png)

I build a script that can list all the files in the different "folders" but at the ingestion in the cuDF nothing is coming out (it's taking a very long time, I didn't see the end of the collection).

What could be the best way to handle this situation. ?

For the configuration, I have p3 2xlarge, the last version of rapids.ai and my table to read has only 180 000 000 records. To be honest maybe that that partitioning is not optimal but I wanted to have your opinion on that point.

Regards

**Comment by kkraus14** [comment]
@rjzamora can you advise on the best way to handle reading this type of partitioning from `dask-cudf`? I know this functionality is relatively new.

**Comment by rjzamora** [comment]
@jeanmidevacc - Is it possible to say a little more about the script you are using to ingest the parquet data?  Can you share the specific commands you are using?

**Comment by jeanmidevacc** [comment]
Ok so I am going to share with you some code.

Ths situation as I said I have a bucket with "subfolders". and I am using dask dataframe.

To read and store the content of one subfolder I am using this command
```{python}
import dask.dataframe as dd
dfd_ratings = dd.read_parquet('s3://bucket/subfolder0/subfolder1/subfolder2/', engine='pyarrow')
```
with subfolder1 the subfolder that will contain all the files of my table, so in this case subfolder2 is a specific partition of my table with multiple files inside (screenshot 1).

I was expecting that doing that
```{python}
import dask.dataframe as dd
dfd_ratings = dd.read_parquet('s3://bucket/subfolder0/subfolder1/', engine='pyarrow')
```
Will read all the files in subfolder1 but the requests is taking too long.

I try another path by providing directly the list of files with a small function that I built with boto3  to list all the parquet files in s3://bucket/subfolder0/subfolder1/ . But even with the list in dd.read_parquet() without success, the request looks stuck (running half a day without success, but no crash).

I have currently around 4700 files for this table.

I tried another approach with blazingsql, but even in this case I didn't managed to read the files by following [this instruction](https://twitter.com/blazingsql/status/1214651455681904640?s=20) (but I think that I am missing something with this package).

So you talk about maybe using dask-cudf @kkraus14, can it maybe help me for that.

I will like to thank you for your reactivity, really appreciate it.

**Comment by jeanmidevacc** [comment]
This morning after the hint on using dask-cudf , I try to apply it with this commandline 
```{python}
import dask_cudf
dfd_ratings = dask_cudf.read_parquet('s3://bucket/subfolder0/subfolder1/')
print(len(dfd_ratings))
```

Still frozen after 4 hours

**Comment by kkraus14** [comment]
Does the Dask status page show tasks running in doing this? If you're trying to read a large number of large parquet files that could be a ton of very non-trivial IO where reading the data from S3 is bottlenecking you in general.

**Comment by rjzamora** [comment]
In dask_cudf, the planning (read_metadata) stage of `read_parquet` is mostly the same as the `pyarrow`-based code in dask.dataframe.  Pyarrow *should* be able to handle the nested structure you describe, but I'll need to double check and follow up.

Assuming the file/directory structure is not a problem,  I expect that you are still missing a global `"_metadata"` file.  Therefore, dask will need to parse the footer metadata of every file in the dataset before even building the task graph to read the data.  This can be painfully slow on S3 when there are a large number of files.

**Comment by jeanmidevacc** [comment]
Hello @kkraus14 and @rjzamora thanks for your feedback.

@kkraus14 I am going to have a look on the dask status page and see what is happening.

@rjzamora Yes I understand your point, I am not sure how I can build this `_metadata` file but I am going to investigate on that.

**Comment by kkraus14** [comment]
Closing this as stale. If this is still an issue feel free to reopen.
