### ISSUE TITLE
librmm_cffi module missing from rapidsai/rapidsai:latest Docker image

### ISSUE THREAD

**Issue by SharplyUnclear** [rapidsai/cudf#4648]
**Describe the bug**
I am using a Docker image (docker pull rapidsai/rapidsai:latest) and can't find the librmm_cffi module when accessing the system using a Jupyter notebook.

![Screenshot from 2020-03-22 23-33-33](https://user-images.githubusercontent.com/3503922/77265810-a2793200-6c95-11ea-86b6-72057ea5f8a6.png)

**Steps/Code to reproduce bug**
Fire up Jupyter notebook. Enter the following into a cell:
from librmm_cffi import librmm

**Expected behavior**
That the module is found

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
$docker pull rapidsai/rapidsai:latest
$docker run --gpus all --rm -it -v "$PWD":/tmp/working -w=/tmp/working -p 8888:8888 rapidsai/rapidsai:latest

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
I cannot find this script inside the Docker image.
Here is the nvidia-smi output:
![Screenshot from 2020-03-22 23-36-07](https://user-images.githubusercontent.com/3503922/77265933-f7b54380-6c95-11ea-8878-9bc5f0a26a38.png)

**Additional context**
I installed the nvidia-cuda-toolkit in the hope that might fix things.

**Comment by SharplyUnclear** [comment]
My LD_LIBARARY_PATH contains **/usr/local/cuda/lib64**  
However, this resolves to **targets/x86_64-linux/lib** - which does not point to anything.
I suspect this is the problem - what changes should I make?

**Comment by jrhemstad** [comment]
`librmm_cffi` is really old and as far as I know, shouldn't be used. Is there documentation or an example that is still showing it used?

**Comment by SharplyUnclear** [comment]
Yes, the Accelerating Data Science Workflows with RAPIDS training that I purchased and followed on-line yesterday. I am trying to replicate it in my own environment - use it as a best-practice template.

https://courses.nvidia.com/courses/course-v1:DLI+L-DS-01+V1/course/

**Comment by joshwyatt** [comment]
@SharplyUnclear we are releasing a major upgrade to that DLI course this week, which will be in line with rapidsai/rapidsai:latest. I'd be happy to set you up with an early release, and will reach out to you via email.

**Comment by SharplyUnclear** [comment]
Thank you. I am happy to run the training (on my own environment) and field test it actively for you.

**Comment by kkraus14** [comment]
Thanks @joshwyatt! Closing this as it's resolved.
