### ISSUE TITLE
[DOC] Dictionary column factory method incorrectly specifies null mask behaviour

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#4658]
## Report incorrect documentation

**Location of incorrect documentation**
https://github.com/rapidsai/cudf/blob/1b9406816de3dbaf9e36811e5fd40d305b5fe087/cpp/include/cudf/dictionary/dictionary_factories.hpp#L72-L74

**Describe the problems or issues found in the documentation**
The documentation says the null mask is copied from the indices column whereas the very next line says indices cannot be nullable

**Steps taken to verify documentation is incorrect**
Read the implementation
https://github.com/rapidsai/cudf/blob/1b9406816de3dbaf9e36811e5fd40d305b5fe087/cpp/src/dictionary/dictionary_factories.cu#L61

**Suggested fix for documentation**
I'd prefer if the null mask was taken from indices column as it would simplify things. e.g. in testing, we wouldn't have to make a null mask separately. We could make a `fixed_width_column_wrapper<int32_t>` with nulls to construct a dictionary column.

**Comment by davidwendt** [comment]
There are 2 `cudf::make_dictionary_column` functions. This one
https://github.com/rapidsai/cudf/blob/1b9406816de3dbaf9e36811e5fd40d305b5fe087/cpp/include/cudf/dictionary/dictionary_factories.hpp#L56
uses the null-mask from the indices column. The one referenced in the description takes a null-mask as a separate parameter.

The line from https://github.com/rapidsai/cudf/blob/1b9406816de3dbaf9e36811e5fd40d305b5fe087/cpp/include/cudf/dictionary/dictionary_factories.hpp#L72
should have been part of the doxygen for the first one and not the second one.

**Comment by devavret** [comment]
Ok so I'll remove the offending line.

**Comment by davidwendt** [comment]
> Ok so I'll remove the offending line.

Actually, if you can _move_ it up to the other API that would be great.

**Comment by davidwendt** [comment]
Fixed in #4679
Not sure why auto-close of issues is not working here.

**Comment by kkraus14** [comment]
@davidwendt likely because `branch-0.14` is not yet the default branch.
