### ISSUE TITLE
.drop (and other methods) should perfectly match Pandas method signatures.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#466]
When we removed drop_column, we talked about whether or not inplace should be available as an argument. Should it?

More importantly, it seems to me and others that all cudf methods should exist to mirror Pandas at this time, so we should endeavor to make all signatures match Pandas exactly. Supporting pyarrow perfectly, or Spark perfectly, can be an additional library that we build as the project matures. Opinions?

**Comment by UmashankarTriforce** [comment]
I would like to know if this issue is still open. If yes, may I know what needs to be done in this issue as I wish to work on this issue!

**Comment by thomcom** [comment]
I'd start by taking a look to see if our `.drop` signature matches Pandas or not, and creating a PR to get a better match if not. There's also a much larger ongoing discussion about matching the rest of Pandas APIs, which is probably better suited by creating a new issue.

**Comment by kkraus14** [comment]
I'm going to close this issue and recommend we open issues on a per function basis when things are not matching in a way that impacts / breaks things.
