### ISSUE TITLE
[DOC] Update 10 minutes to dask-cudf

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#4665]
### Report improvements to documentation

**Location of incorrect documentation**
[Link](https://rapidsai.github.io/projects/cudf/en/0.12.0/10min.html)

**Describe the problems or issues found in the documentation**
- `10 minutes to dask-cudf` should be refreshed (in 0.14). Here are a couple of suggestions, but it would be good to read through and update content wherever applicable.
  - Reduce the number of examples that perform `df.compute()` which will not work with larger datasets [(example)](https://github.com/rapidsai/cudf/blob/branch-0.13/docs/cudf/source/10min.ipynb?short_path=c1a961d#L5598).
  - Update `to_parquet` segment since we support GPU accelerated parquet writing.

**Comment by GregoryKimball** [comment]
Thanks @shwina for your changes in #10531, next time we dig into the docs for "10 Minutes to cuDF and Dask-cuDF", do you think these points are worth addressing?
