### ISSUE TITLE
[FEA] `SUM_OF_SQUARES` aggregation for groupby in libcudf

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#4667]
It would be great if libcudf groupby could provide a `SUM_OF_SQUARES` aggregation.

**Additional context**
While Pandas does not have a `sum_of_squares` aggregation explicitly, it looks like the `dask_cudf` implementation of `groupby.std` could benefit from a `sum_of_squares` aggregation greatly (cc: @quasiben).

**Comment by karthikeyann** [comment]
Adding SUM_OF_SQUARES in hash groupby causes ptxas compiler segfault. (similar to crash faced by @davidwendt)
https://github.com/rapidsai/cudf/blob/6828e2ce559569c55b8f04e660a93ab4c21f25b4/cpp/src/groupby/hash/groupby.cu#L74

**Comment by harrism** [comment]
If this does not happen in CUDA 11.x, then you can add it with an include guard to workaround the compiler issue.

**Comment by karthikeyann** [comment]
Even with "closes" keyword in PR #7362 , this issue is not closed automatically!

**Comment by davidwendt** [comment]
> Even with "closes" keyword in PR #7362 , this issue is not closed automatically!

My understanding is that this only works if the PR's branch matches the default branch and our default branch is still 0.18.
