### ISSUE TITLE
[BUG] Remove linking against `gtest_main` in unit tests

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#4685]
**Describe the bug**

After https://github.com/rapidsai/cudf/pull/4616 was merged, it requires libcudf unit tests to add the macro `CUDF_TEST_PROGRAM_MAIN()` at the end of the file to insert a custom `main()` function that will configure RMM for all of the tests in the file.

Ideally, if you forget to add this, your file will fail to compile. However, by linking against `gtest_main`, your file will still happily compile, but use GTest's provided `main()` instead of the custom libcudf one.

https://github.com/rapidsai/cudf/blob/557d106a4d5542a9ab3c04e3f48feb05d90547ee/cpp/tests/CMakeLists.txt#L55

We should remove linking test files against `gtest_main` so that if you forget to add `CUDF_TEST_PROGRAM_MAIN()` your test will fail to compile.

**Comment by jrhemstad** [comment]
In fact... @vuule I'm a bit surprised we aren't getting compiler errors about multiple definitions of `main()`.

**Comment by vuule** [comment]
I made the bulk of changes for this one, but the merge will be blocked on #4742
