### ISSUE TITLE
[BUG] java.lang.UnsatisfiedLinkError: ai.rapids.cudf.Rmm.isInitializedInternal()Z

### ISSUE THREAD

**Issue by rui911013** [rapidsai/cudf#4702]
when i "mvn clean install" java module, the libcudfjni.so is generated correctly ,but  when it run test module, all of the test case is error ,the error info is below:
==================
java.lang.UnsatisfiedLinkError: ai.rapids.cudf.Rmm.isInitializedInternal()Z
	at ai.rapids.cudf.Rmm.isInitializedInternal(Native Method)
	at ai.rapids.cudf.Rmm.isInitialized(Rmm.java:69)
	at ai.rapids.cudf.CudfTestBase.afterAll(CudfTestBase.java:51)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeAfterAllMethods$7(ClassTestDescriptor.java:253)
==================

my relative configuration info are below 
CentOS 7.4
cudf-0.12
GPU- P4
CUDA-10.2
gcc-6.2
jdk -1.8

btw, before ,i built the libcudf.so successfuly hardly because i must built it in offline environment
please help me 
thanks

**Comment by rui911013** [comment]
I saw some relatively pr in #3228 ,and I guess my problem is similar to it ,BUt i don'g know how to modify my error

**Comment by jlowe** [comment]
Typically when UnsatisfiedLinkError occurs it's because one of the dependencies needed by the shared libraries bundled in the cudf.jar cannot be found.  You had mentioned the jar was built elsewhere.  Does the CUDA runtime version used to build the JAR match the CUDA runtime on the machine where the issue occurs?

If possible to do so, running with `LD_DEBUG=libs` set in the environment of the process can help narrow down which symbol lookup is failing and causing the native library to not load.

**Comment by rui911013** [comment]
> Typically when UnsatisfiedLinkError occurs it's because one of the dependencies needed by the shared libraries bundled in the cudf.jar cannot be found. You had mentioned the jar was built elsewhere. Does the CUDA runtime version used to build the JAR match the CUDA runtime on the machine where the issue occurs?
> 
> If possible to do so, running with `LD_DEBUG=libs` set in the environment of the process can help narrow down which symbol lookup is failing and causing the native library to not load.

thank you very much, I have solved this problem by add the extra dependency libboost_filesystem.so. 
 I will close this issue .
