### ISSUE TITLE
[FEA] positive modulo -- pmod functionality

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#4708]
cudf currently supports Mod and PyMod -- modulo operator matches the Python `%` behavior. SQL additionally has a `pmod` operator that results in positive values using the following logic `((a % b) < 0) ? ((a % b) + |b|) : (a % b)` that we'd like to utilize.

Here's a summary of current/desired functionality:
Tests
24854.55893 % 90770.74881, 79946.87288 % -15456.4335, 7967.43488 % 32213.22119, -86099.68377 % 36223.96138, 63477.14374 % 98993.65544, 13763380.78173 % 19869268.744, 8677894.99092 % 4029109.83562, -86099.68377 % -15456.4335

Python Mod
`24854.55893, -12791.72812, 7967.43488, 22572.20037, 63477.14374, 13763380.78173, 619675.3196799997, -8817.516270000007`

cudf Mod
`24854.55893, 2664.7053799999994, 7967.43488, -13651.761010000002, 63477.14374, 1.376338078173E7, 619675.3196799997, 8817.516270000007`

cudf PyMod
`24854.55893, -12791.72812, 7967.434879999997, 22572.20037, 63477.14374, 1.376338078173E7, 619675.3196799997, -8817.516270000007`

Spark pmod (desired funtionality)
`24854.55893, 2664.7053799999994, 7967.43488, 22572.20037, 63477.14374, 1.376338078173E7, 619675.3196799997, 6638.917229999992, 8817.516270000007`

**Comment by rwlee** [comment]
@harrism, sorry I forgot to the Spark label. This is not related to Python, we originally thought pmod was short for python-modulo instead of positive-modulo

**Comment by sriramch** [comment]
@rwlee 

@razajafri pointed out that the implementation may not be correct.

- is your cudf mod result for `-86099.68377 % -15456.4335` (last item) a positive value? afaict, it should be a negative value

- where did you get the definition of pmod? is this the sparks definition of pmod or is this what we need (for some reason not documented here)?

from what i can gather from your requirement, cudf mod returns the sign of the dividend (c++11 functionality) and pymod returns the sign of the divisor. hence, you want to somehow unify all this to make sure that it returns a positive value always. if so, then what about the case when both of them are negative? according to [this](https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/arithmetic.scala#L608) scala implementation (which should honor sign rules like c++11), pmod of 2 negative values should return a negative value. however, what you seem to be expecting is a positive value. [this](https://docs.microsoft.com/en-us/dotnet/api/microsoft.spark.sql.functions.pmod?view=spark-dotnet) definition seems vague as well.

can you please confirm? 

cc: @razajafri

**Comment by razajafri** [comment]
Thanks @sriramch as discussed offline, [this](https://gitlab-master.nvidia.com/nvspark/spark/-/blob/nvmaster/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/arithmetic.scala#L608) is what we want.

**Comment by rwlee** [comment]
@sriramch

`-86099.68377 % -15456.4335` should indeed be negative

I made a mistake when copying over the last test result which caused my proposed logic to be off. The spark logic that @razajafri linked is the what we would like to replicate.
