### ISSUE TITLE
[BUG] DataFrame __setitem__ alignment issue with assigning series with unsorted index.

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#4709]
**Describe the bug**
Assigning a series with unsorted index to existing column in a dataframe with similar index fails to align the column as per index.
**Steps/Code to reproduce bug**
```
>>> import cudf
>>> df=cudf.DataFrame({"A":[1, 3, 2, 5, 3]}, index=[3, 2, 4, 1, 5])
>>> sr=cudf.Series([4, 3, 5, 6, 1], index=[3, 4, 1, 2, 5])
>>> df['A']=sr
>>> print(df)
   A
3  5
2  6
4  4
1  3
5  1
```

**Expected behavior**
```
   A
3  4
2  6
4  3
1  5
5  1
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: source

**Additional context**
This is due to join in `_align_to_index` [here](https://github.com/rapidsai/cudf/blob/f90b91e9f1e77b69f11c7027caf05867cdf9f8bf/python/cudf/cudf/core/series.py#L2492), which sorts the output. As this output is getting assigned to dataframe in `__setitem__`  [here](https://github.com/rapidsai/cudf/blob/f90b91e9f1e77b69f11c7027caf05867cdf9f8bf/python/cudf/cudf/core/dataframe.py#L566) without proper knowledge of the index, the order gets messed.

**Comment by rgsl888prabhu** [comment]
You wouldn't see this bug as it has been taken care with a less efficient approach, once we get #4574 we can address this issue with better solution, so keeping this issue alive.

**Comment by kkraus14** [comment]
Closing as this is no longer an issue and there's room for additional optimization in #4574
