### ISSUE TITLE
[QST/Discussion] Reorganize pytests

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#4730]
The pytests directory currently has a flat structure: `test/all_tests`. 
It might make sense to move tests to subfolders based on the operations/modules they might be most relevant to? Eg: All `IO` related tests can move to `io/tests` like the pattern followed by [dask](https://github.com/dask/dask/tree/master/dask/dataframe/io) or to `tests/io` like [pandas](https://github.com/pandas-dev/pandas/tree/master/pandas/tests).

**Comment by vuule** [comment]
I think for cuIO the preferable path would be `tests/io/file_format` so it's easier to selectively run groups of related tests from different files.
We can go ahead and make this change for cuIO tests in 0.19, unless there are objections to this structure.

**Comment by vyasr** [comment]
The plan for this will be discussed and decided upon in #11199

**Comment by vyasr** [comment]
Closing in favor of #15723, which is a bit updated and hopefully more discoverable.
