### ISSUE TITLE
[BUG] nan_as_null is not working in certain case in creation of Series

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#4740]
**Describe the bug**
nan_as_null is not working in Series `__init__` in certain cases as shown below.

**Steps/Code to reproduce bug**
```
>>> import cudf
>>> import numpy as np
>>> cudf.Series(cudf.utils.utils.scalar_broadcast_to(np.nan, size=10))
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
6   NaN
7   NaN
8   NaN
9   NaN
dtype: float64

```

**Expected behavior**
```
0    null
1    null
2    null
3    null
4    null
5    null
6    null
7    null
8    null
9    null
dtype: float64

```

**Comment by kkraus14** [comment]
We need to be careful with this one, since `nan_as_null=True` is the default, if we run a kernel every time we pass a `Column` into this it would be unnecessarily expensive.

**Comment by rgsl888prabhu** [comment]
Should we make nan_as_null to be False by default ?

**Comment by kkraus14** [comment]
> Should we make nan_as_null to be False by default ?

No because that misaligns expectations when coming from Numpy / Pandas.

**Comment by rgsl888prabhu** [comment]
So, how about handling it only if we are getting it from non-cudf elements ? I think this is the way currently it's handled apart from some places.
