### ISSUE TITLE
cudf 0.4 build error due to cmake using default c/c++ compilers

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cudf#475]
I was building cudf 0.4.0 on the psgcluster login node, which is Centos 7.5.1804, and encountered building error while compiling two new utilities header files, cpp/src/utilities/wrapper_types.hpp and type_dispatcher.hpp. 

The commands I am using are: (the same commands i was using to build cudf 0.3 without any errors)
module load gcc/5.4.0
module load cuda/9.2.88.1
source activate cudf_dev
cd cpp
mkdir BLD
cd BLD
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
make -j

After checking with Jake Hemstad, we found the errors are because cmake is not using 5.4 version of c/c++ compiler in $PATH. Instead, cmake picks up default /usr/bin/c++, version 4.8.5. The solution is to either set CC/CXX env variable right before cmake, or adding options to cmake, i.e., 
CC=/rightPath/gcc CXX=/rightpath/g++ CUDAHOSTCXX=/rightpath/g++ cmake ..
or
cmake -DCMAKE_CXX_COMPILER=/rightpath/g++ -DCMAKE_C_COMPILER=/rightpath/gcc .. 

Doris 

## Reporting a bug

- [x ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by jrhemstad** [comment]
Thanks Doris! We'll try and get this figured out.

**Comment by kkraus14** [comment]
This was resolved in the refactor, closing.
