### ISSUE TITLE
[BUG] Max aggregate returns invalid results for a float32 column with nans

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#4754]
**Describe the bug**
Running max aggregate on a table returns invalid result. I haven't gotten around to writing a unit test for this but can do if so required 

**Steps/Code to reproduce bug**
Create the following table 
```
scala> spark.sql(""select * from floatsAndDoubles"").show
+-----+------+
|float|double|
+-----+------+
|  NaN|   NaN|
| 1.02|   NaN|
|  NaN|   4.5|
+-----+------+
```

running an aggregate(max) op on the double-column will result in the following table 

```
+----------+-----------+
| float    |max(double)|
+----------+-----------+
| 1.020000 | -179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000.000000 |
| NaN      | 4.500000  |
+----------+-----------+
```

**Expected behavior**
It should output this 

```
"scala> spark.sql(""select float, max(double) from floatsAndDoubles group by float"").show
+-----+-----------+
|float|max(double)|
+-----+-----------+
| 1.02|        NaN|
|  NaN|        NaN|
+-----+-----------+"
```

**Additional context**
For context here is what aggregate(sum) does in cudf
```
+------+-----+
|float | sum |
+------+-----+
| 1.02 | NaN |
| NaN  | NaN |
+------+-----+
```

**Comment by harrism** [comment]
@razajafri Please provide a title for this issue.

**Comment by jrhemstad** [comment]
Why is there an expectation that `NaN` is greater than other values?

**Comment by jrhemstad** [comment]
Closing this as redundant with https://github.com/rapidsai/cudf/issues/4753

**Comment by jlowe** [comment]
> Why is there an expectation that NaN is greater than other values?

Because that would be consistent with the sorted order.  See https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/tests/table/row_operators_tests.cu#L43-L44
