### ISSUE TITLE
[BUG] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

### ISSUE THREAD

**Issue by starlett3** [rapidsai/cudf#4757]
I'm running the notebooks/cuml/linear_regression_demo notebook.
On the line:
`X_cudf = cudf.DataFrame.from_pandas(X_train)`

I get error:
> ERROR:Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

I'm running this on:
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
on a machine with four V100s
Driver Version: 410.104      
CUDA Version: 10.0 

I ran the Jupyter notebook inside a docker container on the machine:
`docker run --runtime=nvidia --rm -it -p 9991:8888 -p 9992:8787 -p 9993:8786 -v /home/xxx/WORKSPACE/rapids-kml:/opt/gpudb/kml rapidsai/rapidsai:cuda10.0-runtime-ubuntu16.04 `

**Comment by kkraus14** [comment]
This is stale and should be resolved so closing.
