### ISSUE TITLE
DataFrame.to_arrow uses the same host pointer for index and data column

### ISSUE THREAD

**Issue by nsakharnykh** [rapidsai/cudf#476]
## Reporting a bug

- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [x] I have included the version or commit hash I am using for reference.
commit 7aa3799e73948899a85e70bc73d3cea50b65dff1
- [x] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
Ubuntu, 4.15.0-041500-generic, Quadro GV100
- [x] I have included the following version information for:
      Arrow 0.10.0, cmake 3.13.1, CUDA 10.0, gcc/g++ 5.4, Numpy 1.15.2, Pandas 0.20.3, Python 3.5
- [x] I have included below a minimal working reproducer
```
import cudf
df = cudf.DataFrame([('a', list(range(10)))])
df.to_arrow()
```

To reproduce, just go to `cudf/python/cudf/dataframe/numerical.py` and add the following line:
```
        print(memoryview(data))
```
after
```
        data = pa.py_buffer(self.data.mem.copy_to_host())
```
in `to_arrow()` function.

Then run the test attached above, you'll see that the memory pointer is the same for the index & the data column:
```$ python test_to_arrow.py 
<memory at 0x7f2b100597c8>
<memory at 0x7f2b100597c8>
```

**Comment by kkraus14** [comment]
I don't think this is an issue, I'm not sure on the semantics of memoryview but see this:
```python
import numpy as np
import pyarrow as pa

buf1 = pa.py_buffer(np.array([1,2,3]))
buf2 = pa.py_buffer(np.array([4,5,6]))
bufs = (buf1, buf2)

for i in bufs:
    print(i.address)
    print(memoryview(i))
```

```
59303616
<memory at 0x7fb91f86a108>
134777472
<memory at 0x7fb91f86a108>
```
The memory addresses of PyArrow buffers are clearly different so I think we're okay. I imagine we'd see the same behavior when adding the print statement to `numerical.py`. Closing this as a non-issue.
