### ISSUE TITLE
[DOC] Document supported NVIDIA GPUs and CUDA versions for cuDF

### ISSUE THREAD

**Issue by saifrahmed** [rapidsai/cudf#4791]
I realize RAPIDS overall (especially model fitting, etc.) requires a certain level (or above) of NVIDIA GPU chips -- but curious what the cuDF-specific requirements are? Just via trial and error, I already noticed it seems to work on a broader set of chips than RAPIDS overall.

Is there a compatibility matrix available specifically for cuDF and which chips are supported?

**Comment by jrhemstad** [comment]
We currently support CUDA 10 and newer and compute capability 6.0 and newer (Pascal+).

**Comment by harrism** [comment]
Seems this is not documented anywhere  I can find. Let's change this into a doc bug.

**Comment by harrism** [comment]
#4953 helps, but it doesn't really solved the "compatibility matrix" question of this bug...

The only thing about supported GPUs is "Pascal architecture or better". Most users are not going to know what that means. We should add "Compute Capability 6.0 or higher".
