### ISSUE TITLE
Category dtype on read_csv not consistent between pandas and cudf

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#480]
## Feature request
Category dtype on read_csv not consistent between pandas and cudf

## Reporting a bug
The 'category' dtype on read_csv in pandas does a 1up encoding of the strings in the field.  The 'category' dtype on read_Csv in cudf does a hash encoding of strings in the field.

While I believe the 'hash' dtype to be a better implementation for XGBoost, the implementations should likely be the same as pandas for compatibility.

Suggesting adding a 'hash' category dtype to clearly indicate the use of hash encoding.

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by datametrician** [comment]
I think this is a feature request more than a bug.

**Comment by datametrician** [comment]
To elaborate, we have to make some modifications from pandas for performance reasons. We try hard to balance expected behavior between pandas and other data processing frameworks, and create something pythonic that many users (including from other ecosystems) would appreciate.

**Comment by kkraus14** [comment]
This also moves away from the Arrow specification which also uses an enumeration approach, but as mentioned using a deterministic hashing gives large performance benefits, especially in distributed use cases as it prevents having to synchronize the categories of the partitions. Going to leave this open but I don't see this as high priority.

**Comment by GregoryKimball** [comment]
I'd like to omit discussion of implementation details such as hash versus one-hot encoding from the docs for now. Please feel free to raise an issue if you find cases where pandas and cudf category types do show the same behavior.
