### ISSUE TITLE
Support drop method  in cudf for portability with pandas

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#481]
## Feature request
Support drop method  in cudf for portability with pandas

## Reporting a bug
The drop method is not supported in cudf.  For compatibility with pandas, the method should be introduced into cudf with support for the inplace argument.  
```
imports cudf
<...read_csv code here...>
df.drop_column('current_loan_delinquency_status')
```
```
imports pandas as pd
<...read_csv code here...>
df.drop('current_loan_delinquency_status', axis=1, inplace=True)
```

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by harrism** [comment]
This is fixed by #439 which has already been merged to branch-0.5 (which means it will be in the upcoming 0.5 release).
