### ISSUE TITLE
[QST] cuDF Query is too slow

### ISSUE THREAD

**Issue by GoyalMansi** [rapidsai/cudf#4810]
Hi All,

I recently ported a script to use cuDF dataframes in place of pandas dataframes. On comparing the time taken by API calls, I found panda APIs to be doing much better. Honestly, I am confused by seeing such results. I am not sure if I have done it correctly, as this is my first time using cuDF. For your reference:

1. temp = cudf_df.query('Id == @i')
The Id column is int64 type, dataframe contains around 12 rows.
This query took:  **0:00:01.262744**

2. temp=pandas_df[pandas_df['Id']==i]  
The Id column is int64 type, dataframe contains data identical to cudf dataframe.
This query took:  **0:00:00.006388**

**System Configuration**
cuDF package version: cudf-cuda100  0.6.1 
NVIDIA CUDA toolkit version:  CUDA Version 10.0.130 with CUDA Patch Version 10.0.130.1
GPU Name: Titan RTX
Operating System: Linux
Architecture: x86_64
Distribution: Ubuntu
Version: 18.04.3 

cudf query API is almost 200 times slower. Could someone please point me in the right direction? 
Thanks in advance!

**Comment by harrism** [comment]
thanks for your question! You probably need thousands of rows minimum to see a speedup. For small data frames, the overhead of launching a kernel on the GPU will be larger than the overhead of calling a function on the CPU. 12 rows is miniscule.

**Comment by GoyalMansi** [comment]
Thank you, that does make a lot of sense. Maybe, I need to find a better use case for cuDF then. Thanks Mark for the reply!

**Comment by kkraus14** [comment]
@GoyalMansi additionally it looks like you installed an old version of cuDF via pip as opposed to the latest version from conda. Would highly recommend installing from conda if/when you try cuDF again!
