### ISSUE TITLE
[DISCUSSION] Python `cuDF.dtype` 

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#4823]
# Motivation

With Pandas 1.0 comes the introduction of several new nullable datatypes, including:

- [nullable integer](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html), which can be used as `pd.Int64Dtype()`, `pd.Int32Dtype()` and so on and so forth. 
- [nullable string](https://pandas.pydata.org/pandas-docs/stable/user_guide/text.html#text-types), declared as `pd.StringDtype()`
- [nullable boolean](https://pandas.pydata.org/pandas-docs/stable/user_guide/boolean.html)

In addition, `pd.NA` has been added as a "universal" null object. 

Since cuDF columns are nullable regardless of the datatype, it could be argued that the new Pandas datatypes behave more like the way that data in cuDF does right now. Currently, when we go from nullable cuDF data to Pandas data (or more generally, pure Python data), various things can happen:

- If the data is integer typed, we'll get a sentinel value (`-1` right now)
- If the data is float typed, we'll get Python float `nan` in the null slots
- If the data is string typed, we'll get Python `NoneType`.
- If the data is bool typed, we'll get an `object` series with `NoneType`s.

When we move data back and forth from pandas, we might want to be able to ingest the nullable datatypes and end up with cuDF columns that have nulls in the right places, as well as yielding pandas nullable types with `pd.NA` in the correct spots when going the other way. 

In addition it may no longer be appropriate to label our data with NumPy types, e.g. `column.dtype`. One thought is to use the Pandas nullable types instead, however that leaves `float` as an odd type that would have to stay a numpy type. In addition, many new branches of code would have to be written to accommodate the behavior of the pandas type objects themselves as opposed to the numpy ones.

# `cuDF.dtype` 
What is being proposed is a dedicated dtype object that could contain the logic we need both to operate internally as well as interface with external libraries, such as numpy, pandas, and pyarrow. Such an object would:

- Be attached as `.dtype` to relevant cuDF objects
- Computes all its useful attributes at init, such as kind and size. We then wouldn't need to ever call things like `is_categorical_dtype` ever again. We'd write the code such that any incoming numpy or pandas types would be converted to `cudf.dtype` objects and then would follow a single codepath thereafter. 
- Contains all it's mappings to libcudf types, pyarrow types, numpy types, and pandas types (currently defined in multiple places)
- Compares sensibly with datatypes in other libraries
- Is able to produce a cuDF scalar with the appropriate `cuDF.dtype` similar to NumPy, e.g. `cudf.dtype('int')(0)` is a `cudf.Scalar` with `cudf.dtype('int')` dtype. 

I am curious to know what people think of this and any proposed behavior that we'd want to include if we move forward.

**Comment by kkraus14** [comment]
Pandas issue discussing nullable Float types: https://github.com/pandas-dev/pandas/issues/32265

**Comment by kkraus14** [comment]
> * Is able to produce a cuDF scalar with the appropriate `cuDF.dtype` similar to NumPy, e.g. `cudf.dtype('int')(0)` is a `cudf.Scalar` with `cudf.dtype('int')` dtype. Do Pandas dtypes have a nice way to specify this?

Not sure on the API of `cudf.dtype('int')(0)`, numpy does this as `np.dtype('int').type(0)` for example.

> I am curious to know what people think of this and any proposed behavior that we'd want to include if we move forward.

I think we should iron out what the proposed behavior for cuDF is with regards to `int64` vs `Int64Dtype` and other non-nullable dtypes. I don't think we have any plans / intentions to support the non-nullable Pandas types logic so we should make it clear that we'll end up promoting those.

> In addition, `pd.NA` has been added as a "universal" null object.

We should write up what our plan is regarding this. Currently we have `cudf.Scalar` which can be nullable, but it's strongly typed so it's not quite equivalent to `pd.NA`. We should probably also have `cudf.NA` for compatibility reasons.

**Comment by brandon-b-miller** [comment]
Both NumPy and the new Pandas types can ingest a scalar and produce (some kind of) converted scalar. The pandas types yield numpy types, i.e. `pd.Int64Dtype().type(0)` gives us a scalar `0` with `numpy.int64` type, and `pd.Int8Dtype().type(0)` produces a `numpy.int8` dtype. The string dtype produces a Python `str`, and `pd.BooleanDtype()` produces `np.bool_` typed scalars. In our picture, we might produce `cudf.Scalar`s with the corresponding `cudf.dtype` from all of these.

RE: `int64` vs `Int64Dtype`, I think in some ways we're already implicitly promoting the datatypes, the fact that we label a nullable series with `numpy.int64` seems somewhat misleading in that our data won't behave the same way a `numpy.int64` array does. It's simpler in my opinion for users to get used to expecting to work with `cudf.dtype` in our ecosystem, while still allowing people to pass NumPy and Pandas datatypes around for compatibility and interfacing with other libraries. That way our datatypes obey our own set of rules, which we can of course make as pandas-like as we want (but are not _limited_ to it). As such I don't think we should really 'promote' incoming `numpy.int64` data to `pd.Int64Dtype()`, instead we might promote it to `cudf.int64` which means its own thing, and the same thing is expected for every kind of incoming data. 

As for `pd.NA`, I think that at least some things are straightfoward: If a pandas series has `pd.NA`s in it, we should get `null`s when ingesting it into cuDF. When we send data out of cuDF to pandas, we should get the corresponding nullable pandas type, always, even if our data doesn't actually have nulls. The `cudf.NA` object makes sense only in the scalar context imo. I'm a little fuzzy on the technical details of the typing issue though, I will follow up on that.

**Comment by TomAugspurger** [comment]
I'm sure I've missed discussions, but what's the benefit of introducing a `cudf.dtypes.Int64Dtype()` vs. just using `pandas.Int64Dtype()`?

I understand that for some dtypes like Categorical, you might want to ensure that the categories / codes are stored in GPU memory, or you might want to override specific methods. But for something basic like Int64Dtype I hope that we could share the same dtype implementation.

**Comment by brandon-b-miller** [comment]
@TomAugspurger thank you so much for your thoughts here. From a big picture perspective, we'd like for our dtypes to  share as much of the same implementation/API as possible with pandas. Ideally what we will have in the end is a rather thin wrapper around pandas dtypes, overriding some of the necessary methods as you say. For instance, we might want `.type` to be able to construct GPU backed scalars instead of numpy scalars. 

The problem we've had historically just plugging in pandas nullable types is that a lot of our machinery depends on being able to call `np.dtype(some_object)` and have it work as expected. Moreover, cuDF uses pyarrow types extensively internally, so we end up having to have a lot of branches/dicts mapping types between libraries. On top of that, we have a few dtypes that are not yet supported by pandas, such as `datetime64[ms]` (and millis and seconds, etc). The result is a situation where even if we did take the plunge and switched to:

- pandas nullable dtypes for int types and strings
- numpy types for floats (temporarily), and datetimes/timedeltas
- our own custom dtype for categorical, list, and struct

Now we have a somewhat inconsistent library where a user can't really be sure what to expect when accessing `.dtype` of a cuDF object, and a lot of internal branching and handling that depends on what dtype object can be expected.

The motivation of this work is to unify these things so that both internally and externally, the same code can always be used to work with our dtypes. The problem of course is that numpy is used extensively in the python ecosystem and it simply will not work with anything except actual numpy type objects as I am sure you are aware. 

That said, I do wish I had a better picture of what that would mean for the ecosystem globally and would prefer a solution that involved both us and pandas, and would love to engage with the relevant people on that.

**Comment by vyasr** [comment]
Since this issue was first raised, cuDF has settled on using normal (non-nullable) dtypes to represent all data, even though all data in cuDF is nullable. When pandas 2.0 comes around we'll need to reevaluate since 2.0 is likely to significantly revamp the handling of nulls and missing data, but until then the current approach is the most user-friendly since the pandas nullable dtypes are not widely used nor are they compatible with the rest of ecosystem's dtypes (e.g. numpy/cupy/pyarrow).
