### ISSUE TITLE
[BUG] Context issues when importing cudf in global context with dask-cuda cluster

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#4827]
**Describe the bug**
We have context issues when importing cudf in a global context with dask-cuda cluster. This causes all the `dask_cuda_workers` to point to the same gpu . 

**Steps/Code to reproduce bug**
```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import rmm
# works if i dont import cudf
import cudf
if __name__ == "__main__":
    cluster = LocalCUDACluster()
    client = Client(cluster)
    print(client)
    client.run(
        rmm.reinitialize,
        pool_allocator=True,
        managed_memory=False,# if memory_mode == "default" else True,
        initial_pool_size=30000000000,
    )
    print("initialize call")
    print("success")
```

Trace: https://gist.github.com/VibhuJawa/187650dc2cf9ccc6a919cca1f20f1734

**Work Around**
Import `cudf` in the : 
```python
if __name__ == "__main__":
```

**Additional context**
Slack Thread with discussion: https://nvidia.slack.com/archives/CGLPWR4HJ/p1586206152076500

**Comment by kkraus14** [comment]
This is resolved by using the `RAPIDS_NO_INITIALIZE` or `CUDF_NO_INITIALIZE` environment variable.
