### ISSUE TITLE
[DOC] Create example C++ app using libcudf++ with typical CUDA kernels

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#4829]
Related to #4824, but worth separating into two doc requests.

Some users have existing CUDA C++ codebases with custom kernels. They need examples of how how to hook up a custom CUDA kernel to libcudf++ code.

A useful example would be a C++ application that does the following:
1. Reads a CSV file into a cudf DataFrame
2. Calls a custom CUDA kernel on multiple input columns
3. Writes custom CUDA kernel results into cudf DataFrame output columns

**Comment by harrism** [comment]
I'm not optimistic that this will get prioritized immediately. However we did discuss a goal of adding simple API examples in the C++ docs for each public API, much like other APIs (like C++ STL and Thrust). This would not be a single integrated example.

**Comment by harrism** [comment]
BTW, I find this confusing, because the title is about UDFs, but the description is about calling custom kernels. Would be  good to know which users actually want.

**Comment by antonmks** [comment]
Would be nice to see the examples of 
  a filter applied to a set of columns
  use of copy_if_else 
  group by 
  calling of a custom unary/binary functions

**Comment by randerzander** [comment]
This has been resolved in [rapids-examples](https://github.com/rapidsai/rapids-examples)

**Comment by harrism** [comment]
I don't think `rapids-examples` is the simple example we need of building a C++ app using cmake that links and calls libcudf.

**Comment by randerzander** [comment]
That's why I didn't close #4824 =)

The rapids-examples repo is several more complex use cases.

**Comment by harrism** [comment]
I see. But I think the simple examples for libcudf (including of using UDFs) should be in the libcudf repo so they undergo code review by the libcudf team, as well as CI, and are kept consistent with the API and documentation (and eventually can become part of the documentation).
