### ISSUE TITLE
Cugraph needs header files not installed anymore after refactor

### ISSUE THREAD

**Issue by Iroy30** [rapidsai/cudf#485]
## Feature request

Prior to cuff refactor, files in cugraph used functionalities included by gdf/gdf.h, gdf/errorutils.h and gdf/utils.h which after the refactor have become cudf.h, and other two are in cpp/src/utilities/error_utils.h and cpp/src/utilities/cudf_utils.h  respectively, both of which are not installed. These header files need to be installed (updating CMakelists.txt) for cugraph to find and utilize them (to fix the current build issue).
## Reporting a bug

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by dantegd** [comment]
Could you provide a list of what files are needed in cuGraph? If I remember correctly its at least `error_utils.h` and what used to be `gdf/utils.h`. Any other files?

**Comment by Iroy30** [comment]
files in cugraph use functionalities earlier included by gdf/gdf.h, gdf/errorutils.h and gdf/utils.h which after the refactor have become cudf.h, and other two are in cpp/src/utilities/error_utils.h and cpp/src/utilities/cudf_utils.h  both of which are not installed.

**Comment by kkraus14** [comment]
@Iroy30 is this resolved?
