### ISSUE TITLE
[FEA] df["col"].astype(datetime64[]) should support hours, minutes units.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4855]
Currently, only `ns`, `us`, `ms`, `s` are supported. Other units would be really great to have.

**Comment by beckernick** [comment]
@chinmaychandak could you provide any additional context about the desire for this behavior? I don't believe this exists in pandas.

**Comment by vyasr** [comment]
We already support a wider range of resolutions than pandas does, so unless we see significant sustained interest in expanding that support even further I'm going to say we won't be addressing this issue.
