### ISSUE TITLE
Unable to read a .txt file

### ISSUE THREAD

**Issue by ericmjl** [rapidsai/cudf#486]
## Reporting a bug

- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 

- [x] I have included the version or commit hash I am using for reference: 

v0.4.0 from conda-forge.

- [x] I have included the following environment details:

Ubuntu 16.04, NVIDIA GeForce GTX1080

- [x] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python

Arrow: 0.10.0
cMake 3.5.1
gcc 5.4.0
numpy: 1.15.4
pandas: 0.20.3
python: 3.6.7

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The minimally reproducible error lives in a notebook in a separate GitHub repository: https://github.com/ericmjl/rapids-test/blob/master/cudf-test.ipynb

I get an uninformative GDF error ("GDF_UNSUPPORTED_DTYPE") showing up. Two issues come to mind here.

Firstly, the error message is uninformative as to why there's an error. As the end-user, I am left uninformed as to what exactly in my data is causing the unsupported dtype error. 

Secondly, I am unsure why any of the columns would have an unsupported dtype, given that each column is essentially a float.

Please let me know if there's other things you'd like me to try w.r.t. this dataset, to see if I might be able to uncover other issues.

**Comment by datametrician** [comment]
@BradReesWork would you or someone look into this

**Comment by Iroy30** [comment]
The read_csv dtype argument essentially takes in list of strings as an input and converts it to a gdf datatype. What you want to try is put dtype = ['float64' , 'float64', 'float64', 'float64'] instead of dtype=[np.float64, np.float64, np.float, np.float]. Currently the datatypes supported are reflected by the following code snippet:

gdf_dtype convertStringToDtype(std::string &dtype) {

	if (dtype.compare( "str") == 0) 		return GDF_STRING;
	if (dtype.compare( "date") == 0) 		return GDF_DATE64;
	if (dtype.compare( "date32") == 0) 		return GDF_DATE32;
	if (dtype.compare( "date64") == 0) 		return GDF_DATE64;
	if (dtype.compare( "timestamp") == 0)	return GDF_TIMESTAMP;
	if (dtype.compare( "category") == 0) 	return GDF_CATEGORY;
	if (dtype.compare( "float") == 0)		return GDF_FLOAT32;
	if (dtype.compare( "float32") == 0)		return GDF_FLOAT32;
	if (dtype.compare( "float64") == 0)		return GDF_FLOAT64;
	if (dtype.compare( "double") == 0)		return GDF_FLOAT64;
	if (dtype.compare( "short") == 0)		return GDF_INT16;
	if (dtype.compare( "int") == 0)			return GDF_INT32;
	if (dtype.compare( "int32") == 0)		return GDF_INT32;
	if (dtype.compare( "int64") == 0)		return GDF_INT64;
	if (dtype.compare( "long") == 0)		return GDF_INT64;

	return GDF_invalid;
}
When you pass np.float, GDF_invalid is returned resulting in GDF error ("GDF_UNSUPPORTED_DTYPE") showing up.
Hopefully that solves your issue.

**Comment by ericmjl** [comment]
@Iroy30 thanks for getting back on that. Yes, changing to strings works out.

I have other issues to raise regarding the API, but for the purposes of this issue, I'm happy to consider it solved.
