### ISSUE TITLE
cudatoolkit not installed automatically

### ISSUE THREAD

**Issue by ericmjl** [rapidsai/cudf#487]
## Feature request

I would like to see cudatoolkit installed automatically when installing cudf.

When I first tried printing a dataframe to the output area of the Jupyter notebook, I saw an error stating that `cudatoolkit` needed to be installed via conda. I experienced "user surprise" when this error showed up, as I had assumed that the installation commands on the RAPIDS AI front page would have installed all things necessary for usage out-of-the-box. If `cudatoolkit` was installed automatically, we could reduce user surprise, which would help with adoption.

**Comment by kkraus14** [comment]
@ericmjl given the typical way of installing the CUDA toolkit is **not** via conda and conda currently can't detect if the CUDA toolkit is installed from outside of conda I'm not in favor of adding the `cudatoolkit` conda package as a dependency. I'm going to close this but we can revisit if/when conda adds support for detecting an existing CUDA installation.
