### ISSUE TITLE
automatically infer dtypes when using read_csv

### ISSUE THREAD

**Issue by ericmjl** [rapidsai/cudf#488]
## Feature request

Related to #487 (in spirit, not in technicalities), this is an issue report about reducing user surprise when interfacing with cuDF. 

The pandas read_csv API does not require me to specify dtypes for my data. Even though dtype specification is an option, pandas has a sane default in which it automatically infers dtypes. To help with user adoption, this should be the default as well. As evidenced by #486, the lack of documentation reachable from a search engine was a a big stumbling block.

**Comment by BradReesWork** [comment]
I will work on getting the documentation better.  The API should match Pandas where specifying the dtype is optional.

**Comment by Iroy30** [comment]
That is currently in the pipeline with PR #478

**Comment by kkraus14** [comment]
Fixed by #478
