### ISSUE TITLE
[QST][Java] first call of 'ColumnVector.from...(...) ' is too slow ?

### ISSUE THREAD

**Issue by rui911013** [rapidsai/cudf#4892]
> I use the java interface ’ColumnVector.fromLongs‘ to generate the Table. and at the same time, i want to know what time it is spent , code like this:
--------------
                val currentColumnVecotr: Array[ColumnVector] = new Array[ColumnVector](3)
                val s1 = System.currentTimeMillis
                currentColumnVecotr(0) = ColumnVector.fromBoxedInts(10, 2, 30, 40)
                val s2 = System.currentTimeMillis
                currentColumnVecotr(1) = ColumnVector.fromBoxedLongs(1L, 2L, 3L, 4L)
                currentColumnVecotr(2) = ColumnVector.fromBoxedBooleans(true, false, false, true)
                val retTable : Table = new Table(currentColumnVecotr: _*)
                val s3 = System.currentTimeMillis
                System.out.println(fisrt call ColumnVector.from... time is " + (t2 - t1))
                System.out.println(generate table time is " + (t3 - t1))
---------------
finally, i get the result :
**first call ColumnVecotr.from...  time is 1599ms
generate table time is 1601ms**

quetion: 
1.my first question is that why the first call of ColumnVector.from... cost 1599ms, but the follow code is cost few  ? I doubt that I have not add the cudaThreadSynchronize() to avoid the Asynchrony of CUDA API ？if so , is there some good method to profile  java performance.
2. I want to know if it is normal to this time cost (1601ms) ,after all  I just generate 3 columns

**Comment by revans2** [comment]
There is often a lot of startup time with Cuda.  When Cuda first interacts with a GPU it needs to set up a number of things, both in the kernel and on the GPU, including sending the precompiled kernels to the GPU.  In the case of cuDF that can be over 500MB of kernels that are sent.  That will hopefully drop a lot once we remove the legacy API support and the corresponding kernels, but it will not all go away.

If it is any consolation when I run the same program, with a few edits to make it compile it takes me 4.1 seconds to do the first column vector call.  This is a known issue both in the java side and on the python side.

@kkraus14 do you know if there is anything being done to address this in the C++ code or that python is doing that the java API could adopt?

**Comment by kkraus14** [comment]
> @kkraus14 do you know if there is anything being done to address this in the C++ code or that python is doing that the java API could adopt?

We're not doing anything special on the C++ side where I think this is just standard CUDA startup overheads. In addition to context creation and copying over the device code, driver API initialization also occurs which is a non-trivial cost as well.

We validate the GPU setup (GPU architecture, driver version, toolkit version, etc.) on import which does the driver initialization, so we only need to initialize the context (and implicitly copy device code) on first column creation, but it's still costly.

**Comment by revans2** [comment]
@rui911013 does that answer your question?

**Comment by rui911013** [comment]
> There is often a lot of startup time with Cuda. When Cuda first interacts with a GPU it needs to set up a number of things, both in the kernel and on the GPU, including sending the precompiled kernels to the GPU. In the case of cuDF that can be over 500MB of kernels that are sent. That will hopefully drop a lot once we remove the legacy API support and the corresponding kernels, but it will not all go away.
> 
> If it is any consolation when I run the same program, with a few edits to make it compile it takes me 4.1 seconds to do the first column vector call. This is a known issue both in the java side and on the python side.
> 
> @kkraus14 do you know if there is anything being done to address this in the C++ code or that python is doing that the java API could adopt?



> @rui911013 does that answer your question?

yes，thank you and @kkraus14
