### ISSUE TITLE
[QST] I need a "reduce" operation

### ISSUE THREAD

**Issue by schernolyas** [rapidsai/cudf#4893]
Hi!

I have grouped my cudf stream and now I need to reduce values by unique values.
 For example, My stream has:
a   b
1  1
1  2
2  3
2  4

I need to get stream with have unique value of column 'a' and result of some function from column 'b'
a  f(a)
1  10
2  20

How I can do it? Thanks for advice!

**Comment by kkraus14** [comment]
@schernolyas it sounds like you're doing a groupby. Can you give more information about what `f(a)` looks like? Do built in groupby aggregations not suffice for your use case?

**Comment by schernolyas** [comment]
Hi @kkraus14 !
Do you mean that I can decrease count of rows by groupby? I tried groupby without success.

**Comment by kkraus14** [comment]
@schernolyas Yes, in your above example, you could do something like `df.groupby(['a']).sum()` which would return you two rows of `[3, 7]` which is the sum of the `b` column.

**Comment by schernolyas** [comment]
Hi @kkraus14 !

Thank you very much for your comments.

**Comment by kkraus14** [comment]
@schernolyas my pleasure, I'm going to close this as it seems your question is resolved. If you have any additional questions feel free to open a new issue.
