### ISSUE TITLE
[FEA] Implement toJavaFormatString for floating point numbers

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#4895]
**Is your feature request related to a problem? Please describe.**
As a Java user (including Scala and Spark users), I would expect a cast from float/double to string to return results consistent with Java's implementation of `String.valueOf(n)`.

The results currently returned by CuDF are inconsistent, both in precision and formatting. For example:

Float.MAX_VALUE
```
Java: 3.4028235E38
cuDF: 3.402823466e+38
```

Double.MAX_VALUE:
```
Java: 1.7976931348623157E308
cuDF: 1.797693135e+308
```

**Describe the solution you'd like**
The ideal solution would be to provide a specific method in the Java cuDF library that implements the same logic as `jdk.internal.math.FloatingDecimal.BinaryToASCIIBuffer#getChars` where different formatting rules are used depending on the specific values of the mantissa and exponent. For example, if the exponent is between 0 and 7 then the number is formatted without using scientific notation.

**Describe alternatives you've considered**
- We could document that CuDF cast from float to string is not compatible with Java.
- Another option is bringing the data into the CPU and applying the formatting but that would be prohibitively expensive.

**Comment by kkraus14** [comment]
It sounds like we're just looking for controllable precision of Float --> String instead of something Java specific, yes?

**Comment by revans2** [comment]
@andygrove I don't think we are going to get something that is so java specific.  cuDF is intended to be a base platform providing common functionality. The code you are pointing at is very complicated and it is also GPL licensed so we cannot really do too much with that directly.  The java spec does not cover this particular use case, but the javadocs for `Float.toString` do.

https://docs.oracle.com/javase/8/docs/api/java/lang/Float.html#toString-float-

@kkraus14 I don't think we can get away with just controllable precision because everything except a few hard coded numbers have a variable precision. 

> Returns a string representation of the <code>float</code>
>  argument. All characters mentioned below are ASCII characters.
>  <ul>
>  <li>If the argument is NaN, the result is the string
>  "<code>NaN</code>".
>  </li><li>Otherwise, the result is a string that represents the sign and
>      magnitude (absolute value) of the argument. If the sign is
>      negative, the first character of the result is
>      '<code>-</code>' (<code>'\u002D'</code>); if the sign is
>      positive, no sign character appears in the result. As for
>      the magnitude <i>m</i>:
>  <ul>
>  <li>If <i>m</i> is infinity, it is represented by the characters
>      <code>"Infinity"</code>; thus, positive infinity produces
>      the result <code>"Infinity"</code> and negative infinity
>      produces the result <code>"-Infinity"</code>.
>  </li><li>If <i>m</i> is zero, it is represented by the characters
>      <code>"0.0"</code>; thus, negative zero produces the result
>      <code>"-0.0"</code> and positive zero produces the result
>      <code>"0.0"</code>.
>  </li><li> If <i>m</i> is greater than or equal to 10<sup>-3</sup> but
>       less than 10<sup>7</sup>, then it is represented as the
>       integer part of <i>m</i>, in decimal form with no leading
>       zeroes, followed by '<code>.</code>'
>       (<code>'\u002E'</code>), followed by one or more
>       decimal digits representing the fractional part of
>       <i>m</i>.
>  </li><li> If <i>m</i> is less than 10<sup>-3</sup> or greater than or
>       equal to 10<sup>7</sup>, then it is represented in
>       so-called "computerized scientific notation." Let <i>n</i>
>       be the unique integer such that 10<sup><i>n</i> </sup>≤
>       <i>m</i> &lt; 10<sup><i>n</i>+1</sup>; then let <i>a</i>
>       be the mathematically exact quotient of <i>m</i> and
>       10<sup><i>n</i></sup> so that 1 ≤ <i>a</i> &lt; 10.
>       The magnitude is then represented as the integer part of
>       <i>a</i>, as a single decimal digit, followed by
>       '<code>.</code>' (<code>'\u002E'</code>), followed by
>       decimal digits representing the fractional part of
>       <i>a</i>, followed by the letter '<code>E</code>'
>       (<code>'\u0045'</code>), followed by a representation
>       of <i>n</i> as a decimal integer, as produced by the
>       method <a href="../../java/lang/Integer.html#toString-int-"><code>Integer.toString(int)</code></a>.
> 
>  </li></ul>
>  </li></ul>
>  How many digits must be printed for the fractional part of
>  <i>m</i> or <i>a</i>? There must be at least one digit
>  to represent the fractional part, and beyond that as many, but
>  only as many, more digits as are needed to uniquely distinguish
>  the argument value from adjacent values of type
>  <code>float</code>. That is, suppose that <i>x</i> is the
>  exact mathematical value represented by the decimal
>  representation produced by this method for a finite nonzero
>  argument <i>f</i>. Then <i>f</i> must be the <code>float</code>
>  value nearest to <i>x</i>; or, if two <code>float</code> values are
>  equally close to <i>x</i>, then <i>f</i> must be one of
>  them and the least significant bit of the significand of
>  <i>f</i> must be <code>0</code>.

**Comment by andygrove** [comment]
Thanks @revans2 and @kkraus14. Having controllable precision might be a nice feature to consider for the future but I agree that it won't provide Java compatibility, although it would get us closer for double -> string.
