### ISSUE TITLE
[FEA] Add forward fill and backward fill options for fillna in groupby objects.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#4896]
#1361 is an FEA for `df.fillna()`. 

I'm creating this specifically for groupby objects.

**Comment by chinmaychandak** [comment]
@kkraus14 Is this being targeted for 0.15?

**Comment by randerzander** [comment]
Still a desired [FEA]

**Comment by kkraus14** [comment]
Being worked on in #7118
