### ISSUE TITLE
Support more series operators 

### ISSUE THREAD

**Issue by jcrist** [rapidsai/cudf#49]
The following are missing:

- [x] negation (`-x`)
- [x] inv (`~x`)
- [x] boolean operations (`&`, `|`, `^`)
- [x] pow (`x ** 2`)

pow was added in #892 . Negation and inversion are part of #1163. Boolean bitwise operations are in #1292.

**Comment by jrhemstad** [comment]
@kkraus14 are these still missing?

**Comment by kkraus14** [comment]
> @kkraus14 are these still missing?

Yes, as far as I'm aware.

**Comment by mrocklin** [comment]
I ran into this today.  Here is a minimal example.

```python
import cudf
gdf = cudf.DataFrame({'x': [1, 2, 3], 'y': [1, 2, 1]})
gdf[(gdf.x > 1) & (gdf.y < 2)]
```

**Comment by mrocklin** [comment]
Checking in here.  Should this be doable now that Jitify is in?

**Comment by mrocklin** [comment]
At first glance it doesn't appear to be available yet.

**Comment by devavret** [comment]
@mrocklin It can be added. Bitwise operators weren't included in the first set of Jitified functions.

**Comment by harrism** [comment]
Reopening this issue because I realized that this issue requests more than just bitwise ops. @devavret what about pow() and the unary ops that are requested? Are these already done?

**Comment by devavret** [comment]
@harrism pow was added in #892 . Negation and inversion are part of #1163
