### ISSUE TITLE
[QST][JAVA]Can I use cudf-java.jar to accelerate my SparkSQL operation ? 

### ISSUE THREAD

**Issue by rui911013** [rapidsai/cudf#4904]
as you know, spark's data format is RDD[row] , while  the Interface of cudf-java.jar is both table、columnVector，if I want to use cudf to accelerate my SparkSQL job  and not modify my application's code , what I need to do ? 

I guess I need to thransfer RDD[internalRow] to RDD[ColumnBatch] and then call cudf-jar interface ,  well ,it's said that this process is supported in spark3.0 .  

finally , I am very interested in  where and how to connect interface of cudf-jar , like ai.rapids.cudf.ColumnVector or Table .  

Hope to get help ！ 
thanks

**Comment by krajendrannv** [comment]
Spark 3.0 will have native GPU support and RAPIDS Accelerator for Spark plugin will enable Spark 3.0 users to accelerate SQL queries without code change. RAPIDS Accelerator for Spark (jars) will be available as a Beta release (with selected functionality) tentatively around Spark+AI Summit. If you provide us details regarding your use case, data size, and SQL operators used in your query, we can get back to you whether those functionalities will be supported in our Beta release. 
Regarding the cudf-jar interface and how to use RAPIDS Accelerator for Spark, please look out for talks, tutorials, etc. that will be posted in our Datascience webpage https://www.nvidia.com/en-us/deep-learning-ai/solutions/data-science/
