### ISSUE TITLE
[BUG] Copy in deserialization of `MultiIndex` objects

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/cudf#4910]
**Describe the bug**

In deserialization of `MultiIndex` objects, we call [`reset_index`]( https://github.com/rapidsai/cudf/blob/4009501328166b109a73a0a9077df513186ffc2a/python/cudf/cudf/core/multiindex.py#L50 ). This results in [a call to `DataFrame.copy(...)`]( https://github.com/rapidsai/cudf/blob/65bbee7920182f709a269b8f0aba4b2434f4beb3/python/cudf/cudf/core/dataframe.py#L1544 ). It would be good to avoid this copy in deserialization (if not more generally).

**Comment by rgsl888prabhu** [comment]
Resolved with #4915
