### ISSUE TITLE
[FEA] series hash

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4913]
**Is your feature request related to a problem? Please describe.**

I'd like to use cudf to hash a column
* security: ioc matching for md5/sha1/...
* optimization: partitioning, caching, ..
* safety: error codes, ...

**Describe the solution you'd like**

1. `series.hash(alg='sha512') -> int64` 
2. `df.hash(alg='sha512') -> int64`
3. Worth considering a few variants, esp. md5/sha256/sha512 for sec/CLX community.

* Something fast-ish that avoids needing to move all the data to the CPU to get a has
* In our past use cases, md5/sha1 would have been useful due to community norms (data exchanges), and higher for stuff like court admissability
* In latest use case, just want fast (use for lossy cache optimizations)
* Potentially do something like both `series.hash() -> int` and `df.hash() -> int`
* Potential for controlling hash size (32b, 64b,  256b, ...)

**Describe alternatives you've considered**

* Move to CPU and compute there
* Use one of the public cuda md5 algos

**Additional context**

* May also be relevant to cusignal
* I saw some internal hashing discussion in cuml (umap) and as part of partitioning

**Comment by jrhemstad** [comment]
This already exists in[ libcudf](https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/include/cudf/hashing.hpp#L34). I'm think it's already exposed to Python as well. Maybe here: https://github.com/rapidsai/cudf/blob/75302c9651b8fe7d6dc850b398711ab90ed61ace/python/cudf/cudf/core/frame.py#L266

**Comment by kkraus14** [comment]
@jrhemstad This is a request for generating a single scalar hash from a column of values as opposed to hashing each value in the column.

**Comment by GregoryKimball** [comment]
Closing for now as low priority
