### ISSUE TITLE
Wiki is out of date

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#492]
## Feature request

The cuDF wiki is out of date: https://github.com/rapidsai/cudf/wiki

It still refers to pygdf and links to the old, archived repository.

**Comment by mike-wendt** [comment]
@taureandyernv can you update this and set a standard that we can use for other repos? Maybe start an internal doc to circulate what this looks like with the PMs and go from there?

cc @randerzander @datametrician

**Comment by mike-wendt** [comment]
Done
