### ISSUE TITLE
[BUG] cudf.set_allocator reserves memory when pool=False

### ISSUE THREAD

**Issue by jeanp413** [rapidsai/cudf#4921]
**Describe the bug**
Calling `cudf.set_allocator` with `allocator="managed", pool=False, initial_pool_size=None` is reserving half total GPU memory in 0.14 this wasn't the case in 0.13.
If I change `allocator="default"` in the script below no memory is reserved.

**Steps/Code to reproduce bug**
```python
import cudf
import time

cudf.set_allocator(allocator="managed",
                    pool=False,
                    initial_pool_size=None,# Default is 1/2 total GPU memory
                    enable_logging=False)

df = cudf.DataFrame()
df['col1'] = cudf.Series(tuple(range(10000)))
df['col2'] = cudf.Series(tuple(range(10000)))
time.sleep(3)
print(df.head(10))
time.sleep(5) 
```
**Expected behavior**
`cudf.set_allocator` shouldn't reserve memory when `pool=False` is set.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [conda]

**Comment by kkraus14** [comment]
@brandon-b-miller could you take a look into this?

**Comment by kkraus14** [comment]
Fixed by https://github.com/rapidsai/rmm/pull/348
