### ISSUE TITLE
C++ Doxygen template was deleted

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#493]
## Feature request

The [code documentation template](https://github.com/rapidsai/cudf/blob/3c7bea328533a78907ab25871d10095e9a838c87/libgdf/src/example_documentation.cpp) was deleted as a result of the "refactor". 

It should either be added back, or moved to a Wiki page.

**Comment by kkraus14** [comment]
@jrhemstad can you submit a PR in readding it?

**Comment by jrhemstad** [comment]
> @jrhemstad can you submit a PR in readding it?

Not sure what you're asking.

**Comment by kkraus14** [comment]
Can you readd 

> > @jrhemstad can you submit a PR in readding it?
> 
> Not sure what you're asking.

You said that the template was deleted accidentally in the refactor, I was simply suggesting to create a PR of readding it and if there's questions of locations we can discuss in the PR.

**Comment by jrhemstad** [comment]
Sorry, I read "readding it" as "reading it" instead of "re-adding it" and was very confused.

Now I understand :)

I'm happy to add it back, but I believe that @mt-jones deleted it on purpose as he would prefer a Wiki page instead.

Personally I don't care which of the two we go with.

**Comment by eyalroz** [comment]
@jrhemstad : Wiki page.

By the way - according the documentation template , we should _not_ be adding the silly
```
/* ---------------------------- */
```
lines before and after the doxygen comments. We should get rid of all of those.

**Comment by jrhemstad** [comment]
I wrote the template and put those lines come from the default behavior of the vim Doxygen plugin. It's purely aesthetic and I like the visual separation.

 It's also perfectly valid Doxygen: http://www.doxygen.nl/manual/docblocks.html

You're free to omit it if you'd like.

**Comment by harrism** [comment]
#4 at that link has two examples with horizontal separators.

**Comment by eyalroz** [comment]
> #4 at that link has two examples with horizontal separators.

No examples with distinct separator comment blocks. Filling out the first and last line in the same block is still not to my liking, but it's much better than the 3 consecutive comment blocks we have now.

**Comment by jrhemstad** [comment]
> > #4 at that link has two examples with horizontal separators.
> 
> No examples with distinct separator comment blocks. Filling out the first and last line in the same block is still not to my liking, but it's much better than the 3 consecutive comment blocks we have now.

Ah, I see what you mean. You dislike:

```
/* ---------------------------- */
/**
* \brief
*/
/* ---------------------------- */
```

vs.

```
/********************************************//**
 *  ... text
 ***********************************************/
```

I see how that could be annoying for folds in some IDEs. I have no problem with the latter.

 When I (or someone else) creates a Wiki page for the Doxygen template, we can update it to show the latter.

**Comment by harrism** [comment]
I agree and I'm also opposed to what I will call "Jake-style triple comments", (for lack of a better name). 

```
/***********************************/
/**
 * @brief my brief comment
 **/
/***********************************/
```

What I documented in our internal documentation guidelines that Jake converted into a .cpp file is like this:

```
/***********************************
 * @brief my brief comment
 ***********************************/
```

Note it's one comment, not three. But I am confused by what you dislike about these @eyalroz . Is it asterisks?

My *truly* preferred commenting style is C++-style:

```
//***********************************
// @brief my brief comment
//***********************************
```

Because if all block comments only use `\\`, you can easily (temporarily) comment out a whole section of a file (or a whole file), including block comments, using C-style comments. I'm not sure why I didn't suggest that in the original document.

**Comment by eyalroz** [comment]
I dislike the separator rows, in any format. The reason is that I don't feel subsequent functions need to be so strongly separated, visually, just by virtue of having a doxygen comment. I mean:
```
void pop();
void goes();
void the_weasel();
//---------------------------------------
void and_now_for_something_completely_different();

```
becomes:
```
///---------------------------------------
///@ brief
///---------------------------------------
void pop();

///---------------------------------------
///@ brief
///---------------------------------------
void goes();

///---------------------------------------
///@ brief
///---------------------------------------
void the_weasel();

//---------------------------------------

///---------------------------------------
///@ brief
///---------------------------------------
void and_now_for_something_completely_different();

```
instead of:
```
///@ brief
void pop();

///@ brief
void goes();

///@ brief
void the_weasel();

//---------------------------------------

void and_now_for_something_completely_different();

```
See what I mean?

**Comment by harrism** [comment]
I've never needed a standalone separator bar like that. What do you use it for?

**Comment by jrhemstad** [comment]
> I agree and I'm also opposed to what I will call "Jake-style triple comments", (for lack of a better name).

Before my good name gets dragged through the mud, this just happens to be the default in the Vim Doxygen toolkit! 

https://github.com/vim-scripts/DoxygenToolkit.vim

**Comment by harrism** [comment]
I was teasing you, please don't be insulted. :)

**Comment by eyalroz** [comment]
I'll live with the majority vote.
