### ISSUE TITLE
[DOC] Update nvstrings notebooks per new notebooks requirements

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#4939]
Currently, we have some [nvstrings notebooks](https://github.com/rapidsai/cudf/tree/branch-0.14/python/nvstrings/notebooks) that can be moved to the [cudf notebooks folder](https://github.com/rapidsai/cudf/tree/branch-0.14/notebooks).  Some of these notebooks would be useful to our users, so we should update these to our new [guidelines](https://github.com/rapidsai/kb/issues/16).  While not all of them should be moved, we can definitely use or redo a few.

- [ ] Select which notebooks/concepts to move to `cudf/notebooks`
- [ ] Update/fix and move the selected notebooks to the new folder 
- [ ] Update the a README as per guidelines
- [ ] Consolidate/redo remaining notebooks, as needed, into new notebooks for `cudf/notebooks`

**Comment by kkraus14** [comment]
@taureandyernv nvstrings is deprecated as of 0.13 where we should either port those notebooks to cudf or remove those notebooks. Given these notebooks were mostly used for testing from the looks of it I think we can remove them / move them into docstrings / unit tests instead.

**Comment by taureandyernv** [comment]
I think you're right.  Word count seems to be a popular request, and as `nvstrings` is deprecated, shall we port that one over to cudf with current best practices?

**Comment by kkraus14** [comment]
I'd be happy to have a word count notebook ported to use cuDF string APIs.

**Comment by kkraus14** [comment]
Notebooks were removed as part of refactoring so closing this issue.
