### ISSUE TITLE
[BUG] df.assign performs deep copy

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4944]
**Describe the bug**

We had some code taking longer than expected, and traced it down to assign performing deep copies. This is pretty bad when in a for loop w/ hundreds of cols:

```
for col in df:
  df = df.assign(**{col + 'z': df[col]})
```

Looping over the columns will cause `len(df.columns)` calls of `df.copy(deep=True)`. We expected it to be cheap CPU-only calls.

**Environment overview (please complete the following information)**

RAPIDS 0.13. Looks like RAPIDS master as well as of time of writing.

![Screenshot from 2020-04-18 01-21-34](https://user-images.githubusercontent.com/4249447/79632406-bf2d4c00-8113-11ea-99c6-228709392351.png)

**Comment by kkraus14** [comment]
This is pandas semantics unfortunately where they expect `.assign` to do a deep copy: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.assign.html.

If you don't want a deep copy, you could use a shallow copy + `__setitem__` or something similar:
```
newdf = df.copy(deep=False)
for col in newdf:
    newdf[col + 'z'] = newdf[col]
```

**Comment by lmeyerov** [comment]
@kkraus14 

Yep, that's the internal work-around we did  yesterday.

We had ~200 uses of `assign` in our code base - it's a great primitive  - and all but ~5 needing to be removed for direct assignment. It's now outlawed by our informal style guide :(

This seems worth not giving up on for bug-for-bug compatibility w/ pandas. Some counterproposals:

1. **Method `df::assign_shallow`**: same call, but sets `deep=False`. So new CPU wrapper stuff, but no actual GPU copying, and ideally, zero GPU calls at all.

2. **df::assign keyword parameter deep**: Extend `assign` to have keyword `deep=False`. This causes different semantics than pandas, however.

3. **lint mode**: Reveal gotchas like known default-slow `assign`. Ex: Style guide, run-time warning level, ... .
