### ISSUE TITLE
[DOC] string docs for basic regex actions

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#4946]
## Report incorrect documentation

**Location of incorrect documentation**

https://docs.rapids.ai/api/cudf/stable/search.html?q=search&check_keywords=yes&area=default#

**Describe the problems or issues found in the documentation**

Searching docs for `search` and `match` had no hits for the new methods. I expected docs that would guide us on:

* String match
* Regex match
* How to get the first group out / NA
* How to get a list of matches out
* How to convert non-strings to strings and get matches out

**Steps taken to verify documentation is incorrect**

Slack

**Suggested fix for documentation**

1. API method docs

2. Include regex as part of the quick tutorials, esp. for the above actions of str/rgx match (bool/span), single/multiple groups (val), and non-str -> str.

---

**Comment by davidwendt** [comment]
For reference: https://docs.rapids.ai/api/libcudf/stable/md_regex.html

**Comment by harrism** [comment]
@davidwendt is there any action needed here?

**Comment by davidwendt** [comment]
The description is asking for examples and tutorials on using regex. I don't think these exist.
I'm not sure if the request is for Python API documentation or libcudf doxygen examples(?) documentation.
I believe all of the Python docs have examples in their API but I don't think there is a general tutorial on using regex.
Also, I don't know how to improve the doc search feature (or if it should be improved for this).

**Comment by lmeyerov** [comment]
There were two locations, afaict first is still outstanding and second is done:

1. Initial intro, aiding both initial discoverability and providing a reference example: part of 10min to cudf

https://docs.rapids.ai/api/cudf/stable/10min.html

2. Done: actual docs -- searching `search`/`match` now leads to series methods with examples

https://docs.rapids.ai/api/cudf/stable/api.html?highlight=match#cudf.core.column.string.StringMethods.match

**Comment by harrism** [comment]
OK, sounds like a Python doc request.

**Comment by GregoryKimball** [comment]
To clarify,t his issue is requesting to add a regex example to the "[10 min to cuDF and Dask-cuDF](https://docs.rapids.ai/api/cudf/stable/user_guide/10min.html#string-methods)".
