### ISSUE TITLE
[FEA] .plot() method 

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/cudf#4948]
**Is your feature request related to a problem? Please describe.**
I wish I could use cuDF to do `.plot()` like `pandas.DataFrame.plot()`.

**Describe the solution you'd like**
`cudf.DataFrame.plot()` 
- scatter
- bar
- line

**Describe alternatives you've considered**
Converting `.to_pandas()` and using `pandas.DataFrame.plot()`.

Building `cudf.DataFrame.plot()` method that temporarily converts `.to_pandas()` then uses `pandas.DataFrame.plot()`.

**Additional context**
Maybe this could use Datashader https://github.com/holoviz/datashader/pull/793 where pandas uses Matplotlib.

**Comment by GregoryKimball** [comment]
Closing this because the `.to_pandas()` workaround is adequate.
