### ISSUE TITLE
[QST]ffi.error: symbol 'rmmInitialize' not found in library ???

### ISSUE THREAD

**Issue by ehsanshah** [rapidsai/cudf#4952]
when i run this command :
(rapids) ehsan@tensor:~/Documents$ python3.7 -c "import cudf"

Traceback (most recent call last):
  File "/home/ehsan/.local/lib/python3.7/site-packages/librmm_cffi/wrapper.py", line 37, in __getattr__
    return self._cached[name]
KeyError: 'rmmInitialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ehsan/.local/lib/python3.7/site-packages/cudf/__init__.py", line 3, in <module>
    from cudf import dataframe
  File "/home/ehsan/.local/lib/python3.7/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/home/ehsan/.local/lib/python3.7/site-packages/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
  File "/home/ehsan/.local/lib/python3.7/site-packages/librmm_cffi/__init__.py", line 54, in <module>
    librmm.initialize()
  File "/home/ehsan/.local/lib/python3.7/site-packages/librmm_cffi/wrapper.py", line 90, in initialize
    return self.rmmInitialize(opts)
  File "/home/ehsan/.local/lib/python3.7/site-packages/librmm_cffi/wrapper.py", line 39, in __getattr__
    fn = getattr(self._api, name)
ffi.error: symbol 'rmmInitialize' not found in library '/home/ehsan/anaconda3/envs/rapids/lib/librmm.so': /home/ehsan/anaconda3/envs/rapids/lib/librmm.so: undefined symbol: rmmInitialize
#---------------------------------------------------------------------------------------------------------------------------
i install rapidsai with :
conda install -c rapidsai -c nvidia -c conda-forge -c defaults rapids=0.13 python=3.7 cudatoolkit=10.2
#---------------------------------------------------------------------------------------------------------------------------
#/usr/local/cuda-10.2/

export PATH=$PATH:/usr/local/cuda-10.2/bin
export CUDADIR=/usr/local/cuda-10.2/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/extras/CUPTI/lib64:/usr/local/cuda-10.2/targets/x86_64-linux/lib:

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.48.02    Driver Version: 440.48.02    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   45C    P8    16W / 280W |    748MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1464      G   /usr/lib/xorg/Xorg                            26MiB |
|    0      2715      G   /usr/lib/xorg/Xorg                           186MiB |
|    0      2931      G   /usr/bin/gnome-shell                         267MiB |
|    0      3177      G   gnome-ring                                     2MiB |
|    0      3880      G   ...rogram/Idea-IU-193.6015.39/jbr/bin/java     3MiB |
|    0     19084      G   ...n/Program/pycharm-2019.3.2/jbr/bin/java     3MiB |
|    0     25162      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files   114MiB |
+-----------------------------------------------------------------------------+

#
# Name                    Version                   Build  Channel
libnvstrings              0.13.0               cuda10.2_0    rapidsai
nvstrings                 0.13.0                   py37_0    rapidsai
(rapids) ehsan@tensor:~/Documents$ conda list cuda
# packages in environment at /home/ehsan/anaconda3/envs/rapids:
#
# Name                    Version                   Build  Channel
cudatoolkit               10.2.89              h6bb024c_0    nvidia
dask-cuda                 0.13.0                   py37_0    rapidsai
(rapids) ehsan@tensor:~/Documents$ 

and os : 
Ubuntu 19.10

<pre># packages in environment at /home/ehsan/anaconda3/envs/rapids:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
aiohttp                   3.6.2            py37h516909a_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.4              pyh9f0ad1d_0    conda-forge
bokeh                     1.4.0            py37hc8dfbb8_1    conda-forge
boost                     1.70.0           py37h9de70de_1    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1001    conda-forge
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
colorcet                  2.0.1                      py_0    conda-forge
cryptography              2.8              py37hb09aad4_2    conda-forge
cudatoolkit               10.2.89              h6bb024c_0    nvidia
cudf                      0.13.0                   py37_0    rapidsai
cudnn                     7.6.5                cuda10.2_0  
cugraph                   0.13.0                   py37_0    rapidsai
cuml                      0.13.0          cuda10.2_py37_0    rapidsai
cupy                      7.3.0            py37h940342b_0    conda-forge
curl                      7.69.1               h33f0ec9_0    conda-forge
cusignal                  0.13.0                   py37_0    rapidsai
cuspatial                 0.13.0                   py37_0    rapidsai
cuxfilter                 0.13.0                   py37_0    rapidsai
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.14.0                     py_0    conda-forge
dask-core                 2.14.0                     py_0    conda-forge
dask-cuda                 0.13.0                   py37_0    rapidsai
dask-cudf                 0.13.0                   py37_0    rapidsai
dask-xgboost              0.2.0.dev28      cuda10.2py36_0    rapidsai
datashader                0.10.0                     py_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.14.0           py37hc8dfbb8_0    conda-forge
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fastavro                  0.23.2           py37h8f50634_0    conda-forge
fastrlock                 0.4             py37h3340039_1001    conda-forge
fiona                     1.8.9.post2      py37hdff7cfa_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fsspec                    0.6.3                      py_0    conda-forge
gdal                      2.4.4            py37h5f563d9_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.0                he1b5a44_1    conda-forge
geotiff                   1.5.1                h38872f0_8    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.64.2               h6f030ca_0    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
grpc-cpp                  1.23.0               h18db393_0    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 5.2.0            py37h43977f1_1    conda-forge
ipython                   7.13.0           py37hc8dfbb8_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter-server-proxy      1.3.2                      py_0    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
kealib                    1.4.13               hec59c27_0    conda-forge
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcudf                   0.13.0               cuda10.2_0    rapidsai
libcugraph                0.13.0               cuda10.2_0    rapidsai
libcuml                   0.13.0               cuda10.2_0    rapidsai
libcumlprims              0.13.0               cuda10.2_0    nvidia
libcurl                   7.69.1               hf7181ac_0    conda-forge
libcuspatial              0.13.0               cuda10.2_0    rapidsai
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   2.4.4                h2b6fda6_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libhwloc                  2.1.0                h3c4fd83_0    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.3           nompi_h9f9fd6a_101    conda-forge
libnvstrings              0.13.0               cuda10.2_0    rapidsai
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libpq                     12.2                 h5513abc_1    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.13.0               cuda10.2_0    rapidsai
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             4.3.0a            ha48a99a_1034    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxgboost                1.0.2dev.rapidsai0.13      cuda10.2_6    rapidsai
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
llvmlite                  0.31.0           py37h5202443_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markdown                  3.2.1                      py_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
matplotlib-base           3.2.1            py37h30547a4_0    conda-forge
mistune                   0.8.4           py37h8f50634_1001    conda-forge
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
multidict                 4.7.5            py37h516909a_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
nccl                      2.5.7.1              hc6a2c23_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h8960a57_1    conda-forge
nvstrings                 0.13.0                   py37_0    rapidsai
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1f               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
panel                     0.6.4                         0    conda-forge
param                     1.9.3                      py_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pillow                    7.1.1            py37h718be6c_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h8573dbc_1    conda-forge
proj                      6.3.0                hc80f0dc_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
psutil                    5.7.0            py37h8f50634_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-xgboost                1.0.2dev.rapidsai0.13  cuda10.2py37_6    rapidsai
pyarrow                   0.15.0           py37h8b68381_1    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pyee                      7.0.1                      py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pynvml                    8.0.4                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyppeteer                 0.0.25                     py_1    conda-forge
pyproj                    2.5.0            py37h8ff28aa_0    conda-forge
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyviz_comms               0.7.4              pyh8c360ce_0    conda-forge
pywavelets                1.1.1            py37h03ebfcd_1    conda-forge
pyyaml                    5.3.1            py37h8f50634_0    conda-forge
pyzmq                     19.0.0           py37hac76be4_1    conda-forge
rapids                    0.13.0          cuda10.2_py37_0    rapidsai
rapids-xgboost            0.13.0          cuda10.2_py37_0    rapidsai
re2                       2020.04.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rmm                       0.13.0                   py37_0    rapidsai
rtree                     0.9.4            py37h8526d28_1    conda-forge
scikit-image              0.16.2           py37hb3f55d8_0    conda-forge
scikit-learn              0.22.2.post1     py37hcdab131_0    conda-forge
scipy                     1.4.1            py37ha3d9a3c_3    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37hb106bac_1    conda-forge
simpervisor               0.3                        py_1    conda-forge
six                       1.14.0                     py_1    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
tqdm                      4.45.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
ucx                       1.7.0+g9d06c3a       cuda10.2_0    rapidsai
ucx-py                    0.13.0+g9d06c3a          py37_0    rapidsai
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websockets                8.1              py37h8f50634_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xarray                    0.15.1                     py_0    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xgboost                   1.0.2dev.rapidsai0.13  cuda10.2py37_6    rapidsai
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.4                h516909a_0    conda-forge
yarl                      1.3.0           py37h516909a_1000    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
</pre>

**Comment by kkraus14** [comment]
@ehsanshah `librmm_cffi` is a remnant of an old version of the `rmm` python library that's likely left on your system somewhere.

Could you run a `pip list | grep rmm` and see if there's a `librmm_cffi` or `rmm_cffi` or something similar package installed that you can remove?

**Comment by ehsanshah** [comment]
@kkraus14 i run command : pip list | grep rmm and pip list | grep librmm_cffi and pip list | grep rmm_cffi 
but not found any package  
note: i run in virtualenv 'rapids'

**Comment by kkraus14** [comment]
Is that the same environment as your conda environment above? If so you have a ton of conflicting and old versions of things, i.e. `cudf 0.6.1`. Based on this I think your best bet is to blow away the environment and start fresh with a new environment.

**Comment by ehsanshah** [comment]
@kkraus14 thanks I'm uninstall annaconda and remove all library and install again
