### ISSUE TITLE
[FEA] Apply corr() after groupby

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#4954]
**Is your feature request related to a problem? Please describe.**

I'd like to apply .corr() after doing groupby on cudf dataframe columns. The desired solution is defined below using pandas df, which is not supported yet by cudf.  I'd like to know also if there is a workaround to be able to calculate .corr() between groupbyed columns. 

**Describe the solution you'd like**

I want to be able to calculate the following using cudf df as I can do with pandas df.

```
pdf =  pd.DataFrame({ 'id1': ['id01', 'id01', 'id01', 'id02', 'id02', 'id02'], 'id2': [1, 1, 1, 2, 2, 2], 'v1': [1, 2, 3, 1, 2, 3], 'v2': [1, 3, 3, 2, 1, 1]})
pdf.groupby(['id1','id2']).apply(lambda x: pd.Series({'r2': x.corr()['v1']['v2']}))

		     r2
id1	id2	
id01	1	0.866025
id02	2	-0.866025
```

**Comment by beckernick** [comment]
We've now implemented groupby.corr, like pandas. Closing as resolved

```python
import cudf
​
df = cudf.DataFrame({
    'id1': ['id01', 'id01', 'id01', 'id02', 'id02', 'id02'],
    'id2': [1, 1, 1, 2, 2, 2],
    'v1': [1, 2, 3, 1, 2, 3],
    'v2': [1, 3, 3, 2, 1, 1]}
)
print(df.groupby(['id1','id2']).corr())
                   v1        v2
id1  id2                       
id01 1   v1  1.000000  0.866025
         v2  0.866025  1.000000
id02 2   v1  1.000000 -0.866025
         v2 -0.866025  1.000000
```
