### ISSUE TITLE
Conda installation problem (cannot load library 'librmm.so')

### ISSUE THREAD

**Issue by diaper151** [rapidsai/cudf#496]
### Reporting a bug

First, Thanks u for making such a great tool.

when I used conda install
```bash
conda install -c numba -c conda-forge -c nvidia -c rapidsai -c defaults cudf=0.4.0
```
then 
```python
import cudf
```
it showed 
> OSError: cannot load library 'librmm.so': libcudart.so.9.2: cannot open shared object file: No such file or directory

I've check the system prerequisites, everything is satisfied. Is there anything I need to install or it's a bug? Thanks.

**Comment by AK-ayush** [comment]
@diaper151 Did you install cuda=9.2 anywhere either  system-wise or in conda env?

**Comment by diaper151** [comment]
@AK-ayush I have cuda-10 installed on my system. I saw rapid also support cuda-10. Should I try to install cuda-9 and give it a try?

**Comment by AK-ayush** [comment]
@diaper151 Can you try reinstalling the cudf for cuda-10 using the below command: 

`conda install -c rapidsai/label/cuda10.0 cudf `

**Comment by diaper151** [comment]
@AK-ayush  although it successfully installed with
 `
conda install -c numba -c conda-forge -c nvidia -c rapidsai/label/cuda10.0 -c defaults cudf=0.4.0
` 
But when I import cudf. It said 
`
No module named 'cudf'
`
But I can saw cudf in conda list output. That's weird.......

**Comment by AK-ayush** [comment]
By any chance you forgot to activate the conda env... It happened with me earlier.

**Comment by diaper151** [comment]
I've activated my temp env. and now somehow I successfully installed it. But it still said cannot load library 'librmm.so': libcudart.so.9.2......@@ I guess I'll try next time when 0.5 release

**Comment by AK-ayush** [comment]
@diaper151  can you please try with cuda-9.2 on system then it should work.  or you can install the cuda toolkit within conda env using :
```
conda install -c anaconda cudatoolkit
```
and try finding the file `libcudart.so.9.2` using:
```
find / -name libcudart.so.9.2
```
It is strange why it is giving error in cuda-10. will look into it.

**Comment by AK-ayush** [comment]
@diaper151 I am not able to reproduce your issue with system wise cuda-10 and installing the cudf using:
```
conda create -n rapids python=3.5
conda install  -n rapids -c numba -c conda-forge -c nvidia -c rapidsai/label/cuda10.0 -c defaults cudf
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/cuda/compat
source activate rapids
python -c "import cudf;print(cudf.__version__)"
```
---
Can you please list down the steps that you tried...

**Comment by kkraus14** [comment]
@diaper151 How did you install CUDA? After installation did you do the post-installation scripts of setting the PATH and LD_LIBRARY_PATH environment variables accordingly? See: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#environment-setup

**Comment by diaper151** [comment]
@kkraus14  Yes, I use  cuda runfile to install and all paths look fine.
@AK-ayush  Finally, After `conda install -c anaconda cudatoolkit` then everthing works just fine. Thanks you very much :100:

**Comment by kkraus14** [comment]
@diaper151 My guess is that CUDA wasn't installed properly or the path wasn't set before installing the `cudatoolkit` from conda. Glad to hear it's resolved 😄.

**Comment by robalvsan** [comment]
> @diaper151 I am not able to reproduce your issue with system wise cuda-10 and installing the cudf using:
> 
> ```
> conda create -n rapids python=3.5
> conda install  -n rapids -c numba -c conda-forge -c nvidia -c rapidsai/label/cuda10.0 -c defaults cudf
> export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/cuda/targets/x86_64-linux/lib:/usr/local/cuda/compat
> source activate rapids
> python -c "import cudf;print(cudf.__version__)"
> ```
> 
> Can you please list down the steps that you tried...

Do you install the conda packages before activating the environment? Is that correct?
