### ISSUE TITLE
[BUG] cudf.read_csv OOM when loading dataset

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#4964]
**Describe the bug**
Hi,

I think I may have found some room of improvement on memory management when loading a csv file with cudf.read_csv method.

I am testing the following code on a DGX-1 with 8xV100 16GB each.

```
import cudf
import numpy as np

# X, y datasets
X_train_file="dataset/tmp_dataset_13M_X_train_0"
y_train_file="dataset/tmp_dataset_13M_y_train_0"

X = cudf.read_csv(X_train_file, header=None, dtype=['float32'] * 111)
y = cudf.read_csv(y_train_file, header=None, dtype=['float32'])
```

It successfully reads a CSV file with 13 million rows and 111 columns and the total amount of memory used in the GPU is 6.80 GB.

<img width="617" alt="Screenshot 2020-04-21 at 00 36 20" src="https://user-images.githubusercontent.com/26169771/79806204-280d0200-8368-11ea-953a-fc557526f485.png">

But, when I try to read a CSV file with 14 million rows and 111 columns, it runs OOM.

<img width="1385" alt="Screenshot 2020-04-21 at 00 38 46" src="https://user-images.githubusercontent.com/26169771/79806358-82a65e00-8368-11ea-8945-5e89fcbcf529.png">

**Expected behavior**
Considering 13M rows take 6.8 GB of memory, I was expecting to be able to load a much bigger csv file.

**Environment overview (please complete the following information)**
DGX-1 , latest RAPIDS 0.13 container.

**Comment by kkraus14** [comment]
cc @OlivierNV @vuule does this align with expectations on memory usage from the C++ side of things?

**Comment by vuule** [comment]
Is 6.8GB the usage after the `read_csv`? I estimate the table size in memory to be ~5.7GB, so I expect that this to be the case. 
The memory usage is a lot higher during the `read_csv` call, since the input csv file is also in the device memory. @miguelusque how big is the input file? This could explain the OOM problem.

**Comment by miguelusque** [comment]
Hi @vuule,

6.8 GB is the GPU memory 

The input file sizes are the following:

![image](https://user-images.githubusercontent.com/26169771/79809722-84c0ea80-8371-11ea-9c40-672865ed05fc.png)

The memory usage after reading the 13M rows file is the following:

![image](https://user-images.githubusercontent.com/26169771/79809836-ca7db300-8371-11ea-8886-13a53b25a9dc.png)

I always restart the kernels between loading the 13M rows file and trying to read the 14M rows file.

Regards,
Miguel

**Comment by vuule** [comment]
Given the size of the input file, the OOM issue is expected. The input size is ~10GB, and the output dataframe is ~6GB. At 14M rows, they add up to more than 16GB and `read_csv` cannot have both in device memory.
For files too big to fit into device memory (as this kind of is), we have the byte_range parameter. With this, `read_csv` only loads the given range of the input file into the device memory.

**Comment by kkraus14** [comment]
Thanks for the explanation @vuule. Closing this as not an issue.

**Comment by miguelusque** [comment]
Hi @vuule ,

Thank you for the clarification.

Hi @kkraus14 ,

I think we should not close this issue yet.

With the current implementation, the user is not able to read a DataFrame of about 7.5 GBs of memory in a 16 GBs card.

If I am not wrong, the _byte_range_ proposed workaround would force the user to manually read the file in GPU in order to determine where a specific row starts (assuming rows do not have the same number of characters).

I would suggest something transparent for the user, which would let him load the CSV file in GPU without OOM.

Maybe, when reading the file, if the size is of size 'X', internally the algorithm might try and read the file in chunks of size 'Y'.

What do you think?

Regards,
Miguel

**Comment by kkraus14** [comment]
That is out of scope for cuDF. If you use a framework like Dask which uses cuDF internally it transparent handles doing this chunking for you as well as spilling to larger than GPU memory as needed.
