### ISSUE TITLE
[DOC] Add a RAPIDS Code of Conduct

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#4966]
I noticed that none of the RAPIDS projects have a Code of Conduct. Defining the rules by which a community is expected to follow makes our OS community more inclusive and increases the number of potential future contributors. If you look at any of the top Open Source Repos, they all have a Code of Conduct.

https://github.com/vuejs/vue/blob/dev/.github/CODE_OF_CONDUCT.md
https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md
https://github.com/tensorflow/tensorflow/blob/master/CODE_OF_CONDUCT.md
https://github.com/microsoft/vscode uses https://opensource.microsoft.com/codeofconduct/
https://github.com/nodejs/node/blob/master/CODE_OF_CONDUCT.md
https://github.com/kubernetes/kubernetes/blob/master/code-of-conduct.md

We could base ours off one of them, our adopt something like the Contributor Convenant. I think some of the above have done exactly this. https://www.contributor-covenant.org/

Note: NVIDIA has a company wide CoC: https://www.nvidia.com/content/dam/en-zz/Solutions/about-us/documents/NVIDIA-Code-of-Conduct-external.pdf but I couldn't find an Open Source CoC. It seems like this would be very inline with NVIDIA's company values.

**Comment by harrism** [comment]
We have one, but it's not linked from GitHub. https://docs.rapids.ai/resources/conduct/

**Comment by codereport** [comment]
Awesome! It shows on our Community page that we don't have one because we are missing a `CODE_OF_CONDUCT.md` file. I will open PR to add one.
