### ISSUE TITLE
ValueError: Buffer size must be divisible by element size

### ISSUE THREAD

**Issue by ashwanth0203** [rapidsai/cudf#4969]
**Describe the bug**
Unable to convert Pandas Dataframe to cudf data frame. While doing so facing the "ValueError: Buffer size must be divisible by element size" issue

**Steps/Code to reproduce bug**
for t_df in pd.read_csv("testset.csv",chunksize=2):
    t_df['prev_sales']= t_df['prev_sales'].apply(lambda x: np.array(ast.literal_eval(x)))
    t_df = cudf.DataFrame.from_pandas(t_df)

**Expected behavior**
Need the data frame as output

**Comment by rgsl888prabhu** [comment]
@ashwanth0203 please share the `testset.csv`.

**Comment by kkraus14** [comment]
No response so closing.
