### ISSUE TITLE
[BUG] OOM when reading csv file skip_rows parameter

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#4970]
Hi!

**Describe the bug**
I am trying to read a huge CSV file in two different dataframes.

The first dataframe is successfully read using `nrows parameters=half_number_of_rows` 
The second dataframe is read using `skip_rows=half_number_of_rows`.

When reading the second dataframe, it OOM.

I have tried to only read the second dataframe (without reading the first dataframe), and it also OOM.

It seems that the file is fully loaded into memory first, and then the dataframe is built, taking into consideration the `skip_rows` parameter once the file is fully loaded in memory.

**Steps/Code to reproduce bug**
Attached code about how to reproduce this issue.

![read_csv OOM](https://user-images.githubusercontent.com/26169771/79858492-cbddc880-83cf-11ea-93f7-4065d742d182.png)

**Expected behaviour**
Successfully reading the second dataframe, by skipping the first half of the rows without loading the full file into memory.

**Environment**
V100 with 16GBs

Hope it helps!
Miguel

**Comment by vuule** [comment]
@miguelusque there is an error in your repro script. The `nrows` is set to 7M, which is already half of the total number of rows. Then, you pass `skiprows=nrows//2`, which is only a quarter of the total number. With this, you try to read 3/4 of the entire file at once and probably run into the OOM issue because of that. Please try running the code above without diving `nrows` by 2.
I tried an equivalent repro at half size for my 8GB GPU. When reading the whole file, OOM happens as expected. When passing `skiprows=nrows//2`, it works fine.

**Comment by miguelusque** [comment]
Hi @vuule ,

Apologies for the wrong piece of code. I added an extra issue when trying to clean it up before creating the issue. 😅

I have renamed the variable `nrows` to `half_nrows`, and passed it to both parameters, `nrows=half_nrows` and `skip_rows=half_nrows`.

Considering the total amount of rows in the file is `14_000_000`, and `half_nrows=7_000_000`, I think that both commands should be able to create the dataframe.

![image](https://user-images.githubusercontent.com/26169771/80177779-f6609900-85fc-11ea-998a-ab08ba88fe9e.png)

Looking forward to your comments, and apologies for the inconveniences.

Regards,
Miguel

**Comment by vuule** [comment]
@miguelusque  I think I found the issue. the `skip_rows` parameter in your code should be `skiprows`. I'm surprised Python does not complain about this typo.

**Comment by miguelusque** [comment]
Hi @vuule ,

You are right. I have changed it to `skiprows` and it works like a charm. Thank you!

Btw, please notice that `cudf.io.avro. read_avro`, `cudf.io.orc. read_orc` , `cudf.io.parquet. read_parquet` have `skip_rows` in their interface, instead of `skiprows`. Maybe, it might be well-worth to follow the same parameter name accross cudf.io read methods.

Closing this issue now, and apologies for the misunderstanding.

Regards,
Miguel

**Comment by harrism** [comment]
So is this actually a parameter naming issue in the Python API? @miguelusque can you open an issue for that if so?

**Comment by miguelusque** [comment]
Sure! I’ll do.

The issue is because the python layer accepts **kwargs, which are not manually checked, so any typo as the above with result in a potential bug (like it happened to me).

I have gone through the cuDF python code for that part, and I am not 100% sure **kwargs is needed for this function (I have seen only one potential parameter passed as kwargs, but I am not 100% sure) (I am trying to setup a cuDF dev environment to perform some tests).

Finally, please notice that the skip_rows parameter name is not consistent across cuDF file readers skip_rows vs skiprows). I think it would might be a good idea to agree a unique parameter name.

**Comment by vuule** [comment]
>Finally, please notice that the skip_rows parameter name is not consistent across cuDF file readers (skip_rows vs skiprows). I think it would might be a good idea to agree a unique parameter name.

FWIW, `skiprows` is named as such for compatibility with the Pandas API. I don't know if other APIs have a reason to not follow the same naming.

**Comment by miguelusque** [comment]
I think we should stick to `skiprows`. AFAIK, the other functions in their equivalent CPU libraries do not support neither `skiprows` nor `skip_rows` parameter.

**Comment by miguelusque** [comment]
Hi @harrism / @vuule ,

As requested, I have opened a feature request detailing what it has been found during the resolution of this issue.

https://github.com/rapidsai/cudf/issues/5035

Hope it helps.

Regards,
Miguel
