### ISSUE TITLE
Add nightly conda builds

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#498]
Does this package publish nightly conda builds?  If so, where are they available?

**Comment by mrocklin** [comment]
I was just talking with @kkraus14 and he pointed me to the `cudf` package on the `rapidsai` channel, but said that this might not have survived a recent process change.

**Comment by mrocklin** [comment]
cc @mike-wendt

**Comment by thomcom** [comment]
True CI with tagged release builds seems like what we should be developing toward.

**Comment by mike-wendt** [comment]
This is on the roadmap and will be done as soon as possible. There are other stability issues that take priority at the moment.

**Comment by mrocklin** [comment]
No rush.  Was just curious if this was possible today.

**Comment by mike-wendt** [comment]
Also FWIW the plan for the next CI iteration will not only do nightly builds but also all PRs will be built with conda pkgs so developers can test their code more directly.

**Comment by mike-wendt** [comment]
Initial builds are happening currently. There are some issues with missing packages due to the transition by conda-forge that is also happening today. Will monitor but the jobs are setup to build packages for all commits on branches `branch-M.X`. They are pushed to the same conda channel and labeled with the branch they are built off of for the time being.

**Comment by mike-wendt** [comment]
New versioning and true nightlies are in place for cuDF. Closing, reopen if necessary.

**Comment by mrocklin** [comment]
WOOT.

**Comment by datametrician** [comment]
> WOOT.

Gimmick infringement...

**Comment by mrocklin** [comment]
FWIW, I've been independently wooting since even when it was cool.

**Comment by datametrician** [comment]
Shots fired...
