### ISSUE TITLE
[FEA] Add support for variable-width columns in interleave_columns

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#4988]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use `interleave_column` in cases where the columns are variable-width, such as strings.

**Describe the solution you'd like**
interleave_columns works with fixed-width types but I would also like to be able to use it with variable-width types.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by sriramch** [comment]
@andygrove i'm presuming you would need this capability not just for strings, but for dictionary types as well (although string support may be a more pressing need). is that correct?

**Comment by harrism** [comment]
I had been told that Spark doesn't need libcudf dictionary types.

**Comment by andygrove** [comment]
Yes, we were looking for this for strings. I'm not sure if/when we would need support for dictionary types.
