### ISSUE TITLE
[FEA] row-wise hashing using common hash functions like MD5 & SHA-2

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#4989]
**Is your feature request related to a problem? Please describe.**
We would like to use cudf to hash each row of a column, expanding the existing hash functionality to use other common hash functions like md5, sha2, etc.

**Describe the solution you'd like**
The existing hash functionality exists here:
https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/include/cudf/hashing.hpp#L34

Ideally this would be enhanced to support an additional optional argument that specifies which hash function to use.

**Additional context**
This feature request is somewhat similar to #4913 but hashes each row rather than hashing an entire column to a single value.

**Comment by revans2** [comment]
One of the hard parts with this is that most hashes are more than 64 bits.

MD5 is a 128bit hash
https://en.wikipedia.org/wiki/MD5
SHA1 is 160 bits
SHA2 is actually several different widths that we would want to support.
224, 256, 384, and 512.

So there is no simple way to return these types of hashes with existing cudf data types in a binary form.  Spark returns a hex encoded string for these results, which would be one option.  Of you could wait for array support to go in and return a binary array that is the correct length.

Hash functions that we would like to see that do fit into a long/int are CRC32, MurMur3 and xxhash64

**Comment by lmeyerov** [comment]
Growing the use case a bit for DPI-style & compression use cases:

Hashing / multi-hashing:

-- hash: rabin-karp, bloom filter
-- size: 8b - 128b

Collision checking:

-- Given a stream, what are the substring matches? <-- feels like categorical encoding with the option to throw out appears-only-once
