### ISSUE TITLE
[FEA] Allow merging an index column with data column using keyword "on"

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#5014]
In Pandas, if the dataframe on the left has index named `var1` and the dataframe on the right has a data column named `var1` then you can simply use `df1.merge(df2,on='var1')` however this doesn't work in cuDF

With cuDF, you need to write `df1.merge(df2,left_index=True,right_on='var1')`. It would be convenient for converting Pandas code to RAPIDS code to allow using the `on` parameter to refer to either an index or data column.

**Comment by kkraus14** [comment]
Pushing to 0.18
