### ISSUE TITLE
[BUG] Merge converts index to wrong dtype

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#5016]
**Describe the bug**
When you merge two dataframes in cuDF, the resulting index has the wrong dtype

**Steps/Code to reproduce bug**
df = cudf.DataFrame()
df['a'] = np.random.randint(0,10,1000).astype('int8')
df['b'] = np.random.uniform(0,1,1000).astype('int8')
te = df.groupby('a')[['b']].agg('mean').rename({'b':'b2'})
df = df.merge(te,left_on='a',right_index=True,how='left')
print(df.index.max())
`# THIS PRINTS 127`

**Expected behavior**
The original index was 0-999, the resultant index gets changed into numbers between -128 and 127 so it appears that the index was casted to int8

**Environment overview (please complete the following information)**
0.13.0+0.ga2804c3.dirty

**Comment by kkraus14** [comment]
cc @brandon-b-miller
