### ISSUE TITLE
[BUG] grouped_time_range_rolling_window() assumes ASC sort order

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#5031]
`grouped_time_range_rolling_window()` applies a rolling-window aggregation function across table-rows that are grouped by specified projection, and ordered by a timestamp column. It allows for windows to be specified in terms of timestamps, rather than static row offsets.

The current implementation of `grouped_time_range_rolling_window()` assumes that the rows are sorted in increasing order of timestamps. However, this need not always be the case, since a user may choose to order records in descending order. Thus, `PRECEDING` rows might possess *later* timestamps. Likewise, `FOLLOWING` records might be have an *earlier* nominal time.

`grouped_time_range_rolling_window()` should account for the sort-order of the input records.

**Comment by mythrocks** [comment]
For the record (excuse the pun), I have addressed this as part of the following PR: https://github.com/rapidsai/cudf/pull/4881 
(Please refer to [this commit](https://github.com/rapidsai/cudf/pull/4881/commits/a3091b692899ddd9f2c3e934c889d9069eb16d19).)

**Comment by harrism** [comment]
Is this fixed by #4881 @mythrocks ?

**Comment by mythrocks** [comment]
@harrism , @sameerz: Yes, this is now resolved, with #4881.
