### ISSUE TITLE
[BUG] `grouped_time_range_rolling_window()` should permit invocation without specifying grouping_keys

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#5032]
`grouped_time_range_rolling_window()` applies a rolling-window aggregation function across table-rows that are grouped by specified projection, and ordered by a timestamp column. It allows for windows to be specified in terms of timestamps, rather than static row offsets.

This function currently errors out when invoked without any grouping keys. In query engines like SparkSQL, it is commonplace (albeit inefficient) for users to apply window-functions to an unpartitioned dataset, using a time-range window. 

In this case, it would be preferable to treat the input as a single partition, instead of erroring out.

**Comment by mythrocks** [comment]
For the record (excuse the pun), I have addressed this as part of the following PR: #4881
(Please refer to this commit: https://github.com/rapidsai/cudf/pull/4881/commits/61e5bfc6db793aa2051ff8a150bbca0d20f14fc8.)

**Comment by harrism** [comment]
Generally I don't recommend fixing bugs in new feature PRs, because the new feature might have lower priority than the bug fix...

**Comment by harrism** [comment]
Is this fixed by 4881?

**Comment by mythrocks** [comment]
@harrism , @sameerz: Yes, this is now resolved.

**Comment by mythrocks** [comment]
> Generally I don't recommend fixing bugs in controversial new feature PRs, because the new feature might have lower priority than the bug fix...

Thank you, @harrism, I'll bear this in mind. I wasn't proud of mixing those concerns. They were all interrelated, so it saved time rebasing across 3 PRs. I'll try avoid this in the future.

**Comment by harrism** [comment]
It's easy to branch from an open PR branch and just make a PR that depends on another PR. Then when the dependency PR is merged, the dependent PR changes just get simpler. No rebases required.
