### ISSUE TITLE
[BUG] Rename skip_rows parameter to skiprows, and add parameter name checks

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#5035]
**Is your feature request related to a problem? Please describe.**
This feature request is related to issue #4970 .

I was incorrectly invoking cudf.read_csv method with the parameter `skip_rows`, instead of `skiprows`.

Python didn't complain about the wrong parameter name. I think that is because the python layer accepts `**kwargs`. These parameters are not manually checked in the code, so any typo as the above will result in a potential bug (like it happened to me).

I have gone through the cuDF python code for that part, and I am not 100% sure if `**kwargs` is needed for this function, because I have only seen one potential parameter passed as kwargs. (but I am not 100% sure, I am trying to setup a cuDF dev environment to perform some tests now).

Finally, please notice that the `skip_rows` parameter name is not consistent across cuDF file readers. `cudf.io.avro.read_avro`, `cudf.io.orc.read_orc` , `cudf.io.parquet.read_parquet` have `skip_rows` in their interface, while `cudf.io.csv.read_csv` has `skiprows` instead.

I would suggest to maintain `skiprows` instead of `skip_rows` because Pandas uses it and the other methods in their equivalent CPU libraries seem to do not support any kind of skip rows parameter.

**Comment by harrism** [comment]
This sounds like a bug, not a new feature.
