### ISSUE TITLE
cudf merge printing out dtypes 

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#504]
## Reporting a bug
cudf *merge* API printing out dtypes for all columns in jupyter notebook
System: Haswell 4xV100
Container: nvcr.io/nvidia/rapidsai/rapidsai:cuda9.2_ubuntu16.04

This happens on both of these cudf merges.  
```
    acq_df = acq_df.merge(names_df, how='left', on=['seller_name'])
```
Unexpected output below the notebook code cell.
```
1:int64
1:int32
1:float64
1:int64
1:int64
1:datetime64[ms]
1:datetime64[ms]
1:float64
1:float64
1:float64
1:float64
1:float64
1:int32
1:int32
1:int32
1:int64
1:int32
1:int32
1:int64
1:float64
1:int32
1:float64
1:float64
1:int32
2:int32
3:int32
```

- [ ] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. 
- [ ] I have included the version or commit hash I am using for reference.
- [ ] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [ ] I have included the following version information for:
      Arrow, cmake, CUDA, gcc/g++, Numpy, Pandas, Python
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by kkraus14** [comment]
I'll resolve this in a PR shortly, thanks for the report @kenhester!
