### ISSUE TITLE
[BUG] libcudf++ based CSV reader unable to parse hex values

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#5044]
**Describe the bug**
The new ported CSV reader unable to parse hex values and returning different values.

**Steps/Code to reproduce bug**
```
TEST_F(CsvReaderTest, HexTest)
{
  auto filepath = temp_env->get_temp_dir() + "DatesCastToTimestampS.csv";
  {
    std::ofstream outfile(filepath, std::ofstream::out);
    outfile << "0x0\n-0x1000\n0xfedcba\n0xABCDEF\n0xaBcDeF\n9512c20b\n";
  }

  cudf_io::read_csv_args in_args{cudf_io::source_info{filepath}};
  in_args.names          = {"A"};
  in_args.dtype          = {"hex"};
  in_args.header         = -1;
  auto result            = cudf_io::read_csv(in_args);

  const auto view = result.tbl->view();

  cudf::test::print(view.column(0));
}
```
returns
```
[0, 0, 0, 0, 0, 2501034507]
```

**Expected behavior**
Should be able to provide actual set of values
```
[ 0,  -4096, 16702650, 11259375,  1259375, 2501034507]
```

**Comment by OlivierNV** [comment]
Oh, no, it actually just doesn't like the `x` in `0x0` because it's not within the valid characters for hex digits -> was the `0x` prefix supported in the legacy path ?

**Comment by rgsl888prabhu** [comment]
Yes, it was. I found this issue because of a failing test case.

**Comment by OlivierNV** [comment]
@rgsl888prabhu Note that your set of reference values appear to be incorrect: entries 3 and 4 should be identical (only case is different).

**Comment by OlivierNV** [comment]
Oh I see: I couldn't find the place where the legacy path deal with the `0x` prefix, but that's because it didn't :)
What happened was that since the only digit before `'x'` was `'0'`, and `'x'` being an invalid digit, it was treated as 0, so it behaved just like a `'00'` prefix in front of the other digits, which had no effect since the failure was not reported and there was no `NaN`-replacement logic.

**Comment by rgsl888prabhu** [comment]
Oh, ok. So, isn't it possible to support with `x` in string, pandas supports this.

**Comment by kkraus14** [comment]
> Oh, ok. So, isn't it possible to support with `x` in string, pandas supports this.

Pandas supports this by falling back to using a Python function to convert hex to int and doing so via a UDF that executes in pure Python land. It's not quite comparable here.

**Comment by OlivierNV** [comment]
> Oh, ok. So, isn't it possible to support with `x` in string, pandas supports this.

Oh yeah, was just puzzled by why the legacy path worked in the first place. I already added the support for `0x` prefix as part of PR #5024 , pretty much just copy-pasting your test case and including it in the csv reader cpp tests moving forward.
