### ISSUE TITLE
[DOC] cudf.Series fillna preserves the Series's original dtype

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#5050]
Calling `fillna` on an empty Series (which has dtype of `object`) doesn't update the dtype.
```
import cudf

df = cudf.DataFrame({'id': [0, 1, 2], 'val': None})
df.dtypes

id      int64
val    object
dtype: object
```

In Pandas DataFrames, `fillna` as called below returns an `int64` Series.

Expected:
```
df['val'].fillna(-1)

0    -1
1    -1
2    -1
Name: val, dtype: int64
```

cudf keeps the original dtype:
```
df['val'].fillna(-1)

0    -1
1    -1
2    -1
Name: val, dtype: object
```

**Comment by kkraus14** [comment]
I think we made the conscious decision to not allow `fillna` to typecast the underlying column, so `-1` is instead converted to the type of the column, which is inferred to be `object` in this case (string).

What is the expected dtype of a column with a value of `None`?

**Comment by randerzander** [comment]
Interesting. Pandas uses `object` for an empty Series as well. I edited the description to reflect that.

Without allowing `fillna` to do a typecast, the recommended way to handle this is to re-cast the Series to the desired type before calling `fillna`?

**Comment by kkraus14** [comment]
> Without allowing `fillna` to do a typecast, the recommended way to handle this is to re-cast the Series to the desired type before calling `fillna`?

Yes. I think we made this decision because it's generally ambiguous but it's much cheaper to cast the scalar to the type of the column versus the column to the type of the scalar.

**Comment by randerzander** [comment]
Ok. I'll keep this issue open as a reminder to update the API docs to reflect this behavior.
