### ISSUE TITLE
Create doc examples for Arrow formatted data interop

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#506]
## Feature request

External applications generate Arrow formatted data they'd like to read into cuDF efficiently.

External applications want to consume cuDF results as Arrow formatted data.

cuDF supports both above use cases, documentation with examples needs to be written.

**Comment by kkraus14** [comment]
@randerzander @beckernick is this done?

**Comment by kkraus14** [comment]
Closing as this is stale.
