### ISSUE TITLE
type_dispatcher should support functors over subset of cuDF types

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#507]
This issue regards the master and v0.5 branches.

If you use the `type_dispatcher()` function and pass a class whose operator() is only implemented for _some_ of the types corresponding to `gdf_dtype`s - you will get a compiler error, since the type dispatcher has code calling all instantiations of that template. Instead, the dispatcher should use template meta-programming methods to only make the call if the operator is available, and otherwise fail somehow (e.g. with an assert, which is what it does for invalid `gdf_dtype`s).

The class with the `operator()` template should not be required to have some adjoining trait indicating what types are supported - the dispatcher can figure it out on its own, and it shouldn't even be terribly difficult.

@jrhemstad  FYI.

**Comment by jrhemstad** [comment]
I'd absolutely support this. I've seen several cases where this would be useful. 

I just haven't been sure the right way to go about implementing it. I'd love to hear any ideas.

**Comment by eyalroz** [comment]
@jrhemstad : How about [this way](https://stackoverflow.com/q/26366205/1593077)?

**Comment by harrism** [comment]
We decided not to do this, and stick with requiring users of type_dispatcher to implement a functor for every type, because it forces them to right understandable error messages and/or use SFINAE to handle unsupported types.
