### ISSUE TITLE
[FEA] groupby diff()

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#5079]
A powerful way to make features for time series models in Pandas is `df.groupby(col)[tar].diff()` or `df.groupby(col)[tar].agg('diff')`. It would be great to add this to cuDF

**Comment by aerdem4** [comment]
Would be nice to have groupby diff to accelerate this Kaggle kernel: https://www.kaggle.com/aerdem4/accelerating-trading-on-gpu-via-rapids

**Comment by beckernick** [comment]
@karthikeyann is the under active development, or should we remove the current assignment tag?
