### ISSUE TITLE
Kernel crashing

### ISSUE THREAD

**Issue by datascientistpur** [rapidsai/cudf#5082]
I am processing a huge file with strings(file size approx 5.12GB,rows 208 million).Whenever I try to concatenate strings the memory utilization shoots to 32GB and kernel crashes.

Request help in processing the same.

CUDF version:0.10.0
CUDA version:10.1
GPU:Tesla V100

**Comment by kkraus14** [comment]
@datascientistpur It sounds like you're running out of memory. Could you update to cudf 0.13 which is the latest release? The error messaging should be much better where we can help troubleshoot.
