### ISSUE TITLE
[DISCUSSION] tolerance-based test utilities for floating point columns

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#5095]
Right now libcudf provides two column equality testing utilities, both of which operate the same except for floating point values:
 - `expect_columns_equal`: compares floating point values exactly.
 - `expect_columns_equivalent`. compares floating point values using a tolerance based on ULP 4.

Due to imprecision and error in real-world data, cuspatial needs the ability to specify custom tolerances. The tolerance provided by `expect_columns_equivalent` is insufficient for meter or kilometer based measurements, for instance.

Do custom tolerance varients of `expect_columns_` belong in libcudf, and if so, what should those APIs look like?

**Comment by devavret** [comment]
Linking a relevant discussion: https://github.com/rapidsai/cudf/pull/5055#discussion_r419480147

There seems to be a common need to specify a custom tolerance.

> Do custom tolerance variants of `expect_columns_` belong in libcudf, and if so, what should those APIs look like?

Apparently, yes. libcudf doesn't just provide data movement operations but also arithmetic operations like in binaryops, unaryops, and aggregations like mean and standard deviation. Those will need to specify custom ULP as many standard functions in CUDA are not IEEE compliant and have a maximum ulp error other than 0.5

**Comment by jrhemstad** [comment]
Having the ULP be a parameter definitely makes sense. Though it feels a little awkward to make it a parameter for `expect_columns_equivalent` since it's a parameter that only applies to 2 types.

**Comment by jrhemstad** [comment]
In numerical code, a more common way of doing "approximate equality" is to compute a norm of the vector of floating point values and then compare the norms within a tolerance. That may be more appropriate for the kind of computation that cuSpatial is doing. It's also clear and obvious that it's specific to floating point values.

**Comment by devavret** [comment]
> Though it feels a little awkward to make it a parameter for `expect_columns_equivalent` since it's a parameter that only applies to 2 types

`expect_columns_equivalent` only takes care of two issues: floating point equality and null mask equivalence.

> That may be more appropriate for the kind of computation that cuSpatial is doing

Would've been fine if only clients of libcudf needed this. Turns out, libcudf internally needs it too. @sriramch, thoughts?

**Comment by sriramch** [comment]
`expect_columns_equivalent` performs near equal comparison of two values on the device. for the binaryops testing, there was a need to compare the value computed on the device (by the operator)  with the one computed on the host, and the tolerance limits varied based on the operator. hence, as @devavret points out, this is needed internally too. #5055 does this for the binary op.

**Comment by cwharris** [comment]
Accounting for ULP works when we're testing bit manipulation, but we also need the ability to test using real-world unit tolerances, such as seconds, meters, grams, etc. ULP doesn't help with this.

Custom ULP tolerances are one part of the solution. Absolute value tolerances solve something entirely different, but are still useful.

**Comment by cwharris** [comment]
Just to be perfectly clear, the use cases for absolute value tolerances are _entirely different_ than ULP tolerances. One cannot substitute for the other.

**Comment by cwharris** [comment]
> Having the ULP be a parameter definitely makes sense. Though it feels a little awkward to make it a parameter for `expect_columns_equivalent` since it's a parameter that only applies to 2 types.

I 100% agree with this, and I'm wondering about the practicality of it.

Afaict in total `expect_columns_equivalent` and `expect_tables_equivalent` are only used a total of 4 times. once in libcudf, and three times in cuspatial. libcudf is using it against integer and string columns (which has no effect and can be replaced with `_equals`). cuspatial is using it against floating point columns exclusively.

It might make sense to eliminate non-floating-point support in `expect_columns_equivalent`, which makes it less awkward to add a ULP parameter.

I would still like to have an `expect_columns_approx` function for testing real-world tolerances, though.

**Comment by jrhemstad** [comment]
> It might make sense to eliminate non-floating-point support in `expect_columns_equivalent`



> Afaict in total `expect_columns_equivalent` and `expect_tables_equivalent` are only used a total of 4 times.

That's because it was a relatively late addition. 

> It might make sense to eliminate non-floating-point support in expect_columns_equivalent

It's used for more than just floating point approximate equals. It also treats a non-nullable column equivalent to a nullable column with a mask whose bits are all set.

**Comment by cwharris** [comment]
> It also treats a non-nullable column equivalent to a nullable column with a mask whose bits are all set.

ULP and nullness seem tangential. What if we broke these options out as parameters?

**Comment by harrism** [comment]
I suggest we build the functionality we need for cuSpatial in cuSpatial. Work out the kinks. Then if it seems like it would be useful to contribute back to libcudf, open an issue or PR for it.

cuSpatial doesn't have nulls, and the discussion above shows that there are other differing needs in libcudf. So I reckon cuSpatial should serve itself first.

**Comment by harrism** [comment]
BTW, just saw this. https://github.com/rapidsai/cudf/issues/5105

**Comment by cwharris** [comment]
@jrhemstad 
> In numerical code, a more common way of doing "approximate equality" is to compute a norm of the vector of floating point values and then compare the norms within a tolerance. That may be more appropriate for the kind of computation that cuSpatial is doing. It's also clear and obvious that it's specific to floating point values.

Do you mean using a combination of binary and conditional operators to explicitly compare two numeric columns, rather than use a test utility? If so, that's less than ideal, since the "expect equal" won't print differences in terms of expected and actual results.

**Comment by harrism** [comment]
Yeah, like RMS error.

**Comment by devavret** [comment]
> the "expect equal" won't print differences in terms of expected and actual results.

Why not? [binary ops tests](https://github.com/rapidsai/cudf/blob/ee3f68acb7517258ba00632e738bfc64186878b0/cpp/tests/binaryop/assert-binops.h#L73) do it. The comparator can be customized.

**Comment by GregoryKimball** [comment]
Closing this for now. If cuSpatial has need of additional test utilities let's please create a new issue.
