### ISSUE TITLE
[FEA] Support INT96 timestamp type when writing Parquet

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#5096]
**Is your feature request related to a problem? Please describe.**
Spark 3.0 recently updated the default timestamp type for Parquet writing to revert to the Spark 2.x behavior which is to use INT96 timestamps.  This enabled compatibility by default with stable Presto and Hive releases that do not support the TIMESTAMP_MICROS type.  See https://github.com/apache/spark/pull/28450 for details.

Without write support for INT96 timestamps, Spark users with the RAPIDS plugin will not be able to use the accelerated cudf Parquet writer by default when writing timestamps unless they override the Spark config for the default Parquet timestamp type.  They will only be able to do so if they do not require Parquet file compatibility with other software that only supports INT96 timestamps.

Therefore it would be nice if the cudf Parquet writer supported writing timestamps in the Parquet INT96 timestamp format for improved compatibility.  The Spark RAPIDS plugin would then be able to support accelerating writing Parquet files containing timestamps with the default Spark configs.

**Describe the solution you'd like**
The Parquet writer args would contain a boolean flag to control whether timestamps are written as TIMESTAMP_MICROS or INT96.  Since cudf does not yet support timezones, we would only need support for converting UTC-based timestamps to the INT96 format.

**Describe alternatives you've considered**
The alternative is to require the user to override the Spark default Parquet timestamp type setting, but this is not a viable solution if the user requires Parquet file compatibility with other tools that only support INT96 timestamps.  Without cudf INT96 support, users requiring INT96 interop would have to revert to the slower Spark CPU Parquet writer.

**Comment by jrhemstad** [comment]
Looks like INT96 is deprecated in Parquet: https://issues.apache.org/jira/browse/PARQUET-323

**Comment by jlowe** [comment]
Yes, that is true.  However it doesn't change the user's reality of needing to interoperate with software packages that still require the old timestamp type.  That's what prompted Apache Spark to revert the default type relatively late in 3.0 development.

If INT96 support  for UTC timestamps is too much of a burden, then we'll have to document the incompatibility and hope INT96 is dropped from those other software packages in their stable releases sooner than later.

**Comment by jrhemstad** [comment]
> However it doesn't change the user's reality of needing to interoperate with software packages that still require the old timestamp type.

Sure, I don't have any dogs in this race (I don't think we're going to add a first clas INT96 type to libcudf). I was just curious about the INT96 type and did some searching and just happened to notice the issue that they were deprecating it.

**Comment by OlivierNV** [comment]
Should be a relatively simple addition, might be doable for 0.14 (~1 hour of coding + 2 weeks of PR review time).

**Comment by jlowe** [comment]
The biggest obstacle as I see it is handling the conversion from Gregorian to Julian calendar.  Seems like that requires a lookup table to convert, even for the UTC timezone.  See https://github.com/apache/spark/blob/branch-3.0/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/util/RebaseDateTime.scala#L357 and https://github.com/apache/spark/blob/branch-3.0/sql/catalyst/src/main/resources/gregorian-julian-rebase-micros.json.

Do we have a similar, reversed lookup table for translating INT96 values from Julian to Gregorian in the reader?

**Comment by OlivierNV** [comment]
> Do we have a similar, reversed lookup table for translating INT96 values from Julian to Gregorian in the reader?

It might be more complicated to go from from INT64->INT96 than the other way around, but the reader did not use a lookup table:
https://github.com/rapidsai/cudf/blob/branch-0.14/cpp/src/io/parquet/page_data.cu#L691

IIRC, there was some weird thing where the base should be noon instead of midnight, but it was needed to exactly match the pyarrow reader.

**Comment by OlivierNV** [comment]
Looking at the apache spark implementation, it looks like we may have incorrect INT96 timestamps if dealing with dates before 1582 (though it looks like arrow would have the same problem as well).
I'd definitely would rather avoid the ORC-like timezone LUT stuff.

**Comment by OlivierNV** [comment]
Yeah, no. Not gonna happen. I think for people who care about Spark 2.4 vs 3.0 compatibility for dates before 1582 should go with the Spark writer.
I'd suggest we stick with the way simpler Apache Arrow route for this
https://github.com/apache/parquet-cpp/blob/master/src/parquet/arrow/writer.h#L195
(It seems like the Spark "Proleptic Gregorian" problem is largely self inflicted)

**Comment by OlivierNV** [comment]
To clarify: I think the "Proleptic Gregorian" data format Spark uses is outside of parquet: the conversions could be done as a pre- or post-processing of the timestamp values (like timezones, ~ no conversion is actually necessary if just loading/writing/sorting). Alternatively, if the differences only occur for dates before 1582, one possible fallback would be to count the number of such timestamps and discard gpu results if an old data is found, redoing the operation with the slow spark-cpu path (assuming such occurrences are rare)

**Comment by harrism** [comment]
Since relative priority of this has not been discussed, I don't think it should be "on deck".

**Comment by OlivierNV** [comment]
FWIW, one possible alternative to the extra int96_timestamps parameter would be to just always using INT96 timestamps for nanoseconds timestamps (since there is currently no alternate way to preserve nanoseconds timestamp precision in parquet afaik).

**Comment by jlowe** [comment]
> one possible alternative to the extra int96_timestamps parameter would be to just always using INT96 timestamps for nanoseconds timestamps 

For Spark, we want a parameter to control this rather than auto-select based on timestamp type.  Spark uses microsecond-resolution timestamps internally, and we want to control the Parquet timestamp output format without forcing the cast to nanoseconds (and potentially overflowing the value during the process).

**Comment by revans2** [comment]
Another thing to keep in mind is that this is not the only place where there is not a clear one to one mapping between Parquet internal types and CUDF types.  For example Parquet supports a `BINARY` type which depending on the metadata could be a String or it could be a non-nullable list of bytes.  Which is separate from a nullable list of bytes which would be a Group typed as a list of byte values.  Spark makes a distinction between these two so we need a way to tell CUDF what compatible Parquet type we want to write.
