### ISSUE TITLE
[DOC] Stale links and suggestion for older API docs

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#5125]
## Report incorrect documentation
Hi,

While googling for some random cudf methods, sometimes I finish in an old version of the API (which is reasonable).

Nevertheless, if I try to navigate to [https://rapidsai.github.io/projects/cudf/en/latest/](https://rapidsai.github.io/projects/cudf/en/latest/) or [https://rapidsai.github.io/projects/cudf/en/stable/](https://rapidsai.github.io/projects/cudf/en/stable/), it redirects to 0.12 version.

Might I suggest to have a noticeable banner on top of all the older API docs clearly stating it belongs to an old version of the library, and also providing a link to the latest stable version?

Regards,
Miguel

**Comment by taureandyernv** [comment]
@mike-wendt @dillon-cullinan this seems like an ops issue.  I reposted this down the chain.  @kkraus14 can we keep this open until Ops corrects the issue, for public tracking?

@miguelusque thanks again!!

**Comment by kkraus14** [comment]
Where are these links from? The correct link for API docs is: https://docs.rapids.ai/api

**Comment by mike-wendt** [comment]
@miguelusque @kkraus14 closing this as @ajschmidt8 implemented a redirect that takes users from the old project links to the docs site and the current docs back in end of May 2020
