### ISSUE TITLE
[FEA] Support for `all_ipv4` and `all_hex` apis

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#5131]
**Is your feature request related to a problem? Please describe.**
It would be required to know whether a column is completely made-up of hex/ipv4 strings or not while converting them to integers.

**Describe the solution you'd like**
New apis that can handle the operation where it checks the whole column for being ipv4/hex.

**Additional context**
Discussion https://github.com/rapidsai/cudf/pull/5112#discussion_r421749789

**Comment by jrhemstad** [comment]
It seems overly specialized to bake a predicate and reduction together into a single API. This is just an `is_ipv4` + `all` reduction.

**Comment by rgsl888prabhu** [comment]
Yes, you are correct.

**Comment by kkraus14** [comment]
> It seems overly specialized to bake a predicate and reduction together into a single API. This is just an `is_ipv4` + `all` reduction.

For what it's worth I think we baked this exactly together for `all_integer` and `all_float` APIs. We're perfectly happy to just have an `is_ipv4` and `is_hex` API and then run the reduction afterwards.
