### ISSUE TITLE
[BUG] `cudf::binary_operation` ignores cuda context when registering JIT compiled PTX

### ISSUE THREAD

**Issue by magnatelee** [rapidsai/cudf#5133]
**Describe the bug**

`cudf::binary_operation` currently ignores the CUDA context of the caller thread, which makes the JIT compiled PTX loaded on a wrong device. Even worse is that `cudf::binary_operation` does not check the CUresult from the [kernel launch](https://github.com/rapidsai/cudf/blob/branch-0.13/cpp/src/binaryop/binaryop.cpp#L222-L232), so the error is being silently ignored, and noticed only with cuda-memcheck.

**Comment by jlowe** [comment]
Any idea how the calling thread's context is being ignored here?  Is this a case where a thread is being created without an explicit context and CUDA is auto-selecting a (potentially incorrect) device when it implicitly initializes the context?  If so that will cause problems in Spark with the RAPIDS plugins in a multi-GPU setup where the GPU device is assigned at the application level (not through `CUDA_VISIBLE_DEVICES`).

**Comment by devavret** [comment]
This is happening in Jit where the compiled kernel is being registered with only one context. On a subsequent call from a different context, this fails. It would affect cases where the different threads are assigned different devices, as is the case with @magnatelee's usage.

If spark uses one libcudf process per GPU then this won't affect it. It if uses one thread per GPU then it will.

**Comment by devavret** [comment]
I'm investigating a fix such that the in-memory cache is stored per context.

**Comment by jlowe** [comment]
> If spark uses one libcudf process per GPU then this won't affect it.

Ah, great to hear.  The Spark RAPIDS plugin currently only uses one GPU per process.

**Comment by harrism** [comment]
So what is left in this bug, @devavret ?

**Comment by devavret** [comment]
The issue also asks for a check
> Even worse is that cudf::binary_operation does not check the CUresult from the kernel launch, so the error is being silently ignored, and noticed only with cuda-memcheck.

I implemented this in https://github.com/NVIDIA/jitify/pull/67 and after that the `launch` call in Launcher.h needs to be replaced with`safe_launch`

**Comment by jrhemstad** [comment]
@devavret @magnatelee is this still an issue?

**Comment by devavret** [comment]
Not a lot is left. Just needs to replace the `launch` in https://github.com/rapidsai/cudf/blob/2780a8cea7743002d62b72c804ef693c8807d586/cpp/src/jit/launcher.h#L97 with `safe_launch`

**Comment by ttnghia** [comment]
Hi! How is this going?

**Comment by devavret** [comment]
I had a branch for it but I can't find it anymore. Must be lost in my corrupted git. Here's a new one #7510
