### ISSUE TITLE
[BUG] Unused extract_component function declaration in datetime.hpp

### ISSUE THREAD

**Issue by trevorsm7** [rapidsai/cudf#5134]
**Describe the bug**
In PR https://github.com/rapidsai/cudf/pull/4689, the `extract_component` function was replaced by `apply_datetime_op`, but the old declaration in the header was not removed.
https://github.com/rapidsai/cudf/blob/71d645c0d2782981697bd15333717e99ba37ee70/cpp/include/cudf/datetime.hpp#L47-L52

**Expected behavior**
Remove the unused `extract_component` declaration.

**Comment by harrism** [comment]
This appears to be fixed even though #5135 is still in progress. I can't find `extract_component()` in the code anymore.
