### ISSUE TITLE
[DISCUSSION] Erroring in boolean masking if mask has nulls

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#5146]
**Describe the issue**
Currently `cudf` considers `null` as False in boolean-masking/gathering, but pandas error if it has `null`/`None`. 

*pandas*
```
>>> import pandas as pd
>>> sr = pd.Series([1,2,3])
>>> mask = pd.Series([pd.NA, True, False])
>>> sr[mask]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rgsl888/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 907, in __getitem__
    if com.is_bool_indexer(key):
  File "/home/rgsl888/anaconda3/lib/python3.7/site-packages/pandas/core/common.py", line 136, in is_bool_indexer
    raise ValueError(na_msg)
ValueError: cannot mask with array containing NA / NaN values

```

*cudf*
```
>>> import cudf
>>> sr = cudf.Series([1,2,3])
>>> mask = cudf.Series([None, True, False])
>>> sr[mask]
1    2
dtype: int64
```

Will there be any disadvantage/issue if we follow pandas behavior? Is there any situation we can benefit from cudf behavior.

**Comment by kkraus14** [comment]
@jrhemstad @harrism We can enforce this from the Python by checking the null count before running the `apply_boolean_mask` operation, but we may want to change this from the libcudf side as well. I believe the original driving factor may have been cuDF expected behavior.

**Comment by kkraus14** [comment]
cc @revans2 @jlowe for expected Spark behavior for boolean masking when the mask has nulls.

**Comment by jlowe** [comment]
In Spark SQL, the `IF` and `CASE WHEN` statements used to select elements based on a boolean expression interpret the expression as if-and-only-if the mask is true then return the `IF` or `CASE WHEN` result otherwise return the `ELSE` result.  That's one case where Spark would expect `null` would be treated like a `false` (because neither are exactly `true`).

**Comment by jrhemstad** [comment]
I think `apply_boolean_mask` should be left as-is. It's functionality is a super set of what Pandas needs and Pandas behavior can easily be implemented in the Python layer with a `has_nulls` check.

**Comment by harrism** [comment]
> @jrhemstad @harrism We can enforce this from the Python by checking the null count before running the `apply_boolean_mask` operation, but we may want to change this from the libcudf side as well. I believe the original driving factor may have been cuDF expected behavior.

Please use has_nulls, not null_count.  I think the libcudf behavior is still needed by Spark, so let's leave as is and fix in Python like Jake says.

**Comment by kkraus14** [comment]
Thanks all for the discussion! Yup we'll move forward with using `has_nulls`.
