### ISSUE TITLE
[DISCUSSION] Improving Column Factory APIs

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#5150]
The "Problem"
-
Today, if we need to create a known-type column on-the-fly, multiple steps are involved:

```
auto tid = type_to_id<size_type>();
auto type = data_type{tid};
size_type size = ...;
auto numbers_column = std::make_unique<column>(
    type,
    size,
    mask_state::UNALLOCATED,
    stream,
    mr);
```
This is relatively straightforward, but can bloat code when creating multiple columns (especially when multiple _types_ of columns are needed). It's a relatively common pattern, and we might benefit from DRY'ing it up a bit. Columns can also need to be initialized from host-side memory, which adds aditional code...

A) Copy using thrust, temporarily allocating extra device memory.
```
auto numbers = vector<size_type>{ 5, 2, 7, 4, 3 };
rmm::device_vector d_numbers = numbers;
thrust::copy(
    rmm::exec_policty(stream)->on(stream),
    d_numbers.cbegin(),
    d_numbers.cend(),
    numbers_column.begin());
```
B) Create a device_buffer and column manually.
```
auto numbers = vector<size_type>{ 5, 2, 7, 4, 3 };
auto tid = type_to_id<size_type>();
auto type = data_type{tid};
auto buffer = rmm::device_buffer(
    numbers.data(),
    sizeof(size_type) * numbers.size(),
    stream,
    mr);
auto numbers_column = make_unique<column>(
    type,
    numbers.size(),
    buffer,
    cudf::mask_state::UNALLOCATED, // adding a mask bloats code, too
    0);
```
Proposed Solution
-
Consolidate column creation to column factory detail APIs.
```
auto numbers_column = detail::make_column<size_type>({ 5, 2, 7, 4, 3 });
```
```
auto numbers_column = detail::make_column<size_type>(
    { 5, 2, 7, 4, 3 },
    {}, // todo: explore best options for excluding a null mask
    mr,
    stream);
```
```
auto numbers_column = detail::make_column<size_type>(
    { 5, 2, 7, 4, 3 },
    { true, false, false, true, false},
    mr,
    stream);
```
Bonus points: find and replace appropriate code with the new detail APIs.

**Comment by harrism** [comment]
So this is basically proposing promoting some of the test wrapper functionality to libcudf core detail API.

I think the existing factories are fine for creating uninitialized columns. So I think this issue is really about creating columns that copy from non-column data sources (host vectors), correct?

**Comment by cwharris** [comment]
Mostly. Creating an uninitialized column of a compile time known type requires instantiating the data_type, but thats only 2 more calls, and its pretty straightforward.

**Comment by davidwendt** [comment]
I'm not picturing the example patterns in your proposed solution would be very common outside of test code with small datasets. I'm expecting something more like:
```
template<typename T, typename Iterator>
std::unique_ptr<column> make_column(
  Iterator begin, Iterator end, ... )
```
Here is one I created for strings at one point https://github.com/rapidsai/cudf/blob/520b100493e50e00112852d5f0fd8301d94f21bf/cpp/include/cudf/strings/detail/strings_column_factories.cuh#L35-L39

**Comment by cwharris** [comment]
@davidwendt Great point. Iterators would be far more useful.

**Comment by jrhemstad** [comment]
> So I think this issue is really about creating columns that copy from non-column data sources (host vectors), correct?

Agreed. 

> Creating an uninitialized column of a compile time known type requires instantiating the data_type, but thats only 2 more calls, and its pretty straightforward.

Your first example isn't using a factory at all, it's using the column constructor directly. This is how I would replace your example with a factory call.

```
auto numbers_column = make_numeric_column(type_to_id<size_type>, 
    size,
    mask_state::UNALLOCATED,
    stream,
    mr);
```

**Comment by cwharris** [comment]
> Your first example isn't using a factory at all

Totally overlooked that, sorry. Though you still need to instantiate a `data_type` as well, afaik.

```
auto numbers_column = make_numeric_column(
    data_type{type_to_id<size_type>()},
    size,
    mask_state::UNALLOCATED,
    stream,
    mr);
```
vs
```
auto numbers_column = make_column<size_type>(
    size,
    mask_state::UNALLOCATED,
    stream,
    mr);

```
Out of curiosity, where's the push-back for a non-host-initialized templated factory functions coming from? Template instantiation overhead?

**Comment by GregoryKimball** [comment]
Closing this for now. I propose that we add an example in `cpp/examples/` that uses host vectors with the current APIs, and then from there we could evaluate making a diff to the column factory APIs.
