### ISSUE TITLE
[DOC] cross link rmm and cudf documentation

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#5152]
## Report needed documentation

**Report needed documentation**
Documentation of cudf APIs uses rmm APIs in arguments. These rmm APIs in arguments are not linked to rmm documentation.

**Describe the documentation you'd like**

For example, 
The doc page https://docs.rapids.ai/api/libcudf/0.13/classcudf_1_1timestamp__scalar.html
has following rmm API usage of `rmm::mr::device_memory_resource`
this could be linked to 
https://docs.rapids.ai/api/rmm/stable/classrmm_1_1mr_1_1device__memory__resource.html

**Possible Solution**
This can be achieved by using [doxgen TAGFILES](http://www.doxygen.nl/manual/external.html)
This needs change in both cudf and rmm repo `Doxyfile`s.

**Comment by karthikeyann** [comment]
openCV doxygen example for cross referencing via weblink. 
https://docs.opencv.org/3.4/d3/dff/tutorial_cross_referencing.html

**Comment by harrism** [comment]
Great suggestion!

**Comment by ajschmidt8** [comment]
Hey @karthikeyann. The two PRs below should resolve this issue. Let me know if you have any questions.

https://github.com/rapidsai/rmm/pull/672
https://github.com/rapidsai/cudf/pull/7149

**Comment by ajschmidt8** [comment]
@harrism, @karthikeyann, just to follow up on this, it looks like the `cudf` docs have been successfully cross-linked to `rmm`. You can confirm on the page below. Please ensure everything is working as expected.

https://docs.rapids.ai/api/libcudf/nightly/classcudf_1_1column.html
