### ISSUE TITLE
cudf read_csv_strings reads doubled quoted float numbers incorrectly

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cudf#516]
## Reporting a bug

- [x] I am using the latest version of cuDF from conda, built from `master`, or
built from the latest tagged release. -- cuDF 0.4.0 from master
- [x] I have included the version or commit hash I am using for reference.
- [x] I have included the following environment details:
      Linux Distro, Linux Kernel, GPU Model
- [x] I have included the following version information for:
      Arrow, cmake, CUDA 9.2, gcc/g++5.4, Numpy, Pandas, Python3.5.5
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

A client gives me a csv file ( a small version of the csv is attached here -- adding .txt suffix since the site does not take .csv) that has columns of strings and floats. All the strings and floats have double quotes around them. 

When i use pandas:
```
import pandas as pd
df = pd.read_csv('xl_100_4lines.csv', delimiter=',',
                 names = ['str1','str2','str3','str4','n1','n2','n3','n4','n5','n6'],
                 skiprows=1)

print(df.head(2))
```

The output is correct:
        str1      str2      str3     str4        n1        n2         n3  
0   tourers  spooneys  savagery   bialis  0.369141  4.040020  28.916602   
1  denounce  nymphean    soloed  serfage  0.456655  4.787483  35.468340   
...

However, if i use cudf.io.csv.read_csv_strings, the float numbers are not loaded correctly due to the double quotes. 
```
columns = cudf.io.csv.read_csv_strings('xl_100_4lines.csv', delimiter=',',
                                       names = ['str1','str2','str3','str4','n1','n2','n3','n4','n5','n6'],
                                       dtype=['str','str','str','str','float','float','float','float','float','float'],
                                       quoting=True,
                                       doublequote=True,
                                       skiprows=1)

print(columns[0])
print(columns[3])
print(columns[4])
```

Output:
['tourers', 'denounce', 'airspeed', 'ens']    
['bialis', 'serfage', 'haematin', 'transom']
            
0 -139.63084
1 -139.54337
2  -139.4468
3 -139.64496

Apparently the column 4 float numbers are wrong. I played with quoting and doublequote options but with no avail. The temp solution i am using to allow me to go on is to remove all the quotes of float numbers from the csv file. 

Please let me know if you need more info. 
Doris 

[xl_100_4lines.csv.txt](https://github.com/rapidsai/cudf/files/2676734/xl_100_4lines.csv.txt)

-->

**Comment by j-ieong** [comment]
Assign myself in spirit (since cannot actually do it on GitHub yet).

The recent PR with quotations options only handled quoted strings. We need a small fix to handle quoted numbers (basically ignore surrounding quotechar).

**Comment by dorisnvidia** [comment]
Perfect. I cloned the master branch this morning, rebuilt cudf, and the issue is fixed. THANKS.
