### ISSUE TITLE
[FEA] error checking on date/time parseing

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#5160]
**Is your feature request related to a problem? Please describe.**
For spark we need to be able to parse date/timestamp strings into timestamps.  But if spark sees something that is invalid it returns a null.  If cudf sees something invalid.
```
 Invalid formats are not checked. If the string contains unexpected
 or insufficient characters, that output row entry's timestamp value is undefined.
 Negative timestamp values are not currently supported. These would have
 dates formatted before 1970-01-01.
```

We get undefined behavior.  We cannot truly support spark with this API as it stands today.

**Describe the solution you'd like**
It would be great to support negative ts values and to return a null for anything that does not conform with the given pattern.

**Describe alternatives you've considered**
I would have to write my own, because I have to support data that is improperly formatted.  I still might have to do it because of https://github.com/rapidsai/cudf/issues/5126

**Comment by kkraus14** [comment]
We also have `is_integer`, `is_float`, `is_*` APIs that return a boolean mask as to whether the given string element is the expected type. We could do something similar here which would allow you to use that boolean mask to fill with nulls, as from the Python side we'd likely want to throw an exception as opposed to returning nulls on invalid entries.

**Comment by harrism** [comment]
So is the request here then to add `is_timestamp`?

**Comment by kkraus14** [comment]
ping @revans2 for response to above

**Comment by revans2** [comment]
Sorry @harrism I guess I missed this. We have started to do a bunch of nasty things with regular expressions to try and work around this which I would love to get rid of, or replace as much of it as possible.

So yes if we could get a function that would take a column of strings along with a format, and would return a column of boolean values saying if it matches that format or not it would be great, because that would let us reduce the number of regular expressions that we use. 

It would not solve the issue of negative time stamps, but I have not tested that in a while and I think it might be fixed.

@andygrove is parsing of timestamps prior to 1970 working?

**Comment by andygrove** [comment]
@revans2 I just ran `CastOpSuite` after modifying all the test dates and timestamps to be pre-1970 and it worked in general but did highlight a bug where the number of seconds is rounded up incorrectly for timestamps that also have a millisecond component. Is this the issue you had seen before or should I file a new issue for this?

**Comment by revans2** [comment]
@andygrove please file a new issue for that.
