### ISSUE TITLE
[BUG] read_csv appear to sometimes lose the last row

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#5161]
Seeing the CSV reader “lose” a row unexpectedly at various row sizes in the millions. It looks to be the last row, but it's not completely consistent in the first place.

Noticed this in an environment with cuDF commit `520b100`. This was not happening in cuDF commit `b12f24d` from 2020-05-07. @rgsl888prabhu has tracked it to https://github.com/rapidsai/cudf/pull/5024

Haven’t been able to pin down a minimal example of this yet.

**Comment by OlivierNV** [comment]
Is the file being read through byte_range (through dask), or skiprows+nrows or just loaded in one shot ?

**Comment by rgsl888prabhu** [comment]
Loaded in one shot

**Comment by OlivierNV** [comment]
Is there a way to check if there is some sort of "magic threshold" around 64MB, eg: you lose the last row if the file is 65MB or larger, but everything is fine if the file size is 63MB or smaller ? (also would be good to confirm that the problem goes away if adding an extra `\n` at the end of the file)

**Comment by rgsl888prabhu** [comment]
I tried sample file size bigger than 65 MB and it didn't reproduce the issue and adding `\n` didn't resolve the issue. It seems the issue is particular to the example test file that @beckernick provided.

**Comment by OlivierNV** [comment]
Found the problem: the last block may start in EOF state if the data end was in range of the previous block but outside of chunk_size, in which case the last row offset ends up being ignored (fix is to only enter EOF state when processing the data end, otherwise stay in pass-through state)
