### ISSUE TITLE
[FEA] DataFrame level support for unique function

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/cudf#5170]
Is your feature request related to a problem? Please describe.
I wish cuDF could run unique in the DataFrame level.

We need a version of "unique" function in the DataFrame level that runs on the columns in parallel. Right now, "unique" (and other functions as well) function is only available in the Series level which only allows us to run this function one column at a time. For instance, if we have 'C1', 'C2', 'C3', ..., 'C20' as categorical columns, we have to call the value_counts for 'C1', then for 'C2', ...., then for 'C20' one by one. I think this sequential computing approach is causing us to lose significant amount of time because we can calculate the value counts for 'C1', 'C2', 'C3', ..., 'C20' simultaneously in one CUDA kernel.

Also, some of these operations can be possibly fused into one or couple of CUDA kernels.

Describe the solution you'd like
Creating CUDA kernels for these functions to run on columns of DataFrame in parallel.

Describe alternatives you've considered
One easy and fast solution might be to create N number of streams where N is the number of columns in the DataFrame. Then, N number of kernel calls can be made using these streams. This might not be as fast as the one kernel approach since there will be a delay to create streams but it can provide a level of speedup. Maybe streams can be created at the beginning of a program in the cudf level and these streams can be used whenever need.

**Comment by jrhemstad** [comment]
>  I think this sequential computing approach is causing us to lose significant amount of time because we can calculate the value counts for 'C1', 'C2', 'C3', ..., 'C20' simultaneously in one CUDA kernel.

This would need to be benchmarked and profiled. Furthermore, I really don't think we want to get into the business of adding a fused version of every Series level function. That would be awfully specialized and onerous to maintain.

Doing these operations on independent streams is a much more maintainable solution.

**Comment by harrism** [comment]
The unique values are different for every column. So you would only benefit if the kernel launch overhead is the bottleneck. Probably only for tables of small number of rows, in other words.

As Jake says, requires benchmarking. Not going to prioritise this high right now without evidence it is a problem.

**Comment by oyilmaz-nvidia** [comment]
Yes, the unique values are different for every column but while calculating unique values of column one, we can also calculate it for column two at the same time (maybe in a different kernel call). 

I know cudf doesn't support the multiple streams right now but I was thinking one way to see a proof is to create multiple streams and make multiple kernel calls using these streams. If we ignore the time spent to create streams for now, that at least should give an idea on the possible speedup.

value_count and unique functions are the ones we spent most of the time in pre-processing (and they are taking a lot of time). And, now, we are calling these functions sequentially for every column one by one.

**Comment by harrism** [comment]
Can you provide a profile demonstrating the bottleneck?

**Comment by beckernick** [comment]
This is not supported in the pandas API. @oyilmaz-nvidia is this still a bottleneck for you?
