### ISSUE TITLE
[FEA] DataFrame level support for std function

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/cudf#5172]
Is your feature request related to a problem? Please describe.
I wish cuDF could run std function in the DataFrame level.

**Comment by devavret** [comment]
What would this return?
- A per column std value? (output is a vector of scalars, vector.size == num_columns)
- One std value for the entire dataframe?

IOW, Is the motivation behind this purely for performance or is this something that can't be done currently?

**Comment by harrism** [comment]
I think this should be combined with #5171 and #5173 and only one of the 3 kept open (and fixed together).

**Comment by galipremsagar** [comment]
@oyilmaz-nvidia , Is this the feature you are looking for : https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.std ?

**Comment by harrism** [comment]
See #5048. This is independent of whether cuDF supports the operation. I believe the request is for an optimization -- perform on all columns in a single kernel launch. IMO that's an implementation detail and *if* performance *is a problem* and that problem can be demonstrated with a reproducer, then we should fix it.

**Comment by beckernick** [comment]
`DataFrame.std` has been implemented, with the following loose performance on a V100 and a CPU with 40 physical cores.

```python
import cudf
​
gdf = cudf.datasets.randomdata(
    nrows=1000000,
    dtypes={"id": int, "w": int, "x": float, "y": float, "z": float}
)
df = gdf.to_pandas()
​
%time _ = df.std()
%time _ = gdf.std()
CPU times: user 27.9 ms, sys: 0 ns, total: 27.9 ms
Wall time: 27.6 ms
CPU times: user 2.34 ms, sys: 0 ns, total: 2.34 ms
Wall time: 2.14 ms
```

I'm going to close this issue. If this proves to be a bottleneck in a workflow, please feel free to reopen it.
