### ISSUE TITLE
[FEA] DataFrame level support for count function

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/cudf#5176]
Is your feature request related to a problem? Please describe.
I wish cuDF could run count function in the DataFrame level.

**Comment by galipremsagar** [comment]
This API now exists in cudf: https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.count

**Comment by harrism** [comment]
@galipremsagar I think you closed a bunch of issues based on #5048 which are requests for optimization. (However since they didn't have details I think it's OK to keep them closed until the details are available.)
