### ISSUE TITLE
[FEA] DataFrame level support for sum function

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/cudf#5177]
Is your feature request related to a problem? Please describe.
I wish cuDF could run sum function in the DataFrame level.

**Comment by galipremsagar** [comment]
@oyilmaz-nvidia Is this what you are looking for?

```python
In [8]: df = cudf.DataFrame({'x':[1,2,3], 'y':[4,5,6]})                                                            

In [10]: df                                                                                                        
Out[10]: 
   x  y
0  1  4
1  2  5
2  3  6

In [11]: df.sum()                                                                                                  
Out[11]: 
x     6
y    15
dtype: int64

```

**Comment by oyilmaz-nvidia** [comment]
@galipremsagar Yes, this is exactly what I am looking for. Thanks!

**Comment by galipremsagar** [comment]
@oyilmaz-nvidia Thanks for confirming. Closing this FEA as you can try this out in `branch-0.14` or `branch-0.15`

**Comment by oyilmaz-nvidia** [comment]
@galipremsagar Thanks for this new feature in cudf. Quick question, I also created feature request for similar functions like mean, std, etc. Do you know if they are also available or not?

**Comment by galipremsagar** [comment]
@oyilmaz-nvidia Yes, there are. Will be pointing to their docs in their threads.

**Comment by galipremsagar** [comment]
https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.sum
