### ISSUE TITLE
[FEA] A DataFrame function to get std, var, mean, sum at the same time

### ISSUE THREAD

**Issue by oyilmaz-nvidia** [rapidsai/cudf#5178]
**Is your feature request related to a problem? Please describe.**
std, var, mean, and sum functions can be calculated at the same time in the dataframe level and returned to the user. Right now, we call, mean, std, and var sequentially.

**Comment by GregoryKimball** [comment]
Closing this until we have data showing significant negative impact from sequential DataFrame calculations.

**Comment by vyasr** [comment]
I'm not sure if this was a request to change cuDF's internals or a request to change the API. FWIW it's already possible to do the latter with `agg`:
```
>>> cudf.DataFrame({'a': [1., 2, 3, 4]}).agg(("std", "var", "sum", "mean"))
              a
std    1.290994
var    1.666667
sum   10.000000
mean   2.500000
```
