### ISSUE TITLE
[FEA] Query rmm allocation_mode from python side

### ISSUE THREAD

**Issue by felipeblazing** [rapidsai/cudf#5179]
**Is your feature request related to a problem? Please describe.**
Would like to be able to know how rmm default allocator is currently configured.

**Describe the solution you'd like**
basically an api that is something along the lines of
rmm.is_managed()
rmm.uses_pool()
rmm.pool_size()

To know how it was initialized. 

**Describe alternatives you've considered**
Writing my own in c++ and making cython bindings

**Comment by jrhemstad** [comment]
This isn't really possible. RMM initialization is [going away](https://github.com/rapidsai/rmm/issues/301). There is no single concept of `uses_pool()` as there are potentially many different kinds of pool suballocators. Likewise, a pool suballocator may have many pools making `rmm.pool_size()` meaningless.

**Comment by harrism** [comment]
Well, presumably the Python API of cuDF is going to own whatever MRs it uses, and will provide some way of selecting the mode. If it does this,  it can provide APIs as requested.

**Comment by felipeblazing** [comment]
So are we saying the only way to know what properties a resource contains is to know before the fact what MR is being used and what properties it contains? I ask this because depending on what kind of allocations a resource has we will change how a query plan is executed and given the fact that the user can set this it feels very difficult to make the right choice. 

The way we are handling it now is basically slapping the user in the face and saying. Its cute that you had a default memory resource before. We just invalidated it and made you a new one buddy.

**Comment by felipeblazing** [comment]
> Well, presumably the Python API of cuDF is going to own whatever MRs it uses, and will provide some way of selecting the mode. If it does this, it can provide APIs as requested.

Right now the initalization parameters to rmmInitialize are discarded. Whatever you selected goes away in python land and is not stored anywhere.

Mostly here I am saying. There are characteristics of memory resources. Being able to query information about those resources can allow those of us using the resources to be more intelligent about them. Like preferring an algorithm that has less random i/o when you are using uvm.

**Comment by jrhemstad** [comment]
> There are characteristics of memory resources.

The problem is that there are a boundless number of possible `device_memory_resources`, which means there are a boundless number of possible properties. It is nearly impossible to come up with a set of properties that make sense to query all possible resources. 

Even something like "is_uvm" isn't really possible because a `device_memory_resource` could easily use UVM for some allocations, but not _all_ allocations. So it wouldn't make sense to query `mr.is_uvm()` because it would depend on the allocation you requested. 

Specific to UVM, what you would have to do is make the allocation, and then query it with `cudaPointerGetAttributes` as you said.

**Comment by felipeblazing** [comment]
Ok I understand the reason why my request is problematic.

**Comment by jrhemstad** [comment]
@felipeblazing what you _can_ do is compare if a resource is equal to another resource. So you could do `mr->is_equal(managed_memory_resource{})` to detect if the resource is equivalent to a `managed_memory_resource`.

Granted, that doesn't solve your original request, but I do want to remind that it is an available tool.

**Comment by harrism** [comment]
I would like to reiterate my comment above. 

> presumably the Python API of cuDF is going to own whatever MRs it uses, and will provide some way of selecting the mode. If it does this, it can provide APIs as requested.

I would like @shwina or @kkraus14 to comment. I think this is a reasonable request, unless the cuDF Python API plans to also move toward user-defined resources.

**Comment by shwina** [comment]
Yes -- the Python API will also be moving towards user-defined resources. However, we'll hold a reference to the user-provided memory resource so that they don't have to worry about keeping it alive.

The API will look something like this:

```python
import rmm

rmm.mr.set_memory_resource(
    rmm.mr.CUDAManagedMemoryResource(...)
)
```
