### ISSUE TITLE
Extend DataFrame::sort_values for sorting along multiple columns

### ISSUE THREAD

**Issue by muellren** [rapidsai/cudf#518]
## Feature request

`sort_values(by, ascending=True)`  of `DataFrame` currently only supports sorting along one column, i.e., by and ascending can only take a single value. 

In Pandas, DataFrame `sort_values(by, ascending)` can take a `str` or a list of `str` for `by` and a `bool` or a list of `bool` for `ascending` respectively:

http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html#pandas.DataFrame.sort_values

**Comment by jrhemstad** [comment]
This will be fixed by: https://github.com/rapidsai/cudf/issues/518  as soon as the Python side is updated to use it.

**Comment by kkraus14** [comment]
@jrhemstad I think you linked to the incorrect PR / issue number.
