### ISSUE TITLE
[GPUCI] Adopt the copyright check script from cuML into cuDF

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#5186]
**Is your feature request related to a problem? Please describe.**
Just learned that cuML has a script that runs as part of the CI style checks that verifies that all modified files have a proper copyright notice. We should adopt that script into cuDF.

**Describe the solution you'd like**
https://github.com/rapidsai/cuml/blob/branch-0.14/ci/checks/copyright.py

**Comment by GregoryKimball** [comment]
Closed by #10253 and #10290
