### ISSUE TITLE
[BUG] Possible memory leak during cuDF compilation?

### ISSUE THREAD

**Issue by mkandes** [rapidsai/cudf#5197]
**Describe the bug**

Observe huge spike in memory usage during compilation of cuDF from source. Up to 71 GBs at peak.

**Steps/Code to reproduce bug**

See Singularity definition file below. Use to run 'sudo singularity build --sandbox test Singularity'. Have not tested build process in native/VM-only environment. 

----
Bootstrap: shub
From: mkandes/ubuntu-cuda-openmpi:latest

%labels

    APPLICATION_NAME rapids
    APPLICATION_VERSION 0.13.0
    APPLICATION_URL https://rapids.ai

    AUTHOR_NAME Marty Kandes
    AUTHOR_EMAIL mkandes@sdsc.edu

    LAST_UPDATED 20200513

%setup

%environment

    # Set default miniconda environment
    export PATH="/opt/miniconda3/bin:${PATH}"

%post -c /bin/bash

    # Set operating system mirror URL
    export MIRRORURL='http://us.archive.ubuntu.com/ubuntu'

    # Set operating system version
    export OSVERSION='bionic'

    # Set system locale
    export LC_ALL='C'

    # Set debian frontend interface
    export DEBIAN_FRONTEND='noninteractive'

    # Set paths to CUDA binaries and libraries
    export CUDA_HOME='/usr/local/cuda-10.1'
    export PATH="${CUDA_HOME}/bin${PATH:+:${PATH}}"
    export LD_LIBRARY_PATH="${CUDA_HOME}/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

    # Set paths to OpenMPI binaries and libraries
    export PATH="/opt/openmpi-3.1.4/bin:${PATH}"
    export LD_LIBRARY_PATH="/opt/openmpi-3.1.4/lib:${LD_LIBRARY_PATH}"

    # Set paths to OSU Microbenchmarks binaries
    export PATH="/opt/omb-5.6.2/collective:${PATH}"
    export PATH="/opt/omb-5.6.2/one-sided:${PATH}"
    export PATH="/opt/omb-5.6.2/pt2pt:${PATH}"
    export PATH="/opt/omb-5.6.2/startup:${PATH}"

    # Upgrade all packages to their latest versions
    apt-get -y update && apt-get -y upgrade

    # Install miniconda3
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
    chmod +x Miniconda3-latest-Linux-x86_64.sh
    ./Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda3

    # Setup conda environment
    export PATH="/opt/miniconda3/bin:${PATH}"
    export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

    # Install common python packages 
    conda install -y jupyterlab
    conda install -y numpy
    conda install -y matplotlib
    conda install -y pandas
    conda install -y plotly
    conda install -y scipy
    conda install -y scikit-learn
    conda install -y scikit-image
    conda install -y seaborn
    conda install -y statsmodels
    conda install -y opencv

    # Install GPU-accelerated python packages
    conda install -y cupy
    conda install -y numba

    # Install additional python packages
    conda install -y astropy
    conda install -y biopython
    conda install -y h5py
    conda install -y nltk
    conda install -y sympy

    # Make high-level directory to hold all RAPIDS libraries
    export RAPIDS_VERSION='0.13.0'
    export RAPIDS_HOME="/opt/rapids-${RAPIDS_VERSION}"
    mkdir -p "${RAPIDS_HOME}"

    # Install rmm dependencies
    conda install -y clang -c conda-forge
    conda install -y clang-tools -c conda-forge
    conda install -y cmake
    conda install -y cffi
    conda install -y pytest
    conda install -y cython

    # Download, build, and install rrm (RAPIDS Memory Manager)
    export RMM_HOME="${RAPIDS_HOME}/rmm-${RAPIDS_VERSION}"
    git clone --recurse-submodules https://github.com/rapidsai/rmm.git "${RMM_HOME}"
    cd "${RMM_HOME}"
    git checkout "v${RAPIDS_VERSION}"
    ./build.sh librmm rmm
    cd python
    python setup.py build_ext --inplace
    python setup.py install

    # Install cuDF dependencies 
    apt-get -y install libboost-all-dev

    pip install cmake_setuptools

    conda install -y pyarrow
    conda install -y fastavro
    conda install -y notebook
    conda install -y fsspec
    conda install -y sphinx
    conda install -y sphinx_rtd_theme
    conda install -y sphinxcontrib-websupport
    conda install -y nbsphinx -c conda-forge
    conda install -y numpydoc
    conda install -y recommonmark
    conda install -y pandoc
    conda install -y pip
    conda install -y partd
    conda install -y flake8
    conda install -y black
    conda install -y isort
    conda install -y pre_commit -c conda-forge
    conda install -y dask
    conda install -y distributed
    conda install -y streamz
    conda install -y dlpack -c conda-forge
    conda install -y arrow-cpp
    conda install -y boost-cpp
    conda install -y double-conversion
    conda install -y rapidjson
    conda install -y flatbuffers
    conda install -y hypothesis

    # Download, build, and install cuDF and its supporting libraries
    export CUDF_HOME="${RAPIDS_HOME}/cudf-${RAPIDS_VERSION}"
    git clone https://github.com/rapidsai/cudf.git "${CUDF_HOME}"
    cd "${CUDF_HOME}"
    git checkout "v${RAPIDS_VERSION}"
    git submodule update --init --remote --recursive
    ./build.sh --allgpuarch

    # Cleanup
    apt-get -y autoremove --purge
    apt-get -y clean

    # Update database for mlocate
    updatedb

%files

%runscript

%test
----

**Expected behavior**

Singularity container/sandbox build will fail if not enough memory is available on build system.

**Environment overview (please complete the following information)**
 - Environment location: Singularity v2.6.1 on Ubuntu 18.04 LTS
 - Method of cuDF install: From source with conda help
  - If method of install is [Singularity], provide commands used: sudo singularity build --sandbox test Singularity'

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

Singularity test:/opt/rapids-0.13.0/cudf-0.13.0> ./print_env.sh 
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit fef2a2b514e981d19af162991c82471e2efec84a (HEAD, tag: v0.13.0, origin/master)
     Merge: a2804c35b a8d129e35
     Author: Mike Wendt <mike.wendt@me.com>
     Date:   Wed Apr 1 14:24:47 2020 -0400
     
     REL v0.13.0 CHANGELOG Updates
     
     Closes #4775
     **git submodules***
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
     e3f867027c1d9603b5a677795900465b9fac9cb8 thirdparty/jitify (heads/cudf)
     cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx (0.8.1-99-gcdcda48)
     a97a7380c76346c22bb67b93695bed19592afad2 thirdparty/libcudacxx/libcxx (heads/rapidsai-interop)
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux sbld 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
     
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              44
     On-line CPU(s) list: 0-43
     Thread(s) per core:  1
     Core(s) per socket:  1
     Socket(s):           44
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               63
     Model name:          Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz
     Stepping:            2
     CPU MHz:             2494.222
     BogoMIPS:            4988.44
     Virtualization:      VT-x
     Hypervisor vendor:   KVM
     Virtualization type: full
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            4096K
     L3 cache:            16384K
     NUMA node0 CPU(s):   0-43
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat md_clear
     
     ***CMake***
     /opt/miniconda3/bin/cmake
     cmake version 3.14.0
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-10.1/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Apr_24_19:10:27_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.168
     
     ***Python***
     /opt/miniconda3/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /opt/miniconda3/bin:/opt/omb-5.6.2/startup:/opt/omb-5.6.2/pt2pt:/opt/omb-5.6.2/one-sided:/opt/omb-5.6.2/collective:/opt/openmpi-3.1.4/bin:/usr/local/cuda-10.1/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
     LD_LIBRARY_PATH                 : /opt/openmpi-3.1.4/lib:/usr/local/cuda-10.1/lib64:/.singularity.d/libs
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/miniconda3/bin/conda
     # packages in environment at /opt/miniconda3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     alabaster                 0.7.12                   py37_0
     appdirs                   1.4.3            py37h28b3542_0
     arrow-cpp                 0.15.1           py37h7cd5009_5
     asn1crypto                1.3.0                    py37_0
     astropy                   4.0.1.post1      py37h7b6447c_1
     attrs                     19.3.0                     py_0
     babel                     2.8.0                      py_0
     backcall                  0.1.0                    py37_0
     biopython                 1.76             py37h7b6447c_0
     black                     19.10b0                    py_0
     blas                      1.0                         mkl
     bleach                    3.1.4                      py_0
     bokeh                     2.0.2                    py37_0
     boost-cpp                 1.71.0               h7b6447c_0
     brotli                    1.0.7                he6710b0_0
     bzip2                     1.0.8                h7b6447c_0
     c-ares                    1.15.0            h7b6447c_1001
     ca-certificates           2020.1.1                      0
     cairo                     1.14.12              h8948797_3
     certifi                   2020.4.5.1               py37_0
     cffi                      1.14.0           py37h2e261b9_0
     cfgv                      3.1.0                      py_0    conda-forge
     chardet                   3.0.4                 py37_1003
     clang                     10.0.0          default_hde54327_1    conda-forge
     clang-tools               10.0.0          default_hde54327_1    conda-forge
     clangxx                   10.0.0          default_hde54327_1    conda-forge
     click                     7.1.2                      py_0
     cloudpickle               1.4.1                      py_0
     cmake                     3.14.0               h52cb24c_0
     cmake-setuptools          0.1.3                    pypi_0    pypi
     commonmark                0.9.1                      py_0
     conda                     4.8.3                    py37_0
     conda-package-handling    1.6.0            py37h7b6447c_0
     cryptography              2.8              py37h1ba5d50_0
     cudatoolkit               10.0.130                      0
     cudnn                     7.6.5                cuda10.0_0
     cupy                      6.0.0            py37hc0ce245_0
     cycler                    0.10.0                   py37_0
     cython                    0.29.17          py37he6710b0_0
     cytoolz                   0.10.1           py37h7b6447c_0
     dask                      2.16.0                     py_0
     dask-core                 2.16.0                     py_0
     dbus                      1.13.14              hb2f20db_0
     decorator                 4.4.2                      py_0
     defusedxml                0.6.0                      py_0
     distributed               2.16.0                   py37_0
     dlpack                    0.2                  he1b5a44_1    conda-forge
     docutils                  0.16                     py37_0
     double-conversion         3.1.5                he6710b0_1
     editdistance              0.5.3            py37h3340039_0    conda-forge
     entrypoints               0.3                      py37_0
     expat                     2.2.6                he6710b0_0
     fastavro                  0.23.3           py37h7b6447c_0
     fastcache                 1.1.0            py37h7b6447c_0
     fastrlock                 0.4              py37he6710b0_0
     ffmpeg                    4.0                  hcdf2ecd_0
     flake8                    3.7.9                    py37_0
     flatbuffers               1.11.0               he6710b0_0
     fontconfig                2.13.0               h9420a91_0
     freeglut                  3.0.0                hf484d3e_5
     freetype                  2.9.1                h8a8886c_1
     fsspec                    0.7.1                      py_0
     future                    0.18.2                   py37_0
     gflags                    2.2.2                he6710b0_0
     glib                      2.63.1               h5a9c865_0
     glog                      0.4.0                he6710b0_0
     gmp                       6.1.2                h6c8ec71_1
     gmpy2                     2.0.8            py37h10f8cd9_2
     graphite2                 1.3.13               h23475e2_0
     grpc-cpp                  1.26.0               hf8bcb03_0
     gst-plugins-base          1.14.0               hbbd80ab_1
     gstreamer                 1.14.0               hb453b48_1
     h5py                      2.8.0            py37h989c5e5_3
     harfbuzz                  1.8.8                hffaf4a1_0
     hdf5                      1.10.2               hba1933b_1
     heapdict                  1.0.1                      py_0
     hypothesis                5.11.0                     py_0
     icu                       58.2                 he6710b0_3
     identify                  1.4.15             pyh9f0ad1d_0    conda-forge
     idna                      2.8                      py37_0
     imageio                   2.8.0                      py_0
     imagesize                 1.2.0                      py_0
     importlib_metadata        1.5.0                    py37_0
     intel-openmp              2020.1                      217
     ipykernel                 5.1.4            py37h39e3cac_0
     ipython                   7.13.0           py37h5ca1d4c_0
     ipython_genutils          0.2.0                    py37_0
     isort                     4.3.21                   py37_0
     jasper                    2.0.14               h07fcdf6_1
     jedi                      0.17.0                   py37_0
     jinja2                    2.11.2                     py_0
     joblib                    0.14.1                     py_0
     jpeg                      9b                   h024ee3a_2
     json5                     0.9.4                      py_0
     jsonschema                3.2.0                    py37_0
     jupyter_client            6.1.3                      py_0
     jupyter_core              4.6.3                    py37_0
     jupyterlab                1.2.6              pyhf63ae98_0
     jupyterlab_server         1.1.1                      py_0
     kiwisolver                1.2.0            py37hfd86e86_0
     krb5                      1.17.1               h173b8e3_0
     ld_impl_linux-64          2.33.1               h53a641e_7
     libboost                  1.71.0               h97c9712_0
     libcurl                   7.69.1               h20c2e04_0
     libedit                   3.1.20181209         hc058e9b_0
     libevent                  2.1.8                h1ba5d50_0
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     libglu                    9.0.0                hf484d3e_1
     libllvm10                 10.0.0               he513fc3_1    conda-forge
     libopencv                 3.4.2                hb342d67_1
     libopus                   1.3.1                h7b6447c_0
     libpng                    1.6.37               hbc83047_0
     libprotobuf               3.11.2               hd408876_0
     libsodium                 1.0.16               h1bed415_0
     libssh2                   1.9.0                h1ba5d50_1
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                h2733197_0
     libuuid                   1.0.3                h1bed415_2
     libvpx                    1.7.0                h439df22_0
     libxcb                    1.13                 h1bed415_1
     libxml2                   2.9.9                hea5a465_1
     llvm-tools                10.0.0               he513fc3_1    conda-forge
     llvmdev                   10.0.0               he513fc3_1    conda-forge
     llvmlite                  0.32.1           py37hd408876_0
     locket                    0.2.0                    py37_1
     lz4-c                     1.8.1.2              h14c3975_0
     markupsafe                1.1.1            py37h7b6447c_0
     matplotlib                3.1.3                    py37_0
     matplotlib-base           3.1.3            py37hef1b27d_0
     mccabe                    0.6.1                    py37_1
     mistune                   0.8.4            py37h7b6447c_0
     mkl                       2020.1                      217
     mkl-service               2.3.0            py37he904b0f_0
     mkl_fft                   1.0.15           py37ha843d7b_0
     mkl_random                1.1.0            py37hd6b4f25_0
     more-itertools            8.2.0                      py_0
     mpc                       1.1.0                h10f8cd9_1
     mpfr                      4.0.1                hdf1c602_3
     mpmath                    1.1.0                    py37_0
     msgpack-python            1.0.0            py37hfd86e86_1
     mypy_extensions           0.4.3                    py37_0
     nbconvert                 5.6.1                    py37_0
     nbformat                  5.0.6                      py_0
     nbsphinx                  0.7.0              pyh9f0ad1d_0    conda-forge
     nccl                      1.3.5                cuda10.0_0
     ncurses                   6.2                  he6710b0_0
     networkx                  2.4                        py_0
     nltk                      3.4.5                    py37_0
     nodeenv                   1.3.5                      py_0    conda-forge
     notebook                  6.0.3                    py37_0
     numba                     0.49.1           py37h0573a6f_0
     numpy                     1.18.1           py37h4f9e942_0
     numpy-base                1.18.1           py37hde5b4d6_1
     numpydoc                  0.9.2                      py_0
     nvstrings-cudaunknown     0.0.0.dev0               pypi_0    pypi
     olefile                   0.46                     py37_0
     opencv                    3.4.2            py37h6fd60c2_1
     openssl                   1.1.1g               h7b6447c_0
     packaging                 20.3                       py_0
     pandas                    1.0.3            py37h0573a6f_0
     pandoc                    2.2.3.2                       0
     pandocfilters             1.4.2                    py37_1
     parso                     0.7.0                      py_0
     partd                     1.1.0                      py_0
     pathspec                  0.7.0                      py_0
     patsy                     0.5.1                    py37_0
     pcre                      8.43                 he6710b0_0
     pexpect                   4.8.0                    py37_0
     pickleshare               0.7.5                    py37_0
     pillow                    7.1.2            py37hb39fc2d_0
     pip                       20.0.2                   py37_3
     pixman                    0.38.0               h7b6447c_0
     plotly                    4.6.0                      py_0
     pluggy                    0.13.1                   py37_0
     pre-commit                2.4.0            py37hc8dfbb8_0    conda-forge
     pre_commit                2.4.0                         0    conda-forge
     prometheus_client         0.7.1                      py_0
     prompt-toolkit            3.0.4                      py_0
     prompt_toolkit            3.0.4                         0
     psutil                    5.7.0            py37h7b6447c_0
     ptyprocess                0.6.0                    py37_0
     py                        1.8.1                      py_0
     py-opencv                 3.4.2            py37hb342d67_1
     pyarrow                   0.15.1           py37h0573a6f_0
     pycodestyle               2.5.0                    py37_0
     pycosat                   0.6.3            py37h7b6447c_0
     pycparser                 2.19                     py37_0
     pyflakes                  2.1.1                    py37_0
     pygments                  2.6.1                      py_0
     pyopenssl                 19.1.0                   py37_0
     pyparsing                 2.4.7                      py_0
     pyqt                      5.9.2            py37h05f1152_2
     pyrsistent                0.16.0           py37h7b6447c_0
     pysocks                   1.7.1                    py37_0
     pytest                    5.4.1                    py37_0
     python                    3.7.6                h0371630_2
     python-dateutil           2.8.1                      py_0
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1                     py_0
     pywavelets                1.1.1            py37h7b6447c_0
     pyyaml                    5.1.2            py37h516909a_0    conda-forge
     pyzmq                     18.1.1           py37he6710b0_0
     qt                        5.9.7                h5867ecd_1
     rapidjson                 1.1.0                h6bb024c_0
     re2                       2019.08.01           he6710b0_0
     readline                  7.0                  h7b6447c_5
     recommonmark              0.6.0                      py_0
     regex                     2020.4.4         py37h7b6447c_0
     requests                  2.22.0                   py37_1
     retrying                  1.3.3                    py37_2
     rhash                     1.3.8                h1ba5d50_0
     rmm                       0.13.0                   pypi_0    pypi
     ruamel_yaml               0.15.87          py37h7b6447c_0
     scikit-image              0.16.2           py37h0573a6f_0
     scikit-learn              0.22.1           py37hd81dba3_0
     scipy                     1.4.1            py37h0b6359f_0
     seaborn                   0.10.1                     py_0
     send2trash                1.5.0                    py37_0
     setuptools                45.2.0                   py37_0
     sip                       4.19.8           py37hf484d3e_0
     six                       1.14.0                   py37_0
     snappy                    1.1.7                hbae5bb6_3
     snowballstemmer           2.0.0                      py_0
     sortedcontainers          2.1.0                    py37_0
     sphinx                    3.0.3                      py_0
     sphinx_rtd_theme          0.4.3                      py_0
     sphinxcontrib             1.0                      py37_1
     sphinxcontrib-applehelp   1.0.2                      py_0
     sphinxcontrib-devhelp     1.0.2                      py_0
     sphinxcontrib-htmlhelp    1.0.3                      py_0
     sphinxcontrib-jsmath      1.0.1                      py_0
     sphinxcontrib-qthelp      1.0.3                      py_0
     sphinxcontrib-serializinghtml 1.1.4                      py_0
     sphinxcontrib-websupport  1.2.1                      py_0
     sqlite                    3.31.1               h7b6447c_0
     statsmodels               0.11.0           py37h7b6447c_0
     streamz                   0.5.3                      py_0
     sympy                     1.5.1                    py37_0
     tbb                       2020.0               hfd86e86_0
     tblib                     1.6.0                      py_0
     terminado                 0.8.3                    py37_0
     testpath                  0.4.4                      py_0
     thrift-cpp                0.11.0               h02b749d_3
     tk                        8.6.8                hbc83047_0
     toml                      0.10.0           py37h28b3542_0
     toolz                     0.10.0                     py_0
     tornado                   6.0.4            py37h7b6447c_1
     tqdm                      4.42.1                     py_0
     traitlets                 4.3.3                    py37_0
     typed-ast                 1.4.1            py37h7b6447c_0
     typing_extensions         3.7.4.1                  py37_0
     uriparser                 0.9.3                he6710b0_1
     urllib3                   1.25.8                   py37_0
     virtualenv                16.7.5                     py_0    conda-forge
     wcwidth                   0.1.9                      py_0
     webencodings              0.5.1                    py37_1
     wheel                     0.34.2                   py37_0
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7                had09818_2
     zeromq                    4.3.1                he6710b0_3
     zict                      2.0.0                      py_0
     zipp                      3.1.0                      py_0
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.3.7                h0b5b093_0
     
</pre></details>
Singularity test:/opt/rapids-0.13.0/cudf-0.13.0>

**Additional context**

Base Singularity container definition file: https://github.com/mkandes/ubuntu-cuda-openmpi

**Comment by harrism** [comment]
Hi @mkandes it would help to know how many threads you are using to build, and where in the build you see the memory usage spike.  I routinely build libcudf with 14 threads on my Ubuntu 18.04 desktop and memory usage stays < 10GB. But if you build with many more threads than this of course memory usage can be much higher.

What evidence have you seen that there is a memory leak rather than just a lot of parallelism in your build?

**Comment by philtrade** [comment]
I have run into similar situation twice when I set the `PARALLEL_LEVEL=8` (8 core cpu, ubuntu 18.04).  It is spurious though, not doesn't happen on every run.

It would run fine with up to 8 threads for a while.  Then at some point suddenly massive number of compilation threads were spawned.  The load on my machine shot up to 80+, eventually compilations start to fail with out of memory.   It is as if "suddenly the build process decided there is no dependency among all obj targets", or the parallelism allowed is unbounded. 

Happened to me once a week ago, since then I tuned it down to 4 and it was fine.

But it happened again today, when I tried to rebuild the repo (a few hundred commits behind the HEAD) with the same level of 8.   Too bad I didn't capture the output as to the exact point it happened (will try in the future).

**Comment by mkandes** [comment]
@harrism: That's a good point. I was originally building on my laptop using only a single-core. I did not increase the number of threads when I then attempted to build on a larger VM. I'll give that a shot and see if that reduces the problem. It's just the first time I've run into this kind of issue with a piece of software. Memory leak was probably not the right term to use here.

**Comment by kkraus14** [comment]
Closing as this was answered.
