### ISSUE TITLE
[FEA] Support custom IO data sources in cuIO readers

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5200]
Add support for user implemented data sources, similar to the data sink support added in https://github.com/rapidsai/cudf/pull/4231

**Comment by felipeblazing** [comment]
Is there any chance we can start using arrow apis for this are are we still rolling our own source / sink interface? https://arrow.apache.org/docs/cpp/io.html

**Comment by vuule** [comment]
> Is there any chance we can start using arrow apis for this are are we still rolling our own source / sink interface? https://arrow.apache.org/docs/cpp/io.html

I would like this too, but IMO it comes at a cost.
The main hurdle I see is that we need the data source to provide ways to read into CPU or GPU memory (as in some cases we can read directly into GPU memory). One way is to have an API that includes both read/write types (current sink), or we pass two separate sources/sinks to readers that make use of the direct reads/writes. 

Also, Arrow API is not sufficient for some types of sources (e.g. read/allocation alignment requirements).

Let me know what you think. 

FWIW, we (will) have a simple way for users to declare adapters for Arrow sources/sinks and use them that way.
