### ISSUE TITLE
[QST] Python 3.8 support

### ISSUE THREAD

**Issue by xmnlab** [rapidsai/cudf#5201]
**What is your question?**
I just want to check if there is any plan/estimate date for python 3.8 support?

thanks!

**Comment by weiji14** [comment]
Just noting that Python 3.8 *should* be supported in v0.15 according to https://docs.rapids.ai/notices/rsn0003/, and that Python 3.8 nightly builds are already available at https://anaconda.org/rapidsai-nightly/cudf/files.

**Comment by kkraus14** [comment]
Yup this is a solved problem, closing. Thanks!

**Comment by xmnlab** [comment]
awesome. thanks!
