### ISSUE TITLE
[DOC] Gaps in `cudf` Python Documentation

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5210]
## Report incorrect documentation
There are some gaps in `cudf` python documentation. I made a list of all such issues below..

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/nightly/

**Describe the problems or issues found in the documentation**

**DataFrame**
Method | Issue
-- | --
add | documentation missing
argsort | documentation missing
deserialize | needs to be hidden
equals | documentation missing
floordiv | documentation missing
groupby | documentation missing
memory_usage | documentation missing
mod | documentation missing
mul | documentation missing
pow | documentation missing
radd | documentation missing
reset_index | documentation missing
rfloordiv | documentation missing
rmod | documentation missing
rmul | documentation missing
rpow | documentation missing
rsub | documentation missing
rtruediv | documentation missing
serialize | documentation missing
sub | documentation missing
truediv | documentation missing

**Series**
Method | Issue
-- | --
logical_not | needs to hidden
logical_or | needs to hidden
memory_usage | documentation missing
merge | improvise docs
remainder | needs to hidden
serialize | needs to hidden
sum_of_squares | needs to hidden
to_arrow | documentation missing
to_pandas | documentation missing
unique_k | Deprecated 3 years ago, Remove the method.

Attributes |  Issue
-- | --
cat | documentation missing
dt | documentation missing
empty | documentation missing
has_nulls | documentation missing
is_monotonic | documentation missing
is_monotonic_decreasing | documentation missing
is_monotonic_increasing | documentation missing
is_unique | documentation missing
str | documentation missing
values | documentation missing
values_host | documentation missing

**Strings**

`StringMethods` will need more class doc to it as well.

Method | Issue
-- | --
ngrams | documentation missing
ngrams_tokenize | documentation missing
normalize_spaces | documentation missing
token_count | documentation missing
tokenize | documentation missing
cat | need examples
center | need examples
code_points | need examples
contains | need examples
count | need examples
endswith | need examples
extract | need examples
find | need examples
findall | need examples
get | need examples
htoi | need examples
index | need examples
insert | need examples
ip2int | need examples
isalnum | need examples
isalpha | need examples
isdecimal | need examples
isdigit | need examples
isempty | need examples
islower | need examples
isnumeric | need examples
isspace | need examples
isupper | need examples
join | need examples
len | need examples
ljust | need examples
lower | need examples
lstrip | need examples
match | need examples
pad | need examples
partition | need examples
replace | need examples
replace_with_backrefs | need examples
rfind | need examples
rindex | need examples
rjust | need examples
rpartition | need examples
rsplit | need examples
rstrip | need examples
slice | need examples
slice_from | need examples
slice_replace | need examples
split | need examples
startswith | need examples
strip | need examples
swapcase | need examples
title | need examples
translate | need examples
upper | need examples
url_decode | need examples
url_encode | need examples
wrap | need examples
zfill | need examples

**IO**

Method | Issue
-- | --
to_parquet | need examples
to_orc | need examples
read_json | need examples
to_json | need examples
read_hdf | need examples
to_hdf | need examples

**Documentation is missing for:**
`StringAccessor`
`CategoricalAccessor`
`Index` (All types)
`MultiIndex`

**Steps taken to verify documentation is incorrect**
Check against API behavior and pandas.

**Suggested fix for documentation**
Fix according to API behavior.

**Comment by galipremsagar** [comment]
There are also issues in the formatting of docs in some of the methods. Sample issues in snaps below:

<img width="639" alt="Screen Shot 2020-05-15 at 7 55 09 PM" src="https://user-images.githubusercontent.com/11664259/82107493-d4cf6a80-96ed-11ea-8013-70906e521d75.png">
<img width="920" alt="Screen Shot 2020-05-15 at 7 55 29 PM" src="https://user-images.githubusercontent.com/11664259/82107494-d6009780-96ed-11ea-99c7-7361ca19d44e.png">
<img width="643" alt="Screen Shot 2020-05-15 at 7 55 51 PM" src="https://user-images.githubusercontent.com/11664259/82107495-d6992e00-96ed-11ea-8ea5-42fcbec86f95.png">
<img width="771" alt="Screen Shot 2020-05-15 at 7 57 39 PM" src="https://user-images.githubusercontent.com/11664259/82107496-d6992e00-96ed-11ea-8d77-08a20393420d.png">

**Comment by kkraus14** [comment]
@galipremsagar I think also Index / MultiIndex classes aren't documented as well as CategoricalMethods.

**Comment by galipremsagar** [comment]
> @galipremsagar I think also Index / MultiIndex classes aren't documented as well as CategoricalMethods.

Ah right, will add them to this list.
