### ISSUE TITLE
[BUG] Reduce the use of macros in cuIO

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5211]
Some of the macros can be replaced with constructs that provide type safety without performance loss.

May be blocked on having cuIO benchmarks to be able to verify that there are no perf regressions.

Examples:
https://github.com/rapidsai/cudf/blob/855648c8495163311623883d0c1248f6a87ba53b/cpp/src/io/comp/unsnap.cu#L260
and
https://github.com/rapidsai/cudf/blob/855648c8495163311623883d0c1248f6a87ba53b/cpp/src/io/csv/csv_gpu.cu#L700
could be inline fuctions.

https://github.com/rapidsai/cudf/blob/855648c8495163311623883d0c1248f6a87ba53b/cpp/src/io/parquet/parquet.h#L31
and
https://github.com/rapidsai/cudf/blob/855648c8495163311623883d0c1248f6a87ba53b/cpp/src/io/orc/dict_enc.cu#L30
Could be constexpr variables.

**Comment by harrism** [comment]
Can you add some pointers to examples that should be replaced in this issue?

**Comment by cwharris** [comment]
#6206 was unfortunately reverted after being accused of breaking the build. Attempts were made to fix in place, but did not prove fruitful. :(

**Comment by vuule** [comment]
Closing, the closing PR #6782 had a typo in the issue #.
