### ISSUE TITLE
[FEA] SeriesGroupBy diff() and cumsum()

### ISSUE THREAD

**Issue by MuhammadZeeshan34** [rapidsai/cudf#5215]
**Describe the bug**
AttributeError: 'SeriesGroupBy' object has no attribute 'diff'

**Steps/Code to reproduce bug**
df = pd.DataFrame({'a': [0, 1, 2, 3],'b': [0.1, 0.2, None, 0.3]})
df = cudf.from_pandas(df)
df.groupby('a')['b'].diff()
df.groupby('a')['b'].cumsum

Is there any alternative to perform these two operations 'diff' and 'cumsum' using cudf?

**Comment by harrism** [comment]
Duplicates #1298 (cumsum) and #5079 (diff).

CC @kkraus14 for whether there is a workaround.

**Comment by beckernick** [comment]
Closing, as this issue is covered by the issues linked by @harrism above. Let's take further discussion of `groupby.diff` to #5079
