### ISSUE TITLE
[FEA] Ignore case when using regex in replace

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#5217]
**Is your feature request related to a problem? Please describe.**
I need to replace a string not matter the case

In pandas I can search for 'a' to match 'A' and replace it for  'C' using `(?i)`

```
import pandas as pd
s = pd.Series(['A','B'])
print(s.str.replace(r'(?i)a', 'C'))

0    C
1    B
dtype: object

```
```
import cudf
s = cudf.Series(['A','B'])
print(s.str.replace(r'(?i)a', 'C'))
0    A
1    B
dtype: object

```

I would like cudf could accept `(?i)`

**Describe the solution you'd like**
Using `(?i)` should match lower and upper case strings

**Describe alternatives you've considered**
For chars, it makes sense to use 'a' and 'A' in the regex, but not for strings because a combination of all lower and upper cases must be created.

**Comment by davidwendt** [comment]
Supporting case-sensitivity dynamically inside the regex pattern will probably not be supported. However, it does look it would be possible to add support for a regex flag like https://docs.python.org/3/library/re.html#re.IGNORECASE where the entire pattern is evaluated as case-sensitive (or not).

**Comment by vyasr** [comment]
The flag for completely case-sensitive or insensitive matches now exists in libcudf. The remaining ask is to add support for these flags at the Python layer.

**Comment by davidwendt** [comment]
> The flag for completely case-sensitive or insensitive matches now exists in libcudf. The remaining ask is to add support for these flags at the Python layer.

There is no plan to support this libcudf
https://github.com/rapidsai/cudf/blob/ce1933fc07d5f8d1da3ad36217ea0b39d7a926fa/cpp/include/cudf/strings/regex/flags.hpp#L35-L40

**Comment by vyasr** [comment]
Silly me. I saw #10208 and didn't check what flags were actually added. So do you think we should close this issue as wontfix @davidwendt?

**Comment by davidwendt** [comment]
> Silly me. I saw #10208 and didn't check what flags were actually added. So do you think we should close this issue as wontfix @davidwendt?

Yes,
