### ISSUE TITLE
Use Black for automatic code styling in Python

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#522]
There seem to be some ongoing conversations about linting and code style.  

I'd like to submit [Black](https://black.readthedocs.io/en/stable/) for consideration.  It is commonly used to automatically format code.  This removes most conversation about code style, which is pleasant.

Here is a [lightning talk](https://youtu.be/bTAFl8P2DkE?t=301) about the project.

**Comment by shwina** [comment]
Very cool project! Is there a way to support Cython with Black?

**Comment by ericmjl** [comment]
To the best of my knowledge, @ambv wants help with this: https://github.com/ambv/black/issues/359

**Comment by kkraus14** [comment]
Closed by #2160
