### ISSUE TITLE
[BUG] split function in dask cudf raise `expand` parameter is not supported 

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#5223]
**Describe the bug**

split function in  dask_cudf `df["A"].str.split("/").compute()` raise 
```
NotImplementedError: `expand` parameter is not supported 
```

**Steps/Code to reproduce bug**
In dask is possible to split a series using:

```
from dask import dataframe as dd
import pandas as pd
df = dd.from_pandas(pd.DataFrame({"A":["1,2","3,4"]}), npartitions=1)
df["A"].str.split("/").compute()

0    [1,2]
1    [3,4]
Name: A, dtype: object
```
But in dask_cudf:

```
from dask import dataframe as dd
import cudf
import dask_cudf
df = dask_cudf.from_cudf(cudf.DataFrame({"A":["1,2","3,4"]}), npartitions=1)
df["A"].str.split("/").compute()

~/.conda/envs/dask_cudf_013/lib/python3.7/site-packages/cudf/core/column/string.py in split(self, pat, n, expand, **kwargs)
    850         """
    851         if expand is not True:
--> 852             raise NotImplementedError("`expand` parameter is not supported")
    853 
    854         # Pandas treats 0 as all

NotImplementedError: `expand` parameter is not supported

```
**Expected behavior**
Same Dask behavior.Split the string into n items using a string a separator

**Environment overview (please complete the following information)**
 - Environment location: GCP
 - Method of cuDF install: conda

**Comment by rgsl888prabhu** [comment]
Currently we don't support expand, you can try something like 
```
df["A"].str.split(",", expand=True, n=1).compute()
```

**Comment by galipremsagar** [comment]
> Currently we don't support expand

What @rgsl888prabhu is correct.

For more context: https://github.com/rapidsai/cudf/issues/5127#issuecomment-627075209

**Comment by beckernick** [comment]
In the time between when this was file and today, we've implemented support for ListColumns and `expand`. 

```python
from dask import dataframe as dd
import cudf
import dask_cudf
df = dask_cudf.from_cudf(cudf.DataFrame({"A":["1,2","3,4"]}), npartitions=1)
df["A"].str.split("/").compute()
0    [1,2]
1    [3,4]
Name: A, dtype: list
```

When using `expand=True` with Dask (CPU or GPU), you'll need to pre-specify the number of output columns with the `n=...` parameter. Please feel free to re-open this issue if you run into any issues!
