### ISSUE TITLE
[BUG] RunTimeError in extract function for a valid regex

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5229]
**Describe the bug**
`extract` API seems to error on a valid regex.

**Steps/Code to reproduce bug**

```python
>>> import cudf
>>> s = cudf.Series(['a1', 'b2', 'c3'])
>>> s.str.extract(r'(?P<letter>[ab])(?P<digit>\d)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/cudf/lib/python3.7/site-packages/cudf/core/column/string.py", line 452, in extract
    out = cpp_extract(self._column, pat)
  File "cudf/_lib/strings/extract.pyx", line 32, in cudf._lib.strings.extract.extract
RuntimeError: cuDF failure at: /cudf/cpp/src/strings/regex/regcomp.cpp:398: invalid regex pattern: nothing to repeat at position 1
>>> s.to_pandas().str.extract(r'(?P<letter>[ab])(?P<digit>\d)')
  letter digit
0      a     1
1      b     2
2    NaN   NaN


# The above reg-ex seems to be a valid one.
>>> import re
>>> re.compile(r'(?P<letter>[ab])(?P<digit>\d)')
re.compile('(?P<letter>[ab])(?P<digit>\\d)')

```

**Expected behavior**
I think we shouldn't be erroring in case of this regex, a followup to this is maybe we'll need an API to extract the column names from regex like in this case.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install:  from source[`branch-0.14`]

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.extract.html

**Comment by davidwendt** [comment]
Not sure why 2 separate issues are opened in one issue.

For the first issue, the `(?P)` pattern is not supported. Supported regex features are documented here: https://docs.rapids.ai/api/libcudf/nightly/md_regex.html

**Comment by galipremsagar** [comment]
Thanks for the documentations David, closing this issue as I separated the 2nd Issue : https://github.com/rapidsai/cudf/issues/5234
