### ISSUE TITLE
GPU accelerate MICE imputation

### ISSUE THREAD

**Issue by raghavmi** [rapidsai/cudf#523]
## Feature request

MICE imputation is a powerful, but compute intensive imputation strategy.

MICE:
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3074241/
https://www.youtube.com/watch?v=zX-pacwVyvU

It has been shown to work well with EHR data that's typically quite sparse:
https://arxiv.org/abs/1801.00065

A GPU accelerated MICE imputer would be a great addition to RAPIDS.

**Comment by kaish114** [comment]
Is **MICE imputation** _implementation_ has been done in **cuDF**?

**Comment by kkraus14** [comment]
@kaish114 No, this is out of scope for cuDF but we welcome for someone to build it on top of cuDF in another library that's more domain specific.

**Comment by kaish114** [comment]
Great!! Thank you so much for your response.
