### ISSUE TITLE
[BUG] extract API returns empty string returned instead of None in a specific example

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5234]
**Describe the bug**
`extract` API seems to return an empty string in a specific case where it has to return `None`.

**Steps/Code to reproduce bug**
```python
>>> s = cudf.Series(['a1', 'b2', 'c3'])
>>> s.str.extract(r'([ab])(\d)')
      0     1
0     a     1
1     b     2
2  None  None


>>> s.str.extract(r'([ab])?(\d)')
   0  1
0  a  1
1  b  2
2     3
>>> s.str.extract(r'([ab])?(\d)')[0][2]
''


>>> s.to_pandas().str.extract(r'([ab])?(\d)')
     0  1
0    a  1
1    b  2
2  NaN  3
>>> 

```

**Expected behavior**
The expected behavior is to return `None` instead of an empty string `''`.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install:  from source[`branch-0.14`]

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.extract.html

**Comment by davidwendt** [comment]
Adding reference to similar issue #5157 
The problem is the placement of the `?` after the group `(...)`

```
>>> import pandas as pd
>>> ps = pd.Series(['a1', 'b2', 'c3'])
>>> ps.str.extract(r'([ab])(\d)')
     0    1
0    a    1
1    b    2
2  NaN  NaN
>>> ps.str.extract(r'([ab])?(\d)')
     0  1
0    a  1
1    b  2
2  NaN  3
>>> ps.str.extract(r'([ab]?)(\d)')
   0  1
0  a  1
1  b  2
2     3
```

The greedy quantifier `?` is not supported for capturing group `(...)` in the cudf regex implementation. That is, I don't see how the internal code can return this information.

**Comment by galipremsagar** [comment]
Thanks, @davidwendt ! Closing this issue.
