### ISSUE TITLE
[FEA] Configure Arrow build to include shared libraries, compute, and python support so devices not using conda (Xavier) can build and link cuDF

### ISSUE THREAD

**Issue by jdye64** [rapidsai/cudf#5237]
Currently if trying to build cuDF from source on a Xavier (or any Jetpack 4.4 based device) the build will fail. This is ultimately due to a supported version of conda not being available for aarch64. We need to ensure that when cuDF builds the Arrow library that support for certain components is built since we can rely on those libraries to be available (in conda) on certain devices.

**Comment by GregoryKimball** [comment]
Closing this until we revisit building cuDF on Jetson.
