### ISSUE TITLE
[DISCUSSION] Split out strings-specific APIs into separate shared-object from libcudf.so

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#5244]
As more features are added to cuDF, the `libcudf.so` size and compile time is becoming difficult to manage. It is concerning that we are not able to build `libcudf.so` with debug because of its size. Removing the legacy code should help here but adding new types and new features will quickly take up the space (and time). Initial numbers for removing legacy show the decrease in size is only 25% and compile time improvement only 16%. Also, I did some investigative work to add just 4 unsigned-types to libcudf and found the compile time increased by 20% and the size of `libcudf.so` increased by 13%. This almost cancels out the legacy removal improvement.

Reference also issue #4718 here for just runtime size.

I propose splitting up `libcudf.so` into multiple .so units. There are over 50 strings-specific APIs some of which include some of the largest objects and compile times -- mainly those APIs that use regex. If the strings-specific functions are placed in a separate .so then both libcudf.so and this new .so will have a better chance at building with debug. 

The native string support for libcudf would remain inside `libcudf.so` including those functions used by other libcudf components (e.g. the converters used by the CSV writer). The new .so file would be dependent on `libcudf.so` for the native strings classes and other APIs like gather.

Here is a list of the strings APIs that can be moved:

- count_characters
- count_bytes
- code_points
- capitalize
- title
- to_lower
- to_upper
- swapcase
- all_characters_of_type
- is_integer
- is_float
- join_strings
- contains_re *
- matches_re *
- count_re *
- ipv4_to_integers
- integers_to_ipv4
- url_encode
- url_decode
- extract *
- find
- rfind
- contains
- starts_with
- ends_with
- find_multiple
- findall_re *
- pad
- zfill
- replace
- replace_slice
- replace_nulls
- replace_re *
- replace_with_backrefs *
- partition
- rpartition
- split
- rsplit
- contiguous_split_record
- contiguous_rsplit_record
- strip
- slice_strings
- translate
- wrap

(The * items use regex which are large in compile time and object size)
None of the above APIs are called by internal libcudf functions.

Based on the current size of `libNVStrings.so` I estimate this would reduce the size of `libcudf.so` by 10-15%.

Likewise, I propose also splitting out the [nvtext APIs](https://docs.rapids.ai/api/libcudf/nightly/namespacenvtext.html) into a separater .so since libcudf also does not depend on these APIs for any internal functions.

I believe the main work here would involve the build: CMake files and conda packaging. Also, I suspect this would impact Cython code that used any of the above APIs to import/bind to the new .so file. I don't see any reason to move source files or change the repo directory structure for this.

**Comment by harrism** [comment]
I think this is a good suggestion.  If needed we could modularize other parts of libcudf.

**Comment by davidwendt** [comment]
This has been addressed in #6134
