### ISSUE TITLE
[BUG] Incorrect value for IP address in ip2int

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5252]
**Describe the bug**
`ip2int` seems to be overflowing after a certain IP values, whereas `nvstrings.ip2int` seems to be returning correct values.

**Steps/Code to reproduce bug**
```python
>>> s = cudf.Series(["192.168.0.1", "10.0.0.1"])
>>> s.str.ip2int()
0   -1062731775
1     167772161
dtype: int64
>>> s = cudf.Series(["192.168.0.2", "10.0.0.1"])
>>> s.str.ip2int()
0   -1062731774
1     167772161
dtype: int64
>>> import nvstrings
>>> print(nvstrings.to_device(["192.168.0.1", "10.0.0.1"]).ip2int())
[3232235521, 167772161]
```

**Expected behavior**
The correct integer value of `"192.168.0.1"` is `3232235521` as obtained in `nvstrings` api.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install:  from source, `branch-0.14`

**Comment by davidwendt** [comment]
Closing this as it is fixed in 0.15
