### ISSUE TITLE
[QST] ’ImportError: cannot import name runtime ‘

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#5255]
**What is your question?**
I successfuly build the cudf-0.12 of CPP module before, and ouput the libcudf.so librmm.so libnvstring.so etc ，and my environment is below : 
 CentOS 7.4
kernel 3.10.0-693.el7.x86_64
gpu P4
cuda 10.2 
GCC -6.2
python 3.6.8
but when I build then python package ，it occurs an error : 
![image](https://user-images.githubusercontent.com/33319780/82634669-f0c49600-9c30-11ea-92ad-ed6b446162c7.png)
by the way , befor I install python setup.py , I successfuly install some dependency by pip3 , its information is : 
![image](https://user-images.githubusercontent.com/33319780/82634759-33866e00-9c31-11ea-867c-8017bb4b38d4.png)

how to solve it ?

**Comment by kkraus14** [comment]
What CUDA version do you have installed on your machine? How did you install cupy?

**Comment by kkraus14** [comment]
This is stale and unanswered so closing.
