### ISSUE TITLE
[BUG]cuDF very slow when iterating with .loc

### ISSUE THREAD

**Issue by tranducquy** [rapidsai/cudf#5257]
**Describe the bug**
cuDF very slow when iterating with .loc

**Steps/Code to reproduce bug**

```
 %%timeit
 a = np.random.rand(2000)
 cdf = cudf.DataFrame()
 cdf['a'] = a
 for i in cdf.index:
     e = cdf.loc[i]
```

**Expected behavior**
Compared with performance of Pandas DataFrame, cdf.loc[i] is very slow. This should not be 10 times slower than Pandas?

**Environment overview**
 - Environment location: [Docker RAPIDS]
 - Method of cuDF install: [Docker]
   - Commands used
     docker pull rapidsai/rapidsai:cuda10.1-runtime-ubuntu18.04

**Environment details**
Ubuntu18.04

**Comment by brandon-b-miller** [comment]
Hi @tranducquy, cuDF works best when used to perform the same operation on many data elements at once as opposed to looping through each row individually and operating on it as you go. Are you able to provide some more detail on what you're trying to do? Depending on how you're using the rows, you could be incurring a lot of unnecessary overhead. It might be possible to accomplish your goal without needing to iterate at all, in which case I suspect you might see better performance.

**Comment by kkraus14** [comment]
In addition to what @brandon-b-miller said, I would also add that iterating over Pandas objects also leads to huge slowdowns, where avoiding these iterations will greatly speed up your Pandas code as well.

**Comment by kkraus14** [comment]
Closing as question was answered.
