### ISSUE TITLE
Fail loudly in default cases of switch statements on gdf_dtype

### ISSUE THREAD

**Issue by muellren** [rapidsai/cudf#527]
## Feature request

Missing case clauses on `gdf_dtype` or the `default` case should fail loudly if the functionality is not yet available. The currently used `assert(false)` results in a undefined behavior in `Release` builds. 

Argument checks for currently unsupported data types and modes are missing in the Python layer and loud failures would help with the triage of bugs. 

Occurrences:
- [type_dispatcher.hpp: line 110](/rapidsai/cudf/blob/branch-0.5/cpp/src/utilities/type_dispatcher.hpp#L110)
- [sqls_rtti_comp.h: line 271](/rapidsai/cudf/blob/branch-0.5/cpp/src/sqls/sqls_rtti_comp.h#L271)
- [quantiles.cu: line 201](/rapidsai/cudf/blob/branch-0.5/cpp/src/quantiles/quantiles.cu#L201)

**Comment by jrhemstad** [comment]
Note that in the long term, all `switch` cases in libcudf will be replaced by `cudf::type_dispatcher`. Therefore, focusing on the desired behavior for its default case is appropriate.

**Comment by jrhemstad** [comment]
Thanks to @eyalroz who found what is being called by an `assert` in device code:

```
#define __ASSERT_STR_HELPER(x) #x
#define assert(e) ((e) ? static_cast<void>(0)\
                       : __assertfail(__ASSERT_STR_HELPER(e), __FILE__,\
                                      __LINE__, __PRETTY_FUNCTION__,\
                                      sizeof(char)))
```

We could simply call this directly instead of `assert`, which would ensure that we fail loudly in Release builds.

**Comment by eyalroz** [comment]
We would only use this part:
```
__assertfail(__ASSERT_STR_HELPER("Message"), __FILE__,  __LINE__, __PRETTY_FUNCTION__, sizeof(char)))
```
which can be defined to be another macro (.e.g `fail_like_in_assert()`...)
