### ISSUE TITLE
[FEA] Add pretty print to cudf.Series

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#5275]
**Is your feature request related to a problem? Please describe.**
Hi!

`cudf.DataFrame` object has a nice pretty-print in Jupyter notebooks, while `cudf.Series` object haven't got the same.

**Describe the solution you'd like**
To have pretty-print support in `cudf.Series` objects.

<img width="433" alt="Screenshot 2020-05-25 at 18 02 22" src="https://user-images.githubusercontent.com/26169771/82828800-29bf6d80-9eb2-11ea-9ead-7e76b5122a4a.png">

**Comment by miguelusque** [comment]
Hi @kkraus14 ,

You are right. `pandas.Series` doesn't have pretty printing either.

Nevertheless, I think it might be nice to have it in cuDF, regardless Pandas behaviour.

Many people is using Jupyter notebooks to produce content, i.e. https://jupyterbook.org/, and it would be great if we might format `cudf.Series` in a similar way we do with `cudf.DataFrame`.

I am looking forward for your thoughts on the above.

In the meanwhile, have a great weekend!

**Comment by kkraus14** [comment]
In general the Pandas community still seems to be figuring out how they want to do this so I think it makes sense for us to wait based on their behavior.

**Comment by kkraus14** [comment]
Closing as we're just going to continue following Pandas in this respect and once they had pretty printing to pandas Series we'll immediately get it as well.

**Comment by miguelusque** [comment]
Hi @kkraus14 ,

Pandas allows to style dataframes and series, via https://pandas.pydata.org/pandas-docs/stable/user_guide/style.html .

I assume it might be more expensive to implement those styling capabilities than just pretty printing series.

Could you please reconsider this issue?

Thanks!

**Comment by kkraus14** [comment]
@miguelusque we will follow Pandas in this regard. If/When they implement pretty printing we'll support it as well.

Someone could have code (they shouldnt...) that parses the output of `__repr__` (what the print formatting is) and diverging from Pandas could break that parsing code.
