### ISSUE TITLE
[FEA] Enable parquet metadata collection for chunked parquet writer

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#5284]
**Is your feature request related to a problem? Please describe.**
After [#4450](https://github.com/rapidsai/cudf/pull/4450), it is now possible to collect the raw parquet metadata (with a custom `file_path` field) during each call to `to_parquet`.

Now that [#4870](https://github.com/rapidsai/cudf/pull/4870) exposed a python interface to `write_parquet_chunked` funcrtionality, it would be great to be able to collect the parquet metadata (with a custom `file_path` field) upon closing the ParquetWriter object.  This feature would be useful for writing a global `"_metadata"` file within a multi-GPU (Dask-based) workflow where a single process may need to keep a parquet file open for multiple writes (planned for future multi-GPU functionality in [NVTabular](https://github.com/NVIDIA/NVTabular)).

**Describe the solution you'd like**
I'd like to be able to pass a `metadata_out_file_path` argument to `write_table` when using `cudf.io.parquet.ParquetWriter`.  I'd also like to be able to collect the raw metadata directly from the `write_table` call, or when calling `ParquetWriter.close()`.

**Describe alternatives you've considered**
The only alternatives are to avoid the `write_parquet_chunked` functionality when metadata needs to be collected, or to read back the dataset and write a global metadata file "after-the-fact" with pyarrow.

**Additional context**
Note that I am happy to dig in here myself.  However, I am rasing the issue: (1) in case others feel this would be a trivial change for them to make, (2) to get general feedback before attempting any changes...  cc @benfred @OlivierNV

**Comment by OlivierNV** [comment]
On the CPP side, it seems like a relatively simple addition to the chunked writer, though I'd suggest making a separate `get_metadata` call that would return the metadata from the chunked state for getting the intermediate version (before `write_chunked_end`), so that the overhead of encoding the metadata isn't there unless necessary.
