### ISSUE TITLE
[BUG] cudf.DataFrame.drop_duplicates() alters original row order, pandas doesn't.

### ISSUE THREAD

**Issue by philtrade** [rapidsai/cudf#5286]
**Description**
`cudf.DataFrame.drop_duplicates()` alters original row order because it sorts on the resulting unique values.  Pandas doesn't do that.  Behavior extends to `Series.unique()` as well.

Problematic usage case: large time series with an index sorted by time, with columns to clean.  Callers get back a frame of rows not following original index's order.

```
import pandas as pd, cudf as gd, numpy as np

data={'status': [ 'good', 'bad', 'ugly', 'stuff', 'stuff', 'stuff' ], 'seq': [1,2,3,4,5,6]}
p = pd.DataFrame(data).set_index('seq')
g = gd.DataFrame(data).set_index('seq')

print(p.drop_duplicates('status'))
print(g.drop_duplicates('status'))
```
output:
```
    status
seq       
1     good
2      bad
3     ugly
4    stuff

    status
seq       
2      bad
1     good
4    stuff
3     ugly

```

**Expected behavior**
Original row orders not perturbed.  The 2nd frame output should look like the first:

```
    status
seq       
1     good
2      bad
3     ugly
4    stuff
```

**Environment overview (please complete the following information)**
ipython, cudf branch-0.14, pandas 0.25

**Additional context**
 Callers of `DataFrame.drop_duplicates()` are in for a surprise: pay for the cost of unwanted sort and need to resort it again afterwards to restore the original order.  This surprise/extra demand on users is an obstacle to adoption of `cudf` over `pandas` for large dataset.

The point was discussed several times before: In [#1781](https://github.com/rapidsai/cudf/issues/1781)... and [issue 4997](https://github.com/rapidsai/cudf/issues/4997), re: "Don't sort unless users ask for it.". 

p.s. this issue originates from [the slack thread here.](https://rapids-goai.slack.com/archives/C5E06F4DC/p1590463821261600)

**Comment by harrism** [comment]
> Don't sort unless users ask for it.

I don't know how pandas does it, but the common approach to efficiently find duplicates with massive parallelism is to sort.

Internal note: 
We could investigate sorting the original positions of the values instead, and then use indirection to create a boolean mask for copy_if on the original input.

**Comment by karthikeyann** [comment]
@kkraus14 decision was taken not to give any guarantee on drop_duplicates order. It is possible to return in same order. 
Is this a requirement?

**Comment by philtrade** [comment]
> I don't know how pandas does it, but the common approach to efficiently find duplicates with massive parallelism is to sort.
 
Pandas uses hash.   If sorting achieves parallelism that's not available to pandas, it may well be a reasonable intermediate step.

> Internal note:
> We could investigate sorting the original positions of the values instead, and then use indirection to create a boolean mask for copy_if on the original input.

👍

**Comment by philtrade** [comment]
> ..... It is possible to return in same order.

👍

> decision was taken not to give any guarantee on drop_duplicates order ([#1845 (comment)](https://github.com/rapidsai/cudf/pull/1845#discussion_r294103129))....... Is this a requirement?

Perturbing the original order is quite an unexpected intervention to callers who provide an ordered series but "is guaranteed that may receive a scrambled set in return."   Is "not guaranteeing original order" helpful to users, when compared to a non-invasive-by-default procedure?  😅

**Comment by rgsl888prabhu** [comment]
> > Don't sort unless users ask for it.
> 
> I don't know how pandas does it, but the common approach to efficiently find duplicates with massive parallelism is to sort.
> 
> Internal note:
> We could investigate sorting the original positions of the values instead, and then use indirection to create a boolean mask for copy_if on the original input.
> 
> Or we could investigate the feasibility of a hash-based solution.

Currently we are using thrust::copy_if which is stable to get gather mask and gathering the required rows, so not sure why the order is getting scrambled.

**Comment by devavret** [comment]
> Or we could investigate the feasibility of a hash-based solution.

This came up earlier but for performance reasons. I think there’s a way to use hashing to keep first/last and maintain order. This would be an argmin with values as keys.

**Comment by jrhemstad** [comment]
> Perturbing the original order is quite an unexpected intervention to callers who provide an ordered series

It's only unexpected if your frame of reference is coming from a purely sequential computing library like Pandas. 

Sorting to get the unique elements is a _very_ common implementation, even in sequential implementations. For instance, [`std::unique`](https://en.cppreference.com/w/cpp/algorithm/unique) only drops duplicate elements in consecutive ranges of duplicate elements. This makes the sort the users responsibility.

**Comment by jrhemstad** [comment]
> I’d recommend to try the hash approach first.

Not only would a hash implementation preserve the original input order, but I'm pretty sure it would be quite a bit faster as well. As we've seen, the multi-column sorts are really expensive. Seems like the drop_duplicates could be pretty easily implemented as a groupby argmin/argmax for keep first/last, and as a groupby count for keep `false` where you keep only the values with `count == 1`.

**Comment by rgsl888prabhu** [comment]
> > I’d recommend to try the hash approach first.
> 
> Not only would a hash implementation preserve the original input order, but I'm pretty sure it would be quite a bit faster as well. As we've seen, the multi-column sorts are really expensive. Seems like the drop_duplicates could be pretty easily implemented as a groupby argmin/argmax for keep first/last, and as a groupby count for keep `false` where you keep only the values with `count == 1`.

But I don't think groupyby would preserve the order.

**Comment by jrhemstad** [comment]
> But I don't think groupyby would preserve the order.

Yeah, you'd need to do some extra sorting work if you really care about preserving the original order.

If we don't care about preserving original order (and I don't think we should care), then certainly the unordered groupby implementation will be faster than the current implementation that requires sorting the input.

**Comment by philtrade** [comment]
First, thanks for sharing your thoughts @jrhemstad !

> This makes the sort the users responsibility.

Depends on the goal.  Tooling a fastest machinery is often an attractive and exciting exercise for engineers.  If the goal is for wider and faster adoption of `cudf` though, usability may be an equally important issue.

User would be reluctant to adopt if `cudf` doesn't work or requires lot of work-arounds.  One more gotcha, one more reason/excuse to defer the adoption.  I have seen that on both slack and fastai forum.

Will `std:unique` be designed the same way, if the usage is mainly to deal with indexed data, like `drop_duplicates()` has to with a DataFrame?

"How quickly a new tool is adopted by the user community" is another kind of performance metric.   On that count, `pandas` had done outstandingly (for whatever reasons), without which, will `cudf` be conceived by now?  --- What *is* `cudf`'s frame of reference?  `c++'s std library`, or a practical and popular DataFrame library?

Now users are eagerly hoping that `cudf` will boost their productivity, better/smoother usability will pay very handsome dividend to everyone, because it'll likely to win their collaboration, loyalty, and contribution along the way.

**Comment by devavret** [comment]
@philtrade I'd like to point out a detail that there are two products here: cuDF, which has pandas like API, and libcudf, which is written in C++ and CUDA. The latter is the underlying layer used by the former. libcudf has users other than cuDF. Therefore, @jrhemstad was probably addressing cuDF developers here

> It is possible, but expensive. We should not enforce this behavior by default. Users of libcudf (meaning the cuDF python layer here) are always free to do what I suggested in [#1845 (comment)](https://github.com/rapidsai/cudf/pull/1845#discussion_r294103129).

He is not dismissing your concerns. 🙂 He's just asking @rgsl888prabhu to handle it in the python layer rather than pushing the responsibility down to CUDA layer.

**Comment by philtrade** [comment]
> libcudf has users other than cuDF.   Therefore, @jrhemstad was probably addressing cuDF developers here

👌  Thanks for the clarification and reminder @devavret, it's helpful to know!

Part of his reply was referring to my words below so I thought I was being addressed.

> Perturbing the original order is quite an unexpected intervention to callers who provide an ordered series

Regardless, I don't intend to steer the direction, the pieces are complex and the decision is your to make.  @jrhemstad, sorry if my comments inadvertently crossed some unknown boundaries.
