### ISSUE TITLE
[QST] Illegal Memory Access

### ISSUE THREAD

**Issue by datascientistpur** [rapidsai/cudf#5296]
Whenever I try to either join or filter the dataframe,I m getting runtime error 700.
The detailed error description  is:
RuntimeError:CUDA error encountered ar: /conda/conda-bld/libcudf_1580806686173/work/cpp/src/join/legacy/join_compute_apu.h:357:700 cudaErrorIllegalAddress an illegal memory address was encountered 

The code worked fine on cudf 0.10,but post upgrade to 0.12,started getting this error.
The data size is 4GB.

Specification:
GPU:Volta V100
GPU memory:32GB

Request help to resolve the issue.

**Comment by jrhemstad** [comment]
0.12 is quite old. Your error is being thrown from code that no longer exists. I suggest trying with the latest 0.14 or 0.15.

**Comment by datascientistpur** [comment]
@jrhemstad, wanted to know if 0.13 works,since 0.14 is in nightly mode?

**Comment by kkraus14** [comment]
@datascientistpur can you try with 0.13 and report back? There's no reproducer for us to try with.

**Comment by harrism** [comment]
Closing due to no response. Please reopen if this is still an issue.
