### ISSUE TITLE
branch-0.5 Join test fails again....

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#530]
* Using branch-0.5 tip as of today.
* Devuan ASCII GNU/Linux, with Miniconda 2.
* An Intel x86_64 machine with 16 GB RAM.

3 tests are failing on memory allocation. Snippet of the `LastTest.log` (which we get with `make test`):
```
[----------] 2 tests from MaxJoinTest/0, where TypeParam = TestParameters<(join_op)0, (gdf_method)1, std::tuple<std::vector<int, s
td::allocator<int> > >, false>
[ RUN      ] MaxJoinTest/0.HugeJoinSize
[       OK ] MaxJoinTest/0.HugeJoinSize (10670 ms)
[----------] 2 tests from MaxJoinTest/0, where TypeParam = TestParameters<(join_op)0, (gdf_method)1, std::tuple<std::vector<int, s
td::allocator<int> > >, false>
[ RUN      ] MaxJoinTest/0.HugeJoinSize
[       OK ] MaxJoinTest/0.HugeJoinSize (10670 ms)
[ RUN      ] MaxJoinTest/0.InputTooLarge
/home/eyalroz/src/blazing/cudf/cpp/tests/join/join_tests.cu:153: Failure
      Expected: rmm::alloc((&(the_column->data)), (host_vector.size() * sizeof(col_type)), (0), "/home/eyalroz/src/blazing/cudf/cp
p/tests/join/join_tests.cu", 153)
      Which is: 4
To be equal to: RMM_SUCCESS
      Which is: 0
/home/eyalroz/src/blazing/cudf/cpp/tests/join/join_tests.cu:154: Failure
      Expected: cudaMemcpy(the_column->data, host_vector.data(), host_vector.size() * sizeof(col_type), cudaMemcpyHostToDevice)
      Which is: 11
To be equal to: cudaSuccess
      Which is: 0
[  FAILED  ] MaxJoinTest/0.InputTooLarge, where TypeParam = TestParameters<(join_op)0, (gdf_method)1, std::tuple<std::vector<int, std::allocator<int> > >, false> (2410 ms)
[----------] 2 tests from MaxJoinTest/0 (13080 ms total)

[----------] 2 tests from MaxJoinTest/1, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, std::allocator<int> > >, false>
[ RUN      ] MaxJoinTest/1.HugeJoinSize
unknown file: Failure
C++ exception with description "parallel_for failed: invalid argument" thrown in the test body.
[  FAILED  ] MaxJoinTest/1.HugeJoinSize, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, std::allocator<int> > >, false> (10285 ms)
[ RUN      ] MaxJoinTest/1.InputTooLarge
/home/eyalroz/src/blazing/cudf/cpp/tests/join/join_tests.cu:153: Failure
      Expected: rmm::alloc((&(the_column->data)), (host_vector.size() * sizeof(col_type)), (0), "/home/eyalroz/src/blazing/cudf/cpp/tests/join/join_tests.cu", 153)
      Which is: 4
To be equal to: RMM_SUCCESS
      Which is: 0
/home/eyalroz/src/blazing/cudf/cpp/tests/join/join_tests.cu:154: Failure
      Expected: cudaMemcpy(the_column->data, host_vector.data(), host_vector.size() * sizeof(col_type), cudaMemcpyHostToDevice)
      Which is: 11
To be equal to: cudaSuccess
      Which is: 0
[  FAILED  ] MaxJoinTest/1.InputTooLarge, where TypeParam = TestParameters<(join_op)1, (gdf_method)1, std::tuple<std::vector<int, std::allocator<int> > >, false> (2427 ms)
[----------] 2 tests from MaxJoinTest/1 (12712 ms total)
```

**Comment by AK-ayush** [comment]
@eyalroz I also came up the same issue of failing `MaxJoinTest/0.InputTooLarge`. the real cause of this issue was gpu memory allocated by the some other process.  
Clear out your gpu memory before running the `make test`... after that all tests should run successfully.

**Comment by eyalroz** [comment]
> Clear out your gpu memory before running the `make test`... after that all tests should run successfully.

1. This can absolutely not be a reason for a test to fail. This is a test for the code we've written, not for the amount of available memory. Now, if _very little_ memory was available, then an appropriate message would be reasonable - saying "Not enough available GPU memory to run this test".
2. Actually, my GPU memory is completely clear and nothing else is using it. I just have a GPU with a smaller amount of memory. The code probably doesn't account for that.

**Comment by AK-ayush** [comment]
You said that you are using a GPU with smaller amount of memory. From my understanding, I can conclude the following... please correct me if I m wrong.  

```
[ RUN      ] MaxJoinTest/0.InputTooLarge
/cudf/cpp/tests/join/join_tests.cu:153: Failure
      Expected: rmm::alloc((&(the_column->data)), (host_vector.size() * sizeof(col_type)), (0), "/cudf/cpp/tests/join/join_tests.cu", 153)
      Which is: 4
To be equal to: RMM_SUCCESS
      Which is: 0
/cudf/cpp/tests/join/join_tests.cu:154: Failure
      Expected: cudaMemcpy(the_column->data, host_vector.data(), host_vector.size() * sizeof(col_type), cudaMemcpyHostToDevice)
      Which is: 11
To be equal to: cudaSuccess
      Which is: 0
``` 

As you can see `rmm::alloc(...)` is throwing error code 4(`RMM_ERROR_OUT_OF_MEMORY`) whereas the expected is 0(`RMM_SUCCESS`) as defined in enum in [memory.h](https://github.com/rapidsai/cudf/blob/branch-0.5/cpp/src/rmm/memory.h#L32)

Since this `rmm::alloc(...)` doesn't allocate the memory properly which is why `cudaMemcpy(...)` is throwing error code 11(`cudaErrorInvalidValue`) because it is trying to copy an improper pointer.

**Comment by eyalroz** [comment]
I understand this is what's happening, I'm just saying that the test should be written so that it doesn't happen. That is, on any GPU on which cudf is supported, the allocation size should be set so that we don't fail making the allocation (at least not with a relatively-empy GPU).

In my case, I have a GTX 1050 with 0 / 4040 MiB used memory, according to nvidia-smi.

**Comment by jrhemstad** [comment]
Duplicate of https://github.com/rapidsai/cudf/issues/369 

It's a known issue that this test will fail for GPUs with small amounts of GPU memory. The purpose of this test is to exercise inputs whose sizes were once causing an integer overflow. It is on my list to find an alternative way to test for this behavior that doesn't require allocating a large amount of GPU memory.

**Comment by eyalroz** [comment]
@jrhemstad : Oh, I thought that had already been taken care of :-(
