### ISSUE TITLE
[FEA] A cudf.config module to manage configuration options

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5311]
In a discussion with @jakirkham the idea of a `cudf.config` module, similar to [Dask](https://docs.dask.org/en/latest/configuration.html) was brought up.

The specific use case we had in mind was a way for users to specify whether or not to use pack/unpack serialization; but there may be other such "global" options that we may want to expose in the future.

**Comment by jakirkham** [comment]
One other idea Ashwin mentioned was configuring the RMM allocator used.

**Comment by brandon-b-miller** [comment]
+1 - could have an option here to disable/enable cross joins when implemented.

**Comment by jakirkham** [comment]
cc @rjzamora (in case you have needs for this as well)

**Comment by charlesbluca** [comment]
With #8153 merged, this configuration module could also be used to enable/disable packing of tables during serialization

**Comment by quasiben** [comment]
Would it make sense if this option existed at the dask-cuda level ?

**Comment by quasiben** [comment]
Ah, @charlesbluca pointed me to the previous dask-cuda discussion here:
https://github.com/rapidsai/dask-cuda/issues/601
