### ISSUE TITLE
[FEA] Improve `unique_count` to count the number of unique rows in a table

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#5314]
**Is your feature request related to a problem? Please describe.**

libcudf has a [`unique_count`](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/include/cudf/stream_compaction.hpp#L182) function, but it only works on individual columns. 

**Describe the solution you'd like**

I want a function that tells me the number of unique rows in a table.

**Comment by jrhemstad** [comment]
So it looks like the internal `unique_count` function [_already_ works on tables](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/src/stream_compaction/drop_duplicates.cu#L149), but the top-level API only accepts a column, which is wrapped in a [table](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/src/stream_compaction/drop_duplicates.cu#L310).

**Comment by harrism** [comment]
What is driving this need (so I can prioritize)?

**Comment by jrhemstad** [comment]
> What is driving this need (so I can prioritize)?

This allows computing the output size (in # of rows) of groupby without requiring a special groupby API.

**Comment by karthikeyann** [comment]
> So it looks like the internal `unique_count` function [_already_ works on tables](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/src/stream_compaction/drop_duplicates.cu#L149), but the top-level API only accepts a column, which is wrapped in a [table](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/src/stream_compaction/drop_duplicates.cu#L310).

table API was not required earlier. pandas [Dataframe.nunique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html) calculates _per column unique_count_.

Would simply exposing the detail API and a public API on table be enough?

**Comment by jrhemstad** [comment]
> table API was not required earlier. pandas [Dataframe.nunique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html) calculates _per column unique_count_.

Remember that libcudf is not Pandas. 

> Would simply exposing the detail API and a public API on table be enough?

Changing the existing `column_view` API to work on `table_view` is what I suggest.

**Comment by karthikeyann** [comment]
@jrhemstad do you need `null_policy::INCLUDE/EXCLUDE` and `nan_policy::NAN_IS_NULL/NAN_IS_VALID` functionality as well for this public API?
(this needs some extra code & special cases for implementing for `table_view`)

If they are not required, exposing detail API should be a better option.
```
cudf::size_type unique_count(table_view const& keys,
                             null_equality nulls_equal = null_equality::EQUAL,
                             cudaStream_t stream       = 0)
```

**Comment by jrhemstad** [comment]
> @jrhemstad do you need `null_policy::INCLUDE/EXCLUDE` and `nan_policy::NAN_IS_NULL/NAN_IS_VALID` functionality as well for this public API?
> (this needs some extra code & special cases for implementing for `table_view`)
> 
> If they are not required, exposing detail API should be a better option.
> 
> ```
> cudf::size_type unique_count(table_view const& keys,
>                              null_equality nulls_equal = null_equality::EQUAL)
> ```

We need whatever options are required such that `unique_count` can be used to compute the output size (in number of rows) of any groupby operation.
