### ISSUE TITLE
[FEA] Upgrade to Arrow 0.17.1

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#5323]
With the nvcc fixes merged into Arrow 0.17.1, we should upgrade as part of 0.15.

Additionally, once there's conda packages built for the CUDA pieces of arrow-cpp and pyarrow, we can avoid the static linking we're currently doing and dynamically link against the shared library.

**Comment by jakirkham** [comment]
FWIW there are CUDA packages in conda-forge ( https://github.com/conda-forge/arrow-cpp-feedstock/pull/146 ). Though it would be good if we can test them to make sure they behave as expected. If not, would be good to raise an issue or PR upstream regarding needed changes.

**Comment by quasiben** [comment]
Upgraded to 0.17 in https://github.com/rapidsai/cudf/commit/fc53eb4677ad77882bb28d26070b5258c8670ed4#diff-d4fd27eb0c2194718d94e2828c04d5a2
