### ISSUE TITLE
[BUG] read_orc reads incorrect data on one row

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#5324]
**Describe the bug**
When reading data via `cudf.read_orc` one of the rows seems to have incorrect data.

**Steps/Code to reproduce bug**
```python
import cudf

df = cudf.read_orc("row_bug.orc")
df.iloc[3874]

_col0     10100163
_col1         4125
_col2    637000238
Name: 3874, dtype: int32
```

**Expected behavior**
```python
import pyarrow.orc as orc
pdf = orc.ORCFile("row_bug.orc").read().to_pandas()
pdf.iloc[3874]

_col0     10100163
_col1         4125
_col2    927000494
Name: 3874, dtype: int32
```
Value of `_col2` at index location `3874` should be `927000494`

**Environment overview (please complete the following information)**
 - Method of cuDF install: Conda
   - 0.14 nightly on May 29

**Additional context**
Data here: [row_bug.orc.zip](https://github.com/rapidsai/cudf/files/4703780/row_bug.orc.zip)

Thanks @trstovall for pointing out the issue.

cc: @OlivierNV

**Comment by OlivierNV** [comment]
From the expanded data in the slack thread, it looks like perhaps a corner-case in RLE patched-base or delta mode.

**Comment by OlivierNV** [comment]
I can reproduce this, extracting stripe #26 (only 331 rows), there is one stray value very different than the others (points at RLE):
```
[324] 347000041 (0x14aecce9)
[325] 347000011 (0x14aecccb)
[326] 927000463 (0x3740e78f)
[327] 347000002 (0x14aeccc2)
[328] 347000003 (0x14aeccc3)
[329] 347000036 (0x14aecce4)
[330] 347000041 (0x14aecce9)
```

**Comment by OlivierNV** [comment]
Weird, it seems to be the 2nd value of a 6-value RLEv2-mode1 sequence.

**Comment by harrism** [comment]
Good job investigating. File an Apache issue?
