### ISSUE TITLE
[QST] Operations on StringColumns 

### ISSUE THREAD

**Issue by stokhos** [rapidsai/cudf#5338]
**What is your question?**

Dear cudf team:

I'm working on some data that are in type decimal.Decimal, because I want the precise solution from mathematical operations.  In order do so, I need to convert float into string, and string to deciaml.Decimal.

```python
from decimal import Decimal
import numpy as np
import cudf

a = Decimal('1.1')
b = Decimal('1.0')
np.mod(a,b) == Decimal('0.1') # this evaluates to True

df = cudf.DataFrame({'a':['1.1', '1.2','1.3', '1.
                                   'b':['1.0', '1.0','1.0', '1.0']})

df['a'].applymap(lambda x: Decimal(x))

in1=df['a']

def kernel(in1, out1):
    for i, x, in enumerate(in1):
        out1[i] = np.mod(Decimal(x), Decimal('1.0'))

df.apply_rows(kernel,
            incols=['a'],
            outcols=dict(out1=Decimal),
            kwargs=dict())

```
I'd like change the dtype of data from string to decimal.Decimal. 

I have tried applymap, apply_rows, and had no luck with them.

Is there a way of doing this? 

With applymap, i got an error say: AttributeError: 'StringColumn' object has no attribute 'unary_operator'.

With apply_rows, I got an error: Cannot get an array view of a StringColumn.

It looks like cudf may handle string in a way that is different from pandas. Could you talk a little bit more about this?

Best

**Comment by kkraus14** [comment]
@stokhos UDFs are not supported on string columns yet. I believe we improved this error message as of 0.14, but @galipremsagar could you check to see if this is still the behavior and fix it to throw a clearer error if possible?

**Comment by kkraus14** [comment]
For more details, the way `applymap` and `apply_rows` work in cuDF is by pipelining the function through Numba to just in time compile vectorized GPU code. For strings, the big challenge this poses is that an arbitrary number of temporary strings of temporary sizes could be produced and it's impossible to know how much memory to allocate up front to store these temporary strings. While it is possible to allocate memory from within a kernel, it's not efficient to do so, and the memory needs to be set aside from the normal memory pool to be allocated in host API calls.

**Comment by ntaherkhani** [comment]
Hi, 
Did the string support on UDFs in 0.14 version of cudf? if so, how can I install it?
thanks

**Comment by kkraus14** [comment]
> Hi,
> Did the string support on UDFs in 0.14 version of cudf? if so, how can I install it?
> thanks

It did not, we just improved the error message to indicate that UDFs are not yet supported on String / Category columns. You can follow #3802 for UDF support for Strings.
