### ISSUE TITLE
[QST] Should we depend on Thrust and CUB from github rather than the CUDA Toolkit?

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#5346]
Summarizing an offline discussion here. 

Is it OK to stop using Thrust from the CUDA Toolkit in RMM and cuDF and switch to getting a specific tag from github? Prompted by https://github.com/rapidsai/rmm/pull/378#issuecomment-634306806

Pros:

- We get a bunch of improvements (explicit allocator argument in device_vector, correct operation with PTDS), and access to new features (thrust::shuffle, not sure if we’ll need this, could be useful in testing)
- Ability to use a single version of Thrust across all versions of CUDA that we support (with flexibility to make Thrust version depend on CUDA version if necessary)

Cons:

- Thrust only fully tests the versions included with toolkit releases. (I don’t think this is a big problem, because it’s a header-only library and we test what we use.)
- Another dependency to fetch at configure/build time. This only happens at cmake configure time, and it's not a big issue longer term because we plan to centralize dependency management so we can fetch once for all RAPIDS libraries.

We’re just now hitting the point where we need the latest Thrust for a couple of things, so we haven’t had to make the switch up to now. I feel comfortable with switching, but wanted to get opinions.

Other comments: 
- from @trevorsm7: Conor and I are looking at adding a variant of thrust::transform_output_iterator for fixed_point columns. Using the latest thrust (or a side branch) would make it possible for us to contribute that iterator to thrust and maybe be able to use it in cudf within a reasonable timeframe.
- from @jrhemstad: I support moving to the latest as well. My comment was from a desire to make sure we thought and talked about it first.

Overall there were no objections, but we need to test cuDF first. #5315 CI should be a sufficient test.

**Comment by kkraus14** [comment]
Question from my end:
- Do we have any plans to expose thrust / cub types / classes in public APIs? If so does that pose any potential issue with regards to potentially mixing versions in different libraries and not versioning based on the toolkit shipped version?
- What are thrust / cub's support plans for gcc 5 / C++14 moving forward? Do they align with our support plans? Worst case we can just pin to the last version that supports our needs, but seems like we want to be able to continue moving forward with new releases once we make this change.

**Comment by harrism** [comment]
Good questions. 

> * Do we have any plans to expose thrust / cub types / classes in public APIs? If so does that pose any potential issue with regards to potentially mixing versions in different libraries and not versioning based on the toolkit shipped version?

I don't think there are any CUB types we would expose in public APIs -- CUB tends to be used inside of  implementations (mostly in device code).  We *may* expose `device_vector` in public APIs, however it is not very likely because it is a class template and libcudf public APIs are type-erased.  But I wouldn't rule it out completely. Note that `device_vector` is already part of the RMM API, inasmuch as that is a "public RAPIDS API".  As for whether this could cause issues: a) Maybe? but b) I think we should explicitly prevent that by using "rapids-core" build infrastructure to ensure RAPIDS libraries  share their dependencies as much as possible.

> * What are thrust / cub's support plans for gcc 5 / C++14 moving forward? Do they align with our support plans? Worst case we can just pin to the last version that supports our needs, but seems like we want to be able to continue moving forward with new releases once we make this change.

Thrust just deprecated C++03 and C++11, and GCC < 5. Given that CUDA is only just getting to C++17 support,  I  can't see Thrust dropping support for these within the next year or two, which I would  say aligns well with our needs. (I don't know our  specific support *plans* for compilers and C++ versions, I don't think we've discussed them in detail!)

**Comment by kkraus14** [comment]
> I think we should explicitly prevent that by using "rapids-core" build infrastructure to ensure RAPIDS libraries share their dependencies as much as possible.

I'm more concerned about someone else writing their own C++ code / application and using the thrust / cub that ship with the toolkit and it being incompatible.

**Comment by jrhemstad** [comment]
@felipeblazing @williamBlazing @jlowe @revans2 do you foresee this impacting you guys at all?

**Comment by jlowe** [comment]
My only concern would be mixing Thrust versions within an application, as @kkraus14 mentioned.  If we need to interface with libcudf and some other non-RAPIDS library and the latter expects the standard toolkit's Thrust, will there be issues?  I don't think so, but it would be good for someone with more Thrust/CUB knowledge to confirm.

**Comment by rongou** [comment]
To use PTDS, we need to compile all CUDA code with the `--default-stream per-thread` flag. At that point we can make sure we are using the correct/identical version of thrust/cub across the board.

**Comment by kkraus14** [comment]
> My only concern would be mixing Thrust versions within an application, as @kkraus14 mentioned. If we need to interface with libcudf and some other non-RAPIDS library and the latter expects the standard toolkit's Thrust, will there be issues? I don't think so, but it would be good for someone with more Thrust/CUB knowledge to confirm.

#5315 is essentially ready to merge, but we need to answer this question. If someone has a non-RAPIDS library built against the standard toolkit's Thrust / CUB is it going to cause issues? If it does we're making integrating with libcudf that much more difficult.

**Comment by jrhemstad** [comment]
> If someone has a non-RAPIDS library built against the standard toolkit's Thrust / CUB is it going to cause issues?

What kind of problems do you imagine? It's a header-only library, so it's not like we have to worry about depending on different DLLs. Furthermore, Thrust isn't exposed in any of our external interfaces.

**Comment by kkraus14** [comment]
> Furthermore, Thrust isn't exposed in any of our external interfaces.

This is the piece I was looking for. Do we intend to keep it this way moving forward or do we want to reserve the right to expose Thrust via our external interfaces in the future? If we expose it would there be potential issues in a library that used the toolkit shipped version passing an object to our newer version?

**Comment by harrism** [comment]
As I mentioned in #5315 `cudf::make_strings_column` takes a `device_vector`, so it *is* exposed in external interfaces. But arguably that is practically a detail API.
