### ISSUE TITLE
[FEA] Centralize common CMake functionality

### ISSUE THREAD

**Issue by jdye64** [rapidsai/cudf#5350]
As new components are being added to cuDF there are noticeable sections of CMake snippets that are being used over and over. One in particular is the "# - conda environment" section. These snippets are good candidates to be moved to CMake modules so they can be used from a central location.

**Comment by mt-jones** [comment]
@jdye64 
I agree. We should make an effort to centralize.
We should detail candidate build components to centralize, and determine where best to put them.

Would you share an example of your vision, here?

**Comment by jdye64** [comment]
Sure. I'm going through things right now and identifying what makes sense and what doesn't. Let me compile that list and will report back a proposal.

**Comment by jdye64** [comment]
@mt-jones Ok here is what I'm thinking for the scope of this PR. I really didn't intend for this PR to be a heavy task so I have identified 3 sections that would be nice to have a the cmake/Modules directory that already exists.

1. "build type" - This section deals with the type of build, straightforward but all modules use it and follow the same pattern from ./build.sh
2. "compiler options" - Lots of details here, all the settings could be overridden if included in a project that wanted to change them, also follows the ./build.sh cmake flags
3. "conda environment" - This snippet is universal and for the time being is needed in any project that wishes to interact with cudf, such as new external datasources.

Thoughts on this?

**Comment by beckernick** [comment]
@jdye64 @robertmaynard is this still relevant given the CMake updates?

**Comment by jdye64** [comment]
Nope, I forgot it was hanging around. I will close it
