### ISSUE TITLE
[BUG] cudf.read_json error from nested data is unclear

### ISSUE THREAD

**Issue by vinayakbhadage** [rapidsai/cudf#5371]
**Describe the bug**
cudf failed to read json file.

**Steps/Code to reproduce bug**
1. Creating json file using pandas: 
```
path_df="./test_df_1.json"
orient="records"
compression=None
pdf.to_json("./test_df_1.json",orient="records",compression=None,index=True)

got_df = cudf.read_json(path_df, orient=orient, compression=compression)

```

**Expected behavior**
expecting the dataframe but received the following error:

`NotImplementedError: struct<altId: string, audiences: list<item: string>, body: string, firstCreated: string, headline: string, id: string, instancesOf: list<item: string>, language: string, mimeType: string, provider: string, pubStatus: string, subjects: list<item: string>, takeSequence: int64, urgency: int64, versionCreated: string>`

**Environment overview (please complete the following information)**
 - Environment location: Azure Kubernetics Service 
 - Method of cuDF install: Docker + helm chart
  https://github.com/rapidsai/helm-chart

**Environment details**
rapids helm chart is installed in azure AKS using rapidsai docker image. 
`cudf.__version__`
is '0.13.0'

**Additional context**

**Comment by kkraus14** [comment]
It looks like you have nested data in your JSON which is not yet supported in cuDF. We should improve the error messaging here though.

**Comment by benfred** [comment]
see also https://github.com/rapidsai/cudf/issues/2362

**Comment by GregoryKimball** [comment]
Closing in favor of #8827
