### ISSUE TITLE
Update usage of `gdf` type aliases to use wrapper types

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#538]
For the non-fundamental column types (GDF_DATE32/DATE64/CATEGORY/TIMESTAMP) in libcudf, there are type aliases defined that are used for underlying type representation, e.g. `gdf_date32` uses `int` as it's underlying type representation:

https://github.com/rapidsai/cudf/blob/d71dcdcab0eb41891ab019ab3a7fbbe6f83588aa/cpp/include/cudf/types.h#L7 

There are also concrete C++ wrapper types for these non-fundamental column types. E.g.,

https://github.com/rapidsai/cudf/blob/d71dcdcab0eb41891ab019ab3a7fbbe6f83588aa/cpp/src/utilities/wrapper_types.hpp#L258

These types define the arithmetic and boolean operators that allow the wrapper to be used as if it were a fundamental type. 

For consistency and better code maintainability, all code that was using the type aliases (e.g., gdf_date32) should be updated to use the corresponding concrete wrapper types (e.g., cudf::date32).

Examples of using the type aliases that should be updated: 

https://github.com/rapidsai/cudf/blob/fcccb51a2d5e0764a4461ae46f3bc0fd885dee43/cpp/src/io/csv/datetime_parser.cuh#L68

https://github.com/rapidsai/cudf/blob/fcccb51a2d5e0764a4461ae46f3bc0fd885dee43/cpp/src/io/csv/datetime_parser.cuh#L119

**Comment by harrism** [comment]
Closing as the libcudf++ port fixes this.
