### ISSUE TITLE
[BUG] use device_uvector instead of device_vector when possible

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5380]
The new `device_uvector` does not initialize the allocated memory so it's much faster when the initial content is not relevant.
There are many places where `device_vector` can be replaced with `device_uvector` to improve the performance. Example:
```C++
rmm::device_vector<size_type> left_indices(left.num_rows());
thrust::sequence(
  rmm::exec_policy(stream)->on(stream), left_indices.begin(), left_indices.end(), 0);
```

**Comment by jrhemstad** [comment]
Furthermore, `device_uvector` has a `stream` argument in its constructor which allows correctly stream ordering the allocation. This is currently not possible with `device_vector` and can lead to significant issues when using non-default streams (see https://github.com/rapidsai/cudf/issues/2631).

**Comment by jrhemstad** [comment]
Didn't see this when I wrote https://github.com/rapidsai/cudf/issues/7287. Going to close this as a duplicate since I provided a little more context in that issue.
