### ISSUE TITLE
[FEA] Support reduction for NTH_ELEMENT 

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#5391]
**Is your feature request related to a problem? Please describe.**
In the Spark plugin, we currently rely on `cudf::reduce` for aggregate expression such as min/max and we would like to also use it for first/last (nth) expressions.

**Describe the solution you'd like**
I would like to be able to call `cudf::reduce` with aggregate expressions created by the following code.

```
cudf::make_nth_element_aggregation(0, null_policy::INCLUDE);
cudf::make_nth_element_aggregation(0, null_policy::EXCLUDE);
cudf::make_nth_element_aggregation(-1, null_policy::INCLUDE);
cudf::make_nth_element_aggregation(-1, null_policy::EXCLUDE);
```
This currently fails with `cuDF failure at: ../src/reductions/reductions.cpp:94: Unsupported reduction operator`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by karthikeyann** [comment]
Would using `get_element(column_view, index)` suffice?
https://github.com/rapidsai/cudf/blob/7a574df986d751dab7e4e93585a83918403702a3/cpp/include/cudf/copying.hpp#L715-L718

Note: ` get_element` does not support negative index or excluding nulls. 
> This currently fails with `cuDF failure at: ../src/reductions/reductions.cpp:94: Unsupported reduction operator`.

(https://github.com/rapidsai/cudf/pull/4739#discussion_r402513000)

**Comment by karthikeyann** [comment]
@andygrove

**Comment by andygrove** [comment]
@karthikeyann Sorry, I missed the mention somehow. 

The Spark first/last aggregate functions have an `ignoreNulls` parameter, so I don't think `get_element` alone will suffice unless there is another method that I can use to efficiently filter out the nulls first?

Also, since `get_element` doesn't support negative indices, I'm not sure how I would be able to use it for the `last` aggregate.
