### ISSUE TITLE
[BUG] read_parquet against s3 hits multiple errors

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#5402]
**Describe the bug**

Running `read_parquet('s3://blazingsql-colab/parquet_lan_logs/march_week5_00.parquet').shape` works in pandas but fails in cudf

* First time requires a manual `! pip install s3fs` due to no module `s3fs`
* Then causes `NoCredentialsError: Unable to locate credentials`

**Steps/Code to reproduce bug**

See above. 

**Expected behavior**

Expect the output `(9999999, 13)`

**Environment overview (please complete the following information)**

RAPIDS 0.13 from conda

**Environment details**

**Additional context**

Encountered while porting a rapidsacademy / blazingsql lab from sql to cudf: https://github.com/RAPIDSAcademy/rapidsacademy/blob/master/tutorials/security/tour/Tutorial_1_A_Network_Mapping.ipynb

**Comment by kkraus14** [comment]
@ayushdg is S3 support plumbed into fsspec yet? I don't think we ever supported reading directly from S3 in cudf Python and always deferred to dask-cudf for it.

**Comment by ayushdg** [comment]
Reading single files from s3 is supported in cuDF. Fsspec relies on the s3fs module for reading from s3 which is not a hard dependency while installing rapids. (Pandas relies on s3fs as well)

W.r.t the `NoCredentialsError`, I'm guessing this happens because s3fs expects credentials to be present unless `anon=True` is provided as a part of the `storage_options` kwarg. More info on that [here](https://docs.dask.org/en/latest/remote-data-services.html#amazon-s3).

```python
read_parquet('s3://blazingsqlcolab/parquet_lan_logs/march_week5_00.parquet', storage_options={'anon': True}).shape
```

**Comment by lmeyerov** [comment]
* For pandas parity, may want to make s3fs an actual dep, and as cudf is kitchen-sink anyways (e.g., expect http reads to work out of box too), but not a big deal IMO, was just surprising

* For the non-obvious arguments, I recommend matching pandas semantics for smart defaults, or doing a much clearer error + clear docs.

**Comment by kkraus14** [comment]
> * For pandas parity, may want to make s3fs an actual dep, and as cudf is kitchen-sink anyways (e.g., expect http reads to work out of box too), but not a big deal IMO, was just surprising

I don't think Pandas has this as a normal dependency but I could be mistaken. I'm not in favor of it being a dependency, but if it's not installed we should clearly error to install it.

> * For the non-obvious arguments, I recommend matching pandas semantics for smart defaults, or doing a much clearer error + clear docs.

Agreed that we should match Pandas semantics where it makes sense and clearly document and error/warn where we choose to differ from these semantics.

**Comment by beckernick** [comment]
@ayushdg is this now partially or fully covered by https://github.com/rapidsai/cudf/issues/6916 ?

**Comment by ayushdg** [comment]
Yup this should be covered by #6916 and starting pandas v1.2 the default behavior for pandas in this case is identical to existing cudf behavior

**Comment by lmeyerov** [comment]
cool -- any implications for s3 readers from dask?

**Comment by ayushdg** [comment]
Shouldn't have any implications for s3 reads through dask. s3 options are exposed today via the `storage_options` in the dask, cuDF and pandas. Closing the issue for now. Feel free to reopen this one or follow #6916 if the behavior differs.
