### ISSUE TITLE
Rename Column.replace() with Column.replace_attrs()?

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#541]
I propose that `Column.replace()` be renamed  `replace_attrs`. Or perhaps the `copy()` method can be extended to include the functionality of `replace()`?

https://github.com/rapidsai/cudf/blob/612ca60a7f41adb227ad556a91c76b69d2527d9b/cudf/column.py#L314

Reason: the name `replace()` should be used for the method for replacing *values* of the column, rather than class attributes (see #539).

Edit: added link to relevant LOC

**Comment by kkraus14** [comment]
`copy` should not modify default Python behavior for shallow/deep copies. I'm in favor of moving `replace` --> `replace_attrs`.

**Comment by kkraus14** [comment]
Resolved by #539
