### ISSUE TITLE
[BUG] dataframe.rename() causing column name mismatch issue because it is not using meta

### ISSUE THREAD

**Issue by think-high** [rapidsai/cudf#5413]
**Describe the bug**
I am reading multiple CSV(s) into dask_cudf dataframe using `dask_cudf.read_csv(...)`. There is a column name mismatch in the CSV(s) with a few CSV(s) having a column name as `"col2"` and the rest CSV(s) having column name as `"COL2"`

After reading the data I am successfully able to run` len(df)` but when I run `len(df)` after renaming any column(not specifically "col2" but ANY column) using `df.rename(...)`, then I get this error:

```
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   ['COL2']
  Missing: ['col2']
```

The meta of the dataframe after reading from csv has "col2" as shown below:
(I understand that's because the first csv has "col2" as column name and dask uses the initial data sample to infer the meta)
```
df._meta.dtypes
```
```
Unnamed: 0    int64
col1          int64
col2          int64
dtype:      object

```

My understanding is that since the rename in [dask/dataframe/core.py](https://github.com/dask/dask/blob/8eeb0e0194ef0561b4202f42de06c0b7fc0784b9/dask/dataframe/core.py#L3810) is calling `self.map_partitions` without the meta, that's why it is unable to infer the schema.
```
def rename(self, index=None, columns=None):
    ...
    return self.map_partitions(M.rename, None, columns=columns)
```
**Steps/Code to reproduce bug**

```
pd.DataFrame({"col1":[0,1],"col2":[0,1]}).to_csv("f1.csv")
pd.DataFrame({"col1":[0,1],"COL2":[0,1]}).to_csv("f2.csv")
df =dask_cudf.read_csv('f*.csv')
```
```
len(df)
```
4

After renaming any column, for example "col1" below
```
df = df.rename(columns={"col1":"COL1"})
len(df)
```
I get this error:
```
...
ValueError: The columns in the computed data do not match the columns in the provided metadata
  Extra:   ['COL2']
  Missing: ['col2']
```
<details>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-64-47ea2d13e0bb> in <module>
----> 1 len(df_1)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
   3471             return super().__len__()
   3472         else:
-> 3473             return len(s)
   3474 
   3475     @property

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/core.py in __len__(self)
    533     def __len__(self):
    534         return self.reduction(
--> 535             len, np.sum, token="len", meta=int, split_every=False
    536         ).compute()
    537 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/base.py in compute(self, **kwargs)
    164         dask.base.compute
    165         """
--> 166         (result,) = compute(self, traverse=False, **kwargs)
    167         return result
    168 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/base.py in compute(*args, **kwargs)
    442         postcomputes.append(x.__dask_postcompute__())
    443 
--> 444     results = schedule(dsk, keys, **kwargs)
    445     return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
    446 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, direct, retries, priority, fifo_timeout, actors, **kwargs)
   2672                     should_rejoin = False
   2673             try:
-> 2674                 results = self.gather(packed, asynchronous=asynchronous, direct=direct)
   2675             finally:
   2676                 for f in futures.values():

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/client.py in gather(self, futures, errors, direct, asynchronous)
   1972                 direct=direct,
   1973                 local_worker=local_worker,
-> 1974                 asynchronous=asynchronous,
   1975             )
   1976 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    822         else:
    823             return sync(
--> 824                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    825             )
    826 

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    337     if error[0]:
    338         typ, exc, tb = error[0]
--> 339         raise exc.with_traceback(tb)
    340     else:
    341         return result[0]

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/utils.py in f()
    321             if callback_timeout is not None:
    322                 future = asyncio.wait_for(future, callback_timeout)
--> 323             result[0] = yield future
    324         except Exception as exc:
    325             error[0] = sys.exc_info()

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1831                             exc = CancelledError(key)
   1832                         else:
-> 1833                             raise exception.with_traceback(traceback)
   1834                         raise exc
   1835                     if errors == "skip":

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/optimization.py in __call__()
   1020         if not len(args) == len(self.inkeys):
   1021             raise ValueError("Expected %d args, got %d" % (len(self.inkeys), len(args)))
-> 1022         return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
   1023 
   1024     def __reduce__(self):

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in get()
    149     for key in toposort(dsk):
    150         task = dsk[key]
--> 151         result = _execute_task(task, cache)
    152         cache[key] = result
    153     result = _execute_task(out, cache)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in <genexpr>()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in _execute_task()
    113     """
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in <listcomp>()
    113     """
    114     if isinstance(arg, list):
--> 115         return [_execute_task(a, cache) for a in arg]
    116     elif istask(arg):
    117         func, args = arg[0], arg[1:]

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/core.py in _execute_task()
    119         # temporaries by their reference count and can execute certain
    120         # operations in-place.
--> 121         return func(*(_execute_task(a, cache) for a in args))
    122     elif not ishashable(arg):
    123         return arg

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/utils.py in apply()
     29 def apply(func, args, kwargs=None):
     30     if kwargs:
---> 31         return func(*args, **kwargs)
     32     else:
     33         return func(*args)

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/core.py in apply_and_enforce()
   5240             return meta
   5241         if is_dataframe_like(df):
-> 5242             check_matching_columns(meta, df)
   5243             c = meta.columns
   5244         else:

~/anaconda3/envs/rapids-env2/lib/python3.7/site-packages/dask/dataframe/utils.py in check_matching_columns()
    680             extra_info = "Order of columns does not match"
    681         raise ValueError(
--> 682             "The columns in the computed data do not match"
    683             " the columns in the provided metadata\n"
    684             f"{extra_info}"
</details>

**Expected behavior**
The result from len(df) i.e 146112989

**Environment overview (please complete the following information)**
 - Method of cuDF install: conda install rapids nightly channel (0.14)

**Comment by kkraus14** [comment]
cc @quasiben

**Comment by quasiben** [comment]
Weird, when I started looking at this issue it was about NYCTaxi data :)

I think if you define the column names from the get go you should be ok:

> df =dask_cudf.read_csv('f*.csv', names=['col1', 'col2'])

Then rename however you please.  In the yellow taxi data set there are two names for the same column: `RateCodeID` and `RatecodeID` .  Probably you are seeing these errors now because dask recently merged in PR https://github.com/dask/dask/pull/5927 which aims to make these another column name relate issues easier to identify

**Comment by randerzander** [comment]
Thanks for the suggested workaround, but it's nice to allow column names to be read from the headers, even if there are slight differences.

Has Dask considered something like a read_csv flag which would use case and whitespace insensitive column name reading? That would eliminate a lot of painful cleanup code specifically for the taxi dataset, that I'd bet money applies to other public datasets.

**Comment by quasiben** [comment]
@randerzander agreed that would a nice work around -- I am not aware of any previous discussion where dask considered using flags to ignore case.  My guess is that this would be somewhat challenging giving more control to Dask to make decisions about what is and what is not considered a mistake.  Asking users to define columns is probably a good middle ground in that the users _knows_ what _should_ happen and Dask can appropriately reason about the number of columns moving forward

**Comment by GregoryKimball** [comment]
I agree that asking users to define columns is a good solution in this scenario
