### ISSUE TITLE
[FEA] NULL ?= NULL behavior in Join should be parameterized

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#542]
**Is your feature request related to a problem? Please describe.**
Currently, the libcudf implementation of `join` assumes that `NULL != NULL`, e.g., the rows `{1, 2, 3, NULL}` and `{1, 2, 3, NULL}` are *not* equal and would therefore not be considered a match for an inner-join.

However, Pandas considers `NaN == NaN` in an inner-join. Therefore, the current libcudf NULL behavior does not match what is expected in Pandas.

**Describe the solution you'd like**
For compatibility with Pandas and to provide greater flexibility to end-users, the behavior as to whether or not `NULL == NULL` should be an option that can be selected via a parameter to the Join APIs. 

**Additional context**
This is a result of discussion with @kkraus14 @williamBlazing about desired and expected null behavior in cuDF and libcudf.

**Comment by jrhemstad** [comment]
Update on this issue. We no longer consider `NaN == NULL`, and so the original argument about supporting `NaN == NaN` no longer applies. The updated `row_equality_comparator` already correctly handles `NaN == NaN`.

`NULL == NULL` is already a parameter in `row_equality_comparator`, and it would be trivial to expose it in the public API if that is still needed.

**Comment by harrism** [comment]
> `NULL == NULL` is already a parameter in `row_equality_comparator`, and it would be trivial to expose it in the public API if that is still needed.

Is it still needed? This was your request originally, right?

**Comment by jrhemstad** [comment]
It could still be done, but there hasn't been any user request for it lately, so I'm content to wait until someone asks for it.
