### ISSUE TITLE
[BUG] Regex code calls deprecated "rmmGetInfo" function

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#5436]
**Describe the bug**

The `regexec.cu` file contains a call to [`rmmGetInfo` ](https://github.com/rapidsai/cudf/blob/56769d4755091e3fe892fcdd020bd1e2a9a19cfe/cpp/src/strings/regex/regexec.cu#L104).

This[ function is deprecated](https://github.com/rapidsai/rmm/issues/305) and should be removed.

**Comment by harrism** [comment]
Looks like you deleted this in #5444 ?
