### ISSUE TITLE
[QST] Lots of package conflicts when installing cuDF on Ubuntu machine

### ISSUE THREAD

**Issue by athenawisdoms** [rapidsai/cudf#5445]
I am trying to install the RAPIDS cuDF package on my Ubuntu machine using conda.

Running the command

    conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf

or

    conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.13 python=3.7 cudatoolkit=10.2

both gives the following messages

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

This took a really long time, before attempting to estimate conflicts 172 packages 

> Examining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil libtiff fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt libxml2 setuptools numba cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache fontconfig pyopenssl cudf cx_oracle prompt_toolkit gstreamer numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet xz ipython_genutils joblib gst-plugins-base matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess zstd openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi blosc parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip sExamining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil libtiff fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt libxml2 setuptools numba cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache fontconfig pyopenssl cudf cx_oracle prompt_toolkit gstreamer numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet xz ipython_genutils joblib gst-plugins-base matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess zstd openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi blosc parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip sExamining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil libtiff libpng fastparquet python-snappy pillow freetype fsspec pexpect pytz et_xmlfile heapdict wcwidth qt glib traitlets mkl-service pyqt libxml2 setuptools numba cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache fontconfig pyopenssl cudf cx_oracle prompt_toolkit gstreamer numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib gst-plugins-base matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess zstd openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd libprotobuf numpy scikit-learn pyparsing h5py tornado dbus python-dateutil pygments ecos soupsieve cffi blosc parso ppft mkl_fft zlib dask kiwisolver cvxopt hdf5 patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi botExamining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil libtiff libpng fastparquet python-snappy pillow freetype fsspec pexpect pytz et_xmlfile heapdict wcwidth qt glib traitlets mkl-service pyqt libxml2 setuptools numba cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache fontconfig pyopenssl cudf cx_oracle prompt_toolkit gstreamer numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib gst-plugins-base matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess zstd openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd libprotobuf numpy scikit-learn pyparsing h5py tornado dbus python-dateutil pygments ecos soupsieve cffi blosc parso ppft mkl_fft zlib dask kiwisolver cvxopt hdf5 patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi botExamining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python sqlite jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six olefile thrift:   2Examining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python sqlite jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six olefile thrift:   2Examining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml readline fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six olefile thrift:  Examining conflict for dask-core pickleshare backcall python_abi osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml readline fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six olefile thrift:  Examining conflict for dask-core pickleshare backcall python_abi openssl osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft mysql-connector-c dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six Examining conflict for dask-core pickleshare backcall python_abi openssl osqp mkl_random cloudpickle cvxpy-base psutil fastparquet python-snappy pillow fsspec pexpect pytz et_xmlfile heapdict wcwidth qt traitlets mkl-service pyqt numba setuptools cython beautifulsoup4 multiprocess cycler sip pyyaml fastcache pyopenssl cudf cx_oracle prompt_toolkit numexpr msgpack-python wrapt markupsafe llvmlite future sortedcontainers urllib3 numpy-base jedi distributed pycparser protobuf pytables dill hmmlearn mysql-connector-python locket chardet ipython_genutils joblib matplotlib sqlalchemy python jdcal xlrd mock click matplotlib-base peewee ptyprocess openpyxl jinja2 ipython tblib decorator wheel nose pysocks cytoolz partd numpy scikit-learn pyparsing h5py tornado python-dateutil pygments ecos soupsieve cffi parso ppft mkl_fft mysql-connector-c dask kiwisolver cvxopt patsy zict cryptography pytorch ninja pox typing_extensions pathos packaging multitasking statsmodels certifi bottleneck requests yfinance bokeh pymysql pip scipy cvxpy arch scs toolz pandas idna six olefile thrift:

and finding lots of conflicts, such as the following  

```
Package typing_extensions conflicts for:
anaconda/linux-64::bokeh==2.0.2=py37_0 -> typing_extensions[version='>=3.7.4']
defaults/noarch::dask==2.9.2=py_0 -> bokeh[version='>=1.0.0'] -> typing_extensions[version='>=3.7.4']

Package cryptography-vectors conflicts for:
defaults/linux-64::pymysql==0.9.3=py37_0 -> cryptography -> cryptography-vectors[version='2.3.*|2.3.1.*']
anaconda/linux-64::urllib3==1.25.8=py37_0 -> cryptography[version='>=1.3.4'] -> cryptography-vectors[version='2.3.*|2.3.1.*']

Package hdf5 conflicts for:
anaconda/linux-64::pytables==3.5.2=py37h71ec239_1 -> hdf5[version='>=1.10.4,<1.10.5.0a0']
anaconda/linux-64::h5py==2.9.0=py37h7918eee_0 -> hdf5[version='>=1.10.4,<1.10.5.0a0']The following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

`conda list cudf` shows that cuDF is still not installed. 

Is there a better `conda` command to run to install cuDF?

**System Environment**

- Nvidia driver 440.33.01 
- CUDA Version 10.2.89
- cudatoolkit 10.2.89 
- Python 3.7.4
- conda 4.8.3
- Ubuntu 18.04
- Nvidia 2080 Ti

**Comment by kkraus14** [comment]
@athenawisdoms could you dump the output of `conda list` here? Alternatively, if creating a new environment is an option I'd suggest taking that route and doing:

```
conda create --name rapids -c rapidsai -c nvidia -c conda-forge -c defaults python=3.7 cudatoolkit=10.2 cudf=0.14
```

NOTE: 0.14 just released so upgraded cudf to 0.14 in the command, but feel free to roll it back if needed.

**Comment by athenawisdoms** [comment]
@kkraus14 Thanks your suggestion to createa a new environment works!

However, I'll still like to install cudf to my existing environment. Here's the `conda list` output as requested. Wonder if you can identify the problem...

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
arch                      4.9.1           np116py37h14c3975_0    bashtage
backcall                  0.1.0                    py37_0    anaconda
beautifulsoup4            4.8.2                    py37_0    anaconda
blas                      1.0                         mkl  
blosc                     1.16.3               hd408876_0    anaconda
bokeh                     2.0.2                    py37_0    anaconda
bottleneck                1.3.1            py37hdd07704_0    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h2e261b9_0    anaconda
chardet                   3.0.4                 py37_1003    anaconda
click                     7.0                      py37_0    anaconda
cloudpickle               1.4.1                      py_0    anaconda
cryptography              2.9.2            py37h1ba5d50_0    anaconda
cudatoolkit               10.2.89              hfd86e86_1    anaconda
cvxopt                    1.2.0            py37hfa32c7d_0    anaconda
cvxpy                     1.0.24           py37he1b5a44_0    conda-forge
cvxpy-base                1.0.24           py37he1b5a44_0    conda-forge
cx_oracle                 7.0.0            py37h7b6447c_0    anaconda
cycler                    0.10.0                   py37_0    anaconda
cython                    0.29.13          py37he6710b0_0    anaconda
cytoolz                   0.10.1           py37h7b6447c_0    anaconda
dask                      2.9.2                      py_0  
dask-core                 2.9.2                      py_0  
dbus                      1.13.6               h746ee38_0    anaconda
decorator                 4.4.0                    py37_1    anaconda
dill                      0.3.1.1                  py37_0    anaconda
distributed               2.16.0                   py37_0    anaconda
ecos                      2.0.7           py37h3010b51_1000    conda-forge
et_xmlfile                1.0.1                    py37_0    anaconda
expat                     2.2.6                he6710b0_0    anaconda
fastcache                 1.1.0            py37h516909a_0    conda-forge
fastparquet               0.4.0            py37h03ebfcd_0    conda-forge
fontconfig                2.13.0               h9420a91_0    anaconda
freetype                  2.9.1                h8a8886c_1    anaconda
fsspec                    0.7.1                      py_0    anaconda
future                    0.17.1                py37_1000    conda-forge
glib                      2.56.2               hd408876_0    anaconda
glpk                      4.65                 h3ceedfd_2    anaconda
gmp                       6.1.2                h6c8ec71_1  
gsl                       2.4                  h14c3975_4    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.9.0            py37h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
heapdict                  1.0.1                      py_0    anaconda
hmmlearn                  0.2.3            py37hc1659b7_1    conda-forge
icu                       58.2                 h9c2bf20_1  
idna                      2.8                      py37_0    anaconda
intel-openmp              2019.4                      243    anaconda
ipython                   7.7.0            py37h39e3cac_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.15.1                   py37_0    conda-forge
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.13.2                   py37_0    anaconda
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.1.0            py37he6710b0_0    anaconda
libedit                   3.1.20181209         hc058e9b_0    anaconda
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.6.0                hdbcaa40_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_0    anaconda
libuuid                   1.0.3                h1bed415_2    anaconda
libxcb                    1.13                 h1bed415_1    anaconda
libxml2                   2.9.9                hea5a465_1    anaconda
llvmlite                  0.32.1           py37hd408876_0    anaconda
locket                    0.2.0                    py37_1    anaconda
lz4-c                     1.8.1.2              h14c3975_0    anaconda
lzo                       2.10                 h49e0be7_2  
markupsafe                1.1.1            py37h7b6447c_0    anaconda
matplotlib                3.1.1            py37h5429711_0    anaconda
matplotlib-base           3.1.3            py37hef1b27d_0  
metis                     5.1.0                hf484d3e_4    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.0.2            py37h7b6447c_0    anaconda
mkl_fft                   1.0.12           py37ha843d7b_0    anaconda
mkl_random                1.0.2            py37hd81dba3_0    anaconda
mock                      3.0.5                    py37_0    conda-forge
msgpack-python            1.0.0            py37hfd86e86_1    anaconda
multiprocess              0.70.9           py37h516909a_0    conda-forge
multitasking              0.0.9                      py_0    ranaroussi
mysql-connector-c         6.1.11               h597af5e_0  
mysql-connector-python    8.0.18           py37h9c95fcb_1    anaconda
ncurses                   6.1                  he6710b0_1    anaconda
ninja                     1.9.0            py37hfd86e86_0    anaconda
nose                      1.3.7                    py37_2    conda-forge
numba                     0.49.1           py37h0573a6f_0    anaconda
numexpr                   2.7.0            py37h9e4a6bb_0    anaconda
numpy                     1.16.4           py37h7e9f1db_0    anaconda
numpy-base                1.16.4           py37hde5b4d6_0    anaconda
olefile                   0.46                     py37_0    anaconda
openblas                  0.3.3             h9ac9557_1001    conda-forge
openpyxl                  2.6.2                      py_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
osqp                      0.5.0            py37hb3f55d8_0    conda-forge
packaging                 20.3                       py_0    anaconda
pandas                    1.0.3            py37h0573a6f_0    anaconda
parso                     0.5.1                      py_0    conda-forge
partd                     1.1.0                      py_0    anaconda
pathos                    0.2.5                      py_0    conda-forge
patsy                     0.5.1                    py37_0    anaconda
pcre                      8.43                 he6710b0_0    anaconda
peewee                    3.9.2            py37h6b74fdf_0    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                    py37_0    anaconda
pillow                    7.1.2            py37hb39fc2d_0    anaconda
pip                       19.1.1                   py37_0    conda-forge
pox                       0.2.7                      py_0    conda-forge
ppft                      1.6.6.1                  py37_0    conda-forge
prompt_toolkit            2.0.9                    py37_0    anaconda
protobuf                  3.6.0            py37hf484d3e_0    anaconda
psutil                    5.7.0            py37h7b6447c_0    anaconda
ptyprocess                0.6.0                    py37_0    conda-forge
pycparser                 2.20                       py_0    anaconda
pygments                  2.4.2                      py_0    conda-forge
pymysql                   0.9.3                    py37_0  
pyopenssl                 19.1.0                   py37_0    anaconda
pyparsing                 2.4.2                      py_0    conda-forge
pyqt                      5.9.2            py37h05f1152_2    anaconda
pysocks                   1.7.1                    py37_0    anaconda
pytables                  3.5.2            py37h71ec239_1    anaconda
python                    3.7.3                h0371630_0    anaconda
python-dateutil           2.8.0                    py37_0    anaconda
python-snappy             0.5.4            py37he6710b0_0  
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.5.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.3.1            py37h7b6447c_0    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
rarfile                   3.1                      pypi_0    pypi
readline                  7.0                  h7b6447c_5    anaconda
requests                  2.22.0                   py37_1  
scikit-learn              0.22.1           py37hd81dba3_0  
scipy                     1.4.1            py37h0b6359f_0  
scs                       2.0.2           py37h0290663_1000    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8           py37hf484d3e_0    anaconda
six                       1.12.0                   py37_0    anaconda
snappy                    1.1.7                hbae5bb6_3  
sortedcontainers          2.1.0                    py37_0    anaconda
soupsieve                 2.0.1                      py_0    anaconda
sqlalchemy                1.3.7            py37h7b6447c_0    anaconda
sqlite                    3.28.0               h7b6447c_0    anaconda
statsmodels               0.10.1           py37hdd07704_0    anaconda
suitesparse               5.2.0                h9e4a6bb_0    anaconda
tbb                       2019.4               hfd86e86_0    anaconda
tblib                     1.6.0                      py_0    anaconda
thrift                    0.11.0           py37hf484d3e_0  
tk                        8.6.8                hbc83047_0    anaconda
toolz                     0.10.0                     py_0    anaconda
tornado                   6.0.3            py37h7b6447c_0    anaconda
traitlets                 4.3.2                    py37_0    conda-forge
typing_extensions         3.7.4.1                  py37_0    anaconda
unrar                     0.4                      pypi_0    pypi
urllib3                   1.25.8                   py37_0    anaconda
wcwidth                   0.1.7                    py37_0    anaconda
wheel                     0.33.4                   py37_0    conda-forge
wrapt                     1.11.2           py37h7b6447c_0  
xlrd                      1.2.0                    py37_0    anaconda
xz                        5.2.4                h14c3975_4    anaconda
yaml                      0.1.7                h96e3832_1    anaconda
yfinance                  0.1.54                     py_0    ranaroussi
zict                      2.0.0                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.3.7                h0b5b093_0    anaconda
```

**Comment by kkraus14** [comment]
The things that stick out to me from your environment are `pandas`, `dask`, `dask-core`, and `distributed`.

We currently require `pandas >=0.25.3,<1.0.0a0`, `dask >=2.15.0`, `dask-core >=2.15.0`, `distributed >=2.15.0`.

There's also likely a lot of conflicts coming from trying to move from defaults to conda-forge in your environment where you could try:
```
conda install -c nvidia -c rapidsai -c numba -c defaults -c conda-forge "cudf" "pandas" "dask" "distributed"
```

**Comment by kkraus14** [comment]
Closing as answered.
