### ISSUE TITLE
[FEA] provide ORC schema evolution

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#5447]
**Is your feature request related to a problem? Please describe.**
ORC has a "standard" for schema evolution.  Not all tools support it fully, but a lot do, and Spark in particular is one that does. It lets you do a lot of crazy things.  Not just re-order columns and add new ones.  In some cases it also lets you change the type of a column (very similar to cast).  This can be helpful if you started off with a column of int indexes, and then realized that they are going to overflow and want to switch to longs without rewriting all of your old files.

It does this by having a reader schema in addition to the file schema.  The reader schema says what a user(reader) wants the output data to look like. Orc then matches up the schemas based either off of the names of the columns (configurable if it is case sensitive or not) or the order of the columns if there are no names in the file schema.  Orc then uses a set of rules to figure out if it can coerce a column in the file into the desired output type.  The rules are kind of complex and I am happy to list what I have learned by reading the code here if needed.  

**Describe the solution you'd like**
I would like one of two options.  I'm not sure which fits better with the use cases that people have.

1. Provide a reader schema in some form to the orc reader and have it handle doing all of that for me.  The reader schema would likely be based off of cudf types instead of Orc types.
2. Provide a separate schema evolution engine. It would take a table, the tables schema, and a reader schema.  It would then do the checks and modifications to produce the desired output table.

Part of me would prefer the second option, because spark supports schema evolution for JSON, Orc, Parquet, and Avro.  It looks like I could reuse the same engine for other formats if I know that they support a subset of another engine that cudf supports.

**Describe alternatives you've considered**
I could do all of this myself in java/scala which is specific to the spark accelerator plugin, but then others would not benefit form it.

**Additional context**
Parquet has no standard for schema evolution.  Each tool has to come up with their own set of modifications that they support.  Avro does have a "standard". I have not dug into the details of it.  It mostly looks like column addition/removal and reordering.

Be aware that this also impacts nested types.  A struct can typically evolve the columns within itself too.  This means the engine needs a way to get a schema that has names for the children types, not just positions.

**Comment by sameerz** [comment]
@vuule can we discuss whether this is on the cuIO roadmap?

**Comment by vuule** [comment]
@revans2 can you please share a reference for the ORC schema evolution standard?

**Comment by revans2** [comment]
Sorry it looks like I am wrong.  It is not part of the specification.  Not even the [ORCv2](https://orc.apache.org/specification/ORCv2/) that is still WIP. It is built into the java APIs.

https://github.com/apache/orc/blob/rel/release-1.6.9/java/core/src/java/org/apache/orc/impl/SchemaEvolution.java

I looked for similar code in the C++ API and it is not there. When I got the initial ORC presentation/pitch from Owen and the Horton-works team they really pushed the reader schema like with Avro. I guess I assumed that it would just be replicated in the C++ code too.  But I am wrong. For some reason I keep seeing in my head a web page that had a chart in it for what could be mapped to what so I might just be imagining things. Because this is java specific I don't expect core cudf to support this. I will provide the information here on how schema evolution works as derived from the java APIs for the 1.6.9 release.  That way the java API team can at least decide what to do with it. But I am going to need a bit of time to put it together.

**Comment by revans2** [comment]
Sorry I started to create a chart, but I found the ruled in another file.  

https://github.com/apache/orc/blob/acbf0205e0919d16f7daf239c367fdd6dfb22ecc/java/core/src/java/org/apache/orc/impl/ConvertTreeReaderFactory.java#L2122-L2249

It is very clear from the comment that these are hives rules, so it looks like ORC inherited them.

**Comment by revans2** [comment]
After having discussed this on the Spark side we feel that we should just drop this request and just implement it internally. It looks like it would be a very java specific feature and if others are interested in having it they can reopen this and we can discuss if we implement this as a part of the java API or in C++.
