### ISSUE TITLE
[FEA] Filtering non-alphanumeric characters and words based on size

### ISSUE THREAD

**Issue by Garfounkel** [rapidsai/cudf#5449]
**Is your feature request related to a problem? Please describe.**
@VibhuJawa and I are working on NLP vectorizers like [CountVectorizer](https://github.com/rapidsai/cuml/pull/2267) and HashingVectorizer for cuML and we started benchmarking those on real datasets. The [reference implementation](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html) from sklearn tokenizes using a regexp (`r"(?u)\b\w\w+\b"`) which select tokens of 2 or more alphanumeric characters. This essentially has the side effect of ignoring punctuation and special characters. Our approach was different since regexp are known to be a difficult problem for GPU. Instead we decided to replace a fixed set of punctuation characters by a delimiter character during the preprocessing step. Tokens are then created based on said delimiter. This solution is far from perfect since our initial list of punctuation characters do not cover every potential unwanted characters from a real dataset. An other thing this solution doesn't cover is the case of tokens consisting of a single alphanumeric character which are ignored by sklearn's regexp.

**Describe the solution you'd like**
We'd like a built-in way to filter out non-alphanumeric characters as well as words smaller than n characters. The definition of a word can be based on a specific delimiter.
```python
s = Series(['abc£def', 'I am a developer', '℉℧ is not alphanumeric'])
s.str.filter_non_words(min_word_size=2, delimiter=' ')
# Series(['abc def', ' am   developer', '  is not alphanumeric'])
```
Note that the non-words are replaced by the delimiter so that `'abc£def'` can later be tokenized as two sperate tokens: `['abc', 'def']`.

Edit: Actually it's probably better to separate the two functionalities to make them more generic, something like:
```python
>> s.str.replace_non_alphanumns(replacement_char=' ')
>> s.str.replace_small_tokens(token_len=2, replacement_char=' ' , delimiter=' ')
```

**Describe alternatives you've considered**
We tried computing the non-alphanumeric characters from the dataset using a regexp and use this instead of our fixed punctuation list. 
```python
def get_punctuation_list(docs):
    characters = docs.str.character_tokenize().unique()
    return characters.str.extract('([^\w\d])', expand=False).dropna().tolist() 

punctuation_list = get_punctuation_list(doc)
doc = doc.str.replace(punctuation_list, [delimiter], regex=False)
```
The problem with this approach is that as `punctuation_list` grows, `doc.str.replace(punctuation_list, [delimiter], regex=False)` becomes way slower, about 45 seconds on a dataset of 5M tweets, against a few msec when using our fixed (and much smaller) punctuation list.

**Comment by VibhuJawa** [comment]
For `replace_non_alphanumns`:

>> s.str.replace_non_alphanumns(replacement_char=' ')

Another option i think can be to add functionality to `nvstrings.translate`  to add an argument to map  `unspecified characters` to a default  character instead of keeping it unchanged.  

```python
>>> s =cudf.Series["abc$def"])
>>> print(s.str.translate(str.maketrans('abcdef','abcdef'), missing_char = ' ' ))
['HELLo', 'tHErE', 'worLd]
```

**Comment by Garfounkel** [comment]
With the `translate` approach suggested by @VibhuJawa:
```python
def get_punctuation_list(docs):
    characters = docs.str.character_tokenize().unique()
    return characters.str.extract('([^\w\d])', expand=False).dropna().tolist()

punctuation_list = get_punctuation_list(doc)  # ~4 seconds

ord_delimiter = ord(delimiter)
table = {ord(char): ord_delimiter for char in punctuation_list}

doc = doc.str.translate(table)  # ~8 seconds
```
We are faster than the described alternative we first tried:
```python
punctuation_list = get_punctuation_list(doc)  # ~4 seconds
doc = doc.str.replace(punctuation_list, [delimiter], regex=False)  # ~40 seconds
```
But we still believe that two dedicated functions to remove non-numeric as well as small words would be faster. This seems generic enough to be something that could be reused as well.

**Comment by VibhuJawa** [comment]
CC: @davidwendt / @randerzander  .

**Comment by Garfounkel** [comment]
The original issue was not very clear and mixed two separate problems as one. Closing in favor of #5520 and #5521.
