### ISSUE TITLE
[BUG] Series.str.translate doesn't translate some unicode characters.

### ISSUE THREAD

**Issue by Garfounkel** [rapidsai/cudf#5453]
**Describe the bug**
It seems like some unicode characters are not translated by `Series.str.translate()`.

**Steps/Code to reproduce bug**
```python
from cudf import Series

>>> table = str.maketrans('😢@“', '   ')
{128546: 32, 64: 32, 8220: 32}

>>> Series(['😢test “@']).str.translate(table)
0    😢test “ 
dtype: object
```

**Expected behavior**
All character within the table should be replaced by the corresponding character, including `😢` or `“`.

**Comment by galipremsagar** [comment]
I don't think we currently support unicode(instead we support UTF-8) in our string apis. But would defer to @davidwendt on this.

**Comment by davidwendt** [comment]
So strings in Python source code are always managed as Unicode. I believe the Cython layer usually converts strings to UTF-8 when passing to libcudf. I need to trace this through to see what is happening to the characters during the `translate()` call.
