### ISSUE TITLE
[FEA] Ability to build libcudf with reduced runtime dependencies

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#5457]
**Is your feature request related to a problem? Please describe.**
The Spark plugin uses libcudf.so outside of a conda environment.  It makes the plugin much more user friendly and avoids the complexity of ensuring the available conda environment matches the jar shipped with the user's application.  To run outside of a conda environment and make the Java bindings jar easier to use, the libcudf.so runtime dependencies are bundled into the jar.

Back in 0.14, this was relatively reasonable to do because libcudf.so had a very limited set of runtime dependencies that were not expected to be on every OS instal (ignoring CUDA which is a prerequisite for the kernel driver):
- libboost_filesystem.so.1.70.0
- librmm.so

Recently the runtime dependency list has drastically increased for libcudf.so.  Here's the list of new runtime dependencies since 0.14 as reported by `ldd` (ignoring updated versions of existing dependencies, like libboost_filesystem.so):
- libarrow_cuda.so.17
- libarrow.so.17
- libaws-c-common.so.0unstable
- libaws-c-event-stream.so.0unstable
- libaws-checksums.so
- libaws-cpp-sdk-core.so
- libaws-cpp-sdk-core.so
- libaws-cpp-sdk-s3.so
- libbz2.so.1.0
- libcom_err.so.3
- libcrypto.so.1.1
- libcurl.so.4
- libgssappi_krb5.so.2
- libk5crypto.so.3
- libkrb5.so.3
- libkrb5support.so.0
- liblz4.so.1
- libprotobuf.so.22
- libresolv.so.2
- libsnappy.so.1
- libssh2.so.1
- libssl.so.1.1
- libzstd.so.1

A small subset of these additional dependencies will be on every machine, but most will not.  Getting libcudf.so to run turnkey outside of a conda environment means shipping all these libraries with the package which will significantly bloat the jar.  Also I suspect most of the use cases we need for libcudf do not require these dependencies at all, but we can't load libcudf.so without them.

**Describe the solution you'd like**
I'd like the ability to use the core of libcudf without the Arrow datasource features and all the dependency baggage associated with it.  IIUC Arrow is not needed by the core algorithms in libcudf and is only used for data source and interop.  One approach is to split libcudf into libcudf_core.so and libcudf.so.  The former is just the core algorithms and data structures of libcudf, while the latter contains support for Arrow data sources, IPC, etc. 
 libcudf.so would have a runtime dependency on libcudf_core.so.  This would allow us to ship libcudf_core.so with a minimal set of runtime dependencies.

**Describe alternatives you've considered**
Another possible approach is cmake build flags to enable/disable the additional Arrow functionality that is triggering all the extra dependencies.  That would allow someone to build libcudf.so with a reduced dependency list (and necessarily reduced functionality).

**Comment by kkraus14** [comment]
cc @mt-jones who's reworking the build system to better handle the case(s) where people don't want to use conda

@jlowe We needed to bump to Arrow 0.17.1 as we've had problems with people moving past Arrow 0.15 and not being able to use cudf in their environments. A short term fix for this would likely be to add back in the ability to static link the needed Arrow bits at the cpp layer, but put that behind a CMake conditional variable. Is that something someone on the Spark team can take on?

**Comment by jlowe** [comment]
> A short term fix for this would likely be to add back in the ability to static link the needed Arrow bits at the cpp layer

Curious, why was the static linking removed?

> Is that something someone on the Spark team can take on?

Assuming this isn't an easy fix from someone more knowledgable, we'll have no choice but to do so.  The Java 0.15 build is blocked by this.

**Comment by kkraus14** [comment]
> Curious, why was the static linking removed?

Our CI has been built around conda where we can just mark it as a dependency and then we don't have to worry about building Arrow. The Python environment also requires PyArrow which requires a full arrow-cpp shared library install regardless, so it was a two birds, one stone situation.

The static linking did some janky things to work around the fact that the Arrow GPU headers / library weren't distributed as nice packages in Arrow 0.15 which we very much didn't want to maintain any more. In hindsight it seems we should have just removed the janky things and controlled static vs dynamic linking via a CMake conditional variable.

> Assuming this isn't an easy fix from someone more knowledgable, we'll have no choice but to do so. The Java 0.15 build is blocked by this.

It should be mostly just adding back what was deleted, bumping the relevant Arrow versions, removing the janky symbol handling of the Arrow GPU static linkage, and then combining the current approach and the static linking approach via CMake conditional variables.

If someone could take a stab at it, it would be appreciated and I'm happy to guide / shepherd things through.

**Comment by rongou** [comment]
I can take a look at this.

**Comment by kkraus14** [comment]
> I can take a look at this.

The changes made were in this PR: https://github.com/rapidsai/cudf/pull/5408

**Comment by rongou** [comment]
If I understand the change correctly, before we were using `ExternalProject` to pull in arrow and build it locally, now we rely on the arrow conda package, which causes the java build to choke. I think we have a few options in terms of building java:
* Use `FetchContent` in cuDF to get arrow like we are doing for other c++ dependencies. We'd still need to build arrow locally.
* Use `conda` in the java CI container. This'll make the java build matches more closely with the c++/python build.
* Install arrow in the java CI build container and help cmake find it.

In all these approaches, we'd still need to package the .so files in the jar; or we can ask the user to install the binary dependencies, or perhaps provide a container with all the dependencies.

A more ambitious plan is to separate out the common c++ components used by both python and java, and package them separately.

**Comment by kkraus14** [comment]
> now we rely on the arrow conda package, which causes the java build to choke.

To be clear we're not relying specifically on conda, but we are relying on `libarrow` and `libarrow_cuda` shared libraries being available on the cmake search path.

> Use `conda` in the java CI container. This'll make the java build matches more closely with the c++/python build.

I don't think you want to do this. Conda ships a build toolchain based on gcc-7 and C++11 ABI which means that if you take this route it won't work on CentOS / RHEL and won't work on Ubuntu 16.04 with gcc-5 (works if you upgrade to gcc-7).

> In all these approaches, we'd still need to package the .so files in the jar; or we can ask the user to install the binary dependencies, or perhaps provide a container with all the dependencies.

With `ExternalProject_Add` or `FetchContent` you could build static libraries for `libarrow` and `libarrow_cuda` and then statically link them into `libcudf` so you don't need to ship any arrow related shared libraries. This is what we were previously doing with `ExternalProject_Add`.
