### ISSUE TITLE
[BUG] Parsing dates with read_csv adds 1 day to dates

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#546]
Parsing dates with read_csv adds 1 day to date.

```python
>>> with open('test.csv', 'w') as f:
...   f.write('1970-1-1,1970-1-2\n')
... 
18
>>> from cudf import read_csv
>>> df = read_csv('test.csv', names=list('ab'), dtype=['date','date']) 
>>> print(df)
                        a                       b
0 1970-01-02T00:00:00.000 1970-01-03T00:00:00.000
>>> df.a.astype('q')[0] == 24 * 3600 * 1000
True
```

```python
>>> # conversion from Python's date works:
>>> from datetime import date
>>> from cudf import DataFrame as DF
>>> DF({'a': [date(1970,1,1)]}).a.astype('q')[0] == 0
True
```

**Environment details (please complete the following information):**
 - Docker
 - Ubuntu 16.04 amd64
 - P100 and driver 396.44
 - CUDA: 9.2
 - Method of cuDF install: from source (commit 7aa3799e73948899a85e70bc73d3cea50b65dff1)
 - gcc/g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
 - cmake version 3.13.1

**Comment by j-ieong** [comment]
This looks like a bug in `datetime_parser.cuh`.

From what I can tell, previously 3ee81553efea9b0a416cf826926adfd1ccaf9119 fixed a couple of off-by-1 issues but I guess broke this one by removing the "-1"...
