### ISSUE TITLE
[BUG] dask_cudf.from_cudf corrupting data when using LocalCUDACluster()

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#5462]
**Describe the bug**
`dask_cudf.from_cudf` seems to be corrupting data when using LocalCUDACluster().
In the script below, if you ommit ` dask_client=Client(LocalCUDACluster())` then there is no issue, but for my use case, that is not an option. The code below is a simple reproducer, not the full actual use case of interest.

**Steps/Code to reproduce bug**
```
import cudf
import dask_cudf
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

def main():
    dask_client=Client(LocalCUDACluster())

    df1 = cudf.DataFrame()
    df1['a'] = [i%2 for i in range(10)]
    df1['b'] = 3

    df2 = cudf.DataFrame()
    df2['a'] = [i%3 for i in range(10)]

    df = df1.merge(df2, on=['a'], how='outer')

    print(df)

    df = dask_cudf.from_cudf(df, npartitions=2)

    print(df.compute())

if __name__ == "__main__":
    main()  
```
Outputs:
```
    a     b
0   2  null
1   2  null
2   2  null
3   0     3
4   0     3
5   1     3
6   1     3
7   0     3
8   1     3
9   0     3
10  1     3
11  0     3
12  1     3
13  0     3
14  0     3
15  1     3
16  1     3
17  0     3
18  1     3
19  0     3
20  1     3
21  0     3
22  1     3
23  0     3
24  0     3
25  1     3
26  1     3
27  0     3
28  1     3
29  0     3
30  1     3
31  0     3
32  1     3
33  0     3
34  0     3
35  0     3
36  0     3
37  0     3

    a     b
0   2  null
1   2  null
2   2  null
3   0     3
4   0     3
5   1     3
6   1     3
7   0     3
8   1     3
9   0     3
10  1     3
11  0     3
12  1     3
13  0     3
14  0     3
15  1     3
16  1     3
17  0     3
18  1     3
19  0     3
20  1     3
21  0     3
22  1     3
23  0     3
24  0     3
25  1     3
26  1     3
27  0     3
28  1     3
29  0     3
30  1     3
31  0     3
32  1  null
33  0  null
34  0  null
35  0  null
36  0  null
37  0  null
```

**Expected behavior**
I would expect that doing `dask_cudf.from_cudf` would not change the values of the dataframe.

**Environment overview (please complete the following information)**
Installed using conda:
cudf                      0.15.0a200612   py37_g046385d16_1192    rapidsai-nightly
dask-cuda                 0.15.0a200612           py37_10    rapidsai-nightly
dask-cudf                 0.15.0a200612   py37_g823169119_1235    rapidsai-nightly
libcudf                   0.15.0a200612   cuda10.0_g046385d16_1192    rapidsai-nightly
libnvstrings              0.15.0a200604   cuda10.0_gaeda0c0_774    rapidsai-nightly
librmm                    0.15.0a200612   cuda10.0_gfb61dc0_164    rapidsai-nightly
nvstrings                 0.15.0a200604   py37_gaeda0c0_774    rapidsai-nightly
rmm                       0.15.0a200612   py37_gfb61dc0_164    rapidsai-nightly

**Environment details**
./print_env.sh
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 9e730d5e450cfb37d277b0aa57e9aab818ef357b (HEAD -> branch-0.15, upstream/branch-0.15)
     Merge: 8231691 fc99ce5
     Author: Jake Hemstad <jhemstad@nvidia.com>
     Date:   Fri Jun 12 09:52:04 2020 -0500
     
     Merge pull request #5437 from bdice/join-docs-cleanup
     
     [REVIEW] Join docs cleanup
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=16.04
     DISTRIB_CODENAME=xenial
     DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
     NAME="Ubuntu"
     VERSION="16.04.5 LTS (Xenial Xerus)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 16.04.5 LTS"
     VERSION_ID="16.04"
     HOME_URL="http://www.ubuntu.com/"
     SUPPORT_URL="http://help.ubuntu.com/"
     BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
     VERSION_CODENAME=xenial
     UBUNTU_CODENAME=xenial
     Linux william-Lith 4.4.0-140-generic #166-Ubuntu SMP Wed Nov 14 20:09:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Jun 12 16:00:57 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  GeForce GTX 106...  Off  | 00000000:17:00.0 Off |                  N/A |
     | 22%   54C    P2    30W / 120W |     12MiB /  3019MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  GeForce GTX 106...  Off  | 00000000:65:00.0  On |                  N/A |
     | 31%   56C    P2    33W / 120W |   1290MiB /  3016MiB |      7%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    1      1227      G   /usr/lib/xorg/Xorg                           502MiB |
     |    1      1809      G   compiz                                        64MiB |
     |    1      3225      G   ...AAAAAAAAAAAAAAgAAAAAAAAA --shared-files   183MiB |
     |    1      3542      G   ...uest-channel-token=17790048034141171264    78MiB |
     |    1      6217      G   ...ield-trial-handle=5312174812830869938,1   457MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                12
     On-line CPU(s) list:   0-11
     Thread(s) per core:    2
     Core(s) per socket:    6
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
     Stepping:              4
     CPU MHz:               1730.175
     CPU max MHz:           4000.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              7007.89
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              8448K
     NUMA node0 CPU(s):     0-11
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt ssbd ibrs ibpb stibp kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req flush_l1d
     
     ***CMake***
     /usr/local/bin/cmake
     cmake version 3.13.1
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
     Copyright (C) 2015 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2018 NVIDIA Corporation
     Built on Sat_Aug_25_21:08:01_CDT_2018
     Cuda compilation tools, release 10.0, V10.0.130
     
     ***Python***
     /home/william/miniconda3/bin/python
     Python 3.7.4
     
     ***Environment Variables***
     PATH                            : /home/william/miniconda3/bin:/home/william/miniconda3/condabin:/usr/local/cuda/bin:/home/william/bin:/home/william/.local/bin:/opt/maven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/william/miniconda3
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/william/miniconda3/bin/conda
     # packages in environment at /home/william/miniconda3:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     asn1crypto                1.2.0                    py37_0
     ca-certificates           2019.10.16                    0
     certifi                   2019.9.11                py37_0
     cffi                      1.13.0           py37h2e261b9_0
     chardet                   3.0.4                 py37_1003
     conda                     4.7.12                   py37_0
     conda-package-handling    1.6.0            py37h7b6447c_0
     cryptography              2.8              py37h1ba5d50_0
     et-xmlfile                1.0.1                    pypi_0    pypi
     gitdb                     4.0.2                    pypi_0    pypi
     gitpython                 3.1.0                    pypi_0    pypi
     idna                      2.8                      py37_0
     jdcal                     1.4.1                    pypi_0    pypi
     libedit                   3.1.20181209         hc058e9b_0
     libffi                    3.2.1                hd88cf55_4
     libgcc-ng                 9.1.0                hdf63c60_0
     libstdcxx-ng              9.1.0                hdf63c60_0
     ncurses                   6.1                  he6710b0_1
     numpy                     1.18.1                   pypi_0    pypi
     openpyxl                  3.0.3                    pypi_0    pypi
     openssl                   1.1.1d               h7b6447c_3
     pip                       19.3.1                   py37_0
     pycosat                   0.6.3            py37h14c3975_0
     pycparser                 2.19                     py37_0
     pydrill                   0.3.4                    pypi_0    pypi
     pymysql                   0.9.3                    pypi_0    pypi
     pynvml                    8.0.4                    pypi_0    pypi
     pyopenssl                 19.0.0                   py37_0
     pysocks                   1.7.1                    py37_0
     python                    3.7.4                h265db76_1
     readline                  7.0                  h7b6447c_5
     requests                  2.22.0                   py37_0
     ruamel_yaml               0.15.46          py37h14c3975_0
     setuptools                41.4.0                   py37_0
     six                       1.12.0                   py37_0
     smmap                     3.0.1                    pypi_0    pypi
     sqlite                    3.30.0               h7b6447c_0
     tk                        8.6.8                hbc83047_0
     tqdm                      4.36.1                     py_0
     urllib3                   1.24.2                   py37_0
     wheel                     0.33.6                   py37_0
     xz                        5.2.4                h14c3975_4
     yaml                      0.1.7                had09818_2
     zlib                      1.2.11               h7b6447c_3
     
</pre></details>

**Additional context**
Encountered this issue when debugging an issue in BlazingSQL. In BlazingSQL it is common for a user to create a dask_client using LocalCudaCluster and if they create a table from a cudf.DataFrame, then for a distributed query, we would first convert that to a dask_cudf.DataFrame and hence this issue can occur.

**Comment by galipremsagar** [comment]
Closing this as this has been fixed by: https://github.com/rapidsai/cudf/pull/5561
