### ISSUE TITLE
[FEA] Split COPYING_TEST into multiple different tests.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#5464]
COPYING_TEST is getting pretty large.  It contains tests for:

- concatenate
- gather
- split
- slice
- copy_range
- scatter
... and more

It takes a pretty long time to compile.  We should consider breaking this up into a set of separate tests.

**Comment by karthikeyann** [comment]
Are these files not compiled in parallel?

**Comment by nvdbaranec** [comment]
My assumption was that the parallelization was happening across the different tests, not the individual source files within each test.  That might not be the case though.

**Comment by karthikeyann** [comment]
Also, many `.cu` files in `cpp/tests` could be changed to `.cpp`. (should reduce compile time).
Following object files have zero kernels. (excluding _ZN3cub11EmptyKernelIvEEvv)
```
cpp/build/tests/CMakeFiles/COPYING_TEST.dir/copying/get_value_tests.cu.o 0
cpp/build/tests/CMakeFiles/COPYING_TEST.dir/copying/slice_tests.cu.o 0
cpp/build/tests/CMakeFiles/COPYING_TEST.dir/copying/split_tests.cu.o 0
cpp/build/tests/CMakeFiles/COPYING_TEST.dir/copying/utility_tests.cu.o 0
```

To get kernel count per object file:
`find cpp/build/tests/CMakeFiles/*_TEST.dir/ -iname "*.cu.o" -exec bash -c "echo -ne \"{} \"; cuobjdump {} --dump-elf-symbols  | grep STB_GLOBAL | grep -v EmptyKernel | grep STB_GLOBAL -c" \; | sort -n -k2,2`

**Comment by karthikeyann** [comment]
@nvdbaranec `gather_tests.cu` takes most time to compile. Reason is `cudf::detail::gather` tests runs on iterator, raw_pointers of Numeric Types which needs `.cu` compilation.

![image](https://user-images.githubusercontent.com/6488848/84947034-3167e000-b107-11ea-9408-075256168621.png)
