### ISSUE TITLE
[BUG] RuntimeError: CUDA_ERROR_INVALID_PTX while building for a different arch on shared filesystem

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5469]
**Describe the bug**
I have a shared filesystem where I'm performing a clean build on a machine with T4 GPU and the build succeeds and workflows run correctly.
Using the same shared directory doing a clean build on a different machine with V100 GPU I get the below `RuntimeError`.

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.DataFrame({'a':[1, 2, 3]})
df[df['a'] == 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/series.py", line 1349, in __eq__
    return self._binaryop(other, "eq")
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/series.py", line 1005, in _binaryop
    outcol = lhs._column.binary_operator(fn, rhs, reflect=reflect)
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 99, in binary_operator
    lhs=self, rhs=rhs, op=binop, out_dtype=out_dtype, reflect=reflect
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/nfs/pgali/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/core/column/numerical.py", line 442, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 193, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 126, in cudf._lib.binaryop.binaryop_v_s
RuntimeError: CUDA_ERROR_INVALID_PTX
```

**Expected behavior**
Not have the runtime error. Clearing `$HOME/.cudf/0.15.0` fixed the problem. 
As part of the clean build, we should either be clearing the `.cudf` directory or capture architectures and separate `prog_binop` files for separate build architectures.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install:  from source

cc: @kkraus14

**Comment by jinga-lala** [comment]
Any update on how to solve this bug?

**Comment by devavret** [comment]
> Any update on how to solve this bug?

I believe the following should solve this for now.

> Clearing `$HOME/.cudf/0.15.0` fixed the problem.

**Comment by jinga-lala** [comment]
It worked!! 
Thanks a lot!

**Comment by harrism** [comment]
@devavret with your experience on this, how hard would it be to detect that the current cached code is invalid on the present architecture? Is the architecture encoded in the cache? If we can detect this easily, we can purge the cache at runtime and re-JIT.

**Comment by jrhemstad** [comment]
fyi, putting the JIT cache in a network file system is a recipe for bad performance. Specify a local JIT cache path with: `LIBCUDF_KERNEL_CACHE_PATH=/path/to/local/directory ./a.out`.

**Comment by devavret** [comment]
V100's compute capability version is 7.0 and T4's is 7.5. It's possible that by running on T4 first, the kernels in the cache were built for 7.5 and that was unsupported on V100.

Simply by looking at the raw cache file I can see that it has that information in the header
```
.version 6.5
.target sm_70
.address_size 64
```
We could either use that or, just like we store cache per cudf version, store cache in a compute capability named directory.

What's more important is what @jrhemstad said about using cache stored in a network file system.

**Comment by harrism** [comment]
Sure, but this issue is orthogonal to network file systems.

> store cache in a compute capability named directory.

This seems the simplest approach.

**Comment by kkraus14** [comment]
> > store cache in a compute capability named directory.
> 
> This seems the simplest approach.

Do we need to handle different target architectures as well? I.E. would `sm_70` vs `sm_80` have different PTX?

**Comment by harrism** [comment]
Yes, but they would also have different compute capability and so end up in a different cache directory. I guess I don't understand the concern?

**Comment by kkraus14** [comment]
I guess I interpreted `.version` as the CUDA version which was incorrect 😄
