### ISSUE TITLE
[FEA] Rename `cudf::unique_count` to `cudf::distinct_count`

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#5481]
I commented in [Add cudf::unique_count(table_view) #5468](https://github.com/rapidsai/cudf/pull/5468) that `cudf::unique_count` probably is not the right name for this algorithm as `std::unique` has different semantics in **C++.** I would argue that `cudf::distinct_count` is a better name (`distinct` is the most common name for "unique-ness", see below)

This is just a suggestion, but if enough people agree I will submit a PR making the change.

---
**Current suggestions/options:**

1. Rename to `cudf::distinct_count`
2. Rename to `cudf::sort_unique_count`
3. Take `sort` out of `cudf::unique_count`: +1 from @harrism 
4. Leave as is

I personally am OK with any of the first 3

---

![image](https://user-images.githubusercontent.com/36027403/84723843-9b8c5380-af54-11ea-8f43-99c6859af9a0.png)

**Comment by harrism** [comment]
Can you repeat your reasoning for why cudf::unique_count is not a good name *in C++*?   There is no `std::distinct_count`.

**Comment by harrism** [comment]
I guess you mean because std::unique determines uniqueness just by comparing to the elements around each element. In other words, the "unique count" is different depending on whether the input keys are sorted/grouped or not.

We could take a different approach: the first thing `cudf::unique_count` does is to sort. Instead,  we  could assume that the input keys are sorted, and make `cudf::unique_count()` identical in behavior to counting the size of the result of `std::unique()`.  This would have the added benefit of providing an API that allows users to re-use already sorted results. However, it would require changing the Python implementation of `nunique` to first sort the inputs if they are not sorted.

**Comment by codereport** [comment]
@harrism Good point, I should elaborate.

In C++, `std::unique` has the behaviour or removing "adjacent duplicates." This is inherited from the function in BASH called `uniq` ([link](https://linuxhint.com/bash_uniq_command/)).

https://www.godbolt.org/z/2cG8uG
```cpp
std::vector v = { 1, 1, 2, 2, 3, 3, 1, 1, 2, 2, 3, 3 };
auto it = std::unique(v.begin(), v.end());
v.erase(it, v.end());
print(v); // 1 2 3 1 2 3
```

As you can see, `std::unique` doesn't removing all duplicate values, which is what the `cudf::unique_count` does. So there is a mismatch in semantics. The most common name for this "unique-ness" algorithm is `distinct`. You are correct, it doesn't not exist in C++, but other languages have it. The equivalent in C++ is to `std::sort` and then `std::unique`.

**Comment by harrism** [comment]
I think maybe our messages crossed.

**Comment by codereport** [comment]
> I think maybe our messages crossed.

Yep, sorry - didnt see your reply until just now.

> the first thing cudf::unique_count does is to sort.

This is (if you see in the Hoogle Translate table) exactly why Haskell calls their version `sortUniq`. 

An alternative to `cudf::distinct_count` could be `cudf::sorted_unique_count`

**Comment by harrism** [comment]
I am in favor of leaving the name and changing the behavior (remove the sort) for consistency with std C++. That aligns better with libcudf practice than renaming to match a bunch of languages cuDF is not written in. :)

**Comment by codereport** [comment]
I updated the description with a "current suggestions/options" section to keep track of what people prefer. I am fine with any of the first three.

**Comment by jrhemstad** [comment]
I'm weary of anything requiring/implying a sort. The current functionality for `unique_count` could (and probably _should_) be implemented with a hash-based algorithm. 

As such, it's technically possible we want both:
1. `distinct_count` counts the number of distinct elements, no matter their position
2. `unique_count` counts the number of adjacent duplicates.

**Comment by codereport** [comment]
> `unique_count` counts the number of adjacent duplicates.

@jrhemstad I assume you mean: `unique_count` counts the number of elements assuming adjacent duplicates have been removed ?
