### ISSUE TITLE
[FEA] Implement Pandas DataFrame.infer_objects() method

### ISSUE THREAD

**Issue by lherche** [rapidsai/cudf#5485]
**Is your feature request related to a problem? Please describe.**
cuDF does not currently include an implementation of `infer_objects`. This is an issue when porting to cuDF from Pandas as we rely on `infer_objects` in our Pandas workflow.

Working Pandas snippet:
```python
import pandas as pd

data = pd.DataFrame(
    data=([[1, 10, 100, 1000, 10000], [2, 20, 200, 2000, 20000]]), 
    columns=['a', 'b', 'c', 'd', 'e']
)
data.infer_objects()
```

The same workflow fails with cuDF:
```python
import cudf as pd

data = pd.DataFrame(
    data=([[1, 10, 100, 1000, 10000], [2, 20, 200, 2000, 20000]]), 
    columns=['a', 'b', 'c', 'd', 'e']
)
data.infer_objects() # no method
```

```python-traceback
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-8f78ca044bbe> in <module>
      5 data=([[1, 10, 100, 1000, 10000], [2, 20, 200, 2000, 20000]]), columns=['a', 'b', 'c', 'd', 'e']
      6       )
----> 7 data.infer_objects() # no method

~/miniconda3/envs/rapids14/lib/python3.7/site-packages/cudf/core/dataframe.py in __getattr__(self, key)
    430                 return self[key]
    431 
--> 432         raise AttributeError("'DataFrame' object has no attribute %r" % key)
    433 
    434     @annotate("DATAFRAME_GETITEM", color="blue", domain="cudf_python")

AttributeError: 'DataFrame' object has no attribute 'infer_objects'
```

**Describe the solution you'd like**
Add support for `infer_objects` to cuDF.

**Describe alternatives you've considered**
None yet.

**Additional context**
N/A

**Comment by galipremsagar** [comment]
Is the requirement to infer the object of a mixed type? Because from seeing what `pd.DataFrame.infer_objects` accomplishes inferring dtypes of a mixed dtype series. But incase of cudf there is no support for mixed dtypes yet, a series of dtype `object` in cudf contains all `strings`.

**Comment by lherche** [comment]
Yes, this is a requirement to infer the object of a mixed type. I think you are right, this feature request is only relevant if/when support for mixed dtypes is added.

**Comment by vyasr** [comment]
@beckernick @galipremsagar @lherche cudf will probably never support columns of mixed types (aka dtype `object`). I would say our options here are to 1) implement `infer_objects` as a no-op so that existing code doesn't break, 2) implement `infer_objects` as throwing a loud error so that users understand that this functionality does not exist and why, or 3) leave it unimplemented. What do you all think? CC @shwina

**Comment by vyasr** [comment]
I'm going to close this issue as something we will not fix. cuDF will likely never have a meaningful implementation of this function, and any attempt to silently mimic it will probably only lead to hiding deeper issues. If we see multiple users run into this in the future I would be open to option 2 above (implementing `infer_objects` as always throwing an exception), but in lieu of hearing more frequent issues around this missing functionality I think leaving it unimplemented is equally reasonable for now.
