### ISSUE TITLE
[FEA] Add a libcudf `codify` function

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5498]
I wish libcudf had a `codify` function that codifies the values of a column:

```
codify([b, a, c, a, a, b]) == [1, 0, 2, 0, 0, 1]
```

This is essentially a `drop_duplicates` followed by a `lower_bound`. It is already implemented as part of the dictionary column utility [`encode`](https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/src/dictionary/encode.cu).

It would be great if just the "codify" portion of `encode` was exposed as a public API.

Additional context:

The reason the user can't currently just do this using `drop_duplicates` + `lower_bound` is because `drop_duplicates` doesn't guarantee sorted output. That's an internal detail that `encode` currently relies on (and so would `codify`).

**Comment by shwina** [comment]
cc: @jrhemstad

**Comment by jrhemstad** [comment]
@davidwendt what do you think about breaking out the logic used in `dictionary::encode` into a new function that could just be called by both `dictionary::encode` and `codify`?

**Comment by shwina** [comment]
Does the following sound reasonable?

1. Move this logic to a `cudf::detail::codify` function
2. Add `cudf::codify` in `cudf/transform.hpp`

**Comment by jrhemstad** [comment]
> Does the following sound reasonable?
> 
> 1. Move this logic to a `cudf::detail::codify` function
> 2. Add `cudf::codify` in `cudf/transform.hpp`

Sounds fine to me.

**Comment by harrism** [comment]
Why the name `codify` rather than `encode`?  

codify (verb): arrange (laws or rules) into a systematic code.
encode (verb): convert into a coded form.

I think the latter is more appropriate and idiomatic here. The former connotes legal terminology.

**Comment by shwina** [comment]
No strong feelings here. I can rename to `encode`

**Comment by shwina** [comment]
Closed by #5572
