### ISSUE TITLE
[BUG] Extended runtime for GroupBy.apply()

### ISSUE THREAD

**Issue by kkranen** [rapidsai/cudf#5499]
**Describe the bug**
Using the .apply() method on grouped dataframes where the groups number in the millions results extremely extensive if not infinite runtime. The function passed to apply is seemingly irrelevant, the issue has been tested with the identity function (def out(x): return x) as well as nlargest and other user defined functions.

**Steps/Code to reproduce bug**
```python-traceback
import cudf
toy_dataset = cudf.DataFrame([[i,100-i % 100] for i in range(1000000)]+[[i,110-i % 100] for i in range(1000000)]+[[i,130-i % 100] for i in range(1000000)],columns=['doc_id','cat_id'])
def toy_func_sort_cat_id(x):
    return x.nlargest(2,'cat_id')
def toy_func_sort_doc_id(x):
    return x.nlargest(2,'doc_id')
# Following cell runs in < 3 seconds
a = toy_dataset.groupby('cat_id').apply(toy_func_sort_doc_id)
# Following cell doesn't complete in >1 hour
b = toy_dataset.groupby('doc_id').apply(toy_func_sort_cat_id)

```

**Expected behavior**
Improved performance of Groupby apply.

**Environment overview (please complete the following information)**
Rapids Docker Container on NGC (dgx1v.32g.1.norm)

**Comment by shwina** [comment]
Thanks for reporting. This is currently a known limitation of `.apply()`: the implementation simply iterates over the groups and concatenates the results together in the end.

`apply()` is likely to be useful only for a small number of large groups. It is going to be extremely slow for a large number of small groups.

Unfortunately, this is likely to remain a limitation for some time.

Are you able to provide the actual operation you wish to perform on the groups?

**Comment by kkranen** [comment]
The operation being executed is essentially a WAR since cudf can't support lists yet. It encodes list elements as a set of columns in the new dataframe (elem1,elem2....elemN for arbitrary fixed N). I was able to overcome this issue utilizing apply_grouped.

**Comment by shwina** [comment]
@kkranen - just FYI, list type are currently being worked on in cuDF and some operations on lists will be supported after this release. If there are specific operations you'd like to see, we'd love to hear about them in a GitHub issue!

**Comment by kkraus14** [comment]
Closing as this is answered.
