### ISSUE TITLE
[BUG] Leaking libcudacxx dependency

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#5507]
**Is your feature request related to a problem? Please describe.**

libcudf internally relies on libcudacxx for the timestamp and duration functionality. 

https://github.com/rapidsai/cudf/blob/31d746605fb4a3fd4b24a5732aed16ce7944adf7/thirdparty/CMakeLists.txt#L66-L73

It is a build time dependency, but should not be a runtime dependency, i.e., libcudacxx should _not_ be a dependency of other libraries linking against libcudf (just as Thrust or CUB should not be an external dependency). For example, Cython should not need access to libcudacxx headers when building it's binding library linked against `libcudf.so`. 

The fact that Cython _does_ need access to these headers indicates that we are leaking this internal, third party dependency in our public headers:
https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/setup.py#L50-L54

**Describe the solution you'd like**

Find and remove all leaks of `libcudacxx` in public libcudf headers such that Cython (and anyone else linking against libcudf) need not know about libcudacxx

At least one of the leaks is in the `scalar.hpp` header:

https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/include/cudf/scalar/scalar.hpp#L20

`traits.hpp` and `type_dispatcher.hpp` should not need to be exposed here. I'm guessing `scalar.hpp` needs to be split into a header and a source file to hide this dependency.

**Comment by harrism** [comment]
I consider this a bug, not a feature request.

**Comment by davidwendt** [comment]
I also noticed this when trying to create an example program using the libcudf API.

Just including the `cudf/column/column_factories.hpp` header required adding a `-I` path for `libcudacxx` and `/usr/local/cuda/include` to the compile statement.

```
# g++ -std=c++14 -I$CONDA_PREFIX/include cudf_incl.cpp -o cudf_incl
In file included from /conda/envs/rapids/include/rmm/thrust_rmm_allocator.h:27:0,
                 from /conda/envs/rapids/include/cudf/column/column_factories.hpp:18,
                 from cudf_incl.cpp:2:
/conda/envs/rapids/include/rmm/mr/device/thrust_allocator_adaptor.hpp:19:54: fatal error: thrust/detail/type_traits/pointer_traits.h: No such file or directory
compilation terminated.

# g++ -std=c++14 -I$CONDA_PREFIX/include -I/usr/local/cuda/include cudf_incl.cpp -o cudf_incl
In file included from /conda/envs/rapids/include/cudf/utilities/type_dispatcher.hpp:23:0,
                 from /conda/envs/rapids/include/cudf/utilities/traits.hpp:22,
                 from /conda/envs/rapids/include/cudf/column/column_factories.hpp:21,
                 from cudf_incl.cpp:2:
/conda/envs/rapids/include/cudf/wrappers/durations.hpp:24:23: fatal error: simt/chrono: No such file or directory
compilation terminated.

```
The source file for the above is just this:
```
#include <cudf/column/column_factories.hpp>
int main( int argc, const char** argv )
{
   return 0;
}
```

**Comment by harrism** [comment]
@jrhemstad I started looking at `scalar.hpp` and I don't think this can be solved by adding an implementation .cpp file, as it includes template class definitions. However, I believe since those are in the `detail` namespace, the use of those headers can be moved to a detail header that is only included from internal files.

**Comment by jrhemstad** [comment]
This was more of an issue when we were using our own private clone of `freestanding`. Now that we use official libcu++ I don't see this as a big deal. Furthermore, as https://github.com/NVIDIA/libcudacxx/pull/105 progresses, its likely that libcu++ will become an explicit, public dependency. Closing.
