### ISSUE TITLE
[FEA] Cython: Column.release() and Table.release()

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5519]
Provide `Column.release()` and `Table.release()` `cdef` methods which return `unique_ptr[column]` and `unique_ptr[table], thus releasing ownership of the underlying data.

These functions would be the counterparts to `Column.from_unique_ptr` and `Table.from_unique_ptr` respectively.

**Comment by beckernick** [comment]
@shwina , can this be closed given PR discussion culminating in https://github.com/rapidsai/cudf/pull/5616#issuecomment-780179387 ?

**Comment by shwina** [comment]
Yup
