### ISSUE TITLE
[FEA] Windowing support with gzip deflate in read_csv

### ISSUE THREAD

**Issue by kenhester** [rapidsai/cudf#552]
**Is your feature request related to a problem? Please describe.**
I am using read_csv with large files.  decompressing the file will not fit into GPU memory.  I would like to not split to disk, but use windowing support with read_csv to only load the rows need for processing.   

**Describe the solution you'd like**

Read a window / partition/ portion of the gzip between the skip_rows and nrows arguments.  This is necessary when the file decompressed is larger then the GPU memory.  The file will be read into GPU memory in windows.  Expecting that the rows before skip_rows and after nrows should not occupy GPU memory.

```
import pandas as pd
pd.read_csv("sample.gz",compression='gzip')
```
```
import cudf
cudf.read_csv("sample.gz",compression='gzip')
```
```
import cudf
import pandas as pd
df1 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=0, nrows=400000)
df2 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=400001, nrows=400000)
df3 = cudf.read_csv("sample.gz",compression='gzip', skip_rows=800001, nrows=400000)
df = pd.concat([df1,df2,df3])

```

**Describe alternatives you've considered**
Alternative:
Decompress to disk
Split the file into smaller pieces

**Additional context**

**Comment by kkraus14** [comment]
Fixed by #633.
