### ISSUE TITLE
[FEA] Remove accents from strings

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#5527]
**Is your feature request related to a problem? Please describe.**
For some NLP operation is necessary to remove accents from letters, for example, transform é, è, â, î, ô to e, e, a, i, o.
In pandas, you can use `str.normalize` to do the work

**Describe the solution you'd like**
A pandas like function `str.normalize` to remove accents from strings

**Describe alternatives you've considered**
It would be possible to use regular expressions to remove accents

**Comment by davidwendt** [comment]
There is an internal normalize function being added as part of #5511.
Once this PR is finished I can look at reusing it for implementing this feature.

**Comment by davidwendt** [comment]
The normalizer that is built into the `nvtext::subword_tokenize` function has the following behavior. Using mostly the [unicode category](https://unicodebook.readthedocs.io/unicode.html#categories) attribute for each character, the normalizer will

- add padding around punctuation (unicode category starts with "P") as well as certain ASCII symbols like "^" and "$"
- add padding around the [CJK Unicode block](https://en.wikipedia.org/wiki/CJK_Unified_Ideographs_(Unicode_block)) characters
- change whitespace (e.g. `"\t", "\n", "\r"`) to just space `" "`
- remove control characters (unicode categories "Cc" and "Cf")

The padding process here adds a single space before and after the character.

The normalizer can also optionally (with a parameter) lower-case and remove accents from characters. If specified, lower-casing must also remove the accents -- the accents cannot be removed from upper-case characters without lower-casing it and lower-casing cannot be performed without also removing accents. However, if the accented character is already lower-case, then only the accent is removed.

@argenisleon Let me know if this behavior would work for you for this. My plan was to expose this normalizer as its own API in case it is useful outside of the tokenizer.

**Comment by argenisleon** [comment]
Thanks @davidwendt, It sounds perfect for my use case.

**Comment by argenisleon** [comment]
Hi @davidwendt,

When working with a series full of nulls values I get:
```
import cudf
cdf = cudf.DataFrame({"A":[None, None,None]})
cdf["A"].astype(str).str.normalize_characters()
```
```
   3667         """
   3668         return self._return_or_inplace(
-> 3669             cpp_normalize_characters(self._column, do_lower), **kwargs
   3670         )
   3671 

cudf/_lib/nvtext/normalize.pyx in cudf._lib.nvtext.normalize.normalize_characters()

RuntimeError: cuDF failure at: /opt/conda/envs/rapids/conda-bld/libcudf_1596061003383/work/cpp/include/cudf/detail/utilities/cuda.cuh:64: num_blocks must be > 0
```

Is this expected?

**Comment by davidwendt** [comment]
Argh. No, this is not expected. This is a bug.
