### ISSUE TITLE
[DOC] upgrade cudf package

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#5530]
Rapids.ai provides very good information on how to install `cudf`.
I cannot find any information on that site, and in documentation section, on _how to upgrade, already installed, `cudf`_ package.
As of now I was always removing whole cudf conda env, creating new one and installing there.
I would like to automate upgrade process now, thus my question here.
Thank you.

**Comment by jangorecki** [comment]
.

**Comment by GregoryKimball** [comment]
We recommend using the [RAPIDS docker containers](https://hub.docker.com/r/rapidsai/rapidsai/), or starting in a [fresh conda virtual environment](https://github.com/rapidsai/cudf#conda).
