### ISSUE TITLE
[DISCUSS] Minimize the use of `**kwargs`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5532]
There are several places within `cudf` where we utilize the following pattern:

```python
def foo(arg_1, **kwargs):
    bar = kwargs.get("arg_2", None)
    ...
```

Wherever possible, we should replace this with just:

```python
def foo(arg_1, arg_2=None):
    ...
```

Not only is the latter shorter, but it also makes it explicit what arguments `foo` accepts, without having the reader look at the implementation to figure that out. See [here](http://ivory.idyll.org/blog/on-kwargs.html) for a bit more detailed description of the problem.

Here are some suggestions:

* For public-facing APIs which need to have a `**kwargs` (for example, https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/cudf/core/series.py#L1648) we should clearly document what arguments can be passed for `kwargs`. In many places we already document this nicely, but it's worth auditing :)

* For internal functions (for example, https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/cudf/core/column/column.py#L829) we should avoid `**kwargs` whenever possible and use explicit keyword arguments instead (here, `ordered=False`).

* There are also some places where we have `**kwargs` but don't use it at all (for example https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/cudf/core/series.py#L2321). Let's just delete those.

**Comment by shwina** [comment]
See https://github.com/rapidsai/cudf/issues/6536#issuecomment-709531544 for an example of why `**kwargs` is problematic.

**Comment by vyasr** [comment]
@shwina is this still an issue? I see it in some places, but there is also a question of pandas compliance since there are some APIs where we have `**kwargs` just because pandas does, even if we don't use them (e.g. all the Series reductions).

**Comment by vyasr** [comment]
Discussed offline, we are good to close
