### ISSUE TITLE
[FEA] cuDF doesn't have the apply() method

### ISSUE THREAD

**Issue by vivanov10** [rapidsai/cudf#5540]
**Is your feature request related to a problem? Please describe.**

cuDF doesn't have the `apply()` method. However, it implements the `apply_rows` method which is somewhat more difficult to use than the pandas apply method

**Describe the solution you'd like**

An implementation of `apply()` as in pandas

**Describe alternatives you've considered**

We currently convert everything to a list, and make the conversion via standard python `[f(x) for x in l]`. 

**Additional context**

Pandas example:
```python
import pandas as pd
df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
def square(x):
   return x * x
df.apply(square)
```

cuDF example:
```python
import cudf as pd

df = pd.DataFrame({'A': [1, 2], 'B': [10, 20]})
def square(x):
   return x * x
df.apply(square) # no method

```

Traceback:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-0ca78a3bad5f> in <module>
      6 def square(x):
      7    return x * x
----> 8 df.apply(square) # no method

~/miniconda3/envs/rapids14/lib/python3.7/site-packages/cudf/core/dataframe.py in __getattr__(self, key)
    430                 return self[key]
    431 
--> 432         raise AttributeError("'DataFrame' object has no attribute %r" % key)
    433 
    434     @annotate("DATAFRAME_GETITEM", color="blue", domain="cudf_python")

AttributeError: 'DataFrame' object has no attribute 'apply'
```

**Comment by shwina** [comment]
See also https://github.com/rapidsai/cudf/issues/1501

**Comment by GregoryKimball** [comment]
Closing in favor of #1501. We support row-wise UDF apply (axis=1), but we don't support column-wise UDF apply (axis=0) yet. Also here is a more recent location for the [Guide to UDFs](https://docs.rapids.ai/api/cudf/stable/user_guide/guide-to-udfs.html).
