### ISSUE TITLE
[FEA] cuDF `Series` objects do not have  `map` function 

### ISSUE THREAD

**Issue by vivanov10** [rapidsai/cudf#5541]
**Is your feature request related to a problem? Please describe.**

cuDF `DataFrame` and `Series` objects do not have `map` function 

**Describe the solution you'd like**

Implement a `map()` function as in pandas

**Describe alternatives you've considered**

Currently we convert the `Series` to a `list`, and use standard python `[h.get(x, None) for x in l]` as an alternative

**Additional context**

pandas example:
```python
import pandas as pd
import numpy as np
s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
s.map({'cat': 'kitten', 'dog': 'puppy'})
```

cudf example
```python
import cudf as pd
import numpy as np
s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
s.map({'cat': 'kitten', 'dog': 'puppy'}) # no attribute

```

Traceback:
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-2e1f8db0943c> in <module>
      3 import numpy as np
      4 s = pd.Series(['cat', 'dog', np.nan, 'rabbit'])
----> 5 s.map({'cat': 'kitten', 'dog': 'puppy'}) # no attribute

AttributeError: 'Series' object has no attribute 'map'
```

**Comment by galipremsagar** [comment]
I suppose there is no `DataFrame.map` api for pandas. Hence correcting the title.
