### ISSUE TITLE
[FEA] `pytorch` `DataLoader` doesn't support cuDF arrays

### ISSUE THREAD

**Issue by vivanov10** [rapidsai/cudf#5547]
**Is your feature request related to a problem? Please describe.**
When iterating pytorch data loader that uses the cudf arrays, I am getting the following errors for the default collate function in pytorch

**Describe the solution you'd like**
Contact `pytorch` maintainers to implement support for cuDF in their

**Describe alternatives you've considered**
Convert to `numpy array` first. `Pytorch` supports it.

**Additional context**

pandas sample
```python
import pandas as pd
from torch.utils.data import Dataset, DataLoader

df = pd.DataFrame({'a': [0,1,2,3,4], 'b': [5,6,7,8,9]})

class DatasetNew(Dataset):
   def __init__(self, data):
       self.data = df

   def __len__(self):
       return len(self.data)

   def __getitem__(self, index):
       data = self.data.loc[index, :].values
       return data


d = DatasetNew(df)
dataloader = DataLoader(d)
for x in dataloader:
   print(x)

```

cuDF sample
```python
import cudf as pd
from torch.utils.data import Dataset, DataLoader

df = pd.DataFrame({'a': [0,1,2,3,4]})

d = DatasetNew(df)
dataloader = DataLoader(d)
for x in dataloader:
   print(x)
# TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'cupy.core.core.ndarray'>
```

Traceback:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-a971bf667ed2> in <module>
     19 d = DatasetNew(df)
     20 dataloader = DataLoader(d)
---> 21 for x in dataloader:
     22    print(x)
     23 # TypeError: default_collate: batch must contain tensors, numpy arrays, numbers, dicts or lists; found <class 'cupy.core.core.ndarray'>

~/miniconda3/envs/rapids14/lib/python3.7/site-packages/torch/utils/data/dataloader.py in __next__(self)
    613         if self.num_workers == 0:  # same-process loading
    614             indices = next(self.sample_iter)  # may raise StopIteration
--> 615             batch = self.collate_fn([self.dataset[i] for i in indices])
    616             if self.pin_memory:
    617                 batch = pin_memory_batch(batch)

~/miniconda3/envs/rapids14/lib/python3.7/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
    232         return [default_collate(samples) for samples in transposed]
    233 
--> 234     raise TypeError((error_msg.format(type(batch[0]))))
    235 
    236 

TypeError: batch must contain tensors, numbers, dicts or lists; found <class 'cupy.core.core.ndarray'>```

**Comment by alecgunny** [comment]
You'll probably want to use dlpack with cuDF's `to_dlpack` and torch's `from_dlpack` to map from cupy arrays to torch tensors. It might be worth taking a look at [NVTabular's](https://github.com/nvidia/nvtabular) [torch dataloader](https://github.com/NVIDIA/NVTabular/blob/master/nvtabular/torch_dataloader.py), which wraps the generic torch DataLoader with this functionality.

**Comment by kkraus14** [comment]
+1 to using dlpack as the way to get into PyTorch zero copy.

Given this isn't a cuDF issue and is out of our control, I'm going to close this issue, but I would suggest you raise an issue on the PyTorch repo if you'd like them to natively support cuDF objects.

**Comment by jperez999** [comment]
yeah so to make cudf pytorch friendly you want to move from a cudf.dataframe to dlpack using the `to_dlpack` api(https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.to_dlpack). Then you want to take that product and turn it into a tensor using `torch.utils.dlpack.from_dlpack` api (https://pytorch.org/docs/stable/dlpack.html). Hope this helps.

**Comment by vivanov10** [comment]
Thanks for the explanation :)
