### ISSUE TITLE
UX Frequent Failure: TRY NOW IN COLAB often fails due to K80 GPU runtime allocation

### ISSUE THREAD

**Issue by discdiver** [rapidsai/cudf#5558]
Thank you for Rapids!

The [Getting Started page](https://rapids.ai/start.html) has a TRY NOW IN COLAB link that is arguably the primary call to action. Trying in Colab sounds great. But after clicking the link and running Colab cells and spending time installing things, I see that the code won't run if Colab gives you a K80 GPU. After several restarts, I still get a K80 each time. K80s appear to be very common GPU in Colab, unless you are using the paid Colab Pro. This is a frustrating user experience for folks who want to try Rapids.

**Comment by galipremsagar** [comment]
Instead of using restart runtime, could you try using **Factory reset runtime**? Because that seems to have worked for me on switching to a different GPU type.

![Screen Shot 2020-06-23 at 9 13 29 AM](https://user-images.githubusercontent.com/11664259/85414760-24e1ee00-b532-11ea-8769-90821867f321.png)

**Comment by discdiver** [comment]
Thanks. It gives me a k80 ever time.

**Comment by discdiver** [comment]
Update, it gave me a p100 now! 🎉 
However, this is quite a suboptimal demo if it takes a bunch of time and you're ad Colab's mercy to give you a nicer GPU.

**Comment by kkraus14** [comment]
Thanks for letting us know @discdiver. Conversations are happening in the background to see if the Colab experience can be improved, but I unfortunately can't share any details at this time. Given your issue is resolved I'm going to close this issue.
