### ISSUE TITLE
[BUG] Rename "master" branch.

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#5560]
Decades from now, will history students wonder why an entire industry decided to rename a core part of its infrastructure, or will they wonder why it was named that way to begin with?

Let's rename the "master" branch.

**Comment by cwharris** [comment]
What does it take to get this done?

@mike-wendt, what implications does this have for CI, and is there anything you need from library devs / anything we can do to help?

**Comment by cwharris** [comment]
There are several places across all repos where "master" is mentioned with regards to either the master branch, an owning data structure, owning process, etc., including, but not limited to:
- `README.md`
- `CONTRIBUTING.md`
- `PULL_REQUEST_TEMPLATE.md`
- `Dockerfile`
- `Doxyfile`
- python config files (`conf.py`, `versioneer.py`, `_version.py`, etc)
- shell scripts
- Jupyter notebooks
- CMakeLists.txt

**Comment by cwharris** [comment]
thrust/thrust#1203 is updating as well.

Let's update any third party "master" branch references to point at the corresponding commit id. This should prepare us for up stream renames.

**Comment by cwharris** [comment]
Should we set up a mirror branch (`main`) so we can start updating code iteratively, rather than use one massive PR which has to coordinate with the branch rename?

**Comment by datametrician** [comment]
@cwharris there's a plan to get this done systematically that I've been discussing with @mike-wendt and ops, and will work with others to roll out. for now, closing this issue.

**Comment by cwharris** [comment]
@datametrician Any way to help?

**Comment by datametrician** [comment]
All repos, when we have a plan everyone can help.
No running with scissors :)
