### ISSUE TITLE
parquet_column_view should use type_dispatcher

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#5565]
**Describe the bug**

`parquet_column_view` has an explicit switch over type_ids:
https://github.com/rapidsai/cudf/blob/a537380726e9a3e6b7a0f0944ae573053ec5e93e/cpp/src/io/parquet/writer_impl.cu#L118

This kind of code is extremely problematic and is precisely why the `type_dispatcher` was developed. 

This should be replaced with a type dispatched function object.

**Comment by devavret** [comment]
This exact thought crossed my mind when I was working on it, so I tried. But the code for each type is so different that it needed a separate template specialization for each type. There's no code reusability between any two types. The primary goal this achieves is to provide a translation for `cud::type_id` to `parquet::Type`, which needs to be defined case by case somewhere a. la. `type_to_id`

As a negative, this reduced the readability of the existing code.

**Comment by jrhemstad** [comment]
> This exact thought crossed my mind when I was working on it, so I tried. But the code for each type is so different that it needed a separate template specialization for each type. There's no code reusability between any two types. The primary goal this achieves is to provide a translation for `cud::type_id` to `parquet::Type`, which needs to be defined case by case somewhere a. la. `type_to_id`
> 
> As a negative, this reduced the readability of the existing code.

Using the type_dispatcher ensures that any new types added are automatically picked up instead of easy to forget need to manually update the switch statement.

**Comment by devavret** [comment]
> Using the type_dispatcher ensures that any new types added are automatically picked up instead of easy to forget need to manually update the switch statement.

What good would that be if parquet needs special handling for every type anyway?

**Comment by jrhemstad** [comment]
> > Using the type_dispatcher ensures that any new types added are automatically picked up instead of easy to forget need to manually update the switch statement.
> 
> What good would that be if parquet needs special handling for every type anyway?

Because the `type_dispatcher` is the single source of truth for mapping runtime types to compile time types. There should not be exceptions or deviations.

**Comment by cwharris** [comment]
The design of `type_dispatcher` encompasses a few things, some of which are not accounted for in the example code. For one, the `type_dispatcher` pattern encourages a pure-function approach, so setting instance-specific state is discouraged, or it at least encourages a single assignment of a custom type. In that way, `type_dispatcher`'s design has a cascade effect. Using it incorrectly or in a clunky way reveals "anti-patterns" in the calling code.

Here, for example, we are assigning three separate highly coupled values, and this would require, at the very least, a `tie` at the call site to accomplish using `type_dispatcher`, but given that we would have already created a tuple to return _from_ type dispatcher, it's likely we would have noticed the correlation and created a custom type, or simply used the tuple as the source of truth, requiring us to change each value at once, reducing the likelihood of erroneous state changes down the line.

https://github.com/rapidsai/cudf/blob/a537380726e9a3e6b7a0f0944ae573053ec5e93e/cpp/src/io/parquet/writer_impl.cu#L118-L123

Although less of an issue, `type_dispatcher` also eliminates the possibility of omitting a `break` and falling through to the next switch, which could save some debugging time.

**Comment by cwharris** [comment]
That being said, this code works as is and should probably just remain the way it is until we factor out the member variables. There's not much to be gained now that it's implemented and tested, but the `type_dispatcher` pattern should still be used for new code, avoiding type-based switches. It's verbose, but encourages better code upstream.

**Comment by cwharris** [comment]
One more thought on the subject...

> The primary goal this achieves is to provide a translation for `cud::type_id` to `parquet::Type`, which needs to be defined case by case somewhere a. la. `type_to_id`

This is actually an argument in favor of `type_dispatcher`, as it imposes a compile-time restraint on handling all cases, even if one of those cases is a catch all al a `default` that calls `CUDF_FAIL`. If there truly is a mapping per type, there won't `CUDF_FAIL` case, and any time a new type is added, it will need to be accounted for explicitly, reducing the likelihood of future bugs.

**Comment by kaatish** [comment]
Fixed by #7461
