### ISSUE TITLE
[FEA] cudf io kafka source

### ISSUE THREAD

**Issue by jdye64** [rapidsai/cudf#5575]
Now that Kafka is a valid source in libcudf a python interface needs to be added so that python users can create dataframes based on messages consumed from Kafka. The implementation should include the following methods at a minimum

- metadata: print the underlying kafka consumer metadata, useful for debugging
- current_configs: return a dictionary of the underlying kafka consumer configurations
- read_gdf: Given kafka configurations read messages from kafka and create a cudf dataframe
- committed: retrieve the current committed offsets for the underlying connection
- get_watermark_offsets: retrieve the connections watermark offsets
- commit: manually commit the offsets for the connection
- unsubscribe: remove connection from the list of topic/partition consumers but don't close the tcp connection
- close: close the socket connection and clean up

**Comment by kkraus14** [comment]
> read_gdf: Given kafka configurations read messages from kafka and create a cudf dataframe

This shouldn't be a method of the Kafka source. From my perspective this new KafkaSource class is something that should be able to be passed to any IO reader / writer function. So you'd call a normal `cudf.read_json` or `cudf.read_avro` to specify the expected data type, and pass an instance of `KafkaSource` as to where to read that data from.

**Comment by jdye64** [comment]
Ok I like that better. Are you ok with me introducing that extra parameter to the other io objects then? Was it sure if that would be welcomed or not given their signature would no longer look exactly like pandas

**Comment by kkraus14** [comment]
This wouldn't need a new parameter. Instead of passing a string for a filepath or a buffer object, you pass an instance of `KafkaSource` and we handle it under the hood transparently to the end user.

In the future, we can then also hook this up to something like fsspec where a user could provide a URI string and we construct the `KafkaSource` object based on that URI string.

**Comment by jdye64** [comment]
Makes sense
