### ISSUE TITLE
Can I turn on the “per thread stream”  about libcudf ? [QST]

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#5596]
I found that cudf default bulid option about multi-strema is "default stream", so I rebuild the libcudf like this way to support multi stream about operation on gpu :
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/rapids -DCMAKE_CXX11_ABI=ON -DPER_THREAD_DEFAULT_STREAM=ON
and I have 3 questions about stream:
1. when I use "per-thread-stream" , I found that read_parquet performance is better , speed up is up to 1.2X average. my question is Can I just simply modify the option "default stream" to "per-thread-stream" to support one cpu thread to one stream ? and is this way sure to work and improve performance ?
2. when I use "per-thread-stream", I found that the performance of "read_parquet + groupby_aggregate" is not as expected .the performace is getting worse compared to read_parquet only . and at the same time, there is a 0.7% default stream ,I don't know why .the nsight profile is :
![image](https://user-images.githubusercontent.com/33319780/85940971-5869b180-b952-11ea-8db1-d7379ce42eec.png)
3. when I use "per-thread-stream", I found that the overlap about kernel is not bad, but the overlap of HostToDevice and the DeviceToHost is not as expected ,like this :
![image](https://user-images.githubusercontent.com/33319780/85941018-ba2a1b80-b952-11ea-82b0-30da45ada504.png)
please give me some advice

**Comment by rui911013** [comment]
this is qdrep files about per-thread-stream and legacy-default-stream.
and my cpu thread num is 12, gpu thread num is 3, and I use semaphore to control the cpu thread to require device 。

[nsight-profile.zip](https://github.com/rapidsai/cudf/files/4841839/nsight-profile.zip)

**Comment by jrhemstad** [comment]
PTDS is largely untested and should be considered largely experimental.

You will find answers to a few of your questions about per-thread default stream here: https://developer.nvidia.com/blog/gpu-pro-tip-cuda-7-streams-simplify-concurrency/

**Comment by harrism** [comment]
PTDS support is in progress. It should work successfully for cuDF now in 0.15 (current development branch), as long as you use the RMM default memory resource, cnmem_memory_resource, or pool_memory_resource.

**Comment by kkraus14** [comment]
Closing as this was implemented in #4995
