### ISSUE TITLE
[BUG] at ai.rapids.cudf.ColumnVector.binaryOpVS(Native Method): Could not allocate native memory

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/cudf#5597]
When I run TPC-DS query 3 in spark local model, the following error occured
----------------------------------------------
20/06/28 15:36:48 [Executor task launch worker for task 313] ERROR Executor: Exception in task 0.0 in stage 4.0 (TID 313)
java.lang.OutOfMemoryError: Could not allocate native memory
        at ai.rapids.cudf.ColumnVector.binaryOpVS(Native Method)
        at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1037)
        at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1024)
        at ai.rapids.spark.CudfBinaryExpression.doColumnar(GpuExpressions.scala:234)
        at ai.rapids.spark.CudfBinaryExpression.doColumnar$(GpuExpressions.scala:231)
        at org.apache.spark.sql.rapids.GpuEqualTo.doColumnar(predicates.scala:260)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval(GpuExpressions.scala:185)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:166)
        at ai.rapids.spark.CudfBinaryOperator.columnarEval(GpuExpressions.scala:238)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval(GpuExpressions.scala:171)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:166)
        at ai.rapids.spark.CudfBinaryOperator.columnarEval(GpuExpressions.scala:238)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval(GpuExpressions.scala:170)
        at ai.rapids.spark.GpuBinaryExpression.columnarEval$(GpuExpressions.scala:166)
        at ai.rapids.spark.CudfBinaryOperator.columnarEval(GpuExpressions.scala:238)
        at ai.rapids.spark.GpuFilter$.apply(basicPhysicalOperators.scala:108)
        at ai.rapids.spark.GpuFilterExec.$anonfun$doExecuteColumnar$2(basicPhysicalOperators.scala:173)

by the way, 
1. the java test code show a similar error (when i build the jar in cuDF-src-path/java)
"target/surefire-reports/ai.rapids.cudf.UnaryOpTest-output.txt"
Jun 28, 2020 7:17:49 PM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNING: TestEngine with ID 'junit-jupiter' failed to execute tests
java.lang.OutOfMemoryError: Could not allocate native memory
        at ai.rapids.cudf.ColumnVector.binaryOpVS(Native Method)
        at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1037)
        at ai.rapids.cudf.ColumnVector.binaryOp(ColumnVector.java:1024)
        at ai.rapids.cudf.ColumnVector.log10(ColumnVector.java:956)
        at ai.rapids.cudf.UnaryOpTest.testLog10(UnaryOpTest.java:268)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2. the cuDF-src/cpp test show the following error：

89% tests passed, 7 tests failed out of 66
Total Test time (real) = 138.05 sec
The following tests FAILED:
	  5 - GROUPBY_TEST (Failed)
	 21 - BINARY_TEST (Child aborted)     # a memory error in the free()@glibc
	 22 - TRANSFORM_TEST (Failed)
	 23 - JITCACHE_TEST (SEGFAULT)
	 24 - JITCACHE_MULTIPROC_TEST (SEGFAULT)
	 40 - ROLLING_TEST (SEGFAULT)
	 41 - GROUPED_ROLLING_TEST (SEGFAULT)

----------------------------------------------
**Environment details**
the cuDF jar was build by myself (i am using branch-0.14 from github without any code changed)
build was on CentOS-7.4, not using docker env

print_env.sh  
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit 6244cfceddcd3c2d8ce84336c49c75f7b9a64540 (HEAD, origin/branch-0.14)
     Author: Ray Douglass <3107146+raydouglass@users.noreply.github.com>
     Date:   Tue Jun 2 11:52:15 2020 -0400

     Update CHANGELOG.md
     **git submodules***
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
     b165e1fb11eeea64ccf95053e40f2424312599cc thirdparty/cub (v1.7.1)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
     50680b29d1f9bc41905acf006a1a94a40e0728e1 thirdparty/jitify (remotes/origin/cudf_0.14)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
     cdcda484d0c7db114ea29c3b33429de5756ecfd8 thirdparty/libcudacxx (0.8.1-99-gcdcda48)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
     a97a7380c76346c22bb67b93695bed19592afad2 thirdparty/libcudacxx/libcxx (heads/rapidsai-interop)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

     ***OS Information***
     CentOS Linux release 7.4.1708 (Core)
     NAME="CentOS Linux"
     VERSION="7 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="7"
     PRETTY_NAME="CentOS Linux 7 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:7"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"

     CENTOS_MANTISBT_PROJECT="CentOS-7"
     CENTOS_MANTISBT_PROJECT_VERSION="7"
     REDHAT_SUPPORT_PRODUCT="centos"
     REDHAT_SUPPORT_PRODUCT_VERSION="7"

     CentOS Linux release 7.4.1708 (Core)
     CentOS Linux release 7.4.1708 (Core)
     Linux lxsyslab-spark-gpu-worker1.lxsyslab.baidu.com 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 GNU/Linux

     ***GPU Information***
     Sun Jun 28 19:30:38 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
     | N/A   37C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     Address sizes:       46 bits physical, 48 bits virtual
     CPU(s):              96
     On-line CPU(s) list: 0-95
     Thread(s) per core:  2
     Core(s) per socket:  24
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6271 CPU @ 2.60GHz
     Stepping:            6
     Frequency boost:     enabled
     CPU MHz:             1000.000
     CPU max MHz:         2601.0000
     CPU min MHz:         1000.0000
     BogoMIPS:            5200.00
     Virtualization:      VT-x
     L1d cache:           1.5 MiB
     L1i cache:           1.5 MiB
     L2 cache:            48 MiB
     L3 cache:            66 MiB
     NUMA node0 CPU(s):   0-23,48-71
     NUMA node1 CPU(s):   24-47,72-95
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_pt tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts

     ***CMake***
     /opt/toolchain/bin/cmake
     cmake version 3.17.2

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /opt/toolchain/bin/g++
     g++ (GCC) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89

     ***Python***
     /usr/bin/python
     Python 2.7.5

     ***Environment Variables***
     PATH                            : /opt/toolchain/bin:/root/.BCloud/bin:/usr/local/cuda/bin:/root/disk0/software/hadoop/bin:/root/disk0/software/scala-2.12.11/bin:/root/disk0/software/spark-3.0.1-SNAPSHOT-bin-hadoop3/bin:/root/disk0/software/jdk1.8.0_251/bin:/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin:/home/opt/bin:/usr/local/cuda-10.2/bin:/root/bin
     LD_LIBRARY_PATH                 : /opt/rapids/legacy/lib:/opt/rapids/legacy/lib64:/usr/local/cuda/lib64:/usr/local/cuda/lib:/usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2//lib64:/usr/local/cuda-10.2//lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /opt/toolchain/bin/pip
     Package         Version
     --------------- -------
     cycler          0.10.0
     joblib          0.15.1
     kiwisolver      1.2.0
     matplotlib      3.2.2
     numpy           1.19.0
     pandas          1.0.5
     pip             20.1.1
     pyarrow         0.17.1
     pyparsing       2.4.7
     python-dateutil 2.8.1
     pytz            2020.1
     scikit-learn    0.23.1
     scipy           1.5.0
     setuptools      41.2.0
     six             1.15.0
     threadpoolctl   2.1.0

</pre></details>

i build the cuDF using gcc-7.5
[root@lxsyslab-spark-gpu-worker1 cudf.branch-0.14.legacy]# which gcc
/opt/toolchain/bin/gcc

i use the following command to fetch the code:
git clone https://github.com/rapidsai/cudf.git cudf.branch-0.14
cd cudf.branch-0.14 || exit 1
git checkout origin/branch-0.14 || exit 1
git submodule update --init --remote --recursive

**Comment by jlowe** [comment]
I think the key is this:
> the cuDF-src/cpp test show the following error

If the libcudf unit tests aren't passing then we're very likely to see problems in the cudf Java unit tests and Java applications because it's all built on libcudf.  So before digging into anything related to Java, we need to get to the root cause of the cpp unit test failures.  The `memory error in the free()@glibc` error message is particularly concerning.

A few things to check:
- How did you build libcudf?  Did you follow the instructions in [CONTRIBUTING.md](https://github.com/rapidsai/cudf/blob/branch-0.15/CONTRIBUTING.md) and use a conda environment or something else?
- Are there any other processes using the GPU at the same time?  You can use the `nvidia-smi` command to see what processes are using the GPU, how much memory they are consuming, and how much is free.
- For the cpp unit tests that are failing, you can run them manually from the binaries built in the `gtests` directory under your cpp build directory.  It would be interesting to run those and see what additional output they produce to provide more insight into the failures.

**Comment by JustPlay** [comment]
When the cuDF CPP&JAVA code was build with CMAKE_CXX11_ABI=ON，the "ai.rapids.cudf.ColumnVector.binaryOpVS(Native Method)" goes wrong;

but, when use CMAKE_CXX11_ABI=OFF, everything just works well

**Comment by jlowe** [comment]
It sounds like you're building outside of a conda environment and not using the OS toolchain.

I suspect this is caused by trying to use a toolchain that supports the C++11 ABI on an OS that didn't ship with that same toolchain and ABI support and the ABIs are getting mixed somewhere.  Did you also compile your own libboost_filesystem.so or was that installed from prebuilt binaries?

When running outside of a conda environment and trying to run on older OS's like CentOS 7, I recommend building everything libcudf depends upon (e.g.: librmm, libboost_filesystem, etc.) with CMAKE_CXX_ABI=OFF and using [devtoolset](https://www.softwarecollections.org/en/scls/rhscl/devtoolset-8/) as the toolchain so your binaries don't require you to provide the toolchain's runtime wherever you try to run the cudf jar.  This is what we do when building the official cudf artifact published to Maven Central.

**Comment by JustPlay** [comment]
@jlowe 

I build everything cudf depends upon (gcc, glibc, arrow, boost, ...), but libcudf relays on libboost_system-mt.so.1.53, and  the boost i build only has libboost_system.so， no -mt prefix，event i set the threading=multi， so libcudf still use the system's default libboost_system-mt.so.1.53

the error occurs on binaryOsVS, does this relay boost_filesystem?

**Comment by jlowe** [comment]
> I build everything cudf depends upon (gcc, glibc,

I highly recommend using devtoolset as I mentioned previously rather than a toolchain you build separately.  Binaries from devtoolset will mesh nicely with the runtime on your base OS, and you won't need to worry about accidentally mixing runtimes as you do when using a toolchain you built.  You also won't have to build as many things to get it to work, just what is missing from your base OS.

> the error occurs on binaryOsVS, does this rely on boost_filesystem?

Yes, because [binary operations use JIT](https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/src/binaryop/binaryop.cpp#L138) to handle all the possible combinations of input types and output type.  The JIT subsystem uses a cache to amortize the cost of compiling custom kernels, and [that cache leverages libboost_filesystem](https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/src/jit/cache.cpp#L65).
