### ISSUE TITLE
[FEA] Update parquet writer metadata_file_path type to data_sink

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#5606]
**Is your feature request related to a problem? Please describe.**
Currently all writer use the `data_sink` type to write data to arbitrary data sinks, like remote file buffers etc. The `metadata_file_path` for `write_parquet` is expected to be a string, which only supports writing to local files.

**Describe the solution you'd like**
Updating `metadata_out_file_path` from `std::string` to type `data_sink` and handling metadata writing to a data_sink, to support metadata being written to file buffers that need not be local to that machine.

**Comment by OlivierNV** [comment]
IIRC, the parquet writer does not write to `metadata_out_file_path` -> this string is being inserted in the rowgroup metadata as the `parquet::RowGroup.file_path` string and the metadata is returned to the caller as a binary blob (this is mainly intended for multi-file datasets, and the string is never used to actually create a file)

**Comment by kkraus14** [comment]
@ayushdg can this be closed based on Olivier's answer above?

**Comment by ayushdg** [comment]
Thanks for the response @OlivierNV. Looks like that is indeed the case. 

Yes @kkraus14 should be good to close 😄
