### ISSUE TITLE
[FEA] cudf groupby aggregate into list

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#5620]
Is your feature request related to a problem? Please describe.

Groupby is a widely used method at the preprocessing stages of ML and DL models. For recommender systems, one usage is to create a grouped data frame with list entries. cuDF currently does not support that functionality.

Describe the solution you'd like
I'd like to be able to get row entries as lists or nested lists  after groupby operation.

Additional context
Pandas support this operation (see example below).
```
df = pd.DataFrame({'doc_id': [1, 1, 2, 2, 3, 3], 'category_id': [1, 2, 3, 3, 5, 6], 'confidence_level': [0.92, 0.251, 0.352, 0.359, 0.978, 0.988], 'timestamp':['02-01-2020', '03-01-2020', '01-01-2020', '03-01-2020', '04-01-2020', '02-01-2020']})

#Ensuring that interactions are chronologically ordered
df.sort_values(['timestamp'], inplace=True)
df

  doc_id  category_id  confidence_level   timestamp
2       2            3             0.352  01-01-2020
0       1            1             0.920  02-01-2020
5       3            6             0.988  02-01-2020
1       1            2             0.251  03-01-2020
3       2            3             0.359  03-01-2020
4       3            5             0.978  04-01-2020

df_grouped = df.groupby('doc_id', as_index=False).agg({'category_id': list, 'confidence_level': list})

df_grouped
  doc_id category_id confidence_level
0       1      [1, 2]    [0.92, 0.251]
1       2      [3, 3]   [0.352, 0.359]
2       3      [6, 5]   [0.988, 0.978]
```

**Comment by kkraus14** [comment]
cc @shwina for thoughts regarding Python API here

**Comment by jrhemstad** [comment]
This is pretty simple from a C++ perspective. It's just a groupby w/o aggregation, and we're only returning 1 key per group and the associated values as a list.

**Comment by shwina** [comment]
@jrhemstad would it be possible to expose this as a groupby aggregation in libcudf? Something like `aggregation::COLLECT` for instance? More likely than not Python users are going to want to perform this operation along with other aggregations.

**Comment by jrhemstad** [comment]
> @jrhemstad would it be possible to expose this as a groupby aggregation in libcudf? Something like `aggregation::COLLECT` for instance? More likely than not Python users are going to want to perform this operation along with other aggregations.

It only makes sense as an aggregation if it has meaning in other contexts where `aggregation` is used, i.e., a reduction or a rolling operation. I don't think that applies.

**Comment by beckernick** [comment]
In my experience, this is a common operation in Spark workflows (`collect_list`). See https://github.com/rapidsai/cudf/issues/2974 as this may be a duplicate

**Comment by devavret** [comment]
@shwina, we already have `groupby::get_groups()`. You can take the output and using offsets and values, convert it to a list column.

**Comment by shwina** [comment]
Thanks, @devavret, that should work. One benefit of libcudf supporting a `COLLECT` aggregation is that it could be performed at the same time as other aggregations. If we implemented this as a Python-only agg, then `a.groupby("b").agg(["collect", "sum"])` would resolve to two API calls instead of just one. Don't know if a libcudf solution would be any better/more efficient though.

**Comment by jrhemstad** [comment]
> If we implemented this as a Python-only agg, then `a.groupby("b").agg(["collect", "sum"])` would resolve to two API calls instead of just one. Don't know if a libcudf solution would be any better/more efficient though.

I don't think there's much opportunity for libcudf to do it any better. The `groupby` object already memoizes any of the work done between the aggregation and `get_groups`, so you're already benefiting from that.

**Comment by kkraus14** [comment]
Will libcudf not use a hash groupby for the `sum` aggregation and then have to recompute a sort groupby for the `get_groups` operation?

**Comment by harrism** [comment]
Good point @kkraus14. @devavret should answer, but I think if you do the get_groups first it will do a sort, and then memoize the groups, which it could then use in the sum.

But it seems to me if you could specify "collect" and "sum" together, then it would give the libcudf groupby the information it needs to always take the optimal path, whereas if they are separate then performance might depend on the order, which is not really desireable...

**Comment by devavret** [comment]
> Will libcudf not use a hash groupby for the `sum` aggregation and then have to recompute a sort groupby for the `get_groups` operation?

It will. If `COLLECT` and `SUM` are requested together, it will do a sort groupby only. `COLLECT` requires a sort groupby. The cost of doing a sort is large enough that if both are requested, hash groupby appears "free". I'm not justifying not making `COLLECT`, just giving a perspective to help prioritise.

**Comment by shwina** [comment]
From an offline conversation with @jrhemstad and @kkraus14:

The `get_groups()` method works for doing a `COLLECT` aggregation purely within Python. However, if the user requests more than one aggregation, e.g., both `COLLECT` and `SUM`, things become difficult.

Even if libcudf uses a sort groupby for computing the `SUM`, there is no guarantee that the ordering of that result will be the same as that of `get_groups()`. The only way to ensure the same ordering for two aggregations is to perform them both in the same `aggregate()` call. 

It seems like a libcudf `COLLECT` agg is the best way forward. I was halfway through implementing a Python version of `COLLECT`, but unless there are any objections, I'll switch gears to move it to libcudf.
