### ISSUE TITLE
[FEA]  join two cudf data frames with list columns

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#5621]
**Is your feature request related to a problem? Please describe.**

Join method is used often at the preprocessing stages of ML and DL models. For recommender systems, one usage is to join two data frames with lists and/or nested lists columns. cuDF currently does not support that functionality.

**Describe the solution you'd like**

I'd like to be able to join two cudf data frames with list and/or nested list columns. 

**Additional context**
Pandas support this operation (see example below). 

```
import pandas as pd

nested = [[['1', '2', '3'], ['1','2']], [['2', '3', '1']], [['3', '4']], [['1']]]
doc_id= [1, 2, 3, 4]
df = pd.DataFrame({'doc_id': doc_id, 'col1': nested})

nested = [['1', '2', '3'], ['2', '3', '2'], ['3', '4', '5'], ['1'], ['2']]
ad_id= [1, 2, 3, 4, 5]
df2 = pd.DataFrame({'ad_id': ad_id, 'col2': nested})

df_merged = df.merge(df2, how='left', left_on='doc_id', right_on='ad_id')
df_merged
  doc_id                 col1  ad_id       col2
0       1  [[1, 2, 3], [1, 2]]      1  [1, 2, 3]
1       2          [[2, 3, 1]]      2  [2, 3, 2]
2       3             [[3, 4]]      3  [3, 4, 5]
3       4                [[1]]      4        [1]
```

**Comment by jrhemstad** [comment]
To be clear, this isn't asking to join _on_ list columns, but rather list columns come along for the ride in the dataframe. 

I think this should largely "just work" once https://github.com/rapidsai/cudf/pull/5073 is done.

**Comment by rnyak** [comment]
@jrhemstad yes, agreed.

**Comment by rnyak** [comment]
> To be clear, this isn't asking to join _on_ list columns, but rather list columns come along for the ride in the dataframe.
> 
> I think this should largely "just work" once #5073 is done.

@jrhemstad I see that #5073 was merged. Does that mean we can have python api for cuDF list type column soon? Thanks.

**Comment by shwina** [comment]
@rnyak I'm working on bindings for gather/slice for list types in Python. It's currently waiting on a fix for https://github.com/rapidsai/cudf/issues/5717.
