### ISSUE TITLE
[QST] Generate JavaCPP API

### ISSUE THREAD

**Issue by archenroot** [rapidsai/cudf#563]
There are already some works on integration within Spark (which I really like). Is this code open-source or closed? In either way i was thinking to try generate Java API with help of JavaCPP - 
https://github.com/bytedeco/javacpp
You can look what JavaCPP already supports:
https://github.com/bytedeco/javacpp-presets

I have already ported Gunrock and it works quite well(we are just cleaning some packaging details), this will be probably more difficult task, but ... if you are interested in me give it a try, can you please identify main API files?

I am really excited by this contribution and love the rapids demo :+1:

**Comment by archenroot** [comment]
The question is if I should wait for some stable API (I understand you are under heavy dev at moment, correct me if I am wrong), or you think the structures are stable enough?

**Comment by kkraus14** [comment]
Closed by #1995
