### ISSUE TITLE
[QST] Run Dask client process on a machine without a GPU

### ISSUE THREAD

**Issue by vinhdiesal** [rapidsai/cudf#5631]
I currently has a Dask SSH cluster  where the scheduler is an IMAC (no nvidia GPU) and the workers are two machines with nvidia GPUS each. 
I would connect a DASK SSH cluster as follows:
```
from dask.distributed import Client, SSHCluster
cluster = SSHCluster(
        ["localhost", "192.168.1.119", "192.168.1.191"],
        connect_options={"known_hosts": None,"username": "vinhdiesal"},
        worker_options={"nthreads": 100},
        scheduler_options={"port": 0, "dashboard_address": ":8797"},
        worker_module= 'dask_cuda.dask_cuda_worker'
)
client = Client(cluster)
client
from dask.distributed import Client, SSHCluster
cluster = SSHCluster(
        ["localhost", "192.168.1.119", "192.168.1.191"],
        connect_options={"known_hosts": None,"username": "vinhdiesal"},
        worker_options={"nthreads": 100},
        scheduler_options={"port": 0, "dashboard_address": ":8797"},
        worker_module= 'dask_cuda.dask_cuda_worker'
)
client = Client(cluster)
client
```
Then I try to import cudf, but it gets the following error: 
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-4-426582e71336> in <module>
      2 import numpy as np
      3 import pandas as pd
----> 4 import cudf
      5 import dask_cudf

~/anaconda3/envs/dask-rapids/lib/python3.7/site-packages/cudf/__init__.py in <module>
      3 from cudf.utils.gpu_utils import validate_setup  # isort:skip
      4 
----> 5 validate_setup(check_dask=False)
      6 
      7 import cupy

~/anaconda3/envs/dask-rapids/lib/python3.7/site-packages/cudf/utils/gpu_utils.py in validate_setup(check_dask)
      8         return
      9 
---> 10     from cudf._cuda.gpu import (
     11         getDeviceCount,
     12         driverGetVersion,

ImportError: libcuda.so.1: cannot open shared object file: No such file or directory
```
When I import cudf on my worker machines its fine. 
Is my setup valid? Does downloading a cuda package on a non-nvidia machine make sense?

**Comment by kkraus14** [comment]
> Is my setup valid? Does downloading a cuda package on a non-nvidia machine make sense?

Currently the way that dask works is that the client machine and the scheduler both end up needing to run a small amount of code similar to the workers in order to understand the expected output metadata. In the case of cuDF this means that they need to be able to run code that requires a GPU as well as the driver and cuda toolkit.

**Comment by vinhdiesal** [comment]
Unfortunately my setup will work for Dask and dask-ml/dask-xgboost, but won't work with rapids. In order for it to work with the RAPIDS package, I changed my setup so instead of the scheduler being the imac, the schedule is the same machine as one of the workers with nvidia GPUS and it works. 
I can close. Thanks.
