### ISSUE TITLE
[BUG]Cannot get an array view of a StringColumn ​

### ISSUE THREAD

**Issue by liuandy-good** [rapidsai/cudf#5646]
my csv data: 
0,stu0,1,36.65,2020-07-05
1,stu1,0,75.14,2020-07-05
2,stu2,1,35.13,2020-07-05
3,stu3,0,15.2,2020-07-05
4,stu4,1,24.4,2020-07-05
5,stu5,0,30.77,2020-07-05
6,stu6,1,96.44,2020-07-05
7,stu7,0,39.09,2020-07-05
8,stu8,1,52.35,2020-07-05
9,stu9,0,61.79,2020-07-05
my code: 
import pandas
import cudf
import numpy as np
import time
pdf=pandas.read_csv("stu_3.csv",header=None,names=["id","sex","score",'sc_date'],dtype={'id':'S','sex':'i','score':'f','sc_date':'S'})
#pdf.head(10)
cdf = cudf.from_pandas(pdf)
def kernal (in1,out):
        out=id.count('tu')
        out=score+2
start_time=time.time()
cdf=cdf.apply_rows(kernal,
                   incols=['id'],
                   outcols=dict(out='S'),
                   kwargs=dict()
                   )
end_time=time.time()
print("CUDF find string:",end_time - start_time)

and get an error: 
/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/column/column.py in data_array_view(self)
     86         """
     87         if self.dtype == "object":
---> 88             raise ValueError("Cannot get an array view of a StringColumn")
     89 
     90         if is_categorical_dtype(self.dtype):

ValueError: Cannot get an array view of a StringColumn

any one know what's wrong with that? Appreciate for your help!

**Comment by shwina** [comment]
Hi @liuandy-good  - thanks for reporting. The `apply_rows` function does not currently support DataFrames with string columns, unfortunately.

Could you possibly provide the equivalent Pandas code that achieves what you are looking to do? Perhaps we can suggest an approach that will work well with cuDF.

**Comment by liuandy-good** [comment]
Hi @shwina I am trying to test the string type data performance on GPU VS CPU. here the code in Pandas. 

pdf=pandas.read_csv("stu_3.csv",header=None,names=["id","sex","score",'sc_date'])
pdf['str_index']=pdf.id.apply(lambda x:x.count('stu'))

please kindly guide how to do the testing. 
Thanks

**Comment by beckernick** [comment]
Hi @liuandy-good , thanks for providing an example. In both pandas and cuDF, the recommended way to do that example would be to use `pdf.id.str.count("stu")`. 

We also provide some string operation benchmarks in the RAPIDS [release slide deck](https://docs.rapids.ai/overview/latest.pdf). Slide 31 may be of interest to you (as of 2020-07-07).

**Comment by liuandy-good** [comment]
Thank you @beckernick  it works.
