### ISSUE TITLE
[BUG] Repeat is missing from 0.14 stable API Doc.

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/cudf#5655]
**Describe the bug**
The `repeat` function of a cudf data series is missing from the API doc.

**Steps/Code to reproduce bug**
Here is the function:
```
>>> import cudf
>>> cudf.__version__
'0.14.0'
>>> df = cudf.DataFrame()
>>> df['value'] = [1,2,3]
>>> df['repeat'] = [2,1,0]
>>> df['value'].repeat(df['repeat'])
0    1
0    1
1    2
Name: value, dtype: int64
```

**Comment by shwina** [comment]
@galipremsagar do you think using the sphinx `:inherited-members:` option as we discussed may resolve this?

**Comment by shwina** [comment]
Ah I noticed you already opened https://github.com/rapidsai/cudf/issues/5653 for this
