### ISSUE TITLE
[FEA] cudf/cuIO support for read/write parquet files with nested list columns

### ISSUE THREAD

**Issue by rnyak** [rapidsai/cudf#5665]
**Is your feature request related to a problem? Please describe.**

We would like to be able to write cudf dataframes with list type columns to parquet files, and read from the parquet files accordingly. cudf does not have list type column support yet. But once this functionality comes along, the support for parquet read/write would be very useful also.

**Additional context**
We can create a pandas df with list/nested list columns, where pandas thread these columns as object dtype, but the elements in the lists are in their original type (ex: int, float).
```
import pandas as pd
#create a pandas df with nested list columns
nested = [['1', '2', '3'], ['1','2'], ['2', '3', '1'], ['1']]
confidence=[[0.7, 00.5], [0.2, 0.3], [0.92], [0.15]]
doc_id= [1, 2, 3, 4]
df = pd.DataFrame({'doc_id': doc_id, 'col1': nested, 'confidence': confidence})
print(df)

  doc_id       col1 confidence
0       1  [1, 2, 3]  [0.7, 0.5]
1       2     [1, 2]  [0.2, 0.3]
2       3  [2, 3, 1]      [0.92]
3       4        [1]      [0.15]

#save the df as parquet file
df.to_parquet('df.parquet')
#load the df
df_new = pd.read_parquet('df.parquet')
print(df_new)
  doc_id       col1 confidence
0       1  [1, 2, 3]  [0.7, 0.5]
1       2     [1, 2]  [0.2, 0.3]
2       3  [2, 3, 1]      [0.92]
3       4        [1]      [0.15]
```

**Comment by rnyak** [comment]
@harrism @kkraus14 Is there any update on this FEA? thank you.

**Comment by kkraus14** [comment]
> @harrism @kkraus14 Is there any update on this FEA? thank you.

Not yet, Parquet reading is being worked on currently and we're still working on the Python plumbing.

**Comment by harrism** [comment]
I believe the reader PR is #5723.

**Comment by devavret** [comment]
The writer PR is #6075

**Comment by benfred** [comment]
I believe this is done / can be closed
