### ISSUE TITLE
[BUG] Parquet writer produces results that cannot be read by the CPU

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#5677]
**Describe the bug**
This is based off of https://github.com/NVIDIA/spark-rapids/issues/347

I was able to reproduce the error on my own using the latest cudf-0.15 code. I don't know exactly how the format of the data being produced is wrong though, just that it is.

I have created a minimal parquet file on the CPU that can be used to more easily reproduce the error, and the bad GPU file along with it.  Because the data is licensed I cannot post it here directly, but I am happy to share it with someone directly.

**Steps/Code to reproduce bug**
Read the input file in parquet using the GPU.  Write it out again as parquet using the GPU.

Test the format of the file.

```
 java -jar parquet-tools-1.10.1.jar dump GPU.parquet
```

It will exit with an error like 

```
org.apache.parquet.io.ParquetDecodingException: Can't read value in column [non_interest_bearing_upb] optional double non_interest_bearing_upb at value 11809 out of 13000, 11809 out of 13000 in currentPage. repetition level: 0, definition level: 1
```
Note: the file can still be opened using cudf.

**Expected behavior**
The data can be read by the CPU as well as the GPU

**Environment overview (please complete the following information)**
I did this on a V100, but the original issue was filed on a TITAN X (Pascal)

**Comment by kkraus14** [comment]
@devavret @vuule could one of you look into this?

**Comment by vuule** [comment]
I'll look into this starting today or tomorrow.

**Comment by vuule** [comment]
Observations so far from experimenting with the repro:
- The issue also reproes when only the column in question is read/written;
- The issue also reproes without snappy compression;
- Without compression, file written by cudf is a much smaller (650bytes to 1.9KB) than the pandas version;
- The file written by cudf can be opened with cudf reader, and the resultint dataframe has the right data;

This all points to a compatibility issue between cudf and pandas RLE encoding. cudf produces a valid file, but pandas is unable to process the RLE encoded data correctly.
