### ISSUE TITLE
[FEA] Support byte ranges in read_csv (and other formats)

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#568]
To enable batched reading of large text files (csv, line-delimited-json, ...) it is often useful to be able to read a chunk of data while respecting some delimiter.  For example some process might be tasked with reading from 4GB to 5GB in the file starting and stopping at a `\n` character.

This would be particularly helpful when parallelizing around `cudf.read_csv` with `dask_cudf.read_csv`, but would presumably also be helpful for other functions in the future.  

The dask.bytes module does this here:

https://github.com/dask/dask/blob/master/dask/bytes/utils.py#L149-L238

However it returns Python `bytes` objects so might not be appropriate for `cudf`.  It might be good to take inspiration from though.

**Comment by thomcom** [comment]
This is fairly high priority in my opinion. I asked some RAPIDS io people if it is on their radar.

**Comment by mrocklin** [comment]
>  is this supposed to only work for file input? I don't see a huge use case for the buffer input.

I agree.  The eventual use caes for buffer input that I have in mind is when we get data from cloud storage like S3 or GCS.  In that case though we can easily find the delimiters on the host side (where the data will be anyway in this case) and so the current functionality should be fine I think.
