### ISSUE TITLE
[FEA] Replace nvstrdesc with string_view

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#5682]
**Is your feature request related to a problem? Please describe.**
The struct `nvstrdesc_s` used in cuIO is similar to `string_view`. They both contain a pointer to the char array and the size of the string. (string_view contains only 2 additional members). `string_view` has the necessary methods to perform operations expected of `nvstrdesc_s`
https://github.com/rapidsai/cudf/blob/ec4b7b6b3e888aa62b204cbae0d958529bdff9f9/cpp/src/io/parquet/parquet_gpu.h#L39-L42

**Describe the solution you'd like**
For all purposes, `nvstrdesc_s` can be replaced with `string_view`. 

Doing this will be a multi-step process.
- [x]  In parquet writer, reduce usage of `stats_column_desc` members in favor of `column_device_view`
- [x]  In orc writer, reduce usage of `stats_column_desc` members in favor of `column_device_view`
- [x] Refactor statistics calculation to remove `nvstrdesc_s` and use `column_device_view` instead of members of stats_column_desc that replicate the same information
- [ ] Kick out `stringdata_to_nvstrdesc()` in all the writers.

**Comment by davidwendt** [comment]
I would not recommend using `cudf::strings::detail::create_string_vector_from_column` for this. The only function that uses this right now is [cudf::strings::detail::scatter](https://github.com/rapidsai/cudf/blob/ec4b7b6b3e888aa62b204cbae0d958529bdff9f9/cpp/include/cudf/strings/detail/scatter.cuh#L68) and appears to be the last remnant of code that tries to impose _nullness_ into a `string_view` instance:
https://github.com/rapidsai/cudf/blob/ec4b7b6b3e888aa62b204cbae0d958529bdff9f9/cpp/src/strings/utilities.cu#L65-L68
This works but is kind of hacky -- using `string_view` instance merely as `pair` container of two values (pointer and length).

This implementation should have been probably removed/fixed as part of #4548 but got missed.

I would recommend using the following API (which seems to be lacking documentation):
https://github.com/rapidsai/cudf/blob/ec4b7b6b3e888aa62b204cbae0d958529bdff9f9/cpp/include/cudf/strings/detail/strings_column_factories.cuh#L34-L39

This takes iterators over types like `pair<pointer,integer>` and created just for this kind of thing.

**Comment by devavret** [comment]
@davidwendt the API you suggested seems to create a strings column from a pair of pointer an integer. What `stringdata_to_nvstrdesc()` does is the opposite. It creates a struct that is a pair of pointer and size values. Are you suggesting that we should use a pair instead of `nvstrdesc_s`?

**Comment by davidwendt** [comment]
Yes, my mistake. If the intention is to encode _nullness_ into the data vector (instead of in a separate bitmask), then I would recommend using a `pair` or struct like `nvstrdesc_s` instead of `string_view`.

The API I (wrongly) suggested converts a vector of pairs into a strings column.

**Comment by devavret** [comment]
I don't believe `nvstrdesc_s` exists to encode nullness. I believe it is an artifact of the cuIO's handling of the old libcudf nvstring.

At the very least, we could consolidate the string comparison codes located here: https://github.com/rapidsai/cudf/blob/ce826c57c8cafb7d78f33873ca8c0c030fa42087/cpp/include/cudf/strings/string_view.inl#L263-L277 and here: https://github.com/rapidsai/cudf/blob/ce826c57c8cafb7d78f33873ca8c0c030fa42087/cpp/src/io/utilities/block_utils.cuh#L196-L228
