### ISSUE TITLE
[FEA] Wildcard support for Parquet reader

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5683]
Based on this [comment](https://github.com/rapidsai/cudf/pull/5536#pullrequestreview-436885074).

Parquet reader now takes a list of input files. However, each input file has to be specified in the call. 

With this feature, the caller could pass a string with a wildcard (e.g. `path/*.parquet`) to select multiple files more easily.

**Comment by ayushdg** [comment]
Happy to take this on for 0.17 unless someone is working on it already 😄 .

cc: @kkraus14 @vuule

**Comment by vuule** [comment]
AFAIK no one is working on this. It's all yours :)
