### ISSUE TITLE
[FEA] Create gbenchmarks for cudf strings APIs

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#5698]
There are currently no benchmarks for any of the strings-specific libcudf APIs.

Propose creating the following gbenchmarks:

- [x] [to_lower](https://docs.rapids.ai/api/libcudf/nightly/group__strings__case.html#gaec51c2123138c05b0ceadb1e85af3487)
- [x] [concatenate](https://docs.rapids.ai/api/libcudf/nightly/group__strings__combine.html#gad7f5f7e88679a40024f67ca985a7fd9e)
- [x] [contains_re](https://docs.rapids.ai/api/libcudf/nightly/group__strings__contains.html#ga52059d8e8aecad5d615e24e4418c4b24)
- [x] [findall_re](https://docs.rapids.ai/api/libcudf/nightly/group__strings__contains.html#gae4cb1343a4849dea337e477adbb93894)
- [x] Type [converters](https://docs.rapids.ai/api/libcudf/nightly/group__strings__convert.html)
     - [x] datetime
     - [x] integers
     - [x] floats
     - [x] fixed-point
     - [x] urls
- [x] [extract](https://docs.rapids.ai/api/libcudf/nightly/group__strings__substring.html#ga64fc8a21d364a17fe5fef21390b067a7)
- [x] [slice_strings](https://docs.rapids.ai/api/libcudf/nightly/group__strings__substring.html#gaa689719250048ea788b5db1549c8265f)
- [x] [find](https://docs.rapids.ai/api/libcudf/nightly/group__strings__find.html#gab6e310599d76a7f11b7468095c553d25)
- [x] [find_multiple](https://docs.rapids.ai/api/libcudf/nightly/group__strings__find.html#gafe50a5948aff2953c86e581008405ac0)
- [x] [translate](https://docs.rapids.ai/api/libcudf/nightly/group__strings__modify.html#ga5c08de60b12b1a821e31d4f39139441f)
- [x] [replace](https://docs.rapids.ai/api/libcudf/nightly/group__strings__replace.html) -- currently there are 7 of these
- [x] [split](https://docs.rapids.ai/api/libcudf/nightly/group__strings__split.html#gab6d5490bdb150d48a0689a9f3555d2ba)
- [x] [split_record](https://docs.rapids.ai/api/libcudf/nightly/group__strings__split.html#gab6d5490bdb150d48a0689a9f3555d2ba) 
- [x] [filter](https://docs.rapids.ai/api/libcudf/nightly/group__strings__modify.html#ga027c628eb76a8e504d31ff0745a58257)

This is not all the APIs but covers most if not all the key kernels that would show the performance impact of code changes here.

**Comment by karthikeyann** [comment]
For converters, benchmarks for `from_durations`, `to_durations` is already present 
[cpp/benchmarks/string/convert_durations_benchmark.cpp](https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/benchmarks/string/convert_durations_benchmark.cpp)

**Comment by davidwendt** [comment]
This is now complete.
