### ISSUE TITLE
[QST] Generate the changelog at release time?

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#570]
There seems to be some friction around maintaining the changelog.

1.  We're spending time generating scripts to check it as part of CI
2.  New devs seem confused about what to write where
3.  It's a constant source of merge conflicts

We ran into this in the Dask projects as well (where the influx of new/drive-by devs was higher and so the issues above more acute) and ended up abandoning the process during code development.  Instead the release manager (in this case, me) just went through at release time and added entries manually.  This was annoying, but only takes around 20m, and saved several times that much headache on everyone else.

This was made easy because we did two things:

1.  Squash on merge for most PRs, which captures the PR title as the commit
2.  Modify the PR header title when we merge, or else modify the commit message when we merge to ease the process when we release

FWIW I've personally be *very* happy with this choice.  It has been way less time consuming for me than policing people was before, and it generates zero frustration for devs who were previously asked to do the bookkeeping.

**Comment by mrocklin** [comment]
> Concerns here are some new feature PRs we have are quite heavy (20+ commits), and when it comes to blame down the road we loose potentially valuable information for new files and large changes. Granted there are other PRs like bug fixes that are 1-2 commits with and additional one for CHANGELOG updates so maybe there needs to be a standard treating each type differently.

Yeah, for what it's worth I used to argue this same point.  Now I squash and merge everything and haven't looked back.  I do this even for 100+ commit PRs.  Often most of those commits aren't super-informative anyway.  FWIW I believe that most PyData projects, and also most Apache projects do the same.  Pandas and Spark specifically both squash-and-merge, even for large PRs.  Often this results in commits that are more meaningful, and it means that all points in history pass all tests.

I agree that without a squash-and-merge approach doing what I'm suggesting would be quite challenging.

**Comment by thomcom** [comment]
FWIW I'm in favor of automated builds and automating any aspect of the build that can be automated (automatically, KWIM?). I haven't used squash and merge yet, professionally, but it sounds pretty good - especially when we could auto-increment minor version numbers and automatically update the CHANGELOG as well.

**Comment by mike-wendt** [comment]
@thomcom all of what you proposed is either implemented or on the roadmap. The only thing that is manual is the CHANGELOG as the team does not have enough code/PR hygiene to support it.

For the moment we will continue with the process we have in place for at least this release and possibly the next. This way we can collect actual feedback from the broader team based on their experiences before making any changes.

**Comment by datametrician** [comment]
I'm going to close this issue.  Let's continue as we're doing and revisit this in the future. There are several reasons why our current processes are in place, and I think we need to continue with them for a while before tweaking them.
