### ISSUE TITLE
Improve parameters of cuIO kernels (Avro)

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5710]
Many cuIO kernels and their callers have a large number of parameters. These functions can the improved by grouping their parameters into meaningful abstractions.

Example: 
https://github.com/rapidsai/cudf/blob/38921ccd71bdf89609d90e0899a1bfb037879cd6/cpp/src/io/csv/csv_gpu.h#L150-L162

Edit: parameter order is also inconsistent/incorrect - in some places out parameters are places before inputs.

**Comment by vuule** [comment]
The changes should include a type that is a non-owning view of a device buffer - something like `device_span`. 
There are many places where a pointer to a buffer and the buffer element count are passed as separate parameters.

**Comment by cwharris** [comment]
Introducing `device_span` in #6233 which could prove useful here.

**Comment by vuule** [comment]
Keeping the issue open for the existing Avro PR.
For the other components - we are improving the parameters and adding useful abstractions (like span, 2dspan, column views) as we make other refactorings in the code. It does not seem like we should make changes focused on the parameters now that the refactoring is well on it's way.
