### ISSUE TITLE
[QST] Is there dask.compute() equivalent function for dask_cudf dataframes?

### ISSUE THREAD

**Issue by think-high** [rapidsai/cudf#5711]
**What is your question?**
I am wondering if there is a function to which I can pass a dictionary with values as `dask_cudf` dataframes and it can compute and return those. I believe you can do that for `dask` dataframes when passed it to `dask.compute()`.  

Do let me know if there is some understanding flaw here. 

Thanks

**Comment by Salonijain27** [comment]
`dask_cudf` has a `.compute()` function.

```
import dask_cudf
import cudf
​
df = cudf.datasets.randomdata(10)
ddf = dask_cudf.from_cudf(df, 2)
print(" ddf : \n", ddf.compute())
print(" ddf.sum() : \n", ddf.sum().compute())
```

**Comment by think-high** [comment]
Thanks, I was thinking something like `dask.compute()` instead of something like `dask.DataFrame.compute()` so that I can pass on multiple-dataframes to be computed through that method. But I figured out that actually `dask.compute()` can be used with `dask_cudf`dataframes as well so I am sorted now. 

Thanks for the help!! Appreciate it 👍  :) :)
