### ISSUE TITLE
[FEA] concat with +

### ISSUE THREAD

**Issue by gumdropsteve** [rapidsai/cudf#5724]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to call `.head(2)` and `.tail(2)` to display the first few and last few rows of a dataframe. It would be cool to be able to concat them with `+`.

**Describe the solution you'd like**
```python
import cudf

a = cudf.DataFrame()
a['z'] = [1, 2]

b = cudf.DataFrame()
b['z'] = [0, 9]

a + b
```
| z | 
| -- |
| 1 |
| 2 | 
| 0 |
| 9 |

**Describe alternatives you've considered**
```python
import cudf

a = cudf.DataFrame()
a['z'] = [1, 2]

b = cudf.DataFrame()
b['z'] = [0, 9]

cudf.concat([a, b])
```
| z | 
| -- |
| 1 |
| 2 | 
| 0 |
| 9 |

```python
dask_cudf.concat([df.head(2), df.tail(2)]).compute()
```

 dropoff_latitude | dropoff_longitude | dropoff_taxizone_id | dropoff_datetime 
-- | -- | -- | -- | 
40.660793 | -73.960922 | 189 | 2016-02-01 00:06:45
40.709499 | -74.006126 | 210 | 2016-02-01 00:09:01
40.743591 | -73.976830 | 141 | 2009-01-01 00:11:39
40.727242 | -74.001839 | 212 | 2009-01-01 00:07:18

**Comment by shwina** [comment]
@gumdropsteve The `+` operator is used for adding the elements of one dataframe with another -- so `a + b` already works, but gives you:

```python
    z
0   1
1  11
```

Extending `+` to also be able to do concatenation would be difficult or impossible, unfortunately. It could also lead to surprising and difficult to track bugs.

If you want a one-liner for displaying the first and last two rows of a DataFrame, how about `iloc`:

```python
In [5]: a = cudf.DataFrame({'a': [1, 2, 3, 4, 5, 6]})

In [6]: a.iloc[[0, 1, -2, -1]]
Out[6]:
   a
0  1
1  2
4  5
5  6
```

**Comment by kkraus14** [comment]
Closing as this is answered.
