### ISSUE TITLE
[DOC] Document the various types we can cast to in `.astype()`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5728]
The docs for [`astype`](https://docs.rapids.ai/api/cudf/stable/api.html?highlight=astype#cudf.core.dataframe.DataFrame.astype) should include a few different examples of types that Series/DataFrames/Index can be cast to, and how to specify those data types.

For example, see Pandas' astype [docs](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html).

**Comment by kkraus14** [comment]
We should probably have equivalent docs to this:

https://pandas.pydata.org/pandas-docs/stable/getting_started/basics.html#basics-dtypes

**Comment by kkraus14** [comment]
Fixed by #5857
