### ISSUE TITLE
[BUG] Issue when transforming a pa table to pandas.df and then transform it to Cudf. 

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#573]
**Describe the bug**
Hi,

As far as I can see Rapids uses pandas 0.20.3, so it is not possible to read parquet files through pandas (later pandas versions support parquet via pd.read_parquet).

I have tried the following workaround:
- Transform the pa table to pandas.df and then transform it to Cudf. I am getting the following error:

---------------------------------------------------------------------------
CudaAPIError                              Traceback (most recent call last)
<ipython-input-37-25d49050f107> in <module>
----> 1 dspa=cudf.DataFrame.from_pandas(ds)

/conda/envs/rapids/lib/python3.5/site-packages/cudf-0+unknown-py3.5-linux-x86_64.egg/cudf/dataframe/dataframe.py in from_pandas(cls, dataframe, nan_as_null)
   1511         # Set columns
   1512         for colk in dataframe.columns:
-> 1513             df[colk] = Series(dataframe[colk].values, nan_as_null=nan_as_null)
   1514         # Set index
   1515         return df.set_index(dataframe.index.values)

/conda/envs/rapids/lib/python3.5/site-packages/cudf-0+unknown-py3.5-linux-x86_64.egg/cudf/dataframe/series.py in __init__(self, data, index, name, nan_as_null)
     73 
     74         if not isinstance(data, columnops.TypedColumnBase):
---> 75             data = columnops.as_column(data, nan_as_null=nan_as_null)
     76 
     77         if index is not None and not isinstance(index, Index):

/conda/envs/rapids/lib/python3.5/site-packages/cudf-0+unknown-py3.5-linux-x86_64.egg/cudf/dataframe/columnops.py in as_column(arbitrary, nan_as_null)
    176             data = datetime.DatetimeColumn.from_numpy(arbitrary)
    177         else:
--> 178             data = as_column(rmm.to_device(arbitrary), nan_as_null=nan_as_null)
    179 
    180     elif isinstance(arbitrary, pa.Array):

/conda/envs/rapids/lib/python3.5/site-packages/librmm_cffi/wrapper.py in to_device(self, ary, stream, copy, to)
    227         if to is None:
    228             to = self.device_array_like(ary, stream=stream)
--> 229             to.copy_to_device(ary, stream=stream)
    230             return to
    231         if copy:

/conda/envs/rapids/lib/python3.5/site-packages/numba/cuda/cudadrv/devices.py in _require_cuda_context(*args, **kws)
    210     def _require_cuda_context(*args, **kws):
    211         get_context()
--> 212         return fn(*args, **kws)
    213 
    214     return _require_cuda_context

/conda/envs/rapids/lib/python3.5/site-packages/numba/cuda/cudadrv/devicearray.py in copy_to_device(self, ary, stream)
    203 
    204             sz = min(_driver.host_memory_size(ary), self.alloc_size)
--> 205             _driver.host_to_device(self, ary, sz, stream=stream)
    206 
    207     @devices.require_context

/conda/envs/rapids/lib/python3.5/site-packages/numba/cuda/cudadrv/driver.py in host_to_device(dst, src, size, stream)
   1799         fn = driver.cuMemcpyHtoD
   1800 
-> 1801     fn(device_pointer(dst), host_pointer(src), size, *varargs)
   1802 
   1803 

/conda/envs/rapids/lib/python3.5/site-packages/numba/cuda/cudadrv/driver.py in safe_cuda_api_call(*args)
    288             _logger.debug('call driver api: %s', libfn.__name__)
    289             retcode = libfn(*args)
--> 290             self._check_error(fname, retcode)
    291         return safe_cuda_api_call
    292 

/conda/envs/rapids/lib/python3.5/site-packages/numba/cuda/cudadrv/driver.py in _check_error(self, fname, retcode)
    323                     _logger.critical(msg, _getpid(), self.pid)
    324                     raise CudaDriverError("CUDA initialized before forking")
--> 325             raise CudaAPIError(retcode, msg)
    326 
    327     def get_device(self, devnum=0):

CudaAPIError: [1] Call to cuMemcpyHtoD results in CUDA_ERROR_INVALID_VALUE

**Expected behavior**
No error message.

**Environment details (please complete the following information):**
fatal: not a git repository (or any of the parent directories): .git
Python 2.7.15rc1
print_env.sh: line 58: type: conda: not found
print_env.sh: line 63: type: pip: not found

The output of the file environment.txt is the following (I copy paste as attachments have some issues).

**git***

***OS Information***
DGX_NAME="DGX Server"
DGX_PRETTY_NAME="NVIDIA DGX Server"
DGX_SWBUILD_DATE="2018-11-16"
DGX_SWBUILD_VERSION="4.0.4"
DGX_COMMIT_ID="cc11146"
DGX_PLATFORM="DGX Server for DGX-1"
DGX_SERIAL_NUMBER=TobefilledbyO.E.M.
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
Linux nvidiadgx1 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

***GPU Information***
Thu Dec 20 08:26:23 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
| N/A   31C    P0    57W / 300W |  16102MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
| N/A   31C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
| N/A   30C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
| N/A   27C    P0    41W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
| N/A   28C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
| N/A   29C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   30C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
| N/A   29C    P0    42W / 300W |     11MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     23227      C   /conda/envs/rapids/bin/python              16091MiB |
+-----------------------------------------------------------------------------+

***CPU***
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              80
On-line CPU(s) list: 0-79
Thread(s) per core:  2
Core(s) per socket:  20
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               79
Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
Stepping:            1
CPU MHz:             3329.304
CPU max MHz:         3600.0000
CPU min MHz:         1200.0000
BogoMIPS:            4390.19
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            51200K
NUMA node0 CPU(s):   0-19,40-59
NUMA node1 CPU(s):   20-39,60-79
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall
 nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vm
x smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dno
wprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust
 bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida a
rat pln pts flush_l1d

***CMake***
/usr/bin/cmake
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).

***g++***

***nvcc***

***Python***
/usr/bin/python

***Environment Variables***
PATH                            : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
LD_LIBRARY_PATH                 :
NUMBAPRO_NVVM                   :
NUMBAPRO_LIBDEVICE              :
CONDA_PREFIX                    :
PYTHON_PATH                     :

**Additional context**

**Comment by thomcom** [comment]
Thanks @miguelangel ! Can you give me the rest of the code (as though from a REPL) to reproduce the error caused at `dspa=cudf.DataFrame.from_pandas(ds)`?

**Comment by kkraus14** [comment]
Resolved by #893
