### ISSUE TITLE
[FEA] DataFrame.describe() for datetime columns

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5737]
Currently, datetime columns are ignored in `DataFrame.describe()`:

```python
In [4]: df = cudf.DataFrame({"A": pd.date_range("2000", periods=2)})

In [5]: df.describe()
Out[5]:
Empty DataFrame
Columns: []
Index: [count, mean, std, min, 25%, 50%, 75%, max]
```

Per https://github.com/dask/dask/issues/6434, datetime columns will be treated similar to numeric columns in Pandas 1.1, which should make it relatively easy for us to include them in `describe()`.

**Comment by marlenezw** [comment]
Hi! Should datetime_is_numeric be set to True as the default since the datetime columns are numeric now? In the pandas API it looks like it's still set to False as the default.

**Comment by shwina** [comment]
Hmm - here's my understanding of the situation:

* Currently, we don't handle datetimes _at all_ in describe. We also don't appear to handle categoricals.
* Pandas treats datetimes as categoricals by default and historically this was the only supported behaviour.
* Pandas 1.1, introduced the ability to treat them as numeric -- however this is not the default behaviour. However, it sounds like it is the more _useful_ behaviour as Pandas will eventually make it default.

I'd say let's make `datetime_is_numeric=False` the default (same as Pandas), but let's definitely support `datetime_is_numeric=True`.

To support `datetime_is_numeric=False`, we need to be able to handle categoricals in `describe()`. It looks like previously, categorical handling was [blocked](https://github.com/rapidsai/cudf/blob/branch-0.16/python/cudf/cudf/core/series.py#L4041) by some other issues. If that's no longer the case, let's go ahead and add it. If it's still difficult to handle categoricals for some reason, then let's raise a `NotImplementedError` when `datetime_is_numeric=False` as a first step and figure out what's needed to support it.

Supporting `datetime_is_numeric=True` should be relatively easier.

@marlenezw Does that sound good to you?

**Comment by marlenezw** [comment]
Thank you, @shwina, that's super helpful! This all sounds good to me. I've made some changes that I think should support datetime_is_numeric=True. I'll look at how to support categoricals too and then run my code by you once I'm done, or if I run into any issues.

**Comment by galipremsagar** [comment]
Sorry that this wasn't earlier linked to the `describe` refactor PR: https://github.com/rapidsai/cudf/pull/6060

All dtypes(including datetime and duration) support have been added in #6060

**Comment by marlenezw** [comment]
No worries @galipremsagar! I'll take a look at your code just to compare it to what I was thinking :D
