### ISSUE TITLE
[FEA] Automatically detect detect and store the kernel cache in different locations for different architectures

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#5740]
**Is your feature request related to a problem? Please describe.**

I wish cudf could automatically detect and store the kernel cache in different locations for different architectures. 

**Why:** 

Currently we by default use  `/home/.cudf` as the cache location but a lot of times, home directory might be shared across a bunch of machines with different architectures and can cause issues like: https://github.com/rapidsai/cudf/issues/5738 . 

**Workaround:** 

We recommend setting `LIBCUDF_KERNEL_CACHE_PATH ` to a local non shared location. This also adds the benefit of fast IO for the cache location .

**Comment by harrism** [comment]
I believe it was changed to home directory for security reasons. So I think a proper fix might require encoding architecture in the cache key rather than moving the cache.

**Comment by vyasr** [comment]
I believe this is the same issue as #5469 and was resolved by #7090
