### ISSUE TITLE
[FEA] Add support for `to_string` api in cudf Objects

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5741]
**Is your feature request related to a problem? Please describe.**
We should be having a `to_string` API for configurable `__str__` like output for all `cudf` Objects like `DataFrame`, `Series` & `Index`. This API actually allows flexibility to control quite a few params like `na_rep`, `header`, `name`, `dtype`, ...etc.

**Describe the solution you'd like**
Depending on the display setting we can move specific chunk to cudf object to pandas and call `to_string` of those respective objects. Similar to the approach currently being taken in `__str__`

**Describe alternatives you've considered**
The only alternative is to convert to pandas object and use their `to_string`.

**Additional context**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.to_string.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_string.html

**Comment by vyasr** [comment]
This is now supported:
```
In [46]: cudf.DataFrame({'a': [1]}).to_string()
Out[46]: '   a\n0  1'

In [47]: pd.DataFrame({'a': [1]}).to_string()
Out[47]: '   a\n0  1'

In [48]: cudf.Series([1]).to_string()
Out[48]: '0    1\ndtype: int64'

In [49]: pd.Series([1]).to_string()
Out[49]: '0    1'
```
