### ISSUE TITLE
[BUG] Fix header order issue in `device_operators.cuh`

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#5746]
In the https://github.com/rapidsai/cudf/pull/5704, an issue was discovered with the order of the headers included in the file. The issue discussed in the following comment thread: https://github.com/rapidsai/cudf/pull/5704#discussion_r458532778 It seems like it has to do with Jitify requiring `<simt/type_traits>` while other files just depend on `<type_traits>` but the conflict seems to occur from including `fixed_point.hpp` before `utilities/traits.hpp`. This issue is being set up so that the root of this conflict can be addressed and resolved at a later date. Below is a list of some of the files dependency hierarchies:

### device_operators.cuh

#include <cudf/fixed_point/fixed_point.hpp>
--------#include <simt/limits>
--------#include <simt/type_traits>  // add simt namespace
--------#include <algorithm>
--------#include <cassert>
--------#include <cmath>
--------#include <string>

#include <cudf/utilities/traits.hpp>
--------#include <cudf/strings/string_view.cuh>
----------------#include <cuda_runtime.h>
----------------#include <cstddef>
----------------#include <cudf/types.hpp>
----------------#include <iterator>
----------------#include "./string_view.inl"
----------------#include <thrust/find.h>
------------------------#include <cstdlib>
--------#include <cudf/lists/list_view.cuh>
--------#include <cudf/types.hpp>
--------#include <cudf/utilities/type_dispatcher.hpp>
--------#include <cudf/wrappers/durations.hpp>
--------#include <cudf/wrappers/timestamps.hpp>
--------#include <simt/type_traits>

#include <cudf/scalar/scalar.hpp>
--------#include <cudf/types.hpp>
--------#include <cudf/utilities/traits.hpp>
--------#include <cudf/utilities/type_dispatcher.hpp>
--------	#include <rmm/thrust_rmm_allocator.h>
--------#include <rmm/device_buffer.hpp>
--------#include <rmm/device_scalar.hpp>

--------#include <memory>
--------#include <type_traits> <- was ABLE TO DELETE
--------#include <utility>
--------#include <vector>
	
#include <cudf/types.hpp>
#include <cudf/utilities/error.hpp>

#include <simt/type_traits>
#include <type_traits> <- ORIGINALLY

### type.cpp (jit)

#include <cudf/column/column_view.hpp>
#include <cudf/scalar/scalar.hpp>
#include <cudf/utilities/type_dispatcher.hpp>
#include <string>

**Comment by ttnghia** [comment]
Hi there! 

I tried to reproduce this issue but it seems that the issue has been fixed somehow. Can somebody verify that, please?

**Comment by codereport** [comment]
> Hi there!
> 
> @codereport, I tried to reproduce this issue but it seems that the issue has been fixed somehow. Can you or somebody verify that, please?

Hi @ttnghia, thanks for pointing this out. Looks like somewere along the way the issue self resolved. I have set up https://github.com/rapidsai/cudf/pull/7401 to remove the comment and will take the bug label off this issue.
