### ISSUE TITLE
[QST] cudf build failure, I am not sure why. After doing a clean and rerunning it fails after the last cytonizing file 61/61

### ISSUE THREAD

**Issue by brookdpg** [rapidsai/cudf#5761]
ops@ops-XPS-15-9560:~/cudf$ sudo ./build.sh cudf
[sudo] password for ops: 
+ NUMARGS=1
+ ARGS=cudf
+++ dirname ./build.sh
++ cd .
++ pwd
+ REPODIR=/home/ops/cudf
+ VALIDARGS='clean libcudf cudf dask_cudf benchmarks tests libcudf_kafka -v -g -n -l --allgpuarch --disable_nvtx --show_depr_warn -h'
+ HELP='./build.sh [clean] [libcudf] [cudf] [dask_cudf] [benchmarks] [tests] [libcudf_kafka] [-v] [-g] [-n] [-h] [-l]
   clean                - remove all existing build artifacts and configuration (start
                          over)
   libcudf              - build the cudf C++ code only
   cudf                 - build the cudf Python package
   dask_cudf            - build the dask_cudf Python package
   benchmarks           - build benchmarks
   tests                - build tests
   libcudf_kafka        - build the libcudf_kafka C++ code only
   -v                   - verbose build mode
   -g                   - build for debug
   -n                   - no install step
   -l                   - build legacy tests
   --allgpuarch         - build for all supported GPU architectures
   --disable_nvtx       - disable inserting NVTX profiling ranges
   --show_depr_warn     - show cmake deprecation warnings
   -h                   - print this text

   default action (no args) is to build and install '\''libcudf'\'' then '\''cudf'\''
   then '\''dask_cudf'\'' targets
'
+ LIB_BUILD_DIR=/home/ops/cudf/cpp/build
+ CUDF_BUILD_DIR=/home/ops/cudf/python/cudf/build
+ DASK_CUDF_BUILD_DIR=/home/ops/cudf/python/dask_cudf/build
+ BUILD_DIRS='/home/ops/cudf/cpp/build /home/ops/cudf/python/cudf/build /home/ops/cudf/python/dask_cudf/build  '
+ VERBOSE=
+ BUILD_TYPE=Release
+ INSTALL_TARGET=install
+ BUILD_BENCHMARKS=OFF
+ BUILD_ALL_GPU_ARCH=0
+ BUILD_NVTX=ON
+ BUILD_TESTS=OFF
+ BUILD_DISABLE_DEPRECATION_WARNING=ON
+ BUILD_LIBCUDF_KAFKA=OFF
+ INSTALL_PREFIX=
+ PARALLEL_LEVEL=
+ hasArg -h
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' -h '
+ ((  1 != 0  ))
+ for a in ${ARGS}
+ echo ' clean libcudf cudf dask_cudf benchmarks tests libcudf_kafka -v -g -n -l --allgpuarch --disable_nvtx --show_depr_warn -h '
+ grep -q ' cudf '
+ hasArg -v
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' -v '
+ hasArg -g
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' -g '
+ hasArg -n
+ ((  1 != 0  ))
+ grep -q ' -n '
+ echo ' cudf '
+ hasArg --allgpuarch
+ ((  1 != 0  ))
+ grep -q ' --allgpuarch '
+ echo ' cudf '
+ hasArg benchmarks
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' benchmarks '
+ hasArg tests
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' tests '
+ hasArg --disable_nvtx
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' --disable_nvtx '
+ hasArg --show_depr_warn
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' --show_depr_warn '
+ hasArg libcudf_kafka
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' libcudf_kafka '
+ hasArg clean
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' clean '
+ ((  0 == 0  ))
+ GPU_ARCH=-DGPU_ARCHS=
+ echo 'Building for the architecture of the GPU in the system...'
Building for the architecture of the GPU in the system...
+ buildAll
+ (( 1 == 0  ))
+ echo ' cudf '
+ grep -q ' [^-]\+ '
+ hasArg libcudf
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' libcudf '
+ hasArg libcudf_kafka
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' libcudf_kafka '
+ buildAll
+ (( 1 == 0  ))
+ echo ' cudf '
+ grep -q ' [^-]\+ '
+ hasArg libcudf
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' libcudf '
+ buildAll
+ (( 1 == 0  ))
+ echo ' cudf '
+ grep -q ' [^-]\+ '
+ hasArg cudf
+ ((  1 != 0  ))
+ echo ' cudf '
+ grep -q ' cudf '
+ cd /home/ops/cudf/python/cudf
+ [[ install != '' ]]
+ PARALLEL_LEVEL=
+ python3.6 setup.py build_ext --inplace
version is3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0]
/home/ops/.local/lib/python3.6/site-packages/setuptools/dist.py:454: UserWarning: Normalizing '0.15.0a+2665.g3cf6c2571.dirty' to '0.15.0a0+2665.g3cf6c2571.dirty'
  warnings.warn(tmpl.format(**locals()))
running build_ext
building 'cudf._cuda.gpu' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../cpp/include/cudf -I../../cpp/include -I../../cpp/build/include -I../../cpp/build/_deps/libcudacxx-src/include -I/usr/include/libcudf/libcudacxx -I/usr/include -I/usr/local/lib/python3.6/dist-packages/numpy/core/include -I/home/ops/.local/lib/python3.6/site-packages/pyarrow/include -I/usr/include -I/usr/include/python3.6m -c cudf/_cuda/gpu.cpp -o build/temp.linux-x86_64-3.6/cudf/_cuda/gpu.o -std=c++14
cudf/_cuda/gpu.cpp: In function ‘int __pyx_pymod_exec_gpu(PyObject*)’:
cudf/_cuda/gpu.cpp:5650:90: error: ‘cudaDevAttrCanFlushRemoteWrites’ was not declared in this scope
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrCanFlushRemoteWrites)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 255, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:5650:90: note: suggested alternative: ‘__pyx_k_cudaDevAttrCanFlushRemoteWrites’
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrCanFlushRemoteWrites)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 255, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          __pyx_k_cudaDevAttrCanFlushRemoteWrites
cudf/_cuda/gpu.cpp:5662:90: error: ‘cudaDevAttrHostRegisterSupported’ was not declared in this scope
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrHostRegisterSupported)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 257, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:5662:90: note: suggested alternative: ‘__pyx_k_cudaDevAttrHostRegisterSupported’
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrHostRegisterSupported)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 257, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          __pyx_k_cudaDevAttrHostRegisterSupported
cudf/_cuda/gpu.cpp:5674:90: error: ‘cudaDevAttrPageableMemoryAccessUsesHostPageTables’ was not declared in this scope
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrPageableMemoryAccessUsesHostPageTables)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 259, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:5674:90: note: suggested alternative: ‘__pyx_n_s_pageableMemoryAccessUsesHostPage’
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrPageableMemoryAccessUsesHostPageTables)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 259, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          __pyx_n_s_pageableMemoryAccessUsesHostPage
cudf/_cuda/gpu.cpp:5686:90: error: ‘cudaDevAttrDirectManagedMemAccessFromHost’ was not declared in this scope
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrDirectManagedMemAccessFromHost)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 262, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:5686:90: note: suggested alternative: ‘__pyx_n_s_directManagedMemAccessFromHost’
   __pyx_t_4 = __Pyx_PyInt_From_int(((__pyx_t_4cudf_5_cuda_3gpu_underlying_type_attribute)cudaDevAttrDirectManagedMemAccessFromHost)); if (unlikely(!__pyx_t_4)) __PYX_ERR(0, 262, __pyx_L1_error)
                                                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                          __pyx_n_s_directManagedMemAccessFromHost
cudf/_cuda/gpu.cpp: In function ‘PyObject* __pyx_convert__to_py_cudaDeviceProp(cudaDeviceProp)’:
cudf/_cuda/gpu.cpp:7869:35: error: ‘struct cudaDeviceProp’ has no member named ‘directManagedMemAccessFromHost’
   member = __Pyx_PyInt_From_int(s.directManagedMemAccessFromHost); if (unlikely(!member)) goto bad;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:7893:40: error: ‘struct cudaDeviceProp’ has no member named ‘luid’
   member = __Pyx_PyObject_FromString(s.luid); if (unlikely(!member)) goto bad;
                                        ^~~~
cudf/_cuda/gpu.cpp:7896:44: error: ‘struct cudaDeviceProp’ has no member named ‘luidDeviceNodeMask’
   member = __Pyx_PyInt_From_unsigned_int(s.luidDeviceNodeMask); if (unlikely(!member)) goto bad;
                                            ^~~~~~~~~~~~~~~~~~
cudf/_cuda/gpu.cpp:8001:35: error: ‘struct cudaDeviceProp’ has no member named ‘pageableMemoryAccessUsesHostPageTables’; did you mean ‘pageableMemoryAccess’?
   member = __Pyx_PyInt_From_int(s.pageableMemoryAccessUsesHostPageTables); if (unlikely(!member)) goto bad;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                   pageableMemoryAccess
cudf/_cuda/gpu.cpp:8055:45: error: ‘struct cudaDeviceProp’ has no member named ‘uuid’
   member = __pyx_convert__to_py_CUuuid_st(s.uuid); if (unlikely(!member)) goto bad;
                                             ^~~~
cudf/_cuda/gpu.cpp: At global scope:
cudf/_cuda/gpu.cpp:7816:18: warning: ‘PyObject* __pyx_convert__to_py_CUuuid_st(CUuuid_st)’ defined but not used [-Wunused-function]
 static PyObject* __pyx_convert__to_py_CUuuid_st(CUuuid_st s) {
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by kkraus14** [comment]
@brookdpg what version of CUDA toolkit and the driver do you have installed?

Can you dump the output of `nvidia-smi` and `nvcc --version` here?

**Comment by brookdpg** [comment]
ops@ops-XPS-15-9560:~/cudf/python/cudf/cudf$ nvidia-smi 
Fri Jul 24 11:45:58 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.48                 Driver Version: 410.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1050    Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   51C    P3    N/A /  N/A |    889MiB /  4042MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1997      G   /usr/lib/firefox/firefox                       1MiB |
|    0      4899      G   /usr/lib/xorg/Xorg                           608MiB |
|    0      5315      G   /usr/bin/gnome-shell                         276MiB |
|    0     31391      G   /usr/lib/firefox/firefox                       1MiB |
+-----------------------------------------------------------------------------+
ops@ops-XPS-15-9560:~/cudf/python/cudf/cudf$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
ops@ops-XPS-15-9560:~/cudf/python/cudf/cudf$

**Comment by kkraus14** [comment]
Okay, looks like you have CUDA toolkit version 9.1 installed, and the oldest version we support is CUDA 10.1 as of 0.15 nightlies.
