### ISSUE TITLE
[FEA] Add Float 16 support to RAPIDS cudf

### ISSUE THREAD

**Issue by MurrayData** [rapidsai/cudf#5770]
**Is your feature request related to a problem? Please describe.**

I want to use half precision for some inputs to a deep learning model and was hoping to use Numba Kernels and UDFs. within 
RAPIDS in the data preparation stage.

At present there is no Numba JIT CUDA kernel support for float16 and RAPIDs converts to float32 on ingestion from NumPy or CuPy.

CuPy supports float16.

When I try to run a kernel on a CuPy created float 16 array, I get:
```
NotImplementedError: float16
```

**Describe the solution you'd like**

Provide float16 support in RAPIDS cudf. I've logged an issue with Numba also who have plans to implement but work is needed.

https://github.com/numba/numba/issues/4402

**Describe alternatives you've considered**

With modern GPUs supporting half precision for deep learning, i woudl like to generate tensors directly from RAPIDS so no alternative.

Workaround is post-processing with CuPy.

**Comment by harrism** [comment]
This is definitely something we can do, but it will require significant work (as with adding any datatype).

**Comment by jrhemstad** [comment]
> This is definitely something we can do, but it will require significant work (as with adding any datatype).

float16 poses even more difficulty than adding other types because the `__half` type doesn't behave like normal types, e.g., it doesn't have normal arithmetic or comparison operators. You have to go through the special half-precision intrinsics like `_hadd`, so that means pretty much every feature/algorithm will need significant specialization for half-precision types.

**Comment by harrism** [comment]
Actually CUDA provides a C++ class for half (I believe in cuda_fp16.h) that makes it work like other float types on both host and device and is bit exact between the two.  Also half2 which provides higher throughput.

**Comment by jrhemstad** [comment]
> Actually CUDA provides a C++ class for half (I believe in cuda_fp16.h) that makes it work like other float types on both host and device and is bit exact between the two. Also half2 which provides higher throughput. So we shouldnt need to use to use the builtins.

I originally checked `cuda_fp16.h` but missed `cuda_fp16.hpp` that does indeed define the `__half` type arithmetic operators. 

It doesn't work in host code though, so it's going to be a pain to write tests.

**Comment by tkram01** [comment]
Was this closed because it was decided not to implement it?

**Comment by harrism** [comment]
I think the requester closed it. @GregoryKimball should probably decide whether or not to reopen it.

**Comment by quasiben** [comment]
It's worth noting the CUDA FP16 support in Numba is wrapping up.  I believe the last PR for support is https://github.com/numba/numba/pull/8001 -- we are trying to target full support in the 0.57 release

**Comment by Pedrexus** [comment]
Any news on this issue?

**Comment by jrhemstad** [comment]
fwiw, it's on our roadmap for libcu++ to had an equivalent of `__half` that works in both host/device code. That would resolve my original concern with trying to add support for fp16 in libcudf.

There's still the obvious concern of increased compile time and binary size that comes with adding any new type. The juice would need to be worth the squeeze.

**Comment by Pedrexus** [comment]
Nice, is there a schedule for it becoming available?
