### ISSUE TITLE
[QST] UserWarning: you will need a GPU with NVIIDA Pascal or newer architecture

### ISSUE THREAD

**Issue by stevencarlislewalker** [rapidsai/cudf#5776]
**What is your question?**

We are using cuDF to build out predictive modelling pipelines.

We get the following warning.
![cudf_warning](https://user-images.githubusercontent.com/2754158/88584729-19e21800-d020-11ea-91c0-cf7408faa421.png)

Note that we are able to create cuDF dataframes, so we are not sure how relevant the warning is for us.  We are warned about a potential issue, but then there appears to be no such issue.

How can we tell whether this warning points to a genuine issue in any particular case?

Thanks!

**Comment by teju85** [comment]
@stevencarlislewalker most of RAPIDS projects [support GPUs from Pascal+ architectures only](https://github.com/rapidsai/cudf/#cudagpu-requirements), including cudf. And from the screenshot above, it seems that you are on a K80 which is 2 architectures older than Pascal. Thus, this warning is expected in your case. Can you retry this on any GPU from [this](https://developer.nvidia.com/cuda-gpus#compute) list whose capability version is >= 6.0?

**Comment by harrism** [comment]
> How can we tell whether this warning points to a genuine issue in any particular case?

This is a genuine warning. If you actually try to run algorithms on the data frames you created they are likely to fail with errors.

**Comment by kkraus14** [comment]
Closing as this has been answered.

**Comment by stevencarlislewalker** [comment]
Thanks @harrism and @teju85.  I apologize for the late reply, but I did appreciate your answer.
