### ISSUE TITLE
Use standards-compliant "include guards" consistently

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#578]
At the moment, some header files used `#ifndef FILE_NAME_H_`-style include guards, while others use `#pragma once` (e.g. `include/gdf/cffi/types.h`. While the latter is widely supported, it does not offer a meaningful benefit, and - it is non-standard.

I suggest the same kind of include guards be used all over, and that these be the standards-compliant `#ifndef`-based ones.

For discussion of this issue see:

- [Is #pragma once a safe include guard?](https://stackoverflow.com/questions/787533/is-pragma-once-a-safe-include-guard)
- [#pragma once vs include guards](https://stackoverflow.com/questions/1143936/pragma-once-vs-include-guards)

**Comment by jrhemstad** [comment]
Note that in some instances it is required because CFFI cannot process an `#include` guard whereas `#pragma once` is ignored. This is true of `include/gdf/cffi/types.h`.

But when not otherwise required by CFFI, I agree that standard include guards should be used.

**Comment by jrhemstad** [comment]
Probably wasted effort as CFFI will slowly go away in favor of Cython.

**Comment by harrism** [comment]
There has been a decision to allow #pragma once in RAPIDS libraries since all compilers we care about support it.
