### ISSUE TITLE
[DISCUSS] cuDF testing strategy 

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#5788]
Opening this issue for discussing the following points brought up by @cwharris in https://github.com/rapidsai/cudf/issues/5754#issuecomment-665182370

> If I recall correctly, assert_eq relies on Pandas’s assert utilities, which is why we need to convert from non-nullable. Is this a good opportunity to implement our own testing comparators? That could serve as both a good reference and the defacto for how cuDF types map to Pandas types, and allow us to add special consideration for certain types. It’s possible this would eliminate “unless it’s this type, and then test this other way and fill null results with...” logic in our tests - I think this would lead to more consistency, less bugs, faster tests, and less time spent writing tests.

> I think “upgrading”/converting Pandas types to cudf types, then using custom comparators is a good approach - if we choose to write our own.

**Comment by brandon-b-miller** [comment]
Since our source of truth is generally the result of the corresponding operation in pandas, Really I think the "correct" approach here is to instantiate the pandas test data as nullable types up front in as many cases as possible. After that we'd perform the operation in question and then `to_pandas` should work fine for comparison.

If anything ends up being different it signals something that's different about the way cuDF `null` works w.r.t `pd.NA` and we want to know that.

**Comment by shwina** [comment]
Side note: external users should use the public APIs in [`cudf.testing`](https://github.com/rapidsai/cudf/blob/branch-0.15/python/cudf/cudf/testing/testing.py) for comparing two cuDF objects, rather than the internal `assert_eq` utility.

**Comment by brandon-b-miller** [comment]
Turns out the limitation to what I said before is just that pandas doesn't yet support certain things for nullable series. For example:

```
>>> import operator
>>> import pandas as pd
>>> x = pd.Series([1,2,3], dtype=pd.Int64Dtype())
>>> y = pd.Series([4,5,6], dtype=pd.Int64Dtype())
>>> operator.and_(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nfs/brmiller/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/pandas/core/ops/common.py", line 64, in new_method
    return method(self, other)
  File "/home/nfs/brmiller/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/pandas/core/ops/__init__.py", line 552, in wrapper
    res_values = logical_op(lvalues, rvalues, op)
  File "/home/nfs/brmiller/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/pandas/core/ops/array_ops.py", line 351, in logical_op
    res_values = dispatch_to_extension_op(op, lvalues, rvalues)
  File "/home/nfs/brmiller/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/pandas/core/ops/dispatch.py", line 125, in dispatch_to_extension_op
    res_values = op(left, right)
TypeError: unsupported operand type(s) for &: 'IntegerArray' and 'IntegerArray'
```

**Comment by brandon-b-miller** [comment]
I believe this is no longer relevant / has been fixed by a combination of `nullable=False` being written into `to_pandas` and broadly keeping all the original tests the same by defaulting to false.
