### ISSUE TITLE
Building libgdf/pygdf against CUDA enabled Apache Arrow

### ISSUE THREAD

**Issue by pearu** [rapidsai/cudf#579]
I am creating this issue to record the current procedure for building libgdf and pygdf against CUDA enabled arrow. Suggestions to improve the procedure are given at the end.

Building the libraries with CUDA support requires Arrow version 0.11 which has not been released as of yet. So, using the master branch from arrow github atm. Both libgdf and pygdf are from their respective master branches.

# Setting up conda environment
```
conda create -n libgdf-arrow011 python>=3.6 pytest cmake setuptools numpy cffi \
  numba>=0.40 pandas cython -c conda-forge
conda activate libgdf-arrow011
```

Check out libgdf and pygdf master branches as usual.

# Building libgdf with CUDA enabled arrow
```
export PARQUET_ARROW_VERSION=master
```
One should change `master` to `0.11` when arrow 0.11 is released.

## Option 1: using patched libgdf

Use [arrow-cuda branch of Quansight/libgdf](https://github.com/Quansight/libgdf/tree/arrow-cuda).

## Option 2: change libgdf manually

Edit `libgdf/cmake/Templates/Arrow.CMakeList.txt` so that
```
  -DARROW_BUILD_SHARED=ON -DARROW_GPU=ON -DARROW_COMPUTE=ON -DARROW_PYTHON=ON -DARROW_HDFS=ON
```
are effective. This is required for enabling CUDA support both in libgdf and pygdf.

Apply the following patch to `libgdf/CMakeFiles.txt`:
```
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -175,7 +175,7 @@ add_custom_target(   # target to link the python files and trigger cffi
 # The test target
 add_custom_target(pytest DEPENDS copy_python)
 add_custom_command(TARGET pytest POST_BUILD
-                   COMMAND ${CMAKE_COMMAND} -E env LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CMAKE_BINARY_DIR} py.test -v
+                   COMMAND ${CMAKE_COMMAND} -E env LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${CMAKE_BINARY_DIR}:${ARROW_ROOT}/lib py.test -v
                    WORKING_DIRECTORY --cache-clear tests)
```

## Build libgdf

```
mkdir libgdf/build
cd libgdf/build
cmake -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
make
make test
make pytest # expect test_arrow_availability to fail
```
It is expected that `test_arrow_availability` will fail because pyarrow is not installed. If pyarrow is installed, you should remove it because pyarrow needs to be built with CUDA support enabled, see below.

Install libgdf for pygdf:
```
make install
python setup.py develop
```

# Build pyarrow with CUDA support

```
cd CMakeFiles/thirdparty/arrow-download/arrow-prefix/src/arrow/python/
export ARROW_HOME=`pwd`/../../arrow-install/usr/local/
python setup.py build_ext --with-cuda develop
cd -
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ARROW_HOME/lib
```

# Build pygdf

```
cd ../pygdf
python setup.py develop
```

# Testing pygdf and libgdf

Set up numba environment (you might need to adjust the values):
```
export NUMBAPRO_LIBDEVICE=/usr/local/cuda-9.2/nvvm/libdevice
export NUMBAPRO_NVVM=/usr/local/cuda-9.2/nvvm/lib64/libnvvm.so
```

Run pygdf tests
```
py.test -sv .
```
Most tests are expected to pass. Any failures may or may not be related to this issue.

Run libgdf tests
```
cd ../libgdf/build
make pytest
```
Now all tests are expected to succeed.

# Final notes

The above procedure is clearly suboptimal because the way libgdf uses arrow: libgdf is linked statically to arrow library (that is fine) but pyarrow needs to be built against the same arrow library to match the versions as well as to enable CUDA support.

For an optimal procedure, I suggest the following workflow:
1. Build and install arrow library with CUDA support, or use the corresponding conda package (say, arrow-cpp-cuda, does not exist yet).
2. Build and install pyarrow package with CUDA support, or use the corresponding conda package (say, pyarrow-cuda, does not exist yet).
3. Build and install libgdf using the arrow library from step 1. This requires some changes in libgdf cmake configuration.
4. Build and install pygdf as usual.

**Comment by thomcom** [comment]
Should we move this to live documentation on the website and review it next time issues are generated from it?

**Comment by kkraus14** [comment]
Closing as this is outdated.
