### ISSUE TITLE
[BUG] possible leak in `mutable_table_device_view`

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#5792]
@jlowe and I have been debugging a leak seen on the spark side, and I think we've hit a small leak that could lead to fragmentation over time.

It seems to be here:

```
diff --git a/cpp/include/cudf/table/table_device_view.cuh b/cpp/include/cudf/table/table_device_view.cuh
index b4099c6eb5..e54cbea855 100644
--- a/cpp/include/cudf/table/table_device_view.cuh
+++ b/cpp/include/cudf/table/table_device_view.cuh
@@ -95,7 +95,10 @@ class mutable_table_device_view
  public:
   static auto create(mutable_table_view source_view, cudaStream_t stream = 0)
   {
-    auto deleter = [](mutable_table_device_view* t) { t->destroy(); };
+    auto deleter = [](mutable_table_device_view* t) {
+      t->destroy();
+      delete t->_descendant_storage;
+    };
     return std::unique_ptr<mutable_table_device_view, decltype(deleter)>{
       new mutable_table_device_view(source_view, stream), deleter};
   }
```
After the diff above is applied, I am not detecting any more leaks. I'll keep testing. It would be great to have someone double check this patch, and I am happy to submit a PR for it if people think it is OK.

The other subclass of `table_device_view_base` was deleting `_descendent_storage`, but `mutable_table_view` wasn't.

We added some logging in RMM to find this and I have some call stacks if people are interested. In our case, it was happening within the aggregate kernel.

**Comment by jrhemstad** [comment]
Confirmed, that's definitely a leak.

**Comment by abellina** [comment]
Ok thanks @jrhemstad, added a PR.
