### ISSUE TITLE
[FEA] support linking Boost statically

### ISSUE THREAD

**Issue by rongou** [rapidsai/cudf#5794]
**Is your feature request related to a problem? Please describe.**
The java library requires linking Boost statically (https://github.com/rapidsai/cudf/tree/branch-0.15/java#build-from-source). However, the current conda-based build environment doesn't actually support this. One needs to obtain `libboost_filesystem.a` separately.

**Describe the solution you'd like**
There are several options:
1. Ask the user to install Boost manually outside of conda, `sudo apt install libboost-all-dev`. This may be a very old version, depending on the OS.
1. Ask the user to download and build Boost. This seems like extra work.
1. Download and build Boost using CMake. This may increase the CMake running time, but it does make the build more self contained. However, with the shared library option, Boost still needs to be in the conda environment.
1. Replace the couple places we actually use Boost (really just `boost::filesystem::path` and `boost::filesystem::create_directories`) with our own code. Making this work cross platform is probably non-trivial.
1. Wait for CUDA 11 and C++17 and replace `boost::filesystem` with `std::filesystem`.

Looking at these options, maybe we can do 1 right now and 5 later?

**Additional context**
* Also see #2599
* Static libs were recently removed from the `conda-cpp` conda package (https://github.com/conda-forge/boost-cpp-feedstock/pull/76).

**Comment by kkraus14** [comment]
I think we should support 1 and 3 for now, and once 5 happens we can migrate.

> * Static libs were recently removed from the `conda-cpp` conda package ([conda-forge/boost-cpp-feedstock#76](https://github.com/conda-forge/boost-cpp-feedstock/pull/76)).

Even with a boost static conda package, I don't think this solves the problem for the Java build since it would have the C++11 ABI which isn't compatible with CentOS / RHEL outside of conda.
