### ISSUE TITLE
[BUG]cudaErrorIllegalAddress when trying to subword tokenize more than 100 strings

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#5796]
**Describe the bug**

We seem to be hitting cudaErrorIllegalAddress when trying to subword tokenize more than 100 strings 

**Steps/Code to reproduce bug**
##### Create the required Vocab Hash Table
```python
with open('test_vocab.txt','w+') as file:
    string = '[PAD]\n[CLS]\n[UNK]\n[SEP]\nThis\nis\na\ntest'
    file.write(string)

# !wget https://raw.githubusercontent.com/rapidsai/clx/267c6d30805c9dcbf80840f222bf31c5c4b7068a/python/clx/analytics/perfect_hash.py
!python3 perfect_hash.py  --vocab 'test_vocab.txt' --output 'test_vocab-hash.txt' --compact
```
####  Actual Bug:
```python

import cudf
string = "This is a test"
test_len =101
str_ser = cudf.Series([string]*test_len)
cudf_tokens, masks, metadata = str_ser.str.subword_tokenize("test_vocab-hash.txt")
```

```python

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-f1ab0cec3f68> in <module>
      3 test_len =101
      4 str_ser = cudf.Series([string]*test_len)
----> 5 cudf_tokens, masks, metadata = str_ser.str.subword_tokenize("test_vocab-hash.txt")

/nvme/0/vjawa/conda/envs/cuml_july_28/lib/python3.7/site-packages/cudf/core/column/string.py in subword_tokenize(self, hash_file, max_length, stride, do_lower, do_truncate, max_num_strings, max_num_chars, max_rows_tensor, **kwargs)
   4167             max_num_strings,
   4168             max_num_chars,
-> 4169             max_rows_tensor,
   4170         )
   4171         return (

cudf/_lib/nvtext/subword_tokenize.pyx in cudf._lib.nvtext.subword_tokenize.subword_tokenize()

RuntimeError: for_each: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Expected behavior**
I would expect the same behavior as I get tokenize<=100 strings. 
```python
import cudf
string = "This is a test"
test_len =100
str_ser = cudf.Series([string]*test_len)
cudf_tokens, masks, metadata = str_ser.str.subword_tokenize("test_vocab-hash.txt")
cudf_tokens[0:10]
```
```python
array([2, 5, 6, 7, 0, 0, 0, 0, 0, 0], dtype=uint32)
```
**Environment overview (please complete the following information)**
 

**Environment details**
```
cudf                      0.15.0a200728   py37_g9951f71d4_3630    rapidsai-nightly
libcudf                   0.15.0a200728   cuda10.2_g9951f71d4_3630    rapidsai-nightly
```

CC: @davidwendt / @raykallen / @BartleyR  / @randerzander

**Comment by davidwendt** [comment]
My first thought is that `subword_tokenizer` has 8 parameters. One is `max_num_strings` which is default set to `100`.
https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.column.string.StringMethods.subword_tokenize
Can you try setting this parameter higher?

**Comment by VibhuJawa** [comment]
> My first thought is that subword_tokenizer has 8 parameters. One is max_num_strings which is default set to 100.
> https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.column.string.StringMethods.subword_tokenize
> Can you try setting this parameter higher?

Yup, that seems to fix that issue, Missed that parameter.   Thanks David. 

I am still wondering why we even need `max_num_strings ` parameter at all if the input is a string series?

For reference [hugging face](https://huggingface.co/transformers/main_classes/tokenizer.html )  API does not seem to have it.

**Comment by VibhuJawa** [comment]
Closing this issue to better discuss it and related problems in 5799 .
