### ISSUE TITLE
[QST] Choose specific GPU to use with Dask-cuDF

### ISSUE THREAD

**Issue by jmkim** [rapidsai/cudf#5798]
In a machine with multiple GPUs is it possible to select which GPU to use for Dask-cuDF? Thank you!

Related question: #3428 (for cuDF)

**Comment by beckernick** [comment]
Yes! The answer in your linked issue also applies to Dask-cuDF.

If you're using a LocalCUDACluster, you can pass `CUDA_VISIBLE_DEVICES=...` to set specific GPUs. If you're using the command line to launch dask-cuda-workers, you can set `CUDA_VISIBLE_DEVICES` as an environment variable to dictate which GPUs get workers.

Closing this for now, but please feel free to open again if you have any more questions regarding how to do this.

**Comment by jmkim** [comment]
Hi,

Thank you for your fast reply! \o/

It seems for Dask-cuDF, `CUDA_VISIBLE_DEVICES` is for specifying the (multiple) GPUs for compute, but with only one GPU's memory. I confirmed on my machine that `CUDA_VISIBLE_DEVICES` works well with multiple GPUs and Dask-cuDF combination. It worked but seems using only one GPU memory even over multiple GPUs.

* How can I distribute the memory usage into multiple GPUs with Dask-cuDF?
* I have two NVLinked `GeForce RTX 2080 Ti`, is this a supported GPU for distributing the memory?

@beckernick (Sorry, I mention you in here, cuz I cannot re-open this issue)

Thank you!
