### ISSUE TITLE
The API headers are missing explanatory/Doxygen comments

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#580]
`include/types.h` and `include/functions.h` are central parts of the API. Almost no functions nor data types have explanatory comments - and many of them need such comments (for people who do not have prior experience with the library). I'm writing some (as part of getting to know the interface).

**Comment by eyalroz** [comment]
@thomcom : In terms of quantity, yes, in terms of quality, not really. A bunch of the new doxygen comments are ok, but there are some comments which are redundant (e.g. full comments on _i8, i_16 etc.), and some comments which don't really explain what a function does.

So if you commit that you can close this issue, but try to give it some editorial attention.

**Comment by thomcom** [comment]
Yes, there are a huge quantity of comments there that I'm not extremely positive on. :) This issue has been transferred from libgdf, so I have less background context than usual. Personally, I am not inclined to accept 2300 lines of comments, and I'd prefer to punt it back to the author then delve into lots of copy/paste. What do you think?

**Comment by eyalroz** [comment]
I think at least one round of punting is reasonable, with a bit of guidance on what's expected. Perhaps some specific review notes on a couple of specific Doxygen comments as well.

That will likely also reduce the number of comment lines.

However - `functions.h` does have several hundred functions defined, even if we drop the typed variants (`_i8`, `_f32`, etc.) - so you'd expect well over 1,000 lines of Doxygen comments overall.

**Comment by kkraus14** [comment]
Closing this as documentation is an ongoing effort and has vastly improved.
