### ISSUE TITLE
[FEA] Upgrade arrow to 1.0

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#5835]
In late July arrow released 1.0: https://arrow.apache.org/blog/2020/07/24/1.0.0-release/ . This release includes a new datasets API which dask will shortly be using.   I believe both cuda 10/11 arrow packages are already available on conda-forge

**Comment by kkraus14** [comment]
I believe @trxcllnt is looking at this

**Comment by calebwin** [comment]
Also, #5843, which I am working on, depends on this. I'm using pyarrow's dataset API and filtering functionality for which the latest version is in pyarow 1.0.

**Comment by trxcllnt** [comment]
We're blocked until [this PR](https://github.com/apache/arrow/pull/7909), or another with a solution to the underlying problem, is merged and released. [This](https://github.com/trxcllnt/cudf/tree/fea/arrow-1.0.0) is my current in-progress cudf branch using Arrow 1.0.0.
