### ISSUE TITLE
[FEA] Smarter Parquet Filtering

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#5838]
In moving toward predicate pushdown we can take a small step on the Python side of cuDF if we filter out the row groups we want to read _prior_ to reading.  This would be something like:

```python
cudf.read_parquet(..., filter=....)

def read_parquet(..., filter=DNF):

    # DataSets API
    
    fragments = pa.Dataset.get_fragments(filters=filters)
    for frag in fragments:
        rgs = frag.split_by_row_group(filters)

    # read in list of row groups if available
    cdf = cudf.read_parquet(...,row_groups=rgs)
```

We can show this working in a more extensive example:

```python
In [1]: import dask

In [2]: import pandas as pd

In [3]: ddf = dask.datasets.timeseries()

In [4]: ddf.head()
Out[4]:
                       id     name         x         y
timestamp
2000-01-01 00:00:00  1009  Charlie -0.939573 -0.087096
2000-01-01 00:00:01  1000      Bob -0.103627 -0.511412
2000-01-01 00:00:02  1010   Hannah -0.034740 -0.113289
2000-01-01 00:00:03   989  Charlie -0.003334  0.111069
2000-01-01 00:00:04   993    Edith -0.901643  0.611072

In [5]: ddf2 = ddf.set_index('name').reset_index() # sort data by name

In [6]: import pyarrow as pa

In [7]: schema = pa.schema([("name", pa.string()),
    ...:                     ("id", pa.int64()),
    ...:                     ("x", pa.float64()),
    ...:                     ("y", pa.float64()),
    ...:                    ])
    ...:
    ...:

In [8]: ddf2.to_parquet('ts-dask.parquet', engine='pyarrow', schema=schema)

In [9]: df = ddf2.compute()

In [10]: df.to_parquet('ts.parquet', engine='pyarrow', row_group_size=500_000)
```

The above generates two parquet datasets:
1) directory of parquet files with metadata stored at `ts-dask.parquet/_metadata`
2) a single parquet file with 6 row groups

Using `pyarrow=1.0` we can get the rows groups which pass a filter with the following:

```python
In [1]: import pyarrow.dataset as ds

In [2]: import pyarrow as pa

In [3]: import pyarrow.parquet as pq

In [4]: pa_filters = pq._filters_to_expression([('name', '==', 'Bob')])

In [5]: total_rgs = 0

In [6]: dataset = ds.dataset('/tmp/bzaitlen/ts.parquet', format="parquet")

In [7]: for frag in list(dataset.get_fragments(pa_filters)):
   ...:     rgs = frag.split_by_row_group(pa_filters)
   ...:     total_rgs += len(rgs)
   ...:     for rg in rgs:
   ...:         for r in rg.row_groups:
   ...:             print(r.statistics)
   ...: print("Total number of row_groups to read", total_rgs)
{'name': {'min': 'Alice', 'max': 'Frank'}, 'id': {'min': 853, 'max': 1157}, 'x': {'min': -0.9999988240521096, 'max': 0.9999981473247674}, 'y': {'min': -0.9999905162772675, 'max': 0.9999994127748095}, '__index_level_0__': {'min': 0, 'max': 100432}}
Total number of row_groups to read 1

In [8]: total_rgs = 0

In [9]: dataset = ds.dataset('/tmp/bzaitlen/ts-dask.parquet/', format="parquet")

In [10]: for frag in list(dataset.get_fragments(pa_filters)):
    ...:     rgs = frag.split_by_row_group(pa_filters)
    ...:     total_rgs += len(rgs)
    ...:     for rg in rgs:
    ...:         for r in rg.row_groups:
    ...:             print(r.statistics)
    ...: print("Total number of row_groups to read", total_rgs)
{}
{}
{'name': {'min': 'Bob', 'max': 'Bob'}, 'id': {'min': 868, 'max': 1157}, 'x': {'min': -0.9999906429881646, 'max': 0.9999813763065377}, 'y': {'min': -0.9999881748336441, 'max': 0.9999994127748095}}
{}
{}
Total number of row_groups to read 5
```

cc @calebwin @kkraus14 @rjzamora

**Comment by kkraus14** [comment]
> Using pyarrow=1.0 we can get the rows which pass a filter with the following:

You mean row groups, not specific rows, correct?

**Comment by kkraus14** [comment]
cc @felipeblazing @williamBlazing @revans2 @jlowe would this type of row group pruning be of interest for you if we pushed it down to the libcudf level or are you already handling it yourself?

**Comment by quasiben** [comment]
> You mean row groups, not specific rows, correct?

Sorry, yes

**Comment by jlowe** [comment]
For the Spark plugin we're going through the same code Spark uses to filter the Parquet row groups.  Otherwise we'd have to translate the Spark filter predicate into some kind of libcudf predicate equivalent.  It was simpler and more compatible with Spark to go through the existing code path we have available.

If libcudf ever supports filtering rows _within_ the row group then we would need to translate the Spark predicate into the libcudf equivalent to take advantage of that.  At that point the hard work of translating the filter would be done, and we could leverage the common libcudf CPU code to perform the row group filtering as well.

**Comment by kkraus14** [comment]
> If libcudf ever supports filtering rows _within_ the row group then we would need to translate the Spark predicate into the libcudf equivalent to take advantage of that. At that point the hard work of translating the filter would be done, and we could leverage the common libcudf CPU code to perform the row group filtering as well.

One thing we've been discussing is the ability to take in a filter, and then load only the columns relevant to the filter first to see if additional row groups can be pruned (after the typical metadata based pruning) and then avoid loading those row groups for the additional columns.

Otherwise I don't think there's an opportunity to fuse the kernels for filtering and decoding where we'd likely be best off just reading and then performing the filter after the read.

**Comment by jlowe** [comment]
> One thing we've been discussing is the ability to take in a filter, and then load only the columns relevant to the filter first to see if additional row groups can be pruned

Nice.  If that prunes a fair number of row groups in real-world queries that would be incentive enough for us to translate the Spark filter into a libcudf equivalent.

**Comment by calebwin** [comment]
> Otherwise I don't think there's an opportunity to fuse the kernels for filtering and decoding where we'd likely be best off just reading and then performing the filter after the read.

I agree. Based on discussion with Ben, I've temporarily shifted my work from #5804 to #5843 which will implement row-group-level filtering for the Python Parquet reader. We think that implementing some filtering on the Python side first using pyarrow should make it easier to determine how and what kind of filtering can be useful on the C++ side.
