### ISSUE TITLE
[FEA] cudf.Series.items() as an equivalent for pandas.Series.items()

### ISSUE THREAD

**Issue by think-high** [rapidsai/cudf#5842]
**Is your feature request related to a problem? Please describe.**
I am working on enabling dask_cudf dataframe profiling and for that I have a code flow that uses [`six.iteritems`](https://six.readthedocs.io/#six.iteritems). And it's breaking because `cudf.Series` doesn't have `items()` as a method unlike [`pandas.Series`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.items.html#pandas.Series.items).

**Describe the solution you'd like**
`items()` method in `cudf.Series` that returns an Iterable of tuples containing the (index, value) pairs from a Series. An equivalent of [`pandas.Series.items()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.items.html#pandas.Series.items)

**Comment by galipremsagar** [comment]
Doing this(iteration) on GPUs would be inefficient(super-slow), you could do `Series.to_pandas().items()` alternately if `Series.items` is what something you are looking for. Let us know if this solves what you are trying to achieve.

**Comment by think-high** [comment]
Sure, I will see alternative solutions then. Is there any other way to get the list of index and values of a GPU array without getting it back to primary memory?

**Comment by galipremsagar** [comment]
To perform iteration you will need to copy data to host memory. (do `.to_pandas`). If you are looking for doing something like this, you could also do this:

```python
>>> s = cudf.Series([10, 20, 30], index=['a', 'b', 'c'])
>>> for i in range(len(s)):print(s.index[i], s.iloc[i])
... 
a 10
b 20
c 30
```

But again each lookup in iteration is also equivalent to copying element to host memory from device memory. Instead we'd recommend using `Series.to_pandas().items()`

**Comment by think-high** [comment]
Perfect. Thanks a lot for explaining.
