### ISSUE TITLE
Cudf for cuda 11

### ISSUE THREAD

**Issue by Hannan-Naseem** [rapidsai/cudf#5852]
Hello there, 
I want to know if cudf for cuda 10.x is compatible with cuda 11x.
If not, what is the alternative?
If yes, how to install or modify it?

**Comment by kkraus14** [comment]
Hi @Hannan-Naseem, we are planning to support CUDA 11 for the 0.15 release and will begin publishing CUDA 11 nightly builds of 0.15 in the very near future.

If you're looking to build from source yourself, libcudf should support CUDA 11 in `branch-0.15` today.

**Comment by Hannan-Naseem** [comment]
Okay, Thank you @kkraus14
