### ISSUE TITLE
CUDA_RT_CALL macro should not call exit()

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#587]
The CUDA_RT_CALL macro in src/hash-join/concurrent_unordered_multimap.h calls exit(1) when an error is encountered. This could lead to memory leaks since this gives no opportunity to clean up memory. Instead of exiting, the macro should propagate the error (return an error, or throw, as appropriate).

**Comment by kkraus14** [comment]
@jrhemstad is this resolved?

**Comment by jrhemstad** [comment]
Not yet, no. The transition to using exceptions will help resolve this though.

**Comment by kkraus14** [comment]
@jrhemstad is this resolved now? 😁

**Comment by seunghwak** [comment]
Based on the above descriptions and the comment below,

https://github.com/rapidsai/cudf/blob/358bfaf1b3a722e8fbfd660d2cc3e36a6cfb485e/cpp/src/hash/helper_functions.cuh#L49

It seems like just replacing CUDA_RT_CALL with CUDA_TRY will fix this issue, I will work on this, but please let me know if you have any concerns on this approach.

**Comment by jrhemstad** [comment]
> It seems like just replacing CUDA_RT_CALL with CUDA_TRY will fix this issue, I will work on this, but please let me know if you have any concerns on this approach.

Yep, that works. Thanks.
