### ISSUE TITLE
[BUG] Incorrect values with read_orc

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#5892]
**Describe the bug**
Getting a difference in values when reading a file with `cudf.read_orc` vs `pd.read_orc / pyarrow.orc`

**Steps/Code to reproduce bug**
```python
import cudf
df = cudf.read_orc("orc_mismatch.orc")
df._col8.value_counts()

1.166878e-02     99677
1.166878e+16         6
4.829986e-320        1
Name: _col8, dtype: int32

df._col8.dtype
dtype('float64')
```

**Expected behavior**
```python
import pandas as pd
df = pd.read_orc("orc_mismatch.orc")
df._col8.value_counts()

0.011668778935185185    99684
Name: _col8, dtype: int64

df._col8.dtype
dtype('O')
```

**Environment overview (please complete the following information)**
 - Environment location: Baremetal 
 - Method of cuDF install: conda

**Environment details**
Nightly from Aug7

**Additional context**
Link to data: [orc_mismatch.orc.zip](https://github.com/rapidsai/cudf/files/5044005/orc_mismatch.orc.zip)

Original type `_col8` as interpreted by PyArrow  is `decimal`

```python
from pyarrow import orc

a = orc.ORCFile("orc_mismatch.orc")
a.schema

_col0: int32
_col8: decimal(38, 18)
```
<details>
<summary>Here are the statistics</summary>
<pre>
$ orc-statistics orc_mismatch.orc

*** Column 0 ***
Column has 99684 values and has null value: no

*** Column 1 ***
Data type: Integer
Values: 99684
Has null: no
Minimum: 1
Maximum: 7326
Sum: 230857068

*** Column 2 ***
Data type: Decimal
Values: 99684
Has null: no
Minimum: 0.011668778935185185
Maximum: 0.011668778935185185
Sum: 1163.19055937499998154

File orc_mismatch.orc has 1 stripes
*** Stripe 0 ***

--- Column 0 ---
Column has 99684 values and has null value: no

--- Column 1 ---
Data type: Integer
Values: 99684
Has null: no
Minimum: 1
Maximum: 7326
Sum: 230857068

--- Column 2 ---
Data type: Decimal
Values: 99684
Has null: no
Minimum: 0.011668778935185185
Maximum: 0.011668778935185185
Sum: 1163.19055937499998154
</pre>
</details>

cc: @mikechenfu Thanks for pointing out the issue! 😃

**Comment by williamBlazing** [comment]
When will this issue be addressed? The reason this is of interest to us (BlazingSQL) is that we have some queries in our End to end tests that run in gpuCI that when they use ORC, they fail sporadically and we are hoping that fixing this issue will resolve that for us. Right now we are checking manually the results of all gpuCI test runs because we do have these random ORC failures.

**Comment by kkraus14** [comment]
@williamBlazing it's being investigated now.
