### ISSUE TITLE
[BUG]thrust::system::system_error what():  parallel_for failed: invalid configuration argument

### ISSUE THREAD

**Issue by tqslj2** [rapidsai/cudf#5897]
```
import cudf
from cudf import io
import matplotlib.pyplot as plt
from matplotlib import rcParams as rcp
import numpy as np
import pandas as pd
import time

# Set the variables
data_path = './rapids/'

# File names to use as input are:
# MICROBIOLOGYEVENTS.csv, MICROBIOLOGYEVENTS_5_Million.csv, MICROBIOLOGYEVENTS_10_Million.csv, 
# MICROBIOLOGYEVENTS_20_Million.csv, MICROBIOLOGYEVENTS_40_Million.csv

input_file_name="MICROBIOLOGYEVENTS_40_Million.csv"

# Specify the column names for the input file
col_names = ['ROW_ID','SUBJECT_ID','HADM_ID','CHARTDATE','CHARTTIME','SPEC_ITEMID',
             'SPEC_TYPE_DESC','ORG_ITEMID','ORG_NAME','ISOLATE_NUM','AB_ITEMID','AB_NAME',
             'DILUTION_TEXT','DILUTION_COMPARISON','DILUTION_VALUE','INTERPRETATION']

# Column types have to be set for gdf.  It does not automatically figure them out like Pandas does
col_types = ['int', 'int', 'int', 'str', 'str', 'int', 'str', 'int', 'str', 'int', 'int', 'str', 'str', 
             'str', 'float', 'str']

# Create the CUDA data frame
MICROBIOLOGYEVENTS_gdf = cudf.read_csv(str(data_path +input_file_name), delimiter=',',  
                                       names=col_names, dtype=col_types, skiprows=1)
```

when i use the code above to load a big csv file, i got a issue :
terminate called after throwing an instance of 'thrust::system::system_error'
what():  parallel_for failed: invalid configuration argument

this file is just 4G, when i use a smaller file who is smaller than 2G, evething is ok, that makes me quite confused , i am wondering is there a size control variable for cuda ?

i am using the container rapidsai-dev:0.14-cuda10.0-devel-ubuntu16.04-py3.6 and this is my gpu information ：

 Mon Aug 10 05:53:49 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   29C    P0    24W / 250W |      0MiB / 32480MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+---------nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130
--------------------------------------------------------------------+
anyone have met this before? thanks !!

**Comment by harrism** [comment]
Thanks for filing an issue. Is it possible to get an example of the data files you are loading?

**Comment by tqslj2** [comment]
yes, this is the original small csv file ,and i just duplicate it for several times.

[MICROBIOLOGYEVENTS.zip](https://github.com/rapidsai/cudf/files/5049424/MICROBIOLOGYEVENTS.zip)

**Comment by vuule** [comment]
Reading the 16x concatenated file (1.1GB) locally consumes up to 5.3GB of device memory. So reading your 4GB file should take around 20GB (out of 32GB you have available). This seems excessive, but not enough to cause an OOM error.
Still, the error really looks like an OOM issue.
@tqslj2 can you please run 
`nvidia-smi --query-gpu=timestamp,utilization.memory,memory.total,memory.free,memory.used --format=csv -l 1` 
in a separate terminal while you're running the script and post the log.

**Comment by tqslj2** [comment]
timestamp, utilization.memory [%], memory.total [MiB], memory.free [MiB], memory.used [MiB]
2020/08/13 08:41:26.178, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:41:27.179, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:41:28.179, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:41:29.180, 0 %, 32480 MiB, 32469 MiB, 11 MiB
2020/08/13 08:41:30.180, 0 %, 32480 MiB, 32469 MiB, 11 MiB
2020/08/13 08:41:31.181, 0 %, 32480 MiB, 31990 MiB, 490 MiB
2020/08/13 08:41:32.181, 0 %, 32480 MiB, 31768 MiB, 712 MiB
2020/08/13 08:41:33.181, 0 %, 32480 MiB, 31620 MiB, 860 MiB
2020/08/13 08:41:34.182, 0 %, 32480 MiB, 31346 MiB, 1134 MiB
2020/08/13 08:41:35.182, 1 %, 32480 MiB, 30322 MiB, 2158 MiB
2020/08/13 08:41:36.183, 0 %, 32480 MiB, 30798 MiB, 1682 MiB
2020/08/13 08:41:37.183, 0 %, 32480 MiB, 30798 MiB, 1682 MiB
2020/08/13 08:41:38.183, 0 %, 32480 MiB, 30798 MiB, 1682 MiB
2020/08/13 08:41:39.184, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:40.184, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:41.184, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:42.185, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:43.185, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:44.186, 0 %, 32480 MiB, 29700 MiB, 2780 MiB
2020/08/13 08:41:45.186, 3 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:46.187, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:47.187, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:48.187, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:49.188, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:50.188, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:51.189, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:52.189, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:53.190, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:54.190, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:55.190, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:56.191, 0 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:57.191, 12 %, 32480 MiB, 27506 MiB, 4974 MiB
2020/08/13 08:41:58.192, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:41:59.192, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:42:00.192, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:42:01.193, 0 %, 32480 MiB, 32480 MiB, 0 MiB
2020/08/13 08:42:02.193, 0 %, 32480 MiB, 32480 MiB, 0 MiB
------------------------------------------------------------------------------------------------------------------------------

yes, it's a lit bit weird, there is a time that the gpu utilization jumped into 12% and then the error above just occurred.

**Comment by vuule** [comment]
Thank you for posting the results!
The memory usage is much lower than expected. It doesn't seem that this is an OOM issue. 
I'll need to repro the issue to triage further.

**Comment by vuule** [comment]
I don't repro the issue after concatenating the shared file 66 times to get a (41693981, 16) table.
The memory usage peaks at roughly 19GB and parsing is successful.

>  i am using the container rapidsai-dev:0.14-cuda10.0-devel-ubuntu16.04-py3.6

@tqslj2 can you please try running the same script with a newer build?

**Comment by tqslj2** [comment]
excuse me for a little bit late to see your message and thanks a lot for your solution !! i will try it

**Comment by harrism** [comment]
No answer from the requester in 6 months. Closing.
