### ISSUE TITLE
Cases and typechecks to handle int16/GDF_INT16 missing in some places 

### ISSUE THREAD

**Issue by yashv28** [rapidsai/cudf#591]
Eg - 
source files in **src/** directory
tests in **python/tests/**
**include/gdf/cffi/functions.h**

Maybe even in [PyGDF](https://github.com/gpuopenanalytics/pygdf)

**Comment by harrism** [comment]
Can you be more specific with links to specific lines of code? (PyGDF is superseded by cuDF.)

**Comment by jrhemstad** [comment]
This was related to very old code in the join implementation and no longer relevant.
