### ISSUE TITLE
[BUG] A data buffer is cast into a type with a different layout

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#5916]
A device array containing objects of type `thrust::pair<const char*, size_type>` is cast to `nvstrdesc_s`  using `reinterpret_cast`. These two types are not guaranteed to have the same memory layout. 
The code works, but it's not guaranteed to work correctly on all compilers/platforms.

Observed the issue in ORC and Parquet readers.

**Comment by harrism** [comment]
@vuule can you add a link to the problem code?

**Comment by devavret** [comment]
Can this be remedied by the suggestion in #5682 . Essentially doing away with `nvstrdesc`

**Comment by vuule** [comment]
Thanks @devavret . Assigned to you since the other issue is already on you.

**Comment by vuule** [comment]
Issue still relevant.

**Comment by vyasr** [comment]
This was resolved in https://github.com/rapidsai/cudf/pull/7841
