### ISSUE TITLE
gdf_column currently not able to support more complex data types 

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#592]
The current implementation of gdf_column contains its data type as an enum, which means it cannot fully describe more complex data types such as a decimal or timestamp.
Decimal requires to also describe the scale and precision while timestamp also requires at least the resolution (seconds, miliseconds, microseconds or nanoseconds) of the timestamp.

The way Apache Arrow handles this is with a DataType class which has in turn a vector or Fields which in turn has KeyValueMetadata and also a DataType, all this allowing for nested datatypes. This may be more complex than what gdf_column needs (unless we need support for nested datatypes).

I propose something in between, with a struct describing a datatype, with its current enum, but also adding the ability to have key value pairs for additional descriptors of that datatype enum.

**Comment by kkraus14** [comment]
Going to close this as it was resolved.
