### ISSUE TITLE
[BUG] cudf.concat error due to index unmatch

### ISSUE THREAD

**Issue by KazukiOnodera** [rapidsai/cudf#5923]
I’m reporting cudf.concat behavior. Please take a look at attached pdf. (My cudf version is 0.15.0a+3198.g1f41adf16)
1. In cell 4, the error was caused due to index unmatch, so cdf.sort_index can solve the error. But I do think cudf.concat should handle not sorted index cdf.
2. In cell 7, the error was caused due to index unmatch as well, but same index doesn’t exist. In this case, I propose that cudf.concat returns like cell 8.

[cudf.concat.pdf](https://github.com/rapidsai/cudf/files/5057363/cudf.concat.pdf)

**Comment by kkraus14** [comment]
@galipremsagar can you tackle this for 0.15?
