### ISSUE TITLE
[BUG] Boolean comparision b/w null datetime columns leads to null

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#5937]
**Describe the bug**
Boolean comparison b/w null DateTime columns leads to null (divergence with pandas)

**Steps/Code to reproduce bug**
```python

s_1 = cudf.Series(data=[None,np.datetime64('2020-01-01')],dtype='datetime64[ns]')
s_2 = cudf.Series(data=[None,np.datetime64('2020-01-01')],dtype='datetime64[ns]')
s_1==s_2

```
```python
0    <NA>
1    True
dtype: bool
```

**Expected behavior**
```python

import pandas as pd
s_1 = pd.Series(data=[None,np.datetime64('2020-01-01')],dtype='datetime64[ns]')
s_2 = pd.Series(data=[None,np.datetime64('2020-01-01')],dtype='datetime64[ns]')
s_1==s_2
```
```python

0    False
1     True
dtype: bool
```

**Environment overview (please complete the following information)**
Cudf-0.16 Source build  (Commit:https://github.com/rapidsai/cudf/commit/3a04496cf051e360486d86c67f6ff81e90bbad95)

**Comment by kkraus14** [comment]
This is not a bug, we have just started having proper null propagation behavior instead of following `NaN` behavior. `null == null` is expected to return `null`.
