### ISSUE TITLE
[FEA] cudf.crosstab

### ISSUE THREAD

**Issue by KazukiOnodera** [rapidsai/cudf#5944]
I often use this method, so it would be awesome if cudf can handle this
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html

**Comment by miguelusque** [comment]
Hi1 This feature would be a very nice one to have. Thank you for considering it!

**Comment by rafatsiddiqui9** [comment]
Hi,

I am working on the Amex default prediction competition dataset and really wanted to use crosstab feature. Can you kindly consider this to be included in future releases?

**Comment by shaswat-indian** [comment]
I'm working on this issue.

**Comment by galipremsagar** [comment]
Thanks @shaswat-indian, assigned it to you.
