### ISSUE TITLE
[FEA] Remaining dictionary column work in libcudf

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#5963]
This issue attempts to outline the known remaining work to enable column type DICTIONARY. These items are meant to be fulfilled with multiple PRs.

References to other open dictionary issues:
- #3535 This lists some of the original requirements for dictionary column
- #5576 This describes converting dictionary to use only unsigned integers for the indices

I did a search for `dictionary32` to find all the places where specialization was added to libcudf to simply throw an exception as a place-holder. Here is a list of those APIs (in no particular order):

- [x] [`cudf::reduction::detail::reduce`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/include/cudf/detail/reduction.cuh#L141)
- [x] [`cudf::make_column_from_scalar`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/column/column_factories.cpp#L182)
- [x] [`cudf::copy_range`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/copying/copy_range.cu#L156)
- [x] [`cudf::scatter` scalar](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/copying/scatter.cu#L174)
- [x] [`cudf::merge`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/merge/merge.cu#L340)
- [x] [`cudf::clamp`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/replace/clamp.cu#L226)
- [x] [`cudf::contains`](https://github.com/rapidsai/cudf/blob/79280864b99e6af2710d5dfcc93d82cd1a818f23/cpp/src/search/search.cu#L178)

There are also other libcudf APIs that do not have the place-holder code that will likely need dictionary columns specialization in some way:

- [ ] binaryops
- [x] unaryops
- [x] groupby
- [x] join (keys match)
- [x] minmax
- [x] quantile
- [x] replace
- [x] replace_nulls
- [x] rolling
- [x] ~~scan~~ (not supported)
- [x] upper_bound, lower_bound  (keys match)

The '(keys match)' items mean these could just work with the indices if the two input columns had matching keys.
Most of the other libcudf APIs use `gather()` which is already implemented for dictionary.

Also cuIO in general does not support the current dictionary type. The writers, at the very least, could call `cudf::dictionary::decode()` to convert them to a non-dictionary column before writing. Likewise, the readers could call `cudf::dictionary::encode()` after the initial column is created.

Lastly, I have a prototype of an index-type normalizing iterator which I hope could be useful for managing the indices. This would allow the child indices column to be any (unsigned) integer type without requiring adding DICTIONARY8 or DICTIONARY16 types to libcudf.

**Comment by kkraus14** [comment]
> Lastly, I have a prototype of an index-type normalizing iterator which I hope could be useful for managing the indices. This would allow the child indices column to be any (unsigned) integer type without requiring adding DICTIONARY8 or DICTIONARY16 types to libcudf.

This is super important for cuDF Python to be able to adopt libcudf dictionary types. Thank you for continuing to think about this problem 😄.

**Comment by davidwendt** [comment]
I'm starting to see some interesting patterns here that were not covered in the requirements discussion #3535.

When a cudf API accepts two columns like in `copy_range`, `merge`, `contains`, `replace`, etc both columns are required to have the same type. This makes sense since the values are combined to make a new column. For dictionaries, this strictly means both columns must have the same key type.

Furthermore, if both dictionary columns have identical keys then APIs like `contains`, `lower_bound` and `upper_bound` can work strictly with the indices since their outputs are bool (or integer) columns regardless of the input types. So, much of the specialization logic for `scatter`, `replace`, `contains`, etc has been to first rebuild both input dictionary columns so they have matching keys. Then, the resulting dictionary is the new matched keys and the output of running the original operation on just the two indices of the matched columns. This could be a waste if the dictionary keys already matched. We could add a check to see if the keys matched first but this would be wasteful too if the keys already matched. Should we just make it a requirement to the caller to ensure the keys match in these cases?

Also, should these APIs actually require both columns be DICTIONARY type? For example, `fill` and `scatter-scalar` only require the `scalar` argument to match the keys type. It seems reasonable that I would want to scatter strings column into a dictionary column for example. Or perform a search within a dictionary column using values from a non-dictionary column (or vice versa). Although, it may be more efficient to convert the non-dictionary to a dictionary with matching keys before performing the operation since the overall code logic may be equivalent.

@kkraus14 @harrism @jrhemstad

**Comment by kkraus14** [comment]
> We could add a check to see if the keys matched first but this would be wasteful too if the keys already matched.

Does a dictionary column allow using a shared pointer or something similar to the keys? Could we do a pointer equivalence check instead of having to do a full equality check?

> Should we just make it a requirement to the caller to ensure the keys match in these cases?

That sounds like a huge footgun from my perspective. Users will end up calling APIs with mismatched dictionaries and getting incorrect results back as opposed to erroring isn't acceptable in my mind.

> Also, should these APIs actually require both columns be DICTIONARY type? For example, fill and scatter-scalar only require the scalar argument to match the keys type. It seems reasonable that I would want to scatter strings column into a dictionary column for example. Or perform a search within a dictionary column using values from a non-dictionary column (or vice versa). Although, it may be more efficient to convert the non-dictionary to a dictionary with matching keys before performing the operation since the overall code logic may be equivalent.

Yes, the natural user experience would be to provide a scalar or column of the type of the keys, but ideally we can support the paths of key-type, equal dictionary-type, and unequal dictionary-type columns and scalars.

**Comment by harrism** [comment]
@davidwendt are the checklists up to date in the description?

**Comment by davidwendt** [comment]
> @davidwendt are the checklists up to date in the description?

Yes. 
I'm not sure binary-ops makes sense for dictionary though maybe there are a few ops that do.
And I was waiting for the rolling-window implementation to settle.
There may have been some new APIs added that probably need to consider dictionary as well.
And I'm sure that whenever the Python integration starts it will find issues in the checked items above as well.

**Comment by davidwendt** [comment]
Since only binary-ops is left and dictionary support may not make sense here, I'm going to close this issue. We can open a separate feature request(s) if the cudf team thinks dictionary column support should be added for specific in binary-ops.
