### ISSUE TITLE
[FEA] Additional formats support in `from_timestamps` libcudf API

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#5991]
**Is your feature request related to a problem? Please describe.**
`from_timestamps` currently supports following format specifiers:
```c++
"%Y,%y,%m,%d,%H,%I,%p,%M,%S,%f,%z,%Z"
```

There are few more format specifiers which python standard library supports: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

The format specifiers which I'd like to request support from libcudf similar to the above standard library are:
```python

 %a
 %A
 %w
 %b
 %B
 %U
 %W
 %c
 %x
 %X
 %G
 %u
 %V
```

**Additional context**
This would be helpful for api's such as `Series.dt.strftime` which uses standard library formats: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.strftime.html

**Comment by karthikeyann** [comment]
are these formats not possible to achieve with combination of currently-supported specifiers?

**Comment by davidwendt** [comment]
The following specifiers are locale-dependent: `%a, %A, %b, %B, %c, %x, %X` and the first 5 of these require locale-specific names for months (e.g. January, Jan, December, Dezember, Dez) and weekdays (e.g. Sunday, Sonntag, Sat, Sam). These strings are not available from device code and would have to be passed in from the Python or C++ layer. Further, the `%c` and `%x` specifiers impose locale-specific separators and order.

The remaining listed specifiers are all numeric, locale independent values.
Reference: https://docs.python.org/3.7/library/datetime.html#strftime-and-strptime-behavior

**Comment by jrhemstad** [comment]
Keep in mind that libcudf should stick with the standard C++ format specifiers for time_points specified here: https://en.cppreference.com/w/cpp/chrono/system_clock/formatter

When these don't align with Pandas, the translation from Pandas specifies to C++ specifies should be made at the Python layer.

**Comment by davidwendt** [comment]
The PR #9047 includes support for most of these specifiers.

The `%u, %w, %U, %W, %V, %G` output numbers and are supported directly.

The `%a, %A, %b, %B` specifiers require passing in the string names for the weekdays and months as appropriate using the new optional `names` parameter. This is a `strings_column_view` whose structure is defined in the [doxygen comment for cudf::strings::from_timestamps](https://github.com/rapidsai/cudf/blob/branch-21.10/cpp/include/cudf/strings/convert/convert_datetime.hpp#L169-L212). The comment includes C++ sample code for retrieving the weekday and month names from the current locale using std library functions. There is an equivalent Python library to retrieve these strings as well. The same `nl_langinfo` ids can be used as described in the C++ example.
```
import locale
from locale import nl_langinfo

names = [nl_langinfo(locale.AM_STR), nl_langinfo(locale.PM_STR),
         nl_langinfo(locale.DAY_1), nl_langinfo(locale.DAY_2), nl_langinfo(locale.DAY_3),
         nl_langinfo(locale.DAY_4), nl_langinfo(locale.DAY_5), nl_langinfo(locale.DAY_6),
         nl_langinfo(locale.DAY_7), nl_langinfo(locale.ABDAY_1), nl_langinfo(locale.ABDAY_2),
         nl_langinfo(locale.ABDAY_3), nl_langinfo(locale.ABDAY_4), nl_langinfo(locale.ABDAY_5),
         nl_langinfo(locale.ABDAY_6), nl_langinfo(locale.ABDAY_7),
         nl_langinfo(locale.MON_1), nl_langinfo(locale.MON_2), nl_langinfo(locale.MON_3),
         nl_langinfo(locale.MON_4), nl_langinfo(locale.MON_5), nl_langinfo(locale.MON_6),
         nl_langinfo(locale.MON_7), nl_langinfo(locale.MON_8), nl_langinfo(locale.MON_9),
         nl_langinfo(locale.MON_10), nl_langinfo(locale.MON_11), nl_langinfo(locale.MON_12),
         nl_langinfo(locale.ABMON_1), nl_langinfo(locale.ABMON_2), nl_langinfo(locale.ABMON_3),
         nl_langinfo(locale.ABMON_4), nl_langinfo(locale.ABMON_5), nl_langinfo(locale.ABMON_6),
         nl_langinfo(locale.ABMON_7), nl_langinfo(locale.ABMON_8), nl_langinfo(locale.ABMON_9),
         nl_langinfo(locale.ABMON_10), nl_langinfo(locale.ABMON_11), nl_langinfo(locale.ABMON_12)]

print(names)

['AM', 'PM', 
'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 
'Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat',
'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 
'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
```

The `%x, %X, and %c` format specifiers are general date/time patterns and are not supported directly. But the `nl_langinfo` can be used to retrieve the corresponding format. 
- `%x` can be replaced with `nl_langinfo(D_FMT)` (e.g. returns `%m/%d/%y`)
- `%X` can be replaced with `nl_langinfo(T_FMT)` (e.g. returns `%H:%M%S`)
- `%c` can be replaced with `nl_langinfo(D_T_FMT)` (e.g. returns `%a %b %d %H:%M:%S %Y`)

**Comment by marlenezw** [comment]
Thanks for the work on this @davidwendt, this was really needed!

**Comment by jrhemstad** [comment]
Can this issue be closed?

**Comment by davidwendt** [comment]
I was keeping it open for the python/cython work to be completed to pass the langinfo to the new parameter added to the `from_timestamps` API.

**Comment by marlenezw** [comment]
I'm working on this now. It should be ready to close once #9169 is done, which should be soon!

**Comment by galipremsagar** [comment]
Yes, closing this issue.
