### ISSUE TITLE
[FEA] how to make a for by data frame? on pandas I use df.iterrows and on cudf, how would I do it?

### ISSUE THREAD

**Issue by thiago2034** [rapidsai/cudf#5997]
I'm doing my Final Paper based in Cudf, showing the difference in performance between pandas and cudf, but I need one for by data frame, on pandas I use df.iterrows and on cudf, how would I do it? in pandas is: for index, row in df.iterrows():

**Comment by kkraus14** [comment]
@thiago2034 if you're using `df.iterrows()` then you're iterating via the CPU in Python which by its nature won't benefit from GPU acceleration, so we've chosen not to implement this function in cuDF, but instead throw an exception indicating to explicitly copy to host via `.to_arrow()` or `.to_pandas()` before using iteration based methods.

Do you have a specific use case that you're looking to use `iterrows` for?

**Comment by thiago2034** [comment]
I don't have any specific reason, I just tested the different ways of doing it for pandas and saw that iterrows is the one that performs the most, do you have any recommendations for the cudf? I tried using: for i in range (len (df)): where df is a dataframe made in cudf, but I saw that in performance it is very slow, do you have any suggestions for this case?

**Comment by karthikeyann** [comment]
@thiago2034 Try `Dataframe.apply_rows` of user defined functions (UDF)
https://docs.rapids.ai/api/cudf/stable/guide-to-udfs.html#DataFrame-UDFs

**Comment by kkraus14** [comment]
Alternatively, depending on what you're trying to do in the loop, ideally you could accomplish it using built-in cuDF APIs. Can you share what's inside your for loop?

**Comment by kkraus14** [comment]
Closing as the question has been answered.
