### ISSUE TITLE
[FEA] Implement data generators for different data profiles

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#6000]
cuIO benchmarks and fuzz tests need to cover data with different characteristics (cardinality, null %, nesting levels). Current [data generators ](https://github.com/rapidsai/cudf/blob/branch-0.15/cpp/benchmarks/common/generate_benchmark_input.hpp) do not have options to control the data characteristics.

In addition, for fuzz testing it's essential to have a way to replay the test. Generators should also take a seed and deterministically generate the data from it.

- [ ] Expand the generators to utilize different data profile parameters.
- [ ] Use an integral seed to generate the output.
- [ ] Design an XML format for the data parameters.
- [ ] Implement a parser to convert between the XML and parameters.

High priority parameters:

- Number of unique elements (cardinality) - determines how well data can be represented as a dictionary.
- Average number of repeated adjacent elements - determines how well RLE encoding applies to the data.
- Percentage of null elements.
- Average length - for variable width types.
- Average nesting level - for nested data types.

Lower priority:
- Value distribution (Normal, uniform).
- Value range.

**Comment by calebwin** [comment]
Regarding C++ vs Python for data generation, I've fixed a performance issue with my Python-based dataset generator. Now, about 512 MB of low-entropy (sampled from 128 strings) string data can be generated in ~30s and ~50s for 512 MB of integers.

Further profiling is needed (the changes that introduce this dataset generator are in #5843) but based on numbers Vukasin and I had yesterday, the relative speedup of C++ compared to Python should be around 4x-8x, not 40x, faster.

**Comment by harrism** [comment]
I wonder if there are core parts of the data generation that can be accelerated in C++ rather than writing the whole thing in C++, to achieve performance parity without having to write the whole thing in C++...

**Comment by vuule** [comment]
> Now, about 512 MB of low-entropy (sampled from 128 strings) string data can be generated in ~30s and ~50s for 512 MB of integers.

Wow, a huge leap! Is this with low cardinality? would you mind gathering the timings with high cardinality? I mostly wonder how long it would take to generate many different strings.

**Comment by vuule** [comment]
> I wonder if there are core parts of the data generation that can be accelerated in C++ rather than writing the whole thing in C++, to achieve performance parity without having to write the whole thing in C++...

Maybe we can do simple types in C++, and rest in Python. I need to figure out string generation before giving a more conclusive answer.

We can also use CUDA very efficiently in some cases :)

**Comment by vuule** [comment]
@galipremsagar is looking into fuzz testing now, so we will soon know how data generators fit in there. 
I expect that his research into fuzz testing will help guide some of the decisions here.

**Comment by calebwin** [comment]
I just modified my dataset generator to parallelize across columns. Again, I haven't done extensive profiling but I'm seeing ~15s for ~512 MB of string data with 16 columns where each column is sampled from a set (unique to each column) of 400 randomly selected cities (using Mimesis) where each column is randomly masked for 5% null rate.

> would you mind gathering the timings with high cardinality? I mostly wonder how long it would take to generate many different strings.

With the same config as for string data, except with random integers and no cardinality specified (a new random integer for each value gnerated), I have ~35s.
