### ISSUE TITLE
[FEA] Add parquet support

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#601]
**Is your feature request related to a problem? Please describe.**

I would like to be able to read parquet files from cudf.

This is obviously a large ask.  FWIW I would welcome partial functionality being released even if it is incomplete.

For dask-cudf it would also be especially useful to be able to specify particular row groups and columns from within a parquet file like the following:

    df = cudf.read_parquet('myfile.parquet', columns=['x', 'y'], row_groups=[4, 5, 6])

**Comment by datametrician** [comment]
I believe blazing is pretty far along in this and should be in cuIO soon.

**Comment by kkraus14** [comment]
CPU only version added in #893. I think this should suffice for the dask needs and we can improve performance with a GPU-accelerated reader in the future.
