### ISSUE TITLE
[FEA] consider not to read entire file as meta when setting chunksize to None

### ISSUE THREAD

**Issue by mengdong** [rapidsai/cudf#6010]
**Is your feature request related to a problem? Please describe.**
Per https://github.com/rapidsai/cudf/blob/0b7ad98c7c2d23e989d57ac47481f5ca9873b58c/python/dask_cudf/dask_cudf/io/csv.py#L109, meta is generated by reading an entire CSV file, when the file size is large, this will lead to OOM

**Describe the solution you'd like**
No to read the entire CSV file.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by kkraus14** [comment]
cc @rjzamora is this how dask upstream does it? Should we pass a byte range of some form instead?

**Comment by rjzamora** [comment]
>cc @rjzamora is this how dask upstream does it? Should we pass a byte range of some form instead?

Yes, this is what dask does, and also what we do in the typical case (vie dask).  We are only doing the full-file read for `meta` when the user specifies `chunksize=None` (or when the csv files are compressed).  It is certainly possible to avoid the full file read if the file is not compressed.
