### ISSUE TITLE
import cudf is throwing error (ImportError: cannot import name 'numpy_support')

### ISSUE THREAD

**Issue by arghyakusumdas6163** [rapidsai/cudf#6014]
My cudf installation was OK. But, I am getting the following error when importing cudf:

>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/__init__.py", line 7, in <module>
    from cudf import core, datasets
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/core/column/__init__.py", line 1, in <module>
    from cudf.core.column.categorical import CategoricalColumn  # noqa: F401
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/core/column/categorical.py", line 11, in <module>
    import cudf._libxx as libcudfxx
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/_libxx/__init__.py", line 5, in <module>
    from . import (
  File "cudf/_libxx/aggregation.pxd", line 9, in init cudf._libxx.reduce
  File "cudf/_libxx/aggregation.pyx", line 11, in init cudf._libxx.aggregation
  File "/home/adas5/.conda/envs/argo_3.6/lib/python3.6/site-packages/cudf/utils/cudautils.py", line 7, in <module>
    from numba import cuda, numpy_support
ImportError: cannot import name 'numpy_support'

GPU configuration is as follows:
$ nvidia-smi
Mon Aug 17 14:51:32 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  On   | 00000000:87:00.0 Off |                    0 |
| N/A   32C    P0    26W / 250W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by galipremsagar** [comment]
This has been fixed by https://github.com/rapidsai/cudf/pull/5033. 

Please feel free to reopen this issue if it persists on a newer version of `cudf`. This has been fixed in `0.14`.

**Comment by arghyakusumdas6163** [comment]
Thanks. Changing the version to 0.14 fixed the issue.

**Comment by soerendip** [comment]
Version of what  is meant here? There is cudf 0.8 and numba 0.51, both does not seem to be the right fit.

**Comment by kkraus14** [comment]
> Version of what is meant here? There is cudf 0.8 and numba 0.51, both does not seem to be the right fit.

cudf 0.8 is very old at this time where you'd need to upgrade it.

**Comment by soerendip** [comment]
Ok, it us better to install it with pip rather than with conda. With conda 0.8 was latest.

________________________________

**Comment by kkraus14** [comment]
> Ok, it us better to install it with pip rather than with conda. With conda 0.8 was latest.

The latest on conda should be 0.16. We do not publish builds on pip.
