### ISSUE TITLE
[BUG] DataFrame.sum() with axis=1 warning message should be displayed only when not supported datatype is used

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#6018]
**Describe the bug**
Hi! When using `DataFrame.sum(axis=1)`, the following warning message is displayed:

```
/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py:5367: UserWarning: Row-wise operations currently only support int, float, and bool dtypes.
  "Row-wise operations currently only support int, float, "
```
In the picture below, it can be seen that `sum()` is being calculated on int64 columns only. Therefore, I am not sure if the warning message should be displayed.

![image](https://user-images.githubusercontent.com/26169771/90474786-6227be00-e126-11ea-800e-f196849e1c8c.png)

**Steps/Code to reproduce bug**
Create a DataFrame with int64 columns only, and try to sum their values row by row.

**Expected behavior**
No warning message is displayed when int or float columns are used.

**Environment overview (please complete the following information)**
RAPIDS 0.15 nightly build.

**Comment by isVoid** [comment]
This seems like a quick fix. `_prepare_for_rowwise_op` should pop the warning when it detects the `common_dtype` is neither `np.number` or `np.bool`, and keep silence otherwise.
