### ISSUE TITLE
[FEA] Add 'transpose' parameter to 'from_dlpack' and 'to_dlpack' methods

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#6037]
**Is your feature request related to a problem? Please describe.**
When invoking `from_dlpack()` or `to_dlpack()`, there is a warning message which is always displayed:

> UserWarning: WARNING: cuDF to_dlpack() produces column-major (Fortran order) output. If the output tensor needs to be row major, transpose the output of this function.

I do not personally like that warning, because it is useful the first time you see it, but it is a bit disappointing when you are reminded the same thing every time you execute the code. I am aware that it can be disabled, but it adds extra code for something that looks like can be solved by just reading the documentation.

**Describe the solution you'd like**
Therefore, I think I have figured out an approach that would remove the need of displaying that message, and also would benefit the developer, by making use of a simpler API.

My proposal is to add an optional boolean parameter to those methods: 'transpose', which would indicate if the DataFrame/Series should be transposed before converting from/to dl_pack format.

Having an optional parameter would make that common pattern (transpose + convert from/to dl_pack) cleaner, and at the same time would facilitate to remove the warning described above.

What do you think?

Regards,
Miguel

**Comment by harrism** [comment]
Rather than a boolean parameter, why not have the user specify the order  the data is in (for from_dlpack()) or the order they want the data in (for to_dlpack())?  Then they don't have to know whether they need it transposed, just the order they have/need it in.

**Comment by harrism** [comment]
FWIW, the reason I didn't originally do something like this is because it required adding a dependency on another external library (cuBLAS) to libcudf. :)

**Comment by miguelusque** [comment]
> Rather than a Boolean parameter, why not have the user specify the order the data is in (for from_dlpack()) or the order they want the data in (for to_dlpack())? Then they don't have to know whether they need it transposed, just the order they have/need it in.

That completely makes senses to me.

**Comment by miguelusque** [comment]
Hi @harrism 

I was wondering if cuBLAS needed, considering the discussion in this link: https://github.com/rapidsai/cudf/issues/4322#issuecomment-610031899

It looks `cudf::transpose` is considerably faster than in the original implementation, so, maybe, cuBLAS is not needed anymore.

**Comment by harrism** [comment]
We could potentially use that, but it is likely to be a lot slower than a cuBLAS transpose.

**Comment by miguelusque** [comment]
Warning messages has been removed from code, and added to API documentation.

Closing this issue now.
