### ISSUE TITLE
[BUG] null keys in a join with null not equal causes performance problems

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#6052]
**Describe the bug**
Spark does not consider nulls to be equal as a part of a join.  Spark generally will filter out the nulls before they get to the join, but it does not guarantee in all cases that they will be removed before getting to the join.  If there are lots of nulls in a join nulls are not equal then the performance of the join is really bad.

From profiling we see that both building the table and probing the table are slow, but building the table is especially slow.  I speculate that when building the table that because nulls are not equal that lots of entries are added to the table, even though they will never evaluate as true when probing the table either.  Because of this there are lots and lots of hash collisions for both building and probing.

**Steps/Code to reproduce bug**
Just do a rather large join with nulls are not equal.  Then add in nulls and see how long it takes.  If you need me to I can provide some parquet files that show the error.  They are not proprietary or anything, just about 75MB so I don't want to just attach them to the issue.

This is related to https://github.com/NVIDIA/spark-rapids/issues/569

**Comment by jrhemstad** [comment]
I think in prior implementations, when `NULL != NULL` was specified, we'd build a mask by ANDing the bitmasks of all of the "on" columns and use that mask to determine if a given row should be inserted into the map. Or maybe that was in groupby. Anyways, we can probably do the same thing again.

**Comment by jrhemstad** [comment]
We already do the same optimization in groupby, so all the pieces exist to do the same thing for Join.

https://github.com/rapidsai/cudf/blob/855e735c07e14d11b8ef309d943e9a28c91e0698/cpp/src/groupby/hash/groupby.cu#L281

https://github.com/rapidsai/cudf/blob/855e735c07e14d11b8ef309d943e9a28c91e0698/cpp/src/groupby/hash/groupby_kernels.cuh#L60-L62

**Comment by revans2** [comment]
@jrhemstad Just want to let you know that we have a work around up for review (https://github.com/NVIDIA/spark-rapids/pull/594) so this is not super critical, but it is something that would be nice to have fixed.
