### ISSUE TITLE
[BUG] .str.stod() no longer works on a String column

### ISSUE THREAD

**Issue by drabastomek** [rapidsai/cudf#6070]
**Describe the bug**
I used `.stod()` to convert a string column to a decimal. However, this has stopped working on nightly 0.15.

**Steps/Code to reproduce bug**
Minimal example:

```
df = cudf.DataFrame([['0.01'], ['0.02']], columns=['string_column'])
df['string_column'].str.stod()
```

**Expected behavior**
A columns converted to decimal type.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

   - pull: `docker pull rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7`
   - run: 

```
docker run --gpus all -it -p 8888:8888 -p 8787:8787 -p 8786:8786 --name kdd_rapids \
	rapidsai/rapidsai-nightly:cuda10.2-runtime-ubuntu18.04-py3.7
```

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by galipremsagar** [comment]
`.stod` was not exposed via `.str.stod` as we recommend to use `astype` API because, though underlying we call the identical code-path(`stod`) but we have added additional validation if all the string values to be type-casted are capable/valid of being type-casted to float.

**Comment by drabastomek** [comment]
Makes sense! Thanks! Closing this bug.
