### ISSUE TITLE
[BUG] unbalanced files read by each dask worker by read_csv with dask_cudf

### ISSUE THREAD

**Issue by mengdong** [rapidsai/cudf#6074]
**Describe the bug**
unbalanced memory utilization observed when running uniformed 1GB csv files with dask_cudf

**Steps/Code to reproduce bug**
with repeated higgs csv dataset, do:
```
    colnames = ['label'] + ['feature-%02d' % i for i in range(1, 29)]
    df = dask_cudf.read_csv('/script/rapids/higgs_1g/*.csv',header=None, names=colnames, chunksize=None)
```
and should observe unbalanced GPU memory utilization when reading large amount of data

**Expected behavior**
when each file has the same size, we expect each worker to read same amount of files and hence utilize the same amount of GPU memory

**Environment overview (please complete the following information)**
docker rapidsai/rapidsai-nightly:cuda10.1-base-ubuntu18.04-py3.7 
4 T4 each in a separate docker container

**Environment details**
```
CONDA_SHLVL=1
WORLD_SIZE=2
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LD_LIBRARY_PATH=/opt/conda/envs/rapids/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64
CONDA_EXE=/opt/conda/bin/conda
GDAL_DATA=/opt/conda/envs/rapids/share/gdal
RAPIDS_DIR=/rapids
LESSCLOSE=/usr/bin/lesspipe %s %s
HOSTNAME=sys4028
OLDPWD=/script/rapids
CUDA_PATH=/opt/conda/envs/rapids
GSETTINGS_SCHEMA_DIR_CONDA_BACKUP=
CPL_ZIP_ENCODING=UTF-8
CONDA_PREFIX=/opt/conda/envs/rapids
NVIDIA_VISIBLE_DEVICES=1
_CE_M=
PROJ_LIB=/opt/conda/envs/rapids/share/proj
NCCL_VERSION=2.4.8
PWD=/script/rapids/cudf
HOME=/root
CONDA_PYTHON_EXE=/opt/conda/bin/python
DEBIAN_FRONTEND=noninteractive
_CE_CONDA=
GSETTINGS_SCHEMA_DIR=/opt/conda/envs/rapids/share/glib-2.0/schemas
PROJ_NETWORK=ON
CONDA_PROMPT_MODIFIER=(rapids) 
TERM=xterm
MASTER_ADDR=0.0.0.0
CUDA_PKG_VERSION=10-1=10.1.243-1
CUDA_VERSION=10.1.243
NVIDIA_DRIVER_CAPABILITIES=compute,utility
RANK=1
SHLVL=1
NVIDIA_REQUIRE_CUDA=cuda>=10.1 brand=tesla,driver>=384,driver<385 brand=tesla,driver>=396,driver<397 brand=tesla,driver>=410,driver<411
MASTER_PORT=2222
PATH=/opt/conda/envs/rapids/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
CONDA_DEFAULT_ENV=rapids
LESSOPEN=| /usr/bin/lesspipe %s
_=/usr/bin/printenv
```

**Additional context**
`df.map_partitions(len)` shows 48 partitions with same size (2200000), however still observe unbalanced GPU utilization.

**Comment by JohnZed** [comment]
@mengdong could you describe a little more about the imbalance you are seeing? Is that based on running nvidia-smi and looking at GPU occupancy % or based on GPU memory usage observed? 48 partitions with the same size seems like pretty fair balance overall.

**Comment by quasiben** [comment]
Based on what you first said it looks like the read_csv is perfectly balanced with partitions all with same size `2200000` . What is the "unbalanced GPU utilization` ?

**Comment by mengdong** [comment]
it is observed based on GPU memory usage.

**Comment by JohnZed** [comment]
Could you post statistics about the observed per-gpu memory usage observed?

**Comment by mengdong** [comment]
"""
-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.51.06    Driver Version: 450.51.06    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:04:00.0 Off |                    0 |
| N/A   40C    P0    25W /  70W |   9129MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            On   | 00000000:05:00.0 Off |                  Off |
| N/A   42C    P0    27W /  70W |   8120MiB / 16127MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            On   | 00000000:08:00.0 Off |                    0 |
| N/A   41C    P0    25W /  70W |   8120MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            On   | 00000000:09:00.0 Off |                    0 |
| N/A   45C    P0    27W /  70W |  11232MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla T4            On   | 00000000:84:00.0 Off |                    0 |
| N/A   29C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla T4            On   | 00000000:85:00.0 Off |                    0 |
| N/A   31C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla T4            On   | 00000000:88:00.0 Off |                  Off |
| N/A   31C    P8     9W /  70W |      0MiB / 16127MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla T4            On   | 00000000:89:00.0 Off |                    0 |
| N/A   31C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     47007      C   python                           1009MiB |
|    0   N/A  N/A     47517      C   ...da/envs/rapids/bin/python     8119MiB |
|    1   N/A  N/A     48005      C   ...da/envs/rapids/bin/python     8123MiB |
|    2   N/A  N/A     48002      C   ...da/envs/rapids/bin/python     8119MiB |
|    3   N/A  N/A     47998      C   ...da/envs/rapids/bin/python    11229MiB |
+-----------------------------------------------------------------------------+
"""

We run 1 scheduler, 4 dask-cuda-worker each with 1 thread, to read 48 GB higgs. The key to repro this is to clean the cache with `echo 2 > /proc/sys/vm/drop_caches`

**Comment by quasiben** [comment]
I'm still a little confused here.  Are you saying that after `read_csv` while the number of rows in each partition is equal the distribution of data (memory) is unequal across all GPUs ?

**Comment by mengdong** [comment]
yes. We have 48 partitions with the same number of rows, that doesn't mean each worker will process the same amount of partitions.

**Comment by rjzamora** [comment]
How are you creating your distributed cluster?  You seem to have reasonably balanced memory usage accross the first four devices, and zero across the others.  It doesn't look unusual for a LocalCUDACluster instance with four workers.

Note that using dask is different from an MPI-like code with explicit data decomposition between workers. The exact scheduling of data/tasks onto workers depends a lot on the specific code you are running - That said, I guess I would expect a stand-alone `read_csv` call to result in slightly-better balance (assuming you are following-up with `persist`).

**Comment by vyasr** [comment]
Closing as stale.
