### ISSUE TITLE
[QST] How double(fp64) and int64 was supported by cuDF by only using FP32 (and int32) cuda core ?

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/cudf#6084]
**What is your question?**
Running TPC-DS benchmark on rapids-0.2/cuDF-0.15,  when use DCGM to monitor the gpu activity， i only see FP32A， the FP64A always zero.
1.  does cuDF only use FP32 cuda core (not use FP64 cuda core)?  (NOTE: the data type is double in the benchmark)
2. how double type is supported by not using FP64 cuda core?
3. how int64 is supported? （because T4 only has int32 core, v100 maybe the same）
4. how can i monitor the usage of int cuda core (just as FP32A, FP64A, FP16A, ...) 

[47.dcgm.csv.txt](https://github.com/rapidsai/cudf/files/5121264/47.dcgm.csv.txt)

**Comment by harrism** [comment]
I have never used DCGM.  Libcudf uses fp64 arithmetic for fp64 data.  Libcudf uses int64 arithmetic for int64 data.

CUDA GPUs without int64 ALUs can still emulate int64 with multiple int32 instructions.

If you aren't seeing profiler data for fp64 and you are sure there are fp64 operations in the program, I suspect a profiler configuration problem.

**Comment by datametrician** [comment]
> because T4 only has int32 core,

If you're using a T4 you're emulating fp64. What GPU are you using?

**Comment by harrism** [comment]
> If you're using a T4 you're emulating fp64

T4 does not emulate fp64, it just has a lot fewer FP64 ALUs than (e.g.) V100 so its throughput is lower.

**Comment by kkraus14** [comment]
Closing as this is answered.
