### ISSUE TITLE
`gdf_reduce_optimal_output_size()` is a misnomer

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#610]
Our API has a function named `gdf_reduce_optimal_output_size()`. It does _not_ return an "optimal output size", it returns the amount of scratch space necessary for the the output of the first phase of cudf's two-phase reduction. It should be named appropriately.

**Comment by eyalroz** [comment]
I suggest: `gdf_reduction_get_intermediate_output_size()`

**Comment by thomcom** [comment]
I suggest `gdf_reduction_get_maximum_block_size`. Low priority. I'd approve a PR probably.

**Comment by eyalroz** [comment]
@thomcom : That name betrays an implementation detail... we do not commit to the intermediate result having the same size as a block of threads.

**Comment by jrhemstad** [comment]
I agree that the function is poorly named.

I believe that the best solution is to do away with it entirely and avoid doing a 2-step reduction. Instead, the implementation can be updated to use atomic operations to update the global sum with each block sum. 

That way there is no need to do an allocation to hold the intermediate results between the first and second phase, and therefore no need for this function at all.

**Comment by eyalroz** [comment]
@jrhemstad : I would be perfectly fine with doing away with two-phase reductions.

I was assuming there was some reason for the current implementation being what it is, and for this function being exposed. Can you verify that no such reason exists? I'll ask on our BlazingDB slack.

**Comment by jrhemstad** [comment]
This function's sole purpose is for allocating the temporary buffer space necessary for holding the intermediate reduction results of the first-phase of a 2-step reduction. 

I'm unaware of any reason to do a two-phase reduction. It could potentially be faster for very large inputs, but I believe it would be a wash compared to a block-sum & atomic implementation.

**Comment by eyalroz** [comment]
> ...I'm unaware...

I'm also unaware, I'm just saying we should make extra sure before removing stuff.

**Comment by harrism** [comment]
I looked into this when I was last updating the reduction code. I planned to eliminate two-pass reductions but it wasn't in the scope of the PR I was working on. 

My guess is that the reduction was written based on existing reduction examples and tutorials, which are based on early CUDA hardware that either didn't have atomics or had slow atomics. All GPU hardware supported by RAPIDS has fast atomics. As long as we perform one atomic per thread block we should be fast. A slowdown due to atomics would be a corner case for atomic-based single-pass reductions. Single-pass reductions would simplify the code and eliminate the API function this issue is discussing, so we should consider including it in the 0.6 release (February).

**Comment by kovaltan** [comment]
PL #1005 will be performed by single step reduction and `gdf_reduce_optimal_output_size()` will be removed in the PL.

**Comment by eyalroz** [comment]
@kovaltan : And does that happen in branch-0.6?

**Comment by kovaltan** [comment]
It will be at branch-0.7.

**Comment by eyalroz** [comment]
So - do you guys want to merge this PR for 0.6 or close it?

**Comment by kovaltan** [comment]
I've looked through this issue again.
It seems that PL #611 got merged and closes this issue and PL #1005 is just a related PL with this issue.
@jrhemstad  @harrism could you confirm? then close this issue? This is still marked as `open`.

**Comment by jrhemstad** [comment]
Ah yes, this issue should have been closed with PR https://github.com/rapidsai/cudf/pull/611

https://github.com/rapidsai/cudf/pull/1005 will supersede https://github.com/rapidsai/cudf/pull/611, but that's not important for this issue. 

Closing now.
