### ISSUE TITLE
why is GpuCoalesceBatches performance is bad sometimes ?

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#6107]
**What is your question?**
![image](https://user-images.githubusercontent.com/33319780/91457652-2a9fdb00-e8b7-11ea-945c-08dc7b951cfa.png)
I test tpcds query93, i found that GpuCoalesceBatches is long tail , I want to know why and how to know what's happening

**Comment by jlowe** [comment]
GpuCoalesceBatches is not the slow part here.  The actual concatenation of the batches, measured by the `concat batch time` metric, was only 3ms on average and 180ms worst-case.  The `collect batch time` metric is measuring how long this query plan node took to receive all of the batches (i.e.: how long it took to drain the input iterator).  That means it's really measuring the time of nodes earlier in the plan up to the beginning of the stage (usually a scan if the first stage or an exchange if a subsequent stage).

Since the image only shows this specific node I can't say offhand which node was the slowest, but it wasn't this one.

**Comment by kkraus14** [comment]
Should this issue move to https://github.com/nvidia/spark-rapids?

**Comment by jlowe** [comment]
Yes, this is a question on the Spark plugin not cudf.

**Comment by chenrui17** [comment]
i am sorry , i carelessly sent it in the wrong place
@jlowe Thank you for your help， this is part of dag, i think GpuShuffledHashJoin is slowest , all right ? if so , why ?do we have some optimize method , I a tuned several times ,like concurrentTask , rapidsBatchSize, but its performance is also bad.
![image](https://user-images.githubusercontent.com/33319780/91513164-41c1e580-e916-11ea-8f60-ded10111c8fb.png)
here is tpc-ds query 93 complete history UI ， I want to why this query run slowly, and especially stage 7 spent 2.4m ,while cpu spark cost only  1m.
[Details for TPC-DS Q93.htm.zip](https://github.com/rapidsai/cudf/files/5139608/Details.for.TPC-DS.Q93.htm.zip)

**Comment by chenrui17** [comment]
here is CPU SparkSQL history UI , the whole query only spent 1.4m 
[tpcds_q93_history_ui_CPU.zip](https://github.com/rapidsai/cudf/files/5139701/tpcds_q93_history_ui_CPU.zip)

**Comment by jlowe** [comment]
That's the wrong direction in the query plan to look.  The `build time` metric in GpuShuffledHashJoin is very similar to the `collect batch time` metric in GpuCoalesceBatches.  It's how long it spent waiting to drain it's input iterator to get all of the data for the build-side table.  If you look at how long it took to actually perform the join once all the input was retrieved, it was very fast.  `join time` was only 19ms on average, 657ms for the worst-case in any task.

I can't readily explain why the worst-case coalesce batch time collect time was only 19.3s but the worst-case build time was 59.6s and the join itself isn't most of the difference.  Tasks waiting for their turn on the GPU can factor into these metrics, but I would expect any time spent waiting for the GPU to be accounted for in both node's metrics.

I'll spend some time diffing into the details you uploaded, but we may need an nsight systems profile trace to get more details on where the time is being spent in the join vs. collect.

**Comment by jlowe** [comment]
@chenrui17 can you file this issue in https://github.com/NVIDIA/spark-rapids?  This issue needs to be tracked there.

**Comment by JustPlay** [comment]
![image](https://user-images.githubusercontent.com/5866501/92321547-7f80e580-f05d-11ea-9ed0-8ce677db3961.png)
