### ISSUE TITLE
[FEA] add API to JNI buildings for libcudf to query whether it was compiled for PTDS

### ISSUE THREAD

**Issue by abellina** [rapidsai/cudf#6112]
This issue suggests adding a queriable flag in libcudf to find out whether it was compiled for PTDS (https://github.com/rapidsai/cudf/issues/6111). 

This issue is exactly the same, but for the JNI layer.

**Comment by jlowe** [comment]
As part of this, the Java tests should fail if the JNI code was not compiled in the same manner as libcudf wrt. the PTDS setting.  This will prevent a cudf jar build from succeeding on a mismatched configuration.

**Comment by harrism** [comment]
I think @rongou has been working on this. Assigning.

**Comment by harrism** [comment]
Hmmm, I can't assign to @rongou...
