### ISSUE TITLE
[FEA] Why the powerful cudf not support drop row in pandas ?

### ISSUE THREAD

**Issue by cuge1995** [rapidsai/cudf#6115]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I wish I could use cuDF to do [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by kkraus14** [comment]
Could you please give a code example of what is not working?

**Comment by kkraus14** [comment]
No example or code was given so closing this issue.
