### ISSUE TITLE
[BUG] libcudf can emit jitify warnings to stdout when JIT cache is missing

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#6117]
**Describe the bug**
Sometimes libcudf emits messages like the following to stdout which can corrupt application data being produced on stdout:
```
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
```

**Steps/Code to reproduce bug**
Remove the cudf JIT cache directory (e.g.: rm -rf "$HOME/.cudf") and run `cpp/build/gtests/BINARY_TEST`.
This also happens when running the Java `TimestampColumnVectorTest` unit test with the JIT cache removed.

**Expected behavior**
libcudf should not print unexpected messages to stdout.  If warnings need to be emitted they should go to stderr, never stdout.

**Comment by chinmaychandak** [comment]
I am also seeing this:


```
cudf/utilities/bit.hpp(19): warning: cassert: [jitify] File not found
cudf/fixed_point/fixed_point.hpp(27): warning: cassert: [jitify] File not found
```

What I'm more concerned about is that once this appears, I see a weird network connection error in the Dask worker logs. I am trying to send some payload periodically to an endpoint, and it works just fine until I see the Jitify warning. Not even sure if this is related, but thought I'll put this out here.

```
Failed while sending payload. Will retry: HTTPSConnectionPool(host='endpoint', port=443): Read timed out. (read timeout=30)
```

**Comment by lmeyerov** [comment]
Seeing this in 0.15.1 (conda)

Not sure what to do with this one nor root cause wrt user code. We have python set to not store .pyc, maybe related?

**Comment by harrism** [comment]
This appears to come from Jitify. 

https://github.com/NVIDIA/jitify/blob/3e96bcceb9e42105f6a32315abb2af04585a55b0/jitify.hpp#L2817-L2821

I will file a Jitify issue.

**Comment by jlowe** [comment]
I think there's two issues here, Jitify logging to stdout and the issue triggering Jitify to log in the first place.  Logging to stderr is an improvement, but we're still going to be fielding questions from users as to what this message means.  I think it's worthwhile to fix the cause of it in libcudf as well.

From the error messages, it looks like the issue centers around cassert use in bit.hpp and fixed_point.hpp.  Very curious that failing to include cassert isn't fatal to runtime compilation, implying the cassert includes can be removed completely or conditionally included only when not compiling at runtime.  Alternatively we could stringify cassert as we have other headers or maybe just provide an empty string for it since compilation at runtime does not fail.  If we decide to stub or otherwise avoid including cassert during runtime compilation, it would be good to understand why this isn't failing today to verify this won't bite us in the future with a trivial change to cassert usage in bit.hpp or fixed_point.hpp.

**Comment by harrism** [comment]
For now #6509 disabled printing altogether. I'm guessing jitify must provide some replacement for `assert()` that allows this to compile with NDEBUG even though cassert is not found?

**Comment by jrhemstad** [comment]
Did https://github.com/rapidsai/cudf/pull/6509 sufficiently resolve this to close?

**Comment by jlowe** [comment]
I think this can be closed. I haven't seen this since that fix went in.  However I wouldn't be surprised to see a subsequent  issue like, "I wish JIT provided more details when runtime compilation fails." :smile:
