### ISSUE TITLE
[FEA] Row-wise operations support for DateTime columns.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#6129]
The following code fails with `ValueError: All values must be of equal length`. I also see the warning: `"Row-wise operations currently only support int, float, "`.

```
import cudf
gdf = cudf.DataFrame({'t1':["2050-01-01 00:00:00"], 't2':["2050-01-02 00:00:00"]})
gdf["t1"] = gdf["t1"].astype("datetime64[ms]")
gdf["t2"] = gdf["t2"].astype("datetime64[ms]")

# If columns are converted to integers, this obviously works
# gdf["t1"] = gdf["t1"].astype("int")
# gdf["t2"] = gdf["t2"].astype("int")

gdf["StartTime"] = gdf[["t1", "t2"]].min(axis=1)
```

It would be great if we could have row-wise operations like this on DateTime columns as well.

**Comment by beckernick** [comment]
This was resolved in https://github.com/rapidsai/cudf/pull/6415 , closing!
