### ISSUE TITLE
[FEA] Add Kafka cluster metadata API to custreamz.kafka.

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#6131]
Confluent Kafka has an API for the consumer to get the metadata for a Kafka cluster. Here’s how I use it to get the number of partitions for a topic:

```
kafka_cluster_metadata = consumer.list_topics(topic)
npartitions = len(kafka_cluster_metadata.topics[topic].partitions)
```

In custreamz, we currently need to specify the number of partitions to start a stream, which is not ideal in case of production workloads where we need to add partitions to a topic, etc. No other streaming stacks need the end-user to specify #partitions for a stream. 

I can create a PR against streamz to use this `list_topics` API with CK, but it is currently lacking in the custreamz.kafka/cudf_kafka bit.

It would be great to port this API to custreamz.kafka. 

cc: @jdye64

**Comment by jsmaupin** [comment]
I've thought we needed this for some time.  I'm not sure why the user had to specify the partition.  Will we need to reset the job if the number of partitions change?  Is there any way to refresh this value without shutting down the stream?

**Comment by chinmaychandak** [comment]
> Will we need to reset the job if the number of partitions change? 

Currently, yes.

> Is there any way to refresh this value without shutting down the stream?

I was trying to implement this [here](https://github.com/python-streamz/streamz/compare/master...chinmaychandak:master). Can you take a look?
