### ISSUE TITLE
[BUG] astype('datetime64[ms]') throws an error with '.msZ' string format

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#6136]
Reproducer:
```
import cudf

# Passes with cuDF and Pandas
gdf = cudf.DataFrame({'t1':["2050-01-01T00:00:00Z"]})
gdf["t1"].astype('datetime64[ms]')

# Fails with cuDF but passes with Pandas
gdf = cudf.DataFrame({'t1':["2050-01-01T00:00:00.000Z"]})
gdf["t1"].astype('datetime64[ms]')
```

The second example fails showing the error: `ValueError: Unable to infer the timestamp format from the data` with cuDF.

**Comment by galipremsagar** [comment]
Looks like it appears to be fixed in `0.16`:

```python
>>> import cudf
>>> gdf = cudf.DataFrame({'t1':["2050-01-01T00:00:00Z"]})
>>> gdf["t1"].astype('datetime64[ms]')
0   2050-01-01
Name: t1, dtype: datetime64[ms]
>>> cudf.__version__
'0.16.0a+1373.g49dc6b7dd.dirty'
>>> import pandas as pd
>>> pdf = pd.DataFrame({'t1':["2050-01-01T00:00:00.000Z"]})
>>> pdf["t1"].astype('datetime64[ms]')
0   2050-01-01
Name: t1, dtype: datetime64[ns]
```

@chinmaychandak Which version is this error in?

**Comment by chinmaychandak** [comment]
I am using `cudf v0.16.0a200901` which seems to be the latest.

I think you ran the Pandas example for the test instead of cuDF ^. :)

**Comment by galipremsagar** [comment]
> I am using `cudf v0.16.0a200901` which seems to be the latest.
> 
> I think you ran the Pandas example for the test instead of cuDF ^. :)

I see, apologies for the confusion. Yes this is an issue in cudf. Thanks @chinmaychandak !
