### ISSUE TITLE
[FEA] FileNotFoundError instead of GDF_FILE_ERROR 

### ISSUE THREAD

**Issue by daxiongshu** [rapidsai/cudf#614]
**Is your feature request related to a problem? Please describe.**
A common mistake of using read_csv is the wrong file path where the input file doesn't exist. Currently, the error message of cudf.read_csv is GDF_FILE_ERROR which is a little bit confusing. My first impression was it means the file is corrupted or the data type is incorrect.

**Describe the solution you'd like**
pandas.read_csv will print "FileNotFoundError" directly which is much easier to understand. We could do the same.

**Comment by thomcom** [comment]
Good first issue!

**Comment by BradReesWork** [comment]
We are working on expanding error handling and messages

**Comment by mjsamoht** [comment]
Fixed by #760
