### ISSUE TITLE
import cudf not working

### ISSUE THREAD

**Issue by brookdpg** [rapidsai/cudf#6145]
ops@ops-XPS-15-9500:~$ conda activate  yourenvname
(yourenvname) ops@ops-XPS-15-9500:~$ python
Python 3.6.11 | packaged by conda-forge | (default, Aug  5 2020, 20:09:42) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/__init__.py", line 7, in <module>
    from cudf import core, datasets
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import buffer, column
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/core/column/__init__.py", line 1, in <module>
    from cudf.core.column.categorical import CategoricalColumn  # noqa: F401
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/core/column/categorical.py", line 11, in <module>
    import cudf._libxx as libcudfxx
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/_libxx/__init__.py", line 5, in <module>
    from . import (
  File "cudf/_libxx/aggregation.pxd", line 9, in init cudf._libxx.reduce
  File "cudf/_libxx/aggregation.pyx", line 11, in init cudf._libxx.aggregation
  File "/home/ops/anaconda3/envs/yourenvname/lib/python3.6/site-packages/cudf/utils/cudautils.py", line 7, in <module>
    from numba import cuda, numpy_support
ImportError: cannot import name 'numpy_support'
>>> quit()
(yourenvname) ops@ops-XPS-15-9500:~$ conda list
# packages in environment at /home/ops/anaconda3/envs/yourenvname:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py36_0  
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12                   py36_0  
anaconda                  custom                   py36_1  
anaconda-client           1.7.2                    py36_0  
anaconda-project          0.8.4                      py_0  
argh                      0.26.2                   py36_0  
argon2-cffi               20.1.0           py36h7b6447c_1  
arrow-cpp                 0.15.0           py36h090bef1_2    conda-forge
asn1crypto                1.4.0                      py_0  
astroid                   2.4.2                    py36_0  
astropy                   4.0.1.post1      py36h7b6447c_1  
atomicwrites              1.4.0                      py_0  
attrs                     19.3.0                     py_0  
autopep8                  1.5.4                      py_0  
babel                     2.8.0                      py_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.shutil_get_terminal_size 1.0.0                    py36_2  
beautifulsoup4            4.9.1                    py36_0  
bitarray                  1.4.2            py36h7b6447c_0  
bkcharts                  0.2                      py36_0  
blas                      1.0                         mkl  
bleach                    3.1.5                      py_0  
blosc                     1.20.0               he1b5a44_0    conda-forge
bokeh                     2.1.1                    py36_0  
boost-cpp                 1.70.0               ha2d47e9_1    conda-forge
boto                      2.49.0                   py36_0  
bottleneck                1.3.2            py36heb32a55_1  
brotli                    1.0.7                he6710b0_0  
brotlipy                  0.7.0           py36h7b6447c_1000  
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.6.24                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2020.6.20                py36_0  
cffi                      1.14.0           py36h2e261b9_0  
chardet                   3.0.4                 py36_1003  
click                     7.1.2                      py_0  
cloudpickle               1.5.0                      py_0  
clyent                    1.2.2                    py36_1  
colorama                  0.4.3                      py_0  
contextlib2               0.6.0.post1                py_0  
contextvars               2.4                        py_0  
cryptography              2.9.2            py36h1ba5d50_0  
cudatoolkit               10.2.89              h6bb024c_0    nvidia
cudf                      0.13.0                   py36_0    rapidsai
cudnn                     7.6.5                cuda10.2_0  
cupy                      7.7.0            py36h4445f8d_0    conda-forge
curl                      7.71.1               hbc83047_1  
cycler                    0.10.0                   py36_0  
cython                    0.29.21          py36he6710b0_0  
cytoolz                   0.10.1           py36h7b6447c_0  
dask                      2.20.0                     py_0  
dask-core                 2.20.0                     py_0  
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
distributed               2.20.0                   py36_0  
dlpack                    0.3                  he1b5a44_1    conda-forge
docutils                  0.16                     py36_1  
double-conversion         3.1.5                he6710b0_1  
entrypoints               0.3                      py36_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.9                he6710b0_2  
fastavro                  0.23.5           py36h7b6447c_0  
fastcache                 1.1.0            py36h7b6447c_0  
fastrlock                 0.4              py36he6710b0_0  
filelock                  3.0.12                     py_0  
flake8                    3.8.3                      py_0  
flask                     1.1.2                      py_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.2               h5ab3b9f_0  
fribidi                   1.0.9                h7b6447c_0  
fsspec                    0.6.3                      py_0    conda-forge
future                    0.18.2                   py36_1  
get_terminal_size         1.0.0                haa9412d_0  
gettext                   0.19.8.1             hd7bead4_3  
gevent                    20.6.2           py36h7b6447c_0  
gflags                    2.2.2                he6710b0_0  
glib                      2.65.0               h6f030ca_0    conda-forge
glob2                     0.7                        py_0  
glog                      0.4.0                he6710b0_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py36h10f8cd9_2  
graphite2                 1.3.14               h23475e2_0  
greenlet                  0.4.16           py36h7b6447c_0  
grpc-cpp                  1.23.0               h18db393_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.10.0           py36h7918eee_0  
harfbuzz                  2.4.0                hca77d97_1  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
immutables                0.14             py36h7b6447c_0  
importlib-metadata        1.7.0                    py36_0  
importlib_metadata        1.7.0                         0  
iniconfig                 1.0.1                      py_0  
intel-openmp              2020.1                      217  
intervaltree              3.0.2                      py_1  
ipykernel                 5.3.4            py36h5ca1d4c_0  
ipython                   7.16.1           py36h5ca1d4c_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.5.1                      py_0  
isort                     4.3.21                   py36_0  
itsdangerous              1.1.0                    py36_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py36_0  
jeepney                   0.4.3                      py_0  
jinja2                    2.11.2                     py_0  
joblib                    0.16.0                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                    py36_0  
jupyter                   1.0.0                    py36_7  
jupyter_client            6.1.6                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py36_0  
jupyterlab                2.1.5                      py_0  
jupyterlab_server         1.2.0                      py_0  
keyring                   21.2.1                   py36_0  
kiwisolver                1.2.0            py36hfd86e86_0  
krb5                      1.18.2               h173b8e3_0  
lazy-object-proxy         1.4.3            py36h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.34                 hc38a660_9    conda-forge
libarchive                3.3.3             hc47fbbf_1007    conda-forge
libcudf                   0.13.0               cuda10.2_0    rapidsai
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libevent                  2.1.10               hcdb4288_1    conda-forge
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15                 h63c8f33_5  
liblief                   0.10.1               he6710b0_0  
libllvm9                  9.0.1                h4a3c616_1  
libnvstrings              0.13.0               cuda10.2_0    rapidsai
libpng                    1.6.37               hbc83047_0  
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.13.0               cuda10.2_0    rapidsai
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libtool                   2.4.6                h7b6447c_5  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
libxslt                   1.1.34               hc22bd24_0  
llvmlite                  0.33.0           py36hc6ec683_1  
locket                    0.2.0                    py36_1  
lxml                      4.5.2            py36hefd8a0e_0  
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10                 h7b6447c_2  
markupsafe                1.1.1            py36h7b6447c_0  
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py36hef1b27d_0  
mccabe                    0.6.1                    py36_1  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.1.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
mock                      4.0.2                      py_0  
more-itertools            8.4.0                      py_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.1.0                    py36_0  
msgpack-python            1.0.0            py36hfd86e86_1  
multipledispatch          0.6.0                    py36_0  
nbconvert                 5.6.1                    py36_0  
nbformat                  5.0.7                      py_0  
nccl                      2.7.8.1              hc6a2c23_0    conda-forge
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                        py_1  
nltk                      3.5                        py_0  
nose                      1.3.7                    py36_2  
notebook                  6.1.1                    py36_0  
numba                     0.50.1           py36h0573a6f_1  
numexpr                   2.7.1            py36h423224d_0  
numpy                     1.18.5           py36ha1c710e_0  
numpy-base                1.18.5           py36hde5b4d6_0  
numpydoc                  1.1.0                      py_0  
nvstrings                 0.13.0                   py36_0    rapidsai
olefile                   0.46                     py36_0  
openpyxl                  3.0.4                      py_0  
openssl                   1.1.1g               h7b6447c_0  
packaging                 20.4                       py_0  
pandas                    0.25.3           py36hb3f55d8_0    conda-forge
pandoc                    2.10                          0  
pandocfilters             1.4.2                    py36_1  
pango                     1.45.3               hd140c19_0  
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
patchelf                  0.11                 he6710b0_0  
path                      13.1.0                   py36_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py36_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py36_0  
pcre                      8.44                 he6710b0_0  
pep8                      1.7.1                    py36_0  
pexpect                   4.8.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    7.2.0            py36hb39fc2d_0  
pip                       20.2.1                   py36_0  
pixman                    0.40.0               h7b6447c_0  
pkginfo                   1.5.0.1                  py36_0  
pluggy                    0.13.1                   py36_0  
ply                       3.11                     py36_0  
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.5                      py_0  
prompt_toolkit            3.0.5                         0  
psutil                    5.7.0            py36h7b6447c_0  
ptyprocess                0.6.0                    py36_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py36h403a769_0  
pyarrow                   0.15.0           py36h8b68381_1    conda-forge
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py36h7b6447c_0  
pycparser                 2.20                       py_2  
pycrypto                  2.6.1           py36h7b6447c_10  
pycurl                    7.43.0.5         py36h1ba5d50_0  
pydocstyle                5.0.2                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.6.1                      py_0  
pylint                    2.5.3                    py36_0  
pyodbc                    4.0.30           py36he6710b0_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
pyrsistent                0.16.0           py36h7b6447c_0  
pysocks                   1.7.1                    py36_0  
pytables                  3.6.1            py36h71ec239_0  
pytest                    6.0.1                    py36_0  
python                    3.6.11          h4d41432_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_1  
python-language-server    0.34.1                   py36_0  
python-libarchive-c       2.9                        py_0  
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py36h7b6447c_0  
pyxdg                     0.26                       py_0  
pyyaml                    5.3.1            py36h7b6447c_1  
pyzmq                     19.0.1           py36he6710b0_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 0.7.2                      py_0  
qtconsole                 4.7.5                      py_0  
qtpy                      1.9.0                      py_0  
re2                       2019.08.01           he6710b0_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.7.14        py36h7b6447c_0  
requests                  2.24.0                     py_0  
ripgrep                   11.0.2               he32d670_0  
rmm                       0.13.0                   py36_0    rapidsai
rope                      0.17.0                     py_0  
rtree                     0.9.4                    py36_1  
ruamel_yaml               0.15.87          py36h7b6447c_1  
scikit-image              0.16.2           py36h0573a6f_0  
scikit-learn              0.23.1           py36h423224d_0  
scipy                     1.5.0            py36h0b6359f_0  
seaborn                   0.10.1                     py_0  
secretstorage             3.1.2                    py36_0  
send2trash                1.5.0                    py36_0  
setuptools                49.2.1                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3                  py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0                     py_0  
snappy                    1.1.8                he6710b0_0  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.0                      py_0  
sphinxcontrib             1.0                      py36_1  
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.3                      py_0  
spyder                    4.1.4                    py36_0  
spyder-kernels            1.9.2                    py36_0  
sqlalchemy                1.3.18           py36h7b6447c_0  
sqlite                    3.32.3               h62c20be_0  
statsmodels               0.11.1           py36h7b6447c_0  
sympy                     1.6.1                    py36_0  
tbb                       2020.0               hfd86e86_0  
tblib                     1.6.0                      py_0  
terminado                 0.8.3                    py36_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
toolz                     0.10.0                     py_0  
tornado                   6.0.4            py36h7b6447c_1  
tqdm                      4.48.2                     py_0  
traitlets                 4.3.3                    py36_0  
typed-ast                 1.4.1            py36h7b6447c_0  
typing_extensions         3.7.4.2                    py_0  
ujson                     1.35             py36h14c3975_0  
unicodecsv                0.14.1                   py36_0  
unixodbc                  2.3.7                h14c3975_0  
uriparser                 0.9.3                he6710b0_1  
urllib3                   1.25.9                     py_0  
watchdog                  0.10.3                   py36_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py36_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py36_0  
widgetsnbextension        3.5.1                    py36_0  
wrapt                     1.11.2           py36h7b6447c_0  
wurlitzer                 2.0.1                    py36_0  
xlrd                      1.2.0                    py36_0  
xlsxwriter                1.2.9                      py_0  
xlwt                      1.3.0                    py36_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.2                he6710b0_2  
zict                      2.0.0                      py_0  
zipp                      3.1.0                      py_0  
zlib                      1.2.11               h7b6447c_3  
zope                      1.0                      py36_1  
zope.event                4.4                      py36_0  
zope.interface            4.7.1            py36h7b6447c_0  
zstd                      1.4.4                h3b9ef0a_2    conda-forge
(yourenvname) ops@ops-XPS-15-9500:~$

**Comment by shwina** [comment]
It looks like this is a relatively old version of cuDF (0.13) -- could you try installing a newer version? Scroll down to the "Release Selector" section of this page: https://rapids.ai/start.html

**Comment by brookdpg** [comment]
that fixes the issue thanks.
