### ISSUE TITLE
[DOC] How about to make a comparison table? (suggestion)

### ISSUE THREAD

**Issue by TakuNishiumi** [rapidsai/cudf#6166]
When I uses cuDF, I got this error.
`AttributeError: 'DataFrameGroupBy' object has no attribute 'get_group'`
I understood that it is not supported yet.

If you have the comparison table between cuDF and pandas, it is very useful for users.
(This is example of cupy https://docs.cupy.dev/en/stable/reference/comparison.html)

**Comment by AllDuffy** [comment]
Would love get_group functionality and especially a comparison table

**Comment by vyasr** [comment]
While we do not have an exact table, we do maintain [some documentation about this](https://docs.rapids.ai/api/cudf/stable/user_guide/pandas-comparison/) now. Moreover, we now have cudf.pandas, which is the intended drop-in replacement, so I'm closing this issue as resolved. Use of the profiler and the pandas test suite to identify fallbacks will reduce the gap between cudf and pandas APIs over time.
