### ISSUE TITLE
[FEA] cuio: use datasource as the exclusive reader input argument

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#6185]
Internally, readers are instantiating datasources (from filepaths or otherwise), presumably out of convenience. This complicates the reader interfaces and implementation. Let's factor the readers filepath arguments in to explicit datasource initialization _outside_ of the reader and accept `std::unique_ptr<datasource>` or `std::vector<std::unique_ptr<datasource>>` (in the case of parquet, for example) as file/data input exclusively.

https://github.com/rapidsai/cudf/blob/f4735c7f658da4a157dc09391da899b072878305/cpp/src/io/csv/reader_impl.hpp#L78-L81
https://github.com/rapidsai/cudf/blob/f4735c7f658da4a157dc09391da899b072878305/cpp/src/io/json/reader_impl.hpp#L177-L180
https://github.com/rapidsai/cudf/blob/f4735c7f658da4a157dc09391da899b072878305/cpp/src/io/orc/reader_impl.cu#L817-L823
https://github.com/rapidsai/cudf/blob/f4735c7f658da4a157dc09391da899b072878305/cpp/src/io/parquet/reader_impl.cu#L1248-L1253

**Comment by vuule** [comment]
The reason why we have a separate path for file names is because JSON and CSV derive compression type from the file extension. If we pass this information in a different way, we can remove the filepath overloads.

**Comment by cwharris** [comment]
Sounds like that makes this issue dependent on #6188

**Comment by vuule** [comment]
This will be closed by #9088 and #9089

**Comment by vuule** [comment]
@cwharris can we close this one now? :)

**Comment by cwharris** [comment]
yep!
