### ISSUE TITLE
[FEA] cuio: consolidate host decompression

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#6188]
Host decompression is used by json/csv readers immediately after datasource read. Rather than being a part of each reader/writer, we could consolidate them in to the datasource, or a decorator of some kind. This would simplify the readers, and also enable decouple decompression from `range_offset` and `range_size`.

This might become more straightforward after #6185

Aside from keeping things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself), abstracting the host decompression away from the readers may allow use it in more readers.

Examples:
https://github.com/rapidsai/cudf/blob/2b090758110bc486f0a7edf8b5d881b98f224a60/cpp/src/io/json/reader_impl.cu#L642-L645
https://github.com/rapidsai/cudf/blob/2b090758110bc486f0a7edf8b5d881b98f224a60/cpp/src/io/json/reader_impl.cu#L240-L260
https://github.com/rapidsai/cudf/blob/2b090758110bc486f0a7edf8b5d881b98f224a60/cpp/src/io/json/reader_impl.cu#L268-L283

**Comment by vuule** [comment]
@cwharris should we close this one?
