### ISSUE TITLE
DataFrameGroupBy.quantile() in cuDF

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cudf#619]
**Is your feature request related to a problem? Please describe.**
When can we have a quantile function in the Groupby cuDF object ? Similar to Pandas, where you do something like:
`df.groupby(['cat1']).quantile([0.25,0.5], interpolation='linear')`
I understand that in 0.4.0 only sum/count/mean/min/max are supported.

**Describe the solution you'd like**
Similar to pandas

**Comment by dorisnvidia** [comment]
I hit the 'enter' key by mistake so the issue was submitted prematurely. sorry about that. 

**Is your feature request related to a problem? Please describe.**
When can we have a quantile function in the Groupby cuDF object ? Similar to Pandas, where you do something like:
df.groupby(['cat1']).quantile([0.25,0.5], interpolation='linear')
I understand that in 0.4.0 only sum/count/mean/min/max are supported. 

**Describe the solution you'd like**
Similar to pandas

**Comment by kkraus14** [comment]
Fixed by #1866
