### ISSUE TITLE
[FEA] Support "inplace" argument for set_index

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#6198]
**Is your feature request related to a problem? Please describe.**
The `inplace` argument (available in pandas) is not currently supported for `cudf.DataFrame`.

```python
import cudf

df = cudf.DataFrame({'id': [0, 1, 2], 'val': ["a", "b", "c"]})
df.set_index("id", inplace=True)
```
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-a9ff99a5ec88> in <module>
      2 
      3 df = cudf.DataFrame({'id': [0, 1, 2], 'val': ["a", "b", "c"]})
----> 4 df.set_index("id", inplace=True)

TypeError: set_index() got an unexpected keyword argument 'inplace'
```

**Describe alternatives you've considered**
`df = df.set_index("a")` works fine, but is less efficient than an in-place operation. A more-efficient (but uglier) alternative may be (?):

```python
df = cudf.DataFrame({'id': [0, 1, 2], 'val': ["a", "b", "c"]})
index = ["id"]
df.index = df[index].copy(deep=False)
df.drop(columns=index, inplace=True)
```

**Additional context**
The `read_parquet` logic in upstream `dask.dataframe` assumes setting/resetting the index is a zero-copy operation.  To handle index preservation correctly in `dask_cudf` (which is currently broken in some cases), it would be nice to have a simple `inplace` option.

**Comment by kkraus14** [comment]
@isVoid can you tackle this when you get a chance?
