### ISSUE TITLE
[BUG] cudf::io::read_parquet with set_num_rows causes ilegal memory access

### ISSUE THREAD

**Issue by williamBlazing** [rapidsai/cudf#6200]
**Describe the bug**
Having issues with cudf::io::read_parquet when only trying to read 1 row (tried with 100 rows and had same issue).  This issue is recent, so i am guessing it may have been introduced by https://github.com/rapidsai/cudf/pull/6051/files

The error i am getting is:
```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
```

It does not crash all the time, more like 1 in 10. 

**Steps/Code to reproduce bug**
```
// std::shared_ptr<arrow::io::RandomAccessFile> file  
auto arrow_source = cudf::io::arrow_io_source{file};
cudf_io::parquet_reader_options pq_args = cudf::io::parquet_reader_options::builder(cudf_io::source_info{&arrow_source});
pq_args.enable_convert_strings_to_categories(false);
pq_args.enable_use_pandas_metadata(false);
pq_args.set_num_rows(1);
cudf_io::table_with_metadata table_out = cudf::io::read_parquet(pq_args);
```

**Expected behavior**
Should not crash

**Environment overview (please complete the following information)**
This is happening inside BlazingSQL code. Using cudf from conda:
cudf                      0.16.0a200910   cuda_10.2_py38_g6c0801ffd_1633    rapidsai-nightly
dask-cuda                 0.16.0a200910           py38_90    rapidsai-nightly
dask-cudf                 0.16.0a200910   py38_g6c0801ffd_1633    rapidsai-nightly
libcudf                   0.16.0a200910   cuda10.2_g6c0801ffd_1633    rapidsai-nightly
librmm                    0.16.0a200910   cuda10.2_g9d02c5b_365    rapidsai-nightly
rmm                       0.16.0a200910   cuda_10.2_py38_g9d02c5b_365    rapidsai-nightly

I have seen this on my local box and on gpuCI https://gpuci.gpuopenanalytics.com/blue/organizations/jenkins/blazingsql%2Fgpuci%2Fpyblazing%2Fprb%2Fpyblazing-gpu-build/detail/pyblazing-gpu-build/3455/pipeline

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by rgsl888prabhu** [comment]
@williamBlazing  Is it possible to provide me a sample dataset on which this is reproducible.

**Comment by rgsl888prabhu** [comment]
And I was just curious about couple of stuff
- is this PR available in the nightly that you are using https://github.com/rapidsai/cudf/pull/6195
- And how did you ping point it to parquet ?

I have tried creating multiple column with huge number of rows and read just 1 row, but I couldn't reproduce the issue.

I will be trying couple of more options, and if possible please provide me your reproducible code.

**Comment by calebwin** [comment]
I ran into this on the latest branch-0.16 with-
```python
In [3]: cudf.read_parquet("python/cudf/cudf/tests/data/parquet/concatenated_yellow_tripdata_2015-01_08_head_40M.parquet", num_rows=100)                  
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorIllegalAddress: an illegal memory access was encountered
Aborted (core dumped)
```
I reproduced for some values of `num_rows` where it would work some times and then fail eventually. Relevant file is attached; it has 1 row group. Also this issue didn't come up when I was setting `num_rows` when using your not-yet-merged args filtering work for ORC and it doesn't seem to be an issue with `skip_rows`


.

**Comment by rgsl888prabhu** [comment]
@calebwin Thank you, I was able to reproduce it.

**Comment by nvdbaranec** [comment]
> **Describe the bug**
> Having issues with cudf::io::read_parquet when only trying to read 1 row (tried with 100 rows and had same issue). This issue is recent, so i am guessing it may have been introduced by https://github.com/rapidsai/cudf/pull/6051/files
> 

Do you know how recently your repro case was working? Also is there some easy way to get access to the file you're using to repro?

**Comment by nvdbaranec** [comment]
Hey @williamBlazing , I think I have a fix for this.  If you have a chance, could you give this PR a try?

https://github.com/rapidsai/cudf/pull/6217

Don't even need to grab the PR itself, it's a true one-liner you can just paste locally.

**Comment by williamBlazing** [comment]
@nvdbaranec We finally got a chance to verify this fix today. Thanks @romeluko for doing that

**Comment by nvdbaranec** [comment]
Fantastic.  Glad to help.
