### ISSUE TITLE
[BUG] column_view data() uses same _offset regardless of data type 

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#6203]
**Describe the bug**
In https://github.com/rapidsai/cudf/blob/branch-0.16/cpp/include/cudf/column/column_view.hpp#L74
The `_offset` pointer math changes based off the templated type, which is problematic if the templated type does not match the column's type. For example, a `uint32_t` column with `offset = 2` that has `cv.data<uint64_t>()` will return an address 16 bytes rather than 8 bytes past the start of column device memory. A `uint32_t` column with `offset = 2` that has `cv.data<uint8_t>()` will return an address 2 bytes past the start of column device memory.

**Steps/Code to reproduce bug**
Use the `data<T>()` function on a sliced column where the size of type `T` is not the same as the column's type

**Expected behavior**
Return the same address regardless of templated type.

**Additional context**
Blocking #6139

**Potential Solution**
`return head<T>() + (_offset * size_of(type()) / sizeOf(T));`
This is problematic when dealing with non-standard types that cause `(_offset * size_of(type()) / sizeOf(T))` to not equal an integer value.
or
`return static_cast<T>(static_cast<type()>(_data) + _offset);`
or
`return static_cast<T>(_data + _offset * size_of(type()));`

**Comment by jrhemstad** [comment]
> which is problematic if the templated type does not match the column's type.

This is illegal and results in undefined behavior.

**Comment by jrhemstad** [comment]
If you want to view the elements of a column as bytes, this would be the way to do it:

```
auto bytes = reinterpret_cast<char*>(c.data<uint32_t>());
```

First you get the data as it's real type, then you cast it.

**Comment by davidwendt** [comment]
Left a comment in the PR on this
https://github.com/rapidsai/cudf/pull/6139/files#r487044483

**Comment by rwlee** [comment]
Thanks, switched to the reinterpret_cast approach last night. Thanks for the help Jake and David! Closing this issue.
