### ISSUE TITLE
[FEA] cuio: reduce subscript member access in parse utilities

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#6210]
There's a lot of clutter cause by subscript member access in the parsing utilities which inhibits refactoring. Instead of subscript member access, we can use pointers as iterators. Updating return values to use pointers rather than offsets will also simplify the functions. Invocations will need to be adjusted to account for the removal of a sentinel value (`-1`) in place of `end` in some locations.

Example:
https://github.com/rapidsai/cudf/blob/c27d844986b70003c16b6203464f53936a41739c/cpp/src/io/csv/datetime.cuh#L32-L42

Raw replacement:
```c++
__inline__ __device__ const char *begin findFirstOccurrence(const char *begin, const char *end, char c)
{
  while (begin < end and *begin != c) { begin++; }
  return begin;
} 
```

This specific example is probably just `thrust::find`, but there are numerous others that may be more complex.

**Comment by cwharris** [comment]
I'm going to take this one, as it's interfering with higher level changes.

**Comment by cwharris** [comment]
Introducing device_span in #6233 could be beneficial here.

**Comment by harrism** [comment]
Why not just use `thrust::find`?

```
__inline__ __device__ auto findFirstOccurrence(const char *begin, const char *end, char c)
{
  return thrust::find(thrust::seq, begin, end, c);
} 
```

You will need to work out the needed return type though...

**Comment by cwharris** [comment]
@harrism I'm attempting to change as little as possible because the code is volatile and CI take a while to build/report test failures, and centos likes to fail. Keeping the focus on subscript access.

**Comment by cwharris** [comment]
Just realized this is the issue and not the PR. Yes, thrust::find is the appropriate replacement when we get back to updating this code again.
