### ISSUE TITLE
[BUG] estimate_join_output_size returns size_type which on overflow can cause a hang

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#6221]
**Describe the bug**
estimate_join_output_size can overflow and result in what appears to be a hang instead of an error.

**Steps/Code to reproduce bug**
I don't have C++ code to reproduce the error just yet.  I'll try to work on it if it is needed.  The case we have is trying to run TPC-DS query 72 on scale factor 200 with anything smaller than about 1,000 shuffle partitions.  I know that does not mean a lot, but essentially if we divide the join up 10,000 ways so each key is joined separately it succeeds, but takes a really really long time.  If we divide the join up 1,000 ways it fails with an out of memory error trying to allocate the data.  If I divide the join up 500 or smaller ways it just hangs with 100% GPU utilization until I kill it. Looking at the code I suspect that we are getting an overflow in `estimate_join_output_size`. 

**Expected behavior**
The join does not hang, but fails early with an error about how it is too big.

**Environment overview (please complete the following information)**
cudf-0.15 release (java)
V100 GPU
Ubuntu 18.04.4 LTS

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Comment by harrism** [comment]
I think we need a repro or at least a pointer to the relevant code you think is wrong.

**Comment by revans2** [comment]
@harrism  The following patch should reproduce the error I described. If you set the number of entries on the left/right smaller the test passes.  I have a set of entries commented out that make the 16GB GPU run out of memory and return an error, but the default values should hang.

```diff
diff --git a/cpp/tests/join/join_tests.cpp b/cpp/tests/join/join_tests.cpp
index 4fb0c282b5..a15fde58e6 100644
--- a/cpp/tests/join/join_tests.cpp
+++ b/cpp/tests/join/join_tests.cpp
@@ -16,6 +16,8 @@
 
 #include <cudf/column/column.hpp>
 #include <cudf/column/column_view.hpp>
+#include <cudf/column/column_factories.hpp>
+#include <cudf/scalar/scalar_factories.hpp>
 #include <cudf/copying.hpp>
 #include <cudf/join.hpp>
 #include <cudf/sorting.hpp>
@@ -484,6 +486,43 @@ TEST_F(JoinTest, LeftJoinOnNulls)
   CUDF_TEST_EXPECT_TABLES_EQUAL(*sorted_gold, *sorted_result);
 }
 
+TEST_F(JoinTest, InnerJoinSizeExplosion)
+{
+  auto zero = cudf::make_numeric_scalar(cudf::data_type(cudf::type_id::INT32));
+  zero->set_valid(true);
+  static_cast<cudf::scalar_type_t<int32_t> *>(zero.get())->set_value(0);
+
+  // Max pool size exceeded with 
+  // int32_t left = 45000;
+  // int32_t right = 45000;
+  // But the following appears to hang
+  int32_t left = 45000;
+  int32_t right = 450000;
+ 
+  auto col0_0 = cudf::make_column_from_scalar(*zero, left);
+  auto col1_0 = cudf::make_column_from_scalar(*zero, right);
+
+  CVector cols0, cols1;
+  cols0.push_back(std::move(col0_0));
+  cols1.push_back(std::move(col1_0));
+
+  Table t0(std::move(cols0));
+  Table t1(std::move(cols1));
+
+  auto result            = cudf::inner_join(t0, t1, {0}, {0}, {{0, 0}});
+  auto result_sort_order = cudf::sorted_order(result->view());
+  auto sorted_result     = cudf::gather(result->view(), *result_sort_order);
+
+  auto col_gold_0 = cudf::make_column_from_scalar(*zero, left * right);
+  CVector cols_gold;
+  cols_gold.push_back(std::move(col_gold_0));
+  Table gold(std::move(cols_gold));
+
+  auto gold_sort_order = cudf::sorted_order(gold.view());
+  auto sorted_gold     = cudf::gather(gold.view(), *gold_sort_order);
+  CUDF_TEST_EXPECT_TABLES_EQUAL(*sorted_gold, *sorted_result);
+}
+
 TEST_F(JoinTest, InnerJoinNoNulls)
 {
   column_wrapper<int32_t> col0_0{{3, 1, 2, 0, 2}};
```
