### ISSUE TITLE
[REVIEW] Add cudf::detail::span in anticipation of std::span / thrust::span

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#6233]
**Is your feature request related to a problem? Please describe.**
cudf contains many pairs of pointers + size, or begin/end pointers with no abstraction around them. `std::span` was created to handle this case, but is not available until C++ 20. cudf won't be using C++ 20 any time soon, but we can implement our own and clean up various pointer/size begin/end arguments around the code base.

**Describe the solution you'd like**
Implement `cudf::utilities::span` in `include/cudf/utilites/span.cuh` to match spec (or a subset) for std::span.

**Describe alternatives you've considered**
Standardizing on multiple arguments for `ptr`/`size` or `begin`/`end`.

**Additional context**
https://en.cppreference.com/w/cpp/container/span

We can likely get by with a subset of the spec. It is possible we need a `.hpp` version, but we may be able to avoid duplicate code using templates, inheritance, or possibly using only the `.hpp` version, since neither are owning classes.

**Comment by jrhemstad** [comment]
For the `Extent` template parameter I think we can just worry about the dynamic extent option. So we can do something like this for now:
```
template<
    class T,
    std::size_t Extent = cudf::detail::dynamic_span_extent
> class span{
   static_assert(Extent == cudf::detail::dynamic_span_extent, "Only dynamic extent is supported");
```

We can add support for the static Extent if/when we care about that.
