### ISSUE TITLE
[FEA] Replace cooperative loading of structs with a function or a simple single thread loading

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6236]
Many kernels in cuIO start with loading a struct to shared memory. This is currently done by using all threads to read in a part of the struct in a not reader friendly way.
Examples:
https://github.com/rapidsai/cudf/blob/9fc167ce118f576d7bb62d611e6cfc6234cdc4fc/cpp/src/io/orc/stripe_data.cu#L1122-L1124
https://github.com/rapidsai/cudf/blob/83d1ad7415afeac4acc00c7697a3736abab1ed9f/cpp/src/io/orc/stats_enc.cu#L252-L258
Also, it is dangerous as has been rightly stated here:
https://github.com/rapidsai/cudf/blob/83d1ad7415afeac4acc00c7697a3736abab1ed9f/cpp/src/io/parquet/page_data.cu#L953-L956

Increasing the struct size might in some cases cause the whole struct to not be read.

### Proposed fix:
Try and replace this with reading using a single thread. These reads might not be too expensive as generally there's very few such reads in a block. The rest of the computation would easily overshadow it in terms of time spent.
OR
Replace this with a function that has a descriptive name and handle the overflowing struct size case inside it. It could check for the clock size and the struct size and have a loop so read larger structs in smaller blocks.

**Comment by jrhemstad** [comment]
I believe this is something [`trove`](https://github.com/bryancatanzaro/trove) can help with. It will do better than that hacked code too because it will use vectorized load/stores.

**Comment by harrism** [comment]
CUB also has various loaders that are intended for this purpose.

**Comment by jrhemstad** [comment]
> CUB also has various loaders that are intended for this purpose.

cub::BlockLoad is more for loading an array of items. In this case, we're loading a single large struct cooperatively. This is more what trove is intended for.
