### ISSUE TITLE
[BUG] Memory discrepancy with concat( ignore_index=True )

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#6249]
**Describe the bug**
When concatenating two dataframes with `ignore_index=True` the memory usage of the resulting dataframe should be the sum of memory usage of the individual dataframes, however this doesn't seem to be the case in practice despite `df.memory_usage` reporting identical values.

**Steps/Code to reproduce bug**
```python
import cudf
from cudf.datasets import randomdata

df1 = randomdata(nrows=100000000,
                 dtypes={'a':int, 'b':int},
                 seed=0)

df2 = randomdata(nrows=100000000,
                 dtypes={'a':int, 'b':int},
                 seed=0)

print(df1.memory_usage(deep=True))
print(df2.memory_usage(deep=True))
```
```
Memory usage and nvidia-smi
a        800000000
b        800000000
Index            0
dtype: int64
a        800000000
b        800000000
Index            0
dtype: int64

|   0  Quadro RTX 8000     On   | 00000000:15:00.0 Off |                  Off |
| 33%   38C    P2    70W / 260W |   3636MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
```

After concat
```python
df_res = cudf.concat([df1, df2], ignore_index=True)
del(df1, df2)
print(df_res.memory_usage(deep=True))
```
```
Memory usage and nvidia-smi
a        1600000000
b        1600000000
Index             0
dtype: int64

|   0  Quadro RTX 8000     On   | 00000000:15:00.0 Off |                  Off |
| 33%   38C    P2    69W / 260W |   5158MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
```

The `nvidia-smi` memory usage 3636MiB vs 5158MiB doesn't seem to add up. 

I did confirm that `del(df_res)` cleared all the GPU memory and the additional 1.5GB wasn't from another variable in memory.

**Expected behavior**
Ideally the memory used by the dataframe after concat should be the same as the memory used by the initial dataframes concatenated.

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker 0.15 release image

**Comment by kkraus14** [comment]
@ayushdg could you try a few things to help triage?

Does `df_res.reset_index(drop=True)` reduce the memory usage?

Does deleting columns `a` and `b` free all of the memory usage?

**Comment by ayushdg** [comment]
> Does df_res.reset_index(drop=True) reduce the memory usage?

Yup it looks like `df_res.reset_index(drop=True) ` does reduce the memory usage.
```
print(df_res.memory_usage(deep=True))

a        1600000000
b        1600000000
Index             0
dtype: int64

In [4]: print(df_res.index)
RangeIndex(start=0, stop=200000000)

|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
| N/A   45C    P0    28W /  70W |   5084MiB / 15109MiB |      0%      Default |
```

```
In [6]: df_res = df_res.reset_index(drop=True)

In [7]: print(df_res.memory_usage(deep=True))
a        1600000000
b        1600000000
Index             0
dtype: int64

In [8]: print(df_res.index)
RangeIndex(start=0, stop=200000000)

|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
| N/A   46C    P0    28W /  70W |   3558MiB / 15109MiB |      0%      Default |

```

> Does deleting columns a and b free all of the memory usage?

Deleting both columns `a` and `b` without the `reset_index` does not free all of the memory usage:
```
In [4]: del(df_res['a'])

In [5]: del(df_res['b'])

In [6]: print(df_res.memory_usage(deep=True))
Index    0
dtype: int64

In [7]: print(df_res.index)
RangeIndex(start=0, stop=200000000)

|   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
| N/A   41C    P0    27W /  70W |   2032MiB / 15109MiB |      0%      Default |
```

**Comment by kkraus14** [comment]
Okay, I'm guessing that we materialized a memoized column underneath the `RangeIndex` for some reason. Will let @isVoid dig in from here 😄
