### ISSUE TITLE
[BUG] Still multiple calls to deprecated `rmm::mr::get_default_resource()`

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#6250]
**Describe the bug**
In #6121 @hyperbolic2346 removed most calls to `get_default_resource()` and replaced them with `get_current_device_resource()`, but there are still quite a few calls. 

These need to be removed before we merge rapidsai/rmm#560

**Comment by cwharris** [comment]
Didn't realize you assigned this to yourself @harrism .

**Comment by harrism** [comment]
Yeah, because I needed it merged for rapidsai/rmm#560
