### ISSUE TITLE
[BUG] native_jpointerArray has no bound checking

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#6266]
**Describe the bug**
native_jpointerArray there are no bounds checking. This does not cover us from passing empty arrays.

**Steps/Code to reproduce bug**
Found during code review

**Expected behavior**
We should do some sort of bound checks for the `operator[]` based on Bobby's comment here :https://github.com/rapidsai/cudf/pull/6171#discussion_r490385446

**Comment by sameerz** [comment]
Still needed.

**Comment by vyasr** [comment]
@revans2 please correct me and reopen if I am mistaken, but it looks like this issue was resolved in https://github.com/rapidsai/cudf/pull/6287. I now see bounds checking e.g. [here](https://github.com/rapidsai/cudf/blob/branch-24.06/java/src/main/native/include/jni_utils.hpp#L411).
