### ISSUE TITLE
[QST] Why use 512 as the alignment size while the underlaying RMM use 256 by default

### ISSUE THREAD

**Issue by JustPlay** [rapidsai/cudf#6290]
https://github.com/rapidsai/cudf/blob/1fa807259174e297d9a3cefaeec58d54eb429987/java/src/main/native/src/RmmJni.cpp#L39

Why use 512 as the alignment size while the underlaying RMM use 256 by default @jrhemstad

**Comment by jlowe** [comment]
This is a remnant from when RMM was using CNMEM.  See https://github.com/NVIDIA/cnmem/blob/master/src/cnmem.cpp#L48.  This can probably be lowered to 256 now.

**Comment by JustPlay** [comment]
> This is a remnant from when RMM was using CNMEM. See https://github.com/NVIDIA/cnmem/blob/master/src/cnmem.cpp#L48. This can probably be lowered to 256 now.

Thanks

and another question why rmm use 256？

**Comment by jrhemstad** [comment]
> and another question why rmm use 256？ @jlowe

This is the minimum alignment of `cudaMalloc` and so RMM follows it.

**Comment by jlowe** [comment]
> and another question why rmm use 256？

The CUDA runtime always returns allocations that are 256-byte aligned, probably for performance reasons on the device.  See https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-memory-accesses.
