### ISSUE TITLE
[FEA] Support selecting different hash functions in hash_partition

### ISSUE THREAD

**Issue by gaohao95** [rapidsai/cudf#6307]
**Is your feature request related to a problem? Please describe.**

Right now, cuDF hard-codes `MurmurHash3_32` inside `hash_partition`. Here is one example.
https://github.com/rapidsai/cudf/blob/5976d74567f248b67a06f7c84180c3c909b3c0e3/cpp/src/hash/hashing.cu#L481

I wish cuDF can allow the user of the cpp API to choose which hash function to use for `hash_partition`. 

**Describe the solution you'd like**
In terms of API, maybe we can add a template or additional argument of hash function to [`cudf::detail::hash_partition`](https://github.com/rapidsai/cudf/blob/5976d74567f248b67a06f7c84180c3c909b3c0e3/cpp/include/cudf/detail/hashing.hpp#L27). Raise an error if the hash function is incompatible with the data type (e.g. identity hash function with string type). 

**Additional context**
@abc99lr discovered using different hash functions has significant impact on the distributed join performance due to hash conflict. For example, when hacking cuDF to use identify hash function instead of Murmur hash like [this](https://github.com/rapidsai/cudf/compare/branch-0.16...gaohao95:select-hash-functions) decreases the running time of [distributed join](https://github.com/rapidsai/distributed-join) from 0.581s to 0.345s using 4 DGX-1V nodes with 32 GPUs, with 50 million rows/table/GPU. 

cc @nsakharnykh @abc99lr

**Comment by jrhemstad** [comment]
Adding a template to `detail::hash_partition` for the hash function sounds good to me.

```
template <typename Hash>
std::pair<std::unique_ptr<table>, std::vector<size_type>> hash_partition(
  table_view const& input,
  std::vector<size_type> const& columns_to_hash,
  int num_partitions,
  Hash&& hash
  rmm::mr::device_memory_resource* mr,
  cudaStream_t stream)
```
