### ISSUE TITLE
[BUG] Null mask gets auto removed from temp column in Column._concat()

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#631]
**Describe the bug**
When trying to concat columns which have null masks, we create an empty column of the size of the final result. We then make and uninitialized mask and add it to the result column using `Column.replace` which calls the column constructor. What ends up happening is that the constructor counts the number of nulls in the newly added mask. Since the mask is uninitialized, it may or may not have null values set. In case there aren't any null values, the constructor removes the mask. This causes the new result column to not have a mask set. When accessed from C++, there's an illegal access of a nullptr and we get a crash.

**Steps/Code to reproduce bug**
Unable to get this behaviour outside of pytests but I've already investigated the cause so the description above should be sufficient.

**Expected behavior**
The mask should not be deleted and libcudf should get a valid pointer to an empty null mask

**Environment details (please complete the following information):**
 - Environment location: Bare-metal on 10.110.44.117 (but should be reproducible everywhere)
 - Method of cuDF install: from source
 - Please run and attach the output of the `cudf/print_env.sh` script to gather relevant environment details
[printenv.txt](https://github.com/rapidsai/cudf/files/2729749/printenv.txt)

**Comment by devavret** [comment]
@kkraus14 suggested that a way to fix this would be to pass `null_count` along with `mask` to `Column.replace` so that it does not remove the mask when it sees a non-0 `null_count`. Gonna try it.

**Comment by kkraus14** [comment]
Resolved by #547
