### ISSUE TITLE
[FEA] Need a way to check the memory usage of DataFrame

### ISSUE THREAD

**Issue by amotupal** [rapidsai/cudf#632]
Is there a function similar to [DataFrame.memory_usage()](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.memory_usage.html) in pandas to check the memory usage of my DataFrame?
I am using 2080 Ti with 11 GB frame buffer. Still I am getting the error GDFError: GDF_MEMORYMANAGER_ERROR very frequently. '$nvidia-smi ' is showing me that my application is using up all GPU memory.

**Comment by harrism** [comment]
I don't think we have this yet, but agree it would be useful. Setting this as a feature request.

**Comment by quasiben** [comment]
This has now been added by https://github.com/rapidsai/cudf/pull/3610
