### ISSUE TITLE
[BUG] Remaining testing and cleanup tasks for Abstract Syntax Tree

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#6320]
PR #5494 left a few loose ends. This issue tracks them.

 - [x] [AST / n-ary transform need tests with larger data sizes.](https://github.com/rapidsai/cudf/pull/5494#issuecomment-678839857) Often issues arise in logic with custom kernels pertaining to differences between running a kernel with a single block and with multiple blocks.  Testing with enough data to cause multiple blocks to run is necessary for this reason.
 - [x] [`ast_plan` needs docs](https://github.com/rapidsai/cudf/pull/5494/files/5ecd6fcd6e54c2c495ac0716de21bb7dd2297140#r474772732)
 - [x] [Move `ast_plan` initialization logic from `compuite_column` (in `transform.cu`) into `ast_plan` constructor.](https://github.com/rapidsai/cudf/pull/5494/files/5ecd6fcd6e54c2c495ac0716de21bb7dd2297140#r474739692)
 - [x] [`expression` constructors need SFINAE changes for correct functionality.](https://github.com/rapidsai/cudf/pull/5494#discussion_r474983646)

CC @bdice

**Comment by lamarrr** [comment]
I attempted a fix for the fourth one, here: https://github.com/rapidsai/cudf/pull/5494#discussion_r495262075

**Comment by harrism** [comment]
@codereport assigning this to you since you are looking at AST. Please let @jrhemstad and I know if that's not appropriate.
