### ISSUE TITLE
[FEA] Plumb edit_distance_matrix to Python

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#6341]
We should plumb edit_distance_matrix to the Cython layer. This could potentially live in the `cudf._lib.nvtext.edit_distance` namespace alongside the canonical `edit_distance`.

For now, I'm not sure we if need to plumb this all the way up to the Python layer. See https://github.com/rapidsai/cudf/issues/4569#issuecomment-600807535 in which we decided similarly for `find_multiple` based on efficiency and utility. With list column support we could plumb it all the way up if desired.

It would be useful if we could analogously do for `edit_distance_matrix` what we can currently do for `find_multiple`.

```python
from cudf._lib.strings import find_multiple
import cudf
import cupy as cp

a = cudf.Series(["rabbit","dog", "bird"])
b = cudf.Series(["a","b"])

out = find_multiple.find_multiple(a._column, b._column) # NumericalColumn output (contiguous buffer)
out = cp.asarray(out).reshape(-1, len(b)) # reshape to "actual" 2-d matrix representation
out
array([[ 1,  2],
       [-1, -1],
       [-1,  0]], dtype=int32)
```

**Comment by beckernick** [comment]
This is still necessary, and likely should be plumbed up to the Python layer given list column support. Updating the title accordingly.

**Comment by davidwendt** [comment]
From libcudf, it looks like `nvtext::edit_distance_matrix` returns a lists column whereas `cudf::strings::find_multiple` returns a single array. It would not be difficult to change `find_multiple` return a lists column if that is helpful.
