### ISSUE TITLE
[FEA] digitize on gpu bins

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#6360]
**Is your feature request related to a problem? Please describe.**

In < 0.15, `gdf[col].digitize(cudf.Series(...))` would work, but now throws an exception (no `.view()`). Looking at the code, this may because a coercion is gone (`series.view()`?) or maybe digitize changed.

Not filing it as a bug as b/c the digitize signature suggests we were using undocumented behavior.

**Describe the solution you'd like**

* digitize API accepts cudf series for bins, not just nd.array
* ... and hopefully implemented without a CPU round trip

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by kkraus14** [comment]
Looks like we're just missing an `as_column` call on `bins` within the Column `digitize` function.

**Comment by isVoid** [comment]
Working on improving the API and addressing the issue.
