### ISSUE TITLE
[BUG] Insufficient test coverage of ORC and Parquet statistics

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#6362]
Please see comment: 
https://github.com/rapidsai/cudf/pull/6293#issuecomment-701109873

* Parquet statistics are never enabled in tests;
* ORC has statistics enabled by default, but the tests look like they only test the resulting data frame content;

- [ ] ORC coverage (Vukasin)
- [ ] Parquet coverage (Devavret)

**Comment by vuule** [comment]
From what I've seen so far:
- Parquet statistics are never enabled in tests;
- ORC has statistics enabled by default, but the tests look like they only test the resulting data frame content;

I'll post here if there's any additional info from the rest of the team.

**Comment by vuule** [comment]
Some ORC coverage added in https://github.com/rapidsai/cudf/pull/6142. Planning to expand it.

**Comment by devavret** [comment]
I've added one orc statistics test based on #6142 . I'll try to add more to hopefully cover all the cases.
