### ISSUE TITLE
[BUG] List comparison testing creating thrust failures

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#6364]
**Describe the bug**
When comparing list columns using `CUDF_TEST_EXPECT_COLUMNS_EQUAL` with `print_all_differences` set to `true`, any difference in the columns will cause a thrust error and crash with the following error:

```
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  CUDA free failed: cudaErrorLaunchFailure: unspecified launch failure
Aborted (core dumped)
```

**Steps/Code to reproduce bug**
In `cpp/tests/reshape/byte_cast_tests.cpp` change any byte in `int16_expected`'s definition. Then add `true` as the third argument to the comparison on line 44 of the same file. This can be repeated with other tests, but this is the first and simplest case to recreate.

**Expected behavior**
The difference between to the two columns printed out without crashing and aborting the entire test suite.

**Additional context**
Error was traced to `cpp/tests/utilities/column_utilities.cu:163` -- something to do with the conversion of the differences to an `int32` column is causing the thrust failure. Commenting out lines 163 through 173 skips the thrust failure, but 164 through 173 still has the error.

**Comment by ttnghia** [comment]
This is fixed in https://github.com/rapidsai/cudf/pull/7382. Close.
