### ISSUE TITLE
[FEA] cuDF Parquet reader should use pinned memory to copy data from sysmem to GPU

### ISSUE THREAD

**Issue by chirayuG-nvidia** [rapidsai/cudf#6376]
**Is your feature request related to a problem? Please describe.**
NvTabular is building asynchronous dataloader for accelerating tabular dataloading for DL framework like PyTorch and TensorFlow. The primary function of this async dataloader is prepare training data by reading from Parquet input files and preparing input tensors for training. Currently Parquet reader in cuDF uses pageable memory to copy parquet input to GPU for decompression. HostToDeviceMemcpy from pageable memory leads to a lock in CUDA context that prevents from submitting other CUDA API calls from the framework training thread. Nsight profiler image at the end illustrate the problem.

**Describe the solution you'd like**
Memmapped Parquet input files can be first staged on a pinned system memory before issuing H2D memcpy, this will have additional overhead of a CPU memcpy but it will be good to implement and understand the performance improvements (or regressions) from this approach.

**Additional context**
![image](https://user-images.githubusercontent.com/48134467/94732645-6517f000-031b-11eb-9752-ae079322eecf.png)

@jperez999 @benfred @EvenOldridge to help further define NVT priority for this.

**Comment by jperez999** [comment]
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by devavret** [comment]
We are waiting on having a pool of pinned memory in RMM.

**Comment by vuule** [comment]
Once we switch to kvikIO for device reads, data from the input file will be transfered via pinned buffers in kvikIO's pool. I assume this will address the issue since that's the bulk of data copied onto the GPU.
Expecting to start using kvikIO in next release, will update this issue once we do.

**Comment by GregoryKimball** [comment]
I believe this is closed by #12574. Further improvements in data copying should be scoped within [kvikIO](https://github.com/rapidsai/kvikio).
