### ISSUE TITLE
[FEA] make/cmake uninstall target

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#642]
It would be great if we had a make/cmake uninstall command to allow for purging a previously installed libcudf that isn't managed by conda.

**Comment by beckernick** [comment]
@robertmaynard is this issue still relevant?

**Comment by robertmaynard** [comment]
I presume it would be still relevant. By default CMake doesn't offer this feature so it would require some investigation

**Comment by vyasr** [comment]
I think this is out of scope for any particular library like cudf. If we want this functionality, it should be implemented via cmake.
