### ISSUE TITLE
[FEA] Replace `pair_iterator` with `thrust::optional`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#6470]
**Is your feature request related to a problem? Please describe.**

libcudf currently provides a `pair_iterator` that returns a `pair<T, bool>` for each element in a column:
https://github.com/rapidsai/cudf/blob/48e9d1bb15c73f241a173bb6de02dbf496aa87bf/cpp/include/cudf/detail/iterator.cuh#L132-L157

This is useful for nullable inputs to generic code paths that operate on iterators. 

However, the `pair` approach is a bit cumbersome as it requires accessing the `first` and `second` members which reduce legibility.

The [`std::optional`](https://en.cppreference.com/w/cpp/utility/optional) (and `thrust::optional`) type was specifically designed to replace the use of a `pair<T,bool>`:
> As opposed to other approaches, such as std::pair<T,bool>, optional handles expensive-to-construct objects well and **is more readable, as the intent is expressed explicitly.**

**Describe the solution you'd like**

We should standardize on using `thrust::optional<T>` in-lieu of `pair<T,bool>` and make a new iterator that returns `thrust::optional<T>` for each element in a column. We can then replace `pair_iterator` with this new iterator. 

With this new iterator I think we should be stadandarizing more `detail::` algorithms in libcudf to operate on iterators that return `thrust::optional<T>` for nullable inputs. That allows us to write algorithms that can generically operate on `scalar`s or `column`s. 

**Additional context**

This is purely a code quality change to be more in line with canonical C++.

**Comment by vyasr** [comment]
I think this is resolved by https://github.com/rapidsai/cudf/pull/7772 and the usage of `optional_iterator` in follow-up PRs. @robertmaynard @jrhemstad please reopen if you disagree.
