### ISSUE TITLE
[FEA] rolling.cu takes too long to compile. Consider refactoring

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#6472]
It looks like `rolling.cu` is taking about 5 minutes to compile. This might possibly have to do with the addition of new rolling-window operations (`grouped_rolling_window()`, `time_based_*rolling_window()`, `rolling_window_udf()`) and the new aggregations that it supports.

It might be wise to split this into multiple translation units, to better parallelize the compile.

**Comment by jrhemstad** [comment]
I'm going to say this is more of a feature request than a bug, but it would be very nice.

**Comment by mythrocks** [comment]
I'll try have a patch out for this today.

**Comment by mythrocks** [comment]
So much for the naive approach. The issue is with the time-range overloads. Still investigating.
