### ISSUE TITLE
[FEA] support read/write parquet/orc with fixed-point decimal data

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#6474]
Considering both parquet and orc support fixed-point decimal type, I think we should support reading decimal columns from parquet/orc as fixed_point columns and writing fixed_point columns to parquet/orc as decimal type. 
This feature is quite helpful in terms of spark-rapids.

Currently, 
* parquet/orc reader convert decimal type to float64 (int64) while decoding data.
* parquet/orc writer can not write data of fixed_point type.

**Comment by harrism** [comment]
This is targeted for v0.18, after the currently in progress cuIO refactor of parquet/orc.
