### ISSUE TITLE
[FEA] Use official NVTX from GitHub 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#6476]
**Is your feature request related to a problem? Please describe.**

libcudf currently [vendors a prototype version](https://github.com/rapidsai/cudf/blob/branch-0.16/cpp/include/cudf/detail/nvtx/nvtx3.hpp) of the NVTX C++ wrappers that are now hosted [officially on GitHub](https://github.com/NVIDIA/NVTX/tree/dev/cpp).

**Describe the solution you'd like**

Remove the vendored header and instead use CMake/CPM to pull the header from GitHub.

**Comment by harrism** [comment]
The official version appears to still be in the `dev` branch. Any idea when it will be released?

**Comment by jrhemstad** [comment]
> The official version appears to still be in the `dev` branch. Any idea when it will be released?

Our goal is to have a tagged release done by end of October.

**Comment by harrism** [comment]
Still waiting on the tagged release.

**Comment by vyasr** [comment]
@jrhemstad any idea what the blocker is on tagging a release for NVTX? [The last one that I see](https://github.com/NVIDIA/NVTX/tags) is the June 2020 version 3.0.1 release. All of the upstream dependencies have been merged, it seems?

**Comment by jrhemstad** [comment]
The necessary changes are now in the official `release-v3` branch and there is a 3.1 release tag: https://github.com/NVIDIA/NVTX/releases/tag/v3.1.0

We should be good now to remove our vendored header in favor of getting nvtx from the GitHub repo.

**Comment by davidwendt** [comment]
Will this include an equivalent fix created here https://github.com/rapidsai/cudf/pull/11798 ?
Or do we have to do something else to work around the warning?

**Comment by jrhemstad** [comment]
> Will this include an equivalent fix created here #11798 ? Or do we have to do something else to work around the warning?

I opened a PR with a fix for that warning here: https://github.com/NVIDIA/NVTX/pull/61
