### ISSUE TITLE
[BUG] Corrupt data when converting list columns to/from parquet

### ISSUE THREAD

**Issue by benfred** [rapidsai/cudf#6477]
**Describe the bug**

Writing a dataframe with a list column to parquet results in different data when that parquet file is read back in.

This seems to only occur when the parquet file contains more than 1 row group: small datasets won't trigger this bug.

**Steps/Code to reproduce bug**
Minimal repro is here:

```python
import cudf
import cupy

# if we reduce num_rows to < 2M or so this all works
num_rows = 10_000_000
num_docs = num_rows / 2
num_categories = 1_000

# generate a random pairing of doc: category
documents = cudf.DataFrame(
    {
        "document_id": cupy.random.randint(num_docs, size=num_rows),
        "category_id": cupy.random.randint(num_categories, size=num_rows),
    }
)

# group categories by document_id to create a list column
original = documents.groupby("document_id").agg({"category_id": ["collect"]})
original.columns = original.columns.get_level_values(0)
original.reset_index(inplace=True)

# round trip the dataframe to/from parquet
original.to_parquet("test.parquet")
restored = cudf.read_parquet("test.parquet")

# if we have more than 1 rowgroup the restored dataframe contains different data
# than the original dataframe
print("# of row groups", cudf.io.parquet.read_parquet_metadata("test.parquet")[1])
print(original)
print(restored)
```

**Expected behavior**
The original and restored dataframe should have the same values

**Environment overview (please complete the following information)**
 - Environment location: bare-metal
 - Method of cuDF install: source, latest 0.16 branch

**Comment by devavret** [comment]
Triaging this with Ben offline, it seems like a reader issue

**Comment by benfred** [comment]
This seems likely an issue with ```cudf.read_parquet```. When writing out the dataframe with pandas - and then reading back with cudf we still have the same problem.  

```
original.to_pandas().to_parquet("pandas.parquet", row_group_size=100000) 
cudf.read_parquet("pandas.parquet")  # exhibits the same bug
```

**Comment by nvdbaranec** [comment]
Do we know if this is a recent behavioral change?  That is - was it working, say a week ago?   Wondering if the parquet struct PR might be the cause.

**Comment by benfred** [comment]
@nvdbaranec It looks like this bug exists in cudf 0.15, so I don't think this is because of the recent changes.

I just installed the stable cudf 0.15 to test this out - and I'm seeing this same behaviour in cudf 0.15. Reading the input file generated in the script with cudf 0.15 returns incorrect results, while reading with pandas works .

**Comment by nvdbaranec** [comment]
Ok, thanks.  I believe I've identified the issue.  Should have a PR up for you to try Monday morning.
