### ISSUE TITLE
[FEA] Add new parameter to cudf::gather to enable behavior of negative indices beget null elements

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#6479]
This is the second of a series of issues as part of a larger join refactor. 

It would be great if `cudf::gather` exposed a way to get `null` when negative indices are specified in the gather map. 

```
cudf::gather({1, 2, 3, 4, 5, 6}, {1, 3, -1}) == {2, 4, null}
```

The `join` API is going to be refactored to return gather map(s) instead of the actual result of a join. This is so callers have the freedom to construct the output table in whatever way they like. Currently, the libcudf join code and join API are both complicated because it tries to construct an output table that meets Pandas' expectations. As a consequence, the Cython and Python code is also complicated.

This feature will enable the libcudf join API to return a gather map with negative values to indicate non-matches in outer joins.

cc: @jrhemstad

**Comment by jrhemstad** [comment]
> negative indices

While the original intention is for negative indices, I think we can expand it just to say that any out of bounds index yields a null.

**Comment by shwina** [comment]
cc: @brandon-b-miller as well

**Comment by mythrocks** [comment]
> It would be great if `cudf::gather` exposed a way to get null when negative indices are specified in the gather map.

I didn't realize that the following code wasn't the prescribed way to achieve that effect:
```c++
    auto output_table = detail::gather(table_view{{input}},
                                       output->view(),
                                       detail::out_of_bounds_policy::IGNORE,
                                       detail::negative_index_policy::NOT_ALLOWED,
                                       mr,
                                       stream);
```
This is from [rolling.cu](https://github.com/rapidsai/cudf/blob/f2935881a433a97418191edf3643b20c8eaa0334/cpp/src/rolling/rolling.cu#L662).

**Comment by shwina** [comment]
I think that code does do that, but this is not exposed in the public API

**Comment by mythrocks** [comment]
Ah, so. Gotcha.

**Comment by shwina** [comment]
This is now enabled with the `NULLIFY` out of bounds policy introduced in #6523. Closing.
