### ISSUE TITLE
[FEA] Add a join API that returns gather maps rather than a table

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#6480]
This would depend on #6479 and #6478 

It would be great if libcudf had a `join` API that returned gather map(s) (one in case of an `inner` join and two in case of outer joins). For example:

```c++
std::pair<std::unique_ptr<cudf::column>, std::unique_ptr<cudf::column>> left_join(...);
```

As explained in #6479 , this could result in simpler join code, both in the C++ as well as in Python.

As follow up tasks to this feature, we should:

- Update Python bindings to use the new gather map API
- Remove the `columns_in_common` option from the existing libcudf join APIs - since Python will no longer need it
- Refactor the existing libcudf join APIs to just call the new API that returns a gather map

**Comment by shwina** [comment]
cc: @jrhemstad

**Comment by jlowe** [comment]
We would love to see this for the RAPIDS plugin for Spark as well.  There are many cases where a join occurs in the query and one or more keys involved in the join do not appear in the output table.  The current cudf join APIs always manifest the key columns in the join result.  Having the gather maps join API allows us to gather only the output columns that are needed.
