### ISSUE TITLE
[DISCUSS] cuDF internal/developer documentation

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#6481]
Because cuDF is designed and written differently from many other Python libraries, it's important that we document our internals and design choices carefully. Currently, it can be a significant effort for someone to start contributing to the cuDF source code due to the lack of developer documentation.

We're developing an outline for our dev docs here:

https://docs.google.com/document/d/1gJOw2-DuzfpNz1CPiwgw3cf3Ag1h8tu_j_kPFYCgg8k/edit#heading=h.3fq7j7kityfk

Feedback and suggestions are very much appreciated.

**Comment by shwina** [comment]
Still very much needed.

**Comment by shwina** [comment]
Yeah that sounds like a really good place to start.

**Comment by harrism** [comment]
In case it helps, libcudf has a developer guide here: https://github.com/rapidsai/cudf/blob/branch-21.06/cpp/docs/DEVELOPER_GUIDE.md

**Comment by shwina** [comment]
I'll target this for 21.08 along with the array refactor.

**Comment by vyasr** [comment]
I've been working on this and can take it off @shwina's plate.

**Comment by vyasr** [comment]
We should be able to close this issue between https://github.com/rapidsai/cudf/pull/11217, https://github.com/rapidsai/cudf/pull/11199, https://github.com/rapidsai/cudf/pull/11122, https://github.com/rapidsai/cudf/pull/11235, and https://github.com/rapidsai/cudf/pull/10817
