### ISSUE TITLE
License issues when switching to conda

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#6484]
https://github.com/conda-forge/conda-forge.github.io/issues/209#issuecomment-706439782

Conda bundles GPL in several packages that would be normally used.  This makes the switch to conda a problem for any company wishing to adopt rapids.

**Comment by kkraus14** [comment]
This seems like a conda issue as opposed to a cuDF or RAPIDS issue. I'm not sure what we can do to help with conda GPL licensing issues from the RAPIDS side of things.

If the ask is to provide easier ways of installing RAPIDS libraries outside of conda:
- Our stance on pip packaging: https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472
- For building from source: https://github.com/rapidsai/cudf/issues/2770

**Comment by pseudotensor** [comment]
There is no "rapids" github to post broader issues.   Yes, I'm aware of the lack of pip support and why.

Building from all packages, beyond cudf, related to rapids by source is not easy.  The build.sh scripts do not work for half of the rapids repos.  One can make Ubuntu work after several changes, but centos has issues building rmm making it a non-starter approach.  This is not the rmm repo, and cudf itself build only requires a handful of changes/fixes compared to what is posted.

**Comment by kkraus14** [comment]
> Building from all packages, beyond cudf, related to rapids by source is not easy. The build.sh scripts do not work for half of the rapids repos. One can make Ubuntu work after several changes, but centos has issues building rmm making it a non-starter approach. This is not the rmm repo, and cudf itself build only requires a handful of changes/fixes compared to what is posted.

Opening github issue(s) on the repos that you're interested in with the current problems you're running into when using `build.sh` would be greatly appreciated. We want to make installing a smooth process and right now `build.sh` assumes that dependencies are already installed in certain ways, and many of these assumptions are likely incorrect.
