### ISSUE TITLE
[FEA] type casting between fixed-point decimal and other numeric types

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#6486]
**What is your question?**
According to the checklist of [issue 3556](https://github.com/rapidsai/cudf/issues/3556), we are able to _cast to/from floats, ints and decimal with other precision/accuracy_ in cuDF. How can we achieve that? 
`cudf::logical_cast` alone doesn't seem to be the right solution. For integer types, we can perform cudf::logicial_cast after rescaling fix_point data to zero. But how to deal with float_point types?
 @codereport can you help to give some advice? Thanks!

**Comment by harrism** [comment]
@codereport I unchecked the box next to 

> cast to/from floats, ints and decimal with other precision/accuracy

because I looked at cast_ops.cu and I see multiple `CUDF_FAIL("Fixed point unary ops currently not supported");`.

Casting between types is a unary operation. Apparently this is not implemented yet. Converting this issue into a feature request.

**Comment by harrism** [comment]
Assigning to @codereport for 0.17.

**Comment by sperlingxx** [comment]
@codereport @harrism 
May I ask about the progress on this issue? The release_0.3 of spark-rapids project heavily depends on this feature, so we really want to know when this feature will be ready.
Sorry for any disturbing :)

**Comment by codereport** [comment]
I am wrapping up `cudf::round` and this will be next. Should be done before 0.17 is released.

**Comment by shwina** [comment]
Oops - apologies. Can someone please move this back to P0? @harrism @kkraus14
