### ISSUE TITLE
[FEA] Dask_cudf support Avro files

### ISSUE THREAD

**Issue by albert17** [rapidsai/cudf#6496]
**Is your feature request related to a problem? Please describe.**
I want to use dask_cudf to read Avro files in NVTabular. 

**Describe the solution you'd like**
dask_cudf implementation for Avro files. Similar to existing support for CSV, Parquet, Json, and ORC. 

**Describe alternatives you've considered**
I have thought about implementing the Dask version within NVTabular using cudf. It would work, but it may make more sense to have an implementation in rapids that is accessible by everyone.

**Additional context**
https://github.com/rapidsai/cudf/tree/main/python/dask_cudf/dask_cudf/io

**Comment by rjzamora** [comment]
NVTabular likes to have a mechanism to control the output partition sizes.  This is supported in csv and parquet (and can be supported in orc).  It will be easy to support a file <-> partition mapping for avro, but it may take a bit of work on the cudf side to handle (decompose) large avro files.

@albert17 - Do you suspect that the avro files are typically larger than the desired output partition?  Or, do you expect there to be many small files?

**Comment by albert17** [comment]
I don't know about the expected file size. Probably @benfred can answer this question better.

Do you @rjzamora think it is a better idea to implemented directly in NVTabular?

**Comment by rjzamora** [comment]
> Do you @rjzamora think it is a better idea to implemented directly in NVTabular?

No - It definitely makes sense to implement something in dask-cudf.  However, I wanted to clarify that the short-term dask-cudf solution would most likely map each file to a separate partition.

**Comment by rjzamora** [comment]
**Update**:  I submitted [a draft PR](https://github.com/dask/dask/pull/6740) to dask with an experimental `read_avro` design.  [This script](https://gist.github.com/rjzamora/bfc76bb95babc7bbb70842ec7ea3c106) demonstrates how cudf can be used (with that branch) to produce a Dask-CuDF DataFrame.

**Comment by GregoryKimball** [comment]
I'll close this for now, and we will reopen when Avro support receives a strong pull from the user base.
