### ISSUE TITLE
[BUG] Broken tests in debug build

### ISSUE THREAD

**Issue by mtjrider** [rapidsai/cudf#6521]
## Summary
When compiling `libcudf.so` with debug symbols, not all tests pass / execute without error.
The following is a list of tests that either fail or error:

* `COPYING_TEST`: does not compile
* `DICTIONARY_TEST`: illegal memory access
* `ERROR_TEST`: failure
* `FIXED_POINT_TEST`: illegal memory access
* `GROUPBY_TEST`: failure
* `INTEROP_TEST`: illegal memory access
* `JOIN_TEST`: unknown, indefinite hang
* `REDUCTION_TEST`: failure
* `REPLACE_NULLS_TEST`: failure
* `REPLACE_TEST`: illegal memory access
* `SEARCH_TEST`: illegal memory access
* `TEXT_TEST`: illegal memory access

where "illegal memory access" indicates that, at some point a `cudaErrorIllegalAddress` error was detected, and "failure" indicates that the test simply failed. I have attached a more complete report detailing precisely which sub-test prompted the error(s) or failure(s): [cudf-debug-test-log.txt](https://github.com/rapidsai/cudf/files/5374474/cudf-debug-test-log.txt)

## Reproducing the failures

Build `libcudf.so` with debugging symbols by cloning PR https://github.com/rapidsai/cudf/pull/6134 and configuring with `cmake .. -DCMAKE_BUILD_TYPE=Debug`. Alternatively, if you're using [RAPIDS compose](https://github.com/trxcllnt/rapids-compose), simply fetch/checkout the PR, and build the C++ cudf library with `build-cudf-cpp --debug`.

## Expected behavior

All tests should pass regardless of build type.

## Environment details

Built from source.
[print_env_out.txt](https://github.com/rapidsai/cudf/files/5374499/print_env_out.txt)

## Status

- [ ] `COPYING_TEST` fixed
- [ ] `DICTIONARY_TEST` fixed
- [ ] `ERROR_TEST` fixed
- [ ] `FIXED_POINT_TEST` fixed
- [ ] `GROUPBY_TEST` fixed
- [ ] `INTEROP_TEST` fixed
- [ ] `JOIN_TEST` fixed
- [ ] `REDUCTION_TEST` fixed
- [ ] `REPLACE_NULLS_TEST` fixed
- [ ] `REPLACE_TEST` fixed
- [ ] `SEARCH_TEST` fixed
- [ ] `TEXT_TEST` fixed

**Comment by harrism** [comment]
I'm hoping that cudaIllegalMemoryAccess failures are all the same problem. May be related to rapidsai/rmm#563.

**Comment by ttnghia** [comment]
Does this issue still persist? I see that all the tests status are "fixed".

**Comment by razajafri** [comment]
This is still a valid bug. I faced this yesterday, I only ran tests on the Java bindings and saw a heap of `IllegalMemoryAccess Errors`. The errors magically went away when I built cudf `Release` build. 

[illegalmemoryaccess.txt](https://github.com/rapidsai/cudf/files/6343561/illegalmemoryaccess.txt)
