### ISSUE TITLE
[BUG] DataFrame.sample() produces unexpected results

### ISSUE THREAD

**Issue by pruddle** [rapidsai/cudf#6532]
**Describe the bug**
DataFrame.sample() returns values not present in the original dataframe

**Steps/Code to reproduce bug**
```
import cudf

df = cudf.DataFrame([1,2], columns=['col1'])
num_trials = 1000

results = []
for _ in range(0,num_trials): 
    results.append(df.sample(frac = 1, replace = True))
    
df = cudf.concat(results)

df['col1'].nunique()
```

**Expected behavior**
I expect "2" to be returned rather than "3".  Running the same code against a pandas dataframe returns "2"

**Environment overview (please complete the following information)**
 - Environment location:  Domino Data Lab on AWS
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 64c68fa0947a7dafe0d87077dfac5886a608a99c (HEAD -> master, origin/master)
     Author: Paul Ruddle <paul.ruddle@cigna.com>
     Date:   Wed Oct 14 15:46:31 2020 +0000
     
     update with spark etl
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux run-5f872801f48a01381982fee8-qw6bp 4.14.193-149.317.amzn2.x86_64 #1 SMP Thu Sep 3 19:04:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Oct 14 21:20:41 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.00    Driver Version: 418.87.00    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
     | N/A   51C    P0    45W / 300W |   2218MiB / 16130MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              8
     On-line CPU(s) list: 0-7
     Thread(s) per core:  2
     Core(s) per socket:  4
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
     Stepping:            1
     CPU MHz:             2650.888
     CPU max MHz:         3000.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4600.16
     Hypervisor vendor:   Xen
     Virtualization type: full
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            46080K
     NUMA node0 CPU(s):   0-7
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx xsaveopt
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.10.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/ubuntu/.conda/envs/rapids/bin/python
     Python 3.7.9
     
     ***Environment Variables***
     PATH                            : /home/ubuntu/.conda/envs/rapids/bin:/opt/conda/condabin:/home/ubuntu/.local/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/opt/code-server:/opt/oracle/instantclient_12_1:/home/ubuntu/.local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/scala/bin:/opt/oracle/instantclient_12_1:/home/ubuntu/.local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/tmp:/opt/oracle/instantclient_12_1:/home/ubuntu/.local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/share/scala/bin:/opt/oracle/instantclient_12_1:/home/ubuntu/.local/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/oracle/instantclient_12_1:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/ubuntu/.conda/envs/rapids
     PYTHON_PATH                     :
     
     ***conda packages***
     /opt/conda/condabin/conda
     # packages in environment at /home/ubuntu/.conda/envs/rapids:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     aiohttp                   3.6.2            py37h8f50634_1    conda-forge
     appdirs                   1.4.3                      py_1    conda-forge
     argon2-cffi               20.1.0           py37h8f50634_2    conda-forge
     arrow-cpp                 0.17.1          py37h1234567_11_cuda    conda-forge
     arrow-cpp-proc            1.0.1                      cuda    conda-forge
     async-timeout             3.0.1                   py_1000    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.2.0             pyh9f0ad1d_0    conda-forge
     aws-sdk-cpp               1.7.164              hba45d7a_2    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.2            py37hc8dfbb8_0    conda-forge
     boost                     1.72.0           py37h48f8a5e_1    conda-forge
     boost-cpp                 1.72.0               h8e57a91_0    conda-forge
     brotli                    1.0.9                he1b5a44_2    conda-forge
     brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
     bzip2                     1.0.8                h516909a_3    conda-forge
     c-ares                    1.16.1               h516909a_3    conda-forge
     ca-certificates           2020.6.20            hecda079_0    conda-forge
     cairo                     1.16.0            hcf35c78_1003    conda-forge
     certifi                   2020.6.20        py37he5f6b98_2    conda-forge
     cffi                      1.14.3           py37he30daa8_0
     cfitsio                   3.470                hce51eda_7    conda-forge
     chardet                   3.0.4           py37he5f6b98_1008    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     click-plugins             1.1.1                      py_0    conda-forge
     cligj                     0.5.0                      py_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     colorcet                  2.0.1                      py_0    conda-forge
     cryptography              3.1.1            py37hff6837a_1    conda-forge
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudf                      0.15.0          cuda_10.1_py37_g71cb8c0e0_0    rapidsai
     cudf_kafka                0.15.0          py37_g71cb8c0e0_0    rapidsai
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cugraph                   0.15.0          py37_gb34091ac_0    rapidsai
     cuml                      0.15.0          cuda10.1_py37_ga3002e587_0    rapidsai
     cupy                      7.8.0            py37h0632833_1    conda-forge
     curl                      7.71.1               he644dc0_8    conda-forge
     cusignal                  0.15.0          py37_gdac6dff_0    rapidsai
     cuspatial                 0.15.0          py37_gc5b7527_0    rapidsai
     custreamz                 0.15.0          py37_g71cb8c0e0_0    rapidsai
     cuxfilter                 0.15.0          py37_gf17ebcb_0    rapidsai
     cyrus-sasl                2.1.27               h063b49f_1    conda-forge
     cytoolz                   0.11.0           py37h8f50634_1    conda-forge
     dask                      2.30.0                     py_0    conda-forge
     dask-core                 2.30.0                     py_0    conda-forge
     dask-cuda                 0.15.0                   py37_0    rapidsai
     dask-cudf                 0.15.0          py37_g71cb8c0e0_0    rapidsai
     dask-xgboost              0.2.0.dev28      cuda10.1py37_0    rapidsai
     datashader                0.11.1             pyh9f0ad1d_0    conda-forge
     datashape                 0.5.4                      py_1    conda-forge
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distributed               2.30.0           py37hc8dfbb8_1    conda-forge
     dlpack                    0.3                  he1b5a44_1    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     faiss-proc                1.0.0                      cuda    conda-forge
     fastavro                  1.0.0.post1      py37h8f50634_1    conda-forge
     fastrlock                 0.5              py37h3340039_1    conda-forge
     fiona                     1.8.13           py37h0492a4a_1    conda-forge
     fontconfig                2.13.1            h86ecdb6_1001    conda-forge
     freetype                  2.10.3               he06d7ca_0    conda-forge
     freexl                    1.0.5             h516909a_1002    conda-forge
     fsspec                    0.8.3                      py_0    conda-forge
     gdal                      3.0.4           py37h4b180d9_10    conda-forge
     geopandas                 0.8.1                      py_0    conda-forge
     geos                      3.8.1                he1b5a44_0    conda-forge
     geotiff                   1.6.0                h05acad5_0    conda-forge
     gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     giflib                    5.2.1                h516909a_2    conda-forge
     glib                      2.65.0               h3eb4bd4_0
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     hdf4                      4.2.13            hf30be14_1003    conda-forge
     hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     importlib-metadata        2.0.0                      py_1    conda-forge
     importlib_metadata        2.0.0                         1    conda-forge
     ipykernel                 5.3.4            py37hc6149b9_1    conda-forge
     ipython                   7.18.1           py37hc6149b9_1    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
     jedi                      0.17.2           py37hc8dfbb8_1    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     joblib                    0.17.0                     py_0    conda-forge
     jpeg                      9d                   h516909a_0    conda-forge
     json-c                    0.13.1            hbfbb72e_1002    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter-server-proxy      1.5.0                      py_0    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.6.3            py37hc8dfbb8_2    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     kealib                    1.4.13               h33137a7_1    conda-forge
     krb5                      1.17.1               hfafb76e_3    conda-forge
     lcms2                     2.11                 hbd6801e_0    conda-forge
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.8.0               17_openblas    conda-forge
     libcblas                  3.8.0               17_openblas    conda-forge
     libcudf                   0.15.0          cuda10.1_g71cb8c0e0_0    rapidsai
     libcudf_kafka             0.15.0             g71cb8c0e0_0    rapidsai
     libcugraph                0.15.0          cuda10.1_gb34091ac_0    rapidsai
     libcuml                   0.15.0          cuda10.1_ga3002e587_0    rapidsai
     libcumlprims              0.15.0          cuda10.1_gdbd0d39_0    nvidia
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libcuspatial              0.15.0          cuda10.1_gc5b7527_0    rapidsai
     libdap4                   3.20.6               h1d1bd15_1    conda-forge
     libedit                   3.1.20191231         h14c3975_1
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libfaiss                  1.6.3           he68dc02_3_cuda    conda-forge
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
     libgcrypt                 1.8.4             hf484d3e_1000    conda-forge
     libgdal                   3.0.4               he6a97d6_10    conda-forge
     libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
     libgfortran4              7.5.0               hae1eefd_17    conda-forge
     libgomp                   9.3.0               h5dbcf3e_17    conda-forge
     libgpg-error              1.39                 he1b5a44_0    conda-forge
     libgsasl                  1.8.0                         2    conda-forge
     libhwloc                  2.1.0                h3c4fd83_0    conda-forge
     libiconv                  1.16                 h516909a_0    conda-forge
     libkml                    1.3.0             hd79254b_1012    conda-forge
     liblapack                 3.8.0               17_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libnetcdf                 4.7.4           nompi_h84807e1_105    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libntlm                   1.4               h516909a_1002    conda-forge
     libopenblas               0.3.10          pthreads_hb3c22a3_5    conda-forge
     libpng                    1.6.37               hed695b0_2    conda-forge
     libpq                     12.3                 h5513abc_1    conda-forge
     libprotobuf               3.12.4               h8b12597_0    conda-forge
     librdkafka                1.4.0                h40bdf00_0    conda-forge
     librmm                    0.15.0          cuda10.1_g8005ca5_0    rapidsai
     libsodium                 1.0.18               h516909a_1    conda-forge
     libspatialindex           1.9.3                he1b5a44_3    conda-forge
     libspatialite             4.3.0a            h2482549_1038    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.1.0                hdf63c60_0
     libthrift                 0.13.0               hbe8ec66_6    conda-forge
     libtiff                   4.1.0                hc7e4089_6    conda-forge
     libuuid                   2.32.1            h14c3975_1000    conda-forge
     libuv                     1.34.0               h516909a_0    conda-forge
     libwebp                   1.1.0                h56121f0_4    conda-forge
     libwebp-base              1.1.0                h516909a_3    conda-forge
     libxcb                    1.13              h14c3975_1002    conda-forge
     libxgboost                1.2.0dev.rapidsai0.15    cuda10.1_611    rapidsai
     libxml2                   2.9.10               hee79883_0    conda-forge
     llvmlite                  0.34.0           py37h5202443_2    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.3.1              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
     mistune                   0.8.4           py37h8f50634_1002    conda-forge
     msgpack-python            1.0.0            py37h99015e2_2    conda-forge
     multidict                 4.7.5            py37h8f50634_2    conda-forge
     multipledispatch          0.6.0                      py_0    conda-forge
     munch                     2.5.0                      py_0    conda-forge
     nbclient                  0.5.0                      py_0    conda-forge
     nbconvert                 6.0.7            py37hc8dfbb8_0    conda-forge
     nbformat                  5.0.7                      py_0    conda-forge
     nccl                      2.7.8.1              h51cf6c1_1    conda-forge
     ncurses                   6.2                  he6710b0_1
     nest-asyncio              1.4.1                      py_0    conda-forge
     nodejs                    13.13.0              hf5d1a2b_0    conda-forge
     notebook                  6.1.4            py37hc8dfbb8_0    conda-forge
     numba                     0.51.2           py37h9fdb41a_0    conda-forge
     numpy                     1.19.2           py37h7ea13bd_1    conda-forge
     olefile                   0.46                       py_0    conda-forge
     openjpeg                  2.3.1                h981e76c_3    conda-forge
     openssl                   1.1.1h               h516909a_0    conda-forge
     packaging                 20.4               pyh9f0ad1d_0    conda-forge
     pandas                    1.1.3            py37h9fdb41a_2    conda-forge
     pandoc                    2.11                 hd18ef5c_0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     panel                     0.9.7                      py_0    conda-forge
     param                     1.9.3                      py_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pcre                      8.44                 he1b5a44_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickle5                   0.0.11           py37h8f50634_0    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    7.2.0            py37h718be6c_2    conda-forge
     pip                       20.2.3                   py37_0
     pixman                    0.38.0            h516909a_1003    conda-forge
     poppler                   0.87.0               h4190859_1    conda-forge
     poppler-data              0.4.9                         1    conda-forge
     postgresql                12.3                 h8573dbc_1    conda-forge
     proj                      7.0.0                h966b41f_5    conda-forge
     prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
     prompt-toolkit            3.0.8                      py_0    conda-forge
     psutil                    5.7.2            py37hb5d75c8_1    conda-forge
     pthread-stubs             0.4               h14c3975_1001    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py-xgboost                1.2.0dev.rapidsai0.15 cuda10.1py37_611    rapidsai
     pyarrow                   0.17.1          py37h1234567_11_cuda    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyct                      0.4.6                      py_0    conda-forge
     pyct-core                 0.4.6                      py_0    conda-forge
     pydeck                    0.4.1              pyh9f0ad1d_0    conda-forge
     pyee                      7.0.4              pyh9f0ad1d_0    conda-forge
     pygments                  2.7.1                      py_0    conda-forge
     pynvml                    8.0.4                      py_1    conda-forge
     pyopenssl                 19.1.0                     py_1    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyppeteer                 0.2.2                      py_1    conda-forge
     pyproj                    2.6.1.post1      py37h34dd122_0    conda-forge
     pyrsistent                0.17.3           py37h8f50634_1    conda-forge
     pysocks                   1.7.1            py37he5f6b98_2    conda-forge
     python                    3.7.9                h7579374_0
     python-confluent-kafka    1.3.0            py37h8f50634_1    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1             pyh9f0ad1d_0    conda-forge
     pyviz_comms               0.7.6              pyh9f0ad1d_0    conda-forge
     pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
     pyzmq                     19.0.2           py37hac76be4_2    conda-forge
     rapids                    0.15.1          cuda10.1_py37_gc1db54b_5    rapidsai
     rapids-xgboost            0.15.1          cuda10.1_py37_gc1db54b_5    rapidsai
     re2                       2020.07.06           he1b5a44_1    conda-forge
     readline                  8.0                  h7b6447c_0
     requests                  2.24.0             pyh9f0ad1d_0    conda-forge
     rmm                       0.15.0          cuda_10.1_py37_g8005ca5_0    rapidsai
     rtree                     0.9.4            py37h8526d28_1    conda-forge
     scikit-learn              0.23.2           py37h6785257_0    conda-forge
     scipy                     1.5.2            py37hb14ef9d_1    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                50.3.0           py37hb0f4dca_1
     shapely                   1.7.1            py37hedb1597_1    conda-forge
     simpervisor               0.3                        py_1    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     sortedcontainers          2.2.2              pyh9f0ad1d_0    conda-forge
     spdlog                    1.8.1                hc9558a2_0    conda-forge
     sqlite                    3.33.0               h62c20be_0
     streamz                   0.6.0              pyh9f0ad1d_0    conda-forge
     tbb                       2020.2               hc9558a2_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.1            py37hc8dfbb8_1    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
     thrift-compiler           0.13.0               hbe8ec66_6    conda-forge
     thrift-cpp                0.13.0                        6    conda-forge
     tiledb                    1.7.7                h8efa9f0_3    conda-forge
     tk                        8.6.10               hbc83047_0
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.0.4            py37h8f50634_2    conda-forge
     tqdm                      4.50.2             pyh9f0ad1d_0    conda-forge
     traitlets                 5.0.4                      py_1    conda-forge
     treelite                  0.92             py37h023e13c_2    conda-forge
     treelite-runtime          0.92                     pypi_0    pypi
     typing-extensions         3.7.4.2                       0    conda-forge
     typing_extensions         3.7.4.2                    py_0    conda-forge
     tzcode                    2020a                h516909a_0    conda-forge
     ucx                       1.8.1+g6b29558       cuda10.1_0    rapidsai
     ucx-py                    0.15.0+g6b29558          py37_0    rapidsai
     urllib3                   1.25.10                    py_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     websockets                8.1              py37h8f50634_2    conda-forge
     wheel                     0.35.1                     py_0
     widgetsnbextension        3.5.1            py37hc8dfbb8_1    conda-forge
     xarray                    0.16.1                     py_0    conda-forge
     xerces-c                  3.2.2             h8412b87_1004    conda-forge
     xgboost                   1.2.0dev.rapidsai0.15 cuda10.1py37_611    rapidsai
     xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
     xorg-libice               1.0.10               h516909a_0    conda-forge
     xorg-libsm                1.2.3             h84519dc_1000    conda-forge
     xorg-libx11               1.6.12               h516909a_0    conda-forge
     xorg-libxau               1.0.9                h14c3975_0    conda-forge
     xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
     xorg-libxext              1.3.4                h516909a_0    conda-forge
     xorg-libxrender           0.9.10            h516909a_1002    conda-forge
     xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
     xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
     xorg-xproto               7.0.31            h14c3975_1007    conda-forge
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h516909a_0    conda-forge
     yarl                      1.6.2            py37h8f50634_0    conda-forge
     zeromq                    4.3.3                he1b5a44_2    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.3.0                      py_0    conda-forge
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Comment by pruddle** [comment]
Additional information I discovered on further exploration, this only reproduces when replace = True.  Replace = False has the expected behavior.

**Comment by ChrisJar** [comment]
I can work on this
