### ISSUE TITLE
[FEA] Add support for KFold CrossValidation Iterator in dask_cudf

### ISSUE THREAD

**Issue by miroenev** [rapidsai/cudf#6535]
Sklearn and dask_ml have cross-validation iterators that enable the mapping of the train and test data subsets onto non-overlapping groups/folds of equal sizes. The performance measure reported by k-fold cross-validation is then the average of the values computed in the loop. 

https://scikit-learn.org/stable/modules/cross_validation.html#k-fold
https://ml.dask.org/modules/generated/dask_ml.model_selection.KFold.html

It would be great to have similar functionality for dask_cudf datasets/dataframes however the current dask_ml implementation only works with dask arrays.

```preload dask_cudf.core.DataFrame
data = dask_cudf.read_parquet( ... )

from dask_ml.model_selection import KFold

kf = KFold( n_splits=10 )

for train, test in kf.split( data ):
    print("%s %s" % (train, test))
```

>     ---------------------------------------------------------------------------
>     TypeError                                 Traceback (most recent call last)
>     <ipython-input-71-93f2b63b1d3b> in <module>
>     ----> 1 for train, test in kf.split(data):
>         2     print("%s %s" % (train, test))
> 
>     /opt/conda/envs/rapids/lib/python3.8/site-packages/dask_ml/model_selection/_split.py in split(self, X, y, groups)
>         239 
>         240     def split(self, X, y=None, groups=None):
>     --> 241         X = check_array(X)
>         242         n_samples = X.shape[0]
>         243         n_splits = self.n_splits
> 
>     /opt/conda/envs/rapids/lib/python3.8/site-packages/dask_ml/utils.py in check_array(array, accept_dask_array, accept_dask_dataframe, accept_unknown_chunks, accept_multiple_blocks, preserve_pandas_dataframe, remove_zero_chunks, *args, **kwargs)
>         178     elif isinstance(array, dd.DataFrame):
>         179         if not accept_dask_dataframe:
>     --> 180             raise TypeError(
>         181                 "This estimator does not support dask dataframes. "
>         182                 "This might be resolved with one of\n\n"
> 
>     TypeError: This estimator does not support dask dataframes. This might be resolved with one of
> 
>         1. ddf.to_dask_array(lengths=True)
>         2. ddf.to_dask_array()  # may cause other issues because of unknown chunk sizes
> 

---
Note that the code above works if the dataframe is converted to a dask array, however it is unclear how the returned dask.array.core.Array indexes can be used to row index into the original data [ dask_cudf.core.DataFrame ].
```
for train, test in kf.split(data.to_dask_array(lengths=True)):    
    print("%s, \n %s" % (train, test))

> dask.array<concatenate, shape=(8592337,), dtype=int64, chunksize=(645351,), chunktype=numpy.ndarray> ,
> dask.array<concatenate, shape=(954705,), dtype=int64, chunksize=(599268,), chunktype=numpy.ndarray>
  ...
```
**Describe the solution you'd like**
Ideally the KFold utility function could be applied to dask_cudf dataframes directly, and the resulting folds would be directly handed to upstream model training logic.

**Comment by rjzamora** [comment]
Perhaps it makes the most sense to raise an issue in [dask-ml](https://github.com/dask/dask-ml/issues)?

We can certainly track the feature here, but I suspect the necessary changes (to handle a DataFrame collection in `KFold.split`) will be mostly in dask/dask-ml (and maybe dask/dask).

**Comment by beckernick** [comment]
> Perhaps it makes the most sense to raise an issue in dask-ml?

Agreed. I don't think there is currently an action from the cuDF side. Happy to continue the discussion on dask-ml or cuml as appropriate. Closing, but please feel free to re-open if discussion needs to happen here.
