### ISSUE TITLE
[FEA] Replace all `cudaMemcpyAsync(hostdevice_vector)`

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6538]
Replace all `cudaMemcpyAsync(hostdevice_vector)` with `hostdevice_vector.device_to_host()` or `hostdevice_vector.host_to_device()` as appropriate.

Example:
https://github.com/rapidsai/cudf/blob/bfd83f3388d47d816342d5a7ed29a0ed28a62bd9/cpp/src/io/parquet/writer_impl.cu#L442-L443

**Comment by vuule** [comment]
Looks like #7035 addressed all instances where the entire buffer is copied over. We need changes to the sync API to avoid the remaining raw copies. Closing the issue based on this.
