### ISSUE TITLE
[FEA] Segmented sort / sorted_order (argsort)

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#6541]
**Is your feature request related to a problem? Please describe.**
Given we now support list columns, we could use functions for segmented sorts and sorted_order (argsort) to sort the list elements within a column. Only handling 1 depth of lists should be fine for now and if we need arbitrary nesting we could revisit in the future.

**Describe the solution you'd like**
For example say we had a table that looked like:
| a | b | c |
| - | - | - |
| [21, 22, 23, 22] | [13, 14, 12, 11] | ["a", "b", "c", "d"] |
| [22, 21, 23, 22] | [14, 13, 12, 11] | ["a", "b", "c", "d"] |

I'd like to be able to run a segmented `sorted_order (argsort)` against column `a` which would return a new `list<int32>` column that could be used to gather other `list` columns:
| segmented_gather_map |
| - |
| [0, 1, 3, 2] |
| [1, 0, 3, 2] |

Additionally, it should be able to handle multiple columns as well. I.E. columns `a` and `b`:
| segmented_gather_map |
| - |
| [0, 3, 1, 2] |
| [1, 3, 0, 2] |

Then for a `sort` as opposed to `sorted_order` you could imagine using `segmented_gather_map` (from the previous multi column example) against the columns:
| a | b | c |
| - | - | - |
| [21. 22. 22. 23] | [13, 11, 14, 12] | ["a", "d", "b", "c"] |
| [21, 22, 22, 23] | [13, 11, 14, 12] | ["b", "d", "a", "c"] |

**Describe alternatives you've considered**
Running a separate sort per list against the flattened data, but would be prohibitively expensive.

**Additional context**
There's similar needs for groupby aggregations, where there's potential overlap in functionality here.

**Comment by kkraus14** [comment]
Likely depends on #6542

**Comment by jrhemstad** [comment]
`argsort` means the same thing as `sorted_order` here?

**Comment by kkraus14** [comment]
> `argsort` means the same thing as `sorted_order` here?

Yes, apologies!

**Comment by ogreen** [comment]
The attached zip file has an efficient segmented sort that is based on NVIDIA's CUB library. Most of the sorting is done using CUB's sorting functionality. The key thing that this segmented sorting algorithm offers is simple and efficient load-balancing.
[lrb_sort.cuh.zip](https://github.com/rapidsai/cudf/files/5425537/lrb_sort.cuh.zip)

Details of the algorithm (and performance) can be found in the [following paper](https://www.researchgate.net/publication/335723059_Improving_Scheduling_for_Irregular_Applications_with_Logarithmic_Radix_Binning).

**Comment by harrism** [comment]
>  One handling 1 depth of lists should be fine for now 

@kkraus14 I'm having trouble parsing the above. Can you clarify what the "one" and "1" mean? :)

**Comment by kkraus14** [comment]
> @kkraus14 I'm having trouble parsing the above. Can you clarify what the "one" and "1" mean? :)

Fixed above, it should have been "Only handling 1 depth of lists should be fine for now". What I meant is that only handling `list<int32>` or `list<int16>` as the segmented gathermap would be fine, but this may have just been a copy paste error from the segmented gather issue.

**Comment by kkraus14** [comment]
This is active for the Python implementation still.

**Comment by ttnghia** [comment]
Maybe the same FEA issue for Python binding: https://github.com/rapidsai/cudf/issues/7467

**Comment by kkraus14** [comment]
Going to close this in favor of #7467, thanks @ttnghia!
