### ISSUE TITLE
[FEA] Segmented gather

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#6542]
**Is your feature request related to a problem? Please describe.**
Given we now support list columns, we could use a function for a segmented gather to gather the elements within a list element within a column. One handling 1 depth of lists should be fine for now and if we need arbitrary nesting we could revisit in the future.

**Describe the solution you'd like**
For example say we had a table that looked like:
| gather_map | value_column |
| - | - |
| [0, 1, 3, 2] | ["a", "b", "c", "d"]
| [1, 0, 3, 2] | ["a", "b", "c", "d"]

I'd like to be able to run a segmented gather against column `value_column` which would return a new `list<string>` column that is the result of gathering each list element based on the list element in `gather_map`:
| result_value_column |
| - |
| ["a", "b", "d", "c"] |
| ["b", "a", "d", "c"] |

**Describe alternatives you've considered**
Flattening the gather map column and repeating the offsets in some way to properly increment the flattened gather map column to generate a global gather map and applying that against the flattened `value_column`.

**Additional context**

**Comment by karthikeyann** [comment]
What should be the behavior for empty list in a gather_map row?
The options are
1. Skip that row in output column
2. empty list in that row in output column.
3. Undefined behavior

**Comment by jrhemstad** [comment]
> What should be the behavior for empty list in a gather_map row?
> The options are
> 
> 1. Skip that row in output column
> 2. empty list in that row in output column.
> 3. Undefined behavior

Almost certainly 3. Gathering from an empty list element doesn't seem any different from an out-of-bounds access like trying to gather from past the end of the list.

**Comment by karthikeyann** [comment]
Sorry if that was ambiguous.
I meant, a gather_map's row is empty list. 
eg. `gather_map = [{1,0}, {}, {1}], value_column=[{1,2,3},{3,4},{5,6}]`

**Comment by jrhemstad** [comment]
Ah, in that case I think an empty list element is probably the most sensible thing? You can think of this as doing a set of `cudf::gather` operations on each list. And so in `cudf::gather` an empty gather map yields an empty column. I think it makes sense for the same to apply here.
