### ISSUE TITLE
Found conflicts using “conda install”

### ISSUE THREAD

**Issue by scirocc** [rapidsai/cudf#6551]
**Describe the bug**
Found conflicts using “conda install”
My command is "conda install -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.15 python=3.8 cudatoolkit=10.2"
and return "found conflicts,looking for incompatible packages"
My env is ubuntu18.04 ,python3.8,cuda10.2
Is there any way to fix this?

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by scirocc** [comment]
or please tell me the exact version of conda/miniconda,python,cuda toolkit,cudf that won't  have conflicts

**Comment by kkraus14** [comment]
@scirocc can you give more information as to what is in your conda environment? Alternatively I would suggest creating a new environment instead of installing into your existing one:
```
conda create -n rapids -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.16 python=3.8 cudatoolkit=10.2
```

**Comment by kkraus14** [comment]
Closing as there's been no response.
