### ISSUE TITLE
[FEA] Accept a vector of scalar* into scatter instead of a vector of unique pointers to scalars

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#6554]
**Is your feature request related to a problem? Please describe.**

I'd like to be able to pass scalars themselves instead of unique pointers to scalars to this version of `scatter`:
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/include/cudf/copying.hpp#L148

Currently, the requirement to pass unique pointers makes it so that we have to `move` those pointers away from the cython scalar objects that own them and creates some potentially unsafe situations. As far as I can tell, all of the rest of the libcudf APIs accept the scalars directly - in which case we can pass the scalar using `get()` without modifying the ownership, this seems to be the only case like this. 

**Describe the solution you'd like**
Allow this API to accept the scalar* 's themselves instead of unique pointers to those scalars.

**Describe alternatives you've considered**
The current approach `move`s the pointers and I think we just don't re-use those objects so there's never any breakages. 

**Additional context**

**Comment by cwharris** [comment]
We're using `std::vector<std::reference_wrapper<scalar>>` in a couple of other places.

I'm wondering if it's appropriate and/or feasible to have a `scalar_view` type. We have a handful of types deriving from `scalar` and it's not clear if all of those would need their own views...

**Comment by jrhemstad** [comment]
It's a mistake that `scatter` takes a `vector<unique_ptr<scalar>>`. As @cwharris said, it should be `std::vector<std::reference_wrapper<scalar>>`.

**Comment by cwharris** [comment]
@jrhemstad the fact that we don't have views of scalars is making some things difficult non-obvious on the python side. One solution is to use `shared_ptr` instead of `unique_ptr`.

**Comment by harrism** [comment]
There is a separate issue open for that: #6558
