### ISSUE TITLE
[BUG] Incorrect behavior in CSV reader when both header and skiprows parameters are used

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#656]
**Description**
When parsing a CSV file with nonzero header and skiprows parameters the resulting dataframe is not consistent with pandas implementation. There are two issues observed:
* Header row is not skipped correctly so it appears again in a data row.
* With pandas, total number of skipped rows is skiprows+header, so the header row is always the first one read. This is not the case in cuDF, where only skiprows rows are skipped and the header can be any of the remaining rows.

**Repro steps:**
dtypes = ['float32', 'int32']
lines = [','.join(dtypes),
        "1.1, 1",
        "12.12, 2",
        "123.123, 3",
        "1234.1234, 4"]
buffer = '\n'.join(lines) + '\n'
pd_df = pd.read_csv(StringIO(buffer), skiprows=1, header=1)
df  = read_csv(StringIO(buffer), skiprows=1, header=1)

pd_df content:
   12.12	     2
0 123.1230    3
1 1234.1234  4

df content:
   1.1	     1
0 1.1             1
1 123.123      3
2 1234.1234  4

**Comment by kkraus14** [comment]
Fixed by #689
