### ISSUE TITLE
[BUG] Missing stream arguments to `device_scalar` methods

### ISSUE THREAD

**Issue by magnatelee** [rapidsai/cudf#6580]
**Describe the bug**
I found several `device_scalar` method calls that don't pass the stream argument available in the scope. They will not be synchronized correctly if the passed explicit stream is non-blocking. Here is the list of mistakes I found:

https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/bitmask/null_mask.cu#L450
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/copying/concatenate.cu#L233
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L218
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L275
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cu#L292
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L120
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L140
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/hash_join.cuh#L142
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/nested_loop_join.cuh#L89
https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/join/nested_loop_join.cuh#L98

**Comment by harrism** [comment]
Thanks so much for this @magnatelee  -- very helpful.
