### ISSUE TITLE
[DOC] Remove outdated multi-gpu dask-cudf overview from docs

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#6583]
We should remove https://docs.rapids.ai/api/cudf/stable/dask-cudf.html from the docs, as it is outdated and potentially confusing. Dask-cuDF is covered in other documentation.

**Comment by harrism** [comment]
@rjzamora Is this your bailiwick?

**Comment by rjzamora** [comment]
> @rjzamora Is this your bailiwick?

It probably should be.  I haven't dealt with documentation much in the past, but I'd be happy to give it more attention.

**Comment by rjzamora** [comment]
> Dask-cuDF is covered in other documentation.

@beckernick - I agree that the "Multi-GPU with Dask-cuDF" page should be removed.  However, it doesn't seem that Dask-cuDF is very well documented in other places.  Perhaps it makes sense for us to add a README to `cudf/python/dask_cudf`?  [The 10-min introduction](https://docs.rapids.ai/api/cudf/stable/10min.html) does a nice job comparing cudf with Dask-cuDF, but I think it would be ideal to have a dedicated Dask-cuDF landing page with useful information.  What do you think?

**Comment by beckernick** [comment]
I think that's consistent with the general trend we're moving in @rjzamora . cuML did something [similar](https://github.com/rapidsai/cuml/tree/branch-0.17/python/cuml/fil) for the Forest Inference Library. We should take care to note that Github SEO is not that good for files down in the tree, so we may want to replicate the information in actual hosted documentation

**Comment by harrism** [comment]
@beckernick @rjzamora what should we do here?

**Comment by beckernick** [comment]
We still need to remove this documentation and replace it with a simple summary + links out to other relevant documentation. 

@rjzamora I see you closed https://github.com/rapidsai/cudf/pull/6665 due to it going stale. Would you recommend we continue from where that PR left off and expand the README with additional links and references?

**Comment by rjzamora** [comment]
I'm sorry for letting this issue and #6665 go stale - Totally my fault for not prioritizing documentation enough.

> Would you recommend we continue from where that PR left off and expand the README with additional links and references?

Yes.  I agre that the easiest approach is to open a fresh PR with the same changes, but to improve/expand the README.
