### ISSUE TITLE
[BUG] CSV reader: DataFrame contains incorrect data when data type inference is used

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#659]
**Description**
When parsing a CSV file with data type inference, the data in the resulting dataframe is partially corrupted. The issue reproes even when the data types are the same in both cases, as the repro steps below show.

**Repro steps**
dtypes = ['float64', 'int32']
lines = [','.join(dtypes),
"1.1, 1",
"12.12, 2",
"123.123, 3",
"1234.1234, 4"]
buffer = '\n'.join(lines) + '\n'
df_correct = read_csv(StringIO(buffer), dtype=dtypes, compression=None)
df2_bug = read_csv(StringIO(buffer), compression=None)

df_correct content:
float64 int32
0 1.1 1
1 12.12 2
2 123.123 3
3 1234.1234 4

df2_bug content:
float64 int32
0 1.1 -1749152730
1 12.12 -279189465
2 123.123 -1013785646
3 1234.1234 -1092438448

**Comment by felipeblazing** [comment]
Is anyone looking into this? If not I can take a gander.

**Comment by felipeblazing** [comment]
I started making a test for this situation and ran into a problem parsing floats at all. I made a few tests and here is an example of a simple test that fails.

`
TEST(gdf_csv_float_test, FloatTest)
{
	const char* fname			= "/tmp/CsvFloatTest.csv";
	const char* names[]			= { "A" };
	const char* types[]			= { "float64" };

	std::ofstream outfile(fname, std::ofstream::out);
	outfile << "1\n12\n123.123\n1234.1234\n";
	outfile.close();
	ASSERT_TRUE( checkFile(fname) );

	{
		csv_read_arg args{};
		args.input_data_form	= gdf_csv_input_form::FILE_PATH;
		args.filepath_or_buffer	= fname;
		args.num_cols			= std::extent<decltype(names)>::value;
		args.names				= names;
		args.dtype				= types;
		args.delimiter			= ',';
		args.lineterminator 	= '\n';
		EXPECT_EQ( read_csv(&args), GDF_SUCCESS );

		EXPECT_EQ( args.num_cols_out, args.num_cols );
		ASSERT_EQ( args.data[0]->dtype, GDF_FLOAT64 );


		auto ACol = gdf_host_column<double>(args.data[0]);
		EXPECT_THAT( ACol.hostdata(),
				::testing::ElementsAre(1,12,123.123,1234.1234) );

	}
}
`

we see the following output
`[ RUN      ] gdf_csv_float_test.FloatTest
/home/felipe/git-repos/forks/cudf/cpp/tests/io/csv/csv_test.cu:516: Failure
Value of: ACol.hostdata()
Expected: has 4 elements where
element #0 is equal to 1,
element #1 is equal to 12,
element #2 is equal to 123.123,
element #3 is equal to 1234.12
  Actual: { 1, 12, 1.22812e+06, 1.23381e+08 }, whose element #2 doesn't match`

So whenever the floats have a decimal point data is being corrupted.

**Comment by felipeblazing** [comment]
Is this actually a bug?
So the input is "float64,int32\n1.1,1\n12.12,2\n123.123,3\n1234.1234,4\n" and we aren't telling it to skip rows or antyhing of that nature. How is it supposed to know that it needs to skip the first row? Removing those two lines seems to make this work fine though it infers an int64 instead of an int32.

**Comment by thomcom** [comment]
There's another issue where it is reported that you need to specify arguments to this function carefully. I'm going to reference that here.

**Comment by thomcom** [comment]
See https://github.com/rapidsai/cudf/issues/602 and @vuule's comment. Does that resolve this?

**Comment by vuule** [comment]
@thomcom I have a fix for #656

**Comment by thomcom** [comment]
Please close this issue which is replaced with #700.
