### ISSUE TITLE
[BUG] Revert change to `__sizeof__` in the case of sliced Columns

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#6590]
In #6549 we changed the behavior of `__sizeof__` to report the actual memory being used by the column in memory. Unfortunately, Dask doesn't deduplicate objects referencing the same memory so this has caused issues with causing premature spilling due to reporting much higher memory usage than we actually use.

For now, we should revert the change to report the size of the sliced column as opposed to the size of the underlying memory allocation(s). but we should still fix the issues of referring to `.mask` which caused a copy construction of a new bitmask if the Column was sliced.

cc @quasiben @beckernick @jakirkham @pentschev

**Comment by beckernick** [comment]
cc @ayushdg
