### ISSUE TITLE
[BUG] concatenate fixed-point coulumns with different scales  

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#6611]
Currently, fixed-point columns with different scales can be concatenated. Because [operator==](https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/include/cudf/types.hpp#L298) of data_type only compares type_id, which leads to the unexpected success of [type check](https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/src/copying/concatenate.cu#L336) before column concatenation.

When cuDF performs a concatenation with multiply fixed-point column, it takes the type of the first column as output type. This behavior may change the actual value of fixed-point columns unexpectedly.

Either we change the operator== of data_type class, or change the pre-check of cudf::concatenate to adapt fixed-point data ?

**Comment by codereport** [comment]
This was never intended to be supported. In order to concat, the `fixed_point` scales need to be the same. I will set up a PR and block this use case.
