### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by stromal** [rapidsai/cudf#6613]
**Describe the bug**
When I am trying to import dask_cudf I get the following ERROR:
```

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-afb970ad91bb> in <module>()
      8 from dask_cuda import LocalCUDACluster
      9 import dask_xgboost
---> 10 import dask_cudf
     11 import dask
     12 from xgboost.dask import DaskDMatrix

ModuleNotFoundError: No module named 'dask_cudf'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

```
I have dask and RAPID installed with pip
- when I search for: pip install dask_cudf
- original site is not exists anymore: https://pypi.org/project/dask-cudf/
- google stored site history: https://webcache.googleusercontent.com/search?q=cache:8in7y2jQFQIJ:https://pypi.org/project/dask-cudf/+&cd=1&hl=en&ct=clnk&gl=uk

I am trying to install it with the following code in the Google Colab Window
`%pip install dask-cudf`

I get the following ERROR
```
ERROR: Could not find a version that satisfies the requirement dask-cudf (from versions: none)
ERROR: No matching distribution found for dask-cudf
```

On the github page of CUDF is archived how can I install it to google colab now?
https://github.com/rapidsai/dask-cudf

**Comment by rjzamora** [comment]
There is not pypi package for dask-cudf.  You may want to follow instructions [here](https://rapids.ai/start.html), or use the [conda package](https://anaconda.org/rapidsai/dask-cudf).

**Comment by stromal** [comment]
@rjzamora  https://rapids.ai/start.html is jsut the starting page this doenet  help and I can not use conda for Google Colab. I jsut want to use it the last supported version as it wa on pip.

**Comment by rjzamora** [comment]
Sorry for the confusion - I do understand. The page I shared simply lists the available mechanisms for installing RAPIDS libraries (conda, docker, or source).  Note that [pip is NOT supported](https://medium.com/rapids-ai/rapids-0-7-release-drops-pip-packages-47fc966e9472) (the cached page you are finding is far out of date).

**Comment by kkraus14** [comment]
Given this is answered I'm going to close this issue. If you run into anything else feel free to open a new issue.
