### ISSUE TITLE
[QST] best way to get data onto many GPUs using dask_cudf

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#6624]
dask_cudf can read csv, parquet, orc, json and presumably in each case immediately distributes data, never centralizing onto 1 GPU.  cudf supports in-memory operations like from_pandas, from_arrow, etc.

However, it's not clear if going from cudf -> dask_cudf via dask_cudf.from_cudf() is a problem since it would seem the frame has to exist on a single (say 0 by default) GPU with cudf.  So cudf -> dask_cudf is not a good way to go at all.

Seems dask_cudf could support more directly in-memory CPU->GPU operations like cudf, especially from_arrow.

Of course, if on disk at first the dask_cudf options are fine, but if ever need to do anything on CPU it's currently awkward as have to go through disk.  Maybe that's ok for NVME, as I understand cudf can bypass memory, but is same true for dask_cudf?

Although, I'm not sure this is the case regarding NVME, is https://developer.nvidia.com/gpudirect part of cudf or separate?  Is there a specific reason this is not part of cudf?  Probably technical reasons?

**Comment by kkraus14** [comment]
> Although, I'm not sure this is the case regarding NVME, is https://developer.nvidia.com/gpudirect part of cudf or separate? Is there a specific reason this is not part of cudf? Probably technical reasons?

GPUDirect is a broad range of technology related to bypassing CPU memory to interface to GPU memory. This includes network RDMA (https://docs.nvidia.com/cuda/gpudirect-rdma/index.html) over fabrics like infiniband / RoCE, and GPUDirect Storage (https://developer.nvidia.com/gpudirect-storage).

We take advantage of network RDMA when possible by using OpenUCX (https://www.openucx.org/) via UCX-py for accelerated communication in Dask. GPUDirect Storage is not yet integrated as it is still early access and was only recently made publicly available. We'll hopefully have a pull request up for the GPUDirect Storage integration in the near future.

> Of course, if on disk at first the dask_cudf options are fine, but if ever need to do anything on CPU it's currently awkward as have to go through disk. Maybe that's ok for NVME, as I understand cudf can bypass memory, but is same true for dask_cudf?

dask_cudf just sets up a plan as to how to call into the underlying cudf functions. In the case of POSIX filesystems it basically hands off completely to cudf to read so we can take advantage of any and all cudf optimizations available to us.

> However, it's not clear if going from cudf -> dask_cudf via dask_cudf.from_cudf() is a problem since it would seem the frame has to exist on a single (say 0 by default) GPU with cudf. So cudf -> dask_cudf is not a good way to go at all.

It depends. The codepath for `from_cudf()` will actually slice the memory of the cudf DataFrame up zero-copy and transfer those slices onto the workers based on the given partitioning and whatnot. If UCX is enabled it will take advantage of it and leverage things like NVLink / Network RDMA to do the actual memory transfers.

> Seems dask_cudf could support more directly in-memory CPU->GPU operations like cudf, especially from_arrow.

Agreed that we should add a `from_arrow` to dask-cudf that takes a similar path as above and slices up the pyarrow object zero copy and ships those slices to the workers, which can then use the `cudf.from_arrow` method.

You could possibly implement this yourself today as a workaround by creating a list of arrow array/table slices, and then using `dask.bag.from_sequence` (https://docs.dask.org/en/latest/bag-creation.html#db-from-sequence) against those slices, followed by `to_delayed` (https://docs.dask.org/en/latest/bag-creation.html#dask.bag.core.Bag.to_delayed) to turn it into a normal dask delayed collection. Once you have that collection you could call `cudf.from_arrow` against each delayed partition, and then use `dask.dataframe.from_delayed` (https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.from_delayed) to turn it into a Dask DataFrame backed by cudf DataFrames (this is how dask_cudf works). cc @rjzamora who's the expert in this area for if he has any thoughts or if I have anything wrong here

Additionally with this approach, we have the opportunity for future optimizations where we could use UCX to go directly from host memory in the client process to GPU memory in the worker processes. UCX would automatically handle using shared memory in the case of it being on the same machine or network RDMA in the case of it being on different machines.

**Comment by rjzamora** [comment]
>Agreed that we should add a from_arrow to dask-cudf that takes a similar path as above and slices up the pyarrow object zero copy and ships those slices to the workers, which can then use the cudf.from_arrow method.

It seems pretty reasonable to add `from_arrow` to dask_cudf.  It may even make sense to add the method to `dask.dataframe` (and allow dask_cudf to register a specialized `from_arrow_dispatch` for the cudf-specific conversion mechanism).  Although there is always resistence to anything outside the pandas api in `dask.dataframe`,  IO/conversion is a bit more flexible.

>You could possibly implement this yourself today as a workaround by creating a list of arrow array/table slices, and then using dask.bag.from_sequence (https://docs.dask.org/en/latest/bag-creation.html#db-from-sequence) against those slices, followed by to_delayed (https://docs.dask.org/en/latest/bag-creation.html#dask.bag.core.Bag.to_delayed) to turn it into a normal dask delayed collection. Once you have that collection you could call cudf.from_arrow against each delayed partition, and then use dask.dataframe.from_delayed (https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.from_delayed) to turn it into a Dask DataFrame backed by cudf DataFrames (this is how dask_cudf works). cc @rjzamora who's the expert in this area for if he has any thoughts or if I have anything wrong here

This approach seems reasonable, but we would most-likely skip the `dask.bag`->`Delayed` steps since it's more conventional to construct the collection [directly from a dictionary](https://github.com/dask/dask/blob/94bdd4e3e9a34cc10308b4f3a6f40a35d507f304/dask/dataframe/io/io.py#L224) in simple cases like this.  The approach would likely be: (1) create a list of arrow array/table slices, (2) construct a simple partition-wise graph to convert each slice to a pandas/cudf partition, and (3) use the graph to initialize a new DataFrame collection.

**Comment by beckernick** [comment]
> It seems pretty reasonable to add `from_arrow` to dask_cudf. It may even make sense to add the method to `dask.dataframe` (and allow dask_cudf to register a specialized `from_arrow_dispatch` for the cudf-specific conversion mechanism). There is always resistence to anything outside the pandas api in `dask.dataframe`, but IO/conversion is a bit more flexible.

This would likely be quite valuable for interfacing with a broad range of data warehouses that can ship batches of Arrow data around. I can think of Snowflake and BigQuery off the top of my head.

**Comment by kkraus14** [comment]
Closing as this is answered.
