### ISSUE TITLE
[FEA] `table_view` of `fixed_point`s should always have the same scale

### ISSUE THREAD

**Issue by codereport** [rapidsai/cudf#6626]
There are two things that should be fixed:
1. `table_view` of `fixed_point`s should always have the same scale
2. `cudf::bitmask_and` should take `std::vector` of `cudf::column`s

This was partially solved in this PR https://github.com/rapidsai/cudf/pull/6616#discussion_r514888544 but breaking it out into a separate issue.

**Reasoning:**
1. A table is the equivalent of a 2-rank array (usually referred to as a matrix or a table). In array languages, it is only possible to have a single type in these. The same way it doesn't make sense to have a matrix where one column is integers and another is floating point, it doesn't make sense to have a column with `fixed_point`s of varying scales.
2. Currently, the `cudf::bitmask_and` takes a `table_view` as input and generates the `logical_and` reduced bitmask. However, `table_view` here is an overspecification - we don't actually NEED a `table_view`, we just need `n` `column_view`s - and a `table_view` is a convenient way to get that. However, for calculating an "and" bitmask, the types of the columns need not be the same - you only care about the bitmasks of each of the columns - not the types. Changing it from a `table_view` to a `std::vector<cudf::column>` will enable this.

Note: after re-reading my first point, it really makes me think that the `cudf::data_type` `operator==` should be modified to take `scale` into account. I will give this some more thought.

**Comment by harrism** [comment]
@codereport can you provide a reason for each point.

**Comment by codereport** [comment]
> @codereport can you provide a reason for each point.

@harrism Description updated

**Comment by karthikeyann** [comment]
For point 1, a table can contain mixed type columns. (table documentation says `A set of cudf::column's of the same size.` in a given order. Hence this conclusion).
`concatenate(std::vector<table_view>`) requires each corresponding column in each table to be same type and scale. (AFAIK, every `i`th column of each table should have same scale.).

Why independent `fixed_point` columns in a single table_view has to be in same scale? 
is this constraint coming from any fixed_point algorithm on table_view?

**Comment by jrhemstad** [comment]
> The same way it doesn't make sense to have a matrix where one column is integers and another is floating point

But `table` isn't a matrix. A table (or dataframe) is columns of potentially different types.

**Comment by codereport** [comment]
hmmm, re: @karthikeyann & @jrhemstad 

My understanding was indeed mistaken. If 1 is wrong - then having the API take a `table_view` in 2  is also ok. Closing Issue
