### ISSUE TITLE
[FEA] Introduce `DecimalDtype` to cuDF

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#6654]
As a first step towards supporting decimal fixed-point arithmetic, we need to introduce a new `DecimalDtype` dtype.

Requirements:

* Similar to other cuDF [dtypes](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/core/dtypes.py), should inherit from [ExtensionDtype](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.api.extensions.ExtensionDtype.html). This requires us to define the abstract methods `name` and `type`. We could probably use `'decimal'` and [`decimal.Decimal`](https://docs.python.org/3/library/decimal.html#decimal-objects) respectively.

* Similar to PyArrow's [`Decimal128Type`](https://arrow.apache.org/docs/python/generated/pyarrow.decimal128.html), should be constructed from a `precision` and a `scale` attribute:

  ```python
  >>> import cudf
  >>> dt = cudf.DecimalDtype(precision=4, scale=2)
  ```

* Should expose `.from_arrow()` and `.to_arrow()` methods that convert from and to PyArrow `Decimal128Type`.

**Comment by harrism** [comment]
Should it have the explicit storage size in the name like PyArrow?  libcudf has 32-bit and 64-bit now, with plans to add 128-bit in the future.

**Comment by harrism** [comment]
@kkraus14 should this aim for 0.18?

**Comment by kkraus14** [comment]
> Should it have the explicit storage size in the name like PyArrow? libcudf has 32-bit and 64-bit now, with plans to add 128-bit in the future.

In the call we had from the Python side I think we decided to only have a single `DecimalDtype` for now hooked up to `DECIMAL64`.

Then as a follow up we'll explore automatically handling type promotion / demotion based on the calculated `precision` value from operations.

If that exploration doesn't pan out we'll split the types into `Decimal64Dtype` and `Decimal32Dtype`.

> @kkraus14 should this aim for 0.18?

No I think we can safely do this in 0.17.
