### ISSUE TITLE
[FEA] Introduce `DecimalColumn` to cuDF

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#6657]
Following #6654, we should introduce a `DecimalColumn` that will enable constructing Series and DataFrame objects containing columns with decimal values. The steps below describe how to set up the minimum amount of infrastructure for a DecimalColumn that can communicate with libcudf.

1. Create a `DecimalColumn` class that inherits from `ColumnBase`, similar to our other column classes:

   ```python 
   class DecimalColumn(ColumnBase):
       pass
   ```

   At a minimum, we need to implement the `base_size`, `from_arrow` and `to_arrow` methods.

2. Extend [`as_column`](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/core/column/column.py#L1536) to handle constructing DecimalColumns from Python host objects such as `List[Decimal]` objects. This is done in two steps: (1) construct a `pa.array` from the Python object (2) use `DecimalColumn.from_arrow()` to construct a `DecimalColumn` from the `pa.array`.

3. Extend the [`build_column`](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/core/column/column.py#L1400) API to handle building DecimalColumns from `Buffer` objects. 

4. Cython bindings:

   * Add the `DECIMAL64` enumerator to Cython: https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/include/cudf/types.hpp#L229. For now, this is the only libcudf type we will support.

   * Add binding in [types.pxd](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/_lib/cpp/types.pxd) to the new `data_type` [constructor](https://github.com/rapidsai/cudf/blob/branch-0.17/cpp/include/cudf/types.hpp#L263).

5. Enable generating a `cudf::column_view` from a `DecimalColumn` - this will probably require small changes to the [`_view`](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/_lib/column.pyx#L376) function.

6. Enable constructing `DecimalColumn` from a `std::unique_ptr<cudf::column>` - this will probably require small changes to the [`from_unique_ptr`](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/_lib/column.pyx#L426) function.

**Comment by kkraus14** [comment]
Pushing to 0.18
