### ISSUE TITLE
[FEA] cudf.DataFrame.to_arrow should make copying the df's index optional

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#666]
Currently, when I copy a DataFrame to host using .to_arrow(), it copies the df's index to the 'None' column.

Repro steps:
```
import cudf
df = cudf.DataFrame({k: [1,1] for k in 'ab'})
df.to_arrow().columns
```

Result:
```
[<Column name='None' type=DataType(int64)>
 [
   [
     0,
     1
   ]
 ], <Column name='a' type=DataType(int64)>
 [
   [
     1,
     1
   ]
 ], <Column name='b' type=DataType(int64)>
 [
   [
     1,
     1
   ]
 ]]
```
**Describe the solution you'd like**
1. Instead of 'None', that column should be named `__index__`
2. Copying the index should be optional, possibly specified by an `preserve_index` argument, True by default (see [pyarrow.from_pandas](https://arrow.apache.org/docs/python/generated/pyarrow.Table.html#pyarrow.Table.from_pandas))
3. cudf.DataFrame.from_arrow(df.to_arrow()) == df should return True

**Comment by kkraus14** [comment]
Fixed by #749
