### ISSUE TITLE
[BUG] Use std::chrono for timestamp processing in cuIO

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#6674]
Some code that processes timestamp fields in cuIO could be replaced with `cuda::std::chrono` library use.
This refers to conversion between time units and similar operations.

I'm not sure how to systematically find the code that can be replaced, but looking for places where TIMESTAMP columns are processed should find the most of it.

- [x] ORC
- [x] Parquet
- [x] CSV, JSON
- [x] Avro (if any)
- [ ] ORC timezone (blocked on cuda::timezone)

**Comment by jrhemstad** [comment]
Note that once https://github.com/rapidsai/cudf/pull/6275 is merged, we drop `simt::std` and use `cuda::std`.

**Comment by vuule** [comment]
still relevant

**Comment by vuule** [comment]
Places where I see `chrono` can potentially be used:
https://github.com/rapidsai/cudf/blob/d9421002678c00c0b55c38fa80c07239b70fb1c3/cpp/src/io/csv/datetime.cuh#L123
https://github.com/rapidsai/cudf/blob/d9421002678c00c0b55c38fa80c07239b70fb1c3/cpp/src/io/csv/datetime.cuh#L422
https://github.com/rapidsai/cudf/blob/f08d6f1dc5c9c3e85b259b7091e3a86368bb87aa/cpp/src/io/orc/reader_impl.cu#L97
https://github.com/rapidsai/cudf/blob/473063ffeed14150690b18140271a491b9d8a494/cpp/src/io/orc/stripe_data.cu#L1748
https://github.com/rapidsai/cudf/blob/473063ffeed14150690b18140271a491b9d8a494/cpp/src/io/orc/stripe_data.cu#L1782
https://github.com/rapidsai/cudf/blob/b9214c40fe0a5d270d67453b13a29079a38bf2ba/cpp/src/io/orc/stripe_enc.cu#L806
https://github.com/rapidsai/cudf/blob/branch-21.10/cpp/src/io/orc/timezone.cpp
https://github.com/rapidsai/cudf/blob/branch-21.10/cpp/src/io/orc/timezone.cuh
https://github.com/rapidsai/cudf/blob/8aaf8e656de3a3269b78d5e0be012f2f9da48fa8/cpp/src/io/parquet/page_data.cu#L662
