### ISSUE TITLE
[FEA] Tag libcudf JIT kernel cache by commit along with version

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#6689]
**Is your feature request related to a problem? Please describe.**
It will be beneficial to tag the kernel cache by the commit and the version as we can run into issues due to a stale cache from the previous commit. 
  
We propose shifting the default location frm: 
```bash
/.cudf/0.17.0/
```
to something like: 
```bash
/.cudf/0.17.0.[commit-hash]/
```

**Additional context**

Never mind unrelated issues. ~We believe a stale cache issue led to the issue https://github.com/rapidsai/tpcx-bb/issues/128 go un-noticed for a bit (we are triaging it right now); if we can have our cache tagged by commit along with version number, it can prevent such problems in the future.~   

CC: @beckernick

**Comment by harrism** [comment]
This issue description lacks some context. I guess you are referring to the libcudf JIT compilation cache?

**Comment by VibhuJawa** [comment]
> This issue description lacks some context. I guess you are referring to the libcudf JIT compilation cache?

Yup, I meant the `libcudf JIT compilation cache` . 

Also, the issue turned out to be unrelated to this so I am not sure if this relevant anymore.

**Comment by harrism** [comment]
@devavret didn't you address this?

**Comment by devavret** [comment]
> @devavret didn't you address this?

No, I just saw this. I added a compute arch level to the cache, not the commit. I'll have to see how we can get the commit sha during compilation. This would also mean that libcudf would not be able to build when not a git repository. Like if someone downloaded it as a zip from GitHub. Or special case that and be aware that the cache conflict would not be fixed in such cases.

**Comment by harrism** [comment]
How would you get the git commit from C++ in a portable way?

**Comment by jlowe** [comment]
> How would you get the git commit from C++ in a portable way?

Typically something during the build generates a header file that contains the relevant build version information, e.g.: a shell script using `git` to obtain the commit information and emitting it into a header file as a `#define` or `constexpr` at build time before C++ sources are compiled.

> Like if someone downloaded it as a zip from GitHub. Or special case that and be aware that the cache conflict would not be fixed in such cases.

In these cases we can fallback to a timestamp-like string generated at the time of build instead of a git commit hash to try to keep the build ID unique and avoid JIT cache collisions.

**Comment by devavret** [comment]
@cwharris is this still needed? I suppose the cache now updates if the code changes.

**Comment by cwharris** [comment]
Looks like the pre-compiled program isn't considered when computing the hash. We can either use a custom hasher to account for it in the file name (file name contains hash), or we can add the suggested cudf version directory.

I'll get a PR up to add cudf version to the cache path.

**Comment by cwharris** [comment]
Actually, cudf version is included as part of the jit kernel cache path.
```
.jitify-cache/21.06.00/75/binaryop_jit_kernel.cu.<hash-goes-here>.sm75.v10.jitify
```

**Comment by devavret** [comment]
@cwharris It was included from the very beginning. I think this issue was asking this for nightlies. So that changes within a release doesn't make users do a manual cache cleanse.

**Comment by cwharris** [comment]
Adding the commit id to the hash path creates a couple of problems and raises a few question. First, we probably don't want to invalidate the cache on every commit in CI. This means we have to deviate how CI and local builds generate the cache path, which is non-ideal. I personally feel this is a non-starter for the commit id approach.

Instead, lets incorporate the parts of the build that do effect the cache's validity in to the hash that's already on the cache file. Off the top of my head, this means hashing the contents/source of the recompiled program, along with it's compilation arguments, and combining this with the hash of the individual kernels. This will allow CI and local builds to hit the cache so long as the source hasn't changed significantly.

jitify2 has some hooks we can use (a custom hasher type) that will allow us to inject this information, though I haven't explored how to do it yet.

**Comment by cwharris** [comment]
The key to good caching is a good key. :)

Being too vague or too specific means we end up doing a lot of extra work. Commit ID is too vague. We could add thousands of commits without ever effecting the validity of the cache. On the other hand, we can update code locally without making a commit and still need to clear the cache.

**Comment by devavret** [comment]
>Off the top of my head, this means hashing the contents/source of the precompiled program, along with it's compilation arguments, and combining this with the hash of the individual kernels.

This is the right way to go. I've wanted to do that since the beginning but wasn't possible since program creation itself was a jitify operation. I'd suggest waiting until after the compiled binops PR #8192 is merged.

**Comment by GregoryKimball** [comment]
@vyasr We've been moving away from JIT in libcudf - is this issue still relevant? Does this tagging proposal have any application to Python-Numba UDF jitted kernels?
