### ISSUE TITLE
[FEA] Improve libcudf compile time for simple reductions (cudf::reduce)

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#6717]
Currently the source files simple reductions (`min`, `max`, `sum`, `product`, and `sum-of-squares`) each take 5-7 minutes to build and in the top 12 slowest source files to compile.

| (ms) | object file built |
| ----- | ----- |
| 860441 | CMakeFiles/cudf_base.dir/src/sort/sort.cu.o |
| 857510 | CMakeFiles/cudf_base.dir/src/sort/stable_sort.cu.o |
| 496797 | CMakeFiles/cudf_rolling.dir/src/rolling/rolling.cu.o |
| 491553 | CMakeFiles/cudf_reductions.dir/src/reductions/scan.cu.o |
| 440116 | CMakeFiles/cudf_reductions.dir/src/reductions/**max.cu**.o |
| 423566 | CMakeFiles/cudf_reductions.dir/src/reductions/**min.cu**.o |
| 417868 | CMakeFiles/cudf_base.dir/src/stream_compaction/drop_duplicates.cu.o |
| 401584 | CMakeFiles/cudf_base.dir/src/strings/sorting/sorting.cu.o |
| 398396 | CMakeFiles/cudf_hash.dir/src/hash/hashing.cu.o |
| 330566 | CMakeFiles/cudf_reductions.dir/src/reductions/**product.cu**.o |
| 322124 | CMakeFiles/cudf_reductions.dir/src/reductions/**sum.cu**.o |
| 319379 | CMakeFiles/cudf_reductions.dir/src/reductions/**sum_of_squares.cu**.o |
| 284708 | CMakeFiles/cudf_join.dir/src/join/semi_join.cu.o |
| 279809 | CMakeFiles/cudf_base.dir/src/search/search.cu.o |
| 243226 | CMakeFiles/cudf_base.dir/src/groupby/hash/groupby.cu.o |
| `^` | Top 15 slowest compile objects |

![baseline](https://user-images.githubusercontent.com/45795991/98604025-06964800-22b1-11eb-8ae7-48f49459d55b.png)

The [`cudf::reduce`](https://docs.rapids.ai/api/libcudf/stable/group__aggregation__reduction.html#ga382c3ca1ce3191138795a5c0c4619450) function looks like the following:
```
std::unique_ptr<scalar> reduce(
  const column_view &col,
  std::unique_ptr<aggregation> const &agg,
  data_type output_dtype,
  rmm::mr::device_memory_resource *mr = rmm::mr::get_current_device_resource());
```

The output-type of the scalar is passed as a parameter. This means that the reduce function requires a double type-dispatch. The 1st type-dispatch is for the input `col` column-type and the 2nd type-dispatch is for the output-type `output_dtype`. Although operations like `sum` and `product` only work with numeric types, `min` and `max` handle non-numerics as well. With over 20 numeric types (`int, float, bool, timestamp, duration`), the combination is over 400. That is, a double type-dispatch creates 400 unique code-paths for each of the simple reduction types. And the `min` and `max` operations also includes the strings type.

Adding the dictionary column type to this code increased the compile time for _each of these_ from ~5 minutes to ~18 minutes.

Note that the compound operations (`mean`, `std`, and `var`) all compile in less than 2 minutes because the 2nd type-dispatch is isolated to only the two float types. Adding dictionary support to these operations did not change the compile time significantly.

I propose improving the compile time for the simple reduce ops by trying to remove the 2nd type-dispatcher call for the output-type. For operations like `min` and `max`, we could reasonable restrict the output-type to be equal to the input-type. However, for the other 3 operations (`sum`, `product`, `sum-of-squares`) it is reasonable to expect an output-type different (larger, say) than the input column-type.

But if the output-type is generally the same as the input-type we could optimize for that case. And whenever the output-type does not match the input-type we can perform the reduction operation on a hardcoded type (`int64_t` for integer columns and `double` for floating point columns) and then cast the single scalar result to the output type upon return. The extra cast step would be a performance hit but only applicable if the types do not match.

Testing with the `sum` operation, the compile time is now about ~30s. This includes handling the output-type cast. Running the gbenchmarks for reduction for `sum` showed no change in performance. But the benchmark code logic sets the output-type to the input column-type. Testing with unmatched types showed a significant slow down (~30%) attributed to the extra, final scalar cast step. Perhaps there are some techniques to improve this cast step -- like converting the type without allocating a new scalar.

One other question for consideration or clarification. Are they cases where the overflow side-effects of reduce on smaller output-types are expected and desired? For example, summing 1000 `uint8` values can currently cause intermediate overflows as the values accumulate. This seems non-deterministic and probably undefined behavior but I wanted to ask to be sure.

Changes here would also require reworking the `any` and `all` operations which currently call `min` and `max` but require the output-type to be boolean. Therefore, this seems a good optimization for these 2 ops since the 2nd type-dispatch would not be required.

Overall, I think this could improve the code a bit by defactoring the `result_type_dispatcher` defined in [simple.cuh](https://github.com/rapidsai/cudf/blob/e4404e45a07ff2b599184724dd4bc564c0329d8c/cpp/src/reductions/simple.cuh#L73-L88) which has different rules for different ops and type combinations:
```
  static constexpr bool is_supported_v()
  {
    // for single step reductions,
    // the available combination of input and output dtypes are
    //  - same dtypes (including cudf::wrappers)
    //  - any arithmetic dtype to any arithmetic dtype
    //  - bool to/from any arithmetic dtype
    //  - fixed_point to fixed_point
    return cudf::is_convertible<ElementType, ResultType>::value &&
           (std::is_arithmetic<ResultType>::value ||
            std::is_same<Op, cudf::reduction::op::min>::value ||
            std::is_same<Op, cudf::reduction::op::max>::value) &&
           !cudf::is_fixed_point<ResultType>() &&
           !std::is_same<ResultType, cudf::list_view>::value &&
           !std::is_same<ResultType, cudf::struct_view>::value;
  }
```
Adding a new legal type/op combination to this logic seems problematic. Without this 2nd dispatch, each operation can handle their combination of types more independently and more naturally.

**Comment by harrism** [comment]
I support this direction. :)

**Comment by revans2** [comment]
From the Spark perspective we want to avoid overflows and always does what you are proposing.  The output of sum is always a long or a double. I would have to look to be 100% sure that for fixed point decimal it does the same thing, but I am fairly sure that we would want to output DECIMAL64 from SUM in those cases.

**Comment by jrhemstad** [comment]
In groupby we always fix the output type according to these rules: https://github.com/rapidsai/cudf/blob/88821fb7fd4b81a98b8efa2f2ab8c7871d02bdef/cpp/include/cudf/detail/aggregation/aggregation.hpp#L232-L391

min/max use the same type as the input, summing integers always uses 64bit, etc. 

Seems sensible to do the same thing for reductions.
