### ISSUE TITLE
[BUG] A possible source of memory leaks in cudf/bindings

### ISSUE THREAD

**Issue by pearu** [rapidsai/cudf#672]
Allocating memory using `malloc` in 
[cdef gdf_column** list_lhs = <gdf_column**>malloc(len(col_lhs) * sizeof(gdf_column*))](https://github.com/rapidsai/cudf/blob/b79c56a5dad2cf3e0740ba4a89b08c808d21be31/python/cudf/bindings/join.pyx#L45)
is not freed within the function where it is defined.

Similar pattern is used elsewhere.

**Comment by kkraus14** [comment]
cc @dantegd

**Comment by seunghwak** [comment]
```python
33     cdef gdf_context* context = create_context_view(0, method, 0, 0, 0)
48     cdef gdf_column** list_lhs = <gdf_column**>malloc(len(col_lhs) * sizeof(gdf_column*))
49     cdef gdf_column** list_rhs = <gdf_column**>malloc(len(col_rhs) * sizeof(gdf_column*))
50     cdef gdf_column** result_cols = <gdf_column**>malloc(result_num_cols * sizeof(gdf_column*))
57         list_lhs[idx] = column_view_from_column(col._column)
64             result_cols[res_idx] = column_view_from_NDArrays(0, None, mask=None, dtype=col._column.dtype, null_count=0)
76         result_cols[res_idx] = column_view_from_NDArrays(0, None, mask=None, dtype=dtype, null_count=0)
86         list_rhs[idx] = column_view_from_column(col._column)
93             result_cols[res_idx] = column_view_from_NDArrays(0, None, mask=None, dtype=col._column.dtype, null_count=0)
```

There are more places for memory leaks. I think we should establish a coding convention to use std:unique_ptr (or std::shared_ptr for shared ownership) for owned memory allocations and use raw pointers for observing memory locations. And we may use heap allocations only when memory allocation size can be large.
