### ISSUE TITLE
[BUG] pandas.isnull is broken by CudaDF

### ISSUE THREAD

**Issue by andyndang** [rapidsai/cudf#6743]
**Describe the bug**
I'm getting exception when calling `pandas.isnull` on a cudf:

```
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```
**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

Code:
```
import pandas as pd
pd.isnull(cudf_dataframe)
```

**Expected behavior**
Return false

**Environment overview (please complete the following information)**
 - Environment location: blazingsql.com
 - Method of cuDF install: blazingsql.com
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by galipremsagar** [comment]
`pandas.isnull` works only for host objects and not gpu objects(cudf_dataframe in this case). Instead you can use:

```
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> import cudf
>>> cudf_dataframe = cudf.DataFrame({'a':[1, 2, 3], 'b':[1, 2, None]})
>>> pd.isnull(cudf_dataframe)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/pandas/core/dtypes/missing.py", line 124, in isna
    return _isna(obj)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/pandas/core/dtypes/missing.py", line 163, in _isna
    return _isna_ndarraylike(np.asarray(obj), inf_as_na=inf_as_na)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/nvme/0/pgali/envs/cudfdev/lib/python3.7/site-packages/cudf/core/dataframe.py", line 924, in __array__
    "Implicit conversion to a host NumPy array via __array__ is not "
TypeError: Implicit conversion to a host NumPy array via __array__ is not allowed, To explicitly construct a GPU matrix, consider using .as_gpu_matrix()
To explicitly construct a host matrix, consider using .as_matrix()
>>> cudf_dataframe.isnull()
       a      b
0  False  False
1  False  False
2  False   True
```

**Comment by andyndang** [comment]
So would you say this is a Pandas bug then?

**Comment by galipremsagar** [comment]
> So would you say this is a Pandas bug then?

Not exactly, pandas objects are on cpu memory whereas cudf objects are on gpu memory, implicit conversion of gpu object to cpu object is not allowed. The straight alternative to `pd.isnull` in this case is `df.isnull`, but if you are looking for something like `cudf.isnull` similar to `pd.isnull` do let us know.

**Comment by kkraus14** [comment]
Closing as this is answered.
