### ISSUE TITLE
dask_cudf performance is costlier than cuDf

### ISSUE THREAD

**Issue by KeertiBafna** [rapidsai/cudf#6747]
I have a GPU node with 2 Tesla P-100's . I am comparing the cost of using cuDF compared to dask_cudf on a fairly big dataframe. 
The dataframe size is 74886209 rows × 15 columns . 

**A simple groupby sum operation on cuDF dataframe takes 0.045 seconds**
df = df.groupby('d_id').sales.sum().reset_index()

**The same operation of a dask_cudf df takes 1.199 seconds**
df = df.groupby('d_id').sales.sum().reset_index().compute()

**_This is how my client looks like:_**
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
from dask_cuda.initialize import initialize

# Configurations
protocol = "ucx"
interface = "eth0"    # DGX-2
enable_tcp_over_ucx = True
enable_nvlink = False
enable_infiniband = False

initialize(
    create_cuda_context=True,
    enable_tcp_over_ucx=enable_tcp_over_ucx,
    enable_infiniband=enable_infiniband,
    enable_nvlink=enable_nvlink,
)

cluster = LocalCUDACluster(n_workers=2, local_directory="/home/keerti",
                          memory_limit=0.8, device_memory_limit=0.8,
                           CUDA_VISIBLE_DEVICES=[0,1],
                            protocol=protocol,
                            interface=interface,
                            enable_tcp_over_ucx=enable_tcp_over_ucx,
                            enable_infiniband=enable_infiniband,
                            enable_nvlink=enable_nvlink,
                            rmm_pool_size="25GB",
                            rmm_managed_memory=False
                        )
client = Client(cluster)

Is there anything i might be missing? Why is dask_cudf slower compared to cudf in this case ?

**Comment by beckernick** [comment]
In general, you should expect to see some overhead using Dask compared to raw cuDF on a single GPU. You might also expect some additional overhead using multiple GPUs for operations that can be comfortably done in such a short time by cuDF on one GPU.

With that said, a few things could be going on here. If you're able to share your full code (cluster setup, reading data, running the code of interest, etc.), it may be possible to provide more targeted info.

**Comment by KeertiBafna** [comment]
@beckernick  Please find below my full code:
## Cluster setup
import cudf; print('cuDF Version:', cudf.__version__)
import dask_cudf; print('dask_cudf Version:', dask_cudf.__version__)
import pandas as pd; print('pandas Version:', pd.__version__)
import pyarrow.parquet as pq
import dask.dataframe as dd
import dask; print('dask Version:', dask.__version__)
import numpy as np
import glob
from time import time
import logging
logging.getLogger("py4j").setLevel(logging.ERROR)
import rmm
import glob
import os
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
from dask_cuda.initialize import initialize
protocol = "ucx"
interface = "eth0"    # DGX-2
enable_tcp_over_ucx = True
enable_nvlink = False
enable_infiniband = False

initialize(
    create_cuda_context=True,
    enable_tcp_over_ucx=enable_tcp_over_ucx,
    enable_infiniband=enable_infiniband,
    enable_nvlink=enable_nvlink,
)

cluster = LocalCUDACluster(n_workers=2, local_directory="/home/keerti",
                          memory_limit=0.8, device_memory_limit=0.8,
                           CUDA_VISIBLE_DEVICES=[0,1],
                            protocol=protocol,
                            interface=interface,
                            enable_tcp_over_ucx=enable_tcp_over_ucx,
                            enable_infiniband=enable_infiniband,
                            enable_nvlink=enable_nvlink,
                            rmm_pool_size="25GB",
                            rmm_managed_memory=False
                        )
client = Client(cluster)

#Calculations and Timing

def get_parquet_list(path):
    l1 = []
    for name in glob.glob(path + '/**/*.parquet', recursive=True):
        l1.append(name)
    return l1

mode= 'd-cudf'

if mode == 'd-cudf':
    path = '/mnt/pipeline/home/keerti/WBA/compute_prep_div_410.parquet'
    df = dask_cudf.io.parquet.read_parquet(path)
    t0 = time()
    df = df.groupby('d_id').sales_units.sum().reset_index().compute()
    dt_dask_cudf = time() - t0
    print(dt_dask_cudf)
else:
    path = '/mnt/pipeline/home/keerti/WBA/compute_prep_div_410.parquet'
    pa_tbl = get_parquet_list(path)
    df = cudf.read_parquet(pa_tbl)
    t0 = time()
    df = df.groupby('d_id').sales_units.sum().reset_index()
    dt_cudf = time() - t0
    print(dt_cudf)

**Comment by beckernick** [comment]
Thanks. That's quite helpful. In particular, this is the key section:

```python
df = dask_cudf.io.parquet.read_parquet(path)
t0 = time()
df = df.groupby('d_id').sales_units.sum().reset_index().compute()
dt_dask_cudf = time() - t0
```

Unlike raw cuDF, Dask operations are generally [lazily evaluated](https://en.wikipedia.org/wiki/Lazy_evaluation). This is present in many distributed computing frameworks, including Dask and Spark. When you call `df = dask_cudf.io.parquet.read_parquet(path)` what you're actually doing is adding a task to a task graph that says "I should read some data." Until you force it to execute, it doesn't. When you call `compute`, in this case you are capturing the time it takes both to read your data and conduct your groupby aggregation.

This section of the 10 minute guide to cudf and dask-cudf might be informative as well: https://docs.rapids.ai/api/cudf/stable/10min.html#Dask-Performance-Tips

**Comment by kkraus14** [comment]
To add to what @beckernick said, it also looks like you're doing your communication over TCP which will possibly bottleneck the two GPUs communicating to the combine the results of groupbys.

Generally, if a computation fits on a single GPU then you don't need to do any of that communication.

**Comment by KeertiBafna** [comment]
My bad, i didn't explain the code. The time i mentioned in the question was only aggregation, i calculated the time taken for just reading a parquet and substracted it from the dt_dask_cudf (dt_dask_cudf - time_taken_to_load). 

To make it more clear, there are two steps here 1: Loading the data, 2: Aggregation, the total time combined for these two for cuDf is 3.36 seconds wherein the total time for dask_cudf is around 6 seconds.

The bigger objective here is that i want both my gpu's to be utilised. The combined memory of my gpu's is 32 ( 2* 16 P100), i assumed that if i have a single df with memory greater than 16 and i'm using dask_cudf, it would utilise the memory of the second gpu but i am not seeing it. I get a memory error. Is this assumption wrong ? If not, am i missing something here ?

**Comment by kkraus14** [comment]
I believe this was answered so I'm going to close this. @KeertiBafna if you have further questions related to using Dask + cuDF feel free to open a new issue.
