### ISSUE TITLE
[BUG] Typo in cudf/core/column/numerical.py: "Buffer has no attribute from_array_lik"

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/cudf#6778]
it looks like this is a typo because we receiving this error in our `rapids-single-cell-examples` notebooks:

![image](https://user-images.githubusercontent.com/1242464/99313499-a746b380-282d-11eb-9717-7a7d84881561.png)

It looks like this went out with the 0.16 release and is still present in the 0.17 branch. I only see the mispelling in that one file and I don't see see any other spellings that are missing the 'e'. Here's a grep of the cudf repo:

```bash
python/cudf/cudf/utils/cudautils.py:    output_dary = cuda.device_array_like(data)
python/cudf/cudf/core/column/numerical.py:                    data=Buffer.from_array_lik(ary),
python/cudf/cudf/core/buffer.py:        data : Buffer, array_like, int
python/cudf/cudf/core/buffer.py:            self._init_from_array_like(data, owner)
python/cudf/cudf/core/buffer.py:            self._init_from_array_like(np.asarray(data), owner)
python/cudf/cudf/core/buffer.py:            self._init_from_array_like(np.asarray(data), owner)
python/cudf/cudf/core/buffer.py:    def _init_from_array_like(self, data, owner):
python/cudf/cudf/core/buffer.py:            self._init_from_array_like(dbuf, owner)
python/cudf/cudf/core/frame.py:        lower : scalar or array_like, default None
python/cudf/cudf/core/frame.py:        upper : scalar or array_like, default None
docs/cudf/source/guide-to-udfs.ipynb:    "output_dary = rmm.device_array_like(a_dary)\n",
```

**Comment by cjnolet** [comment]
I think this issue was referenced in a #6887 by mistake because I don't see any changes related to this and it looks like it hasn't been fixed. Can we open this issue back up?

**Comment by kkraus14** [comment]
@cjnolet #6887 was specifically fixing this issue. It turned out to be an 0d-array that caused going down the codepath with this typo, but was more generally unhandled.
