### ISSUE TITLE
[BUG] [FEATURE] print_gdf_column() deficient

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#680]
Our test utilities have a function named `print_gdf_column()`. It is obviously of key importance when testing and when debugging our implementations. Also, the less convenient and flexible its output is, the more time does a developer need to decipher its output and derive useful insights from it.

Having said that...

* It does not allow indicating that column data is of bit resolution (e.g. for stencils).
* It handles `int8_t` data as characters, always (AFAICT) and thus prints junk for such columns, especially for higher values.
* It does not print indices at terminal column and row heads
* It does not use uniform space per-element, and will use as many characters as the value has digits (for integer values).
* It does not support setting the precision or other format aspects for floating-point columns
* It does not account for terminal width automatically, nor does it allow manually setting line width.
* It does not support printing contiguous subcolumns of a column.
* It does not print relevant column meta-data, such as the type name, size, number of null values, and nullability.

I consider the first 2 points to be bugs and the rest to be important missing features.

PS - The implementation should use the type dispatcher, but currently doesn't.

**Comment by jrhemstad** [comment]
No longer relevant in libcudf++.
