### ISSUE TITLE
Avro reader has very limited test coverage

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#6802]
Avro reader currently has a single test, with a few more basic tests pending to be merged.

Some cases not covered:

- [ ] Large input files;
- [x] Columns of all supported types;

**Comment by vuule** [comment]
Marking as P0 for 0.18 as it's preventing other Avro refactoring work.

**Comment by cwharris** [comment]
Maybe we can use [Apache's python-based reader/writer](https://anaconda.org/conda-forge/avro) to generate test data. Generating files via python from the c++ side seems backwards, but do we have a methodology to store/load pre-generated test data/files in tests?

**Comment by vuule** [comment]
> Maybe we can use [Apache's python-based reader/writer](https://anaconda.org/conda-forge/avro) to generate test data. Generating files via python from the c++ side seems backwards, though. Do we have a methodology to store/load pre-generated test data/files in tests?

Maybe I'm misunderstanding the question, but you can generate tmp avro files using fastavro in Python tests. There are tests that already do this.

**Comment by cwharris** [comment]
It would be nice to have c++ tests, though, since the reader is implemented at that level.

**Comment by vuule** [comment]
missing large tests still relevant

**Comment by vuule** [comment]
Closing, since #12912 added larger tests
