### ISSUE TITLE
[FEA] need to support cudf.DataFrame([[‘a’,‘b’]]).corr() when set ‘method=spearman’, we only support ‘method=pearson’ so far

### ISSUE THREAD

**Issue by dominicshanshan** [rapidsai/cudf#6804]
**Is your feature request related to a problem? Please describe.**
from time series analysis, need to support spearman correlation matrix calculation in cuDF

**Describe the solution you'd like**
similar like pandas.DataFrame().corr(method='spearman')

**Additional context**
is it possible to let me know this feature adding roadmap? big thanks !

**Comment by beckernick** [comment]
This would be a welcome addition. This could be implemented by combining `series.rank()` with the existing pearson correlation.

Would you be interested in contributing this?

**Comment by dominicshanshan** [comment]
love to .... but need your guidance ;) @beckernick

**Comment by beckernick** [comment]
Pearson correlation is currently the implementation of correlation in cuDF Python currently. Spearman correlation is defined mathematically as the pearson correlation of the ranks of the columns. Rank is implemented currently. This means we have everything needed in cuDF Python.

There are several ways to do this. One way might be to switch implement two "private" functions, `_corr_pearson` and `_corr_spearman`. `_corr_pearson` could be the existing implementation, and `_corr_spearman` would use `rank` and then call `_corr_pearson`. The `corr` function could then delegate appropriately depending on the method argument. Then, you could update the series/dataframe level `corr` functions to allow for spearman.

https://github.com/rapidsai/cudf/blob/de5577c1648e4cece2bc76a1f3a70e6ee4ae4bbf/python/cudf/cudf/core/column/numerical.py#L330-L339

**Comment by dominicshanshan** [comment]
need more time to finish, holiday season in China ;)
