### ISSUE TITLE
[BUG] Headers are included in wrong order

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#681]
(This can be seen as a sub-issue of #479.)

In many cudf `.cpp` and `.cu` files we see project-specific or even translation-unit-specific headers include _after_ system or third-party-library headers.

This is the opposite of the [established and recommended order](https://stackoverflow.com/a/2762596/1593077), which is such that no include should depends on an include appearing _later_. Or in other words:

1. headers corresponding to this cpp file (if applicable)
2. headers from the same component,
3. headers from other components,
4. system headers.

Part of the reason flipping the order is important is, that the way things are now, it's much more likely that a project-specific or TU-specific header does not itself include headers it needs, and implicitly relies on the fact that the code using it includes the necessary header first. This misguides developers w.r.t.  dependencies of the more specific header, and may cause surprising bugs if the same - supposedly functioning - header is included, but the compiler complains about undefined constructs.

PS - relative-path includes (`#include "foo.h"`) should come before includes from the compiler-defined path (`#include <bar.h>`) and this doesn't contradict the above ordering, if we make sure to only use relative-path includes when they're really called for.

**Comment by williamBlazing** [comment]
Are there static analysis tools that we can employ that help us keep track of these sort of things? I imagine that if there are, the first time we would employ them it would be a nightmare to address all the issues it would find, but that should not discourage us.

**Comment by eyalroz** [comment]
@williamBlazing : Here are [three possible tools](https://www.slant.co/topics/263/~best-open-source-c-static-analysis-tools) which may or may not offer this.  I think that some IDEs take care of include orders and even redundant-include-removal. But - if we're just talking include order, it's quite simple to see when this is the case and just fix it, like I did for testing code in PR #908 .

**Comment by jrhemstad** [comment]
> Are there static analysis tools that we can employ that help us keep track of these sort of things? I imagine that if there are, the first time we would employ them it would be a nightmare to address all the issues it would find, but that should not discourage us.

There are indeed tools that do this, including IDEs.

Annoyingly, I noticed VSCode would _alphabetize_ includes when I ran the auto-formatter. I had to disable that.
