### ISSUE TITLE
[QST] Spreading GPU cudf operations over multiple GPUs

### ISSUE THREAD

**Issue by cornelis22** [rapidsai/cudf#6812]
**What is your question?**
Hi,

I want to parallel-ize, if it is a correct term, my function across multiple cards. The execution time for a grid search on a single card takes an hour to complete.

By grid search, I mean my function takes a certain combination of inputs and I am trying to figure out which is the best.

Do I use the Python multiprocessing module or is there another way? Links to simple tutorial will be great

**Comment by kkraus14** [comment]
See here: https://docs.rapids.ai/api/cudf/stable/dask-cudf.html
