### ISSUE TITLE
[QST] Should cudf support an incoming schema for parquet writing and possibly other formats

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#6816]
**What is your question?**
It seems like there are options sneaking in to the writing for parquet such as int96 timestamps and decimal precision that indicate that the data alone is not enough to know how to write a parquet file. Cudf will probably never support all the types that are in parquet and has no real need. The software using cudf could have knowledge about the desired parquet schema that cudf has no real interest in knowing and know way of guessing properly. In those cases, it seems that it would be nice for cudf to have opinionated defaults, but support an incoming schema of how to write the data. If no schema is given, it writes data as it wants, but if the schema exists then cudf would attempt to write the data in this way. Obviously, there can be invalid schemas passed in, but I think it's completely fine to error if the schema isn't possible. Further, I think there are times when coercion is desired and times when it isn't. Something like converting decimals to floats on write could be desired or an error. I think the default should be error, but a boolean should exist in the write options to allow coercion of types where possible.

What are the thoughts on something like this?

**Comment by kkraus14** [comment]
cc @vuule @devavret who have been looking at parquet pretty heavily and may have some opinions here

**Comment by devavret** [comment]
Passing in a schema means you primarily want coercion. Apart from int96, are there other types that we want to write that don't have a cuDF equivalent? i.e. cannot be achieved with a `cuDF::cast` before writing.

**Comment by hyperbolic2346** [comment]
I'll let @revans2 and @jlowe chime in wish specifics, but int96 and decimal precision come immediately to mind. I think they were talking about an issue with structs or lists as well.

**Comment by kkraus14** [comment]
I think being able to specify that a column is a `Map` column is likely another situation since libcudf current has no `Map` support.

**Comment by jlowe** [comment]
> int96 and decimal precision come immediately to mind. I think they were talking about an issue with structs or lists as well.

Spark needs to be able to specify the precision of the decimal being written (we can't assume the max precision for DECIMAL64 is appropriate, for example).  And @kkraus14 is correct, Spark needs to specify that a Parquet map type is being written rather than a list-of-struct-of-pairs column as cudf sees it.

**Comment by revans2** [comment]
Yes, we also have a situation with storing the Binary type.  We don't support reading it yet, but we need to be able to say is this a list of bytes that is not nullable or is it binary.

**Comment by devavret** [comment]
> we also have a situation with storing the Binary type

What's the cudf column equivalent of binary type? What do you use/plan to use to write this?

**Comment by jlowe** [comment]
> What's the cudf column equivalent of binary type?

LIST of non-nullable INT8 or UINT8.  It could technically be implemented as a STRING as well, since cudf strings don't rely on string terminator characters.

> What do you use/plan to use to write this?

libcudf already supports a `byte_cast` function that returns a LIST of INT8 which is one way these columns could be created.  Another case would be loading a column from Parquet that's encoded as a binary column and preserving that column's schema when written to another Parquet file.

**Comment by hyperbolic2346** [comment]
I added a feature request for Apache Arrow's schema for parquet writing. This isn't the only possible approach, but content specific to that option should be routed there. This discussion is more an over-arching "do we need this" more than a "how would we do this", which the feature request covers.

**Comment by devavret** [comment]
As per the meeting today, the input metadata added in #7461 satisfies most of the spark use cases. I'll add a closes tag to this in that PR. Feel free to edit #7461 to remove the tag if you disagree.
