### ISSUE TITLE
fail to import cudf (jupyter notebook)

### ISSUE THREAD

**Issue by micaelamaria** [rapidsai/cudf#6818]
I run ubuntu 20.04 with python 3.8.3 - I installed cudf with the command: 
```
conda create -n rapids-0.16 -c rapidsai -c nvidia -c conda-forge \
    -c defaults rapids=0.16 python=3.8 cudatoolkit=10.1
```
whenever I try to import cudf I get the same error - "ModuleNotFoundError: No module named 'cudf'" - even though I installed it without any problems.

Any hints?

**Comment by beckernick** [comment]
Can you share how you activate your conda environment and start Python?

**Comment by micaelamaria** [comment]
I didn't activate a conda environment. Only run "import cudf" on a cell in my jupyter notebook

**Comment by micaelamaria** [comment]
big detail ;)

**Comment by beckernick** [comment]
Could you share the commands you use to test this? Perhaps something that looks similar to:

```
(base) nicholasb@exp01:~$ conda activate rapids
(rapids) nicholasb@exp01:~$ python
Python 3.7.8 | packaged by conda-forge | (default, Nov 17 2020, 23:45:15)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
>>>
```

**Comment by micaelamaria** [comment]
(base) mik@prisma-ds:~$ conda activate rapids-0.16
(rapids-0.16) mik@prisma-ds:~$ python
Python 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cudf
/home/mik/anaconda3/envs/rapids-0.16/lib/python3.8/site-packages/cudf/utils/gpu_utils.py:156: UserWarning: No NVIDIA GPU detected
  warnings.warn("No NVIDIA GPU detected")
>>>

**Comment by kkraus14** [comment]
Given this has gone stale I'm going to close this. @micaelamaria based on the above message it looks like cudf imported as expected but you don't have a GPU on your system. Please raise a new issue if there's further problems.
