### ISSUE TITLE
Showing cudf content or printing .head() of a cudf is extremely slow 

### ISSUE THREAD

**Issue by DKorman** [rapidsai/cudf#6841]
**What is your question?**
I am using rapids docker, and on jupyter notebook whenever I try to see content of a cudf, or the frist couple of rows, this takes a really long time. Possibly doesnt even execute?

Regards,
Davor

**Comment by galipremsagar** [comment]
Can you share the dataframe and code where you are seeing long execution times?

**Comment by kkraus14** [comment]
No answer, closing.
