### ISSUE TITLE
[BUG] df.min() and df.max() doesn't work with a mix of boolean and non-boolean columns

### ISSUE THREAD

**Issue by skirui-source** [rapidsai/cudf#6846]
``` python
data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
gdf=gd.DataFrame(data)
gdf.min()
```
<details>

TypeError                                 Traceback (most recent call last)
~/cudf/python/cudf/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1839             data = as_column(
-> 1840                 memoryview(arbitrary), dtype=dtype, nan_as_null=nan_as_null
   1841             )

TypeError: memoryview: a bytes-like object is required, not 'list'

During handling of the above exception, another exception occurred:

ArrowInvalid                              Traceback (most recent call last)
~/cudf/python/cudf/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1868                         if nan_as_null is None
-> 1869                         else nan_as_null,
   1870                     ),

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._sequence_to_array()

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: Could not convert False with type numpy.bool_: tried to convert to double

During handling of the above exception, another exception occurred:

ArrowInvalid                              Traceback (most recent call last)
<ipython-input-12-f07b64c167a1> in <module>
      1 data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
      2 gdf=gd.DataFrame(data)
----> 3 gdf.min()

~/cudf/python/cudf/cudf/core/dataframe.py in min(self, axis, skipna, level, numeric_only, **kwargs)
   5687             level=level,
   5688             numeric_only=numeric_only,
-> 5689             **kwargs,
   5690         )
   5691 

~/cudf/python/cudf/cudf/core/dataframe.py in _apply_support_method(self, method, axis, *args, **kwargs)
   6524                     result[col] = support_result[idx]
   6525             else:
-> 6526                 result = Series(result)
   6527                 result = result.set_index(self._data.names)
   6528             return result

~/cudf/python/cudf/cudf/core/series.py in __init__(self, data, index, dtype, name, nan_as_null)
    190 
    191         if not isinstance(data, column.ColumnBase):
--> 192             data = column.as_column(data, nan_as_null=nan_as_null, dtype=dtype)
    193         else:
    194             if dtype is not None:

~/cudf/python/cudf/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1892                     )
   1893                     data = as_column(
-> 1894                         data, dtype=dtype, nan_as_null=nan_as_null
   1895                     )
   1896     return data

~/cudf/python/cudf/cudf/core/column/column.py in as_column(arbitrary, nan_as_null, dtype, length)
   1776         elif arb_dtype.kind in ("O", "U"):
   1777             data = as_column(
-> 1778                 pa.Array.from_pandas(arbitrary), dtype=arbitrary.dtype
   1779             )
   1780             # There is no cast operation available for pa.Array from int to

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.Array.from_pandas()

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib.array()

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/array.pxi in pyarrow.lib._ndarray_to_array()

~/compose/etc/conda/cuda_10.1/envs/rapids/lib/python3.7/site-packages/pyarrow/error.pxi in pyarrow.lib.check_status()

ArrowInvalid: Could not convert False with type numpy.bool_: tried to convert to double
</details>

**Comment by taureandyernv** [comment]
So basically, here is the pandas output
```
import pandas as pd
data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
pdf=pd.DataFrame(data)
pdf.min()
```
outputs:
```
a        1
b        3
c    False
dtype: object
```
and we get your error above with 
```
import cudf
data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
gdf=cudf.DataFrame(data)
gdf.min()
```

However, converting the bool column to integer or double gives you the right answer

```
import cudf
data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
gdf=cudf.DataFrame(data)
gdf['c'] = gdf['c'].astype("double")
gdf.min()
```
outputs
```
a    1.0
b    3.0
c    0.0
dtype: float64
```

Have we had any movement on solving this? @skirui-source

**Comment by skirui-source** [comment]
@taureandyernv  No. I am working on other tickets as of now, I haven't made any further actions to solve this

**Comment by galipremsagar** [comment]
The real issue here currently is that of @taureandyernv pointed out. We would have to throw an error because pandas supports mixed types and cudf doesn't.

**Comment by beckernick** [comment]
As of 21.08, we apparently automatically coerce the bool to avoid the mixed type issue. This feels reasonable enough, as `0 == False` and `1 == True` will both return True. Mixed type isn't an option, as Prem mentioned.

```python
import cudf
data={"a": [1, 2, 3], "b": [3.0, 4.0, 5.0], "c": [True, True, False]}
gdf=cudf.DataFrame(data)
gdf.min()
a    1.0
b    3.0
c    0.0
dtype: float64
```

I'm going to close this issue, but if folks want to discuss whether we should throw an error here please feel free to re-open.
