### ISSUE TITLE
[QST] Arrow Usage with CuDF

### ISSUE THREAD

**Issue by vibhatha** [rapidsai/cudf#6849]
Does CuDF support mapping data from a PyArrow table directly or does it work with ChunkArrays or Arrays in Arrow?

**Comment by kkraus14** [comment]
Hi @vibhatha cuDF works entirely in GPU memory, so you can't memmap directly as you normally would with CPU memory. We follow the same memory layout as Apache Arrow with the exceptions of using a byte per boolean (as opposed to a bit for Arrow), and support smaller bitwidth decimals (currently decimal32 and decimal64).

In cuDF all columns use contiguous memory under the hood, so we don't directly support ChunkedArrays like Arrow has. Generally, we defer to an upstream framework like BlazingSQL, Dask, or Spark to use cuDF APIs and do this chunking automatically.

**Comment by vkhodygo** [comment]
@kkraus14 I've been meaning to ask this for quite some time: what stands behind the choice to use bytes to store bools? As someone who works with big data full of indicator columns switching to PyArrow backend in Pandas helped immensely with memory consumption. It also allows to move from larger than memory datasets to something manageable as well as to reduce the code complexity.
