### ISSUE TITLE
[BUG] snappy compression off by default

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#6851]
**Describe the bug**

Pandas to_parquet defaults to `compression='snappy'` but `cudf`/`dask_cudf` do not appear to (0.16)

Reference spec: https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_parquet.html

**Steps/Code to reproduce bug**

Explicitly snappy:
```
%%time
! rm -rf lines10M*
! ( echo "Line,F2,F3,N,I" \
    && perl -E 'for($i=0;$i<10000000;$i++){say "Line $i,field2,field3,",int rand 100,",$i" }' \
  ) > lines10M.csv
! echo "generated csv, now making parquet" && ls -alh lines10M.csv
dask_cudf.read_csv('lines10M.csv').to_parquet('lines10M.parquet', compression='snappy')
! du -hs lines10M.parquet
```

=> `133M	lines10M.parquet`

Erasing `compression='snappy'` =>  `314M	lines10M.parquet`

**Expected behavior**

Both should be ~`133M`

**Environment overview (please complete the following information)**

latest stable 0.16 via conda/docker in a 10.2 env

**Comment by vuule** [comment]
Closing, should be fixed via #6967
