### ISSUE TITLE
[FEA] factorize function

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#6871]
**Is your feature request related to a problem? Please describe.**
In exploring a few xarray workflows I found I needed [factorize](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.factorize.html) as a top level function

**Describe the solution you'd like**
Pandas has a [factorize](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.factorize.html) function.  It would be great if this feature also existed for cuDF

```python
In [39]: pd.factorize(pd.Index([1, 2, 3, 1]))
Out[39]: (array([0, 1, 2, 0]), Int64Index([1, 2, 3], dtype='int64'))
```

I would like the above to exist for cuDF

> cudf.factorize(cudf.Index([1, 2, 3, 1]))

**Describe alternatives you've considered**
No alternatives considered

**Comment by brandon-b-miller** [comment]
We have `Series.factorize()` [here](https://github.com/rapidsai/cudf/blob/branch-0.17/python/cudf/cudf/core/series.py#L2545) so this should be fairly easy and just require moving some code around + some tests
