### ISSUE TITLE
Series.map[FEA]

### ISSUE THREAD

**Issue by jfpuget** [rapidsai/cudf#6888]
**Is your feature request related to a problem? Please describe.**
I could not find an equivalant to pandas.Series.map() function in cudf.

**Describe the solution you'd like**
A map function that works on cudf series as the pandas equivalent

**Describe alternatives you've considered**
Moving to pandas.

**Additional context**

**Comment by kkraus14** [comment]
This was added in https://github.com/rapidsai/cudf/pull/6459

**Comment by jfpuget** [comment]
ok, I am using 0.16.  Will move to 17 hen, thanks.
