### ISSUE TITLE
[FEA] Parquet writer, use cudf_dtype, not ConvertedType to know data in column

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6894]
In parquet writer, the `ConvertedType` is assumed to be the type of the input columns in kernels because that is generally the type we get while reading.https://github.com/rapidsai/cudf/blob/0cc1fff48886bd70751bd141cafae2c61f89dda0/cpp%2Fsrc%2Fio%2Fparquet%2Fpage_enc.cu#L179 There are exceptions e.g. when timestamp is written using int96, we needed to set the `ConvertedType` to `UNKNOWN`.https://github.com/rapidsai/cudf/blob/2ce59fccaac0277cc79a4d0d3a961adb90f1cd21/cpp%2Fsrc%2Fio%2Fparquet%2Fwriter_impl.cu#L781-L782 Such cases need special handling while creating the schema as they cannot be changed in `parquet_column_view` because that will inform the EncColumnDesc which is used by the kernels. 

We should store and use the cudf dtype because that is more accurate in defining the contents of the input column.

After #6893, the separately stored cudf dtype can be removed because it exists in the stored member `column_device_view`.

**Comment by vuule** [comment]
Changes that resolve issue #6893 should also resolve this one. Assigning to @kaatish based on this, we can reassign if needed
