### ISSUE TITLE
[FEA] base aggregation clone method should be pure virtual

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#6901]
**Is your feature request related to a problem? Please describe.**
#6891 was caused by a clone method not being overridden in a derived aggregation class.  It would be nice if the compiler could catch these missing implementation errors.

**Describe the solution you'd like**
The `aggregation` base class should be abstract, with a pure-virtual `clone` method.  This will require anyone deriving the class to override methods or add fields to also override the `clone` method before the derived class can be instantiated.

**Describe alternatives you've considered**
There is a `derived_aggregation` templated class that makes implementing `clone` easier, but developers can intentionally or mistakenly ignore that class and still derive from `aggregation` directly and forget to override `clone`.

**Comment by karthikeyann** [comment]
As a side note, ideally enum for aggregation should be replaced with individual classes. An abstract `aggregation` class with pure virtual functions should serve as interface. Each aggregation has its own derived class.
But one advantage of enum is, enum makes it easy for aggregation dispatching, & condition checking (`if` or `switch`).
It's a design decision to take.

**Comment by jlowe** [comment]
This was fixed by #8052
