### ISSUE TITLE
[FEA] Parquet and ORC writer API should be a class

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6911]
Parquet writer has the feature to write in chunks. This currently carries around a state which is opaque to the user as it is not defined in a public header. Such feature can be better accessed if parquet writer is a class. This class could be constructed with a sink and other argument struct and would have a method to `write_table()` and `close()`. This is, in fact what the python interface is right now. This would allow us to not copy over certain arguments into the state object.
As for the concern about not being a function based API, there's precedent in libcudf in the form of `groupby()` which is also a class based API.

- [x] Parquet API
- [X]  ORC API

**Comment by vuule** [comment]
FWIW, Parquet writer has a class-based API in Python. Should be a good starting point for the C++ API design.
As a side note, ORC is missing the equivalent API.
