### ISSUE TITLE
[BUG] Wrong warning when invoking DataFrame.from_gpu_matrix method

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#6924]
**Describe the bug**
I am currently running RAPIDS 0.16.

When invoking the method `DataFrame.from_gpu_matrix()` it displays the following warning message.

> 
> /opt/conda/envs/rapids/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: DataFrame.from_gpu_matrix will be removed in 0.16. Please use cudf.DataFrame() to create a DataFrame out of a gpu matrix
>   """Entry point for launching an IPython kernel.
> [9]:
> 

Considering I am running RAPIDS 0.16 container (`rapidsai/rapidsai:cuda11.0-runtime-ubuntu18.04`), I think that method should be removed or the warming message updated with the latest version where that method would be available in cuDF.

**Steps/Code to reproduce bug**
```
import cudf
import cupy as cp

df = cudf.DataFrame({'a':range(nelem),
                     'b':range(500, nelem + 500),
                     'c':range(1000, nelem + 1000)})

gpu_matrix = df.as_gpu_matrix()

df2 = cudf.DataFrame.from_gpu_matrix(gpu_matrix)
```

Hope it helps!

**Comment by galipremsagar** [comment]
The deprecated API(`from_gpu_matrix`) is now removed as part of `0.17`: https://github.com/rapidsai/cudf/pull/6442/
