### ISSUE TITLE
[DOC] Remove 'from_gpu_matrix' example from "Update 10 minutes to cuDF and CuPy" tutorial

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#6925]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/stable/10min-cudf-cupy.html

**Describe the problems or issues found in the documentation**
One of the examples showcases the usage of the method `from_gpu_matrix`. This method was meant to be deprecated by v0.16. I think it is wellworth to change the example, showcasing how to use `cudf.DataFrame` instead.

Hope it helps!
Miguel

**Comment by galipremsagar** [comment]
This has been addressed in nightly(0.17), and should be out in stable as well when `0.17` is released.  Here is the updated tutorial in nightly: https://docs.rapids.ai/api/cudf/nightly/10min-cudf-cupy.html
