### ISSUE TITLE
[DOC] Release notes 

### ISSUE THREAD

**Issue by roarjn** [rapidsai/cudf#6931]
## Report incorrect documentation
It would be helpful to users to provide list of new features, bugs fixed to every release notes here. Perhaps it exists at another location. https://github.com/rapidsai/cudf/releases

**Location of incorrect documentation**
https://github.com/rapidsai/cudf/releases

**Describe the problems or issues found in the documentation**
Missing release notes documentation on Github.

**Steps taken to verify documentation is incorrect**
Went to https://github.com/rapidsai/cudf/releases

**Comment by harrism** [comment]
You might check the [changelog](https://github.com/rapidsai/cudf/blob/branch-0.17/CHANGELOG.md). Also, we do a release blog with every release, for a higher overview of what is new. [All release blogs are collected here](https://medium.com/rapids-ai/tagged/rapids-ai).

**Comment by roarjn** [comment]
Thanks. Change logs and blogs are helpful. Imho it would be helpful to maintain a short summary of major feature changes to the release notes. E.g which cudf release started supporting cuda 11.0 etc.

**Comment by harrism** [comment]
I think you can see that https://github.com/rapidsai/cudf/releases includes a summary of all changes starting with release 0.17.

**Comment by roarjn** [comment]
tried looking [here](https://github.com/rapidsai/cudf/releases) but could not find a summary.

**Comment by harrism** [comment]
@roarjn when I visit that page the first thing I see is the following summary (screenshot). The links are all clickable to go to pull requests to see full details.  All future releases will include a "breaking changes" section to list any changes to public APIs or behavior.

![image](https://user-images.githubusercontent.com/783069/102025824-94081300-3dee-11eb-9726-76255bc05693.png)

**Comment by roarjn** [comment]
Thanks @harrism.. perhaps 0.18 is on the private repo as I only see 0.17 without release notes.

**Comment by harrism** [comment]
Ooooh, I see. 0.17 and 0.18 releases are still drafts. 0.17 should be released this week, and then you will see it.
