### ISSUE TITLE
[QST]

### ISSUE THREAD

**Issue by Elias254** [rapidsai/cudf#6941]
**What is your question?**
Please share the code for data analytics (correlations and regressions) and visualization (scatter and bar) for data frame in blazingsql

**Comment by taureandyernv** [comment]
Please go to app.blazingsql.com.  this will open one of their free GPU instances on jupyterhub.  Go to `Welcome_to_BlazingSQL_Notebooks/intro_notebooks/` and that has all that you're looking for.  You can test and retest your ideas right there as well.

**Comment by Elias254** [comment]
> Please go to app.blazingsql.com. this will open one of their free GPU instances on jupyterhub. Go to `Welcome_to_BlazingSQL_Notebooks/intro_notebooks/` and that has much of what you're looking for. You can test and retest your ideas right there as well.

Thanks a lot
