### ISSUE TITLE
[FEA] Support list_contains() for looking up scalar values in list columns

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#6944]
It would be good to support a `list_contains()` operation on list columns, to check if each row contains a specified value.

The operation should take a `list` column and a scalar value to be looked up in each list row of the column.
(An overload with a vector search key can be added in the future.)

The operation must return a `bool` column, each value indicating whether the search key was found in the list row at the same index of the input column.

Here are some suggested policies for null-handling. (These might need to be parameterized at a later date.)
1. If the list row is null, `list_contains()` returns `null` for that row, regardless of the search key.
2. If the search key is null, `list_contains()` returns `null` for all rows in the column.
3. If the list row is non-null, but contains a null element, and the search key is non-null:
    a. Policy#1: `list_contains()` returns `true` if the search key is found. Otherwise, it returns null. (This behaviour is consistent with Spark/SQL semantics.)
    b. Policy#2: `list_contains()` returns a non-null true/false value, and ignores the null element.

The choice of policy for `#3` above could be keyed on whether nulls compare equal.

**Comment by revans2** [comment]
If it is not too much extra work I would love to see if we could also support a version that takes a column for the value being looked for instead of just a scalar.  With iterators it should not be that much more work and it would let Spark support more use cases.
