### ISSUE TITLE
[QST] cuda 11.1 support

### ISSUE THREAD

**Issue by gboeing** [rapidsai/cudf#6962]
When is cuda 11.1 support to be released, for use with the new RTX 30 series?

**Comment by kkraus14** [comment]
> When is cuda 11.1 support to be released, for use with the new RTX 30 series?

You should be able to use CUDA 11.0 with RTX 30 series cards without issue. If it gives you problems please let us know!

CUDA 11.1 support is currently being evaluated and we're hoping to have it in 0.18 in the February 2021 timeframe, but nothing is committed to as of yet.

**Comment by gboeing** [comment]
Thanks @kkraus14.

> You should be able to use CUDA 11.0 with RTX 30 series cards without issue.

Is that documented somewhere? I'm on Ubuntu 20.04. I initially tried to install CUDA 11.0 but during the NVIDIA driver installation phase it terminated with error and the NVIDIA installer log said that it could not detect a supported GPU. However, installing CUDA 11.1 works fine and my GPU is detected.

According to the CUDA 11.1 [release notes](https://docs.nvidia.com/cuda/archive/11.1.0/cuda-toolkit-release-notes/index.html):

> Added support for NVIDIA Ampere GPU architecture based GA10x GPUs GPUs (compute capability 8.6), including the GeForce RTX-30 series.

No such comment appears in the CUDA 11.0 [release notes](https://docs.nvidia.com/cuda/archive/11.0/cuda-toolkit-release-notes/index.html). Unless I'm misinterpreting that, **it looks like RTX 30 series support was added in CUDA 11.1, not 11.0**. In which case, it sounds like the new RTX 30 series cards won't be supported by rapids until February?

**Comment by kkraus14** [comment]
@gboeing CUDA is broken down into 2 components, the Driver component and the Toolkit component. For RTX 30 series cards, it requires a sufficiently new driver, version `>=455.23` and that was likely what errored during installation. Newer drivers guarantee backwards compatibility with old Toolkits, so you should be able to use the CUDA 11.0 toolkit with a newer driver and everything should just work out of the box for RTX 30 cards.

**Comment by gboeing** [comment]
Thanks @kkraus14. Can confirm this all works.
