### ISSUE TITLE
[QST] `cudf.read_csv` slower than Pandas

### ISSUE THREAD

**Issue by kratika464** [rapidsai/cudf#6965]
**What is your question?**
Why is CUDF getting more time to read CSV compare to pandas?

We read a csv in pandas(pd.read_csv()) and CUDF(cudf.read_csv()) and their time and csv size compare:-
Stock = QQQ
Total no. of rows 1445
Size of file is : 61.1884765625 KB [ time with cudf 2.691218376159668 sec ] [ time with pandas : 0.004311561584472656 sec]

Stock = TOPS
Total no. of rows 4104
Size of file is : 205.8828125 KB [ time with cudf : 1.1979680061340332 sec ] [ time with pandas : 0.006078958511352539 sec]

Why is cudf getting more time than pandas? I am also attaching "QQQ" and "TOPS" CSV.

As an above point I try the same process with large data set (Stock name ="GOOGL" and size= 9071.7451171875 KB and Total no. of rows 208512)
and their output was amazing:-
pandas = 0.113028764 sec
CUDF = 0.03534054 sec
And we clearly see the difference between cudf and pandas.

I also notice when we are reading a CSV with pandas. So their class is <class 'pandas.core.frame.DataFrame'>
and with CUDF their class is <class 'cudf.core.dataframe.DataFrame'>. So, the timing issue is related to this class difference?

Rapids installation:-
conda create -n rapids-0.16 -c rapidsai -c nvidia -c conda-forge
-c defaults rapids=0.16 python=3.7 cudatoolkit=10.1
Cuda:-
version = 10.1
Cudnn:-
version = 7.6
tensorflow-gpu=2.2.0
[stock_market_data-GOOGL.zip](https://github.com/rapidsai/cudf/files/5670434/stock_market_data-GOOGL.zip)
[stock_market_data-QQQ.zip](https://github.com/rapidsai/cudf/files/5670435/stock_market_data-QQQ.zip)
[stock_market_data-TOPS.zip](https://github.com/rapidsai/cudf/files/5670436/stock_market_data-TOPS.zip)

**Comment by kkraus14** [comment]
@kratika464 when you got the longer times for reading the QQQ / TOPS files was it the first cudf API call in the python execution? If so you may have just been timing initializing the CUDA Driver, CUDA Runtime, and creating a CUDA context, all of which have non-trivial overhead. Regardless, if Pandas can handle a CSV in less than 10 milliseconds there's likely not going to be much benefit from using cudf.

**Comment by kkraus14** [comment]
Closing as this is answered.
