### ISSUE TITLE
[DOC] customer needs document for C/C++ APIs 

### ISSUE THREAD

**Issue by dorisnvidia** [rapidsai/cudf#697]
## Report needed documentation
Docs for C/C++ APIs for both cudf and cuml. 

**Report needed documentation**
We showed a customer a list of cudf functions available, and a benchmark test result that demonstrated 20x speed up in read_csv and quantile calculation on GPU using cudf compared to a C++ implementation on CPU on a big dataset. The customer wants to start integrating these functions but need a better document than the header file. 

**Describe the documentation you'd like**
Similar to the current cudf/cuml online HTML docs for python, with some simple code examples and compile/link info. 

**Steps taken to search for needed documentation**
For cudf, include/cudf/functions.h and io_function.h is a good start. For cuml, go to src directory and look for various header files for different methods.

**Comment by harrism** [comment]
@dorisnvidia This PR can serve for cuDF documentation improvement, but you'll need to file separate issues for cuML and other libraries.

**Comment by jrhemstad** [comment]
See https://github.com/rapidsai/cudf/issues/699 and https://github.com/rapidsai/cudf/issues/698

**Comment by harrism** [comment]
To clarify #698 is the issue covering Doxygen configuration. This issue covers completing documentation coverage of libcudf (all APIs documented).

**Comment by jrhemstad** [comment]
@dorisnvidia with https://github.com/rapidsai/cudf/pull/823 merged, you can now do `make doc` to build the Doxygen HTML.

Note that our documentation is still quite sparse (but improving!).

Would love if you could take a look and perhaps let us know of things that you would like, but are missing.

**Comment by harrism** [comment]
Since #823 is merged but the docs are still improving, I'm moving this issue to v0.7 to continue tracking.

**Comment by kkraus14** [comment]
Docs live at https://docs.rapids.ai/api/libcudf/stable/ and are an ongoing effort.
