### ISSUE TITLE
[DOC] Outdated RAPIDS 'merge' advisory on hypervisor setup page

### ISSUE THREAD

**Issue by lmeyerov** [rapidsai/cudf#6971]
## Report incorrect documentation

**Location of incorrect documentation**

https://docs.nvidia.com/grid/latest/grid-vgpu-release-notes-vmware-vsphere/index.html#bug-2642134-rapids-cudf-merge-fails

```
5.25. RAPIDS cuDF merge fails on NVIDIA vGPU
Description
The merge function of the RAPIDS cuDF GPU data frame library fails on NVIDIA vGPU. This function fails because RAPIDS uses the Unified Memory feature of CUDA, which NVIDIA vGPU does not support.

Status
Open

Ref. #
2642134
```

**Describe the problems or issues found in the documentation**

This function might no longer fail

**Steps taken to verify documentation is incorrect**

I asked @kkraus14 

**Suggested fix for documentation**

Remove the advisory

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by vyasr** [comment]
These notices will be removed in the next release of this documentation.
