### ISSUE TITLE
[FEA] Implement integration blogs as benchmark tests

### ISSUE THREAD

**Issue by kevingerman** [rapidsai/cudf#6981]
It is important to track performance and function of integrations that rapids has made into other projects. Especially where we have published blogs describing those features.

Implement benchmark test cases using the Algorithm example that will be skipped if dependencies are not present in the current environment.

External test repos tend to drift as the target project grows and changes.

First candidates:
https://medium.com/rapids-ai/100x-faster-machine-learning-model-ensembling-with-rapids-cuml-and-scikit-learn-meta-estimators-d869788ee6b1

**Comment by davidwendt** [comment]
Do you mean to open this under the cuml repo?
