### ISSUE TITLE
[FEA] Add java bindings for get_json_object

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#6986]
**Is your feature request related to a problem? Please describe.**
Add java bindings for get_json_object once available thru https://github.com/rapidsai/cudf/issues/6985

**Comment by sameerz** [comment]
@razajafri @nvdbaranec I believe you are working on this in https://github.com/rapidsai/cudf/pull/7286

**Comment by sameerz** [comment]
Still in progress, @nvdbaranec is reworking #7286 now that performance benchmarking is done.

**Comment by razajafri** [comment]
closed by #7286
