### ISSUE TITLE
[FEA] Refactor schema generation in parquet writer

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#6989]
The schema generation in parquet writer has gradually improved in the last few PRs but is bound to add complexity due to the addition of input schema (#6862, #6816) and the addition of struct writing support. The schema generation should be moved out of the main `write_chunk()` function and into an intermediate class that bridges between `parquet_column_view` and `cudf::column`. Notably, the list_schema should be constructed by recursion rather than iteration.

**Comment by sameerz** [comment]
@devavret can you confirm this is being worked on in 0.19?  Related: #6816

**Comment by devavret** [comment]
> @devavret can you confirm this is being worked on in 0.19?  Related: #6816 

Yes
