### ISSUE TITLE
[FEA] Enable passing scalars to cudf::datetime::add_calendrical_months

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#6990]
**Is your feature request related to a problem? Please describe.**

[add_calendrical_months](https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/include/cudf/datetime.hpp#L188-L191) expects the right operand to be a column of "months" with one entry for each row in the left operand. It would be useful if a scalar could be passed however and the function would internally construct a full column with that scalar value repeated and perform the sum. 

**Describe the solution you'd like**
Some kind of overload of this function that accepts scalars. 

**Describe alternatives you've considered**
Currently I'm constructing the column in python using make_column_from_scalar and performing the sum after that. 

**Additional context**

**Comment by isVoid** [comment]
@brandon-b-miller do you expect the scalar as a `cudf::scalar` or just a c++ int?

**Comment by brandon-b-miller** [comment]
`cudf::scalar` is fine

**Comment by isVoid** [comment]
What's the behavior of a null scalar? I was thinking of two possibilities:
- Raise if it sees months is null
- Return a column that is all null (this aligns with the column api better, because on that one computes the bitmask AND between input column and months column).
