### ISSUE TITLE
[QST] Very slow & memory intensive performance 

### ISSUE THREAD

**Issue by scazz010** [rapidsai/cudf#6999]
cuDF is taking a crazy amount of time and memory to perform very basic tasks (17 mins & 500 mb of memory) to create a DataFrame with 5 integer elements. As far as I can tell, everything is set up correctly although the graphics card has only recently been released. I'm at a complete loss to know where to look next so any help would be very greatly appreciated! 

---

After setting up an environment using anaconda, I ran the example code from the cuDF github readme: 

```import cudf, io, requests
from io import StringIO

url = "https://github.com/plotly/datasets/raw/master/tips.csv"
content = requests.get(url).content.decode('utf-8')

tips_df = cudf.read_csv(StringIO(content))
tips_df['tip_percentage'] = tips_df['tip'] / tips_df['total_bill'] * 100

# display average tip by dining party size
print(tips_df.groupby('size').tip_percentage.mean())
```

It completes correctly, but taking around 15 minutes and using over 500MB of memory on the graphics card, which doesn't seem at all correct to me. 

I'm using a GeForce RTX 3060 Ti. The truncated output from CUDA deviceQuery is:

```Device 0: "GeForce RTX 3060 Ti"
  CUDA Driver Version / Runtime Version          11.1 / 10.1
  CUDA Capability Major/Minor version number:    8.6
[....]
deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 11.1, CUDA Runtime Version = 10.1, NumDevs = 1
```

I'm using the latest nvidia driver, and the cuda 10.1 tool set:
`NVIDIA-SMI 455.45.01    Driver Version: 455.45.01    CUDA Version: 11.1 `

OS: Ubuntu 20.04
Cuda: V10.1.243

I'm using conda 4.9.2 and I've installed everything locally using: 
```
conda create -n test2
conda activate test2
conda install -c rapidsai -c nvidia -c numba -c conda-forge     cudf=0.14 python=3.7 cudatoolkit=10.1 requests
```

output of running the suggested demo:

```
time python demo-cudf.py 
size
1    21.729202
2    16.571919
3    15.215685
4    14.594901
5    14.149549
6    15.622920
Name: tip_percentage, dtype: float64

real	15m17.744s
user	15m14.769s
sys	0m6.279s
```

I've also tried with a new conda envrionment and the nightly builds:
`conda install -c rapidsai-nightly -c nvidia -c conda-forge -c defaults cudf=0.18 python=3.7 cudatoolkit=10.1`
(which is much, much slower - 50 minutes, 660MB of memory). Memory use (as reported by nvidia-smi) creeps slowly up, so it isn't hanging or waiting for anything (as far as I can tell).

And I've tried with cudf 0.17 as well (similar times/memory to the nightly)

The CUDA install looks to be functioning properly:
```nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
```
I compiled some of the samples including bandwidthTest and deviceQuery. Both outputs look good to me, I can paste them if it's helpful. 

nvidia-smi (whilst the demo code is running):

![smi](https://user-images.githubusercontent.com/28679828/101954660-60619900-3bf4-11eb-87b2-31be30a6cfc6.png)

I also tried running:
```
import cudf
df = cudf.DataFrame()
df['key'] = [0, 1, 2, 3, 4]
df['val'] = [float(i + 10) for i in range(5)]  # insert column
print(df)
```
which completed OK in 17 minutes with v0.14, again using +400MB of memory on the graphics card. 

Thanks again for any insight!
Cheers

**Comment by ayushdg** [comment]
I suspect this is related to #6956. 

The issue shouldn't persist on creating a conda environment with `cudatoolkit=11.0`

```
conda create -n new-env
conda activate new-env
conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.16 python=3.7 cudatoolkit=11.0 requests
```

**Comment by scazz010** [comment]
Perfect, that solves it. 
Thanks so much for the quick response :) Cheers
