### ISSUE TITLE
[BUG] Reading back chunked parquet file fails

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#7011]
**Describe the bug**
Using cudf-0.16, NVTabular uses `cudf.io.parquet.ParquetWriter` to iteratively write out a parquet file to a `BytesIO` object as data is processed, and then later reads back the final "file" into device memory (the intention being to pre-emptively "spill" data to host memory without relying on Dask-CUDA).  This approach fails for cudf>=0.17, unless the inital `ParquetWriter` object is initialized with `index=False`. 

The main problem seems to be in the final `cudf.read_parquet` call, becuase everything works fine if that call is replaced with `pd.read_parquet`.  However, the parquet "file" does include incomplete index information in the pandas metadata.  So, there is also a problem in the write phase.

**Steps/Code to reproduce bug**

```python
import cudf
from cudf.io.parquet import ParquetWriter as pwriter
from io import BytesIO

index = None  #  Only works if index == False

# Create a dataframe
df = cudf.DataFrame({"a":range(4)})

# Create a ParquetWriter object with BytesIO sink
bio = BytesIO()
writer = pwriter(bio, compression=None, index=index)

# Write parquet file in multiple "chunks"
writer.write_table(df.iloc[0:2])
writer.write_table(df.iloc[2:4])
writer.close()

# Read back final file
cudf.io.read_parquet(bio, index=False, use_pandas_metadata=False)
```

<details>
  <summary>Output Traceback</summary>

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-4f5ec159a7eb> in <module>
     18 
     19 # Read back final file
---> 20 cudf.io.read_parquet(bio, index=False, use_pandas_metadata=False)

~/workspace/cudf_18/cudf/python/cudf/cudf/io/parquet.py in read_parquet(filepath_or_buffer, engine, columns, filters, row_groups, skiprows, num_rows, strings_to_categorical, use_pandas_metadata, *args, **kwargs)
    256             num_rows=num_rows,
    257             strings_to_categorical=strings_to_categorical,
--> 258             use_pandas_metadata=use_pandas_metadata,
    259         )
    260     else:

~/workspace/cudf_18/cudf/python/cudf/cudf/_lib/parquet.pyx in cudf._lib.parquet.read_parquet()

~/workspace/cudf_18/cudf/python/cudf/cudf/_lib/parquet.pyx in cudf._lib.parquet.read_parquet()

~/workspace/cudf_18/cudf/python/cudf/cudf/core/dataframe.py in __setattr__(self, key, col)
    607         try:
    608             object.__getattribute__(self, key)
--> 609             object.__setattr__(self, key, col)
    610             return
    611         except AttributeError:

~/workspace/cudf_18/cudf/python/cudf/cudf/core/dataframe.py in index(self, value)
   2521                 f"new values have {new_length} elements"
   2522             )
-> 2523             raise ValueError(msg)
   2524 
   2525         # try to build an index from generic _index

ValueError: Length mismatch: Expected axis has 4 elements, new values have 2 elements
```
</details>

I believe that part of the problem is that the final `BytesIO` object contains "pandas metadata" that specifies a `RangeIndex` that does not match the number of rows in the parquet file.  Within the bytes returned by `bio.getvalue()`, I see:
```
"index_columns": [{"kind": "range", "name": null, "start": 0, "stop": 2, "step": 1}]
```

This suggests that the pandas metadata was not updated when the second chunk was added to the file, and explains the `Length mismatch` error.  However, it is not clear why this metadata would matter if we are spefiying ~both `index=False` **and**~ `use_pandas_metadata=False` in `read_parquet`.  Note that, even with this "bad" metadata, the pandas version of `read_parquet` returns the correct result.

**Expected behavior**

I would expect:

1. The file written by `ParquetWriter` to include complete "pandas metadata"
2. `cudf.read_parquet` to ignore the pandas metadata if it is "bad," and especially if `use_pandas_metadata==False`

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Server"
     DGX_PRETTY_NAME="NVIDIA DGX Server"
     DGX_SWBUILD_DATE="2020-03-04"
     DGX_SWBUILD_VERSION="4.4.0"
     DGX_COMMIT_ID="ee09ebc"
     DGX_PLATFORM="DGX Server for DGX-1"
     DGX_SERIAL_NUMBER="QTFCOU8220024"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
     NAME="Ubuntu"
     VERSION="18.04.4 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.4 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux dgx14 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Dec 14 19:23:47 2020
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:06:00.0 Off |                    0 |
     | N/A   32C    P0    57W / 300W |   3520MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:07:00.0 Off |                    0 |
     | N/A   32C    P0    41W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:0A:00.0 Off |                    0 |
     | N/A   30C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:0B:00.0 Off |                    0 |
     | N/A   29C    P0    42W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:85:00.0 Off |                    0 |
     | N/A   30C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                    0 |
     | N/A   30C    P0    42W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
     | N/A   32C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:8A:00.0 Off |                    0 |
     | N/A   28C    P0    43W / 300W |     12MiB / 32510MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0     26853      C   ...mora/miniconda3/envs/cudf_17/bin/python   877MiB |
     |    0     60788      C   ...mora/miniconda3/envs/cudf_17/bin/python   879MiB |
     |    0     60907      C   ...mora/miniconda3/envs/cudf_17/bin/python   875MiB |
     |    0     60911      C   ...mora/miniconda3/envs/cudf_17/bin/python   875MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              80
     On-line CPU(s) list: 0-79
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             3403.288
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4390.13
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-19,40-59
     NUMA node1 CPU(s):   20-39,60-79
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /datasets/rzamora/miniconda3/envs/cudf_18/bin/cmake
     cmake version 3.19.1
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89
     
     ***Python***
     /datasets/rzamora/miniconda3/envs/cudf_18/bin/python
     Python 3.7.9
     
     ***Environment Variables***
     PATH                            : /home/nfs/rzamora/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/bin:/home/nfs/rzamora/bin:/home/nfs/rzamora/.local/bin:/datasets/rzamora/miniconda3/envs/cudf_18/bin:/datasets/rzamora/miniconda3/condabin:/usr/local/cuda/bin:/opt/bin:/home/nfs/rzamora/.vscode-server/bin/940b5f4bb5fa47866a54529ed759d95d09ee80be/bin:/home/nfs/rzamora/bin:/home/nfs/rzamora/.local/bin:/usr/local/cuda/bin:/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /datasets/rzamora/miniconda3/envs/cudf_18
     PYTHON_PATH                     :
     
     ***conda packages***
     /datasets/rzamora/miniconda3/condabin/conda
     # packages in environment at /datasets/rzamora/miniconda3/envs/cudf_18:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h4abf009_2    conda-forge
     arrow-cpp                 1.0.1           py37h9631afc_16_cuda    conda-forge
     arrow-cpp-proc            2.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-common              0.4.59               h36c2ea0_1    conda-forge
     aws-c-event-stream        0.1.6                had2084c_6    conda-forge
     aws-checksums             0.1.10               h4e93380_0    conda-forge
     aws-sdk-cpp               1.8.70               h57dc084_1    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.3            py37h89c1867_0    conda-forge
     boost-cpp                 1.74.0               h9d3c048_1    conda-forge
     brotli                    1.0.9                he1b5a44_3    conda-forge
     brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_0    conda-forge
     cffi                      1.14.4           py37hc58025e_1    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   3.0.4           py37he5f6b98_1008    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.19.1               h1f3970d_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.3.1            py37h7f0c10b_0    conda-forge
     cudatoolkit               10.2.89              h6bb024c_0    nvidia
     cudf                      0.18.0a0+83.gf965d9acae          pypi_0    pypi
     cudnn                     7.6.5                cuda10.2_0
     cupy                      8.1.0            py37hd81ff16_0    conda-forge
     cython                    0.29.21          py37hb892b2f_1    conda-forge
     cytoolz                   0.11.0           py37h4abf009_1    conda-forge
     dask                      2020.12.0+6.g1d669480          pypi_0    pypi
     dask-cudf                 0.18.0a0+108.ga5515f2152           dev_0    <develop>
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2.31.0.dev0+95.gc6d6fff1          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37he5f6b98_2    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37hcd2ae1e_2    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  1.2.1            py37h5e8e339_0    conda-forge
     fastrlock                 0.5              py37h3340039_1    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h7ca028e_0    conda-forge
     fsspec                    0.8.4                      py_0    conda-forge
     future                    0.18.2           py37h89c1867_2    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.33.2               h1870a98_1    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                5.43.2             pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  1.5.10             pyhd3deb0d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        2.0.0                      py_1    conda-forge
     importlib_metadata        2.0.0                         1    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.3.4            py37h888b3d9_1    conda-forge
     ipython                   7.19.0           py37h888b3d9_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2           py37h89c1867_1    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.7.0            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.11                 hcbb858e_1    conda-forge
     ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
     libblas                   3.9.0                3_openblas    conda-forge
     libcblas                  3.9.0                3_openblas    conda-forge
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
     libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
     libgfortran5              9.3.0               he4bcb1c_17    conda-forge
     libgomp                   9.3.0               h5dbcf3e_17    conda-forge
     liblapack                 3.9.0                3_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.13.0.1             h8b12597_0    conda-forge
     librmm                    0.18.0a201210   cuda10.2_gaf10710_15    rapidsai-nightly
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.1.0                h4f3a223_6    conda-forge
     libutf8proc               2.6.0                h36c2ea0_0    conda-forge
     libuv                     1.40.0               hd18ef5c_0    conda-forge
     libwebp-base              1.1.0                h36c2ea0_3    conda-forge
     llvmlite                  0.35.0           py37h9d7f4d0_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h4abf009_1002    conda-forge
     more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.0            py37hc928c03_2    conda-forge
     nbclient                  0.5.1                      py_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.0.8                      py_0    conda-forge
     nbsphinx                  0.7.1              pyh9f0ad1d_0    conda-forge
     nccl                      2.8.3.1              h1a5f58c_0    conda-forge
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.1.5            py37h89c1867_0    conda-forge
     numba                     0.52.0           py37hdc94413_0    conda-forge
     numpy                     1.19.4           py37h7e9df27_1    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.1            py37h8f50634_2    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1h               h516909a_0    conda-forge
     orc                       1.6.5                hd3605a7_0    conda-forge
     packaging                 20.7               pyhd3deb0d_0    conda-forge
     pandas                    1.1.5            py37hdc94413_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.0.1            py37h63a5d19_0    conda-forge
     pip                       20.3.1             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37he5f6b98_3    conda-forge
     pre-commit                2.9.3            py37h89c1867_0    conda-forge
     pre_commit                2.9.3                hd8ed1ab_0    conda-forge
     prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
     prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
     protobuf                  3.13.0.1         py37h745909e_1    conda-forge
     psutil                    5.7.3            py37hb5d75c8_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.9.0              pyh9f0ad1d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37hbeecfa9_16_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
     pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.3           py37h4abf009_1    conda-forge
     pysocks                   1.7.1            py37he5f6b98_2    conda-forge
     pytest                    6.1.2            py37h89c1867_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     python                    3.7.9           hffdb5ce_0_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.4             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
     pyzmq                     20.0.0           py37h5a562af_1    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2020.11.13       py37h4abf009_0    conda-forge
     requests                  2.25.0             pyhd3deb0d_0    conda-forge
     rhash                     1.3.6             h516909a_1001    conda-forge
     rmm                       0.18.0a201210   cuda_10.2_py37_gaf10710_15    rapidsai-nightly
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37he5f6b98_2    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.3.1              pyhd8ed1ab_1    conda-forge
     sphinx-copybutton         0.3.1              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.14             pyh9f0ad1d_1    conda-forge
     sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     streamz                   0.6.1              pyhd3deb0d_1    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.1            py37h89c1867_1    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     tk                        8.6.10               hed695b0_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h4abf009_0    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     typed-ast                 1.4.1            py37h4abf009_1    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.25.11                    py_0    conda-forge
     virtualenv                20.2.2           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.1             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.3                h58526e2_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Additional context**
cc @albert17

**Comment by devavret** [comment]
As for the writer, the issue is in how the ParquetWriter class handles writing the pandas metadata. It generates the metadata upon the first call to write_table() and therefore the index is fixed as the one used for the first table. This parquet metadata generation could be moved to the close() call because that's when it is written out but I can't guess how to merge the index across all the write_table() calls. I'll take a look at the reader next.

**Comment by rjzamora** [comment]
It may be fair to leave the index information out of the pandas metadata for the `ParquetWriter` class if it is a `RangIndex`.  This type of index is rarely needed by the user - especially if it is an "un-named" `RangeIndex`.

It may also make sense to leave `ParquetWriter` as is, and implement the "fix" in the cudf reader.  It seems that the pandas reader can handle a `RangeIndex` with the wrong length in cases like this.  so, hopefully cudf can as well.

**Comment by devavret** [comment]
> 2. `cudf.read_parquet` to ignore the pandas metadata if it is "bad," and especially if `use_pandas_metadata==False`

It's a simple fix to ignore pandas metadata when `use_pandas_metadata==False`. Try this patch: 
[ignore_pandas_meta.txt](https://github.com/rapidsai/cudf/files/5747520/ignore_pandas_meta.txt)

>  However, it is not clear why this metadata would matter if we are spefiying both `index=False` **and** `use_pandas_metadata=False` in `read_parquet`.

BTW, `index=False` doesn't seem to be an argument in [pandas' `read_parquet`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_parquet.html). It's a writer argument.

**Comment by rjzamora** [comment]
> It's a simple fix to ignore pandas metadata when use_pandas_metadata==False. Try this patch:
ignore_pandas_meta.txt.

Great!  An ideal fix would automatically ignore the pandas metadata if that metadata contains a RangeIndex **and** the size of that index does not agree with the number of rows in the data.  However, I would consider the "full" fix a much lower priority than a functional `use_pandas_metadata=False` argument.

>Fixing this is going to involve moving around the code to generate pandas metadata and passing the final metadata to the state, as detailed in my previous comment.

It is probably rare for a user to actually need a `RangeIndex` to be preserved in practice.  The more common situation is that the `RangeIndex` is just "accidentally" preserved in the metadata.  Therefore, I do not think a write-side fix needs to be prioritized here if it is a pain.

>BTW, index=False doesn't seem to be an argument in pandas' read_parquet. It's a writer argument.

Oops - Good point.  I thought the pyarrow engine was using this kwarg on the backend, but I was wrong.

**Comment by devavret** [comment]
While trying to "Fix" this, and while writing tests, I found that pyarrow doesn't work as expected when specifying `use_pandas_metadata=False`. It restored the non-standard `RangeIndex`.

```python
In [1]: import cudf
In [2]: import pandas as pd
In [3]:     df = pd.DataFrame(
   ...:         {
   ...:             "a": range(6, 9),
   ...:             "b": range(3, 6),
   ...:             "c": range(6, 9),
   ...:             "d": ["abc", "def", "xyz"],
   ...:         }
   ...:     )
   ...: 
In [6]: df.set_index(pd.RangeIndex(stop=9, step=3), inplace=True)
In [7]: df
Out[7]: 
   a  b  c    d
0  6  3  6  abc
3  7  4  7  def
6  8  5  8  xyz
In [8]: df.to_parquet('bleh.parquet')
In [9]: import pyarrow as pa
In [12]: pa.parquet.read_table('bleh.parquet', use_pandas_metadata=False).to_pandas()
Out[12]: 
   a  b  c    d
0  6  3  6  abc
3  7  4  7  def
6  8  5  8  xyz
```

**Comment by galipremsagar** [comment]
`use_pandas_metadata` seems to be respected only if we pass in any value to `columns` parameter. When `columns` is `None`, `use_pandas_metadata` is ignored. 

For example: https://github.com/rapidsai/cudf/pull/2748#issuecomment-529034525 (Verified this on my end)

I think we should raise this in pyarrow community and ask if this is an intended behavior, and if so we the documentation for this parameter will have to mention explicitly that it would be functional only when `columns` is not None.

**Comment by vuule** [comment]
@rjzamora Is this issue still relevant?

**Comment by rjzamora** [comment]
This bug still exists:  If you use `ParquetWriter` to write out a file in multiple chunks with a `RangeIndex`, `cudf.read_parquet` will fail when reading the file back (while pandas will not).

I wouldn't consider it a priority, since NVTabular works around it.  However, it would be great if cudf automatically ignored a problematic `RangeIndex` in the metadata.
