### ISSUE TITLE
[FEA] Update Python bindings for "replace" functions

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#702]
As a workflow developer, I need fillna to be faster. I also need to replace non-null values without writing a custom UDF.

#643 provides a libcudf implementation for replacing null values

1. Extend #643 (if necessary) to support replacing any value,
2. Update cudf/python fillna bindings to use #643 instead of [current JIT'ed impl](https://github.com/rapidsai/cudf/blob/branch-0.6/python/cudf/utils/cudautils.py#L366)
3. Provide cudf.dataframe and cudf.series equivalents of [pandas.DataFrame.replace](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.replace.html) and [pandas.Series.replace](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.replace.html) (#539)

**Comment by shwina** [comment]
For values that are non null, please see #539.

**Comment by randerzander** [comment]
This was fixed by #539
