### ISSUE TITLE
[QST] AWS SageMaker - data wrangling with GPU on a CPU instance

### ISSUE THREAD

**Issue by baboon215** [rapidsai/cudf#7030]
Hi, is it possible to use a CPU instance to 'send' a job to a GPU instance for data wrangling part?

Do I need to use a g4dn instance even for the initial code development that doesn't need GPU? Links to relevant documentation will be helpful. Thank you.

**Comment by kkraus14** [comment]
Hi @baboon215, using a GPU instance for the entire development is definitely the easiest way to get up and running and keep things straightforward.

To dispatch work to a GPU instance, the way I've seen people do this is by starting a dask scheduler / worker on the GPU instance and then connecting to it from the CPU worker. One note in doing this is that you couldn't use the high level Dask APIs like `dask.dataframe` or `dask.array` as the meta calculations would fail from not having a GPU available. You'd be somewhat on your own here, but here are some docs to point you in the right direction:
- dask gpu worker: https://dask-cuda.readthedocs.io/en/latest/worker.html
- dask scheduler: https://docs.dask.org/en/latest/setup/cli.html
- dask client: https://distributed.dask.org/en/latest/api.html#client
