### ISSUE TITLE
[FEA] Add support for `Series.drop`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#7045]
**Is your feature request related to a problem? Please describe.**
We currently have support for `drop` API in `DataFrame` but not in `Series`. I'd like to request support for `drop` in `Series` too for the ability to filter/drop out indices.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.drop.html#pandas.Series.drop

**Comment by isVoid** [comment]
Looking into this issue.
