### ISSUE TITLE
[DOC] Request for help with Fannie Mae Data

### ISSUE THREAD

**Issue by baridhi** [rapidsai/cudf#7047]
Hi,

I'm a PhD student and I came across your data repository (https://rapidsai.github.io/demos/datasets/mortgage-data) while searching for Fannie Mae data. I'm interested to get specific info about bonds issued against some housing MBS. Please see the file attached. I was wondering if you could guide/help me in collecting/understanding the data about the underlying securities mentioned in pages 3 onwards (with CUSIP and pool # etc.). Clearly, this is not an "issue" - but a request for help. Unfortunately, I couldn't find any other channel to float this. Happy to be redirected adequately.
[California_eg_ER846035-ER660692-ER1062467.pdf](https://github.com/rapidsai/cudf/files/5737915/California_eg_ER846035-ER660692-ER1062467.pdf)

**Comment by kkraus14** [comment]
@baridhi the mortgage data you linked to above is an example dataset purely to show the technology capabilities of cuDF. We are by no means financial domain experts and cannot help you in this regard.
