### ISSUE TITLE
Some question about function decode_page_data() from reader_impl.cu[QST]

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7049]
**What is your question?**
I have some question about function `decode_page_data()`  from  https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/src/io/parquet/reader_impl.cu from line 1203 to 1271 
1. my first question is `valids.host_to_device(stream)`and `data.host_to_device(stream)` , why we need to 2 memory copys from host to device about data and valids , from annotation I see variable `data` and `valids` is introduced when column is nested columns,  while I only choose some column that is basic type ,like string and bigint , but this code will execute in any case , i want to know if is right .

2. my second question is that I found when my rowgroup num is 32, the number of select column is 6, and the parqeut file is 256M ,so it will only read about ~5M, and from nsight system , this 2 memory copy `valids.host_to_device(stream)`and `data.host_to_device(stream)` is time consuming  ,its CUDA API is `cudaHostAlloc` and `cudaMemcpyAsync_ptsz` and `cudaFreeHost` like below picture red block, this 2 stage is Inefficiency , 8 bytes per PCIE transfer ，and it transerd `chunk.size()` times total , so how to improve it ?
![image](https://user-images.githubusercontent.com/33319780/103079095-32298380-460e-11eb-9cda-631d5dcba8d2.png)

Code attached
```
// Update chunks with pointers to column data.
  for (size_t c = 0, page_count = 0, str_ofs = 0; c < chunks.size(); c++) {
    input_column_info const &input_col = _input_columns[chunks[c].src_col_index];
    CUDF_EXPECTS(input_col.schema_idx == chunks[c].src_col_schema,
                 "Column/page schema index mismatch");

    if (is_dict_chunk(chunks[c])) {
      chunks[c].str_dict_index = str_dict_index.data().get() + str_ofs;
      str_ofs += pages[page_count].num_input_values;
    }

    size_t max_depth = _metadata->get_output_nesting_depth(chunks[c].src_col_schema);

    // allocate (gpu) an array of pointers to validity data of size : nesting depth
    chunk_nested_valids.emplace_back(hostdevice_vector<uint32_t *>{max_depth});
    hostdevice_vector<uint32_t *> &valids = chunk_nested_valids.back();
    chunks[c].valid_map_base              = valids.device_ptr();

    // allocate (gpu) an array of pointers to out data of size : nesting depth
    chunk_nested_data.emplace_back(hostdevice_vector<void *>{max_depth});
    hostdevice_vector<void *> &data = chunk_nested_data.back();
    chunks[c].column_data_base      = data.device_ptr();

    // fill in the arrays on the host.  there are some important considerations to
    // take into account here for nested columns.  specifically, with structs
    // there is sharing of output buffers between input columns.  consider this schema
    //
    //  required group field_id=1 name {
    //    required binary field_id=2 firstname (String);
    //    required binary field_id=3 middlename (String);
    //    required binary field_id=4 lastname (String);
    // }
    //
    // there are 3 input columns of data here (firstname, middlename, lastname), but
    // only 1 output column (name).  The structure of the output column buffers looks like
    // the schema itself
    //
    // struct      (name)
    //     string  (firstname)
    //     string  (middlename)
    //     string  (lastname)
    //
    // The struct column can contain validity information. the problem is, the decode
    // step for the input columns will all attempt to decode this validity information
    // because each one has it's own copy of the repetition/definition levels. but
    // since this is all happening in parallel it would mean multiple blocks would
    // be stomping all over the same memory randomly.  to work around this, we set
    // things up so that only 1 child of any given nesting level fills in the
    // data (offsets in the case of lists) or validity information for the higher
    // levels of the hierarchy that are shared.  In this case, it would mean we
    // would just choose firstname to be the one that decodes the validity for name.
    //
    // we do this by only handing out the pointers to the first child we come across.
    //
    auto *cols = &_output_columns;
    for (size_t idx = 0; idx < max_depth; idx++) {
      auto &out_buf = (*cols)[input_col.nesting[idx]];
      cols          = &out_buf.children;

      int owning_schema = out_buf.user_data & PARQUET_COLUMN_BUFFER_SCHEMA_MASK;
      if (owning_schema == 0 || owning_schema == input_col.schema_idx) {
        valids[idx] = out_buf.null_mask();
        data[idx]   = out_buf.data();
        out_buf.user_data |=
          static_cast<uint32_t>(input_col.schema_idx) & PARQUET_COLUMN_BUFFER_SCHEMA_MASK;
      } else {
        valids[idx] = nullptr;
        data[idx]   = nullptr;
      }
    }

    // copy to the gpu
    valids.host_to_device(stream);
    data.host_to_device(stream);

    // column_data_base will always point to leaf data, even for nested types.
    page_count += chunks[c].max_num_pages;
  }
```

**Comment by kkraus14** [comment]
cc @devavret @vuule @nvdbaranec

**Comment by devavret** [comment]
> it transerd chunk.size() times total

This part seems like it will be fixed by #7005

I'll check the rest and reply in a while.

**Comment by chenrui17** [comment]
@devavret  before gpuinflate , we should transfer data to GPU from host pinned memory ,but from nsight system, i can see source memory info is  pageable not pinned kind, is it normal ? how to solve it ?

![image](https://user-images.githubusercontent.com/33319780/103214461-6c1ac280-494b-11eb-9bd2-597b68e15ef4.png)

code is in function `decompress_page_data `
```
CUDA_TRY(cudaMemcpyAsync(inflate_in.device_ptr(start_pos),
                               inflate_in.host_ptr(start_pos),
                               sizeof(decltype(inflate_in)::value_type) * (argc - start_pos),
                               cudaMemcpyHostToDevice,
                               stream.value()));
CUDA_TRY(cudaMemcpyAsync(inflate_out.device_ptr(start_pos),
                               inflate_out.host_ptr(start_pos),
                               sizeof(decltype(inflate_out)::value_type) * (argc - start_pos),
                               cudaMemcpyHostToDevice,
                               stream.value()));
```

**Comment by devavret** [comment]
@chenrui17 The transfers you mentioned between line 967 and 976 appear to be taking place once per codec. Therefore there should be maximum of 3 transfers from pinned memory of `inflate_(in/out)`. The nsys timeline shows multiple transfers. They're probably coming from something else. May I suggest re-running nsight but with backtraces on.

**Comment by chenrui17** [comment]
> @chenrui17 The transfers you mentioned between line 967 and 976 appear to be taking place once per codec. Therefore there should be maximum of 3 transfers from pinned memory of `inflate_(in/out)`. The nsys timeline shows multiple transfers. They're probably coming from something else. May I suggest re-running nsight but with backtraces on.

Thank you for your correction , i made a mistake ! 
The data transfer code what i want to say should be in `read_column_chunks `  https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/src/io/parquet/reader_impl.cu line 820 to line 860

**Comment by chenrui17** [comment]
the problem of that  source memory kind is pageable is sloved by myslef , because I set the spark.memory.offHeap.size 10g , while thinks of my T4 gpu has 16G memory ,so I set the spark.rapids.memory.pinnedPool.size=16G , it's bigger that offHeap size
