### ISSUE TITLE
[FEA] Support for boolean data-type in cudf/python

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#705]
Support `bool` Series data type

Related to #667. I'm creating this as a separate issue to let cudf/cpp and cudf/python work proceed separately. @kkraus14 feel free to close if you prefer them in a single issue/pr

**Comment by beckernick** [comment]
@randerzander it looks to me like this has been completed. We have a mapping of `np.bool_:      GDF_BOOL8` in the `cudf_cpp` Cython file, and can create Boolean columns in the Python layer. Closing this for now.
