### ISSUE TITLE
[BUG] OSError: Could not load shared object file: libllvmlite.so

### ISSUE THREAD

**Issue by debparth** [rapidsai/cudf#7052]
**Describe the bug**
This error pops up when i try to import cudf in google colab
![image](https://user-images.githubusercontent.com/53347017/103276132-959f1280-497a-11eb-89db-7204fae86f58.png)

**Steps/Code to reproduce bug**
1) Copied the code from the rapids-colab

`# Install RAPIDS`
`!git clone https://github.com/rapidsai/rapidsai-csp-utils.git`
`!bash rapidsai-csp-utils/colab/rapids-colab.sh stable`
`import sys, os`
`dist_package_index = sys.path.index('/usr/local/lib/python3.6/dist-packages')`
`sys.path = sys.path[:dist_package_index] + ['/usr/local/lib/python3.6/site-packages'] + sys.path[dist_package_index:]`
`sys.path`
`exec(open('rapidsai-csp-utils/colab/update_modules.py').read(), globals())`

2) Installing conda & rapidsai packages
3) While trying to `import cudf`

**Expected behavior**
It must have been able to run without getting this error & give me percentage mean of the dataframe.

**Environment overview (please complete the following information)**
 - Environment location: Google
 - Method of cuDF install: Conda

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
- It gives me an error in colab when running `cudf/print_env.sh`

**Comment by lucy2329** [comment]
Same issue man!

**Comment by Weidong725** [comment]
You can look at this problem. It can get you out of trouble for a while
https://github.com/rapidsai/rapidsai-csp-utils/issues/36

**Comment by debparth** [comment]
Hi @Weidong725 , Thanks it worked for me.
