### ISSUE TITLE
[FEA] Automate license year update

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#7073]
**Is your feature request related to a problem? Please describe.**
All source files has Copyright year and they are updated manually in each pull request.
Define the rules for updating the Copyright year.

**Describe the solution you'd like**
This could be automated via GitHub actions
or a pre-commit hook could be added.

Few options are
https://github.com/NitorCreations/license-maintainer
https://github.com/marketplace/actions/update-license-copyright-year-s
https://github.com/marketplace/actions/license-checker
https://github.com/marketplace/actions/license-year-updater

**Comment by harrism** [comment]
Or it could be an additional style check.

**Comment by vyasr** [comment]
This was resolved in #10253 and #10290
