### ISSUE TITLE
[FEA] Support union for nested types

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7089]
**Is your feature request related to a problem? Please describe.**
union only works for non-nested types right now.  It would be nice to support it for nested types as well. This is mostly blocked on scalar support for nested types.  When we do get around to implementing it we should be sure to test with SPARK-32376 where a struct can have null columns added to it to make the two sides match.  I am not sure if it will require any code changes on our part though.

**Comment by harrism** [comment]
I wasn't aware that libcudf has a union API. What is it called and what header is it in?

**Comment by revans2** [comment]
Sorry filed this in the wrong place
