### ISSUE TITLE
[DOC] Cudf python API lookup has long latency

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#7098]
**Describe the problems or issues found in the documentation**
Currently, when I need to lookup a API signature from the documentation, the documentation site would first serve the page that contains every function API of `cudf`, then jump to the right section that has the function signature. This introduces unnecessary latency for a single function lookup. 

**Suggested fix for documentation**
A few different solutions may be implemented:
1. Serve every function into its own page. Like how pandas does it.
2. Create group/modules hierarchies, on the atomic level, serve module/class as a single page, jump to the API on that page. Like how libcudf/doxygen does it.

Other solutions also welcomed.

**Comment by galipremsagar** [comment]
So the root cause of this problem is that our entire documentation is written into a single html file(api.html) - we should probably find a way to chunk these out into separate html files

**Comment by isVoid** [comment]
This is being worked on by @galipremsagar in v0.20.
