### ISSUE TITLE
[BUG] CMAKE_BUILD_TYPE doesn't propagate to Arrow build

### ISSUE THREAD

**Issue by trxcllnt** [rapidsai/cudf#710]
It seems like the `CMAKE_BUILD_TYPE` option in the cudf source build doesn't propagate to the Arrow-cpp build. After cmake checks out the Arrow repo, the Arrow build reports:
```
Configured for DEBUG build (set with cmake -DCMAKE_BUILD_TYPE={release,debug,...})
-- Build Type: DEBUG
```

I'm running this line in a docker container to check out and build the cudf source:
```sh
# Clone cudf source repo, build, and install
RUN git clone --recurse-submodules -b ${CUDF_BRANCH} ${CUDF_REPO} ${CUDF_HOME} \
 && cd ${CUDF_HOME}/cpp && mkdir build && cd build \
 && cmake \
    -DBUILD_TESTS=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=${CUDF_INSTALL_PATH} \
    -DCMAKE_C_COMPILER=/usr/bin/gcc-${GCC_VERSION} \
    -DCMAKE_CXX_COMPILER=/usr/bin/g++-${CXX_VERSION} \
    .. \
 && make -j \
 && make install \
 && make python_cffi \
 && make install_python
```

**Expected behavior**
The `-DCMAKE_BUILD_TYPE` option should probably propagate down to the Arrow build as well.

 - Environment location: Docker
 - Method of cuDF install: from source
 

**Additional context**
You can see the entire dockerfile in this gist: https://gist.github.com/trxcllnt/fbc003ace726391795eb96c0c313f4d9#file-blazingsql-dockerfile-L111

Thanks!

**Comment by beckernick** [comment]
@trxcllnt is this still relevant?

**Comment by trxcllnt** [comment]
@beckernick I think this has been fixed.
