### ISSUE TITLE
XGBoost GPU error on WSL2 (using tree_method = 'gpu_hist')

### ISSUE THREAD

**Issue by BenWynne-Morris** [rapidsai/cudf#7101]
I've run into an error trying to get XGBoost GPU working on WSL2, which also resulted in a black screen for the second monitor.

```
Attempting to train XGBoost with tree method of gpu_hist causes the following error:
[23:10:50] task [xgboost.dask]:tcp://127.0.0.1:45075 got new rank 0
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  for_each: failed to synchronize: cudaErrorUnknown: unknown error
```

**Environment**
- Microsoft Windows 10 Pro Insider Preview
- Version 2004 (Build 21277)
- Windows Subsystem Linux 2 - Ubuntu 20.04 
- NVIDA Driver 465.21 / CUDA 11.0
-  xgboost 1.3.0dev.rapidsai0.17  
-  cuda11.0py37_0

Here is how I installed my Rapids environment:
```
$ conda create -n rapids-0.17 python=3.7
$ conda activate rapids-0.17
$ conda install -c rapidsai -c nvidia -c conda-forge \
   -c defaults rapids-blazing=0.17 python=3.7 cudatoolkit=11.0
```

**Performance**
WSL2 is generally working quite well since installation a couple of weeks ago:
- I've been able to train some machine learning algorithms (e.g. kmeans) on WSL2 with Python + Dask + Cuda
- I've also been able to train XGBoost on WSL2 with Python + Pandas (i.e. CPU); but so far not on the GPU (with or without Dask)

**Code**
Code example was taken from https://medium.com/rapids-ai/a-new-official-dask-api-for-xgboost-e8b10f3d1eb7
Example data source: `$ wget https://archive.ics.uci.edu/ml/machine-learning-databases/00280/HIGGS.csv.gz`

The key code bit below that seems to cause the crash is 'tree_method': 'gpu_hist'

Here is the code I ran:
```
from dask.distributed import Client
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
client = Client(cluster)
import xgboost as xgb
import dask_cudf
fname = './data/HIGGS.csv'
colnames = ["label"] + ["feature-%02d" % i for i in range(1,29)]
dask_df = dask_cudf.read_csv(fname, header=None, names=colnames)
X = dask_df[dask_df.columns.difference(['label'])]
y = dask_df['label']
dtrain = xgb.dask.DaskDMatrix(client, X, y)
params = {'tree_method': 'gpu_hist'}
output = xgb.dask.train(client, params, dtrain, num_boost_round=100)
```

First time poster on GitHub so please be gentle with me..

**Comment by kkraus14** [comment]
Hey @BenWynne-Morris, I would suggest raising this as an issue on the xgboost repository instead of cudf: https://github.com/dmlc/xgboost

**Comment by BenWynne-Morris** [comment]
Thanks @kkraus14 - I thought this might be a CUDA driver issue (or perhaps WSL2 related).  

Have re-posted here:
https://github.com/dmlc/xgboost/issues/6585
