### ISSUE TITLE
[FEA] Target Encoding 

### ISSUE THREAD

**Issue by subhamiitk** [rapidsai/cudf#7104]
**Is your feature request related to a problem? Please describe.**
 I wish I could use dask_cudf to do Target Encoding similar to [TargetEncoding in cumL](https://github.com/rapidsai/cuml/blob/5ff2794/python/cuml/preprocessing/TargetEncoder.py#L24)

**Describe the solution you'd like**
Target Encoding fit and fit_transform should be made available with smoothing and k_fold parameters.

**Describe alternatives you've considered**

1. As the dataset was more than 100mn, i had to do mean target encoding in BigQuery itself. But I couldn't perform K-fold Target Encoding there.  
2. For toy dataset of 1mn records, I also tried [category_encoders.target_encoder](https://contrib.scikit-learn.org/category_encoders/targetencoder.html) as cuml Target Encoding is not working as raised in this [issue](https://github.com/rapidsai/cuml/issues/3355)
**Additional context**
Reference:
https://github.com/rapidsai/cuml/blob/5ff2794/python/cuml/preprocessing/TargetEncoder.py#L24

**Comment by kkraus14** [comment]
If target encoding is implemented in cuML, is there a reason you'd want it in cuDF?

**Comment by beckernick** [comment]
As target encoding was implemented in cuML and there has been no further discussion here, I'm going to close this issue. 

Please feel free to re-open, but I recommend we move discussion for a Dask version to the cuML issue tracker.
