### ISSUE TITLE
[BUG] really slow GPU parsing of parquet file

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7114]
**Describe the bug**
I have a parquet file that is very slow to unsnap on the GPU, but is very fast on the CPU.

**Steps/Code to reproduce bug**
I am happy to share the file with whom ever, it is a 326 MB parquet file based off of some data from a TPC-DS run for the `store sales` table with decimal data instead of doubles for money related columns.

```
Schema:
message spark_schema {
  optional int32 ss_sold_date_sk;
  optional int32 ss_item_sk;
  optional int64 ss_ticket_number;
  optional int32 ss_quantity;
  optional int32 ss_net_paid (DECIMAL(7,2));
  optional int32 ss_net_profit (DECIMAL(7,2));
}
```

For me all I have to do is to read the data in and it takes about 1.8 seconds to do it, where as on the CPU through Spark it typically takes about 300 ms single threaded (including some computation at the end/spark overhead).

**Expected behavior**
When I use nsys profile it shows that nearly all of the time 98% is being taken by the unsnap kernel.
I realize that there are not that many columns (6) and that there are only 9 row groups, but there are about 701 data/dictionary pages so I would expect to be able to unsnap the pages all in parallel and see some kind of a speed up, but instead it is much much slower. I also didn't see much if any data size skew between the pages (at least according to the parquet CLI tool).

**Environment overview (please complete the following information)**
 Bare metal desktop with a V100 16 GB GPU in it (cuda 10.1)

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 11ebc3e089b3da786d6d6cf71596d8d2404a6d04 (HEAD -> branch-0.18, origin/branch-0.18)
     Author: Robert (Bobby) Evans <bobby@apache.org>
     Date:   Mon Jan 11 13:22:25 2021 -0600
     
     Adds in JNI support for creating an list column from existing columns(#7112)
     
     Adds in java support to be able to create a list column from other existing columns.
     
     Authors:
     - Robert (Bobby) Evans <bobby@apache.org>
     
     Approvers:
     - Jason Lowe (@jlowe)
     
     URL: https://github.com/rapidsai/cudf/pull/7112
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux roberte-desktop 4.15.0-130-generic #134-Ubuntu SMP Tue Jan 5 20:46:26 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Mon Jan 11 16:16:06 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  GeForce GT 710      Off  | 00000000:17:00.0 N/A |                  N/A |
     | 50%   46C    P8    N/A /  N/A |    689MiB /  1993MiB |     N/A      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-PCIE...  Off  | 00000000:65:00.0 Off |                    0 |
     | N/A   42C    P0    27W / 250W |      0MiB / 16160MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz
     Stepping:            4
     CPU MHz:             1200.021
     CPU max MHz:         4000.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6999.82
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            8448K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req md_clear flush_l1d
     
     ***CMake***
     /home/roberte/miniconda3/envs/cudf_dev/bin/cmake
     cmake version 3.19.1
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-10.1/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243
     
     ***Python***
     /home/roberte/miniconda3/envs/cudf_dev/bin/python
     Python 3.7.6
     
     ***Environment Variables***
     PATH                            : /home/roberte/miniconda3/envs/cudf_dev/bin:/home/roberte/miniconda3/condabin:/usr/local/cuda-10.1/bin:/home/roberte/.local/bin:/home/roberte/bin:/usr/local/cuda-10.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.1/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/roberte/miniconda3/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/roberte/miniconda3/condabin/conda
     # packages in environment at /home/roberte/miniconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                        main
     abseil-cpp                20200225.2           he1b5a44_0    conda-forge
     alabaster                 0.7.12                   py37_0
     apipkg                    1.5                      pypi_0    pypi
     appdirs                   1.4.4                      py_0
     argon2-cffi               20.1.0           py37h7b6447c_1
     arrow-cpp                 1.0.1           py37hf00d4d6_5_cuda    conda-forge
     arrow-cpp-proc            2.0.0                      cuda    conda-forge
     async_generator           1.10             py37h28b3542_0
     attrs                     20.3.0             pyhd3eb1b0_0
     aws-sdk-cpp               1.7.164              hc831370_1    conda-forge
     babel                     2.8.0                      py_0
     backcall                  0.2.0                      py_0
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.2.1                      py_0
     bokeh                     2.2.3                    py37_0
     boost-cpp                 1.72.0               h8e57a91_0    conda-forge
     brotli                    1.0.9                he6710b0_2
     brotlipy                  0.7.0           py37h7b6447c_1000
     bzip2                     1.0.8                h7b6447c_0
     c-ares                    1.16.1               h7b6447c_0
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_0    conda-forge
     cffi                      1.14.4           py37h11fe52a_0    conda-forge
     cfgv                      2.0.1                      py_0    conda-forge
     chardet                   3.0.4                 py37_1003
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2                      py_0
     cloudpickle               1.4.1                    pypi_0    pypi
     cmake                     3.19.1               h1f3970d_0    conda-forge
     cmake-format              0.6.11             pyh9f0ad1d_0    conda-forge
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0
     configparser              5.0.0                    pypi_0    pypi
     cryptography              3.1.1            py37h1ba5d50_0
     cudatoolkit               10.1.243             h6bb024c_0    nvidia
     cudnn                     7.6.0                cuda10.1_0    nvidia
     cupy                      8.1.0            py37h66f4e5a_0    conda-forge
     curl                      7.71.1               hbc83047_1
     cython                    0.29.21          py37hb892b2f_1    conda-forge
     cytoolz                   0.11.0           py37h7b6447c_0
     dask                      2020.12.0+8.gda7b56d7          pypi_0    pypi
     dask-core                 2.25.0                     py_0
     databricks-cli            0.10.0                   pypi_0    pypi
     decorator                 4.4.2                      py_0
     defusedxml                0.6.0                      py_0
     distlib                   0.3.1                    py37_0
     distributed               2.19.0+5.gd4c8bdb0          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16                     py37_1
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37he1b5a44_0    conda-forge
     entrypoints               0.3                      py37_0
     execnet                   1.7.1                      py_0    conda-forge
     expat                     2.2.10               he6710b0_2
     fastavro                  1.2.0            py37h4abf009_0    conda-forge
     fastrlock                 0.5              py37he6710b0_0
     filelock                  3.0.12                     py_0
     findspark                 1.4.2                    pypi_0    pypi
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h5ab3b9f_0
     fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
     future                    0.18.2                   py37_1
     gflags                    2.2.2                he6710b0_0
     glog                      0.4.0                he6710b0_0
     gmp                       6.1.2                h6c8ec71_1
     grpc-cpp                  1.30.2               heedbac9_0    conda-forge
     heapdict                  1.0.1                      py_0
     hypothesis                5.43.3             pyhd8ed1ab_0    conda-forge
     icu                       64.2                 he1b5a44_1    conda-forge
     identify                  1.4.11                     py_0    conda-forge
     idna                      2.10                       py_0
     imagesize                 1.2.0                      py_0
     importlib-metadata        2.0.0                      py_1
     importlib_metadata        2.0.0                         1
     iniconfig                 1.1.1                      py_0
     ipykernel                 5.3.4            py37h5ca1d4c_0
     ipython                   7.19.0           py37h888b3d9_0    conda-forge
     ipython_genutils          0.2.0                    py37_0
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2                   py37_0
     jinja2                    2.11.2                     py_0
     jpeg                      9b                   h024ee3a_2
     jsonschema                3.2.0                      py_2
     jupyter_client            6.1.7                      py_0
     jupyter_core              4.6.3                    py37_0
     jupyterlab_pygments       0.1.2                      py_0
     krb5                      1.18.2               h173b8e3_0
     lcms2                     2.11                 h396b838_0
     ld_impl_linux-64          2.33.1               h53a641e_7
     libblas                   3.8.0               14_openblas    conda-forge
     libcblas                  3.8.0               14_openblas    conda-forge
     libcurl                   7.71.1               h20c2e04_1
     libedit                   3.1.20191231         h14c3975_1
     libevent                  2.1.10               h72c5cf5_0    conda-forge
     libffi                    3.2.1             hf484d3e_1007
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     liblapack                 3.8.0               14_openblas    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libopenblas               0.3.7                h5ec1e0e_6    conda-forge
     libpng                    1.6.37               hbc83047_0
     libprotobuf               3.12.4               hd408876_0
     librmm                    0.18.0a201211   cuda10.1_g21e5650_16    rapidsai-nightly
     libsodium                 1.0.18               h7b6447c_0
     libssh2                   1.9.0                h1ba5d50_1
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                h2733197_1
     libutf8proc               2.5.0                h14c3975_2
     libuv                     1.40.0               h7b6447c_0
     llvmlite                  0.32.1           py37hd408876_0
     locket                    0.2.0                    py37_1
     lz4-c                     1.9.2                heb0550a_3
     markdown                  3.3.2                    py37_0
     markupsafe                1.1.1            py37h14c3975_1
     mccabe                    0.6.1                    py37_1
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h14c3975_1001
     more-itertools            8.5.0                      py_0
     msgpack-python            1.0.0            py37hfd86e86_1
     nbclient                  0.5.1                      py_0
     nbconvert                 6.0.7                    py37_0
     nbformat                  5.0.8                      py_0
     nbsphinx                  0.7.1              pyh9f0ad1d_0    conda-forge
     nccl                      2.8.3.1              h8b44402_0    conda-forge
     ncurses                   6.2                  he6710b0_1
     nest-asyncio              1.4.1                      py_0
     nodeenv                   1.3.5                      py_0    conda-forge
     notebook                  6.1.5            py37h89c1867_0    conda-forge
     numba                     0.49.1           py37h0da4684_0    conda-forge
     numpy                     1.17.5           py37h95a1406_0    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.1            py37h8f50634_2    conda-forge
     olefile                   0.46                     py37_0
     openssl                   1.1.1h               h516909a_0    conda-forge
     packaging                 20.8               pyhd3deb0d_0    conda-forge
     pandas                    1.1.4            py37h10a2094_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                    py37_1
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.0                      py_0
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.7.0                      py_0
     pexpect                   4.8.0                    py37_1
     pickleshare               0.7.5                 py37_1001
     pillow                    8.0.1            py37he98fc37_0
     pip                       20.3.3             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1                   py37_0
     pre-commit                2.1.1                    py37_0    conda-forge
     pre_commit                2.1.1                         0    conda-forge
     prometheus_client         0.8.0                      py_0
     prompt-toolkit            3.0.8                      py_0
     protobuf                  3.12.4           py37h3340039_0    conda-forge
     psutil                    5.7.2            py37h7b6447c_0
     ptyprocess                0.6.0                    py37_0
     py                        1.9.0                      py_0
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     py4j                      0.10.8.1                 py37_0
     pyarrow                   1.0.1           py37h72578d1_5_cuda    conda-forge
     pycodestyle               2.6.0                      py_0
     pycparser                 2.20                       py_2
     pyflakes                  2.2.0                      py_0
     pygments                  2.7.2              pyhd3eb1b0_0
     pyopenssl                 19.1.0                     py_1
     pyparsing                 2.4.7                      py_0
     pyrsistent                0.17.3           py37h7b6447c_0
     pysocks                   1.7.1                    py37_1
     pytest                    6.2.1            py37h89c1867_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     pytest-forked             1.3.0                    pypi_0    pypi
     pytest-xdist              2.1.0                    pypi_0    pypi
     python                    3.7.6           cpython_h8356626_6    conda-forge
     python-dateutil           2.8.1                      py_0
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.1                     py_0
     pyyaml                    5.3.1            py37h7b6447c_1
     pyzmq                     19.0.2           py37he6710b0_1
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.08.01           he1b5a44_0    conda-forge
     readline                  8.0                  h7b6447c_0
     recommonmark              0.6.0                      py_0    conda-forge
     regex                     2020.10.15       py37h7b6447c_0
     requests                  2.24.0                     py_0
     rhash                     1.4.0                h1ba5d50_0
     rmm                       0.18.0a201217   cuda_10.1_py37_gefd4c08_18    rapidsai-nightly
     send2trash                1.5.0                    py37_0
     setuptools                50.3.1           py37h06a4308_1
     six                       1.15.0                     py_0
     snappy                    1.1.8                he6710b0_0
     snowballstemmer           2.0.0                      py_0
     sortedcontainers          2.2.2                      py_0
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.3.1              pyhd8ed1ab_1    conda-forge
     sphinx-copybutton         0.3.1              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.0              pyh9f0ad1d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0
     sphinxcontrib-devhelp     1.0.2                      py_0
     sphinxcontrib-htmlhelp    1.0.3                      py_0
     sphinxcontrib-jsmath      1.0.1                      py_0
     sphinxcontrib-qthelp      1.0.3                      py_0
     sphinxcontrib-serializinghtml 1.1.4                      py_0
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.31.1               h7b6447c_0
     sre-yield                 1.2                      pypi_0    pypi
     streamz                   0.6.0                    pypi_0    pypi
     tabulate                  0.8.7                    pypi_0    pypi
     tblib                     1.7.0                      py_0
     terminado                 0.9.1                    py37_0
     testpath                  0.4.4                      py_0
     thrift-cpp                0.13.0               h62aa4f2_2    conda-forge
     tk                        8.6.10               hbc83047_0
     toml                      0.10.1                     py_0
     toolz                     0.11.1                     py_0
     tornado                   6.0.4            py37h7b6447c_1
     traitlets                 5.0.5                      py_0
     typed-ast                 1.4.1            py37h7b6447c_0
     typing_extensions         3.7.4.3                    py_0
     urllib3                   1.25.11                    py_0
     virtualenv                20.0.35                  py37_0
     wcwidth                   0.2.5                      py_0
     webencodings              0.5.1                    py37_1
     wheel                     0.35.1                     py_0
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h7b6447c_0
     zeromq                    4.3.3                he6710b0_3
     zict                      2.0.0                      py_0
     zipp                      3.4.0              pyhd3eb1b0_0
     zlib                      1.2.11               h7b6447c_3
     zstd                      1.4.5                h9ceee32_0
     
</pre></details>

**Additional context**
I am running this on 11ebc3e089b3da786d6d6cf71596d8d2404a6d04

I tried to do a bit of profiling with nsight compute, but I am not an expert on any of this so I couldn't come up with much of what might be wrong/off about this.

**Comment by jlowe** [comment]
This issue is still valid.

**Comment by vuule** [comment]
@revans2 what is the driver version you are/were using?

**Comment by revans2** [comment]
Sorry I was out on vacation for the past week.

```$ nvidia-smi 
Tue Apr 13 15:52:46 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GT 710      On   | 00000000:17:00.0 N/A |                  N/A |
| 50%   48C    P0    N/A /  N/A |    711MiB /  1993MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-PCIE...  On   | 00000000:65:00.0 Off |                    0 |
| N/A   44C    P0    27W / 250W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
```

**Comment by revans2** [comment]
But I am running with the 10.1 runtime. I will upgrade to 11.2 soon-ish and see if it fixes the issue.

**Comment by elstehle** [comment]
Fixed by https://github.com/rapidsai/cudf/pull/7975 and https://github.com/rapidsai/cudf/pull/7962
