### ISSUE TITLE
[FEA] Fixed-point precision support for SUM in a window operation

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#7117]
**Is your feature request related to a problem? Please describe.**
We currently don't have any support for fixed-point precision in a window operation for sum

**Describe the solution you'd like**
Provide support for fixed-point precision for `sum` in a window operation

**Additional context**
This builds on #3556

**Comment by revans2** [comment]
@razajafri could you me a little more clear about exactly what you want from sum? Do you want to operator to change the scale as it does the sum or will that be done ahead of time and all this needs to do is to treat the sum as if it were a long/int and then make sure the types is set properly at the end? Is there anything special that we need to worry about in the case of an overflow?

**Comment by razajafri** [comment]
@revans2 and I spoke offline to chalk this out. 

> Do you want to operator to change the scale as it does the sum or will that be done ahead of time and all this needs to do is to treat the sum as if it were a long/int and then make sure the types is set properly at the end?

Precision is what we mean above and not scale. In cudf math is done on the underlying data type, either `int32` or `int64` and then converted back to the respective fixed-point type. More on this after I look into what Spark expects in case of an overflow

> Is there anything special that we need to worry about in the case of an overflow?

I need to dig a little deeper in Spark to know how we expect cudf to handle the overflow. We are currently handling all the Decimals as Decimal64. There is bound to be overflow at some point and I will update this ticket when I have an answer to this.
