### ISSUE TITLE
[BUG] Slow kernel_agent (make_string_columns) calls when parsing a Parquet File

### ISSUE THREAD

**Issue by tgravescs** [rapidsai/cudf#7124]
**Describe the bug**
I have a parquet file that during load shows very high times in a _kernel_agent kernel.  nsys profile seems to indicate this comes from a make_string_column call. The times are in the 25+ms just for that kernel to run. the unsnap kernel is like 48ms, gpuDecodePageData is only 7ms and GpuBuildStringDictionaryIndex is also only 6.4ms.
The time for the make_string_column seems large here.

**Steps/Code to reproduce bug**

I can provide a file to reproduce this but can't share publicly. I can also provide an nsys trace if needed.

Using the cudf java API from Scala I can read the parquet file like below and get an nsys trace of it:
```
val arg = "dump608561145.parquet"
import ai.rapids.cudf.Table
import java.io.File
for (i <- 0 to 3) {
  val start = System.currentTimeMillis()
  val t = Table.readParquet(new File(arg))
  val end = System.currentTimeMillis()
  println("TABLE " + i + " (" + (end - start) + " ms) "+ t)
}
```

schema of data:
 ```
|-- timestamp: timestamp (nullable = true)
 |-- Id: string (nullable = true)
 |-- name: string (nullable = true)
```

**Expected behavior**
I was investigating parquet read performance and when I use I use nsys profile it seems like the time by this kernel is very high. I would have expected it to be less.

**Environment overview (please complete the following information)**
bare metal running on a T4 box with ubuntu

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     Not inside a git repository

     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
     NAME="Ubuntu"
     VERSION="18.04.3 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.3 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux spark-egx-05 4.15.0-121-generic #123-Ubuntu SMP Mon Oct 5 16:16:40 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Tue Jan 12 17:19:11 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla T4            On   | 00000000:3B:00.0 Off |                    0 |
     | N/A   38C    P8    15W /  70W |      0MiB / 15079MiB |      0%   E. Process |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla T4            On   | 00000000:5E:00.0 Off |                    0 |
     | N/A   42C    P8    15W /  70W |      0MiB / 15079MiB |      0%   E. Process |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla T4            On   | 00000000:AF:00.0 Off |                    0 |
     | N/A   33C    P8    10W /  70W |      0MiB / 15079MiB |      0%   E. Process |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla T4            On   | 00000000:D8:00.0 Off |                    0 |
     | N/A   33C    P8    10W /  70W |      0MiB / 15079MiB |      0%   E. Process |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
    ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              64
     On-line CPU(s) list: 0-63
     Thread(s) per core:  2
     Core(s) per socket:  16
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
     Stepping:            4
     CPU MHz:             1998.754
     BogoMIPS:            4200.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            22528K
     NUMA node0 CPU(s):   0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,62
     NUMA node1 CPU(s):   1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31,33,35,37,39,41,43,45,47,49,51,53,55,57,59,61,63
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear flush_l1d

     ***CMake***

     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***

     ***Python***
     /usr/bin/python
     Python 2.7.17

**Additional context**

**Comment by devavret** [comment]
Are the strings large? If so, this will be fixed by #7576

**Comment by devavret** [comment]
@tgravescs Can you check if the issue persists with the latest code?

**Comment by tgravescs** [comment]
sorry, I missed your questions.  I had to delete the original file that reproduced this due to it having to be deleted after so many days, we can close this for now and I'll reopen if we see the issue again.
