### ISSUE TITLE
[FEA] Support ORC read/write with Fixed-point data

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#7126]
**Is your feature request related to a problem? Please describe.**
Need Decimal support for ORC read/write 

**Additional context**
Issue #6474 was closed prematurely it seems because there is no Decimal type support for ORC 

- [x] Reader support
- [x] Writer support

**Comment by sameerz** [comment]
This is still needed; just got a customer request for this.

**Comment by sameerz** [comment]
Still needed.

**Comment by vuule** [comment]
Closed with #8198
