### ISSUE TITLE
[BUG] Unable to retrieve datetime values using JSON reader dtype parameter

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#7128]
**Describe the bug**
When trying to read datetime values from a json file by specifying a `dtype` mapping is leading to data corruption.

**Steps/Code to reproduce bug**
```python
In[24]: import cudf
In[25]: df = cudf.DataFrame({'a':cudf.Series([32434345435, 345345435, 343453], dtype='datetime64[ns]')})
In[26]: df
Out[26]: 
                              a
0 1970-01-01 00:00:32.434345435
1 1970-01-01 00:00:00.345345435
2 1970-01-01 00:00:00.000343453
In[27]: df.to_json('sample.json', lines=True, orient='records', date_unit='ns')
/home/pgali/anaconda3/envs/cudf_dev/lib/python3.7/site-packages/cudf/io/json.py:82: UserWarning: Using CPU via Pandas to write JSON dataset, this may be GPU accelerated in the future
  "Using CPU via Pandas to write JSON dataset, this may "
In[28]: cudf.read_json('sample.json', lines=True, orient='records', dtype={'a':'datetime64[ns]'})
Out[28]: 
                        a
0 1969-12-31 23:59:59.999
1 1969-12-31 23:59:59.999
2 1969-12-31 23:59:59.999

# But without `dtype` parameter the underlying values(integers) remain correct
In[33]: cudf.read_json('sample.json', lines=True, orient='records')
Out[33]: 
             a
0  32434345435
1    345345435
2       343453
```
**Expected behavior**
```python
In[28]: cudf.read_json('sample.json', lines=True, orient='records', dtype={'a':'datetime64[ns]'})
Out[28]: 
                              a
0 1970-01-01 00:00:32.434345435
1 1970-01-01 00:00:00.345345435
2 1970-01-01 00:00:00.000343453
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 2f26bc2ab19b4c36546ebed8618a33de81ee4808 (HEAD -> 7103)
     Merge: d020dbb40a 4da8312d5b
     Author: galipremsagar <sagarprem75@gmail.com>
     Date:   Tue Jan 12 11:48:25 2021 -0600
     
     Merge remote-tracking branch 'upstream/branch-0.18' into 7103
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
     NAME="Ubuntu"
     VERSION="20.04.1 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.1 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux pgali-HP-Z8-G4-Workstation 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Jan 12 15:55:43 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 8000     Off  | 00000000:22:00.0 Off |                  Off |
     | 33%   31C    P8     5W / 260W |    724MiB / 48601MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro RTX 8000     Off  | 00000000:2D:00.0  On |                  Off |
     | 33%   34C    P8    20W / 260W |    406MiB / 48592MiB |      3%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A       974      G   /usr/lib/xorg/Xorg                  4MiB |
     |    0   N/A  N/A      1775      G   /usr/lib/xorg/Xorg                  4MiB |
     |    0   N/A  N/A     25101      C   .../envs/cudf_dev/bin/python      711MiB |
     |    1   N/A  N/A       974      G   /usr/lib/xorg/Xorg                 39MiB |
     |    1   N/A  N/A      1775      G   /usr/lib/xorg/Xorg                190MiB |
     |    1   N/A  N/A      1903      G   /usr/bin/gnome-shell              105MiB |
     |    1   N/A  N/A      3821      G   ...AAAAAAAA== --shared-files       30MiB |
     |    1   N/A  N/A     18401      G   ...f_3394.log --shared-files       27MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          12
     On-line CPU(s) list:             0-11
     Thread(s) per core:              2
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           85
     Model name:                      Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
     Stepping:                        4
     CPU MHz:                         1200.030
     CPU max MHz:                     3700.0000
     CPU min MHz:                     1200.0000
     BogoMIPS:                        6800.00
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        6 MiB
     L3 cache:                        19.3 MiB
     NUMA node0 CPU(s):               0-11
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX unsupported
     Vulnerability L1tf:              Mitigation; PTE Inversion
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/pgali/anaconda3/envs/cudf_dev/bin/cmake
     cmake version 3.18.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
     Copyright (C) 2019 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Wed_Jul_22_19:09:09_PDT_2020
     Cuda compilation tools, release 11.0, V11.0.221
     Build cuda_11.0_bu.TC445_37.28845127_0
     
     ***Python***
     /home/pgali/anaconda3/envs/cudf_dev/bin/python
     Python 3.7.9
     
     ***Environment Variables***
     PATH                            : /home/pgali/anaconda3/envs/cudf_dev/bin:/home/pgali/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin
     LD_LIBRARY_PATH                 : :/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/pgali/anaconda3/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/pgali/anaconda3/condabin/conda
     # packages in environment at /home/pgali/anaconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200923.2           h9c3ff4c_1    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                        py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h4abf009_2    conda-forge
     arrow-cpp                 1.0.1           py37hf99d332_21_cuda    conda-forge
     arrow-cpp-proc            2.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-common              0.4.59               h36c2ea0_1    conda-forge
     aws-c-event-stream        0.1.6                had2084c_6    conda-forge
     aws-checksums             0.1.10               h4e93380_0    conda-forge
     aws-sdk-cpp               1.8.70               h57dc084_1    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.3            py37h89c1867_0    conda-forge
     boost-cpp                 1.74.0               h9d3c048_1    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_1    conda-forge
     cffi                      1.14.4           py37hc58025e_1    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   4.0.0            py37h89c1867_1    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.5               h1f3970d_0    rapidsai-nightly
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.3.1            py37h7f0c10b_1    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.0a0+163.g2f26bc2ab1          pypi_0    pypi
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py37h0ce7dbb_0    rapidsai
     cython                    0.29.21          py37hcd2ae1e_2    conda-forge
     cytoolz                   0.11.0           py37h4abf009_1    conda-forge
     dask                      2020.12.0+34.g4f4d2950          pypi_0    pypi
     dask-cudf                 0.18.0a0+163.g2f26bc2ab1.dirty          pypi_0    pypi
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2020.12.0+21.g658fccc3          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37h89c1867_3    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37hcd2ae1e_3    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     execnet                   1.7.1                      py_0    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  1.2.3            py37h5e8e339_0    conda-forge
     fastrlock                 0.5              py37hcd2ae1e_2    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h7ca028e_0    conda-forge
     fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
     future                    0.18.2           py37h89c1867_3    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.34.0               hf41bbd9_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                6.0.0              pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  1.5.12             pyhd3deb0d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        2.0.0                      py_1    conda-forge
     importlib_metadata        2.0.0                         1    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.4.2            py37h888b3d9_0    conda-forge
     ipython                   7.19.0           py37h888b3d9_1    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2           py37h89c1867_1    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
     jupyter_core              4.7.0            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.11                 hcbb858e_1    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_1    conda-forge
     libblas                   3.9.0                7_openblas    conda-forge
     libcblas                  3.9.0                7_openblas    conda-forge
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
     libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
     libgfortran5              9.3.0               he4bcb1c_17    conda-forge
     libgomp                   9.3.0               h5dbcf3e_17    conda-forge
     liblapack                 3.9.0                7_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.14.0               h780b84a_0    conda-forge
     librmm                    0.18.0a210112   cuda11.0_g94b083a_20    rapidsai-nightly
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.2.0                hdc55705_0    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuv                     1.40.0               h7f98852_0    conda-forge
     libwebp-base              1.1.0                h36c2ea0_3    conda-forge
     llvmlite                  0.35.0           py37h9d7f4d0_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py37h5e8e339_3    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h5e8e339_1003    conda-forge
     more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
     nbclient                  0.5.1                      py_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.0.8                      py_0    conda-forge
     nbsphinx                  0.8.0              pyhd3deb0d_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.1.6            py37h89c1867_0    conda-forge
     numba                     0.52.0           py37hdc94413_0    conda-forge
     numpy                     1.19.5           py37haa41c4c_1    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.1            py37h5e8e339_2    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1i               h7f98852_0    conda-forge
     orc                       1.6.6                h7950760_1    conda-forge
     packaging                 20.8               pyhd3deb0d_0    conda-forge
     pandas                    1.1.5            py37hdc94413_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.1.0            py37he6b4880_1    conda-forge
     pip                       20.3.3             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37h89c1867_4    conda-forge
     pre-commit                2.9.3            py37h89c1867_0    conda-forge
     pre_commit                2.9.3                hd8ed1ab_0    conda-forge
     prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
     prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
     protobuf                  3.14.0           py37hcd2ae1e_1    conda-forge
     psutil                    5.8.0            py37h5e8e339_1    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37h9267296_21_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
     pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
     pyorc                     0.4.0                    pypi_0    pypi
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
     pysocks                   1.7.1            py37h89c1867_3    conda-forge
     pytest                    6.2.1            py37h89c1867_1    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     pytest-forked             1.2.0              pyh9f0ad1d_0    conda-forge
     pytest-xdist              2.2.0              pyhd8ed1ab_0    conda-forge
     python                    3.7.9           hffdb5ce_0_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.5             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.3.1            py37h5e8e339_2    conda-forge
     pyzmq                     20.0.0           py37h499b945_1    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
     regex                     2020.11.13       py37h5e8e339_1    conda-forge
     requests                  2.25.1             pyhd3deb0d_0    conda-forge
     rhash                     1.4.1                h7f98852_0    conda-forge
     rmm                       0.18.0a210112   cuda_11.0_py37_g94b083a_20    rapidsai-nightly
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37h89c1867_3    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.4.3              pyhd8ed1ab_0    conda-forge
     sphinx-copybutton         0.3.1              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.1              pyhd3deb0d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     streamz                   0.6.1              pyhd3deb0d_1    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.2            py37h89c1867_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h5e8e339_1    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     typed-ast                 1.4.2            py37h5e8e339_0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
     virtualenv                20.3.0           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.3                h58526e2_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.8                ha95c52a_1    conda-forge
     
</pre></details>

**Additional context**
Surfaced while fuzz testing: #6001

**Comment by beckernick** [comment]
This is still an issue, but a duplicate of https://github.com/rapidsai/cudf/issues/6382 . Closing to consolidate discussion in #6382
