### ISSUE TITLE
[FEA] Support mangle_dupe_cols in read_csv

### ISSUE THREAD

**Issue by mjsamoht** [rapidsai/cudf#713]
This corresponds to 'mangle_dupe_cols' parameter in pandas.

Duplicate columns will be specified as ‘X’, ‘X.1’…’X.N’, rather than ‘X’…’X’. Default is True.  Passing in False will cause data to be overwritten if there are duplicate names in the columns.

**Comment by vuule** [comment]
Looks like pandas does not support mangle_dupe_cols=False yet. Our behavior is consistent with mangle_dupe_cols=True, so we are pretty much compatible with pandas on this. I recommend prioritizing this feature very low.

**Comment by mjsamoht** [comment]
Okay, since pandas doesn't support this I will de-prioritize.

**Comment by karthikeyann** [comment]
In our implementation when `mangle_dupe_cols=False`, All duplicate columns will be ignored; First appearance is parsed. is this behavior requested somewhere?
pandas is opposite of that.
> Passing in False will cause data to be overwritten if there are duplicate names in the columns.

**Comment by beckernick** [comment]
Given that our behavior matches for `mangle_dupe_cols=True`, we support `mangle_dupe_cols=False` as noted above, and `mangle_dupe_cols=False` is not supported in pandas, it doesn't sound like there is any action to take.

Given that, I'm going to close this issue.
