### ISSUE TITLE
[FEA] Add list len support

### ISSUE THREAD

**Issue by albert17** [rapidsai/cudf#7157]
**Is your feature request related to a problem? Please describe.**
I need to be able to get list len for the entries of a column whose data type is list. @kkraus14 told me this is not implemented yet.

It works for string: `ddf[col] = ddf[col].map_partitions(lambda x: x.str.len())`

But not for list: `ddf[col] = ddf[col].map_partitions(lambda x: x.list.len(), meta=(col, ddf_dtypes[col].dtype))` I get the error `Exception: AttributeError("'ListMethods' object has no attribute 'len'")`

**Comment by kkraus14** [comment]
I believe we'd need a new libcudf function of something like `cudf::list::count_elements` or something similar, where the output would be a column of integers with the number of elements in each list element.

**Comment by revans2** [comment]
+1 we could definitely use this for spark too.

**Comment by isVoid** [comment]
@shwina and I will pair on introducing the python API.

**Comment by kkraus14** [comment]
Fixed by #7283
