### ISSUE TITLE
[DOC] Not 100% accurate statement in 10 min to cuDF and CuPy

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#7160]
## Report incorrect documentation
Hi!

I think the following paragraph is not 100% accurate:

> Because CuPy arrays have a single dtype, each column in our DataFrame must have the same dtype, **regardless of which method we use.**

The following code works just fine:

```
import cudf
import cupy

df = cudf.DataFrame({'a': 3, 'b': 3.0})
arr = cupy.asarray(df.as_gpu_matrix())
```

In the example above, `int` datatypes as casted to `float64`.

Hope it helps!
Miguel

**Location of incorrect documentation**
https://github.com/rapidsai/docs/blob/gh-pages/api/cudf/0.18/10min-cudf-cupy.ipynb

**Comment by ajschmidt8** [comment]
@miguelusque, the documentation you mentioned is automatically generated from `cudf`'s source files, so I've transferred your issue into the `cudf` repo.
