### ISSUE TITLE
[DOC] no cuDF notebooks in folder or in rapidsai notebook forlder

### ISSUE THREAD

**Issue by Sh4zKh4n** [rapidsai/cudf#7163]
**Location of incorrect documentation**
The notebooks seem to be empty and the rapidsai notebook collection is missing any notebooks on cuDF

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

https://github.com/rapidsai/cudf/tree/branch-0.18/notebooks

https://github.com/rapidsai/notebooks

**Steps taken to verify documentation is incorrect**
I have looked and havent found any notebooks.

**Suggested fix for documentation**
Return the example notebooks for cuDF for new users.

**Comment by kkraus14** [comment]
Hi @Sh4zKh4n, at this time we don't have any notebooks outside of our documentation notebooks for cudf. You can see the documentation notebooks here: https://github.com/rapidsai/cudf/tree/branch-0.18/docs/cudf/source

If someone would like to contribute notebooks demonstrating cuDF in the future we'd be very happy.
