### ISSUE TITLE
[BUG] fatal error: simt/chrono: No such file or directory

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [rapidsai/cudf#7165]
Now our group (HugeCTR https://github.com/NVIDIA/HugeCTR) is trying to install cuDF with conda instead of building from source code. This is the command we are using to install cuDF:
```
conda config --add channels conda-forge --add channels nvidia --add channels rapidsai --add channels anaconda && \
conda install -y cudf=0.17.0 cudatoolkit=11.0
```
By using the above command, we can install cuDF successfully.
But when building our project, I encounter the following error message:
```
/opt/conda/include/cudf/wrappers/durations.hpp:24:10: fatal error: simt/chrono: No such file or directory
 #include <simt/chrono>
```
The same error occurs when using cuDF-0.16. Could you give us some suggestions about this issue?

**Comment by harrism** [comment]
@trxcllnt @jrhemstad @kkraus14 Leaked libcu++ dependency. Not sure it's possible to avoid this going forward (even if libcudf doesn't leak it, RMM is likely to), so we need a way to make sure it's included with the installed library and found by dependent libs.
