### ISSUE TITLE
how to read excel sheet by sheet using cuDF?

### ISSUE THREAD

**Issue by Gpwner** [rapidsai/cudf#7191]
**What is your question?**
how to read excel sheet by sheet using cuDF?

**Comment by harrism** [comment]
If you export the excel to a CSV (comma-separated value) file, you can read it using cuDF's [`read_csv`](https://docs.rapids.ai/api/cudf/stable/api.html#cudf.io.csv.read_csv).

**Comment by beckernick** [comment]
Additionally, you can read an excel sheet in pandas with `pd.read_excel` and then use `cudf.from_pandas`.

**Comment by kkraus14** [comment]
There are no plans to GPU accelerate reading excel sheets in cuDF, especially given there's a ~1MM row limit to excel sheets. We could consider adding a convenience API to pipeline through Pandas for this, but won't do so unless there's community feedback indicating demand.
