### ISSUE TITLE
[BUG] cudf::round produces incorrect results for FLOAT32/FLOAT64

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7195]
**Describe the bug**
We found while running TPCDS queries in spark that some values round incorrectly when done on FLOT32/FLOAT64. I don't really know the reasons why though.

**Steps/Code to reproduce bug**
apply the following patch and run `ROUND_TEST`

```diff
diff --git a/cpp/tests/round/round_tests.cpp b/cpp/tests/round/round_tests.cpp
index 06fd5faddf..4a868aad18 100644
--- a/cpp/tests/round/round_tests.cpp
+++ b/cpp/tests/round/round_tests.cpp
@@ -335,6 +335,29 @@ TYPED_TEST(RoundTestsFloatingPointTypes, SimpleFloatingPointTestWithNullsHalfUp)
   CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected, result->view());
 }
 
+TYPED_TEST(RoundTestsFloatingPointTypes, SimpleFloatingPointTestHalfUpIssues)
+{
+  using fw_wrapper = cudf::test::fixed_width_column_wrapper<TypeParam>;
+
+  auto const input    = fw_wrapper{{1.025, 0.575, 2.005, 2.015, 2.025}};
+  auto const expected = fw_wrapper{{1.03, 0.58, 2.01, 2.02, 2.03}};
+  auto const result   = cudf::round(input, 2, cudf::rounding_method::HALF_UP);
+
+  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected, result->view());
+}
+
+
+TYPED_TEST(RoundTestsFloatingPointTypes, SimpleFloatingPointTestHalfEvenIssues)
+{
+  using fw_wrapper = cudf::test::fixed_width_column_wrapper<TypeParam>;
+
+  auto const input    = fw_wrapper{{1.025, 0.575, 2.005, 2.015, 2.025}};
+  auto const expected = fw_wrapper{{1.03, 0.58, 2.01, 2.02, 2.03}};
+  auto const result   = cudf::round(input, 2, cudf::rounding_method::HALF_EVEN);
+
+  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected, result->view());
+}
+
 TYPED_TEST(RoundTestsFloatingPointTypes, SimpleFloatingPointTestNegHalfUp1)
 {
   using fw_wrapper = cudf::test::fixed_width_column_wrapper<TypeParam>;
```

**Expected behavior**
It should pass

**Comment by harrism** [comment]
There is always going to be a problem with trying to round binary floating point values to a specific number of decimal places. Binary numbers have binary places, not decimal places. 

What is happening here is this:

1.025 is not exactly representable in binary floating point. Enter it here: https://www.h-schmidt.net/FloatConverter/IEEE754.html  You will see that the actual stored value is `1.02499997615814208984375`.

The implementation of HALF_UP round used here is this:
https://github.com/rapidsai/cudf/blob/2e0889aed46ca84ad3731249b2b29eeb59dcda1f/cpp/src/round/round.cu#L100-L106

What happens is `(roundf(0.02499997615814208984375 * 100) / 100 --> 2.0 / 100 --> 0.02`. 
What you are expecting is `(roundf(0.025 * 100) / 100 --> 3.0 / 100 --> 0.03`

@codereport should comment but I am guessing "fixing" this behavior would be complicated...

**Comment by codereport** [comment]
@harrism is exactly correct. This is not a bug. This is just how floating point works. It is the same issue that leads to 
```cpp
auto const x= decimal32{1.001, scale_type{-3}}; // x == 1, not 1.001 : (
```
As Mark pointed out in the original discussion, this is inevitably going to lead to times where results _look wrong_ but are actually just working the way IEEE floating point works. 

I agree with @harrism that it would be very complicated.

**Comment by revans2** [comment]
The reason that I found these errors is because Spark is getting different numbers that appeared to be correct. But I should have looked more closely.  They are converting to decimal first and then doing the rounding.

```
BigDecimal(d).setScale(_scale, mode).toDouble
```

You are correct.
