### ISSUE TITLE
[FEA] Support partitioning by columns in chunked Parquet writer

### ISSUE THREAD

**Issue by chinmaychandak** [rapidsai/cudf#7196]
The chunked parquet writer does a great job of creating a single large parquet file output instead of generating of lots of smaller parquet files (extremely useful in batch ETL, streaming use cases). 

But it does not support partitioning by columns, and putting an upper limit of the size of the large parquet file being overwritten before creating a new one. It would be absolutely great to have that support, if at all possible. I could not find the chunked parquet writer in the API docs, too. Any reason for that?

Also, do we have perf. metrics for the accelerated parquet writers/readers (including chunked writer)?

**Comment by randerzander** [comment]
Still a desired [FEA]

**Comment by devavret** [comment]
@randerzander Do you mean you want to use the chunked writer to write one column at a time?

**Comment by randerzander** [comment]
@chinmaychandak can you say more about your use case?

**Comment by chinmaychandak** [comment]
We use `df.to_parquet(..., partition_cols=[a, b])` in custreamz (streaming) - a bunch of small parquet files are created per batch using this operation. The number of files becomes really large as more and more batches get processed.

Querying such a large number of parquet files downstream is inefficient - we need to be able to aggregate smaller parquet files (within each partition_col directory, ofc) so that downstream querying becomes much more efficient. 

Without `partition_cols`, the chunked writer already does the trick.

Another FEA which would be really good (both w/ and w/o partition_cols) in the chunked writer is to be able to specify a size limit until which the chunked writer aggregates/overwrites smaller parquet files - once that size is reached, it should automatically start writing to a new parquet file.

Also, there's no docs on the chunked writer currently? 

Let me know if you want me to open FEAs for the above two.

**Comment by chinmaychandak** [comment]
BTW, Databricks Delta supports the above features, and they're super useful! It would be awesome if we could have them here.
