### ISSUE TITLE
[BUG] `assert_eq` is failing to assert for integer comparison

### ISSUE THREAD

**Issue by rgsl888prabhu** [rapidsai/cudf#7199]
**Describe the bug**
assert_eq is not failing when comparing two different integer values.

**Steps/Code to reproduce bug**
```
>>> from cudf.tests.utils import assert_eq
>>> a = 1493282
>>> b = 1493274
>>> assert_eq(a, b)
True
```

**Expected behavior**
This should assert and fail

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [from source]

**Additional context**
This is failing as it hits `np.allclose` in asser_eq, may be needs a check for type before it goes to `np.allclose`.

**Comment by isVoid** [comment]
If all compare operands that falls under https://github.com/rapidsai/cudf/blob/eb1336f96b320815cf742289d3a5492a5b21fe03/python/cudf/cudf/tests/utils.py#L99-L106 are scalars, I suggest replacing them with the following logic:

```python
        if np.issubdtype(type(left), np.floating):
            np.testing.assert_almost_equal(left, right)
        else:
            np.testing.assert_equal(left, right)
```

Note that `np.testing.assert_equal(np.nan, np.nan)` will not raise.

**Comment by isVoid** [comment]
cc @kkraus14 @shwina for visibility
