### ISSUE TITLE
[FEA] Support rank in rolling_window

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#7208]
**Is your feature request related to a problem? Please describe.**
Like `ROW_NUMBER`, which supported in [PR 4881](https://github.com/rapidsai/cudf/pull/4881), `RANK` is widely used window function in spark sql (and other sql engines). So, we want to provide GPU override of `RANK` in spark-rapids, which relied on cuDF implementaion.
[Here](https://jaceklaskowski.gitbooks.io/mastering-spark-sql/content/spark-sql-functions-windows.html#rank) is the eloboration of `RANK`.

**Describe the solution you'd like**
Referring the implementation of row_number, I suggest we firstly implement `process_rolling_window` functor for `RANK` to support numeric `RANK`. Then, we support `RANK` in `time_range_rolling_window`.

**Additional context**
[Here](https://github.com/NVIDIA/spark-rapids/issues/1584) is the related issue in spark-rapids.

**Comment by williamBlazing** [comment]
BlazingSQL would like RANK and DENSE_RANK for `rolling_window`, and `grouped_rolling_window`

**Comment by sameerz** [comment]
This issue still valid.

**Comment by sameerz** [comment]
Tagging @rwlee who is looking at this issue.
