### ISSUE TITLE
[BUG] Test column comparison functions do not compare column null_count()

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#7210]
The comparison of `null_count()` inside of `column_property_comparator::compare_common()` between input columns seems to have been erroneously removed.   

Adding it back in causes a few unit tests to fail (1 in RESHAPE_TEST, 1 in STREAM_COMPACTION_TEST and a number of them in COPYING_TEST)

`EXPECT_EQ(lhs.null_count(), rhs.null_count());`

**Comment by harrism** [comment]
Looking over the history, it doesn't look to me like `column_property_comparator::compare_common()` ever compared `null_count()`.
