### ISSUE TITLE
[BUG] NaN values no longer sort correctly after optimization

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7212]
**Describe the bug**
After #7167 was merged in NaN values no longer sort the same as they did before.  From https://github.com/rapidsai/cudf/pull/7167#issuecomment-767687989 it sounds like the optimization will be disabled for floating point sorts.

**Comment by davidwendt** [comment]
@revans2  Would you mind trying the changes in #7215 to make sure it fixes this error?

**Comment by revans2** [comment]
> @revans2 Would you mind trying the changes in #7215 to make sure it fixes this error?

@davidwendt I am in the process of building them right now, but it might take a while. I'll post on #7215 with my results
