### ISSUE TITLE
[BUG] Parquet reader segfaults loading file with nested type as map key

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#7229]
**Describe the bug**
libcudf crashed with a segfault while trying to load a Parquet file containing a column with a Map type.  This file is a bit interesting since the Map key is a nested type instead of a primitive type.  I verified this file can be loaded successfully in Apache Spark.

The crash occurs when trying to specify the column name to load from this file.  Without specifying the name of any column to load the crash does not occur.

**Steps/Code to reproduce bug**
A sample Parquet file is attached that can reproduce the crash.

[maptest.parquet.zip](https://github.com/rapidsai/cudf/files/5882866/maptest.parquet.zip)

Unzip the archive and use the following test code to reproduce the crash.
```c++
#include <cudf/io/parquet.hpp>
#include <cudf/table/table.hpp>

int main() {
  auto path = std::string("maptest.parquet");
  auto opts = cudf::io::parquet_reader_options::builder(cudf::io::source_info(path))
    // NOTE: without specifying the column name it does not crash
    .columns({"value"})
    .build();
  auto result = cudf::io::read_parquet(opts);
  return 0;
}
```

**Expected behavior**
libcudf methods should not segfault with valid inputs.

**Comment by devavret** [comment]
Seems to work. What's the expected result? Does this look like it? I cannot confirm because pyarrow doesn't seem to support reading list of structs from parquet.

```python
In [1]: import cudf

In [2]: cudf.read_parquet("maptest.parquet")
Out[2]: 
                                               value
0  [{'key': {'first': 'John', 'middle': 'Y.', 'la...
```
