### ISSUE TITLE
[FEA] Explore Jitify v2 Support

### ISSUE THREAD

**Issue by cwharris** [rapidsai/cudf#7245]
https://github.com/NVIDIA/jitify/blob/jitify2/jitify2_user_guide.md

**Comment by cwharris** [comment]
`cudatoolkit=11.2` is being published to `conda-forge` currently.

https://github.com/conda-forge/cudatoolkit-feedstock/pull/46

**Comment by cwharris** [comment]
Jitify v1 allowed for header source lookup given a header name, but it doesn't look like we took advantage of this at any point. Instead, we were using file callback to populate header source (see launcher.cpp). Jitify allows header source to be provided explicitly, which is what we're doing, but it accepts this in the form of a string formatted like `<header_name>\n<header_source>`, and this is how we provide it. Jitify v2 does not allow header source lookup, and expects both the header name and source to be included as a string map. I'll need to separate out the header name and header source from the `<header_name>\n<header_source>`  format string to populate the string map so it jitify v2 will understand it.

I plan on doing this in a couple phases.

**Comment by vyasr** [comment]
@cwharris we can close this now that #7372 is merged, right?

**Comment by cwharris** [comment]
@vyasr not yet, we're still looking in to some issues.

**Comment by cwharris** [comment]
https://github.com/rapidsai/cudf/pull/7919
