### ISSUE TITLE
[BUG] CSV reader: tabs are not supported and blank characters when parsing data

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#725]
dtypes = ['float64', 'int64']
lines = [','.join(dtypes),
        "\t1.1, \t1",
        "\t12.12, \t2",
        "\t123.123, \t3"]
buffer = '\n'.join(lines) + '\n'
cu_df = read_csv(StringIO(buffer))

The output is garbage, because \t is treated as part of the number.

**Comment by vuule** [comment]
You can assign this to me, I think I know where the issue is.

**Comment by harrism** [comment]
Unless this is crucial it will be 0.6 -- we are supposed to be in burn down for 0.5.

**Comment by mjsamoht** [comment]
Fixed by #815
