### ISSUE TITLE
[BUG] read_csv cann't read full data

### ISSUE THREAD

**Issue by KimChow** [rapidsai/cudf#7263]
**Describe the bug**
cudf.read_csv cann't read full data
![image](https://user-images.githubusercontent.com/5865561/106351803-71d44100-6319-11eb-8e67-e2a2cd2b87cb.png)

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**
total is 1241525 row, only read 367407 

**Environment overview (please complete the following information)**
 - Environment location: wls ubuntu 18
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
python3.8

**Comment by galipremsagar** [comment]
@KimChow could you provide us the CSV file or its url?

**Comment by kkraus14** [comment]
No response for reproducer, closing the issue.
