### ISSUE TITLE
[FEA] pass a a list-like, or callable to the skiprows

### ISSUE THREAD

**Issue by naarkhoo** [rapidsai/cudf#7268]
**Is your feature request related to a problem? Please describe.**
using _iteratable_ as skiprows for `read_csv` similar to pandas

**Describe the solution you'd like**
so one can pass a a list-like, or callable to the skiprows

**Additional context**
This helps to read a csv file in a selective way - I don't know other options where one can skip some certain rows. In a large file it would be difficult to read a file first and the filter out.

**Comment by vuule** [comment]
closing as duplicate of https://github.com/rapidsai/cudf/issues/5017
