### ISSUE TITLE
[QST] Is it better to use shared memory in regex engine implementation?

### ISSUE THREAD

**Issue by K-Wu** [rapidsai/cudf#7281]
Hi,

I appreciate a lot your effort in releasing the RAPIDS suite. I have a question about the performance choice when you implement the regex engine during my reading the source code. It seems the current implementation uses thread-local memory and does not use shared memory during processing regular expression. Besides, some other APIs implementation that uses thrust to parallelize or transform does not use shared memory, either. Does that mean thread-local memory performance is close to shared memory in latest microarchitectures?

Thank you.

Best Regards,
Kun

**Comment by harrism** [comment]
@davidwendt have you thought about this?

**Comment by davidwendt** [comment]
I've been thinking about it. There are a few things I certainly like to try. But I want to create some strings benchmarks #5698 before trying to experiment with performance improvements. The next one on my list does include an API that uses regex.

**Comment by harrism** [comment]
@K-Wu I'm going to close this since it's a bit open-ended.  Our regex implementation can certainly be improved, and likely will in the future.

**Comment by K-Wu** [comment]
@harrism @davidwendt Sure. Thank you for the answers and examining this issue!
