### ISSUE TITLE
[BUG] Casting Decimal32 to Decimal64 returns an invalid value

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#7291]
**Describe the bug**
While adding support for Decimal32 in the Spark-plugin I ran into a situation where I have to upcast two Decimal32 values before multiplying them otherwise the result isn't automatically promoted to a Decimal64. I noticed casting directly from D32 to D64 doesn't work and I have to do the following D32 -> INT32 -> INT64 -> D64

**Steps/Code to reproduce bug**
Just take a D32 value and try to upcast it to D64 by calling `castTo`. e.g. 

```
Decimal(unscaledValue=578375, scale=-8).castTo(D64(scale=-8) => D64(unscaledValue=0, scale=-8) 
```
which is wrong 

**Expected behavior**
I expect to see the same values in a D64 column instead of a D32 but what I see is garbage.

**Comment by codereport** [comment]
I don't think this is a bug. 
```scala
Decimal(unscaledValue=578375, scale=-8)
```
is unrepresentable as a `Decimal32`. `578,375` with scale of `-8` will be stored as `578,375 * 10^8` which is `5.78375e+13` - which exceeds the maximum value of `int32_t`.

However, considering you are got this to work by converting to `int32` first - I am a bit confused. Am i missing something?

**Comment by codereport** [comment]
Treating `578,375` as an already scaled value, I replicated the test in libcudf and it worked fine:
```
TEST_F(FixedPointTestOneRep, CastFrom32to64)
{
  using namespace numeric;

  auto const input    = cudf::test::fixed_point_column_wrapper<int32_t>{{578375},scale_type{-8}};
  auto const expected = cudf::test::fixed_point_column_wrapper<int64_t>{{578375},scale_type{-8}};
  auto const result   = cudf::cast(input, make_fixed_point_data_type<decimal64>(-8));

  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected, result->view());
}
```

**Comment by razajafri** [comment]
Give me sometime to verify this. I am switching over to another task so it won't be until a few days

**Comment by ttnghia** [comment]
Ping you guys to check if this is still an issue.

**Comment by razajafri** [comment]
this isn't reproducible. I might have caught a build in which this wasn't working but I don't see it currently. Closing it
