### ISSUE TITLE
Reduce the size of parquet/orc functions

### ISSUE THREAD

**Issue by kaatish** [rapidsai/cudf#7299]
Some function in parquet and orc are quite large, for eg. [`gpuInitPageFragments()`](https://github.com/rapidsai/cudf/blob/54cddb10db3f9ee1794b9e00fc9a69a75942806e/cpp/src/io/parquet/page_enc.cu#L113-L407) is 294 and [`gpuDecodeOrcColumnData()`](https://github.com/rapidsai/cudf/blob/branch-0.18/cpp/src/io/orc/stripe_data.cu#L1397-L1745) is 348 lines long.

For readability and maintainability it would be good to break them into smaller and easier to understand functions. Ideally the number of lines for such functions should be around 100 lines or less.

- [x] Parquet reader
- [ ] Parquet writer
- [ ] ORC reader
- [ ] ORC writer

**Comment by vuule** [comment]
Just a note that addressing this will most likely include other clean up in/around the affected functions to further improve readability/maintainability. For example, I expect that we want to add some types/abstractions, increase the use of algorithms, reduce the mutable state, improve naming as we go about breaking these long functions apart.
I might have a sample PR for this soon.

**Comment by vuule** [comment]
still relevant

**Comment by GregoryKimball** [comment]
@vuule I would like to close this issue because it is too broad and not adequately specific enough. Please let me know if you would like us to rework this topic in a new issue.

**Comment by vuule** [comment]
Parquet reader has made great strides in this regard (and ORC reader refactor is underway) so we can probably make an issue focused on writers. I know that ORC writer code could be reorganized to decrease compile time, if nothing else.

I'd need to look into this and come up with a more detailed proposal. Some aspects to keep in mind: separate host from device code so we can have some code in .cpp files; make sure PQ and ORC components are reasonably aligned.
