### ISSUE TITLE
[BUG] Slow performance in left_anti_join and left_semi_join when nulls are in the data

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#7300]
**Describe the bug**
Performance is really bad in `left_anti_join` and `left_semi_join` calls when nulls are involved. It appears to be related to #6052 in that we are building a hash table and performance suffers with collisions.

**Steps/Code to reproduce bug**
Generate a table with some null keys and run `left_anti_join` or `left_semi_join` on the data. The performance can be measured in minutes with a table of 10 million rows.

**Expected behavior**
When nulls are not equal, we don't need to hash the row and store it, so this is completely wasted work to hash the row if it is null.

**Comment by kkraus14** [comment]
@hyperbolic2346 was this fixed by #6943?

**Comment by hyperbolic2346** [comment]
@kkraus14 No, this is the same issue in a different spot. Probably the same general fix as well.

**Comment by jlowe** [comment]
We currently have a workaround in place for this in the Spark plugin where nulls are manually filtered before performing the join. I'd love to see this fixed so we can remove it.

**Comment by jlowe** [comment]
This is still relevant.

**Comment by jlowe** [comment]
Still relevant

**Comment by nvdbaranec** [comment]
Starting on this.
