### ISSUE TITLE
[FEA] Support cudatoolkit=11.2

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [rapidsai/cudf#7339]
Now when I install cudf through conda, I should specify `cudatoolkit=11.0`, or there will be errors like this:
```
UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
Package libgcc-ng conflicts for:
cudf=0.19 -> cudatoolkit[version='>=11.0.221,<11.1.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0|>=7.2.0']
```
When do you think is possible to support `cudatoolkit=11.2`?

**Comment by harrism** [comment]
Hi @XiaoleiShi-NV we are working to add support for 11.2 in the next release (0.19). We need to add support in our CI systems first. Also, there are various conda packages that we depend on that need to add 11.2 support.

**Comment by harrism** [comment]
Still relevant.

**Comment by kkraus14** [comment]
This now works as expected in the 0.19 release. Closing.
