### ISSUE TITLE
[BUG] orc writing can produce invalid orc file

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#7346]
**Describe the bug**
We had some unicorn data come through in https://github.com/NVIDIA/spark-rapids/issues/1550 that produced invalid orc data that would crash spark. We couldn't reproduce it by writing the data to parquet, reading it into memory, and then writing it to orc. There is something magical about how this data is ordered or something. I wrote a hack to dump the contents of the orc write function to disk and then a small test to read that data in and build a table and write that table with orc. This orc file is unreadable by spark.

The table is fairly normal looking data outside of some unicode characters. It has 7 columns of long and string types.

**Steps/Code to reproduce bug**
The code and data is in https://github.com/hyperbolic2346/cudf/tree/mwilson/dump_orc. I added the file 39852.tbl, which is the raw data dump from the orc write code and then a test that will read that file and produce a 39852.orc file. That file will crash spark reading it, so something is broken about that file. The test code expects the .tbl file live in /tmp when you run the test and will produce the orc file in /tmp as well.

**Expected behavior**
Orc files written by cudf should be readable by anything that can read orc.

**Additional context**
It seems related to nulls. I originally had a bug in my table writing code that didn't properly write out nulls and those files were readable by spark without issue. It wasn't until I got the null writing correct that the problem was reproduced.

**Comment by nvdbaranec** [comment]
Would be curious to see if  tbl -> cudf -> parquet -> cudf -> orc  also produces the issue.   Having a parquet file to start with would be handy.

**Comment by hyperbolic2346** [comment]
We tried this without the tbl in the middle. The first attempt to repro was to write the data as parquet and then read it and write it again as orc. This didn't produce the issue. The thought was handing off a parquet file would be easy for reproduction.

**Comment by nvdbaranec** [comment]
What I mean is :  if we can take the tbl data and covert it to parquet (assuming that parquet -> cudf -> orc also generates the bug) it's easier to work with that since we won't need your test/debug code.

**Comment by hyperbolic2346** [comment]
I understand that and I haven't tested that specifically. I have tested getting spark to ask cudf to write the data as parquet and then read that parquet into cudf and write it as orc with cudf and that does not reproduce the issue. The only way I could reproduce it was to go directly from this data to orc or get spark to write directly to orc. I'm not sure why that is required though.

**Comment by revans2** [comment]
This feels like an equivalence vs equality situation.  Are there nulls in the string columns? And can we check to see if any of the nulls point to non-empty data? This would explain why if we went through something like parquet or re-creating the table yourself would normalize the data the issue disappears.

**Comment by hyperbolic2346** [comment]
Yes, the first two string columns have 4 null rows at the very end of the columns but those have data.

**Comment by hyperbolic2346** [comment]
I tested this with some orc writes of test string data with nulls on the last row and was unable to reproduce this. It is possible that it requires enough data to not fit in a dictionary.

**Comment by kkraus14** [comment]
cc @vuule @rgsl888prabhu for visibility

**Comment by vuule** [comment]
I'll take a look once I'm done with the current task. 
Planning to compare the repro ORC file and the ORC file after going through Parquet write/read. Should at least show whether the difference is in ORC encoding, or dataframe content.

**Comment by vuule** [comment]
The repro file also crashes the pyarrow reader.

**Comment by vuule** [comment]
Well this is a fun one!

Wrote some tests and got very interesting results.
With original repro file:

- Read with cudf: column of empty strings
- Read with pyarrow: crash

Read the repro file and save it again as ORC:

- Read with cudf: column of null elements
- Read with pyarrow: column of empty strings

So now I got two lines to investigate: why does a column of empty strings turn into a column of nulls, and what's wrong with the repro file to cause the crash (and perhaps incorrect cudf result?).

**Comment by vuule** [comment]
Looks like there's some corruption between columns when writing - writing only "ffc_name" column does not result in crash when reading with pyarrow, while writing all columns up to "ffc_name" (inclusive) and reading only "ffc_name" produces the crash from the issue.

**Comment by vuule** [comment]
Another data point - the repro does not change when writing the file without compression. 
Given that direct encoding is used for the string column, the failure is very surprising since the ORC column is pretty much a copy of the cudf column.

**Comment by vuule** [comment]
@hyperbolic2346 I got a [PR](https://github.com/rapidsai/cudf/pull/7565) that resolves the issue locally. Will open the PR for review once I have a self-contained test.
