### ISSUE TITLE
[FEA] Refactor stats_column_desc in cuio

### ISSUE THREAD

**Issue by kaatish** [rapidsai/cudf#7347]
The stats_column_desc structure contains multiple members such as `valid_map_base`, `column_offset`, `column_data_base` etc. that can replaced by `column_device_view`.

Doing so will require changing other functions accordingly such as `GatherColumnStatistics`, `MergeColumnStatistics` used for stats calculation.

**Comment by devavret** [comment]
@kaatish  Does #7439 _completely_ address this?

**Comment by kaatish** [comment]
> @kaatish Does #7439 _completely_ address this?

No it does not. I am currently working on #7334 which should enable me to finish this.
