### ISSUE TITLE
 [FEA] url_decode is too slow for long url

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7348]
**Is your feature request related to a problem? Please describe.**
current `url_decode` is too slow for long url , the unit test example is dozens of characters, while length of my url chars are 500~1000 , and from nsihgt system, `replace` and `url_decode` kernel takes almost half of the total time. 

![image](https://user-images.githubusercontent.com/33319780/107328882-55d75900-6aea-11eb-80a9-e91a3e6dbdb4.png)

Comparative test in spark-rapids：
SQL contains `url_decode` CPU time is 15m
SQL contains `url_decode` GPU time is 37m
SQL not contains `url_decode` CPU time is 10m
SQL not contains `url_decode` GPU time is 2.8m

other configs and environment is same , so i can determin that the problem is url too long. when SQL not contains `url_decode`, speed up is up to 3.5X, while when it contains 'url_decode` , the performance is not as good as CPU.

**Comment by davidwendt** [comment]
How many strings are you testing with? 
Currently, GPU performance for most strings operations are usually better with a large number of small strings vs a small number of large strings.

**Comment by chenrui17** [comment]
> How many strings are you testing with?
> Currently, GPU performance for most strings operations are usually better with a large number of small strings vs a small number of large strings.

about 20,000 strings, and each string size is about 500~1000

**Comment by davidwendt** [comment]
Could you paste a few of the strings here? I could then duplicate them to create a set of 20K to reproduce this.

**Comment by jlowe** [comment]
I have a sample benchmark for `url_decode` along with a change to make it character-level parallelism instead of row-level parallelism.  I need to clean it up and upmerge, but I hope to post it later today.

**Comment by kkraus14** [comment]
@jlowe is this fixed by #7353?

**Comment by jlowe** [comment]
> is this fixed by #7353?

Yes.  For this specific case there's still a significant amount of time being spent in string scalar replace called just before `url_decode`, but that is tracked by #7370.
