### ISSUE TITLE
[BUG] Extensions are compiled twice when building the python package using build.sh

### ISSUE THREAD

**Issue by manopapad** [rapidsai/cudf#7361]
**Describe the bug**
Extensions are compiled twice when building the python package using `build.sh`.

**Steps/Code to reproduce bug**
Do a fresh git pull, then run `./build.sh cudf`.

**Expected behavior**
The `build_ext` step should compile everything, then the `install` step should just copy files to the installation directory. Instead it seems like the `install` step invokes `build_ext` again (without setting `PARALLEL_LEVEL` and `-j`, which makes compilation slow).

**Environment overview**
 - Environment location: bare-metal
 - Method of cuDF install: from source

**Environment details**
Prometheus DGX-1 cluster

**Additional context**
Here is the output I get when running `./build.sh cudf`: [output.txt](https://github.com/rapidsai/cudf/files/5955566/output.txt).

**Comment by vyasr** [comment]
This appears to have been fixed by the switch to scikit-build (if not before).
