### ISSUE TITLE
[BUG] head, tail, and loc/iloc with a slice should return a view, not a copy

### ISSUE THREAD

**Issue by magnatelee** [rapidsai/cudf#7374]
**Describe the bug**
In Pandas, any of the following operation create a view of the input dataframe/series through which one can make in-place updates:

- `head`
- `tail`
- `loc[from:to]`
- `iloc[from:to]`

On the other hand, in cuDF these operators make a separate copy for the selected subset.

**Steps/Code to reproduce bug**
Here is an example with `loc`. (the same can be reproduced with other operators as well.)

```
>>> x = cudf.Series([1,2,3,4,5,6])
>>> y = x.loc[0:2]  # creates a copy that contains the first three entries
>>> y
0    1
1    2
2    3
dtype: int64
>>> y[:] = y + 1  # updates y in place
>>> y
0    2
1    3
2    4
dtype: int64
>>> x             # x remains the same
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
```

Here is what Pandas does for the same program:
```
>>> x = pd.Series([1,2,3,4,5,6])
>>> y = x.loc[0:2]  # creates a view to x
>>> y
0    1
1    2
2    3
dtype: int64
>>> y[:] = y + 1
>>> y
0    2
1    3
2    4
dtype: int64
>>> x            # x is updated as well
0    2
1    3
2    4
3    4
4    5
5    6
dtype: int64
```

**Expected behavior**
I personally find the Pandas semantics inconsistent and confusing, as the same in-place update semantics doesn't apply to a case where the selected subset is non-contiguous (which can arise when, for example, one passes a boolean mask to `loc`). That said, if we want to be consistent with Pandas, cuDF should create views in the same way from these operators.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda (cudf-0.18.0a+157.g04aa30cf11)

**Comment by isVoid** [comment]
It looks like we could benefit from a test utility function `assert_same_memory` that can tell whether two python object is of different views of the same memory object. Under the hood it compares the value of `Buffer.ptr` value to determine if the two objects are pointing to the same piece of memory. 

For objects that holds more than one buffer object such as `StringColumn`(offset and char) or `cudf.Series`(index and value), I guess we have to compare recursively for all buffers involved? What about list-type columns that can nest other lists?

looking for opinions.. cc @shwina @kkraus14

**Comment by shwina** [comment]
I think it's more useful to write tests for the high level behaviour here, i.e. we test that assigning to a slice modifies the original object, rather than make assertions about the internal data.

**Comment by shwina** [comment]
To clarify what I said above: a utility to test that two objects share the same buffers does sound very useful to me, but it may not be sufficient for testing high level behaviour such as `loc/iloc`

**Comment by kkraus14** [comment]
I can imagine two useful test utilities here:
- `assert_equivalent_memory(input_obj, reference_obj)`
  - asserts that the underlying buffers in `input_obj` are the same as the underlying buffers in `reference_obj`, including having the same pointers and sizes
- `assert_is_view(input_obj, reference_obj)`
  - asserts that the underlying data buffer(s) in `input_obj` have the underlying buffers in `reference_obj` as a parent/owner
  
These get funky to try to use with things like string / list columns though in which some buffers can be views (character data for example), while others have to have a new column constructed (offsets for example).

**Comment by vyasr** [comment]
Closing since changes in both cudf and pandas moving towards copy-on-write semantics will make this concern obsolete. The copy semantics will be consistent by default starting in pandas 3.0, and can be made to be consistent in 2.0 (and current cudf) by turning on copy-on-write
