### ISSUE TITLE
[BUG] std incorrectly calculated in dask `describe` calls for specific dataframe values

### ISSUE THREAD

**Issue by wphicks** [rapidsai/cudf#7402]
**Describe the bug**
When a dataframe is filled with specific values, the reported `std` output by `describe` is NaN

**Steps/Code to reproduce bug**
```
import numpy as np
from dask import dataframe as dd

import cudf
import dask_cudf as dgd

df = cudf.DataFrame({
    'x': np.full((20,), 22642751, dtype=np.float),
    'y': np.full((20,), 22642751, dtype=np.float),
})
pdf = df.to_pandas()
ddf = dgd.from_cudf(df, npartitions=4)
pddf = dd.from_cudf(pdf, npartitions=4)
dd.assert_eq(ddf.describe(), pddf.describe(), check_less_precise=3)
```

**Expected behavior**
The reported `std` should be 0.0, as we see from the Pandas output instead of NaN

**Environment overview (please complete the following information)**
source build of branch-0.18

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 53ed28e91c71bd5f7413949c8cdaf0e3bbd0b5b8 (HEAD -> branch-0.18, tag: branch-0.18-latest, upstream/branch-0.18)
     Author: Mike Wendt <1915404+mike-wendt@users.noreply.github.com>
     Date:   Tue Feb 16 21:44:16 2021 -0500
     
     Update stale GHA with exemptions & new labels (#7395)
     
     Follows #7388
     
     Updates the stale GHA with the following changes:
     
     - [x] Uses `inactive-30d` and `inactive-90d` labels instead of `stale` and `rotten`
     - [x] Updates comments to reflect changes in labels
     - [x] Exempts the following labels from being marked `inactive-30d` or `inactive-90d`
     - `0 - Blocked`
     - `0 - Backlog`
     - `good first issue`
     
     Authors:
     - Mike Wendt (@mike-wendt)
     
     Approvers:
     - Keith Kraus (@kkraus14)
     - Ray Douglass (@raydouglass)
     
     URL: https://github.com/rapidsai/cudf/pull/7395
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=20.04
     DISTRIB_CODENAME=focal
     DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
     NAME="Ubuntu"
     VERSION="20.04.1 LTS (Focal Fossa)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 20.04.1 LTS"
     VERSION_ID="20.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=focal
     UBUNTU_CODENAME=focal
     Linux whicks-dt 5.8.0-36-generic #40~20.04.1-Ubuntu SMP Wed Jan 6 10:15:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Wed Feb 17 12:45:24 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Quadro RTX 8000     Off  | 00000000:15:00.0 Off |                  Off |
     | 33%   32C    P8    32W / 260W |    751MiB / 48601MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro RTX 8000     Off  | 00000000:2D:00.0 Off |                  Off |
     | 33%   38C    P8    22W / 260W |     18MiB / 48593MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |    0   N/A  N/A      1443      G   /usr/lib/xorg/Xorg                  4MiB |
     |    0   N/A  N/A    210588      C   .../envs/cudf_dev/bin/python      743MiB |
     |    1   N/A  N/A      1443      G   /usr/lib/xorg/Xorg                 10MiB |
     |    1   N/A  N/A      1722      G   /usr/bin/gnome-shell                4MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:                    x86_64
     CPU op-mode(s):                  32-bit, 64-bit
     Byte Order:                      Little Endian
     Address sizes:                   46 bits physical, 48 bits virtual
     CPU(s):                          12
     On-line CPU(s) list:             0-11
     Thread(s) per core:              2
     Core(s) per socket:              6
     Socket(s):                       1
     NUMA node(s):                    1
     Vendor ID:                       GenuineIntel
     CPU family:                      6
     Model:                           85
     Model name:                      Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
     Stepping:                        4
     CPU MHz:                         1387.290
     CPU max MHz:                     3700.0000
     CPU min MHz:                     1200.0000
     BogoMIPS:                        6800.00
     Virtualization:                  VT-x
     L1d cache:                       192 KiB
     L1i cache:                       192 KiB
     L2 cache:                        6 MiB
     L3 cache:                        19.3 MiB
     NUMA node0 CPU(s):               0-11
     Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
     Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable
     Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT vulnerable
     Vulnerability Meltdown:          Mitigation; PTI
     Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
     Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
     Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling
     Vulnerability Srbds:             Not affected
     Vulnerability Tsx async abort:   Mitigation; Clear CPU buffers; SMT vulnerable
     Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/whicks/anaconda3/envs/cudf_dev/bin/cmake
     cmake version 3.18.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 8.4.0-3ubuntu2) 8.4.0
     Copyright (C) 2018 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda-11.0/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Wed_Jul_22_19:09:09_PDT_2020
     Cuda compilation tools, release 11.0, V11.0.221
     Build cuda_11.0_bu.TC445_37.28845127_0
     
     ***Python***
     /home/whicks/anaconda3/envs/cudf_dev/bin/python
     Python 3.7.9
     
     ***Environment Variables***
     PATH                            : /usr/local/cuda-11.0/bin:/home/whicks/.yarn/bin:/home/whicks/.config/yarn/global/node_modules/.bin:/home/whicks/scripts:/home/whicks/bin:/home/whicks/rc/git_aliases:/usr/local/cuda/bin:/home/whicks/.yarn/bin:/home/whicks/.config/yarn/global/node_modules/.bin:/home/whicks/.nvm/versions/node/v12.18.4/bin:/home/whicks/scripts:/home/whicks/bin:/home/whicks/rc/git_aliases:/home/whicks/anaconda3/envs/cudf_dev/bin:/home/whicks/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/whicks/.fzf/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-11.0/lib64:/usr/local/cuda/lib64:
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/whicks/anaconda3/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/whicks/anaconda3/condabin/conda
     # packages in environment at /home/whicks/anaconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                        py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
     arrow-cpp                 1.0.1           py37h0d899e7_30_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-cal                 0.4.5                h2ff795d_6    conda-forge
     aws-c-common              0.4.67               h7f98852_0    conda-forge
     aws-c-event-stream        0.2.6                h4285e0c_4    conda-forge
     aws-c-io                  0.8.3                h3b39b8c_1    conda-forge
     aws-checksums             0.1.11               h3b39b8c_1    conda-forge
     aws-sdk-cpp               1.8.138              h9e0957a_1    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.3.0              pyh44b312d_0    conda-forge
     bokeh                     2.2.3            py37h89c1867_0    conda-forge
     boost-cpp                 1.75.0               hc6e9bd1_0    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_1    conda-forge
     cffi                      1.14.5           py37hc58025e_0    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   4.0.0            py37h89c1867_1    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.5               h1f3970d_0    rapidsai-nightly
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.4.4            py37hf1a17b8_0    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.0a0+253.g53ed28e91c.dirty          pypi_0    pypi
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py37h0ce7dbb_0    rapidsai
     cython                    0.29.21          py37hcd2ae1e_2    conda-forge
     cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
     dask                      2021.2.0+15.gf8d5f607          pypi_0    pypi
     dask-cudf                 branch-0.18-latest-0.g53ed28e91c.dirty          pypi_0    pypi
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2021.2.0+7.g383ea032          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37h89c1867_3    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37hcd2ae1e_3    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     execnet                   1.8.0              pyh44b312d_0    conda-forge
     expat                     2.2.10               h9c3ff4c_0    conda-forge
     fastavro                  1.3.2            py37h5e8e339_0    conda-forge
     fastrlock                 0.5              py37hcd2ae1e_2    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h0708190_1    conda-forge
     fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
     future                    0.18.2           py37h89c1867_3    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.35.0               h146f9af_0    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                6.2.0              pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  1.5.13             pyh44b312d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        3.4.0            py37h89c1867_0    conda-forge
     importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.4.2            py37h888b3d9_0    conda-forge
     ipython                   7.20.0           py37h888b3d9_2    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.18.0           py37h89c1867_2    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter_client            6.1.11             pyhd8ed1ab_1    conda-forge
     jupyter_core              4.7.1            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.12                 hddcbb42_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     libblas                   3.9.0                8_openblas    conda-forge
     libcblas                  3.9.0                8_openblas    conda-forge
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
     libgfortran-ng            9.3.0               hff62375_18    conda-forge
     libgfortran5              9.3.0               hff62375_18    conda-forge
     libgomp                   9.3.0               h2828fa1_18    conda-forge
     liblapack                 3.9.0                8_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.14.0               h780b84a_0    conda-forge
     librmm                    0.18.0a210217   cuda11.0_g99b5d86_36    rapidsai-nightly
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.2.0                hdc55705_0    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuv                     1.41.0               h7f98852_0    conda-forge
     libwebp-base              1.2.0                h7f98852_0    conda-forge
     llvmlite                  0.35.0           py37h9d7f4d0_1    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py37h5e8e339_3    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h5e8e339_1003    conda-forge
     more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
     mypy                      0.782                      py_0    conda-forge
     mypy_extensions           0.4.3            py37h89c1867_3    conda-forge
     nbclient                  0.5.2              pyhd8ed1ab_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
     nbsphinx                  0.8.1              pyh44b312d_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.2.0            py37h89c1867_0    conda-forge
     numba                     0.52.0           py37hdc94413_0    conda-forge
     numpy                     1.20.1           py37haa41c4c_0    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.3            py37h5e8e339_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1j               h7f98852_0    conda-forge
     orc                       1.6.7                h7950760_0    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.1.5            py37hdc94413_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.8.1              pyhd8ed1ab_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.1.0            py37h4600e1f_2    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37h89c1867_4    conda-forge
     pre-commit                2.10.1           py37h89c1867_0    conda-forge
     pre_commit                2.10.1               hd8ed1ab_0    conda-forge
     prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
     prompt-toolkit            3.0.16             pyha770c72_0    conda-forge
     protobuf                  3.14.0           py37hcd2ae1e_1    conda-forge
     psutil                    5.8.0            py37h5e8e339_1    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37h3dc597d_30_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.8.0              pyhd8ed1ab_0    conda-forge
     pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
     pyorc                     0.4.0                    pypi_0    pypi
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.3           py37h5e8e339_2    conda-forge
     pysocks                   1.7.1            py37h89c1867_3    conda-forge
     pytest                    6.2.2            py37h89c1867_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     pytest-forked             1.3.0              pyhd3deb0d_0    conda-forge
     pytest-xdist              2.2.1              pyhd8ed1ab_0    conda-forge
     python                    3.7.9           hffdb5ce_100_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.4.1            py37h5e8e339_0    conda-forge
     pyzmq                     22.0.3           py37h499b945_0    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
     regex                     2020.11.13       py37h5e8e339_1    conda-forge
     requests                  2.25.1             pyhd3deb0d_0    conda-forge
     rhash                     1.4.1                h7f98852_0    conda-forge
     rmm                       0.18.0a210217   cuda_11.0_py37_g99b5d86_36    rapidsai-nightly
     s2n                       0.10.26              h9b69904_0    conda-forge
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37h89c1867_3    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.1.0              pyhd8ed1ab_0    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.5.1              pyhd8ed1ab_0    conda-forge
     sphinx-copybutton         0.3.1              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.1              pyhd3deb0d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.2            py37h89c1867_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h5e8e339_1    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     typed-ast                 1.4.2            py37h5e8e339_0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
     virtualenv                20.4.2           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.4                h9c3ff4c_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.8                ha95c52a_1    conda-forge
     
</pre></details>

**Additional context**
I found this while working on tracking down another bug. I haven't done much to triage it, except confirming that this does *not* occur without Dask (e.g. on a direct call of `df.describe()` in the above.

**Comment by wphicks** [comment]
Just discovered that `84886781` also produces a mismatch, though in this case the reported `std` is not NaN; it's just wrong.

**Comment by pentschev** [comment]
The how how `dask_cudf` is computing `var`, which is in https://github.com/rapidsai/cudf/blob/dcf949caf895dbbcd936b21d372d4072b95be37e/python/dask_cudf/dask_cudf/core.py#L390-L425 and then https://github.com/rapidsai/cudf/blob/dcf949caf895dbbcd936b21d372d4072b95be37e/python/dask_cudf/dask_cudf/core.py#L353-L362 seem to be the problem resulting in numerical imprecisions for large numbers, see example below:

```python
In [1]: import cudf, dask_cudf, dask.dataframe as dd, dask.array as da, pandas as pd, numpy as np

In [2]: gdf = dask_cudf.from_cudf(cudf.Series([9.39590082e+08, 9.39590082e+08, 9.39590082e+08]), npartitions=1)

In [3]: gdf.var().compute()
Out[3]: -192.0

In [4]: a = np.array([9.39590082e+08, 9.39590082e+08, 9.39590082e+08])

In [5]: a.var()
Out[5]: 0.0

In [6]: x = a.sum()

In [7]: x2 = (a ** 2).sum()

In [8]: n = len(a)

In [9]: (x2 / n)
Out[9]: 8.828295221927666e+17

In [10]: (x / n) ** 2
Out[10]: 8.828295221927667e+17

In [11]: (x2 / n) - (x / n) ** 2
Out[11]: -128.0
```

The final result of `var` for the case above is a negative number, for which `np.sqrt` will be called in `std`, thus resulting in NaN.

I believe both the code in `dask_cudf` is taken from https://github.com/dask/dask/blob/895c9541044e16809151f0e3db95c48ea338c6d3/dask/bag/chunk.py#L20-L33. NumPy seems to compute using a different (but perhaps inefficient for distributed systems) way to compute it (see Notes in https://numpy.org/doc/stable/reference/generated/numpy.std.html), which is probably why it's not reproducible there.

**Comment by jakirkham** [comment]
cc @rjzamora (in case you have thoughts here 🙂)

**Comment by rjzamora** [comment]
Thank you for investigating this @pentschev - dask_cudf is clearly using a naive algorithm for var/std that is very easy to parallelize.  This approach is known to have numerical-stability issues (as you clearly demonstrated).

Perhaps it makes sense to use the parallel version of Welford's online algorithm [(Chan 79')](http://i.stanford.edu/pub/cstr/reports/cs/tr/79/773/CS-TR-79-773.pdf)?  I seem to get good results when I do something like the following in `dask_cudf.DataFrame.var`:

```python
            def _local_var(x, skipna):
                n = len(x)
                avg = x.mean(skipna=skipna)
                m2 = ((x - avg)**2).sum(skipna=skipna)
                return n, avg, m2

            def _aggregate_var(parts):
                n, avg, m2 = parts[0]
                for i in range(1, len(parts)):
                    n_a, avg_a, m2_a = n, avg, m2
                    n_b, avg_b, m2_b = parts[i]
                    n = n_a + n_b
                    avg = (n_a * avg_a + n_b * avg_b) / n
                    delta = avg_b - avg_a
                    m2 = m2_a + m2_b + delta ** 2 * n_a * n_b / n
                return m2 / (n - 1)

            dsk = {}
            name = "var-" + tokenize(axis, skipna, ddof, split_every, dtype, out)
            local_name = "local-" + name
            num = self._get_numeric_data()
            parts = []
            for n in range(num.npartitions):
                parts.append((local_name, n))
                dsk[parts[-1]] = (_local_var, (num._name, n), skipna)
            dsk[(name, 0)] = (_aggregate_var, parts)

            graph = HighLevelGraph.from_collections(name, dsk, dependencies=[num])
            return dd.core.new_dd_object(graph, name, meta, (None, None))
```
