### ISSUE TITLE
[QST] Why it took too long to run `cudf.Series`

### ISSUE THREAD

**Issue by ChenZhongPu** [rapidsai/cudf#7407]
I am new to `cudf`. After installing it, I try to run the examples following [10 Minutes to cuDF and Dask-cuDF](https://docs.rapids.ai/api/cudf/stable/10min.html).

I found that it took too long to run the simple `s = cudf.Series([1,2,3,None,4])`. Note that it does not report any error message, and I have to cancel the execution after waiting for more than 10 minutes. Anything wrong?

-----
OS: Ubuntu 18.04
GPU: RTX 3070
NVIDIA Driver: 460.32.03

The installing commands: `conda create -n rapids-core-0.17 -c rapidsai -c nvidia -c conda-forge  -c defaults cudf=0.17 python=3.7 cudatoolkit=10.1`

**Comment by davidwendt** [comment]
Comments in #7200 may be of help
https://github.com/rapidsai/cudf/issues/7200#issuecomment-765857621

**Comment by ChenZhongPu** [comment]
> Comments in #7200 may be of help
> [#7200 (comment)](https://github.com/rapidsai/cudf/issues/7200#issuecomment-765857621)

I have checked Comments in #7200 but my case seems much worse. 

In my case, any call of `cudf` cannot return any results (I try to wait for more than 10 minutes). To be specific, not just **took too long**, but **got stuck**.

**Comment by ChenZhongPu** [comment]
More information when executing `nvidia-smi`:

> +-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|             ID   ID                                                                      Usage      |
|=============================================================================|
|    0   N/A  N/A      1143      G   /usr/lib/xorg/Xorg                 40MiB |
|    0   N/A  N/A      1207      G   /usr/bin/gnome-shell               83MiB |
|    0   N/A  N/A      1555      G   /usr/lib/xorg/Xorg                573MiB |
|    0   N/A  N/A      1681      G   /usr/bin/gnome-shell              145MiB |
|    0   N/A  N/A      1897      G   ...2.1-linux-x86_64.AppImage       30MiB |
|    0   N/A  N/A      2431      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A      3168      G   /usr/lib/firefox/firefox            3MiB |
|    0   N/A  N/A      8291      G   gnome-control-center                3MiB |
|    0   N/A  N/A     15470      G   /opt/freedownloadmanager/fdm       37MiB |
|    0   N/A  N/A     16701      C   python                            331MiB |
+-----------------------------------------------------------------------------+

The last process is the one I am running for `cudf`.

**Comment by davidwendt** [comment]
It sounds like you are hitting a ptx jit recompilation.
https://github.com/rapidsai/cudf/issues/6999#issuecomment-743493537

**Comment by ChenZhongPu** [comment]
Cool, man. Thanks for your response. Using `cudatoolkit=11.0` solves the problem.

**Comment by davidwendt** [comment]
Glad you got it working.
