### ISSUE TITLE
[BUG] Illegal memory access to collision counter in concurrent_unordered_multimap

### ISSUE THREAD

**Issue by gaohao95** [rapidsai/cudf#7413]
**Describe the bug**
In `cpp/src/hash/concurrent_unordered_multimap.cuh`, member element `m_collisions` is [allocated in host memory](https://github.com/rapidsai/cudf/blob/593dc1c901686f96113a8259aa3742bd5a8dc2a9/cpp/src/hash/concurrent_unordered_multimap.cuh#L541), but the host pointer is passed to `atomicAdd` in device function `insert`, [here](https://github.com/rapidsai/cudf/blob/593dc1c901686f96113a8259aa3742bd5a8dc2a9/cpp/src/hash/concurrent_unordered_multimap.cuh#L340), and [here](https://github.com/rapidsai/cudf/blob/593dc1c901686f96113a8259aa3742bd5a8dc2a9/cpp/src/hash/concurrent_unordered_multimap.cuh#L349).

**Steps/Code to reproduce bug**
Any code using `concurrent_unordered_multimap` with `count_collisions` set to `true` should observe illegal memory access in the kernel.

**Comment by gaohao95** [comment]
> Since the `concurrent_unordered_multimap` is not public facing and the `count_collisions` functionality is not used internally, this will be fairly low priority to fix.

No problem at all. It's not a blocker for me as well. Just want to raise an issue here so that it can get tracked.

**Comment by jrhemstad** [comment]
> No problem at all. It's not a blocker for me as well. Just want to raise an issue here so that it can get tracked.

Thanks. I think this oversight is a holdover from when the `concurrent_unordered_multimap` object itself was allocated in managed memory.

**Comment by vyasr** [comment]
No longer relevant as of #10642.
