### ISSUE TITLE
[FEA] Add Python bindings for drop_list_duplicates

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#7414]
**Is your feature request related to a problem? Please describe.**
I wish I could deduplicate the elements in a column list. For example, applying the function to this dataframe:
0    [optimus, a, optimus]
1           [optimus, b]
2           [optimus, c]
Name: A, dtype: list

should output
0    [optimus, a]
1           [optimus, b]
2           [optimus, c]
Name: A, dtype: list

**Describe the solution you'd like**
In pandas you could use someting like `df.apply(lambda x: set(x['column_list']), axis=1)`. No sure which could be the best approach in cudf

**Describe alternatives you've considered**
```
text = ["Optimus a", 
        "Optimus b Optimus",
       "Optims c"]
df = cudf.DataFrame({'text':text,'doc_id':[0,1,2]})
tokens = df.text.str.tokenize(' ')
tk_cnts = df.text.str.token_count(' ')
global_pos = df.doc_id.repeat(tk_cnts).reset_index(drop=True)

tokenized_df = cudf.DataFrame({'token':tokens,'doc_id':global_pos})
tokenized_df['token_order']=1
tokenized_df['token_order'] = tokenized_df['token_order'].cumsum()

tokenized_df.columns = ['token_ser', 'output_column_id_ser', 'ouput_token_order_ser']
tokenized_df= tokenized_df.drop_duplicates(["token_ser","output_column_id_ser"])
tokenized_df["token_ser"] = tokenized_df["token_ser"].str.detokenize('output_column_id_ser')
```

**Comment by kkraus14** [comment]
I think this would make sense to expose as something like `cudf.Series.list.unique()` in cuDF Python

**Comment by ttnghia** [comment]
We have a new PR for `drop_list_duplicates` in cudf C++: https://github.com/rapidsai/cudf/pull/7528
Please work on the python side if necessary. Thanks.
