### ISSUE TITLE
[QST]docker build failed with dockerfile

### ISSUE THREAD

**Issue by senseb** [rapidsai/cudf#742]
**What is your question?**

Step 22/26 : RUN source activate cudf &&     mkdir -p /cudf/cpp/build &&     cd /cudf/cpp/build &&     cmake .. -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} &&     make -j install &&     make python_cffi &&     make install_python
 ---> Running in fc2619bea379
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- The CUDA compiler identification is unknown
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-5
-- Check for working CXX compiler: /usr/bin/g++-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- broken
CMake Error at /conda/envs/cudf/share/cmake-3.13/Modules/CMakeTestCUDACompiler.cmake:46 (message):
  The CUDA compiler

    "/usr/local/cuda/bin/nvcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /cudf/cpp/build/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_49543/fast"
    /usr/bin/make -f CMakeFiles/cmTC_49543.dir/build.make CMakeFiles/cmTC_49543.dir/build
    make[1]: Entering directory '/cudf/cpp/build/CMakeFiles/CMakeTmp'
    Building CUDA object CMakeFiles/cmTC_49543.dir/main.cu.o
    /usr/local/cuda/bin/nvcc     -x cu -c /cudf/cpp/build/CMakeFiles/CMakeTmp/main.cu -o CMakeFiles/cmTC_49543.dir/main.cu.o
    In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:179:0,
                     from /usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:50,
                     from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:78,
                     from <command-line>:0:
    /usr/include/features.h:367:25: fatal error: sys/cdefs.h: No such file or directory
    compilation terminated.
    CMakeFiles/cmTC_49543.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_49543.dir/main.cu.o' failed
    make[1]: *** [CMakeFiles/cmTC_49543.dir/main.cu.o] Error 1
    make[1]: Leaving directory '/cudf/cpp/build/CMakeFiles/CMakeTmp'
    Makefile:121: recipe for target 'cmTC_49543/fast' failed
    make: *** [cmTC_49543/fast] Error 2

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:18 (project)

**Comment by kkraus14** [comment]
@senseb Are you still having this issue? This looks to be an issue with nvidia-docker or docker as opposed to our library as it's erroring in just detecting a usable nvcc.

**Comment by harrism** [comment]
No response, closing.
