### ISSUE TITLE
[QST] Is cudf=0.19 on conda cloud ready to use

### ISSUE THREAD

**Issue by XiaoleiShi-NV** [rapidsai/cudf#7426]
Now we are using `cudf=0.17` with our project, but we plan to upgrade to `cudf=0.19` soon, is the `rapidsai-nightly/cudf=0.19` ready to use? We find the following error when compiling:
[log.txt](https://github.com/rapidsai/cudf/files/6027049/log.txt)

Two extra questions:

1. When will `cudf=0.19` officially be released?
2. Will `cudf=0.19` support CUDA 11.2?

**Comment by kkraus14** [comment]
1. The v0.19 release schedule is here: https://docs.rapids.ai/maintainers
2. We are working towards supporting CUDA 11.2 in v0.19 but it is not supported quite yet
