### ISSUE TITLE
[FEA] Warn when performance is inferior to pandas.

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#743]
**Is your feature request related to a problem? Please describe.**

Our current implementation is sub-optimal when the number of columns is large, as a python `Column` object needs to get allocated in serial for each column.

In a similar vein, when `groupby` is called with a large number of samples and a small number of classes, performance quadratically gets worse than pandas (#533).

**Describe the solution you'd like**
I propose that we add logging to appear during code execution if use cases such as `transpose` with a large number of columns or `groupby` is called with few classes and many samples.

**Describe alternatives you've considered**
Alternatively we can describe existing limitations in the RAPIDS documentation.

**Comment by jrhemstad** [comment]
> a large number of columns or groupby is called with few classes and many samples.

How would you detect this and give a warning? Is this a common use-case? Is it common and important enough that we should add an alternative implementation?

**Comment by thomcom** [comment]
In my opinion it is worth optimizing. Our modus operandi is "high performance dataframe manipulation of massive datasets". When pandas crushes our performance (#533) on a medium-large-ish dataset, I think it is worth creating a special case to handle that situation. Pandas clearly has.

Prioritizing #533 isn't my call by any means, and I'm fine with whatever the powers-that-be think are the highest priorities.

**Comment by thomcom** [comment]
Simple condition checks can be used if we want - `if numrows > 100000 and len(groupbycol[1:1000].unique() < 20` then `warn`. I can improve the resolution of the analysis to the point when pandas beats us and call that the threshold. It's just an idea.

**Comment by thomcom** [comment]
Why shouldn't we handle special cases automatically? It is fairly easy (and fun!) to define a threshold even across multiple parameters where the performance of one algorithm is superior.

**Comment by harrism** [comment]
I agree we should automate it. I like "minimal configuration" libraries that try to do a good job automatically but provide the knobs required to tune when the user is savvy enough to do so.

**Comment by randyzwitch** [comment]
I’d rather not have something like this, as a user can profile if they choose and/or this could be a documentation note. Having libraries throwing warnings is a lot of noise when nothing is technically wrong

**Comment by kkraus14** [comment]
Given the discussion has gone stale on this I'm going to close this issue.
