### ISSUE TITLE
[FEA] Enable lazy loading of python `Column` data and properties

### ISSUE THREAD

**Issue by thomcom** [rapidsai/cudf#744]
**Is your feature request related to a problem? Please describe.**

In order to improve performance with large dataframes, we should investigate lazy loading of objects when the user requests them, leaving them untouched on GPU the rest of the time. This is important because with when transposing a Dataframe with a large number of columns, `Column` allocation and `cffi_view` are the primary bottlenecks

**Describe the solution you'd like**

Treat pythonic `DataFrame`s and `Column`s as metadata containers whenever possible. When a specific range of data is requested, only the data required to perform the computation is accessed. In the current form we would allocate `Column` objects only when a request is made to perform python-level `DataFrame` calculations. For example, in `merge`, instead of creating `Column` objects for the resulting merge results, simply retain a reference to the results and compute the `Column` object when it is needed for i/o or a python-level stats operation.

**Describe alternatives you've considered**
Refactor python to allow `Row` based `DataFrame`s or `Column` based dataframes, depending on which is most efficient. This is probably an effective eventual solution, as real world data will (always?) be either very wide or very deep, but not both (and if it is both, it won't be computable).

**Additional context**
This FEA request is the product of a meeting between myself, @devavret, @jrhemstad, and @randerzander w.r.t. to slow performance of `transpose` in our existing architecture.

**Comment by devavret** [comment]
Additionally, an alternative considered was that we create a c++ side matrix for results of operations like transpose and in the vein of immutability, we allocate the whole `df` as a single block of memory and don't allow adding/removing columns. 
**Problems with this approach:**
- datatypes need to homogeneous across columns
- large changes required on python side.

**Comment by devavret** [comment]
The proposed solution would also take care of @kkraus14 's concerns about performance degradation when we register new columns with numba's garbage collection. No need to do it right away.

**Comment by kkraus14** [comment]
cc @mrocklin this has huge implications for Dask interoperability

**Comment by kkraus14** [comment]
Closing as this is stale.
