### ISSUE TITLE
[BUG] Multiple definition of `cudf::max_string_sentinel'

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#7455]
The constant array 
```
__constant__ char max_string_sentinel[5]{"\xF7\xBF\xBF\xBF"};
``` 
is defined in a header file (`device_operators.cuh`). Therefore, when that header is included multiple times in multiple, separate compilation units, we will have compiling error saying that there are multiple definitions of `max_string_sentinel`.

**Comment by davidwendt** [comment]
Where are you seeing this issue?
This constant is being moved to a different file in #7439

**Comment by ttnghia** [comment]
I have this issue when creating new tests in which that header is indirectly included. 
If https://github.com/rapidsai/cudf/pull/7439 can fix this then it's great.

**Comment by karthikeyann** [comment]
I tried extern while making it as `__constant__` but extern can't be used with these memory specifiers.
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#device-memory-specifiers

> When compiling in the whole program compilation mode (see the nvcc user manual for a description of this mode), __device__, __shared__, __managed__ and __constant__ variables cannot be defined as external using the extern keyword. The only exception is for dynamically allocated __shared__ variables as described in __shared__.

**Comment by ttnghia** [comment]
I see. Then we need to do something else to take that constant out of the header. According to https://nvidia.slack.com/archives/CDTANRCTT/p1614641342115500, we have a fix here: https://github.com/rapidsai/cudf/pull/7480

**Comment by mythrocks** [comment]
> I tried extern while making it as `__constant__` but extern can't be used with these memory specifiers.

`extern` would force external linkage. We would need the opposite. I can confirm that `static` works, in #7480. 

@karthikeyann, could I please bother you to review that change in #7480?
