### ISSUE TITLE
[FEA] Refactor aggregation APIs

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#7456]
Currently, aggregation APIs (groupby, reductions, rolling, etc.) are scattered around in multiple files and there are inconsistencies between the directory structures in `cpp/include/`, `cpp/src/`, `cpp/tests/`,  and `cpp/benchmarks/`. For example:

`cpp/include/`:
 * include/cudf/aggregation.hpp
 * include/cudf/groupby.hpp
 * include/cudf/rolling.hpp
 * ....

`cpp/src/`:
 * src/aggregation/*.*
 * src/groupby/*.*
 * src/rolling/*.*
 * ....

`cpp/tests/`:
 * tests/aggregation/*.*
 * tests/groupby/*.*
 * tests/grouped_rolling/*.*
 * tests/lead_lag/*.*
 * ....

I suggest to group all aggregation APIs together, so those APIs will be in `include/aggreation/*.*`, `src/aggregation/*.*`, `tests/aggregation/*.*` etc.

**Comment by harrism** [comment]
I think this should be covered as part of #7106 and #6895

**Comment by jrhemstad** [comment]
I don't think it makes sense to group everything that touches `aggregation` under a `aggregation/` directory. It's too broad a category to be useful. Grouping `groupby`,`reduction`,`scan`,`rolling`,etc. into the same directory is more harmful than helpful.

**Comment by ttnghia** [comment]
Yes, it would be complex to combine everything to one. So, how about make them sub-categories? For example, we can have
```
aggregation/grouby/
aggregation/reduction/
aggregation/rolling/
```

Grouping the related APIs together make things easier to access and refer to.

**Comment by jrhemstad** [comment]
I still think that hurts more than it helps. The fact that a very diverse set of algorithms share a common `aggregation` input parameter is an implementation detail. Adding another layer of indirection to group things by an implementation detail doesn't seem worth it.

**Comment by harrism** [comment]
Good point. Moreover, not all groupby operations are aggregations. Same goes for rolling. Suggest we close this as `wontfix`.
