### ISSUE TITLE
[FEA] Change ClangFormat line width configuration

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#7458]
Request: Change ClangFormat configuration to allow longer lines.
Reason: Please look at the following snippets:

```
cudf::column_view zero_size_column(
    cudf::data_type{cudf::type_id::FLOAT32}, 0, nullptr, nullptr, 0);
auto results = cudf::strings::from_floats(zero_size_column);
cudf::test::expect_strings_empty(results->view());
```

```
cudf::column_view zero_size_column(
    cudf::data_type{cudf::type_id::STRING}, 0, nullptr, nullptr, 0);
auto results =
    cudf::strings::to_floats(zero_size_column, cudf::data_type{cudf::type_id::FLOAT32});
EXPECT_EQ(0, results->size());
```

```
auto const result_fixed_window =
    rolling_window(input_column, 2, 1, 1, make_collect_list_aggregation());
CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(expected_result->view(), result_fixed_window->view());
```

```
auto const result_with_nulls_excluded =
    rolling_window(input_column, 2, 1, 1, make_collect_list_aggregation(null_policy::EXCLUDE));
```

```
if (has_nulls(keys)) {
    unique_keys =
      groupby_null_templated<true>(keys, requests, &cache, include_null_keys, stream, mr);
} else {
    unique_keys =
      groupby_null_templated<false>(keys, requests, &cache, include_null_keys, stream, mr);
}
```

And many many many similar examples out there. With short line limit, long code lines are broken into ugly, clumsy blocks. If we have the following format then it is fantastic:
```
cudf::column_view zero_size_column(cudf::data_type{cudf::type_id::FLOAT32}, 0, nullptr, nullptr, 0);
auto results = cudf::strings::from_floats(zero_size_column);
cudf::test::expect_strings_empty(results->view());
```

```
cudf::column_view zero_size_column(cudf::data_type{cudf::type_id::STRING}, 0, nullptr, nullptr, 0);
auto results = cudf::strings::to_floats(zero_size_column, cudf::data_type{cudf::type_id::FLOAT32});
EXPECT_EQ(0, results->size());
```

```
auto const result_fixed_window = rolling_window(input_column, 2, 1, 1, make_collect_list_aggregation());
CUDF_TEST_EXPECT_COLUMNS_EQUIVALENT(expected_result->view(), result_fixed_window->view());
```

```
auto const result_with_nulls_excluded = rolling_window(input_column, 2, 1, 1, make_collect_list_aggregation(null_policy::EXCLUDE));
```

```
if (has_nulls(keys)) {
    unique_keys = groupby_null_templated<true>(keys, requests, &cache, include_null_keys, stream, mr);
  } else {
    unique_keys = groupby_null_templated<false>(keys, requests, &cache, include_null_keys, stream, mr);
  }
```

Suggestion: Raise the column limit parameter to at least 150, instead of just 100 as the current limit. Two short lines will lead to more clumsy code and more lines in files, which makes us to use mouse scrolling a lot more, which also consumes a lot of time to scroll up and down all the time.

**Comment by harrism** [comment]
We had this discussion when we added clang-format. 100 lines was a good compromise length we arrived at.

Not everyone uses very wide editing windows or big monitors. More importantly, lines longer than 100 characters require horizontal scrolling in GitHub code reviews. We spend a *lot* of time in code reviews in this team, so I consider that a big issue.

I don't find any of the examples you shared clumsy, and I don't think the wide versions are fantastic.

**Comment by codereport** [comment]
> We spend a lot of time in code reviews in this team, so I consider that a big issue.

I can second this, there was a 60+ comment thread at one point. We decided on 100. 

![image](https://user-images.githubusercontent.com/36027403/109736635-ae05f600-7b92-11eb-9391-b8fa6c8309c5.png)

**Comment by ttnghia** [comment]
Thank you for letting me know. I will keep the issue open for a while so if anybody has the same thinking can see this.

**Comment by harrism** [comment]
Nah, let's close it.
