### ISSUE TITLE
[BUG] read_csv() segafults or raises an exception when reading a large file

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#746]
You can download the CSV file here:
ftp://ftp.ncdc.noaa.gov/pub/data/ghcn/daily/by_year/2017.csv.gz

Code to set up the repro:
names = ["id", "date", "type", "val", "time", "dummy1", "dummy2", "dummy3"]
dtypes = ['int' for name in names]

With an 8GB GPU, repro steps are the following:
* df = cudf.read_csv(fn, names=names, dtype=dtypes) -> segfault in line 497 (cudaMalloc of 8 bytes)
* df = cudf.read_csv(fn, names=names, dtype=dtypes, nrows=7000000) -> CUDA OOM error in line 1266 (cudaMalloc of 28000000 bytes)

At the time of failure the GPU still has more than 7GB of free memory.

Note the the behavior is expected to be different on different cards.

**Comment by jeaton32** [comment]
Looking at the file itself, it may be that one of the columns is mixing char and int data, and this is confusing the data type detector.  5th column  varies over (a,N,S,T,e,E,1,2,7) etc.

**Comment by vuule** [comment]
The failure happens before data parsing.
It looks like the issue is in the munmap() call, the size is wrong. I got the fix that works locally, will submit a PR if it checks out on another system too.

**Comment by kkraus14** [comment]
Fixed by #747.
