### ISSUE TITLE
[FEA] Python bindings for `lists::contains`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#7462]
https://github.com/rapidsai/cudf/pull/7039 introduces a `lists::contains` API that we should plumb through to Python. The Python API we want is probably something like:

```python
>>> s = cudf.Series([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
>>> s.list.contains(4)  # returns Series([False, True, True])
```

**Comment by kkraus14** [comment]
@skirui-source please do not close issues until the pull request is merged. Generally using the `fixes` keyword is the preferred way of having pill requests automatically close issues: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
