### ISSUE TITLE
[FEA] Python bindings for `lists::extract_lists_element`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#7464]
https://github.com/rapidsai/cudf/pull/5753 introduces `lists::extract_list_element` which we should plumb through to Python. 

I'm not sure what the Python API should look like. For example we could have:

```python
s = cudf.Series([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
s.list.extract(-1)  # returns Series([3, 5, 6])
```

or alternatively:

```python
s.list[-1]  # returns Series([3, 5, 6])
```

**Comment by kkraus14** [comment]
Should this return a `cudf.Scalar` object in the future once we have scalars for list types?
