### ISSUE TITLE
[FEA] Python bindings for `lists::segmented_gather`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#7465]
https://github.com/rapidsai/cudf/pull/7003 introduces `lists::segmented_gather` which we should plumb through to Python. 

I'm not sure what the Python API should look like. For example we could have:

```python
s = cudf.Series([[1, 2, 3], [3, 4, 5], [4, 5, 6]])
s.list.take([[0, 1], [2], [1, 2]])  # returns Series([[1, 2], [5], [5, 6]])
```

or alternatively:

```python
s.list[[[0, 1], [2], [1,  2]]]
```

cc: @kkraus14 if you have a preferred API as this was requested by you in https://github.com/rapidsai/cudf/issues/6542 :)

**Comment by kkraus14** [comment]
I'm in preference of `list.take` personally. `__getitem__` is too overloaded as it is.
