### ISSUE TITLE
[FEA] Add support for explode_outer

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#7466]
**Is your feature request related to a problem? Please describe.**
The Spark plugin would like to support explode_outer, which requires support from libcudf. This is an explode operation that does not remove empty lists or null entries, but instead represents them with nulls.

```
  a          b
null        100
[5, 6]      200
[]          300
[1, 2, 3]   400
```

would result in:
```
  a          b
null        100
5           200
6           200
null        300
1           400
2           400
3           400
```

**Comment by kkraus14** [comment]
cc @marlenezw @shwina for visibility. This is the behavior we'd want by default for `Series.explode` / `DataFrame.explode`.

**Comment by hyperbolic2346** [comment]
I'm not sure the origin of the nomenclature, but the goal is to bring the nulls and empty lists out into the result.
