### ISSUE TITLE
[QST] problem with importing cuDF

### ISSUE THREAD

**Issue by Mashael0x** [rapidsai/cudf#7472]
**What is your question?**
I am running [colab_notebook](https://colab.research.google.com/drive/1rY7Ln6rEE1pOlfSHCYOVaqt8OvDO35J0#forceEdit=true&offline=true&sandboxMode=true) from rapidsai website, I set the notebook to use gpu and make sure it is one of the three GPUs required to run the code and haven't changed anything in the code. but this problem keeps occuring to me.
I searched in the internet but it seems no one faces this problem..

![Screenshot (1139)](https://user-images.githubusercontent.com/70824363/109506121-57bf8700-7aae-11eb-9f72-6d4895bd228e.png)

**Comment by galipremsagar** [comment]
What is the version you are on? This seems to be an outdated version of `cudf`, can you upgrade your `cudf` to the latest version?

**Comment by kkraus14** [comment]
@Mashael0x Colab recently updated to Python 3.7 and CUDA 11.2 which allows cuDF to be supported again. We are working on building an updated Colab installer and hope to have it released in the near future.

cc @taureandyernv to update once it's released

**Comment by taureandyernv** [comment]
@Mashael0x @kkraus14 @beckernick , the update to Colab is live

**Comment by Mashael0x** [comment]
> @Mashael0x @kkraus14 @beckernick , the update to Colab is live. RAPIDS versions are 0.18 and 0.19 are running on Colab. Be sure to update the installation script for Python 3.7 (an example is provided)

thank you for informing me, I switched to jupyter lab but I will try installing rapids again in google colab
