### ISSUE TITLE
[BUG] cuDF makes an alias in the case where Pandas makes a copy

### ISSUE THREAD

**Issue by magnatelee** [rapidsai/cudf#7487]
**Describe the bug**
In Pandas, every assignment of a series to a dataframe on a column name, whether the name is fresh or not, copies the series. In cuDF, however, the assignment introduces an alias to the series, through which all the future updates are visible. 

**Steps/Code to reproduce bug**
In Pandas, any updates to `y` aren't visible to its copy `x`.
```
>>> x = pd.DataFrame({"x" : [1,2,3], "y" : [4,5,6]})
>>> x["x"] = x["y"]
>>> x.loc[:, "y"] = 100
>>> x
   x    y
0  4  100
1  5  100
2  6  100
```
In cuDF, `x` and `y` are pointing to the same buffer, and any updates to one are propagated to the other.
```
>>> x = pd.DataFrame({"x" : [1,2,3], "y" : [4,5,6]})
>>> x["x"] = x["y"]
>>> x.loc[:, "y"] = 100
>>> x
     x    y
0  100  100
1  100  100
2  100  100
```

**Expected behavior**
cuDF creating an alias in this case is understandable from the performance standpoint, but needs to implement at least COW in order to be consistent with Pandas.

**Comment by shwina** [comment]
Note that Pandas makes a copy regardless (i.e., it doesn't employ any copy-on-write semantics):

```python
In [28]: df = pd.DataFrame({'a': [1, 2, 3]})

In [29]: df['b'] = df['a']

In [30]: df['b'].values.__array_interface__
Out[30]:
{'data': (94855343235584, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3,),
 'version': 3}

In [31]: df['a'].values.__array_interface__
Out[31]:
{'data': (94855343362816, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (3,),
 'version': 3}
```

IMO, not making a copy here unless necessary (e.g., when aligning indexes) sounds preferable. Someone wanting a copy can specify that explicitly:

```python
 >>> x = cudf.DataFrame({"x" : [1,2,3], "y" : [4,5,6]})
>>> x["x"] = x["y"].copy()
>>> x.loc[:, "y"] = 100
```

If we do decide at some point to make a copy instead, it'll be important to note that there's many places internally where we build up DataFrames from Series objects. We'll likely need to rewrite those bits of code to avoid this copying behaviour (e.g., by building the DataFrame from the underlying Column objects instead).

**Comment by vyasr** [comment]
Given the moves in pandas and cudf towards copy-on-write functionality, I think we can close this as the behaviors will naturally be aligned as of pandas 3.0.
