### ISSUE TITLE
[BUG] "Runtime compilation failed" exception thrown in cudf after importing gevent

### ISSUE THREAD

**Issue by benfred** [rapidsai/cudf#7496]
**Describe the bug**

Running cudf code can fail with either a ```Runtime compilation failed``` or ```NVRTC error: NVRTC_ERROR_COMPILATION```  (depending on environment) after importing gevent. The same code works fine without the gevent import.

We hit this issue in NVTabular when importing the ```tritonclient.http``` package - which in turn [imports gevent](https://github.com/triton-inference-server/server/blob/27580311abd9390fda8cd436257bb474bc830299/src/clients/python/library/tritonclient/http/__init__.py#L30) (see https://github.com/NVIDIA/NVTabular/issues/616)(https://github.com/NVIDIA/NVTabular/issues/616)

**Steps/Code to reproduce bug**

On the ```rapidsai/rapidsai:cuda11.0-runtime-ubuntu20.04-py3.8``` container - go ```pip install gevent``` and then run this test script:

```python
import cudf
import tempfile
import os
import shutil

# remove cached kernels
shutil.rmtree(os.path.expanduser("~/.cudf"), ignore_errors=True)

import gevent


def write_parquet_dataset(outputdir):
    df = cudf.datasets.timeseries(
        start="2000-01-01",
        end="2000-01-04",
        freq="60s",
        dtypes={
            "id": int,
        },
    ).reset_index()

    half = int(len(df) // 2)

    filenames = [os.path.join(outputdir, f"dataset-{i}.parquet") for i in range(2)]
    df.iloc[:half].to_parquet(filenames[0], chunk_size=1000)
    df.iloc[half:].to_parquet(filenames[1], chunk_size=1000)
    return filenames


with tempfile.TemporaryDirectory() as outputdir:
    filenames = write_parquet_dataset(outputdir)
    dfs = [cudf.read_parquet(f) for f in filenames]
    df = cudf.concat(dfs, axis=0)

    # this line fails with a RuntimeError: NVRTC error: NVRTC_ERROR_COMPILATION
    # (but doesn't fail if we don't import gevent above)
    df["id"] = df["id"].astype("int64")
```

This throws an exception like:

```
Traceback (most recent call last):
  File "test.py", line 34, in <module>
    df["id"] = df["id"].astype("int64")
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/dataframe.py", line 763, in __setitem__
    value = Series(value)._align_to_index(
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/series.py", line 4396, in _align_to_index
    if self.index.equals(index):
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/index.py", line 210, in equals
    return super(Index, self).equals(other, check_types=check_types)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/frame.py", line 564, in equals
    if not self_col.equals(other_col, check_dtypes=check_types):
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 169, in equals
    return (self == other).min()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/column.py", line 1127, in __eq__
    return self.binary_operator("eq", other)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 119, in binary_operator
    return _numeric_column_binop(
  File "/opt/conda/envs/rapids/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/cudf/core/column/numerical.py", line 679, in _numeric_column_binop
    out = libcudf.binaryop.binaryop(lhs, rhs, op, out_dtype)
  File "cudf/_lib/binaryop.pyx", line 209, in cudf._lib.binaryop.binaryop
  File "cudf/_lib/binaryop.pyx", line 107, in cudf._lib.binaryop.binaryop_v_v
RuntimeError: Runtime compilation failed
```

**Expected behavior**
Process should exit successfully 

**Environment overview (please complete the following information)**

 - Environment location: Docker
 - Method of cuDF install: Docker
   ```docker pull rapidsai/rapidsai:cuda11.0-runtime-ubuntu20.04-py3.8 ```
   ```docker run --rm -it   --gpus "device=all" rapidsai/rapidsai:cuda11.0-runtime-ubuntu20.04-py3.8 /bin/bash```

**Comment by kkraus14** [comment]
@benfred do you happen to know if `gevent` forks the process or something along those lines? CUDA is not fork safe and importing `cudf` I believe initializes the CUDA driver and a CUDA context which then can cause issues when forking.

Alternatively this may be fixed by #xxxx.

**Comment by benfred** [comment]
Thanks for the suggestions!

I spent some time trying to figure out whats going on here, but didn't get very far:

*  I built the 0.19 branch from source this morning, and it still has this issue - so I don't think #7510 fixes.  
* I don’t see any forked processes,  new threads or changes in environment variables when importing gevent. 
* Compiling cudf with [JITIFY_PRINT_LOG defined](https://github.com/rapidsai/jitify/blob/e3f867027c1d9603b5a677795900465b9fac9cb8/jitify.hpp#L2376-L2382) prints out these JIT compile errors (which I didn't find all that helpful, but including just in case it helps you):
```
---------------------------------------------------
--- JIT compile log for  ---
---------------------------------------------------
detail/libcxx/include/limits(344): error: floating constant is out of range

detail/libcxx/include/limits(396): error: floating constant is out of range

2 errors detected in this compilation.

---------------------------------------------------
``` 
* Building gevent from source (with the rapids container environment w/ ```apt install gcc  build-essential```) doesn’t have this issue - but the gevent wheels on pypi do
* Trying to ablate the gevent install (by commenting stuff out until it works / doesn’t work)  - show that its something to do with some of the gevent cython modules.  After importing these modules there is a phantom ‘_cython_3_0a6’ in sys.modules - indicating that the wheels distributed are being built with a prerelease version of cython . However,  compiling gevent from source using ```Cython==3.0a6``` still works though - so this seems unrelated. Since I can't build these cython modules myself and still have the errors happen - I couldn't triage farther than this, but do think its related to code [like this](https://github.com/gevent/gevent/blob/master/src/gevent/_greenlet_primitives.py#L131-L132) in gevent.

Our core problem was trying to get the triton inference server client working alongside cudf - and we've found 2 workarounds to achieving this(compiling gevent from source / using the tritonclient.grpc package instead of tritonclient.http). Given that - this bug isn't all that high priority for us, so feel free to close this if you want .

**Comment by kkraus14** [comment]
> Building gevent from source (with the rapids container environment w/ apt install gcc build-essential) doesn’t have this issue - but the gevent wheels on pypi do

Have you tried with a conda install of `gevent`? This sounds like a possible C++ versioning conflict between the gevent wheels and the conda environment in which case there's not much that we can do.

**Comment by benfred** [comment]
Installing gevent with conda also works (``` conda install -c conda-forge gevent```)  - so I'm going to close this issue. Thanks for all your help!
