### ISSUE TITLE
[FEA] Support converting dataframes containing decimal columns to cupy or other format

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#7511]
Our codepath to coerce to a CuPy array eventually hits a call to `np.issubdtype`, which currently fails for Decimal columns because numpy doesn't recognize the data type.

As a user, I may want to convert a dataframe containing Decimal columns to a CuPy array or some other format (even if they are coerced to floats), perhaps as input to a machine learning model. 

Related to #7440 and https://github.com/rapidsai/cuml/issues/3580

```python
import cudf
import pyarrow as pa
​
df = cudf.DataFrame({
    "a":[0.1,0.2,0.9],
    "b":[0.3,0.9,20],
})
​
pa_decimal_b = df.b.to_arrow().cast(pa.decimal128(precision=7, scale=2))
df["b"] = cudf.core.column.DecimalColumn.from_arrow(pa_decimal_b)
​
df.as_gpu_matrix()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-53-e1af0d2555bd> in <module>
     10 df["b"] = cudf.core.column.DecimalColumn.from_arrow(pa_decimal_b)
     11 
---> 12 df.as_gpu_matrix()

/raid/nicholasb/miniconda3/envs/rapids-gpu-bdb-automated-tests/lib/python3.7/site-packages/cudf/core/dataframe.py in as_gpu_matrix(self, columns, order)
   3545         if any(
   3546             (is_categorical_dtype(c) or np.issubdtype(c, np.dtype("object")))
-> 3547             for c in cols
   3548         ):
   3549             raise TypeError("non-numeric data not yet supported")

/raid/nicholasb/miniconda3/envs/rapids-gpu-bdb-automated-tests/lib/python3.7/site-packages/cudf/core/dataframe.py in <genexpr>(.0)
   3545         if any(
   3546             (is_categorical_dtype(c) or np.issubdtype(c, np.dtype("object")))
-> 3547             for c in cols
   3548         ):
   3549             raise TypeError("non-numeric data not yet supported")

/raid/nicholasb/miniconda3/envs/rapids-gpu-bdb-automated-tests/lib/python3.7/site-packages/numpy/core/numerictypes.py in issubdtype(arg1, arg2)
    386     """
    387     if not issubclass_(arg1, generic):
--> 388         arg1 = dtype(arg1).type
    389     if not issubclass_(arg2, generic):
    390         arg2 = dtype(arg2).type

TypeError: Cannot interpret '<cudf.core.column.decimal.DecimalColumn object at 0x7f1c045d3200>' as a data type
```

**Comment by shwina** [comment]
Would it work to explicitly cast decimal -> int/float, and then convert to a CuPy array? For cuDF to do this implicitly sounds like a potential source of other bugs.

**Comment by dantegd** [comment]
@shwina so would the proposed solution be for cuDF's `.values` or `.as_gpu_matrix` to err (with an informative error) in the case of decimal columns and leave conversions to the user?

**Comment by shwina** [comment]
Yes -- I'm aware that's likely not the case today :)

**Comment by beckernick** [comment]
When I filed this, I expected that exact response @shwina 😄 . In the cuml input utilities, there is a call to `_as_gpu_matrix` which would error (today and in the future). I think ideally, a user could smoothly pass dataframes with Decimal columns to the ML estimator, like in PySpark. Perhaps this kind of conversion might be better suited inside cuML?

**Comment by shwina** [comment]
> When I filed this, I expected that exact response @shwina 😄

My main fear is if we do this, it opens up the possibility of subtle bugs sneaking into users' code -- for example, floating-point arithmetic inadvertently being employed instead of fixed-point, or fixed-point columns "mysteriously" disappearing after certain operations.

**Comment by dantegd** [comment]
> When I filed this, I expected that exact response @shwina smile . In the cuml input utilities, there is a call to `as_gpu_matrix` which would error (today and in the future). I think ideally, a user could smoothly pass dataframes with Decimal columns to the ML estimator, like in PySpark. Perhaps this kind of conversion might be better suited inside cuML as part of the flexibile input tooling?

That should be pretty easy in cuML, though due to the implementation of most algorithms, currently that'll mean convert all Decimal/fixed point columns to floating point probably.

**Comment by beckernick** [comment]
No longer relevant, closing
