### ISSUE TITLE
[BUG] scatter_by_map does not work correctly

### ISSUE THREAD

**Issue by dmitra79** [rapidsai/cudf#7513]
scatter_by_map is supposed to "use map_index to determine the destination of each row of the original DataFrame."
The output should be a list of frames with all the records for a specific index value.
This used to work in earlier version (ex. 0.10)
Now however, the dataframes in the list have multiple different values in the index column

**Steps/Code to reproduce bug**
I am having trouble coming up with a small reproducible example.
What I have is a cudf DataFrame with many numeric columns and a single 'id' column:

```
> df.dtypes
vp_m             float64
va_m             float64
vb_m             float64
vc_m             float64
vp_a             float64
va_a             float64
vb_a             float64
vc_a             float64
ip_m             float64
ia_m             float64
ib_m             float64
ic_m             float64
ip_a             float64
ia_a             float64
ib_a             float64
ic_a             float64
f                float64
df               float64
utc       datetime64[ns]
status             int32
id                object
dtype: object
```

I call:
```
id_df_list = df.scatter_by_map(df['id'])
[print(x['id'].unique()) for x in id_df_list]
```
and I get the output of length 42, which is correct in my case, but the assignments are wrong in that each dataframe contains multiple different values in 'id' column.

Output:
```
0    B337
1    B567
2    B608
3    B939
Name: id, dtype: object
0    B193
1    B608
Name: id, dtype: object
0    B161
1    B193
2    B326
3    B703
Name: id, dtype: object
....
```

**Environment overview (please complete the following information)**
I am on ubuntu 18, cudf 0.15.
Python 3.8.6
Conda install

**Comment by dmitra79** [comment]
I think I have a simplified example of the problem:
```
import cudf
import numpy as np

temp= cudf.DataFrame()
temp['id'] = ['B'+str(10*i) for i in range(42)]*100
temp['val'] = np.random.random(42*100) 
print(temp.head())
print(temp.dtypes)
gr=temp.scatter_by_map(temp['id'])
print(len(gr))
#[print(x['id'].unique()) for x in gr]
print(gr[0].head())
```
The output is:
```
    id       val
0   B0  0.622897
1  B10  0.556713
2  B20  0.727283
3  B30  0.635668
4  B40  0.841739
id      object
val    float64
dtype: object
42
        id       val
3342  B310  0.454540
1800  B360  0.353106
3956  B400  0.251557
1892  150B  0.324376
2467  60B3  0.045864
```
This clearly shows that the dataframes in output list do not have rows grouped by 'id' (even though the size of the list matched the number of unique elements in 'id' column)

**Comment by dmitra79** [comment]
It doesn't work with integer columns as well:
```
temp= cudf.DataFrame()
temp['id'] =  [i for i in range(100,142)]*100 
temp['val'] = np.random.random(42*100) 
print(temp.head())
print(temp.dtypes)
gr=temp.scatter_by_map(temp['id'])
print(len(gr))
print(gr[0].head())
```
results in:
```
    id       val
0  100  0.456549
1  101  0.649196
2  102  0.315516
3  103  0.027266
4  104  0.471647
id       int64
val    float64
dtype: object
42
Empty DataFrame
Columns: [id, val]
Index: []
```
Only the last dataframe in 'gr' contains data, the rest are empty

**Comment by shwina** [comment]
@dmitra79 -- thank you for reporting. As a workaround, are you able to use `groupby`?

Instead of:

```python
gr = temp.scatter_by_map(temp['id'])
```

You could do:

```python
gr = list(temp.groupby(temp['id']))
```

I'm looking into the problem with `scatter_by_map`, but please keep in mind that `scatter_by_map` is not an API that Pandas supports, so cuDF may also decide not to support it at some point in the future.

**Comment by dmitra79** [comment]
@shwina , thank you for the suggestion of using groupby -  that does seem to work for me.

**Comment by dmitra79** [comment]
If the scatter_by_map is no longer supported, this should be documented (and it should be removed from the API)

**Comment by wence-** [comment]
This error is a consequence of passing a partitioning map to `scatter_by_map` whose values are not in `[0, num_partitions)`.  In this case there are 42 partitions but the values are in the range `[100, 142)`.

In the C++ interface this restriction is documented:

>  Values in `partition_map` must be in the range `[0, num_partitions)`, otherwise behavior is undefined.

However it is not documented in the Python API (which might also check for validity).

**Comment by wence-** [comment]
For the string example, this looks to be an integer type casting issue (either in cudf, or libcudf). Strings are `scatter_by_map`ed by going via a categorical column's integer `codes`.

Simpler reproducer:
```python
import cudf
import numpy as np
df = cudf.DataFrame({"id": np.asarray([i % 2 for i in range(129)]).astype("int8"), "val": np.arange(129)})

a, b = df.scatter_by_map(df["id"])
assert len(a["id"].unique()) == 1 ## fails
assert len(b["id"].unique()) == 2 ## fails
```

If I first upcast the `df["id"]` to an `int32` (say), things work.

**Comment by wence-** [comment]
> For the string example, this looks to be an integer type casting issue (either in cudf, or libcudf).

This is a bug in libcudf...

**Comment by davidwendt** [comment]
Not sure if this relevant but valid values for `int8` are from -128 to 127 and so the `range(129)` looks invalid to me since it would include 128.
