### ISSUE TITLE
[BUG] contiguous_split can crash when an output partition exceeds 2GB

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#7514]
**Describe the bug**
When contiguous_split is directed to build an output partition of a size > 2GB then one of the following can occur:
- An exception is thrown with the message: `cuDF failure at: workspace/spark/cudf18_nightly/cpp/src/copying/pack.cpp:113: Encountered column data outside the range of input buffer`
- GPU crash with illegal memory access

**Steps/Code to reproduce bug**
1. Build up a table with columns that are rather large, e.g.: between 1 to 2GB each.
1. Make sure the table has enough of these columns to exceed 2GB of total space then add yet one more of these large columns to the table
1. Call `contiguous_split` with no split indices, i.e.: generate only one output partition consisting of the entire input table

**Expected behavior**
`contiguous_split` should not crash

**Environment overview (please complete the following information)**
cudf 0.18 run with the RAPIDS Accelerator for Apache Spark

**Comment by nvdbaranec** [comment]
PR coming shortly for 0.19
