### ISSUE TITLE
[gpuCI] The check "gpuCI/cudf/pr-builder" can not be triggered.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#7519]
I have a PR https://github.com/rapidsai/cudf/pull/7457 and the check `gpuCI/cudf/pr-builder` has not started automatically. And it can not even be triggered manually.

May I know how to trigger the check  `gpuCI/cudf/pr-builder` ? I tried the comment "`rerun tests`" but failed.

The merging now is blocked by this check.

**Comment by kkraus14** [comment]
This is because you are not on the whitelist for gpuCI. There was a comment in the PR from the bot asking an admin to approve. Closing this issue.
