### ISSUE TITLE
[FEA] enable iteration over cudf series

### ISSUE THREAD

**Issue by lastephey** [rapidsai/cudf#7521]
Hi cuDF developers,

**Is your feature request related to a problem? Please describe.**
I am not sure if this is a feature request or bug, but I would like to be able to iterate over a cuDF series. I am using cuDF 0.19.

Here is a sample that demonstrates what I mean:

```
stephey@cgpu19:~$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dask
>>> import dask_cudf
>>> import cudf
>>> df = dask.datasets.timeseries()
>>> df_id_cpu = df['id']
>>> cpu_loop = [i for i in df_id_cpu]
>>> df_gpu = df.map_partitions(cudf.from_pandas)
>>> df_id_gpu = df_gpu['id']
>>> gpu_loop = [i for i in df_id_gpu]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/app/miniconda3/lib/python3.8/site-packages/dask/dataframe/core.py", line 3055, in __iter__
    for row in s:
  File "/app/miniconda3/lib/python3.8/site-packages/cudf/core/series.py", line 877, in __iter__
    cudf.utils.utils.raise_iteration_error(obj=self)
  File "/app/miniconda3/lib/python3.8/site-packages/cudf/utils/utils.py", line 388, in raise_iteration_error
    raise TypeError(
TypeError: Series object is not iterable. Consider using `.to_arrow()`, `.to_pandas()` or `.values_host` if you wish to iterate over the values.

```

**Describe the solution you'd like**
I would like to be able to iterate over a cudf series the same way I can in pandas:

```
>>> df_gpu = df.map_partitions(cudf.from_pandas)
>>> df_id_gpu = df_gpu['id']
>>> gpu_loop = [i for i in df_id_gpu]
```

**Describe alternatives you've considered**
One option is to convert from a cudf series to a cupy array, although this is much slower in my application than using `to_pandas()`.

**Additional context**
Using `.to_pandas()` is a workable option, although I'm trying to keep all my work on the GPU if possible. 

Please let me know if I can answer questions or provide any other information.

Thank you very much,
Laurie

**Comment by galipremsagar** [comment]
> **Additional context**
> Using `.to_pandas()` is a workable option, although I'm trying to keep all my work on the GPU if possible.

In your example above why do you want to be iterating over a GPU-backed series object? Also, we see that you are trying to convert a `Series` object to a list for which the best way to do it is via `to_pandas().tolist()`. The reason iterating over a GPU-backed series object is disabled is because it is quite slower when compared to iterating over a CPU-backed series object. 

Maybe it would be helpful for us to help you with your next operation if you can provide what you want to do with the iterable?

**Comment by lastephey** [comment]
Thank you for the information-- this is helpful. Now I understand why iterating in this way would be slow/disabled, but then it might be nice to have a more informative error message. 

I'm trying to do something like:

```
image = cp.zeros((10,10))
for i, j in zip(df_id_gpu, df_id_gpu):
    image[i, j] += 1.0
```

where I use the values in the cudf series `df_id_gpu` to populate an image. 

What's the best strategy in this situation? Thank you.

**Comment by galipremsagar** [comment]
You can achieve that operation by keeping all the data on GPU memory:

```python
>>> import cudf
>>> import cupy as cp
>>> df_id_gpu = cudf.Series([0, 1, 2, 3, 4, 5])
>>> image = cp.zeros((10,10))
>>> df_id_gpu
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64
>>> image
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
>>> df_id_gpu.values
array([0, 1, 2, 3, 4, 5])
>>> image[df_id_gpu.values, df_id_gpu.values] += 1
>>> image
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
```

**Comment by lastephey** [comment]
Thank you very much for this solution-- this strategy is exactly what I wanted to know. 

I appreciate your time. I'll go ahead and close.

**Comment by mohandeepzumen** [comment]
I'm doing a different operation where i have a spell check method and each of the word in the cell has to go through this spellCheck method. I'm not able to iterate through every cell. Tried doing .topandas().tolist(), but the performance remains the same. Is there a way i can iterate through each cell in a series?

**Comment by shwina** [comment]
@mohandeepzumen can you show us what your `spellcheck` method looks like?

**Comment by mohandeepzumen** [comment]
def spellCheck(word,model):
    if word in model.words:
        pass
    else:
        w = model.get_nearest_neighbors(word, k=1)[0][1]

the model here refers to a fasttext model trained on a corpus of text.
