### ISSUE TITLE
[QST] Is it possible to install rapids in a Jetson Xavier AGX?

### ISSUE THREAD

**Issue by JJavierga** [rapidsai/cudf#7529]
Does RAPIDS support that kind of architecture? If it does, can you tell me where to get some guidelines?

Thank you

**Comment by alborotogarcia** [comment]
@JJavierga yes, I made it working, but first you'd need to build pyarrow-1.0.1 on GPU, and then follow this guide

https://gist.github.com/heavyinfo/da3de9b188d41570f4e988ceb5d81abc

however cuml and cugraph won't AFAIK..

**Comment by JJavierga** [comment]
Thank you very much. I needed the cuml part, so I'll look for other alternatives.

**Comment by kkraus14** [comment]
Closing as this is answered.
