### ISSUE TITLE
[BUG] conda env libthrift version mismatch

### ISSUE THREAD

**Issue by wbadart** [rapidsai/cudf#7539]
**Describe the bug**
Installing `cudf=0.18` via conda installs `libthrift=0.14.1` as a dependency. However, it seems that `cudf` is looking specifically for version `0.14.0`, so importing fails:

```
In [1]: import cudf
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/wbadar/.local/opt/miniconda3/envs/foo/lib/python3.8/site-packages/cudf/__init__.py", line 69, in <module>
    from cudf.io import (
  File "/home/wbadar/.local/opt/miniconda3/envs/foo/lib/python3.8/site-packages/cudf/io/__init__.py", line 9, in <module>
    from cudf.io.parquet import (
  File "/home/wbadar/.local/opt/miniconda3/envs/foo/lib/python3.8/site-packages/cudf/io/parquet.py", line 9, in <module>
    from pyarrow import dataset as ds, parquet as pq
  File "/home/wbadar/.local/opt/miniconda3/envs/foo/lib/python3.8/site-packages/pyarrow/dataset.py", line 24, in <module>
    from pyarrow._dataset import (  # noqa
ImportError: libthrift.so.0.14.0: cannot open shared object file: No such file or directory
```

**Steps/Code to reproduce bug**
```sh
conda create -n foo -c rapidsai -c nvidia -c conda-forge -c defaults cudf=0.18 python=3.8 cudatoolkit=11.0 --yes
conda activate foo
python -c 'import cudf'
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Environment details**

<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 53929eb7ce03954a7b107a2e08639da3447b0ecf (HEAD -> branch-0.19, tag: branch-0.19-latest, origin/branch-0.19, origin/HEAD)
     Author: rwlee <rwlee@users.noreply.github.com>
     Date:   Tue Mar 9 01:22:18 2021 -0800
     
     Remove detail from device_span (#7533)
     
     Fix for issue caused by stale PR issue from #7406
     
     Authors:
     - @rwlee
     - Keith Kraus (@kkraus14)
     
     Approvers:
     - Keith Kraus (@kkraus14)
     - Mike Wilson (@hyperbolic2346)
     - GALI PREM SAGAR (@galipremsagar)
     - Jake Hemstad (@jrhemstad)
     - Vukasin Milovanovic (@vuule)
     - Paul Taylor (@trxcllnt)
     
     URL: https://github.com/rapidsai/cudf/pull/7533
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux <...> 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Mar  9 14:20:18 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 450.102.04   Driver Version: 450.102.04   CUDA Version: 11.0     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  Off  | 00000000:61:00.0 Off |                    0 |
     | N/A   34C    P0    55W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  Off  | 00000000:62:00.0 Off |                    0 |
     | N/A   34C    P0    53W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  Off  | 00000000:89:00.0 Off |                    0 |
     | N/A   33C    P0    54W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
     | N/A   34C    P0    56W / 300W |      0MiB / 32510MiB |      5%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              40
     On-line CPU(s) list: 0-39
     Thread(s) per core:  2
     Core(s) per socket:  10
     Socket(s):           2
     NUMA node(s):        2
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
     Stepping:            7
     CPU MHz:             1035.838
     CPU max MHz:         2201.0000
     CPU min MHz:         1000.0000
     BogoMIPS:            4400.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            14080K
     NUMA node0 CPU(s):   0-9,20-29
     NUMA node1 CPU(s):   10-19,30-39
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
     
     ***CMake***
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     
     ***Python***
     /home/wbadar/.local/opt/miniconda3/envs/foo/bin/python
     Python 3.8.8
     
     ***Environment Variables***
     PATH                            : /home/wbadar/.local/opt/miniconda3/envs/foo/bin:/home/wbadar/.local/opt/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/wbadar/.local/opt/miniconda3/envs/foo
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/wbadar/.local/opt/miniconda3/condabin/conda
     # packages in environment at /home/wbadar/.local/opt/miniconda3/envs/foo:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200923.3           h9c3ff4c_0    conda-forge
     arrow-cpp                 1.0.1           py38h1ee4e12_33_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     aws-c-cal                 0.4.5                h76129ab_8    conda-forge
     aws-c-common              0.5.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7                h6bac3ce_1    conda-forge
     aws-c-io                  0.9.1                ha5b09cb_1    conda-forge
     aws-checksums             0.1.11               h99e32c3_3    conda-forge
     aws-sdk-cpp               1.8.151              hceb1b1e_1    conda-forge
     boost-cpp                 1.72.0               h9d3c048_4    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h7f98852_1    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py38h578d9bd_1    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudf                      0.18.0          cuda_11.0_py38_g20778e5ddb_0    rapidsai
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py38hb7c6141_0    rapidsai
     dlpack                    0.3                  he1b5a44_1    conda-forge
     fastavro                  1.3.2            py38h497a2fe_0    conda-forge
     fastrlock                 0.5              py38h709712a_2    conda-forge
     fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     grpc-cpp                  1.36.2               h7919d58_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     libblas                   3.9.0                8_openblas    conda-forge
     libcblas                  3.9.0                8_openblas    conda-forge
     libcudf                   0.18.0          cuda11.0_g20778e5ddb_0    rapidsai
     libcurl                   7.75.0               hc4aaa36_0    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
     libgfortran-ng            9.3.0               hff62375_18    conda-forge
     libgfortran5              9.3.0               hff62375_18    conda-forge
     libgomp                   9.3.0               h2828fa1_18    conda-forge
     liblapack                 3.9.0                8_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libprotobuf               3.15.5               h780b84a_0    conda-forge
     librmm                    0.18.0          cuda11.0_ga4ee6b7_0    rapidsai
     libssh2                   1.9.0                ha56f1ee_6    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
     libthrift                 0.14.1               he6d91bd_1    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     llvmlite                  0.35.0           py38h4630a5e_1    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     numba                     0.52.0           py38h51da96c_0    conda-forge
     numpy                     1.20.1           py38h18fd61f_0    conda-forge
     nvtx                      0.2.3            py38h497a2fe_0    conda-forge
     openssl                   1.1.1j               h7f98852_0    conda-forge
     orc                       1.6.7                heec2584_1    conda-forge
     pandas                    1.1.5            py38h51da96c_0    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     protobuf                  3.15.5           py38h709712a_0    conda-forge
     pyarrow                   1.0.1           py38h7b0d817_33_cuda    conda-forge
     python                    3.8.8           hffdb5ce_0_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2021.1             pyhd8ed1ab_0    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     rmm                       0.18.0          cuda_11.0_py38_ga4ee6b7_0    rapidsai
     s2n                       1.0.0                h9b69904_0    conda-forge
     setuptools                49.6.0           py38h578d9bd_3    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.9                ha95c52a_0    conda-forge
     
</pre></details>

**Comment by kkraus14** [comment]
Fixed by https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/128

May take a bit to propagate.

**Comment by wbadart** [comment]
Awesome, thanks Kieth 👍
