### ISSUE TITLE
[FEA] Add equi-join support for structs

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#7543]
There is no current way to run a join using a struct column. It would be nice to support this in cudf. This will probably leverage some of the work from #7422.

**Describe the solution you'd like**
It would certainly be nice to support arbitrary depths, but based on #7422 it might require a first-pass at a single depth and a later PR to add support for more depths.

Of particular concern is handling of NaN, Inf, -Inf, etc. These should be handled exactly the same as if the comparison was made between columns of the types inside the structs, so this should be fairly straight forward. The other concern is null handling. Join has the option of nulls comparing equal or not based on incoming parameters. There is some potential for issues around nulls here and care needs to be taken with the implementation.

A null struct would not be the same as a struct with all null entries.

**Comment by jrhemstad** [comment]
> It would certainly be nice to support arbitrary depths, but based on #7422 it might require a first-pass at a single depth

We should clarify what this means. "Arbitrary depths" should not mean a struct that contains arbitrarily nested list type(s). But multiple levels of `struct`, e.g., `struct< int, struct<int, float> >`.

Arbitrary levels of structs can be handled trivially in the same way as https://github.com/rapidsai/cudf/pull/7422 by exploding the struct parent columns' null masks into `bool` columns and then handling the struct column as extra columns in the table.

**Comment by nvdbaranec** [comment]
Do you even need to expand the null masks into seperate columns?  If a struct has a null mask, all of it's children will also have a null mask with everything pushed down.  Seems like all you need to do is just flatten all the columns into one big table_view and use that for comparison.

**Comment by jrhemstad** [comment]
> Do you even need to expand the null masks into seperate columns? If a struct has a null mask, all of it's children will also have a null mask with everything pushed down. Seems like all you need to do is just flatten all the columns into one big table_view and use that for comparison.

I had the same idea in sorting, but [Bobby reminded me why that won't work](https://github.com/rapidsai/cudf/issues/7226#issuecomment-772645974).

The key is that you need to be able to differentiate `null` from `{null, null, null}`, i.e., a null struct vs a struct of all nulls. 

Though actually... I wonder if we actually have the same problem in join, especially if nulls are considered unequal.
