### ISSUE TITLE
[BUG] cudf.read_parquet row_group argument does not seem to work

### ISSUE THREAD

**Issue by dmitra79** [rapidsai/cudf#7559]
**Describe the bug**

I have some large snappy-compressed parquet files (~1000MB) each: ~64M rows, ~24 string columns (mostly numeric underneath, with one timestamp column). Loading the whole file seem to be just over my GPU memory limits.  However, when I worked with these files previously (about a year ago, cudf=0.8 or so), I was  able to load them using using row_groups and processes them piece by piece.

Now, when I try to read a specific row_group,  I  get a memory error:
```
MemoryError                               Traceback (most recent call last)
<ipython-input-28-80c97b273caf> in <module>
----> 1 rg_df = cudf.read_parquet(in_fp, row_group=0)

~/anaconda3/envs/mindsynchro/lib/python3.8/site-packages/cudf/io/parquet.py in read_parquet(filepath_or_buffer, engine, columns, row_groups, skip_rows, num_rows, strings_to_categorical, use_pandas_metadata, *args, **kwargs)
    205 
    206     if engine == "cudf":
--> 207         return libparquet.read_parquet(
    208             filepaths_or_buffers,
    209             columns=columns,

cudf/_lib/parquet.pyx in cudf._lib.parquet.read_parquet()

cudf/_lib/parquet.pyx in cudf._lib.parquet.read_parquet()

MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:68: cudaErrorMemoryAllocation out of memory
```

It is as though the row_group argument gets ignored...

**Expected behavior**
I expect cudf.read_parquet(in_fp, row_group=0) to successfully load data for a single group.

**Environment overview (please complete the following information)**
- ubuntu 18
- conda install
- cudf 0.15 (also tried with 0.18 with same result)

**Comment by kkraus14** [comment]
@galipremsagar any chance you can look into this?

@dmitra79 what GPU are you trying to read the data into? How much memory is available when trying to read? Could you share data for us to try to reproduce the behavior you're seeing?

**Comment by galipremsagar** [comment]
@dmitra79 I think we have changed the `row_group` parameter to `row_groups`, so can you pass in the parameter as a list of integers?:

https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.io.parquet.read_parquet

**Comment by dmitra79** [comment]
@galipremsagar   You are right - I didn't notice that change. With corrected argument name it works with an 'int' as well:
```
cudf.read_parquet(in_fp, row_groups=0)
```
Thank you!
