### ISSUE TITLE
[BUG]Output jar and libcudf.so size is abnormal when build cudf use build-in-docker.sh 

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#7567]
**Describe the bug**
I use `java/ci/build-in-docker.sh` to build cudf jar, and i only modified the `PARALLEL_LEVEL=${PARALLEL_LEVEL:-20} `,  and finally build success, but ouput the cudf jar size only 72M, and cpp/build/libcudf.so only 308M, and i confirmed this is not normal , because i download cudf-jar from https://oss.sonatype.org ,cudf-0.19-SNAPSHOT-cudf.jar size is about 260M
**Steps/Code to reproduce bug**
OS: CentOS7
command: scl enable devtoolset-7 "java/ci/build-in-docker.sh"
cudf version : latest

**Comment by chenrui17** [comment]
I modified the PARALLEL_LEVEL to default value 4, build time is too long , output libcudf.so and cudf jar size return to normal, i don't know what happend. any advise ?

**Comment by jlowe** [comment]
I've used that script successfully with different parallelism settings, and I cannot explain how the parallelism would resultin. a different build output size.

The most likely explanation of a smaller libcudf.so being produced without errors is that it didn't build for all supported GPU architectures.  Do you have the log available from that suspicious build or are you able to provide the jar or libcudf.so from that build?  I'm curious what the log lines said for what CUDA version it was building against and what architectures it was building for, e.g.:
```
-- CUDF: CUDA_VERSION: 10.1
-- CUDF: Building CUDF for GPU architectures: 60-real;70-real;75
```

**Comment by chenrui17** [comment]
> I've used that script successfully with different parallelism settings, and I cannot explain how the parallelism would resultin. a different build output size.
> 
> The most likely explanation of a smaller libcudf.so being produced without errors is that it didn't build for all supported GPU architectures. Do you have the log available from that suspicious build or are you able to provide the jar or libcudf.so from that build? I'm curious what the log lines said for what CUDA version it was building against and what architectures it was building for, e.g.:
> 
> ```
> -- CUDF: CUDA_VERSION: 10.1
> -- CUDF: Building CUDF for GPU architectures: 60-real;70-real;75
> ```

Check the log , it seems to be the problem, my log is :
-- CUDF: CUDA_VERSION: 10.2
-- CUDF: Building CUDF for GPU architectures: 60-real

**Comment by chenrui17** [comment]
In cpp/CMakeLists.txt , i deleted below code ,and set(CUDF_BUILD_FOR_ALL_ARCHS TRUE), and the problem is temporary solved
```
if(NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
  set(CUDF_BUILD_FOR_ALL_ARCHS TRUE)
elseif(CMAKE_CUDA_ARCHITECTURES STREQUAL "")
  unset(CMAKE_CUDA_ARCHITECTURES CACHE)
  set(CUDF_BUILD_FOR_DETECTED_ARCHS TRUE)
endif()
```
