### ISSUE TITLE
[BUG] setup.py files contain the wrong Python versions

### ISSUE THREAD

**Issue by mike-wendt** [rapidsai/cudf#7578]
**Describe the bug**
The `setup.py` files in the folders within the [/python](https://github.com/rapidsai/cudf/tree/branch-0.19/python) directory contain the following snippets:

```
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
```
We currently only support 3.7/3.8

**Steps/Code to reproduce bug**
Examine these files:
- https://github.com/rapidsai/cudf/blob/branch-0.19/python/dask_cudf/setup.py#L21-L22
- https://github.com/rapidsai/cudf/blob/branch-0.19/python/cudf_kafka/setup.py#L84-L85
- https://github.com/rapidsai/cudf/blob/branch-0.19/python/custreamz/setup.py#L23-L24
- https://github.com/rapidsai/cudf/blob/branch-0.19/python/cudf/setup.py#L141-L142

**Expected behavior**
To be updated to match the current supported Python versions

**Environment overview (please complete the following information)**
 - Environment location: N/A found in source code
 - Method of cuDF install: N/A found in source code

**Environment details**
N/A

**Additional context**
N/A

**Comment by kkraus14** [comment]
@galipremsagar minor issue that can be fixed as part of the larger `setup.py` cleanup
