### ISSUE TITLE
[FEA] Python bindings for `lists::drop_list_duplicates`

### ISSUE THREAD

**Issue by shwina** [rapidsai/cudf#7582]
https://github.com/rapidsai/cudf/pull/7528 introduces a `lists::drop_list_duplicates` API that we should plumb through to Python. The Python API we want is probably something like:

```python
>>> s = cudf.Series([[4, 2, 2, 9], [8, 8, 2], [2, 1]])
>>> s.list.unique()  # returns Series([[4, 2, 9], [8, 2], [2, 1]])
```

**Comment by kkraus14** [comment]
Assigned you @skirui-source since it should be similar to the other list APIs you're plumbing through, thanks!

**Comment by kkraus14** [comment]
Closing as duplicate of #7414
