### ISSUE TITLE
[QST] Where are the C libraries?

### ISSUE THREAD

**Issue by snunez1** [rapidsai/cudf#7597]
The [top level rapids documentation](https://docs.rapids.ai/api) says about libcudf:

> libcudf is a C/C++ CUDA library for implementing standard dataframe operations.

If there is a C (not C++) API is sure is well hidden. Can someone point me in the direction of a libcudf with a C interface? I'll build it if necessary.

**Comment by jrhemstad** [comment]
There are no C interfaces for libcudf. The description as a "C/C++" library is imprecise. It's only a CUDA C++ library

**Comment by snunez1** [comment]
Is a C API on the roadmap?

**Comment by jrhemstad** [comment]
No, it is not on our roadmap at this time. The effort to develop and maintain a C interface would be very high and there hasn't been significant justification to do so.
