### ISSUE TITLE
[FEA] Python bindings for `column_view::child`

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#7608]
cpp has already supported [extracting child columns by index](https://github.com/rapidsai/cudf/blob/branch-0.19/cpp/include/cudf/column/column_view.hpp#L344) for a column of nested type.  It will be much helpful to plumb through to Python.

What's more, [it exists in JNI already](https://github.com/rapidsai/cudf/blob/branch-0.19/java/src/main/native/src/ColumnViewJni.cpp#L1535).

I'm not sure what the Python API should look like. For example we could have:
```
s = cudf.Series([{"a": 1, "b": "s1"}, {"a": 2, "b": "s2"}])
s.struct.a  # returns Series([1, 2])
s.struct.b  # returns Series(["s1", "s2"])
```
or alternatively:
```
s.struct[0]  # returns Series([1, 2])
s.struct[1]  # returns Series(["s1", "s2"])
```

**Comment by kkraus14** [comment]
PyArrow does this via a `field` operator that can take in either a name of the column or the position, where I think it would make sense for us to follow:
```
s = cudf.Series([{"a": 1, "b": "s1"}, {"a": 2, "b": "s2"}])

s.struct.field('a') # returns Series([1, 2])
s.struct.field(0) # returns Series([1, 2])

s.struct.field('b') # returns Series(["s1", "s2"])
s.struct.field(1) # returns Series(["s1", "s2"])
```

**Comment by skirui-source** [comment]
Not sure why this issue is still open? @kkraus14

**Comment by kkraus14** [comment]
> Not sure why this issue is still open? @kkraus14

Not sure, closing, thanks @skirui-source!
