### ISSUE TITLE
[BUG] Specifying DataFrame column labels from Index results in error 

### ISSUE THREAD

**Issue by laceyg** [rapidsai/cudf#7613]
**Describe the bug**
When creating a cudf DataFrame, passing the column labels as a pandas or cudf Index object results in an error. The equivalent operation in pandas works fine.

**Steps/Code to reproduce bug**
```
import pandas as pd
import cudf

# works correctly
temp = pd.DataFrame([[1, 2, 3, 4]], columns=pd.Index(['A', 'B', 'C', 'D']))

# both of these result in error
temp = cudf.DataFrame([[1, 2, 3, 4]], columns=cudf.Index(['A', 'B', 'C', 'D']))
temp = cudf.DataFrame([[1, 2, 3, 4]], columns=pd.Index(['A', 'B', 'C', 'D']))
```

```
...
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
```

**Expected behavior**
I would expect the Index object to specify the column labels successfully.

**Environment overview (please complete the following information)**
 - Environment location: DGX Station
 - Method of cuDF install: 
 
 `docker pull rapidsai/rapidsai-core:0.18-cuda10.1-runtime-ubuntu18.04-py3.8`

 `docker run -it --rm -w /home/$USER -v /home/$USER:/home/$USER -v /data:/data -p 8888:8888 -p 8787:8787 rapidsai/rapidsai-core:0.18-cuda10.1-runtime-ubuntu18.04-py3.8`

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     Not inside a git repository
     
     ***OS Information***
     DGX_NAME="DGX Station"
     DGX_PRETTY_NAME="NVIDIA DGX Station"
     DGX_SWBUILD_DATE="2017-10-31"
     DGX_SWBUILD_VERSION="3.1.3"
     DGX_COMMIT_ID="31e745794370d852fdb0a178ef022a872f58efdf"
     DGX_SERIAL_NUMBER="0154517000028"
     
     DGX_OTA_VERSION="3.1.6"
     DGX_OTA_DATE="Thu Apr 19 12:57:07 EDT 2018"
     
     DGX_OTA_VERSION="3.1.7"
     DGX_OTA_DATE="Mon Nov 19 10:52:14 EST 2018"
     
     DGX_OTA_VERSION="4.0.4"
     DGX_OTA_DATE="Thu Jan  3 15:26:33 EST 2019"
     
     DGX_OTA_VERSION="4.0.6"
     DGX_OTA_DATE="Thu Jun 20 13:26:29 EDT 2019"
     
     DGX_OTA_VERSION="4.0.7"
     DGX_OTA_DATE="Tue Feb  4 13:49:07 EST 2020"
     
     DGX_R418_REPO_ENABLED=20200721-145240
     
     DGX_OTA_VERSION="4.5.0"
     DGX_OTA_DATE="Tue Jul 21 15:15:54 EDT 2020"
     
     DGX_OTA_VERSION="4.6.0"
     DGX_OTA_DATE="Tue Oct 27 14:02:14 EDT 2020"
     
     DGX_OTA_VERSION="4.7.0"
     DGX_OTA_DATE="Mon Jan 25 15:28:00 EST 2021"
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux DGX 4.15.0-134-generic #138-Ubuntu SMP Fri Jan 15 10:52:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Tue Mar 16 15:00:00 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 418.181.07   Driver Version: 418.181.07   CUDA Version: 10.1     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Tesla V100-DGXS...  On   | 00000000:07:00.0  On |                    0 |
     | N/A   31C    P0    50W / 300W |   3588MiB / 16125MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-DGXS...  On   | 00000000:08:00.0 Off |                    0 |
     | N/A   31C    P0    36W / 300W |     12MiB / 16128MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-DGXS...  On   | 00000000:0E:00.0 Off |                    0 |
     | N/A   31C    P0    36W / 300W |     12MiB / 16128MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-DGXS...  On   | 00000000:0F:00.0 Off |                    0 |
     | N/A   32C    P0    35W / 300W |     12MiB / 16128MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    0      2531      G   /usr/lib/xorg/Xorg                            27MiB |
     |    0      2694      G   /usr/bin/gnome-shell                          99MiB |
     |    0     17381      C   /opt/conda/envs/rapids/bin/python           1145MiB |
     |    0     22386      C   /opt/conda/envs/rapids/bin/python            995MiB |
     |    0     37194      C   /opt/conda/envs/rapids/bin/python           1309MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              40
     On-line CPU(s) list: 0-39
     Thread(s) per core:  2
     Core(s) per socket:  20
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               79
     Model name:          Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
     Stepping:            1
     CPU MHz:             1199.290
     CPU max MHz:         3600.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            4397.43
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            256K
     L3 cache:            51200K
     NUMA node0 CPU(s):   0-39
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts md_clear flush_l1d
     
     ***CMake***
     /usr/bin/cmake
     cmake version 3.10.2
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Sun_Jul_28_19:07:16_PDT_2019
     Cuda compilation tools, release 10.1, V10.1.243
     
     ***Python***
     /home/griffin/anaconda3/bin/python
     Python 3.8.3
     
     ***Environment Variables***
     PATH                            : /home/griffin/bin:/home/griffin/.local/bin:/usr/local/cuda/bin:/opt/bin:/usr/local/cuda/bin:/home/griffin/bin:/home/griffin/.local/bin:/home/griffin/anaconda3/bin:/home/griffin/anaconda3/condabin:/usr/local/cuda/bin:/opt/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
     LD_LIBRARY_PATH                 :
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/griffin/anaconda3
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/griffin/anaconda3/bin/conda
     # packages in environment at /home/griffin/anaconda3:
     #
     # Name                    Version                   Build  Channel
     _ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
     _libgcc_mutex             0.1                        main
     alabaster                 0.7.12                     py_0
     anaconda                  2020.07                  py38_0
     anaconda-client           1.7.2                    py38_0
     anaconda-navigator        1.9.12                   py38_0
     anaconda-project          0.8.4                      py_0
     argh                      0.26.2                   py38_0
     asn1crypto                1.3.0                    py38_0
     astroid                   2.4.2                    py38_0
     astropy                   4.0.1.post1      py38h7b6447c_1
     atomicwrites              1.4.0                      py_0
     attrs                     19.3.0                     py_0
     autopep8                  1.5.3                      py_0
     babel                     2.8.0                      py_0
     backcall                  0.2.0                      py_0
     backports                 1.0                        py_2
     backports.functools_lru_cache 1.6.1                      py_0
     backports.shutil_get_terminal_size 1.0.0                    py38_2
     backports.tempfile        1.0                        py_1
     backports.weakref         1.0.post1                  py_1
     beautifulsoup4            4.9.1                    py38_0
     bitarray                  1.4.0            py38h7b6447c_0
     bkcharts                  0.2                      py38_0
     blas                      1.0                         mkl
     bleach                    3.1.5                      py_0
     blosc                     1.19.0               hd408876_0
     bokeh                     2.1.1                    py38_0
     boto                      2.49.0                   py38_0
     bottleneck                1.3.2            py38heb32a55_1
     brotlipy                  0.7.0           py38h7b6447c_1000
     bzip2                     1.0.8                h7b6447c_0
     ca-certificates           2020.6.24                     0
     cairo                     1.14.12              h8948797_3
     certifi                   2020.6.20                py38_0
     cffi                      1.14.0           py38he30daa8_1
     chardet                   3.0.4                 py38_1003
     click                     7.1.2                      py_0
     cloudpickle               1.5.0                      py_0
     clyent                    1.2.2                    py38_1
     colorama                  0.4.3                      py_0
     conda                     4.9.2            py38h578d9bd_0    conda-forge
     conda-build               3.18.11                  py38_0
     conda-env                 2.6.0                         1
     conda-package-handling    1.6.1            py38h7b6447c_0
     conda-verify              3.4.2                      py_1
     contextlib2               0.6.0.post1                py_0
     cryptography              2.9.2            py38h1ba5d50_0
     curl                      7.71.1               hbc83047_1
     cycler                    0.10.0                   py38_0
     cython                    0.29.21          py38he6710b0_0
     cytoolz                   0.10.1           py38h7b6447c_0
     dask                      2.20.0                     py_0
     dask-core                 2.20.0                     py_0
     dbus                      1.13.16              hb2f20db_0
     decorator                 4.4.2                      py_0
     defusedxml                0.6.0                      py_0
     diff-match-patch          20200713                   py_0
     distributed               2.20.0                   py38_0
     docutils                  0.16                     py38_1
     entrypoints               0.3                      py38_0
     et_xmlfile                1.0.1                   py_1001
     expat                     2.2.9                he6710b0_2
     fastcache                 1.1.0            py38h7b6447c_0
     filelock                  3.0.12                     py_0
     flake8                    3.8.3                      py_0
     flask                     1.1.2                      py_0
     fontconfig                2.13.0               h9420a91_0
     freetype                  2.10.2               h5ab3b9f_0
     fribidi                   1.0.9                h7b6447c_0
     fsspec                    0.7.4                      py_0
     future                    0.18.2                   py38_1
     get_terminal_size         1.0.0                haa9412d_0
     gevent                    20.6.2           py38h7b6447c_0
     glib                      2.65.0               h3eb4bd4_0
     glob2                     0.7                        py_0
     gmp                       6.1.2                h6c8ec71_1
     gmpy2                     2.0.8            py38hd5f6e3b_3
     graphite2                 1.3.14               h23475e2_0
     greenlet                  0.4.16           py38h7b6447c_0
     gst-plugins-base          1.14.0               hbbd80ab_1
     gstreamer                 1.14.0               hb31296c_0
     h5py                      2.10.0           py38h7918eee_0
     harfbuzz                  2.4.0                hca77d97_1
     hdf5                      1.10.4               hb1b8bf9_0
     heapdict                  1.0.1                      py_0
     html5lib                  1.1                        py_0
     icu                       58.2                 he6710b0_3
     idna                      2.10                       py_0
     imageio                   2.9.0                      py_0
     imagesize                 1.2.0                      py_0
     importlib-metadata        1.7.0                    py38_0
     importlib_metadata        1.7.0                         0
     intel-openmp              2020.1                      217
     intervaltree              3.0.2                      py_1
     ipykernel                 5.3.2            py38h5ca1d4c_0
     ipython                   7.16.1           py38h5ca1d4c_0
     ipython_genutils          0.2.0                    py38_0
     ipywidgets                7.5.1                      py_0
     isort                     4.3.21                   py38_0
     itsdangerous              1.1.0                      py_0
     jbig                      2.1                  hdba287a_0
     jdcal                     1.4.1                      py_0
     jedi                      0.17.1                   py38_0
     jeepney                   0.4.3                      py_0
     jinja2                    2.11.2                     py_0
     joblib                    0.16.0                     py_0
     jpeg                      9b                   h024ee3a_2
     json5                     0.9.5                      py_0
     jsonschema                3.2.0                    py38_0
     jupyter                   1.0.0                    py38_7
     jupyter_client            6.1.6                      py_0
     jupyter_console           6.1.0                      py_0
     jupyter_core              4.6.3                    py38_0
     jupyterlab                2.1.5                      py_0
     jupyterlab_server         1.2.0                      py_0
     keyring                   21.2.1                   py38_0
     kiwisolver                1.2.0            py38hfd86e86_0
     krb5                      1.18.2               h173b8e3_0
     lazy-object-proxy         1.4.3            py38h7b6447c_0
     lcms2                     2.11                 h396b838_0
     ld_impl_linux-64          2.33.1               h53a641e_7
     libarchive                3.4.2                h62408e4_0
     libcurl                   7.71.1               h20c2e04_1
     libedit                   3.1.20191231         h14c3975_1
     libffi                    3.3                  he6710b0_2
     libgcc-ng                 9.1.0                hdf63c60_0
     libgfortran-ng            7.3.0                hdf63c60_0
     liblief                   0.10.1               he6710b0_0
     libllvm9                  9.0.1                h4a3c616_1
     libpng                    1.6.37               hbc83047_0
     libsodium                 1.0.18               h7b6447c_0
     libspatialindex           1.9.3                he6710b0_0
     libssh2                   1.9.0                h1ba5d50_1
     libstdcxx-ng              9.1.0                hdf63c60_0
     libtiff                   4.1.0                h2733197_1
     libtool                   2.4.6                h7b6447c_5
     libuuid                   1.0.3                h1bed415_2
     libxcb                    1.14                 h7b6447c_0
     libxml2                   2.9.10               he19cac6_1
     libxslt                   1.1.34               hc22bd24_0
     llvmlite                  0.33.0           py38hc6ec683_1
     locket                    0.2.0                    py38_1
     lxml                      4.5.2            py38hefd8a0e_0
     lz4-c                     1.9.2                he6710b0_0
     lzo                       2.10                 h7b6447c_2
     markupsafe                1.1.1            py38h7b6447c_0
     matplotlib                3.2.2                         0
     matplotlib-base           3.2.2            py38hef1b27d_0
     mccabe                    0.6.1                    py38_1
     mistune                   0.8.4           py38h7b6447c_1000
     mkl                       2020.1                      217
     mkl-service               2.3.0            py38he904b0f_0
     mkl_fft                   1.1.0            py38h23d657b_0
     mkl_random                1.1.1            py38h0573a6f_0
     mock                      4.0.2                      py_0
     more-itertools            8.4.0                      py_0
     mpc                       1.1.0                h10f8cd9_1
     mpfr                      4.0.2                hb69a4c5_1
     mpmath                    1.1.0                    py38_0
     msgpack-python            1.0.0            py38hfd86e86_1
     multipledispatch          0.6.0                    py38_0
     navigator-updater         0.2.1                    py38_0
     nbconvert                 5.6.1                    py38_0
     nbformat                  5.0.7                      py_0
     ncurses                   6.2                  he6710b0_1
     networkx                  2.4                        py_1
     nltk                      3.5                        py_0
     nose                      1.3.7                    py38_2
     notebook                  6.0.3                    py38_0
     numba                     0.50.1           py38h0573a6f_1
     numexpr                   2.7.1            py38h423224d_0
     numpy                     1.18.5           py38ha1c710e_0
     numpy-base                1.18.5           py38hde5b4d6_0
     numpydoc                  1.1.0                      py_0
     olefile                   0.46                       py_0
     openpyxl                  3.0.4                      py_0
     openssl                   1.1.1g               h7b6447c_0
     packaging                 20.4                       py_0
     pandas                    1.0.5            py38h0573a6f_0
     pandoc                    2.10                          0
     pandocfilters             1.4.2                    py38_1
     pango                     1.45.3               hd140c19_0
     parso                     0.7.0                      py_0
     partd                     1.1.0                      py_0
     patchelf                  0.11                 he6710b0_0
     path                      13.1.0                   py38_0
     path.py                   12.4.0                        0
     pathlib2                  2.3.5                    py38_0
     pathtools                 0.1.2                      py_1
     patsy                     0.5.1                    py38_0
     pcre                      8.44                 he6710b0_0
     pep8                      1.7.1                    py38_0
     pexpect                   4.8.0                    py38_0
     pickleshare               0.7.5                 py38_1000
     pillow                    7.2.0            py38hb39fc2d_0
     pip                       20.1.1                   py38_1
     pixman                    0.40.0               h7b6447c_0
     pkginfo                   1.5.0.1                  py38_0
     pluggy                    0.13.1                   py38_0
     ply                       3.11                     py38_0
     prometheus_client         0.8.0                      py_0
     prompt-toolkit            3.0.5                      py_0
     prompt_toolkit            3.0.5                         0
     psutil                    5.7.0            py38h7b6447c_0
     ptyprocess                0.6.0                    py38_0
     py                        1.9.0                      py_0
     py-lief                   0.10.1           py38h403a769_0
     pycodestyle               2.6.0                      py_0
     pycosat                   0.6.3            py38h7b6447c_1
     pycparser                 2.20                       py_2
     pycurl                    7.43.0.5         py38h1ba5d50_0
     pydocstyle                5.0.2                      py_0
     pyflakes                  2.2.0                      py_0
     pygments                  2.6.1                      py_0
     pylint                    2.5.3                    py38_0
     pyodbc                    4.0.30           py38he6710b0_0
     pyopenssl                 19.1.0                     py_1
     pyparsing                 2.4.7                      py_0
     pyqt                      5.9.2            py38h05f1152_4
     pyrsistent                0.16.0           py38h7b6447c_0
     pysocks                   1.7.1                    py38_0
     pytables                  3.6.1            py38h9fd0a39_0
     pytest                    5.4.3                    py38_0
     python                    3.8.3                hcff3b4d_2
     python-dateutil           2.8.1                      py_0
     python-jsonrpc-server     0.3.4                      py_1
     python-language-server    0.34.1                   py38_0
     python-libarchive-c       2.9                        py_0
     python_abi                3.8                      1_cp38    conda-forge
     pytz                      2020.1                     py_0
     pywavelets                1.1.1            py38h7b6447c_0
     pyxdg                     0.26                       py_0
     pyyaml                    5.3.1            py38h7b6447c_1
     pyzmq                     19.0.1           py38he6710b0_1
     qdarkstyle                2.8.1                      py_0
     qt                        5.9.7                h5867ecd_1
     qtawesome                 0.7.2                      py_0
     qtconsole                 4.7.5                      py_0
     qtpy                      1.9.0                      py_0
     readline                  8.0                  h7b6447c_0
     regex                     2020.6.8         py38h7b6447c_0
     requests                  2.24.0                     py_0
     ripgrep                   11.0.2               he32d670_0
     rope                      0.17.0                     py_0
     rtree                     0.9.4                    py38_1
     ruamel_yaml               0.15.87          py38h7b6447c_1
     scikit-image              0.16.2           py38h0573a6f_0
     scikit-learn              0.23.1           py38h423224d_0
     scipy                     1.5.0            py38h0b6359f_0
     seaborn                   0.10.1                     py_0
     secretstorage             3.1.2                    py38_0
     send2trash                1.5.0                    py38_0
     setuptools                49.2.0                   py38_0
     simplegeneric             0.8.1                    py38_2
     singledispatch            3.4.0.3                  py38_0
     singularity               2.4.6                         0    conda-forge
     sip                       4.19.13          py38he6710b0_0
     six                       1.15.0                     py_0
     snappy                    1.1.8                he6710b0_0
     snowballstemmer           2.0.0                      py_0
     sortedcollections         1.2.1                      py_0
     sortedcontainers          2.2.2                      py_0
     soupsieve                 2.0.1                      py_0
     sphinx                    3.1.2                      py_0
     sphinxcontrib             1.0                      py38_1
     sphinxcontrib-applehelp   1.0.2                      py_0
     sphinxcontrib-devhelp     1.0.2                      py_0
     sphinxcontrib-htmlhelp    1.0.3                      py_0
     sphinxcontrib-jsmath      1.0.1                      py_0
     sphinxcontrib-qthelp      1.0.3                      py_0
     sphinxcontrib-serializinghtml 1.1.4                      py_0
     sphinxcontrib-websupport  1.2.3                      py_0
     spyder                    4.1.4                    py38_0
     spyder-kernels            1.9.2                    py38_0
     sqlalchemy                1.3.18           py38h7b6447c_0
     sqlite                    3.32.3               h62c20be_0
     statsmodels               0.11.1           py38h7b6447c_0
     sympy                     1.6.1                    py38_0
     tbb                       2020.0               hfd86e86_0
     tblib                     1.6.0                      py_0
     terminado                 0.8.3                    py38_0
     testpath                  0.4.4                      py_0
     threadpoolctl             2.1.0              pyh5ca1d4c_0
     tk                        8.6.10               hbc83047_0
     toml                      0.10.1                     py_0
     toolz                     0.10.0                     py_0
     tornado                   6.0.4            py38h7b6447c_1
     tqdm                      4.47.0                     py_0
     traitlets                 4.3.3                    py38_0
     typing_extensions         3.7.4.2                    py_0
     ujson                     1.35             py38h7b6447c_0
     unicodecsv                0.14.1                   py38_0
     unixodbc                  2.3.7                h14c3975_0
     urllib3                   1.25.9                     py_0
     watchdog                  0.10.3                   py38_0
     wcwidth                   0.2.5                      py_0
     webencodings              0.5.1                    py38_1
     werkzeug                  1.0.1                      py_0
     wheel                     0.34.2                   py38_0
     widgetsnbextension        3.5.1                    py38_0
     wrapt                     1.11.2           py38h7b6447c_0
     wurlitzer                 2.0.1                    py38_0
     xlrd                      1.2.0                      py_0
     xlsxwriter                1.2.9                      py_0
     xlwt                      1.3.0                    py38_0
     xmltodict                 0.12.0                     py_0
     xz                        5.2.5                h7b6447c_0
     yaml                      0.2.5                h7b6447c_0
     yapf                      0.30.0                     py_0
     zeromq                    4.3.2                he6710b0_2
     zict                      2.0.0                      py_0
     zipp                      3.1.0                      py_0
     zlib                      1.2.11               h7b6447c_3
     zope                      1.0                      py38_1
     zope.event                4.4                      py38_0
     zope.interface            4.7.1            py38h7b6447c_0
     zstd                      1.4.5                h0b5b093_0
     
</pre></details>

**Additional context**

**Comment by laceyg** [comment]
Temporary workaround for me is to convert to a list: `pd.Index(['A', 'B', 'C', 'D']).tolist()`

**Comment by skirui-source** [comment]
@laceyg I am unable to reproduce the bug in my workstation(seems to be working fine): 
```
>>> import cudf
>>> import pandas as pd
>>> pdf = pd.DataFrame([[1, 2, 3, 4]], columns=pd.Index(['A', 'B', 'C', 'D']))
>>> pdf
   A  B  C  D
0  1  2  3  4
>>> gdf = cudf.DataFrame([[1, 2, 3, 4]], columns=pd.Index(['A', 'B', 'C', 'D']))
>>> gdf
   A  B  C  D
0  1  2  3  4
>>> gdf2 = cudf.DataFrame([[1, 2, 3, 4]], columns=cudf.Index(['A', 'B', 'C', 'D']))
>>> gdf2
   A  B  C  D
0  1  2  3  4
```

I'm guessing it might have been resolved, Can you try reproducing with the latest nightly and let me know if you still 
have the issue?

**Comment by skirui-source** [comment]
Closing this ticket because the issue is resolved in the latest `(rapidsai/rapidsai-core-nightly:0.20-cuda11.0-runtime-ubuntu18.04-py3.7)` 👍🏾
