### ISSUE TITLE
[FEA] Cover struct columns in fuzz testing

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#7618]
The cuIO fuzz tests currently cannot generate input with struct columns. cudf now support this type of data for Parquet IO, so coverage should be expanded to include columns of struct data type.

Ideally, the generated columns should cover the following:

- [ ] Variable levels of nesting;
- [ ] Combination of nested structs, lists and non-nested data types;

**Comment by vuule** [comment]
CC @devavret and @nvdbaranec to add any corner cases that need to be covered.

**Comment by devavret** [comment]
1. One of the children is strings
2. Columns have an offset (sliced column)
3. Many permutations/combinations of nullability of levels. (every level nullable, no level nullable etc)

**Comment by vuule** [comment]
what is missing before we can close this one?

**Comment by nvdbaranec** [comment]
I would add:  Many permutations of empty things.   Empty strings, empty lists, empty structs.  These tend to expose slightly different problems than just null values (particularly with strings, where various child columns can be nullptr, etc).

**Comment by galipremsagar** [comment]
https://github.com/rapidsai/cudf/pull/9180 has already started paying dividends for ORC `struct` support fuzz-testing: https://github.com/rapidsai/cudf/issues/9395

I would like to verify the nested empty types cases that @nvdbaranec pointed out and there is some cleanup to be done hence moving this to `22.02`.
