### ISSUE TITLE
[FEA] Cover struct columns in C++ cuIO benchmarks

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#7619]
The cuIO benchmarks currently cannot generate input with struct columns. libcudf/cuDF now support this type of data for Parquet IO, so coverage should be expanded to include columns of struct data type.

**Comment by vuule** [comment]
@devavret @nvdbaranec what kind of nesting should be covered in benchmarks?

**Comment by devavret** [comment]
On the writer side: crazy deep single child structs should be sufficient.

**Comment by vuule** [comment]
> On the writer side: crazy deep single child structs should be sufficient.

Should be be two cases - "crazy deep" and single level?

**Comment by nvdbaranec** [comment]
> Should be be two cases - "crazy deep" and single level?

I think it's  "one" -> "two" -> "many"

**Comment by devavret** [comment]
The single level part is because it's a benchmark. From performance perspective, the number of children should not matter. They're going to be converted to single child anyway.

**Comment by vuule** [comment]
are nullability variations relevant here?

**Comment by devavret** [comment]
> are nullability variations relevant here?

No. It shouldn't affect performance. Only correctness.
