### ISSUE TITLE
[BUG] Compilation fails with device_uvector destructor error

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#7629]
**Describe the bug**
When compiling cudf, it will fail with the error:

```
/usr/local/rapids/include/rmm/mr/device/per_device_resource.hpp(89): error: calling a __host__ function("rmm::device_buffer::~device_buffer") from a __host__ __device__ function("rmm::device_uvector<int> ::~device_uvector") is not allowed
```

This happens due to this [feature](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compiler-generated-functions), which says that since `device_uvector` has a defaulted destructor, it will get the same host and device decorators of `thrust::optional` when used here in explode.cu:

```
std::unique_ptr<table> build_table(
  table_view const& input_table,
  size_type const explode_column_idx,
  column_view const& sliced_child,
  cudf::device_span<size_type const> gather_map,
  thrust::optional<cudf::device_span<size_type const>> explode_col_gather_map,
  thrust::optional<rmm::device_uvector<size_type>> position_array,
  rmm::cuda_stream_view stream,
  rmm::mr::device_memory_resource* mr)
```

This isn't valid since device_buffer doesn't have the same decorators and produces the compile error seen above.

**Steps/Code to reproduce bug**
1) compile cudf.

In all seriousness, this issue isn't seen by everyone and that is a mystery. CI didn't catch it and I can't reproduce it on my machine, but it has been seen in cuda 10.1, 10.2, 11.0, and 11.2

Many thanks to @robertmaynard for deciphering this error.

**Comment by jrhemstad** [comment]
We can eliminate the warning by adding `#pragma nv_exec_check_disable` to `device_uvector`s dtor.
