### ISSUE TITLE
[BUG] cudf::partition causing data corruption on structs

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7638]
**Describe the bug**
We recently switched over to try and use cudf::partition (0.19) as a way to partition shuffle data in some cases for Spark. Instantly a test started to fail that partitioning a column with a struct in it.

**Steps/Code to reproduce bug**
```diff
diff --git a/cpp/tests/partitioning/partition_test.cpp b/cpp/tests/partitioning/partition_test.cpp
index a6838112a5..e15d57fc67 100644
--- a/cpp/tests/partitioning/partition_test.cpp
+++ b/cpp/tests/partitioning/partition_test.cpp
@@ -141,6 +141,35 @@ TYPED_TEST(PartitionTest, Identity)
   run_partition_test(table_to_partition, map, 6, table_to_partition, expected_offsets);
 }
 
+TYPED_TEST(PartitionTest, Struct)
+{
+  using value_type = cudf::test::GetType<TypeParam, 0>;
+  using map_type   = cudf::test::GetType<TypeParam, 1>;
+
+  fixed_width_column_wrapper<value_type, int32_t> A({1, 2}, {0, 1});
+  auto struct_col = cudf::test::structs_column_wrapper({A}, {0, 1}).release();
+  auto table_to_partition = cudf::table_view{{*struct_col}};
+
+  fixed_width_column_wrapper<map_type> map{9, 2};
+
+  fixed_width_column_wrapper<value_type, int32_t> A_expected({2, 1}, {1, 0});
+  auto struct_expected = cudf::test::structs_column_wrapper({A_expected}, {1, 0}).release();
+  auto expected = cudf::table_view{{*struct_expected}};
+
+  std::vector<cudf::size_type> expected_offsets{0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2};
+
+  // This does not work because we cannot sort a struct right now...
+  // run_partition_test(table_to_partition, map, 12, expected, expected_offsets);
+  // But there is no ambiguity in the ordering so I'll just copy it all here for now.
+  auto num_partitions = 12;
+  auto result = cudf::partition(table_to_partition, map, num_partitions);
+  auto const& actual_partitioned_table = result.first;
+  auto const& actual_offsets           = result.second;
+  EXPECT_EQ(actual_offsets, expected_offsets);
+
+  CUDF_TEST_EXPECT_TABLES_EQUAL(expected, *actual_partitioned_table);
+}
+
 TYPED_TEST(PartitionTest, Reverse)
 {
   using value_type = cudf::test::GetType<TypeParam, 0>;
```
This test definitely fails and I think it is reproducing the error.  Essentially what I see is that the child of the struct is not being changed despite the parent column being reordered. I think this is a scatter issue, but I am not 100% sure.

**Expected behavior**
The child of the struct should be reordered just like the struct was. 

**Additional context**
Please verify that lists are working correctly too.

**Comment by jrhemstad** [comment]
This must be a bug in `scatter`. The `cudf::partition` API doesn't touch the input data whatsoever. It just computes the scatter map from the input `partition_map` and calls `scatter`.

**Comment by ttnghia** [comment]
I have dug into the details of scatter implementation. It ultimately calls `column_scatterer_impl`, which has specializations for string, list, and dictionary32 (so lists should be scattered correctly). The other types are scattered by a default implementation, which is incorrect for struct type. I'm adding struct support to it.
