### ISSUE TITLE
Unsafe usage of OrderedDict inheritance

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#7646]
### Summary

The `OrderedColumnDict` class used as a base for `ColumnAccessor is making some unsafe choices that are not currently leading to bugs, but could lead to developer error in the future. We can either restrict usage explicitly to stop developers from using unsafe APIs, in which case we can make some performance improvements, or we can make a more flexible but slower choice.

### Background

Inheriting from built-in classes in Python can be dangerous because internal optimizations may have unexpected consequences. In this case, the most relevant issue is that overriding `__setitem__` does not necessarily affect other methods in the way that you might expect; in particular, `update` is not guaranteed to call `__setitem__`, but may instead inline the code for performance. Typically, dict-like classes are instead advised to extend `collections.abc.MutableMapping` instead, because in that case implementing the abstract methods _is_ guaranteed to give the expected behavior for the other mixin methods.

The `OrderedColumnDict` currently inherits from `OrderedDict`. In Python 2.7, `OrderedDict` was a standalone class, but in Python 3 [it is a direct subclass of `dict`](https://github.com/python/cpython/blob/master/Lib/collections/__init__.py#L78). However, this is where things get more complicated. `OrderedDict` was implemented in Python until Python 3.5, when a [C implementation was added](https://bugs.python.org/issue16991). Interestingly, while the original Python implementation does not override `update`, the C implementation [hooks back into the `MutableMapping` C implementation](https://github.com/python/cpython/blob/226a012d1cd61f42ecd3056c554922f359a1a35d/Objects/odictobject.c#L1213). This means that up until Python 3.5, overriding `__setitem__` would not change the behavior of `update`, but afterwards it would. 

### Proposal

The upshot is that the `OrderedColumnDict` is currently relying on an implementation detail to make methods like `update` and `setdefault` use the `__setitem__` implementations of `EqualLengthValuesMappingMixin` and `ColumnValuesMappingMixin`. Since CPython makes no guarantees that this behavior will not change in the future, we have two options:

**Option 1**

Instead of inheriting directly from `OrderedDict`, we can implement a `MutableMapping` that owns an `OrderedDict` internally and override `__setitem__` there to perform the necessary conversions. This change will slow the code somewhat, but it will make the object safe to future modifications in the Python code base.

**Option 2**

As far as I can tell, this class is only ever used internally, and only by the `ColumnAccessor`. The closest thing to an exception is that it's constructed [in a temporary table for the purpose of hashing](https://github.com/rapidsai/cudf/blob/branch-0.19/python/cudf/cudf/core/dataframe.py#L4857), and even then it's internally being passed to the `ColumnAccessor` constructor. That being the case, we could simply override all other mutating methods of `OrderedColumnDict` (of the top of my head that's just `update` and `setdefault`), either to raise exceptions so that future developers can't accidentally use them, or to implement them by calling `__setitem__`. If it's never a user-facing object, either change seems like a reasonable choice. The important thing is to either 1) ensure that all methods that we use are correctly overridden, or 2) only ever use `__setitem__` so that we don't rely on any other behavior.

**Performance Implications**

I originally started looking at this code while playing with some benchmarking code from @shwina. For data frames with 1M rows, the shallow copying of columns that happens in order to match dtypes (see `Merge._match_key_dtypes` in `cudf/core/join.py`) takes around ~5% of the execution time of the entire merge by itself, and that jumps into the 10-15% range for data frames with 1000 rows. 

In either option, benchmarks suggest that we would benefit from inlining the `__setitem__` logic from the mixins. `__setitem__` calls are not free, especially once you're overriding the C implementations of built-in (even a trivial implementation that just calls `super().__setitem__(...)` is close to an order of magnitude slower), so we would benefit measurably from avoiding the extra Python function call overhead and MRO lookup by just combining the mixin implementations of `__setitem__` into a single `__setitem__` override in `OrderedColumnDict`.

Option 2 would also enable some further optimization. Since `dict` is insertion-ordered as of Python 3.7, we could safely have `OrderedColumnDict` inherit from `dict` instead of `OrderedDict`, which would not only make `__setitem__` calls about 10% faster according to my benchmarks, but make copies about twice as fast, which in turn would make shallow copying columns much faster, an operation that seems to occur fairly often due to the need to match dtypes in join-like operations.

**Comment by shwina** [comment]
Re option 1: Is the fact that `OrderedDict` implements `update` in an inheritance-friendly way truly an implementation detail? Perhaps inheriting from OrderedDict directly isn't so unsafe after all; the docs seem to have recipes based on doing exactly that: https://docs.python.org/3/library/collections.html#ordereddict-examples-and-recipes. 

Note also, there's a reference to subclassing `dict` directly being OK now (which I admit I have always thought was a bad idea).

**Comment by shwina** [comment]
OK I think I misunderstood, what's an implementation detail is that`update()` relies on `__setitiem__` in a non-explicit way. 

Even so, I think option 2 sounds much more preferable here 🙂

**Comment by kkraus14** [comment]
I think there's an option 3 here that's likely high effort and not the best use of time, but we could implement the `OrderedColumnDict` or even the whole `ColumnAccessor` in Cython using C++ where appropriate to eliminate bottlenecks.

**Comment by vyasr** [comment]
@shwina exactly, the implementation detail is that while update is documented as being equivalent to `for k in E: D[k] = E[k]`, this is only true from a user perspective. Subclassing from dict is generally not advised, there's tons of articles/posts discussing this ([like](https://treyhunner.com/2019/04/why-you-shouldnt-inherit-from-list-and-dict-in-python/) [these](https://dev.to/0xbf/customize-your-own-dictionary-python-tips-5b47) [articles](https://stackoverflow.com/questions/3387691/how-to-perfectly-override-a-dict) that show up when i search "python don't subclass dict"). However, the reason is generally not that there's anything horribly wrong with doing it, just that it requires a lot of care because you really have to override every method. So I think we can do it in this case where it's for a purely internal variable.

@kkraus14 yes that is definitely an option, but as you point out a much higher effort one. @shwina mentioned that you two were maybe considering moving towards using a list rather than dict of columns as the internal storage in the long term. If significant changes like that are being considered, it's probably best to do some research and pick the best long term solution (cythonizing the whole class, using python but changing underlying data structures, etc) before undertaking a more significant refactoring. What I'm proposing here would be a quick win that'll just take me an hour to implement, so I'd advocate for implementing this now and revisiting the broader refactoring later.
