### ISSUE TITLE
[BUG] Remove references to TravisCI

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cudf#765]
Remove all references to travisci and update for gpuci if necessary.

Here are the files that reference travis:
* `python/versioneer.py`
* `conda/recipes/libcudf_cffi/meta.yaml`
* `conda/recipes/libcudf/meta.yaml`
* `ci/cpu/cudf/upload-anaconda.sh`
* `ci/cpu/libcudf/upload-anaconda.sh`
* `cpp/cmake/Modules/ConfigureGoogleTest.cmake`
* `cpp/cmake/Modules/ConfigureArrow.cmake`

**Comment by mike-wendt** [comment]
Fixed in #766
