### ISSUE TITLE
[BUG] nested types is_monotonic* exception in cudf

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#7653]
**Describe the bug**
C++ exceptions are thrown during autocomplete in python of nested type columns with more than one element (struct, list).

**Steps/Code to reproduce bug**
```python
def attributes(obj):
    names=[]
    for name in dir(obj):
        try:
            hasattr(obj, name)
        except:
            print(name)
            names.append(name)
    return names

import cudf
struct_series = cudf.Series([ {"Int": -1}, {"Int": 1}, {"Int": None} ])
list_series = cudf.Series([[1, 2, 3], [1, 2], [None, 1] ])
attributes(struct_series)
attributes(list_series)
```

```
_constructor_sliced
../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view, <unnamed> = (void *)nullptr, has_nulls = false]: block: [0,0,0], thread: [0,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view, <unnamed> = (void *)nullptr, has_nulls = false]: block: [0,0,0], thread: [1,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
is_monotonic
is_monotonic_decreasing
is_monotonic_increasing
is_unique
nullmask
values
values_host
```

**Expected behavior**
No C++ exceptions should be thrown during autocomplete.

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: from source

**Environment details**
<details><summary>Click here to see environment details</summary><pre>
     
     **git***
     commit 6fe8b1b7be71c0f3587d3ef43c535aec376d1e45 (HEAD -> branch-0.19)
     Author: Mark Harris <mharris@nvidia.com>
     Date:   Fri Mar 19 21:03:56 2021 +1100
     
     Eliminate literal parameters to uvector::set_element_async and device_scalar::set_value (#7563)
     
     After rapidsai/rmm#725 is merged, this PR updates cuspatial to eliminate passing literal values to `device_scalar::set_value`.
     
     Note there are still similar issues with uses of `cudf::scalar` that need to be addressed. But I wanted to get this open before the end of the week. This can be merged after RMM 725 is merged to fix the build, so I think the `scalar` issues should be fixed separately.
     
     Authors:
     - Mark Harris (@harrism)
     
     Approvers:
     - Devavret Makkar (@devavret)
     - Paul Taylor (@trxcllnt)
     - Mike Wilson (@hyperbolic2346)
     
     URL: https://github.com/rapidsai/cudf/pull/7563
     **git submodules***
     
     ***OS Information***
     DISTRIB_ID=Ubuntu
     DISTRIB_RELEASE=18.04
     DISTRIB_CODENAME=bionic
     DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
     NAME="Ubuntu"
     VERSION="18.04.5 LTS (Bionic Beaver)"
     ID=ubuntu
     ID_LIKE=debian
     PRETTY_NAME="Ubuntu 18.04.5 LTS"
     VERSION_ID="18.04"
     HOME_URL="https://www.ubuntu.com/"
     SUPPORT_URL="https://help.ubuntu.com/"
     BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
     PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
     VERSION_CODENAME=bionic
     UBUNTU_CODENAME=bionic
     Linux knataraj-ws 4.15.0-137-generic #141-Ubuntu SMP Fri Feb 19 13:46:27 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
     
     ***GPU Information***
     Fri Mar 19 21:29:16 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |===============================+======================+======================|
     |   0  Quadro GV100        Off  | 00000000:15:00.0 Off |                  Off |
     | 36%   48C    P2    39W / 250W |      0MiB / 32508MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     |   1  Quadro GV100        Off  | 00000000:2D:00.0 Off |                  Off |
     | 41%   55C    P2    40W / 250W |    208MiB / 32498MiB |      0%      Default |
     +-------------------------------+----------------------+----------------------+
     
     +-----------------------------------------------------------------------------+
     | Processes:                                                       GPU Memory |
     |  GPU       PID   Type   Process name                             Usage      |
     |=============================================================================|
     |    1      1410      G   /usr/lib/xorg/Xorg                           125MiB |
     |    1      1891      G   /usr/bin/gnome-shell                          81MiB |
     +-----------------------------------------------------------------------------+
     
     ***CPU***
     Architecture:        x86_64
     CPU op-mode(s):      32-bit, 64-bit
     Byte Order:          Little Endian
     CPU(s):              12
     On-line CPU(s) list: 0-11
     Thread(s) per core:  2
     Core(s) per socket:  6
     Socket(s):           1
     NUMA node(s):        1
     Vendor ID:           GenuineIntel
     CPU family:          6
     Model:               85
     Model name:          Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz
     Stepping:            4
     CPU MHz:             1200.199
     CPU max MHz:         3700.0000
     CPU min MHz:         1200.0000
     BogoMIPS:            6800.00
     Virtualization:      VT-x
     L1d cache:           32K
     L1i cache:           32K
     L2 cache:            1024K
     L3 cache:            19712K
     NUMA node0 CPU(s):   0-11
     Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke md_clear flush_l1d
     
     ***CMake***
     /home/karthikeyan/miniconda3/envs/cudf_dev/bin/cmake
     cmake version 3.18.5
     
     CMake suite maintained and supported by Kitware (kitware.com/cmake).
     
     ***g++***
     /usr/local/bin/g++
     g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
     
     
     ***nvcc***
     /usr/local/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2019 NVIDIA Corporation
     Built on Wed_Oct_23_19:24:38_PDT_2019
     Cuda compilation tools, release 10.2, V10.2.89
     
     ***Python***
     /home/karthikeyan/miniconda3/envs/cudf_dev/bin/python
     Python 3.7.10
     
     ***Environment Variables***
     PATH                            : /home/karthikeyan/miniconda3/envs/cudf_dev/bin:/usr/local/bin:/usr/local/cuda-10.2/bin:/home/karthikeyan/.vscode-server-insiders/bin/e4b1e9ac57ab3cc942ab9bff09967bf3238a7910/bin:/home/karthikeyan/bin:/home/karthikeyan/.local/bin:/home/karthikeyan/miniconda3/condabin:/usr/local/bin:/usr/local/cuda-10.2/bin:/home/karthikeyan/.vscode-server-insiders/bin/e4b1e9ac57ab3cc942ab9bff09967bf3238a7910/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin:/home/karthikeyan/miniconda3/bin:/home/karthikeyan/.local/bin:/usr/local/cuda/bin:/home/karthikeyan/miniconda3/bin:/home/karthikeyan/.local/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda-10.2/lib64:/usr/local/cuda-10.2/lib64:/home/karthikeyan/4cudf/cpp/build:/home/karthikeyan/4cudf/cpp/build/release
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /home/karthikeyan/miniconda3/envs/cudf_dev
     PYTHON_PATH                     :
     
     ***conda packages***
     /home/karthikeyan/miniconda3/condabin/conda
     # packages in environment at /home/karthikeyan/miniconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20200225.2           he1b5a44_2    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                        py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h4abf009_2    conda-forge
     arrow-cpp                 1.0.1           py37h9631afc_16_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-common              0.4.59               h36c2ea0_1    conda-forge
     aws-c-event-stream        0.1.6                had2084c_6    conda-forge
     aws-checksums             0.1.10               h4e93380_0    conda-forge
     aws-sdk-cpp               1.8.70               h57dc084_1    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.1                      py_0    conda-forge
     beautifulsoup4            4.9.3              pyhb0f4dca_0
     black                     19.10b0                    py_4    conda-forge
     blas                      1.0                         mkl
     bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
     bokeh                     2.2.3            py37h89c1867_0    conda-forge
     boost-cpp                 1.74.0               h9d3c048_1    conda-forge
     brotli                    1.0.9                he1b5a44_3    conda-forge
     brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h36c2ea0_0    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_1    conda-forge
     cffi                      1.14.4           py37hc58025e_1    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   3.0.4           py37he5f6b98_1008    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.5               h1f3970d_0    rapidsai-nightly
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.3.1            py37h7f0c10b_0    conda-forge
     cudatoolkit               10.2.89              h6bb024c_0    nvidia
     cudnn                     7.6.5                cuda10.2_0
     cupy                      8.1.0            py37hd81ff16_0    conda-forge
     cython                    0.29.22          py37hcd2ae1e_0    conda-forge
     cytoolz                   0.11.0           py37h4abf009_1    conda-forge
     dask                      2021.3.0+33.gc19a56a2          pypi_0    pypi
     decorator                 4.4.2                      py_0    conda-forge
     defusedxml                0.6.0                      py_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2021.3.0+18.g98148cbf          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37he5f6b98_2    conda-forge
     double-conversion         3.1.5                he1b5a44_2    conda-forge
     editdistance              0.5.3            py37h3340039_2    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     execnet                   1.8.0              pyh44b312d_0    conda-forge
     expat                     2.2.9                he1b5a44_2    conda-forge
     fastavro                  1.3.3            py37h5e8e339_0    conda-forge
     fastrlock                 0.5              py37h3340039_1    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h7ca028e_0    conda-forge
     fsspec                    0.8.7              pyhd8ed1ab_0    conda-forge
     future                    0.18.2           py37h89c1867_2    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.33.2               h1870a98_1    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                6.8.1              pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  1.5.10             pyhd3deb0d_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        2.0.0                      py_1    conda-forge
     importlib_metadata        2.0.0                         1    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     intel-openmp              2020.2                      254
     ipykernel                 5.3.4            py37h888b3d9_1    conda-forge
     ipython                   7.21.0           py37h888b3d9_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.17.2           py37h89c1867_1    conda-forge
     jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jsonschema                3.2.0                      py_2    conda-forge
     jupyter_client            6.1.7                      py_0    conda-forge
     jupyter_core              4.7.0            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.11                 hcbb858e_1    conda-forge
     ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
     libcurl                   7.71.1               hcdd3856_8    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
     libgfortran-ng            7.3.0                hdf63c60_0
     libgomp                   9.3.0               h5dbcf3e_17    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.13.0.1             h8b12597_0    conda-forge
     librmm                    0.19.0a210303   cuda10.2_gbbc3e97_34    rapidsai-nightly
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                hab1572f_5    conda-forge
     libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
     libthrift                 0.13.0               h5aa387f_6    conda-forge
     libtiff                   4.1.0                h4f3a223_6    conda-forge
     libutf8proc               2.6.0                h36c2ea0_0    conda-forge
     libuv                     1.40.0               hd18ef5c_0    conda-forge
     libwebp-base              1.1.0                h36c2ea0_3    conda-forge
     llvmlite                  0.35.0           py37h9d7f4d0_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.2                he1b5a44_3    conda-forge
     markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
     markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h4abf009_1002    conda-forge
     mkl                       2020.2                      256
     mkl-service               2.3.0            py37he8ac12f_0
     mkl_fft                   1.2.1            py37h54f3939_0
     mkl_random                1.1.1            py37h0573a6f_0
     more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.0            py37hc928c03_2    conda-forge
     mypy                      0.782                      py_0    conda-forge
     mypy_extensions           0.4.3            py37h89c1867_3    conda-forge
     nbclient                  0.5.1                      py_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.0.8                      py_0    conda-forge
     nbsphinx                  0.8.1              pyh44b312d_0    conda-forge
     nccl                      2.8.3.1              h1a5f58c_0    conda-forge
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
     ninjavis                  0.2.1                    pypi_0    pypi
     nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
     notebook                  6.2.0            py37h89c1867_0    conda-forge
     numba                     0.52.0           py37hdc94413_0    conda-forge
     numpy                     1.19.2           py37h54aff64_0
     numpy-base                1.19.2           py37hfa32c7d_0
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.3            py37h5e8e339_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openssl                   1.1.1j               h7f98852_0    conda-forge
     orc                       1.6.5                hd3605a7_0    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.2.3            py37hdc94413_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.7.1              pyh9f0ad1d_0    conda-forge
     partd                     1.1.0                      py_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.0.1            py37h63a5d19_0    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37he5f6b98_3    conda-forge
     pre-commit                2.9.3            py37h89c1867_0    conda-forge
     pre_commit                2.9.3                hd8ed1ab_0    conda-forge
     prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
     prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
     protobuf                  3.13.0.1         py37h745909e_1    conda-forge
     psutil                    5.7.3            py37hb5d75c8_0    conda-forge
     ptyprocess                0.6.0                   py_1001    conda-forge
     py                        1.9.0              pyh9f0ad1d_0    conda-forge
     py-cpuinfo                7.0.0              pyh9f0ad1d_0    conda-forge
     pyarrow                   1.0.1           py37hbeecfa9_16_cuda    conda-forge
     pycodestyle               2.6.0              pyh9f0ad1d_0    conda-forge
     pycparser                 2.20               pyh9f0ad1d_2    conda-forge
     pyflakes                  2.2.0              pyh9f0ad1d_0    conda-forge
     pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
     pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
     pyorc                     0.4.0                    pypi_0    pypi
     pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
     pyrsistent                0.17.3           py37h4abf009_1    conda-forge
     pysocks                   1.7.1            py37he5f6b98_2    conda-forge
     pytest                    6.2.2            py37h89c1867_0    conda-forge
     pytest-benchmark          3.2.3              pyh9f0ad1d_0    conda-forge
     pytest-forked             1.2.0              pyh9f0ad1d_0    conda-forge
     pytest-xdist              2.2.1              pyhd8ed1ab_0    conda-forge
     python                    3.7.10          hffdb5ce_100_cpython    conda-forge
     python-dateutil           2.8.1                      py_0    conda-forge
     python_abi                3.7                     1_cp37m    conda-forge
     pytz                      2020.4             pyhd8ed1ab_0    conda-forge
     pyyaml                    5.3.1            py37hb5d75c8_1    conda-forge
     pyzmq                     20.0.0           py37h5a562af_1    conda-forge
     rapidjson                 1.1.0             he1b5a44_1002    conda-forge
     re2                       2020.11.01           h58526e2_0    conda-forge
     readline                  8.0                  he28a2e2_2    conda-forge
     recommonmark              0.7.1              pyhd8ed1ab_0    conda-forge
     regex                     2020.11.13       py37h4abf009_0    conda-forge
     requests                  2.25.0             pyhd3deb0d_0    conda-forge
     rhash                     1.3.6             h516909a_1001    conda-forge
     rmm                       0.19.0a210319   cuda_10.2_py37_gdce33aa_48    rapidsai-nightly
     scipy                     1.6.0            py37h91f5cce_0
     send2trash                1.5.0                      py_0    conda-forge
     setuptools                49.6.0           py37he5f6b98_2    conda-forge
     six                       1.15.0             pyh9f0ad1d_0    conda-forge
     snappy                    1.1.8                he1b5a44_3    conda-forge
     snowballstemmer           2.0.0                      py_0    conda-forge
     sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
     soupsieve                 2.1                pyhd3eb1b0_0
     spdlog                    1.7.0                hc9558a2_2    conda-forge
     sphinx                    3.5.2              pyhd8ed1ab_0    conda-forge
     sphinx-copybutton         0.3.1              pyhd8ed1ab_0    conda-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.1              pyhd3deb0d_0    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.34.0               h74cdb3f_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     tblib                     1.6.0                      py_0    conda-forge
     terminado                 0.9.1            py37h89c1867_1    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     tk                        8.6.10               hed695b0_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h4abf009_0    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     typed-ast                 1.4.1            py37h4abf009_1    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.25.11                    py_0    conda-forge
     virtualenv                20.2.2           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.1             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.3                h58526e2_3    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.0                      py_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.5                h6597ccf_2    conda-forge
     
</pre></details>

**Additional context**
https://github.com/rapidsai/cudf/pull/7422#issuecomment-802756987

**Comment by shwina** [comment]
What's weird is if I do:

```python
struct_series.is_mon<TAB>
```

I get a C++ exception:

```
struct_series.is_mon../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view; void *<anonymous> = (void *)nullptr; __nv_bool has_nulls = false]: block: [0,0,0], thread: [0,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view; void *<anonymous> = (void *)nullptr; __nv_bool has_nulls = false]: block: [0,0,0], thread: [1,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
```

But if I actually run the method, I get a nice Python exception:

```python
struct_series.is_monotonic_increasing
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-5-ab40890a5f5e> in <module>
----> 1 struct_series.is_monotonic_decreasing

~/cudf/python/cudf/cudf/core/series.py in is_monotonic_decreasing(self)
   6241         out : bool
   6242         """
-> 6243         return self._column.is_monotonic_decreasing
   6244
   6245     @property

~/cudf/python/cudf/cudf/core/column/column.py in is_monotonic_decreasing(self)
    967             else:
    968                 self._is_monotonic_decreasing = self.as_frame()._is_sorted(
--> 969                     ascending=[False], null_position=None
    970                 )
    971         return self._is_monotonic_decreasing

~/cudf/python/cudf/cudf/core/frame.py in _is_sorted(self, ascending, null_position)
   3493         """
   3494         return libcudf.sort.is_sorted(
-> 3495             self, ascending=ascending, null_position=null_position
   3496         )
   3497

~/cudf/python/cudf/cudf/_lib/sort.pyx in cudf._lib.sort.is_sorted()
    102     cdef table_view source_table_view = source_table.data_view()
    103     with nogil:
--> 104         c_result = cpp_is_sorted(
    105             source_table_view,
    106             column_order,

MemoryError: std::bad_alloc: CUDA error at: ../include/rmm/mr/device/cuda_memory_resource.hpp:69: cudaErrorAssert device-side assert triggered

```

**Comment by shwina** [comment]
MRE:

```
>>> struct_series = cudf.Series([ {"Int": -1}, {"Int": 1}, {"Int": None} ])
>>> hasattr(struct_series, "is_monotonic")
../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view; void *<anonymous
> = (void *)nullptr; __nv_bool has_nulls = false]: block: [0,0,0], thread: [0,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
../../../../include/cudf/table/row_operators.cuh:294: cudf::weak_ordering cudf::element_relational_comparator<has_nulls>::operator()(signed int, signed int) [with Element = cudf::struct_view; void *<anonymous
> = (void *)nullptr; __nv_bool has_nulls = false]: block: [0,0,0], thread: [1,0,0] Assertion `false && "Attempted to compare elements of uncomparable types."` failed.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-64c6bc5cafb5> in <module>
----> 1 hasattr(struct_series, "is_monotonic")

~/cudf/python/cudf/cudf/core/series.py in is_monotonic(self)
   6219         out : bool
   6220         """
-> 6221         return self._column.is_monotonic_increasing
   6222
   6223     @property

~/cudf/python/cudf/cudf/core/column/column.py in is_monotonic_increasing(self)
    956             else:
    957                 self._is_monotonic_increasing = self.as_frame()._is_sorted(
--> 958                     ascending=None, null_position=None
    959                 )
    960         return self._is_monotonic_increasing

~/cudf/python/cudf/cudf/core/frame.py in _is_sorted(self, ascending, null_position)
   3493         """
   3494         return libcudf.sort.is_sorted(
-> 3495             self, ascending=ascending, null_position=null_position
   3496         )
   3497

~/cudf/python/cudf/cudf/_lib/sort.pyx in cudf._lib.sort.is_sorted()
    102     cdef table_view source_table_view = source_table.data_view()
    103     with nogil:
--> 104         c_result = cpp_is_sorted(
    105             source_table_view,
    106             column_order,

RuntimeError: reduce failed to synchronize: cudaErrorAssert: device-side assert triggered
```

**Comment by shwina** [comment]
In general, Python users shouldn't "see" C++ exceptions directly. Our Cython bindings are marked with `except  +` which should intercept any C++ exceptions and convert them into Python errors.

In this case, it looks like the C++ uses `release_assert` which doesn't raise a true C++ exception (i.e., one that inherits from `std::exception`). I don't believe Cython is equipped to handle those. cc: @jrhemstad

Thus, we see the raw output of `release_assert`.

As for the behaviour of tab completion, I believe that tab completion evaluates any properties, but swallows exceptions they may raise:


```python
In [4]: class Foo:
   ...:     @property
   ...:     def prop(self):
   ...:         print("hello")
   ...:         raise ZeroDivisionError()
   ...:

In [5]: x = Foo()

In [6]: x.prop<TAB>  # "hello" printed, but no exception raised
```

**Comment by kkraus14** [comment]
Resolved by https://github.com/rapidsai/cudf/pull/7583
