### ISSUE TITLE
[BUG] Higher memory footprint when writing strings to orc

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#7661]
**Describe the bug**
`df.to_orc` has a higher memory footprint in 0.19 nightlies vs 0.18 when writing string columns.

**Steps/Code to reproduce bug**

```python
nrows = 20_000_000
df =  cudf.DataFrame()
df['a'] = ['abc'] * nrows
for i in range(5):
    df[f'e{i}'] = "random_string"

df.to_orc(f'./test.orc', compression='snappy')
```

Peak memory usage in 0.18: `5864 MB`
Peak memory usage in 0.19 @ a5684328726bfa8dfdbbf10a50f47677ce57974b: `8432MB`

**Expected behavior**
Similar memory usage

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: Docker
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - 0.18 release CUDA 10.2, python 3.8
   - 0.19 nightly, CUDA 10.2, python 3.8 
     ```
     cudf                      0.19.0a210318   cuda_10.2_py38_ga568432872_236    rapidsai-nightly
     cudf_kafka                0.19.0a210318   py38_ga568432872_236    rapidsai-nightly
     dask-cudf                 0.19.0a210318   py38_ga568432872_236    rapidsai-nightly
     libcudf                   0.19.0a210318   cuda10.2_ga568432872_236    rapidsai-nightly
     ```

**Additional Context**
[Script](https://gist.github.com/pentschev/2e2e3fe8059240f2679b6f7002faa891) used to measure memory usage.

cc: @randerzander

**Comment by devavret** [comment]
Narrowed it down to the size of `encoded_data` https://github.com/rapidsai/cudf/blob/34cccfe7b922562856e3d188f90d6a6ad50ab77f/cpp/src/io/orc/writer_impl.cu#L606

It is 1.72 GB but it shouldn't be.

**Comment by vuule** [comment]
> Narrowed it down to the size of `encoded_data`
> 
> https://github.com/rapidsai/cudf/blob/34cccfe7b922562856e3d188f90d6a6ad50ab77f/cpp/src/io/orc/writer_impl.cu#L606
> 
> It is 1.72 GB but it shouldn't be.

I messed with this code in a recent PR, can take a look today.

**Comment by devavret** [comment]
> > Narrowed it down to the size of `encoded_data`
> > https://github.com/rapidsai/cudf/blob/34cccfe7b922562856e3d188f90d6a6ad50ab77f/cpp/src/io/orc/writer_impl.cu#L606
> > 
> > It is 1.72 GB but it shouldn't be.
> 
> I messed with this code in a recent PR, can take a look today.

It looks like the code hasn't changed in function. The part which is supposed to calculate the amount of memory to allocate is unchanged.
