### ISSUE TITLE
[FEA] cudf::strings::to_fixed_point support scientific notation

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#7665]
**Is your feature request related to a problem? Please describe.**
Currently, `cudf::strings::to_fixed_point` can not parse input string formatted as scientific notation, such as: `1.76e-3`.  And scientific notation is widely used in Spark and other kinds of applications. 

**Describe the solution you'd like**
Reinforce `string_to_decimal_fn`.

**Comment by davidwendt** [comment]
Including this unanswered comment/question here just for historical purposes.
https://github.com/rapidsai/cudf/issues/7285#issuecomment-772064726
Should have a PR for this ready soon.
