### ISSUE TITLE
[QST] if possible & how to build the python package of cudf for K40 GPU (kepler) by myself?

### ISSUE THREAD

**Issue by helai78** [rapidsai/cudf#7682]
I knew: cudf is required for Pascal architecture or better(compute capabilty>6.0). 

but I only have a tesla K40m GPU (Kepler) in a normal PC (24GB + i5 CPU), which can run ubuntu 20.04 or 18.04. whatverer...

My budgt is very limited. I had 40GB data in mysql DB and have already run my python programs in win10. but the running speed became slower and slower. So it seem to a good start to use a GPU for the beter performance. I just bought a K40m GPU 2 weeks before. 

I met the problem that 'no kernel image is not available for the execution in the device' and read some posts about it.

So, my question is 
For this GPU, can I build the special python package by myself by following the build instruction and the addtional make features like
    "nvcc -arch=sm_35 -gencode=arch=compute_35, code=sm_35" when seting CUDA_NVCC_FLAGS
    or some other features

Thanks in advance!

**Comment by kkraus14** [comment]
@helai78 the problem is that we take advantage of some device features in libcudf that don't exist on architectures older than Pascal where trying to compile for something like the Kepler architecture won't work unfortunately.

**Comment by helai78** [comment]
Thank you for your immediate reply!
I can understood that there is a dilemma between the better performace (the better device features) and the applicability.
Could I just use the basic cudf features like:  
1. io features: read_csv, read_sql, read_sql to_sql 
2. the basic floating points calculation capability 
3. some advance features: like sum, mean, and rolling
while not using the device features in libcudf of Pascal?
A little impovement of GPU utilization should be better for me than using CPU.
Do it make sense?

**Comment by kkraus14** [comment]
Specifically for aggregations in point 3, we use device atomics that are not available in architectures earlier than Pascal. I'm not sure about other features, but in development we prioritize building the most efficient implementations which often requires using newer features not supported in older architectures.

You're more than welcome to give building with Kepler architecture a shot, but we make no guarantees and won't provide support for doing so.
