### ISSUE TITLE
Cannot compile cudf

### ISSUE THREAD

**Issue by Yeghia** [rapidsai/cudf#7694]
Hi, this is the first time I'm asking a question on gitHub, forgive me if it is the wrong place.
I'm trying to compile cudf on CentOS 7.3 with GCC 6.2 and GCC 7.3 and I'm getting the following warnings and errors:

/home/yeghia/build/cudf/cpp/include/cudf/utilities/traits.hpp(619): **warning: dynamic initialization in unreachable code**
          detected during:
            instantiation of "__nv_bool cudf::is_bit_castable_to_impl<FromType>::operator()<ToType,<unnamed>>() [with FromType=numeric::decimal64, ToType=cudf::timestamp_us, <unnamed>=(void *)nullptr]" 
/home/yeghia/build/cudf/cpp/include/cudf/utilities/type_dispatcher.hpp(466): here
            instantiation of "decltype(auto) cudf::type_dispatcher(cudf::data_type, Functor, Ts &&...) [with IdTypeMap=cudf::id_to_type_impl, Functor=cudf::is_bit_castable_to_impl<numeric::decimal64>, Ts=<>]" 
(635): here
            instantiation of "__nv_bool cudf::is_bit_castable_from_impl::operator()<FromType,<unnamed>>(cudf::data_type) [with FromType=numeric::decimal64, <unnamed>=(void *)nullptr]" 
/home/yeghia/build/cudf/cpp/include/cudf/utilities/type_dispatcher.hpp(496): here
            instantiation of "decltype(auto) cudf::type_dispatcher(cudf::data_type, Functor, Ts &&...) [with IdTypeMap=cudf::id_to_type_impl, Functor=cudf::is_bit_castable_from_impl, Ts=<cudf::data_type &>]" 

[ 49%] Building CUDA object CMakeFiles/cudf.dir/src/dictionary/add_keys.cu.o
/home/yeghia/cuda-10.0/bin/nvcc  -DBOOST_NO_CXX14_CONSTEXPR -DCUDF_VERSION=0.19.0 -DJITIFY_PRINT_LOG=0 -DJITIFY_USE_CACHE -DSPDLOG_ACTIVE_LEVEL=SPDLOG_LEVEL_INFO -DTHRUST_DEVICE_SYSTEM=THRUST_DEVICE_SYSTEM_CUDA -DTHRUST_HOST_SYSTEM=THRUST_HOST_SYSTEM_CPP -Dcudf_EXPORTS -I/home/yeghia/build/cudf/cpp/build/_deps/dlpack-src/include -I/home/yeghia/build/cudf/cpp/build/_deps/jitify-src -I/home/yeghia/build/cudf/cpp/build/_deps/libcudacxx-src/include -I/home/yeghia/build/cudf/cpp/include -I/home/yeghia/build/cudf/cpp/build/include -I/home/yeghia/build/cudf/cpp/src -I/home/yeghia/build/cudf/cpp/build/_deps/arrow-src/cpp/src -I/home/yeghia/build/cudf/cpp/build/_deps/arrow-src/cpp/src/generated -I/home/yeghia/build/cudf/cpp/build/_deps/arrow-src/cpp/thirdparty/hadoop/include -I/home/yeghia/build/cudf/cpp/build/_deps/arrow-src/cpp/thirdparty/flatbuffers/include -I/home/yeghia/build/cudf/cpp/build/_deps/thrust-src -I/home/yeghia/build/cudf/cpp/build/_deps/thrust-src/dependencies/cub -I/home/yeghia/build/cudf/cpp/build/_deps/rmm-src/include -I/home/yeghia/build/cudf/cpp/build/_deps/spdlog-src/include -isystem=/u/yeghia/catsSDE/38/boost -isystem=/home/yeghia/cuda-10.0/include -O3 -DNDEBUG --generate-code=arch=compute_60,code=[sm_60] --generate-code=arch=compute_70,code=[sm_70] --generate-code=arch=compute_75,code=[compute_75,sm_75] -Xcompiler=-fPIC --expt-extended-lambda --expt-relaxed-constexpr -Werror=cross-execution-space-call -Xcompiler=-Wall,-Werror,-Wno-error=deprecated-declarations -Xcompiler=-Wno-deprecated-declarations -Xcompiler -pthread -std=c++14 -x cu -c /home/yeghia/build/cudf/cpp/src/dictionary/add_keys.cu -o CMakeFiles/cudf.dir/src/dictionary/add_keys.cu.o
/home/yeghia/build/cudf/cpp/build/_deps/rmm-src/include/rmm/device_scalar.hpp(38): **error: static assertion failed with "Scalar type must be trivially copyable"**
          detected during:
            instantiation of class "rmm::device_scalar<T> [with T=cudf::timestamp_D]" 
/home/yeghia/build/cudf/cpp/include/cudf/scalar/scalar.hpp(177): here
            instantiation of class "cudf::detail::fixed_width_scalar<T> [with T=cudf::timestamp_D]" 
/home/yeghia/build/cudf/cpp/include/cudf/scalar/scalar.hpp(489): here
            instantiation of class "cudf::chrono_scalar<T> [with T=cudf::timestamp_D]" 
/home/yeghia/build/cudf/cpp/include/cudf/scalar/scalar.hpp(534): here
            instantiation of class "cudf::timestamp_scalar<T> [with T=cudf::timestamp_D]" 
/home/yeghia/build/cudf/cpp/src/copying/shift.cu(64): here
            instantiation of "std::enable_if_t<<expression>, std::unique_ptr<cudf::column, std::default_delete<cudf::column>>> cudf::<unnamed>::shift_functor::operator()<T>(const cudf::column_view &, cudf::size_type, const cudf::scalar &, rmm::cuda_stream_view, rmm::mr::device_memory_resource *) [with T=cudf::device_storage_type_t<cudf::timestamp_D>]" 
/home/yeghia/build/cudf/cpp/include/cudf/utilities/type_dispatcher.hpp(456): here

Not sure how to proceed, any suggestions?

**Comment by kkraus14** [comment]
Hi @Yeghia, I believe we required GCC 7.5+ nowadays in compiling libcudf. We also no longer support CUDA 10.0, where our current minimum supported version is CUDA 10.1.

**Comment by Yeghia** [comment]
Hi @kkraus14, the cudf web [page ](https://github.com/rapidsai/cudf/blob/branch-0.19/CONTRIBUTING.md#setting-up-your-build-environment) says that the minimum GCC is 5.4+ and CUDA is 10.0+.
Is there a way to download an older version of cudf which can be compiled with GCC 7.3 and CUDA 10.0?

**Comment by kkraus14** [comment]
Apologies, that page is out of date. The last version of libcudf that supported CUDA 10.0 was version 0.14 which is 9+ months old as of now and will likely be very difficult to build. I would highly recommend upgrading your CUDA / GCC if possible. Building libcudf now is significantly easier than it was in version 0.14 as we've done extensive CMake work to make it smoother.

**Comment by Yeghia** [comment]
Thanks, @kkraus14! I understand, unfortunately, it is not that easy to upgrade, we are a large company, and the product we are working on is quite large as well, changing a compiler means we have to make the rest of the code to be compliant too. On top of that, we have schedules for releases, so it is a really complicated procedure.

Thus, I would prefer to try all existing possibilities before I push forward the topic of changing a compiler. So, if you can provide the instructions on where to get an older version, that will be great!

**Comment by kkraus14** [comment]
All of our previous releases are on github in tags. For 0.14, you can see it here: https://github.com/rapidsai/cudf/tree/v0.14.0

**Comment by Yeghia** [comment]
Thank you very much, @kkraus14! I will give it a try.

One more question, is there a version that supports GCC 5.2 and CUDA 10.0?

**Comment by kkraus14** [comment]
> Thank you very much, @kkraus14! I will give it a try.
> 
> One more question, is there a version that supports GCC 5.2 and CUDA 10.0?

You would have to go so far back to when it was `libgdf` instead of `libcudf` and I would *highly* recommend against doing that as the library was in a very immature state at that time.

**Comment by harrism** [comment]
Is it not possible for you to use precompiled packages?

**Comment by Yeghia** [comment]
> > Thank you very much, @kkraus14! I will give it a try.
> > One more question, is there a version that supports GCC 5.2 and CUDA 10.0?
> 
> You would have to go so far back to when it was `libgdf` instead of `libcudf` and I would _highly_ recommend against doing that as the library was in a very immature state at that time.

OK, understood!

**Comment by Yeghia** [comment]
> Is it not possible for you to use precompiled packages?

I would prefer that, of course, where can I find them?

**Comment by harrism** [comment]
https://rapids.ai/start.html#get-rapids

**Comment by vyasr** [comment]
Closing for now since the issue appears resolved. @Yeghia feel free to reopen if you're still having trouble
