### ISSUE TITLE
Update the cudf github pull-request-template instructions

### ISSUE THREAD

**Issue by davidwendt** [rapidsai/cudf#7699]
The current template still describes adding `[ ]` decorations to the PR. Sometimes these are accidentally left in during merge. Here are the two sections in the PULL_REQUEST_TEMPLATE.md that mention the `[ ]` text.

> 5. If your pull request is not ready for review but you want to make use of the
   continuous integration testing facilities please label it with `[WIP]`.

5. If your pull request is not ready for review but you want to make use of the
   continuous integration testing facilities please mark your pull request as Draft.

> 6. If your pull request is ready to be reviewed without requiring additional
   work on top of it, then remove the `[WIP]` label (if present) and replace
   it with `[REVIEW]`. If assistance is required to complete the functionality,
   for example when the C/C++ code of a feature is complete but Python bindings
   are still required, then add the label `[HELP-REQ]` so that others can triage
   and assist. ...

6. If your pull request is ready to be reviewed without requiring additional
   work on top of it, then remove it from "Draft" and make it "Ready for Review".
   If assistance is required to complete the functionality,
   for example when the C/C++ code of a feature is complete but Python bindings
   are still required, then add the label `help wanted` so that others can triage
   and assist. ...

**Comment by kkraus14** [comment]
> Sometimes these are accidentally left in during merge.

The gpucibot merger automatically removes the brackets during the merge.

**Comment by kkraus14** [comment]
I.E. https://github.com/rapidsai/cudf/pull/7724 --> https://github.com/rapidsai/cudf/commit/e2693e054566b7bd3c0892a8dfa07d7414967bfc

**Comment by davidwendt** [comment]
I did not realize that these were being stripped out.
So do you think it is not worth updating these instructions?
@harrism

**Comment by kkraus14** [comment]
I think the instructions are still a bit dated where we generally try to use draft PRs to indicate something is WIP as opposed to the `[WIP]` tag nowadays.

**Comment by harrism** [comment]
@davidwendt I like your suggested edits.

**Comment by davidwendt** [comment]
Closed by #7785
