### ISSUE TITLE
[BUG] Templated data accessors in column_view should not work with non-fixed-width types.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#7712]
The `column_view` data accessors (`begin`, `head,`,  `data`, etc) can be used with non-fixed-width templated types.  For example:

```
column_view c;
c.begin<struct_view>();
```

Aside from being wrong, this can obscure serious bugs in the code.  For example an implementation functor that has a default implementation, and only specializes for, say, string_view, can quietly compile (and fail terribly at runtime) for `list_view` or `struct_view`.  Example:

```
template<T>
void func(column_view const& c)
{
     auto x = c.begin<T>();
}

template<>
void func<string_view>(column_view const& c)
{
    //
}

```

**Comment by davidwendt** [comment]
You should really use `column_device_view` to access `begin(), end(), pair_begin(), pair_end()`. 
These work with fixed-width-types and strings columns and dictionary columns too.
That said, I would hate for the `column_view` ones to go away. 
They are really convenient when you know you are working with only fixed-width columns like offsets.

**Comment by jrhemstad** [comment]
We're not taking away the `column_view` ones, simply disabling them for types that aren't valid like `struct_view` or `string_view`.
