### ISSUE TITLE
[FEA] use `constexpr` instead of `__host__ __device__` whenever possible.

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#7713]
**Is your feature request related to a problem? Please describe.**
In libcudf, nvcc uses `--expt-relaxed-constexpr`. Both host and device code can call constexpr functions. constexpr functions also implies inline. It enables compile time evaluated functions both in device and host code. 
libcudf has many functions which could be converted to `constexpr`.

**Describe the solution you'd like**
Use `constexpr` instead of `__host__ __device__` and `CUDA_HOST_DEVICE_CALLABLE` whenever possible 

**Describe alternatives you've considered**
NA.

**Additional context**
https://en.cppreference.com/w/cpp/language/constexpr

**Comment by harrism** [comment]
I think we should close this in light of #7795. Please reopen if necessary.
