### ISSUE TITLE
[BUG] explode_outer_position doesn't match to Spark's counterpart 

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#7721]
**Describe the bug**
In cuDF,  `explode_outer_position` will mark the position values of empty rows with `0`. Meanwhile, the position values of empty rows are marked as `null` in Spark.

**Steps/Code to reproduce bug**
For input data like:
 * [[5,null,15], 100]
 * [null,        200]
 * [[],          300]
 
cuDF returns
 * [0,     5,    100]
 * [1,  null,    100]
 * [2,    15,    100]
 * [0,  null,    200]
 * [0,  null,    300]

But Spark returns
 * [0,     5,    100]
 * [1,  null,    100]
 * [2,    15,    100]
 * [null,  null,    200]
 * [null,  null,    300]

**Comment by hyperbolic2346** [comment]
I assume this holds for explode_position as well?

**Comment by sperlingxx** [comment]
> I assume this holds for explode_position as well?

I think current `explode_position` implementation is identicial to Spark, since the empty/null elements of array will be regarded as other values.
