### ISSUE TITLE
[FEA] GZIP decompression Performance Optimization

### ISSUE THREAD

**Issue by lixiaolx** [rapidsai/cudf#7723]
### Is your feature request related to a problem? Please describe.

In the analysis of read_ When decompressing the gzip of parquet operator, it is found that the current SM utilization is low, and there are many serials in the implementation. some findings：
- 1. When dealing with data blocks, we use serial traversal blocks.
- 2. There are many thread judgment branches in the kernel of each warp.

### Describe alternatives you've considered

I have some ideas, but I don't know the feasibility and difficulty. I need to confirm them as follows:

-  1.In the section of  "/ / main loop decoding blocks", can the blocks in gzip be processed in parallel so that each thread can process one block and the synchronization between threads can be reduced?
- 2.The current implementation is a threadblocks processing a page. Can you try a separate thread processing a page?

**Comment by kkraus14** [comment]
Unfortunately we haven't had the bandwidth to prioritize this work. At the same time, we have plans to migrate all of the compression and decompression functionality in libcudf to use https://github.com/nvidia/nvcomp.

Once gzip is migrated to using nvcomp we can explore optimizing it in there.

**Comment by GregoryKimball** [comment]
Now that libcudf has integrated with [nvCOMP](https://github.com/nvidia/nvcomp), I recommend reopening the issue in the nvCOMP repo with a clean test case and an Nsight Systems profile.
