### ISSUE TITLE
[BUG] cudf.io.read_csv of kaggle csv results in different output than pandas.read_csv 

### ISSUE THREAD

**Issue by kevingerman** [rapidsai/cudf#774]
using  cbg_b12.csv from [Kaggle - Census Block Group American Community Survey Data](https://www.kaggle.com/safegraph/census-block-group-american-community-survey-data)
```
import cudf
import pandas as pd

>>> df2=pd.read_csv( '/path/to/safegraph_open_census_data/data/cbg_b12.csv' )                                                                                                                                                   
>>> df1=cudf.io.read_csv( '/path/to/safegraph_open_census_data/data/cbg_b12.csv' )
>>> len(df1)
223828
>>> len(df2)
220333
```

**Expected behavior**
Expect that cudf.io.read_csv would generate an equivalent dataframe given the same input.   This problem occurs with some other kaggle csvs.

**Environment details (please complete the following information):**
Docker image built from source #fffc02ad19d2f17454a0739c856e9b9670aa7f88
` docker build -t $(basename $(pwd)):cuda9.2-ubuntu16.04-0.5.0 --label githash=$(git rev-parse HEAD) .`
`nvidia-docker run -ti -v $(pwd):/work -v /datasets:/datasets cudf:cuda9.2-ubuntu16.04-0.5.0 bash`
`source activate cudf`
...

**Additional context**
Pandas version: 0.20.3

**Comment by kevingerman** [comment]
A curious observation when I was poking around yesterday....
I took a series from the cudf.DataFrame created by reading the above file.     The len of that series matched the incorrect length of the dataframe.   However, after exporting that series to an array the len of the array was equal to the expected length for the dataframe.
```
>>> len(s1)
223769
>>> len( s1.to_array() )
220332
```

**Comment by vuule** [comment]
Strange. Perhaps data comparison can help triage the issue.
@kevingerman What is the result of the following comparison?
 pd.util.testing.assert_frame_equal(df2, df1.to_pandas())

**Comment by j-ieong** [comment]
It could be blank lines or empty fields leading to null values in the data frame. `to_array()` has a default  `fillna() = None` I think, which can result in skipping null values and returning a denser/smaller output.

**Comment by kkraus14** [comment]
@kevingerman that will call a `to_array(fillna='pandas')` under the hood so it won't drop the nulls.

**Comment by vuule** [comment]
The record count kernel is returning the wrong count. 
The issue is somehow related to '\r\n' used in this file. I'm investigating to see what exactly is going on.
