### ISSUE TITLE
[BUG] How to convert a cudf Series of lists to 2D array ?

### ISSUE THREAD

**Issue by gandroz** [rapidsai/cudf#7745]
I try to run a TSNE analysis on some data. The data is stored as a Series of arrayas in a pandas dataframe

![image](https://user-images.githubusercontent.com/38106881/112735938-70905080-8f25-11eb-9576-c804d17958e8.png)

The embeddings is a pandas Series of arrays. I load the dataframe to `cudf` like this

```
pandas_df = pd.read_pickle("data.pkl")
cudf_df = cudf.DataFrame.from_pandas(pandas_df)
```

then I try to perform a TSNE fit on the data

```
tsne = TSNE(n_components=2, verbose=1, perplexity=50, init='pca', n_iter=300)
tsne_results_fr = tsne.fit_transform(pandas_df.minmax);
```

but I got the following error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-daa306b963f1> in <module>
      1 tsne = TSNE(n_components=2, verbose=1, perplexity=50, init='pca', n_iter=300)
----> 2 tsne_results_fr = tsne.fit_transform(pandas_df.minmax);

~/miniconda3/envs/nlp/lib/python3.8/site-packages/cuml/internals/api_decorators.py in inner(*args, **kwargs)
    594 
    595                 # Call the function
--> 596                 ret_val = func(*args, **kwargs)
    597 
    598             return cm.process_return(ret_val)

cuml/manifold/t_sne.pyx in cuml.manifold.t_sne.TSNE.fit_transform()

~/miniconda3/envs/nlp/lib/python3.8/site-packages/cuml/internals/api_decorators.py in inner_with_setters(*args, **kwargs)
    408                                 target_val=target_val)
    409 
--> 410                 return func(*args, **kwargs)
    411 
    412         @wraps(func)

cuml/manifold/t_sne.pyx in cuml.manifold.t_sne.TSNE.fit()

ValueError: data should be two dimensional
```

My guess is that providing the cudf Series is interpreted as a "list" whereas it expects kind of a 2D array. I tried

```
cudf_df.embedding.to_array()
```

but got an error

```
TypeError: *obj* doesn't implement the cuda array interface.
```

Expected behavior:
Either allow to pass a list of arrays or to convert it to a 2D array

**Comment by kkraus14** [comment]
@gandroz this isn't directly supported since the lists could be of variable length. What you can do is use the `.list.leaves` method to get a flatten view of the list column zero-copy: https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.column.lists.ListMethods.leaves

Then from there you should be able to do something like `cupy.asarray(flattened_series).reshape(...)` to get a 2d array and every operation in this chain should be zero-copy.

**Comment by beckernick** [comment]
Since this question has been answered and gotten a thumbs up, I'm going to close the issue. Please feel free to re-open to continue the discussion.
