### ISSUE TITLE
[FEA] Use __builtin_unreachable for unreachable code paths 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#7753]
**Is your feature request related to a problem? Please describe.**

The `type_dispatcher` currently has a [`default` case](https://github.com/rapidsai/cudf/blob/cddafd9b1dd3ab815020a513626a611cd8a50de0/cpp/include/cudf/utilities/type_dispatcher.hpp#L500-L514) to avoid a compiler warning about missing a return statement, even though that code path can never be taken.

This is annoying because we're forced to return _something_, and arbitrarily chose a default constructed object of whatever type the other cases return. This is problematic if the thing you're returning isn't default constructible. 

**Describe the solution you'd like**

We can use `__builtin_unreachable()` instead. 

For host code, this is already supported by gcc.

For device code,[ nvcc adds support in 11.3](https://developer.nvidia.com/blog/boosting-productivity-and-performance-with-the-nvidia-cuda-11-2-c-compiler/). 

Once we've moved to CUDA enhanced compatibility and are compiling with the 11.3 compiler, we should switch to using `__builtin_unreachable()` and remove the default case of returning a default constructed object.

**Comment by jrhemstad** [comment]
I think we should add a macro to wrap this functionality that will also insert an `assert` such that if we ever _do_ hit a region of code that is supposed to be unreachable, we'll have a way of finding that out in a debug build:

```
#define CUDF_UNREACHABLE(msg) do{assert(false && "Unreachable: " msg); __builtin_unreachable(); } while(0)
```

Example: https://godbolt.org/z/Tavr19K9s

**Comment by jrhemstad** [comment]
We can provide similar wrappers for `__builtin_assume` and `__builtin_assume_aligned`, but these can be functions instead of macros: https://godbolt.org/z/qYxvKP68b

**Comment by ttnghia** [comment]
Is there any standard attribute `[[unreachable]] ` for this purpose? I am reluctant to have vendor-specific attributes.

**Comment by jrhemstad** [comment]
> Is there any standard attribute `[[unreachable]] ` for this purpose? I am reluctant to have vendor-specific attributes. Edit: I found only a (2017) proposal for it but probably it didn't go in C++ standard yet.

No, but it is supported by the compilers we care about (gcc and nvcc).
