### ISSUE TITLE
[FEA] Add scalar support for struct

### ISSUE THREAD

**Issue by razajafri** [rapidsai/cudf#7790]
**Is your feature request related to a problem? Please describe.**
This issue tracks discussion on how we can support a STRUCT scalar, which may need changes on the CPP side as well once we discuss what the layout should be.

**Describe the solution you'd like**
Ability to create a Scalar Struct

**Describe alternatives you've considered**
None.

**Comment by jrhemstad** [comment]
Related https://github.com/rapidsai/cudf/issues/5887
