### ISSUE TITLE
[FEA] Convert Binary Operations to use device-side type dispatch rather than JIT

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#7801]
JIT overhead for binary ops is a problem in some situations. @karthikeyann did an [experiment](https://github.com/rapidsai/cudf/pull/4269) a while back to use device-side dispatch rather than JIT. The compile time cost was low, and performance was good. 

Compiled binops use a single compiled kernel (per operation) with device-side type dispatch, so the code should be simpler.  The operation dispatch can be on the host, but there are only a small number of operations relative to the combinations of types and operations, so this should not be expensive.

**Comment by jrhemstad** [comment]
For this, I think it'd make sense to make a `triple_type_dispatcher`, ala https://github.com/rapidsai/cudf/blob/24f301605fe19c66c336e93d71565169b6fdcab1/cpp/include/cudf/utilities/type_dispatcher.hpp#L546-L570

**Comment by cwharris** [comment]
> JIT overhead for binary ops is a problem in some situations.

Can we get more specific here? How we handle JIT compilation was recently changed with jitify2. Is it possible some of these problems are alleviated?

**Comment by harrism** [comment]
@cwharris one important Spark use case runs on platforms where they can't write a JIT cache so every worker pays the JIT overhead.

**Comment by karthikeyann** [comment]
integration to sparks, python pending.
