### ISSUE TITLE
[FEA] support collect aggregations in reduction

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#7807]
**Is your feature request related to a problem? Please describe.**
Currently, cuDF supports collect aggregations in rolling windows and groupBy context (though the support is not complete). But, collect aggregations in reduction context is still missing.

**Additional context**
I believe we can not support this feature until #5887 got solved, since scalar of ListType is essential in reduction to collect.

**Comment by jrhemstad** [comment]
A collect reduction doesn't make much sense to me. Turn an entire column into a list column with a single list?

**Comment by sperlingxx** [comment]
@jrhemstad Yes, it basically turns an entire column into a list column with a single list. We need this feature because we want to provide GPU support of spark built-in function `collect_list`(`collect_set`) with reduction.  Here is the example:
```sql
> SELECT collect_list(col) FROM VALUES (1), (2), (1) AS tab(col);
 [1,2,1]
> SELECT collect_set(col) FROM VALUES (1), (2), (1) AS tab(col);
 [1,2]
```
So, we need a method to produce scalars (in ListType) from corresponding input columns. It matches to the semantic of reduce.
