### ISSUE TITLE
[QST]running cudf of cpu

### ISSUE THREAD

**Issue by naarkhoo** [rapidsai/cudf#7824]
I am developing a ML pipeline on my macbook pro laptop to be deployed on a server which has NVDIA servers. There is not ssh, neither interactive terminal to work with the server. The challenge is I wish I could make my code in my laptop, debug and make sure it works and the send it out to the server. However, I seems I can't have CUDF running on my laptop due to the hardware.

In TensorFlow using a parameter I can set the hardware to be cpu or gpu and TF will take care of the rest. This is very handy since one can develop the code with cpu but deploy on gpu. 

I wonder if there is any recommendation in such a setup - where I can keep developing the pipeline with CUDF on my laptop but be able simple to run it on GPU ?

**Comment by kkraus14** [comment]
@naarkhoo the general guidance we give here is if you're using `cuDF` directly to use pandas instead of `cuDF` and if you're using `dask-cudf` to use `dask.dataframe` instead. As of now, our stance is that it's out of scope to add a CPU implementation for cuDF.

**Comment by naarkhoo** [comment]
I understand. The code is in Pandas and works perfectly on the PC but extremely slow (given the data size). I need to translate it to CUDF - but as it is now, not possible to debug/troubleshoot easily.

**Comment by kkraus14** [comment]
Closing this issue as the question has been answered.
