### ISSUE TITLE
[FEA] Logging in libcudf

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#7861]
Certain libcudf functions need to send warnings to users. 
Examples:
1. #7152 : We deviate from typical parquet writer behaviour and as a result the written file is unreadable by certain other libraries. We'd prefer to warn the user about it but not throw an exception. https://github.com/rapidsai/cudf/issues/7152#issuecomment-801407395
2. We want to warn the user when despite specifying, GDS is not available to be used https://github.com/rapidsai/cudf/pull/7444#issuecomment-801457142

These warnings can be part of a log and in general libcudf can have logging similar to RMM.

**Comment by jlowe** [comment]
Similar to https://github.com/rapidsai/rmm/issues/564 I'd like to see the ability for the application to provide a logging sink to better control the handling of any log messages.  Emitting uncontrollable messages to stdout or creating files in the current directory will be problematic for some use-cases.  Providing a log sink adapter or some similar interface allows the libcudf log messages to be funneled to any existing logging mechanism the app may be using.

**Comment by vuule** [comment]
Some new potential uses in cuIO:
warn on fallback to host JSON tree traversal
warn on compression failure in Parque and ORC writers
info about nvCOMP use (vs internal implementations)

**Comment by vuule** [comment]
Finally revisiting this :)

Initial design thoughts:

- Use [spdlog library](https://github.com/gabime/spdlog) (header-only).
- Have a global logger that's initialized on first use.
- Default logging level is WARNING (or maybe OFF initially).
- Provide a way to customize logging level and sink. One or more of the following:
  - At build time - CMake flags to set level (maybe also sink, e.g. file vs stdout);
  - During intialization - environment variables, again can control level and basic sink options.
  - At runtime (any point) - libcudf API that allows more control, like providing custom sink(s).

@jlowe is a libcudf API what you had in mind in your request? It would need to be called before any other libcudf functions to avoid potentially logging with default settings.

**Comment by vyasr** [comment]
Just a note, spdlog can be used header-only or precompiled. Given that we use it header-only in rmm since rmm itself is header-only, it may not help compile times in libcudf to use its compiled mode here, but if we do go the spdlog route it's worth checking on the compile times before @davidwendt comes after you 😄

**Comment by GregoryKimball** [comment]
Now that we have merged https://github.com/rapidsai/cudf/pull/12637, I'd like to close this issue and continue the discussion for additional logging items in new issue(s).

**Comment by vuule** [comment]
@GregoryKimball regarding the additional logging items: I opened a PR for cuIO warnings that are not related to integrations https://github.com/rapidsai/cudf/pull/13043. cuIO ntegrations should be covered as well in 23.06.
