### ISSUE TITLE
[BUG] Constructing from a nested numpy array of bools yields malformed list type series

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#7869]
**Describe the bug**

Making a list type column with bools as the leaf type gets me the wrong result using a certain API. 

**Steps/Code to reproduce bug**
This works for every data type except bool:

```python
data = [np.array([1,2,3])]
cudf.Series(data)
# 0    [1, 2, 3]
# dtype: list
```
```python
data = [np.array([True, True, True])]
cudf.Series(data)
# 0    True
# dtype: bool
```

**Expected behavior**
I should get 

```
# 0    [True, True, True]
# dtype: list
```

**Environment overview (please complete the following information)**
 - Environment location: Bare Metal
 - Method of cuDF install: Source

**Comment by galipremsagar** [comment]
This issue is resolved now:

```python
>>> import numpy as np
>>> import cudf
>>> data = [np.array([1,2,3])]
>>> cudf.Series(data)
0    [1, 2, 3]
dtype: list
>>> data = [np.array([True, True, True])]
>>> cudf.Series(data)
0    [True, True, True]
dtype: list
>>> cudf.__version__
'21.12.00a+226.geda31b6385.dirty'
```
