### ISSUE TITLE
[FEA] Using struct as return values instead of `std::pair` and `std::tuple`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#7885]
**Is your feature request related to a problem? Please describe.**
Currently, cudf has a lot of APIs that return `std::pair` or `std::tuple`. For example:

```
std::tuple<table_view,
           std::vector<order>,
           std::vector<null_order>,
           std::vector<std::unique_ptr<column>>>
flatten_nested_columns(...)
```

In order to access the result component, we need to use:
```
auto result = flatten_nested_columns(...);

auto table = std::get<0>(result);
auto orders = std::get<1>(result);
auto null_precedence = std::get<2>(result);
....
```

How to know which component index to call `std::get<component_index>()` ? The only way is to look up the API doxygen.
This usage is very ambiguous and the code is very difficult/time-consuming to maintain.

**Describe the solution you'd like**
Using a struct as a return value, instead of `std::pair` or `std::tuple`.

For example:
```
struct flatten_nested_columns_result {
    table_view table;
    std::vector<order> column_orders;
    std::vector<null_order> null_precedences;
    std::vector<std::unique_ptr<column>> column_validities;
};

flatten_nested_columns_result flatten_nested_columns(...)
```

Then, for usage:
```
auto result = flatten_nested_columns(...);

auto table = result.table;
auto orders = result.column_orders;
auto null_precedence = result.null_precedences;
....
```

This shows very cleary what result component we are accessing, certainly can avoid mistake, and we don't need to look up the API doxygen to verify/understand the code.

**Comment by jrhemstad** [comment]
I think using a `pair` is fine when returning 2 things, but for more than 2 things, a custom type is likely preferred to a `tuple`.

That said, I think this becomes irrelevant with C++17 structured bindings.

**Comment by ttnghia** [comment]
Ah, yes, structure binding! Thanks for reminding me that. Then we can switch to use structure binding all the time when it is ready. Close issue.
