### ISSUE TITLE
[FEA] Have CUDA  runtime controls via only CMAKE_CUDA_RUNTIME_LIBRARY

### ISSUE THREAD

**Issue by robertmaynard** [rapidsai/cudf#7888]
Currently cudf exposes the CMake variable `CUDA_STATIC_RUNTIME` to control which runtime library should be used. Instead we should directly use CMAKE_CUDA_RUNTIME_LIBRARY ( https://cmake.org/cmake/help/latest/variable/CMAKE_CUDA_RUNTIME_LIBRARY.html )

This comes from the discussion in https://github.com/rapidsai/cudf/issues/7600 and https://github.com/rapidsai/cudf/pull/7887

**Comment by vyasr** [comment]
Migrating to https://github.com/rapidsai/build-planning/issues/4
