### ISSUE TITLE
[FEA] Remove CUDA 10.x compiler bug work arounds

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#7913]
**Is your feature request related to a problem? Please describe.**

There are several places where CUDA 10.x compiler bugs forced us to put in work arounds. 

Examples: 
https://github.com/rapidsai/cudf/blob/192ff46cb18c44360536eb413eb185b92b5cd4d4/cpp/src/groupby/hash/groupby.cu#L58-L59

https://github.com/rapidsai/cudf/blob/192ff46cb18c44360536eb413eb185b92b5cd4d4/cpp/src/groupby/groupby.cu#L122-L125

I believe there are more, but don't know them off the top of my head. 

**Describe the solution you'd like**
Now that https://github.com/rapidsai/cudf/pull/7780 is merged, we should remove those.

**Comment by davidwendt** [comment]
I volunteer to fix the ones I added here for dictionary support.

**Comment by davidwendt** [comment]
I believe these are all removed now. Checking with @karthikeyann as well.

**Comment by davidwendt** [comment]
I believe all of these have been addressed so going to close this.
We can re-open it any have been missed.
