### ISSUE TITLE
[DOC] Missing 'regex' and 'method' documentation at DataFrame.replace() method

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#7924]
## Report incorrect documentation
`regex` and `method` parameters seem to do not be documented.
![image](https://user-images.githubusercontent.com/26169771/114161524-77a55e80-9928-11eb-99e8-db990920d989.png)

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/nightly/api.html#cudf.core.dataframe.DataFrame.replace

**Describe the problems or issues found in the documentation**
The parameters above seem to do not be documented.

**Suggested fix for documentation**
To have them documented.

**Comment by davidwendt** [comment]
Looks like this has been fixed in 21.10 https://docs.rapids.ai/api/cudf/stable/api_docs/api/cudf.core.column.string.StringMethods.replace.html
