### ISSUE TITLE
[BUG] Hash join on structs throw exception caused by flattening null mask  

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#7936]
**Describe the bug**
If probe table contains a non-null struct column and build table contains a nullable corresponding struct column, the number of columns of probe and build table will be different after `structs::detail::flatten_nested_columns`. Because build table contains extra column to represent validity of struct. The difference will fail the assertion at `cudf/cpp/src/join/hash_join.cu:365` with message  `Mismatch in number of columns to be joined on`.

**Steps/Code to reproduce bug**
```c++
auto int_col_a  = column_wrapper<int32_t>{{48, 27, 351, 31, 25}};
auto struct_col_a = cudf::test::structs_column_wrapper{{int_col_a}};
auto int_col_b  = column_wrapper<int32_t>{{351, 25, 27, 31, 48}};
auto struct_col_b = cudf::test::structs_column_wrapper{{int_col_b}, {1, 1, 0, 1, 1}};
std::vector<std::unique_ptr<cudf::column>> cols_a, cols_b;
cols_a.push_back(struct_col_a.release());
cols_b.push_back(struct_col_b.release());
Table ta(std::move(cols_a));
Table tb(std::move(cols_b));
auto result = cudf::inner_join(ta, t1, {0}, {0});
```

**Comment by jrhemstad** [comment]
@hyperbolic2346 @karthikeyann Unless you guys can think of a better solution, I'm guessing we should always materialize a bool mask for a struct column to avoid this.

**Comment by hyperbolic2346** [comment]
Is it valid to compare a nullable and all valid struct column with a non-nullable and by default all valid struct column equal?

**Comment by jrhemstad** [comment]
> Is it valid to compare a nullable and all valid struct column with a non-nullable and by default all valid struct column equal?

If I'm understanding you correctly, then yes. For any column type, a non-nullable column is effectively equivalent to a nullable column with an all valid null mask.

**Comment by hyperbolic2346** [comment]
I agree then that always adding a null mask is the best approach.

**Comment by jrhemstad** [comment]
> I agree then that always adding a null mask is the best approach.

On second thought, I think this is only relevant for Join. For sorting I don't think it's necessary to always expand a non-nullable struct column's bool mask. Perhaps it needs to be a parameter to the flatten fucntion.
