### ISSUE TITLE
[FEA] Revisit grid dimensions for cuIO kernels

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#7943]
After several cooperative loading of structs was removed from several cuIO kernels in #, many of them had no longer a need for a larger block size. The general pattern went from:
```cuda
__global__ kernel(some_struct_t *obj) {
  __shared__ some_struct_t s;
  auto t = threadIdx.x;
  if (t == 0) {
    // some processing
  }
  if (t < sizeof(some_struct_t) / sizeof(uint32_t)) { 
    ((volatile uint32_t *)&s)[t] = ((const uint32_t *)&obj[id])[t]; 
  }
__syncthreads();
  if (t == 0) {
    // some more processing
  }
}
```
to 
```cuda
__global__ kernel(some_struct_t *obj) {
  __shared__ some_struct_t s;
  auto t = threadIdx.x;
  if (t == 0) {
    // some processing
  }
  if (t == 0) { 
    s = obj[id];
  }
  __syncthreads();  // Not needed anymore
  if (t == 0) {
    // some more processing
  }
}
```
We should hunt down all such cases and simplify the block dimensions so that we can remove all `if (t == 0)` conditions and merge the code blocks, and remove the unnecessary synchronizations.

### Some examples:
https://github.com/rapidsai/cudf/blob/0ca82ea357312771e0be347fe1964d51c88018e1/cpp/src/io/parquet/page_enc.cu#L398
https://github.com/rapidsai/cudf/blob/0ca82ea357312771e0be347fe1964d51c88018e1/cpp/src/io/parquet/page_enc.cu#L1501
https://github.com/rapidsai/cudf/blob/0ca82ea357312771e0be347fe1964d51c88018e1/cpp/src/io/parquet/page_enc.cu#L424

**Comment by GregoryKimball** [comment]
Here is an excellent example of a kernel that only uses thread 0:
https://github.com/rapidsai/cudf/blob/f6e9666412715927798baaff41996dbaac20dc43/cpp/src/io/parquet/page_enc.cu#L247
