### ISSUE TITLE
[BUG] No binaries for CUDA 10 on Conda channels or PyPi

### ISSUE THREAD

**Issue by MasoodK** [rapidsai/cudf#795]
**Describe the bug**
pip: There seems to be no -cuda100 packages on PyPi and "pip install cudf-cuda100" fails; README suggests it's there.

Conda: I have CUDA 10 installed with the env variables set up (CUDA_HOME, LD_LIBRARY_PATH, PATH), but Conda wants to install binaries for 9.2 after "solving the environment." I don't see any CUDA 10 binaries here: https://conda.anaconda.org/rapidsai/linux-64

I have and need CUDA10 and if I go ahead and install the existing binary for 9.2, I'll get the following error after `import cudf`: OSError: cannot load library 'librmm.so': libcudart.so.9.2: cannot open shared object file: No such file or directory
And symlinking `libcudart.so.9.2` to `libcudart.so` (which is linked to v10) does not work.

Is there a possibility to have a binary either on PyPi or conda for CUDA 10 in the next few days?
Thanks in advance!
Details below:

**Environment details:**
 - Environment location: AWS p3.2xlarge (V100), CentOS, python 3.6
 - Method of cuDF install:
conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf
pip install cudf-cuda100

**Additional context**
--------------------------------------------
Conda log:
        (gpu) [root@ip-*** ]# conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /workspace/Anaconda/envs/gpu

  added / updated specs:
    - cudf

The following NEW packages will be INSTALLED:

  cffi               conda-forge/linux-64::cffi-1.11.5-py36h9745a5d_1001
  cudf               rapidsai/linux-64::cudf-0.4.0-py36_0
  cython             conda-forge/linux-64::cython-0.28.5-py36hf484d3e_1000
  libcudf            rapidsai/linux-64::libcudf-0.4.0-cuda9.2_0
  libcudf_cffi       rapidsai/linux-64::libcudf_cffi-0.4.0-cuda9.2_py36_0
  llvmlite           numba/linux-64::llvmlite-0.27.0-py36hf484d3e_0
  numba              numba/linux-64::numba-0.42.0-np115py36hf484d3e_0
  nvstrings          nvidia/linux-64::nvstrings-0.2.0-cuda9.2_py36_3
  pycparser          conda-forge/noarch::pycparser-2.19-py_0

The following packages will be SUPERSEDED by a higher-priority channel:

  parquet-cpp        conda-forge/noarch::parquet-cpp-1.5.1~ --> conda-forge/linux-64::parquet-cpp-1.5.0.pre-h83d4a3d_0

The following packages will be DOWNGRADED:

  arrow-cpp                        0.11.1-py36h0e61e49_1004 --> 0.10.0-py36h70250a7_0
  boost-cpp                            1.68.0-h11c811c_1000 --> 1.67.0-h3a22d5f_0
  pandas                              0.24.0-py36hf484d3e_0 --> 0.20.3-py36_1
  pyarrow                          0.11.1-py36hbbcf98d_1002 --> 0.10.0-py36hfc679d8_0
  thrift-cpp                           0.12.0-h23e226f_1000 --> 0.11.0-hafb3f75_3

Proceed ([y]/n)?

**Comment by datametrician** [comment]
You're looking at the wrong branch. In the master branch it's clear we haven't released that yet.  The release will be out soon and merged to master. Thank you for your patience.
