### ISSUE TITLE
[BUG] cuda throws an unexpect error code when allocating host memory

### ISSUE THREAD

**Issue by wjxiz1992** [rapidsai/cudf#7964]
**Describe the bug**
It's a query running in Spark with RAPIDS plugin. The error message:

```
Caused by: ai.rapids.cudf.CudfException: CUDA error encountered at: /home/jenkins/agent/workspace/jenkins-cudf_nightly-pre_release-github-6-cuda10.1/cpp/src/io/utilities/hostdevice_vector.hpp:60: 800 cudaErrorNotPermitted operation not permitted
  	at ai.rapids.cudf.Table.writeParquetChunk(Native Method)
  	at ai.rapids.cudf.Table.access$300(Table.java:45)
  	at ai.rapids.cudf.Table$ParquetTableWriter.write(Table.java:858)
  	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$writeBatch$2(ColumnarOutputWriter.scala:151)
  	at com.nvidia.spark.rapids.ColumnarOutputWriter.$anonfun$writeBatch$2$adapted(ColumnarOutputWriter.scala:148)
```

But: 
_cuda10.1/cpp/src/io/utilities/hostdevice_vector.hpp:60:_ is `CUDA_TRY(cudaMallocHost(&h_data, sizeof(T) * max_elements));`

which should return cudaSuccess, cudaErrorInvalidValue, cudaErrorMemoryAllocation but not `cudaErrorNotPermitted = 800`

**Environment details**
Docker image: nvcr.io/nvidian/swgpu-spark/spark-ucx:3.0.2-cuda10.1-ubuntu18.04
In NGC cloud.

**Comment by jrhemstad** [comment]
Hm, the only time I've seen `cudaErrorNotPermitted` is when trying to make CUDA RT calls inside a host call back function added with `cudaStreamAddCallback`. I don't think that's being used in the Spark plugin, so I'm a bit mystified by that error. I wonder if some systems disallow allocating page locked memory?

**Comment by jlowe** [comment]
There's a ulimit setting for maximum amount of locked memory, maybe we're hitting that limit?  See the output of `ulimit -a`

**Comment by wjxiz1992** [comment]
> There's a ulimit setting for maximum amount of locked memory, maybe we're hitting that limit? See the output of `ulimit -a`

```
root@1918940:/# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2062918
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1048576
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 65536
cpu time               (seconds, -t) unlimited
max user processes              (-u) unlimited
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

```

**Comment by wjxiz1992** [comment]
We are still getting this error sometimes (not 100% reproduce).
What else should I provide here?

**Comment by harrism** [comment]
@wjxiz1992 since it's been a while, and we've dropped CUDA 10.x support in the latest, could you try with the latest RAPIDS to see if this still happens?

**Comment by wjxiz1992** [comment]
@harrism No there's no such error under latest cuDF with CUDA11.
