### ISSUE TITLE
[FEA] Request a cudf function for `reverse` 

### ISSUE THREAD

**Issue by wmalpica** [rapidsai/cudf#7967]
**Is your feature request related to a problem? Please describe.**
I would be useful to have the ability to make a reverse copy of a column and/or table. 
I am thinking of `std::reverse` (https://en.cppreference.com/w/cpp/algorithm/reverse) . But not necessarily using iterators, since that might make things more complicated.

**Describe the solution you'd like**
The following APIs could be very useful (and hopefully self describing):
std::unique_ptr<column> reverse(column_view const& source);
std::unique_ptr<table> reverse(table_view const& source);
void reverse_in_place(mutable_column_view & mutable);
void reverse_in_place(mutable_table_view & mutable);

**Describe alternatives you've considered**
Right now if i want to make a reverse copy, i would have to make a `sequence` of indexed going from high to low and then go a `gather`, which is a lot less efficient.

**Additional context**

**Comment by jrhemstad** [comment]
This should be pretty straightforward to implement using the `detail::gather` that takes an iterator and using a counting iterator that goes in reverse.

**Comment by shaneding** [comment]
If no one else is currently working on this issue, I would love to take it on to get a better understanding of the c++ part of the codebase.

**Comment by shaneding** [comment]
@williamBlazing just wanted to check in since `reverse` is already [exposed](https://github.com/rapidsai/cudf/blob/8834ed64855f767065be3b8a12adf0b97284241c/python/cudf/cudf/core/series.py#L3674) at the python level. So would that suffice, or did you actually want this at the C++ layer?

**Comment by harrism** [comment]
@shaneding I think you should follow @jrhemstad 's advice and implement it in libcudf C++ using `detail::gather` and then expose it to Python via Cython. For the structure of files and APIs and Cython, I think you could look at a similar API, like `cudf::repeat`. 

- header: `cpp/include/cudf/filling.hpp`
- detail header: `cpp/include/cudf/detail/repeat.hpp`, 
- implementation: `cpp/src/filling/repeat.cu`
- Cython: `python/cudf/_lib/filling.[pxd, pyx]`

Please also check out `cpp/DEVELOPER_GUIDE.md` for general guidelines.
