### ISSUE TITLE
[FEA] `.describe()` after `DataFrameGroupBy`

### ISSUE THREAD

**Issue by HanwGeek** [rapidsai/cudf#7990]
**Is your feature request related to a problem? Please describe.**

if I want to get `describe()` information after a `.groupby()` operation. But I got:
```python
AttributeError: 'DataFrameGroupBy' object has no attribute 'describe'
```

**Describe the solution you'd like**
When I execute this:
```python
df.groupby(['col1', 'col2'])[['col3', 'col4']].describe()
```
I would like to get results the same as `pandas`.

Thank you very much! Feel free to make any comment about this issue.

**Comment by kkraus14** [comment]
Looks like this is the equivalent of running `DataFrameGroupBy.agg(['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max'])` and I believe we support all of these aggregations already.

**Comment by HanwGeek** [comment]
Thank you for your reply! And I think these could satisfy my needs. I will close this issue.

**Comment by kkraus14** [comment]
Reopening this as we should still support this feature. Glad to hear there's a nice workaround though!

**Comment by quasiben** [comment]
This is being actively worked on here: https://github.com/rapidsai/cudf/pull/8179
