### ISSUE TITLE
[QST] Queston about row number limit in cuDF dataframe

### ISSUE THREAD

**Issue by lastephey** [rapidsai/cudf#7991]
Dear cuDF developers,

I am using Dask to load in some parquet data as a dask-cudf dataframe. When I use `.compute()` to convert from dask-cudf back to cuDF (I need some functions that aren't supported in dask-cudf) I am encountering this error:

```
RuntimeError: cuDF failure at: ../src/copying/concatenate.cu:365: Total number of concatenated rows exceeds size_type range
```

My dataframe has 27 million rows which seems... large but maybe still reasonable? What is the row limit? Is there any way I can increase this limit? 

If I can provide more info please let me know.

Thank you very much,
Laurie

**Comment by davidwendt** [comment]
The row limit for a cudf column/dataframe is 2 billion (2,147,483,647).

**Comment by beckernick** [comment]
> When I use .compute() to convert from dask-cudf back to cuDF (I need some functions that aren't supported in dask-cudf) I am encountering this error:

Would you be able to share which operations aren't supported in dask-cudf?

In the meantime, could you stay in Dask land but use the cudf operations with `ddf.map_partitions(custom_func)` to operate independently on each individual DataFrame partition?

**Comment by lastephey** [comment]
Thank you for your quick responses, David and Nick.

Sure, a few of the operations I'm using in cuDF:
* `cudf.melt`
* `cudf.to_datetime`
* `cudf.drop_duplicates`

Thank you for the suggestion-- I can try the map partitions approach and report back. 

I am wondering why I hit this row limit when I am well under 2 billion rows. Does it sound like a possible bug? If so I am happy to file a report.

**Comment by beckernick** [comment]
Thanks Laurie!

This likely came up due to non numeric columns in the table. For example, the ~2 billion MAX(int32) limit on string columns presents based on the number of individual characters, rather than rows.


> Sure, a few of the operations I'm using in cuDF:
> cudf.melt
> cudf.to_datetime
> cudf.drop_duplicates

drop_duplicates and melt should be available as `ddf.drop_duplicates` and `ddf.melt`. For `to_datetime`, could you intead explicitly cast the column with `ddf[col].astype("datetime64[ms]")?

**Comment by lastephey** [comment]
Thanks Nick. Ok I see, the row limit makes sense.

Thanks for the pointer about melt and drop_duplicates. I see now I was trying to use them incorrectly, like:

```
dask_cudf.melt(ddf)
```
instead of

```
ddf.melt()
```

I think I should be able to make this work within Dask using your suggestions. I'll close this, thank you very much for your help!

**Comment by cboettig** [comment]
> The row limit for a cudf column/dataframe is 2 billion (2,147,483,647).

Is this still the case?  Is this configurable?
