### ISSUE TITLE
[FEA] min and max aggregation and reduction for single level struct types

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#7995]
**Is your feature request related to a problem? Please describe.**
We would like to be able to support the `min` and `max` SQL operators for single level structs (No nesting) in Spark.  By this I mean that a struct of strings is required to be supported, but a struct of lists or a struct of other structs is not.

**Describe the solution you'd like**
It would be great if we could get the existing `min` and `max` aggregations to work on non-nested structs for group by aggregations and reductions.  Bonus points if we can make it work for window operations too, but that is not a requirement.

**Describe alternatives you've considered**
Because of how the group by aggregations work there really is no way for us to pick apart the struct and do the aggregation using existing APIs.

**Additional context**
This should follow the rules that min/max already support, and also match with sorting for structs https://github.com/rapidsai/cudf/pull/7422

Min should return the minimum non-null value in the range. If all of the values in the range are null then null is returned.
The minimum value should be determined by the ordering of a struct with in ascending order with nulls last for each of the child columns.

Max should return the maximum non-null value in the range. If all of the values in the range are null then null is returned.
The maximum value should be determined by the ordering of a struct with in ascending order with nulls last for each of the child columns.

```
scala> df.orderBy(col("b"), col("a")).show
+------+---+
|     a|  b|
+------+---+
|  null|  1|
|   [,]|  1|
| [, 1]|  1|
|  [1,]|  1|
|[1, 1]|  1|
|  null|  2|
+------+---+


scala> df.groupBy("b").agg(max(col("a")), min(col("a"))).show
+---+------+------+
|  b|max(a)|min(a)|
+---+------+------+
|  1|[1, 1]|   [,]|
|  2|  null|  null|
+---+------+------+
```

In this case we have a struct column `a` with two string entries in it.  If the string is printed as an empty string it is really null (Sorry that is how spark does it)  So the minimum value for group 1 is `[,]` or both null values. This is because the null struct itself is filtered out and nulls child columns are last (min) in ascending order.  Where as for group 2 where all of the structs are null, then a null is returned. 

I would love to hear from the python side if they have different requirements.

**Comment by kkraus14** [comment]
Python generally doesn't have strict requirements for struct columns since Pandas stores a column of Python dictionaries in this situation and defers to Python dictionary semantics which doesn't allow comparisons. Generally, I would just push for our null handling semantics to be consistent with parent and children columns.

**Comment by revans2** [comment]
this is still wanted

**Comment by ttnghia** [comment]
This should be closed as it has been addressed.
Other remaining structs works are here: https://github.com/rapidsai/cudf/issues/8974
