### ISSUE TITLE
[FEA] Expose list accessor on dask-cudf series

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#7997]
Today, I can manipulate ListDtype columns and execute operations like segmented sort and unique. Because these operations do not have cross-row (or cross-partition) dependencies, they can be executed in Dask by passing a lambda function to `map_partitions`.

It would be nice to expose the `list` accessor on dask-cuDF objects like we do for other accessors. As this is not supported by pandas, perhaps this could be plumbed up directly in dask-cudf.

```python
import cudf
import dask_cudf
​
s = cudf.Series([[3,0], [2,2], [3,-5]])
ds = dask_cudf.from_cudf(s, 1)
​
print(s.list.unique())
print(ds.map_partitions(lambda x: x.list.unique(), meta=ds._meta).compute())
print(ds.list)
0     [0, 3]
1        [2]
2    [-5, 3]
dtype: list
0     [0, 3]
1        [2]
2    [-5, 3]
dtype: list
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-68b2cae607f6> in <module>
      7 print(s.list.unique())
      8 print(ds.map_partitions(lambda x: x.list.unique(), meta=ds._meta).compute())
----> 9 print(ds.list)

AttributeError: 'Series' object has no attribute 'list'
```

**Comment by rjzamora** [comment]
Seems reasonable.  Just to clarify - The request is to expose a `list` accessor so that dask_cudf code can look more like cudf code.  This is not meant to add anything that map_partitions cannot achieve, correct?

What is meant by a DataFrame list accessor?  Doesn't this only make sense at the Series level?

**Comment by beckernick** [comment]
Yep, exactly.

> What is meant by a DataFrame list accessor? Doesn't this only make sense at the Series level?

Nothing, just an oversight while typing up a few issues 😃
