### ISSUE TITLE
[BUG] Passing `format` kwarg causes RunTimeError in `cudf.to_datetime()`

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8010]
**Describe the bug**
Passing `format` kwarg causes RunTimeError in cudf.to_datetime()

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

cudf 0.18.1

Some minor behavior I just observed:
datetime.strptime('02-Oct-2017 09:30', '%d-%b-%Y %H:%M')  :white_check_mark:

pd.to_datetime('02-Oct-2017 09:30', format='%d-%b-%Y %H:%M') :white_check_mark: -> Timestamp obj

cudf.to_datetime('02-Oct-2017 09:30', '%d-%b-%Y %H:%M'):white_check_mark: -> str

Now matching pandas...

cudf.to_datetime('02-Oct-2017 09:30', format='%d-%b-%Y %H:%M') :x: -> RuntimeError: invalid format specifier: b

**Expected behavior**
Not cause an error

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by beckernick** [comment]
Note that `cudf.to_datetime('02-Oct-2017 09:30', '%d-%b-%Y %H:%M')` returning a string is silently failing, as the format pattern is passed to the error parameter

**Comment by galipremsagar** [comment]
> Note that `cudf.to_datetime('02-Oct-2017 09:30', '%d-%b-%Y %H:%M')` returning a string is silently failing, as the format pattern is passed to the error parameter

Opened a PR to fix this issue: #8068 

But there is another error that is being caused due to usage of `%b` which is a format specifier that is not supported by libcudf:

https://docs.rapids.ai/api/libcudf/nightly/group__strings__convert.html#ga030d41440ce2c1724fe55364750a011e
https://github.com/rapidsai/cudf/issues/3109

I would defer to @davidwendt on this aspect for the support of additional format specifiers.

**Comment by davidwendt** [comment]
The `%b` format specifier support in libcudf is covered in issue #5991

**Comment by galipremsagar** [comment]
Closing this issue as `%b` support is being addressed as part of #5991
