### ISSUE TITLE
[BUG] Incorrect values while casting from float to Decimal dtype

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#8015]
**Describe the bug**
Casting from float to Decimal dtype can result in value being off by unit scale.

**Steps/Code to reproduce bug**
```python
import cudf
from cudf.core.dtypes import Decimal64Dtype

df = cudf.datasets.randomdata(nrows=10_00_000, dtypes={'cost':int, 'id':int}, seed=12)
df['cost'] = df['cost']/100
df['cost_decimal_9_2'] = df['cost'].astype(Decimal64Dtype(9,2))

res = df['cost'] - df['cost_decimal_9_2'].astype("float64")

res[res!=0]

4         0.01
21        0.01
52        0.01
56        0.01
64        0.01
          ... 
999932    0.01
999933    0.01
999935    0.01
999970    0.01
999990    0.01
Length: 121848, dtype: float64
```

**Expected behavior**
Values match 

In the same case above for the precision 3 decimal column the same error doesn't exist
```python
df['cost_decimal_9_3'] = df['cost'].astype(Decimal64Dtype(9,3))
res = df['cost'] - df['cost_decimal_9_3'].astype("float64")
res[res!=0]

Series([], dtype: float64)
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: conda  0.20 nightly (April 20th)
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Additional context**

**Comment by codereport** [comment]
Hi @ayushdg, 

Unfortunately this is just the way that decimal types work when constructing from IEEE 754 floating point. I reproduced your results, and looked only at the first 5 values:
```python
In [28]: df
Out[28]: 
    cost    id cost_decimal_9_2
0   9.63  1005             9.63
1   9.77  1026             9.77
2  10.48  1026            10.48
3  10.78   960            10.78
4   9.79   982             9.78

In [29]: from decimal import *

In [31]: Decimal(979/100)
Out[31]: Decimal('9.78999999999999914734871708787977695465087890625')
```
You can see that floating point exact value is actually `9.78999...` which will be truncated down to `9.78`. You can see the same behaviour happening in C++ with `CNL` `fixed_point` type: https://godbolt.org/z/7dfn9z1cv

One quick fix is the following:
```python
df['cost_decimal_9_2'] = df['cost'].astype(str).astype(Decimal64Dtype(9,2))
```
You can also convert the integers and then do the division on the DecimalType.

**Comment by harrism** [comment]
Wow I'm getting a lot of nickels.

**Comment by codereport** [comment]
> Wow I'm getting a lot of nickels.

I was thinking we should start a master issue for keeping track of all of these.

**Comment by harrism** [comment]
We can call it "Mark's piggy bank".

**Comment by codereport** [comment]
I'm going to close this issue. Feel free to re-open if you have further questions.
