### ISSUE TITLE
[BUG] Source build -- nvcc error   : 'cicc' died due to signal 9 (Kill signal)

### ISSUE THREAD

**Issue by Atharex** [rapidsai/cudf#8018]
**Describe the bug**
Compiling cudf from source branch v0.18.1 triggers the following nvcc errors and hangs up the machine where I executed the compilation:
```
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/groupby/sort/group_max.cu.o] Error 9
make[2]: *** Waiting for unfinished jobs....
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/copy_range.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/filling/repeat.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/groupby/sort/sort_helper.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/dictionary/detail/concatenate.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/concatenate.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/shift.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/dictionary/set_keys.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/lists/contains.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/groupby/sort/group_min.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/groupby/hash/groupby.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/lists/extract.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/groupby/sort/group_sum.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/gather.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/sample.cu.o] Error 9
nvcc error   : 'cicc' died due to signal 9 (Kill signal)
make[2]: *** [CMakeFiles/cudf_base.dir/src/copying/copy.cu.o] Error 9
make[1]: *** [CMakeFiles/cudf_base.dir/all] Error 2
make: *** [all] Error 2
```

**Steps/Code to reproduce bug**
The following script in a CentOS 7 docker image with a pre-installed CUDA toolkit triggers the error:

```
## Configure the patched GCC 7.5
wget https://gpuci.s3.us-east-2.amazonaws.com/builds/gcc7.tgz -O /gcc7.tgz
tar xvzf /gcc7.tgz -C /
rm -f /gcc7.tgz
export GCC7_DIR=/usr/local/gcc7
export CC=${GCC7_DIR}/bin/gcc
export CXX=${GCC7_DIR}/bin/g++
export CUDAHOSTCXX=${GCC7_DIR}/bin/g++
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=${GCC7_DIR}/lib64:$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/lib
export PATH=${GCC7_DIR}/bin:$PATH

## Configure Miniconda
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b
export PATH=/root/miniconda3/bin:$PATH
export CONDA_PREFIX=/root/miniconda3

## Fetch cuDF repo
export CUDF_HOME=/cudf
git clone --branch v0.18.1 --recurse-submodules https://github.com/rapidsai/cudf $CUDF_HOME
cd $CUDF_HOME
git submodule update --init --remote --recursive

## Create Conda env
conda env create --name cudf_dev --file conda/environments/cudf_dev_cuda11.0.yml
source activate cudf_dev

## Initiate the build
cd $CUDF_HOME/cpp
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/opt/rapids/cudf
make -j
make install

```

**Expected behavior**
The build to finish successfully without hang ups and errors

**Environment overview (please complete the following information)**
 - Environment location: Docker
 - Method of cuDF install: from source
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit 999be56c805bcdca93ce818c1646468aed82d2c4 (HEAD, tag: v0.18.1)
     Author: Raymond Douglass <ray@raydouglass.com>
     Date:   Mon Mar 15 17:17:51 2021 -0400

     REL v0.18.1 release
     **git submodules***

     ***OS Information***
     CentOS Linux release 7.9.2009 (Core)
     NAME="CentOS Linux"
     VERSION="7 (Core)"
     ID="centos"
     ID_LIKE="rhel fedora"
     VERSION_ID="7"
     PRETTY_NAME="CentOS Linux 7 (Core)"
     ANSI_COLOR="0;31"
     CPE_NAME="cpe:/o:centos:centos:7"
     HOME_URL="https://www.centos.org/"
     BUG_REPORT_URL="https://bugs.centos.org/"

     CENTOS_MANTISBT_PROJECT="CentOS-7"
     CENTOS_MANTISBT_PROJECT_VERSION="7"
     REDHAT_SUPPORT_PRODUCT="centos"
     REDHAT_SUPPORT_PRODUCT_VERSION="7"

     CentOS Linux release 7.9.2009 (Core)
     CentOS Linux release 7.9.2009 (Core)
     Linux e6bde74ccc85 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Tue Apr 20 18:33:05 2021
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  GeForce RTX 208...  Off  | 00000000:1A:00.0 Off |                  N/A |
     | 22%   26C    P8    16W / 250W |      0MiB / 11019MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  GeForce RTX 208...  Off  | 00000000:68:00.0 Off |                  N/A |
     | 22%   34C    P8    21W / 250W |      0MiB / 11016MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                36
     On-line CPU(s) list:   0-35
     Thread(s) per core:    2
     Core(s) per socket:    18
     Socket(s):             1
     NUMA node(s):          1
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Model name:            Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
     Stepping:              7
     CPU MHz:               1200.073
     CPU max MHz:           4800.0000
     CPU min MHz:           1200.0000
     BogoMIPS:              6000.00
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              25344K
     NUMA node0 CPU(s):     0-35
     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology

     ***CMake***
     /root/miniconda3/envs/cudf_dev/bin/cmake
     cmake version 3.18.5

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /usr/local/gcc7/bin/g++
     g++ (GCC) 7.5.0
     Copyright (C) 2017 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2020 NVIDIA Corporation
     Built on Mon_Oct_12_20:09:46_PDT_2020
     Cuda compilation tools, release 11.1, V11.1.105
     Build cuda_11.1.TC455_06.29190527_0

     ***Python***
     /root/miniconda3/envs/cudf_dev/bin/python
     Python 3.7.10

     ***Environment Variables***
     PATH                            : /root/miniconda3/envs/cudf_dev/bin:/root/miniconda3/condabin:/root/miniconda3/bin:/usr/local/gcc7/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:
     LD_LIBRARY_PATH                 : /usr/local/gcc7/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/usr/local/cuda-11.1/lib64:/usr/local/cuda/lib64:/usr/local/lib
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    : /root/miniconda3/envs/cudf_dev
     PYTHON_PATH                     :

     ***conda packages***
     /root/miniconda3/condabin/conda
     # packages in environment at /root/miniconda3/envs/cudf_dev:
     #
     # Name                    Version                   Build  Channel
     _libgcc_mutex             0.1                 conda_forge    conda-forge
     _openmp_mutex             4.5                       1_gnu    conda-forge
     abseil-cpp                20210324.0           h9c3ff4c_0    conda-forge
     alabaster                 0.7.12                     py_0    conda-forge
     apipkg                    1.5                        py_0    conda-forge
     appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
     argon2-cffi               20.1.0           py37h5e8e339_2    conda-forge
     arrow-cpp                 1.0.1           py37h363ccdf_36_cuda    conda-forge
     arrow-cpp-proc            3.0.0                      cuda    conda-forge
     async_generator           1.10                       py_0    conda-forge
     attrs                     20.3.0             pyhd3deb0d_0    conda-forge
     aws-c-cal                 0.4.5                h76129ab_8    conda-forge
     aws-c-common              0.5.2                h7f98852_0    conda-forge
     aws-c-event-stream        0.2.7                h6bac3ce_1    conda-forge
     aws-c-io                  0.9.1                ha5b09cb_1    conda-forge
     aws-checksums             0.1.11               h99e32c3_3    conda-forge
     aws-sdk-cpp               1.8.151              hceb1b1e_1    conda-forge
     babel                     2.9.0              pyhd3deb0d_0    conda-forge
     backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
     backports                 1.0                        py_2    conda-forge
     backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
     black                     19.10b0                    py_4    conda-forge
     bleach                    3.3.0              pyh44b312d_0    conda-forge
     bokeh                     2.3.1            py37h89c1867_0    conda-forge
     boost-cpp                 1.75.0               hc6e9bd1_0    conda-forge
     brotli                    1.0.9                h9c3ff4c_4    conda-forge
     brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
     bzip2                     1.0.8                h7f98852_4    conda-forge
     c-ares                    1.17.1               h7f98852_1    conda-forge
     ca-certificates           2020.12.5            ha878542_0    conda-forge
     certifi                   2020.12.5        py37h89c1867_1    conda-forge
     cffi                      1.14.5           py37hc58025e_0    conda-forge
     cfgv                      3.2.0                      py_0    conda-forge
     chardet                   4.0.0            py37h89c1867_1    conda-forge
     clang                     8.0.1                hc9558a2_2    conda-forge
     clang-tools               8.0.1                hc9558a2_2    conda-forge
     clangxx                   8.0.1                         2    conda-forge
     click                     7.1.2              pyh9f0ad1d_0    conda-forge
     cloudpickle               1.6.0                      py_0    conda-forge
     cmake                     3.18.5               h1f3970d_0    rapidsai-nightly
     cmake_setuptools          0.1.3                      py_0    rapidsai
     colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
     commonmark                0.9.1                      py_0    conda-forge
     cryptography              3.4.7            py37h5d9358c_0    conda-forge
     cudatoolkit               11.0.221             h6bb024c_0    nvidia
     cudnn                     8.0.0                cuda11.0_0    nvidia
     cupy                      8.0.0            py37h0ce7dbb_0    rapidsai
     cython                    0.29.23          py37hcd2ae1e_0    conda-forge
     cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
     dask                      2021.4.0+27.g42433599          pypi_0    pypi
     decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
     defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
     distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
     distributed               2021.4.0+20.gd5fc324b          pypi_0    pypi
     dlpack                    0.3                  he1b5a44_1    conda-forge
     docutils                  0.16             py37h89c1867_3    conda-forge
     double-conversion         3.1.5                h9c3ff4c_2    conda-forge
     editdistance-s            1.0.0            py37h2527ec5_1    conda-forge
     entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
     execnet                   1.8.0              pyh44b312d_0    conda-forge
     expat                     2.2.10               h9c3ff4c_0    conda-forge
     fastavro                  1.4.0            py37h5e8e339_0    conda-forge
     fastrlock                 0.6              py37hcd2ae1e_0    conda-forge
     filelock                  3.0.12             pyh9f0ad1d_0    conda-forge
     flake8                    3.8.3                      py_1    conda-forge
     flatbuffers               1.12.0               h58526e2_0    conda-forge
     freetype                  2.10.4               h0708190_1    conda-forge
     fsspec                    2021.4.0           pyhd8ed1ab_0    conda-forge
     future                    0.18.2           py37h89c1867_3    conda-forge
     gflags                    2.2.2             he1b5a44_1004    conda-forge
     glog                      0.4.0                h49b9bf7_3    conda-forge
     gmp                       6.2.1                h58526e2_0    conda-forge
     grpc-cpp                  1.37.0               h36de60a_1    conda-forge
     heapdict                  1.0.1                      py_0    conda-forge
     hypothesis                6.10.0             pyhd8ed1ab_0    conda-forge
     icu                       68.1                 h58526e2_0    conda-forge
     identify                  2.2.3              pyhd8ed1ab_0    conda-forge
     idna                      2.10               pyh9f0ad1d_0    conda-forge
     imagesize                 1.2.0                      py_0    conda-forge
     importlib-metadata        3.10.1           py37h89c1867_0    conda-forge
     importlib_metadata        3.10.1               hd8ed1ab_0    conda-forge
     iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
     ipykernel                 5.5.3            py37h085eea5_0    conda-forge
     ipython                   7.22.0           py37h085eea5_0    conda-forge
     ipython_genutils          0.2.0                      py_1    conda-forge
     isort                     5.0.7            py37hc8dfbb8_0    conda-forge
     jedi                      0.18.0           py37h89c1867_2    conda-forge
     jinja2                    2.11.3             pyh44b312d_0    conda-forge
     jpeg                      9d                   h36c2ea0_0    conda-forge
     jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
     jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
     jupyter_core              4.7.1            py37h89c1867_0    conda-forge
     jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
     krb5                      1.17.2               h926e7f8_0    conda-forge
     lcms2                     2.12                 hddcbb42_0    conda-forge
     ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
     libblas                   3.9.0                8_openblas    conda-forge
     libcblas                  3.9.0                8_openblas    conda-forge
     libcurl                   7.76.1               hc4aaa36_1    conda-forge
     libedit                   3.1.20191231         he28a2e2_2    conda-forge
     libev                     4.33                 h516909a_1    conda-forge
     libevent                  2.1.10               hcdb4288_3    conda-forge
     libffi                    3.3                  h58526e2_2    conda-forge
     libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
     libgfortran-ng            9.3.0               hff62375_19    conda-forge
     libgfortran5              9.3.0               hff62375_19    conda-forge
     libgomp                   9.3.0               h2828fa1_19    conda-forge
     liblapack                 3.9.0                8_openblas    conda-forge
     libllvm10                 10.0.1               he513fc3_3    conda-forge
     libllvm8                  8.0.1                hc9558a2_0    conda-forge
     libnghttp2                1.43.0               h812cca2_0    conda-forge
     libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
     libpng                    1.6.37               h21135ba_2    conda-forge
     libprotobuf               3.15.8               h780b84a_0    conda-forge
     librmm                    0.18.0          cuda11.0_ga4ee6b7_0    rapidsai
     libsodium                 1.0.18               h36c2ea0_1    conda-forge
     libssh2                   1.9.0                ha56f1ee_6    conda-forge
     libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
     libthrift                 0.14.1               he6d91bd_1    conda-forge
     libtiff                   4.2.0                hdc55705_0    conda-forge
     libutf8proc               2.6.1                h7f98852_0    conda-forge
     libuv                     1.41.0               h7f98852_0    conda-forge
     libwebp-base              1.2.0                h7f98852_2    conda-forge
     llvmlite                  0.36.0           py37h9d7f4d0_0    conda-forge
     locket                    0.2.0                      py_2    conda-forge
     lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
     markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
     markupsafe                1.1.1            py37h5e8e339_3    conda-forge
     mccabe                    0.6.1                      py_1    conda-forge
     mimesis                   4.0.0              pyh9f0ad1d_0    conda-forge
     mistune                   0.8.4           py37h5e8e339_1003    conda-forge
     more-itertools            8.7.0              pyhd8ed1ab_0    conda-forge
     msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
     mypy                      0.782                      py_0    conda-forge
     mypy_extensions           0.4.3            py37h89c1867_3    conda-forge
     nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
     nbconvert                 6.0.7            py37h89c1867_3    conda-forge
     nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
     nbsphinx                  0.8.3              pyhd8ed1ab_0    conda-forge
     nccl                      2.7.8.1            h4962215_100    nvidia
     ncurses                   6.2                  h58526e2_4    conda-forge
     nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
     nodeenv                   1.6.0              pyhd8ed1ab_0    conda-forge
     notebook                  6.3.0              pyha770c72_1    conda-forge
     numba                     0.53.1           py37h134767a_0    conda-forge
     numpy                     1.20.2           py37h038b26d_0    conda-forge
     numpydoc                  1.1.0                      py_1    conda-forge
     nvtx                      0.2.3            py37h5e8e339_0    conda-forge
     olefile                   0.46               pyh9f0ad1d_1    conda-forge
     openjpeg                  2.4.0                hf7af979_0    conda-forge
     openssl                   1.1.1k               h7f98852_0    conda-forge
     orc                       1.6.7                heec2584_1    conda-forge
     packaging                 20.9               pyh44b312d_0    conda-forge
     pandas                    1.1.5            py37hdc94413_0    conda-forge
     pandoc                    1.19.2                        0    conda-forge
     pandocfilters             1.4.2                      py_1    conda-forge
     parquet-cpp               1.5.1                         2    conda-forge
     parso                     0.8.2              pyhd8ed1ab_0    conda-forge
     partd                     1.2.0              pyhd8ed1ab_0    conda-forge
     pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
     pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
     pickleshare               0.7.5                   py_1003    conda-forge
     pillow                    8.1.2            py37h4600e1f_1    conda-forge
     pip                       21.0.1             pyhd8ed1ab_0    conda-forge
     pluggy                    0.13.1           py37h89c1867_4    conda-forge
     pre-commit                2.12.1           py37h89c1867_0    conda-forge
     pre_commit                2.12.1               hd8ed1ab_0    conda-forge
     prometheus_client         0.10.1             pyhd8ed1ab_0    conda-forge
     prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
     protobuf                  3.15.8           py37hcd2ae1e_0    conda-forge
     psutil                    5.8.0            py37h5e8e339_1    conda-forge
     ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
     py                        1.10.0             pyhd3deb0d_0    conda-forge
     py-cpuinfo                8.0.0              pyhd8ed1ab_0    con-forge
     sphinx-markdown-tables    0.0.15             pyhd3deb0d_0    conda-forge
     sphinx_rtd_theme          0.5.2              pyhd8ed1ab_1    conda-forge
     sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
     sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
     sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
     sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
     sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
     sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
     sphinxcontrib-websupport  1.2.4              pyh9f0ad1d_0    conda-forge
     sqlite                    3.35.4               h74cdb3f_0    conda-forge
     streamz                   0.6.2              pyh44b312d_0    conda-forge
     tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
     terminado                 0.9.4            py37h89c1867_0    conda-forge
     testpath                  0.4.4                      py_0    conda-forge
     tk                        8.6.10               h21135ba_1    conda-forge
     toml                      0.10.2             pyhd8ed1ab_0    conda-forge
     toolz                     0.11.1                     py_0    conda-forge
     tornado                   6.1              py37h5e8e339_1    conda-forge
     traitlets                 5.0.5                      py_0    conda-forge
     typed-ast                 1.4.3            py37h5e8e339_0    conda-forge
     typing_extensions         3.7.4.3                    py_0    conda-forge
     urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
     virtualenv                20.4.4           py37h89c1867_0    conda-forge
     wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
     webencodings              0.5.1                      py_1    conda-forge
     wheel                     0.36.2             pyhd3deb0d_0    conda-forge
     xz                        5.2.5                h516909a_1    conda-forge
     yaml                      0.2.5                h516909a_0    conda-forge
     zeromq                    4.3.4                h9c3ff4c_0    conda-forge
     zict                      2.0.0                      py_0    conda-forge
     zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
     zlib                      1.2.11            h516909a_1010    conda-forge
     zstd                      1.4.9                ha95c52a_0    conda-forge

</pre></details>

**Comment by jrhemstad** [comment]
Try reducing the amount of parallelism in your build by specifying `make -jN` for some value of N. I'm guessing you're running out of memory during your build.

**Comment by Atharex** [comment]
That was the case indeed, thanks @jrhemstad 

Now it almost compiles, but at the end the following error is thrown:
```
...
[ 70%] Built target DICTIONARY_TEST
[ 71%] Built target SCALAR_TEST
[ 73%] Built target TEXT_TEST
[ 73%] Built target REPLACE_NULLS_TEST
[ 74%] Built target RESHAPE_TEST
[ 74%] Built target ROUND_TEST
[ 74%] Built target COLLECT_LIST_TEST
[ 75%] Built target TRAITS_TEST
[ 76%] Built target COLUMN_TEST
[ 77%] Built target HASH_MAP_TEST
[ 77%] Built target DECOMPRESSION_TEST
[ 81%] Built target COPYING_TEST
[ 82%] Built target LISTS_TEST
[ 82%] Built target HASHING_TEST
[ 82%] Built target TIMESTAMPS_TEST
[ 83%] Built target UNARY_TEST
[ 83%] Building CXX object tests/CMakeFiles/JITCACHE_MULTIPROC_TEST.dir/jit/jit-cache-multiprocess-test.cpp.o
In file included from /root/home/cudf/cpp/tests/jit/jit-cache-multiprocess-test.cpp:19:0:
/root/home/cudf/cpp/tests/jit/jit-cache-test.hpp: In member function 'void JitCacheTest::purgeFileCache()':
/root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:61:95: error: 'begin' was not declared in this scope
     for (auto& path : boost::filesystem::recursive_directory_iterator(cudf::jit::getCacheDir())) {
                                                                                               ^
/root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:61:95: note: suggested alternative:
In file included from /usr/local/gcc7/include/c++/7.5.0/string:51:0,
                 from /usr/local/gcc7/include/c++/7.5.0/bits/locale_classes.h:40,
                 from /usr/local/gcc7/include/c++/7.5.0/bits/ios_base.h:41,
                 from /usr/local/gcc7/include/c++/7.5.0/ios:42,
                 from /usr/local/gcc7/include/c++/7.5.0/ostream:38,
                 from /usr/local/gcc7/include/c++/7.5.0/iterator:64,
                 from /usr/include/boost/iterator.hpp:17,
                 from /usr/include/boost/operators.hpp:86,
                 from /usr/include/boost/system/error_code.hpp:17,
                 from /usr/include/boost/filesystem/path_traits.hpp:23,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:19,
                 from /root/home/cudf/cpp/tests/jit/jit-cache-multiprocess-test.cpp:19:
/usr/local/gcc7/include/c++/7.5.0/bits/range_access.h:105:37: note:   'std::begin'
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
In file included from /root/home/cudf/cpp/tests/jit/jit-cache-multiprocess-test.cpp:19:0:
/root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:61:95: error: 'end' was not declared in this scope
     for (auto& path : boost::filesystem::recursive_directory_iterator(cudf::jit::getCacheDir())) {
                                                                                               ^
/root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:61:95: note: suggested alternative:
In file included from /usr/local/gcc7/include/c++/7.5.0/string:51:0,
                 from /usr/local/gcc7/include/c++/7.5.0/bits/locale_classes.h:40,
                 from /usr/local/gcc7/include/c++/7.5.0/bits/ios_base.h:41,
                 from /usr/local/gcc7/include/c++/7.5.0/ios:42,
                 from /usr/local/gcc7/include/c++/7.5.0/ostream:38,
                 from /usr/local/gcc7/include/c++/7.5.0/iterator:64,
                 from /usr/include/boost/iterator.hpp:17,
                 from /usr/include/boost/operators.hpp:86,
                 from /usr/include/boost/system/error_code.hpp:17,
                 from /usr/include/boost/filesystem/path_traits.hpp:23,
                 from /usr/include/boost/filesystem/path.hpp:25,
                 from /usr/include/boost/filesystem.hpp:16,
                 from /root/home/cudf/cpp/tests/jit/jit-cache-test.hpp:19,
                 from /root/home/cudf/cpp/tests/jit/jit-cache-multiprocess-test.cpp:19:
/usr/local/gcc7/include/c++/7.5.0/bits/range_access.h:107:37: note:   'std::end'
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
make[2]: *** [tests/CMakeFiles/JITCACHE_MULTIPROC_TEST.dir/jit/jit-cache-multiprocess-test.cpp.o] Error 1
make[1]: *** [tests/CMakeFiles/JITCACHE_MULTIPROC_TEST.dir/all] Error 2
make: *** [all] Error 2
```

Does this indicate wrong boost or gcc dependencies? 

I'm using
- boost-1.53.0-28 from the official Centos 7 repos 
- patched GCC 7.5.0 from https://github.com/rapidsai/gpuci-build-environment#supporting-image---gcc7-from-source-build-for-centos-7

**Comment by jrhemstad** [comment]
That kind of looks like wrong boost dependencies. Note that if you wait a bit, we're actually in the process of removing this dependency: https://github.com/rapidsai/cudf/pull/7932

**Comment by kkraus14** [comment]
For our conda / CI builds we use boost 1.72.0: https://github.com/rapidsai/cudf/blob/branch-0.20/conda/recipes/libcudf/meta.yaml#L42

**Comment by Atharex** [comment]
@kkraus14 thanks, using boost 1.72 solved the issue!

@jrhemstad that will be in version 0.20, right? I will give this rebuild a try with 0.19 now

**Comment by jrhemstad** [comment]
> @jrhemstad that will be in version 0.20, right? I will give this rebuild a try with 0.19 now

Yep.
