### ISSUE TITLE
[BUG] Incorrect index returned from label_bins when include_lowest is true

### ISSUE THREAD

**Issue by marlenezw** [rapidsai/cudf#8047]
Hi, I'm running some tests on `cut`, and `label_bins` seems to be giving me the incorrect index in some cases when `include_lowest=True`.  In the python code, when if `include_lowest` is True then I'm setting  `left_inclusive = True`. This seems to be altering the bin some values are placed in when it shouldn't. 
I've added an example of what I'm getting below. Thank you :D 

```
#results are correct when lowest_included is False (by default)

In [2]: cudf.cut(np.array([1, 7, 5, 4, 6, 3]), 2)
Out[2]: 
CategoricalIndex([(0.994, 4.0], (4.0, 7.0], (4.0, 7.0], (0.994, 4.0],
                  (4.0, 7.0], (0.994, 4.0]],
                 categories=[(0.994, 4.0], (4.0, 7.0]], ordered=True, dtype='category')

In [3]: pd.cut(np.array([1, 7, 5, 4, 6, 3]), 2)
Out[3]: 
[(0.994, 4.0], (4.0, 7.0], (4.0, 7.0], (0.994, 4.0], (4.0, 7.0], (0.994, 4.0]]
Categories (2, interval[float64]): [(0.994, 4.0] < (4.0, 7.0]]

#results are incorrect when  lowest_included is True

In [2]: cudf.cut(np.array([1, 7, 5, 4, 6, 3]), 2, include_lowest=True)
Out[2]: 
CategoricalIndex([(0.993, 4.0], (4.0, 7.0], (4.0, 7.0], (4.0, 7.0], (4.0, 7.0],
                  (0.993, 4.0]],
                 categories=[(0.993, 4.0], (4.0, 7.0]], ordered=True, dtype='category')

In [3]: pd.cut(np.array([1, 7, 5, 4, 6, 3]), 2, include_lowest=True)
Out[3]: 
[(0.993, 4.0], (4.0, 7.0], (4.0, 7.0], (0.993, 4.0], (4.0, 7.0], (0.993, 4.0]]
Categories (2, interval[float64]): [(0.993, 4.0] < (4.0, 7.0]]
```
As you can see 4 is placed in the wrong bin. 
When I compare the indexes I'm getting back from label_bins

```
#we expect this
(Pdb) labels
<cudf.core.column.numerical.NumericalColumn object at 0x7f7e6a4d7050>
[
  0,
  1,
  1,
  0,
  1,
  0
]
dtype: int32

#we get this instead.
(Pdb) labels
<cudf.core.column.numerical.NumericalColumn object at 0x7f7eeb719290>
[
  0,
  1,
  1,
  1,
  1,
  0
]
dtype: int32

```
cc @vyasr

**Comment by jrhemstad** [comment]
If you're setting `left_inclusive=true` then the value `4` is going to get placed into the `[4.0, 7.0]` bin. 

`include_lowest` isn't the same thing as `left_inclusive`. `include_lowest` just says the _first_ left bound should be inclusive. We don't handle that in libcudf and requires modifying the bin edges passed into `label_bins`.

**Comment by marlenezw** [comment]
Oh, thanks @jrhemstad! I didn't realize they were not the same! I'll fix this in python then :D 
Closing the issue
