### ISSUE TITLE
[FEA] Support for non key nested types in cudf::merge

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8050]
**Is your feature request related to a problem? Please describe.**
For sorting data in Spark we use `merge` if the data is too large to fit in a single batch. We need to be able to support sorting data that contains nested types (that are not necessarily the key we are sorting on).

**Describe the solution you'd like**
I would like to see merge support the same types for non-sort keys columns that gather supports so we can sort whatever it is we need to sort.

**Describe alternatives you've considered**
As a work around we will concat the tables together and sort them, but it is much slower, and not ideal.

**Comment by firestarman** [comment]
Reopen this since it is still missing the array and map type support.

**Comment by vyasr** [comment]
Closing as resolved by https://github.com/rapidsai/cudf/pull/14250.
