### ISSUE TITLE
[FEA] Java APIs to determine CUDA driver and runtime versions

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8084]
**Is your feature request related to a problem? Please describe.**
Related to the snappy nanosleep issue, sometimes we may need to detect a combination of CUDA driver and CUDA runtime that has known issues and either emit a warning or throw an exception when a particular combination is detected.

**Describe the solution you'd like**
The existing Java `Cuda` class can expose methods like the following:
```
/** Returns the latest CUDA version supported by the driver as 1000*major + 10*minor */
int getDriverVersion();

/** Returns the CUDA runtime version as 1000*major + 10*minor */
int getRuntimeVersion();
```

It may be helpful to have a method that returns the full driver version string rather that only being able to access the CUDA runtime supported by the driver.

**Comment by GaryShen2008** [comment]
Maybe we can also support https://github.com/rapidsai/cudf/issues/6363.
