### ISSUE TITLE
[FEA] Support `hashcode` and `equal` for `ColumnView` .

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#8090]
These two are the standard APIs in Java for an `Object`, who is the parent class of `ColumnView`.

So we may want to support them by taking into account the rows/data inside a `ColumnView`, instead of the default implementation.

This may need the native support because these two need to access the underlying data but the data is on GPU. 
Yes we could copy the data to CPU, but not sure whether it is a good way. Maybe it is when the data is not big.

This is low priority since we are not using them.

**Comment by revans2** [comment]
This feels problematic. Why exactly do we want this? We can define equality however we want. Right now it is the same java object pointing to underlying CUDF data. Why is that not good enough?

**Comment by vyasr** [comment]
Given the last comment here and the stale nature of the issue, I'm going to close this for now, but feel free to reopen if you think there's an action item here @revans2.
