### ISSUE TITLE
[DOC] cudf.Series.factorize() uniques value is of type Index, not Series 

### ISSUE THREAD

**Issue by miguelusque** [rapidsai/cudf#8097]
## Report incorrect documentation

**Location of incorrect documentation**
https://docs.rapids.ai/api/cudf/stable/api.html?highlight=factorize#cudf.core.series.Series.factorize

**Describe the problems or issues found in the documentation**
uniques values returned by `factorize()` method is of type `Index`, not `Series`.

**Comment by kkraus14** [comment]
Fixed by #8154
