### ISSUE TITLE
[QST] cudf column for strings

### ISSUE THREAD

**Issue by buckeye17** [rapidsai/cudf#8134]
I've got a `dask_cudf` dataframe named "ddf" that has a column named "name" which consists of strings that are 8 characters long.  When I use `map_partitions()` to apply some quadtree filtering with `cuspatial`, I get an error meassage stating:
```
RuntimeError: cuDF failure at: ../include/cudf/strings/detail/gather.cuh:148: total size of output strings is too large for a cudf column
```
If I drop the "name" column, this error does not occur.  I should be able to use a left join to reinstate the "name" column after quadtree filtering, but when I add the following code to do so, I get the same error.  How can I fix or workaround this issue?
```
unique_cudf = (ddf.loc[:, ["num_id", "name"]]
                .map_partitions(lambda cudf: cudf.head(1))
                .reset_index()
                .drop("index", axis=1)
                .compute())
ddf = ddf.drop("name", axis=1)
ddf = ddf.map_partitions(lambda cudf: my_quadtree_filter())
ddf = ddf.merge(unique_cudf, how="left", on="num_id")
```

**Comment by beckernick** [comment]
When the error presents, are you calling `compute`, `persist`, or something else?

In this context, the error means an individual partition has a column with too many total characters across all strings in the column. It's hard to be more concrete without additional details. Does this still occur if you increase the number of partitions during either the read stage or by repartitioning your dataframe in memory?

**Comment by vyasr** [comment]
Since this issue vanished and we have no repro of the original error case, and since we know the typical cause of this error (column with too many characters), I'm going to close this issue as resolved. Please feel free to reopen if the issue recurs.
