### ISSUE TITLE
[FEA] JNISupports creating a ColumnVector from an array of UTF8 string directly.

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#8136]
cudf cpp expects an UTF8 string to be dealt with. It is missing an API to create a ColumnVector from an array of UTF8 string directly.
e.g.
ColumnVector

This is low priority since now the API `build` can be used to achieve this.

**Comment by davidwendt** [comment]
duplicate of #8137 ?

**Comment by jlowe** [comment]
Yes, this is a duplicate.

**Comment by firestarman** [comment]
Thanks for this. 
I filed two similar issues unexpectedly.
