### ISSUE TITLE
[FEA] Explore removing kwarg branching logic in dask_cudf operator bindings based on dask version

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#8160]
Now that we pin dask-cudf to a specific dask version, we may be able to remove the `DASK_VERISON` branching logic in the operator bindings in `dask_cudf/core.py`:

https://github.com/rapidsai/cudf/blob/770dc385154853b1dc1c7ccbe676442e81414f8a/python/dask_cudf/dask_cudf/core.py#L722-L733

**Comment by vyasr** [comment]
AFAICT this is no longer an issue. The only usage of `DASK_VERSION` right now is for query-planning support, which presumably will go away soon.
```
(rapids) coder _ ~/cudf $ git grep DASK_VERSION
python/dask_cudf/dask_cudf/tests/utils.py:    DASK_VERSION = Version(dask.__version__)
python/dask_cudf/dask_cudf/tests/utils.py:    DASK_VERSION = None
python/dask_cudf/dask_cudf/tests/utils.py:        skip = QUERY_PLANNING_ON and DASK_VERSION < Version(lt_version)
python/dask_cudf/dask_cudf/tests/utils.py:        xfail = QUERY_PLANNING_ON and DASK_VERSION < Version(lt_version)
```
