### ISSUE TITLE
Using 0.5.0 with rapidsai/rapidsai container failed due to deps (pyarrow, ..)

### ISSUE THREAD

**Issue by yaronha** [rapidsai/cudf#818]
i'm interested in using latest cudf with the entire set of tools (jupyter, ..) 
it seems like there is no up to date container with cudf 0.5.0 in docker hub rapidsai/rapidsai, so i tried to use the latest (cuda9.2_ubuntu16.04_root) and update cudf inside using:

```
> conda install -c numba -c conda-forge -c nvidia -c rapidsai -c defaults cudf=0.5.0

UnsatisfiableError: The following specifications were found to be in conflict:
  - cudf=0.5.0 -> libcudf=0.5 -> pyarrow=0.11.1 -> arrow-cpp=0.11.1 -> boost-cpp[version='>=1.68.0,<1.68.1.0a0']
  - cudf=0.5.0 -> libcudf=0.5 -> pyarrow=0.11.1 -> parquet-cpp=1.5.1
  - pyarrow=0.10 -> arrow-cpp=0.10.0
  - pyarrow=0.10 -> parquet-cpp=1.5.0.pre

```

it failed due to dependency conflicts with pyarrow, i tried to update pyarrow to 0.11.1 and it failed due to dependency on python, etc. i wonder if there is a way to bypass those issues or have a ready made container with latest cudf (0.5.0). if not, where can i get the `Dockerfile` for `cuda9.2_ubuntu16.04_root` so i can patch it to use cudf 0.5.0 ?

Thanks

**Comment by mike-wendt** [comment]
These are live on Docker Hub and include 3 new container types to match CUDA and enable drop in replacement. We also have containers for 18.04 with gcc 7 support.

https://hub.docker.com/r/rapidsai/rapidsai/tags
