### ISSUE TITLE
[BUG] null ordering for nulls in children appears to be ignored

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8189]
**Describe the bug**
Null precedence appears to be ignored for child columns when both sorting structs and when doing bounds checks on them, or perhaps it is the validity for the child columns are ignored.

**Steps/Code to reproduce bug**

```diff
diff --git a/cpp/tests/search/search_struct_test.cpp b/cpp/tests/search/search_struct_test.cpp
index 50c326269a..480f768282 100644
--- a/cpp/tests/search/search_struct_test.cpp
+++ b/cpp/tests/search/search_struct_test.cpp
@@ -22,6 +22,7 @@
 
 #include <cudf/lists/lists_column_view.hpp>
 #include <cudf/search.hpp>
+#include <cudf/sorting.hpp>
 #include <cudf/table/table_view.hpp>
 
 using bools_col   = cudf::test::fixed_width_column_wrapper<bool>;
@@ -92,24 +93,33 @@ TYPED_TEST(TypedStructSearchTest, TrivialInputTests)
 {
   using col_wrapper = cudf::test::fixed_width_column_wrapper<TypeParam, int32_t>;
 
-  auto child_col_t     = col_wrapper{10, 20, 30, 40, 50};
+  auto child_col_t     = col_wrapper{{null, -13167}, null_at(0)};
   auto const structs_t = structs_col{{child_col_t}}.release();
 
-  auto child_col_values1     = col_wrapper{0, 1, 2, 3, 4};
+  auto child_col_values1     = col_wrapper{{null, -32619, -23070}, null_at(0)};
   auto const structs_values1 = structs_col{{child_col_values1}}.release();
 
-  auto child_col_values2     = col_wrapper{100, 101, 102, 103, 104};
-  auto const structs_values2 = structs_col{{child_col_values2}}.release();
+  cudf::test::print(*structs_t);
+  cudf::test::print(*structs_values1);
 
-  auto const results1  = search_bounds(structs_t, structs_values1);
-  auto const expected1 = int32s_col{0, 0, 0, 0, 0};
-  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected1, results1.first->view(), print_all);
-  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected1, results1.second->view(), print_all);
+  auto const t            = cudf::table_view{std::vector<cudf::column_view>{*structs_t}};
+  auto const values       = cudf::table_view{std::vector<cudf::column_view>{*structs_values1}};
+
+  auto const t_order = cudf::sorted_order(t, {cudf::order::ASCENDING}, {cudf::null_order::BEFORE});
+  cudf::test::print(*t_order);
+
+  auto const v_order = cudf::sorted_order(values, {cudf::order::ASCENDING}, {cudf::null_order::BEFORE});
+  cudf::test::print(*v_order);
 
-  auto const results2  = search_bounds(structs_t, structs_values2);
-  auto const expected2 = int32s_col{5, 5, 5, 5, 5};
-  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected2, results2.first->view(), print_all);
-  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected2, results2.second->view(), print_all);
+  auto const t_order_aft = cudf::sorted_order(t, {cudf::order::ASCENDING}, {cudf::null_order::AFTER});
+  cudf::test::print(*t_order_aft);
+
+  auto const v_order_aft = cudf::sorted_order(values, {cudf::order::ASCENDING}, {cudf::null_order::AFTER});
+  cudf::test::print(*v_order_aft);
+
+  auto const results1  = search_bounds(structs_t, structs_values1, {cudf::order::ASCENDING}, {cudf::null_order::BEFORE});
+  auto const expected1 = int32s_col{0, 1, 1};
+  CUDF_TEST_EXPECT_COLUMNS_EQUAL(expected1, results1.first->view(), print_all);
 }
 
 TYPED_TEST(TypedStructSearchTest, SlicedColumnInputTests)

```

This is a fairly simple test that has a struct with a single child.  The data for the child column is

```
t = {null, -13167};
values = {null, -32619, -23070};
```

I do a lower bound on these ascending, with NULLs before, I would expect to see an output of.

`0, 1, 1` because it is a lower bound so the `values` `null` should come before the `t` `null`, and both `-32619` and `-23070` are larger than `null`, but smaller than `-13167`.  But instead I see `2, 0, 0`. 

I thought then that maybe I had sorted things wrong. So I printed out the sorted order for both tables and it says that they are sorted, but even if I change the null ordering to after it still says that they are sorted.

```
[ RUN      ] TypedStructSearchTest/2.TrivialInputTests
Struct<int32_t,>:
Length : 2:
   10
   NULL, -13167

Struct<int32_t,>:
Length : 3:
   110
   NULL, -32619, -23070

0,1
0,1,2
0,1
0,1,2
../tests/utilities/column_utilities.cu:235: Failure
Failed
first difference: lhs[0] = 0, rhs[0] = 2
Google Test trace:
../tests/search/search_struct_test.cpp:122:  <--  line of failure

[  FAILED  ] TypedStructSearchTest/2.TrivialInputTests, where TypeParam = int (3 ms)
```

**Expected behavior**
As was discussed in https://github.com/rapidsai/cudf/issues/7226 I expected the null ordering of a child column to be inherited from its parent for both upper/lower bounds and sorting in general.

**Comment by revans2** [comment]
FYI: I tested this with https://github.com/rapidsai/cudf/pull/8188 and it is still showing the same issues so it is not the same thing.

**Comment by ttnghia** [comment]
> As was discussed in #7226 I expected the null ordering of a child column to be inherited from its parent for both upper/lower bounds and sorting in general.

@revans2, in your example, the nulls are at the child column level. The parent columns doesn't know about null in their children, thus the search/sort API will consider those struct columns as having no null. I'm trying to figure out what should be changed regarding this.

**Comment by ttnghia** [comment]
I tried to call `printf` inside the row comparator, and found an interesting phenomenon: During sorting a structs column having just 2 rows (as in the example above), the comparator is called several thousand times! I.e., my `printf` call is executed several thousand times. Currently I'm trying to figure out why that happens.

**Comment by ttnghia** [comment]
Hah, I finally found the cause of our problem: struct flattening always uses `null_order::BEFORE` for the child column. I'm fixing that and run some tests before pushing a PR.

**Comment by ttnghia** [comment]
@revans2 Please test my PR to make sure it fixes the issue. Your provided example passed the test but I'm not sure if you have other more complex data to test.
