### ISSUE TITLE
[FEA] ngram function that outputs a list

### ISSUE THREAD

**Issue by argenisleon** [rapidsai/cudf#8190]
**Is your feature request related to a problem? Please describe.**
I would like to have function that get a string like `bumblebee` and output a list like `[[bu],[um],[mb],[bl],[le],[eb],[be],[ee]]`

**Describe the solution you'd like**
the `character_ngrams` function already exist but outputs a series. Maybe a param like `output` could be used to output a list. Something like `character_ngrams(2, output='list')`

**Describe alternatives you've considered**
I considered `character_ngrams` but the function output a cudf dataframe

**Comment by beckernick** [comment]
This might be nice for `ngrams_tokenize`, too. I believe the Spark ngrams feature returns an array per row by default. https://spark.apache.org/docs/latest/api/java/org/apache/spark/ml/feature/NGram.html

**Comment by davidwendt** [comment]
From the description, it appears the desired result is for every string element to become list element. I believe this can be done without a new libcudf API. Using the strings column output of `character_ngrams`, the lists offsets column is just a sequence of numbers from 0 up to the number of strings.

```
input strings column: ['bumblebee']  -- this example is a column with 1 string in it;
output of character_ngrams(2): ['bu','um','mb','bl','le','eb','be','ee'] becomes a child of the output lists column;
offsets column: [0,1,2,3,4,5,6,7,8] is the offsets child column of the output lists column.
```

I don't follow the `ngrams_tokenize` request from @beckernick. Perhaps he meant the `ngrams` generate API? If every string row is to become a list element, then this approach would work that as well. Otherwise, I'd need to see an example of desired output for the  `ngrams_tokenize` case.

**Comment by beckernick** [comment]
> I don't follow the ngrams_tokenize request from @beckernick. Perhaps he meant the ngrams generate API? ... (elided)

I'm actually off base on the spark ngrams behavior based on the docs so it may not be relevant here ("A feature transformer that converts the input array of strings into an array of n-grams"). It essentially takes array<string> and returns array<string>. Feel free to ignore the above

```python
from pyspark.sql import SparkSession, Row
from pyspark.ml.feature import NGram
​
spark = SparkSession.builder.master("local").getOrCreate()
df = spark.createDataFrame([Row(a=["dog", "cat", "bear", "fish"])])
ngram = NGram(n=2, inputCol="a", outputCol="out")
ngram.transform(df).show(truncate=False)
+----------------------+------------------------------+
|a                     |out                           |
+----------------------+------------------------------+
|[dog, cat, bear, fish]|[dog cat, cat bear, bear fish]|
+----------------------+------------------------------+
```

**Comment by argenisleon** [comment]
@davidwendt An output like `['bu','um','mb','bl','le','eb','be','ee']` from `['bumblebee']` will be enough form my use case (string clustering).
@beckernick In case that the plan is to be compatible with Spark and taking into account that split chars is already implemented https://github.com/rapidsai/cudf/issues/8094  creating n-grams from a list could be the way to go.
