### ISSUE TITLE
[BUG] DataFrame.rank() ignores axis option

### ISSUE THREAD

**Issue by tfeher** [rapidsai/cudf#8212]
**Describe the bug**
The DataFrame.rank() method ignores the `axis` option and ranks always along axis=0.

**Steps/Code to reproduce bug**
```python
import cudf
import numpy as np
gdf = cudf.DataFrame(data={'A': [4, 2, 4, 8, np.nan], 'B':[5,4,3,2,1]})
gdf.rank(axis=1)
```
This gives 
|   A | B|
|---|---|
|2.5 | 5.0|
|1.0 | 4.0|
|2.5 | 3.0|
|4.0 | 2.0|
|NA | 1.0|

**Expected behavior**

Rank along columns when axis=1 is specified. Here is the expected output produced by pandas
```python
import pandas as pd
df = pd.DataFrame(data={'A': [4, 2, 4, 8, np.nan], 'B':[5,4,3,2,1]})
df.rank(axis=1)
```
Prints:
| A | B|
|---|---|
|1.0 | 2.0|
|1.0 | 2.0|
|2.0 | 1.0|
|2.0 | 1.0|
|NaN | 1.0|

**Environment overview**

Tested with 0.20 nightly  docker image (rapidsai/rapidsai-core-dev-nightly:0.20-cuda11.2-devel-ubuntu18.04-py3.8).

**Additional context**
The ranking method is used by [cheminformatics](https://github.com/NVIDIA/cheminformatics/blob/d32368d7aa2901e3f05c2c7726b0ed3c8c825ea2/nvidia/cheminformatics/utils/metrics.py#L74)

**Comment by mlgill** [comment]
Thanks for filing this @tfeher -- this exactly the describes the bug as I initially identified it.

**Comment by kkraus14** [comment]
We should at least be throwing for now that we don't yet support `axis=1`.
