### ISSUE TITLE
Remove `volatile` usage in `rolling_detail.cuh` where not required

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#8230]
In the device code in `rolling_detail.cuh`, there are variables declared as `volatile` to work around compiler optimizations in CUDA 10.x. E.g.:
```c++
    // declare this as volatile to avoid some compiler optimizations that lead to incorrect results
    // for CUDA 10.0 and below (fixed in CUDA 10.1)
    volatile cudf::size_type count = 0;
```
Given that CUDF 0.20 supports CUDA 11.0+, it should now be safe to remove this comment, and the `volatile` attributes.

If not handled in #8158, this can be addressed after #8158 is merged.

**Comment by vyasr** [comment]
This was resolved in #12088
