### ISSUE TITLE
[FEA] Utility function to construct `packed_columns::metadata`

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/cudf#8236]
**Is your feature request related to a problem? Please describe.**
I am working on serialization/deserialization of `packed_columns` as part of #8153; as part of deserialization, I must reconstruct the `packed_columns::metadata` from a `std::vector<uint8_t>` in Cython. However, I do not think it is possible to directly create a struct in Cython using a non-default constructor (based on this [SO answer](https://stackoverflow.com/questions/45991342/directly-call-c-struct-constructor-from-cython)).

**Describe the solution you'd like**
A potential workaround for this would be a simple C++ utility function that takes in a `std::vector<uint8_t>`, constructs the `packed_columns::metadata`, and returns it. This could then be used in Cython in the place of the non-default constructor.

**Describe alternatives you've considered**
This only seems to apply for stack-allocated objects, but not those on the heap; I'm not too familiar with Cython, but perhaps there could be a way to create a heap-allocated `packed_columns::metadata` here?

**Additional context**
My current naive implementation of serialization/deserialization:

- https://github.com/charlesbluca/cudf/blob/da27ce8a032cbb923a023744b4e55ebfb9d53b14/python/cudf/cudf/_lib/copying.pyx#L746-L764

cc @nvdbaranec

**Comment by nvdbaranec** [comment]
For what it's worth, the `packed_columns::metadata_` field here is a pointer, so the underlying `metadata` struct is a heap object.

`std::unique_ptr<metadata> metadata_;`

**Comment by charlesbluca** [comment]
Is there a way to access this object from deserialization? Currently my strategy here is to make a Python list copy of the `metadata`'s vector:

```python
        cdef uint8_t[::1] mv = (<uint8_t[:self.data.metadata_.get()[0].size()]>
                                self.data.metadata_.get()[0].data())
        header["metadata-vector"] = [
            mv[i]
            for i in range(self.data.metadata_.get()[0].size())
        ]
```

And then later reconstruct the vector, and then the `metadata` using it:

```python
        cdef vector[uint8_t] v
        for ui in header["metadata-vector"]:
            v.push_back(ui)
        cdef cpp_copying.metadata m = cpp_copying.metadata(v)
```

But that would result in a stack-allocated object, right?

**Comment by nvdbaranec** [comment]
I'm not familiar enough with cython to give you a correct answer.  I know that in other places in the cython bindings we use unique_ptr<> wrapped objects though.

**Comment by shwina** [comment]
@charlesbluca you're right that we can't stack allocate, but we _can_ wrap in a unique_ptr as @nvdbaranec is suggesting. So something like:

```
        cdef vector[uint8_t] v
        for ui in header["metadata-vector"]:
            v.push_back(ui)
        cdef unique_ptr[cpp_copying.metadata] m = make_unique[cpp_copying.metadata](v)
```

**Comment by charlesbluca** [comment]
Thanks for the tip! I'll try that out and report back - if that works, then we can close this issue.

**Comment by charlesbluca** [comment]
That resolves it - I am able to create the `unique_ptr` from Cython. Thanks @shwina!
