### ISSUE TITLE
[FEA] Allow "df.index = some_index"

### ISSUE THREAD

**Issue by tebeka** [rapidsai/cudf#824]
**Is your feature request related to a problem? Please describe.**
In Pandas it's possible to do `df.index = [1,2,3]`, in cudf `df.index` is a read only property.

**Describe the solution you'd like**
I'd like to be able to set the index like it's possible in pands

**Describe alternatives you've considered**
There's `df.set_index`, however it's not supporting `inplace` so we copy the DataFrame over.

**Additional context**
IMO it's `cudf` should be a `drop in` replacement to pandas `DataFrame` as much as possible.

**Comment by thomcom** [comment]
Agree! We'll work on it.
