### ISSUE TITLE
[FEA] CSV and JSON readers: Pass column data types as objects instead of strings

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#8240]
Currently the column data types are passed as strings and parsed to the readers. cuDF has classes that better represent column data types and can be passed instead.

Second part of this API change is to remove the Python dictionary -> `std::vector` conversion that is used to enable passing a dictionary of (column name, data type) pairs. It should be possible to pass a `std::map` from Cython instead of the current hacky conversion to a vector of strings.

Suggested steps:

- [x] Expand the API to allow passing `std::vector<data_type>`. Python layer and tests can keep using the old API. **Unblocks issue [#7110](https://github.com/rapidsai/cudf/issues/7110)**.
- [x] Expand the C++ API to allow passing `std::map<std::string, data_type>` (column name, type name). Update C++ tests to use the new APIs.
- [x] Remove the dictionary -> vector conversion in the Python layer and switch to using `std::map<std::string, data_type>` when the dictionary is passed to the Python reader API.
- [ ] Remove the option to pass `std::vector<std::string>`.

**Comment by vuule** [comment]
Blocks the reader part of https://github.com/rapidsai/cudf/issues/7110

**Comment by vuule** [comment]
@galipremsagar The C++ changes are done, ready to switch the Python to use the new APIs.

**Comment by galipremsagar** [comment]
@vuule Cython is not using any `std::vector<std::string>` for `set_dtypes`, it now safe to be removed.

**Comment by vuule** [comment]
Thank you for taking care of the Cython side, now I get to remove some code :D

**Comment by galipremsagar** [comment]
> Thank you for taking care of the Cython side, now I get to remove some code :D

Burn it away :fire: :fire:

**Comment by revans2** [comment]
Be aware that when I tried to do this on the java side I ran into a bug that is still open.

https://github.com/rapidsai/cudf/issues/8613

We cannot move the java code over to the new API until this is fixed.
