### ISSUE TITLE
[BUG] incorrect assertion in stringConcatenate and listConcatenateByRow

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#8246]
**Describe the bug**
There exists incorrect assertion on length of input columns in both [stringConcatenate](https://github.com/rapidsai/cudf/blob/92f067dcd80ce11c0431432f3817bebfa97816a0/java/src/main/java/ai/rapids/cudf/ColumnVector.java#L512) and [listConcatenateByRow](https://github.com/rapidsai/cudf/blob/92f067dcd80ce11c0431432f3817bebfa97816a0/java/src/main/java/ai/rapids/cudf/ColumnVector.java#L551). However, libcudf supports single column concatenation for both string and list_by_row. And single column concatenation is also valid in Spark.

**Expected behavior**
We should reduce the requirement of length from 2 to 1, so as to unblock single column inputs from Spark rapids.

**Comment by Salonijain27** [comment]
@sperlingxx seems like the PR to fix this issue has been merged. Are we good to close this issue?
