### ISSUE TITLE
[FEA] support for strings columns

### ISSUE THREAD

**Issue by yaronha** [rapidsai/cudf#825]
**Is your feature request related to a problem? Please describe.**
I'm reading tables from an external DB, some columns contain strings and the cudf fails with `Strings are not yet supported`, i looked at `nvstrings` but not sure how to use it in the context of creating a Dataframe, i tried the following:

```python
import nvstrings
s = nvstrings.to_device(['a', 'b', 'c'])
df['s'] = s
```
got: `ArrowTypeError: 'nvstrings' object is not iterable`

 i wonder whats the plan to support Strings? and if there are some suggested workarounds/best-practices?

**Describe the solution you'd like**
I would like to have support for using string columns

**Describe alternatives you've considered**
a possible short term alternative may be converting a strings columns to a valid GPU data type (category, hash, hash list). it may also be possible to read from a DB to pandas DF, and then converting the specific columns to another cudf type, but i guess it means an extra copy and overhead which can be avoided if we transform data types in-flight.

**Additional context**
I assume many data sets will contain string columns, users would appreciate a solution which is as transparent as possible

**Comment by kkraus14** [comment]
Fixed by #1032
