### ISSUE TITLE
[BUG] bug passing in cp.array in quantile function

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8288]
**Describe the bug**
Possible bug passing in cp.array in quantile function: issue appears in Series and DataFrame

**Steps/Code to reproduce bug**
```
series = cudf.Series([1,2,3,4])
series.quantile([0.25, 0.5, 0.75])  # works
series.quantile(np.arange(0.25, 1, 0.25)) # works 
series.quantile(cp.arange(0.25, 1, 0.25)) # TypeError: only size-1 arrays can be converted to Python scalars
```
Similar can happen in DataFrame

**Environment overview (please complete the following information)**
conda environment, rapids-0.19

**Comment by harrism** [comment]
Please always title your issue, and follow the instructions in the issue description. Please don't just leave the instructions in the issue. I've added a title, but I don't know if it's a good one, so please edit it as necessary.
