### ISSUE TITLE
[BUG] Scalability of `dask_cudf.read_csv`.

### ISSUE THREAD

**Issue by trivialfis** [rapidsai/cudf#8295]
Hi, I'm using `dask_cudf` to read csv data and have compared the performance between different numbers of workers.  The benchmark is performed using the `HIGGS` dataset from UCI machine learning repository.

# results
```
workers: seconds
1: 12.3432776927948
2: 22.175198078155518
3: 24.799917459487915
4: 48.711235761642456
5: 52.810699462890625
6: 71.11984133720398
7: 81.38515329360962
8: 91.19775366783142
```
As you can see the performance decrease with the number of workers increase.

# script
``` python
from dask_cuda import LocalCUDACluster
from distributed import Client, wait
import dask_cudf
from dask_ml.model_selection import train_test_split
from typing import Tuple
from dask import dataframe as dd
from time import time
import argparse


def load_higgs() -> Tuple[dd.DataFrame, dd.Series, dd.DataFrame, dd.Series]:
    file_path = "HIGGS/HIGGS.csv"
    colnames = ["label"] + ["feature-%02d" % i for i in range(1, 29)]

    s = time()
    df = dask_cudf.read_csv(file_path, header=None, names=colnames)
    y = df["label"]
    X = df[df.columns.difference(["label"])]

    X, y = client.persist([X, y])
    wait([X, y])
    print("Load data:", time() - s)

    s = time()
    X_train, X_valid, y_train, y_valid = train_test_split(
        X, y, test_size=0.33, random_state=42
    )
    X_train, X_valid, y_train, y_valid = client.persist(
        [X_train, X_valid, y_train, y_valid]
    )
    wait([X_train, X_valid, y_train, y_valid])
    print("Train test split:", time() - s)

    return X_train, X_valid, y_train, y_valid


def main(client: Client):
    s = time()
    X_train, X_valid, y_train, y_valid = load_higgs()
    print("load: ", time() - s)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--n_workers", type=int, required=True)
    args = parser.parse_args()
    with LocalCUDACluster(n_workers=args.n_workers) as cluster:
        print("dashboard:", cluster.dashboard_link)
        with Client(cluster) as client:
            main(client)
```

# environment
dask_cudf: `0.19.2`
cudf: `0.19.2`
python: `3.7.10`
dask: `2021.04.0`
distributed: `2021.04.0`

All are installed via conda.

**Comment by ayushdg** [comment]
I wasn't able to reproduce locally, tested from 1-4 workers (on a system with 4 GPUs). It might be worth getting a dask [performance report](https://distributed.dask.org/en/latest/diagnosing-performance.html) or a screen grab of the dask profile  to get a better sense of what might be happening

**Comment by trivialfis** [comment]
Thanks for the reply, I will try to obtain the performance report.

**Comment by trivialfis** [comment]
Suggested by @ayushdg , here is the result I got from running read_csv on prom:


[cudf_issue.zip](https://github.com/rapidsai/cudf/files/6597640/cudf_issue.zip)

**Comment by quasiben** [comment]
How big is the HIGGs data set ?  If it fits comfortably on a single GPU, transfers could lead to lower performance ?  Are you measuring performance of the read_csv or the full workflow ?

**Comment by trivialfis** [comment]
Thanks for the reply.  It's a moderately sized dataset with 11000000 samples and 29 features and it's dense.   It can be downloaded from https://archive.ics.uci.edu/ml/datasets/HIGGS . Sorry for didn't provide a full description of the data.

> If it fits comfortably on a single GPU, transfers

Yes, it can fit comfortably in 1 GPU. 

>  Are you measuring the performance of the read_csv or the full workflow

I'm only measuring performance of `read_csv`.  

> transfers could lead to lower performance 

Not sure, that's what this issue for. ;-)  I'm running it on prom so all GPUs are reading the same file and are attached to a single node.  Also reading parquet is blazing fast.   I can't be sure whether it's bounded by IO or by some other overhead introduced by accident.  It's a bit surprising to see the time increases almost linearly.

**Comment by ayushdg** [comment]
Looking at the profile there seem to be no transfers and the raw `read_csv` time seems to be increasing linearly as the number of GPU's increase. Given that this is a single large csv file that is being read by multiple workers, it feels like either an IO bottleneck or a single CPU thread responsible for IO. 

Since the same issue doesn't happen with parquet I'm curious if the dataset is a single parquet file or multiple files?

**Comment by trivialfis** [comment]
> I'm curious if the dataset is a single parquet file or multiple files

It's multiple files obtained by first reading the csv then save parquet.

**Comment by trivialfis** [comment]
@ayushdg Thanks for looking into it.  Short summary: the issue is caused by data storage instead of cudf.
