### ISSUE TITLE
[BUG] reading a parquet file with no rows and nested types can throw an error

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8323]
**Describe the bug**
Because of the bug fixed by #8314 I decided to take a look at everywhere that make_empty_column is used without an explicit type id.

https://github.com/rapidsai/cudf/blob/de579a59714f960fe33440811b4c49e5efeb3f3f/cpp/src/io/parquet/reader_impl.cu#L1575

is one of those places, but it looks like all of the readers have similar problems, just not all of them support nested types yet.

**Steps/Code to reproduce bug**
Just read the attached file [empty_nested.snappy.parquet.zip](https://github.com/rapidsai/cudf/files/6525104/empty_nested.snappy.parquet.zip) and you get an error like.
```
cuDF failure at: ../src/column/column_factories.cpp:66: make_empty_column is invalid to call on nested types
```

**Expected behavior**
You get the correct empty table back.

**Comment by harrism** [comment]
@nvdbaranec do you want to tackle #8322 together with this one?

**Comment by nvdbaranec** [comment]
> 
> 
> @nvdbaranec do you want to tackle #8322 together with this one?

Yep, I'll handle it.  (Separate PR though)
