### ISSUE TITLE
[BUG] cudf doc build failures

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#8345]
After https://github.com/rapidsai/cudf/pull/8293 was merged in, I was expecting to see the page listed on the [I/O index](https://docs.rapids.ai/api/cudf/nightly/io.html).  Checking the doc [build logs](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/doc-builds/job/docs-build/2750/console), it looks like there is a failure with the notebook conversion:

```
05:30:27 nbsphinx.NotebookError: UndefinedError in 10min.ipynb:
05:30:27 'nbformat.notebooknode.NotebookNode object' has no attribute 'tags'
```

**Comment by galipremsagar** [comment]
I was not able to repro this error on `4.0.2` version of `sphinx`, but from the log the docs build seems to be using older version of some packages, they are:
 `sphinx` - `3.5.3` (newer is `4.0.2`)
`sphinxcontrib-serializinghtml` - `1.1.4` (newer is `1.1.5`)
`sphinxcontrib-htmlhelp` - `1.0.3` (newer is `2.0.0`)

@ajschmidt8 this looks like a environment issue, can we sync up the docs environment to be similar to [dev environments](https://github.com/rapidsai/cudf/tree/branch-21.06/conda/environments) where I'm not seeing these errors.

**Comment by ajschmidt8** [comment]
@galipremsagar, I also notice that our `devel` containers are using `sphinx` 3.5.3. Strangely, we don't have any version pins on `sphinx` in our conda recipe below. I'll have to look into this to see why we're not getting the latest `sphinx` version. I likely won't get to it until next week however.

https://github.com/rapidsai/integration/blob/branch-21.06/conda/recipes/rapids-doc-env/meta.yaml#L36-L50

**Comment by ajschmidt8** [comment]
after a quick investigation, I noticed that the latest version of [`sphinx-click` on conda-forge](https://anaconda.org/conda-forge/sphinx-click/files) requires `sphinx < 4`. That's likely why we're not getting the latest `sphinx` version.

![image](https://user-images.githubusercontent.com/7400326/119679666-8aa7bb80-be0e-11eb-821e-cf02cdfabf6e.png)

**Comment by ajschmidt8** [comment]
I'm not sure if that version spec on `conda-forge` is accurate though, because the `sphinx-click` source code below seems to indicate a different spec. I'll investigate this more next week.

https://github.com/click-contrib/sphinx-click/blob/3.0.0/requirements.txt

**Comment by galipremsagar** [comment]
Sure, from `cudf` side we are safe to remove `sphinx-click` if there is no other repo using it.

**Comment by jakirkham** [comment]
Offline @dantegd and I came to the conclusion that this may be related to this `nbsphinx` issue ( https://github.com/spatialaudio/nbsphinx/issues/563 ). If so, this may just come down to metadata hot-fixing as described in issue ( https://github.com/conda-forge/nbsphinx-feedstock/issues/36 )

Though we didn't dig into this `sphinx-click` angle. So there might be something we are missing in that analysis

**Comment by ajschmidt8** [comment]
Opened up https://github.com/rapidsai/integration/pull/291 to address this. That seemed to fix the `cudf` builds for me locally.

**Comment by ajschmidt8** [comment]
After https://github.com/rapidsai/integration/pull/291 was merged and installed in the containers, it seems that doc builds are fixed (link below). Closing this issue.

https://gpuci.gpuopenanalytics.com/job/rapidsai/job/doc-builds/job/docs-build-pipeline/311/
