### ISSUE TITLE
[FEA] Add a type-equality check function in core cudf.

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#8357]
It is currently pretty common to see code like this cudf:

`CUDF_EXPECTS(lhs.type() == rhs.type(), "Both inputs must be of the same type");`

But this can fail pretty badly in the case of nested types.   For example,  a `list<int>` column and a `list<list<float>>` would pass this check, but then explode spectacularly later on. 

A function like `column_types_equal(column_view, column_view)` would allow for a more thorough check.  Bonus points for a scalar version as well.

**Comment by isVoid** [comment]
For reference, something like this: https://github.com/rapidsai/cudf/blob/90e29d9f64207a61966aba216af55c9a11d4c5fa/cpp/src/lists/copying/scatter_helper.cu#L33-L41
(also just noticed a but in this one, shouldn't just compare `.id()`, but should compare `.type()`.)

**Comment by ttnghia** [comment]
@isVoid Is this already addressed, so we can close it?
