### ISSUE TITLE
[FEA] copy_if_else support for nested scalar values

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8361]
**Is your feature request related to a problem? Please describe.**
cudf::copy_if_else has support for APIs that take scalar values for both the lhs, the rhs, or both. We would like to be able to use these APIs for nested types like Structs and Arrays.

**Comment by firestarman** [comment]
Hi @gerashegalov , 
Could I know any updates or plan for this ?
Thanks in advance.

**Comment by gerashegalov** [comment]
Hi @firestarman, I am working on struct scalar right now. I understand that I am slow because I am getting used to C++ and cudf but I am making progress.
