### ISSUE TITLE
[FEA] API to prune null masks from all valid columns 

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#8365]
As requested here https://github.com/rapidsai/cudf/issues/7654#issuecomment-848668976, an API that takes a table and prunes null masks from its columns which have a null mask allocated but no nulls in them. Preferably this API would use a single kernel per table rather than one kernel per column.

**Comment by GregoryKimball** [comment]
Closed downstream by #9061, we may upstream that feature to libcudf if there is more interest.
