### ISSUE TITLE
[DOC] Inconsistent installation instructions

### ISSUE THREAD

**Issue by henningpeters** [rapidsai/cudf#838]
**Describe the bug**
rapids.ai's installation instructions are outdated

**Describe the problems or issues found in the documentation**
Installation procedures for conda and pip between GitHub cudf Readme's and rapids.ai are not fully in sync, example:

website for cudf:
```
$ conda install -c numba -c nvidia -c rapidsai -c conda-forge -c defaults cudf=0.5
```

GitHub for cudf:
```
$ conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf=0.5
$ conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults cudf=0.5
$ pip install cudf-cuda92
$ pip install cudf-cuda100
```

**Suggested fix for documentation**
Keep docs and website in sync

**Comment by mike-wendt** [comment]
@henningpeters the website has been updated with the chooser https://rapids.ai/start.html#get-rapids that updates based off of the desired install method/CUDA version

I believe this resolves this issue, please confirm

**Comment by henningpeters** [comment]
Something's wrong:
```
unable to resolve host address 'rapids.ai'
```

**Comment by henningpeters** [comment]
Nevermind, now it works, will check it out...

**Comment by henningpeters** [comment]
The GitHub readme's installation instructions and the website chooser are still not yet fully in sync, in particular the GitHub instructions don't enforce version numbers for Python and cudf. See below for a summary:

```
github:
conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf
conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults cudf
pip install cudf-cuda92
pip install cudf-cuda100

rapids.ai:
conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf=0.5 python=3.6
conda install -c nvidia/label/cuda10.0 -c rapidsai/label/cuda10.0 -c numba -c conda-forge -c defaults cudf=0.5 python=3.6
python3.6 -m pip install cudf-cuda92==0.5
python3.6 -m pip install cudf-cuda100==0.5
```

**Comment by harrism** [comment]
@randerzander Are you working on this issue?
