### ISSUE TITLE
[BUG]Function extract_element() of get_json_object return null  when input json value contains char '['/']'/'{'/'}'

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#8387]
**Describe the bug**
When input json is like below, and if we  call `get_json_object($.item)`,  it will return null. Attention, the reason why it returns null is the last char of  value string `bug_key[` is `[`.
```
{
     "\"name\":\"charlie\","
      "\"age\":\"100\","
      "\"school\":\"\","
      "\"item\":"
               "["
                       ...
                       "\"bug_key\":\"bug_value[\","
                       ...
               "]"
}
```

**Expected behavior**
we  should return like this : 
```
"["
        ...
        "\"bug_key\":\"bug_value[\","
        ...
"]"
```

**Additional context**
The problem is in function `extract_element()` (https://github.com/rapidsai/cudf/blob/branch-21.06/cpp/src/strings/json/json_path.cu#L231) . when  var `cur_el_type` is not `VALUE`, may be `ARRAY` or `OBJECT`, and then , we want to extract the value of this row, but the value string may contains char '['  or ']' or '{' or '}', though in generally,  user will not and shouldn't add a string and it  contains some char like that, but spark/Hive will return the correct value when it meets this problem.

**Comment by chenrui17** [comment]
@nvdbaranec

**Comment by nvdbaranec** [comment]
Question about this.  This piece here is not valid json:

```
      "item" : [                      
                       "bug_key" : "bug_value["
                   ]
```
The inner element in there seems to be intended to be an object, so changing it to this would be valid:


```
      "item" : [                      
                       {"bug_key" : "bug_value["}
                   ]
```

Does Spark actually work with the above case as-is or is the example wrong?

**Comment by nvdbaranec** [comment]
Pinging @trxcllnt just in case I'm mistaken.

**Comment by viadea** [comment]
I think @nvdbaranec  is correct.
I just quickly did a test on CPU mode's Spark, and here are the results:
1. Bad json format -- returns null.
```
import org.apache.spark.sql.functions._ 
import org.apache.spark.sql.types._
val inputDF = Seq ((0, """{"item" : ["bug_key" : "bug_value["]}""")).toDF("id", "info")
val outputDF = inputDF.select($"id", get_json_object($"info", "$.item").alias("item"))
outputDF.show(false)

+---+----+
|id |item|
+---+----+
|0  |null|
+---+----+
```

2. Good json format -- returns correct value
```
import org.apache.spark.sql.functions._ 
import org.apache.spark.sql.types._
val inputDF = Seq ((0, """{"item" : [{"bug_key" : "bug_value["}]}""")).toDF("id", "info")
val outputDF = inputDF.select($"id", get_json_object($"info", "$.item").alias("item"))
outputDF.show(false)

+---+--------------------------+
|id |item                      |
+---+--------------------------+
|0  |[{"bug_key":"bug_value["}]|
+---+--------------------------+
```

@chenrui17 Could you also confirm with above Apache Spark's behavior(CPU mode)?

**Comment by chenrui17** [comment]
@vindows @nvdbaranec you are right, before i post the json format looks like not valid, the inner element in there seems to be intended to be an object.  
what i want to say is that : if input json is like  this nested json format, get_json_object API will return wrong result , compared to CPU spark result.

**Comment by chenrui17** [comment]
```
  "{"
      "\"a\":\"aaa\","
      "\"b\":\"bbb\","
      "\"c\":\"ccc\","
      "\"id\":\"123456\","
      "\"item\":"
            "["
                "{"
                              "\"ID\":null,"
                              "\"image\":\"https://xxxxxx\","
                              "\"type\":\"up_down\","
                              "\"source\":0,"
                              "\"pd\":\"mini\","
                              "\"searchID\":\"6bfdae0[\""
                "}"
            "],"
      "\"pos\":1"
  "}"
```
Input example for details.

**Comment by nvdbaranec** [comment]
If you have the chance, give this patch a try.  It should address the issue:

https://github.com/rapidsai/cudf/pull/8556
