### ISSUE TITLE
[BUG] cudf installation via pip segfaults

### ISSUE THREAD

**Issue by henningpeters** [rapidsai/cudf#839]
**Describe the bug**
Installing cudf via pip results in a segfault in the installation process

**Steps/Code to reproduce bug**
```
pip install cudf
pip install cudf-cuda92
pip install cudf-cuda100
```

**Expected behavior**
No segfault :-)

**Environment details (please complete the following information):**
 - Environment location: GCP / Ubuntu 18.04 / CUDA 10.0 
 - Method of cuDF install: pip

**Additional context**
It didn't matter which pip package (cudf/cudf-cuda92/cudf-cuda100) I chose.
The full package name incl. version was `cudf_cuda100-0.5.0.post1-cp36-cp36manylinux1_x86_64.whl`
It is not fully clear whether the crash happens on installing cudf or any of its deps.

**Comment by raydouglass** [comment]
Since you are using CUDA 10, please only use `pip install cudf-cuda100`. Please make sure your pip is referring to a python 3.6 or 3.7 dist-package (check with `pip -V`).

If you're verified that and still having an issue, can you please provide the full output from a clean install attempt using the following: `pip install -vvv cudf-cuda100`

**Comment by henningpeters** [comment]
It worked with the latest package and a fresh install:

```
Successfully installed cffi-1.11.5 cudf-cuda100-0.5.1 cython-0.29.4 llvmlite-0.27.0 numba-0.41.0 numpy-1.16.1 nvstr
ings-cuda100-0.2.0.post2 pandas-0.24.1 pyarrow-0.12.0 pycparser-2.19 python-dateutil-2.8.0 pytz-2018.9 six-1.12.0
```

I also verified with latest pip, running it in a virtualenv and tested it with a mean calc sample.

**Comment by kkraus14** [comment]
This was likely a numpy ABI related issue which the 0.5.1 hotfix resolved, thanks for the followup @henningpeters!
