### ISSUE TITLE
[FEA] Cleanup on logic inside DeviceRolling::is_supported()

### ISSUE THREAD

**Issue by nvdbaranec** [rapidsai/cudf#8399]
There is some logic in https://github.com/rapidsai/cudf/blob/0eeb0c9239eb62b08a2be81d339c03c1078659c3/cpp/src/rolling/rolling_detail.cuh#L82  that really should be covered by `is_valid_aggregation`, but `is_valid_aggregation` is currently missing some edge cases.

```
 // MIN/MAX supports all fixed width types
 (((O == aggregation::MIN || O == aggregation::MAX) && cudf::is_fixed_width<T>()) ||

  // SUM supports all fixed width types except timestamps
  ((O == aggregation::SUM) && (cudf::is_fixed_width<T>() && !cudf::is_timestamp<T>())) ||

  // MEAN supports numeric and duration
  ((O == aggregation::MEAN) && (cudf::is_numeric<T>() || cudf::is_duration<T>())));
```

Once these edge cases are cleared up, clear out this code.  Also, if `is_valid_aggregation ` can handle a wide enough set of cases, it might be possible to remove the various `is_supported()` functions entirely and just have a single generic global template (checking `is_valid_aggregation` and `has_corresponding_operator`) used in it's place.

**Comment by nvdbaranec** [comment]
Pinging @mythrocks

**Comment by bdice** [comment]
@mythrocks @karthikeyann This came up in our meeting today. If you have any additional context on what needs to be done or whether this issue can be closed, feel free to share. The code has moved to a different filename since this issue was filed: https://github.com/rapidsai/cudf/blob/3bf6d1dbe485f479164c13df9d6007ffdefaf613/cpp/src/rolling/detail/rolling.cuh#L83

**Comment by mythrocks** [comment]
There is some cleanup that can be done here, but I don't know if there's enough to warrant a pair-up.
At the time, `is_valid_aggregation()` returned incorrect results for `STRUCT`/`LIST`. E.g. `SUM` on `STRUCT` columns. I haven't checked if that's been sorted out. If it has, then `is_valid_aggregation()` can be used in place of `DeviceRolling::is_supported()`.
