### ISSUE TITLE
[BUG] conda install nightly cudf, librmm&libcudf version mismatched

### ISSUE THREAD

**Issue by pxLi** [rapidsai/cudf#8404]
**Describe the bug**
related to https://github.com/NVIDIA/spark-rapids/issues/2521

use conda to install nightly cudf could bring mismatched version of librmm/libcudf and result in,
```
>>> import cudf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cudf/__init__.py", line 11, in <module>
    from cudf import core, datasets, testing
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/__init__.py", line 3, in <module>
    from cudf.core import _internals, buffer, column, column_accessor, common
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/_internals/__init__.py", line 3, in <module>
    from cudf.core._internals.where import where
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/_internals/where.py", line 11, in <module>
    from cudf.core.column import ColumnBase
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/column/__init__.py", line 3, in <module>
    from cudf.core.column.categorical import CategoricalColumn
  File "/opt/conda/lib/python3.8/site-packages/cudf/core/column/categorical.py", line 25, in <module>
    from cudf import _lib as libcudf
  File "/opt/conda/lib/python3.8/site-packages/cudf/_lib/__init__.py", line 4, in <module>
    from . import (
ImportError: /opt/conda/lib/python3.8/site-packages/cudf/_lib/groupby.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN4cudf7groupby7groupby5shiftERKNS_10table_viewENS_9host_spanIKiLm18446744073709551615EEERKSt6vectorISt17reference_wrapperIKNS_6scalarEESaISC_EEPN3rmm2mr22device_memory_resourceE
```

command: `conda install -y -c rapidsai -c rapidsai-nightly -c nvidia -c conda-forge -c defaults cudf=21.06 python=3.8 cudatoolkit=${CUDA_VER}`

_21.05.28_ - **21.06.00**
![image](https://user-images.githubusercontent.com/8086184/120165364-15811f80-c22e-11eb-81fd-2c82d2986fd8.png)
_21.05.30_ - **21.06.00**
![image](https://user-images.githubusercontent.com/8086184/120165267-f7b3ba80-c22d-11eb-977e-62b4702b81b8.png)
_21.05.30_ - **21.08.00** matched
![image](https://user-images.githubusercontent.com/8086184/120165765-7c063d80-c22e-11eb-85f7-7413601a7adf.png)

This occur intermittently,  looks like there could be some bad deployment setup which overwrites the regular conda deployment.

**Expected behavior**
cudf, rmm, librmm and libcudf version should be the same version via conda install

**Comment by pxLi** [comment]
I keep monitoring the status for only **21.06 nightly** has this issue,  21.08 looks fine

**Comment by firestarman** [comment]
I am wondering if this mismatch would happen when the librmm/libcudf build fails, but rmm/cudf build does not.

**Comment by pxLi** [comment]
looks like the version mismatching of 21.06 nightly did not happen again in recent 5 days.

Close this issue for now, will reopen if see this again
