### ISSUE TITLE
[BUG] cudf 0.19.1 cannot load cupy data

### ISSUE THREAD

**Issue by cdeotte** [rapidsai/cudf#8408]
**Describe the bug**
You cannot assign multiple cudf columns at once with cupy data

**Steps/Code to reproduce bug**

    x = [[1,2,3,4,5,6,7,8],
         [1,2,3,4,5,6,7,8],
         [1,2,3,4,5,6,7,8]]
    y = [[5,6,7,8],
         [5,6,7,8],
         [5,6,7,8]]
    d = cudf.DataFrame(x,columns=['a','b','c','d','e','f','g','h'])
    d.loc[:,['a','b','c','d']] = cupy.array(y) 
    print(d)

    ##########
    # DISPLAYS

    #  a | b | c | d | e | f | g | h
    # -- | -- | -- | -- | -- | -- | -- | --
    # 5 | 5 | 5 | 5 | 5 | 6 | 7 | 8
    # 6 | 6 | 6 | 6 | 5 | 6 | 7 | 8
    # 7 | 7 | 7 | 7 | 5 | 6 | 7 | 8

**Expected behavior**
It should display

    #  a | b | c | d | e | f | g | h
    # -- | -- | -- | -- | -- | -- | -- | --
    # 5 | 6 | 7 | 8 | 5 | 6 | 7 | 8
    # 5 | 6 | 7 | 8 | 5 | 6 | 7 | 8
    # 5 | 6 | 7 | 8 | 5 | 6 | 7 | 8

**Environment details**
RAPIDS cudf 0.19.1

**Comment by shwina** [comment]
Thanks for reporting.

Note that you will see _much_ better performance when the _columns_ you want to set are contiguous in memory rather than the _rows_. Thus, the following is much preferred (and works today):


```python
In [55]: d
Out[55]:
   a  b  c  d  e  f  g  h
0  1  2  3  4  5  6  7  8
1  1  2  3  4  5  6  7  8
2  1  2  3  4  5  6  7  8

In [56]: y = cupy.asarray([[5, 5, 5], [6, 6, 6], [7, 7, 7], [8, 8, 8]])

In [57]: y
Out[57]:
array([[5, 5, 5],
       [6, 6, 6],
       [7, 7, 7],
       [8, 8, 8]])

In [58]: d.assign(**dict(zip(('a', 'b', 'c', 'd'), y)))
Out[58]:
   a  b  c  d  e  f  g  h
0  5  6  7  8  5  6  7  8
1  5  6  7  8  5  6  7  8
2  5  6  7  8  5  6  7  8
```

**Comment by vyasr** [comment]
I no longer observe this bug on the most recent version of cudf (22.08):
```
   a  b  c  d  e  f  g  h                                                                                                                                                                                  │
0  5  6  7  8  5  6  7  8                                                                                                                                                                                  │
1  5  6  7  8  5  6  7  8                                                                                                                                                                                  │
2  5  6  7  8  5  6  7  8
```
