### ISSUE TITLE
[FEA] Java: CollectSetAggregation need to implement the RollingAggregation interface

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#8412]
**Describe the bug**
After the introduction of the `RollingAggregation` interface, each Aggregation Operation, which can be used in rolling window, need to implement it. Otherwise, they can not corporate with the holder `AggregationOverWindow`.

**Expected behavior**
I filed #8406 to fix this issue.

**Comment by revans2** [comment]
I don't consider this a bug. Until the rolling window support for collect set was merged in, the java `CollectSetAggregation` should not have implemented `RollingAggregation`. It is a feature that was missed.
