### ISSUE TITLE
[BUG] Can't install cudf

### ISSUE THREAD

**Issue by hadarishav** [rapidsai/cudf#8414]
Used the command : conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=0.19 python=3.7 cudatoolkit=10.1
I am on centOS 7.9
It gives the following error:
PackagesNotFoundError: The following packages are not available from current channels:

  - cudatoolkit=10.1
  - cudf=0.19

Current channels:

  - https://conda.anaconda.org/rapidsai/linux-32
  - https://conda.anaconda.org/rapidsai/noarch
  - https://conda.anaconda.org/nvidia/linux-32
  - https://conda.anaconda.org/nvidia/noarch
  - https://conda.anaconda.org/numba/linux-32
  - https://conda.anaconda.org/numba/noarch
  - https://conda.anaconda.org/conda-forge/linux-32
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-32
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/linux-32
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/linux-32
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/linux-32
  - https://repo.anaconda.com/pkgs/pro/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by shwina** [comment]
Thanks for reporting. It looks like you're trying to install on a 32-bit system, which is not supported.

**Comment by hadarishav** [comment]
no. It is a 64-bit system.

**Comment by shwina** [comment]
Could you please post the result of `conda info`? For me, it's something like:

```
conda info                                                                                                                                        (rapids)

     active environment : rapids
    active env location : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0/envs/rapids
            shell level : 1
       user config file : /home/ashwin/workspace/rapids/.condarc
 populated config files : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0/.condarc
                          /home/ashwin/workspace/rapids/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.8.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0  (writable)
      conda av data dir : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0/pkgs
                          /home/ashwin/workspace/rapids/.conda/pkgs
       envs directories : /home/ashwin/workspace/rapids/compose/etc/conda/cuda_11.2.0/envs
                          /home/ashwin/workspace/rapids/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.24.0 CPython/3.8.5 Linux/5.8.0-44-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by hadarishav** [comment]
Thanks @shwina ! Now, I deleted miniconda from my system, installed anaconda and cudf got installed without any issues. I don't know why it was not before.

**Comment by shwina** [comment]
Great -- thanks for letting us know and glad it's resolved!
