### ISSUE TITLE
[FEA] Time series resampling (df.resample)

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#8416]
In pandas, I can "resample" time series data (converting the frequency or up/downsampling the data while keeping track of the associated values) with the convenient [resample](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.resample.html) API. This feature request comes care of [this stackoverflow post](https://stackoverflow.com/questions/67757306/how-to-use-pandas-resample-with-cudf).

In the following example, per-minute data is aggregated into three minute bins and the associated values are summed.

```python
import pandas as pd
​
index = pd.date_range('1/1/2000', periods=9, freq='T')
series = pd.Series(range(9), index=index)
print(series, "\n")
print(series.resample('3T').sum())
2000-01-01 00:00:00    0
2000-01-01 00:01:00    1
2000-01-01 00:02:00    2
2000-01-01 00:03:00    3
2000-01-01 00:04:00    4
2000-01-01 00:05:00    5
2000-01-01 00:06:00    6
2000-01-01 00:07:00    7
2000-01-01 00:08:00    8
Freq: T, dtype: int64 

2000-01-01 00:00:00     3
2000-01-01 00:03:00    12
2000-01-01 00:06:00    21
Freq: 3T, dtype: int64
```

**Comment by shwina** [comment]
There has been some related discussion in https://github.com/rapidsai/cudf/issues/6255.

**Comment by shwina** [comment]
Just curious: does Spark have similar resampling functionality? Google says "no", but just thought to check. cc: @revans2 @jlowe

**Comment by jlowe** [comment]
> does Spark have similar resampling functionality?

No, Spark does not have built-in resampling like this.
