### ISSUE TITLE
tail cudf method

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#845]
There is a `head` method for cudf, while there is no `tail`. I would like to request `tail` method, similarly as the one in pandas.
```py
print(gdf.head(3))
#   id4 mean_v1 mean_v2   mean_v3
#0    1       3       3 50.523914
#1    2       2       3 50.630413
#2    3       3       3 50.728027
print(gdf.tail(3))
#AttributeError: 'DataFrame' object has no attribute 'tail'
```

**Comment by beckernick** [comment]
This could be a good first issue. `tail` methods could be defined analogously to the `head` methods as `Series` and `DataFrames` are iterable:

```
def tail(self, n=5):
    return self[-n:]
```
