### ISSUE TITLE
mean function should coerce from integer to double

### ISSUE THREAD

**Issue by jangorecki** [rapidsai/cudf#847]
Using 0.5 installed from pip. Mean function called on integer is giving an integer answer, which is truncated form of the correct answer. I below code I expect to get mean_v1 as 1.5
```py
import cudf
x = cudf.DataFrame([
  ("id1", [1, 1]),
  ("v1", [1, 2])
])
ans = x.groupby(['id1']).agg({'v1':'mean'})
print(ans)
#   id1 mean_v1
#0    1       1
```

**Comment by kkraus14** [comment]
So Pandas will actually return an integer from the `mean()` call if the result can be safely typecast from the float to an integer. We're exploring this in #894 so closing this as a duplicate.

**Comment by thomcom** [comment]
Also, `mean` does coerce to float as of `branch-0.6` now and going forward. #894 discusses if we should cast back to int ala pandas.
