### ISSUE TITLE
[FEA] Creating a structDtypeColumn from existing df columns

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#8473]
**What is your question?**
Is it possible to create a `structDtype` column from existing cudf columns?

eg:
```python
>>> df = cudf.DataFrame({'a':['aa','aa','cc'], 'b':['x','y','z'], 'c':['1','2','3']})
>>> df
	a	b	c
0	aa	x	1
1	aa	y	2
2	cc	z	3

# Create a new struct column
>>> df
	a	b	c	d
0	aa	x	1	{'b': 'x', 'c': '1'}
1	aa	y	2	{'b': 'y', 'c': '2'}
2	cc	z	3	{'b': 'z', 'c': '3'}
```

**Comment by shwina** [comment]
Not today, but it should be very easy to add. Do you have an API in mind for doing this? This is a situation where there's no equivalent Pandas API AFAIK.

**Comment by ayushdg** [comment]
For the initial api, being able to create a `StructColumn` column by passing cudf series in the constructor seems like a good option. Something along the lines of the example below would work.
```python
df['d'] = cudf.core.column.StructColumn(data=[df['b'], df['c']])
```

**Comment by shwina** [comment]
I'd rather we avoid interacting with Column directly. How about something like:

```python
cudf.Series.struct.from_arrays(list_of_array_likes, names)
```

**Comment by ayushdg** [comment]
> I'd rather we avoid interacting with Column directly. How about something like:
> 
> ```python
> cudf.Series.struct.from_arrays(list_of_array_likes, names)
> ```

Agreed, this is a better option. Works for me!

**Comment by shwina** [comment]
Decided to go with a simpler `df.to_struct()` API instead.
