### ISSUE TITLE
[BUG] Segfault when reading small zipped CSV files

### ISSUE THREAD

**Issue by elstehle** [rapidsai/cudf#8497]
**Describe the bug**
There's an out-of-bounds memory access that is observed when reading in `.zip` files that are less than, approximately 64KB in size.

**Steps/Code to reproduce bug**
1. Download the following zip file
```
wget http://data.gdeltproject.org/gdeltv2/20210513074500.export.CSV.zip
```

1. Try to read in the downloaded zipped CSV file
```python
import cudf
filename = '20210513074500.export.CSV.zip'
dfs = cudf.read_csv(filename, header=None, sep='\t')
```

**Expected behavior**
Data is read into cudf.

**Comment by quasiben** [comment]
Thanks @elstehle I was able to verify this is a bug.  @harrism do you think this is an issue on the libcudf side ?

**Comment by elstehle** [comment]
@quasiben thanks for verifying. I have investigated the issue and put up a PR which should fix this:
https://github.com/rapidsai/cudf/pull/8498
