### ISSUE TITLE
[BUG] group_by.replace_nulls fails if the column is not nullable

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8504]
I put this as a bug because it is unexpected.

In my use case I can work around the issue because my data is already sorted by the groups. If it wasn't and I had one column that wasn't nullable in with others that were I would then have to write a conditional path that would sort the data myself ahead of time and pull out the columns that don't need null replacement and hope that `replace_nulls` would not change the order of the data.  Would be nice if `replace_nulls` could just copy the column if needed.

**Comment by ttnghia** [comment]
Can you clarify the issue, please? I dig into the `replace_null` code and see that nullable columns are already handled thus I'm not sure what's wrong here? As we can see from the code below, all columns are always sorted regardless of their nullability.

```
      bool nullable       = values.column(i).nullable();
      auto final_mr       = nullable ? rmm::mr::get_current_device_resource() : mr;
      auto grouped_values = helper().grouped_values(values.column(i), stream, final_mr);
      return nullable ? detail::group_replace_nulls(
                          *grouped_values, group_labels, replace_policies[i], stream, mr)
                      : std::move(grouped_values);
```

**Comment by ttnghia** [comment]
@revans2 is there any chance that this PR fixes your issue: https://github.com/rapidsai/cudf/pull/8699?

**Comment by revans2** [comment]
Not totally sure what happened I have tried to reproduce this and cannot. I am just going to close it and will reopen it if I see the issue again.
