### ISSUE TITLE
[FEA] CUDA versions between PyTorch and RAPIDS

### ISSUE THREAD

**Issue by yueyericardo** [rapidsai/cudf#8510]
Hi Developers,

Thanks for the great tools you have made.
Our group would like to use cudf for deep learning, however pytorch currently only support CUDA 10.2 and CUDA 11.1, the nightly version rapids supported is CUDA 11.0 and 11.2, which is a pain for users (mostly scientist) if they need to compile either pytorch or rapids from source. Is that possible for rapids to support CUDA 11.1 for user to install from conda? 

I noticed that #8224 just remove cuda 11.1 related files.

Thanks!
Richard

**Comment by IgnacioJPickering** [comment]
This will definitely be very helpful. For reference I believe the current roadmap for torch is to [not support cuda 11.2](https://github.com/pytorch/pytorch/issues/50232#issue-781659919) and go straight for 11.3.

**Comment by quasiben** [comment]
I don't think RAPIDS will specifically build packages for 11.1 and instead will rely on [CUDA Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/index.html) introduced in 11.1.  So 11.2 should be backwards compatible with 11.1

**Comment by yueyericardo** [comment]
But the pain is that pytorch and cudf could not be installed on a same conda environment, because of cudatoolkit confilcts, it's really annoying.

**Comment by quasiben** [comment]
That is annoying.  I _think_ folks are able to use latest RAPIDS and Pytorch 1.7.1 which has cuda 11.0 builds.  @IgnacioJPickering do you know if pytorch will also support cuda 11.4 ?

**Comment by yueyericardo** [comment]
From what I got, currently they are still working on to support cuda11.3 [Support CUDA 11.3 · Issue #56721 · pytorch/pytorch](https://github.com/pytorch/pytorch/issues/56721)

**Comment by quasiben** [comment]
@RobertoDF unfortunately, there are no plans to build CUDA 11.3 versions of RAPIDS but I see the frustration and need for better alignment of supported CUDA versions between PyTorch and RAPIDS

**Comment by RobertoDF** [comment]
and what about CUDA 11.4 ?

**Comment by quasiben** [comment]
Yes, there are already builds for 11.4:
- https://anaconda.org/rapidsai-nightly/cudf/files
- https://anaconda.org/rapidsai/cudf/files

**Comment by RobertoDF** [comment]
Didn't notice that!Thanks!!

**Comment by yueyericardo** [comment]
> @RobertoDF unfortunately, there are no plans to build CUDA 11.3 versions of RAPIDS but I see the frustration and need for better alignment of supported CUDA versions between PyTorch and RAPIDS

Yes, please make it high priority! Our research code needs these two library to be compatible with each other.
Currently an ugly solution is to install `pip torch==1.9.0+cu111` with `conda cudf cuda11.0`, the binary size after build the conda package is huge (1.7 GB), and there are some bugs in this solution.

**Comment by quasiben** [comment]
@ezyang (apologies if you are the wrong person to ping here), do you know if PyTorch is planning on adding CUDA 11.4/11.5 support ?  Between RAPIDS and Torch we are slightly out of sync leading to conflicts when installing both.  With 11.3 support in PyTorch we _should_ be able to build with CUDA 11.4 and things should _just work_ with [enhanced compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/)

**Comment by ezyang** [comment]
cc @malfet

**Comment by alexwilson1** [comment]
Any update on the progress of this please? What would be the current recommended way to work with PyTorch and Rapids side by side please?

**Comment by quasiben** [comment]
With the upcoming release of RAPIDS 21.12 we've enabled [CUDA Enhanced Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/) (CEC) in our builds.  This should allow for RAPIDS and Pytorch to coexist in all 11.X runtimes as long as minimum driver versions are met (as described in the link).  For example the following should work:

> conda create -n pytorch_and_rapids -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge cudf=21.12 pytorch=1.10.0 cudatoolkit=11.3

Note: RAPIDS does not explicitly build an explicit 11.3 conda package or any defined CUDA versioned package and instead relies on CEC.  A next step here would be helping PyTorch folks also use CEC . 

If you have time it would be great if anyone on this thread could test and report back

**Comment by andrearosasco** [comment]
Hey @quasiben. So right now something like this `conda install -c nvidia -c pytorch -c conda-forge cuml=22.02 pytorch torchvision cudatoolkit=11.3` should actually work? I'm running it right now. I'll let you know.

**Comment by quasiben** [comment]
Yup, that _should_ work.  Please let us know either way

**Comment by mattf** [comment]
out of curiosity, are you able to use a container for this? https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch bundles cudf and pytorch.

**Comment by andrearosasco** [comment]
Ok, the installation was successful, I'll check if everything works and let you know.

@mattf I don't have docker installed right now so I can't test it, sorry.

**Comment by andrearosasco** [comment]
Alright, I've tried to run this useless script to see if there was any "interference" and everything worked fine:
```
import torch
from cuml.cluster.dbscan import DBSCAN

dbscan = DBSCAN(eps=1.0, min_samples=1)

a = torch.zeros(1000, 1000)
a = a.to('cuda')
```

The only issue I've experienced is that the first access to the GPU (either `dbscan = DBSCAN(eps=1.0, min_samples=1)` or  a = a.to('cuda')) takes a few minutes. It's probably because I'm running it through WSL2 on Win10 2h21. This is probably not the right place to ask but do you know if this has been fixed on Win11 (I think it was on NVIDIA side)?

**Comment by quasiben** [comment]
Hmm, I have experienced that particular issue. @charlesbluca or @taureandyernv have you seen this ?  If they haven'tt I would suggest we close this and open a new issue specific to WSL and CUDA context creation

**Comment by andrearosasco** [comment]
Thanks! Updating the driver shortened the time a lot. It's still 8 seconds but it's much better than a few minutes. Do you experience a similar performance? If not they might have completely solve it in Win11

**Comment by charlesbluca** [comment]
Yeah I'd say that ~8 seconds is pretty consistent with the performance I'm seeing - I don't really have too much understanding between the differences in WSL2 between Win10 and Win11, so going off Microsoft's [official documentation](https://docs.microsoft.com/en-us/windows/ai/directml/gpu-cuda-in-wsl) I would assume that WSL2 on Win11 and Win10 21H2 are roughly equivalent, with most issues from there being resolved through NVIDIA driver updates.

To push on the original issue, @yueyericardo are you able to create an environment using the environment creation command in @quasiben's comment?

```
conda create -n pytorch_and_rapids -c rapidsai-nightly -c nvidia -c pytorch -c conda-forge cudf=21.12 pytorch=1.10.0 cudatoolkit=11.3
```

**Comment by nathanin** [comment]
Hi - @yueyericardo , did @quasiben 's command work for you? I just tried on my ubuntu system and ran into [conflicts](https://pastebin.com/AKp6GMJL). @charlesbluca did the build work when you tried it?

Has anyone been able to build an environment with rapids and pytorch living side by side recently?

**Comment by charlesbluca** [comment]
The build did work for me - granted, I did try it using mamba, so it's possible that the environment solved differently - could you try the same command with mamba and let me know if you still get conflicts?

I tried out a more general RAPIDS / PyTorch install and things were still successful:

```
mamba create -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge cudf pytorch

  + cudatoolkit               11.5.0  h36ae40a_9                   nvidia/linux-64          Cached
  + cudf                    22.04.00  cuda_11_py39_g8bf0520170_0   rapidsai/linux-64          13MB
  + pytorch                   1.11.0  py3.9_cuda11.5_cudnn8.3.2_0  pytorch/linux-64            1GB
  + pytorch-mutex                1.0  cuda                         pytorch/noarch              3kB
```

**Comment by nathanin** [comment]
Yes! mamba seems to install everything no problem. 

```
$ mamba create -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge rapids=22.02 pytorch torchvision torchaudio cudatoolkit=11.3

$ conda activate pytorch_and_rapids

$ python
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cuml; clf = cuml.neighbors.NearestNeighbors(); import torch; torch.cuda.is_available()
True
```

Thanks!

**Comment by beckernick** [comment]
@nathanin do you mean that the same `create` command works with mamba but not baseline conda?

**Comment by nathanin** [comment]
@beckernick that's right. switch `mamba` to `conda` in the line pasted above, and I get [conflicts](https://pastebin.com/xdEtz60H)

**Comment by taureandyernv** [comment]
interesting....

what version on conda and mamba are you using?  I'd like to see if updates from either of them fix or break things.

**Comment by nathanin** [comment]
```
$ mamba --version
mamba 0.14.0
conda 4.11.0
```

**Comment by charlesbluca** [comment]
I'm also on `conda` 4.11.0 and the command from your link was able to create an environment:

- https://controlc.com/b0baa7c8

**Comment by jhkonan** [comment]
This command worked for me:

```
conda create -y -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge rapids=22.02 pytorch torchvision torchaudio cudatoolkit=11.3
```

**Comment by bdice** [comment]
It looks like this issue has had a few conversations but the core problems appear to be solved. Please feel free to re-open or file a new issue if needed!

**Comment by jlobo** [comment]
Hi all, I tried different configurations from this thread to run PyTorch and RAPIDS with CUDA but it was useless for me.

I did it with docker and here is the configuration:

```
FROM nvidia/cuda:11.3.1-runtime-ubuntu20.04
ENV PATH=$PATH:/opt/conda/bin/

RUN apt-get update -y && apt-get upgrade -y \
    && apt-get install -y wget \
    ### conda ###
    && wget https://repo.anaconda.com/archive/Anaconda3-2022.10-Linux-x86_64.sh -O conda.sh \
    && bash conda.sh -b -p /opt/conda \
    && rm -f conda.sh \
    && conda update -y conda \
    && conda init \
    ### clean ###
    && apt-get remove -y wget curl \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN conda install -c rapidsai -c nvidia -c pytorch -c conda-forge cuml=22.02 pytorch torchvision cudatoolkit=11.3
```

Any suggestions how I should do it?

**Comment by jhkonan** [comment]
What issue did you get when trying this?

> 
> ```
> conda create -y -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge rapids=22.02 pytorch torchvision torchaudio cudatoolkit=11.3
> ```

**Comment by bdice** [comment]
@jlobo If you're interested in using a container, you may like to try the NVIDIA Deep Learning Frameworks (DLFW) containers. These images are pre-configured with libraries like PyTorch or TensorFlow as well as all RAPIDS libraries. See here for more information:
- Overview / docs: https://docs.nvidia.com/deeplearning/frameworks/
- PyTorch + RAPIDS container: https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch

**Comment by jlobo** [comment]
Simple never finished to resolve conflicts @jhkonan.

> What issue did you get when trying this?
> 
> > ```
> > conda create -y -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge rapids=22.02 pytorch torchvision torchaudio cudatoolkit=11.3
> > ```

**Comment by bdice** [comment]
@jlobo I strongly recommend using [mamba](https://mamba.readthedocs.io/en/latest/installation.html) for solving environments. I see conda fail quite often with complicated environments that mamba handles just fine.

**Comment by jlobo** [comment]
Thanks for the advice @bdice

**Comment by JoachimMoe** [comment]
I have tried creating the above environments using both ```conda``` and ```mamba``` , i.e. 

```conda create -y -n pytorch_and_rapids -c rapidsai -c nvidia -c pytorch -c conda-forge rapids=22.02 pytorch torchvision torchaudio cudatoolkit=11.3```

When importing *any* RAPIDS library, this error occurs: 

```
 File "rmm/_lib/device_buffer.pyx", line 1, in init rmm._lib.device_buffer
TypeError: C function cuda.ccudart.cudaStreamSynchronize has wrong signature (expected __pyx_t_4cuda_7ccudart_cudaError_t (__pyx_t_4cuda_7ccudart_cudaStream_t), got cudaError_t (cudaStream_t))                
``` 

Did anyone resolve this?
