### ISSUE TITLE
[BUG] cudf.testing.assert_frame_equal not using rtol or atol correctly for floats

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8518]
**Describe the bug**
cudf.testing.assert_frame_equal not using rtol or atol correctly for floats 
ex. cudf.testing.assert_series_equal(data, expect, rtol=1e-2, atol=1e-3)

**Steps/Code to reproduce bug**
```
data = cudf.Series([-0.43, 0.1234, 1.5, -1.31])
data = data.mod(1)
expect = cudf.Series([0.57, 0.1234, 0.5, 0.69], dtype=float)
cudf.testing.assert_series_equal(data, expect)
```
Gives error
```
AssertionError: ColumnBase are different
values are different (50.0 %)
[left]:  [0.57   0.1234 0.5    0.69  ]
[right]: [0.57   0.1234 0.5    0.69  ]
```
And here are those values.
```
data.iloc[0], expect.iloc[0]
Out: (0.5700000000000001, 0.57)
data.iloc[1], expect.iloc[1]
Out: (0.12339999999999995, 0.1234)
```

**Expected behavior**
No error. Adding an `rtol` or `atol` kwarg does nothing as well. Above values are within default values for rtol (1e-5) and atol (1e-8).

The following does work: `cp.testing.assert_array_almost_equal(data.values, expect.values)`

**Environment overview (please complete the following information)**
 conda install, rapids-0.19

**Additional context**
Part of TDD

**Comment by vyasr** [comment]
This no longer errors on 22.08:
```
>>> import cudf
>>> data = cudf.Series([-0.43, 0.1234, 1.5, -1.31])
>>> data = data.mod(1)
>>> expect = cudf.Series([0.57, 0.1234, 0.5, 0.69], dtype=float)
>>> cudf.testing.assert_series_equal(data, expect)
>>>
```
I suspect that this was resolved in #10011, but it may have happened elsewhere.
