### ISSUE TITLE
[BUG] Clip floats using integer lower/upper bounds in a Series or DataFrame fails 

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8519]
**Describe the bug**
Clipping a DataFrame or Series using ints causes a cudf Failure because it won't handle the different dtypes (int and float)

**Steps/Code to reproduce bug**
```
data = cudf.Series([-0.43, 0.1234, 1.5, -1.31])
data.clip(0, 1)

...
  File "cudf/_lib/replace.pyx", line 216, in cudf._lib.replace.clip
  File "cudf/_lib/replace.pyx", line 198, in cudf._lib.replace.clamp
RuntimeError: cuDF failure at: ../src/replace/clamp.cu:250: mismatching types of scalar and input
```
Meanwhile the following will work

```
data.clip(0., 1.)
```

**Expected behavior**
data.clip(0, 1)
Out: 
0    0.0000
1    0.1234
2    1.0000
3    0.0000
dtype: float64

will coerce the integer upper/lower bounds to the float data.

**Environment overview (please complete the following information)**
conda install rapids-0.19

**Comment by vyasr** [comment]
This no longer fails on cudf 22.08:
```
>>> data = cudf.Series([-0.43, 0.1234, 1.5, -1.31])
>>> data.clip(0, 1)
0    0.0000
1    0.1234
2    1.0000
3    0.0000
dtype: float64
```
