### ISSUE TITLE
[FEA] Optimizations for groupby::scan 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#8522]
The `groupby` object[ has a parameter](https://github.com/rapidsai/cudf/blob/6728c75e6923bd3c86955199030836d1d1561fa1/cpp/include/cudf/groupby.hpp#L112) allowing a caller to indicate that their keys (and likewise values to aggregate) are already in sorted order such that all values belonging to a particular group are already contiguous. 

However, this information is not fully leveraged in the `groupby::scan` implementation. 

Internally, the `groupby::scan` implementation calls `get_grouped_values()` to rearrange the values such that all values in the same group are contiguous https://github.com/rapidsai/cudf/blob/6728c75e6923bd3c86955199030836d1d1561fa1/cpp/src/groupby/sort/scan.cpp#L74-L75

This in turn calls the `sort_groupby_helper::grouped_values` to perform the grouping: https://github.com/rapidsai/cudf/blob/6728c75e6923bd3c86955199030836d1d1561fa1/cpp/src/groupby/sort/sort_helper.cu#L289-L302

Which in turn calls `key_sort_order` to get the indices of the sorted order of the keys: https://github.com/rapidsai/cudf/blob/6728c75e6923bd3c86955199030836d1d1561fa1/cpp/src/groupby/sort/sort_helper.cu#L107-L157

Then the values are gathered based on the sorted key order: https://github.com/rapidsai/cudf/blob/6728c75e6923bd3c86955199030836d1d1561fa1/cpp/src/groupby/sort/sort_helper.cu#L294-L299

However, the steps of materializing the `key_sort_order` and performing the `gather` are completely redundant if the user has already specified that the inputs are already sorted. 

I haven't full thought through the solution, but my intuition is that `sort_groupby_helper` should short circuit when they keys are already sorted and just return a view to the input values.

**Comment by jrhemstad** [comment]
This impacts more than just `groupby::scan`. This optimization will improve any time `grouped_values` is called when the input keys are already sorted.

**Comment by revans2** [comment]
Not sure if this is still an issue or not, but I would love to have groupby::scan go faster for already sorted data. As this is a use case we commonly have in Spark.

**Comment by PointKernel** [comment]
Oops, I completely forgot about this issue. Will work on this shortly.

**Comment by PointKernel** [comment]
Still desired.
