### ISSUE TITLE
Rapids AI 0.19 CUDF : libarrow_cuda.so.100 not found

### ISSUE THREAD

**Issue by MordicusEtCubitus** [rapidsai/cudf#8526]
Dears,

First, thanks for cudf and dask-cudf : it is just hugely-great !

I've installed rapidsAI on redh7 using:
```
conda create -n rapids-0.19 -c rapidsai -c nvidia -c conda-forge   rapids=0.19 python=3.8 cudatoolkit=11.0
```
I can import cupy, numba, dask_cuda but cudf fails with this error
```
----> 4 from . import (
      5     avro,
      6     binaryop,

ImportError: libarrow_cuda.so.100: cannot open shared object file: No such file or directory
```

After a search indeed, I have libarrow for cpu, not gpu
```
$ conda upgrade arrow-cpp
Collecting package metadata (current_repodata.json): done
Solving environment: / 

Updating arrow-cpp is constricted by 

pyarrow -> requires arrow-cpp==1.0.1=py38ha12db41_37_cpu
```
Do you know how can I solve this ?

Thanks in advance

With kind regards,

Gaël

**Comment by quasiben** [comment]
I'm not sure why you picked up the old arrow version.  Can you try with the latest release:

> conda create -n rapids-21.06 -c rapidsai -c nvidia -c conda-forge  rapids=21.06 python=3.8 cudatoolkit=11.0

**Comment by MordicusEtCubitus** [comment]
Just because when I tried the 21.06 version the channel `rapidsai-nightly` was not mirrored where I did this and I did not thought I could try without `-nightly`. Sure I should have to.

Below is default config on rapids AI web site for 21.06 
```
conda create -n rapids-21.06 -c rapidsai-nightly -c nvidia -c conda-forge \
    rapids=21.06 python=3.8 cudatoolkit=11.0
```

I'm going to give it a try right now !

Thanks

**Comment by MordicusEtCubitus** [comment]
Sadly I have the same issue

```
---> 11 from cudf.core.column import ColumnBase
     12 from cudf.core.dataframe import DataFrame
     13 from cudf.core.frame import Frame

/path/conda/envs/rapids026/lib/python3.8/site-packages/cudf/core/column/__init__.py in <module>
      1 # Copyright (c) 2020-2021, NVIDIA CORPORATION.
      2 
----> 3 from cudf.core.column.categorical import CategoricalColumn
      4 from cudf.core.column.column import (
      5     ColumnBase,

/path/conda/envs/rapids026/lib/python3.8/site-packages/cudf/core/column/categorical.py in <module>
     23 
     24 import cudf
---> 25 from cudf import _lib as libcudf
     26 from cudf._lib.scalar import as_device_scalar
     27 from cudf._lib.transform import bools_to_mask

/path/conda/envs/rapids026/lib/python3.8/site-packages/cudf/_lib/__init__.py in <module>
      2 import numpy as np
      3 
----> 4 from . import (
      5     avro,
      6     binaryop,

ImportError: libarrow_cuda.so.100: cannot open shared object file: No such file or directory
```

**Comment by MordicusEtCubitus** [comment]
Anyway; my conda environment is always installed with an old arrow-cpp

```
$ pip freeze | grep arrow
pyarrow==1.0.1
```

Trying to update:
```
mamba install pyarrow==4.0.1
Encountered problems while solving:
  - package cudf-21.06.00-cuda_11.0_py38_gae440465c2_0 requires pyarrow >=1.0.1,<1.0.2.0a0, but none of the providers can be installed
```
But now I can update to arrow-cpp with cuda
```
mamba install pyarrow==1.0.1=py38hf66eee4_28_cuda
```

This looks a little barbarian, but cudf can now be imported.

Many thanks, will check if it works fine...

**Comment by quasiben** [comment]
Why is an old arrow-cpp version being installed ?

**Comment by MordicusEtCubitus** [comment]
I don't know, isn't it conda which does that ?
I have the same on my personal laptop

Mamba seems to explain that the cudf 2106 package wants it: 

mamba install pyarrow==4.0.1
Encountered problems while solving:
  - package cudf-21.06.00-cuda_11.0_py38_gae440465c2_0 requires pyarrow >=1.0.1,<1.0.2.0a0, but none of the providers can be installed

**Comment by beckernick** [comment]
> I have the same on my personal laptop
> mamba install pyarrow==4.0.1

cuDF currently requires pyarrow >=1.0.1,<1.0.2.0a0, which explains the incompatibility problem when you run this command .

> Why is an old arrow-cpp version being installed ?

Perhaps it is already there in the global environment and being picked up by conda, rather than being installed? Additionally, sometimes upgrading can get a bit thorny.

Could you verify that arrow and pyarrow are not present in your base environment, do a conda clean, and then try creating a fresh environment with the install command (avoiding pip)?

**Comment by beckernick** [comment]
I'm going to close this issue as answered as we were not able to reproduce it in clean environments and there has not been an update since June.

Please feel free to re-open this issue to continue the discussion.
