### ISSUE TITLE
AttributeError: 'Random' object has no attribute 'schoice'

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#8550]
```
Traceback (most recent call last):
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/cudf/tests/test_groupby.py", line 1825, in test_groupby_shift_row_mixed_fill
    t = rand_dataframe(
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/cudf/tests/dataset_generator.py", line 462, in rand_dataframe
    df = get_dataframe(
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/cudf/tests/dataset_generator.py", line 219, in get_dataframe
    column_params.generator = column_params.generator()
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/cudf/tests/dataset_generator.py", line 411, in <lambda>
    generator=lambda cardinality=cardinality: [
  File "/opt/h2oai/dai/python/lib/python3.8/site-packages/cudf/tests/dataset_generator.py", line 412, in <listcomp>
    mimesis.random.random.schoice(
AttributeError: 'Random' object has no attribute 'schoice'
```

several tests fail like this.  Seems to be typo in schoice vs. choice.  0.19.2 had no issues, but 21.06 does.

**Comment by pseudotensor** [comment]
`mimesis.random.random.schoice` appears twice in that file.

**Comment by pseudotensor** [comment]
Still there in master: https://github.com/rapidsai/cudf/blob/branch-21.08/python/cudf/cudf/tests/dataset_generator.py#L412 (one of them)

**Comment by dantegd** [comment]
I don’t think it is a typo, just the fact that `mimesis` [4.1.0](https://github.com/lk-geimfari/mimesis/blob/a7e05d1e3713981a7264c5932cc29272a036b391/CHANGELOG.rst#version-410) had this change:

```
Renamed Random.schoice to Random.generate_string
```

**Comment by beckernick** [comment]
I don't believe that mimesis is one of our runtime dependencies, but it is unpinned and installing from conda-forge in our development environment: https://github.com/rapidsai/cudf/blob/5b8895dc50a5daf99bafede67617e8ebd39d3af6/conda/environments/cudf_dev_cuda11.2.yml#L56

In conda-forge, [mimesis](https://anaconda.org/conda-forge/mimesis) is at version 4.0.0, which is likely why this has not previously come up. In the short term, would you be able to install from conda-forge and/or use mimesis <4.1 @pseudotensor ?

Beyond that, mimesis on conda-forge will likely eventually be updated. Perhaps we should add an environment constraint (either <4.1 or >=4.1) and update to `generate_string` (depending on the constraint selected). What do you think @shwina ?

**Comment by shwina** [comment]
We probably want to add the former constraint, and then the latter when 4.1+ becomes available. It looks like mimesis hasn't seen activity on conda-forge for a while unfortunately: https://github.com/conda-forge/mimesis-feedstock/pulls

**Comment by beckernick** [comment]
Sounds good. I'll file a separate issue and cross-link

**Comment by beckernick** [comment]
Going to close this issue as it is now covered by #8551 . Please feel free to re-open if relevant.
