### ISSUE TITLE
I was really surprised...

### ISSUE THREAD

**Issue by MickeyDragon** [rapidsai/cudf#8552]
I couldn't find any installation tutorials for c++....

I can't quite find it.....

I searched for almost 2 hours and 3 hours, but it was still the same...

Can you give me the link to the tutorial?.....

please...

**Comment by beckernick** [comment]
We've just added an example of building a custom application with libcuDF [here](https://github.com/rapidsai/cudf/tree/branch-21.08/cpp/examples). It goes through a basic example of reading a CSV file , doing a groupby aggregation, and writing the result to a CSV. Let us know if you have any feedback.

I'm going to close this issue as answered, but please feel free to re-open.
