### ISSUE TITLE
[FEA] Support multi-character newline delimiters with a read_text API

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#8557]
There are many semi-structured text file formats which require domain specific parsing logic to load into a DataFrame before analysis can be performed. For example, in genomics there are [FASTA](https://en.wikipedia.org/wiki/FASTA_format) and [VCF](https://en.wikipedia.org/wiki/Variant_Call_Format) formats, each with various Python libraries that ease parsing into Pandas DataFrames.

In cuDF, we have quite a few string functions we can use to implement custom parsing logic for text formats, but there's an initial difficulty in loading the raw text into rows in a DataFrame. It's possible to use read_csv with a newline delimiter, but that's limited to a single character, and there's significant overhead using read_csv when the files aren't actually CSVs.

It would be useful to have a `read_text` API which loads text into rows, but supports splitting records on a multi-character delimiter.

Borrowing from the FASTA file example, something like `cudf.read_text('fasta.example', delim='*\n')` would result in a single string column with 3 records.
```
;LCBO - Prolactin precursor - Bovine
; a sample sequence in FASTA format
MDSKGSSQKGSRLLLLLVVSNLLLCQGVVSTPVCPNGPGNCQVSLRDLFDRAVMVSHYIHDLSS
EMFNEFDKRYAQGKGFITMALNSCHTSSLPTPEDKEQAQQTHHEVLMSLILGLLRSWNDPLYHL
VTEVRGMKGAPDAILSRAIEIEEENKRLLEGMEMIFGQVIPGAKETEPYPVWSGLPSLQTKDED
ARYSAFYNLLHCLRRDSSKIDTYLKLLNCRIIYNNNC*

>MCHU - Calmodulin - Human, rabbit, bovine, rat, and chicken
MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA
DIDGDGQVNYEEFVQMMTAK*

>gi|5524211|gb|AAD44166.1| cytochrome b [Elephas maximus maximus]
LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGTNLV
EWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFHPYYTIKDFLG
LLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLALFLSIVIL
GLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGX
IENY
```

It's possible to do this parsing on the CPU and construct a cudf.DataFrame from objects in host memory, but that also has performance penalties.

**Comment by randerzander** [comment]
cc @elstehle, @davidwendt

**Comment by cwharris** [comment]
How large are the files we'd expect to see with these file formats?

**Comment by randerzander** [comment]
> How large are the files we'd expect to see with these file formats?

"It depends" :) Genomes are a few GB raw, and can compress pretty well.. down to a few MB. But I'd say a great many analyses call for work across multiple files, so you can get large quickly.

This implies the need for:
a. Compression support
b. Reading lists of multiple files into a single DataFrame like we can do with existing readers

cc @VibhuJawa

**Comment by elstehle** [comment]
> Update:
> 
> With #8702 merged in, I believe we now need Python bindings

@jdye64 is working on a PR for those in https://github.com/rapidsai/cudf/pull/8998

**Comment by jdye64** [comment]
> > Update:
> > With #8702 merged in, I believe we now need Python bindings
> 
> @jdye64 is working on a PR for those in #8998

Yes, I will update those bindings right now actually, if they need it, and then change the PR from WIP to ready for review. I know a few things such as multiple inputs need to be removed from the bindings as @cwharris made some modifications where multiple inputs are forbidden so need to change that.
