### ISSUE TITLE
[BUG] update to dask/distributed 2021.6.1 to prevent hangs

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#8562]
https://github.com/dask/distributed/issues/4926

rapids 21.06 hangs in xgboost: https://github.com/dmlc/xgboost/issues/7032
rapids 21.08 is still on 2021.6.0.

I can't try 2021.6.1 until rapids is updated.  I encountered errors when trying 2021.6.1 with 21.06, even before any compatibility check.

Many hangs in dask related things have been happening since rapids 19, so hoping dask/distributed has figured it out now.

**Comment by pseudotensor** [comment]
No response here.  Dask xgboost hangs all the time @trivialfis even in single node.  distributed/dask update may help, would hope cudf team doesn't miss this update.

**Comment by trivialfis** [comment]
For testing latest packages you can try rapids nightly (which is what we are doing on XGBoost's CI), at least we know whether it's fixed in nightly. ;-)

See this docker file and conda command: https://github.com/dmlc/xgboost/blob/1c8fdf2218eed2bd90d069aa85eb1ab0865d3532/tests/ci_build/Dockerfile.gpu#L21

**Comment by pseudotensor** [comment]
> For testing latest packages you can try rapids nightly (which is what we are doing on XGBoost's CI), at least we know whether it's fixed in nightly. ;-)
> 
> See this docker file and conda command: https://github.com/dmlc/xgboost/blob/1c8fdf2218eed2bd90d069aa85eb1ab0865d3532/tests/ci_build/Dockerfile.gpu#L21
> 
> Aside from that, I think we might be missing some configurations for testing. It would be great if I can reproduce your issue so I can add some automated tests in the future.

I cannot use latest rapids with new dask, it fails with various errors as I mentioned.  cudf needs to be updated to work with new dask/distributed.

**Comment by trivialfis** [comment]
Can you try nightly?  They are both on development branch.

**Comment by quasiben** [comment]
cudf and dask-cudf CI are regularly tested against latest in dask/distributed.   Are you referring to nightlies or released versions ?  In the other dask/distributed issues you filed it I thought you were using released versions

**Comment by pseudotensor** [comment]
Thanks, I see now 21.08 does allow dask/distributed 2021.6.2 so will try that.  I guess 21.08 is still in middle of development so could be in broken state, however.

**Comment by galipremsagar** [comment]
@pseudotensor cudf `21.08` is a nightly version and is not in a broken state, it is available for use.

**Comment by beckernick** [comment]
By default, the 21.10 nightly ships with dask and distributed 2021.9.0. Closing.
