### ISSUE TITLE
[QST] error: could not find git for clone of jitify-populate

### ISSUE THREAD

**Issue by MickeyDragon** [rapidsai/cudf#8563]
**What is your question?**
I am building the project with the command below.
`sudo bash ./build.sh --ptds`
Below is the order in which I solved the error....
The last jitify-populate error could not be resolved...
### first error
Building for the architecture of the GPU in the system...
-- The CUDA compiler identification is NVIDIA 11.2.67
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CUDF: Auto detection of gpu-archs: 61
-- CUDF: Building CUDF for GPU architectures: 61-real
CMake Error at /snap/cmake/882/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /snap/cmake/882/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /snap/cmake/882/share/cmake-3.20/Modules/FindZLIB.cmake:120 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:121 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/rmfkdehd/cudf-branch-21.08/cpp/build/CMakeFiles/CMakeOutput.log".
See also "/home/rmfkdehd/cudf-branch-21.08/cpp/build/CMakeFiles/CMakeError.log".
### solution
sudo apt-get install zlib1g-dev
### Second Error
Building for the architecture of the GPU in the system...
-- CUDF: Auto detection of gpu-archs: 61
-- CUDF: Building CUDF for GPU architectures: 61-real
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- CPM: adding package jitify@2.0.0 (cudf_0.19)
CMake Error at /snap/cmake/882/share/cmake-3.20/Modules/ExternalProject.cmake:2633 (message):
  error: could not find git for clone of jitify-populate
Call Stack (most recent call first):
  /snap/cmake/882/share/cmake-3.20/Modules/ExternalProject.cmake:3683 (_ep_add_download_command)
  CMakeLists.txt:22 (ExternalProject_Add)

-- Configuring incomplete, errors occurred!
See also "/home/rmfkdehd/cudf-branch-21.08/cpp/build/_deps/jitify-subbuild/CMakeFiles/CMakeOutput.log".

CMake Error at /snap/cmake/882/share/cmake-3.20/Modules/FetchContent.cmake:1000 (message):
  CMake step for jitify failed: 1
Call Stack (most recent call first):
  /snap/cmake/882/share/cmake-3.20/Modules/FetchContent.cmake:1141:EVAL:2 (__FetchContent_directPopulate)
  /snap/cmake/882/share/cmake-3.20/Modules/FetchContent.cmake:1141 (cmake_language)
  build/cmake/CPM_7644c3a40fc7889f8dee53ce21e85dc390b883dc.cmake:753 (FetchContent_Populate)
  build/cmake/CPM_7644c3a40fc7889f8dee53ce21e85dc390b883dc.cmake:581 (cpm_fetch_package)
  build/cmake/CPM_7644c3a40fc7889f8dee53ce21e85dc390b883dc.cmake:258 (CPMAddPackage)
  cmake/thirdparty/CUDF_GetJitify.cmake:20 (CPMFindPackage)
  cmake/thirdparty/CUDF_GetJitify.cmake:29 (find_and_configure_jitify)
  CMakeLists.txt:127 (include)
How To Fix jitify-populate Errors?......

**Comment by harrism** [comment]
Do you have `git` installed?

**Comment by vyasr** [comment]
I'm going to close this for now as likely caused by either a bad connection or broken git installation, but please reopen if needed.
