### ISSUE TITLE
[BUG] Strange code logic in `ColumnBase._fill`

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#8566]
I came across this during the categorical column refactor:
https://github.com/rapidsai/cudf/blob/1de662fb6cf41ef402096dd68e1bb7c50ab4baa4/python/cudf/cudf/core/column/column.py#L345-L380

Seems strange that `self` is returned in the middle.

**Comment by beckernick** [comment]
Nice find. Perhaps this could have been caused by a merge conflict resolution that removed an older implementation?
