### ISSUE TITLE
[FEA] Proposal to deprecate Python 3.7 in 21.08, drop in 21.10

### ISSUE THREAD

**Issue by raydouglass** [rapidsai/cudf#8590]
Just want to start a discussion about deprecating Python 3.7 for 21.08 and drop it completely in 21.10.

In addition, add Python 3.9 support in either 21.08 or 21.10 depending on available resources.

Please review the [release schedule](https://docs.rapids.ai/maintainers) for 21.08 and 21.10 schedules.

**Comment by harrism** [comment]
@raydouglass, since issues can't be assigned to codeowner groups, I recommend opening a PR that implements the deprecation, and assigning it to cudf-python-codeowners.  I don't know enough about the relative popularity of Python versions to comment.

**Comment by vyasr** [comment]
I have no knowledge of what discussions have gone into making these decisions in the past, but FWIW [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) is a good guideline that the community is (slowly) moving towards adopting, so we could do the same. There is some discussion on what dask will do on dask/community#66, so we may be constrained by them, but some of the largest components of the SciPy stack (scipy, scikit-learn, etc) are now following NEP 29. numpy is lagging a bit behind (~6 months as of the Python 3.6 drop), but considering that almost the entire remaining ecosystem relies on them that seems like a reasonable way to allow other release cycles to reach an appropriate release version before numpy pulls the rug out from under them. We don't have a comparable constraint.

**Comment by bdice** [comment]
https://docs.rapids.ai/notices/rsn0014/ This can be closed.
