### ISSUE TITLE
[BUG] `title` function documentation does not match implemenation

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8596]
**Describe the bug**
The [libcudf strings `title()` documentation](https://github.com/rapidsai/cudf/blob/branch-21.08/cpp/include/cudf/strings/capitalize.hpp#L52-L54) states that the first character after each occurrence of spaces is capitalized, but the [implementation is capitalizing after non-alphabetic characters](https://github.com/rapidsai/cudf/blob/branch-21.08/cpp/src/strings/capitalize.cu#L101-L106) instead.

**Steps/Code to reproduce bug**
Call `title()` on a string column that contains the string "n2VIDIA".  The expected output is "N2vidia" but instead the result is "N2Vidia".

**Expected behavior**
`title()` should capitalize after whitespace rather than any non-alphabetic character.  If the current behavior of `title()` is considered correct then the documentation needs to be updated and there needs to be a mechanism that can capitalize only after whitespace.

**Comment by davidwendt** [comment]
This is designed after the Pandas str.title() function.
```
>>> import pandas as pd
>>> s = pd.Series(["n2vidia"])
>>> s.str.title()
0    N2Vidia

```
So it looks like the documentation is incorrect.

**Comment by jlowe** [comment]
Thanks @davidwendt I updated the summary accordingly so this tracks fixing the documentation.  I'll file a separate feature request for a way to capitalize only after whitespace which is what we need for Spark.

**Comment by jlowe** [comment]
Filed #8597 to track the new behavior we need for emulating Spark's `initcap` behavior.
