### ISSUE TITLE
[FEA] Ability to capitalize first letter of words separated by a space in a string

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8597]
**Is your feature request related to a problem? Please describe.**
Spark's `initcap` feature capitalizes the first letter of each word, where words are strings of characters separated by a space character.  The existing `title()` behavior is close, but it defines words as alphabetic sequences separated by non-alphabetic characters, and as such will capitalize something like "n2vidia" to "N2Vidia" instead of "N2vidia".

**Describe the solution you'd like**
`title()` could be overloaded with a new enum parameter that allows more control over what characters are considered word separators.  One value could be non-alphabetic characters which matches the existing behavior, another could be a space character (i.e.: `' '`) to match what is needed by Spark, and this could be extended to others in the future if necessary.

**Describe alternatives you've considered**
A completely new name could be used for the needed method, but this could lead to confusion with the existing `title()` method.

**Comment by davidwendt** [comment]
Closed by #8602

**Comment by jlowe** [comment]
@davidwendt does #8602 allow conversion only on the literal space character (i.e.: `' '`) or any whitespace character?  The issue description above calls for the former, but it looks like #8602 only supports the latter.

Should Spark capitalize solely based on one specific type of whitespace instead of any type of whitespace?  Probably not, but unfortunately we need to emulate what it does.

**Comment by jlowe** [comment]
That sample data works well to demonstrate.  `abc\tdef\nghi jkl` would be capitalized to `Abc\tdef\nghi Jkl`.  Here's the same example in the Spark shell:
```
scala> sql("select initcap('abc\tdef\nghi jkl')").collect
res0: Array[org.apache.spark.sql.Row] =
Array([Abc	def
ghi Jkl])
```

This behavior arises because [the code implementing this in Spark](https://github.com/apache/spark/blob/master/common/unsafe/src/main/java/org/apache/spark/unsafe/types/UTF8String.java#L491) is checking for the space character rather than any whitespace character.

**Comment by davidwendt** [comment]
This is certainly strange. The original `title()` code did not support this. The #8602 only added the ability to treat alphanumerics the same as alphabetics which Pandas supports. Sounds like this needs a different API with different behavior specific to Spark..
Looking at some other languages and implementations, I see one example that passes a delimiter character to `capitalize` that may work for this.
