### ISSUE TITLE
[BUG]prefixsum floating array is not correct

### ISSUE THREAD

**Issue by yidong-nvidia** [rapidsai/cudf#860]
To reproduce it
```
import cudf
import numpy as np
df = cudf.DataFrame()
df['input'] = np.array([1.0, 2.0, 3.0])
output = cudf.utils.cudautils.prefixsum(df['input'].data.to_gpu_array())
print(cudf.Series(output).to_array())

df['input'] = np.array([1, 2, 3])
output = cudf.utils.cudautils.prefixsum(df['input'].data.to_gpu_array())
print(cudf.Series(output).to_array())
```
It works for the integer array but not the floating array.

**Comment by jrhemstad** [comment]
@yidong-nvidia can you include the results from your reproducer?

**Comment by yidong-nvidia** [comment]
I am running in under python3.6 and cudf5.0. This is what I have in a Ubuntu VDI machine at NVIDIA.
```
[0. 0. 0. 0.]
[0 1 3 6]
```

**Comment by kkraus14** [comment]
Note our prefixsum also always puts a 0 as the first element while Pandas does not, should be an easy fix from the python side.

**Comment by jrhemstad** [comment]
> Note our prefixsum also always puts a 0 as the first element while Pandas does not, should be an easy fix from the python side.

This shouldn't be the case. That should only happen if it's an _exclusive_ sum scan. This can be controlled via the `inclusive` flag in our libcudf API https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/scan.cu#L66

**Comment by kkraus14** [comment]
> > Note our prefixsum also always puts a 0 as the first element while Pandas does not, should be an easy fix from the python side.
> 
> This shouldn't be the case. That should only happen if it's an _exclusive_ sum scan. This can be controlled via the `inclusive` flag in our libcudf API https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/scan.cu#L66
> 
> Granted, this function sorely needs to be updated to support other types.

On the python side we put a 0 as the first element and then feed libcudf a pointer to the second element and the size - 1 😅

**Comment by jrhemstad** [comment]
> > > Note our prefixsum also always puts a 0 as the first element while Pandas does not, should be an easy fix from the python side.
> > 
> > 
> > This shouldn't be the case. That should only happen if it's an _exclusive_ sum scan. This can be controlled via the `inclusive` flag in our libcudf API https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/scan.cu#L66
> > Granted, this function sorely needs to be updated to support other types.
> 
> On the python side we put a 0 as the first element and then feed libcudf a pointer to the second element and the size - 1

Good lord, reading that gave me an aneurysm. 

I assume now that we're clear on the API it will be corrected to work normally?

**Comment by kkraus14** [comment]
> > > > Note our prefixsum also always puts a 0 as the first element while Pandas does not, should be an easy fix from the python side.
> > > 
> > > 
> > > This shouldn't be the case. That should only happen if it's an _exclusive_ sum scan. This can be controlled via the `inclusive` flag in our libcudf API https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/scan.cu#L66
> > > Granted, this function sorely needs to be updated to support other types.
> > 
> > 
> > On the python side we put a 0 as the first element and then feed libcudf a pointer to the second element and the size - 1
> 
> Good lord, reading that gave me an aneurysm.
> 
> I assume now that we're clear on the API it will be corrected to work normally?

Yea, I'll make a github issue as well since I'm sure there will need to be conversations surrounding null behaviors 😄

**Comment by kkraus14** [comment]
Issue created here: https://github.com/rapidsai/cudf/issues/936
