### ISSUE TITLE
[FEA] Deprecate `ser.str.subword_tokenize` API in favor of cudf.core.subword_tokenizer.SubwordTokenizer

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#8604]
**Is your feature request related to a problem? Please describe.**
Now that we have added cudf.core.subword_tokenizer.SubwordTokenizer with [PR](https://github.com/rapidsai/cudf/pull/7942). We should deprecate the `ser.str.subword_tokenize` API in favor of it in the future release. 

Reasons to switch to this API are: 

1.  Equivalent to `HuggingFace` so makes switching easier
2.  Faster (13x+ at smaller batch sizes)
3.  Fixes discrepancies in parameters like `stride` etc. that can cause difficult bugs to find. 

**Additional context**
Have added [PR](https://github.com/rapidsai/cudf/pull/8603) to provide warnings for users  

Also have added a PR to clx to use the new tokenizer. (https://github.com/rapidsai/clx/pull/430 )

**Comment by vyasr** [comment]
@VibhuJawa can we close this issue after #8603?

**Comment by VibhuJawa** [comment]
> @VibhuJawa can we close this issue after #8603?

Nope, we still need to depreciate it.  I just added that warning last release so that users have a 2 release window to fix it . Will depreciate next release.
