### ISSUE TITLE
[FEA] Deprecate label_encoding method in favor of categorical columns

### ISSUE THREAD

**Issue by lastephey** [rapidsai/cudf#8608]
Dear cuDF developers,

**Is your feature request related to a problem? Please describe.**

My feature request is for cuDF to add the ability for the `label_encoding` function to encode string data. My specific use-case is to encode string values as ints.

**Describe the solution you'd like**

I would like to use the `label_encoding` function to encode some values that are currently strings as ints. My larger goal is to use these data in CuPy's [histogram2d](https://docs.cupy.dev/en/stable/reference/generated/cupy.histogram2d.html?highlight=histogram2d), but since CuPy does not yet support string arrays, I was hoping that label encoding would help me get around this problem.

**Describe alternatives you've considered**

I have also tried the cuDF `replace` function for this, but it looks like it doesn't support encoding strings as ints either:

```
to_replace and value should be of same types,got to_replace dtype: object and value dtype: int64
```

I'd be equally happy with `replace` supporting the ability to replace objects of different types.

**Additional context**

If there are better ways to accomplish this task, I would be grateful for your suggestions. 

Thank you very much,
Laurie

**Comment by davidwendt** [comment]
What does the string data look like? You may be able to use the [subword_tokenize](https://docs.rapids.ai/api/cudf/stable/api.html#subwordtokenizer) function to assign integers to words.

If you want to replace an entire string row with an integer you could use `replace` with strings that contain integers and then cast that result to `int64`
```
>>> import cudf
>>> s = cudf.Series(['a','b','a','c'])
>>> s.str.replace(['a','b','c'],['1','2','3'], regex=False).astype('int64')
0    1
1    2
2    1
3    3
dtype: int64

```

**Comment by beckernick** [comment]
In addition to @davidwendt , you could do this in a couple of other ways to avoid enumerating your categories (the former probably being preferred method in pandas):

```python
import cudf
​
s = cudf.Series(["a","b","c"])
s.astype("category").cat.codes
0    0
1    1
2    2
dtype: uint8
```

```python
import cudf
from cuml.preprocessing import LabelEncoder
​
s = cudf.Series(["a","b","c"])
​
le = LabelEncoder()
le.fit(s)
le.transform(s)
0    0
1    1
2    2
dtype: uint8
```

cc @shwina perhaps we should consider deprecating `label_encode` as the core functionality is generally covered by categorical columns and cuML's `LabelEncoder`. From the [git blame](https://github.com/rapidsai/cudf/blame/bbf375b081d7d0fa6ddd9385383b023140cdbb0d/python/cudf/cudf/core/series.py#L3777) it's from the early pyGDF days years ago. I don't think this method is supported in pandas.

**Comment by lastephey** [comment]
Thank you @davidwendt and @beckernick for your suggestions. I think they all sound like they will do what I need. The strings I need to replace are all values in a single column. 

I haven't had time to try these out yet but I just wanted to say thank you and that I really appreciate your quick answers and advice.

**Comment by lastephey** [comment]
Ok, I've had some time to read about and test the options you suggested. 

1. `subword_tokenize` would definitely work for what I need to do, but there's some overhead to set this up.
2. Using `replace` as @davidwendt suggested works well, but it does result in this warning for me using cuDF `21.08.00a`: 
```
/opt/miniconda3/lib/python3.8/site-packages/cudf/core/column/string.py:945: UserWarning: `n` parameter is not supported when `pat` and `repl` are list-like inputs
  warnings.warn(
```
3. Using categorial data is the simplest and my favorite. I didn't even know about this functionality within Pandas, so thank you very much for the pointer.
4. the cuML solution also seems fine, although in my case I'm not using cuML so I don't want to add this extra dependency unless I have to. 

Thank you both again for your help and suggestions. I really appreciate it. My question is resolved. Should I close this, or would you like me to keep it open for issue tracking?

**Comment by beckernick** [comment]
Glad this is resolved. Let's keep this open and edit the title to be a discussion around deprecating `label_encoding`.

**Comment by vyasr** [comment]
This was done in #9535 and #9289
