### ISSUE TITLE
[FEA] Refactor aggregations to accommodate for distributed computing

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#8610]
Currently, the aggregations in cudf are designed to perform computation only in a single node. Distributed aggregations require some changes from them. Take Spark for example, it requires 3 steps:
 * `update` step: computes local aggregations on partitioned datasets, producing partial results
 * `merge` step: merges the partial results, which in turn may produce a final result, or just produce new partial results
 * `finalize` step: to compute the final result after merging

The `finalize` step is not always be required, as the `merge` step can do its job.

In order to use cudf aggregations in distributed computing, our current solution is to add more aggregations, such as the recently added `MERGE_LISTS`, `MERGE_SETS`, and the upcoming `MERGE_VARIANCES`, `MERGE_STDS` etc. For `VARIANCE` and `STD` aggregation, we potentially need to add `FINALIZE_VARIANCES`, `FINALIZE_STDS` as well. Otherwise, we will have to combine the finalize step into the merge step for these aggregations, which will have to produce the final results at every merging. This is a waste of computation, as such final results will be discarded if a merging is not a "final" merge. In addition, keep adding `MERGE_*` aggregations that are just for merging the results of existing aggregations is not a good design.

## Solution
A solution for our problem is to refactor (groupby) aggregations to expose 3 public APIs: `compute`, `merge`, `finalize` (or any other better names) that support the necessary steps in distributed computing. The `compute` step will do the same job as currently implemented for single-node computation. By default, the `merge` and `finalize` steps will throw `unimplemented exception` until they are implemented for specific aggregations.

Any better solution is welcomed.

**Comment by jrhemstad** [comment]
> Currently, the aggregations in cudf are designed to perform computation only in a single node. Distributed aggregations require some changes from them.

This isn't true. We've provided the necessary components to support distributed groupby aggregations in both Dask and Blazing for years with the current design.

**Comment by revans2** [comment]
I personally don't think we need this.  In Spark update and merge are both just group by aggregations.  Finalize is a project like operation that does not need anything special from cudf to do.

**Comment by ttnghia** [comment]
@revans2 Then why can't we just do exactly the same as Dask/Blazing for Spark?

**Comment by revans2** [comment]
@ttnghia we are doing the same thing as them.

**Comment by ttnghia** [comment]
Thanks all.

**Comment by revans2** [comment]
For just about everything. They don't support collect_list or collect_set, so this is new for everyone.  I don't know 100% what is happening with standard deviation or variance. I took a quick look at dask, but I am not a python expert so I don't know for sure what is happening there. I see that blazing does support it, so I would need to read through their code to see how they are doing it.
