### ISSUE TITLE
[BUG] CSV parsing throws when filtering columns using data_types API

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8613]
**Describe the bug**
The way to set the data types expect when parsing CSV is changing. The old API which is deprecated took a string to indicate how to parse it.  The new API takes a data_type.  However when I tried to switch the java API over to use this new API I started to get exceptions and even a seg fault in one case.

**Steps/Code to reproduce bug**
Apply the attached patch and run the CSV tests.

[tests.patch.gz](https://github.com/rapidsai/cudf/files/6718776/tests.patch.gz)

**Expected behavior**
The tests pass, or at least don't crash in scary ways. It is not clear from the docs if the semantics of the API also changed or not, but if they did and I am passing in the wrong things a descriptive error message would be a lot better.

**Comment by revans2** [comment]
This appears to only happen when only some of the columns are being read, and others are filtered out.

**Comment by revans2** [comment]
I upmerged my original patch and it looks like this may have already been fixed.  I will run through a full set of tests to verify it though.

**Comment by vuule** [comment]
I did fix a few bugs in the original implementation, so hopefully that's it.

**Comment by revans2** [comment]
Yup all of my tests passed so I am just going to close this
