### ISSUE TITLE
[FEA] Use MyST for cudf markdown docs

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#8636]
Currently, cudf python rely on [recommonmark](https://github.com/readthedocs/recommonmark) to bridge markdown docs. However, this extension is deprecated. The suggested replacement is [MyST](https://github.com/executablebooks/MyST-Parser) parser.

**Comment by vyasr** [comment]
Spoke with @shwina and @isVoid, and our plan is to instead standardize on a single file format. Since the majority of our existing docs are rst, we'll be converting the outstanding Markdown files into rst.
