### ISSUE TITLE
[BUG] Shared-memory from_arrow no longer zero-copy

### ISSUE THREAD

**Issue by bryevdv** [rapidsai/cudf#8639]
cc @trxcllnt @galipremsagar 

Looking into implementing zero-copy `from_arrow` for node-rapids for Arrow arrays stored in IPC format in shared memory, we noticed that Python cudf [`from_arrow`](https://github.com/rapidsai/cudf/blob/branch-21.08/python/cudf/cudf/core/column/column.py#L222) delegates to `libcudf.interop.from_arrow` which will always result in a copy. Evidently previously it was possible to avoid a copy when and arrow table had been created via ` GpuArrowReader` from GPU memory.

**Comment by beckernick** [comment]
@bryevdv it looks like we've been delegating to `from_arrow` for quite a while based on the [git blame history](https://github.com/rapidsai/cudf/blame/7ad07b49e73ddbaca32e16cf491953a5e98b79bf/python/cudf/cudf/core/column/column.py#L433). Is this a recent change in behavior?

**Comment by trxcllnt** [comment]
@beckernick no, the change happened when we switched Python to using `libcudf.from_arrow`. Previously all the [`from_arrow` logic was handled in Python](https://github.com/rapidsai/cudf/blob/b164b382b9b778d3eccf643e533b30afe955ddab/python/cudf/cudf/core/column/column.py#L1106-L1108), and we zero-copy moved the Arrow buffers into cuDF buffers [via `buffers_from_pyarrow`](https://github.com/rapidsai/cudf/blob/b164b382b9b778d3eccf643e533b30afe955ddab/python/cudf/cudf/utils/utils.py#L110-L173).

**Comment by bryevdv** [comment]
Still needs to be addressed, AFAIK.

**Comment by shwina** [comment]
Is it not possible for C++ to also zero copy similarly where applicable? The reason we moved to the C++ impl was to avoid duplicates logic between C++ and Python.

**Comment by trxcllnt** [comment]
@shwina yeah it would be possible, but the current implementation returns a `unique_ptr<cudf::table>`, meaning it must copy the input data so the return can be a valid owning type. For true zero-copy, we'd need a version that returns a `cudf::table_view` (from which a `cudf::table` could be constructed if a copy was desired).

**Comment by shwina** [comment]
cc @jrhemstad for advice on the API here, but maybe we could return something like a `pair<table_view, memory_owner>`? In the IPC case, the `memory_owner` would own nothing?

**Comment by vyasr** [comment]
I think the new solutions to this issue will come from work on https://github.com/rapidsai/cudf/issues/14926.

**Comment by vyasr** [comment]
With the closing of #14926 this is resolved. We now use the C Data Interface for all Arrow interop, so no extraneous copies will be made.
