### ISSUE TITLE
[BUG] Dask-cuDF Series groupby aggregation returns DataFrame

### ISSUE THREAD

**Issue by rjzamora** [rapidsai/cudf#8655]
**Describe the bug**
Dask-cuDF is currently returning a single-column `cudf.core.dataframe.DataFrame` object for cases that *should* be returning a `Series`. 

**Steps/Code to reproduce bug**
```python
import pandas as pd
import numpy as np
import cudf
import dask_cudf
import dask.dataframe as dd

df = pd.DataFrame(
    {
        "x": np.random.randint(0, 5, size=10000),
        "y": np.random.normal(size=10000),
    }
)
ddf = dd.from_pandas(df, npartitions=1)
gddf = dask_cudf.from_cudf(cudf.from_pandas(df), npartitions=1)

print(type(ddf.groupby("x").y.agg("max").compute()))
print(type(gddf.groupby("x").y.agg("max").compute()))
```

**Result**:
```
<class 'pandas.core.series.Series'>
<class 'cudf.core.dataframe.DataFrame'>
```

**Expected behavior**
I would expect this output to be:
```
<class 'pandas.core.series.Series'>
<class 'cudf.core.series.Series'>
```

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda

**Additional Context**
This bug is discussed in #8045, but should probably be addressed separately (cc @charlesbluca ).

**Comment by charlesbluca** [comment]
Digging into this, it looks like maybe we would want to replicate the post processing steps Dask is performing on a series groupby here?

- https://github.com/dask/dask/blob/8601b540f8e7eac95fa739a5ca28f1d707299ed0/dask/dataframe/groupby.py#L1917-L1921
