### ISSUE TITLE
[BUG] Empty `columns` is not returning empty dataframe in `read_parquet`

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/cudf#8668]
**Describe the bug**
`columns` is used to select what columns to be read from parquet file. When `columns` is `None`, all columns are read. When `columns` is `[]`, no columns should be read, but in `cudf` all `[]` and `None` have the same behavior.

**Steps/Code to reproduce bug**
```python
>>> import cudf
>>> df = cudf.DataFrame({'a':[1, 2, 3], 'b':[4, 5, 6]})
>>> df.to_parquet('a')
>>> import pandas as pd
>>> pd.read_parquet('a')
   a  b
0  1  4
1  2  5
2  3  6
>>> pd.read_parquet('a', columns=None)
   a  b
0  1  4
1  2  5
2  3  6
>>> pd.read_parquet('a', columns=[])
Empty DataFrame
Columns: []
Index: []
>>> cudf.read_parquet('a', columns=None)
   a  b
0  1  4
1  2  5
2  3  6
>>> cudf.read_parquet('a', columns=[])
   a  b
0  1  4
1  2  5
2  3  6
```
**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: from source

**Comment by galipremsagar** [comment]
@devavret @vuule This behavior seems to be because of a design choice in `libcudf` layer: https://github.com/rapidsai/cudf/blob/8aaf8e656de3a3269b78d5e0be012f2f9da48fa8/cpp/include/cudf/io/parquet.hpp#L53-L54

Is this for the sake of spark? If so, we can handle this special case in python/cython layer.

**Comment by devavret** [comment]
This is probably because a table is not available during the construction of this input args object. And we don't want the user to have to know what the file contains before we read it for them. We can make it std::optional now so that by default it asks for all columns to be read and we don't have to use the special case of _columns = [] to signify the default case.

**Comment by vuule** [comment]
I fixed the issue with the interface for that passing an empty list results in a dataframe with no columns.
The dataframe still has 3 rows, while pandas returns a completely empty dataframe. Thus, the following test fails:
```
def test_parquet_empty_columns_param():
    buffer = BytesIO()
    df = cudf.DataFrame({"a": [1, 2, 3], "b": ["a", "b", "c"]})
    df.to_parquet(buffer)

    expected = pd.read_parquet(buffer, columns=[])
    got = cudf.read_parquet(buffer, columns=[])
    print(got)
    assert_eq(expected, got)
```
@galipremsagar do we want to fully match Pandas' behavior here?

**Comment by galipremsagar** [comment]
> I fixed the issue with the interface for that passing an empty list results in a dataframe with no columns. The dataframe still has 3 rows, while pandas returns a completely empty dataframe. Thus, the following test fails:
> 
> ```
> def test_parquet_empty_columns_param():
>     buffer = BytesIO()
>     df = cudf.DataFrame({"a": [1, 2, 3], "b": ["a", "b", "c"]})
>     df.to_parquet(buffer)
> 
>     expected = pd.read_parquet(buffer, columns=[])
>     got = cudf.read_parquet(buffer, columns=[])
>     print(got)
>     assert_eq(expected, got)
> ```
> 
> @galipremsagar do we want to fully match Pandas' behavior here?

Discussed offline and addressed in https://github.com/rapidsai/cudf/pull/11018#pullrequestreview-992662765
