### ISSUE TITLE
[QST] Is it possible to install with python 3.9.5?

### ISSUE THREAD

**Issue by fredguth** [rapidsai/cudf#8669]
**What is your question?**
Is there any version (even in beta) that works with python 3.9.5?

**Comment by quasiben** [comment]
We are working on adding 3.9 Python support -- is there something you specifically need in Python 3.9?  One thing you could try to unblock you while we continue working on 3.9 support is to [build from source](https://github.com/rapidsai/cudf/blob/branch-21.08/CONTRIBUTING.md#setting-up-your-build-environment).  Would this be an option for you ?

**Comment by fredguth** [comment]
Build from source is an option, yes. Thanks for the link.
The only reason to use 3.9 is that I am using a set of libs whose dependencies are a little complicated. My environment is working with 3.9.
