### ISSUE TITLE
[BUG] DataFrame setitem causing data corruption for cupy array inputs

### ISSUE THREAD

**Issue by esnvidia** [rapidsai/cudf#8672]
**Describe the bug**
Setting the values obtained from multiple columns of a StandardScaler to the GDF is not working (although this might be user error)

**Steps/Code to reproduce bug**
![image (1)](https://user-images.githubusercontent.com/80840697/124782664-657c9180-df12-11eb-8ed4-b6be2e02da90.png)
![image (2)](https://user-images.githubusercontent.com/80840697/124782697-6ca39f80-df12-11eb-85c0-6c5404b5b038.png)

Code is here
[Untitled.zip](https://github.com/rapidsai/cudf/files/6778220/Untitled.zip)

**Expected behavior**
Set the values to the GDF. All the columns have the same values in the GDF despite the output not showing it should be the case.
Looks like values are 

**Environment overview (please complete the following information)**
conda install rapids 21.06, bare-metal.

**Comment by beckernick** [comment]
The following is a minimal, reproducible example that demonstrates the underlying setitem issue causing data corruption. In this example, the first 10 values of the contiguous array are being set into the 10 rows for each column.

```python
import cudf
import cupy as cp
​
df = cudf.DataFrame({
    "a": range(10),
    "b": range(10),
})
arr = cp.arange(20,40).reshape(-1, 2)
df.loc[:, ["a","b"]] = arr
​
print(arr)
print(df)
[[20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]]
    a   b
0  20  20
1  21  21
2  22  22
3  23  23
4  24  24
5  25  25
6  26  26
7  27  27
8  28  28
9  29  29
```
