### ISSUE TITLE
[FEA] Support struct and list columns in element_equality_comparator

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#8683]
From `cpp/include/cudf/table/row_operators.cuh`, add functionality to `element_equality_comparator` and `row_equality_comparator` to compare struct and list elements. Currently they are quietly caught as non-`is_equality_comparable` types and return false representing unequal elements.

`row_equality_comparator` is used in #8652 for rank and dense rank scan aggregations. Both would benefit from this change.

**Comment by jrhemstad** [comment]
We have explored this at length and unfortunately this is not possible as it would require arbitrary recursion.

**Comment by rwlee** [comment]
Is there a reason to not support the simple cases of lists and structs? e.g. structs without lists or other structs as elements and lists that are not lists of lists or lists of structs.

**Comment by jrhemstad** [comment]
> structs without lists or other structs as elements and lists that are not lists of lists or lists of structs.

Yes, this case we can support by special casing the dispatch for struct and lists.
