### ISSUE TITLE
[BUG] cudf package not compatible with cuda 10 setup

### ISSUE THREAD

**Issue by henningpeters** [rapidsai/cudf#869]
**Describe the bug**
Installing and importing the `cudf` package on a CUDA 10 system results in following error:

```
(xxy) henning@instance-4:~$ python -c "import cudf"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/henning/xxy/lib/python3.6/site-packages/cudf/__init__.py", line 2, in <module>
    from cudf import dataframe
  File "/home/henning/xxy/lib/python3.6/site-packages/cudf/dataframe/__init__.py", line 1, in <module>
    from cudf.dataframe import (buffer, dataframe, series,
  File "/home/henning/xxy/lib/python3.6/site-packages/cudf/dataframe/buffer.py", line 3, in <module>
    from librmm_cffi import librmm as rmm
  File "/home/henning/xxy/lib/python3.6/site-packages/librmm_cffi/__init__.py", line 50, in <module>
    librmm_api = ffi.dlopen(_get_lib_name())
OSError: cannot load library '/home/henning/xxy/lib/python3.6/site-packages/librmm.so': libcudart.so.9.2: cannot open 
shared object file: No such file or directory
```

It's not clear to the user that the cudf package is tied to a specific CUDA version. The docs btw don't list the cudf package, but only cudf-cuda** packages.

**Steps/Code to reproduce bug**
```
pip install cudf
python -c "import cudf"
```

**Expected behavior**
Just an import

**Environment details (please complete the following information):**
 - Environment location: Cloud(GCP)
 - Method of cuDF install: pip
 
**Additional context**
Installed latest CUDA (10.0.130-1) and driver version (410.79)

**Comment by kkraus14** [comment]
You need to use `pip install cudf-cuda100`

**Comment by kkraus14** [comment]
Due to the nature of the compiled code underneath it's both difficult and troublesome to create a single install for multiple CUDA versions.

**Comment by kkraus14** [comment]
> Another option would be to fail gracefully

Agreed. I've created a feature request issue for this: https://github.com/rapidsai/cudf/issues/870. Did using `pip install cudf-cuda100` work for you?

**Comment by henningpeters** [comment]
Yep, see #839

**Comment by kkraus14** [comment]
Awesome, going to close this issue as I've created https://github.com/rapidsai/cudf/issues/870 to track better raising an error for this situation.
