### ISSUE TITLE
[FEA] Groupby correlation (Pearson)

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#8691]
I'd like to be able to calculate the correlation of my value columns on a per-group basis (groupby correlation). As an example, a data scientist might hypothesize that the sales or usage patterns of two products are more or less correlated on certain days of the week than others, which could be valuable information. To run that analysis, they'd like to do something like a groupby correlation where the key is the day of the week and the value columns are the sales (usage) patterns of each product.

As noted in https://github.com/rapidsai/cudf/issues/1267#issuecomment-876589573, supporting correlation (and implicitly covariance) in the groupby machinery might potentially require additional design. Unlike something like sum which operates on a single column, correlation operates on two columns so the aggregation takes more than one input. In Spark, the `corr` function takes two inputs and returns the per-group correlation of the input columns. In Pandas, `corr` will return the full pairwise correlation matrix using all columns in the dataframe.

Today, Spark only [supports](https://spark.apache.org/docs/latest/api/python/reference/api/pyspark.sql.DataFrame.corr.html) Pearson correlation, which is the [default in pandas](https://pandas.pydata.org/docs/reference/api/pandas.core.groupby.DataFrameGroupBy.corr.html) (though pandas supports additional methods).

Examples below.

Pandas:

```python
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import pandas as pd

df = pd.DataFrame({
    "key": [0]*4 + [1]*3,
    "a": [10,3,4,2,-3,9,10],
    "b": [10,23,-4,2,-3,9,19],
    "c": [10,-23,-4,21,-3,19,19],
})
​
print(df.groupby("key").corr())
              a         b         c
key                                
0   a  1.000000  0.077471  0.185581
    b  0.077471  1.000000 -0.604482
    c  0.185581 -0.604482  1.000000
1   a  1.000000  0.920285  0.997609
    b  0.920285  1.000000  0.891042
    c  0.997609  0.891042  1.000000
```

Spark:

```python
sdf = spark.createDataFrame(df)
sdf.createOrReplaceTempView("df")
​
sdf.groupby("key").agg(F.corr("a", "b")).show()  # could just as easily be Spark SQL
+---+------------------+
|key|        corr(a, b)|
+---+------------------+
|  0|0.0774711279979589|
|  1|0.9202846173114504|
+---+------------------+
```

**Comment by jrhemstad** [comment]
Like @beckernick mentioned, this may require some thinking on if/how the `groupby` C++ interface may need to change. Currently `groupby::aggregate` takes a list of `aggregation_request`s, which is just a column and a list of aggregations to perform on that column:

https://github.com/rapidsai/cudf/blob/a5427d2658b8e323b702a1f5e11a1512f2bab459/cpp/include/cudf/groupby.hpp#L58-L61

Correlation is unique in that it's not just operating on a single column, but instead two columns. 

Initial ideas:

- Make `aggregation_request` take multiple columns?
   - This just kind feels wrong. If a request allows multiple columns, there's no easy control over mapping an aggregation to the number of column it expects
- Make the column you're correlating _against_ an argument to the `pearson_correlation` aggregation. e.g., if we wanted to do a groupby pearson correlation of `col_a` with `col_b` it might look like:
```
auto agg = make_pearson_agg(col_b);
auto req = aggregation_request(col_a, {agg}); // form a request to do a pearson agg of col_a against b
groupby(keys).aggregate(req);
```

The only thing I don't like about this is there's an implicit requirement that `col_a` and `col_b` be the same size/type and especially order that isn't explicitly enforced.

I'll keep thinking on it as there may be better ideas yet.

**Comment by revans2** [comment]
Another option might be to have the correlation take a non-nullable struct column. If you were just operating on column views it would be very fast because it is just metadata pointing to the child columns.

**Comment by jrhemstad** [comment]
I like the idea of making the `values` column a struct column. That solves my complaint above about enforcing the columns be linked.
