### ISSUE TITLE
[BUG] `loc` behavior differs from pandas when a duplicated index is requested

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#8693]
**Describe the bug**
When we have a series with a duplicated index such as 

```python
x = cudf.Series([1,2,3,4], index=[0,1,1,2])
```

And we try and fetch the items corresponding to that duplicated index, we get just the first element rather than a series of all the elements corresponding to that index:

```python
x.loc[1]
# 2
```

**Steps/Code to reproduce bug**
See above

**Expected behavior**
We should get the same thing as pandas, basically all the rows corresponding to that index gathered. 
```python
x.to_pandas().loc[1]
# 1    2
# 1    3
# dtype: int64
```

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal]
 - Method of cuDF install: [source]

**Environment details**

**Additional context**

**Comment by shwina** [comment]
This is because of an "optimization" for scalar inputs to `loc` (https://github.com/rapidsai/cudf/blob/branch-23.02/python/cudf/cudf/core/series.py#L292), that we should probably get rid of.

A workaround is to pass the index in a list:

```python
s.loc[[0]] 
```
