### ISSUE TITLE
[FEA] Gracefully detect and except when using incorrect CUDA version

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#870]
If a user does a `pip install cudf` it currently isn't compatible with CUDA 10. We should more gracefully detect and throw a friendlier exception when this happens to guide a user in the correct direction.

**Comment by jrhemstad** [comment]
Duplicate with https://github.com/rapidsai/cudf/issues/499 ?

**Comment by kkraus14** [comment]
Resolved by #4692
