### ISSUE TITLE
[FEA] Use extension dtype for numerical columns

### ISSUE THREAD

**Issue by devavret** [rapidsai/cudf#8707]
From https://github.com/rapidsai/cudf/issues/8688#issuecomment-877309345

Currently we use numpy dtypes for our Numerical columns. When converting our dataframe's metadata to pandas compatible metadata using pyarrow, it results in a dictionary entry `"numpy_type": "float64"` which when read back from pandas causes it to convert nulls to NaNs. This is because pandas uses an extension type (basically a wrapper over numpy dtype in this case) for nullable columns. This extension dtype's string alias is `"Float64"` (F is capitalized).

We could also use extension dtypes for nullable numerical columns which evaluate to the same string aliases as their pandas' counterpart.

This would fix #8688 and df.to_pandas()

**Comment by brandon-b-miller** [comment]
I more or less support this, but there are a number of caveats that we have run into when experimenting with this in the past:

- years of pandas/numpy use as the main tool for data science/scientific computing in python has created a situation where numpy dtypes are expected in everyone's workflows, causing this to be a huge breaking change
- numerous internal uses of numpy dtype APIs such as `promote_types`, `find_common_type`, inside the codebase that support a broad spectrum of functionality, which will not work on non-numpy dtypes (we are at least trying to move away from this as a first step)
- deadlock inside the numpy codebase that prevents any kind of custom python object from properly comparing with a numpy dtype, see https://github.com/numpy/numpy/issues/7242 and https://github.com/numpy/numpy/issues/5345 for details, this means we can't easily create smart dtype objects that play nice with numpy outside of the cudf codebase.

Ultimately there is not a great way of dealing with this issue short of the pydata community gravitating as a whole to something more advanced.

cc @shwina @vyasr

**Comment by shwina** [comment]
Agree on all the points that Brandon brought up. Unfortunately, at this moment, this is just a `wontfix` for us :(

**Comment by harrism** [comment]
If we won't fix it, why not close it?
