### ISSUE TITLE
[FEA] Support min and max for STRING and TIMESTAMP_* in group by scan and scan.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8709]
**Is your feature request related to a problem? Please describe.**
As a part of https://github.com/rapidsai/cudf/issues/8440 it was decided that for running window aggregations that scan and group by scan should be used.  min and max aggregations in window work for STRING and TIMESTAMP_* types.  For STRING works for scan after some fixes, but not for group by scan. TIMESTAMP_* does not work for either of these.  IT would really be great to have support for all of these types available.

**Describe alternatives you've considered**
For TIMESTAMP_* I could cast it to a numeric type that is supported and then cast it back afterwards, but hat feels like a waste. STRING I don't know of a way to work around this.

**Additional context**
I only care about inclusive scans with nulls excluded.  Not really sure if that makes too much of a difference.

In order of priority on this I would say that STRING is much more important than TIMESTAMP_* and specifically within TIMESTAMP all I care about right now is TIMESTAMP_DAYS and TIMESTAMP_MICROSECONDS.

**Comment by davidwendt** [comment]
Closed by #9518, #9502, and #9536
