### ISSUE TITLE
[BUG] Groupby scans and segmented shift should preserve original index

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#8715]
If I use groupby.cumsum or other scan operations (or segmented shift) from Python for feature engineering, my results do not preserve an existing index. Instead, the groupby keys become the index. We should preserve the index, if possible.

Note that the differing output order is covered by #8714 

```python
import cudf
import numpy as np

np.random.seed(12)
nrows = 100

df = cudf.DataFrame({
    "key":[0] * (nrows//2) + [1] * (nrows//2),
    "val1": range(nrows),
}).sample(nrows) # shuffle data

df.head(8)
	key	val1
70	1	70
86	1	86
18	0	18
91	1	91
74	1	74
97	1	97
43	0	43
48	0	48

df.groupby("key").val1.cumsum().head()
key
0     18
0     61
0    109
0    115
0    157
Name: val1, dtype: int64

df.to_pandas().groupby("key").val1.cumsum().head()
70     70
86    156
18     18
91    247
74    321
Name: val1, dtype: int64
```

**Comment by isVoid** [comment]
@beckernick could you verify if https://github.com/rapidsai/cudf/pull/8720 also closes this?

**Comment by beckernick** [comment]
Confirmed this is now resolved. Thanks Michael!
