### ISSUE TITLE
[BUG] min/max sorted aggregation on string columns mishandles all null case

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8717]
**Describe the bug**
Requesting an min or max aggregation on a string column that contains all nulls returns data associated with another key.

**Steps/Code to reproduce bug**
Attached is a patch which adds a new test that can reproduce the issue.  It fails to properly calculate the aggregated value for the null key as null since there's no other non-null values. Note that changing the aggregation from min to max also has the same issue, but in both cases changing `sorted::YES` to `sorted::NO` allows the test to pass.

[sorted_min_string_test_patch.txt](https://github.com/rapidsai/cudf/files/6804087/sorted_min_string_test_patch.txt)

**Expected behavior**
When libcudf is using sort-based aggregation internally it should not return a different aggregation than hash-based.  The sorting is supposed to be a performance-only hint rather than changing the associated aggregated values.

**Comment by karthikeyann** [comment]
@jlowe try this PR https://github.com/rapidsai/cudf/pull/8731 as a fix.

**Comment by jlowe** [comment]
Yep, that works, thanks @karthikeyann!
