### ISSUE TITLE
[BUG] missing nightly for rapids package cuda 11.2

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cudf#8733]
https://anaconda.org/rapidsai-nightly/rapids/files?version=21.08.00a210713

Nightly has only cuda 11.0 and is (unlike other packages) missing 11.2.  Not sure where to report this.

Went missing since >=210710.

**Comment by pseudotensor** [comment]
Same for rapids-blazing package.

**Comment by raydouglass** [comment]
There are [errors in `cugraph`](https://gpuci.gpuopenanalytics.com/job/rapidsai/job/integration/job/branches/job/branch-meta-pkg-nightly-build/1167/CONDA_CONFIG_FILE=conda%2Frecipes%2Fversions.yaml,CONDA_USERNAME=rapidsai-nightly,CUDA_VER=11.2,PYTHON_VER=3.7,RAPIDS_VER=21.08.00a/console) which are blocking the `rapids` and `rapids-blazing` meta packages for CUDA 11.2.

There are a couple `cugraph` PRs to address this:
- https://github.com/rapidsai/cugraph/pull/1709
- https://github.com/rapidsai/cugraph/pull/1712

**Comment by beckernick** [comment]
CUDA 11.2 packages for 21.08 nightlies are [now available](https://anaconda.org/rapidsai-nightly/rapids/files?version=21.08.00a210719). Thanks for filing this issue @pseudotensor .

Closing.
