### ISSUE TITLE
[BUG] "RuntimeError: Total number of concatenated rows exceeds size_type range" for 2.2 million row series

### ISSUE THREAD

**Issue by marco-ve** [rapidsai/cudf#8748]
**Describe the bug**
A cudf.Series containing lists will throw a RuntimeError if one tries to access a certain number of rows, depending on the length of the contained lists.

**Steps/Code to reproduce bug**
```
gsr = cudf.Series([arr for arr in np.random.uniform(low=-0.2, high=0.2, size=(2000000,512))])
gsr

```

This will display just fine (2 million rows).

```
gsr = cudf.Series([arr for arr in np.random.uniform(low=-0.2, high=0.2, size=(2200000,512))])
gsr
```

2.2 million rows. This will throw a "RuntimeError: cuDF failure at: ../src/copying/concatenate.cu:359: Total number of concatenated rows exceeds size_type range". However, accesssing an element directly by index will work fine. Also, accessing elements [0:60] will work, but [0:61] will throw the same exception.

```
gsr = cudf.Series([arr for arr in np.random.uniform(low=-0.2, high=0.2, size=(2200000,256))])
gsr
```

This will display just fine (2.2 million rows, but shorter lists).

**Expected behavior**
Expected behavior would be for the series to access rows without throwing an error, independent of the dimensions of the object contained, same as in e.g. a pandas series.

**Environment overview (please complete the following information)**
Environment is a jupyterlab notebook hosted in the rapidsai docker container, using an RTX3090 with 24GB VRAM. cuml version is 21.06.01+2.g101fc0fda4.

**Comment by shwina** [comment]
List columns are limited by number of _elements_ (not _rows_). The total number of _elements_ in a list column cannot exceed `INT32_MAX`. We should raise a better error message here.

Internally, a list column holds a column of all its elements, i.e., the following list column:

```
[1, 2, 3]
[4, 5]
[6, None, 8]
```

internally holds the column `[1,  2, 3, 4, 5,  6, None, 8]`. The size of _that_ column cannot exceed `INT32_MAX`.

**Comment by marco-ve** [comment]
Thanks for the clarification. But isn't the max value of an int32 2.2 billion, whereas 2,200,000 * 512 is only 1.1 billion?

Also why does accessing rows [0:60] not throw an error, but [0:61] does?

**Comment by shwina** [comment]
Thanks -- you're right, that is a bug. Investigating.

**Comment by shwina** [comment]
Slightly simpler, more revealing reproducer (although I still haven't root-caused this):

```
In [12]: s = cudf.Series([arr for arr in np.ones((2_200_000, 512))]) # a list column of 2_200_000 rows and 512 elements per row
In [13]: top = s.iloc[:31] # slice of first 31 rows
In [14]: bottom = s.iloc[31:62]  # slice of rows 31-62
In [15]: cudf.concat([top, bottom])  # errors
In [15]: cudf.concat([top.copy(), bottom.copy()])  # deep copy before concat, no error
```

cc: @nvdbaranec
