### ISSUE TITLE
[FEA] Java bindings for AST expressions

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8773]
**Is your feature request related to a problem? Please describe.**
#5494 added AST support for composing and evaluating expressions at runtime, and it would be nice to have Java bindings for this feature.

**Describe the solution you'd like**
The Java bindings should have a class hierarchy similar to the native AST node types, but ideally not owning the actual underlying native objects directly.  This would require the AST nodes to be `AutoCloseable` and leak-tracked.  Instead, the use-case is likely to be one-shot build and use, so it would be easier on the application to have pure JVM classes to build the AST and a separate API to "compile" that into a native AST representation that does need to be closed and leak-tracked.

**Describe alternatives you've considered**
A thinner, more direct binding could be done, but this puts more burden on the application to avoid leaks and increases the object creation overhead for every node in the tree.

**Comment by vyasr** [comment]
@jlowe can we close this with #8846?

**Comment by jlowe** [comment]
Yes, this was fixed by #8846 and #8888.
