### ISSUE TITLE
Dockerfile has no cleaning commands [BUG]

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#881]
**Describe the bug**
The Dockerfile contains build commands but no corresponding clean commands. 

**Steps/Code to reproduce bug**
Each layer size is bigger than its intended size due to storage space taken by temporary files. 

**Expected behavior**
dockerfile best practices suggest to clean the temporary files after build/install in same RUN command. https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run
Otherwise, that layer will take more storage space. 

**Environment details (please complete the following information):**
 - Environment location: [Docker]
 - Method of cuDF install: [ Docker build from source]

**Additional context**
add clean commands for all build commands generating temporary files.

**Comment by kkraus14** [comment]
@randerzander any ideas on how we can better maintain the Dockerfile here as opposed to the greater rapidsai Dockerfile?
