### ISSUE TITLE
[FEA] Ability to regex replace a capture group followed by a digit

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#8816]
**Is your feature request related to a problem? Please describe.**
I would like to capture a group and then specify in the replace string that the capture group is emitted followed by a zero.  The problem is that `\10` looks like I'm asking for capture group 10 instead of capture group 1 followed by a zero.

**Describe the solution you'd like**
If there was an alternate syntax for specifying a capture group, like `${1}` instead of `\1` then `${1}0` wouldn't be ambiguous what is being requested.

**Describe alternatives you've considered**
One potential issue with the proposed solution is that it adds semantic interpretation of the replace string that didn't exist before.  That could break existing use-cases that happen to use a `${1}` syntax or something like it. Another approach could be to allow hexadecimal escapes or some other notation, e.g.: `\1\x30` where hex 30 is ASCII `0`, but that too will add a new interpretation of potentially pre-existing replace strings.

**Comment by davidwendt** [comment]
Looking at the reference documentation [here](https://www.regular-expressions.info/refreplacebackref.html) I'm not seeing  `\x##` syntax mentioned for the replacement string. And we certainly do not support all the features listed there. Regardless, supporting escaped characters in the replacement string in the current libcudf logic would be difficult. I think we could more easily support the `${#}` pattern but like Jason mentioned, this could fail if there are existing replacement strings that happen to have strings with this pattern and are relying on the `\#` syntax. I think we could support both by first checking if the `\#` pattern exists and if not, switch to look for `${#}` and thereby disallow a mixture of the two syntaxes. This would still have some holes but could minimize any breakages.
