### ISSUE TITLE
[FEA] Improve cudf.Index to enable dask_cudf to perform repartition operations

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#882]
As a data engineer, I work with files of disparate and inconvenient sizes. Dask and cuDF need partitions of varying sizes depending on workflow. Today I can use Dask.Distributed to repartition host-side, but ideally I could do it on GPU, especially after performing filtering, resampling, etc.

@mrocklin listed 3 necessary improvements to cuDF's indexing [here](https://github.com/rapidsai/dask-cudf/issues/40#issuecomment-425098589).

**Comment by mrocklin** [comment]
Note that at least for the CSV case we can probably also improve the situation by implementing a blocked `dask_cudf.read_csv` as proposed in https://github.com/rapidsai/dask-cudf/issues/71

**Comment by mrocklin** [comment]
Concretely we need operations like the following for the various inequalities

    df[df.index >= 5]

**Comment by kkraus14** [comment]
Closing this with #958
