### ISSUE TITLE
[FEA] Add DataFrame.from_gpu_matrix support

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#883]
As a numba user, I write kernels that produce ndarrays on GPU. I'd like to use a DataFrame.from_gpu_matrix function to easily take these kernel results into a DataFrame.

To get device ndarrays into DataFrames today, I need to split the ndarray up into 1D arrays, wrap them in cudf.Series and then add to a DataFrame. The process of allocating those device arrays and then wrapping is error prone and requires more code than desired.

@AK-ayush fyi

**Comment by jrhemstad** [comment]
If we can have an efficient and high performance way to convert an ndarray into a DF, then this would be a great solution to the transpose performance problem.

**Comment by kkraus14** [comment]
Resolved by #1004.
