### ISSUE TITLE
[FEA] Refactor `cudf::strings::detail::make_strings_children` to accept `std::function` as argument

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#8845]
Currently, the internal API `cudf::strings::detail::make_strings_children` is a template function, accepting arbitrary functor as its template argument. As a result, the function has to be put into a header, which in turn is included in many source files. Since the function is a template function, each call to it will result in a separate template instantiation with separate code path.

We can improve this by rewriting the function into a regular function, replacing its template argument by a `std::function` parameter for the input functor. By doing so, we will be able to put the function into a `.cpp/.cu` file and will just have one function instantiation. I believe that this will significantly improve compiling time and reduce binary size.

**Comment by ttnghia** [comment]
@davidwendt Please give comments on this. I think this is a very interesting task.

**Comment by davidwendt** [comment]
I'm pretty sure this will not work. The functor that is passed to this utility is forwarded along to `thrust` functions which are header only and so this generally requires inline device functors/lambdas known at compile time -- we do not compile with (-rdc).  So thrust will not be able to call a function it cannot inline at compile time in libcudf.

**Comment by ttnghia** [comment]
Oh that is bad :disappointed:

**Comment by ttnghia** [comment]
How about we create this lambda in the caller function:
```
auto for_each_fn = [exec_size, stream](SizeAndExecuteFunction& size_and_exec_fn) {
    thrust::for_each_n(rmm::exec_policy(stream),
                       thrust::make_counting_iterator<size_type>(0),
                       exec_size,
                       size_and_exec_fn);
  };
```
Then we pass this lambda to the ulitity function?

**Comment by davidwendt** [comment]
Every `for_each_fn` would be a different type because of the `size_and_exec_fn` and so you would have the same problem.

**Comment by ttnghia** [comment]
Yes, they are of different types, but they can be converted into a fixed type of `std::function<void()>`. Let me try that shortly.

**Comment by davidwendt** [comment]
You will not be able to call a `device` function defined in one .cu from a `device` code function defined in a separate .cu file.

**Comment by ttnghia** [comment]
Ah I got it---as we are not compiling with (-rdc). Thanks!

**Comment by ttnghia** [comment]
Unfortunately my idea doesn't work in the meantime, as we are not using `-rdc` compilation. Close for now.
In the future, if `-rdc` is enable then this will be feasible and can be look back.
