### ISSUE TITLE
[DOC] Installation command is incorrect.

### ISSUE THREAD

**Issue by sidgan** [rapidsai/cudf#886]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.
The website: https://rapids.ai/start.html states the install command as `python3.6 -m pip install cudf-cuda100=0.5 cuml-cuda100=0.5`.

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.
Pip installing a speceif version needs == instead of =, or if its using = it should have single quote such as `'cuml-cuda100=0.5'`

**Steps taken to verify documentation is incorrect**
List any steps you have taken:
Installed with the correct command.

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.
Fix the command or provide both fully complete options. 
---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by mike-wendt** [comment]
I already fixed this on the website
