### ISSUE TITLE
[QST] How to rewrite iterrows in cudf

### ISSUE THREAD

**Issue by cr4zy-C** [rapidsai/cudf#8860]
I am trying to calculate the number of tasks in queue, the current implementation iterates over each row and compares the current row to the whole dataset, I also want to do it similar with cudf to improve its performance. My problem is that currently that I am not sure how I can rewrite this code to still work the same. I faced some issues with the comparison of datetimes and I am not sure how I can access the whole dataframe when using `apply_rows`?

```python
for index, row in tqdm(filtered_data.iterrows(), total=filtered_data.shape[0]):
             filtered_data.loc[index, 'queue'] = queue_init + filtered_data[(filtered_data['startDate'] < row['startDate']) & (filtered_data['endDate'] > row['startDate'])]['id'].count()
```

**Comment by beckernick** [comment]
Iterating over the rows of a cuDF object in a Python loop is not supported for performance reasons (each row will cause its own device to host transfer).

Perhaps there might be a vectorized approach to your logic that would be efficient? If you provide a minimal, reproducible example, someone in the community might be able to help out.

**Comment by cr4zy-C** [comment]
Thanks, I read through the guide, it is quite helpful but I could not find the solution to my problem. Of course I can provide an example and hopefully someone can help me or point me to another resource that might help.

### Example
Needed imports
```python
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm
tqdm.pandas()
```
Function which counts the tasks in queue (row start time needs to be later than from others in dataframe and row start time needs to be earlier than end time from others in dataframe, so that the tasks are still running)
```python
def tasks_in_queue(data_df, queue_init=0):
    # Calculating tasks in queue
    filtered_data = data_df.sort_values(by=['startDate'])  

    for index, row in tqdm(filtered_data.iterrows(), total=filtered_data.shape[0]):
         filtered_data.loc[index, 'tasksInQueue'] = queue_init + filtered_data[(filtered_data['startDate'] < row['startDate']) & (filtered_data['endDate'] > row['startDate'])]['id'].count()

    return filtered_data
```

Data generation, create 10.000 random samples
```python
data = pd.DataFrame()

start_list = []
end_list = []
range_size = 10000

for i in range(range_size):
    month = np.random.randint(1, 13)
    day = np.random.randint(1, 31)
    hour = np.random.randint(0, 24)
    minute = np.random.randint(0, 60)
    
    
    if month == 2 and day > 28:
        day = 28
    
    start_list.append(f"2021-{str(month).zfill(2)}-{str(day).zfill(2)} {str(hour).zfill(2)}:{str(minute).zfill(2)}:22")
    end_list.append(f"2021-{str(month).zfill(2)}-{str(day if day >= 25 else day + 3).zfill(2)} {str(hour if hour >= 19 else hour + 4).zfill(2)}:{str(minute if minute > 55 else minute + 4).zfill(2)}:22")

data['startDate'] = pd.to_datetime(start_list, format="%Y-%m-%d %H:%M:%S")
data['endDate'] = pd.to_datetime(end_list, format="%Y-%m-%d %H:%M:%S")
data['id'] = [i for i in range(range_size)]

data.head()
```
Run it and check the time
```python
%%time
test_data = tasks_in_queue(data, 0)
test_data.head()
```

**Comment by beckernick** [comment]
From what you've described, an efficient way to do this (CPU or GPU) might be to do an inequality self-join to get one row per unique ID based on your start/end date criteria, followed by a groupby count operation to get the number of rows per ID. This would give you the correct value per ID.

This is not currently available in cuDF Python (it doesn't exist in pandas/Dask), though we've been working on the [capabilities](https://github.com/rapidsai/cudf/milestone/7) in CUDA/C++ and it exists in Apache Spark.

If you have enough memory, you can accomplish the same thing with a standard cartesian self join and then filtering after the fact based on your condition (but you may go out of memory / take a performance hit). This would be much faster than iterating row by row.

**Comment by cr4zy-C** [comment]
Ok thank you for the suggestion I will try to implement it! Also will take a look at Apache Spark

**Comment by beckernick** [comment]
Glad to hear it. As a suggestion, you can do a self join by adding a `key` column with the same value.

```python
df=["key"] = 1
df.merge(df, on="key")
```

I'm going to close this issue as answered, but please feel free to re-open.
