### ISSUE TITLE
[FEA] Extend support for add_calendrical_months to INT32

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8865]
**Is your feature request related to a problem? Please describe.**
`add_calendrical_months` was added to cudf recently, which is great, but there is a slight disconnect with what Spark wants/needs for it.

**Describe the solution you'd like**
Spark stores month ranges as an INT32. `add_calendrical_months` only supports an INT16. This is probably not much of an issue in practice because an INT16 gives us 2730 years of range but it is not as much as Spark supports. This means that for scalar calendar interval values, which is the most common type, we can use the provided API, because we can verify that it is in the supported range.  For actual vectors of data we cannot use the API and will have to fall back to the CPU.

But this brings up another issue. All we can support with the current API is scalar values for months, but the current API does not support scalar values for months, so we would have to turn the scalar into a full column vector before processing.  This is a somewhat minor issue in terms of memory and computation time, but it would be nice to be able to avoid that step and just do the math directly using a scalar.

**Describe alternatives you've considered**
In theory we could look at the month interval and if any of them are out of the range for what an INT16 supports, we add months in a loop until we have done it enough, but that just feels wrong and could result in the worst case us calling the API 32,000 times. Especially because it looks like the code already supports in as INT32

```
using duration_m = duration<int32_t, months::period>;
```

**Additional context**
Like I said this is not critical. We have a work around for all of the issues. I mostly wanted to document the disconnect between what was wanted in #3750 and what was actually implemented. That way hopefully we can get this fixed before we get too far down the road.

**Comment by beckernick** [comment]
Thanks for looking into this so quickly. https://github.com/rapidsai/cudf/issues/6990 requests scalar support, so I'm going to update the title of this issue to explicitly request int32

**Comment by revans2** [comment]
Sounds good.

**Comment by vuule** [comment]
@revans2 should scalar version also support int32?

**Comment by revans2** [comment]
> @revans2 should scalar version also support int32?

Yes if possible.
