### ISSUE TITLE
[BUG] cudf reads orc file failed.

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#8878]
``` python
In [1]: import pandas as pd

In [2]: import pyarrow.orc

In [3]: pd.read_orc("struct_193401869.orc")
Out[3]: 
                                a
0  {'c_3': 100, 'c_1': 'Hello-0'}
1  {'c_3': 101, 'c_1': 'Hello-1'}
2  {'c_3': 102, 'c_1': 'Hello-2'}
3  {'c_3': 103, 'c_1': 'Hello-3'}
4  {'c_3': 104, 'c_1': 'Hello-4'}
5  {'c_3': 105, 'c_1': 'Hello-5'}
6  {'c_3': 106, 'c_1': 'Hello-6'}
7  {'c_3': 107, 'c_1': 'Hello-7'}

In [4]: import cudf

In [5]: cudf.read_orc("struct_193401869.orc")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-fde708a23404> in <module>
----> 1 cudf.read_orc("/home/bobwang/work.d/nvspark/spark-rapids/struct_193401869.orc")

~/anaconda3/envs/rapids-21.08/lib/python3.7/site-packages/cudf/io/orc.py in read_orc(filepath_or_buffer, engine, columns, filters, stripes, skiprows, num_rows, use_index, decimal_cols_as_float, timestamp_type, **kwargs)
    300                 use_index,
    301                 decimal_cols_as_float,
--> 302                 timestamp_type,
    303             )
    304         )

cudf/_lib/orc.pyx in cudf._lib.orc.read_orc()

cudf/_lib/orc.pyx in cudf._lib.orc.read_orc()

RuntimeError: cuDF failure at: ../src/io/orc/reader_impl.cu:1155: Expected streams data within stripe

```
The meta of ORC file:
``` console
Structure for struct_193401869.orc
File Version: 0.11 with ORC_14
Rows: 8
Compression: ZLIB
Compression size: 4096
Type: struct<a:struct<c_3:smallint,c_1:string>>

Stripe Statistics:

File Statistics:

Stripes:
  Stripe: offset: 3 data: 50 rows: 8 tail: 37 index: 0
    Stream: column 3 section DATA start: 3 length 6
    Stream: column 3 section LENGTH start: 9 length 6
    Stream: column 3 section DICTIONARY_DATA start: 15 length 31
    Stream: column 2 section DATA start: 46 length 7
    Encoding column 0: DIRECT
    Encoding column 1: DIRECT
    Encoding column 2: DIRECT
    Encoding column 3: DICTIONARY[8]

File length: 167 bytes
Padding length: 0 bytes
Padding ratio: 0%
```
And the orc file can be found at https://drive.google.com/file/d/14lT5ROarR48ecaOcPH44H3NRNNpUFQcG/view?usp=sharing

The issue can be found in the latest 21.08 nightly build.

**Comment by rgsl888prabhu** [comment]
@wbo4958 Using which application/library  `struct_193401869.orc` has been created ?

**Comment by wbo4958** [comment]
Actually, spark-rapids pruned some columns and change the order of columns, is there any problem? BTW, spark also can read this file.

**Comment by rgsl888prabhu** [comment]
I just wanted to see whether the issue is dependent on data or how it has been written, since I read the orc via pyarrow and created new orc file using pyarrow, and cudf read it properly. So, I just wanted to be sure and a way to repro if required.

**Comment by wbo4958** [comment]
cudf can't read that file, which seems to be a cudf bug.

**Comment by firestarman** [comment]
Found a similiar issue https://github.com/rapidsai/cudf/issues/8910.

**Comment by wbo4958** [comment]
Hi @rgsl888prabhu,

I just debugged the cudf ORC reader and found cudf ORC reader may require **ROW_INDEX**  for the nested schema. The dumped file **struct_193401869.orc** just does not contain any ROW_INDEX stream.

For example,  for the schema "struct<a:struct<c_3:smallint,c_1:string>>",

First, for the 1st level, the ORC reader tries to [gather_stream_info](https://github.com/rapidsai/cudf/blob/branch-21.10/cpp/src/io/orc/reader_impl.cu#L1143) for the "a: struct",  and cudf ORC reader throw exception because it can't find any stream for "a".

**Comment by rgsl888prabhu** [comment]
Yeah, I agree. Even I saw that and I was thinking how to approach this issue since in case if you write same dataframe using pyarrow it adds all these streams. I am currently working towards an approach to solve this. And I am also working on the issue #8910, but I haven’t been able to pinpoint the issue so far.

**Comment by firestarman** [comment]
Hi, any updates here?
May I know whether this bug is specific to struct or not ?

**Comment by rgsl888prabhu** [comment]
So far I have seen this with struct, but currently trying other scenarios as well such as having other type column along with struct. And what happens if number of rows goes beyond 10k.

**Comment by rgsl888prabhu** [comment]
@wbo4958 @firestarman Please try #9060 and let me know if it fixes your issue.

**Comment by firestarman** [comment]
> @wbo4958 @firestarman Please try #9060 and let me know if it fixes your issue.

Verified locally and it can fix this issue. Thanks.
