### ISSUE TITLE
[FEA] Support for CUDA 8.0 or 9.1?

### ISSUE THREAD

**Issue by datatalking** [rapidsai/cudf#8937]
**Is your feature request related to a problem? Please describe.**
Is there any support or patchable options to run cudf in CUDA 8.0 or 9.1 [...]

**Describe the solution you'd like**
Be able to use cudf for processing data in python 2.7 with CUDA 8.0 or 9.1

**Describe alternatives you've considered**
We are currently not using cudf and are facing integration issues with Apache Airflow resulting in speed decreases

**Additional context**
The current implementation is based on https://gist.github.com/datatalking/15320ca9a3ed27dd438b0ddfc96fc60e

**Comment by beckernick** [comment]
I'm going to close this issue as answered, but please feel free to re-open. Thanks!
