### ISSUE TITLE
[FEA] Allow "no-op" to a sequence column in groupby transform-like operations

### ISSUE THREAD

**Issue by isVoid** [rapidsai/cudf#8951]
Per #8714 we have made return columns in groupby transform like operations to match the order of inputs. This is achieved by doing a multi-column sort (creating a sequence column afterwards, and group them by keys):

https://github.com/rapidsai/cudf/blob/b9820f15c1da6b20d37bd13f23a68e7c1e07c786/python/cudf/cudf/core/groupby/groupby.py#L1009-L1012

However, this can be further simplified by attaching a "meta-column" to inputs on the first run. And sort the result using the "meta-column" as key. This reduces the multi-column sort to a single-column sort. AFAIK, this isn't possible in libcudf right now, because for "transform-like" operations (e.g. shift), the "meta-column" is also operated upon.

**Comment by isVoid** [comment]
cc @shwina

**Comment by wence-** [comment]
I was trying to understand this comment about multi-column sorts. AFAICT, the current implementation of `mimic_pandas_order` sorts a single key column and then uses that to gather the grouped result into the correct order.

**Comment by vyasr** [comment]
I agree, AFAICT this is already a single-column sort. @isVoid could you clarify what you were thinking of here?

**Comment by isVoid** [comment]
I think you both are correct - It is likely at certain stage I have confused passing a single column table into `get_groups` function v.s. multi-column sorts. Given what @wence- described above, I think this feature request is likely no longer relevant given the implementation is optimal.
