### ISSUE TITLE
[FEA] support lists::contains on lists of structs.

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8958]
**Is your feature request related to a problem? Please describe.**
We would like to extend the `lists::contains` function to support lists of structs and list of more deeply nested structs, like a struct with structs in it. We are prioritizing structs right now, and this is not intended to cover structs that also contain lists.

Just like with the existing code if the input value is a null or if the search value is a null, then the output should also be a null.

**Describe the solution you'd like**
Have `lists::contains` just work.

**Describe alternatives you've considered**
We could try and hack this together ourselves by picking apart the child columns and then checking for equality for each of them, with and-ing them all together followed by a reduction, but that gets really complicated.

**Comment by revans2** [comment]
This is still wanted. Not a huge priority though

**Comment by ttnghia** [comment]
Blocked by hash refactoring. I'm still investigating it.

**Comment by jrhemstad** [comment]
> Blocked by hash refactoring. I'm still investigating it.

This will be solved trivially by https://github.com/rapidsai/cudf/issues/10186

**Comment by ttnghia** [comment]
@revans2 I think we should better support trivial `lists::contain` first (i.e., check if each list contains a given scalar), as we did for the general `cudf::contain` before. General support for checking a list containing a set a scalars is more difficult and will be implemented later if there is customer request.
