### ISSUE TITLE
[FEA] Add nested struct support for cudf::contains

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8965]
**Is your feature request related to a problem? Please describe.**
For Spark we are pushing to get more support for structs in a number of operators. We already have some support for sorting structs, so we should be able to come up with a way to check for existence of a struct value from one column to another. NOTE this does not include lists as children of the structs just structs that contains basic types including strings and other structs.

his should follow the same pattern we have supported for sorting where null child columns are considered equal to other null child columns.  Like described in https://github.com/rapidsai/cudf/issues/8964

**Describe the solution you'd like**
I would like to see cudf::contains updated so it can support this.

**Describe alternatives you've considered**
I don't think there is an alternative that we can do on our own.

**Comment by revans2** [comment]
This is still wanted

**Comment by ttnghia** [comment]
Please note that this is partially supported in https://github.com/rapidsai/cudf/pull/9929
Full support for this requires complete hashing work, which is undergone some refactoring in the meantime.
