### ISSUE TITLE
[FEA] add nested struct support for nth reduction and group by aggregation

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#8967]
**Is your feature request related to a problem? Please describe.**
For Spark we are pushing to to support structs more fully in our product.  As a part of this we would like to be able to support nth on nested structs as a part of a reduction and also as a part of an group by aggregation. 

In both cases looking at the code it essentially first calculates the indexes to get and then gets them either with a gather or a get element.  Gather already supports all nested types, not just structs, so it should just work after doing some type check updates. But I could be wrong and I am open to other options. 

**Describe the solution you'd like**
Have first and last work  out of the box.

**Describe alternatives you've considered**
Hack something together where I take the validity of the original input column and then combine it with a sequence, and then do the nth aggregation to finally get the set of indexes to gather or get directly.

**Comment by sperlingxx** [comment]
I am working on this issue.
