### ISSUE TITLE
[BUG] Ragged DataFrames don't work when importing Numpy arrays.

### ISSUE THREAD

**Issue by roshkins** [rapidsai/cudf#8982]
**Describe the bug**

Ragged DataFrames work for Series, but not when using Numpy arrays.

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

```python
import cudf
import numpy as np

df = cudf.DataFrame()
df['series1'] = np.array([1,2,3])
df['series2'] = np.array([1,2]) # error here

df
```

vs.

```python
import cudf
import numpy as np

df = cudf.DataFrame()
df['series1'] = cudf.Series([1,2,3])
df['series2'] = cudf.Series([1,2]) # no error here

df
```
has no errors.
**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

Paperspace, installed from Docker:  rapidsai/rapidsai:0.19-cuda11.0-runtime-ubuntu18.04-py3.7

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details
Couldn't run.

**Additional context**

**Comment by beckernick** [comment]
Thanks for filing an issue @roshkins . What is expected behavior in your mind?

When I try this with CPU PyData libraries, I see similar behavior.

```python
import pandas as pd
import numpy as np
​
df = pd.DataFrame()
df['series1'] = pd.Series([1,2,3])
df['series2'] = pd.Series([1,2]) # no error here
​
print(df)
   series1  series2
0        1      1.0
1        2      2.0
2        3      NaN
```
```python
import pandas as pd
import numpy as np
​
df = pd.DataFrame()
df['series1'] = np.array([1,2,3])
df['series2'] = np.array([1,2]) # error here
​
df
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_73241/1555942935.py in <module>
      4 df = pd.DataFrame()
      5 df['series1'] = np.array([1,2,3])
----> 6 df['series2'] = np.array([1,2]) # error here
      7 
      8 df

/raid/nicholasb/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/pandas/core/frame.py in __setitem__(self, key, value)
   3161         else:
   3162             # set column
-> 3163             self._set_item(key, value)
   3164 
   3165     def _setitem_slice(self, key: slice, value):

/raid/nicholasb/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/pandas/core/frame.py in _set_item(self, key, value)
   3240         """
   3241         self._ensure_valid_index(value)
-> 3242         value = self._sanitize_column(key, value)
   3243         NDFrame._set_item(self, key, value)
   3244 

/raid/nicholasb/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/pandas/core/frame.py in _sanitize_column(self, key, value, broadcast)
   3897 
   3898             # turn me into an ndarray
-> 3899             value = sanitize_index(value, self.index)
   3900             if not isinstance(value, (np.ndarray, Index)):
   3901                 if isinstance(value, list) and len(value) > 0:

/raid/nicholasb/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/pandas/core/internals/construction.py in sanitize_index(data, index)
    749     """
    750     if len(data) != len(index):
--> 751         raise ValueError(
    752             "Length of values "
    753             f"({len(data)}) "

ValueError: Length of values (2) does not match length of index (3)
```

**Comment by roshkins** [comment]
I was expecting that the arrays would be converted to series since they
were assigned to a dataframe. But it looks like perhaps this is expected
behavior and I need to explicitly cast it to a series.

**Comment by beckernick** [comment]
We generally try to follow CPU PyData libraries for compatibility reasons, so I think we'd likely want to continue following their behavior with this example. As a result, I'm going to close this issue as resolved.

Please feel free to re-open it if you'd like to continue the discussion.
