### ISSUE TITLE
[BUG] cudf.DataFrame.to_arrow consuming a large amount of host memory

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#899]
Converting a relatively small dataframe (80MB) consumes so much host memory that it causes Python to generate repeated GC warnings.

```
from dask.distributed import Client, wait
from dask_cuda import LocalCUDACluster
import dask, cudf
import dask.array as da
import dask.dataframe as dd

ip = '0.0.0.0'
cluster = LocalCUDACluster(ip=ip)
client = Client(cluster)

import dask.array as da
import dask.dataframe as dd

n_rows = 5000000
n_keys = 5000000

ddf = dd.concat([
    da.random.random(n_rows).to_dask_dataframe(columns='x'),
    da.random.randint(0, n_keys, size=n_rows).to_dask_dataframe(columns='id'),
], axis=1).persist()

# from distributed.utils import format_bytes
# format_bytes(len(gdf) * 8 * 2)
# This is a 80MB dataframe
gdf = ddf.map_partitions(cudf.from_pandas)

def get_arrow(df):
    return df.to_arrow()

%time pats = gdf.map_partitions(get_arrow).compute()
```
Result:
```
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 24% CPU time recently (threshold: 10%)
distributed.utils_perf - WARNING - full garbage collections took 26% CPU time recently (threshold: 10%)
CPU times: user 21 s, sys: 1.03 s, total: 22 s
Wall time: 22.1 s
```

**Comment by kkraus14** [comment]
@randerzander does this happen outside of Dask? I'd guess this is more likely due to serialization related code in Dask than anything cuDF related as the `to_arrow` code is all just straight memory copies from device to host.

**Comment by randerzander** [comment]
@kkraus14 no, it doesn't. Using cudf.DataFrame.to_arrow directly takes ms, for multi-GB dataframes.

This looks like a Dask serialization problem, as you say. @mrocklin should I move this issue to dask_cudf or dask proper?

**Comment by mrocklin** [comment]
For context, Dask special cases arrow Tables and RecordBatches here: https://github.com/dask/distributed/blob/master/distributed/protocol/arrow.py

If there are improvements that could be made there then yes, an issue would be welcome.

You might also want to ensure that you're using the most recent arrow release (0.12?).  They may have improved this recently.
