### ISSUE TITLE
[FEA] Support callables in groupby.agg

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#901]
Do we intend to support user-defined callables in groupby aggregations?

```python
import cudf
df = cudf.DataFrame({'x': [1, 2, 3]})
df.groupby('x').agg(sum)
```

```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-3c112c2bac22> in <module>()
----> 1 df.groupby('x').agg(sum)

~/cudf/python/cudf/groupby/groupby.py in agg(self, args)
    316         # use_prefix enables old functionality - prefixing column
    317         # groupby names since we don't support MultiColumn quite yet
--> 318         use_prefix = 1 < len(self._val_columns) or 1 < len(args)
    319         if not isinstance(args, str) and isinstance(
    320                 args, collections.abc.Sequence):

TypeError: object of type 'builtin_function_or_method' has no len()
```

For dask dataframe groupby aggregations I'm particularly interested in the following callable

```python
lambda x: (x**2).sum()
```

It doesn't need to be fast, the dataframe on which this is run is often quite small.

**Comment by mrocklin** [comment]
cc @kkraus14 @thomcom

**Comment by thomcom** [comment]
The groupby functions are fixed in CUDA: max, min, sum, count, and mean. The shortest answer here is: square x into another column and `.sum` by that column. I am looking into providing a programmatic solution to do just that.

**Comment by mrocklin** [comment]
The relevant code in dask/dask is here

https://github.com/dask/dask/blob/5cd3843a71f716731527758fab7a47b5294b66ad/dask/dataframe/groupby.py#L240-L247

If there is an equally clean way to do this in a cudf-friendly way then it
is possibly feasible to push that change upstream to dask and fix it there.

**Comment by thomcom** [comment]
Is there a reason we can't do

```
def _var_chunk(df, *index):
    if is_series_like(df):
        df = df.to_frame()
    g = _groupby_raise_unaligned(df, by=index)
    x = g.sum()
    g2 = _groupby_raise_unaligned(x**2, by=index)
    x2 = g2.sum().rename(columns=lambda c: c + '-x2')
    n = g.count().rename(columns=lambda c: c + '-count')
    return pd.concat([x, x2, n], axis=1)
```
to achieve the same result @mrocklin ?

**Comment by mrocklin** [comment]
I'm not sure.  Maybe?  If you make that change do tests pass?  If so, great!  :)

**Comment by mrocklin** [comment]
FWIW I no longer care about this.  I've handled it in Dask here: https://github.com/dask/dask/pull/4482

**Comment by kkraus14** [comment]
Closing this as it's resolved upstream in dask and out of scope for cuDF.
