### ISSUE TITLE
[BUG] Wrong decimal values  after changing data type

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#9014]
**Describe the bug**
Hello, we got a wrong value when we change the decimal data type using Decimal64Dtype.

**Steps/Code to reproduce bug**
```python
import cudf
from cudf.core.dtypes import Decimal64Dtype
df = cudf.DataFrame({'a':[1.150,1.151, 1.152,1.153,1.154,1.155,1.434,1.665,1.746,1.867]})
df.a.round(decimals=2, how='half_up')
0    1.15
1    1.15
2    1.15
3    1.15
4    1.15
5    1.16
6    1.43
7    1.67
8    1.75
9    1.87
Name: a, dtype: float64

df.a.round(decimals=2, how='half_up').astype(Decimal64Dtype(9,2))
0    1.14
1    1.14
2    1.14
3    1.14
4    1.14
5    1.15
6    1.43
7    1.67
8    1.75
9    1.87
Name: a, dtype: decimal64
```

**Expected behavior**
```python
df.a.round(decimals=2, how='half_up').astype(Decimal64Dtype(9,2))
0    1.15
1    1.15
2    1.15
3    1.15
4    1.15
5    1.16
6    1.43
7    1.67
8    1.75
9    1.87
Name: a, dtype: decimal64

```
**Environment overview (please complete the following information)**
 - Environment location:  Docker
 - Method of cuDF install: conda

**Environment details**
```
cudf.__version__
'21.08.00a+289.gb011299069'
```

**Comment by harrism** [comment]
See 
https://github.com/rapidsai/cudf/issues/7195 and
https://github.com/rapidsai/cudf/issues/8015

If you go to https://www.h-schmidt.net/FloatConverter/IEEE754.html and enter "1.15" you can see it's not exactly representable in floating point. It's 1.499...  So when you cast to decimal, which is an integer, it truncates to 1.14.

Therefore I'm pretty sure this is not a bug, it's just how floating point works, as in the above two issues.

Perhaps convert to decimal first, then round (this is what Spark does, according to https://github.com/rapidsai/cudf/issues/7195).

**Comment by MikeChenfu** [comment]
Thanks @harrism. Good to know that.
And do you have any idea to do a multiplication between float and decimal, like 0.1 * df.a?
Currently, the workaround is to assign 0.1 to a new column and change the data type as decimal for multiplication, but use more GPU memory. Appreciate it if you have any ideas about it.

**Comment by harrism** [comment]
Ultimately you have to convert the two to the same type. If it's scalar multiplication (0.1 * every element of the DF), then use a scalar, not a column. The difference in size between a float scalar and a decimal scalar should be negligible.

**Comment by harrism** [comment]
Sorry, didn't mean to hit close. If you consider this still a bug, please reopen for discussion.
