### ISSUE TITLE
[FEA] Function to convert `dask cupy array` to `dask cudf dataframe`

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#9029]
**Is your feature request related to a problem? Please describe.**

We should implement a function to convert `dask  cupy array` to `dask cudf dataframe`

**Describe the solution you'd like**

We should have an API like below (following the dask cpu api) 
```python
import  dask_cudf 
df = dask_cudf.from_dask_array(dask_ar)
```

On CPU Frames it works like this : 

```python
import  dask.dataframe as dd
dask_df = dd.from_dask_array(dask_ar)
```

**Describe alternatives you've considered**

Below work around works for now. 
```python

import cudf

## below creates the dask_cudf type of DatFrame
meta_df = cudf.DataFrame(data=np.ones(shape=(2,dask_ar.shape[1]), dtype=dask_ar.dtype))
dask_df = dask_ar.to_dask_dataframe(meta=meta_df)

## to make writing sucessful with parquet
dask_df.columns = [str(col) for col in dask_df.columns]
```

**Comment by quasiben** [comment]
Does `dd.from_dask_array` not work or result in a DtoH/HtoD transfer when using dask cupy arrays ?

**Comment by VibhuJawa** [comment]
> Does `dd.from_dask_array` not work or result in a DtoH/HtoD transfer when using dask cupy arrays ?

It seems to ceate host frames instead of `cudf` fames. 

```python
import  dask.dataframe as dd
import dask.array as da
import cupy as cp

ar = np.ones(shape=(100_000,12),dtype=cp.float32)
dask_ar = da.from_array(ar,chunks=50_000).map_blocks(cp.asarray)
```
See below: 
```python
dask_df = dd.from_dask_array(dask_ar)
df = dd.from_dask_array(dask_ar)

print(type(df._meta))
print(type(df.get_partition(0).compute()))
```

```python
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
```

**Comment by quasiben** [comment]
Thanks for testing @VibhuJawa . This is definitely an issue when constructing the dataframe dask will check `meta` if this is None, then Dask defaults to `pd.Dataframe`:
https://github.com/dask/dask/blob/bfbce61a623587ca8693ba280c76387bb8060c22/dask/dataframe/io/io.py#L36-L37

We could check for `__cuda_array_interface__` or `is_cupy_type`: https://github.com/dask/dask/blob/bfbce61a623587ca8693ba280c76387bb8060c22/dask/utils.py#L1259-L1261

I'm surprised but perhaps we haven't been down this before where we want to generally convert from cupy to cudf. 

cc @jakirkham @pentschev @galipremsagar if you have thoughts here

**Comment by rjzamora** [comment]
Hopefully this was closed by https://github.com/dask/dask/pull/9579, but please re-open if something is missing.
