### ISSUE TITLE
[FEA] gpuCI should run tests under cuda-memcheck

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#904]
**Is your feature request related to a problem? Please describe.**
Memory errors can occur in unit tests that aren't reported as failed tests. 

**Describe the solution you'd like**
In addition to running our tests as they are now, we should also run our Python and C++ unit tests under `cuda-memcheck` and `valgrind` in order to catch any uncaught memory errors.

**Comment by felipeblazing** [comment]
Yes please for the love of everything that is universe

**Comment by jrhemstad** [comment]
Revisiting this issue, given that today our CI takes quite a while to run, I think running under `cuda-memcheck` is more of a nightly kind of thing.

**Comment by jlowe** [comment]
After helping to chase down #5792 I would love to see this be run on a regular basis.  Running this nightly or even only weekly seems like a good compromise.

**Comment by mnicely** [comment]
@awthomp We should consider this as well for cuSignal

**Comment by harrism** [comment]
@jlowe we would have to disable pool allocation in tests to make cuda-memcheck work for leak checking.

**Comment by jlowe** [comment]
> we would have to disable pool allocation in tests to make cuda-memcheck work for leak checking.

Sure, but I don't see that as a blocker.  Should be straightforward to update the unit tests to use the pool allocator based on a cmake flag.  The nightly/weekly memcheck job can build with the cmake flag set appropriately.  Devs may also appreciate this flag if they want to run one or more unit tests under memcheck manually as part of their own testing before submitting a PR.

**Comment by jrhemstad** [comment]
> Should be straightforward to update the unit tests to use the pool allocator based on a cmake flag.

It doesn't even need to be a cmake flag. It's already possible to change the allocator via a command line argument to any test binary. 

https://github.com/rapidsai/cudf/blob/9e5196da813568450da1e4549b1baab2d54753dd/cpp/tests/utilities/base_fixture.hpp#L250-L268

**Comment by harrism** [comment]
Nice.

**Comment by karthikeyann** [comment]
C++ unit tests are running using `cuda-sanitizer --tool memcheck`
Python tests is not. We should reconsider this because python teests will take a lot more time to run using `cuda-sanitizer`.

**Comment by vyasr** [comment]
I agree that it will take longer, although I don't know what our constraints are when it comes to nightly builds. The Python tests almost certainly exhibit better code coverage than the C++ tests (especially of corner cases) so there would almost certainly be value in running those checks through `compute-sanitizer`. We would probably need to measure the runtime of the tests to determine whether the tradeoff is worthwhile, though.

**Comment by GregoryKimball** [comment]
How long do the Python tests take to run through `compute-sanitizer`?

**Comment by karthikeyann** [comment]
cudf pytest took 28m47s to run (1727s)
cudf pytest with compute-sanitizer ran (with errors), in 3h27m29s (12459s=7.2 times)

**Comment by karthikeyann** [comment]
Number of memcheck errors, runtime and the pytest file.
```
========= ERROR SUMMARY: 19 errors
real    0m36.259s
pytest python/cudf/cudf/tests/test_gpu_arrow_parser.py
========= ERROR SUMMARY: 81 errors
real    2m3.046s
pytest python/cudf/cudf/tests/test_csv.py
========= ERROR SUMMARY: 2 errors
real    0m14.351s
pytest python/cudf/cudf/tests/test_sparse_df.py
========= ERROR SUMMARY: 4 errors
real    10m46.758s
pytest python/cudf/cudf/tests/test_parquet.py
========= ERROR SUMMARY: 4 errors
real    1m8.669s
pytest python/cudf/cudf/tests/test_s3.py
========= ERROR SUMMARY: 4 errors
real    4m55.468s
pytest python/cudf/cudf/tests/test_orc.py
========= ERROR SUMMARY: 4 errors
real    0m36.796s
pytest python/cudf/cudf/tests/test_avro_reader_fastavro_integration.py
```

**Comment by GregoryKimball** [comment]
CUDA memcheck and compute sanitizer are running on the libcudf C++ tests as part of the nightly build, and all errors have been addressed. Future work with CUDA memcheck and compute sanitizer for the python tests will be tracked in #11194

**Comment by karthikeyann** [comment]
Leaving a comment here about runtime. Memcheck on GoogleTests took ~3 hours.
```
[32mgpuCI logger[0m » [12/16/2022 10:49:12] Googletests
[32mgpuCI logger[0m » [12/16/2022 10:58:54] Memcheck on GoogleTests with rmm_mode=cuda
[32mgpuCI logger[0m » [12/16/2022 14:08:44] Check conda packages
```
From last log in version 22.12
https://gpuci.gpuopenanalytics.com/job/rapidsai/job/gpuci/job/cudf/job/branches/job/cudf-gpu-build-branch-22.12/lastBuild/CUDA=11.5/
