### ISSUE TITLE
[BUG]value_counts return int type on empty columns

### ISSUE THREAD

**Issue by skmatti** [rapidsai/cudf#905]
Invoking value_counts on empty column returns int value(0) whereas pandas returns empty Series object.

```
import cudf
df = cudf.DataFrame({'x': [], 'y': []})
print(df.x.value_counts())
```
Result:
`0`

With pandas:
```
import pandas as pd
df = pd.DataFrame({'x': [], 'y': []})
print(df.x.value_counts())
```
Result:
`Series([], Name: x, dtype: int64)`

Environment details:
Python 3.6
cudf 0.5

**Comment by kkraus14** [comment]
Resolved by #917
