### ISSUE TITLE
[FEA] ZStandard codec support for ORC reader

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9057]
**Is your feature request related to a problem? Please describe.**
Some users have ORC data that uses the ZStandard compression codec rather than the standard Snappy codec. RAPIDS is unable to accelerate loading of these files due to the lack of support for this codec on ORC reads.

**Describe the solution you'd like**
The libcudf ORC reader should support loading ORC files that have been compressed with the ZStandard codec.

**Comment by jlowe** [comment]
Still desired.

**Comment by jlowe** [comment]
Still desired

**Comment by vuule** [comment]
Added in https://github.com/rapidsai/cudf/pull/10873
