### ISSUE TITLE
[FEA] Add Java bindings for CSV reading with `data_type` schema

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9062]
**Is your feature request related to a problem? Please describe.**
#8240 is removing the ability to specify data types for CSV reading as strings.  Currently the Java bindings for CSV reading only support passing strings for the data types.

**Describe the solution you'd like**
The Java bindings should add a `Table.readCSV` method that takes the data schema to read as an array of `DType` rather than strings.

**Comment by revans2** [comment]
I have a patch for this, but the last time I tried to do it I ran into some bugs. I will try to resurrect that patch and verify that the bugs have been fixed.

**Comment by revans2** [comment]
The bug I found is still open https://github.com/rapidsai/cudf/issues/8613 I'll see if it is still a problem/
