### ISSUE TITLE
[FEA] JNI support get map value for all value types and for all basic key types

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#9109]
**Is your feature request related to a problem? Please describe.**
We would like to be able to support getting map values on more than just string to string maps.  CUDF does not officially support maps and in JNI we have a stand alone special API just for string to string get map values.  This is to update that existing code unless we can add some list API operations to support it more generally.

**Describe the solution you'd like**
Update the existing JNI cudf code for get map values to be more generic. Longer term support more list operations so we can do this correctly.

**Describe alternatives you've considered**
It would be great to have a list_position. Which would return the position of the first element in a list that is equal to a value provided as either a scalar or a column vector.

We could then create map get from this by pulling out the keys from the map and calling list_position on it, and then pulling out the values list column and calling extract_list_element on it and the result of list_position.

**Comment by revans2** [comment]
We are exploring doing this a different way, but for now we still want it.

**Comment by revans2** [comment]
Same comment as before

**Comment by mythrocks** [comment]
I've bumped this to 22.04 for now.
Most of the machinery required to replace the current `map_lookup` kernel are in place. 
I'll post a separate PR for the `map_view` when viable. Once that's available, we can begin the assembly.
