### ISSUE TITLE
[FEA] Gather map complement for batched full join

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9114]
**Is your feature request related to a problem? Please describe.**
Currently the RAPIDS Accelerator only supports full joins if it pulls in the entire left and right tables before calling libcudf's full join API.  However this often leads to GPU out of memory errors which requires performing the join in batches on one side (e.g.: pulling in the entire right table but streaming through the left table in batches).  Performing a batched full join cannot be done via the libcudf API, but it can be done by treating it as a left outer join + right anti join.  For example, we could perform the following steps:
1. Build a `cudf::hash_table` with the entire right table
2. For each batch of the streamed left table, generate the left outer join gather maps
3. Emit the batch corresponding to the gather maps
4. Filter the right table's gather map to remove any invalid indices (e.g.: -1 to indicate no corresponding row) and cache it.
5. After all of the streamed left table batches have been processed, this completes the left outer join portion of the full join. 
 Now on to the steps to generate the right anti join without re-processing the left table again:
6. Concatenate all the cached and filtered right table gather maps
7. Remove all duplicates from the concatenated right gather map
8. Generate the gather map complement of the concatenated and filtered right gather map
9. Emit the batches corresponding to the right gather map complement using invalid entries for the left table
10. That completes the right anti join, and together all the emitted batches form the result of the full join

I think we have all the tools in libcudf to perform the above steps except the ability to generate a gather map complement.

**Describe the solution you'd like**
There should be a new API that looks something like this:
```
/**
 * Generates the complement of the given gather map for a table, i.e.: any row that is _not_ referenced in the original
 * gather map will be referenced in the resulting gather map.
 */
std::unique_ptr<rmm::device_uvector<cudf::size_type>> gather_map_complement(rmm::device_uvector<cudf::size_type> const &gather_map, cudf::size_type table_row_count);
```

**Describe alternatives you've considered**
We can discuss whether or not the new API will tolerate duplicates or require the caller to filter them first.  Similarly there may be a desire for the API to automatically filter negative indices in the original table.  These additions would allow the caller to simply concatenate the right table's gather maps from the series of left outer join calls, but doing so would increase memory pressure on the GPU if there are many duplicate entries from the right table during the series of left outer joins (i.e.: lots of -1 entries or join explodes and many duplicate rows in the right gather maps).

As such I'm thinking it would be better for the caller to filter out duplicates and invalid entries in the right gather maps before concatenating and generating the complement.  If the complement can be generated just as quickly with duplicate entries present in the input that's great, and maybe there's a use-case outside of joins where such a gather map complement API would be useful.

**Comment by revans2** [comment]
I have a few concerns.

1) From the algorithm described it sounds like the right side hash table needs to be alive even after we emit a batch of data for later processing.  If that is true we really should look into supporting being able to spill these hash tables.
2) We are going to have to support several operations on gather maps (filter for example).  CUDF does not currently support processing on gather maps that might be larger than the column size.  We can work around this by chunking it/etc but it is likely to get a little complicated.
3) The maximum amount of memory used is still going to be proportional to the entire right side table. It would be great to think about how we might be able to do this in a more distributed way. It might not actually matter in practice, but I know we can do a Left outer join and a right anti join in a distributed way, so what would it take to actually be able to do any sized full outer join without any issues.

**Comment by jlowe** [comment]
> From the algorithm described it sounds like the right side hash table needs to be alive even after we emit a batch of data for later processing.

It's not a requirement.  The only requirement is that the right-side table is available throughout the process, much like it is today for other batched joins that are right-side built.  It would be nice to be able to cache the right side hash table for efficiency, but we can free it in-between batches and regenerate it from the right table for each batch if it something that cannot be spilled.

> CUDF does not currently support processing on gather maps that might be larger than the column size. We can work around this by chunking it/etc but it is likely to get a little complicated.

Yes, I was assuming we would have to chunk in those cases.  Maybe that's an argument for either filtering directly in this new API. However if individual gather maps are already that big, not sure I want to concatenate them together first, since that's a very big allocation request for the concat result.  I suppose another alternative is new APIs that allow filtering/deduplicating of gather maps directly.

> It would be great to think about how we might be able to do this in a more distributed way. It might not actually matter in practice, but I know we can do a Left outer join and a right anti join in a distributed way, so what would it take to actually be able to do any sized full outer join without any issues.

Agree it would be interesting to consider another way to approach the join at a high level.  That's a discussion more appropriate in https://github.com/NVIDIA/spark-rapids/issues/3300 since it's outside the realm of libcudf.  libcudf is already generating gather map complements internally as part of its full join implementation, so this is mostly just requesting a public API to access it.

**Comment by jrhemstad** [comment]
> except the ability to generate a gather map complement.

I think this could be done as an anti-join of the gather map against a sequence `[0,n)`.

**Comment by jlowe** [comment]
> I think this could be done with existing public APIs as an anti-join of the gather map against a sequence [0,n).

One issue there is the gather map can be too big to manifest as a single column, a prerequisite for performing cudf operations on it.  If it's too big, we could chunk it with zero-copy column views, perform the anti-joins to get a series of gather maps, but then we need to remove duplicates from the resulting column maps.  Doing that is tricky if the concatenated gather maps are too large to manifest as a single cudf column.

libcudf is already computing the gather map compliment in `get_left_join_indices_complement`, and it would be great if we could expose that existing functionality.  I think that does what we need (i.e.: filtering -1 and ignoring duplicates) once we concatenate all of the right table gather maps from each left join batch.

**Comment by jrhemstad** [comment]
> One issue there is the gather map can be too big to manifest as a single column

Wouldn't a public version of `get_left_join_indices_complement` suffer from the same problem?

**Comment by jlowe** [comment]
> Wouldn't a public version of get_left_join_indices_complement suffer from the same problem?

Not if it took a gather map as an argument as it does today.

**Comment by jrhemstad** [comment]
> Not if it took a gather map as an argument as it does today.

Hm, that could be a slippery slope of bifurcating APIs that take a `column_view` vs. a `device_span`. I'm not opposed, but we should spend some time thinking/talking about it.

**Comment by jlowe** [comment]
Still desired.

**Comment by ttnghia** [comment]
@jlowe @jrhemstad I'm starting the implementation. Please have a look at the interface of the proposed API here and give comment if you have any: https://github.com/rapidsai/cudf/pull/9883

**Comment by jlowe** [comment]
Upon further discussion with @jrhemstad offline, I think we can perform the batched full join without needing to compute the complement for a gather map.  Ultimately what the original algorithm described above is trying to do is track which rows in the right table have not been "hit" as we perform the join against each batch of the left table.  Using gather maps to track the rows is inefficient for this, as gather maps can have duplicate entries and is using INT32 instead of a boolean.  And of course tracking the gather map is tracking which rows have been "hit", which means we need to compute the complement to know which rows were not "hit."

Instead of tracking gather maps, we can use a BOOL8 column, the same size as the right table, to track which columns have not been hit.  The algorithm would work like this:
1. Create a BOOL8 column, let's call it the tracking mask, which is the same size as the right table and initialized to all TRUE
2. For each batch of the left table:
    1.  Perform a left outer join with the right table to produce gather maps
    2. Filter the right table gather map to remove any invalid indices and then use the result as a scatter map to scatter a BOOL8 FALSE scalar into the tracking mask.
    2. Use the original gather maps from the left outer join on the left and right table to produce an output batch
3. After all batches of the left table have been processed, use the tracking mask to filter the right table via `apply_boolean_mask`.
4. Combine the filtered right table with null columns for the corresponding left table to emit a batch of all rows in the right table that did not match any rows in the left table.  At that point we've emitted batches that comprise a left outer join along with a batch for all rows in the right that didn't match any in the left, and together that forms the result of the full join.

With this approach we can avoid the complication of concatenating, de-duplicating, and complementing gather maps.  As such I'm going to close this feature request since we have a more efficient path forward that does not require any changes to libcudf.  We do need Java bindings for scatter which I'll be filing a tracking issue for shortly.

**Comment by ttnghia** [comment]
Yeah, that's very similar to my original idea of map complement with multiple input maps. I'm glad that you guys adopted to use it directly.
