### ISSUE TITLE
[FEA] Add nested struct support in serial hash functions

### ISSUE THREAD

**Issue by rwlee** [rapidsai/cudf#9119]
**Is your feature request related to a problem? Please describe.**
Supported nested structs in serial mumur3 and md5 hash functions.

**Describe the solution you'd like**
Add flattening with struct null pushdown in top level hash functions. Should be straightforward with proper flattening utilities.

**Describe alternatives you've considered**
Adding struct support as part of the type dispatch, but this approach would require recursion for nested structs. Flattening within that dispatch would also cause issues because the struct parent null pushdown would have to be done per row.

**Comment by GregoryKimball** [comment]
I believe this is closed by #11292, please feel free to reopen with an update.
