### ISSUE TITLE
[QST] Does cudf allow configuration of ORC stripe size

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#9126]
In Apache Hive and Apache Spark, you can control ORC stripe size with configurations:
[Hive example](https://community.cloudera.com/t5/Community-Articles/ORC-Creation-Best-Practices/ta-p/248963),  [Spark example](https://stackoverflow.com/questions/52075481/how-to-set-orc-stripe-size-in-spark).

Without control over size, I end up putting many rows with different column values in the same stripes, such that read filtering isn't able to be selective enough when reading from distributed storage (HDFS, or S3).

Looking at the to_orc API docs, I don't see a way to control this in cudf. Is there an environment configuration that exposes stripe size control?

**Comment by vuule** [comment]
Opened issue https://github.com/rapidsai/cudf/issues/9261

**Comment by vuule** [comment]
Closing since the feature request issue is created.
