### ISSUE TITLE
[BUG] DataFrame.from_records - TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#914]
**Describe the bug**
Hi,

I am trying to convert a **<class 'numpy.recarray'>** object to **cuDF.DataFrame,** but the following error is displayed:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-5-77b0c5038eae> in <module>
      3 print(type(temp))
      4 
----> 5 temp_df = cudf.DataFrame.from_records(temp)

/conda/envs/rapids/lib/python3.6/site-packages/cudf-0+unknown-py3.6-linux-x86_64.egg/cudf/dataframe/dataframe.py in from_records(self, data, index, columns, nan_as_null)
   1811         names = data.dtype.names if columns is None else columns
   1812         df = DataFrame()
-> 1813         for k in names:
   1814             # FIXME: unnecessary copy
   1815             df[k] = Series(np.ascontiguousarray(data[k]),

TypeError: 'NoneType' object is not iterable
```
Any idea why?

**Steps/Code to reproduce bug**
Please, have a look at the screenshot attached.
![2019-02-11 10_56_08-jupyterlab](https://user-images.githubusercontent.com/26169771/52559309-48047580-2df5-11e9-8f9a-1cf45afc3e2a.png)

**Expected behavior**

**Environment details (please complete the following information):**
I am using the latest RAPIDS container (0.5.1), on a DGX-1.

docker pull nvcr.io/nvidia/rapidsai/rapidsai:cuda10.0-runtime-ubuntu18.04
 

**Additional context**

**Comment by AK-ayush** [comment]
@miguelangel can you try again with cudf 0.6 or latest build? This is fixed now.
If it works, then please close the issue.

**Comment by miguelangel** [comment]
Hi,

It is working now. Apologies for the late response.

Thanks!

Miguel
