### ISSUE TITLE
[FEA] Provide shallow hash function for `column_view`

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9140]
**Is your feature request related to a problem? Please describe.**

I want to hash all of the "shallow" state of a `column_view` into a single value. 

**Describe the solution you'd like**

I would like a constant time hash function that hashes all of the shallow state of a `column_view` such that for two `column_view`s `a` and `b` then:
```
is_shallow_equal(a,b) => shallow_hash(a) == shallow_hash(b)
```

See also https://github.com/rapidsai/cudf/issues/9139

**Comment by karthikeyann** [comment]
Should `shallow_hash` be a public or detail or only in src/ ?

**Comment by jrhemstad** [comment]
`detail::` API.
