### ISSUE TITLE
[BUG] Unable to read parquet with cuDF which are written with ParquetWriter

### ISSUE THREAD

**Issue by bschifferer** [rapidsai/cudf#9216]
**Describe the bug**
I write multiple dataframes with ParquetWriter to a single parquet file. The reason is, that convert tfrecords to parquet files. tfrecords could be large to load all into memory. Therefore, I need to write it into chunks to a parquet file.
When I try to load the parquet file with cuDF, I get following error:

```
ValueError: Length mismatch: Expected axis has 20 elements, new values have 5 elements
```

However, I am able to read the same parquet file with pandas.

**Steps/Code to reproduce bug**
cudf version: '21.06.01+0.g101fc0fda4.dirty'

```
import cudf

from cudf.io.parquet import ParquetWriter

df = cudf.DataFrame({'col1': [0,1,2,3,4]})

w = ParquetWriter('test1' + ".parquet")
w.write_table(df)
w.write_table(df)
w.write_table(df)
w.write_table(df)
w.close()

df1 = cudf.read_parquet('test1.parquet')
```

**Comment by benfred** [comment]
I also see this on cudf v21.08.02

**Comment by devavret** [comment]
Seems to be a duplicate of #7011
