### ISSUE TITLE
[FEA] Add 'index_col' parameter to 'read_csv' method.

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#922]
**Is your feature request related to a problem? Please describe.**
When loading a csv file, the index is created automatically, not allowing me to select the index I would like to use.

As a workaround, I read the file, and the use the DataFrame.set_index() method to create a new DF with the correct index, but it is inefficient in terms of memory consumption. 

**Describe the solution you'd like**
Add 'index_col' parameter to  'read_csv' method.

**Describe alternatives you've considered**
(explained above)

**Additional context**
I noticed it when porting existing code to RAPIDS.

**Comment by kkraus14** [comment]
@mjsamoht this is purely on the Python side and involves calling `.set_index` on the dataframe object we create from from the `gdf_column` objects returned from the C++ API. If your team isn't clear on how to implement this, just let me know and I can help guide in the right direction.

**Comment by miguelangel** [comment]
I have just tested PR https://github.com/rapidsai/cudf/pull/995 and it seems to work. Thank you @kkraus14 !
