### ISSUE TITLE
[BUG] Mean Aggregation on decimal column yields a float64 column as result

### ISSUE THREAD

**Issue by kuhushukla** [rapidsai/cudf#9224]
**Describe the bug**
`mean()` aggregation for decimal seems to return a float64 column.

**Steps/Code to reproduce bug**
```  
@Test
  void testGroupByMeanDecimal() {
    try (Table t1 = new Table.TestBuilder()
        .column( "1",  "1", "1", "1")
        .column(0, 1, 3 , 3)
        .decimal64Column(4,
            123456L, 123456L, 123456L, 123456L)
        .build()) {
      try (Table result = t1
          .groupBy(GroupByOptions.builder()
              .withKeysSorted(true)
              .withKeysDescending(false, false)
              .build(), 0, 1)
          .aggregate(GroupByAggregation.mean().onColumn(2));
           Table expected = new Table.TestBuilder()
               .column( "1",  "1", "1")
               .column(   0,    1, 3)
               .decimal64Column(4,
                   123456L, 123456L, 123456L)
               .build()) {
        assertEquals(result.getColumn(2).getType(), expected.getColumn(2).getType());

      }
    }
  }
```
**Expected behavior**
Returned column type should be decimal.

**Comment by jrhemstad** [comment]
I suspect this is because `target_type_t` needs to be updated to use the same type as the input when the input type is `fixed_point`: https://github.com/rapidsai/cudf/blob/c6ddd46d4aa7b7c9914da29c89ad6a5ebde1c3bd/cpp/include/cudf/detail/aggregation/aggregation.hpp#L950-L966

**Comment by codereport** [comment]
groupby mean should not even be enabled at the moment. We blocked it for reductions and I thought that took care of groupby as well but that is not the case.
