### ISSUE TITLE
[BUG] Cannot build gcc

### ISSUE THREAD

**Issue by 4nanook** [rapidsai/cudf#9239]
**Describe the bug**
Trying to build on Ubuntu 21.04 based system, Intel i7-9700k CPU, getting the following error:

make: *** No rule to make target '../build-x86_64-linux-gnu/libiberty/libiberty.a', needed by 'build/genmodes'.  Stop.

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

git clone https://github.com/gcc-mirror/gcc.git
cd gcc
mkdir build
cd build
../gcc/configure -v --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --prefix=/usr/local/gcc-11.1.0 --enable-checking=release --enable-languages=c,c++,fortran --disable-multilib --program-suffix=-11.1
make -j8

**Expected behavior**

Expected it to go through the normal compile and bootstrap process.

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
     Bare metal, i7-9700k with 32G RAM clocked at 4.9Ghz with an Asus mainboard.  Ubuntu 21.04 installed.

 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

There is no cudf directory nor print_env.sh script included in the git clone code.

**Additional context**

**Comment by beckernick** [comment]
Hi @4nanook , from your description it looks like you're trying to build gcc and running into errors, rather than building cuDF. Are you experiencing an issue related to cuDF?

**Comment by 4nanook** [comment]
I apologize, I obviously was on the wrong github site, please feel free to delete this.
