### ISSUE TITLE
[DOC] Installation on AWS EC2 instance

### ISSUE THREAD

**Issue by Katsdog** [rapidsai/cudf#924]
## Report incorrect documentation
The instructions for installing cuDF via pip, conda, docker and from source posted on the RAPIDS AI website/ Github are very good. But the process must be slightly different for installing on an AWS EC2 instance. 
Many users will want to take advantage of Amazon EC2 instances in part because of multiple available GPUs.
Its very likely that cuDF's GPU powered dataframe operations paired with multiple GPUs will be often used by data people. 

**Describe the problems or issues found in the documentation**
The EC2 instance I'm using is Deep Learning AMI Ubuntu Version 21.0.

The pre-requisites of installing RAPIDS should already be satisfied: 
- Ubuntu version: 16.04
- CUDA version: 9.0, V 9.0.176 (returned when running `$ nvcc --version`)
-    This EC2 instance comes pre-loaded with CUDA 8.0, 9.0, 9.2 and 10.0.
- Python 3.6.5 :: Anaconda, Inc.

**Steps taken to verify documentation is incorrect**
Setting up cuDF on an EC2 instance will probably require additional steps judging from the inability to load the cuDF module after installation.

These are the steps to recreate the issue:
1. Start an AWC EC2 instance. I can walk you through it if necessary.
2. Linux console opens up with a message `Please use one of the following commands to start the required environment with the framework of your choice:`
Gives many options: Pytorch, Tensorflow. Should probably go with CUDA 9.0 by entering                                                            `source activate python3`.
3. `conda install -c nvidia -c rapidsai -c numba -c conda-forge -c defaults cudf`
4. `$ python -c "import cudf"` shows the error:
`OSError: cannot load library '/home/ubuntu/anaconda3/lib/librmm.so': libcudart.so.9.2: cannot open shared object file: No such file or directory`

So `import cudf` went looking for  `'libcudart.so.9.2` in `/home/ubuntu/anaconda3/lib/librmm.so`.

But when you enter `find / -name libcudart.so.9.2`, it gets found here: `found libcudart.so in` `usr/local/cuda-9.0/lib64/`

So when you do `conda install cuDF`, it installs in a place that different than it's supposed to be. Right?

## Report needed documentation
Could you please suggest a way to complete the installation in this environment. 
I can provide any needed environment/directory structure info. 

**Report needed documentation**
You can probably have a separate set of instructions for installation in this environment listed here: https://rapids.ai/start.html

**Steps taken to search for needed documentation**
I've noticed that other users were having similar issues that had been resolved by your team.
But I wasn't able to implement the solutions in the EC2 environment.
https://github.com/rapidsai/cudf/issues/441
https://github.com/rapidsai/cudf/issues/496

**Comment by Katsdog** [comment]
The issue was identical to #496.

Did this and everything worked:
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export PATH=/usr/local/cuda-10.0/bin${PATH:+:${PATH}}

**Comment by taureandyernv** [comment]
Ha...i was literally going to send you an update, but you figured it out.  Were you able to get the notebooks working?  That was where i was stuck and why it took me so long to get back to you.

**Comment by Katsdog** [comment]
At first I had a problem with the notebook because everything appeared as if the notebook was running on the EC2 instance but it was running locally. This is even after I set up a tunnel via PUTTY to go to a specific port. The trick was right clicking the top left corner of the linux terminal, going to settings and setting up the tunnel with the local port there. Really appreciate your help!

**Comment by AK-ayush** [comment]
Great!! @Katsdog 
 I can see that you have resolved your issue.
