### ISSUE TITLE
[DOC]  Subword tokenizer docs missing

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/cudf#9245]
## Report incorrect documentation
In the latest nightly docs we don't have link to  Subword tokenizer .  (See [link](https://docs.rapids.ai/api/cudf/stable/api.html#subwordtokenizer)) . We need to fix that. 

See below for missing link: 
![image](https://user-images.githubusercontent.com/4837571/133843753-a4d469f1-dcd0-4351-9146-9f29598a799c.png)

**Comment by galipremsagar** [comment]
Fixed by #9354
