### ISSUE TITLE
[FEA] Integrated Env/Version output for bug reports

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#931]
Currently, cudf suggests that users execute [print_env.sh](https://github.com/rapidsai/cudf/blob/branch-0.6/print_env.sh) to generate valuable info when submitting bug reports.  No doubt, this information is critical.  This style is also similar to how PyTorch and Tensorflow collect debug info.  While this is good, I think we could do better (for python cudf users) by integrating this functionality directly into cudf.  Doing this would simply the task for users (no script downloading) and it would also help in airgapped environments where pulling a script from the public github repo can be challenging.

@kkraus14 reminded me that `numba`  has a very simple UX to produce this output: `numba -s`.   Perhaps we could callout to that as numba is a dependency.  Thoughts?

**Comment by kkraus14** [comment]
I'd absolutely be in support of this, but it would be great to maintain a way of supporting non-Python users simultaneously.

**Comment by jrhemstad** [comment]
Can the script be distributed as part of the conda package?

**Comment by quasiben** [comment]
Yes, we could also do that.  Are libcudf users installing via conda ?

**Comment by jrhemstad** [comment]
> Yes, we could also do that. Are libcudf users installing via conda ?

If someone is using libcudf directly, then they're cloning the repo, in which case they automatically get the `print_env.sh` script.

**Comment by kkraus14** [comment]
> > Yes, we could also do that. Are libcudf users installing via conda ?
> 
> If someone is using libcudf directly, then they're cloning the repo, in which case they automatically get the `print_env.sh` script.

That's not necessarily true, libcudf is distributed as a conda package as well and would allow users who don't want to build from source to utilize it.

**Comment by jrhemstad** [comment]
> > > Yes, we could also do that. Are libcudf users installing via conda ?
> > 
> > 
> > If someone is using libcudf directly, then they're cloning the repo, in which case they automatically get the `print_env.sh` script.
> 
> That's not necessarily true, libcudf is distributed as a conda package as well and allows users who don't want to build from source to utilize it.

But that would be solved via my previous suggestion to just distribute `print_env.sh` via the conda package, yes?

**Comment by kkraus14** [comment]
> > > > Yes, we could also do that. Are libcudf users installing via conda ?
> > > 
> > > 
> > > If someone is using libcudf directly, then they're cloning the repo, in which case they automatically get the `print_env.sh` script.
> > 
> > 
> > That's not necessarily true, libcudf is distributed as a conda package as well and allows users who don't want to build from source to utilize it.
> 
> But that would be solved via my previous suggestion to just distribute `print_env.sh` via the conda package, yes?

I don't think the `print_env.sh` would be on their path and be callable by default similarly to `numba -s` for example unless we make some changes. I'd propose we put this into the `libcudf` conda package instead of the `cudf` conda package though.

**Comment by vyasr** [comment]
Closing in favor of #15609, which has more current discussion.
