### ISSUE TITLE
[BUG] Insert on concurrent_unordered_map for un-packable key-value pair type is broken

### ISSUE THREAD

**Issue by chirayuG-nvidia** [rapidsai/cudf#9317]
There is a race condition in `attempt_insert` function at https://github.com/rapidsai/cudf/blob/branch-21.12/cpp/src/hash/concurrent_unordered_map.cuh#L291 . Since `atomicCAS` (by Thread T1) updates the key of a location before the payload is assigned to the hash table, another thread (T2) which is trying to insert the same key gets `Sentinel` (unused value) payload values as it observes that Key is updated, however either the payload store instruction is not yet issued or the value is not updated across all caches.

A possible fix is to check the payload for sentinel value  when an `attempt_insert` returns that key already exists. A user supplied comparator can be used and `insert` can use strong load qualifier with sleep to get updated payload value before returning to thread T2.

Filing the bug for tracking and completeness sake, not sure if cuCollections will replace cuDF map implementation(s).

**Comment by vyasr** [comment]
We won't be fixing this in favor of #10401.
