### ISSUE TITLE
[QST] About ORC writer

### ISSUE THREAD

**Issue by firestarman** [rapidsai/cudf#9319]
**What is your question?**
What's the difference between [cudf_io::write_orc](https://github.com/rapidsai/cudf/blob/branch-21.12/cpp/tests/io/orc_test.cpp#L169) and [cudf_io::orc_chunked_writer](https://github.com/rapidsai/cudf/blob/branch-21.12/cpp/tests/io/orc_test.cpp#L634) ?
Do they both support decimal columns now ?

I saw this PR https://github.com/rapidsai/cudf/pull/8198 has added the decimal writing but seems only for the `cudf_io::write_orc`. Is it true?
If yes, any plan to let `cudf_io::orc_chunked_writer` also support decimals ?

Thanks in advance

**Comment by vuule** [comment]
@firestarman did I answer your question, can we close the issue?

**Comment by vuule** [comment]
Closing as inactive. Please reopen if needed.
