### ISSUE TITLE
[BUG] read_csv parses datetime64[ms] incorrectly

### ISSUE THREAD

**Issue by trstovall** [rapidsai/cudf#932]
**Describe the bug**
Datetimes with "YYYY-MM-DD HH:MM:SS.xxx" formats are incorrectly parsed, and parsed different depending on column index.

**Steps/Code to reproduce bug**
```
>>> from cudf import read_csv
>>> dt = '2016-04-30 04:26:40.000'
>>> with open('tmp.csv', 'w') as f:
...   f.write('{0},{0}\n'.format(dt))
... 
48
>>> print(read_csv('tmp.csv', names=['a','b'], dtype=['date','date']))
                        a                       b
0 2016-05-04T18:59:20.000 1969-12-31T23:59:59.000
>>> 
>>> with open('tmp.csv', 'w') as f:
...   f.write('0,{0},{0}\n'.format(dt))
... 
50
>>> print(read_csv('tmp.csv', names=['a','b','c'], dtype=['int32','date','date']))
     a                       b                       c
0    0 1969-12-31T23:59:59.000 1969-12-31T23:59:59.000
```

**Expected behavior**
Correct parsing of datetime regardless of column number

**Environment details (please complete the following information):**
 docker container "rapidsai/rapidsai:0.5-cuda10.0-base-ubuntu16.04-gcc5-py3.7"

**Comment by kkraus14** [comment]
cc @mjsamoht

**Comment by miguelangel** [comment]
I have found a similar behaviour. In my case, the date format is 'DD/MM/YYYY HH:MM:SS', and is always parsed to '1969-12-31T23:59:59.000'.

Please find attached an example of the dataset (only that column):

<img width="155" alt="screenshot 2019-02-13 at 22 25 22" src="https://user-images.githubusercontent.com/26169771/52745579-aee58280-2fdf-11e9-9e5a-990d08fd2097.png">

Below, you can observe the results when the file is loaded with Pandas:

![cpu](https://user-images.githubusercontent.com/26169771/52745615-c58bd980-2fdf-11e9-9451-4806279f7350.png)

And now, different tries that I have made usign cudf:

![cudf](https://user-images.githubusercontent.com/26169771/52745656-dccac700-2fdf-11e9-8cf7-156e9333940c.png)

Hope it helps!
Miguel

**Comment by j-ieong** [comment]
This is because it's not correctly handling the second-millisecond portion. I should have a quick fix

**Comment by miguelangel** [comment]
Hi @j-ieong, please notice that in my example there is no milisecond portion.

**Comment by j-ieong** [comment]
@miguelangel Can you give a sample row from your file so I can see the format? Thanks!
