### ISSUE TITLE
[BUG] Null Handling in `where`

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#9328]
Null handling in `where` does not reflect Pandas Null handling:

```python
In [20]: sr = pd.Series([0, 1, 2, None])

In [21]: sr.where(~(sr > 1), -1)
Out[21]:
0    0.0
1    1.0
2   -1.0
3    NaN
dtype: float64

In [22]: sr = cudf.Series([0, 1, 2, None])

In [23]: sr.where(~(sr > 1), -1)
Out[23]:
0    0
1    1
2   -1
3   -1
dtype: int64
```

In the above `Nan` is always treat as a value less than any int/float, etc. 

cc @randerzander

**Comment by beckernick** [comment]
This feels like a nullable dtype discrepancy or perhaps pandas/our documentation is in need of an update? 

[pd.Series.where](https://pandas.pydata.org/docs/reference/api/pandas.Series.where.html)
> Where cond is True, keep the original value. Where False, replace with corresponding value from other. 

`~(sr > 1)` should resolve to `[True, True, False, NA]` in cuDF and in pandas with nullable types. Without nullable types, we should get `[True, True, False, True]` and thus keep the Nan. 

If `sr.where` only replaces where the mask is False, this may be behaving as intended?

**Comment by charlesbluca** [comment]
Looks like you were correct @beckernick; the nulls are replaced after a call to `cudf._lib.copying.copy_if_else`, and looking at the docstring over in the header file:

https://github.com/rapidsai/cudf/blob/fd0b71089627b4ddcc7ccbbdde84a4371916e3da/cpp/include/cudf/copying.hpp#L769-L770

A simple workaround here would be to simply assign `None` to the null values of the `copy_if_else` result immediately afterwards, though I'm interested in why this is the behavior in libcudf, and if it would be better to implement this fix there.

**Comment by brandon-b-miller** [comment]
We're equivalent to pandas nullable types here:
```
sr = pd.Series([0, 1, 2, None], dtype='Int64')
>>> sr
0       0
1       1
2       2
3    <NA>
dtype: Int64
>>> sr.where(~(sr > 1), -1)
0     0
1     1
2    -1
3    -1
dtype: Int64
```

**Comment by brandon-b-miller** [comment]
Yes - I think that is what is happening. `sr` is different, I think `where` is consistent. I'm not quite sure what to do about this yet but will spend some cycles thinking about it today.

**Comment by quasiben** [comment]
Thanks for jumping in @charlesbluca and @brandon-b-miller . A doc update might be the resolution here
