### ISSUE TITLE
[FEA] Need java bindings changes to support row to column changes

### ISSUE THREAD

**Issue by hyperbolic2346** [rapidsai/cudf#9361]
**Is your feature request related to a problem? Please describe.**
CUDF currently has a single row to column and column to row conversion API. This code handles fixed-width tables with limitations on row size. A new API is being created that will handle larger tables and, eventually, variable-width data.

**Describe the solution you'd like**
This new API might be slower than the existing conversion code due to the limitations allowing for optimizations that can not be assumed by the new API. As a result, the code calling this API would need to make a decision of which API to use. The small-row code will be renamed from `convert_to_rows` and `convert_from_rows` to `convert_to_rows_fixed_width_optimized` and `convert_from_rows_fixed_width_optimized`. The new API will be named `convert_to_rows` and `convert_from_rows`. Currently there is a decision to call this API or use the CPU to convert the data based on size. This feature would add a third case to call the new API.

**Additional context**
This code will depend on https://github.com/rapidsai/cudf/pull/8444

**Comment by chenrui17** [comment]
so if this pr is finished, we can handle variable-width data, like string type column to convert from row to column or from column to row, right ? and when will it be finished ?

**Comment by hyperbolic2346** [comment]
The first stage of this code, which is this PR, does not support variable-width data. That is scheduled for a later PR. Strings will be the first supported after some performance improvements are made to this code.

**Comment by chenrui17** [comment]
@hyperbolic2346  so , for string type , how we  convert column2row or row2column in gpu? because string type data width is not fixed, please give me some idea. thanks a lot.

**Comment by hyperbolic2346** [comment]
@chenrui17 Right now we do not support string conversions on GPU. If there is variable-width data, the table will not be converted on the GPU.

**Comment by razajafri** [comment]
This is still valid and actively being worked on

**Comment by razajafri** [comment]
@hyperbolic2346 is this done now?

**Comment by razajafri** [comment]
closed as part of https://github.com/rapidsai/cudf/pull/8444
