### ISSUE TITLE
[QST] Dictionary like operation

### ISSUE THREAD

**Issue by eyalhir74** [rapidsai/cudf#9371]
Say I have an array in python of strings and a matching integer values for each string.
Is there a simple way to give this dictonary as input, an additional vector of requested strings to look for in this dictionary and get the appropriate values for each of these input strings? on the GPU?

thanks

**Comment by beckernick** [comment]
Hi @eyalhir74 , is this a question related to cuDF? It sounds like you might be looking for key-value pair data structures on the GPU. You may be interested in https://github.com/NVIDIA/cuCollections

For better support from the community, please include some sample code using cuDF, pandas, or Dask to describe what you're trying to accomplish.

**Comment by harrism** [comment]
@beckernick cuCollections is a C++ library, but @eyalhir74 mentions Python.

**Comment by eyalhir74** [comment]
@beckernick @harrism
Basically I am looking to replace the HashLookup component in TensorFlow. Currenlty 50% of our training is CPU bound because this lookup is done on the CPU and NOT the GPU. 
So I thought I could replace it with a Python equivalent..

However, looking at this again, seems in order to write a custom TF op, I would have to do it in C++ anyway.
I am also not sure if this effort would pay off, performance wise, i.e. : 
- write a custom OP
- move ~a few MB of strings input from python to C++
- copy it to the GPU
- do a ~500 * 1000 strings lookup on the GPU
- copy results back from GPU to CPU and from C++ back to Python (TF op)

Any thoughts would be greatly appereciated 
Thanks

**Comment by jrhemstad** [comment]
Could you cast your problem as a pandas join/merge? cuDF's merge implementation uses a hash-based join.

**Comment by shwina** [comment]
Indeed, lookup problems like this can be cast as merges. In cuDF, for example, the Pandas `loc` method is built around a merge, which in turn, uses a GPU-based hash table:

```python
In [17]: df = cudf.DataFrame({'a': [1, 2, 3, 4], 'b': ['x', 'y', 'z', 'w']}, index=["cat", "dog", "swallow", "lynx"])

In [18]: df
Out[18]:
         a  b
cat      1  x
dog      2  y
swallow  3  z
lynx     4  w

In [19]: df.loc[['cat', 'swallow', 'lynx']]
Out[19]:
         a  b
cat      1  x
swallow  3  z
lynx     4  w
```

**Comment by eyalhir74** [comment]
@shwina @harrism @jrhemstad 
Thanks a lot guys. Looks promising, though I will have to go to C++ to incorpate this in TF (if I am not mistaken)
A followup question please. Attached is a NVPROF screen shot of a big lookup I do in production.

The "lookup_strings" and "lookup_strings1" ranges are the actuall call to df.loc
I was wondering why ~50% of this operation doesn't show GPU work?

There's an additional huge "DATAFRAME_INIT" range at startup, which seems to happen only once per session, is that right?

![Screenshot from 2021-10-07 10-25-53](https://user-images.githubusercontent.com/2410527/136339295-448f965d-6254-42d7-a188-d97589994404.png)
