### ISSUE TITLE
[FEA] Add Doxygen CI check 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9373]
**Is your feature request related to a problem? Please describe.**

As https://github.com/rapidsai/cudf/pull/9355 shows, Doxygen documentation can easily get out of date. 

No one likes out of date documentation. This leads to a bad experience for users and developers alike. 

**Describe the solution you'd like**

Doxygen will generate warnings if the documentation does not match the code.

We should eliminate all current sources of warnings and then enable these warnings as a CI check to ensure Doxygen documentation stays up to date. 

**Additional context**

This check should probably be optional at the beginning, but eventually should be required.

**Comment by davidwendt** [comment]
https://github.com/rapidsai/cudf/pull/9355#issuecomment-934745941

**Comment by karthikeyann** [comment]
Number of warnings in Doxygen are high.
To get opinion, 
some of trivial functions without documentation are `operator<`, `operator=`, has_nulls, begin, end, etc.
Should they be skipped or warning ignored or documented? (documentation for method, parameters and return type)

**Comment by harrism** [comment]
Seems to me that public APIs should be documented. For detail APIs, we definitely have the option to skip.  Is there any way to auto-generate docs for standard functions like `operator<`, `operator=`?

**Comment by karthikeyann** [comment]
>  Is there any way to auto-generate docs for standard functions like operator<, operator=?

[CUB uses ALIASES](https://github.com/karthikeyann/cub/blob/fea-docs_doxygen/docs/Doxyfile#L193-L230). we could add aliases for these operators for ease the effort.

Another idea is to add custom filter command `INPUT_FILTER`. 
I tested a simple example, for `operator=` as follows. 
- created `filter.sh` with content `sed 's/^.* operator=(/\/** @brief assignment operator. @returns reference to object **\/ \0/g' $@`
- set `INPUT_FILTER = /path/to/filter.sh` in Doxyfile.
All warnings related to `operator=` are gone. 

how about we implement an input filter?
Note: As stated in https://www.doxygen.nl/manual/config.html#cfg_input_filter, we cannot insert or remove new lines.
> Note that the filter must not add or remove lines; it is applied before the code is scanned, but not when the output code is generated. If lines are added or removed, the anchors will not be placed correctly.

**Comment by harrism** [comment]
Can the input filter only be applied to undocumented functions? Wouldn't want to overwrite existing ones.

Is there much value in doing it this way rather than fixing it once, manually? (Or running an automated fix just once)  This would only fix the operators that we write the script to fix, and is only needed on public APIs.  Does that account for a large fraction of the errors / warnings?

**Comment by karthikeyann** [comment]
input filter processes the entire file.
Tunning an automated or manual fix once is preferred.

The warnings are distributed among 67 files. 1483 warnings.
Here are the files with most warnings.
- 293 warnings from cudf/io/ 
- column, scalar, table
- strings, lists
- utilities, cudf_test
