### ISSUE TITLE
[FEA] Document cuDF allocation alignment/padding requirements

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9389]
**Is your feature request related to a problem? Please describe.**

cuDF informally states that we follow the Arrow physical memory layout spec. However, we're a little loose on some of the particulars, especially around alignment/padding.

Arrow[ *requires* ](https://wesm.github.io/arrow-site-test/format/Layout.html#requirements-goals-and-non-goals)all allocations be 8B aligned and padded to 8B sizes. It *recommends* expanding this to 64B aligned and 64B padded. 

cuDF isn't (formally) following this. Implicitly, we know all allocations made through RMM will be 256B aligned. As it happens, RMM will currently pad out to 8B [(though it shouldn't do that) ](https://github.com/rapidsai/rmm/issues/865). However, due to zero-copy slicing, we can't assume `column.data<T>()` pointer will be 256B aligned, and can only expect the pointer alignment to be at least `alignof(T)`. 

Specifically for null masks, we expect/[allocate](https://github.com/rapidsai/cudf/blob/1424a2dfce0f1015675cde82e9bef69533d1ada5/cpp/include/cudf/null_mask.hpp#L44-L57) the null mask of a column to always be padded to 64B. 

**Describe the solution you'd like**

At the very least, we should write down our current expectations. These requirements can be best captured in requirements of the `column_view` class, as `column_view` is the arbiter of how we interact will all memory consumed by libcudf. 

- `data` must be aligned to at least the alignment of the underlying type
- It must be safe to dereference any address in the range `[data, data + num_elements * size_of(data_type))` 
   - **Note**: This is currently incompatible with the Arrow spec. e.g., libcudf would currently allow an `INT8` allocation to be any size, whereas Arrow would require it to be padded to a multiple of 8 bytes. 
- `null_mask` must be aligned to `alignof(bitmask_type)`
- `null_mask` must point to an allocation padded to a multiple of 64 bytes such that it is safe to dereference any address in the range `[null_mask, null_mask + bitmask_allocation_size_bytes(num_elements))`

Additionally, we should consider expanding the requirement for allocation padding to make it such that _all_ allocations be padded out to 64B. This could be achieved easily enough with a `device_memory_resource` adapter that rounds allocations up to at least 64B. 

**Additional Considerations**

As best I can tell, these requirements are technically incompatible with the [CUDA Array Interface](https://numba.pydata.org/numba-doc/dev/cuda/cuda_array_interface.html) because the CAI doesn't say _anything_ about padding/alignment. This seems like something we should push to be addressed in the CAI.

**Comment by shwina** [comment]
cc: @gmarkall @leofang @jakirkham for thoughts on:

> As best I can tell, these requirements are technically incompatible with the CUDA Array Interface because the CAI doesn't say anything about padding/alignment. This seems like something we should push to be addressed in the CAI.

**Comment by kkraus14** [comment]
> This will result in poorly performing code in a lot of cases where we zero copy at the moment. For example, slices

Yes, if we require a 64B padded allocation that would be the case. Alternatively we'd have to do a bunch of non-trivial work and add complexity into `__cuda_array_interface__` to describe the underlying memory allocation in addition to the relevant data.

**Comment by kkraus14** [comment]
I just realized that dlpack spec does indicate that pointers should be 256 byte aligned, but I'm not sure if we're following that properly. Doesn't look like CuPy follows this as expected for sliced arrays either:
```
import cupy

test_base = cupy.array([1, 2, 3, 4, 5])
test_sliced = test_base[2:]

test_dlpack_base = test_base.toDlpack()
test_dlpack_sliced = test_sliced.toDlpack()

output_base = cupy.fromDlpack(test_dlpack_base)
output_sliced = cupy.fromDlpack(test_dlpack_sliced)

print("Base dlpack pointer is 256 byte aligned?", (output_base.data.ptr % 256) == 0)  # True
print("Sliced dlpack pointer is 256 byte aligned?", (output_sliced.data.ptr % 256) == 0)  # False
```

**Comment by kkraus14** [comment]
cc @leofang ⬆️

**Comment by jrhemstad** [comment]
There's no way to make an arbitrarily sliced array be 256B aligned.

The Arrow spec states that _allocations_ should be 8B (64B) aligned, but not that every pointer (e.g., for a sliced/offset array) must have such alignment.

**Comment by vyasr** [comment]
Based on recent discussions on this issue, Arrow's padding requirements are actually far less strict than we thought. 64 byte padding is recommended solely for the usual performance reasons (e.g. ability to use vector instructions), and 8 byte padding is only required at the level of IPC packets (which cudf does not currently support) and not individual columns. For a comprehensive summary on our discussions, see https://github.com/rapidsai/rmm/issues/865#issuecomment-1517028971.

With that in mind, I think we can close this issue since there are no alignment/padding requirements to be documented here. @jrhemstad please reopen if you think there is still some action to be taken on this issue.
