### ISSUE TITLE
missing: cuFile_LIBRARY cuFileRDMA_LIBRARY cuFile_INCLUDE_DIR

### ISSUE THREAD

**Issue by pedronahum** [rapidsai/cudf#9401]
Hi,

I am trying to build the C++ library from source using cuda 11.2 / gcc 9.4 / Ubuntu 18.04 / Driver Version: 470.74. However, it seems that a dependency is missing. In particular, I get the following error:

Could NOT find cuFile (missing: cuFile_LIBRARY cuFileRDMA_LIBRARY cuFile_INCLUDE_DIR) 

Is there a way to obtain this library for Cuda 11.2? Cuda 11.4 seems to include GDS, but I havent managed to find this library for Cuda 11.2. Any pointer here is appreciated. 

Best,

**Comment by pedronahum** [comment]
Hi @beckernick. Deeply sorry, yesterday evening I upgraded my distribution to Ubuntu 20.04 and cannot reproduce the error.

fyi, it seems that aws-sdk-cpp is required, as the build will fail if a header file (ie, aws/core/Aws.h) from this library is not found. After installing this sdk, I managed to build the cudf library. 

Best,

**Comment by vyasr** [comment]
@Atharex cuFile is a part of the CTK since CUDA 11.4. If you have a sufficiently new CTK it will be present. Building libcudf now requires CUDA>=11.5, so if you can build the latest versions of cudf you should automatically have cuFile available.
