### ISSUE TITLE
[BUG] custreamz fails to connect to kafka with oauth login

### ISSUE THREAD

**Issue by pthalasta** [rapidsai/cudf#9410]
**Describe the bug**
custreamz does not work with kafka oauth configs due to Kafka data source object has a parameter kafka_config of type `map[string string]`. However, confluent kafka can take `'oauth_cb': functools.partial(function)` to get token from the server to connect to Kafka broker.

https://github.com/rapidsai/cudf/blob/branch-21.10/python/custreamz/custreamz/kafka.py#L30
https://github.com/rapidsai/cudf/blob/branch-21.10/python/cudf_kafka/cudf_kafka/_lib/kafka.pxd#L21

librdkafka's example link: https://github.com/confluentinc/confluent-kafka-python/blob/master/examples/oauth_producer.py

**Steps/Code to reproduce bug**
Can be replicated by trying to connect to Kafka broker with oauth 

**Expected behavior**
https://github.com/rapidsai/cudf/blob/branch-21.10/python/custreamz/custreamz/kafka.py#L30 should be changed to accept a config of type `map[string,object]` 

**Environment overview (please complete the following information)**
 - Environment location: all
 - Method of cuDF install: conda but shouldn't matter

**Comment by jdye64** [comment]
PR https://github.com/rapidsai/cudf/pull/9486 should be merged in the coming days to resolve this issue.
