### ISSUE TITLE
[FEA] `drop_duplicates` and `distinct_count` behavior/implementation is very inefficient 

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9413]
**Is your feature request related to a problem? Please describe.**

https://github.com/rapidsai/cudf/issues/9411 made me take a closer look at [`cudf::drop_duplicates`](https://github.com/rapidsai/cudf/blob/27184431443fad3207590a10d9e32144d7c4c827/cpp/include/cudf/stream_compaction.hpp#L238) and [`cudf::distinct_count`](https://github.com/rapidsai/cudf/blob/27184431443fad3207590a10d9e32144d7c4c827/cpp/include/cudf/stream_compaction.hpp#L262). 

Unlike `std::unique`, both of these APIs will drop/count _all_ unique rows across the entire table (as opposed to only contiguous equivalent rows). 

On the surface, this seems convenient for a user because they don't have to worry about sorting their dataframe if they want to get only the unique rows. However, it has an insidious impact on performance.

Imagine if you were to call `distinct_count` and then `drop_duplicates`. The way these functions are currently implemented, they _both_ require doing a sort of the inputs. 

Instead, if `distinct_count` and `drop_duplicates` worked like `std::unique` and the user had to first sort the input, then only _one_ sort would be needed. Alternatively, the data may _already_ be sorted (as is the case with Python indexes), where _no_ sort would be necessary.

The current behavior is very sub-optimal for performance as it can require 2 redundant multi-column sorts. Multi-column sorts are among the most expensive operations in libcudf, so this is a _bad thing_. 

(Furthermore, if the data isn't already sorted, using a sort-based implementation is likely to be much slower than a hash-based implementation, so we should look at refactoring these implementations). 

**Describe the solution you'd like**

I'd like to do two things:

1. Update `drop_duplicates/distinct_count` to work like `std::unique`, i.e., it only considers contiguous equivalent elements.
   - This would require the data be presorted to preserve the existing behavior. Note that this also requires the user to describe _how_ the data is sorted for things like null_order and such. We can look at [`groupby`](https://github.com/rapidsai/cudf/blob/e6caaf55dd38b08e2fd7eab70feb36d526d52163/cpp/include/cudf/groupby.hpp#L127-L129) for an example of how we've handled this there. 
2. Add `unordered_drop_duplicates` and `unordered_distinct_count` that behave like the current APIs.
   - We should look at using a hash-based implementation for the `unordered_*` algorithms as it will likely be much faster  

**Describe alternatives you've considered**

> Why not preserve the existing APIs and add `ordered_drop_duplicates` and `ordered_distinct_count`?

While this is certainly an option, I think that the behavior I described above would be more canonical for C++. 

> Why have both `unordered_*` and ordered versions?

If the data is already sorted, there's a good chance a sort based implementation could be faster than hash-based, but we can test that and see.

**Comment by harrism** [comment]
Why not rename the new ordered version of `drop_duplicates` to `cudf::unique`?

**Comment by harrism** [comment]
Just for reference in thinking about naming and semantics, I also note that `std` (our eternal inspiration) does not have a `unique_count`. Typical approaches to implementing it:

1. 
```
std::vector<int> v{...};
int unique_count = std::set<int>(v.begin(), v.end()).size();
```
2. 
```
std::vector<int> v{...};
std::sort(v.begin(), v.end());
int unique_count = std::unique(v.begin(), v.end()) - v.begin();
```

I think we discussed this in the past, and decided that due to the costs of materializing columns / tables, it's better to provide an algorithm that actually counts the unique items with a scan than to require the user to build their own as in method 2. The hashing approach you mention would be similar to approach 1 and probably would be faster in a lot of not pre-sorted cases.

I can't remember why we decided to call it `distinct_count` instead of `unique_count`. I bet @codereport was involved or would have an opinion on the naming!

**Comment by harrism** [comment]
> I think it was actually called unique_count at one point and I pointed out that "unique" has semantics in C++ that didn't align with what the libcudf algorithm was doing. So we ended up changing it to distinct_count as "distinct" doesn't have any specific C++ semantics.

But now Jake is suggesting changing the non-ordering semantics to match `std::unique`. Are there other semantics that should stop us using that name?

**Comment by jrhemstad** [comment]
> Given the Python observation, why not call `cudf::drop_duplicates` just `cudf::unique()` to match both STL and Pandas and have it be unordered? Users need to sort first if they want it ordered.

But the behavior of `std::unique` doesn't match Pandas `unique`. If we go with the `unique/unordered_unique` naming, Pandas would use the `unordered_unique`.

**Comment by harrism** [comment]
Hmmm, perhaps I misunderstood @shwina 's message.

What does Pandas unique return for [4, 4, 0, 1, 2, 2, 4, 4]?   std:unique would return [4, 0, 1, 2, 4].

**Comment by ttnghia** [comment]
> As a promising anecdote, @gaohao95 has already experimented with a hash-based solution of `drop_duplicates` with [cuCollections](https://github.com/NVIDIA/cuCollections) and reports it's 100x faster than the current sort-based solution.

@jrhemstad Is there any draft PR yet? I am implementing `cudf::contains` for structs and have similar need for structs hashing.
