### ISSUE TITLE
[FEA] Add API for generating per-list sequences 

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#9424]
**Is your feature request related to a problem? Please describe.**
Could we support sequence on columns?

## input

| start | end | step |
| --- | --- | --- |
| 0  |  5  |  1 |
| -2 | 2 | 2 |
| -3 | 3 | 1 |

## output

| start | end | step | sequence(start, end, step)  |
| --- | --- | --- | --- |
| 0  |  5  |  1 |  [0, 1, 2, 3, 4, 5] |
| -2 | 2 | 2 | [-2, 0, 2] |
| -3 | 3 | 1 | [-3, -2, -1, 0, 1, 2, 3]

**Comment by beckernick** [comment]
Perhaps https://github.com/rapidsai/cudf/pull/8886 is relevant for the timestamp sequence?
