### ISSUE TITLE
[BUG] String match returns incorrect result in some cases

### ISSUE THREAD

**Issue by ayushdg** [rapidsai/cudf#9434]
**Describe the bug**
`series.str.match` returns incorrect results in the case of some regular expressions. 

**Steps/Code to reproduce bug**
```python
import cudf

regex = "^\\^|()\\-*\\[\\]\\$$"
pdf = pd.DataFrame({"a": ["a normal string", "%_%", "^|()-*[]$"]})
df = cudf.from_pandas(pdf)

print(df.a.str.match(regex))
```
```
0    True
1    True
2    True
Name: a, dtype: bool
```

**Expected behavior**
In the above example
```python
print(pdf.a.str.match(regex))
```
```
0    False
1    False
2     True
Name: a, dtype: bool
```
**Environment overview (please complete the following information)**
 - Environment location: Bare-metal
 - Method of cuDF install: conda
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
Came up while adding gpu tests for string functionality in dask-sql: https://github.com/dask-contrib/dask-sql/pull/256

**Comment by davidwendt** [comment]
It looks like there are a lot of unescaped regex characters in the pattern that may be confusing the code. Here is the documentation that includes the meaning for the [special regex characters](https://docs.rapids.ai/api/libcudf/stable/md_regex.html). Looks like if you escape them all, you will get the correct result.

```
import cudf
regex = "^\\^\\|\\(\\)\\-\\*\\[\\]\\$$"
s = cudf.Series(["a normal string", "%_%", "^|()-*[]$"])
print(s.str.match(regex))

0    False
1    False
2     True
dtype: bool
```

**Comment by ayushdg** [comment]
Thanks for the context and link. 
Are the regex rules for cudf string pattern matching slightly different than the standard python regex rules? (In terms of requiring to escape certain chars)

Trying to evaluate if dask-sql will need a special case to handle regexes differently for gpu dataframes vs pandas df's.

**Comment by davidwendt** [comment]
I would expect that all regex characters would need to be escaped if they are to be matched literally in a target string. Perhaps python has done some work to guess when the escape was intended? I don't have a clue how they would know to do that.

**Comment by andygrove** [comment]
I am also running into this issue. Here is one example:

## Python

```python
>>> pattern = re.compile('a[-+]')
>>> values = ['a-', 'a+', 'a']
>>> [pattern.search(x) for x in values]
[<re.Match object; span=(0, 2), match='a-'>, <re.Match object; span=(0, 2), match='a+'>, None]
>>> 
```

## cuDF with escaping (correct results)

```python
>>> cudf.Series(['a+', 'a-', 'a']).str.contains('a[\-\+]', regex=True)
0     True
1     True
2    False
dtype: bool
```

## cuDF without escaping

```python
>>> cudf.Series(['a+', 'a-', 'a']).str.contains('a[-+]', regex=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andy/miniconda3/envs/rapids-21.10/lib/python3.7/site-packages/cudf/core/column/string.py", line 743, in contains
    result_col = libstrings.contains_re(self._column, pat)
  File "cudf/_lib/strings/contains.pyx", line 29, in cudf._lib.strings.contains.contains_re
RuntimeError: cuDF failure at: ../src/strings/regex/regcomp.cpp:397: invalid regex pattern: nothing to repeat at position 3
```
