### ISSUE TITLE
[QST]Performance about read_parquet

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#9466]
**What is your question?**
i use cudf `read_parquet` cpp API and some other data process api , and read remote hdfs file and do some data process, and it's performance is not very good, and gpu util is very slow, according to the nsight system, read data from Host to device cost too much time ,and it's likely it called `cudaMemcpyAsync` many times, and every time it only transfer a little data, and how to solve this problem and improve it's performance.
one parquet file data size: 400MB
column num : 100
select column num : 60
![image](https://user-images.githubusercontent.com/33319780/137919747-d3546a92-0a85-4dde-a782-37e91437f7f1.png)

**Comment by quasiben** [comment]
How is your application reading from hdfs ?  Are you buffering data on the host machine or reading each individual chunk directly onto the device?

**Comment by devavret** [comment]
@chenrui17 can you post the result of reading all 100 columns in `read_parquet` and then discard the unneeded ones after reading. This is **NOT** a recommendation, just an experiment.

**Comment by GregoryKimball** [comment]
Thank you @chenrui17 for your question about parquet performance. We frequently find that the time to copy data from host to device is longer than the time needed to decompress and decode the data. Please feel free to open a follow-up issue if you would like to continue studying read_parquet performance with us.
