### ISSUE TITLE
[BUG] Add fixed point to AllTypes in libcudf unit tests

### ISSUE THREAD

**Issue by karthikeyann** [rapidsai/cudf#9468]
**Describe the bug**
Fixed point types are missing in `cudf::tests::AllTypes`.
`AllTypes` is not all types. It includes only non-compound types.

**Expected behavior**
AllTypes should include fixed point types and fix failing compilation and unit tests.

Tests fails to compile:
- [x] ITERATOR_TEST
- [x] REDUCTION_TEST
These fail due to fixed point scalar and device scalar defined differently from other scalars.

unit test run fails
- [ ] QUANTILES_TEST #9469

**Comment by codereport** [comment]
Closing as https://github.com/rapidsai/cudf/pull/9472 has been merged.
