### ISSUE TITLE
[BUG] cudf uses deprecated `Series.label_encoding` function internally

### ISSUE THREAD

**Issue by vyasr** [rapidsai/cudf#9474]
There are multiple places where cuDF internally calls the `Series.label_encoding` method, which was deprecated in #9289:
- https://github.com/rapidsai/cudf/blob/branch-21.12/python/cudf/cudf/core/column/column.py#L968
- https://github.com/rapidsai/cudf/blob/branch-21.12/python/cudf/cudf/core/algorithms.py#L62
- https://github.com/rapidsai/cudf/blob/branch-21.12/python/cudf/cudf/core/dataframe.py#L3248
Note that the latter is the `DataFrame` implementation of `label_encoding`.

The first two should be rewritten to not use the deprecated function, while the third should also be deprecated.

**Comment by shwina** [comment]
Closing this as it looks like #9535 addressed it. Please feel free to reopen if I missed something.

**Comment by vyasr** [comment]
This isn't quite addressed yet because the three internal uses of the now-internal `Series._label_encoding` are still present. #9535 simply added an extra level of indirection so that those would not also throw warnings because those functions are not deprecated but they were relying on the now-deprecated `label_encoding` function. I'm removing `DataFrame.label_encoding` now, which addresses one of the uses documented in this issue, but we still need to investigate the other two.
