### ISSUE TITLE
[FEA] Add binary operations to 'DatetimeColumn' object

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#948]
**Is your feature request related to a problem? Please describe.**
I am trying to calculate the timestep by substracting end_date and start_date.

Please, find below the code and the error raised:

<img width="1350" alt="screenshot 2019-02-14 at 14 35 39" src="https://user-images.githubusercontent.com/26169771/52790212-4beafe80-3066-11e9-96b2-8304aa2b9ae3.png">

**Describe the solution you'd like**
To be able to substract two columns of type 'numpy.datetime64'.

**Describe alternatives you've considered**
None yet.

**Additional context**
Add any other context, code examples, or references to existing implementations about the feature request here.

**Comment by thomcom** [comment]
Your shortest path solution is to convert the datetime columns into integer columns, do your arithmetic, and convert them back. I'm pretty sure that the base type for datetime is a UNIX time. Either that or a datetime string ('m not sure), but either way if you get the datetime to become a UNIX timestamp then you can arithmetic it.

**Comment by kkraus14** [comment]
> Your shortest path solution is to convert the datetime columns into integer columns, do your arithmetic, and convert them back. I'm pretty sure that the base type for datetime is a UNIX time. Either that or a datetime string ('m not sure), but either way if you get the datetime to become a UNIX timestamp then you can arithmetic it.

Converting to an `int64` should be a zero-op essentially. We don't have a concept of timedeltas yet, so doing subtraction of dates isn't going to be coming in the very near term, but at least doing comparisons like greater than, less than, equals, etc. should be doable.

**Comment by miguelangel** [comment]
Hi @kkraus14,

I did as you suggested, and it worked! 

In fact, the operation I needed to do was a bit more complex. 

I will copy the code here, in case it might be useful for someone:

> import time
> import cudf
> import pandas as pd
> width_step=60
> base_time = pd.Timestamp("2010-01-01 00:00:00")
>   .................
> file_df['timestep'] = (((file_df['date'].astype(np.int64)/1000 - \
>      time.mktime(base_time.timetuple()))/(width_step*60))).astype(np.int)

Regards,
Miguel
