### ISSUE TITLE
[FEA] CI should ignore changes to the CHANGELOG

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#949]
**Is your feature request related to a problem? Please describe.**
If I have a PR that has passed all of the CI tests, but there's a conflict only on the `CHANGELOG.md`, then as soon as I resolve the conflict, I have to wait for all of the CI process to pass _again_. This is redundant and unnecessary and slows development velocity. 

**Describe the solution you'd like**
CI should not be re-run if the only change was made to the `CHANGELOG.md` file.

**Comment by dillon-cullinan** [comment]
If GitHub does not support the way we want to do this, there is a roundabout solution where we run style and changelog checks before triggering CPU/GPU builds. This will ensure the changelog is already updated before running resource heavy builds. Its not a perfect approach, but it is a solution if our ideal doesn't work out.

**Comment by jrhemstad** [comment]
As we add more and more configurations to the CI matrix, CI turnaround time grows, and this issue becomes more and more important.

**Comment by mike-wendt** [comment]
This is still WIP, will update once it is complete.
