### ISSUE TITLE
[FEA] Better test-wide fixtures and standardize around said fixtures

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#951]
Currently a lot of the tests have dataframe creation fixtures that are test specific or module specific which reduces code reuse and test coverage. We should create test-wide fixtures for things like dataframe creation that hit a wide range of dtypes / number of columns / number of rows to ensure we properly test all of our functions.

**Comment by GregoryKimball** [comment]
The [dataset_generator](https://github.com/rapidsai/cudf/blob/branch-22.08/python/cudf/cudf/testing/dataset_generator.py) module contains the [rand_dataframe](https://github.com/rapidsai/cudf/blob/ff63c0a745382d79eaf0ae45931e7167d9763b88/python/cudf/cudf/testing/dataset_generator.py#L314) function for generating test data.
