### ISSUE TITLE
[FEA] Implement .min() and .max() of a column

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#953]
**Is your feature request related to a problem? Please describe.**
I need to calculate the min and max of a column with datatype numpy.datetime64.

I have tried _df['date'].min()_ and _df['date'].max()_, but they seem to do not be implemented yet.

If I do _min(df['date'])_ or _max(df['date'])_, it takes about 6 seconds each, compared to miliseconds within Pandas.

**Describe the solution you'd like**
.min() and .max() functions implemented.

**Describe alternatives you've considered**
_min(df['date'])_ 
 _max(df['date'])_

**Additional context**
I am porting code from pandas to cudf

**Comment by jrhemstad** [comment]
We've got a `gdf_min` and `gdf_max` function, but it looks to only support arithmetic types. 

https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/reductions.cu#L252

This will need to be corrected. Furthermore, the reductions API should be redesigned to just be a simple `gdf_reduction` function with the reduction operation specified by an `enum`. 

I'll create an issue.

**Comment by kkraus14** [comment]
> **Is your feature request related to a problem? Please describe.**
> I need to calculate the min and max of a column with datatype numpy.datetime64.
> 
> I have tried _df['date'].min()_ and _df['date'].max()_, but they seem to do not be implemented yet.
> 
> If I do _min(df['date'])_ or _max(df['date'])_, it takes about 6 seconds each, compared to miliseconds within Pandas.
> 
> **Describe the solution you'd like**
> .min() and .max() functions implemented.
> 
> **Describe alternatives you've considered**
> _min(df['date'])_
> _max(df['date'])_
> 
> **Additional context**
> I am porting code from pandas to cudf

`df['date'].min()` and `df['date'].max()` are implemented for non datetime columns.

**Comment by jrhemstad** [comment]
See https://github.com/rapidsai/cudf/issues/954

**Comment by miguelangel** [comment]
Thank you both!

**Comment by harrism** [comment]
Looks like #1005 fixed min/max reductions for everything but the datatype requested in this bug, since #954 doesn't mention the same datatype. Reopening this and assigning @kovaltan .

**Comment by jrhemstad** [comment]
> Looks like #1005 fixed min/max reductions for everything but the datatype requested in this bug, since #954 doesn't mention the same datatype. Reopening this and assigning @kovaltan .

Sure looks like it's supported on the C++ side: https://github.com/rapidsai/cudf/pull/1005/files?file-filters%5B%5D=.cu&file-filters%5B%5D=.cuh&file-filters%5B%5D=.hpp&file-filters%5B%5D=.md&file-filters%5B%5D=.pxd&file-filters%5B%5D=.py&file-filters%5B%5D=.pyx&file-filters%5B%5D=.txt#diff-a83afc2ab36a155de543f41bb89f7ad3R127

**Comment by harrism** [comment]
Maybe, but the PR has Python code also. The pytests only test integer and floating point types: https://github.com/rapidsai/cudf/pull/1005/files?file-filters%5B%5D=.pxd&file-filters%5B%5D=.py&file-filters%5B%5D=.pyx&hide-deleted-files=true#diff-eda0c73352e7354b37c748e677b10ffbR14
