### ISSUE TITLE
[BUG] libcudf reductions should support non-arithmetic types for some operations

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#954]
**Describe the bug**
`gdf_min` and `gdf_max` do not support non-arithmetic types, e.g., `GDF_CATEGORY`, `GDF_DATE32`, `GDF_DATE64`, `GDF_CATEGORY`, `GDF_TIMESTAMP`.

https://github.com/rapidsai/cudf/blob/branch-0.6/cpp/src/reductions/reductions.cu#L207

**Expected behavior**
While it makes sense to not support `sum`, `product` and `sum_of_squares` for these types, we should support `min` and `max`.

**Additional context**
While this is being updated, two additional changes should be made to the libcudf reductions implementation.

1. The API should change from having individual functions for `gdf_min`, `gdf_max`, etc. to just `gdf_reduction` and the operation is specified via an enum.
2. The reduction implementation uses a 2-stage reduction algorithm with custom kernel. I don't see any reason we shouldn't just be using a `thrust::reduction`.

**Comment by jrhemstad** [comment]
Related issue that can be tackled at the same time: https://github.com/rapidsai/cudf/issues/446

**Comment by kovaltan** [comment]
[jrhemstad](/jrhemstad) 
I think the custom kernel is required to handle nulls. https://github.com/rapidsai/cudf/blob/c5b9d3e84eaf932ff87f336df72092aa7e9ba13a/cpp/src/reductions/reductions.cu#L47-L49
`thrust::reduction` cannot directly handle nulls unless we have null bitmap iterator for thrust.

Can we drop 2: `thrust::reduction` request  from this bug?

**Comment by jrhemstad** [comment]
> [jrhemstad](/jrhemstad)
> I think the custom kernel is required to handle nulls.
> 
> [cudf/cpp/src/reductions/reductions.cu](https://github.com/rapidsai/cudf/blob/c5b9d3e84eaf932ff87f336df72092aa7e9ba13a/cpp/src/reductions/reductions.cu#L47-L49)
> 
> Lines 47 to 49 in [c5b9d3e](/rapidsai/cudf/commit/c5b9d3e84eaf932ff87f336df72092aa7e9ba13a)
> 
>  T loaded = identity; 
>  if (i < size && gdf_is_valid(mask, i)) 
>      loaded = loader(data, i); 
> 
> `thrust::reduction` cannot directly handle nulls unless we have null bitmap iterator for thrust.
> Can we drop 2: `thrust::reduction` request from this bug?

So there's two orthogonal issues that I didn't do a good job of enumerating:
1. Single stage reduction
2. Use `thrust::reduction`

2. Is just a means for accomplishing 1., but I agree that accomplishing 2. may require some extra work.

In the meantime, a single-stage reduction can be accomplished by simply using an atomic to update the global reduction with each block's reduction result.

**Comment by kovaltan** [comment]
> In the meantime, a single-stage reduction can be accomplished by simply using an atomic to update the global reduction with each block's reduction result.

Okay, I will implement by using atomic operations.

**Comment by kovaltan** [comment]
@jrhemstad 

> 1. The API should change from having individual functions for `gdf_min`, `gdf_max`, etc. to just `gdf_reduction` and the operation is specified via an enum.

For C++ API,  item 1 is almost done.
But how about python bindings?
Do we also replace  `gdf_min`, `gdf_max`... into `gdf_reduction` + enums ?

**Comment by jrhemstad** [comment]
> But how about python bindings?
> Do we also replace `gdf_min`, `gdf_max`... into `gdf_reduction` + enums ?

Yes, I believe those should change as well, @kkraus14 can say for sure.

Keith, for context, Kova has updated all of the operation specific reduction APIs, e.g., `gdf_max`, `gdf_min`, into a generic `gdf_reduction` API where the op is selected with an enum. I assume the Python bindings will need to be updated accordingly.
