### ISSUE TITLE
[DOC] .unique_count() documentation is missing

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#956]
## Report incorrect documentation

**Location of incorrect documentation**
.unique_count() documentation is missing. 

**Describe the problems or issues found in the documentation**
Documentation missing.

**Steps taken to verify documentation is incorrect**
Tried to find the documentation, but not found.

**Suggested fix for documentation**
Add documentation.
---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by dillon-cullinan** [comment]
There was a bug where the Series() class was referencing itself in our docs causing none of the functions to show. This has been resolved.

**Comment by miguelangel** [comment]
Hi @dillon-cullinan, 

Thank you for fixing it. Nevertheless, there is a typo in the method description. It says ‘valies’ instead of ‘values’:

Returns the number of unique valies of the Series: approximate version, and exact version to be moved to libgdf
