### ISSUE TITLE
[FEA] Clarify non-existent subdirectory error messages for file writers

### ISSUE THREAD

**Issue by randerzander** [rapidsai/cudf#9564]
With latest cudf nightlies, attempting to write a file to a non-existend subdirectory fails as expected (matching Pandas), but the error is unclear:
```
RuntimeError: cuDF failure at: ../src/io/utilities/data_sink.cpp:36: Cannot open output file
```

Pandas's is a bit better:
```
IOError: [Errno 2] No such file or directory: './dir/name.csv'
```

It would be helpful for users to know if the write fails because the subdirectory didn't exist, as opposed to some other permissions or worse (if writing to a distributed fs) error.

**Comment by rnyak** [comment]
I get same error `RuntimeError: cuDF failure at: ....: Cannot open output file` when the subdirectory doesn't exist but the error msg is not informative.. it is hard to tell what's the issue. I agree that It would be helpful for users to know that this is because the subdirectory doesn't exist.
