### ISSUE TITLE
[BUG] Conda packages of dask-cudf aren't CUDA version agnostic

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#9567]
**Describe the bug**
In dask-cudf we add the cupy package for the specific CUDA version to the `setup.py`: https://github.com/rapidsai/cudf/blob/branch-21.12/python/dask_cudf/setup.py#L70-L73. When we make a conda package of dask-cudf we do not upload a separate package per CUDA version though. This leads to a dask-cudf package with a `cupy-cuda114` dependency being installed, where if someone tries to use pip in that environment it leads to a broken state.

This seems to go back to at least the 21.08 packages as well. Should probably either remove the cupy dependency from dask-cudf or publish a separate conda package per CUDA version.

Bigger picture... pip packaging is so broken when it comes to handling CUDA...

**Comment by shwina** [comment]
Re: removing the dependency, the only removal I can see as being potentially breaking is [here](https://github.com/rapidsai/cudf/blob/branch-21.12/python/dask_cudf/dask_cudf/backends.py#L262). @galipremsagar (or perhaps @pentschev ) do you have any thoughts on whether this is OK to remove? I don't quite understand why `dask_cudf` should responsible for registering CuPy types with dask.

Note that I think removing  the dependency  is the less desirable solution. Longer term, I wonder if CUDA enhanced compatibility will "just" solve this problem for us.

**Comment by galipremsagar** [comment]
> do you have any thoughts on whether this is OK to remove?

I'm testing it out, will get back on this soon

**Comment by galipremsagar** [comment]
I think we also have two more options here:
1. We can remove `cp.ndarray` dispatch, I have tested `dask`, `dask-cudf` & `dask-cuda` for this change and all seem to be functioning well.
2. We can make the registering of `cp.ndarray` dispatch optional just like in `dask`, i.e., if import of `cupy` succeeds in dask-cudf we register, or else ignore.


Doing 2 now (as we are close by release) and 1 on next release seems like a safer bet.

**Comment by kkraus14** [comment]
There's a 3rd option here as well in just publishing dask-cudf conda packages per CUDA version as well (for now at least). Right now the way we're publishing the packages is broken where we're uploading both packages and clobbering them where only the one that finishes last ends up staying.

**Comment by ajschmidt8** [comment]
> There's a 3rd option here as well in just publishing dask-cudf conda packages per CUDA version as well (for now at least). Right now the way we're publishing the packages is broken where we're uploading both packages and clobbering them where only the one that finishes last ends up staying.

Thanks Keith! We'll create an internal issue to complete this.

**Comment by galipremsagar** [comment]
Also, I think option 3 that Keith suggested is better approach for time being as I see more places in `dask_cudf` where we use `cupy` for some internal methods, example: https://github.com/rapidsai/cudf/blob/fc868b8392627755a6d191b7fea6a20860d32e44/python/dask_cudf/dask_cudf/backends.py#L275

I think we can try getting rid of them in future but since option 3 is being implemented will leave the code as-is for now.

**Comment by ajschmidt8** [comment]
PR merged: https://github.com/rapidsai/cudf/pull/9578

**Comment by ajschmidt8** [comment]
looks like the latest builds now include `cudatoolkit` version constraints ([link](https://anaconda.org/rapidsai-nightly/dask-cudf/files?page=1)).

![image](https://user-images.githubusercontent.com/7400326/140189757-0ca2e6bf-8dd5-4e03-8fe4-c51474086b68.png)


@kkraus14, can you confirm that this solves the issue? If so, can we close this?

**Comment by kkraus14** [comment]
Resolved by #9578
