### ISSUE TITLE
[BUG] Cast Decimal64 to Decimal128 is really slow

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#9597]
**Describe the bug**
When testing the limits of SUM overflow detection I noticed something really odd.  If the input value is a Decimal64, but the output is a Decimal128 the GPU does a lot more computation, and takes a lot longer to complete.  But if the input is Decimal128 and the output is Decimal128 then it is significantly faster.

```scala
scala> Seq(18, 28).foreach{i => println(i); spark.time(spark.range(0, 10000000000L, 1, 1).selectExpr(s"SUM(CAST('${"9"*i}' AS Decimal($i, 0)))").collect()).foreach(System.err.println)}
18
Time taken: 4134 ms                                                             
[9999999999999999990000000000]
28
Time taken: 1598 ms                                                             
[99999999999999999999999999990000000000]
```

So I did an nsys trace and found

For the slow query we got...
![slow_decimal](https://user-images.githubusercontent.com/3441321/140315379-60c7c974-fee8-4764-aba4-7eac487882aa.png)

And the fast one we got...
![fast_decimal](https://user-images.githubusercontent.com/3441321/140315464-6cf4b7da-63e4-4f22-82fd-afd2b442e94b.png)

So the cast takes way longer than the reduction does.

Long story short I found that we were doing a div that took most of the time in the cast and I looked at the cast code for decimal and found.

https://github.com/rapidsai/cudf/blob/9d375f51c734635c617a73f5dabdf20516896e96/cpp/src/unary/cast_ops.cu#L171-L189

Which shows us doing a DIV, even if the scale change is 0 and we end up dividing by 1.

So this comes down to two things.

1) Why are we doing a divide at all if the scale does not change?
2) Why is the divide so slow anyways? Is it because of the decimal128 support and dividing 128 bit values is really slow?

**Steps/Code to reproduce bug**
I don't have a C++ repro case yet, but it should just be something like make a large decimal64 value and cast it to a decimal128 value with the same scale. Because that is what we are doing.

**Expected behavior**
The cast, which should involve no real data changes except casting an `int64_t` to an `__int128_t` should ideally be as fast as copying the data.

**Environment overview (please complete the following information)**
Ubuntu 20 with an a6000 on a pre-release cuda 11.5 (but the driver is for cuda 11.4 because I have an older card just for display and it is a long story).

**Additional context**
I changed the input batch sizes from 2 GiB to 512MiB and saw very little change in the time it takes to process all 10 billion values.

**Comment by jrhemstad** [comment]
> Is it because of the decimal128 support and dividing 128 bit values is really slow?

This is almost certainly the issue. 

So this would be fixed by special casing for `input.scale() == scale` and just returning a copy of the input?

**Comment by revans2** [comment]
I am trying to upcast from a decimal64 to a decimal128 with the same scale. So it is not really returning a copy of the input. It is returning a wider copy of the input `__int128_t` as the underlying value instead of `int64_t`.

**Comment by revans2** [comment]
It might just be changing `if (input.type().scale() > scale) {` to `if (input.type().scale() >= scale) {`

**Comment by revans2** [comment]
Yup that appears to have fixed the issue. My time for the first query drops from 4 seconds to about 2 seconds.

@jrhemstad I am happy to put up a PR. Is it too late to get this into 21.12?  Should I bug @codereport to put this into his decimal128 PR, because that is the one where this shows up?

**Comment by codereport** [comment]
I am still actively working on the decimal128 PR so I think it is totally fine to make this change in that PR.

**Comment by codereport** [comment]
I have pushed the changed in this commit: https://github.com/rapidsai/cudf/pull/9483/commits/1034057301540a4f3355ce0ae16b16c481a6bb77. 

I think it's OK to close this PR as decimal128 is showing up in that PR.

**Comment by jrhemstad** [comment]
This is an issue, so let's keep it open until the decimal128 PR is merged.
