### ISSUE TITLE
[FEA] Series and and DataFrame.first and last

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#9600]
Pandas provides a `first` and `last` methods on DataFrames and Series. These methods require the index be a DatetimeIndex. They accept an offset string, DateOffset, or dateutil.relativedelta.

- [ ] [First](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.first.html): "This function can select the first few rows based on a date offset."
- [ ] [Last](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.last.html#pandas.DataFrame.last): "this function selects the last few rows based on a date offset."

These can potentially be implemented with a combination of searchsorted and slicing.

The documentation for `last` explicitly indicates the DatetimeIndex should be sorted, however neither `first` nor `last` conduct runtime checks of this requirement (see https://github.com/pandas-dev/pandas/issues/38000 ). Additionally, it's not clear that pandas unit tests cover offsets other than strings based on [these tests](https://github.com/pandas-dev/pandas/blob/dae5c5972aa539dcd5ba633e8d56735d61cfe7ae/pandas/tests/frame/methods/test_first_and_last.py).

To start, we could support only string offsets, like in the examples below.

It may be worth discussing expected behavior on the pandas repository.

For example:

```python
import pandas as pd
​
i = pd.date_range('2018-04-09', periods=4, freq='2D')
ts = pd.DataFrame({'A': [1, 2, 3, 4]}, index=i)
print(ts)
print(ts.first('3D'))
            A
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
            A
2018-04-09  1
2018-04-11  2
```

```python
import pandas as pd
​
i = pd.date_range('2018-04-09', periods=4, freq='2D')
ts = pd.DataFrame({'A': [1, 2, 3, 4]}, index=i)
print(ts)
print(ts.last("6D"))
            A
2018-04-09  1
2018-04-11  2
2018-04-13  3
2018-04-15  4
            A
2018-04-11  2
2018-04-13  3
2018-04-15  4
```

**Comment by isVoid** [comment]
Pandas do support `pd.DateOffset` object besides string, but the argument should be specified in "relativedelta"/singular form. Cudf does not support this argument for `DateOffset` yet.
```python
>>> s
2000-01-01 00:00:00    0
2000-05-01 16:00:00    1
2000-08-31 08:00:00    2
2000-12-31 00:00:00    3
dtype: int64

>>> s.first(pd.DateOffset(month=7))
2000-01-01 00:00:00    0
2000-05-01 16:00:00    1
dtype: int64
```

**Comment by isVoid** [comment]
Besides, pandas assume ascending order. On a descending ordered indexed series it produces wrong answer.

```python
>>> s
2000-04-01    0
2000-03-01    1
2000-02-01    2
2000-01-01    3
dtype: int64

>>> s.first('2M')
Series([], dtype: int64)
```
