### ISSUE TITLE
[BUG] "RuntimeError: Total number of concatenated rows exceeds size_type range" for 394 millions rows x 3 columns dataframe

### ISSUE THREAD

**Issue by co-tran-sp** [rapidsai/cudf#9609]
**Describe the bug**
According to https://github.com/rapidsai/cudf/issues/8748, the number of max unique entitlements are int32 which is around 2.2 billions. When `cudf.DataFrame(df)` is called with ~1.1 billion unique values, it will throw the RuntimeError above

**Steps/Code to reproduce bug**
`df = pd.DataFrame(np.random.rand(394531839,3))
df = cudf.DataFrame(df)`

**Expected behavior**
The cudf should be able to load the pandas dataframe
**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Environment is a jupyterlab notebook with rapids-21.10 env, using an Tesla T4 with 16GB VRAM. cuml version is 21.10.00.

**Comment by beckernick** [comment]
I am unable to reproduce this behavior with the 21.12 nightly or 21.10 release using a 32GB V100 GPU.

```python
import pandas as pd
import numpy as np
import cudf
​
df = pd.DataFrame(np.random.rand(394531839,3))
gdf = cudf.from_pandas(df)
gdf.shape
(394531839, 3)
```

Please also note that the int32 size type limit is per column, so if you are getting this error it may be a red herring. Could you share a minimal, reproducible, complete example?

**Comment by vyasr** [comment]
I am also not able to reproduce this as of 22.08, so I'm going to close, but feel free to reopen if the issue recurs.
