### ISSUE TITLE
[FEA] libcudf stream parameters should default to `cudaStreamPerThread` when compiled for PTDS

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9614]
**Is your feature request related to a problem? Please describe.**
#9534 occurred because libcudf was using a default-value argument as the stream to use (i.e.: the stream argument in the `detail` APIs that is currently hidden from the public APIs) and that stream was stream 0 (the default stream).  Because libcudf was compiled for PTDS, it properly interpreted 0 as `cudaStreamPerThread` but this concept was not conveyed to other libraries called by libcudf.  When 0 was passed to these other libraries, it ended up using the default stream instead of `cudaStreamPerThread`.  Ideally libcudf should pass the same stream it is using to external libraries that take a stream parameter.  Then for libraries that are completely driven by stream parameters, those libraries don't have to be compiled with PTDS when libcudf is compiled with PTDS to avoid surprising performance pitfalls.

**Describe the solution you'd like**
The default value of stream arguments in libcudf should be `cudaStreamPerThread` when libcudf is being compiled for PTDS.  This will cause libcudf to pass the same stream it is using to external libraries that take a stream This idea was proposed by @jrhemstad in an offline discussion of solutions to #9534.

**Describe alternatives you've considered**
A workaround is to compile all external libraries libcudf is using with PTDS when libcudf is compiled for PTDS, but this seems unnecessary for libraries like nvcomp which never uses the default stream unless directed by the application code to do so by passing the legacy default stream value as the stream to use.

Another option is to track down every place in libcudf where we pass a stream parameter to an external library and then pass `cudaStreamPerThread` if the stream is stream 0 and libcudf is compiled for PTDS.  This seems more fragile in practice, as we have to manually locate all of these places, fix them (which may be tricky if the stream is passed into that code as a parameter), and remembering to fixup new external call sites going forward.

**Comment by jrhemstad** [comment]
The alternative that wasn't mentioned and is what I would vastly prefer to see here is to expose streams in the public APIs of libcudf. https://github.com/rapidsai/cudf/issues/925

That way, a caller can specify whatever stream they like (including `cudaStreamPerThread`).

I'd much prefer that option to some non-standard switheroo of defaulted function parameter values through compile time definitions.

**Comment by jlowe** [comment]
Yes, thanks @jrhemstad for fixing my omission.  Exposing the stream parameter would be great and should remove the need for libcudf to be compiled with PTDS.  I filed this mostly under the assumption #925 is still a long ways off -- is that no longer the case?

**Comment by jbrennan333** [comment]
Since nvcomp-2.3 is going to be released as only shared libraries.  The solution in [#9534](https://github.com/rapidsai/cudf/issues/9534), compiling nvcomp with `CUDA_API_PER_THREAD_DEFAULT_STREAM`, will no longer work.

**Comment by jrhemstad** [comment]
Filed https://github.com/rapidsai/cudf/issues/10864 for solution.
