### ISSUE TITLE
[FEA] Control rowgroup and page size when writing Parquet files

### ISSUE THREAD

**Issue by vuule** [rapidsai/cudf#9615]
Add a parameter to control the rowgroup size and the page size of the output Parquet file. The size can be specified in bytes or in the number of rows.

**Comment by vuule** [comment]
Reopening - page size control has not been implemented.

**Comment by etseidl** [comment]
Hi @vuule. Controlling page size is a feature of great interest to my group.  I've taken a stab at implementing this functionality...would it be useful to submit a PR, or do you already have an implementation in mind and just need the time/priority to get it implemented?

**Comment by devavret** [comment]
@etseidl Sure, go ahead.
