### ISSUE TITLE
[FEA] Regex: Provide option for '.' to not match '\r'

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#9619]
**Is your feature request related to a problem? Please describe.**
In Python and cuDF, the default behavior is that  `.`  will match all characters except for line-feeds, so this will match on `\r`. However, the default behavior in Java (as used by Spark) is that `.` will *not* match `\r` so this leads to an incompatibility.

## cuDF example:

```python
>>> cudf.Series(['a\rb']).str.contains('a.', regex=True)
0    True
dtype: bool

>>> cudf.Series(['a\nb']).str.contains('a.', regex=True)
0    False
dtype: bool
```

## Spark example:

```scala
scala> val df = Seq("a\rb", "a\nb").toDF("c0")
scala> df.createOrReplaceTempView("t1")
scala> spark.sql("select c0 rlike 'a.' from t1").show
+-----------+                                                                   
|c0 RLIKE a.|
+-----------+
|      false|
|      false|
+-----------+
```

**Describe the solution you'd like**
I would like an option to specify whether `.` should match `\r` so that we can match the default Java behavior?

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by davidwendt** [comment]
I'm reluctant to add specific support for `\r` character since it could create confusion in other places where `\n` is handled -- like for `^` and `$` as well as builtin classes `\W` and `\D`.
Could you replace the `\r` with `\n` in the input string? Since both are single byte characters, this could be done in-place on the chars column.

**Comment by andygrove** [comment]
I think that the best I can do in terms of a workaround is to inspect the input first to see if it does contain `\r` if the regex pattern contains `.` and fall back to the CPU in that case. Replacing `\r` with `\n` could have side effects but it all depends what the regex pattern is.

**Comment by davidwendt** [comment]
Another option is to use `[^\r\n]` instead of `.`
This would match any character but `\r` or `\n`.
