### ISSUE TITLE
[BUG] CUDA_HOST_DEVICE_CALLABLE is 1: Misleading 2. unwieldy

### ISSUE THREAD

**Issue by eyalroz** [rapidsai/cudf#962]
At the moment, we have:
```
#define CUDA_HOST_DEVICE_CALLABLE __host__ __device__ __forceinline__
#define CUDA_DEVICE_CALLABLE __device__ __forceinline__
```
which is patently misleading, since we're just suggesting callability, not forcing inlining. So - IMO, these _have_ to be changed to something else.

Now, these macros are already pretty long; annoyingly so even. And if they're lengthened to also reflect the inlining, it'll be too much. I therefore suggest using the following shorthands:
```
#define __fhd_ __forceinline__ __host__ __device__ 
#define __fd__ __forceinline__ __device__ 
```
The initials are a bit cryptic when you first encounter them, but they aren't confusing or misleading - you'll know it's something you have to look up. But once you _have_ looked them up even once - you won't forget them, because they're initials: `f` for forced-inlining, `h` for host and `d` for device.

I know using `__` as a prefix is not very nice in C++, but - we already have `__host__`, `__device__` and `__shared__`, so this isn't that much more of a transgression.

**Comment by harrism** [comment]
You should always use `inline`, not `__forceinline__`, a CUDA compiler engineer once told me...
