### ISSUE TITLE
[FEA] DataFrame swapaxes

### ISSUE THREAD

**Issue by beckernick** [rapidsai/cudf#9628]
For pandas API compatibility, we can implement [DataFrame.swapaxes](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.swapaxes.html). This appears to either return a transpose (swapping index and column axes) or the original frame. In both cases, the data is copied by default (but can be parameterized to return a view / the original frame instead).

[Series.swapaxes](https://pandas.pydata.org/docs/reference/api/pandas.Series.swapaxes.html) is likely going to be deprecated in the future based on https://github.com/pandas-dev/pandas/issues/18262 and the method itself is generally no longer useful since pandas removed Panels. There may be some numpy compatibility reasons it still exists, based on https://github.com/pandas-dev/pandas/pull/26654 . If we eventually run into similar needs with CuPy, we can cross that bridge when we come to it.

```python
import pandas as pd
​
df = pd.DataFrame({
    "a": [0,1,None,3],
    "b": [3,9,20,1]
})
​
print(df)
print(df.swapaxes(0,0, copy=False))
print(df.swapaxes("index", "columns"))
print(df.swapaxes(1,0))
print(df.swapaxes(0,1))
     a   b
0  0.0   3
1  1.0   9
2  NaN  20
3  3.0   1
     a   b
0  0.0   3
1  1.0   9
2  NaN  20
3  3.0   1
     0    1     2    3
a  0.0  1.0   NaN  3.0
b  3.0  9.0  20.0  1.0
     0    1     2    3
a  0.0  1.0   NaN  3.0
b  3.0  9.0  20.0  1.0
     0    1     2    3
a  0.0  1.0   NaN  3.0
b  3.0  9.0  20.0  1.0
```

**Comment by vyasr** [comment]
DataFrame.swapaxes [was deprecated in pandas 2.1](https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#other-deprecations) ([this issue](https://github.com/pandas-dev/pandas/issues/51946)) so it's not worth our time to implement it now.
