### ISSUE TITLE
[FEA] Support rolling_aggregation for NTH_ELEMENT

### ISSUE THREAD

**Issue by res-life** [rapidsai/cudf#9643]
Rapid Plugin is supporting first,last function in window context which should use CUDF nth_element.

**Additional context**

Should implements **make_nth_element_aggregation<rolling_aggregation>**

```
// NTH_ELEMENT does not have rolling_aggregation unlike COUNT
// Please see the folowing:

cpp/src/aggregation/aggregation.cpp

  /// Factory to create an NTH_ELEMENT aggregation
  template <typename Base>
  std::unique_ptr<Base> make_nth_element_aggregation(size_type n, null_policy null_handling)
  {
    return std::make_unique<detail::nth_element_aggregation>(n, null_handling);
  }
  template std::unique_ptr<aggregation> make_nth_element_aggregation<aggregation>(
    size_type n, null_policy null_handling);
  template std::unique_ptr<groupby_aggregation> make_nth_element_aggregation<groupby_aggregation>(
    size_type n, null_policy null_handling);

  /// Factory to create a COUNT aggregation
  template <typename Base>
  std::unique_ptr<Base> make_count_aggregation(null_policy null_handling)
  {
    auto kind =
      (null_handling == null_policy::INCLUDE) ? aggregation::COUNT_ALL : aggregation::COUNT_VALID;
    return std::make_unique<detail::count_aggregation>(kind);
  }
  template std::unique_ptr<aggregation> make_count_aggregation<aggregation>(
    null_policy null_handling);
  template std::unique_ptr<rolling_aggregation> make_count_aggregation<rolling_aggregation>(
    null_policy null_handling);
  template std::unique_ptr<groupby_aggregation> make_count_aggregation<groupby_aggregation>(
    null_policy null_handling);
  template std::unique_ptr<groupby_scan_aggregation> make_count_aggregation<groupby_scan_aggregation>(
    null_policy null_handling);
```

**Comment by res-life** [comment]
Similar with: https://github.com/rapidsai/cudf/issues/7231

**Comment by res-life** [comment]
Spark plugin planned this into:  22.02

**Comment by revans2** [comment]
Still interested in this.

**Comment by sameerz** [comment]
Still needed

**Comment by revans2** [comment]
Just as some context #11141 was filed to make first/last more efficient for group by operations. If the author decides to add in first/last as and aggregation separate from nth, we still would want an nth rolling_aggregation. But first/last wold have the highest priority as they are much more common compared to nth_element in Spark.

**Comment by mythrocks** [comment]
Apologies for the delay. Very shortly, I'll be raising a PR in CUDF to address `NTH_ELEMENT()`. 

We'll have `FIRST()` as `NTH_ELEMENT(0)` and `LAST()` as `NTH_ELEMENT(-1)`, and use `NTH_ELEMENT()` to implement SQL's `NTH_VALUE()`. A couple of considerations regarding indices:
1. CUDF's indices are 0-based. SQL's 1-based indices will require adjustment before calling down to CUDF.
2. CUDF's indices will need to support the range `[-window_size, window_size)`. This is a superset of SQL's requirement of `[1, window_size]` (or `[0, window_size)`, in CUDF parlance).
