### ISSUE TITLE
[BUG] hash_join always computes join size even if size is passed by caller

### ISSUE THREAD

**Issue by jlowe** [rapidsai/cudf#9647]
**Describe the bug**
`hash_join` will always call `compute_join_output_size` even if the join size is passed by the caller.

**Steps/Code to reproduce bug**
Build the libcudf gtests and take a profile like this:
```
nsys profile gtests/JOIN_TEST --gtest_filter=*HashJoinSequentialProbes
```
Load the profile and zoom into where the size is computed by the test and then passed to the join.  Note in the trace how the `pair_count` kernel is invoked by both `inner_join_size` and `inner_join` as shown in this sample trace screenshot:

![image](https://user-images.githubusercontent.com/1360766/141149723-50282095-ebea-418a-ae30-04b1183a50db.png)

**Expected behavior**
The `pair_count` kernel should not be invoked by `inner_join` if the join size is passed by the caller.

**Comment by abellina** [comment]
@jlowe and myself discussed a fix. I am trying to get stylecheck to pass locally and should have a PR up shortly.

**Comment by jrhemstad** [comment]
Ah yes, I overlooked that fact that when using `value_or` that argument expression is sequenced before the expressions inside the function. Using a ternary will fix this.

https://godbolt.org/z/1r6d5b8eq
