### ISSUE TITLE
[FEA] Construct `column_view` from `rmm::device_uvector` and `device_span`

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#9656]
Sometimes, we need to call some API that only accepts `column_view` input but we only have data stored in `rmm::device_uvector` (which can implicitly casted into `device_span`). As a result, we need to construct a `column_view` from `rmm::device_uvector` manually like this, in many places:
```
 auto gather_map = column_view(
      cudf::data_type{cudf::type_to_id<cudf::size_type>()}, output_size, indices.data());
```

This is lengthy and error-prone.

A better solution is to add a utility API to do that automatically. Internally, that utility may call `type_dispatcher` to construct the output `column_view` depending on the input type.

**Comment by ttnghia** [comment]
Tag @jrhemstad and @davidwendt as this idea is from you guys and it's great if you can work on it :smile:

**Comment by jrhemstad** [comment]
> A better solution is to add a utility API to do that automatically. Internally, that utility may call `type_dispatcher` to construct the output `column_view` depending on the input type.

There's no need for a type dispatch here because you already know the type from the `device_span`.

**Comment by davidwendt** [comment]
Make sure you really need this. If you doing this for calling `cudf::detail::gather` then you can just pass the `device_uvector` directly to https://github.com/rapidsai/cudf/blob/ba2b51dd8f1b1dd0611f90742e0ffb835615cd33/cpp/include/cudf/detail/gather.hpp#L78-L84 which will automatically convert the `device_uvector` to a `device_span`.

Example: https://github.com/rapidsai/cudf/blob/ba2b51dd8f1b1dd0611f90742e0ffb835615cd33/cpp/src/copying/copy.cu#L162-L175

**Comment by jrhemstad** [comment]
I think there are plenty of other places where people are constructing a `column` or ` column_view` from a `device_uvector` that make this an important and useful thing.
