### ISSUE TITLE
Always writing Index column of dask_cudf to ORC [BUG]

### ISSUE THREAD

**Issue by MikeChenfu** [rapidsai/cudf#9661]
**Describe the bug**
Hi Guys, I found the dask_cudf df always writes index column even if set the `index=False`.

**Steps/Code to reproduce bug**
Here is the sample code.
```python
import dask_cudf
import cudf
df = cudf.DataFrame({'a':[1,2,3] * 10})
dfs = dask_cudf.from_cudf(df, npartitions = 2)
dfs.to_orc('test1/', index=False)
cudf.read_orc('test1/part.0.orc')

	index	a
0	0	1
1	1	2
2	2	3
3	3	1
4	4	2
5	5	3
6	6	1
7	7	2
8	8	3
9	9	1
10	10	2
11	11	3
12	12	1
13	13	2
14	14	3


```
**Expected behavior**
```python
import dask_cudf
import cudf
df = cudf.DataFrame({'a':[1,2,3] * 10})
dfs = dask_cudf.from_cudf(df, npartitions = 2)
dfs.to_orc('test1/', index=False)
cudf.read_orc('test1/part.0.orc')

	a
0	1
1	2
2	3
3	1
4	2
5	3
6	1
7	2
8	3
9	1
10	2
11	3
12	1
13	2
14	3


```

**Environment overview (please complete the following information)**
 - Environment location: [Docker]
 - Method of cuDF install: [conda]
   
**Environment details**
```
cudf.__version__
'21.08.00a+289.gb011299069'
```

**Comment by beckernick** [comment]
The `to_orc` API [in Dask](https://docs.dask.org/en/latest/_modules/dask/dataframe/io/orc/core.html) uses the parameter `write_index` rather than `index`. `dfs.to_orc('test1/', write_index=False)` will avoid writing the index.

Closing as answered.
