### ISSUE TITLE
more docs for new apply_* features 

### ISSUE THREAD

**Issue by sklam** [rapidsai/cudf#97]
More docs for https://github.com/gpuopenanalytics/pygdf/pull/96

**Comment by kkraus14** [comment]
Updating as this is a bit dated. Docs are missing for `groupby.apply_grouped` and `groupby.apply`

**Comment by kkraus14** [comment]
@randerzander what is the status on this?

**Comment by randerzander** [comment]
docs have been published for [groupby.apply](
https://rapidsai.github.io/projects/cudf/en/0.6.0/api.html#cudf.groupby.legacy_groupby.Groupby.apply) and [groupby.apply_grouped](https://rapidsai.github.io/projects/cudf/en/0.6.0/api.html#cudf.groupby.legacy_groupby.Groupby.apply_grouped)

ok to close?

**Comment by sklam** [comment]
Docs for `groupby.apply` is not right.  It doesn't compile.

**Comment by kkraus14** [comment]
@sklam Are you saying the docstring is incorrect in claiming it compiles a Python function or that the docs do not compile and generate properly for you?

**Comment by sklam** [comment]
Sorry for being unclear.  The docstring is incorrect in saying that `.apply` compiles the incoming python function.  It's applying the incoming function as is to every group.  The implemented behavior is similar to the pandas equivalent [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.core.groupby.GroupBy.apply.html).

**Comment by kkraus14** [comment]
Fixed by #1447
