### ISSUE TITLE
[FEA] Add `CUDF_DEBUG_ASSERT` macro for assert-debugging in Release mode

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#9705]
Currently, there are not many debug utilities in cudf. When developing new features, we may have to manually debug printing variables to catch bugs and then have to cleanup such printing statements when bugs have been fixed. The next time a bug emerges, we have to repeat the same process. That is very time-consuming and tedious.

An option for debugging is to switch to compile in Debug mode and use build-in debug-assert utilities such as the `assert` native macro from C++. However, compiling and running in Debug mode is both extremely slow thus not many developers want to do that.

Another option is to use `CUDF_EXPECT` but that macro should not be used in many places just to catch potential bugs. The small runtime overhead of that macro also raises the eyebrow of some devs who want to keep overhead minimal.

I propose to add `CUDF_DEBUG_ASSERT` which is enabled only by a compiler flag (such as `-DENABLE_DEBUG_ASSERT`). Devs are free to use it in production code and enable it by compiler flag in their local dev environment. In production, is it disabled by default thus will not incur any runtime overhead. Having this macro could help devs reduce their debug time a lot, since many bugs can be discovered easily by an assert statement but are difficult/not trivial to see by other ways, such as the out-of-bound access issue. And because the code won't require to be compiled in Debug mode, adding/using that macro will have very little impact on both compile time and runtime.

**Comment by jrhemstad** [comment]
Sounds to me like reinventing `NDEBUG`. You can build without `-DNDEBUG` and without specifying `-g -G`.

**Comment by ttnghia** [comment]
Yeah, exactly like that. By having our own macro, we can control what and where it is doing. Otherwise, we can't choose to disable `assert` in the std functions and enable it for only our functions.

**Comment by jrhemstad** [comment]
I don't really love the idea of adding yet another macro. I'd rather just use the existing semantics and mechanics of `assert` and `NDEBUG`.
