### ISSUE TITLE
[BUG] cudaErrorIllegalAddress when reading a CSV file

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#971]
**Describe the bug**
Hi,

I have a csv file of 5135558 rows.

When I try to read it, the following error happens.

<img width="1070" alt="screenshot 2019-02-16 at 23 40 53" src="https://user-images.githubusercontent.com/26169771/52910431-a28b4f00-3297-11e9-80f5-c7c5c05b95e3.png">

But, if I split the file in two parts, load them into two different DataFrames, and then concat both DataFrames, it works perfectly.

<img width="1060" alt="screenshot 2019-02-16 at 23 44 27" src="https://user-images.githubusercontent.com/26169771/52910438-acad4d80-3297-11e9-8d99-4ad01e7e554c.png">

The GPU is 16GB, and the  memory consumption before the error is raised is as follows:

0, 0 %, 3684 MiB
1, 0 %, 11 MiB
2, 0 %, 11 MiB
3, 0 %, 11 MiB
4, 0 %, 11 MiB
5, 0 %, 11 MiB
6, 0 %, 11 MiB
7, 0 %, 11 MiB

**Steps/Code to reproduce bug**
Run the code above

**Expected behavior**
CVS read without issues.

**Environment details (please complete the following information):**
DGX-1, with 8 v-100 16GB each.

**Comment by vuule** [comment]
@miguelangel how big is the input file, and how big is the resulting dataframe (after concatination)? At one point during reading we store both the input file and the dataframe columns on the GPU, so it might drive the memory usage over the GPU memory capacity in this case.

**Comment by miguelangel** [comment]
Hi @vuule, the file is 2917M. Also, please have a look at my comment on GPU memory consumption reported by nvidia-smi.

**Comment by vuule** [comment]
I have local repro on a GTX 1080 (8 GB). 
It does not look like it runs out of memory. Perhaps the issue is related to use of 32bit ingeters with a file larger than 2^31 bytes. I'm looking into the root cause. So far isolated the issue to convertCsvToGdf().

**Comment by miguelangel** [comment]
Solved with https://github.com/rapidsai/cudf/pull/1001. Thank you all!
