### ISSUE TITLE
[FEA] Add a license-check into CI tests to verify license header

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#9729]
I have observed many times that in a new PR, devs sometimes forget to modify the copyright year in the license header. Many times, the reviewers realized that and pointed that out. However, there is not any guarantee that the forgotten headers are always discovered. For reviewers, manually checking for license header is kind of tedious and time-consuming, especially in a large PR with many modified files.

I propose to add a script (similar to clang-format style check) into CI tests to verify if the copyright year in the license header of the modified files has been updated. Maybe that is just a simple python script, and it can solve this problem forever. I'm not familiar with python thus will not be able to do it :smile:.

**Comment by harrism** [comment]
I believe cuML has this.

**Comment by galipremsagar** [comment]
Resolved by https://github.com/rapidsai/cudf/pull/10253
