### ISSUE TITLE
[QST]why is the `cudf::io::gpuinflate` performance  so poor ?

### ISSUE THREAD

**Issue by chenrui17** [rapidsai/cudf#9731]
**What is your question?**
I use `cudf::io::gpuinflate` API to inflate a gzip txt file, and it cost about 10s, and gpu util is 100%, and sm_act is ~0.01, based nsight system analysis, about all of the time is the `inflate_kernel`
![image](https://user-images.githubusercontent.com/33319780/142593319-3a66fe4b-84ff-423e-8fba-dd1deb30ac18.png)
so , my question is why is the performance is so poor ? because input data is row based ? how we improve this infalte performance ?

**Comment by devavret** [comment]
The inflate kernel is currently designed for inflating multiple small chunks of compressed data. One block is used to inflate one chunk. Its performance will be poor if you're inflating one continuous large compressed chunk as only one block will be active.
For more generic GPU based decompression, you can take a look at https://github.com/NVIDIA/nvcomp. Although nvCOMP also doesn't support generic deflate yet, they do offer competitive alternatives which you can use to compress and then decompress single large chunks.

cc @elstehle, @nsakharnykh

**Comment by GregoryKimball** [comment]
Question was answered

**Comment by nsakharnykh** [comment]
Quick update related to this issue: nvCOMP added support for GPU inflate/deflate in 2.3 https://github.com/NVIDIA/nvcomp/blob/main/CHANGELOG.md. Some performance numbers are published on the devzone page https://developer.nvidia.com/nvcomp
