### ISSUE TITLE
what should stringConcatenateListElements return when list only contains nulls?

### ISSUE THREAD

**Issue by HaoYang670** [rapidsai/cudf#9745]
I am using the method `stringConcatenateListElements(Scalar separator,
      Scalar narep, boolean separateNulls, boolean emptyStringOutputIfEmptyList)` in Spark-Rapids to cast Array typed dataframe to string type. I find that when the input is `Array(null, null. null)`, the output is always an empty string. (I set `narep="null"`, `seperateNulls`=true). However, what the expected is `"null, null, null"`.

**Describe the solution you'd like**
I add a test in `ColumnVectorTest.java`:
![image](https://user-images.githubusercontent.com/59198230/142799981-c67b4800-e3be-421e-a174-96bc0236e7f9.png)
This is what I expected.

**Comment by sperlingxx** [comment]
Hi @ttnghia, would you take a look when you have time?

**Comment by ttnghia** [comment]
Yes, the result is correct. It's the desired behavior of Spark. When the input is all nulls, Spark will output null.

**Comment by ttnghia** [comment]
You will find that behavior almost everywhere: nulls in => null out :smiley:

**Comment by ttnghia** [comment]
FYI: Here is the cudf doc for the case of all nulls in a list:
```
* In the special case when the input list row contains all null elements, the output will be the
* same as in case of empty input list regardless of @p string_narep and @p separate_nulls values.
```

**Comment by HaoYang670** [comment]
![image](https://user-images.githubusercontent.com/59198230/142806834-c337755d-c129-484b-bba1-1066626b36f2.png)
This is the result I get from Spark. When the input is `Array(null, null)`, the output is `"[null, null]"`, instead of `null`.

**Comment by ttnghia** [comment]
That's interesting. @revans2 should know more about this, so can you comment on this please? If necessary then we can change that in cudf implementation.

**Comment by HaoYang670** [comment]
![image](https://user-images.githubusercontent.com/59198230/142807512-e540e9bf-020d-4274-9264-9f9065a8d68c.png)

**Comment by HaoYang670** [comment]
This is the result I get using Spark 3.2.0. When casting to string, `Array(null, null)` is casted to `"[null, null]"`

**Comment by revans2** [comment]
Sorry @ttnghia

I opened #7727 in March and it was close din April, so I am having some trouble remembering all of the details from 7 months ago.  Also all of the places we currently use this API have all of the parameters set to false, so there could be some oddness happening there too.

**Comment by ttnghia** [comment]
I just realize that the example above is casting from struct to string, not concat strings. Did you try concat strings?
```
val data = Seq(("James","A","Smith","2018","M",3000), (null, null, null, null, null, 1000))
val columns = Seq("fname","mname","lname","dob_year","gender","salary")
import spark.sqlContext.implicits._
val df = data.toDF(columns:_*)
df.show(false)

df.select(concat(col("fname"),lit(','), col("mname"),lit(','),col("lname")).as("FullName")).show(false)
```

The behavior for all-nulls input was requested to match with Python output. We can further modify the cudf API if we must support non-null non-empty output for such cases.

**Comment by HaoYang670** [comment]
```
scala> val data = Seq(Row(Array(null, null)))
data: Seq[org.apache.spark.sql.Row] = List([[Lscala.runtime.Null$;@39081953])

scala> val schema = StructType(Array(StructField("a", ArrayType(IntegerType, true))))
schema: org.apache.spark.sql.types.StructType = StructType(StructField(a,ArrayType(IntegerType,true),true))

scala> val df0 = spark.createDataFrame(spark.sparkContext.parallelize(data), schema)
df0: org.apache.spark.sql.DataFrame = [a: array<int>]

scala> df0.createOrReplaceTempView("df0")

scala> val df1 = spark.sql("select concat(a, a) as res from df0")
df1: org.apache.spark.sql.DataFrame = [res: array<int>]

scala> df1.collect
res1: Array[org.apache.spark.sql.Row] = Array([WrappedArray(null, null, null, null)])

scala> val df2 = df1.withColumn("res", col("res").cast(StringType))
df2: org.apache.spark.sql.DataFrame = [res: string]

scala> df2.collect
res2: Array[org.apache.spark.sql.Row] = Array([[null, null, null, null]])

scala> df2.show
+--------------------+
|                 res|
+--------------------+
|[null, null, null...|
+--------------------+


scala> val df3 = spark.sql("select concat_ws(', ', a, a) as res from df0")
df3: org.apache.spark.sql.DataFrame = [res: string]

scala> df3.collect
res4: Array[org.apache.spark.sql.Row] = Array([])

scala> df3.show
+---+
|res|
+---+
|   |
+---+
```
I review https://github.com/rapidsai/cudf/issues/4728 and find the difference between `concat` and `concat_ws` on dealing with "all nulls list" (`df2` and `df3`). The behavior of `concatenate_list_elements` in cudf is more similar with `concat_ws`.
However, in Spark, `cast(StringType )` deals with `null` in the same way as `concat` (transfer each `null` to "null" in the list). 
Could add an new api in `concatenate_list_elements` that is consisted with `concat` and `cast(StringType)` on dealing with all `null` list?

**Comment by jrhemstad** [comment]
> Could you add a new API in concatenate_list_elements that is consisted with concat and cast(StringType) on dealing with all null list? 

@ttnghia before proceeding with anything along these lines, can someone please summarize what libcudf operation we are talking about and the missing behavior? I've seen both casting and concatenating discussed and those seem like very different operations, so I'm not clear what behavior we are discussing.

**Comment by ttnghia** [comment]
The behavior we're talking here is directly related to the API `join_list_elements` (formerly knew as `concatenate_list_elements`) (https://github.com/rapidsai/cudf/blob/31f92d70bdf5b80434d24b6883e45496dbe85042/cpp/include/cudf/strings/combine.hpp#L258).

Previously, in order to match with Spark and Python behaviors, it was designed with a parameter to specify what the output will be in case of all-nulls input list, that is either a null, or an empty string (https://github.com/rapidsai/cudf/blob/31f92d70bdf5b80434d24b6883e45496dbe85042/cpp/include/cudf/strings/combine.hpp#L222):
```
 * In the special case when the input list row contains all null elements, the output will be the
 * same as in case of empty input list regardless of @p string_narep and @p separate_nulls values.
 ```

Now it seems that we need to have a third option to allow using `string_narep`.

**Comment by ttnghia** [comment]
> I've seen both casting and concatenating discussed and those seem like very different operations

We're talking about casting struct to string (in Spark). That can be done by casting each child into a string then concatenating these string results.

**Comment by jrhemstad** [comment]
> Now it seems that we need to have a third option to allow using string_narep

I strongly dislike that idea. This API is already a nightmare of option flags with a complex cross product of behavior depending on the values of the various parameters. This API is trying to do too many things.

For example, why is the `separators` column allowed to contain null elements necessitating a `separator_narep` to use in place of nulls in `separators`. This could be done much cleaner by requiring `separators.null_count() == 0`. A user can perform `replace_nulls` on `separators` with `separator_narep` before hand to achieve that behavior. 

Likewise, `empty_list_policy` seems entirely unnecessary. An empty list should generate an empty string. If someone wants to turn empty strings into nulls, this can be achieved by post-processing empty strings to be null. 

The relationship between `string_narep` and `separate_nulls` is also confusing. When would I specify a valid `string_narep` and not want separators? If the goal is to enable filtering out null elements, then this should be a pre-processing step. 

> In the special case when the input list row contains all null elements, the output will be the
> same as in case of empty input list regardless of @p string_narep and @p separate_nulls values.

Why? This is very non-intuitive. If I have `[null, null, null]` with `string_narep == 'n'` and `separator == :` I expect to get `"n:n:n"`.

It is clear this API was overfit to corner cases of Spark and/or Python. We should take a step back and ask "What does it make sense for this function to do?" then work backwards from there and decide how corner cases can be satisfied by pre/post-processing as I described above.

**Comment by ttnghia** [comment]
I'm a bit confused why the casting op from struct to string can't produce the desired result (like `"[null, null, null]"`). If the struct members are casting into string first, you (@HaoYang670 ) should get a list of strings like `["null", "null", "null"]`. Concatenate these strings then should produce the correct result.

**Comment by HaoYang670** [comment]
```

  private  def castArrayToString(
                                  input: ColumnView,
                                  elementType: DataType,
                                  containsNull: Boolean,
                                  ansiMode: Boolean,
                                  legacyCastToString: Boolean,
                                  stringToDateAnsiModeEnabled: Boolean): ColumnVector = {
    val (leftStr, rightStr) =  ("[", "]")
    val emptyStr = ""
    val nullStr =  "null"
    val numRows = input.getRowCount.toInt

    // cast all elements in arrays (lists) to string type. Ex: [[1,2,3],[4,5]] => [["1","2","3"], ["4","5"]]
    withResource(doCast(input, ArrayType(elementType, containsNull), ArrayType(StringType, containsNull), ansiMode, legacyCastToString, stringToDateAnsiModeEnabled)) { strArr =>
      // cast each array (list) to a string (without brackets). Ex: [["1","2","3"], ["4","5"]] => ["1, 2, 3", "4, 5"]
      withResource(strArr.stringConcatenateListElements(
        Scalar.fromString(", "),
        Scalar.fromString("null"),
        true,
        true)) { withoutBrackets =>
        // add brackets to each string. Ex: ["1, 2, 3", "4, 5"] => ["[1, 2, 3]", "[4, 5]"]
        withResource(Seq(leftStr, rightStr).safeMap(Scalar.fromString).safeMap(s => ColumnVector.fromScalar(s, numRows))){ case Seq(leftColumn, rightColumn) =>
          withResource(ArrayBuffer.empty[ColumnVector]) { columns =>
            columns += leftColumn.incRefCount()
            columns += withoutBrackets.incRefCount()
            columns += rightColumn.incRefCount()

            withResource(ColumnVector.stringConcatenate(Scalar.fromString(emptyStr), Scalar.fromString(nullStr), columns.toArray))(
              _.mergeAndSetValidity(BinaryOp.BITWISE_AND, input)
            )
          }
        }
      }
    }
```
Currently, I am developing the function of casting ArrayType column to StringType Column (https://github.com/NVIDIA/spark-rapids/issues/4028). Firstly, I cast all elements in array to string type. Secondly, I use the function https://github.com/rapidsai/cudf/blob/49d1cc28648fe676dbddcf27c01939f87122ed8e/java/src/main/java/ai/rapids/cudf/ColumnView.java#L2449 to concatenate all elements in one array to a string. 
To be consistent with Spark, this function should return `"[null, null]"` when the input array is `Array(null, null)`. However, these are what I get when I run the code on my desktop:
```
scala> import org.apache.spark.sql.types._
import org.apache.spark.sql.types._

scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> val schema = StructType(Array(StructField("a", ArrayType(IntegerType, true))))
schema: org.apache.spark.sql.types.StructType = StructType(StructField(a,ArrayType(IntegerType,true),true))

scala> val data0 = Seq(Row(Array(null, null)))
data0: Seq[org.apache.spark.sql.Row] = List([[Lscala.runtime.Null$;@3b58d05f])

scala> val df0 = spark.createDataFrame(spark.sparkContext.parallelize(data0), schema)
df0: org.apache.spark.sql.DataFrame = [a: array<int>]

scala> df0.withColumn("a", col("a").cast(StringType)).collect
21/11/24 09:18:52 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> cast(a#1 as string) AS a#3 will run on GPU
    *Expression <Cast> cast(a#1 as string) will run on GPU
  !NOT_FOUND <RDDScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.execution.RDDScanExec could be found
    @Expression <AttributeReference> a#1 could run on GPU

res0: Array[org.apache.spark.sql.Row] = Array([[]])                             

scala> val data1 = Seq(Row(Array(null, 1)))
data1: Seq[org.apache.spark.sql.Row] = List([[Ljava.lang.Object;@40c925a1])

scala> val df1 = spark.createDataFrame(spark.sparkContext.parallelize(data1), schema)
df1: org.apache.spark.sql.DataFrame = [a: array<int>]

scala> df1.withColumn("a", col("a").cast(StringType)).collect
21/11/24 09:19:32 WARN GpuOverrides: 
*Exec <ProjectExec> will run on GPU
  *Expression <Alias> cast(a#8 as string) AS a#10 will run on GPU
    *Expression <Cast> cast(a#8 as string) will run on GPU
  !NOT_FOUND <RDDScanExec> cannot run on GPU because no GPU enabled version of operator class org.apache.spark.sql.execution.RDDScanExec could be found
    @Expression <AttributeReference> a#8 could run on GPU

res1: Array[org.apache.spark.sql.Row] = Array([[null, 1]])
```
When the input is all-nulls-array, the output is `"[]"` (when `emptyStringOutputIfEmptyList` is set as `True`), or `"[null]"` ( when `emptyStringOutputIfEmptyList` is set as `False`). And when there exists one element that is not `null` (such as `Array(null, null, 1)`),  every `null` element in the array is converted to string `"null"`.

**Comment by HaoYang670** [comment]
```
scala> import org.apache.spark.sql._
import org.apache.spark.sql._

scala> import org.apache.spark.sql.types._
import org.apache.spark.sql.types._

scala> val schema = StructType(Array(StructField("a", ArrayType(IntegerType, true))))
schema: org.apache.spark.sql.types.StructType = StructType(StructField(a,ArrayType(IntegerType,true),true))

scala> val data0 = Seq(Row(Array(null, null)))
data0: Seq[org.apache.spark.sql.Row] = List([[Lscala.runtime.Null$;@1177049c])

scala> val df0 = spark.createDataFrame(spark.sparkContext.parallelize(data0), schema)
df0: org.apache.spark.sql.DataFrame = [a: array<int>]

scala> df0.withColumn("a", col("a").cast(StringType)).collect
res0: Array[org.apache.spark.sql.Row] = Array([[null, null]])

scala> val data1 = Seq(Row(Array(null, 1)))
data1: Seq[org.apache.spark.sql.Row] = List([[Ljava.lang.Object;@4f00ee48])

scala> val df1 = spark.createDataFrame(spark.sparkContext.parallelize(data1), schema)
df1: org.apache.spark.sql.DataFrame = [a: array<int>]

scala> df1.withColumn("a", col("a").cast(StringType)).collect
res1: Array[org.apache.spark.sql.Row] = Array([[null, 1]])
```
This is the result when I run the same code on Spark. You can see the difference between Spark and Spark-rapids when casting `df0` to string type.

**Comment by ttnghia** [comment]
A null element will result in a null after casting. You can then use `GpuCoalesce` to replace null by string literal "null".

**Comment by HaoYang670** [comment]
Thank you, I will try it

**Comment by HaoYang670** [comment]
I currently use GpuNvl to cast all `null`s to string before calling `stringConcatenateListElements`, so that it does not depend on `cudf` to process all nulls list. Thank you very much @ttnghia @jrhemstad @revans2  @sperlingxx
