### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by anamariaUIC** [rapidsai/cudf#9747]
**Describe the bug**

Hello,

I installed this library via:
anamaria@login-2[SABER]: ~ $ module load Python/3.7.4-GCCcore-8.3.0
anamaria@login-2[SABER]: ~ $ module load CUDA/11.1.1-GCC-10.2.0

anamaria@login-2[SABER]: ~ $ conda install -c rapidsai -c nvidia -c numba -c conda-forge cudf=21.08 python=3.7 cudatoolkit=11.1

Installation finished and I got message:
Your installed version is: 2.17

I started the same Python version (above) I used to install this and I got:
anamaria@login-2[SABER]: ~ $ python
Python 3.7.4 (default, Aug 10 2021, 17:30:40)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

            import cudf
            Traceback (most recent call last):
            File "", line 1, in
            ModuleNotFoundError: No module named 'cudf'
            import os
            import numpy as np
            import math
            import pandas as pd; print('Pandas Version:', pd.version)
            Pandas Version: 1.1.3
            import cudf; print('cuDF Version:', cudf.version)
            Traceback (most recent call last):
            File "", line 1, in
            ModuleNotFoundError: No module named 'cudf'

anamaria@login-2[SABER]: ~ $ module list

Currently Loaded Modules:

    bzip2/1.0.8-GCCcore-8.3.0 5) SQLite/3.29.0-GCCcore-8.3.0 9) Python/3.7.4-GCCcore-8.3.0 13) GCC/10.2.0
    ncurses/6.1-GCCcore-8.3.0 6) XZ/5.2.4-GCCcore-8.3.0 10) GCCcore/10.2.0 14) CUDAcore/11.1.1
    libreadline/8.0-GCCcore-8.3.0 7) GMP/6.1.2-GCCcore-8.3.0 11) zlib/1.2.11-GCCcore-10.2.0 15) CUDA/11.1.1-GCC-10.2.0
    Tcl/8.6.9-GCCcore-8.3.0 8) libffi/3.2.1-GCCcore-8.3.0 12) binutils/2.35-GCCcore-10.2.0

anamaria@login-2[SABER]: ~ $ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Please advise

**Steps/Code to reproduce bug**
Follow this guide http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports to craft a minimal bug report. This helps us reproduce the issue you're having and resolve the issue more quickly.

**Expected behavior**

**Environment overview (please complete the following information)**
 - Environment location: [Bare-metal, Docker, Cloud(specify cloud provider)]
 - Method of cuDF install: [conda, Docker, or from source]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**

**Comment by davidwendt** [comment]
This looks identical to #9743 
@anamariaUIC  did you mean to open a different issue?

**Comment by anamariaUIC** [comment]
@davidwendt Hi David, I didn't know if I posted my issue under the right queue (since it hasn't be assigned to anyone) so I posted it here. The issue is the same.

**Comment by beckernick** [comment]
Let's consolidate discussion in #9743 for clarity. Closing this issue.
