### ISSUE TITLE
[BUG] May the legacy pygdf documentation on readthedocs be deleted? 

### ISSUE THREAD

**Issue by PeterHuang2015** [rapidsai/cudf#975]
**Describe the bug**
May the legacy pygdf documentation on readthedocs be deleted? It might be misleading for newbie for searching official docs.

**Steps/Code to reproduce bug**
As [legacy pygdf doc link](https://pygdf.readthedocs.io/en/latest/) appear on top of google search results: https://www.google.com.hk/search?q=cudf+documentation&rlz=1C1GGRV_enCN803CN803&oq=cudf+documentation&aqs=chrome..69i57.6647j0j1&sourceid=chrome&ie=UTF-8 while there's almost empty there.

**Expected behavior**
All search queries would lead to [official documents](https://cudf.readthedocs.io/en/latest/) without any misleading info.

**Comment by randerzander** [comment]
Thanks for reporting this, @PeterHuang2015.

I've updated pygdf.readthedocs.io to point to a page that links to cuDF API docs instead.
