### ISSUE TITLE
[FEA] Let Pascal GPUs run latest RAPIDS on WSL2

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#9753]
**Is your feature request related to a problem? Please describe.**
Currently, Pascal processes cannot run RAPIDS on WSL2.  They emit CUDA Memory errors, such as  #9427 .  Later architectures are not affected by this issue.

**Describe the solution you'd like**
I can run RAPIDS on WSL2 with a Pascal GPU (like the one on my laptop)

**Describe alternatives you've considered**

- Running another GPU arch (Turning, Volta, Ampere)
- Running RAPIDS 21.08

**Comment by semenoffalex** [comment]
Please, make it happen. It's super annoying not being able to use the latest version of cudf.

**Comment by taureandyernv** [comment]
I regret to inform the community that despite our best attempts in our spare cycles, we could not find the root cause. This is now a `won't-fix`.  If you do have a WSL2 machine and need RAPIDS, and you have a system with a Pascal GPU, you can 

1. Install a newer GPU with [Compute Capability 7.0 or higher](https://developer.nvidia.com/cuda-gpus)
2. Use a cloud or network option from our [Quick Starts](https://rapids.ai/#quick-start) or [Deployment Guides](https://docs.rapids.ai/deployment/stable/)
3. Install RAPIDS 21.08 via Docker or Conda, [which was successful in](https://github.com/rapidsai/cudf/issues/11382#issuecomment-1252962753) #11382

Thanks @bdice, @davidwendt, @beckernick , and all the others who helped trying to track down a fix.
