### ISSUE TITLE
[QST] Can I Skip CMake FetchContent_Declare for rapids-cmake?

### ISSUE THREAD

**Issue by mixcheck** [rapidsai/cudf#9757]
**What is your question?**
I am using an internal network, so git clone is not possible...

Even if I download the zip file and try to install it, I can't get past the FetchContent part.

The blocked process is as follows.

-- in RAPIDS.cmake files
set(rapids-cmake-version 22.02)
include(FetchContent)
**FetchContent_Declare(
  rapids-cmake
  GIT_REPOSITORY https://github.com/rapidsai/rapids-cmake.git
  GIT_TAG        branch-${rapids-cmake-version}
)**
FetchContent_GetProperties(rapids-cmake)
if(rapids-cmake_POPULATED)
  if(NOT "${rapids-cmake-dir}" IN_LIST CMAKE_MODULE_PATH)
    list(APPEND CMAKE_MODULE_PATH "${rapids-cmake-dir}")
  endif()
else()
  FetchContent_MakeAvailable(rapids-cmake)
endif()

Can I skip this process? or Can you update the source files to build/install process not only git cloning phase but also your entire source file?

From other environment, I found the FetchContent make folders in cpp/build/_deps/*

Thanks

++ I fount some answers about skipping FETCH_CONTENT process...

https://stackoverflow.com/questions/66448309/can-i-block-or-skip-add-executable-from-third-party-repos-cmake-fetchcontent-de

**Comment by harrism** [comment]
@robertmaynard can you answer this?

**Comment by robertmaynard** [comment]
@mixcheck Yes you can do offline builds, but it does require a couple of small changes.

On a machine with internet access run the following
```
cmake -S <cudf_src> -B <build_directory> -DCPM_SOURCE_CACHE=<user>/cudf_offline_cache
cd <user>/cudf_offline_cache && git clone https://github.com/rapidsai/rapids-cmake.git
```
This will populate `cudf_offline_cache` with all the needed dependencies to build cudf. Now you will need to transfer this directory over to your offline machine so it has these dependencies.

On the offline machine ( presuming 22.02+ ) you will need to do the following:
```
cd <cudf_src>
echo "add_subdirectory(\${CPM_SOURCE_CACHE}/rapids-cmake)" > fetch_rapids.cmake
cmake -S <cudf_src> -B <build_directory> -DCPM_SOURCE_CACHE=<abs_path_to>/cudf_offline_cache
```
Now that the dependencies exist in the directory set by `CPM_SOURCE_CACHE` cudf will find it and not download from the internet. The exception to this is rapids-cmake, which the `echo` command will resolve for us.

**Comment by GregoryKimball** [comment]
Closing for now

**Comment by caork** [comment]
> [@mixcheck](https://github.com/mixcheck) Yes you can do offline builds, but it does require a couple of small changes.
> 
> On a machine with internet access run the following
> 
> ```
> cmake -S <cudf_src> -B <build_directory> -DCPM_SOURCE_CACHE=<user>/cudf_offline_cache
> cd <user>/cudf_offline_cache && git clone https://github.com/rapidsai/rapids-cmake.git
> ```
> 
> This will populate `cudf_offline_cache` with all the needed dependencies to build cudf. Now you will need to transfer this directory over to your offline machine so it has these dependencies.
> 
> On the offline machine ( presuming 22.02+ ) you will need to do the following:
> 
> ```
> cd <cudf_src>
> echo "add_subdirectory(\${CPM_SOURCE_CACHE}/rapids-cmake)" > fetch_rapids.cmake
> cmake -S <cudf_src> -B <build_directory> -DCPM_SOURCE_CACHE=<abs_path_to>/cudf_offline_cache
> ```
> 
> Now that the dependencies exist in the directory set by `CPM_SOURCE_CACHE` cudf will find it and not download from the internet. The exception to this is rapids-cmake, which the `echo` command will resolve for us.

when I transfer this directory to offline machine, the path changed:
cmake -S cpp -B build_directory -DCPM_SOURCE_CACHE=cudf_offline_cache
CMake Error: The current CMakeCache.txt directory /home/asus/offline_directory/cudf-24.10.00/build_directory/CMakeCache.txt is different than the directory /home/asus/working_directory/cudf-24.10.00/build_directory where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/asus/offline_directory/cudf-24.10.00/cpp/CMakeLists.txt" does not match the source "/home/asus/working_directory/cudf-24.10.00/cpp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
but if I replace all the path to new path, the hash changed:
[ 11%] Creating directories for 'rapids-cmake-populate'
[ 22%] Performing download step (download, verify and extract) for 'rapids-cmake-populate'
-- File already exists but no hash specified (use URL_HASH):
  file='/home/asus/offline_directory/cudf-24.10.00/build_directory/_deps/rapids-cmake-subbuild/rapids-cmake-populate-prefix/src/branch-24.10.zip'
Old file will be removed and new file downloaded from URL.
-- Downloading...
   dst='/home/asus/offline_directory/cudf-24.10.00/build_directory/_deps/rapids-cmake-subbuild/rapids-cmake-populate-prefix/src/branch-24.10.zip'
   timeout='none'
   inactivity timeout='none'
how to solve this? thanks" @GregoryKimball
