### ISSUE TITLE
[BUG] Issue in the documentation page display using pydata sphinx theme

### ISSUE THREAD

**Issue by mayankanand007** [rapidsai/cudf#9761]
**Describe the bug**
There seems to be an issue in the pydata sphinx theme that we use for the `cuDF` docs where when you scroll all the way down, text seems to get overwritten. [bottom left in the image below]

![cudf_docs](https://user-images.githubusercontent.com/36782063/143062968-58b745d2-b87c-431f-b2fa-ec1a6935a3a2.JPG)

**Steps/Code to reproduce bug**
Its there on all pages for me, eg: https://docs.rapids.ai/api/cudf/nightly/api_docs/series.html

**Expected behavior**
This shouldn't happen and the behavior should be the same as `pandas` docs here: https://pandas.pydata.org/docs/reference/series.html

**Comment by galipremsagar** [comment]
I can't seem to repro this issue on local builds, @ajschmidt8 I remember we do some post-processing on top of local builds for production hosting, could it be an issue in that step?

**Comment by ajschmidt8** [comment]
Yes, I think this is due to the post-processing. I think I found the issue. The sidebar height gets messed up since I insert some additional HTML elements. I will open a PR to adjust the CSS accordingly.

**Comment by ajschmidt8** [comment]
PR opened below.

- https://github.com/rapidsai/docs/pull/247

We will be able to preview the fix in the PR at the link shown in the screenshot below once that GitHub Check completes.

![image](https://user-images.githubusercontent.com/7400326/151375463-e30c2090-1ccb-4395-a7d8-c4e62d2d3cff.png)

**Comment by ajschmidt8** [comment]
Seems to be resolved now in the preview environment below.

https://deploy-preview-247--docs-rapids-ai.netlify.app/api/cudf/nightly/api_docs/series.html

Please confirm and then we can merge the PR and close this issue.

**Comment by galipremsagar** [comment]
It seems to be fixed. Thanks @ajschmidt8 Closing this issue.
