### ISSUE TITLE
[BUG] dtype definitions in read_csv fail and without definition are inferred incorrectly

### ISSUE THREAD

**Issue by quasiben** [rapidsai/cudf#977]
## Data

```
a,b,c
1.2,2017-01-09 11:13:28,N
1.2,2017-01-09 11:13:28,N
1.2,2017-01-09 11:13:28,N
```

**Without** defining a dtype the above data has an incorrect inferred dtype when parsing with `read_csv`

```python
In [3]: df = cudf.read_csv('dtype-test.csv')

In [5]: df.dtypes.values
Out[5]: array([dtype('float64'), dtype('<M8[ms]'), dtype('int32')], dtype=object)
```

**With** a dtype defined the above crashes
```python
In[8]: df = cudf.read_csv('dtype-test.csv', dtype=dict(a=dtype('float64'), b=dtype('<M8[ms]'), c=dtype('object')))
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Aborted
```

cc @kkraus14

**Comment by kkraus14** [comment]
We don't support `object` or `string` dtypes yet so this is expected.

**Comment by kkraus14** [comment]
We should fail much more gracefully than this though.

**Comment by mjsamoht** [comment]
With v0.7 TOT I get the following result.  Since we now support `NVStrings` I believe everything works as expected:

```
>>> df = cudf.read_csv('dtype-test.csv')
>>> df.dtypes.values
array([dtype('float64'), dtype('<M8[ms]'), dtype('O')], dtype=object)
>>> print(df)
     a                       b  c
0  1.2 2017-01-09T11:13:28.000  N
1  1.2 2017-01-09T11:13:28.000  N
2  1.2 2017-01-09T11:13:28.000  N
>>> 
```

@quasiben let me know if there is still an open issue to look into.  Otherwise, we can close this issue.

**Comment by mjsamoht** [comment]
@quasiben let me know if you still see this problem.  Otherwise, we'll go ahead and close this issue.
