### ISSUE TITLE
[QST] 'LIBCUDF_CUFILE_POLICY'='ALWAYS' Except Error 

### ISSUE THREAD

**Issue by EdisonZiXing** [rapidsai/cudf#9779]
Hello,everyone:
I wanna optimize the IO speed so I trying to use this code in python

**os.environ['LIBCUDF_CUFILE_POLICY'] = 'ALWAYS'**

But when I run with cudf.read_parquet(),such error excepted:

**RuntimeError: cuDF failure at: ../src/io/utilities/file_io_utilities.cpp:154: cuDF failure at: ../src/io/utilities/file_io_utilities.cpp:129: could not find cuFile cuFileDriverOpen symbol**

So could someone tell me which part I missed?
**Thx for who wanna replies!!!**

**Comment by vuule** [comment]
It's possible that cuFile is not installed or not available in your environment. Which CUDA toolkit version are you using?

**Comment by EdisonZiXing** [comment]
> It's possible that cuFile is not installed or not available in your environment. Which CUDA toolkit version are you using?
@vuule 
Dear vuule:
I'm using CUDA toolkit 11.5, should I installed the cuFile again?I thought it is a inline function of cuDF,could u give me more instructions or advice?
Thanks for replies vuule!!!

**Comment by vuule** [comment]
cuFile is a separate library, included in CUDA 11.4+ toolkits. cuDF loads cuFile at runtime and it looks like this is the part that fails.
Please check if `libcufile.so` is present in your cuda install directory, and if `LD_LIBRARY_PATH` is set correctly.

**Comment by vuule** [comment]
Closing since there's no response from the requester. Please reopen if this issue is still relevant.

**Comment by pavithra16-prog** [comment]
> CUDA

So, in CUDA version 11.4 also, this will work right ?

Thank you

**Comment by pavithra16-prog** [comment]
> cuFile is a separate library, included in CUDA 11.4+ toolkits. cuDF loads cuFile at runtime and it looks like this is the part that fails. Please check if `libcufile.so` is present in your cuda install directory, and if `LD_LIBRARY_PATH` is set correctly.

So, in **CUDA version 11.4** also, this will work right ? (setting environment variable LIBCUDF_CUFILE_POLICY=ALWAYS)

Thank you

**Comment by pavithra16-prog** [comment]
How to install cuFile library for CUDA 11.4 ?

**Comment by vuule** [comment]
cuFile library should be installed with CUDA 11.4. There are a few additional steps to enable its use, described in 
https://docs.nvidia.com/gpudirect-storage/troubleshooting-guide/index.html#troubleshoot-install

**Comment by pavithra16-prog** [comment]
I am using GPU from a Google Cloud Virtual Machine instance, so, how to install GDS in this ?

**Comment by pavithra16-prog** [comment]
> I am using GPU from a Google Cloud Virtual Machine instance, so, how to install GDS in this ?

Should i follow the same steps as given in that link ?
because, i am not able to disable iommu (not found error).
Also, how to find whether my platform is DGX or non-DGX?

**Comment by vuule** [comment]
> I am using GPU from a Google Cloud Virtual Machine instance, so, how to install GDS in this ?

 Unfortunately, there's no way to set up GDS in this use case (cloud).

**Comment by pavithra16-prog** [comment]
> > I am using GPU from a Google Cloud Virtual Machine instance, so, how to install GDS in this ?
> 
> Unfortunately, there's no way to set up GDS in this use case (cloud).

Ohh Okay, thanks, but is there any other way in Google cloud vm instance through which I can bring the data directly from SSD (Storage) to GPU memory during computation (any specific function in Python or ...)?

**Comment by pavithra16-prog** [comment]
No, actually I am doing a project where I am analysing storage bottleneck in GPUs, so I wanted to get the time taken when data is taken directly from SSD. So, no problem, if VM does not support this.
