### ISSUE TITLE
[FEA] libcudf should provide a generic `scan` function

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#978]
**Is your feature request related to a problem? Please describe.**
Currently `libcudf` only supports an inclusive/exclusive prefix sum operation. A prefix sum is a specialization of the more generic `scan` operation that supports other operations such as `min`, `max`, and `product`. If I want to compute one of these other scan operations, there is no way for me to do so with the current `libcudf`.

**Describe the solution you'd like**

`gdf_prefixsum` should be renamed to `gdf_scan` and should add an `enum` parameter that selects among the supported scan operations: `sum`, `min`, `max`, `product`.

**Comment by kovaltan** [comment]
Do we also need `sum_of_squares` ? 
`reduction` also support it.

**Comment by jrhemstad** [comment]
> Do we also need `sum_of_squares` ?
> `reduction` also support it.

I don't believe we need a `scan` equivalent of `sum_of_squares`.

> Do we also need generic `reduction` function?

Yes, that would be ideal. That's what I described in  https://github.com/rapidsai/cudf/issues/954 as additional work to be done.
