### ISSUE TITLE
[BUG] ORC writing failed when table is empty

### ISSUE THREAD

**Issue by sperlingxx** [rapidsai/cudf#9783]
**Describe the bug**
When writing an empty table, whose number of rows is 0, via cuDF ORC writer, it will throw a CUDA exception: `for_each: failed to synchronize: cudaErrorInvalidConfiguration: invalid configuration argument`.
If there exists empty string columns, the `build_dictionaries` method inside `writer::impl::write` will lead to a segmentation fault.

**Steps/Code to reproduce bug**
Writes an empty table through `cudf::io::orc_chunked_writer`.

**Comment by vuule** [comment]
Got local repro.
Looks like the issue is specific to writing files with Snappy compression.
Working on a fix.

**Comment by vuule** [comment]
Implemented the fix in https://github.com/rapidsai/cudf/pull/9808, will add more tests tomorrow and open for review.
