### ISSUE TITLE
[BUG] > 10x performance regression in dispatch_equality_op for 21.12 vs 21.10

### ISSUE THREAD

**Issue by revans2** [rapidsai/cudf#9795]
**Describe the bug**
We are still working to trace some things down, but we saw a huge performance regression in TPC-DS query 28 in 21.12.  When doing some profiling it appears to all be.

void cudf::binops::compiled::for_each_kernel<cudf::binops::compiled::dispatch_equality_op(cudf::mutable_column_device_view &, const cudf::column_device_view &, const cudf::column_device_view &, bool, bool, cudf::binary_operator, rmm::cuda_stream_view)::[lambda(int) (instance 1)]>(int, T1)

Specifically it is doing >= and <= comparisons on integers in the query.

I will attache the traces that I have for them.

If you look at individual calls to this kernel it is 6.365 - 11.874 ms for 21.12 vs 187 - 272 us for 21.10. So that is at least a 23x time increase.

**Comment by jrhemstad** [comment]
@karthikeyann can you look at this?

**Comment by revans2** [comment]
So it looks like for AND we are doing an `equalToNullAware` to match with what Spark is doing which appears to be the regression.  The other kernels are fast.

**Comment by revans2** [comment]
We are doing similar things for both `AND` and `OR` operations to match the Spark semantics.  So it appears that we are doing `NULL_EQUALS` on two boolean column vectors, and that is where the performance degradation is happening.

**Comment by jlowe** [comment]
It appears to be related to the decimal128 changes.  If I roll back to this commit:
```
commit 0da63f0e0129e987111469248c8d9bb4f6b18290 (HEAD)
Author: Ashwin Srinath <3190405+shwina@users.noreply.github.com>
Date:   Tue Nov 16 15:18:34 2021 -0500

    Update copyright text on resample.py (#9701)
    
    Co-authored-by: Ashwin Srinath <shwina@users.noreply.github.com>
```
then I don't see the performance regression.  However if I pull in just the next two commits:
```
9aefbc2750 (HEAD) Java Support for Decimal 128 (#9485)
c1f20c7be6 Add support for `decimal128` (#9483)
```
then I see the performance regression.

**Comment by revans2** [comment]
So I wrote some micro benchmarks to try and get an idea of the performance changes for a few binops between 21.10 and the current 21.12 code. I need to check to be 100% positive, but I think 21.10 was compiled with CUDA 11.2, but the 21.12 was compiled with CUDA 11.5. So there are likely to be some compiler differences too. I tried to compile cudf 21.10 with CUDA 11.5, but I got compile errors and having been through some of this when we started work on the dec128 branch I know it is not super simple to get working properly.

The micro-benchmark is for a query.
```scala
spark.time(spark.range(Int.MaxValue * 5L).selectExpr(s"CAST(id%100 AS ${TEST_TYPE}) AS id1", s"CAST(id%50 AS ${TEST_TYPE}) as id2").selectExpr(s"MAX(id1 ${TEST_OP} id2)").show())
```

The following is a table of the results.

|OP & VER/TYPE | LONG | INT | BYTE | DECIMAL(8,0) | DECIMAL(15,0) | DECIMAL(30,0)
|-- | -- | -- | -- | -- | -- | --
|<=> 21.12 | 5376 | 5647 | 5480 | 13663 | 14258 | 6469
|<=> 21.10 | 1044 | 1303 | 1144 | 2684 | 2958 | N/A
|= 21.12 | 1000 | 1265 | 1111 | 9150 | 9775 | 2091
|= 21.10 | 1052 | 1303 | 1104 | 2707 | 2931 | N/A
|>= 21.12 | 1002 | 1265 | 1103 | 9172 | 9836 | 2094
|>= 21.10 | 1043 | 1286 | 1104 | 2664 | 2930 | N/A

I also ran one set of tests for 
```scala
spark.time(spark.range(Int.MaxValue * 5L).selectExpr("id", "id as id2").selectExpr("MAX(id <=> id2)").show())
```

To try and measure the overhead of the mod(`%`) operations. For both types the difference in time was almost exactly 630 ms. So I am hoping that there are not big differences in the CAST operation between the versions either.

A few takeaways from this.

1. The `<=>` operator (null safe equals) got a lot slower for more types than just boolean.
2. Decimal operations for `=` and `>=` got much slower. For DECIMAL32 vs INT32 they went from an overhead of about 2x to about 7x, and for DECIMAL64 vs INT64 it went from 2.8x to about 9.8x. This is especially bad for the Spark plugin because we know that the scale is the same between both sides so we should be able to bit cast them to the correct INT type and get a huge speedup.
3. DECIMAL128 does not have the same issues as DECIMAL64 or DECIMAL32. It is faster than they are for some reason.
4. For int types the other operators `=` and `>=`, which each are launched slightly differently, appear to actually get slightly faster in 21.12. Note: I only had 3 data points in each measurement. I ran them on an a6000 that was also handling my graphics. But the deviation between the runs was really small so I think it is real.

@karthikeyann I am not sure if you want me to file separate issues for each of these or not.  The one big one we see right now that is impacting the query time is just null safe equals for BOOL8. But I thought the extra information might help to narrow it down. The others are less important and so if they are not fixed as a part of this I will file separate follow on issues for them.

**Comment by karthikeyann** [comment]
@revans2 I understand it's compiled with CUDA 11.5
Which CUDA runtime version is this benchmark running on? 11.5 or 11.2 or 11.0

**Comment by revans2** [comment]
They are all running under 11.5

**Comment by robertmaynard** [comment]
Can we close this with https://github.com/rapidsai/cudf/pull/9816 being merged?

**Comment by revans2** [comment]
I am fine with it. I didn't close it because there were still some binops that were slower and I didn't know what others wanted to do to be sure that was not lost.

**Comment by robertmaynard** [comment]
@revans2 I am out of the loop, what binops are still slower?

**Comment by revans2** [comment]
> @revans2 I am out of the loop, what binops are still slower?

https://github.com/rapidsai/cudf/pull/9816#issuecomment-984347836

**Comment by karthikeyann** [comment]
@revans2 Benchmark times for large input were back to normal for all benchmarks in  https://github.com/rapidsai/cudf/pull/9816#issuecomment-985498914 (click Benchmark Details)
Run these benchmarks again to confirm in 21.12 and 22.02 and we can close this.
