### ISSUE TITLE
[BUG] dtypes not preserved with zero rows

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/cudf#981]
In the following example I would expect the dtypes to not change as I call `head`

```python
import cudf
df = cudf.DataFrame({'x': [1, 2]})

>>> df.dtypes
x    int64
dtype: object

>>> df.head(0).dtypes
x    float64
dtype: object
```

**Comment by mrocklin** [comment]
This is important for Dask because we often carry around empty dataframes as metadata.  If the dtypes are not preserved then we get caught up on that frequently.

**Comment by mrocklin** [comment]
I believe that this is still live.  Reopening.

```python
In [1]: import cudf

In [2]: s = cudf.Series([True, False])

In [3]: s.dtype
Out[3]: dtype('bool')

In [4]: s.head(0).dtype
Out[4]: dtype('int8')
```

**Comment by kkraus14** [comment]
> I believe that this is still live. Reopening.
> 
> ```python
> In [1]: import cudf
> 
> In [2]: s = cudf.Series([True, False])
> 
> In [3]: s.dtype
> Out[3]: dtype('bool')
> 
> In [4]: s.head(0).dtype
> Out[4]: dtype('int8')
> ```

This looks to be isolated to boolean dtypes, likely because we use an int8 numba device array underneath. Exploring.
