### ISSUE TITLE
[FEA] Arrow to SSTables converter

### ISSUE THREAD

**Issue by mughetto** [rapidsai/cudf#9811]
**Is your feature request related to a problem? Please describe.**
I wish I could use cudf to preprocess my data and write the results in SSTables so that I could bulk load my Cassandra instance with `sstableloader`.

**Describe the solution you'd like**
A new method to write sstables:
cudf.Dataframe.to_sstables("foo.db")

**Additional context**
Recently Datastax contributed a way to analyze Cassandra data with RAPIDS:
https://developer.nvidia.com/blog/analyzing-cassandra-data-using-gpus-part-2/

It took the form of https://github.com/datastax/sstable-to-arrow

The opposite transform would allow us to prepare ready-to-use tables for Cassandra directly in our GPU workflow.

**Comment by beckernick** [comment]
Glad to hear you'd like to use RAPIDS to analyze Cassandra data @mughetto 

I'm not well versed in the SSTable file format, but I wonder if this feature request makes more sense on the Apache Arrow project itself. Perhaps you might be interested in opening discussion there? From the sstable-to-arrow repository README, it looks like the Arrow Java API is doing much of the heavy lifting

**Comment by mughetto** [comment]
Hey @beckernick 

good point, I came from the RAPIDS side into it, so the Slack server and this board was my first stop. Let me try to ask on the datastax board first, maybe with their experience in sstables to arrow they can also help/orient us for the inverse operation.

**Comment by mughetto** [comment]
For the record, I also opened a feature request with Cassandra:
https://issues.apache.org/jira/browse/CASSANDRA-17201

**Comment by pi-guy-in-the-sky** [comment]
Hello, my apologies for the slow reply! Unfortunately, sstable-to-arrow doesn't support the inverse operation from RAPIDS to Cassandra, and the project isn't currently being actively maintained. Perhaps you could check out the [dsbulk](https://docs.datastax.com/en/dsbulk/doc/dsbulk/reference/dsbulkCmd.html) tool to see if that meets your needs?

**Comment by mughetto** [comment]
Hi Alex,

thanks for the feedback. I did look in dsbulk before but I think I ended up discarding it because it also requires to go through a parquet -> CSV step.

I'll have another look at it if sstable-to-arrow is not maintained anymore.

**Comment by vyasr** [comment]
I'm going to close this for now since it seems from the above discussion that the best path here is to convert cudf objects to host arrow objects and then interconvert from there again, but feel free to reopen if there is a compelling reason to support this directly in cudf.
