### ISSUE TITLE
[FEA] convert_datetime.cu should use proper chrono types for timestamp/duration handling

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9812]
**Is your feature request related to a problem? Please describe.**

The functionality in [`convert_datetime.cu`](https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/src/strings/convert/convert_datetime.cu#L205) parses timestamps using plain integers instead of `chrono` types. This should be avoided as it leads to problems like this: https://github.com/rapidsai/cudf/pull/9793 

**Describe the solution you'd like**

Use appropriate `chrono` types and functions

**Comment by davidwendt** [comment]
It appears the chrono classes do not handle negative timestamps
https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L720-L724

The chrono classes are being used wherever possible:
https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L315-L320
https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L598-L601

and have been helpful in handling tricky calculations like:
- day-of-week: https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L781-L782
- week-of-year: https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L888-L896
- especially in handling ISO weeks and ISO years: https://github.com/rapidsai/cudf/blob/dad51a548e7460ba96ce1b395a3ae6c4645e78dd/cpp/src/strings/convert/convert_datetime.cu#L858-L859

I don't believe there is anything left in this file that can benefit from the chrono classes.
Therefore, I'd like to close this issue.
