### ISSUE TITLE
[FEA] Dispatch to different binary op kernels for common data types

### ISSUE THREAD

**Issue by jrhemstad** [rapidsai/cudf#9813]
**Is your feature request related to a problem? Please describe.**

The compiled binary ops use device side dispatch for the input data types. 

It currently has logic that will do a single vs double type dispatch in the same operator based on the existence of a common data type between the inputs.

https://github.com/rapidsai/cudf/blob/fc82b1d206e93a46c9ef3535711c88ec20bd4fde/cpp/src/binaryop/compiled/binary_ops.cuh#L196-L209

This expands out to a very large number of switch statements that clearly causes problems for the optimizer (see https://github.com/rapidsai/cudf/pull/9802).

**Describe the solution you'd like**

Instead of doing single vs double type dispatch in device code, there should be separate kernels for single vs double type dispatch and we should dispatch to those different kernels from host code.

**Comment by robertmaynard** [comment]
Closing issue as #9816 has been merged
