### ISSUE TITLE
[FEA] Remove DataFrame._repr_pandas025_formatting.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#9824]
**Is your feature request related to a problem? Please describe.**
It appears that the function [`DataFrame._repr_pandas025_formatting`](https://github.com/rapidsai/cudf/blame/39a3050a200b7728def8bd2cc14bf27e8dbc9279/python/cudf/cudf/core/dataframe.py#L1679) is only called once, in a test: https://github.com/rapidsai/cudf/blob/31f92d70bdf5b80434d24b6883e45496dbe85042/python/cudf/cudf/tests/test_repr.py#L101

It is failing a doctest (#9815) because the variable `gdf` is not defined:
https://github.com/bdice/cudf/blob/39a3050a200b7728def8bd2cc14bf27e8dbc9279/python/cudf/cudf/core/dataframe.py#L1687-L1704

**Describe the solution you'd like**
This function could be removed from the API of `cudf.DataFrame` and its logic could be implemented in the test code.

**Comment by vyasr** [comment]
I thought I had already addressed this. I think it must be in a branch that I haven't made a PR for yet, I'll push that out sometime before the next release.

**Comment by bdice** [comment]
@vyasr If you have a branch removing this and want to push, that'd be helpful. We're getting down to the last few failures in #9815.

**Comment by vyasr** [comment]
I should be able to get to this tomorrow.

**Comment by vyasr** [comment]
I stitched together the changes from a few cleanup stashes/branches and pushed them to #9922, which should resolve this.
