### ISSUE TITLE
[BUG] DataFrame.reindex behavior differs from pandas

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#9827]
**Describe the bug**
The behavior of `DataFrame.reindex` fails doctests and differs from pandas. From a preliminary discussion in our dev meeting, we may have the behavior that we intend already in place -- this issue can be closed if we choose to keep the current implementation and update the doctests in #9815 to match.

**Steps/Code to reproduce bug**
This doctest (#9815) fails:
https://github.com/rapidsai/cudf/blob/582cc6e466c7d941e1b34893fd56fbd42fe90d68/python/cudf/cudf/core/dataframe.py#L2254-L2272

Below is the doctest output:
```python
File "/home/bdice/code/cudf/python/cudf/cudf/core/dataframe.py", line 2289, in DataFrame.reindex
Failed example:
    df_new
Expected:
       key   val  sum
    0    0  10.0  NaN
    3    3  13.0  NaN
    4    4  14.0  NaN
    5   -1   NaN  NaN
Got:
        key   val   sum
    0     0  10.0  <NA>
    3     3  13.0  <NA>
    4     4  14.0  <NA>
    5  <NA>  <NA>  <NA>
```

**Expected behavior**

Pandas gives the following output (uses `NaN` instead of `<NA>`, and casts the column `key` to type `float64`):
```python
>>> pd.DataFrame({'key': [0, 1, 2, 3, 4], 'value': [10.0, 11.0, 12.0, 13.0, 14.0]}).reindex(index=[0, 3, 4, 5], columns=['key', 'value', 'sum'])
   key  value  sum
0  0.0   10.0  NaN
3  3.0   13.0  NaN
4  4.0   14.0  NaN
5  NaN    NaN  NaN
```

**Comment by shwina** [comment]
I think here we have the right behaviour. All our types are nullable, so we  can afford to use `<NA>` as a null value and avoid casting things to  `float`. We may need a way of telling doctests to not check the result dtypes when necessary (similar to the `check_dtype=False` argument to `assert_frame_equal` in pytests).

**Comment by bdice** [comment]
@shwina Awesome, thanks for confirming. I will update the doctest and close this issue.

> We may need a way of telling doctests to not check the result dtypes when necessary (similar to the `check_dtype=False` argument to `assert_frame_equal` in pytests).

No additional changes are necessary beyond updating the output of the example in 699c21aafc1f604a41dac954bbbe87ddefe8a5f5. Doctests execute the commands and compare the printed output. In some sense, doctests are a test of the REPL environment and validate the workings of `repr` / `str` methods.
