### ISSUE TITLE
[FEA] Keeping up with arrow realses 

### ISSUE THREAD

**Issue by nirandaperera** [rapidsai/cudf#9844]
**Is your feature request related to a problem? Please describe.**
Since Cudf is following a 2 month release cycle, is it possible to upgrade to the latest Apache Arrow version (which follows a 3 month release cycle) at every release?

**Describe the solution you'd like**
Upgrade to the latest Arrow version in every release

**Describe alternatives you've considered**
n/a

**Additional context**
I am working on a project that uses Cudf and Arrow. It would be nice to be able to use the latest features of both the projects.

**Comment by beckernick** [comment]
There is currently an open PR to upgrade to the latest arrow release (https://github.com/rapidsai/cudf/pull/9686), which will close the associated issue that was opened shortly after the official arrow release https://github.com/rapidsai/cudf/issues/9645 .

Release cadences across various projects can make it challenging to quickly upgrade dependencies depending on the release timing, but we have a goal of keeping up with Arrow releases.

Given we have an open issue to upgrade to Arrow 6.0, I'm going to close this issue as answered. Please feel free to re-open it.
