### ISSUE TITLE
[FEA] Make replace_re multine behavior consistent with contains_re

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#9845]
**Is your feature request related to a problem? Please describe.**

Given the input string `"A\nB\nC"` and the regexp pattern `"^B"`, `contains_re` will not find a match but `replace_re` will.

**Describe the solution you'd like**
I would like `replace_re` to match the behavior of `contains_re` where `^` only matches the start of the string and does not match newlines within the string.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by davidwendt** [comment]
I can add the `regex_flags` parameter to `replace_re` like it is in `contains_re` so that the `^` and `$` matching behavior should be the same.

**Comment by andygrove** [comment]
That sounds great. Thanks @davidwendt
