### ISSUE TITLE
[FEA] Implement version of string::split that accepts a regular expression for the delimiter

### ISSUE THREAD

**Issue by andygrove** [rapidsai/cudf#9862]
**Is your feature request related to a problem? Please describe.**
I would like to make the GPU implementation of Spark's `split()` function support regular expressions for the delimiter.

**Describe the solution you'd like**
I would like a version of the cuDF `string::split` function that accepts a regular expression for the delimiter

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by davidwendt** [comment]
I believe this feature request already exists as #3584
