### ISSUE TITLE
`lists::contains()` needs to switch to use `cudf::nullate`

### ISSUE THREAD

**Issue by mythrocks** [rapidsai/cudf#9869]
This is a follow-on issue from #9510.

The backend code for `lists::contains()` and `lists::index_of()` currently use `bool`s in `lookup_functor` for branching on whether the `search_keys` contain null elements. This would be a whole lot neater if `cudf::nullate` were used instead.

This would require `cudf::make_pair_rep_iterator` to support `nullate` first, which obfuscates the already drawn out change in #9510. The proposed switch to `cudf::nullate` will ideally be a focused change, handled separately.

**Comment by mythrocks** [comment]
The code here is currently under modification, to support `STRUCT` keys. We can consider this issue afterwards.

**Comment by bdice** [comment]
@divyegala Can this be closed by your recent changes in #13810?

**Comment by davidwendt** [comment]
Definitely looks like this logic is using nullate now.
