### ISSUE TITLE
[FEA] Implement `DatetimeProperties.date`

### ISSUE THREAD

**Issue by charlesbluca** [rapidsai/cudf#9877]
**Is your feature request related to a problem? Please describe.**
In Pandas, it is possible to extract the date from a column of datetime objects using the `date` attribute of the `DatetimeProperties`:

```python
import cudf

gsr = cudf.Series(cudf.date_range("2000", freq='s', periods=6))
psr = gsr.to_pandas()

psr.dt.date
0    2000-01-01
1    2000-01-01
2    2000-01-01
3    2000-01-01
4    2000-01-01
5    2000-01-01
dtype: object
```

This attribute doesn't exist in cuDF's `DatetimeProperties`:

```python
gsr.dt.date
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-53087fa7f6a3> in <module>
----> 1 gsr.dt.date

AttributeError: 'DatetimeProperties' object has no attribute 'date'
```

**Describe the solution you'd like**
It would be nice to have a `date` attribute for the `DatetimeProperties` to match up with the one in Pandas.

**Describe alternatives you've considered**
It is possible to compute roughly the same series using `strftime`:

```python
gsr.dt.strftime("%Y-%m-%d")
0    2000-01-01
1    2000-01-01
2    2000-01-01
3    2000-01-01
4    2000-01-01
5    2000-01-01
dtype: object
```

I'm not sure if there's a more performant way to achieve this using `_get_dt_field`.

**Additional context**
This is coming up as a blocker for some datetime casting work in https://github.com/dask-contrib/dask-sql/pull/343. If it is reasonably performant to use `strftime` here we can use that instead of `date`.

**Comment by beckernick** [comment]
I believe this is a duplicate of https://github.com/rapidsai/cudf/issues/7880

@charlesbluca can we consolidate discussion in that issue?

**Comment by charlesbluca** [comment]
Sure!
