### ISSUE TITLE
[FEA] Implement `drop_duplicates` for range values without sorting

### ISSUE THREAD

**Issue by ttnghia** [rapidsai/cudf#9886]
Currently, `cudf::drop_duplicates` uses sorting to check for duplicates, then copies the unique values to the result column. This is inefficient if the input values are known to be within some range like `[0, size)` as we can use a label array to check for the existence of the input and copy the unique values in `O(n)` time. In particular, a more efficient approach for dropping duplicates can be:
 * Allocate an `int8_t` label array of size `size`, fill it with `0`
 * For each input value `val`, assign `label[val] = 1`
 * For the indices `i` iterating from `0` to `size`, copy `i` to the output array if `label[i] == 1`.

The approach above is just a simple hashing solution---I tried to use just plain array for simplicity and performance.

As such, we can add a new API called `drop_duplicate_range`, or just add an overload of `drop_duplicate` that accepts an additional `size` parameter. The new API will use that approach for efficiently handling ranged data.

**Comment by jrhemstad** [comment]
I don't think there'd be much value in adding a custom algorithm for "ranged" data over just having a hash-based drop duplicate algorithm. See https://github.com/rapidsai/cudf/issues/9413

**Comment by ttnghia** [comment]
The reason I filed this issue is hoping that we can get some performance gain by using plain array over "ranged" data. 
Anyway, if just has-based approach is enough then I'm going to close this.
