### ISSUE TITLE
[BUG] Read CSV is corrupting String Data

### ISSUE THREAD

**Issue by taureandyernv** [rapidsai/cudf#989]
Code

```
import cudf
import cuml
df = cudf.read_csv("data/nytaxi/nytaxi_pre_mapd_200k.csv")
df.to_pandas().to_csv('foo2.csv', index=False)
```

This was my output.  Note the ```vendor_id```, ```store_and_fwd_flag```, and ```payment_type```

The vendor id and the payment type are the same.   Store and fwd flag seems to work although I'm not sure why it gives negative numbers.   These are the dtypes

vendor_id                          int32
rate_code                          int64
store_and_fwd_flag                 int32
passenger_count                    int64
trip_time_in_secs                  int64
trip_distance                    float64
pickup_longitude                 float64
pickup_latitude                  float64
dropoff_longitude         datetime64[ms]
dropoff_latitude          datetime64[ms]
tolls_amount                     float64
tip_amount                       float64
total_amount                     float64
mta_tax                          float64
fare_amount                      float64
payment_type                       int32
surcharge                        float64
pickup_datetime_year               int64
pickup_datetime_month              int64
pickup_datetime_day                int64
pickup_datetime_hours              int64
dropoff_datetime_year              int64
dropoff_datetime_month             int64
dropoff_datetime_day               int64
dropoff_datetime_hours             int64
dtype: object
![no change payment type](https://user-images.githubusercontent.com/46935140/53037439-1449d100-342f-11e9-9507-cfdde30e162b.png)
![change on saff not anything else](https://user-images.githubusercontent.com/46935140/53037440-1449d100-342f-11e9-81bb-2627ab94cc10.png)

The data is the 200k NYC taxi cab data

**Comment by kkraus14** [comment]
You need to use `read_csv_strings`

**Comment by taureandyernv** [comment]
Hey, after chatting with Randy, I re-titled the issue to be more clear.  `read_csv_strings`, while informative, was sadly a red herring.  I feel that we need to reopen and investigate this issue.

`read_csv` is not hashing the strings properly, as it creates duplicate values for dissimilar strings.  I created a smaller file to showcase the behavior.  You can see in the payment method is varied in this text version of `test csv`: 
```vendor_id, store_and_fwd_flag, payment_method
CMT, Y, CSH
CMT, N, CRD
CMT, N, CSH
CMT, Y, CRD
VST, Y, CSH
VST, N, CRD
VST, N, CSH
VST, Y, CRD```

However, running this, 
```import cudf
df = cudf.read_csv("data/nytaxi/test.csv") #just put it in the same directory as the taxi data
print(df)```

yields this result
```   vendor_id  store_and_fwd_flag  payment_method
0 -285570274         -1586344742     -1199149054
1 -285570274           387199968     -1199149054
2 -285570274           387199968     -1199149054
3 -285570274         -1586344742     -1199149054
4 -285570274         -1586344742     -1199149054
5 -285570274           387199968     -1199149054
6 -285570274           387199968     -1199149054```

Vendor ID and payment methods are all hashed into the same value.  Single character strings are hashed properly.  Also, for some reason, there's 1 less row.  It processes 7 instead of 8. 

```print('nrows', len(df))```
```nrows 7```

**Comment by randerzander** [comment]
A simpler repro..

I'm not sure if dtype inference is supposed to work for hashing strings.. @mjsamoht can you comment?

Test 1: Using dtype inference
```
import cudf

lines = """
CMT, Y, CSH
CMT, N, CRD
CMT, N, CSH
CMT, Y, CRD
VST, Y, CSH
VST, N, CRD
VST, N, CSH
VST, Y, CRD
"""

fn = 'test.csv'
with open(fn, 'w') as fp:
    fp.write(lines.strip())
df = cudf.read_csv('test.csv')
print(df)
```

Result:
```

       CMT           Y         CSH
0 65148228   387199968 -1235226407
1 65148228   387199968 -1235226407
2 65148228 -1586344742 -1235226407
3 65148228 -1586344742 -1235226407
4 65148228   387199968 -1235226407
5 65148228   387199968 -1235226407
```
In the above, if you don't specify dtypes, strings get hashed, but all to the same value.

Test 2: When specifying dtypes, hashing is working as expected:
```
dtypes = ['int', 'int', 'int']
df = cudf.read_csv('test.csv', dtype=dtypes)
print(df)
```

Result 2:
```
   CMT    Y  CSH
0 2226   30 2260
1 2226   30 2274
2 2226   41 2260
3 4186   41 2274
4 4186   30 2260
5 4186   30 2274
```

**Comment by j-ieong** [comment]
Hi @randerzander, to clarify you wish to have the strings hashed rather than be maintained as strings correct?

What cudf version are you using?
We fixed a bug with string hashing with PR #927, to be in the 0.6.0 release. It should fix the issue of same hash, due to not taking into account start offset of the field.

**Comment by randerzander** [comment]
@taureandyernv were you building from source in branch-0.6, or using the 0.5 container or..?

**Comment by taureandyernv** [comment]
Used 0.5.1 after pulling latest docker.  confirming source `branch 0.6` hashes correctly.  Will update notebook text to advise others to use 0.6 for this notebook.  Will add notebook to be release schedule for 0.6 docker container
