### ISSUE TITLE
[BUG] Setting a float into an int dtype series through iloc should cast the series

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/cudf#9913]
**Describe the bug**
Setting a float into a pandas series of int dtype should cast the series to float, but what happens now is the incoming scalar gets rounded and the series remains int dtype.

**Steps/Code to reproduce bug**
```python
>>> psr = pd.Series([1,2,3])
>>> gsr = cudf.Series([1,2,3])
>>> psr
0    1
1    2
2    3
dtype: int64
>>> gsr
0    1
1    2
2    3
dtype: int64
>>> psr.iloc[1] = 0.5
>>> gsr.iloc[1] = 0.5
>>> psr
0    1.0
1    0.5
2    3.0
dtype: float64
>>> gsr
0    1
1    0
2    3
dtype: int64
```

**Expected behavior**
We should get the same thing as pandas here.

**Environment overview (please complete the following information)**
22.02

**Environment details**
Please run and paste the output of the `cudf/print_env.sh` script here, to gather any other relevant environment details

**Additional context**
Came up during https://github.com/rapidsai/cudf/issues/8693

**Comment by wence-** [comment]
Fixed by #12074
