### ISSUE TITLE
[BUG] 2D Array Assignment

### ISSUE THREAD

**Issue by aerdem4** [rapidsai/cudf#9928]
**Describe the bug**
When I try to set 2D cupy array to some columns of cudf dataframe, it doesn't work correct. I get same value for the whole row. So it is like it is setting one column of 2D array to all columns of cudf dataframe.

**Steps/Code to reproduce bug**
`df[[f"f_{i}" for i in range(n)]] = cp.random.randn(m, n)
`

**Expected behavior**
It should correctly set 2D arrays to columns like it can be done in pandas.

**Workaround**
```
for i in range(n):
    df[f"f_{i}"] = cp.random.randn(m)
```

**Environment overview (please complete the following information)**
Fresh RAPIDS 21.12 conda installation on Ubuntu 20.04

**Comment by beckernick** [comment]
This seems similar to another issue we resolved: https://github.com/rapidsai/cudf/issues/8672

```python
import pandas as pd
import numpy as np
​
m, n = 5, 3
​
df = pd.DataFrame({f"f_{i}":range(m) for i in range(n)})
df[[f"f_{i}" for i in range(n)]] = np.random.randn(m, n)
print(df)
        f_0       f_1       f_2
0 -1.145855 -1.925980 -0.888776
1 -1.197261 -0.259193  3.517007
2  0.233636 -0.435549 -1.525251
3 -0.322054 -0.423073 -0.802210
4 -1.017598 -0.881462 -0.382520
```
```python
import cudf
import numpy as np
​
m, n = 5, 3
​
df = cudf.DataFrame({f"f_{i}":range(m) for i in range(n)})
df[[f"f_{i}" for i in range(n)]] = cp.random.randn(m, n)
print(df)
        f_0       f_1       f_2
0 -0.274912 -0.274912 -0.274912
1 -0.889039 -0.889039 -0.889039
2  0.049632  0.049632  0.049632
3  0.605849  0.605849  0.605849
4  0.766410  0.766410  0.766410
```
