### ISSUE TITLE
__syncthreads Using help

### ISSUE THREAD

**Issue by lixiaolx** [rapidsai/cudf#9936]
When writing the cuda code, I encountered the need to write the __syncthreads() function in the .cuh file, but a compilation error was reported
![image](https://user-images.githubusercontent.com/17673134/146736545-f13d984e-ae5d-4053-9f7e-a1df8244b2c9.png)

I tried several ways and failed to compile. LINK (lcudart, lcudadevrt, libcudart.so, libnvrtc.so, libcudadevrt.a)
I saw in cudf that you have written the __syncthreads() function in the cuh file.(eg.https://github.com/rapidsai/cudf/blob/31f92d70bdf5b80434d24b6883e45496dbe85042/cpp/src/io/utilities/block_utils.cuh#L160
) 
can you tell me how did you compile it, what settings are there, or what header files are cited? Can you help me?

**Comment by beckernick** [comment]
Hi @lixiaolx , could you please share a small, reproducible example of a CUDA kernel with __syncthreads you've tried to compile and the error?
