### ISSUE TITLE
[BUG] cudftestutil leaks compile options

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#9952]
**Describe the bug**
https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/CMakeLists.txt#L618-L621

This passes on the compile options to any project that is using it which includes the `-Werror` that we use. Should probably just flip it to PRIVATE.

**Comment by harrism** [comment]
@robertmaynard is this as simple as flipping PUBLIC to PRIVATE?

**Comment by robertmaynard** [comment]
It needs to be:

```cmake
target_compile_options(
  cudftestutil PUBLIC "$<BUILD_INTERFACE:$<$<COMPILE_LANGUAGE:CXX>:${CUDF_CXX_FLAGS}>>"
                      "$<BUILD_INTERFACE:$<$<COMPILE_LANGUAGE:CUDA>:${CUDF_CUDA_FLAGS}>>"
)```

So that C++ test files that cudf builds still get propagated the flags, but external consumers of `cudftestutil` don't get the flags
