### ISSUE TITLE
[BUG] `BUILD_SHARED_LIBS` CMake option doesn't build static library when set to "OFF"

### ISSUE THREAD

**Issue by kkraus14** [rapidsai/cudf#9954]
**Describe the bug**
https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/CMakeLists.txt#L43

This option is not used anywhere in the CMake currently. It should probably be used to parametrize whether `SHARED` or `STATIC` is passed to the `add_library` call here: https://github.com/rapidsai/cudf/blob/branch-22.02/cpp/CMakeLists.txt#L162

**Steps/Code to reproduce bug**
Build libcudf with `-DBUILD_SHARED_LIBS=OFF`.

**Expected behavior**
A static library of libcudf is built with `-DBUILD_SHARED_LIBS=OFF`.

**Comment by ajschmidt8** [comment]
I haven't tried replicating this issue locally, but I was just going over some of our CMake stuff myself and stumbled upon the `BUILD_SHARED_LIBS` option. It seems to be a global flag provided by CMake.

https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by kkraus14** [comment]
Aha, I think I reported this without being able to truly test it because when setting `-DBUILD_SHARED_LIBS=OFF` I run back into #9718.

I'll close this for now and reopen that with more details.
