### ISSUE TITLE
[FEA]The following packages are not available from current channels

### ISSUE THREAD

**Issue by Jobe-Zhong** [rapidsai/cudf#9957]
How to install to mac os ?
![image](https://user-images.githubusercontent.com/95477965/147449674-482393e8-f06c-44c7-8d91-5581b9e8e62a.png)

**Comment by galipremsagar** [comment]
Currently, Apple doesn't allow support for NVIDIA GPUs, for more context : https://discussions.apple.com/thread/250413789?answerId=250793356022#250793356022


Hence due to the lack of support, we cannot publish or either run `cudf` on MacOS.

**Comment by beckernick** [comment]
With the above, I'm going to close this issue as resolved. Please feel free to reopen the issue to continue the discussion.
