### ISSUE TITLE
[FEA] orc file written by cudf doesn't include Column Statistics in RowIndex

### ISSUE THREAD

**Issue by wbo4958** [rapidsai/cudf#9964]
Spark 3.2 has changed the orc dependency to 1.6.11 which has different behaviors with orc 1.5.10 (spark-plugins shaded) when picking row group with filter pushed down.

In a word, Spark 3.2 will **return empty** when reading the orc file written by cudf with filter pushed down which is because of missing Column Statistic in RowIndex.

From the orc spec, Column Statistic of RowIndex seems not to be a required field. But if the orc file didn't include Column Statistic in RowIndex, the spark will get incorrect result.

**Comment by revans2** [comment]
Is there a bug filed against Spark for this?  It is one thing to work around it in CUDF, which would be nice, but if it really is optional then it is a bug in Spark itself.

**Comment by wbo4958** [comment]
I think it's the ORC issue not a spark issue, I just filed an ORC issue https://issues.apache.org/jira/browse/ORC-1075

**Comment by vuule** [comment]
@wbo4958 can you confirm that `columnStatistics` is not present in `RowIndex`? If that's the case, this is a feature request as we current don't support row group statistics (which are optional). If somehow there is an incorrect value, I will look into fixing that.

Since `columnStatistics` are optional in `RowIndex`, the code should not depend on existence of this field. Maybe stripe statistics can be used instead?

**Comment by wbo4958** [comment]
@vuule, Yeah, columnStatistics is not present in RowIndex. I have filed an issue for the Orc reader. Suppose it is orc reader issue. Thx

**Comment by wbo4958** [comment]
Closed this issue, since the orc file written by cudf is following ORC format. Cudf doesn't have to add statistics in RowIndex.

ORC maintainer has confirmed it's the ORC java issue, and there is a PR pending to review.

**Comment by vuule** [comment]
I think we can keep this open as a feature request. @wbo4958 are you okay with this option?

**Comment by wbo4958** [comment]
sure.

**Comment by vuule** [comment]
Scoped out the feature. Changes required:

1. Encode rowgroup-level stats in the writer (currently they are merged into stripe-level stats and discarded).
2. Include the encoded stats in the row index entries.
3. Enable stats by level (rowgroup, stripe, file, none) in the ORC API (currently a boolean option). This would also make the API consistent with Parquet 👍

**Comment by vuule** [comment]
Both PRs are merged, closing.
