### ISSUE TITLE
[BUG] Reductions are not performed in the output precision.

### ISSUE THREAD

**Issue by bdice** [rapidsai/cudf#9988]
**Describe the bug**
The `cudf::reduce` algorithm takes a parameter `cudf::data_type output_dtype`. The docs state that the reduction (computation) is performed in the output precision:
https://github.com/rapidsai/cudf/blob/7392f9f5f10dc6efb4d21cfcef18a14a0df421c3/cpp/include/cudf/reduction.hpp#L62

However, the computation precision does _not_ match the output precision. The `element_type_dispatcher`'s implementation of `reduce_numeric` casts floating-point values to `double` before performing the reduction. https://github.com/rapidsai/cudf/blob/7392f9f5f10dc6efb4d21cfcef18a14a0df421c3/cpp/src/reductions/simple.cuh#L364-L365

Similarly, `reduce_numeric` casts integral values to `int64_t` before performing the reduction. 
https://github.com/rapidsai/cudf/blob/7392f9f5f10dc6efb4d21cfcef18a14a0df421c3/cpp/src/reductions/simple.cuh#L387-L388

This code should be refactored to match the docs - we _should_ perform computations in the output precision, to avoid overflow and floating-point truncation issues. This invokes UB if the output type is `uint64_t` and the reduction exceeds `INT64_MAX`, for example. The type dispatch on `output_dtype` should be performed at the place where the reduction functor is called, rather than having a type dispatch to (down)cast the results at the end:
https://github.com/rapidsai/cudf/blob/7392f9f5f10dc6efb4d21cfcef18a14a0df421c3/cpp/src/reductions/simple.cuh#L391-L396

This also affects segmented reductions in #9621.

**Comment by isVoid** [comment]
Here's a contrived example to show case the discrepancy:
```c++
TEST_F(OverflowReductionTest, float64)
{
  double const f64 = 0.7654111;
  cudf::test::fixed_width_column_wrapper<double> in{f64, f64};
  cudf::data_type output_dtype{cudf::type_id::FLOAT32};

  float const expected = static_cast<float>(f64) * static_cast<float>(f64);
  auto const result    = cudf::reduce(in, cudf::make_product_aggregation(), output_dtype);

  EXPECT_EQ(expected, static_cast<cudf::numeric_scalar<float>*>(result.get())->value());
}
```

In general, we shouldn't compare "equality" to two floating point numbers, but I'd argue here we actually should because we want to show the result of a simple floating point operation actually match up in exact.

**Comment by bdice** [comment]
Discussed with @davidwendt. We will fix this by addressing two parts:
- Unsigned types will use an uint64 accumulation type (`ResultType`)
- Docs will be updated to indicate that reductions are performed in int64/uint64/double precision, rather than the precision of the input types or the requested output type.

We decided the minimal reproduction of a problem with floating point error above (https://github.com/rapidsai/cudf/issues/9988#issuecomment-1007709523) is not a major problem, but we could address it in the future (if needed) by adding an explicit specialization for `float32` types.

**Comment by bdice** [comment]
The code for segmented reductions should be updated according to the plan above, as well. Then we can eliminate these TODOs:
- https://github.com/rapidsai/cudf/blob/d24bf11838863739da014d828156e8bf638430ff/cpp/src/reductions/simple_segmented.cuh#L417
- https://github.com/rapidsai/cudf/blob/d24bf11838863739da014d828156e8bf638430ff/cpp/src/reductions/simple_segmented.cuh#L437
